### ISSUE TITLE
Feature: Implement back/forward touch gestures

### ISSUE THREAD

**Issue by quantumfrost** [files-community/Files#100]
Would be nice to have horizontal overscroll touchpad gestures for going back and forward, like in Chrome and Edge.

**Requirements**
- Swiping left/right navigates backwards or forwards.
- Works with touchpad gestures
- Works with touch screen gestures

**Comment by quantumfrost** [comment]
Also, do you know if the Windows API allows custom touchpad gestures? That is, can you intercept raw finger location data and process it in your own app instead of passing it to the OS?

**Comment by duke7553** [comment]
If you mean the UWP, then I would have to check.

**Comment by yaichenbaum** [comment]
I have spent some time looking into this and it is definitely possible, I already got a touch screen gesture to navigate back and forward. I to get touchpad gestures working as well in the future.

**Comment by NitrusOxide** [comment]
Are we talking like a touchpad Geusture...? Or a button like Win 10 File explorer?

**Comment by NitrusOxide** [comment]
> touchpad/touch screen. It say in the requirements of the issue.

Ok. I ask because: 1) I'm new to this place. 2) I know a little HTML to where I could do something to make a back button. 
BUT, does anyone know any Javascript commands to encode in an HTML website (for testing) that would involve taking commands from the touch pad/touchscreen?

**Comment by Josh-65** [comment]
Files isn't a web site. Its Winappsdk (xaml for UI, C# for code/functions)

**Comment by NitrusOxide** [comment]
Oh, man I'm stupid. Sorry bout that! I thought we were talking similar-to-google-drive type stuff. But Ok. Am I allowed to contribute in HTML files? If so, I might, _maybe_, be able to do something. I think I'll try to do some C# coding to help. I'd really like to use a new kind of file explorer!

**Comment by Josh-65** [comment]
Files doesn't have any HTML content as far as I know.

**Comment by NitrusOxide** [comment]
Alright. I'll leave you alone now. Thanks for the info, though!

**Comment by heftymouse** [comment]
Can I be assigned to this?

**Comment by yaira2** [comment]
@quantumfrost thank you for your feedback, we're currently working on implementing this feature.
