### ISSUE TITLE
Feature: Horizontal scroll with shift

### ISSUE THREAD

**Issue by DovieW** [files-community/Files#10006]
### What feature or improvement do you think would benefit Files?

It would be nice if you could scroll horizontally with the regular vertical scroll wheel while holding shift.
It's pretty standard across apps it seems.
Just checking now, VS Code and Chrome have this.

### Requirements

- While holding shift and scrolling with a vertical scroll wheel, Files window should scroll horizontally in all instances where a horizontal bar would show

### Files Version

Version: 2.3.11.0

### Windows Version

OS Version: 10.0.22000.978

**Comment by yaira2** [comment]
Related: https://github.com/microsoft/microsoft-ui-xaml/issues/877
