### ISSUE TITLE
无法新建文件夹

### ISSUE THREAD

**Issue by chongchong2501** [files-community/Files#10009]
### Description

新建文件夹让输入文件夹名，设置名称是灰色的

### Steps To Reproduce

1.右击新建文件夹
2.键入文件夹名
3.设置名称无法点击

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

版本: 2.3.11.0 OS Version: 10.0.22622.590

### Windows Version

版本	Windows 11 家庭中文版 版本	22H2 安装日期	‎2022/‎9/‎2 操作系统版本	22622.590 体验	Windows Feature Experience Pack 1000.22634.1000.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9593336/debug.log)
[debug.log](https://github.com/files-community/Files/files/9593348/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9593350/debug_fulltrust.log)

**Comment by hez2010** [comment]
Known issue with IME, merge with #9301.
To workaround the issue you can type an arbitrary english letter and delete it, then the button will become available.
