### ISSUE TITLE
Feature: Adjust spacing based on input method

### ISSUE THREAD

**Issue by VasigaranAndAngel** [files-community/Files#10002]
### What feature or improvement do you think would benefit Files?

I wish for an option to automate the compact style switch. When I use touch, the Compact style needs to be turned off. and when I do not use touch, the Compact style needs to be turned on. Like in the windows 11 context menu. it will be very useful.

## Steps to follow

- Remove the existing option to use compact spacing in the details layout
- Add a new drop-down menu with the label "Spacing" with three sub items
   - Automatic (this should be the default option), this option switches to compact style on mouse/pen input and to regular with touch input.
   - Regular uses the more spaced-out styles.
   - Compact uses tighter spacing styles.
 - Add documentation page to website repo detailing the differences between the options

### Files Version

Version: 2.3.11.0

### Windows Version

Windows 11 21H2 22000.978

**Comment by yaichenbaum** [comment]
Do you think it would be confusing to have the sizes automatically change when the user touches the screen? The context menu is a little different because you don't actually see the size changing.

**Comment by VasigaranAndAngel** [comment]
https://user-images.githubusercontent.com/72515046/190857514-d4028a52-a853-4697-b81c-a8e97772c290.mp4

Sometimes it would be confusing. but it can be made a bit smarter.
1. The changes must happen only when the files app is focused.
2. The file which is pressed or touched must be in the same place and the other contents have to go away as the size changes.

**Comment by yaichenbaum** [comment]
That looks like it might work, we'll approve this issue and do some testing.

**Comment by yaichenbaum** [comment]
Should pen input be treated as touch or mouse?

**Comment by VasigaranAndAngel** [comment]
> Should pen input be treated as touch or mouse?

It should be treated as a mouse because pen accuracy is the same as mouse accuracy. It would be better if there was options in the settings to choose the spacing for pen, touch and mouse.

**Comment by yaichenbaum** [comment]
I updated the requirements in the issue to include the pen feedback, I think we have the requirements figured out but please continue sharing feedback.

**Comment by yaira2** [comment]
Thank you for your feedback, we don't have plans to implement this now, but we'll keep this feedback in mind.
