### ISSUE TITLE
Thumbnails for 3D files such as OBJ and FBX (Space Thumbnails?)

### ISSUE THREAD

**Issue by mickterio** [files-community/Files#10010]
### What feature or improvement do you think would benefit Files?

It would be great to enable thumbnails for 3D files such as OBJ and FBX. 

Space Thumbnails (https://github.com/EYHN/space-thumbnails) already does that for the File Explorer, so maybe the feature could be implemented through collaboration :)

### Requirements

- Adding support for OBJ thumbnails
- Adding support for FBX thumbnails

### Files Version

2.3.11.0

### Windows Version

Windows 22622.290

**Comment by Josh-65** [comment]
Merging with #9523
