### ISSUE TITLE
Shortcut icons are not showing

### ISSUE THREAD

**Issue by Flying-Ass** [files-community/Files#10018]
### Description

Shortcut icons are not showing properly:

Here is a picture of the problem:
![image](https://user-images.githubusercontent.com/113554764/191123570-e3827605-75fd-472b-976d-7bc754e5cde1.png)

I removed the shorcut boxes for windows using registry as mentioned here, which may have caused the problem: https://winaero.com/remove-shortcut-arrow-overlay-in-windows-10/

### Steps To Reproduce

- Go to any dictionary that includes shortcuts

### Steps to fix

- Fix shortcut icons appearances

### Files Version

Version: 2.3.11.0 OS Version: 10.0.22000.978

### Windows Version

Windows 11 Pro 21H2 22000.978

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9602523/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9602524/debug_fulltrust.log)

**Comment by Flying-Ass** [comment]
I didn't try. I was hoping that you can solve this problem happening without shortcut boxes. Similar problems mentioned at #8166 #8591 #2581 and closed due to lack of response.

**Comment by yaichenbaum** [comment]
Let's keep this opened as it's a confirmed issue, this isn't a fix but we are working on making the overlays smaller so that the regular thumbnail is easier to see.

**Comment by Flying-Ass** [comment]
I just want to mention that, even if you remove the shortcut overlays complately in Files, people would still use registry method in order to keep their desktops look cleaner and that still may cause the same problem. Therefore a fix around this method would be appreciated.

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by yaira2** [comment]
I'm not able to repro this in the latest preview but if it's still an issue, let us know and we'll take another look.
