### ISSUE TITLE
Shortcut icons not showing 

### ISSUE THREAD

**Issue by Flying-Ass** [files-community/Files#10017]
Here is a picture of the problem:
![image](https://user-images.githubusercontent.com/113554764/191117417-4daae8e8-cafa-4091-8cba-4aaa8ec229e4.png)

I removed the shorcut icons for windows using registry as mentioned here, which may cause the problem: https://winaero.com/remove-shortcut-arrow-overlay-in-windows-10/
I tried using WinAero aswell but it didn't work.

This issues had similar problems but closed due to lack of information: #8166 #8591 #2581

**Comment by Josh-65** [comment]
Please reopen using the bug report template
