### ISSUE TITLE
Close new tab content scroll animation

### ISSUE THREAD

**Issue by JoyPanda** [files-community/Files#10019]
### What feature or improvement do you think would benefit Files?

Is it possible to close the new tab window's content scroll animation? When i create a new tab or switch to a tab, the content in the target tab will play a scroll animation, it's a little boring. Thanks for your reply!

### Requirements

- This proposal will improve the express

### Files Version

2.3.11.0

### Windows Version

OS Version: 10.0.19044.1826

**Comment by Josh-65** [comment]
I presume everything when it quick scrolls and fades from the bottom to its position
