### ISSUE TITLE
Feature Request - RoseBox theme 

### ISSUE THREAD

**Issue by t3dium** [files-community/Files#10027]
### What feature or improvement do you think would benefit Files?

Since I think a rosebox (and possibly an acrylic rosebox) theme on this app would look very nice:

website which contains hex codes: <https://kraxen72.github.io/rosebox/>

some demo pictures for reference:

libreddit:
![image](https://user-images.githubusercontent.com/83690012/191329726-7825b6a6-738a-4fa8-9b40-3c6651a5783f.png)

Obsidian with typewriter dark theme
![image](https://user-images.githubusercontent.com/83690012/191328980-60ebcca9-53f7-4b09-a1e1-815fbdca7452.png)

### Requirements

.

### Files Version

2.3.11

### Windows Version

10 21h2

**Comment by yaichenbaum** [comment]
Thank you for your feedback, please see our documentation on creating custom themes https://files.community/docs/configuring/custom-themes
