### ISSUE TITLE
Copy/Paste in a network directory

### ISSUE THREAD

**Issue by alexcamponogara** [files-community/Files#10030]
### Description

When i try to copy and paste from in a local directory to a remote directory it creates two folders with the same name where the first folder is empty and the second is with files 

![Immagine 2022-09-21 133017](https://user-images.githubusercontent.com/114073465/191493140-8ef17406-0e8a-450f-9ccb-6dd471cec875.png)

New is empty
and New - Copia is with files in

### Steps To Reproduce

1. Copy one local folder
2. Open a Network folder 
3. Paste the selected local into the network
4. Two folders created with the same name 

### Steps to fix

Copying the folder should be working creating only one folder with files in it

### Files Version

Version 2.3.11.0 OS Version: 10.0.22000.978

### Windows Version

Windows 11 Pro 21H2 22000.978

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9616208/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9616209/debug_fulltrust.log)

**Comment by gave92** [comment]
Merging with #9628
