### ISSUE TITLE
Sub settings option dont have icons

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#10034]
### Description

![image](https://user-images.githubusercontent.com/26977075/191602311-fa3fdd78-4ba0-41da-910d-c518a126fd22.png)

### Steps To Reproduce

1. Open settings
2. Open any subsetting via header

### Steps to fix

- Add icons to subsetting items

### Files Version

2.3.36.0

### Windows Version

10.0.19043.1899

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9620089/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9620090/debug_fulltrust.log)

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
This is by design

**Comment by Josh-65** [comment]
It looks quite weird. Is there some issue with them being added?

**Comment by yaichenbaum** [comment]
They were removed when we went for the compact sub items, the icons didn't look good like that.
