### ISSUE TITLE
black boxes

### ISSUE THREAD

**Issue by mohamed2991** [files-community/Files#10032]
### Description

black boxes on folders icon in first start of the app
![Screenshot 2022-09-21 182133](https://user-images.githubusercontent.com/36738116/191544774-4c80099b-41c4-401f-ab24-ba799052f92f.png)

### Steps To Reproduce

first start of the app

### Steps to fix

open any folder and go back then folders back to normal shape
or just close app and reopen

### Files Version

Version: 2.3.11.0 OS Version: 10.0.22622.575

### Windows Version

Windows 11 Pro Version	22H2 Installed on	‎7/‎25/‎2022 OS build	22622.575  Windows Feature Experience Pack 1000.22634.1000.0

### Relevant Assets/Logs

![Screenshot 2022-09-21 182133](https://user-images.githubusercontent.com/36738116/191546176-4b55bca2-501b-4f70-81b8-e03239f82fcc.png)

**Comment by Josh-65** [comment]
Merging with #6373
