### ISSUE TITLE
Tag column and menu.

### ISSUE THREAD

**Issue by GitHubkaede** [files-community/Files#10049]
### What feature or improvement do you think would benefit Files?

The right-click menu software has no icon, such as "Winrar"
![snipaste_20220923ww174453](https://user-images.githubusercontent.com/34001186/191934834-36f9f904-f413-433d-a38c-2380e16c4c7c.png)

### Requirements

I hope to be able to drag and move freely, "Tag column, Size column, Type column" and can be set globally by default.

I hope the right-click menu can select the WIN11 menu or the classic traditional menu, which is fatal to my habit, so I can't use files for a long time.

The use of it is very good, I hope it can be better.

### Files Version

2.3.12.0

### Windows Version

Windows 22H2 22621.521

**Comment by Josh-65** [comment]
Merging with #3834
