### ISSUE TITLE
Bug: Open With menu doesn't work when Files is set as the default file manager.

### ISSUE THREAD

**Issue by lazerl0rd** [files-community/Files#10045]
### Description

After setting Files as the default file manager (either via the toggle or by following the instructions at https://github.com/files-community/Files/issues/9149#issuecomment-1126821256), the "Open With" menu seems to no longer function.

### Steps To Reproduce

1. Install the Files app.
![image](https://user-images.githubusercontent.com/24303423/191845695-2d019254-c49a-4f82-94a0-e450422e1304.png)

2. Set it as the default file manager via the Settings menu.
![image](https://user-images.githubusercontent.com/24303423/191845505-b9d8ed74-d6c2-4b80-9a3f-5c034833f3dd.png)

3. Right-click any file and press "Open With". If there is a sub-menu, then select "Choose another app".
![image](https://user-images.githubusercontent.com/24303423/191845432-7b6d754a-1dd4-4ced-92e0-c7af91598266.png)
or
![image](https://user-images.githubusercontent.com/24303423/191845457-a23690cc-1be9-45ec-bcf7-f720ca3ed4c0.png)

4. Nothing happens.

### Steps to fix

- Allow "Choose another app"/"Open With" requests to go through to Windows Explorer (assuming that is the package that handles it).

### Files Version

Version: 2.3.11.0 OS Version: 10.0.22622.598

### Windows Version

Windows 11 22H2 22622.598

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9629271/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9629272/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
Are you using an insider build? Doesn't work on certian insider builds as Microsoft broke some stuff.
