### ISSUE TITLE
Context menu - add a button to access the context menu, as well as right click (or add to Options menu) to 

### ISSUE THREAD

**Issue by andyfmidd** [files-community/Files#1004]
To me, a UWP program should not use "right click" Do others?
It is awkward on a touch screen/logical keyboard.
I get that the desktop version does, and have no problem with right click remaining. I just feel the options should be available by either the options menu or a button.

Add a button near the + ("create new item" button (navigation line), to get the menu?

On the same concept, could also add a dedicated properties button too.

**Comment by Jaiganeshkumaran** [comment]
Instead of having a button next to the + button, why not have the context menu options in the triple-dot menu?

**Comment by yaichenbaum** [comment]
@andyfmidd We don't plan on implementing this specific change, but we are looking into alternative ways to access these options outside of the context menu.
