### ISSUE TITLE
Opening downloads folder sorted and grouped by date created opens on "This year" instead of "yesterday"

### ISSUE THREAD

**Issue by potatohub741** [files-community/Files#10047]
### Description

When opening my downloads folder that I have sorted by date created and grouped also by date created, it opens in a position with "This year" as the grouped heading, which then requires me to scroll all the way up to see my latest downloads. I have tried different combinations of sorting and grouping by date created, date modified, and altering the ascending and descending options to no avail.

### Steps To Reproduce

1. Set "Sort By" to "Date Created"
2. Set "Group By" to "Date Created"
3. Navigate to a different folder other than downloads (e.g. the Home folder)
4. Navigate back to downloads
5. You will see your scroll position has been navigated so that the "This year" group heading is at the top of the visible folder space.

### Steps to fix

- Add an option to reset or disable any saved scroll positions when opening any folder in the settings?
- Add an option to scroll to the top of a folder upon opening

### Files Version

Version: 2.3.11.0 OS Version: 10.0.22000.856

### Windows Version

Windows 11 Pro 21H2 22000.856

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9630619/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9630620/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
Merging with #6186 (issue applies to all group options)
