### ISSUE TITLE
Open new tab or window on the same desktop

### ISSUE THREAD

**Issue by cekkr** [files-community/Files#10050]
### What feature or improvement do you think would benefit Files?

When it's in use the multi-desktop feature and you open a directory on the explorer, Files use to change desktop on the last window used. Instead, it should open the tab (or window) on the same desktop.

Thank you!

### Requirements

- Open tab/window on same desktop

### Files Version

Version: 2.3.11.0 

### Windows Version

Win 11 OS Version: 10.0.22621.521

**Comment by princesingh04** [comment]
hey can you assign this task to me?

**Comment by Josh-65** [comment]
Merging with #7603
