### ISSUE TITLE
Allows it to function normally when in safe mode.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [files-community/Files#10055]
### What feature or improvement do you think would benefit Files?

I was using this till I realized its linked to windows hypervisor and essentially is useless when that visor is down such as when in safe mode.

My desire is to have an alternative to windows explorer.

### Requirements

I have no idea. I am not a coder.

### Files Version

2.0.36.0

### Windows Version

Windows 11 Pro

### Comments

I don't know if this can be done. Since it really is a valuable importance though not sure I will even use the application if I can't use it when the system is having issues. I keep an eye on it though.

**Comment by Josh-65** [comment]
That expected, the whole point of safe mode is to remove all unnecessary programs/drivers.
