### ISSUE TITLE
Sidebar tooltips

### ISSUE THREAD

**Issue by andyfmidd** [files-community/Files#1005]
Adding an item to the sidebar merely adds its name (last element of the full path?).
However, apart from clicking it, its path is unknown (for us with short memories!). Add a tooltip to show full path.
Items with the identical name, but located on a different drive (e.g. NAS) can't be added at the moment. The Desktop explorer allows duplicate names. The tooltip helps identify them.

**Comment by XPoppyX** [comment]
An alternative could be adding "properties" to the context menu of pinned items, or also for the library and drives
