### ISSUE TITLE
双面板视图不生效

### ISSUE THREAD

**Issue by seed-00** [files-community/Files#10063]
### Description

启用双面板视图，重启和打开新标签页都显示为单面板

### Steps To Reproduce

1.多任务点击启用双面板视图和始终以双面板试图打开新标签页
2.刷新、重启、打开新标签皆是单面版

### Steps to fix

1.进入精简模式在退出，就显示双面板（然而每次重启和打开新标签都要重复一遍此动作才会显示双面板）

### Files Version

2.3.11

### Windows Version

W10与W11都普遍出现这个问题

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9639303/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9639304/debug_fulltrust.log)

**Comment by Josh-65** [comment]
Merging with #9701
