### ISSUE TITLE
Right click errors

### ISSUE THREAD

**Issue by zzdts** [files-community/Files#10065]
### Description

版本: 2.3.12.0
OS Version: 10.0.22000.978   
I can't use mouse right click func.  That cause a crash. 

### Steps To Reproduce

1 Go to disk fold .
2 right click at any item ,a file or a fold , then crash caused.

 

### Steps to fix

- eg. Fix crash that occurs when right click

### Files Version

Version 2.3.12.0 OS Version: 10.0.22000.978   

### Windows Version

Win 11 21H2  22000.978

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9640167/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9640168/debug_fulltrust.log)

**Comment by gave92** [comment]
Try to disable the Tags feature in Files Settings.

**Comment by gave92** [comment]
Could you post the contents of this file? `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState\settings\filetags.json"`
