### ISSUE TITLE
Bug: Dragging an item select hovered folders

### ISSUE THREAD

**Issue by ferrariofilippo** [files-community/Files#10068]
### Description

When you drag around an item in `DetailsLayout` and you hover a folder, the latter is selected.
I think this may happen because of the `Selection-Rectangle`, which is enabled whenever you press the pointer and then move the mouse.

### Steps To Reproduce

1. Select an item in `DetailsLayout`
2. Drag it around, hovering other folders
3. See how these folders get selected

### Steps to fix

.

### Files Version

Version: 2.3.28.0 OS Version: 10.0.22000.1042

### Windows Version

Windows 11 Home 21H2 22000.1042

### Relevant Assets/Logs

https://user-images.githubusercontent.com/102259289/192319346-e0702651-b3cb-4cad-97f4-58dfcb4e41e4.mp4

**Comment by Josh-65** [comment]
I presume this is the same as #6768

**Comment by ferrariofilippo** [comment]
Oh yes, I hadn't seen it
