### ISSUE TITLE
Bug: Closing banners leads to Files crash

### ISSUE THREAD

**Issue by ferrariofilippo** [files-community/Files#10069]
### Description

Sometimes, when you close a `Result-Banner` by clicking on the `X` button, Files crashes because of an unhandled exception.
On my computer, this happens around half the time I close banners that way.
Edit: we should check if banners exist before removing them programmatically (if you close progress banners, Files crashes).

### Steps To Reproduce

1. Execute an operation that creates a `Result-Banner`
2. Close the banner using the `X` button
3. See that occasionally Files crashes

### Steps to fix
- Resolve crash

### Files Version

Version: 2.3.28.0 OS Version: 10.0.22000.1042

### Windows Version

Windows 11 Home 21H2 22000.1042

### Relevant Assets/Logs

![2](https://user-images.githubusercontent.com/102259289/192320005-0155e513-efba-4560-aec2-026690a82711.png)
![3](https://user-images.githubusercontent.com/102259289/192320040-b28cf5d0-7529-4a04-979b-573455b8d21d.png)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9647733/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/9647734/debug.log)

**Comment by yaichenbaum** [comment]
Do you want to work on this?

**Comment by ferrariofilippo** [comment]
I tested it again and the problem seems to be fixed
