### ISSUE TITLE
Bug: Poor thumbnail quality in the grid layouts

### ISSUE THREAD

**Issue by BiosNod** [files-community/Files#10067]
### Thumbnail DPI problem

I have a 2560x1440 monitor, in the new explorer (Files) I see poor preview quality of any types of files (some blur) but in the old default explorer I see a good and clear image of the preview. Is there any option to corrects this? Something like a pixel density set for a preview? This problem is manifested using "large icons mode"

### See the screenshot:

1 - new file explorer (Files) - very bad blur
2 - old file explorer (Default Win 10 explorer) - very good sharp

![Annotation 2022-09-26 131617](https://user-images.githubusercontent.com/16207244/192253104-a017ccb4-62e8-4877-8b86-9d22852cb907.jpg)

Because of this problem I don't want to switch to a new file explorer just yet =( Many thanks in advance for the future

### Requirements

- Display sharp thumbnail as expected

### Files Version

2.3.12.0

### Windows Version

Windows 10 21H2, build 19044.1288

**Comment by yaichenbaum** [comment]
We can resolve this issue by using the `UseCurrentScale` option, the downside is that this would replace the `ReturnOnlyIfCached` option.

**Comment by yaichenbaum** [comment]
https://github.com/files-community/Files/pull/10105 includes some improvements for thumbnail sharpness but I think there is still room for improvement.

**Comment by Hyrules** [comment]
I have this issue as well i'm using Files 3.0.15.0 and the files are not on onedrive but a secondary nvme drive. Here is a screenshot of the issue : 

![image](https://github.com/files-community/Files/assets/3161577/b172fd55-c6e7-413b-b119-eb8563df022f)

To reproduce I just have to open a folder with images for the first time and then some of the thumbnails are blurry and not full resolution. If I press F5 to refresh the screen the thumbnails then load properly. This does not happen in a folder where the thumbnails have already been loaded.

**Comment by BiosNod** [comment]
> I have this issue as well i'm using Files 3.0.15.0 and the files are not on onedrive but a secondary nvme drive. Here is a screenshot of the issue :
It seems another issue with sharpness о.O ... It seems you have a super low resolution in big resolution photos? On my monitor I don’t even need to try to repeat this - it’s like this on any previews

**Comment by Hyrules** [comment]
THese photos are not super high resolution but this happens with any types of photo in any photo folder.

I can also add the following if it might help diagnosing the issue : I'm using 4k monitor with125% scaling 

![image](https://github.com/files-community/Files/assets/3161577/380cf990-9fac-4839-a066-9e3d1debf94a)

**Comment by yaira2** [comment]
It's less to do with the image resolution and more to do with the way thumbnails are fetched in Files. There is a way to fix this issue, we just haven't yet figured out how...

**Comment by yaira2** [comment]
This issue should be resolved in the next release
