### ISSUE TITLE
Bug: Files crashes due to unhandled exception

### ISSUE THREAD

**Issue by ferrariofilippo** [files-community/Files#10066]
### Description

Sometimes, when opening Files, the program crashes because of an unhandled exception.
The problem is that a `DriveItem` (usually `C:`) is loaded twice, raising the exception.
It's not the first time I have had this issue (first time was some 10 days ago), but it seemed to work after restarting Files

### Steps To Reproduce

.

### Steps to fix

- Before adding a `DriveItem` check if it already exists
- Add a Try-Catch to manage the exception

### Files Version

Version: 2.3.28.0 OS Version: 10.0.22000.1042

### Windows Version

Windows 11 Home 21H2 22000.1042

### Relevant Assets/Logs

![1](https://user-images.githubusercontent.com/102259289/192162128-06a90a49-87f6-44fd-9a83-0d73811af78e.png)

**Comment by yaichenbaum** [comment]
@ferrariofilippo is this still an issue?

**Comment by ferrariofilippo** [comment]
> @ferrariofilippo is this still an issue?

This hasn't happened since then
