### ISSUE TITLE
Transparency support for webp images

### ISSUE THREAD

**Issue by p-yukusai** [files-community/Files#10060]
### What feature or improvement do you think would benefit Files?

I'm unsure of this being a bug or not, but since it only seems to consistently happen with webp images, I will assume it's just not implemented.
Currently Files will show a dark background in place of the transparency of the image, which is weird since transparency for this file format works flawlessly in the preview pane.

### Requirements

- Make transparency work for thumbnails of webp images in the same way as it works for the preview pane.

### Files Version

Version: 2.3.12.0

### Windows Version

Windows 11 21H2 (OS Build 2200.1042)

### Comments

Thumbnail
![image](https://user-images.githubusercontent.com/85849071/192107812-53c68f7d-a12b-4c84-887e-11dab1dee473.png)
Preview pane
![image](https://user-images.githubusercontent.com/85849071/192107784-be4da48e-cd47-469f-a83b-0b668dcf1a7b.png)

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by p-yukusai** [comment]
Yes, nothing has changed by using the current preview version (Version: 2.3.49.0)

**Comment by yaira2** [comment]
This appears to be resolved in the latest preview build.
