### ISSUE TITLE
Files App freezes when changing windows desktop background

### ISSUE THREAD

**Issue by Himankan** [files-community/Files#10079]
### Description

When files window is open and I right click on desktop to select 'Next Desktop Background', the Files app completely freezes.
It most commonly happens with folders with lots of files or media.

### Steps To Reproduce

1. Open a folder with lots of files, say `C:/Windows`
2. Keep Window opened while changing background image as follows
3. ![image](https://user-images.githubusercontent.com/26485723/193061230-ee0fc84a-f43e-4ec2-89e0-46449fbad3a8.png)
4. Now go back to the folder and the folder stops responding
5. Sometimes the entire app crashes

### Steps to fix

-Fix app crash that occurs when changing desktop background
-Fix freezing of opened window when changing desktop background

### Files Version

Version: 2.3.12.0 OS Version: 10.0.19044.2075

### Windows Version

Edition	Windows 10 Home Single Language Version	21H2 Installed on	‎31-‎03-‎2021 OS build	19044.2075 Experience	Windows Feature Experience Pack 120.2212.4180.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9675697/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9675698/debug_fulltrust.log)
![image](https://user-images.githubusercontent.com/26485723/193061230-ee0fc84a-f43e-4ec2-89e0-46449fbad3a8.png)

**Comment by yaichenbaum** [comment]
This is a Windows issue unfortunately but the good news is that Microsoft improved this behavior on Windows 11.
