### ISSUE TITLE
JPEG 2000 thumbnails

### ISSUE THREAD

**Issue by patrik-krajcovic2** [files-community/Files#10073]
### What feature or improvement do you think would benefit Files?

I want Files to show JPEG 2000 thumbnails, because I am going to convert my entire library to JPEG 2000 and Files won't showing thumbnails.

### Requirements

Add support for JPEG 2000 thumbnails

### Files Version

2.3.11

### Windows Version

Windows 11 22H2

**Comment by Josh-65** [comment]
Can you try the preview build as it should be fixed there https://files.community/download/preview

**Comment by yaichenbaum** [comment]
What program are they set to open in?

**Comment by yaichenbaum** [comment]
A screenshot would be helpful

**Comment by patrik-krajcovic2** [comment]
![Files preview screenshot](https://user-images.githubusercontent.com/69351811/192944711-a3728c38-58d9-4b2a-9d1c-27d143708388.png)

**Comment by yaichenbaum** [comment]
What's the result in File Explorer?

**Comment by patrik-krajcovic2** [comment]
It's same

**Comment by yaichenbaum** [comment]
Same issue? This should be reported to IrfanView.

**Comment by patrik-krajcovic2** [comment]
XnView has same issue

**Comment by patrik-krajcovic2** [comment]
I tried every app to open JPEG 2000 but nothing generated thumbnails.

**Comment by yaichenbaum** [comment]
Thumbnails need to be generated by the app the file is associated with. I recommend putting in a feature request with IrfanView or a similar app.
