### ISSUE TITLE
Installation Troubles

### ISSUE THREAD

**Issue by Djtpj** [files-community/Files#10074]
### Description

I cannot install the application. Every time I try, something goes wrong. For example, when I try to install from the Microsoft Store I click the button and it rolls the installing wheel forever, the install button goes gray and nothing happens, or the app freezes and nothing happens. I have also tried the side loader, and the install button slightly changes color, and then the app freezes.

I have tried nearly every single solution that I could think of, or have found online

### Steps To Reproduce

1. Go to Microsoft Store
2. Search for "files app"
3. Open the Files page
4. Click the install button
5. Scream at your computer because you've been trying to get this to work all day

### Steps to fix

I literally just want to install the app

### Files Version

I do not have a version, as I cannot install the app

### Windows Version

The newest version of Windows 11 as of 9/28/22

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/93952263/192926351-e7c7ee39-0f91-49a2-ba87-1ad7566a3d40.png)
Frozen Microsoft Store install page

![image](https://user-images.githubusercontent.com/93952263/192926362-ca044328-f0aa-4021-9a8d-57a798b2f112.png)
Frozen side loader

**Comment by yaichenbaum** [comment]
Is this an issue with any other app in the Store?

**Comment by Djtpj** [comment]
Nope, I appear to be able to install other apps.

**Comment by Djtpj** [comment]
So, update after some testing: it does seem to be an issue with Spotify, and everything froze once again. It also seems that I cannot click any of the buttons that come from the account drop down in the top right without freezing Microsoft Store. I have no idea why Store has decided to be so difficult, and I am now researching what could be the cause behind that.

**Comment by Djtpj** [comment]
Had to restart the service for some reason, just followed [these steps](https://answers.microsoft.com/en-us/windows/forum/all/microsoft-store-keeps-freezing/5d3ec42a-fd97-43e3-9c42-f09d13b69cf2)

Looking forward to getting use this app!
