### ISSUE TITLE
i keep getting an error "installation failed ask developer for dependencies"

### ISSUE THREAD

**Issue by Luqmaan2** [files-community/Files#10076]
### Description

![image](https://user-images.githubusercontent.com/73324519/193028633-479c7d45-948a-4811-84e5-54a646676121.png)

### Steps To Reproduce

release the dependencies

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

19042.630

### Windows Version

windows 10 20h2

### Relevant Assets/Logs

null

**Comment by Josh-65** [comment]
Install from https://files.community/download/stable

**Comment by yaichenbaum** [comment]
@Luqmaan2 does the install work from here? https://files.community/download/stable
