### ISSUE TITLE
About "drag"

### ISSUE THREAD

**Issue by Leoijeon** [files-community/Files#10088]
### Description

1. drag files from Files app always don't like what we used to do in windows explorer, you can't directly drag files to open it in another app, you can't drag it to web explorer to upload files (just like uploading debug.log file now), and drag files to desktop will always ask you want to move or copy.......
2.  if I open the setting, the whole Files app won't be move

### Steps To Reproduce

1. drag files to open it in another app or desktop
2. drag the Files app when opening settings

### Steps to fix

Fix drag file to another app or desktop

### Files Version

Version: 2.3.12.0 OS Version: 10.0.19044.2006

### Windows Version

Windows 10 Pro Version	21H2 OS build	19044.2006

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/9680261/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/9680262/debug.log)

**Comment by yaichenbaum** [comment]
> drag files from Files app always don't like what we used to do in windows explorer, you can't directly drag files to open it in another app, you can't drag it to web explorer to upload files (just like uploading debug.log file now)

This works fine on my end, can you specify which app you're dragging to?

**Comment by Leoijeon** [comment]
> > drag files from Files app always don't like what we used to do in windows explorer, you can't directly drag files to open it in another app, you can't drag it to web explorer to upload files (just like uploading debug.log file now)
> 
> This works fine on my end, can you specify which app you're dragging to?

I tried today and it works normal, maybe is a special app, or maybe an update that I did a few days ago fixed this problem. If I recall some details I will report it.
