### ISSUE TITLE
About Preview pane

### ISSUE THREAD

**Issue by Leoijeon** [files-community/Files#10087]
### Description

when I use the preview panel to preview pdf files, it will only show one page (not continuous). Another problem is when I click another pdf file, the contents in preview panel won't change until I reopen the preview pane.

### Steps To Reproduce

1. click any pdf files in files
2. open the preview pane
3. click another one

### Steps to fix

Fix the refreshing speed when want to preview another pdf file
Add a previewer handler change options, for AdobeDC, PDF-Xchange, Sumatra or something else.

### Files Version

Version: 2.3.12.0 OS Version: 10.0.19044.2006

### Windows Version

Windows 10 Pro Version	21H2 OS build	19044.2006

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/9680232/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/9680233/debug.log)

**Comment by Josh-65** [comment]
Is this an issue in the preview version? https://files.community/download/preview

**Comment by Leoijeon** [comment]
Installed from Microsoft store. This problem is not happened now. But the refreshing speed is still slow sometimes (not only preview pane but also the file list).

**Comment by Leoijeon** [comment]
This problem is not happened in preview version
