### ISSUE TITLE
Thumbnails of some jpgs, svg files and adobe files are not shown

### ISSUE THREAD

**Issue by ElitePheonix009** [files-community/Files#10092]
### Description

I have jpg files, svg files and adobe files in many folders. Thumbnails of some jpg files (thumbnails of most jpg files are shown), svg files and adobe files (such as .ai, .psd, .xd, etc.) are not being shown and are blank (sometimes it shows and sometimes does not show even after my waiting). If the folder is refreshed, the issue for most of the files is fixed.

### Steps To Reproduce

1) Open any folder containing some jpg files (thumbnails of most jpg files are shown), svg files and adobe files (such as .ai, .psd, .xd, etc.).
2) See that their thumbnails are blank.

![image](https://user-images.githubusercontent.com/94096555/193276777-65342f52-6718-43bd-aa7c-065e5ba46000.png)

### Steps to fix

1) Refresh the folder.
2) See that the thumbnails for most of the file types are now shown.

![image](https://user-images.githubusercontent.com/94096555/193278041-98358669-44e4-458c-86e7-9b39cf0309dd.png)

### Files Version

Version: 2.3.12.0 OS Version: 10.0.19044.2006

### Windows Version

Edition	Windows 10 Pro Version	21H2 Installed on	‎15-‎09-‎2022 OS build	19044.2006 Experience	Windows Feature Experience Pack 120.2212.4180.0

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/9684452/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/9684453/debug.log)

**Comment by yaichenbaum** [comment]
Can you confirm if this issue is resolved in the latest preview build? https://files.community/download/preview

**Comment by verdaderoken** [comment]
Had the same problem in stable version for image files. It looks fixed in the latest preview build

**Comment by DanielWilliams78** [comment]
Thank you for letting me know.
