### ISSUE TITLE
Using 'back' mouse button while in Recycle Bin causes crash if there are many items in Recycle Bin

### ISSUE THREAD

**Issue by deathgrape** [files-community/Files#10093]
### Description

Files crashes if you attempt to go back to the previous directory, while in the Recycle Bin folder and there are items in it.

### Steps To Reproduce

1. Have a recycle bin with several items in it (I can't reproduce it with the Recycle Bin empty)
2. Navigate to some other directory
3. Navigate to the recycle bin using the same tab
4. Use the 'back' mouse button to try to go back to that other directory from step 2
5. Files crashes

### Steps to fix

To fix issue: 

Be able to return to previous directory after going to the Recycle Bin, without needing to have an empty Recycle Bin all the time.

### Files Version

Version: 2.3.12.0 OS Version: 10.0.22621.521

### Windows Version

Windows 11 Pro Version	22H2  OS build 22621.521 	Windows Feature Experience Pack 1000.22634.1000.0

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/9687170/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/9687171/debug.log)

**Comment by Josh-65** [comment]
Are you using column view?

**Comment by deathgrape** [comment]
It's in 'adaptive'.

**Comment by Josh-65** [comment]
Is this an issue in the preview version? https://files.community/download/preview

**Comment by deathgrape** [comment]
Seems like that fixed it!
