### ISSUE TITLE
Deletion of Items on Startpage Collections

### ISSUE THREAD

**Issue by leander-hass** [files-community/Files#10096]
### Description

I use bundles to group directories for quick access on my startpage. I have two bundles with 3-4 directories. When I reopen the Files app sometimes the directories I added to the bundles are not there anymore.

### Steps To Reproduce

1. Create bundle(s) on startpage.
2. Add multiple (larger) directories to the bundle at once.
3. Restart Files app.

### Steps to fix

- eg. large directories may lead to this error (I have multiple thousand files/GB in there)
- eg. cannot reliably add multiple directories to bundles

### Files Version

Version: 2.3.12.0 OS Version: 10.0.19044.2006

### Windows Version

Windows 10 Home 21H2 19044.2006

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9690387/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9690388/debug_fulltrust.log)

**Comment by Josh-65** [comment]
Have you tried tags as bundles are being replace with them. You can right click a folder to add a folder/file to them and edit the name in Files settings > experimental > edit tags

**Comment by leander-hass** [comment]
Im sorry, by collections I meant bundles (I use the app in german). I have not tried tags as bundles. I am currently not using tags in the files app.

**Comment by yaichenbaum** [comment]
We're no longer working on the bundles feature and will eventually be replacing it with a tag's widget.
