### ISSUE TITLE
Enable new shortcut creation in context menu

### ISSUE THREAD

**Issue by Himankan** [files-community/Files#10091]
### What feature or improvement do you think would benefit Files?

- The Add New Shortcut option is missing from context menu. Rt click >New > Shortcut
- We can currently create file shortcuts by clicking on file or folder but not for web addresses (URL).

- Also for some reason we can't click the context menu > New > Folder option when the context menu touches the top edge of screen

![image](https://user-images.githubusercontent.com/26485723/193215129-76a0110d-c596-4d16-a39d-119ad8df3ed7.png)

### Requirements

- The proposal to add the option to create new shortcuts from context menu, both for files and URLs.
- To enable clicking on menu items when context menu reaches top edge of screen

### Files Version

Version: 2.3.38.0 OS Version: 10.0.19044.2075

### Windows Version

Edition Windows 10 Home Single Language Version 21H2 Installed on ‎31-‎03-‎2021 OS build 19044.2075 Experience Windows Feature Experience Pack 120.2212.4180.0

**Comment by yaichenbaum** [comment]
Thank you for your feedback, merging with #1671
