### ISSUE TITLE
新建文件夹名称命名问题

### ISSUE THREAD

**Issue by AisinGioroKiIoi** [files-community/Files#10098]
### Description

在咱的软件中新建文件夹时命名为“2022年某某某项目资料”，点确定后，只有【2022】，后面的内容不显示。望解决，ᠪᠠᠨᡳᡥᠠ（巴尼哈/谢谢）

### Steps To Reproduce

无

### Steps to fix

无

### Files Version

版本： 2.3.12.0 OS Version: 10.0.25211.1001

### Windows Version

版本	Windows 11 專業工作站版 Insider Preview 版本	22H2 安裝於	‎2022/‎9/‎30 OS 組建	25211.1001 體驗	Windows Feature Experience Pack 1000.25211.1001.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9691956/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9691957/debug_fulltrust.log)

**Comment by AisinGioroKiIoi** [comment]
@yair100 您好，这个问题怎么直接关闭了呢？

**Comment by AisinGioroKiIoi** [comment]
@yair100 这个问题已经存在很久了。新建文件夹的时候命名一次，显示错误，然后需要再重新命名。一项工作干两遍，很影响效率的。望解决，ᠪᠠᠨᡳᡥᠠ（巴尼哈/谢谢）

**Comment by AisinGioroKiIoi** [comment]
您好，无法安装软件。

直接安装，报错。

卸载原有的，重启电脑，再安装。错误如下：
![image](https://user-images.githubusercontent.com/52952040/193597213-f4d64875-cea7-4830-ab4a-be806c8b406d.png)

**Comment by AisinGioroKiIoi** [comment]
您好，在【版本： 2.3.42.0
OS Version: 10.0.25211.1001】中，我尝试建了几个文件夹，均正常。ᠪᠠᠨᡳᡥᠠ（巴尼哈/谢谢）

**Comment by yaichenbaum** [comment]
We closed this because the template isn't filled out

**Comment by choicky** [comment]
我遇到相同的问题。我的系统是 windows 11 x64 `22H2` 版。 Files 版本 `2.3.12.0` 的情况下，鼠标右键新建文件夹时，如果文件夹的名字是 `yyyymmdd-中文` 形式，创建出来的文件夹名字是  `yyyymmdd-` ，也就是汉字的内容被截断了。

 preview build https://files.community/download/preview 的 Files 正常，即， `2.3.61.0` 的Files 没有出现该问题。
