### ISSUE TITLE
Bug: Using left/right arrow key in column layout crashes app

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#10109]
### Description

Using the left/right arrow key in the column layout to switch between columns crashes the app.

### Steps To Reproduce

1. Switch to the column layout
2. Select a folder
3. Use left/right arrow key to switch between the existing and newly opened column
4. See crash

### Steps to fix

- Fix crash that occurs when using keyboard navigation

### Files Version

v2.3.39

### Windows Version

Windows 11

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9694991/debug.log)

**Comment by ferrariofilippo** [comment]
Shouldn't this be tracked in #9921 ?

**Comment by yaichenbaum** [comment]
I'm not sure if they are the same but at least we have clear steps to reproduce this one.
