### ISSUE TITLE
Feature: Display modal when shortcut file cannot be opened

### ISSUE THREAD

**Issue by verdaderoken** [files-community/Files#10119]
### What feature or improvement do you think would benefit Files?

Currently, there's no dialog for a deleted file when you try to open a shortcut.

This is a minor feature but it helps to make Files more intuitive by giving the user a hint of why it does not work anymore.

Here's what it looks like in Explorer:
![image](https://user-images.githubusercontent.com/88200096/193684147-b73a08cf-7229-4a4f-9f1a-d56223a029ac.png)

### Requirements

- Display a modal when shortcuts cannot be found
- Ask if the user would like to delete the shortcut
- Add primary button "Delete shortcut"
- Include secondary button to close the modal "No".

### Files Version

2.3.42.0

### Windows Version

10.0.22623.730

**Comment by puppetsw** [comment]
@yair100 I'll take this one on.
