### ISSUE TITLE
Bug: Closing app when menu flyouts are open causes hang

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#10110]
### Description

Closing the app when the right click content menu is still open causes the application to hang for a couple of seconds before it closes.

### Steps To Reproduce

1. Right click on a file or folder
2. Click close button on the title bar
3. Observe that the application hangs for a couple of seconds before closing

### Steps to fix

- Fix hang that occurs when opening the context menu before closing the app

### Files Version

v.2.3.39

### Windows Version

Windows 11

### Relevant Assets/Logs

No crash is detected in the log files

**Comment by yaichenbaum** [comment]
This might be a WinAppSdk issue but it's hard to know.

**Comment by sthivaios** [comment]
I can confirm that this is indeed a bug.


https://user-images.githubusercontent.com/109022579/195944587-a78b772e-c2df-4596-9ea3-7cebdc897fd7.mp4
