### ISSUE TITLE
新建文件夹时命名显示不全

### ISSUE THREAD

**Issue by AisinGioroKiIoi** [files-community/Files#10115]
### Description

在咱的应用中，新建文件夹时，会要求对文件命名，输入“2020-2021_某某某项目”，点【确定】后，只显示【2020-2021】，后面的字符不显示。需要重新对文件夹进行一次命名。对文件夹命名，一项事务处理两边，很影响效率，望解决。ᠪᠠᠨᡳᡥᠠ（巴尼哈/谢谢）

### Steps To Reproduce

如上

### Steps to fix

无

### Files Version

版本： 2.3.12.0 OS Version: 10.0.25211.1001

### Windows Version

版本 Windows 11 專業工作站版 Insider Preview 版本 22H2 安裝於 ‎2022/‎9/‎30 OS 組建 25211.1001 體驗 Windows Feature Experience Pack 1000.25211.1001.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9697919/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9697921/debug_fulltrust.log)

**Comment by Josh-65** [comment]
#10098 Don't make the same issues yair will get to you when he can

**Comment by AisinGioroKiIoi** [comment]
@Josh-65 您好，我在使用过程中遇到了一个问题，进行了反馈（#10098），什么话语都不说，直接把问题关了。我实在不知道这是一个什么意思？是让我重新说明一下吗？
