### ISSUE TITLE
未处理的错误

### ISSUE THREAD

**Issue by AisinGioroKiIoi** [files-community/Files#10128]
### Description

整理文件的时候频繁弹出如下错误提示，应用关闭。
![image](https://user-images.githubusercontent.com/52952040/193745684-1fc913a8-8192-4abb-8d59-0a450d91895f.png)

### Steps To Reproduce

如上

### Steps to fix

未知

### Files Version

版本： 2.3.42.0 OS Version: 10.0.25211.1001

### Windows Version

版本	Windows 11 專業工作站版 Insider Preview 版本	22H2 安裝於	‎2022/‎9/‎30 OS 組建	25211.1001 體驗	Windows Feature Experience Pack 1000.25211.1001.0

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/9703148/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/9703149/debug.log)

**Comment by AisinGioroKiIoi** [comment]
您好，该问题仅作反馈，可能是偶然性问题。不奢求解决。ᠪᠠᠨᡳᡥᠠ（巴尼哈/谢谢）

另，挂载的网络位置，文件移动、粘贴后，还是需要手动刷新之后才能显示。亦仅作反馈，不奢求解决，ᠪᠠᠨᡳᡥᠠ（巴尼哈/谢谢）

**Comment by AisinGioroKiIoi** [comment]
您好，这个问题我没什么步骤可写。就是将文件夹A中的内容剪贴至文件夹B，软件弹出该提示，也没有更多的信息。ᠪᠠᠨᡳᡥᠠ（巴尼哈/谢谢）

**Comment by yaichenbaum** [comment]
Is there a sequence of steps that consistently reproduces the issue? Eg. open a folder and do x...

**Comment by AisinGioroKiIoi** [comment]
没有一系列步骤。就是发生问题那天，文件夹内右键剪贴或者Ctrl+x，到另一个文件夹右键粘贴，或者Ctrl+v。有可能是突发情况。

**Comment by yaichenbaum** [comment]
Does it happen in the grid layouts?

**Comment by sthivaios** [comment]
That doesn't seem to happen to me. @yair100 Is it possible that there are any complications with the chinese translation?

**Comment by yaichenbaum** [comment]
I don't think so, there are some crashes when you use the details layout but it's hard to reproduce consistently.

**Comment by sthivaios** [comment]
Oh, alright.
