### ISSUE TITLE
Very Laggy!

### ISSUE THREAD

**Issue by kevinmorrison** [files-community/Files#10136]
I have disabled a number of features because I am trying to end the lag but no matter how lean I make files it is painfully laggy. I use Everything as my search index and wondering if there might be a conflict between these two? Other than how irritating this app is with the constant hanging on navigation I love what you are doing and this is something that Microcrap could have done long ago if they cared about their users. Would love to continue using this app but if I cant get past this lag issue I am going to have to remove it and wait until a more stable version comes around and it sucks because I am really loving everything else about this app. Anyone else experiencing lag, or am I in my own special bubble?

**Comment by Josh-65** [comment]
Try the preview version https://files.community/download/preview. It probably won't be perfect, but improvements are being made. Any specific issues you can make by following the issue templates.

**Comment by kevinmorrison** [comment]
Thanks Josh, I will give it a go and see if it helps.

**Comment by kevinmorrison** [comment]
Installed it and put it through the paces and it did in fact stop the lag issue I was having!

**Comment by tracer8** [comment]
Files is lag as hell.
Ping me if Files Smooth as ever. I will pay for that!
