### ISSUE TITLE
Cannot revert to explorer after setting Files as default

### ISSUE THREAD

**Issue by whytewolf69** [files-community/Files#10134]
### Description

Reverting back to windows file manager after selecting file manager as default manager when opening windows file manger  and trying to open any drive or file the error application not found. Right click on select open will work. Quick access on left side works
![Screenshot 2022-10-05 234410](https://user-images.githubusercontent.com/35296982/194083600-876da218-9c33-4a75-bd40-d4231cf89ecf.jpg)

### Steps To Reproduce

1. open windows file manager
2. open any drive

### Steps to fix

na

### Files Version

Version: 2.3.12.0 OS Version: 10.0.22000.1042

### Windows Version

Windows 11 Pro Version	21H2 OS Build 22000.1042

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9716334/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9716342/debug_fulltrust.log)

**Comment by Josh-65** [comment]
You can turn off the toggle in Files settings > experimental.

If you have uninstalled files, then open this https://raw.githubusercontent.com/files-community/Files/main/src/Files.FullTrust/Assets/FilesOpenDialog/UnsetFilesAsDefault.reg > right click on the opened page > Save as > set the type to "all files" > remove the .txt from the end of the name > open the file > allow admin when you get the prompt.

**Comment by whytewolf69** [comment]
This does not fix the issue have already turned of File app in Files settings > experimental.
Issue is still present after reverting back to windows file explorer

**Comment by Josh-65** [comment]
Did you do the second method

**Comment by whytewolf69** [comment]
yes

**Comment by Josh-65** [comment]
What modification, scripts or other programmes have you ran on your system. As this probably isn't a Files issue by the screenshot

**Comment by whytewolf69** [comment]
All I have done is install files app and selected it as the default explorer then deselected it reverting back to windows explorer. It worked fine b4 this was done nothing else was done prior to this no scripts

**Comment by Josh-65** [comment]
Try restart Windows if that doesn't change it re-pin the items.

**Comment by whytewolf69** [comment]
Quick access works that is not the issue it is the right side of explorer all drives  and folders on the right

**Comment by FlorentLM** [comment]
I'm having the exact same issue. Checked the option on, it set Files as default, and when I turned it off it made my Explorer like that. Rebooting didn't help, the registry change either

**Comment by Pudding555** [comment]
Same issue...

**Comment by sthivaios** [comment]
I just checked this, and it seems like the issue is gone, at least for me. I am using the preview (PRE) version of "Files", but if I set it as default, and then go back to settings > experimental and then untoggle "Set Files as the default file manager", it reverts back to windows explorer.

- OS : Windows 11 Enterprise EVALUATION  (OS Build : 22621.525)
- App Version : "Files" PREVIEW (PRE)

**Comment by yaichenbaum** [comment]
@whytewolf69 can you try installing the latest version of Files and toggling the option on/off?

**Comment by whytewolf69** [comment]
That is the version I have been using

**Comment by yaichenbaum** [comment]
> https://raw.githubusercontent.com/files-community/Files/main/src/Files.FullTrust/Assets/FilesOpenDialog/UnsetFilesAsDefault.reg

What happens when you open this file?

**Comment by whytewolf69** [comment]
Adding that to the registry does not fix the issue

**Comment by whytewolf69** [comment]
Do you know the issue that I am having

**Comment by yaichenbaum** [comment]
To clarify, we need to know what happens when you open the reg file. Is there an error message, does it say imported successfully?

**Comment by whytewolf69** [comment]
Say imported successfully but I don't think you know the issue that is happening

**Comment by yaichenbaum** [comment]
What happens if you set Files as the default again and try opening a drive from File Explorer?

**Comment by whytewolf69** [comment]
1. I switched to file app as default manager
2. I have now reverted back to windows explorer as default file manager.
3. Windows explorer works as the default manager and Quick access works on the left side of windows explorer and is the only way that windows explorer can be used.
4. When I try to use the right window Payne in windows explorer I get the error message as in screen shot above, when I try to access anything

https://user-images.githubusercontent.com/35296982/195760465-2961cadd-80bd-4096-ab6f-4adc446aed2c.mp4

**Comment by whytewolf69** [comment]
The same will not work

**Comment by whytewolf69** [comment]
If you mean when file app is default the when I use file app it works

**Comment by yaichenbaum** [comment]
I'm wondering if the other modifications on your device are interfering with File Explorer.

**Comment by whytewolf69** [comment]
No there are no other modifications to my computer the issue as only
occurred since file app has been installed

**Comment by Josh-65** [comment]
The screenshots you send clearly show lots/big modification to your Windows install. They don't have to be done after Files one to potentially cause issues. Can you say what programs/scripts you used to get that look on Windows

**Comment by whytewolf69** [comment]
No the only thing that was put on was windows blinds and that was after the
problem had already occurred there's no other modifications on the
computer. Problem was already there before windows blinds was installed.

**Comment by whytewolf69** [comment]
Oh well still no fix

**Comment by Josh-65** [comment]
It's likely an issue with your Window install as those registry changes have worked for everyone else

**Comment by mrfenyx** [comment]
I have the exact same issue. I unchecked the "Set Files as the default file manager" option, it requested Admin elevation, I granted it but nothing changed. From the "normal" Explorer, as soon as I click on any folder inside the actual file/folder list (not Quick Access) it still opens the Files App. I wanted to give the .REG file a try but it is no longer available it would seem (getting a 404).
I'm on version 2.3.12.0 of Files.

**Comment by mrfenyx** [comment]
Maybe also important: the command "%SystemRoot%\Explorer.exe" opens the Files App

**Comment by Josh-65** [comment]
If you open the registry and go to `HKEY_CLASSES_ROOT\Folder\shell\explore\command` send a screenshot of what the window

**Comment by mrfenyx** [comment]
![image](https://user-images.githubusercontent.com/2023454/201623063-45982b52-b0fa-457d-9a90-aa8244c209d5.png)

**Comment by Josh-65** [comment]
what's in the open folder under the explore?

**Comment by mrfenyx** [comment]
![image](https://user-images.githubusercontent.com/2023454/201629499-5ccf0b3f-0ff0-4b77-a3de-c83f6d86d09c.png)
![image](https://user-images.githubusercontent.com/2023454/201629560-f0fc803e-8c7e-47e5-8a7f-032952e32794.png)

**Comment by Josh-65** [comment]
There the same as mine, no idea why it's not opening Explorer. You can try running these in an admin CMD terminal then restart when there finished.
sfc /scannow
dism /online /cleanup-image /restorehealth
