### ISSUE TITLE
When creating a folder, why does clicking the button fail?

### ISSUE THREAD

**Issue by lololololkl** [files-community/Files#10131]
### Description

![image](https://user-images.githubusercontent.com/39233442/193970032-159658e4-bfe0-4194-9adb-ae915fd523dc.png)
When creating a new folder, after typing the name, the "Set Name" button cannot be clicked.

### Steps To Reproduce

1. to create a new folder
2. After typing Chinese folder name
3. can not click the butoon, but English folder name can.

### Steps to fix

Just fix this bug.

### Files Version

2.3.12.0

### Windows Version

10.0.19041.1288

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/39233442/193972915-d00d9453-bd66-43c2-a776-6ac6c1f3940f.png)

**Comment by gave92** [comment]
#9563
