### ISSUE TITLE
Right Click Pinned Options

### ISSUE THREAD

**Issue by kevjustice** [files-community/Files#10133]
### What feature or improvement do you think would benefit Files?

"Ye age old right click menu issue"
Would it be possible to pin right click options from the Win11 "overflow" menu to the main right click menu?  My explorer/overflow right click menu is like 80% of the height on my 4k screen.  I just want 1 or 2 options in the shortened "Files" right click menu.

### Requirements

- Improve productivity
- Still have access to all the right-click "crap"

### Files Version

2.3.12.0

### Windows Version

Windows 11 Pro Version	22H2 Installed on	‎5/‎15/‎2022 OS build	22623.730 Experience	Windows Feature Experience Pack 1000.22636.1000.0

**Comment by Josh-65** [comment]
Merging with #3966
