### ISSUE TITLE
Selecting logs in the about menu does not open log location

### ISSUE THREAD

**Issue by whytewolf69** [files-community/Files#10135]
### Description

Selecting logs in the about menu does not open log location

### Steps To Reproduce

1. go to settings 
2. about
3. click on open log location

### Steps to fix

no fix

### Files Version

Version: 2.3.12.0 OS Version: 10.0.22000.1042

### Windows Version

Windows 11 Pro Version	21H2 OS Build 22000.1042

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9716427/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9716428/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
Is Files set as the default file manager?

**Comment by whytewolf69** [comment]
Not anymore no

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
