### ISSUE TITLE
Cannot connect to default share of remote machines

### ISSUE THREAD

**Issue by Alby11** [files-community/Files#10143]
### Description

Hi everyone! I'm trying to browse a server's default share (e.g.: C$) but nothing is being shown nor errors are thrown.

![image](https://user-images.githubusercontent.com/17138674/194299241-c1c9c974-869c-4fb4-99fd-9766198db8e5.png)

### Steps To Reproduce

1. put the server address in the address bar like: \\servername\c$
2. press enter

### Steps to fix

- no fixes available

### Files Version

2.3.45.0

### Windows Version

Windows 11 22H2 22623.730

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9724386/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9724387/debug_fulltrust.log)

**Comment by Josh-65** [comment]
What is the server type (FTP, SFTP, WebDAV)

**Comment by Alby11** [comment]
> What is the server type (FTP, SFTP, WebDAV)

Hi @Josh-65, it is SMB (Windows Server)

**Comment by Alby11** [comment]
> Do the files show if you map it as a network drive?

Yes! I guess that the problem is due to my regular user, which is not admin of that server.

But with regular file explorer, UAC pops out for credentials. With Files it doesn't.

**Comment by Josh65-2201** [comment]
Is this still an issue in 3.4.1 or above?
