### ISSUE TITLE
Installation stops on MSIXBUNDLE

### ISSUE THREAD

**Issue by SAB236YT** [files-community/Files#10145]
### Description

it gets to 16% and then refuses to move what do i do?

### Steps To Reproduce

???

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

Files 2.3.12.0 x64/amd64

### Windows Version

Windows 10 Pro x64 OS Version 2004 Build 19041.1415

### Relevant Assets/Logs

wait but how do i know if i did not install it

**Comment by yaichenbaum** [comment]
It's recommended to use the appinstaller https://files.community/download/stable.

**Comment by SAB236YT** [comment]
> It's recommended to use the appinstaller file https://files.community/download/stable.

thnks

**Comment by SAB236YT** [comment]
> > It's recommended to use the appinstaller file https://files.community/download/stable.
> 
> thnks

tho there is an error that interrupts the installation 0x80080005

**Comment by yaichenbaum** [comment]
Can you send a screenshot?

**Comment by SAB236YT** [comment]
> Can you send a screenshot?

sure wait up

**Comment by SAB236YT** [comment]
![Cattura](https://user-images.githubusercontent.com/98963514/194771426-e047b75f-32f7-469e-bdbf-76aa37941815.PNG)
this time its different...

**Comment by yaichenbaum** [comment]
I'm not sure what the issue is, I recommend opening an issue in Feedback Hub under AppInstaller.

**Comment by SAB236YT** [comment]
> 

ok thank you anyway
just you to know that its in italian so ill make the translation for you
"The installation of the application was not succsesfull with the error message: Error 0x8000000B: impossible to open the package from the position f5459d4828d6d0005eb969e187134578496e0c3. (0x8000000b)"
