### ISSUE TITLE
samba can't be connected in win11 22H2 and error suffix when copy folder in samba.

### ISSUE THREAD

**Issue by tower-town** [files-community/Files#10149]
### Description

 I wonder why the file can't connect via samba in win11 22H2, but win10 21H1 has no problem.
Sometimes, I feel good in win10.
Unfortunately, when I copy the folder to samba today, the `Files` will be created in a blank folder and copied into "\<folder>-copy".

There is no problem in using File explorer on the corresponding computer in the above two situations

### Steps To Reproduce

input "\\\\\<ip-addr>" in address bar.

### Steps to fix

null

### Files Version

Version: 2.3.12.0 OS Version: 10.0.19043.1889 and Version: 2.3.12.0 OS Version: 10.0.22621.608

### Windows Version

win10 21H1 and win11 22H2

### there are log files in win10

[debug.log](https://github.com/files-community/Files/files/9731450/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9731452/debug_fulltrust.log)

### there are log files in win11
[debug.log](https://github.com/files-community/Files/files/9731562/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9731564/debug_fulltrust.log)

**Comment by gave92** [comment]
Merging with #9628
