### ISSUE TITLE
Bug: Opening Google Drive

### ISSUE THREAD

**Issue by WhispersOfJ** [files-community/Files#10142]
### Description

Upon Opening Drive, Files crashed.

### Steps To Reproduce

1. Double-Click On Google Drive Icon (Z:\ in my case)
2. Crash

### Steps to fix

Crash makes it impossible to access my Google Drive using Files, and thus makes it impossible for me to continue to use Files.

### Files Version

Version: 2.3.12.0 OS Version: 10.0.25211.1010

### Windows Version

Windows 11 Pro Insider Preview 22H2 25211.1010

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9724307/debug.log)

**Comment by yaichenbaum** [comment]
Is this an issue in the preview version? files.community/download/preview
