### ISSUE TITLE
Bug: Folder suggestions are not showing in the Address bar

### ISSUE THREAD

**Issue by verdaderoken** [files-community/Files#10150]
### Description

The folder suggestions are not showing in Address bar. 
![image](https://user-images.githubusercontent.com/88200096/194523219-cd266dda-acb6-42c3-805c-419657e4d048.png)
the 

### Steps To Reproduce

1. Navigate to any folder that has subdirectories
2. Click on the Address bar and type the letters of any subdirectory.
3. Suggestions will show but the actual text is not.

### Steps to fix

- Make the actual folder texts visible

### Files Version

2.3.46.0

### Windows Version

10.0.22623.730

### Relevant Assets/Logs

N/A

**Comment by sthivaios** [comment]
Yes, I can confirm that this doesn in fact happen.



![Image](https://user-images.githubusercontent.com/109022579/195150267-eb6fa9eb-e3cc-4de8-b79e-6e2cf137758a.png)
