### ISSUE TITLE
sometimes moving files very slow

### ISSUE THREAD

**Issue by Leoijeon** [files-community/Files#10159]
### Description

I'm moving some pdf files (about 4~10 MB one pdf), it moved several files then got stuck, and the computer fan started spinning faster.
![D3_L765PNN$)O@ NUC MM 7](https://user-images.githubusercontent.com/30471002/194711896-e2de9359-8c7c-4ea3-93f2-20c40c3b3acf.png)

### Steps To Reproduce

1. moving files 

### Steps to fix

Fix sometimes move/copy files slow

### Files Version

Version: 2.3.12.0 OS Version: 10.0.19044.2006

### Windows Version

Windows 10 Pro Version	21H2 OS build	19044.2006 Experience	Windows Feature Experience Pack 120.2212.4180.0

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/9739447/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/9739448/debug.log)

**Comment by Josh-65** [comment]
Is this an issue in the preview version? https://files.community/download/preview

**Comment by Leoijeon** [comment]
No, installed from Microsoft store.

**Comment by Josh-65** [comment]
No, it isn't an issue, or you haven't tried it?

**Comment by Leoijeon** [comment]
It's better to use the preview version?

**Comment by Josh-65** [comment]
Not always its less stable and has thing that may not make it to stable releases. It's asked to see if the bug has already been fixed

**Comment by Leoijeon** [comment]
Ok, I will try this

**Comment by Leoijeon** [comment]
This problem is not happened in preview version
