### ISSUE TITLE
A file can't be renamed the same as a folder name

### ISSUE THREAD

**Issue by RihanArfan** [files-community/Files#10152]
### Description

If you have a folder named `[folder] something.json` and try to rename a file to the same name (`[file] something.xyz` -> `[file] something.json`), the file name will auto increment (`[file] something.json (2)`).

### Steps To Reproduce

1. Create folder named something.json
2. Create file named example.txt
3. Rename example.txt to something.json
4. Result: file becomes something.json (2)

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

2.3.12.0 (Stable latest Microsoft store version)

### Windows Version

Windows 11 22H2

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/20425781/194538871-77351e64-3744-4735-8c86-c2560081eaaa.png)

**Comment by ambitiousCC** [comment]
Interestingly, even the file manager that comes with Windows does not support consistent names for folders and files.

**Comment by Josh-65** [comment]
The file system isn't able to determine what is and isn't a folder when using names. Files won't be able to support it.
