### ISSUE TITLE
exiting properties dialog box bug

### ISSUE THREAD

**Issue by Leoijeon** [files-community/Files#10160]
### Description

I opened a picture's properties, then exit it. But the properties dialog box did not close but cover the whole Files app just like the screenshot. This didn't happen before, so I don't know it is an accidental bug or not.
![_UK(G$}}OTZ8@1NP}KYIB`J](https://user-images.githubusercontent.com/30471002/194712166-4627f590-998d-4bd5-ba82-5b49afed51cb.png)

### Steps To Reproduce

1. open a picture's properties
2. see the detail page
3. exit properties

### Steps to fix

Fix the crash when closing properties

### Files Version

Version: 2.3.12.0 OS Version: 10.0.19044.2006

### Windows Version

Windows 10 Pro Version	21H2 OS build	19044.2006 Experience	Windows Feature Experience Pack 120.2212.4180.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9739461/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9739462/debug_fulltrust.log)

**Comment by Leoijeon** [comment]
the whole app then can't close until I end the process by task manager

**Comment by yaichenbaum** [comment]
Is this an issue in the preview build? https://files.community/download/preview

**Comment by Leoijeon** [comment]
No, I install it from MS app store

**Comment by Josh-65** [comment]
Did you download it from the link and test to see if issue happened?

**Comment by Leoijeon** [comment]
it didn't happen again, but I think it may be better if I report it.
