### ISSUE TITLE
Hi I like it，hope to add double click to click function

### ISSUE THREAD

**Issue by Superhedgehoger** [files-community/Files#10168]
### What feature or improvement do you think would benefit Files?

I really like the windows explorer general options to click on items (selected when pointing), underline only when pointing to an icon title, and the checkbox feature.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

版本: 2.3.12.0 OS Version: 10.0.22621.608

### Windows Version

eg.Windows 11 21H222000.194

### Comments

![image](https://user-images.githubusercontent.com/65106668/194790530-5095d0cc-d247-474e-b6f9-a066aaaed845.png)

**Comment by Josh-65** [comment]
Double click is the default way. single click can be found in Files settings > preferences > file and folder
