### ISSUE TITLE
Add Folders to Favorites

### ISSUE THREAD

**Issue by klngai** [files-community/Files#10164]
### What feature or improvement do you think would benefit Files?

How do I add folders to Favorites especially those that show upon the main panel?
![Files _ window](https://user-images.githubusercontent.com/14360781/194773578-fc06e0a8-7ec8-462e-b5b3-56871a55bd54.jpg)
e.g. adding music, pictures and videos to Favorites!

### Requirements

Nice!  Reply to kaleung.ngai@gmail.com

### Files Version

Version 2.3.12.0

### Windows Version

Windows 11 Insider Preview 10.0.22623.730 (ni_release)

### Comments

Thanks.

**Comment by gave92** [comment]
Navigate to a folder, right-click and select "pin to favorites"

**Comment by klngai** [comment]
Worked.  Thanks.  I liked it.
