### ISSUE TITLE
Display deleted filenames in the ongoing tasks menu

### ISSUE THREAD

**Issue by BraianPita** [files-community/Files#10165]
### What feature or improvement do you think would benefit Files?

I think it would be better to display the names of the actual file/folder we are deleting when the notification of completion shows on the ongoing tasks menu in the top right corner of the window. The reason is clarity since it becomes unclear what file was successfully deleted if I am deleting multiple files/folders from the same folder.

This image represents what I am referring to:
![image](https://user-images.githubusercontent.com/54162188/194775736-efada9c6-138e-493e-a941-81901fb6a614.png)
If I delete multiple files from the AppData/Local folder it would be unclear which is which. I hope to be able to see the actual names of deleted files/folders.

### Requirements

- This proposal will include the name of a file/folder deleted along with the completion notification.
- This proposal will include the name of a file/folder in the ongoing tasks notification of progress.

### Files Version

Version: 2.3.28.0 

### Windows Version

OS Version: 10.0.19044.2006

**Comment by Josh-65** [comment]
Merging with #4811
