### ISSUE TITLE
Right column should refresh for both folder contents and single files

### ISSUE THREAD

**Issue by Colin-VideoRevealed** [files-community/Files#10162]
### What feature or improvement do you think would benefit Files?

Watch recording and you'll see that when reselecting the single file, you still see the old folder contents.
This is both confusing and irrelevant. 

https://user-images.githubusercontent.com/93034904/194731538-19b84a76-d56d-4ebb-9ff6-c9526b80c947.mp4

### Requirements

The right area should always show relevant data based on what is selected in the previous column. 
Selecting a single file should show nothing on the right unless preview is open. 

### Files Version

Version: 2.3.12.0 OS Version: 10.0.22621.608

### Windows Version

Edition	Windows 11 Pro Version	22H2 22621.608

**Comment by yaira2** [comment]
Merging with #10998, this is being worked on and should be available soon.
