### ISSUE TITLE
Bug: Folders ending with a dot character aren't displayed properly 

### ISSUE THREAD

**Issue by warpdesign** [files-community/Files#10169]
### Description

Files does not display correctly WSL folders ending with a dot, and cannot interact with them (no way to open a directory named `toto...` for example).

### Steps To Reproduce

1. Open a terminal in WSL
2. Create a folder named `foo...` by typing `mkdir foo...`
3. Navigate to this directory in Files (for example: `\\wsl$\Ubuntu-22.04\tmp`)

Notice how:
- the folder's name is `foo` instead of `foo...`
- double-clicking on the folder does nothing

### Steps to fix

- Allow users to properly navigate to these locations
- Display the proper name

### Files Version

Version 2.13.12.0

### Windows Version

version 10.0.19044.2075

### Relevant Assets/Logs

Screenshot of Files displaying the `tmp` folder, and below how the folder is supposed to look like:

![image](https://user-images.githubusercontent.com/199648/194847789-01bc71c8-f238-4db5-800a-1d116d0634e7.png)

`explorer.exe` displays the folder correctly but cannot access it:

![image](https://user-images.githubusercontent.com/199648/194848042-e365599c-16be-4124-ac5e-34d3d09c5ae0.png)

[react-explorer](https://github.com/warpdesign/react-explorer) can display and access it correctly:

![image](https://user-images.githubusercontent.com/199648/194848289-0cc4205f-e82c-4fcb-985d-1ea0951d547b.png)

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by yaira2** [comment]
@warpdesign

**Comment by warpdesign** [comment]
I installed 2.4.67.0 and am still having problems: folder name appears to be correct and it says file is "folder" (dossier in French) as expected, but the icon is wrong (shows unknown file instead of folder icon) and double-clicking on the icon does nothing.

![image](https://user-images.githubusercontent.com/199648/233962151-41591068-34d3-4825-ade6-f04691934ec2.png)

**Comment by yaira2** [comment]
@warpdesign I've tried the steps to reproduce this and the folder opens correctly. Although the dot doesn't display, this is consistent with File Explorer. Can you check if it's still an issue on your end?
