### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by Taiyou06** [files-community/Files#10166]
### Description

It lagged a lot when same tab opened up multiple times

### Steps To Reproduce

1. Open up same tab 6-7 times (with a lot of files)
2. Try to switch between them

### Steps to fix

(i have no clue to be honest)

### Files Version

2.3.12.0

### Windows Version

Windows 10 Home Single Language Version	21H2 19044.2075

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9742458/debug.log)

**Comment by Josh-65** [comment]
Is this an issue in the preview version? https://files.community/download/preview

**Comment by Taiyou06** [comment]
> Is this an issue in the preview version? https://files.community/download/preview

i downloaded it from microsoft store

**Comment by Taiyou06** [comment]
works fine _i guess_, spammed a lotta tabs it slowed down a lot but didn't crashed
