### ISSUE TITLE
Properties menu opens on wrong monitor.

### ISSUE THREAD

**Issue by Xyphyn** [files-community/Files#10179]
### Description

I have a dual monitor setup (different res, if that changes anything), and when I open the properties menu on a file, it appears on the bottom left of my second monitor, even if the files app is on my first monitor.

### Steps To Reproduce

1. Right click a file
2. Click properties
3. See the properties window open on the wrong monitor

### Steps to fix

- Make the properties menu open on the monitor the app is on, or have it just open on the middle of the app itself.

### Files Version

Version: 2.3.12.0

### Windows Version

Windows 11 Dev 22H2 10.0.25217.1000

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9758014/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9758015/debug_fulltrust.log)

![GIF of what's happening](https://user-images.githubusercontent.com/80978739/195147718-b6e44e43-4dbb-4c40-8f8e-2773cfd82ca1.gif)

**Comment by Josh-65** [comment]
This shouldn't be an issue in the preview version as it opens at mouse cursor. https://files.community/download/preview

**Comment by verdaderoken** [comment]
This is fixed in the preview version
