### ISSUE TITLE
How to clear the tags

### ISSUE THREAD

**Issue by Leoijeon** [files-community/Files#10173]
### Description

I installed preview version. The preview version (2.3.47) app shows my file tag "unknown", so I change it to "blue". Then in the stable version (2.3.12) also shows "unknown" tag. 
Because I tagged many files, now I want to clear all tag, how to do that?

### Steps To Reproduce

tag files

### Steps to fix

How to clear the tags

### Files Version

Version: 2.3.12.0 OS Version: 10.0.19044.2006

### Windows Version

Windows 10 Pro Version	21H2 OS build	19044.2006 Experience	Windows Feature Experience Pack 120.2212.4180.0

### Relevant Assets/Logs

none

**Comment by Josh-65** [comment]
Right click on the file or folder > File tags > click the one called unknown.

**Comment by Leoijeon** [comment]
I know this, I mean can I clear different file's tag one time? I delete the filetags.db, but these tags still there.

**Comment by Josh-65** [comment]
That tags that show as option are in Files settings > experimental > edit tags. If it doesn't work, then I don't know why it would be there.

**Comment by Leoijeon** [comment]
yes, I edit this file, "unknown" tag still exists. I curious about how this "tag info" stored?

**Comment by Josh-65** [comment]
It's stored in the filetags.db file. But if you deleted it all files/folders should have lost there tags.

**Comment by gave92** [comment]
Tag info is also stored inside each file, so no you can't get remove tags from all files at once.

**Comment by gave92** [comment]
Edit: the best way to remove all tags is from inside Files. Clicking on each tag in Files sidebar shows all files with a tag, and you can untag them all at once. That is if you haven't deleted the filetags.db files :)

**Comment by Leoijeon** [comment]
Thanks for your answer. I tried again and show all hidden files, then I found when I tag a file, the second file will generate.
![QQ图片20221011193958](https://user-images.githubusercontent.com/30471002/195080495-2f673bc7-1930-4ea7-9003-86f41e8a84de.png)

**Comment by Leoijeon** [comment]
> Edit: the best way to remove all tags is from inside Files. Clicking on each tag in Files sidebar shows all files with a tag, and you can untag them all at once. That is if you haven't deleted the filetags.db file :)

Your suggestion is useful. But there also a problem, the "Unknown" tagged files won't show in sidebar's tag page automatically. Unless I open their directory, then they will show in sidebar's tag page.

**Comment by yaichenbaum** [comment]
> Your suggestion is useful. But there also a problem, the "Unknown" tagged files won't show in sidebar's tag page automatically. Unless I open their directory, then they will show in sidebar's tag page.

This is the expected behavior, Files only knows about the tags in its database, unless we index the complete file system, we have no way to detect unknown tags in advance. Does the additional file go away if you turn off the setting to display alternate data streams?
