### ISSUE TITLE
The Recycle Bin is displayed as Shell: RecycleBinFolder

### ISSUE THREAD

**Issue by MimecraftAndrew** [files-community/Files#10175]
The Recycle Bin is displayed as Shell: RecycleBinFolder.I don't know how to correct.I think it's a big big problem.
![屏幕截图 2022-10-11 091726](https://user-images.githubusercontent.com/113965299/194975978-74c178c9-5f5a-4e80-87b0-27a2594f4b7d.png)

**Comment by Josh-65** [comment]
Restart files if it happens again, please make a new issue following the issue templates.
