### ISSUE TITLE
Add column for path when doing search

### ISSUE THREAD

**Issue by silversword411** [files-community/Files#10172]
### What feature or improvement do you think would benefit Files?

When doing search there's no easy way to see where all the files are that you just searched for. Should have another column for "path" which auto-shows after doing search

![2022-10-10_085744 - ApplicationFrameHost_C_‎-_Files](https://user-images.githubusercontent.com/13395348/194871720-b8e7e741-66df-4a3c-9689-951dfcff6ec2.png)

### Requirements

- Need to add a column type of "path"
- Need to automatically switch column view to include it after searching

### Files Version

2.1.15.0

### Windows Version

Win 10 21H2

**Comment by Josh-65** [comment]
Merging with #7070

**Comment by silversword411** [comment]
Sorry, my search-fu didn't find that original issue...I did try! ;)
