### ISSUE TITLE
[WSL] Auto refresh of directory

### ISSUE THREAD

**Issue by warpdesign** [files-community/Files#10170]
### What feature or improvement do you think would benefit Files?

Right now, when a folder from WSL is opened in `Files`, if the folder is updated, its content won't be refreshed in Files: the user has to manually refresh it.

### Requirements

- Running a command `inotifywait` using `wsl.exe` allows to get notified of filesystem changes with WSL

### Files Version

Version 2.13.12.0

### Windows Version

version 10.0.19044.2075

### Comments

This has been implemented in `react-explorer`: https://github.com/warpdesign/react-explorer/pull/253/files with success.

**Comment by Josh-65** [comment]
Merging with #9250
