### ISSUE TITLE
Feature: Add support for creating shortcuts from the new item menu

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#10187]
### What feature or improvement do you think would benefit Files?

There should be the ability to add a new shortcut from the new menus in Files.

### Requirements
- Clicking on the option should display a modal
![image](https://user-images.githubusercontent.com/39923744/195749611-2b4dd2f4-5d09-488e-b17a-ee864537e20e.png)
- Detection on when it a local/network drive or a web address (https, http)
- Include a browse option to select a network drive or local folder

### Files Version

2.3.12.0

### Windows Version

10.0.19043.2006

**Comment by yaichenbaum** [comment]
I think we need design for this one.
