### ISSUE TITLE
New issue template for Code Quality issues

### ISSUE THREAD

**Issue by QuaintMako** [files-community/Files#10184]
As for now, there is two types of issues by default in on the repository : bug and feature request.

Sometimes, when developing, we can fall upon refactoring that may have nothing to do with our current issues that we'd like to mark for later. We are also currently going through a massive refactoring of the codebase. 

It would be nice to have a template issue about code quality for those type of situations.

An issue of that type could be defined as : 

- Title
- Description of Issue: What is the issue? What makes you think this is bad for the codebase?
- Possible solution: Maybe you have already an idea about how to clear the problem?
- What would it would bring: Maybe a clearer source code, or better performances etc..
- Concerned files: Listing the files so one can directly see where to start.

Such issue would have a `Code Quality` label when generated.

### Requirements

- This proposal will allow to have a more streamlined process when it comes to keeping our codebase clean.
- This proposal will allow anyone wanting to just do refactoring / codebase management and not developping issues to have something to look at.

### Files Version

Unrelevant

### Windows Version

Unrelevant

**Comment by QuaintMako** [comment]
Posting such a feature request because I am stumbling on quite a lot of small (and not so small) refactorings that have nothing to do with what I'm currently working on. Doing all of them by myself would be quite the task or/and out of the scope of the issue I am tackling when seeing them.

**Comment by yaichenbaum** [comment]
@QuaintMako do you want to create a template?

**Comment by QuaintMako** [comment]
Can give it a shot, yeah

**Comment by QuaintMako** [comment]
Looking into it, but I'm not sure how to process here.

I believe the issue templates are to be done through the settings menu. I (obviously) do not have the rights for it here. 

Looked around the Git documentation, seems they are stored in the .git folder, which I do not have access as well since it's a fork.

So, any hint on how to process would be gladly taken! ^^

**Comment by QuaintMako** [comment]
Looking into it, but I'm not sure how to process here.

I believe the issue templates are to be done through the settings menu. I (obviously) do not have the rights for it here. 

Looked around the Git documentation, seems they are stored in the .git folder, which I do not have access as well since it's a fork.

So, any hint on how to process would be gladly taken! ^^

**Comment by QuaintMako** [comment]
Looking into it, but I'm not sure how to process here.

I believe the issue templates are to be done through the settings menu. I (obviously) do not have the rights for it here. 

Looked around the Git documentation, seems they are stored in the .git folder, which I do not have access as well since it's a fork.

So, any hint on how to process would be gladly taken! ^^

**Comment by yaichenbaum** [comment]
It's just a markdown file that gets added to `github/ISSUE_TEMPLATE``

**Comment by QuaintMako** [comment]
Alright! Will get to it soon then! Thanks for the quick answer!
