### ISSUE TITLE
Code Quality: Switching the Helpers Classes to static

### ISSUE THREAD

**Issue by QuaintMako** [files-community/Files#10185]
Most Helpers are defined as static classes. 

Yet by roaming through the code, we can find some of them that are not, such as `FilesystemHelpers`. 

**Requirements**
- Helper classes with plural name should be static (static class ExceptionHelpers)
- Helper classes with singular name should be instantiable. (sealed class ThemeHelper)

**Comment by yaichenbaum** [comment]
@d2dyno1 @lukeblevins

**Comment by d2dyno1** [comment]
I agree with few exceptions:
- Helper classes with plural name should be static (`static class ExceptionHelpers`)
- Helper classes with singular name should be instantiable. (`sealed class ThemeHelper`)

**Comment by yaichenbaum** [comment]
This is ready to build

**Comment by 0x5bfa** [comment]
I really don't like plural and singular naming convention because someone who is wanting to create a new helper class would be connfused. so here's the solution.

- Move classes that need to be instanced into Services.

@d2dyno1 What do you think?

**Comment by d2dyno1** [comment]
I think we should be careful when doing this and first determine which helpers we want to convert into what

**Comment by yaira2** [comment]
@QuaintMako what's the status on this issue?

**Comment by yaira2** [comment]
I think we can continue working on this as needed, closing for now.
