### ISSUE TITLE
Dedicated recycle bin area

### ISSUE THREAD

**Issue by gisturbance** [files-community/Files#10199]
### What feature or improvement do you think would benefit Files?

The recycle bin doesn't seem like something that belongs to "Favorites". It's a sacred place where files are deleted and recovered. Having a dedicated area for it would increase accessibility and free space in the favourites section.

### Requirements

- Create a dedicated area at the bottom of the left sidebar, that is always visible, excluded from the scrolling area above.
- Add an icon and/or a title for the recycle bin to the left side of the area, with the current/max size of the bin below it, maybe accompanied by a meter bar (as the drives).
- Add a button "empty bin" to the right side of the area, including a keyboard shortcut to trigger its action.
- Add the ability to drag & drop files onto the area, moving them into the bin. Holding the Shift key while dropping the file would delete the file permanently.
- Add the ability to click onto the area (except the delete button) to open the recycle bin.
- Add an option to toggle the visibility of the recycle bin area.

### Files Version

Version: 2.3.12.0

### Windows Version

Windows 11 Pro 22H2 22621.674

**Comment by Josh-65** [comment]
- How would it be more accessible? It would be the same size and area out of the favourites. 
- Always showing the current and max size of the bin doesn't make since since it local and determent by the drive size. Which visible on the home page and the sidebar when hovered over.
- Right clicking to empty the bin is already a thing.
- It can already be pinned/unpinned from there like any other folder on favorites, so it makes sense to have it there.

**Comment by gisturbance** [comment]
> How would it be more accessible? It would be the same size and area out of the favourites.
> It can already be pinned/unpinned from there like any other folder on favorites, so it makes sense to have it there.

I wouldn't say that a recycle bin is a "favorite folder", rather a dedicated feature currently presented as a folder. It being a separate area would prevent any (accidental) interference (move/deletion) with other actual folders, especially since the sorting of the favorite items differs by every language and the items can't be rearranged.
Adding to that, for someone who isn't using the favorites at all, it could be an annoyance to have that "Favorites" entry there solely for the paper bin, which not even semantically belongs in there.

> Always showing the current and max size of the bin doesn't make since since it local and determent by the drive size. Which visible on the home page and the sidebar when hovered over.

Looking at the properties of the recycle bin shows a configurable maximum size. Showing it directly with the current size would remove the need of spending time to hover. Users with smaller drives could directly see they have to declutter the bin, should that be the cause of nearly running out of space.

> Right clicking to empty the bin is already a thing.

A dedicated button still wouldn't hurt, since that would be the secondary action of that area, besides opening the bin.

**Comment by yaichenbaum** [comment]
Recycle Bin is pinned as if it were a regular folder, users can navigate to it via the address bar, but it requires typing "Shell:RecyleBin" and is a little harder to discover. More advanced users can unpin it if they like and just type the path.

**Comment by gisturbance** [comment]
> Recycle Bin is pinned as if it were a regular folder, users can navigate to it via the address bar, but it requires typing "Shell:RecyleBin" and is a little harder to discover. More advanced users can unpin it if they like and just type the path.

That's why it's so inaccessible. Having it separated would improve the whole flow.
One shouldn't have to navigate to delete/recover files.One shouldn't need to search between favorites for it.

Otherwise one could also remove the drives, the libraries and everything else because they can be added as favorites or navigated as well. Next step is to remove the settings button, or the whole interface at all, leaving only a search bar.

I prefer a graphical user-inteface that is also solely keyboard navigatable (hence the empty-bin shortcut) without having to take unnecessary extra steps to reach such a fundamental function.

As said, a recycle bin is not just a folder since accidentally mishandling it can lead to lost files. It's not a favorite item, it's a system action, that should be separated due to it's nature. Especially since every time the alphabetically sorted favorite list changes when another entry joins, or the system language is changed.

One doesn't simply disguise a shredder as a folder and puts it into a rack with other folders.

**Comment by yaichenbaum** [comment]
> That's why it's so inaccessible. Having it separated would improve the whole flow.
One shouldn't have to navigate to delete/recover files. One shouldn't need to search between favorites for it.

This can be said about any favorite or drive, the line needs to be drawn somewhere and I think we have a pretty good balance with the current design. It's useful to have a recycle bin shortcut on the sidebar but it's not the main function of the app. We'll leave this open to continue gathering feedback.

**Comment by gisturbance** [comment]
> > That's why it's so inaccessible. Having it separated would improve the whole flow.
> > One shouldn't have to navigate to delete/recover files. One shouldn't need to search between favorites for it.
> 
> This can be said about any favorite or drive, the line needs to be drawn somewhere and I think we have a pretty good balance with the current design. It's useful to have a recycle bin shortcut on the sidebar but it's not the main function of the app that it deserves a dedicated section. If you're concerned about accidentally deleting items, I recommend unpinning it from the sidebar. We'll leave this open to continue gathering feedback.

This misconception only applies when assuming that the recycle bin is equal to a drive or folder, which, from a perspective outside the fairly ill-designed Windows ecosystem, it simply is not.
I would go as far as treating it like a separate application - with the purpose of it's name, recycling files -, that due to bad design decisions was made to look like a folder.

To recap:
- Recycle bin has a different name in each language
- The sorting in the Favorites section solely happens alphabetical
- Upon adding or removing entries, the sorting changes
- Accidentally moving a file to the recyble bin due to changed sorting might lead to lost or corrupt data
- Removing the recycle bin from favorites makes it harder to access (unless visiting desktop or typing into address bar)
- The recycle bin is tied to the system action "delete", deeming it's availability always as necessary

---

The description upon issue creation states the following:
>  This project thrives from differentiation from competing apps.

When creating this issue, I was thinking that it's welcomed to stray away from outdated concepts that Windows itself is following until today. Leading to an enlightening view of improved and future-rich user experiences.

That said, I would advise to rethink the interpretation of fundamental concepts we are hauling around since decades, holding us back from innovation.

**Comment by Josh-65** [comment]
Favorites are stored alphabetically. Items are added to the bottom and the user can move them
![image](https://user-images.githubusercontent.com/26977075/195958886-d807ee90-f431-4c7e-801d-83c07d073509.png)

**Comment by gisturbance** [comment]
Oh, indeed. I only tried moving the entries by drag & drop, but the move actions are in the context menu. Though that shouldn't interfere with the rest of my arguments.

Understandable, that not everything can be implemented, though I dare to say that the mass alone doesn't know what's best, it rather stays to things it's used to.

**Comment by yaichenbaum** [comment]
> Understandable, that not everything can be implemented, though I dare to say that the mass alone doesn't know what's best, it rather stays to things it's used to.

That's very true, we've made several changes that took some time to be accepted but ended up being copied by others (removing the ribbon, simplifying the context menu etc). I want to note that we don't approve/close feature requests based on the effort, we're trying to build something special and we're not going to cut corners. However, before making a change to an existing feature, we either need solid feedback that the current solution is problematic or there is a good suggestion that would greatly improve the user experience.
In this case, I haven't been convinced that pinning recycle bin to the sidebar is problematic. I still need some time to read up on the rest of the discussion to see if the recommendations will bring a big improvement but I'm currently leaning towards leaving as is.
