### ISSUE TITLE
Files Preview 2.3.48.0 Crashing

### ISSUE THREAD

**Issue by cobbettjp** [files-community/Files#10197]
### Description

Files Preview 2.3.48.0 crashing regularly.

### Steps To Reproduce

The crashes were happening whilst browsing directories after turning off  'Enable overriding folder preferences in individual directories', 

However I've turned this back on now and it's still crashing, so that may not be the cause.

### Steps to fix

None.

### Files Version

Files Preview 2.3.48.0

### Windows Version

Windows 11 Pro 22H2 22621.674

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9779507/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9779508/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
This is specific to the details layout and is being tracked here https://github.com/microsoft/microsoft-ui-xaml/issues/7695
