### ISSUE TITLE
Bug: Files crashes when clicking browse on properties customise page

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#10193]
### Description

![image](https://user-images.githubusercontent.com/26977075/195596844-385ab8db-44e8-47f1-b79a-81aa8e881572.png)

### Steps To Reproduce

1. Right click on a folder
2. Open the properties menu
3. Open the customise page
4. Click browse button
5. Files crashes

### Steps to fix

- Fix browse not opening file explorer open dialog

### Files Version

2.3.48.0

### Windows Version

11.0.22621.608

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9776650/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9776651/debug_fulltrust.log)

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.
