### ISSUE TITLE
Bug: "Open in new window/tab" command is not working for tags in the sidebar

### ISSUE THREAD

**Issue by ferrariofilippo** [files-community/Files#10198]
### Description

"Open in a new tab" and "Open in a new Window" commands aren't working for Tags.

### Steps To Reproduce

1. Right click on a tag in `Tags` Sidebar section
2. Select `Open in new window/pane`
3. See an error is displaying

### Steps to fix

- Commands should work properly

### Files Version

Version 2.3.28.0 OS Version: 10.0.22621.521

### Windows Version

Windows 11 Home 22H2 22621.521

**Comment by yaira2** [comment]
Is this still an issue in v2.4?

**Comment by ferrariofilippo** [comment]
Everything works fine!
