### ISSUE TITLE
[Feature Request] Add customizable shortcut folder to side pane 

### ISSUE THREAD

**Issue by Browntomcat33** [files-community/Files#10201]
Something like this.
![mockup](https://user-images.githubusercontent.com/100460368/195747895-71a58397-df26-44ba-82d2-d674108d442b.jpg)

**Comment by Josh-65** [comment]
You can use tags for custom items in the sidebar

**Comment by yaichenbaum** [comment]
@Josh-65 I think this is requestion support for creating custom sidebar sections.

**Comment by yaichenbaum** [comment]
@Browntomcat33 can you open an issue with the feature template?
