### ISSUE TITLE
Bug: Google drive icon overlays aren't displayed

### ISSUE THREAD

**Issue by soredake** [files-community/Files#10204]
### Description

Google drive sync icons are no longer shown in preview version.

### Steps To Reproduce

1. Download preview version.
2. Navigate to Google Drive
3. Observe that google drive sync icons aren't shown.

### Steps to fix

- Display Google Drive icon overlays

### Files Version

2.3.48.0

### Windows Version

10.0.22000.1042

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9784748/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9784749/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
Is this on the grid layout?

**Comment by soredake** [comment]
> Is this on the grid layout?

Icons are missing on all layouts.

**Comment by yaichenbaum** [comment]
I can reproduce this issue

**Comment by ferrariofilippo** [comment]
I found the line that causes the problem (line 283 of `Files.App.Shell.Win32API.cs`).
This line was changed in <a href="https://github.com/files-community/Files/pull/9896">#9896</a> to avoid an exception.
