### ISSUE TITLE
scrolling in preview version is less smooth than in stable version

### ISSUE THREAD

**Issue by soredake** [files-community/Files#10205]
### Description

Scrolling in preview version is less smooth than in stable version.

### Steps To Reproduce

1. Have 144hz monitor like me
2. Try scrolling in stable (somewhat acceptable)
3. Try scrolling in preview (less smooth)

### Steps to fix

- Make scrolling as smooth as in stable

### Files Version

2.3.48.0

### Windows Version

10.0.22000.1042

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/9784812/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/9784813/debug.log)

**Comment by yaichenbaum** [comment]
Is specific to the details layout?

**Comment by soredake** [comment]
> Is specific to the details layout?

No, it happens in all layouts.

**Comment by yaichenbaum** [comment]
This seems to be a regression with all WinAppSdk applications, can you open an issue on their repo and link it here?

**Comment by soredake** [comment]
https://github.com/microsoft/WindowsAppSDK/issues/3060
