### ISSUE TITLE
Bug: Move options are showing for non favorites on the sidebar

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#10215]
### Description

The context menu of the favorites section show entries to move the element (up or down). This does not work because the order of the sections is fixed.

### Steps To Reproduce

1. Right click on the favorites section in the sidebar.
2. Click on "Move to bottom"
3. Nothing is happening.

### Steps to fix

The easiest way is to remove the menu entries.
We can also add the functionality but it is an important development without much added value.

I am preparing a pr to remove these entries from the menu.

### Files Version

Dev at 2022-10-15 16:37 utc

### Windows Version

Windows 11 22621.674

### Relevant Assets/Logs

![section](https://user-images.githubusercontent.com/46631671/195987885-35e97091-8f74-4913-9a07-2233c2ea375b.png)

**Comment by yaichenbaum** [comment]
@cinqmilleans do you want to work on this?

**Comment by cinqmilleans** [comment]
It's already done, here #10219. Note that my screenshort is obsolete. In the preview version, this bug applies to all sections. In the dev version, only the Favorites section. I modified my issue but not the screenshot. My fix corrects this last section.
