### ISSUE TITLE
Feature: Ability to sort favorites

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#10216]
### What feature or improvement do you think would benefit Files?

Favorites are listed in chronological order (default) or sorted manually by the user. It would be handy if you could easily sort them by name.

### Requirements

- Add an entry in the favorites context menu to automate sorting. This command sorts only when clicked. It doesn't change anything when adding/moving a favorite later. You have to repeat the operation to sort out if you add elements. It's an action, not a setting.

### Files Version

Version: 2.3.48.0 OS Version: 10.0.22621.674

### Windows Version

Windows 11 22621.674

### Comments

Here a screenshot.
![sort](https://user-images.githubusercontent.com/46631671/195988687-a609eb45-694c-4fd4-b937-94459bb4ebbb.png)

**Comment by yaichenbaum** [comment]
It might be confusing if it only sorts once given that the sort options throughout the rest of the app do not.

**Comment by cinqmilleans** [comment]
It looks fine to me. You can provide a checkbox in the menu to sort or not by name. This is a feature that is not a priority but that we can consider a lot later.

**Comment by yaira2** [comment]
Thank you for your feedback, we don't have plans to implement this option at this time.
