### ISSUE TITLE
Feature: Allow to set default layout for folders in Settings

### ISSUE THREAD

**Issue by bchevreau** [files-community/Files#10218]
Hi

The fact that Layout>Column for example has to be re-selected everytime a new window is opened is quite tedious for people that prefer to solely use that Layout. Suggestion would be to add the option to select a specific Layout as default under Preferences > Files and Folders.

Thanks in advance!

**Comment by Josh-65** [comment]
this is fixed in the preview version. https://files.community/download/preview
