### ISSUE TITLE
Bug: Untagged files showing in tag search results

### ISSUE THREAD

**Issue by Leoijeon** [files-community/Files#10217]
### Description

In a tag page, pressing F5 to refresh will cause some bug. Same bug will occur in preview version.

### Steps To Reproduce

1. click tag on the sidebar
2. refresh page
3. see that untagged items are showing in the results

### Steps to fix
- Only show taged files

### Files Version

Version: 2.3.12.0 OS Version: 10.0.19044.2006

### Windows Version

Windows 10 Pro Version	21H2 OS build	19044.2006 Experience	Windows Feature Experience Pack 120.2212.4180.0

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/9792198/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/9792199/debug.log)

**Comment by yaichenbaum** [comment]
This issue will be resolved in the next preview build https://files.community/download/preview
