### ISSUE TITLE
RAM Usage stacking up after opening and closing tabs

### ISSUE THREAD

**Issue by webddemo** [files-community/Files#10210]
### Description

I opened and closed tabs on both the microsoft store and preview versions and the RAM usage gradually goes up but never comes down or gets any stable numbers, even if I leave only one tab open. 

### Steps To Reproduce

1. I made a simple test opening 6 tabs
2. Then I closed them all apart from one
3. Then opened 3 more 
4. At this point the ram usage usually stacks up a decent lot. Continue opening and closing groups of tabs to check.

### Steps to fix

- Check if the problem is reproducible on your side
- Optimize app by treating the memory leak if problem is found
- Test solution with big test cases

### Files Version

Version: 2.3.48.0 OS Version: 10.0.22621.674

### Windows Version

Windows 11 Home 22H2 22621.674

### Relevant Assets/Logs

I opened the same tab with 222 items which is a Downloads folder, but any folder does the same to a bigger or smaller extent. I also sort the information by date and mixed folders with files. That ram value (506 MB) is for just 1 tab after deleting all the others and if you create more the number keeps stacking up like in the image below. I also used both the MS Store and Preview versions. 

![Screenshot 2022-10-14 230723](https://user-images.githubusercontent.com/73552800/195956186-4c3c2c82-4f2f-493b-bd40-0dc1d1b121dd.png)

**Comment by yaichenbaum** [comment]
Merging with #4180

**Comment by yair100** [comment]
@webddemo we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
