### ISSUE TITLE
SMB Not Working

### ISSUE THREAD

**Issue by sthivaios** [files-community/Files#10223]
### Description

When I try to access an SMB share, it simply doesn't do anything.

In this case, I tried accessing my Domain Controller that has an SMB share on it. It is on \\blackcomb.

When you go there it does nothing. Doesn't ask for your credentials, doesn't show any folders... It does nothing.

Take a look at the video below...

https://user-images.githubusercontent.com/109022579/196004017-a589c8f8-4fd6-4800-9900-868dd292cf77.mp4

Below is what should have happened, and what happens with Windows Explorer

https://user-images.githubusercontent.com/109022579/196004108-f8fffa01-00a4-4302-af6a-8f697e7c2db3.mp4

### Steps To Reproduce

1. Open the app
2. Click on the path bar
3. Go on an SMB share \\[share] (in my case --> \\blackcomb
4. Nothing happens

### Steps to fix

Nope

### Files Version

Version : 2.3.48.0 

### Windows Version

Windows 11 22H2 (Build 22621.525)

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/9792905/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/9792906/debug.log)

**Comment by Josh-65** [comment]
Network access is properly off since VMs default to being a public network. Can you try connecting in File explorer and see what it shows`

**Comment by sthivaios** [comment]
> Network access is properly off since VMs default to being a public network. Can you try connecting in File explorer and see what it shows`

That's what I am saying. It is working properly with normal explorer.

**Comment by yaira2** [comment]
This was resolved in v2.4.30.
