### ISSUE TITLE
Add double click to explorer pane to go up a directory

### ISSUE THREAD

**Issue by coachz1** [files-community/Files#10227]
### What feature or improvement do you think would benefit Files?

It would be very helpful if the file folder pane allowed double clicking in the white area to go up a directory. This is  an extremely fast way a very efficient way to work with a lot of files and folders

### Requirements

Add double click functionality

### Files Version

2.3.12

### Windows Version

Win 11 22h2

### Comments

If you get these features I'm gonna start sending you Christmas cards

**Comment by yaichenbaum** [comment]
This is already supported in the latest version of Files....
