### ISSUE TITLE
Feature: Add an option to disable confirmation modal when changing file extensions

### ISSUE THREAD

**Issue by undecV** [files-community/Files#10221]
### What feature or improvement do you think would benefit Files?

When renaming a file with its extension, a gentle dialog will tell you, "If you change a file extension, the file might become unusable. Are you sure you want to change it?"

I've noticed this is a good security design, but it might not be pleasant for someone who knows what they're doing.

### Requirements

- Like the "Show a confirmation dialog when deleting files or folders" option in "Preferences" -> "Files and folders", 
Add an option like "Show a confirmation dialog when changing the file extension"

### Files Version

Version: 2.3.12.0

### Windows Version

Windows 11 Home 22H2 22621.674

### Comments

Related: [Turn off change file extension warning in Windows 7 - SuperUser](https://superuser.com/questions/67449/turn-off-change-file-extension-warning-in-windows-7)

**Comment by cinqmilleans** [comment]
It's an great idea.

**Comment by yaichenbaum** [comment]
This is an interesting idea to try, I'm going to leave this in planning for a while to gather additional feedback before approving.

**Comment by QuaintMako** [comment]
It'd be a fine addition to Files. 
Working on an issue related to file renaming, the file extension confirmation pop-up was slowing me down quite a bit.

**Comment by yaira2** [comment]
Let's move forward with this feature

**Comment by yaira2** [comment]
This will be included in the next release
