### ISSUE TITLE
Default sort and group by

### ISSUE THREAD

**Issue by ReadieFur** [files-community/Files#10229]
### What feature or improvement do you think would benefit Files?

Would it be possible to add a default sort and group by button based on the current folder view, like in how Microsoft's Explorer has the option to se a default sort and group by option for all folders.

### Requirements

- Create a either a tab in settings or a button to the sorting drop-down menu to apply the current filters to all folders.

### Files Version

Version: 2.3.12.0 OS Version: 10.0.22621.674

### Windows Version

Windows 11 22H2 22621.674

### Comments

Windows Explorer folder views option:
![image](https://user-images.githubusercontent.com/60425965/196015961-7011fbef-04fb-4d6d-a6ed-80687aadf527.png)

**Comment by yaichenbaum** [comment]
Thank you for your feedback, this is something we're planning to implement and being tracked in #7082
