### ISSUE TITLE
Bug: Settings displays wrong language after installing Files

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#10220]
### Description

After install, English is selected in the settings, but the locale language is used.
The System language is no longer available in the options. It was practical and avoids having to place English before the other languages, and therefore missing its rightful place.

### Steps To Reproduce

1. Use Windows in a language other than English.
2. Install Files.
3. Open Files. It is in the local language.
4. Open settings. English is selected.

### Steps to fix

- Add System language, used by default after install
- Place English in the others languages.

### Files Version

Version: 2.3.48.0 OS Version: 10.0.22621.674

### Windows Version

Windows 11 22621.674

### Relevant Assets/Logs

![lang](https://user-images.githubusercontent.com/46631671/195992591-115c7cd1-9b6a-4173-b95c-4e529a3c75b7.png)

**Comment by yaichenbaum** [comment]
@cinqmilleans good catch! Do you want to work on this?

**Comment by cinqmilleans** [comment]
It's already done. The pr is #10222. The bug is only in the option menu language switcher.
