### ISSUE TITLE
Bug: Dual pane context menu flashes

### ISSUE THREAD

**Issue by coachz1** [files-community/Files#10225]
### Description

When you open a second set of files in the dual pane mode and right click over the primary primary pain folder the context menu   flashes rapidly making it unusable

### Steps To Reproduce

Open a secondary pane
Right click  over folder in primary pane
 Context menu flashes and flashes

### Steps to fix

Make contex menu not flash

### Files Version

2.3.12

### Windows Version

Win 11 22h2

### Relevant Assets/Logs

None

**Comment by yaichenbaum** [comment]
Thank you for your feedback, can you share a screen recording?
