### ISSUE TITLE
List view and sidebar following

### ISSUE THREAD

**Issue by coachz1** [files-community/Files#10224]
### What feature or improvement do you think would benefit Files?

I really like the look but need LIST view in the main screen and for the sidebar to be able to expand to follow the directories as they open.
![explorer_HyAMglnpJj](https://user-images.githubusercontent.com/53879358/196004825-36907f0b-d3f9-4b6a-a8d6-830efce7d852.png)

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.3

### Windows Version

windows 11 22h2

### Comments

I really like the look but need LIST view in the main screen and for the sidebar to be able to expand to follow the directories as they open.

**Comment by coachz1** [comment]
Also need a ribbon up top please !!!!!

**Comment by Josh-65** [comment]
the ribbon is not coming back instead following the new design of the toolbar which is simpler and user friendly. if you want something added to it make a separate feature request

**Comment by yaichenbaum** [comment]
Merging with #1928

**Comment by coachz1** [comment]
Thanks for the tremendous help.  Is this feature in 2.3.12 or a beta
version ?  If beta how can I test it please ?

**Comment by coachz1** [comment]
What was not user friendly about the ribbon ? I loved it.

**Comment by yaichenbaum** [comment]
There are pro and cons for both the ribbon and simplified toolbar but we made the decision to use the toolbar and it appears to be working very well.
