### ISSUE TITLE
Add list view

### ISSUE THREAD

**Issue by coachz1** [files-community/Files#10226]
### What feature or improvement do you think would benefit Files?

Would really like to see a list view just like in the old windows Explorer where the folders and files wrap tightly next to each other and are  sorted alphabetically by folder's 1st and then files.
 Also an easy way to change to the other modes such as details, small medium large icons and And in details mode have control over which columns are displayed and how they are sorted?   Something that could be clicked on.

### Requirements

Not sure

### Files Version

2.3.12

### Windows Version

Win 11 22h2

### Comments

Thanks for any help with these features.  Windows Explorer has not been developed well at all and I've been using an app called clover for the past 10 years to get tabs which is now has broken graphics in the toolbar in windows 11. Plus the company's latest versions are full of trojans which makes it completely unusable

**Comment by yaichenbaum** [comment]
Merging with #2509

**Comment by yaira2** [comment]
@coachz1 thank you for your patience, I'm excited to share that a List View layout will be included in the next release.
