### ISSUE TITLE
Feature: Add toolbar button to hide file extensions

### ISSUE THREAD

**Issue by coachz1** [files-community/Files#10228]
### What feature or improvement do you think would benefit Files?

Add a button in the toolbar to hide and show file extensions

### Requirements

It would be very helpful to have a button in the toolbar to easily toggle on enough file extensions being displayed.

### Files Version

2.3.12

### Windows Version

Win11 22h2

**Comment by yaichenbaum** [comment]
There is already an option in settings Can you share more about your use case for a quick shortcut on the toolbar?

**Comment by Josh-65** [comment]
This is also in the layout flyout on the tool bar
![image](https://user-images.githubusercontent.com/26977075/196023523-2f0eb745-6323-43b2-a2d8-446703bb23b7.png)

**Comment by coachz1** [comment]
It's nice to be able to have extensions off but when I want to know what
extension a file is it's nice to have a check box like in the ribbon to
turn them back on quickly.

**Comment by yaichenbaum** [comment]
Does the flyout Josh mentioned work for you?
