### ISSUE TITLE
Not sure if right place if so let me know. Diskmgmt issue

### ISSUE THREAD

**Issue by JoshyJoshyVR** [files-community/Files#10236]
### Description

I cannot extend a drive in windows when there is a drive between as shown in the screenshot

### Steps To Reproduce

Shrink a disk
Put a drive inbetween empty and one you want extended

### Steps to fix

Not sure

### Files Version

Not sure as i dont have custom one

### Windows Version

11 22H2

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/83929921/196062622-be959531-710d-4e8f-9ea3-962c4f0eec5f.png)

**Comment by Josh-65** [comment]
This is not a Files issue.

**Comment by Josh-65** [comment]
This is not a Files issue. However, Aomei partition assistant will properly work for your use case to make sure you review the changes before running them
