### ISSUE TITLE
Feature: Esc to cancel tab tear off

### ISSUE THREAD

**Issue by verdaderoken** [files-community/Files#10234]
### What feature or improvement do you think would benefit Files?

Sometimes when using a touchpad, I accidentally drag a tab out to a new window. While still holding down the left button, I tried to cancel it with Esc but didn't work. A cancel function would be helpful to quickly prevent unintentional dragging.

### Requirements

- Implement a cancel shortcut when tearing a tab out of the window <kbd>Esc</kbd>

### Files Version

2.3.49.0

### Windows Version

10.0.22623.746

**Comment by Deekshithrathod** [comment]
Hello @yaichenbaum 
This issue could be a really good starting point for me to get started with opensource.

Can you assign this issue to me?

**Comment by anandv07** [comment]
Anyone working on this issue? I would like to work on it

**Comment by Josh-65** [comment]
@Deekshithrathod Are you working on this?

**Comment by yaira2** [comment]
> Anyone working on this issue? I would like to work on it

Looks like it's open, let us know how it goes.

**Comment by anandv07** [comment]
Ok thanks! I'll work on it

**Comment by Deekshithrathod** [comment]
@Josh-65 Sorry, couldn't find time to work on the issue. you can re-assign it to @anandv07

**Comment by Spid3rrr** [comment]
I can take it @yair100

**Comment by yaira2** [comment]
@Spid3rrr thank you

**Comment by Spid3rrr** [comment]
@yaira2 I can't seem to figure this out. I think it's better to leave it to someone else. Sorry for the delay.

**Comment by Spid3rrr** [comment]
@yair100 I think this task is too challenging for me as a first issue. It may be best to re-assign it. Sorry for the delay !

**Comment by yaira2** [comment]
> How can I completely disable draging out to a new window? I really don't want to drag out to new windows but it frequently happen to me accidentally. It annoys me.

@gluons this should be resolved in the latest preview build https://files.community/download

**Comment by yaira2** [comment]
@verdaderoken support for canceling tab tear off will be included in v3.
