### ISSUE TITLE
Clicking on the "Open log location" option in settings menu doesn't go to the folder in which logs are stored

### ISSUE THREAD

**Issue by ElitePheonix2009** [files-community/Files#10233]
### Description

I am going to settings, clicking on the about section and then clicking on the option "Open log location" doesn't open the folder in which logs for this app is stored.

### Steps To Reproduce

1. Click on the settings option (the gear icon).
2. Click on the about section.
3. Click on "Open log location" option.
4. See that the folder where the logs are stored doesn't open.

### Steps to fix

Make sure that when we clicking on the option "Open log location" the folder where logs are stored is open.

### Files Version

Version: 2.3.12.0 OS Version: 10.0.19044.2130

### Windows Version

Edition	Windows 10 Pro Version	21H2 Installed on	‎15-‎09-‎2022 OS build	19044.2130 Experience	Windows Feature Experience Pack 120.2212.4180.0

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/9794955/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/9794956/debug.log)

**Comment by ElitePheonix2009** [comment]
https://user-images.githubusercontent.com/114980232/196042995-163d874d-667e-48ca-af86-3adc2b79d3dd.mp4

**Comment by yaichenbaum** [comment]
Is this an issue in the preview build?

**Comment by verdaderoken** [comment]
> Is this an issue in the preview build?

Preview build works fine for me

**Comment by ElitePheonix2009** [comment]
> Is this an issue in the preview build?

I am using the stable build.
