### ISSUE TITLE
Bug: File name column has a max width

### ISSUE THREAD

**Issue by Jimmy20220531** [files-community/Files#10230]
### Description

I can't stretch the file name column past a certain width This is very confusing to me. Uninstalling and reinstalling is still the same.

### Steps To Reproduce
1. Open folder in the details layout
2. Try resizing the name column as wide as possible

### Steps to fix
- Remove the max width

### Files Version
v3.3.12

### Windows Version

Win 10 21H2

**Comment by ferrariofilippo** [comment]
Should this be applied to all columns or just to the name?

**Comment by Jimmy20220531** [comment]
> Should this be applied to all columns or just to the name?
I can only ask the problem, but I am not enough to solve it.

**Comment by ferrariofilippo** [comment]
> I can only ask the problem, but I am not enough to solve it.

I know how to solve it, but this is an issue of all columns. I want to know if you think the width limit shoul be removed from all columns

**Comment by Jimmy20220531** [comment]
> > I can only ask the problem, but I am not enough to solve it.
> 
> I know how to solve it, but this is an issue of all columns. I want to know if you think the width limit shoul be removed from all columns
just to the name is much enough, Thank you so much.
