### ISSUE TITLE
Indicate the current layout mode

### ISSUE THREAD

**Issue by XPoppyX** [files-community/Files#1023]
concept:
![Captura de pantalla 2021-01-05 184523](https://user-images.githubusercontent.com/61259627/103703590-8f1a2780-4f86-11eb-8d60-045f8d953722.jpg)

**Comment by SOI7** [comment]
What if the current layout mode icon replaces the layout menu icon on the status bar?

**Comment by yaichenbaum** [comment]
@SOI7 Having a unique icon not specific to any layout mode indicates that the button it to select a layout mode, if the icon changed with the layout mode, it might cause confusion to the user.

**Comment by yaichenbaum** [comment]
@XPoppyX This enhancement will be implemented with #3159.

**Comment by mdtauk** [comment]
Should the layout button itself, display the icon of the currently chosen layout mode?
