### ISSUE TITLE
Cannot open .zip file through default association

### ISSUE THREAD

**Issue by FineWolf** [files-community/Files#10237]
### Description

When Files is associated as a default application for `.zip` files, opening them will return a "No such interface supported" error.

![image](https://user-images.githubusercontent.com/203591/196068343-68ab872f-322c-436f-b644-bb973a67eae1.png)

### Steps To Reproduce

1. Associate through Apps › Default apps in the control panel `.zip` files to files.
    ![image](https://user-images.githubusercontent.com/203591/196068421-c7607e2f-2f42-413d-ac26-24fd3e25e867.png)
2. Try to open a `.zip` file. The above error is thrown. No logs is generated by Files.

### Steps to fix

- `.zip` files opened through the normal shell process when Files is set as the default handler for that type should open without an error message.

### Files Version

Version: 2.3.12.0 OS Version: 10.0.22621.674

### Windows Version

Windows 11 22H2 (OS Build 22621.674)

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/203591/196068343-68ab872f-322c-436f-b644-bb973a67eae1.png)
![image](https://user-images.githubusercontent.com/203591/196068421-c7607e2f-2f42-413d-ac26-24fd3e25e867.png)

(Logs were deleted prior to testing and no `debug.log` or `debug_fulltrust.log` files were generated when the error was triggered).

**Comment by Josh-65** [comment]
Is this an issue in the preview version? https://files.community/download/preview

**Comment by Josh-65** [comment]
if Files is set as default, then any time a zip is opened in File explorer it will open Files instead.

**Comment by FineWolf** [comment]
> if Files is set as default, then any time a zip is opened in File explorer it will open Files instead.

Which is the desired behavior when setting Files as the default application; not the error message above.
