### ISSUE TITLE
 Feature: Switch between folders in dual pane view with a shortcut

### ISSUE THREAD

**Issue by xnanitex** [files-community/Files#10245]
### What feature or improvement do you think would benefit Files?

Would be nice to switch between dual pane folders without using a mouse (as well and toggling it on or off). 
The dual pane view feature is well-known since Total Commander (no doubt, a classical file explorer) and probably many users would love to try this out in a new way, so that the adding a keyboard shortcut in Files would facilitate this kind of use.

### Requirements

**This proposal will**

- accomplish switching between two panes without a need of using a mouse.
- foster **Drag&Drop** actions.
- make more users happy.

### Files Version

Version: 2.3.12.0

### Windows Version

Windows 10 21H2 19044.2130

### Comments

Collaterally, toggling the dual pane view on and off with a shortcut would make this feature look complete.

**Comment by yaichenbaum** [comment]
> accomplish switching between two panes without a need of using a mouse.

What shortcuts does Total Commander use?

**Comment by yaichenbaum** [comment]
The tab key is used to switch the focus between UI elements so that won't work here.

**Comment by yaichenbaum** [comment]
We can easily use a shortcut like `ctrl` + `shift` + `alt` + `F1' but it's not going to be useful if it doesn't make sense. It's sometimes helpful to look at other apps to see how they handle this.

**Comment by gave92** [comment]
We already have this, don't we? Should be Ctrl+Shift+Left/Right arrow key iirc.
