### ISSUE TITLE
Code Quality : Duplication of FileTagHelper

### ISSUE THREAD

**Issue by QuaintMako** [files-community/Files#10248]
There is currently two FileTagsHelper coexisting in the code. One in `Files.App.Helpers` and the other in `Files.App.Filesystem`. 

They share multiple methods with the same signatures, however their implementations are somewhat different.

The two helpers should be merged into only one contained in `Files.App.Helpers`.

Extra attention must be taken to ensure the merge of the shared methods.

**Comment by hez2010** [comment]
Noticed and I'm working on it currently.

**Comment by QuaintMako** [comment]
Perfect, thanks for bringing it up!
