### ISSUE TITLE
Bug: Drives section has the wrong order

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#10252]
### Description

The Drives section sometimes appears in the wrong order (with c: last), while the home page is correct.
The order should be by letter and not by discovery. The C: drive sometimes appears last.

### Steps To Reproduce

For C:, I do not know. It seems random, half the time.

The bug can be seen as follows:
1) Connect a USB key.
2) Connect a second USB key.
3) Remove the first USB key.
4) Reconnect the first USB key.
It appears with the initial letter but in last position. The order is no longer correct.

### Steps to fix

Drives are added in the order of discovery. The position should be forced when adding a drives. I can do it.

### Files Version

dev #eabf72e

### Windows Version

Windows 11 22621.674

### Relevant Assets/Logs

![drives1](https://user-images.githubusercontent.com/46631671/196753275-dad0a4e7-7eee-4f12-bfed-3dcd9cfb0a33.png)

**Comment by yaichenbaum** [comment]
This looks good, feel free to open a PR.
