### ISSUE TITLE
Add support for send to option

### ISSUE THREAD

**Issue by ElitePheonix2009** [files-community/Files#10251]
### What feature or improvement do you think would benefit Files?

I will like to customize the context menu using a app, and the app puts the custom context menu items in the send to option. So, pls support the send to option.

### Requirements

- Add send to option to the context menu.
- Add all the options inside the send to option available in file explorer.

### Files Version

Version: 2.3.12.0 OS Version: 10.0.19044.2130

### Windows Version

Edition	Windows 10 Pro Version	21H2 Installed on	‎15-‎09-‎2022 OS build	19044.2130 Experience	Windows Feature Experience Pack 120.2212.4180.0

### Comments

![image](https://user-images.githubusercontent.com/114980232/196721704-97a636ec-6caa-42c6-b1e8-e919b17d3112.png)

**Comment by yaichenbaum** [comment]
Merging with #7350
