### ISSUE TITLE
Bug: Clicking preferences in settings causes network drives to load again

### ISSUE THREAD

**Issue by Abell1656** [files-community/Files#10256]
### Description

As soon as you switch to the "presets" tab in the settings, Files is automatically adding network drives for the unused drives (drive letters).

### Steps To Reproduce

* precondition: some network drives have to be defined

* open the settings and change over to the "presets" - tab
* as soon as the tab has become active Files will start to fill all unused drives (drive letters) with already network connections
* at the end you'll see umpteen duplicated network drives

### Steps to fix

- don't add duplicate drives

### Files Version

Version: 2.3.48.0

### Windows Version

OS Version: 10.0.22000.1098

### Relevant Assets/Logs

https://user-images.githubusercontent.com/116265116/196912842-49a3e940-842b-4dab-8ac3-49bb53ba1b8d.mp4

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by Abell1656** [comment]
I've updated to Version: 2.3.57.0, but the mentioned problem still remain - after pressing preferences new network drives will be added. The only obvious difference is, that the windows desktop does not flash anymore.

**Comment by yaira2** [comment]
This issue should be resolved in the latest preview build (v2.5.30).
