### ISSUE TITLE
The width of the "file tag" in the details layout is too wide

### ISSUE THREAD

**Issue by tangtao199511** [files-community/Files#10257]
Thank you so much for developing such a good-looking and handful file app. I want to replace it with the original file explorer.

But I am so sorry that there might be some imperfects in the latest version.

1. The width of the "file tag" **in the details layout** is too wide, and the default width of all the colunms are not customizable. Every time I directed to a new location, the width of the columns turns back to the default one. as shown below:

![image](https://user-images.githubusercontent.com/44110508/196973419-57740a1d-42ee-4908-9d94-fbfe4b13b950.png)

2. It is sad that the speed of showing items in this app is not as fast as the original one, especially there are thousands of items in one directory.

I will be so happy and appreciate you if these two issues can be solved, then this app will definately become my default file explorer app. Thank you again for developing such a good app! ♥

**Comment by yaichenbaum** [comment]
> The width of the "file tag" in the details layout is too wide, and the default width of all the colunms are not customizable. Every time I directed to a new location, the width of the columns turns back to the default one. as shown below:

The latest preview build allows you to set the default width of columns (it still allows you to override the default widths in individual directories).

> It is sad that the speed of showing items in this app is not as fast as the original one, especially there are thousands of items in one directory.

The preview build has a number of performance improvements but please be advised that there may be unexpected issues with this build. https://files.community/download/preview

**Comment by tangtao199511** [comment]
Thank you very much. I will try it on immediately.

 

Best
