### ISSUE TITLE
Bug: Tabs have wrong text in dual pane layout

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#10265]
### Description

In dual panel mode, the tab labels show the 2 open folders. But when we change the folder of the right panel, the title of the left panel also changes. This is not the case when modifying the left panel.

### Steps To Reproduce

1. Open folder 1 in left panel and folder 2 in right panel.
2. Give the focus at the right panel.
3. Open folder 3 in the right panel.
4. The tab label is "folder 3 | folder 3" instead of "folder 1 | folder 3".

### Steps to fix

- Do not modify the first panel in the title of the tab when modifying the second panel.

### Files Version

dev commit 7a5262f

### Windows Version

Windows 11 22621.674

### Relevant Assets/Logs

Here, the first panel is not the homepage, but it is nevertheless what is indicated in the tab.

![tab](https://user-images.githubusercontent.com/46631671/197055890-02bc1f8b-6747-48d7-ad72-c74af6c380ac.png)

**Comment by yaichenbaum** [comment]
@lukeblevins is this resolved by your refactor work?

**Comment by lukeblevins** [comment]
@yair100 Yes, it should overhaul that behavior. Regardless, you can assign this one to me.

**Comment by ferrariofilippo** [comment]
@yair100 this seems to be fixed

**Comment by yaira2** [comment]
@cinqmilleans can you confirm?

**Comment by cinqmilleans** [comment]
I confirm. This is fixed (tested with the preview).
