### ISSUE TITLE
Files crashes after opening and closing the properties of a file or folder

### ISSUE THREAD

**Issue by Tarog** [files-community/Files#10267]
### Description

After right clicking a file or folder and selecting prooperties, closing out of the properties window crashes the app.

### Steps To Reproduce

1.right click any file or folder
2. selecr properties
3. exit out of the properties window

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

files 2.3.12.0

### Windows Version

Windows 10 21H2

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/9838010/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/9838011/debug.log)

**Comment by yaichenbaum** [comment]
This is fixed in the latest preview version
