### ISSUE TITLE
Bug: Properties window for drives displays the drive letter in the name text box

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#10263]
### Description

The properties textbox for renaming a drive initializes the field with the drive letter (ex: "SSD (D:)"). If the name changes, it is used to rename and Windows adds the path to it. It is therefore necessary to delete the useless path to rename it.

### Steps To Reproduce

1. Open the properties of a fixed drive.
2. The textbox of name contains the name and the path.

### Steps to fix

- Initialize field with name without path.
- The popup will no longer contain the path. It should be displayed elsewhere.

### Files Version

dev commit 7a5262f

### Windows Version

Windows 11 22621.674

### Relevant Assets/Logs

![EditDrive](https://user-images.githubusercontent.com/46631671/197020316-be8aa2af-3466-43ae-8c6a-d2fe37535e8f.png)

**Comment by yaichenbaum** [comment]
> It should be displayed elsewhere

Where should it be displayed and should it be displayed at all?

**Comment by cinqmilleans** [comment]
You can simply remove the path when editing. Here is a mockup.

https://user-images.githubusercontent.com/46631671/197225832-e27acaaa-e016-4e6e-a006-434fbbe2b554.mp4

**Comment by yaichenbaum** [comment]
We can try that behavior, it might be confusing but we can see how it works.

**Comment by Josh-65** [comment]
Having the path there doesn't cause issues when renaming for me it. it will remove the path if there when setting the name.
