### ISSUE TITLE
Scroll wheel doesn't work in context menu when x-mouse button control is active

### ISSUE THREAD

**Issue by lucky-ly** [files-community/Files#10264]
### Description

I use X-mouse Button Control to disable annoying back/forward behaviour of 4/5th mouse buttons. But if XMBC is active, I can't scroll context menus with scroll wheel in Files. Scrolling works fine in all other places (mail files list, left panel, preferences, etc).

### Steps To Reproduce

1. Install and launch X-Mouse Button Control
2. Set "Move overflow items into a submenu" to "Off" in Files
3. Right-click on file/folder/empty space
4. Wait until all menu items are loaded and scrollbar appeared
5. Try to scroll the menu with scroll wheel

### Steps to fix

Make scroll wheel work in context menus when x-mouse button control is launched

### Files Version

Version: 2.3.12.0 OS Version: 10.0.19042.1706

### Windows Version

Windows 10 Pro 20H2 19042.1706

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9833247/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9833248/debug_fulltrust.log)

https://user-images.githubusercontent.com/4019526/197038448-0f3e1846-ec7b-4d42-bc57-0a5184945d41.mp4

**Comment by yaira2** [comment]
Thank you for your feedback, this appears to be an issue with the WinUI control, can you open an issue on their repository?

**Comment by rtxbae** [comment]
I have similar problem. I don't think x-mouse button control have any tickets system since it's not open source. @lucky-ly have you found any solution?

**Comment by rtxbae** [comment]
Interesting, that actually works!

**Comment by S-codex** [comment]
> [@rtxbae](https://github.com/rtxbae) I didn't check, but there's one workaround that might work, since it works with Yandex Browser, which apparently suffers from the same problem. You can create separate profile for Files app process in x-mouse button control and in that profile check "Disable Scroll Window Under Cursor" checkbox on Options tab.

Thank you so much! I had issues with using touchpad on firefox with X-Mouse Button enabled. This fixed it.
Update : Sorry, I was mistaken. The actual solution was to revert Wheel Up and Wheel Down to default (do not intercept) . For some reason my touchpad which has precision drivers emulates Wheel Up and Wheel Down while swipe-scrolling
