### ISSUE TITLE
Feature: Display drive letter of the connected network drives

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#10261]
### What feature or improvement do you think would benefit Files?

It is possible to assign a letter to a network drive. It then appears in the local drives but without displaying its letter. I don't know if it's a bug or if it's intentional. It would be convenient to display its drive letter like any other drive. I see no reason not to.

### Requirements

Modify DriveItem.Text for network drives.

### Files Version

dev commit 4e3b8db

### Windows Version

Windows 11 22621.674

### Comments

Drive Z:NVIDIA_SHIELD does not display its letter Z:.
![Drive1](https://user-images.githubusercontent.com/46631671/196993918-2e97c70a-baa9-4861-a969-1c5397642534.png)
![Drive2](https://user-images.githubusercontent.com/46631671/196993921-0479c954-ce30-492a-ac03-566ce94e8eb7.png)
![Drive3](https://user-images.githubusercontent.com/46631671/196993924-e5f67c3c-7b3f-4a05-927e-653d0e9a3d21.png)

**Comment by yaichenbaum** [comment]
It should probably be displayed
