### ISSUE TITLE
Files still believes files are moving when they are done moving

### ISSUE THREAD

**Issue by piotr25691** [files-community/Files#10262]
### Description

When you are moving files with Files, it gets stuck at 0%, and it stays at 0% even after the files are done moving so it never believes it moved anything

### Steps To Reproduce

1. Move a file to another location
2. Click on the button where ongoing actions are shown
3. Experience it showing "0%" regardless of the current file status

### Steps to fix

- When you move a file it should track the progress properly and it cannot get stuck at 0%

### Files Version

Version: 2.3.12.0 OS Version: 10.0.22621.675

### Windows Version

Windows 11 22H2 22621.675

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9832595/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9832596/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by piotr25691** [comment]
> Is this still an issue in the preview version? [files.community/download/preview](https://files.community/download/preview)

I would have to recreate this error again, but then also in that preview version the inte

**Comment by yaichenbaum** [comment]
Can you share a screen recording?
