### ISSUE TITLE
Opening OneDrive page causes all files to be downloaded to device 每次打开OneDrive页面都会使OneDrive下载我的全部文件

### ISSUE THREAD

**Issue by Lord-Balzac** [files-community/Files#10266]
### Description

Everytime I open OneDrive Folder in Files App would sync all my files to my device.
----
每次我在Files内打开OneDrive文件夹都会使OneDrive同步我的所有文件。

### Steps To Reproduce

- Select OneDrive in the left panel and open it
- The OneDrive page will be blank for seconds
- As the file list is shown , the OneDrive app shows that files with only Internet access are being downlaoded
----
- 在左栏中选择OneDrive文件夹以打开
- OneDrive文件夹页面会呈现几秒的空白
- 文件列表加载同时，在OneDrive应用中可以看到OneDrive正在下载原本仅保存在云端的文件

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

Version: 2.3.12.0 OS Version: 10.0.22623.746

### Windows Version

Windows (on Arm)11 22H2 22623.746

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/51845167/197072133-49ad7379-b951-4ed0-b5f3-6aa7543676d6.png)
----
[debug.log](https://github.com/files-community/Files/files/9834363/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9834364/debug_fulltrust.log)

**Comment by Josh-65** [comment]
Can you see if this is an issue in the preview version? https://files.community/download/preview

**Comment by Lord-Balzac** [comment]
> Can you see if this is an issue in the preview version? https://files.community/download/preview

Oops, I can't install the preview version on my device.
![image](https://user-images.githubusercontent.com/51845167/197116600-9422189d-9573-4b2a-8a44-eb3cb4a40c79.png)

**Comment by Josh-65** [comment]
Try restarting your computer and trying it again

**Comment by Lord-Balzac** [comment]
> Try restarting your computer and trying it again

It seems that the issue is gone for now.
