### ISSUE TITLE
Exessive memory usage of runtimebroker.exe trough Files when accessing network drives

### ISSUE THREAD

**Issue by N0C1** [files-community/Files#10277]
### Description

Runtimebroker.exe responsible for checkign universal app permissions bloats memory usage, when accessing network shares trough files app.

In my case up to 8 GB (32 GB RAM).

### Steps To Reproduce

- Open a SMB file location
- Access or open a file (large files increase the effect)

### Steps to fix

Closing the files app lets runtimeborker.exe return to normal, in my case less then 100 MB memory usage.

### Files Version

Version: 2.3.12.0 OS Version: 10.0.22621.675

### Windows Version

Windows 11 Pro Version 22H2 OS 22621.675

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/48812025/197394854-76eb41a7-9d41-4b0c-8252-e97649982258.png)

[debug.log](https://github.com/files-community/Files/files/9846668/debug.log)

**Comment by yaichenbaum** [comment]
Merging with #4180
You can also try the preview build which already has some improvements in this area https://files.community/download/preview

**Comment by N0C1** [comment]
Hi yiachenbaum,

thanks for the suggestion & your great piece of work!
Switched to preview, but the issue persists.
Looking forward to new versions!

**Comment by yaichenbaum** [comment]
Can you send a screenshot? The preview build doesn't use runtime broker.

**Comment by N0C1** [comment]
Hello,

there you go:
![image](https://user-images.githubusercontent.com/48812025/197408996-a9f4e3ca-2fb3-42b9-8d0f-fbdf3fa741c7.png)
[debug.log](https://github.com/files-community/Files/files/9847240/debug.log)
If you need additional files let me know.

I also noticed that it initially downloaded stable, when I clicked Preview on the website.

https://user-images.githubusercontent.com/48812025/197408629-656787ed-d2b0-4401-bc2f-153ae71988cd.mp4
