### ISSUE TITLE
Default file manager Bug

### ISSUE THREAD

**Issue by shadow575bg** [files-community/Files#10270]
### Description

Well I just installed today Files and want to try if I use the ,Set Files as the Default file manager,
But when I have (RuntimeBroker.exe errors every time) Then i wanted to use the standard file manager but then i get this error
(View Image 1, If Someone want to see My RuntimeBroker.exe error is - ShareX_TPXrE2OCw0)
Is there any fix to this?

 And The Sad Think i need to be with Files until you fix my bug

### Steps To Reproduce

1. Go to Options
2. Experimental
3. Turn On ,Set Files as the Default file manager`
4. Turn off ,Set Files as the Default file manager`
5. Ur Pc Is broken

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

Version: 2.3.12.0 OS Version: 10.0.19045.2075

### Windows Version

Windows 10 22H2 (OS Build 19045.2075)

### Relevant Assets/Logs

![Image 1](https://user-images.githubusercontent.com/86497295/197244182-ba440655-45ab-4a35-a227-f140dc20be62.png)
![ShareX_TPXrE2OCw0](https://user-images.githubusercontent.com/86497295/197244232-009abb96-99c2-4f20-ab0e-40ac057fe0de.png)

**Comment by yaichenbaum** [comment]
Thank you for your feedback, this might be fixed in the preview version, but we don't have any plans to continue tracking this issue https://files.community/download/preview as we're hoping Microsoft will provide an official solution for changing the default file manager.
