### ISSUE TITLE
Add a more compact view

### ISSUE THREAD

**Issue by richardvlittlewood** [files-community/Files#10278]
### What feature or improvement do you think would benefit Files?

The spacing between items in the list view is excessive, even with the "compact styles" option selected. This requires more scrolling to see the same number of lines. The app should support a view at least as compact as windows 10 file explorer.

### Requirements

Modify compact styles option to offer an extra level of compactness

### Files Version

2.3.12.0

### Windows Version

Windows 10

### Comments

The current line spacing would stop me using this otherwise promising app.

**Comment by yaichenbaum** [comment]
This is resolved in the preview build https://files.community/download/preview
