### ISSUE TITLE
Bug: Always open new tabs in dual pane doesn't work on startup

### ISSUE THREAD

**Issue by h3x1e** [files-community/Files#10276]
### Description

Dual Pane view is enabled in settings, when opening Files App both panes are no visible.

Tab indicates that there is a second pane open.

Switching to compact view then back to normal view causes the second panel to show correctly.

Opening new tab does not activate Dual Panel view.

### Steps To Reproduce

- Go to settings > Multitasking > Check Enable dual panel view + Always open new tabs in dual pane mode.
- Close Files
- Open files (Dual pane does not show)
- Use Ctrl + Alt + UpArrow to go into compact mode
- Use Ctrl + Alt + DownArrow to go into normal mode
- Dual Pane will now show on active tab.

### Steps to fix

Switch to compact view then back to normal view will enable that tabs dual panel.
or
Click 3 dots  > Close Pane > Open new Pane

### Files Version

Version: 2.3.12.0 OS Version: 10.0.22621.675

### Windows Version

Windows 11 Pro 22H2 10.0.22621

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9846177/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9846178/debug_fulltrust.log)

Image showing single pane, but tab does show second pane is active.

![image](https://user-images.githubusercontent.com/26570942/197385582-662993c1-fc96-4592-924b-5895f9d2f425.png)

**Comment by matthiscock** [comment]
Similar, but not the same reported here:
https://github.com/files-community/Files/issues/10449

**Comment by h3x1e** [comment]
Yeah, sorry, this has been fixed now.
