### ISSUE TITLE
Not working Drag and drop files in FL studio

### ISSUE THREAD

**Issue by hc2cr7** [files-community/Files#10279]
### Description

I am trying to drag a .wav audio file into FL studio but FL studio not accepting the file through Files app, but drag and dropping the same file through windows file explorer is working, I tried drag and dropping the same file with Files to other software and its working, only having issue with FL studio 

### Steps To Reproduce

Just drag and drop an audio file into FL studio

### Steps to fix

no fix

### Files Version

Version: 2.3.12.0 OS Version: 10.0.19044.2130

### Windows Version

Windows 10 Pro 21H2 19044.2130

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9846788/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9846789/debug_fulltrust.log)

**Comment by verdaderoken** [comment]
Same issue with [#9788](https://github.com/files-community/Files/issues/9788)


Related: 
Drag & drop also doesn't work in Messenger Desktop using Files app

**Comment by Josh-65** [comment]
Can you see if this is an issue in the preview version? https://files.community/download/preview

**Comment by verdaderoken** [comment]
> Can you see if this is an issue in the preview version? https://files.community/download/preview

Yes, still an issue in the preview version
![image](https://user-images.githubusercontent.com/88200096/197460242-34068f70-d542-4b42-aec9-b01d14e2f064.png)

**Comment by yaichenbaum** [comment]
This will be fixed in v2.4 or v2.5
