### ISSUE TITLE
Feature: Update themes

### ISSUE THREAD

**Issue by DeveloperWOW64** [files-community/Files#10281]
### What feature or improvement do you think would benefit Files?

Some themes (Modern House, Bound to Be Blue, Luxury Red) need to be updated to the latest schemas and/or be abandoned.

### Requirements

_No description provided_

### Files Version

Version: 2.3.12.0

### Windows Version

Windows 11 Insider Beta 22H2 22623.870

### Comments

Fixed by: #10275

**Comment by yaichenbaum** [comment]
What are the issues with those themes and what do you think will solve them?

**Comment by DeveloperWOW64** [comment]
> What are the issues with those themes and what do you think will solve them?

* They have outdated template
* Modern House needs to exist
* Luxury Red needs to not exist

**Comment by yaichenbaum** [comment]
> They have outdated template

What do you mean by outdated template?

> Modern House needs to exist
> Luxury Red needs to not exist

I'm not sure I'm following, can you explain what you mean by this?

**Comment by DeveloperWOW64** [comment]
> What do you mean by outdated template?

@onein528:
> "Also, I notice that Files no longer doesn't support old theme resources."

> I'm not sure I'm following, can you explain what you mean by this?

Previously, I wanted to implement the Modern House theme (see old themes repo), which used outdated template, so I wanted to add it.

Luxury Red isn't really visually appealing and is too extreme in the way the light is displayed, so I wanted to remove it.

**Comment by yaichenbaum** [comment]
> Previously, I wanted to implement the Modern House theme (see old themes repo), which used outdated template, so I wanted to add it.

We're not adding additional themes to the app at this time.
