### ISSUE TITLE
Bug: Exception is thrown when previewing html files

### ISSUE THREAD

**Issue by 0x5bfa** [files-community/Files#10280]
### Description

https://github.com/files-community/Files/blob/d4bb3e867cf7f52bf9ddc184501a993e3ccb40c5/src/Files.App/UserControls/FilePreviews/HtmlPreview.xaml.cs#L10-L25

In my other app's tests, even if I called Ensure-- method before calling NavigateToString, WebView2 throw an exception that is something like 'Method was called unexpected time'. So notice that WebView2 is still  surprisingly unstable and has bad developer experience.

`https://github.com/microsoft/microsoft-ui-xaml/issues/3714`

### Steps To Reproduce

1. Go to the directry that contains html file.
2. View its preview

### Steps to fix

- As the title: call EnsureCoreWebView2Async before calling other WebView2-related methods such as navigateToString.

### Files Version

Latest version

### Windows Version

Windows 11 21H1

### Relevant Assets/Logs

Although I added like following screenshot, sometimes still WebView2 doesn't load its own html string with an exception InvalidOperationException.

![image](https://user-images.githubusercontent.com/62196528/197399026-f7a55a02-9d4f-433c-9159-a3456f9afbb6.png)

**Comment by yaichenbaum** [comment]
Is this a bug report or code quality issue?

**Comment by hez2010** [comment]
It's a bug. We should ensure CoreWebView getting loaded.

**Comment by onein528** [comment]
No a bug basically. It's a spec. but failing even though you added ensuring method is a bug.

**Comment by yaichenbaum** [comment]
Do you want to open a PR for this?

**Comment by onein528** [comment]
Of course, I would do. However I have little time these days.

**Comment by ferrariofilippo** [comment]
@yair100 I can't reproduce this bug anymore. It seems this was fixed back in #10573
