### ISSUE TITLE
Feature: Toggle legacy copy dialog

### ISSUE THREAD

**Issue by CamTheHelpDesk** [files-community/Files#10282]
### What feature or improvement do you think would benefit Files?

While I appreciate the simple "Ongoing Tasks" menu, I do appreciate the default Windows copy dialog, especially when I'm copying large files, as it allows me to see what exactly is going on and identify what files are failing.

A toggle between the ongoing tasks menu and legacy copy dialog would solve this issue.

### Requirements

- Create a settings toggle that allows the user to select between the new "Ongoing Tasks" menu and the legacy Windows copy dialog.

### Files Version

2.3.12.0

### Windows Version

Windows 11 Pro 22H2 22621.674

**Comment by yaichenbaum** [comment]
Merging with #6825 #4811
