### ISSUE TITLE
Allow to set Files as default file explorer only for the current user

### ISSUE THREAD

**Issue by kaname-png** [files-community/Files#10296]
### What feature or improvement do you think would benefit Files?

Currently when you enable the option to set Files as the default file manager, it applies that option to all users of the computer, so if a user does not have Files installed then Windows throws an error that the application is not installed.

This way you can choose which users want to set Files as the default file explorer and which do not.

### Requirements

I don't know.

### Files Version

Versión: 2.3.12.0

### Windows Version

OS Version: 10.0.22621.675

**Comment by Josh-65** [comment]
This is fixed in the preview version? https://files.community/download/preview
When downloaded just turn the toggle on > then off > then on to get the updates.
