### ISSUE TITLE
Code Quality: Duplication in ModernShellPage and ColumnShellPage

### ISSUE THREAD

**Issue by QuaintMako** [files-community/Files#10304]
### Description

Some code is duplicated between `ModernShellPage.xaml.cs` and `ColumnShellPage.xaml.cs`. Sometimes it's entire methods, sometimes it's only partial bits.

We should look into fusing the two classes into an `abstract class BaseShellPage` to regroup the duplicates.

### Concerned code

- ModernShellPage.cs
- ColumnShellPage.cs

### Gains

- Better maintainability. 
- No need to do the same modifications twice when we want to add a functionality to the two pages.

### Requirements

- Regrouping the duplicated code into an `abstract class BaseShellPage`.

**Comment by yaichenbaum** [comment]
I believe @lukeblevins has some ideas on this but it doesn't hurt to write them down.

**Comment by lukeblevins** [comment]
This should have been informed by the work that's in progress. The PR for it is open already as a draft. I'd prefer if we used that work instead.
