### ISSUE TITLE
Very good Explorer Alternative, but very, very slow!

### ISSUE THREAD

**Issue by TheNopCrafter** [files-community/Files#10307]
### Description

Files is really a good explorer, bur also very slow. If you switch between folders in the menu on the right, it lags. I have also tried in the Preview version…. it is a little, little bit better. But the same thing is if you go into an under folder, and another etc. It is much too slow… But at first, the "slowness" did not touch me but when I wanted to copy some data this takes of a gigabyte on a SSD four Minutes or more. And when I open .zip files, then I only have to wait. It is soo slow. It would be very good, if you make it faster and a better use experience. Because the features and the design is AWESOME! :D

### Steps To Reproduce

1. Copy a file
2. Or, Open different folders
3. Or do something in a Zip file

### Steps to fix

- Faster Switching between folders
- In all a faster experience
- Faster copying/other actions
- Faster working with Zip Files

### Files Version

Version: 2.3.12.0 OS Version: 10.0.22621.675

### Windows Version

Windows 11 22H2

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9872041/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9872042/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
Merging with #4180

**Comment by Josh-65** [comment]
Speed improvements are always being made. You can try the preview builds https://files.community/download/preview as it's faster.

**Comment by timluther** [comment]
Agreed, the app is extraordinarily slow when opening directories - obviously it's doing something expensive each time.
I'm doing my own investigations, I have Files compiling locally. 
Here's a speed capture I made using 'Very sleepy'
[files_speed_capture.csv](https://github.com/files-community/Files/files/9893424/files_speed_capture.csv)

And here's a video showing just how slow it is. Explorer is instant when navigating. Files should be instant also.
https://user-images.githubusercontent.com/4411129/198825791-e4f11fb8-ce2e-40c7-92b1-5c4ccf47f98e.mp4

**Comment by yaichenbaum** [comment]
I can't access those recordings (you should be able to upload them directly to GitHub) but as Josh mentioned, performance is constantly being improved. Navigating to different directories in the latest preview build is significantly faster than the current stable release. I recommend installing the latest preview build and comparing to the latest stable build.

**Comment by yair100** [comment]
@timluther we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
