### ISSUE TITLE
Bug: Archive information is not shown when open

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#10301]
### Description

Date created, Date modified, and File sizes are shown as 0. 7z and I presume RARs will have the icons blank.
![image](https://user-images.githubusercontent.com/26977075/197961137-1e6d465b-b795-4dd7-8a33-2a570f193f49.png)

### Steps To Reproduce

Open a 7z archive

### Steps to fix

?

### Files Version

2.3.51.0

### Windows Version

10.0.22621.675

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9867098/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9867099/debug_fulltrust.log)

**Comment by cinqmilleans** [comment]
The library used, SevenZipExtractor, returns the current date for CreationTime and LastAccessTime. It only has LastWriteTime, which is the date of the file. The size is always 0.

If necessary we can display the date of the file, or display nothing if we have no relevant information.

**Comment by gave92** [comment]
Fixed by #10563, #10564
