### ISSUE TITLE
Bug: Folder with zips in loads quite slowly

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#10300]
### Description

I have a folder with 14 zip archives in and it takes about 10 seconds for it to load but after when going in and out of the folder its instant. This seems to only happen after a computer restart or Files update.

### Steps To Reproduce

1. Create a folder with 10+ archive files
2. Restarting computer
3. Navigate to the folder of archives

### Steps to fix

?

### Files Version

2.3.51.0

### Windows Version

10.0.22621.675

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9867098/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9867099/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
Is this folder set as the startup tab?

**Comment by Josh-65** [comment]
No, I just navigate to it like normal

**Comment by yaichenbaum** [comment]
Does this happen with the default app settings?

**Comment by Josh-65** [comment]
No. I'll try see what setting makes it slow.

**Comment by yaichenbaum** [comment]
Is it calculate folder sizes?

**Comment by Josh-65** [comment]
Nope it still very slow. The reset might of just being a onetime thing since I can't get it to do that again. There also doesn't seem to be a setting making it that way.

**Comment by Josh-65** [comment]
I've found this happens will .dll too.

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by Josh-65** [comment]
Yes

**Comment by Josh-65** [comment]
This seem to be fixed in 2.4.24.0
