### ISSUE TITLE
Contenedores: Se pierde la configuración de carpetas

### ISSUE THREAD

**Issue by CarlosCevallos** [files-community/Files#10313]
### Description

Se pierde la configuración de carpetas al crear un Contenedor.

Me despido, sin antes, agradecerles por este programa que me parece fabuloso !.
Muchas gracias por este grandísimo aporte.

### Steps To Reproduce

1.- Abrir el "Files"  ( Versión: 2.3.12.0 OS Version: 10.0.19044.2132  )
2.- Click en boton "..." y "Crear Contenedor"
3.- Dentro del Nuevo Contenedor,  dar clik en "Agregar elemento" / "Agregar carpeta"
4.- Agregar alguna carpeta
5.- Salir del programa "Files"
6.- Volver a abrir el programa "Files"
7.- El contenedor esta vacío. El elemento "carpeta" agregado no figura.

### Steps to fix

Debo repetir los pasos a partir del paso 3 (agregar elemento / carpeta"

### Files Version

Versión: 2.3.12.0 OS Version: 10.0.19044.2132

### Windows Version

Windows 10 versión 21H2 (compilación SO 19044.2132)

### Relevant Assets/Logs

![files-2](https://user-images.githubusercontent.com/10996684/198325923-d41b134e-f85a-4627-8b63-d256a20a9076.png)

**Comment by gave92** [comment]
Thanks for the report. I'm closing this as we're in the process to replace Bundles with the file tags feature.
