### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by silversparker** [files-community/Files#10315]
First of all, thanks for creating the app, I love to use it.

I just have a little suggestion or rather a question regarding your pre-installed themes. I love to use the glass theme but whenever the files windows is inactive, the semi-transparent background gets replaced by a black background. Is there any way around this or could you change that in the next release? I didnt find anything in the documentation about custom themes. Thank you very much. Greetings from Germany!

**Comment by gave92** [comment]
Happy you like Files:) Unfortunately this is a system limitation. Windows turns off transparency if an app is not on the foreground.
