### ISSUE TITLE
Cannot unmount virtual disk images.

### ISSUE THREAD

**Issue by foxxyboy16** [files-community/Files#10314]
### Description

Cannot unmount virtual disk images.

### Steps To Reproduce

1. Go to the appropriate folder where your .iso image located 
2. Click on Mount and mount an iso image
3. Unmount iso image
Actual result:
Image cannot unmount properly

Expected result:
Image should be unmounted.

### Steps to fix

Release the proper update.

### Files Version

Version 2.3.12

### Windows Version

Windows 10 22H2

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/58509576/198326064-c8d299c5-d400-4232-a7bf-4dd9c7f6f517.png)

**Comment by Josh-65** [comment]
Merging with #10154
