### ISSUE TITLE
Replace dialog on ftp-servers and net-drives

### ISSUE THREAD

**Issue by SimonL888** [files-community/Files#10312]
### What feature or improvement do you think would benefit Files?

Please include a dialog if one want to replace a file when working on a network-drive. Now there is always coming up a copy of the file and no dialog or option to replace files or to decide on that behavior.

### Requirements

-New dialog on net drives to replace files or overwrite them

### Files Version

Version: 2.3.12.0 OS Version: 10.0.22000.1165

### Windows Version

Windows 11

**Comment by gave92** [comment]
Merging with #8609
