### ISSUE TITLE
Column mode improvements

### ISSUE THREAD

**Issue by CarlosCevallos** [files-community/Files#10316]
### What feature or improvement do you think would benefit Files?

1.- You can move the separation lines of the columns dynamically.
2.- Modify the font size of file names.

### Requirements

You could see the full names of the files or folders with better clarity

![files-2-col](https://user-images.githubusercontent.com/10996684/198381994-69b42b8e-a261-489e-88a0-78583fc75f3e.png)

### Files Version

Versión: 2.3.12.0 OS Version: 10.0.19044.2132

### Windows Version

Windows 10 versión 21H2 (compilación SO 19044.2132)

**Comment by yaichenbaum** [comment]
Merging with #6534

**Comment by CarlosCevallos** [comment]
Excuse my ignorance please, I would like to understand...
You are closing this message because
1.- is not important now?
2.- Will it be taken into account in another version?
3.- Have the settings already been made? ..if so ...where or how do I configure it?

Could you guide me please?

**Comment by yaichenbaum** [comment]
We're tracking this feature request in an existing issue.
