### ISSUE TITLE
Dual panel view doesn't have 'memory'  when 'Continue where you left off' option is selected

### ISSUE THREAD

**Issue by WilliamDelRey** [files-community/Files#10317]
### Description

Dual panel view doesn't have 'memory'  when 'Continue where you left off' option is selected, the expected behavior is with dual panel enabled to reopen both panels

### Steps To Reproduce

1. Select 'Continue where you left off' option in startup setting
2. Enable dual panel view
3. Add a second panel
4. Close Files
5. Open Files

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

Version 2.3.12.0

### Windows Version

Windows 11 Pro 21H2 Build: 22000.1098

### Relevant Assets/Logs

-

**Comment by Josh-65** [comment]
Can you see if this is an issue in the preview version? https://files.community/download/preview

**Comment by WilliamDelRey** [comment]
It works like a charm! Great work!!!
