### ISSUE TITLE
Bug: Localization switching back to Default on DetailsBrowser

### ISSUE THREAD

**Issue by QuaintMako** [files-community/Files#10320]
### Description

When opening a view in Details Browser, when the view is done loading, all the items localization switch back to the default language.

### Steps To Reproduce

1. Go into Settings and set any language other than default (to better see the issue)
2. Switch back to any tab and open a folder with several different object.
3. Observe the localization going from selected language to the default language.

### Steps to fix

- The localization stays to the default language.

### Files Version

Version : 2.3.48.0 OS

### Windows Version

W11 21H2 Version: 10.0.22000.1098

### Relevant Assets/Logs

![BrokenLoca](https://user-images.githubusercontent.com/110472580/198686371-e99dcbae-294d-4180-9482-5dc57cd4e663.gif)

**Comment by QuaintMako** [comment]
Looking at the gif, there may be a bunch of stuff broken regarding the localization. Can I see the buttons under the Favorites and the date of modification. But it may be because my computer's language is set to English.

**Comment by yaichenbaum** [comment]
Favorites work off of the folder names

**Comment by yaichenbaum** [comment]
See #1586 for reference

**Comment by yaichenbaum** [comment]
We're going to leave this as is
