### ISSUE TITLE
Bug: Items in File in use model are shown twice

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#10321]
### Description

![image](https://user-images.githubusercontent.com/26977075/198741733-f505daa4-0502-40d2-a8a4-ce246f113863.png)

### Steps To Reproduce

1. Open a file that gets locked by program
2. Attempt to delete it
3. See the file shown twice in the dialog

### Steps to fix

Scan for and display items only one in model

### Files Version

2.3.52.0

### Windows Version

10.0.22621.675

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9892266/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9892267/debug_fulltrust.log)

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.
