### ISSUE TITLE
Random Crashes

### ISSUE THREAD

**Issue by Bluemethyst** [files-community/Files#10328]
### Description

Randomly crashing every few minutes for no reason, I've checked logs and no errors even show up, Please fix I love your product

### Steps To Reproduce

Just use the app for more then 3 mins or so

### Steps to fix

Just reopen the app and it wont do it for another 3 mins or so

### Files Version

Version: 2.3.12.0 OS Version: 10.0.19044.2130

### Windows Version

Edition	Windows 10 Home Version	21H2 Installed on	‎02/‎12/‎2021 OS build	19044.2130 Experience	Windows Feature Experience Pack 120.2212.4180.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9894966/debug.log)

**Comment by yaichenbaum** [comment]
Thank you for your feedback, I'm having a hard time reproducing this issue. Is there a specific action that is causing the app to crash?

**Comment by Bluemethyst** [comment]
Nothing, absolutely nothing, just browsing through my documents folder and it just randomly crashes, im sorry but thats all that seems to be happening

**Comment by Bluemethyst** [comment]
I just tested this on my phone and yes that does seem to trigger it, i was just moving some photos around. I was also going through one of my game directories managing my mods and it crashed again, the games files are all on my C drive so im not sure of the issue there

**Comment by yaichenbaum** [comment]
Can you verify that these are the steps to reproduce the issue?
1. Connect phone to computer
2. Open phone directory in Files
3. Move photo to different folder
4. App crashes

**Comment by Bluemethyst** [comment]
Yes that exactly, tysm for looking into this. It also does it with other types of media, I just tried videos and it does the same

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by Bluemethyst** [comment]
Just tried all the things that were causing the issues before and no crashes at all! Thank you so much for this amazing product!!
Keep up the great work!
