### ISSUE TITLE
The property window is not draggable

### ISSUE THREAD

**Issue by hez2010** [files-community/Files#10333]
### Description

The property window is not draggable in Files preview.

### Steps To Reproduce

1. Open property window
2. Try to drag the title bar

### Steps to fix

- Make the title bar of the property window draggable

### Files Version

2.3.53

### Windows Version

Windows 11 25231.1

### Relevant Assets/Logs

N/A

**Comment by yaichenbaum** [comment]
Merging with #9919. Looks like it was accidentally closed before.
