### ISSUE TITLE
crashing after creating a theme file then opening the custom theme dropdown

### ISSUE THREAD

**Issue by cycles-3D** [files-community/Files#10332]
### Description

after creating a theme.xaml file in the themes folder and opening the custom theme drop down it just crashes and doesnt show anything in logs

### Steps To Reproduce

1.create a theme file in the theme folder
2.restart files
3.open custom thmems drop down

### Steps to fix

didnt find a fix

### Files Version

Version: 2.3.12.0 OS Version: 10.0.22621.674 

### Windows Version

windows 11 22h2   

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9895489/debug.log)

**Comment by Josh-65** [comment]
Could you upload the theme file

**Comment by cycles-3D** [comment]
il send it as a text file since git hub doesnt support xaml. i just modified the nord theme. 
[nordmodified.txt](https://github.com/files-community/Files/files/9895550/nordmodified.txt)

**Comment by yaichenbaum** [comment]
`SolidBackgroundFillColorQuarternary` has an invalid color, removing the extra `0` should solve the issue.

**Comment by Josh-65** [comment]
For themes v2 it should show the theme but as invalid rather than crashing.
