### ISSUE TITLE
Can't eject hard disk 

### ISSUE THREAD

**Issue by Leoijeon** [files-community/Files#10334]
### Description

If I want to eject my hard disk, but didn't close Files app, system will tell me I can't eject. When I close Files app, I can eject my hard disk normally.

### Steps To Reproduce

1. open Files
2. eject hard disk

### Steps to fix

fix the problem when eject hard disk

### Files Version

Version: 2.3.12.0 OS Version: 10.0.19044.2006

### Windows Version

Windows 10 Pro Version	21H2 OS build	19044.2006 Experience	Windows Feature Experience Pack 120.2212.4180.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9895819/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9895821/debug_fulltrust.log)

**Comment by ELowry** [comment]
To add to this, it appears that as long as you have the actual drive open in Files, it will not be able to eject it.

In Windows File Explorer, ejecting a drive from within it will move all tabs/widows that are inside the drive to the default ("home") folder view, unless some file transfer or other similar operation is ongoing.

My personal view is that the ideal way things should go is the following:
1. A user ejects a drive which is currently navigated to in 1+ tabs/windows.
2. Unless some file transfer is ongoing, a small popup opens with a confirmation request:
   * "Are you sure you wish to eject this drive? It is currently open in Files."
   * This popup could include a "Don't ask again" checkmark associated with an option in the Files settings.
3. If confirmed or automatically skipped, Files should do one of the following:
   * [Ideal IMHO] Close all tabs/windows that are actively exploring the ejecting drive.
      * In the case where this is the only open tab, return to either "My Computer" or the user's chosen "home location"
   * Return the tabs/windows that are actively exploring the ejecting drive to either "My Computer" or the user's chosen "home location".

This would avoid the issue of having to hunt down any open tabs, and would avoid user confusion about an app using the drive (Files itself).

Note that #9560 would also help avoid confusion, but would not fix the issue with having to hunt the relevant tabs.

**Comment by Josh-65** [comment]
Is this still an issue?

**Comment by yaira2** [comment]
Merging with #11091
