### ISSUE TITLE
Code Quality: Dead code and types

### ISSUE THREAD

**Issue by QuaintMako** [files-community/Files#10359]
### Description

There are a bunch of dead code and types in the source code, probably reminiscent of former structures.  While it's not a huge issue in itself, it does create some clutter around the codebase.

### Concerned code

Whole solution

### Gains

- A cleaner codebase.
- A better application of the YAGNI principle.

### Requirements

- Inspect the code and remove methods and objects that are artifacts of former structure.

**Comment by QuaintMako** [comment]
Running some tools can help us find the dead code pretty easily, it shouldn't take a lot of work to remove.

**Comment by yaichenbaum** [comment]
> Running some tools can help us find the dead code pretty easily, it shouldn't take a lot of work to remove.

We need to evaluate each case because we sometimes keep things around for reference. Are you interested in opening a PR and I'll go over it to see if there is anything we want to keep?

**Comment by thebarshablog** [comment]
I'd like to take care of this issue, incase it has not been assigned.

**Comment by yaira2** [comment]
It's preferred to make these changes in increments (usually when you're already working on the file with the code) as opposed to a single PR that takes care of it all at once.

**Comment by thebarshablog** [comment]
For sure, I'll keep tab of each thing that requires attention and will do so according.

**Comment by yaira2** [comment]
@QuaintMako do we need a dedicated issue to track this or should it just be a general goal while working on the codebase?

**Comment by QuaintMako** [comment]
I think we can close it now.
