### ISSUE TITLE
Bug: Files crashes when right clicking item in search result

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#10361]
### Description

*

### Steps To Reproduce

1. Go to a folder
2. Search for file/folder
3. Right click an item

### Steps to fix

- Stop the crash when right clicking a search item

### Files Version

2.3.56.0

### Windows Version

10.0.22621.755

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9904266/debug.log)

**Comment by the-lazy-learner** [comment]
Could I try working on this issue? I'm mostly a beginner, so I might need some guidance in the process. But yes I'd love to contribute to the project.

**Comment by Josh-65** [comment]
Go ahead the discord https://discord.gg/files has a dev chat for any help you need.

**Comment by Josh-65** [comment]
This is fixed on 2.3.61.0
