### ISSUE TITLE
Bug: Pinning a file to Start Menu won't work properly

### ISSUE THREAD

**Issue by verdaderoken** [files-community/Files#10369]
### Description

I tried to pin a file to Start Menu, specifically executable files like this `test.exe`
![image](https://user-images.githubusercontent.com/88200096/199132131-227fc2ea-40a4-4b3e-a7ca-aaac1940f9b7.png)
![image](https://user-images.githubusercontent.com/88200096/199132099-e141c2c7-e022-45f1-8009-3fb897b6a92d.png)

After pinning, it would only show something like this which I wasn't expecting.
> File 
> ![image](https://user-images.githubusercontent.com/88200096/199132239-0bfc29f8-768b-4338-8a1b-68d039db90c3.png)

Clicking it would not open the program but rather interpret it as a folder which shows a **NotAFolder** error:
![image](https://user-images.githubusercontent.com/88200096/199132704-7ea59405-e5f9-4bf0-b40f-5cb779dc1d0f.png)

On the other hand, pinning folders is working properly.

### Steps To Reproduce

1. Select a file to pin to Start Menu (some files like ".txt" don't have this option)
2. Click Yes to pin
3. Open the pinned item

### Steps to fix

- The app should be pinned like this and would open the file when clicked _(there is no icon because I just created the file)_
![image](https://user-images.githubusercontent.com/88200096/199132321-e4415954-3c2f-4a95-8505-e48253b08c2d.png)

### Files Version

2.3.56.0

### Windows Version

10.22623.875

### Relevant Assets/Logs

Already shown in the description

**Comment by yaichenbaum** [comment]
Is this the same as #9740?

**Comment by verdaderoken** [comment]
> Is this the same as #9740?

Yes, it's the same
