### ISSUE TITLE
Bug: Can't open a path using Files.exe

### ISSUE THREAD

**Issue by verdaderoken** [files-community/Files#10370]
### Description

I can't open a path using Files.
e.g: `Files "C:\Windows"`
It did work before in early versions but recently the app would open with this message: 
![image](https://user-images.githubusercontent.com/88200096/199135992-87746e89-7492-42b3-97bc-18e8e1534fe1.png)

### Steps To Reproduce

1. Copy a path
2. Paste the path in Run and press Enter
    - Should look like this: `Files "<path>"` or `Files.exe "<path>"`
3. The app will open but shows a dialog box instead of executing the path

### Steps to fix

- Make the app recognize the path again and execute it properly

### Files Version

2.3.57.0

### Windows Version

10.0.22623.875

### Relevant Assets/Logs

N/A

**Comment by KairuDeibisu** [comment]
This issue seems to only effect shortcut files or folders being accessed with a system link.

The following worked for me 

- `Files "Desktop\Test"`
- `Files "C:\Windows"`

The following did not work for me

- `Files "Desktop\Demo"`

The only difference.

Demo is a shortcut to a folder called Demo in my Documents folder.

Version: 2.3.12.0
OS Version: 10.0.19045.2193

**Comment by Josh-65** [comment]
> This issue seems to only effect shortcut files or folders being accessed with a system link.
> 
> The following worked for me
> 
> * `Files "Desktop\Test"`
> * `Files "C:\Windows"`
> 
> The following did not work for me
> 
> * `Files "Desktop\Demo"`
> 
> The only difference.
> 
> Demo is a shortcut to a folder called Demo in my Documents folder.
> 
> Version: 2.3.12.0 OS Version: 10.0.19045.2193

This is an issue that was added in 2.3.57 as some paths were probably changed.

**Comment by verdaderoken** [comment]
Still not working on my end

![image](https://user-images.githubusercontent.com/88200096/204149672-bb332fc0-6e44-4395-9122-ef3e56da1841.png)

![image](https://user-images.githubusercontent.com/88200096/204149680-8d35d98a-56b4-4096-a71d-9aa57d2f710a.png)
