### ISSUE TITLE
Sort by EXIF Date

### ISSUE THREAD

**Issue by Thane5** [files-community/Files#10375]
### What feature or improvement do you think would benefit Files?

I propose to add the ability to sort files by EXIF date. This Files app currently only has "last changed" and "creation date", but those file properties can often mismatch with the actual date when a photographic picture was taken after you editied it. In windows the EXIF date is simply called "date" for some reason.

### Requirements

- This proposal will allow users to sort files by EXIF date

### Files Version

2.3.12.0

### Windows Version

Windows 11 22H2

**Comment by yaichenbaum** [comment]
Creation date is supposed to remain unmodified after editing 🤔

**Comment by Thane5** [comment]
I know that it's not ideal, but my raw editing software does that in certain cases. 
It's called Canon's Digital Photo Professional 4, and when i assign a star-rating to any of my pictures, it will update both the "created on" and "last edited" date to that second.
It would be interesting to know if other tools behave similarly, but i dont know any right now.

**Comment by yaichenbaum** [comment]
The logic might be that the edit is "creating" a new image. This will be implemented together with #8366
