### ISSUE TITLE
App crashes when opening folder

### ISSUE THREAD

**Issue by Data4467** [files-community/Files#10372]
### Description

The app crashed when searching for a folder in the "hidden files". But I dont think it necessarily has to do with the "hidden files", because I had the error once before, when just opening a folder.

### Steps To Reproduce

1. Go to folder
2. Double click to open

### Steps to fix

Fix the crash when opening folders

### Files Version

2.3.57.0

### Windows Version

Windows 11 22H2 22621.755

### Relevant Assets/Logs

[Log.txt](https://github.com/files-community/Files/files/9910729/Log.txt)

**Comment by yaichenbaum** [comment]
Merging with #9921
