### ISSUE TITLE
Bug: Files won't activate

### ISSUE THREAD

**Issue by verdaderoken** [files-community/Files#10379]
### Description

I'm trying to activate Files using the <kbd>Win</kbd>+<kbd>(Number)</kbd> combination in Taskbar but it won't work. 

The only workaround for me was to click the icon, but even when clicking the icon still needs two clicks because of the beep sound at the first click. (a beep will trigger when Files is minimized and you clicked the icon)

### Steps To Reproduce

1. Minimize Files app
2. Press Win+(the index where Files is in the Taskbar, in my case Win+3 
![image](https://user-images.githubusercontent.com/88200096/199358445-a438e21b-f619-4f45-aef5-73703e0ec230.png)
3. A default Windows beep sound will play but the app will not activate

### Steps to fix

- Prevent the Windows beep sound
- Activate the app immediately after clicking or using the hotkey

### Files Version

2.3.57.0

### Windows Version

10.0.22623.875

### Relevant Assets/Logs

N/A

**Comment by yaichenbaum** [comment]
Is Files the default file manager? What happens if you toggle it off and on again?

**Comment by verdaderoken** [comment]
> Is Files the default file manager? What happens if you toggle it off and on again?

Yes, it is already set as default. Toggling off and on seems to have no effect

**Comment by verdaderoken** [comment]
I forgot to write that the problem only occurs when the app is **minimized** at first and then you hit that Win+ hotkey or click the icon. Both will produce a beep sound.

The only difference is that using the hotkey would not activate the app at all while clicking it would need you to hit the icon twice before it actually restores from being minimized.

**Comment by verdaderoken** [comment]
> What happens if you toggle it off and on again?

I just encountered a new one. This happens after toggling the default file manager off and ON and hitting `Win+E`.
![image](https://user-images.githubusercontent.com/88200096/199364897-1868208c-ddcc-4689-a41d-24088d7e5a5f.png)
I had to install the stable version and toggle the setting there to get it working again. Also, the import settings won't work in the latest preview as I have failed to restore a 2.3.57.zip backup

Will post a separate issue. :)

**Comment by yaichenbaum** [comment]
That's a known issue 👍

**Comment by verdaderoken** [comment]
> That's a known issue 👍

How about the import settings? 
> Also, the import settings won't work in the latest preview as I have failed to restore a 2.3.57.zip backup

**Comment by yaichenbaum** [comment]
Can you reproduce this if you export and import a new backup? Please open a bug report if it's still an issue.

**Comment by Josh-65** [comment]
#10194. Yair said it would be a WinAppSdk bug or Windows. would this still be the case?

**Comment by yaichenbaum** [comment]
Seems Files specific but hard to know
