### ISSUE TITLE
Soft-locking operations when executing at least two operations after each other

### ISSUE THREAD

**Issue by QuaintMako** [files-community/Files#10383]
### Description

We can soft-lock Files' operations (copy, paste, empty etc...) pretty easily. It's pretty detrimental, since it forces the user to reset the software when they want to do more than two operations in a row.

### Steps To Reproduce

1. Copy any file in a folder. It works.
2. Copy another file in the same folder. The operation doesn't end, yet it appears in the `Ongoing Tasks` pane.

### Steps to fix

- Resolve the soft-locking of the operations.

### Files Version

Version 2.3.57.0

### Windows Version

W11 21H2 22000.1098

### Relevant Assets/Logs

![SoftLock](https://user-images.githubusercontent.com/110472580/199505568-75725530-622a-4cc3-8f54-b37b1055c636.gif)

**Comment by QuaintMako** [comment]
Digging around different commits, it seems the issue was introduced by #10365. 
I can do the operations without any issue before this one, but it no longer works afterwards.

**Comment by gave92** [comment]
This is a strange one. The error comes from the taskbar update code, I'll take a look.
