### ISSUE TITLE
Bug: Files launcher isn't being copied when changing the default file manager

### ISSUE THREAD

**Issue by verdaderoken** [files-community/Files#10381]
### Description

I tried toggling the setting 'Set as default file manager' off and on, closed the app, and opened it again using Win+E but I got this error instead.
![image](https://user-images.githubusercontent.com/88200096/199365919-bf7cda1d-4182-43a9-a684-e6abf9e87f8f.png)

### Steps To Reproduce

1. Unset it first if it's already set as default.
2. Set Files as the default file manager. 
3. Close the app
4. Open using these two methods:
    - By using Win+E, the _**Application not found**_ window should appear.
    - By clicking the app icon, Files would open with a _**Did you delete this folder?**_ modal, which should not happen.

### Steps to fix

- The error should not appear and Files should open

### Files Version

2.3.57.0

### Windows Version

10.0.22623.875

### Relevant Assets/Logs

N/A

**Comment by yaichenbaum** [comment]
I can't reproduce this, could be the registry files were out of date for you. Can you reproduce this issue again?

**Comment by verdaderoken** [comment]
> I can't reproduce this, could be the registry files was out of date for you. Can you reproduce this issue again?

Yes, I just tried it now. Here's the video 

https://user-images.githubusercontent.com/88200096/199368500-d932452f-7c24-4dfa-bbdc-cbc932549fa6.mp4

**Comment by yaichenbaum** [comment]
I can reproduce the issue (it's indeed a regression in a recent preview build), thank you for the report.

**Comment by gave92** [comment]
@yair100 can you reproduce this in Debug from main? Or only if installed from the appinstaller?

**Comment by yaichenbaum** [comment]
Installed from appinstalelr

**Comment by yaira2** [comment]
Merging with #10521
