### ISSUE TITLE
Bug: Importing a backup fails but shows no error

### ISSUE THREAD

**Issue by verdaderoken** [files-community/Files#10382]
### Description

Here's what I did:
Basically customizing the app and exporting the settings so when the app is resetted, I can import the backup and see what happens.
https://user-images.githubusercontent.com/88200096/199373033-22d55197-f184-4b52-b8fe-d3d390fdff2b.mp4

_Ignore the theme setting, I thought it would be also included in the backup._

### Steps To Reproduce

1. Pin some folders, customize
2. Export the settings
3. Reset the app
4. Open Files and import the backup zip
5. Nothing will happen. Pinned folders are not showing up.

### Steps to fix

- Fix the import

### Files Version

2.3.57.0

### Windows Version

10.0.22623.875

### Relevant Assets/Logs

N/A

**Comment by yaichenbaum** [comment]
What happens if you restart the app?

**Comment by verdaderoken** [comment]
> What happens if you restart the app?

Still the same, folders and settings like compact mode would not still show up
