### ISSUE TITLE
Incomplete right-click menu for network drives

### ISSUE THREAD

**Issue by wslrj123** [files-community/Files#10394]
### Description

For a defunct network drive, I can't delete it using files

### Steps To Reproduce

1.Open files
2.Right-click a network drive in the left navigation bar
3.I want close it,so?

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

2.3.12

### Windows Version

windows10 21H2 19044.2130

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/106938316/199657007-58692813-dd56-4a94-bc39-ac29e9f3126a.png)

**Comment by Josh-65** [comment]
Have you looked in the more section of the menu?

**Comment by wslrj123** [comment]
> 您是否查看了菜单的“更多”部分？
Of course

![image](https://user-images.githubusercontent.com/106938316/199865438-30a9a6ad-8b85-4c54-bde7-d05d4fdecf08.png)

Sorry,Blame me for not being detailed enough,This question is only for a failed network drive

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
