### ISSUE TITLE
Incomplete right-click menu for network drives

### ISSUE THREAD

**Issue by wslrj123** [files-community/Files#10393]
### What feature or improvement do you think would benefit Files?

For a defunct network drive, I can't delete it using files

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.3.12

### Windows Version

windows10 21H2 19044.2130

**Comment by yaichenbaum** [comment]
This issue might work better with the bug template
