### ISSUE TITLE
Feature: Auto create folder when using ctrl + shift + n shortcut

### ISSUE THREAD

**Issue by Wrongkalonka** [files-community/Files#10396]
### What feature or improvement do you think would benefit Files?

Auto create folder when using the ctrl + shift + n shortcut instead of prompting user to choose an item type.

### Requirements

- Ctrl + shift + n shortcut will no longer display the new item dialog
- Shortcut will now auto prompt user to enter the folder name

### Files Version

2.3.12.0

### Windows Version

Edition	Windows 10 Pro Version	21H2 Installiert am	‎13.‎08.‎2020 Betriebssystembuild	19044.2130 Leistung	Windows Feature Experience Pack 120.2212.4180.0

### Comments

Would be nice to have the setting to choose what the shortcut will create. In my use case i would like to be able to set it to folder since that is the default with Windows explorer and i got used to it and really like it to be able to create a new folder without using the mouse.
Also the popup window when hitting the shortcut takes sometimes about one to two seconds to show the selectable options.

**Comment by yaichenbaum** [comment]
Folders are now selected by default in the preview build, can you see if this solves the issue?

**Comment by Josh-65** [comment]
I believe they mean to have the shortcut just make a new file or folder instantly without the prompt showing (File explorer will do this for folders). Not the keyboard selection.

**Comment by Wrongkalonka** [comment]
> I believe they mean to have the shortcut just make a new file or folder instantly without the prompt showing (File explorer will do this for folders). Not the keyboard selection.

Yes, this is what I was looking for. The Prompt takes time and needs another input. If I need anything else than a folder I use the button at the top. But being able to create a folder with one shortcut and nothing else would be awesome.
Maybe ad a opt-in in the settings or the prompt to select a default and "don't show this massage again".

**Comment by yaichenbaum** [comment]
We'd prefer to take an opinionated approach here. We can change the default for `ctrl` + `shift` + `n` if that's what users want but we won't add a setting to change this behavior.

**Comment by verdaderoken** [comment]
I've been using `Alt`+`W`+`Space` for a while to mimic the File Explorer's way of the `Ctrl`+`Shift`+`N`. For me, having the option to create a folder, without going through the prompts, would be a time saver and would also work for users who are used to Explorer's way of creating folders.

**Comment by yaichenbaum** [comment]
I would prefer that as well

**Comment by francisco-lafe** [comment]
I would prefer that as well, I'm used to `CTRL+SHIFT+N`

**Comment by yaira2** [comment]
This shortcut will be included in the next release.
