### ISSUE TITLE
Bug: Beep sound when pressing Alt key combinations

### ISSUE THREAD

**Issue by verdaderoken** [files-community/Files#10407]
### Description

Pressing Alt key combinations like Alt+D would trigger a Windows default beep sound.

### Steps To Reproduce

1. Open Files
2. Press Alt+D or any other combinations

### Steps to fix

- Remove the beep sound when pressing Alt key combinations

### Files Version

2.3.58.0

### Windows Version

10.0.22623.875

### Relevant Assets/Logs

None

**Comment by yaichenbaum** [comment]
Can you share a recording?

**Comment by verdaderoken** [comment]
> Can you share a recording?

The issue seems to be fixed. I don't know what happened that day, I can't reproduce the issue now
