### ISSUE TITLE
Improved Columns

### ISSUE THREAD

**Issue by gergy008** [files-community/Files#10409]
### What feature or improvement do you think would benefit Files?

Explorer.exe features columns that don't work at all and I was hoping this app would make a replacement. However, while it didn't solve my issue, it is a fantastic app and want to stick with and help make it perfect.

I'm requesting more columns, as this app doesn't seem to even have basic overview of file metadata (for music, as an example) yet - and hopefully would be gunning for a working folder count (completely broken in explorer.exe)

I've tried looking throughout the app to see if this exists - I was expecting to find it right clicking on columns, settings, clicking on views buttons - haven't found it unfortunately.

### Other notes

Sorting columns too quickly activates the double click to go back - this shouldn't active when clicking to sort columns.

### Requirements

- Add new columns that users can use
- Files will remember the choices for individual folders
- This will make Files partially irreplaceable against explorer.exe

### Files Version

Version: 2.3.12.0

### Windows Version

OS Version: 10.0.22000.1098

### Comments

![image](https://user-images.githubusercontent.com/2872732/200088573-e04ca338-cfc7-40d2-8a07-e0b47ed5bbf0.png)

![image](https://user-images.githubusercontent.com/2872732/200088619-841b95b6-479e-4b21-9a29-7590fca74c2c.png)

![image](https://user-images.githubusercontent.com/2872732/200088671-c6d55a31-557b-4dcb-be17-efa918e20e83.png)

![image](https://user-images.githubusercontent.com/2872732/200088542-5d992460-c9da-4f5f-8549-a829955f43e5.png)

**Comment by yaichenbaum** [comment]
This is a high priority for us, but we're currently blocked by the lack of a modern data grid control. Merging with #8366
