### ISSUE TITLE
Listview: add empty space where there is no column

### ISSUE THREAD

**Issue by XPoppyX** [files-community/Files#1040]
**Before:** 
![Anotación 2020-06-12 150354](https://user-images.githubusercontent.com/61259627/84537613-1556df80-acbe-11ea-8da2-659c299c95c6.png)

**After:** 
![Anotación 2020-06-12 1503542](https://user-images.githubusercontent.com/61259627/84537615-17b93980-acbe-11ea-978f-cbc2d719a8fd.png)

**Comment by d2dyno1** [comment]
We could add a margin for now as a placeholder?

**Comment by yaichenbaum** [comment]
@d2dyno1 Having the scroll bar at the edge of the app is important, I wonder if we can just edit the template of the DataGrid to solve this issue.

**Comment by d2dyno1** [comment]
> @d2dyno1 Having the scroll bar at the edge of the app is important, I wonder if we can just edit the template of the DataGrid to solve this issue.
Does not seem like a problem.

I'm not sure about the Margin solution that's why I'm calling it "Temporary" - I dunno how it will behave when user tries to resize the column
