### ISSUE TITLE
A file in a folder does not appear once created

### ISSUE THREAD

**Issue by SpyassL** [files-community/Files#10404]
### Description

Once you create a file in any folder, it does not appear until you 

### Steps To Reproduce

1. Get Ubuntu WSL
2. Open \\wsl$\Ubuntu in Files
3. Go to \home\x, where x is any valid folder inside of \home
4. Create a new folder or file.
5. Give the folder or file a name.

### Steps to fix

Correct action happens when clicking Refresh

### Files Version

Версія: 2.3.12.0 OS Version: 10.0.19044.2130

### Windows Version

Windows 10 21H2 19044.2130

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/104501034/200066758-50bba11e-b093-4625-af0d-fd4c7dad1b5b.png)

**Comment by Josh-65** [comment]
Merging with #9250
