### ISSUE TITLE
Some additional features I@d like to see

### ISSUE THREAD

**Issue by alansharkey** [files-community/Files#10401]
### What feature or improvement do you think would benefit Files?

Two things:

1. When I hover over an item (e.g. a file) while I have it set to single click to perform whatever action that file needs, can the hover action select that file? You know it's been selected when the action menu above changes and a small vertical bar appears next to the name of the file. 
2.  The right mouse click context menu doesn't seem to include the option to delete the file. Can that be added?

Thanks

Alan

### Requirements

Make it work like MS FIle Explorer. But better.

### Files Version

2.3.12.0

### Windows Version

Windows 11 Home - latest updates but not 22H2.

**Comment by Josh-65** [comment]
This is in the preview version https://files.community/download/preview

**Comment by alansharkey** [comment]
Thanks.

I downloaded the preview and the select works as promised. However, I may have found a bug. I changed a setting (Preferences -> Files & Folders -> List & sort Directories along side Files) from on to off. Which changed it so that directories were sorted along side files. But when I turned it off, it didn’t go back to the previous sort (Directories first, then files). Closing and re-opening the program didn’t change it back either.

Is this a bug or am I doing something wrong?

Regards

Alan

**Comment by Josh-65** [comment]
You can click on the name header in the details view

**Comment by alansharkey** [comment]
That doesn't change the sorting order for the directory that is in the files & folders order.

**Comment by Josh-65** [comment]
All sort options are here
![image](https://user-images.githubusercontent.com/26977075/199966648-6bd473c1-332f-4147-82c4-77aaf7493fbe.png)

**Comment by alansharkey** [comment]
Thanks. The tick was still left on ‘sort by files & folders’. Removed now and it all works as expected.

Regards

Alan
