### ISSUE TITLE
Choose another app isn't working.

### ISSUE THREAD

**Issue by sfksuperman** [files-community/Files#10411]
### Description

When I try to open any media file using any other app (to select vlc or any other), it doesn't open up the preferences tab at all.

![image](https://user-images.githubusercontent.com/34414624/200127912-6d790fc3-6c51-4c1e-a264-2ed35651e073.png)

### Steps To Reproduce

1. Right-click on any media file.
2. Select the OPEN WITH option.
3. Select CHOOSE ANOTHER APP.

### Steps to fix

It should open up a list of a supported apps to select from. For e.g., the screenshot below.
<img width="323" alt="image" src="https://user-images.githubusercontent.com/34414624/200128033-2cdae5a0-9331-4c46-9ef1-7510ebcfea3e.png">

### Files Version

2.3.12.0

### Windows Version

Windows 11 22H2 22621.755

**Comment by Josh-65** [comment]
You will need to upload the logs files directly to GitHub. You can get them in files settings > about > open log folder.

**Comment by sfksuperman** [comment]
[debug.log](https://github.com/files-community/Files/files/9944509/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9944510/debug_fulltrust.log)
I got two logs, check, please.

**Comment by yaichenbaum** [comment]
This is specific to older builds of Windows and should be working properly on the newest version of Windows 11.

**Comment by sfksuperman** [comment]
Not working bro, my windows 11 is 22621.819.

**Comment by ItsjustmeTJ** [comment]
Good day everyone, 

I'm too am having the same problem with "Choose Another App" not working. 

To correct the issue I downloaded the windows 11 image and reinstalled it (pre 22H2) (keeping all apps and settings).  When windows 11 came up, "Choose Another App" worked fine. 
I then ran system security updates, restarted and again all worked fine. 
*However. when I re-plied 22H2 sadly the problem returned.   My windows ver is 10.0.22621 Build 22621.   Thank you in advance to anyone who can shed some light on this.  : )

TJ

**Comment by FerdowsurAsif** [comment]
Had the same problem with "Choose Another App" for MKV files. Didn't test other types of media files. Not reproducible with Excel, doc, or other type of files. 

Had to go to settings and chose the default apps to change app.

**Windows 11**
Version 10.0.22621 
Build 22621

**Comment by real-mack** [comment]
I have same problem I bought new PC with Win 11 Home with latest updates and its not working at all with any files. I cant even change it in settings or anywhere else. Not even in Properties. HOW TO SOLVE IT??

**Comment by Josh65-2201** [comment]
Do you have another program that can open it the file?

**Comment by real-mack** [comment]
Yes sir. For example for video files I have also VLC player and MPC-HC player. Im trying to google solution whole day and I cant find anything..

**Comment by Josh65-2201** [comment]
Does it work in Windows File Explorer?

**Comment by real-mack** [comment]
No it doesnt work.

**Comment by Josh65-2201** [comment]
Then it will be a Windows issue and not related to Files. No idea what could be the issue.

**Comment by real-mack** [comment]
Yes I know its Windows problem but I dont know how to solve it..
