### ISSUE TITLE
FILE TAG to move to last by default for every folder.

### ISSUE THREAD

**Issue by sfksuperman** [files-community/Files#10412]
### What feature or improvement do you think would benefit Files?

Why FILE TAG always appear on the 2nd column? There should be a default setting to move it to last for every folder; can we have this?

![image](https://user-images.githubusercontent.com/34414624/200128119-959e43fa-f530-490f-bde5-9c88758b9df8.png)

### Requirements

There should be a default setting to move it to last for every folder.

### Files Version

2.3.12.0

### Windows Version

Windows 11 22H2 22621.755

### Comments

![image](https://user-images.githubusercontent.com/34414624/200128221-cbb509ce-b50b-4f45-879d-97a84f40fd69.png)

**Comment by Josh-65** [comment]
Merging with #8385
