### ISSUE TITLE
Add tab grouping

### ISSUE THREAD

**Issue by SpyassL** [files-community/Files#10410]
### What feature or improvement do you think would benefit Files?

Currently, Filer has tabs. But there is no grouping.

And if you have multiple folders you open in Files, it is impossible to separate those tasks into groups, like browser tabs in Microsoft Edge or Terminal tabs in Windows Terminal.

### Requirements

- They work the way it is shown in any further attachment
![image](https://user-images.githubusercontent.com/104501034/200109513-6b19c841-0837-4ea7-8b69-ec3462a03d51.png)
msedge version
![image](https://user-images.githubusercontent.com/104501034/200109632-4cd80f82-0168-47dc-9b58-17d7f18da795.png)
files implementation 1
![image](https://user-images.githubusercontent.com/104501034/200110028-ef6e47cb-7c4a-4897-aa3a-296181222c8f.png)
files implementation 2

### Files Version

Версія: 2.3.12.0 OS Version: 10.0.19044.2130

### Windows Version

Windows 10 21H2 19044.2130

**Comment by yaichenbaum** [comment]
Merging with #9981
