### ISSUE TITLE
Check  box

### ISSUE THREAD

**Issue by BrandonCF** [files-community/Files#10415]
### What feature or improvement do you think would benefit Files?

Item checkboxes as a constant option like the Windows default file explorer would be a great addition. When multiselecting via cursor it gives you the opportunity to uncheck any unwanted files or folders without accessing any additional settings or menus. The same can be said for adding files and folders as well. I've found this feature extremely useful in the default file explorer and think it would be beneficial to add it here. 

### Requirements

- This proposal will require an additional setting in Preferences/Files and Folders (really unsure what to put here, so I took a stab at it)

### Files Version

Version: 2.3.12.0 OS 

### Windows Version

Edition	Windows 11 Home Version	22H2 Installed on	‎10/‎22/‎2022 OS build	22622.575 Experience	Windows Feature Experience Pack 1000.22634.1000.0

**Comment by yaichenbaum** [comment]
Mering #8918
