### ISSUE TITLE
Bug: 7z archives are not extracted correctly

### ISSUE THREAD

**Issue by ferrariofilippo** [files-community/Files#10414]
### Description

When I try to extract a 7z archive, only the base folder is extracted.

The problem is related to line # 63 of `Files.App.Helpers.ZipHelpers`.
The base folder is not considered as a directory. 
Because of this line # 124 is evaluated to true and the method returns.

### Steps To Reproduce

1. Start the extraction of a 7z archive
2. See that only the base folder is created

### Steps to fix

?

### Files Version

Version: 2.3.55.0 OS Version: 10.0.22621.755

### Windows Version

Windows 11 Home Version 22H2 22621.755

### Relevant Assets/Logs

![Folder](https://user-images.githubusercontent.com/102259289/200177646-04d9f158-5e24-434d-b222-340aeb113fc0.png)

`xStage` is a folder but `IsDirectory` is set to false

**Comment by QuaintMako** [comment]
Happens for a .zip file as well.

**Comment by Josh-65** [comment]
Does #10453 not fix this?

**Comment by QuaintMako** [comment]
It does not for me @Josh-65.

**Comment by yaira2** [comment]
@ferrariofilippo do you want to look at this issue?

**Comment by ferrariofilippo** [comment]
I'll try
