### ISSUE TITLE
Correct spelling for "dialog"

### ISSUE THREAD

**Issue by cosmicr** [files-community/Files#10419]
### What feature or improvement do you think would benefit Files?

As per: https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/d/dialog-box-dialog-dialogue

> When you need to refer to a dialog box, use dialog. Don't use pop-up window, dialog box, or dialogue box.

It's jarring to see it spelled "dialogue". Unless there's some new scheme I am unaware of, I believe it should be spelled *dialog*. 

### Requirements

Only one (two maybe) changes required for English: https://github.com/files-community/Files/blob/19746704d597cfa9e63cead722f74558df8ab1a2/src/Files.App/Strings/en-GB/Resources.resw#L823

and maybe French, I'm not sure: https://github.com/files-community/Files/blob/19746704d597cfa9e63cead722f74558df8ab1a2/src/Files.App/Strings/fr-FR/Resources.resw#L823

### Files Version

Version 2.3.12

### Windows Version

Windows 10 22H2

### Comments

I wanted to do a straight up pull request on this but I'm not really familiar with GitHub and big projects. Sorry if this is against rules or anything like that - I'm surprised it has slipped through the net all this time.

**Comment by Josh-65** [comment]
"dialogue" is the correct spelling for British English and French. "dialog" is American English.

**Comment by cosmicr** [comment]
Even in the context of a dialog box?

**Comment by Josh-65** [comment]
It's a translation for users to see so yes. No idea if yair would want to change it.

**Comment by cosmicr** [comment]
Fair enough. I had thought that even Americans spell it "Dialogue" in the context of speech etc, but as a computer term I've always known it as dialog. I speak Australian English Fwiw which is pretty much the same as British.

 I'm not fussed I thought it was a worthy suggestion.

**Comment by yaichenbaum** [comment]
I recommend opening an issue through Crowdin so that other translators can chime in.
