### ISSUE TITLE
Cannot create a new folder.

### ISSUE THREAD

**Issue by BellCocoa** [files-community/Files#10420]
### Description

If I type in Japanese, I can't create it.

### Steps To Reproduce

If I type in Japanese, I can't create it.

### Steps to fix

Copy-paste the text to create it.

### Files Version

2.3.12.0 OS Version: 10.0.22621.674

### Windows Version

Windows 11 22H2　22621.674

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/9950023/debug_fulltrust.log)

**Comment by Josh-65** [comment]
Merging with #9563
