### ISSUE TITLE
I cannot compile the project, can someone help me

### ISSUE THREAD

**Issue by JustWeZero** [files-community/Files#10425]
I prepared the environment following the readme. When I built this solution, I got an error:

```C:\Users\卢子建\.nuget\packages\microsoft.windows.cswinrt\2.0.0\build\Microsoft.Windows.CsWinRT.Authoring.targets(343,5): error MSB3030: Could not copy the file "E:\C#_Project\Files\src\BackgroundTasks\bin\x64\Debug\BackgroundTasks.winmd" because it was not found.```

and this project built failed.How can I fix this problem? thx.

**Comment by Josh-65** [comment]
Have you tried re-cloning the repository?

**Comment by JustWeZero** [comment]
yes, I have tried this method but it still has the problem.

**Comment by JustWeZero** [comment]
> Have you tried re-cloning the repository?

yes, I have tried this method but it still has the problem.

**Comment by hez2010** [comment]
Can you try renaming your folder from `C#_Project` to a name without special characters?

**Comment by JustWeZero** [comment]
> Can you try renaming your folder from `C#_Project` to a name without special characters?

I renamed "C#" to "Csharp". It fixed the problem. Much thanks for your help!
