### ISSUE TITLE
Feature: Implement support for elevated operations

### ISSUE THREAD

**Issue by hez2010** [files-community/Files#10422]
### What feature or improvement do you think would benefit Files?

After we remove the full trust process, we need to implement a new model for elevated operations. 
Users can already open Files as administrator to work around this issue today, but it's still *better to have* from the perspective of user experience.

### Requirements

- For elevated operations, use an elevated COM component to execute them
- Possible blocker: https://github.com/microsoft/WindowsAppSDK/issues/3092

### Files Version

2.3.58

### Windows Version

Windows 11 25236

**Comment by hez2010** [comment]
@Lukiluc29 It depends on the blocker issue https://github.com/microsoft/WindowsAppSDK/issues/3092.

**Comment by Lukiluc29** [comment]
> @Lukiluc29Cela dépend du problème de blocage [microsoft/WindowsAppSDK#3092](https://github.com/microsoft/WindowsAppSDK/issues/3092) .

You don't have any more recent information on this bug as it has been present for a long time.

**Comment by gave92** [comment]
For reference here the changes I'd make to implement this once https://github.com/microsoft/WindowsAppSDK/issues/3092 is fixed: https://github.com/gave92/files-uwp/tree/admin_ops.
At any time we could just loose hope in a fix and implement admin operations with a separate process (like we used to do) but it's annoying.

**Comment by Lukiluc29** [comment]
> For reference here the changes I'd make to implement this once [microsoft/WindowsAppSDK#3092](https://github.com/microsoft/WindowsAppSDK/issues/3092) is fixed: https://github.com/gave92/files-uwp/tree/admin_ops. Alternatively we could just loose hope in a fix and implement admin operations with a separate process (like we used to do) but it's annoying.

And it is not possible to re-implement administrative operations as before with a separate process while waiting for https://github.com/microsoft/WindowsAppSDK/issues/3092 to be fixed? Because sometimes it's a bit annoying to always go back to the default explorer to open, delete, or rename a folder/file with administrator permissions without having to constantly run Files as an administrator.

**Comment by yaira2** [comment]
This issue is resolved in our dev branch and will be included in the next release.
