### ISSUE TITLE
Implement Set Background

### ISSUE THREAD

**Issue by CarlosRivera4726** [files-community/Files#10436]
### What feature or improvement do you think would benefit Files?

This is optional, but I want set new backgrounds and the option in the official explorer is the option, but in files (the best) is not

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.3.12.0

### Windows Version

10 22H2

**Comment by Josh-65** [comment]
This is available the preview version https://files.community/download/preview
