### ISSUE TITLE
Bug: Switching to Favorites is crashing after selecting a tag

### ISSUE THREAD

**Issue by isdwsdfv** [files-community/Files#10433]
### Description

Switching to Favorites is crashing after clicking a tag.

### Steps To Reproduce

1. Select a tag from the sidebar
2. Click "Favorites" on the sidebar
3. Files is crashing

### Steps to fix

I do not konw.

### Files Version

版本: 2.3.12.0 OS Version: 10.0.22621.755

### Windows Version

Windows 11 22H2 22621.755

### Relevant Assets/Logs

[files.txt](https://github.com/files-community/Files/files/9961101/files.txt)
![屏幕截图 2022-11-08 192741](https://user-images.githubusercontent.com/116344443/200565027-d9302837-2295-450f-a726-da715668a021.png)

**Comment by yaichenbaum** [comment]
What happens if you toggle the option on and off?

**Comment by isdwsdfv** [comment]
If this option is enabled, there is a high probability that it will crash. If you turn this option on and then turn it off, you are less likely to crash. This will not happen if the option is never turned on.

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Yair ***@***.***>
发送时间: 2022年11月8日 23:54
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [files-community/Files] Bug！ (Issue #10433)


What happens if you toggle the option on and off?

―

**Comment by Josh-65** [comment]
Can you please upload the debug.log and debug_fulltrust.log files directly to GitHub. You can get them in files settings > about > open log folder.

**Comment by isdwsdfv** [comment]
从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: Josh-65 ***@***.***>
发送时间: Wednesday, November 9, 2022 11:44:18 AM
收件人: files-community/Files ***@***.***>
抄送: isdwsdfv ***@***.***>; Author ***@***.***>
主题: Re: [files-community/Files] Bug！ (Issue #10433)


Can you please upload the debug.log and debug_fulltrust.log files directly to GitHub. You can get them in files settings > about > open log folder.

―

**Comment by Josh-65** [comment]
You can't send them via email you will have to open the issue on the github site

**Comment by isdwsdfv** [comment]
😶
All right.
从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年11月9日 11:58
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [files-community/Files] Bug！ (Issue #10433)


You can't send them via email you will have to open the issue on the github site

**Comment by isdwsdfv** [comment]
What should I do? I'm not familiar with GitHub.🤔

**Comment by Josh-65** [comment]
Where the leave comment box click on it. Then drag the two files into it and wait a few seconds then click comment

**Comment by isdwsdfv** [comment]
[debug.log](https://github.com/files-community/Files/files/9967414/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9967415/debug_fulltrust.log)

Is that the way to do it？🤔

**Comment by Josh-65** [comment]
yes

**Comment by isdwsdfv** [comment]
Is there anything to do?

发件人: Josh-65 ***@***.***>
发送时间: 2022年11月9日 12:58
收件人: files-community/Files ***@***.***>
抄送: isdwsdfv ***@***.***>; Author ***@***.***>
主题: Re: [files-community/Files] Bug！ (Issue #10433)


yes

**Comment by Josh-65** [comment]
The error in the logs might be fixed on the preview builds but the set as default options doesn't on it. It will probably just be a wait for the option to be fixed then you can use it.

**Comment by isdwsdfv** [comment]
Thanks.👍

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年11月9日 17:20
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [files-community/Files] Bug！ (Issue #10433)


The error in the logs might be fixed on the preview builds but the set as default options doesn't on it. It will probably just be a wait for the option to be fixed then you can use it.

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by isdwsdfv** [comment]
No， there isn‘t. It has been fixed.

You seem to have removed the animation.

Can you update it to the official version? I recently noticed the Windows Settings application also crashes due to Windows.Ui.Xaml.dll.


从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年12月12日 3:02
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [files-community/Files] Bug！ (Issue #10433)


Is this still an issue in the preview version? https://files.community/download/preview

―

**Comment by isdwsdfv** [comment]
That is amazing! It crashed again! It was crashed by Microsoft.UI.Xaml.dll. I don’t know why! But the app crashes far less often: only once so far, in fact.

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年12月12日 3:02
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [files-community/Files] Bug！ (Issue #10433)


Is this still an issue in the preview version? https://files.community/download/preview

―

**Comment by Josh-65** [comment]
If it crashes again you can make a new bug report for it

**Comment by isdwsdfv** [comment]
I've found that when I click a color tag in Tags and then click "Favorites," a crash happens. Other times, just click "Favorites," and it won't crash.
I don’t want to report a bug anymore, that is complex.


从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年12月12日 8:30
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [files-community/Files] Bug！ (Issue #10433)


Closed #10433<https://github.com/files-community/Files/issues/10433> as completed.

―

**Comment by isdwsdfv** [comment]
It will crash if I click the App or document or other things in bags.

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年12月12日 8:30
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [files-community/Files] Bug！ (Issue #10433)


Closed #10433<https://github.com/files-community/Files/issues/10433> as completed.

―

**Comment by hez2010** [comment]
Would you like to record a video of the repro steps so that we can reproduce it locally and fix the issue?

**Comment by isdwsdfv** [comment]
Is it OK?

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: Steve ***@***.***>
发送时间: Monday, December 12, 2022 9:35:11 AM
收件人: files-community/Files ***@***.***>
抄送: isdwsdfv ***@***.***>; Author ***@***.***>
主题: Re: [files-community/Files] Bug！ (Issue #10433)


Would you like to record a video of the repro steps so that we can reproduce it locally and fix the issue?

―

**Comment by hez2010** [comment]
You cannot attach the video as an email attachment, instead you need to upload the video from GitHub directly.

**Comment by isdwsdfv** [comment]
https://user-images.githubusercontent.com/116344443/207007646-6ffe0f90-7c9b-432c-9943-c229f0136b94.mp4

**Comment by hez2010** [comment]
Thanks. Can reproduce it locally.

**Comment by hez2010** [comment]
@yair100 I suspect it's another WinUI 3 bug.

```
2022-12-12 18:23:24.2531|ERROR|AppUnhandledException|Value cannot be null. (Parameter 'key')
	System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.ThrowHelper.ThrowArgumentNullException(String name)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at ABI.System.Type.ToAbi(Type value)
   at ABI.System.Type.Pinnable..ctor(Type type)
   at ABI.Microsoft.UI.Xaml.Controls.IFrameMethods.Navigate(IObjectReference _obj, Type sourcePageType, Object parameter, NavigationTransitionInfo infoOverride)
   at Files.App.Views.ModernShellPage.NavigateToPath(String navigationPath, Type sourcePageType, NavigationArguments navArgs)
   at Files.App.Views.MainPage.SidebarControl_SidebarItemInvoked(Object sender, SidebarItemInvokedEventArgs e)
   at Files.App.UserControls.SidebarControl.Sidebar_ItemInvoked(NavigationView sender, NavigationViewItemInvokedEventArgs args)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
--- End of stack trace from previous location ---
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
   at ABI.System.EventHandler`1.Do_Abi_Invoke[TAbi](Void* thisPtr, IntPtr sender, TAbi args)
```

**Comment by isdwsdfv** [comment]
Your changes in the preview version seem to have been updated to the official version, thank you very much! But in the official version, we still have the same problem that I had in the preview yesterday ：“I've found that when I click a color tag in Tags and then click "Favorites," a crash happens. Other times, just click "Favorites," and it won't crash. ” And ” It will crash if I click the App or document or other things in bags.”

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年12月12日 17:24
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [files-community/Files] Bug！ (Issue #10433)


Reopened #10433<https://github.com/files-community/Files/issues/10433>.

―

**Comment by isdwsdfv** [comment]
And it starts up a little slower than previous versions.



发件人: ***@***.***>
发送时间: 2022年12月12日 17:24
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [files-community/Files] Bug！ (Issue #10433)


Reopened #10433<https://github.com/files-community/Files/issues/10433>.

―

**Comment by yaira2** [comment]
Startup is a little slower for now but file naviation should be quicker.

**Comment by isdwsdfv** [comment]
https://user-images.githubusercontent.com/116344443/207199715-3baa34b8-2108-47e7-addc-4c9b53cd0621.mp4

https://user-images.githubusercontent.com/116344443/207199724-4a428569-20af-4942-81c3-ca265e033b05.mp4

Three bugs.

**Comment by isdwsdfv** [comment]
![屏幕截图 2022-12-13 201423](https://user-images.githubusercontent.com/116344443/207315999-fc38143b-f0d6-4f73-9d33-76b2bf127de0.png)

**Comment by Josh-65** [comment]
Is this still an issue in 2.4.8?

**Comment by isdwsdfv** [comment]
It's still slow to boot, but the bugs have been fixed.

发件人: ***@***.***>
发送时间: 2022年12月28日 14:58
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [files-community/Files] Bug: Switching to Favorites is crashing after selecting a tag (Issue #10433)


Is this still an issue in 2.4.8?

―
