### ISSUE TITLE
Removing `async void` methods

### ISSUE THREAD

**Issue by QuaintMako** [files-community/Files#10438]
### Description

We can find `async void` methods in the source code. Those methods are associated with _fire and forget_ behaviors. There is no way to wait for their end and response accordingly.

`async void` methods should be used only for event handling.

Instead, `async void` should be replaced by `async Task`. 

### Concerned code

- Whole Solution, there is currently 205 occurences of `async void`.

### Gains

- An ability to use `await` on `async` methods we could not before.
- Removing a code smell from the base.

### Requirements

- If an `async void` method is detected, make it into a `async Task` method.
- Be wary of `async void` event handlers. They can stay as is.

**Comment by kianiehsan66** [comment]
Is anyone working on this issue? I'd like to try it out, I'm new to open-source.

**Comment by TheBestUser01234567890** [comment]
> Is anyone working on this issue? I'd like to try it out, I'm new to open-source.

Yeah, I am new to contributing also

**Comment by yaira2** [comment]
@kianiehsan66 how's it going on this?
