### ISSUE TITLE
Search and sharing options

### ISSUE THREAD

**Issue by rav1980** [files-community/Files#10431]
### What feature or improvement do you think would benefit Files?

1. There is no information about the file search status in the program. Immediately after starting the search for files, the word "search results" appears in the directory path bar. It is not known whether the search is over or whether it is still necessary to wait for the next results.
2. Besides, I don't know if in the search results window it is possible to add a column where the file / folder is located. This is useful when you want to browse the list and find out where the files / folders are, and especially when you can sort the list by location on the disk or disks.
3. I also didn't find advanced / extended search, so I can't search for files within their size or date range.
4. There is no sharing option in folder / drive properties.
5. After clicking on the left bar icon it is not possible to display all disks or all library folders but you have to decide (drop-down menu) on one disk or folder. This makes it impossible, for example, to check a free space on all disks. You have to use the "home" icon, which is not intuitive for me.

### Requirements

- Add search progress information
- Add more columns like path (in search results), movie length, resolution of image files, bitrate of music files
- Add extended search options
- Add sharing options
- Add view of all libraries, disks (with information about their size and free space) just like on the main page.

### Files Version

Wersja: 2.3.12.0

### Windows Version

Windows 10 Pro 22H2 19045.2130

### Comments

Without these functions, I am often forced to use the default windows application or Total Commander, and I hope that your great idea for the appearance, arrangement of elements, customization options and of course tabs will allow me to use only your program.
BTW this is the first time i'm using github to ask for extra features. I would like to thank you for a great job on this project and wish you perseverance and creativity in the future.

**Comment by Josh-65** [comment]
Thanks for the feedback, please make them separate issue in future.

1) There is a loading indicator in the tab and performance improvements to it are being tracked here #6825 when complete search would hopefully be quick or instant.
2) Being tracked here #7070
3) Being tracked here #4813 and #7124
4) Being tracked here #5941. If it not what you mean please say.
5) The home button has a drive widget showing all drives and free/total space

**Comment by rav1980** [comment]
Great! I&#39;m not familiar with GitHub. I will wait for update.    Pozdrawiam  Rafał Kotarba 
            
          
     
      
       
        Dnia 8 listopada 2022 07:03 Josh-65 ***@***.***&gt; napisał(a):
       
    
       
         
 Thanks for the feedback, please make them separate issue in future. 
 
 There is a loading indicator in the tab and performance improvements to it are being tracked here  github.com #6825  when complete search would hopefully be quick or instant. 
 Being tracked here  github.com #7070 
 Being tracked here  github.com #4813  and  github.com #7124 
 Being tracked here  github.com #5941 . If it not what you mean please say. 
 The home button has a drive widget showing all drives and free/total space
