### ISSUE TITLE
option to turn off animation

### ISSUE THREAD

**Issue by nzarbayezid** [files-community/Files#10443]
### What feature or improvement do you think would benefit Files?

There should be an option to disable animation in the application

as you can see when you open the application it takes some time to load because of the animation | [preview](https://imgur.com/a/itfNZJ4).

my windows animation is turned off completely | [preview](https://imgur.com/a/5eXhA1l).

### Requirements

- we just need an option for turning out animation completely in the app

### Files Version

Version: 2.3.12.0 OS Version: 10.0.19044.2130

### Windows Version

Edition	Windows 10 Pro Version	21H2 Installed on	‎10/‎9/‎2022 OS build	19044.2130 Experience	Windows Feature Experience Pack 120.2212.4180.0

**Comment by yaichenbaum** [comment]
Animations can be turned off from the settings app in Windows.

**Comment by nzarbayezid** [comment]
https://imgur.com/a/5eXhA1l

mine is tuned off but the application still shows the animation!
