### ISSUE TITLE
Dual Pane Bug (On Open)

### ISSUE THREAD

**Issue by matthiscock** [files-community/Files#10449]
### Description

I get this bug on the two computers I use.

Setting:
Enable Dual Pane View: True
Always open tabs in dual pane mode: True

When I open the app, it open with one pane viewable, but the tab title suggests there should be two.
When I open a new tab - its the same

If I enter company overlay, and then exit compact overlay
- The dual panes show up and work as expected.

On Launch / And-Or on new tab
![image](https://user-images.githubusercontent.com/5795004/201317153-f3b53aaf-e591-46a3-bb45-1016a4e54863.png)

After entering and then exiting compacy overlay:
![image](https://user-images.githubusercontent.com/5795004/201317276-b09b68c3-8dbb-4e22-8f3d-fd49cf80c07e.png)

I tried uninstall / install no effect

### Steps To Reproduce

Open App
Only see one pane, two expected

### Steps to fix

Enter overlay mode
Exit overlay mode

### Files Version

2.3.12.0

### Windows Version

Windows 11 - Has happened on all versions ive had.  Im up to date

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9989218/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9989220/debug_fulltrust.log)

**Comment by Josh-65** [comment]
You said on #10276 that it's not the same but they look like the same issue. Can you say what you thinks different?
