### ISSUE TITLE
Feature: Shortcut to Show/hide dot files

### ISSUE THREAD

**Issue by mimoguz** [files-community/Files#10458]
### What feature or improvement do you think would benefit Files?

Dot files are *nix hack to hide files. Shouldn't their visibiliy also can be toggled using the "show hidden items" toggle and ctrl+h shortcut?

Currently the user needs to go to settings dialog each time they want to change the visibility of the dot files. Since, no thanks to multi-platform apps' mishandling of config/user data paths, now dot files are everywhere, I think that feature (it's very helpful btw, thanks for implementing it) should be streamlined.

### Requirements

- Toggle the dot files' visibility using the same toggle button and shortcut used for hidden files.
- If desired, add an option to turn this behaviour on/off.

### Files Version

Version: 2.3.12.0

### Windows Version

Windows 11 22H2 22621.819

**Comment by mimoguz** [comment]
Alternatively, show dot files settings can be an enum with three members: hidden, visible, and 'same as hidden files and folders'.

**Comment by mimoguz** [comment]
> Alternatively, the "show dot files" setting can be an enum with three members: hidden, visible, and "same as hidden files and folders".

I  just went ahead and -hastily- implemented this: [Commit link](https://github.com/mimoguz/Files/commit/fd39c187d5eaba675ec51c7ec76396007b9d048b). What do you think.

**Comment by yaichenbaum** [comment]
Dot files are not the same as hidden files, I'm interested in hearing more about your use case for constantly toggling the setting on and off.

**Comment by mimoguz** [comment]
> Dot files are not the same as hidden files

Technically, you're correct, they are not the same. But they accomplish same thing in their respective worlds. On KDE file manager, Dolphin, the option to show dot files is even labeled as "Show Hidden Files".

>  I'm interested in hearing more about your use case for constantly toggling the setting on and off.

What is the use case for constantly toggling hidden items? Under my user folder, there are 51 dot folders and 8 dot files, and some of them belong to Microsoft apps!. They should have been under AppData, but they are not. The java project I'm currently working on has 3 dot folders: .git, .github, .idea, And then there are .gitignore and .editorconfig files. They should be hidden by default, but they are not. Most of the time I don't need to see them, like I don't need to see the _"regular"_ hidden files, they are just visual noise. But sometimes I need to see them, just like sometimes I need to see the regular hidden files. Files has a quick toggle and a shotcut to show/hide hidden items, and I just thought that those can be used to show/hide dot files too.

Anyway, thanks!. And sorry for my broken English.

**Comment by yaichenbaum** [comment]
If we can add a shortcut for this, what would you suggest?

**Comment by mimoguz** [comment]
> If we can add a shortcut for this, what would you suggest?

Ctrl + . 

🙂

**Comment by cinqmilleans** [comment]
A feature to modify hotkeys is in the works. This will also allow keyboard shortcuts to be assigned to commands that do not have them by default.

**Comment by yaira2** [comment]
Merging with #11481
