### ISSUE TITLE
Bug: Crash in Column layout after opening subfolder and clicking a breadcrumb

### ISSUE THREAD

**Issue by kraleb** [files-community/Files#10455]
### Description

When a file is dragged into a subdirectory while in the column layout, such that the subdirectory opens as the new primary pane, and then a folder is selected from the address breadcrumb, the app crashes with a 'Something went wrong!' error.

![image](https://user-images.githubusercontent.com/43391485/201498081-f05eac32-f1ab-48cc-8381-3664b917acee.png)
Clicking any of the breadcrumbs (Users, kaleb, Documents, Example Folder) will crash the program in this state.

### Steps To Reproduce

1. Enable the Column Layout
2. Drag a file to a folder, hold on the folder long enough for Files to open it as a new primary pane
3. Release the file, it will be moved into the folder
4. Click a breadcrumb in the address bar
5. The program should crash and pop an 'Something went wrong!' error

### Steps to fix

- The program should not crash, and navigate similarly to normal operation in the described context.

### Files Version

2.3.12.0

### Windows Version

Windows 11 10.0.22621 

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9996101/debug.log)

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by kraleb** [comment]
> Is this still an issue in the preview version? https://files.community/download/preview

Does not look like it is an issue on the Preview version (2.3.59.0), from what I can tell - Feel free to close this out at your leisure.
