### ISSUE TITLE
Bug: Navigating using arrows in Columns Layout break tab name

### ISSUE THREAD

**Issue by ferrariofilippo** [files-community/Files#10452]
### Description

Sometimes, while navigating between columns (using arrows), it happens that the tab name keeps changing.
I think this is caused by the focus bouncing between the last two blades.
I post here a video to show what happens.

### Steps To Reproduce

1. Open a folder and set Layout to `Columns`
2. Navigate using arrows (Up/Down and Right/Left) for a while
3. See that tab name keeps on changing

### Steps to fix

- The focus should not bounce between the last two blades

### Files Version

Version: 2.3.55.0 OS Version: 10.0.22621.755

### Windows Version

Windows 11 Home Version 22H2 22621.755

### Relevant Assets/Logs

https://user-images.githubusercontent.com/102259289/201476781-9387d55b-9ac8-4783-9d05-fb162fed2c48.mp4

**Comment by ferrariofilippo** [comment]
This is not a bug anymore since the tab name shows only the name of the first column. I'm not sure this is the expected behaviour

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by ferrariofilippo** [comment]
Yes it is. Actually, the issue is that the tab name shows the name of the first column
For example if I open `C:/Users` tab name will be `C:` instead of `Users`

**Comment by yaira2** [comment]
I can reproduce this issue as well

**Comment by ferrariofilippo** [comment]
> I can reproduce this issue as well

It seems to work on my end, both in preview and dev (last opened column path is displayed in the tab)

**Comment by ferrariofilippo** [comment]
@yair100 it's working on my side, can you confirm?
