### ISSUE TITLE
Incorrect text coloration after switching themes.

### ISSUE THREAD

**Issue by AqilCont** [files-community/Files#1045]
### Describe the bug
Text coloration doesn't switch back accordingly when switching to dark theme from light theme.

### To Reproduce
1. Go to Settings
2. Switch to light mode
3. Exit out
4. Go to Settings again, but switch to dark mode this time
5. Exit and observe

### Expected behavior
It should simply be the correct color. Not anything too major, but makes the whole aesthetics and everything else(basically the reason for this project) kind of pointless.

### Screenshots
![image](https://user-images.githubusercontent.com/32044067/84557389-c37f7b00-acf8-11ea-8a33-a4024845b315.png)

### Desktop (please complete the following information):
- **OS:**
![image](https://user-images.githubusercontent.com/32044067/84557423-017c9f00-acf9-11ea-91d1-c9ebdaff770b.png)
 - **App version: v0.10.1**

**Additional context**
This is after me completely breaking it(its rendered useless) after switching view mode. Navigating to large folders hard crashes everything.

**Comment by yaichenbaum** [comment]
@AqilCont Thank you for opening this issue, it appears as if this is an issue with the DataGrid control we are currently using. I am closing this issue since it will likely be resolved when the new WinUI DataGrid control is ready.
