### ISSUE TITLE
Downloads folder - Files [ appearing in | sorted into ] incorrect relative timeframe group

### ISSUE THREAD

**Issue by raynerdacruz** [files-community/Files#10450]
### Description

In Figure 1, Files displays the 2 files ( marked in a red dotted square ) in the **incorrect** -> Last Month, relative timeframe group. In comparison, File Explorer ( Figure 2 ) displays the **same** 2 files ( marked in a red dotted square ) in the **correct** -> Last Week, relative timeframe group. 

Also, I'm not sure if this issue is just isolated to the Downloads folder or wide-ranging, as I've only just started using Files as an alternative file explorer.

Figure 1 - Files
![ApplicationFrameHost_TkAVWSQPEy](https://user-images.githubusercontent.com/10243952/201411779-93ac53e4-8209-4210-a526-39df7a79fc2d.png)

Figure 2 - File Explorer
![explorer_tcX5CttQx9](https://user-images.githubusercontent.com/10243952/201411799-ff8fe03d-5ca1-487f-ba82-2406e0735831.png)

### Steps To Reproduce

N/A

### Steps to fix

Fix the bug causing files to appear in the incorrect relative timeframe group.

### Files Version

2.3.12.0

### Windows Version

10.0.19045.2130

### Relevant Assets/Logs

N/A

**Comment by raynerdacruz** [comment]
I've installed the latest preview, Version: 2.3.58.0, and I'm seeing the same problem.

**Comment by raynerdacruz** [comment]
I think I've figured out why I'm seeing the issue that I've described originally.

" Relative timeframe groups " refers to Today, Yesterday, Last Week, Last Month, etc.

So my theory is:
The files and folders are being categorized or grouped into relative timeframe groups based on date of creation.
And then within each relative timeframe group they're being sorted by date modified.

To prove my theory, let's take a file from the Downloads folder and verify the theory by touching its date modified timestamp. 
Specifically I will change the date from 14/11/22 to 26/11/22, and time from 14:08 to 22:08.
In Files, I expect the file to remain in the same relative timeframe group, except now it should appear at the top of the category.
In File Explorer I expect the file to move into a different relative timeframe group - from Last Week to Today. I haven' included the screenshot of this but you can trust me that's what happened.


And my theory was right. See Before and After.


Now, the problem I have with the approach adopted by Files is that it's a bit odd as a user that is familiar with how File Explorer does it - I prefer how File Explorer does it. However, now that I know what's happening with the files and folders in the Downloads folder ( within Files ), the approach adopted by Files of grouping by creation date and then sorting by date modified does kind of make sense as to why Files does it that way - but I still prefer how File Explorer does it ( change my mind ), as opposed to File Explorer's way of grouping by date modified and sorting by date modified - not sure if that's technically the right way to say it. 

Given what I've explained above, it would be nice to have an option in the settings that allows us to toggle between the 2 approaches, or just have a poll and go with one if we can't have both.

Before:
![image](https://user-images.githubusercontent.com/10243952/204113611-a8f59ae5-3432-43d1-a30e-23f8294384ec.png)

After:
![image](https://user-images.githubusercontent.com/10243952/204113613-20dd8706-db38-4686-8ce7-b71a2a778814.png)

**Comment by Josh-65** [comment]
You can change what there grouped and sorted by with the options
![image](https://user-images.githubusercontent.com/26977075/204114025-647fbcde-eb7f-45c8-aa59-d0f4c2d54d1e.png)

**Comment by raynerdacruz** [comment]
That's perfect, now I have it like how File Explorer shows it. How did I not see that lol.
