### ISSUE TITLE
Important Things to Add

### ISSUE THREAD

**Issue by yigitytkn** [files-community/Files#10454]
### What feature or improvement do you think would benefit Files?

The app needs improvement to completely replace the default file explorer. Because Microsoft will not be able to offer a file explorer of this quality. I wanted to share a few features that I saw missing.

### Requirements

- The application name "Files" must be variable according to the language of the operating system. For example, if the operating system language is Turkish, the application should appear as "Dosyalar" instead of "Files".

- Also the default file manager feature should definitely be improved. For example, the "Save As" window should be added. When we want to download files from the browser, the Windows file explorer opens to select the location and specify the file name. Also, although the default file manager is "Files", clicking the Windows Explorer icon does not open "Files".

- Bitlocker support should be added.

- File tags should be support Turkish.

### Files Version

2.3.12.0

### Windows Version

Windows 11 22H2 22623.891

**Comment by Josh-65** [comment]
1. Files is the name of the program it doesn't makes sense to change it based on language. Other programs also don't do this.
2. Save as is on the do to list
3. Bit locker is supported and control by windows.
4. File tags do support all languages
