### ISSUE TITLE
Delete file stuck at 0%

### ISSUE THREAD

**Issue by j4yjoe** [files-community/Files#10457]
### Description

hi, when i delete a file, the ongoing task is very often stuck at 0%. a sign of this bug is always that the "permanently delete" field is grayed out before deleting the file. 
is there any way to fix this?

### Steps To Reproduce

1. Delete a file
2. Check Ongoing Tasks if glitch has happened

### Steps to fix

Restart the programm

### Files Version

Version: 2.3.12.0

### Windows Version

Windows 21H2

### Relevant Assets/Logs

![deleting files](https://user-images.githubusercontent.com/96732797/201518440-c34e580b-e8b4-412e-a792-23df95970d87.png)
![deleting files 2](https://user-images.githubusercontent.com/96732797/201518553-7237f694-8535-44dc-88a1-7d8218313ab4.png)

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
