### ISSUE TITLE
Tag column showing 1 tag only even if there is enough space for more.

### ISSUE THREAD

**Issue by chungchungdev** [files-community/Files#10468]
### Description

As the title said.

### Steps To Reproduce

1. Tag a file with 2 or more tags.
2. Make sure the tag column have enough space to show 2 or more tags.
3. Only the first tag is shown

### Steps to fix

show as many tags as possible to fill the width of tag column

### Files Version

Version: 2.3.12.0 OS Version: 10.0.22621.755

### Windows Version

Windows 11 22H2 22621.755

### Relevant Assets/Logs

not applicable

**Comment by yaichenbaum** [comment]
Merging with #9584
