### ISSUE TITLE
Are you sure you want to copy this files without its properties?

### ISSUE THREAD

**Issue by StrBalu** [files-community/Files#10461]
System is Win10 with google drive mapped as a network drive.
When copying to this mapped drive, in regular windows explorer there is a prompt:
**Are you sure you want to copy this files without its properties?**

This prompt is missing in files. The copy just fails (unsuccessful copy) without further information or a prompt.

OS: Microsoft Windows 10 Enterprise Version 10.0.19042 Build 19042
Files: 2.3.12.0

**Comment by Josh-65** [comment]
Merging with #9423
Please follow the issue templates next time.
