### ISSUE TITLE
Bug: Navigating with keys in the Column Layout crashes the program

### ISSUE THREAD

**Issue by kraleb** [files-community/Files#10464]
### Description

While in the Column layout, using left and right arrow keys to traverse the file structure causes the program to exit with a 'Something went wrong!' error, and induces a catastrophic failure.

This bug is present on the Preview build (v 2.3.59.0) and not on the stable release (v 2.3.12.0)

### Steps To Reproduce

1. Enter the Column layout
2. Enter a folder
3. Select *either* a subfolder or a file within that folder
4. Press the right arrow key
5. The program will exit with a catastrophic error

Alternatively, if you are in a subfolder and wish to return to a parent folder, pressing the left arrow key will crash the program.

### Steps to fix

- Fix crash that occurs when navigating the folder structure using the directional keys in the column layout.
  - I would expect this functionality to mirror that of Finder's (Mac OS) column view.
  - In the case that the selected item is a file, and not a folder, I think nothing should happen when pressing the right arrow key when it is selected.

### Files Version

2.3.59.0 (Preview)

### Windows Version

Windows 11 22H2 22621.819

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10005150/debug.log)

**Comment by yaichenbaum** [comment]
Merging with #10109
