### ISSUE TITLE
[Bug] Opening multiple files of the same type makes Files app (Preview sideload version) crash.

### ISSUE THREAD

**Issue by slavoyar8601** [files-community/Files#10460]
### Description

Opening multiple files of the same type makes Files app (Preview sideload version) crash. The bug doesn't present in Stable version off MS Store.

### Steps To Reproduce

1. Open any folder
2. Select 2 or more files of the same type
3. Press Enter

### Steps to fix

Fix the opening of files of the same type.

### Files Version

2.3.59.0

### Windows Version

Windows 11 Pro Insider Preview, 22H2, 25236.1010

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10002984/debug.log)

**Comment by Josh-65** [comment]
Merging with #10423
