### ISSUE TITLE
File copy fails without prompt or additional info

### ISSUE THREAD

**Issue by StrBalu** [files-community/Files#10463]
### Description

File copying fails when an internet-originated file is attempted to be copied to a google drive mapped as a network drive. 

### Steps To Reproduce

1. Download a file from the internet
2. Try to copy the file downloaded to google drive (mapped as a network drive)

### Steps to fix

There should be a prompt asking if I want to proceed, like in case of windows explorer:

![image](https://user-images.githubusercontent.com/17196176/201705888-a37db3a4-4f30-49c0-ad9e-3197fa7a9875.png)

### Files Version

2.3.12.0

### Windows Version

Microsoft Windows 10 Enterprise Version 10.0.19042 Build 19042

### Relevant Assets/Logs

<img width="252" alt="image" src="https://user-images.githubusercontent.com/17196176/201707606-6b7c413e-107e-4a24-b912-b21ec567fa06.png">

**Comment by Josh-65** [comment]
Merging with #9423
