### ISSUE TITLE
Bug: Nord theme is using the wrong colors

### ISSUE THREAD

**Issue by Burntninjas** [files-community/Files#10465]
If the theme is intended to be based on [Nord](https://www.nordtheme.com) colors:
`#3d4252` should be  `#3b4252`
`#d8dee9` should be `#d8dee9`

**Steps to fix**
- Update the theme file with the correct colors

**Comment by yaichenbaum** [comment]
Do you want to open a PR with this change?

**Comment by Burntninjas** [comment]
I've created a pull request: #10466
