### ISSUE TITLE
Save / cache field width

### ISSUE THREAD

**Issue by tejo-ak** [files-community/Files#10470]
### What feature or improvement do you think would benefit Files?

The **Files** should have a capability to persist (save or cache) the width of each field (e.g., Name, file tag, date modified, etc.) primarily in the "Details Layout) after the width of those field changed

Currently, the widths configuration will reset to its default setting when a folder is opened

### Requirements

- improve user experience
- reduce users' confusion when viewing files or folders in details layout mode

### Files Version

Version: 2.3.12.0 OS Version: 10.0.19042.1706

### Windows Version

10.0.19042.1706

**Comment by Josh-65** [comment]
This is fixed in the preview version https://files.community/download/preview
