### ISSUE TITLE
Feedback and request

### ISSUE THREAD

**Issue by newyork2003** [files-community/Files#10478]
Im a viusal artist. Ive been working for 10 years in OSX/Finder with a huge amount of files and folders. And I need it to be visual (thumbnail).  When dealing with huge amounts of visual data is necessary the file type group. Since too many folders are useless (visualizing what is inside each one is counterproductive).
I personally love how Finder organizes it:
1st- folders
2nd- documents
3rd- images
4th-PDF documents
5th- video files
6th-others

And going now to windows is a horror show. Since its grouped alphabeticlly. And certain files like images, text and video are separated by the exact file type. Ex: JPEG and PNG are in separated groups. And alphabetilly order does not make sense.
I would love a windows software where i could choose what to put inside each group and its hirearchy in the layout.

**Comment by Josh-65** [comment]
Please make a new issue following the issue templates.

**Comment by newyork2003** [comment]
ok, new here :)
