### ISSUE TITLE
Bug: Crash when right clicking on media files

### ISSUE THREAD

**Issue by cleuton4k** [files-community/Files#10485]
### Description

fails to right click on media files like mp3,mp4,png.....

### Steps To Reproduce

fails to right click on media files like mp3,mp4,png.....

### Steps to fix

fails to right click on media files like mp3,mp4,png.....

### Files Version

2.3.60

### Windows Version

w10 22h2 64bit

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10016573/debug.log)

**Comment by Josh-65** [comment]
I can't reproduce this. The log also doesn't show a crash. Did this happen one time or multiple times?

**Comment by cleuton4k** [comment]
it happens every time i right click on a file/folder and then the app crashes

**Comment by cleuton4k** [comment]
https://user-images.githubusercontent.com/90144967/202228464-495e4651-70d4-4459-b399-ad202c1c0609.mp4

**Comment by cleuton4k** [comment]
What I have to do?

**Comment by yaira2** [comment]
Build the app and try to reproduce the crash

**Comment by cleuton4k** [comment]
unfortunately I don't know how to do that, because I'm not a developer

**Comment by yaira2** [comment]
Can you share the file you're right clicking on?

**Comment by cleuton4k** [comment]
2.4 is ok

**Comment by prochak96** [comment]
I suddenly started having this problem with first the preview version, and now 2.4 too.
