### ISSUE TITLE
Move favourite items

### ISSUE THREAD

**Issue by newyork2003** [files-community/Files#10482]
### What feature or improvement do you think would benefit Files?

Add the posibility to move the order of the favourite items

### Requirements

- This proposal will accomplish a better persoalization

### Files Version

2.3.12

### Windows Version

Windows 10

**Comment by yaira2** [comment]
You can right click favorites to reorder the items.

**Comment by newyork2003** [comment]
Well, not very intuitive

**Comment by yaira2** [comment]
Drag and drop is blocked by this issue https://github.com/microsoft/microsoft-ui-xaml/issues/3290
