### ISSUE TITLE
Refresh "group by date"

### ISSUE THREAD

**Issue by newyork2003** [files-community/Files#10483]
### Description

Every time that my "download file" refreshes it strats by showing the "yesterday" not the "today"

### Steps To Reproduce

1- go to "downloads" while in "group by date"
2-refresh it
3- it will show 1st the day before 

### Steps to fix

-fix it to show the "today"

### Files Version

2.3.12

### Windows Version

Windows 10 Pro Version	21H2 Installed on	‎25/‎08/‎2022 OS build	19044.2251 Experience	Windows Feature Experience Pack 120.2212.4180.0

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/10016323/debug_fulltrust.log)

**Comment by yaira2** [comment]
Is this the same as #6186?

**Comment by Josh-65** [comment]
I presume it is
