### ISSUE TITLE
The hover color of the close caption button of does not match Windows 11 

### ISSUE THREAD

**Issue by Poopooracoocoo** [files-community/Files#10497]
### What feature or improvement do you think would benefit Files?

The hover color of the close caption button of does not match Windows 11's new color.

### Requirements

- This proposal will make Files fit in with Windows 11 better

### Files Version

2.3.60.0

### Windows Version

Windows 11 21H2 22000.1219

### Comments

Expected behaviour found in version 2.3.12.0:
<img width="100" alt="image" src="https://user-images.githubusercontent.com/51363864/202233845-4f28ab39-e88c-4605-b6fa-ef51348161dc.png">

Actual behaviour found in Preview Version 2.3.60.0:
<img width="99" alt="image" src="https://user-images.githubusercontent.com/51363864/202233893-4852d05d-49ea-4f5e-9ded-7bb037efb0c6.png">

It'd be great if the caption buttons got some more love as a whole, but I realise Microsoft hasn't decided on what they should like. Gotta think about hover states, pressed states, active and inactive, light and dark mode, and fade effects.

**Comment by yaira2** [comment]
Seems like an issue with WinAppSdk, can you open an issue on their repository?
