### ISSUE TITLE
Bug right click

### ISSUE THREAD

**Issue by Karapass56** [files-community/Files#10495]
### Description

When i right click on a file, the app just crash...

### Steps To Reproduce

1. Go into your Files app
2. Right click on any file 
3. it will crash...

### Steps to fix

- eg. Fix crash that occurs when right clicking on a file

### Files Version

Version 2.3.12.0

### Windows Version

Windows 10 22H2 19045.2251

### Relevant Assets/Logs
[debug.log](https://github.com/files-community/Files/files/10036911/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/10036912/debug_fulltrust.log)

**Comment by Josh-65** [comment]
Can you please upload the debug.log and debug_fulltrust.log files directly to GitHub (email attachments don't work) . You can get them in files settings > about > open log folder.

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
