### ISSUE TITLE
Google chrome and zip folders

### ISSUE THREAD

**Issue by JoshyJoshyJoshy** [files-community/Files#10498]
### Description

When trying to open a zip file from gogole chrome with files set as zip default, i get the error in relevant assests

### Steps To Reproduce

1: Set files as default for .zip files
2: Download a zip from google chrome
3: Double click

### Steps to fix

Find some way to get rid of the error?

### Files Version

Version: 2.3.12.0 OS Version: 10.0.22621.819

### Windows Version

Windows 11 22H2 22621.819

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/83929921/202329141-15c4883c-134b-4056-85bf-b6321b5afdc1.png)

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by JoshyJoshyVR** [comment]
Error in parsing the package

**Comment by yaira2** [comment]
Sometimes you need to restart Windows to get the installation to work.

**Comment by JoshyJoshyVR** [comment]
Ah, in that case i cant do that right now, im at achool, give me about an hour if thats ok

**Comment by YeahJenni** [comment]
@yair100 Even after a restart the preview doesnt work. Is it that the appinstaler is 2kb? The fact that microsoft store is blocked at my school? If its because microsoft store is blocked i need time to get home, where i have unblocked wifi

**Comment by yaira2** [comment]
Can you try again with the latest preview?
