### ISSUE TITLE
在对文件布局设置的时候希望可以像windows自带的工具一样可以应用全部

### ISSUE THREAD

**Issue by dx3284470** [files-community/Files#10499]
### What feature or improvement do you think would benefit Files?

现在工具只能对某一个文件夹中的文件进行布局设置，但是我希望可以对一个文件夹内的文件进行布局设置后可以应用到所有的文件上。比如我打开文件夹选择小图标，可以点击应用到全局，这样我打开别的文件夹后里面可以直接显示成小图标而不是列表

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.3.12.0

### Windows Version

Windows 10 21H2

### Comments

![1668657411797](https://user-images.githubusercontent.com/118417141/202351500-9fb73e8a-ef6c-473b-9944-70c6a0a0ae76.png)
想要添加的就是这个按钮的功能

**Comment by yaira2** [comment]
The latest preview build has support for changing the default layout. https://files.community/download/preview
