### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by foursplaysroblox** [files-community/Files#10507]
### What feature or improvement do you think would benefit Files?

I suggest files having the tabbed windows meterial it should look like this
![image](https://user-images.githubusercontent.com/82078139/202683314-2c36d630-7d7f-41d0-b7c7-e3226e7ea822.png)

### Requirements

- Changes the theme of Files

### Files Version

Version 2.3.12.0

### Windows Version

Windows 11 22H2 25236.1010

**Comment by Josh-65** [comment]
Files already has a Windows 11 mica but also the acrylic in the custom themes. You can also add custom image as the background here https://files.community/blog/posts/how-to-use-background-image
