### ISSUE TITLE
Tags crash the app

### ISSUE THREAD

**Issue by Newguru-1** [files-community/Files#10502]
### Description

Whenever I set a tag on a file, the file never shows up on the tag filter, and a pop-up notification shows up: "something went wrong: files ran into a problem that the developers didn't prepare for yet".

### Steps To Reproduce

1. Open the Files app
2. Set a color tag on a file
3. Choose the tag color filter on the sidebar
4. No files show up, and the app crashes.

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

Files (Preview) version 2.3.60.0

### Windows Version

Windows 11 Pro 22H2 10.0.22621 Build 22621

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10031015/debug.log)

**Comment by hez2010** [comment]
Thanks for reporting. I have sent a quick fix to this issue.
