### ISSUE TITLE
How to diable animation?

### ISSUE THREAD

**Issue by GhostShadow0316** [files-community/Files#10509]
### Description

I want to disable animation in Files bc it makes my computer slower.

### Steps To Reproduce

.

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

2.3.12.0 OS Version: 10.0.19045.2251

### Windows Version

Edition	Windows 10 Pro Version	22H2 Installed on	‎11/‎7/‎2022 OS build	19045.2251 Experience	Windows Feature Experience Pack 120.2212.4180.0

### Relevant Assets/Logs

.

**Comment by Josh-65** [comment]
You can disable them in Windows settings > ease of access > Animations. It may be under one of the sidebar options.
