### ISSUE TITLE
Preview Version 2.3.60: Cannot Install 

### ISSUE THREAD

**Issue by valsamis-d** [files-community/Files#10508]
Hello,

I downloaded the preview version of files (_Files.preview.appinstaller_) but the installation fails with the following error:

_App installation failed with error message: Appinstaller operation failed with error code 0x80070490. Detail: Element not found. (0x80070490)_

Any ideas?

Thank you
Dimi

**Comment by Josh-65** [comment]
This is an app installer issue.
You can try running these in an admin CMD terminal then restart when there finished.
sfc /scannow
dism /online /cleanup-image /restorehealth
