### ISSUE TITLE
OTA updates for Files

### ISSUE THREAD

**Issue by sfksuperman** [files-community/Files#10504]
### What feature or improvement do you think would benefit Files?

I don't find any inbuilt updater or OTA update feature yet. If it's not available yet, please bring it. Thanks.

### Requirements

I don't find any inbuilt updater or OTA update feature yet. If it's not available yet, please bring it. Thanks.

### Files Version

Version: 2.3.12.0

### Windows Version

Windows 11 22H2 22621.819

### Comments

If I'm missing anything, please guide me.

**Comment by sfksuperman** [comment]
> Files has auto update built in, v2.3.12 is currently the latest stable version but it should auto update when the next release is available.

1) and what about Files version 2.3.6.0? because I'm checking it right for and not getting any auto update so far.
2) don't you think we should get a visible button to check for updates whenever we want?

**Comment by Josh-65** [comment]
2.3.60 is for preview ? https://files.community/download/preview

**Comment by sfksuperman** [comment]
Ok fine I will fresh install the latest one. One last thing, why the download speed of github is way slow? I'm using good speed wifi as of now.

**Comment by Josh-65** [comment]
GitHub is the full file while the site one is effectively just a shortcut to the actual file
