### ISSUE TITLE
Continue were you left off option doesnt work always

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#10501]
### Description

Many time I've had the option just not save and restore the tabs. Usually when Files is force closed or crashes.

### Steps To Reproduce

1. Enable Continue were you left off in Files settings > preferences > startup settings
2. Open a few tabs
3. Have Files crash
4. See it opens to Home

### Steps to fix

?

### Files Version

2.3.60

### Windows Version

10.0.22621.819

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10030478/debug.log)

**Comment by yaira2** [comment]
Merging with #5993

**Comment by BanCrash** [comment]
@Josh-65 do you have more than one Files window opened when this happens? Or just one?

**Comment by Josh-65** [comment]
Just one
