### ISSUE TITLE
Add an option to add the selected file context menu to the more area of the toolbar

### ISSUE THREAD

**Issue by dpierangeli** [files-community/Files#10500]
### What feature or improvement do you think would benefit Files?

On a touch device the opening of the context-menu by long tapping is not really reliable, sometimes it needs some trying to invoke it.

I'd like an option to add the selected file/folder context menu in the 'more' area of the toolbar.

### Requirements

- This proposal will accomplish help using the context menu on a touch device

### Files Version

Versione 2.3.12.0 

### Windows Version

Windows 11 22h2

### Comments

Quick edited screenshot ;)

![Immagine-screen](https://user-images.githubusercontent.com/9047951/202393312-1fc1d59c-1cd7-4fad-ba3a-9a25a0798055.png)

**Comment by yaira2** [comment]
Merging with #6085
