### ISSUE TITLE
Allow to resize the information area in Preview section

### ISSUE THREAD

**Issue by dhbtfs** [files-community/Files#10511]
### What feature or improvement do you think would benefit Files?

All us to resize the information area in preview section. Preview section can be resized, it could also change the mouse icon so we would know you can do this.
![Screenshot 2022-11-18 193123](https://user-images.githubusercontent.com/95389975/202789286-6819e6b5-cb14-4e8f-81ff-7e35e3c4a044.png)

### Requirements

- This proposal will make the Preview section actually useful.

### Files Version

Version: 2.3.60.0 OS Version: 10.0.22621.819

### Windows Version

Edition	Windows 11 Pro Version	22H2 Installed on	‎13/‎11/‎2022 OS build	22621.819 Experience	Windows Feature Experience Pack 1000.22636.1000.0

**Comment by yaira2** [comment]
You can right click in the empty space around the preview and click the option to only show the preview.
