### ISSUE TITLE
Replace copy option in recycle bin with with cut

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#10516]
### What feature or improvement do you think would benefit Files?

Doesn't make sense to copy items from the recycle bin but moving them instead

### Requirements

- Disable copy in recycle bin
- Enable move/cut in recycle bin

### Files Version

2.3.60.0

### Windows Version

10.0.22621.875

**Comment by yaira2** [comment]
I don't see an issue with the current setup, cut already works so I'm not sure we need extra logic to disable copy.
