### ISSUE TITLE
create shortcut for files 

### ISSUE THREAD

**Issue by vipking-o1** [files-community/Files#10510]
### What feature or improvement do you think would benefit Files?

a feature that can make a shortcut to a folder in that opens in files

### Requirements

alow to create a shortcut that opens a folder in files 

### Files Version

Version: 2.3.12.0 OS Version: 10.0.22622.590

### Windows Version

22622.590

**Comment by Josh-65** [comment]
You can right click a folder and make a shortcut. Then move it to where you want.
