### ISSUE TITLE
Clicking the install button in the ribbon after selecting a font file, does not install the font.

### ISSUE THREAD

**Issue by ElitePheonix2009** [files-community/Files#10512]
### Description

I have selected a font file such as .ttf and .otf. Then , I have clicked on the install button the ribbon. Clicking it does not do anything.

### Steps To Reproduce

1. Select a font file such as .ttf and .otf.
2. Click on the install button on the ribbon.
3. See that it does not install the font.

https://user-images.githubusercontent.com/114980232/202835442-1b92586e-f36e-4431-a00f-5ad225f1a7b9.mp4

### Steps to fix

Make sure that clicking the install button in the ribbon pops up the installing fonts window and installs the font.

### Files Version

Version: 2.3.12.0 OS Version: 10.0.19045.2251

### Windows Version

Edition	Windows 10 Pro Version	22H2 Installed on	‎15-‎09-‎2022 OS build	19045.2251 Experience	Windows Feature Experience Pack 120.2212.4180.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10046121/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/10046122/debug_fulltrust.log)

**Comment by Josh-65** [comment]
They do install but without showing the dialog. Can you check `C:/Windows/fonts` to see if it's there

**Comment by ElitePheonix2009** [comment]
> They do install but without showing the dialog. Can you check `C:/Windows/fonts` to see if it's there

I have checked the fonts from windows settings, but it's not there.

**Comment by Josh-65** [comment]
Can you check the folder location. Windows front in settings don't always have the same name as the file

**Comment by ElitePheonix2009** [comment]
> They do install but without showing the dialog. Can you check `C:/Windows/fonts` to see if it's there

It's not there

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by ElitePheonix2009** [comment]
> Is this still an issue in the preview version? https://files.community/download/preview

It is still not fixed in the preview version

**Comment by yaira2** [comment]
@ElitePheonix2009 is the user an administrator? What happens if you run Files as admin?
