### ISSUE TITLE
Feature: Enable folder context menus on taskbar icon jumplist

### ISSUE THREAD

**Issue by Newguru-1** [files-community/Files#10518]
### What feature or improvement do you think would benefit Files?

Hello

It would be great if you could enable folder contextual menus on the taskbar jumplist itself - huge timesaver!!!

In practice, enable the same functionality already present on windows explorer.

Thanks for all the hard work!

The immediate benefit example would be to empty the recycle bin, straight from the taskbar jumplist.

Example: (windows explorer jumplist contextual menu / files app jumplist contextual menu)

![windows explorer](https://user-images.githubusercontent.com/16686682/202869420-1e2a7d53-e53c-4dac-96c5-ba6ad0b6ec86.jpg)

![files preview](https://user-images.githubusercontent.com/16686682/202869425-e552b5e2-20d3-4329-b362-8a8ce137a141.jpg)

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

Files (Preview) version 2.3.60.0

### Windows Version

Windows 11 Pro 22H2 10.0.22621 Build 22621

**Comment by yaira2** [comment]
Is there an api for this :thinking:

@ahmed605

**Comment by ahmed605** [comment]
> Is there an api for this :thinking:
> 
> @ahmed605 

Looks like Windows doesn't support showing jumplist for things without AppID/AUMID, and Recycle Bin doesn't have one

So I guess Explorer is adding them manually if it detects Recycle Bin?

**Comment by yaira2** [comment]
It seems that File Explorer is doing something custom here.

**Comment by Newguru-1** [comment]
Bummer. That's unfortunate since it's a massive difference. Thanks anyway.
