### ISSUE TITLE
Bug: 7zip size information isn't shown correctly 

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#10528]
### Description

Title

### Steps To Reproduce

1. Create a .zip or .7z archive
2. Go to properties of archive
3. See uncompressed size as 0b

### Steps to fix

- Correctly disable the archives uncompressed size

### Files Version

2.3.61.0

### Windows Version

10.0.22621.875

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10050834/debug.log)

**Comment by gave92** [comment]
Fixed by #10563
