### ISSUE TITLE
Bug: Some settings aren't exported/import correctly

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#10526]
### Description

I've found that Startup settings, Date format and Open items with single click are set to default when I import my settings

### Steps To Reproduce

1. Toggle one of the settings in description
2. Export settings
3. Change settings back
4. Import settings

### Steps to fix

1. Include these options in the export/import

### Files Version

2.3.61.0

### Windows Version

10.0.22621.875

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10050813/debug.log)

**Comment by hecksmosis** [comment]
I think startup settings and open files with single click do import correctly

**Comment by Josh-65** [comment]
You're on stable. This issue is from the preview versions.

**Comment by QuaintMako** [comment]
@Josh-65 it seems to be working as intended for me in 2.4.3 Dev Version.

Can you still reproduce it?

**Comment by Josh-65** [comment]
Nope
