### ISSUE TITLE
Bug: 7z archives aren't displaying sub items correctly

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#10527]
### Description

When I open a 7z archive it shows folder as blank files and they cannot be opened. Clicking and right click menu do nothing
![image](https://user-images.githubusercontent.com/26977075/203031145-9a0a28e0-97b7-4c2f-b725-3377563399a7.png)

### Steps To Reproduce

1. Create 7z archive with folders in
2. Open archive
3. See folder are shown as files and cannot be clicked

### Files Version

2.3.61.0

### Windows Version

10.0.22621.875

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10050826/debug.log)

**Comment by Josh-65** [comment]
There supposed to be folders

**Comment by gave92** [comment]
Fixed by #10563.
