### ISSUE TITLE
Bug: Option to set default file manager doesn't copy launcher program

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#10521]
**Steps to reproduce**
1. Open settings dialog
2. Navigate to experimental
3. Toggle option to make Files default
4. Close app and try the `win` + `e` shortcut and see error message

**Steps to fix**
- Bundle launcher exe with the app and copy to the correct location when making Files the default

**Comment by verdaderoken** [comment]
This is the same as #10381, right?

**Comment by yaira2** [comment]
Yes
