### ISSUE TITLE
Bug: wrong Folder Icons

### ISSUE THREAD

**Issue by xIUPITERx** [files-community/Files#10536]
### Description

Folders in the details layout aren't displayed correctly.
The special ones (pictures, documents, music, ...) are low quality and the normal ones are only displayed at third of their original size.

![image](https://user-images.githubusercontent.com/97352673/203155876-d35c3489-5c95-4536-a839-c313f3b29877.png)

![image](https://user-images.githubusercontent.com/97352673/203156909-dfe6213e-5c1e-4549-b5d7-a971ebcdddd3.png)

### Steps To Reproduce

for the glitch
1. The layout has to be details
2. Switch between details and symbols and you see the icon popping in

low quality icons
1. The layout has to be details
2. the picture music etc folders aren't sharp

### Steps to fix

- normal folders should be displayed at the correct size
- use sharper, high quality icons for the special folders

### Files Version

Version: 2.3.12.0 OS Version: 10.0.22621.819

### Windows Version

Windows 11 Pro 22H2 22621.819

### Relevant Assets/Logs

https://user-images.githubusercontent.com/97352673/203155638-8e46d93a-01de-4d96-8db9-6c5a0860700c.mp4

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by xIUPITERx** [comment]
They seems to be fixed, 
but in the preview version is also a similar bug that affects the folder icons

> ![image](https://user-images.githubusercontent.com/97352673/203746339-ea90f23a-182a-41f6-959b-e59d4b9c6fc4.png)
> These Icons should be used

> ![image](https://user-images.githubusercontent.com/97352673/203745088-b634857c-eb32-4bf5-a3e7-50da401e3bbd.png)
> But these Icons are used
