### ISSUE TITLE
Cant open ZIP Folder

### ISSUE THREAD

**Issue by xIUPITERx** [files-community/Files#10533]
### Description

Files can't open ZIP Folders, if it's not an bug I would ask to implement it as an feature.

### Steps To Reproduce

try to open a ZIP Folder with the files app.
2. Error message appears.

### Steps to fix

-Files should be able to handle ZIP folders corretly.

### Files Version

Version: 2.3.12.0 OS Version: 10.0.22621.819

### Windows Version

Windows 11 pro 22H2 22621.819

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/97352673/203146263-8b4e9eac-5268-4d5c-bb99-ec992952bbce.png)

**Comment by Josh-65** [comment]
Can you see if this is an issue in the preview version? https://files.community/download/preview

**Comment by xIUPITERx** [comment]
In the preview version it works just fine.

**Comment by xIUPITERx** [comment]
it would be cool if you could open the unzipped folder via the status menu once it is ready.
