### ISSUE TITLE
allow for nested side bar navigation

### ISSUE THREAD

**Issue by lenadm** [files-community/Files#10538]
### What feature or improvement do you think would benefit Files?

Hi as a user of explorer++ i got incredibly used to navigating through the use of the nested side bar. 
![nyyVrYmULY](https://user-images.githubusercontent.com/118849312/203402991-5a2bc8ff-71f3-4638-a431-589360575c9c.png)
the lack of this feature in files made it incredibly difficult to adapt to a new workflow and even then i cant help but feel i lost a little bit of functionality. As such i would love to see this feature implemented into files.

### Requirements

make it like explorer++ but nicer to use and look at

### Files Version

2.3.12.0

### Windows Version

windows 10 home 22h2

**Comment by Josh-65** [comment]
Merging with #1928

**Comment by yair100** [comment]
@breandead Tree View is currently available in preview https://files.community/download. It will be included in the next stable release.
