### ISSUE TITLE
folders don´t retain tags

### ISSUE THREAD

**Issue by Newguru-1** [files-community/Files#10539]
### Description

After setting a tag on a folder, the tag is removed from the folder, moments later.

### Steps To Reproduce

1. right click on a folder to set a tag
2. select the tag filter
3. reselect the folder
4. the tag disappear from the folder and the tag filter is blank

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

Files (Preview) version 2.3.61.0

### Windows Version

Windows 11 Version 22H2 (0S Build 22621.819)

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10071277/debug.log)

**Comment by Josh-65** [comment]
Where are the folder you are putting the tags on

**Comment by Newguru-1** [comment]
On my Onedrive. I have all my folders synced there.

 

De: Josh-65 ***@***.***> 
Enviada: 22 de novembro de 2022 21:51
Para: files-community/Files ***@***.***>
Cc: Newguru-1 ***@***.***>; Author ***@***.***>
Assunto: Re: [files-community/Files] folders don´t retain tags (Issue #10539)

 

Where are the folder you are putting the tags on

**Comment by Josh-65** [comment]
It likely an issue with OneDrive not supporting the use of ADS files which are used for tags. If you turn off the sync program and set it do they stay?

**Comment by Newguru-1** [comment]
No. 

I paused the Onedrive sync, and the issue maintains.

I did try with a smaller folder, also on Onedrive and with the sync engine enabled, and the tag stayed on.

 

I think the issue has to do with the folder size.

I was trying with a massive main folder (my photos library) which is 331 Gb in size, and the tag doesn’t stay on.

Do you have a size limit in place?

 

 

De: Josh-65 ***@***.***> 
Enviada: 22 de novembro de 2022 21:55
Para: files-community/Files ***@***.***>
Cc: Newguru-1 ***@***.***>; Author ***@***.***>
Assunto: Re: [files-community/Files] folders don´t retain tags (Issue #10539)

 

It likely an issue with OneDrive not supporting the use of ADS files which are used for tags. If you turn off the sync program and set it do they stay?

**Comment by xIUPITERx** [comment]
OneDrive is not the problem, I use tags without any issues.

**Comment by Newguru-1** [comment]
Has the issue been identified? Do you need more info on my part?

Thanks

**Comment by Josh-65** [comment]
Not right now, a dev may need more info when they try to fix it.

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by Newguru-1** [comment]
No. It's fixed. Tanks

Os meus cumprimentos,

Pedro Matos
________________________________
