### ISSUE TITLE
Bug: Original path and date deleted column sizes aren't saved

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#10535]
### Description

When I open recycle bin and then edit the column sizes then exit and go back it reset to original width

### Steps To Reproduce

1. Go to recycle bin
2. Edit original path or date deleted column size
3. Go to home page
4. Go back to recycle bin
5. See column sizes reset

### Steps to fix

?

### Files Version

2.3.61.0

### Windows Version

10.0.22621.875

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10060287/debug.log)

**Comment by itayweb** [comment]
Tried to reproduce but the size stays the way I set it and didn't reset and got the same Files version

**Comment by gave92** [comment]
I think it only happens if you disable "Enable individual preferences for individual directories" option in settings. @Josh-65 could you check?

**Comment by Josh-65** [comment]
Yep only when its off
