### ISSUE TITLE
Auto minimize sidebar 

### ISSUE THREAD

**Issue by xIUPITERx** [files-community/Files#10534]
### What feature or improvement do you think would benefit Files?

I would like to see a button that minimises the sidebar without having to drag it with the mouse, so that I can quickly switch between normal and narrow.  In addition, the sidebar should be minimised automatically when the File App window only takes up half of the screen (on-off toggle in the settings).
![Screenshot 2022-11-20 200211](https://user-images.githubusercontent.com/97352673/203148419-ff5328b5-80a2-4334-a4c9-9c42f2462d79.png)

### Requirements

Thanks to the new snap function, you can rearrange windows very quickly. So it would be nice if you didn't have to adjust the page layout every time you moved a window in order to have enough space to work.

### Files Version

Version: 2.3.12.0 OS Version: 10.0.22621.819

### Windows Version

Windows 11 Pro 22H2 22621.819

### Comments

Normal sidebar
![image](https://user-images.githubusercontent.com/97352673/203149924-8aea3421-246e-4e2d-92e0-22f457d0fad0.png)

Minimized sidebar 
![image](https://user-images.githubusercontent.com/97352673/203150060-5ec531b4-0811-4694-a5ee-b95fdb5a5cf9.png)

**Comment by yaira2** [comment]
You can double click the grid splitter to expand/collapse the sidebar
