### ISSUE TITLE
Bug: Files freezes when deleting a folder that has an open file

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#10530]
### Description

Sometime Files will crash but the windows will just be frozen and have to be killed from task manager. I've only had this when deleting folders with no specific area.

### Steps To Reproduce

1. Open file in folder
2. Delete the folder
3. Files will freeze but not closed

### Steps to fix

1. Display error message with name of the open item instead of freezing

### Files Version

2.3.61.0

### Windows Version

10.0.22621.875

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10050903/debug.log)

**Comment by yaira2** [comment]
Is this when deleting a specific kind folder (eg. empty folders)?

**Comment by Josh-65** [comment]
Seems to be when there's a file in the folder beeing used
