### ISSUE TITLE
Themes disappeared from the app

### ISSUE THREAD

**Issue by vfransant** [files-community/Files#10542]
### Description

Hello!

I'm not sure if this is the place to talk about this, so if it isn't I'm sorry

I really like the Files, I've been using it for some time and it is awesome. But somedays ago, it went back to default theme and when I went to the settings to change the theme they aren't there. I tried to see in the folder if there is any but there isn't. I tried to uninstall Files and install again, but no success with the themes issue.

Is there any way I can download them sepparetedly, or is there something I can do about it?

Thank you and keep the good work!

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/68281581/203450203-40991977-a7e7-43eb-b678-19543e207d78.png)
(It is in portuguese, but as you can see there is only the default theme and I didn't remove them from the folder)

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

2.3.12.0

### Windows Version

Windows 11 22H2 22621.819

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/68281581/203450457-df960df8-b7ea-42de-97cf-f605213bd829.png)

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by vfransant** [comment]
> Is this still an issue in the preview version? https://files.community/download/preview

No, I installed it and all the themes appeared in the preview version
