### ISSUE TITLE
Crash when clicking outside window after closing properties dialogue

### ISSUE THREAD

**Issue by Tamnac** [files-community/Files#10546]
### Description

A crash when following this specific sequence below.

### Steps To Reproduce

1. Select a folder
2. Click properties icon
3. Click in the properties dialogue to move focus there
4. Press cancel on the properties dialogue 
5. Click on something outside the files window 
6. Crash

### Steps to fix

- Fix crash

### Files Version

Version: 2.3.12.0 OS Version: 10.0.19045.2251

### Windows Version

10.0.19045

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10079872/debug.log)

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by Tamnac** [comment]
@yair100 ok I downloaded it and checked - and no, no longer an issue.
