### ISSUE TITLE
Feature: Allow changing display format for the file size

### ISSUE THREAD

**Issue by Leopold702** [files-community/Files#10545]
### What feature or improvement do you think would benefit Files?

Currently, file size units are dynamically adjusted based on the file size. While this should be just fine (or even preferable) for most people, some (myself included) may prefer to see different units (e.g. kilobytes like in Windows Explorer, or even raw bytes). 

Also, having unified file size units makes it easier to gauge the size of files in a folder at a quick glance, see the example below:

![files](https://user-images.githubusercontent.com/64221830/203852658-7a0378e5-7b13-4112-859a-956f0b972435.png)

![explorer](https://user-images.githubusercontent.com/64221830/203852668-c2e93468-a4ea-44b0-8012-7f08985baf68.png)

So it would be nice if Files had the option to choose the preferable units.

Also on the same note, it would be nice if Files could address the whole kilobytes/kibibytes situation, for example:

- By showing proper abbreviation for the binary units (KiB instead of KB, MiB instead of MB, GiB instead of GB, etc), Dolphin style.
- By allowing to switch to the decimal units as advised by SI (i.e. KB that equals 1000 bytes, etc), macOS style.

### Requirements

- Will allow users to see more precise file sizes, which in many cases adds additional context to the file
- Will give more flexibility in terms of the file size units usage

### Files Version

Version: 2.3.12.0 OS Version: 10.0.19045.2251

### Windows Version

Windows 10 Pro 22H2 19045.2251

**Comment by yaira2** [comment]
Which formats would you like to see supported?
