### ISSUE TITLE
[HELP] how do i repair the win + e keyboard shortcut now?

### ISSUE THREAD

**Issue by fislysandi** [files-community/Files#10544]
i clicked the switch for the replacing default file explorer and after using files a little i did not like it so i unchecked the win + e explorer hook and i get this 
![explorer_Apey4YFnZM](https://user-images.githubusercontent.com/45166203/203609911-33ee94f1-39e1-439a-ad5a-9dc71cd63a06.png)

the main file explorer works just fine fine 
![explorer_iyypNJ4lNM](https://user-images.githubusercontent.com/45166203/203610757-7eaabb8e-6b03-4d56-bf51-e6bd0f59f940.png)
but im wondering what do i do now to repair the shortcut? 

even using my backed up registry it didnt repair it but it told me that it couldnt restore it fully.

please see the code for how [tablacus](https://github.com/tablacus/TablacusExplorer) does this explorer hook without bricking the shortcut as a note to the future.

but anyone just please tell me how to undo what files has done to win + e

**Comment by Josh-65** [comment]
You can turn the toggle off at Files settings > experimental > set as default

If you have uninstalled Files or the above doesn't work open this https://raw.githubusercontent.com/files-community/Files/main/src/Files.App/Assets/FilesOpenDialog/UnsetFilesAsDefault.reg > right click on the opened page > Save as > set the type to "all files" > remove the .txt from the end of the name > open the file > allow admin when you get the prompt.

**Comment by fislysandi** [comment]
😡

**Comment by Josh-65** [comment]
There is already a new method for the next stable update that won't cause that issue

**Comment by fislysandi** [comment]
I TURNED OFF THE CHECK MARK AND I STILL DONT HAVE THE DEFAULT FILE EXPLORER

**Comment by Josh-65** [comment]
Then do the second method

**Comment by fislysandi** [comment]
uhh lemme try then.

**Comment by fislysandi** [comment]
YAY

**Comment by fislysandi** [comment]
sorry for bothering you
