### ISSUE TITLE
Bug: Search non-indexed objects" not centered 

### ISSUE THREAD

**Issue by xIUPITERx** [files-community/Files#10549]
### Description

When you open a tag folder, this message appears at the bottom of the field:

  ``Not found what you are looking for?``
  ``Search non-indexed objects``

But it's not centred and in the most usecases redundant.
It would be usefull to hide it.

### Steps To Reproduce

1. Go to an tag folder
2. open it
3. scroll down

### Steps to fix

- centre the message or hide it completly

### Files Version

Version: 2.3.61.0 OS Version: 10.0.22621.819

### Windows Version

Windows 11 Pro 22H2 22621.819

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/97352673/203743662-188f77e7-6ce3-42f5-918d-1ddda7e72ed9.png)

**Comment by rahulhumie** [comment]
i want to work in the issue please assign me

**Comment by Josh-65** [comment]
This is already being worked on see the attached pull request
