### ISSUE TITLE
Add more file conflict options

### ISSUE THREAD

**Issue by SimonL888** [files-community/Files#10553]
### What feature or improvement do you think would benefit Files?

please allow more option when conflicting files occur:
- add a "integrate option" for folders if the folder to be pasted exists (like windows explorer)
- add "date comparison" option if files already exists to choose which one to keep (with option to keep booth)
- add option to compare other file details

### Requirements

- adding above mentioned features

### Files Version

Version: 2.3.12.0 OS Version: 10.0.22000.1281

### Windows Version

Windows 11

**Comment by Josh-65** [comment]
Folder are already merged when it already exists

**Comment by Leopold702** [comment]
It would also be nice if the Windows 7 style option to keep both file versions of the same name without comparing them first was added.

**Comment by yaira2** [comment]
Merging with #9803
