### ISSUE TITLE
The context menu items are not being pulled when right clicking a file

### ISSUE THREAD

**Issue by Duckloveshack** [files-community/Files#10558]
### Description

The Windows 10 context menu items are not shown in Files, although there are additional items created by 3rd party apps. Weirdly enough, it only happens when right clicking files or folders (most likely an issue with my context menu, although i can't specifically point out any issues

### Steps To Reproduce

1.Right click any file

### Steps to fix

* Skip past problematic sections in the context menu perhaps

### Files Version

Version: 2.3.12.0 OS Version: 10.0.22623.891

### Windows Version

Windows 11 22H2 22623.891

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10086907/debug.log)

![Windows 10 context menu](https://user-images.githubusercontent.com/54633619/203852159-facfb5fe-c478-42d3-9f3a-3d6f3ee8594e.png)
Legacy context menu from explorer (right clicking a file)

![Files context menu](https://user-images.githubusercontent.com/54633619/203852196-421d0cab-ddd0-4b51-b401-b5cd540243f6.png)
The Files context menu (right clicking a file)

![Files context menu 2](https://user-images.githubusercontent.com/54633619/203852496-179ab83e-d66c-47b2-a992-443a971c598c.png)
The context menu in Files (no folders or files selected)

**Comment by Josh-65** [comment]
Can you see if this is an issue in the preview version? https://files.community/download/preview

**Comment by Duckloveshack** [comment]
Nope, it's not an issue with the preview version, although i have to check if maybe deleting my normal files profile may fix it
