### ISSUE TITLE
File name issue

### ISSUE THREAD

**Issue by newyork2003** [files-community/Files#10556]
### Description

At my download folder I get the full file name in the small icon mode. As seen here:
![Files_RGRy9YqTtZ](https://user-images.githubusercontent.com/118293214/203840684-c8c5baea-c931-459f-a96a-3909e09490fb.png)

But in all my other folders its shorted with a (...). While still using the small icon mode. As seen here:
![Files_Xh92XcSEUo](https://user-images.githubusercontent.com/118293214/203840753-6e65217f-dc23-4092-946b-6164457c3e50.png)

### Steps To Reproduce

--

### Steps to fix

-fix filenames issues

### Files Version

Version: 2.3.61.0 OS Version: 10.0.19044.2251

### Windows Version

Windows 10 Pro Version	21H2 Installed on	‎25/‎08/‎2022 OS build	19044.2251 Experience	Windows Feature Experience Pack 120.2212.4180.0

### Relevant Assets/Logs

----

**Comment by Josh-65** [comment]
Merging with #1033
