### ISSUE TITLE
Hover over OneDrive shows wrong drive infos

### ISSUE THREAD

**Issue by xIUPITERx** [files-community/Files#10552]
### Description

If you hover over OneDrive, it will show you the infos from drive C.

### Steps To Reproduce

1. Hover over the drive C
2. Hover over OneDrive
3. The infos (except the name) will be the same

### Steps to fix

show the correct Onedrive information if you hover over th folder

### Files Version

Version: 2.3.61.0 OS Version: 10.0.22621.819

### Windows Version

Windows 11 Pro 22H2 22621.819

### Relevant Assets/Logs

https://user-images.githubusercontent.com/97352673/203774366-538ee740-cc63-42eb-bcc7-1cc134470339.mp4

**Comment by yaira2** [comment]
Merging with #10001
