### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by newyork2003** [files-community/Files#10555]
### Description

The search bat at https://files.community/docs is not working

### Steps To Reproduce

1- go here https://files.community/docs
2- try to type something in the search bar
3- it always says that it cant find what you are seraching for

### Steps to fix

-fix the search at https://files.community/docs

### Files Version

chrome  107.0.5304.107 (Official Build) (64-bit)

### Windows Version

Windows 10 Pro Version	21H2 Installed on	‎25/‎08/‎2022 OS build	19044.2251 Experience	Windows Feature Experience Pack 120.2212.4180.0

### Relevant Assets/Logs

-----

**Comment by Josh-65** [comment]
Website issues go here https://github.com/files-community/Website

**Comment by newyork2003** [comment]
The link to report issues in the website is not working
https://github.com/files-community/Website/blob/main/issues

**Comment by Josh-65** [comment]
Dont type the URL in. Click on the link I sent then go to issue > new issue > bug report
