### ISSUE TITLE
Hide specific or empty drives

### ISSUE THREAD

**Issue by xIUPITERx** [files-community/Files#10550]
### What feature or improvement do you think would benefit Files?

1. Have an option to hide all empty drives (like an empty optical drive)
2. Have an option to hide specific drives (e.g. with very important data or drives that you do not have permission to open.)

### Requirements

- It would look cleaner 
- It would save space
- It makes the use safer

### Files Version

Version: 2.3.61.0 OS Version: 10.0.22621.819

### Windows Version

Windows 11 Pro 22H2 22621.819

**Comment by yaira2** [comment]
Merging with #9170

**Comment by xIUPITERx** [comment]
But that is not the same feature request

**Comment by yaira2** [comment]
> But that is not the same feature request

Can you elaborate?

**Comment by xIUPITERx** [comment]
In the feature request you mentioned, the drives (only empty ones) should be hidden in the sidebar.
I want to hide them everythere in the app, because i have no permissions even to see if the drives are empty.

**Comment by xIUPITERx** [comment]
The "hover over the drive to see Information"- feature wouldn't even work for the drives I mentioned.

**Comment by yaira2** [comment]
You can right click on the drives section and click the option to hide it

**Comment by xIUPITERx** [comment]
But I only want to hide the hard drives that I can't use, that would be 3 out of 6, not all of them.
