### ISSUE TITLE
Auto jump to the displayed folder when open explorer in application 

### ISSUE THREAD

**Issue by yangyhua** [files-community/Files#10557]
### What feature or improvement do you think would benefit Files?

When I open the explorer windows in the application, I want the feature the explorer windows in application can auto-jump to the path where the **Files** display. 
attached is using **Listary**:
![image](https://user-images.githubusercontent.com/29419816/203843638-2c6e0375-36f7-4786-97da-e3c89ceb466b.png)

### Requirements

Sry, I don't know how to achieve this feature.
Maybe should change the application default explorer to **Files** first?
Then, achieve by **Files** 

### Files Version

Version: 2.3.12.0 OS Version: 10.0.19044.2251

### Windows Version

Windows 10 IoT Enterprise LTSC 21H2 19044.2251

**Comment by Josh-65** [comment]
Save/open dialog aren't controllable by Files. #6314
