### ISSUE TITLE
Crashes when moving .png file.

### ISSUE THREAD

**Issue by Cilde** [files-community/Files#10559]
### Description

Crashed upon the movement of a .png file, reason still unknown.

### Steps To Reproduce

Unknown how to reproduce.

Dragged image and it crashed.

### Steps to fix

Restart.

### Files Version

V2.3.12.0

### Windows Version

Windows 11 Home 22H2 22621.819

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10087107/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/10087108/debug_fulltrust.log)

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
