### ISSUE TITLE
Clicking on the "Open log location" option in settings menu doesn't go to the folder in which logs are stored even on the latest preview version

### ISSUE THREAD

**Issue by ElitePheonix2009** [files-community/Files#10569]
### Description

I am going to settings, clicking on the about section and then clicking on the option "Open log location" doesn't open the folder in which logs for this app is stored. 
**Note: 1. I am using the preview version. 2. It is not giving me the option to reopen the issue, so I am opening a new issue.**

### Steps To Reproduce

1. Click on the settings option (the gear icon).
2. Click on the about section.
3. Click on "Open log location" option.
4. See that the folder where the logs are stored doesn't open.

https://user-images.githubusercontent.com/114980232/204078034-160e2890-4bed-402f-81ef-6747b2a6d524.mp4

### Steps to fix

Make sure that when we clicking on the option "Open log location" the folder where logs are stored is open.

### Files Version

Version: 2.3.61.0 OS Version: 10.0.19045.2251

### Windows Version

Edition	Windows 10 Pro Version	22H2 Installed on	‎15-‎09-‎2022 OS build	19045.2251 Experience	Windows Feature Experience Pack 120.2212.4180.0

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/10095856/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/10095858/debug.log)

**Comment by Josh-65** [comment]
Turn off the set as default option if you have it on. then try it

**Comment by ElitePheonix2009** [comment]
> Turn off the set as default option, if its already off turn it on then off again. then try it.

This works

**Comment by Josh-65** [comment]
Great a fix for this is being tracked in #10521
