### ISSUE TITLE
Add new folders on a network drive added 3 times

### ISSUE THREAD

**Issue by spssoftie** [files-community/Files#10566]
### Description

Example:

X:\Folder1\Folder2\Folder3\
If this folder contains files and a new Folder (i.e. "test") are added then folders created 3 times.
test
test (2)
test (3)
![Added_Folders_2022-11-25_084450](https://user-images.githubusercontent.com/37895827/203927950-e99e6028-3b17-4c7c-9a7f-8e5d7e269e6c.png)

Sometimes it happens on X:\Folder1\ too.

### Steps To Reproduce

1. Select a mapped network path
2. Use "New" -> "Folder" from menu above
3. Give folder name
4. Click on "Set Name"

![Menu_2022-11-25_084757](https://user-images.githubusercontent.com/37895827/203928768-95b3b01c-95fa-40d1-a5b6-b85d695b13ca.png)

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

Version 2.3.12.0

### Windows Version

Windows 10 22H2 OS build 19045.2251

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10089653/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/10089654/debug_fulltrust.log)

**Comment by gave92** [comment]
#9628
