### ISSUE TITLE
Bug: Alt-up focuses on the tab

### ISSUE THREAD

**Issue by chtenb** [files-community/Files#10567]
### Description

When I press `Alt - arrow up`, files does not move up a folder, but instead focuses the tab header:

![image](https://user-images.githubusercontent.com/1030961/203948348-9d68e802-8153-48da-a39b-b2cfd59fd428.png)

The tooltip of the move-up button indicates that it should work however:

![image](https://user-images.githubusercontent.com/1030961/203948484-7c75583b-6338-4bbf-90e4-c56841d3cc35.png)

### Steps To Reproduce

It reproduces always on any folder for me.

### Steps to fix

- Navigate correctly 

### Files Version

Version: 2.3.12.0 OS Version: 10.0.22621.819

### Windows Version

Windows 11 Business Version	22H2 OS build	22621.819 

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10090459/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/10090460/debug_fulltrust.log)

**Comment by ElitePheonix2009** [comment]
Same issue

**Comment by itayweb** [comment]
I don't know if that was intended but it works when you press again ALT+Up arrow, I mean the first time it's indeed select the folder header but when press again it does go up

**Comment by ElitePheonix2009** [comment]
> I don't know if that was intended but it works when you press again ALT+Up arrow, I mean the first time it's indeed select the folder header but when press again it does go up

I have tried it but it does not work even when pressing again.

**Comment by ElitePheonix2009** [comment]
> I don't know if that was intended but it works when you press again ALT+Up arrow, I mean the first time it's indeed select the folder header but when press again it does go up

Yes, this works

**Comment by verdaderoken** [comment]
Another shortcut for this is `Alt+U` but yeah, `Alt+Up` could've been the default since Explorer (with Tabs) is also using Alt+Up for up folder

**Comment by yaira2** [comment]
It seems to work if you use the shortcut a second time, we'll have to investigate why it selects the tab the first time you use the shortcut.

**Comment by JacomeBomfim** [comment]
Same issue here. It works only when do the shortcut a second time right after the first try.
