### ISSUE TITLE
Good file manager!

### ISSUE THREAD

**Issue by symmetrysorrow** [files-community/Files#10565]
Thanks for a good file manager! I like it for the tags function because it's useful and help me managae files that are in multiple drives. 

 I'd like you to let me "move" files when dragging files through tabs. Copying files and deleting original files take time.

I'm using preview version 2.3.61.0 and there is a bit of lag when overflow context menu is shown. Also, I can't set this as the default file manager.

**Comment by gave92** [comment]
Try draghing while keeping Control or Shift key pressed. It should move the files.
