### ISSUE TITLE
[Feature Request] Tag rename and add new tags

### ISSUE THREAD

**Issue by TheMrBakit** [files-community/Files#10568]
### What feature or improvement do you think would benefit Files?

Hi there my idea is simple I'd like to have more tags and be able to rename them as needed so it

### Requirements

- This proposal will accomplish. It would allow us to click on a named take "Backup", "Save game" and more...
- This proposal will accomplish. being able to add more tags and chose some colours

### Files Version

Version : 2.3.12.0 OS Version: 10.0.22621.819

### Windows Version

Windows 11 Professionnel Version	22H2

### Comments

The option could be added with a right click on the "tags" tab in the lateral menu on the left

**Comment by Josh-65** [comment]
Merging with #9588

You can go to Files settings > experimental > edit tag and change the name there right now

**Comment by TheMrBakit** [comment]
Thanks for the redirection
