### ISSUE TITLE
hi is possible when you move a folder andfinds one with the same name to jut ask if youwant to replace it and not just create a enw one ?

### ISSUE THREAD

**Issue by angaratosurion** [files-community/Files#10576]
### What feature or improvement do you think would benefit Files?

hi is possible when you move a folder andfinds one with the same name to jut ask if youwant to replace it and not just create a enw one ?

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z
this will accopm;ise to nto have duplicate fodlers

### Files Version

Έκδοση: 2.3.12.0 OS Version: 10.0.22000.1281

### Windows Version

Windows 11 Pro 21H2

**Comment by Josh-65** [comment]
Files already does ask. It may work better in the preview version https://files.community/download/preview
