### ISSUE TITLE
UI scale

### ISSUE THREAD

**Issue by Yumileashen** [files-community/Files#10578]
### What feature or improvement do you think would benefit Files?

would be greaat if folder can look smaller or bigger

### Requirements

-scaling down or up the ui

### Files Version

Version: 2.3.12.0 OS Version: 10.0.19044.2251

### Windows Version

Windows 10 Pro Version	21H2 OS Build I19044.2251 Windows Feature Experience Pack 120.2212.4180.0

**Comment by yaira2** [comment]
The UI can be scaled up/down using the built-in option in Windows.

**Comment by Yumileashen** [comment]
where is it?
![image](https://user-images.githubusercontent.com/68269846/204120385-5b76ce12-828e-44c5-bb29-9af4707acfae.png)
this one?

**Comment by Josh-65** [comment]
Windows settings > System > Display > Scale

**Comment by Yumileashen** [comment]
oh sorry
thats the entire windows 
but I mean just for the app

**Comment by yaira2** [comment]
Which layout are you using?

**Comment by yaira2** [comment]
We don't have plans to implement a built-in option as this is already supported system wide, however, you can use the compact spacing option to reduce the item height in the details layout.
