### ISSUE TITLE
No Quick Access?

### ISSUE THREAD

**Issue by Zrrg** [files-community/Files#10584]
### What feature or improvement do you think would benefit Files?

I was using it extencevely, pinning most used folders as in Favourites. Surprised its not featured.

### Requirements

 Just as in Windows Explorer at least. I have lots of pins, probably it should be Favourites, maybe I can move them?

### Files Version

Version: 2.3.12.0 

### Windows Version

OS Version: 10.0.19042.1526

**Comment by yaira2** [comment]
You can right click folders to pin them to the favorites section, we don't have a way to import pinned folders from File Explorer but it's something we're looking at.
