### ISSUE TITLE
Details Layout: "Size all columns to fit" don't work, the size doesn't remain, and I can't sort the columns.

### ISSUE THREAD

**Issue by brockar** [files-community/Files#10580]
### Description

1. In Details Layout the option to size all columns to fit doesn't work. It just doesn't anything. Especially in online folders, the status of the file (online or offline) remains out of view.
2. Also in Details Layout, when I change the width of the columns, I change the folder, and they return to default. I tried to set "Set as default" but the same thing still happens.
3. I cannot move the order of the columns.

### Steps To Reproduce

1. Open a folder.
2. Select Details layout.

3-1, Right-click on the columns and click on Size all columns to fit.

https://user-images.githubusercontent.com/55927935/204120911-a2807660-2a45-4977-8f40-0407467a754d.mp4

3-2, Change the width of the columns, change folder and re-enter the previous one. The columns will return to the same size as at the beginning.

https://user-images.githubusercontent.com/55927935/204120915-f47264a2-17b0-4f2e-9183-781c1caadd9c.mp4

3-3. Just hold the click on a column and try to move it.

https://user-images.githubusercontent.com/55927935/204120932-44b2d66c-03f0-4dab-9bd5-b124d5e697e8.mp4

### Steps to fix

-

### Files Version

Version: 2.3.12.0 OS Version: 10.0.22000.1219

### Windows Version

Windows 11 Pro, 21H2, 22000.1219, Windows Feature Experience Pack 1000.22000.1219.0

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/10097603/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/10097604/debug.log)

**Comment by Josh-65** [comment]
This is fixed in the preview builds. https://files.community/download/preview
