### ISSUE TITLE
Allow typing in the extract here path

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#10588]
### What feature or improvement do you think would benefit Files?

I can only browse and not type in the text box for extract location
![image](https://user-images.githubusercontent.com/26977075/204151781-8dc7eb6d-c7a7-4931-9c9b-37e6c5d59916.png)

### Requirements

- Allow typing in the text box

### Files Version

2.3.63

### Windows Version

10.0.22621.875

**Comment by yaira2** [comment]
This is by design, prevents the need to validate the location and to display errors when it isn't valid.

**Comment by cinqmilleans** [comment]
@yair100 We should open the path selection browser when we click on the path.

**Comment by yaira2** [comment]
That would be confusing, the browse button already takes care of that.
