### ISSUE TITLE
can not change the open method of certain file

### ISSUE THREAD

**Issue by Gryffindor2** [files-community/Files#10581]
### Description

can not open the choosing opening method dialog.

### Steps To Reproduce

Right click on a file, click open file, then the choosing opening method dialog won't appear.

### Steps to fix

only in older windows this function can run normally.

### Files Version

版本: 2.3.12.0 OS Version: 10.0.25247.1000

### Windows Version

Windows 11 Insider Preview Build 25247

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10097748/debug.log)

**Comment by Josh-65** [comment]
Can you see if this is an issue in the preview version? https://files.community/download/preview

**Comment by Gryffindor2** [comment]
I tried the preview version, this problem is solved. Thank you!!
