### ISSUE TITLE
Bug: Theme is not applied on launch

### ISSUE THREAD

**Issue by verdaderoken** [files-community/Files#10586]
### Description

When using themes in Files, the theme is not applied on some app launches. Sometimes it would lose the theme after you close the app and open it again.

I had to hit Alt+I to open Settings and it automatically reloads the theme I set.

### Steps To Reproduce

1. Set a custom theme like Bronze or Green Grass or any theme that is noticeably different from the Default theme.
![image](https://user-images.githubusercontent.com/88200096/204148911-43b9f729-aec2-498c-a716-64ad0a7bbabf.png)

2. Close the app
3. Open the app again and it's back to the default theme. (If the theme is retained, close and open again a few more times)
![image](https://user-images.githubusercontent.com/88200096/204148920-c36710d3-0445-494f-826e-aa6e1dbab650.png)
Sometimes it would retain its theme but most of the time it doesn't.

My workaround for this is to hit Alt+I and the theme will refresh.

### Steps to fix

- Load the theme properly when launching the app

### Files Version

2.3.63

### Windows Version

10.0.22623.885

### Relevant Assets/Logs

None

**Comment by verdaderoken** [comment]
**Mica Imitation** theme would look like this 
![image](https://user-images.githubusercontent.com/88200096/204149072-749f01d4-7b04-4361-a310-2264eb42aa07.png)
 vs what it should look like:
![image](https://user-images.githubusercontent.com/88200096/204149058-91e0300f-26d3-4dbc-b819-01728441eba9.png)

**Comment by yaira2** [comment]
Merging with #10342
