### ISSUE TITLE
创建文件夹的逻辑错误

### ISSUE THREAD

**Issue by ai30328348** [files-community/Files#10582]
### Description

逻辑错误
创建带有中文的文件夹会自动屏蔽中文，或设置名称按钮 为不可用状态
创建全中文文件夹需要输入数字或字母进行欺骗，并删除字母或数字才能创建中文名称的文件夹
软件反应速度也不是很理想，和win11的资源管理器一样卡顿

### Steps To Reproduce

1.点击新建->文件夹
2.输入中文(设置名称按钮，为不可以状态）
3.在中文基础上输入数字或字母后，去掉数字或字母
4.点击设置名称按钮
5.成功创建了文件夹

1.点击新建->文件夹
2.输入中文加英文或字母
3.点击设置名称按钮
4.发现中文被去掉了

### Steps to fix

正常运行，无法修复，属于逻辑错误

### Files Version

版本: 2.3.12.0 OS Version: 10.0.22621.819

### Windows Version

Windows Feature Experience Pack 1000.22636.1000.0

### Relevant Assets/Logs

逻辑错误，无相关日志

**Comment by Josh-65** [comment]
Merging with #9563
