### ISSUE TITLE
Bad keyboard navigation in Details view

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#10591]
### Description

In the Details view, opening a new folder gives focus to the column headings. So you can't easily use keyboard navigation in the new folder.

### Steps To Reproduce

1. Use the Details view.
2. Open a folder with the keyboard (key enter).
3. The focus is on the header (Name).

### Steps to fix

In the Details view, give focus to the first item when opening a folder.

### Files Version

Version: 2.3.57.0 OS Version: 10.0.22621.819

### Windows Version

Windows 11 22621.674

### Relevant Assets/Logs

https://user-images.githubusercontent.com/46631671/204158777-105cfb19-499f-4646-9804-fb81af094714.mp4

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by cinqmilleans** [comment]
I have the problem in the preview, but not anymore in the updated dev version. So it seems corrected.
