### ISSUE TITLE
404

### ISSUE THREAD

**Issue by livingflore** [files-community/Files#10599]
### Description

"Support us" button in Settings > About goes to https://github.com/sponsors/yaichenbaum, which is 404

### Steps To Reproduce

![ApplicationFrameHost_4JIjqa618r](https://user-images.githubusercontent.com/63370734/204464824-7e3b10f2-3a8c-4ba7-b464-2fc609365b2e.gif)

### Steps to fix

replace https://github.com/sponsors/yaichenbaum to patreon/kofi/whatever url

### Files Version

Version: 2.3.12.0 OS Version: 10.0.19044.1766

### Windows Version

10 21H2 19044.1766

### Relevant Assets/Logs

no?

**Comment by Josh-65** [comment]
This has already been fixed and will be available next update
