### ISSUE TITLE
Bug: Opening context menu displays error notification

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#10592]
### Description

The context menu shows me errors. It comes from shell inputs (I tested by disabling them in the code).
I don't understand this part of the code well enough to fix it.

### Steps To Reproduce

1. Open a context menu with shell entries.
2. A error is displayed (somethings went wrong).
3. Exit Files.
4. A another error is diplayed (OLE Automation, com server in use).

### Steps to fix

It's probably coming from one of the shell entries. I'll try to find which one.

### Files Version

Version: 2.3.57.0 OS Version: 10.0.22621.819

### Windows Version

Windows 11 22621.674

### Relevant Assets/Logs

https://user-images.githubusercontent.com/46631671/204159435-c8aa8107-4ccc-40d2-9bc9-025e80dd3bfb.mp4

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by cinqmilleans** [comment]
Yes in the preview and the dev since winui3.

**Comment by cinqmilleans** [comment]
I used ShellExView software (https://www.nirsoft.net/utils/shexview.html) to detect the problematic entry.
"Play to Menu" (Microsoft) triggers the error when opening the menu of a video file.
"Attribute Changer" (https://www.petges.lu/) triggers the error when closing Files after opening the context menu.
The second is little used but the first is more annoying.

**Comment by yaira2** [comment]
Is it something we're doing in Files or something from the shell extensions?

**Comment by cinqmilleans** [comment]
I did some additional analysis. The problem is caused by my television (LG c1). When it's off, I no longer have the problem.
My TV is not visible in the "Cast to Device" menu but my other devices are there. However, it is visible in File Explorer.
I solved the problem by disabling this shell menu.

I didn't solve the bug because the error message is displayed before going into the exception catch that displays it (app.cs). This is probably at multitasking.

**Comment by onegladiator4u** [comment]
I'm using 
Edition	Windows 10 Pro
Version	22H2
Installed on	‎11/‎7/‎2022
OS build	19045.2486
Experience	Windows Feature Experience Pack 120.2212.4190.0

Files Version: 2.4.25.0
OS Version: 10.0.19045.2486
On right click getting error 
![Files_oHQks2vyfA](https://user-images.githubusercontent.com/48617390/215150468-a0808de0-55f9-421f-a232-8065af4cd0b8.png)

Got this error in event viewer.
```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
<System>
  <Provider Name=".NET Runtime" /> 
  <EventID Qualifiers="0">1026</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2023-01-27T17:07:29.6185938Z" /> 
  <EventRecordID>16439</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>GIFT-OF-GOD</Computer> 
  <Security /> 
  </System>
<EventData>
  <Data>Application: Files.exe CoreCLR Version: 7.0.222.60605 .NET Version: 7.0.2 Description: The process was terminated due to an unhandled exception. Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt. Stack: at Vanara.PInvoke.Shell32+IContextMenu.QueryContextMenu(Vanara.PInvoke.HMENU, UInt32, UInt32, UInt32, CMF) at Vanara.PInvoke.Shell32+IContextMenu.QueryContextMenu(Vanara.PInvoke.HMENU, UInt32, UInt32, UInt32, CMF) at Files.App.Shell.ContextMenu.GetContextMenuForFiles(Vanara.Windows.Shell.ShellItem[], CMF, Files.App.Shell.ThreadWithMessageQueue, System.Func`2<System.String,Boolean>) at Files.App.Shell.ContextMenu+<>c__DisplayClass10_0.<GetContextMenuForFiles>b__0() at Files.App.Shell.ThreadWithMessageQueue.<.ctor>b__5_0()</Data> 
  </EventData>
  </Event>
```

**Comment by yaira2** [comment]
I'm getting this error quite frequently, app freezes for around a second each time but doesn't crash.
