### ISSUE TITLE
the search function doesnt work with windows search closed 

### ISSUE THREAD

**Issue by angaratosurion** [files-community/Files#10594]
### What feature or improvement do you think would benefit Files?

the search function doesnt work with windows search closed 

### Requirements

1) go to a folder with a lof subfolders
2) search for something (for exampe *.*)
3) nothing appears

### Files Version

Έκδοση: 2.3.63.0 OS Version: 10.0.22000.1281

### Windows Version

Windows 11 Pro 21H2

**Comment by Josh-65** [comment]
What do you mean closed? If you disabled it then of course search isn't going to work.

**Comment by angaratosurion** [comment]
yeah . 
is it possible to make work even without windows search sicne it isnt exactly a good way to search even with windows explorer

**Comment by Josh-65** [comment]
No it uses the same system. Better implementation is being look at
