### ISSUE TITLE
I hope it can run as Administrator by default

### ISSUE THREAD

**Issue by SteveWorkshop** [files-community/Files#10601]
### What feature or improvement do you think would benefit Files?

  When I opened it, it should automically run as Administrator. Currently to do this, I have to right click the icon and choose 'Run as Administrator' manually. 
  I know, directly get admin premission is a little hard. Maybe you can set a startup item to do this. when boot completed, files can auto start as admin. The famous Powertoys has achieved this. 
  You know that if run as non-admin, some operations cannot be achieved, like deleting some folders or files in C:.
If it can automatically get admin premission, maybe it can really replace explorer.exe! 
As far as I know, MS will gradually replace inbox apps with WAS (Windows App SDK), when winui3 becomes mature. So this time you can go a step ahead them.

### Requirements

- This proposal will accomplish running as admin by default. 

### Files Version

Version: 2.3.36.0

### Windows Version

Windows 11 Pro for Workstations build 22623.1020

**Comment by koltenfluckiger** [comment]
I found a way to run it as admin through the command line.

```shell
$filesExePath = "$ENV:LOCALAPPDATA\Packages\Files*\LocalState\FilesOpenDialog\FilesLauncher.exe"

powershell Start-Process -Verb runas -FilePath $filesExePath
```
You can even put in a file path and it will open up the files app in that folder.
```shell
$filesExePath = "$ENV:LOCALAPPDATA\Packages\Files*\LocalState\FilesOpenDialog\FilesLauncher.exe"
powershell Start-Process -Verb runas -FilePath $filesExePath C:\
```

**Comment by yaira2** [comment]
It looks like you can change the file attributes for "Files.exe" to always run as admin. There is also this issue #10422

**Comment by koltenfluckiger** [comment]
You're welcome! Enjoy!

@SeamusReynolds
