### ISSUE TITLE
Multiple StartSTATask's

### ISSUE THREAD

**Issue by TheBestUser01234567890** [files-community/Files#10602]
### Description

The file src/Files.App/Shell/Win32API.cs has multiple definitions with the same name, StartSTATask

### Concerned code

Only this file: src/Files.App/Shell/Win32API.cs

### Gains

A better code quality (and possibly fix some bugs)

### Requirements

Solving this problem.

**Comment by gave92** [comment]
Each method has different input parameters, it's not really strange it's called method overloading. But perhaps we can make some of the code common.
