### ISSUE TITLE
Open File Dialog

### ISSUE THREAD

**Issue by YT-Advanced** [files-community/Files#10600]
### What feature or improvement do you think would benefit Files?

Dear all, I am an developer and I wish Files has a custom open file dialog and I can use it on my project. Can you help me to do that. Thank you ❤️

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.3.12

### Windows Version

Windows 11

**Comment by Josh-65** [comment]
Merging with #6314
