### ISSUE TITLE
"Spill folder" in right-click context menu

### ISSUE THREAD

**Issue by i-dont-know-username** [files-community/Files#10619]
### What feature or improvement do you think would benefit Files?

To get to the point, I would like there to be an option in the right-click menu called "Spill folder" or "Disolve folder" or something like that where when you right-click on a folder, you can spill its contents into the parent folder

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.3.12.0

### Windows Version

Windows 11 Home, 22H2, Build: 22623.1020

**Comment by Josh-65** [comment]
This doesn't make sense. How would Files know what to split? Why not use the cut option in the right click menu. Dissolving the folder is just deleting it.

**Comment by i-dont-know-username** [comment]
I worded that quite badly, think of it as extracting a folder, that makes more sense

**Comment by Josh-65** [comment]
You can then just select all (Ctrl + A) in that folder then cut then paste it to were you want

**Comment by i-dont-know-username** [comment]
Of course I know you can do that, but I'm just asking for an easier option

**Comment by yaira2** [comment]
I believe this is referred to as flattening folders, it's a neat feature but not something we plan to integrate with Files as it can already be done via shell extensions.

**Comment by yaira2** [comment]
@i-dont-know-username I thought you'd want to know that we've started work on this feature. You can follow our progress in #12367.
