### ISSUE TITLE
When the music player stops, the Files throw a error.

### ISSUE THREAD

**Issue by Geydson-Santos** [files-community/Files#10615]
### Description

My music finalized and the Files request me to notify the developers.

### Steps To Reproduce

Play a music until end.

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

Versão: 2.3.12.0 OS Version: 10.0.19045.2251

### Windows Version

Windows 10 Pro 22H2

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/10142330/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/10142331/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, we'll need more detailed steps to reproduce this issue. Please reopen the issue when it's filled out.
