### ISSUE TITLE
Drag & drop setting

### ISSUE THREAD

**Issue by FIRTREZ** [files-community/Files#10623]
### What feature or improvement do you think would benefit Files?

Right now when trying to drag & drop a file from the app into the desktop (not the folder desktop in the app itself but the actual one) or in fact any folder located on the desktop the app wants to "link" it. I have tried fixing this issue in "regedit" and now instead of "link" it does say "move" but the app decides to right click and give me options to what I want to do whit the file. A good feature would be to add a setting menu to this where you can select your default action for dragging & dropping files.

### Requirements

- Drag & drop outside of files app setting menu

### Files Version

2.3.12.0

### Windows Version

Windows 10 Pro 21H2 19044.2251

**Comment by gave92** [comment]
Unfortunately that's how the UWP api we use for drag&drop works. For now we can't change this.
