### ISSUE TITLE
Option to stop folder click animation

### ISSUE THREAD

**Issue by trihardseven** [files-community/Files#10620]
### What feature or improvement do you think would benefit Files?

Adding an option to disable the little animation that happens on the folder name text when you click it.

### Requirements

- This proposal will add an option to remove the animation

### Files Version

2.3.12.0

### Windows Version

W10

### Comments

I can't take a screenshot of it, but you can just hold the mouse button on any folder name and you will see the animation.

**Comment by gave92** [comment]
Those are system animations and can't be easily turned off. Good news is that animation had been removed from windows 11.

**Comment by trihardseven** [comment]
@gave92 how is that a system animation if normal explorer doesn't have it?

**Comment by gave92** [comment]
The system listview control for uwp apps has the animation.
Btw I forgot the preview version is not uwp anymore, so that animation is gone. You ca  get it from:
https://files.community/download/preview

**Comment by trihardseven** [comment]
much better, thanks
