### ISSUE TITLE
Feedback to Files App + Recommendation

### ISSUE THREAD

**Issue by LiquidSword1** [files-community/Files#10628]
Hi first of all i want to say that i really enjoy the app.

I just miss one feature:

A Rating-funtion with a 0to5 star appearance in an easy way.

I tested plenty of File-explorers and none of these (around 15to20) did not have any feature to set a rating for folders or data in these.
You had to go into properties always and had to set a rating in a very clumsy way.

So far so good.
Greetings

**Comment by Josh-65** [comment]
Please make a new issue following the issue templates.
