### ISSUE TITLE
Rating for folders and files in there

### ISSUE THREAD

**Issue by LiquidSword1** [files-community/Files#10629]
### What feature or improvement do you think would benefit Files?

A simple way to organize and sort folders and items would beadding a rating from 0to5 Stars(or whatever item/symbol you want)to folders and files.
That way one can seperate high priority folders and data from low priority ones within a huge amount of folders or files.
This should be available directly in a folder

![Screenshot 2022-12-05 143300](https://user-images.githubusercontent.com/119866071/205651092-33e21f2d-9549-4408-8ddb-d8843402300a.png)

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

Excuse me. I do not understand what i have to put in this (REQUIREMENTS)-Area.

### Files Version

Version 2.3.12.0

### Windows Version

Windows 11 22H2 22623.1020

### Comments

All been said.
It would improve the organizing for this great explorer.
The main important thing is to be able to set the rating right after the files without to have to click through another submenu.
Greets

**Comment by gave92** [comment]
Currently you can assign tags to folders and sort by them. Sounds similar to what you'dlike to achieve.

**Comment by yaira2** [comment]
Merging with #8366
