### ISSUE TITLE
Bug: Previewing css files causes crash

### ISSUE THREAD

**Issue by SiRo24** [files-community/Files#10622]
### Description

If the file preview is enabled, Files crashes when clicking the .css file. The loading circle occurs briefly, but then the program freezes.
When copying a .css file, the file gets copied, but Files auto-selects it afterwards, so it crashes again.

### Steps To Reproduce

Enable file preview
click on a .css file

### Steps to fix

fix .css preview

### Files Version

2.3.63.0

### Windows Version

Windows 11 22H2 22623.1020

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10149013/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/10149014/debug_fulltrust.log)

**Comment by gave92** [comment]
Could you make sure this still happens with Files 2.3.63? From the log file it looks like it crashed with 2.3.61 but not anymore. It it still happens could you delete the log file and upload it again after triggering the crash? Thanks!

**Comment by SiRo24** [comment]
I deleted the log files, clicked on a css file, Files started loading forever and was (not responding). But even after staying like that for like 4 minutes, no log files were created.

**Comment by SiRo24** [comment]
First of all, your sample works fine, so I played a little bit around and found out that files freezes if my file is larger than 4KB, no matter what part of the file I delete.
[test.css.txt](https://github.com/files-community/Files/files/10149406/test.css.txt)

But I also have a css file with 29KB and it works completely fine
