### ISSUE TITLE
Option to move Recycle Bin outside Favorites to the main navigation on the bottom

### ISSUE THREAD

**Issue by dionysius** [files-community/Files#10624]
### What feature or improvement do you think would benefit Files?

The default windows file explorer has the Recycle Bin in the main navigation on the bottom:
![image](https://user-images.githubusercontent.com/1341084/205515652-7416e375-478b-47f3-81ad-1e7007c7fac6.png)

While Files has it inside the favorites section:
![image](https://user-images.githubusercontent.com/1341084/205515739-6dc2f10d-b45c-46d7-9f13-80fe17ebf947.png)

### Requirements

It just annoys me a little that it is a "Favorite", to me it is better placed somewhere else (e.g. like the original windows file explorer on the main navigation on the bottom.

### Files Version

Version: 2.3.12.0 OS Version: 10.0.19045.2251

### Windows Version

Edition: Windows 10 Pro, Version: 22H2, OS build: 19045.2251, Experience: Windows Feature Experience Pack 120.2212.4180.0

**Comment by yaira2** [comment]
Files isn't File Explorer, not against this change but we'd need a good reason to do it.

**Comment by dionysius** [comment]
Thank you! Definitely open to discussion. I just realized there's a context menu to enable "groups" of the navigation, wouldn't sound too bad to me to be there. The question is though, are there other "special folders" or is it really "only" the recycle bin we talk here about (just thinking forward)

![image](https://user-images.githubusercontent.com/1341084/205517278-fe32df88-0c8a-43ae-b38a-bf4a82d71243.png)

**Comment by yaira2** [comment]
We treat Recycle Bin the same as any other pinned favorite, for what it's worth, you can pin other shell pages to the favorites section as well. With the current design, we'd only create a new group in the sidebar if there are items to group under it.

**Comment by yaira2** [comment]
Closing for now but feel free to continue the discussion and I'll try to respond.
