### ISSUE TITLE
files files browsing feedback

### ISSUE THREAD

**Issue by stoph88** [files-community/Files#10630]
love Files, but I think one thing that would elevate it to the absolute top would be to have a dropdown arrow for folders and subfolders so that you can see ALL files at once, contained neatly in the subfolders.  Basically how Finder works on a Mac, or Treesize on PC.  That would make it perfect!

**Comment by yair100** [comment]
@stoph88 Tree View is currently available in preview https://files.community/download. It will be included in the next stable release.
