### ISSUE TITLE
No working on dotnet 7

### ISSUE THREAD

**Issue by bropines** [files-community/Files#10639]
### Description

После установки он послал меня ставить уже установленный dotnet 7

### Steps To Reproduce

Install preview

### Steps to fix

I dont know

### Files Version

2.3.64.0

### Windows Version

11 22H2 22623.1020

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/57861007/205991879-5de9b476-8db3-4638-96cf-33ee391dd929.png)

**Comment by yaira2** [comment]
Did you install the runtime?

**Comment by bropines** [comment]
Lol. If you remove the sdk from version 6, then it will start. And only after installing sdk, not runtime. It required exactly sdk 7 version and its packages.

**Comment by bropines** [comment]
I take it this is not normal?

**Comment by yaira2** [comment]
It's a limitation of wasdk. We can work around this by using self-contained but we're trying both options to see which one works best.

**Comment by dhbtfs** [comment]
Having same issue as well.

**Comment by Josh-65** [comment]
Because it's not an issue in Files. Just a test to see if it works better changing it and it's expected with preview.
