### ISSUE TITLE
Feature: implement teracopy for copying/moving operations

### ISSUE THREAD

**Issue by lorenzo-allevi** [files-community/Files#10646]
### What feature or improvement do you think would benefit Files?

the app is GREAT, but the copy/move performance is extremely slow, in fact if Teracopy were implemented the above operations would greatly improve and make the whole app more usable as a daily driver.

https://www.codesector.com/teracopy

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

last

### Windows Version

Windows 11 Pro 22H2

**Comment by Josh-65** [comment]
Merging with #7518

**Comment by thiagojramos** [comment]
The biggest reason that I still haven't migrated to files was the lack of this function
