### ISSUE TITLE
Larger font for low-vision users

### ISSUE THREAD

**Issue by BigGoofyCat** [files-community/Files#10647]
### What feature or improvement do you think would benefit Files?

I recently discovered this app through a couple YouTube videos. However, I'm low-vision and discovered that Files doesn't use the default Windows font settings. This means, if I increase the size with one of the font changers from Wintools.info, it doesn't apply to files. This is a common thing with UWP apps. I'd love to use this full-time instead of Windows Explorer, but I need to be able to easily read what's in the app. I've provided an example of what my Windows Explorer likes like with one of the font changers, alongside this app. I'd like to see an option in the settings of Files to either increase the font size and bold it, or an option to use your system theme. If you have any questions or comments, let me know.

### Requirements

Add an option within the Settings of Files to either increase the font size of list items and icons, or a toggle to use Windows font settings from the WindowMetrics section of the registry. Check out Wintools.info to see how their font changers work. This would allow me to switch to this as my full time file manager. I love the tabs!

### Files Version

Version: 2.3.12.0 OS Version: 10.0.19045.2251

### Windows Version

Windows 10 22H2

### Comments

![Screenshot 2022-12-07 144812](https://user-images.githubusercontent.com/120058489/206293956-473a5daa-af37-4077-b816-cd6eb5ac1eaa.png)
![Screenshot 2022-12-07 144847](https://user-images.githubusercontent.com/120058489/206293959-84ca0e2d-9aad-47b5-a62a-d23d4f6c383e.png)

**Comment by Josh-65** [comment]
Can you see if this is an issue in the preview version? https://files.community/download/preview

**Comment by BigGoofyCat** [comment]
Hi, I downloaded the .appinstaller file, how do I use it? Add-AppxPackage command doesn't work. Thanks in advance!

**Comment by Josh-65** [comment]
Clicking it should open app installer. You can also get it from the Microsoft store app if it's not installed

**Comment by BigGoofyCat** [comment]
Much appreciated! I did not have the App Installer. Quick visit to the store and I have it now! Unfortunately, I'm unable to test the preview version. I get an error about .net framework 7.0 every time, and that's after installing it from Microsoft's website and rebooting. Tested on both Windows 10 and 11. Sorry!
![Screenshot 2022-12-07 153101](https://user-images.githubusercontent.com/120058489/206300761-10633c2b-dc2c-42ef-94bf-a9d865af20a1.png)

**Comment by Josh-65** [comment]
There's a current test going causing that. Just have to wait for a fix/change then try.

**Comment by yaira2** [comment]
As you mentioned in the description, Wintools.info doesn't work with UWP applications. It's possible that our transition to WinAppSdk changes this but it's up to tools like Wintools.info to work it out.

In order to properly change the font size, we recommend using the built-in accessibility options in Windows.

**Comment by yaira2** [comment]
As you mentioned in the description, Wintools.info doesn't work with UWP applications. It's possible that our transition to WinAppSdk changes this but it's up to tools like Wintools.info to work it out.

In order to properly change the font size, we recommend using the built-in accessibility options in Windows

**Comment by Josh-65** [comment]
Can you try installing the preview again it should be able to install it now now

**Comment by BigGoofyCat** [comment]
Preview version does install now, but same thing. In my original post, I was asking for a font size option to be added to the settings of the app. I only mentioned Wintools.info because that's what I use for everything else that's not UWP. I will ask the folks at Wintools.info if they can support UWP.

**Comment by Josh-65** [comment]
Windows settings > accessibility > text size works. Also the preview doesn't used UWP anymore and stable will follow eventually. Should ask about WinAppSDK also

**Comment by BigGoofyCat** [comment]
Ok, that's good to know. I tried the text size option in settings last night. Yes, it works, at the expense of making everything else too large. Microsoft took the lazy route and just added one master toggle for text size. Yu cannot change it on an app-by-app basis. That's why I use 3rd party tools.
