### ISSUE TITLE
FEATURE REQUEST: FLUENT ICONS CAN BE EDITED WITH OUR OWN ICONS

### ISSUE THREAD

**Issue by Shikamaru30** [files-community/Files#10649]
### What feature or improvement do you think would benefit Files?

One of the best features of File Explorer is the ability to change icons to whatever icons we wish. I'd love this on the Files app.

### Requirements

I can change the icon through a right-click option or in the Files settings.

### Files Version

Version: 2.3.12.0

### Windows Version

Windows 11 21H2

**Comment by yaira2** [comment]
This is already available in the properties window under the customization tab.

**Comment by Shikamaru30** [comment]
> This is already available in the properties window under the customization tab.

No, it's not. I'm talking about the Fluent Icons (Home, Favorites, Drives, Tags). I can't change the icons for those menus, they are stuck with the default fluent icons.
![image](https://user-images.githubusercontent.com/82041382/206451191-15faec59-d0b9-4549-a2ad-830ada7e5ddb.png)
