### ISSUE TITLE
Cannot remember FTP token and cannot connect FTP sometimes

### ISSUE THREAD

**Issue by SteveWorkshop** [files-community/Files#10641]
### Description

When connection to a FTP that requires login authentication, it repealty shows the password dialog, eveny time you enter a directory, rather than remembering it. What's worse, even if I type the correct username and password, it still cannot show content in the folder! It seems that when filename conatins non-english characters, this bug will appear! 
To temporarily avoid this I have to switch to explorer.exe, or use 3rd software like FileZilla. —— too troublesome. I should have done this in one app rather than two!

### Steps To Reproduce

1. open Files
2. type a FTP address that requires logon
3. type username and password
4. navigate to a folder, especially whose name contains non-english character.
5. you'll have probability to encounter this bug that no file of folder is displayed
6. then navigate to another folder, it will ask your password again
7. finally you are trapped in a loop

### Steps to fix

I guess this may be caused by non-english characters in filename, because even not in FTP, sometimes you rename or create a file with chinese name, the operation won't be successful.

### Files Version

2.3.64.0

### Windows Version

Windows 11 22623.1028

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10172562/debug.log)

**Comment by Josh-65** [comment]
Merging with #10462
