### ISSUE TITLE
External link goes wrong when you unistall files and keep files(preview)! How surprising! 

### ISSUE THREAD

**Issue by SteveWorkshop** [files-community/Files#10657]
### Description

When I install both files(stable version 2.3.12.0) and files preview(beta 2.3.64.0) and set the later as deflult file explorer(I didn't modify any settings of the stable version), everything goes fine. However when I unistall the stable one, the preview one goes wrong! Concrate behaviour is that when clicking an link that opens explorer.exe(according to my settings, this showld open files preview as expected), An error dialog was shown saying "files is unistalled, restoring default explorer.exe". After clicking yes, the default file explorer will be rollbacked to explorer.exe
What a surprise! they are two apps but they run into conflict...

### Steps To Reproduce

1. install two kinds of Files and set the preview one as default file explorer
2. unistall the stable one
3. choose an external link that opens explorer.exe e.eg. "open log location" in the setting apge
4. you'll see the error dialog

### Steps to fix

Maybe there're some code from old app that hasen't been merged into the new app?

### Files Version

2.3.12.0(stable) and 2.2.64.0(beta)

### Windows Version

windows11 22623.1028

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10186898/debug.log)

**Comment by Josh-65** [comment]
If you turn off the toggle in settings then on again does it set it as default again?

**Comment by SteveWorkshop** [comment]
Well, it did set as default again, but after that you click an external link, the bug will appear again. Even you press ⌘+E!
I've tried unistall both two apps and reinstall them, but it didn't work.
I'm also really confused by this...

**Comment by SteveWorkshop** [comment]
<img width="603" alt="image" src="https://user-images.githubusercontent.com/92452488/206599846-aa886a12-fe21-4d4e-b99e-c290267fb11e.png">
A hint dialog like this.

**Comment by yaira2** [comment]
Can you calarify the issue?

**Comment by SteveWorkshop** [comment]
OK,
I' ve installed Files Stable(called FS in the follwoing context) and Files Preview(called FP in the following context). I set FP as default file explorer then it works fine. Then I unistalled FS. Then things goes wrong——Every time I press win+E, an error dialog would show and default file explorer would become windows explorer.exe. I tried reinstalling FS and FP but it didn't work. Additionally, before I first unistall FS, I configured Windows IIS FTP and firewall settings on my machine. I don't know whether it has something to do with the bug.

**Comment by yaira2** [comment]
If you open Files Preview and toggle the option on/off, does it revert the registry changes?

**Comment by SteveWorkshop** [comment]
> If you open Files Preview and toggle the option on/off, does it revert the registry changes?

After performing this operation, the default file explorer is Windows' explorer.exe.
Then try to set FS or FP as default, the problem still exists.

**Comment by yaira2** [comment]
After setting the default back to File Explorer, remove the version of Files that you no longer want and set the default to the version that you do want.

**Comment by SteveWorkshop** [comment]
> If you open Files Preview and toggle the option on/off, does it revert the registry changes?

Thanks for help! I unistalled both, rebooted my PC and installed Files Stable. Now it finally works!

**Comment by yaira2** [comment]
Thanks for the update.
