### ISSUE TITLE
Opened AppData

### ISSUE THREAD

**Issue by ShingasPT** [files-community/Files#10650]
### Description

This happens most of the times.
I open Files and I go to "%appdata%", it loads the files normally and then crashes.

### Steps To Reproduce

Go to "%appdata%"

### Steps to fix

Fix crash that occurs when a person goes to "%appdata%"

### Files Version

Version 2.3.12.0

### Windows Version

Windows 10 22H2

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10181782/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/10181784/debug_fulltrust.log)

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by ShingasPT** [comment]
It says I require .NET 7.0.0 and yet I already have it?[image: image.png]

**Comment by ShingasPT** [comment]
I fixed it, apparently the executable for the .NET 7.0.0 was different when
I re-downloaded? I installed it again and it's working now. I'm gonna test
to see if it crashes.

**Comment by ShingasPT** [comment]
Problem doesn't occur in the preview, it's working perfectly fine!
