### ISSUE TITLE
Network section doesn't display network folders or devices

### ISSUE THREAD

**Issue by Newguru-1** [files-community/Files#10656]
### Description

I have network shared folders that don't show on the network section, even though they show up on file explorer, and Files Preview chrashes whenever I select the network section.

### Steps To Reproduce

I have network shared folders that don't show on the network section, even though they show up on file explorer, and Files Preview crash whenever I select the network section.

- 1. Select the Network sidebar section.
- 2. Files Preview crash if there are shared folders that exist (file explorer) but don't show up in Files Preview.

![Screenshot 2022-12-08 114027](https://user-images.githubusercontent.com/16686682/206437802-63a88ba6-0616-468a-a437-087be2dbd5e8.jpg)

![Screenshot 2022-12-08 114212](https://user-images.githubusercontent.com/16686682/206438070-852bd554-9381-4d44-b76b-bb860b827678.jpg)

### Steps to fix

I´m sorry, but programing is not my area of expertise.

### Files Version

Files (Preview) version 2.3.64.0

### Windows Version

Windows 11 Version 22H2 (0S Build 22621.900)

### Relevant Assets/Logs

I have network shared folders that don't show on the network section, even though they show up on file explorer, and Files Preview crashes whenever I select the network section.

- 1. Select the Network sidebar section.
- 2. Files Preview crash if there are shared folders that exist (file explorer) but don't show up in Files Preview.

![Screenshot 2022-12-08 114027](https://user-images.githubusercontent.com/16686682/206437802-63a88ba6-0616-468a-a437-087be2dbd5e8.jpg)

![Screenshot 2022-12-08 114212](https://user-images.githubusercontent.com/16686682/206438070-852bd554-9381-4d44-b76b-bb860b827678.jpg)

**Comment by Josh-65** [comment]
Merging with #8304
