### ISSUE TITLE
Unable to create a complete Chinese folder when starting

### ISSUE THREAD

**Issue by yuanziwen2002** [files-community/Files#10669]
### Description

After clicking to create a new folder and inputting a complete Chinese name, you need to delete one Chinese character in order to create the folder.

### Steps To Reproduce

1. Create a new folder 
2. Input Chinese characters (for example, "External Dependency Libraries")
3. Delete one character from the Chinese characters (only then can you properly set the folder name)

### Steps to fix

Unable to create a complete Chinese folder, need to delete one Chinese character after inputting the complete Chinese name in order to create a Chinese folder
![image](https://user-images.githubusercontent.com/53592792/206824577-b0c3c712-18bc-448c-8ae0-1d301e7ff694.png)
![image](https://user-images.githubusercontent.com/53592792/206824642-2544ed54-0676-4ab5-9b02-7f8225bb8790.png)

### Files Version

Version: 2.3.12.0 OS Version: 10.0.19045.2251

### Windows Version

Windows10 22h2 19045.2251

### Relevant Assets/Logs

Since this issue does not generate an error or log, I am using a screenshot instead.
![image](https://user-images.githubusercontent.com/53592792/206824763-1b2b6d2c-52dd-4b4c-9372-742b988bbd2b.png)
![image](https://user-images.githubusercontent.com/53592792/206824768-77647db2-1204-4cae-b315-8f92e4ba2d71.png)

**Comment by gave92** [comment]
Merging with #9563
