### ISSUE TITLE
Bug: Search Unindexed Items Label is not responsive to window size when using Details view

### ISSUE THREAD

**Issue by verdaderoken** [files-community/Files#10664]
### Description

When searching or browsing an empty tag, the label at the bottom is not responsive to window size.
It's only responsive to the column headers which introduces clipping when you resized the window and the column headers are wider.

This only happens in Details View.

![image](https://user-images.githubusercontent.com/88200096/206715840-063f03d2-1256-4508-8fab-ef15059642c9.png)

### Steps To Reproduce

1. Search or browse a tag that contains no item
2. Resize the columns wide enough
3. Resize the window to see the clipping

### Steps to fix

- Make the label responsive to the window size. 

### Files Version

2.3.65.0

### Windows Version

10.0.22623.1028

### Relevant Assets/Logs

None

**Comment by gave92** [comment]
Merging with #10549
