### ISSUE TITLE
Crash pressing drives after being in tags

### ISSUE THREAD

**Issue by otDan** [files-community/Files#10662]
### Description

Going into one of the tags and then pressing on the drives tab crashes Files.

### Steps To Reproduce

1. Press on one of the tags
2. Press on the drives main

### Files Version

Version: 2.3.65.0 OS Version: 10.0.22000.1281

### Windows Version

Microsoft Windows 11 Pro 10.0.22000 Build 22000

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10194076/debug.log)

**Comment by hecksmosis** [comment]
Is this not an issue in the stable version?

**Comment by otDan** [comment]
no only on preview

**Comment by otDan** [comment]
now it happens in the new stable version too
