### ISSUE TITLE
Pin to taskbar

### ISSUE THREAD

**Issue by Rotkiw-16** [files-community/Files#10670]
### What feature or improvement do you think would benefit Files?

There is no pin to taskbar for exe shortcuts and without it app isn't fully functional. I've seen unpin from taskbar option though but no pin to taskbar so that's kinda weird.

### Requirements

-add pin to taskbar

### Files Version

Version: 2.3.12.0 

### Windows Version

OS Version: 10.0.19045.2251

**Comment by gave92** [comment]
Also #8205

**Comment by gave92** [comment]
Since windows 10 microsoft has blocked apps except "explorer.exe" from making changes to the taskbar :/

**Comment by Rotkiw-16** [comment]
That's sad news. Thank you for info😇
