### ISSUE TITLE
Automatically closes

### ISSUE THREAD

**Issue by MadaraOzzie** [files-community/Files#10672]
### Description

Files closes whenever I drag and item from the files app IN FULLSCREEN MODE on-to another app and wont be able to achieve such process.

### Steps To Reproduce

1. Maximize "FILES"
2. Drag and item over the taskbar
3. Files closes

### Steps to fix

Fix crash that occurs when "FILE APPLICATION IS MAXIMIZED*

### Files Version

Version: 2.3.12.0

### Windows Version

Windows 10 Version 21H2 ( OS Build 19044.2251 )

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10201370/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/10201371/debug_fulltrust.log)

**Comment by Josh-65** [comment]
Can you see if this is an issue in the preview version? https://files.community/download/preview

**Comment by MadaraOzzie** [comment]
> Can you see if this is an issue in the preview version? https://files.community/download/preview

Ok..surely will. On it

**Comment by Josh-65** [comment]
Sorry for the late reply. That's good that it doesn't crash anymore. The taskbar issue is being tracked in #10767
