### ISSUE TITLE
Network View

### ISSUE THREAD

**Issue by MikeR022** [files-community/Files#10674]
### Description

Crashes when trying to view network. Happens every time for me. Running 2.3.65.0 (Preview) but believe it also occurs on the version available in the Microsoft Store

### Steps To Reproduce

Browse network - click on network icon (which is white - looks like it's not resolved properly) and then crash.

### Steps to fix

Browse network - crash

### Files Version

2.3.65.0

### Windows Version

22H2

### Relevant Assets/Logs

None

**Comment by Josh-65** [comment]
Can you please upload the debug.log and debug_fulltrust.log files directly to GitHub (email attachments don't work) . You can get them in files settings > about > open log folder.

**Comment by MikeR022** [comment]
Hi Josh

Files attached

 

Thanks

Mike

**Comment by Josh-65** [comment]
You cant send them via email as GitHub wont upload them

**Comment by MikeR022** [comment]
If only I read things properly…. Uploading now.

 

Thanks

Mike
