### ISSUE TITLE
Layout saving

### ISSUE THREAD

**Issue by maw-art** [files-community/Files#10689]
### What feature or improvement do you think would benefit Files?

Hi,
As a developper I need to navigate through sets of explorers.
FileApp multi tab and double panel is great for that.
Now if I could save-restore tabs and panel settings according to my projects, it would just be fantastic.
Cheers

### Requirements

- Save tabs and panels settings
- Restore tabs and panels settings

### Files Version

Version : 2.3.12.0 

### Windows Version

OS Version: 10.0.19045.2311

**Comment by Josh-65** [comment]
You can set it to continue were you left off in Files settings > preferences > start-up. There is also tags you can try to have your folder/files shown as per project.
Layout options are in 2.4 you can get the update here https://files.community/downloads/stable

**Comment by Josh-65** [comment]
In the file you name them you can add as many as you want just copy an entry, then change the UID to anything that not used by another tag but uses the same format. a UI for doing this will come eventually.
