### ISSUE TITLE
The "set as default" option causes malfunctions to the Windows file explorer

### ISSUE THREAD

**Issue by HeLiOn--PrImE** [files-community/Files#10682]
### Description

When I activate the "set as default" setting, the original file explorer will not be able to open external devices such as phones or tablets. 
When I double click on t he device, the windows file explorer will open a new window in the User documents.

This issue occurs on Windows 11 when I connect an android phone. I haven't tested it with Apple devices.
The issue behavior is was filmed and is present right at the beginning of this video: https://www.youtube.com/watch?v=h1svlSPJXYc
The issue does not occur anymore if the "set as default" from the Files explorer is turned off.

### Steps To Reproduce

1. Set Files as the default file explorer through the experimental options.
2. Connect an android phone.
3. Try to open the device contents using the Windows File Explorer.
4. Notice the issue occurring.

### Steps to fix

Correct the action that happens when opening the device contents using the Windows File Explorer, while Files is the default explorer.

### Files Version

2.4.0.0

### Windows Version

Windows 11 22H2 22621.900

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10212517/debug.log)

**Comment by yaira2** [comment]
I can't access the video (you can try uploading directly to GitHub) but the option to replace File Explorer will prevent you from using it in certain circumstances.

**Comment by HeLiOn--PrImE** [comment]
> I can't access the video (you can try uploading directly to GitHub) but the option to replace File Explorer will prevent you from using it in certain circumstances.

Uploading video now:
https://user-images.githubusercontent.com/10486881/207186450-2291f7c4-c07a-43f4-9514-c28ac1cd920a.mp4

**Comment by yaira2** [comment]
This is one of the side effects of replacing File Explorer, if this behavior is an issue for you, we recommend turning off the experimental setting for now.
