### ISSUE TITLE
Files cannot copy or move files from a phone or a tablet

### ISSUE THREAD

**Issue by HeLiOn--PrImE** [files-community/Files#10683]
### Description

When I try to copy a file from a phone to the desktop, I only get an error/warning sound.

This issue occurs on Windows 11, when attempting to copy or move files from an android device.
The issue behavior can be seen using this link at the second 26 of the video: https://youtu.be/h1svlSPJXYc?t=26
This issue was not tested with Apple devices.

### Steps To Reproduce

1. Connect an Android phone or tablet to the computer;
2. Attempt copying or moving a file from the device's storage to the desktop;
3. Notice that a sound is played, but the operation is not performed.

### Steps to fix

- eg. Correct action happens when attempting to move a file from a mobile storage to the desktop.

### Files Version

2.4.0.0

### Windows Version

Windows 11 22H2 22621.900

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10212605/debug.log)

**Comment by gave92** [comment]
Is the destination the windows desktop or the desktop folder inside Files? If the first, could you confirm if it works with the second?

**Comment by HeLiOn--PrImE** [comment]
> 

Yes, it works if the destination is opened with Files.

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by HeLiOn--PrImE** [comment]
> Is this still an issue in the preview version? https://files.community/download/

Not really. Now, the context menu is opened and I have the option to select "copy here". 
It's like dragging and dropping with the right click, instead of the left click.
