### ISSUE TITLE
App Crash when clicking any Bundle Link

### ISSUE THREAD

**Issue by ahmedzeeee** [files-community/Files#10688]
### Description

After the latest update, the app keeps crashing whenever I click on any link for a file or a folder in the bundle widget.

### Steps To Reproduce

click on any link for a file or folder in the bundles widget

### Steps to fix

i couldn't find a fix

### Files Version

2.4.0.0

### Windows Version

Windows 11 Pro 22H2 25247.1000

### Relevant Assets/Logs

NA

**Comment by Josh-65** [comment]
Bundles are not supported anymore and will be removed. You can use tags instead, right click a file or folder to add them. then you can search for them with `tag:<name>` or click in the sidebar. 

You can edit or add more from Files settings > experimental > Edit tags. if adding more the UID is anything in the same format as the others.
