### ISSUE TITLE
Additional context menu items disappear after a short period

### ISSUE THREAD

**Issue by prochak96** [files-community/Files#10680]
### Description

On opening Files, initially right clicking an item produces the full context menu with all 3rd party app context menu items listed. However, after a few seconds of browsing and/or navigating through folders, the FullTrust process seems to malfunction and the additional context menu items disappear. Closing and reopening Files restores context menu items, only for them to disappear again in a few seconds.
FullTrust debug log shows errors with 'input is not a valid 64 bit string', presumably corresponding to this behaviour.

### Steps To Reproduce

1. Open Files.
2. Right click on any file and folder. Context menu appears as normal.
3. Right click a few other files, or navigate through some folders and right click another item. Context menu loses additional items like 3rd party app menus (PowerToys, Everything etc.)
4. Close Files and restart to get same behaviour

https://user-images.githubusercontent.com/31608748/207126176-83ebf1c6-1740-4188-8bc3-44e81a3fd532.mp4

### Steps to fix

Fix Context Menu items disappearing, presumably due to FullTrust process crashing or malfunctioning, as indicated by debug log entries.

### Files Version

Version: 2.3.12.0 OS Version: 10.0.22621.900

### Windows Version

Edition	Windows 11 Pro Version	22H2 Installed on	‎08-‎Nov-‎22 OS build	22621.900 Experience	Windows Feature Experience Pack 1000.22638.1000.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10210995/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/10210996/debug_fulltrust.log)

Video showing the error:
https://user-images.githubusercontent.com/31608748/207126743-bd970afc-6fb2-4045-b76b-0744b6982443.mp4

**Comment by Josh-65** [comment]
Can you see if this is an issue in the preview version? https://files.community/download/preview

It likely just crashes

**Comment by prochak96** [comment]
> 
So far, haven't seen this issue occur with this preview version you've sent. Although I did have Files entirely crash one time when I selected multiple .wav files and right clicked. But that also hasn't happened since then.

Will update is problem reoccurs.

**Comment by gave92** [comment]
Thanks, closing for now.
