### ISSUE TITLE
Bug: Cant set file as default file manager

### ISSUE THREAD

**Issue by joseehilton147** [files-community/Files#10691]
### Description

When i try to set as default the option just freeze, like on image:

![image](https://user-images.githubusercontent.com/53986027/207320030-78bc42e3-860e-4fb3-98d0-c6e5b21cbe85.png)

After while comeback as disabled, no error, nothing, just don't work. Any tip?

![image](https://user-images.githubusercontent.com/53986027/207320102-46b82224-df96-4d19-91d3-f8d7eed2d8e4.png)

### Steps To Reproduce

Try to set as default file manager on preview version

### Steps to fix

dont know how to fix.

### Files Version

Versão: 2.4.0.0 OS Version: 10.0.22621.819

### Windows Version

Windows 11 22H2 22621.819

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10217938/debug.log)

**Comment by Josh-65** [comment]
Have you tried restarting your pc then toggle the option

**Comment by joseehilton147** [comment]
> Have you tried restarting your pc then toggle the option

Yes, didnt work

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by joseehilton147** [comment]
is working on 2.4.11
