### ISSUE TITLE
win+e don't bring the opened File window forward

### ISSUE THREAD

**Issue by leoleoasd** [files-community/Files#10693]
### Description

win+e will open a new tab if there is an existing File window. However, the windows aren't brought forward. It remains under other windows.

### Steps To Reproduce

1. Open File and focus on another full-screen app (like chrome)
2. Win+e
3. A new tab will open in File, but the window remains in the background

### Steps to fix

- bring the window forward when opening a new tab

### Files Version

版本: 2.4.0.0 OS Version: 10.0.22621.900

### Windows Version

Windows 11 22H2 22621.900

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10218123/debug.log)

**Comment by yaira2** [comment]
This issue will be resolved with #13588.
