### ISSUE TITLE
Feature: Add back support for Acrylic themes

### ISSUE THREAD

**Issue by MAR8LE** [files-community/Files#10690]
### Description

I downloaded the app "files" and I can't find the glass theme

### Steps To Reproduce

1. Go to settings
2. Go to appearance
3. Click on custom themes
4. kaboom you won't find the "glass" theme

### Steps to fix

N/A

### Files Version

Version: 2.4.0.0 OS Version: 10.0.22621.819

### Windows Version

Windows 11 22h2

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10217573/debug.log)

**Comment by Josh-65** [comment]
The glass and acrylic themes don't work anymore since using a new UI framework. They will be added back if the developers find a good way to make it work.

**Comment by gave92** [comment]
@yair100 perhaps we should leave this open even if low priority. Not sure if there's any blocking issue in WinUI.

**Comment by yaira2** [comment]
It should probably be a priority to bring back Acrylic support, we can switch between the acrylic and mica backdrop from code behind (acrylic for Windows 10 and Mica for Windows 11).

**Comment by DAKCHLEK** [comment]
WE LOVE THE FILES PROGRAMM FOR HIS GLASS THEME . BRING IT BACK GUYS

**Comment by AkazaRenn** [comment]
My favorite thing about "Acrylic Blue" theme is that the operation icons do not follow the system's choice, which makes the whole interface more alive. Would it be possible to add a theme like "default with colorful icons"?

**Comment by yaira2** [comment]
```xml
<ResourceDictionary
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:BelowWindows10version1809="http://schemas.microsoft.com/winfx/2006/xaml/presentation?IsApiContractNotPresent(Windows.Foundation.UniversalApiContract, 7)"
    xmlns:Windows10version1809="http://schemas.microsoft.com/winfx/2006/xaml/presentation?IsApiContractPresent(Windows.Foundation.UniversalApiContract, 7)">
    <ResourceDictionary.ThemeDictionaries>
        <ResourceDictionary x:Key="Default">
            <!--  Accent & button colors  -->
            <Color x:Key="SystemAccentColorDark1">#3d5dfb</Color>
            <Color x:Key="SystemAccentColorDark2">#3d5dfb</Color>
            <Color x:Key="SystemAccentColorDark3">#3d5dfb</Color>
            <Color x:Key="SystemAccentColorLight1">#3d5dfb</Color>
            <Color x:Key="SystemAccentColorLight2">#3d5dfb</Color>
            <Color x:Key="SystemAccentColorLight3">#3d5dfb</Color>
        </ResourceDictionary>

        <ResourceDictionary x:Key="Light">
            <!--  Accent & button colors  -->
            <Color x:Key="SystemAccentColorDark1">#46b2ef</Color>
            <Color x:Key="SystemAccentColorDark2">#46b2ef</Color>
            <Color x:Key="SystemAccentColorDark3">#46b2ef</Color>
            <Color x:Key="SystemAccentColorLight1">#46b2ef</Color>
            <Color x:Key="SystemAccentColorLight2">#46b2ef</Color>
            <Color x:Key="SystemAccentColorLight3">#46b2ef</Color>
        </ResourceDictionary>
    </ResourceDictionary.ThemeDictionaries>
</ResourceDictionary>
```

**Comment by AkazaRenn** [comment]
@yair100 Perfect, thank you so much!

**Comment by Anky-y** [comment]
> This is how you can modify the accent colors through a custom theme
> 
> ```
> <ResourceDictionary
>     xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
>     xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
>     <ResourceDictionary.ThemeDictionaries>
>         <ResourceDictionary x:Key="Default">
>             
>             <Color x:Key="SystemAccentColorDark1">#3d5dfb</Color>
>             <Color x:Key="SystemAccentColorDark2">#3d5dfb</Color>
>             <Color x:Key="SystemAccentColorDark3">#3d5dfb</Color>
>             <Color x:Key="SystemAccentColorLight1">#3d5dfb</Color>
>             <Color x:Key="SystemAccentColorLight2">#3d5dfb</Color>
>             <Color x:Key="SystemAccentColorLight3">#3d5dfb</Color>
>         </ResourceDictionary>
> 
>         <ResourceDictionary x:Key="Light">
>             
>             <Color x:Key="SystemAccentColorDark1">#46b2ef</Color>
>             <Color x:Key="SystemAccentColorDark2">#46b2ef</Color>
>             <Color x:Key="SystemAccentColorDark3">#46b2ef</Color>
>             <Color x:Key="SystemAccentColorLight1">#46b2ef</Color>
>             <Color x:Key="SystemAccentColorLight2">#46b2ef</Color>
>             <Color x:Key="SystemAccentColorLight3">#46b2ef</Color>
>         </ResourceDictionary>
>     </ResourceDictionary.ThemeDictionaries>
> </ResourceDictionary>
> ```

could you tell me how to use this?
@yair100

**Comment by AkazaRenn** [comment]
@Anky-y You basically just save the snippet as a `.xaml` file and put it to the custom themes folder, which you can access by clicking the information button in the theme section of settings. After that, the new theme would appear in settings.

**Comment by Anky-y** [comment]
@AkazaRenn  i did that, but when i select the theme from the settings its basically the same as the default one. nothing changes, am i doing something wrong? i create a file with .xaml as extension, use vs code to save the snippet to it and then access it from the settings.

**Comment by AkazaRenn** [comment]
@Anky-y that's what we expected, this theme only changes some the icons to use blue instead of your theme color of window

**Comment by Anky-y** [comment]
> 

oh, i see. i thought itd be the glass theme, my bad. anyway could you tell me which icons are changing? because i cant seem to even notice that difference

**Comment by AkazaRenn** [comment]
@Anky-y Yes it's minor, those I've noticed have changed are these
![image](https://user-images.githubusercontent.com/8340896/208308386-ede28a10-42ee-444a-9d30-54df1af12856.png)

**Comment by Anky-y** [comment]
@AkazaRenn I see, thanks.

**Comment by mdtauk** [comment]
When background acrylic is added back to WinAppSDK - this should probably be a drop down on the Themes page.
```
**Choose a background style**
[_____________________v_]
    |_____________________|
    |_Solid_______________|
    |_Acrylic_____________|
    |_Mica________________|
    |_Image_______________|
    |_____________________|
```

And depending if they are on Windows 10 or 11 - then the possible options are either hidden or disabled.

**Comment by redhotideas** [comment]
this was the perfect theme


<ResourceDictionary
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:BelowWindows10version1809="http://schemas.microsoft.com/winfx/2006/xaml/presentation?IsApiContractNotPresent(Windows.Foundation.UniversalApiContract, 7)"
    xmlns:Windows10version1809="http://schemas.microsoft.com/winfx/2006/xaml/presentation?IsApiContractPresent(Windows.Foundation.UniversalApiContract, 7)">
    <ResourceDictionary.ThemeDictionaries>
        <ResourceDictionary x:Key="Default">
            
            <x:Double x:Key="SidebarTintOpacity">0.6</x:Double>
            <x:Double x:Key="SidebarTintLuminosityOpacity">0.6</x:Double>

            
            <Color x:Key="SolidBackgroundFillColorTertiary">#2D2D2D</Color>

            

            <AcrylicBrush
                x:Key="SidebarContentBackgroundBrush"
                BackgroundSource="HostBackdrop"
                FallbackColor="{ThemeResource SolidBackgroundFillColorBase}"
                TintColor="{ThemeResource SolidBackgroundFillColorBase}"
                TintOpacity="0.77" />

            <SolidColorBrush x:Key="NavigationViewContentBackground" Color="#282828" />

            <SolidColorBrush x:Key="TabViewItemHeaderBackgroundPointerOver" Color="#3C3B3C" />

            <SolidColorBrush x:Key="TitlebarContentBackgroundBrush" Color="#353535" />
            <SolidColorBrush x:Key="TabViewItemHeaderBackgroundSelected" Color="#353535" />
            <SolidColorBrush x:Key="NavigationToolbarBreadcrumbBackgroundBrush" Color="#353535" />
            <SolidColorBrush x:Key="TextControlBackground" Color="#353535" />

            <SolidColorBrush x:Key="NavigationToolbarBackgroundBrush" Color="#353535" />

        </ResourceDictionary>

        <ResourceDictionary x:Key="Light">

            
            
            <AcrylicBrush
                x:Key="SidebarContentBackgroundBrush"
                BackgroundSource="HostBackdrop"
                FallbackColor="{ThemeResource SolidBackgroundFillColorBase}"
                TintColor="{ThemeResource SolidBackgroundFillColorBase}"
                TintOpacity="0.81" />

            <SolidColorBrush x:Key="NavigationViewContentBackground" Color="#F8F8F8" />

            <SolidColorBrush x:Key="TabViewItemHeaderBackgroundPointerOver" Color="#F8F8F8" />

            <SolidColorBrush x:Key="TitlebarContentBackgroundBrush" Color="#EBEBEB" />
            <SolidColorBrush x:Key="TabViewItemHeaderBackgroundSelected" Color="#EBEBEB" />
            <SolidColorBrush x:Key="NavigationToolbarBreadcrumbBackgroundBrush" Color="#EBEBEB" />
            <SolidColorBrush x:Key="TextControlBackground" Color="#EBEBEB" />

            <SolidColorBrush x:Key="NavigationToolbarBackgroundBrush" Color="#EBEBEB" />


        </ResourceDictionary>


        <ResourceDictionary x:Key="HighContrast">
            <StaticResource x:Key="RegionColor" ResourceKey="SystemColorWindowColor" />
            <SolidColorBrush x:Key="RegionBrush" Color="{ThemeResource RegionColor}" />
        </ResourceDictionary>

    </ResourceDictionary.ThemeDictionaries>
</ResourceDictionary>

**Comment by yaira2** [comment]
I'd like to give an update on the acrylic situation and our plans regarding this popular customization but first a little background into why it was removed.

Towards the end of 2022, we migrated the codebase to WinAppSdk. WinAppSdk has limited support for acrylic, and it can only be applied to the window background. This means that any control (tabs, address bar, file area, sidebar etc) in the app would be on top of the acrylic which defeats the purpose of having it in the first place. Additionally, we have less control over the acrylic transparency and tint color, officially these can be changed but in practice it's buggy and doesn't work as intended.

It's worth noting that in Windows 11, there is a better alternative to acrylic called mica. Mica is a little less transparent and it uses the desktop wallpaper instead of the content behind it. This performs better than acrylic and looks better in many cases. We're looking to bring this to Windows 10 as well so that Files has the same look and feel for everyone.

While acrylic was removed, we still offer advanced customization options, and we recently added an option to settings for changing the background color. There is a wide selection of colors built-in and you can also use a custom color. Support for changing the background colors of the sideabr, address bar and file area is available as well https://files.community/docs/configuring/custom-themes.
![image](https://user-images.githubusercontent.com/39923744/212373511-1304715b-7203-483a-b336-c3e8ac517d63.png)

**Comment by yaira2** [comment]
It appears that you can get the glass effect on Windows 11 by following these steps
1. Open settings > advanced > edit settings file.
2. Close the Files app before continuing
3. Adjust the values for the sidebar, address bar and file area to `#00000001` and restart the Files app.

**Comment by redhotideas** [comment]
I had to go back to version 2.3, the thing I liked the most were:
1-"glass" personalization
2-fully customizable themes
3-column view for navigation

So I miss all the updates and improvements of the new versions... 2.3 still has some problems. I trust that functionality 1 and 2 will be restored as soon as possible otherwise I will be forced to abandon this program over time.
I'm sorry because I think it really potentially better than Explorer

**Comment by yaira2** [comment]
1. Did you follow the instructions above?
2. Which customization options are you missing?

**Comment by redhotideas** [comment]
https://www.windowslatest.com/2022/06/02/windows-11-22h2-is-bringing-mica-acrylic-design-to-more-win32-desktop-apps/

**Comment by yaira2** [comment]
> What's the performance problem? I have a very performing computer (32core 2xRTX3080 128gbRAM), can't you give the possibility to activate it with a performance disclaimer?

1. Theatrically yes, but then users turn it on and still blame the app for performance (see the option to calculate folder sizes)
2. It doesn't work in WinAppSDK, this is the main reason it was removed. The acrylic in WinAppSdk is not the same as it was in UWP.

**Comment by redhotideas** [comment]
You can set it to be activated in the user settings file, so as not to make it easily activated by everyone but by following the instructions

**Comment by redhotideas** [comment]
Is it possible to donate to get this update?

**Comment by yaira2** [comment]
Donations are always welcome, but I hope I'm being transparent when I say we don't have plans to bring back acrylic support right now. Your recommendation to require editing the settings file to enable acrylic would help with the performance concerns. However, as mentioned above, it still doesn't work properly in WinAppSdk. If the issues are resolved, we can reevaluate.

**Comment by redhotideas** [comment]
Is possible ti active acrylic in the v2.4.25?

**Comment by Josh-65** [comment]
No see the above comment

**Comment by yaira2** [comment]
We're excited to share to acrylic will be returning in v2.5.

**Comment by Anky-y** [comment]
> We're excited to share to acrylic will be returning in v2.5.

Any idea when this will be releasing?

**Comment by yaira2** [comment]
Two or three weeks at the latest
