### ISSUE TITLE
Add locale to others languages on creation date and modified date

### ISSUE THREAD

**Issue by joseehilton147** [files-community/Files#10692]
### What feature or improvement do you think would benefit Files?

I'm from Brazil, so as obvious another language, but when I set to my language the date shows in English.

![image](https://user-images.githubusercontent.com/53986027/207322844-10f3356d-4811-41da-8ea4-55793c059a01.png)

### Requirements

Just set locale based on the region's language, like windows does.

### Files Version

Versão: 2.4.0.0 OS Version: 10.0.22621.819

### Windows Version

Windows 11 22H2  22621.819

**Comment by joseehilton147** [comment]
Another place:

![image](https://user-images.githubusercontent.com/53986027/208092634-cc7df06e-5eac-4239-9bf5-f9e1af8dd318.png)

**Comment by QuaintMako** [comment]
Wasn't it discussed in #10320 already?

**Comment by hishitetsu** [comment]
This happens when the language setting is set to Windows Default instead of a specific language.
I will create a PR to fix this issue.

**Comment by yaira2** [comment]
> Wasn't it discussed in #10320 already?

Yes

**Comment by joseehilton147** [comment]
Closed without fix? 

On #10320 didn't resolve anything u guys told will leave as is, so the bug will keep forever?

**Comment by yaira2** [comment]
This is working as intended, the locale follows the Windows setting. We're continuing to discuss in in #11087 and will change the behavior if it works out.

**Comment by yaira2** [comment]
This should be rsolved with #11087
