### ISSUE TITLE
WEBDAV can't be used.

### ISSUE THREAD

**Issue by BaituLime** [files-community/Files#10699]
### Description

![image](https://user-images.githubusercontent.com/50917215/207467607-3c5a69ea-56f5-4085-bce7-7881a65903e0.png)
![image](https://user-images.githubusercontent.com/50917215/207467661-f134a23a-1e15-4b21-9476-4a0699f24580.png)

### Steps To Reproduce

1. Add a webdav network location. Operate as https://docs.cloudreve.org/use/webdav.
2. Visit it.

### Steps to fix

- Let me use it.

### Files Version

Version: 2.4

### Windows Version

Windows 11 Pro 22H2

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/50917215/207467645-c061772b-fe79-4629-8348-6d9cbb2ec667.png)

**Comment by Josh-65** [comment]
Merging with #3917
