### ISSUE TITLE
Add the ability to rearrange pinned items 

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#1069]
**Is your feature request related to a problem? Please describe.**
No. Currently, to change the order of pinned items shown on the sidebar, I need to manually edit the file or unpin all items and pin them again in the order I want. This is not convenient. 

**Describe the solution you'd like**
The right-click context menu could have a move up and a move down option.

**Comment by Br0ckout** [comment]
Describe the solution you'd like
Click and drag would be a better solution to order them IMO, like how Finder works on MacOS.

**Comment by ldsands** [comment]
If it isn't too much to add in addition to the draging up and down to rearrange, access to a json file similar to what we have access to for the terminal options would be very useful as well.

**Comment by jaigak** [comment]
@yair100 @duke7553 Can I create a custom control for this? Rearranging with drag is not easy with the navigation view control. It was designed for static navigation items and not meant for pinning stuff.

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran We plan on implementing some other changes to the sidebar #692. It's ok to use a different control such as a ListView as long as it can support the UI we are aiming for.

**Comment by Jaiganeshkumaran** [comment]
List view has built-in rearrange feature so we only need to save the state.

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran Will it support a hierarchical menu?

**Comment by jaigak** [comment]
@yair100 List view doesn't support that so we can use tree view instead which also supports reordering.

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran TreeView seems like it can do everything we need.

**Comment by DeveloperWOW64** [comment]
#5609

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5979.
