### ISSUE TITLE
ハンドルを開くとフリーズする

### ISSUE THREAD

**Issue by Gudochiyan** [files-community/Files#10695]
### Description

ホームのハンドルされたフォルダをクリックすると、アプリケーションが終了します

### Steps To Reproduce

1. アプリケーションを立ち上げる。
2. ハンドルにピン止めされたフォルダをクリックする。
![Animation](https://user-images.githubusercontent.com/114858988/207362692-e51be20c-390d-42b3-a618-bb5c446d5d53.gif)

### Steps to fix

アプリケーションの安定性を改善する

### Files Version

バージョン: 2.4.0.0 OS Version: 10.0.22621.900

### Windows Version

Microsoft Windows 11 Home 10.0.22621 build22621

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10218940/debug.log)

**Comment by Josh-65** [comment]
Bundles are not supported anymore and will be removed. You can use tags instead, right click a file or folder to add them. then you can search for them with tag:<name> or click in the sidebar.

You can edit or add more from Files settings > experimental > Edit tags. if adding more the UID is anything in the same format as the others.
