### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by SimonJan78** [files-community/Files#10702]
### Description

Hi. Why in version 2.4.0.0 I can't find Glass Theme? Now everything looking as normal Windows. Could put it back please

### Steps To Reproduce

Please add this Theme

### Steps to fix

Please add this Theme

### Files Version

2.4.0.0.

### Windows Version

Windows 10 

### Relevant Assets/Logs

No need to

**Comment by gave92** [comment]
#10690

**Comment by yaira2** [comment]
@SimonJan78 see this comment for the glass theme https://github.com/files-community/Files/issues/10690#issuecomment-1383390672
