### ISSUE TITLE
Splash screen in the WinUI 3 version

### ISSUE THREAD

**Issue by JaiganeshKumaran** [files-community/Files#10706]
The WinUI 3 version is still pretty slow to startup. Consider having a splash screen instead of a blank background.

**Comment by Josh-65** [comment]
Winui 3 doesn't support splash screen and start up performance is being improved to hopefully not need one.

**Comment by JaiganeshKumaran** [comment]
> Winui 3 doesn't support splash screen and start up performance is being improved to hopefully not need one.

You can create your own yourself.

**Comment by Josh-65** [comment]
I don't think there would be much of a point since start up time would be the same anyway. Also when #9837 is implemented a splash screen wouldn't be needed. I'll leave it to @yair2 to say

**Comment by yaira2** [comment]
We don't have plans to implement a splash screen, we're focused on improving performance and stability. Trimming and AOT support will help with startup speed as well.
