### ISSUE TITLE
Button/element blinking when mouse hovering and caused them not clickable

### ISSUE THREAD

**Issue by rtxbae** [files-community/Files#10705]
### Description

Whenever hovering a mouse over a clickable button/elements, the highlight are blinking in the first few seconds and caused clicking not registered or effectively caused a delay. This would mean I'll to click the element twice before anything happens.

### Steps To Reproduce

1. Hover mouse over any clickable elements
2. Try to click it during the blinking

### Steps to fix

I'm not sure why this is happening, probably something to do with animation code? So maybe one could reduce the animation or such.

### Files Version

Version: 2.4.0.0

### Windows Version

Windows 10 22H2 19045.2364

### Relevant Assets/Logs

https://user-images.githubusercontent.com/65499097/207596676-c2d9595d-ead1-4404-a3df-e687a3c3ebaf.mp4

**Comment by gave92** [comment]
Dint have windows 10 anymore. But it was working.

**Comment by yaira2** [comment]
Could be specific to the build

**Comment by rtxbae** [comment]
@yair100 did you made any changes in 2.4.2.0? I noticed the blinking is gone in this version.

**Comment by yaira2** [comment]
Are they clickable now?

**Comment by rtxbae** [comment]
Yes they do!

**Comment by armanatz** [comment]
@yair100 I have the same issue in Windows 10. All elements that are clickable have this behavior for me. When I hover over anything, it blinks and clicks are not registered in that moment. I am on the latest version (2.4.2.0).

**Comment by RavenMacDaddy** [comment]
https://user-images.githubusercontent.com/67732686/217349786-378f8448-d7d7-4096-95f3-eaa3d8472c61.mp4

Same thing is happening with latest 2.4.31.0 build.

In the clip, I'm just hovering the majority of the time while the UI is flickering like crazy on the corresponding buttons.

**Comment by yaira2** [comment]
It looks like a platform bug, can you report this on the WinUI repo?

**Comment by RavenMacDaddy** [comment]
> It looks like a platform bug, can you report this on the WinUI repo?


By platform, do you mean Windows 11 and its winver, or all of it like hardware and drivers?

**Comment by rtxbae** [comment]
I'm seeing this bug back in 2.4.33.0 and Win10 22H2 19045.2486.

**Comment by Josh-65** [comment]
Check the link above for updates
