### ISSUE TITLE
old versions 

### ISSUE THREAD

**Issue by DAKCHLEK** [files-community/Files#10701]
### What feature or improvement do you think would benefit Files?

howa can i get the old version exe or link  to automaticaly instal it 

### Requirements

get the glass theme back 

### Files Version

2.4

### Windows Version

windows 11

**Comment by yaira2** [comment]
https://github.com/files-community/Files/releases/tag/v2.3.12

**Comment by yaira2** [comment]
@DAKCHLEK see this comment for the glass theme https://github.com/files-community/Files/issues/10690#issuecomment-1383390672
