### ISSUE TITLE
Glass theme

### ISSUE THREAD

**Issue by CarNav09** [files-community/Files#10709]
### What feature or improvement do you think would benefit Files?

hello

Sorry, Any way to activate the glass theme from the previous version? Thank you!

### Requirements

.

### Files Version

v2.4

### Windows Version

Windows 11 Home 22H2

### Comments

.

**Comment by yaira2** [comment]
Merging with #10690

**Comment by yaira2** [comment]
@CarNav09 see this comment for the glass theme https://github.com/files-community/Files/issues/10690#issuecomment-1383390672
