### ISSUE TITLE
Preview windows size

### ISSUE THREAD

**Issue by korsc1211** [files-community/Files#10704]
### Description

I do not undertstand id it's bug.
I have adjusted preview windows size by mouse. But I cannot do it now.
I am not sure when this behavior is occured.
When I change the file name, preview function is useful.
I am biggner to use "files"  
Files versidn 2.4.0.0. 

Best Reagrds
Kpo

### Steps To Reproduce

NA

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

2.4.0.0 OS Version: 10.0.22621.963

### Windows Version

Windows 11 Home 22H2 22621.963 Windows Feature Experience Pack 1000.22638.1000.0

### Relevant Assets/Logs

NA

**Comment by Rpurplebeatle** [comment]
On Windows 10 V22H2, the preview window cannot be resized! This clearly seems to be a bug?

**Comment by Josh-65** [comment]
Are you sure it can not be resized. Have you clicked and held on the left then dragged

**Comment by hecksmosis** [comment]
Can confirm this is an issue @Josh-65

**Comment by yaira2** [comment]
There is a bug where the cursor icon doesn't show, this makes it a little hard to find the correct place to draw but it still works.
