### ISSUE TITLE
URL Shortcut Files Not Displayed On Remote Share

### ISSUE THREAD

**Issue by pdiamond-op** [files-community/Files#10708]
### Description

I have folders with .URL (Internet Shortcut) files in a local directory. If I copy those files to a remote share using Windows Explorer, they are not visible using the Files app. I know the .URL files are actually there because if I copy them over using the Files app, it creates a <filename> - Copy version of it, but neither version is visible in Files. .URL files are visible when located on a local drive.

Remote share with .URL file viewed using Windows Explorer
![image](https://user-images.githubusercontent.com/113446450/207644156-f9aeb0a3-bcfd-47f6-aa30-658ceeeda174.png)

The same remote share viewed using Files app
![image](https://user-images.githubusercontent.com/113446450/207643865-335a2995-bca2-4302-a07a-1104eb39ab6a.png)

### Steps To Reproduce

Create a .URL file in any location on a local drive. Using Windows Explorer (or Files) copy that file to a remote share. 
Notice that the file is not visible on the remote share. 
Navigate to the share using Windows Explorer and notice the file is visible.

### Steps to fix

.URL files should be visible when located on a remote share

### Files Version

2.3.12.0

### Windows Version

Windows 10 22H2

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10229420/debug.log)

**Comment by Josh-65** [comment]
Merging with #2436
