### ISSUE TITLE
Change "KB" to "kB"

### ISSUE THREAD

**Issue by i-dont-know-username** [files-community/Files#10707]
### What feature or improvement do you think would benefit Files?

Using "KB" to represent a quantity of kilobytes is just slightly wrong as the prefix for "kilo-" is "k", not "K". This has just been slightly bothering me every time I see it, it would make a real difference if this small detail could be changed.

Thank you so much!

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.4.0.0

### Windows Version

Windows 11 Home Insider Preview, 22H2, 25262.1000

**Comment by yaira2** [comment]
Merging with #10692
