### ISSUE TITLE
Option to show confirmation dialog before deleting files should only affect when sending to recycle bin

### ISSUE THREAD

**Issue by carlosvsilva** [files-community/Files#10712]
### What feature or improvement do you think would benefit Files?

I think Windows Explorer UX is well though out in this regard, as I can disable confirmation dialog when deleting files to recycle bin, since they can be recovered anyway, there's no need to confirm their recycling.

On the other hand, permanent deletes from disk/filesystem should always display the confirmation dialog as it's irreversible.

I believe Files option to show/hide delete dialog confirmation should only apply to recycling a file, and should still confirm with the user for permanent deletes.

Thanks.

### Requirements

- This proposal will safeguard against spurious/unintended permanent deletes
- This proposal will spare the user from confirmation dialogs for easily reversible deletes. 

### Files Version

Versão: 2.4.0.0

### Windows Version

OS Version: 10.0.22621.963

### Comments

![image](https://user-images.githubusercontent.com/40889421/207670505-0457a9a8-571a-4fb2-b29f-282c85d147b4.png)

**Comment by Josh-65** [comment]
Files already does this.
