### ISSUE TITLE
App may crash when clicking on Network or Recycle Bin in Sidebar

### ISSUE THREAD

**Issue by QuaintMako** [files-community/Files#10715]
### Description

This seems to be an issue appearing randomly when using the Sidebar.

I have been able to provoke it only on the Recycle Bin and the Network Drives so far.

### Steps To Reproduce

1. Alternate clicking between items in the Sidebar
2. When clicking on the Recycle Bin or a Network Drive, the application may crash.

### Steps to fix

- Clicking on Network or Recycle Bin should not provoke a crash.

### Files Version

Version: 2.4.1.0 OS Version: 10.0.19045.2251

### Windows Version

W10 Home 22H2 19045.2251

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10231572/debug.log)

**Comment by QuaintMako** [comment]
Seems to be linked to [#3377646610u on AppCenter.](https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/3377646610u/)

**Comment by Hard-Wired** [comment]
Can confirm...

[debug.log](https://github.com/files-community/Files/files/10232786/debug.log)

**Comment by QuaintMako** [comment]
I'm looking into it.

**Comment by smbell1979** [comment]
Brand new install here, fresh out of the box, clicking on "Network" causes an instant crash. I am able to manually copy and paste a UNC path in and it will browse the locations ok.

[debug.log](https://github.com/files-community/Files/files/10253004/debug.log)
