### ISSUE TITLE
2.4.0 with WindowsAppSDK is a huge step back, why?

### ISSUE THREAD

**Issue by jp-weber** [files-community/Files#10714]
### Description

Unfortunately, the update has worsened a few points: the response time, the RAM consumption and there are UI problems.

### Steps To Reproduce

1. Install 2.3.12
2. Update to 2.4.0
3. notice the differences

### Steps to fix

/

### Files Version

2.4

### Windows Version

Win10 22H2

### Relevant Assets/Logs

/

**Comment by Josh-65** [comment]
Thanks for the feedback. Please make a new issue following the issue templates for each issue you encounter as this is not descriptive to help.

**Comment by jp-weber** [comment]
@Josh-65 
What is the way to contribute feedback? 
There is no discussion tab here, so I see the issues as the only way to do this.

**Comment by yaira2** [comment]
> the RAM consumption and there are UI problems.

Ram usage will be reduced in subsequent updates as we work on improving the codebase. We'd like to hear more about the UI issues, can you open a separate issue and include the steps to reproduce it?

**Comment by jp-weber** [comment]
@yair100 
Thank you for the quick respond. I will create a issue tomorrow which targets the UI problems.
