### ISSUE TITLE
Crash on colors

### ISSUE THREAD

**Issue by spidercraft** [files-community/Files#10713]
### Description

Simply look at this video to know what is happening

https://user-images.githubusercontent.com/51022611/207672346-5a3c32e9-a6fe-40a0-89ab-705b852863b4.mp4

### Steps To Reproduce

you can look at this video : 

https://user-images.githubusercontent.com/51022611/207672381-14694264-ef79-471d-aea4-04a722f4073c.mp4

### Steps to fix

i don't know

### Files Version

Version : 2.4.0.0 OS Version: 10.0.22621.819

### Windows Version

Windows 11 22H2 Windows Feature Experience Pack 1000.22636.1000.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10230493/debug.log)

**Comment by yaira2** [comment]
Is this an issue in v2.4.1?

**Comment by QuaintMako** [comment]
Seems to be fixed on 2.4.3 while I could repeat it on 2.4.1. Down below repeating the same steps:


![index](https://user-images.githubusercontent.com/110472580/208314410-584db253-a064-4c83-834d-452b55d98929.gif)
