### ISSUE TITLE
text-overflow on folders offset to left

### ISSUE THREAD

**Issue by SiRo24** [files-community/Files#10724]
### Description

When naming a folder something like "17. December 16" (short first word second word with about that length and a third word),
in small symbols view mode, the preview is 17.... but it is not centered, instead its left aligned
![image](https://user-images.githubusercontent.com/80770571/207944075-08e6ad02-7923-4d93-822d-22d44550bf35.png)

### Steps To Reproduce

-Create a Folder named "17. December 16" or similar
-switch to small symbols view mode

### Steps to fix

- fix left aligned folder name on certain names

### Files Version

2.4.2.0

### Windows Version

Windows 11 22H2 22623.1028

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10239861/debug.log)

**Comment by Josh-65** [comment]
Merging with #1033
