### ISSUE TITLE
Click on Update files when it is first started and it crashes

### ISSUE THREAD

**Issue by Brian-Westerman** [files-community/Files#10727]
### Description

Just click on the little purple down arrow on the top(ish) right and FILES will crash.

### Steps To Reproduce

Just click on the little purple down arrow on the top(ish) right and FILES will crash.

### Steps to fix

It restarts itself, and works okay so long as you don't press that little arrow

### Files Version

Version: 2.4.1.0 OS Version: 10.0.22000.1335

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎1/‎29/‎2022 OS build	22000.1335 Experience	Windows Feature Experience Pack 1000.22000.1335.0

### Relevant Assets/Logs

Sorry, I don't have any to send you, but it happens every time

**Comment by Josh-65** [comment]
Merging with #10722
