### ISSUE TITLE
Application crash on update button

### ISSUE THREAD

**Issue by davisaac19** [files-community/Files#10723]
### Description

When you click on the refresh button, the application stops and closes completely. It doesn't restart, it just closes and displays a notification of a problem in the app.

### Steps To Reproduce

1. Open Files
2. Click on 'update Files'

### Steps to fix

Correct action happens when clicking on 'update' button

### Files Version

Version 2.4.1.0

### Windows Version

Windows 11 Pro 21H2

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10238346/debug.log)

**Comment by Josh-65** [comment]
Merging with #10722
