### ISSUE TITLE
Support for symbolic links

### ISSUE THREAD

**Issue by ItsCubeTime** [files-community/Files#10725]
### What feature or improvement do you think would benefit Files?

Ability to create & move symbolic links directly in Files.

I use a lot of symbolic links in my smaller personal projects to make cross referencing easy where "shortcuts" are incompatible with the softwares thats supposed to read the file paths, unfortunately windows built in "File Explorer" never really offered any support for symbolic links beyond that it can follow them correctly. The issue of mine comes when I want to move folders containing symlinks as I will have to either re-create them afterwards using a 3rd party tool or move my folders usings some form of 3rd party tool - both solutions I find rather inconvenient.

If you move or copy a symlink with Files today it will just create a placeholder file in its place rather than reconstruct it in its new location

### Requirements

None

### Files Version

2.4.0.0

### Windows Version

Win 11 Version 10.0.22000.1219

**Comment by Josh-65** [comment]
Merging with #9991
