### ISSUE TITLE
The application stops when I click on the shortcuts.

### ISSUE THREAD

**Issue by andreibaraboi** [files-community/Files#10720]
### Description

The application stops when I click on the shortcuts.

### Steps To Reproduce

From the Home screen when I click on one of the Shortcuts (from the Groups) the windows freezes.

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...
From the Home screen when I click on one of the Shortcuts (from the Groups) the windows freezes.

### Files Version

2.4.0.0

### Windows Version

Windows 11 pro

### Relevant Assets/Logs

no screenshot

**Comment by yaira2** [comment]
Thank you for taking the time to report this, in order to investigate the issue we'll need the log files and steps to repro this bug, can you please reopen this issue using the issue template?

**Comment by andreibaraboi** [comment]
I am not sure I know how to to use the issue template.
Can you show me how?
