### ISSUE TITLE
Run Problem

### ISSUE THREAD

**Issue by md-mahabub1712** [files-community/Files#10729]
### Description

Files run into a problem that the developer prepare it.

### Steps To Reproduce

go to

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

Version: 2.4.2.0 OS Version: 10.0.22621.963

### Windows Version

Windows 11 Pro Version	22H2 

### Relevant Assets/Logs

![Screenshot_1](https://user-images.githubusercontent.com/112987718/207983237-55c0b4e1-f58e-48e2-ad27-8d3a8b1d9dfc.png)

**Comment by yaira2** [comment]
We need a little more information from you in order to investigate this issue including the log file and steps to reproduce the issue.
