### ISSUE TITLE
Crash when try to update

### ISSUE THREAD

**Issue by kittenvr** [files-community/Files#10722]
### Description

if i press the update buttons on the top right it closes the app and gives a notification the app crashed

### Steps To Reproduce

open the app
click update button

### Steps to fix

make it not crash when doing the steps above

### Files Version

Version: 2.4.0.0 OS Version: 10.0.22000.1219

### Windows Version

Windows 11 Home 21H2 22000.1219

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10238201/debug.log)

**Comment by kittenvr** [comment]
> 

fulltrust or normal?
![image](https://user-images.githubusercontent.com/103120356/207896380-8eee08ad-5728-4bd7-b377-996c2bf46c90.png)
![image](https://user-images.githubusercontent.com/103120356/207896408-75e47a08-5a08-41e5-a674-9feae519467e.png)

**Comment by Josh-65** [comment]
debug.log

**Comment by kittenvr** [comment]
> debug.log

ok i edited

**Comment by Josh-65** [comment]
You can go to https://files.community/download to manually update

**Comment by marcus-k** [comment]
I encounter the same issue when trying to update from v2.4.1 to v2.4.2. Comparing logs with OP, it looks to be a similar issue.


Log: [debug.log](https://github.com/files-community/Files/files/10239953/debug.log)

**Comment by yaira2** [comment]
Are you using the store version or sideload version?

**Comment by marcus-k** [comment]
I believe it was the sideloaded version I originally got back in v2.3.12. I have only clicked the blue update button in the top-right corner since.

**Comment by yaira2** [comment]
What happens if you manually update using the installer from https://files.community/download/stable?

**Comment by marcus-k** [comment]
Hm, it does seems to have worked, though all my settings have been reset. However, I would say this method is less of an update and more of a reinstall process. Not sure why the built-in updating doesn't work.

**Comment by yaira2** [comment]
The sideload version appears to be more reliable when updating but good to hear this was resolved.
