### ISSUE TITLE
Cant remove second folder path from a folder on library

### ISSUE THREAD

**Issue by joseehilton147** [files-community/Files#10737]
### Description

I've added a second path to library on Downloads folder, but when I try to remove the OK option don't work, don't show error nothing, only don't work.

![1](https://user-images.githubusercontent.com/53986027/208091873-b37cdb7c-dd9a-4240-a186-36ae38c6208d.png)

![2](https://user-images.githubusercontent.com/53986027/208091849-46e22b67-defe-4e1f-b2fb-792b0e2b0646.png)

Another example, I have OneDrive, so have 2 images folders, but cant remove one drive path from library:
![image](https://user-images.githubusercontent.com/53986027/208093483-e3cf11d1-a36b-48ed-8fac-319ecc892463.png)

### Steps To Reproduce

Go to library folder
Add second path
try to remove the path

### Steps to fix

dont know how

### Files Version

Versão: 2.4.2.0 OS Version: 10.0.22621.963

### Windows Version

Windows 11 22H2 22621.963

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10245506/debug.log)

**Comment by Josh-65** [comment]
Is this still an issue in 2.4.33.0

**Comment by yaira2** [comment]
I think it's fixed in the latest preview build.
