### ISSUE TITLE
BUG: Drive icon size

### ISSUE THREAD

**Issue by HarlingtonTigers** [files-community/Files#10734]
### Description

This was introduced with 2.4+

Some of the Drive icons are minimal and surrounded by a box. These are manually added icons rather than MS defaults. They showed fine before 2.4 release.
The icons show fine in the Drive properties tab.
![MAIW_0492](https://user-images.githubusercontent.com/120714008/208065194-9138b7ad-c798-4e13-a4f7-a7c56108198e.jpg)

### Steps To Reproduce

Open the App and the issue is immediately apparent.

### Steps to fix

I have not found a work around.

### Files Version

2.4.2

### Windows Version

Windows 22H2 22621.963

### Relevant Assets/Logs

Clean debug log attached
[debug.log](https://github.com/files-community/Files/files/10244465/debug.log)

**Comment by yaira2** [comment]
We increased the resolution of icons on the home page so that they look sharper. This can be resolved by increasing the size of the custom icons.
