### ISSUE TITLE
Unable to scroll at all in files

### ISSUE THREAD

**Issue by CannibalToast** [files-community/Files#10735]
### Description

Unable to scroll using the trackpad on my laptop in any area of files. Tried with a mouse and the problem persists

### Steps To Reproduce

Try to scroll.

### Steps to fix

unfixed at the moment

### Files Version

Stable 2.4.2.0

### Windows Version

22621.675

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10244850/debug.log)

**Comment by yaira2** [comment]
Is this issue in the setting dialog as well?

**Comment by imlit** [comment]
For me this is everywhere.  In settings section as well.

[debug.log](https://github.com/files-community/Files/files/10271110/debug.log)

**Comment by yaira2** [comment]
Seems to be an issue with WinAppSdk, can you report it on their repository?

**Comment by imlit** [comment]
Do I need to install any of the SDK's ?  I don't have Visual Studio installed.

**Comment by Josh-65** [comment]
You can make the issue here https://github.com/microsoft/WindowsAppSDK/issues
