### ISSUE TITLE
Bundles do not work.

### ISSUE THREAD

**Issue by Tsumiyama-Isao** [files-community/Files#10738]
### Description

I specified an exe file and a folder. But upon clicking either of them the Files throws an "unexpected" error.

### Steps To Reproduce

- Open the app
- Clicka bindle.

### Steps to fix

Fix crash that occurs when clicking a bindle.

### Files Version

Version: 2.4.0.0 OS Version: 10.0.19044.2364

### Windows Version

Windows 10 Home edition 21H2

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/56852320/208099088-a3cef40f-75c7-417a-be1e-5c9ef471bf0d.png)

**Comment by Josh-65** [comment]
This is fixed in 2.4.2.0.
