### ISSUE TITLE
Fake Mica theme for Windows 10 doesn't really feel like Mica

### ISSUE THREAD

**Issue by Hidetoshi6721** [files-community/Files#10732]
### Description

Fake Mica theme is a rather solid image, a blurred blue halo instead of a working mica-like counterpart for Windows 10. My desktop wallpaper is completely different, yet the background is from the default Windows 11 Dark Wallpaper.
![image](https://user-images.githubusercontent.com/85873175/208052972-2b9e5287-1059-40a8-a6b7-c16533b81157.png)

### Steps To Reproduce

1. Open Files.
2. Go to Settings > Custom themes under Appearance.
3. Choose 'Fake Mica'.
4. Click the X button.

### Steps to fix

Bring back the previous Mica Imitation theme. This new one is just a frozen image.

### Files Version

Version: 2.4.2.0 OS Version: 10.0.19044.2364

### Windows Version

Windows 10 21H2 19044.2364

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10243868/debug.log)

**Comment by Josh-65** [comment]
Mica doesn't work on Windows 10 that why that theme is called Fake mica.

**Comment by Josh-65** [comment]
It is possible to change the image used.
1. Download [Fake_Mica_2.zip](https://github.com/files-community/Files/files/10246678/Fake_Mica_2.zip)
2. Extract the file
3. Open it in a text editor
4. Edit the path to image with the file location including file extension
5. Open Files settings > (i) icon on custom themes > open theme folder
6. Place file there
7. Restart Files and then the theme should be in there

**Comment by Hidetoshi6721** [comment]
> 

Understandable, but what happened to the previous Mica Imitation theme that used Acrylic? Even though it didn't _EXACTLY_ doesn't imitate the Mica effect, it was usable and worked better than this solid image... just personal preference though.

**Comment by Josh-65** [comment]
It stopped working since Files change the UI framework. It will be added back if there's a good way to support it. See https://github.com/files-community/Files/issues/10690 for updates
