### ISSUE TITLE
Tags don't stay associated with the files set after closing files app

### ISSUE THREAD

**Issue by ikolander951** [files-community/Files#10731]
### What feature or improvement do you think would benefit Files?

I'm not sure if this was brought up before, but I am finding that while the tag system with color coding things is great, it's pretty annoying to find everything untagged after closing the files app itself any time. Which renders this feature completely useless unless you're only tagging things for temporary reasons.

### Requirements

- Make tags linger after closing files app or at least have it as an option

### Files Version

v.2.4.2

### Windows Version

Windows 11 Version 21H2 22000.1335

**Comment by Josh-65** [comment]
Where are the files your tagging

**Comment by Josh-65** [comment]
Where are the files/folder your tagging

Can you please upload the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.

**Comment by ikolander951** [comment]
[debug.log](https://github.com/files-community/Files/files/10248310/debug.log)

The files are inside of an external drive that I have attached to my PC.
There's the debug.log file.

**Comment by gave92** [comment]
Is the drive formatted as NTFS?
