### ISSUE TITLE
Newly installed. Crashed opening a tab from home to network drives. Version: 2.4.2.0 OS Version: 10.0.19045.2251

### ISSUE THREAD

**Issue by zuvuyan** [files-community/Files#10736]
### Description

Version: 2.4.2.0
OS Version: 10.0.19045.2251

New install, using sideload package. changed a couple of preferences (continue where you left off, show hidden files)
Crashed shortly after opening a tab from home to network drives. Crashed 2 more times in restart. Log file + settings attached. This appears to be the trigger, as I have easily recreated it, just now. 

[debug.log](https://github.com/files-community/Files/files/10245133/debug.log)
[Files_2.4.2.0.zip](https://github.com/files-community/Files/files/10245212/Files_2.4.2.0.zip)

### Steps To Reproduce

1. Open files
2. Create new tab "Network Files"
3. Click on child folder "Network" under network drives

### Steps to fix

close "network" tab

### Files Version

Version: 2.4.2.0

### Windows Version

OS Version: 10.0.19045.2251

### Relevant Assets/Logs

Log file + settings attached above

**Comment by Josh-65** [comment]
Mering with #10715
