### ISSUE TITLE
Crash due to insufficient memory

### ISSUE THREAD

**Issue by rtxbae** [files-community/Files#10730]
### Description

The programme crashed when loading a quite large folder with media, from the log I believe it's due to insufficient memory. However, I have a 32GB RAM system, I doubt it'll overload the system by just parsing the media. But, this bug is not always reproducible, sometimes it crash, sometimes it's not.

### Steps To Reproduce

1. Open folder with lots of media (>75K photos)
2. Scrolling through them and let the programme parsing the thumbnails
3. Observe crash if any

### Steps to fix

Perhaps this could be fix with better thumbnails generation?

### Files Version

2.4.2.0

### Windows Version

Windows 10 22H2 19045.2364

### Relevant Assets/Logs
[debug.log](https://github.com/files-community/Files/files/10243079/debug.log)

Update log:
[debug.log](https://github.com/files-community/Files/files/10243134/debug.log)

**Comment by yaira2** [comment]
Can you delete the log file from your device and reupload (the actual file) after reproducing the crash?

**Comment by yaira2** [comment]
That's the same file, can you clear the file and reupload after reproducing the crash? It'll help use isolate the issue without the noise of the older logs.

**Comment by rtxbae** [comment]
I'll reupload them once I could reproduce this again. It's a hit-and-miss to produce this crash.

**Comment by rtxbae** [comment]
Okay I just reproduced them again, edited the post. This time I also trying to sorting them while they're still updating the thumbnails (Date Modified, Descending).

**Comment by yaira2** [comment]
@rtxbae can you see if there is any difference in v2.4.25?

**Comment by rtxbae** [comment]
So far hasn't notice any crash yet, will let you know update if any.
