### ISSUE TITLE
Bug: Double right click on a file crashes app

### ISSUE THREAD

**Issue by whwdzg** [files-community/Files#10739]
### Description

Double right click on a file crashes app

### Steps To Reproduce

1. Right click a file and with the menu still open, right click the file again

### Steps to fix

- Fix the crash

### Files Version

2.4.2.0

### Windows Version

22623.1028

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10246368/debug.log)

**Comment by yaira2** [comment]
Does this happen with any file or just a specific type?

**Comment by whwdzg** [comment]
oh,i'm whrong, it's double right click, it happened on any files, including folders

**Comment by whwdzg** [comment]
it seems that it will crash in a few seconds after i right click on anywhere

**Comment by yaira2** [comment]
```ERROR|AppUnhandledException|The server threw an exception. (0x80010105 (RPC_E_SERVERFAULT))
	System.Runtime.InteropServices.COMException (0x80010105): The server threw an exception. (0x80010105 (RPC_E_SERVERFAULT))```

**Comment by yaira2** [comment]
Seems like a WinAppSdk issue but hard to know.

**Comment by hecksmosis** [comment]
I don't think this is an issue in the latest version
