### ISSUE TITLE
Not compatible with Samsung flow.

### ISSUE THREAD

**Issue by Bastigonzales** [files-community/Files#10747]
### Description

Samsung flow keeps failing whenever i drag any types of file. (jpg,png,mp4, etc)  But when I tested on Windows Explorer it works fine. 

https://user-images.githubusercontent.com/42995601/208242988-08205b42-a5c8-4caa-9609-5a0ea41ff308.mp4

### Steps To Reproduce

1. Choose any type of file.
2. Make sure your device is connected to Samsung flow.
3. Drag any files to Samsung flow.

### Steps to fix

This could be a problem with Samsung flow but it's worth a try to check on why it keeps on failing even on Administration rights.

### Files Version

Version: 2.4.2.0 OS Version: 10.0.22000.1335

### Windows Version

Windows 11 Home Version 21H2  OS build 22000.1335 Experience

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10251756/debug.log)

**Comment by yaira2** [comment]
This is a known issue and it affects other apps as well, merging with #10171
