### ISSUE TITLE
Files not parsing path correctly from Terminal

### ISSUE THREAD

**Issue by adadarohan** [files-community/Files#10748]
### Description

Opening a file using the terminal (both PowerShell and cmd) results in the following error message - 
"Did you delete this folder? The folder you are attempting to access may have been moved or deleted"

Upon closing the prompt, I notice that the path shown in the bar above is `"C:\Users\adada\AppData\Local\Microsoft\WindowsApps\files.exe" <path>"`, with <path> being the path I enter in my terminal. 

For example, if I run the command `files C:\Users\adada\Downloads`, the path opened is `"C:\Users\adada\AppData\Local\Microsoft\WindowsApps\files.exe" C:\Users\adada\Downloads`. This issue only popped up in v2.2.40 and used to work prior to updating it via the windows store. I really love using this app and would hate it if I had to switch back to the default because I can't open files from the terminal. 

Thanks!

### Steps To Reproduce

1. Open any folder in Files ![image](https://user-images.githubusercontent.com/54441075/208253803-7666f1e7-9f4d-426a-a56c-4ea24039138e.png)
2. Copy its path 
<img width="658" alt="image" src="https://user-images.githubusercontent.com/54441075/208253824-eb27f969-fb43-4b20-becd-985060d9c930.png">
3. Open a terminal and type `files [path]` 
<img width="408" alt="image" src="https://user-images.githubusercontent.com/54441075/208253849-e581eb9a-b218-43a4-bebc-453175490756.png">
4. Error message pops up 
<img width="699" alt="image" src="https://user-images.githubusercontent.com/54441075/208253867-1d7b63b2-db5f-46cd-8e39-c8f1d53313ad.png">

### Steps to fix

I'm sorry, I'm not familiar with the codebase, so I'm not sure how to fix this.

### Files Version

Version: 2.4.2.0 OS Version: 10.0.22621.963

### Windows Version

Windows 11 22H2 22621.963

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10252268/debug.log)

**Comment by ziadh** [comment]
Have you tried running cmd/powershell as adminstrator?

**Comment by Josh-65** [comment]
That's not the issue. Files just doesn't parse the path correctly

**Comment by CrayRazy** [comment]
I have the same exact problem. If I right click anything then click on "open file location" I get the same error as on this post. I even tried reinstalling the app but the bug is still there. Any ideas on how to fix this?

**Comment by adadarohan** [comment]
> Have you tried running cmd/powershell as adminstrator?

Yup, the same issue persists. Here is the list of other things I've tried which didn't solve the issue

1. Restarting PC
2. Reinstalling Files (from the Microsoft Store)
3. Removing WindowsApps from PATH and adding it again

**Comment by adadarohan** [comment]
> That's not the issue. Files just doesn't parse the path correctly

My bad, I have renamed the issue accordingly
