### ISSUE TITLE
HAVE HIGH PRIVLILEGES.

### ISSUE THREAD

**Issue by HelderRocket** [files-community/Files#10741]
### What feature or improvement do you think would benefit Files?

It gets to be annoying that every time I want to make a change, such as deleting a folder or moving a file in a location that requires elevated privileges (such as x86 Program Files), this application just throws an error without giving the possibility to do it with elevated privileges. That is, it does not do it like the native file explorer, which throws a warning that privileges are required, and if I want to apply them.

### Requirements

-Requirement: that an option appears in the application configuration, that says something like if I want to make changes in folders or documents with elevated privileges, and remain active all the time, or if on the contrary ask me every time it is necessary.

### Files Version

Versión: 2.4.2.0

### Windows Version

Windows 10.0.19045.2364

**Comment by Josh-65** [comment]
Merging with #10422

**Comment by yaira2** [comment]
This issue is resolved in our dev branch and will be included in the next release.
