### ISSUE TITLE
Eject and remove image disc

### ISSUE THREAD

**Issue by chkarsten** [files-community/Files#10745]
### What feature or improvement do you think would benefit Files?

Add feature option in tab menu to eject and remove iso image and disc

### Requirements

- Add feature option in tab menu to eject and remove iso image and disc. The same behaviour as Windows 11

### Files Version

2.4.2.0

### Windows Version

Windows 11 22H2 22621.963

**Comment by gave92** [comment]
Right click on the drive on the sidebar should have an eject option.
