### ISSUE TITLE
Window control buttons (minimize, maximize, close) appear on the top left of the window when minimizing

### ISSUE THREAD

**Issue by LolicoreExpress** [files-community/Files#10740]
### Description

When minimizing Files window, the three window control buttons appear in he top left corner of Files' window for a split second as it minimizes.
See attached video (slowed down to 20% to make it easier to see).

### Steps To Reproduce

1. Open Files
2. Minimize the Window
3. Pay close attention to top left corner of the window as it minimizes

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...
Fix buttons wrongly appearing there

### Files Version

2.4.2.0

### Windows Version

Windows 22H2 25267.1000

### Relevant Assets/Logs

https://user-images.githubusercontent.com/29737484/208125794-a60163ea-3125-4893-9c94-8735d240b611.mp4

**Comment by yaira2** [comment]
This appears to be an issue with WinAppSdk, can you report it on their repository?

**Comment by yaira2** [comment]
Feel free to share the link in this issue as well

**Comment by LolicoreExpress** [comment]
Oh, yeah, here it is. Hope it's okay to mention Files directly 😅
https://github.com/microsoft/WindowsAppSDK/issues/3259
