### ISSUE TITLE
Feature: Add alternate color to ListView

### ISSUE THREAD

**Issue by onein528** [files-community/Files#10746]
### What feature or improvement do you think would benefit Files?

Add an alternative color that makes the information of the same object more visually understandable. This feature can be achieved by simply adding the CommunityToolkit extension to the ListView attributes, but the extension is a bit buggy(not until you hover on ListView, it is enabled correctly) on only `WinUI3/Win11` although it should be worked on `UWP/Win10`, `WinUI3/Win10`, and `UWP/Win11`.

```xaml
<Page xmlns:ui="using:Microsoft.Toolkit.Uwp.UI">

<ListView ui:ListViewExtensions.AlternateColor="{ThemeResource SubtleFillColorTertiaryBrush}" />

</Page>
```

I think the most deserved color is `{ThemeResource SubtleFillColorTertiaryBrush}`. However when you selecting item, selecting item and stripes are mostly the same color.

### Requirements

_I don’t know what I describe here_

### Files Version

Version: 2.4.2

### Windows Version

Windows 11 22000.100

### Assets

The alternate color used in both screenshots is `{ThemeResource SubtleFillColorTertiaryBrush}`

Alternate color (working correctly) `UWP/Win11`
![61D21D12-5554-4921-A03F-45B6569CB36C](https://user-images.githubusercontent.com/62196528/208232176-323f8203-91aa-45f8-95aa-7218d6e54579.jpeg)

Alternate color (not working correctly) `WinUI3/Win11`
![6F35B81C-3855-445F-A923-B1D575ABB121](https://user-images.githubusercontent.com/62196528/208232183-f0181078-55e4-4cff-89f4-fcd72579a016.png)

**Comment by yaira2** [comment]
Have you been able to figure out the issue with the colors not appyling?
