### ISSUE TITLE
Memory Intensive

### ISSUE THREAD

**Issue by neildmd** [files-community/Files#10744]
I'm loving this new Files explorer but on Windows 10 Home 64-bit it's hogging a lot of memory. 

I only have 12 tabs open and Files is using up almost 1300 MB of RAM. 

There must be an issue here, how can I troubleshoot it?

Files Version
2.4.2.0

Windows Version
Windows 10 22H2 19045.2364

![image](https://user-images.githubusercontent.com/6560233/208226899-5ef2f553-5b48-4f85-96ea-0ba1a10c4c17.png)

**Comment by Hidetoshi6721** [comment]
It's odd, WinAppSdk is supposed to be faster and lighter than UWP.

**Comment by Josh-65** [comment]
It depends on what's open in those tab. Opened archives and large media folders will increase the ram usage a lot.

**Comment by yaira2** [comment]
> It's odd, WinAppSdk is supposed to be faster and lighter than UWP.

WinAppSdk is faster but it's definitely more resource intensive. It'll get better once they add Native AOT support.

Merging with #4180

**Comment by neildmd** [comment]
All folders open contained mainly PDF and DOC files, not a ton of them, 27 in one and 13 in another. Do shell extensions which handle preview icons play a role in this memory usage?

**Comment by yaira2** [comment]
Thumbnail previews can play a part but I've opened folders containing thousands of images with no issues.

**Comment by hez2010** [comment]
> Thumbnail previews

We have a memory cache for thumbnails and icons, I think we may need to limit the count of cache entries (maybe LRU) to prevent the cache growing too large?

**Comment by neildmd** [comment]
Ok so it's not the previews or any shell extensions. I switched to list view, disable all non-Microsoft shell extensions and after a reboot the mem usages is still the same. 

Are there any common resources that are being used by each tab that could be consolidated? That may be an inaccurate way of looking at how it functions programmatically. I'm not a developer, I only understand the lower levels.

**Comment by yaira2** [comment]
> We have a memory cache for thumbnails and icons, I think we may need to limit the count of cache entries (maybe LRU) to prevent the cache growing too large?

Are you sure there is a cache for thumbnails? I thought it was just for icons.

**Comment by hez2010** [comment]
> Are you sure there is a cache for thumbnails? I thought it was just for icons.

May bad. It's for icons.

**Comment by yair100** [comment]
This issue is resolved in Files Preview.

**Comment by yair100** [comment]
@neildmd we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
