### ISSUE TITLE
Não da para desinstalar!

### ISSUE THREAD

**Issue by inteztino** [files-community/Files#10749]
### Description

Estou tentando desintalar o "Cuphead.v1.2-CODEX" e não vai tambem abriu uma "Unidade de DVD (D:)"

### Steps To Reproduce

1.Tento desintalar um arquivo e ele nao desinstala 

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

Cuphead.v1.2-CODEX

### Windows Version

Windows 11

### Relevant Assets/Logs

Esta na pasta de Downloads

**Comment by gave92** [comment]
This repo is about the [Files](http://files.community/) program. This does not look related.
