### ISSUE TITLE
Trying to set permission to ALL in 'D://' disk (disk where OS is not installed)

### ISSUE THREAD

**Issue by lukaqll** [files-community/Files#10743]
### Description

when clicking "OK" nothing happens and an error pops up with a generic message like a windows standardization

### Steps To Reproduce

1. Go to the disk;
2. Right click on a folder.
3. Click on info icon;
4. Go to Security;
5. Click on + button;
6. Enter a group name;
7. Change permissions;
8. Click OK.

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

most recent on this date

### Windows Version

11

### Relevant Assets/Logs

no

**Comment by Josh-65** [comment]
- Can you give the actual Files version from Files settings > about
- Can you give the actual Windows version from Windows settings > About > OS Build
- Can you please upload the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.

**Comment by yaira2** [comment]
Is this an issue when running Files as admin?
