### ISSUE TITLE
copying by draging a file with right mouse button and changing context menu

### ISSUE THREAD

**Issue by inyfinn** [files-community/Files#10759]
### What feature or improvement do you think would benefit Files?

As in the windows explorer. It would be great to have an option when I can drag and drop a file or folder to a blank space and the context menu would appear showing options like copy here, paste here, zip it and so on.

also

im waiting for an option when I could permanently enable "more option" as a default context menu

### Requirements

As above

### Files Version

Wersja: 2.4.2.0 OS Version: 10.0.22621.963

### Windows Version

Windows 11 Pro 22H2 22623.1037 Windows Feature Experience Pack 1000.22638.1000.0

**Comment by gave92** [comment]
Merging with #1396
