### ISSUE TITLE
Some files it cannot copy while explorer.exe can.

### ISSUE THREAD

**Issue by SteveWorkshop** [files-community/Files#10752]
### Description

Think about this situation:
Explorer.exe will propmt you to select a choice while Files just tell you fail to copy/move.
<img width="338" alt="image" src="https://user-images.githubusercontent.com/92452488/208280008-eb2fcfbb-340d-43a0-8453-abaa2cc94621.png">
One more thing related to this issue: not all attributes of a file can be shown or changed in Files.

### Steps To Reproduce

copy or move a file that has extra attibutes (for example, files downloded from Internet will be recognized 'locked' by default) using Files.

### Steps to fix

- enhance Files to handle various of file attributes

### Files Version

2.4.2.0

### Windows Version

win11 22623.1037

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10253149/debug.log)

**Comment by Josh-65** [comment]
Merging with #9423
