### ISSUE TITLE
Show in folder

### ISSUE THREAD

**Issue by Bhooty** [files-community/Files#10753]
### Description

I am using firefox browser and suppose I downloaded a file, after downloading I click the show in folder which opens the correct folder but not selecting the file.

### Steps To Reproduce

1. Download file from internet via firefox
2. click the show in folder
![image](https://user-images.githubusercontent.com/46019727/208287743-a7174bd4-4d43-4c9d-aef8-79f20298ecc1.png)

3. This open the folder but the file is not selected and also the file manager is not popped out.

### Steps to fix

The file needs to selected after opening the file manager

### Files Version

2.4.2.0

### Windows Version

Windows 11 PRO 22H2

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10253390/debug.log)

**Comment by Josh-65** [comment]
Merging with #9390
