### ISSUE TITLE
failed to pin to start

### ISSUE THREAD

**Issue by Bksp** [files-community/Files#10756]
### Description

When I want to anchor an executable, when I open it from the beginning, it doesn't allow me, it also happens if I make a shortcut and I want to put it in browser favorites.

### Steps To Reproduce

Go to file, archive.
Pin to Start menu / Favorites
Try to open

### Steps to fix

ss idk

### Files Version

Versión: 2.4.0.0

### Windows Version

OS Version: 10.0.22621.963

### Relevant Assets/Logs

.

**Comment by Josh-65** [comment]
Merging with #9740
