### ISSUE TITLE
FONT INSTALLING

### ISSUE THREAD

**Issue by inyfinn** [files-community/Files#10757]
### Description

When i want to install font from a context menu, nothing happens.

### Steps To Reproduce

1 right click on font file
2 click on install
3 nothing happens

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

Wersja: 2.4.2.0 OS Version: 10.0.22621.963

### Windows Version

latest

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10254195/debug.log)

**Comment by Josh-65** [comment]
Can you check "C:\Windows\Fonts" for the font

**Comment by verdaderoken** [comment]
Related to #9295

Currently, only a single font is installed. The problem seems to occur when installing multiple fonts at once. It only installs the first item in the selection.

**Comment by Josh-65** [comment]
From the description they are only doing one font. Files doesn't show the normal install window with it though and usually goes straight into the folder.

**Comment by inyfinn** [comment]
Okay, so in order to install like: 500 fonts I have to do it manually, one by one? ;/
I would rather disable "files" for a moment and use windows explorer.

**Comment by Josh-65** [comment]
If you are installing 1 font check if its in "C:\Windows\Fonts".
If you are installing multiple then it wont work in Files currently. Follow issue #9295 for updates.
