### ISSUE TITLE
It won't open files when "explorer.exe C:\"

### ISSUE THREAD

**Issue by whwdzg** [files-community/Files#10764]
### What feature or improvement do you think would benefit Files?

It can open files when "explorer.exe", but "explorer.exe C:\" didn‘t.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.4.3.0

### Windows Version

Windows 11 build 22623.1037

**Comment by Josh-65** [comment]
Merging with #10748
