### ISSUE TITLE
The Frames Ratio of Caption Buttons ( minmaxclose )

### ISSUE THREAD

**Issue by EpGithub22** [files-community/Files#10768]
Suggestion, please consider to make the aspect ratio of the frames of caption buttons ( minmaxclose ) square or 1:1, this will make the appearance of files explorer more nicer and attractive, not like Windows 11 22H2, its ratio is 1:2, 1:2,5 so that the spacing of caption buttons is far away. Thank you🙏
![FRATIO](https://user-images.githubusercontent.com/120552830/208434687-01644562-cd2f-4cb7-9aa2-b62facdf9201.png)

**Comment by yaira2** [comment]
Thank you for your feedback, were using the default AppWindow setup and don't have plans to change this.
