### ISSUE TITLE
Drag & drop crashes Files (when ran as admin)

### ISSUE THREAD

**Issue by dbatab** [files-community/Files#10766]
### Description

As title: any drag and drop operation I've tried has caused Files to instantly crash. This only happens when running Files as admin (which would be nice to drag & drop into other apps that were ran as admin).

I've tried both the stable and the preview version: same behavior.

### Steps To Reproduce

1. open Files via "run as admin"
2. try to drag and drop anything
3. Files instantly crashes and closes

### Steps to fix

none

### Files Version

both 2.4.2.0 and 2.4.3.0

### Windows Version

Windows 11 Pro Version	10.0.22621 Build 22621

### Relevant Assets/Logs

Files log: [debug.log](https://github.com/files-community/Files/files/10258799/debug.log)

Files Preview log: [debug.log](https://github.com/files-community/Files/files/10258802/debug.log)

**Comment by yslupdates** [comment]
I get a similar error when trying to drag and drop something into program files folder. App crashes or I'm not allowed to make the action

**Comment by yaira2** [comment]
This is an issue with WinAppSdk, merging with #10807
