### ISSUE TITLE
Middle Click Floder Crash

### ISSUE THREAD

**Issue by MSEDGE-CORE** [files-community/Files#10761]
### Description

When using mid mouse to open folder in new Tab in files, the App usually crashes.
https://1drv.ms/u/s!AtEykNVQgVMNlH1rF1NeXhoUGtcM?e=orqInX

### Steps To Reproduce

1. Open FilesApp
2. Open a folder
3. Mid click another folder
4. Files crashes

### Steps to fix

Fix crashes when using mid click to open folder in new tab.

### Files Version

版本: 2.4.2.0 OS Version: 10.0.25227.1010

### Windows Version

OS Version: 10.0.25227.1010

### Relevant Assets/Logs

https://1drv.ms/u/s!AtEykNVQgVMNlH6eCWOfHtbd8g1_?e=mJaYe2

**Comment by Josh-65** [comment]
Can you please upload the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.

**Comment by MSEDGE-CORE** [comment]
https://link.jscdn.cn/1drv/aHR0cHM6Ly8xZHJ2Lm1zL3UvcyFBdEV5a05WUWdWTU5sSDZlQ1dPZkh0YmQ4ZzFf.zip
it seems that i can't upload files in my wifi. Maybe this link works

**Comment by Josh-65** [comment]
That link isn't working for me

**Comment by Marin-Kitagawa** [comment]
I am using 2.4.8.0 but it is working fine for me

**Comment by Josh-65** [comment]
Is this still an issue in 2.4.8

**Comment by MSEDGE-CORE** [comment]
It works well on 2.4.8.0 at 2022/12/28 3:15 PM, but i'm not sure if my PC has something wrong.
