### ISSUE TITLE
Bug: Taskbar doesn't un-hide when Files is full screened/maximized

### ISSUE THREAD

**Issue by Marin-Kitagawa** [files-community/Files#10767]
### Description

My taskbar autohides. When every other app is open, if I hover to the bottom of my screen, the taskbar will show up. But this is not the case when this app is open. This doesn't let the taskbar show up. I have tried restarting the app, restarting the PC and even reinstalling the app. Yet, always, this app prevents the taskbar from showing up.

### Steps To Reproduce

1. Enable the option `Automatically hide the taskbar`
2. Open files app in Maximized Window and let taskbar hide
3. Hover to the bottom of the screen and try to open the taskbar (it won't show up)
4. Open any other app as maximized window and hover to the bottom of the screen and now, the taskbar will show up

For now, the only ways to show the taskbar is to press the windows key or close/minimize/restore the Files app

### Steps to fix

Reveal the taskbar on hover (reaching the bottom of the screen) when taskbar is set to autohide

### Files Version

Version: 2.4.2.0 OS Version: 10.0.22621.963

### Windows Version

Edition	Windows 11 Pro 
Version	22H2 
OS build	22621.963 
Experience	Windows Feature Experience Pack 1000.22638.1000.0

### Relevant Assets/Logs

None

**Comment by yaira2** [comment]
Is this an issue in the Phone Link app as well?

**Comment by yaira2** [comment]
Phone Link uses the same framework as Files so it'll be a good way to isolate the issue.

**Comment by Josh-65** [comment]
For me it working in Phone Link not Files though

**Comment by Marin-Kitagawa** [comment]
This is also the same case with the latest release (Preview version) v2.4.3

**Comment by yaira2** [comment]
Is it an issue with the non preview version of Windows?

**Comment by Josh-65** [comment]
I'm getting it with release 22621.965 and dev 25267.1000

**Comment by Marin-Kitagawa** [comment]
> Is it an issue with the non preview version of Windows?

No. It is Windows 11 Pro Stable. What I meant was, the issue occurs in both the versions 2.4.2 (as mentioned during the creation of this bug) and 2.4.3 (preview) of Files app

**Comment by cdsjsz** [comment]
The problem also happens in the 2.4.25 in win11.

**Comment by Marin-Kitagawa** [comment]
The issue still exists even in the version `2.4.40.0`

**Comment by Bootzzzz** [comment]
Is this issue still not fixed?

**Comment by Marin-Kitagawa** [comment]
No. I am using Files 2.4.62.0 (preview). Even in this, I face the same issue

**Comment by yaira2** [comment]
Thank you for all the feedback, the underlying issue is in the WinAppSdk framework. We'll keep this issue open for tracking purposes but please add your feedback on Microsoft repository so that they hopefully fix it soon. https://github.com/microsoft/microsoft-ui-xaml/issues/8431

**Comment by yaira2** [comment]
@Marin-Kitagawa thank you for your patience, we were able to implement a workaround and this issue will be resolved in the next release.
