### ISSUE TITLE
About NAS

### ISSUE THREAD

**Issue by teruakiy** [files-community/Files#10762]
### Description

I cannot open network drive.

### Steps To Reproduce

1. Open "Files"
2. Click "Network drive".
3. Click "Network".
4. Get error message

### Steps to fix

I have nothing to fix this problem

### Files Version

バージョン: 2.4.2.0 OS Version: 10.0.22621.963

### Windows Version

Windows11 22H2

### Relevant Assets/Logs

"I couldn't get it.

**Comment by Josh-65** [comment]
What type of network drive is it? SMP, FTP, SFTP, WebDav

**Comment by teruakiy** [comment]
Dear　Josh

 

Thank you for your reply.  Maybe my NAS is SMB type and a little bit old.

Today I tried again to access to my device by re-installing your app, but result was same as before.

I’d like to wait your answer.

 

Best regards

Teruaki

 

Maybe my NAS is SMB type.NFrom: Josh-65 ***@***.***> 
Sent: Monday, December 19, 2022 12:28 PM
To: files-community/Files ***@***.***>
Cc: teruakiy ***@***.***>; Author ***@***.***>
Subject: Re: [files-community/Files] About NAS (Issue #10762)

 

What type of network drive is it? SMB, FTP, SFTP, WebDav

**Comment by Josh-65** [comment]
Can you see if this is an issue on 2.4.3

**Comment by teruakiy** [comment]
Now I updated 2.4.3, problem looked be solved
