### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by leowem** [files-community/Files#10778]
### Description

it  does  not  work

1)  How  can we   copy a  complete GDRIVE  on  an external   disk  ?
The GDRIVE is  saved  on the  local  hard  disk   but  it seems FILES  does  not see  it 

We  want to bypass 256 caracters  limitation

thanks 

### Steps To Reproduce

click on

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...
fix crash occurred   when opening

### Files Version

Versione 2.4.3.0 OS Version: 10.0.22621.963

### Windows Version

Edizione	Windows 11 Pro Versione	22H2 Data installazione:	‎28/‎09/‎2022 Build sistema operativo	22621.963 Esperienza	Windows Feature Experience Pack 1000.22638.1000.0

### Relevant Assets/Logs

none

**Comment by Josh-65** [comment]
Google drive way of implementing it cloud make it show as a disk in drives. I don't think Google drive supports being sync to external drive. Files can not bypass the Windows 260 path limit.
