### ISSUE TITLE
Image File Preview Blending Modes

### ISSUE THREAD

**Issue by MrSlimeOfSlime** [files-community/Files#10770]
### What feature or improvement do you think would benefit Files?

When in a display mode that includes a preview of the file, Files uses what appears to be linear sampling for images. Whilst this works great for high resolution images, it makes things like pixel art look bad, and can mess-up transparency.

Adding a setting for nearest-neighbor would fix this issue.

### Requirements

- Adding a setting.
- Adding a nearest-neighbor "function" to whatever renders the file icon.

### Files Version

2.4.2.0

### Windows Version

Windows 10 Pro 21H2 19044.2364

**Comment by yaira2** [comment]
@MrSlimeOfSlime are you talking about file thumbnails or the preview pane?

**Comment by AldeRoberge** [comment]
I know this was marked as completed, but it seems like it's never been fixed. Files uses bilinear filtering (or something simillar) that makes pixel art blurry. It should use point/nearest neighbor for crisp pixel art images.

<img width="838" height="370" alt="Image" src="https://github.com/user-attachments/assets/82aca879-cd79-4686-8d4a-125a6cc14973" />

Related to https://github.com/files-community/Files/issues/6473

**Comment by yair100** [comment]
@AldeRoberge we don't currently plan on implementing this.

**Comment by AldeRoberge** [comment]
@yair100 Thanks for the quick answer.

I understand it's not planned right now.

I think it would be very beneficial since the only alternative that does this is [IrfanView](https://www.irfanview.com/). 

Would you accept a pull request that fixes this?

**Comment by yair100** [comment]
Do you have any thoughts on how it can be done when pulling icons from Windows Explorer?
