### ISSUE TITLE
Settings TopBar Animation

### ISSUE THREAD

**Issue by MSEDGE-CORE** [files-community/Files#10776]
### Description

There's some small bugs in the TopBar animation.

https://user-images.githubusercontent.com/74437699/208583502-19248f39-4255-47c3-86b4-d742265e84bb.mp4

### Steps To Reproduce

1. Open Files
2. Click Settings Icon
3. Click Prefrences
4. Click About
5. Repeat 3.4.

### Steps to fix

Fix the Animation.

### Files Version

版本: 2.4.2.0 OS Version: 10.0.25267.1010

### Windows Version

OS Version: 10.0.25267.1010

### Relevant Assets/Logs

https://user-images.githubusercontent.com/74437699/208583502-19248f39-4255-47c3-86b4-d742265e84bb.mp4
[debug.log](https://github.com/files-community/Files/files/10265292/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, we're currently using the default animations from WinUI. It's possible this was resolved in v2.4.3 but if it's still an issue, we recommend reporting it on the WinUI repository.
