### ISSUE TITLE
Right Click Menu Slow

### ISSUE THREAD

**Issue by MSEDGE-CORE** [files-community/Files#10775]
### Description

When right click a file/folder, the menu appears first, then after several seconds, other options appear in no animation.
It's too slow.
(There's some bug with WinUI that it shows slow animations)

### Steps To Reproduce

1. Open Files
2. Right Click a folder/file.
3. Wait for 5 seconds.

### Steps to fix

Improve the speed of right click menu

### Files Version

版本: 2.4.2.0 OS Version: 10.0.25267.1010

### Windows Version

OS Version: 10.0.25267.1010

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10265236/debug.log)

https://user-images.githubusercontent.com/74437699/208582861-f770b2f4-23e8-4208-b731-c6d297b5fdbe.mp4

**Comment by MSEDGE-CORE** [comment]
https://user-images.githubusercontent.com/74437699/208583031-580cc767-67bb-4cc8-ad5f-9f0b528455b7.mp4

Not that video

**Comment by yaira2** [comment]
Merging with #4180

**Comment by yair100** [comment]
@MSEDGE-CORE we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
