### ISSUE TITLE
Unable to update my app either from the files app itself nor from the microsoft store.

### ISSUE THREAD

**Issue by Tod-911** [files-community/Files#10788]
### Description

I am unable to update my app either from the files app itself nor from the Microsoft store. It show a notification stating that these is a problem that the developers didn't prepare for yet. 
![image](https://user-images.githubusercontent.com/74495889/208844358-10d522b5-b6ca-42d8-87a4-f18aae723fcd.png)

 Even in native Microsoft store when I click on update it downloads but it never installs the downloaded update. After few sec it again starts to download the update again from the scratch, this entire process repeats itself again and again.
![image](https://user-images.githubusercontent.com/74495889/208846297-b6d23b2d-e287-4da0-9512-c010e184ed22.png)

### Steps To Reproduce

https://user-images.githubusercontent.com/74495889/208845193-a69ddf37-a4dd-4eb9-a3e3-aa263c317958.mp4

When I click on the update button on the Files app it shows error.

### Steps to fix

I don't know how to fix this is update issue.

### Files Version

Version 2.4.2.0

### Windows Version

Windows 11 Home 22H2

### Relevant Assets/Logs

Uploading Files Update bug.mp4…

![image](https://user-images.githubusercontent.com/74495889/208845944-7a57e53b-7890-4cec-9dd1-b22cfaced88b.png)
![image](https://user-images.githubusercontent.com/74495889/208846308-e8e79931-de4f-4079-ad47-4a1304b6b457.png)

**Comment by Josh-65** [comment]
Try using the sideload version from http://fles.community/download. Double click the downloaded file to install

**Comment by Josh-65** [comment]
Merging with #10789

The MS Store might not be updating it if Files is "open". You can check task manager for `Files` or `files.exe` and end the process then see if the store will update Files.
