### ISSUE TITLE
PDF THUMBNAILS

### ISSUE THREAD

**Issue by DAKCHLEK** [files-community/Files#10784]
### What feature or improvement do you think would benefit Files?

WYH PDF FILES DONT SHOW THUMBNAILS ?

### Requirements

LET UE SEE THE THUMBNAILS NOT THE ICON 

### Files Version

VERSION 2.0.6.3

### Windows Version

windows 11

**Comment by yaira2** [comment]
PDF thumbnails are supported on v2.4.4.
