### ISSUE TITLE
View doesn't change when a part of the name is typed

### ISSUE THREAD

**Issue by Marin-Kitagawa** [files-community/Files#10780]
### Description

Whenever I type the name of the folder or file, it is highlighted but it is not coming into the view. 

### Steps To Reproduce

1. Open files and choose any layout (for e.g. Column)
2. Make sure the folder you are in has enough folders/files to scroll many times
3. Scoll away from a file/folder you want to open i.e. just make it away from the view
4. Type a part of the name of the file or folder
5. Now, you can notice that the selection happened on the matching file or folder, but the view doesn't change i.e. you must scroll to see if it is highlighted or not. I have tested this in Column mode and it didn't work

### Steps to fix

Make the file/folder appear in the view whenever the name or part of the name of the file or folder is typed

### Files Version

Version: 2.4.3.0 OS Version: 10.0.22621.963

### Windows Version

Edition	Windows 11 Pro 
Version	22H2  
OS build	22621.963 
Experience	Windows Feature Experience Pack 1000.22638.1000.0

### Relevant Assets/Logs

None

**Comment by yaira2** [comment]
Is this an issue in all layouts or just columns?
