### ISSUE TITLE
Administrator privileges pop up

### ISSUE THREAD

**Issue by Marin-Kitagawa** [files-community/Files#10781]
### What feature or improvement do you think would benefit Files?

If I try to delete a folder in Program Files for example, the Files app doesn't invoke the Admin privileges popup. It simply fails. I have to manually run the Files app as administrator to delete such folders.

### Requirements

Make files app invoke Admin privileges popup instead of just failing whenever an operation that requires elevation is performed from within the app

### Files Version

Version: 2.4.3.0 OS Version: 10.0.22621.963

### Windows Version

Edition	Windows 11 Pro 
OS build	22621.963 
Experience	Windows Feature Experience Pack 1000.22638.1000.0

**Comment by Josh-65** [comment]
Merging with #10422

**Comment by yaira2** [comment]
This issue is resolved in our dev branch and will be included in the next release.
