### ISSUE TITLE
Make use of left-right inputs.

### ISSUE THREAD

**Issue by Alex-0723** [files-community/Files#10793]
### What feature or improvement do you think would benefit Files?

Some mouses have 'left' and 'right' buttons on the sides that help to assist with navigation, and they were helpful in File Explorer. Necessity isn't the point here, this is purely just for convenience.

### Requirements

There's only really the need to have Files able to interpret these specific inputs, and act accordingly based on them.

### Files Version

2.2.4.0

### Windows Version

Windows 10 22H2 (likely)

### Comments

I'm really excited for this project, and am interested to see what the future holds for it. As of now, the bugs certainly are there, and the fact that not everything is covered by the 'make default' option is sad, but I foresee this project turning into something likely to be much greater than it is now.

**Comment by yaira2** [comment]
Are you referring to the backwards and forward buttons?
