### ISSUE TITLE
Option to hide Cloud Drives from Drives

### ISSUE THREAD

**Issue by FayneAldan** [files-community/Files#10798]
### What feature or improvement do you think would benefit Files?

There should be an option to hide Cloud Drives that mount as a drive (namely Google Drive (G:)) from the Drives lists throughout the app.

### Requirements

- Hide Google Drive (G:) from the Drives list in the sidebar
- Hide Google Drive (G:) from the Drives widget on the Home page
- Do the same for any other Cloud Drives that mount as a drive, now (if there are any others?) and in the future
- Preferably make this a setting that the user can toggle

### Files Version

Version: 2.4.4.0

### Windows Version

Windows 11 Pro 22H2 22623.1037

**Comment by thebarshablog** [comment]
Interested to take on this issue. I can solve this @FayneAldan

**Comment by Josh-65** [comment]
This issue hasn't been reviewed/approved yet. You can work on items in this project https://github.com/orgs/files-community/projects/3/views/2. Some item will be labelled "Good first issue" it would help you get started and better understand the codebase

**Comment by thebarshablog** [comment]
Thank you for the information @Josh-65.
I'll look into it.

**Comment by yaira2** [comment]
Google Drive is handled by Google, we recommend sharing feedback with them requesting this change.
