### ISSUE TITLE
Bug: Can't Edit or Remove a specific page from Startup settings

### ISSUE THREAD

**Issue by LongGray** [files-community/Files#10794]
### Description

After adding a specific page in Startup settings, you can't remove or edit it, because the buttons responsible for editing or Removing them do not activate. 

### Steps To Reproduce

1. Go to Settings/Preferences/Startup settings
2. Choose Open a specific pages
3. Add one or two pages.
4. Try to edit or remove it.

### Steps to fix

Fix the bug when you can't edit or remove the created pages in Settings/Preference/Startup settings menu.

### Files Version

Version 2.4.4.0

### Windows Version

Windows 10 Pro 21H2 19044.2364

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10280412/debug.log)

![image](https://user-images.githubusercontent.com/67371197/208979509-4922bca4-62da-4589-83cf-1354e3f50434.png)

**Comment by Josh-65** [comment]
There is also an issue with the add button showing a blank box when clicked on.
![image](https://user-images.githubusercontent.com/26977075/209913764-1a62c140-c577-4c0c-9af9-e1d67351f46c.png)

**Comment by ferrariofilippo** [comment]
> There is also an issue with the add button showing a blank box when clicked on.

Everything is fine on my side (Built on latest commit)
![1](https://user-images.githubusercontent.com/102259289/210017054-0f47601b-c61b-4dfc-b07a-9b525b9d9450.png)
