### ISSUE TITLE
Clicking "Update Files" button just crashes Files

### ISSUE THREAD

**Issue by erichschroeter** [files-community/Files#10790]
### Description

Version: 2.4.3.0
OS Version: 10.0.22621.963

Clicking "Update Files" button just crashes Files.

### Steps To Reproduce

1. Click the "Update Files" button
2. Observer Files crash

### Steps to fix

I don't know

### Files Version

2.4.3.0

### Windows Version

10.0.22621.963

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10278154/debug.log)

**Comment by Josh-65** [comment]
Merging with #10789
