### ISSUE TITLE
Feature: Cloud Drives widget for Home screen

### ISSUE THREAD

**Issue by FayneAldan** [files-community/Files#10799]
### What feature or improvement do you think would benefit Files?

There should be an option to access your Cloud Drives from a widget on the Home screen. This would allow users easy access to their cloud drives, which are commonly accessed.

### Requirements

- Add a "Show Cloud Drives widget" option to the "Appearance" settings
- Show the user's Cloud Drives on this widget

### Files Version

Version: 2.4.4.0

### Windows Version

Windows 11 Pro 22H2 22623.1037

**Comment by Josh-65** [comment]
What the issue with using the sidebar one?

**Comment by FayneAldan** [comment]
What's wrong with the Drives menu that made you add Drives to the Home panes? It's there for ease of access. I'm proposing the same idea for cloud drives.

**Comment by yaira2** [comment]
Regular drives are commonly accessed, and some have 10+ drives. Based on our understanding, the average user has less than 3 cloud drives so a cloud drive widget isn't as useful.

**Comment by FayneAldan** [comment]
I'm pretty sure anyone with 10+ drives wouldn't be using cloud drives to begin with. Also, if a user uses a cloud drive, it's probably likely that it's regularly accessed.

**Comment by yaira2** [comment]
How many cloud drives do you have?

**Comment by FayneAldan** [comment]
> How many cloud drives do you have?

pCloud for my PC files (the only one I'm paying), Google Drive for Docs, and iCloud for my photos.
