### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by Adithyan007hack** [files-community/Files#10791]
hello
I have version 2.3.12 installed in my windows 10 machine 
and I have downloaded version 2.4.4.0
and tried to install but it failed to install 
reason showing : "App installer failed to install package dependencies. Ask the developer for package"
Does anyone know how to fix issue?

**Comment by yaira2** [comment]
Where you downloading Files from?

**Comment by Adithyan007hack** [comment]
GitHub latest release

**Comment by yaira2** [comment]
That's the wrong installer, use the one from https://files.community/download/stable.
