### ISSUE TITLE
Cannot delete file protected

### ISSUE THREAD

**Issue by CommandPrompt-Wang** [files-community/Files#10808]
### Description

When i delete a file under C:\, it failed.

### Steps To Reproduce

1. copy some files to C:\
2. open files
3. delete these files

### Steps to fix

Only when you **manually run Files as Admin** will it success, which is very inconvenient

i hope it should automatically pop up the UAC window and delete it. Just like explorer.exe in this video

https://user-images.githubusercontent.com/62493399/209051491-c0241805-f690-47de-a277-73f756109f0f.mp4

### Files Version

Version: 2.4.4.0

### Windows Version

OS Version: 10.0.25267.1000

### Relevant Assets/Logs

https://user-images.githubusercontent.com/62493399/209050576-5ce1c707-9232-4f34-bce2-41bfff82cb99.mp4

it seems that there's nothing useful in this log...
[debug.log](https://github.com/files-community/Files/files/10283557/debug.log)

**Comment by yaira2** [comment]
To resolve this issue, you can run Files as admin. We're tracking support to display a prompt for this in #10422

**Comment by yaira2** [comment]
This issue is resolved in our dev branch and will be included in the next release.
