### ISSUE TITLE
Bug: Crash when opening some remote folder via smb

### ISSUE THREAD

**Issue by mika-savijarvi** [files-community/Files#10803]
### Description

Files will crash when trying to open some remote folder via SMB. I first time noticed this when I tried to open the pictures folder by the home widget, it just getting not respond, and I could not even end it by task manager. Since I redirected my picture folder for this user to a remote folder, I tried to directly access that folder instead of using that widget, and it can just be accessible as usual. I also tried some other remote folders, and I found that sometimes some folders will cause the crashing of files, but sometimes they won't. The only one that can certainly reproduce is using that widget.
Additionally, as I said below when crashing by a remote folder, files CANNOT be ended by task manager. And if using windows explorer to access the same folder when files is crashed, windows explorer WILL ALSO CRASH. 

### Steps To Reproduce

The only way that can 100% reproduce is to set the picture folder of your user to a remote folder such as "\\\\NAS\Photo\", then just click the picture bottom on the homepage.

But this is not the ONLY case that files may crash.

### Steps to fix

Fix that crash.

### Files Version

2.4.4.0

### Windows Version

Windows 11 Pro N for workstation 22H2

### Relevant Assets/Logs

No related log is recorded.

**Comment by Josh-65** [comment]
Can you please upload the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.

**Comment by mika-savijarvi** [comment]
[debug.log](https://github.com/files-community/Files/files/10287949/debug.log)
here is the log. I got that issue around the night of 2022-12-21, and then I just switched back to windows explorer. I don't think any error messages have been logged at that time.

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by mika-savijarvi** [comment]
Yes, the issue still exists in the latest preview version. I have also noticed some new phenomena in the preview version. When the program freezes, I can hear the fan speed noticeably increase, and in the task manager, I can see that one core is being used at 100%. I'm not sure if this information is helpful to you.

Let me provide a detailed description of my issue. I have changed the directions for photos and videos in user folder to my NAS using the smb protocol (path format is \\NAS\...). When I click on the shortcuts for these folders on the start page of files, the program immediately becomes unresponsive, and even forcing end task in the task manager doesn't work. The only solution is to restart the computer. In this way can reproduce the issue 100%.

I have also found that even when I don't click on these shortcuts, there is still a chance of encountering the freezing issue when accessing files on the NAS. This happens randomly, but I personally feel that the probability is higher when attempting to re-access a path that has been accessed in this session.

I hope this information is helpful to you.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by yaira2** [comment]
@mika-savijarvi thank you for checking, do you see anything useful in the log file?

**Comment by mika-savijarvi** [comment]
I cleared all logs and tried to reproduce the issue. Nothing is recorded except a drive list and something related to update checking.

`2023-04-03 00:53:10.3765|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-04-03 00:53:11.9587|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-04-03 00:53:11.9795|INFO|UpdateDrivesAsync|Adding cloud provider "Creative Cloud Files" mapped to C:\Users\"USER NAME"\Creative Cloud Files
2023-04-03 00:53:11.9883|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-04-03 00:53:12.0153|INFO|GetDrivesAsync|Drive added: E:\, Fixed
2023-04-03 00:53:12.0347|INFO|GetDrivesAsync|Drive added: F:\, Fixed
2023-04-03 00:53:12.0510|INFO|GetDrivesAsync|Drive added: G:\, Fixed
2023-04-03 00:53:12.0710|INFO|GetDrivesAsync|Drive added: I:\, Removable
2023-04-03 00:53:14.0238|INFO|CheckForUpdates|SIDELOAD: Checking for updates...
2023-04-03 00:53:14.9057|INFO|CheckForUpdates|SIDELOAD: Current Package Name: FilesPreview
2023-04-03 00:53:14.9141|INFO|CheckForUpdates|SIDELOAD: Remote Package Name: FilesPreview
2023-04-03 00:53:14.9212|INFO|CheckForUpdates|SIDELOAD: Current Version: 2.4.60.0
2023-04-03 00:53:14.9277|INFO|CheckForUpdates|SIDELOAD: Remote Version: 2.4.60.0
2023-04-03 00:53:14.9345|WARN|CheckForUpdates|SIDELOAD: Update not found.2023-04-21 16:10:01.4783|Information|App launched. Launch args type: LaunchActivatedEventArgs`

**Comment by yaira2** [comment]
@mika-savijarvi is this still an issue in v3.0.3? If it is, please upload the updated log file so we can take a closer look.
