### ISSUE TITLE
Feature: Sync pinned favorites with File Explorer

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#10800]
### What feature or improvement do you think would benefit Files?

There is quite a bit of overhead in Files for managing pinned favorites, we can reduce this by synchronizing the feature with File Explorer. @jiejasonliu implemented something similar for the recent files widget and it works really well. This will also reduce friction for new users as their pinned favorites from File Explorer will be available in Files as well.

### Requirements

- Items pinned to quick access should be displayed in the favorites section in Files
- Pinning/unpinning an item in Files should make the change in File Explorer as well
- Pinning/unpinning an item in File Explorer should make the change in Files as well
- Favorites from existing users (stored in the json file) should be migrated to the new system (duplicate favorites should be ignored)
- After migrating old favorites, the json file should no longer be used

### Files Version

v2.4.4

### Windows Version

Windows 11

**Comment by FayneAldan** [comment]
This would also be useful as it would show the user's favorites in file choosers, despite being a system dialog.

**Comment by yaira2** [comment]
@FayneAldan excellent point!
