### ISSUE TITLE
Bug: Files crashes if you drag/drop while running as administrator 

### ISSUE THREAD

**Issue by CommandPrompt-Wang** [files-community/Files#10807]
### Description

When Files is **running as admin**, it crashed when i drag a tab out to create  a new window.

### Steps To Reproduce

when i drag the tab out to create a new window **while file is running as admin**, it crashed.

### Steps to fix

only when Files runs without admin will it run normally.

### Files Version

Version: 2.4.4.0

### Windows Version

OS Version: 10.0.25267.1000

### Relevant Assets/Logs

https://user-images.githubusercontent.com/62493399/209048398-46c0bb9e-236b-4e5f-9914-d1c846dda031.mp4  

in this video, i first try to drag the tab out to create a new window **while file is running as admin**, it crashed.  
the second time, i try again without admin, it didn't crash.  
  
  
the log doesn't seem to contain helpful info......

[debug.log](https://github.com/files-community/Files/files/10283504/debug.log)

**Comment by yaira2** [comment]
https://github.com/microsoft/terminal/issues/12017#issuecomment-1004129669
