### ISSUE TITLE
Crash when clicking the Update (Download) Button

### ISSUE THREAD

**Issue by MalteTasler** [files-community/Files#10812]
### Description

Crash when clicking the Update (Download) Button

### Steps To Reproduce

1. Start Files
2. Click the Update (Download) Button

### Steps to fix

N/A

### Files Version

2.4.2.0

### Windows Version

Windows 11 22H2 Build 22621.963

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10287228/debug.log)

**Comment by yaira2** [comment]
This was resolved in v2.4.8.
