### ISSUE TITLE
Bug: Missing network icon

### ISSUE THREAD

**Issue by grzegk1** [files-community/Files#10811]
### Description

When i open the app, the network icon is missing.

### Steps To Reproduce

-

### Steps to fix

- Display folder icon

### Files Version

Wersja: 2.4.4.0 OS Version: 10.0.22621.963

### Windows Version

Windows 11 22621.963

### Relevant Assets/Logs

![Zrzut ekranu 2022-12-22 135549](https://user-images.githubusercontent.com/65245365/209139474-c9d1c81c-d73f-4e4e-8b1d-554ffab0a98d.jpg)

**Comment by Hard-Wired** [comment]
![Screenshot 2022-12-23 183559](https://user-images.githubusercontent.com/33186956/209413673-31d2fca0-58d0-4243-a696-717cefa783a3.png)

Can confirm.

**Comment by Marin-Kitagawa** [comment]
Yes. Same issue here as well

**Comment by yaira2** [comment]
Which icon is supposed to show?

**Comment by Marin-Kitagawa** [comment]
> Which icon is supposed to show?

Same as file explorer
![image](https://user-images.githubusercontent.com/49131888/209459472-b5449da8-1243-40d7-b5c4-786659668450.png)

**Comment by hecksmosis** [comment]
This should be resolved through #10839

**Comment by yaira2** [comment]
We already use that icon for the section header so it would be confusing to use it for the sub item as well. We can do what we did in the past and display a standard folder icon (not sure why that was removed).

**Comment by hecksmosis** [comment]
I'll change it now
