### ISSUE TITLE
Import Settings - No Feedback Import Worked or Not

### ISSUE THREAD

**Issue by hl2guide** [files-community/Files#10810]
### Description

When importing settings there's no:
1. message that it worked or not
2. message like:
```For all settings to apply, please close and then relaunch this app.```

### Steps To Reproduce

(First export settings to a zip using the settings option)

1. Go to settings (cog)
3. Click the about tab
4. Click manage settings
5. Click import settings
6. Select the zip file

### Steps to fix

1. clearly communicate whether the import worked or not.
2. Add a message like:
```For all settings to apply, please close and then relaunch this app.```

### Files Version

2.4.4.0

### Windows Version

Windows 11 22H2 22621.963

### Relevant Assets/Logs

none

**Comment by yaira2** [comment]
This is currently by design, can you open a feature request for this scenario?
