### ISSUE TITLE
Error happend while viewing the properties of video and audio

### ISSUE THREAD

**Issue by xvzhenduo** [files-community/Files#10821]
### Description

view the property of any video or audio file (I tried `.mp4` `.ts` `.mov` `mp3` `flac`) ,the toast below will pop up
![image](https://user-images.githubusercontent.com/74353173/209250720-fc2eb926-6b1f-4a3f-b9f5-5120fd3adb53.png)
 

### Steps To Reproduce

1. go to any folder contained video or audio
2. right click on any video or audio and open the properties
3. wait for a few seconds

### Steps to fix

- fix the error when viewing the properties of video and audio

### Files Version

Version: 2.4.8.0 OS Version: 10.0.25267.1000

### Windows Version

Windows 11 22H2 25267.1000

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10291307/debug.log)

https://user-images.githubusercontent.com/74353173/209252802-9087e971-d0bb-4f68-8944-23116a275a2d.mp4

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by xvzhenduo** [comment]
> Is this still an issue in the preview version? https://files.community/download/preview

Yes, it still still an issue in the preview version.

**Comment by xvzhenduo** [comment]
seem that it has been fixed in [v2.4.25](https://github.com/files-community/Files/releases/tag/v2.4.25)
