### ISSUE TITLE
Bug: Can't click context menu items when it overlaps with the title bar

### ISSUE THREAD

**Issue by CommandPrompt-Wang** [files-community/Files#10823]
### Description

I cannot click some of the items in the context menu when they overlap with the title bar

### Steps To Reproduce

1. Make the window smaller so the context menu is forced to overlap with the title bar
2. Right click a file
3. Trying clicking the options at the top of the context menu

### Steps to fix

Make sure the menu items can be clicked

**Comment by CommandPrompt-Wang** [comment]
Not only does context menu overlaps with the title bar, But also it overflows window bottom edge

**Comment by KisiselSenfoni** [comment]
Hi. I still have same issue with the latest version.

**Comment by CommandPrompt-Wang** [comment]
@KisiselSenfoni yes.

I wonder if that can be fixed by putting the title bar below(Maybe need to re-write the WinUI souce code?)
(or use window without title bar, write a new title bar, which can also fix #10807 )

**Comment by Poker-sang** [comment]
@yair100 This could be tricky for the WinUI3Gallery has the same problem.
But I found that it may associate with another issue  (while Gallery doesn't have). It is that Flyouts could be **clip** by the edge of the window, when they are placed at the top/bottom of the window, or simply be taller than the window. I don't know why it is like this, But in Gallery, such Flyouts would be collapsed by something like `ScrollViewer`.
So IMO, the best solution is to limit the height of Flyouts to (WindowHeight - TitleBarHeight(40)). This could solve two problems in one fell swoop.
If this doesn't work. I suppose to use Pointer events to implement `SetDragArea` manually. Then we won't be plagued by TitleBar issues any longer.
Or, if we could get the area of Flyouts. We can also simply subtract their area dynamically, which I thought is the worst solution. 🤥

**Comment by yaira2** [comment]
> So IMO, the best solution is to limit the height of Flyouts to (WindowHeight - TitleBarHeight(40)). This could solve two problems in one fell swoop.

It would be a shame to limit the flyout height based on the window height as there is already a limitation where the flyout is stuck in the Windows bounds. I was thinking that your new helper would make subtracting the area easy but I guess it can have performance issues.

**Comment by Poker-sang** [comment]
The helper would perform well when when there are not many rectangles. Flyouts are just one or two rectangles.

**Comment by yaira2** [comment]
Can we detect if the menu overlaps the titlebar and exclude that section?

**Comment by Poker-sang** [comment]
Maybe we can. I don't know exactly if we can get the position of `ContextMenuFlyout`.

**Comment by Poker-sang** [comment]
Emmmm I can check it tomorrow, orafter about 10h.

**Comment by Poker-sang** [comment]
> Can we detect if the menu overlaps the titlebar and exclude that section?

@yair100 If so, we may have to add `Opened` event for every `ContextFlyout`. Isn't this coupling too high?

**Comment by yaira2** [comment]
It might be but I'm not sure what else we can do besides wait for Microsoft to fix this.

**Comment by hishitetsu** [comment]
It is now fixed by WASDK 1.4.
