### ISSUE TITLE
Bug: Removing an item from recent list doesn't work with PowerToys locksmith

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#10820]
### Description

If I have PowerToys file locksmith enabled it will open that on the file trying to remove. If I don't have it on then it doesn't remove the selected item but the last one in the list

### Steps To Reproduce

1. Right click an item in a recent list
2. Click remove
3. See last file from list is removed

### Steps to fix

- Remove selected item from list

### Files Version

2.4.8.0

### Windows Version

10.0.22621.963

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10291334/debug.log)

**Comment by yaira2** [comment]
@Josh65-2201 thank you for reporting this issue, I'm able to reproduce the issue as well.

**Comment by yaira2** [comment]
This issue will be resolved in v2.5.
