### ISSUE TITLE
Include an option or layout change to make all Properties tabs visible without overflow.

### ISSUE THREAD

**Issue by ELowry** [files-community/Files#10827]
#### Issue

Currently, the Properties panel uses tabs with an icon and text that displays 2 tabs, and puts the others in a roll-over menu.

This functions well for users who wish to access only the first two tabs on a regular basis; but as someone who regularly modifies shortcuts (for example), I have to rely on the roll-over menu about 80% of the time when opening the Properties menu (to the point where I tend to fall back to Windows File Explorer for such tasks more often than not).

##### Current Implementation

![image](https://user-images.githubusercontent.com/7792033/209311002-69edadd8-3abd-4990-9b08-1fb2a5276704.png)

#### Proposal

The idea would be to either include an option or switch the default behavior to an icon-based display exclusively.

This would easily allow up to half a dozen (if not more) tabs to be displayed at once.

Here is a rough mock-up. It is mostly missing a "current tab" indicator of some sort; a small dot/bar below the icon, maybe? Or a background/border highlight?

##### Proposed Implementation

![image](https://user-images.githubusercontent.com/7792033/209307785-80c82b04-7a20-42e0-b195-f90ff10991e4.png)

### Requirements

- Change the Properties menu's tab design to be icons only.
- Remove the roll-over tabs menu, unless the UI is unable to display all tabs at once.
- (Optional) Set an option to toggle between the current and proposed behavior.

### Files Version

Version: 2.4.8

### Windows Version

Windows 11 22621.963

### Comments

Not including the tab title may present a slight reduction in first-use user experience; however:

1. This is a "more advanced" use of Files (meaning most users will tend to be familiar with the UI/UX at this point)
2. The hover title should be intuitive enough if it appears rapidly.

This is standard behavior in other parts of the UI:
![image](https://user-images.githubusercontent.com/7792033/209309325-aa44bcc2-ce6d-4c18-b139-5fed39481eb8.png)

**Comment by yaira2** [comment]
What happens if you resize the window?

**Comment by ELowry** [comment]
> What happens if you resize the window?

Currently, the overflow tabs get put back inline.

However, there are 2 issues with this:

1. The Properties window always defaults to the same size; so you have to resize it every time… which isn't a solution at all.
2. As new tabs get added (and there are 2 in the works, at least that I know of), resizing will become less and less of a viable solution.

**Comment by yaira2** [comment]
This was resolved in `main`.
