### ISSUE TITLE
Is Files free?

### ISSUE THREAD

**Issue by ShahriarKh** [files-community/Files#10830]
### Description

In the website, it says:

> Files is **free** and open source software, maintained and designed by a collective of hundreds of contributors.

But in Microsoft Store, the app is $1.99:  

![image](https://user-images.githubusercontent.com/31452340/209345993-97542f36-b500-47f7-bcbe-b37aec77ddd4.png)

I'm confused.

### Steps To Reproduce

-

### Steps to fix

-

### Files Version

-

### Windows Version

-

### Relevant Assets/Logs

-

**Comment by yaira2** [comment]
Files is available for free if you download the sideload version. This is mentioned in the stores description as well.

**Comment by ShahriarKh** [comment]
Yeah I downloaded the sideolad version and it's a great app! I was just wondering why the store version is premium.

**Comment by ShahriarKh** [comment]
Got it. Thanks for your fast reply!
