### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Raupy10** [files-community/Files#10838]
### Description

My Files App has an update, but every time i want to install it, it says: "Files has a problem that the developers were not prepared for."
Can you please fix this?
thanks

### Steps To Reproduce

1. open the app Files
2. click on the blue download button in the up right corner
3. Files will now send you a message, that there is a problem and crashes.

### Steps to fix

Fix crash that occurs when the download button which is available as soon as a new update is available is clicked.

### Files Version

Version: 2.4.4.0

### Windows Version

Windows 11 22H2 22621.963

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10298558/debug.log)

**Comment by QuaintMako** [comment]
This has been fixed with #10795 and in 2.4.8 I believe?

**Comment by Raupy10** [comment]
i dont know, but it is still there

**Comment by Raupy10** [comment]
I also can't update to the new version.
Or do you have to download it from the internet?

**Comment by Josh-65** [comment]
You can update from https://files.community/download
