### ISSUE TITLE
Icon Suggestion

### ISSUE THREAD

**Issue by foursplaysroblox** [files-community/Files#10836]
### What feature or improvement do you think would benefit Files?

I suggest files getting a new icon from windows 10X which it looks good in my opinion

### Requirements

- Changes the icon of Files
- Uses the Windows 10X file explorer icon
- adds the preview badge if downloaded the preview versions

### Files Version

Version: 2.4.8.0

### Windows Version

Windows 11 22H2 Dev Build 25267.1000

### Comments

Should look like this
![File Explorer](https://user-images.githubusercontent.com/82078139/209425075-f595f45d-8d88-498a-9bbb-4b796ad4ce90.png)

**Comment by Josh-65** [comment]
Files is not File explorer. Having the icons pretty much the same is also confusing

**Comment by foursplaysroblox** [comment]
can you change icons for ms store apps?

**Comment by Josh-65** [comment]
Unless you switch the icons file and build the app yourself no.
