### ISSUE TITLE
OnGoing task icon display error

### ISSUE THREAD

**Issue by elicec** [files-community/Files#10842]
### Description

![image](https://user-images.githubusercontent.com/9591680/209532101-aa93ab7e-aa0a-471c-9078-98e45fde7549.png)
OnGoing task icon display error

### Steps To Reproduce

1 copy a file to other path

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

Version: 2.4.8.0 OS Version: 10.0.19044.2364

### Windows Version

Windows 10 21H2 19044.2364

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/9591680/209532567-f7c6edb4-197c-48db-a328-dbe862f08524.png)

**Comment by Josh-65** [comment]
There is no issue shown

**Comment by yaira2** [comment]
They are referring to the missing check mark. Seems to be a WinUI issue but as long as the correct color is shown I think it's okay.
