### ISSUE TITLE
Format option missing in context menu of drives in overview.

### ISSUE THREAD

**Issue by RedIODev** [files-community/Files#10840]
### What feature or improvement do you think would benefit Files?

The format option is a core feature of a file explorer. The ability to format usb sticks, sd cards and hard drives is crutial. The current workaround for me is the location list on the left where you can access the format drive option, I think it's confusing to have 2 different context menus for the same item (drives on the sidebar and drives on the main overview).

### Requirements

No requirements

### Files Version

Version: 2.4.8.0 OS Version: 10.0.19045.2364

### Windows Version

Windows 10 22H2 19045

**Comment by hecksmosis** [comment]
This already exists under more.../Format

**Comment by Josh-65** [comment]
Merging with #5888
