### ISSUE TITLE
preview

### ISSUE THREAD

**Issue by chezfo** [files-community/Files#10848]
### What feature or improvement do you think would benefit Files?

Preview pane, should display the actual files. As in the original Windows Explorer.
I don't think it's a luxury!

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

גירסה 2.4.8.0 OS Version: 10.0.22621.963

### Windows Version

Windows 11 Pro 22H2 ‏‏

### Comments

This is how it is in your version, compared to the Windows version
![image](https://user-images.githubusercontent.com/85172877/209587441-72d750a3-fed5-4ced-a684-abcc920889bc.png)
![image](https://user-images.githubusercontent.com/85172877/209587445-4e491ac8-3c99-4212-9d67-d33eb3674b98.png)

**Comment by gave92** [comment]
#4041

**Comment by yaira2** [comment]
@chezfo we're currently tracking this in #4041, in the meantime, Files has an integration with QuickLook if you're interested in trying that out.
