### ISSUE TITLE
Installer fails (0x80070005)

### ISSUE THREAD

**Issue by MangoMango666** [files-community/Files#10851]
### Description

Hello.
I just tried installing Files and the installation fails.
The error message (translated from French) is "App installation failure with error message : unspecified error (0x80070005)".

OS : Windows 10 Enterprise version 21H2 , 
Files version 2.4.8.0 , downloaded from https://files.community/download choosing 'Sideload' (the software center is managed by my employer's IT department )

I tried several times and it happened every time.

### Steps To Reproduce

 - Get a computer with Windows 10 (ar at least, mine)
 - Try installing Files

### Steps to fix

Sorry, I have no idea. I can help with the diagnostic if someone tells me how, though.

### Files Version

2.4.8.0

### Windows Version

Windows 10 Enterprise version 21H2

### Relevant Assets/Logs

Sorry. I have none.

**Comment by yaira2** [comment]
What happens if you restart Windows?

**Comment by MangoMango666** [comment]
> What happens if you restart Windows?

I tried : nothing special. The app is not installed and trying to install it produces the same result again.

**Comment by Josh-65** [comment]
You can try running these in an admin CMD terminal then restart when there finished.
sfc /scannow
dism /online /cleanup-image /restorehealth

**Comment by MangoMango666** [comment]
> You can try running these in an admin CMD terminal then restart when there finished. sfc /scannow dism /online /cleanup-image /restorehealth

I don't have the admin rights on this computer, managed by the company. Is it not possible to install Files as a regular user under Windows ?

**Comment by Josh-65** [comment]
Since your on a company computer they properly disabled the stuff App install needs to work.
