### ISSUE TITLE
DrivesWidget -> DrivesWidgetMoreOptionsButton isn't accessible / is hidden

### ISSUE THREAD

**Issue by benny779** [files-community/Files#10858]
### Description

When the grid is stretched from side to side, the "additional options" button cannot be clicked.
![image](https://user-images.githubusercontent.com/75434503/209789713-77235290-1a30-4c8c-a2c3-c631855e651b.png)
![image](https://user-images.githubusercontent.com/75434503/209789195-abd5b007-ac58-4aeb-ab39-a0a231cab547.png)

### Steps To Reproduce

1. Go to Home.
2. Resize the window so that the grid is stretched from side to side.

### Steps to fix

Option 1: Set max width of the grid.
Option 2: Move the button to the "Group Header" (before the arrow)

### Files Version

Version: 2.4.8.0 OS Version: 10.0.19044.2006

### Windows Version

Windows 10 Pro 21H2 19044.2006

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10313382/debug.log)

**Comment by hecksmosis** [comment]
I can reproduce this

**Comment by hecksmosis** [comment]
@yair100 Can you approve this?

**Comment by yaira2** [comment]
We need to make some changes to widgets before this can be fixed.

**Comment by Josh-65** [comment]
This has been fixed in 2.4.33.0
