### ISSUE TITLE
Files 2.4.8 crashes when user immediately opens a new tab inside the current folder after loading

### ISSUE THREAD

**Issue by Hawksprey420** [files-community/Files#10856]
### Description

I've been noticing this weird pattern in both Files, Files Preview, and Files Dev that wherever I open some folders inside my Desktop, Documents, etc., or even the drive folders, then if I open a subfolder immediately after the folder has been loaded, two things would happen. 
One is that it would proceed as normal, and let me do my work.
Two is that it would immediately crash the app and restart.

Another sub-behavior is that, when I try to do the same thing on the app restart, it either does the same thing again or proceeds as stable. This would happen on random occasions when I try to do it.

I did some poking around Event Viewer to see what dependency was the culprit in crashing the app, and without fail, it's Microsoft.UI.Xaml.dll that's causing the crash every time.

Here's a sample of Event Viewer logs:
Faulting application name: Files.exe, version: 1.0.0.0, time stamp: 0x6377ba57
Faulting module name: Microsoft.UI.Xaml.dll, version: 3.0.0.2212, time stamp: 0x7dc2efab
Exception code: 0xc000027b
Fault offset: 0x00000000007cd8ec
Faulting process id: 0x0x6654
Faulting application start time: 0x0x1D91A7A87965819
Faulting application path: C:\Program Files\WindowsApps\49306atecsolution.FilesUWP_2.4.8.0_x64__et10x9a9vyk8t\Files.App\Files.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.2_2000.707.2303.0_x64__8wekyb3d8bbwe\Microsoft.UI.Xaml.dll
Report Id: 0ed41aa5-461f-4913-a3fa-5b3bbe2e2786
Faulting package full name: 49306atecsolution.FilesUWP_2.4.8.0_x64__et10x9a9vyk8t
Faulting package-relative application ID: App

### Steps To Reproduce

1. Open the Files app on your PC.
2. Then open a folder in a new tab (Documents, drive, anything that has a lot of folders)
3. Immediately, after it loads, open your desired folder again, in a new tab.

Video reproduction:
AUDIO WARNING: PLEASE MUTE THE AUDIO ON SOME FOOTAGES. I don't want to destroy your ears.

https://drive.google.com/file/d/14-VR3bMmNg-VxxK-7hMwJUdtfAYvgInU/view?usp=share_link
Normal behavior when I did the steps to reproduce the issue.

https://drive.google.com/file/d/1aeXKV253tfQZrFhPJA0TfAVPN0W_jQ_M/view?usp=sharing
The buggy behavior. (it's handheld footage because it won't show under OBS 🤣 )

### Steps to fix

Not applicable.

### Files Version

2.4.8.0

### Windows Version

Windows 11 Dev Channel Build Version	10.0.25267

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10312274/debug.log)

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by Hawksprey420** [comment]
> Is this still an issue in the preview version? https://files.community/download/preview

As of now @yair100 , in Version: 2.4.12.0, I haven't reproduced the bug yet.
Will let you know once I have done it again
