### ISSUE TITLE
Adding multiple folders to Bundles will save only one

### ISSUE THREAD

**Issue by hscshuai** [files-community/Files#10857]
### Description

Adding multiple folders to Bundles will save only one.You can only continue adding once you restart, but still only add one.English is not good, partly with the help of translation.thanks.

### Steps To Reproduce

1、Create bundle
2、Add item...
3、Add folder

### Steps to fix

Hopefully, you can add folders as normal.

### Files Version

Files:2.4.8.0    Window:19045.2364

### Windows Version

Windows 10 22H2

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10313320/debug.log)

**Comment by gave92** [comment]
Thanks for the report. Closing as bundles feature is being rebuilt in #9587
