### ISSUE TITLE
Copied directory is there but it does not exist

### ISSUE THREAD

**Issue by simsrw73** [files-community/Files#10862]
### Description

I copied a directory from my $HOME\.config directory to $APPDATA directory. It appears in that directory. I can navigate in to it. Leave and comeback and it's still there. But it is not present in Windows Explorer nor when I navigate to it from the command prompt. The address bar shows "C:\Users\simsrw73\AppData\Roaming\bat". But that directory doesn't exist in the real world. Only in Files. I don't understand what I'm seeing. There are no links or anything that I can see.

![Files](https://user-images.githubusercontent.com/12434447/209839919-35552635-47cc-4ac1-b45c-ccfaa6556752.png)

### Steps To Reproduce

Copy directory from %userprofile%\.config
Paste directory in to %appdata%
Check command prompt or Windows Explorer. Directory does not exist.

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

Version: 2.4.8.0 OS Version: 10.0.22621.963

### Windows Version

W11 Pro 10.0.22621.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10315127/debug.log)

**Comment by gave92** [comment]
Ehehe writes to appdata get redirected to %LocalAppData%\Packages\Files_1y0xx7n9077q4\LocalState. Still looking for a fix. Merging with #9210.
