### ISSUE TITLE
Bug: Bitdefender is missing in the right click context menu

### ISSUE THREAD

**Issue by UNDERNAUT** [files-community/Files#10866]
### Description

Hello,
It seems that my application is not present in the right click context menu.

default context menu:
![image](https://user-images.githubusercontent.com/121576559/209860297-8b4174bd-8c88-4a08-be49-cb3d2e76d63f.png)

Files context menu:
![image](https://user-images.githubusercontent.com/121576559/209860349-ebcb292a-0fdc-493c-a083-c9eaac60d1b7.png)

### Steps To Reproduce

Use Bitdenfender total security

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

- Solution to add it

### Files Version

Version : 2.4.8.0 OS Version: 10.0.19044.2364

### Windows Version

Windows 10 21H2 19044.2364

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10316272/debug.log)

**Comment by Josh-65** [comment]
Can you please upload the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.

**Comment by UNDERNAUT** [comment]
I add it

**Comment by gave92** [comment]
Also #2431, issue specific to bitdefender.

**Comment by yaira2** [comment]
What are they doing differently?

**Comment by yaira2** [comment]
@dahall do you have any ideas on fixing this?

**Comment by yaira2** [comment]
Maybe the same as #8251?

**Comment by gave92** [comment]
Nope because the report is about Windows 10.

**Comment by dahall** [comment]
> Maybe the same as https://github.com/files-community/Files/issues/8251?

Even though the Windows versions are different, I believe this all has to do with how the context menu is registered and how `Files` is pulling those from the registry.

**Comment by gave92** [comment]
A good way of checking is looking at explorer++. If they are able to show it then we should be able as well.

**Comment by yaira2** [comment]
@UNDERNAUT can you check this out?

**Comment by UNDERNAUT** [comment]
Hello,
It seems that explorer++ isn't able to show Bitdefender context menu.
Thank you for your help and sorry for waiting.
![image](https://user-images.githubusercontent.com/121576559/216814282-df8ca9fc-3c6e-451c-a921-e6d4125633f1.png)

**Comment by yaira2** [comment]
Sorry for the long delay, it appears that this issue is with Bitdefender and not Files. It's possible that they did this by design but it's hard to know for sure.
