### ISSUE TITLE
Show all six Folders' Titles in Dual Pane Mode

### ISSUE THREAD

**Issue by sleeper0993** [files-community/Files#10861]
### What feature or improvement do you think would benefit Files?

When there is just one pane displayed, the layout has 6 Folders listed and then all the computers drives below that. Those folders have icons with the titles: Desktop, Documents, Downloads, Music, Pictures, Videos.

When one switches to Dual Panes, all 6 of the icons are displayed for the folders, but the titles for the Documents and Downloads folders disappear and are replaced by 3 dots. I'm guessing that the length of these folders' titles, being 2 characters longer than any of the others, don't fit under Dual Pane Mode. 

### Requirements

This could be done by abbreviating or truncating those folders' titles or at least allowing the option to do that. Possibly the full name could also be displayed by hovering the mouse over the folder's icon.

### Files Version

Version 2.4.8

### Windows Version

Windows 11 21H2

**Comment by yaira2** [comment]
This really depends on the windows size, in any case, we're tracking this in #1033
