### ISSUE TITLE
Add a selection checkbox for better ux

### ISSUE THREAD

**Issue by lorisobi** [files-community/Files#1086]
![image](https://user-images.githubusercontent.com/28399150/84752203-bba42d00-afbd-11ea-9257-a30f43578b4d.png)
 In Windows Explorer you have checkboxes, which show up on hover, to select files and folders.
This feature should be added to Files too, because it implicates users how to select files and enhances the usability and user experience..

**Comment by Jaiganeshkumaran** [comment]
This can be optional feature since it's optional in File Explorer too.

**Comment by lorisobi** [comment]
is it in windows explorer on by default?

**Comment by Jaiganeshkumaran** [comment]
It’s enabled by default only on touchscreen devices.

**Comment by yaichenbaum** [comment]
Merging with #290.
