### ISSUE TITLE
Crashes when i apply a file on a new tag

### ISSUE THREAD

**Issue by swanbroq68** [files-community/Files#10860]
### Description

It crashes when i apply files to a new tag
Thanks for fixing it

### Steps To Reproduce

1. Go to the script
2. Code something that make creating tags simpler
idk how to fix so ur turn

### Steps to fix

Fix crash that occurs when i apply a file on a new tag then make creating tags simpler

### Files Version

Files 2.4.8

### Windows Version

Windows 11 22H2 Build 22621.963

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/118814524/209814736-57eefeeb-59eb-437e-8c8b-399755af015c.png)
![Capture d'écran_20221228_122700](https://user-images.githubusercontent.com/118814524/209814751-9cb9705b-dc75-4844-be29-27a043f2d20c.png)

**Comment by hecksmosis** [comment]
Can you include the debug.log file?

**Comment by hecksmosis** [comment]
You can find it in Settings / About / Open log location

**Comment by gave92** [comment]
Please also attach the tag file.
