### ISSUE TITLE
Opening is slow

### ISSUE THREAD

**Issue by MinhazurSarker** [files-community/Files#10868]
I just installed it and it's opening time slower than the existing Explorer app. Looking forward

**Comment by yaira2** [comment]
Merging with #4180

**Comment by yaira2** [comment]
We're excited to share that startup performance will be significantly improved in the upcoming release of version 3. You can download the preview version from our website https://files.community/download.

**Comment by yair100** [comment]
@MinhazurSarker we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
