### ISSUE TITLE
Microsoft Store

### ISSUE THREAD

**Issue by MasterChief177** [files-community/Files#10877]
So, I used Files for quite a while now and downloaded Files from Microsoft Store. But for some reason it didn't work any more and I noticed that it had a price on Microsoft Store and I bought it but still didn't work. Thereafter, I installed from the website, and now it works. But I don't know if this was intended, if so, why did I not get any notification? I thought that this project was free, maybe we were notified, but I didn't see it.

**Comment by Josh-65** [comment]
The store price is a way of donating to the developer. It says it free in the description of the store. If you have already gotten it on the store then it would be free to download on there.

**Comment by MasterChief177** [comment]
Sorry, I didn't see it.

**Comment by yaira2** [comment]
@MasterChief177 you can download the sideload version from https://files.community

**Comment by MasterChief177** [comment]
I already have it, but thanks.

**Comment by yslupdates** [comment]
I'm currently on a lower version that what's currently latest on github. How can I get MS Store to update to latest or does it take a while for them to get it out to users?

Version: 2.4.8.0
OS Version: 10.0.22000.1335

**Comment by Josh-65** [comment]
Go to the MS store and check for updates.

**Comment by yslupdates** [comment]
Yes I've tried doing that and no new update comes up. My last update/modified date was 12/22/22

**Comment by yaira2** [comment]
We're still waiting for the release to be approved by Microsoft.
