### ISSUE TITLE
Turn Folder into File Bug

### ISSUE THREAD

**Issue by Omegion2** [files-community/Files#10871]
### Description

I turn the Folder into File
![image](https://user-images.githubusercontent.com/82105977/209962253-718f890c-8f21-4bcf-8616-55fc8680c2a7.png)
Which that wasn't happened at all!

### Steps To Reproduce

1. Right Click on the Folder
2. Edit/Add File Tags
3. Click Any of Colors.

### Steps to fix

- Fix the File Tags, that was Turn Folder into File. (For Developers of Files)
- Switch to File Explorer (For Normal User)

### Files Version

Version: 2.4.8.0 (Store) OS Version: 10.0.25252.1010

### Windows Version

Windows 11 Build 25252.1010

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10319766/debug.log)

**Comment by Josh-65** [comment]
If you open the folder in File explorer are they still shown as files

**Comment by Omegion2** [comment]
no, just normal folder in file explorer

**Comment by yaira2** [comment]
@Josh-65 Alternative Data Streams maybe?

**Comment by Josh-65** [comment]
Not sure what your asking, but if it was an ADS file then the folder should show in font of it (folder name:ADS_name) and the folder should still be visible.
They could try turn on `Files settings > Folders > Hidden items > Show Alternative Data Streams` and see what it shows like.

**Comment by yaira2** [comment]
@Omegion2 is this still an issue in v2.4.21?

**Comment by Jaysin08** [comment]
Stop emailing me
