### ISSUE TITLE
File Falla

### ISSUE THREAD

**Issue by Mariepiz** [files-community/Files#10883]
### Description

El programa se cierra
![image](https://user-images.githubusercontent.com/101369384/210024986-fd4a4711-7752-483e-9614-d347336c02a0.png)

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/101369384/210024993-786894c1-0acb-4232-aa89-de5c6fed638d.png)

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...
![image](https://user-images.githubusercontent.com/101369384/210025004-58411803-1608-415f-9ae2-7ef6c7e9c2d3.png)

### Files Version

Versión: 2.4.8.0 OS Version: 10.0.19044.2364

### Windows Version

Windows 10 Home 21H2 19044.2364

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10322707/debug.log)

**Comment by Josh-65** [comment]
Merging with #10881
