### ISSUE TITLE
Make app icon more fluent

### ISSUE THREAD

**Issue by SteveWorkshop** [files-community/Files#10887]
### What feature or improvement do you think would benefit Files?

I feel that Files' app icon is not so consistent with Fluent Design.
I don't like win11's explorer icon which is a big retrogress from win10. So File's icon doesn't need to follow that one.
Win10's icon or Win10x's one is just good!

### Requirements

- This proposal will use win10 or 10x's explorer icon as app icon

### Files Version

2.4.10.0

### Windows Version

win11 22623.1037

**Comment by Josh-65** [comment]
Files cant use the same icon as File explorer. That is confusing for users and most likely not allowed by Microsoft.

**Comment by SteveWorkshop** [comment]
> Files cant use the same icon as File explorer. That is confusing for users and most likely not allowed by Microsoft.

OK, I know it, a...huh, 😅, I mean to modify it based on win10X... not just copy that...

**Comment by yaira2** [comment]
We're happy with Files icon but you're welcome to share concepts.
