### ISSUE TITLE
File se cierra constantemente al estar trabajando 

### ISSUE THREAD

**Issue by Mariepiz** [files-community/Files#10881]
### Description

Aparece un mensaje que indica ha ocurrido un fallo y se cierra 

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/101369384/210024568-048e05f0-3820-450d-8698-495591751e3f.png)

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

Versión: 2.4.8.0 OS Version: 10.0.19044.2364

### Windows Version

Windows 10 Home 21H2 19044.2364

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10322698/debug.log)

**Comment by Josh-65** [comment]
Can you please fill out the step to reproduce your issue. A screenshot of the about page is not useful.
