### ISSUE TITLE
Feature: Improving the recycle bin experience

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#1089]
- [ ] Recycle bin could also use different icons for when it's empty or not #9195
- [x] I was testing file restoration, and all are restored without extension
- [x] Show original location for items in the recycle bin
- [ ] #9946

**Comment by SOI7** [comment]
Apart from the obvious need of an Empty Bin and a Restore File function, one grip I have with the Recycle Bin atm is that it gets lost inside the libraries tree, and since it's not a regular folder, it should be inside a separatde area, maybe either like the Drives section or ditching the library layout and use it as a simple button somewhere

**Comment by gave92** [comment]
Thanks for the feedback.
Both "Empty Bin" and "Restore File" functions are already available (through right click context menu).
After the latest modifications the recycle bin link on the sidebar will appear as the second item (right after th quick access/home link) but this can problably be improved 👍

**Comment by XPoppyX** [comment]
I think an option to empty the recycle bin from the sidebar

**Comment by gave92** [comment]
@XPoppyX perhaps a "empty bin" button on the topbar would be better? Like instead of the disabled "plus" button.

You're right the recycle bin changing position on the sidebar is not ok. I guess it should either be always at the bottom or in a separate section.

**Comment by XPoppyX** [comment]
> perhaps a "empty bin" button on the topbar would be better? Like instead of the disabled "plus" button.

I want to avoid having to open the recycle bin first to be able to empty

**Comment by gave92** [comment]
I see so perhaps an option to emtpy the bin when you right click on the recycle bin entry on the sidebar

**Comment by yaichenbaum** [comment]
When deleting and item or emptying recycle bin, there should be a confirmation dialog.

**Comment by SOI7** [comment]
Recycle bin could also use different icons for when it's empty or not. Also, right now I need to refresh it to see changes after emptying it

**Comment by XPoppyX** [comment]
I was testing file restoration, and all are restored without extension

when it is deleted:
![Anotación 2020-06-28 090022](https://user-images.githubusercontent.com/61259627/85948263-ea0afc00-b91d-11ea-8eb8-7da3d21f86f1.png)

after restoring:
![Anotación 2020-06-28 090100](https://user-images.githubusercontent.com/61259627/85948265-eb3c2900-b91d-11ea-92b2-9ca7e09cf271.png)

**Comment by tsvietOK** [comment]
@XPoppyX Can't reproduce, v0.11

**Comment by XPoppyX** [comment]
![restore](https://user-images.githubusercontent.com/61259627/85948960-d2357700-b921-11ea-9f9f-338ced642669.gif)

**Comment by stamminator** [comment]
> * And maybe disable "properties" from the context menu, because it doesn't show anything useful about the recycle bin.
I agree. In fact, in my version (v0.11.0.0, Windows 10 2004 19041.329), selecting "properties" causes the entire app to crash. I didn't submit a bug report because @XPoppyX's suggestion would render it moot.

**Comment by gave92** [comment]
@stamminator Properties menu for recycle bin was recently removed (in #1264) 👍

**Comment by yaichenbaum** [comment]
Thank you for all your feedback, some of the mentioned have since been addressed but here are some of the ones that were not yet addressed that we think should be solved before closing this issue

- [ ] Recycle bin could also use different icons for when it's empty or not. Also, right now I need to refresh it to see changes after emptying it
- [ ] I was testing file restoration, and all are restored without extension

**Comment by ericcornelissen** [comment]
> 
> 
> > perhaps a "empty bin" button on the topbar would be better? Like instead of the disabled "plus" button.
> 
> I want to avoid having to open the recycle bin first to be able to empty

I would still like to see a button in the top bar to empty the recycle bin to be honest, in addition to the option in the right-click menu.

**Comment by crashmit** [comment]
Would it be possible to also put in a "Date Deleted" category? The Date Modified usually doesn't help there and I mostly restore items, I deleted recently. Would improve UX a lot for me to be able to sort by "Date Deleted"

**Comment by yaichenbaum** [comment]
> Would it be possible to also put in a "Date Deleted" category? The Date Modified usually doesn't help there and I mostly restore items, I deleted recently. Would improve UX a lot for me to be able to sort by "Date Deleted"

This was just implemented with #2892.

**Comment by crashmit** [comment]
Oh perfect, thank you!

**Comment by mdtauk** [comment]
Could the Recycle Bin be Pinned to the sidebar, maybe above the Settings at the bottom of the sidebar?

**Comment by KAMiKAZOW** [comment]
> I want to avoid having to open the recycle bin first to be able to empty

A button in the toolbar would still be nice when I already have the trash open.

**Comment by lukeblevins** [comment]
@yair100 Wondering if there are any updates we can make to this issue's description. For instance, has the missing item extensions on restore bug been fixed?

**Comment by yaichenbaum** [comment]
@duke7553 As of now, nothing has changed with the issue.

**Comment by BanCrash** [comment]
In last commit version, when you enter on the empty recycle bin after one directory with files, it will show the account of files on the previous directory instead "0 items":

![image](https://user-images.githubusercontent.com/11770760/125354405-0d0b2100-e364-11eb-93b3-8ed312620290.png)

However, if you enter a non-empty recycle bin and after that, you clean it, it will show "0 items":

![image](https://user-images.githubusercontent.com/11770760/125354353-fd8bd800-e363-11eb-94f9-1aded627e238.png)

![image](https://user-images.githubusercontent.com/11770760/125354309-f06ee900-e363-11eb-9495-93f826090522.png)


To reproduce: 
1- Clean the recycle bin.
2- Go to another folder that has files inside.
3- Go back to the recycle bin. It will show the amount of items on the previous folder instead 0.

Version: Last commit
OS Version: 10.0.19043.1081

Logs:
[debug_fulltrust.log](https://github.com/files-community/Files/files/6804299/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/6804300/debug.log)

**Comment by cinqmilleans** [comment]
@yair100 @gave92 @SOI7 @mdtauk @ericcornelissen @lukeblevins @Rick-HM @tsvietOK @stamminator @crashmit @KAMiKAZOW Here is a suggested placement of the Recycle Bin. It can be placed as a section between Home and Favorites.
- The recycle bin always accessible even if the favorites are folded.
- Highlights the recycle bin, which cannot be reached like a regular folder.
- Doesn't take up more space than it currently does, unless the bookmarks are folded up.
- The display of the recycle bin is no longer a specific option, but a section like the others, which can be displayed with the contextual menu of the sidebar.
- It can increase clutter if the user has a lot of section.

What do you think ?

![RecycleBin_Project](https://user-images.githubusercontent.com/46631671/178120719-0db1bb06-adeb-4819-b7df-24a1128c417d.png)

**Comment by yaichenbaum** [comment]
I'm not a fan of that design, recycle bin should be treated the same as other favorites.

**Comment by yaichenbaum** [comment]
I'm not a fan of that design, recycle bin should be treated the same as other favorites.
