### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by CloudPeep** [files-community/Files#10895]
### Description

Have tried to download Files from various sites (including microsoft store) and repeatedly get this error:

App installation failed with error message: error 0x80070005: Opening the package from location Files.Package_2.4.11.0_x64_ARM64_Sideload.msixbundle failed. (0x80070005)

### Steps To Reproduce

Execute the install file

### Steps to fix

Installation

### Files Version

2.4.11.0_x64

### Windows Version

Windows 11 Pro 10.0.22000 Build 22000

### Relevant Assets/Logs

Cannot get to this as I am unable to even install the app

**Comment by Josh-65** [comment]
Your Windows install is outdated. Try update Windows and try again

**Comment by Josh-65** [comment]
Download the file from https://files.community/download and place it in a none restricted area like your desktop.
If that doesn't work try update Windows since your version is outdated.
If that doesn't work try running these in an admin CMD terminal then restart when there finished.
sfc /scannow
dism /online /cleanup-image /restorehealth

**Comment by CloudPeep** [comment]
Thanks for your help.

I just checked, and Windows says its up to date.

[image: image.png]

Allan

**Comment by CloudPeep** [comment]
Have done all of these and still get the same error.

Allan

**Comment by Josh-65** [comment]
Are you able to install other apps from the MS store?

**Comment by CloudPeep** [comment]
Yes

**Comment by yaira2** [comment]
Are you installing from the appinstaller file?

**Comment by CloudPeep** [comment]
I have tried to install from the Microsoft Store and the installer
Neither work unfortunately

**Comment by yaira2** [comment]
Which installer?

**Comment by CloudPeep** [comment]
The sideload at https://files.community/download

[image: image.png]



[image: image.png]
Allan Glogauer
Producer

+27 (0)82 450 7151
***@***.***

**Comment by yaira2** [comment]
The msixbundle is the wrong installer, can you verify the file name?

**Comment by CloudPeep** [comment]
Files.Package_2.4.11.0_x64_ARM64_Sideload

Allan Glogauer
Producer

+27 (0)82 450 7151
***@***.***

**Comment by yaira2** [comment]
That's not the installer from https://files.community/download. It should be `Files.Stable.appinstaller`

**Comment by CloudPeep** [comment]
I managed to download the installer but not get this:

[image: image.png]

Allan

**Comment by Josh-65** [comment]
You cant attach an image via email. You have to copy and paste the error message

**Comment by CloudPeep** [comment]
The error message just says


This app can't run on your PC
To find a version for your PC, check with the software publisher

Allan Glogauer
Producer

+27 (0)82 450 7151
***@***.***

**Comment by Josh-65** [comment]
What's the name of the file you are running?

**Comment by CloudPeep** [comment]
files-2.1.13-installer; from FileHippo.


Allan Glogauer
Producer

+27 (0)82 450 7151
***@***.***

**Comment by Josh-65** [comment]
That's not the file you should be running and is outdated. Use the one from https://files.community/download called sideload or the MS store

**Comment by CloudPeep** [comment]
I've tried that.

In the file save dialogue box, it is called Files.stable.

However, when it downloads, it appears names as the file I should have -
Files.stable.appinstaller

When I try to run it I get:
Cannot open app package
Reason:
An error occurred while accessing the file from the web. Please try
downloading and opening the file locally.

Allan

**Comment by Josh-65** [comment]
Try right clicking the file, open properties and see if there is an unblock button.
If not unblock App installer from network access in any security programs you have running.

**Comment by Josh-65** [comment]
Never mind use the preview version listed on the site as the stable one seem to be broken

**Comment by CloudPeep** [comment]
There is no unblock button.

I have temporarily turned off my security programs, and gone offline, and
get:

App Installer failed to retrieve app information. Either the network
connection has been lost or the server cannot be reached. (0x80072EE7)

Have gone back online, and disabled virus protection and get:
An error occurred while accessing the file from the web. Please try
downloading and opening the file locally.
Allan Glogauer
Producer

+27 (0)82 450 7151
***@***.***

**Comment by CloudPeep** [comment]
I tried the preview version and get:
App installation failed with error message: error 0x80070005: Opening the
package from location Files.Package_2.4.14.0_x64_ARM64_Sideload.msixbundle
failed. (0x80070005)

Allan Glogauer
Producer

+27 (0)82 450 7151
***@***.***

**Comment by Josh-65** [comment]
You can try 
1. Open PowerShell as admin
2. Run this command Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/preview/Files.Package.appinstaller

**Comment by CloudPeep** [comment]
That seems to have downloaded the file.

Where on my PC do I find it?


Allan Glogauer
Producer

+27 (0)82 450 7151
***@***.***

**Comment by Josh-65** [comment]
You shouldn't download a file you should run the command in full in an admin PowerShell window.

**Comment by CloudPeep** [comment]
OK, sorry, not familiar with that. Not sure how to do it.

Allan Glogauer
Producer

+27 (0)82 450 7151
***@***.***

**Comment by Josh-65** [comment]
Type PowerShell in the start menu
Right click then run as administrator
copy and paste   Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/preview/Files.Package.appinstaller
Then press enter.

**Comment by CloudPeep** [comment]
Thanks, I did that part but nothing happened.


Allan Glogauer
Producer

+27 (0)82 450 7151
***@***.***

**Comment by Josh-65** [comment]
Have you check the app list in the start menu

**Comment by CloudPeep** [comment]
Thanks. That now seems to have worked

Allan Glogauer
Producer

+27 (0)82 450 7151
***@***.***
