### ISSUE TITLE
When you click on a local folder, an error is reported.

### ISSUE THREAD

**Issue by chengnan661** [files-community/Files#10894]
### Description

When you click on a local folder, an error is reported.
Or there is no response when pointed.
The premise is that the "Default Folder" is turned on.

### Steps To Reproduce

1.Tap Local Folder
2. Open the requested folder where the Files app is located

### Steps to fix

When you click the local folder, you can open the Files app normally

### Files Version

Version: 2.4.11.0 OS Version: 10.0.22000.1335

### Windows Version

win11

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10327247/debug.log)

**Comment by yaira2** [comment]
What's a `local folder`?

**Comment by chengnan661** [comment]
你好，我最近很忙，无法亲自回复你的邮件。会尽快给你回复。谢谢配合！！

**Comment by chengnan661** [comment]
When the desktop folder is opened, files do not respond

**Comment by yaira2** [comment]
@Josh-65 can you reproduce this?

**Comment by Josh-65** [comment]
Assuming that the issue is with opening a folder from the desktop with Files set as default no. Open like it should no error is reported.
