### ISSUE TITLE
Display folder path for search results

### ISSUE THREAD

**Issue by IdkWhatToCallMe123** [files-community/Files#10891]
### What feature or improvement do you think would benefit Files?

If you enter a search query with multiple folder matches, there should be a extra column showing the path. Like in the current version I have to sift through every folder to find the right one, so it would be neat if I could see that info at a glance. 

![Untitled](https://user-images.githubusercontent.com/74187631/210106815-eec36bf5-be72-4aa7-8da2-d02f29c0bfef.png)

### Files Version

Version: 2.4.8.0 OS Version: 10.0.22621.963

### Windows Version

Windows 11 Pro 22H2

**Comment by Josh-65** [comment]
Merging with #7070
