### ISSUE TITLE
Can't install Files 2.4.11 appinstaller

### ISSUE THREAD

**Issue by dexter1100** [files-community/Files#10896]
Sideloading doesn' work with the 2.4.11 appinstaller.
Error message: error 0xC00CEE23: The XML in the .appinstaller file is not valid: Line 51, Column 5, Reason: '>' expected. (0xc00cee23)

This is on Windows 10 pro version: 21H2 Build: 19044.2364

According to this unresolved  bug report: https://techcommunity.microsoft.com/t5/msix/error-0xc00cee23-when-minor-version-gt-10/m-p/1780808  Just don't use minor version numbers greater or equal to 10.

**Comment by Josh-65** [comment]
This is an issue with App installer. Restarting Windows usually works but it not an issue with the version number.
