### ISSUE TITLE
Feature: Append app name to title

### ISSUE THREAD

**Issue by JaiganeshKumaran** [files-community/Files#10899]
### What feature or improvement do you think would benefit Files?

Unlike UWP, setting the window title in WinUI 3 doesn't append the app name. This makes it harder to distinguish a folder window opened in Files from one opened in File Explorer.

### Requirements

When setting title, set it as folder name - Files.

### Files Version

2.4.0.0

### Windows Version

10.0.22000.1335

**Comment by yaira2** [comment]
@JaiganeshKumaran do you want to open a PR?

**Comment by JaiganeshKumaran** [comment]
> @JaiganeshKumaran do you want to open a PR?

Sure.
