### ISSUE TITLE
Bug: Disconnected network drives aren't displayed

### ISSUE THREAD

**Issue by ArtexJay** [files-community/Files#10905]
### Description

Disconnected network mapped drives disappear from the app making it impossible to reconnect the mapped drive from the Files app. Only way to reconnect is by doing it through Windows Explorer.

### Steps To Reproduce

1. Have a mapped drive disconnect from your system. (Typically for me it gets disconnected if I put my laptop to sleep or bring it from one network to another).
2. In windows explorer it will show that it's now disconnected and will allow you to reconnect, while in the Files app it disappears completely.

### Steps to fix

Open the default Windows Explorer and then you will be able to see the disconnected mapped drive there and reconnect. Upon reconnection the mapped drive will show up in Files app.

### Files Version

Version: 2.4.8.0 OS Version: 10.0.25267.1000

### Windows Version

Windows 11 22H2

### Relevant Assets/Logs

Windows Explorer Disconnected Map Drive
![image](https://user-images.githubusercontent.com/32932497/210272934-96fd6b30-a4bc-4c69-a823-05f28224351b.png)

Files App Disconnected Map Drive
![image](https://user-images.githubusercontent.com/32932497/210272956-707fe11c-37c4-4b73-8d60-8478464ac2d7.png)

**Comment by yaira2** [comment]
@ArtexJay do you have the network drive section enabled?

**Comment by ArtexJay** [comment]
> @ArtexJay do you have the network drive section enabled?

There is a network drive section, its not hidden in the files app.

**Comment by ArtexJay** [comment]
The issue is resolved, i haven't encountered any problems now.

**Comment by yaira2** [comment]
@ArtexJay what did you do to resolve it?
