### ISSUE TITLE
Improve code readability and adjust it with code quality standards

### ISSUE THREAD

**Issue by hecksmosis** [files-community/Files#10903]
### Description

There are many parts of the code (especially older ones) where the code quality standards specified on the [website](https://files.community/) are not met (single line if statements use curly braces, #region directives, etc.)

### Concerned code

Most of the codebase, especially older areas.

### Gains

- A better readability

**Comment by yaira2** [comment]
The general idea is to solve things "once we're in there" as opposed to opening a large PR.

**Comment by hecksmosis** [comment]
Ok
