### ISSUE TITLE
Crash when attempting to open a file in Inkscape

### ISSUE THREAD

**Issue by Twentydragon** [files-community/Files#10908]
### Description

When you try to open an Inkscape file, either by double-clicking or by using the Open With menu, Files closes and gives no notice of the crash.

### Steps To Reproduce

1. Make sure you have Inkscape installed.
2. Create an SVG file with Inkscape.
3. Navigate in Files to the SVG file's location.
4. Try to open the SVG file.
5. Observe Files closing itself.

### Steps to fix

Files should not close when attempting to open a file in Inkscape (or an SVG file in general).
Files should produce some kind of pop-up window notifying the user of the crash, rather than just closing.

### Files Version

Version: 2.4.8.0 OS Version: 10.0.19045.2364

### Windows Version

Windows 10.0.19045 Build 19045

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10334027/debug.log)

**Comment by yaira2** [comment]
Is this an issue in v2.4.11? https://files.community/download (use the sideload option)

**Comment by Twentydragon** [comment]
Looks like that's been fixed, but it didn't keep my settings, didn't replace the old version, doesn't have window transparency anymore, and is missing any theme options that aren't flat.

**Comment by yaira2** [comment]
The link I sent was for the sideload version, this release is almost the same as 2.4.8 but it has the fix for this issue. If you wait a couple of days, the update will be released for the store version as well.
