### ISSUE TITLE
Cannot set files as the defaultfile manager

### ISSUE THREAD

**Issue by shenbourne** [files-community/Files#10901]
### Description

If i try to set as default, it will apply for permission to modify the Registry. 
![Snipaste_2023-01-02_12-29-13](https://user-images.githubusercontent.com/121733766/210195315-e695119a-5b54-4ad0-b606-13e0c878462c.jpg)
After I agree it, it’s still disabled.
 
Just like this video:
https://user-images.githubusercontent.com/121733766/210208318-295976b0-12a9-48c6-ae7a-297ceb5587fe.mp4

### Steps To Reproduce

Try to set as default file manager.

### Steps to fix

I dont know how to fix or other methods to achieve it.

### Files Version

Version: 2.4.11.0 OS Version: 10.0.19045.2364

### Windows Version

Windows 10 22H2 19045.2364

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10330623/debug.log)

**Comment by yaira2** [comment]
What happens if you reopen the app?

**Comment by shenbourne** [comment]
> 
 it’s still disabled.

**Comment by shenbourne** [comment]
In fact, after I restart the computer, it still cannot be turned on

**Comment by shenbourne** [comment]
I found that it requested to modify the registry, so are there any onter ways to set it as the default file manager? I'm really fed up with Windows 10 File Explorer

**Comment by yaira2** [comment]
You can make the edits manually but it's not recommended.

**Comment by shenbourne** [comment]
so are there any way deal with it?

**Comment by shenbourne** [comment]
e... I closed this issue by mistake.

**Comment by Josh-65** [comment]
Its not recommend but you can do it manually by opening this https://raw.githubusercontent.com/files-community/Files/main/src/Files.App/Assets/FilesOpenDialog/SetFilesAsDefault.reg > Right click > Save as > set "Save as type" to all files > Remove .txt from end of file name > Run the file

**Comment by Josh-65** [comment]
If this still an issue can you give the following information
1. The name of the installer file you used
2. Where you got the file from

**Comment by shenbourne** [comment]
- The name of the installer file you used:

Files.stable (7).appinstaller

- Where you got the file from:

https://files.community/download
"Sideload"
![Snipaste_2023-01-20_15-16-18](https://user-images.githubusercontent.com/121733766/213638906-ddd9f251-b991-4c45-90fc-f94861e04df3.png)

**Comment by shenbourne** [comment]
> A possible fix you can try is
> Uninstall Files
> Opening PowerShell window as administrator
> Run this command Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/stable/Files.Package.appinstaller
> Open Files and turn the set as default toggle on
> Test if it work

it still didn't work

as the video:

https://user-images.githubusercontent.com/121733766/213642045-526cb34e-c5fe-4563-a7a6-4a0d8cb4d968.mp4

**Comment by Josh-65** [comment]
Did you uninstall Files before running the command

**Comment by shenbourne** [comment]
The last time I uninstalled the software, but it still didn't work.

### Latest version
> Version: 2.4.25.0
> OS Version: 10.0.19045.2486

ps: I Cannot Install the App with "Files.Stable.exe”
![Snipaste_2023-01-25_22-08-43](https://user-images.githubusercontent.com/121733766/214589712-5314c0c0-adaf-4e64-b4c8-0f343e540ecd.png)
This window has remained the same for more than ten minutes.

I could only Install the App with "Files.stable.appinstaller"

**Comment by Josh-65** [comment]
Have you clicked the install button

**Comment by shenbourne** [comment]
I solved this problem by set the account as administrator account.
![image](https://user-images.githubusercontent.com/121733766/214601904-0917570c-16e4-44da-a358-f69547b1e149.png)
(I didn't know why)
