### ISSUE TITLE
[BUG] Cannot drag and drop a file to WhatsApp

### ISSUE THREAD

**Issue by farxhan** [files-community/Files#10909]
### Description

WhatsApp fails to "_obtain_" the file that's dragged and dropped from the Files App. This doesn't happen on other installed programs on my PC like browser or Photoshop, but this might occur on other programs. The original File Explorer can do this job with no problem. The workaround for now is copy the file to clipboard and then paste it on WhatsApp chat field.

I attach a screen recording to illustrate the bug.
https://user-images.githubusercontent.com/67094159/210300054-8bcdcec6-0872-4b59-95e2-17ab0573e959.mp4

### Steps To Reproduce

1. Open a folder that contains a file that you want to share
2. Open a WhatsApp chat
3. Drag the file from Files App and drop it on WhatsApp window
4. The file will not be sent

### Steps to fix

Fix the drag and drop file

### Files Version

Version: 2.4.8.0 OS Version: 10.0.22623.1037

### Windows Version

Windows 11 Education 22H2 22623.1037

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10334329/debug.log)

**Comment by yaira2** [comment]
Merging with #10171

**Comment by bkmikaelo7** [comment]
Just in case someone stumbles here in search of a workaround for whatsapps **drag and drop not recognising audio files as playable in mac os whatsapp desktop app**, I'm glod to tell you that there is a workaround; just **right click the file and select open with -> whatsapp**. After this you select the chat you wish to share in to.  For me this worked.
