### ISSUE TITLE
Feature: Shortcut to open selected folder in Secondary Pane

### ISSUE THREAD

**Issue by Shuaster** [files-community/Files#10907]
### What feature or improvement do you think would benefit Files?

Adding a shortcut to open a folder in the secondary pane would help make the secondary pane more useful, and accelerate its use without having to go into the context menu and selecting the option manually. Similar to the use of Ctrl + Enter to open a folder in a new tab.

### Requirements

- `ctrl` + `shift` + `enter` should open folder in new pane

### Files Version

2.4.8.0

### Windows Version

Version	10.0.22621 Build 22621

**Comment by yaira2** [comment]
This is very reasonable, which shortcut would be a good default?

**Comment by QuaintMako** [comment]
Ctrl+Shift+Enter ?

**Comment by yaira2** [comment]
That's already used for opening in a new tab

**Comment by yaira2** [comment]
That's a good one 👍

**Comment by QuaintMako** [comment]
Looking into it.
