### ISSUE TITLE
Pcloud drive still showing after removal

### ISSUE THREAD

**Issue by smarquespt** [files-community/Files#10906]
### Description

So, I've installed Pcloud on my PC. All good on Files. But now, whem I removed Pcloud from the computer, Files is still showing Pcloud but with a question mark. Not sure if this is a bug or not
![image](https://user-images.githubusercontent.com/1302668/210284054-3f769f69-40ab-402d-8c76-1072866d3ec6.png)

### Steps To Reproduce

1 - Install PCloud
2 - Check files in it
3 - Unistall Pcloud
4 - Check cloud drives

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

Version 2.4.11

### Windows Version

W10 latest

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10333721/debug.log)

**Comment by smarquespt** [comment]
My problem, not Files...

**Comment by yaira2** [comment]
What was the issue?

**Comment by smarquespt** [comment]
Well, apparently when Pcloud was unistalled it wasn't removed from Startup folder. After removal from Startup, it disappeared from Files sidebar.
