### ISSUE TITLE
Bug: Navigating upward from a library leads to wrong folder

### ISSUE THREAD

**Issue by ferrariofilippo** [files-community/Files#10917]
### Description

At the moment, navigating one directory up from a library leads to `C:\Users\<User name>\AppData\Roaming\Microsoft\Windows\Libraries`. I think this is not the correct behaviour. I would expect Files to open default-save-folder's parent.
For example:
- My `Pictures` folder saves in `C:\Users\ffili\Pictures`
- I would expect Files to open `C:\Users\ffili`

Edit. This happens only if the library is opened from the sidebar

### Steps To Reproduce

1. Open a library (Documents, Pictures, Music, ...)
2. Navigate one directory up (Double clicking, Up-Arrow, ...)
3. You are in `Libraries` folder

### Steps to fix

Navigating upward should open library-default-save-folder's parent.

### Files Version

Versione 2.4.8.0 OS Version: 10.0.22621.963

### Windows Version

Windows 11 Home Version 22H2 22621.963

### Relevant Assets/Logs

None

**Comment by yaira2** [comment]
I think this is the intended behavior as libraries can have multiple folders within them.
