### ISSUE TITLE
File App icon mess on Chinese devices

### ISSUE THREAD

**Issue by DMorest** [files-community/Files#10918]
### Description

Hi developers of Files! I'm a user from China and I really love your fluent designs. However recently after I update this app, some of the icons messed up as u can see in the screenshot(fig.1)
![image](https://user-images.githubusercontent.com/103618181/210469369-c0ac41c3-f7d6-470f-a637-b03ed09c50eb.png)

They become kinda unidentified Chinese characters??? I suspect there's something with either my or this app's character mapping, but I can't solve it. Changing the language of the app to English doesn't help as the second screenshot displays (I haven't tried changing my Windows language because I don't want an English OS experience just for this app's icon)
![image](https://user-images.githubusercontent.com/103618181/210469668-841e3ee9-5b0f-417d-b412-c8e4f7b80022.png)

Well, I don't remember having this problem before, it just come up with the new version :(

### Steps To Reproduce

There's no need to process anything, some of the icons on the layout and in the settings panel just messed up :(

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...
Fix the bug that makes the icons display as unidentified Chinese characters!!!

### Files Version

Version: 2.4.8.0 OS Version: 10.0.19044.1706

### Windows Version

Windows 10 21H2 19044.1706

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10340898/debug.log)

screenshotsare displayed in the description

**Comment by Josh-65** [comment]
Merging with #10783
