### ISSUE TITLE
Recent folder

### ISSUE THREAD

**Issue by Asturias76** [files-community/Files#10911]
### What feature or improvement do you think would benefit Files?

Hello, as the recent files, is it possible to have the recent folders used (like in the Windows Explorer) please ?

### Requirements

As described above.

### Files Version

2.4.11

### Windows Version

Windows 10 Pro x64 22H2

**Comment by Asturias76** [comment]
Sorry, my bad, I talked about recent folders in the Quick Access.

![explorer_SrKfN3tYRr](https://user-images.githubusercontent.com/29236723/210607234-f4ff3cd6-20ac-4056-b1f2-cdcdee4b8159.png)

**Comment by yaira2** [comment]
Thank you for the clarification, we don't have plans to display quick access on the sidebar but you can pin regularly accessed locations by right clicking and pressing on "Pin to favorites".

**Comment by Asturias76** [comment]
Yes I did this only for my favorites. It's just that in the Explorer, you have both pinned and recent folders and it's convenient when you work on a folder to have it in this section. But thanks for the already great work :).

**Comment by yaira2** [comment]
We're looking into display recent folders on the home page.

**Comment by Asturias76** [comment]
Ok, nice. Thanks.

**Comment by Enferlain** [comment]
Same, it's a pretty useful feature for productivity. If you were doing a bunch of stuff in a folder it would stay on the recent folders, and you could just go on them instead of having to find the folder manually every time or pin it and then unpin it when you're done using it.

**Comment by yaira2** [comment]
We're actively working on this.

**Comment by tubia** [comment]
Any update on this? It would be really appreciated :)

**Comment by yaira2** [comment]
@tubia recent folders are displayed on the home page.
