### ISSUE TITLE
"Group by"... feature change

### ISSUE THREAD

**Issue by newyork2003** [files-community/Files#10923]
### What feature or improvement do you think would benefit Files?

My user case is:
I am a designer with 2TB of data. Over 40.000 files.
I am switching from MAC to Windows.
I used the "group by" feature in my MAC to organize my files. But in windows the "group by" is so different that all my files are a mess.
If you could PLEASE make the "group by" more similar to MAC Finder.
At finder the group by is more generic. Ex: all images are gathered in the same section while in windows is separated by image file type. and that is a mess

### Requirements

-This proposal will achieve a better group by feature
-A better merging of MAC users to windows
-A better software for designers who use huge amount of data and files

### Files Version

Version: 2.4.8.0

### Windows Version

Windows 10 Pro Version	21H2 Installed on	‎25/‎08/‎2022 OS build	19044.2251 Experience	Windows Feature Experience Pack 120.2212.4180.0

**Comment by yaira2** [comment]
Merging with #10480
