### ISSUE TITLE
App Crashes on Right-Clicking a File or Folder

### ISSUE THREAD

**Issue by KineticAeon** [files-community/Files#10924]
### Description

When right-clicking folders or files outside of the startup page and sidebar, the program hangs for a second and crashes.

### Steps To Reproduce

1. Open Files
2. Open any folder or drive
3. Right-click a folder or file

### Steps to fix

Fix crash that occurs when right-clicking files and folders.

### Files Version

Version: 2.4.8.0 OS Version: 10.0.22000.1219

### Windows Version

WIndows 11 21H2 22000.1219

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10348349/debug.log)

**Comment by KineticAeon** [comment]
No, the preview version works fine.

**Comment by yaira2** [comment]
The fix will be included in the next release.
