### ISSUE TITLE
windows terminal

### ISSUE THREAD

**Issue by netoearth** [files-community/Files#10939]
### Description

The right-click menu does not have the option to open "windows terminal" in the directory,pls fix it!!!

### Steps To Reproduce

see description

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...
see description

### Files Version

版本: 2.4.11.0 OS Version: 10.0.22621.963

### Windows Version

win11 

### Relevant Assets/Logs

see description

**Comment by netoearth** [comment]
Inside of any folder

**Comment by Josh-65** [comment]
Can you screenshot the context menu in Files and File Explorer.

**Comment by netoearth** [comment]
![QQ截图20230106164241](https://user-images.githubusercontent.com/3488120/210964596-ec5ee2d8-e1bb-4afd-b28f-06b198f5f7c2.png)

**Comment by netoearth** [comment]
![未命名-1](https://user-images.githubusercontent.com/3488120/210964980-393a1e53-31ce-4e8a-a1af-0aa34914da93.png)
it can open only in the desktop!!!

**Comment by Josh-65** [comment]
Does File explorer (Not the desktop) show the option in the show more menu

**Comment by netoearth** [comment]
![未命名-1](https://user-images.githubusercontent.com/3488120/210966076-895950dc-0fb6-44b9-a66b-e5d6e665c64a.png)

yes,it works well

**Comment by Josh-65** [comment]
Does t show it in the show more menu

**Comment by netoearth** [comment]
yes ,in chinese it is "在终端中打开"

**Comment by XeroxDev** [comment]
Sorry for "bumping" this, but I think this isn't resolved yet(?). At least for the Terminal preview.

I'm using Files (Preview)
Version: 2.4.24.0
OS Version: 10.0.22621.1105

I opened both explorers in the same folder and here's my context menu opened with a simple right click (not with shift)

Windows Explorer
![324-311-max](https://user-images.githubusercontent.com/10864620/213936618-9535f7c5-6fca-4b8a-97dd-4292148fec3f.png)

Files App
![266-398-max](https://user-images.githubusercontent.com/10864620/213936665-9dcf1791-83c0-4921-849d-fb83ecf7bb9b.png)

**Comment by yaira2** [comment]
What's in the sub menu?

**Comment by XeroxDev** [comment]
"Show more options" Windows Explorer:
![241-318-max](https://user-images.githubusercontent.com/10864620/214000962-d30923ef-5c4e-4601-835c-5d66aec46c48.png)

"More" Files App
![577-403-max](https://user-images.githubusercontent.com/10864620/214001030-abfaf0ff-2356-40fb-9469-02387edefd2e.png)
