### ISSUE TITLE
Uninstalling Files

### ISSUE THREAD

**Issue by Packetron** [files-community/Files#10930]
Files app 2.4.11.0 does not uninstall using the Windows 11 Settings, Installed Apps, Right click on three dots, and clicking Uninstall method.  The listing for Files under Installed Apps disappears but the app is still present in the system.  Is there a way to manually uninstall the app?

**Comment by Josh-65** [comment]
If its not in the app list then it uninstalled. What make you think it isnt

**Comment by yaira2** [comment]
If you made Files the default file manager, you can reinstall Files and turn off the setting to revert the registry changes.
