### ISSUE TITLE
Feature: Add support for the location of disk D in the Favorites of the side bar

### ISSUE THREAD

**Issue by BLdada** [files-community/Files#10938]
### What feature or improvement do you think would benefit Files?

Add support for the location of disk D in the Favorites of the side bar.

### Requirements

Let Files can location Libraies at disk D like explorer.

### Files Version

Version:2.4.8.0

### Windows Version

Windows 11 22H2 25267.1000

### Comments

Files:
![image](https://user-images.githubusercontent.com/65645068/210939267-5ce129d8-4dd2-406e-bb25-b0182e6b7967.png)
Explorer:
![image](https://user-images.githubusercontent.com/65645068/210939314-51698436-d33c-4f0f-a583-3dfc3d51692f.png)

**Comment by Josh-65** [comment]
Those aren't libraries just default pinned folders. You can unpin them then go to your user folder and pin them back. Alternatively you can right click a empty space on the sidebar and click library's option
