### ISSUE TITLE
Auto Delete Zip/Rar when extracting

### ISSUE THREAD

**Issue by Br0ckout** [files-community/Files#1093]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When right clicking a zip/rar file to extract, could we have an option in the settings to trash the original zip/rar file once its extracted.

**Comment by XPoppyX** [comment]
a checkbox could be added in the extraction dialog to choose if we want the file to be deleted when the extraction is finished

**Comment by yaichenbaum** [comment]
Merging with #45.
