### ISSUE TITLE
Crash when opening multiple audio/video files

### ISSUE THREAD

**Issue by Anglodel** [files-community/Files#10944]
### Description

Hi,
I come across a crash with _Files_ when I select multiple audio/video files, and try to launch them with my default media player, _VLC_, or try to right-click on those selected files.
It happens whether I’ve set _Files_ to be the default Windows File Explorer in its Experimental option menu, or not.
Note that _Files_ can launch one audio/video file without a crash, and if _VLC_ is already launched, I can select and play multiple files at once, they will open in a new _VLC_ instance.
I didn’t see this behaviour with any other file type or software in which _Files_ launch a file (eg. a PDF document or an image). _Files_ crashes when it opens multiple files into _VLC_, but not when it opens those files into my other audio player, _AIMP_ (whether I set it as the default media player).
Maybe it is linked to https://github.com/files-community/Files/issues/10821 ?
I think it still is a _Files_ problem, as it’s _Files_ which crash, not _VLC_, right ?

P.S. : Sorry for the initial post without any formatting. I followed the `Contribute to files` > `Give Feedback` link at the bottom of [https://files.community](url) which only links to a blank new issue field at [https://github.com/files-community/files/issues/new](url), not [https://github.com/files-community/Files/issues/new/choose](url)

### Steps To Reproduce

1. Have VLC on your machine, and set it as system default audio player for the file type you want to open (otherwise "Play with VLC" and "Add to VLC playlist" contextual menu entries will not be shown).
2. Have multiple audio files (OGG, FLAC, MP3) somewhere.
3. Try to select more than one at the same time and launch/play them. VLC won’t open, and Files should crash.
4. Try to play only one file, and see it opens and Files does not crash.

### Steps to fix

- Fix crash that occurs when user selects multiple audio/video files at once and  tries to launch them
- Fix crash that _sometimes_ happens when right-clicking on multiple audio/video files

### Files Version

Version : 2.4.11.0 OS Version: 10.0.19045.2364

### Windows Version

Windows 10 Family 22H2 // Windows Feature Experience Pack 120.2212.4190.0

### Relevant Assets/Logs
[debug.log](https://github.com/files-community/Files/files/10362314/debug.log)

**Comment by yaira2** [comment]
Is the issue only when selecting multiple file types?

**Comment by Anglodel** [comment]
No, it happens whether I choose multiple file type or juste MP3, or just FLAC, or just OGG. It just have to be audio or video files and _Files_ crashes.
