### ISSUE TITLE
Drag and Drop crashes the app

### ISSUE THREAD

**Issue by MuhammadrizoDeveloper** [files-community/Files#10940]
### Description

When I drag and drop a file into the other tab the app crashes

### Steps To Reproduce

Open a tab with any folder
Open another tab with any other folder
from the first tab select a file
drag and drop it into the other tab

### Steps to fix

fix drag and dropping files to other tabs

### Files Version

Version: 2.4.8.0 OS Version: 10.0.22000.1335

### Windows Version

Windows 11 21H2 22000.1335

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10359740/debug.log)

![2023-01-06_16-07](https://user-images.githubusercontent.com/87116724/211001280-51373a02-3091-4261-a8fc-7cbe309c5d88.png)

**Comment by Josh-65** [comment]
Can you please upload the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.

**Comment by MuhammadrizoDeveloper** [comment]
[debug.log](https://github.com/files-community/Files/files/10359667/debug.log)


> Can you please upload the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.

**Comment by QuaintMako** [comment]
I took the liberty to add them to the main post.

**Comment by Libroru** [comment]
May I add that this only happens if you try to drag and drop before the actual "icon" shows up. So it always crashes if you select your files and instantly drag and drop them.
