### ISSUE TITLE
Crash when opening multiple audio files

### ISSUE THREAD

**Issue by Anglodel** [files-community/Files#10942]
Hi,
I come across a crash with _Files_ when I select multiple audio files, and try to launch them with my default audio player, _VLC_.
It happens whether I’ve set _Files_ to be the default Windows File Explorer in its Experimental option menu, or not.
Note that _Files_ can launch one audio files without a crash, and if _VLC_ is already launched, I can select and play multiple files at once, they will open in a new _VLC_ instance.
I didn’t see this behaviour with any other file type or software in which _Files_ launch a file. _Files_ crashes when it opens multiple files into _VLC_, but doesn’t when it opens into my other audio player, _AIMP_ (even when I set it as the default audio player).
I think it still is a _Files_ problem, as it’s _Files_ which crash, not _VLC_, right ?

I don’t know which system properties I can fill in here, but do not hesitate to ask me for more :
**_Files_ version :** 2.4.11.0
**OS :** Windows 10 Family 22H2
**OS Version :** 10.0.19045.2364
**CPU :** Intel(R) Pentium(R) Silver N5000 CPU @ 1.10GHz

**Comment by Josh-65** [comment]
Thanks for the feedback. Please make a new issue following the issue templates.
