### ISSUE TITLE
Readme view

### ISSUE THREAD

**Issue by phant0m2290** [files-community/Files#10947]
### What feature or improvement do you think would benefit Files?

If a directory has a readme file it will show up underneath the files and folders. So something like in github. So my idea is to add like an option to toggle readme view

### Requirements

- A new option to toggle readme view
- Checking the current directory for a readme.md file or any form of readme
- A new section to show the readme

### Files Version

2.4.8.0 OS Version: 10.0.19045.2364

### Windows Version

Windows 10 Home Versie 22H2 19045.2364

**Comment by gave92** [comment]
If a directory has a readme it's automatically shown in the preview pane

**Comment by Kay-Titulaer** [comment]
Hmm wierd. it dosnt show up for me.

**Comment by hecksmosis** [comment]
This doesn't work for me @gave92

**Comment by hecksmosis** [comment]
![image](https://user-images.githubusercontent.com/55754091/211208380-2f1462c6-7bb4-48d5-8247-164f0eb008bd.png)

**Comment by gave92** [comment]
Works for me. Relevant code is in ItemsViewModel @ line 1270. You can debug and see what's wrong.

**Comment by yaira2** [comment]
Maybe it's only if the file name is lowercase?

**Comment by gave92** [comment]
Should not be a problem:
```cs
if (... && item.Name.Contains("readme", ---> StringComparison.OrdinalIgnoreCase <---))
```

**Comment by hecksmosis** [comment]
This has started to work for me if I build from main but not from the stable release

**Comment by hecksmosis** [comment]
So I guess this should be closed
