### ISSUE TITLE
files does not show all the characters in the filename.

### ISSUE THREAD

**Issue by cleuton4k** [files-community/Files#10959]
### Description

when the file name has more characters than the other, only the part of the file name which has more characters is shown.

### Steps To Reproduce

https://user-images.githubusercontent.com/90144967/211223476-d1f5bcba-1b70-48c4-961a-920cbd199790.mp4

![114](https://user-images.githubusercontent.com/90144967/211223501-56de41c8-ecb9-4bf1-960c-7fa29d5dc5bb.png)

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

2.4.14

### Windows Version

w10 22h2

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10369699/debug.log)

**Comment by gave92** [comment]
Thanks for this feedback. Merging with #997.
