### ISSUE TITLE
An issue comment repetitively rises up without reason.

### ISSUE THREAD

**Issue by kamilacotrim** [files-community/Files#10953]
### Description

When I click the right button of the mouse on the image recently downloaded from the government website, showing the options about what to do with the file, and not long after this, an issue comment appears without asking for a specific action.   

### Steps To Reproduce

1. Go to app files
2. Click on downloads
3. Click on the image with the right button of the mouse to show options 
4. Wait
5. An error message appears
6. The app opens a second time 

### Steps to fix

If the app is being used the way that it was programmed for, don't send an error message when clicking to show the options of the files, and don't reopen the app.

### Files Version

Versão: 2.4.8.0 OS Version: 10.0.19045.2364

### Windows Version

Windows 10 22H2 19045.2364

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10367513/debug.log)

**Comment by yaira2** [comment]
This issue should be fixed in v2.4.11.
