### ISSUE TITLE
where is the black pixel theme?

### ISSUE THREAD

**Issue by iTaksha** [files-community/Files#10957]
### What feature or improvement do you think would benefit Files?

i want black pixel theme

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.4.8.0

### Windows Version

Edition	Windows 11 Home Single Language Version	22H2 Installed on	‎27-‎10-‎2022 OS build	22621.963 Experience	Windows Feature Experience Pack 1000.22638.1000.0

**Comment by Josh-65** [comment]
Its not a thing anymore. You can do it by following the instructions here https://files.community/docs/configuring/custom-themes
