### ISSUE TITLE
Languages are mixed when default

### ISSUE THREAD

**Issue by sakots** [files-community/Files#10969]
### Description

When windows default langage,

<img width="612" alt="image" src="https://user-images.githubusercontent.com/31465648/211437763-21d11ae4-7d8d-489c-b39d-182fa9ec2573.png">

### Steps To Reproduce

from the start

### Steps to fix

When I set it to Japanese in the settings, the date is also in Japanese.

### Files Version

2.4.14.0, 2.4.15.0(pre)

### Windows Version

windows11 HOME, 22H2, build 22621.963

### Relevant Assets/Logs

no log.

**Comment by sakots** [comment]
Changed the image to a clearer one.

**Comment by yaira2** [comment]
The date follows the system language, closing since this is intended.
