### ISSUE TITLE
Default icons when opening a folder appear gray since v2.4 

### ISSUE THREAD

**Issue by carlosvsilva** [files-community/Files#10968]
### Description

Opening a folder there's a delay in rendering file icons, thumbnails, etc. Currently Files latest version displays each file as a gray box before rendering the final icon.

I suggest changing from a gray box, to a default icon for the respective filetype, before the final icon is rendered.

Note: I run Icaros for media thumbnails

### Steps To Reproduce

1. Open folder for the first time
2. Icons start as gray boxes

### Steps to fix

- Open a folder once to cache rendered final icons

### Files Version

Versão: 2.4.11.0 

### Windows Version

OS Version: 10.0.22621.963

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/40889421/211384593-578278cc-fcc8-47ac-b577-3c77abf364c1.png)
[debug.log](https://github.com/files-community/Files/files/10376028/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/10376029/debug_fulltrust.log)

**Comment by yaira2** [comment]
There are too many file types to display default icons for, but we are working on optimizing the performance when loading thumbnails. Merging with #4180

**Comment by carlosvsilva** [comment]
I suggest just using Windows defaults or alternative, a generic icon for each group of:

- documents
- images
- video
- audio
- exes
- blank for other groups.

**Comment by ErickYu-code** [comment]
希望能解决这个问题，图标加载延迟很影响体验

**Comment by yair100** [comment]
@carlosvsilva we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
