### ISSUE TITLE
Won't Install

### ISSUE THREAD

**Issue by MelTJuan** [files-community/Files#10965]
### Description

Attempt to install results in message

'This app package is not supported for installation by App Installer because it uses certain restricted capabilities.'

### Steps To Reproduce

Install

### Steps to fix

Cannot fix

### Files Version

2.4.14.0

### Windows Version

Windows 10 Pro Version	20H2

### Relevant Assets/Logs

![Capture](https://user-images.githubusercontent.com/122273570/211296621-88df96bf-c5f8-4c61-bccd-f8f531dba5eb.GIF)

**Comment by Josh-65** [comment]
Can you try 
1. Opening PowerShell window as administrator
2. Run this command   Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/stable/Files.Package.appinstaller

**Comment by MelTJuan** [comment]
Success!

Thank you

**Comment by chadify** [comment]
> Can you try
> 
> 1. Opening PowerShell window as administrator
> 2. Run this command   Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/stable/Files.Package.appinstaller

I ran the command and the app installed but on opening it I'm getting the following popup:

![image](https://user-images.githubusercontent.com/72332949/216124521-04703db5-10a8-4a74-80cd-513fa55c2ac9.png)

**Comment by Josh-65** [comment]
The command shouldn't open the app installer window. Did you run it in PowerShell?

**Comment by chadify** [comment]
> The command shouldn't open the app installer window. Did you run it in PowerShell?

Yes I did. I'm also on the latest windows.
