### ISSUE TITLE
Bug: Unable to drag and drop

### ISSUE THREAD

**Issue by verdaderoken** [files-community/Files#10961]
### Description

The drag and dropping of files in some applications are broken in the recent version v2.4.14.
I'm currently testing it out on Adobe Premiere Pro and it doesn't work.
It also doesn't work in Google Chrome.

I'm aware that in the past, some applications would not work well with drag and drop **but** it does work on Adobe Premiere Pro and Google Chrome before.

### Steps To Reproduce

1. Open Files
2. Drag a file to software like Premiere Pro, FL Studio, or Google Chrome
3. The application will deny the drop event

### Steps to fix

- Fix the drag and drop

### Files Version

v2.4.14

### Windows Version

10.0.22623.1095

### Relevant Assets/Logs

None

**Comment by gave92** [comment]
#10949

**Comment by cleuton4k** [comment]
the same happens to me
