### ISSUE TITLE
Toggle for Hardware Acceleration

### ISSUE THREAD

**Issue by rppsedu** [files-community/Files#10974]
### What feature or improvement do you think would benefit Files?

There should be a hardware acceleration switch in the settings - low end devices struggle with it on...

### Requirements

- Make an option in Settings of the Files App

### Files Version

2.0.36.0

### Windows Version

Windows 10

**Comment by yaira2** [comment]
I don't believe we have control over this in Files, it'll follow whatever WinAppSdk and Windows allows. Happy to revisit if this becomes possible.
