### ISSUE TITLE
Add keyboard shortcuts support

### ISSUE THREAD

**Issue by michael-motornyi** [files-community/Files#10978]
### What feature or improvement do you think would benefit Files?

Improve user experience and usability of Files app

### Requirements

Add possibility to improve user experience by adding basic shortcuts like: 
- F5/F6 for copy/move between dual panes
- F3 - file preview
- F4 - edit file
- ctrl+, to open settings
etc.

Add possibility to edit shortcuts in settings

### Files Version

Version: 2.4.14.0

### Windows Version

Windows 11 22H2 25267.1000

**Comment by Josh-65** [comment]
Customising shortcuts is tracked in #9559

**Comment by michael-motornyi** [comment]
@Josh-65  Thanks, didn't know that it is already tracked.

**Comment by yaira2** [comment]
@michael-motornyi This feature will be included in the next release. Please see #9559 for more details.
