### ISSUE TITLE
Bug: Icons/Thumbnails are not loading

### ISSUE THREAD

**Issue by verdaderoken** [files-community/Files#10984]
### Description

Thumbnails in GridView are not loading even when you refresh the folder.
It only loads when you change the size of the grid view.

### Steps To Reproduce

1. Open Files
2. Navigate to a folder with a lot of items
3. Change the view to a grid view (Small Icons, Medium Icons, Large Icons, or Tiles)
4. The icons will not load.

This is my current workaround

5. Change the layout using **Ctrl + Shift + Num** keys
6. Icons should now show up

But if you try to refresh the folder again, the icons would disappear again.

### Steps to fix

- Display the thumbnails correctly

### Files Version

Version: 2.4.20.0

### Windows Version

10.0.22623.1095

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/88200096/211812768-3cff616d-188b-4dae-a705-c290f008647a.png)

**Comment by Josh-65** [comment]
Merging with #10983
