### ISSUE TITLE
Support command like explorer

### ISSUE THREAD

**Issue by minhluan259** [files-community/Files#10988]
### What feature or improvement do you think would benefit Files?

In windows terminal we can open current folder by command like Explorer:
```explorer.exe .```
It works with folder WSL too.

### Requirements

None

### Files Version

Latest

### Windows Version

Windows 11

**Comment by yaira2** [comment]
Should be implemented with #3947

**Comment by minhluan259** [comment]
@yaira2 I'm trying with
`files .`
it's open Home folder instead current folder in terminal
