### ISSUE TITLE
Bug: Slow or stuck file/image preview load time

### ISSUE THREAD

**Issue by Jaluvshuskies** [files-community/Files#10983]
### Description

Haven't quite narrowed down what the issue could be, but when looking in some folders, the image previews aren't loading and are stuck with the grey preview. See image:
![bug](https://user-images.githubusercontent.com/29661044/211716466-8f7bddb0-7a57-472d-acfc-95fdb1ff1bc1.jpg)

p.s. will add more detail to this when I can, it's late but I wanted to report this

### Steps To Reproduce

1. Open files
2. Navigate to a folder with files that have previews (png/jpg/mp4)
3. Observe whether the file previews are shown
4. Set view type to small icons
5. Close files
6. Navigate to the same folder
7. Observe whether the file previews are shown

### Steps to fix

Attempting to figure out what consistent fixes are, however I am unable to find a consistent solution

Here's what I've found so far:
- Zooming out a few clicks (from small icons to details) instantly fixed the issue once per session. It seem s to sometimes continue to fix when repeating this in the same session
- Doesn't appear to be drive related (SDD vs HDD)
- Unsure if related to file type (namely files with previews, like png, jpg, mp4)
- Happens with different folders, regardless of # of files in it (such as even just 1 image)

### Files Version

Version: 2.4.20.0 OS Version: 10.0.19045.2364

### Windows Version

Windows 10 22H2 19045.2364

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10388842/debug.log)

**Comment by yaira2** [comment]
This is being caused by the `WrapPanel` template introduced in #10972

**Comment by gave92** [comment]
IIRC wrap panel does not support virtualization so it tries to render all items at once. Not sure if that's what causing the issue but if wrap panel gets reintroduced we need to remember to check perfo on large folders.

**Comment by yaira2** [comment]
I temporarily reverted the change because of the issue, the code is still there but commented out. I think we'll have to find a different way to wrap the text.
