### ISSUE TITLE
Feature: Close column when selecting a file

### ISSUE THREAD

**Issue by redhotideas** [files-community/Files#10998]
### What feature or improvement do you think would benefit Files?

When I'm browsing through folders and then select a file that isn't a folder, the right hand column should empty, it's very confusing

![image](https://user-images.githubusercontent.com/118266752/212354466-fd2103d6-1839-4ff5-9ebe-d2a496250778.png)

### Requirements

-select folder
-select file
- last column must be empty

### Files Version

Versione 2.4.21.0

### Windows Version

Windows 11 Pro Versione 22H2

**Comment by yaira2** [comment]
Great feedback, we should definitely make this change.

**Comment by yaira2** [comment]
@redhotideas this improvement will be available in the next update.

**Comment by redhotideas** [comment]
I am very happy that this feature will be implemented. I use Files daily as my main explorer. There are many other aspects of pure user experience and workflow that I had noticed and would be proud to contribute again. Unfortunately I'm using an outdated version and therefore I won't be able to enjoy this aspect, I hope in future versions the Acrylic theme will be implemented again which was one of the aspects that made me fall in love with files (together with column navigation).
Hopeful waiting.
