### ISSUE TITLE
Drag and Drop file(s) to a Dropbox folder fails with error message

### ISSUE THREAD

**Issue by schalli35** [files-community/Files#10991]
### Description

I always used drag & drop to upload files from the "Files" App to my dropbox opened within chrome. While dragging file(s) the dropbox window normally got a blue dotted frame around the area where I could drop the file(s). 

Since the last "Files" update I do not get this frame.

While dropping the file(s) I get the error message (translated from german): "An empty file or an empty folder can not be uploaded." (tried Chrome and Edge - most current versions - failed in both).

It works well when I use the built-in windows file explorer (Chrome and Edge).

### Steps To Reproduce

1. Open your dropbox account and the folder where you want to drop file(s)
2. Open "Files" App
3. Drag a file (no matter which type of file)
4. Move it to the dropbox drop zone (-> blue frame does not appear)
5. Drop file
6. Error message appears

### Steps to fix

Please fix the drop error

### Files Version

Version: 2.4.14.0 OS Version: 10.0.19044.2251

### Windows Version

Windows 10 Enterprise Version, 21H2, OS Build 19044.2251, Windows Feature Experience Pack 120.2212.4180.0

### Relevant Assets/Logs

.

**Comment by Josh-65** [comment]
Can you see if this is an issue in 2.4.20

**Comment by schalli35** [comment]
Tested with version 2.4.21 - SUCCESS - thanks for the quick fix!
