### ISSUE TITLE
Resize last column width of column view

### ISSUE THREAD

**Issue by redhotideas** [files-community/Files#10997]
### What feature or improvement do you think would benefit Files?

To be able to read the full name of the files, give the possibility to widen the last column as you like.

![image](https://user-images.githubusercontent.com/118266752/212345207-fa20ce7d-c534-462d-ba0f-66203d3e5640.png)

### Requirements

- set column mode
-select the subfolder
-go to the edge and widen the column

### Files Version

Versione 2.4.21.0

### Windows Version

Windows 11 Pro Versione 22H2

**Comment by Josh-65** [comment]
Merging with #6534
