### ISSUE TITLE
Optional layout

### ISSUE THREAD

**Issue by redhotideas** [files-community/Files#10999]
### What feature or improvement do you think would benefit Files?

Is there the possibility to insert, in addition to the choice of color, the possibility of changing the layout and doing it like this?

### Requirements

- go to settings
- select vertical layout

### Files Version

Versione 2.4.21.0

### Windows Version

Windows 11 Pro Versione 22H2

### Comments

I have been a user of files for about a year, daily as a default finder. I can give my support for the graphics.

**Comment by redhotideas** [comment]
![Files_Tavola disegno 1](https://user-images.githubusercontent.com/118266752/212368851-99b436ef-8bb8-4144-b037-fc36358197f1.jpg)
![Senza titolo-1-02](https://user-images.githubusercontent.com/118266752/212368860-db55d983-b4d1-4737-bf0d-a89a4f8b724c.jpg)

**Comment by yaira2** [comment]
Thank you for the feedback, unfortunately the layout is fixed in place and can't really be rearranged. We don't have plans to change the design but I'd like to hear more about your use case for changing the layout.
