### ISSUE TITLE
Context menu doesn't stay at the same place

### ISSUE THREAD

**Issue by JGomsss** [files-community/Files#10994]
### Description

Context menu doesn't stay at the same place. 

At each right-click, the context menu is redrawn and not at the same place.
Unfortunately, they cause a bad click on quick action.

![Files_nvEUtz032P](https://user-images.githubusercontent.com/28355812/212294887-d837409a-909d-48af-a1e4-a7ba73978a2c.gif)

### Steps To Reproduce

At each right-click on file or folder, the context menu is redrawn and not at the same place.

### Steps to fix

The contextual menu doesn't redrawn and stay at the same place or add an option to use the default contextual menu of Windows

### Files Version

Version : 2.4.21.0 OS Version: 10.0.22621.963

### Windows Version

Windows 11 22H2

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10410490/debug.log)

**Comment by Josh-65** [comment]
It not possible for Files to use the Windows 10 style context menu.

**Comment by JGomsss** [comment]
> It not possible for Files to use the Windows 10 style context menu.

Windows 11 menu is possible ?

**Comment by Josh-65** [comment]
Files is in the style of Windows 11 one.

**Comment by JGomsss** [comment]
I'm not talking about style but about the windows11 menu.
The default Windows 11 context menu does not have this refresh behavior

**Comment by Josh-65** [comment]
I know I was talking about not being able to use the Windows 10 style context menu. Didn't mention anything about load behaviour.

**Comment by yaira2** [comment]
This has to do with the fact that the shell extensions take a little longer to load, as we make more optimizations, this should get faster and smoother.

**Comment by yaira2** [comment]
This was resolved in the latest preview build v2.4.26.
