### ISSUE TITLE
AcrylicBrush implemantation in Advanced themeing

### ISSUE THREAD

**Issue by redhotideas** [files-community/Files#10993]
### What feature or improvement do you think would benefit Files?

Please add the possibility to put the acrylic property to the elements, now only the color can be changed.

### Requirements

<AcrylicBrush
x:Key="SidebarContentBackgroundBrush"
BackgroundSource="HostBackdrop"
FallbackColor="{ThemeResource SolidBackgroundFillColorBase}"
TintColor="{ThemeResource SolidBackgroundFillColorBase}"
TintOpacity="0.81" 
/>

### Files Version

Versione 2.4.21.0

### Windows Version

Windows 11 Pro Versione 22H2

### Comments

I would like to build this in the current version:

<ResourceDictionary
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:BelowWindows10version1809="http://schemas.microsoft.com/winfx/2006/xaml/presentation?IsApiContractNotPresent(Windows.Foundation.UniversalApiContract, 7)"
    xmlns:Windows10version1809="http://schemas.microsoft.com/winfx/2006/xaml/presentation?IsApiContractPresent(Windows.Foundation.UniversalApiContract, 7)">
    <ResourceDictionary.ThemeDictionaries>
        <ResourceDictionary x:Key="Default">
            
            <x:Double x:Key="SidebarTintOpacity">0.6</x:Double>
            <x:Double x:Key="SidebarTintLuminosityOpacity">0.6</x:Double>

            
            <Color x:Key="SolidBackgroundFillColorTertiary">#2D2D2D</Color>

            

            <AcrylicBrush
                x:Key="SidebarContentBackgroundBrush"
                BackgroundSource="HostBackdrop"
                FallbackColor="{ThemeResource SolidBackgroundFillColorBase}"
                TintColor="{ThemeResource SolidBackgroundFillColorBase}"
                TintOpacity="0.77" />

            <SolidColorBrush x:Key="NavigationViewContentBackground" Color="#282828" />

            <SolidColorBrush x:Key="TabViewItemHeaderBackgroundPointerOver" Color="#3C3B3C" />

            <SolidColorBrush x:Key="TitlebarContentBackgroundBrush" Color="#353535" />
            <SolidColorBrush x:Key="TabViewItemHeaderBackgroundSelected" Color="#353535" />
            <SolidColorBrush x:Key="NavigationToolbarBreadcrumbBackgroundBrush" Color="#353535" />
            <SolidColorBrush x:Key="TextControlBackground" Color="#353535" />

            <SolidColorBrush x:Key="NavigationToolbarBackgroundBrush" Color="#353535" />

        </ResourceDictionary>

        <ResourceDictionary x:Key="Light">

            
            
            <AcrylicBrush
                x:Key="SidebarContentBackgroundBrush"
                BackgroundSource="HostBackdrop"
                FallbackColor="{ThemeResource SolidBackgroundFillColorBase}"
                TintColor="{ThemeResource SolidBackgroundFillColorBase}"
                TintOpacity="0.81" />

            <SolidColorBrush x:Key="NavigationViewContentBackground" Color="#F8F8F8" />

            <SolidColorBrush x:Key="TabViewItemHeaderBackgroundPointerOver" Color="#F8F8F8" />

            <SolidColorBrush x:Key="TitlebarContentBackgroundBrush" Color="#EBEBEB" />
            <SolidColorBrush x:Key="TabViewItemHeaderBackgroundSelected" Color="#EBEBEB" />
            <SolidColorBrush x:Key="NavigationToolbarBreadcrumbBackgroundBrush" Color="#EBEBEB" />
            <SolidColorBrush x:Key="TextControlBackground" Color="#EBEBEB" />

            <SolidColorBrush x:Key="NavigationToolbarBackgroundBrush" Color="#EBEBEB" />

        </ResourceDictionary>

        <ResourceDictionary x:Key="HighContrast">
            <StaticResource x:Key="RegionColor" ResourceKey="SystemColorWindowColor" />
            <SolidColorBrush x:Key="RegionBrush" Color="{ThemeResource RegionColor}" />
        </ResourceDictionary>

    </ResourceDictionary.ThemeDictionaries>
</ResourceDictionary>

**Comment by Josh-65** [comment]
Acrylic is not available anymore due to the difficulty supporting it. It might come back in a later update. You can check here #10690 for updates
