### ISSUE TITLE
BUG: Compact Window It doesn't work properly.

### ISSUE THREAD

**Issue by sercanserdar** [files-community/Files#10990]
### Description

When you go to the compact field view, the interface window is shrinking very much and cannot be expanded.

### Steps To Reproduce

1. Go to Compact View CTRL+ALT+UP

### Steps to fix

1. The window should be resized when it goes to a compact appearance.

### Files Version

2.4.21.0

### Windows Version

Windows 10 Home 22H2 19045.2486

### Relevant Assets/Logs

![Screenshot_1](https://user-images.githubusercontent.com/74400917/212001830-d1c4fa2d-476f-49a8-8644-6dc598fe552c.png)

**Comment by yaira2** [comment]
This is the intended behavior and not something we have controll over, compact overlay is not the same as "always on top".
