### ISSUE TITLE
OLE Automation popup sometimes pops up after the file is closed

### ISSUE THREAD

**Issue by 71x11** [files-community/Files#11005]
### Description

Hello, sometimes when my "files" is closed, the following pop-up window will pop up. I don't understand what it means. . .

### Steps To Reproduce

1. Open "File", create several new tabs or open several folders, wait for a while
2. Click "Close" in the upper right corner
3. This issue does not occur 100% of the time. Personally, it happens 3 times out of 10

### Steps to fix

Sorry, I don't know how to fix it

### Files Version

2.4.21.0

### Windows Version

Windows11 22H2 22621.1105

### Relevant Assets/Logs
[debug.log](https://github.com/files-community/Files/files/10417429/debug.log)

![屏幕截图 2023-01-14 210637](https://user-images.githubusercontent.com/122679509/212474045-c17b8570-2ecf-4453-8dbd-1df54b0f67ad.png)

**Comment by Josh-65** [comment]
Can you please upload the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.

**Comment by 71x11** [comment]
[debug.log](https://github.com/files-community/Files/files/10417429/debug.log)

**Comment by 71x11** [comment]
版本: 2.4.21.0
OS Version: 10.0.22621.1105

**Comment by Josh-65** [comment]
Added comments to main issue

**Comment by 71x11** [comment]
Oh, sorry, I don't quite understand the meaning of the sentence "Added comments to main issue", may I describe the main issue in more detail?

**Comment by Josh-65** [comment]
No, It to explain the deleted comments. I added the extra information on the comment to the main post.

**Comment by 71x11** [comment]
Well, I'm in no rush to solve this problem, on the contrary, I enjoy the wonderful experience that "Files" has given me, this software is really good!

**Comment by yaira2** [comment]
Have you made any modifications to Windows?

**Comment by Enferlain** [comment]
![image](https://user-images.githubusercontent.com/15861396/216164767-f7da1451-c315-4b30-98f5-de076c292f0f.png)

Did it get figured out what causes this? I just freshly installed it from the website from the sideload link.

**Comment by Josh-65** [comment]
No changes were made to directly for that issue. Could have been fixed with some PR though maybe it was just Windows at that time.

**Comment by yaira2** [comment]
We're not able to reproduce this issue on our end, we need some more information to help debug this. Have you made any modifications to Windows? Installed any other programs?

**Comment by Enferlain** [comment]
What kind of info can help? It's not a fresh system so tons of stuff is installed.

Found this in event viewer

> Faulting application name: Files.exe, version: 1.0.0.0, time stamp: 0x638f99ee
> Faulting module name: ComCtl32.DLL, version: 5.82.22621.436, time stamp: 0xe01e64f5
> Exception code: 0xc0000005
> Fault offset: 0x0000000000000000
> Faulting process id: 0x0x8FAC
> Faulting application start time: 0x0x1D936819D0499E7
> Faulting application path: C:\Program Files\WindowsApps\Files_2.4.25.0_x64__wvne1zexy08sa\Files.App\Files.exe
> Faulting module path: C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.436_none_fb2b38f27923daed\ComCtl32.DLL
> Report Id: 5836bb5b-6b96-41c0-a736-7ddb97a21a30
> Faulting package full name: Files_2.4.25.0_x64__wvne1zexy08sa
> Faulting package-relative application ID: App
