### ISSUE TITLE
Theme customization option

### ISSUE THREAD

**Issue by redhotideas** [files-community/Files#11002]
### What feature or improvement do you think would benefit Files?

I've seen the theme customization options, but I suggest implementing the color and mica effect in the options menu.
The mica effect should be enabled and adjusted separately in each section.

![Senza titolo-1-03](https://user-images.githubusercontent.com/118266752/212391871-a04b0416-ff9f-4f39-b055-e07ccfeb840a.jpg)

![Screenshot_20230113_191438](https://user-images.githubusercontent.com/118266752/212392224-8ff6e161-6daa-491b-b64c-2a53cc5911ab.png)

### Requirements

- go to settings
- appearance
- adjusts color and mica effect of sections separately

### Files Version

Versione 2.4.21.0

### Windows Version

Windows 11 Pro Versione 22H2

**Comment by yaira2** [comment]
This is already supported https://files.community/docs/configuring/custom-themes

Using a solid color for any area will turn off mica.

**Comment by redhotideas** [comment]
if I remove the mica effect from this element "AppThemeBackgroundColor", the effect in the "AppThemeSidebarBackgroundColor" also changes.
There is no instruction only for **color customization_1**

![image](https://user-images.githubusercontent.com/118266752/212729900-2af81ae6-28e2-4c99-b5e5-f12549d5b1e9.png)
![image](https://user-images.githubusercontent.com/118266752/212730096-77532f0f-32b5-4987-9056-9def9efa15db.png)

**Comment by yaira2** [comment]
`AppThemeBackgroundColor` needs to be transparent for mica to work.

**Comment by redhotideas** [comment]
So this section can't be without mica effect, otherwise I'll remove it from everything?

![image](https://user-images.githubusercontent.com/118266752/212731165-7680f517-7e77-49fe-9c5e-e10cd1d6eb14.png)

**Comment by yaira2** [comment]
Not currently, I'll see if I can add support.

**Comment by redhotideas** [comment]
you would be interested in a set of custom icons. I created them with a new effect for genre element, if it can be interesting I could prepare them for you for a future update

![desktop@3x](https://user-images.githubusercontent.com/118266752/212740788-2096930f-6ee1-4cbf-8df3-0f5958931cd4.png)

![documents@3x](https://user-images.githubusercontent.com/118266752/212740805-e574cad5-9b23-4ce0-a52a-0860ec11c0f4.png)

![Senza titolo-1](https://user-images.githubusercontent.com/118266752/212740830-752b7c8e-7a1a-462c-aa5c-040f06232e3b.jpg)

![Senza titolo-2](https://user-images.githubusercontent.com/118266752/212740861-42680f7e-c2d7-4da5-815a-cc1191e58c48.jpg)

**Comment by redhotideas** [comment]
where do i find the folder with the default home folder icons if i want to change them?

**Comment by yaira2** [comment]
It's under `src\Files.App\Assets\FluentIcons`

**Comment by redhotideas** [comment]
I searched for it, but I can't find the Files folder.
Even doing a search with FluentIcons I can't find anything

**Comment by Josh-65** [comment]
Its on the repository. Only way to change them if you build the app yourself

**Comment by yaira2** [comment]
https://github.com/files-community/Files/tree/main/src/Files.App/Assets/FluentIcons

**Comment by redhotideas** [comment]
What if you want to change these too?

![image](https://user-images.githubusercontent.com/118266752/213501051-abbf87ed-5ffb-4566-8aa7-1ac0ef04d2da.png)

**Comment by redhotideas** [comment]
or this of the 2.3 version

![image](https://user-images.githubusercontent.com/118266752/213501986-058388f3-fcc0-4eab-8096-1ea95e2a36e8.png)
