### ISSUE TITLE
Bug: Scan with Windows defender option missing

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#11004]
### Description

It did show in previous builds but not sure when. May be related to #10866
![image](https://user-images.githubusercontent.com/26977075/212469692-f307f759-3016-4271-bca7-302a0c60db7e.png)![image](https://user-images.githubusercontent.com/26977075/212469721-480555ee-678e-4cd7-946c-dc9ee2e8f05f.png)

### Steps To Reproduce

1. Right click a folder
2. See no "Scan with Microsoft defender

### Steps to fix

- Show "Scan with Microsoft defender" in content menu

### Files Version

2.4.21.0

### Windows Version

10.0.22621.1105

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10417242/debug.log)

**Comment by yaira2** [comment]
It's possible that they switched to the new format because it used to show up. We'd like to support the new format but we're having a hard time implementing it.

**Comment by Josh-65** [comment]
It doesn't show in the new menu only the old style one.

**Comment by lapaz17** [comment]
@yaira2 could you assign me?

**Comment by yaira2** [comment]
@lapaz17 assigned 👍

**Comment by yaira2** [comment]
This is either the same as #10866 or it's using the new shell apis which aren't yet supported.
