### ISSUE TITLE
File Extensions don't show for known file types in Home-Recent Files when set to show

### ISSUE THREAD

**Issue by tcjjr** [files-community/Files#11001]
### Description

File Extensions don't show for known file types in Home-Recent Files when they are set to show in Settings-Folders. They do appear everywhere else, but not there.

### Steps To Reproduce

1. Go to Settings
2. Click the Folders tab
3. Under Display, set Show extensions for known file types to On, then exit Settings.
4. Go to Home.
5. None of the files listed under Recent Files list show their file extensions.

### Steps to fix

unknown

### Files Version

Version: 2.4.21.0 OS Version: 10.0.22621.1105

### Windows Version

Windows 11 Pro Version	22H2 Installed on	‎12/‎19/‎2022 OS build	22621.1105 Serial number	PW02G088 Experience	Windows Feature Experience Pack 1000.22638.1000.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10413613/debug.log)

**Comment by yaira2** [comment]
Merging with #5888 (this should cover recent items as well)
