### ISSUE TITLE
There may be a memory leak

### ISSUE THREAD

**Issue by WCKYWCKF** [files-community/Files#11007]
### Description

I use a translator to translate my native language into English, which may have some problems. I am ashamed of my level of English

While using winui3, I found that when navigating to other pages using the Frame control, the memory would continue to grow until the program crashed. Setting the NavigationCacheMode property for the Page only slows down the process. And the same happens when the Window class updates the Content property.

I tried using the following but to no avail. The program still crashes. With Visual Studio 2022's diagnostic tools, I can see that process memory continues to grow, even though I create windows that only have a Button control.

The WinUI 3 Gallery via the Microsoft App Store also demonstrates this problem. When you keep changing pages in the navigation window until the process memory reaches about 550MB in Task Manager, the program will crash without warning. Even if you use various software to clean up memory, you can't stop this from happening.

Although the process of memory growth is very slow, it may not be a good experience when the user suddenly shuts down the software without warning during use

### Steps To Reproduce

I'm use the WinUI 3 Gallery as an example
Open the WinUI 3 Gallery
Keep clicking on the navigation menu on the left to change the page on the right. This may require you to click about 400 clicks
Looking at the memory occupied by WinUI 3 Gallery through Task Manager, it will crash without warning when it reaches around 550MB

### Steps to fix

Please resolve an issue with growing memory when navigating the Page control with the Frame control
Please resolve the problem of memory growing when the Content property of the Window control is changed

### Files Version

2.4.21

### Windows Version

Windows Feature Experience Pack 1000.25276.1000.0

### Relevant Assets/Logs

I didn't find any bug reports

**Comment by Josh-65** [comment]
This sound more like an issue with WinUi gallery 3. Have you tested this with Files?

**Comment by WCKYWCKF** [comment]
The following content is produced by translation.



The problem of growing memory isn't limited to WinUi gallery 3. This problem persists when you use the Frame control to navigate in your project. There are some methods that can slow down the rate of memory growth, but I don't have a way to completely solve this problem.


The file "error for WinUi gallery 3" demonstrates the process of crashing when navigation is constantly used.
The file "Memory Growth Frame" shows you how memory grows when you use the Frame control in your program
The file "Memory Growth Content" shows you how memory grows when you modify the Content property of a Window control in your program


As you can see from the video, memory growth isn't just in WinUi gallery 3; It's just that WinUi gallery 3's memory growth is the most pronounced.


The speed of memory growth can be greatly reduced by some means. But this does not completely solve the problem.


I've attached the items I used for testing. Please ignore the confusing Chinese. Trust that you can get everything you want to know from the code.


Is this a memory leak or some other unknown problem?


WinUi 3 is a great desktop architecture. If this problem can be solved, it will be even more perfect.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "files-community/Files"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月15日(星期天) 凌晨0:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [files-community/Files] There may be a memory leak (Issue #11007)





 
This sound more like an issue with WinUi gallery 3. Have you tested this with Files?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

Memory Growth Frame.mp4 (12.61M,  到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=7c636634a409549a381fba921236504a54005407055750541d520507011b565002534b0d57045a4805505304520004535650525534216228550e09464d1625175f14125c147010045d06485944026258&code=0cf446be




error for WinUi gallery 3.mp4 (56.52M, 2023年02月14日 01:34 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=30383432f39f42ce6a44e8941733071d5b0b5107090707504f5d0d0a041e0154565d1953060b511f5a0c550a0904535655095104312e3557104a5b4011555a40426f5d5c645a155503545857434a15014c554406310e&code=b8421352




Memory Growth Content.mp4 (10.61M,  到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=77343133c57b32c83148ed95403356180c05540055525d5414000805051e50005a521c515300511a5f5206025057565101500304662a647a5c595e411f1323455643455b46700b594d515f47485e14033909&code=9413f3d7




忘晨终端：BRDW通用引擎.7z (90.03M, 2023年02月14日 01:43 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=7b33636547a9669f3d4fbfc313300b4a0d565a070000085218055200541d0d5c51054e045056084800075a5205060d0707525556352939a8c980dcb3e086f2c68f71312162fd91b6f6e19ea2d31e0e1f350e&code=53ce509e

**Comment by Josh65-2201** [comment]
It possible that its a WinAppSDK issue since it affecting other apps too. Ill leave it up to @yair100 to confirm

**Comment by WCKYWCKF** [comment]
Thank you for your attention to this issue


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "files-community/Files"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月15日(星期天) 凌晨1:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [files-community/Files] There may be a memory leak (Issue #11007)





 
It possible that its a WinAppSDK issue since it affecting other apps too. Ill leave it up to @yair100 to confirm

**Comment by yaira2** [comment]
There are multiple memory leaks in Files, some caused by our own mess, and some are from the ListView and TabView controls in Files. We're tracking this in #4180.

**Comment by yair100** [comment]
@WCKYWCKF we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
