### ISSUE TITLE
Feature: Git integration

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#11014]
### What feature or improvement do you think would benefit Files?

Integration with _git_ is something that may add value for developers. We're inviting the open-source community to share feedback on which _git_ features they would find useful in a file manager and how it would enhance their workflow. Design concepts are welcome as well.

#### Phase 1 (implemented)
- Display the branch name in the status bar, this will let the user know which branch is active.

#### Phase 2 (implemented)
- Support for switching between local branches (this can be a simple flyout with a list view)
   - Display content dialog if there are uncommitted changes and ask user if they want to take the changes.
   - Display content dialog if there are uncommitted changes that can't be taken to the other branch and ask the user if they want to stash them.

#### Phase 3 (implemented)
- Support for checking out remote branches.
- Support for creating new branches, the button is already implemented in the UI. Clicking the new branch button should open a content dialog that allows the user to enter the branch name.

#### Phase 4 (implemented)
- Support for pulling remote changes
- Indicate on the status bar when there are remote commits

#### Future planning
- Indicate on the status bar when there are uncommitted changes
- Support for committing and pushing changes (what's the best way to display the list of changes?)
- Support for searching local branches

### Files Version

v2.4.21

### Windows Version

Windows 11

**Comment by yaira2** [comment]
Fyi @onein528

**Comment by yaira2** [comment]
I think the bare minimum would be support for switching branches. This can be achieved by adding a button/flyout to the status bar.

**Comment by onein528** [comment]
You mean if you open the repository in Files, you will be able to perform Git operations, such as change branch, commit, push, sync?

**Comment by yaira2** [comment]
> Push uncommitted changes

This requires UI for a commit message, not impossible but would require a lot of thought.

> Git commit tree viewing in preview pane or something

A possibility but curious how it would fit into users workflow and how the UI could be integrated.

> Pull
> Sync

I might add these to the minimum

**Comment by onein528** [comment]
I'll look what I can do and try to find what can be implemented.

**Comment by Josh-65** [comment]
Could show the changes of a file in the preview pane when selected. If it isn't too much having a separate "changes" pane to show them all would properly be good too. Ideally it would look like GitHub with the addition and removals of each line.

**Comment by hecksmosis** [comment]
This would be very useful

**Comment by hecksmosis** [comment]
We should probably enable/disable this in settings to not clog the app for non-devs

**Comment by Josh-65** [comment]
Properly wont need a setting since outside of a directory with a GitHub link it shouldn't be shown

**Comment by onein528** [comment]
To create this feature, Files must have git.exe binary module.
How can I add it? Just copy? @yaira2

**Comment by onein528** [comment]
![image](https://user-images.githubusercontent.com/62196528/216776395-486da671-12eb-4494-8191-e277207c5fdf.png)

**Comment by yaira2** [comment]
Is it possible to use the one already installed on the system?

**Comment by yaira2** [comment]
@onein528 instead of "branch:", maybe we can show an icon instead (similar to Visual Studio)

**Comment by onein528** [comment]
Files source code is very hard to understand... I couldn't implement.

FYI

Requirements:

- Use C# Git lib named LibGit2Sharp.
- Even if you open the repository subfolder, Files have to display Git status.

**Comment by ferrariofilippo** [comment]
I'm currently working on this feature. There are a couple of things we need to decide before I can continue my work.

### Checkout Menu
- `How do you access the checkout menu?` Should we use a separate button? I think that clicking on the branch name should open the menu (like in VS)?
- `What kind of menu should we use?` A flyout or a modal?
- `What actions should be there?` I was thinking of choosing the branch and creating a new one (what about inlcuding delete and rename?)

### User's Credentials
- Should we prompt users `each time` they try to push or pull? Should we `save a token` (GitHub Desktop, FluentHub) so that they don't need to log in each time?
- If we choose the token option, how should we handle it? I think we might prompt users if they aren't logged in. We should also include a section in settings to allow them to log in and log out

**Comment by yaira2** [comment]
> Checkout Menu

Phase 1 shouldn't have a checkout menu, I think we should wait for feedback on phase 1 before making these decisions.

**Comment by ferrariofilippo** [comment]
So phase 1 will be:
- Pull
- Push
- Sync
- See branch name

**Comment by 0x5bfa** [comment]
## Overview of authentication via OAuth

Since password authentication method has already been deprecated, there’s only one way to authorize OAuth app; use Personal Access Token.

# Credentials of committer

There’s no need to be authorized by GitHub. We have to show a modal to prompt a user to enter username/password. And commit and push by using libgit2sharp.

https://stackoverflow.com/questions/25084890/how-to-commit-and-push-in-libgit2sharp

**Comment by ferrariofilippo** [comment]
> Phase 1 shouldn't have a checkout menu, I think we should wait for feedback on phase 1 before making these decisions.

Since I've already written some of the code related to phase 2, should I comment that out in the PR?

**Comment by yaira2** [comment]
Would it be possible to copy that work into a separate branch?

**Comment by yaira2** [comment]
I updated the requirements for phase 2.

**Comment by ferrariofilippo** [comment]
How should we differentiate the active branch in the menu? Should we put it on top? Should it be bold?

**Comment by ferrariofilippo** [comment]
What do you think @yair100?
I still need to handle uncommited changes, but the basic checkout works!
![image](https://github.com/files-community/Files/assets/102259289/71fdeb4e-f029-4301-ac9c-c4b97ff1469c)

**Comment by yaira2** [comment]
Looks amazing! Can you add a fixed height and width to the flyout (200 x 200 is probably good)?

**Comment by 0x5bfa** [comment]
Can you customize Flyout padding?

```
+--------------------+
| Branches           |
| +----------------+ |
| | pr-202         | |
| +----------------+ |
| +----------------+ |
| | hotfix         | |
| +----------------+ |
|  ...               |
+--------------------+
```

`Branches` label is styled strong text block style.

**Comment by ferrariofilippo** [comment]
Like this?
![image](https://github.com/files-community/Files/assets/102259289/3bbd7db9-7cc1-41b9-af15-834c886168d3)

**Comment by 0x5bfa** [comment]
Shouldn't Branches, main, pr/12302 labels aligned in the same line?

**Comment by yaira2** [comment]
I updated the requirements for phase 3.

**Comment by ferrariofilippo** [comment]
> Support for creating new branches, the button is already implemented in the UI. Clicking the new branch button should open a content dialog that allows the user to enter the branch name.

I'll start to work on this part of the feature
@yair100 should the user be able to choose the base branch for the new one?

**Comment by 0x5bfa** [comment]
> (what's the best way to display the list of changes?)

I highly recommend to use Preview Pane.

**Comment by yaira2** [comment]
> should the user be able to choose the base branch for the new one?

Yes

**Comment by hez2010** [comment]
I'm wondering if we can implement the support for viewing the contents of a branch without actually checking out it. 
I always want to check the diff between two branches or copy a file from one branch to another, but git itself doesn't support it so I always end up duplicating the whole project directory and checking out them to different branches.

**Comment by 0x5bfa** [comment]
We can use 'compare' of GitHub API. https://stackoverflow.com/questions/64202547/how-to-compare-two-branches-in-github-with-graphql

**Comment by yaira2** [comment]
> I'm wondering if we can implement the support for viewing the contents of a branch without actually checking out it. I always want to check the diff between two branches or copy a file from one branch to another, but git itself doesn't support it so I always end up duplicating the whole project directory and checking out them to different branches.

I can see this being useful in multipane mode, the files would have to be read only as well but this is something we can look into once we finish with the fundamentals.

**Comment by yaira2** [comment]
Phase 4 is ready to build, this is also the final stage before we are ready to release the changes to stable.

**Comment by ferrariofilippo** [comment]
What about deleting local branches?

**Comment by yaira2** [comment]
> What about deleting local branches?

That could be one of the actions we display in #12440
