### ISSUE TITLE
Bug: The add pages menu in startup settings is empty

### ISSUE THREAD

**Issue by badlyo** [files-community/Files#11018]
### Description

I can't add a page, it's blank
![2023-01-15 18_56_59](https://user-images.githubusercontent.com/46354593/212561806-99505b8c-39f0-45f2-b7c4-6f8949841afa.png)

### Steps To Reproduce

  Go to Settings/Preferences/Startup settings
    Choose Open a specific pages
    Add one or two pages.
    Add button
    Blank
![2023-01-15 18_56_59](https://user-images.githubusercontent.com/46354593/212561537-ed3d2657-1302-4ec8-97f0-71d2219e7436.png)

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

2.4.21.0

### Windows Version

Windows 10 Professionnel 21H2

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10420958/debug.log)

**Comment by hecksmosis** [comment]
I can reproduce this

**Comment by jiejasonliu** [comment]
This is due to one-time binding, it's not consistent because it relies on how fast recent folders updates
I was actually looking into improving the performance of recent folder enumeration; I'll fix the binding along side
