### ISSUE TITLE
dragging item with right click and adding context menu with 

### ISSUE THREAD

**Issue by thinktech2go** [files-community/Files#11016]
### What feature or improvement do you think would benefit Files?

Faster shortcuts and creating copies or moving of files/folders
Would work very well with multi tabs.
It is a feature built into MS File Manager

![image](https://user-images.githubusercontent.com/251720/212552562-8ac473e7-d5b6-4df1-8884-71730566fae5.png)

### Requirements

- This proposal will add a context menu if dragging item with mouse right click
- This proposal will implement a built in feature with MS File Manager

### Files Version

Version: 2.4.21.0

### Windows Version

Windows 11 22H2

### Comments

This still works on desktop just not in Files
I often use this context menu to create shortcuts and keep my start menu organized.
I also use "create copy here" whenever I want backup prior to modifying.

**Comment by Josh-65** [comment]
Merging with #1396
