### ISSUE TITLE
Bug: Files crashes on launch

### ISSUE THREAD

**Issue by Algo-ryth-mix** [files-community/Files#11026]
### Description

When launching Files, it immediately crashes and displays the "Something went wrong" dialogue. Happens with every way of launching the Application.

### Steps To Reproduce

Open Files

### Steps to fix

- Files should not crash when being launched

### Files Version

2.4.21.0 (According to Windows Store)

### Windows Version

Windows 11 Pro 21H2 22000.1455

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10424265/debug.log)

**Comment by Algo-ryth-mix** [comment]
https://user-images.githubusercontent.com/12379720/212642601-03a86695-93c4-4ea8-8204-eac8d84b84ae.mp4

**Comment by yaira2** [comment]
Couple of questions
1. Was this a new installation of Files?
2. Have you modified any settings?
3. Does resetting the app fix the crash?

**Comment by Algo-ryth-mix** [comment]
Hey @yair100, sorry for the late reply

The installation was not _new_ but it wasn't particularly old either, I did not modify any settings as far as I can tell.
I tried resetting it but it did not change the situation, uninstalling it however made it so I can now not reinstall it. Not sure if that has anything to do with Files or if that is just the Microsoft Store being the Microsoft Store.

https://user-images.githubusercontent.com/12379720/214252152-bab33ea2-04da-4d1a-9c8b-6373ff69e3d2.mp4

**Comment by Algo-ryth-mix** [comment]
I was able to sideload it via the version from: https://files.community/download. But the crashing persists

**Comment by yaira2** [comment]
Can you confirm these steps?
1. Fresh install of Files
2. App crashes when opening for the first time

**Comment by Algo-ryth-mix** [comment]
Yes indeed 

https://user-images.githubusercontent.com/12379720/215489811-1a3f8126-25f0-44c8-8829-62cc23c2ed2a.mp4

**Comment by yaira2** [comment]
Can you try installing the preview version and seeing if it has the same issue? https://files.commnuity/download/

**Comment by Algo-ryth-mix** [comment]
Hey @yair100 the preview version appears to work fine.
![image](https://user-images.githubusercontent.com/12379720/216016660-adb6676c-6a3f-4398-b882-2854d5369518.png)
![image](https://user-images.githubusercontent.com/12379720/216017072-4ccbc11d-2917-49a3-9a93-ac3cea76f550.png)

Unrelated but there is something weird going on with your download page:
![20230201-111849](https://user-images.githubusercontent.com/12379720/216016539-4ab92c6a-ec7b-4a8a-bd58-be17866d556b.png)

https://user-images.githubusercontent.com/12379720/216016563-4c9aaf89-0b62-470b-8239-9b29ff689b9d.mp4

**Comment by yair100** [comment]
> Hey @yair100 the preview version appears to work fine.

Excellent, I'm not sure what's happening with the stable version as we haven't changed anything that would have solved a crash but I'm glad it's working now.
