### ISSUE TITLE
DetailsLayout Margin/Padding is not set correctly

### ISSUE THREAD

**Issue by ferrariofilippo** [files-community/Files#11025]
### Description

When using details layout content shows in random columns. In the screenshot below, you can see that `Size` is displayed under `Date Modified`
This may be caused by margin/padding or by the switch from `Grid` to `StackPanel`

### Steps To Reproduce

1. Open a folder using DetailsLayout
2. See that file info is not aligned into columns

### Steps to fix

- Content should fit into columns
<em>or</em>
- Fix Margin/Padding

### Files Version

Version: 2.4.21.0 OS Version: 10.0.22621.1105

### Windows Version

Windows 11 Home Version 22H2 22621.963

### Relevant Assets/Logs

![1](https://user-images.githubusercontent.com/102259289/212634245-b5f1a7cc-55ca-4a96-ad4e-af2a1666b844.png)

**Comment by yaira2** [comment]
This looks very wrong, what happens if you go to settings reset folder overrides?

**Comment by ferrariofilippo** [comment]
Nothing changes, it remains as in the screenshot

**Comment by yaira2** [comment]
I can't reproduce the issue, does this happen for all folders? Is there a specific column type that causes it?

**Comment by Josh-65** [comment]
Happens to me when the tag column is enable and the columns span the window. Not as much as the screenshot but probably worsen on higher resolution displays.

**Comment by ferrariofilippo** [comment]
Hiding tags column solve the problem for all folders but the recycle bin, which still appears as in the screenshot.
When tags column is visible, spacing (except in the recycle bin which looks as in the screenshot above) is a little bit off

![3](https://user-images.githubusercontent.com/102259289/212844402-cd017aed-1aa5-4fa1-980a-b6fcd7860c9c.png)

**Comment by hecksmosis** [comment]
@yair100 Don't issues get automatically sorted into the task board?

**Comment by Josh-65** [comment]
they have to be manually added

**Comment by yaira2** [comment]
Is this only in recycle bin?

**Comment by hecksmosis** [comment]
> they have to be manually added

I think this can be automated with Issue Bot

**Comment by hecksmosis** [comment]
> Is this only in recycle bin?

Yes

**Comment by ferrariofilippo** [comment]
> ![3](https://user-images.githubusercontent.com/102259289/212844402-cd017aed-1aa5-4fa1-980a-b6fcd7860c9c.png)

This is not recycle bin

**Comment by yaira2** [comment]
@ferrariofilippo the issue in that screenshot has been there for a while, seems the issue in recycle bin is new.

**Comment by ferrariofilippo** [comment]
Oh ok

**Comment by ferrariofilippo** [comment]
> @ferrariofilippo the issue in that screenshot has been there for a while

`ItemTagColumn` width is set using `Length` and not `LengthIncludingGridSplitter`
