### ISSUE TITLE
Show additional video info

### ISSUE THREAD

**Issue by MarcAnt01** [files-community/Files#1103]
**Is your feature request related to a problem? Please describe.**
Not really

**Describe the solution you'd like**
Show in properties window:
- Framerate;
- Bitrate;
- Resolution;
- Lenght

**Describe alternatives you've considered**
None

**Additional context**
![image](https://user-images.githubusercontent.com/43090263/85019755-9525f380-b16f-11ea-8d15-96b82055b7f2.png)

**Comment by duke7553** [comment]
Assuming this will be implemented with the Details tab in #1962 , I'll link them together.

**Comment by yaichenbaum** [comment]
fyi @winston-de

**Comment by winston-de** [comment]
@yair100 Included in #2289

<img  src="https://user-images.githubusercontent.com/59544401/100685073-78056b80-3330-11eb-9602-535beb11947b.png" width="400" 
/>
<img  src="https://user-images.githubusercontent.com/59544401/100685295-f3671d00-3330-11eb-8415-42542eeda8b9.png" width="400" 
/>
