### ISSUE TITLE
Bug: Files executed as admin crashes when clicking Browse

### ISSUE THREAD

**Issue by ferrariofilippo** [files-community/Files#11038]
### Description

When Files is executed as administrator, clicking the `Browse` button of modals (to select a folder) causes the app to crash.
This problem involves `New Shortcut` and `Extract Archive` dialogs for sure.

### Steps To Reproduce

1. Run Files as administrator
2. Open a dialog that contains a `Browse` button (e.g. `New Shortcut` `Extract Archive`)
3. See that Files crashes

### Steps to fix

Files should open `Pick a Folder` dialog

### Files Version

Version: 2.4.21.0 OS Version: 10.0.22621.1105

### Windows Version

Windows 11 Home Version 22H2 22621.963

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10456926/debug.log)

**Comment by yaira2** [comment]
Merging with https://github.com/microsoft/WindowsAppSDK/issues/2504
