### ISSUE TITLE
Tags doesn't work with network drive

### ISSUE THREAD

**Issue by JamesDAdams** [files-community/Files#11046]
### Description

Hi,

if i add a tags on files in a network drive in the tags list i don't see it

Thanks.

### Steps To Reproduce

1. Add a network drive
2. add tag on a file in yout network drive
3. go to tag list
4. You don't see the file taged earlier

### Steps to fix

I don"t have crash

### Files Version

2.4.21.0

### Windows Version

Windows 10 22H2 19045.2546

### Relevant Assets/Logs

Video example : https://www.veed.io/view/de203d50-697c-4eb7-b7de-55b794b96ac4?sharingWidget=true&panel=share

**Comment by yaira2** [comment]
Is the network drive formatted as NTFS? @gave92 can you confirm this is a requirement?
