### ISSUE TITLE
Feature: Preserve selection while changing layout mode

### ISSUE THREAD

**Issue by Gueztt** [files-community/Files#11048]
### What feature or improvement do you think would benefit Files?

While having few of the files selected in multiselect selection mode, if layout is switched from, say `Details Layout `to `Large Icons layout` to get better preview of the files, the selection is not preseved and vice-versa.

It would be much better if this can be done in the App.

FIles selected in `Details Layout`
![Screenshot 2023-01-22 023234](https://user-images.githubusercontent.com/90543726/213887055-be7b4278-1f3c-485a-8b13-0ef3633b1df8.png)

Selected files no more in selection after switching to `Large Icons Layout`
![Screenshot 2023-01-22 023308](https://user-images.githubusercontent.com/90543726/213887213-34c83f0f-18f3-4b1f-9a2d-d9a2c5ba4be0.png)

### Requirements

- Preserving selection while changing only the layout mode 

### Files Version

2.4.21.0

### Windows Version

Windows 11 22621.1105

**Comment by Josh-65** [comment]
Merging with #2856
