### ISSUE TITLE
Bug: Folder size isn't shown in the recycle bin

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#11043]
### Description

When Calculate folder size is on recycle bin folder still show empty

### Steps To Reproduce

1. Go to Files settings > Folder > Turn on calculate folder size
2. Delete a folder with content
3. Go to recycle bin and se the size column is blank

### Steps to fix

- Show size of a folder in the recycle bin

### Files Version

2.4.23.0

### Windows Version

10.0.22621.1105

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10461938/debug.log)

**Comment by Josh-65** [comment]
Turns out File explorer will show the Folder size information in the recycle bin.

**Comment by hecksmosis** [comment]
This should be quite straightforward to fix, can you approve this @yair100 ?

**Comment by hecksmosis** [comment]
Sorry, I'm stupid, this is not as trivial as i once thought, as i misinterpreted the issue as recycle bin size does not show in properties. Nevertheless, i'll look into it

**Comment by yaira2** [comment]
This issue is fixed in the `main` branch.
