### ISSUE TITLE
GodMode folder shows empty in Files

### ISSUE THREAD

**Issue by katastrophe92** [files-community/Files#11049]
### Description

GodMode folder is empty when opened in Files app 

### Steps To Reproduce

Right click-New Folder-Name the folder what you want + this code .{ED7BA470-8E54-465E-825C-99712043E01C}

### Steps to fix

I do not know what the fix is. 
![22 01 2023  10-38-26](https://user-images.githubusercontent.com/103950507/213909256-7637fe59-5765-4caf-bd4a-a9fc98448d80.png)

### Files Version

Version: 2.4.21.0

### Windows Version

OS 10 Pro Version: 10.0.19045.2486

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10474092/debug.log)
![22 01 2023  10-32-15](https://user-images.githubusercontent.com/103950507/213909398-3336322a-3b47-45ba-a364-ea096d89192e.png)

**Comment by gave92** [comment]
As an alternative, you can paste this in Files address bar: `shell:::{ED7BA470-8E54-465E-825C-99712043E01C}` and it should work.
