### ISSUE TITLE
How can we add a folder quick access to the side panel?

### ISSUE THREAD

**Issue by Freestyleyang** [files-community/Files#11041]
### What feature or improvement do you think would benefit Files?

Hi there,

Thank you for developing such great file management software for Windows! 

Is it possible to add a folder quick access to the side panel like the classic Windows File Explorer? Thank you.

### Requirements

- This proposal will accomplish the quick access to a folder.

### Files Version

v2.4

### Windows Version

Windows 10

**Comment by Josh-65** [comment]
Its the same way. Right click > add to favourites

**Comment by Freestyleyang** [comment]
Haha, thanks a lot!
