### ISSUE TITLE
Custom the List of  “Cloud Drives”

### ISSUE THREAD

**Issue by JordanQD** [files-community/Files#11047]
### What feature or improvement do you think would benefit Files?

I hope to custom the Cloud Drives that to choose which item to show in the sidebar. Additionally, I may need a function that can add Network Drive to the Cloud Drives, as the picture shown. 
![image](https://user-images.githubusercontent.com/25655766/213868925-fff0d3d9-0b6e-4fa5-8d58-e953575a47f2.png)

### Requirements

- This proposal will accomplish which item can be show in the sidebar "Cloud Drive"
- This proposal will accomplish adding the Network Drive to the Cloud Drive. 

### Files Version

2.4.21.0

### Windows Version

Windows 11 22H2 22621.1105

**Comment by Josh-65** [comment]
Merging with #6795

Network drives are also not a cloud drive service which is what the category is for. You can pin the drive to the favourites section by Opening the drive > Right clicking in the blank space > Add to favourites.
