### ISSUE TITLE
Multiselect is annoying for me

### ISSUE THREAD

**Issue by katastrophe92** [files-community/Files#11045]
### What feature or improvement do you think would benefit Files?

First of all thank you for this amazing repository, I really LOVE IT. I would use just this file explorer and ditch the default one but I can not get over one thing: PLEASE add one more selection option to work like in the default windows files explorer.

### Requirements

Will be more user friendly and not always thinking in what selection option i am. At least for me 😄 
And maybe allow us to rearrange the"Home" sidebar the way you want. For example: "Drives" above then "WSL" then "Tags" ...

### Files Version

Version: 2.4.21.0 OS

### Windows Version

Windows 10 Pro 22H2 OS build 19045.2486

### Comments

![20 01 2023  20-15-39](https://user-images.githubusercontent.com/103950507/213794013-4644c30c-2d5d-44d4-af07-43aefc61def4.gif)

**Comment by yaira2** [comment]
This was recently added and will be included in the next release.

**Comment by katastrophe92** [comment]
@yair100 thanks for your answer. The Microsoft Store and GitHub version is the same?
