### ISSUE TITLE
Bug: Text in release note goes behind the scroll bar

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#11056]
### Description

![image](https://user-images.githubusercontent.com/26977075/213933871-f169261c-00a7-4e47-9f64-69e21355e850.png)

### Steps To Reproduce

1. Open release notes

### Steps to fix

- Add some padding to the right of the text.

### Files Version

2.4.24.0

### Windows Version

10.0.22621.1105

### Relevant Assets/Logs

* UI issue

**Comment by yaira2** [comment]
We should also make the flyout a little wider
