### ISSUE TITLE
Bug: Creating a new file or folder wont use set name

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#11059]
### Description

They will always default to using "New Folder" or "New File"

### Steps To Reproduce

1. Right click in a folder
2. Go to new > Folder/File
3. Enter a name
4. See the name not used

### Steps to fix

- Create File/Folder with entered name

### Files Version

2.4.24.0

### Windows Version

10.0.22621.1105

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10475633/debug.log)

**Comment by yaira2** [comment]
@hecksmosis

**Comment by QuaintMako** [comment]
After a quick look, inside `Files.App\Helpers\UIFilesystemHelpers.cs`, line.331 has this set of instruction :
```
userInput = dialog.ViewModel.AdditionalData as string;
```
