### ISSUE TITLE
Bug: Multiselect doesn't work with open items with single click on

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#11052]
### Description

With the commit #11017 for improved multiselect it still doesn't work with single click mode on. As it will just select the File/Folder and double clicking will trigger the go up directory function.

### Steps To Reproduce

1. Enable the option in Files settings > Folders > Open items > Open items with single click.
2. Enable the option in Files settings > Folders > Show selection checkbox next to files name.
3. Try open a folder/file.

### Steps to fix

- Make click region for multiselect on the check box only.

### Files Version

Dev build on commit 985d66e

### Windows Version

10.0.22621.1105

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10474753/debug.log)

**Comment by yaira2** [comment]
How does it work in File Explorer?

**Comment by Josh-65** [comment]
Single click mode in file explorer will select the file then clicking again opens it. Otherwise you have to select the checkbox.
