### ISSUE TITLE
Crash after showing hidden file

### ISSUE THREAD

**Issue by LonerCactus** [files-community/Files#11050]
### Description

If open two tabs, choosing to show hidden file from "Layout button" in one of them, this causes the app to crash.
Column layout must be show only in one tab, if tab more than one in this type of layout this causes the app to crash.

### Steps To Reproduce

In files settings layout mode must be -- columns 

1. Open Files and open any disk or folder
2. Open new tab and open some disk or folder
3. Click "Layout button" and turn on or off "Show hidden items"

### Steps to fix

- Don't open two tabs with column layout if need show hidden files or change layout in other tab.

### Files Version

Version: 2.4.21.0 OS Version: 10.0.22623.1180

### Windows Version

Windows 11 Pro 22H2 (OS Build 22623.1180)

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10474391/debug.log)

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
