### ISSUE TITLE
Clicking "Feedback" and then "Submit" either a bug or feature, opens a folder called "LocalState"

### ISSUE THREAD

**Issue by francisco-lafe** [files-community/Files#11062]
### Description

https://user-images.githubusercontent.com/90066435/214115361-221b9225-6268-4cbe-bc17-ef9df0a60592.mp4

Just check the video.

### Steps To Reproduce

Video has the info needed.

### Steps to fix

1. Make the report a bug option open github
2. Make the submit a feature option open github

### Files Version

Version: 2.4.21.0 OS Version: 10.0.19044.2486

### Windows Version

Edition	Windows 10 Pro Version	21H2 Installed on	‎2021-‎07-‎06 OS build	19044.2486 Experience	Windows Feature Experience Pack 120.2212.4190.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10482469/debug.log)

**Comment by Josh-65** [comment]
This has been fixed for the next update
