### ISSUE TITLE
Ribbon Feature Idea

### ISSUE THREAD

**Issue by Modern293** [files-community/Files#11061]
### What feature or improvement do you think would benefit Files?

This feature will make easier to use with categories example: Home, Share or view.
This feature will be similar than Windows 10 but with Windows 11 icons and UI.

### Requirements

- There is an option for switching ribbon to simplified.
- Go to settings and go to personalize. You can see these 2 buttons: Simplified or Ribbon and click the Ribbon for switching to Ribbon UI or click Simplified for switching to Simplified UI.

### Files Version

Version : 2.4.21.0

### Windows Version

Windows 11 22H2 build 22621.1105

### Comments

It's made for nostalgic users or Windows 10 lovers. Before, some users are disliked the new file explorer in Windows 11 because it's simplified and harder to use. I have added this request for fixing the problem.

**Comment by yaira2** [comment]
Thank you for your feedback, we don't have plans to add back a ribbon.
