### ISSUE TITLE
manual file sort

### ISSUE THREAD

**Issue by MoamenKassem** [files-community/Files#11064]
### What feature or improvement do you think would benefit Files?

I wanted to suggest if you can to add a manual sort possibility (like to chose which file after which)
thank you for this amazing app, keep up the good work.

### Requirements

- This proposal will make it easier for sorting files
- This proposal will also give the user the ability to customize more and more freely

### Files Version

Version: 2.4.21.0 OS Version: 10.0.19045.2486

### Windows Version

Windows 10

**Comment by Josh-65** [comment]
This seem like it would be too hard to manager. Does the tag feature not work for you?

**Comment by yaira2** [comment]
How would this work across sessions and what happens if you add more files to the folder?
