### ISSUE TITLE
Feature: Switch default thumbnail size for adaptive layout to medium

### ISSUE THREAD

**Issue by Sawtaytoes** [files-community/Files#11072]
### What feature or improvement do you think would benefit Files?

The default thumbnail size appears to be "Small" when using Adaptive mode, but in Windows Explorer, this is "Medium" for me. Or at least, I can see more of the image. It'd be great if I could configure this setting because "Small" is too small for me.

Also, text is too far from the folder itself when viewing thumbnails.

Example:
![image](https://user-images.githubusercontent.com/3948069/214552168-e902dfb6-4ad1-4028-8147-4cae226ceb73.png)

In general, there's a lot of wasted space that goes beyond "comfortable":
![image](https://user-images.githubusercontent.com/3948069/214552422-24987604-e684-4921-bd12-20e561fecbce.png)

It'd be great if there was a way to configure this spacing. There's a "compact" mode, but I specifically want to target thumbnails. Spacing in the rest of the UI is fine.

Compare with Windows Explorer:
![image](https://user-images.githubusercontent.com/3948069/214553208-a2f572b8-9f03-4c2a-acff-527bcea6a9a0.png)

Whitespace between the image and text is minimal and whitespace between items is large but about the same as Files.

I actually think Windows Explorer has too much whitespace between thumbnails here. I'm assuming it's sizing them at 4:3. My thumbnails are 16:9 or even 21:9, so they have even more whitespace than usual.

### Requirements

1. This proposal will allow customizing the thumbnail size used by "Adaptive" mode.
2. This proposal will allow condensing whitespace in the thumbnails view.

### Files Version

Version: 2.4.25.0 OS Version: 10.0.22621.1105

### Windows Version

Windows 11 22H2 22621.1105

**Comment by yaira2** [comment]
> In general, there's a lot of wasted space that goes beyond "comfortable":

This is because these images have a wide aspect ratio, the only way to solve this would be together with #1033 which we're having a pretty difficult time on.

We can explore switching the default size to medium but I don't think it's worth adding a setting to configure.
