### ISSUE TITLE
cant install

### ISSUE THREAD

**Issue by Fan4eGGG** [files-community/Files#11078]
### Description

sup.
i downloaded file from [git itself](https://github.com/files-community/Files/releases/tag/v2.4.25) and from [here ](https://files.community/download).
the first one installing stuck at 16% and nothing more. the second i have an infinite loading\installing.
what im doing wrong? halp pls

### Steps To Reproduce

downloading the file
run as admin
???
stuck

### Steps to fix

do nothing.

### Files Version

v2.4.25

### Windows Version

win 10 22h2

### Relevant Assets/Logs

I don't have it

**Comment by Josh-65** [comment]
Can you try using
https://cdn.discordapp.com/attachments/961303641015332864/1067505401479839744/Files.Stable.exe

If that's doesn't work then try
1. Opening PowerShell window as administrator
2. Run this command   Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/stable/Files.Package.appinstaller

**Comment by Fan4eGGG** [comment]
done and... I have a bunch of red errors due to some disabled service.
which service should be enabled?

**Comment by Josh-65** [comment]
Send a screenshot of what it shows

**Comment by Fan4eGGG** [comment]
my powershell on Russian. u sure?
can i change the powershell lang somehow?

**Comment by Josh-65** [comment]
You can send it an il translate it

**Comment by Fan4eGGG** [comment]
aight

![Screenshot_1](https://user-images.githubusercontent.com/40491634/214698050-240a000b-2679-4cd8-971e-583dbf17725a.jpg)

**Comment by Josh-65** [comment]
If you have Windows update disabled go to. Task manager > Services > look for `wuauserv` > Right click > Start

**Comment by Fan4eGGG** [comment]
oh. i guess i delete it w/Win10tweaker :D 
gimme a min. i try to restore it

**Comment by Fan4eGGG** [comment]
so, ok. powershell shows me a green bar for a sec and thats it.
whats next?

**Comment by Josh-65** [comment]
Check for Files in the start menu

**Comment by Fan4eGGG** [comment]
nah. nothing.

**Comment by Fan4eGGG** [comment]
ah. now i can install it from exe. and its opened. thanks.
