### ISSUE TITLE
v2.4.25 is acrylic back?

### ISSUE THREAD

**Issue by redhotideas** [files-community/Files#11076]
### What feature or improvement do you think would benefit Files?

I've read several articles and forums where they say that with the latest Win 11 updates the acrylic feature works fine.

### Requirements

- Go to settings
- appearance
- enable acrylic

### Files Version

Versione 2.4.25

### Windows Version

Windows 11 Pro Versione 22H2

### Comments

Please reactivate the acrylic function I would like to enjoy the new features of the new versions

**Comment by Josh-65** [comment]
See comment https://github.com/files-community/Files/issues/10690#issuecomment-1387196659

**Comment by Josh-65** [comment]
Since you are on Windows 11 you can try the alternative glass theme at https://files.community/docs/configuring/custom-themes
