### ISSUE TITLE
Cannot Install this app

### ISSUE THREAD

**Issue by shenbourne** [files-community/Files#11074]
### Description

as the title
![Snipaste_2023-01-25_22-08-43](https://user-images.githubusercontent.com/121733766/214585664-3a3edfcf-67aa-4276-b44a-dd147643ce58.png)
This window has remained the same for more than ten minutes.

### Steps To Reproduce

double click “Files.Stable.exe”
and it happened

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

Version: 2.4.25.0

### Windows Version

Windows 10 22H2 19045.2364

### Relevant Assets/Logs

none

**Comment by Josh-65** [comment]
Click the install button

**Comment by yaira2** [comment]
@shenbourne can you try the installer for the preview version?
