### ISSUE TITLE
Network drives shows empty before you hit F5 and content appears

### ISSUE THREAD

**Issue by Emulga** [files-community/Files#11077]
### Description

Network drives takes a long time to refresh compared to Windows Explorer.

When you add your network drive in the Favorites bar you will save some time but the behaviour is the same where you have to press F5 to refresh and show the files and folders.

_My network drive is a TrueNAS Scale server if this information matters._

### Steps To Reproduce

1. Click on "Network drives" in the sidebar
2. Click on "Network" and wait about 20-30 secs
3. Double-click on your network drive to access it

### Steps to fix

Once you're in the empty network drive, press refresh F5 on the keyboard to make the files and folders come back.

### Files Version

Version: 2.4.25.0 OS Version: 10.0.19045.2486

### Windows Version

Windows 10 22H2 19045.2486

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10501684/debug.log)

**Comment by yaira2** [comment]
Merging with #10039
