### ISSUE TITLE
Feature: Reword `Enable overriding folder preferences in individual directories`

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#11075]
### What feature or improvement do you think would benefit Files?

The current wording is long and confusing.

### Requirements

- Rename the option to `Sync folder preferences across all directories`
- Remove the below description as it wont be needed.
- Invert the toggle.

### Files Version

2.4.24.0

### Windows Version

10.0.22621.1105

**Comment by yaira2** [comment]
"Sync folders preferences across all directories"?

**Comment by Josh-65** [comment]
Sounds good
