### ISSUE TITLE
Dragging not allowed in Favorites

### ISSUE THREAD

**Issue by Sawtaytoes** [files-community/Files#11071]
### What feature or improvement do you think would benefit Files?

Unlike Windows Explorer, there's no way to drag a folder into the Favorites section to pin it. You need to right-click pin.

There's also no way to reorder Favorites without dragging.

If there's a way to right-click move, then it'd be much simpler if there was a drag 'n drop method just like the default Windows Explorer.

### Requirements

1. This proposal will allow dragging items into the Favorites panel to pin them.
2. This proposal will allow dragging and dropping items in Favorites to reorder them.

### Files Version

Version: 2.4.25.0 OS Version: 10.0.22621.1105

### Windows Version

Windows 11 22H2 22621.1105

**Comment by Josh-65** [comment]
Merging with https://github.com/microsoft/microsoft-ui-xaml/issues/3290

This is an issue with WinUI and Files currently cant do anything for it.
