### ISSUE TITLE
Slow opening of the right-click menu

### ISSUE THREAD

**Issue by GDT1978** [files-community/Files#11073]
### Description

Like I said in the title, the application is really slow when opening of the right-click menu.
It draws the menu, stuck on it loading some sort of shell extensions (winrar, onedrive, nothing special...) and redraw the menu after 3-6 seconds

### Steps To Reproduce

Right-click with mouse over a file (executable, picture...)
See

### Steps to fix

You have to wait

### Files Version

2.4.25 and latest 3 official versions (since I start to use this software)

### Windows Version

Windows 11 22H2

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10499945/debug.log)

**Comment by Josh-65** [comment]
Merging with #10994

**Comment by yaira2** [comment]
@GDT1978 thank you for your feedback, performance is a top priority and we're looking for ways to improve the performance of the context menu.
