### ISSUE TITLE
Fully loading of context menu dismisses sub-menus

### ISSUE THREAD

**Issue by jxolotl** [files-community/Files#11086]
### Description

Additional items in context menu takes time to load while built-in items (Copy, Paste, etc..) are displayed instantly.

However, once the menu is fully loaded, the current selection is reset and any expanded sub-menus are dismissed.

This can be clunky UX-wise especially on a slow device.

https://user-images.githubusercontent.com/123339772/214765935-d038016f-8f6b-4323-9fbe-cb0d31266dc8.mp4

I suspect it's a WinUI issue (as Windows File Explorer also has this issue), but I'm not technically knowledgeable enough to file an issue against WinUI project.

### Steps To Reproduce

It should be easy to reproduce on a slow device:

- Open context menu
- Before it gets fully loaded, try to expand a sub-menu
- The context menu gets fully loaded

**Expected result**

After menu is fully loaded, the sub-menu remains intact.

**Actual result**

After menu is fully loaded, any visible sub-menus are also dismissed.

### Steps to fix

Workaround1: Don't try to select anything before the menu is fully loaded.

Workaround2: Don't use context menu.

Workaround3: If you're trying to workaround the same issue in Windows File Explorer, use [ExplorerPatcher](https://github.com/valinet/ExplorerPatcher) and enable `Disable the Windows 11 context menu` under `File Explorer` category.

### Files Version

2.4.25.0

### Windows Version

22621.1105

### Log file

UI issue, and it's always reproducible regardless of hardware, log is irrelevant.

**Comment by yaira2** [comment]
This is really a performance issue with loading the shell extensions, we're looking into ways to improve it. See #4180

**Comment by jxolotl** [comment]
@yaira2 I think `slow loading of additional items in context menu` is not the same issue as `fully loading of context menu dismisses sub-menus`? The performance issue you're talking about is likely referring to the former while this issue is about the latter.

Even if Files is very fast at loading additional items, the latter issue is still there, it's just harder to reproduce.

Or does closing #4180 also imply the latter being fixed?

**Comment by Josh-65** [comment]
If it loads fast enough you wouldn't be able to get to a sub menu for it to happen. #4180 is also a general issue that properly wont be close since it talking about performance in all aspects of Files.
