### ISSUE TITLE
Bug: Tab becomes its own window if clicked on a bit too long

### ISSUE THREAD

**Issue by coolbond1** [files-community/Files#11081]
### Description

sometimes if i click on a tab and dont release it fast enough it will move the tab into a new window, according to Josh-65 in the discord this could be cause the drag sensitivity is too high and only encountered it with Files.

### Steps To Reproduce

open several tabs.
Click on the tabs with greater and greater delay between press down and release, eventually one should pop out as its own window.

### Steps to fix

either implement an option to disable pop out when dragged or figure out why this is happening in the first place.

### Files Version

Version: 2.4.21.0 OS Version: 10.0.19045.2486

### Windows Version

Win 10 22H2 build 19045.2486

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10504410/debug.log)

**Comment by Josh-65** [comment]
It might be better to make it so tab doesn't go into a new window unless the cursor is fully out of the Files window/edge of screen or goes under the path/search bar area. This is how it works in Edge.
