### ISSUE TITLE
Scrollbar width is too small

### ISSUE THREAD

**Issue by peter-fb** [files-community/Files#11089]
### Description

Files apparently sets its own scrollbar width and doesn't follow Windows theme settings. If you compare Files to File Explorer, the Settings app, and Notepad, then the scrollbar width is about 4 times smaller; this makes it much harder to click on it with the mouse pointer.

### Steps To Reproduce

Open a folder with lots of files so that a scrollbar appears.

### Steps to fix

It's probably best to set the scrollbar to the same width as File Explorer, Notepad etc. Or make the scrollbar width a customizable setting instead.

### Files Version

Version: 2.4.25.0

### Windows Version

Windows 10 Pro 22H2 10.0.19045.2486

### Log file

[debug.log](https://github.com/files-community/Files/files/10507971/debug.log)

**Comment by Josh-65** [comment]
The scrollbar is using Windows 11 styles. Its the same width as the default scrollbar on Windows 10. Can you send a screenshot of what it looks like for you.

**Comment by yaira2** [comment]
Like Josh said, we use the default WinUI scrollbar, there is a setting in Windows to "Always show scrollbars". This should make the width of the scrollbar a little wider.

**Comment by peter-fb** [comment]
Even with the setting "Always show scrollbars", the scrollbar of Files is still very thin. Here's a screenshot of Files, compared with the Windows Settings app, Notepad, and File Explorer:

![2023-01-26 18_26_58-Windows 10](https://user-images.githubusercontent.com/7101417/214907146-5cf7381a-9619-4a4e-9be4-cb7b884f8272.png)

**Comment by yaira2** [comment]
It seems that Microsoft is prioritizing the look over the ease of use, I encourage sharing your feedback on the WinUI repository as this applies to other apps as well.
