### ISSUE TITLE
Can preview version synchronize with stable version?

### ISSUE THREAD

**Issue by SteveWorkshop** [files-community/Files#11088]
### What feature or improvement do you think would benefit Files?

Files preview should receive stable builds when they are avaliable.
For example, today stable 2.4.25 comes to public, preview should receive 2.4.25, rather than staying at 2.4.24
In other time, preview version should be higher.
Like windows, Dev is higher than Beta most of the time, but they sometimes receive same build when a stable build releases.

### Requirements

- This proposal will synchronize build number between preview and stable when stable releases a new build

### Files Version

2.4.24.0 2.4.25.0

### Windows Version

windows11 22623.1180

**Comment by yaira2** [comment]
Preview always has the latest, the version number is sometimes higher on the stable release because of the way the Store handles versioning and auto updates.
