### ISSUE TITLE
Bug: App crashed when copying file from 7zip

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#11096]
### Description

Title

### Steps To Reproduce

1. Open .zip archive in 7Zip
2. Copy file (.json for me) to directory
3. App crashes

### Steps to fix

- 

### Files Version

2.4.25.0

### Windows Version

10.0.22621.1105

### Log file

[debug.log](https://github.com/files-community/Files/files/10514262/debug.log)

**Comment by hishitetsu** [comment]
Somehow 7-zip returns partly short paths, so it seems to fail to detect duplicate paths, resulting in an error.
![image](https://user-images.githubusercontent.com/66369541/215429830-644abe4f-a9f9-4f3a-ba1f-4101cdb57a5d.png)
