### ISSUE TITLE
Feature: Show what apps are using drive upon failed eject

### ISSUE THREAD

**Issue by ggtylerr** [files-community/Files#11091]
### What feature or improvement do you think would benefit Files?

Whenever a user needs to eject an external drive, disk, USB, etc, one of the biggest issues is that a program might be using it. The problem is, Windows doesn't tell you which app currently is. This leads users to either scour through their currently running apps, trying to find which one it could be (or using process explorer, which isn't foolproof), or they just manually disconnect it, potentially causing corruption. Having a feature to show what's using a drive would prevent this problem from occuring.

### Requirements

- Show what app / process is using a drive upon eject (or through a context menu option)
- Be able to close or switch to that app
- If it can't find it, try and show the number of hidden processes using it

### Files Version

2.4.24.0

### Windows Version

Windows 11 22H2 22621.1105

**Comment by Josh-65** [comment]
Merging with #9560

**Comment by ggtylerr** [comment]
What in the world happened here 😅
I don't mind that this is merged with an older feature request - just stick to one and don't mess with it please

**Comment by yaira2** [comment]
I kept this one open because the requirements are clearer.
