### ISSUE TITLE
Crash when changing settings

### ISSUE THREAD

**Issue by samehBijo** [files-community/Files#11098]
### Description

Settings ,
Calculate file size, crash
Uncheck Double click feature , crash 

### Steps To Reproduce

Settings ,
Calculate file size, crash
Uncheck Double click feature , crash 

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...
Settings ,
Calculate file size, crash
Uncheck Double click feature , crash 

### Files Version

Version: 2.4.25.0 OS Version: 10.0.22621.1105

### Windows Version

Windows 11

### Log file

[debug.log](https://github.com/files-community/Files/files/10517594/debug.log)

**Comment by yaira2** [comment]
@samehBijo can you try resetting Files and seeing if it's still an issue?
