### ISSUE TITLE
Glass Feal Theame

### ISSUE THREAD

**Issue by Thulmin** [files-community/Files#11093]
### What feature or improvement do you think would benefit Files?

Requesting to provide a theme which have glass feeling like Mac OS.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.4.25.0

### Windows Version

Windows 11 22H2

**Comment by Josh-65** [comment]
For theming follow the instructions at https://files.community/docs/configuring/custom-themes

**Comment by yaira2** [comment]
In particular, see the sample theme for "Glass". Please note that this theme currently requires Windows 11 but we're working on adding support for Windows 10.
