### ISSUE TITLE
Cannot add specific pages to open

### ISSUE THREAD

**Issue by DW-Andy** [files-community/Files#11097]
### Description

When you click the startup settings called open a specific page or pages and click on add nothing seems to happen so you cannot add pages. This seems to be in Files and Preview Files

### Steps To Reproduce

1. Startup Settings.
2. Open Specific Page or Pages.
3. Click Add.

### Steps to fix

Correct action happens when clicking...

### Files Version

2.4.25.0

### Windows Version

Windows 10 22H2

### Log file

[debug.log](https://github.com/files-community/Files/files/10517493/debug.log)

**Comment by Josh-65** [comment]
Merging with #11018

**Comment by DW-Andy** [comment]
Thanks Josh-65.
