### ISSUE TITLE
Missing strings in language source file

### ISSUE THREAD

**Issue by smarquespt** [files-community/Files#11101]
### Description

Problems with source strings:

**Settings - Appearance**

![image](https://user-images.githubusercontent.com/1302668/215225924-0475038f-e0c1-42a0-bf51-5172ec9767a9.png)

**There is one similar but not the same:**

![image](https://user-images.githubusercontent.com/1302668/215226003-2e9d0955-a596-476c-9151-4e2ff99c4713.png)

**There's an issue in Settings strings itself, don't see them in Crowdin.**

![image](https://user-images.githubusercontent.com/1302668/215226113-e2d4d026-2b5d-421b-963f-f41695f4e58d.png)

**Another issues in Settings - Folders, don't see itin Crowdin**

![image](https://user-images.githubusercontent.com/1302668/215226360-01fdf331-307a-4c4d-b653-8fa8eab97353.png)
![image](https://user-images.githubusercontent.com/1302668/215226672-77b5a23c-da01-4081-87af-6e0ee5035a19.png)

**Also in Settings - Folders, suplicate string in Crowdin, translated in PT not showing in app:**

![image](https://user-images.githubusercontent.com/1302668/215226593-f25156cc-457f-4a10-9613-1dde7c1b3ac6.png)
![image](https://user-images.githubusercontent.com/1302668/215226613-23194c0d-dcee-486a-9459-593110e172bb.png)

**In Settings - Advanced, also not in Crowdin.**

![image](https://user-images.githubusercontent.com/1302668/215226924-023ad8e5-0bc3-406f-a6be-30c293256734.png)

**And in Settings - About, a bunch of them:**

![image](https://user-images.githubusercontent.com/1302668/215227041-27c22e53-6ab7-4356-962f-7ef16e1e733e.png)
![image](https://user-images.githubusercontent.com/1302668/215227069-1c60de00-df98-4575-8c3a-f5dcf8c16b7a.png)

### Steps To Reproduce

Check above

### Steps to fix

Fix strings

### Files Version

V2.4.25

### Windows Version

W10 Home

### Log file

Not related to logs

**Comment by yaira2** [comment]
`UseCompactStyles` is the correct resource, I'm having a hard time following this issue but if you still need help, please start a discussion on Crowdin.
