### ISSUE TITLE
Select next file in folder's sort order after move or delete

### ISSUE THREAD

**Issue by benji78** [files-community/Files#11108]
### What feature or improvement do you think would benefit Files?

After moving or deleting a file in my downloads folder (which I prefer to sort by Date modified), the next file in alphabetical order gets selected (not the next one in the folder's sort order).
This is especially annoying in folders where there are lots of files and/or in large grid view.
For example when I want to delete and move multiple files I just downloaded, I find myself having to scroll back to the top after the page has reloaded multiple times.

Steps to reproduce:
Have multiple files in a folder sorted by anything other than file name.
Select a file (ideally at the top) and move or delete it.
The next file in alphabetical order is selected even if it is all the way down the page.
You then have to scroll all the way back to the top (or wherever you were making changes at) to keep working on your files.

### Requirements

This needs a code change to select the next file in the order defined for this specific folder and not in alphabetical order or the default one (defined in the settings).

### Files Version

Version: 2.4.25.0 OS Version: 10.0.19045.2486

### Windows Version

Windows 10 22H2

### Comments

I did not have any logs to share so I was not certain you would call this a bug hence the feature request.

**Comment by ferrariofilippo** [comment]
#9429 may be linked

**Comment by benji78** [comment]
What I described is indeed the conclusion they ended up at in #9624. I guess I couldn't find it in search and didn't go back as far as July.
I don't have the time right now to look into the code and make a PR, but I have had this issue for a while now and I just wish it would get fixed. 😉
