### ISSUE TITLE
Orden de columnas

### ISSUE THREAD

**Issue by jrmccsa** [files-community/Files#11102]
### What feature or improvement do you think would benefit Files?

Cómo se pueden reordenar las columnas ??
![Captura de pantalla 2023-01-28 133425](https://user-images.githubusercontent.com/123813496/215266643-bc148c09-8327-4449-8128-5e0810822afb.jpg)

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.4.25.0

### Windows Version

Windows 11

### Comments

![Captura de pantalla 2023-01-28 133425](https://user-images.githubusercontent.com/123813496/215266685-0867841f-a006-4b58-b665-2259b9406007.jpg)

**Comment by ferrariofilippo** [comment]
Duplicate #8385
