### ISSUE TITLE
Bug: Recycle bin original path and data deleted columns are set to 0 width

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#11103]
### Description

When I edit any column in details view out of the recycle bin original path and date deleted will be set to 0

### Steps To Reproduce

1. Turn off Files settings > Folder > Enable overriding folder preferences in individual directories
2. Go to recycle bin and set either original path or date deleted
3. Go to any other folder and edit size of a column
4. Go back to recycle bin and see both columns at 0 width

### Steps to fix

- Keep width of columns when others are edited.

### Files Version

2.4.25.0

### Windows Version

10.0.22621.1105

### Log file

[debug.log](https://github.com/files-community/Files/files/10527647/debug.log)

**Comment by ferrariofilippo** [comment]
This will be fixed with #11027
