### ISSUE TITLE
Popup menu items not clickable when over titlebar

### ISSUE THREAD

**Issue by Tamnac** [files-community/Files#11105]
### Description

If a popup menu crosses the titlebar, items on top of the titlebar are not selectable or clickable.

### Steps To Reproduce

1. Open files (not fullscreen)
2. Open popup menu (the "new" button usually works best)
3. Try to select elements crossing the titlebar

### Steps to fix

- Items over titlebar should be clickable

### Files Version

Version: 2.4.25.0 OS Version: 10.0.19045.2486

### Windows Version

Windows 10 22H2

### Log file

[debug.log](https://github.com/files-community/Files/files/10529274/debug.log)

**Comment by yaira2** [comment]
Merging with #10823
