### ISSUE TITLE
Feature: Change folder view context menu's position

### ISSUE THREAD

**Issue by Hareki** [files-community/Files#11106]
### What feature or improvement do you think would benefit Files?

The folder view context menu's top-left corner should be at cursor when right-clicking (bottom-left corner when there's not enough space) in order to: 

1. Make it more intuitive, similar to most context menus. I personally think it's a bit off when the context menu appears directly below my cursor.
2. Maintain consistency with the File Explorer. (Windows in general)

This is what it currently looks like when right-clicking:

![files](https://user-images.githubusercontent.com/81374684/215318421-4e36cfaf-5de0-4c1d-aea4-dc70e6b98e9d.gif)

### Requirements

Position the folder view context menu as it is done in the File Explorer:

![explorer](https://user-images.githubusercontent.com/81374684/215318428-67efbe36-3f7f-4596-9cfa-524aa83a5810.gif)

### Files Version

Version: 2.4.25.0

### Windows Version

Windows 11 22H2 22623.1245

**Comment by Josh-65** [comment]
The is excepted behaviour. File explorer hasn't fully use the new standard of WinUI which Files is.
