### ISSUE TITLE
Where is "List View"?

### ISSUE THREAD

**Issue by sumasage** [files-community/Files#11113]
### What feature or improvement do you think would benefit Files?

I updated to the current version and saw that the "list view" is no longer there.  Is there a way to re-enable it? Thank you.

### Requirements

Not sure is needed.  

### Files Version

Version: 2.4.25.0

### Windows Version

Windows 11 22H2

**Comment by yaira2** [comment]
List view has never been supported but it's on the roadmap.

**Comment by yaira2** [comment]
@sumasage thank you for your patience, I'm excited to share that a List View layout will be included in the next release.

**Comment by sumasage** [comment]
> @sumasage thank you for your patience, I'm excited to share that a List View layout will be included in the next release.

Awesome!! thank you dev team for your hard works.
