### ISSUE TITLE
Make it possible to change folders' color

### ISSUE THREAD

**Issue by SteveWorkshop** [files-community/Files#11119]
### What feature or improvement do you think would benefit Files?

Presonalize the look and feel via changing folders' color
e.g. set it blue to look like iPadOS' file manager app

### Requirements

- This proposal will give an option to set folder color

### Files Version

2.4.25.0

### Windows Version

windows11 22623.1245

**Comment by yaira2** [comment]
Thank you for your feedback, you can customize folder thumbnails from the custimization tab in the properties window.

**Comment by SteveWorkshop** [comment]
> Thank you for your feedback, you can customize folder thumbnails from the custimization tab in the properties window.

Oh, I mean changing the UI color. the folder element, in other words, this widget, is yellow. I hope we can select other color for this element, like a pink folder
<img width="78" alt="image" src="https://user-images.githubusercontent.com/92452488/215518772-8205e57c-9e78-4370-9100-e0841e28075f.png">
This picture, the folder widget, you can give some different styles to choose, just like changing app theme

**Comment by yaira2** [comment]
You mean like across the board? We're tracking this in #10941.

There are some programs in Windows that can already do this but I don't know them offhand and they aren't recommended since they make modifications to the system.
