### ISSUE TITLE
Show warning for permanent deletion; no warning otherwise

### ISSUE THREAD

**Issue by reidprichard** [files-community/Files#11126]
### What feature or improvement do you think would benefit Files?

First off, love the app. Incredible work!

One thing I miss about Windows Explorer is its style of deletion warnings. When a file is deleted to the recycle bin, it does not provide a warning, but it does warn you for permanent deletions, such as 1) deleting a file from a network drive and 2) deleting a file with the shift+delete hotkey.

From what I can tell, Files seems to be all-or-nothing, warning in all cases when the option "Folders > Show confirmation dialog when deleting items" is enabled and never warning when the option is disabled.

### Requirements

The "show confirmation dialog when deleting items" preference will have three options:
- "Always warn": whenever a file is deleted, a confirm dialog will appear.
- "Never warn": no confirmation dialog will be shown for file deletion.
- "Warn for permanent deletions": in the case of permanent deletions (e.g., deleting a file from a network drive, or deleting a file with the shift+delete shortcut), a confirmation dialog will be shown. When files are deleted to the recycle bin, no confirmation dialog will be shown.

### Files Version

2.4.25.0

### Windows Version

Edition	Windows 11 Home Version	22H2 Installed on	‎9/‎30/‎2022 OS build	22621.1105 Experience	Windows Feature Experience Pack 1000.22638.1000.0

**Comment by reidprichard** [comment]
Wow, really? I would have thought that would be the minority view. Is having three options as I suggested too complicated?

**Comment by Josh-65** [comment]
It would make sense to have it show for permeant delete except for the recycle bin since the user already knows that it will be permanent.

**Comment by hishitetsu** [comment]
It seems that the current Files always brings up a confirmation dialog when emptying the trash. I think that should be left as it is.
Should we add a new setting to confirm permanent deletion?

**Comment by yaira2** [comment]
> It would make sense to have it show for permeant delete except for the recycle bin since the user already knows that it will be permanent.

We used to but users complained

**Comment by reidprichard** [comment]
> It seems that the current Files always brings up a confirmation dialog when emptying the trash. I think that should be left as it is. Should we add a new setting to confirm permanent deletion? Or, should the dialog always appear regardless of the setting?

I agree that it makes sense to always warn when emptying the trash. However, this is inconsistent with the behavior where permanent deletions elsewhere are treated no differently.


One large reason I would find this useful is that I often work from a NAS with no recycle bin. When deleting files, it's nice to have the reminder that deletion will be permanent so that I am forced to stop and think whether I really should delete the file before I click okay. In contrast, I give little thought to deleting files locally as I know there will be a long period where they are accessible in my recycle bin (not to mention that anything important is backed up to cloud storage).

**Comment by hishitetsu** [comment]
How about this?
![image](https://user-images.githubusercontent.com/66369541/217394801-d178edac-6012-4ade-b03b-b3789881b155.png)

**Comment by hishitetsu** [comment]
Ok, I will make it later.

**Comment by reidprichard** [comment]
> How about this? ![image](https://user-images.githubusercontent.com/66369541/217394801-d178edac-6012-4ade-b03b-b3789881b155.png)

That's exactly what I had in mind, looks great!
