### ISSUE TITLE
Crash when dragging mouse on any file or folder

### ISSUE THREAD

**Issue by gpexio** [files-community/Files#11127]
### Description

Hello. Starting from version 2.4.25.0 I am experiecing a costant crash everytime that I try to drag a file or a folder around. It does not matter where I try to drop it, since Files will freeze and crash as soon as I begin dragging.
It happens every single time, any file or folder.

### Steps To Reproduce

1. Go to any file or folder in Files
2. Press and hold left mouse button on it
3. Begin to drag the file or folder
4. Files will freeze as soon as you start dragging and will crash shortly after

### Files Version

Version 2.4.25.0

### Windows Version

Windows 11 Pro 21H2

### Log file

[debug.log](https://github.com/files-community/Files/files/10559093/debug.log)

**Comment by yaira2** [comment]
Are you running Files as administrator?

**Comment by gpexio** [comment]
> Are you running Files as administrator? There is an issue in Windows where drag and drop crashes apps (WinAppSdk) running as administrator.

Looks like it was it. Weirdly enough, when the app crashes, it keeps opening again as admin. I don't remember doing that tho. I force closed it and opened it manually from the app list and all seems working fine.
Thanks!
