### ISSUE TITLE
Preview

### ISSUE THREAD

**Issue by ramusiol** [files-community/Files#11129]
### What feature or improvement do you think would benefit Files?

The file preview is (just) not large enough to read texts in a pdf. No function to set it.

### Requirements

preview function

### Files Version

2.4.25.0

### Windows Version

10

### Comments

In Win Explorer is that possible (comfortable).
A readable is crucial to use the app with text files.

**Comment by yaira2** [comment]
You can resize the review pane by holding down on the divider line and dragging it.

**Comment by ramusiol** [comment]
that does not change the size of the previewed file

**Comment by yaira2** [comment]
That's because of the details pane. The app needs to be made taller as well.

**Comment by ramusiol** [comment]
![image](https://user-images.githubusercontent.com/124191303/216151808-107621c9-01fa-42fd-bee5-89eb2a97557b.png)
no, obviously not

**Comment by Josh-65** [comment]
If you don't need details you can right click and enable show preview only

**Comment by ramusiol** [comment]
details are switched off already, see picture. that doesn't change anything.

**Comment by yaira2** [comment]
There seems to be a bug where it hides the details but doesn't expand the preview, will take a look at this.

**Comment by ramusiol** [comment]
Thank you

**Comment by yaira2** [comment]
Can you open a bug report to track this?
