### ISSUE TITLE
Files Preview Failed

### ISSUE THREAD

**Issue by foursplaysroblox** [files-community/Files#11124]
Hi when I try to install Files Preview it won't let me

![image](https://user-images.githubusercontent.com/82078139/215925157-1479e149-7d6e-4f8d-94f8-208b35adbb6e.png)

**Comment by Josh-65** [comment]
Can you try using
1. Opening PowerShell window as administrator
2. Run this command   Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/preview/Files.Package.appinstaller

**Comment by foursplaysroblox** [comment]
it works thank you
