### ISSUE TITLE
startup speed is too slow

### ISSUE THREAD

**Issue by imchuyun** [files-community/Files#11138]
### Description

The software startup speed is too slow. The edge browser has not responded after opening the download folder for half a day.

### Steps To Reproduce

The software startup speed is too slow. The edge browser has not responded after opening the download folder for half a day.

### Steps to fix

The software startup speed is too slow. The edge browser has not responded after opening the download folder for half a day.

### Files Version

版本: 2.4.25.0 OS Version: 10.0.22000.1335

### Windows Version

11 21h2

### Log file

The software startup speed is too slow. The edge browser has not responded after opening the download folder for half a day.

**Comment by yaira2** [comment]
We're excited to share that startup performance will be significantly improved in the upcoming release of version 3. You can download the preview version from our website https://files.community/download.
