### ISSUE TITLE
Bug: Favourite shows as blank and nothing can be pinned

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#11139]
### Description

When I open Files on my VM it shows favourites as blank when File Explorer has the recycle bin pinned. Adding anything to it will crash Files. This doesn't affect my own version of Files

### Steps To Reproduce

1. Open Files
2. See Favourites is blank
3. Open a drive and try pin a folder
4. See Files crashes

### Steps to fix

?

### Files Version

2.4.27

### Windows Version

10.0.25290.1000

### Log file

[debug.log](https://github.com/files-community/Files/files/10576266/debug.log)

**Comment by hecksmosis** [comment]
Sorry, this is me being stupid and not realizing there can be 0 recent items
