### ISSUE TITLE
Show a warning dialog if the user tries to close the application when performing an operation (copy/paste, etc.)

### ISSUE THREAD

**Issue by SnowVolf** [files-community/Files#11134]
### What feature or improvement do you think would benefit Files?

For example, I copy a 45 GB file to my USB flash drive.This is quite a long operation, even for USB 3.0. After a while I switch between applications, and accidentally hitting the explorer, I press the close button. The application closes, although the copying is not finished. As a result, the time spent, and the file on the flash drive turned out to be broken.
It is necessary to monitor the execution of such lengthy operations, and show a warning dialog that an operation is being performed and the copy will not be completed

### Requirements

- Add a check to perform an operation like copy/move/paste

### Files Version

2.4.25

### Windows Version

Windows 11 22H2 22623.1095

**Comment by yaira2** [comment]
Merging with #8207
