### ISSUE TITLE
Cut and paste the opening Word document from explorer to Files caused crash

### ISSUE THREAD

**Issue by Shazoo** [files-community/Files#11132]
### Description

as title . 

### Steps To Reproduce

Cut the word files with ctrl+x in explorer .  %USER%\Desktop
Paste the word files in Files with ctrl+v .   %USER%\OneDrive

Business LTSC Win10 with Business OneDrvie. 

Crashed and lost a file . 

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

版本: 2.4.25.0 OS Version: 10.0.19044.2486

### Windows Version

版本	Windows 10 企业版 LTSC 版本号	21H2 安装日期	‎2022/‎9/‎28 操作系统内部版本	19044.2486 体验	Windows Feature Experience Pack 120.2212.4190.0

**Comment by yaira2** [comment]
Was the word document open at the time?

**Comment by yaira2** [comment]
Can you please attatch the log file to the issue descirption?
