### ISSUE TITLE
Bug installing the update

### ISSUE THREAD

**Issue by ejmurray** [files-community/Files#11141]
### Description

I am not sure when the error occurred here, but the log has been attached for your convenience.

### Steps To Reproduce

Open the application and look at the icon in the top right to show that there is an update.
Click on the update icon and proceed to use the app.

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

Version: 2.4.25.0 OS Version: 10.0.19045.2486

### Windows Version

Windows 10

### Log file

[debug.log](https://github.com/files-community/Files/files/10578370/debug.log)

**Comment by yaira2** [comment]
This should be resolved
