### ISSUE TITLE
Bug relate cloud drive

### ISSUE THREAD

**Issue by Bao1296** [files-community/Files#11145]
### Description

I have 2 error relate cloud drive
![image](https://user-images.githubusercontent.com/42288514/216661654-d4f2e5a5-8b55-442f-9f24-979b7e7fd999.png)

1. Red Color: I have 2 sharepoint (cicamt and Vilai Viet same as Win explorer), but in File (right), it shows only cicamt sharepoint, but when i click to cicamt folder, it show folder in vilai viet sharepoint. How can Files show both 2 sharepoint?
2. Green color: I use Autodesk Drive (https://drive.autodesk.com/) and it shows in Explorer same as a drive, can Files add Autodesk Docs and Drive as a cloud drive.

Thank you so much.

### Steps To Reproduce

.

### Steps to fix

.

### Files Version

2.4.25.0

### Windows Version

Win 10 22H2 19045.2486

### Log file

[debug.log](https://github.com/files-community/Files/files/10581057/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, we're tracking the SharePoint issue here #4966. Can you open a feature request for Autodesk?
