### ISSUE TITLE
Feature: Support Autodesk Drive and BIM 360 cloud drive

### ISSUE THREAD

**Issue by Bao1296** [files-community/Files#11147]
### What feature or improvement do you think would benefit Files?

![image](https://user-images.githubusercontent.com/42288514/216664962-47c24491-ad4c-4e0f-92ec-5b62129fb3f6.png)

Green color: I use Autodesk Drive (https://drive.autodesk.com/) and it shows in Explorer same as a drive, can Files add Autodesk Docs and Drive as a cloud drive.
Thank you so much.

### Requirements

.

### Files Version

2.4.25.0

### Windows Version

Win 10 22H2 19045.2486

**Comment by hecksmosis** [comment]
I can do this, it's the same as some other PRs I've done

**Comment by Bao1296** [comment]
> I can do this, it's the same as some other PRs I've done

I'm looking forward from you about your solution
