### ISSUE TITLE
Files crashes when attempting to open settings

### ISSUE THREAD

**Issue by anditv21** [files-community/Files#11152]
### Description

Files sometimes crashes when I try to open the settings.

### Steps To Reproduce

1. Click on settings icon

### Steps to fix

- Fix crash that sometimes occurs when you click on the Settings icon

### Files Version

Version: 2.4.25.0
OS Version: 10.0.19045.2364

### Windows Version

Windows 10 Pro 22H2

### Log file

[debug.log](https://github.com/files-community/Files/files/10582298/debug.log)

**Comment by yaira2** [comment]
What version of Files?

**Comment by anditv21** [comment]
I use version: 2.4.25.0

**Comment by yaira2** [comment]
Can you try v2.4.30?

**Comment by anditv21** [comment]
With the new version the error has not occurred again yet
