### ISSUE TITLE
UNC Support

### ISSUE THREAD

**Issue by Typod01** [files-community/Files#11158]
### What feature or improvement do you think would benefit Files?

Any chance of adding UNC support?  In the explorer bar I would like to be able to enter a UNC path such as \\servername\share as you can with Windows File Explorer.

### Requirements

Be able to enter a UNC path in the explorer bar
Allow for authenticated connections i.e prompting for username/password if the share is secure

### Files Version

2.4.24.0

### Windows Version

22623.1180

**Comment by yaira2** [comment]
Same as #258?
