### ISSUE TITLE
Crash when scrolling while dragging

### ISSUE THREAD

**Issue by Twentydragon** [files-community/Files#11159]
### Description

When attempting to move an item by dragging to a folder that's scrolled off-screen, Files closes itself with no error message popup.

### Steps To Reproduce

1. Enter a folder with enough files that it requires scrolling to see them all.
2. Drag a file from near the bottom toward the top edge to scroll.
3. Watch Files exit/crash.

### Steps to fix

- Fix crashing when dragging files near the top and bottom of the window.

### Files Version

Version: 2.4.25.0 OS Version: 10.0.19045.2486

### Windows Version

Edition	Windows 10 Home Version	22H2 Installed on	‎2021-‎07-‎30 OS build	19045.2486 Experience	Windows Feature Experience Pack 120.2212.4190.0

### Log file

[debug.log](https://github.com/files-community/Files/files/10610073/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/10610074/debug_fulltrust.log)

**Comment by Josh-65** [comment]
Merging with #11149
