### ISSUE TITLE
Auto and/or Manual Update button

### ISSUE THREAD

**Issue by sfksuperman** [files-community/Files#11157]
### What feature or improvement do you think would benefit Files?

Need an UPDATE button for automatic and/or manual updates.

### Files Version

2.4.25.0

### Windows Version

Windows 11 22H2 22621.1194

**Comment by Josh-65** [comment]
There is already an update button next to settings when one is available.

**Comment by sfksuperman** [comment]
<img width="904" alt="image" src="https://user-images.githubusercontent.com/34414624/218957030-601c1e04-1a1c-483a-9abf-f527c60f893c.png">
Could you please reopen and check this issue? The latest version is 2.4.34 (discord) and 2.4.33 (github) and I have installed 2.4.25.0 so I don't see any update button or option anywhere. Please check.

**Comment by Josh-65** [comment]
Downloaded the installer https://files.community/appinstallers/Files.Stable.exe and use that to update then future update should be fine

**Comment by sfksuperman** [comment]
I don’t understand. Every time I need to do that and still you close the
issue expecting the feature I opened this for. I seriously don’t understand.

**Comment by Josh-65** [comment]
You have only opened 1 other issue about it. There are also times were it doesn't work because of app installer or brakes on certain version numbers. Do the manual way and if it has the issue again open a bug report for it.
