### ISSUE TITLE
Allow changing font size (and maybe font family) 

### ISSUE THREAD

**Issue by klaro00** [files-community/Files#11161]
### What feature or improvement do you think would benefit Files?

Please allow changing font size (and maybe font family) - I like a smaller font.

### Files Version

2.4.x

### Windows Version

Windows 11

**Comment by Josh-65** [comment]
You can change the font following the instructions at https://files.community/docs/configuring/custom-themes

**Comment by klaro00** [comment]
Thanks (for the fastest anwer ever for a submitted ticket).

**Comment by klaro00** [comment]
Closed
