### ISSUE TITLE
possibility to change the file transfer manager

### ISSUE THREAD

**Issue by barthoum47** [files-community/Files#11162]
### What feature or improvement do you think would benefit Files?

Hello,

Your works on Files is amazing, despite some unstabilities

One of them is the bundled file transfer manager.

Could that be possible to add a settings to choose the software used for those operations

- Files bundled manager
- windows bundled manager
- Teracopy
- other

Thanks

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.4.25

### Windows Version

Windows 11 22H2

**Comment by Josh-65** [comment]
Merging with #7518
