### ISSUE TITLE
Copy with Windows Dialog or TeraCopy

### ISSUE THREAD

**Issue by nbkdnz0r** [files-community/Files#11168]
### What feature or improvement do you think would benefit Files?

In my opinion the browser lacks of this feature: to choose the copy mechanism, like the windows dialog or some program like TeraCopy instead of the Files Internal Copy Mechanism.
Everything else is flawless.

### Requirements

- An option button in the menu.
- choose between the files copy and windows own (teracopy overwrites that, for example)

### Files Version

2.0.36.0

### Windows Version

22H2

### Comments

Please. :>

I want to copy with TeraCopy, this is an far more advanced Tool than the Copy Mechanism inside of Files Explorer. Too often theres only an error sign and I have to switch to another browser.

**Comment by yaira2** [comment]
Merging with #7518
