### ISSUE TITLE
Minimize to the task bar TRAY

### ISSUE THREAD

**Issue by meemore** [files-community/Files#11163]
### Description

If you right click on the Minimize button the icon is missing see screenshot of my system

![Screenshot_1](https://user-images.githubusercontent.com/124497263/216815615-475a9751-9427-4c97-8550-150948d69c42.jpg)

### Steps To Reproduce

You have to have RB Tray program to right click on Minimize button in the first place

### Steps to fix

It should also be a built in feature to right click on minimize button to send to Tray

### Files Version

win11

### Windows Version

win11

### Log file

I have no log  the icon is MISSING

**Comment by Josh-65** [comment]
Files doesn't support minimizing to taskbar and is properly a conflict with what ever you are using. There's are plans to add native support for it and with some feature with it.

**Comment by meemore** [comment]
This is the program tool I use to send items to the Tray
![Screenshot_3](https://user-images.githubusercontent.com/124497263/216815881-ad130ac4-1c52-4b86-ae8c-67aa2f204102.jpg)
