### ISSUE TITLE
Bundles Remove confirmation

### ISSUE THREAD

**Issue by meemore** [files-community/Files#11172]
### What feature or improvement do you think would benefit Files?

I wanted to rename a bundle, and I clicked remove bundle,   this needs a "Are you sure you want to delete"  because I made the mistake and poof it was gone.

![Screenshot_1](https://user-images.githubusercontent.com/124497263/216856691-5e8f3f6f-2f38-416e-a2b6-e2fd6b0e95fa.jpg)

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

win11

### Windows Version

win11

**Comment by yaira2** [comment]
Thank you for your feedback, starting in v2.4.30 (available later this week), bundles will be replaced with a tags widget. This will work a little differently but will solve this issue as well.
