### ISSUE TITLE
Copy Box, Bundle Box Temp Box

### ISSUE THREAD

**Issue by meemore** [files-community/Files#11173]
### What feature or improvement do you think would benefit Files?

You should all a copy box area feature, so when you go threw your system and find files you want to copy paste,  there should be a temp box were you can put a bunch of stuff , then nav to the areas you want and drag them down, into the folder , place you want it to be placed.

![Screenshot_2](https://user-images.githubusercontent.com/124497263/216857117-e6f4275f-46f5-4964-8356-445c4a6b7a19.jpg)

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

win11

### Windows Version

win11

**Comment by yaira2** [comment]
Merging with #6514
