### ISSUE TITLE
Home is empty, Favorites is empty and cannot be added to, Drives is empty, etc.

### ISSUE THREAD

**Issue by Stuie** [files-community/Files#11178]
### Description

I recently installed `2.4.30.0` and when I opened it up my `Favorites` list was empty. The `Drives` section in the sidebar is completely empty, but if I type the drive letter in the address bar then the drives are still accessible. The `Home` section contained absolutely nothing. I am unable to add items to my `Favorites` section in the sidebar.

I previously had version `2.4.11.0` installed, and the `Favorites` list was partially populated, it was missing one directory I added before. The drives were not showing up in the sidebar.

I have uninstalled and reinstalled Files and the problem persists.

My most recent launch of Files actually shows the C drive, but none of my others. I can access D:, E:, and F: from PowerShell without any problems.

### Steps To Reproduce

These steps are clearly not going to work for everyone, otherwise there would be a huge problem, but for me the steps are:

1. Open Files
2. Files is not showing anything in Drives, or Home, or Favorites.

### Steps to fix

I haven't been able to find any steps to fix this, including uninstalling and reinstalling Files.

### Files Version

2.4.30.0

### Windows Version

Edition	Windows 11 Pro Version	22H2 Installed on	‎10/‎5/‎2022 OS build	22621.1105 Experience	Windows Feature Experience Pack 1000.22638.1000.0

### Log file

[debug.log](https://github.com/files-community/Files/files/10658712/debug.log)

**Comment by yaira2** [comment]
A fix will be available in the next release.
