### ISSUE TITLE
App closes after about 5 seconds

### ISSUE THREAD

**Issue by cmactavish** [files-community/Files#11179]
### Description

About 5 seconds after opening the app, the blue loading icon pops up next to my cursor, then files closes.

### Steps To Reproduce

1. Open Files
2. wait 5 seconds
3. Files closes

### Steps to fix

Doesn't crash if I open File Explorer and double click a folder which then opens in Files, since Files is set as default.
Issue not present after rolling back to 2.4.25

### Files Version

2.4.30

### Windows Version

Windows 11, Version 22H2, OS Build 22621.1194

### Log file

[debug.log](https://github.com/files-community/Files/files/10659938/debug.log)

**Comment by yaira2** [comment]
A fix is being deployed
