### ISSUE TITLE
Bug: Rotating image causes crash

### ISSUE THREAD

**Issue by anditv21** [files-community/Files#11171]
### Description

Files crashes when trying to rotate an image

### Steps To Reproduce

1. Select a image
2. Click "Rotate Left" or "Rotate Right"

### Steps to fix

- Fix crash that occurs when you click on "Rotate Left" or "Rotate Right" on an image

### Files Version

Version: 2.4.25.0 OS Version: 10.0.19045.2364

### Windows Version

Windows 10 Pro 22H2 19045.2364

### Log file

[debug.log](https://github.com/files-community/Files/files/10625768/debug.log)

**Comment by yaira2** [comment]
What kind of image file?

**Comment by anditv21** [comment]
I hope this informations are helpful:
- Filetypes: png/gif
- Dimensions: 128x128 px

The files have only been downloaded from discord or google and have been renamed.

**Comment by yaira2** [comment]
Were both file types selected?

**Comment by anditv21** [comment]
Yes
But with only the png file selected it also crashes

**Comment by yaira2** [comment]
Can you see if it's an issue in the preview version?

**Comment by anditv21** [comment]
With the current version v.2.4.33 it still crashes.
[debug.log](https://github.com/files-community/Files/files/10748846/debug.log)

**Comment by anditv21** [comment]
With the version: 2.4.40.0 it also crashes
and the log says exactly the same as the times before

**Comment by yaira2** [comment]
Are you using the right click menu or the toolbar buttons?

**Comment by anditv21** [comment]
Using the right click menu I get this error message.
However, these are normal jpeg files.

![image](https://user-images.githubusercontent.com/75949923/220001761-b8ca9aa6-3cf8-4bfe-93b3-64733d0c12b6.png)

**Comment by yaira2** [comment]
Does it work in File Explorer?

**Comment by anditv21** [comment]
yes

**Comment by yaira2** [comment]
Can you see if this happens when running Files as admin? It shouldn't require this but it'll help us debug.

**Comment by anditv21** [comment]
When I run files as administrator it also crashes and I get the same error message

**Comment by lucas-thiebaut** [comment]
@yair100 In the last version which is version 2.4.81 I can't reproduce this problem either in the contextual menu or in the top bar and even as administrator

**Comment by anditv21** [comment]
The problem no longer occurred to me in the newer versions.
