### ISSUE TITLE
Files won't show my drives. 

### ISSUE THREAD

**Issue by nihil-cmyk** [files-community/Files#11189]
### Description

It won't show any of my drives even the primary drive. If I type in the address it'll take me to the destination but i just can't navigate through them. This is especially difficult when I have to transfer stuff from my phone. 

### Steps To Reproduce

![files headache](https://user-images.githubusercontent.com/83378957/217057921-d5a18985-1902-47c1-ba7f-c7c6b9a54f87.jpg)

### Steps to fix

Just fix the it so the drives would be visible. 

### Files Version

Version: 2.4.25.0 OS Version: 10.0.22621.1105

### Windows Version

Edition	Windows 11 Enterprise Version	22H2 Installed on	‎25-‎Nov-‎22 OS build	22621.1105 Experience	Windows Feature Experience Pack 1000.22638.1000.0

### Log file

[debug.log](https://github.com/files-community/Files/files/10668172/debug.log)

**Comment by hecksmosis** [comment]
Do they show in the Drives widget?

**Comment by hecksmosis** [comment]
The log file does not seem to register anything, that seems strage

**Comment by yaira2** [comment]
Can you check if file system access is turned off?
![image](https://user-images.githubusercontent.com/39923744/217067009-1adba641-73ee-48cd-a9f5-5b3276192068.png)

**Comment by nihil-cmyk** [comment]
> Can you check if file system access is turned off? ![image](https://user-images.githubusercontent.com/39923744/217067009-1adba641-73ee-48cd-a9f5-5b3276192068.png)

Both are checked same as the screenshot you provided.

**Comment by yaira2** [comment]
What happens if you manually navigate to the drive using the address bar?

**Comment by nihil-cmyk** [comment]
> What happens if you manually navigate to the drive using the address bar?

It opens the address. But the problem is that I don't know the assigned letter if I plug in an external drive. Or phone where it doesn't even assign a letter.

**Comment by yaira2** [comment]
I'm stumped, maybe @Josh-65 knows.

**Comment by Josh-65** [comment]
Not sure myself. You can try
1. Running the below command in an admin CMD, Restart your system when there done
```
sfc /scannow
dism /online /cleanup-image /restorehealth
```
2. Reinstall Files

**Comment by yaira2** [comment]
@nihil-cmyk please let us know if this helps.

**Comment by nihil-cmyk** [comment]
> @nihil-cmyk please let us know if this helps.

nope it didn't. Josh-65 suggested it on the discord chat as well. The other day it showed a CD rom drive which is a drive i don't have a CD on this machine. Today it's gone again. It happened just random no idea what's causing this bug.

**Comment by yaira2** [comment]
Can you see if it works in RX-Explorer?

**Comment by nihil-cmyk** [comment]
> Can you see if it works in RX-Explorer?

https://github.com/zhuxb711/RX-Explorer this project? lemme try. The interface seems good. If it runs okay it the $2.60 I'll pay for it will save me on ibuprofen :D

**Comment by nihil-cmyk** [comment]
![image](https://user-images.githubusercontent.com/83378957/217619442-a48d1a5c-2711-491e-9a0f-08e89665430a.png)

shows the drives.. hope it won't crash like the native explorer does. Thanks

**Comment by yaira2** [comment]
It's a different project and not connected to Files but good to see it's working. Can you try the preview version of Files?

**Comment by nihil-cmyk** [comment]
> What does it show in Windows File explorer. Your Windows install seem broken as many of the icons aren't showing, native explorer has crashing issues for you and you said you don't have a CD drive yet ones is shown.

same issues again. And RX explorer crashes when I connect my phone... headache after headache... maybe it's because i've upgraded to Windows 11 the first week they released it... i Can see that my primary storage is full anyways maybe installing a fresh copy of the OS will solve the existing problems i have with the native explorer...

**Comment by yaira2** [comment]
That seems like the best solution, I hope you give Files a try regardless because it has a lot to offer over File Explorer.

**Comment by nihil-cmyk** [comment]
> What does it show in Windows File explorer. Your Windows install seem broken as many of the icons aren't showing, native explorer has crashing issues for you and you said you don't have a CD drive yet ones is shown.

![image](https://user-images.githubusercontent.com/83378957/217621532-9cd4411d-0e35-4bd5-acfe-1618220dbfa1.png)
here's my Windows file explorer... everything is in place ... but that green line... it takes forever to load. everything would go fine for and suddenly it freezes and have to restart it. The CD drive is a virtual drive i use for viewing .iso files.
