### ISSUE TITLE
v2.4.31 Acrylic come back?

### ISSUE THREAD

**Issue by redhotideas** [files-community/Files#11182]
### What feature or improvement do you think would benefit Files?

Have you reintroduced the acrylic functionality for theme elements?
Thanks Angelo.

### Requirements

- go to settings
- appearance
- select mica or acrylic

### Files Version

v2.4.31 

### Windows Version

Windows 11 Pro Versione 22H2

### Comments

Please, I saw that with Win11 the acrylic effect is integrated correctly.

**Comment by Josh-65** [comment]
For theming follow the instructions at https://files.community/docs/configuring/custom-themes

**Comment by redhotideas** [comment]
Yes, but insert it with the possibility of activating it only with certain system requirements, so performance isn't a problem, I have a very performing computer and I don't want to give up one of the most beautiful aspects of Files. I'm working with an old version now.

**Comment by Josh-65** [comment]
Performance is only part of the issue. The other part is that it doesn't work properly in WinAppSDK.

**Comment by yaira2** [comment]
@redhotideas we hope to bring mica to older versions of Windows.
