### ISSUE TITLE
Feature: Adjust the color of the disk space progress bar according to remaining free space

### ISSUE THREAD

**Issue by myfix16** [files-community/Files#11181]
### What feature or improvement do you think would benefit Files?

The current version of Files is awesome! However, it would be better if the disk space progress bar could show different colors regarding different free space percentages.

For example, on my computer, the disk space usage bar looks like this:
<img width="381" alt="image" src="https://user-images.githubusercontent.com/61649477/217008311-6cd7714c-9544-4def-a2bf-2b08972b85a5.png">

The `D` drive is nearly full, and I think a red progress bar like the default explorer would be more informative. 
<img width="393" alt="image" src="https://user-images.githubusercontent.com/61649477/217008805-9adec5e8-72cf-4c0b-b7e7-b24ee963f88e.png">

My proposal:
- Free space >= 30%: Default accent color or blue
<img width="59" alt="image" src="https://user-images.githubusercontent.com/61649477/217009926-35b65c20-ff3c-4a22-a918-235d4294c5a3.png">

- Free space >= 10% and < 30%: Yellow
<img width="118" alt="image" src="https://user-images.githubusercontent.com/61649477/217009972-ae028147-3075-4fdf-86b4-1a8cdfced0ce.png">

- Free space < 10%: Red
<img width="116" alt="image" src="https://user-images.githubusercontent.com/61649477/217010053-ec46ef36-f08c-4615-9e02-e49a14fa038e.png">

### Requirements

- This proposal will accomplish: Adjust the color of the disk space progress bar according to the remaining free space

### Files Version

Version: 2.4.31.0 OS Version: 10.0.22623.1250

### Windows Version

Windows 11 22H2 22623.1250 (Beta)

**Comment by yaira2** [comment]
We could do this but we'd have to stop using the accent color.

**Comment by yaira2** [comment]
Thank you for your feedback, we don't have plans to implement this. We use an icon to indicate when the drive is getting full.
