### ISSUE TITLE
Infinite installation

### ISSUE THREAD

**Issue by pachino11188** [files-community/Files#11183]
### Description

Infinite installation. Which installer does the programme use?

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/112216717/217025057-6feb2493-6921-43a4-85f2-bfaae3830ce1.png)

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...
![image](https://user-images.githubusercontent.com/112216717/217024993-e53c32e9-76a6-4c58-9309-ff527e0980a3.png)

### Files Version

2.4.31.0

### Windows Version

Windows 10 Pro x64 (2009 build 19045)

### Log file

fff

**Comment by yaira2** [comment]
Can you try the preview version?

**Comment by yaira2** [comment]
It's a custom installer we just started using but we still need to add error handling.

**Comment by pachino11188** [comment]
Preview version dont work too

**Comment by pachino11188** [comment]
It doesn't report any errors.

**Comment by yaira2** [comment]
What happens?

**Comment by yaira2** [comment]
@Josh-65 I think 19045 isn't supported by Files.

**Comment by pachino11188** [comment]
There are no messages

**Comment by Josh-65** [comment]
10945 should be it the latest for Windows 10

**Comment by yaira2** [comment]
@pachino11188 does the installer open?

**Comment by pachino11188** [comment]
> 

Yep

**Comment by pachino11188** [comment]
![image](https://user-images.githubusercontent.com/112216717/217027261-3e29b278-b47e-4feb-87dd-3945b4456525.png)

But when I press install, nothing happens. The other installer just loads endlessly

**Comment by yaira2** [comment]
Can you translate this?
![image](https://user-images.githubusercontent.com/39923744/217069065-a0bd32b8-eb3e-423d-8571-a5be94dcbb26.png)

**Comment by anditv21** [comment]
"By installing this application, you agree that it will automatically check
for updates and install them."

**Comment by yaira2** [comment]
Can you go to the store page for Files and verify that your system meets the minimum requirements?

**Comment by Josh-65** [comment]
Can you try doing
1. Opening PowerShell window as administrator
2. Run this command
```Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/stable/Files.Package.appinstaller```
