### ISSUE TITLE
Feature: Add back ability to reorder pinned items

### ISSUE THREAD

**Issue by Jeyprox** [files-community/Files#11199]
### What feature or improvement do you think would benefit Files?

Before syncing the pinned items with Windows File Explorer, the app used to allow for moving the individual pins around.
Adding back that functionality would remove the need to go into the File Explorer App every time that you want to move a pin.
This is especially useful for newly added pins that appear at the bottom by default.

This functionality could either be in the form of Drag & Drop or an option inside the context menu of a pinned item.

### Requirements

- Add an option in the pinned item context menu to move the item up / down

or

- Add the option to Drag & Drop the pinned items in the list

### Files Version

2.4.31.0

### Windows Version

Windows 10 22H2 19045.2546

**Comment by yaira2** [comment]
@hecksmosis what do think about creating a dialog popup where users can drag and drop to the correct order and then save the changes?

**Comment by hecksmosis** [comment]
I think we could add a button to the sidebar to make the user able to move files as they wish and have a button appear below to save changes

**Comment by yaira2** [comment]
Eventually we'd want regular drag and drop, I'm curious to see what you have in mind but a dialog might be the simplest.
