### ISSUE TITLE
Discussion: Add a setting to disable tooltips

### ISSUE THREAD

**Issue by sillyrat** [files-community/Files#11195]
### What feature or improvement do you think would benefit Files?

There should be a setting to disable tooltips.  When the mouse pointer pauses over a file or folder, a tooltip appears.  In the Details and Columns layouts, the tooltip blocks the visibility of the names of files and folders behind it, and its utility is questionable as it duplicates information already visible in other columns.  The tooltips add unnecessary mental effort and annoyance as one must constantly think about where the mouse pointer is "parked" so that lists of files and folders aren't intermittently obscured by unwanted tooltips.

### Requirements

Add a switch under Settings --> Folders --> Display called "Show tooltips".

Also duplicate this switch in the Layout button's pop-up control panel, beneath the existing switches for "Show hidden items" and "Show file extensions".

### Files Version

Version: 2.4.31.0

### Windows Version

Windows 11 Pro, version 21H2, OS build 22000.1516

**Comment by yaira2** [comment]
What about the grid layouts?

**Comment by sillyrat** [comment]
To keep things simple, I'd have the "Show tooltips" switch affect *all* the layouts, including the left sidebar containing folders / drives / etc.  When I need to see details, I either switch to a different layout that shows me those details for all files/folders, or I right-click an individual item and choose the Properties button ("i" in a circle). 

By the way, there's a bug with the tooltips: after right-clicking an item and choosing the Properties button, and then closing the Properties window by clicking on either OK or Cancel, the tooltips stop displaying -- when hovering over an item, the selection highlight blinks a few times and then disappears, and no tooltip is shown.

**Comment by yaira2** [comment]
Was just testing the discussion feature in GitHub using this issue, sorry about that!

**Comment by rafaskb** [comment]
A checkbox never hurts. File Explorer has the exact same tooltip, so providing something extra on Files would be nice.

A simpler approach would be to just disbale tooltips _while the preview pane is enabled_, just so we don't have duplicated information. That, of course, would also need to be behind a checkbox somewhere, so users don't get confused about multiple UX designs according to what pane is or isn't active.

**Comment by LolicoreExpress** [comment]
I myself am a Details view user, and can't say it ever occured to me that this could be a hindrance to visibility.
But, it is true that is essentially shows duplicate information.
Maybe this could be a per-view thing ? Like, tooltip doesn't show in details view but does show in thumbnail mode or else.

**Comment by Spid3rrr** [comment]
I don't see it as a real hinderance either. It is duplicate information but only if you're using the Details view. However, I think it should be kept as is, since visually it's not really a problem, and I also think that some users are used to hovering anyways since tabs might be out of view etc.

**Comment by rafaskb** [comment]
> it's important to consider that Files has been successful by carefully choosing which options to add.

I think that's a great guideline, and it's clear in Files that all configuration options there are meaningful and important.

When we take that into consideration, I have to say that I don't see this issue as a priority, and definitely not something at least 20% of the users would use or even notice.

I also agree with the comments above about never seeing tooltips as a hindrance either, they work in such a natural way that I never even noticed they block information or show duplicates. I think they're really useful actually.

So my TL;DR would be: This would be nice but it's not a priority.

**Comment by jimboc1** [comment]
I can't say I ever noticed tooltips. Never seem to be in the one spot long enough.

- if it's redundant info like in the Details view, then it serves no purpose and is just another thing to maintain/translate. Remove completely.
- seeing the full path to Favorites and drive space left in the left panel I can see myself valuing (just discovered it answering this question).
- not a fan of options as they blow out in number and then take too long to find.

**Comment by yaira2** [comment]
One take away from this is that it's not providing value in the details layout, unless everyone feels otherwise, I think we can remove the tooltip from the details layout.
