### ISSUE TITLE
请改进这些细节

### ISSUE THREAD

**Issue by EricRenZirui** [files-community/Files#11194]
### What feature or improvement do you think would benefit Files?

![Snipaste_2023-02-07_09-26-43](https://user-images.githubusercontent.com/58595935/217124764-0fb3cf8f-27ab-4314-841d-40de5f5924a3.png)
![Snipaste_2023-02-07_09-26-05](https://user-images.githubusercontent.com/58595935/217124771-d12839bd-e0fc-45c2-a468-2339d2104142.png)
![Snipaste_2023-02-07_09-22-23](https://user-images.githubusercontent.com/58595935/217124767-1ebcf74d-1d36-49bf-90b8-ebb78657b415.png)

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.4.31.0

### Windows Version

25290.1000

**Comment by yaira2** [comment]
Can you please open a new issue and fill out the form so we can better understand the request?
