### ISSUE TITLE
Tool Tips turn on / off tool tips

### ISSUE THREAD

**Issue by meemore** [files-community/Files#11208]
### What feature or improvement do you think would benefit Files?

I Hope there is a option in future to turn on / off tool tips, sometimes they are nice, but I dont need to see them each time, hovering over the same thing.  

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

win11

### Windows Version

win11

**Comment by yaira2** [comment]
We're tracking this in #11195, please search before posting.
