### ISSUE TITLE
Bug: "Drive ejected: Not a folder" error message after language change 

### ISSUE THREAD

**Issue by myfix16** [files-community/Files#11203]
### Description

When I changed Files' language from English (US) to Windows default (Chinese Simplified in my case), I got an error dialog with header `驱动器已弹出(Drive ejected)` and message `NotAFolder`:
<img width="662" alt="image" src="https://user-images.githubusercontent.com/61649477/217322948-224f4f86-4aa4-403b-8bd0-fffef7d77383.png">

After I clicked "OK", I got a blank page.
<img width="658" alt="image" src="https://user-images.githubusercontent.com/61649477/217324619-e8643f1a-5cbc-4557-9d96-1c59fe7ac3b3.png">  

I inspected the log file, and I thought the issue might be related to this exception:
```
2023-02-08 01:37:25.5644|WARN|NormalizePath|Home\
	System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at Files.App.Helpers.PathNormalization.NormalizePath(String path)
```

### Steps To Reproduce

0. Go to the Home page (which is important, since this bug only occurs when I am on the home page)
1. Set Files' language to English (US)
2. Change the language to Chinese Simplified in settings
3. Click "restart for changes to take effect" and observe the bug

### Steps to fix

1. The error dialog should not happen after the language change. 
2. After restarting the app, I should get the content of the home page instead of a blank page.

### Files Version

Version: 2.4.31.0

### Windows Version

Windows 11 22H2 22623.1250 (Beta)

### Log file

[debug.log](https://github.com/files-community/Files/files/10678045/debug.log)

**Comment by hishitetsu** [comment]
This appears to be happening because the path to the home screen is localized.
I think the path to the home screen should not be localized, but be always "Home".

**Comment by yaira2** [comment]
That works, we might get some complaints about that but at least it'll be more predictable.
