### ISSUE TITLE
Files stop working

### ISSUE THREAD

**Issue by shenbourne** [files-community/Files#11205]
### Description

congratulations! The speed of collapse broke the record!
![image](https://user-images.githubusercontent.com/121733766/217347349-e29ec7b0-74ee-43bc-b80d-c611d2715eb6.png)
Less than 10 seconds!
Amazing! Files has never been so fast!

### Steps To Reproduce

1. Open "Files"

3. Extract the “.rar” file with 7-zip
> ![image](https://user-images.githubusercontent.com/121733766/217348477-3c22dfff-df50-4adf-b105-5ecc08acc530.png)
4. cut the “.exe” file
> ![image](https://user-images.githubusercontent.com/121733766/217348811-c4152139-ce3e-436a-a8cc-f7344d2a049b.png)
5. and "boom"

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

Version: 2.4.11.0 OS Version: 10.0.19045.2364

### Windows Version

Windows 10 22H2 19045.2364

### Log file

[debug.log](https://github.com/files-community/Files/files/10678817/debug.log)

**Comment by Josh-65** [comment]
Your on an outdated version of Files please update from https://files.community/download
