### ISSUE TITLE
Bug: The dialog is not shown when undoing to delete items if the setting to show the dialog is off

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#11200]
### Description

Unfortunately, #11185 did not show a confirmation dialog on undo when the setting to show the dialog is off because DeleteItemAsync method always confirms the setting internally.

### Steps To Reproduce

As the title indicates.

### Steps to fix

Ensure that the dialog is shown regardless of the setting.

### Files Version

Files - Dev (main branch)

### Windows Version

Windows 11 22H2 22621.1105

### Log file

n/a

**Comment by Josh-65** [comment]
I feel like it should show dialog if it going to be permanently deleted anywhere except the recycle bin (User already knowns it permanent) anyway.

**Comment by hishitetsu** [comment]
Maybe so, but it has already been issued as #11126 .
This is for an additional fix for #11185 .
