### ISSUE TITLE
Feature: More flexible AppThemeFontFamily

### ISSUE THREAD

**Issue by ghost** [files-community/Files#11202]

**Comment by yaira2** [comment]
I think you might be able to do this already, try using `/` to separate the font names. If it doesn't work, it's a limitation with XAML and not something we have plans to address from our side.

**Comment by yaira2** [comment]
According to this https://www.mrlacey.com/2021/01/fallback-fonts-in-xaml.html it should work with a regular comma. I assume you tried this already so reopening this issue.
