### ISSUE TITLE
Bug: Moving item from desktop to admin access folder move item to recycle bin

### ISSUE THREAD

**Issue by anditv21** [files-community/Files#11211]
### Description

Sometimes, when I attempt to move a file from the desktop to a folder by dragging it, an error message appears saying "Failed to move 1 item from..." and the file ends up disappearing.

I have noticed this error only with some folders e.g "C:\Program Files\".

### Steps To Reproduce

1. Drag item from desktop to a folder like C:\Program Files
2. See item move to recycle bin rather then staying on desktop

### Steps to fix

- Do not move file from desktop to recycle bin if move failed

### Files Version

Version: 2.4.31.0 OS Version: 10.0.19045.2364

### Windows Version

Windows 10 Pro 22H2 19045.2364

### Log file

[debug.log](https://github.com/files-community/Files/files/10686190/debug.log)

**Comment by anditv21** [comment]
I think the error is occurring due to the need for additional permissions for certain folders.

**Comment by Josh-65** [comment]
Some directories require admin and support for that is tracked at #10422

**Comment by anditv21** [comment]
sorry my fault
no the files have ended up in the recycle bin

Ok thanks for the information

**Comment by Josh-65** [comment]
There's still the issue of them going to the recycle bin it shouldn't do that and just stay on the desktop.

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval

**Comment by yaira2** [comment]
@anditv21 did you use ctrl + z after the error popped up?

**Comment by anditv21** [comment]
Yes the file can be returned to the desktop again by using Ctrl + Z

**Comment by yaira2** [comment]
Should be fixed in the next release.
