### ISSUE TITLE
Bug: [Win.11 Registry Editor NoDrives] causes app to crash

### ISSUE THREAD

**Issue by Diaxium** [files-community/Files#11215]
### Description

Using [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer] and creating the D-WARD(32-Bit) Key to hide any drive on the file explorer will cause the Files App to crash. In my case I'm hiding two drives both (C, and Z) which is a Decimal Value for the key of 33554436. This hides the drives perfectly fine from the regular file explorer. However in this case of the File app causes it to crash. 

### Steps To Reproduce

1. Go to you're search bar or explorer in windows and search for regedit or Registry Editor, and open the app.
2. Go to HKEY_LOCAL_MACHINE -> SOFTWARE -> Microsoft -> Windows -> CurrentVersion -> Policies -> Explorer
3. Left click and create a New -> DWARD (32-bit) Value
4. Name The newly created DWARD to NoDrives
5. Set the value data based on these drive Decimal [Values](https://ss64.com/nt/syntax-nodrives.html)
6. Set the Base to Decimal and input that value into the Value Data.
7. Restart the explorer application via task manager or log off and log back into your desktop, or additionally you can just restart the computer completely. 
8. Now you drives will be hidden from the file explorer, however the files app will now crash.

### Steps to fix

Remove/rename the NoDrives Key in registry editor to fix the crashing. 

### Files Version

v2.4.31

### Windows Version

Windows 11 Pro 22H2 22621.1194

### Log file

[debug.log](https://github.com/files-community/Files/files/10689356/debug.log)

**Comment by yaira2** [comment]
@Diaxium thank you for your feedback, we were able to reproduce this issue as well.

**Comment by yaira2** [comment]
@Diaxium can you see if this is an issue in v3.0.8? If it is, can you upload the updated log file?
