### ISSUE TITLE
Classic Installer problem

### ISSUE THREAD

**Issue by t0ma5** [files-community/Files#11224]
### Description

I have WIN10 x64 without Microsoft Store so I tried using the Classic Installer offered on https://files.community/appinstallers/Files.Stable.exe
Installation process begins but it never ends.

### Steps To Reproduce

Run Files.Stable.exe
Wait....
Installation never completes
No error given

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

Latest

### Windows Version

Win 10 Enterprise LTSC 1809

### Log file

No Log

**Comment by yaira2** [comment]
The minimum supported version is 1903.

**Comment by t0ma5** [comment]
> The minimum supported version is 1903.

same issue here with newer Win version https://github.com/files-community/Files/issues/11183

**Comment by yaira2** [comment]
That might be a different issue, could be a modified version of Windows. We're still waiting to here back from the user.
