### ISSUE TITLE
Issues with WSL showing?

### ISSUE THREAD

**Issue by meemore** [files-community/Files#11226]
### Description

![Screenshot_8](https://user-images.githubusercontent.com/124497263/217960417-e4289910-b6be-4c8b-a156-a7524776dfb7.jpg)
![Screenshot_10](https://user-images.githubusercontent.com/124497263/217960420-3c952d8d-97ec-4dc6-974f-f6791d0a1fd4.jpg)

### Steps To Reproduce

it doesn't show 

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

w11

### Windows Version

w11

### Log file

.

**Comment by Josh-65** [comment]
Thanks for the feedback. Please make a new issue following the issue templates. It tells you how to fill it out if you don't know what to put for a section.

**Comment by yaira2** [comment]
I think we have all the info we need here

**Comment by yaira2** [comment]
I've seen this issue on devices the upgraded from Windows 10.

**Comment by meemore** [comment]
> I've seen this issue on devices that upgraded from Windows 10.
No sir, this is a brand new ssd and windows 11 installed there is no win10 ever installed on this,  I have uninstalled and reinstalled the sub system for Linux.

**Comment by Josh-65** [comment]
Do you have a distro installed and setup. Also what version of WSL are you using?

**Comment by yaira2** [comment]
@meemore do you have any distros installed?
