### ISSUE TITLE
Warns the user of showing system files

### ISSUE THREAD

**Issue by foursplaysroblox** [files-community/Files#11234]
### What feature or improvement do you think would benefit Files?

Hello I would like files to have a feature to warn the user when they click show protected system files

### Requirements

- A warning when the user clicks show system protected system files
- Confirmation buttons labeled "Yes display system protected files" and "No do not display system protected files"

### Files Version

Files Preview 2.4.33.0 

### Windows Version

Windows 11 22H2 Insider Dev 10.0.25295.1000

### Comments

![image](https://user-images.githubusercontent.com/82078139/218055632-7b0adbd3-b212-4972-98fb-2750d43b1e7f.png)

**Comment by yaira2** [comment]
Why? I think "Show protected system files" is warning enough.

**Comment by yaira2** [comment]
@foursplaysroblox
