### ISSUE TITLE
Feature: Make context menu entry "Show more options" always visible

### ISSUE THREAD

**Issue by MalteTasler** [files-community/Files#11236]
### What feature or improvement do you think would benefit Files?

The asynchronous loading of the shell extensions when opening the context menu still leads to a rather ugly "jumping" or "expansion" of the context menu UI as the entry "Show more options" gets added with some delay.

Now, the latest improvements made in #11110 make the situation already better than previously. 
May it be possible to just always (instantly) display the "show more options" entry, so that the context menu can completely get rid of the jumping / expansion? My idea is that the entry "Show more options" could be grayed out (in UI design terms "disabled") initially when opening the context menu and just gets enabled once the shell extensions have been loaded.

Related: #11112 

### Requirements

- This proposal will accomplish making the entry "Show more options" in the context menu always visible
- This proposal will accomplish disabling the entry initially before the shell extensions have finished loading

### Files Version

2.4.33

### Windows Version

Windows 11 22H2 Build 22621.1194

**Comment by hecksmosis** [comment]
I'll do this
