### ISSUE TITLE
Bug: Taskbar preview icon is wrong

### ISSUE THREAD

**Issue by UrbanBreznik** [files-community/Files#11235]
### What feature or improvement do you think would benefit Files?

Alt+tab or Win+tab the icon is not the on of Files, but a ugly generic blue one from WIndows.

### Requirements

- Change the generic icon for the Files one
- This proposal will accomplish better visibility when switching apps

### Files Version

Version: 2.4.31.0 

### Windows Version

Edition	Windows 11 Home Version	22H2 Installed on	‎20/‎09/‎2022 OS build	22621.1194 Experience	Windows Feature Experience Pack 1000.22638.1000.0

### Comments

![Files icon bug](https://user-images.githubusercontent.com/29950176/218118224-c72de652-415c-46ba-abf1-015d231fa254.jpg)

**Comment by yaira2** [comment]
@Ferrario-Filippo the PR doesn't seem to have fixed this, I can still reproduce the issue.

**Comment by ferrariofilippo** [comment]
> @Ferrario-Filippo the PR doesn't seem to have fixed this, I can still reproduce the issue.

Actually, that PR was opened by @hecksmosis in #11188

**Comment by yaira2** [comment]
Whoops! My apologies.

**Comment by ferrariofilippo** [comment]
No problem ;)

**Comment by hecksmosis** [comment]
> > @Ferrario-Filippo the PR doesn't seem to have fixed this, I can still reproduce the issue.
> 
> Actually, that PR was opened by @hecksmosis in #11188

Oops! It's difficult to test if the icons really work because it requires releasing to stable/preview

**Comment by yaira2** [comment]
The CI pipeline renames the folders so it's always in the release folder, even for preview.

**Comment by yaira2** [comment]
I can confirm it's working fine in the stable version v2.3.33 though.

**Comment by hecksmosis** [comment]
Do you mean 2.4.33?

**Comment by hecksmosis** [comment]
> The CI pipeline renames the folders so it's always in the release folder, even for preview.

Oh, didn't know that, looks like it was in the preview folder in WindowsApps

**Comment by yaira2** [comment]
Turns out I was wrong, the pipeline doesn't rename the folder. Stable and dev have the correct icons but preview doesn't.
