### ISSUE TITLE
Option to disable File Explorer Sync Favorites and show a pop up to run files as administrator when modifying system files

### ISSUE THREAD

**Issue by foursplaysroblox** [files-community/Files#11233]
### What feature or improvement do you think would benefit Files?

Hello, I would like an option to disable File Explorer Sync Favorites because the old one looked more cleaner.

### Requirements

- Adds an option to disable File Explorer Sync in Preferences setting

### Files Version

Files Preview 2.4.33.0 

### Windows Version

Windows 11 22H2 Insider Dev 10.0.25295.1000

### Comments

![image](https://user-images.githubusercontent.com/82078139/218052299-ace71b91-270a-441b-8287-593271561602.png)

**Comment by Josh-65** [comment]
Admin operations are being tracked in #10422

**Comment by foursplaysroblox** [comment]
also add a warning to the user when clicking show system files that these files are required to run windows. deleting or editing them can make your computer unusable.

**Comment by Josh-65** [comment]
Please make a separate feature request for different feedback

**Comment by yaira2** [comment]
Are you referring to the recent folders that are shown?

**Comment by foursplaysroblox** [comment]
yes sir

**Comment by yaira2** [comment]
Can you share more about your use case and how this will help?

**Comment by yaira2** [comment]
@foursplaysroblox

**Comment by foursplaysroblox** [comment]
ballz

**Comment by foursplaysroblox** [comment]
Is it there in files because im gonna downgrade files if no

**Comment by yaira2** [comment]
We're waiting to hear back from you about your use case.
