### ISSUE TITLE
Favorites section does not work for me

### ISSUE THREAD

**Issue by TheD0me** [files-community/Files#11242]
### Description

Hi I hope I am in the right place.

The problem is that I can not add folders (in my case the Downloads folder) to the FAVORITES section.

When you press "add to favorites" unfortunately nothing happens ...

I deinstall my Files App( V. 2.4.31.0) and install the new Version from your Website (V. 2.4.33.0), but same Problem

What am I doing wrong?

### Steps To Reproduce

???

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

2.4.33.0

### Windows Version

Windows 11 22H2 22621.1194 

### Log file

[debug.log](https://github.com/files-community/Files/files/10713015/debug.log)

**Comment by yaira2** [comment]
Does it work to add any other folders? What happens if you add it through File Explorer?

**Comment by TheD0me** [comment]
Normal Folder Work but the Libraries not. Sometimes they are there when I restart my PC (if I pressed "add to Favorites" before).

**Comment by ddPn08** [comment]
I have a similar problem.
I can't add all folders to my favorites, not just library folders. I tried drag and drop and it didn't work.
I tried doing it while looking at the debug log, but nothing was updated.

tested versions
win: 10.0.22622.440
files: 2.4.40.0, 2.4.33.0

![image](https://user-images.githubusercontent.com/71378929/219819632-7f480366-c0cf-4aa2-ae24-b611e674c0e3.png)

**Comment by ddPn08** [comment]
I'm not sure, but it was fixed when I tried to unpin the C drive from my favorites.
Also, at that time, the C drive was not displayed in the favorite column in the first place.

**Comment by yaira2** [comment]
I think it'll work if you run as admin, we don't have permission to edit the list if it contains the c drive.

**Comment by TheD0me** [comment]
Now i cant add any Fovorites, I reinstall Files, I add Favorites in the normal expolerer, i start Files as Admin. But not of this works.

Can i add the favorits per .json file (like the tags and bundles)?

**Comment by yaira2** [comment]
Favorites are supposed to sync over from File Explorer

**Comment by yaira2** [comment]
Which locations are currently pinned?

**Comment by TheD0me** [comment]
![image](https://user-images.githubusercontent.com/125121017/220976497-fc217258-04da-412d-898a-1e49c2ad5842.png)

Thats the Windows Expolere Pinned Files. In Files is nothing pinned

**Comment by TheD0me** [comment]
I have already tried to unpin and repin it which unfortunately did not work either

**Comment by yaira2** [comment]
@hecksmosis any ideas?
