### ISSUE TITLE
Can't move file (mkv) from local to shared on network

### ISSUE THREAD

**Issue by macnoobster** [files-community/Files#11246]
### Description

This happens with movie files but some others too.
-I, for example, download a movie file on a local disk.
-Once downloaded, I move it to my movie folder on my mapped network drive (Netgear NAS)
-I receive an error in the task icon, just saying that there was an issue moving the file. "Failed to move file"

### Steps To Reproduce

1-download file 
2-rename file (not mandatory)
3 Cut - paste video file from local to network location
4 "Files" returns error Failed to move file

### Steps to fix

Using windows explorer  works but it alerts me on some files, and asks if it should copy the files without its properties. but after accepting, it copies or moves the file correctly.

### Files Version

Version: 2.4.31.0 OS Version: 10.0.22621.1194

### Windows Version

win 11 22H2 build 22621.1194

### Log file

[debug.log](https://github.com/files-community/Files/files/10713536/debug.log)

**Comment by Josh-65** [comment]
Merging with #9423
