### ISSUE TITLE
Feature: Keep timestamps when extracting an archive

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#11259]
### What feature or improvement do you think would benefit Files?

In Files, timestamps of the file from an extracted archive are set to the current date and time.
But in File Explorer and many other archivers, timestamps are set to the original date and time stored in the archive file.
I think Files should keep timestamps too.

### Requirements

Timestamps are set to the original date and time stored in the archive file, like File Explorer and many other archivers.

### Files Version

Version: 2.4.31.0

### Windows Version

Windows 11 22H2 22621.1105

**Comment by yaira2** [comment]
@hishitetsu thank you for your feedback, we're currently working on implementing this.
