### ISSUE TITLE
Can you install a build for all Useres on a local windows 1o machine?

### ISSUE THREAD

**Issue by Greenman326** [files-community/Files#11250]
I build the sln on my local admin account. The Problem is I cant access it from my other accounts because the files are stored in %appdata%. When trying to build on the other accounts i get an error that another user already installed the aplication. Can i build for all Useres or is the install limited to one Windows User?

**Comment by Josh-65** [comment]
The install is limited to per user and you would have to install separately. You can use the sideload option at https://files.community/download to install for other user rather then VS
