### ISSUE TITLE
Files does not go on top after win+E or by clicking My PC

### ISSUE THREAD

**Issue by bob69420x** [files-community/Files#11251]
### Description

Title 

Video: 
https://www.veed.io/view/46327932-c53f-42b4-84ca-5160826fd86d?panel=share

### Steps To Reproduce

1. Open files explorer
2. Open  `My PC`  or click win+E
3. Window will not go on top like it's supposed to

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

Version: 2.4.31.0 OS Version: 10.0.19045.2486

### Windows Version

Windows 10 22H2 19045.2486

### Log file

[debug.log](https://github.com/files-community/Files/files/10714006/debug.log)

**Comment by Josh-65** [comment]
Merging with #10844

**Comment by yaira2** [comment]
This issue will be resolved with #13588.
