### ISSUE TITLE
Code Quality: Correct namespaces

### ISSUE THREAD

**Issue by 0x5bfa** [files-community/Files#11257]
### Description

I'd like to work on #4180 by reorganizing namespaces and I'd like you guys to feedback one by one whether it is able to be implemented.

#### 0. Correct those namespaces in Files.App

```
Change models:

'Views/SettingsPages/*.xaml(.cs)'        ->   'Views/Settings/*Page.xaml(.cs)'
'Views/Pages/Properties*.xaml(.cs)'      ->   'Views/Properties/*Page.xaml(.cs)'
'ViewModels/Properties/*Properties.cs'   ->   'ViewModels/Properties/*ViewModel.cs'
'ViewModels/SettingsViewModels/*.cs'     ->   'ViewModels/Settings/*.cs'
'ViewModels/Dialogs/*DialogViewModel.cs' ->   'ViewModels/Dialogs/*ViewModel.cs'

Preview samples:

'Views/SettingsPages/Appearance.xaml'   ->   'Views/Settings/AppearancePage.xaml'
'Views/Pages/PropertiesSecurity.xaml'   ->   'Views/Properties/SecurityPage.xaml'
'ViewModels/SettingsViewModels/AppearanceViewModel.cs' -> 'ViewModels/Settings/AppearanceViewModel.cs'
'ViewModels/Properties/SecurityProperties.cs'          -> 'ViewModels/Properties/SecurityViewModel.cs'
'ViewModels/Dialogs/CreateShortcutDialogViewModel.cs'  -> 'ViewModels/Dialogs/CreateShortcutViewModel.cs'
```

#### 1. Merge 'Files.Backend' and 'Files.Shared' into 'Files.Core' (, which is new)

- `Files.Backend` -> `Files.Core`
- `Files.Shared` -> `Files.Core` (merge into Core)

#### 5. Move 'Files.App.CommandLine'

- `Files.App.CommandLine` -> `Files.Core.CommandLine`

#### 6. Move UI-unrelated 'Files.App.Helpers' and 'Files.App.Extensions'

- `Files.App.Helpers` -> `Files.Core.Helpers`
- `Files.App.Extensions` -> `Files.Core.Extensions`

#### 7. Merge 'Files.App.AppModels' into 'DataModels' (, which is existing already)

- `Files.App.AppModels` -> `Files.App.DataModels`

#### 8. Merge 'Files.App.ValueConverters' into 'Files.App.Converters' (, which is existing already)

- `Files.App.ValueConverters` -> `Files.App.Converters`

### Concerned code

Not codes but namespaces.

### Gains

- A better accessible/predictable namespaces.

### Requirements

- Rename those with VS 2022 search/replace functionality.

**Comment by onein528** [comment]
FYI @yaira2

**Comment by yaira2** [comment]
This looks good, do you want to implement?

**Comment by onein528** [comment]
Yes. I'm gonna do this weekend.

**Comment by onein528** [comment]
@yaira2 How about this?

`Files.Backend` -> `Files.Core`
`Files.Shared` -> `Files.Core` (merge into Core)

**Comment by onein528** [comment]
@yaira2

**Comment by yaira2** [comment]
> 4. Rename 'Files.App (Package)' with 'Files.Package'

This will break our build process so not this one.

@d2dyno1 can you answer the rest?

**Comment by d2dyno1** [comment]
I wanted to separate the backed from Shared project. This way we can share common code like utilities and extensions between multiple projects

**Comment by onein528** [comment]
Why did you though they should be separated?

I think there's no problem(reason) and no code decrease maintainability even if they are in the same namespace.
