### ISSUE TITLE
Uninstall files and reverting the registry.

### ISSUE THREAD

**Issue by GreenFishy** [files-community/Files#11254]
**Description**
Files (Preview version) is set as the default explorer, Settings menu is missing. Would like to revert back to the original File Explorer again. Would also like to retry Files (Stable version). 
Unclear on how to revert registry change.
![CorruptedFilesPreview](https://user-images.githubusercontent.com/106456764/218279971-2e238c1d-8f37-4f27-8072-1b8673259f3d.png)

**Steps To Reproduce**
1. Install Files Preview
(Honestly don't know any next step in reproducing this issue).

**Windows**
Windows 11 Home ver. 22H2

**Log File**
n/a

**Side Notes**
If possible could share a video or info on how to revert the registry change, I am use to using linux and trying to understand Windows. So apologizes if I had missed out on any additional info.

**Comment by Josh-65** [comment]
Install Files and turn off the set as default toggle. In future use the issue templates and all the information request and don't make your own.

**Comment by GreenFishy** [comment]
Sorry but this doesn't fix my issue. And I didn't intend to make my own issue template, And there is no linking to the issues template that I can find on the code page. If I need to redo this issue request can you link the template so I can fill out the issue accordingly.

**Comment by Josh-65** [comment]
How did you get to the new issue page?

**Comment by Josh-65** [comment]
Open this https://raw.githubusercontent.com/files-community/Files/main/src/Files.App/Assets/FilesOpenDialog/UnsetFilesAsDefault.reg > Right click > save as > set "Save as type" to all files > Remove .txt from end of file name > Run the file

**Comment by GreenFishy** [comment]
I Checked the websites documentation and found no issues template, and I scoured the GitHub for a issues template and found nothing.

I will reply with the result of the link you just gave me thank you

**Comment by Josh-65** [comment]
Clicking on those links should give the issue templates quite clearly
![image](https://user-images.githubusercontent.com/26977075/218281611-ad142f6a-fc44-493d-8317-c8f60a69494f.png)

**Comment by GreenFishy** [comment]
That menu didnt appear the first time, so I do apologize. Would you have me redo the bug report.
Also the registry file did not fix my issue.

**Comment by Josh-65** [comment]
No need, but can you be more clear on what you issue is or what happens

**Comment by GreenFishy** [comment]
Well I ran the file you provided and it asked to change the registry and I did a reboot. The original file explorer doesn't appear and only the supposed corrupt files preview version shows.

**Comment by Josh-65** [comment]
If it opens the window in the screenshot of the original message that is File explorer.

**Comment by GreenFishy** [comment]
So your saying that its is the File explorer and Not files. I don't use windows much and I am not gonna lie that it looks somewhat similar in appearance. If that's the case I very much apologize! Due to my stupidity, I had thought it was the same, because of the appearance.

**Comment by GreenFishy** [comment]
I really am sorry for the inconvenience!

**Comment by Josh-65** [comment]
It's alright
