### ISSUE TITLE
various annoying problems.

### ISSUE THREAD

**Issue by GitHubkaede** [files-community/Files#11258]
### What feature or improvement do you think would benefit Files?

1. When I want to drag the upper edge of the window, it does not have the effect of elongating the window, and the window size must be changed through the upper right or other edges of the window. I don't know what BUG triggered my operating system: WINDOWS 22H2 22621.1105 (https://i.imgur.com/WD68AOn.mp4)

2. The size of the window will limit any menu length. For example: The length of the "Send To" option had to make me resize the window to find the desired program more efficiently. （https://i.imgur.com/zPXaJm4.mp4）

3. Will it allow me to choose the option not to force new folders or names of files to be added.（https://i.imgur.com/yGDOcMw.png）

4. Is it my problem that the menu is slow to respond? The right-click menu appears for 1~2 seconds before loading the submenu.greatly affect efficiency.

5. The meaning of the function is unclear. When I am in the file type group, I click the group name to enter a strange operation. When I click again to return to the previous page, the focus is also messed up. I have to pull the mouse back to the original focus. I really don't know how to use this feature.
（https://i.imgur.com/3dD89iC.mp4）

6. The renaming function of clicking the file twice with the mouse slowly is gone, I will also use F2 to rename, is it because everyone has not used the function of clicking the file twice?（https://i.imgur.com/8tJwF1d.mp4）

### Requirements

After I installed it, there is no shortcut icon on the desktop. Is it my problem? I need a desktop shortcut to "Files".

### Files Version

2.4.33.0

### Windows Version

22H2 22621.1105

### Comments

While I was waiting to see that 2.4.31.0 had the "Send To" option, the functionality I was expecting was finally there, but after installing it felt that many of the options & habits were not as intuitive as the original explorer.

But the UI is really nice.

I'm not a high-end user, so I don't know what options are Issues&Pull requests. I'm just expressing my opinion.

It's a pity that I can only use translation software to give feedback, Some questions cannot be expressed clearly.

**Comment by Josh-65** [comment]
Thanks for the feedback please make separate issue for different feedback in future

1. Merging with #10813
2. This is a WinUI bug 
3. The popup is for you to enter a name when making a file/folder
4. Merging with #11112
5. The page is to more quickly go to another header by not showing the files/folders in between. It has no use with one group or few items in them.
6. Double click to rename is still a thing. What do you mean it slowly gone?

**Comment by Josh-65** [comment]
To make a desktop shortcut you can find files in the all apps list of the start menu and drag it to the desktop

**Comment by GitHubkaede** [comment]
> 3. The popup is for you to enter a name when making a file/folder

∎ When adding a new file, many times I don’t immediately think of the file name. Of course, I admit that this is already considered inefficient. Maybe I just don’t want it to hinder me from clicking other places smoothly.

> 5. The page is to more quickly go to another header by not showing the files/folders in between. It has no use with one group or few items in them.

∎ Is it possible to turn off or turn on this function, so that one group type can be selected at one time like explorer.

> 6. Double click to rename is still a thing. What do you mean it slowly gone?

∎ Sorry, because the translation expression is wrong, just click twice to rename.
Thank you for your reply.

**Comment by Josh-65** [comment]
> Is it possible to turn off or turn on this function, so that one group type can be selected at one time like explorer.
It not possible but you can make a new feature request for it.
