### ISSUE TITLE
Feature: Remember previously selected option in conflicts dialog

### ISSUE THREAD

**Issue by SuperPyroManiac** [files-community/Files#11266]
### What feature or improvement do you think would benefit Files?

By default, files uses "Generate new name" but it would greatly improve my workflow if I could have it set to "replace" by default.

### Requirements

Remember the previously selected option in the dropdown and auto select the next time the dialog is opened.

### Files Version

2.4.33.0

### Windows Version

Windows 11 Pro - 22H2 22621.1105

**Comment by yaira2** [comment]
@SuperPyroManiac this will be included in the next release.
