### ISSUE TITLE
I need the glass theme 

### ISSUE THREAD

**Issue by anilsonfernandes** [files-community/Files#11269]
### What feature or improvement do you think would benefit Files?

why did you remove the glass theme? I want my refund.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.4.33.0

### Windows Version

10.0.19045.2546

### Comments

--

**Comment by yaira2** [comment]
https://files.community/docs/configuring/custom-themes

**Comment by anilsonfernandes** [comment]
> You can enable the "glass" theme settings by changing the sidebar, address bar and file area background colors to #00000001 https://files.community/docs/configuring/custom-themes. This currently requires Windows 11.

Sorry, I don't use windows 11, I want my refund, please!

**Comment by yaira2** [comment]
Sales are handled by the Store, you can contact Microsoft.

**Comment by yaira2** [comment]
For what it's worth, we're working to try ad bring this to Windows 10 but we don't have a timeline.

**Comment by anilsonfernandes** [comment]
I did the update, it still doesn't work

**Comment by anilsonfernandes** [comment]
I edited it using vsc, as you asked, but it doesn't activate the glass theme

**Comment by yaira2** [comment]
Did you close the app before making the edits?

**Comment by anilsonfernandes** [comment]
yes, but the same not working

**Comment by anilsonfernandes** [comment]
and now, will I be at a loss?

**Comment by Josh-65** [comment]
It doesn't work on Windows 10 yet but a way to support it is been looked at.

**Comment by anilsonfernandes** [comment]
![image](https://user-images.githubusercontent.com/124417568/219053353-af8ee5f4-bfc4-45a2-88e9-b534d3c7e2a1.png)

**Comment by anilsonfernandes** [comment]
I'm on windows 11

**Comment by Josh-65** [comment]
Do you have transparency enabled. It also depends on your background, dark or ones with little details wont show as well.

**Comment by anilsonfernandes** [comment]
![image](https://user-images.githubusercontent.com/124417568/219054523-33fd439f-5192-4af4-884e-af1abcb94969.png)

**Comment by Josh-65** [comment]
You have a black background and transparency off. It wont show any effect either way.

**Comment by anilsonfernandes** [comment]
![image](https://user-images.githubusercontent.com/124417568/219055000-44937701-14bf-4b57-90cb-f79c4321b760.png)

**Comment by anilsonfernandes** [comment]
![image](https://user-images.githubusercontent.com/124417568/219055175-1a34186d-8dcf-4d7a-b6f7-a63bba8d7a44.png)

**Comment by anilsonfernandes** [comment]
![image](https://user-images.githubusercontent.com/124417568/219055601-05da471e-bfac-4359-a2eb-d8483d7319a4.png)

**Comment by anilsonfernandes** [comment]
don't working

**Comment by Josh-65** [comment]
I presume you using a 3rd party tool to make the background. The glass theme uses mica and for that it uses the Windows background. Your settings shows that as only the black colour. You also have transparent effects turned off there.

**Comment by anilsonfernandes** [comment]
I use wallpaper engine does it interfere?

**Comment by Josh-65** [comment]
Wall paper engine doesn't actually set a wall paper to Windows and it uses it own rending system. If you have the image used with wallpaper engine you can set it on Windows by going to Windows settings > Personalisation > Background > Personalise your background set to Picture > Browser photo > Select the image.

The if turn on transparency effects it will show.

**Comment by anilsonfernandes** [comment]
![image](https://user-images.githubusercontent.com/124417568/219059118-75da6da4-14c0-4c2c-9644-c003b9e375d8.png)

**Comment by anilsonfernandes** [comment]
working on, i think!

**Comment by anilsonfernandes** [comment]
I imagined more transparent
