### ISSUE TITLE
Porting to Linux: what are some Windows-only features used in this tool?

### ISSUE THREAD

**Issue by timleg002** [files-community/Files#11260]
Hello!

I'd certainly be interested in porting, or helping to port, such a beautifully designed app to Linux (or other platforms). I'm aware that C# apps can run on Windows, yet I don't have that much of C# experience, to know, if this is actually doable. 

But this is just a file manager: so if any contributor could answer me, what features would be hard to port to Linux, or some stuff to be considered a roadblock in porting to Linux? Thank you!

(I'm aware that there are GitHub issues regarding this, I just don't want to open any new ones)

**Comment by Josh-65** [comment]
Files is not going to be ported to Linux as many part like the UI and functionally frameworks used are not available on Linux. There also very limited developers for Files currently adding a completely different platform would be quite impossible. If you were to work on it you would probably be the only one.

**Comment by yaira2** [comment]
Thank you for your feedback, we're currently focused on Windows and while we don't think we're in position to port to other platforms right now, we've been doing some of the groundwork on making this possible.

Some of the roadblocks will be our integrations with Windows specific features such as libraries, shell extensions and quick access. We're working on storage abstractions as well. Are you interested in helping with this?

**Comment by timleg002** [comment]
I'd certainly be interested in helping with this. Isn't this written in C#/XAML? Isn't it cross platform?

**Comment by yaira2** [comment]
There are ways to take it cross platform but you need to abstract the Windows specific code.

**Comment by alshdavid** [comment]
Sorry to comment on an old closed issue.

I'd love to see this ported to Linux. To date, IMO there is no file manager that even comes close to the ergonomics of Files on any Linux DE.

Given I will be switching to Linux when Windows 10 support is completely dropped, I'll be sad to say goodbye to Files.

Perhaps it can be run on top of Wine?

**Comment by softyoda** [comment]
Where do i pay for this ? Year of the linux desktop won't start if there are still no decent file explorer (the basics)

**Comment by Josh65-2201** [comment]
There is no version of Files on Linux

**Comment by softyoda** [comment]
Yea, this is why i commented. Do you want money?

**Comment by Josh65-2201** [comment]
It's not being worked on and not accepting donations to port it, see https://github.com/files-community/Files/issues/11260#issuecomment-1427037717

**Comment by softyoda** [comment]
"we've been doing some of the groundwork on making this possible" we're in the same boat, i just aren't really a dev and would vibeshitcode using opus4.8 that's why i would prefer paying real human to do the work. I hoped there were possibilities to leverage such bottleneck (money, attention) through the pure will of the crowd. With recent rise of fascism, i think a lot of people simply will leave the microsoft ecosystem (including platform such as github, while keeping git mindset)
