### ISSUE TITLE
Feature: Display transfer speed in status center

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#11265]
### What feature or improvement do you think would benefit Files?

Displaying transfer speed in the status center is a popular feature request from users, we should implement it!

### Requirements

- Use OpacityIcons for every item state icons
- Show speed graph in in-progress StatusCenter item
- Show writing speed in the graph control area
- Show time estimates
- Show current processing file name
- Show processed bytes
- Add retry button to StatusCenter item reprepresents an operation that can be retried
- Update title and subtitle strings

### Files Version

v2.4.33

### Windows Version

Windows 11

**Comment by hez2010** [comment]
When I was implementing the fundamental for rich process, I once considered the support for real-time speed calculation. But it seems to be expensive because we need to save the speed checkpoints frequently, so I ended up with only saving a StartTime for calculating the average speed:

https://github.com/files-community/Files/pull/10814/files#diff-05282d70c531e5d010647b1251e70297456260db0d94a5178c7ffd0ff52b26aeR32

**Comment by yaira2** [comment]
> I once considered the support for real-time speed graph calculation

We definitely want to do this to compete with File Explorer and other file managers.

**Comment by fredphoesh** [comment]
Yes PLEASE! I am often copying large video files for my work, and I get anxious not knowing if anything is happening at all, and then not knowing if the process is done, can I pull out my SD card, or go make a cup of tea, how long will this take etc... very important to me.

**Comment by 0x5bfa** [comment]
I'll work on.

**Comment by 0x5bfa** [comment]
## Specs

I won't create any custom controls using ContentTemplate, but I will modify current UserControl. The item will be categorized into two different kinds; Expandable one and Static one. Expandable one will be implemented by using Expander and will be used for InProgress file system operation. Static one is for any other than it.

### Icons

_Soon_

### Title messages

_Soon_

### Description messages

_Soon_

### ProgressBar behavior

_Soon_

### Speed Graph

_Soon_

### Estimated time

_Soon_

**Comment by 0x5bfa** [comment]
Can you replace requirements with this?

### Requirements

**Phase 1 (In progress)**

- Refactor around StatusCenter classes.
- Rename related classes to include *StatusCenter*.
- Add icon to every item to make its state be more recognizable

**Phase 2 (Ready to build)**

- Use OpacityIcons for every item state icons
- Show speed graph in in-progress StatusCenter item
- Show writing speed in the graph control area
- Show time estimates
- Show current processing file name
- Show processed bytes
- Add retry button to StatusCenter item reprepresents an operation that can be retried
- Update title and subtitle strings

**Comment by 0x5bfa** [comment]
# Draft of strings for status center

## Preface
- Not to show full path for source and destination. Instead, show them on hovering as tooltip

## Kinds
- Copy
- Move
- Recycle
- Delete
- Compress
- Decompress

## Copy
### In progress
- **96% complete**
- *Copying 64 items from Source to Destination*
- Speed: 4.4 MB/s
### Done
- **100% completed**
- *Copied 64 items from Source to Destination*
### Error
- **Error - 96% complete**
- *Copying 64 items from Source to Destination*
### Pause
- **Paused(Pausing) - 96% complete**
- *Copying 64 items from Source to Destination*
- Speed: 4.4 MB/s
### Cancel
- **Canceled(Canceling) - 96% complete**
- *Copying 64 items from Source to Destination*

## Move
### In progress
- **96% complete**
- *Moving 64 items from Source to Destination*
- Speed: 4.4 MB/s
### Done
- **100% completed**
- *Moved 64 items from Source to Destination*
### Error
- **Error - 96% complete**
- *Moving 64 items from Source to Destination*
### Pause
- **Paused(Pausing) - 96% complete**
- *Moving 64 items from Source to Destination*
- Speed: 4.4 MB/s
### Cancel
- **Canceled(Canceling) - 96% complete**
- *Moving 64 items from Source to Destination*

## Recycle
### In progress
- **96% complete**
- *Recycling 64 items from Source*
- Speed: 4 items/s
### Done
- **100% completed**
- *Recycled 64 items from Source*
### Error
- **Error - 96% complete**
- *Recycling 64 items from Source*
### Pause
- **Paused - 96% complete**
- *Recycling 64 items from Source*
- Speed: 4 items/s
### Cancel
- **Canceling - 96% complete**
- *Recycling 64 items from Source*

## Delete
### In progress
- **96% complete**
- *Deleting 64 items from Source*
- Speed: 4 items/s
### Done
- **100% completed**
- *Deleted 64 items from Source*
### Error
- **Error - 96% complete**
- *Deleting 64 items from Source*
### Pause
- **Paused - 96% complete**
- *Deleting 64 items from Source*
- Speed: 4 items/s
### Cancel
- **Canceling - 96% complete**
- *Deleting 64 items from Source*

## Compress
### In progress
- **96% complete**
- *Compressing 64 items from Source*
- Speed: 4 items/s
### Done
- **100% completed**
- *Compressed 64 items from Source*
### Error
- **Error - 96% complete**
- *Compressing 64 items from Source*
### Pause
- **Paused - 96% complete**
- *Compressing 64 items from Source*
- Speed: 4 items/s
### Cancel
- **Canceling - 96% complete**
- *Compressing 64 items from Source*

## Decompress
### In progress
- **96% complete**
- *Decompressing 64 items to Destination*
- Speed: 4 items/s
### Done
- **100% completed**
- *Decompressed 64 items to Destination*
### Error
- **Error - 96% complete**
- *Decompressing 64 items to Destination*
### Pause
- **Paused - 96% complete**
- *Decompressing 64 items to Destination*
- Speed: 4 items/s
### Cancel
- **Canceling - 96% complete**
- *Decompressing 64 items to Destination*

**Comment by mdtauk** [comment]
This is an approach I would like to suggest...  I welcome input and comments on the best approach.  This is of course relevant to en_US and en_GB - other regions will need localisation considerations.

I would like to avoid repetition of similar strings, emphasise the action currently happening, and move the less important info into a tooltip.

------------
 
 ## Kinds
 * Copy - Copied, Copying
 * Move - Moved, Moving
 * Recycle - Recycled, Recycling
 * Delete - Deleted, Deleting / Permanently Delete, Permanently Deleting, Permanently Deleted
 * Archive Compress - Compressed, Compressing
 * Archive Extract (Decompress) - Extracted, Extracting
 
 ## Copy
 ### In progress
 * **Copying 64 items (96%)**
 * _62 / 64 items to "Destination folder name"_  `` 62 / 64 items from "Source Path" to "Destination Path" ``
 * Speed: **4.4 MB/s**
 
 ### Done
 * **Copy completed**
 * _Successfully copied 64 items to "Destination folder name"_    `` 64 items copied from "Source Path" to "Destination Path" ``
 
 ### Error
 * **Copy unsuccessful**
 * _Error message why copy did not complete_  ``2 items failed to copy to "Destination Path" ``
 
 ### Pause
 * **Paused copying 64 items (96%)**
 * _62 / 64 items to "Destination folder name"_  `` 62 / 64 items from "Source Path" to "Destination Path" ``
 * Speed: **4.4 MB/s**
 
 ### Cancel
 * **Copy cancelled(Cancelling copy) (96%)**
 * _62 / 64 items copied to "Destination folder name"_
 
 ## Move
 ### In progress
 * **Moving 64 items (96%)**
 * _62 / 64 items to "Destination folder name"_  `` 62 / 64 items from "Source Path" to "Destination Path" ``
 * Speed: **4.4 MB/s**
 
 ### Done
 * **Move completed**
 * _Successfully moved 64 items to "Destination folder name"_    `` 62 / 64 items from "Source Path" to "Destination Path" ``
 
 ### Error
 * **Move unsuccessful**
 * _Error message why move did not complete_  ``2 items failed to move to "Destination Path" ``
 
 ### Pause
 * **Paused moving 64 items (96%)**
 * _62 / 64 items to "Destination folder name"_  `` 62 / 64 items from "Source Path" to "Destination Path" ``
 * Speed: **4.4 MB/s**
 
 ### Cancel
 * **Move cancelled(Cancelling move) (96%)**
 * _62 / 64 items to "Destination folder name"_   `` 62 / 64 items from "Source Path" to "Destination Path" ``
 
 ## Recycle
 ### In progress
 * **Recycling 64 items (96%)**
 * _62 / 64 items from "Source folder name"_   `` 62 / 64 items from "Source Path" ``
 * Speed: **4 items/s**
 
 ### Done
 * **64 items sent to the Recycle Bin**
 
 ### Error
 * **Recycle incomplete**
 * _62 / 64 items recycled from "Source folder name"_   `` 2 items were not sent to the Recycle Bin ``
 
 ### Pause
 * **Recycle paused (96%)**
 * _62 / 64 items recycled from "Source folder name"_   `` 62 / 64 items recycled from "Source Path" ``
 * Speed: **4 items/s**
 
 ### Cancel
 * **Cancelling recycle (96%)**
 * _62 / 64 items sent to the Recycle Bin_
 
 ## Delete
 ### In progress
 * **Permanently deleting 64 items (96%)**
 * _62 / 64 items from "Source folder name"_   `` 62 / 64 items from "Source Path" ``
 * Speed: **4 items/s**
 
 ### Done
 * **64 items permanently deleted**
 
 ### Error
 * **Unable to delete items**
 * _Error message why delete was unsuccessful_    ``2 items could not be deleted from "Source Path" ``
 
 ### Pause
 * **Delete paused - (96%)**
 * _62 / 64 items deleted from "Source folder name"_   `` 62 / 64 items deleted from "Source Path" ``
 * Speed: **4 items/s**
 
 ### Cancel
 * **Cancelling delete (96%)**
 * _62 / 64 items deleted from "Source folder name"_   `` 62 / 64 items deleted from "Source Path" ``
 
 ## Compress
 ### In progress
 * **Creating "Archive.zip" (96%)**
 * _Compressing 64 items from "Source folder name"_  `` Compressing 64 items from "Source Path" ``
 * Speed: **4 items/s**
 
 ### Done
 * **"Archive.zip" created**
 * _Successfully compressed 64 items from "Source folder name"_    `` Successfully compressing 64 items from "Source Path" ``
 
 ### Error
 * **Failed to create "Archive.zip"**
 * _Error message why files could not be compressed to the archive file_
 
 ### Pause
 * **Paused creating "Archive.zip" - 96% complete**
 * _Compressing 64 items from "Source folder name"_  `` Compressing 64 items from "Source Path" ``
 * Speed: **4 items/s**
 
 ### Cancel
 * **Cancelled creating "Archive.zip"**
 
 ## Decompress
 ### In progress
 * **Extracting "Zipfile.7z" (96%)**
 * _Decompressing 64 items to "Destination folder name"_   ``Decompressing 64 items to "Destination Path" ``
 * Speed: **4 items/s**
 
 ### Done
 * **Extracted "Zipfile.7z"**
 * _Decompressed 64 items to "Destination folder name"_   ``Decompressed 64 items to "Destination Path" ``
 
 ### Error
 * **Unable to extract "Zipfile.7z"**
 * _Error message why archive could not be extracted_
 
 ### Pause
 * **Paused Extracting "Zipfile.7z" (96%)**
 * _Decompressing 64 items to Destination_   ``Decompressing 64 items to "Destination Path" ``
 * Speed: **4 items/s**
 
 ### Cancel
 * **Cancelled extracting "Zipfile.7z" **

-------

Below are notes I made previously in the discord regarding the wording for the ETA messages and calculations

- About 5 mins (5:02 - 4:58)
- Just under 5 mins (4:57 - 4:30)
- Just over 4 mins (4:29 - 4:03)
- About 4 mins (4:02 - 3:58)
- ...
- About a minute (1:02 - 0:58)
- In less than a minute (0:57 - 0:04)
- In a few seconds (0:03 - 0:00)

**Comment by mdtauk** [comment]
Here is a visual with some of the examples
![image](https://github.com/files-community/Files/assets/7389110/cf95ab2a-aa36-4494-98bd-7c5321740591)

**Comment by 0x5bfa** [comment]
The whole plan to redesign Status Center currently approved.

## Requirements
**Phase 1 (Impremented)**
- Refactor the code around StatusCenter
- Redesign the StatusCenter card item UI

**Phase 2 (In progress)**
- Add the speed graph
- Add the speed displaying
- Add current processing file name

**Phase 3 (Ready to Build)**
- Add estimated time of complete displaying
- Improve strings to suit with the design
