### ISSUE TITLE
Feature: Open Windows Terminal as admin using ctrl + shift + `

### ISSUE THREAD

**Issue by francisco-lafe** [files-community/Files#11278]
### What feature or improvement do you think would benefit Files?

On Windows 10, on MS File Explorer (MSFE) you can open a shell terminal by using the combo ALT->F->S->(A|R) A for Admin or R for Regular User.  
This is **extremely** handy as one can open a shell as admin on the path we want to work with with ease, especially for software installation etc.  

![image](https://user-images.githubusercontent.com/90066435/218550668-d1cad969-4e6d-4d55-a605-13f922790ba8.png)

On Windows 11, the brilliant minds of Microsoft removed any of the ALT keys from MSFE, because reasons.  

I've started using Files, I like the way it works, and having this feature would be great. 

### Requirements

- This proposal will require the addition of a hot-key or sequence of keys that would open a (power)shell terminal on the current location as administrator. 

### Files Version

2.4.33.0

### Windows Version

Win 10 - 10.0.19044.2486

**Comment by yaira2** [comment]
<kbd>ctrl</kbd> + <kbd>`</kbd> is for opening Powershell as a regular user, what about <kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>`</kbd> for administrator?

**Comment by francisco-lafe** [comment]
> ctrl + `` is for opening Powershell as a regular user. What about ctrl + shift + ` for administrator?

I have a small gripe with that key, it's not standard across latin keyboard configurations, the ` key changes from keyboard to keyboard layout (say US and ES). But it would be a great feature regardless. 

Thanks,

**Comment by ferrariofilippo** [comment]
In VSCode, using Italian layout you can open the terminal hitting `Ctrl + ò` which would be a `Ctrl + ;` using English layout

**Comment by francisco-lafe** [comment]
Right, which is CTRL+Ñ in spanish.  
One thing I noticed is that the feature of opening powershell, it opens powershell but **not** in the CWD.  

Like:
![image](https://user-images.githubusercontent.com/90066435/218581075-5f84e953-8bc6-4a60-9e6b-72dbde13af0f.png)

**Comment by hecksmosis** [comment]
> In VSCode, using Italian layout you can open the terminal hitting `Ctrl + ò` which would be a `Ctrl + ;` using English layout Also, I remember reading that someone was working on `HotKeys personalization`, I'll se if I can find the related PR / Issue

I think it was @cinqmilleans with the RichCommand implementation

**Comment by ferrariofilippo** [comment]
> One thing I noticed is that the feature of opening powershell, it opens powershell but **not** in the CWD.

Yes, I just found that out myself and I opened a PR to fix that and actually to support also (Ctrl + Shift + `)

**Comment by hecksmosis** [comment]
What's the shortcut to open powershell?

**Comment by ferrariofilippo** [comment]
Ctrl + ` Opens WT

**Comment by ferrariofilippo** [comment]
> I think it was @cinqmilleans with the RichCommand implementation

You're probably right

**Comment by hecksmosis** [comment]
> Ctrl + ` Opens WT

The more you know

**Comment by ferrariofilippo** [comment]
> Right, which is CTRL+Ñ in spanish. 

Just found out that Windows"translates" shortcuts, you should be able to open the terminal using that combination in Files too

**Comment by yaira2** [comment]
@francisco-lafe this will be available in the next release.

**Comment by francisco-lafe** [comment]
So it's going to be `CTRL+<tilde key>` for regular powershell and `CTRL+SHIFT+<tilde key>` for admin, on the current directory we're at.

**Comment by ferrariofilippo** [comment]
Yes, or you can select a folder to open that path

**Comment by PonyLucky** [comment]
This  works well in non latin layouts. By example in French there's `²` instead of `<TILDE>`. I suppose this will bothersome to support each layout. Would it be possible for this shortcut to watch the keycode as well ?

First as normal then keycode would ensure a non breaking update (Don't know if only keycode can actually break something, that's an hypothesis of mine).

**Comment by Josh65-2201** [comment]
It changes based on the keyboard layout. You can look up what the shortcut is for Visual Studio and it will be the same in Files.
