### ISSUE TITLE
Bug: WSL File Browsing issue

### ISSUE THREAD

**Issue by babs232** [files-community/Files#11272]
### Description

Unable to browse files in WSL file system
![image](https://user-images.githubusercontent.com/5404692/218505686-1e540aff-d4b6-44bc-aec8-f21cbb809f12.png)

### Steps To Reproduce

1. Open Files
2. Click on any distribution under WSL
3. Root directory folders will show up
4. Try to click on any folder, the attached error message would show up

### Steps to fix

- no idea

### Files Version

2.4.33.0

### Windows Version

10.0.22623.1255

### Log file

[debug.log](https://github.com/files-community/Files/files/10723879/debug.log)

**Comment by babs232** [comment]
Debug log does not have any exceptions or errors for that matter

**Comment by yaira2** [comment]
Is WSL running?

**Comment by babs232** [comment]
> 

Yes. I can browse from Windows Explorer

![image](https://user-images.githubusercontent.com/5404692/218958013-d2b685f4-0ee1-461d-9e1c-fe3dd066fe7b.png)

This issue is happening post the latest update. Before that it used to work normally, with all the copy-paste operations.

**Comment by mbush00** [comment]
Just wanted to confirm that I have the same issue. It used to work, but I can no longer access my wsl drive. Used to have a WSL folder (directory within my home dir) as a favourite and it magically disappeared as well.

![image](https://user-images.githubusercontent.com/41395074/219676952-f082ce81-8ab9-407f-b532-56530a6eb44f.png)

**Comment by habaneraa** [comment]
Same issue. but I have found something interesting:
In directory \\wsl.localhost\Ubuntu, if I double click any folder, it will pop out a window saying that "network folder error. the network name cannot be found." BUT if I right click the folder and use "Open in the new tab" option, the target directory will be displayed correctly in the new tab!

2 screenshots here
![image](https://user-images.githubusercontent.com/95517280/220506680-0f4144e9-8e5d-4dd0-9f34-7b2e96e1fd94.png)
![image](https://user-images.githubusercontent.com/95517280/220506785-5c7c5b0f-d056-460d-bc2c-d50f0ba4965f.png)

Furthermore, if I enter the WSL path string manually (such as "\\wsl.localhost\Ubuntu\home" in the second picture), i will *always* get the network folder error.

**Comment by GeoDoX** [comment]
+1 Can confirm I'm also having this issue. Right Click + Open in new tab does work as mentioned above.

**Comment by LolnationCH** [comment]
Can also reproduce this issue. From the log : 
![image](https://user-images.githubusercontent.com/9981795/224504353-2efde4ea-d125-49b3-97b6-0399369c5fa5.png)
Files version : 2.4.50.0
Windows 11 : 10.0.22621.1265

Workaround : use the windows explorer to map to a network drive the linux installation, and use the letter drive instead.

**Comment by Josh65-2201** [comment]
For future people, we know this is an issue. No more info or comments on saying you have the issue is needed. If this issue is fixed there will be a comment saying so. You can click subscribe for notifications on GitHub or check back here for updates.
