### ISSUE TITLE
Installer failing

### ISSUE THREAD

**Issue by otherside1** [files-community/Files#11271]
### Description

I have tryed the windows store installer and the non windows store installer both of them fail to install the windows store one give the error "Installer failed with exit code: 0x80070005 : Access is denied." 

### Steps To Reproduce

Download the winstaller or use winget install FilesCommunity.Files 
wait for the installer to get to 80%
It will fail and give that error

### Steps to fix

I have no Idea how to fix this.

### Files Version

2.4.21.0

### Windows Version

Windows 22H2   22621.1194

### Log file

There where no installer logs

**Comment by Josh-65** [comment]
Can you try using https://files.community/appinstallers/Files.Stable.exe

**Comment by otherside1** [comment]
I have

**Comment by otherside1** [comment]
It got to 90% and then just stoped

**Comment by Josh-65** [comment]
Can you try doing
1. Opening PowerShell window as administrator
2. Run this command
```Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/stable/Files.Package.appinstaller```

**Comment by otherside1** [comment]
Tryed that gives the error 0x80070005

**Comment by Josh-65** [comment]
Have you installed unofficial/modified (Remove preinstall apps, disabling Windows update etc..) version of Windows

**Comment by otherside1** [comment]
No

**Comment by Josh-65** [comment]
Can you screenshot the PowerShell Windows after you ran the command

**Comment by otherside1** [comment]
![Screenshot 2023-02-13 074922](https://user-images.githubusercontent.com/94060774/218461861-19eb00cb-9212-4220-986c-d42de5fb1031.png)

**Comment by Josh-65** [comment]
I'm not sure what wrong at this point. You can try running the below command in a admin CMD then restart and try the PowerShell install again. If it doesn't work then it some issue with your Windows install.

```
sfc /scannow
dism /online /cleanup-image /restorehealth
```

**Comment by otherside1** [comment]
I have ran both of the comands you put above and chkdsk.

**Comment by yaira2** [comment]
Does the preview version work?

**Comment by otherside1** [comment]
No

**Comment by yaira2** [comment]
What happens?

**Comment by otherside1** [comment]
App installation failed with error message: AppxManifest.xml(88,14): error 0x80070005: Cannot register the FilesPreview_2.4.34.0_x64__wvne1zexy08sa package because the following error was encountered while registering the windows.appExecutionAlias extension: Access is denied.
.  Try again and contact the package publisher if the problem persists. (0x80070005)

**Comment by yaira2** [comment]
This seems very much like a Windows issue, you mentioned you tried from the Store? Is this an issue with other apps as wel?

**Comment by otherside1** [comment]
Only files and files prevew seems to be affected

**Comment by otherside1** [comment]
In the past i have installed and uninstalled this app is it posible that is left somthing behind that is messing with the new install.

**Comment by yaira2** [comment]
There shouldn't be, uninstalling packaged apps removes everything.

**Comment by otherside1** [comment]
Where is the instaler located in the github repositroy i want to look at the locations it installes t

**Comment by yaira2** [comment]
It's installed to the WindowsPackages directory but the path depends on the installed version.

**Comment by otherside1** [comment]
Is there any .msi installer

**Comment by Josh-65** [comment]
No. That not have the app is packaged

**Comment by otherside1** [comment]
Is there any way I can find a copy of the program files and manulay install the app

**Comment by Josh-65** [comment]
You can try build it with Visual Studio https://github.com/files-community/Files#3-build-the-project but there isn't a portable version to use for that and it's not something you can copy into the folder.

**Comment by Josh-65** [comment]
I assume you haven't used this https://github.com/MishaTY/Rectify11Installer

**Comment by otherside1** [comment]
I have not userd rectify 11 on this pc

**Comment by yaira2** [comment]
You can try resetting the Store by running this command `wsreset -i`.

**Comment by otherside1** [comment]
I think this is an issue on my end so im closing the bug

**Comment by simonushie** [comment]
> Can you try doing
> 
> 1. Opening PowerShell window as administrator
> 2. Run this command
>    `Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/stable/Files.Package.appinstaller`

ran this command no error but didnt see anything afterwards

![image](https://github.com/files-community/Files/assets/43451941/fcd40ad6-0640-4880-8bcf-3231fb29c1f2)

**Comment by Josh65-2201** [comment]
Check the start menu for Files

**Comment by simonushie** [comment]
but 

> > Can you try doing
> > 
> > 1. Opening PowerShell window as administrator
> > 2. Run this command
> >    `Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/stable/Files.Package.appinstaller`
> 
> ran this command no error but didnt see anything afterwards
> 
> ![image](https://private-user-images.githubusercontent.com/43451941/312355152-fcd40ad6-0640-4880-8bcf-3231fb29c1f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMTYzMTMsIm5iZiI6MTcxMDMxNjAxMywicGF0aCI6Ii80MzQ1MTk0MS8zMTIzNTUxNTItZmNkNDBhZDYtMDY0MC00ODgwLThiY2YtMzIzMWZiMjljMWYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDA3NDY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2ZTFlNTJhOTA2ZTJhYzM4MmJkZmYzMWEwMWNhNTcyYjEzZGIzZDk1MzI0YmQwMmYxMmE1ZDdiNDFmNDk2NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-Gf6Rv1xqacY4c05oGWGDrfYaVagf2YlRzeZBqUPIQo)

after a while i noticed that it worked for me perfectly

![image](https://github.com/files-community/Files/assets/43451941/1992a297-bb62-49ed-98f7-1b9fe928e410)

even though the community version always gave me the  'access is denied' error

**Comment by BennettFourr** [comment]
I fixed this my doing a soft reset of my pc.
