### ISSUE TITLE
No min, max, close buttons on windows 10

### ISSUE THREAD

**Issue by mio-19** [files-community/Files#11273]
### Description

No min, max, close buttons on windows 10

![image](https://user-images.githubusercontent.com/57285379/218519244-dca022c5-9d43-48d4-826c-1046d0ad6dc6.png)

### Steps To Reproduce

Open Files

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

2.4.33.0 

### Windows Version

10.0.21390.1

### Log file

[debug.log](https://github.com/files-community/Files/files/10724337/debug.log)

**Comment by yaira2** [comment]
Are the buttons there if you move the mouse cursor? Sounds very much like an issue with WinAppSdk.

**Comment by mio-19** [comment]
I’ve downloaded and installed appsdk runtime 1.2.2 from microsoft before installing files

**Comment by mio-19** [comment]
They are clickable but I can’t see them
