### ISSUE TITLE
Discussion: Minimize to system tray

### ISSUE THREAD

**Issue by Lippiece** [files-community/Files#11279]
### What feature or improvement do you think would benefit Files?

Hi. Thank you for your work.

I suggest allowing the app to stay in memory and optionally close/minimise to tray. I suspect this could help tackle the horrible startup times.

### Requirements

- This proposal will help with performance
- This proposal will bring us one step closer to the return of the Reapers

### Files Version

preview

### Windows Version

Edition	Windows 10 Pro Version	22H2 OS build	19045.2486 Experience	Windows Feature Experience Pack 120.2212.4190.0

### Comments

This feature is implemented in [Sigma](https://github.com/aleksey-hoffman/sigma-file-manager) which is also a good alternative.

**Comment by yaira2** [comment]
Startup performance will get a lot better with Native AOT and IL Trimming.

**Comment by yaira2** [comment]
Fyi @d2dyno1 @JaiganeshKumaran feel free to add to this discussion

**Comment by Lippiece** [comment]
I must say that to keep the app in memory, you can close or not close it to tray. The closing to tray is the optional bit in my proposal. The main point is keeping it in memory.
If I'm correct about the bottleneck of the issue, of course.

**Comment by yaira2** [comment]
We hope to fix them but there are a number of memory leaks in Files, it's usually not a problem with most sessions being around 2 minutes but leaving it open in the background can cause Files to use a lot of resources and potentially crash if it runs out of memory.

**Comment by Jay-o-Way** [comment]
> potentially crash if it runs out of memory.

That sounds more like a leak

**Comment by yaira2** [comment]
We have some long-term plans to add a flyout to the system tray area but we'll need to make some progress on memory usage before staying open in the background.

**Comment by yaira2** [comment]
@Lippiece this feature is included in the latest preview build (https://files.community/download) and will be included in the v3 release.
