### ISSUE TITLE
Crash when going to advanced page in settings

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#11277]
### Description

*

### Steps To Reproduce

1. Open setting
2. Click the advance page

### Steps to fix

?

### Files Version

2.4.34.0

### Windows Version

10.0.22621.1105

### Log file

[debug.log](https://github.com/files-community/Files/files/10725423/debug.log)

**Comment by yaira2** [comment]
Have you made any modifications to the tags file?

**Comment by Josh-65** [comment]
Turns out one of the UID missing a `:` added it and now it works.
