### ISSUE TITLE
Files Crashes On Launch

### ISSUE THREAD

**Issue by KinglyMinecon** [files-community/Files#11275]
### Description

Alot of the time when I launch the files app it closes and says that an error occured. When this error occurs I have to keep opening the app

### Steps To Reproduce

Open the App

### Steps to fix

Fix the crash that occurs when I open the app.

### Files Version

2.4.33.0

### Windows Version

Windows 11 Pro 22H2 22621.1105

### Log file

[debug.log](https://github.com/files-community/Files/files/10724927/debug.log)

**Comment by yaira2** [comment]
What's your screens resolution? Can you reproduce this issue in other resolutions?

**Comment by KinglyMinecon** [comment]
I am no longer having this issue after a restart which is strange as I have already restarted and the issue still existed

**Comment by KinglyMinecon** [comment]
This is really weird

**Comment by yaira2** [comment]
I saw the crash in the log file, used to happen on some screen resolutions but I havent seen it for a while. These issues are very difficult to debug.

**Comment by yaira2** [comment]
@KinglyMinecon can you check again in v2.4.40?
