### ISSUE TITLE
Feature: Option to format drives should be displayed in the main menu

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#11284]
### What feature or improvement do you think would benefit Files?

The option to format drives is currently in the overflow menu, we should make it more accessible and move it to the main menu.

### Requirements

- Display option to format drives in the main menu when right clicking them
- This should apply to the sidebar and drives widget

### Files Version

v2.4.34

### Windows Version

Windows 11

**Comment by yaira2** [comment]
If need be, we should implement the command ourselves in order to reduce the time it takes to load the context menu.

**Comment by hecksmosis** [comment]
Should we redo the format dialog from windows?

**Comment by yaira2** [comment]
Not right now, perhaps Microsoft will the work on this for us 🙂

**Comment by hecksmosis** [comment]
Ok
