### ISSUE TITLE
Feature: Show "send to" in the main context menu

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#11283]
### What feature or improvement do you think would benefit Files?

We currently load the send to options in the "show more options" menu, these options are commonly accessed so we should change the behavior and show them in the main menu. We do something similar for the "open with" menu.

### Requirements

- Show send to menu item in the main context menu

### Files Version

v2.4.34

### Windows Version

Windows 11

**Comment by hecksmosis** [comment]
I'm working on this, but I haven't found a way to correctly find the Send to item which is language independent

**Comment by hecksmosis** [comment]
(it can be done with `Label: "Send to"`)

**Comment by yaira2** [comment]
We used command string for "open with", maybe we can do the same for send to.
