### ISSUE TITLE
Ability to reconnect to disconnected network drives 

### ISSUE THREAD

**Issue by distrair** [files-community/Files#11294]
### What feature or improvement do you think would benefit Files?

For those who had set Files app as default, does not have ability to reconnect to previously connected network drives  

### Requirements

-Have a disconnected network drive on the left panel and in the home page
-Clicking on this disconnected network drive will try to connect to it

### Files Version

2.4.33.0

### Windows Version

Windows 11 22H2 22621.1194

**Comment by yaira2** [comment]
Merging with #10905
