### ISSUE TITLE
cant install on windows 10 Version 20H2 OS Build 19042

### ISSUE THREAD

**Issue by MesterPerfect** [files-community/Files#11296]
### Description

i cant install files on windows 10 Version 20H2 OS Build 19042
Files installation failed. App Installer failed to install package dependencies. Ask the developer for  package

### Steps To Reproduce

1. download ffile 
2. https://github.com/files-community/Files/releases/tag/v2.4.33
3. install files

### Steps to fix

I can't install app any way I know and I don't know where the problem is
Files installation failed. App Installer failed to install package dependencies. Ask the developer for  package

### Files Version

2.4.33.0

### Windows Version

Edition	Windows 10 Pro Version	20H2 Installed on	‏15/‏09/‏2022 OS build	19042.1706 Experience	Windows Feature Experience Pack 120.2212.4170.0

### Log file

[log.log](https://github.com/files-community/Files/files/10734823/log.log)

**Comment by Josh-65** [comment]
Download from https://files.community/download
