### ISSUE TITLE
Feature: Show manage BitLocker option in main menu for drives

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#11303]
### What feature or improvement do you think would benefit Files?

The option to manage BitLocker is currently in the overflow menu, showing it in the main menu would improve the user experience and make it easier to access.

### Requirements

- This proposal will show the manage BitLocker option in the main menu when right clicking drives on the sidebar and home page

### Files Version

v2.4.34

### Windows Version

Windows 11

**Comment by jai1113gunnnala** [comment]
hey!! can I work on this?

**Comment by Josh-65** [comment]
Yes just make a pull request with the changes
