### ISSUE TITLE
`Add to favourites` option shown on files

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#11305]
### Description

When opening the context menu on a file there's an `Add to favourites` option witch doesn't work

### Steps To Reproduce

1. Right click on a file

### Steps to fix

- Remove `Add to favourites` option on files

### Files Version

2.4.34.0

### Windows Version

10.0.22621.1194

### Log file

*

**Comment by yaira2** [comment]
It works but we don't display them in Files (you can check File Explorer), it's currently limited to the preview builds of Windows so we're waiting for it to be released before creating a widget.
