### ISSUE TITLE
Feature: Keyboard shortcut or programmatic way to open file in specific app

### ISSUE THREAD

**Issue by reidprichard** [files-community/Files#11314]
### What feature or improvement do you think would benefit Files?

As part of my workflow, I have a macropad with buttons dedicated to open files I've selected in Explorer in the app of my choosing. This is accomplished by AutoHotkey tapping into the COM interface to get the paths of selected files. In PowerShell, a simplified version of this would look like `(New-Object -ComObject Shell.Application).Windows()[0].Document.SelectedItems() | Select-Object Path` (gets path of first selected item in first open Explorer window).

I have no idea if this is a realistic request, but would it be possible to register a COM object to allow programmatic interaction with Files? Alternatively, it would accomplish my current goals to have customizable keyboard shortcuts for "Open selected file(s) with ____ application".

My knowledge of the Windows APIs is pretty limited, so it's possible that there's already a way to do this?

### Requirements

Either:
1. A COM object will allow programmatic interaction with Files OR
2. A keyboard shortcut will open selected file(s) with the specified .exe

### Files Version

2.4.33.0

### Windows Version

10.0.22621.1265

**Comment by yaira2** [comment]
I'm not sure if we can add official support but depending on the action, you can already use auto hot key to trigger keyboard shortuct.s  but https://github.com/files-community/Files/issues/2355#issuecomment-927377572

**Comment by reidprichard** [comment]
Fair enough. Yeah, I think it should be doable by sending F2, Ctrl+A, Ctrl+C to get the name of the selected item, though that wouldn't work for multiple files.
Just thought I'd ask!

**Comment by yaira2** [comment]
Perhaps we can implement this natively when we add support for custom actions.

**Comment by yaira2** [comment]
@cinqmilleans do you think we can support this with custom actions?

**Comment by cinqmilleans** [comment]
This is something that will be very easy to do with actions. In a next iteration, there will be a mechanism to add/remove custom actions in CommandManager. It will be enough to create an Action class, instantiate it with the parameters (software, hotkey, ...), add it to the commands and the shortcut will work. It will be necessary to provide a repository to store custom hotkeys and actions, but it is an overlay to CommandManager.

**Comment by yaira2** [comment]
@reidprichard thank you for your feedback, we're going to continue tracking this feature in #15141.
