### ISSUE TITLE
When opening image in Photos, cannot browse to other photos in same folder

### ISSUE THREAD

**Issue by reidprichard** [files-community/Files#11315]
### Description

In a folder with multiple pictures, I should be able to browse through the pictures in the Windows 11 Photos app. If I open a picture in the folder from Explorer, this works as expected. However, opening a picture from Files only loads the specific picture - the rest of the pictures in the folder are missing their thumbnails and just endlessly load when I select them. However, Photos shows the correct _number_ of thumbnails despite not loading them.

### Steps To Reproduce

1. Open Files
2. Navigate to a folder containing pictures (PNGs in this case)
3. Double click one to open it
4. Use the left or right arrow to navigate to a different picture in the folder

### Steps to fix

- Allow browsing through a folder full of pictures when opened in Photos

### Files Version

2.4.33.0

### Windows Version

10.0.22621.1265

### Log file

[debug.log](https://github.com/files-community/Files/files/10746244/debug.log)

**Comment by yaira2** [comment]
I can't reproduce this issue, where are the photos located?

**Comment by reidprichard** [comment]
The particular files I was talking about are stored on OneDrive, and the path had a space in it - both of which I know can cause issues. 

I tried again on several other directories which contained other file extensions (.TIF, .CR2, and .JPG), and the issue still shows up. However, opening the file with Windows Photo Viewer (the legacy version of Photos) works as expected, with all other pictures in the directory being viewable.

**Comment by reidprichard** [comment]
Without knowingly changing anything on my end, I just gave this another shot and everything worked (same files, same directory). Not sure if a change in [v2.4.40](https://github.com/files-community/Files/releases/tag/v2.4.40) fixed it? Or perhaps something changed on MS's end. Anyway, closing this!

**Comment by reidprichard** [comment]
This has been intermittently reappearing. I can't put my finger on what causes it to come or to go.

**Comment by reidprichard** [comment]
I think I know what's going on. When images in an open directory are overwritten, the thumbnails aren't generated until Files is manually refreshed. I believe this is causing the issues in the photo viewer.

**Comment by reidprichard** [comment]
Never mind - I have a directory with three images, all of which show thumbnails, yet I can't browse between them after opening any one of them.

**Comment by Josh65-2201** [comment]
@reidprichard Is this still an issue for you in 2.5.21.0?

**Comment by x-rated** [comment]
just letting you know this old issue still occurs in 3.9.13 😔

https://github.com/user-attachments/assets/39efc35c-824b-4667-8cc1-123e63686082

**Comment by Josh65-2201** [comment]
It's an issue with Microsoft Photos, see #15409

**Comment by yair100** [comment]
As this is an issue with Microsoft Photos, users have been able to work around this by switching to other photo apps.
