### ISSUE TITLE
Bug: Can't select any option in the "Compatibility" tab in the Properties of a .exe file.

### ISSUE THREAD

**Issue by thiagojramos** [files-community/Files#11317]
### Description

I can't select any option in the "Compatibility" tab in the properties of an .exe file. But through the Windows file explorer, I can adjust the options.
![2023-02-15 (4)](https://user-images.githubusercontent.com/45890502/219173688-6a88d83c-ec9e-47fb-9086-14dfda955317.png)

### Steps To Reproduce

1. Go to .exe file
2. Click on "properties"
3. next, click on "compatibility" tab

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

2.4.33.0

### Windows Version

Windows 11 - 22623.1255

### Log file

[debug.log](https://github.com/files-community/Files/files/10748112/debug.log)

**Comment by yaira2** [comment]
Does it work if you run Files as admin?

**Comment by thiagojramos** [comment]
Not even this way works.


https://user-images.githubusercontent.com/45890502/219226275-d72fa428-5c74-4e76-9c68-d1f8a5dfa842.mp4

[debug.log](https://github.com/files-community/Files/files/10750727/debug.log)

**Comment by yaira2** [comment]
Are you sure that's running as admin? Unless you turned it off, there is usually a UAC prompt.

What happens if you copy the file to a different location (eg. downloads)? It might be a permissions issue with Files.

**Comment by thiagojramos** [comment]
Yes, it is being run as an administrator. I did deactivate the UAC prompt. The first video below shows the file in "Downloads" and another file in "Documents". In the second video, it shows the same, but now in the native Windows file explorer.

https://user-images.githubusercontent.com/45890502/219437576-f65cfaf3-dd36-410b-8e51-1a4b340782e1.mp4

----------------------

https://user-images.githubusercontent.com/45890502/219437616-03d5ee50-043c-4a25-b9cf-ef0420264112.mp4

----------------------

**Log**: [debug.log](https://github.com/files-community/Files/files/10758599/debug.log)

**Comment by yaira2** [comment]
@thiagojramos this will be fixed in the update following v2.4.40.
