### ISSUE TITLE
Tab switching not working properly

### ISSUE THREAD

**Issue by SakifKhan98** [files-community/Files#11312]
### Description

So, whenever I open Files with more than one tab and put the pc to sleep, and come back to access it, it starts to behave weirdly.

_N.B. This is my first time opening an issue, please have a soft look if I make any mistake._

### Steps To Reproduce

1. Open the files app.
2. Open 2/3 new tabs in the same window by pressing the + icon at the top.
3. Minimize the files window.
4. Put the PC to sleep mode.
5. Log back in and maximize the previously opened files window.
6. Try to click on the previously opened other tabs.

### Steps to fix

I ain't sure about the steps to fix it as I have no experience with Windows Desktop Application Development. Just trying to report it.

### Files Version

App Version: 2.4.33.0, OS Version: 10.0.22000.1219

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎12/‎17/‎2021 OS build	22000.1219 Experience	Windows Feature Experience Pack 1000.22000.1219.0

### Log file

[debug.log](https://github.com/files-community/Files/files/10745095/debug.log)

**Comment by SakifKhan98** [comment]
Whenever I click them, some of them stop responding, and some of them just bounce out of the old window as a new window and behave weirdly i.e. When I double-click a folder, it opens another. Or sometimes the cursor freezes/lags.

**Comment by Josh-65** [comment]
> some of them just bounce out of the old window as a new window

Tab are sensitive to when they make a window that's been tracked here #11081

> When I double-click a folder, it opens another. 

Do you have Files settings > Folders > Opening items > Open folders in a new tab on?

**Comment by SakifKhan98** [comment]
I think I was not clear about what I was saying.

> When I double-click a folder, it opens another.

By this, I meant that after double-clicking the wrong folder was being opened, not the one I was trying to open.

**Comment by Josh-65** [comment]
Can you see if it an issue in the preview version from https://files.community/download

**Comment by SakifKhan98** [comment]
Yes, I tested it with the preview version, and the issue persists. Following is the recent log file with Preview version.
[debug.log](https://github.com/files-community/Files/files/10754898/debug.log)

**Comment by yaira2** [comment]
Merging with #6111
