### ISSUE TITLE
Bug: Deleting online-only files from OneDrive removes files regardless of the confirmation prompt

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#11318]
### Description

Deleting online-only files from OneDrive removes files regardless of the confirmation prompt. This is actually the correct behavior considering File Explorer does the same exact thing, but I think it's preferable to let the user choose and follow the option we have in settings.

### Steps To Reproduce

1. Open OneDrive
2. Create any type of file
3. Right click and choose the option to free up space
4. Delete file
5. See that it's deleted before the user confirms

### Steps to fix

- Allow the user to choose

### Files Version

v2.4.34

### Windows Version

Windows 11

### Log file

NA

**Comment by hishitetsu** [comment]
When deleting online-only file, it will not go into the local Recycle Bin, but it will go into the online Recycle Bin on Onedrive.
It may be a little confusing but we can restore the file, so I think it is ok to leave it as it is.

**Comment by yaira2** [comment]
The main point is that it shouldn't delete until the user clicks on the "confirm" button.

**Comment by hishitetsu** [comment]
Sorry, I understand. When the confirmation dialog appears, the file has already been deleted. This is certainly a problem.

**Comment by yaira2** [comment]
File Explorer doesn't even show the prompt by default (seems odd) but this can be another area where we differentiate in a better way :)
