### ISSUE TITLE
ARRESTO PROGRAMMA

### ISSUE THREAD

**Issue by isaemasolution** [files-community/Files#11322]
### Description

Programma si blocco dopo cambio colore sfondo

### Steps To Reproduce

1 aprire impostazioni
2 cambiare colore sfondo
3 riaprire impostazioni
4 il programma si blocca e si chiude

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

2.4.33.0

### Windows Version

10.0.22623.1255

### Log file

[debug.log](https://github.com/files-community/Files/files/10754605/debug.log)

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by ferrariofilippo** [comment]
Yes

If you need a translations of steps:
Files crashes after changing background color

1. Open Settings
2. Change background color
3. Open Settings again
4. Files Crashes

**Comment by yaira2** [comment]
This will be fixed in the update following v2.4.40
