### ISSUE TITLE
Feature: Disable the display of Cloud Drive space information.

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#11326]
### What feature or improvement do you think would benefit Files?

As noted in #10001, the Cloud Drive space information is not displayed correctly.
But it may be a lot of work to get this right, so we should probably eliminate the display until we can fix it.
I think it is better not to display the wrong information than to display the wrong information.

### Requirements

Disable the display of Cloud Drive space information until we can display the right information.

### Files Version

Version: 2.4.33.0

### Windows Version

Windows 11 22H2 22621.1265

**Comment by yaira2** [comment]
I think we should try and fix this, there might be an api we can use (similar to how we get the file status)

**Comment by hishitetsu** [comment]
In Files, Getting the file status is already possible using the offline API. I am going to use this to fix #11318 . But there doesn't appear to be an offline API to retrieve the cloud drive capacity.

We can do it by using online APIs, but it requires the account authentication which is not currently required.
Using online APIs is a bit hard work and each cloud drive has different APIs, so it would be better to not display capacity until it can be implemented, and only display that have been implemented.

**Comment by yaira2** [comment]
We can add custom logic for each cloud provider, the default should be to disable the capacity but with support for enabling it if possible.

**Comment by hishitetsu** [comment]
Yes, that would be good.
