### ISSUE TITLE
Acrylic mode

### ISSUE THREAD

**Issue by redhotideas** [files-community/Files#11323]
### What feature or improvement do you think would benefit Files?

Can acrylic mode come back in the next release?

### Requirements

- acrylic mode on

### Files Version

v2.4.33

### Windows Version

Windows 11 Pro Versione 22H2

### Comments

pleeeease

**Comment by Josh-65** [comment]
See comment here https://github.com/files-community/Files/issues/10690#issuecomment-1387196659

**Comment by Josh-65** [comment]
Also stop making new issue for this you always going to get the same answer
