### ISSUE TITLE
Scolling bug

### ISSUE THREAD

**Issue by techIndia-hacker** [files-community/Files#11339]
### Description

I am absolutely unable to use your files app for windows. My laptop touchpad two finger scrolling isn't working at all for any pages.

My touchpad works fine for Default windows explorer or websites etc

Driver: Synaptics Mouse

### Steps To Reproduce

just go to any folder with hundreds of smaller files and try to scroll

### Steps to fix

No fix found

### Files Version

2.4.33.0

### Windows Version

Windows 11 21H2 22000.1574

### Log file

[debug.log](https://github.com/files-community/Files/files/10766751/debug.log)

**Comment by Josh-65** [comment]
- If you have software called XMouse control? if so you can try creating a separate profile for Files.exe > Options > enable `Disable Scroll Window Under Cursor`

- You can also try going to Windows Settings > Bluetooth & devices > Mouse > Enable `Scroll inactive windows when hovering over them`

- It may also be caused by https://github.com/microsoft/WindowsAppSDK/issues/2791 in this case it can not be fixed in Files but the above option should get it working.

**Comment by techIndia-hacker** [comment]
`Windows Settings > Bluetooth & devices > Mouse > Enable Scroll inactive windows when hovering over them`
is enabled in my Windows 11, I turned it off and on but nothing worked.

I don't have Xmouse

**Comment by yaira2** [comment]
Can you see if scrolling works in the WinUI 3 Gallery app?

**Comment by yaira2** [comment]
@techIndia-hacker

**Comment by techIndia-hacker** [comment]
Gallery app scrolling works. Will update windows and check for bug again from 21h2 yo 22h2

**Comment by yaira2** [comment]
Thanks

**Comment by techIndia-hacker** [comment]
I am on 22h2 windows 11 now. Still can't scroll in folders. I downloaded latest stable files app just now

**Comment by techIndia-hacker** [comment]
In ur windows system is it working?

**Comment by APursch** [comment]
I have a similar no scroll situation using Logitech mouse where middle scroll button doesn't work in Files.

**Comment by yaira2** [comment]
Which layout mode? Does scrolling work in the settings dialog?

**Comment by APursch** [comment]
> Which layout mode? Does scrolling work in the settings dialog?

Not in any of the layout and not in the settings dialog, i.e. left click and drag the scroll bar works - even if the scroll bar is a bit narrow ;-) - but does not scroll with middle scroll wheel.

**Comment by APursch** [comment]
> 

BTW. not working in the folder tree on the left either.

**Comment by yaira2** [comment]
This sounds like a serious WinAppSdk issue, we're using default WinUI controls without anything custom. Can you report this on the WinUI repository? If they ask, we're using WinAppSdk 1.2.

**Comment by techIndia-hacker** [comment]
@APursch Yeah same situation, anyways the stock windows explorer is fixed in 22h2

**Comment by yaira2** [comment]
File Explorer is going to have the same issue when they switch to WinAppSdk.

**Comment by APursch** [comment]
> 

Happy to but way over my technical ability; please feel free to quote me if you do.

**Comment by techIndia-hacker** [comment]
> This sounds like a serious WinAppSdk issue, we're using default WinUI controls without anything custom. Can you report this on the WinUI repository? If they ask, we're using WinAppSdk 1.2.

U as a developer, should talk about the issue in their repositories. If they want logs, we can send them

**Comment by techIndia-hacker** [comment]
@yair100 I posted this issue on win ui 3 gallery app too

**Comment by APursch** [comment]
Nice to see the scroll bars working - NOT the case with the mouse wheel, maybe one day?
I shall uninstall it again meantime

**Comment by yaira2** [comment]
It's a platform issue with WinUI, and not specific to Files.
