### ISSUE TITLE
Bug: Error while renaming a folder on server (Synology Nas)

### ISSUE THREAD

**Issue by elhombre666** [files-community/Files#11338]
### Description

Folder renaming went wrong, freezed and stopped. (Files is set as default files explorer, we live dangerously here)

### Steps To Reproduce

- Duplicate a folder in the column view (4th column)
- Click on rename
- wait... 
- Freezes. 

### Steps to fix

allow to rename a folder who's duplicated ? 

### Files Version

2.4.33.00

### Windows Version

Windows 11 22h2 22621.1265

### Log file

[debug.log](https://github.com/files-community/Files/files/10766142/debug.log)

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by yaira2** [comment]
@elhombre666 is this only an issue in column layout?

**Comment by yaira2** [comment]
@elhombre666 thank you for your feedback, we were able to reproduce this issue and we're happy to share that it's been fixed in v2.4.66.

**Comment by elhombre666** [comment]
Hello, sorry, didn't notice that I received e-mail from github, I'll check is this ok ! Thanks

De : Yair ***@***.***>
Envoyé : vendredi 21 avril 2023 04:13
À : files-community/Files ***@***.***>
Cc : elhombre666 ***@***.***>; Mention ***@***.***>
Objet : Re: [files-community/Files] Bug: Error while renaming a folder on server (Synology Nas) (Issue #11338)


Closed #11338<https://github.com/files-community/Files/issues/11338> as completed.

-
