### ISSUE TITLE
Enforce Xaml indentation in EditorConfig

### ISSUE THREAD

**Issue by heftymouse** [files-community/Files#11337]
### Description

Similar to what is currently there for C# source files, it would make Visual Studio automatically use tabs instead of the default spaces

### Concerned code

All Xaml files

### Gains

A more seamless contribution experience by having code automatically comply with style guidelines

**Comment by yaira2** [comment]
Do you want to do this?

**Comment by heftymouse** [comment]
Sure, I'll do it
