### ISSUE TITLE
Groups in the Downloads folder are not being sorted

### ISSUE THREAD

**Issue by OscarDL** [files-community/Files#11333]
### Description

On the latest stable version of Files (currently v2.4.33.0), sorting within file groups in the Downloads section works properly, but the grouping itself isn't.

For instance, I set both "group by" and "sort by" to be from newest to oldest, and the sorting within groups works great, but the "Older" group still always shows first, which is super inconvenient.

![example](https://user-images.githubusercontent.com/27915933/219501918-9e6f4db4-dc3b-4a95-a904-c07f6333e508.png)

### Steps To Reproduce

1. Click on the sort icon in the Downloads folder,
2. Group By Date modified + Descending,
3. Groups are still ordered the wrong direction.

### Steps to fix

Haven't found a way to make it the correct sorting direction, so can't list any steps to fix.

### Files Version

Version: v2.4.33.0 OS Version: 10.0.22623.1255

### Windows Version

Windows 11 Pro 22H2 22623.1255

### Log file

[debug.log](https://github.com/files-community/Files/files/10761466/debug.log)

**Comment by Josh-65** [comment]
What happens when you set Grouping to ascending order?

**Comment by hishitetsu** [comment]
It seems all files is in the Older group. It contains files up to last year.

**Comment by hishitetsu** [comment]
@Josh-65 I don't think it is a bug. It is working as intended. Should the Older group be further divided?
