### ISSUE TITLE
Bug: Could not delete large files

### ISSUE THREAD

**Issue by MagidElgady** [files-community/Files#11330]
### Description

Had an external hard drive with files > 100GB and I kept getting "Deletion failed".

### Steps To Reproduce

1. Find large file.
2. Delete large file.
3. Get message saying "Deletion failed."

### Steps to fix

- Use Windows File Explorer instead of the Files App to delete large files.
- Defeats purpose of App 😂.

### Files Version

2.4.33.0

### Windows Version

Windows 10 Enterprise LTSC 21H2 19044.2604

### Log file

No log file

**Comment by Josh-65** [comment]
- Can you please upload the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.
- What file system format is your external drive using?
- Do you get any message in File explorer?

**Comment by MagidElgady** [comment]
1) [debug.log](https://github.com/files-community/Files/files/10760703/debug.log)
2) NTFS
3) Just "Deletion failed" in the Files app.

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
