### ISSUE TITLE
Feature: Show rotate options in the main context menu

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#11345]
### What feature or improvement do you think would benefit Files?

The option to rotate images is currently in the "show more options" menu, we already have our own implementation of these commands for the toolbar. We should reuse these commands in the context menu.

### Requirements

- This proposal will hide the shell extensions for rotating images
- This proposal will add menu options using our own implementation (options should show after "set as").

### Files Version

v2.4.40

### Windows Version

Windows 11

**Comment by yaira2** [comment]
@puppetsw I think you worked on the implementation for toolbar, do you have interest in doing this as well?

**Comment by puppetsw** [comment]
> @puppetsw I think you worked on the implementation for toolbar, do you have interest in doing this as well?

@yair100 Sure, I'll look into it.
