### ISSUE TITLE
Bug: App crashes/freezes when right-clicking on files and folders

### ISSUE THREAD

**Issue by xIUPITERx** [files-community/Files#11342]
### Description

1. right click on specific files
2. app crashes

### Steps To Reproduce

1. right click on a media file
2. or right click on a folder that has been optimized for media content and directly in it is a media file.
3. shell menu opens and app freezes 
4. app crashes

### Steps to fix

app shouldn't crash when opening the shell menu.

### Files Version

5.4.40

### Windows Version

Windows 11 Pro 22621.1265

### Log file

[debug.log](https://github.com/files-community/Files/files/10767965/debug.log)

**Comment by yaira2** [comment]
Is this consistent?

**Comment by xIUPITERx** [comment]
The shell menu opens, freezes and the app crashes.

But apparently not all files are affected. I can still right click on shortcuts and links, but not on folders and png mp4 and over big files.

**Comment by xIUPITERx** [comment]
I can also exclude 3rd party shell entries, as I have deactivated them in order and it still happend.

**Comment by yaira2** [comment]
Interesting, what about txt or docx files?

**Comment by xIUPITERx** [comment]
`txt, pdf, java, docx` are working

`png, ico, mp4, mkv` are not working

Some folders can be open, some folders not.

**Comment by yaira2** [comment]
Seems specific to media files then, what about PowerPoint and Excel?

**Comment by yaira2** [comment]
Is there any shell extension (or any option in "show more options") that's common only to these files?

**Comment by xIUPITERx** [comment]
> Some folders can be open, some folders not.

Folders that mainly contain files that do not work will not work either.
Folders that only contain txt etc do work.

**Comment by xIUPITERx** [comment]
> Seems specific to media files then, what about PowerPoint and Excel?

These two also work

**Comment by yaira2** [comment]
It's interesting that the contents of the folder are making a difference

**Comment by yaira2** [comment]
There is nothing in the log file. Do you have Visual Studio?

**Comment by xIUPITERx** [comment]
> It's interesting that the contents of the folder are making a difference

![image](https://user-images.githubusercontent.com/97352673/219697986-6ee75cb3-b8bf-4542-b8a8-4e2584b7c97e.png)
 Folders that are optimized for pictures, music and videos don't work.

**Comment by yaira2** [comment]
Right clicking on music freezes the app for around 2 seconds but then it continues working. This certainly can be a factor for the folders crash.

**Comment by yaira2** [comment]
I just got this `ppUnhandledException|The server threw an exception. (0x80010105 (RPC_E_SERVERFAULT))
	System.Runtime.InteropServices.COMException (0x80010105): The server threw an exception. (0x80010105 (RPC_E_SERVERFAULT))`

**Comment by yaira2** [comment]
@dahall @hez2010 calling the experts 😂 

Do you have any idea what can be going on here?

**Comment by xIUPITERx** [comment]
> Is there any shell extension (or any option in "show more options") that's common only to these files?

I compared the shell entries in the normal file explorer and there was no difference.

**Comment by Josh-65** [comment]
The error is the same for #11149, #11332 and #11150

**Comment by yaira2** [comment]
I can confirm it's the same issue but let's keep this open for now as it has addition info.

**Comment by xIUPITERx** [comment]
> > It's interesting that the contents of the folder are making a difference
> 
> ![image](https://user-images.githubusercontent.com/97352673/219697986-6ee75cb3-b8bf-4542-b8a8-4e2584b7c97e.png) Folders that are optimized for pictures, music and videos don't work.

It's both, the folder has to optimized for media content **and** directly in it has to be a media file.
If it's optimized for general files and a media file is in it, the folder still works and if it's optimized for media content, but no media file is in it, it also works.

**Comment by hishitetsu** [comment]
#10592 and #11104 may also be the same issues. "Cast to Device" (playtomenu.dll) seems to cause these error. But it works fine in my environment.
Does the error occur or not depending on the device?

**Comment by xIUPITERx** [comment]
> Does the error occur or not depending on the device?

It occurs on all of my windows PCs (two), but they have nearly the same software configuration, so it could be caused by a common third party program.

**Comment by hishitetsu** [comment]
I don't mean the PC, but the device to which it is cast. I think that the error may be caused by the device to which it is cast.

**Comment by yaira2** [comment]
@hishitetsu does adding "Cast to Device" to the list of known menu items solve this issue?

**Comment by hishitetsu** [comment]
I don't know because I can't reproduce it. I will submit a PR to do so in draft for now.
