### ISSUE TITLE
Bug: Adding a tag to folders breaks search

### ISSUE THREAD

**Issue by Silther** [files-community/Files#11343]
### Description

Since the function was added, that tags could be shown in the start menu they no longer worker in the side menu.
This happens on multiple PCs with the same tag names
![image](https://user-images.githubusercontent.com/97352673/219688494-19e847f1-7cbe-4440-a480-134ff9376d42.png)
use
![image](https://user-images.githubusercontent.com/97352673/219688749-21f95e9a-11ec-4f63-92c4-9b39dc8ccaca.png)

### Steps To Reproduce

1. Tag a folder
2. tag a shortcut
3. At the start tab widget you will see both files
4. click on the tag via the side menu or detailed layout 
5. the folder is not visible but the shortcut is.
6. if you only tag a folder, you wont be able to see it, but there will be no message `No items found`

### Steps to fix

show tags in the side menu

### Files Version

7.4.40

### Windows Version

Windows 11 Pro 22621.1265

### Log file

[debug.log](https://github.com/files-community/Files/files/10767984/debug.log)

**Comment by yaira2** [comment]
Are these locations indexed? What happens if you turn on the setting to search unindexed locations?

**Comment by xIUPITERx** [comment]
Yes the locations are indexed.
What amazes me is that the tags are displayed correctly in the start tab.

**Comment by xIUPITERx** [comment]
Could it be the Uid of the tags?
I have now created new tags that are identical to the old ones but have new Udis and so far everything works.
But because of #11342, I can't be sure if it's the IDs because I can only tag shortcuts.
And the error occurred mainly with folders.

**Comment by yaira2** [comment]
That's certainly possible, we're going to have to figure out what's going on with the context menu but in the meantime, you can drag items to a tag in the sidebar to add the tag :)

**Comment by xIUPITERx** [comment]
I tried it, as soon as folders were tagged, all tagged files of the one tag are no longer accessible through the side menu.

**Comment by yaira2** [comment]
Can you update the steps in the description to reproduce this issue?

**Comment by xIUPITERx** [comment]
> What happens if you click a tag in the details layout, do it work there?

that also doesn't work.

**Comment by yaira2** [comment]
Thank you for testing, I really appreciate your willingness to figure out the exact steps to reproduce both this issue and the one with the context menu. I don't have an ETA for fixing them but having good steps to reproduce the issue certainly helps.

**Comment by xIUPITERx** [comment]
wonderful,
If you use such a great app, you should also help out when you have the chance :)

**Comment by ferrariofilippo** [comment]
What happens if you refresh the page?

**Comment by xIUPITERx** [comment]
> What happens if you refresh the page?

Nothing

**Comment by hishitetsu** [comment]
I tagged a folder and opened the tag search results via the sidebar. It shows the tagged folder for me.

**Comment by ferrariofilippo** [comment]
I can't reproduce this anymore

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
