### ISSUE TITLE
A Important Feature about WebDAV Requested 

### ISSUE THREAD

**Issue by lmls1811** [files-community/Files#11350]
### What feature or improvement do you think would benefit Files?

I found that I can't open my webDAV in this app successfully.It displayed"Did you delete this folder?"when I was trying visiting it.
Also I want win11 icons.You can learn it from "My Files-X"app from ms store.

### Requirements

Sorry, I'm a noob in programming

### Files Version

2.4.33.0

### Windows Version

Windows 10 22H2 19045.2486

### Comments

![image](https://user-images.githubusercontent.com/98952700/219821783-36cb77c4-e5f0-44ae-b842-b635f47bf682.png)

**Comment by Josh-65** [comment]
Merging with #3917

The icons follow Windows you can install an unofficial icon pack (YOU WONT GET SUPPORT DOING THIS) or upgrade to Windows 11
