### ISSUE TITLE
Hotkey to add tags

### ISSUE THREAD

**Issue by surya467** [files-community/Files#11352]
### What feature or improvement do you think would benefit Files?

Hotkey Tags

### Requirements

I was wondering if its possible to add hotkey to add tag
So say if i select a file or folder and press Ctrl + 1 - Tags green(this can be customized as per user)
If i select file or folder and press Ctrl + 2 - Tags red(this can be customized as per user)
and so on. This is a feature in MacOS i guess, but i find it really handy for my workflows and i really miss it.
Thanks!

### Files Version

2.4.33.0

### Windows Version

Windows 11 Pro Version	22H2 Installed on	‎1/‎26/‎2023 OS build	22621.1265 Experience	Windows Feature Experience Pack 1000.22638.1000.0

### Comments

Pls do add this if possible, Thanks a ton mate!

**Comment by yaira2** [comment]
Does MacOS allow you to choose a hot key for each tag or is it automatically assigned?

**Comment by surya467** [comment]
https://www.youtube.com/watch?v=go1AmFkE4Jo

you can check this video to understand more.

**Comment by yaira2** [comment]
We'd like to learn more about your use case but watching a video isn't going to do it.

**Comment by surya467** [comment]
Ok so im working on this project that is like a bulk process.
I have to load one file after the other manually into after effects.
So when i am done loading 1 file, i just want to tag it with a color to
know its done. Because the naming of rhe files are similar and its easy to
lose track of which file i selected before.

Earlier i used a macbook so i could use the tags to just mark the one i
loaded by pressing cmd+1.
Now on windows for the same process its kinda confusing.

**Comment by yaira2** [comment]
Does Mac let you choose custom hot keys for tags or do they automatically assign them? What should the hot key be in Files?

**Comment by surya467** [comment]
In mac the default is set to
Cmd + 1, Cmd + 2 and so on

So for windows i think Ctrl + 1, Ctrl +2 and so on should work fine.

Ctrl + 1 for red
Ctrl + 2 for blue... and it continues.

**Comment by yaira2** [comment]
Those shortcuts are for switching tabs, it'll have to be something different.

**Comment by surya467** [comment]
I dont mind if its SHIFT + 1, SHIFT +2  and so on

Or any key that just maybe gives me a tag

like Ctrl + T maybe

**Comment by yaira2** [comment]
That would work, let's see if there are any other suggestions for this.

**Comment by surya467** [comment]
Thank tou so much!!!

**Comment by ferrariofilippo** [comment]
> I dont mind if its SHIFT + 1, SHIFT +2 and so on

I agree with the `shift + number` option. Actually the hotkey doesn't matter since we'll introduce the commands palette.
Anyway, I think that a tag shortcut would improve tags feature since you could apply and remove them quickly.

**Comment by yaira2** [comment]
@ferrariofilippo how to allow users to assign shortcuts? Do we display the tags in the customize shortcut page or do we allow users to customize them directly from the tags page? Maybe both?

**Comment by ferrariofilippo** [comment]
I think all the shortcuts should be together. The link is a good idea 
Are we going to decide which shortcut toggle which tag or will it be a simple `Shift + 1` toggles the first tag and so on?
I would prefer the second option since it would be easier to remember, what do you think?

**Comment by yaira2** [comment]
It can be problematic to auto assign shortcuts here because there is always the chance a user assigned the shortcut to a different action. I think it's best to let the user manually assign the shortcuts for tags.

**Comment by ferrariofilippo** [comment]
That's right, but I didn't mean that.
If we decide that there's a fixed amount of shortcuts for tags (e.g. 5), the first one will toggle the first tag or the user will be able to decide that it toggles, for example, the fifth?

I think we should implement a fixed amount of shortcuts for tags since if the user had like 10 tags it would be a mess for him to manage 10 different shortcuts

**Comment by ferrariofilippo** [comment]
> I don't think we need a hard limit

I disagree, we would need a limit, maybe not too lower but we definitely need a limit. Allowing the user to create as many shortcuts as he wants to will probably require (if possible) a huge refactoring of RichCommands (@cinqmilleans this isn't possible at the moment, am I right?)

**Comment by yaira2** [comment]
Shortcuts will be assigned to actions, I was thinking that we would show an action for each tag and whether a user assigns a shortcut is up to them.

**Comment by ferrariofilippo** [comment]
We will have to replace `CommandCodes` with a string to identify commands then. 
I think we should ask the community before starting to work on this, at least to know how many of them would use this feature with as many shortcuts as they want. I think this will require a lot of work and if it's going to be used by just a couple of people I think it would be a waste to focus on this one instead of other high priorities

**Comment by yaira2** [comment]
Regardless of shortcuts, we need to show tags in the command palette.

**Comment by yaira2** [comment]
@surya467 we're excited to share that we're actively making progress on this feature. Due to the broader nature of this request, we're going to continue tracking it in #15141. You can also subscribe to the linked issue to be notified of further progress.

**Comment by surya467** [comment]
Oh thanks so much!!
