### ISSUE TITLE
Simplify compact mode.

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#11354]
### What feature or improvement do you think would benefit Files?

Simplify compact mode.

The compact mode poses several problems.
1) There is no fundamental difference between a window with reduced size (manually) and compact mode.
2) You can't enter compact mode by minimizing the window, but the result looks like it.
3) The hotkeys are weird (Ctrl+Alt+Up to enter compact mode, Ctrl-Alt-Down to exit it). The reverse would be more logical.
4) There is a third shortcut, listed nowhere, for toggle (F12). This shortcut is buggy because the toggle is always applied twice. This gives a bad visual effect and not the expected result.
5) Concretely, compared to a small window, there are only 2 differences: no settings button and the window cannot be resized. However, the setting menu is now usable with the smallest size. Why do you have to exit compact mode explicitly and not be able to do it by resizing the window?
6) If I leave the window in compact mode, the next open will use the same reduced size but not compact mode.
7) Using a menu, or keyboard shortcut, for compact mode is less intuitive than resizing the window, like for any software or web page.
8) The compact mode, like the reduced size, hides the menu and the search field (accessible by a button). It is very good. On the other hand, the layout does not adapt. For example, the user must manage himself the size of the icons of his layout (LargeIcons or SmallIcons). Large icons are unusable.

I propose to completely remove the compact mode because it is no longer useful. We can keep (and fix) the Toggle command to go from small size to large size. This shortcut is consistent with F11 which toggles the fullscreen. This shortcut can also adapt the layout as needed.

### Requirements

None

### Files Version

2.4.40.0

### Windows Version

10.0.22621.1265

**Comment by yaira2** [comment]
> There is no fundamental difference between a window with reduced size (manually) and compact mode.

The main point of compact overlay is to allow you to overlay the app on top of other Windows. It's working as designed so we're going to keep the behavior as is.

> The hotkeys are weird

We're using these to be consistent with Microsoft Calculator

> There is a third shortcut, listed nowhere, for toggle (F12). This shortcut is buggy because the toggle is always applied twice. This gives a bad visual effect and not the expected result.

This sounds like a bug, feel free to open a separate issue to track it
