### ISSUE TITLE
[Opinion] More customizability / Comparison to QTTabBar

### ISSUE THREAD

**Issue by LinguaOccultus** [files-community/Files#11356]
Hello!

While I used »QTTabBar« (http://qttabbar.wikidot.com - unfortunately no screenshots anymore on the website itself, just google its name for some) as a Windows File Explorer extension, it finally stopped working and its developer is again gone for years already.

On my search for a replacement — which means, something like the original and not a program like all the »commanders« out there — the only one I found is this one. Fine so far.

However, tests shows that this really is what I am looking for but has no even close the customizability like the extension mentioned above. While I do not need just the half of it, some crucial things are missing. Several entries of applications in the context menu, for exmaple. And the custom links are really too close to the also really limited quick access area of the original File Explorer. There not even is a real list view; one has to built one using the details view and hiding columns.

I understand that this project is relatively new and the team is realtively small and that development is a hard business. So, you might take the extension I mentioned and its feature as suggestions for new addition on the one hand.

On the other hand and with the news that Microsoft is working on a new File Explorer theirself, I ask myself where this all leads to. And what the roadmap is for Files under this circumstances. While Files at the moment only is usefull for some users and with new competition from Microsoft, where does this lead to?

Just an opinion on the general status of the situation; no harm meant! ;-)

Greetings from Germany and this grey and rainy day,

Tim

**Comment by Josh-65** [comment]
Thanks for the feedback. Please make a new issue following the issue templates if I have missed any entry's below and for future feedback. It tells you how to fill it out if you don't know what to put for a section.

> Several entries of applications in the context menu

Please make a bug report following the issue template for this and show what entries are missing.

> There not even is a real list view

This is being tracked here #1928
