### ISSUE TITLE
Please add the function of cover selection（请新增封面选择的功能）

### ISSUE THREAD

**Issue by Allen9506** [files-community/Files#11355]
### What feature or improvement do you think would benefit Files?

I hope there can be a function after right-clicking the folder to select pictures supporting jpg format for display as the cover image希望能右键文件夹后可以有一项功能可以选择支持jpg格式的图片作为封面图展示

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

V

### Windows Version

e

### Comments

I hope there can be a function after right-clicking the folder to select pictures supporting jpg format for display as the cover image希望能右键文件夹后可以有一项功能可以选择支持jpg格式的图片作为封面图展示

**Comment by Josh-65** [comment]
This issue doesn't make sense. If your talking about setting a folder icon you can do the following. Right click > Properties > Customization > Browse > select the .icon or .dll file. jpgs can not be support since Windows doesn't allow it. There are online converters for .jpg to .ico

**Comment by yaira2** [comment]
@Allen9506 are you talking about changing album covers? If this is what you mean, we're tracking this in another issue.
