### ISSUE TITLE
GLAAASSSSSSSSSSSSSSSSSSSSS THEEEMEEEEEEE!!!!!!!!!!!!!!!!!!!!!!!! THHEEE GLASS THEME IS REAAAALLLLLLLLL. (trade marked)

### ISSUE THREAD

**Issue by Neglectfull** [files-community/Files#11359]
### Description

As a member of the **glass theme supremacy**.. i am dissapointed to not have a glass theme, i've tried the instructions at--- who the hell cares.com -_- and have found no results... if you could tell me how to get the glass feel back... that would be amazing! if not, that would not b- be amazing.

### Steps To Reproduce

**_this issue should be fixed, By being a sane person :)_**

### Steps to fix

or by doing stuff...

### Files Version

2.4.40.0

### Windows Version

Windows 11 pro, 10.0.22621.1265

### Log file

[debug.log](https://github.com/files-community/Files/files/10775108/debug.log)

**Comment by Josh-65** [comment]
For theming follow the instructions at https://files.community/docs/configuring/custom-themes

**Comment by Neglectfull** [comment]
> For theming follow the instructions at https://files.community/docs/configuring/custom-theme

**open this you numbnut** did you even read.... i said i tried to do that, but it didnt work -_- 


next time learn how to read a paragraph or two!

**Comment by Josh-65** [comment]
You complaining without giving any information and insulting people isn't going to get you anywhere. It's more often going to make others ignore you.

> i've tried the instructions at--- who the hell cares.com

This is not a site and doesn't tell me what you have actually read. So I can only assume that you didn't read from the docs. 

There is a glass theme section that tells you have to enable it. Did you do this if so what the issue? Is it not saving in settings?
Can you screenshot Windows settings > Personalisation > Colours page

**Comment by Neglectfull** [comment]
**WOOOOW**... I READ THE INSTRUCTIONS WHICH I MENTIONED IN THE TEXT... what do you mean it doesnt tell you what i read? isnt it obvious? search up the definition of common sense. Yes  i did it, WHICH EVEN IF YOU DIDNT KNOW AT THE ISSUE YOU OBV KNEW AT THE REPLY! the issue is that it doesnt work.






<img width="737" alt="uuuuhhh" src="https://user-images.githubusercontent.com/123305689/219896417-a4b9c8dc-a5e2-4321-9e9c-87e021b1a908.png">

**Comment by Josh-65** [comment]
Can you send a screenshot of Files

**Comment by Neglectfull** [comment]
yessss can do!
<img width="960" alt="Screenshot 2023-02-18 124048" src="https://user-images.githubusercontent.com/123305689/219898015-a1474099-ea97-4ae2-918d-bd54afd723c0.png"> 

as well as the system files!
<img width="960" alt="Screenshot 2023-02-18 124048" src="https://user-images.githubusercontent.com/123305689/219898621-d984f3e2-f54b-4835-b2d4-1dce5e5e68ff.png">

**Comment by Josh-65** [comment]
It's working fine from based on screenshot

**Comment by Neglectfull** [comment]
maybe- just maybe by eyes are decieving me.. but that does not look like the glass theme (alteast not from the old versions) **THERE IS BARELY ANY BLUR!** It would be a sin to call that "glass theme"

**Comment by Josh-65** [comment]
The original version of it broke. It also had issues see comment https://github.com/files-community/Files/issues/10690#issuecomment-1387225414

**Comment by Neglectfull** [comment]
can you send me the original versions download link.. (you know... that's fully functioning!)

**Comment by Neglectfull** [comment]
may you mention how it broke?

**Comment by Josh-65** [comment]
It broken when going from UWP to WinAppSDK platforms.

You wont get support for this version, It will have many more issues then current versions and wont get feature updates. It may also stop being available in future without notice.
https://github.com/files-community/Files/releases/download/v2.3.12/Files.Package_2.3.12.0_x64_arm64_Sideload.msixbundle

**Comment by Neglectfull** [comment]
oh ok! (‾◡◝)

**Comment by redhotideas** [comment]
it is incredible to create such a beautiful and performing program and not be able to solve an acrylic transparency problem..

**Comment by redhotideas** [comment]
@Josh-65 this is my situation with mica... i can see anything..

![image](https://user-images.githubusercontent.com/118266752/222131463-0b5d5c19-c8aa-4fd4-9866-8c6ce509a770.png)

![image](https://user-images.githubusercontent.com/118266752/222131696-77935b34-9ea0-4644-ba95-10a09c000a63.png)

**Comment by Josh-65** [comment]
This isn't something Files can fix, If Microsoft improved acrylic or made it mica look more like it Files could use that. Did you try the glass one from https://files.community/docs/configuring/custom-themes

**Comment by redhotideas** [comment]
not working...

![image](https://user-images.githubusercontent.com/118266752/222134353-47ba9422-82ae-4870-be10-5e08c6ca87ca.png)

**Comment by Josh-65** [comment]
Thats not the values for the glass theme. If you want it solid color you can use the backgrounds option in the app

**Comment by redhotideas** [comment]
@Josh-65 is really not possible insert a line like this? 

![image](https://user-images.githubusercontent.com/118266752/222194445-f00743c5-36dc-446e-97a4-86df220fffee.png)

**Comment by redhotideas** [comment]
now the situatios is this... not the best

![image](https://user-images.githubusercontent.com/118266752/222194726-b36d367d-c0b8-4f84-953d-31154174b0db.png)

**Comment by yaira2** [comment]
We're excited to share to acrylic will be returning in v2.5.

**Comment by brighr** [comment]
![Screenshot (62)](https://github.com/files-community/Files/assets/153921080/df4b4978-bd31-4293-813d-7fc25528fb2a)
as for me i applied the #00000001 color, i can see it somehow but not really as it should appear. how should i proceed with this issue

**Comment by yaira2** [comment]
@brighr did you change the backdrop to acrylic?
