### ISSUE TITLE
right mouse button menu, I want system default

### ISSUE THREAD

**Issue by binbinLeader** [files-community/Files#11353]
### What feature or improvement do you think would benefit Files?

I hope that the right mouse button can use the system default settings. Can I make an open button?

I hope this: 
![image](https://user-images.githubusercontent.com/31795171/219849582-c52d49b7-68bf-4079-a0be-841af211fcde.png)

not this: 
![image](https://user-images.githubusercontent.com/31795171/219849613-cfb96254-196b-4f64-84fa-e33b2ee6ed43.png)

### Requirements

- This proposal will accomplish next version

### Files Version

2.4.33.0

### Windows Version

Windows 11 专业版 21H2 22000.1574

**Comment by HarkTu** [comment]
Please add setting to make it default, I prefer it despite the delay. Everything I use is in windows context menu.

![Screenshot_19](https://user-images.githubusercontent.com/46054251/219852397-e7e20c1b-82dc-4abe-95b7-cf24e0eef352.png)

Files Version
2.4.33.0

Windows Version
Windows 10

**Comment by hishitetsu** [comment]
How about turning off "Move shell extensions into a sub menu"?
![image](https://user-images.githubusercontent.com/66369541/219863945-0f639b90-1cfb-49cf-868b-8cf84b3859c9.png)

**Comment by binbinLeader** [comment]
> How about turning off "Move shell extensions into a sub menu"? ![image](https://user-images.githubusercontent.com/66369541/219863945-0f639b90-1cfb-49cf-868b-8cf84b3859c9.png)

No, it will get stuck after it is turned off. It is not smooth to use

**Comment by binbinLeader** [comment]
> Please add setting to make it default, I prefer it despite the delay. Everything I use is in windows context menu.

Thank you for your reply

**Comment by Josh-65** [comment]
Are you asking if it possible to use the Windows Explorer context menu? If so its not possible.

**Comment by binbinLeader** [comment]
> Are you asking if it possible to use the Windows Explorer context menu? If so its not possible.

I see. Thank you
