### ISSUE TITLE
RE: THEEEE GLAASSS THEMEEE IS REAAALLL

### ISSUE THREAD

**Issue by Neglectfull** [files-community/Files#11360]
### Description

 #11359 yeah sooo exact same this as mentioned post.

### Steps To Reproduce

 #11359

### Steps to fix

 #11359 just look at that one.

### Files Version

 #11359 just look at that one.

### Windows Version

 #11359 just look at that one.

### Log file

 #11359 just look at that one.

**Comment by Josh-65** [comment]
Don't spam I'm currently wring on the other issue

**Comment by Neglectfull** [comment]
what is your problem Josh-65? start learning how to read a issue before uuhhh i dont know either sennding a comepletly unrelated link, or closing immediately.
