### ISSUE TITLE
Vertical scroll bar jumps around position in list when left mouse click and drag.

### ISSUE THREAD

**Issue by neakmenter** [files-community/Files#11369]
### Description

Vertical scroll bar jumps around position in list when left mouse click and drag.
I click and drag on the vertical scroll bar and, if dragged slowly, the viewed position in the directory will jump to a much lower position then (usually) back up again, multiple times. Very disorientating, as I am dragging slowly to precisely locate a particular file. I've tried is details, tiles and grid views and this behaviour is the same.

### Steps To Reproduce

1. enter a directory with many files
2. left click and drag the vertical scroll bar down and up slowly.
3. observe the described behaviour!

### Steps to fix

ensure vertical scrollbar works correctly when left click and drag (rather than scrollwheel action) is used.

### Files Version

2.4.40.0

### Windows Version

10.0.19045.2604

### Log file

[debug.log](https://github.com/files-community/Files/files/10777871/debug.log)

**Comment by yaira2** [comment]
Can you share a screen recording? You can upload directly to GitHub.

**Comment by yaira2** [comment]
@neakmenter

**Comment by neakmenter** [comment]
Sorry for the delay - busy life! Today I set up for screen recording... and I can't get this to happen again! I guess we can close this? Very sorry to have wasted your time. If it happens again I'll try to get the exact circumstances...

**Comment by yaira2** [comment]
Please let us know if it happenes again.
