### ISSUE TITLE
new file manager for window 10 

### ISSUE THREAD

**Issue by mearyakay** [files-community/Files#11368]
### Description

I tried to open the file again and again but the new file manager is not opening and I get a notification that the automatic file is closed.

### Steps To Reproduce

hhhhhh

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

2.4.33.0

### Windows Version

22H2

### Log file

Edition	Windows 10 Enterprise
Version	22H2
Installed on	‎22-‎01-‎2023
OS build	19045.2604
Experience	Windows Feature Experience Pack 120.2212.4190.0

**Comment by Josh-65** [comment]
Can you check Event view for any errors. Open Files > Type `Event viewer` in the Windows search bar > Windows logs > Application > Check for any error messages (Look at screenshot for what to look for) > Click on any shown > Screenshot the window and upload to GitHub.
![image](https://user-images.githubusercontent.com/26977075/219974891-f7974b12-e204-40cd-a606-f8599ae50537.png)

**Comment by Josh-65** [comment]
You can also attempt to update first from https://files.community/download Select the place you downloaded from.
