### ISSUE TITLE
Move settings `Move shell extensions into a sub menu` into context menu options

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#11361]
### What feature or improvement do you think would benefit Files?

It would make sense to move it into the context menu option since its a context menu setting. The title above it could then be removed also to make it seem less crowded.
![image](https://user-images.githubusercontent.com/26977075/219899754-1669ee43-ef7e-4864-9e23-4bcc4895d9fd.png)

### Requirements

- Remove title `Customise the right click context menu`
- Move 'Move shell extensions into a sub menu' into a sub option of `Context menu options`

### Files Version

2.4.40.0

### Windows Version

10.0.22621.1194

**Comment by yaira2** [comment]
The first group is to turn menu items on or off, so it doesn't really go together. Perhaps it can be renamed to "Context menu items" though.
