### ISSUE TITLE
Bug: Compact row selection background not vertically centered when in Columns Layout

### ISSUE THREAD

**Issue by ChristopherHaws** [files-community/Files#11372]
### Description

When selecting an item while in **Columns Layout** and **Compact Spacing**, the selection background is not vertically centered.
Columns Layout:
![image](https://user-images.githubusercontent.com/5934505/219976472-c4bd1f82-173a-4bed-bd69-e23c36ab5d59.png)

Details Layout:
![image](https://user-images.githubusercontent.com/5934505/219976539-cc864b4a-fd3d-4fc8-b962-1d999c629a03.png)

### Steps To Reproduce

1. Enable **Compact Spacing**
2. Open any folder with items in it
3. Switch to **Columns Layout**
4. Select an item
5. Notice that the selection is not centered

### Steps to fix

- The row selection should match the other layout views

### Files Version

2.4.40.0

### Windows Version

10.0.22621.1265

### Log file

[debug.log](https://github.com/files-community/Files/files/10778060/debug.log)

**Comment by ChristopherHaws** [comment]
I'm not sure if you want me to make a separate issue for this, but I would love it compact mode removed the margin between items and include it as padding in the row selection background instead. The hight of a row is great in compact mode, but the selection highlight looks weird in compact mode.

Here is a comparison of Files vs Explorer:
![image](https://user-images.githubusercontent.com/5934505/219977721-46b0b1bb-8f7c-4d47-b161-68cc118fc8a9.png)
![image](https://user-images.githubusercontent.com/5934505/219977765-d4cb191b-7b14-4fb2-b4d5-395e8ab6a01a.png)
Even explorer has issues with pixels not being aligned... 🙄 

Thanks for this amazing app. It's so much better than the built in File Explorer! :)

**Comment by yaira2** [comment]
That's a good idea, can you open a separate issue for that?

**Comment by rubendejong** [comment]
I'm sorry I have to report this has not been fixed at all, or has a regression. Still looks like this in version 2.5.21.0 on Windows 10.0.22621.2283.

![vqAHnC3EX8](https://github.com/files-community/Files/assets/727249/05c624ea-6a7d-4d24-a584-48e02491c25d)

**Comment by yaira2** [comment]
@rubendejong the fix hasn't been released to stable yet.
