### ISSUE TITLE
Font Size does not match default Windows File Explorer. Too large and looks cluttered.

### ISSUE THREAD

**Issue by pritster5** [files-community/Files#11373]
### Description

The default font size (and I'm not sure if there's a way to change it) is larger than the default font size from Windows File Explorer, leading to UI elements seeming cluttered. On top of that, the text rendering is very alised and not smooth, like in Windows File Explorer.

See below: Left is Windows, Right is Files

![image](https://user-images.githubusercontent.com/7132319/219977467-79ddedd4-31d0-4d0e-adcc-6642d3221767.png)

### Steps To Reproduce

Open the files app and look at any of the text.

### Steps to fix

Changing the default font size to 12pt (as opposed to what looks to be the default of 14pt from the image) would fix this issue.

### Files Version

2.4.40.0

### Windows Version

10.0.22621.1265

### Log file

[debug.log](https://github.com/files-community/Files/files/10778082/debug.log)

**Comment by yaira2** [comment]
Files uses the new XAML styles which are a little different than what File Explorer has today, but you'll start to see File Explorer adopt these as well.

We don't have built-in support for changing the font size but there are options in the Windows Settings app that'll work for not just Files but for all XAML apps.

**Comment by pritster5** [comment]
What about the text rendering? It seems like there is far less aliasing in the default windows File Explorer compared to Files.

**Comment by yaira2** [comment]
Text rendering depends on whatever system XAML and WinUI uses under the hood. We have support for overriding the font (instructions on https://files.community) so you can play around there and see if a different font works better.
