### ISSUE TITLE
Show copying information

### ISSUE THREAD

**Issue by Jazekss** [files-community/Files#11371]
### What feature or improvement do you think would benefit Files?

Copying information (copy process) is not showing anywhere, only like:
`**Copying items** (...) Copying 2 items to D:` (drive letter is for example)

Maybe you can create that copying information is showing somewhere, example in left bottom corner, there is many place to show small area with information about process.

Lower-left corner for example i thing is really correct place

![copying_example](https://user-images.githubusercontent.com/89478349/219975539-41ad0f29-c256-4726-8ce7-b39f49481790.png)

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

Version 2.4.33.0

### Windows Version

Windows 10 Pro N 21h2

**Comment by Josh-65** [comment]
The status centre is the at the top left corner next to settings.

**Comment by Jazekss** [comment]
Yup, i see that, but there is not enough info, than maybe need to add info i shown to this status window, i mean how much copied and time left

**Comment by Josh-65** [comment]
It does show progress as a percentage and to and from locations. Speed is tracked here #11265 and an ETA is pretty much always completely useless and inaccurate so there isn't a point adding that.

**Comment by Jazekss** [comment]
This [#4811](https://github.com/files-community/Files/issues/4811) will be best for me, but if its possible to make that by myself, than i didn't understand how
