### ISSUE TITLE
Bug: Item names of shell extension submenu is not updated

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#11378]
### Description

In File Explorer, the submenu of "Cast to Device" shows "Searching for devices..." first, and then shows devices found.
![スクリーンショット_20230220_135502](https://user-images.githubusercontent.com/66369541/220014658-e33d6fa8-e79c-4d72-bc85-19cd01e9af7f.png)

In Files, the submenu of "Cast to Device" has always shown "Searching for devices..." and is not updated.
![スクリーンショット_20230220_135701](https://user-images.githubusercontent.com/66369541/220014696-2df7859d-fe17-4b33-8cf9-ea02a4fefa1b.png)

But if I select "Searching for devices..." in Files, the same dialog appears as when I select a device in File Explorer.
![スクリーンショット_20230220_135713](https://user-images.githubusercontent.com/66369541/220015098-89c17b39-befc-463e-93e2-325f9b7c3f92.png)

### Steps To Reproduce

1. Right-click the media file to cast.
2. Select "Cast to Device".
3. You see "Searching for devices..." and if you select it, some device is selected even though the device name is not displayed.

### Steps to fix

Item names of shell extension submenu should be updated in real time.

### Files Version

2.4.40.0

### Windows Version

10.0.22621.1265

### Log file

[debug.log](https://github.com/files-community/Files/files/10779898/debug.log)

**Comment by yaira2** [comment]
I have a Bluetooth device connected and it's showing for me.

**Comment by hishitetsu** [comment]
Maybe it happens when it takes a long time to find the device.

**Comment by yaira2** [comment]
I was able to reproduce this as well

**Comment by yaira2** [comment]
The cast to device menu is no longer shown in Files because it was causing some crashes. It's possibly related to this but we don't have plans to bring it back in the near future.
