### ISSUE TITLE
select multiple tags for better search

### ISSUE THREAD

**Issue by houston1337** [files-community/Files#11375]
### What feature or improvement do you think would benefit Files?

for example i have tags
- cats
- dogs
- flowers
- ...

I would like to choose a cat in flowers by choise tags in left menu 

(now it can be done in the search bar by phrase "tag: cats, flowers" , but each time you have to type the phrase manually to search) 

### Requirements

- This proposal will improve searching whis using tags

### Files Version

2.4.40.0

### Windows Version

22h2

**Comment by yaira2** [comment]
You can click a tag in the details layout to search for it, is this what you're looking for?

**Comment by houston1337** [comment]
> You can click a tag in the details layout to search for it, is this what you're looking for?

I think this will make it clearer what I mean: 
![example2](https://user-images.githubusercontent.com/35744830/220091447-6c8fe1b5-6374-48ca-bd0b-2c25cc11c3f2.jpg)

it would be nice if it worked with keypresses ("+" to add a new tag to the search list and "-" to remove it)

**Comment by yaira2** [comment]
We're looking into adding search filters, this isn't going to be ready soon but it's on the roadmap and I think it'll help for this.
![image](https://user-images.githubusercontent.com/39923744/220169541-2a863fb2-4465-4d05-be3f-25279e753afd.png)

**Comment by MalteTasler** [comment]
> We're looking into adding search filters, this isn't going to be ready soon but it's on the roadmap and I think it'll help for this. ![image](https://user-images.githubusercontent.com/39923744/220169541-2a863fb2-4465-4d05-be3f-25279e753afd.png)

That is the related issue btw:
https://github.com/files-community/Files/issues/4813
