### ISSUE TITLE
Cannot open folder via command line args

### ISSUE THREAD

**Issue by philipphock** [files-community/Files#11381]
### Description

Opening a folder using command line args results in NotAFolder error

### Steps To Reproduce

open a terminal
write files c:\

what should happen:
the folder c:\ should be opened

what happens:
a dialog with "NotAFolder" appears

Additional info:
"files" also appears in the adress bar: "files c:\"

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

2.4.40.0

### Windows Version

Win 10 22H2

**Comment by yaira2** [comment]
Please upload the log file

**Comment by yaira2** [comment]
What language is the app set to?

**Comment by hishitetsu** [comment]
@yair100 I can reproduce this using the command prompt. This does not happen in powershell.
It seems that the command I typed at the command prompt itself becomes parameters.

**Comment by Josh65-2201** [comment]
You should replace `files` with `files.exe`

**Comment by hishitetsu** [comment]
I see, but is this not a bug? I think it should start normally without the `.exe`.
