### ISSUE TITLE
WinGet Support for the preview version

### ISSUE THREAD

**Issue by xIUPITERx** [files-community/Files#11380]
### What feature or improvement do you think would benefit Files?

Add support for standalone WinGet packages for the Files (Preview) versions, because the self-updater of the preview version sometimes takes a little longer or cannot be used in the event of a start-up crash.

Since I download files from the Microsoft Store anyway, the Store version is sufficient for me personally, but the Preview version unfortunately has no external updater.

### Requirements

- publish files under FilesCommunity.Files
- publish files preview under FilesCommunity.Files.Preview

### Files Version

2.4.40

### Windows Version

Windows 11 Pro

**Comment by yaira2** [comment]
The preview version updates automatically, opening the app will automatically check for updates and display a notice on the toolbar when one is available.

**Comment by xIUPITERx** [comment]
Yes, but I have the problem (issue is about to be uploaded) that the preview version doesn't even start.
So even if you patch it, I would have to go to the website and download it from there instead of `winget upgrade --all`

**Comment by yaira2** [comment]
We already have a WinGet version for the stable app, would you like to open a PR on the WinGet repo adding the preview version?

**Comment by Josh-65** [comment]
One issue with it is the version number has to be updated for a new version or Winget will not update as a newer version already installed.

**Comment by yaira2** [comment]
@xIUPITERx are you willing to maintain the WinGet package for the preview version?

**Comment by xIUPITERx** [comment]
How complicated would it be?

**Comment by yaira2** [comment]
You'd have to submit an updated package to the WinGet repo about once a week to keep it up to date.

**Comment by Josh-65** [comment]
Properly you would just have to change the version number in the manifest files on the WinGet repo witch can be done from GitHub file edit feature

**Comment by xIUPITERx** [comment]
I'll have a look at it, but it might take a while because it's a bit stressful IRL.

**Comment by yaira2** [comment]
Closing for now but happy to help if you have any questions.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/files-community/Files/issues/11380#issuecomment-1437132690

I've filed https://github.com/microsoft/winget-pkgs/issues/166364#issue-2450869495.
