### ISSUE TITLE
Bug: Deleting a missing file recent files widget crashes app

### ISSUE THREAD

**Issue by Unpuertomex** [files-community/Files#11384]
### Description

If you have a file name listed in the Files List that is no longer available and you try to remove it from the file list it crashed the program. There are no issues when deleting a file that is still active.

### Steps To Reproduce

1. Remove a file that is showing on the File List
2. Right click on it 
3. Wait  few seconds
4.  The program will close

### Steps to fix

Fix crash that occurs when removing a listed file that is no longer available.

### Files Version

2.4.40.0

### Windows Version

Windows 11 10.0.22623.1325

### Log file

[debug.log](https://github.com/files-community/Files/files/10788779/debug.log)

**Comment by yaira2** [comment]
Is this in a network location?

**Comment by yaira2** [comment]
Deleted files are supposed to be removed automatically, but there is an issue in some locations where this isn't working.

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by yaira2** [comment]
@Unpuertomex this doesn't appear to be an issue in v2.4.66 but please let us know if it still happens for you after updating.
