### ISSUE TITLE
Can't select topmost item in shell extensions context menu

### ISSUE THREAD

**Issue by octochamp** [files-community/Files#11397]
### Description

In both Files Preview 2.4.41.0 and in current stable build 2.4.40, when right-clicking an item and selecting "Show more options...", the uppermost item can't be highlighted or selected. It seems to occur when the context menu is large enough that the uppermost item overlaps the title bar. If there are enough files in the window (or the shell extensions submenu does not contain many items) and the submenu doesn't overlap the top of the Files window, the uppermost item works fine.

In the below, "Convert to Adobe PDF" can't be selected
![image](https://user-images.githubusercontent.com/49677546/220353706-24f0d044-e537-4b1b-a886-6e5560522411.png)

In this case, where the item is below the title bar, "Convert to Adobe PDF" can be selected with no issues
![image](https://user-images.githubusercontent.com/49677546/220355416-e8e5f9ff-8f56-4269-8886-a07246843401.png)

### Steps To Reproduce

1. Right-click the topmost file inside a folder
2. Click "Show more options..."
3. If there are enough items in the submenu to overlap the title bar at the top of the Files window, try to select the topmost item

### Steps to fix

Settings > Preferences > Turn OFF "Move shell extensions into a sub menu"
This causes all the shell extensions to populate the bottom of the list (rather than creating a submenu which overlaps the title bar) and can be selected. However this slows down using the right-click context menu.

### Files Version

2.4.41.0

### Windows Version

Windows 11 Pro Version 22H2 22621.1265

### Log file

[debug.log](https://github.com/files-community/Files/files/10793902/debug.log)

**Comment by Josh-65** [comment]
Merging with #10823
