### ISSUE TITLE
Tags arbeitet nicht korrekt

### ISSUE THREAD

**Issue by zubler-egliswil** [files-community/Files#11394]
### Description

Beim Klick unter Einstellungen -> Tags fällt das Programm aus.
Ebenso bei einem simplen rechtsklick im Explorer Fenster.
Bekanntes Problem?
Ich arbeite mir Windows 10 Pro x64 22H2
Betriebssystembuild 19045.2604
Windows Feature Experience Pack 120.2212.4190.0

Danke für die Hilfe.
Freundlichen Gruss Dani

### Steps To Reproduce

Beim Klick unter Einstellungen -> Tags fällt das Programm aus.
Ebenso bei einem simplen rechtsklick im Explorer Fenster.

### Steps to fix

keine Ahnung

### Files Version

2.4.40.0

### Windows Version

10.0.19045.2604

### Log file

[debug.log](https://github.com/files-community/Files/files/10792291/debug.log)

**Comment by ferrariofilippo** [comment]
Thank you for the report. I'll look into this, hopefully I can fix these bugs for the next version (context-menu bug is easy-to-fix, not sure about settings tab)

**Comment by ferrariofilippo** [comment]
Can you upload `filetags.json`? You can find it under `settings` when you click `Open Log Location`.
I want to check if there's somwthing wrong with that.

**Comment by yaira2** [comment]
Merging with #11400
