### ISSUE TITLE
cant resize preview pane

### ISSUE THREAD

**Issue by bnbagiz** [files-community/Files#11395]
Hi i am using Version 2.4.40.0 on the windows version 10.0.19045.2604 

i can not resize the preview pane

**Comment by ferrariofilippo** [comment]
It will be fixed in the next version. 
Actually, you can resize it, but the cursor won't change

**Comment by bnbagiz** [comment]
> It will be fixed in the next version. Actually, you can resize it, but the cursor won't change @Josh-65 can you close this one?

Oh, im sorry.. my fault. it really works!

**Comment by bnbagiz** [comment]
> It will be fixed in the next version. Actually, you can resize it, but the cursor won't change @Josh-65 can you close this one?

but it seems like it doesn preview the whole pdf, is that correct? in only shows me couple pages of a pfd file i want to scroll through in the preview pane
