### ISSUE TITLE
Offline installer

### ISSUE THREAD

**Issue by AlexandreMarkus** [files-community/Files#11396]
### What feature or improvement do you think would benefit Files?

I would like to have an offline installer of Files

### Requirements

- The installer should be able to do the installation without internet connection 

### Files Version

Latest

### Windows Version

Windows 10

**Comment by Josh-65** [comment]
All stable releases will have an offline file here
https://github.com/files-community/Files/releases

**Comment by AlexandreMarkus** [comment]
> All stable releases will have an offline file here
> https://github.com/files-community/Files/releases

I did download the Files.Stables.exe file and here is the result of the installation on a Windows 10 pc with no internet access 

![PXL_20230221_152359757.jpg](https://user-images.githubusercontent.com/59664238/220386532-30ea59f8-64b1-400c-9aaf-4c96feb21f06.jpg)

**Comment by Josh-65** [comment]
That file isn't listed on there. There is a .msixbundle for it

**Comment by flappysquirrel** [comment]
I'm unable to access any .msixbundle files from the releases. 

Have they been removed?

**Comment by Josh65-2201** [comment]
It has since been removed as there was issues on how to get the dependencies for it. It's being looked into and there will documentation on Files site when it available. https://files.community/docs
