### ISSUE TITLE
Progress for file operations

### ISSUE THREAD

**Issue by duke7553** [files-community/Files#114]
Display a dialog box that provides the status of the operation.

**Comment by yaichenbaum** [comment]
The current implementation looks great, the only change I would recommend is adding a way to cancel the operation.

**Comment by szaimen** [comment]
@yaichenbaum Do you have screenshots of the current implementation? :)

**Comment by yaichenbaum** [comment]
This is the one for deleting items but its the same for paste.
![image](https://user-images.githubusercontent.com/39923744/70870603-3fc01e00-1f63-11ea-8312-72bd4ee41058.png)

**Comment by szaimen** [comment]
Thanks, nice to see!

**Comment by duke7553** [comment]
@szaimen Are there any improvements to this flyout you want to see?

**Comment by szaimen** [comment]
@duke7553 I have thought about this and a way to cancel the operation like @yair100 suggested, sounds like a good idea to start with.

Maybe you could also think about adding:
- a way to pause the operation and resume it
- visually show that an operation is happening on the icon in the taskbar
- a popup view, independent from the window (so that you don't accidentally close the window while an operation is happening) or just disallow closing the window if an operation is still hapening (and inform the user, that this is the case)
- some animations and stats with the current speed, estimated time, how many items/folders are left, what is the target directory and source directory ... ?
- adding all operations to the same popup, so that you have one view for all operations?

**Comment by lorisobi** [comment]
Maybe don't make it as annoying as in the classic file explorer, maybe place it in the corner 

![FileTransfer](https://user-images.githubusercontent.com/28399150/80915989-19eeb680-8d56-11ea-9182-472d27808a2b.jpg)


in my **concept** I did 2 different coloured versions.

it could be realized with _WinUI ListView for Messaging or Data Logging_

**Comment by yaichenbaum** [comment]
@lorisobi I was thinking about something similar to this, except in the top right corner.

**Comment by lampenlampen** [comment]
Most apps display notification in the bottom right corner, so i would stay with it.

We also need some way of hiding them and then some "notification center".

**Comment by lampenlampen** [comment]
I think we only need to display at most one notification (for the current folder).
If the user navigates away or initiate a second, the first should hide itself. 

And i would take not the colored version.

**Comment by yaichenbaum** [comment]
@lampenlampen I was thinking of something similar to how it works in Ubuntu. It would probably be a dropdown where you can see the progress.

**Comment by lampenlampen** [comment]
😂 i never in my life saw a linux ui.

**Comment by lorisobi** [comment]
I can not remember how this looks

**Comment by lorisobi** [comment]
> Most apps display notification in the bottom right corner, so i would stay with it.
> 
> We also need some way of hiding them and then some "notification center".

I think this would be fine for power users but probably annoying for (possible) normal users

**Comment by lampenlampen** [comment]
I would think, it is the other way.

The powerusers wants to have all there operations in eye contact.

The normal user starts one operation and either wait til it ends or, if he does some other work, forgets about it and if he want's to check he can have a look into the "notification center".

**Comment by lorisobi** [comment]
i think a normal user doesn't want many options

**Comment by lampenlampen** [comment]
What do you mean with options?

I would only display the newest operation for the current folder with a hide button.
And all operations are listed in the "notification center".

So if the user navigates away from the folder the notification hides, because he clearly is not interested anymore in the operation. He want's to do some other work now.
And if he want's to check the operation, he can look into the notification center.

**Comment by lukeblevins** [comment]
@yair100 I like the idea of adding this as an icon to the new bottom bar. I'll work on a mockup soon based on the image above.

**Comment by yaichenbaum** [comment]
@duke7553 I was actually thinking about putting it in the top right corner.

**Comment by tsvietOK** [comment]
@duke7553 @yaichenbaum May be we can use Flayout to display progress
![image](https://user-images.githubusercontent.com/20501502/80931521-088fc380-8dc3-11ea-93a5-8df56d7a1371.png)

**Comment by duke7553** [comment]
@tsvietOK My mockups will certainly reflect this.

@yaichenbaum imo the top is somewhat crowded, so I think the bottom right corner would look better. I'll have my mockup done very soon so we can compare them.

**Comment by yaichenbaum** [comment]
There is a actually a new WinUI control that is being designed that will allow for notifications throughout the app, I think we should wait to see if this will do what we want.

**Comment by lorisobi** [comment]
> @tsvietOK My mockups will certainly reflect this.
> 
> @yaichenbaum imo the top is somewhat crowded, so I think the bottom right corner would look better. I'll have my mockup done very soon so we can compare them.

![FileTransfer3](https://user-images.githubusercontent.com/28399150/80937791-dab47a00-8dd6-11ea-9c1e-177d0840380f.jpg)


I also did a new design concept (maybe the selection which panes schould be show could also be done with a single button and a selection menu flyout)

**Comment by lorisobi** [comment]
> There is a actually a new WinUI control that is being designed that will allow for notifications throughout the app, I think we should wait to see if this will do what we want.

You mean this one? 
![image](https://user-images.githubusercontent.com/28399150/80937860-0c2d4580-8dd7-11ea-9416-0d44b68b20b5.png)

**Comment by lorisobi** [comment]
> > @tsvietOK My mockups will certainly reflect this.
> > 
> > @yaichenbaum imo the top is somewhat crowded, so I think the bottom right corner would look better. I'll have my mockup done very soon so we can compare them.
> 
> ![FileTransfer3](https://user-images.githubusercontent.com/28399150/80937791-dab47a00-8dd6-11ea-9c1e-177d0840380f.jpg)
> 
> 
> I also did a new design concept (maybe the selection which panes schould be show could also be done with a single button and a selection menu flyout)

maybe this could also be grouped into delete, transfer, copy and for onedrive upload anf download

**Comment by yaichenbaum** [comment]
@lorisobi I was actually talking about this proposal https://github.com/microsoft/microsoft-ui-xaml/issues/913.
If we don't want to wait for that I would suggest using the action center in Windows 10 as opposed to recreating the functionality ourselves.

**Comment by yaichenbaum** [comment]
> May be we can use Flayout to display progress

@tsvietOK I think the flyout would be great for the "action center" if we did create one, however I don't think we should go that route since we can use the built in action center in Windows 10 or the status control from WinUI whenever it's ready.

**Comment by lampenlampen** [comment]
I would also go with the system action center. The operations are global and not tied to 1 instance of files. Especially with multiple instances of files it will get difficult, because i would expect to find all operations in all "notification centers".

**Comment by duke7553** [comment]
@lampenlampen We'll keep this in mind

**Comment by yaichenbaum** [comment]
![image](https://user-images.githubusercontent.com/39923744/84732524-f1b7c180-af69-11ea-84d3-913c562952b5.png)

This a basic mockup I put together to help bring the concepts and ideas in this issue together.

**Comment by lorisobi** [comment]
maybe when the notification view is collapsed an little accent colour indicator should show up at the Notifications Icon if there is an active process.

**Comment by generalguy41** [comment]
Will this be persistent across tabs? As in if I start a large transfer from one tab, and navigate to another, will I still be able to see the dialog? I think it would be nice so you don't have to search through a number of tabs to find the one where the work was done. Might also be nice to maybe make the tab flash or something once it's complete if you're on another tab?

**Comment by lorisobi** [comment]
![image](https://user-images.githubusercontent.com/28399150/84775661-c7a0e680-afdf-11ea-9aad-a8c747d087f8.png)
 maybe like this

**Comment by yaichenbaum** [comment]
@generalguy41 It should definitely work across tabs, if the user tries closing the program when an operation is in progress, there should be a confirmation dialog.

@lorisobi We can technically do that but in general that causes the UI to get a bit crowded, file transfer operation's should be done in the background and leave no distraction to the users. Perhaps we can have a notification in the bottom right of the app when a file transfer application operation has been completed.

**Comment by duke7553** [comment]
Hi everyone.

We can't commit to a deadline on this feature, but things are looking good for it's development. So, I thought I'd share a screenshot of the 1st stage's working prototype. It goes without saying, you don't want to checkout the branch this is being built on unless you're a developer.

![image](https://user-images.githubusercontent.com/20365014/85218408-0c25dc80-b368-11ea-9181-e9e3c9ff679c.png)

**Comment by lampenlampen** [comment]
Are the operations synced across instances?

**Comment by yaichenbaum** [comment]
@lampenlampen Unfortunately the only way to do that would be to keep running the operation in the background when the user "closes" the app. What we can do instead is notify the user if they try closing the app when a task is running.

**Comment by yaichenbaum** [comment]
An important function to include is support for resolving conflicts when transferring files.

**Comment by d2dyno1** [comment]
> Hi everyone.
> 
> We can't commit to a deadline on this feature, but things are looking good for it's development. So, I thought I'd share a screenshot of the 1st stage's working prototype. It goes without saying, you don't want to checkout the branch this is being built on unless you're a developer.
> 
> ![image](https://user-images.githubusercontent.com/20365014/85218408-0c25dc80-b368-11ea-9181-e9e3c9ff679c.png)

Maybe show a progressbar just next to the notifications button to show the progress of operations (Only when the notifications are hidden)

**Comment by R3voA3** [comment]
> @lorisobi I was actually talking about this proposal [microsoft/microsoft-ui-xaml#913](https://github.com/microsoft/microsoft-ui-xaml/issues/913).
> If we don't want to wait for that I would suggest using the action center in Windows 10 as opposed to recreating the functionality ourselves.

I think the action center is a good idea. Don't need to reinvent the wheel for now.

**Comment by duke7553** [comment]
More updates on the StatusCenter UI:

<img width="814" alt="Capture" src="https://user-images.githubusercontent.com/20365014/88693743-a72f7600-d0cd-11ea-86c9-99261f7eb675.PNG">
<img width="814" alt="Capture2" src="https://user-images.githubusercontent.com/20365014/88693745-a72f7600-d0cd-11ea-88fa-19984f916e09.PNG">

Under the hood, things aren't as great. We really need to take a good look at improving the reliability of these operations when multitasking with different tabs. If anyone wants to work on this with me, please let me know and I'll assign you to #632

**Comment by duke7553** [comment]
### Feedback Opportunity:

We're working on improving both the progress UI and reliability of Storage Item operations based on your feedback. 

![image](https://user-images.githubusercontent.com/20365014/92851104-3614fb00-f3bb-11ea-88d1-f1afd85ccfd8.png)
Recently, we decided to add a new banner to the StatusCenter saying "Operation Complete" if a storage item recycle/delete/paste operation takes longer than ten seconds. Does this sound right?

Also, as we improve the reliability of the operations we're inviting everyone here to try out the latest Store preview (which doesn't have the new UI yet) and provide feedback on potential edge cases you find with running long storage item operations. 

For instance, does the app crash when starting an operation and changing tabs? The more information you provide us, the better. Please post crash information you collect in #632 and status center UI design ideas in this issue.

Over the next few weeks, we'll improve the concept of "expanded" status banners which have action buttons on them like "Try again" and "Cancel".

**Comment by lorisobi** [comment]
Have you thought about a clear all button next to the "Ongoing Tasks" Heading or about a swipe control for the operations to cancle or delete?

**Comment by yaichenbaum** [comment]
Thank you for sharing all your feedback. This feature is now available in Files! Please open new issues if you have any additional feedback.
