### ISSUE TITLE
Portable version

### ISSUE THREAD

**Issue by DiscoveryOV** [files-community/Files#11403]
### What feature or improvement do you think would benefit Files?

It would be great if releases could include a portable version of this app, if that's even possible. I would like to use it in a toolbox of sorts which requires running the application on-demand without the ability to install it. (perfect for Backstage mode in ConnectWise Control/ScreenConnect)

### Requirements

- Ideally, there would be a "portable" version of the app available for download here on GitHub and on the main website.
- This portable version would be self-contained, and be executable directly from mostly anywhere on a system.

### Files Version

n/a

### Windows Version

Windows 10/11

**Comment by yaira2** [comment]
Thank you for your feedback, a portable version isn't being planned right now (also, WinAppSdk doesn't have good support for publishing a single exe).

**Comment by Kreijstal** [comment]
you can still publish a portable in the way you let the user download a (compressed) directory with all the depenendencies already on it, just like (portable) inkscape does it. cant you not?

**Comment by hez2010** [comment]
Some features of Files require the app identity to exist, so unfortunately we are not able to make an unpackaged portable version.
