### ISSUE TITLE
 Hope to increase the real-time progress pop-up window with copy (paste delete) function

### ISSUE THREAD

**Issue by zhinailuoli** [files-community/Files#11412]
### What feature or improvement do you think would benefit Files?

The current version can only display copy reminders, but it cannot display the detailed reasons for errors, nor can it display the copy progress and copy speed, so it is impossible to confirm whether the task has been completed. Please add a function similar to the pop-up window below

Preferably I would also like to add the option to customize the background image
![image](https://user-images.githubusercontent.com/107562312/220678253-c890b190-1c9b-4a99-992b-c01bea6bc06b.png)

### Requirements

The current version can only display copy reminders, but it cannot display the detailed reasons for errors, nor can it display the copy progress and copy speed, so it is impossible to confirm whether the task has been completed. Please add a function similar to the pop-up window below

Preferably I would also like to add the option to customize the background image

### Files Version

2.4.40.0

### Windows Version

windows 11 22623.1325

**Comment by yaira2** [comment]
We're tracking this in #11265. The status center should already display if a task completed or failed but hopefully the transfer progress will make it better.
