### ISSUE TITLE
Bug: Network folder error - Android Cellphone

### ISSUE THREAD

**Issue by kennysc** [files-community/Files#11413]
### Description

I am unable to access the files on my cellphone (Samsung S10), the folders Internal storage and SD card are visible, but when I click on them I get an error " Network folder error".
![Capture d’écran 2023-02-22 104843](https://user-images.githubusercontent.com/69609193/220677653-52fb6088-4a3c-48b9-ab4b-c9e4828873dd.png)

### Steps To Reproduce

1. Plug Cellphone to computer
2. Authorize file transfert on the cellphone
3. Navigate to the cellphone "Drive" in Files
4. click on either Internal storage or SD card

### Steps to fix

- Unable to fix it

### Files Version

Version: 2.4.40.0 OS Version: 10.0.22000.1574

### Windows Version

Windows 11 21H2 22000.1574

### Log file

[debug.log](https://github.com/files-community/Files/files/10806024/debug.log)

**Comment by yaira2** [comment]
@kennysc thank you for the report, this will be fixed in the next release.
