### ISSUE TITLE
Feature: Remove the vertical margin between compact rows

### ISSUE THREAD

**Issue by ChristopherHaws** [files-community/Files#11422]
### What feature or improvement do you think would benefit Files?

I would love it if the margin between items was removed when in compact mode. The current row height is great in compact mode, but the selection highlight looks weird, especially when multiple items are selected.

### Requirements

- The height of a compact row should not change
- The padding should be removed between compact rows
- The hover/selection background height should be increased to make it the full height of the row

### Files Version

2.4.40.0

### Windows Version

10.0.22621.1265

### Comments

Here is a comparison of Files vs Explorer:
![image](https://user-images.githubusercontent.com/5934505/219977721-46b0b1bb-8f7c-4d47-b161-68cc118fc8a9.png)
![image](https://user-images.githubusercontent.com/5934505/219977765-d4cb191b-7b14-4fb2-b4d5-395e8ab6a01a.png)
Even explorer has alignment issues... 😆 

Here is how compact vs normal mode looks on OneDrive.com which also uses the new WinUI design:
**Normal:**
![image](https://user-images.githubusercontent.com/5934505/219978844-e0592166-7df2-4cca-a85b-d736a62865c7.png)

**Compact:**
![image](https://user-images.githubusercontent.com/5934505/219978874-d2d8176b-7b92-41b9-8cee-6e01841111aa.png)

Original comment: https://github.com/files-community/Files/issues/11372#issuecomment-1436108821

Thanks for this amazing app. It's so much better than the built in File Explorer! ^_^

**Comment by yaira2** [comment]
> All four corners of the row should have rounded corners
If the row above is also selected, the top corners should no longer be rounded
If the row below is also selected, the bottom corners should no longer be rounded

This is out of scope, we can change the margin but the rounded corners is too much.

**Comment by ChristopherHaws** [comment]
@Josh65-2201 That does look like they are asking for the same change, yes.
