### ISSUE TITLE
Settings crashed

### ISSUE THREAD

**Issue by AleMello** [files-community/Files#11429]
### Description

I was trying to remove Tags widget, but as soon as I open Files app it crashes.

### Steps To Reproduce

Open Files
crash

### Steps to fix

- Fix crash that occurs when I open the app after I turned Tags on on Settings
- Correct action happens when opening the app

https://user-images.githubusercontent.com/4070249/220896432-442e6e2b-ac16-470a-a384-3a4afb630449.mp4

### Files Version

2.4.40

### Windows Version

22H2 22621.1265

### Log file

[debug.log](https://github.com/files-community/Files/files/10813170/debug.log)

**Comment by yaira2** [comment]
Can you try resetting the app?

**Comment by AleMello** [comment]
I restarted my computer and the error still persists.

[image: image.png]

Is there a way to reset it without opening the app?

*Alê Mello*
--

**Comment by yaira2** [comment]
You can reset like this
1. Right click Files icon in the start menu
2. Click App Settings
3. Click reset

**Comment by AleMello** [comment]
Thanks! Now it's ok. Do you want me to repeat what caused the error before? I can do that and record the screen, if it helps...

AlêMello









On Thursday, 23 de February de 2023 13:26:25 (-03:00), Yair wrote:



You can reset like this

Right click Files icon in the start menu
Click App Settings
Click reset

**Comment by yaira2** [comment]
Yes, please try to reproduce the issue again.

**Comment by AleMello** [comment]
Now it's working. I follow the same steps than before, but didn't crash this time.

https://user-images.githubusercontent.com/4070249/221016788-3de447fa-68ff-49e6-b8da-b31886c5f4bc.mp4

**Comment by yaira2** [comment]
Let us know if it happens again
