### ISSUE TITLE
Google drive sync icons is bigger than in windows explorer

### ISSUE THREAD

**Issue by soredake** [files-community/Files#11428]
### Description

Google drive sync icons is bigger than in windows explorer.

### Steps To Reproduce

1. Have google drive installed.
2. Go to google drive folder.
3. Compare sync icons in files preview and windows explorer.

### Steps to fix

Make icons size same as in windows explorer.

### Files Version

2.4.44.0

### Windows Version

Windows 11 Pro 10.0.22621.1265

### Log file

[debug_fulltrust.log](https://github.com/files-community/Files/files/10812676/debug_fulltrust.log)

**Comment by yaira2** [comment]
Merging with #10493
