### ISSUE TITLE
selected files show without scrolling 

### ISSUE THREAD

**Issue by XXABOM7MDXX505** [files-community/Files#11420]
### What feature or improvement do you think would benefit Files?

well, I am not sure if it a called a feature, but when you open a file from other programs like FDM (free download manager) obviously Files will open and auto-select it BUT I have to scroll up or down god knows! 

### Requirements

- nothing really just make the auto-select from other apps show and no need for scrolling like how MS file explorer behaves.

### Files Version

2.4.40.0

### Windows Version

10.0.22621.1265

**Comment by yaira2** [comment]
Merging with #6382
