### ISSUE TITLE
Transparency Controll 

### ISSUE THREAD

**Issue by twinowls** [files-community/Files#11435]
### What feature or improvement do you think would benefit Files?

1. It would be nice to have the transparency control over the main window.
2. It would be nice to have the icon size control of the left hand side folder menu.
3. It would be nice to have an easy method to pay a subscription fee or one time payment in order to support the development of this product.

Otherwise Files is just beautiful. Thank you :-)

### Requirements

- This proposal will accomplish easier utilization for people with eyes problems

### Files Version

V. 2.4.44.0

### Windows Version

Windows 11 Home 10.0.22621

### Comments

Awesome product!

**Comment by yaira2** [comment]
> It would be nice to have the transparency control over the main window.

This isn't supported in WinAppSdk but we'll look into adding support if it becomes available.

> It would be nice to have the icon size control of the left hand side folder menu.

A similar request recently came in, we're tracking this in #11370

> It would be nice to have an easy method to pay a subscription fee or one time payment in order to support the development of this product.

The best way to support the project is to purchase the app on the Microsoft Store, but you can also sponsor us through GitHub. Thank you for the feedback 🙂

**Comment by twinowls** [comment]
The best way to support the project is to purchase the app on the Microsoft Store, but you can also sponsor us through GitHub. Thank you for the feedback 🙂

 <<< I've tried purchase it on MS Store but no luck. The process gets broken somehow for some reason.
On 2/23/2023 7:33:39 PM, Yair ***@***.***> wrote:
It would be nice to have the transparency control over the main window.
This isn't supported in WinAppSdk but we'll look into adding support if it becomes available.
It would be nice to have the icon size control of the left hand side folder menu.
A similar request recently came in, we're tracking this in #11370 [https://github.com/files-community/Files/issues/11370]
It would be nice to have an easy method to pay a subscription fee or one time payment in order to support the development of this product.
The best way to support the project is to purchase the app on the Microsoft Store, but you can also sponsor us through GitHub. Thank you for the feedback 🙂
