### ISSUE TITLE
Keep the drive status expanded

### ISSUE THREAD

**Issue by inhobook** [files-community/Files#11431]
### What feature or improvement do you think would benefit Files?

It's used a lot，so i wish to add the ability to keep the drive status expanded

### Requirements

It's used a lot，so i wish to add the ability to keep the drive status expanded

### Files Version

Version:2.4.40.0

### Windows Version

Windows 10 企业版 LTSC 21H2 10.0.19044.1379

### Comments

It's used a lot，so i wish to add the ability to keep the drive status expanded

**Comment by Josh-65** [comment]
What drive status? Were is it located?

**Comment by inhobook** [comment]
I see this feature







------------------ 原始邮件 ------------------
发件人:                                                                                                                        "files-community/Files"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月23日(星期四) 晚上9:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [files-community/Files] Keep the drive status expanded (Issue #11431)





 
What drive status? Were is it located?

**Comment by Josh-65** [comment]
That doesn't answer the questions. If you added an image you have to do it through GitHub and not an email

**Comment by yaira2** [comment]
Are you talking about the status column in OneDrive?
