### ISSUE TITLE
Provide tighter spacing options for visual elements

### ISSUE THREAD

**Issue by stamminator** [files-community/Files#1143]
**Is your feature request related to a problem? Please describe.**
The app is beautiful, but has too much padding and spacing for the average non-touch user.

**Describe the solution you'd like**
In addition to #737, it would be helpful to have tighter spacing options (and potentially smaller font size options) available in the settings.

**Describe alternatives you've considered**
I don't know if there's such a thing as per-app display scaling in Windows 10, but if there is, providing a slider to the end user so that every visual element could be reasonably scaled up or down might work as well.

**Additional context**
[Here is a demo of this feature in action in Windows 10's default Mail app.](https://security101-my.sharepoint.com/:v:/p/jstamm/EXIqd-J0rsNOqNJR1IH_XrcBjgpOfMvFS0lm--AHuwMRiQ?e=mKozIc)

**Comment by yaichenbaum** [comment]
@stamminator Thank you for your feedback, this is something we are working on and there is already a draft pull request #900.

**Comment by yaichenbaum** [comment]
Merging with #3009.
