### ISSUE TITLE
Bug: Opening file picker as admin will cause crash (WinAppSdk issue)

### ISSUE THREAD

**Issue by Spyromaniac31** [files-community/Files#11440]
### Description

When Files is run as administrator, the app crashes when clicking on the Browse button to change a folder icon. This happens regardless of whether the folder needs admin privileges to be edited, and doesn't happen when Files isn't run as administrator.

### Steps To Reproduce

1. Run Files as administrator, either from the Start Menu or the Taskbar.
2. Right-click on any folder
3. Select the Properties icon
4. Select Customize
5. Select Browse
6. The app crashes

### Steps to fix

- Fix crash that occurs when clicking browse. The button should open the same File Explorer window as it does when Files isn't run as administrator.

### Files Version

Version: 2.4.40.0 OS Version: 10.0.25300.1000

### Windows Version

Edition	Windows 11 Home Insider Preview Version	22H2 Installed on	‎2/‎15/‎2023 OS build	25300.1000 Experience	Windows Feature Experience Pack 1000.25300.1000.0

### Log file

[debug.log](https://github.com/files-community/Files/files/10817106/debug.log)

**Comment by yaira2** [comment]
This is actually an issue in WinAppSdk where trying to open the file picker as admin will cause a crash. They have some workarounds we can try.

**Comment by meilluer** [comment]
> This is actually an issue in WinAppSdk where trying to open the file picker as admin will cause a crash. They have some workarounds we can try.

can you explain those workarounds?

**Comment by yaira2** [comment]
https://github.com/microsoft/WindowsAppSDK/issues/2504

**Comment by carlosvsilva** [comment]
Also Files should prompt to elevate permissions when pasting a file on a directory needing admin rights (Like C:\Program Files\) like Win Explorer, otherwise nothing happens and feels like a bug to the user.

**Comment by jatinsihag234** [comment]
i wanna work on this issue

**Comment by Josh-65** [comment]
> Also Files should prompt to elevate permissions when pasting a file on a directory needing admin rights (Like C:\Program Files) like Win Explorer, otherwise nothing happens and feels like a bug to the user.

This is a known issue tracked at #10422. Please don't add irrelevant comments or report other bugs in other issues.

**Comment by carlosvsilva** [comment]
I didn't know that core functionality is irrelevant, all right then.

**Comment by yaira2** [comment]
> i wanna work on this issue

Thank you, let me know if you have any questions.

**Comment by yaira2** [comment]
> Also Files should prompt to elevate permissions when pasting a file on a directory needing admin rights (Like C:\Program Files) like Win Explorer, otherwise nothing happens and feels like a bug to the user.

@carlosvsilva Fully agree, this is a separate issue. It's a little challenging with WinAppSdk but we should at least display a prompt so that the user knows why it's not working.

**Comment by ghost** [comment]
@yair100  Thank you, Sir. I'm working on that . If you could give me some advice on where to begin, I'd appreciate that.

**Comment by yaira2** [comment]
@jatinsihag234 are you still working on this issue?

**Comment by 0x5bfa** [comment]
They seem to have documented the workaround in MSDN a year ago.
https://github.com/MicrosoftDocs/winrt-api/commit/4f599eb91be47212a5196ae1975498f60dcf49b5
We can start working on using this workaround seeing if this fixed.

**Comment by 0x5bfa** [comment]
A potential fix is in the PR.

**Comment by yaira2** [comment]
This issue will be resolved in the next release.
