### ISSUE TITLE
Code Quality: Delete unused string resources

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#11446]
### Description

I have investigated unused string resources by using this tool.
https://github.com/RandomEngy/RESX-Unused-Finder

Attached file is a list of resources that are candidates for deletion.
[candidates.txt](https://github.com/files-community/Files/files/10820520/candidates.txt)

They do not appear to be referenced directly but may be referenced indirectly via variables.
I will submit a PR once I have confirmed the use or non-use of these.

### Concerned code

Resources.resw

### Gains

Only resources that are being used can be retained.

**Comment by yaira2** [comment]
I was wondering if there was a tool for this! There are quite a few in that list that are used in the details pane and properties window.

**Comment by yaira2** [comment]
Another thing that will reduce work for translators is to merge duplicate strings.

**Comment by hishitetsu** [comment]
I think so too. But I want to remove unused resources first. There may still be some that are being used, so I will look into this a bit more.
