### ISSUE TITLE
Improve the right-click context menu in the tags widget

### ISSUE THREAD

**Issue by hecksmosis** [files-community/Files#11457]
### What feature or improvement do you think would benefit Files?

The right click context menu for tag items currently only has shell items, we should add Open With, Open in new tab/window/pane, etc. when applicable.

### Requirements

- Add more items to right-click context menu in tags widget

### Files Version

2.4.40.0

### Windows Version

Windows 11 21H2

**Comment by hecksmosis** [comment]
I am currently working on this myself, just wanted to open this issue to keep track of it

**Comment by yaira2** [comment]
Good call, should basically support whatever the other widgets have.

Could also add an option to remove the tag.

**Comment by hecksmosis** [comment]
Ok
