### ISSUE TITLE
The application was not what I saw in the video

### ISSUE THREAD

**Issue by Dandiniko** [files-community/Files#11458]
### What feature or improvement do you think would benefit Files?

After seeing the files app in a youtube video, I bought the app from the microsoft store, but in the customization section, there was no glass mode that I saw in the video, but instead there were a few lousy customization modes.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.4.40.0

### Windows Version

Windows 11

### Comments

![Ekran görüntüsü 2023-02-24 231503](https://user-images.githubusercontent.com/126287498/221282399-8ef60fc0-9760-4adc-842d-a2338607c3bb.png)

**Comment by Josh-65** [comment]
The video you watch is old version. The videos are also not official made by Files.
For theming follow the instructions at https://files.community/docs/configuring/custom-themes

**Comment by yaira2** [comment]
In particular, see the instructions for the "glass theme".
