### ISSUE TITLE
Always use one layout view for files, regardless of content.

### ISSUE THREAD

**Issue by andyfmidd** [files-community/Files#11465]
### What feature or improvement do you think would benefit Files?

I like "Details" view in layout. Always. The unpredictability of the other layouts is unhelpful (its slower to scan rows than to scan columns), as well as lack of details, e.g. date, file size. My choice, I know. (Its the first thing I change in a new Windows  installation)

So add an option to "fix" the view, with a selection of preferred view.

Maybe a "default" option in the Layout selection (the three little squares icon).

### Requirements

Amend the UI to permit a selection. Check for this choice at point of display.

### Files Version

Version: 2.4.40

### Windows Version

Windows 11 Pro 22H2 22621.1265

### Comments

Windows Explorer gets this wrong: it does not properly apply to every folder, even when that choice is made (e.g. new USB devices).
(It is possible I missed this option in the various menus :( )

**Comment by hecksmosis** [comment]
I think this is already implemented in Settings > Folders > Sync layout and sorting preferences across directories
