### ISSUE TITLE
Feature: ISO file handling is too complex

### ISSUE THREAD

**Issue by carlosvsilva** [files-community/Files#11466]
### Description

Double clicking or opening a ISO file fails to mount a normal virtual drive (i think Files tries to "decompress" the entire ISO in the background?) .

Trying to click on the context menu top line (Mount ISO) doesn't highlight it when pointing the mouse at it, ONLY when that option touches the top of the screen and is on top of Files title bar.

After mounting it, the iso mounts ok.

When ejecting the virtual drive of the ISO, Files issues an unwarranted warning of "ready to remove device safely" when it's a read only ISO in a virtual drive, nothing should be displayed after ejecting.

At the end, the virtual drive that mounted the ISO, after being ejected, the empty virtual drive lingers around and accumulates with other ejected ISOs stale drives.  

### Steps To Reproduce

1. Double click ISO file (nothing fast happens, no virtual drive is mounted)
2. Right click ISO file, go to "More options" and try to click "Mount" but if that line is placed too high on the screen, it can't be highlighted nor clicked.
3. After successfully mounting ISO, ejecting it will trigger a wrong message to remove device safely.
4. After ejecting it, the stale empty virtual drive will linger around Files drive list on the left side.

### Steps to fix

- Keep it simple, same behaviour as Win Explorer
- Default to mount ISO in a virtual drive with double clicking/Enter to open the ISO file.
- Show the virtual drive with the ISO contents after mounting it.
- Eject silently and remove the stale empty virtual drive from the drives list in the left sidebar.

### Files Version

2.4.40.0

### Windows Version

Win11 22H2 10.0.22621.1265 up2date

### Log file

![Cant select top right click option line](https://user-images.githubusercontent.com/40889421/221368995-7f7da9d0-ca75-4665-b409-1d7d29c58074.png)
![wrong message for isos](https://user-images.githubusercontent.com/40889421/221368996-715523ae-a285-4aa7-abfc-c11daff3d049.png)
![eject iso](https://user-images.githubusercontent.com/40889421/221368997-1346ac10-1a5f-4385-a034-b08f301a2d12.png)
![leftover drive after ejecting iso](https://user-images.githubusercontent.com/40889421/221368998-5210405f-e675-4871-96a7-3052c361f15e.png)
[debug.log](https://github.com/files-community/Files/files/10831736/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/10831737/debug_fulltrust.log)

**Comment by Josh-65** [comment]
Files uses 7zip to view the ISO. The title bar issue is known and tracked in #10823

**Comment by Josh-65** [comment]
Is the issue just with unmounting an ISO file not working?

**Comment by carlosvsilva** [comment]
ISOs and similar files are huge Volumes, as full BlueRay discs or massive contents, it's impossible to unzip each ISO opened by the user. Straight mounting as a virtual drive like Win Explorer is the clear way to go I think.

My only comment above, reports the many Files issues facing users who work with ISO files. Each of them improves Files and the user experience by removing extras that do not apply to ISO volumes, only to USB keys and the like.

The last issue reported is about the leftover virtual drive that should not be there after ejecting it.

**Comment by yaira2** [comment]
> Double clicking or opening a ISO file fails to mount a normal virtual drive (i think Files tries to "decompress" the entire ISO in the background?) .

To mount an ISO file, you need to right click and use the "mount" option. Double clicking or using the open option will allow you to view the ISO file without extracting it.

**Comment by yaira2** [comment]
Opening the iso isn't the same as mounting it, if we changed the behavior to automatically mount it there wouldn't be a way to open the file to see the contents (aside from mounting it).

**Comment by yaira2** [comment]
@carlosvsilva thank you for your feedback, this issue will be addressed in the next release.
