### ISSUE TITLE
Code Quality: Delete duplicate string resources

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#11462]
### Description

Having deleted unused string resources, the next step is to delete duplicates.
The attached is duplicate strings.
[Duplicates.txt](https://github.com/files-community/Files/files/10830337/Duplicates.txt)

I will check if these duplicate strings should be one and submit a PR when done.

### Concerned code

Resources.resw

### Gains

Reduce the workload during translation.

**Comment by yaira2** [comment]
We should prioritize the generic resource names as opposed to the more specific ones like `BaseLayout.Text`.

**Comment by hishitetsu** [comment]
Yes, I will do so. However, there are some codes that depend on key names, such as `CloudDriveSyncStatus_` for example, so I will leave such codes as they are.
