### ISSUE TITLE
Improve Tags Home widget

### ISSUE THREAD

**Issue by carlosvsilva** [files-community/Files#11467]
### What feature or improvement do you think would benefit Files?

Please replace the string "View more" in Tags Home widget, with a GUI element like '...' otherwise it is confusing to mix readable content like "View more" which looks and feels like a users personal file, with other information.
Replace "View more" with just '...' 

I would also really enjoy being able to move around each file from one tag group to another with the mouse pointer, like a Kanban board, to update progress on work on each file.

The toolbar where copy/paste icons are, needs another icon to assign a tag to the current selected file.

See annotated screenshot below. 

### Requirements

- Drag and drop files in Tags widget.
- New icon in toolbar

### Files Version

2.4.40.0

### Windows Version

Win11 22H2 10.0.22621.1265 up2date

### Comments

![Tags Home](https://user-images.githubusercontent.com/40889421/221369985-512ff7bc-b186-4d50-a9a3-d1f10db5ebf1.png)

**Comment by yaira2** [comment]
Can you please open separate feature requests so we can track each request individually?
