### ISSUE TITLE
Feature: Quick switch

### ISSUE THREAD

**Issue by Grreg-fr** [files-community/Files#11478]
### What feature or improvement do you think would benefit Files?

It would be nice to have a functionnality that open the current opened folder in an Open/Save dialog, like with this utility (https://github.com/gepruts/QuickSwitch) or with Listary's Quick Switch (or simply a compatibility with theses tools).

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.4.40.0

### Windows Version

10.0.19044.1566

**Comment by yaira2** [comment]
Like an option in the context menu?

**Comment by Grreg-fr** [comment]
More like an automatic function: with Quick Switch, you just have to get the focus on an opened explorer window and the file dialog sets you instantly to that folder.
A little like hitting Ctrl + Shift + C and pasting it in the file dialog, but quicker (and without the need of an extra keyboard shortcut).
It's the only functionnality missing in Files for me

**Comment by yaira2** [comment]
How do the other file managers handle it:
1. Is there a shortcut or does it automatically set the location to the focused location?
2. What if there are multiple windows open?

**Comment by Grreg-fr** [comment]
When the file dialog of an application is opened (Photoshop for example), you just need to get the focus on the opened explorer window (by clicking in it or via Alt + Tab). When back to Photoshop, the file dialog is now set in the right folder.

And when multiple windows/tabs are opened, the last one in focus is used.
There is also a keybord shortcut to do this action.

**Comment by yaira2** [comment]
Can you request this feature on the repo you linked?

**Comment by Grreg-fr** [comment]
I'll dot that, but as I don't know how it works, I thought maybe it could be done by Files side?

Anyway, thanks for you very quick response!

**Comment by yaira2** [comment]
I think it's best for an existing tool to add support since they've done this before.

**Comment by yaira2** [comment]
@Grreg-fr we're happy to work Listary on an integration if they are interested, but it's not something we plan do on our own.

**Comment by yaira2** [comment]
Support for Listary is actively being worked on in #15069.

**Comment by Grreg-fr** [comment]
Thank you for the update !

I don't know how to make it work though. Is there a guide on how to install
the listary plug-in for non developers like me?

Thank for your help.


[image: twitter] <https://twitter.com/grreg_fr>
[image: linkedin] <https://www.linkedin.com/in/gregoirestern/>
[image: instagram] <https://www.instagram.com/gregstern_fr/>
Greg Stern

Motion designer
+33673038527
***@***.***
https://bento.me/gregstern

**Comment by 0x5bfa** [comment]
Here's the guideline published by Listary dev.

https://github.com/listary/Listary.FileAppPlugin/blob/master/docs/Getting%20Started.md

**Comment by Grreg-fr** [comment]
Thanks. That's way too complicated for me, and I'll wait for it's simple
integration in the next Files updates, but with this feature I will
certainly go back to use it again in my daily tasks!

Thanks for your effort!



[image: twitter] <https://twitter.com/grreg_fr>
[image: linkedin] <https://www.linkedin.com/in/gregoirestern/>
[image: instagram] <https://www.instagram.com/gregstern_fr/>
Greg Stern

Motion designer
+33673038527
***@***.***
https://bento.me/gregstern

**Comment by yaira2** [comment]
@Grreg-fr its still in the development phase but we wanted to let you know that the integration is being worked on.
