### ISSUE TITLE
Feature: Replace See More string in Tags Home widget with a right facing chevron

### ISSUE THREAD

**Issue by carlosvsilva** [files-community/Files#11473]
### What feature or improvement do you think would benefit Files?

Please replace the string "View more" in Tags Home widget, with a GUI element like '...' otherwise it is confusing to mix readable content like "View more" which looks and feels like a users personal file, with other information.
Replace "View more" with just '...'

### Requirements

- Replace See More string in Tags Home widget with a right facing chevron in the container hader

### Files Version

2.4.40.0

### Windows Version

Win11 22H2 10.0.22621.1265 

### Comments

![Tags Home See More](https://user-images.githubusercontent.com/40889421/221411251-a05be1d3-d045-4874-b927-e698388f68c7.png)

**Comment by yaira2** [comment]
Do you mean it's a little crowded?

**Comment by Jay-o-Way** [comment]
Sometimes text is more informative than a few dots. I think current situation is good. Also think about accessibility 🥸

**Comment by yaira2** [comment]
What are your thoughts and adding a chevron to the container header?
![image](https://user-images.githubusercontent.com/39923744/228857996-f726aa73-8553-42c8-af3e-e0e1b860626f.png)

**Comment by Jay-o-Way** [comment]
> Chevron looks like the right answer to me.

That's also a possibility, just I would place it in the same place as the word is.
