### ISSUE TITLE
Bug: Option to pin/unpin recycle bin is missing from context menu

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#11479]
### Description

The right click menu in Recycle Bin is missing the options to pin/unpin it from favorites.

### Steps To Reproduce

1. Open recycle bin
2. Right click in a blank space
3. See that it's missing options

### Steps to fix

- Display the correct options

### Files Version

v2.4.45

### Windows Version

Windows 11

### Log file

NA

**Comment by hecksmosis** [comment]
This is not an issue in 2.4.40

**Comment by yaira2** [comment]
It's a recent change (due to rich commands)

**Comment by hecksmosis** [comment]
This has been fixed (albeit unintentionally) with #11492

**Comment by yaira2** [comment]
@hecksmosis they show up now but do the commands work for you?
