### ISSUE TITLE
Feature: Reduce shortcut icon overlay

### ISSUE THREAD

**Issue by carlosvsilva** [files-community/Files#11488]
### What feature or improvement do you think would benefit Files?

- in Files, the shortcut overlay covers nearly 1/6 of the full icon, with older style arrows.
- in MS Explorer, the shortcut overlay is about half the size of the same graphic in Files, and is further out of the way of the file icon.

Please see screenshot of the same scene in MS Explorer:

### Requirements

- This proposal will ensure icon overlays don't cover too much of the main icon and are aestheticaly pleasing like all of Files.

### Files Version

2.4.40.0

### Windows Version

Win11 22H2 10.0.22621.1265 

### Comments
Files
![Files](https://user-images.githubusercontent.com/40889421/221372998-bb1742af-9895-4e5d-bb67-1d39e764f5fa.png)

Microsoft Explorer
![Windows Explorer](https://user-images.githubusercontent.com/40889421/221407790-ffb3f2af-99cd-4efa-8083-b2c14a6f216d.png)

**Comment by yaira2** [comment]
I'm working on updating the overlay icons so this is perfect timing.
