### ISSUE TITLE
List View

### ISSUE THREAD

**Issue by Fa310tx** [files-community/Files#11485]
### What feature or improvement do you think would benefit Files?

List view is something that has been a part of Microsoft's File Explorer for many years.
Many other file managers also have it.
I will point out that some other file managers use a left-to-right and then top-to-bottom format for their List view while Microsoft's uses a top-to-bottom and then left-to-right format.
Personally, I think Microsoft's way is better.

### Requirements

Adding another layout option

### Files Version

2.4.40.0

### Windows Version

10.0.19045.2604

### Comments

Thanks for making a modern file manager, given that Microsoft doesn't seem to interested in it.

**Comment by yaira2** [comment]
Merging with #2509

**Comment by yaira2** [comment]
@Fa310tx thank you for your patience, I'm excited to share that a List View layout will be included in the next release.
