### ISSUE TITLE
Drag the folder to the tab bar

### ISSUE THREAD

**Issue by xmha97** [files-community/Files#11482]
### What feature or improvement do you think would benefit Files?

Hi, please add the feature below:
- Drag the folder to the tab bar
![image](https://user-images.githubusercontent.com/23485114/221442907-49e3c3e4-c0c7-4f4f-a9db-cbf43c75ea6f.png)

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.4.40.0

### Windows Version

WIndows 11 22H2 22621.1265

**Comment by yaira2** [comment]
To open a new tag?

**Comment by xmha97** [comment]
> To open a new tab?

Yes

**Comment by yaira2** [comment]
Thanks! We're tracking this in another issue #4710. Make sure to subscribe to the issue so that you're notified about any changes.
