### ISSUE TITLE
Expand Navigation Pane

### ISSUE THREAD

**Issue by Fa310tx** [files-community/Files#11486]
### What feature or improvement do you think would benefit Files?

It would be nice to allow drives to expand on the navigation pane.
It's a feature that Microsoft's File Explorer has had for many years.

### Requirements

An option to always expand

### Files Version

2.4.40.0

### Windows Version

10.0.19045.2604

### Comments

Microsoft's File Explorer automatically expands the navigation pane when double-clicking on a directory in the view pane, when the option is enabled.
Personally, I like that functionality.

**Comment by yaira2** [comment]
Column view is a similar idea but we're also planning a tree view layout. Merging with #1928

**Comment by yair100** [comment]
@Fa310tx Tree View is currently available in preview https://files.community/download. It will be included in the next stable release.
