### ISSUE TITLE
"files C:/" shortcut doesn't work anymore

### ISSUE THREAD

**Issue by cid-wings** [files-community/Files#11491]
### Description

Hi before I was use to do this 
`files C:/`
to open a drive with files from my steam deck or windows shortcut 
but now i got this from files
Drive files C:\
![image](https://user-images.githubusercontent.com/30216355/221631748-0dc73345-3ff4-4a39-80d7-6cfebf68030d.png)
or i get this 
![image](https://user-images.githubusercontent.com/30216355/221631944-b2981b1e-dace-4d01-89cc-39826e6198fa.png)

### Steps To Reproduce

steam deck create a shortcut with the program  file/app line "files C:\"

use windows right click create a shortcut "files C:\"

windows R "files C:\"

### Steps to fix

don't know 

### Files Version

2.4.40.0

### Windows Version

10.0.19045.2604

### Log file

[debug.log](https://github.com/files-community/Files/files/10842229/debug.log)

**Comment by yaira2** [comment]
Is this an issue in the preview version?

**Comment by cid-wings** [comment]
> Try changing `files` to `files.exe`

this work fine lol thank you so simple ^^

**Comment by cid-wings** [comment]
> Is this an issue in the preview version?

nope I dont remember wich one was working without the exe it was before the blur/acrylic effect was removed from files
