### ISSUE TITLE
Notification "Something went wrong" often appears when  right-clicking a file

### ISSUE THREAD

**Issue by OscarPutz14** [files-community/Files#11490]
### Description

Notification "Something went wrong" appears most times right-clicking a file in the explorer. The context menu appears, and the app keeps working, but it's still annoying. I tried to identify the problem by trying on different file formats (tried .MTS, .mp4, .jpg) and other drives, but it seems to happen in completely random folders...
![42-27-23-174224](https://user-images.githubusercontent.com/91553409/221625409-d7e95f01-b701-4537-b4ff-1a693e38ce14.png)

### Steps To Reproduce

1. open files
2. right-click some files
3. maybe you'll have the same issue

### Steps to fix

-fix crash that occurs when right-clicking files
- Correct action happens when clicking on some other file

### Files Version

Edition	Windows 11 Home Version	22H2 Installed on	‎14/‎05/‎2022 OS build	22623.1325 Experience	Windows Feature Experience Pack 1000.22639.1000.0

### Windows Version

Edition	Windows 11 Home Version	22H2 Installed on	‎14/‎05/‎2022 OS build	22623.1325 Experience	Windows Feature Experience Pack 1000.22639.1000.0

### Log file

[debug.log](https://github.com/files-community/Files/files/10841966/debug.log)

**Comment by yaira2** [comment]
Can you try the preview build?

**Comment by FreeHK-Lunity** [comment]
same issue with release build, preview fixed it

**Comment by yaira2** [comment]
Thought so, you can thank @hishitetsu for fixing this one 🙂
