### ISSUE TITLE
Opening %appdata% from the address bar crashed Files

### ISSUE THREAD

**Issue by carlosvsilva** [files-community/Files#11499]
### Description

Opening `%appdata%` from the address bar crashed Files

### Steps To Reproduce

1. Click address path bar
2. write `%appdata%`
3. press enter

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

2.4.40.0

### Windows Version

Win11 22H2 10.0.22621.1265

### Log file

`
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
 <System>
  <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" /> 
  <EventID>1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8000000000000000</Keywords> 
  <TimeCreated SystemTime="2023-02-28T11:17:05.2942677Z" /> 
  <EventRecordID>62162</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="21372" ThreadID="5972" /> 
  <Channel>Application</Channel> 
  <Computer>Prestige</Computer> 
  <Security UserID="S-1-5-21-2841299184-1499438901-2616519421-1001" /> 
  </System>
 <EventData>
  <Data Name="AppName">Files.exe</Data> 
  <Data Name="AppVersion">1.0.0.0</Data> 
  <Data Name="AppTimeStamp">63c9df9f</Data> 
  <Data Name="ModuleName">Microsoft.UI.Xaml.dll</Data> 
  <Data Name="ModuleVersion">3.0.0.2302</Data> 
  <Data Name="ModuleTimeStamp">93c3ada5</Data> 
  <Data Name="ExceptionCode">c000027b</Data> 
  <Data Name="FaultingOffset">00000000007cd8bc</Data> 
  <Data Name="ProcessId">0xc40</Data> 
  <Data Name="ProcessCreationTime">0x1d94b662b6d3adc</Data> 
  <Data Name="AppPath">C:\Program Files\WindowsApps\49306atecsolution.FilesUWP_2.4.40.0_x64__et10x9a9vyk8t\Files.App\Files.exe</Data> 
  <Data Name="ModulePath">C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.2_2000.777.2143.0_x64__8wekyb3d8bbwe\Microsoft.UI.Xaml.dll</Data> 
  <Data Name="IntegratorReportId">5aadcf24-68d5-4612-ad5e-7bbddc67e656</Data> 
  <Data Name="PackageFullName">49306atecsolution.FilesUWP_2.4.40.0_x64__et10x9a9vyk8t</Data> 
  <Data Name="PackageRelativeAppId">App</Data> 
 </EventData>
</Event>
`

**Comment by Josh-65** [comment]
Can you please upload the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.

**Comment by yaira2** [comment]
Was this the columns layout?

**Comment by yaira2** [comment]
Can you try the latest preview version?

**Comment by yaira2** [comment]
Did you get a chance to check? There isn't a definite fix because I can't reproduce the issue but there have been some changes that might help.

**Comment by yaira2** [comment]
@carlosvsilva

**Comment by yaira2** [comment]
@carlosvsilva I still haven't been able to reproduce this issue and I had a couple other users test as well. If it's still an issue in v2.4.66, please let us know and upload the log file.
