### ISSUE TITLE
Bug: Tags will disappear after renaming the file

### ISSUE THREAD

**Issue by Skelbti** [files-community/Files#11503]
### Description

I've tag many files (~100) with multiple tags. When I rename some files after tagging them, the files is sorted in relation to its new name but all his tags have been deleted.

### Steps To Reproduce

1. Tags a large number of files ;
2. Rename some files ;
3. See that some files lost their tags ;

### Steps to fix

- All tags should be permanent ;
- Unlimited number of tags ;

### Files Version

2.4.40.0

### Windows Version

Windows 11 22H2 22621.1265

### Log file

[debug.log](https://github.com/files-community/Files/files/10853578/debug.log)

**Comment by yaira2** [comment]
Is the tag actually being removed or if you refresh the directory does it come back? Is this specific to certain file types?

**Comment by yaira2** [comment]
Are you renaming the files in Sibelius or in Files?

**Comment by yaira2** [comment]
@Skelbti tags only work on drives formatted as NTFS, can you confirm if this is the case?

**Comment by yaira2** [comment]
@Skelbti
