### ISSUE TITLE
Bug: Confirm delete takes a long time to show

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#11501]
### Description

The delete confirmation dialog sometimes takes a while until it pops up.

### Steps To Reproduce

1. Select a large folder or file
2. Delete the item using the delete key or toolbar icon
3. See that it takes a while for the delete confirmation dialog to pop up

### Steps to fix

- Display the confirmation prompt right away

### Files Version

v2.4.45

### Windows Version

Windows 11

### Log file

NA

**Comment by hishitetsu** [comment]
How large of a file does this happen? I tried it with a 45 GB VHD file and the dialog appeared in an instant.

**Comment by yaira2** [comment]
Happens with smaller files too, maybe it's only when multiple items are selected.

**Comment by hishitetsu** [comment]
I tried it with 2907 photos totaling 36.4 GB. Still, the dialog appeared immediately.

**Comment by yaira2** [comment]
I can't reproduce this anymore

**Comment by ferrariofilippo** [comment]
I think this is still a bug (See #12008).
It seems this happens with random folders and files (it does not depend on size)

**Comment by itsWindows11** [comment]
Couldn't reproduce this on my end, dialog appears instantly even with many items selected and different sizes.

**Comment by ferrariofilippo** [comment]
It happens randomly to me. Sometimes the dialogs pop ups instantly and sometimes it won't show (trying to delete the same folder)

**Comment by hishitetsu** [comment]
Could this be a file system issue rather than Files? Files accesses the file system to see if the recycle bin is available before displaying the dialog, so the process may stop there if the file system is busy,

**Comment by yaira2** [comment]
> Files accesses the file system to see if the recycle bin is available

What do you mean by available? We should probably show the dialog with a progress ring.

**Comment by hishitetsu** [comment]
> What do you mean by available?

I mean whether the file will be put in the trash or forced to be permanently deleted.

> Can we show the dialog with a progress ring?

That could be a solution.

**Comment by hishitetsu** [comment]
> That could be a solution.

Ah, but when the dialog is set to show only for permanent deletion, it is unclear whether the dialog should show or not until checking if the file can put in the trash.

**Comment by yaira2** [comment]
It doesn't look like there is an easy solution for this 😬

**Comment by ferrariofilippo** [comment]
I don't think that is caused by the access to the recycle bin. Everytime this bug happens to me, clicking on a different folder or on `Back`, will show the popup. It seems like the poup is blocked there but the layout update unlocks it
