### ISSUE TITLE
Tag widget not retaining files 

### ISSUE THREAD

**Issue by Nirav1633** [files-community/Files#11506]
### Description

Files/folders tagged from online shared drives  have to be navigated to in order to show up in the tags widget once computer is disconnected, reconnected to share drives 

### Steps To Reproduce

1. tag a file/folder that exists in an online share drive 
2. Navigate to tags widget to confirm tagged item is in widget 
3. disconnect computer from network/vpn
4. reconnect PC to network/vpn
5. navigate to tag widget 
6. tagged files/folders do not surface in widget
7. navigate to location where file/folder is tagged
8. go back to home page look under tag widget
9. tagged file/folder appears in widget 

### Steps to fix

Navigate to tagged folder location
file/folder resurfaces in tag widget 

### Files Version

2.4.40.0

### Windows Version

Windows 11 22h2 update

### Log file

[debug.log](https://github.com/files-community/Files/files/10855734/debug.log)

**Comment by yaira2** [comment]
@d2dyno1 any recommendations here?

**Comment by yaira2** [comment]
@Nirav1633 is the online drive formatted as NTFS?

**Comment by Nirav1633** [comment]
Correct, all share drives are NTFS format

**Comment by Josh65-2201** [comment]
It may be the case that Windows doesn't attempt to reconnect the drive until you open it. As such the files will never be loaded.

**Comment by yaira2** [comment]
We're tracking this issue in #13502.
