### ISSUE TITLE
Bug: Navigating Network Folders in Location Bar causes error

### ISSUE THREAD

**Issue by hawkerm** [files-community/Files#11508]
### Description

Trying to navigate back in a network drive folder by clicking a parent folder in the application bar:

![image](https://user-images.githubusercontent.com/8959496/222055865-b097a8e7-da22-4bbb-ad9c-94bc49db7279.png)

But get error message instead:

![image](https://user-images.githubusercontent.com/8959496/222055488-4aaaded1-7c87-4456-87c7-54e28c68bca7.png)

If I back out and re-navigate to the location it works fine.

### Steps To Reproduce

1. Go to a network drive folder.
2. Open up and navigate within a sub-folder or two depth
3. Click in the navigation address bar one of the parent folders

### Steps to fix

- Display network folder at the given location without error dialog

### Files Version

Preview 2.4.48.0

### Windows Version

Windows 10 - 21H2 19044.2604

### Log file

Don't see anything related to networking here, but here it is: [debug.log](https://github.com/files-community/Files/files/10857519/debug.log)

**Comment by yaira2** [comment]
We fixed part of this in #11414 but looks like we missed something.

**Comment by hawkerm** [comment]
Yeah, it's weird as well, as I have to like click back elsewhere to some other local folder or the 'Network' folder and then re-enter the address to get back. If I just try and use the addressbar and hit enter on the same exact path it won't reload either.

**Comment by hishitetsu** [comment]
This seems to be a different bug than #11414. I will investigate further and submit a PR when I figure out how to fix it.
