### ISSUE TITLE
Bug: Tag directories do not display all corresponding files

### ISSUE THREAD

**Issue by Skelbti** [files-community/Files#11505]
### Description

After tagging many files (90+) with the same label, when I click on the corresponding label folder all tagged files do not appear.

### Steps To Reproduce

1. Tags a large number of files ;
2. Open the corresponding tag folder ;
3. Press Ctrl + A to select all files ;
4. See the diffrence between the total and selected files ;

![image](https://user-images.githubusercontent.com/86026713/221997965-c2ef6d0a-7b50-4348-bd77-e9b20b81b66b.png)

### Steps to fix

- All tagged files should be present in the corresponding folder ;

### Files Version

2.4.40.0

### Windows Version

Windows 11 22H2 22621.1265

### Log file

[debug.log](https://github.com/files-community/Files/files/10855368/debug.log)

**Comment by yaira2** [comment]
What happens if you turn on the setting to include unindexed items in search results (settings > preferences)?

**Comment by yaira2** [comment]
Are you clicking the tag in the sidebar?

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by yaira2** [comment]
We can't repro this in the preview version but if you're still able to repro the issue, please let us know and we'll take another look.
