### ISSUE TITLE
Search does not work with shortcut name (no problem while searching for folder)

### ISSUE THREAD

**Issue by ibbala** [files-community/Files#11512]
### Description

Search does not work with shortcut name (no problem while searching for folder)

### Steps To Reproduce

1. Go to a folder which has shortcuts
2. Use a shortcut name to search
3. It produces no outcomes
For instance, if a folder has a shortcut named "somename," a search for "somename" returns nothing.

### Steps to fix

Shortcuts are included in search results

### Files Version

Version: 2.4.40.0 OS Version: 10.0.22621.1265

### Windows Version

Windows 11 Pro 22H2 Edition 22621.1265 

### Log file

[debug.log](https://github.com/files-community/Files/files/10859046/debug.log)

**Comment by Josh-65** [comment]
Do you have Files settings > preference >Include unindexed items in search results enabled?

**Comment by ibbala** [comment]
ther is

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by ibbala** [comment]
Yes, it works with this version. Thank you very much for your time.
