### ISSUE TITLE
Feature: Open archives from the home page in the same tab

### ISSUE THREAD

**Issue by manfromarce** [files-community/Files#11517]
### What feature or improvement do you think would benefit Files?

Files usually opens supported archives (Zip, 7z, ...) in the same tab even if they are associated with Windows Explorer.
However, opening them from Recents in the home page launches a new Files instance or Windows Explorer.

### Requirements

- This proposal will make open supported archives listed in Home in the same tab

### Files Version

Version: 2.4.40

### Windows Version

Windows 11 22H2 22621.1344

**Comment by pomydoro** [comment]
Hi, just to let everybody know and help prevent duplicate efforts, I am working on this issue.
