### ISSUE TITLE
Bug: Incorrect Aperture values are shown for photos

### ISSUE THREAD

**Issue by Thane5** [files-community/Files#11516]
### Description

This app displays incorrect aperture values. 
For example, sometimes 8 is displayed as 6, and other times 2.8 is displayed as 3 or even 2,9708536585365852.

### Steps To Reproduce

Select a picture file with EXIF data. Right click on it, go to properties/details or open the "preview" panel. Look for the "Aperture" number.

### Steps to fix

Fix the displayed value to be accurate

### Files Version

2.4.40.0

### Windows Version

Windows 11 22h2 (10.0.22621.1265)

### Log file

[debug.log](https://github.com/files-community/Files/files/10861082/debug.log)

**Comment by Josh-65** [comment]
Does it show it correctly in Windows File explorer?

**Comment by Thane5** [comment]
Yes, it does. 
![image](https://user-images.githubusercontent.com/13683581/222144187-89031052-5c84-49c6-b36c-594541256449.png)
