### ISSUE TITLE
Smooth scrolling blurry - Option to disable it? 

### ISSUE THREAD

**Issue by anoderay** [files-community/Files#11510]
Especially in Detail view I find smooth scrolling very irritating. With only one "click" of mousewheel-rotation it seems reasonably smooth if a bit slow but when scrolling with a bit more oomph the filenames get kinda blurry and it feels jittery. I much prefer the way Win10 and Win11 File Explorers just scroll line by line to a jittery and blurry smooth scrolling.

**Comment by yaira2** [comment]
We don't have plans to allow disabling smooth scrolling.
