### ISSUE TITLE
Files semi freezes up and doesn't show drives as well as shell right click menu

### ISSUE THREAD

**Issue by simplebunsen** [files-community/Files#11514]
### Description

There was some sort of glitch or crash and when files got back, the issues in the title cropped up. Those persisted through full restarts of the files app via taskmanager. Also right clicking in some folders full freezes the manager now.

`2023-02-21 12:52:49.2966|WARN|ParseLinkAsync|Error HRESULT E_FAIL has been returned from a call to a COM component.
	System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at Vanara.PInvoke.Shell32.IShellLinkW.Resolve(HWND hwnd, SLR_FLAGS fFlags)
   at Vanara.Windows.Shell.ShellLink.LoadAndResolve(String linkFile, SLR_FLAGS resolveFlags, HWND hWin, UInt16 timeOut)
   at Vanara.Windows.Shell.ShellLink..ctor(String linkFile, LinkResolution resolveFlags, HWND window, TimeSpan timeOut)
   at Files.App.Helpers.FileOperationsHelpers.ParseLinkAsync(String linkPath)
`
and so on (see debug file)

### Steps To Reproduce

Sorry it suddenly happened, no steps available

### Steps to fix

haven't been able to fix it.

### Files Version

2.4.40.0

### Windows Version

Windows 10 Pro 22H2

### Log file

[debug.log](https://github.com/files-community/Files/files/10860554/debug.log)

**Comment by Josh-65** [comment]
Can you try the preview version https://files.community/download

**Comment by simplebunsen** [comment]
I'm going to try it but the issue appears semi randomly so not sure how fast I could get it again.

Also a full system restart fixed / reset it for now...

**Comment by yaira2** [comment]
We're working on improvements so very likely it's resolved in the preview version.
