### ISSUE TITLE
Feautre: Add "open with" in action bar

### ISSUE THREAD

**Issue by raminmjj** [files-community/Files#11513]
### What feature or improvement do you think would benefit Files?

The benefit of this feature is, no need to right-click on the selected file(s).

### Requirements

same as windows 10 file explorer.

### Files Version

Version: 2.4.40.0

### Windows Version

Windows 11 Pro 22H2

**Comment by yaira2** [comment]
Would a keyboard shortcut work instead?

**Comment by raminmjj** [comment]
that would be great if you could add both of the features.

**Comment by yaira2** [comment]
Thank you for your feedback, we don't currently have plan to add "open with" to the toolbar but we're working on a feature that will allow you to assign a custom keyboard shortcut to the open with action.
