### ISSUE TITLE
Add a better layout for operation center Infomation

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#11524]
### What feature or improvement do you think would benefit Files?

Currently it kind of a mess with the Information moving around based on the length of the text.

### Requirements

- It could be shown as

```
Operation title (This can also show fail and success message)
Progress: items done/Total item todo (Progress percentage)
      To: Location path
    From: Location path
   Speed: XXXX MB/s 
Speed graph
```
(When #11265 is implemented)

Speed and speed graph can be replace with error message if #11522 Under it will be the action buttons

### Files Version

2.4.48.0

### Windows Version

10.0.22621.1265

**Comment by yaira2** [comment]
Can you share a concept?

**Comment by Josh-65** [comment]
I have made a basic concept for the layout and some information that could be added. 
Added what the graph could look like. (each line is a 10% progress increments) and the green/blue line would be for the speed overtime.

![Screenshot 2023-03-01 182633](https://user-images.githubusercontent.com/26977075/222243225-0abc088d-727c-447b-87aa-2efc7ec2cf6f.jpg)
