### ISSUE TITLE
Improve icons / thumbnails scaling

### ISSUE THREAD

**Issue by XPoppyX** [files-community/Files#1152]
the icons and thumbnails do not scale very well, when they are large the quality is very bad

**Windows File explorer** VS. **Files UWP:**
![Captura de pantalla 2020-11-04 180544](https://user-images.githubusercontent.com/61259627/98167818-729b3980-1ec8-11eb-8546-5eb05f6dedfb.png) ![Captura de pantalla 2020-11-04 180555](https://user-images.githubusercontent.com/61259627/98167847-7b8c0b00-1ec8-11eb-9f1c-bb56b978975f.png)

**Comment by AnuthaDev** [comment]
Maybe this is useful? https://devblogs.microsoft.com/oldnewthing/20140120-00/?p=2043

**Comment by yaichenbaum** [comment]
@XPoppyX This appears to be resolved with v1.0, can you let us know if it's still an issue on your end?

**Comment by XPoppyX** [comment]
Yes, it looks much better. Now this is the only thing I notice:
They look a bit pixelated compared to the native file explorer

**Files:**
![Captura de pantalla 2021-01-15 0839182](https://user-images.githubusercontent.com/61259627/104723430-ffa31000-570d-11eb-9f90-3f7201d42766.png)

**File explorer:**
![Captura de pantalla 2021-01-15 083918](https://user-images.githubusercontent.com/61259627/104723466-0df12c00-570e-11eb-8a1b-2caa4ffcfde2.png)

-----------------------

**Files:**
![Captura de pantalla 2021-01-15 090038](https://user-images.githubusercontent.com/61259627/104724974-3417cb80-5710-11eb-8324-718719b14983.png)

**File explorer**
![Captura de pantalla 2021-01-15 090048](https://user-images.githubusercontent.com/61259627/104724991-3c700680-5710-11eb-8fc0-6bc545f62aed.png)

It is even more noticeable in other images

**I don't know if I should open a new issue about this, what do you think?**

**Comment by duke7553** [comment]
@XPoppyX Hey Richard. I'm going to close this since we fixed the larger issue. I believe the pixelation is due to very slight differences in how the xaml image for the icons are stretched vs the thumbnail size requested. It doesn't look very noticeable to me, but if you find a scenario which has icons rendered in an unacceptable way please open a feedback item for it.
