### ISSUE TITLE
Make columns width adjustable

### ISSUE THREAD

**Issue by seltzdesign** [files-community/Files#11533]
### What feature or improvement do you think would benefit Files?

I love the columns layout on MacOS and am so happy to finally have it in Windows 11 as well. 

But one thing that Finder on MacOS can do in columns is make the width adjustable. Often long folder names are cut and there seems to be no way to adjust the column width.

Also in Finder on MacOS you can double-click the right border of a column and it will auto-adjust to fit all file/folder names.

There was even an extension for MacOS called TotalFinder that could always auto-adjust the columns to fit the names, which was super nice as well.

If something like that could be added it would make the columns view much more usable.

### Requirements

- Make columns width adjustable by clicking and dragging on the right border of a column
- Display a resizing cursor when hovering over the right border of a column
- Auto-adjust the width of a column when double-clicking the right border
- Add an option to always auto-adjust the width of columns

### Files Version

2.4.40.0

### Windows Version

Windows 11

### Comments

Thank you to anyone taking this on!

**Comment by yaira2** [comment]
Merging with #6534
