### ISSUE TITLE
Bug: Properties Customize page doesnt load icons from file

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#11542]
### Description

When selecting and .ico or .exe Files will not load any of them. Loading another .dll will crash Files

### Steps To Reproduce

1. Go to properties of a folder
2. Go to customise page
3. Select browse
4. Select a .dll, .ico or .exe file
5. See Files crash or not load icons

### Steps to fix

?

### Files Version

2.4,49.0

### Windows Version

10.0.22621.1265

### Log file

[debug.log](https://github.com/files-community/Files/files/10886874/debug.log)

**Comment by hishitetsu** [comment]
I can't reproduce it. Are there any conditions?

**Comment by hishitetsu** [comment]
> When selecting and .ico or .exe Files will not load any of them.

This should be added to the end of the icon list. I will fix the crash first.

**Comment by hishitetsu** [comment]
> This should be added to the end of the icon list.

Should we replace the icon list instead of adding icons?
