### ISSUE TITLE
Feature: Don't launch Files when user clicks on certain kinds of app notification

### ISSUE THREAD

**Issue by myfix16** [files-community/Files#11548]
### What feature or improvement do you think would benefit Files?

If you receive a Files' "Unhandled exception, submit feedback" app notification and click on it, a new Files window will launch. I don't consider this behavior appropriate since people don't intend to get a new Files window when they click on the "submit feedback" button on the notification.

Therefore, I think it's better to add some logic to the app notification activation handler to prevent launching another instance for some kinds of app notifications.

### Requirements

- This proposal will accomplish: Not launching the app when users click on certain kinds of app notifications

### Files Version

2.4.40.0

### Windows Version

Windows 11 22H2 10.0.22623.1325 (beta)

**Comment by yaira2** [comment]
Default Windows behavior is to open the app that created the notification, I don't think we have control over this.

**Comment by myfix16** [comment]
@yair100 Yes, we cannot control the opening behavior. But we can check the activation type `AppInstance.GetCurrent().GetActivatedEventArgs()?.Kind == ExtendedActivationKind.AppNotification` and call `Exit` or `Process.GetCurrentProcess().Kill()` before the MainWindow is shown, so that users won't see anything.
