### ISSUE TITLE
Bug: Selecting multiple files will show all options in the properties menu

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#11544]
### Description

![image](https://user-images.githubusercontent.com/26977075/222870201-33bd27dd-5ac9-4dab-abbb-d17df0efb543.png)

### Steps To Reproduce

1. Select multiple files
2. Open properties

### Steps to fix

?

### Files Version

2.4.49.0

### Windows Version

10.0.22621.1265

### Log file

[debug.log](https://github.com/files-community/Files/files/10887252/debug.log)

**Comment by hecksmosis** [comment]
I'll do this
