### ISSUE TITLE
Bug: Empty and Restore button disappear when opening the recycle bin twice

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#11540]
### Description

Empty and Restore button is not displayed when opening the recycle bin twice.
Furthermore, the app crashes when trying to open another folder from this state.
![image](https://user-images.githubusercontent.com/66369541/222759124-d0f2d364-278b-4289-bfd1-f9a2728b2601.png)

### Steps To Reproduce

1. Open the recycle bin and you see Empty and Restore button.
2. Open another folder.
3. Open the recycle bin again.
4. Empty and Restore button disappear this time.
5. If trying to open another folder from this state, the app will crash.

### Steps to fix

Show the buttons every time and avoid the crash.

### Files Version

2.4.49.0

### Windows Version

10.0.22621.1265

### Log file

[debug.log](https://github.com/files-community/Files/files/10883319/debug.log)

**Comment by hishitetsu** [comment]
I have investigated it, but I have no idea.
When this occurs, it appears that x:Load is not being evaluated even though the property value has changed.
However, sometimes the buttons appear even the second time.
This does not occur in the released version even though the x:load condition has not changed. This is a complete mystery.

**Comment by hishitetsu** [comment]
Changing `x:Load` to `Visibilty` will resolve this issue, but is it appropriate?

**Comment by hishitetsu** [comment]
I managed to figure out that it occurs when using OpacityIcon. When using FontIcon, it doesn't occur. I don't know why, maybe due to a Windows App SDK bug or maybe due to an OpacityIcon bug.

**Comment by hishitetsu** [comment]
@yair100 It seems this happens when using OpacityIcon via RichCommand only. FontIcon via RichCommand or `<local:OpacityIcon>` work properly. Can you think of anything that might help?

**Comment by yaira2** [comment]
But the context menu doesn't have this issue? We can work around this by hardcoding the icon in the toolbar but @cinqmilleans wants us to use the icon property in the comand.

**Comment by yaira2** [comment]
Is `mode` set to oneway?

**Comment by hishitetsu** [comment]
Explicitly setting oneway did not resolve the problem.

**Comment by yaira2** [comment]
Maybe @cinqmilleans knows. I'd prefer using x:Load if we can.

**Comment by cinqmilleans** [comment]
Is the problem fixed in pr #11565?

**Comment by hishitetsu** [comment]
> Is the problem fixed in pr https://github.com/files-community/Files/pull/11565?

I thought so too and was the first to try it, but no luck.

**Comment by hishitetsu** [comment]
I found a better workaround, I'll submit a PR.
