### ISSUE TITLE
The APP react slowly and weird after running couple of hours.

### ISSUE THREAD

**Issue by Janrilw** [files-community/Files#11545]
### Description

 I like "continue from where you left", and I open the app all the time to keep commonly used folders avaliable, though win11 reboot. But the APP may react slowly and weird after running couple of hours, , for example, I cannot rename a file, the focus often run to the upper folder; I cannot move or clip file easily, which may lead to much lag; clicking on a tab will most likely move it to a new window; sometimes the focus just quickly jump from two adjacent folder and I cannot do anything but forcefully close it.
Besides, clicking file(not folder) in list view may instantly destroy all subfolders already opened on the right side, and everything flash to right, but right click won't trigger that. It is difficult to adapt the content flash on screen. Destroying that is reasonable, but I think it's better to keep the horizontal position.
Anyway, the list view and "continue from where you left" option is 2 reason I give up the default file manager in win11, you guys did really good thing.

### Steps To Reproduce

Use the APP in normal way but never close it, opening multiple tabs is required.

### Steps to fix

Restart can fix the problem, but restarting it everyday may not a good idea.

### Files Version

2.4.40.0

### Windows Version

10.0.22621.1265

**Comment by Josh65-2201** [comment]
Can you please upload the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.

**Comment by yaira2** [comment]
This is a result of some memory leaks, we recommend reopening the app every now and then to work around this issue until it's fixed. We're tracking this in #4180

**Comment by Janrilw** [comment]
> Can you please upload (Do not copy and paste content) the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.

Alright, sorry for inconvenience.
[debug.log](https://github.com/files-community/Files/files/10890817/debug.log)

**Comment by yair100** [comment]
@Janrilw we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller

**Comment by Janrilw** [comment]
thanks, i have noticed the better performance of the app, i will use it for a couple of weeks.



---Original---
From: ***@***.***&gt;
Date: Fri, Sep 4, 2026 05:49 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [files-community/Files] The APP react slowly and weird after running couple of hours. (Issue #11545)


yair100 left a comment (files-community/Files#11545)
 
@Janrilw we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications, keep track of coding agent tasks and review pull requests on the go with GitHub Mobile for iOS and Android. Download it today!

**Comment by yair100** [comment]
@Janrilw thank you for checking.
