### ISSUE TITLE
Can't open folder in Windows Terminal

### ISSUE THREAD

**Issue by AlexNakamuraDF** [files-community/Files#11554]
### Description

Context menu doesn't show option to open folder in Windows Terminal.
<img width="482" alt="image" src="https://user-images.githubusercontent.com/72317263/222934447-3dbb17da-e3ce-43c7-8c08-51b15667186f.png">

(edit) It does show up in Windows File Explorer:
![image](https://user-images.githubusercontent.com/72317263/222934937-5203bc20-a0b6-44c7-96c1-821c3e3cf0ba.png)
### Steps To Reproduce

1. Open Files
2. Open a folder
3. Right click and see context menu

### Steps to fix

Reestablish the option in the context menu that opens a folder in Windows Terminal.

### Files Version

Version: 2.4.40.0 OS Version: 10.0.22621.1265

### Windows Version

Windows 11 22H2 22621.1265

### Log file
[debug.log](https://github.com/files-community/Files/files/10890476/debug.log)

**Comment by Josh65-2201** [comment]
Does the option show in Windows File explorer?

Also can you please upload (Do not copy and paste content) the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.

**Comment by AlexNakamuraDF** [comment]
Done

**Comment by AlexNakamuraDF** [comment]
I found old (solved) bugs about the same thing:
* [8100](https://github.com/files-community/Files/issues/8100)
* [8603](https://github.com/files-community/Files/issues/8603)
* [10939](https://github.com/files-community/Files/issues/10939)

**Comment by Josh65-2201** [comment]
They were for older version of Files. The way it work has change a lot since then

**Comment by yaira2** [comment]
The open in Terminal option is added by Windows Terminal as a shell extension and we don't have control over when it shows, we do however have a keyboard shortcut ctrl + ` that'll open the folder in Terminal.

**Comment by AlexNakamuraDF** [comment]
Thanks! That solves my problem, although I found out there's another bug where that shortcut doesn't work if there are spaces in the current path. I've made another bug report [11555](https://github.com/files-community/Files/issues/11555)

Out of curiosity, does that mean that the git and VS Code options that do appear in the context menu are explicitly supported by Files?

**Comment by yaira2** [comment]
Git and VS Code register shell extensions as well, Windows Terminal sometimes shows up but it's inconsistent. It might have something to do with the way they register the extension.

**Comment by AlexNakamuraDF** [comment]
Good to know, thank you!
