### ISSUE TITLE
Bug: Tags not staying

### ISSUE THREAD

**Issue by KultidGames** [files-community/Files#11553]
### Description

I have created a tag "Done" that I try to apply to files- however, after trying to add that to some recent files, I have been entirely unable to do so- with the tags seemingly being applied at first, but then are removed upon either refreshing the page, exiting the application or going to another folder.

Restarted application several times as well as PC, to no avail.

### Steps To Reproduce

1. Create a tag
2. Apply tag to document
3. Refresh page

### Steps to fix

- Fix bug by having the tag stay after refreshing

### Files Version

2.4.4.40.0

### Windows Version

Windows 10 Home Version

### Log file
[debug.log](https://github.com/files-community/Files/files/10889690/debug.log)

**Comment by Josh65-2201** [comment]
Can you please upload (Do not copy and paste content) the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.

**Comment by KultidGames** [comment]
> Can you please upload (Do not copy and paste content) the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.

My apologies, I've never opened an issue here before! Hopefully that edit was what you were looking for!

**Comment by Josh65-2201** [comment]
Where are the files/folders located you're putting the tags on?

**Comment by Josh65-2201** [comment]
I assume that's the sync folder for Google drive. There might not be anything to do as cloud drives does not support ADS files (what Files uses for tags) and deletes them.

**Comment by KultidGames** [comment]
That's actually just the name of the folder, it's a download I made using RClone- so all of those files are on my PC- there shouldn't be any cloud drives here. At least that I'm aware of, anyways.

**Comment by cwade12c** [comment]
I am experiencing the same behavior.

## Steps To Reproduce
1. Create a tag (I named mine "Entertainment")
2. Apply tag to directory (I applied mine to a directory located on an external hard drive (H:\); this drive always stays plugged in and the drive letter has not changed)
3. Reboot the machine

## Files Version
2.4.40.0

## Windows Version
Windows 11 Home Version 22H2

## Log file
[debug.log](https://github.com/files-community/Files/files/10893305/debug.log)

**Comment by KultidGames** [comment]
Update: 

The File tagging won't apply to only a few files/folders- but it's seemingly at random. 

I've gone back and confirmed that these files do in fact exist and aren't corrupted in any way- it's quite literally random that the tags won't stick.

**Comment by cwade12c** [comment]
They consistently won't stick for me, using the same reproduction steps.

**Comment by yaira2** [comment]
@KultidGames is this specific to Google Drive?

**Comment by KultidGames** [comment]
> @KultidGames is this specific to Google Drive?

The files are locally hosted on my computer- downloaded using RClone from a Google Drive. The files are on my PC- there really isn't any connection to Google Drive other than that being their source, however.

**Comment by yaira2** [comment]
@KultidGames can you try enabling alternate data streams from `Settings > Folders > Hidden Items> Alternate Data Streams`? Let us know if you see an extra file after tagging an item and refreshing the folder.

**Comment by yaira2** [comment]
@KultidGames
