### ISSUE TITLE
Add option to show Windows 11 Context Menu Shell Extensions always on main menu and not sub-menu

### ISSUE THREAD

**Issue by TheAndyMac** [files-community/Files#11558]
### What feature or improvement do you think would benefit Files?

As more products are correctly supporting the Windows 11 Context Menu structure, it would be great if Files had the option to pick up shell extensions that have Windows 11 Context Menus where they are available, displayed them on the top-level menu (perfoming as expected in Windows 11) and removing their legacy menu (if they exist) from the "Show more options..." sub menu.

### Requirements

- Add option in settings for Context Menu to "Use/Honour Windows 11 Context Menus" or use only legacy shell extensions
- Logic in app to determine duplication of Windows 11 and legacy shell extensions depending on this setting
- If in Windows 11 Context Menu mode, always show these on the main menu even if "Move shell extensions to sub menu" on
- If "Move shell extensions to sub menu" off, group Windows 11 extensions after main section, and then show other extensions

### Files Version

2.4.40.0

### Windows Version

Windows 11 Pro Version	22H2 build 22621.1344

**Comment by yaira2** [comment]
This is available in preferences settings "Move shell extensions into a sub menu".

**Comment by TheAndyMac** [comment]
No it does not do what I was asking for - maybe I did not explain it clearly. 

Below is my Windows 11 File Explorer menu with the Windows 11 Context Menu items shown:
<img width="236" alt="image" src="https://user-images.githubusercontent.com/12783814/222977216-40453982-ff8a-47fc-a2f7-9f60ff302b37.png">

and below is Files menu with "Move shell extensions into sub menu" enabled:
<img width="498" alt="image" src="https://user-images.githubusercontent.com/12783814/222977331-e7b233db-f6c2-4cd5-a22d-a7bd25b82caf.png">

What I am suggesting is to provide the option to have the best of both of these, with the Windows 11 Context Menu items available on the main context menu in Files - mocked up as follows:
<img width="467" alt="image" src="https://user-images.githubusercontent.com/12783814/222978123-fb8b7de2-af1c-4d87-aabb-f7f4df981514.png">

**Comment by yaira2** [comment]
The option doesn't currently apply to the home page widgets (it's on the todo list), however, if you right click a file in one of the layout modes it'll take affect.

**Comment by TheAndyMac** [comment]
I've just tried it on some files in Downloads and in Music and it does not show the Windows 11 Context Menu items on the main menu (same system as previous screen shots where Windows File Explorer is showing the additional menus.

<img width="302" alt="image" src="https://user-images.githubusercontent.com/12783814/222989936-31d386cc-8d79-4819-8b50-c55043c710d1.png">

Is this coming in a new version? This was with version 2.4.40.0 on Windows 11 22H2.

**Comment by yaira2** [comment]
Did you turn the setting off? It looks like the setting is still turned on.

**Comment by TheAndyMac** [comment]
Switching the setting off 
<img width="606" alt="image" src="https://user-images.githubusercontent.com/12783814/223040175-ad38b9eb-e84d-455b-8fe1-c64f41596519.png">

gives ALL the extensions added, making the menu a scrolling menu which is really hard to use
<img width="371" alt="image" src="https://user-images.githubusercontent.com/12783814/223040131-a7f10d60-5dc3-40f4-9c59-069ccf424509.png">

while switching the setting on 
<img width="678" alt="image" src="https://user-images.githubusercontent.com/12783814/223040259-82713f57-3b12-404e-a9bf-3a4149ec58e7.png">

has the following
<img width="564" alt="image" src="https://user-images.githubusercontent.com/12783814/223040334-56b5c433-5fee-4ab3-9f82-bd3d282ea5e4.png">
