### ISSUE TITLE
Software response speed   

### ISSUE THREAD

**Issue by CC0413** [files-community/Files#11556]
### What feature or improvement do you think would benefit Files?

The first time to open files software will be stuck and not as fast as windows Explorer response, and the computer will display a white screen when files are opened

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.4.40.0

### Windows Version

10.0.19044.1865

**Comment by QuaintMako** [comment]
Can you link the debug file please?

**Comment by CC0413** [comment]
Could you give me some information? Because I don't know how to link debug.
 




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "files-community/Files"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月5日(星期天) 下午5:19
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [files-community/Files] Software response speed    (Issue #11556)





 
Can you link the debug file please?

**Comment by yaira2** [comment]
Performance improvements are being tacked in #4180

**Comment by yair100** [comment]
@CC0413 we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
