### ISSUE TITLE
Bug: Open in terminal shortcut doesn't work with paths that have spaces

### ISSUE THREAD

**Issue by AlexNakamuraDF** [files-community/Files#11555]
### Description

It's not possible to open folders with spaces in their path using the open terminal shortcut Ctrl+`
Windows Terminal shows error 2147942402

![image](https://user-images.githubusercontent.com/72317263/222937870-29359e30-673d-46e9-8358-1ae245b1f142.png)

### Steps To Reproduce

1. Create a directory named "Test folder with spaces"
2. Open the previous directory
3. Press Ctrl+`
![image](https://user-images.githubusercontent.com/72317263/222937870-29359e30-673d-46e9-8358-1ae245b1f142.png)

### Steps to fix

Stop Windows Terminal from throwing error 2147942402 when trying to open a folder that has spaces in its path and actually open said folder in Windows terminal when pressing Ctrl+`

I haven't looked at the code yet, but I guess there are some quotation marks missing in the command that adds this functionality.

### Files Version

Version: 2.4.40.0 OS Version: 10.0.22621.1265

### Windows Version

Windows 11 22H2 22621.1265

### Log file

[debug.log](https://github.com/files-community/Files/files/10890615/debug.log)

**Comment by yaira2** [comment]
Good catch
