### ISSUE TITLE
Bug: Folders with dots in their name cannot be opened if compressed

### ISSUE THREAD

**Issue by Jemtaly** [files-community/Files#11567]
### Description

When double-clicking a folder with a dot in its name in an archive, the "Open With" menu appears. It seems that this folder is considered a file.

### Steps To Reproduce

1. Create a folder with a dot in its name, such as foo.bar.
2. Compress the folder to .zip (or .7z, .rar, .tar, ...) file.
3. Open the compressed file in Files.
4. Double-click the folder with a dot in its name.

### Steps to fix

- Allow user to open folders with dots in their names

### Files Version

Version: 2.4.40.0 OS Version: 25309.1000

### Windows Version

Windows 11 Insider Preview 22H2 25309.1000

### Log file

[debug.log](https://github.com/files-community/Files/files/10894365/debug.log)

### Screenshot

![image](https://user-images.githubusercontent.com/83796250/223020691-61d31d78-c956-4ea8-b315-67ad296b616e.png)

**Comment by Jemtaly** [comment]
Yes, it still exists.

**Comment by yaira2** [comment]
@Jemtaly a fix has been implemented and will be included in one of the next feature releases.
