### ISSUE TITLE
Add the "Open in Terminal" context menu to the right-click menu of the root directory of the disk.

### ISSUE THREAD

**Issue by Jemtaly** [files-community/Files#11569]
### What feature or improvement do you think would benefit Files?

The "Open in Terminal" context menu didn't show up in the right-click menu at the root of the disk, which was confusing since it would show up in any other directory.

### Requirements

- Add the "Open in Terminal" context menu to the right-click menu of the root directory of the disk.

### Files Version

2.4.40.0

### Windows Version

Windows 11 Insider Preview 22H2 25309.1000

**Comment by yaira2** [comment]
This behavior is controlled by Windows Terminal, I recommend requesting this on the Terminal repo.

**Comment by Jemtaly** [comment]
> This behavior is controlled by Windows Terminal, I recommend requesting this on the Terminal repo.

I found it odd because the context menu can be correctly shown in Windows Explorer. (Figure 1)

Also, not only the "Open in terminal" context menu, but many other context menus are also not displayed at the root of the disk. (Comparing Figure 2 and Figure 3)

![image](https://user-images.githubusercontent.com/83796250/223022624-b86a5fdb-1586-4180-9b1b-9fbdca5edecb.png)
![image](https://user-images.githubusercontent.com/83796250/223022658-9ce52b17-4c6d-472e-a331-ae722230cf8b.png)
![image](https://user-images.githubusercontent.com/83796250/223023765-545d39be-6b4e-48c0-abfd-46739eeff3c6.png)

**Comment by yaira2** [comment]
We're tracking this in another issue, it's possible that it's a permissions issue but it's on our todo list to fix.
