### ISSUE TITLE
Feature: Migrate from Vanara Shell

### ISSUE THREAD

**Issue by QuaintMako** [files-community/Files#11566]
### What feature or improvement do you think would benefit Files?

[Vanara](https://github.com/dahall/Vanara) is a library that streamlines the use of P/Invoke functions, enabling an easier use of Windows' programming functionalities.

While it helped us developped some functionalities within Files, it has been done to a cost. Some part of is preventing us from enabling the [trimming of the application](https://devblogs.microsoft.com/dotnet/app-trimming-in-net-5/) and increases greatly the start up time of the application.

Vanara assemblies are marked for Trimming, but any exposed COM interface cannot be trimmed. Hence, we wish to remove the use of Vanara where COM interfaces are being accessed.

### Requirements

- No regression after eliminating the use of exposed COM interfaces.
- Trimming works as expected.

### Files Version

Version 2.4.40

### Windows Version

Irrelevant

**Comment by yaira2** [comment]
@dahall Vanara has been incredibly useful in Files but it's holding us back from enabling trimming, do you have plans to add trimming support? This will save us a lot of time and will enable us to continue using the library.

**Comment by dahall** [comment]
Vanara's assemblies are all marked for trimming. However, any COM interface exposed, which is almost all the IShellXxx interfaces, cannot be trimmed. It is a shortcoming of .NET, not Vanara.

**Comment by yaira2** [comment]
In that case we can limit the scope of this task to only apply to code where com is being accessed.
