### ISSUE TITLE
Bug: Restore (not Restore All) button does not appear in the toolbar

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#11568]
### Description

Restore button is defined in `InnerNavigationToolbar.xaml`, but it cannot be displayed because `Visibility` property is set to a bool value incorrectly.
If Restore and Restore All button should not be available, I think it should be disabled using `isEnabled` property rather than invisible using `Visibility` property.

### Steps To Reproduce

1. Go to the recycle bin.
2. You see the Empty button and the Restore All button, but not Restore button.

### Steps to fix

Use `isEnabled` instead of `Visibility`.

### Files Version

2.4.49.0

### Windows Version

10.0.22621.1265

### Log file

n/a

**Comment by yaira2** [comment]
Can you try with https://github.com/files-community/Files/pull/11565?

**Comment by hishitetsu** [comment]
Sorry, I was mistaken. I close it.
