### ISSUE TITLE
Need 【Bookmark bar】，Please look at the picture。

### ISSUE THREAD

**Issue by Jimmy20220531** [files-community/Files#11577]
### What feature or improvement do you think would benefit Files?

Need 【Bookmark bar】，Please look at the picture。
![2023-03-07 01 01 44](https://user-images.githubusercontent.com/106609389/223181000-736b81fd-d4ef-476e-87b2-38e3a30596c9.png)
![2023-03-07 01 03 33](https://user-images.githubusercontent.com/106609389/223181020-b0f4a39e-99d2-4061-a0db-a56b818853d8.png)

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.4.40.0

### Windows Version

Windows 10 22h2

**Comment by Josh65-2201** [comment]
Merging with #6458
