### ISSUE TITLE
Bug: Items with Tags applied cannot be copied or cut to non NTFS disks

### ISSUE THREAD

**Issue by Worgle123** [files-community/Files#11570]
### Description

I updated my files version, and as I had lost my disk, I had quite a few files to move onto my disk. I had used tags to keep track of them all, but when I tried to move any number, they would briefly appear, before disappearing again. The ongoing tasks section tells me that the process had failed, so I tried opening them. This worked, so I had a check, and it was only happening with files assigned to a tag. Removing the tags from the files resolved the issue. I sincerely hope that this issue is resolved ASAP, as it makes using the feature extremely difficult. 

Disk used was a just about brand new Samsung T7 SSD.

Thank-you for your consideration.

### Steps To Reproduce

Set a tag for a file.

Attempt to move the file to a disk. It does not matter which buttons you use to copy/paste them, or whether you drag and drop them. (buttons mentioned being in r/click and top bar)

You should get an error saying that it failed to perform the action in the Ongoing tasks list, and file will not have been moved.

### Steps to fix

Fix error which prevents movement of any file to a disk which has a Tag applied. I don't know much about code so can't tell you any possible steps to fix DX (<<<upside down XD)... Sorry...

### Files Version

2.4.40.0

### Windows Version

10.0.22621.1194 or Windows 11, version 22H2

### Log file

[debug.log](https://github.com/files-community/Files/files/10894983/debug.log)

**Comment by gave92** [comment]
What happens if you copy those tagged files using Explorer?

**Comment by hecksmosis** [comment]
Is the disk formatted as NTFS? (Tags only work on NTFS drives)

**Comment by Worgle123** [comment]
File system is exFAT but I don't know if that is it's format.

**Comment by Worgle123** [comment]
> What happens if you copy those tagged files using Explorer?

I can copy/cut them, but a dialog box appears saying that it has properties that cannot be copied. I assume this is just the info about which tag it owns.

**Comment by yaira2** [comment]
> File system is exFAT but I don't know if that is it's format.

This is why, tags don't work on exFAT.

**Comment by gave92** [comment]
We should still allow for the file to be copied though.

**Comment by Worgle123** [comment]
> > File system is exFAT but I don't know if that is it's format.
> 
> This is why, tags don't work on exFAT.

Is compatibility with other formats going to be added, or is it not possible. I really don't want to have to copy/delete my files just to format a disk, especially with 2tb XD...

**Comment by yaira2** [comment]
@Worgle123 a fix has been implemented and will be included in one of the next feature releases.

**Comment by Worgle123** [comment]
Thanks!

Sent via Superhuman ( ***@***.*** )
