### ISSUE TITLE
Deleting tag causes app crash

### ISSUE THREAD

**Issue by ryjacky** [files-community/Files#11573]
### Description

Files app crashes when I tried to delete more than one tags. I just downloaded the app, it is a fresh install and I have never installed it before.

### Steps To Reproduce

1. Go to settings
2. Click on tags
3. Delete one tag (In my case, I deleted the first one first)
4. Delete another tag (then I deleted the second one)
5. It will crash, but the tag is deleted after reopening the app

### Steps to fix

- Fix crash that occurs when deleting more than one tag.

### Files Version

2.4.40.0

### Windows Version

Windows 11 22H2 22621.1265

### Log file

[debug.log](https://github.com/files-community/Files/files/10896948/debug.log)

**Comment by ferrariofilippo** [comment]
Is this an issue in the preview version? https://files.community/download/preview

**Comment by ryjacky** [comment]
I think it is the stable stable version, I downloaded the classic installer at https://files.community/download, the downloaded installer is also named Files.Stable.exe

**Comment by yaira2** [comment]
@ryjacky can you try the preview version?

**Comment by ryjacky** [comment]
Seems like it is fixed in the preview version 2.4.51.0
