### ISSUE TITLE
Better error reporting during operations

### ISSUE THREAD

**Issue by seltzdesign** [files-community/Files#11586]
### What feature or improvement do you think would benefit Files?

Not sure if this is a feature request. From a UX perspective I find it so severe, that I would almost call it a bug.

When there is an error during an operation, you basically get no visual feedback whatsoever. Right now I am trying to move a folder to program files. I drag the folder from the desktop and let go when it says "Move to program files". The folder disappears from the Desktop, but does not appear in the Program Files folder. I did undo and the folder came back. I tried again, but nothing seemed to happen.

Then I noticed that the icon for operations was still there and clicked on it only to see there were errors.

![Screenshot 2023-03-07 132919](https://user-images.githubusercontent.com/6575829/223423687-678a5ef6-a896-4a2e-89cd-88d53068e58f.jpg)

But if you don't open the panel all you see is:

![Screenshot 2023-03-07 133545](https://user-images.githubusercontent.com/6575829/223423855-c4f8aa5c-5596-43e0-bd60-6f6aec521f48.jpg)

Really? That is supposed to tell you there was an error? Not even a small icon, a color change, anything at all?

I refuse to believe that this behavior is intentional. Surely there is some way of actually noticing errors. If not than that would be one of the biggest UX blunders I have seen in many years of being a UX designer.

Bonus question: where does the folder go when I move it and the error appears. It's not on the desktop any more, but also not in the new place. Luckily undo worked, otherwise the folder would have remained in limbo??

### Requirements

- Actually show me there is an error
- Don't actually move a folder if there was an error or move it back

### Files Version

2.4.40.0

### Windows Version

Windows 11 22H2

**Comment by seltzdesign** [comment]
Moved it with Explorer in the end. This is the message that popped up:

<img width="354" alt="image" src="https://user-images.githubusercontent.com/6575829/223425410-481d678e-d647-43bd-a765-380376705c26.png">

You just press continue and it works.

The inability of files to forward or deal with those dialogues I feel is its biggest shortcoming. I would love to replace Explorer with Files for good, but with this and the other errors it can't deal with and doesn't handle gracefully it's just not viable. Shame.

**Comment by yaira2** [comment]
We're tracking this in a couple of different issues
