### ISSUE TITLE
Bigger thumbnails

### ISSUE THREAD

**Issue by francisco-lafe** [files-community/Files#11582]
### What feature or improvement do you think would benefit Files?

Hi, this is a very niche feature but it would be very appreciated. 
Right now I have a 4k monitor, and although the thumbnails are bigger than Windows Explorer, they're still small enough to not be able to see the content of the images. 
Can you allow for "bigger" thumbnails? 

SideBySide comparison:
![image](https://user-images.githubusercontent.com/90066435/223210179-abd0367e-b09e-40a4-b120-2777f4e6876d.png)

### Requirements

- This proposal would allow for a larger degree of zoom in when browsing folders with images, allowing the end-user to have a better preview of the images on a certain location.

### Files Version

2.4.40.0

### Windows Version

10.0.19044.2604

**Comment by yaira2** [comment]
Did you use ctrl + + to zoom in further?

**Comment by francisco-lafe** [comment]
> Did you use ctrl + + to zoom in further?

Hi @yair100 , The left side of the comparison side by side has the max zoom the Files app allows.

**Comment by yaira2** [comment]
This is better suited for a photo layout #5058. In the meantime, you can enable the preview pane to view a larger thumbnail.

**Comment by francisco-lafe** [comment]
It would be a nice feature, as I don't think having the photos in a weird layout would work for my purposes (if you notice I've them ordered by date in the name).  
It's up to you of course, as it's a niche feature.
