### ISSUE TITLE
Code Quality: installed version of NuGet package LiteDB has a critical vulnerability

### ISSUE THREAD

**Issue by ferrariofilippo** [files-community/Files#11585]
### Description

Currently, we're using a version of `LiteDB` which has  a vulnerability of `critical severity`. We should upgrade the package to avoid that.

### Concerned code

- `Files.Shared`

### Gains

- A safer code

### Requirements

- Update `LiteDB` to the latest version (or one that has no issues)

### Comments

![1](https://user-images.githubusercontent.com/102259289/223413196-04502aa1-2840-4f6e-ae41-de3cf2d2421c.png)

**Comment by hez2010** [comment]
Unfortunately we are unable to switch to LiteDB 5.x due to a concurrency issue. 
See #10577.

**Comment by yaira2** [comment]
The vulnerability doesn't affect Files so we should be safe.
