### ISSUE TITLE
Right click -> open in "windows file explorer" (feature)

### ISSUE THREAD

**Issue by gtu78aed87t** [files-community/Files#11595]
### What feature or improvement do you think would benefit Files?

To be able to quickly open location in "windows file explorer" would be awesome. Thanks.

### Requirements

n/a

### Files Version

v2.4.40

### Windows Version

n/a

**Comment by yaira2** [comment]
Files is supposed to replace File Explorer, if we're missing a feature, let us know 🙂

**Comment by Josh65-2201** [comment]
You can currently type `explorer ` with a space in front of the path in the path bar that will open Windows explorer even if Files is set as default
