### ISSUE TITLE
Feature: Support "Select Element" feature in running application

### ISSUE THREAD

**Issue by Poker-sang** [files-community/Files#11592]
### What feature or improvement do you think would benefit Files?

![UFX8LALZ{N67(}TT CKG4(6](https://user-images.githubusercontent.com/62325494/223490620-1a70b4b1-61d2-41eb-b521-16239e06fb57.png)

When an app runs, we can see the in-app toolbar appear within the running application. It is useful when debugging and positioning bugs.

But because of the set of `AppWindowTitleBar.SetDragRectangles()`. The area of toolbar is blocked.

I hope when in debug mode, the area of toolbar can be made available for use.

### Requirements

- This proposal will support **Select Element** feature in running application (only available in DEBUG mode)

### Files Version

2.0.36.0

### Windows Version

Windows11 22H2 22621.1265

**Comment by yaira2** [comment]
This has been an issue ever since we moved to WinAppSdk, it doesn't really affect the app but it would be nice if there was a way to fix it.

**Comment by Poker-sang** [comment]
> This has been an issue ever since we moved to WinAppSdk, it doesn't really affect the app but it would be nice if there was a way to fix it.

I thought simply use `#if DEBUG` and `SetDragRectangle`. And this issue can be fixed.

**Comment by yaira2** [comment]
That's a good idea, do you want to work on this?

**Comment by Poker-sang** [comment]
> That's a good idea, do you want to work on this?

 Sure, let me try it out.
