### ISSUE TITLE
Bug: Tags Widget Context Menu uses wrong string for folders

### ISSUE THREAD

**Issue by ferrariofilippo** [files-community/Files#11599]
### Description

When you right click a folder from Tags Widget, context menu is localized in two different languages

### Steps To Reproduce

1. Open Home page
2. Right click on a folder in the Tags Widget
3. See that some strings are localized in a different language

### Steps to fix

- Use en-US strings

### Files Version

Files Preview 2.4.49.0

### Windows Version

Windows 11 Pro 22H2 10.0.22621.1265

### Log file

![3](https://user-images.githubusercontent.com/102259289/223542510-660ca3d1-208d-49f2-b7cd-bdd060b04407.png)
![2](https://user-images.githubusercontent.com/102259289/223542513-ee55a397-7604-4873-8bad-ab0401898a30.png)

**Comment by yaira2** [comment]
Which language? If you have two language packs in Windows it'll fallback if it's missing a string.

**Comment by ferrariofilippo** [comment]
I have Italian and English USA installed and Files is set to Italian

**Comment by yaira2** [comment]
What happens if you remove the language packs so you just have English?

**Comment by ferrariofilippo** [comment]
Just checked, the string used for `Properties` is actually available only for `da-DK` and `or-IN`. I think other strings are probably the same

**Comment by yaira2** [comment]
Is it in en-us?

**Comment by ferrariofilippo** [comment]
No

**Comment by yaira2** [comment]
Can you check again?

**Comment by ferrariofilippo** [comment]
Still not working

**Comment by ferrariofilippo** [comment]
The problem is that not all strings were updated in #11469 
Here's an example:

![1](https://user-images.githubusercontent.com/102259289/223549373-7101dc12-9a37-4ade-9ea2-1958dcc84362.png)

but in Tags widget there's still the old name
