### ISSUE TITLE
Install file directory location

### ISSUE THREAD

**Issue by gtu78aed87t** [files-community/Files#11593]
### What feature or improvement do you think would benefit Files?

I'm trying to locate the install directory of this application in Windows 10. I wish it was a reveal button under settings.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

v2.4.40

### Windows Version

win 10

### Comments

n/a

**Comment by Josh65-2201** [comment]
Type `files.exe` into the start menu and click open file location
