### ISSUE TITLE
Bug: Format drive option is missing

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#11607]
### What feature or improvement do you think would benefit Files?

It is not possible to format a drive with Files.

### Requirements

 This option should be added to the drive context menus and in the properties popup.
Just open the Windows formatting interface. Possibly preceded by a warning.

### Files Version

2.4.49.0

### Windows Version

10.0.19045.2604

**Comment by hecksmosis** [comment]
This is already implemented

**Comment by hecksmosis** [comment]
It's under "Show more options..."

**Comment by Lukiluc29** [comment]
Personally, it only displays "Format..." and after that opens a PowerShell window. Besides, it would be nice not to display it anymore, I think, to do like the "real" file explorer

**Comment by lucas-thiebaut** [comment]
@yair100 Personally, it shows me "Format..." in the context menu without going into "Show more options".
<img width="328" alt="Capture d'écran 2023-05-13 111024" src="https://github.com/files-community/Files/assets/128183422/698b99d5-c95e-4c90-b142-be9a76ea1026">

**Comment by yaira2** [comment]
@cinqmilleans this issue should be addressed with #13173.
