### ISSUE TITLE
Cut texts in properties

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#11606]
### Description

The texts do not have enough space in the property view, which was designed for English.
In French:
Sauvegard instead of Sauvegarder
Personnalisati instead of Personnalisation

### Steps To Reproduce

1. Use Files in French.
2. Open the property popup.
3. Read the texts.

### Steps to fix

Adjust the size available for the texts.

### Files Version

2.4.49.0

### Windows Version

10.0.19045.2604

### Log file

![property](https://user-images.githubusercontent.com/46631671/223639851-2afa5ea2-d1b6-42d0-8506-2b357d681e30.png)

**Comment by yaira2** [comment]
This is currently as placeholder in the preview branch, the final design won't have this issue.
