### ISSUE TITLE
Bug: Delete has the wrong color

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#11605]
### Description

When inactive, the Delete icon is colored, unlike all the others. However, it is not possible to click on it.

### Steps To Reproduce

1. Display Home.
2. The icon delete is colored.

### Steps to fix

Modify the style of the Delete icon when it is inactive.

### Files Version

2.4.49.0

### Windows Version

10.0.19045.2604

### Log file

Home Page
![one](https://user-images.githubusercontent.com/46631671/223638701-4a93b16f-03c6-422c-909a-e9ea9e057275.png)
Detail Page
![two](https://user-images.githubusercontent.com/46631671/223638703-40fe0441-6490-4e6e-af8e-1025d2bb10f3.png)

**Comment by Josh65-2201** [comment]
Was this not fixed with #11539

**Comment by yaira2** [comment]
Was fixed in a different PR.
