### ISSUE TITLE
After pinning an item, the pin option should be changed to unpin.

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#1160]

**Comment by soumyamahunt** [comment]
Should this be classified as bug instead of feature-request?? I mean, Windows Explorer also shows pin option even if the folder is pinned to quick access.

**Comment by Jaiganeshkumaran** [comment]
@soumyamahunt File Explorer is different, Files UWP is different. You should understand that Files UWP isn't a fluent design copycat of File Explorer instead the goal of Files UWP is to provide a better file manager for Windows.

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran This issue should be resolved with #2859.
