### ISSUE TITLE
Open folder in Wsl2 Ubuntu.

### ISSUE THREAD

**Issue by sergiodn** [files-community/Files#11619]
### Description

When we click on a folder inside Wsl2 Ubuntu, we get the following error message: Network folder error.
When we access the same folder using Windows Explorer, it opens with errors.

Thanks.
Sérgio
Humansoft

### Steps To Reproduce

1. Open Files
2. Click on WSL\Ubuntu in Folders view.
3. Click on home folder
4. We get the error Nework folder error

### Steps to fix

- Fix crash that occurs when we click on a folder inside WSL\Ubuntu

### Files Version

Version: 2.4.40.0

### Windows Version

Windows 11, 22H2 22621.1344

### Log file

I dont have any log file

**Comment by Josh65-2201** [comment]
Merging with #11272
