### ISSUE TITLE
Bug: Context menu is broken.

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#11615]
### Description

The context menu for the parent folder no longer works. This seems to be coming from the commands that compression. The Label property updates based on the content, but may throw an error.

For the specific case of these commands, I recommend having a generic label, and modifying the label in the menu display. It will be better for the command handler.

### Steps To Reproduce

1 Open the context menu in a base folder

### Steps to fix

Fix the compression commands

### Files Version

Last commit

### Windows Version

Win11

### Log file

None

**Comment by ferrariofilippo** [comment]
> For the specific case of these commands, I recommend having a generic label

I think we should simply return `string.Empty` as `archive name` when no item is selected
