### ISSUE TITLE
File selection jumps arount

### ISSUE THREAD

**Issue by Ealfardan** [files-community/Files#11613]
### Description

When I'm trying to perform multiple edits on files in a folder, the selection jumps around after renaming, deletion, opening files or just changing of focus to another screen. Sometimes it jumps to the top of the list and sometimes to the bottom of the list and sometimes it stays put even though I clicked on another file.

This also happens accross multiple tabs, sometimes I work in tab 1, press delete and a file in tab 2 gets deleted, or I copy files from tab 1, press paste in tab 1 and  they get pasted in tab 2.

This becomes really frustrating if I was attempting to delete a file and the selection jumps to another file. Even while renaming, the file names get messed up.

### Steps To Reproduce

I couldn't figure out how to reproduce this behavior, but it occurs pretty frequently and I couldn't place my finger on its triggers just yet.

### Steps to fix

Store global active selections for the entire instance as . Each instance should store:
1. Selections in each tab
2. Active tab
3. Active selection -- which the selection in active tab

This way any changes the user makes are sure to occur on the active selection all the time.

Also, I would assume that the concepts of "Highlighted", "Active", and "Selected" need to be revisited since this could be the root cause of the issue. Idk

### Files Version

2.4.40.0

### Windows Version

Windows 10 Home Single Language 22H2

### Log file

[debug.log](https://github.com/files-community/Files/files/10921612/debug.log)

https://user-images.githubusercontent.com/93459449/223746676-8bcb6561-1b2d-450f-87dd-200f9d01ddf2.mp4

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by Ealfardan** [comment]
Hi yair100,

Thanks for your prompt fix.

I can't verify if it's fixed in the preview because I get this error message when I try to install the preview version:
```
App installation failed with error message: Appinstaller operation failed with error code 0x80070422. Detail: The service cannot be started, either because it is disabled or because it has no enabled devices associated with it. (0x80070422)
```

**Comment by yaira2** [comment]
I'm pretty sure this will be fixed in the next release, please let us know if it's still an issue then.
