### ISSUE TITLE
Plugins?

### ISSUE THREAD

**Issue by nielsbosma** [files-community/Files#11610]
### What feature or improvement do you think would benefit Files?

	Do you have any plans to allow for the development of plugins?

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

Any

### Windows Version

Any

**Comment by yaira2** [comment]
Files supports shell extensions in the context menu, we don't have plans for any other plugins though.

**Comment by yaira2** [comment]
Is there a plugin that you're looking for?
