### ISSUE TITLE
Improves MultiSelect

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#11618]
### What feature or improvement do you think would benefit Files?

The multi selection is convenient, but not pretty, especially in grid mode.

Here are some suggestions for improving it.
* Hide SelectAll checkbox when folder is empty. It's pretty ugly to see that box checked for an empty folder.
* Put the MultiSelect toggle back in the selection menu. It was very convenient. Other settings are also available in the toolbar menus.
* Associate a hotkey to MultiSelect.
* Show the box only when hovering over the element in grid mode. (If you can't enable/disable it easily).

### Requirements

The command already exists. It can be used in the menu.
You can modify the views (SelectAllCheckBox, Grid).

### Files Version

2.4.49.0

### Windows Version

10.0.22621.1265

### Comments

Useless checkbox
![Empty](https://user-images.githubusercontent.com/46631671/223789020-305fe5e2-26b7-4e94-8349-0af0975bea1c.png)

**Comment by yaira2** [comment]
We're currently working on some drastic changes to the multiselect behavior.

**Comment by yaira2** [comment]
The changes have been merged and are available in v2.4.51.
