### ISSUE TITLE
Support for Tags

### ISSUE THREAD

**Issue by thetek43** [files-community/Files#1161]
**Is your feature request related to a problem? Please describe.**
I really like the Tag feature in the Apple Finder. It would improve my workflow quite a bit, and the default Windows Explorer doesn't have it. Image below:

**Describe the solution you'd like**
- The ability to add Tags to files (and folders) with custom names and custom colors
- Tag list should appear on the sidebar below the drives
- Adding/Removing Tags via right click -> last row of the menu -> circles with colors. When a tag is selected, it should appear with a checkmark.
- Tag color in front of file name

**Describe alternatives you've considered**
There's not many good alternatives to tags... E.g., I could make a Tag for ToDo so that I don't have to write everything in a text file which is pretty annoying.

**Additional context**
Image from the Mac Finder:
![grafik](https://user-images.githubusercontent.com/62657802/85202060-1ca46b80-b304-11ea-9ad8-bdfdc247f0a0.png)
![grafik](https://user-images.githubusercontent.com/62657802/85202073-304fd200-b304-11ea-81b4-a170e816b873.png)

**Comment by Jaiganeshkumaran** [comment]
But how would we store it? We could store the tags in local settings however the user will lose the tags when the app is reinstalled.  We can use roaming settings however that only works for Microsoft account and not local accounts.

**Comment by thetek42** [comment]
By roaming, you probably mean %appdata%, right? Afaik, this is available to local users as well - idk. If not just use a C:/Program Files/Files UWP/Data/ folder or something like that.
It was an idea, I don't know how your app works in the background, so sorry if it is not possible. Would be amazing tho :)

**Comment by Jaiganeshkumaran** [comment]
In Windows 10, there’s a feature that syncs the roaming folder to cloud. It’s intended for apps that need to sync data between Windows devices. We don’t really need to use it since the files and folders are probably local however the roaming folder can also be used to restore data if the app has been reinstalled since we can download the data from the cloud. Users probably want the tags to stay even if the app is reinstalled and I don’t really know a good way to do that. Using Program Files might be a better option however, what if the user reinstalled Windows? Also all of these methods for storing tags aren’t portable. Imagine a file on a USB Thumb Drive. When I apply a tag using Files UWP on my current PC, Files UWP will show the tag on this PC only. If I plug the drive on another PC, the tag won’t be shown since the list of tags in this PC doesn’t contain that file. The only way for this to portable across devices is to embed the data in the file itself. However I don’t know how that would work.

**Comment by thetek42** [comment]
Just looked it up, Windows actually supports tags - they are kind of crappy tho. Check this out: https://www.howtogeek.com/344543/how-to-tag-any-windows-file-for-easy-organization/
Maybe that can be used, but I'm not certain. (Hopefully yes!)

**Comment by Jaiganeshkumaran** [comment]
Thanks for that link. Do you want to store tags as colors or strings? If you want to store colors like macOS, we could store them as a string and interpret it as a color and show it on the screen.

**Comment by thetek42** [comment]
I would rather say strings for easier use with win explorer. Then you could set a color in the settings of FilesUWP. By default, just a random color, which can then be changed.

**Comment by Jaiganeshkumaran** [comment]
@duke7553 Could you assign me to this issue?

**Comment by duke7553** [comment]
@Jaiganeshkumaran I'm thinking we DO NOT want to keep a temporary file with JSON for the flags.

**Rationale:** It is far more efficient to use the [BasicProperties.SavePropertiesAsync()](https://docs.microsoft.com/en-us/uwp/api/windows.storage.fileproperties.basicproperties.savepropertiesasync?view=winrt-19041#Windows_Storage_FileProperties_BasicProperties_SavePropertiesAsync_Windows_Foundation_Collections_IIterable_Windows_Foundation_Collections_IKeyValuePair_System_String_System_Object___) method to associate a color value with the filesystem  [property](https://docs.microsoft.com/en-us/windows/win32/properties/props-system-flagcolor?redirectedfrom=MSDN) of the storage items themselves. 

Side note: This is already built-in to Windows for use in Outlook, we just have to create a UI for it

**Comment by thetek42** [comment]
You could also set the tags to "identifier#RRGGBB with RGB being the color set in the settings.

**Comment by Jaiganeshkumaran** [comment]
@duke7553 Most file properties do persist as long as you have the file in an NTFS volume.

**Comment by Jaiganeshkumaran** [comment]
@thetek42 The main issue is that the built-in tags feature only works with some files instead of all files.

**Comment by Jaiganeshkumaran** [comment]
Comments property works with most files but for others I'm searching for another property

**Comment by Jaiganeshkumaran** [comment]
It's much harder than I originally thought. Although tags are there in Windows, it's for a few file types and it doesn't work with others. Microsoft doesn't provide a good documentation about this so it's not reliable. They are other properties however we shouldn't modify them because it may contain other information and even then they are only available for a few files. To make matters even worse, some files have property locks and Explorer doesn't allow you to change any property of the file so I get an exception.

**Comment by jaigak** [comment]
@yair100 @gave92 Any idea on which property to use for storing tags? I don't get why some properties are only available for some file types although they are generic.

**Comment by gave92** [comment]
@Jaiganeshkumaran I haven't investigated this, I'm not sure if there are properties common to all file types.
As an alternative we could also consider using Alternate Data Streams which would work on all files and folders (but NTFS only).
I'd prefer doing this using file properties though :)

**Comment by Jaiganeshkumaran** [comment]
@gave92 Alternate streams is a great idea but we should wait for #177 to be completed

**Comment by gave92** [comment]
@Jaiganeshkumaran I was looking to alternatives to Alternate streams as you'd need to use the fulltrust process to get them (slow) and they do not persists if copied outside NTFS. Not sure if there's another way though.

**Comment by Jaiganeshkumaran** [comment]
@gave92 It's just colour so perfomance might not be an issue. For other file systems the solution is simple: AppData

**Comment by yaichenbaum** [comment]
> @yaichenbaum @gave92 Any idea on which property to use for storing tags? I don't get why some properties are only available for some file types although they are generic.

fyi @duke7553

**Comment by gave92** [comment]
I'd love to see this feature implemented :)
I did some research and tests on this and I currently found two options:
1) Store tags inside the files with Alternate Data Streams
- Pro: tags will not get lost if the file is moved/renamed/modified as long as the file stays on NTFS
- Pro: fully UWP (I did not know you could read/write ADS from UWP!)
- Con: ADS are not indexed by Windows Search so looking for all files matching a tag would be painfully slow
2) Store tags in a database together with filepath
- Pro: search is super quick
- Con: db is difficult to keep updated if the file is moved/renamed (especially if from Explorer)
-> I found a few ways to alleviate this issue but nothing foolproof

![Immagine 2020-10-18 135810](https://user-images.githubusercontent.com/9673091/96915474-901edb00-14a6-11eb-8848-c48b090ed0a6.png)

**Comment by Jaiganeshkumaran** [comment]
@gave92 We can use ADS and also it doesn't need to be indexed because Windows Search only supports properties.

**Comment by gave92** [comment]
@Jaiganeshkumaran you can actually store properties in ADS. E.g. you can add the standard "comments" property to any kind of file.
Unfortunately as I said this does not help us as those properties will not be indexed :(

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran Are you still planning on working on this issue?

**Comment by jaigak** [comment]
@yair100 Yes

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran That's great! Keep us posted.

**Comment by Jaiganeshkumaran** [comment]
> @Jaiganeshkumaran you can actually store properties in ADS. E.g. you can [add](https://docs.microsoft.com/en-us/windows/win32/stg/ipropertysetstorage-ntfs-file-system-implementation) the standard "comments" property to any kind of file. Unfortunately as I said this does not help us as those properties will not be indexed :(
> 
> So don't you find being unable to search for files matching a tag to be a severe limitation?

Maybe we would have to implement then manually

**Comment by gave92** [comment]
The issue is that for finding all files matching a tag you'd have to scan the entire HDD, load the ADS for each file and check if it has a matching tag ---> tooo slow to make any sense
So you'd have to keep an index of which files has a certain tag:
- using the Windows Search index is apparently not possible because it does index ADS
- using a database inside the app is difficult because you can't keep track if a file is moved/renamed
- any idea???

**Comment by carlosvsilva** [comment]
I am also really looking forward for your implementation of tags/colors I think it's of major importance to Files and user experience in Windows.
I only found this resource as a starting point:
https://en.wikipedia.org/wiki/NTFS#Attribute_lists,_attributes,_and_streams
Maybe other file explorers for Windows which suport colored tags can be looked at to see how they do that at a filesystem level.
Thanks

**Comment by Svk1190** [comment]
I think that using a database along with an audit policy can be helpful. The apparent problem with the database approach is that we won't know when a file is renamed/moved to a different location by using file explorer. To address this problem we can use an audit policy, which tells Windows to keep track of file changes. So whenever we tag a file, auditing would be switched on for that file only. Even if Files is closed, any operations on the tagged file would be logged and made available to Files. Thus Files can update its database the next time it is opened. And after all tags are removed from  file, auditing can be switched off for the untagged file. This can help to persist a tag. 

References:
1) [https://community.spiceworks.com/topic/363079-using-event-viewer-to-track-changes-to-files](https://community.spiceworks.com/topic/363079-using-event-viewer-to-track-changes-to-files)
2) [https://superuser.com/questions/1543894/does-can-windows-10-keep-track-of-file-moves-copies-shortcut-creations](https://superuser.com/questions/1543894/does-can-windows-10-keep-track-of-file-moves-copies-shortcut-creations)
3) [https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/apply-a-basic-audit-policy-on-a-file-or-folder](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/apply-a-basic-audit-policy-on-a-file-or-folder)

**Comment by yaichenbaum** [comment]
@Svk1190 would you like to work on this?

**Comment by Svk1190** [comment]
@yair100 sorry, I am not a developer.

**Comment by gave92** [comment]
You can try out [this branch](https://github.com/files-community/Files/tree/tags_v2) for a working implementation of Tags for Files v1.9. UI is unfinished but:
- You can tag files with a color badge through the context menu
- You can find all files with a tag by searching for "tag:TAGCOLOR" in the search-box (e.g "tag:orange")

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5629.

**Comment by e11world** [comment]
I've just been following this looking for this one feature and not sure if anyone is working on it. I'm a web designer/developer not sure if I can help but would love to see this feature along with an easier implementation of tags in general.

**Comment by yaira2** [comment]
@e11world it's already been added, you can find he latest version of Files on our website https://files.community/download

**Comment by e11world** [comment]
> @e11world it's already been added, you can find the latest version of Files on our website https://files.community/download

I did see it but only 4 of them and no way to add or edit any. Seems merged with tags but they should be different things since tags can be the detailed way of finding items but colors are another quicker way to organize and scan items. I guess needs modifications of how it functions.

**Comment by Josh65-2201** [comment]
You can edit anything about them in Files settings > Tags

**Comment by e11world** [comment]
> You can edit anything about them in Files settings > Tags

Thanks I see it now. Pretty amazing!!
