### ISSUE TITLE
Feature: Add CRC32 and CRC64 options to Hashes tab

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#11622]
### What feature or improvement do you think would benefit Files?

CRC32 and CRC64 are also used as hashes and should be added. Especially, CRC32 is very popular because it is used for the checksum in zip archive entries.

### Requirements

Add options to calculate CRC32 and CRC64 hashes

### Files Version

Dev

### Windows Version

10.0.22621.1265

### Comments

The following may be used to calculate CRCs.
https://learn.microsoft.com/dotnet/api/system.io.hashing?view=dotnet-plat-ext-7.0

**Comment by yaira2** [comment]
The plan is to add support for enabling more hashes, we don't have a design for this yet.

**Comment by hishitetsu** [comment]
I think they could be displayed in the same way as the hash values already implemented.

**Comment by yaira2** [comment]
There are a lot of formats, the idea would be to only calculate the ones the user choose.

**Comment by hishitetsu** [comment]
Yes, so I opened another feature request #11263.
