### ISSUE TITLE
file transfer

### ISSUE THREAD

**Issue by amjaman** [files-community/Files#11629]
### What feature or improvement do you think would benefit Files?

If the files app had a file transfer status GUI similar to windows, it would be a definite replacement for windows explorer

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.4.40.0

### Windows Version

10.0.19045.2673

**Comment by Josh65-2201** [comment]
Files will already transferer files and folders the same as file explorer. If you mean to show the status it's being tracked in ##11524 and #11265. Admin prompt support is tracked here #10422
