### ISSUE TITLE
Feature: Add an option to select hash algorithms to be calculated.

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#11623]
### What feature or improvement do you think would benefit Files?

Since calculating hash values is a heavy process for large files, I think there should be an option to not calculate unnecessary hash values.

### Requirements

Add a menu flyout in the hash page for selecting hash algorithms to be calculated.

### Files Version

Dev

### Windows Version

10.0.22621.1265

**Comment by yaira2** [comment]
@hishitetsu I think we can display a menu flyout in the hash page with a list of options to turn on/off.

**Comment by hishitetsu** [comment]
Like this?
![image](https://user-images.githubusercontent.com/66369541/224189386-08a2478d-32d6-4615-9197-6f1cdde632bf.png)

**Comment by yaira2** [comment]
With a different icon perhaps but that's exactly what I had in mind.

**Comment by hishitetsu** [comment]
OK. I rewrote the requirements.

**Comment by hishitetsu** [comment]
My latest design. Is there a better icon?
![image](https://user-images.githubusercontent.com/66369541/224356599-2c27187b-cd8c-4153-a4fe-16eb03278726.png)

**Comment by yaira2** [comment]
The previous design was cleaner

**Comment by hishitetsu** [comment]
You mean `ToggleMenuFlyoutItem`? That would close the flyout every time I select one so I have tried using `ToggleSwitch`.
Would `ToggleMenuFlyoutItem` still be better?

**Comment by yaira2** [comment]
`ToggleMenuFlyoutItem` design is nicer, you can workaround the closing issue by turning off light dismiss.

**Comment by hishitetsu** [comment]
I found the combination of Click and Closing events prevent the flyout from closing.
Now I need to decide on an icon. Would this be easier to understand?
![image](https://user-images.githubusercontent.com/66369541/224368975-5231cac3-3644-4b94-8504-81d2bbee9176.png)

**Comment by yaira2** [comment]
What about an eye?

**Comment by yaira2** [comment]
Yes
