### ISSUE TITLE
Hide empty drives

### ISSUE THREAD

**Issue by SiRo24** [files-community/Files#11634]
### What feature or improvement do you think would benefit Files?

An option to hide empty drives in the drives-section on the left side (I think File Explorer has this feature).
I've got three hard drives installed in my PC, but for some reason between those drives there is a generic button for "USB-Drive E:".
The folder behind is empty and the hover tooltip shows no info.
I have no partition on any drive with the letter E:
When I insert a USB-drive, it shows up under its own name and partition, but has no tooltip and when I click on the generic E: button, a popup displays with "access denied". 
I also tried a thumb drive with a "normal" FAT partition and a RAW partition, but this RAW partition also shows up even though it is empty.
Would be neat, if those partitions would disappear, to reduce clutter in Files.

### Requirements

- Check if partition is empty before adding it to the drives list being displayed on the left side

### Files Version

2.4.49.0

### Windows Version

Windows 11 22H2 25314.1000

**Comment by yaira2** [comment]
Merging with #10550
