### ISSUE TITLE
Bug: Files returns to parent folder

### ISSUE THREAD

**Issue by SiRo24** [files-community/Files#11638]
### Description

Sometimes when clicking on a link or switching back to another tab, files returns to its parent location.
For example:  link points to or tab contains C:\...\...\...  but Files jumps to C:\
A click on the back arrow or using alt+left brings you back to the folder, you wanted to access.

### Steps To Reproduce

Sadly doesn't happen every time.
1. open link
2. end up at the wrong location

or

1. create tab
2. create another tab
3. do stuff in other tab
4. return to first tab
5. wonder how you got here

The last time the issue occurred to me and is documented in the log file was as I did this:
1. open a folder
2. open downloads folder in a new tab
3. extract downloaded .zip
4. copy extracted folder
5. switch to previous tab
6. end up in a parent folder

### Steps to fix

- Fix returning to top parent folder from shortcuts or tabs

### Files Version

2.4.49.0

### Windows Version

Windows 11 22H2 25314.1000

### Log file

[debug.log](https://github.com/files-community/Files/files/10933817/debug.log)
the error occured around 17:30, so I dont know if the previous entries are even necessary, but here is the log file.

**Comment by yaira2** [comment]
Is this an issue in the stable release?

**Comment by SiRo24** [comment]
I just tested it on 2.4.40.0, which is the latest stable I think, but the issue is still there.
I opened a shortcut pointing to S:\folder\folder\...\ and Files jumped to S:\ , but again when clicking the arrow or alt + left I got to S:\folder\folder\...\.
So basically every time this error occurs, I get redirected to the right path but then instantly get redirected again to the parent folder.

**Comment by yaira2** [comment]
Can you share a screen recording? You can upload the file directly to GitHub.

**Comment by SiRo24** [comment]
https://user-images.githubusercontent.com/80770571/225851631-cb531f56-9f97-4bcc-a3f8-1572584eefdb.mp4

First 2.4.53.0 Preview then 2.4.40.0 Stable

**Comment by yaira2** [comment]
Is the folder location actually changing or just the header in the address bar? (similar to #6111)

**Comment by SiRo24** [comment]
Yes, the folder location and address bar changes.

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
