### ISSUE TITLE
I can not click on item in show more options in contex menu

### ISSUE THREAD

**Issue by Under-Idea** [files-community/Files#11639]
### Description

When you right click and show more options, you are unable to click on item that is in the level of window control buttons

![224093378-1ed73e76-a537-4c60-b82a-eb5f1585fd3a](https://user-images.githubusercontent.com/75729134/224100242-221c35d9-ec5e-4326-8be2-c0228726ff22.png)

_If you have it like I have it in the picture, you will not be able to click on "Open in Terminal"_

### Steps To Reproduce

1. right click
2. click on "show more options"

### Files Version

2.4.40.0

### Windows Version

Windows 10 21H2 19044.2604

**Comment by Josh65-2201** [comment]
Merging with #10823
