### ISSUE TITLE
CI: Should be built in three conditions on Azure Pipeline

### ISSUE THREAD

**Issue by 0x5bfa** [files-community/Files#11649]
### What feature or improvement do you think would benefit Files?

We should build Files in the all conditions (Debug, Release, Store, Preview, Stable) on Azure Pipeline or on GitHub Actions. Even if Azure Pipeline successfully build Files in Debug, the compiler would fail to build in other conditions. Also building time won't be changed by adding further jobs in the Pipeline because you can use Pallalel Jobs (adding up to 10) in public repositories.

- `Files CI` is for the main branch
- `Files PR` is for the PRs

Each one will run in the all conditions: Debug, Release, Store, Preview, Stable. Those conditions will be implemented in pipeline templates

Folder structure
```
.
builds
├─ templates
│  ├─ build-projects.yml
│  ├─ ...
│  └─ ...
├─ ci.yml
└─ pr.yml
```

### Requirements

**Phase 1 (plannning)**

- Create some templates for avoidance of duplication.
- Create generic two Azure Pipelines to run in all conditions; Debug, Release, Store, Preview, Stable. One is for main branch and the other is for PRs.
  - You can test that Pipeline in the PR.
- When that Pipeline become stable, remove existing debug CI in the PR.

**Phase 2 (planning)**

- Use those templates in Release Pipeline as well
  - You can test them in the PR.

**Phase 3 (planning)**
- Move that Pipeline to the GitHub Actions
  - Leave InteractionTests running test task as it is in that Azure Pipeline because there is no test driver on the GitHub Marketplace.

### Files Version

Version 2.0.40

### Windows Version

Windows 11 23H2

**Comment by yaira2** [comment]
I looked into using GitHub actions but it doesn't support Windows Test Driver.

**Comment by onein528** [comment]
I'm still talking about AzurePipeline.

**Comment by yaira2** [comment]
The existing release pipeline should be left as is because the build process is a little complicated and isn't meant to run on PRs. For the testing pipeline, we'll have to add some kind of generic pipeline that allows us to pass a variable with the build configuration.

**Comment by 0x5bfa** [comment]
@yaira2 here's requirements draft. After approved, can you assign me and can you give me an access to the Files Azure Piepline?

### Requirements (draft)

**Phase 1**

- Create some templates for avoidance of duplication.
- Create generic Azure Pipeline to run in all conditions; Debug, Release, Store, Preview, Stable.
  - You can test that Pipeline in the PR.
- When that Pipeline become stable, remove existing debug CI in the PR.

**Phase 2**

- Use those templates in Release Pipeline as well
  - You can test them in the PR.

**Phase 3**
- Move that Pipeline to the GitHub Actions
  - Leave InteractionTests running test task as it is in that Azure Pipeline because there is no test driver on the GitHub Marketplace.
