### ISSUE TITLE
Choose another app isn't working

### ISSUE THREAD

**Issue by ItsjustmeTJ** [files-community/Files#11645]
### Description

Good day everyone,

I'm too am having the same problem with "Choose Another App" not working.

To correct the issue I downloaded the windows 11 image and reinstalled it (pre 22H2) (keeping all apps and settings). When windows 11 came up, "Choose Another App" worked fine.
I then ran system security updates, restarted and again all worked fine.

*However.  to my surprise when I re-plied 22H2 sadly the problem returned. My windows ver is 10.0.22621 Build 22621. Thank you in advance to anyone who can shed some light on this. : )
![200127912-6d790fc3-6c51-4c1e-a264-2ed35651e073](https://user-images.githubusercontent.com/98914359/224155390-4c77211d-7729-44ed-a33e-d70f088ad70e.png)

### Steps To Reproduce

1. Right mouse button on any doc,  i.e. .JPG,  .mpg,  .doc....
2.  Select Open With
3.  Select Choose Another App

After you select Choose Another App,  the window closes instead of giving you an option to choose another app.

### Steps to fix

I was able to fix it by reverting back to pre 22H2.  However, when I reapplied 22H2 the problem returned

### Files Version

Any

### Windows Version

Ver 10.0.22621  Build 22621

### Log file

-na

**Comment by yaira2** [comment]
Some older versions of Windows 11 have this issue but it's not related to Files.
