### ISSUE TITLE
Crashes when too much happening for Files to handle

### ISSUE THREAD

**Issue by BPRTS** [files-community/Files#11642]
### Description

Whenever I quickly try to archive a zip file or quickly check the properties of something, Files freezes and closes pretty much right after. It crashed on both my laptop and desktop, but more often on my laptop.

Laptop Specs:
![image](https://user-images.githubusercontent.com/100706516/224127524-b0a549a4-8e15-4f0e-a4cb-e276ca9bb275.png)

Desktop Specs:
![image](https://user-images.githubusercontent.com/100706516/224127887-0da2dd52-d05d-420d-a4e8-2027ba615c7a.png)

### Steps To Reproduce

1. Open Files (Preview) / Files
2. Select a file and then Right click followed by a quick left click  

!Video has been made on laptop!

https://user-images.githubusercontent.com/100706516/224126159-7f5a2738-88cc-4d06-a230-627649606dd5.mp4

### Steps to fix

I don't the fix for the issue. I know that is less likely to happen on a more powerful computer like my desktop. I did manage to crash it there too but far less often and just in more heavy loaded cases.

### Files Version

2.4.49.0

### Windows Version

Version:22H2 | OS Build 22624.1391 

### Log file

[debug.log](https://github.com/files-community/Files/files/10935120/debug.log)

**Comment by yaira2** [comment]
Can you fill out the "Steps to fix" section? (eg. Fix crash that occurs when...)

**Comment by BPRTS** [comment]
> Can you fill out the "Steps to fix" section? (eg. Fix crash that occurs when...)

I dont exactly know what it mean, cuz I dont know a fix, it just crashes

**Comment by yaira2** [comment]
I think this is specific to the context menu and we're taking several steps to address it. You can expect improvements over the next few updates.
