### ISSUE TITLE
Lags, freezes and sometimes crashes after short use

### ISSUE THREAD

**Issue by imhe6** [files-community/Files#11659]
### Description

I open Files app and operating for less than a minute, then it starts to lag and freeze for a seconds, but mostly gets back to normal; sometimes even crashes (sometimes pop up Windows-level (bottom-right) notification of "Files crashed" and restart, sometimes the app just closes silently).
These only happen when I am operating the app (such as opening directories and click settings button). If I launch an instance and leave it there untouched, there won't be any problem. 

### Steps To Reproduce

- open Files app
- doing operations (in the log I simply switch between two independent directories)
- Lags and freezes start to appear, sometimes the app crash

### Requirements

- Fix the issues of lags and freezes and crashes during use.

### Files Version

2.4.40.0

### Windows Version

Windows 11 22H2 10.0.22621.1265, but also happened on Win11 21H2 before

### Log file

[debug.log](https://github.com/files-community/Files/files/10944900/debug.log)

"replaced-dueto-privacy" in log are the replacements of my Windows username and my OneDrive email (← probably useful: this is very long since OneDrive for Business attached the full domain name to its folder's name)

**Comment by Josh65-2201** [comment]
Can you see if this is an issue in the preview version? https://files.community/download

**Comment by imhe6** [comment]
> Can you see if this is an issue in the preview version? https://files.community/download

I've tried force-deployment for preview version, and in preview version it still freezes sometimes, but seems no longer crash.

**Comment by Josh65-2201** [comment]
What are you doing when it freezes?

**Comment by imhe6** [comment]
> 
[debug.log](https://github.com/files-community/Files/files/10947673/debug.log)

It can happen after any operation (click on settings button, open context menu, goes into a directory...), less frequent but still has. What's more, debug.log doesn't have any sign of error or expectation.

**Comment by imhe6** [comment]
> What are you doing when it freezes?
[debug.log](https://github.com/files-community/Files/files/10947677/debug.log)

It can happen after any operation (click on button, goes into directory...), just less frequent than the main version. debug.log has no sign of error or expectation at all.

**Comment by imhe6** [comment]
> What are you doing when it freezes?

[debug.log](https://github.com/files-community/Files/files/10947681/debug.log)

It can happen after any operation (click on button, goes into directory...), just less frequent than the main version. debug.log has no sign of error or expectation at all.
