### ISSUE TITLE
Deleting items in search doesn't work

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#11650]
### Description

The button will show as disabled and when clicked it will give the something when wrong notification

### Steps To Reproduce

1. search for a file in a folder
2. Select the file
3. Attempt to delete it

### Requirements

?

### Files Version

2.4.50.0

### Windows Version

10.22621.1305

### Log file

[debug.log](https://github.com/files-community/Files/files/10940778/debug.log)

**Comment by ferrariofilippo** [comment]
FYI @cinqmilleans 
Related with #11641 (See `Files.App.Actions.DeleteItemAction`)

**Comment by cinqmilleans** [comment]
It's always been that behavior. I found this out by moving the old code into the command. I reproduced the behavior. To investigate.

**Comment by cinqmilleans** [comment]
If we authorize the deletion of the searched elements, it works (popup then effective deletion). However, the list does not update, the item is still visible (like in FileExplorer).

We can activate the deletion in the search results but by updating the list manually (this will be an added value).
