### ISSUE TITLE
ContextMenu for AddressBar

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#11656]
### What feature or improvement do you think would benefit Files?

Left and right click on the address bar does the same thing, enter edit mode. It's easy to add a context menu with commands specific to the current folder. It's prettier and more intuitive, especially to paste in open a path in a clic (as in Chrome). On mockups, I also put the Favorite icon in the address bar to add/remove in one click (like in a web browser).

### Requirements

- Add a context menu to the address bar.
- Add the Favorite icon to the address bar.

### Files Version

main

### Windows Version

Windows 11

### Comments

![AddressBar1](https://user-images.githubusercontent.com/46631671/224366741-0733b402-6c1f-476c-831b-09e5ad8005f8.png)
![AddressBar2](https://user-images.githubusercontent.com/46631671/224366743-cf11d3ff-1ed0-4ecc-a5a0-8b224b59bf83.png)

**Comment by yaira2** [comment]
This is really two separate tasks, replacing the chevron/arrow with an actionable button for pinning/unpinning is fine with me. As for the right click menu, it should be limited to copy and paste.
