### ISSUE TITLE
Cannot locate another directory when renaming file

### ISSUE THREAD

**Issue by KenCheungGameDesinger** [files-community/Files#11651]
### Description

as title

### Steps To Reproduce

click file
renaming(highlighting the file name)
turn to other directory, e.g. go to desktop/download/whatever drives
then the app shows error message

### Requirements

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

Application_Form_Interns (1)

### Windows Version

Windows 11 22H2

### Log file

[debug.log](https://github.com/files-community/Files/files/10941624/debug.log)

**Comment by Josh65-2201** [comment]
What Files version are you on?

**Comment by KenCheungGameDesinger** [comment]
2.4.40.0

「Josh65-2201 ***@***.***>」在 2023年3月10日週五，下午8:49 寫道：

**Comment by Josh65-2201** [comment]
Can you see if this is an issue in the preview version? https://files.community/download

**Comment by yaira2** [comment]
@KenCheungGameDesinger

**Comment by KenCheungGameDesinger** [comment]
This might be a preview version, since I didn't download it from the
Microsoft Store.

Below is my version number for your reference：
App version: 2.4.40.0
Windows version: 10.0.22621.1413
[image: image.png]

Yair ***@***.***> 於 2023年3月17日 週五 上午11:09寫道：

**Comment by Josh65-2201** [comment]
Thats not the preview. Use the link above and click the one that says preview

**Comment by yaira2** [comment]
This appears to be resolved in the latest preview build.

**Comment by KenCheungGameDesinger** [comment]
Thanks!

「Yair ***@***.***>」在 2023年3月29日週三，下午10:06 寫道：
