### ISSUE TITLE
Directory tree view on the left side panel (Navigation pane in File Explorer)

### ISSUE THREAD

**Issue by imhe6** [files-community/Files#11662]
### What feature or improvement do you think would benefit Files?

I am used to the directory tree pane on the left side of File Explorer (also known as Navigation pane). It can be set (disabled by default) to expand to your current directory as well as all its parent directories, so it is convenient for jumping between directories. Also it displays the subfolder of some internal user directory such as OneDrive, removable devices and some frequently-visited folders (←showed by File Explorer automatically, not those manually pinned) so users can directly open them.
Files app also has left panel to opening directories, however it is fixed by setting and never changes during use. Thus the panel mostly serve as fixed shortcuts list rather than directory navigator. Since the app's home screen has mostly the same shortcuts, I rarely use left panel.
That's why I wonder Files app can have a kind of explorer "navigation pane"  in left panel. There are many people (at least my friends and colleagues) used to the navigation pane, so this features could be helpful to many users.

### Requirements

A directory tree pane that most functions are same as "navigation pane" of File Explorer:
- Can expand to current directory, expanding its parents as well
- Can show some system-specified user folder (and subfolder) such as OneDrive and its first-level subfolders
- Can automatically recommend frequently-used folders in "Favorites" (This sounds more like a feature request for Favorites...)
- Other behaviors of File Explorer's "navigation pane"

### Files Version

2.4.50.0 (Preview)

### Windows Version

Windows 11 22H2 10.0.22621.1265

**Comment by MalteTasler** [comment]
Tree view is being tracked in this issue: #1928

**Comment by yair100** [comment]
@imhe6 Tree View is currently available in preview https://files.community/download. It will be included in the next stable release.
