### ISSUE TITLE
Bug: Tying to select file is crashing app

### ISSUE THREAD

**Issue by ciao1092** [files-community/Files#11660]
### Description

(sometimes) The app will crash when typing in the folder list view.

### Steps To Reproduce

1. Open the app
2. Open C:
3. Switch to the column layout
4. Start writing in the list view to search a folder
5. The app will crash

### Requirements

- Fix crash that occurs when typing directly in list view to search for files/folders

### Files Version

2.4.40.0

### Windows Version

Windows 11 22H2 build 22624.1391 (10.0.22624.1391)

### Log file

[debug.log](https://github.com/files-community/Files/files/10945949/debug.log)

**Comment by Josh65-2201** [comment]
Can you see if this is an issue in the preview version? https://files.community/download

**Comment by ciao1092** [comment]
Hello. I will do some more testing, but in the preview version it seems it's not happening. Closing this

**Comment by yaira2** [comment]
@ciao1092 can you check in v2.4.53?

**Comment by ciao1092** [comment]
Just happened. I will soon upload a log.

**Comment by ciao1092** [comment]
**Files version: v2.4.53**
**Windows Version: Microsoft Windows [Version 10.0.22624.1391] (Windows 11)
[debug.log](https://github.com/files-community/Files/files/11001908/debug.log)

**Comment by yaira2** [comment]
How many items are in the folder?

**Comment by ciao1092** [comment]
Around 50, I think 47

**Comment by yaira2** [comment]
Is it specific to `c:\`?

**Comment by ciao1092** [comment]
Yeah, it seems...

**Comment by yaira2** [comment]
@Spid3rrr are you able to repro it?

**Comment by Spid3rrr** [comment]
It appears to be running okay on preview, stable and my dev branch so far. I can't seem to reproduce it. Anyone else ?
