### ISSUE TITLE
Bug: Tags in columns view crashes application

### ISSUE THREAD

**Issue by thymaro** [files-community/Files#11674]
### Description

Trying to open a tag when columns view is the standard viewing mode will crash the application every time.

### Steps To Reproduce

1. Open settings
2. go to 'folders'
3. go to 'layout mode'
4. choose 'columns'
5. close settings
6. go to any file on system
7. right-click on file
8. assign tag to file
9. in the left panel, where you can click on favorites, drives, etc., click on the tag you just assigned
10. the application will crash right after the click, not displaying the content of the tag

### Requirements

- Fix crash that occurs when trying to display all files assigned to a certain tag after setting the standard display mode to 'columns'

### Files Version

2.4.50.0

### Windows Version

10.0.19044.2604

### Log file

[debug.log](https://github.com/files-community/Files/files/10949373/debug.log)

**Comment by ferrariofilippo** [comment]
@yair100 should we open tag search results in `DetailsLayout` or should we implement it for `ColumnsView`? In the latter case we should support opening `Home` in `ColumnShellPage`

**Comment by yaira2** [comment]
The former, Column Layout should never display search results.
