### ISSUE TITLE
Bug: Files crashes when item is selected and tab is switched

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#11671]
### Description

*

### Steps To Reproduce

1. Open two tabs
2. Select an item in either
4. Switch tab
5. Files crashes

### Requirements

- Fix crash when switching tabs with a selected item

### Files Version

2.4.50.0

### Windows Version

10.0.22621.1344

### Log file

[debug.log](https://github.com/files-community/Files/files/10948841/debug.log)

**Comment by QuaintMako** [comment]
Might be linked to #11666

**Comment by Josh65-2201** [comment]
The issue was fixed for me with the linked pull request
