### ISSUE TITLE
In Whatsapp Windows Store version, Drag And Drop files into a conversation doesn't work

### ISSUE THREAD

**Issue by davidcc73** [files-community/Files#11686]
### Description

Files dragged from the Files program into a WhatsApp conversation do trigger the windows mouse loading icon and then it goes away without adding the file to the conversation like File Explorer Does.

### Steps To Reproduce

In the WhatsApp Windows Store App, open a conversation and drag a file from the Files window into a conversation, the file should be added to the conversation like in File Explorer, but that does not happen.

### Requirements

When a File is dragged from the Files program into a WhatsApp conversation that file should be added to the conversation just like File Explorer Does.

### Files Version

2.4.40.0

### Windows Version

Windows 11 22H2 10.0.22621.1344

### Log file

[debug.log](https://github.com/files-community/Files/files/10951689/debug.log)

**Comment by yaira2** [comment]
Merging with #10171
