### ISSUE TITLE
drag and drop makes Files crash

### ISSUE THREAD

**Issue by antho686** [files-community/Files#11698]
### Description

When I lauch the Files explorer from Git bash and then try to drag and drop, Files crashes and closes.

### Steps To Reproduce

open a git bash terminal, navigate to any folder and open files using the command ``start .`
Then try to drag a folder, Files crashes at this moment.

### Requirements

- If I start Files from elsewhere, the drag and drop function doesn't make the app crash
- Using Windows 11 Pro, version 22H2, build: 22621.1265 with Windows Feature Experience Pack 1000.22638.1000.0

### Files Version

2.4.40.0

### Windows Version

Windows 11 Pro 22H2 22621.1265 Windows Feature Experience Pack 1000.22638.1000.0

### Log file

[debug.log](https://github.com/files-community/Files/files/10958713/debug.log)

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by yaira2** [comment]
@antho686

**Comment by antho686** [comment]
Trying it right away

**Comment by antho686** [comment]
So this issue isn't happening anymore with the new version, thanks a lot!
