### ISSUE TITLE
I pressed Win+E and got a message with error.

### ISSUE THREAD

**Issue by yanivg101** [files-community/Files#11695]
### Description

I don't know what happen, just got this error message

### Steps To Reproduce

Maybe it because of the Win+E? I don't know.

### Requirements

I don't know how to fix.

### Files Version

2.4.51.0

### Windows Version

10.0.19045.2604

### Log file

[debug.log](https://github.com/files-community/Files/files/10957471/debug.log)

**Comment by Josh65-2201** [comment]
This has been fixed and will be in the next update
