### ISSUE TITLE
Bug: Generating new name for conflict is appending "copy" instead of a number "(#)" 

### ISSUE THREAD

**Issue by bckncook** [files-community/Files#11697]
### What feature or improvement do you think would benefit Files?

When I move or copy a file from one folder to another folder that already contains a file with the same name, and I would like to keep both, I would like the option for it to append " (#)" to the file (like Windows) instead of "- Copy" when I select Generate New Name. 

If it were the same file, I would almost always choose Replace or Skip, not Keep Both (aka Generate New Name), so when I choose to keep both, it is almost always because it isn't the same file, and therefore is not a copy, but an additional item with the same name.

### Requirements

- [ ] When copying and pasting items within the same folder, "- copy" should be appended (as is File Explorer)
- [ ] When copying and pasting item from a different folder, selecting generate new name from the conflict modal should append a number (as in File Explorer)

### Files Version

2.4.40.0

### Windows Version

Windows 11 22H2 22623.1020

**Comment by yaira2** [comment]
When you select the option to generate a new name, you can click the text box and change the name.

**Comment by bckncook** [comment]
This gave me hope, but when I tried it, it is not at all what I'm talking about.  Not only does the naming method not stick, but it doesn't create the appropriate index number either, so in addition to still having to rename every file manually, I also have to figure out what its index number would be in advance, which is even harder than letting it stick "-Copy" on all of them and then manually going to the folder, pasting the same file name on all the items in a set that should have the same name, and THEN letting it automatically give them appropriate index numbers.

**Comment by Jay-o-Way** [comment]
Not trivializing the issue - I get it - but can say that, _after_ the copy action, Explorer does allow to rename multiple files at once and it will then add the auto number.

Besides that - if you often need to rename many files in one action, you might want to use Power Rename (part of PowerToys) if you don't already.

**Comment by bckncook** [comment]
Yes, the entire second half of my previous post was about doing it _after_ the copy action, but I do it often enough that I need it to happen in one swoop _during_ the copy action... so the better answer is _definitely_ not to open a separate app every time instead - that's even worse - when I can continue to just accomplish this easily and natively in Windows.  Will check in on Explorer's progress again in a few months and if any attempts to remedy this have been made, I'll install and try it again.

**Comment by yaira2** [comment]
This is indeed a bug

**Comment by yaira2** [comment]
In File Explorer, copying and pasting an item in the same directory will also append "- copy). But if you copy the item from another folder and paste it, it'll prompt you to compare the info, if you select the option to keep both it'll only append a number.

**Comment by bckncook** [comment]
Not sure I understand the reason for this reply. It seems only to restate the premise of the thread.  i.e., yes, this I is how I would need Files to work as well in order to adopt it as a replacement for Files Explorer.  Thanks.

**Comment by yaira2** [comment]
It's just an observation that File Explorer has a similar behavior in one scenario.

**Comment by bckncook** [comment]
Sure, there are lots of scenarios where Files behaves similarly to File Explorer (and looks better doing it), but just like the other scenario you mentioned, they too are completely unrelated to the request at hand... lol. ;)

**Comment by yaira2** [comment]
This issue will be resolved in the next release.
