### ISSUE TITLE
File action are disabled for first tab when multiple tabs are open

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#11701]
### Description

I've had this happen multiple times but only in the first tab. Actions like cut, copy, paste, delete, Add to favorites and add to archive are disabled for all items in any folder.

### Steps To Reproduce

1. Open two tabs
2. Navigate to two directories in each tab
3. Attempt to take an action in the first tab
4. See described options are disabled

### Requirements

- Make sure all allowed actions are enabled in the context menu and toolbar

### Files Version

2.4.51.0

### Windows Version

10.0.22621.1344

### Log file

[debug.log](https://github.com/files-community/Files/files/10960195/debug.log)

**Comment by hishitetsu** [comment]
@yair100 Isn't it ready to build? It doesn't occur in 2.4.40.0, so it may be a regression caused by RichCommand.

**Comment by yaira2** [comment]
Yes

**Comment by cinqmilleans** [comment]
I'm taking care of it.
