### ISSUE TITLE
Can't create a folder using

### ISSUE THREAD

**Issue by davidcc73** [files-community/Files#11700]
### Description

When using the program the option to create a folder is available, but when the mouse moves over it, it's color does not change, and pressing it does not do anything.

Mouse over 2º Option (Ficheiro means File)
![Captura de Ecrã (140)](https://user-images.githubusercontent.com/68875095/224765990-1e741187-38a3-452d-89a9-a459294057ba.png)

Mouse over 1º Option (Pasta means Folder) has it can be seen the interface does not react to the mouse
![Captura de Ecrã (141)](https://user-images.githubusercontent.com/68875095/224766010-4e7a3d68-8bf3-4584-9143-373ecb3e257e.png)
its

### Steps To Reproduce

1-Go to Files
2-Go inside any Folder
3-Right Click inside it
4-Select New
5-Then Try to select Folder

### Requirements

A Folder is created when clicking "folder" inside de sub-menu "New"

### Files Version

2.4.40.0

### Windows Version

10.0.22621.1344

### Log file

[debug.log](https://github.com/files-community/Files/files/10959486/debug.log)

**Comment by Josh65-2201** [comment]
Merging with #10823

**Comment by yaira2** [comment]
@Poker-sang this is another title bar drag region, what are your thoughts on disabling the drag region when the context menu is opened?
