### ISSUE TITLE
Preview version crashes after a few seconds within opening it

### ISSUE THREAD

**Issue by lianesilva** [files-community/Files#11703]
### Description

Hi,

Just trying the app out for the first time, so I installed the Preview version. When opening Files Preview, it simply crashes within 5 seconds. Tried opening it normally and as Admin, and it keeps happening.

### Steps To Reproduce

1. Open app
2. Wait around 5 seconds

### Requirements

- eg. Fix crash that occurs when opening the app

### Files Version

2.4.51.0

### Windows Version

Windows 10 21H2

### Log file

Stopping CCS Services at 23:06:07.65 on 18/06/2022  Silva\AppData\Roaming\Avid_CCS_Service_Stop.log
  Silva\AppData\Roaming\Avid_CCS_Service_Stop.log
*************** AvidHubService ***************  Silva\AppData\Roaming\Avid_CCS_Service_Stop.log
23:06:07.72 ## Service Not Installed  Silva\AppData\Roaming\Avid_CCS_Service_Stop.log
  Silva\AppData\Roaming\Avid_CCS_Service_Stop.log
*** AvidHubService Stopped at 23:06:07.72 ****  Silva\AppData\Roaming\Avid_CCS_Service_Stop.log
  Silva\AppData\Roaming\Avid_CCS_Service_Stop.log
*************** AvidTransportClient ***************  Silva\AppData\Roaming\Avid_CCS_Service_Stop.log
23:06:07.74 ## Service Not Installed  Silva\AppData\Roaming\Avid_CCS_Service_Stop.log
  Silva\AppData\Roaming\Avid_CCS_Service_Stop.log
*** AvidTransportClient Stopped at 23:06:07.75 ****  Silva\AppData\Roaming\Avid_CCS_Service_Stop.log
  Silva\AppData\Roaming\Avid_CCS_Service_Stop.log
*************** AvidAssetCacheService ***************  Silva\AppData\Roaming\Avid_CCS_Service_Stop.log
23:06:07.77 ## Service Not Installed  Silva\AppData\Roaming\Avid_CCS_Service_Stop.log
  Silva\AppData\Roaming\Avid_CCS_Service_Stop.log
*** AvidAssetCacheService Stopped at 23:06:07.78 ****  Silva\AppData\Roaming\Avid_CCS_Service_Stop.log
  Silva\AppData\Roaming\Avid_CCS_Service_Stop.log
*************** AvidAssetDeliveryService ***************  Silva\AppData\Roaming\Avid_CCS_Service_Stop.log
23:06:07.80 ## Service Not Installed  Silva\AppData\Roaming\Avid_CCS_Service_Stop.log
  Silva\AppData\Roaming\Avid_CCS_Service_Stop.log
*** AvidAssetDeliveryService Stopped at 23:06:07.80 ****  Silva\AppData\Roaming\Avid_CCS_Service_Stop.log
  Silva\AppData\Roaming\Avid_CCS_Service_Stop.log
*************** AvidProjectSyncService ***************  Silva\AppData\Roaming\Avid_CCS_Service_Stop.log
23:06:07.82 ## Service Not Installed  Silva\AppData\Roaming\Avid_CCS_Service_Stop.log
  Silva\AppData\Roaming\Avid_CCS_Service_Stop.log
*** AvidProjectSyncService Stopped at 23:06:07.83 ****  Silva\AppData\Roaming\Avid_CCS_Service_Stop.log
Script Complete at 23:06:07.83  Silva\AppData\Roaming\Avid_CCS_Service_Stop.log

**Comment by yaira2** [comment]
Is this still an issue in the latest preview version? https://files.community/download/preview

**Comment by yaira2** [comment]
@lianesilva

**Comment by lianesilva** [comment]
Hi,


Sorry, I thought I had replied. Its not happening to me anymore, so it's
all fixed, thank you!
