### ISSUE TITLE
Error when going back after seaching files in home directory

### ISSUE THREAD

**Issue by JiaChen-Zeng** [files-community/Files#11709]
### Description

![image](https://user-images.githubusercontent.com/3676278/224888208-d9b9381f-848b-4c93-9751-8c04b58244b1.png)

### Steps To Reproduce

1. Open Home directory
2. Search "abc"
3. Double click the empty space
4. You see the error message

### Requirements

Make double click to exit the search and prevent the error.

### Files Version

2.4.40.0

### Windows Version

10.0.19044.2604

### Log file

[debug.log](https://github.com/files-community/Files/files/10963961/debug.log)

**Comment by hishitetsu** [comment]
I'll fix it.
