### ISSUE TITLE
Make the region to interact with files smaller and leave space to for interacting with current directory

### ISSUE THREAD

**Issue by JiaChen-Zeng** [files-community/Files#11707]
### What feature or improvement do you think would benefit Files?

Currently I don't know (or hard to know and unintuitive) how to right click on the current directory when the files fill up the UI, leaving no empty space. I hope there will be an option to leave some space out for this purpose. For example in QTTabbar, we can configure it in a way where we can only click in the name column and there is plenty of place left.

![image](https://user-images.githubusercontent.com/3676278/224881852-36997978-fb89-420d-be9a-d923f2212bdf.png)

### Requirements

- This proposal will accomplish easy interaction with the current directory

### Files Version

2.4.40.0

### Windows Version

10.0.19044.2604

**Comment by yaira2** [comment]
There is extra space on the left

**Comment by JiaChen-Zeng** [comment]
Do you mean here?
![image](https://user-images.githubusercontent.com/3676278/224882695-c2dcd700-ce2a-4277-ad55-f5213d9b0e25.png)

**Comment by yaira2** [comment]
Lower down, to the left of the icons.

**Comment by JiaChen-Zeng** [comment]
Or maybe just add a button on the menu bar for more options on the directory

**Comment by JiaChen-Zeng** [comment]
This place? I think this would be too narrow to click though. The left top region is good for me but I think people won't recognize we can click on it
![image](https://user-images.githubusercontent.com/3676278/224883122-114b7517-4e8f-45c3-a697-97dcdc32c429.png)

**Comment by yaira2** [comment]
It hasn't been a problem so far but we can reevaluate if it becomes one.

**Comment by JiaChen-Zeng** [comment]
Personally it's a big issue for me. It prevents me from double clicking to exit the current directory
