### ISSUE TITLE
Bug: Context menu clipped by the edge of window

### ISSUE THREAD

**Issue by Poker-sang** [files-community/Files#11713]
### Description

Context menu flyouts could be clip by the edge of the window, when they are placed at the top/bottom of the window, or simply be taller than the window.

![O@LKL3D@ZZ3LHIRQON70FMD](https://user-images.githubusercontent.com/62325494/224932588-08cdb6a2-d820-46b9-9fbb-024a065a2a64.png)

![@0`B(SYD7KO7XDSZBFUAU R](https://user-images.githubusercontent.com/62325494/224932663-e8bd4f13-d3c7-4172-837b-f45c29cffe6e.png)

### Steps To Reproduce

Resize the window and right tap anywhere.

### Requirements

Fix the bug by limiting the height of the menu or any other ways.

### Files Version

2.0.36.0

### Windows Version

Windows11 22H2 22621.1265

### Log file

[debug.log](https://github.com/files-community/Files/files/10965595/debug.log)

**Comment by yaira2** [comment]
This is a WinAppSdk limitation

**Comment by Poker-sang** [comment]
But Gallery's flyouts would collapse automatically, which looks better I thought?

![image](https://user-images.githubusercontent.com/62325494/225034175-d5d790f1-5358-4900-8da9-aa2221c9b51b.png)

**Comment by yaira2** [comment]
Which property controls that? It might not be available for the command bar flyout.

**Comment by Poker-sang** [comment]
> Which property controls that? It might not be available for the command bar flyout.

Seems you are right. And the issue is caused by `CommandBarFlyout.Placement`. when it is set to `Full`, the `CommandBarFlyout` would exceed the lower boundary of the window
![O@LKL3D@ZZ3LHIRQON70FMD](https://user-images.githubusercontent.com/62325494/224932588-08cdb6a2-d820-46b9-9fbb-024a065a2a64.png)

And whatever the value is, it might exceed the left or right boundary. We may have to set Placement to Left or Right manually to fix this bug.

**Comment by Lukiluc29** [comment]
I too am having a similar problem. For example, when I want to remove the "Tags" category the drop-down menu shows only part
![Capture d’écran (10)](https://github.com/files-community/Files/assets/128183422/fb92f3e5-feb5-446d-be6b-5da0ff8b93cc)

**Comment by hishitetsu** [comment]
It is now fixed by WASDK 1.4.

**Comment by Poker-sang** [comment]
@hishitetsu  Thanks! Can you link if you are convenient?
