### ISSUE TITLE
Bug: Freezes when opening a ZFS drive

### ISSUE THREAD

**Issue by DjalimSimaila** [files-community/Files#11722]
### Description

Files hangs when I try to navigate inside a zfs, it stop responding and cant be killed by the task manager. The drive I try to open is a zfs dataset (and the only zfs dataset) on a SD card formated on a arch linux machine, as zfs isn't supported by windows, I use the windows port of the openZFS drive found [here](https://github.com/openzfsonwindows/openzfs/releases).
The odd part is that classic Explorer.exe can open the drive just fine as any other software ( I was expecting bugs as the driver is bit hacky but Files is the only program I have problems with yet)

### Steps To Reproduce

I created the drive on a archlinux system with the following commands
- ```zpool create SharedStorage /dev/disk/by-id/mmc-SD256_0x550c28ec```
- ```zfs create SharedStorage/main```

I run the following commands to mount my zfs pool in windows
1. Import the pool with the command ```zpool import -f {poolToImport}``` 
   In my case its ```zpool import -f SharedStorage```
2. Set the driveletter attribute of the dataset you're trying to mount.
   My dataset is called 'main' so its ```zfs set driveletter=Q SharedStorage/main```
3. Mount the dataset so it is available for the system
   ```zfs mount SharedStorage/main```

Then I just try to open the drive in Files as I would do for any other drives

1. Open Files
2. Click on the drive "SharedStorage/main (Q:)" under the drive category
then it freezes

### Requirements

- Fix crash that occurs when opening a ZFS drive

### Files Version

2.4.40.0

### Windows Version

Win 11 10.0.22621.1265

### Log file

[debug.log](https://github.com/files-community/Files/files/10973609/debug.log)

**Comment by yaira2** [comment]
@DjalimSimaila thank you for your feedback.

**Comment by heftymouse** [comment]
I tried reproducing it on ZFS for Windows 2.2.0rc5 by creating a pool from Windows itself on a VHD, and it seems to work fine. Does this issue only occur for drives created on Linux?

**Comment by yaira2** [comment]
@DjalimSimaila
