### ISSUE TITLE
Code Quality: Move to `SettingsControls`

### ISSUE THREAD

**Issue by Poker-sang** [files-community/Files#11727]
### Description

There is a library that implement about `SettingsCard`/`SettingsExpander`: [CommunityToolkit.Labs.WinUI.SettingsControls](https://github.com/CommunityToolkit/Labs-Windows).
What about move to SettingsControls?

Appearance (arrow icon of Files is smaller, and there is no background color for arrow button):
<img width="351" alt="7~YIOGE N7 C`HWXZN7U7{D" src="https://user-images.githubusercontent.com/62325494/225278357-f9874613-94e7-497d-a8de-20271fe3806b.png">

### Concerned code

The code under namespace `Files.App.UserControls.Settings`

### Gains

- Less code and low coupling.
- No need to maintain code about SettingsControls.
- Better appearance.

### Requirements

- Using library [CommunityToolkit.Labs.WinUI.SettingsControls](https://github.com/CommunityToolkit/Labs-Windows)

**Comment by yaira2** [comment]
The control isn't officially stable yet, our plan is to wait for it to be officially released outside of labs before adopting it.

**Comment by yaira2** [comment]
@Poker-sang is there an issue on the Toolkit where we can track the progress and see when this will be moved to their regular Nuget feed?

I'm also wondering if there is any benefit in using their control when we can just use our own and make modifications as needed.

**Comment by Poker-sang** [comment]
@yair100 Seems like it will be moved to ToolKit 8.0 according to [this](https://devblogs.microsoft.com/ifdef-windows/announcing-the-windows-community-toolkit-labs/#future).

If there is any benefit, it's that we don't have to maintain the controls as much and still get a good performance. Of course, reducing the source code is also one of the benefits.

**Comment by yaira2** [comment]
> If there is any benefit, it's that we don't have to maintain the controls as much and still get a good performance. Of course, reducing the source code is also one of the benefits.

It depends, if we had to choose between creating a new control or using an existing solution, I'd use the existing solution. But in this case, we have something custom built that not only works well, but we have complete control over it and don't need to use another dependency.

**Comment by Poker-sang** [comment]
You also have a point, so let's maintain the status quo

**Comment by yaira2** [comment]
If there is ever a compelling reason to switch, it shouldn't be that hard to do so.
