### ISSUE TITLE
Library and OneDrive Personnal Vault

### ISSUE THREAD

**Issue by TLImpala** [files-community/Files#11721]
### Description

When clic on a library which contains a folder of the Onedrive Personnal Vault...

If the Personnal Vault is closed, we have a message box in Files which is annoying.

If the Personnal Vault is open, no problem, the contents is displayed

![image](https://user-images.githubusercontent.com/92330945/225104292-21eb699f-e6b6-48c4-8dbb-b56743b412e3.png)

### Steps To Reproduce

Go to Library
Clic on a library which contains a Folder of the Onedrive Personnal Vault

The other folder sources are displayed and a message appears when the Onedrive Personnal Vault folder is treated.

### Requirements

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

Do not display the message

Only not display the closed Onedrive Personnal Vault folder contents.

### Files Version

2.4.40.0

### Windows Version

10.0.22621.1413

### Log file

[debug.log](https://github.com/files-community/Files/files/10972656/debug.log)

**Comment by yaira2** [comment]
Personal vault isn't supported right now
