### ISSUE TITLE
No favorites or quick access

### ISSUE THREAD

**Issue by Scouser0001** [files-community/Files#11734]
Cannot pin anything to the favorites, and nothing shows in quick access

**Comment by Josh65-2201** [comment]
Thanks for the feedback. Please make a new issue following the issue templates. It tells you how to fill it out if you don't know what to put for a section.

**Comment by Josh65-2201** [comment]
This is likely the same as #11529

**Comment by Scouser0001** [comment]
Yes my issue looks to be the same as #11529 except I am still on win10. As in the recorded case it is the same on the stable and the beta version
