### ISSUE TITLE
Bug: Pasting rar file crashes app when copying from VMware

### ISSUE THREAD

**Issue by bf3dying** [files-community/Files#11748]
### Description

从VMware 16.2 虚拟机中复制了文件,然后在Files 文件中粘贴,粘贴不了

### Steps To Reproduce

1.安装VMware 虚拟机,然后安装windows操作系统
2.选择虚拟机 中windows 系统任意一个文件,右键点击复制
3.到Files 中点击粘贴就报这个错了,在windows 系统默认的文件夹管理器中,粘贴是可以的.

### Requirements

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

2.4.40.0

### Windows Version

Win11

### Log file

2023-03-17 10:07:00.7804|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-03-17 10:07:00.7990|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-03-17 10:07:00.8127|INFO|GetDrivesAsync|Drive added: E:\, Fixed
2023-03-17 10:07:00.8285|INFO|GetDrivesAsync|Drive added: F:\, Fixed
2023-03-17 10:07:01.8753|INFO|IsRunningOnArm|Running on ARM: False
2023-03-17 10:07:02.8939|INFO|CheckForUpdates|STORE: Checking for updates...
2023-03-17 10:26:52.7938|INFO|OnActivated|App activated. Activated args type: ProtocolActivatedEventArgs
2023-03-17 11:02:02.1717|INFO|OnActivated|App activated. Activated args type: ProtocolActivatedEventArgs

**Comment by bf3dying** [comment]
YES,This issue was encountered in the latest version

If there are environmental tests, you should also encounter this problem.



bf3dying
 
From: Yair
Date: 2023-03-17 11:10
To: files-community/Files
CC: bf3dying; Author
Subject: Re: [files-community/Files] File paste failed (Issue #11748)
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by yaira2** [comment]
Which build number? We made some improvements that should help.

**Comment by yaira2** [comment]
@bf3dying

**Comment by bf3dying** [comment]
> Which build number? We made some improvements that should help.
程序版本：2.4.61.0 （10.0.22621.1485）
操作系统版本：Windows 11 专业版   （22621.1485）

**Comment by bf3dying** [comment]
> Is this still an issue in the preview version? https://files.community/download/preview
预览版本也存在同样问题。

**Comment by yaira2** [comment]
Can you fill out the requirements for the expected behavior?

**Comment by bf3dying** [comment]
> @bf3dying does the app crash when you try pasting the content?


Will not crash, only an error indicating replication failure，
I just tested again and it seems that only RAR reported an error. Copying files in other formats, such as txt and XML, was successful. I don't know why!

![2023-04-24_162135](https://user-images.githubusercontent.com/33117233/233941777-7be523ef-d8f0-45b7-835b-a275bcc495b1.jpg)

**Comment by yaira2** [comment]
@bf3dying thanks for the response, can you do me a favor and upload the log file after this issue occurs again?
