### ISSUE TITLE
Feature: Keep FilesLauncher.exe up to date on users devices

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#11746]
### What feature or improvement do you think would benefit Files?

Whenever we make changes to the FilesLauncher file, existing users need to toggle the default file manager setting off and on for it to apply. Automatically updating this file will make sure users always have the latest improvements.

### Requirements

- Keep the FilesLauncher.exe up to date when users update Files

### Files Version

v2.4.40

### Windows Version

Windows 11

**Comment by hishitetsu** [comment]
How about checking FilesLauncher.exe in LocalAppData at startup and replacing it if the binary has been updated?

**Comment by yaira2** [comment]
By comparing the hash?

**Comment by hishitetsu** [comment]
Yes
