### ISSUE TITLE
random crash

### ISSUE THREAD

**Issue by nemson-source** [files-community/Files#11754]
### Description

a random crash

### Steps To Reproduce

i dont know how it happend

### Requirements

Fix crash 
i dont know how it happend

### Files Version

2.4.40.0

### Windows Version

10.0.19045.2728

### Log file

[debug.log](https://github.com/files-community/Files/files/11004833/debug.log)

**Comment by nemson-source** [comment]
a new crash
[debug.log](https://github.com/files-community/Files/files/11006062/debug.log)

**Comment by nemson-source** [comment]
a new crach
[debug.log](https://github.com/files-community/Files/files/11009467/debug.log)

**Comment by Josh65-2201** [comment]
You don't need to keep uploading a log on every crash. What where you doing when it crashed?

**Comment by Josh65-2201** [comment]
Can you also see if this is an issue in the preview version? https://files.community/download

**Comment by nemson-source** [comment]
its with the preview version (latest github release)
it happens randomly

**Comment by Josh65-2201** [comment]
GitHub is not the preview builds its the stable ones

**Comment by nemson-source** [comment]
ok then its the sable one i got it from git hub

**Comment by Josh65-2201** [comment]
Can you try using the preview one. You can get it from the link above

**Comment by nemson-source** [comment]
ok i will poste if it crash again

**Comment by nemson-source** [comment]
for now no crash but multiple warnings in the log file

**Comment by nemson-source** [comment]
hi
it happend again
here is the
[debug.log](https://github.com/files-community/Files/files/11011035/debug.log)
 log file

**Comment by nemson-source** [comment]
i switcht back to stable

**Comment by nemson-source** [comment]
it was in the background
