### ISSUE TITLE
Able to rename Favorites without having to rename folder names?

### ISSUE THREAD

**Issue by madmuffinz** [files-community/Files#11757]
### What feature or improvement do you think would benefit Files?

As the title says, I would have some favorite folders with generic names that would be the same based on how I sort my folders. If I could rename the favorites so I can distinguish which directory I'm opening and for quicker access that would be a really neat feature!

### Requirements

Be able to right click/open context menu on favorite shortcuts and be able to rename them to distinguish possible duplicate names that lead to other directories

### Files Version

2.4.40.0

### Windows Version

Windows 10 Home Version 22H2

**Comment by Josh65-2201** [comment]
Merging with #7256

**Comment by yaira2** [comment]
Merging with #3422
