### ISSUE TITLE
Anthor way to access File Path

### ISSUE THREAD

**Issue by Rotten-LKZ** [files-community/Files#1175]
Now it will tell me it's a error file path when i access "D:/Videos/".

So I just want to this software not only support "\" to access file path, but also support "/"

**Comment by soumyamahunt** [comment]
> Now it will tell me it's a error file path when i access "D:/Videos/".
> 
> So I just want to this software not only support "" to access file path, but also support "/"

Seems to be working fine for me.

**Comment by yaichenbaum** [comment]
Merging with #1203.
