### ISSUE TITLE
Feature: API for third-party applications to get Files tab‘s path

### ISSUE THREAD

**Issue by Chaoses-Ib** [files-community/Files#11765]
### What feature or improvement do you think would benefit Files?

Is it possible for Files to add an API to get a tab's path? This will allow third-party applications to integrate with Files. For example, [Listary](https://www.listary.com/)'s [file application plugin](https://github.com/listary/Listary.FileAppPlugin) can get the folder opened in Files via this API, and then enable users to jump to the folder in file dialogs like this:

![image](https://user-images.githubusercontent.com/50246090/226175273-54af4d08-7277-4a22-b73d-ab9729aaf348.png)

### Requirements

The API can be implemented as a URL protocol or a CLI argument.

For example, it can follow the [x-callback-url specification](https://x-callback-url.com/):
```
files-uwp://x-callback-url/get-tab-path?x-success=myapp://x-callback-url
```
Or just add a CLI argument:
```powershell
> files.exe --active-tab-path
C:\Windows
```

### Files Version

Version: 2.4.54.0

### Windows Version

Windows 11 22H2 22621.1413

**Comment by yaira2** [comment]
You can already get the path using the screen reader apis.

**Comment by Chaoses-Ib** [comment]
Do you mean UI Automation or MSAA? As far as I can see, UIA doesn't give direct access to the full path, and Files' UI may change in the future. This is an unstable approach.

![image](https://user-images.githubusercontent.com/50246090/226176162-3cb11f5f-afe0-4a66-b402-104a4420dc6a.png)

**Comment by yaira2** [comment]
It would have to be combined, this method exists today and for what it's worth, this behavior has been consistent without any changes for a couple of years without any plans to change it.

**Comment by yaira2** [comment]
This will be resolved with #15069

**Comment by yaira2** [comment]
We'd like to add a cmd line arg as well, but it requires some thought on how to work with multiple windows.

**Comment by 0x5bfa** [comment]
Our own console app can help us.

> files.exe -console

In a new console window:

> list window
...
> select window 0
...
> list tab
...
> select tab 0
...
> get path
> navigate -path ""

This is too diskpart command like but we can do the similar in a PowerShell like way

**Comment by hishitetsu** [comment]
> We'd like to add a cmd line arg as well, but it requires some thought on how to work with multiple windows.

I think we need to implement https://github.com/files-community/Files/issues/12689 first.
