### ISSUE TITLE
历史记录

### ISSUE THREAD

**Issue by zhugeben** [files-community/Files#11762]
### What feature or improvement do you think would benefit Files?

能否在功能栏上添加个历史记录，有时候找文件忘了开新窗口，把最初要用的目录窗口给弄没了，入伏哦有个历史记录，再变回去应该会很便捷。详情考虑下

### Requirements

就像右侧的布局、排序那样，点三角通过下方出现的菜单进行选择历史目录或文件

### Files Version

2.4.40

### Windows Version

版本	Windows 11 家庭中文版 版本	22H2 安装日期	‎2023/‎2/‎22 操作系统版本	22621.1413 体验	Windows Feature Experience Pack 1000.22639.1000.0

**Comment by Josh65-2201** [comment]
There is a back button on the top left of the path bar. You can also restore closed tabs using Ctrl + Shift + T

**Comment by zhugeben** [comment]
可能是我没说明白，比如我打开了目录A，从里面打开一个文件进行编辑，然后发现需要从B目录里打开一个文件查找需要的内容，我没有开新窗口，直接从A目录这个窗口里切换目录到B，打开参考的文件后，我又想再打开A目录里的另一个文件，这时候我才发现我已经把窗口切换到B目录了，如果有个历史记录，我可以直接从历史记录里找到A目录，然后点击直接切换到A目录，而不是现在需要层层切换，直到出现A目录。
另外，初始窗口下面有各最近使用的文件，能否添加剪切、复制、移动的功能，即使右键菜单里也没有找到这几个功能

**Comment by yaira2** [comment]
Do you mean like this? #4098
