### ISSUE TITLE
bookmarks don't work

### ISSUE THREAD

**Issue by Torguen** [files-community/Files#11767]
### Description

Suddenly my favorites have been deleted and now I can't add new favorites, it just doesn't work.

What happens is that the bookmark is added to the windows system not to Files.
Files adds the bookmark to windows, not itself.

![Captura4](https://user-images.githubusercontent.com/19652075/226177655-7dc1aa4e-8520-4085-8cca-d58cb0c44d32.PNG)

Bookmarks don't work

https://user-images.githubusercontent.com/19652075/226177663-97767f61-ef4a-4705-8f50-eed1cb72ccf0.mp4

### Steps To Reproduce

Add a bookmark
Check to see which Files has been added to the bookmark to windows.

### Requirements

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

2.4.40.0

### Windows Version

10 64

### Log file

[debug.log](https://github.com/files-community/Files/files/11011948/debug.log)

**Comment by Josh65-2201** [comment]
Can you please upload (Do not copy and paste content) the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.

**Comment by Torguen** [comment]
[debug.log](https://github.com/files-community/Files/files/11011948/debug.log)

Ok this is

**Comment by Josh65-2201** [comment]
Can you see if this is an issue in the preview version? https://files.community/download

**Comment by Torguen** [comment]
Same as version 2.4.40.0, favorites don't work.
[debug.log](https://github.com/files-community/Files/files/11021053/debug.log)

**Comment by yaira2** [comment]
I've seen this issue happen when there are drives pinned to favorites in File Explorer.
