### ISSUE TITLE
Bug: Windows Defender's Smart App Control blocks files.dll from loading

### ISSUE THREAD

**Issue by xIUPITERx** [files-community/Files#11770]
### Description

When I try to open Files Preview on a computer with Smart-App-Control it gets blocked.

![06-18-23-210646](https://user-images.githubusercontent.com/97352673/226203382-966b8806-9208-4b36-9708-adb10b212dad.png)

```
Part of this app has been blocked.
Some features of Files may not work because we cannot confirm who published Files.dll that the app tried to load.
```
![Screenshot 2023-03-19 201839](https://user-images.githubusercontent.com/97352673/226204373-e117ece0-d151-4c76-a756-88260a340faa.png)

### Steps To Reproduce

- Activate Smart-App-Control (Clean Windows 11 install required)
- Open Files Preview
- App gets blocked ([Smart app control has blocked part of this app](https://support.microsoft.com/en-us/topic/smart-app-control-has-blocked-part-of-this-app-0729fff1-48bf-4b25-aa97-632fe55ccca2))

### Requirements

I had the same problem once with Powertoys, it was a signature error. [PowerToys #18658](https://github.com/microsoft/PowerToys/issues/18658)

### Files Version

Version 2.4.54.0

### Windows Version

Windows 11 22H2 25314.1010

### Log file

[debug.log](https://github.com/files-community/Files/files/11012213/debug1.log)

**Comment by Josh65-2201** [comment]
This is an issue with Windows Defender and not Files. Best to send Feedback to them and disable smart app control

**Comment by xIUPITERx** [comment]
> This is an issue with Windows Defender and not Files. Best to send Feedback to them and disable smart app control

The problem usually occurs when the app itself has a signature error.

**Comment by xIUPITERx** [comment]
Why should the error occur after a Files-update if nothing has changed in the Windows defender?

**Comment by xIUPITERx** [comment]
> disable smart app control

Not really helpful as you can't reactivate it once it's been switched off.

**Comment by Josh65-2201** [comment]
The .dll file was properly changed meaning it's a different file to Smart app control and it gets blocked because it hasn't been verified at Microsoft. You can submit it as a false positive and see if it's unblock it or turn it off now to use it.

**Comment by Josh65-2201** [comment]
@yair100 Is the files.dll not signed?

**Comment by yaira2** [comment]
Files is packaged so everything in it gets signed.

**Comment by xIUPITERx** [comment]
I have sent the feedback about the false positive blocking, let's see if anything happens.

**Comment by yaira2** [comment]
@Silther looking at this issue again, this is because smart app control detects when apps are accessing the file system and it's technically correct to notify you. That said, the whole point of Files is to be able to navigate the file system so it should be safe to ignore.

**Comment by yaira2** [comment]
Isn't there a way to bypass apps?
