### ISSUE TITLE
New folder (+) when Files is reduced

### ISSUE THREAD

**Issue by ciagamsi** [files-community/Files#11787]
### What feature or improvement do you think would benefit Files?

Being able to click on (+) to create a new folder even when Files is not in full screen.
(When I reduce the folder the (+) option disappears)

### Requirements

This will make the (+) option available to create a new folder no matter the size of the window.

### Files Version

2.4.40.0

### Windows Version

10.0.22621.1413

**Comment by cinqmilleans** [comment]
Strange, it is visible even in compact mode.

An idea to improve this menu is to create a new folder when double-clicked.

**Comment by yaira2** [comment]
Please open a bug report
