### ISSUE TITLE
Some improvments

### ISSUE THREAD

**Issue by unkilling** [files-community/Files#11788]
### What feature or improvement do you think would benefit Files?

Hi
I just tried Files and it is very nice. 
Neverless, some features in my opinion and for my use are missing.

1. There isn't a simple list view as we have in the vanilla windows explorer. It is useful to have all files and folders in the row instead columns. It's faster to scroll all files and folders in a very busy specific folder
2. It's not possible to add some columns in the details view.
    In my case, I work a lot with music and having ID3 columns (title, artist, album, genre, codec, year, number track, so on...) are very important (See attachment)
3. In the same spirit, it is crucial for me to have the bottom panel full a important informations (See attachment)
It is useful for audio files, video files, image files

![explorer_hoiRDmozfO](https://user-images.githubusercontent.com/9696193/226604985-edef2f41-9400-4f87-86bf-eac4ad688dc1.png)

### Requirements

-

### Files Version

Version 2.4.54.0

### Windows Version

Windows 10 22H2

**Comment by yaira2** [comment]
Merging with #2509

**Comment by yaira2** [comment]
And #8366

**Comment by yaira2** [comment]
@unkilling thank you for your patience, I'm excited to share that a List View layout will be included in the next release.
