### ISSUE TITLE
Feature: Add a description to each `IAction`

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#11786]
### What feature or improvement do you think would benefit Files?

I think a description of what the action does would be helpful when implementing the command palette or shortcut customization features.

### Requirements

- `IAction` must have a property named `Description`
- `Description` property of each action must have a description of what the action does

### Files Version

2.4.54.0

### Windows Version

Windows 11 22H2

**Comment by yaira2** [comment]
> Also it would be nice to have an alternate label, because some commands have the same label, Paste for example, and are indistinguishable when listed by labels.

We'll only show commands for the context so I don't think this will be an issue.

**Comment by hishitetsu** [comment]
I am wondering if alternate labels would be helpful to list shortcuts like this.

| Key | Action | Description |
| --- | ------- | ------------ |
| Ctrl+C | Copy | Copy items to clipboard |
| Ctrl+Shift+C | Copy path | Copy path of item to clipboard |
| Ctrl+X | Cut | Cut items to clipboard |
| Ctrl+V | Paste | Paste items from clipboard to current folder |
| Ctrl+Shift+V | Paste to selected | Paste items from clipboard to selected folder |

**Comment by yaira2** [comment]
Isn't the description enough

**Comment by hishitetsu** [comment]
Maybe so. I'll change requirements to the description only.

**Comment by cinqmilleans** [comment]
Here is what I envision.
* Add optionnel Description, for tooltip.
* Add Name in addition to Label. Name is immutable (but localized). Name is the default value of Label if undefined.
* The label may change (for example, (un)compressing actions change it to include the folder depending on the selection.)
This is the name that will be displayed in the command palette.
* Add Category (immutable). Some actions have similar names. For example "Ascending" can apply to sort or group.
This category will be an enum, containing the value None. If there is a category, it will be displayed with a different style before ordering. This helps to facilitate the search filter and to group together similar commands.

We will have for example
[bold]Sort By[/bold] Name
[bold]Sort By[/bold] Size
[bold]Group By[/bold] Name
[bold]Group By[/bold] Size
[bold]Selection[/bold] Select all
[bold]Selection[/bold] Invert selection
[bold]Selection[/bold] Clear selection

**Comment by yaira2** [comment]
@cinqmilleans the descriptions have been added,
