### ISSUE TITLE
Even better with the keyboard.

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#11783]
### What feature or improvement do you think would benefit Files?

Here are some suggestions for using the keyboard.

1) Using accesskeys can be very convenient. This allows access to the application on the keyboard, without having to press several keys at the same time and without having to memorize the keys. We can go further. If we open a menu, we have to move with the arrows, we can put sub-accesskeys. These can be dynamic. For example, an accesskey to access the grid, and when selected, each visible item has a 1, 2 or 3 digit number depending on the number. Ditto for the sidebar, we can add accesskeys for the headings, which opens it if closed and allows access to the elements by numbers.

2) We use hotkeys extensively. They often use modifiers. However, the keys do nothing. We can use C to copy, without needing Ctrl (but also keep this more standard hotkey). Let's use all available keys: enter, tab, space, letters, number.

3) Some actions lack visual feedback, especially on the keyboard. Add feedback for these keyboard actions (snack). Ideal for Copy for example.

4) The homepage lacks keyboard access. It is not easy to open a disc. Add possibilities (accesskey, ...). For example, it's easy to go up one folder (back) but when you've come back to home, you can't go down easily to another drive.

5) Some actions are only available in the context menu so with the mouse. Allow to open this menu with the keyboard and move around easily.

### Requirements

To discuss.

### Files Version

main

### Windows Version

Windows 11

**Comment by Josh65-2201** [comment]
> We can use C to copy, without needing Ctrl

This would probably make a lot of unintended actions. When typing text or pressing C to find the folder/files that has c at the start. Same with any others.

**Comment by yaira2** [comment]
> We use hotkeys extensively. They often use modifiers. However, the keys do nothing. We can use C to copy, without needing Ctrl (but also keep this more standard hotkey). Let's use all available keys: enter, tab, space, letters, number.

This is part of the keyboard remapping feature, I can't imagine anyone using `c` alone but the remapping feature will allow them to do this.

> Some actions lack visual feedback, especially on the keyboard. Add feedback for these keyboard actions (snack). Ideal for Copy for example.

We can probably add a message or something to the status bar for a couple of seconds, please open an issue to start a discussion.

> The homepage lacks keyboard access. It is not easy to open a disc. Add possibilities (accesskey, ...). For example, it's easy to go up one folder (back) but when you've come back to home, you can't go down easily to another drive.

We already have tab navigation, but we can certainly explore additional ways to improve accessibility, can you open a new discussion for this?

> Some actions are only available in the context menu so with the mouse. Allow to open this menu with the keyboard and move around easily.

Users can open the context menu with the `menu` key, the action center will also make it easier to access supported actions for the context.
