### ISSUE TITLE
Error when Delete

### ISSUE THREAD

**Issue by umitc18** [files-community/Files#11784]
### Description

I selected the files, deleted them permanently and got an error.(This is the second time this has happened to me.)

### Steps To Reproduce

1. Select files
2. Shift + Delete
3. Ok

### Files Version

2.4.40.0

### Windows Version

Windows 11 22H2 10.0.22621.1413

### Log file

[debug.log](https://github.com/files-community/Files/files/11023637/debug.log)

**Comment by yaira2** [comment]
What error did you get? What happened?

**Comment by yaira2** [comment]
@umitc18
