### ISSUE TITLE
Selecting groups in Downloads doesnt set scroll position properly

### ISSUE THREAD

**Issue by sguergachi** [files-community/Files#11792]
### Description

When I select a group in downloads using Tiles layout, for example "Today" it doesnt show me the contents of "Today" group unless I scroll up.

### Steps To Reproduce

Open Downloads
Set layout to Tiles
Select a group
Select "Today"

https://user-images.githubusercontent.com/615386/226687215-3a263d13-583a-48b9-96e0-cf5bad77cbe1.mp4

### Requirements

Selecting any group heading should set the scroll position to the top of the group to properly show its contents.

### Files Version

2.4.40.0

### Windows Version

10.0.22621.1413

### Log file

[debug.log](https://github.com/files-community/Files/files/11031559/debug.log)

**Comment by Josh65-2201** [comment]
Merging with #5825

**Comment by sguergachi** [comment]
Seems in 2.5 this either is an issue again or it wasnt fixed correctly, can anyone else repro this?

**Comment by Josh65-2201** [comment]
There hasn't been a fix for this
