### ISSUE TITLE
Bug: New tab icon disappears when window is smaller than 640 pixels

### ISSUE THREAD

**Issue by ciagamsi** [files-community/Files#11797]
### Description

New tab icon disappears when window is smaller than 640 pixels
### Steps To Reproduce

1. Open Files
2. Reduce Files to a small window size and noticed the new tab button hides

### Requirements

Being able to click on (+) to create a new tab even when Files is not in full screen.

### Files Version

2.4.40.0

### Windows Version

10.0.22621.1413

### Log file
[debug.log](https://github.com/files-community/Files/files/11034318/debug.log)

**Comment by Josh65-2201** [comment]
Can you please upload (Do not copy and paste content) the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.

**Comment by Josh65-2201** [comment]
Can you also see if this is an issue in the preview version. https://files.community/download

**Comment by ciagamsi** [comment]
> Can you please upload (Do not copy and paste content) the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.

First time I use Github my bad, it should be good now.

**Comment by ciagamsi** [comment]
> Can you also see if this is an issue in the preview version. https://files.community/download

Same issue in 2.4.40.0 and 2.4.55.0
