### ISSUE TITLE
Bug: Incorrect tab icon for Cloud Drives & WSL Distributions

### ISSUE THREAD

**Issue by mafra99** [files-community/Files#11795]
### Description

The tab icon is not displayed consistently for Cloud Drives and WSL distributions.

Some examples:

OneDrive Work Account - Icon is displayed correctly in the drive root
![image](https://user-images.githubusercontent.com/56681014/226730976-2770ea34-9ff9-423c-b783-b526a8ba2d63.png)

OneDrive Work Account - Icon not displayed correctly in subdirectories
![image](https://user-images.githubusercontent.com/56681014/226731149-a0b7853c-5ea2-4494-94f3-533e97b62290.png)

OneDrive Personal - Icon not shown at all
![image](https://user-images.githubusercontent.com/56681014/226731328-517ee3f4-a299-4ee8-966a-f69bbfa9cb1f.png)

WSL Distribution - Network share icon is displayed
![image](https://user-images.githubusercontent.com/56681014/226731565-c995df42-a541-4f1f-91b7-ce689422f67f.png)

### Steps To Reproduce

1. Open Files
2. Open OneDrive or a WSL Distribution
3. Optional (only if  tab icon is correct): open a directory of that drive
4. See that the tab icon is not displayed correctly

### Requirements

The tab icon should be displayed correctly in all cases.
If possible, the same icon should be displayed as in the sidebar.

### Files Version

2.4.54.0

### Windows Version

10.0.25314.1010

### Log file

-

**Comment by yaira2** [comment]
> OneDrive Work Account - Icon not displayed correctly in subdirectories

This is as designed, you'll notice the same behavior in File Explorer.

> OneDrive Personal - Icon not shown at all
> WSL Distribution - Network share icon is displayed

I can't reproduce this but it's certainly a bug.

**Comment by yaira2** [comment]
@mafra99 do you want to work on this?

**Comment by marcofranzen99** [comment]
Sure, i think this won't be too hard to fix

But let me make sure that I understood the requirements correctly:

- display the icon of the cloud provider in the drive root of the cloud drive
- do not display the icon of the cloud provider in subdirectories of the cloud drive &rarr; keep the behavior of File Explorer
- display the icon of the WSL distribution in the WSL drive root (note: file explorer doesn't show them)
- do not display the icon of the WSL distribution in subdirectories &rarr; keep behavior of File Explorer

@yair100 can you confirm?
