### ISSUE TITLE
Bug: Icons aren't loading for quick access widget

### ISSUE THREAD

**Issue by Felga7453** [files-community/Files#11794]
### Description

Quick access icons take very long time to load. even 20 seconds
![image](https://user-images.githubusercontent.com/98357862/226730471-33925aa6-2e7d-4dfd-bb3e-11a451a666f2.png)

### Steps To Reproduce

1. open "Files"
2. Go to "homepage"

### Requirements

I dont understand but uhh

- wait a while, it comes back after 20-ish seconds

### Files Version

Version: 2.4.40.0

### Windows Version

Windows 11 22H2 22621.1413

### Log file

[debug.log](https://github.com/files-community/Files/files/11033275/debug.log)

**Comment by yaira2** [comment]
Is this an issue in the preview version?

**Comment by Felga7453** [comment]
stable version. clean install from store

**Comment by Josh65-2201** [comment]
Can you see if this is an issue in the preview version? https://files.community/download

**Comment by Felga7453** [comment]
![image](https://user-images.githubusercontent.com/98357862/226738920-3c50d6e0-77ef-469d-a9b4-ceaa53a6369e.png)
same, loads quicker tho

**Comment by yaira2** [comment]
@Felga7453 thank you for reporting this, it'll be fixed in the next preview build.
