### ISSUE TITLE
Request: Default Behavior for Duplicate Files

### ISSUE THREAD

**Issue by calm-crow** [files-community/Files#11819]
### What feature or improvement do you think would benefit Files?

I would like to have a default behavior setting for when files are moved or copied and duplicates occur.
Cases of renaming and overwriting are too infrequent.

### Requirements

- Add a setting option under Settings->Folders->Behaviors.
- Remember the previous behavior.

### Files Version

2.4.40.0

### Windows Version

10.0.19045.2728

**Comment by yaira2** [comment]
This is already implemented in the preview version.
