### ISSUE TITLE
Action with multiple states

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#11825]
### Description

For some actions, we face a problem. The action can concern the current element or a selected element. For example, the Paste command can apply to the current list or to a sidebar item. The state of the Toolbar's Paste button should always match the state for the list, even if a sidebar context menu is open, and that menu should match the state to the selected item without updating the button.

Here is a simple solution to this problem. We use 2 actions, one for the current element (without needing a selection) and one for the selected element (keyboard or menu). The action on the selected element applies to the current element if no element is selected. The hotkey is applied to the action of the selection.

The only trick is that it will be necessary to add an IsPublic property to the actions (by default true). Thus, for the user, only one action will be visible in the palette, with its hotkey.

We can then add the selected content to IContentPageContext (in the homepage or the sidebar). Actions based on the selection will be able to use it.

### Concerned code

IAction

### Gains

Show different states for the same action in different places.

### Requirements

Add property bool IsPublic

**Comment by hishitetsu** [comment]
I think isPrivate is better because developers tend to think the default is false.

**Comment by hishitetsu** [comment]
Or, it is better to prepare IPrivateAction.

**Comment by yaira2** [comment]
The toolbar button always pastes to the open folder and not the selected folder.

**Comment by cinqmilleans** [comment]
@yair100 The Paste command on the toolbar is different from that on the context menu. It's bad practice but that's what I was asked to do. Here is the discussion https://github.com/files-community/Files/pull/11753#issuecomment-1474785497.

**Comment by 0x5bfa** [comment]
I still don't understand why the toolbar is clickable while sidebar item's context flyout is open. As I made some other contexts, we should be able to close this issue.

**Comment by yaira2** [comment]
Here is a screenshot to illustrate: 
![image](https://github.com/files-community/Files/assets/39923744/9bdd7ff0-440b-4e8f-9b62-8d140f96b6be)


The toolbar isn't actually clickable until the context menu is closed, but it indicates that the option is available.

**Comment by 0x5bfa** [comment]
But then this problem should be fixed if you add SelectedItem.Type == Folder and SelectedItems.Count is 0 or something, and trigger the event to invoke IsExecutable again when selection changed.
