### ISSUE TITLE
Very slow startup

### ISSUE THREAD

**Issue by TheStxfan** [files-community/Files#11836]
### What feature or improvement do you think would benefit Files?

All right, I have to say this is an extremely great project, but I'm a fast user who likes when everything on the PC is fast and responsive. There is a very big problem with the Files app...
Sometimes it stutters and sometimes does freeze and crashes, these remain not issues to ignore. But another very big and annoying issue is the slow startup. When I launch the application, it takes a while to open and once it does, after 1 second of black screen it starts loading the "home" screen.
I calculated the time it takes for the app to launch with and without the "calculate folder size" option and compared it to the default windows file explorer. Here are the results:
- Files with folder size (opening directly the app): 3.67s
- Files with folder size (opening a folder on desktop with replace default explorer option): 4.96s
- Files without folder size (opening directly the app): 3.61s
- Files without folder size (opening a folder on desktop with replace default explorer option): first try - 21.05s; second try - 4.73s
- Default windows file explorer (opening directly the app): 1.68s
- Default windows file explorer (opening a folder on desktop): 1.55s
I know it's not easy, but I hope you fix these issues in the future updates.
Keep up the good work!

### Requirements

Fix slow startup time, stutters and crashes.

### Files Version

2.4.40.0

### Windows Version

Windows 11 Pro 22H2 22621.1413

**Comment by yaira2** [comment]
Startup speed is mainly a limitation with WinAppSdk but it'll get better over time. Progress is being tracked in #4180.

**Comment by yaira2** [comment]
We're excited to share that startup performance will be significantly improved in the upcoming release of version 3. You can download the preview version from our website https://files.community/download.
