### ISSUE TITLE
Bug: Using the refresh button on a disconnected network share causes Files to freeze

### ISSUE THREAD

**Issue by mafra99** [files-community/Files#11835]
### Description

If you try to use the refresh button on a disconnected network share, it will cause Files to freeze for some time.
After around one minute "This folder is empty" is displayed.

### Steps To Reproduce

1. Access a network share
2. Disconnect the network share (e.g. disconnect network cable or wifi)
3. Try to refresh the content via the refresh button
4. See that Files freezes and does not respond

### Requirements

- Files won't freeze
- A loading indicator is shown for the tab as long as Files tries to connect

### Files Version

2.4.56.0

### Windows Version

10.0.25314.1010

### Log file

There is no useful information in the log file

**Comment by yaira2** [comment]
Thank you for reporting this issue.

**Comment by yaira2** [comment]
This issue appears to be resolved.
