### ISSUE TITLE
Theme implementation

### ISSUE THREAD

**Issue by redhotideas** [files-community/Files#11830]
### What feature or improvement do you think would benefit Files?

is it possible to implement a background view like the windiws start menu? here you can see how the start menu works perfectly with this translucent effect. on windows 11.

![image](https://user-images.githubusercontent.com/118266752/227528993-0cd0a9e4-af55-41e7-8972-a03352612f66.png)

### Requirements

- go to setting
- translucent mode -ON-

### Files Version

Versione 2.4.40

### Windows Version

Windows 11 Pro Versione 22H2

**Comment by redhotideas** [comment]
no!! it's not good to answer like this, it's not the same thing.
the background doesn't show objects behind it, and when I have the **Files** window in the center of the screen I see a colored hole like the desktop background that has nothing to do with it

**Comment by yaira2** [comment]
That's because we use mica, acrylic is designed for transient surfaces like the start menu but not for apps like Files.

**Comment by yaira2** [comment]
That's correct, the guidelines with Windows 11.

**Comment by redhotideas** [comment]
@yaira2 make me happy :)

**Comment by yaira2** [comment]
We tried it but it doesn't look good on large surfaces with multiple layers, and it has several performance issues.

**Comment by yaira2** [comment]
You can achieve this on your own if you compile from the source, the main thing is to change the backdrop material to acrylic.

**Comment by redhotideas** [comment]
I did it with the guide, but it only activates the mica effect.

Where can I activate the acrylic effect in the code?

**Comment by redhotideas** [comment]
"AcrylicBrush" : true,

**Comment by yaira2** [comment]
MainWindow.xaml

**Comment by yaira2** [comment]
https://github.com/files-community/Files/blob/main/src/Files.App/MainWindow.xaml

**Comment by redhotideas** [comment]
Perfect! thank you so much for your time, but I don't know what to change to make the theme acrylic and I don't know where to insert the code.. sigh so sad

**Comment by redhotideas** [comment]
@yaira2 I don't jump out, I'm looking at all possible pages but I can't find the file to update to activate the acrylic mode. can you please explain it to me?

**Comment by Josh65-2201** [comment]
You have to build the app yourself https://github.com/files-community/Files#building-from-source. Then find MainWindow.xaml in Visual Studio. Change the line and build the app
