### ISSUE TITLE
"Continue where you left off" not working after using CTRL+E to open Files

### ISSUE THREAD

**Issue by i-dont-know-username** [files-community/Files#11834]
### Description

When “Startup settings” is set to ”Continue where you left off“, then when using CTRL+E to open _Files_, it instead opens _Files_ as if that setting were set to “Open a new tab”.

### Steps To Reproduce

1. Open _Files_
2. Go to the _Settings_ menu
3. Go to the _Preferences_ section
4. Set _Startup settings_ to _Continue where you left off_
5. Close the _Settings_ menu
6. Use _CTRL + E_ to open _Files_ (Make sure that _Set Files as the default file manager_ setting is switched to _On_)
7. Observe that previously left open tabs are all closed and replaced with a _Home_ tab

### Requirements

I'm don't understand how to read or write code, so I can't really offer anything helpful here.

### Files Version

2.4.40.0

### Windows Version

10.0.25324.1000

### Log file

[debug.log](https://github.com/files-community/Files/files/11066871/debug.log)

I had to reinstall the app for an entirely unrelated reason, so if the log file seems weird, that's probably why.

**Comment by Josh65-2201** [comment]
This is fixed for the preview builds. https://files.community/download
