### ISSUE TITLE
Custom Font Set in Advanced Settings not applying to Tab titles

### ISSUE THREAD

**Issue by i-dont-know-username** [files-community/Files#11838]
### Description

![image](https://user-images.githubusercontent.com/110698934/227714378-0e2f27cf-165b-4dcb-9751-d6dfd982e620.png)
I chose to use a monospace font only for the purpose of highlighting the bug (I of course do not use a monospace font normally)

### Steps To Reproduce

1. Open _Files_
2. Go to _Settings_
3. Go to _Advanced Settings_
4. Click _Open settings file_
5. Close _Files_
6. Change "AppThemeFontFamily" from "Segoe UI Variable Display" to another font
7. Open _Files_
8. Observe that the font used in the titles of the tabs does not match the custom one set everywhere else.

### Requirements

Obvious

### Files Version

2.4.56.0

### Windows Version

10.0.25324.1011

### Log file

[debug.log](https://github.com/files-community/Files/files/11069010/debug.log)

**Comment by yaira2** [comment]
This would be a limitation with the WinUI tab control, it looks like overriding the font isn't supported on the WinUI control. Please report this on their GitHub repo.

**Comment by yaira2** [comment]
@mafra99 found a workaround and this wil be fixed in the next release.
