### ISSUE TITLE
Bug: Formula of Earlier This Week & Last Week

### ISSUE THREAD

**Issue by raynerdacruz** [files-community/Files#11841]
### Description

The file I have marked with a red box appears in the wrong relative timeframe group.
( I've not looked at the source code ) It appears that the formula for, earlier this week = ( current date - 7 days ) or ( Sun to Sat ). Rather than, earlier this week = Mon to Sunday. Which is why I'm seeing the file appear in the wrong group. In File Explorer, the formula is the latter so the file appears in the Last Week group instead of Earlier This Week, which is correct.

( Not sure if including this is relevant to solving the issue - I don't think it is but I'll mention it anyway ) 
In Files, the sort by and group by are set to: 
Sort By = Date Modified, Descending. 
Group By = Date Modified, Descending.

**Figure 1 - Files**
![Files_0YpvObvKHB](https://user-images.githubusercontent.com/10243952/227745558-17155854-b4c6-417b-bce4-2660c95db7d1.png)

**Figure 2 - File Explorer**
![8vwCwR62Vl](https://user-images.githubusercontent.com/10243952/227745658-456d92b7-2de4-488a-9abc-82442eec4288.png)

### Steps To Reproduce

Go to the Downloads.

### Requirements

Please change the formula for last week and earlier this week.

### Files Version

2.4.40.0

### Windows Version

10.0.19045.2728

### Log file

[debug.log](https://github.com/files-community/Files/files/11070366/debug.log)

**Comment by hishitetsu** [comment]
Certainly the logic of the week calculation does not seem to be correct.
@yair100 May I fix it? I would like to include the following modifications as well.
* Add "Future" category for future timestamps
* Split "Older" category by year in response to #11333

**Comment by yaira2** [comment]
Go ahead 👍
