### ISSUE TITLE
Bug: Selection check box is shown behind tags

### ISSUE THREAD

**Issue by i-dont-know-username** [files-community/Files#11842]
### Description

See picture
![image](https://user-images.githubusercontent.com/110698934/227746542-3f2179e3-b13a-490a-9eea-5387e89e9ccf.png)
The item tags are overlapping the item check boxes in the Tiles layout mode.

### Steps To Reproduce

1. Ensure that the _Layout mode_ is set to _Tiles_.
2. Ensure that _Item check boxes_ are visible.
3. Assign a tag to an item.
4. Hover your cursor over the item with an assigned tag.
5. Observe that the tag and check box overlap one another.

### Requirements

- Ensure the checkbox is on top of the tags

### Files Version

2.4.56.0

### Windows Version

10.0.25324.1011

### Log file

[debug.log](https://github.com/files-community/Files/files/11070409/debug.log)

**Comment by i-dont-know-username** [comment]
I would also like to add the tag circle and the Uploaded to OneDrive tick should be centre aligned with the check box

**Comment by amansingh179** [comment]
can i work on this issue ?

**Comment by Josh65-2201** [comment]
Yes

**Comment by i-dont-know-username** [comment]
![bitmoji](https://sdk.bitmoji.com/render/panel/12f3a5e1-c85f-49cd-94f4-6dce9cb18ef1-a845f6d6-c263-4f95-b9df-29a6d9c7150c-v1.png?transparent=1&palette=1&width=246)

**Comment by amansingh179** [comment]
Need more detail about this issue ...

**Comment by Josh65-2201** [comment]
What details?

**Comment by i-dont-know-username** [comment]
> 

Could you explain more about what you mean be "details"?

**Comment by amansingh179** [comment]
I'm new to the open source contribution if u can guide my how to start on this issue it will be very helpful for me

**Comment by yaira2** [comment]
@amansingh179 this issue was already resolved, would you like me to find you a different issue to work on?

**Comment by amansingh179** [comment]
@yair100 yeah sure!!

**Comment by yaira2** [comment]
@amansingh179 how about #8976?
