### ISSUE TITLE
tab pop out

### ISSUE THREAD

**Issue by gemini-mouse** [files-community/Files#11856]
### Description

when I have to switch between tabs, somehow, the tab pops out and becomes an isolated window 
it's quite annoying

It looks like the mouse selects the tab when hovering over tab.

### Steps To Reproduce

open several tab, and click one of the tabs, sometimes the tab will pop out and become an isolated window 

### Requirements

don't select the tab when hovering over the tab

### Files Version

2.4.40.0

### Windows Version

10.0.22621.1413

### Log file

test

**Comment by Josh65-2201** [comment]
Merging with #11081
