### ISSUE TITLE
Offline Installer 

### ISSUE THREAD

**Issue by gerroon** [files-community/Files#11854]
### What feature or improvement do you think would benefit Files?

Hi

None of the installers work without internet and behind firewall. No dependencies can be downloaded with the non-windows store installer.

### Requirements

Please provide downloadable version that does not require internet connection.

### Files Version

0000

### Windows Version

11

**Comment by yaira2** [comment]
You can download the offline installer from GitHub releases.

**Comment by gerroon** [comment]
"Installing
The msixbundle doesn't contain the required dependencies for installing. If you already have Files, it should automatically update, otherwise, you can download Files from our website https://files.community/download"

**Comment by Josh65-2201** [comment]
You can still install it and it will say what it needs. You can search on google on where to get them

**Comment by zzhzero** [comment]
I have the same problem I need to install it on an offline win10 without administrator privileges

**Comment by Josh65-2201** [comment]
Follow mine and yairs comment

**Comment by zzhzero** [comment]
> 关注我和亚伊拉的评论

The latest version does not seem to provide an offline installer

![image](https://user-images.githubusercontent.com/26578967/229035580-38421217-13e6-4443-b20a-4b922ccd6a4a.png)

**Comment by Josh65-2201** [comment]
I assume you on the one labeled "draft", scroll down for 2.4.40.

**Comment by zzhzero** [comment]
> I assume you on the one labeled "draft", scroll down for 2.4.40.

https://github.com/files-community/Files/releases/tag/v2.4.40

I am looking for the file on this page if not please tell me where I can find it

**Comment by Josh65-2201** [comment]
Since 2.4.60.0 is going to be release soon it may of been removed until then. Check back in a few days.

**Comment by yaira2** [comment]
The offline installers aren't supported at the moment.
