### ISSUE TITLE
Code Quality: Global usings, single line namespaces

### ISSUE THREAD

**Issue by lukeblevins** [files-community/Files#11853]
### Description

I think we should start the conversation about global usings and single line namespace declarations.

_Originally posted by @lukeblevins in https://github.com/files-community/Files/issues/11832#issuecomment-1484257518_
            

### Concerned code

All cs files

### Gains

Better readability

### Requirements

- Agree upon a subset of using statements that are common to most source files
- Add `GlobalUsings.cs`
- Amend code quality guidelines for single line namespace definitions
- Implement single line namespace defs

### Comments

This is under discussion on the discord server

**Comment by onein528** [comment]
Here's my proposal

```cs
// System
global using global::System;
global using global::System.Collections.Generic;
global using global::System.Collections.ObjectModel;
global using global::System.Linq;
global using global::System.Text;
global using global::System.Threading;
global using global::System.Threading.Tasks;

// Windows Community Toolkit
global using global::CommunityToolkit.Mvvm.ComponentModel;
global using global::CommunityToolkit.Mvvm.Input;
global using global::CommunityToolkit.Mvvm.Messaging;

// Files Front-end
global using global::Files.App.Helpers;
global using global::Files.App.Extensions;
global using global::Files.App.Filesystem;
// NOTE: We can add more here...

// Files Back-end
global using global::Files.Shared;
global using global::Files.App.Storage;
global using global::Files.Sdk.Storage;
// NOTE: We can add more here...

// Vanara
// NOTE: We can add more here...
```

**Comment by 0x5bfa** [comment]
@yair100 Can I work on this?

**Comment by 0x5bfa** [comment]
@yair100 @lukeblevins How about adding following license header to every c# source files and xaml files?

```cs
// Copyright (c) 2023 Files Community
// Licensed under the MIT License. See the LICENSE.
```

```xaml
<!-- Copyright (c) 2023 Files Community Licensed under the MIT License. See the LICENSE. -->
```

**Comment by yaira2** [comment]
@0x5bfa we can definitely do that but let's keep it separate from the Global Usings PR.
