### ISSUE TITLE
Bug: Multiselect is getting cleared when select on hover is enabled

### ISSUE THREAD

**Issue by JBVector** [files-community/Files#11867]
### Description

There seems to be a conflict between selecting multiple files and the "hover to select option". It undoes my selection when I hover over any one of them for too long:

https://user-images.githubusercontent.com/65097814/228113349-4fc3d24d-1b7a-45fd-8705-dd8385e4ee4b.mp4

### Steps To Reproduce

1. Enable "Select files and folders when hovering over them"
2. Select multiple files
3. Hover over one of them

### Requirements

Momentarily disable the "hover to select" option when multiple files are selected.

### Files Version

2.4.56.0

### Windows Version

Windows 11 22H2 22621.1413

**Comment by yaira2** [comment]
This will be fixed in the next release
