### ISSUE TITLE
Support for OpenHashTab and HashTab

### ISSUE THREAD

**Issue by MeiVinEight** [files-community/Files#11863]
### Description

When i use OpenHashTab, it keeps showing "loading", and i cannot close OpenHashTab's window
And can it support for HashTab in the file attribute winow?

### Steps To Reproduce

1. Install OpenHashTab
2. Right click a file
3. choose "more options"
4. choose "Hashes"

### Requirements

OpenHashTab's window should be able to close gracefully

### Files Version

Version: 2.4.40.0

### Windows Version

Windows 11 22H2 23419.1000

### Log file

Has no more useful information in log file

**Comment by yaira2** [comment]
The next release of Files is going to have a built-in tab for viewing hashes. Support for comparing hashes is going to be worked on as well.
