### ISSUE TITLE
Bug: Crashes when copying files while running as administrator

### ISSUE THREAD

**Issue by Giantvince1** [files-community/Files#11862]
### Description

The program crashes every time I try to copy or move files whilst it is running as Admin (my own user is an administrator, I always take over the local Administrator account after renaming it and enable Admin Approval mode for it).

### Steps To Reproduce

1. Run Files with Admin privileges
2. Attempt to copy or cut any file
3. This can also be seen by attempting drag & drop
4. Program crashes

### Requirements

Please fix the crash that occurs when the user attempts to copy or move files while running the program with Administrator privileges (at least while the *current* user is an Administrator themselves), but preferably get its core functionality working in all normally-accessible contexts (standard user, Administrator). It would be a bonus if it could operate normally under the premise of NT AUTHORITY/SYSTEM but I know that may not be possible for a UWP app.

### Files Version

Version 2.4.40.0

### Windows Version

Windows 11 22H2 22621.1413

### Log file

[debug.log](https://github.com/files-community/Files/files/11083469/debug.log)

**Comment by yaira2** [comment]
@Giantvince1 Is this still an issue in the latest preview build? https://files.community/download/

**Comment by Giantvince1** [comment]
This preview seems to have fixed the problem; I am able to cut and paste files whilst the program is running as Administrator, even to/from restricted locations such as the `Program Files` folder, without hindrance. I also don't notice any problems copying/pasting other items after doing this any longer.

I will note that I do not have an easy way to test running in `NT AUTHORITY/SYSTEM` contexts for UWP applications, but that is a limitation of Windows itself along with how UWP apps are installed/stored, and as such I can't test that scenario, nor expect it to work normally.

I can also test across different users if need be, where for example one user IS an administrator, and one is NOT, and the NON-admin user tries to do this under the context of a different user who DOES have admin capabilities, but I don't know if cross-user is supported either since the UWP framework seems to HEAVILY focus on per-user app installs rather than wanting to do system-wide installs.

**Comment by yaira2** [comment]
Thank you for letting us know that this is fixed. I want to point out that Files is now a regular Win32 program so we have easier access to a lot of APIs that were harder to use in UWP.
