### ISSUE TITLE
Feature: Support for editing metadata of multiple files simultaneously 

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#11869]
### What feature or improvement do you think would benefit Files?

We don't have support for editing metadata of multiple files simultaneously, if you try selecting multiple files and opening properties, you'll see the general page but nothing else. Support for editing the details of multiple files is an important feature that sometimes forces me to use File Explorer.

### Requirements

- This proposal will allow users to edit the metadata of multiple files simultaneously 

### Files Version

v2.4.40

### Windows Version

Windows 11

**Comment by hishitetsu** [comment]
I'm working on this.
