### ISSUE TITLE
Weird file path appearing in this PC on stable version 2.4.40.0

### ISSUE THREAD

**Issue by JBVector** [files-community/Files#11881]
### Description

When I click on "this PC", the path is a very long string of numbers and letters:
![image](https://user-images.githubusercontent.com/65097814/228392939-38fdcb68-9def-4ae6-bf07-e9d9906a26d4.png)

### Steps To Reproduce

1. Open files (2.4.40.0)
2. Click on This PC
3. Check the path in the bar.

### Requirements

Change it so that a proper path (Simply "This PC") appears when in the "This PC" folder.

### Files Version

2.4.40.0

### Windows Version

Windows 11 22H2 22621.1413

### Log file

[debug.log](https://github.com/files-community/Files/files/11095286/debug.log)

**Comment by yaira2** [comment]
The path is expected (this isn't a regular folder), but it shouldn't be too hard to match it up with a friendly display name.
