### ISSUE TITLE
Feature: Improve shell extension loading performance

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#11882]
### What feature or improvement do you think would benefit Files?

`EnumMenuItems()` in `ContextMenu` class is synchronous and recursive, which is why it takes so long to display shell extensions.
Changing this should help improve performance.

### Requirements

Avoid synchronous and recursive calling in `GetContextMenuForFiles()` and `EnumMenuItems()` by:
* Separate the loading process for the main menu and submenus
* Call `EnumMenuItems()` asynchronously if possible

### Files Version

2.4.58.0

### Windows Version

Windows 11 22H2

**Comment by hishitetsu** [comment]
I'm starting to work on it.

**Comment by lukeblevins** [comment]
@yair100 This could be assigned to @hishitetsu
