### ISSUE TITLE
icon display error

### ISSUE THREAD

**Issue by BAF3C9BDC8CB** [files-community/Files#11885]
### Description

![image](https://user-images.githubusercontent.com/30283646/228411951-ea00d548-f456-423e-a0e4-a1e7ab423e96.png)
![image](https://user-images.githubusercontent.com/30283646/228412145-e48dcfaa-f996-4ac0-bbe3-28ca9e2c0a47.png)

### Steps To Reproduce

Occurs when opening "files"

### Requirements

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

2.4.40.0

### Windows Version

Windows 10 Pro 21H2 19044.1826

### Log file

[debug.log](https://github.com/files-community/Files/files/11095962/debug.log)

**Comment by yaira2** [comment]
This will be fixed in the next release
