### ISSUE TITLE
XAML code suggestions

### ISSUE THREAD

**Issue by Jay-o-Way** [files-community/Files#11889]
### Description

I would just like to offer some suggestions.

- MS strongly recommends to use multiples of 4 for all element sizes and margins. This is to anticipate display scaling, especially 125%.
- This also applies to Font Sizes. Even for icons, because those values are actually the same. I see different font sizes being used, like 12, 14, 16 and so on. It would be better to use **StaticResources** `Style="{StaticResource CaptionTextBlockStyle}"` for text. You can find them in WinUI 3 Gallery. (see how all the numbers are multiples of 4)
  - examples: `FontIcon FontSize="14"`, `CornerRadius="6"`, `RowDefinition Height="50"`, `Margin="8,4,10,4"` etc.
  - icons are often based on 16px size.
- `BorderThickness="0,0,0,.5` → _half_ pixels?
- [Deprecated icon codes](https://learn.microsoft.com/windows/apps/design/style/segoe-fluent-icons-font#icon-list) → Is on the radar.
- [x:Uid](https://learn.microsoft.com/dotnet/desktop/xaml-services/xuid-directive), combined with a resources.resw file, allows to set one uid on an element and then set more then one property in the resources file. **Do** check if the Property's name is supported by the element. For example:
  ```xaml
  <control x:Uid="ElementID" ...>
  ```
  ```xml
  <data name="ElementID.Header">
    <value>This is the header</value>
  </data>
  <data name="ElementID.Title">
    <value>This is the title</value>
  </data>
  <data name="ElementID.Content">
    <value>This is the content</value>
  </data>
  <data name="ElementID.Description">
    <value>This is the description</value>
  </data>
  <data name="ElementID.Tooltip">
    <value>This is the tooltip</value>
  </data>
  ```

### Concerned code

General

### Gains

Code with recommendations in mind.

### Requirements

[WinUI 3 Gallery](https://www.microsoft.com/store/productId/9P3JFPWWDZRC) should be the holy grail.

**Comment by yaira2** [comment]
> MS strongly recommends to use multiples of 4 for all element sizes and margins. This is to anticipate display scaling, especially 125%.

We do our best to follow this guideline although there are some instances where it doesn't work.

> [x:Uid](https://learn.microsoft.com/dotnet/desktop/xaml-services/xuid-directive), combined with a resources.resw file, allows to set one uid on an element and then set more then one property in the resources file. Do check if the Property's name is supported by the element. For example:

x:Uid isn't very readable in xaml as it's hard to know which properties are being translated for each control.
