### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by newyork2003** [files-community/Files#11895]
### Description

The software crash every time that i select files and drag them to something outside Files

### Steps To Reproduce

Select some files and drag them to an external software or to another tab

### Requirements

- eg. Fix crash that occurs when you move files outside the software (Files)
- eg. Correct action happens when clicking...

### Files Version

2.4.40 and 2.4.58 (pre)

### Windows Version

Windows 10 Pro Version	21H2 OS build	19044.2251 Experience	Windows Feature Experience Pack 

### Log file

[debug.log](https://github.com/files-community/Files/files/11103980/debug.log)

**Comment by Josh65-2201** [comment]
Merging with #11149
