### ISSUE TITLE
Bug: Cannot unpin shell folders

### ISSUE THREAD

**Issue by ferrariofilippo** [files-community/Files#11897]
### Description

When you try to unpin a shell folder from the favorites, nothing happens.
Also, if you open a library (e.g. Pictures) and right click on the first path, you'll see `Pin to Favorites` even if the folder is already pinned. Clicking on it will unpin it.

### Steps To Reproduce

1. Pin some shell folders (This PC, Network, or Default Library folder)
2. Right click on a pinned item
3. Click `Unpin from favorites`
4. See that the folder is not removed

### Requirements

Files should unpin Shell folders

### Files Version

Preview 2.4.59.0

### Windows Version

Windows 11 22H2 10.0.22621.1413

### Log file
I add here the event report for the crash
[Error.txt](https://github.com/files-community/Files/files/11108570/Error.txt)

**Comment by hishitetsu** [comment]
I can't reproduce it. Are there any additional conditions?

**Comment by ferrariofilippo** [comment]
> I can't reproduce it. Are there any additional conditions?

Probably there was an issue with one specific folder, I can't reproduce the crash anymore. Still there's another bug related, I changed title, steps and description

**Comment by hecksmosis** [comment]
I'll work on this
