### ISSUE TITLE
Opening Recycle Bin or Control Panel redirects to the File Explorer

### ISSUE THREAD

**Issue by iPlayNone** [files-community/Files#11905]
Every time I try opening the recycle bin or the control panel they just open the file explorer and now I cannot access them even tried typing control panel in the path
![image](https://user-images.githubusercontent.com/72128959/228760631-462a0f9a-03b4-4ac4-9820-ff08ce540515.png)

**Comment by Josh65-2201** [comment]
Thanks for the feedback. Please make a new issue following the issue templates. It tells you how to fill it out if you don't know what to put for a section.
