### ISSUE TITLE
Opening Control Panel or Recycle Bin redirects to the File Explore

### ISSUE THREAD

**Issue by iPlayNone** [files-community/Files#11906]
### Description

Opening control panel or recycle bin opens file explorer instead of the app I even tried opening with the path bar(see image below) and it didn't work unlike the windows file explorer
![2023-03-30 15 29 57](https://user-images.githubusercontent.com/72128959/228775638-890b50bf-966b-4735-b619-a27e441568a1.png)
 

### Steps To Reproduce

1. Open settings in the Files App
2. Go to Advanced
3. Click Set Files as the default file manager
4. Click Yes on the Registry Editor
5. Open Control Panel

Or

1. Use the SetFilesAsDefault.reg or UnsetFilesAsDefault.reg
2. Then open Control Panel or Recycle bin

### Requirements

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

2.4.40.0

### Windows Version

Windows 10 22H2 10.0.19045.2728

### Log file

[debug.log](https://github.com/files-community/Files/files/11109440/debug.log)

**Comment by Josh65-2201** [comment]
You should not manually change the registry or use the setas files. Have you turned the Set as default toggle off then on again in settings?

**Comment by iPlayNone** [comment]
> You should not manually change the registry or use the setas files. Have you turned the Set as default toggle off then on again in settings?

I used the UnSetFilesAsDefault.reg that I found here on the github of Files

**Comment by Josh65-2201** [comment]
Again you should not use the files. Do it in app, Files settings > Advanced > Set as default.

**Comment by iPlayNone** [comment]
> Again you should not use the files. Do it in app, Files settings > Advanced > Set as default.

Tysm I know now what confused me it's kaspersky blocking the enabling of Set Files as default because it was just off even though I set it as default
