### ISSUE TITLE
Feature: spacebar to select file

### ISSUE THREAD

**Issue by piernik** [files-community/Files#11913]
### What feature or improvement do you think would benefit Files?

We can chech multiplefiles with checkboxes. How about checking the with spacebar?

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.4.40.0

### Windows Version

10.0.22621.1413

**Comment by yaira2** [comment]
This is currently available in the preview version and will be included in the next stable release.
