### ISSUE TITLE
Feature: Make MultiSelect even easier

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#11911]
### What feature or improvement do you think would benefit Files?

Multi-selection has improved a lot. It is no longer necessary to switch to MultiSelect mode and it is very practical.

However, once the selection has been started, it is no longer possible to use the usual selection facility to select multiple regions. For example, it is possible to use Shift to select close elements, but to select a second group, it is necessary to click element by element. If the click is not precise on the checkbox but a little next to it, the whole selection is lost. If you have the reflex to use the keyboard to move, the selection is lost.

Here is a solution. Use 2 selection modes, without having to switch manually.
* The normal mode is used as now. However, the selection checkbox is colored but without the ghyph to indicate that it is checked (on the mockup the normal state includes an unsightly bar).
* If you explicitly select an element (by clicking on the box or with the selection command), you switch to MultiSelection mode. The selection (used by the actions) no longer corresponds to the elements selected by the list but to those checked (the two are no longer identical).
* It is then possible to move around more easily.
* Selecting a group and clicking on an element checks all elements (this does not work on the mockup).
* Deselecting all returns to normal mode.

### Requirements

Modify the different layouts accordingly.

### Files Version

main

### Windows Version

Windows 11

### Comments

https://user-images.githubusercontent.com/46631671/228908984-06c49408-731b-473b-96ab-45260df1a04b.mp4

**Comment by cinqmilleans** [comment]
@yair100 Here is a simpler version. You can "pin" the selected elements. The selection (used by actions) is the checked items (if any) or the selected list items (if none are checked). I attach a mockup.

https://user-images.githubusercontent.com/46631671/230633510-bbf0756e-3ca9-4f31-9def-ff6020ebda2e.mp4

**Comment by yaira2** [comment]
Is this equipment to the multiselect property on the ListView control?
