### ISSUE TITLE
Bug: Folder customization are applied directly

### ISSUE THREAD

**Issue by mafra99** [files-community/Files#11917]
### Description

The folder customizations are applied directly and the window minimizes as soon as you select a new icon or click Restore Default.
The Save & Restore buttons have no effect on the behavior of the customizations page.

### Steps To Reproduce

1. Select a folder
2. Open the properties
3. Navigate to Customizations
4. Select a new icon or click Restore default

### Requirements

- Properties window is not minimized and remains open until Save or Cancel is clicked
- The save button saves the new icon
- Cancel button discards the changes
- If possible, "Restore Default" should highlight the new icon in the selection after it is clicked

### Files Version

2.4.59.0

### Windows Version

10.0.25324.1011

### Log file

n/a

**Comment by yaira2** [comment]
Fyi @0x5bfa

**Comment by 0x5bfa** [comment]
Thank you for reporting. I can repro and Future PR will fix.
