### ISSUE TITLE
WSL: asks for password when I click on a folder

### ISSUE THREAD

**Issue by nORKy54** [files-community/Files#11922]
### Description

Hi,

My Debian WSL is visible on the bar. I can click and see my folder. But when I click on a folder, I have message box : 
![image](https://user-images.githubusercontent.com/3739340/229183040-d4255eeb-59a8-42b8-a8f5-99c75db03c43.png)

I tested my wsl login, it does not work.

### Steps To Reproduce

1. Open Files
2. Click on your WSL box name
3. Click on any folder

### Requirements

- No dialog box to show. It must be possible to navigate without credentials

### Files Version

App 2.4.40.0 - Windows 10.0.19044.2604

### Windows Version

Windows 10 Enterprise 21H2 19044.2604

### Log file

Sorry, to many personnals informations. But I checked the debug.log, no log with 'wsl' and no error/warn about this message box.

**Comment by Josh65-2201** [comment]
Can you try updating to 2.4.60. https://files.community/download

**Comment by Kajot-dev** [comment]
For me it's working fine on v2.4.60 (and does not work on v2.4.40)

**Comment by nORKy54** [comment]
Yeah !! It works with 2.4.60. Thanks you !
