### ISSUE TITLE
random crash

### ISSUE THREAD

**Issue by nemson-source** [files-community/Files#11924]
### Description

it crasht in the background

### Steps To Reproduce

idk

### Requirements

- eg. Fix crash that occurs when...

### Files Version

2.4.60.0 (github)

### Windows Version

10.0.19045.2728

### Log file

[debug.log](https://github.com/files-community/Files/files/11124967/debug.log)

**Comment by yaira2** [comment]
I don't see anything specific in the log file, if it happens again, try to put together steps we can use to reproduce on our end and let us know.

**Comment by Josh65-2201** [comment]
This might be something to do with Windows since I've had Files close after about 10 minutes of being idle with no errors at all.

**Comment by yaira2** [comment]
That shouldn't happen, I'll keep an eye out for similar reports.

**Comment by nemson-source** [comment]
idk i opened a folder then i left it in the background for about 20 seconds and then it crasht

**Comment by nemson-source** [comment]
and now it's making my pc lag
