### ISSUE TITLE
slow down

### ISSUE THREAD

**Issue by nemson-source** [files-community/Files#11927]
### Description

files is making my pc lag after deleting multiple files in a folder with a lot of other files

### Steps To Reproduce

delete multiple files in a folder with a lot of other files

### Requirements

fix the lag that occurs wen deleting multiple files

### Files Version

2.4.60.0 (github)

### Windows Version

10.0.19045.2728

### Log file

i dont have a log file

**Comment by yaira2** [comment]
Merging with #4180

**Comment by yair100** [comment]
@nemson-source we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
