### ISSUE TITLE
Files freezes and then crashes when right-clicking a media file

### ISSUE THREAD

**Issue by mikjac42** [files-community/Files#11935]
### Description

When right-clicking any media file, Files will open the context menu, freeze with the last entry in the context menu showing "Loading... >", after a couple of seconds the app closes. No error message is shown, no error is written to debug.log.

File types confirmed affected: mp3, wav, mp4, wmv, avi, png, jpg, bmp
File types confirmed not affected: txt, exe, pdf, zip, docx, xlsx, psd

Measures attempted to fix/mitigate bug, without succes:
- Rebooted system.
- Updated Windows.
- Disabled all windows shell extensions.
- Disabled all 'Context menu options' in Settings -> Preferences, in Files.
- Reinstalled Files.

### Steps To Reproduce

1. Open Files.
2. Navigate to media file location.
3. Right-click media file.
4. Freeze -> Crash

### Requirements

-Fix crash that occurs when right-clicking a media file.
-Right-clicking a media file should open the context menu without crashing.

### Files Version

2.4.40.0

### Windows Version

Windows 10 Pro 21H2 19044.2728

### Log file

[debug.log](https://github.com/files-community/Files/files/11130004/debug.log)

**Comment by Josh65-2201** [comment]
Can you see if this is an issue in 2.4.60.0

**Comment by mikjac42** [comment]
Issue persists in 2.4.60.0 (Preview)

**Comment by yaira2** [comment]
Merging with #11882
