### ISSUE TITLE
deleting error

### ISSUE THREAD

**Issue by NamNotMe** [files-community/Files#11934]
### Description

when delete file that is being run, the app just crash

### Steps To Reproduce

goto temp
ctrl+a
delete

### Requirements

Fix crash that occurs when delete file

### Files Version

2.4.60.0

### Windows Version

11 22h2

### Log file

[debug.log](https://github.com/files-community/Files/files/11129999/debug.log)

**Comment by Libroru** [comment]
Also happens when deleting a folder

**Comment by yaira2** [comment]
@NamNotMe thank you for reporting this issue, we can't reproduce this in the latest preview build, so we think the issue is fixed. Please let us know if this issue continues to occur on your end.
