### ISSUE TITLE
Drag/drop from outlook attachment not working

### ISSUE THREAD

**Issue by cristof-thomas** [files-community/Files#11939]
### Description

The drag and drop of an attached file in outlook is not copying the file into the folder

### Steps To Reproduce

Select attachment in outlook and drop into folder, no file is in!

### Requirements

File should be copied

### Files Version

2.4.40.0

### Windows Version

W10 22H2 Build 19045.2728

### Log file

None

**Comment by Josh65-2201** [comment]
Can you update to 2.4.60 and try again.

**Comment by yaira2** [comment]
2.4.60 is still in certification for the Store but you can download the preview version to test https://files.community/download.

**Comment by Josh65-2201** [comment]
@cristof-thomas Can you see if this is fixed in the updated version.

**Comment by yaira2** [comment]
@cristof-thomas we're going to close this issue for now as it appears to work on our side. Please let us know if it's still an issue for you after updating to v2.4.62.
