### ISSUE TITLE
Bug: Preview pane causes crash with AVC1-24bits NV12-12bits

### ISSUE THREAD

**Issue by gilps** [files-community/Files#11936]
### Description

When opening a folder with files in MKV format with AVC1-24bits codec with NV12-12bits color, the application when trying to place the preview image in panel preview, the application stops responding at the same time.
I have several files of different codecs I only saw this problem in this type of file AVC1-24bits NV12-12bits

### Steps To Reproduce

Open file folder
enable previewer panel
instant crash

I use quicklook, if you don't use the "File" preview panel and use only the quicklook it works normally!

File info
[Lista de filtros em uso]
  (1) Built-in MKV Source
  (2) Built-in Video Codec/Transform
  (3) Enhanced Video Renderer(Custom Present)
  (4) Built-in Audio Codec/Transform
  (5) DirectSound Audio Renderer

[Informação do Vídeo]
  Codec de Vídeo AVC1 - Decoder FFmpeg Interno(h264, Thread Frame)
  Tipo de Entrada AVC1(24 bits)
  Tamanho da Entrada 1920 × 1080(1.78:1)
  Saída NV12(12 bits)
  Tamanho da Saída 1920 × 1080(1.78:1)
  Frame Rate 23.976
  BitRate: VBR

[Informações do Áudio]
  Codec de Áudio AC3(0x2000) - Decoder FFmpeg Interno(ac3)
  Sample rate 48000 ->48000 samples / seg
  Bitrate 0 ->24 bits / sample
  Canais 2 ->1 canais
  Bitrate: 192 kbps

### Requirements

disabling panel preview

### Files Version

2.4.40.0

### Windows Version

10.0.19045.2788

### Log file

the application crashes and does not save the log!
the log only has the record before the crash!

[logs.txt](https://github.com/files-community/Files/files/11130564/logs.txt)

**Comment by QuaintMako** [comment]
Is it still an issue on the new stable 2.4.60 version?

I also took the liberty to condense the logs inside a file to clean the issue.

**Comment by gilps** [comment]
This version 2.4.4 is the only one available in the microsoft store.

I installed 2.4.6, but the same crash happens!
cash does not let the application generate the LOG

**Comment by gilps** [comment]
https://youtu.be/nPyyIyy6U8A

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/

**Comment by yaira2** [comment]
@gilps
