### ISSUE TITLE
Feature: Add "Review Files" button to toolbar

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#11931]
### What feature or improvement do you think would benefit Files?

When Files is launched several times, it suddenly display a dialog asking for a review. This is very annoying to users and stops them from working, so a button to display the dialog should appear on the toolbar like the release notes button instead.

### Requirements

- Avoid displaying a dialog asking for a review out of the blue
- Instead, display a button on the toolbar
- When the button is pressed, the dialog asking for review appears

### Files Version

2.4.60.0

### Windows Version

Windows 11 22H2

**Comment by yaira2** [comment]
The review dialog only shows after launching the app 10 times and clicking review will dismiss the prompt and never show it again so I don't think it's really that much of a concern.
