### ISSUE TITLE
Feature: Display modal when trying to view directories that require admin access

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#1194]
**Describe the request**
I've multiple users on my PC and in some scenarios I want to be open a file or folder in another user. When I access another users' folder in File Explorer for the first time, it will show me a small dialog where I can get access (Standard users need admin password). In Files UWP, you can only access another users' folder after you get access permission via File Explorer or the properties window. When you try to access them without permission, Files UWP will simply say the folder is empty. This isn't really a Files UWP bug since Windows returns no items when the user doesn't have permission however we should check whether the user has permission or not and we should add the current user to the permission list for that folder.

**Requirements**
- Display modal explaining that the user does not have permission to access the location
- Modal should have a "close" action
- Modal should have an "edit permissions" action

**Comment by okey2k** [comment]
Any estimated date on this issue? 
Thanks.

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran is this still an issue in v2.0.34?

**Comment by Jaiganeshkumaran** [comment]
> @Jaiganeshkumaran is this still an issue in v2.0.34?

It seems to be still an issue, folders that the current user doesn't have access to appears empty.
