### ISSUE TITLE
Feature: Rename copy location to copy path

### ISSUE THREAD

**Issue by dracp** [files-community/Files#11945]
### What feature or improvement do you think would benefit Files?

Adapt the "Copy location" action to its specific function of "copy the path of the element".

Understanding that the location of a file or folder can be better interpreted as the place where it is located or stored, the "Copy location" function -from the popup menu that is displayed when right-clicking on a selected file or folder- should allow copying to the clipboard its location, that is, the "Folder/Directory that contains it" and not the "Path of the element" as it currently works.

Hence, it is proposed to replace the current "Copy location" string with the new "Copy path" or "Copy as path" that exactly expresses its function, that is, "Copy the path of the element" (File/Folder), as displays the "Item Path" section of the "Preview Pane".

Picture:
Folder >> FeedbackHub >> Location: ----> 	C:\Users\dracp\Documents 
Folder >> FeedbackHub >> Path: -------->	C:\Users\dracp\Documents\FeedbackHub = Pane Preview / Item Path

![230402 F 2 4 60 0_Propuesta de modificación_Copy Path x Copy Location](https://user-images.githubusercontent.com/102802425/229377713-f4632b33-6647-4fc7-819d-695f25a86194.png)

### Requirements

- Change Source String : "Copy location" to "Copy path"
- Update references in the code as well (property names etc)

### Files Version

2.4.60.0

### Windows Version

W11 22H2 22621.1485

**Comment by yaira2** [comment]
I think it's best to keep the label but adjust the behavior to match it.

**Comment by dracp** [comment]
Whatever you consider. Although I still think, that it would be interesting in any case, to be able to copy the path of the element.

**Comment by dracp** [comment]
> I think it's best to keep the label but adjust the behavior to match it.

Whatever you consider. Although I still think, that it would be interesting in any case, to be able to copy the path of the element.

**Comment by hishitetsu** [comment]
In File Explorer, it is labeled as "Copy as path"

**Comment by yaira2** [comment]
@dracp this will included in v2.5.
