### ISSUE TITLE
PROPOSAL: Files 2.4.60.0. Modify "Copy location"

### ISSUE THREAD

**Issue by dracp** [files-community/Files#11944]
Understanding that the location of a file or folder can be better interpreted as the place where it is located or stored, the **"Copy location"** function -from the popup menu that is displayed when right-clicking on a selected file or folder- should allow copying to the clipboard its location, that is, the **"Folder/Directory that contains it"** and not the **"Path of the element"** as it currently works.

Hence, it is proposed to replace the current **"Copy location"** string with the new **_"Copy path"_** or **_"Copy as path"_** that exactly expresses its function, that is, **"Copy the path of the element"** (File/Folder), as displays the **"Item Path"** section of the "Preview Pane".

Picture:
Folder >> FeedbackHub >> Location ---> 	C:\Users\dracp\Documents 
Folder >> FeedbackHub >> Path: ------->	C:\Users\dracp\Documents\FeedbackHub = Preview Pane / Item Path 

![230402 F 2 4 60 0_Propuesta de modificación_Copy Path x Copy Location](https://user-images.githubusercontent.com/102802425/229373852-ce39c0ea-1b4a-4422-882e-2b41bb2874dd.png)

**Comment by yaira2** [comment]
Can you use the feature request template?

**Comment by dracp** [comment]
> Can you use the feature request template?

Oh I'm sorry. I have never used it. Now I try.
Thanks.

Do I delete this issue?

**Comment by yaira2** [comment]
> Do I delete this issue?

I closed the issue so you don't have to do anything from your part.
