### ISSUE TITLE
Code Quality: Introduce item template to PaneHolderPage.xaml

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#11955]
### Description

The multipane feature consists of two ModernShellPages and a GridSplitter. The code around this is hard to work with and prevents us from expanding the feature to allow more than two panes. Creating an item template will allow us to create and close panes on demand.

### Concerned code

PaneHolderPage.xaml

### Gains

- easier to maintain
- will allow supporting more than two mains

### Requirements

- use item template instead of hardcoding the right and left pane

**Comment by 0x5bfa** [comment]
What about using BladeView like ColumnsLayout? If we do so, it'd be easier to merge ColumnShellPage and ModernShellPage.

**Comment by yaira2** [comment]
Once there is a template, we can do some testing to figure out the best control.

As a sidenote, isn't BladeView being phased out?

**Comment by 0x5bfa** [comment]
Yeah, they plan to remove.
We can make similar one if we plan not to use as well.

Agreed, let’s create a template first.

**Comment by 0x5bfa** [comment]
I did a quick search and I found that we cannot add time template and item repeater to enumerate shell pages as we have sizer in-between.

We seem to have use StackPanel.Children and add UIElements to it. This increases amount of code in code base but this seems to be a better idea.

Things what we have to interact with are:
- Add a pane
- Remove a pane
- Focus on a pane using accent border color at the bottom.
- Focus off a pane
- Support to resize panes

**Comment by yaira2** [comment]
We might want to support vertical panes as well in the future.

**Comment by 0x5bfa** [comment]
Let's use StackPanel.Orientation then

**Comment by yaira2** [comment]
There can be a scenario with 4 panes, two on top, and two on bottom.

**Comment by 0x5bfa** [comment]
Oh are we gonna support different orientations?

**Comment by yaira2** [comment]
After discussing Discord, we'll only support one orientation at a time. It's also worth pointing out that we're not actually adding support for different orientations right now, we're only bringing this up now in order to prevent extra work in the future.
