### ISSUE TITLE
Feature: Reduce opacity of the black background of the toolbar icons

### ISSUE THREAD

**Issue by rafaskb** [files-community/Files#11956]
### What feature or improvement do you think would benefit Files?

Dark theme icons have a completely opaque black background to help with contrast and readability, and that works great, however they can look a bit off when using themes that aren't super dark (see screenshots below).

An idea to fix it is to just slightly decrease the opacity of the black regions, so they remain dark, but naturally inherit some of the theme's colors.

The same might also be valid for light themes.

### Requirements

- Adjust icons

### Files Version

2.4.60.0

### Windows Version

10.0.19044.2728

### Comments

![image](https://user-images.githubusercontent.com/2331058/229617937-86eaeb31-7b38-4ded-9d8b-578e26a71bbe.png)
![image](https://user-images.githubusercontent.com/2331058/229617902-4a58aaa9-e9f8-4fc4-9762-cce3ad61af0b.png)

**Comment by Jay-o-Way** [comment]
I would say 100% transparent. The color of the background can always change.

**Comment by yaira2** [comment]
@rafaskb thank you for your feedback, we made some adjustments to the icon opacity and it'll be included in the next release.
