### ISSUE TITLE
Feature: Rename the "Path:" text to "Location"

### ISSUE THREAD

**Issue by dracp** [files-community/Files#11950]
### What feature or improvement do you think would benefit Files?

Adapt the action "Path:" to its corresponding function.

In the "Properties" window of the element, the specific action shown by the "Path" key corresponds exactly to the "Location" of the element and not with the path of the element.

![230403 F 2 4 60 0_Propuesta de modificación_Folders Properties_Location x Path](https://user-images.githubusercontent.com/102802425/229491851-5add6f1b-e85a-4327-94c9-54a9d58708f2.png)

### Requirements

- Change the Key: "Path" by **_"Location"_**

- Change Source String : "Path:" by **_"Location:"_**

### Files Version

2.4.60.0

### Windows Version

W11 22H2 22621.1485

**Comment by yaira2** [comment]
@dracp thank you for your feedback.
