### ISSUE TITLE
Bug: Can't drag multiple files from the tags area

### ISSUE THREAD

**Issue by tavombr** [files-community/Files#11958]
### Description

I use tags to categorize RAW photos from different folders and locations to then drag them to Photoshop, today i had an issue, dragging all the files from a tag doesn't work. I can drag individual files but not multiple at the same time. 

### Steps To Reproduce

1. Tag several files with the same color from different locations. 
2. Go to the respective color tag.
3. Select all the files (or at least two.)
4. Drag them. Nothing happens.

### Requirements

Just being able to do it, as before.

### Files Version

2.4.60.0

### Windows Version

Windows 11 22H2 10.0.22621.1413

### Log file

[debug.log](https://github.com/files-community/Files/files/11143534/debug.log)

**Comment by yaira2** [comment]
@tavombr thank you for reporting this issue, a fix will be included in v2.5.
