### ISSUE TITLE
Run as Administrator

### ISSUE THREAD

**Issue by MeiVinEight** [files-community/Files#11964]
### What feature or improvement do you think would benefit Files?

Can the Files App run as Administrator defaultly, like Windows Terminal.
![image](https://user-images.githubusercontent.com/57023439/229678163-c34616c5-4168-4905-8025-079adb01971c.png)
Because many operations require administrator permissions, such as modify file's owner.

### Requirements

Add a option, make it run as administrator defaultly if on.

### Files Version

Version: 2.4.60.0

### Windows Version

Windows 11 22H2 23419.1000

**Comment by yaira2** [comment]
You can change the properties of the exe file to always run as admin. (this works for any exe, not just Files)

**Comment by MeiVinEight** [comment]
But I don't want all exes run as admin, but only Files App. And rerun as admin manually is also cumbersome.
I think after setting Files as default file manager, is should have run as admin defaultly.

**Comment by Josh65-2201** [comment]
You only set files.exe to run as administrator. You don't do it on all of them
