### ISSUE TITLE
Crash keep going

### ISSUE THREAD

**Issue by newyork2003** [files-community/Files#11968]
### Description

I just download the new files version ad the crash while moving items still persists.

### Steps To Reproduce

1- select some items
2-drag item outside FilesApp 
3-the software crashes

### Requirements

- eg. Fix crash that occurs when moving files outside the software or to other tabs

### Files Version

2.4.60.0

### Windows Version

Windows 10 Pro Version	21H2 OS build	19044.2251 Expe rience	Windows Feature Experience Pack

### Log file

[debug.log](https://github.com/files-community/Files/files/11147448/debug.log)

**Comment by Josh65-2201** [comment]
Where are you drag items to and from?

**Comment by newyork2003** [comment]
from the dowload folder to google chrome or any exterior app, just dragging it rround makes it crash. SOmetimes i dont even make it to leave Files.
 I just updated to 2.4.61 and the crash is still there.

**Comment by Josh65-2201** [comment]
Also did you modify the log file as there is no crash reported in either of them

**Comment by newyork2003** [comment]
yes, because it contains names of folders with confidential information. I also noticed that the crash happens when using the icons mode, if it is at list mode it just doesent happen

**Comment by Josh65-2201** [comment]
Without a clear error shown I assume it would be the same issue as #11149

**Comment by Josh65-2201** [comment]
Merging with #11149

**Comment by newyork2003** [comment]
Hi, I just uploaded to the new version (2.5) and this crash still persisits.

**Comment by Josh65-2201** [comment]
Can you upload the log file

**Comment by newyork2003** [comment]
> Can you upload the log file

no it contains sensitive informstion as my full name in some file names
ps: i dowloaded 2.5.21 and the crash is still going on

**Comment by Josh65-2201** [comment]
Do you have Files running as admin?
And you can remove the paths/your name from it.

**Comment by Josh65-2201** [comment]
Type files.exe into the startmenu > Open File location

**Comment by newyork2003** [comment]
> Type files.exe into the startmenu > Open File location

thanks, it was not checked to alwas run as admin, i had just made the cahnge and i will oserve how it eveolves

**Comment by Josh65-2201** [comment]
The only error is see in the log are related to the recent files area if your not running as admin can you try open Windows File Explorer > Select the view tab > click options > under Privacy click clear

**Comment by newyork2003** [comment]
> The only error is see in the log are related to the recent files area if your not running as admin can you try open Windows File Explorer > Select the view tab > click options > under Privacy click clear

just didt it, i will observe files app
