### ISSUE TITLE
Bug: Multiselect cannot be used with single click to open enabled

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#11975]
### Description

When I have open items with single click enabled multiselect is not usable as it will open the folder/file.

### Steps To Reproduce

1. Enable Files settings > Folders > Opening items > Open Items with a single click
2. Try click on thumbnail/icon
3. See folder/file is opened rather than selected

### Requirements

- Don't open folder/file when clicking on thumbnail

### Files Version

2.4.61.0

### Windows Version

10.0.22621.1485

### Log file

[debug.log](https://github.com/files-community/Files/files/11155473/debug.log)

**Comment by hishitetsu** [comment]
Oh, I hadn't thought about a single click to open.
When 'Open items with a single click' is enabled, it would be good to show checkboxes even if no items are selected.

**Comment by Josh65-2201** [comment]
Might be best to do it the same as double click. If it doesn't work well then yeah.
