### ISSUE TITLE
Bug: Column view scroll jumps from left to right when using arrow keys for navigation

### ISSUE THREAD

**Issue by kytdkut** [files-community/Files#11977]
### Description

![annoying contents sway](https://user-images.githubusercontent.com/12164375/230000602-9c09d96c-0a26-4ddf-8a09-60e61f268267.gif)

### Steps To Reproduce

While in columns view, press the up/down arrows to change directory. The contents of the entire Files windows sway left and then right. Does not happen if you click/select folders with the mouse. See the attached gif.

### Requirements

I would expect the arrow keys to behave the same as the mouse in this case. I was about to check the contents of multiple folders in the same root and then I found that I need to do it with the mouse. The window contents sway is annoying and the whole animation takes what is seems like an eternity to complete.

### Files Version

2.4.60.0

### Windows Version

W11 22H2 22621.1413

### Log file

This is a functionality bug. The app itself does not crash.

**Comment by kytdkut** [comment]
Sorry for using the bug label. This is not a feature request.

**Comment by yaira2** [comment]
The bug label is appropriate for this issue, thanks!

**Comment by yaira2** [comment]
@kytdkut thank you for reporting this issue, we were able to reproduce it on our end and a fix is being worked on.

**Comment by yaira2** [comment]
@kytdkut a fix has been implemented and will be included in one of the next releases.
