### ISSUE TITLE
Bug: Checkboxes are STILL overlapping Tags

### ISSUE THREAD

**Issue by i-dont-know-username** [files-community/Files#11981]
### Description

![image](https://user-images.githubusercontent.com/110698934/230077273-9ed9e062-55fb-4097-8f76-f577b6a25e5f.png)

### Steps To Reproduce

_Same as stated in previous report._

### Requirements

_Same as stated in previous report._

### Files Version

2.4.62.0

### Windows Version

10.0.25330.1000

### Log file

[debug.log](https://github.com/files-community/Files/files/11158580/debug.log)

**Comment by yaira2** [comment]
@i-dont-know-username can you clarify the expected behavior? The tag and cloud status are centered vertically so we don't really have room to adjust it.

**Comment by i-dont-know-username** [comment]
The behaviour I'd expect is for them to not overlap each other. This could maybe be achieved by making the tag circle and the check box slightly smaller to make more room?

**Comment by yaira2** [comment]
The checkbox and tag circle are already about as small as they can be but the next release will include an option to hide checkboxes.

**Comment by yaira2** [comment]
@i-dont-know-username v2.4.66 includes an option to hide the checkboxes.
