### ISSUE TITLE
Bug: Renaming cloud storage drive causes crash

### ISSUE THREAD

**Issue by SchachSebastian** [files-community/Files#11980]
### Description

When using Files with cloud integration a different name for every cloud provider is shown, for example:
Google Drive displays *Google Drive* and
the OneDrive connection is displayed as *OneDrive*. This behaviour is fine when using only one account for each provider.
However, when using two Google Accounts, one is displayed as *Google Drive* and the other uses the email address of the connected cloud storage. The expected behaviour would be to follow the same `naming convention` for both.

Besides that a few problems appear when using Files with multiple cloud storage connections:

- **Renaming Cloud Storage**, when renaming the cloud storage it displays the correct name correctly, at least until you restart Files, then it converts to the default name.
- **Renaming the cloud storage drive**, when renaming the drive, an error appears that causes Files to crash (sometimes the error show directly, sometimes it's not)
![image](https://user-images.githubusercontent.com/91465214/230045533-aaf39ad4-e11b-4e87-a8ac-f0b7489e2486.png)

I'm not sure how connected these issues are, so I only created one issue, however I can split it, if needed.

### Steps To Reproduce

# Preparations:
1. Install Google Drive for Desktop
2. Add multiple Google Accounts
3. Open Files
4. Notice the different naming convention

## Renaming cloud storage:

5. Click on Cloud Storage -> Google Drive -> Properties
6. Enter new name
7. Save
8. Restart Files (name resets to default one)

## Renaming the cloud storage drive:

5. Drives -> select the drive associated with the cloud storage -> Properties
6. Enter new name
7. Save

at this point it either crashes directly or after a little time clicking through Files settings
The new name, however, is kept

### Requirements

- Fix the **crash** that occurs when renaming the cloud storage associated drive.
- Use same **naming convention** for all new  cloud storage connections (`email` or `cloud provider #number` or match `drive name`)
- Make the cloud storage **renameable** (maybe couple it with the drive name and make no difference between renaming drive or storage)

### Files Version

2.4.61.0

### Windows Version

Windows 10 Pro 22H2 19045.2728

### Log file

[debug.log](https://github.com/files-community/Files/files/11157421/debug.log)

**Comment by Josh65-2201** [comment]
Google drive won't let you change the name of the sync drives or folders. 
Also I think google drive is what's adding the email to the other one as to not conflict. Can you check in Windows File explorer and see if it shows the same as in Files.

**Comment by SchachSebastian** [comment]
Sure, you're right, in windows file explorer it shows the cloud storage drive with the email name, however, an additional cloud storage section isn't provided by windows explorer (like in Files) + the name of the `drive is changeable`. 
This additional section only belonging to Files seems to first use the same name as the drive itself, but after renaming the drive, the `name does not update` (only updates in the drive section)

**Comment by yaira2** [comment]
> Notice the different naming convention

It seems like there are multiple issues going on here, I think we should track them in separate issues. Can you open a new issue for this and we'll continue tracking the crash in this one?

**Comment by yaira2** [comment]
@SchachSebastian can you check if the crash is still present in the latest preview build? https://files.community/download
