### ISSUE TITLE
Bug: Close Settings Tooltip Hidden Behind Maximise Button

### ISSUE THREAD

**Issue by i-dont-know-username** [files-community/Files#11982]
### Description

![image](https://user-images.githubusercontent.com/110698934/230078140-e978cf96-aa7d-4ec6-8fdf-e02c9f073971.png)

_**Suggestion for fix**_
_Make it so that the tooltip never appears in that location_

### Steps To Reproduce

**1.** Restore the window.
**2.** Open Settings.
**3.** Hover the mouse on the close button.

### Requirements

*Obvious*

### Files Version

2.4.61.0

### Windows Version

10.0.25330.1000

### Log file

[debug.log](https://github.com/files-community/Files/files/11158714/debug.log)

**Comment by yaira2** [comment]
Thank you for reporting this issue, this seems to be a platform issue in WinAppSdk but I'll keep the issue open in case someone has a workaround.

**Comment by ferrariofilippo** [comment]
What if we place the tooltip under the button?

**Comment by i-dont-know-username** [comment]
> What if we place the tooltip under the button or on its left?
> 
> ![1](https://user-images.githubusercontent.com/102259289/230141535-8574dbca-421d-41ad-bcd3-28acc6225c44.png) ![2](https://user-images.githubusercontent.com/102259289/230142186-b8eb7cf5-5191-4778-91a0-32165045b8ff.png)

That would work great, thanks!

**Comment by yaira2** [comment]
> What if we place the tooltip under the button or on its left?

That's a good workaround 👍
