### ISSUE TITLE
Bug: Default color schemes have very little impact in the color scheme

### ISSUE THREAD

**Issue by rafaskb** [files-community/Files#11989]
### Description

When applying one of the predefined color schemes to Files on version, it seems like the impact they have on changing Files colors is very little. The same color schemes were much more noticeable on 2.4.40.0.

Assigning a custom color works as expected.

### Steps To Reproduce

1. Go to Settings
2. Go to Appearances
3. Select one of the predefined color schemes, such as "Red"
4. Files should be Red now, but it isn't

### Requirements

- Use the correct color when choosing one of the built-in options

### Files Version

2.4.61.0

### Windows Version

10.0.19044.2728

### Log file

https://user-images.githubusercontent.com/2331058/230205893-c199b961-2d84-4b57-98c9-5fffd57a076b.mp4

**Comment by Jimmy20220531** [comment]
my video，哈哈。

**Comment by ferrariofilippo** [comment]
At the moment, the `A` is set to 0x32 I think we should change that to something like 0x60. Should they have even more impact?
@0x5bfa I'd like to hear your opinion on this 

Light B/A (Red):
![Before_Light](https://user-images.githubusercontent.com/102259289/230614620-8ffc8988-10bb-4231-976c-7406bc067333.png)
![After_Light](https://user-images.githubusercontent.com/102259289/230614611-90a30d22-26c7-4018-9a42-fc0cb83c4c1f.png)

Dark B/A (Red): 
![Before_Dark](https://user-images.githubusercontent.com/102259289/230614622-3922da88-cd4b-4e5e-a99f-065094d3dfe2.png)
![After_dark](https://user-images.githubusercontent.com/102259289/230614613-9979da75-b94f-41b8-8571-a167b192147e.png)

**Comment by rafaskb** [comment]
Personally I would push it even farther, `0xB0` or even `0xC0` perhaps.
I see the default color schemes as something that says "Hey do you want to radically change the appearance of the app? Here are some choices!", while the fine tuning in the config files say "But if you want to fine tune it to your liking, here are the configs"

**Comment by ferrariofilippo** [comment]
> Personally I would push it even farther, `0xB0` or even `0xC0` perhaps. I see the default color schemes as something that says "Hey do you want to radically change the appearance of the app? Here are some choices!", while the fine tuning in the config files say "But if you want to fine tune it to your liking, here are the configs"

I agree with you on the `radically change` thing (I use `0xFF`, which I think most people would consider awful). 
Still, I'm not sure how much the average user would like this "hard" change

**Comment by 0x5bfa** [comment]
As it's a difficult issue, I cannot say I must or should be like this, however I'd say that pushing it further is agreeable and like to be set to 0xA0. In opacity setting, would like to be set to likely 0.7

**Comment by yaira2** [comment]
This is a regression in v2.4.60, has anyone figured out which commit caused this issue?

**Comment by yaira2** [comment]
I confirmed that this was introduced in #11820
