### ISSUE TITLE
File gets tick mark when I select them

### ISSUE THREAD

**Issue by Ajinkya2024** [files-community/Files#11996]
### Description

after the last update, whenever I select any file, that file gets selected. to unselect I have to re-select it again. Selection option is turned off in the settings.

### Steps To Reproduce

1. select any file

### Requirements

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

latest version

### Windows Version

latest

### Log file

.
![Files](https://user-images.githubusercontent.com/130047571/230335546-c8bf850d-ca39-46ca-a505-36653581aedc.png)

**Comment by Josh65-2201** [comment]
This is how it should work as it used for mouse/touch selection

**Comment by Ajinkya2024** [comment]
before the last update, it was never used to select the files. As you can see in this picture. in the Column view it does not select the files.
![Screenshot 2023-04-06 151638](https://user-images.githubusercontent.com/130047571/230341267-3cbc6c0c-3344-40db-a257-1cc0afffd206.png)

**Comment by Josh65-2201** [comment]
Yes I know, there used to be an setting for turning it on but was removed to make it easier and more obvious for mouse only or touchscreen selection. I will update this request for adding the setting back.

**Comment by Josh65-2201** [comment]
Actually there already is one #11938. You can look there for updates on it.
