### ISSUE TITLE
Feature: Color network drives

### ISSUE THREAD

**Issue by EugeneRM0** [files-community/Files#11998]
### What feature or improvement do you think would benefit Files?

It would be helpful if the network drives box had a different color than the local drives.
If it could be customized, even better. Thus, local drives would have one color, network drives another, and external drives such as GDrive or OneDrive another color.

### Requirements

- This proposal allows to quickly differentiate local and network drives.

### Files Version

2.4.61.0

### Windows Version

Windows 10 Pro 22H2

**Comment by Josh65-2201** [comment]
What do you mean by box? Network drive have different icons to local ones and a separate widget is being discussed at #5135

**Comment by EugeneRM0** [comment]
> What do you mean by box/color? Network drive have different icons to local ones and a separate widget is being discussed at #5135

Something like this:

![drives](https://user-images.githubusercontent.com/130060085/230375290-ec0ade12-7439-46e8-ac8a-19aa47694671.png)

**Comment by yaira2** [comment]
> This proposal allows to quickly differentiate local and network drives.

Can you elaborate on this use case and how it fits into your workflow?

**Comment by EugeneRM0** [comment]
> Can you elaborate on this use case and how it fits into your workflow?

We work with several local disks and network drives, I personally have 10 and sometimes more.
When you have a high pace of work it would be nice to be able to quickly identify the drives by color and not having to read the name.

Sometimes the drives are different folders on the same IP and at a quick glance the first thing you see is several folders with the same IP, which forces you to stop to identify each one.

On the other hand, colors are easier to remember, which helps in medium or large companies to better identify things for standard users or users with limited computer skills.
For example, users will more easily remember that the Documents unit is blue. That is easier than not making them remember the Y:

At least in our case it is a matter of productivity and getting to automate movements by color association.

**Comment by yaira2** [comment]
@EugeneRM0 would applying custom icons to the different drives help?

**Comment by mdtauk** [comment]
What about having Network Drives in a separate group on the home screen?

**Comment by EugeneRM0** [comment]
@yaira2  In my particular case, it works for me. I can put the same icon but in different colours so that the mental association is quicker.

I'm sure there are many people who would welcome customising the icon. 

Thanks

**Comment by yaira2** [comment]
@EugeneRM0 I believe you can change the icon from the desktop.ini file, can you check if this works?
