### ISSUE TITLE
Bug: Application is crashing when changing file permissions

### ISSUE THREAD

**Issue by MeiVinEight** [files-community/Files#11994]
### Description

![image](https://user-images.githubusercontent.com/57023439/230277984-65b0123b-868f-4e22-b8c5-82eaf9a74059.png)

### Steps To Reproduce

1. Create a folder and disable inheritance using the windows file manager.
2. Add a permission principal with only Read and execute access using the windows file manager.
3. Edit it's access to full control using the Files App in security in properties.
4. Edit it's access to full control using the Files App in advanced security.
5. It will report "Something went wrong!" and crashed.

These operations do not seem to reproduce the problem 100%, but the modifyings of folder's access permissions do not take effect,
It seems that it is not just this operation that causes the program to crash.
And it seems not work when edit file/folder's access permissions.

### Requirements

- Fix program crashes caused by some operations.
- Fix security editing, make it work, such as edit user's permissions.

### Files Version

Version: 2.4.61.0

### Windows Version

Windows 11 22H2 23424.1000

### Log file

[debug.log](https://github.com/files-community/Files/files/11166953/debug.log)

**Comment by Josh65-2201** [comment]
There are known issues being tracked in #11549, #11550 and #11551. I assume these are the things you are trying to edit in Files

**Comment by yaira2** [comment]
Fyi @0x5bfa

**Comment by 0x5bfa** [comment]
To make things more clear, I’m planning the following to do:

- Add a ViewModel for SecurityAdvancedPage.
- Remove UI-related parts from Filesystem.Security.AccessControlEntry class
- Remove the code using the default C# security classes
- Use Win32API by using Vanara possibly

Current security-related codes are a little messy. I’ll find the way.

**Comment by 0x5bfa** [comment]
'M sorry but the feature is disabled for a year because of its instability. So we can now close and have to implement the feature to edit file permission. I can start working on from my previous try.
