### ISSUE TITLE
Run on background

### ISSUE THREAD

**Issue by YT-Advanced** [files-community/Files#11995]
### What feature or improvement do you think would benefit Files?

I think you should have a option to let Files run in the background. By this way, we can help better start time

### Requirements

Nope

### Files Version

Latest

### Windows Version

Windows 11

**Comment by Josh65-2201** [comment]
This is being discussed in #11279. If you have anything to add please make a comment there.

**Comment by yaira2** [comment]
@YT-Advanced This feature is included in the latest preview build (https://files.community/download) and will be included in the v3 release.
