### ISSUE TITLE
右键菜单

### ISSUE THREAD

**Issue by ChenAi140** [files-community/Files#12006]
### What feature or improvement do you think would benefit Files?

能不能添加win10风格的右键菜单？win11那个一点都不好用

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z
能不能添加win10风格的右键菜单？win11那个一点都不好用

### Files Version

2.4.61.0

### Windows Version

win10

### Comments

能不能添加win10风格的右键菜单？win11那个一点都不好用

**Comment by Josh65-2201** [comment]
It is not possible to do this.
