### ISSUE TITLE
High CPU usage after opening the software

### ISSUE THREAD

**Issue by sscco55** [files-community/Files#12000]
### Description

Opening the software 

Open the task manager and find that the CPU usage of Files Preview is hovering between 30% and 50%

This may sound ridiculous, but it did happen in front of me

### Steps To Reproduce

1) Open files preview
2) Open Task Manager

### Requirements

Reduce CPU usage

### Files Version

2.4.62.0

### Windows Version

Windows 11 22H2 25330.1000

### Log file

[debug.log](https://github.com/files-community/Files/files/11171735/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, we're tracking this in #4180.
