### ISSUE TITLE
Crash when deleting folder/files

### ISSUE THREAD

**Issue by Lexyaade** [files-community/Files#12008]
### Description

Files crash when I want to delete files or folders that are stored on external storage devices.
The delete function works on internal storage devices.

Crash happens by methods:

Clicking on top bar trashcan
Left click-> trashcan
Pressing delete on keyboard

Tested on:

M.2   Delete function works
Internal SSD   Delete function works
Internal HDD   Delete function works

External SSD   Delete function causing a crash
Multiple PenDrives   Delete function causing a crash

### Steps To Reproduce

1. Try to delete anything from external storage device
2. Wait for a few seconds 
3. Crash

### Requirements

Fix crash that occurs when trying to delete files from external storage devices

### Files Version

2.4.61.0 10.0.22621.1413

### Windows Version

Edition	Windows 11 Home Version	22H2 Installed on	‎25/‎02/‎2023 OS build	22621.1413 Experience	Windows Feature Experience Pack 1000.22639.1000.0

### Log file

[debug.log](https://github.com/files-community/Files/files/11179175/debug.log)

**Comment by ferrariofilippo** [comment]
Did you press `Delete` twice?
This bug should be fixed by #11928

**Comment by Lexyaade** [comment]
Yes, I pressed it twice, but not quickly. I waited maybe 10-20 seconds, which is quite a long time to wait for the pop-up. 
And now that you mentioned this I tested how long it would take without pressing it again, and I waited for now maybe 6 minutes and it did nothing. No pop-up nothing. It won't freeze up or anything, I can switch folders and create files/folders without a problem after clicking delete once, but as soon as I click it the second time it crashes.

**Comment by ferrariofilippo** [comment]
> Yes, I pressed it twice, but not quickly. I waited maybe 10-20 seconds, which is quite a long time to wait for the pop-up. And now that you mentioned this I tested how long it would take without pressing it again, and I waited for now maybe 6 minutes and it did nothing. No pop-up nothing. It won't freeze up or anything, I can switch folders and create files/folders without a problem after clicking delete once, but as soon as I click it the second time it crashes.

There might be another bug report for the modal not showing I'll see if I can find it, anyway as I mentioned earlier, there's already a PR to fix this issue

**Comment by yaira2** [comment]
@ferrariofilippo with the crash fixed and the other issue being tracked in #11501, can we close this issue now?

**Comment by ferrariofilippo** [comment]
I agree
