### ISSUE TITLE
Shortcuts for different modes

### ISSUE THREAD

**Issue by maurodegroeve** [files-community/Files#12001]
### What feature or improvement do you think would benefit Files?

So I can toggle between Column mode and detail mode with a key button.

### Requirements

Assign a button to every viewing mode

### Files Version

2.4.60

### Windows Version

Windows 11

**Comment by gave92** [comment]
Cltr+Shift+Num will change the layout mode (e.g Cltr+Shift+1 is Details, Cltr+Shift+6 is Column)

**Comment by Josh65-2201** [comment]
That should be added to the shortcuts docs on the site too
