### ISSUE TITLE
Feature: Add support for changing the font sizes

### ISSUE THREAD

**Issue by martago54** [files-community/Files#12007]
### What feature or improvement do you think would benefit Files?

I know there is a line in the configuration file stating:

AppThemeFontFamily 	Segoe UI Variable

But there is no way to change the font size and in nowhere is explained how to change to a different "font family" as the line state.

The importance of change the font type and size is to have the capability of showing most of the files of a folder, if you are able to change to a smaller font size.

The existing "Segoe UI Variable" font type has a larger size than the default windows file explorer app.

### Requirements

- This proposal will alow to show more if not all of the files within a folder.
- it will allow to be similar in functionality with windows file explorer in this regard

### Files Version

Version 2.4.61.0

### Windows Version

Windows 10 10.0.19045.2728

**Comment by Josh65-2201** [comment]
To change the font you enter the name of an installed font on your system. You can find then in Windows settings > Personalization > Fonts.

**Comment by martago54** [comment]
There is no "Segoe UI Variable" font but just "Segoe UI" without the word "Variable".  Is it supposed to add this word to the font name?

My feature request also mentioned the possibility to change the font size in complement to changing the font type.

**Comment by Josh65-2201** [comment]
Segoe UI variable is the default for Windows 11 but falls back to the Segoe UI for Windows 10 users. I know you asked also for font size and that's why I have left this request open.

**Comment by martago54** [comment]
Tks for your quick replies.

**Comment by martago54** [comment]
Accessing Settings, then Advanced, then "Edit Settings File", then changing the line "AppThemeFontFamily" to another valid font name, then save the configuration file, then exit and restart the program, then the old "Segoe UI Variable" was automatically restored by the program, so in practice it does not allow to change the default Segoe UI font name to another font.  Am I doing here anyting wrong?

**Comment by Josh65-2201** [comment]
You have to close Files before saving the file

**Comment by martago54** [comment]
It worked but there is no big difference with other fonts, we do need to change the font size if we want to acommodate more lines in the program displayed screen.

**Comment by yaira2** [comment]
Files uses a number of different font sizes so it's not so simple to add support for changing them. You can however change the scaling in Windows.

**Comment by martago54** [comment]
I had already thought about that Windows feature which I used, in fact I had configured the text to appear with 125% scaling a long time ago, which should be responsible for not seeing as much lines in your software as I would like.  However, File Explorer, which I confirmed use the same font as your program - Segoe UI - do show more lines, thus showing more files within a folder, in spite of the 125% scaling configuration, probably internally disregarding this personal configuration.

Your software has great advantages in Windows 10, because Microsoft had not changed, and probably will never do, as it did in Windows 11, in creating TABS in File Explorer.

**Comment by Josh65-2201** [comment]
If your goal is just to see more items you can try using compact mode in Files settings > Use compact spacing in the details layout

**Comment by martago54** [comment]
This was one of the first configurations I tried, it is still on.  Just to give you a more exact picture of what I am talking - in Windows 10 File Explorer, with the same font name, in spite of the 125% scaling, in my working directory (or folder):
- in File Explorer, the display shows me all 10 subfolders, all 18 files and it still leaves a blank space for another 5 files if they existed;
- in your FILE app, the display shows all of the 10 subfolders and only 15 of the existing files, there are an extra 3 files that are not shown unless I scroll down, and no blank space in the screen.
As I don't want to unncessary see a larger font and displaying less files and folders, I will continue to use File Explorer, in spite of not having TABS as your app does.

**Comment by 0LBaID** [comment]
Dont want to hijack this issue thread but is there a way to change the font color as well?

**Comment by Josh65-2201** [comment]
There isn't currently. Can you open a separate request with the reasons why you would want this.

**Comment by Josh65-2201** [comment]
Why did you close this?

**Comment by yaira2** [comment]
@martago54 following the modern design guidelines, Files isn't going to be a 1:1 match with Files Explorer when it comes to how many items fit on the screen. In order to improve the compact spacing option, we're reducing the margin between items and we're also looking into reducing the font size by default. However, we don't plan to add a setting to control this manually.
