### ISSUE TITLE
Bug: Nothing happens when pressing the Yes button on the Review Files dialog

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#12015]
### Description

As the title described. Pressing the Yes button merely closes the dialog.

### Steps To Reproduce

1. Launch the store version Files several times.
2. If you see the Review Files dialog, press the Yes button.
3. The dialog is closed, but the UI for review doesn't appear.

### Requirements

The UI for review should appear when the Yes button is pressed.

### Files Version

2.4.61.0

### Windows Version

Windows 11 22H2

### Log file

No useful logs were output.

**Comment by hishitetsu** [comment]
This code would fix the issue, but I can't test it in my environment.
```csharp
WinRT.Interop.InitializeWithWindow.Initialize(storeContext, App.WindowHandle);
```

**Comment by yaira2** [comment]
I haven't had any issues on my side, but I'm not surprised to see this issue as it's very finicky. Do you want to open a PR with this fix?

**Comment by hishitetsu** [comment]
Yes, I submitted a PR for now.
But we may have to register a new version in the store to see if this fixes the issue.
