### ISSUE TITLE
Feature: Reduce margin in the compact spacing option

### ISSUE THREAD

**Issue by DanRotaru** [files-community/Files#12012]
### What feature or improvement do you think would benefit Files?

Please add a small - compact view option for details layout (look at atached screenshot) 
![image](https://user-images.githubusercontent.com/7759507/230643856-8092fb43-5e2d-488b-abcd-563a965ab003.png)

Option to remove that big space between, for me now it's only one reason to not change my default explorer. Windows explorer it's more practical with this option
![image](https://user-images.githubusercontent.com/7759507/230644116-282014a5-3af1-478e-a2da-332cc2127197.png)

Option in original windows explorer
![image](https://user-images.githubusercontent.com/7759507/230644170-4c52d313-d4e6-441c-9545-bbcf43a790e8.png)

### Requirements

- None

### Files Version

2.4.61.0

### Windows Version

Windows 11 - 10.0.22621.1485

**Comment by Josh65-2201** [comment]
There is in Files settings > Use compact spacing in the details layout

**Comment by DanRotaru** [comment]
It is doing smaller paddings, not space between elements. I want to set same paddings and without (or 1px) spacing between elements. Now it's looking bad:(
![image](https://user-images.githubusercontent.com/7759507/230644598-055430a7-f5d9-4ef1-88c9-37548f472f2d.png)

**Comment by DanRotaru** [comment]
Decrease this space
![image](https://user-images.githubusercontent.com/7759507/230644947-60383ec9-89ae-4b1e-9384-5c2dab15c829.png)

**Comment by ferrariofilippo** [comment]
You can do it by yourself, just drag the splliters on the header (Vertical line between `Name` and `DateModified`)

**Comment by yaira2** [comment]
We left the space between items to be consistent with File Explorer, we are however looking into reducing the margin on each item so that it doesn't take up as much space.

**Comment by Frenvius** [comment]
the current spacing in compact mode is quite useful, thanks for that!
but would it be possible to also add an option to decrease the spacing between the icons, please?

![image](https://user-images.githubusercontent.com/5433348/236296247-ec72c2c5-4b6c-4ba3-af10-3a4a94edb0ad.png)

**Comment by 0x5bfa** [comment]
We can create Generic.xml and Compact.xaml

Like, if the user prefer to use compact mode, Files would load Compact.xaml instead of Generic.xaml

**Comment by yaira2** [comment]
This feature is implemented in our dev branch and will be included in the next release.
