### ISSUE TITLE
Bug: No icons on the quick access widget

### ISSUE THREAD

**Issue by Rmdhn1** [files-community/Files#12019]
### Description

There is no icon appearing on home favourites
![image](https://user-images.githubusercontent.com/54092365/230730145-3db1c0c2-c4ab-4c73-968e-54e075ba79e7.png)

### Steps To Reproduce

1. Open Files
2. Look with your eyes
3. Attempt to fix it by changing icon
4. Drive Unplugged NotAFolder

### Requirements

- Make them appear again
- Allow to change folder icon

### Files Version

2.4.61

### Windows Version

22H2 22621.1413

### Log file

[debug.log](https://github.com/files-community/Files/files/11183598/debug.log)

**Comment by CodeAnk2829** [comment]
Fixes:
step 1: Click on the three dots located at  the top-right corner.
step 2: Go to 'Options'
step 3: Shift to 'view' panel
step 4: Make sure you have checked the following checkboxes (as shown in the screenshot).
![image](https://user-images.githubusercontent.com/104667338/230768542-3e246e43-125a-4e21-963b-adc3fa5caa96.png)

**Comment by Rmdhn1** [comment]
![image](https://user-images.githubusercontent.com/54092365/230773175-41bb6c56-20eb-46fe-bf78-a00e17660e63.png)
made it worse

**Comment by yaira2** [comment]
@Rmdhn1 thank you for reporting this issue, I can't reproduce this locally, but I wonder if it has to do with there being some drives in the favorites section. Can you see what happens if you unpin them?

**Comment by Rmdhn1** [comment]
i just got a windows update not too long ago. It's showing again, until it stopped and having the icons disappear after clicking trough folders and rapidly going back to Home, although it's showing again after i alt tabbed? However i can't reproduce this anymore. will reopen if it happens again
