### ISSUE TITLE
File explorer

### ISSUE THREAD

**Issue by Bootzzzz** [files-community/Files#12018]
### Description

On windows 11, while i am auto-hiding my taskbar and opens your file explorer, once I place my cursor on the bottom of the screen, the taskbar does not unhide, it only does not work on your app and on fullscreen only

### Steps To Reproduce

Turn on task bar auto hide, go to file explorer, on fullscreen, place cursor on the bottom and taskbar does not unhide

### Requirements

Fix taskbar autohide

### Files Version

2.4.60.0

### Windows Version

10.0.22621.1413

### Log file

[debug.log](https://github.com/files-community/Files/files/11183535/debug.log)

**Comment by Josh65-2201** [comment]
Merging with #10767. Check there for updates.
