### ISSUE TITLE
Ongoing Task

### ISSUE THREAD

**Issue by dp4github** [files-community/Files#12023]
### What feature or improvement do you think would benefit Files?

I like this 'Files' app much, it is probably best alternative of Microsoft's windows explorer. but 1 thing I don't likw much is Ongoing Task which is your version of Copy Handler, I did not mean that it is not a good, it's nice but if there is an option to use other copy handler like TeraCopy or eles, it's a very good thing for people like me who bought TeraCopy. Because there is no option to change default copy handler  in this 'Files' app but can't Use Tera Copy. So my request is to add an ability to use external copy handler.

Another thing is app is crashes sometimes when trying to delete any file.

### Files Version

Version 2.4.61.0

### Windows Version

Windows 11 Pro 22H2 22621.1485

### Comments

![Screenshot 2023-04-09 100753](https://user-images.githubusercontent.com/130268684/230754955-2499df51-6ffe-4530-9dff-4e5a66b74af5.png)

**Comment by Josh65-2201** [comment]
Merging with #7518. Check there for updates.
