### ISSUE TITLE
Bug: App keeps crashing, not allowing me to delete anything

### ISSUE THREAD

**Issue by sawm90** [files-community/Files#12021]
### Description

so my file's app keeps crashing and when i try to delete something in file explorer by keeping active in the file.

### Steps To Reproduce

1. go on files
2. press any buttton
3. it will crash

### Requirements

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...
- eg the x button

### Files Version

2.4.62.0

### Windows Version

51621011

### Log file

[debug.log](https://github.com/files-community/Files/files/11184606/debug.log)

**Comment by sawm90** [comment]
sorry the windows version is actually:Windows Feature Experience Pack 1000.22639.1000.0 22621.1413 Windows 11 Home:2H22

**Comment by Josh65-2201** [comment]
Can you clarify what you are doing to cause the crash. You said it crashed when you deleted something the File Explorer, but also when pressing any button (What button?) in Files.

**Comment by yaira2** [comment]
@sawm90 I haven't been able to reproduce this issue locally but there are some improvements in v2.4.64 that might have helped. Can you give it another try and see what happens?

**Comment by yaira2** [comment]
@sawm90 this appears to be resolved but please let us know if it's still an issue after updating to v2.4.66.
