### ISSUE TITLE
Bug: Some context menus do not use custom font

### ISSUE THREAD

**Issue by i-dont-know-username** [files-community/Files#12026]
### Description

![image](https://user-images.githubusercontent.com/110698934/230770546-eee4decf-29a0-4a7c-8afa-27a2d1af0700.png)
The _Archive_ submenu uses _Segoe UI_ instead of the font set in the Settings file

### Steps To Reproduce

1. Set a custom font in the Settings file
2. Look at the submenu

### Requirements

A custom font to be set

### Files Version

2.4.61.0

### Windows Version

10.0.25336.1000

### Log file

[debug.log](https://github.com/files-community/Files/files/11185337/debug.log)

**Comment by yaira2** [comment]
Thank you for reporting this issue.

**Comment by yaira2** [comment]
In case someone comes across this issue, the best way to resolve it would be to identify the `StaticResource `being used in the `MenuFlyout` control and overriding it in `App.xaml`.

**Comment by MrFrawsty** [comment]
I would like to work on this. I looked through the files and found where some styles weren't added to some `TextBoxes` and `TextBlocks`

**Comment by yaira2** [comment]
@MrFrawsty regular TextBoxes and TextBlocks inherit the font correctly, this issue is specific to the context menu.

**Comment by MrFrawsty** [comment]
Oh my mistake. I'll just look at the context menu then.

**Comment by yaira2** [comment]
@i-dont-know-username this issue will be resolved in the next update.
