### ISSUE TITLE
win11 22624.1546右键会出现卡死，然后闪退

### ISSUE THREAD

**Issue by tangyajun007** [files-community/Files#12022]
### Description

win11 22624.1546右键会出现卡死，然后闪退 

### Steps To Reproduce

访问任何盘，右键文件或者文件夹，就会出现卡死，过一会就会闪退

### Requirements

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

2.4.61.0

### Windows Version

10.22624.1546

### Log file

[debug.log](https://github.com/files-community/Files/files/11184692/debug.log)

**Comment by Josh65-2201** [comment]
Can you see if this is an issue in 2.4.62.0 https://files.community/download (Select preview) and post the updated log if it happens

**Comment by yaira2** [comment]
@tangyajun007 thank you for reporting this issue, does this issue only occur when right clicking on certain file types?

**Comment by hishitetsu** [comment]
This may be fixed by #12089.

**Comment by yaira2** [comment]
@tangyajun007 this appears to resolved in v2.4.66, but please let us know if it's still occurring after the update.
