### ISSUE TITLE
Linux Paths converted to Windows Paths

### ISSUE THREAD

**Issue by ldsands** [files-community/Files#1203]
**Is your feature request related to a problem? Please describe.**
Given how often people are using WSL now on Windows it would be nice if we could put in a Linux path and have it bring up that location in the tab. For example, when clicking on the new tab address bar and pasting in a linux path.

![image](https://user-images.githubusercontent.com/7889104/85324360-4fc73600-b48f-11ea-9c85-44c8df16f7f5.png)

**Describe the solution you'd like**
Ideally if some simple regex could be applied to convert POSIX paths to Windows paths. Would that be easy?

for the image above for example it would ideally change from 
`/mnt/f/GithubRepos/path/location` to `F:\GithubRepos\path\location`

**Additional context**
Maybe the following link might help?

[Regex for regnizing Windows and POSIX paths](https://stackoverflow.com/a/42036026)

**Comment by duke7553** [comment]
Thanks for opening this feedback item. I will likely get to implementing this one when better WSL support is added. I can't announce an ETA on that just yet.

**Comment by yaichenbaum** [comment]
@ldsands Thank you for opening this issue, this feature was implemented with v1.2.
