### ISSUE TITLE
It is necessary to allow the use of the built-in window for copying / moving files in Windows.

### ISSUE THREAD

**Issue by BezCommentariev** [files-community/Files#12032]
### What feature or improvement do you think would benefit Files?

you need to add a switch that allows you to use the built-in copy / move files window in Windows.

### Requirements

You need to add (in the "advanced" or "preferences" menu a switch that allows you to use the built-in copy / move files window in Windows. Using Files is inconvenient.

### Files Version

2.4.61.0

### Windows Version

10.0.22621.1413

### Comments

![2023-04-09 221714](https://user-images.githubusercontent.com/129542833/230792678-3b79cd0f-e82b-4d34-936d-da10ba28dabe.png)

**Comment by Josh65-2201** [comment]
There are improvements being discussed in #11524 and a speed graph in #11265. Is there any other reason for you wanting to use Windows version?

**Comment by yaira2** [comment]
@BezCommentariev we're going to continue tracking improvements in #11524 and #11265.

**Comment by yaira2** [comment]
@BezCommentariev we're currently working on the speed graph, and the plan is to include it in the v3 release.
