### ISSUE TITLE
Feature: Add invalid name and path warnings to modals

### ISSUE THREAD

**Issue by ferrariofilippo** [files-community/Files#12044]
### What feature or improvement do you think would benefit Files?

At the moment, when you try to create a shortcut, if you enter a non existing path, `Create` button will be disabled but no reason is shown.
Thre's a similar issue when creating archives: you can enter whatever name you want (even using forbidden chars), and the `Create` button will always be enabled. If the name contains forbidden chars, the creation of the archive will fail and no reason will be given (only `Couldn't create the archive`)
Finally, there's a warning tip when we you try to create a file with an invalid name. This is a simple text block and looks different from the one used in tag creation. I think we should always use the same style to be consistent

### Requirements

- Add a warning tip when the shortcut path doesn't exist
- Add a warning tip when the archive name isn't valid
- Change the style of the warning tip of the `Rename` dynamic dialog 

### Files Version

2.4.61.0

### Windows Version

Windows 11 Pro 22H2 10.0.22621.1485

**Comment by yaira2** [comment]
@ferrariofilippo can you share the design you're planning to use?

**Comment by ferrariofilippo** [comment]
I posted them in #11977

**Comment by yaira2** [comment]
![image](https://user-images.githubusercontent.com/39923744/232090201-4bf0c478-674c-4ca6-9821-ed54bee1cac8.png)
![image](https://user-images.githubusercontent.com/39923744/232090223-04060a6c-1d92-49d9-b564-4a4e9cee5cec.png)
![image](https://user-images.githubusercontent.com/39923744/232090249-2da6400c-c30a-454d-872d-5a43508bb68a.png)

**Comment by yaira2** [comment]
Something about this design isn't resonating with me, perhaps it's the tight margins or the fact that the size of the dialog changes. Can you try using a teaching tip?

**Comment by ferrariofilippo** [comment]
@yair100 Which of the two?
1:
![3](https://user-images.githubusercontent.com/102259289/232135117-315bd410-3b81-4fc7-992c-aafa38abfc1a.png)

2:
![2](https://user-images.githubusercontent.com/102259289/232135122-547f4063-82b1-490b-b0da-27bc77a9b987.png)

**Comment by yaira2** [comment]
The first one looks better.

**Comment by ferrariofilippo** [comment]
Sorry for the ping

**Comment by ferrariofilippo** [comment]
If the user closes the tip using the 'x' it won't be displayed on that dialog, should I disable it?

**Comment by yaira2** [comment]
Will changing the text reopen the teaching tip? I think it's okay to keep the "x" considering that it's a way of acknowledging the message.

**Comment by ferrariofilippo** [comment]
> Will changing the text reopen the teaching tip?

No, you have to open reopen the modal

**Comment by yaira2** [comment]
That seems like an limitation in the implementation, let's move forward regardless and if I notice a fix when reviewing the PR, I'll let you know.

**Comment by ferrariofilippo** [comment]
What about adding a visual state to turn its border to red?
I mean, we would leave the tip, this would be a second warning

**Comment by yaira2** [comment]
> What about adding a visual state to turn its border to red?

Let's try with the teaching tip and wait for feedback to see if more changes are necessary.
