### ISSUE TITLE
Shorten the Days of the Week!

### ISSUE THREAD

**Issue by itsJavaCoder** [files-community/Files#1204]
**Is your feature request related to a problem? Please describe.**

**I just went through my files and the date modified almost touched the file type. Being me, this is very irritating and frustrating.**

**Describe the solution you'd like**

**I would like for you to shorten the days of the week for example: Sun=Sunday, Mon=Monday ,Tue=Tuesday, Wed=Wednesday, Thu=Thursday, Fri=Friday, and Sat=Saturday. Remove the space between the day of the week and the month so in all, the format would be like: Fri July 17, 2020.**

**Describe alternatives you've considered**

**N/A**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**N/A**

**Comment by R3voA3** [comment]
I'd rather see the columns being auto adjusted or the width of the columns being increased.

**Comment by yaichenbaum** [comment]
Merging with #2207.
