### ISSUE TITLE
Bug: Files crashes sometimes when deleting/moving folders

### ISSUE THREAD

**Issue by JasonTan94** [files-community/Files#12042]
### Description

It freezes when I delete a folder containing images (png in my case). Then it just crashes even when the folder only contains 1 image in it. Happens every time, so I just open up file explorer instead and remove it myself.

### Steps To Reproduce

1. Select a folder that contains images.
2. Click the delete icon on the top ribbon bar.

### Requirements

- Fix crash that occurs when deleting a folder containing images.

### Files Version

Version: 2.4.62.0

### Windows Version

Windows 10 Pro 21H2 10.0.19044.2788

### Log file

[debug.log](https://github.com/files-community/Files/files/11196095/debug.log)

**Comment by yaira2** [comment]
@JasonTan94 thank you for reporting this issue, can you confirm if this issue is an issue in the preview version as well? https://files.community/download

**Comment by tarokawa516** [comment]
@yair100 Thank you, I tried to reproduce my issue https://github.com/files-community/Files/issues/12060 with new preview version, and looks the bug has now fixed!

**Comment by yaira2** [comment]
@tarokawa516 thank you for the update, I'm happy to hear it's working properly now. We're going to keep this open a little longer to confirm if it's fixed for @JasonTan94 as well.

**Comment by JasonTan94** [comment]
Yes, the bug has been fixed, thank you @tarokawa516 and @yair100.
