### ISSUE TITLE
Bug: Stuck in crash loop when a symbolic link points a Google Drive folder

### ISSUE THREAD

**Issue by jandye** [files-community/Files#12041]
### Description

Crashes when viewing folder with symbolic link to a folder. Appears to be just an issue pointing to a folder on a Google Drive virtual drive (i.e. "Stream files" syncing option, did not test "Mirror files" option).

Also if set to "Continue where you left off", will continually crash whenever trying to open again. Can escape the loop by right clicking on the taskbar icon and selecting a different folder.

Tested pointing a symlink to other folder locations and it seems to work fine. Also tested symlink to file on Google Drive and seems to work fine.

### Steps To Reproduce

1. With Google Drive installed and Stream Files set as syncing option
2. Open command prompt as admin
2. Create a symbolic link to a folder on Google Drive e.g.
		mklink /d "%UserProfile%\Downloads\Course Contents" "G:\My Drive\Studies\Course Contents"
3. Open folder where symlink is located e.g. %UserProfile%\Downloads
4. Crash...

### Requirements

1. Don't crash when viewing a folder with symlink to GDrive
2. Maybe also if set to "Continue where you left off" and detects a crash immediately after opening, then re-open to default home/new tab to break crash loop

### Files Version

2.4.61.0

### Windows Version

Windows 10 - 10.0.19045.2788

### Log file

2023-04-11 15:21:59.1695|Information|App launched. Launch args type: LaunchActivatedEventArgs
2023-04-11 15:21:59.5840|Information|Drive added: C:\, Fixed
2023-04-11 15:21:59.6331|Information|Drive added: H:\, Fixed
2023-04-11 15:21:59.8950|Information|Drive added: U:\, Network
2023-04-11 15:21:59.9313|Information|Adding cloud provider "Google Drive" mapped to H:\
2023-04-11 15:22:01.0650|Information|Running on ARM: False
2023-04-11 15:22:01.3916|Error|Source object type is not a projected type and does not inherit from a projected type. (Parameter 'value')

**Comment by yaira2** [comment]
@Jay-o-Way can you still repro this? Can you upload the log file?

**Comment by Jay-o-Way** [comment]
Haven't seen it bug out in a while, no.

**Comment by Jay-o-Way** [comment]
Haven't seen it bug out in a while, no.
