### ISSUE TITLE
Bug: Ctrl + A shortcut isn't selecting text when renaming files

### ISSUE THREAD

**Issue by francisco-lafe** [files-community/Files#12040]
### What feature or improvement do you think would benefit Files?

Hello, I work with the extensions of the files shown, when I press F2 to change the file name, I also press CTRL+A to edit the whole name of the file. Or copy the name of the file. 
On Windows Explorer, pressing F2 enables the change name for the file (files does this too) and then CTRL+A selects the entire text on the text box. 

![image](https://user-images.githubusercontent.com/90066435/230964598-6b6a4a70-20f5-41f1-a75c-84e2f9ff8871.png)

### Requirements

- This proposal will achieve the functionallity of the combination CTRL+A to select the entire text inside the textbox

### Files Version

2.4.61.0

### Windows Version

10.0.19044.2728

**Comment by yaira2** [comment]
Thank you for bringing this to our attention, this looks like a bug.

**Comment by francisco-lafe** [comment]
No problem, thank you 😄

**Comment by yaira2** [comment]
A fix will be included in the next release.
