### ISSUE TITLE
Feature: Disable keyboard shortcuts when renaming items

### ISSUE THREAD

**Issue by ferrariofilippo** [files-community/Files#12053]
### What feature or improvement do you think would benefit Files?

I think that keyboard shortcuts that are not related with editing should be disabled when renaming items.
We should still handle other common shortcuts such as `Esc`, `Ctrl + A`, ...

### Requirements

- This feature will prevent future issues involving RichCommands remapping (think of a user assigning a shortcut to `Shift + Letter`)

### Files Version

2.4.61.0

### Windows Version

Windows 11 Pro 22H2 10.0.22621.1485

**Comment by yaira2** [comment]
We have a lot of checks in place, but it's a good idea to simplify the code and disable them altogether.
