### ISSUE TITLE
Unable to click on the first option in the right-click menu that covers the title bar

### ISSUE THREAD

**Issue by sirwgame** [files-community/Files#12059]
### Description

When the right-click menu pops up and covers the top of the title bar, the first menu cannot be clicked, and if it covers the minimum and maximum buttons of the program, the maximum and minimum buttons will be directly clicked instead of the menu.
![1681367526334](https://user-images.githubusercontent.com/39762146/231673455-19673f21-b89c-485e-89f7-0da035ef85e8.jpg)
![1681367573211](https://user-images.githubusercontent.com/39762146/231673626-2dd76380-4ceb-444c-bb7a-dac2fd0ee068.jpg)

### Steps To Reproduce

1. Ensure there is a long right-click menu
2. Right click in the program blank near the title menu section
3. Popup the right-click menu to see the effect

### Requirements

Each option in the right-click menu can be clicked correctly

### Files Version

2.4.62.0

### Windows Version

10.0.19044.2728

### Log file

[debug.log](https://github.com/files-community/Files/files/11218951/debug.log)

**Comment by ferrariofilippo** [comment]
Duplicated #10823
