### ISSUE TITLE
Bug: Some of the key names are not correct

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#12054]
### Description

VirtualKey.Menu is represented as "Menu" in the string resources, but this key is Alt key, so it should be represented as "Alt".
For the same reason, I think VirtualKey.Back should be represented as "Backspace" and VirtualKey.Escape should be represented as "Esc".

### Steps To Reproduce

1. See tooltips of navigation buttons.
2. Shortcuts that should be represented as "Alt+..." are represented as "Menu+...".

### Requirements

Match string resources to the representation on the keyboard.

### Files Version

2.4.61.0

### Windows Version

Windows 11 22H2

### Log file

n/a

**Comment by hecksmosis** [comment]
I'll do this

**Comment by yaira2** [comment]
@hishitetsu this issue has been resolved.
