### ISSUE TITLE
Bug: Property window crashes randomly

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#12057]
### Description

Files suddenly crashes when repeatedly opening and closing property windows or moving sections.
The timing of the crash is random, and the same steps may or may not result in a crash.

### Steps To Reproduce

1. Open and close property windows or move sections repeatedly.
2. Files crashes.

### Requirements

Do not crash.

### Files Version

2.4.61.0

### Windows Version

Windows 11 22H2

### Log file

No error log found. AccessViolationException seems to occur.
![スクリーンショット 2023-04-18 121930](https://user-images.githubusercontent.com/66369541/232663074-0395b825-089e-4375-8d5f-fdfbb4a6d842.png)

**Comment by StarKnightt** [comment]
I think you need to upgrade it, because as you mentioned that you are in 2.4.61.0 version of this software but the current version is 2.4.61.1, Here you can read the release notes 👇🏻
 https://github.com/files-community/Files/releases/tag/v2.4.61

**Comment by yaira2** [comment]
@hishitetsu thank you for reporting this issue. I was able to reproduce it as well.

**Comment by yaira2** [comment]
I can confirm this is still an issue in v2.4.80.

**Comment by hishitetsu** [comment]
It seems that once the properties window is opened, the crash will then occur even when operating the main window.
