### ISSUE TITLE
Run With Powershell does not always work if files is run as small window

### ISSUE THREAD

**Issue by Sahnreis** [files-community/Files#12062]
### Description

If you run files as a small window(like quarter of a fullhd screen or less) the "run with powershell" command is not clickable and does also not react to a mouse hover.
Normal behavior is immediately restored as soon as the window is enlarged.

### Steps To Reproduce

1. open files
2. reduce window size with drag and drop
3. right click on some script
4. click "show more options"

### Requirements

- it should always be possible to click the command
- the size should not matter

### Files Version

2.4.61.0

### Windows Version

10.0.19044.2846

### Log file

[debug.log](https://github.com/files-community/Files/files/11226669/debug.log)

**Comment by Josh65-2201** [comment]
Is this option on the title bar? #10823

**Comment by Sahnreis** [comment]
if its not working: yes, the option overlaps the title bar.
but if you resize the window to be more like a "portrait mode" it works again despite overlapping. not shure if its 100% related to the overlapping but seems to be an duplicate of the linked Bug.
