### ISSUE TITLE
Crashed while moving a file in dropbox to another dropbox folder

### ISSUE THREAD

**Issue by tarokawa516** [files-community/Files#12060]
### Description

Crashed unfortunately.

### Steps To Reproduce

1. Save a PSD file to dropbox root folder.
2. Cut it
3. Open another dropbox folder
4. Paste it - something went wrong and crashed

### Requirements

- shouldn't crash of cause...

### Files Version

2.4.61.0

### Windows Version

10.0.22621.1555

### Log file

[debug.log](https://github.com/files-community/Files/files/11223188/debug.log)

**Comment by Josh65-2201** [comment]
Merging with #12042

From the logs this is the same error and cause as the above linked issue.
