### ISSUE TITLE
Bug: Cannot delete file

### ISSUE THREAD

**Issue by MeiVinEight** [files-community/Files#12063]
### Description

I have set the Files.exe run as admin, but it also can't delete file which need admin.

### Steps To Reproduce

1. Create a new file
2. Change it's permission, disable inheritance and add two users: `Administrators` has full control, and `Users` only has read permissions.
3. Delete this file use Files App
4. You will  find that Files App can't delete this file but Windws file explorer.exe can do it.

### Requirements

- Let the Files App can delete that file

### Files Version

Version: 2.4.61.0

### Windows Version

Windows 11 22H2 23424.1000

### Log file

[debug.log](https://github.com/files-community/Files/files/11228622/debug.log)

**Comment by MeiVinEight** [comment]
Bug right click Files App and choose Run as admin, Files App can delete that file, so setting Files.exe run as an admin doesn't seem like the best approach.

**Comment by gave92** [comment]
Merging with #10422

**Comment by yaira2** [comment]
This issue is resolved in our dev branch and will be included in the next release.
