### ISSUE TITLE
Delete some files

### ISSUE THREAD

**Issue by ferdher** [files-community/Files#12061]
### Description

I was selecting some archives/folders to delete but i selected them with ctrl+click for select random archives and when i try delete the selection of files the program crashes and it didn´t deleted the files that i was selected

### Steps To Reproduce

1. I select some files using ctrl+click to select ramdom files 
2. next i do click on delete button
3. program crashes

### Requirements

i dont know how to fix the issue, the issue tha i discover its about delete option selecting some ramdom files and not using the shift+click option, i used ctrl+click option to select some files and not all

### Files Version

2.4.61.0

### Windows Version

10.0.19045.2846

### Log file

[debug.log](https://github.com/files-community/Files/files/11226178/debug.log)

**Comment by Josh65-2201** [comment]
Merging with #12042

From the logs this is the same error and cause as the above linked issue.
