### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by RaulNY878** [files-community/Files#12075]
### Description

error crash

### Steps To Reproduce

error crash

### Requirements

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

new version previwer

### Windows Version

Windows 11 22H2

### Log file

error crash

**Comment by Josh65-2201** [comment]
Thanks for the feedback. Please make a new issue following the issue templates. It tells you how to fill it out if you don't know what to put for a section.

**Comment by yaira2** [comment]
@RaulNY878 in particular, we need you to fill out the steps to reproduce the crash so that we can try to reproduce the issue and work on a fix.
