### ISSUE TITLE
Bug: Silent Exception when rapidly switching columns with keyboard in ColumnView

### ISSUE THREAD

**Issue by QuaintMako** [files-community/Files#12072]
### Description

A silent exception that doesn't provoke a crash nor a freeze may be catched when rapidly switching between the blades in the column view. It does not seem to be possible to be catched when doing it with the mouse, hinting to an issue with rapid inputs.

Solving it will help us keep cleaner logs, and would prevent possible side effects that are not yet discovered.

### Steps To Reproduce

1. Go in ColumnView, inside a folder containing other folders with at least a depth of two.
2. Rapidly switch between the blades using the right and left keyboard keys.
3. An exception will be raised. 

### Requirements

- No exception raised when switching rapidly between blades.

### Files Version

Version 2.4.64 Dev

### Windows Version

W10 Home 22H2 19045.2251

### Log file

[debug.log](https://github.com/files-community/Files/files/11238708/debug.log)

**Comment by ferrariofilippo** [comment]
@QuaintMako this might be fixed by #11986 (I added a null check)

**Comment by QuaintMako** [comment]
> @QuaintMako this might be fixed by #11986 (I added a null check)

Well, it does fix the issue, but it seems to bring some really heavy slowdowns for me.

**Comment by ferrariofilippo** [comment]
I can't reproduce that, on my side it seems to work as before. I don't even know what could be the cause, there are no big changes, I mean there are 2 more ifs but nothing that should impact on performances

**Comment by ferrariofilippo** [comment]
@QuaintMako is this still a bug? If no, are there any slowdowns?

**Comment by QuaintMako** [comment]
I'll look into it hopefully tomorrow

**Comment by QuaintMako** [comment]
@ferrariofilippo it seems it has been fixed, and on the slowdowns, not anything that wouldn't be expected of a madman smashing their keyboard. It can be closed for me, good job!
