### ISSUE TITLE
Code Quality: Reusable control for thumbnail display with overlay

### ISSUE THREAD

**Issue by QuaintMako** [files-community/Files#12071]
### Description

The thumbnails in Files may sometimes be displayed with an overlay over them, to show different information such as being a shortcut. We currently are adding all those information separatedly. They could be gathered within a single reusable control for thumbnail, handling the display of overlays.

### Concerned code

- ItemViewModel
- ColumnViewBase, DetailsLayout et GridLayout

### Gains

- Better readability
- Duplication reducation

### Requirements

- Have a reusable control for thumbnail
- Have a reusable control for overlays so that we can use it indecently from the thumbnail control (eg. the grid layouts).
- Add a DisplayOverlay property (or something along these lines) to the thumbnail control. Setting the property to true will load the overlay inside the thumbnail control.

**Comment by yaira2** [comment]
Besides for layouts, we can use this for the sidebar and home page widgets.

**Comment by mdtauk** [comment]
Are we rolling Status Icons and the Explorer Overlay Icons, into a single control?

The Explorer API supports only a single overlay icon, and the guidance is for app devs to display their icons in the Status column, for modern apps.

https://devblogs.microsoft.com/oldnewthing/20190313-00/?p=101094

**Comment by yaira2** [comment]
> Are we rolling Status Icons and the Explorer Overlay Icons, into a single control?

Overlays will be a separate control, however, the icon control will have the overlay control built-in as well. I'll update the requirements to clarify this point.

**Comment by mdtauk** [comment]
> > Are we rolling Status Icons and the Explorer Overlay Icons, into a single control?
> 
> Overlays will be a separate control, however, the icon control will have the overlay control built-in as well. I'll update the requirements to clarify this point.

So we are going to persist with the actual overlay on top of the main file icon.

**Comment by yaira2** [comment]
We will in the sidebar, columns layout, details layout, recent files widget, properties window and details pane.

**Comment by mdtauk** [comment]
> We will in the sidebar, columns layout, details layout, recent files widget, properties window and details pane.

Can I just confirm, the areas you mentioned above.  This is where the Overlay Icon will be treated like the Status Icons right?

But for now on the Icon Views, you will have them overlap the main icon or thumbnail?

**Comment by yaira2** [comment]
The other way around, icon views will have them separate while the other areas will have them overlaying on the main icon.

**Comment by mdtauk** [comment]
> The other way around, icon views will have them separate while the other areas will have them overlaying on the main icon.

Those examples you mentioned mostly use the 16 x 16 icons, overlaying an icon on that makes it almost unreadable.  Details layout has the column you can place it in, Sidebar does not really benefit from displaying an overlay icon.
