### ISSUE TITLE
Bug: System.AccessViolationException in ContextMenu

### ISSUE THREAD

**Issue by btomblinson** [files-community/Files#12078]
### Description

I was trying to work on issue #11580 but when I right click on a file or a folder and try to make an archive of it, Files crashes with the attached error.

I am running the master branch using the latest code. I even tried checking out v2.4.40 tag/release since that was the version mentioned on the issue and I still get the same error.

https://user-images.githubusercontent.com/16448374/232260674-3c842e94-b8f5-48c7-95a2-072cf0937657.mp4

### Steps To Reproduce

Run latest code
Right click on a file or folder and select archive

### Requirements

Do not crash when trying to archive a file/ folder

### Files Version

master

### Windows Version

Windows 11 22H2

### Log file

Log doesn't show much

[debug.log](https://github.com/files-community/Files/files/11240991/debug.log)

**Comment by yaira2** [comment]
Thank you for reporting this issue, this happens for me as well and I mentioned it to @hishitetsu but they can't reproduce it so it might be device specific.

**Comment by btomblinson** [comment]
@yair100 are you using Windows 10 or 11? Might be a Windows 11 bug. I can try to run on a Windows 10 machine if necessary. Regardless it’s definitely a major issue on Windows 11 since it prevents users from creating archive files.

**Comment by yaira2** [comment]
Windows 11, I should note that it's only in debug mode. I can't reproduce the issue in release.

**Comment by hishitetsu** [comment]
I don't think this is an archive file creation issue, but a shell extension loading issue.
There is the following workaround in the same class. Do we need the same workaround here?
```csharp
			// Hackish workaround to avoid an AccessViolationException on some items,
			// notably the "Run with graphic processor" menu item of NVidia cards
			if (offset > 5000)
				return null;
```
However, if it only happens in debug mode, I would like to leave it as is without extra workarounds.

**Comment by btomblinson** [comment]
Yeah I just noticed it because I was trying to work on #11580 so I was running in debug and using the context menu to select create archive. I have no issue with adding a “hack” to get around it if that’s the only option. Could also use #if debug pre processor so the hack is only used in debug build configuration

**Comment by hishitetsu** [comment]
@btomblinson Can you try to add the hack if possible? I can't confirm if it works as I can't reproduce.

**Comment by btomblinson** [comment]
Well now that I look at it more, on line 273 of contextmenu, should we just add the accessviolationexception to the catch so we just ignore it? Only concern is if it causes downstream problems but I can test that instead of adding a “hack” around that try catch

**Comment by hishitetsu** [comment]
It is a bad idea to catch the AccessViolationException in general, but if you just want to work on #11580, it is worth a try.

**Comment by hishitetsu** [comment]
Or you can comment out and skip this process, because creating archive doesn't use shell extensions. Anyway this is about #11580, not this issue.

**Comment by yaira2** [comment]
> There is the following workaround in the same class. Do we need the same workaround here?
> However, if it only happens in debug mode, I would like to leave it as is without extra workarounds.

This was just my experience but it's possible that it happens for others in release, it might be worth adding the work around just in case.

**Comment by hishitetsu** [comment]
@yair100  @btomblinson 
In this PR, the same workaround is applied when loading submenus. Could you try to see if this solves the issue?

**Comment by yaira2** [comment]
@btomblinson can you confirm this issue is fixed?
