### ISSUE TITLE
BUG Deleteing

### ISSUE THREAD

**Issue by ell1712** [files-community/Files#12076]
### Description

when deleting any file or folder it always bug, so it didnt delete the file or folder

### Steps To Reproduce

press delete

### Requirements

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

2.4.62.0

### Windows Version

Edition	Windows 11 Home Single Language Version	22H2 Installed on	‎3/‎29/‎2023 OS build	22621.1555 Experience	Windows Feature Experience Pack 1000.22640.1000.0

### Log file

bug delete

**Comment by Josh65-2201** [comment]
Can you please upload (Do not copy and paste content) the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.

**Comment by yaira2** [comment]
@ell1712 are you by any chance using the delete key on the num pad?

**Comment by yaira2** [comment]
This is possibly related to #11501.
