### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by Prodigio** [files-community/Files#12079]
### Description

I simply downloaded latest release `.exe`  and am executing it as Administrator. It won't install with the following error message:

![grafik](https://user-images.githubusercontent.com/18284425/232264591-bd93be67-961e-4051-8305-6d4262723847.png)

(which basically means "Error occurred due to logoff of a user.")

### Steps To Reproduce

1. Login as Windows user without administratort priviliges
2. Execute `Files.Stable.exe` via right-click menu with Administrator priviliges 
    - (Windows prompt for Administrator user passwort pops up)
4. Provide password and press Enter
5. Won't install

### Requirements

- Logged on as Windows user without Administrator priviliges
- Execute `Files.Stable.exe` as Administrator via right-click menu

### Files Version

2.4.62.0

### Windows Version

Windows 10 22H2 (Build 19045.2846)

### Log file

No logfile is created. Cannot provide one. No logs are created in Windows event manager either.

**Comment by yaira2** [comment]
Does the preview version work?

**Comment by yaira2** [comment]
https://files.community/download

**Comment by yaira2** [comment]
Based on this, the Store version should also work.

**Comment by filipeaguiar** [comment]
I have the same problem. Neither version works

**Comment by yaira2** [comment]
> I have the same problem. Neither version works

What happens if you try the preview version?
