### ISSUE TITLE
Rightclicking on a touchscreen when Files UWP starts crashes/freezes it

### ISSUE THREAD

**Issue by PeterStrick** [files-community/Files#1208]
**Describe the bug**
Files UWP will crash/freeze if you try to rightclick a folder/file on a touchscreen (hold to rightclick) when it starts.

**To Reproduce**
1. Start Files UWP
2. Rightclick something without selecting anything
3. See it crash/freeze

**Expected behavior**
Don´t crash/freeze and show the context menu.

**Screenshots**
Videorecording in zip file: 
[videorec.zip](https://github.com/files-community/files-uwp/files/4817484/videorec.zip)

**Desktop:**
 - OS Version: Windows 10 2004 19041.329
 - App version: 0.10.2.0

**Additional context**
Rightclicking when selecting smething first doesn´t crash/freeze it.

**Comment by Jaiganeshkumaran** [comment]
Can you post the log file?

**Comment by PeterStrick** [comment]
> Can you post the log file?

[debug.txt](https://github.com/files-community/files-uwp/files/4829461/debug.txt)

Here you go.

**Comment by Jaiganeshkumaran** [comment]
@PeterStrick Thanks for the log file. I'm working on a fix for this issue.

**Comment by jaigak** [comment]
@yair100 Could you assign me for this issue?

**Comment by Jaiganeshkumaran** [comment]
I don't have a touch screen to test but I will be opening a PR that tries to fix this issue soon.

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran Have you made any progress on this issue?

**Comment by jaigak** [comment]
@yair100 Please assign this issue with someone who has a touch screen.

**Comment by Thomas1664** [comment]
@yair100 Can you assign me for this issue? I do have a touch screen.
