### ISSUE TITLE
Icons too dark

### ISSUE THREAD

**Issue by PauloDaniel1993** [files-community/Files#12082]
### Description

For some reason, the icons are extremely dark.
![image](https://user-images.githubusercontent.com/97897297/232312826-08fa7664-7ba5-4255-b8ce-94703c05d06c.png)

Is this the expected behaviour?
If no, from where the colours are retrieved?

### Steps To Reproduce

1. Run files
2. right click anywhere

### Requirements

- Colourful icons

![image](https://user-images.githubusercontent.com/97897297/232312886-28f1b9b7-363d-4891-9e64-0e3bae362d58.png)

### Files Version

2.4.61.0

### Windows Version

10.0.22621.1546

### Log file

**Comment by Josh65-2201** [comment]
Icons accents are set by your Windows accent color. Do you have it set to grey?

**Comment by yaira2** [comment]
It's recommended to use a lighter accent color in dark mode for this reason.

**Comment by PauloDaniel1993** [comment]
Thanks a lot, I did not see this part of the accent in the documentation
