### ISSUE TITLE
Bug: Crash or hang up when opening properties about image files

### ISSUE THREAD

**Issue by Shadow912kage** [files-community/Files#12080]
### Description

Files crash or hang up when opening properties about image files.

### Steps To Reproduce

1. Right-click on the image file then open the properties dialog.
2. Wait a minute... then the mouse cursor will be busy.
3. Files crash or hung up.

### Requirements

Fix the crash that occurs when opening properties about image files.

### Files Version

Filles 2.4.62.0

### Windows Version

Windows 10 Pro 22H2 10.0.19045.2908, insider preview

### Log file

[debug.log](https://github.com/files-community/Files/files/11241826/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report. Does this happen on all image files or only a certain one.

**Comment by Shadow912kage** [comment]
> Thanks for the report. Does this happen on all image files or only a certain one.

As far as I can tell, it happens with all image files.
And same issue occurs on the Files preview 2.4.64.0.
In my opinion, It seems to depend on Windows 10 Pro 22H2 preview release 10.0.19045.2908.

**Comment by yaira2** [comment]
@Josh65-2201 are you able to repro this issue?

**Comment by Josh65-2201** [comment]
Files hasn't crashed for me but it does send the "something when wrong" notification and my log shows the same error as the one on the issue.

**Comment by yaira2** [comment]
@Shadow912kage is this the same as #12057?

**Comment by Shadow912kage** [comment]
> @Shadow912kage is this the same as #12057?

Maybe another issue.
Not reproduced #12057 on the Files 2.4.62.0/preview 2.4.65.0, Windows 10 Pro 22H2 preview release 19045.2908.

**Comment by Shadow912kage** [comment]
thx. all!
I confirmed this issue was resolved on Files ver.2.4.66.0
