### ISSUE TITLE
Bug: Search result button to search unindexed items is not clickable

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#12085]
### Description

*

### Steps To Reproduce

1. Disable Files settings > Preferences > Include unindexed items in search results
2. Search for anything in files
3. Attempt to click the search unindexed items button.

### Requirements

- Fix search unindexed items not acting like a button

### Files Version

2.4.64.0

### Windows Version

10.0.22621.1555

### Log file

[debug.log](https://github.com/files-community/Files/files/11242718/debug.log)

**Comment by ferrariofilippo** [comment]
At the moment that is an hyperlink not a button

**Comment by yaira2** [comment]
@Josh65-2201 this issue will be fixed in v2.5.
