### ISSUE TITLE
Bug: Can't select some files in column view

### ISSUE THREAD

**Issue by rafaskb** [files-community/Files#12090]
### Description

When trying to select some files in column view by clicking them, Files closes all subsequent subfolders opened in columns and returns to the first column.

https://user-images.githubusercontent.com/2331058/232351898-5d8615ef-9948-4ab1-bed3-3e98c491582b.mp4

### Steps To Reproduce

1. Open some folders in column view
2. Try to select files of different names and types (I haven't narrowed down the exact issue)
3. Some of them will cause the bug to happen

### Requirements

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

2.4.62.0

### Windows Version

10.0.19044.2846

### Log file

There are no logs about the bug in the debug.log file, but I attached it anyways. The bug happened at on 2023-04-16 around 9 PM.

[debug.log](https://github.com/files-community/Files/files/11245022/debug.log)

**Comment by yaira2** [comment]
Thank you for bringing this to our attention, it also looks like the tag icon is misaligned but that's a separate issue.

**Comment by ferrariofilippo** [comment]
Can you tell us how did you set these?
![6](https://user-images.githubusercontent.com/102259289/232409043-a8d86bd0-74eb-45aa-bdc4-3219f3d984c9.png)

**Comment by rafaskb** [comment]
> Can you tell us how did you set these?

Here it is
![image](https://user-images.githubusercontent.com/2331058/232490770-8a98fbc6-107c-4319-9dab-a550373b51fa.png)

**Comment by hishitetsu** [comment]
This seems to occur when a shortcut to a folder is selected and then a file further on is selected.
When a shortcut is selected, should the shortcut destination be opened in a new column as if it were a symbolic link?

**Comment by yaira2** [comment]
Would it be worth checking the behavior in Finder?

**Comment by hishitetsu** [comment]
The same behavior is observed in Finder. So this behavior should not be changed and the file should be opened correctly.

**Comment by yaira2** [comment]
@rafaskb we implemented a fix and it'll be included in one of the next releases.
