### ISSUE TITLE
Custom context menu items aren't shown when right-clicking empty space

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#1209]
**To reproduce**

1. Install any app that adds a custom context menu for folders (ex: Git for Windows).
2. Select a folder and right click. You'll see the custom context menu item added by the application.
3. Now right click on empty space, you won't see the custom context menu.

**Screenshots**

![2020-06-25](https://user-images.githubusercontent.com/45227503/85737310-e52b2a00-b71c-11ea-8863-47e3745b54df.png)

![2020-06-25 (2)](https://user-images.githubusercontent.com/45227503/85737220-d2b0f080-b71c-11ea-91f8-3bc5628d10f3.png)

**Desktop:**

- OS: Windows 10 Home Single Language Version 1903 (Build 18362.900)

- App version: v0.10.5.0 (Downloaded from the Microsoft Store)

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran Can you please add more details such as the app version and steps to reproduce this issue?

**Comment by Jaiganeshkumaran** [comment]
**To reproduce**

1. Install any app that adds a custom context menu for folders (ex: Git for Windows).
2. Select a folder and right click. You'll see the custom context menu item added by the application.
3. Now right click on empty space, you won't see the custom context menu.
