### ISSUE TITLE
Favorites not shown

### ISSUE THREAD

**Issue by DanielDrechsel** [files-community/Files#12109]
### Description

since yesterday i can't see my favorites. 
i tried to add another folder, but this folder is also not shown 
![image](https://user-images.githubusercontent.com/131137959/232692680-0a180a40-9931-4d2e-9f9f-094adf218de8.png)

### Steps To Reproduce

1. Start FileExplorer
2. Favorites are not shown
3. 
![image](https://user-images.githubusercontent.com/131137959/232692766-980dc971-d056-45c9-9e0d-a668c50040cf.png)

### Requirements

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

2.4.62.0 

### Windows Version

Win 11 21H2 Version 10.0.22621 Build 22621

### Log file

[debug.log](https://github.com/files-community/Files/files/11258733/debug.log)

**Comment by yaira2** [comment]
@DanielDrechsel thank you for reporting this issue, can you see if this was resolved in the preview version? https://files.community/download

**Comment by DanielDrechsel** [comment]
yes it works now fine.Thanks
