### ISSUE TITLE
Context menu item is not selectable if is rendered above address bar

### ISSUE THREAD

**Issue by oleklukasiewicz** [files-community/Files#12102]
### Description

Context menu items that are rendered above address bar are not selectable.

![image](https://user-images.githubusercontent.com/69370471/232484249-3b6c79f0-891c-461b-8168-b24fa1c6667b.png)

### Steps To Reproduce

1. Go to any folder.
2. Right click folder space near columns headers.
3. Open sub menu used for adding new folder/item.
4. Try click/ hover  folder option.

### Requirements

- Make items that are rendered above addresss bar clickable.

### Files Version

2.4.62.0

### Windows Version

Windows 11 - 10.0.22621.1631

### Log file

none

**Comment by Josh65-2201** [comment]
Merging with #10823
