### ISSUE TITLE
Demande explorateur de fichier windows 11 par défaut

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12107]
Bonjour, je voudrais savoir si avec les fichiers de "Files" il serai possible d'inclure un fichier dans l'explorateur Windows 11 par défaut pour pouvoir mettre l'affichage par colonne et le personnaliser

**Comment by Josh65-2201** [comment]
I'm unsure what you mean. If you want to set Files as the default explorer then go to Files settings > Advanced > Enable Set as default. This does not work for the open/save dialogs yet but is planned.

Also for future requests please follow the issue templates.

**Comment by Lukiluc29** [comment]
Non je crois que je me suis mal exprimé. En gros je voudrais pouvoir intégrés un fichier appartenant à "Files" et l'intégrer directement dans l'explorateur Windows 11 et pouvoir en quelque sorte le personnaliser. Je voudrai inclure dans l'explorateur de fichier Windows 11 l'affichage par colonne

**Comment by Josh65-2201** [comment]
Windows File Explorer doesn't have a column view and nothing can be done by us. By integrate a file do you mean to move it from Files to Windows File Explorer? You should already be able to click and drag it over.

**Comment by Lukiluc29** [comment]
En gros ce que je veux faire c'est pouvoir intégrés le fichier contenant l'affichage par colonne de "Files" et l'intégrés dans la base de donnée de l'explorateur de fichier Windows 11 pour que celui-ci puisse avoir l'affichage par colonne qui n'est pas encore le cas pour l'instant dans celui de Windows

**Comment by Josh65-2201** [comment]
There is no file for column view. Files column view is coded and made separately. There isn't a way to transfer it to Windows File explorer, Microsoft world have to build that feature for it.

**Comment by Lukiluc29** [comment]
Donc il n(y a pas moyen de contourner Microsoft pour l'ajouter sois meme

**Comment by Josh65-2201** [comment]
No
