### ISSUE TITLE
the moviment of the windows

### ISSUE THREAD

**Issue by blackbird98888** [files-community/Files#12114]
### Description

the move the windows is slow and lag

### Steps To Reproduce

1.click the window
2.move the window
3.and look the window is slow and lag.

### Requirements

fix bug

### Files Version

Versione: 2.4.62.0

### Windows Version

windows 11 22H2  10.0.22621.1555

### Log file

[debug.log](https://github.com/files-community/Files/files/11266704/debug.log)

**Comment by yaira2** [comment]
@blackbird98888 the latest release (v2.4.66) includes WinAppSdk 2.3 which has some improvements for the refresh rate.
