### ISSUE TITLE
nothings

### ISSUE THREAD

**Issue by blackbird98888** [files-community/Files#12113]
### What feature or improvement do you think would benefit Files?

add the glass theme pls

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

Versione: 2.4.62.0

### Windows Version

windows 11 22H2

**Comment by yaira2** [comment]
Thank you for your feedback, please see our documentation to learn more about customizing the theme in Files https://files.community/docs/configuring/custom-themes. There are several sample schemes on that page including "glass"..
