### ISSUE TITLE
Feature: Change the behavior of toolbar and flyout buttons with modifier keys

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#12117]
### What feature or improvement do you think would benefit Files?

The ability to change the behavior of toolbar and flyout buttons with modifier keys would allow for a greater variety of operations.
For example, In FIle Explorer the delete button acts as permanent deletion while pressing `Shift`, but it doesn't in Files.

### Requirements

Create a mechanism to change the behavior of toolbar and flyout buttons with modifier keys.

### Files Version

2.4.65.0

### Windows Version

Windows 11 22H2

**Comment by yaira2** [comment]
Once someone is already using the keyboard, is there a reason they would use the shift + the toolbar button instead of shift + delete?

**Comment by hishitetsu** [comment]
When operating with a mouse, one hand is free and may press a modifier key with that one hand to change the action.
