### ISSUE TITLE
Sidebar: add "properties" in context menu of drives

### ISSUE THREAD

**Issue by XPoppyX** [files-community/Files#1212]
![Captura de pantalla (33)](https://user-images.githubusercontent.com/61259627/85471740-e292ce00-b57e-11ea-852f-3fcabb303a45.jpg)

**Comment by tobias-mayer** [comment]
What about displaying it for every item in the Sidebar, just like in Windows explorer?

**Comment by Thomas1664** [comment]
@yaichenbaum Can you assign me?

**Comment by yaichenbaum** [comment]
@Thomas1664 Done 👍.

**Comment by Thomas1664** [comment]
What about adding (almost) every context menu item to each sidebar item (except recycle bin and home)?

**Comment by yaichenbaum** [comment]
> What about adding (almost) every context menu item to each sidebar item (except recycle bin and home)?

That should work.

**Comment by Thomas1664** [comment]
@yaichenbaum Adding properties to drives works. However, it does not work for pinned folders because no properties are shown.
