### ISSUE TITLE
Feature: Font Color customization for theme

### ISSUE THREAD

**Issue by 0LBaID** [files-community/Files#12130]
### What feature or improvement do you think would benefit Files?

I was hoping that part of the "theme" configuration could include the font color customization option. I would like to choose my font color to contrast my theme color. Currently the white font is "blinding" with a dark theme color.Hope this can be added and thank you all for your hard work on Files, its a big step up from the native explorer.

### Requirements

- This proposal will accomplish adding the font color customization to themeing

### Files Version

2.4.66.0

### Windows Version

windows 10 22H2

**Comment by yaira2** [comment]
Thank you for your feedback, the challenge in overriding the font color is that different areas of the app use different font colors. It's not impossible to support but it won't be very user friendly (even for advanced users) to require overriding so many brushes.

**Comment by 0LBaID** [comment]
Thanks for the feedback. I am not seeing anything but white anywhere (maybe you can share where a font is a different color?). I am using a uxtheme and wanted to share my current explorer font color as an example:

![image](https://user-images.githubusercontent.com/131370849/233427946-9acaa7cf-fe1c-42a1-8e5f-6f35982d68e2.png)

**Comment by yaira2** [comment]
There are many different areas but even on a single control there can be a regular, hover, pressed and disabled state. And each control can have different brushes, so overriding them all would add a lot of complexity to the codebase.

**Comment by 0LBaID** [comment]
Got it, thanks for taking the time to explain and appreciate all your doing. Makes sense if to complicated to work on qol and stability.

**Comment by yaira2** [comment]
Stability is definitely a priority but we'll keep this open as well to see if anyone has additional feedback or ideas on how to implement it.

**Comment by yaira2** [comment]
Thank you for sharing your feedback with us. Although this isn't the outcome you were hoping for, we wanted to update this issue and let you know that we don't have any plans to implement this option.
