### ISSUE TITLE
Delay when opening the app

### ISSUE THREAD

**Issue by josuelrocha** [files-community/Files#12132]
### What feature or improvement do you think would benefit Files?

Hello,

I started using the app recently and it's very good, but I noticed that there is a delay when opening the app, I understand that when I open it, it loads several things, but that bothers me a little. So my suggestion is the following: Instead of always needing to start up and load everything necessary every time you open the app, why not do it once when starting Windows? Because even with the app closed, it could continue running in the background, already with everything loaded that is necessary, so when opening the app, it would just be opening a new instance. This way I believe it would completely eliminate this problem with delay and I also believe it may have other benefits such as memory consumption.

### Requirements

- (no requirements)

### Files Version

Version: 2.4.66.0

### Windows Version

Windows 11 22H2 22621.1555

**Comment by yaira2** [comment]
@joergpichler thank you for your feedback, the main limitation with startup time is from the WinAppSdk framework. The good news is that the startup performance will get better as the framework does. We're also working on our own optimizations #4180.

We're tracking support for minimizing to the system tray in #11279.

**Comment by yaira2** [comment]
@josuelrocha This feature is included in the latest preview build (https://files.community/download) and will be included in the v3 release.

**Comment by josuelrocha** [comment]
> @josuelrocha This feature is included in the latest preview build (https://files.community/download) and will be included in the v3 release.

What good news! I tested it and it's really fast now.

**Comment by yair100** [comment]
@josuelrocha we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
