### ISSUE TITLE
Bug: Batch files are executed as SYSTEM user

### ISSUE THREAD

**Issue by Cromagnon31** [files-community/Files#12139]
### Description

When double clicking on a batch file or an executable, it's executed as SYSTEM user.

USERNAME=SYSTEM
USERPROFILE=C:\Users\OW

When you open a shell on a directory is is executed as the session user.

USERNAME=OW
USERPROFILE=C:\Users\OW

USERPROFILE is good but not USERNAME !

### Steps To Reproduce
0. log in Windows session as standard user (eg not SYSTEM user) and open Files.

1 Edit a batch files with the 2 lines :
SET
PAUSE
Open(double click) the batch file.
Look at USERNAME variable, it's SYSTEM
or 

2 Open(double click) %windir%\system32\cmd.exe and run set command in the newly opened shell.
Look at USERNAME variable, it's SYSTEM

3. Open a shell and run the batch file or set command
Look at USERNAME it it's the logged user name.

### Requirements

When opening a batch file  or an executable it should run in the user environmement eg environment, variable USERNAME should be equal to the logged user name, not SYSTEM.

### Files Version

2.4.62.0

### Windows Version

Window 11 pro 22H2 22261.1555

### Log file

[debug.log](https://github.com/files-community/Files/files/11296129/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report. Can you give the following information.
- Are you running the bat files as admin?

**Comment by yaira2** [comment]
@Cromagnon31 can you confirm if this is the same as #5648?

**Comment by Cromagnon31** [comment]
No, I just click on it.

If I open a shell at the directory place, the user is the session user.

 

Strange isn't it ? 

 

 

De : Josh65-2201 ***@***.*** 
Envoyé : vendredi 21 avril 2023 15:32
À : files-community/Files
Cc : OlivierW; Author
Objet : Re: [files-community/Files] Batch files are executed as SYSTEM user (Issue #12139)

 

Thanks for the report. Can you give the following information.

*	Are you running the bat files as admin?

**Comment by Cromagnon31** [comment]
No. Quite a bit different I guess.

Batch is executed normally (ie not as administrator) from data storage outside Windows directories.  

 

 

De : Yair ***@***.*** 
Envoyé : vendredi 21 avril 2023 15:37
À : files-community/Files
Cc : OlivierW; Mention
Objet : Re: [files-community/Files] Batch files are executed as SYSTEM user (Issue #12139)

 

@Cromagnon31 <https://github.com/Cromagnon31>  can you confirm if this is the same as #5648 <https://github.com/files-community/Files/issues/5648> ?

**Comment by Cromagnon31** [comment]
The issue is tagged as more-info. Do you need more information ?
Do you expect to fix it in a near release ?

**Comment by Cromagnon31** [comment]
In facts it's not necessary for me to have multiple graphical sessions. I'll follow issue #2491.

RemoteFX seems not to be the good horse. It's deprecated since 2021. 
https://support.microsoft.com/en-us/topic/kb4570006-update-to-disable-and-remove-the-remotefx-vgpu-component-in-windows-bbdf1531-7188-2bf4-0de6-641de79f09d2

I already use VNC for console management of my server which is hosted somewhere outside.
On Manjaro TigerVncC seems better then X11Vnc.
VNC lacks of encryption then I use it only on local network directly or via VPN. SSH tunnelling is also a way, but I didn't find at this time a Windows vnc client able to manage automatically the tunnel.
 
**An important info :** I've removed the "pam-close-systemd_system-dbus.so" and now polkit rights elevation works fine without. #1684 issue is not more applicable.
Is there a link with the fact that the D-Bus session is created by systemd --user ?

I've installed Xrpd on fresh install of Manjaro below is the process to make it working : 

Install xorg an xorgxrdp paquet with GUI (-git or -del version seems not uptodate) 
May be command line shoud work (not tested) : 
> sudo pamac install xrdp xorgxrdp

Start xrdp services
> sudo systemctl start xrdp xrdp-sesman

At startup 
> sudo systemctl enable xrdp xrdp-sesman

  
Modify Xorg section in /etc/xrdp/sesman.ini as explained ;
```
[Xorg]
param=/usr/lib/xorg

```
Modify/create /etc/X11/Xwrapper.config
 ```
# Allow anyone to start X:
 allowed_users=anybody
```
  
Modify ~/.xinitrc to make xfce the default manager and not create D-Bus session if already present :
Also modify .xinitrc of others users ans /etc/skel/.xinitrc for future users.
```

!/bin/bash
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

SESSION=${1:-xfce}

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

get_session(){
        local args=
        if [[ -z $DBUS_SESSION_BUS_ADDRESS ]]; then
        # Need dbus-session
                args+=(dbus-launch --sh-syntax --exit-with-session)
        fi
        case "$1" in
                awesome) args+=(awesome) ;;
                bspwm) args+=(bspwm-session) ;;
                budgie) args+=(budgie-desktop) ;;
                cinnamon) args+=(cinnamon-session) ;;
                deepin) args+=(startdde) ;;
                enlightenment) args+=(enlightenment_start) ;;
                fluxbox) args+=(startfluxbox) ;;
                gnome) args+=(gnome-session) ;;
                i3|i3wm) args+=(i3 --shmlog-size 0) ;;
                jwm) args+=(jwm) ;;
                kde) args+=(startplasma-x11) ;;
                lxde) args+=(startlxde) ;;
                lxqt) args+=(lxqt-session) ;;
                mate) args+=(mate-session) ;;
                xfce) args+=(xfce4-session) ;;
                openbox) args+=(openbox-session) ;;
                *) args+=("$1") ;;
        esac

        echo "${args[*]}"
}

```
That is all. Rdp connection should work fine !

**Comment by yaira2** [comment]
> The issue is tagged as more-info. Do you need more information ?

This is more a reminder for me to come back to this, I haven't had the chance to properly read up on the latest comments.

**Comment by yaira2** [comment]
Can you do us a favor and update the requirements to include the expected behavior?

**Comment by Cromagnon31** [comment]
Hi,
I have deleted a message which was for another project issue.
My Files version is actually 2.5.10.0.
Issue is still there.
The expected behavior is that batch files should be executed as the logged user and not as the SYSTEM user.
Notice that if I open a terminal with the context menu, the user is the logged user.

**Comment by Cromagnon31** [comment]
New feedback for this issue. 

Batch is executed with expected user when using contextual menu "Open as administrator" or "Open as other user".
Issue still remain when directly clicking on the batch file name or using contextual menu 'Open".

Another issue appear : if batch is located in "My documents", batch is not executed at all when double clicking on the batch file name or using contextual "Open". batch is not executed and a window pop-up with the message : "File not found, The file you are trying to access may have been moved or deleted".

![2023-12-29 11_21_23-Documents - Files](https://github.com/files-community/Files/assets/6310532/a57c2309-ff83-4e57-a121-3fef82ff0531)

Actual Windows version : Windows 11 professional 23H2 build 22631.2861
Files : 3.0.15.0
Note that the PC is in a Windows domain and the user too.

**Comment by yaira2** [comment]
A fix for this issue has been merged into `main` and will be included in the next update.
