### ISSUE TITLE
Bug: Extract Files grayed out when contents of archive

### ISSUE THREAD

**Issue by deathrjj** [files-community/Files#12138]
### Description

The Extract button works when selecting an archive however when viewing the files contained within an archive, the button appears but is grayed out. Pressing this button when inside the folder should have the same functionality as pressing it with the folder selected.

**While viewing contents of archive (.zip):**
![image](https://user-images.githubusercontent.com/7521286/233637216-6caad6f5-3ac2-4e35-9fac-d9675f1d97b5.png)

**While outside archive (How it should also be when inside):**
![image](https://user-images.githubusercontent.com/7521286/233636866-b0f06bc5-3652-4af0-9030-04113c88d9c0.png)

### Steps To Reproduce

Open a archive (I have tested with zip and 7z archvies and this occurs and look at the toolbar

### Requirements

Fix "Extract Files" being grayed out while viewing contents of archive

### Files Version

Version: 2.4.66.0 OS Version:10.0.19045.2846

### Windows Version

Windows 10 Enterprise 22H2 Build: 19045.2846

### Log file

[debug.log](https://github.com/files-community/Files/files/11295781/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I was able to reproduce this.

**Comment by yaira2** [comment]
@deathrjj thank you for reporting this issue, a fix will be included in the next release.
