### ISSUE TITLE
Feature: Ability to create tags from the Tags section and from the context menu

### ISSUE THREAD

**Issue by Marin-Kitagawa** [files-community/Files#12146]
### What feature or improvement do you think would benefit Files?

I want to have an option to create Tags from the Tags section (image below) and from the content menu. The context menu just provides the ability to assign tags. To create a tag, I have to go to settings, go to Tabs menu and then create a new tag. Why? Please make it simpler

![image](https://user-images.githubusercontent.com/49131888/233683553-d51b1f02-7847-4fe3-a569-2a628286cf53.png)

### Requirements

- Add option to tags context menu to "Edit tags"
- Clicking this option should open the tags page in settings

### Files Version

2.4.66.0

### Windows Version

Windows 11 Pro 10.0.22621.1555

**Comment by yaira2** [comment]
Thank you for your feedback

**Comment by Marin-Kitagawa** [comment]
Wow. That was really fast

**Comment by yaira2** [comment]
@Marin-Kitagawa we still have to finalize the requirements on how this will be implemented but it's definitely on our radar.

**Comment by Marin-Kitagawa** [comment]
@yair100 Sure. Looking forward to it ☺️

**Comment by hecksmosis** [comment]
We should probably add this to the context menu in the sidebar

**Comment by Marin-Kitagawa** [comment]
@hecksmosis Adding it in context menu and in the Tags section (above image) would be great instead of just in the context menu

**Comment by hecksmosis** [comment]
> @hecksmosis Adding it in context menu and in the Tags section (above image) would be great instead of just in the context menu

Yes, I think doing both is a good idea, I was just saying that for the sidebar one we should add it in the context menu for the sidebar items. We could do a popup and reuse it in both cases, couldn't we @yair100 ?

**Comment by yaira2** [comment]
@hecksmosis I was hoping that we could open directly to the settings page to reduce duplicating the UI but we'll have to rework settings dialog before this is possible.

**Comment by yaira2** [comment]
The direction we're probably going to take is to
1. Add an option to "Create tag", this will open a popup modal and allow the user to create a new tag.
2. Add an option to delete tags when right clicking them in the sidebar.
3. Add option when right clicking the tag section in the sidebar to "Manage tags", this should open the tags page in settings.

**Comment by 0x5bfa** [comment]
I guess we can add a context menu to the section header item as we also have an option to open a dialog to map a network location in widget drive section(meaning we can do this for this option as well). Currently we, however, don't have a way to know the section item is the section because it is LocationItem which is the same as we use for folders in Pinned section. If we create a class named SidebarSectionItem or SidebarSpecialItem.

**Comment by ferrariofilippo** [comment]
Hi, I started working on this. Is this concept what you were thinking about:
![Image](https://github.com/user-attachments/assets/3de9b20f-98e2-4103-a66a-adeafadb8c07)
![Image](https://github.com/user-attachments/assets/835adc78-0374-409d-a51f-3773a29169cd)
![Image](https://github.com/user-attachments/assets/68d2c34c-a49e-463a-8861-4976b2c0eade)
![Image](https://github.com/user-attachments/assets/47b053a1-e2d1-4a3d-9df1-4148fdca1b30)

Having been away for a long time, I am not up to date with the project - is there any “deep-link” to access the settings yet?

**Comment by yaira2** [comment]
The plan is to add an 'Edit tags' menu option which will deep link into settings.

> Having been away for a long time, I am not up to date with the project - is there any “deep-link” to access the settings yet?

Not yet, I think this is really a prerequisite for the issue.

**Comment by ferrariofilippo** [comment]
Something like this?

https://github.com/user-attachments/assets/373959b7-c542-424d-90aa-6aafae14a6ef

Anyway, what are `deep-links` needed for? If they are used only to access the `Settings Dialog` I think we can simply use a parameter for `OpenSettingsCommand`

**Comment by yaira2** [comment]
> Something like this?

Yes!

> Anyway, what are deep-links needed for? If they are used only to access the Settings Dialog I think we can simply use a parameter for OpenSettingsCommand

That's what I had in mind 👍
