### ISSUE TITLE
An option to disable animation

### ISSUE THREAD

**Issue by VictoriousRaptor** [files-community/Files#12147]
### What feature or improvement do you think would benefit Files?

I notice that the only way to disable animation in Files seems to be disable animation in Windows settings (mentioned in #10509). This seems like unreasonable. Only Files is a bit slow on my two laptops, other animation of Windows is very smooth so disabling animation system-wise looks unnecessary.

### Requirements

- An option in settings to disable animation effects.

### Files Version

2.4.62.0 (store)

### Windows Version

Windows 10 22H2 19045.2486

**Comment by Josh65-2201** [comment]
Thanks for the feedback.
What is your reason for disabling animations? Files doesn't have many and doesn't affect performance.

**Comment by Josh65-2201** [comment]
Can you try updating to 2.4.66.0 and see if it's an issue still.

**Comment by yaira2** [comment]
@VictoriousRaptor v2.4.66 fixed the issue with framerates. If it's still an issue, please let us know and we'll investigate.

**Comment by VictoriousRaptor** [comment]
@yair100 Still experience frame drops and lags on 2.4.66 (store version). I record a video to demonstrate the problem. The this video is 30fps so actually it's smoother but it still lags and some frame drops when click on settings tabs. 

https://user-images.githubusercontent.com/10308169/233755324-d40bce23-2fd0-48cd-8ca0-0b8f8fb26835.mp4

**Comment by yaira2** [comment]
@VictoriousRaptor is this specific to the settings dialog?

**Comment by VictoriousRaptor** [comment]
v2.4.70 is much better. Basically it's fixed.

**Comment by yaira2** [comment]
Thanks for letting us know

**Comment by mwisnicki** [comment]
Another reason to disable animations is because someone might find them annoying or too slow (in terms of perception rather than fps)

**Comment by mwisnicki** [comment]
> @yaira2 Still experience frame drops and lags on 2.4.66 (store version). I record a video to demonstrate the problem. The this video is 30fps so actually it's smoother but it still lags and some frame drops when click on settings tabs.
> 
>  2023-04-22_09-39-58.mp4

I still see this choppiness in 3.1.1.0
I think powertoys is also C#/winui but it animates very smoothly

**Comment by yaira2** [comment]
@mwisnicki please report an issue on the WinUI repo.

**Comment by mwisnicki** [comment]
> @mwisnicki please report an issue on the WinUI repo.

About performance or disabling unwanted animations?

**Comment by yaira2** [comment]
About the framerate
