### ISSUE TITLE
CPU Utilization

### ISSUE THREAD

**Issue by rinteln1972** [files-community/Files#12145]
### Description

The new update to version 2.4.66.0 is making my CPU run at 10-12% and forcing my fan to constantly be on.  This is happening on both my work and home laptops.  Both are windows 10 machines (lenovo laptops)  

Is this something that has been mentioned by others?

Please see attached image of my task manager

### Steps To Reproduce

![Files CPU Usage](https://user-images.githubusercontent.com/131473034/233678797-20e3c265-99c4-4efc-9945-cdc0e3d9ec85.png)

### Requirements

Reboot does not resolve.
Reinstall does not resolve.

### Files Version

Version 2.4.66.0

### Windows Version

Windows 10 OS Build: 19045.2788

### Log file

[debug.log](https://github.com/files-community/Files/files/11297293/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report. I am unable to reproduce this, Can you give the following information.
- Do you have Files settings > Folders > Calculate folder sizes enabled.
- What is your CPU model. Weaker ones will always have high usage. Performance improvements are tracked in #4180 
- Do you have network drives mounted?

**Comment by yaira2** [comment]
This can happen when loading large directories or if the option to calculate folder sizes is turned on (it's off by default for this reason). In both cases, the utilization is expected to go down once the items finish loading.

Can you please share steps to reproduce this issue?

**Comment by rinteln1972** [comment]
Hi Yair

Thanks for the really quick response.

I have Calculate folder sizes turned off
I have Include Unindexed Items turned off
I do have 6 shared drives at work, and a large OneDrive and Google Drive at home.
Both Laptops have i7 Chips with 16gb RAM

To reproduce the issue I boot up my laptop and open My Files, it's just always running high and does not fluctuate throughout the day.  The only major resource I use is Chrome as most of our systems are web based.

If I close My Files the CPU usage drops to 4%

With My Files it's not running at 100% all the time so I'm not freaking out.  It just seems to use to put unnecessary stress on my CPU.  I have only recently started having this issue, since mid to late Feb 2023.  I ran the new update today but did not resolve the issue.

Please see attached images.

Thank you,
Stephen

[cid:88887343-e1ba-4a18-a9a5-086804854490]

[cid:d79f1a35-96f2-42f0-a73c-f928deec2a10]

[cid:443c62e7-3503-44d8-8c88-39dd258b3aaa]

[cid:f73e0897-4304-4bdd-8d16-333c869847f8]


________________________________

**Comment by yaira2** [comment]
@rinteln1972 thank you for the response, can you add this feedback to #4180 so that we can track it in a single issue?

**Comment by yaira2** [comment]
@rinteln1972 we identified an issue where the CPU usage was unexpectedly high on the home page. A fix has been implemented and will be included in the next update.

**Comment by rinteln1972** [comment]
That's great news! Thank you for looking into this and finding a solution.

Stephen

**Comment by yaira2** [comment]
At first, we thought it was the same as #4180 but when we took a closer look, we realized this was a new issue. We're still looking for ways to resolve #4180 but at least we have an immediate fix for the home page.
