### ISSUE TITLE
Bug: Files crashes when right clicking a file/folder in a removable storage drive

### ISSUE THREAD

**Issue by RichardMar** [files-community/Files#12153]
### Description

When opening removable storge Files crashes

### Steps To Reproduce

1. Open an removable storge drive
2. Right click on a file or folder
3. Files crashes

### Requirements

- Fix crash that occurs when right click on removable devices

### Files Version

2.4.66.0

### Windows Version

10.0.22621.1555

### Log file

```
2022-12-15 18:00:17.8050|ERROR|AppUnhandledException|服务器出现意外情况。 (0x80010105 (RPC_E_SERVERFAULT))
System.Runtime.InteropServices.COMException (0x80010105): 服务器出现意外情况。 (0x80010105 (RPC_E_SERVERFAULT))
```

**Comment by Josh65-2201** [comment]
Can you please upload (Do not copy and paste content) the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.

**Comment by yaira2** [comment]
@RichardMar is this for any file type or just images/videos (or folders containing them)?

**Comment by yaira2** [comment]
@RichardMar can you confirm if this is the same as #12162?

**Comment by RichardMar** [comment]
on media file such as images videos audios ,right click them will occur crush

**Comment by RichardMar** [comment]
[debug.log](https://github.com/files-community/Files/files/11330491/debug.log)

**Comment by yaira2** [comment]
@RichardMar we're going to continue tracking this in #12162.
