### ISSUE TITLE
Enable or Disable Tabs 

### ISSUE THREAD

**Issue by quma** [files-community/Files#12164]
### What feature or improvement do you think would benefit Files?

needs a feature in the settings menu to enable or disable the tabs.

### Requirements

- Menu/Appearance/ 
-Desable Tabs

### Files Version

2.4.67

### Windows Version

Windows 11 22H2

**Comment by yaira2** [comment]
@quma thank you for your feedback, can you please share more about your use case for disabling tabs?

**Comment by quma** [comment]
Hallo Yaira
I don't really use Tabs.
In the most cases I use a singel window to navigate or open files etc. and in some cases the split window function to copying files from one folder to a another.

I personally prefer a more compact Toolbar. Specially in the hight with more space for the explorer content.
What also means the "Disable Tabs Function" makes more sens if it's results in a little bit thiner Toolbar.

On some Notebooks it makes it easyer to work with.

**Comment by yaira2** [comment]
Hiding the tabs wouldn't free up space as there still needs to be a title bar. Moving the address bar into the title bar isn't an option as there wouldn't be enough space for it.

**Comment by quma** [comment]
There is a little space that can be removed.
Like in the screenshot
![IMG_20230423_190652](https://user-images.githubusercontent.com/856745/233854237-2d5c20df-3b74-4f3f-b7a6-3b9813b0115c.png)

**Comment by yaira2** [comment]
@quma we're talking about around 16 pixels, it's not going to gain you any significant amount of space. That being said, we're looking into other ways to maximize the space within the layouts.

**Comment by yaira2** [comment]
There is also the complexity of adjusting the UI when tabs are hidden.

**Comment by yaira2** [comment]
@quma thank you for your feedback, we currently don't have any plans to add this option.
