### ISSUE TITLE
Bug: Crash occuring when cutting and pasting between tabs

### ISSUE THREAD

**Issue by pakmanj** [files-community/Files#12161]
### Description

Second time. It seems to happen when I am cutting and pasting files. between two tabs.

### Steps To Reproduce

select files in one tab
ctrl x
select other tab
ctrl c
crash report

### Requirements

- eg. Fix crash that occurs when...cutting and pasting files.
- eg. Correct action happens when clicking...

### Files Version

2.4.67 

### Windows Version

Edition	Windows 10 Pro Version	22H2 Installed on	‎11/‎7/‎2022 OS build	19045.2846 Experience	Windows Feature Experience Pack 120.2212.4190.0

### Log file

[debug.log](https://github.com/files-community/Files/files/11302099/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report. I am unable to reproduce this, Can you give the following information.
- Where are you pasting to and from?

**Comment by yaira2** [comment]
@pakmanj
