### ISSUE TITLE
Trainz Railroad 2004 is Crashing the Game! Looks Like I Need to Install DirectX9

### ISSUE THREAD

**Issue by SethPederito2023** [files-community/Files#12163]
### Description

![Screenshot 2023-04-22 132511](https://user-images.githubusercontent.com/127005043/233802888-cb355de7-02de-454c-bc05-39ec55d657a9.png)

### Steps To Reproduce

Step 1 : Download Direct X9
Step 2 : Install Direct X9
Done!

### Requirements

Direct X9

### Files Version

19045.2846

### Windows Version

Windows 10 22H2

### Log file

![Screenshot 2023-04-22 132511](https://user-images.githubusercontent.com/127005043/233803152-0fd05355-e567-4b8e-b4ff-066585584a28.png)

**Comment by Josh65-2201** [comment]
This isn't related to Files.
