### ISSUE TITLE
Bug: Freezes when opening a file until file gets closed again

### ISSUE THREAD

**Issue by paulober** [files-community/Files#12167]
### Description

I opened a python file with "Open With" > "Vs code" and then the files app hangs until i close vs code again.

### Steps To Reproduce

1. Open a file with "Open with"
2. Try to interact with the app

### Requirements

- The app should not hang until a file has been closed which was opened with the app

### Files Version

2.4.67

### Windows Version

Windows 11 22H2

### Log file

[debug.log](https://github.com/files-community/Files/files/11303431/debug.log)'
It also made my hole explorer crash (after opening the logs location thought the link in the files app > about and the right click) which now cannot be reopened! Here are the Windows event logging protocols
[filesapp-crashes-explorer.evtx.zip](https://github.com/files-community/Files/files/11303439/filesapp-crashes-explorer.evtx.zip)

**Comment by Josh65-2201** [comment]
Thanks for the report. I am unable to reproduce this but there are errors shown in the log.

**Comment by yaira2** [comment]
@paulober is this only when using "open with"?

**Comment by paulober** [comment]
@yair100 @Josh65-2201 It seems like it was a (for now) one time issue which I cannot reproduce.

**Comment by yaira2** [comment]
@paulober thank you for the update, please let us know if it happens again.

**Comment by Lukiluc29** [comment]
Hello, I tested and on my side by doing the manipulation with "open with" on a photo the application crashed

**Comment by yaira2** [comment]
@Lukiluc29 the issue with photos is being tracked in #12162

**Comment by Lukiluc29** [comment]
Ah yes I just saw that. I think it must have been the same problem suddenly because I tried again on many other files other than photos and nothing happened.
