### ISSUE TITLE
Right Click haven't open in terminal？

### ISSUE THREAD

**Issue by berial** [files-community/Files#12198]
### Files:
![Files](https://i.imgur.com/z1r2kmj.png)

### Explorer:
![Explorer](https://i.imgur.com/9agmdED.png)

### Steps To Reproduce

1.Right click on the folder using Files
2.Right click on the folder using Explorer

### Requirements

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

2.4.68.0

### Windows Version

Windows 11 Pro 22H2 10.0.22621.1555

### Log file

none

**Comment by yaira2** [comment]
@berial thank you for the feedback, Windows Terminal seems to have switched to the new Windows 11 shell commands which we don't have support for yet #8251. In the meantime, we have a keyboard shortcut ctrl + ` for opening the selected folder in Windows Terminal.

**Comment by berial** [comment]
Thanks.

**Comment by yaira2** [comment]
And for a pro tip, Ctrl + Shift + ` will open Windows Terminal as admin.
