### ISSUE TITLE
Bug: When closing the secondary pane with a shortcut, the primary pane stops working as expected.

### ISSUE THREAD

**Issue by rafaskb** [files-community/Files#12202]
### Description

When we have two panes open in Files and we close the secondary one with the keyboard shortcut `Ctrl + Shift + W`, the primary pane doesn't regain focus automatically, so opening a folder from the favorites menu no longer works.
A workaround is to click the primary pane again, so it becomes active and focused, and then opening something from the favorites sidebar.

https://user-images.githubusercontent.com/2331058/234363691-0fb0bf95-5a35-467b-9ec8-97096e7374c8.mp4

### Steps To Reproduce

1. Open Files with both panes active.
2. Click on the second pane, so it's active and has focus.
3. Press the keyboard shortcut `Ctrl + Shift + W` to close the secondary pane.
4. Try to open a folder from the favorites menu.
5. That won't work because the primary pane is not focused, therefore nothing happens.

### Requirements

- Fix bug described above

### Files Version

2.4.68.0

### Windows Version

10.0.19044.2846

### Log file

```

```

**Comment by yaira2** [comment]
@rafaskb can you attach the debug file to the description?

**Comment by rafaskb** [comment]
> @rafaskb this time we don't actually need the log file but in the future, can you upload the actual file instead of copying the text?

I did include the whole content of the debug log in the original issue, seems like it's no longer there though. Is there any difference between including the content of the file and the file itself?

**Comment by Josh65-2201** [comment]
We ask users to upload the file and not copy and paste the contents into the box so it doesn't make a long wall of text on GitHub and allows for searching/reading the contents of the log easier.

**Comment by yaira2** [comment]
@rafaskb a fix has been implemented and will be part of the next feature release (v2.5).
