### ISSUE TITLE
Impossible to open Files: Store code

### ISSUE THREAD

**Issue by lyonelf** [files-community/Files#12201]
### Description

I have this window sinc last update:

Files n’est actuellement pas disponible dans votre compte. Assurez-vous que vous êtes connecté au Microsoft Store et réessayez. Voici le code d’erreur, au cas où vous en auriez besoin : 0x803F8001

### Steps To Reproduce

try to open it

### Requirements

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

2.0.67

### Windows Version

11

### Log file

[debug.log](https://github.com/files-community/Files/files/11320489/debug.log)

**Comment by Josh65-2201** [comment]
This is an issue with the Microsoft store. You can try using the classic installer from https://files.community/download

**Comment by yaira2** [comment]
@lyonelf can you verify that you're signed into the Microsoft Store?

**Comment by lyonelf** [comment]
I can't sign in because i have no personnal account, only a pro school one.

**Comment by yaira2** [comment]
@lyonelf you're best option would be to use the classic installer that @Josh65-2201 linked. Can you see if that works?

**Comment by lyonelf** [comment]
Yes it’s ok like that.

I’ll try to remember this, for next time if hapen again

 

De : Yair ***@***.***> 
Envoyé : mardi 25 avril 2023 16:47
À : files-community/Files ***@***.***>
Cc : Lionel-BZH ***@***.***>; Mention ***@***.***>
Objet : Re: [files-community/Files] Impossible to open Files: Store code (Issue #12201)

 

@lyonelf <https://github.com/lyonelf>  you're best option would be to use the classic installer that @Josh65-2201 <https://github.com/Josh65-2201>  linked. Can you see if that works?
