### ISSUE TITLE
Bug : issue with deleting and renaming protected folders in Windows

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12211]
### Description

When I try to delete a protected folder by providing administrative credentials, nothing happens except for an error message in "Task in progress". Similarly, when I try to rename a protected folder by providing administrative credentials, nothing happens there's not even an error message and the file name remains the same even after the attempted renaming.

### Steps To Reproduce

1. Open "Files".
2. Navigate to the folder containing the file you want to delete.
3. Right-click on the file and select "Delete" or drag it to Recycle Bin icon.

### Requirements

1. Fix the bug to display a window requesting user permission when attempting to delete or rename a protected file.
2. If the administrator denies permission, do not display an error.
3. If the administrator grants permission but the file cannot be deleted, display a notification stating that the file cannot be deleted.
4. Allow deletion or renaming of protected files once user permission is granted.

### Files Version

Version : 2.4.69.0

### Windows Version

Windows 11 22H2 22621.1555

### Log file

[debug.log](https://github.com/files-community/Files/files/11330826/debug.log)

**Comment by Josh65-2201** [comment]
Merging with #10422

Thanks for the report. It is a known issue.

**Comment by yaira2** [comment]
This issue is resolved in our dev branch and will be included in the next release.
