### ISSUE TITLE
New tab (CTRL + T) should consider path of its previous tab

### ISSUE THREAD

**Issue by pavangayakwad** [files-community/Files#12215]
### What feature or improvement do you think would benefit Files?

Whenever new tab (CTRL + T) is opened it should consider path of currently focused tab. 

### Requirements

Whenever new tab (CTRL + T) is opened it should consider path of currently focused tab. 

### Files Version

2.4.69.0

### Windows Version

10.0.22621.1635

**Comment by Josh65-2201** [comment]
Thanks for the feedback. 
CTRL + T function is to open a new tab at the home page. Ctrl + Shift + K will duplicate the tab. Remapping shortcuts is being worked on.

**Comment by pavangayakwad** [comment]
Well this is great and thanks for swift reply. I will close this issue as this feature already implemented. However I wasn't clear which shortcut key to use.

**Comment by Josh65-2201** [comment]
There's documentation here https://files.community/docs/configuring/keyboard-shortcuts for shortcuts to use and other things. They will also be in app when the remapping system is made.
