### ISSUE TITLE
Bug: Issue with Network File not responding when opened in Network Drive

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12216]
### Description

When attempting to open the "Network" file in the network drive, nothing happens and the application indicates that it is not responding, before closing without any error reporting. Furthermore, the application does not reopen once it is closed.

### Steps To Reproduce

1. Open "Files"
2. Find the "Network Drives" category
3. Expand it
4. Click on the "Network" file

### Requirements

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

Version : 2.4.69.0

### Windows Version

Windows 11 22H2 22621.1555

### Log file

[debug.log](https://github.com/files-community/Files/files/11336870/debug.log)

**Comment by yaira2** [comment]
Thank you for reporting this issue.

**Comment by Lukiluc29** [comment]
It was my pleasure, and I believe you can see that I am actively trying to identify any significant bugs or errors that may exist, as I recognize the vast potential of your application.

**Comment by Lukiluc29** [comment]
I noticed that by reproducing this bug there was no longer any problem that occurs on version 2.4.80

**Comment by Lukiluc29** [comment]
I have this problem again in version 1.4.81

**Comment by Lukiluc29** [comment]
Finally by uninstalling and reinstalling Files all works again as before

**Comment by yaira2** [comment]
@Lukiluc29 thanks for the update, please let us know if the issue occurs again.
