### ISSUE TITLE
Files app Crashed

### ISSUE THREAD

**Issue by py-cal** [files-community/Files#12224]
### Description

When I try to select a few screenshots, the Files app crashes out of nowhere.

### Steps To Reproduce

1. Go to the Screenshots Folder
2. Select multiple pictures
3. Click right-click on one of them to modify them
4. Wait a few seconds
5. Files app crashes

### Requirements

Fix the crash that occurs when I want to  modify multiple Pictures.

### Files Version

2.4.69.0

### Windows Version

10.0.22621.1555

### Log file

[debug.log](https://github.com/files-community/Files/files/11346863/debug.log)

**Comment by yaira2** [comment]
@py-cal thank you for reporting this issue, we're currently tracking this in #12162. Please subscribe to that issue to be notified of updates.
