### ISSUE TITLE
Bug: Files crashes when opening properties from search page

### ISSUE THREAD

**Issue by ferrariofilippo** [files-community/Files#12220]
### Description

If you open a new tab on `Home` and you start searching anything (like tagged files), the properties button will be enabled on the landing page. Clicking on it will crash the app

### Steps To Reproduce

1. Open a new tab on `Home` (this won't happen if you navigate anywhere. The tab must open on `Home`)
2. Click on a tag on the sidebar (or search for anything)
3. See that the `Properties` button on the toolbar is enabled
4. Click on it
5. See that Files crashes

### Requirements

- The properties button should be disabled when in a search results

### Files Version

2.4.69.0

### Windows Version

Windows 11 Pro 22H2 10.0.22621.1555

### Log file

[debug.log](https://github.com/files-community/Files/files/11341856/debug.log)

**Comment by yaira2** [comment]
@ferrariofilippo thank you for reporting this, we need to update the rich command to be disabled on the search page.

**Comment by yaira2** [comment]
It might also be a good idea to add some error handling in the properties widow as well.

**Comment by ferrariofilippo** [comment]
> @ferrariofilippo thank you for reporting this, we need to update the rich command to be disabled on the search page.

We don't have one at the moment
