### ISSUE TITLE
Bug: App crashes when I try to access a folder through ftp

### ISSUE THREAD

**Issue by enricodarodda** [files-community/Files#12222]
### Description

I have mapped a network folder through ftp on windows file explorer, and when i access through it there are no issues, but when I try to access it through the Files app, then the app crashes, and it doesn't even handle the login prompt.

### Steps To Reproduce

1. Map an ftp network folder on windows file explorer
2. try to access it through files app
3. see what happens

### Requirements

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

Version: 2.4.69.0

### Windows Version

Windows 10 Pro 22H2 19045.2913 Windows Feature Experience Pack 1000.19041.1000.0

### Log file

[debug.log](https://github.com/files-community/Files/files/11343142/debug.log)

**Comment by yaira2** [comment]
Thank you for reporting this issue, I can see the error in the log file.

**Comment by enricodarodda** [comment]
Thank you for replying so soon, hope the fix is easy.
Wish the best, have a good day

**Comment by ferrariofilippo** [comment]
The exception is caused by the URL, does it contain any special character or anything "strange"?

**Comment by enricodarodda** [comment]
No, it is a standard ftp url, so it is specified as "ftp://...." but there are no strange characters in it, simple plain text, so special characters coming from different alphabets  or different symbols

**Comment by ferrariofilippo** [comment]
I can't reproduce this, can you @enricodarodda?
