### ISSUE TITLE
Error after close

### ISSUE THREAD

**Issue by dougg0k** [files-community/Files#12226]
### Description

I get this error after closing Files.
![files_after_close](https://user-images.githubusercontent.com/10801221/235016556-165b0d52-d4e5-48be-aaad-bc7908283219.png)

I have only seen this error with Files.

### Steps To Reproduce

I didnt find anything in common, other than closing Files, and it doesnt always happen. Maybe after using more, it does.

### Requirements

How would I know what it takes to fix?

### Files Version

2.4.69

### Windows Version

Windows 10 22H2

### Log file

Folder is empty.

**Comment by yaira2** [comment]
> folder is empty

There should be other files there besides for the log file, can you try to uninstall/reinstall the app?

**Comment by dougg0k** [comment]
Nope, it's empty. I installed yesterday using chocolatey since winget is not working. No point in reinstalling.

**Comment by Josh65-2201** [comment]
Chocolatey isn't supported by Files. Can you try reinstalling using the classic installer from https://files.community/download

**Comment by yaira2** [comment]
> No point in reinstalling

The app isn't installed correctly, and it seems that you're not using an official version of Files. Please let us know if this is still an issue in v2.4.70.

**Comment by dougg0k** [comment]
It was the same lastest version, supported or not.

**Comment by yaira2** [comment]
@dougg0k the Choco version is very possibly modified or missing important components so we can't help. If this is still an issue in the official version, we can do our best to try to reproduce/fix the issue.
