### ISSUE TITLE
CustomOpenDialog doesn't build

### ISSUE THREAD

**Issue by memory-hunter** [files-community/Files#12237]
I am trying to make my first open-source contribution and I checked out issues and saw that I could take up some tasks.
I forked the repository and cloned it to download the source code.
I have read README.md and made sure that **I have the prerequisites.**
I am having trouble because every other 9 project builds but `CustomOpenDialog` doesn't.

Errors I'm getting:
```
Error	C2039	'cout': is not a member of 'std'	CustomOpenDialog
Error	C2873	'endl': symbol cannot be used in a using-declaration	CustomOpenDialog	
```
and so on... (very similar errors).

The thing is, in the editor, everything is fine. No red squiggly lines under the lines which the errors show.

**Comment by QuaintMako** [comment]
Thanks for bringing it to our attention @memory-hunter. 

It is a known issue for some developers, it comes to C++. While I wouldn't be able to explain the exact whereabouts as I don't know much it myself, this answer is mostly to bring to your attention that you can unload this project safely and build Files without it. 

The application will function as expected, so you can already start looking into any issue that interested you. We're looking forward to see your first contribution!

**Comment by memory-hunter** [comment]
> Thanks for bringing it to our attention @memory-hunter.
> 
> It is a known issue for some developers, it comes to C++. While I wouldn't be able to explain the exact whereabouts as I don't know much it myself, this answer is mostly to bring to your attention that you can unload this project safely and build Files without it.
> 
> The application will function as expected, so you can already start looking into any issue that interested you. We're looking forward to see your first contribution!

Thanks for the reply @QuaintMako. Will do so then and try to make it work. I did run the program both earlier and now as well after having it unloaded (thinking the following would be caused by this), I am getting certain `.pdb` files not being loaded in, and when trying to **Right Click** on any directory/file to open up the context menu (like where the Properties are), I am getting an exception which I can't go through, I think it's a good idea to start a separate issue for it or do I append it to this?

**Comment by yaira2** [comment]
@memory-hunter did unloading the project help?

**Comment by memory-hunter** [comment]
> @memory-hunter did unloading the project help?

Unfortunately, it didn't. I tested and could build the project/run the debug without unloading and with unloading but the problem which I later commented, still occurred in both cases.

**Comment by yaira2** [comment]
I'm assuming you set the startup project to `Files.Package`. If you're still having this issue, I recommend cleaning and rebuilding the solution.

**Comment by memory-hunter** [comment]
> I'm assuming you set the startup project to `Files.Package`. If you're still having this issue, I recommend cleaning and rebuilding the solution.

CustomOpenDialog is unloaded.
Files.Package is set up as the default startup project.
I cleaned and rebuilt the project (9 suceeded and 0 failed as expected)
Got a `winrt:hresult_error` by InstallService.dll

On right click, I got `winrt:hresult_error` by Microsoft.UI.Xaml.Controls.dll

**Comment by yaira2** [comment]
Is the project building now? What are you right clicking?

**Comment by memory-hunter** [comment]
> Is the project building now? What are you right clicking?


Yes, the project builds. After the program runs and I get the first window, if I right click on any of the drives, for example, to see Properties, it throws the exception then.

**Comment by yaira2** [comment]
Does clicking `continue` work?

**Comment by hishitetsu** [comment]
`CustomOpenDialog` does not appear to be used in the first place. If it is no longer used, the project should be removed.

**Comment by yaira2** [comment]
@hishitetsu it hasn't been finished yet but there is a hidden setting for it...

**Comment by hishitetsu** [comment]
Oh, I didn't know that. It doesn't appear to be included in the built package.

**Comment by memory-hunter** [comment]
> Does clicking `continue` work?

Yes but the functionality isn't there. It just stays in the same state and doesn't show me the menu.

**Comment by yaira2** [comment]
> Yes but the functionality isn't there. It just stays in the same state and doesn't show me the menu.

This is probably because the menu lost focus, I think you can work around it by unchecking the option for "break when this exception occurs".

**Comment by memory-hunter** [comment]
> > Yes but the functionality isn't there. It just stays in the same state and doesn't show me the menu.
> 
> This is probably because the menu lost focus, I think you can work around it by unchecking the option for "break when this exception occurs".

Oh yeah, that helps. Okay, that's it all figured out then. I'll leave the issue as is, and if needed, you decide to close it or not.
