### ISSUE TITLE
Resolving French Translation Issues on Crowdin

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12232]
I have noticed certain issues with the French translations on Crowdin. For example, some sentences contain unnecessary capitalization or missing words/letters, which can make the text difficult to understand. To improve the translations, I have been editing as many words and phrases as possible to make them more clear and consistent.

**Comment by yaira2** [comment]
@Lukiluc29 thank you, we appreciate your help on improving the translations.
