### ISSUE TITLE
Feature: Support for accessing WSA files

### ISSUE THREAD

**Issue by SteveWorkshop** [files-community/Files#12246]
### What feature or improvement do you think would benefit Files?

when wsa is installed, files should give a way to browse wsa files.
For this function, I have two thoughts.
1) Files can mount userdata.vhdx and integrate EXT4 driver to read it. -no need to launch wsa
2) Integrate adb into files to browse wsa storage. In this situation, WSA must be launched. So files should detect whether wsa is running, if not, it should automatically launch wsa.

### Requirements

- This proposal will accomplish managing files in wsa

### Files Version

2.4.70.0

### Windows Version

windows11 22624.1680

**Comment by yaira2** [comment]
This is a fascination idea, does File Explorer offer this yet?

**Comment by SteveWorkshop** [comment]
No, but some microsoft store apps can do it, like ADB Explorer and apk installer

**Comment by SteveWorkshop** [comment]
apk installer: https://www.microsoft.com/store/productId/9P2JFQ43FPPG
adb explorer: https://www.microsoft.com/store/productId/9PPGN2WM50QB

the former is open-source.

**Comment by SteveWorkshop** [comment]
![Image](https://user-images.githubusercontent.com/92452488/235394251-819591cd-c41b-49d5-96ef-51ca8831bfb6.png)

Seems that Microsoft also has this idea

**Comment by yaira2** [comment]
Are you referring to local network access?

**Comment by SteveWorkshop** [comment]
seems that they want to do file transfer, a little relevant to my wish

**Comment by yaira2** [comment]
That sounds like copy/paste

**Comment by yaira2** [comment]
I'm closing this issue since Microsoft is no longer supporting WSA.
