### ISSUE TITLE
Bug: Cut items stay translucent after copying other items

### ISSUE THREAD

**Issue by richardhttps** [files-community/Files#12249]
### Description

Cut items stay translucent after copying other items, whereas they are expected to lose the translucency.
Below are two screen recordings, one is of Files that demonstrates the issue, and the other is of Windows' File Explorer that demonstrates the expected behavior.

https://user-images.githubusercontent.com/33163707/235434266-0553db91-f788-4fe8-b011-f32b1dd53b5a.mp4

https://user-images.githubusercontent.com/33163707/235434273-d7c14a11-8ca2-4ac4-8e8c-c2962e0bf7da.mp4

### Steps To Reproduce

Demonstrated in the recordings

### Requirements

-

### Files Version

2.4.70.0

### Windows Version

10.0.22621.1635

### Log file

[debug.log](https://github.com/files-community/Files/files/11364598/debug.log)

**Comment by ferrariofilippo** [comment]
I can reproduce this issue

**Comment by yaira2** [comment]
This issue will be resolved in one of the next updates.
