### ISSUE TITLE
Feature: Add support to group by month

### ISSUE THREAD

**Issue by yunancun** [files-community/Files#12244]
### What feature or improvement do you think would benefit Files?

Hello, I have been looking for a file explorer that can sort folders into groups by a specific date, and through my research, I went across your app and obtained it through the windows store. 

I see that it can group the folder by years compared to Native Explorer's "A long time ago". 
Which is slightly better than the native ones, but I'd need more than this. 

I'd like it to sort all files/folders by month. even for older files/folders that were created a year ago. 

### Requirements

To have the file sorted by specific month.

i.e.: Assuming May. 
last week
earlier month 
last month
April 2023
March 2023 
February 2023
....

Dec 2022
Nov 2022

Etc

### Files Version

v2.4.70

### Windows Version

22621.1635

**Comment by Josh65-2201** [comment]
Thanks for the feedback.

**Comment by yaira2** [comment]
Something like `Group by month`?

**Comment by yunancun** [comment]
> Something like `Group by month`?

Yes, I would like to track file modification/creation by specific month.

**Comment by hishitetsu** [comment]
I'll work on this.

**Comment by yunancun** [comment]
> I'll work on this.

Much appreciated

**Comment by yaira2** [comment]
This will be added in v2.5.
