### ISSUE TITLE
"Copy Location" is gone.

### ISSUE THREAD

**Issue by testama** [files-community/Files#12247]
### What feature or improvement do you think would benefit Files?

I cannot find "Copy Location" in the menu.
In single selection and right click, there is 'Copy location", but in multiple selection and right click, there is no "Copy Location".
I need "Copy Location" in multiple selection menu.
thanks.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.4.70.0

### Windows Version

10.0.22621.1555

### Comments

![image](https://user-images.githubusercontent.com/39455117/235425789-4f624c07-e1ac-43b9-a05a-d47dea82dc82.png)
![image](https://user-images.githubusercontent.com/39455117/235425834-16cb270d-a12d-40f1-a2b0-9ded9ea80dad.png)

**Comment by yaira2** [comment]
@testama this is by design, copy location isn't for copying the item, it's for copying the location of the item. I think you're looking for the copy button.
![image](https://user-images.githubusercontent.com/39923744/235460797-cc42dddb-989c-44cc-89e4-5a1d3292f49c.png)

**Comment by testama** [comment]
> 

yes, that icon is copy button. I know.
I want copy "location".

**Comment by yaira2** [comment]
This is by design, do you have a use case for copying multiple paths into the clipboard?

**Comment by testama** [comment]
yes I have. but, that was an amateur, detour, inefficient way.
I realized I was wrong. thank you.
I try to do without copying multiple path copy.

**Comment by yaira2** [comment]
@testama we'd like to learn more about your use case.

**Comment by testama** [comment]
for Excel(VBA).
I'm low skilled clerical worker, not IT engineer.
1. copying multi paths
2. matching copied paths and image files
3. pasting images into the cells

you can ignore me anymore.

**Comment by testama** [comment]
may I close this issue?
thank you yair100 san.
