### ISSUE TITLE
Downloads folder sorting

### ISSUE THREAD

**Issue by riverstone01** [files-community/Files#12258]
### Description

I expect that the Downloads folder will sort by date descending. 

The app used to do this, but at some point in the last couple of updates it now defaults to name ascending (which is my default under Settings/Folders). I can manually change it, but as soon as I click out of the folder it goes back to name ascending when I return.

### Steps To Reproduce

1. Click on Downloads.
2. Click Sort options. It is set to Name, Ascending.
3. Change to Date modified, Descending.
4. Click on another folder.
5. Clack back on Downloads.
6. Files are back to Name, Ascending.

### Requirements

Set Downloads folder to default sorting to Date modified, Descending.

### Files Version

2.4.70.0

### Windows Version

Windows 11 Pro 22H2 22621.1555

### Log file

[debug.txt](https://github.com/files-community/Files/files/11370385/debug.txt)
The file is over 100MB, but have attached the last couple of days--the same URI error goes back for weeks.

**Comment by riverstone01** [comment]
> Thanks for the report, Can you give the following information.
> 
> * What the path of your download folder or are you using a library?
> * What layout are you using

Thanks for the reply @Josh65-2201. I'm using Columns. Just discovered the problem doesn't occur in other layouts, and that it remembers the layout if I change the Downloads folder to Details. Thanks--should've been able to work that one out!

**Comment by Josh65-2201** [comment]
There is an open issue for this here #12045. You can check for updates on it there.
