### ISSUE TITLE
Bug: Cannot add/remove access control entry

### ISSUE THREAD

**Issue by 0x5bfa** [files-community/Files#12255]
### Description

As the title.

### Steps To Reproduce

1. Click a file's properties
2. Go to Security
3. Click + or -

or

1. Click a file's properties
2. Go to Security
3. Go to Advanced permissions
4. Click Change above.

### Requirements

_Non_

### Files Version

2.4.70.0

### Windows Version

10.0.25336.1010

### Log file

_None_

**Comment by yaira2** [comment]
It opens a legacy dialog from File Explorer but it still works.

**Comment by 0x5bfa** [comment]
Fixed title.
