### ISSUE TITLE
Bug: Files crashes if it tries to access a html/svg file via preview

### ISSUE THREAD

**Issue by piperun** [files-community/Files#12256]
### Description

If you have preview panel on and you access a html file (or svg) it'll crash if you got a firewall blocking the connection for the msedge executable that wants to connect when doing so.

Before it would outright crash and not start up again, but now it simply crashes and then comes back.

### Steps To Reproduce

1. Download a html file
2. Have a firewall like simplewall or comodo firewall with no allowance for the process that previews web pages.
3. just click once on the html file
4. It should crash and start itself again.

### Requirements

- It shouldn't have to re-launch and should instead should either:
* Tell the user that there's no connect and thus can't be previewed
* Default to another browser / showing the raw data / show nothing

### Files Version

2.4.70.0 10.0.19045.2364

### Windows Version

Windows 10 22H2

### Log file

[debug.log](https://github.com/files-community/Files/files/11368862/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I was able to reproduce this.

**Comment by yaira2** [comment]
@hishitetsu was this fixed in your PR?

**Comment by hishitetsu** [comment]
> @hishitetsu was this fixed in your PR?

That is a possibility, but I don't have the environment to test it, so I would like someone to test it.

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/
