### ISSUE TITLE
Edit layout column details

### ISSUE THREAD

**Issue by acdiana** [files-community/Files#12250]
### What feature or improvement do you think would benefit Files?

In music files for example, you want to see information such as bitrate, duration, etc. in the columns.
In video files, other information
It might be possible to choose the columns from any field of the file properties.
![files](https://user-images.githubusercontent.com/132260896/235435516-5c84edd3-39d4-47f1-8ed7-1370a7e82a46.png)
![files](https://user-images.githubusercontent.com/132260896/235435559-9989b0cd-b358-4c8d-9954-ad2323da3de9.png)

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.4.70.0

### Windows Version

Edição	Windows 11 Pro Versão	21H2 Instalado em	‎29/‎05/‎2022 Compilação do SO	22000.1880 Experiência	Pacote de Experiência de Recursos do Windows 11 1000.22001.1000.0

**Comment by Josh65-2201** [comment]
Thanks for the feedback

Merging with https://github.com/files-community/Files/issues/8366
