### ISSUE TITLE
Bug: No Disk Icon in "Disk" Category

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12251]
### Description

I don't see any icons other than the default drive icon in the "Disk" category in Files. Even when I connect removable drives such as USB drives, external hard drives, or memory cards, only a folder icon is displayed.

### Steps To Reproduce

1. Open Files
2. Insert a removable disk
3. Only one file icon appears

### Requirements

The icons associated with each removable disk should be introduced in the sidebar.

### Files Version

Version : 2.4.70.0

### Windows Version

Windows 11 22H2 22621.1635

### Log file

No need

**Comment by yaira2** [comment]
@Lukiluc29 thank you for the report, can you attach the log file?

**Comment by Lukiluc29** [comment]
Why do you attach the log file when it's just an icon and not a bug or for example the application is not responding or something?

**Comment by Josh65-2201** [comment]
Icons not showing is a bug and the log file could show an error on why it won't show them.

**Comment by Lukiluc29** [comment]
[debug.log](https://github.com/files-community/Files/files/11365896/debug.log)

**Comment by yaira2** [comment]
Thanks! Can you also share a screenshot of the issue?

**Comment by Lukiluc29** [comment]
And there is also the OneDrive logo in the sidebar and also where the file is located.
![Capture d'écran 2023-05-01 185310](https://user-images.githubusercontent.com/128183422/235492180-f170b750-26c8-47c0-98e3-a155c3c0b525.png)
![Capture d'écran 2023-05-01 185503](https://user-images.githubusercontent.com/128183422/235492186-39ad67a5-1980-464f-b09a-7646722bc597.png)

**Comment by yaira2** [comment]
@gave92 are removable drives supposed to have the folder icon?

**Comment by Lukiluc29** [comment]
No it should match those
![Capture d'écran 2023-05-01 190026](https://user-images.githubusercontent.com/128183422/235492995-34cab6e4-92f8-440b-8db7-84b8f5c11aaf.png)

**Comment by gave92** [comment]
Nope, iirc we user to display the corect (drive) icon for removable drives.

**Comment by yaira2** [comment]
If it's displaying on the home page, it might be because the sidebar uses a different resolution/size.

**Comment by Lukiluc29** [comment]
> S'il s'affiche sur la page d'accueil, c'est peut-être parce que la barre latérale utilise une résolution/taille différente.

Maybe, but that doesn't explain why internal drives have a logo and removable ones don't.

**Comment by Lukiluc29** [comment]
> If it's displaying on the home page, it might be because the sidebar uses a different resolution/size.

Maybe, but that doesn't explain why internal drives have a logo and removable ones don't.

**Comment by hecksmosis** [comment]
I have a fix
