### ISSUE TITLE
Code Quality: Avoid reflection in SetCursor

### ISSUE THREAD

**Issue by hez2010** [files-community/Files#12253]
As per discussion in https://github.com/files-community/Files/pull/12238#discussion_r1181247346. 

We should get rid of reflection calls and change them to call ProtectedCursor setter from UIElement-derived types directly instead.

**Comment by yaira2** [comment]
👍

**Comment by hishitetsu** [comment]
ProtectedCursor is literally protected, so it cannot be accessed without reflection or creating subclasses that expose the property.
