### ISSUE TITLE
Bug: Files can't copy or move any iso file

### ISSUE THREAD

**Issue by Nightingale0504** [files-community/Files#12259]
### Description

Files can't copy or move any iso files.
When I try to copy or move a iso file, Files' move progress will exceed 100% and there is no upper limit.

### Steps To Reproduce

1. Copy or move a iso file to other folder or drive with Files.

### Requirements

- Let Files can copy or move any iso files and Files' progress won't exceed 100%.

### Files Version

Files version: 2.4.70.0, OS version: 10.0.25217.1010

### Windows Version

Windows 11 22H2 25217.1010

### Log file

[debug.log](https://github.com/files-community/Files/files/11369855/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report. I am unable to reproduce this, Can you give the following information.
- Does it give any errors in Windows File explorer?

**Comment by OperatorRosmontis** [comment]
> Thanks for the report. I am unable to reproduce this, Can you give the following information.
> 
> * Does it give any errors in Windows File explorer?

No, it doesn't.
And the image file isn't .jpg/.jpeg etc. , it's .iso/.img etc.

**Comment by yaira2** [comment]
@Nightingale0504 thank you for reporting this issue, can you check if it's still an issue in v2.5.20?
