### ISSUE TITLE
Code Quality: Use Files.App.Data for data models

### ISSUE THREAD

**Issue by 0x5bfa** [files-community/Files#12265]
### Description

This quality improvement is on going. You can see what kind work is in progress in the bottom, GitHub Issue Timeline.

- Wrong namespace cause mislead.
- Putting classes together in to the same folder make Solution Explorer looks terrible.

### Concerned code

Whole Files.App project

### Gains

- A better readability.
- A better maintainability.

### Requirements

- Do one class per file
- Don't use unofficial workds such as Params and Nav except Args(Rationale: Used in System.EventArgs).
- Organize classes.

**Comment by yaira2** [comment]
@d2dyno1 are you on board for this?

**Comment by d2dyno1** [comment]
Yep, I agree there should be a separation between data and logic 👍

**Comment by 0x5bfa** [comment]
This was done by https://github.com/files-community/Files/pull/12233.
