### ISSUE TITLE
Show localised (localized) names for system folders

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#1226]
**Is your feature request related to a problem? Please describe.**
Not really. In File Explorer, it will show the localized name instead of the real name for system folders such as Users folder.

![2020-06-25 11-13-34_Trim](https://user-images.githubusercontent.com/45227503/85666622-4e3d7e00-b6da-11ea-8c21-dfb1d3e0977b.gif)

**Describe the solution you'd like**
Files UWP should show to localized name instead of the real name for system folders.

**Comment by jaigak** [comment]
@yair100 Could you assign me on this issue?

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran Are you still planning to work on this issue?

**Comment by jaigak** [comment]
@yair100 Yes but only if you let me use StorageFolder

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran The reason we don't use StorageFolder over there is because it will slow down the loading of the items. Perhaps there is another way to find the localized name without using StorageFolder.

**Comment by jaigak** [comment]
@yair100 There's a function named SHGetLocalizedName but it's not allowed in UWP. SHGetFileInfo can also be used but it is also not allowed.

**Comment by yair100** [comment]
> @yair100 There's a function named SHGetLocalizedName but it's not allowed in UWP. SHGetFileInfo can also be used but it is also not allowed.

We can probably put that in the FullTrustProcess.

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran This feature was implemented with #3561.

**Comment by karim891** [comment]
OK fuke you


في الأحد، ١٤ فبراير ٢٠٢١ ٦:١٤ م Yair Aichenbaum ***@***.***>
كتب:
