### ISSUE TITLE
Bug: Values in preview pane can be edited

### ISSUE THREAD

**Issue by mafra99** [files-community/Files#12268]
### Description

The values in the preview pane can be edited.

![image](https://user-images.githubusercontent.com/56681014/235925011-09a7b5b1-2fe8-409e-a325-b7eee85a9305.png)

### Steps To Reproduce

1. Open an item in the preview pane
2. Click on any of the values (e.g. Item count, Date modified, ...)
3. See that it is possible to type in the textbox

### Requirements

- It should not be possible to modify the values

### Files Version

2.4.70.0

### Windows Version

10.0.22621.1555

### Log file

-

**Comment by yaira2** [comment]
@mafra99 thank you for your feedback. We still have to add support for saving the changes but this is by design.
