### ISSUE TITLE
Feature: Option to always load full preview for OneDrive items

### ISSUE THREAD

**Issue by dontthroworanges** [files-community/Files#12270]
### What feature or improvement do you think would benefit Files?

I would like these following settings/improvements to the Preview Pane:

1. Ability to hide file details to increase the size of the file preview. Would like to see the preview as big as possible. 
2. Setting to always load full preview when selecting files stored in OneDrive/SharePoint. 

### Requirements

These proposals will increase the usability of the preview pane for reviewing the contents of a document without opening the document. Additionally, this will increase the usability of storing files in OneDrive and Sharepoint. 

### Files Version

2.4.70.0

### Windows Version

10.0.22621.1555

**Comment by yaira2** [comment]
@dontthroworanges thank you for your feedback, you can already hide the details pane when right clicking on a preview.

**Comment by dontthroworanges** [comment]
> @dontthroworanges thank you for your feedback, you can already hide the details pane when right clicking on a preview.

Thanks for the info. I see that now, thanks. 

I would still appreciate a setting to always load the full preview upon selecting the file. Thanks!

**Comment by yaira2** [comment]
I'm pretty sure this would require downloading the file and depending on the size/internet speed, it can take some time to display the preview. Is that still something you'd be interested in?

**Comment by yaira2** [comment]
@dontthroworanges it looks like this is resolved in the latest preview build. Can you give it a try and confirm if it's working as expected? https://files.community/download
