### ISSUE TITLE
After closing the window, continue running the application

### ISSUE THREAD

**Issue by KFC-code** [files-community/Files#12279]
### What feature or improvement do you think would benefit Files?

I would like to make the app not closing entirely when you close the window.

### Requirements

It would increase the performance on low-end devices, as is wouldn't had to load the entire app.

### Files Version

2.4.70.0

### Windows Version

Windows 11 22H2 22624.1616

**Comment by yaira2** [comment]
Thanks for the feedback, Merging with https://github.com/files-community/Files/issues/11279

This is planned but there a few issues in Files that has to solve before doing this. You can check the above issue for updates. You can also just minimize Files rather than closing.

**Comment by yaira2** [comment]
@KFC-code This feature is included in the latest preview build (https://files.community/download) and will be included in the v3 release.
