### ISSUE TITLE
Full Tree expand of the drives on the left pane

### ISSUE THREAD

**Issue by Sush85** [files-community/Files#12271]
### What feature or improvement do you think would benefit Files?

Is it possible to full tree-like expand the drives on the left pane like windows explorer?

### Requirements

The drive letters on the left side should expand fully with tree-like structure just like windows explorer

### Files Version

2.4.70.0

### Windows Version

Windows 11 22H2 22621.1635

**Comment by yaira2** [comment]
Thank you for your feedback, we don't have plans to implement a tree view sidebar but we're planning to add a dedicated tree view layout in #1928.

**Comment by yair100** [comment]
@Sush85 Tree View is currently available in preview https://files.community/download. It will be included in the next stable release.
