### ISSUE TITLE
Bug: Advanced permissions page messes up navigation history

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#12277]
### Description

After I click the back button at the advanced permissions page on a properties window, the security page doesn't open even if I try to open it.

### Steps To Reproduce

1. Open a properties window.
2. Click Security.
3. Click Advanced permissions.
4. Click the back button.
5. Click General.
6. Click Security.
7. The security page will not open. 

### Requirements

Navigation must always work properly.

### Files Version

2.4.80.0

### Windows Version

Windows 11 22H2

### Log file

There are no logs related to this issue.

**Comment by 0x5bfa** [comment]
Thank you for reporting this. I can repro and will work on this.

**Comment by yaira2** [comment]
@0x5bfa how is this going?

**Comment by yaira2** [comment]
@0x5bfa are you still working on this?

**Comment by 0x5bfa** [comment]
Not actually. But if someone is stucking on this issue, I would tell them what API should be called and where the proper data is.
