### ISSUE TITLE
Details view Columns

### ISSUE THREAD

**Issue by BammBeee62** [files-community/Files#12278]
### What feature or improvement do you think would benefit Files?

I use a file manager to organise mainly audio and video files and some extra columns in the details view (there are only 5 available) would allow me to exclusively use this app.
Access to Bitrates and some of the tags would be much appreciated.

### Requirements

- This proposal will accomplish having more details columns to choose from.
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.4.70.0

### Windows Version

Windows 11 Pro 22H2 1000.22640.1000.0

### Comments

Thankyou, this app, by the way, is far faster than File Explorer on my machine.

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #8366. You can check there or click subscribe in the right sidebar for updates.
