### ISSUE TITLE
Bug: Renaming a file in dual pane causes focus to keep changing

### ISSUE THREAD

**Issue by Androl404** [files-community/Files#12285]
### Description

After entering panel view, and working between the files a bit, Files starts switching very fast between the two panels. You can see it in the right bar if you're working on two different disks.

### Steps To Reproduce

1. Open Files
2. Enter pannel mode
3. Start working
4. After about 2 minutes, the issue occurs

### Requirements

- Make Files to stay in the last used pannel

### Files Version

2.4.70.0

### Windows Version

Windows 10 Family 22H2 19045.2913 Windows Feature Experience Pack 1000.19041.1000.0

### Log file
[debug.log](https://github.com/files-community/Files/files/11410170/debug.log)

**Comment by Josh65-2201** [comment]
Can you please upload (Do not copy and paste content) the debug.log file. You can get it in Files settings > About > Open log folder.

**Comment by Androl404** [comment]
It says it's too long because its 10 707 lines

**Comment by Josh65-2201** [comment]
It should work if you upload the file. I assume you trying to copy and paste the content of it into the box.

**Comment by Androl404** [comment]
Sorry, I've modified the first message, it should contain the log (the whole file)

**Comment by Josh65-2201** [comment]
Thanks

**Comment by yaira2** [comment]
I was able to reproduce this issue

**Comment by ferrariofilippo** [comment]
I was able to reproduce this in 2.4.70 but I can't in 2.4.81

**Comment by yaira2** [comment]
I don't think we changed anything that would have fixed the issue but it's hard to test since it's on and off.

**Comment by yaira2** [comment]
@Androl404 this issue will be resolved in v2.5.

**Comment by Androl404** [comment]
> @Androl404 this issue will be resolved in v2.5.

Sounds great ! Thank you very much !
