### ISSUE TITLE
Bug: Dual Pane crashes consistently any time images are loading

### ISSUE THREAD

**Issue by blainegrissom** [files-community/Files#12280]
### Description

Any time dual pane is enabled and two folders with multiple images are opened, Files lags and stops loading contents of folders even if you go to another folder. Neither the context menu nor the properties windows can be opened, as they immediately close. After ~10-15 seconds or trying to interact with other parts of the Files interface, Files freezes and must be closed before being able to be used again. This happens regardless of local drives or network drives.

### Steps To Reproduce

Enable dual pane mode, either through settings or the three-dot menu in the top right of Files.

In both panes, open a folder with multiple images. The layout mode does not matter.

After moving through the file system for a few seconds, or by opening another folder with images in the other pane, you will notice Files start to slow down terribly. In the details layout you will notice the drive/folder you are in will have a blue bar flickering and shifting rapidly, as if Files is constantly trying to calculate the size of the folder/drive.

### Requirements

Fix unresponsive behavior when navigating folders with large amounts of content in dual-pane mode.

Fix Files crash caused by using dual-pane mode in a manner that would cause multiple files to index.

### Files Version

2.4.70.0

### Windows Version

10.0.19045.2846

### Log file

[debug.log](https://github.com/files-community/Files/files/11408463/debug.log)

**Comment by yaira2** [comment]
Thank you for reporting this issue

**Comment by blainegrissom** [comment]
Of course. The weirdest thing to me is that the log file does not reflect this issue.

**Comment by yaira2** [comment]
I saw some errors in the log file that might be related, if you want to confim, you can try deleting the log file and reproducing the issue again.

**Comment by blainegrissom** [comment]
Sorry about that, was busy today. Here's a clean log reproducing the issue.
[debug.log](https://github.com/files-community/Files/files/11410804/debug.log)

**Comment by yaira2** [comment]
Thanks for checking, the latest preview build (https://files.community/download) has some fixes that might help. Can you try the preview and see if it helps?

**Comment by blainegrissom** [comment]
Sure thing!

**Comment by blainegrissom** [comment]
Issue occurred again. Here is the debug.log
[debug.log](https://github.com/files-community/Files/files/11437183/debug.log)

**Comment by hishitetsu** [comment]
This may be the same issue as #12285.

**Comment by yaira2** [comment]
@blainegrissom this issue will be fixed in v2.5.
