### ISSUE TITLE
Feature: Nilesoft Shell Context Menu Integration

### ISSUE THREAD

**Issue by hboyd2003** [files-community/Files#12287]
### What feature or improvement do you think would benefit Files?

[Nilesoft Shell](https://github.com/moudey/Shell) is an advanced alternative to the Windows 11 context menu, offering extensive customization capabilities and the ability to effortlessly create custom context menu entries. Integrating Shell's custom context menu with Files would significantly enhance the user experience, especially for power users who value customization and efficiency.

While Shell is not open-source, users of it can effectively not use Files as it eliminates the effectiveness of Files and I believe that its integration into Files would greatly benefit both communities.

### Requirements

- Nilesoft Shell's custom context menu entries show up in the Files context menu
- Custom context menu entries show up seamlessly among the standard Files context menu.

### Files Version

2.4.80.0

### Windows Version

Windows 11 Pro 22H2 22621.1635

**Comment by yaira2** [comment]
Files already displays shell extensions, are these not showing for you?

**Comment by Tctcl** [comment]
I've just tried this myself, the Files context menu does not seem to be displaying any of the added Items.
I've also tried [ikas-mc](https://github.com/ikas-mc) [ContextMenuForWindows11](https://github.com/ikas-mc/ContextMenuForWindows11) and any of the custom Items I created there would also not show up.

**Comment by hboyd2003** [comment]
@yair100 Nilesoft Shell fully replaces the context menu (to my understanding) so it does not add its custom entries via a shell extension. As it is the context menu itself, it handles them.

**Comment by yaira2** [comment]
We appreciate the feedback but we don't have plans to support this in Files.
