### ISSUE TITLE
Bug : issues with Office document preview and editing time in Files

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12289]
### Description

I am experiencing some issues with the document preview feature in Files. When I click on an Office document (Word, PowerPoint, etc.) and the preview window is opened, only the first page or slide is displayed, and it is very blurry.I would like to be able to resize the document when enlarging or shrinking the preview pane in "preview only" mode, similar to what can be done with PDF. Additionally, when I check the editing time in the preview window, it shows an incorrect value of "2110200000000" instead of the actual editing time displayed in the document details, which is "3517 minute(s)".

### Steps To Reproduce

1. Go to "Document."
2. Click on a Word or PowerPoint document, for example.

### Requirements

1. Ensure that the document preview feature is functioning properly and displays all pages/slides clearly.
2. Update the editing time in the preview window to match the actual editing time displayed in the document details.
3. Fix any errors in the display of editing time in the document details, if applicable.
4. The implementation of a feature allowing to resize documents in the preview pane, as it is possible with PDF.

### Files Version

Version : 2.4.80.0

### Windows Version

Windows 11 22H2 22621.1635

### Log file

<img width="352" alt="Capture d'écran 2023-05-06 105327" src="https://user-images.githubusercontent.com/128183422/236614406-ca9fc9a1-cedd-444c-b3ca-d374d38a80a7.png">
<img width="374" alt="Capture d'écran 2023-05-06 103118" src="https://user-images.githubusercontent.com/128183422/236614408-16d8f3b6-e014-420d-89ec-c3e80068ad62.png">
<img width="372" alt="Capture d'écran 2023-05-06 103149" src="https://user-images.githubusercontent.com/128183422/236614410-5be2b389-c1a3-4e3d-a696-1d7bd1fe68b8.png">
<img width="372" alt="Capture d'écran 2023-05-06 103843" src="https://user-images.githubusercontent.com/128183422/236614412-bad791cd-9bfc-4342-9b01-10600bccd6fe.png">

**Comment by Lukiluc29** [comment]
And also the preview of Office files like Word and PowerPoint is only done on files downloaded in OneDrive

**Comment by Josh65-2201** [comment]
Thanks for the report.
> The preview of Office files like Word and PowerPoint is only done on files downloaded in OneDrive

The file has to be downloaded since without doing so there isn't any data there for the preview.

> Ensure that the document preview feature is functioning properly and displays all pages/slides clearly

Can you make a bug report for this

> Update the editing time in the preview window to match the actual editing time displayed in the document details

Can you make a bug report for this

> The implementation of a feature allowing to resize documents in the preview pane, as it is possible with PDF

Can you make a bug report using the 1st and 2nd screenshots for examples.

**Comment by Lukiluc29** [comment]
> Merci pour le rapport.
> 
> > L'aperçu des fichiers Office comme Word et PowerPoint se fait uniquement sur les fichiers téléchargés dans OneDrive
> 
> Le fichier doit être téléchargé car sans cela, il n'y a pas de données pour l'aperçu.
> 
> > Assurez-vous que la fonction d'aperçu du document fonctionne correctement et affiche clairement toutes les pages/diapositives
> 
> Pouvez-vous faire un rapport de bogue pour cela
> 
> > Mettez à jour l'heure d'édition dans la fenêtre d'aperçu pour qu'elle corresponde à l'heure d'édition réelle affichée dans les détails du document
> 
> Pouvez-vous faire un rapport de bogue pour cela
> 
> > La mise en place d'une fonctionnalité permettant de redimensionner les documents dans le volet de prévisualisation, comme c'est possible avec PDF
> 
> Pouvez-vous faire un rapport de bogue en utilisant les 1ère et 2ème captures d'écran pour des exemples.

But there is no other way to see the file without uploading it to OneDrive

**Comment by Josh65-2201** [comment]
For local files it's a known issue. You can check here https://github.com/files-community/Files/issues/4041 for updates.

**Comment by Lukiluc29** [comment]
And you know when you are going to tackle this problem?

**Comment by Josh65-2201** [comment]
There isn't any known time right now. If progress is made it will be shown in that issue.
