### ISSUE TITLE
Bug: Details pane has the wrong editing time value

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12296]
### Description

When I check the editing time in the preview window, it shows an incorrect value of "2110200000000" instead of the actual editing time displayed in the document details, which is "3517 minute(s)".

### Steps To Reproduce

1. Go to "Document."
2. Click on a Word or PowerPoint document, for example.

### Requirements

Update the editing time in the preview window to match the actual editing time displayed in the document details.

### Files Version

Version : 2.4.80.0

### Windows Version

Windows 11 22H2 22621.1635

### Log file

<img width="374" alt="236614408-16d8f3b6-e014-420d-89ec-c3e80068ad62" src="https://user-images.githubusercontent.com/128183422/236642531-145458a7-a615-447c-83fe-160569531102.png">

**Comment by Josh65-2201** [comment]
Thanks for the report.

**Comment by yaira2** [comment]
This will be fixed in v2.5.

**Comment by Lukiluc29** [comment]
> This will be fixed in v2.5.

I installed the new version of Files, which is 2.4.81, but when I check the total editing time for a Word document, everything is correct. However, for PowerPoint files, it's incorrect, but only on some files, not all.
![Capture d’écran (8)](https://github.com/files-community/Files/assets/128183422/415ffae0-afa7-40d1-bf18-fbe54bfcca63)
<img width="234" alt="Capture d'écran 2023-05-09 131805" src="https://github.com/files-community/Files/assets/128183422/adcebf98-235b-45bf-94f4-eadc9fe9fa41">
