### ISSUE TITLE
Bug : issues with Office document preview

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12295]
### Description

I am experiencing some issues with the document preview feature in Files. When I click on an Office document (Word, PowerPoint, etc.) and the preview window is opened, only the first page or slide is displayed and she's very blurry on top of that.

### Steps To Reproduce

1. Go to "Document."
2. Click on a Word or PowerPoint document, for example.

### Requirements

Ensure that the document preview feature is functioning properly and displays all pages/slides clearly.

### Files Version

Version : 2.4.80.0

### Windows Version

Windows 11 22H2 22621.1635

### Log file

<img width="372" alt="236614410-5be2b389-c1a3-4e3d-a696-1d7bd1fe68b8" src="https://user-images.githubusercontent.com/128183422/236642338-b3e96b2d-a5ec-4408-af64-0f6c401bf7ca.png">
<img width="374" alt="236614408-16d8f3b6-e014-420d-89ec-c3e80068ad62" src="https://user-images.githubusercontent.com/128183422/236642340-ccac108b-6124-47ac-bf44-ca7cde0a798f.png">

**Comment by Josh65-2201** [comment]
This might also be related to #4041

**Comment by yaira2** [comment]
We don't have support for previewing Office files yet, what you're seeing is the thumbnail.

**Comment by yaira2** [comment]
Merging with #4041
