### ISSUE TITLE
Bug: Crash due to git directory on WSL drive

### ISSUE THREAD

**Issue by LaaZa** [files-community/Files#12292]
### Description

When trying to open directory in WSL that contains .git, Files crashes. This is a new issue with the new git integration.

### Steps To Reproduce

1. Go to WSL
2. Click to open a directory containing a .git directory
3. Crash

### Requirements

Fix crash that occurs when trying to open git directories on WSL.

### Files Version

2.4.80.0

### Windows Version

10.0.22621.1635

### Log file

[debug.log](https://github.com/files-community/Files/files/11412437/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I was able to reproduce this.

**Comment by yaira2** [comment]
This issue will be fixed in the next preview build.
