### ISSUE TITLE
Option to use custom Right Click menu, custom shell and administrator copy

### ISSUE THREAD

**Issue by Victorcangil** [files-community/Files#12306]
### What feature or improvement do you think would benefit Files?

I am using [ExplorerPatcher](https://github.com/valinet/ExplorerPatcher) to change my Windows 11 Right Click menu to use the Windows 10 one, because I like it more. WHen using files, I find that it forces its own Right Click menu.
Is there an option, inside the app or in registry, to be able to use these custom Right Click menus?
I want to have it like this:
![ExplorerPatcher's Windows 10 right click](https://user-images.githubusercontent.com/7458743/236855373-b000d296-b1d3-49a5-b313-876c866cf27a.png)
But Files forces it like this
![Files right click](https://user-images.githubusercontent.com/7458743/236855449-70a90cf7-6d95-4df3-9799-758848984b60.png)

Also, is there a way to use Windows' shell instead of Files custom, soz, for example, use Teracopy's copy dialog?
Also, is there a way to have a pop.-up ask for administrator priviledges when copying to admin protected folders (Like C:/ProgramFiles). I have to use Windows Explorer to copy as admin because Files doesn't let me.

### Requirements

-Proposal to use custom Right Click menus and bypass the custom Files shell.
-Hability to use custom context menus when copy pasting, such as Teracopy

### Files Version

2.4.70.0

### Windows Version

Windows 11 22H2 (SO 22621.1635)

**Comment by Josh65-2201** [comment]
It isn't possible to use the Windows 10 style context menu as Files doesn't have the code or access for it at all.

**Comment by Josh65-2201** [comment]
What are your reasons to want to use the old style?

**Comment by Victorcangil** [comment]
I find it more useful, having every option at plain sight, without having to go to any submenus (I know the option of having the submenus on the main right click menu is there, but even after trying that, I find myself going back to the Windows 10 style. I don't know, I find it faster overall and more useful (I'm referring to Windows 10 to Windows 11, without refering to the Files one)
