### ISSUE TITLE
Use suspended start time

### ISSUE THREAD

**Issue by humbertomoli99** [files-community/Files#12300]
### What feature or improvement do you think would benefit Files?

I've noticed that while the Files application is generally good, it takes a bit of time to start up. To improve my experience and make the app more responsive, I suggest adding the "Use Suspended Start Time" feature. This feature would allow the app to start up more quickly by leveraging the suspended state of the app when it was last used, instead of requiring a full startup sequence every time. I believe that adding this feature would greatly benefit me as a user and make the Files app more competitive in the market.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.4.70.0

### Windows Version

22H2 22621.1555

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #11279 as that's the current plan. You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
@humbertomoli99 This feature is included in the latest preview build (https://files.community/download) and will be included in the v3 release.
