### ISSUE TITLE
Bug: Preview pane dimensions reset after changing the orientation 

### ISSUE THREAD

**Issue by enricodarodda** [files-community/Files#12317]
### Description

When I split my screen among two apps, the Files window gets automatically resized to accomodate the spacing that I need. However the preview sidebar does not maintain the previous setting (in terms of dimension) once i go out of the side-by-side app view, and it just goes back to the initial/default dimension, which is too small for me. The thing is that when the files app is in side-by-side mode, the sidebar gets placed below the elements, great design choice, and if I resize it it maintains its dimension even if I go in and out of side-by-side mode, but the contrary is not true, so the dimension preview sidebar when I have my app is not preserved when I move in and out of the side-by-side mode.

### Steps To Reproduce

1. Open the files app
2. Open the preview sidebar
3. move the files app to the right (or left) part of the screen until it gets attached to the side (alternatively use the keyboard shortcut: start + left/right arrow key)
4. go out of side-by-side app view

### Requirements

- eg. Fix preview sidebar bug that occurs when you go in and out of side-by-side app viewing

### Files Version

2.4.70.0

### Windows Version

10.0.19045.2913

### Log file

[debug.log](https://github.com/files-community/Files/files/11440237/debug.log)

**Comment by yaira2** [comment]
@enricodarodda can you attach a screen recording of this issue?

**Comment by enricodarodda** [comment]
Unfortunately the file becomes quite big, can I be clearer somehow?

**Comment by yaira2** [comment]
I see, it looks like it changes to the minimum size.

**Comment by enricodarodda** [comment]
Yeah, exactly

**Comment by yaira2** [comment]
This appears to be fixed in the latest dev build. The changes will be included in the upcoming v2.5 release.
