### ISSUE TITLE
Smaller tile size option

### ISSUE THREAD

**Issue by takanobuko-kore** [files-community/Files#12319]
### What feature or improvement do you think would benefit Files?

The icons in the Files' tile are bigger than the ones in Explorer's tile.

When I compared by the same windows size of the app,

Explorer can show 50 folders,
![Explorer](https://github.com/files-community/Files/assets/110897881/4be631a6-30a4-454a-8f0a-c37076b45cc3)
But Files can show 35 folders.
![Files](https://github.com/files-community/Files/assets/110897881/75a23d5c-ded8-4783-99a2-c00dd44397cd)

### Requirements

- Using the smaller icon in tile mode

or

- Controllable the size by `DefaultGridViewSize` in user_setting.json

### Files Version

2.4.70.0

### Windows Version

10.0.22621.1702

**Comment by Josh65-2201** [comment]
Thanks for the feedback have you tried compact mode in Files settings > Appearance > Use compact spacing in the details layout

**Comment by yaira2** [comment]
Support for additional sizes is actively being worked on, you can track the latest progress in #10492.
