### ISSUE TITLE
Bug: Cannot Paste Folder to Files on Remote Desktop

### ISSUE THREAD

**Issue by takanobuko-kore** [files-community/Files#12318]
### Description

I use a Windows native remote desktop connection.
I often copy files between a source PC and a destination PC, but I found the below behaving;

||  src -> dest |  dest -> src  |
| ---- | ---- | ---- |
|  file  |  yes  |  yes  |
|  folder  |  **no**  |  yes  |

The source PC is Windows 10, not using Files, and the destination PC is Windows 11, using Files.
Only folders cannot be pasted, so I assume that it's not a design but a bug.

### Steps To Reproduce

1. Connect to remote PC which is using Files by Windows native remote desktop connection.
2. Copy folder from source PC to destination PC.

### Requirements

- Be able to copy folder from source PC to destination PC.

### Files Version

2.4.70.0

### Windows Version

10.0.22621.1702

### Log file

[debug.log](https://github.com/files-community/Files/files/11440328/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I was able to reproduce this.

**Comment by yaira2** [comment]
Thank you for reporting this issue, it'll be resolved in the upcoming v2.5 release.
