### ISSUE TITLE
Code Quality: Append `Async` to the end of each async method for consistency

### ISSUE THREAD

**Issue by itsWindows11** [files-community/Files#12310]
### Description

Some of the methods in the codebase have `Async` in the end of the method name for the async task, but most async methods in the entire solution don't end with `Async`, for example `ArchiveHelpers.DecompressArchiveHere`.

### Concerned code

The entire solution.

### Gains

- Better consistency between async method namings.
- Quickly identify async methods that might not be awaited in the codebase.

### Requirements

- Append `Async` to all the async method names, i.e. instead of `public Task Do()`, rename to `public Task DoAsync()`.
- For `async void` methods keep them as is, don't add `Async` to it.

**Comment by yaira2** [comment]
@itsWindows11 do you want to work on this?

**Comment by itsWindows11** [comment]
I'm currently busy with exams and stuff so haven't got much time to work on it unfortunately. Feel free to assign someone else to work on it.

**Comment by yaira2** [comment]
No worries, it's low priority anyways. I added it to the project board for tracking.

**Comment by gauravagrwal** [comment]
I will work on this

**Comment by yaira2** [comment]
@gauravagrwal are you still working on this?

**Comment by itsWindows11** [comment]
@yaira2 I might be able to work on it now this weekend.

**Comment by yaira2** [comment]
Thanks!
