### ISSUE TITLE
Enhancement request: error message for Networks

### ISSUE THREAD

**Issue by lucas-thiebaut** [files-community/Files#12323]
### What feature or improvement do you think would benefit Files?

I would like to propose an enhancement to the system behavior when networks are not activated. Currently, when a network is inactive, it displays "This folder is empty". Instead, it would be helpful to show an error message with an option to enable the network, such as a button to activate it, instead of displaying "Folder Empty" or providing an alternative method to activate it.

### Requirements

1. Implement an error message system when networks are inactive.
2. Provide an option, such as a button, to enable the network.

### Files Version

Version : 2.4.81

### Windows Version

Windows 11 22H2 22621.1702

**Comment by Josh65-2201** [comment]
https://github.com/files-community/Files/issues/1100 could also be more accurate

**Comment by Lukiluc29** [comment]
> Thank you for your feedback, can you confirm if this is the same as #9735?

Yes, that's right. It would be like the Windows file explorer with an error message, and once the error message is removed, a small banner appears at the top, and when we click on it, it offers to activate it.
