### ISSUE TITLE
Is acrylic mode come back?

### ISSUE THREAD

**Issue by redhotideas** [files-community/Files#12320]
### What feature or improvement do you think would benefit Files?

is the acrylic version of the background available again?

### Requirements

- go to settings
- acrylic background on

### Files Version

v2.4.70

### Windows Version

Windows 11

### Comments

please integrate it again.

**Comment by Josh65-2201** [comment]
There is no change from the previous answer in https://github.com/files-community/Files/issues/10690#issuecomment-1387196659

**Comment by yaira2** [comment]
We're excited to share to acrylic will be returning in v2.5.
