### ISSUE TITLE
Bug: Keyboard shortcuts for resizing thumbnail sizes aren't working

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#12322]
### Description

The keyboard shortcuts for increasing/decreasing thumbnail sizes are no longer working.

### Steps To Reproduce

1. Switch to the grid layout
2. Try using `ctrl` + `+` and `ctrl` + `-` to change the thumbnail size
3. Nothing happens

### Requirements

- Properly adjust the thumbnail sizes

### Files Version

v2.4.81

### Windows Version

Windows 11

### Log file

NA

**Comment by Lukiluc29** [comment]
On my side everything works as it should be with the shortcut Ctrl + +/- or Ctrl + mouse wheel

**Comment by yaira2** [comment]
Are you using the num pad?

**Comment by ferrariofilippo** [comment]
> Are you using the num pad?

Using the num pad everything works on my side

**Comment by yaira2** [comment]
What about the on the regular keyboard?

**Comment by ferrariofilippo** [comment]
> What about the on the regular keyboard?

It won't work in that case

**Comment by ferrariofilippo** [comment]
@cinqmilleans why is `IsVisible` set to `false` here?
![3](https://github.com/files-community/Files/assets/102259289/9cf6466f-1a4f-45bc-a3c3-b57f348b2a99)

**Comment by cinqmilleans** [comment]
Keyboard shortcuts with IsVisible false are usable but do not appear in menus and tooltip that show hotkeys. They will be visible in the command palette and editing hotkeys. This mainly concerns specific keys on certain keyboards for direct access (GoForward, etc.).

**Comment by ferrariofilippo** [comment]
Do we need the `!` in the command code?

**Comment by cinqmilleans** [comment]
The command code does not change, it is the hotkey code that changes.  This is used to parse the hotkey for custom hotkeys.  If it's inconvenient, you can use another notation.  I'll watch this when I get back in a few days. What is the problem exactly ?
