### ISSUE TITLE
Feature: Make the rename text box larger

### ISSUE THREAD

**Issue by takanobuko-kore** [files-community/Files#12321]
### What feature or improvement do you think would benefit Files?

When I rename files which has a long name in Explorer, a text area will appear.
![1](https://github.com/files-community/Files/assets/110897881/7b24bd17-6ee5-4c53-af5d-4c3857c2bd34)
![2](https://github.com/files-community/Files/assets/110897881/91694c9e-83a8-439c-b911-1eaeda7f0cff)

But in Files, a single-line textbox will appear.
![3](https://github.com/files-community/Files/assets/110897881/aae572c0-ed89-4e9a-b57c-48bb11063b1e)
![4](https://github.com/files-community/Files/assets/110897881/1a57d79b-9c54-4616-99bc-1b59ae730e25)

It is too hard to rename a long name while checking.

### Requirements

- Rename textbox should fill up the vertical space in the grid layouts

### Files Version

2.4.70.0

### Windows Version

10.0.22621.1702

**Comment by PhillipTodorov** [comment]
Hi, I would be willing to work on this, is this is only an issue in Details, Tiles, Columns and Adaptive view, is the goal to make all of the views with dynamically sized text boxes?

**Comment by yaira2** [comment]
@PhillipTodorov it's specific to the tiles and grid layouts. I think the solution is to change the row span of the text box when the item is being renamed.

**Comment by KlenAr313** [comment]
Heyo! 
I noticed that there wasn't any progress here, and I would like to solve this problem. But I have a question:
Should I get rid of the X, like in the example?

(This is my first contribution here, and I couldn't open the xaml-s in Designer. Is this a common thing in this project, or is it just for me?)

**Comment by yaira2** [comment]
@KlenAr313 WinUI3 doesn't have a visual designer.

**Comment by yaira2** [comment]
@takanobuko-kore thank you for your feedback, this issue will be addressed in the next update.
