### ISSUE TITLE
All image extensions show photo icon with "ext name" as an image instead of the actual thumbnails

### ISSUE THREAD

**Issue by hisdumbpuppy** [files-community/Files#12324]
### Description

All image extensions show photo icon with "ext name" as an image instead of the actual thumbnails

<img width="756" alt="image" src="https://github.com/files-community/Files/assets/34972545/8e1ecd96-a9c5-47e5-9785-daaee89a544c">

<img width="643" alt="image" src="https://github.com/files-community/Files/assets/34972545/5ad46b51-09d6-48ec-b33b-b47615f231b4">

<img width="722" alt="image" src="https://github.com/files-community/Files/assets/34972545/2b82e703-ee78-458f-ace8-f997769cfd87">

### Steps To Reproduce

Open files app
Find a folder that contains PNGS, JPG, ICO (Any image extension)
They are shown as generic icons

<img width="162" alt="image" src="https://github.com/files-community/Files/assets/34972545/548af02d-f4cc-4c34-9c57-83caab8051be">

### Requirements

Unsure of how to resolve this

### Files Version

2.4.70.0

### Windows Version

Windows 11 Pro 22H2 22621.1702

### Log file

[debug.log](https://github.com/files-community/Files/files/11445368/debug.log)

**Comment by cattenbb** [comment]
Good point - Ya they show up fine there. Might be user error on my end though. Just wanted to give a heads up in case anyone has this as well.

**Comment by gave92** [comment]
Is this only for Onedrive online files or also for local images?

**Comment by cattenbb** [comment]
It is happening with both

**Comment by yaira2** [comment]
@hisdumbpuppy what do these look like in File Explorer?

**Comment by yaira2** [comment]
@hisdumbpuppy
