### ISSUE TITLE
Sub menu disappear when we move mouse

### ISSUE THREAD

**Issue by rajq123** [files-community/Files#12328]
### Description

Right click sub-menu disapearing when it is above the mouse cursor. See the 10 sec video and you will get my point

### Steps To Reproduce

just the video explains

### Requirements

i think the behaviour to close that menu should be altered in some way like seconds or proximty to the mouse

### Files Version

2.3.12

### Windows Version

win 10 1709

### Log file

https://github.com/files-community/Files/assets/57880269/7951f471-edca-468d-bc00-3657d2b84868

**Comment by yaira2** [comment]
Thank you for your feedback, which version of Files are you using?
