### ISSUE TITLE
Bug: Tags on network drives are not displayed when selecting tag

### ISSUE THREAD

**Issue by Cromagnon31** [files-community/Files#12331]
### Description

Tags on network drives are not displayed when selecting tag

### Steps To Reproduce

Create a new tag.

Associate tags to network drive directory (standard windows share mapped on a letter)
Select tag in the left pane.

Tagged network directories are not in the right pane.

### Requirements

- Display tagged items from network drives

### Files Version

2.4.70.0

### Windows Version

Windows 11 Professionnel 22H2 22621.1555

**Comment by yaira2** [comment]
Thank you for your feedback, can you please add the log file as an attachment instead of copy/pasting the contents?

**Comment by Cromagnon31** [comment]
[debug.log](https://github.com/files-community/Files/files/11453995/debug.log)

**Comment by gave92** [comment]
Could you check if the tags put on network files are present in the normal file view if you refresh the folder/reopen the app?

**Comment by Cromagnon31** [comment]
Yes, same tag on a local file works well. After closing/reopening the tag on the network file is always set, but no files appears in the  view when selected.

 

De : Marco Gavelli ***@***.*** 
Envoyé : jeudi 11 mai 2023 21:17
À : files-community/Files
Cc : OlivierW; Author
Objet : Re: [files-community/Files] Bug: Tags on network drives are not displayed when selecting tag (Issue #12331)

 

Could you check if the tags put on network files are present in the normal file view if you refresh the folder/reopen the app?
