### ISSUE TITLE
Navigation Pane 

### ISSUE THREAD

**Issue by Doncampa** [files-community/Files#12330]
### What feature or improvement do you think would benefit Files?

I find the Navigation Pane useful for navigating through folders and files

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.4.70.0

### Windows Version

Windows 11 Pro 22H2 22621.1702

**Comment by yaira2** [comment]
Thank you for your feedback, can you explain what you mean by navigation pane?

**Comment by yaira2** [comment]
@Doncampa
