### ISSUE TITLE
Removing duplicates in localized strings

### ISSUE THREAD

**Issue by QuaintMako** [files-community/Files#12341]
### Description

Some localized strings are duplicates of each other in Files. Some work can be done to reduce said duplications.

### Concerned code

- English localization, the other localizations will be updated automatically when the resources.

### Gains

- Shorter time needed to translate Files.
- Easier to review the translations.
- A better maintanability overall.

### Requirements

- Any string that are duplicated are fused in one.
- The removed strings are properly replaced in code.

**Comment by hishitetsu** [comment]
I previously removed duplicate strings in #11462.
There may be some duplicate keys again, but most of the duplicate strings have key names with special meanings. (Key.Home, CompressionLevelNone, etc.)
These are referenced by dynamically generated keys, so strings can no longer be referenced if key names are changed.
