### ISSUE TITLE
Bug: Issue with Blurriness when Switching Files View Modes

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12349]
### Description

I have encountered an issue with Files where, when switching from Column or Details view mode to Tiles, Small Icons, Medium Icons, or Large Icons view modes, only the first item appears sharp while all the other items appear blurry.

### Steps To Reproduce

1. Navigate to a directory that is in either Details or Column view mode.
2. Switch to Tiles, Small Icons, Medium Icons, or Large Icons view mode.

### Requirements

Investigate the cause of blurriness when switching view modes.

### Files Version

Version : 2.4.81

### Windows Version

Windows 11 22H2 22621.1702

### Log file

![Capture d’écran (12)](https://github.com/files-community/Files/assets/128183422/77e7d7a6-24cb-49ce-b195-0fda207efbd3)
<img width="770" alt="Capture d'écran 2023-05-13 180152" src="https://github.com/files-community/Files/assets/128183422/ab5fb713-bec1-4266-bd2d-f14aff5affec">

**Comment by Josh65-2201** [comment]
Thanks for the report, Can you give the following information.
- Does refreshing the folder fix it?

**Comment by Lukiluc29** [comment]
> Thanks for the report, Can you give the following information.
> 
> * Does refreshing the folder fix it?

Yes, but then I always have to update my files when I change the display

**Comment by yaira2** [comment]
Is this folder by any chance in OneDrive?

**Comment by Lukiluc29** [comment]
> Is this folder by any chance in OneDrive?

No, not necessarily because look at the image below, the elements are not in the Cloud
![Capture d’écran (18)](https://github.com/files-community/Files/assets/128183422/e8fa4de0-c89d-4aef-87f8-82e66284aff5)
