### ISSUE TITLE
Code Quality: Continued work to clean up entire project

### ISSUE THREAD

**Issue by 0x5bfa** [files-community/Files#12340]
### Description

This is a milestone to display what PR is related the cleaning-up plan. Rationale is that Files source codebase don't have consistency. All of us absolutely must be forced to follow the guideline to keep code clean. I will clean up the project with the strict order I defined so that I would not break any existing functionalities. 

### Concerned code

I have following stages to clean up:
1. Rename files with the appropriate name and put them into appropriate namespace for each.
2. Rename variables with preferred name to follow the guideline (The most likely to happen is that I rename property-backing-field from '_isHidden' to '_IsHidden')
3. Reorder variables & methods to follow the class structure guideline (Section 3 in the guildeline)
4. Add/Update/Improve C# XML Comments and double-slashed comments.
6. Refactor to improve performance. You can see what I will work on in Requirements section.

- Files.App.**
- Files.Shared
- Files.Backend

### Gains

- A better readability.
- A better maintainability.
- Faster build of Files.App

### Requirements

- Force to follow the guideline in anyway
- Add sealed accessor to entire Files.App except classes from which other classes have to be deriven.
- Add internal accessor to entire Files.App
- Append Async to the end of async method name
- Add init accessor to properties which have to be readonly
- Use Utils namespace for utilities, manangers, and watchers
- Use Lazy class for delay initialization
- Avoid boxing

**Comment by yaira2** [comment]
> Append Async to the end of async method name

This is already being worked on

**Comment by yaira2** [comment]
> Entire project

How do you want to split this up?

**Comment by JaiganeshKumaran** [comment]
> The most likely to happen is that I rename property-backing-field from '_isHidden' to '_IsHidden'
I don't this is the recommended convention.

**Comment by 0x5bfa** [comment]
Please note that this issue's purpose is to force codebase to follow the guideline for great consistency.

> from '_isHidden' to '_IsHidden'

This is on the guideline. Can you open an issue for that?

**Comment by yaira2** [comment]
Merging with #4180
