### ISSUE TITLE
I have to give up on Files.  Maybe in the future I will try again

### ISSUE THREAD

**Issue by meemore** [files-community/Files#12346]
### What feature or improvement do you think would benefit Files?

Make an ON / OFF option when hovering over Drives so you can turn off the tooltips.  How often do you really need to know how much space is left used or the total size?  I have been trying to deal with it.   It pops up above or below the drive you're looking for every time   Can one of the Dev team please tell me if is there a reason this needs to pop up every time? or at least change the delay to 10 seconds or something?  Please.

### Requirements

am I the only one who thinks this is annoying?

### Files Version

71.0

### Windows Version

win11

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #12081. You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
@meemore thank you for your feedback, we're trying to understand more about the use case for turning off these tooltips. Can you add your feedback to #12081?
