### ISSUE TITLE
Very laggy when doing certain operation

### ISSUE THREAD

**Issue by iAlcatrazZ** [files-community/Files#12343]
### Description

So far I've been enjoying the app very much, this is truely best File Explorer alternative I've ever seen. But there are a few things that need serious optimization
- Option to run as admin by default
- Increase performance of the new pane, currently it's very laggy, the feature is so useful but so laggy
- Overal performance optimization

### Steps To Reproduce

1. open 2 folders in 2 panes
2. rename the files in the right pane accordingly to the files in the left pane

### Requirements

perform as smoothly as possible

### Files Version

2.4.70.0

### Windows Version

10.0.22621.1702

### Log file

[debug.log](https://github.com/files-community/Files/files/11464781/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, settings Files to always run as admin as already supported. You can use these steps to enable this option.
1. Right click the Files process in Task Manager
![image](https://github.com/files-community/Files/assets/39923744/ae1a131a-3f4a-4ec1-89a3-c66263052138)
2. Click on "properties"
3. Select the compatibility tab
4. Toggle the option to "run this program as administrator"

**Comment by yaira2** [comment]
Improving performance is a top priority and we're continuing to make progress in this area. You can subscribe to #4180 for further updates.

**Comment by yair100** [comment]
@iAlcatrazZ we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
