### ISSUE TITLE
Quicklook not working with PDFs - works standalone

### ISSUE THREAD

**Issue by ak1dd** [files-community/Files#12355]
### Description

Select a PDF file and hit SPACE to invoke Quicklook.

"Failed to view PDF - Consider reporting to Quicklook author..."

However it works for every other filetype I've tried, works in Windows Explorer and the Files preview pane.

### Steps To Reproduce

Select a PDF file and hit SPACE to invoke Quicklook.

### Requirements

Show the Quickview window when selecting a PDF

### Files Version

2.4.71.0

### Windows Version

Windows 11 Pro 10.0.22621 Build 22621

### Log file

[debug.log](https://github.com/files-community/Files/files/11479230/debug.log)

**Comment by yaira2** [comment]
Thank you the feedback, we don't have any control over Quicklook. Can you please report this to Quicklook?

**Comment by ak1dd** [comment]
I could but it only happens with Files.   It works in Windows Explorer.   The Files preview works.  Only pressing space in Files on a PDF fails.   Pretty sure that isn't a Quicklook bug

**Comment by yaira2** [comment]
> "Failed to view PDF - Consider reporting to Quicklook author..."

It's hard to know but I suggest following the recommendation in the Quicklook app. It could be a limitation in their API or it could be something completely different.
