### ISSUE TITLE
Feature: Update preview pane icon

### ISSUE THREAD

**Issue by ak1dd** [files-community/Files#12356]
### What feature or improvement do you think would benefit Files?

The new toolbar glyphs look great but any that have enclosed areas are black filled.   This looks bad in some color schemes and I imagine will create other issues with themes in the future.

It isn't too noticeable with a dark theme but some glyphs are very noticeable.   See attached screenshot.  The top part is Files, the bottom is Windows Explorer
![Screenshot 2023-05-15 160540](https://github.com/files-community/Files/assets/38289720/a12bb79b-0846-48ce-b713-bb5845032ae9)

### Requirements

Update the preview pane icon to have better contrast when selected.

### Files Version

2.4.71.0

### Windows Version

Windows 11 Pro 10.0.22621 Build 22621

### Comments

Not a huge deal but could add a bit of polish.

**Comment by ak1dd** [comment]
Attached the wrong screenshot.  This one hopefully shows it better.  

![Screenshot 2023-05-15 162325](https://github.com/files-community/Files/assets/38289720/a8a5e412-452d-430f-b5b5-b03b407ae0c0)

**Comment by yaira2** [comment]
It seems to me the main issue is the preview pane.

**Comment by yaira2** [comment]
@ak1dd thank you for reporting this issue, the issue with the preview pane icon will be fixed in the upcoming v2.5 release.
