### ISSUE TITLE
Feature: remove WinuiEx dependency (when possible)

### ISSUE THREAD

**Issue by Jay-o-Way** [files-community/Files#12358]
### What feature or improvement do you think would benefit Files?

Mica is now (easily) available in the latest WASDK.

### Requirements

Pretty UI? :)

### Files Version

2.4.71

### Windows Version

Windows 11

### Comments

https://learn.microsoft.com/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.media.micabackdrop?view=windows-app-sdk-1.3

```xaml
<Window x:Class="MyApp.MainWindow">

    <Window.SystemBackdrop>
        <MicaBackdrop MicaKind="BaseAlt"/>
    </Window.SystemBackdrop>

</Window>
```

I've heard there were issues with v1.3.0, so you might want to go up to 1.3.1

**Comment by yaira2** [comment]
I'm not following this feature request, can you clarify what you're looking for?

**Comment by 0x5bfa** [comment]
We are using [Mica Alt](https://learn.microsoft.com/en-us/windows/apps/design/style/mica) by using an external library named [WinUIEx](https://github.com/dotMorten/WinUIEx). We recognize Microsoft has finally released [that API](https://learn.microsoft.com/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.media.micabackdrop?view=windows-app-sdk-1.3) but still we need to use WinUIEx for some reasons such as setting min width/height and making titlebar collapse.

https://github.com/files-community/Files/blob/571b8978ad711bd03ff03836fec54e0a8b4933de/src/Files.App/MainWindow.xaml.cs#L32-L50

**Comment by 0x5bfa** [comment]
If it is the issue, can you rename the title to 'Feature: Remove WinUIEx reference'?

**Comment by Jay-o-Way** [comment]
Have a look at related pr https://github.com/microsoft/PowerToys/pull/25936

**Comment by yaira2** [comment]
Thank you for your feedback, removing dependencies is a goal for many projects including Files. In this case we're still using WinUIEx to make it easier to implement certain features but we'll definitely remove it once it's no longer required.

**Comment by yaira2** [comment]
This change has been completed! A big thank you to @0x5bfa and everyone else who contributed to this effort.
