### ISSUE TITLE
Feature Request: Replace Folder Icons in Sidebar for a Windows Explorer-like Experience

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12351]
### What feature or improvement do you think would benefit Files?

Hello, I was wondering if it would be possible to replace the current folder icons in the sidebar with the icons listed below, creating a similar experience to Windows Explorer while keeping the icons on the home page as they are.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

Version : 2.4.81

### Windows Version

Windows 11 22H2 22621.1702

### Comments

<img width="75" alt="Capture d'écran 2023-05-13 221046" src="https://github.com/files-community/Files/assets/128183422/384334fe-5968-407c-9fae-0c9be304038f">
<img width="75" alt="Capture d'écran 2023-05-13 221052" src="https://github.com/files-community/Files/assets/128183422/02d99d76-59d4-4db6-aee5-ee9774838aff">
<img width="84" alt="Capture d'écran 2023-05-13 221101" src="https://github.com/files-community/Files/assets/128183422/ee08b446-1112-416c-950a-1d30685c5934">
<img width="111" alt="Capture d'écran 2023-05-13 221106" src="https://github.com/files-community/Files/assets/128183422/3dab3edf-96d4-40ca-b5bd-7727cbe40107">
<img width="70" alt="Capture d'écran 2023-05-13 221112" src="https://github.com/files-community/Files/assets/128183422/dce86b7b-51c6-4cee-8aca-563e381ec2f6">

**Comment by Josh65-2201** [comment]
You can pin the folders from your user folder to favorite's, then change the folder icons in properties. Not all of them may work since Files request a higher resolution one.

**Comment by Lukiluc29** [comment]
> You can pin the folders from your user folder to favorite's, then change the folder icons in properties. Not all of them may work since Files request a higher resolution one.

Yes, I understand. Basically, I'm suggesting an update where instead of using folder icons for the favorites (such as Desktop, Downloads, Music, Pictures, and Videos), we use the icons from Windows File Explorer, as shown in the images I provided earlier.

**Comment by yaira2** [comment]
We're already using the icons from File Explorer, the reason they look a little different is because we use the higher resolution version in Files.

**Comment by Lukiluc29** [comment]
> We're already using the icons from File Explorer, the reason they look a little different is because we use the higher resolution version in Files.

But it is not possible to change them to have a better appearance, even if the quality will be lower, because I prefer the icons of the Windows Explorer favorites bar.

**Comment by Lukiluc29** [comment]
@yaira2 I apologize if I didn't express myself clearly on this subject, but what I meant was that I would like the icons to be like those of OneDrive. Allow me to explain: the OneDrive icon is displayed in the Windows Explorer sidebar, and when it's shown in the Quick Access menu, it appears as a file. I would like the same format for icons representing desktop, downloads, documents, images, music, and videos.
<img width="146" alt="Capture d'écran 2023-05-17 174727" src="https://github.com/files-community/Files/assets/128183422/5cec189d-c5b7-4917-93b3-9f45fba4ec55">
<img width="175" alt="Capture d'écran 2023-05-17 174707" src="https://github.com/files-community/Files/assets/128183422/d10a6fbb-0d7d-4c10-8146-bfc3510af62d">

**Comment by yaira2** [comment]
The icon depends on the size we request, we request a higher resolution version for the quick access because it's a little bigger.

**Comment by Lukiluc29** [comment]
> The icon depends on the size we request, we request a higher resolution version for the quick access widget because it's a little bigger.

And you can't request the same size as the OneDrive icon in the sidebar to have the same logos as those in the Windows sidebar and keep the same size for those in the quick access.
