### ISSUE TITLE
Home: removing a recent file from the list fails and opens instead File Locksmith from MS Powertoys

### ISSUE THREAD

**Issue by carlosvsilva** [files-community/Files#12354]
### Description

When I have a irrelevant recent file in the Home of Files and I right click on it and select remove this item, instead of removing, File Locksmith from Microsoft opens instead ?!

### Steps To Reproduce

1. right click on recent file in Home
2. click remove this item
3. file locksmith opens and scans for locks of this file
4. file remains in the recent list

### Requirements

- remove the specified file from Files recent list

### Files Version

2.4.70.0

### Windows Version

10.0.22621.1702

### Log file

[debug.log](https://github.com/files-community/Files/files/11472202/debug.log)

**Comment by yaira2** [comment]
Thank you for the report, this issue should be resolved in v2.4.71.
