### ISSUE TITLE
Viewing a PDF with QuickLook *ONLY* fails using Files

### ISSUE THREAD

**Issue by ak1dd** [files-community/Files#12357]
### Description

Sorry I wrote a bug report previously and it was closed with the statement "we have not control over QL - not our bug".

I'm pretty sure this is a Files issue.

QL works with every filetype I have tried in Files when pushing space *except* PDFs.   The same files viewed the same way in Windows Explorer work fine.

I won't repost a report regardless of this report's disposition but I'm pretty confident this isn't a QL bug.  Love Files a lot.

### Steps To Reproduce

Using Files.  Find a PDF in the filelist.  Hit space.   Fails.  Every other filetype works.
Using Explorer.  Find a PDF in the filelist.  Hit space.  Works.

### Requirements

just try it.

### Files Version

2.4.71.0

### Windows Version

Windows 11 Pro 10.0.22621 Build 22621

### Log file

[debug.log](https://github.com/files-community/Files/files/11479451/debug.log)

**Comment by yaira2** [comment]
@ak1dd I apologize if you felt we closed the other issue too quickly, the way the Quicklook integration works in Files is a bit different than the way it works in File Explorer. When you press the spacebar in Files, we use Quicklooks API to pass the file information to their app for them to preview it. All the processing happens on their side and as far as I know, there isn't anything different we can do.

This isn't about placing blame on either app, however, we feel that Quicklook is in better position to debug this as they have a better understanding of their code.

**Comment by Jay-o-Way** [comment]
I have absolutely no in-side knowledge of this code, so I must make sure to make zero conclusions, but it reminds me of an issue in PowerToys. There, the PT Run module passes a calculation with numbers to a Mages engine. A non-integer number is passed and, somewhere down the line, the fractional part has all leading zeros trimmed, resulting in bad output. Say, `5.4*9.0018` will be treaded as `5.4*9.18`
Just saying that even something as simple as "passing on" might have a small, unexpected oversight.

**Comment by Jay-o-Way** [comment]
@ak1dd where do I get this QuickLook? I wanna try this.

**Comment by yaira2** [comment]
It's available on the Microsoft Store.
