### ISSUE TITLE
Rename FILES

### ISSUE THREAD

**Issue by lvsunz3748** [files-community/Files#12350]
### What feature or improvement do you think would benefit Files?

I suggest you rename FILES to make the name of your app more distinctive. With a search on Files or FILES for various reasons the search finds tons of apps and other things that have nothing to do with your presently named app. I think all of your current and prospective users would greatly appreciate the convenience of a name change. Thank you. 

### Requirements

This suggestion will substantially minimize search time, avoid confusion re other apps not associated with your app, maximize user convenience.

### Files Version

2.4.44

### Windows Version

Windows 10, 64 bit

**Comment by yaira2** [comment]
Thank you for your feedback, the generic term is actually very good for SEO and it's working fine for us so we don't have any plans to change it.
