### ISSUE TITLE
Feature: Use gray and white grid in ColorPickerButton to indicate transparency

### ISSUE THREAD

**Issue by Poker-sang** [files-community/Files#12369]
### What feature or improvement do you think would benefit Files?

Now it's hard to tell if the background color is completely transparent or the same gray as the background. Maybe we can use transparent grid(alpha grid? I don't know what it's called) to show what color it really is.
Now:
![Now](https://github.com/files-community/Files/assets/62325494/e34c4692-f084-4765-a8a0-aef47150f942)
Expected:
![Expected](https://github.com/files-community/Files/assets/62325494/44cb74f8-0b92-4d65-b54d-c5c9c5724f59)

Maybe we can use PathIcon

### Requirements

- Add a Grid as the background of Border

- Maybe we can use PathIcon: "M0 6 L0 0 L6 0 L6 6 L12 6 L12 0 L18 0 L18 6 L12 6 L12 12 L18 12 L18 6 L24 6 L24 12 L18 12 L18 18 L24 18 L24 24 L6 24 L6 18 L0 18 L0 12 L6 12 L6 18 L12 18 L12 24 L18 24 L18 18 L12 18 L12 12 L6 12 L6 6 Z"

### Files Version

2.4.82.0

### Windows Version

Windows 11 22H2 23440.1000

**Comment by yaira2** [comment]
This is a good idea, do you want to work on it?

**Comment by Poker-sang** [comment]
Yes
