### ISSUE TITLE
Translation: wording/translation of "window" and "pane" to Dutch is...difficult

### ISSUE THREAD

**Issue by Jay-o-Way** [files-community/Files#12364]
### Description

In **Settings** > **General** > **Context menu**, there are four options. Two of them are in English and two are in Dutch. Number 2 = "Show option to open folders in a new window" and number 3 = "Toon optie om mappen in nieuw venster te openen". Considering the translation, the words _window_ and _venster_ are basically **identical**. The significant difference is between "window" and "pane", but in Dutch, the second word/meaning is close to the first.

![image](https://github.com/files-community/Files/assets/65828559/4c98ea12-3280-4c7d-88e5-fa23dff6c34a)

Comparing to Windows Explorer: the words "detailvenster" and "voorbeeldvenster" are used (for details en preview, respectively)
![image](https://github.com/files-community/Files/assets/65828559/be476921-393c-42c4-bf2c-3195ada995d1)

### Steps To Reproduce

Not a real bug

### Requirements

Translation that reflects the different meanings, to be unambiguous. The actual menu entry uses "**deelvenster**", which is correct. For example: https://www.interglot.com/dictionary/en/nl/search?q=pane

### Files Version

2.4.71

### Windows Version

Windows 11

### Log file

[debug.log](https://github.com/files-community/Files/files/11486840/debug.log)

**Comment by Jay-o-Way** [comment]
If you guys need more help with translating to Dutch, I could do that :)

**Comment by ferrariofilippo** [comment]
At the moment 76% of the app is translated to Dutch. 
If you want to help, here's the link: https://crowdin.com/project/files-app

**Comment by Jay-o-Way** [comment]
Also noticed that the word "new" pane might not be 100% accurate, it implies that everything that will be opened in a new pane, will be shown in a pane. But (from what I see) it all opens in one and the same pane?

**Comment by Jay-o-Way** [comment]
Yep. But I understand if that is unrelated to the translation stuff

**Comment by ferrariofilippo** [comment]
> Yep. But I understand if that is unrelated to the translation stuff

The fact is that you can only open two panes, but there's an open feature request to improve that number.
I think we should leave the translation as is

**Comment by Jay-o-Way** [comment]
@yair100 (imo) translation issues are very different from actual (functionality) bugs. Would you rather create a issue form or link to Crowdin's repo?
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser:~:text=If%20you%20prefer%20to%20receive%20certain%20reports%20outside%20of%20GitHub%2C%20you%20can%20direct%20people%20to%20external%20sites%20with%20contact_links.

My suggestion would be to include (something like) the following in _config.yml_
```yml
  - name: Translation issues
    url: https://crowdin.com/project/files-app
    about: Please send in translation improvements here.
```

**Comment by yair100** [comment]
> @yair100 (imo) translation issues are very different from actual (functionality) bugs. Would you rather create a issue form or link to Crowdin's repo? https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser:~:text=If%20you%20prefer%20to%20receive%20certain%20reports%20outside%20of%20GitHub%2C%20you%20can%20direct%20people%20to%20external%20sites%20with%20contact_links.
> 
> My suggestion would be to include (something like) the following in _config.yml_
> 
> ```yaml
>   - name: Translation issues
>     url: https://crowdin.com/project/files-app
>     about: Please send in translation improvements here.
> ```

A link would be nice, I didn't know you could do that.

**Comment by Jay-o-Way** [comment]
Is that something you want to do yourself or want somebody to make a pr..?

**Comment by yaira2** [comment]
@Jay-o-Way would you be interested in opening a PR?
