### ISSUE TITLE
Bug: Issue with Missing Column Icon and English Text in View Modes Menu

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12368]
### Description

I have encountered an issue when right-clicking in an empty area, where the context menu appears, and I attempt to modify the view mode. The column icon does not appear, and next to the view mode names, it shows the text in English, even though my file explorer is set to French, and everything is correctly translated to French in Crowdin.

### Steps To Reproduce

1. Go to any directory
2. Right-click to display the context menu
3. Navigate to "View Mode"

### Requirements

Identify the cause of the missing column icon and incorrect language display in the view modes menu.

### Files Version

Version : 2.4.82.0

### Windows Version

Windows 11 22H2 22621.1702

### Log file

![Capture d'écran 2023-05-16 195148](https://github.com/files-community/Files/assets/128183422/912aad09-6df5-4f30-8a57-d30269c9ee94)

**Comment by yaira2** [comment]
Thank you for the report, we're in the process of updating many of the icons throughout the app. Unfortunately, the new format doesn't work in submenus. It'll look less strange once we update the rest of the layout icons.

**Comment by Lukiluc29** [comment]
> Thank you for the report, we're in the process of updating many of the icons throughout the app. Unfortunately, the new format doesn't work in submenus but it'll look less strange once we update the rest of the layout icons.

Okay, and for the French translation ?

**Comment by yaira2** [comment]
Translations are done on Crowdin by the community so you can double check or add a comment if this wasn't already fixed.

**Comment by Lukiluc29** [comment]
> Translations are done on Crowdin by the community so you can double check or add a comment if this wasn't already fixed.

The problem is that on Crowdin all the translations have been done for a long time
![Capture d'écran 2023-05-16 204148](https://github.com/files-community/Files/assets/128183422/665d3452-5e93-4778-9b04-678d574096cd)

**Comment by yaira2** [comment]
@QuaintMako can you help with this?

**Comment by QuaintMako** [comment]
> @QuaintMako can you help with this?

Looking into it.

**Comment by QuaintMako** [comment]
I believe it should be fixed with the next Crowdin update.
