### ISSUE TITLE
Bug: RepositionThemeTransition sometimes not playing nicely

### ISSUE THREAD

**Issue by Jay-o-Way** [files-community/Files#12360]
### Description

Headers in Settings do not (always) use animation when moving.

### Steps To Reproduce

- Open the settings.
- Find an expander with more settings below it.
- Click the chevron to expand and collapse the expander.
- _Some_ headers (TextBlocks / apparently not always) will move **instantaneously** upwards or down, when the expander is collapsed. Preceeding the in-between controls, which slide up.

Weird thing is that, after you keep expanding and collapsing a number of times, the headers _will_ follow. 😕

### Requirements

Headers will follow the sliding animation

### Files Version

2.4.71

### Windows Version

Windows 10

### Log file

[debug.log](https://github.com/files-community/Files/files/11482562/debug.log)

**Comment by yaira2** [comment]
Thank you for reporting this issue, it'll be fixed in v2.5.
