### ISSUE TITLE
Bug: Progress bar is overlapping text in ongoing operations 

### ISSUE THREAD

**Issue by BrandonCF** [files-community/Files#12362]
### Description

First line on "Ongoing Tasks" is cramped and nearly illegible.

### Steps To Reproduce

1. Start a Task
2. Check "Ongoing Tasks" in top right corner

### Requirements

- Fix spacing of 1st line of "Ongoing Tasks" so that the text and progress bar aren't on top of one another.

### Files Version

Version 2.4.70.0

### Windows Version

Edition	Windows 11 Home Version	22H2 Installed on	‎5/‎1/‎2023 OS build	22621.1702 Experience	Windows Feature Experience Pack 1000.22641.1000.0

### Log file

[debug.log](https://github.com/files-community/Files/files/11483175/debug.log)

**Comment by yaira2** [comment]
Thank you for the report, can you upload a screenshot of the issue so I have a better idea what you're seeing?

**Comment by BrandonCF** [comment]
![image](https://github.com/files-community/Files/assets/42322943/0a6b526b-b961-4205-82a6-817c5ae937dc)

**Comment by yaira2** [comment]
Does this only happen when extracting an archive?

**Comment by BrandonCF** [comment]
No, any operation, but just the top operation, the 1st one.

**Comment by yaira2** [comment]
@BrandonCF this issue should be resolved in the v2.5 release.

**Comment by BrandonCF** [comment]
Your great! Love your explorer. Beats the hell out of the stock explorer that's in danger with every Windows update!
