### ISSUE TITLE
Bug: Renaming 

### ISSUE THREAD

**Issue by jose-asks** [files-community/Files#12372]
### Description

The two problems are mentioned in the Steps to Reproduce section. The bug happens when in column view of the app. When using a keyboard shortcut or pressing any key the app switches back to the folder or to the file within that folder. This happens both in dual preview pane and single preview pane.  

### Steps To Reproduce

Problem 1: Arrow key
1. Open any folder with files in them.
2.  Rename any file. 
3. Press the left arrow key or right arrow key.

Problem 2: Auto hover not on point
1. With selecting files when hovering over then, turned on, under behavior and on file option of the app's setting. 
2. Select a folder by clicking it.
3. Without clicking any file within the folder, hover the mouse in order to select a single item.
4. Use the shortcut key Fn+F2 to rename the file item.

### Requirements

For the arrow key problem, a fix of not moving back and forth will do.

For the auto hover, a fix of hovering on point is better.

### Files Version

2.4.71.0

### Windows Version

Windows 10 22H2

### Log file

[debug.log](https://github.com/files-community/Files/files/11493553/debug.log)

**Comment by yaira2** [comment]
Thank you for reporting this issue.

**Comment by yaira2** [comment]
@hishitetsu by any chance, did your recent PR fix this as well?

**Comment by hishitetsu** [comment]
The column view had the same renaming issue as the dual pane, so I also fixed it.
But I can't determine if what is being reported here is the same issue.

**Comment by jose-asks** [comment]
I would like to add that the second problem I mentioned was in fact due to pressing a different key when a file item was being selected. 
For example, I selected a folder that I want to rename and after I click the folder or hover over it and I press the ctrl key or F2 key on the keyboard, the behavior of opening the folder appears.
Similarly, this behavior is also connected to the first problem that I mentioned.

**Comment by yaira2** [comment]
@jose-asks thank you for reporting these issues, can you open an issue for "Auto hover not on point" so we can track it separately?

**Comment by jose-asks** [comment]
Sure. Thank you.

**Comment by jose-asks** [comment]
@yaira2 Hello! I check this issue with the updated version, 2.5, and it was addressed. Also, this is an issue related to #12450 which you told me to create.
Thank you.

**Comment by yaira2** [comment]
Thank you
