### ISSUE TITLE
Bug: Duplicate Display Issue with Pinned Directories in the Favorites Bar in the Quick Access Home Page

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12377]
### Description

Hello, I have noticed an issue where any directory I pin to the Favorites bar in the sidebar on the Quick Access Home Page is displayed as a duplicate entry.

### Steps To Reproduce

1. Right-click on a folder
2. Click on "Add to Favorites"

### Requirements

Identify the cause of the duplicate display issue for pinned directories in the Favorites bar.

### Files Version

Version : 2.4.82.0

### Windows Version

Windows 11 22H2 22621.1702

### Log file

<img width="960" alt="Capture d'écran 2023-05-17 095908" src="https://github.com/files-community/Files/assets/128183422/adf313ac-03ca-4b61-b633-1313501701b9">

**Comment by yaira2** [comment]
Thank you reporting this issue.

**Comment by hecksmosis** [comment]
I'll look into this

**Comment by yaira2** [comment]
@Lukiluc29 this issue should be resolved in v2.5.
