### ISSUE TITLE
Bug: Drag and drop images from browser isn't working

### ISSUE THREAD

**Issue by stotka1** [files-community/Files#12378]
### Description

When I try to drag and drop an image from a browser the progress bar shows up and says copy completed but the file doesn't appear in the folder. 

### Steps To Reproduce

1. Open image in browser
2. Drag to files
3. Doesn't show up but has notification that it does.

### Requirements

Have the image saved (Show up) into the desired folder via drag and drop

### Files Version

019801

### Windows Version

Edition	Windows 10 Pro Version	22H2 Installed on	‎28-‎Mar-‎21 OS build	19045.2965 Experience	Windows Feature Experience Pack 1000.19041.1000.0

### Log file

[debug.log](https://github.com/files-community/Files/files/11495613/debug.log)

**Comment by stotka1** [comment]
Sorry, copied the wrong thing. Files version: 2.4.71.0
Refreshing doesn't help

**Comment by yaira2** [comment]
I'm not able to repro this issue with Edge, which browser are you using?

**Comment by stotka1** [comment]
So I just tried a few browsers. My main is Vivaldi (Chromium). Vivaldi and Chrome when dragging into Files does a **Copy** command and doesn't do anything. Firefox does a **Move** command and manages to get an image into Files.
![Files_G9ViXOp0bn](https://github.com/files-community/Files/assets/4647470/25893e85-0653-49d9-a4fb-d181772bae61)

**Comment by gave92** [comment]
Funny, just tried to drag&drop the above screenshot from Vivaldi to Files and it works.

**Comment by yaira2** [comment]
@stotka1 the latest preview build (v2.5.33) includes a potential fix for this issue, can you try the preview and see if it helps? https://files.community/download

**Comment by stotka1** [comment]
Sure, I'm in the middle of moving, so might take a little bit.

**Comment by yaira2** [comment]
Thanks! It appears to be fixed but let us know if it's still an issue on your device and we'll take another look.

**Comment by stotka1** [comment]
Hello. Tested it out. On Chrome and Vivaldi (Chromium) it still doesn't work, on Firefox it works but because it does a Move command and creates a .bmp file. Chrome does a copy command and tries to create a .jpg file and fails. 
I'm not sure why Firefox creates .bmp files.
I have also tested this on 3.0.1.0

**Comment by yaira2** [comment]
@stotka1 is the app still crashing? Can you also upload the updated log file?

**Comment by stotka1** [comment]
The app never crashes. It just won't create the .jpg file when dragging from a browser. 
[debug.log](https://github.com/files-community/Files/files/13278132/debug.log)

**Comment by yaira2** [comment]
> When I try to drag and drop an image from a browser the progress bar shows up and says copy completed but the file doesn't appear in the folder.

**Comment by stotka1** [comment]
Yes, the progress bar shows and says its completed. But the file never appears.

**Comment by Josh65-2201** [comment]
Seems to be the same issue as https://github.com/files-community/Files/issues/13646#issuecomment-1799572242

**Comment by stotka1** [comment]
Yes, its the same from what I see
