### ISSUE TITLE
apps

### ISSUE THREAD

**Issue by sedoy1111** [files-community/Files#12382]
### What feature or improvement do you think would benefit Files?

Hello, I would like to see a transparent theme, as well as the sounds of opening folders. So that it could be turned on and off

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.4.71.0

### Windows Version

10.0.22621.1702

**Comment by Josh65-2201** [comment]
For theming follow the instructions at https://files.community/docs/configuring/custom-themes

**Comment by yaira2** [comment]
@sedoy1111 thank you for your feedback, sounds in apps aren't very common these days, can you share more about your request and why you think Files should be different in this way?
