### ISSUE TITLE
Click items do not have the same item from the  task maneger windows

### ISSUE THREAD

**Issue by crazygod5555** [files-community/Files#12388]
### What feature or improvement do you think would benefit Files?

RAR item:
[https://imgur.com/gBryNHO](url)

No RAR:
[https://imgur.com/V7lQJCh](url)

### Requirements

synchronous the windpws task manager click items or make a way to add the items to Files's items

### Files Version

2.4.71.0

### Windows Version

10.0.22000.856

**Comment by Josh65-2201** [comment]
Thanks for the report. Can you confirm your issue is with WinRAR not showing in Files context menu. 
If so this is an issue with WinRAR using the new Windows 11 system. You can download a version below 6.0 to get it back. Support for the Windows 11 context menu system is being tracked in #8251

**Comment by yaira2** [comment]
@crazygod5555

**Comment by yaira2** [comment]
Thank you for the update

**Comment by crazygod5555** [comment]
> Thank you for the update

But it only works on old version WINRAR(under V6.x)
