### ISSUE TITLE
Feature Request: Rename “Files” into something unique for SEO

### ISSUE THREAD

**Issue by wharjack** [files-community/Files#12385]
### What feature or improvement do you think would benefit Files?

By renaming the Files into something better, it will be good for SEO. Why it's important? It's because when we search something like "How to make files app faster",  search engine result is something irrelevant since the name "Files" is too generic.

### Requirements

- This proposal will accomplish better results for search engine and when Files user had a problem, they will search about that problem and have better search engine results.

### Files Version

Version: v2.4.71

### Windows Version

Edition	Windows 10 Pro Version	21H2 Installed on	‎27/‎08/‎2022 OS build	19044.2965 Experience	Windows Feature Experience Pack 1000.19041.1000.0

### Comments

![image](https://github.com/files-community/Files/assets/52787179/39dae628-1532-4325-acc7-d1a3f9426e7d)

**Comment by Josh65-2201** [comment]
This was addressed with https://github.com/files-community/Files/issues/12350#issuecomment-1546786193

**Comment by yaira2** [comment]
@wharjack have you visited our documentation site https://files.community?

**Comment by wharjack** [comment]
Oh, I'm sorry, this is a duplicate feature request. 
@yaira2 I visited it right now, why?

@yaira2 I clicked #12350, and I saw your comment in there. I see that Files is already good for SEO. 

Anyway, do you have plans on rewriting Files from C, C# and C++ to Rust? I think it will have a good boost to its performance. I really appreciate your hard work in creating Files, and I'm grateful that I can experience a very beautiful file manager, and also its UI is second to none. However, its performance is not that good, there's no day it won't slow down. Thank you so much, guys! I appreciate your responses!

**Comment by yaira2** [comment]
We don't have plans to rewrite in C++ or Rust, our current focus is refactoring the existing code to improve reliability and performance. C# can be very performant (and memory efficient) if you have good code and use the right APIs and together with the help of the open-source community, we believe we're on track to making Files one of the fastest file managers available on Windows.

**Comment by wharjack** [comment]
Good luck guys! Looking forward to it. 🙏
