### ISSUE TITLE
Recycle Bin

### ISSUE THREAD

**Issue by lico9182** [files-community/Files#12383]
### What feature or improvement do you think would benefit Files?

Hi Developer, i don't know if i'm just missing a setting in Files, or if it that the Recycle Bin can't be accessed via the app, great file manager software thanks for creating it, best regards L 

### Requirements

To add the Recycle Bin for Windows 11 os

### Files Version

2.4.71.0

### Windows Version

Windows 11 Pro 22H2 22621.1702

### Comments

To have access to the Windows 11 Recycle Bin inside Files application, if it's there already where do i go to see it please? thanks L

**Comment by Josh65-2201** [comment]
Can you make a new issue using bug report template on this showing the error message you get

**Comment by lico9182** [comment]
Hi Josh65, thanks i've done so just now, regards Livio
