### ISSUE TITLE
Bug: Items aren't vertically centers in column layout (with compact spacing)

### ISSUE THREAD

**Issue by redhotideas** [files-community/Files#12398]
### Description

Look at the image below, the names and icons are offset towards the bottom

![image](https://github.com/files-community/Files/assets/118266752/cda600a1-4389-46f7-a7f2-da95ad3eacc8)

### Steps To Reproduce

1 - set column view
1 - set minimalised view

### Requirements

- fix Vertically center or increase the space below 

### Files Version

2.4.82.0

### Windows Version

10.0.22621.1702

### Log file

[debug.log](https://github.com/files-community/Files/files/11514271/debug.log)

**Comment by sash9696** [comment]
Hi @yaira2 I would like to work on this issue. Would you please assign it to me?

**Comment by redhotideas** [comment]
@sash9696 if possible reduce the space between the elements and the separator line

**Comment by yaira2** [comment]
@sash9696 how is this going?

**Comment by yaira2** [comment]
@redhotideas this issue is resolved in our development branch and will be included in the next release.
