### ISSUE TITLE
Bug: Disable drag & drop as admin to prevent crash

### ISSUE THREAD

**Issue by hoang3402** [files-community/Files#12390]
### Description

everytime i try to drag a file with the file running with admin rights it crashes

### Steps To Reproduce

1. open Files as admin
2. drag and drop a file
3. app crashes

### Requirements

- disable drag & drop as admin to prevent crash

### Files Version

2.4.70.0

### Windows Version

Microsoft Windows 11 Pro Version	10.0.22621 Build 22621

### Log file

[debug.log](https://github.com/files-community/Files/files/11508888/debug.log)

**Comment by yaira2** [comment]
We should probably disable drag and drop to prevent a crash.

**Comment by yaira2** [comment]
@hoang3402 thank you for your patience, the next version of Files will include a fix for this issue. In addition to this fix, it'll also include support for admin file operations without having to elevate Files.
