### ISSUE TITLE
More information on file Details without having to click on Properties

### ISSUE THREAD

**Issue by clarwilliams** [files-community/Files#12407]
### What feature or improvement do you think would benefit Files?

When opening a list of files the layout should include more properties. For example, for audio and video files, a "Length" property would be very helpful, without having to click on Properties for each file. This is currently unavailable in the app. 

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

Version 2.4.71

### Windows Version

Windows 11 Pro 64-bit

**Comment by Josh65-2201** [comment]
Thanks for the feedback. Can you clarify that you are talking about the details view columns.

**Comment by clarwilliams** [comment]
Yes, that’s correct.Sent from my phone.On May 20, 2023, at 3:05 AM, Josh65-2201 ***@***.***> wrote:﻿
Thanks for the feedback. Can you clarify that you are talking about the details view columns.

**Comment by Josh65-2201** [comment]
Merging with #8366. You can check there or click subscribe in the right sidebar for updates.
