### ISSUE TITLE
Key bind - assign Color Tag

### ISSUE THREAD

**Issue by Transmissiontoday** [files-community/Files#12406]
### What feature or improvement do you think would benefit Files?

As the title suggest it would be nice to have the ability to assign/unassign faster color tags with keybinds , 

i.e. 'CTRL / SHIFT' or 'CTRL + SHIFT' + 4 = Green 

- shortcut assign in control panel would be ideal to give the user freedom as of what key binds they use to prevent the override of existing shortcuts and maximize efficiency.

### Requirements

To further improve tag functionality, developers can consider the following:

1. Faster tag assignment: Introducing keybinds or keyboard shortcuts, such as 'CTRL/SHIFT' or 'CTRL+SHIFT' + a number, can enable users to quickly assign or unassign color tags. This streamlines the process and improves efficiency.

2. Customizable keybinds: Developers can provide a control panel or settings interface where users can customize their own keybinds for assigning color tags. This flexibility allows users to choose key combinations that work best for them while preventing conflicts with existing shortcuts.

3. Bulk tag assignment: Enabling the ability to assign color tags to multiple folders or files simultaneously can save time and effort. Users could select multiple items and assign a color tag to all of them at once, improving the overall organization process.

By implementing these improvements, users can experience a more efficient and streamlined workflow when organizing their folders and files with color tags. It provides greater control and customization options while enhancing productivity.

### Files Version

PRE

### Windows Version

windows 10

**Comment by ferrariofilippo** [comment]
We're discussing this feature at #11352
