### ISSUE TITLE
When the software opens a file for a long time, there will be no response

### ISSUE THREAD

**Issue by 454342265** [files-community/Files#12410]
### Description

When the software opens a file for a long time, there will be no response

### Steps To Reproduce

1.Open software
2.remain open for a long time
3.Click on the interface
4.The system reports that the software is not responding

### Requirements

No longer crashes after opening the software for a long time

### Files Version

2.4.71.0

### Windows Version

Windows 11 Pro Insider Preview 22H2 25314.1010

### Log file

[debug.log](https://github.com/files-community/Files/files/11522617/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Can you give the following information.
- Are you using Files or just staying on the Home page

**Comment by yaira2** [comment]
@454342265
