### ISSUE TITLE
Bug: Items from multiple columns are selected

### ISSUE THREAD

**Issue by redhotideas** [files-community/Files#12429]
### Description

If I have an item selected individually (first image) and then I make a multiple selection in the same folder, the previously selected item will result in a double selection (second image)

![image](https://github.com/files-community/Files/assets/118266752/90ae406f-ad0a-4d1e-bf52-1f2a2ee3f984)

![image](https://github.com/files-community/Files/assets/118266752/08f7f4ba-bafe-4466-9e12-4af22684ace4)

### Steps To Reproduce

1. Select a single item
2. make a multiple selection in the same folder

1. Select a single item
2. Hover over folder items
3. Previously selected single item will have double selection

### Requirements
- Close open folder if selecting multiple items in the parent folder

### Files Version

2.4.82.0

### Windows Version

10.0.22621.1702

### Log file

[debug.log](https://github.com/files-community/Files/files/11543352/debug.log)

**Comment by yaira2** [comment]
Do you have the hover to selection option enbled?

**Comment by redhotideas** [comment]
occurs equally with the option on and off
