### ISSUE TITLE
Feature: Add a link to Crowdin on the About page of the settings dialog

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#12426]
### What feature or improvement do you think would benefit Files?

Adding a link to Crowdin on the About page helps users to improve the translation if they think it is not correct.

### Requirements

Add a link to Crowdin on the About page of the settings dialog.

### Files Version

2.4.83.0

### Windows Version

Windows 11 22H2

**Comment by yaira2** [comment]
@hishitetsu thank for opening this issue. I added a link in #12433
