### ISSUE TITLE
Ability to widen columns in column view

### ISSUE THREAD

**Issue by redhotideas** [files-community/Files#12422]
### What feature or improvement do you think would benefit Files?

In many cases it is necessary to read the full filenames. You should have the ability to widen columns (keeping the current minimum size unchanged)

![image](https://github.com/files-community/Files/assets/118266752/d6812084-86c9-4783-a0f6-07cad7f8bd28)

### Requirements

- set column view
- position the mouse on the dividing line
- widen to the right

### Files Version

2.4.82.0

### Windows Version

10.0.22621.1702

**Comment by ferrariofilippo** [comment]
Duplicate #6534

**Comment by yaira2** [comment]
@redhotideas thank you for your feedback, can you confirm if this is the same as #6534?

**Comment by redhotideas** [comment]
yes! I commented there

**Comment by yaira2** [comment]
Thank you
