### ISSUE TITLE
Feature: Support choosing the dual pane orientation

### ISSUE THREAD

**Issue by rafaelsouzams** [files-community/Files#12427]
### What feature or improvement do you think would benefit Files?

The current and vertical panels (one next to the other) are very cool, but they have a problem of poor use of the screen on large screens, especially when using the column layout!
It could still exist, but it would be great to have another option for horizontal panels (one on top of the other), this would be perfect for being able to visualize a whole hierarchy of columns on both sides!

[actual problem]
![image](https://github.com/files-community/Files/assets/25182245/b8b510aa-a76a-4b1b-9f8c-2f973e185c3f)

[concept solution]
![image](https://github.com/files-community/Files/assets/25182245/c95a0fa1-409b-44d5-a2c6-4660990d2e86)

### Requirements

- keep current dashboards for those who prefer
- add a new option to view panels one above the other instead of next to each other

### Files Version

2.4.71.0

### Windows Version

Windows 11 22h2 22621.1702

**Comment by JunoArc** [comment]
Bumping this too

**Comment by yaira2** [comment]
This will be possible once #11955 is complete.

**Comment by yaira2** [comment]
Concept image
![image](https://github.com/files-community/Files/assets/39923744/9507b1d8-a799-4239-af7f-79807a02d423)
