### ISSUE TITLE
Bug: Opening file issue 

### ISSUE THREAD

**Issue by DissMercy** [files-community/Files#12428]
### Description

Impossible to open a photo from the files app

### Steps To Reproduce

1. Go on files app
2. Try to open a png image

### Requirements

- eg. Fix crash that occurs when...

### Files Version

Version : 2.4.71.0

### Windows Version

Windows 11 22H2

### Log file

[debug.log](https://github.com/files-community/Files/files/11540888/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Can you see if this is an issue in the preview version. https://files.community/download

**Comment by yaira2** [comment]
@DissMercy can you also share a screen recording so I can make sure I'm trying the same repro steps?

**Comment by yaira2** [comment]
This appears to be resolved in v2.5.
