### ISSUE TITLE
Bug: Restart dialog does not display without scrolling

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#12421]
### Description

If the user changes the language setting, a dialog will appear prompting the user to restart. However, this dialog appears at the bottom of the settings page, so if the window size is small, the user will have to scroll to see it.

https://github.com/files-community/Files/assets/66369541/8ef42069-57dc-4958-818f-85e492988a00

### Steps To Reproduce

1. Reduce the window size.
2. Change the language setting.
3. The dialog will not display without scrolling.

### Requirements

The dialog should be fully visible without scrolling regardless of the window size.

### Files Version

2.4.71.0

### Windows Version

Windows 11 22H2

### Log file

n/a

**Comment by yaira2** [comment]
Thank you for reporting this issue.

**Comment by yaira2** [comment]
I'll work on this
