### ISSUE TITLE
scrollbars always visible

### ISSUE THREAD

**Issue by redhotideas** [files-community/Files#12424]
### What feature or improvement do you think would benefit Files?

For those who use the graphics tablet and do not always have the mouse wheel under their finger, going to select the scroll bars is complicated and you have to wait for them to open every time. Repeated over time is a waste of time.
From the settings it would be necessary to have a switch to have the possibility of keeping them always visible

![image](https://github.com/files-community/Files/assets/118266752/eaa0992c-dbd0-45db-882b-34eeb11294cf)

### Requirements

- go to setting
- scroll bar auto hidden OFF

### Files Version

2.4.82.0

### Windows Version

10.0.22621.1702

**Comment by redhotideas** [comment]
@Josh65-2201 correct, now they are always visible

**Comment by yaira2** [comment]
@Josh65-2201 does that completely hide them or just auto collapses them?

**Comment by Josh65-2201** [comment]
With the option on it shows the scrollbar as if you were hovering over them always. If off it will have the smaller collapsed state. There's no hide option in Windows as far as I know.
