### ISSUE TITLE
Feature: Add support for PowerToys Peek

### ISSUE THREAD

**Issue by cartifanwlr** [files-community/Files#12432]
### What feature or improvement do you think would benefit Files?

PowerToys added the Peek feature in 0.70. It's essentially macOS QuickLook, allowing you to preview files with Ctrl+Space. This does not work in Files, and I'd like to see this feature supported in Files.

### Requirements

- PowerToys Peek should work inside Files

### Files Version

2.4.71.0

### Windows Version

Windows 11 version 22H2 build 22624.1755

**Comment by yaira2** [comment]
Thank you for your feedback, Files already supports QuickLook so it shouldn't be too hard if PowerToys has an api for this.

**Comment by hishitetsu** [comment]
I don't know if Peek has an API, but we need to think about which hotkey to assign if we implement this. We already assign Ctrl+Space to toggle selection. Should we add an option to select a tool to preview items?

**Comment by yaira2** [comment]
> Should we add an option to select a tool to preview items

This is probably the best solution, this way we can have a single action for preview items.

**Comment by yaira2** [comment]
I opened an issue on the PowerToys repo to start the discussion on creating an api for third party file managers https://github.com/microsoft/PowerToys/issues/2

**Comment by yaira2** [comment]
Thank you for your feedback. We're closing this issue because PowerToys doesn't have an API for this, but we'll be happy to reevaluate if this changes in the future.

**Comment by yair100** [comment]
This feature will be included in the next update. Please see #17954.
