### ISSUE TITLE
Feature: Editable size of preview file content of preview pane

### ISSUE THREAD

**Issue by warquys** [files-community/Files#12435]
### What feature or improvement do you think would benefit Files?

Be able to expand the window to the bottom of the preview file content of the preview pan.
In my case it would be to preview code files or log files quickly without having to open them.

### Requirements

- Select a file.
- Open the preview pane (if not already open).
- Select the bottom of the window preview file content.
- Drag and slide down or up to adjust size.

### Files Version

2.4.71.0

### Windows Version

10.0.22621.1702

### Comments

This would be done by selecting the bottom of the window (in red on the picture).
![image](https://github.com/files-community/Files/assets/64769541/be53da26-9d79-4bcf-ad66-5c1b9e46784d)

Window of preview file content size would be kept between files (not reset each unselected file and slecte and no custome size for each file).

**Comment by yaira2** [comment]
Did you try hiding the details (by right clicking the preview)?

**Comment by warquys** [comment]
No, I don't know about this possibility but I don't think I need to resize in as much. Just enough to still see the fields on the date of creation and others

**Comment by warquys** [comment]
Also the option menu does not allow it in the context of a text file. The context menu of a fill allow only to copy all the text and the context menu for other file allow to open in big the preview file content.

**Comment by warquys** [comment]
the preview section is more than enough! Thank you.
