### ISSUE TITLE
Switch to allow permanent full path availability

### ISSUE THREAD

**Issue by Xemanth** [files-community/Files#1243]
The address bar needs a switch to allow full path to be always available. Now it needs clicking to be visible.

**Comment by yaichenbaum** [comment]
@Xemanth The full path should show by default in v0.20, can you confirm if this is what you had in mind?

**Comment by yaichenbaum** [comment]
Thanks again for your feedback.

_Since we didn't hear from you on this topic for 7+ days, we'll assume everything is worked out and close this feedback item. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this._
