### ISSUE TITLE
Possibility to edit the values ​​in the preview pane

### ISSUE THREAD

**Issue by warquys** [files-community/Files#12434]
### Description

It is possible to modify the values ​​in the preview panel. When I talk about value, it's values ​​like "count lines" of a txt file, or the creation date of a folder or file. It does it with all the inromations of the prevew pane.
This might look normal, but when the values ​​are changed, no change is made. Example, I change the access path cella does not change the access path of the sectioner element. I think the basic behavior is that there is no possibility to change the values ​​and that these fields are read only.

### Steps To Reproduce

1. Select a file
2. Open the prevew pane (if not open)
3. Click on one of the fields
4. Edit the value

### Requirements

values ​​should not be editable

### Files Version

2.4.71.0

### Windows Version

10.0.22621.1702

### Log file

[debug.log](https://github.com/files-community/Files/files/11547247/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, can you confirm if this is the same as #6128?

**Comment by warquys** [comment]
I had seen this request before, but no. The bug is that it is possible to edit the metadata of the files but that has no impact and it would seem more logical to me that it is not possible.
the logic to set it on read only is : I do not see why it would be possible to change the number of elements of a folder by using thepreview pane.

**Comment by yaira2** [comment]
Can you clarify the difference between this and #6128? It seems that both are asking for the ability to edit properties/metadata from the details pane.

**Comment by warquys** [comment]
The problems is that it is possible to edit these fields when it should not have the possibility to edit them.

**Comment by yaira2** [comment]
I can see the confusion over this but so far it hasn't proven to be a real issue, so I don't see any harm in leaving it like this until we add a save button.

**Comment by warquys** [comment]
I think some fields should not be editable like the number of elements in a file

**Comment by yaira2** [comment]
> I think some fields should not be editable like the number of elements in a file

This will be addressed once we have support for saving 👍
