### ISSUE TITLE
Bug: "Show preview only" option menu does not appear for txt files

### ISSUE THREAD

**Issue by warquys** [files-community/Files#12437]
### Description

When you right click in the preview file content window, we don't see the "Show preview only" for txt file. But a menu that only displays Select All (text).

### Steps To Reproduce

1. Select a txt file.
2. Open the preview pane (if not already open).
3. Right clique on the preview content file

### Requirements

Have default menu options in menus for text elements.

### Files Version

2.4.71.0

### Windows Version

10.0.22621.1702

### Log file

[debug.log](https://github.com/files-community/Files/files/11547520/debug.log)

**Comment by yaira2** [comment]
Thank you for the feedback, this will be addressed in v2.5.
