### ISSUE TITLE
启动页问题反馈

### ISSUE THREAD

**Issue by AisinGioroKiIoi** [files-community/Files#12449]
### Description

设置为下次从本次离开的位置启动。但它好像每次启动都是首页。偶尔才会从上次离开的地方启动。望优化，ᠪᠠᠨᡳᡥᠠ（巴尼哈/谢谢）

### Steps To Reproduce

-

### Requirements

-

### Files Version

2.4.83.0

### Windows Version

10.0.25370.1

### Log file

[debug.log](https://github.com/files-community/Files/files/11559796/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report. 
- Can you fill out the steps to reproduce. including how you are closing and opening Files.

**Comment by AisinGioroKiIoi** [comment]
您好，或许我觉得这两个过程比较通用，没有什么特别的，便没有填写。

启动软件：电脑开机后，从任务栏或开始菜单，点击该APP，启动。

关闭软件：其一，点击右上角的“X”关闭。其一，电脑关机，APP连同系统关闭。

**Comment by Josh65-2201** [comment]
Sorry for the delayed response. Can you confirm it the same issue as #12624

**Comment by AisinGioroKiIoi** [comment]
您好，不太一样。我这边关机前无论是否开启着软件，重启之后都是打开了首页。ᠪᠠᠨᡳᡥᠠ（巴尼哈/谢谢）

**Comment by Josh65-2201** [comment]
Can you try
1. Opening Files
2. Go to a location
3. Close Files via the X button
4. Open Files and see if it at the location you were before

**Comment by AisinGioroKiIoi** [comment]
> 

您好，這樣操作是可以回到之前的位置的。在關閉計算機或者重啟計算機的時候才沒有按照預定設置回到之前的位置。ᠪᠠᠨᡳᡥᠠ（巴尼哈/谢谢）

**Comment by Josh65-2201** [comment]
Based on that it seem it is the same issue as #12624. You can check there or click subscribe in the right sidebar for updates.
