### ISSUE TITLE
Bug: Multiselect with ctrl doesn't close unfocused columns

### ISSUE THREAD

**Issue by redhotideas** [files-community/Files#12456]
### Description

In column view, if you select multiple folders together by holding down ctrl or shift in the last column, the contents of the first folder disappear correctly, select Img.2.
If I make a further selection by repeatedly pressing ctrl or shift, the content of the first selected column Img.1 will appear and disappear in the last column Img.3

Img.1
![image](https://github.com/files-community/Files/assets/118266752/34de82e5-c32e-4dc6-bdc6-d6196ff36904)

Img.2
![image](https://github.com/files-community/Files/assets/118266752/cd1aabca-8f5e-480a-a407-de83e4463b9c)

Img.3
![image](https://github.com/files-community/Files/assets/118266752/098c8168-049d-44e4-951a-64b63b10ca73)

### Steps To Reproduce

- select a folder
- make a multiple selection with ctrl or shift pressed
- repeat this operation several times by pressing and releasing ctrl or shift to select other additional folders

### Requirements

- the last column must always remain empty

### Files Version

2.4.82.0

### Windows Version

10.0.22621.1702

### Log file

[debug.log](https://github.com/files-community/Files/files/11563379/debug.log)

**Comment by yaira2** [comment]
This does seem like #12429, in both cases selecting a second folder should close the last column.

**Comment by yaira2** [comment]
This issue will be resolved in the upcoming v2.5 release.
