### ISSUE TITLE
Auto hover not on point

### ISSUE THREAD

**Issue by jose-asks** [files-community/Files#12450]
### Description

When trying to select a folder or using the auto hover feature in the setting, in this case I want to rename the folder with a shortcut key Fn+F2 or instead pressing any of the three, Caps, Shift, Ctrl key, a behavior of opening the files or hiding the files within the folder appears. Additionally, it happens only in folders and not the files within a folder.

### Steps To Reproduce

1. Manual selection or using the auto hover feature in the setting, select a folder.
2. press the Fn+F2 key to rename the folder.

### Requirements

It would be better if we can fix the issue. Thank you.

### Files Version

2.4.71.0

### Windows Version

Windows 10 22H2

### Log file

[debug.log](https://github.com/files-community/Files/files/11560951/debug.log)

**Comment by yaira2** [comment]
What happens after pressing F2?

**Comment by jose-asks** [comment]
The files within that folder appears and if we press Fn+F2 again, it will hide the files within that folder.

**Comment by jose-asks** [comment]
It does not have to be the Fn+F2 key, for example when a folder was selected and you toogle the Ctrl or Shift or Caps key, the behavior appears.

**Comment by Josh65-2201** [comment]
Can you see if this is an issue in 2.5.1.0

**Comment by jose-asks** [comment]
Hello, Yes. It was not an issue anymore with the new update. I have also posted a similar report, #12372, you may check it. 
I am really thankful to the Team for addressing the issue.
