### ISSUE TITLE
Feature: Support Run as Different User for shortcut files

### ISSUE THREAD

**Issue by lisbonjoker** [files-community/Files#12457]
### What feature or improvement do you think would benefit Files?

There's an option missing from the option menu, usually under the "Run as Administrator" which is "Run as Different User".  

### Requirements

- This proposal will accomplish me being allowed to run apps under a different user inside the same computer or in the current ActiveDirectory.

### Files Version

2.4.71.0

### Windows Version

10.0.19044.2965

**Comment by yaira2** [comment]
Does the option show if you hold down the shift key (when opening the context menu)?

**Comment by lisbonjoker** [comment]
> Does the option show if you hold down the shift key (when opening the context menu)?

Nope, only one it shows up is really just the "Run as Administrator" option.

**Comment by yaira2** [comment]
The option is showing for me, can you send a screenshot of the context menu? I'm curious if any other options are missing.
![image](https://github.com/files-community/Files/assets/39923744/5fe34241-d194-472b-83f0-c93cf4ccd22e)

**Comment by lisbonjoker** [comment]
![image](https://github.com/files-community/Files/assets/80425961/5e0b4dda-2d2c-48e3-8318-925c89842cdf)
That doesn't show up for me, but it does show up in the Window's File Manager.

**Comment by Josh65-2201** [comment]
Are you selecting an executable? What's the file extension?

**Comment by yaira2** [comment]
@lisbonjoker

**Comment by lisbonjoker** [comment]
> Are you selecting an executable? What's the file extension?

It's a shortcut of an executable.

**Comment by yaira2** [comment]
@lisbonjoker this feature is implemented in the dev branch and will be included in the next release.

**Comment by lisbonjoker** [comment]
> @lisbonjoker this feature is implemented in the dev branch and will be included in the next release.

Thank you very much :)!
