### ISSUE TITLE
Unable to see Nextcloud folder

### ISSUE THREAD

**Issue by Xemanth** [files-community/Files#1245]
**Describe the bug**
I have Nextcloud folder inside my user profile but Files UWP doesn't show it at all. 
With File Explorer I can see it...
Really weird stuff!
Expected behaviour is to show the folder :)

**Screenshots**
![image](https://user-images.githubusercontent.com/6332266/85827434-fad93780-b78e-11ea-9b86-da75e882e0e8.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 21H1 20150.1000
 - App version: [v0.10.2.0]

**Comment by Jaiganeshkumaran** [comment]
It could be just a shortcut to another location. Files UWP hides all shortcuts since we don't support them yet. If you want to access your Nextcloud folder from Files UWP, copy the location that the shortcut is pointing to and paste it on Files UWP's path box.

**Comment by Xemanth** [comment]
> It could be just a shortcut to another location. Files UWP hides all shortcuts since we don't support them yet. If you want to access your Nextcloud folder from Files UWP, copy the location that the shortcut is pointing to and paste it on Files UWP's path box.

It's not shortcut... I can go to the Nextcloud path if I just type it. But currently, it's not possible to pin it to sidebar like this or at least I haven't found a way yet :D 
![image](https://user-images.githubusercontent.com/6332266/85829984-77224980-b794-11ea-9fda-b77e20f2123e.png)

**Comment by Jaiganeshkumaran** [comment]
@Xemanth You can right-click on the empty space and click 'Pin to sidebar'.

**Comment by Xemanth** [comment]
> @Xemanth You can right-click on the empty space and click 'Pin to sidebar'.
Which empty area? Can you pinpoint me with more specific information :( I tried to click right click everywhere but can't see Pin button  :(

**Comment by Jaiganeshkumaran** [comment]
By empty I mean space were no file is shown. You need the latest version to see the pin option.
![திரைப்பிடிப்பு (6)](https://user-images.githubusercontent.com/45227503/85830700-a348c500-b7aa-11ea-9bcb-149f241a33e7.png)

**Comment by Xemanth** [comment]
> shown. You need the latest version to see the pin option.
I have version 0.10.2.0 from Microsoft Store. Isn't it the latest?
I don't have that Pin directory to sidebar -option there where you have it.
![image](https://user-images.githubusercontent.com/6332266/85832124-2a407200-b798-11ea-970d-0a32a2fd19e8.png)

Anywayz, the original problem is still there that I can't see the Nextcloud folder inside user profile folders listing :(

**Comment by Jaiganeshkumaran** [comment]
I downloaded from the Microsoft Store and I already have v0.10.7.

**Comment by yaichenbaum** [comment]
@Xemanth The latest preview v0.10.7 includes the option @Jaiganeshkumaran mentioned. It should roll out to all users in a few weeks.

**Comment by duke7553** [comment]
@Jaiganeshkumaran We also prevent visibility of items marked with FileAttributes.System

**Comment by duke7553** [comment]
@Xemanth To test this, run the PowerShell command:
`Get-ItemProperty C:\Path\To\Item |  Format-list -Property * -Force`

and reply back with all the output of the command.

**Comment by Xemanth** [comment]
> @Xemanth To test this, run the PowerShell command:
> `Get-ItemProperty C:\Path\To\Item |  Format-list -Property * -Force`
> 
> and reply back with all the output of the command.

I will test this later today. How can I dl from Store preview builds for testing? Easier to test things when using latest build.

**Comment by yaichenbaum** [comment]
@Xemanth You can sign up for the preview builds [here](https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAO__Qw_X6FUM0pUSzMxNUlCWE1FVENKVlVNVUNTRVpOUS4u).

**Comment by PartyDonut** [comment]
It looks like the bug occurs when the folders icon is changed? Nextcloud assigns a custom nextcloud icon to every synced folder, after reverting the icon back to the default folder icon the folders show up in files-uwp and still sync with nextcloud. 

This is with the Nextcloud 2.7 beta-client, not sure if this works for older clients.

**Comment by duke7553** [comment]
@PartyDonut This is valuable information. Thank you for following up!

**Comment by Xemanth** [comment]
> @Xemanth To test this, run the PowerShell command:
> `Get-ItemProperty C:\Path\To\Item | Format-list -Property * -Force`
> 
> and reply back with all the output of the command.

Sorry, forgot to answer. Here's output:
PS C:\Users\Xemanth> Get-ItemProperty C:\Users\Xemanth | Format-list -Property * -Force


PSPath            : Microsoft.PowerShell.Core\FileSystem::C:\Users\Xemanth
PSParentPath      : Microsoft.PowerShell.Core\FileSystem::C:\Users
PSChildName       : Xemanth
PSDrive           : C
PSProvider        : Microsoft.PowerShell.Core\FileSystem
Mode              : d-----
BaseName          : Xemanth
Target            : {}
LinkType          :
Name              : Xemanth
FullName          : C:\Users\Xemanth
Parent            : Users
Exists            : True
Root              : C:\
Extension         :
CreationTime      : 6.7.2020 22.09.31
CreationTimeUtc   : 6.7.2020 19.09.31
LastAccessTime    : 14.7.2020 22.11.46
LastAccessTimeUtc : 14.7.2020 19.11.46
LastWriteTime     : 8.7.2020 14.09.33
LastWriteTimeUtc  : 8.7.2020 11.09.33
Attributes        : Directory



PS C:\Users\Xemanth>

**Comment by Xemanth** [comment]
> like the bug occurs when the folders icon is changed? Nextcloud assigns a custom nextcloud icon to every synced folder, after reverting the icon back to the default folder icon the folders show up in files-uwp and still syncs with nextcloud.
> 
> This is with the Nextcloud 2.7 beta-client, not sure if this works for older clients.

Where can I modify these icons ? Now I can't test can I see Nextcloud folder as Files-UWP crashes when I go to my user profile =)
This behavior started after updating to Files-UWP beta program and now I'm using version 0.11.1.0.
I have installed Nextcloud 2.6.5 client.

**Comment by duke7553** [comment]
@Xemanth Thanks. Can you run it for: C:\Users\Xemanth\Nextcloud

**Comment by Xemanth** [comment]
> @Xemanth Thanks. Can you run it for: C:\Users\Xemanth\Nextcloud

PS C:\Users\Xemanth> Get-ItemProperty C:\Users\Xemanth\Nextcloud | Format-list -Property * -Force


PSPath            : Microsoft.PowerShell.Core\FileSystem::C:\Users\Xemanth\Nextcloud
PSParentPath      : Microsoft.PowerShell.Core\FileSystem::C:\Users\Xemanth
PSChildName       : Nextcloud
PSDrive           : C
PSProvider        : Microsoft.PowerShell.Core\FileSystem
Mode              : d---s-
BaseName          : Nextcloud
Target            : {}
LinkType          :
Name              : Nextcloud
FullName          : C:\Users\Xemanth\Nextcloud
Parent            : Xemanth
Exists            : True
Root              : C:\
Extension         :
CreationTime      : 13.5.2020 18.10.05
CreationTimeUtc   : 13.5.2020 15.10.05
LastAccessTime    : 14.7.2020 22.23.12
LastAccessTimeUtc : 14.7.2020 19.23.12
LastWriteTime     : 14.7.2020 22.23.11
LastWriteTimeUtc  : 14.7.2020 19.23.11
Attributes        : System, Directory



PS C:\Users\Xemanth>

**Comment by duke7553** [comment]
@Xemanth Thanks! 

This confirms the item is invisible because it is marked with the SYSTEM attribute. Since you can navigate to it just fine, we should look into displaying SYSTEM items as well. Files currently excludes these from the query.

**Comment by PartyDonut** [comment]
> 
> Where can I modify these icons ? Now I can't test can I see Nextcloud folder as Files-UWP crashes when I go to my user profile =)
> This behavior started after updating to Files-UWP beta program and now I'm using version 0.11.1.0.
> I have installed Nextcloud 2.6.5 client.

In the standard windows file explorer select the right-click the nextcloud folder -> Properties -> Customize -> Change Icon, then just select the default windows folder icon.

Or you can run this on the folder using powershell
`Get-Item C:\PathToFolder -Force | Where-Object { $_.PSIsContainer -and $_.Attributes -match "System" } | ForEach-Object { $_.Attributes = "" }`

Both options remove the nextcloud icon, syncing icons still work in standard file explorer.

Not sure why nextcloud is using the system Attributes, so proceed with caution i suppose?

**Comment by yaichenbaum** [comment]
@Xemanth Nextcloud will be pinned by default in the next update.

**Comment by pawal** [comment]
With the default download from Microsoft Store, Nextcloud is invisible for me too.

**Comment by Meldrak** [comment]
Same issue for me

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5097.
