### ISSUE TITLE
Feature: Option to disable selection indicator

### ISSUE THREAD

**Issue by redhotideas** [files-community/Files#12455]
### What feature or improvement do you think would benefit Files?

In the settings add an option to disable the selection bar, sometimes it is confusing or annoying when there are labels of the same color

![image](https://github.com/files-community/Files/assets/118266752/695da0c2-203f-4b9b-9533-d9adc905c5cb)

### Requirements

- go to settings
- folders
- disable selection bar

### Files Version

2.4.82.0

### Windows Version

10.0.22621.1702

### Comments

it would be nice to also select gray intensity selection

**Comment by yaira2** [comment]
The selection indicator uses the system accent color which is adjustable in Windows settings.

**Comment by redhotideas** [comment]
yes I know, but I would like to have the possibility to remove it not to change the color

**Comment by yaira2** [comment]
I can see where you're coming from, but this is a pretty niche scenario. There are exceptions but our general rule for adding a setting is that it'll be used by at least 3% of users. We can always reconsider if interest increases but, in the meantime, I suggest using a distinct color for the tags or accent color.

**Comment by redhotideas** [comment]
@yaira2 I understand, so I ask if it's a problem if I report many things, requests or bugs.
I use files very hard every day, I would like to actively contribute, but I don't have the skills on the programming side. I can only report design and workflow issues...
Thanks anyway for your work.
