### ISSUE TITLE
Bug: Column layout items remain selected in "Continue where you left off" mode

### ISSUE THREAD

**Issue by redhotideas** [files-community/Files#12454]
### Description

In the "Continue where you left off" mode when I reopen files I am correctly in the window from which I left, but the folders of the original path remain selected even if I select another one

![image](https://github.com/files-community/Files/assets/118266752/e1dc4978-9808-4a0d-b73d-a9eeccca3516)

### Steps To Reproduce

- select "Continue  where you left off" mode
- go to a subfolder in columnar mode
- close files
- reopen files
- select a folder other than the path where file opened

### Requirements

reset the original folder selection when I select another one in the same folder

### Files Version

2.4.82.0

### Windows Version

10.0.22621.1702

### Log file

[debug.log](https://github.com/files-community/Files/files/11563173/debug.log)

**Comment by yaira2** [comment]
Thank you for reporting this issue

**Comment by yaira2** [comment]
This is fixed in the `main` branch.
