### ISSUE TITLE
An unnamed folder crashes "Files"

### ISSUE THREAD

**Issue by LeoBOUDEAUdev** [files-community/Files#12468]
### Description

![Screenshot 2023-05-27 131851](https://github.com/files-community/Files/assets/98223456/ad786ee7-13aa-4b25-87d8-ca93f0fbc25c)
In favorite folders and quick access two folders crash the software when I interact with them. After verification these files are connected with non-existent hard drives. These disks have as letters: O:/ and N:/ . Please fix this bug.

### Steps To Reproduce

1. If we try to open these folders or if we right click on them.

### Requirements

I will be able to interact with them without crashing

### Files Version

2.4.71.0

### Windows Version

10.0.19045.2965

### Log file

[debug.log](https://github.com/files-community/Files/files/11581698/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report.

**Comment by yaira2** [comment]
@LeoBOUDEAUdev thank you for reporting this issue, a fix will be included in the upcoming v2.5 release.
