### ISSUE TITLE
List view

### ISSUE THREAD

**Issue by dpbueno** [files-community/Files#12461]
### What feature or improvement do you think would benefit Files?

I miss the list view, there are indeed other views but they are all large

### Requirements

List view

### Files Version

2.4.71.0

### Windows Version

Windows 10

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #2509. You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
@dpbueno thank you for your patience, I'm excited to share that a List View layout will be included in the next release.
