### ISSUE TITLE
app no permite eliminar carpetas ancladas y en menu no permite ordenar las carpetas

### ISSUE THREAD

**Issue by kruciare** [files-community/Files#12462]
### Description

Al eliminar una carpeta anclada en el panel el programa se reinicia, y al reorganizar las carpetas ancladas en el menú de acceso rápido no lo permite 

### Steps To Reproduce

.

### Requirements

- eg. Fix crash that occurs when...

### Files Version

la ultima 

### Windows Version

windows 11

### Log file

.

**Comment by Josh65-2201** [comment]
Thanks for the report. Can you give the following information.
- Can you please upload (Do not copy and paste content) the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.
- Can you please add the Files version, latest/last doesn't exist.
- Can you fill out the steps to reproduce.

**Comment by Josh65-2201** [comment]
@kruciare Can you answer the above questions please.
