### ISSUE TITLE
HTML file preview breaks the program

### ISSUE THREAD

**Issue by nimbus2332** [files-community/Files#12467]
### Description

Hi, I have Windows 10 21H1.

I have installed your program by default and enabled the CTRL+P viewport. When I hover the cursor over an HTML file weighing more than 1,5,10,50 megabytes, the program crashes and restarts again and again. I also generate files with content in various languages, and the program breaks with any content if the file weighs more than 500 KB, especially often breaks if the language is Chinese.

I also have another problem: if I install the default program and run it, the window is not created in full screen. After canceling the "default", the program opens again to the entire monitor.

***

How to make the left panel as in the usual Windows Explorer? That is, I want to return the "This PC" section.

***

The dark theme is annoying and does not match the colors of the dark theme of Windows Explorer. How do I set a completely black color for the interface? Now it's kind of gray with a tilt to black, it's unpleasant for the eyes

### Steps To Reproduce

1. Click to HTML file 1
2. 
[html.zip](https://github.com/files-community/Files/files/11581397/html.zip)

### Requirements

- eg. Fix crash that occurs when...

### Files Version

Stable on MS Store

### Windows Version

Win 10 Pro 21H2 19044.2965

### Log file

[LocalState.zip](https://github.com/files-community/Files/files/11581389/LocalState.zip)

**Comment by nimbus2332** [comment]
https://github.com/files-community/Files/issues/12256 

I have a clean Windows without any firewall modifications, except for ADGuard.

**Comment by Josh65-2201** [comment]
Thanks for the report. In future make separate issues for different feedback.
- HTML preview issues is already known in #12256. You can check there or click subscribe in the right sidebar for updates.
- Anything in the This PC section can be accessed from the Home section in Files. What reason would you want it?
- Default Window sizing is done by Windows and Files can not control it.
- You can change the background in Files settings > Appearance > background. Clicking on the drop down of the header 
![image](https://github.com/files-community/Files/assets/26977075/5bad69d0-5b2b-4eef-bc75-b3128122d762)

**Comment by yaira2** [comment]
@nimbus2332 Is this still an issue in the preview version? https://files.community/download/
