### ISSUE TITLE
Progress bar misplaced in Ongoing Tasks window

### ISSUE THREAD

**Issue by jh961202** [files-community/Files#12463]
### Description

The "Ongoing Tasks" popup window shows the ongoing filesystem operations with progress bars to give a more visual experience.
However, it's layout has messed up recently for some reason, just like the screenshots below.

![image](https://github.com/files-community/Files/assets/8479301/88eb6119-67ab-4749-9ed6-678521ce6ddd)
![image](https://github.com/files-community/Files/assets/8479301/d580660d-af74-435a-9db9-d43e84426d88)

### Steps To Reproduce

1. Move/copy/delete files, or do anything that will be listed in the "Ongoing Tasks".
2. See the error.

### Requirements

The progress bar shouldn't mixed with, but shuld be over or at the bottom of the description text.

### Files Version

2.4.71.0

### Windows Version

10.0.22621.1702

### Log file

[debug.log](https://github.com/files-community/Files/files/11577059/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, This has been fixed in preview build 2.4.83 and will be released to stable as 2.5
