### ISSUE TITLE
error alerts on notifications bar

### ISSUE THREAD

**Issue by 98Ulamog** [files-community/Files#12464]
### Description

idk it keeps alerting when i rename files

### Steps To Reproduce

try to rename a file in any directory

### Requirements

it just spams notifications

### Files Version

2.4.40.0 

### Windows Version

windows 11

### Log file

[debug.log](https://github.com/files-community/Files/files/11579962/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, you are on an outdated version. Please update to 2.4.71. or later https://files.community/download
