### ISSUE TITLE
Feature: Quit to taskbar / Impoved opening speed

### ISSUE THREAD

**Issue by dotargz** [files-community/Files#12465]
### What feature or improvement do you think would benefit Files?

It would be nice if the app could minimize itself or similar so that when reopened it takes less time to run and possibly remove the ever visible layout shift when opening the app(?)

### Requirements

- This proposal will create an option to close the app to the user but keep it running
- This proposal will allow for the app to open a new tab when re-opening the app.
- This proposal will (hopefully) do this in a way that opening the app after startup/first launch is much faster

### Files Version

2.4.83.0

### Windows Version

Windows 11 10.0.22621.1702

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #11279. You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
@dotargz This feature is included in the latest preview build (https://files.community/download) and will be included in the v3 release.
