### ISSUE TITLE
Add ARM/ARM64 Builds to the Release Pipeline

### ISSUE THREAD

**Issue by MattPeterUK** [files-community/Files#1247]
Please improve the speed of the overall app, I'm using a Surface Pro X and Files UWP  as my main device and file explorer. It can be very sluggish on the Microsoft SQ1 from time to time. 

But this is THE file explorer Windows 10 needs and deserves, I highly appreciate your work. The UI and UX are insanely good, expect for the slowness from time to time. 

I haven't noticed any app crashing so far. 

Thanks again.

**Comment by Jaiganeshkumaran** [comment]
This is due to the fact that the Microsoft Store version of Files UWP only offers x86 and x64 builds of the app and not ARM.

**Comment by MattPeterUK** [comment]
> This is due to the fact that the Microsoft Store version of Files UWP only offers x86 and x64 builds of the app and not ARM.

You're right, but the MS Store website says that there is an ARM version. Very weird indeed. 

![UWP](https://user-images.githubusercontent.com/65657775/85845074-f79c7680-b7a3-11ea-8462-ffa2adac717b.jpg)

**Comment by Jaiganeshkumaran** [comment]
I think the Microsoft Store originally offered an ARM build however it got pulled for no apparent reason.

**Comment by yaichenbaum** [comment]
In order to have an ARM build, it would need to be added to the pipeline.

**Comment by soumyamahunt** [comment]
Since .Net5 now supports ARM64, migrating the desktop extension project to .Net5 would be good idea.

**Comment by Jaiganeshkumaran** [comment]
.NET 5 is currently only a preview so we should wait until it becomes stables.

**Comment by yaichenbaum** [comment]
We will now start offering ARM64 builds on the Microsoft Store.
