### ISSUE TITLE
希望在新版本对图像UI做出改变

### ISSUE THREAD

**Issue by abbcccbba** [files-community/Files#12473]
### What feature or improvement do you think would benefit Files?

1.在驱动器图标的左边添加一个类似于Windows自带资源管理器的箭头标志，以允许在未打开该文件夹的情况下预览该文件夹的文件目录。
2.在对文件做出更改时，进度会显示在窗口左上方的类似于圆形的图标当中。这种做法并不醒目，有时我压根就没有察觉到操作已经开始了。
3.文件资源显示异常，我的磁盘只有100G，却显示一个200G的文件夹？6...
4.另外，搜索功能也有问题。在./下载文件夹内搜索“docker”时，并没有搜索到，这是因为它位于./下载/程序目录里，希望添加可以搜索文件夹以及以下搜索子文件夹的功能。
5.该问题可能由权限不足导致。在删除一些特定的文件时，总是会报错失败。而用系统自带的资源管理器删除时，提示需要管理员权限，点击确定时即可删除。

### Requirements

1.希望添加在驱动器图标的左边添加一个类似于Windows自带资源管理器的箭头标志。
2.在对文件做出更改时（如：复制、粘贴），做出醒目的提醒。可以直接将显示进度的窗口嵌入到左侧的文件预览框内。
3.对于前面提到过的搜索异常以及文件大小显示异常的问题做出修复。

### Files Version

Files 2.4.71.0

### Windows Version

Microsoft Windows 11 Pro 22H2 22621.1702

**Comment by Josh65-2201** [comment]
Thanks for the feedback. Please make a new issue for each different issue/feedback you have in the future.

For 1 - Merging with #1928. You can check there or click subscribe in the right sidebar for updates.
For 2 - Merging with #7225. You can check there or click subscribe in the right sidebar for updates.
For 3 - Please make a bug report following the issue template
For 5 - Merging with #10422. You can check there or click subscribe in the right sidebar for updates.
