### ISSUE TITLE
Bug: Issue with Column Layout Persistence in Application Settings

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12472]
### Description

I have noticed an issue regarding the persistence of column settings in the application. When I enable or disable columns, such as the "Tag column" or others, in the "Details layout column" menu, and then close the settings, the changes are saved successfully. However, the layout remains the same despite the modifications made in the settings, even after refreshing or closing and reopening the application.

### Steps To Reproduce

1. Open Files
2. Go to the settings
3. Navigate to "Folder" section

### Requirements

Identify the cause of the column layout persistence issue.

### Files Version

Version : 2.4.83.0

### Windows Version

Windows 11 22H2 22621.1778

### Log file

.

**Comment by Josh65-2201** [comment]
Can you please upload (Do not copy and paste content) the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.

**Comment by Lukiluc29** [comment]
[debug.log](https://github.com/files-community/Files/files/11584779/debug.log)

**Comment by yaira2** [comment]
The options in settings are just the default and they won't override existing preferences. If you want to reset the existing preferences, you can toggle the option to sync preferences across folders on & off. Let me know if this helps.

**Comment by Lukiluc29** [comment]
Ah OK. Thank you, because I did not really understand what this option corresponded to but now I know.
