### ISSUE TITLE
Bug: Installing a font causes Files to freeze

### ISSUE THREAD

**Issue by mafra99** [files-community/Files#12474]
### Description

Installing one or multiple fonts via the NavigationToolbar or the right-click menu causes Files to freeze.

### Steps To Reproduce

1. Select one or multiple font files (*.ttf)
2. Install the font using the Install button of the NavigationToolbar or the install option of the right click menu (Show more options > Install)
3. See that Files freezes and does not respond while the font is being installed

### Requirements

- Files should not freeze

### Files Version

2.4.83.0

### Windows Version

10.0.25375.1

### Log file

[debug.log](https://github.com/files-community/Files/files/12138569/debug.log)

**Comment by yaira2** [comment]
@mafra99 thank you for reporting this issue.

**Comment by yaira2** [comment]
@mafra99 is this still an issue in v2.5.20? If it is, please upload the log file so we can investigate further.

**Comment by yaira2** [comment]
A PR would be great, thanks!
