### ISSUE TITLE
"Detach Tabs" -  toggle option

### ISSUE THREAD

**Issue by vovapaukoff** [files-community/Files#12483]
### What feature or improvement do you think would benefit Files?

 Option to enable or disable tabs detach functionality.
Make sliding tabs visually represented as sliding on one axis like in chrome

chrome example:
![Record_2023_05_29_13_14_23_11](https://github.com/files-community/Files/assets/115099551/56b2edd2-ca93-4b3c-b125-12c2a346e987)

### Requirements

This option will:
- save a lot of pain to users that using tablets like Wacom, pen input are very sensitive and can cause a lot of dragging mistakes.
- make faster tabs arrangement by dragging them on one axis
- make it possible to choose you own working style (everything in one place like browser or separated in different windows)

### Files Version

2.4.71.0

### Windows Version

Windows 11 Pro Version	22H2 / build 22621.1778 / Feature Experience Pack 1000.22642.1000.0

**Comment by yaira2** [comment]
@vovapaukoff thank you for your feedback, this seems a little similar to #11081, can you confirm if fixing that will solve your issue?

**Comment by vovapaukoff** [comment]
Hi Yair.
In case of detach toggle, yes, it can do it.

**Comment by yaira2** [comment]
We don't have an ETA for fixing it but it's on our todo list. You can subscribe to #11081 to be updated when the fix is ready.
