### ISSUE TITLE
Feature: Add "Install" toolbar button for certificate files

### ISSUE THREAD

**Issue by manfromarce** [files-community/Files#12482]
### What feature or improvement do you think would benefit Files?

Windows Explorer has a context menu entry for installing certificates (supports .cer, .crt, .pfx and .der as far as I know) which is loaded as a shell entry in Files. Since there is a toolbar button to quickly install fonts or inf files, having it for certificates would be nice too.

### Requirements

- This proposal will add an Install button to the toolbar for .cer, .crt, .pfx and .der files (similar to .inf and font files)

### Files Version

2.4.71.0

### Windows Version

Windows 11 22H2 10.0.22631.1825

**Comment by yaira2** [comment]
@manfromarce thank you for your feedback.

**Comment by br1trs** [comment]
Hi! Can I work on this feature?

**Comment by yaira2** [comment]
Sure

**Comment by yaira2** [comment]
The install button should be implemented using the new actions format in the code base.

**Comment by br1trs** [comment]
ok

**Comment by yaira2** [comment]
@manfromarce this feature will be included in the upcoming v2.5 release.
