### ISSUE TITLE
Auto sorting files into folders/tags by file type 

### ISSUE THREAD

**Issue by MIfoodie** [files-community/Files#12486]
### What feature or improvement do you think would benefit Files?

The whole point of Files is to improve the default file manager. Part of improving the default file manager should be improving how people can organize their files. 

A helpful feature would be to auto-tag files with a specific file extension (.stl, .png, etc) with a set tag. This would remove the time-consuming task of manually tagging your files.

To make this more useful, you should also be able to automatically sort files into folders by tags. For example, if you had a tag that was "Pictures" and was set to tag everything with a .png and .jpeg extension, you could have a folder that included all of the files tagged with "Pictures" to make finding files much easier.

### Requirements

- This proposal will accomplish sorting files and file management issues by automatically doing most of the work

### Files Version

2.4.71.0

### Windows Version

Windows 10 Education 22H2 19045.2965

**Comment by Josh65-2201** [comment]
Thanks for the feedback, finding all tagged files/folders can already be done by searching them in the search bar or using the tags section on the sidebar or home page.

**Comment by yaira2** [comment]
@MIfoodie this seems similar to #11992.
