### ISSUE TITLE
Feature: Re-add tooltip to details layout

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#12481]
### What feature or improvement do you think would benefit Files?

#11962 removed tooltip from details layout. However, it is more convenient to have the full file name displayed on hover when the file name does not fit in the column. So I think tooltip is necessary even for details layout.
![image](https://github.com/files-community/Files/assets/66369541/c307d659-398b-4d98-99df-64078d58c946)

### Requirements

Re-add tooltip to details layout (if posible, only display when text is cut off)

### Files Version

2.4.71.0

### Windows Version

Windows 11 22H2

**Comment by yaira2** [comment]
Would it be better if we showed the tooltip, but only when text was cut off?
