### ISSUE TITLE
Uninstall Files

### ISSUE THREAD

**Issue by Lieuallen** [files-community/Files#12494]
### What feature or improvement do you think would benefit Files?

Although impressive, Files just isn't for me (I wish I'd known that before I selected to make it my default file manager!). I'd like to uninstall it, but it's not listed under the list of programs I can uninstall. Will the installer have an uninstall option?

### Requirements

- This proposal will accomplish removing Files as the default file manager (perhaps this is already done by unselecting this option?)
- This proposal will accomplish uninstalling of Files

### Files Version

Version 2.0.36.0

### Windows Version

Windows 11 22H2 22621.1413

**Comment by yaira2** [comment]
We're sorry to hear you're uninstalling Files, that being said, there are two way you can uninstall Files (or any other app)
1. Right click the app in the start menu and click on "uninstall"
2. From the Windows Settings app

**Comment by Josh65-2201** [comment]
It seems you are on a very outdated version of Files I suggest you update and give that ago https://files.community/download

**Comment by yaira2** [comment]
I missed that point, we've made some significant improvements over the last few months both with stability and features.
