### ISSUE TITLE
Bug: The theme option sometimes resets to "light"

### ISSUE THREAD

**Issue by MarcAnt01** [files-community/Files#12504]
### Description

Periodically I notice that Files launches in light theme even though I have set the system option setting. I go to settings and it is light

### Steps To Reproduce

No precise repro steps, I'm afraid it might be involved with updates

### Requirements

Fix setting being "forgotten". 

### Files Version

2.4.84.0

### Windows Version

10.0.22631.1825

### Log file

[debug.log](https://github.com/files-community/Files/files/11610872/debug.log)

**Comment by ferrariofilippo** [comment]
![image](https://github.com/files-community/Files/assets/102259289/93932582-774b-4280-9cf9-d59612a242d9)

@yaira2 the issue seems to be caused by lines 62 & 63

**Comment by yaira2** [comment]
Good catch, I'm not sure how we can avoid this without this issue being resolved https://github.com/microsoft/microsoft-ui-xaml/issues/4651.

**Comment by ferrariofilippo** [comment]
We should somehow lock the `settings` file so that it cannot be accessed by other processes while this method is being executed

**Comment by Lukiluc29** [comment]
I also had this bug recently when installing the latest Files stable update.

**Comment by hishitetsu** [comment]
@ferrariofilippo thanks for the good info. I was able to reproduce it and I think I can fix it.

**Comment by Josh65-2201** [comment]
2.5.14 is outdated try update and then see if you can reproduce again

**Comment by MarcAnt01** [comment]
> 2.5.14 is outdated try update and then see if you can reproduce again

Even if outdated, it's still newer than the version where the given fix was released, so this needs to be addressed.

Whatever, I'll let you know if this happens again on newer versions

**Comment by yaira2** [comment]
@MarcAnt01 the fix hasn't been released yet, it's still in the preview version.

**Comment by yaira2** [comment]
Can you check with the latest preview build? https://files.community/download/preview

**Comment by MarcAnt01** [comment]
> @MarcAnt01 the fix hasn't been released yet, it's still in the preview version.

Ah, got it. I thought that issues were closed as long as a fix was reaching the preview builds. I'm running the latest build and I will keep you updated
