### ISSUE TITLE
Ctrl + V to paste inside a folder pastes in the main folder

### ISSUE THREAD

**Issue by MarcAnt01** [files-community/Files#12503]
### Description

If I want to paste inside a folder and I paste with ctrl + V after having selected it, nothing happens. Basically the behavior in https://github.com/files-community/Files/issues/6590 show up. If I paste from the context menu instead the behavior is correct.

### Steps To Reproduce

1. Create a folder A with a random file and a subfolder B
2. Copy the file
3. While inside A click on B
4. Ctrl + V

### Requirements

When a folder is selected Ctrl + V pastes inside it

### Files Version

2.4.84.0

### Windows Version

10.0.22631.1825

### Log file

Not needed

**Comment by hishitetsu** [comment]
Thank you for reporting this. This is the same behavior as File Explorer. #6590 is about right-click menus.
Instead, you can use Ctrl+Shift+V to paste items into the selected folder. This shortcut is unique to Files and is not found in File Explorer.

**Comment by MarcAnt01** [comment]
> Thank you for reporting this. This is the same behavior as File Explorer. #6590 is about right-click menus. Instead, you can use Ctrl+Shift+V to paste items into the selected folder. This shortcut is unique to Files and is not found in File Explorer.

I was quite certain before opening the issue that it was consistent with what was done in File explorer, but this is not the case. Anyway, wouldn't it be a better idea to paste directly in the subfolder? What's the point of clicking on a folder and then ctrl + V if not clicking on it?

**Comment by hishitetsu** [comment]
It may confuse users that the behavior of Ctrl+V changes depending on whether an item is selected or not, because users are not necessarily aware of whether an item is selected or not when they press Ctrl+V.

**Comment by MarcAnt01** [comment]
> It may confuse users that the behavior of Ctrl+V changes depending on whether an item is selected or not, because users are not necessarily aware of whether an item is selected or not when they press Ctrl+V.

Honestly I disagree, because between Ctrl + C and Ctrl+ V not a lot of time usually elapses and the action of selecting a folder is usually done on purpose

**Comment by hishitetsu** [comment]
Consider the case where a folder is copied with Ctrl+C and then Ctrl+V is pressed as is. Does the user then expect the copied folder to be pasted into that folder?
For use cases like yours, Files provides the shortcut Ctrl+Shift+V. I think that is sufficient to fulfill your request.
