### ISSUE TITLE
Inconsistent Translation in "Files" App - "Allow" instead of "Autorisé" in Advanced Permissions

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12501]
### Description

I have noticed an inconsistency in the translation within the "Files" app. When accessing the properties and advanced permissions, the term "Allow" is displayed instead of the expected translation "Autorisé." This discrepancy is noticeable, especially considering that it is correctly translated as "Autorisé" on Crowdin.

### Steps To Reproduce

1. Open Files
2. Right-click on a folder
3. Open Properties
4. Go to Security
5. Click on Advanced Permissions

### Requirements

Ensure that the translation for "Allow" is updated to "Autorisé" in the appropriate language files.

### Files Version

Version : 2.4.84.0

### Windows Version

Windows 11 22H2 22621.1778

### Log file

<img width="594" alt="Capture d'écran 2023-05-31 093212" src="https://github.com/files-community/Files/assets/128183422/e20bc039-e668-4774-a951-3692cf2b7ec4">

**Comment by yaira2** [comment]
Thank you for reporting this issue.
