### ISSUE TITLE
Bug: Clear All button Overlaps with Minimize button

### ISSUE THREAD

**Issue by cardin** [files-community/Files#12517]
### Description

Within the Ongoing Tasks pane, there's no way to click on the Clear All button, as its hitbox overlaps with the Minimize button, such that any clicks will instead activate the Minimize button.

![image](https://github.com/files-community/Files/assets/553816/118c681e-eed4-4349-b5dd-e11585be4e2c)

### Steps To Reproduce

Self-explanatory based on above screenshot

### Requirements

- Change the flyout position to "Bottom"

### Files Version

Files 2.4.71.0

### Windows Version

Windows 10.0.19045.3031

### Log file

[debug.log](https://github.com/files-community/Files/files/11620470/debug.log)

**Comment by yaira2** [comment]
Thank you for reporting this issue.

**Comment by yaira2** [comment]
This issue should be resolved in the upcoming v2.5 release.
