### ISSUE TITLE
while moving or copying files, close files app and reopen then progress tab is gone plz fix this

### ISSUE THREAD

**Issue by Mushiness0127** [files-community/Files#12513]
### Description

same as title

### Steps To Reproduce

1. copy or moving files to other directory
2. close files app
3. reopen files app
4. progress bar is disappeared
5. file transfer is still in progress in background without any other progress interface

### Requirements

- eg. Fix crash that occurs when...

### Files Version

Version: 2.4.71.0 / OS Version: 10.0.22621.1702

### Windows Version

Windows 11 22H2 22621.1702

### Log file

N/A

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #8207. You can check there or click subscribe in the right sidebar for updates.
