### ISSUE TITLE
Bug: Changing the mode in the preview pane causes details to display incorrectly

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12511]
### Description

When I'm, for example, on a preview mode of a file and switch to details, no details are displayed. I have to go to another folder and come back to see them.

### Steps To Reproduce

1. Open Files
2. Open the preview pane and switch it to "Preview" mode
3. Go to an element
4. Switch to details mode

### Requirements

Fix the problem of incorrect detail mode display when changing from "Preview" to "Details".

### Files Version

Version : 2.4.84.0

### Windows Version

Windows 11 22H2 22621.1778

### Log file

![Capture d'écran 2023-05-31 203843](https://github.com/files-community/Files/assets/128183422/2d655618-d21c-473b-ab13-ff7a7095a50f)

**Comment by yaira2** [comment]
Thank you for reporting this issue

**Comment by yaira2** [comment]
This issue will be resolved in the upcoming v2.5 release.

**Comment by Lukiluc29** [comment]
Hello, this problem persists in version 2.4.85
<img width="269" alt="Capture d'écran 2023-06-08 075000" src="https://github.com/files-community/Files/assets/128183422/d4a8fd39-2f0b-4eb4-8dbb-150ddf424e89">

**Comment by Lukiluc29** [comment]
@yaira2 Hello, this problem persists in version 2.4.85
<img width="269" alt="Capture d'écran 2023-06-08 075000" src="https://github.com/files-community/Files/assets/128183422/9becb2c6-0149-4fee-ab96-ac38cbaf6763">
