### ISSUE TITLE
Bug: Deleting folder in column layout doesn't close it

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12512]
### Description

I have encountered an issue when deleting a folder in column view. After deleting the folder while it is open, the folder itself gets deleted, but the contents of the deleted folder remain visible.

### Steps To Reproduce

1. Open Files
2. Open the folder to see the contents
3. Delete Open Folder

### Requirements

Ensure that the deletion process removes both the folder and its contents from the view.

### Files Version

Version : 2.4.84.0

### Windows Version

Windows 11 22H2 22621.1778

### Log file

![Capture d'écran 2023-05-31 205106](https://github.com/files-community/Files/assets/128183422/5af97dbc-6d77-4fee-92dd-faa76d395111)

**Comment by yaira2** [comment]
Thank you for reporting this issue.

**Comment by hishitetsu** [comment]
This also happens after a folder is renamed. Even after renaming, the columns of the folder before renaming are still there, and an error occurs when trying to access that item.

**Comment by yaira2** [comment]
This issue will be resolved in the upcoming v2.5 release.
