### ISSUE TITLE
Support of "Peek" Feature from Windows PowerToys

### ISSUE THREAD

**Issue by LinusHe** [files-community/Files#12519]
### What feature or improvement do you think would benefit Files?

Windows PowerToys just implemented a feature called "Peek" (see [here](https://learn.microsoft.com/de-de/windows/powertoys/peek)) which allows to preview a file by pressing a shortcut while the file is selected in the windows explorer. 

It would be great if it's somehow possible to support this also in the Files app.

### Requirements

Assign a customizable keyboard shortcut that activates the "Peek" feature when a file is selected.

### Files Version

2.4.71.0

### Windows Version

Windows 11 Pro 22H2 22621.1702

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #12432. You can check there or click subscribe in the right sidebar for updates.
