### ISSUE TITLE
Bug: Right-clicking at the bottom of the page does not bring up a context menu.

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#12524]
### Description

Right-clicking at the bottom of the page does not bring up a context menu. However, the context menu seems to be generated internally, and I have to click somewhere else to perform other operations.
![image](https://github.com/files-community/Files/assets/66369541/8e7ab39c-1163-4e58-80fb-a5f9c0ae8179)

### Steps To Reproduce

1. Right-click at the bottom of the page.
2. The context menu doesn't appear.

### Requirements

The context menu should appear. I confirmed it appears in 2.4.71.0.

### Files Version

2.4.84.0

### Windows Version

Windows 11 22H2

### Log file

n/a

**Comment by yaira2** [comment]
Thank you for reporting this
