### ISSUE TITLE
Files crashes when i try to drag a file

### ISSUE THREAD

**Issue by mahdi28881** [files-community/Files#12529]
### Description

when I'm editing or doing something performance heavy and I try to drag a file as I always did with Microsoft Explorer the files program crashes saying an error occurred and takes me to this place
**and the same thing happened when i tied to drag and drop the debug log in the browser

ps: i just wanted to say thank you for the amazing app and all the hard work that you've put into it  XO

### Steps To Reproduce

open something performance heavy
try to drag a file onto another program while the system is under load

### Requirements

I should be able to drag files even when my pc is under load

### Files Version

2.4.71.0

### Windows Version

10.0.19044.2965

**Comment by mahdi28881** [comment]
you are the expert but the thing that caught my eye was

2023-06-02 11:22:58.4466|Information|App activated. Activated args type: ProtocolActivatedEventArgs
2023-06-02 11:23:51.4630|Error|System.Runtime.InteropServices.COMException (0x8000FFFF): Catastrophic failure (0x8000FFFF (E_UNEXPECTED))

**Comment by yaira2** [comment]
> ps: i just wanted to say thank you for the amazing app and all the hard work that you've put into it XO

Thank you for the kind words

**Comment by Josh65-2201** [comment]
@mahdi28881 Can you see if this is an issue in 2.5.21.0

**Comment by yaira2** [comment]
We have some further improvements in the latest preview build.
