### ISSUE TITLE
Recycle Bin Crash

### ISSUE THREAD

**Issue by notaiva** [files-community/Files#12530]
### Description

Files Crashed When Trying To Load Recycle Bin On Home Tab Where Quick Access Icon Showed
But When Minimizing Quick Access Tab It Wont Crash

https://drive.google.com/file/d/16aY4HTd2WKwXJwuby5LiOLkyUGnFLTvB/view?usp=sharing
The Video of What Happened 
GitHub Wont Let Me Post Video Larger Than 10mb

_Im sorry if the bug report isnt detailed_

### Steps To Reproduce

1. Pin Recycle Bin To Quick Access
2. Open Files 

### Requirements

The Recycle Bin Icon Supposed To Load But It Refused

### Files Version

Version: 2.4.71.0 OS Version: 10.0.22621.1702

### Windows Version

Windows 11 22H2 22621.1702

### Log file

[debug.log](https://github.com/files-community/Files/files/11633857/debug.log)

**Comment by hishitetsu** [comment]
@notaiva thank you for reporting the issue. Can you try turning off the Tags widget to see if this problem still occurs? It may be the same problem as #12370.

**Comment by yaira2** [comment]
Thank you for the report, we're going to continue tracking this in #12370
