### ISSUE TITLE
Indiscernible tags after modifying ads data

### ISSUE THREAD

**Issue by lapaz17** [files-community/Files#12539]
### Description

1.Create two text files
2.Tag one of them with work/home etc.
3. change ads of both of them by using https://learn.microsoft.com/en-us/windows/win32/fileio/using-streams 
4. inspect ads data by "more < filename " on cmd  (This is TestFile:Stream-26e859d14b3d and This is TestFile:Stream are being written)
5. Click one of unknown tags on folder
6. No file is being shown unlike other predefined tags (work/home etc.) 
![Screenshot (2)](https://github.com/files-community/Files/assets/39624400/1669d6d2-4973-425e-92d0-8712a7030259)

![Screenshot (3)](https://github.com/files-community/Files/assets/39624400/ac363505-9ac1-4495-aabe-61229b39e5ad)

### Steps To Reproduce

Written above

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

commit 6d7c29d4037362602f2146cb0b9fab504999d18b (HEAD -> main, origin/main, origin/HEAD) Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com> Date:   Fri Jun 2 01:59:28 2023 -0400

### Windows Version

Windows 11 (22H2): 22621

### Log File

[debug.log](https://github.com/files-community/Files/files/11646186/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Sorry for the delayed response.
- If you open the ADS file does it have only the same UID as the tag you want added to the file/folder?

**Comment by lapaz17** [comment]
Sorry, I deleted my windows partition. Wont help about that

**Comment by Josh65-2201** [comment]
Alright.
