### ISSUE TITLE
Bug: Issue with Compression Progress Display in "Ongoing Tasks" for Elements

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12531]
### Description

Hello, I have encountered an issue related to the compression of folders. When I attempt to compress a folder of varying size and check the "Ongoing Tasks" section to monitor the compression progress, it shows 0% or just 50% progress even though the compression is actually taking place. Ideally, there should be a progress indicator similar to file extraction (for example, 500/1000: 50% or just for example 47% only) to reflect the ongoing compression progress.

### Steps To Reproduce

1. Open Files
2. Compress a large file

### Requirements

Identify the cause of the incorrect progress display in the "Ongoing Tasks" section during folder compression.

### Files Version

Version : 2.4.84.0

### Windows Version

Windows 11 22H2 22621.1778

### Log file

<img width="315" alt="Capture d'écran 2023-06-02 111657" src="https://github.com/files-community/Files/assets/128183422/8fbc7c96-8bcc-4660-9799-665b0c5b98c1">

![Capture d'écran 2023-06-02 112735](https://github.com/files-community/Files/assets/128183422/c84cfc26-23a8-45bd-9024-7d87d3a2c00b)

**Comment by yaira2** [comment]
Thank you for reporting this issue

**Comment by ferrariofilippo** [comment]
This bug might not be caused by Files itself but rather by SevenSipSharp library.
I remember a few months ago I found out that the library isn't updating the progress of single elements. I tried to work on it but it was out of my knowledge

**Comment by Lukiluc29** [comment]
> This bug might not be caused by Files itself but rather by SevenSipSharp library. I remember a few months ago I found out that the library isn't updating the progress of single elements. I tried to work on it but it was out of my knowledge

In this case you should ask SevenZipSharp to fix the bug ?

**Comment by ferrariofilippo** [comment]
There's already an open issue:
https://github.com/squid-box/SevenZipSharp/issues/77

**Comment by Lukiluc29** [comment]
Ok thank you
