### ISSUE TITLE
Bug: Renaming a tag doesn't save the changes

### ISSUE THREAD

**Issue by stotka1** [files-community/Files#12535]
### Description

When editing the name of the existing tags, It doesn't save the changes in full. Only saves 1 of the changes. Sometimes not even that. 
I have tried editing one then closing the window, then editing the next. I've tried changing one or more then closing the full app and only some changes stick until a later windows restart. 
I have only tried editing the existing colour names without adding more tags.
The edited names seem to save one by one but in random intervals and tries.

### Steps To Reproduce

Open settings
Tags
Edit
Rename
Save Changes
At a later time some of the names turn to the default name

### Requirements

Have tag names saved until edited again.

### Files Version

2.4.71.0

### Windows Version

10.0.19045.2965

### Log file

[debug.log](https://github.com/files-community/Files/files/11643386/debug.log)

**Comment by Josh65-2201** [comment]
Thans for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by stotka1** [comment]
On app restart the names go to their default state in the preview version.

**Comment by Josh65-2201** [comment]
What do you mean default state? Do you mean they go back to the name/color you set before the edit.
Can you also upload the log from the preview version.

**Comment by stotka1** [comment]
Yes, the tags go back to their original name.
[debug.log](https://github.com/files-community/Files/files/11643796/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the Information, I have added to the project board to be tracked.

**Comment by yaira2** [comment]
Is this only when renaming multiple tags?

**Comment by stotka1** [comment]
It happens randomly. Single or Multiple

**Comment by yaira2** [comment]
This issue will be resolved in the next release
