### ISSUE TITLE
Feature: Show a progress ring while loading the properties details page

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#12532]
### What feature or improvement do you think would benefit Files?

Since it takes a little time to display the properties details page, it would be helpful to display a progress ring while loading.

### Requirements

Show a progress ring while loading the properties details page.

### Files Version

2.4.84.0

### Windows Version

Windows 11 22H2

**Comment by yaira2** [comment]
Thank you for the feedback.

**Comment by hishitetsu** [comment]
I'll work on this.
