### ISSUE TITLE
Persistant tags that are visible in to other network users through other tools

### ISSUE THREAD

**Issue by dhodgman** [files-community/Files#12533]
### What feature or improvement do you think would benefit Files?

As a member of a software development team,
    I need to be able to add, update and delete tags on network files and folders
    that are visible to other network users through other tools
    so that we can use tags to manage our work.

### Requirements

This requirement is why I purchased this tool (2.4.71.0).  Disappointed that it doesn't do what I'd hoped.  

### Files Version

2.4.71.0

### Windows Version

10.0.19045.3031

### Comments

If this feature is available, I'm confident that I can persuade my company to purchase this tool for many users.
Please advise whether this can be provided and in what time frame?

**Comment by Josh65-2201** [comment]
Thanks for the report. I am unable to reproduce this, Can you give the following information.
- What other tool are you referring too? Files uses ADS files to store and read tags on files and folders.
- Are your network drives formatted as NTFS?
- Assuming the tool you are referring to is Files do they have the same `filetags.json` file located in Files settings > About > Open log location > settings

**Comment by dhodgman** [comment]
Hi Josh.  I am referring to MS File Explorer primarily.  I need to tag files so that other people can see the tags without using your product.  I also need them to be able to search for files using tags in the same way you can use Explorer to search for photos based on tags.

**Comment by Josh65-2201** [comment]
Windows File Explorer doesn't support tags as Microsoft has never made that feature. They are developed by the Files team for the app. However they are just saved as ADS files so you could make a read them if you wanted.

Tag can also be search for using `tags:<tag name>` in Files
