### ISSUE TITLE
Press esc to deselect a file

### ISSUE THREAD

**Issue by lapaz17** [files-community/Files#12538]
### What feature or improvement do you think would benefit Files?

![Screenshot (1)](https://github.com/files-community/Files/assets/39624400/49c29eb8-de1f-4a59-b9fe-eb29a2e6e5d9)
After selecting a file by mistake, I immediately pressed esc to deselect but nothing happened. Is this by choice?  It is a missing one I guess. It should have deselected.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

commit 6d7c29d4037362602f2146cb0b9fab504999d18b (HEAD -> main, origin/main, origin/HEAD) Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com> Date:   Fri Jun 2 01:59:28 2023 -0400

### Windows Version

Windows 11 (22H2): 22621

**Comment by yaira2** [comment]
>  Is this by choice? It is a missing one I guess. It should have deselected.

It's never been requested before, for what it's worth, it's isn't supported in File Explorer either.

**Comment by hishitetsu** [comment]
We already have an action in place to achieve this. All that remains is to assign esc key to the hotkey.
https://github.com/files-community/Files/blob/main/src/Files.App/Actions/Content/Selection/ClearSelectionAction.cs

**Comment by yaira2** [comment]
In that case this will be supported once we add support for remapping keyboard shortcuts.
