### ISSUE TITLE
Lag when deleting folders

### ISSUE THREAD

**Issue by Allen1351** [files-community/Files#12536]
### Description

When I press to delete a folder or several folders, it does nothing until I enter or leave the current path. Then the dialogue to confirm deletions pops out. So is not a problem of just lagging to execute the order, it only reacts to it once the path changes. 

### Steps To Reproduce

1. Delete a folder
2. Wait, nothing happens
3. Enter another folder

### Requirements

- eg. Fix crash that occurs when...

### Files Version

2.4.71.0

### Windows Version

10.0.19045.2965

### Log file

[debug.log](https://github.com/files-community/Files/files/11644565/debug.log)

**Comment by yaira2** [comment]
Thank you for reporting this issue, it should be fixed in the preview build and will be included in the upcoming v2.5 release.
