### ISSUE TITLE
Feature: Add option to hide "send to" menu

### ISSUE THREAD

**Issue by D-Maxwell** [files-community/Files#12546]
### What feature or improvement do you think would benefit Files?

I would like being able to choose which entries show up in each context menu ; although, as this may not be compatible with the current way context menus have been implemented, or as it may require quite the effort, I would like to ask for an option to hide the "Send to" entry, as it looks out of place, and as I personally find no use in its presence (although this last bit is completely subjective).

### Requirements

- This suggestion will allow for further customisation
- This proposition would bring cohesion to the UI
- This feature could de-clutter each context menu, for those who find no use in the option.

### Files Version

2.4.71.0

### Windows Version

Windows 10 (22H2): 19045

### Comments

The fact that the 'Send to' entry does not feature an icon is what makes it stand out negatively. If none of the aforementioned options were to be implemented or implementable, I definitely think giving it an icon would add to the continuity and cohesion of the Files app's user interface.

Alternatively, one could follow the registry entries that determine whether 'Send to' should be enabled or not. This way, for those which have disabled it already (using third party software like WinaeroTweaker for instance), there would be no redundant setting to toggle.

**Comment by yaira2** [comment]
The send to menu is already hidden, where are you seeing it?

**Comment by D-Maxwell** [comment]
![image](https://github.com/files-community/Files/assets/98100481/1c69b6b0-5b72-4b8c-93fa-504aeae67e33)

Perhaps I have done something unintended ; if so, I do not know what it might be.

**Comment by Josh65-2201** [comment]
The send to menu was enabled in #10986

**Comment by yaira2** [comment]
I mixed it up with cast to device.

**Comment by D-Maxwell** [comment]
Is there a native way to disable this option ?

**Comment by yaira2** [comment]
Not in Files directly, but you can you use apps like WinaeroTweaker for this.

**Comment by D-Maxwell** [comment]
> Not in Files directly, but you can you use apps like WinaeroTweaker for this.

![image](https://github.com/files-community/Files/assets/98100481/f4f1af4d-a99f-4ead-81fc-a2ee5b68077f)

'Send to' is already disabled.

Therefore I may ask once more : is there a way to disable this, or must new code be implemented ?

**Comment by yaira2** [comment]
"Send to" might be different because we have special logic to display it in the main menu as opposed to the sub menu where all the other shell extensions are displayed in a sub menu. We can look into supporting this option, but we'll need to gather more feedback to see if other users are interested in this as well.

**Comment by D-Maxwell** [comment]
> "Send to" might be different because we have special logic to display it in the main menu as opposed to the other shell extensions that are displayed in a sub menu. We can look into supporting this option, but we'll need to gather more feedback to see if other users are interested in this as well.

Understandable and understood, I will look forward to any related community polls.
So this is in fact not a bug, but nothing more than a lack of parity ? (I was afraid it had to do with my inability to customise the user folders icons (NotAFolder ??).

Hopefully this gains interest from others.

**Comment by yaira2** [comment]
It's not a bug because we don't have built-in support for hiding menu items, it's a feature request 👍

**Comment by yaira2** [comment]
> I was afraid it had to do with my inability to customise the user folders icons

This sounds like a different issue, but can you elaborate?
