### ISSUE TITLE
Copying file path copies without quotes

### ISSUE THREAD

**Issue by lapaz17** [files-community/Files#12540]
### Description

Shift right click and selecting "copy as path" on Explorer.exe implements same function with quotes. This will provide bugs when users want to paste paths containing whitespaces to cmd or similar cli  .
My preferred solution: If path contains whitespaces, add quotes.

### Steps To Reproduce

1. press crtl shift c after pressing a file
2.paste it to somewhere
3.pastes without quotes unlike explorer.exe

### Requirements

- e.g. Fix crash that occurs when...
My preferred solution: If path contains whitespaces, add quotes.

### Files Version

commit 6d7c29d4037362602f2146cb0b9fab504999d18b (HEAD -> main, origin/main, origin/HEAD) Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com> Date:   Fri Jun 2 01:59:28 2023 -0400

### Windows Version

Windows 11 (22H2): 22621

### Log File

[debug.log](https://github.com/files-community/Files/files/11646273/debug.log)

**Comment by yaira2** [comment]
@lapaz17 thank you for your feedback, this isn't currently supported but it's a good feature to add. Can you open a feature request so we can properly track this?
