### ISSUE TITLE
How to disable the update notification

### ISSUE THREAD

**Issue by shead0shead** [files-community/Files#12541]
### What feature or improvement do you think would benefit Files?

When i open the app, an update notification appears, can I turn it off?

### Files Version

2.3.12.0

### Windows Version

Windows 11 (22H2): 22621

**Comment by Josh65-2201** [comment]
There isn't a way to do so as its intended for people to be on the latest version.

**Comment by yaira2** [comment]
@shead0shead is there a reason why you're still using v2.3.12?

**Comment by shead0shead** [comment]
It's more convenient for me and in the version I use there are fewer functions that I don't need.

**Comment by yaira2** [comment]
This version is no longer supported but we'd like to hear more about your use case  to see if we can improve the latest version.
