### ISSUE TITLE
Taskbar stays hidden

### ISSUE THREAD

**Issue by GuruDeol** [files-community/Files#12547]
### Description

Hi there... I keep the taskbar settings as auto hide but when i use this files app, the taskbar doesnt show up when the move my mouse at the bottom. This only happens when i'm using files app in the full screen

### Steps To Reproduce

make sure your taskbar is set on auto hide.
open the app in maximize mode.
move the cursor to the bottom of the screen to bring the taskbar.
the taskbar doesn't come up.

### Requirements

- e.g. Fix the taskbar apperance when cursor is moved at the bottom of the screen while using files app. I have to press windows button to make the taskbar appear in the app.

### Files Version

2.4.71.0

### Windows Version

Windows 11 Insider: 25xxx series

### Log File

[debug.log](https://github.com/files-community/Files/files/11658178/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #10767. You can check there or click subscribe in the right sidebar for updates.
