### ISSUE TITLE
Feature: Ctrl + shift to copy as path with quotes

### ISSUE THREAD

**Issue by lapaz17** [files-community/Files#12545]
### What feature or improvement do you think would benefit Files?

Shift right click and selecting "copy as path" on Explorer.exe implements same function with quotes. This will provide bugs when users want to paste paths containing whitespaces to cmd or similar cli, so add copy feature with quotes

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.4.71.0

### Windows Version

Windows 11 (22H2): 22621

**Comment by yaira2** [comment]
Thank you for the feedback

**Comment by HorseBandit** [comment]
@yaira2 Any plan to approve this one?

**Comment by yaira2** [comment]
We're waiting for more feedback before approving this.
