### ISSUE TITLE
Bug: App crashes when moving file from VS code to Files

### ISSUE THREAD

**Issue by takanobuko-kore** [files-community/Files#12548]
### Description

When I tried to move a file from explorer in VS Code to Files by D&D, Files immediately crashed and restart automatically.
It crashed not drop but just drag to Files.
![image](https://github.com/files-community/Files/assets/110897881/048b7781-95cd-4e76-99ff-f6ed92dc498c)

FYI, it doesn't crash if move a file from Files to VS Code.

### Steps To Reproduce

Move a file from explorer in VS Code to Files by D&D

### Requirements

- Enable to move a file from explorer in VS Code to Files by D&D
- It might happen in another application

### Files Version

2.4.71.0

### Windows Version

Windows 11 (22H2): 22621

### Log File

[debug.log](https://github.com/files-community/Files/files/11661506/debug.log)

**Comment by yaira2** [comment]
Thank you for the bug report, can you check if this is still an issue in the latest preview build? https://files.community/download

**Comment by takanobuko-kore** [comment]
Yes, it is.

**Comment by yaira2** [comment]
@takanobuko-kore thanks for checking, we recently updated some dependencies that might have helped. Can you try the latest preview again (v2.5.32)?

**Comment by yaira2** [comment]
I can still repro the issue in v2.5.32, but the good news is that we have a fix for it in v2.5.33.
