### ISSUE TITLE
Bug: Custom Font not used consistently

### ISSUE THREAD

**Issue by QuaintMako** [files-community/Files#12553]
### Description

Several windows / menus in the application does not use the custom font where we could expect it to.

Some notable examples can be:
- The Properties Window
- The Shell Extension Menu (?)
- ~Update notes~

![Screenshot_1](https://github.com/files-community/Files/assets/110472580/2bcb18c6-2d81-4976-b3ef-f77fe192ab08)

### Steps To Reproduce

For the case of the Properties window:

1- Use any custom font (`Segoe Script` can be helpful to distinguish quickly the correct use)
2- Open the properties of any element, observe several texts use the standard font.

### Requirements

- The custom font is properly used throughout the application

### Files Version

Segoe Script

### Windows Version

Windows 10 (22H2): 19045

### Log File

Irrelevant.

**Comment by yaira2** [comment]
Thank you for the bug report

**Comment by QuaintMako** [comment]
Found another one in the update panel:
![image](https://github.com/files-community/Files/assets/110472580/2d1453b4-5f79-4a0d-8179-1378c07b20ab)

**Comment by yaira2** [comment]
> Found another one in the update panel:

This is probably because it's a markdown reader

**Comment by yaira2** [comment]
> The Shell Extension Menu

The context menu looks alright to me.
