### ISSUE TITLE
Auto hidden Taskbar doesn't open when hovering Taskbar position.

### ISSUE THREAD

**Issue by jatinsehrwt** [files-community/Files#12552]
### Description

When hovering over the bottom of the screen, with files app in full-screen mode and enabled as default file manager of windows. It wont't let me peek the taskbar in auto-hidden mode. 

### Steps To Reproduce

1. Set files app as default file manager
2. Turn on auto-hiding feature of taskbar in windows 11
3. Open files app and hover over taskbar

### Requirements

- Able to peek the taskbar

### Files Version

2.4.71.0

### Windows Version

Windows 11 Insider: 23xxx series

### Log File

[debug.log](https://github.com/files-community/Files/files/11664856/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #10767. You can check there or click subscribe in the right sidebar for updates.
