### ISSUE TITLE
Bug: OpenHashTab freezes when opened from Files

### ISSUE THREAD

**Issue by Shadow912kage** [files-community/Files#12550]
### Description

When I open OpenHashTab, the OpenHashTab window freezes and the mouse icon is busy.
Environment:
-  Files: v2.4.71.0/2.4.84.0
-  OpenHashTab: v3.0.2
-  OS: Windows 10 Pro 22H2 10.0.19045.3031

### Steps To Reproduce

1. Install OpenHashTab: [namazso/OpenHashTab: 📝 File hashing and checking shell extension](
https://github.com/namazso/OpenHashTab)
2. Right-click on the file
3. Select "Show more options"
4. Select "Hashes"

### Requirements

- Fix the freeze that occurs when using OpenHashTab

### Files Version

Version: 2.4.71.0 and 2.4.84.0

### Windows Version

Windows 10 (22H2): 19045

### Log File

[debug.log](https://github.com/files-community/Files/files/11662970/debug.log)

**Comment by Shadow912kage** [comment]
OpenHashTab window freezes.

**Comment by yaira2** [comment]
Thank you for the report, I added this to our project board, but I wanted to make sure you're aware that we have a hashes tab built-in to the properties window.

**Comment by yaira2** [comment]
@Shadow912kage we're able to repro this issue, but it appears to be an issue with OpenHashTab. We suggest reporting this to the OpenHashTab developer.
