### ISSUE TITLE
Bug: Alignment is off on the name column

### ISSUE THREAD

**Issue by mdtauk** [files-community/Files#12567]
### What feature or improvement do you think would benefit Files?

I noticed a few issues with things not aligning properly.  Wherever possible these things should be corrected to make the app feel more polished and professional.

![image](https://github.com/files-community/Files/assets/7389110/d2d43c9f-7843-4291-ba9e-3a4b6100a67c)

### Requirements

- This proposal will improve app quality

### Files Version

2.4.85

### Windows Version

Windows 11 (22H2): 22621

### Comments

Before a major release, these little things should be fixed to come out strong.

**Comment by yaira2** [comment]
@0x5bfa I believe you had a fix for this, can you confirm?

**Comment by mdtauk** [comment]
The other column headers are slightly out of alignment too, only by a pixel or 2, but it is noticeable

**Comment by yaira2** [comment]
This will be resolved in v2.5.
