### ISSUE TITLE
Feature: Support for pushing git changes

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#12561]
### What feature or improvement do you think would benefit Files?

We have support for pulling changes so it makes sense to add support for pushing as well.

### Requirements

- Display the number of unpushed commits on the status bar
- Clicking the button will display menu flyout with the options to
   - push
   - pull

### Files Version

v2.4.85

### Windows Version

Windows 11 (22H2): 22621

**Comment by mdtauk** [comment]
Do we need to list un-pushed commits somewhere?

**Comment by yaira2** [comment]
Yes, but it'll have to wait for the git pane so users can commit the changes.
