### ISSUE TITLE
Add trace to visualize the path in column view

### ISSUE THREAD

**Issue by py-Alexis** [files-community/Files#12568]
### What feature or improvement do you think would benefit Files?

When in column view you know the path only with the text at the top and not from the different columns themselves so I think I would be great that to indicate each folder we are in.

Since my explanation are probably not very clear, I photoshopped what it would look like
before
![image](https://github.com/files-community/Files/assets/85698747/f48c344e-4736-48f0-92db-0f93cd27bdfb)
after
![image](https://github.com/files-community/Files/assets/85698747/3bc38d50-0058-4ed8-af02-1a94545fc649)

### Requirements

Keep the "highlight" on the folder in column mode

### Files Version

Version: 2.4.71.0

### Windows Version

Windows 10 (22H2): 19045

**Comment by yaira2** [comment]
This is already implemented, if it's not working properly in the latest preview, can you open a bug report? https://files.community/download.

**Comment by py-Alexis** [comment]
Sorry I hadn't realized there was a preview version I works perfect 
thanks

**Comment by py-Alexis** [comment]
Hello, I sorry again I thought that installing the preview version had solved the problem but it did because teh app use the dark theme by default so I open a bug report #12577 as you asked
