### ISSUE TITLE
Silent Error when Folder Delete operation failed

### ISSUE THREAD

**Issue by cardin** [files-community/Files#12574]
### Description

I was using Files to delete a folder. The folder deletion failed (due to a subfile being opened by another application).

However, there was no error popup to indicate the folder deletion failed. One has to go to the Ongoing Tasks panel to know that the operation failed.

### Steps To Reproduce

1. Have a folder that contains some files
2. Open one of the files in Visual Studio Code
3. Use Files to delete the folder
4. Observe that is no indication that the operation failed. No popups, no color changes, no icons.
5. Observe the Ongoing Tasks panel mention the operation failed

### Requirements

- When a file operation failed, there should be an outward indication of failure, such as a popup, color change, or notification icon.

### Files Version

2.4.85.0

### Windows Version

Windows 10 (22H2): 19045

### Log File

I checked the logs, there was nothing written in the prior 6 hours till when the file operation failed. So there are no relevant logs to upload.

**Comment by yaira2** [comment]
Deleting an open file displays a popup dialog for me, can you see what happens if you try deleting the file itself as opposed to the folder?

**Comment by gave92** [comment]
Deleting the parent folder of a in-use file also displays a popup for me
<img width="414" alt="image" src="https://github.com/files-community/Files/assets/9673091/37285593-1380-4bd8-a9e0-28212efc4f6e">
@yaira2 didn't the Ongoing Tasks icon use to display a colored badge with the number of operations? Has support for badges come back for winui yet?

**Comment by Josh65-2201** [comment]
This might be a different reason the folder failed to delete as VS code doesn't lock files and can normally be delete when open in VS code. Can you try in Windows File Explorer and see if it show an error.

**Comment by yaira2** [comment]
> didn't the Ongoing Tasks icon use to display a colored badge with the number of operations? Has support for badges come back for winui yet?

This needs to be tested but I don't remember seeing this in any of the WinUI changelogs.

**Comment by cardin** [comment]
> This might be a different reason the folder failed to delete as VS code doesn't lock files and can normally be delete when open in VS code

Ah you're right - VSCode doesn't really lock.

Okay it took me a while to reproduce the problem again, but the new reproduction steps are:
1. Have a folder with a file in it
2. Use **WSL** and open the file in `vi` or `vim` (not `nano`, it doesn't lock)
3. Try deleting the file in Files App
4. Ongoing Tasks had a deletion failure, but there isn't any UI popup
![image](https://github.com/files-community/Files/assets/553816/edf98728-3c18-4f9d-a13e-2ddec3cc1e91)

Files Version 2.5.0.0
Windows 10.0.19045.3031
WSL 5.15.90.1-microsoft-standard-WSL2

**Comment by Josh65-2201** [comment]
What does it do in Windows File Explorer?

**Comment by cardin** [comment]
> What happens if you do in Windows File Explorer?

If I had used WSL to `vi` the file, Windows Explorer refuses to delete due to Admin privileges.

![image](https://github.com/files-community/Files/assets/553816/ca498283-8190-4edf-9304-256fcf2cba52)

====

If I had used WSL to `cd` into the folder, Windows Explorer ignores WSL and deletes the folder.

**Comment by Josh65-2201** [comment]
This is likely the same issue as #10422

**Comment by yaira2** [comment]
We hope to find a solution for that soon, thanks.

**Comment by yaira2** [comment]
This issue is resolved in our dev branch and will be included in the next release.
