### ISSUE TITLE
Files List

### ISSUE THREAD

**Issue by CrispyMates** [files-community/Files#12578]
### What feature or improvement do you think would benefit Files?

Hello I'm a newby and don't really know what i'm doing but I recently purchaes Files.Community. It's nice and smooth and i'm enjoyinhg it so far but I though i'd give you some feedback on what I think. 
It would be helpful if there were some instructional videos for the likes of us plebs. 🥺
Seccondly the different view optioans are good but I feel you're missing List view like Windows Explorer. With list view, the folders are small like in Detail viw but one thing i really like is the way the folders wrap\create as many columns as you need for the number of folders\files within a folder. 
![List View](https://github.com/files-community/Files/assets/136147331/1b3d1f45-a4e0-4ed2-aef0-45db31881a99)

Also, could you get rid of teh new Tackbar, I have all my shortcuts setup in a folder where they load into ExplorerPatcher 
![TaskBar ExplorerPatcher](https://github.com/files-community/Files/assets/136147331/8cd5addc-1a44-40e7-94f2-995758793d9b)

Thnkyou to whoever is out there. 

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.4.71.0

### Windows Version

Windows 11 (22H2): 22621

### Comments

btw I am not a prorammer, just a user of your products and this seemed the only way I could give you feedback.

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #2509. You can check there or click subscribe in the right sidebar for updates.
Also Files doesn't control or change the Windows taskbar.

**Comment by Josh65-2201** [comment]
What would you need instructional videos on?

**Comment by CrispyMates** [comment]
Well I had no idea how to use Columns view until I found a youtube video of someone reviewing it. The review didn't extactly show you how to use it but I figured it out once I replayed the video a couple of times.
Also I'm not entirely sure how to use Tags and what\how it willbenefit my work. 
Just a couple of examples from a pleb whi is getting to know your App 🙂

**Comment by Josh65-2201** [comment]
There is documentation on the site here https://files.community/docs user information would be under Configuring files

**Comment by CrispyMates** [comment]
Ok, thanks I'll have a closer look. Cheers from Down Under 🌏🦘

**Comment by yaira2** [comment]
@CrispyMates thank you for your patience, I'm excited to share that a List View layout will be included in the next release.
