### ISSUE TITLE
After modifying the tagged dwg file (autocad), the tag will disappear.

### ISSUE THREAD

**Issue by Gump529** [files-community/Files#12573]
### Description

After modifying the tagged dwg file (autocad), the tag will disappear.
I hope that this bug can be fixed as soon as possible. This function is very helpful to me, thank you very much.

### Steps To Reproduce

1. Tag the dwg file
2. modifying the tagged dwg file
3.  the tag  disappear

### Requirements

dwg files can be tagged

### Files Version

2.4.71.0

### Windows Version

Windows 11 Insider: 25xxx series, Windows 11 (21H2): 22000

### Log File

[debug.log](https://github.com/files-community/Files/files/11702362/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report. Can you check if the ADS files are kept, you can do this by.
- Going to Files settings > Folders > Hidden items > Show alternate data streams
- Add a tag to the dwg file
- There should be a grey out file below it shown as `filename.dwg:files`
- Open that file in autocad
- Save it in the program
- See if that `filename.dwg:files` file is still there

**Comment by Josh65-2201** [comment]
@Gump529 Can you answer the above question please.

**Comment by gave92** [comment]
Autocad probably replaces the old file when saving changes, so the tag is lost.
