### ISSUE TITLE
Files se cierra continuamente

### ISSUE THREAD

**Issue by Mariepiz** [files-community/Files#12586]
### Description

Files se cierra continuamente, se abre y se queda en programa no responde, luego se esta trabajando y se cierra inesperadamente 

### Steps To Reproduce

Files se cierra continuamente, se abre y se queda en programa no responde, luego se esta trabajando y se cierra inesperadamente 

### Requirements

- e.g. Fix crash that occurs when...
Files se cierra continuamente, se abre y se queda en programa no responde, luego se esta trabajando y se cierra inesperadamente 

### Files Version

2.4.71.0

### Windows Version

Windows 10 (22H2): 19045

### Log File

[debug.log](https://github.com/files-community/Files/files/11716114/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by Josh65-2201** [comment]
@Mariepiz Can you answer the above questions please.

**Comment by yaira2** [comment]
@Mariepiz thank you for the report, can you help us out with a little more information about what features you were using when it crashed?
