### ISSUE TITLE
Use Everything for searching

### ISSUE THREAD

**Issue by YT-Advanced** [files-community/Files#12587]
### What feature or improvement do you think would benefit Files?

- It will improve the speed and performance when searching
- It also support search with regex #9711 , search content and a lot of other options
You can see all the feature of Everything here: https://www.voidtools.com/support/everything/searching/
- Lastly, Everything can be called via command line, so we can use it to be a part of Files project
Follow this link: https://www.voidtools.com/support/everything/command_line_options/

### Requirements

- EveryThing portable executable

### Files Version

Latest

### Windows Version

Windows 11 (22H2): 22621

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #5845. You can check there or click subscribe in the right sidebar for updates.
