### ISSUE TITLE
Bug: Preview Pane does not refresh when switching pane in Dual Pane

### ISSUE THREAD

**Issue by QuaintMako** [files-community/Files#12588]
### Description

When using the dual pane mode, the Preview Pane does not correctly refresh its content. Instead, it displays no information even if an item is selected.

![NoRender](https://github.com/files-community/Files/assets/110472580/b38e2e0b-478e-458b-90d6-36525798541e)

### Steps To Reproduce

1. Open the dual pane mode.
2. Select an item so its preview is done.
3. Switch column by clicking on another item. No preview is displayed.

### Requirements

- The preview is correctly displayed when switching pane.

### Files Version

V.2.81.0 Dev

### Windows Version

Windows 10 (21H2): 19044

### Log File

Unneeded

**Comment by yaira2** [comment]
Thank you for reporting this issue
