### ISSUE TITLE
Feature: Add Separate "Compress" and "Decompress" Options in the Context Menu

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12582]
### What feature or improvement do you think would benefit Files?

I would like to propose adding a separate function in the context menu specifically for decompressing files. Currently, the decompress option is included within the "Archive" category in the context menu. I suggest renaming this category to "Compress" and adding a separate category named "Decompress" instead of putting them all in one category.

### Requirements

Modify the context menu interface to include a distinct "Compress" category and a separate "Decompress" category.

### Files Version

Version : 2.4.85.0

### Windows Version

Windows 11 (22H2): 22621

**Comment by yaira2** [comment]
Thank you for your feedback
