### ISSUE TITLE
Inconsistent Pluralization Issue in File Explorer

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12583]
### Description

I apologize in advance if I've categorized this issue incorrectly, as I wasn't sure which category it falls under. When I navigate to the Desktop folder, for example, and there are no applications displayed, instead of showing "0 item," it displays "0 items" with an unnecessary "s".

### Steps To Reproduce

1. Go to a directory that contains no files or folders

### Requirements

Identify the source of pluralization inconsistency within the Files interface.

### Files Version

Version 2.4.85.0

### Windows Version

Windows 11 (22H2): 22621

### Log File

<img width="476" alt="Capture d'écran 2023-06-11 121214" src="https://github.com/files-community/Files/assets/128183422/0771c368-5632-4823-8aa4-2aa70820c5ff">

**Comment by Josh65-2201** [comment]
`0 items` is the correct way of saying it.

**Comment by Lukiluc29** [comment]
Ah yes, it's true I had forgotten that zero is considered a number and therefore follows the same grammar rules as other numbers.
