### ISSUE TITLE
Bug: Scrollbar isn't visible when trying to reorder multiple elements in the sidebar

### ISSUE THREAD

**Issue by oleklukasiewicz** [files-community/Files#12596]
### Description

When the sidebar contains multiple elements, the scroll bar is not visible when trying to reorder them, even if the elements overflow the list.
![image](https://github.com/files-community/Files/assets/69370471/876d3e42-50db-43da-a020-c9c8558594e7)

### Steps To Reproduce

1. Add multiple item to sidebar.
2. Try to reorder them.

### Requirements

- Multiple items in sidebar

### Files Version

2.5.0.0

### Windows Version

Windows 11 (22H2): 22621

### Log File

[debug.log](https://github.com/files-community/Files/files/11735753/debug.log)

**Comment by yaira2** [comment]
This is fixed in the `main` branch.
