### ISSUE TITLE
Feature: Disable Mica on Windows 10

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#12591]
### What feature or improvement do you think would benefit Files?

Mica is only available for Windows 11, so it should be disabled on Windows 10.

### Requirements

Disable Mica on Windows 10 or at least indicate that it has no effect in Windows 10.

### Files Version

2.5.0.0

### Windows Version

Windows 10 (22H2): 19045

**Comment by yaira2** [comment]
We use it for the fallback colors

**Comment by hishitetsu** [comment]
Should it be called Mica in Windows 10?

**Comment by hishitetsu** [comment]
https://github.com/files-community/Files/blob/4dcde7b93850df8df8c878cb62961ba8d10e1074/src/Files.App/ViewModels/Settings/AppearanceViewModel.cs#L33-L34

I think Solid, which is now disabled, is appropriate.

**Comment by yaira2** [comment]
The default color for solid is transparent so it doesn't have very good contrast between the tabs and content.

**Comment by hishitetsu** [comment]
Okay, so Mica has no visual effect in Windows 10, but the color actually changes. I was a little mistaken.
