### ISSUE TITLE
Bug: Folders scroll to the top after using mouse wheel to open a folder in new tab

### ISSUE THREAD

**Issue by Zerlaxv1** [files-community/Files#12595]
### Description

When opening a folder with a wheel click, it will open the other folder in a new tab as intended. However, when returning to the first folder, it will open the pinned location instead of the previous location within the folder.

### Steps To Reproduce

1. open a pinned folder 
2. Move somewhere in the folder
3. Wheel click on another pinned folder
4. Come back to the first folder

https://github.com/files-community/Files/assets/62764982/ac9432a9-e779-46d6-bfcb-5e0401aeb3ab

### Requirements

When we come back, we should be in the same location where we left off.

### Files Version

2.5.0.0

### Windows Version

Windows 10 (22H2): 19045

### Log File

[debug.log](https://github.com/files-community/Files/files/11735316/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I was able to reproduce this.

**Comment by yaira2** [comment]
This issue will be fixed in the next release.
