### ISSUE TITLE
[Feature Request] QoL Changes related to group by date

### ISSUE THREAD

**Issue by octopushugger** [files-community/Files#12593]
### What feature or improvement do you think would benefit Files?

I like to change a lot of folders to "group by -> date modified -> month". This is inconvenient in the current preview version of Files for 3 reasons. I have to finagle with an extra flyout for years/months, then go back into the menu and change group sort to descending, then set item sort to date and descending as well. 

### Requirements

Therefore, when selecting group by date:

- I propose group sort is automatically set to descending. 

- I propose item sort within those groups is automatically set to corresponding date type (modified or created) and also auto-set to descending. (date created/modified being automatically added to the columns if not already present and that grouping was selected)

- I propose removal of the "years" date grouping option to limit flyouts and allow faster access to "months" which wouldn't need a name distinction anymore. And add option in the settings to switch between the months/years grouping styles globally but renamed to something like "use classic date grouping style". 

### Files Version

2.4.85.0

### Windows Version

Windows 11 (22H2): 22621

### Comments

The "years" options appears to be the same date grouping style as from explorer. Besides the somewhat misleading naming the "months" style is a straight improvement to me so having years seems useless unless you dislike it being different from explorer which in that case I'd expect those users to want the change globally, not per folder, making it better as a settings option. 

Github meta comment: I dislike this multi-box layout for issues. I don't think it made me be more clear, I think it just made me take more time to organize my thoughts to match the layout.

**Comment by Josh65-2201** [comment]
Thanks for the feedback. I've added this to the project board.

**Comment by yaira2** [comment]
> I propose group sort is automatically set to descending.

Thank you for your feedback, you can set the default sort direction from Settings > Folders > Sorting and grouping

> I propose removal of the "years" date grouping option to limit flyouts and allow faster access to "months" which wouldn't need a name distinction anymore. And add option in the settings to switch between the months/years grouping styles globally but renamed to something like "use classic date grouping style".

This is more of a recent addition, but you can also change the default date unit from Settings > Folders > Sorting and grouping.
