### ISSUE TITLE
Crash When Deleting Files from Downloads directory

### ISSUE THREAD

**Issue by Yarlen74** [files-community/Files#12594]
### Description

App crashed after selecting all but a handful of files from the Downloads directory and deleting them.

### Steps To Reproduce

1) Have a hundred of so files in Downloads folder
2) Select all but 5-8 of them and delete (not permanently)

### Requirements

- e.g. Fix crash that occurs when deleting lots of files

### Files Version

2.5.0.0

### Windows Version

Windows 11 (22H2): 22621

### Log File

[debug.log](https://github.com/files-community/Files/files/11735217/debug.log)

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by yaira2** [comment]
@Yarlen74 we can't reproduce this in the latest preview build. If you're still seeing this issue, please let us know.
