### ISSUE TITLE
Feature: Display drive information in Details Pane

### ISSUE THREAD

**Issue by QuaintMako** [files-community/Files#12597]
### What feature or improvement do you think would benefit Files?

With #12549, folder information is now displayed when no item is selected. However, when in the root folder, the information display is incomplete regarding to the drive data.

A new controller should be created to display for more complete information. The information displayed in the `Drive Properties > General` are a good place to start.

![image](https://github.com/files-community/Files/assets/110472580/93bbfa9d-4d4e-4472-bf53-7ae6436eaa4d)

### Requirements

- When in any root folder, like `C:/`, and no item is selected, basic information about the drive are displayed in the preview pane.
- The information displayed should be matching the information inside the `Drive Properties > General`.

### Files Version

2.5.0

### Windows Version

Windows 10 (21H2): 19044

**Comment by yaira2** [comment]
We can also take inspiration from the tooltip when hovering over drives.

**Comment by QuaintMako** [comment]
Can you assign the issue to me @yaira2 ? Thanks.

**Comment by yaira2** [comment]
@QuaintMako I got a design from @mdtauk
![image](https://github.com/files-community/Files/assets/39923744/5f5f4cc5-7a46-4306-adc1-9a45dffb3b24)

**Comment by Artoryn** [comment]
Howdy, I would like to work on this time if possible. I do think that the preview above would be a nice implementation for the preview window.

**Comment by yaira2** [comment]
@Artoryn thank you! Please let us know if you have any questions.

You can also join the app-dev channel on our Discord server discord.gg/files.

**Comment by yaira2** [comment]
This feature will be included in the next update.
