### ISSUE TITLE
Feature: Request for Animation Transition between "Details" and "Preview" in the Preview Pane

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12608]
### What feature or improvement do you think would benefit Files?

I was wondering if it would be possible to add a subtle animation when switching from "Details" to "Preview" in the preview pane. I envision an animation where the small bar beneath the words "Details" and "Preview" would smoothly slide from one word to the other, similar to when transitioning between folders (e.g., from "Desktop" to "Downloads") in the sidebar.

### Requirements

Design a visually appealing animation that seamlessly moves the bar between the "Details" and "Preview" words.

### Files Version

Version : 2.5.0.0

### Windows Version

Windows 11 (22H2): 22621

**Comment by Josh65-2201** [comment]
Thanks for the feedback. I have added this to the project board.

**Comment by yaira2** [comment]
This will be included when we are able to update the Community Toolkit and use the Segmented control.
