### ISSUE TITLE
"Advanced" feature Advanced > Set Files as the default file manager

### ISSUE THREAD

**Issue by JackGFuller** [files-community/Files#12602]
### Description

I run as a Standard User. But even when running Files as Administrator, this feature doesn't 'stick. 

When I sign on as Administrator, this feature is Enabled. The button is "On" !
But Windows then says that there is no Explorer.exe. So this may be one of the "Proceed at your own risk" items.

As Standard User, explorer.exe does exist.

### Steps To Reproduce

Settings > Advanced > Experimental feature flags.

UAC wants approval. Granted.

Move button from Off to On.

"On" shows for a second or so, then reverts to "Off".

### Requirements

I would expect that this Feature Flag would stay "On".

### Files Version

2.4.71.0

### Windows Version

Windows 11 (22H2): 22621

### Log File

[debug.log](https://github.com/files-community/Files/files/11741131/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report. Normally when it doesn't turn on it means the some compatibility issue. You can try the below but it may not work.
- Update Files and Windows.
- Disable anything that blocks editing the registry.

**Comment by yaira2** [comment]
@JackGFuller were you able to get this working?

**Comment by JackGFuller** [comment]
Thanks for your response!

Alas - not yet, even with Files 2.5.10.0. 

Running as Standard [not Administrator], when I select the option, 

![image](https://github.com/files-community/Files/assets/74563788/2e0dff0e-9508-4cdb-bc57-248e72658cc1)

I then move the button to "On":

Upon moving to "On", I am asked by UAC to enter my PIN. Upon doing so, the button moves quickly to "Off".

However, when running as Administrator, I can set that flag to "On", and it stays on. But when performing a "Save As", it is File Explorer that is shown, for indicating the Save As location, not Files.

**Comment by Josh65-2201** [comment]
That option doesn't change the open/save as dialogs. It will only opens Files when Windows File Explorer is called to open. What happens if you turn it on then open Windows File Explorer.

**Comment by yaira2** [comment]
I think we can call this a side effect, the experimental feature is primarily designed for Administrator accounts. I've seen it working on non admin accounts but there are different factors that can affect this and it's hard to know what it is.

**Comment by JackGFuller** [comment]
Thanks for the thread. I suppose this is one of the perils of an Experimental Feature. However, Without this capability, there doesn't seem much that Files offers that isn't already in File Explorer, now that FE has tabs.
________________________________

**Comment by yaira2** [comment]
Thank you for the feedback, there are a number of features Files offers that File Explorer doesn't (such as tags, dual pane, column layout, custom themes, Git integration, hashes page in the Properties window etc) but we encourage feedback if you have ideas.

**Comment by JackGFuller** [comment]
Haven't had much need for dual pane. But one feature I do like is the display of the size of a Folder. FE only shows the size when hovering over the FolderName - not as convenient.

It's been 50 years since I wrote a line of code, and that in PL/I, a mainframe language forgotten by most. So I speak from ignorance as to the effort needed to have Files be the default file manager. But that certainly would be a "Nice to have"! I'd sign up for sure.
________________________________

**Comment by yaira2** [comment]
@JackGFuller if you pin Files to the taskbar, you can use `win` + `1` or whichever number corresponds to its position in the taskbar to launch it.
