### ISSUE TITLE
Add option to export\import settings

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#1260]
**Is your feature request related to a problem? Please describe.**
Not really. Many users use multiple Windows devices and it'd we really useful to sync settings with their Microsoft account.

**Describe the solution you'd like**
Use RoamingSettings for storing settings instead of LocalSettings (only app settings not pinned folders).

**Describe alternatives you've considered**
None.

**Comment by duke7553** [comment]
@Jaiganeshkumaran IIRC RoamingSettings is being deprecated.

**Comment by Jaiganeshkumaran** [comment]
How about using the Apps folder in OneDrive for storing settings. Microsoft's own apps like Office Lens and Fresh Paint use the apps folder for storing and syncing.

**Comment by merwie** [comment]
it would be nice if you could save your settings in one drive so when you install it on a new pc it could auto-sync :D

**Comment by crashmit** [comment]
I really want this feature too! Hope it gets moved to to-do soon :)

**Comment by d2dyno1** [comment]
@yair100 need a design spec for export/import buttons.

**Comment by yair100** [comment]
> @yair100 need a design spec for export/import buttons.

I think a simple section with two buttons added to the about page can do the job, adjusting the UI afterwards shouldn't be too hard.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #6542.
