### ISSUE TITLE
Feature: Rename "Mica Alt" to just "Mica"

### ISSUE THREAD

**Issue by mdtauk** [files-community/Files#12600]
### Description

On the settings screen, the dropdown with Acrylic and Mica Alt as the options, this should use the wording **Mica** even though internally we know it uses Mica Alt.

It would make it simpler for the User to understand by keeping it simple, and not use internal "developer" wording.

### Steps To Reproduce

1. Open Settings
2. Go to Appearance
3. Open the "Backdrop Material" DropDown options

### Requirements

- Reconsider the wording to be more user friendly.
- Avoid anyone asking what Mica Alt is, and where is Mica

### Files Version

2.5

### Windows Version

Windows 11 (22H2): 22621

### Log File

N/A

**Comment by yaira2** [comment]
Fyi @Ferrario-Filippo

**Comment by heftymouse** [comment]
@mdtauk What about in the future, when the option to use Mica non-alt is enabled?

**Comment by heftymouse** [comment]
I agree, but it'd be good to offer that flexibility for people looking to theme the app - same story as acrylic

**Comment by yaira2** [comment]
Regular mica makes sense when users make the other layers transparent.

**Comment by Jay-o-Way** [comment]
@mdtauk is there official statement from Microsoft about this? Also check out the linked issue. It would be **extra** confusing if we say "mica" but use "mica alt".

**Comment by mdtauk** [comment]
> @mdtauk is there official statement from Microsoft about this? Also check out the linked issue. It would be **extra** confusing if we say "mica" but use "mica alt".

The Material is Mica, and the alt form was created to allow tabbed interfaces to have good contrast.  It is not a separate kind of material.

Microsoft doesn't really have the options to choose a surface for the user, so its a technical distinction, rather than a user facing one.

**Comment by yaira2** [comment]
@heftymouse are you planning to enable regular mica?

**Comment by heftymouse** [comment]
I'm planning on doing it as a part of the upcoming code jam

**Comment by heksesang** [comment]
> @mdtauk is there official statement from Microsoft about this? Also check out the linked issue. It would be **extra** confusing if we say "mica" but use "mica alt".

The naming convention draws a parallel to font names. Internally, "Arial Regular" and "Arial Bold" are two different fonts in a font family, but you'd usually only expose the name "Arial" (the name of the font family) to the user in an application. The same applies to "Mica" - internally there exists two variants of the material which have two different technical purposes, but they are grouped together under the material name "Mica" when exposed to the user.

Which is why referring to "Mica alt" at all in the settings is a really bad idea. It will only cause confusion for the users.

**Comment by yaira2** [comment]
We're planning to add an option for regular "Mica" as well so we won't be making this change.

**Comment by mdtauk** [comment]
> We're planning to add an option for regular "Mica" as well so we won't be making this change.

That is going to cause some issues with accessibility and contrast ratios with the TabView controls

**Comment by Jay-o-Way** [comment]
Yeah I would advice against that @yaira2
Check out https://learn.microsoft.com/en-us/windows/apps/design/style/mica#app-layering-with-mica-alt

**Comment by yaira2** [comment]
We advise against using acrylic, but it turns out that this type of customization is extremely popular with users, so we added the option. I wouldn't recommend someone use regular "mica", but it makes sense if the user made the content layer transparent.

**Comment by mdtauk** [comment]
> We also advise against using acrylic, but it turns out that this type of customization is extremely popular with users, so we added the option. I wouldn't recommend someone use regular "mica", but it makes sense if the user made the content layer transparent.

But Acrylic and Mica are the two materials Windows uses for apps (smoke is also a material but only used for content dialogs)

Mica Alt is just there to ensure good contrast for tab scenarios.

We should offer Acrylic, Mica, and Solid - and not differentiate between Mica and MicaAlt

**Comment by yaira2** [comment]
This is missing the point that there are use cases for having both Mica Alt and Mica. If we rename Mica Alt to just Mica, we won't be able to add the option for regular Mica.

**Comment by mdtauk** [comment]
> This is missing the point that there are use cases for having both Mica Alt and Mica. If we rename Mica Alt to just Mica, we won't be able to add the option for regular Mica. We could do this if that's what the community wants but it'll mean less customization.

I don't think Mica should be an option.  It would cause problems with the TabView control.  So the user can choose Mica or Acrylic - and they get Mica Alt, because of the tab control.
