### ISSUE TITLE
Feature: Add splash screen on startup

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#12615]
### What feature or improvement do you think would benefit Files?

Ideally there wouldn't be a need for a splash screen but the reality is that the app can take a few seconds to load. A splash screen can help reassure users that the app is loading.

### Requirements

- Add splash screen on startup
- Display progress ring
- Display app logo

### Files Version

v2.5.1

### Windows Version

Windows 11 (22H2): 22621

**Comment by 0x5bfa** [comment]
Can I work on it? It should be easy work; how come did you add https://github.com/files-community/Files/labels/help%20wanted label?

**Comment by mdtauk** [comment]
There is guidance on handling Splash Screens - and the focus should probably be on ensuring the screen is displayed as quickly as possible for performance reasons.

![image](https://github.com/files-community/Files/assets/7389110/a953f4ed-79b2-4b75-9885-2815dce09c32)

**Comment by 0x5bfa** [comment]
What the hell. 

They doesn't support SplashScreen in WinUI3/WASDK.

- `https://github.com/microsoft/microsoft-ui-xaml/issues/4055`
- `https://github.com/microsoft/microsoft-ui-xaml/issues/6942`

**Comment by mdtauk** [comment]
With WinUI 3 and WinAppSDK - you need to make a custom splash screen, and display it whilst the UI loads.

With WinUI 2 and UWP its built into the plaform.

**Comment by 0x5bfa** [comment]
Oh, I have an experience of making custom splash screen, adding progressring. Let me see what I can do.
