### ISSUE TITLE
Startup Setting Ignored if Files Not Closed Before PC Shutdown

### ISSUE THREAD

**Issue by HobbesKo** [files-community/Files#12619]
### Description

`Continue where you left off` startup setting is ignored if Files is not closed before shutting down the PC.
On reboot, Files will open to the 'Home' page.
The startup setting works fine if Files is closed before shutting down the PC.

### Steps To Reproduce

1. Set startup setting to `Continue where you left off`
2. Leave Files running
3. Shut down PC

### Requirements

Files should remember the startup setting on PC reboot. It should make no difference whether Files is running or closed before  shutting down the PC.

### Files Version

2.5.0.0

### Windows Version

Windows 11 (22H2): 22621

### Log File

[debug.log](https://github.com/files-community/Files/files/11755051/debug.log)

**Comment by Josh65-2201** [comment]
This also can be reproduce if the user signs out or with certain crashes. (No notification for these crashes, the window will just close.)

**Comment by yaira2** [comment]
This is currently the way the feature is intended to work, can you please open a feature request so we can track support for detecting shutdown?
