### ISSUE TITLE
Code Quality: Use thread-safe collections if accessed by multiple threads

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#12617]
### Description

Currently there are some properties using non-thread-safe collections. They may be accessed by multiple threads and cause unexpected errors if those elements can change. These should be replaced with thread-safe collections such as `BlockingCollection` and `ConcurrentDictionary`.

### Concerned code

Collections accessed by multiple threads and whose elements can change

### Gains

Avoid unexpected behavior and crashes.

### Requirements

They should be replaced with thread-safe collections such as `BlockingCollection` and `ConcurrentDictionary`.

**Comment by yaira2** [comment]
Do you want to work on this?

**Comment by hishitetsu** [comment]
> Do you want to work on this?

Yes, but it will take quite a bit of time.

**Comment by hishitetsu** [comment]
Close since it appears that crashes due to not being thread-safe no longer occur.
