### ISSUE TITLE
Bug: Folder is empty after canceling a search

### ISSUE THREAD

**Issue by IlyaSulli** [files-community/Files#12612]
### Description

When you press the back button, after a search results, results in it saying that the folder is empty.

### Steps To Reproduce

1. Go to Downloads through quick access sidebar
2. Search test
3. Press enter
4. Press the back button

### Requirements

Should result in going back to root folder

### Files Version

Version 2.5.1.0

### Windows Version

Windows 11 Insider: 23xxx series

### Log File

[debug.log](https://github.com/files-community/Files/files/11750558/debug.log)

**Comment by IlyaSulli** [comment]
Update: It isnt just when you go back, it also says that the folder is empty if you select a folder from the quick access sidebar after completing a search

**Comment by Josh65-2201** [comment]
Thanks for making the report, I have added it to the project board

**Comment by yaira2** [comment]
Thank you for reporting this issue, it'll be fixed in the next release.
