### ISSUE TITLE
Bug: Crash when opening highlighted folder in new tab

### ISSUE THREAD

**Issue by x3rt** [files-community/Files#12613]
### Description

Majority of the time when opening a highlighted/selected folder via middle-mouse button or triple finger tap on a trackpad, Files crashes 

### Steps To Reproduce

1. Select/Highlight a folder
2. Press Middle mouse to open in new tab
3. 50% chance of it (Files) crashing 

https://github.com/files-community/Files/assets/51767230/f1464975-2971-47eb-8a41-02a35a8174d8
In the video I did the same exact thing twice, but only one of those times did it crash.

### Requirements

Fix the crash that happens whenever a highlighted folder is opened in a new tab via middle mouse (This does not seem to happen via the context menu)

### Files Version

Version 2.5.1.0 

### Windows Version

Windows 11 (22H2): 22621

### Log File

[debug.log](https://github.com/files-community/Files/files/11750849/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report.

**Comment by yaira2** [comment]
I was able to repro this issue as well.
