### ISSUE TITLE
TreeView Glyph on the left navigation pane

### ISSUE THREAD

**Issue by EpGithub22** [files-community/Files#12611]
### What feature or improvement do you think would benefit Files?

thanks for releasing version 2.5, the appearance is okay, but there is still no glyph for folder tree in the left navigation pane, this is very important from my point of view, hopefully we can see that in the next version.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

Files version 2.5 June.2023

### Windows Version

Windows 11 (22H2): 22621

### Comments

I am using Windows 11 insider preview Beta Channel build 22631.1835

**Comment by yair100** [comment]
@EpGithub22 Tree View is currently available in preview https://files.community/download. It will be included in the next stable release.
