### ISSUE TITLE
PDF files missing pages in Preview Pane

### ISSUE THREAD

**Issue by enricodarodda** [files-community/Files#12623]
### Description

When I open a PDF in the Preview pane, I can only go through some of the pages, NOT all of them; the problem is that it stops after the tenth page of several files, is that on purpose?

### Steps To Reproduce

1. Enable the Preview Pane
2. Select a PDF file, so that it gets opened in the preview pane
3. Swipe the pages up to the end, it will stop before the end

### Requirements

- e.g. Fix PDFs display feature that occurs when you select a PDF and gets opened in the Preview Pane

### Files Version

2.5.0.0

### Windows Version

Windows 10 (22H2): 19045

### Log File

[debug.log](https://github.com/files-community/Files/files/11758684/debug.log)

**Comment by yaira2** [comment]
Thank you for the feedback, this is indeed for performance reasons. For a richer preview, we recommend using QuickLook or SeerPro which can preview files with the press of the space bar.
