### ISSUE TITLE
Sort files by lenght

### ISSUE THREAD

**Issue by moray33** [files-community/Files#12627]
### What feature or improvement do you think would benefit Files?

Hello. A feature that I'm missing is sorting video and audio files by lenght. It would be very handy for me.

Thank you.
Kind regards.

### Requirements

Sort video and audio files by lenght.

### Files Version

2.5

### Windows Version

Windows 10 (22H2): 19045

**Comment by gave92** [comment]
Thanks for the feedback. Merging with #8366.
