### ISSUE TITLE
Bug: Application hang when dragging file onto a tab/folder which contains existing file with same name 

### ISSUE THREAD

**Issue by hawkerm** [files-community/Files#12637]
### Description

Seems like a timing/threading issue maybe?

Was able to replicate the issue by acting very quickly

Seems like a problem around the conflict dialog:

![image](https://github.com/files-community/Files/assets/8959496/5c0169d1-1d84-4b0d-ac69-8f30c596f86d)

### Steps To Reproduce

1. Open a folder 'A' that contains a file like `test.txt`
2. Open another tab
3. Navigate to a 2nd folder 'B' that also contains a file named `test.txt`
4. Go back to the first tab
5. Drag the file `test.txt` on top of the tab for folder 'B'
6. Let go of the mouse pointer **right away**...
7. Observe application hangs (sometimes before the conflict dialog appears, sometimes after), after a while it'll close as UWP apps do.

If no hang was observed, you were too slow to drag and let go of pointer before tab switched.

![image](https://github.com/files-community/Files/assets/8959496/baefa85d-2e4f-4b15-9db3-7add6de32d97)

### Requirements

App should not hang, operation to resolve conflict should proceed as normal

### Files Version

2.5.0.0

### Windows Version

Windows 10 (22H2): 19045

### Log File

[debug.log](https://github.com/files-community/Files/files/11777810/debug.log)

**Comment by yaira2** [comment]
@hawkerm thank you for reporting this issue, I added it to the project board.

**Comment by hawkerm** [comment]
No problem, not sure if related or different (don't have a solid repo), but do notice more instability just switching between folder tabs quickly, so maybe has to do more generally with pending operations and tab switching?

**Comment by yaira2** [comment]
I'm seeing a bunch of COM Exceptions in the log file but it seems to be related to `ListRecentFoldersAsync`, I'm not sure where the conflicts dialog is coming into play 🤔

**Comment by yaira2** [comment]
@hawkerm can you check if this was resolved in v2.5.21?
