### ISSUE TITLE
Add bulk filename change

### ISSUE THREAD

**Issue by ivellios1988** [files-community/Files#12634]
### What feature or improvement do you think would benefit Files?

I noticed Files doesn't let me change names of multiple files at once. I would really appreciate if you add this functionality.

### Requirements

This proposal will add the functionality of bulk filename change in Files.

### Files Version

2.5.1.0

### Windows Version

Windows 10 (22H2): 19045

**Comment by Josh65-2201** [comment]
Thanks for the feedback, can you confirm if this is the same as #8191.

**Comment by yaira2** [comment]
In the meantime, I suggest using PowerToys. It has a shell extension for bulk name and it's a very good tool.

**Comment by ivellios1988** [comment]
> Thanks for the feedback, can you confirm if this is the same as #8191.

Yeah, it's the same. Thanks for mentioning this, for some reason I didn't find this issue.
