### ISSUE TITLE
Mica thematic anomaly

### ISSUE THREAD

**Issue by oxc-v** [files-community/Files#12638]
### Description

![image](https://github.com/files-community/Files/assets/59563828/f5c7bd67-0597-4e3d-a746-1e5e05c2eeaa)
The color scheme of this theme is a bit strange, unlike the normal mica effect

### Steps To Reproduce

![image](https://github.com/files-community/Files/assets/59563828/8b272d5e-a37a-42f4-a569-ea469e1769e7)

### Requirements

- 

### Files Version

2.5.1.0

### Windows Version

Windows 11 (22H2): 22621

### Log File

[debug.log](https://github.com/files-community/Files/files/11778048/debug.log)

**Comment by Josh65-2201** [comment]
That looks normal since it a dark Windows background you are using. What are you trying to do?

**Comment by oxc-v** [comment]
![image](https://github.com/files-community/Files/assets/59563828/f5bd6932-5174-4f03-9939-ebc5c6319b55)
This is a windows system application, I think this tone is normal

**Comment by Josh65-2201** [comment]
You have the glass theme in the settings file. You can remove the `#0000001` values to return to normal.

**Comment by heftymouse** [comment]
@oxc-v It's because Files uses Mica Alt, not regular Mica like most apps. This is because it's the recommendation for apps that use tabs, but we may add the option to use regular Mica in the future.

**Comment by oxc-v** [comment]
Well, why isn't the TAB color for this theme highlighted
![image](https://github.com/files-community/Files/assets/59563828/618c8362-34bf-4ffa-9c5d-8718dafcb931)

**Comment by oxc-v** [comment]
![image](https://github.com/files-community/Files/assets/59563828/7d97992a-f7e8-4020-826d-8ea1da1bab04)
![image](https://github.com/files-community/Files/assets/59563828/83199197-c11c-4095-a935-9c91f57ba491)

Well, why isn't the TAB color for this theme highlighted and doesn't look layered

**Comment by Josh65-2201** [comment]
The theme is suppose to look like that as you made it all transparent. You can change the last two numbers of `AppThemeAddressBarBackgroundColor` using the HEX format to increase opacity.

**Comment by Jay-o-Way** [comment]
X-ref #12600

**Comment by yaira2** [comment]
@oxc-v thank you for the feedback, Files uses Mica Alt to provide extra contrast between the tabs and content. We're tracking support for regular Mica in #12600.
