### ISSUE TITLE
3 more options on the top ribbon bar

### ISSUE THREAD

**Issue by onlytanmoy** [files-community/Files#12635]
### What feature or improvement do you think would benefit Files?

Great app as replacement of default win explorer, many thanks!

Just got one feature request, will it be possible to add the below options on the ribbon bar on the top?

- Copy Path
- Move To
- Copy To

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.5.1.0

### Windows Version

Windows 11 (22H2): 22621

**Comment by yaira2** [comment]
Thank you for your feedback, while we don't have plans to add these to the toolbar, we're working on a command palette and keyboard shortcuts which will make it easier to access these options.
