### ISSUE TITLE
Feature: Add support for setting a background image for the app

### ISSUE THREAD

**Issue by onlytanmoy** [files-community/Files#12636]
### What feature or improvement do you think would benefit Files?

Hiya, please add option in the Appearance section of the settings to add custom image as background.

### Requirements

- Add combo box with sub options "Image" and "None"
- Include sub setting to select image source
- Include sub setting to change transparency
- Include sub setting to choose image placement

### Files Version

2.5.1.0

### Windows Version

Windows 11 (22H2): 22621

**Comment by yaira2** [comment]
@onlytanmoy thank you for your feedback, are there any other options you think should go together with this? For example, changing the image transparency so that the mica/acrylic backdrop is visible...

**Comment by onlytanmoy** [comment]
@yaira2 I am glad you liked this suggestion. I can think of two options for now:
a. Controlling the image transparency as you already mentioned 
b. Have the image source pointed to some folder containing multiple wallpapers for daily auto change of background or a defined rotation frequency like hourly etc.

**Comment by kafuuchinolpx** [comment]
> @yaira2 I am glad you liked this suggestion. I can think of two options for now: a. Controlling the image transparency as you already mentioned b. Have the image source pointed to some folder containing multiple wallpapers for daily auto change of background or a defined rotation frequency like hourly etc.

How to point to image source

**Comment by yaira2** [comment]
We're actively working on this feature and progress can be followed in #15290.
