### ISSUE TITLE
Feature: Add open in vs code/studio button to the status bar

### ISSUE THREAD

**Issue by VasigaranAndAngel** [files-community/Files#12632]
### What feature or improvement do you think would benefit Files?

it will be nice if a button in the details layout opens the git folder in vs code. and a button that opens the folder in Visual Studio if the folder has a solution file.

![image](https://github.com/files-community/Files/assets/72515046/1b6f566d-a7f9-4574-9b2f-d1a320535efa)

### Requirements

- Add open in vs code button to status bar for git repos
- Add open vs studio button instead if there is a sln file in the directory
- The buttons should only be visible if the respective app is installed

### Files Version

Version: 2.5.1.0

### Windows Version

Windows 11 (22H2): 22621

### Comments

Using a json configuration file to configure the rules(if the folder has a specific file type or something) and buttons(open the folder with a specific application) would be more customizable and awesome.
But I'm not sure about this idea. it would be complicated or problematic.

**Comment by yaira2** [comment]
Thank you for the feedback

**Comment by ferrariofilippo** [comment]
I started working on this

![image](https://github.com/files-community/Files/assets/102259289/b6cc9895-cfe5-4359-bd54-f5de362f9e1c)

**Comment by yaira2** [comment]
@mdtauk should we use a generic icon for this or is it better to use the actual icons?

**Comment by mdtauk** [comment]
Is VS Code the only handler for git?

What about GitHub Desktop?

Do we want to include a setting for choosing a Git handler app to appear on any context menu or future Git flyout?

If there is a handler then the app icon would be appropriate, but not sure about it being on the status bar

**Comment by yaira2** [comment]
> Do we want to include a setting for choosing a Git handler app to appear on any context menu or future Git flyout?

Not right now, the button will show VS Studio for sln projects and VS Code for everything else.

**Comment by ferrariofilippo** [comment]
I think we should use the actual icons

**Comment by VasigaranAndAngel** [comment]
Coool
