### ISSUE TITLE
Use Central Package Management

### ISSUE THREAD

**Issue by heftymouse** [files-community/Files#12642]
### Description

Central Package Management is a NuGet/MSBuild feature where through a `Directory.Packages.props` file package versions can be synced across multiple projects.

### Concerned code

All

### Gains

This is useful for avoiding issues that may arise from having different versions of packages like WinAppSDK and MVVM Toolkit.

### Comments

https://devblogs.microsoft.com/nuget/introducing-central-package-management/

**Comment by yaira2** [comment]
Thank you for the feedback, do you want to work on this?

**Comment by heftymouse** [comment]
Sure
