### ISSUE TITLE
Can't install the app

### ISSUE THREAD

**Issue by Mason-17** [files-community/Files#12646]
### Description

I can't install the app from the classic installer. When I try, it says:
```Install Failed. Please contact your software vendor. (0x80073CF9)```

I've tried solving this using various methods online, but none of them have solved the issue. 

### Steps To Reproduce

1. Download classic installer.
2. Run classic installer.
3. Failure + Error.

### Requirements

Classic installer should just install the app. It seems to be integrating with the Microsoft Store which is odd. 

### Files Version

2.5.1.0

### Windows Version

Windows 10 (22H2): 19045

### Log File

There is no log file

**Comment by yaira2** [comment]
Thank you for the feedback, the classic installer requires the Windows Update service as well as a couple of others. Are you by any chance using a modified version of Windows?

**Comment by Mason-17** [comment]
Thank you for the quick response. No, I'm not. If you're referring to the update service for the Store, I already made sure it was there I'm pretty sure, but I'm willing to follow any instructions you may have for making sure it is up and running.

**Comment by Josh65-2201** [comment]
You can try
1. Opening PowerShell as administrator
2. Run this command
```Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/stable/Files.Package.appinstaller```

**Comment by Mason-17** [comment]
@Josh65-2201 this worked. I notice that the command above downloads a different file than the one provided on the website. I used this app about a year ago and remember it being a .appinstaller file, similar to the preview.

**Comment by Josh65-2201** [comment]
It was change to a custom installer due to the unreliability of app installer. Not sure what the issue you were having was though.

**Comment by Mason-17** [comment]
I don't know either, I stayed up all night last night trying to figure it out. When the app gets an update, do I have to run the command again? Or does the app have an update feature built-in?

**Comment by Josh65-2201** [comment]
It has auto update. Not sure if it will work or not.

**Comment by yaira2** [comment]
Auto update will likely work if you got the app to install.

**Comment by AceidicDawn** [comment]
Just wanted to chime in on this and say i was having the same issue yesterday, and ended up calling it a night before figuring it out, never found out why it was happening but thanks for the fix on here.

**Comment by simplg** [comment]
Same bug for me, had to use the powershell command to install it. Windows 10 Pro 22H2 19045.3086

**Comment by tomasklaen** [comment]
Same issue (Win10 22H2 19045), not so lucky with the powershell alternative, which produced this error:

```
Add-AppxPackage : Deployment failed with HRESULT: 0x80073CFB, The provided package is already installed, and reinstallation of the package was blocked. Check the AppXDeployment-Server event log for details. Deployment of package Microsoft.WindowsAppRuntime.1.3_3000.882.2207.0_x64__8wekyb3d8bbwe was blocked because the        provided package has the same identity as an already-installed package but the contents are different. Increment the version number of the package to be installed, or remove the old package for every user on the system before installing this package.
NOTE: For additional information, look for [ActivityId] 52306536-b638-0003-3b2a-315238b6d901 in the Event Log or use
the command line Get-AppPackageLog -ActivityID 52306536-b638-0003-3b2a-315238b6d901
At line:1 char:1
+ Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/s ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceExists: (https://cdn.fil...ge.appinstaller:String) [Add-AppxPackage], PSInvalidO
   perationException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand
```

It obviously complains about already being installed, but I don't see it in installed programs, or windows store installed apps, and doesn't even pop up in start menu, so no idea how to remove it.

**Comment by Josh65-2201** [comment]
The error is not about Files but about Windows app runtime. Go to Settings > Apps > Installed apps > Search for `Windows App Runtime` and uninstall all the ones shown then retry

**Comment by tomasklaen** [comment]
Can't see that in neither the control panel:

![image](https://github.com/files-community/Files/assets/47283320/4f79fe45-fe84-4699-ae32-a853926a9f96)

nor the windows settings:

![image](https://github.com/files-community/Files/assets/47283320/4ac59ef7-31c5-4b1d-89f1-5b6297b28cfb)

Same for files.
