### ISSUE TITLE
Homescreen refresh bug

### ISSUE THREAD

**Issue by Suchan7820** [files-community/Files#12640]
### Description

Files app(tab) opened in the same form do not measure changed storage capacity on the home screen. 
Also, the Refresh button doesn't work on the home screen.

https://cdn.discordapp.com/attachments/1119504351036186727/1119560646284021780/ordinary.mp4

### Steps To Reproduce

1.Open Files app
2.Change storage capacity somehow

### Requirements

- e.g. Fix crash that occurs when...
- always

### Files Version

Stable 2.5.1.0

### Windows Version

Windows 11 (22H2): 22621

### Log File

[debug.log](https://github.com/files-community/Files/files/11778490/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I have added it to the project board.

**Comment by yaira2** [comment]
Thank you for the feedback, we're currently tracking this request in #6182.
