### ISSUE TITLE
タグ機能

### ISSUE THREAD

**Issue by XERE** [files-community/Files#12643]
### What feature or improvement do you think would benefit Files?

タグの機能にとても関心しているが。ファイル名などから適切なタグを自動でつけてくれるっていうことができたらいいかも

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.5.1.0

### Windows Version

Windows 11 Insider: 25xxx series, Windows 11 Insider: 23xxx series

### Comments

よろしくお願いいたします

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #11992. You can check there or click subscribe in the right sidebar for updates.
