### ISSUE TITLE
Issue with File Details Not Displaying Properly in Preview Mode

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12649]
### Description

I previously reported an issue regarding the display of file details not appearing properly when switching from preview mode to details mode. I was informed that this problem would be resolved, but unfortunately, it is still persisting. Specifically, when I switch from preview mode to details mode, no details are displayed. I have to navigate to another folder and return to view the details.

### Steps To Reproduce

https://github.com/files-community/Files/assets/128183422/4ddffc2e-7297-44a0-b79b-255213df21a1

### Requirements

Identify the cause of the file details not being displayed correctly during the switch from preview mode to details mode.

### Files Version

Version 2.5.1.0

### Windows Version

22H2 22621.1848

### Log File

[debug.log](https://github.com/files-community/Files/files/11784374/debug.log)

**Comment by Lukiluc29** [comment]
I tested with several other file types (jpeg, png, pdf...) but the error remains the same.

**Comment by Lukiluc29** [comment]
> Is this only in the columns layout?

No, in all the others too

**Comment by yaira2** [comment]
I can't reproduce this in `main` (we've made some improvements in this area). Please let us know if it's still an issue by the time the next update is released and we'll reopen this issue.

**Comment by Lukiluc29** [comment]
@yaira2 This problem still persists
