### ISSUE TITLE
Working With Images

### ISSUE THREAD

**Issue by AYHJA** [files-community/Files#12654]
### Description

Most of the time when I'm using Files, it crashes when I'm working with images.

### Steps To Reproduce

1. Open any folder with multiple images.

### Requirements

- e.g. Fix crash that occurs when...
You load a folder that has more images than can be displayed on screen without scrolling. I have one panel open and the display properties panel. 

### Files Version

2.5.1.0

### Windows Version

10.0.22621.1848

### Log File

[debug.log](https://github.com/files-community/Files/files/11792865/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report.

**Comment by AYHJA** [comment]
Yes, and since I posted the report I have viewed a folder with as few as 6 images (but all fairly large files, 7MB>) so maybe that's a part of it. I'd be more than happy to submit more information if needed. Just let me know if I can help. Files is awesome.

**Comment by yaira2** [comment]
@AYHJA is this still an issue in v3.0.5? If it's still occurring, please upload the updated log file.
