### ISSUE TITLE
Add Navigation Pane "Expand to Open Folder" Feature

### ISSUE THREAD

**Issue by NeArnold** [files-community/Files#12653]
### What feature or improvement do you think would benefit Files?

I would like "Expand to open Folder" to work in each tab, such that if I switch tabs the Navigation Pane will display the folder tree down to highlighting the current folder.

### Requirements

Messaging to the Navigation pane on folder and tab changes.

### Files Version

2.5.1.0

### Windows Version

Edition	Windows 10 Pro Version	22H2 Installed on	‎4/‎20/‎2020 OS build	19045.3086 Experience	Windows Feature Experience Pack 1000.19041.1000.0

**Comment by Josh65-2201** [comment]
Thanks for the feedback, is this the same as #1928?

**Comment by yaira2** [comment]
It's not exactly the same but we're tracking all tree view related requests there.
