### ISSUE TITLE
Bug: Item names in Tags widget don't have ellipsis even when trimmed

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#12650]
### Description

As the title described. Furthermore, no tooltips are displayed, so the full file name is not known.
![image](https://github.com/files-community/Files/assets/66369541/e1b832a2-913d-4635-a5a2-af4b02015c44)

### Steps To Reproduce

1. Enable Tags widget.
2. Tag an item with a long name.
3. Open the home page.
4. The item name doesn't have ellipsis.

### Requirements

- Item names in Tags widget should have ellipsis if trimmed.
- The path of the file should be displayed in a tooltip like Recent files widget.

### Files Version

2.5.1.0

### Windows Version

10.0.22621.1848

### Log File

n/a

**Comment by yaira2** [comment]
Thank you for reporting this issue.
