### ISSUE TITLE
Connecting an iPhone does not open Files 

### ISSUE THREAD

**Issue by elixss** [files-community/Files#12663]
### Description

Connecting a device (in my case an iPhone) opened Windows Explorer instead of Files, altough Files is set as default explorer in its advanced settings tab.

### Steps To Reproduce

1. connect an iPhone (I am not sure if this works with other devices)
2. Wait

### Requirements

I'd like Files to be opened instead of Windows Explorer. 

### Files Version

2.5.2

### Windows Version

Edition	Windows 11 Pro Version	22H2 Installed on	‎4/‎25/‎2023 OS build	22621.1848 Experience	Windows Feature Experience Pack 1000.22642.1000.0

### Log File

[debug.log](https://github.com/files-community/Files/files/11804832/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, the option to replace File Explorer has some limitations and doesn't cover all scenarios. If we find a way to do this, we'll make sure to add support.
