### ISSUE TITLE
Bug: Context menu is mising icon for "New shortcut"

### ISSUE THREAD

**Issue by IlyaSulli** [files-community/Files#12668]
### Description

When you right click on an image there is no icon, unlike other ones which makes it look weird
![image](https://github.com/files-community/Files/assets/81645040/606df8fe-f586-4a8e-bd79-48238e042ff0)

### Steps To Reproduce

1. Right click within a folder
2. Hover over New
3. (There isn't an icon associated with the shortcut button)

### Requirements

There should maybe be a white outline icon for a shortcut like the other ones above it within the same section

### Files Version

2.5.1.0

### Windows Version

10.0.23481.1000

### Log File

[debug.log](https://github.com/files-community/Files/files/11806039/debug.log)

**Comment by yaira2** [comment]
Thank you for reporting this, I can reproduce the issue as well.
