### ISSUE TITLE
Bug: Inaccurate Names in Preview Pane for "Network" and "Recycle Bin" Folders

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12669]
### Description

I have noticed an issue with the preview pane when opening the "Network" folder. Instead of displaying the correct name, it shows "Shell:NetworkPlacesFolder." Similarly, the same problem occurs with the Recycle Bin, where the folder is labeled as "Corbeille" but displayed as "Shell:RecycleBinFolder" in the preview pane.

### Steps To Reproduce

1. Go to either the "Trash" folder or the "Network" folder
2. Open the preview pane

### Requirements

Identify the cause of the incorrect names in the preview pane for the "Network" and "Recycle Bin" folders.

### Files Version

Version 2.5.2.0

### Windows Version

22H2 22621.1848

### Log File

![Capture d'écran 2023-06-20 193601](https://github.com/files-community/Files/assets/128183422/17a16873-6627-4e92-bcbe-b439a9b0e370)
![Capture d'écran 2023-06-20 194304](https://github.com/files-community/Files/assets/128183422/37cde361-5c95-4ad3-9f04-e901a8c275c6)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by Lukiluc29** [comment]
I just noticed that all the "This PC"
![Capture d'écran 2023-06-24 124534](https://github.com/files-community/Files/assets/128183422/fac6c428-77d9-474e-afaa-f5ba80c378fb)
 folder whose name also starts with "Shell:" has the wrong name.

**Comment by Lukiluc29** [comment]
After checking, I see that the issue has been resolved with the fix provided by hotfix #12866.
