### ISSUE TITLE
OneDrive

### ISSUE THREAD

**Issue by Stixz** [files-community/Files#12660]
### What feature or improvement do you think would benefit Files?

Would like to have the ability to have OneDrive integrated as it is on Windows File Manager.

### Requirements

- This proposal will accomplish having easy and ready access to OneDrive and it's contents.its

### Files Version

2.5.1.0

### Windows Version

22H2

**Comment by yaira2** [comment]
Thank you for your feedback, Files has full support for OneDrive built in. Do you see OneDrive in the sidebar?

**Comment by Stixz** [comment]
No, I don't have it there.?.

**Comment by Stixz** [comment]
NM, I found it. Do you need me to remove the feature request?

Thanks for your help and a great app.!
