### ISSUE TITLE
Big directories crash

### ISSUE THREAD

**Issue by sdifiore** [files-community/Files#12666]
### Description

Every time I try to use it in a folder that has a high volume of files (although it might be size), it crashes.
It happened when I tried to copy a folder from a OneDrive to one in the SSD and now, just opening the pictures folder, with a large number of files, it just crashed upon entering it.
The picture folder has 20.428 files between its root and 23 others subfolders, per a total of 18.1 GB.
Also, when this happens it has to be reinstalled as whenever it opens it, it pops up as everything was ok and then crashes again.

### Steps To Reproduce

Just double click a folder a folder containing a large number of files, as stated previously, in my case there are 20.428 files between its root and 23 others subfolders, per a total of 18.1 GB.

### Requirements

- Not allowing to crash when handling a folder with a high number of files (size?)

### Files Version

2.5.2.0

### Windows Version

Windows 11 Home 22H2 22621.1848 with Windows Feature Experience Pack 1000.22642.1000.0 and configured for development

### Log File

Please, notice that I had to reinstall it and the previous one was removed with Revo Uninstaller Pro, and I can't guarantee that the data here belongs to the version that actually crashed.

[debug.log](https://github.com/files-community/Files/files/11805181/debug.log)

**Comment by yaira2** [comment]
Thank you for reporting this issue, I don't see anything in the log file from the crash. Can you try to repro the issue again and see if it shows up in the logs?

**Comment by yaira2** [comment]
@sdifiore can you try to reproduce this issue again?
