### ISSUE TITLE
Bug: Opening "Network," "Recycle Bin," or "This PC" locations crashes app

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12664]
### Description

I've encountered an issue where clicking on the "Network", "Recycle Bin", or "This PC" folders, whether through the navigation bar for "Network" or using shortcuts on the desktop or elsewhere, results in Files crashing and becoming unresponsive. I've noticed that this problem occurs exclusively in the column view. Until this issue is resolved, I've found a workaround, which is to pin these folders to favorites.

### Steps To Reproduce

1. Open Files
2. Set Files as default
3. Synchronize column mode in settings
4. Unpin Recycle Bin from the sidebar
5. Close Files
6. Open Recycle Bin from the desktop

### Requirements

Investigate and identify the root cause of the crashing issue when accessing "Network", "Recycle Bin", or "This PC" folders.

### Files Version

Version 2.5.2.0

### Windows Version

22H2 22621.1848

### Log File

[debug.log](https://github.com/files-community/Files/files/11804866/debug.log)

**Comment by sadamike** [comment]
I'm curious... What are the steps to even add it to Favorites?
- I can't find a way to navigate to the actual special shell object. It's not listed in Home.
- Putting C:\$Recycle.Bin or the "S-1-......." folder it contains into Favorites doesn't give full Recycle Bin functionality.
- Browsing to Shell:RecycleBin in the address bar gives an error: NotAFolder

**Comment by Josh65-2201** [comment]
Thanks for the report. The log file doesn't show any errors but your issue may be fixed when #12679 is.

**Comment by Lukiluc29** [comment]
@Josh65-2201 I just noticed that all the folders listed with names starting with "Shell:" never respond when launched, except if we add them to favorites.

**Comment by yaira2** [comment]
@Lukiluc29 do you have the option to sync folder preferences enabled?

**Comment by Lukiluc29** [comment]
> do you have the option to sync folder preferences enabled?

No.
