### ISSUE TITLE
Bug: Tags will not stay when used for files in a OneDrive Sync drive/folder

### ISSUE THREAD

**Issue by Garrieth** [files-community/Files#12665]
### Description

My tags stay on files/folders when they are on my local computer.
But the tags disappear on files/folders when they are in a synced folder using OneDrive Sync.

### Steps To Reproduce

1. Add tag to file/folder that is synced through OneDrive.
2. Open that tag feature. The file does not show.
3. Go back to the desired file/folder, and the tag removed itself. 

### Requirements

- e.g. Fix crash that occurs when...
using OneDrive Sync

### Files Version

2.5.1.0

### Windows Version

10.0.19045.3086

### Log File

[debug.log](https://github.com/files-community/Files/files/11804915/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report. Can you give the following information.
- Is your OneDrive sync location on a NTFS drive
- Do the tags stay if you add them when the sync client is closed.

**Comment by Garrieth** [comment]
Thank you for troubleshooting this.

 - Sorry, I am not sure what a NTFS drive is. Perhaps this would help: OneDrive Sync is syncing my company's folders from O365 SharePoint. Also, the OneDrive sync location is on one of my SSD drives. Not my regular hard drive, and not my M.2 SSD, just my regular SSD.
 - No, they still go away (just the ones from the synced folders, not tags from my local PC).

Much appreciated.

**Comment by Josh65-2201** [comment]
You can check if the drive is NTFS by right clicking it > Go to properties > Check file system on the 3rd line.
Can you add tags to a folder on the same drive outside of the OneDrive sync folder?

**Comment by Garrieth** [comment]
Oh okay yes it says 'File System: NTFS' for that SSD. 

Yes, the tags that I have working are also on that same SSD.

**Comment by Josh65-2201** [comment]
It may be an issue with your company not allowing the ADS files needed to save tags and they get removed when OneDrive sync the folder. Files cant currently do anything about that.

**Comment by Garrieth** [comment]
Gotcha, okay thanks.

**Comment by yaira2** [comment]
> It may be an issue with your company not allowing the alternate data stream files needed to save tags and they get removed when OneDrive sync the folder. Files cant currently do anything about that.

@Josh65-2201 is there a way we can try to reproduce this? We can try to detect this issue in the app and disable tags when it's not supported.

**Comment by yaira2** [comment]
> It may be an issue with your company not allowing the alternate data stream files

@Josh65-2201 can you clarify what you mean? Is there an option in OneDrive to disable ADS?

**Comment by Josh65-2201** [comment]
I've not use the company version of OneDrive/SharePoint so I can't be sure but I've seen others have issues with ADS files not staying with the business version and haven't with the personal version.

**Comment by Josh65-2201** [comment]
@Garrieth Can you see if the ADS files are shown in the OneDrive folder when you add a tag by going to Files settings > Folders > Hidden items > Show alternate data streams

**Comment by Garrieth** [comment]
Hey guys, thanks for checking it out. When I enable ‘Show ADS’, it says “Drive Unplugged”, all files disappear, and Files lags a bunch. When I disable it again, everything goes back to normal.  From: Josh65-2201Sent: Friday, September 29, 2023 6:25 AMTo: files-community/FilesCc: Garrieth; MentionSubject: Re: [files-community/Files] Tags will not stay when used for files in a OneDrive Sync drive/folder (Issue ***@***.*** Can you see if the ADS files are shown in the OneDrive folder when you add a tag by going to Files settings > Folders > Hidden items > Show alternate data streams—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by yaira2** [comment]
@Garrieth can you try enabling "Show ADS" again?

**Comment by Garrieth** [comment]
> @Garrieth can you try enabling "Show ADS" again in v3.0.8?

Sure thing. I am on v3.0.8 and have enabled "Show ADS". 
And it works now!! A file is created (it is faint though) with :files after it. But that is okay :) 
Cool, thanks!!

**Comment by yaira2** [comment]
Thanks! You can hide the alternate data streams again, that was just for testing purposes.
