### ISSUE TITLE
Feature: Add tooltips to Git columns

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#12675]
### What feature or improvement do you think would benefit Files?

Currently no tooltips appear in the Git column. If tooltips appear as needed, users can see more information.

### Requirements

Add tooltips to Git columns as follows:

| Column | Tooltip |
| --- | --- |
| Git status | Display full status name (e.g. Modified) |
| Commit sha | Display full hash value |
| Commit date, message, author | Display full value if trimmed |

### Files Version

2.5.2.0

### Windows Version

Windows 11 22H2

**Comment by yaira2** [comment]
Thank you for the feedback.
