### ISSUE TITLE
No puede abrir carpetas...

### ISSUE THREAD

**Issue by Antonel-Art** [files-community/Files#12678]
### Description

Trato de abrir ciertas carpetas pero entra en conflicto y se cierra inesperadamente... Un explorador de archivos que no puede explorar archivos?... Además al darle clic derecho a carpetas se demora mucho en responder ya que se tarde en leer "Mostrar más opciones" sería genial si la carga de esa opción se de cuando el usuario quiera acceder a esa opción y no sea una carga automática... En fin, ese detalle puedo soportarlo, pero el hecho que crashee cuando abro accesos directos del escritorio o cuando le doy clic con botón central del ratón para aperturar nueva pestaña es fatal... 

### Steps To Reproduce

1. clic medio en escritorio
2. error
3. se cierra el programa

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

2.5.2.0

### Windows Version

1000.22642.1000.0

### Log File

[debug.log](https://github.com/files-community/Files/files/11819057/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report. This issue is unclear to me. Is Files crashing when right clicking a media file or when you open a folder of media files? If it is the second what layout are you using for that folder?

**Comment by yaira2** [comment]
@Antonel-Art thank you for the report, the issue with middle clicking folders has been fixed in v2.5.10.
