### ISSUE TITLE
Bug: Extract compact file doesn't uncompress all files

### ISSUE THREAD

**Issue by Base-115** [files-community/Files#12672]
### Description

The feature to extract compact file doesn't work to all file inside compact folder.

Basically, the uncompress only effect the files that aren't media, video and audio files like MP4, MOV, WAV, AIF and still images like PNG.

Download to compact file that this problem happen (size: 15 GB): https://www.blackmagicdesign.com/dvres/editors-guide-resolve18

### Steps To Reproduce

1. Download compact file and save in User Download folder;
2. Go to the folder where the compact files was save;
3. In menu toolbar, click in "Extract";
4. In sub-menu that appear, click "Extract Files";
5. In the dialog box that spawn, click in "Extract".
6. Browser through the folder uncompressed.

Pay attention in the "Media" folder and their subfolders.

https://github.com/files-community/Files/assets/112908515/84d38a15-02fc-446f-ab2a-baa303a7d84d

### Requirements

It was expect that all item inside of folder would be uncompressed, in this case, mainly the videos, audios and images.

In this video, I extract the folder with feature embed in Windows Explorer and show the files that wasn't extract by Files.

https://github.com/files-community/Files/assets/112908515/65d0d5af-8c1e-4e84-a0a4-b377a61ad3a9

### Files Version

2.5.1.0

### Windows Version

10.0.19045.3086

### Log File

[debug.log](https://github.com/files-community/Files/files/11807784/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
@Josh65-2201 are you able to repro this?

**Comment by Josh65-2201** [comment]
Yes using the provided archive, seems to be media related files only.

**Comment by hishitetsu** [comment]
I've found the cause and am working to fix it.
