### ISSUE TITLE
Tile mode crash with many videos

### ISSUE THREAD

**Issue by AguilaDesign** [files-community/Files#12687]
### Description

To cut a long story short, when I open a folder with a large number of videos (+70), files crash constantly. I imagine this is due to the thumbnail generation that overloads the program, but that's just a hypothesis.

### Steps To Reproduce

Open a folder containing videos in tile mode.

### Requirements

The software does not crash when a folder full of videos is opened

### Files Version

2.5.1.0

### Windows Version

10.0.22621.1848

### Log File

[debug.log](https://github.com/files-community/Files/files/11833226/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report. I am unable to reproduce this, Can you give the following information.
- What layout are you using?
- Does it only happen in that layout?

**Comment by AguilaDesign** [comment]
Having tested the different views, it seems that the crash occurs on the views: tiles and grids, but not on columns and details. Which leads me to think that this is well and truly correlated to a thumbnails generation.

**Comment by Josh65-2201** [comment]
Thanks for testing, this seems to be the same as #12581 then.
