### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by vmachacek** [files-community/Files#12681]
### Description

When i replace the default windows app with Files and hit WIN + E it takes several times longer than windows native app. Is this something which is okay? I would like to use Files as much as possible, however this is not nice

### Steps To Reproduce

switch back and forth default app, than hit WIN + E

### Requirements

- make startup instant

### Files Version

2.5.2.0

### Windows Version

10.0.22621.1848

### Log File

[debug.log](https://github.com/files-community/Files/files/11821994/debug.log)

**Comment by vmachacek** [comment]
I think if WIN + E would bring into view existing instance that could mitigate the issue relatively well

**Comment by yaira2** [comment]
Thank you for your feedback, we're aware of the slow startup speed and it's something we're actively looking to resolve. We have some potential solutions that we're testing, and we hope to implement these improvements later this year.

**Comment by yaira2** [comment]
We're excited to share that startup performance will be significantly improved in the upcoming release of version 3. You can download the preview version from our website https://files.community/download.
