### ISSUE TITLE
crash on unc share access

### ISSUE THREAD

**Issue by gregclerk** [files-community/Files#12682]
### Description

crash on unc share access

### Steps To Reproduce

crash on unc share access

### Requirements

- e.g. Fix crash that occurs when...
crash on unc share access

### Files Version

2.5.1.0

### Windows Version

Win 11 22H2 22621.1848

### Log File

[debug.log](https://github.com/files-community/Files/files/11822108/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report.
- Can you fill out the steps to reproduce.
