### ISSUE TITLE
Feature: Update OneDrive status icons

### ISSUE THREAD

**Issue by mdtauk** [files-community/Files#12685]
### What feature or improvement do you think would benefit Files?

At present only the cloud storage folders display status icons.  With the addition of GIT support, icons should be added for these also.

This would replace the coloured letter that is currently used to maintain consistency, and avoid it looking like bad text rendering.

The icon should appear alone unless the status column is wide enough to display the text label also.

When icon only, the text should be in a tooltip

![image](https://github.com/files-community/Files/assets/7389110/a61ec3f8-4cd7-4649-847c-db40a5a9f406)
Icons are in the figma file, @yaira2 can provide them

### Requirements

- This proposal will bring consistency to file status across all parts of Files 

### Files Version

2.5

### Windows Version

Windows 11 release

**Comment by yaira2** [comment]
Thank you for your help on this, I added the icons to the app but the OneDrive status icons still need to be connected.
