### ISSUE TITLE
Show Multi-file size

### ISSUE THREAD

**Issue by IlyaSulli** [files-community/Files#12680]
### What feature or improvement do you think would benefit Files?

When you select multiple files and folders, it should calculate the storage size (It currently doesn't show within the properties menu)
![image](https://github.com/files-community/Files/assets/81645040/09e62a11-b405-434b-a7e6-193d5e731d86)

### Requirements

Not sure...

### Files Version

2.5.2.0

### Windows Version

10.0.23481.1000

**Comment by Josh65-2201** [comment]
Thanks for the feedback. I am unable to reproduce this, Can you give the following information.
- Were are the file/folders located (local drive, network, cloud storage etc.)

**Comment by Lukiluc29** [comment]
#12664 I encountered the same problem but when I put it in my favorites bar it does not crash
