### ISSUE TITLE
I love Files, but it's so slow I can't use it

### ISSUE THREAD

**Issue by ryder203** [files-community/Files#12696]
### Description

Windows 11 File Explorer is slow. On Windows 10 it is so damn fast... but "Files" on Windows 11 is even more slow than the File Explorer. Don't know why, but it takes 2 seconds to open sometimes, even if it is set to start with Windows. Files loads a window, is slow in doing so  and then loads the content and animations. It's totally not snappy, but it should be on my Ryzen 3900X / 32GB RAM / M.2 SSD setup.

### Steps To Reproduce

1. Use Windows 11 and latest Rocketdock
2. Set "Files" as default file manager
3. Open "Files" from Rocketdock or elsewhere

### Requirements

- fix the speed for opening Files windows and loading content and animations

### Files Version

2.5.1.0

### Windows Version

10.0.22631.1825

### Log File

[debug.log](https://github.com/files-community/Files/files/11840215/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, startup performance is mainly an issue with WinAppSdk but we're exploring some workarounds #12614. We're also working on general optimizations to improve performance once the app is opened #4180.

**Comment by yaira2** [comment]
We're excited to share that startup performance will be significantly improved in the upcoming release of version 3. You can download the preview version from our website https://files.community/download.
