### ISSUE TITLE
Incorrect display of interface icons

### ISSUE THREAD

**Issue by AryaPaw** [files-community/Files#12692]
### Description

I've been watching this bug for a long time. I even tried reinstalling the app. Nothing helps to fix and I have suspicions that everyone has such a bug.

![image](https://github.com/files-community/Files/assets/23700199/ce543e36-db21-45ff-a75b-ac7cd7d9bca1)

### Steps To Reproduce

1. Open Files
2. Look at the application interface icons and icons from the drop-down menu

### Requirements

In a light theme, this error is not so noticeable, but in a dark theme, the problem is clearly visible.

### Files Version

2.5.1.0

### Windows Version

23419.1000

### Log File

[debug.log](https://github.com/files-community/Files/files/11836008/debug.log)

**Comment by yaira2** [comment]
Are you referring to the inconsistent icons?

**Comment by AryaPaw** [comment]
> Are you referring to the inconsistent icons?

Watch icons background
In the dark theme, their background is black, and in light white
The background of the icons must be transparent.

**Comment by yaira2** [comment]
This is the intended design.
Fyi @mdtauk

**Comment by Lukiluc29** [comment]
@yaira2 I was also wondering if later there are plans to fix the design inconsistencies, especially in the "Layout" tab, where all elements have transparent backgrounds, except for the "Column" option which has a black background and a slightly lower quality compared to the others. It can be a bit awkward.

**Comment by yaira2** [comment]
@Lukiluc29 we're in the midst of updating the icons to the new styles, there are hundreds of icons in the app but to answer your question, we intend to finish the work on this over the next few months.

**Comment by Lukiluc29** [comment]
@yaira2 Alright, I'm glad to know that. I can't wait to see this.

**Comment by yaira2** [comment]
Closing because this is the intended design, the other icons will be updated over time.
