### ISSUE TITLE
Download Section Select

### ISSUE THREAD

**Issue by oleklukasiewicz** [files-community/Files#12694]
### What feature or improvement do you think would benefit Files?

It would be very useful to add the ability to select items by section ('Today', 'Earlier this week') in the download view by selecting the section heading (something like in Samsung Photos Gallery).

### Requirements

- Adding checkbox to downloads headers
- Adding ability to select all items in section by selecting checkbox in header

### Files Version

2.5.1.0

### Windows Version

10.0.22621.1848

**Comment by yaira2** [comment]
Thank you for your feedback, can you confirm if this is the same as #9528?

**Comment by oleklukasiewicz** [comment]
> Thank you for your feedback, can you confirm if this is the same as #9528?

Yes, it's exactly the same feature
