### ISSUE TITLE
Bug: Accessing network location causes crash

### ISSUE THREAD

**Issue by dexter2040** [files-community/Files#12697]
### Description

Files crash when accessing a Network location (SharePoint site) added through Explorer.exe.
Does not crash while accessing a mapped disk.
Does not crash while accessing same network location, but added by a "Sync" button in SharePoint

### Steps To Reproduce

1. Add a network location in the File Explorer (regular Windows File Explorer)
![image](https://github.com/files-community/Files/assets/50174639/24cef876-c39d-410d-acef-e88f36967135)

2. Open that location in Files

### Requirements

No crash when accessing a Network location added to the Explorer

### Files Version

2.5.2.0

### Windows Version

10.0.19045.2965

### Log File

[debug.log](https://github.com/files-community/Files/files/11840675/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
@dexter2040 Is this still an issue in the preview version? https://files.community/download?
