### ISSUE TITLE
Bug: The Git panel remains in the status bar when the home page is displayed in dual-pane

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#12701]
### Description

When both a Git directory and the home page are displayed in the dual pane, the Git panel in the status bar doesn't disappear when the focus is on the home page. 
If I try to open the branch selection flyout in this state, the app crashes.

### Steps To Reproduce

1. Start dual-pane mode.
2. Open a Git directory and the home page.
3. Focus the home page.
4. The Git panel in the status bar doesn't disappear.
5. Open the branch selection flyout.
6. The app crashes.

### Requirements

The Git panel in the status bar shouldn't appear when the focus is on the home page.

### Files Version

2.5.2.0

### Windows Version

10.0.22621.1848

### Log File

[debug.log](https://github.com/files-community/Files/files/11849548/debug.log)

**Comment by yaira2** [comment]
I can repro this as well.
