### ISSUE TITLE
mihail8059784

### ISSUE THREAD

**Issue by mihail8059784** [files-community/Files#12705]
### What feature or improvement do you think would benefit Files?

Добавьте пожалуйста в меню выделения текста пункт буфер обмена, сделайте ещё предпросмотр при наведении указателя на видео (лучше как в youtube) и аудио и других файлов, и добавьте кнопку выбора всех файлов как в стандартном проводнике

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.5.2.0

### Windows Version

10.0.25375.1

**Comment by rihards-simanovics** [comment]
== RUS
Михаил, небольшое замечание по этикету написания вопроса на Github. Все запросы должны быть на стандартном английском языке, чтобы убедиться, что каждый сможет прочитать и понять проблему. Пожалуйста, используйте такие сервисы, как https://www.deepl.com/en/translator#en/ru/ для перевода ваших отзывов с русского на английский для достижения наилучшего результата перевода. Вы можете попробовать использовать Google или Яндекс переводчик, однако результаты будут не такими хорошими.

== EN
Michail, just a little note on the etiquette of writing the Github issue. All requests should be in Standard English as to make sure that everyone can read and understand the issue. Please use services such as https://www.deepl.com/en/translator#en/ru/ to translate your feedback from Russian to English for best translation result. You could try Google, or Yandex translator however the results will not be as good.

== Original Issue Translation
"Please add clipboard item to text selection menu, preview video (better as in youtube) and audio and other files, and add a button to select all files as in standard file explorer" - @mihail8059784

**Comment by Josh65-2201** [comment]
Thanks for the feedback. Please make separate issues for different request in the future.


> Please add the clipboard item to the text selection menu

This is supported can you say where you aren't seeing this option.


> make another preview when hovering the pointer over the video (better as in youtube) and audio and other files

What would be your use case for this. There is already support for QuickLook, SeerPro and the Preview pane.


>  add a button for selecting all files as in the standard explorer

This is supported via the keyboard shortcut `Ctrl` + `A` or via the toolbar option
![image](https://github.com/files-community/Files/assets/26977075/fe478d03-d4b8-42b1-8e17-51e1da7ede47)

**Comment by mihail8059784** [comment]
I don't see clipboard when renaming files when I right click on selected text

**Comment by Josh65-2201** [comment]
What do you mean by clipboard? Can you send a screenshot of what your seeing.

**Comment by mihail8059784** [comment]
![image](https://github.com/files-community/Files/assets/137566274/d82259fe-6a99-417d-8073-b320884a9bef)

**Comment by Josh65-2201** [comment]
Cut, copy and paste options are there. There isn't anything else related to the clipboard.

**Comment by mihail8059784** [comment]
just add clipboard item to this menu
![image](https://github.com/files-community/Files/assets/137566274/cb558f5c-c4e2-40ba-9538-e6bf6be63bd2)

**Comment by rihards-simanovics** [comment]
Hey @Josh65-2201 I think this can be translation issue.

So I think what @mihail8059784 is asking is whether you can add the clipboard selection (like with cut, copy and paste) like what you get by using `WIN + V` as an item (say "select/insert from clipboard") in the context menu when you right click on selected text during file/folder renaming process.

I do see the point of why they would want it, (from non technical user point of view) but I don't know if this is possible.

**Comment by yaira2** [comment]
> make another preview when hovering the pointer over the video

Thank you for your feedback, we don't have plans to implement this now, but you can do something similar with the QuickLook integration by pressing the space bar.
