### ISSUE TITLE
Feature: Request to Customize Archive Button in File Explorer Sidebar

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12709]
### What feature or improvement do you think would benefit Files?

I have a request regarding the customization of the archive button in the File Explorer sidebar. Currently, when the 7-Zip software is not installed on the device, there is a dropdown menu with options like "Create an archive," "Create {name}.zip," and "Create {name}.7z." However, I would prefer to have a simplified experience similar to Windows Explorer, where, if 7-Zip is not installed, there is only a single "Archive" button instead of the dropdown menu to create a file .zip.

### Requirements

Develop an option to detect the presence of 7-Zip and adjust the archive button accordingly.

### Files Version

Version 2.5.1.0

### Windows Version

22H2 22621.1848

**Comment by Josh65-2201** [comment]
Thanks for the feedback, 7-zip is built into Files so it doesn't matter weather the 7-zip programs is installed or not. This is why the tree options show.

**Comment by Lukiluc29** [comment]
Yet when I try to convert a file to 7z, it shows me an error
<img width="250" alt="Capture d'écran 2023-06-24 110814" src="https://github.com/files-community/Files/assets/128183422/91a25b21-e681-4e18-a353-18077a3e9f31">

**Comment by Josh65-2201** [comment]
You should submit a bug report for that

**Comment by Lukiluc29** [comment]
And is it normal that the archive has the same behavior as a classic folder and on top of that without an icon?
<img width="457" alt="Capture d'écran 2023-06-24 111133" src="https://github.com/files-community/Files/assets/128183422/0a73f1a1-f0fc-43d7-929c-802a5912c735">

**Comment by Josh65-2201** [comment]
Yes archives can be open in Files like a normal folder. As for the icon it depends on what your default program is for the archive type.

**Comment by Lukiluc29** [comment]
Because even installing 7z, the perciste error and the icon still does not appear (I am on files stable 2.5.1.0)

**Comment by Lukiluc29** [comment]
@Josh65-2201 I made a bug report on the fact that when we do a 7z compression with or without having it on our computer, it displays an error message but the files are still compressed
