### ISSUE TITLE
Navigation tree buttons cause crash

### ISSUE THREAD

**Issue by IlyaSulli** [files-community/Files#12711]
### Description

When you click on the buttons on the top bar that contains the previous folder names to get back, it causes the files app to crash. I tested it on the downloads folder.
![image](https://github.com/files-community/Files/assets/81645040/665e7113-d897-4d09-9dcc-be4ce64d5362)

### Steps To Reproduce

1. Click on the downloads folder
2. Click on one of the navigation tree buttons (eg. Users)
3. It crashes

### Requirements

It should navigate back to the folder

### Files Version

2.5.2.0

### Windows Version

10.0.23481.1000

### Log File

[debug.log](https://github.com/files-community/Files/files/11856352/debug.log)

**Comment by gave92** [comment]
Should be fixed by #12700

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by hishitetsu** [comment]
It may be fixed by #12700.
