### ISSUE TITLE
Bug: "Drive unplugged" error in Column Layout when compressing items

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12710]
### Description

I have encountered an issue when compressing one or multiple files using 7z. After the compression process, an error message is displayed, but the resulting file is still compressed and contains all the requested files.

### Steps To Reproduce

1. Open Files
2. Go to a directory that can be compressed (with the column layout)
3. Compress files or folders in 7z
4. "Drive unplugged" error is displayed

### Requirements

Don't display error

### Files Version

Version 2.5.2.0 / dev

### Windows Version

22H2 22621.1848

### Log File

[debug.log](https://github.com/files-community/Files/files/11856335/debug.log)
![Capture d'écran 2023-06-24 114112](https://github.com/files-community/Files/assets/128183422/fccf8b21-781f-4394-a137-d76b511d8831)

**Comment by Josh65-2201** [comment]
Thanks for making the bug report.  Can you give the following information.
- Is this only an issue in column view
- Is the only error shown the `Not A Folder` one?

**Comment by Lukiluc29** [comment]
Yes this is the only error that appears and only in column view

**Comment by Lukiluc29** [comment]
@Josh65-2201 I have recently noticed that even when compressing a 7z or zip file, the "disconnected disk" error still appears, although it does not occur consistently.

**Comment by Lukiluc29** [comment]
Vous avez des nouvelles de ce bug qui est très dérengeant pour ma part car je fais beaucoup de compression zip ou 7z

**Comment by Lukiluc29** [comment]
You have news of this bug which is very disturbing for me because I do a lot of zip or 7z compression.

**Comment by Josh65-2201** [comment]
This issue hasn't been looked at yet

**Comment by yaira2** [comment]
I can reproduce this issue
