### ISSUE TITLE
Feature: Display custom zip icon instead of Files logo for archives

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12713]
### What feature or improvement do you think would benefit Files?

I want to request a change of compression icons in file explorer. Currently, when there is no associated compression application (such as 7z, WinRAR, etc.), icons for .7z files appear as a blank icon when it would be better to have a 7z icon and .zip files display the Files logo while it would also be better to have the same icon as the default file explorer.

### Requirements

Develop a unified compressed file icon that can be used when no compression application is available.

### Files Version

Version 2.5.2.0 / dev

### Windows Version

22H2 22621.1848

### Comments

![Capture d'écran 2023-06-24 115651](https://github.com/files-community/Files/assets/128183422/9739b242-aa6f-4940-9210-82c20fe6172f)
![2560px-7-Zip_Icon svg](https://github.com/files-community/Files/assets/128183422/c1c45070-fdd0-42a2-b02f-f9fad7891cc8)
![Capture d'écran 2023-06-24 120613](https://github.com/files-community/Files/assets/128183422/7dcc26a8-6f90-49b9-84f3-8483769d3075)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, I've added this to the project board.

**Comment by Lukiluc29** [comment]
I'm not sure if the issue is on my end, but the icons are still the same as before.
