### ISSUE TITLE
Bug: Translation Issues in Property Dialog

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12718]
### Description

I have noticed some translation issues in the property dialogs. For example, when opening the properties of the Recycle Bin (which does not have any permissions), the phrase "Advanced permissions" is displayed in English. Additionally, when clicking on this button, the phrase "Unable to display current owner" is not translated correctly. In my case, these phrases should be in French instead. I would like to point out that all translations in Crowdin are in French, so the issue does not originate from Crowdin.

### Steps To Reproduce

1. Open Files
2. Go to properties (For example : Recycle Bin)
3. Go to security
4. Click on the button "Advanced permissions"

### Requirements

Identify the source of the translation issues within the property dialogs.

### Files Version

Version 2.5.2.0 / dev

### Windows Version

22H2 22621.1848

### Log File

No need for this problem

**Comment by Josh65-2201** [comment]
Thanks for the report, A fix is being worked on.
