### ISSUE TITLE
Slow and unresponsive

### ISSUE THREAD

**Issue by karthikvijay5227** [files-community/Files#12719]
### Description

It is taking time to load as compared to files explorer in windows.Please make it faster to load.It also freezes sometimes and crashes.

### Steps To Reproduce

It crashes and showing black screen when it is trying to open.

### Requirements

When the app opens,it remains as black screen and unresponsive and loads after a few seconds.It should be faster as compared to files explorer.

### Files Version

2.5

### Windows Version

Windows 11 22621.1848

### Log File

[debug.log](https://github.com/files-community/Files/files/11857046/debug.log)

**Comment by Josh65-2201** [comment]
Thank you for your feedback, Merging with #4180. You can check there or click subscribe in the right sidebar for updates.

Startup performance is limited mainly by WinAppSdk. A workarounds is being looked at here https://github.com/files-community/Files/issues/12614.

**Comment by Josh65-2201** [comment]
As for the crash can you see if this is an issue in the preview version. https://files.community/download

**Comment by yaira2** [comment]
@karthikvijay5227 thank you for your feedback, we're aware of the slow startup performance and while it's a limitation with the WinAppSdk framework, we're actively looking for a solution.

**Comment by yaira2** [comment]
We're excited to share that startup performance will be significantly improved in the upcoming release of version 3. You can download the preview version from our website https://files.community/download.

**Comment by karthikvijay5227** [comment]
When will be the version 3 release?

**Comment by yaira2** [comment]
We're aiming to release it in a couple of weeks, but you can already try the preview using the link above.

**Comment by yair100** [comment]
@karthikvijay5227 we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
