### ISSUE TITLE
Log Location Folder Shortcut Button Crashes App

### ISSUE THREAD

**Issue by IlyaSulli** [files-community/Files#12712]
### Description

When on the about page and click on the open log location button, it crashes the app

### Steps To Reproduce

1. Click the cog
2. Click about
3. Click open log location

### Requirements

Should open the log location

### Files Version

2.5.2.0

### Windows Version

10.0.23481.1000

### Log File

[debug.log](https://github.com/files-community/Files/files/11856359/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by hishitetsu** [comment]
It may be fixed by #12700.
