### ISSUE TITLE
Folders with many files open partially down the folder

### ISSUE THREAD

**Issue by IlyaSulli** [files-community/Files#12714]
### Description

With folders with many files the folder is opened at the top but as the remaining files load, it is put partially down the page
![image](https://github.com/files-community/Files/assets/81645040/1ce2d89d-bde2-4630-888c-3a67b36dc420)

### Steps To Reproduce

1. Open a folder with many files
2. Wait for all the files to load and the screen will be partially down folder

### Requirements

Should stay at the top of the page

### Files Version

2.5.2.0

### Windows Version

10.0.23481.1000

### Log File

[debug.log](https://github.com/files-community/Files/files/11856402/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Merging with #5825. You can check there or click subscribe in the right sidebar for updates.
