### ISSUE TITLE
Bug: To entry in any empty folder with arrow keys in Column Layout crash Files 

### ISSUE THREAD

**Issue by Base-115** [files-community/Files#12724]
### Description

Files crash when access some empty folder with arrow keys, in Column Layout.

### Steps To Reproduce

1. Set "Column Layout";
2. Create or find some empty folder;
3. With Arrow Key, press Right Arrow Key to entry to empty folder.

https://github.com/files-community/Files/assets/112908515/78da4647-1193-4cee-8c98-fb99fe2aa08c

### Requirements

It is expect to entry to folder without crash, like is possible if you click with cursor in empty folder side.

https://github.com/files-community/Files/assets/112908515/727aed86-6bec-4540-8f02-abbfbc1b8444

### Files Version

2.5.2.0

### Windows Version

10.0.19045.3086

### Log File

[debug.log](https://github.com/files-community/Files/files/11858360/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, a fix is being worked on.
