### ISSUE TITLE
Can we show 'Destination folder access denied' pop-up window?

### ISSUE THREAD

**Issue by onlytanmoy** [files-community/Files#12729]
### What feature or improvement do you think would benefit Files?

Hello, 
Is it possible to show a similar pop-up in Files? Below is the screenshot from default windows explorer

![image](https://github.com/files-community/Files/assets/48493659/248239b6-7023-4a99-9b40-a3e33d5b1b8d)

At the moment the copy fails in Files as admin permission needs to be provided for that and since no such pop-up comes up, there is no way to do it.

### Requirements

This will help to copy the file post giving the admin permission like how its currently possible in default windows explorer!

### Files Version

2.5.1.0

### Windows Version

10.0.22621.1848

**Comment by gave92** [comment]
Merging with #10422

**Comment by Josh65-2201** [comment]
Thanks for the feedback, 
You can also right click Files in the start menu to run as admin as a workaround right now.
