### ISSUE TITLE
Automatically hide/show taskbar

### ISSUE THREAD

**Issue by DiamonAurora** [files-community/Files#12722]
### Description

When the automatically hide taskbar setting is on for Windows and Files — this app — is open and _maximised_, the taskbar can't show itself when the cursor moves to the bottom of the screen. The only way for it show is to restore down the window or press the Windows start key. Files is an app that doesn't follow the normal behavior for when that setting is on. It

This is suppose to be different for when an app is open in _fullscreen_ (f11), where the cursor never shows the taskbar when it's on the bottom of the screen.

### Steps To Reproduce

1. Have automatically hide taskbar turn on.
2. Open File screen and have it maximised.
3. Put the cursor on the bottom of the screen
4. Do the same thing with another app, see the difference

### Requirements

Install the app

### Files Version

2.5.1.0

### Windows Version

10.0.22621.1848

### Log File

[debug.log](https://github.com/files-community/Files/files/11857414/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #10767. You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
@DiamonAurora Thank you for all the feedback, the underlying issue is in the WinAppSdk framework. We're tracking this in #10767 but please add your feedback to the WinUI repository so that they hopefully fix it soon. https://github.com/microsoft/microsoft-ui-xaml/issues/8431
