### ISSUE TITLE
Bug: Issue with Recycle Bin Icon Not Updating After Emptying

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12720]
### Description

I have encountered an issue where the Recycle Bin icon does not update to reflect that it is empty after using the "Empty Recycle Bin" button. It continues to show the full bin icon even though the Recycle Bin is empty.

### Steps To Reproduce

1. Open the Recycle Bin in the Files
2. Click on the button "Empty Recycle Bin"

### Requirements

Identify the cause of the Recycle Bin icon not updating after emptying.

### Files Version

Version 2.5.2.0 / dev

### Windows Version

22H2 22621.1848

### Log File

![Capture d'écran 2023-06-24 153149](https://github.com/files-community/Files/assets/128183422/8fa1aef4-fba7-41bd-9ac6-de5aba0c3a07)
![Capture d'écran 2023-06-24 153205](https://github.com/files-community/Files/assets/128183422/0ed919d9-58f9-4a8a-9aa7-e5933dccd0fb)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #10367 and #9946. You can check there or click subscribe in the right sidebar for updates.
