### ISSUE TITLE
Bug: Alignment Issue in Properties - "Type" and "File System" Misalignment

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12727]
### Description

I have noticed an alignment issue in the properties window when performing a right-click on a file, folder, drive, or other items and accessing the properties. Specifically, the "Type:" label is misaligned with the corresponding element, and the "File System:" label is misaligned with the actual file system information of the drive, both appearing slightly shifted compared to the rest of the categories in the properties.

### Steps To Reproduce

1. Open Files
2. Right-click on a file
3. Click on propreties

### Requirements

Adjust the layout and formatting of the properties window to ensure proper alignment of the "Type" and "File System" labels with their respective elements.

### Files Version

Version 2.5.2.0 / dev

### Windows Version

22H2 22621.1848

### Log File

What propreties displays:
<img width="597" alt="Capture d'écran 2023-06-25 100128" src="https://github.com/files-community/Files/assets/128183422/dcbb2333-d70d-4674-8225-0780d26394ab">
<img width="594" alt="Capture d'écran 2023-06-25 100352" src="https://github.com/files-community/Files/assets/128183422/0b009871-a1c8-4980-a127-25835d46ebef">
How it should be displayed
<img width="468" alt="Capture d'écran 2023-06-25 100546" src="https://github.com/files-community/Files/assets/128183422/ee657b6a-0227-4b5b-80b9-db99dabceef6">

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by ItIsOHM** [comment]
Hey there, I'd love to work on this issue. But since I'm a beginner it'd be of great help if you could point me from where I can start? Thanks!

**Comment by Jay-o-Way** [comment]
I would start at https://github.com/files-community/Files/blob/d97f3e1b014fe2e8c00b14902bea74d38fa4216c/src/Files.App/Views/Properties/GeneralPage.xaml#L99-L136

and then https://github.com/files-community/Files/blob/d97f3e1b014fe2e8c00b14902bea74d38fa4216c/src/Files.App/ResourceDictionaries/PropertiesStyles.xaml#L21C2-L27

and remove the (bottom) padding(s) `0,4`

**Comment by ItIsOHM** [comment]
Hello @Jay-o-Way, thanks a lot for the detailed help, but I apologize I wouldn't be able to work on this issue right now. Although I'd love to tackle it in the near future :D

**Comment by Jay-o-Way** [comment]
@ItIsOHM Okay. It's a quick fix, but if you really want to do it, then I will not take it from you, for now.

**Comment by ItIsOHM** [comment]
> @ItIsOHM Okay. It's a quick fix, but if you really want to do it, then I will not take it from you, for now.

Ah thanks! Then i'll try to fix it in some days if it's alright? In the meantime if anyone else would like to work on this then they can :D

**Comment by mdtauk** [comment]
Can we also use the Secondary or Tertiary text brushes to distinguish the heading text, from the value text?

Similar to what @yaira2 recently did with the Details pane

**Comment by yaira2** [comment]
> Hey there, I'd love to work on this issue. But since I'm a beginner it'd be of great help if you could point me from where I can start? Thanks!

I ended up doing this together with some other tweaks to the properties window, let me know if you'd like me to recommend another issue.
