### ISSUE TITLE
Save session for different uses and or add support to save all sessions per window

### ISSUE THREAD

**Issue by piperun** [files-community/Files#12735]
### What feature or improvement do you think would benefit Files?

I would like to see Files have the ability to save sessions and have them be reusable, effectively have different defined sessions a user can pick from (example: session saved as work opens up work related folders, session saved as gaming opens up gaming related folders, etc.).
If not at least I would like if it would be possible to save every session per window, as right now it only saves the latest window's session.

### Requirements

- This proposal would accomplish having predefined sessions for user to more quickly setup their folders if Files crashes
- This proposal will accomplish a better crash recovery experience

### Files Version

2.5.1.0

### Windows Version

10.0.19045.2965

**Comment by Josh65-2201** [comment]
Thanks for the feedback, can you confirm this is the same as #11900

**Comment by piperun** [comment]
Yes this seems to be almost the same.
I'll close this one and have my fingers crossed for the feature to get implemented!
