### ISSUE TITLE
improvements

### ISSUE THREAD

**Issue by Rotoscop** [files-community/Files#12734]
### What feature or improvement do you think would benefit Files?

Hi ! suggestion: 
1. pressing win+E opens a new tab in an already open explorer, and now opens a new explorer window, convenient when tabbed so as not to multiply many explorer windows. 
2. context menu as in windows, possibility to disable like the built-in context menu in windows 
3. probably my mistake , but when I open explorer for the first time I have pane (two sides) open. I have to close it every time. 
4. layaout - very missing "list"

![47-25-23-214737](https://github.com/files-community/Files/assets/137718839/b01b7106-cc98-4da2-8c3a-1b466bfa69d2)
![Snipaste_2023-06-25_21-53-57](https://github.com/files-community/Files/assets/137718839/c46fb892-8b10-4053-8576-83d49a874e92)

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.5.1.0

### Windows Version

10.0.22621.1848

**Comment by Josh65-2201** [comment]
Thanks for the feedback, in future make separate request for different feedback/bugs
1. Making a new window is intended. Attaching to a new tab would likely be added when https://github.com/files-community/Files/issues/9709 is implemented.
2. This doesn't make sense to me. Can you clarify what you mean.
3. You can turn it off in Files settings > General > Open tabs in dual pane mode
4. This is being tracked in https://github.com/files-community/Files/issues/2509. You can check there or click subscribe in the right sidebar for updates.

**Comment by Rotoscop** [comment]
Thanks for the answers, 
point 3 is corrected thank you)) 
Point 4 I think I will get used to, if not, I will write in more detail what I mean, everything else is waiting very much) 
Thank you for your work, I really was waiting for such a guide!
