### ISSUE TITLE
Feature: Ctrl+V with text/image in clipboard will create a text/image file in the current folder

### ISSUE THREAD

**Issue by Anazark** [files-community/Files#12739]
### What feature or improvement do you think would benefit Files?

This is a really useful feature of "OneCommander" where if you have an image copied in your clipboard (after doing a screenshot for example), you can simply paste it in the file explorer and it will create an image file with the image in the clipboard as the content

### Requirements

- Doing "Ctrl+V" in a folder while having an image or a text copied in the clipboard, will create a new file (image or text) corresponding to the content of the clipboard
- Optional : having a text or an image in the clipboard will add a new line in the context menu (right click) names "paste as new file"

### Files Version

2.5.10.0

### Windows Version

Windows 10 (10.0.19044.1826)

### Comments

Thanks again for all your work !

**Comment by Josh65-2201** [comment]
Thanks for the feedback, this is already works for images.

**Comment by yaira2** [comment]
Thank you for your feedback, as Josh mentioned, this should already work for images. We've discussed supporting text files but at the moment, we don't have plans to implement it.
