### ISSUE TITLE
Feature: Remove auto select readme file

### ISSUE THREAD

**Issue by MohitSethi99** [files-community/Files#12731]
### Description

Automatically selection of README.md when a folder is opened is a very crude implementation. The intent of selecting a folder is lost cos of this. Things start to break very quickly when working with columns layout with preview pane enabled.

### Steps To Reproduce

1. Selected a folder I wanted to delete, and it selected the README.md inside of it.
2. Press delete and it will delete the README.md instead of folder.

### Requirements

The folder I selected should be selected and it should not select any other file or folder.

### Files Version

2.5.1.0

### Windows Version

10.0.22621.1848

### Log File

N/A

**Comment by MohitSethi99** [comment]
Maybe having a toggle in settings to disable this functionality altogether would be helpful.
Also Why not show README.md content when a folder is selected and not alter user's selection? I'm not aware of the architecture of this project so not sure if it can be done but it seems to be a better implementation.

**Comment by Lukiluc29** [comment]
I have the same problem too. When I open a folder containing a README.md file and my preview pane is open, it automatically selects itself, and it's a bit annoying.

**Comment by yaira2** [comment]
I'm happy to remove this feature if it's not useful. It was originally introduced before we had the column layout.
