### ISSUE TITLE
Bug: Type "Home" (without quotation mark) in Select directory path field crash Files.

### ISSUE THREAD

**Issue by Base-115** [files-community/Files#12733]
### Description

Type "Home" (without quotation mark) in Select directory path crash Files.

https://github.com/files-community/Files/assets/112908515/2d64afe1-a70a-4226-8947-1f7b96662484

### Steps To Reproduce

1. Go to Select directory path (Keyboard Shortcut: Ctrl + L)
2. Type "Home" (without quotations marks)

### Requirements

Fix prevent to crash. Typing this string in Select directory path should be cool if this move to the "Folder" where are the "Quick Access", "Drives" and "Recent Files"

(If I'm being confused, I refer to "Folder" from this picture.)
![HomFolFiles](https://github.com/files-community/Files/assets/112908515/9b377ccd-e6f3-4c4d-9b6c-b8a282a6bd22)

### Files Version

2.5.2.0

### Windows Version

10.0.19045.3086

### Log File

[debug.log](https://github.com/files-community/Files/files/11860300/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
@Base-115 this issue will be fixed in v2.5.20.
