### ISSUE TITLE
Feature: Multi-level / Nested Tags

### ISSUE THREAD

**Issue by Anazark** [files-community/Files#12738]
### What feature or improvement do you think would benefit Files?

First of all thank you for this software
About tags, i would like to be able to create tags inside other tags/"tags family tree", like a tag containing multiple other tags ; and having the assignment of a child-tag automatically apply all parent-tags

Exemple 1 : having a tag "Work" containing child-tags such as "Recent Projects" and "Old Projects", and by applying the tag "Recent Project" to a file it would also apply the parent-tag that is "Work" without me having to do it

Exemple 2 : having an "Art" tag containing the child-tags "Photography" and "Digital", and the tag "Photography" contains the child-tags "Black and White" and "Amateur"
Assigning the tag "Amateur" to a file would also assign automatically "Photography" and "Art" to it

### Requirements

- Being able to connect tags with each other / imbricating tags inside one another
- The assignment of a child-tag will also automatically assign all parent-tags to the file

### Files Version

2.5.10.0

### Windows Version

Windows 10 (10.0.19044.1826)

### Comments

Thanks again for all of you hard work !

**Comment by yaira2** [comment]
Thank you for your feedback

**Comment by fazioliamboina** [comment]
yes please

**Comment by Warr1611** [comment]
Curious about the state of this one. Is work on this being considered?

**Comment by yaira2** [comment]
We haven't considered this feature yet, but people are welcome to share feedback and we'll take it into account when reviewing this proposal.

**Comment by yaira2** [comment]
Upon further consideration, I believe this could potentially be addressed by #11992, depending on the feature's implementation and the conditions it supports. For instance, a condition could be set to automatically add a tag (e.g., 'work') to files that already have a specific tag (e.g., 'Recent Projects'). Would that solve your use case?

**Comment by Thundercraft5** [comment]
Nested tags at current could be done with slashes (`parent/child/tag`); maybe the app could support Nested Tags this way?

Example setup:
```
Work/Projects/Programming
Work/Files/Images
```

**Comment by yaira2** [comment]
> Upon further consideration, I believe this could potentially be addressed by [#11992](https://github.com/files-community/Files/issues/11992), depending on the feature's implementation and the conditions it supports. For instance, a condition could be set to automatically add a tag (e.g., 'work') to files that already have a specific tag (e.g., 'Recent Projects'). Would that solve your use case?

Merging with #11992.

**Comment by AbyssalSoda** [comment]
I don't think the Auto-Tagger system quite fully aligns with my needs when it comes to fulfilling the role nested tags. Users likely want a system that works more like this:

You have a tag for "Project A" and a general tag for "Assets" that applies to a wide range of content.  While the "Assets" tag would contain all assets globally, the "Project A" tag could display a nested "Assets" tag within it. This nested tag would only show assets specifically related to "Project A." This is typically how I have seen nested tags applied when it comes to a visual interface and not just a normal filter - I want a space similar to the Tag widget that allows me to visualize and select these tags in a semi-hierarchal manner.

I could be missing something here looking at autotarget but presently I don't see any way to achieve this mentioned.

**Comment by yaira2** [comment]
This should address the use case by automatically adding the 'assets' tag (in your example) whenever a 'project a' tag is added.
