### ISSUE TITLE
Bug: Nothing happens when entering `%temp%`

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#12742]
### Description

As the title described. It should be replaced with the path defined by environment variable.

### Steps To Reproduce

1. Enter `%temp%` or `%tmp%` in the path bar.
2. Nothing happens.

### Requirements

It should be replaced with the path defined by environment variable.

### Files Version

2.5.10.0

### Windows Version

10.0.22621.1848

### Log File

n/a

**Comment by yaira2** [comment]
Thank you for reporting and fixing this issue.
