### ISSUE TITLE
Remove the dead useless space above tabs

### ISSUE THREAD

**Issue by Anazark** [files-community/Files#12741]
### What feature or improvement do you think would benefit Files?

There is a line of dead useless space above the tabs. This line of space doesn't even allow to grab/move the window (when you click on the portion right above your tabs, which can quickly fill the entire line)
![image](https://github.com/files-community/Files/assets/137785463/d6f84f47-d2f4-44a3-b088-e86ba9089934)
![image](https://github.com/files-community/Files/assets/137785463/ac98c981-7afd-4ec4-be78-5c6a62c1144c)

I think it would be best :

1) If this line of space is entirely removed, as with most internet browsers. Personally, I think this space is annoying when you want to click a tab and have to go all the way up only to back-pedal for a few pixels
Alternatively, you could make it an option in the settings like the browser Opera does (if there are people who like having that dead useless space)
![image](https://github.com/files-community/Files/assets/137785463/37ace3cf-0724-4001-91c5-07f8339c8241)

2) That when this line of space is left in place by the user, making it so that it's no longer useless and able to move/grab the window when clicking on the portion of it that is above tabs

### Requirements

- Remove the space above tabs when the window is maximized (optional : include an option in the settings to bring it back if wanted)
- Making it so that the space above tabs (if chosen to be left as is) is clickable/useable to drag and move the window, and not being useless dead space

### Files Version

2.5.10.0

### Windows Version

Windows 10 (10.0.19044.1826)

### Comments

Thank you again so much for this wonderful software

**Comment by yaira2** [comment]
> There is a line of dead useless space above the tabs. This line of space doesn't even allow to grab/move the window (when you click on the portion right above your tabs, which can quickly fill the entire line)

Thank you for your feedback, this is supposed to be a drag space but there is an issue where it isn't working (related to #10813).  The plan when the app is maximized is to either do what you're suggesting or at the very least make them clickable. #6397
