### ISSUE TITLE
Bug: Emptying recycle bin crashes app

### ISSUE THREAD

**Issue by oacoello** [files-community/Files#12749]
### Description

I have my recycle bin shortcut pinned on the favorites section, if I right click the shortcut and select "empty recycle bin" the app crashes. I can open other windows if I middle click the files taskbar pinned icon. But the other windows just freezes until it shows the "Files is not responding" windows dialog.

### Steps To Reproduce

1. Pin recycle bin on favorites left bar.
2. Right click the shortcut.
3. Click on the context menu, "empty recycle bin".

### Requirements

The recycle bin shortcut needs to be pinned on the favorites left bar.

### Files Version

2.5.10.0

### Windows Version

10.0.19045.3086

### Log File

[debug.log](https://github.com/files-community/Files/files/11871477/debug.log)

Screen recording.
![3k8aGFQpts](https://github.com/files-community/Files/assets/72462404/d2cbf884-6104-489b-bcbf-d1a69142b1f5)

**Comment by yaira2** [comment]
I can reproduce an issue where it freezes but it doesn't crash for me.

**Comment by Lukiluc29** [comment]
Me too, the trash bin freezes, and it can be frustrating, especially when dealing with large files as it freezes for a long time.

**Comment by yaira2** [comment]
This issue is fixed in our dev branch and will be included in the next release.
