### ISSUE TITLE
Bug: Translation Error in Preview Pane for Files and 7z Files when Copying Paths

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12744]
### Description

I have encountered a translation error in the preview pane when trying to copy the path of a compressed 7z file or folder. Instead of displaying "Users" in the path, it shows "Utilisateurs" since I have Files set to French. However, this error does not occur for regular folders in the preview pane. This problem causes that when we copy the path in the path bar, the path is erroneous and displays an error.

### Steps To Reproduce

1. Open Files
2. Go to a folder with a file
3. Click on a file or 7z compressed file
4. Open the preview window

### Requirements

Implement a fix to display "Users" in the path for files and compressed files 7z.

### Files Version

Version 2.5.10.0 / dev

### Windows Version

22H2 22621.1848

### Log File

No need.

**Comment by yaira2** [comment]
@Lukiluc29 thank you for the report, I added this to the project board.

I also want to thank you for all the feedback and bug reports you're sending us. While we can't get to everything at once, it's very helpful to get them in our project board because it helps us prioritize and know which areas need improvement.

**Comment by Lukiluc29** [comment]
> @Lukiluc29 thank you for the report, I added this to the project board.
> 
> I also want to thank you for all the feedback and bug reports you're sending us. While we can't get to everything at once, it's very helpful to get them in our project board because it helps us prioritize and know which areas need improvement.

All right. It is with great pleasure !
