### ISSUE TITLE
Bug: Connecting phone into laptop crashes the app

### ISSUE THREAD

**Issue by MMZThumper** [files-community/Files#12751]
### Description

I plugged my S23 into my laptop to copy some videos I had made when I got a notification that Files ran into a problem that the developers didn't plan for yet. While my phones plugged in the app won't open. As soon as I unplug my phone the app opens just fine.
![Screenshot 2023-06-26 111342](https://github.com/files-community/Files/assets/98562828/70ab35ec-cc99-4345-a7fe-2827a39d2812)

### Steps To Reproduce

1. Open Files app like normal
2. Plug a USB cable into your laptop or PC
3. Plug the other end of the USB cable into your S23
4. App should encounter a problem

### Requirements

- e.g. Fix crash that occurs when...
My expected behavior was that the app would continue to work as intended. That my S23 would appear under Device's and Drives just like it does within Windows Files Manager and that I would be able to access the storage on my device to copy, move and delete files stored on my phone.

### Files Version

2.5.10.0

### Windows Version

Windows 11 22H2 22621.1

### Log File

[debug.log](https://github.com/files-community/Files/files/11872492/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by hishitetsu** [comment]
This may be the same issue as #12370.
@MMZThumper could you try disabling some of the widgets to see if the crash can be avoided?

**Comment by yaira2** [comment]
@MMZThumper this issue will be resolved in the upcoming v2.5.20 release.
