### ISSUE TITLE
Bug: "copy path" from context menu crashes files

### ISSUE THREAD

**Issue by yIsItSo** [files-community/Files#12757]
### Description

right click on file
copy path
--> crash notice, automatic restart of Files

### Steps To Reproduce

right click on file
copy path
--> crash notice, automatic restart of Files

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

2.5.10.0

### Windows Version

10.0.22631.1906

### Log File

[debug.log](https://github.com/files-community/Files/files/11878522/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.
