### ISSUE TITLE
Preview compatibility with powertoys under windows 11

### ISSUE THREAD

**Issue by Sedelbum** [files-community/Files#12759]
### What feature or improvement do you think would benefit Files?

hello, I use powertoys under windows 11 and a priori but I can be wrong when on an image in your explorer when I do the CTRL+SPACE shortcut I do not have a preview of the image that I should have with powertoys. I tried in this one to assign it another key combination but again it doesn't work in fact it selects me or deselects the image only. Do you think you will soon be able to remedy this?
Thank you for your program and sorry for the google translate.
Cordially
Fabrice

### Requirements

I'm sorry but I don't understand this topic

### Files Version

2.5.1.0

### Windows Version

10.0.22621.1848

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #12432. You can check there or click subscribe in the right sidebar for updates.
