### ISSUE TITLE
Code Quality: Add PowerShell script for Files build

### ISSUE THREAD

**Issue by 0x5bfa** [files-community/Files#12758]
### What feature or improvement do you think would benefit Files?

When I edit code in Code Spaces, I hardly can build from command line. By adding build PS Script, we can use it from Pipeline as well.

### Requirements

- Add PowerShell Script for the build.
- Integrate with Azure Pipeline.

### Files Version

2.5.10

### Windows Version

10.0.22000

**Comment by yaira2** [comment]
@0x5bfa isn't there a dot net command for building the solution?

**Comment by 0x5bfa** [comment]
Yes, I become to think it's not something we want.
