### ISSUE TITLE
Smaller icon size in grid layout

### ISSUE THREAD

**Issue by manfromarce** [files-community/Files#12752]
### What feature or improvement do you think would benefit Files?

Currently small icons in Files are larger then medium icons in Windows Explorer and I would like to have icons of that size. Following the current naming, a new option "Very small icons" could be added, but it could be confusing for users.
Alternatively, since "medium" in Files is also more equivalent to Explorer's "large" and "large" to "very large", they could all be changed to match Windows Explorer size when "compact mode" is enabled.
A slider or something else that allows to set a custom size directly could also be considered.

### Requirements

- This proposal will add the ability to have smaller icons (equivalent to Medium in Windows Explorer)
- This proposal could allow to set a custom icon size through a slider or similar (optional)

### Files Version

2.5.10.0

### Windows Version

10.0.22631.1906

**Comment by yaira2** [comment]
@manfromarce thank you for your feedback, support for further customizing the icon sizes is being planned, you can follow the progress in https://github.com/files-community/Files/issues/10492.

**Comment by Xavron** [comment]
If you're able to build Files, you can set a good small size as I just did:

...Files\src\Files.App\Constants.cs > public const int GridViewSizeSmall = 70;

They currently have 100 set. You could go with anything in the 70-75 range. 70 is a hair smaller than File Explorer.

If you can't, then its what it is. I can't do anything about it.

**Comment by yaira2** [comment]
Support for additional sizes is actively being worked on, you can track the latest progress in #10492.

**Comment by Xavron** [comment]
Yes, I know and still don't like it ;)

Master branch grid slider, make smaller icons for grid can be done like this if it still never gets better:

...Files\src\Files.App\UserControls\InnerNavigationToolbar.xaml

x:Name="GridViewSlider"
IsThumbToolTipEnabled="False"
Maximum="300"
Minimum="60" <--- eg this to 60
SnapsTo="Ticks"
TickFrequency="10" <---- eg this to 10

If they change it any further, hopefully they get it right. I won't be adding anything further here.
