### ISSUE TITLE
Suddenly crash

### ISSUE THREAD

**Issue by Shadow912kage** [files-community/Files#12762]
### Description

A Files crashed suddenly while minimized on the taskbar.  It may be caused by opening the download folder in a tab and downloading the file there from Chrome.  I am attaching the log file.

### Steps To Reproduce

Unknown...

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

2.5.10.0

### Windows Version

10.0.19045.3154

### Log File

[debug.log](https://github.com/files-community/Files/files/11880418/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
@Shadow912kage thank you for the feedback, we're not able to repro this issue on our side but it'll help if you can confirm on your side as well. You can download the latest preview build from our website https://files.community/download.
