### ISSUE TITLE
Cannot install on an offline computer( 0x80072EFE The SSL connection could not be established)

### ISSUE THREAD

**Issue by Zeyuan-Cheng** [files-community/Files#12761]
### Description

I tried to intall files using the Files.Stable.exe installer that I get from the offical site(https://files.community/download), the popup window showed this message: The SSL connection could not be established, see inner exception. 
The computer I use is not connected to the internet(Couldn't do it due to company policy).
Is this a bug or this app has to be installed on a online computer?

![微信图片_20230627170819](https://github.com/files-community/Files/assets/55337545/ef06715e-60f0-433b-9c00-2ba75a62f649)

### Steps To Reproduce

Use the Files.Stable.exe to install on an offline computer

### Requirements

The installer should run

### Files Version

latest

### Windows Version

Windows 10

### Log File

No log

**Comment by yaira2** [comment]
@Zeyuan-Cheng please let us know if those links work.

**Comment by Zeyuan-Cheng** [comment]
> @Zeyuan-Cheng please let us know if those links work.

Yes，thanks a lot!

**Comment by AlexandreMarkus** [comment]
The solution is not working anymore, do you have an alternative solution? Thank you

**Comment by Josh65-2201** [comment]
You need to change the URL version numbers to the current preview build 3.5.31.0
