### ISSUE TITLE
Folder with over 1000+ files will cause high CPU usage even when idle

### ISSUE THREAD

**Issue by piperun** [files-community/Files#12767]
### Description

Files use upwards to 10% of my CPU (4790k) even when idle.
It seems to occur when you open a folder with lots of files (1000+) the file size does not seem to matter

### Steps To Reproduce

1. Open up Files
2. Open at least 1 folder with lots of files (1000+)
3. It should bump up the Files CPU usage to at least 6%

### Requirements

- It should ideally use around the same CPU usage as Windows own file explorer (which hovers around 1-2% at most)

### Files Version

2.5.10.0

### Windows Version

10.0.19045.2965

### Log File

[debug.log](https://github.com/files-community/Files/files/11887518/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, improving performance is something that we're actively working on. We're tracking this in #4180.

**Comment by yair100** [comment]
@piperun we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
