### ISSUE TITLE
Feature : Batch rename with F2

### ISSUE THREAD

**Issue by Anazark** [files-community/Files#12763]
### What feature or improvement do you think would benefit Files?

Hello again, sorry for all the posts and suggestions i hope i'm not bothering too much

In the native windows, you could select multiple files and press F2 to batch rename them according to the format "{whatyoujusttyped} (x)" but i couldn't do it with Files
This is a functionality i use really frequently it would be great to have it in Files

Thanks again for all the work

### Requirements

- Selecting multiple files and pressing "F2" should make us able to batch rename the selected files according to the format "{whatyoujusttyped} (x)", with "x" being a number

### Files Version

2.5.10.0

### Windows Version

Windows 10 (10.0.19044.1826)

### Comments

Thank you so much for this software you guys rock

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #8191. You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
@Anazark thank you for your feedback, until this is added, we recommend using PowerToys Reanme. It integrates directly into Files and has a lot of great features.
