### ISSUE TITLE
Installed fail with error 0x80073cf9

### ISSUE THREAD

**Issue by yonist** [files-community/Files#12766]
### Description

I downloaded the stand alone installed and got an error: 0x80073cf9

Happen when I installed in both normal mode and administrator.

### Steps To Reproduce

1. Download
2. Install

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

2.5.10.0

### Windows Version

Windows 10 19045.3086

### Log File

No log file...

**Comment by Josh65-2201** [comment]
What the full error message?

**Comment by yonist** [comment]
See the picture

![image](https://github.com/files-community/Files/assets/499992/fb498e14-b65a-4331-91f3-efb19219b03b)

**Comment by Sebo1411** [comment]
I had a similar issue installing the "stable" release(just a different error), but you should be able to **install the preview** as I did.

**Comment by Josh65-2201** [comment]
To install stable you can try
1. Opening PowerShell as administrator
2. Run this command
```Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/stable/Files.Package.appinstaller```
3. See if Files is in the start menu/recent section
