### ISSUE TITLE
Bug: Files are incorrectly downloaded from OneDrive

### ISSUE THREAD

**Issue by cardin** [files-community/Files#12774]
### Description

OneDrive allows users to put files online-only. I.e. they are downloaded on-demand when accessed.

If we have a Git Repository that is online-only, when Files accesses the folder, it will try to parse the `.git/` directory and download all the files within.

This download process causes responsiveness issues as OneDrive tries to sync hundreds of blob files down.

![image](https://github.com/files-community/Files/assets/553816/4ef02208-7c68-4cb0-9ae7-55db1b36b6df)
![image](https://github.com/files-community/Files/assets/553816/0b102cb7-9e25-403a-bf57-5c3f8a5bc18e)
![image](https://github.com/files-community/Files/assets/553816/c18953bd-6327-4d2c-9dd7-ef2bec75e462)

### Steps To Reproduce

1. Have a online-only OneDrive .git folder
2. Access that folder using Files
3. OneDrive sync notification will popup, showing multiple files downloaded
4. This causes Files and system slowdown, depending on network and hardware conditions

### Requirements

- Files should not slow down or impact the system when accessing an online-only Git repository.

### Files Version

2.5.10.0

### Windows Version

10.0.19045.3086

### Log File

No log files were generated by Files.

**Comment by cardin** [comment]
This was spawned from #12770 as requested.

**Comment by yaira2** [comment]
Thank you for your feedback, this definitely needs to be addressed.

**Comment by yaira2** [comment]
@0x5bfa do you have time to look into this?

**Comment by 0x5bfa** [comment]
Dont think so.

**Comment by yaira2** [comment]
@cardin can you repro this in v3.0.3?

**Comment by cardin** [comment]
> @cardin can you repro this in v3.0.3?

![image](https://github.com/files-community/Files/assets/553816/b077ba1c-972b-40cb-9d7f-41cae56f8565)
Yes, reproed in Files Preview 3.0.3

**Comment by yaira2** [comment]
Can you repro this with the `Files` repo?

**Comment by cardin** [comment]
Yes it is reproducible with the Files repo


https://github.com/files-community/Files/assets/553816/ae1267d3-c8d3-4c30-896b-155ec2111111

**Comment by yaira2** [comment]
> Yes it is reproducible with the Files repo

When are the files being downloaded? (the performance issue is being actively worked on)

**Comment by yaira2** [comment]
@cardin

**Comment by AkazaRenn** [comment]
> @AkazaRenn @Traxeronus @cardin 
> 
> For testing purposes, can you
> 1. Create a new folder and add a couple of text files
> 2. Right click the files and free up space
> 3. Refresh the directory and see if the files are downloaded

Tried that, they don't get re-downloaded

**Comment by yaira2** [comment]
@AkazaRenn can you try to identify if there is a specific file type that gets downloaded?

**Comment by AkazaRenn** [comment]
@yaira2 PDF, PNG, jpg, txt, docx, ps1, sh, I don't think there's a type difference.

**Comment by yaira2** [comment]
Do they get downloaded if you copy them to the test folder?

**Comment by AkazaRenn** [comment]
@yaira2 they are, here are my steps

1. Copy aaa.sh and BBB.ps1 (previously downloaded unintentionally by Files) to the test folder
2. Do `Free up space` to them
3. Refresh the view
4. They get downloaded again
5. Repeating 2 & 3 gets the same result

**Comment by yaira2** [comment]
Is there anything else in the test folder or just those two files?

**Comment by AkazaRenn** [comment]
@yaira2 only those two files in the test folder. The text files I created before for testing were deleted before they are copied in.

**Comment by yaira2** [comment]
Do you have the option to calculate folder sizes turned on?

**Comment by AkazaRenn** [comment]
@yaira2 no, it's off. And here's an update on the new test text file, it now also gets downloaded upon refreshing, the previous result might be an accident.

**Comment by yaira2** [comment]
This is what I think is the cause -
Checking if a file requires admin rights to open requires downloading the file, to avoid this we cancel the check for online files. However, it's possible the check is still happening for placeholder files.

**Comment by yaira2** [comment]
I have a potential fix in #14009

**Comment by AkazaRenn** [comment]
@yaira2 sorry for being late, I think it's good now on the preview build

**Comment by yaira2** [comment]
> sorry for being late

Thank you for reporting and helping debug this issue!
