### ISSUE TITLE
Allow user to enable/disable Git feature

### ISSUE THREAD

**Issue by cardin** [files-community/Files#12770]
### What feature or improvement do you think would benefit Files?

Files just received a Git feature. However, not everyone wants to have Git features enabled, as it adds clutter and impacts performance.

Files should have a toggle to disable Git features.

### Requirements

- Add a toggle to disable Git features at an application level, or at a per-folder level.
- Not display Git related buttons, columns, status indicators when Git is disabled
- Not attempt to parse .git folder automatically

### Files Version

2.5.10.0

### Windows Version

10.0.19045.3086

### Comments

One major performance impact is when a Git Repository is stored as cloud-only.

When Files loads such a directory, it will start fetching all the files inside of `.git/`, even if they were cloud-only.

A long sync operations ensues, as hundreds of files start getting downloaded to parse the `.git/` directory.

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Is the only performance related issue with cloud downloads. It may be better to change it so it doesn't download them. 
As for the columns you can turn them off by right clicking on the column header (Where it says name) > Go to Git > Turn of ones you don't want.

**Comment by cardin** [comment]
> As for the columns you can turn them off by right clicking on the column header (Where it says name) > Go to Git > Turn of ones you don't want.

Ah okay, I was looking in the wrong location. It would be good to synchronize both views to have the same options available.
![image](https://github.com/files-community/Files/assets/553816/13018858-f5a5-406a-a24c-94f9d16757eb)

**Comment by cardin** [comment]
> Is the only performance related issue with cloud downloads

Admittedly I haven't use the feature (I have my own Git Client, and also I didn't want to trigger cloud downloads), so yes, my main issue is with the cloud downloads creating moments of unresponsiveness.

**Comment by Josh65-2201** [comment]
Aright. The one were it downloads the git folder to parses it can you make a separate bug report for it and change this one to be about including Git columns in the settings menu.

**Comment by cardin** [comment]
Closed as it was forked to #12773 and #12774 which are more specific.

**Comment by Josh65-2201** [comment]
Thanks
