### ISSUE TITLE
Function "Group by"

### ISSUE THREAD

**Issue by FoundTheWOUT** [files-community/Files#1277]
Will files-UWP support "Group by" function like Explorer in the future?
I think using "Group by" it's more convenient to browse in some folder, for example, the "Download".

![QQ截图20200628140905](https://user-images.githubusercontent.com/47922588/85939535-f48ebb00-b948-11ea-8735-c78d01df4399.png)

**Comment by Jaiganeshkumaran** [comment]
We can add this feature to the details view.

**Comment by yaichenbaum** [comment]
Merging with #1874.
