### ISSUE TITLE
Settings area should allow Git columns to be toggled

### ISSUE THREAD

**Issue by cardin** [files-community/Files#12773]
### What feature or improvement do you think would benefit Files?

Settings area currently allows columns to be toggled on and off.

But the columns related to Git can't be found in the settings. They can only be found by right-clicking the column header and going to the Git submenu.

Hence I propose the Git columns be able to be toggled off in the settings as well.

Screenshots below:

![image](https://github.com/files-community/Files/assets/553816/268fd102-9dea-4a4a-8de3-4ddc4f876cab)
![image](https://github.com/files-community/Files/assets/553816/73fe6eba-faab-455c-9e85-9f77a293d828)

### Requirements

- Add a toggle in Settings for showing/hiding Git-related columns

### Files Version

2.5.10.0

### Windows Version

10.0.19045.3086

### Comments

Recreated and refined based on issue #12770

**Comment by yaira2** [comment]
@cardin the columns in settings are only for columns that are available in all folders, do you have a use case for globally enabling the git columns?

**Comment by cardin** [comment]
Not really, I just wanted to universally disable all Git functions to have more control over how I wanted Files to interact with Git.

**Comment by Josh65-2201** [comment]
It could still be added as a global default for all git folders.

**Comment by yaira2** [comment]
> Not really, I just wanted to universally disable all Git functions to have more control over how I wanted Files to interact with Git.

You can do the following

1. Open a git folder
2. Hide the git columns (they are all hidden by default in the preview version)
3. Right click a column header and click set as default
