### ISSUE TITLE
Right-Click Context Menu is sluggish and causes click registration & rendering delays

### ISSUE THREAD

**Issue by cardin** [files-community/Files#12786]
### Description

I apologise for the title, the problem is difficult to describe. But I have attached a video capture!

**When I open the Right Click Context Menu and click on a menu entry, an unrelated menu entry is triggered instead.**

https://github.com/files-community/Files/assets/553816/257aa64e-7f0f-4779-8141-d92d0c47b25e

If you look at my video capture, you can see I was attempting to click on "Pin to Favorites".

Instead, the result is that Windows Terminal and VLC Player are randomly launched.

If I wait a few seconds for the Context Menu to fully render, the location where "Pin to Favorites" is, gets rerendered with Windows Terminal and VLC Player menu entries instead. So there is a click registration and rendering delay there.

### Steps To Reproduce

1. Ensure your context menu has many entries and does not use the "Move extensions to submenu" feature
2. Right Click to open the Context Menu, and quickly click on a specific entry
3. Notice a sudden menu flicker as the expanded context menu rerenders, followed by the wrong menu entry being activated by your prior mouse click

### Requirements

- There should not be rendering delays and menu flickerings
- The menu I activated should be the menu I saw, not the menu that was later rerendered.

### Files Version

2.5.10.0

### Windows Version

10.0.22621.1928

### Log File

No log files were generated by Files for this issue.

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #11112. You can check there or click subscribe in the right sidebar for updates. 
Currently the best way to deal with this is to enable Files settings > Genral > Move shell extensions into a sub menu

**Comment by yaira2** [comment]
@cardin is this an issue if you turn off the option to show shell extensions in the main menu?

**Comment by yaira2** [comment]
The default is to put them in the sub menu, I understand the appeal of having them in the main menu which is why the option is available but it's just not reliable or performant this way.

**Comment by yaira2** [comment]
It really depends on the device and how many shell extensions are installed. In general I agree that we shouldn't provide "bad" options but in this case we got a lot of requests, so we let users decide for themselves.
