### ISSUE TITLE
Files App erroneously claims Windows 11 is a Windows 10

### ISSUE THREAD

**Issue by cardin** [files-community/Files#12789]
### Description

Files App claims my Windows is version 10.0.22621.1928, when in fact, it is a Windows 11 PC.

![image](https://github.com/files-community/Files/assets/553816/1941027a-95c0-44fd-b858-3fd7d9a7ad77)

### Steps To Reproduce

1. Files App > Settings > About > Copy > Windows version

### Requirements

- It should be Windows 11. not Windows 10

### Files Version

2.5.10.0

### Windows Version

10.0.22621.1928

### Log File

no logs are generated by Files App

**Comment by Josh65-2201** [comment]
It is giving the correct version.

**Comment by cardin** [comment]
Apologies, I mistakenly thought the 10 was referring to the Windows version. I shall close this issue then.
