### ISSUE TITLE
crush on ya for making such a marvelous explorer (●'◡'●)ﾉ♥

### ISSUE THREAD

**Issue by proxymentality** [files-community/Files#12783]
### Description

The program crashes as soon as I open a folder with lots of photos. Don't ask me what these photos are, I work as an anime channel admin...

### Steps To Reproduce

1. Opening a folder
2. Trying to upload all previews of images set on little icons.
3. Lovely crushing (⊃｡•́‿•̀｡)つ──☆*:・ﾟ

### Requirements

Fix plz crash that occurs when da pics are previewing..

### Files Version

2.5.10.0

### Windows Version

22H2 build 19045.3086

### Log File

[debug.log](https://github.com/files-community/Files/files/11901061/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #12581. You can check there or click subscribe in the right sidebar for updates.
