### ISSUE TITLE
Bug: Pasting files from TeamViewer remote control session doesn't work

### ISSUE THREAD

**Issue by AlquistArj** [files-community/Files#12788]
### Description

I get an error when copying files from File Explorer running in a TeamViewer remote control session.

### Steps To Reproduce

From a TeamViewer remote session select files in File Explorer, Ctrl+C to copy them
Paste into Files on controlling PC fails.

### Requirements

- e.g. Fix crash that occurs when...
Files should copy as happens when pasting into File Explorer

### Files Version

2.5.10.0

### Windows Version

Edition	Windows 11 Pro Version	22H2 Installed on	‎05/‎10/‎2022 OS build	22621.1928 Experience	Windows Feature Experience Pack 1000.22644.1000.0

### Log File

I'm not happy uploading log file to public place
[debug.log](https://github.com/files-community/Files/files/11905944/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report. You will need to upload the log file but you can edit anything you don't want shown out.

**Comment by AlquistArj** [comment]
ok, uploaded just the error message

**Comment by Josh65-2201** [comment]
Thanks, I've added this to the project board.

**Comment by yaira2** [comment]
@AlquistArj is this still an issue in v3.0.3? If you can still reproduce the issue, please upload the updated log file so we can take a closer look.

**Comment by AlquistArj** [comment]
No, still not working properly. Copying from Files on the PC to FileManager on PC in a TeamViewer session works ok, but copying a file from FileManager in a TeamViewer session to Files in the host only seems to copy the first 64k of the file.

**Comment by yaira2** [comment]
Is the app crashing?

**Comment by yaira2** [comment]
@AlquistArj

**Comment by thompatry** [comment]
I will reopen this case. I am having this issue. The Files app does not crash. I can copy files from my PC to the Teamviewer Remote PC. Where is fails is when I want to copy from the Teamviewer Remote PC to my PC. I have upload the debug log here. I copied from my computer at 7:28:30 and it works. When I copy back at 7:30:30, it appears to not work and hang. It acts like it is copying but does nothing. I have included the log file from that time.

[debug.log](https://github.com/files-community/Files/files/14572240/debug.log)

**Comment by yaira2** [comment]
> to the Teamviewer Remote PC. Where is fails is when I want to copy from the Teamviewer Remote PC to my PC. I have upload the debug log here. I copied from my computer at 7:28:30 and it works. When I copy back at 7:30:30, it appears to not work and hang. It acts like it is copying but does nothing. I have included the log file from that time.

This seems to be a bit of a different issue, can you please open a new issue so we can track it properly?
