### ISSUE TITLE
Option to open the Windows properties dialog of a file/folder

### ISSUE THREAD

**Issue by Alloc86** [files-community/Files#12787]
### What feature or improvement do you think would benefit Files?

I like Files' own properties dialog a lot, but in some cases you need Windows' own properties dialog. My main issue right now is working with TortoiseSVN, which adds a tab to the properties:
![SvnProperties](https://github.com/files-community/Files/assets/5400030/929149d9-8638-4e06-b302-0a37054393de)

I assume Files' can't just integrate those additional tabs, so a way to open Windows' properties dialog on a file/folder would be necessary. Possibly just a button on the General tab of Files' that says "Show Windows' properties dialog" would be good enough.

### Requirements

* Button somewhere in the UI
  * Files' properties dialog
  * Files' context menu on files/folders
* API to open Windows' properties dialog

### Files Version

2.5.10.0

### Windows Version

10.0.19045.3031

**Comment by Josh65-2201** [comment]
Thanks for the feedback, I've added this to the project board.

**Comment by yaira2** [comment]
@Alloc86 thank you for sharing your feedback. We don't have plans to add this option to Files, but if TortoiseSVN adds a shell extension to the right click context menu in File Explorer, it should work in Files as well.
