### ISSUE TITLE
Feature: When dragging images from Firefox, use CF_HDROP

### ISSUE THREAD

**Issue by Trinitek** [files-community/Files#12784]
### What feature or improvement do you think would benefit Files?

This issue was originally reported in #3357, wherein dragging image files from Firefox into Files would copy a bitmap file with a random file name instead of the expected file name and format.

Consider a JPEG file like https://upload.wikimedia.org/wikipedia/commons/0/04/Seychelles_parakeet_pair.jpg. If we copy the image from Firefox and then inspect the clipboard format with a tool like InsideClipboard, we can see a list of formats are supported:

![image](https://github.com/files-community/Files/assets/6560270/50b3899d-1551-4111-9261-48d10745408f)

Of these, only two of them are image formats: `CF_DIBV5` and `CF_DIB`. The bitmap file that is created today is sourced from one of these two. Firefox however exposes the true file name and format in `CF_HDROP`, where it points to a temporary file in the user's local app data folder. See the above image and https://learn.microsoft.com/en-us/windows/win32/shell/clipboard#cf_hdrop.

If we were to drag and drop the image into Windows File Explorer, we can infer that it respects `CF_HDROP` because the resulting file is thus saved as 'Seychelles_parakeet_pair.jpg' and with a JPEG format, which is what we want.

![image](https://github.com/files-community/Files/assets/6560270/92c5badb-8950-4b17-8d82-5cc0cff00905)

### Requirements

- When Files is a drop target from other programs, Files will inspect CF_HDROP to determine if it is suitable for copying/moving files, and otherwise fallback to a different clipboard format.

### Files Version

2.5.1.0

### Windows Version

10.0.19045.2965

**Comment by yaira2** [comment]
@Trinitek thank you for your feedback, do you want to work on this?

**Comment by Trinitek** [comment]
It might be a few days before I can find the time, but I'd be happy to try.

**Comment by Trinitek** [comment]
I was playing around with this earlier and I totally forgot that the clipboard exposes a different set of formats like `FileGroupDescriptorW` for drag-drop operations. So this likely won't involve `CF_HDROP` at all for the use case that I stated in the original issue.

**Comment by Josh65-2201** [comment]
Should this be merge with to https://github.com/files-community/Files/issues/11735

**Comment by Trinitek** [comment]
> Should this be merge with to #11735

That issue looks like drag-and-drop _from_ Files, not to it. This issue doesn't cover it.

**Comment by yaira2** [comment]
It goes both ways
