### ISSUE TITLE
Bug: Misalignment Between Separators

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12792]
### Description

There is a slight misalignment with the separators. When no item is selected, there is a larger left offset compared to the right.
![Capture d'écran 2023-06-29 202329](https://github.com/files-community/Files/assets/128183422/9f227359-6364-4fec-bdfd-ec3bf20f287b)
![Capture d'écran 2023-06-29 202336](https://github.com/files-community/Files/assets/128183422/4b4c2409-9401-4b72-9af2-05e74608b363)

### Steps To Reproduce

1. Open Files
2. Go to a folder

### Requirements

Identify the cause of the misalignment

### Files Version

Dev

### Windows Version

22H2 22621.1848

### Log File

No need.

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.
