### ISSUE TITLE
Feature: Add action to initialize a folder as a Git repo

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#12799]
### What feature or improvement do you think would benefit Files?

Adding an action to initialize a folder as a Git repo aligns with our vision to improve developers workflows. Users will be able to access these actions once #12440 is implemented.

### Requirements

- Add action to initialize a folder as a Git repo

### Files Version

v2.5.11

### Windows Version

Windows 11

**Comment by yaira2** [comment]
@xmamalou

**Comment by mdtauk** [comment]
Cloning a repo.
Creating a new repo.
These sound like items in the New flyout
![image](https://github.com/files-community/Files/assets/7389110/48b6e3cb-9784-46d8-ab09-dafabffabb90)

Creating a new repo, would that require an empty folder to do it, or would doing it to an existing folder, commit the contents and then turn it into a tracked repo folder?

**Comment by yaira2** [comment]
It'll require an existing folder but it could be empty.

**Comment by Welding-Torch** [comment]
Can someone share a screenshot of where this feature is? I can't seem to find it.

**Comment by Josh65-2201** [comment]
It using the command bar. Click the address bar in the folder you want to be a git repo > type `>git` > should see the option to click on

**Comment by Lukiluc29** [comment]
> It using the command bar. Click the address bar in the folder you want to be a git repo > type `>git` > should see the option to click on

Personally, I can't create a Git folder. It only shows me executable commands that shouldn't be here.
![Capture d'écran 2023-08-29 171035](https://github.com/files-community/Files/assets/128183422/50b82432-18b2-4017-8e70-e58e5248ebc1)

**Comment by yaira2** [comment]
> Can someone share a screenshot of where this feature is? I can't seem to find it.

@Welding-Torch this feature wasn't released yet, it'll be included in the next release.

**Comment by Welding-Torch** [comment]
Thank you @Josh65-2201 and @Lukiluc29, I appreciate the explanations.

@yaira2 Oh, I was misled by this line in the release notes, as can be seen here:
![image](https://github.com/files-community/Files/assets/46340124/68e1e840-b92b-4d65-9d32-2f1ff3934452)

Thank you ❤️

**Comment by yaira2** [comment]
It was technicallyy included in v2.5.20 but the only way to access it is by assigning a keyboard shortcut (there isn't a UI for this either).
