### ISSUE TITLE
Make pull request window not appear unless pull was requested + add "up to date" notif when pulling

### ISSUE THREAD

**Issue by xmamalou** [files-community/Files#12797]
### What feature or improvement do you think would benefit Files?

Sometimes, when you navigate a folder in Files that is also a git repo with a remote branch associated with it, a pull popup will appear automatically when Files detects that the local branch is out of date. I feel it'd be better if that popup appeared only if the user explicitly asked to pull from a remote branch (personally made me do accidental pulls and thus lose some progress). 

Also, it'd be nice if the pull button showed a balloon notification -or anything similar- that the branch is already up to date, as it currently shows nothing, thus seeming more like the button doesn't work.

### Requirements

- Make the popup appear only when pull button is clicked on
- Make the pull button show "Branch is up to date" when clicking on it and branch is up to date.

### Files Version

2.5.10.0

### Windows Version

10.0.22621.1928

**Comment by yaira2** [comment]
> a pull popup will appear automatically when Files detects that the local branch is out of date

This sounds like a bug, it's only supposed to update if the users explicitly clicks the button on the status bar. Can you open a new issue as a bug report?

> Also, it'd be nice if the pull button showed a balloon notification -or anything similar- that the branch is already up to date, as it currently shows nothing, thus seeming more like the button doesn't work.

Starting in the next release, the status bar will display the number of incoming and outgoing commits.
