### ISSUE TITLE
Feature: Add support for editing Git username from settings

### ISSUE THREAD

**Issue by xmamalou** [files-community/Files#12798]
### What feature or improvement do you think would benefit Files?

The current git repo management tools are really good, but it'd be nice to see them extended. Currently, stuff like repo initialization, remote branch adding or committing can be done only through the terminal or through the git GUI client (which I personally find a bit clunky). 

### Requirements

- Add option in the settings to add/view git users

### Files Version

2.5.10.0

### Windows Version

10.0.22621.1928

**Comment by yaira2** [comment]
> Add options in the "create branch" menu for adding remote branches

The next release will have support for pushing commits to remote repos. @ferrariofilippo do you know if this will publish branches as well?

**Comment by yaira2** [comment]
#2780 will unlock more possibilities for making Git commands easily accessible without cluttering the UI.

**Comment by yaira2** [comment]
@xmamalou I just tested and I can confirm that it works to publish new branches. This feature is available in the latest preview build https://files.community/download.

**Comment by yaira2** [comment]
> Add -in the context menu, probably- an option to initialize folder as a git repo

We're trying to avoid adding options to the context menu, would allowing users to assign a keyboard shortcut and making this accessible from the command palette be satisfactory?

**Comment by yaira2** [comment]
> Add option in the settings to add/view git users

Can you elaborate on this point?

**Comment by xmamalou** [comment]
> Can you elaborate on this point?

Trying to commit changes on a repo without configuring a username and a user email will fail, so I thought having a place where someone can configure those would be neat

**Comment by yaira2** [comment]
I believe the username is whatever you set in command line but I'll refer to @Ferrario-Filippo on this.

**Comment by xmamalou** [comment]
> I believe the username is whatever you set in command line but I'll refer to @Ferrario-Filippo on this.

Ye, I know, the feature I mentioned was about having the option to edit this info from within files rather than exclusively a terminal

**Comment by yaira2** [comment]
There is a good chance we won't add the option to edit the username, but I'll leave this open for discussion to give other users time to add their own feedback.

To add some background, we don't intend for Files to replace dedicated Git clients or even command line. The goal of the integration is to provide context and quick access to actions when users are browsing their Git folders.

**Comment by ferrariofilippo** [comment]
I'm not sure about a setting to edit username/email, but I think we should include one to login/logout/switch account

**Comment by xmamalou** [comment]
> To add some background, we don't intend for the Git features to replace dedicated Git clients or even command line. The goal of the integration is to provide context and quick access to actions when users are browsing their Git folders.

Ah, understandable. Thanks 👍

**Comment by yaira2** [comment]
Merging with #13049.
