### ISSUE TITLE
Bug: The length of tag names is not limited

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#12800]
### Description

The length of tag names is not limited. If I create a new tag with too long name, the Edit and Delete buttons are no longer visible and the app becomes unstable.
![image](https://github.com/files-community/Files/assets/66369541/3f9563b3-a3a5-4fdc-bc05-1468fca40521)

### Steps To Reproduce

1. Create a new tag with too long name.
2. The Edit and Delete buttons are no longer visible and the app becomes unstable.

### Requirements

There should be a length limit on tag names.

### Files Version

2.5.10.0

### Windows Version

10.0.19044.3086

### Log File

n/a

**Comment by QuaintMako** [comment]
What should the limit be? Something arbitrary?

**Comment by hishitetsu** [comment]
Yes, it's arbitary. But I think 64 characters is enough.

**Comment by mdtauk** [comment]
This also brings up another question, do we truncate with an ellipses, or wrap these tag labels?

**Comment by hishitetsu** [comment]
It would be better to truncate with an ellipses since the full name is displayed when the cursor is hovered over the tag.

**Comment by mdtauk** [comment]
> It would be better to truncate with an ellipses since the full name is displayed on a tooltip when the cursor is hovered over the tag.

Character limits seem like an obvious fix, but languages like German use very long word combinations, so a limit for one language, may be too much for another.

**Comment by hishitetsu** [comment]
I see, then 256 characters limit is sufficient, isn't it? In any case, I think the limit is necessary to avoid making the app unstable.
 256 characters tag name doesn't seem to make the app unstable.

**Comment by QuaintMako** [comment]
I'd suggest combining both ideas : limit to 256 characters, and implement a mechanism of wrapping in the Tags edition?

**Comment by mdtauk** [comment]
> I see, then 256 characters limit is sufficient, isn't it? In any case, I think the limit is necessary to avoid making the app unstable. 256 characters tag name doesn't seem to make the app unstable.

256 is a fair number, but you can truncate the characters displayed also.

**Comment by mdtauk** [comment]
> I'd suggest combining both ideas : limit to 256 characters, and implement a mechanism of wrapping in the Tags edition?

Wrapping may be possible too, but that may have an impact on row heights, and so truncating with an ellipses, may have to suffice.

**Comment by Lukiluc29** [comment]
I wanted to modify a label that I saved, but after trying to modify it again, the edition does not work. I don't know if it's related to the number of characters.
<img width="619" alt="Capture d'écran 2023-06-30 133332" src="https://github.com/files-community/Files/assets/128183422/180762f4-df60-46b0-a0bd-401941556af1">

**Comment by mdtauk** [comment]
I think its also worth looking at how we present the tags, I think @yaira2 was happy with this idea I proposed when we were looking at the sidebar design.

![image](https://github.com/files-community/Files/assets/7389110/ea0aea74-a501-4d7a-a482-5f1cc579ff0d)

**Comment by hishitetsu** [comment]
> I wanted to modify a label that I saved, but after trying to modify it again, the edition does not work. I don't know if it's related to the number of characters.

That is because the tag name is too long and hides the text box, so truncating with an ellipses will solve the problem.

**Comment by mdtauk** [comment]
> > I wanted to modify a label that I saved, but after trying to modify it again, the edition does not work. I don't know if it's related to the number of characters.
> 
> That is because the tag name is too long and hides the text box, so truncating with an ellipses will solve the problem.

This is something to note, because if the tag label is truncated, the edit TextBox will still have to display the whole string.
We also do not yet have validation to handle the 256 character count.

**Comment by Lukiluc29** [comment]
> That is because the tag name is too long and hides the text box, so truncating with an ellipses will solve the problem.

So I don't need to report on it. The problem will therefore be solved in this report if I understand correctly?

**Comment by hishitetsu** [comment]
> So I don't need to report on it. The problem will therefore be solved in this report if I understand correctly?

Yes.

**Comment by yaira2** [comment]
I'll look into this
