### ISSUE TITLE
Bug: Status center doesn't indicate when archive is decompressed

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12809]
### Description

I have noticed an issue regarding decompression message in File Explorer. When I compress a folder, a message appears confirming that the file has been successfully compressed. However, when I decompress a file, there is no message displayed in the status center.

### Steps To Reproduce

1. Extract items from archive
2. Open status center and look for the status

### Requirements

Update status center when the items are extracted.

### Files Version

v2.5.11

### Windows Version

22H2 22621.1848

### Log File

No need.

**Comment by yaira2** [comment]
I can reproduce this in v2.5.11.

**Comment by ferrariofilippo** [comment]
Does it happen with big archives too?
