### ISSUE TITLE
Bug: STRG-e key combination crashes Files

### ISSUE THREAD

**Issue by JohRest** [files-community/Files#12801]
### Description

When I press right ctrl + e when Files has the focus it crashes.

### Steps To Reproduce

Give focus to the program
Press rigth ctrl + e

### Requirements

Fix crash that occurs when right ctrl + e is pressed.

### Files Version

2.5.10.0

### Windows Version

22621.1928

### Log File

[debug.log](https://github.com/files-community/Files/files/11916488/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.
