### ISSUE TITLE
Network Folder Display Slow

### ISSUE THREAD

**Issue by littlefooch** [files-community/Files#12808]
### Description

Very slow in comparison to File Explorer
I have a LAN with 10 Win 11 machines
FE displays in 2-4 sec
Files displays in 10-20 s
Order of magnitude difference

### Concerned code

N/a

### Gains

improved UI performance

### Requirements

- eg. Using a specific design pattern.
- eg. Separating Interface I into three new interfaces I1, I2 and I3.
- eg. Regrouping the duplicated process into a new helper.

**Comment by yaira2** [comment]
Thank you for your feedback, we're tracking this and other optimizations in #12014.
