### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by dotdotcurrve** [files-community/Files#12807]
### What feature or improvement do you think would benefit Files?

The default font size is much bigger than the default File Explorer. Is there any way to change this?

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.5.10.0

### Windows Version

10.0.22621.1848

**Comment by yaira2** [comment]
Thank you for the feedback, the font size can't be changed but if it helps, you can enable the compact spacing option in Settings for a more dense layout.
