### ISSUE TITLE
"Back" should go up

### ISSUE THREAD

**Issue by brutlern** [files-community/Files#12817]
### What feature or improvement do you think would benefit Files?

Ever since Windows exists, I hated that "Back" doesn't automatically go "Up" in the folder, instead of cycling the folder history. There should be an option for the "Back" action (specifically "Backspace" on the keyboard or the "Back" side button on the mouse) to go "Up" instead.

### Requirements

By default "Back" action should go "Up" a the folder instead, maybe an option to toggle this behavior for the handful of people who actually want "Back" to go back, and not "Up".
Option to map button to required action ( maybe not everyone wants "Backspace" to be the default button).

### Files Version

2.5.10.0

### Windows Version

10.0.22621.1928

**Comment by Josh65-2201** [comment]
This already exists with the Up arrow next to the reload button

**Comment by yaira2** [comment]
Thank you for your feedback, as Josh mentioned, Files includes options for both actions. We're also working on keyboard remapping, so that'll do the trick for you. You can subscribe to #9559 to be notified when it's implemented.

**Comment by mdtauk** [comment]
Back should go Back.  Up should go up a level.  Doing anything different will add confusion.

**Comment by yaira2** [comment]
@brutlern This feature will be included in the next release. Please see #9559 for more details.
