### ISSUE TITLE
Bug: "Open in new window" follows the startup settings

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#12812]
### Description

When I open a folder with "Open in new window", I expect only that folder to be opened in the new window. However, if the startup settings is "Continue where you left off", tabs in the original window are opened together.

### Steps To Reproduce

1. Set the startup settings other than "Open a new tab".
2. Open a folder with "Open in new window".
3. Tabs other than the folder you want to open are also opened according to the startup settings.

### Requirements

Only the selected folder should be opened in a new window.
However, if the user starts the app by specifying a folder from the command line, it should follow the startup settings as before.

### Files Version

2.5.11.0

### Windows Version

10.0.22621.1848

### Log File

n/a

**Comment by yaira2** [comment]
Thank you for reporting this issue.
