### ISSUE TITLE
Integrate FUSE based open source cloud drive software.

### ISSUE THREAD

**Issue by upintheairsheep** [files-community/Files#12811]
### What feature or improvement do you think would benefit Files?

Add a semi-package manager to install open source FUSE clients for cloud (mainly), network, etc drives without having to install the official manufacturers program, which will start to slow down the computer. Additionally, it will include GUI for the setup process. The external FUSE mount software should not run in the background unless the user is actively using a cloud drive. rClone should be the first and foremost one. All FUSE clients should be prebuilt as an EXE and portable, and only run when the specific cloud drive is in use.

Issues of official cloud clients: 
1. Usually always run in the background, slowing the system down, especially on lower-end systems
2. Have unnecessary "automatic file backup" features, which is usually unwanted due to storage limitations and privacy reasons
3. Most of the time, these tools do not support multiple users (ex: home and work/school )
4. Many people do not want to take the extra length to install the software required.
5. Unwanted integrations between the cloud service and operating system and/or software can cause errors or problems in the future

### Requirements

see above

### Files Version

N/A

### Windows Version

N/A

**Comment by Josh65-2201** [comment]
Thanks for the feedback. Are you asking to have a cloud provider called FUSE added? If so can you link to the client install.
If you are asking for Files to integrate the cloud drive clients into the app? If so that properly isn't going to happen as Files doesn't have the dev team to add and maintain all the APIs for them.

**Comment by yaira2** [comment]
Thank you for your feedback, as Josh mentioned above, we don't currently have the capacity to implement support for cloud services but if you can link us to the client, we'll be happy to add support for detecting the client.

**Comment by upintheairsheep** [comment]
No, I want support for mounting FUSE-based cloud storage. FUSE is a drive
mounting tool.
