### ISSUE TITLE
Bug: Deleting tags after changing layout may cause crash

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#12814]
### Description

As the title described. It is always reproduced by the following steps.

### Steps To Reproduce

1. Set "Home" tag and "Work" tag to a folder in the details layout.
2. Change the layout to the grid layout.
3. Change the layout back to the details layout.
4. Delete "Home" tag.
5. Delete "Work" tag.
6. The app will crash.

### Requirements

Fix crash.

### Files Version

2.5.11.0

### Windows Version

10.0.22621.1848

### Log File

[debug.log](https://github.com/files-community/Files/files/11923916/debug.log)

**Comment by yaira2** [comment]
Thank you for reporting this issue.

**Comment by hishitetsu** [comment]
Certainly this avoids crashes, but the underlying problem is that the binding to the grid layout occurs despite the change to the details layout. This may cause other problems besides this crash.
