### ISSUE TITLE
Drag and drop into the software. 

### ISSUE THREAD

**Issue by SobanMub** [files-community/Files#12815]
### What feature or improvement do you think would benefit Files?

Hi,

I am graphic designer and I continuously need to drag images, videos and pdfs into the software. But 'files' doesnt support it at all which is great kill for me. kindly update the software with drag and drop feature for softwares.

thank you

### Requirements

Hi,

I am graphic designer and I continuously need to drag images, videos and pdfs into the software. But 'files' doesnt support it at all which is great kill for me. kindly update the software with drag and drop feature for softwares.

thank you

### Files Version

2.5.10.0

### Windows Version

10.0.22621.1928

### Comments

Hi,

I am graphic designer and I continuously need to drag images, videos and pdfs into the software. But 'files' doesnt support it at all which is great kill for me. kindly update the software with drag and drop feature for softwares.

thank you

**Comment by Josh65-2201** [comment]
Thanks for the feedback what software are you trying files into drag to.

**Comment by SobanMub** [comment]
I use coreldraw.

**Comment by Josh65-2201** [comment]
Thanks it may be fix when #11735 is also fixed.

**Comment by yaira2** [comment]
@SobanMub thank you for your feedback, as Josh mentioned, this issue is being tracked in #11735. You can subscribe to that issue to be notified when it's fixed.
