### ISSUE TITLE
App crashes when opening from the Home view with an inexistent pinned folder

### ISSUE THREAD

**Issue by softtama** [files-community/Files#12818]
### Description

- App crashes when opening from the Home view. 
- It works fine when I quickly navigate to other folder/view before it crashes.
- But it will crash anyway when I switch back to the Home view.
- It only happens if the app is in windowed mode.
- If I quickly maximize the window in the Home view, the app will not crash.
- After I maximize the window in the Home view and I switch back to other folder/view and then I restore to the windowed mode, the app will crash.
- From my observation, it is occurred when an inexistent pinned folder is displayed on "Quick access" section of the Home view.
- In this case, the inexistent pinned folder on my PC is located on an external hard drive which I do not currently connect to the PC.

### Steps To Reproduce

The description I wrote is clear enough to reproduce the issue.

### Requirements

- The app should not crash with the condition I wrote on the description.

### Files Version

2.5.10.0

### Windows Version

10.0.22621.1848

### Log File

[debug.log](https://github.com/files-community/Files/files/11926583/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report. Can you give the following information.
- Do you have tags enabled for the home page?

**Comment by softtama** [comment]
> Thanks for the report. Can you give the following information.
> 
> * Do you have tags enabled for the home page?

Yes, I enabled them.

**Comment by Josh65-2201** [comment]
It likely the same issue as #12370 then.

**Comment by yaira2** [comment]
@softtama can you see if disabling the tags widget fixes the crash?

**Comment by yaira2** [comment]
This issue will be resolved in the upcoming v2.5.20 release.
