### ISSUE TITLE
Bug: Entering `%appdata%` into path bar crashes app

### ISSUE THREAD

**Issue by misfit-franck** [files-community/Files#12828]
### Description

When performing a specific search on the file search bar,
for example: "%appdata%
the software fails to resolve the requested path and crashes: Either it restarts, this time on the desired path, or you have to restart it manually. 
Most of the time, problems are solved automatically, but only after a long period of crashing and waiting.

### Steps To Reproduce

1. Use column layout
2. Enter `%appdata%` into the path bar

### Requirements

Fixed a crash that occurred when a system command was typed directly into the Files search bar

### Files Version

2.5.10.0

### Windows Version

22621.1928

### Log File

[debug.log](https://github.com/files-community/Files/files/11929666/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by yaira2** [comment]
@misfit-franck which layout mode are you using?

**Comment by misfit-franck** [comment]
I currently using Columns Layout

**Comment by yaira2** [comment]
@misfit-franck is this still an issue in the preview version? https://files.community/download

**Comment by misfit-franck** [comment]
@yaira2 I don't think, but in preview version, this issue does not occur.

**Comment by Josh65-2201** [comment]
Thanks for checking, please comment if it happens again.
