### ISSUE TITLE
I can't unpin from favorites or sort favorites.

### ISSUE THREAD

**Issue by BarkBijli** [files-community/Files#12823]
### Description

I can't unpin from favorites or sort favorites. When I try to unpin from favorites the application crashes and closes and when I try to sort and press "ok", it doesn't work either. The software is awesome, but it has these bugs and is a bit slow too. I am currently using windows 10. Version 22H2, build 19045.3155. I hope they fix this. Thanks!

### Steps To Reproduce

1. Unpin doesn't work.
2. Sorting favorites doesn't work.
3. Too slow.
4. 
It closes on its own sometimes.

### Requirements

I can't unpin from favorites or sort favorites. When I try to unpin from favorites the application crashes and closes and when I try to sort and press "ok", it doesn't work either. The software is awesome, but it has these bugs and is a bit slow too. I am currently using windows 10. Version 22H2, build 19045.3155. I hope they fix this. Thanks!

### Files Version

2.5.10.0

### Windows Version

windows 10. Version 22H2, build 19045.3155

### Log File

[debug.log](https://github.com/files-community/Files/files/11928543/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Merging with #12551. You can check there or click subscribe in the right sidebar for updates.
