### ISSUE TITLE
Bug: Crash when dragging items to another Files window and hovering over the folder

### ISSUE THREAD

**Issue by mambans** [files-community/Files#12827]
### Description

When dragging file/files to another folder in another window and hovering over the folder to open the folder before dropping the files, the window I'm dragging two crashes.

If relevant, both folders contains a lot of images/videos.

(Side question, Are there anyway to disabled the hovering to open folder?)

It also just crashed when I opened a folder (containing many images/videos)
[debug.log for second crash when just opening a folder](https://github.com/files-community/Files/files/11929525/debug.log)

### Steps To Reproduce

1. Have two windows open with folders inside them
2. Drag a file from first window to second window and hover over a folder to open the folder (before dropping the file)
3. Second window crashes

### Requirements

When dragging files to another folder in another window, it should not crash.

### Files Version

2.5.10.0

### Windows Version

22621.1928

### Log File

[debug.log](https://github.com/files-community/Files/files/11929498/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

No there isn't a setting to disable opening a folder on drag hover. Why would you want this?

**Comment by mambans** [comment]
> Thanks for the report, I've added this to the project board.
> 
> No there isn't a setting to disable opening a folder on drag hover. Why would you want this?

Oke thanks.

I personally would like a option like that because if the thumbnails size of the file from the first window is larger than the thumbnails on the second window, then It is hard to see which folder I am hovering to drop the file into and I have to pause the confirm its the correct folder.

![image](https://github.com/files-community/Files/assets/23280380/fad0d7e9-688f-4e61-8651-55e513bd3126)

https://github.com/files-community/Files/assets/23280380/785d8c56-c664-4ccc-b09a-09f2a2ebae94

**Comment by Josh65-2201** [comment]
Thats being tracked in #12556. You can check there or click subscribe in the right sidebar for updates.

**Comment by mambans** [comment]
> Thats being tracked in #12556. You can check there or click subscribe in the right sidebar for updates.

Ah thanks!

**Comment by yaira2** [comment]
@mambans Is this still an issue in the preview version? https://files.community/download/preview

**Comment by mambans** [comment]
> @mambans Is this still an issue in the preview version? https://files.community/download/preview

No, I can't reproduce the issue in the preview build. 👍 👍

**Comment by yaira2** [comment]
Awesome! Thank you for checking.
