### ISSUE TITLE
Feature: Tag section on Detials Pane, should include "Add Tags" button

### ISSUE THREAD

**Issue by mdtauk** [files-community/Files#12821]
### What feature or improvement do you think would benefit Files?

As mentioned in #12810 when a file or folder has no tags, a tags section still shows in the detail pane.

![image](https://github.com/files-community/Files/assets/7389110/fdb49d44-dd57-48cd-bfb8-c587a1b2de89)

Rather than hiding this when no tags have been attached to the item, we could put an "Add Tag" or "Add Tags" button.

![image](https://github.com/files-community/Files/assets/7389110/b0bfec44-6e39-4e2b-90d0-969a85472f8d)
![image](https://github.com/files-community/Files/assets/7389110/573fed30-aad7-4a23-b4ab-4950b30d6bd8)

### Requirements

- This will simplify adding tags to items, and emphasise the feature to people who are not familiar with it.

### Files Version

2.5.10

### Windows Version

22621.1928

**Comment by yaira2** [comment]
What's the expected action after clicking the button?

**Comment by mdtauk** [comment]
What is the current UX for adding tags to an item?  Is this not a menu flyout?

**Comment by yaira2** [comment]
It's usually a menu flyout

**Comment by mdtauk** [comment]
> It's usually a menu flyout

Then we could make it a DropDownButton if you'd like, which would indicate it brings up a flyout.

![image](https://github.com/files-community/Files/assets/7389110/5cab350b-f5cb-4bef-a9c2-cb57c1e493bd)

**Comment by mdtauk** [comment]
For completion sake, here is how the details pane could look with tags and git repo detials

![image](https://github.com/files-community/Files/assets/7389110/0214ae91-329f-4d40-b641-e95753fd316e)

**Comment by Lukiluc29** [comment]
> For completion sake, here is how the details pane could look with tags and git repo detials
> 
> ![image](https://user-images.githubusercontent.com/7389110/250564482-0214ae91-329f-4d40-b641-e95753fd316e.png)

Sorry to intrude on your conversation, but I think this concept is beautiful
