### ISSUE TITLE
Folder Tree

### ISSUE THREAD

**Issue by MikeN68** [files-community/Files#12829]
### What feature or improvement do you think would benefit Files?

Clearly this is a marked improvement over the default built in File Explorer but I really wish you could incorporate expanding to the current folder in the 'navigation pane'.  
Thanks

### Requirements

Not really sure how to complete this.

### Files Version

2.5.10.0

### Windows Version

10.0.22621.1702

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #1928. You can check there or click subscribe in the right sidebar for updates.

**Comment by yair100** [comment]
@MikeN68 Tree View is currently available in preview https://files.community/download. It will be included in the next stable release.
