### ISSUE TITLE
Right Click Drag not Supported / Changing Selected Files background/foreground etc

### ISSUE THREAD

**Issue by dbareis** [files-community/Files#12824]
### What feature or improvement do you think would benefit Files?

I am just trying this app now...

Explorer has a right-click drag option. It is buggy in that it displays a misleading (at best) message when dragging but it allows you to easily copy/move, create shortcuts etc.

Another thing I don't like is the lack of theme options such as modifying how selected files look, but for now I will continue to try it as a Windows Explorer replacement...

### Requirements

Compatible with Windows Explorer.  In the long run I will not use this app without it.

### Files Version

2.5.10.0

### Windows Version

10.0.19045.3086

**Comment by yaira2** [comment]
Thank you for your feedback, we're tracking this request in #1396
