### ISSUE TITLE
Bug: App crashed while moving files

### ISSUE THREAD

**Issue by dbareis** [files-community/Files#12825]
### Description

Your app dies during move operation.  It closed one of the two windows open and opened a new one in a new (not used by me Location):  C:\Users\Dennis\Downloads

Note I was moving from the **configured download location** (not in "users"), it seems to have moved all my download files and reconfigured the download directory!

### Steps To Reproduce

Don't know more than above

### Requirements

* Not crash
* Not reconfigure my directory settings  (it seems to have also played with "my pictures", I don't seem to be able to start Explorer to check if permanent change to Windows settings or just this app misbehaving.
permanent

### Files Version

C:\Users\Dennis\Downloads

### Windows Version

11

### Log File

[debug.log.zip](https://github.com/files-community/Files/files/11928843/debug.log.zip)

**Comment by Josh65-2201** [comment]
Thanks for the report. Can you give the following information.
- What's your Files and Windows version. You can get these in Files settings > About > Click "Copy" on the first box.
- Can you fill out the steps to reproduce with step by step on what you did to have Files crash, as your description is unclear.

**Comment by yaira2** [comment]
@dbareis can you confirm how you were transferring the files? Drag & drop, copy & paste etc.

**Comment by dbareis** [comment]
@yaira2 As your apps drag & drop doesn't support moving (as far as I can see), I cut and pasted the files.

v: 2.5.10.0 / 10.0.19045.3086
I'm surprised you need 2 x copy to get the information you want and then without titles...  I'm also surprised the debug log doesn't contain that and way more info.

I've stopped using the app as it reconfigured Windows settings for at least downloads & my pictures.  I think the crash might have done this but either way it shouldn't ever happen.

**Comment by yaira2** [comment]
> I've stopped using the app as it reconfigured Windows settings for at least downloads & my pictures.

Can you elaborate on this? Files isn't supposed to change any Windows settings.

**Comment by dbareis** [comment]
For the life of my very old laptop, downloads was configured by me to be at: "D:\TMP\### Download ###", running Files now also shows it there currently (as I restored its location), it was also correct before the crash as that was my source directory.  After the crash it points to it's default location under "users", "My pictures" also got moved but not under there, (perhaps a random direction within the library?).

**Comment by yaira2** [comment]
Can you try to reproduce this issue again so we have exact steps to reproduce it? I understand if it's too much of an inconvenience, but it'll help us investigate the issue so that it doesn't happen again.

**Comment by dbareis** [comment]
I have already tried, but I think there was a prompt about conflicting files and I said overwrite.  I tried that again a few times and it didn't crash.  It sounds like the debug log needs to record a lot more information.  I looked for dump files but couldn't find any.

**Comment by yaira2** [comment]
It doesn't look like the crash was related to the file transfer.

**Comment by Josh65-2201** [comment]
@dbareis have you been able to reproduce this issue on 2.5.21.0?

**Comment by yaira2** [comment]
@dbareis are you still able to reproduce this? We've made a number of improvements in v2.5.21 but we'd like confirmation before closing this issue.

**Comment by dbareis** [comment]
Hi,

I'm not using the app, I might try it again in 6 months or so

**Comment by yaira2** [comment]
Thanks for the response.
