### ISSUE TITLE
Poor performance

### ISSUE THREAD

**Issue by Mason-17** [files-community/Files#12822]
### Description

The app takes a long time to open, and when open, is slow to navigate throughout the app.
Note: once the app opens for the first time, it opens faster, but not as fast as other apps. Also, regardless of the above, navigation is laggy. The app was installed via the .appinstaller file (I made an issue before). 

### Steps To Reproduce

1. Open app
2. wait
3. app opens
4. use app
5. wait

### Requirements

- Snappier opening of the app and faster navigation

### Files Version

2.5.10.0

### Windows Version

10.0.19045.3086

### Log File

No log

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #4180 and #12614. You can check there or click subscribe in the right sidebar for updates.

Right now it mostly limited by WinAppSDK but will improve over time.

**Comment by yaira2** [comment]
@Mason-17 thank you for your feedback, aside from startup speed, is there any other actions that are slow for you?

**Comment by Mason-17** [comment]
> @Mason-17 thank you for your feedback, aside from startup speed, is there any other actions that are slow for you?

Mostly just navigation between folders. I will note however that coming back to my laptop after a period of time and opening the app does cause a slow startup time.

**Comment by yaira2** [comment]
I've noticed that as well, the first step we're taking to address startup speed is to add a splash screen. They will provide users with an immediate response when opening the app. We're working on additional improvements as well.

**Comment by Mason-17** [comment]
> I've noticed that as well, the first step we're taking to address startup speed is to add a splash screen. They will provide users with an immediate response when opening the app. We're working on additional improvements as well.

Awesome. I'm looking forward to it. If you need me to test anything, please let me know.

**Comment by yaira2** [comment]
We're excited to share that startup performance will be significantly improved in the upcoming release of version 3. You can download the preview version from our website https://files.community/download.

**Comment by yair100** [comment]
@Mason-17 we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
