### ISSUE TITLE
Bug: Clicking new tab button crashes app

### ISSUE THREAD

**Issue by notcooler** [files-community/Files#12826]
### Description

i clicked a new tab and it crasehed thats it, did nothing else

### Steps To Reproduce

Oopen files
click new tab
and it crashes

### Requirements

It crashes when opening new tab

### Files Version

2.5.10.0

### Windows Version

10.0.22621.1848

### Log File

[debug.log](https://github.com/files-community/Files/files/11929113/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
@notcooler can you try again and see if it crashes consistently?

**Comment by notcooler** [comment]
> @notcooler can you try again and see if it crashes consistently?

Yea after i reported this i was using the computer for a bit more, and it doesnt crash everytime but it crashes sometimes.

Although it might be that i was running low on ram because i was doing some deep learling tests, but i am not sure on that.

**Comment by yaira2** [comment]
Based on the logs, it seems to be some sort of race condition. It's not specific to the "new tab" button but it's one of the more noticeable places.

**Comment by yaira2** [comment]
@notcooler this issue should be resolved in the upcoming v2.5.20 release.

**Comment by notcooler** [comment]
> @notcooler this issue should be resolved in the upcoming v2.5.20 release.

Okay thank you man, have a good day!
