### ISSUE TITLE
Drag to resize the window from the top border results to move.

### ISSUE THREAD

**Issue by cos1110** [files-community/Files#12820]
### Description

When you want to resize the window, you click on the upper border of the window. However this results to moving instead of resizing.

### Steps To Reproduce

1. Go to the upper side of the window horizontal border.
2. Let the the cursor become "resize" (up-down arrow).
3. Click and drag.

### Requirements

Window should be resized from the top border.

### Files Version

2.5.10.0

### Windows Version

10.0.19045

### Log File

[debug.log](https://github.com/files-community/Files/files/11926970/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #10813. You can check there or click subscribe in the right sidebar for updates.
