### ISSUE TITLE
Bug: Performance Issues when Viewing Git Folders: Slow Loading and Error Message

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12837]
### Description

I'm experiencing performance issues when viewing Git folders. In the "Details" view, the Git column data takes a long time to load, and in the "Columns" view, files/folders take a while to appear and only show up simultaneously after a long wait. Additionally, when this occurs and there is a significant delay, an error message appears stating that my disk is disconnected, even though it is my internal disk. Interestingly, when I navigate to a large folder like "Windows," it takes less time to load everything, and files load progressively. In reality, I don't really know if it's a performance issue or a crash when generating files or folders.

### Steps To Reproduce

1. Open Files
2. Go to a folders Git
3. Click on a folder in the Détails or Column mode

### Requirements

1. Improve the loading efficiency of files/folders in Git folders, allowing them to load progressively rather than all at once after a long delay.
2. Compare performance with other folders like "Windows" to identify any discrepancies and improve the overall loading speed in Git folders.
3. Address any errors or false disk disconnection messages that appear during extended loading times.

### Files Version

Dev

### Windows Version

22H2 22621.1848

### Log File

![Capture d'écran 2023-07-03 163602](https://github.com/files-community/Files/assets/128183422/11ca7b1d-c613-47ae-89c8-87b5a045e325)
![Capture d'écran 2023-07-03 163620](https://github.com/files-community/Files/assets/128183422/0f5ab614-76fd-498f-ba08-bfdf524c7380)
![Capture d'écran 2023-07-03 163643](https://github.com/files-community/Files/assets/128183422/8aa9b449-f4b3-4b98-9dbe-9f9778a8cf72)
![Capture d'écran 2023-07-03 163653](https://github.com/files-community/Files/assets/128183422/9e1e09a7-fe48-4469-9b1c-263e7e53d1ad)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.
