### ISSUE TITLE
FTP - Documentation

### ISSUE THREAD

**Issue by dwilbourn618** [files-community/Files#12835]
### What feature or improvement do you think would benefit Files?

There is no documentation on connecting to FTP drives with Files. There are a number of Issues that mention improvements and changes to FTP and otherwise imply that this is possible but nothing whatsoever in the documentation on how to do it. 

### Requirements

Enable use of FTP

### Files Version

2.5.10.0

### Windows Version

11

**Comment by Josh65-2201** [comment]
It the same as Windows File Explorer. Enter `ftp://<ip>:<port>` into the path bar or right click the network folder on the sidebar and enter the same ftp path there.

**Comment by dwilbourn618** [comment]
Well, aren't I the fool, I had no idea File Explorer could do that! 
Still, I think that just proves 
a) there is a need for documentation 
and 
b) some kind of wizard to make it even easier and obvious would make Files even better than File Explorer (which is the whole point surely!)

**Comment by dwilbourn618** [comment]
Ok, tried that but I can't get it to work. FreeCommander XE and Filezilla work fine and have both have wizards to create FTP links.

**Comment by yaira2** [comment]
Documentation is a good idea, can you open this request on the website repo? https://github.com/files-community/Website
