### ISSUE TITLE
Google Drive for Desktop

### ISSUE THREAD

**Issue by tRahErug7sTi** [files-community/Files#12832]
### What feature or improvement do you think would benefit Files?

When I load Google Drive for desktop, it is listed in the section "Drives."
I'd prefer it appear in the section "Cloud Drives"
Is that possible?

![filesapp](https://github.com/files-community/Files/assets/138404963/341677c7-27d8-444e-adae-265f8742d981)

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.5.10.0

### Windows Version

Windows 11 22H2 22621.1928

### Comments

Thanks,

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Google Drive showing in the drive section is a limitation from Google. It will also only show up in the cloud section if it set to mirror mode not streaming.

**Comment by yaira2** [comment]
@Josh65-2201 are there instructions for setting up mirror mode? Maybe we can add this to the documentation for cloud drives.

**Comment by Josh65-2201** [comment]
Googles docs page says it accessed by Opening Drive for desktop > click Settings cog wheel > click Preferences > click Folders from Drive > click My Drive syncing options > Selected Mirror files. 
There should also be a warning that it downloads all of the drives contents for offline use so it may not be an option for everyone.

**Comment by rfgamaral** [comment]
Hey there @yaira2 and @Josh65-2201!

> Thanks for the feedback, Google Drive showing in the drive section is a limitation from Google. It will also only show up in the cloud section if it set to mirror mode not streaming.

Can you clarify how is this a Google limitation? I would expect that a third-party app likes Files would have a lot of control on how things are displayed, and I can say that the current sidebar in Files is miles better than the one on Windows Explorer, so I don't quite understand how this is a Google limitation.

![Screenshot 2023-11-05 102908](https://github.com/files-community/Files/assets/96476/ab2334c0-8b88-47b3-8f2b-916ca2b952a6)

This is what I currently see when I have my Google Drive configured as streaming, which is my preference. But the duplicate Google Drive entry is kind of annoying, makes me want to just hide the "Cloud Drives" node. However, I would prefer if I could keep things separate:

- Drives: Contains only your system drives
- Cloud Drives: Contains only your cloud drives

What exactly is preventing you from adding a setting to Files where one could show/hide individual items from "Drives" and "Cloud Drives" without affecting the visibility of the other?

**Comment by yaira2** [comment]
The limitation is that Google sets it up as a regular drive, so it's automatically listed when we fetch the other drives. There are some workarounds, but we're not so excited about implementing them due to the potential impacts on startup performance

**Comment by rfgamaral** [comment]
> There are some workarounds, but we're not so excited about implementing them due to the potential impacts on startup performance.

I guess what I'm failing to understand is why simply not rendering certain individual items under certain categories in the sidebar impacts startup performance. Granted that I don't have any knowledge on how this app is built, as a developer myself, I really don't understand why a thing like this is problematic. For the record, I'm not judging or doubting, I'm just trying to understand.

**Comment by yaira2** [comment]
The challenge is identifying if a given drive is provided by Google Drive because the drive letter and name isn't always the same. There are some potential solutions and it's possible we'll implement one in the future, but they all have some downsides.

**Comment by rfgamaral** [comment]
I see, thanks for clarifying that for me, @yaira2.
