### ISSUE TITLE
Application inaccessible

### ISSUE THREAD

**Issue by Tzipirigu** [files-community/Files#12831]
### Description

I try to open the app and the UI freezes

### Steps To Reproduce

1. I open the application
2. The app crashes as soon as I open it
![Weird Bug](https://github.com/files-community/Files/assets/91142910/3a40be78-9d46-49f8-8724-a8ce6ff59b8c)

### Requirements

Fix crash that occurs when the app is opening

### Files Version

2.5.10.0

### Windows Version

Windows 11 Pro 21H2; Build: 22000.2057

### Log File

[debug.log](https://github.com/files-community/Files/files/11930307/debug.log)

**Comment by yaira2** [comment]
@Tzipirigu thank you for the report, can you check if resetting the app helps?

**Comment by yaira2** [comment]
@Tzipirigu thank you for the update, let us know if it becomes an issue again and we'll take a look.
