### ISSUE TITLE
detail tags when detail vue is on aren't enough

### ISSUE THREAD

**Issue by github-MaxCE** [files-community/Files#12830]
### What feature or improvement do you think would benefit Files?

on my music folders i normally want to see the song title, album, artist, part of set, track number, composer, etc, etc

this was easy on the normal files explorer as there was a more page with hundreds of details that you can enable, this simply doesn't exist on Files

### Requirements

- This proposal wants that there would be a more button when right clicking on the details section which will open a menu that has a list of windows supported tags and metadata info. thus allowing the user to customise each folder

### Files Version

2.5.10.0

### Windows Version

10.0.22621.1928

**Comment by yaira2** [comment]
Thank you for your feedback, we're planning to add all the columns available in File Explorer. We're already tracking this request in #8366 but if you subscribe to the issue, you'll be notified when it's implemented.
