### ISSUE TITLE
Crash on new tab click

### ISSUE THREAD

**Issue by SemyonL** [files-community/Files#12833]
### Description

Clicked new tab "+" and the app crashed:

### Steps To Reproduce

1. Have 1 open tab
2. Click "+" on the title bar with mouse

### Requirements

- New tab is opened

### Files Version

2.5.11.0

### Windows Version

10.0.22621.1848

### Log File

[debug - Redacted.log](https://github.com/files-community/Files/files/11932446/debug.-.Redacted.log)

**Comment by yaira2** [comment]
Thank you for the report, can you confirm it's the same as #12821?

**Comment by SemyonL** [comment]
Yes, looks very similar. Even crash log is almost identical.

**Comment by yaira2** [comment]
We're going to continue tracking this there, you can subscribe to #12826 to be notified when it's fixed.
