### ISSUE TITLE
Drag and Drop from Files App into Corel

### ISSUE THREAD

**Issue by curtiselliotharris** [files-community/Files#12847]
### What feature or improvement do you think would benefit Files?

For some reason I cannot drag and drop from Files App and have it load in CorelDraw or Corel product?

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.5.10.0

### Windows Version

10.0.22621.1928

**Comment by mdtauk** [comment]
Are there any system level APIs used by File Explorer, to allow Files to also be able to drag files into apps like Corel, or Discord, or Edge etc - any app that supports having drop targets for files?

**Comment by Josh65-2201** [comment]
Thanks for the report, Merging with #11735. You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
@Josh65-2201 can you add Corel to that issue so we know which apps are still not working?

**Comment by Josh65-2201** [comment]
I'm not able to edit issues anymore
