### ISSUE TITLE
Bug: Scrolling with Trackpad when connected via parsec on MacBook

### ISSUE THREAD

**Issue by jehucampos** [files-community/Files#12849]
### Description

Scrolling with trackpad doesn't function correctly when connected to Windows PC from Mac via Parsec.  Only "momentum scrolling" is possible, but result is erratic.  Dragging two fingers to scroll doesn't work as expected.

### Steps To Reproduce

1. Connect to PC with Files via Parsec on MacBook with trackpad.
2. Attempt to scroll in Files window.

### Requirements

Expected: Scroll naturally.
Actual: Scrolling is erratic and nonfunctional.

### Files Version

2.5.10.0

### Windows Version

10.0.19045.3155

### Log File

[debug.log](https://github.com/files-community/Files/files/11951070/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
@jehucampos thank you for sharing your feedback. The preview version of Files is using a newer version of WinAppSdk so it's possible there are some improvements in this area. If you're still seeing these issues, we encourage sharing this feedback on the WinAppSdk repo and sharing the link here for future reference.
