### ISSUE TITLE
Sorting in groups by date modified

### ISSUE THREAD

**Issue by dollphix** [files-community/Files#12846]
### Description

I am trying to group files and folders by year and sort the groups in a descending or ascending by year.  The files and folder in groups also need to be sorted according to date modified in a descending or ascending order.  I am finding it difficult to achieve this. Even those sorting functionalities have been implemented, achieving the above was difficult. Program default to ascending order of groups and group items with the above settings even though sorting is set to descending order year by groups and date modified of files and folders in a group. 

Kindly check on this features.

### Steps To Reproduce

1. Groups items by year
2. Sort groups in a descending order
3. sort groups items or content by date modified in a descending order

### Requirements

Not a crash but failed functionality.
Program failed to achieve the above sorting settings.

### Files Version

2.5.10.0

### Windows Version

10.0.22621.1928

### Log File

No log file to upload

**Comment by Josh65-2201** [comment]
Thanks for the report. Can you give the following information.
- A screenshot of what Files and Windows File Explorer looks like with your ordering settings.

**Comment by yaira2** [comment]
@dollphix

**Comment by dollphix** [comment]
I am trying to achieve the sorting arrangement in the attached figure.

<img width="257" alt="image" src="https://github.com/files-community/Files/assets/126979918/47141c4f-23c6-4367-bd54-1e16b1fabad8">

Sorry, I cannot show the view of files and folders on my computer. I hope the above image explains what I am trying to achieve.

**Comment by Josh65-2201** [comment]
You can do this by set
Group by > Date modified/created > Year
Group by > Descending
Sort by > Date modified
Sort by > Descending
