### ISSUE TITLE
Feature: Alternating color rows in detailed view

### ISSUE THREAD

**Issue by VCHLOROK** [files-community/Files#12848]
### What feature or improvement do you think would benefit Files?

This is an apprearance-relevant request: It would be great if we had the option to enable alternating color rows in the "details" layout, like in the picture attached. The colours could of course be relevant or dictated by the chosen theme, etc. This would be a significant visual improvement when dealing with a lot of files in a folder, and help reduce productivity errors, for those of us who need it / choose to enable it.

Let me take this chance to say congratulations on a great product altogether, I bought it 2 minutes after testing it with the preview version.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.5.10.0

### Windows Version

10.0.22621.1848

### Comments

![Screenshot 2023-07-04 175844](https://github.com/files-community/Files/assets/138599528/465cc533-6930-4678-b9f1-2dbb899d9402)
![Screenshot 2023-07-04 175824](https://github.com/files-community/Files/assets/138599528/5ad2b60b-4411-425a-85ce-c5e0f4b143e7)

**Comment by mdtauk** [comment]
There is guidance for this with WinUI - if we do implement it, we know how it should be done.
![image](https://github.com/files-community/Files/assets/7389110/8ab94f6f-3175-46f5-a6c2-c7547364e668)

**Comment by yaira2** [comment]
Thank you for your support, we explored this a couple of months ago but found that it was very unstable but we'd be happy to add this as an option once those issues are resolved.

**Comment by Lukiluc29** [comment]
It would be nice if it were a function that can be activated and deactivated because maybe for some people like me it can be disturbing.

**Comment by mdtauk** [comment]
There is also the underline option, if it can be figured out, it could be a dropdown option between:
- None
- Banded
- Lined

**Comment by VCHLOROK** [comment]
wow thanks for the responses! I am new to github, (in fact I just subscribed to give this input) so please excuse my noobiness, but do I have to "close issue" now that I had a satisfactory response?

**Comment by yaira2** [comment]
We should leave this open so it's on the ToDo list.

**Comment by yaira2** [comment]
Thank you for your feedback, we don't have plans to support this now due to performance concerns, but we'll reevaluate if this changes in the future.
