### ISSUE TITLE
Bug: In column display mode on Files, Impossible to access network space

### ISSUE THREAD

**Issue by misfit-franck** [files-community/Files#12850]
### Description

In column display mode on Files, it's impossible to access network space: the software crashes and consumes a lot of RAM memory and CPU usage. About 27.8% CPU usage and 1,475.9 MB RAM.
However, after several attempts, the same problem occurs access to the network seems to depend on the software's moods, i.e., when it wants to.

![Screenshot 2023-07-04 180906](https://github.com/files-community/Files/assets/128629661/dc9f80b7-f1b4-4056-89a6-d6995c214f63)

### Steps To Reproduce

Open software for network requirements
Access the network area on the software sidebar.

NB: Files must be in column display mode.

### Requirements

- e.g. Fix crash that occurs when...
Fixed the problem that occurs when the user tries to access the software's network space and Files is in column display mode

### Files Version

2.5.10.0

### Windows Version

22621.1928

### Log File

[debug.log](https://github.com/files-community/Files/files/11951459/debug.log)

**Comment by Lukiluc29** [comment]
Try pinning Network to your favorites. For my part when I do this technique and I access the Network, Files does not crash.

**Comment by misfit-franck** [comment]
> Try pinning Network to your favorites. For my part when I do this technique and I access the Network, Files does not crash.

@Lukiluc29 Thank for you technique.

**Comment by Josh65-2201** [comment]
Thanks for the report and sorry for the delayed response. Does this happen only in column layout for you?

**Comment by Lukiluc29** [comment]
@Josh65-2201 Yes, this problem is present only in column mode and I have made a report to say that it occurs for "This PC", "Recycle Bin" and "Network". Donc, quand ce problème sera réglé il faudra prendre en compte ce rapport et celui que j'ai fais précedemment #12664.
