### ISSUE TITLE
Feature: Reduce unnecessary capitalizations

### ISSUE THREAD

**Issue by ImranDirkhan** [files-community/Files#12854]
### What feature or improvement do you think would benefit Files?

I become sick when I see unnecessary capitalizations, for example, the capital W in "Open With". There are many such instances; please make corrections so that it may feel natural.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.5.10.0

### Windows Version

10.0.19045.3086

**Comment by yaira2** [comment]
Thank you for your feedback, can you please compile a list of these instances?

**Comment by sineptic** [comment]
@yaira2 i can create issues in crowdin "mistake in the source string" where I see unnecessary capitalizations

**Comment by mdtauk** [comment]
Windows has guidance on dealing with capitalisation.

https://learn.microsoft.com/en-us/windows/win32/uxguide/text-ui#capitalization

**Comment by yaira2** [comment]
@sineptic it's best to compile a single list and share them in this issue.

**Comment by ImranDirkhan** [comment]
Some instances of unnecessary capitalizations are in the pictures attached
in this email. Note that these are like “Open With” in which “W” should not
be capitalized. Only the first letter of the first word should be
capitalized (except where it is proper). In the picture where hovering over
delete icon, there should be space between Del and Ctrl+D.

**Comment by Jay-o-Way** [comment]
@ImranDirkhan images are not passed through wth replies via email. Please open te issue in a browser and edit the comment to add images 🙂

**Comment by yaira2** [comment]
I fixed the issue with "Open With", if you find additional instances, feel free to post them in this issue and we'll do our best to address them.

**Comment by Jay-o-Way** [comment]
@yaira2
| key                                              | string                        |
|--------------------------------------------------|-------------------------------|
| SelectAll                                        |                               |
| InvertSelection                                  |                               |
| ClearSelection                                   |                               |
| WelcomeDialog.PrimaryButtonText                  | Grant Permission              |
| NewFolder                                        |                               |
| NewFile                                          |                               |
| FileNotFoundDialog.Title                         |                               |
| AccessDenied                                     |                               |
| AddDialog.Title                                  | Create a New Item             |
| all that start with "Property"                   |                               |
| ClearPropertiesButton.Content                    |                               |
| NavToolbarLargeIcons.ToolTipService.ToolTip      | Large icons (Ctrl+Shift+5)    |
| NavToolbarMediumIcons.ToolTipService.ToolTip     |                               |
| NavToolbarSmallIcons.ToolTipService.ToolTip      |                               |
| SidebarCloudDrives                               |                               |
| PropertyItemName                                 |                               |
| all "DriveType*"                                 |                               |
| StatusDeletionFailed                             |                               |
| ExtractArchive                                   |                               |
| DialogRestoreLibrariesTitleText                  | Restore Libraries             |
| AskCredentialDialog.Title                        | Credential Required           |
| LargeIcons                                       |                               |
| MediumIcons                                      |                               |
| SmallIcons                                       |                               |
| OngoingTasks                                     |                               |
| ExportSettings                                   |                               |
| ReducedColorMode_Color16Bit                      | 16 Bit Colours (65536)        |
| ReducedColorMode_Color8Bit                       | 8 Bit Colours (256)           |
| FolderWidgetCreateNewLibraryDialogTitleText      | Create Library                |
| FolderWidgetCreateNewLibraryInputPlaceholderText | Enter Library name            |
| SettingsOpenInLogin                              | Open Files on Windows Startup |
| SizeAllColumnsToFit                              |                               |
| DateCreatedColumn                                |                               |
| OpenFolderWithOneClickColumnsLayout              |                               |
| EditSettingsFile                                 |                               |
| ReleaseNotes                                     |                               |
| NetworkAuthenticationDialogTitle                 | Enter Network Credentials     |
| SwitchBranch                                     |                               |
| CreateNewBranch                                  |                               |
|                                                  |                               |

**Comment by yaira2** [comment]
This should be resolved in `main`.
