### ISSUE TITLE
Feature: Add support for "Proton Drive" (cloud drive)

### ISSUE THREAD

**Issue by u1b4n** [files-community/Files#12851]
### What feature or improvement do you think would benefit Files?

It's still in closed beta on windows but I got access and can provide all necessary data (and a temporary test account if necessary).
Proton Drive -> https://proton.me/drive
Information to the roadmap -> https://proton.me/blog/proton-drive-roadmap

Uses following folder:
`C:\Users\%username%\Proton Drive\<ProtonUsername>`

### Requirements

- This proposal will make the Proton Drive folder visible under "Cloud Drives".

### Files Version

2.5.11.0

### Windows Version

10.0.22621.1928

### Comments

If you want to implement it (and I would be very grateful about that:) and test it, feel free to contact me via [Discord](https://discord.com/users/95664603219482625).

**Comment by Josh65-2201** [comment]
Thanks for the feedback, I've added this to the project board.

**Comment by u1b4n** [comment]
Proton Drive is out of beta. Everyone with a proton account can use / test it... ([blog post](https://proton.me/blog/proton-drive-windows)

**Comment by yaira2** [comment]
This feature will be included in the next version of Files.
