### ISSUE TITLE
can't compile

### ISSUE THREAD

**Issue by sineptic** [files-community/Files#12860]
### Description

i can't build project because Visual Studio say that:

Error	CS0103	The name 'ViewModel' does not exist in the current context
Files.App	D:\Timur\files app\Files\src\Files.App\UserControls\PathBreadcrumb.xaml.cs	21	Active

and same errors in next lines

### Steps To Reproduce

i think add usings
or change ViewModel to other class

### Requirements

can't build project

### Files Version

latest(i use git clone ~6:00 07.05.23)

### Windows Version

10.0.19045.3086

### Log File

Error	CS0103	The name 'ViewModel' does not exist in the current context
Files.App	D:\Timur\files app\Files\src\Files.App\UserControls\PathBreadcrumb.xaml.cs	21	Active

**Comment by gave92** [comment]
IIRC when I had this error I had to update the Net Sdk version to at least 7.0.32

**Comment by sineptic** [comment]
I upgraded to the 7.0.305 .NET SDK, but nothing has changed. I have another bug, maybe they are related somehow?
Error	MSB4062	The "Microsoft.Build.AppxPackage.RemovePayloadDuplicates" task could not be loaded from the assembly C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VisualStudio\v17.0\AppxPackage\Microsoft.Build.AppxPackage.dll. Could not load file or assembly 'file:///C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VisualStudio\v17.0\AppxPackage\Microsoft.Build.AppxPackage.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.	Files.App	C:\Users\sinep\.nuget\packages\microsoft.windowsappsdk\1.3.230602002\buildTransitive\MrtCore.PriGen.targets	1443

@gave92

**Comment by gave92** [comment]
I'm attaching here my VS installation confguration (what components I have installed). You may want to try to import it using VS Installer to check if threre's anything you're missing.
[vsconfig.zip](https://github.com/files-community/Files/files/11961477/vsconfig.zip)

**Comment by sineptic** [comment]
Thank you so much, everything worked. i still have one question: where can i find the .exe? (i can see it in windows start, but i can't find the location). thanks again.

**Comment by Josh65-2201** [comment]
type Files.exe into the startmenu search then open file location.

**Comment by sineptic** [comment]
thank you
