### ISSUE TITLE
Bug: Thumbnail in details pane sometimes reloads

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12877]
### Description

For the past few days, I’ve noticed an unusual behavior in the preview pane. Let me explain. When I navigate to the “Downloads” folder, for example, and there are large files present, the file information and its icon load twice. First, when I click on the folder, and then again when the folder is fully loaded. The same occurs when I access the “Music” folder, where there are fewer or no files. However, when I access a Git folder, there is no file information displayed. On the other hand, if I open a file within a Git folder, everything is displayed correctly.

### Steps To Reproduce

1. Open Files and select a folder on the sidebar (eg. downloads)
2. Open the details pane and click a different item in the sidebar (eg. documents)
3. Observe how the downloads icon reloads for a moment before switching the icon to documents
4. This issue only occurs when switching between folders, it doesn't occur when switching from the home page.

### Requirements

Investigate the cause of the duplicate loading of file information and icons in the preview pane as well as problems where no information from Git folders is displayed.

### Files Version

Dev

### Windows Version

22H2 22621.1848

### Log File

[debug.log](https://github.com/files-community/Files/files/11970378/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report. Can you give the following information.
- Send a video recording of this issue
- What information is missing for Git Folders?

**Comment by Lukiluc29** [comment]
@Josh65-2201 Here is a screen recording of the preview pane behavior (I noticed this issue only occurs when clicking on a folder in favorites)

https://github.com/files-community/Files/assets/128183422/4c26bc96-d5a1-4893-aa62-6cd1aa0a3e05

Here is the problem with the preview pane for Git folders

![Capture d'écran 2023-07-07 161222](https://github.com/files-community/Files/assets/128183422/914abf8d-67c9-43b7-8c55-1700b703cc3c)

**Comment by Josh65-2201** [comment]
Thanks, I've added this to the project board.

**Comment by Lukiluc29** [comment]
@Josh65-2201 I think I found the problem. The "GitHelpers.cs" file is missing from the Helpers folder.

**Comment by Lukiluc29** [comment]
This problem persists in the latest update

**Comment by yaira2** [comment]
I update the description with steps to consistently repro this issue.

**Comment by Lukiluc29** [comment]
@yaira2 I just checked, but the problem persists when I'm in column view. I think I know why. When I click on the folder in the sidebar, the icon appears, and then it is loaded again once the folder is completely loaded. In contrast, in details view, the icon does not appear until the folder is completely loaded.

**Comment by yaira2** [comment]
I'll work on a fix
