### ISSUE TITLE
Offline Installer

### ISSUE THREAD

**Issue by Malephar** [files-community/Files#12871]
### What feature or improvement do you think would benefit Files?

Is there a way to use a offline installer? I want to install on my workstation and the firewall doesn't allow it.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

all realeases

### Windows Version

10

**Comment by Malephar** [comment]
The link in broken

**Comment by yaira2** [comment]
Try
`https://cdn.files.community/files/preview/Files.Package_2.5.11.0_Preview_Test/Files.Package_2.5.11.0_x64_ARM64_Preview.msixbundle`
`https://cdn.files.community/files/preview/Files.Package_2.5.11.0_Preview_Test/Dependencies/x64/Microsoft.WindowsAppRuntime.1.3.msix`
`https://cdn.files.community/files/preview/Files.Package_2.5.11.0_Preview_Test/Dependencies/x64/Microsoft.VCLibs.x64.14.00.appx`
