### ISSUE TITLE
Icons not showing up after setting them

### ISSUE THREAD

**Issue by curtiselliotharris** [files-community/Files#12876]
### Description

When I go into a folder and switch the icon to be an .ico file it doesn't change from default folder icon in Files App.

### Steps To Reproduce

on folder right click
Properties Settings
Customization
Browse

In Windows 11, latest update.

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

2.5.10.0

### Windows Version

10.0.22621.1928

### Log File

no clue.

**Comment by Josh65-2201** [comment]
Can you please upload (Do not copy and paste content) the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.
