### ISSUE TITLE
Feature: Autoplay media in Details/Preview pane

### ISSUE THREAD

**Issue by plyoung** [files-community/Files#12879]
### What feature or improvement do you think would benefit Files?

It would be nice if there was a toggle to enable auto-play of media file previews, for example audio, via the details/preview panel.

I'm a game developer and sometimes I want to quickly go through sound clips to find something to use and having to first press the play is an extra step which slows me down.

### Requirements

- Any preview with a play button should be able to auto-play
- It should be optional, perhaps a toggle in Settings, else in context menu of details/preview pane

### Files Version

2.5.10.0

### Windows Version

10.0.22621.1848

**Comment by yaira2** [comment]
Thank you for your feedback

**Comment by yaira2** [comment]
@plyoung thank you for sharing your feedback, we don't have plans to add this option to Files.
