### ISSUE TITLE
Bug: Favourites is slow to load taking 10+ seconds on first open on Files

### ISSUE THREAD

**Issue by deathrjj** [files-community/Files#12875]
### Description

When opening the application, with no other instances open, it takes a very long time for the favourites to load, useually more than 10 seconds.

![image](https://github.com/files-community/Files/assets/7521286/dba512e8-9af1-4f58-a143-a1657b81df49)
![image](https://github.com/files-community/Files/assets/7521286/7352a040-6071-4df8-adc8-9c1d2b466334)
First Image shows how it looks upon initial open and second shows how it looks after approx 15s had passed

![image](https://github.com/files-community/Files/assets/7521286/a4f917ce-4c38-46c1-9585-df835b09eed3)
This shouldn't be being caused by my PC as I have very high specs, running an i9 with 32gb of Ram

To fix this issue, maybe current favourites could be saved to some kind of cache and then updated if there were any changes when the program is opened 

### Steps To Reproduce

1. Close all instances of Files 
2. Open Files
3. Observe that the Items in 'Favourites' are not visible for a reasonable period of time

### Requirements

No other instances of Files are open

### Files Version

2.5.10.0

### Windows Version

10.0.19045.3086

### Log File

[debug.log](https://github.com/files-community/Files/files/11969787/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
@deathrjj thank you for the feedback, can you see if there are any improvements in v2.5.20?

**Comment by deathrjj** [comment]
@yaira2 Much faster now thanks!

**Comment by yaira2** [comment]
We're excited to share that startup performance will be significantly improved in the upcoming release of version 3. You can download the preview version from our website https://files.community/download.
