### ISSUE TITLE
Bug: Details Pane isn't displaying overview in the Column layout

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12878]
### Description

I previously reported an issue regarding the display of file details not appearing properly when switching from preview mode to details mode. I was informed that this problem would be resolved, but unfortunately, it is still persisting. Specifically, when I switch from preview mode to details mode, no details are displayed. I have to navigate to another folder and return to view the details.

### Steps To Reproduce

https://github.com/files-community/Files/assets/128183422/3543b2b2-5063-4c36-8b94-12993b91ed2b
1. Open Files
2. Open the preview pane
4. Set the preview pane on preview
5. Go to a file or folder
6. Go to a other file or folder
7. Switch preview pane to details

### Requirements

Identify the cause of the file details not being displayed correctly during the switch from preview mode to details mode.

### Files Version

Dev

### Windows Version

22H2 22621.1848

### Log File

[debug.log](https://github.com/files-community/Files/files/11970446/debug.log)

**Comment by yaira2** [comment]
Thank you for the report, I tried multiple times to reproduce this but wasn't able to but with the screen recording, I can see you're using column layout. Can you update the steps to reproduce this?

**Comment by Lukiluc29** [comment]
@yaira2 It's done. I updated the steps to reproduce. I am waiting for this problem to be fixed because this problem has been present since the new preview pane modeling and it is a bit disturbing for me.

**Comment by Lukiluc29** [comment]
And also, I tried with all other layout and it's the same so this problem is not specific to column layout.

**Comment by yaira2** [comment]
@Lukiluc29 I'm able to repro this issue in Columns but it's not present in the other layouts. However, if after reproducing it in Columns you switch to another layout, the issue will be present until you change the selected item.

**Comment by Lukiluc29** [comment]
@yaira2 I manage to reproduce this problem even in details mode as you can see below. This bug happens when I navigate in folders/files.
<img width="768" alt="Capture d'écran 2023-07-12 082409" src="https://github.com/files-community/Files/assets/128183422/d76d80a4-d832-49b7-9355-7ad94fe620b5">

**Comment by Lukiluc29** [comment]
@yaira2 I just tried the fix in developer mode but this error still persists

**Comment by Lukiluc29** [comment]
But this problem only occurs on files because when you go from "Preview" to "Details on a folder this problem does not occur.
