### ISSUE TITLE
Feature: Add support for Owncloud

### ISSUE THREAD

**Issue by EnteQuackQuack** [files-community/Files#12873]
### What feature or improvement do you think would benefit Files?

It would be great if there was an option to add custom 3rd-party cloud storage services. 

I use [Owncloud](https://owncloud.com/) which comes with a desktop program and is detected by windows explorer as a cloud.

While it works as a workaround to link the main storage directory to a windows folder and pin the folder as favorite, it would be better to have the cloud in the cloud storage-section.

Owncloud also adds a range of right click actions which get displayed in the windows explorer, adding these would be great too.

### Requirements

- added section in the settings to add network drives
- support for additional program-specific right click actions

### Files Version

2.5.10.0

### Windows Version

10.0.22621.1848

### Comments

https://owncloud.com/news/desktop-client-2-6-release-native-virtual-file-system-on-windows-10/
They explained here more in detail how their windows explorer integration works, maybe it helps

**Comment by yaira2** [comment]
@EnteQuackQuack this feature will be available in the upcoming v2.5.20 release.
