### ISSUE TITLE
Bug: Hanging of File Software 

### ISSUE THREAD

**Issue by uttambasar** [files-community/Files#12870]
### Description

Hi, 
I have purchase Files App from Microsoft store. While using this app i have repeatedly the app hangs and restart again. The File app working very slow also. Hangs even on multiple tabs open.  

### Steps To Reproduce

Not understand this behavior 

### Requirements

- e.g. Fix crash that occurs when...
Close the issue of hanging. 

### Files Version

2.5.10.0

### Windows Version

Windows 11 Pro, 22H2

### Log File

[debug.log](https://github.com/files-community/Files/files/11967705/debug.log)

**Comment by uttambasar** [comment]
It is feel irritate to use on rush hour of office time. Hence resolve this issue immediately.

**Comment by yaira2** [comment]
@uttambasar at what point does it start hanging, is there a particular action or setup where you can always reproduce this issue?

**Comment by Josh65-2201** [comment]
@uttambasar Can you see if this is an issue in 2.5.21.0, If so can you answer the above question

**Comment by uttambasar** [comment]
Hello..

Issue arise when uses multiple tabs in single file. It suddenly stopped
working and start again over.

Also whenever back the tab page it takes 2 seconds not immediately and
refresh the tab again then came all the way.

Hang issue is getting repeatedly and make feel annoying to use.


Regards,
Uttam Basar
#18, Vivekananda Path
Udaypur Birubari, Nr. Kalimandir
Guwahati-781016, Assam
Mob: +91-98641 72078
www.electroassam.com

**Comment by yaira2** [comment]
@uttambasar did you have a chance to check if this is still an issue in the preview version of Files? https://files.community/download

**Comment by uttambasar** [comment]
Dear Sir, The issue is not resolve till date. I am still facing the restart of File while using it in multiple or single tab.  Regards,  Uttam Basar  Sent from Mail for Windows From: YairSent: 13 September 2023 02:38To: files-community/FilesCc: uttambasar; MentionSubject: Re: [files-community/Files] Hanging of File Software (Issue ***@***.*** did you have a chance to check if this is still an issue in the preview version of Files? https://files.community/download—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by yaira2** [comment]
@uttambasar can you upload an updated log file from the latest preview build?

**Comment by uttambasar** [comment]
Hello.! I don’t have any log file. Can’t understand how to get it. But the problem is still there. Hanging problem is now getting worst and annoying. I will soon stop working with “FILE” tab and will mark as worst App.  Regards,  Uttam Basar  Sent from Mail for Windows From: YairSent: 25 October 2023 22:46To: files-community/FilesCc: uttambasar; MentionSubject: Re: [files-community/Files] Bug: Hanging of File Software (Issue ***@***.*** can you upload an updated log file from the latest preview build?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by Josh65-2201** [comment]
(Do not copy and paste content) the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.

**Comment by uttambasar** [comment]
Attached files of log folder as required.   Sent from Mail for Windows From: Josh65-2201Sent: 26 October 2023 11:06To: files-community/FilesCc: uttambasar; MentionSubject: Re: [files-community/Files] Bug: Hanging of File Software (Issue #12870) (Do not copy and paste content) the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by uttambasar** [comment]
Attached files of log folder Sent from Mail for Windows From: Josh65-2201Sent: 26 October 2023 11:06To: files-community/FilesCc: uttambasar; MentionSubject: Re: [files-community/Files] Bug: Hanging of File Software (Issue #12870) (Do not copy and paste content) the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by Josh65-2201** [comment]
Email attachments don't work. Please open the GitHub site and drag the file to the comment box wait a few seconds and then click comment.

**Comment by uttambasar** [comment]
[debug.log](https://github.com/files-community/Files/files/13197830/debug.log)

**Comment by yaira2** [comment]
@uttambasar that log file seems to be from the stable version, can you send the one from the preview version? https://files.community/download

**Comment by yaira2** [comment]
@uttambasar
