### ISSUE TITLE
Code Quality: Update DependencyProperty generator to have the property declaration

### ISSUE THREAD

**Issue by 0x5bfa** [files-community/Files#12889]
### Description

We have a problem about SourceGenerator - that is we cannot reference to the generated property in advance. Whenever I hover on the property, Visual Studio tells me there's a error that there's no such a property in the project because the proeprty is not declared explicitly although they will be disappeared in building.

![image](https://github.com/files-community/Files/assets/62196528/2284ded2-563e-4a43-85d3-04ba7e85b1b3)

Current:

```cs
namespace Files.App.UserControls
{
	[DependencyProperty<ToolbarViewModel>("ViewModel")]
	public sealed partial class PathBreadcrumb : UserControl
	{
		private void PathItemSeparator_DataContextChanged(FrameworkElement sender, DataContextChangedEventArgs args)
			=> ViewModel.PathItemSeparator_DataContextChanged(sender, args);
	}
}
```

Proposal:

```cs
namespace Files.App.UserControls
{
	public sealed partial class PathBreadcrumb : UserControl
	{
		[DependencyProperty]
		pubilc ToolbarViewModel ViewModel { get; set; }

		private void PathItemSeparator_DataContextChanged(FrameworkElement sender, DataContextChangedEventArgs args)
			=> ViewModel.PathItemSeparator_DataContextChanged(sender, args);
	}
}
```

### Concerned code

- Files.Core.SourceGenerator

### Gains

- A better readability.
- A better maintainability.

### Requirements

- Update source generation way

**Comment by Poker-sang** [comment]
Hmmm, I just thought about it. Maybe we have to write more code in property, unless we can use partial keyword in property:
```cs
namespace Files.App.UserControls
{
	public sealed partial class PathBreadcrumb : UserControl
	{
		[DependencyProperty]
		pubilc ToolbarViewModel ViewModel { get => (ToolbarViewModel)GetValue(ViewModelProperty); set => SetValue(ViewModelProperty, value); }

		private void PathItemSeparator_DataContextChanged(FrameworkElement sender, DataContextChangedEventArgs args)
			=> ViewModel.PathItemSeparator_DataContextChanged(sender, args);
	}
}
```
I'm sorry I didn't think much about what I said earlier.

**Comment by michael-hawker** [comment]
@Poker-sang FYI we have a Toolkit Labs proposal together for this once partial properties come to .NET: https://github.com/CommunityToolkit/Labs-Windows/discussions/449

**Comment by 0x5bfa** [comment]
Seems that it will take much time to be implemented...

**Comment by 0x5bfa** [comment]
> Hmmm, I just thought about it. Maybe we have to write more code in property, unless we can use partial keyword in property:
> 
> ```cs
> namespace Files.App.UserControls
> {
> 	public sealed partial class PathBreadcrumb : UserControl
> 	{
> 		[DependencyProperty]
> 		pubilc ToolbarViewModel ViewModel { get => (ToolbarViewModel)GetValue(ViewModelProperty); set => SetValue(ViewModelProperty, value); }
> 
> 		private void PathItemSeparator_DataContextChanged(FrameworkElement sender, DataContextChangedEventArgs args)
> 			=> ViewModel.PathItemSeparator_DataContextChanged(sender, args);
> 	}
> }
> ```
> 
> I'm sorry I didn't think much about what I said earlier. Maybe it will be available in .NET8? [partial properties](https://github.com/dotnet/csharplang/issues/6420#issue-1356379075)

It can be fine because no one use ViewModelProerty. The point is that we should be able to find references of that property in VS.

**Comment by Poker-sang** [comment]
Yes. I'm afraid so.

**Comment by 0x5bfa** [comment]
Are we able to implement in that way?

**Comment by Poker-sang** [comment]
> Are we able to implement in that way?

It is possible. But this approach is more cumbersome and it still reports errors. This is because the property references the generated and non-existent field.

BTW I would like to ask, are you using vs2022? incremental generators do mot work well for vs2019 and earlier.

**Comment by 0x5bfa** [comment]
Yes, I'm using VS2022. How come? It should depend on .NET SDK and should not depend on VS version, I suppose.

**Comment by Poker-sang** [comment]
> Yes, I'm using VS2022. THat's wierd. It should depend on .NET SDK not VS version, I suppose.


The ability to generate projects depends on the .NET SDK, but the static analysis of the code (syntax highlighting) depends on the version of vs. The latest version of vs2022 (i.e. vs17.6) corresponds to roslyn version 4.6. vs2019(vs16.x) can only use the api of roslyn 3.x, while the incremental generator is a new feature of Roslyn 4.3.0 (corresponding to vs17.3). So earlier versions of vs won't work.

**Comment by 0x5bfa** [comment]
@yaira2 I think that way *1 is the fair solution because we can easily update when partial property is implemented.

*1
```cs
namespace Files.App.UserControls
{
	public sealed partial class PathBreadcrumb : UserControl
	{
		[DependencyProperty]
		pubilc ToolbarViewModel ViewModel { get => (ToolbarViewModel)GetValue(ViewModelProperty); set => SetValue(ViewModelProperty, value); }

		private void PathItemSeparator_DataContextChanged(FrameworkElement sender, DataContextChangedEventArgs args)
			=> ViewModel.PathItemSeparator_DataContextChanged(sender, args);
	}
}
```

**Comment by 0x5bfa** [comment]
It have taken too much time so far. Unless they plan and implement we cannot even use, and so I close this as not planned right now.
