### ISSUE TITLE
incorrect translation(i can't see it in Crowdin)

### ISSUE THREAD

**Issue by sineptic** [files-community/Files#12884]
### Description

in English version all is OK, but in Russian we have problem and i don't understand how i can fix it(in Crowdin translation all is OK i think)
![Screenshot 2023-07-07 115616](https://github.com/files-community/Files/assets/98404983/7d0be913-cb11-440a-81b7-869887a62b29)
![Screenshot 2023-07-07 115845](https://github.com/files-community/Files/assets/98404983/898654b5-35a2-4df1-ba62-2cefcf6ffd88)

### Steps To Reproduce

- [ ] understand if this can be solved on Crowdin translation
- if not:
    -  [ ] find bug in code
    -  [ ] fix it
- else:
    - [ ] fix it in Crowdin

### Requirements

always when i focus on "Back", "Forward" or "Up" in left top corner

### Files Version

latest Dev(i use git pull ~11:00 07.07.23)

### Windows Version

10.0.19045.3086

### Log File

no matter(i don't do anything to get bug)

**Comment by Josh65-2201** [comment]
Thanks for the report, Latest changes from crowding haven't been merge yet so it might be fixed on next release.

**Comment by sineptic** [comment]
thx
