### ISSUE TITLE
Bug: Crash when clicking on Documents

### ISSUE THREAD

**Issue by prgsmall** [files-community/Files#12888]
### Description

Under favorites, I clicked on one  of my favorites, which opened in column view.
Then I clicked on Documents, which as not in column view.
Application crashed.

### Steps To Reproduce

I'm not able to reproduce this issue.

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

2.5.10.0

### Windows Version

10.0.19044

### Log File

[debug.log](https://github.com/files-community/Files/files/11982515/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
@prgsmall I think this is fixed in the upcoming v2.5.20 release, please let us know if it happens again and we'll look for another fix.

**Comment by prgsmall** [comment]
Thank you...
