### ISSUE TITLE
Option to toggle between Performance/Visual Effects

### ISSUE THREAD

**Issue by ruykava** [files-community/Files#12882]
### What feature or improvement do you think would benefit Files?

It would be great if there were an option to turn off visual effects so that older computers can run Files with faster performance. 

### Requirements

- Toggle switch to turn off all visual effects

### Files Version

2.5.10.0

### Windows Version

10.0.19045.3155

**Comment by yaira2** [comment]
Thank you for your feedback, Windows has built-in settings to disable visual effects. Please let me know if this makes a noticeable difference in performance.
![image](https://github.com/files-community/Files/assets/39923744/6a9c833c-b24e-4b73-93d4-d7d93595ec15)
