### ISSUE TITLE
error on changing icon

### ISSUE THREAD

**Issue by curtiselliotharris** [files-community/Files#12880]
### Description

described earlier

### Steps To Reproduce

won't replace folder ico with new ico

### Requirements

- e.g. Fix crash that occurs when...
nothing happens

### Files Version

2.5.10.0

### Windows Version

10.0.22621.1928

### Log File

[debug.log](https://github.com/files-community/Files/files/11971930/debug.log)

**Comment by Josh65-2201** [comment]
Is this the same issue as #12876
