### ISSUE TITLE
Request to Improve Icon Resolution in Files Application

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12891]
### Description

I noticed that recently you made changes to the icon resolution in the Favorites bar. However, I wanted to inquire if it would be possible to enhance the resolution of all the icons within the Files application. For instance, some icons appear blurry, such as the folder icon in the Favorites, which is of better quality compared to other folder icons. Similarly, the PDF icon is also blurry and many other. So, I would like all icons in Files to have the same resolution as those in File Explorer.

### Steps To Reproduce

1. Navigate in Files

### Requirements

Improve resolution of all icons in Files like those in favorites.

### Files Version

Dev

### Windows Version

22H2 22621.1848

### Log File

No need.

**Comment by Lukiluc29** [comment]
@yaira2 Do you think this icon and thumbnail issue will be fixed soon ?

**Comment by yaira2** [comment]
We try to avoid giving timelines but what I can say is that #12071 will keep the icons consistent throughout the app, and will make it easier for us to implement new layouts.

**Comment by Lukiluc29** [comment]
OK, I understand. I'm eager to !
