### ISSUE TITLE
Feature: Update layout button icon as layout changes

### ISSUE THREAD

**Issue by mdtauk** [files-community/Files#12894]
### What feature or improvement do you think would benefit Files?

At the moment, the layout button's icon does not match the current chosen layout from the flyout.

![image](https://github.com/files-community/Files/assets/7389110/514b2541-2d19-4d3c-b6ae-c5885fb8483b)

### Requirements

- This proposal will allow the user to see what the current layout is being used, and provides a better hint at what this button does, which is unlabelled in the UI

### Files Version

2.5.13 Preview

### Windows Version

22621.1928

**Comment by yaira2** [comment]
Thank you for your feedback.

**Comment by ferrariofilippo** [comment]
When using adaptive layout should we use a specific icon or the one corresponding to the current layout (details or grid)?

**Comment by Josh65-2201** [comment]
Adaptive mode was turned into a toggle from based on the  `Work in progress` discord post
