### ISSUE TITLE
mr peter prewett

### ISSUE THREAD

**Issue by peterprewett** [files-community/Files#12899]
### What feature or improvement do you think would benefit Files?

It takes nearly 5 minutes to get a email code in Australia

### Requirements

speed up access to github

### Files Version

22621.1928

### Windows Version

11

### Comments

If not sorted will no longer use this service cannot wait 5 minutes to access

**Comment by Josh65-2201** [comment]
Files doesn't send any email code. If your trying to login to GitHub to authorizes it is an issue with GitHub.
