### ISSUE TITLE
Feature: Increase maximum read volume length to 128 characters (64 characters Unicode) for UDF File Systems

### ISSUE THREAD

**Issue by ObiW4nKenobi** [files-community/Files#12901]
### What feature or improvement do you think would benefit Files?

The use case for this request is to see a more complete description of mostly optical media volume labels. Most optical media these days uses Blu-Ray disc to distribute 4K movies. Some movies have titles that exceed 32 bytes of data. Especially movies of a series. Take for instance, The Lord of the Rings movies.
"The Lord of the Rings - The Fellowship of the Ring" (50 characters)
"The Lord of the Rings - The Two Towers" (38 characters)
"The Lord of the Rings - Return of the King" (42 characters)
These titles are all truncated and look unprofessional in such display cases.

### Requirements

- This proposal will properly show volume labels that require more than 32 characters to fully and more accurately display a volumes label according to the contents stored therein.

### Files Version

2.5.10.0

### Windows Version

10.0.19045.3155

**Comment by Josh65-2201** [comment]
Thanks for the feedback, I've added this to the project board.

**Comment by yaira2** [comment]
@ObiW4nKenobi thank you for your feedback, this feature will be included in the upcoming v2.5.20 release.
