### ISSUE TITLE
Keeps crashing

### ISSUE THREAD

**Issue by kingfagoat** [files-community/Files#12908]
### Description

Well files has been crashing for me for a few months. I switched to other alternatives but found I prefered files even with the unstability. that being said its pretty bad from that perspective. it crashes several time a day on average, whenever I ask it to do anything slightly taxing. If I open in administrator mode then it is all but guaranteed to crash. Also takes up about 400 mb of ram for no reason that I can understand and so I have to kill it sometimes

### Steps To Reproduce

Ask it to do something taxing
Especially in administrator mode

or

Leave it running and kill it when your computer starts to lag cause its taking up half a gig of ram 

### Requirements

- e.g. Fix crash that occurs when...
Just when moving files or compressing, just when interacting when files

### Files Version

2.5.13.0

### Windows Version

10.0.19045.3086

### Log File

[debug.log](https://github.com/files-community/Files/files/11996639/debug.log)
I just reinstalled it to see if that would help and I think I deleted the previous log as a result but as I said its been happening a while

**Comment by yaira2** [comment]
> Especially in administrator mode

Are you by any chance using drag & drop?

**Comment by kingfagoat** [comment]
I think I must be now you mention it. Hadn't thought of that

**Comment by yaira2** [comment]
@kingfagoat this seems to be the same as #12390. Unfortunately there isn't much we can do because it's a system llimitation but we can at least disable it to prevent the crash.

**Comment by yaira2** [comment]
@kingfagoat this seems to be the same as #12390.  Unfortunately there isn't much we can do because it's a system limitation but we can at least disable it to prevent the crash.
