### ISSUE TITLE
Full context menu feature request

### ISSUE THREAD

**Issue by penzboti** [files-community/Files#12914]
### What feature or improvement do you think would benefit Files?

Some people use extra features, and don't want to click on "more options" every time.

### Requirements

- This proposal will make the app more customizable
- This proposal will make the app more accessible
- This proposal will make the app more convenient

### Files Version

2.5.10.0

### Windows Version

10.0.22621.1928

### Comments

I also changed this in the file explorer in windows 11 with external programs, but I can't do that here.
![image](https://github.com/files-community/Files/assets/50163206/66d2784f-6e61-42a2-8e6b-64341e83b50d)

**Comment by Josh65-2201** [comment]
Thanks for the feedback. You can turn off the more options sub menu Files settings > General > Move shell extensions into a sub menu
