### ISSUE TITLE
Visualizacion previa de documento word

### ISSUE THREAD

**Issue by Destajador3000** [files-community/Files#12911]
### Description

No me funciona la visualización previa de documento word. Otros tipos de archivo se vi lo hace pero los de extensión de word no lo hace

### Steps To Reproduce

Visualizacion previa de documento word

### Requirements

Visualización previa de documentos word

### Files Version

2.5.10.0

### Windows Version

10.0.19045.3086

### Log File

No me funciona la visualización previa de documento word. Otros tipos de archivo se vi lo hace pero los de extensión de word no lo hace

**Comment by yaira2** [comment]
@Destajador3000 thank you for your feedback, previews for Office files aren't available yet but you can take advantage of our integrations with QuickLook and SeerPro for previewing this file types.
