### ISSUE TITLE
Tab Pinning

### ISSUE THREAD

**Issue by centsi** [files-community/Files#12918]
### What feature or improvement do you think would benefit Files?

I would appreciate being able to pin tabs, so that they always open with Files and the tabs are smaller in size.

This would be helpful when a folder is used very often, for example I download a lot of files and it would be nice for the downloads folder to always be ready for me.

It could also be useful when doing a long task involving a specific folder where the PC might be restarted before the project has finished, so pinning a tab could be used as a placeholder and reminder.

### Requirements

- It would be necessary to add a new right click option to pin / unpin the tab.
- A list of pinned tabs would also be required somewhere in settings.
- It might also be useful to have command line switches to open multiple folders, or a file type which could be used to open multiple folders.

### Files Version

2.5.10.0

### Windows Version

10.0.22621.1848

**Comment by yaira2** [comment]
@centsi thank you for your feedback, we don't have plans to support pinning tabs but we're planning to add an option to set aside sessions to quickly resume them #11900.

**Comment by yaira2** [comment]
> It might also be useful to have command line switches to open multiple folders, or a file type which could be used to open multiple folders.

@Josh65-2201 is this already supported?
