### ISSUE TITLE
Bug: Google Drive offline access option missing in context menu

### ISSUE THREAD

**Issue by penzboti** [files-community/Files#12912]
### Description

In the file explorer on the drive folder there is a context menu option to download the folder offline, or make it only avaliable online.
![image](https://github.com/files-community/Files/assets/50163206/a817b0f2-c648-4806-b6df-55f2beec10c4)
This is missing in the files app.
![image](https://github.com/files-community/Files/assets/50163206/17901212-fba9-4e44-913a-7f39a4bb66c2)

### Steps To Reproduce

1. Open Drives -> Google Drives
2. Right click a folder or file
3. Open more options

### Requirements

1. Download and login into Google Drive.
2. Have a folder or file inside the drive

### Files Version

2.5.10.0

### Windows Version

10.0.22621.1928

### Log File

[debug.log](https://github.com/files-community/Files/files/11998959/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Merging with #3834. You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
This issue will be resolved in the upcoming v2.5.20 release.
