### ISSUE TITLE
Bug: Display Issue with Git Folder Search in Detail View

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12927]
### Description

I have noticed an issue when performing a search within a Git folder in detail view. The Git columns remain visible, and the search columns are added after the Git columns instead of having only the search columns. I'm not sure if this is intentional, but I find it a bit inconvenient. I believe this might not be intentional because the file information is aligned as if it's not a search within a Git folder.

### Steps To Reproduce

1. Open a Git Folder
2. Launch a search

### Requirements

Identify the cause of the issue and determine if it is a bug or an intentional design choice.

### Files Version

2.5.14.0

### Windows Version

22H2 22621.1848

### Log File

![Capture d'écran 2023-07-10 163405](https://github.com/files-community/Files/assets/128183422/402b82d0-0551-4bb9-bc48-efe91f0a9c57)

**Comment by yaira2** [comment]
Thank you for reporting this issue.

**Comment by yaira2** [comment]
This issue is fixed in the dev branch and will be included in the next release.
