### ISSUE TITLE
Error on downloading PDF in Sidekick browser

### ISSUE THREAD

**Issue by dlorde** [files-community/Files#12924]
### Description

I downloaded a small PDF file (a utility bill) from Sidekick web browser while Files was running in the background showing the downloads directory. When the download had finished, Files popped up a generic error message ('Something went wrong'). There don't seem to be any problems with Files - it shows the newly downloaded file.

I tried another browser download with Files in the background showing a different directory and got no error message.

When I downloaded another PDF with Files showing the downloads directory again, there was no error message, so I was unable to replicate the error. 

Nothing shows in the Status Centre. The log file shows "The system cannot find the drive specified."

### Steps To Reproduce

1. Files running showing 'downloads' folder
2. Download a small PDF from browser to 'downloads' folder.
3. Files generic error appears.

Note: I could not replicate this.

### Requirements

Fix the error message that occurs when small PDF is downloaded as described above.

### Files Version

2.5.10.0

### Windows Version

10.0.22621.1848

### Log File

[debug.log](https://github.com/files-community/Files/files/12012894/debug.log)

**Comment by gave92** [comment]
Thanks for the report. The relevant error is:
> 2023-07-11 09:54:46.1235|Error|System.ArgumentOutOfRangeException: This collection cannot work with indices larger than Int32.MaxValue - 1 (0x7FFFFFFF - 1). (Parameter 'index')
   at ABI.System.Collections.IList.ToAbiHelper.EnsureIndexInt32(UInt32 index, Int32 listCapacity)
   at ABI.System.Collections.IList.ToAbiHelper.GetAt(UInt32 index)
   at ABI.System.Collections.IList.Vftbl.Do_Abi_GetAt_0(IntPtr thisPtr, UInt32 index, IntPtr* result)

Unfortunately we had this for a veery long time and never quite manged to fix it.

**Comment by yaira2** [comment]
@dlorde thank you for reporting this issue, we believe it's fixed in the dev branch and will be included in the next release.
