### ISSUE TITLE
Bug: Issue with Path Column Name in Files - Unwanted Ellipsis

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12929]
### Description

Since the addition of the Path column, there has been a minor issue in Files where the column name contains ellipsis, which should not be the case. I am using Files in the French language, so I'm unsure if this issue is specific to that language.
Ps: in Crowdin no translation contains an ellipsis

### Steps To Reproduce

1. Open a folder
2. Launch a search

### Requirements

Investigate the cause of the ellipsis appearing in the column name and determine if it is language-specific.

### Files Version

2.5.14.0

### Windows Version

22H2 22621.1848

### Log File

![Capture d'écran 2023-07-11 193540](https://github.com/files-community/Files/assets/128183422/31964f73-4792-42f8-81f7-dde2bb2f720a)

**Comment by mdtauk** [comment]
Just as a note, that is a Colon, not an Ellipsis.

# :
colon

# …
ellipsis

**Comment by Lukiluc29** [comment]
Sorry, I was on 2.5.13 so there was no Crowdin update yet.
