### ISSUE TITLE
Inconsistent file copy percentage

### ISSUE THREAD

**Issue by halphas91** [files-community/Files#12928]
### Description

Hello,

I've noticed that the percentage of progress for a file copy (from one disk to another, for example) is wrong: instead of 15%, for example, it says 15000% or more. 

This seems inconsistent.

Thanks for your help.

### Steps To Reproduce

1 - I copy and paste a file from one disk to another
2 - I click on the icon to see the progress of the operation
3 - the percentage is inconsistent.

### Requirements

Correct the problem to obtain the correct percentage.

### Files Version

2.5.10.0

### Windows Version

10.0.22621.1928

### Log File

[debug.log](https://github.com/files-community/Files/files/12017510/debug.log)

**Comment by gave92** [comment]
Thanks for the report. I can't seem to reproduce this. Could you share a screen recording of this?

**Comment by halphas91** [comment]
Hi,

Sorry for the delay.
Here is a copy of the percentage when I copy 3 files from one hard disk to another.



![image_105](https://github.com/files-community/Files/assets/47086153/a1121f67-bb5a-4347-b4b3-c2bef1bd8f82)

As you can see, 42200% si shown !!!

**Comment by Josh65-2201** [comment]
Can you see if this is only an issue in the French language.

**Comment by halphas91** [comment]
It's the same problem in english.

**Comment by robmulally** [comment]
> Hi,
> 
> Sorry for the delay. Here is a copy of the percentage when I copy 3 files from one hard disk to another.
> 
> ![image_105](https://user-images.githubusercontent.com/47086153/257789750-a1121f67-bb5a-4347-b4b3-c2bef1bd8f82.png)
> 
> As you can see, 42200% si shown !!!

How do you see this copy status? i've been using Files on Two PC's and I can't see files copying I just have to watch task manager untill the Disk activity Stops, I don't see any icons at the top i see described in other threads.

**Comment by halphas91** [comment]
First, when you copy something (image 1)
Then you can see the progression in % (image 2)
![1](https://github.com/files-community/Files/assets/47086153/b035a161-517f-4dd3-8bed-c0aaab5e9b05)
![2](https://github.com/files-community/Files/assets/47086153/506cc9e0-92ef-43ff-b5ef-40eb4af2a352)

**Comment by robmulally** [comment]
How do I get that to shoot show up? I couldn't find in settings.

Or manual. I'm going crazy. For now I have to use file explorer.

Its good it keeps copying if files closes but not being able to see it
copying means I run the risk of files corruption.

I installed via windows app store.

Rob

**Comment by robmulally** [comment]
> The status center is the icon next to setting ![image](https://user-images.githubusercontent.com/26977075/258153110-278d0bbc-1d32-4c97-b47c-98abd532173c.png)

I don't see that at all the gap you described is not wide enough for an icon to fit between.

**Comment by yaira2** [comment]
This appears to be resolved in our development branch.
