### ISSUE TITLE
Libraries don't show up

### ISSUE THREAD

**Issue by Pietro228** [files-community/Files#12925]
### Description

Hi,

I restarted files because it was in a crash loop and then my libraries don't show up.
![obrazek](https://github.com/files-community/Files/assets/53868994/de68fe2c-dea7-4050-83be-85aa53777944)

### Steps To Reproduce

1. Restart Files
2. Open Files
3. No libraries show up

### Requirements

- Fix ibraries not showing up.

### Files Version

2.5.10.0

### Windows Version

10.0.22631.1972

### Log File

[debug.log](https://github.com/files-community/Files/files/12012941/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report.
- Do you have library section enabled?

**Comment by Pietro228** [comment]
Oh thanks, it was not enabled.

Anyway this is a bad UX. I was searching for it in settings and tried to right click on the side bar "Home", "Drives" items as well, but I didn't know that I have to click blank space which is so small. It would be great to see it in settings.

**Comment by Josh65-2201** [comment]
I believe they were in older versions, you can open a feature request for showing sidebar items options in the general tab of settings menu.
