### ISSUE TITLE
Bug: Tabs, address bar, and folder content get out of sync when adding multiple tabs at once

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12939]
### Description

I would like to address an issue regarding the display of tab logos and names when transitioning from a pinned disk or folder where the tab logo hasn't finished loading to the home page. Currently, when on the home page, the tab logo and name from the previous disk or folder remain displayed, whereas the tab name should show the home logo and name.

### Steps To Reproduce

Go from a pinned folder whose tab logo hasn't finished loading to home.

### Requirements

Identify the cause of the tab logo and name persistence issue during navigation.

### Files Version

Version 2.5.14.0

### Windows Version

22H2 22621.1848

### Log File

[debug.log](https://github.com/files-community/Files/files/12031054/debug.log)

<img width="961" alt="Capture d'écran 2023-07-12 201828" src="https://github.com/files-community/Files/assets/128183422/8cbbb3b0-db4b-4f26-bc55-4a2f852efd3f">

**Comment by Jyoticharan** [comment]
please assign me to fix it
