### ISSUE TITLE
Force close when opening Recycle bin in 2nd pane

### ISSUE THREAD

**Issue by be4con** [files-community/Files#12936]
### Description

I opened download folder in 1st pane and tried to open the Recycle Bin in the right hand 2nd pane and when I did Files crashed and restarted.

### Steps To Reproduce

Haven't been able to reproduce but this is exactly what I did:
1) Already 5 tabs opened with a combination of networked, cloud and local folders open. All views have a 2nd pane
2) Navigated to Download folder in left-hand pane of existing tab
3) Clicked right-hand pane to focus, then clicked Recycle Bin in left-hand navigation menu.
4) Right pane cleared and went blank
5) After about 3s Files crashed without the Recycle Bin opening.
6) On automatic restart Recycle Bin had loaded successfully in the right-hand pane. 

### Requirements

- e.g. Fix crash that occurs when...
- loading a large folder in right-hand pane of 2 pane window

### Files Version

2.5.10.0

### Windows Version

10.0.22621.1992

### Log File

[debug.log](https://github.com/files-community/Files/files/12027695/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by be4con** [comment]
Hi Josh

 

It didn’t happen in the preview version but, as I said in the report, I couldn’t reproduce it. It was a one-time issue.

 

Cheers

Dave

**Comment by yaira2** [comment]
@be4con thank you for the report, it's likely this was resolved but please let us know if it happens again.
