### ISSUE TITLE
Bug: Pasting folder in Column View automatically selected and opens the folder

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12938]
### Description

I have encountered an issue where Files navigates into the folders and files being pasted when I paste a folder that contains subfolders/files. This behavior disrupts the intended workflow and can cause confusion.

### Steps To Reproduce

1. Set column layout
2. Copy a folder with multiple files and folders
3. Paste

### Requirements

Identify the cause of the automatic navigation when pasting folders and files.

### Files Version

Version 2.5.14.0

### Windows Version

22H2 22621.1848

**Comment by yaira2** [comment]
File Explorer?

**Comment by Lukiluc29** [comment]
> Explorateur de fichiers?

Sorry I wanted to put Files

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
@Lukiluc29 the correct behavior when pasting an item is for it to be selected. Is there a desire to be inconsistent with the other layouts?
