### ISSUE TITLE
Bug: Details tab info fails to load

### ISSUE THREAD

**Issue by verdaderoken** [files-community/Files#12932]
### Description

The details info below the filename is not loading when you initially set the Preview pane to **Preview** tab.

![image](https://github.com/files-community/Files/assets/88200096/6c394144-b139-42d0-9dc8-5887d76234e4)

### Steps To Reproduce

1. Initially set to **Preview** tab
2. Select an item
3. Now, select the Details tab.
4. The other info is not showing.
5. If you keep switching back & forth, it will still not load.

It only loads when you initially set it to **Details** tab

### Requirements

Details info should be shown.

### Files Version

2.5.14.0

### Windows Version

10.0.23493.1000

### Log File

Irrelevant

**Comment by yaira2** [comment]
Thank you for your feedback, we're tracking this issue in #12878.
