### ISSUE TITLE
Feature: Display sidebar options when right clicking headers

### ISSUE THREAD

**Issue by Pietro228** [files-community/Files#12930]
### What feature or improvement do you think would benefit Files?

Hi,

I was recently struggling to show the libraries section on the sidebar. I tried to show options by clicking the parent menu items like "Drive", "Home" to get the options menu, because I couldn't find it anywhere in the settings. Then I was told that I need to right click on a small blank space to change the menu items options. I think that's a bad UX and many people wouldn't find this on their own.

I clicked where the red dot is:
![obrazek](https://github.com/files-community/Files/assets/53868994/c4afc640-7ecc-45e1-862e-9753e77e4f2b)

### Requirements

- Move the menu items options context menu to the settings.

### Files Version

2.5.10.0

### Windows Version

10.0.22631.1972

**Comment by Josh65-2201** [comment]
Thanks for the feedback, I've added this to the project board.
