### ISSUE TITLE
Functional support

### ISSUE THREAD

**Issue by Grayfoam** [files-community/Files#12940]
### What feature or improvement do you think would benefit Files?

Can support all the features of Listary, especially the folder location function, can save a lot of time, improve efficiency.

### Files Version

2.5.10.0

### Windows Version

10.0.19045.3086

**Comment by Josh65-2201** [comment]
Thanks for the feedback. I assume you mean library when saying `listary`. They are fully supported, If something isn't working please make a bug report with your exact issue.

**Comment by yaira2** [comment]
@Josh65-2201 Listary is a third party app for searching the file system. We don't have plans to support Listary directly, but we plan to improve search and to incorporate a number of the features into Files.

**Comment by yaira2** [comment]
Support for Listary is actively being worked on in #15069.
