### ISSUE TITLE
Bug: Issue with Context Menu in Preview Pane When Right-Clicking on Item Icons

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12941]
### Description

I have noticed an issue in the preview pane. When I right-click on the icon of an item, whether in the Details section or the Preview section, a context menu appears. However, this should not happen since we can now switch between sections using the "Details" and "Preview" buttons.

### Steps To Reproduce

1. Open the preview pane
2. Right-click on the icon

### Requirements

Identify the cause of the context menu appearing when right-clicking on item icon in the preview pane.

### Files Version

Version 2.5.14.0

### Windows Version

22H2 22621.1848

### Log File

<img width="281" alt="Capture d'écran 2023-07-13 110445" src="https://github.com/files-community/Files/assets/128183422/7d6f1d5f-2e6d-4041-afa3-4bea6fd24c75">

**Comment by yaira2** [comment]
Thank you for your feedback, the context menu is for downloading previews for items in the cloud.

**Comment by Lukiluc29** [comment]
Ah ok, I didn't know because I've never seen this button highlighted even in the Cloud.
