### ISSUE TITLE
Bug: Tags are not displayed in the Preview Pane if no item is selected

### ISSUE THREAD

**Issue by ferrariofilippo** [files-community/Files#12947]
### Description

If no item is selected, the Preview Pane will show details of the current folder. The Preview Pane won't show its tags (even if it has some)

### Steps To Reproduce

1. Select a tagged folder
2. Open the preview pane
3. See that it displays selected folder's tags
4. Open that folder
5. See that the tags section won't be rendered (no tags are detected)

### Requirements

Tags (if any) should always be displayed in the preview pane

### Files Version

Files Preview 2.5.14.0

### Windows Version

Windows 11 Pro 22H2 22621.1992

### Log File

Selected item:
![Screenshot 2023-07-14 135904](https://github.com/files-community/Files/assets/102259289/b8548d09-76a1-460a-9687-e79ccb638636)

No item selected:
![Screenshot 2023-07-14 135854](https://github.com/files-community/Files/assets/102259289/4da690b0-befa-4995-8e65-79f2578c23aa)

**Comment by yaira2** [comment]
Thank you for reporting this issue.
