### ISSUE TITLE
Bug: App crashes when moving multiple files

### ISSUE THREAD

**Issue by be4con** [files-community/Files#12945]
### Description

Repeated issues with Files crashing when attempting to move large files (several GB) by drag and drop from one drive to another

### Steps To Reproduce

1. Drag file + Shift to move from one drive to another
2. Repeat process with a 2nd file whilst the initial file process is ongoing
3. Crash almost always occurs once the first file process completes and the 2nd is ongoing

### Requirements

- e.g. Fix crash that occurs when...
Fix crash that occurs when moving multiple files by drag and drop (with Shift pressed)

### Files Version

2.5.10.0

### Windows Version

10.0.22621.1992

### Log File

[debug.log](https://github.com/files-community/Files/files/12041628/debug.log)

**Comment by Jyoticharan** [comment]
could you please assign me this work

**Comment by be4con** [comment]
Not sure if this is directed at me? Seems unlikely but just in case… sure thing!

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by yaira2** [comment]
@be4con we made some additional improvements in the latest preview, can you try again?
