### ISSUE TITLE
Properties hotkey

### ISSUE THREAD

**Issue by th3v4n** [files-community/Files#12944]
### What feature or improvement do you think would benefit Files?

In regular explorer I can do Alt+Enter or Alt+double click on a file or folder and open the properties window.
 
Can this be added to Files? Seems like an oversight.

Thanks!

Evan

### Requirements

- Add Alt-Enter as a hotkey for opening the properties window.
- Add Alt-Double click as a hotkey for opening the properties window.

### Files Version

2.5.10.0

### Windows Version

10.0.22621.1848

**Comment by yaira2** [comment]
Thank you for your feedback, `alt` + `enter` is already implemented, can you give it a try?
