### ISSUE TITLE
Performance with network shared drives is poor

### ISSUE THREAD

**Issue by MikeChuckRoast** [files-community/Files#12942]
### Description

Performance when browsing files on a network shared drive is poor. It often takes a long time to refresh the page. Tab shows spinner icon and window is frozen. May even result in "not responding" message from Windows. 

### Steps To Reproduce

Browse to a location on a network shared drive. Especially one with many folders and files. 
Simply browse: open folders, go up and down the directory tree. 

### Requirements

Expecting performance to be equivalent to Windows File Explorer. 

### Files Version

2.5.10.0

### Windows Version

10.0.19045.3086

### Log File

[debug.log](https://github.com/files-community/Files/files/12038019/debug.log)

**Comment by MikeChuckRoast** [comment]
It does sound similar; though #12704 seems to be calling out a folder with shortcuts to SMB drives. My use case is browsing the contents of the SMB drive; especially with many files or folders.

**Comment by yaira2** [comment]
Thank you for the feedback, this is on our todo list to look into, and we'll post an update in #12704 when it's resolved.
