### ISSUE TITLE
Bug: Crash when creating a new SFV file

### ISSUE THREAD

**Issue by GalaxyVOID** [files-community/Files#12955]
### Description

Application: Files.exe
CoreCLR Version: 7.0.823.31807
.NET Version: 7.0.8
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at Vanara.PInvoke.Shell32+IContextMenu.InvokeCommand(CMINVOKECOMMANDINFOEX ByRef)
   at Vanara.PInvoke.Shell32+IContextMenu.InvokeCommand(CMINVOKECOMMANDINFOEX ByRef)
   at Files.App.Utils.Shell.ContextMenu+<>c__DisplayClass12_0.<InvokeItem>b__0()
   at Files.App.Utils.Shell.ThreadWithMessageQueue+Internal+<>c__DisplayClass2_0.<.ctor>b__0()
   at Files.App.Utils.Shell.ThreadWithMessageQueue.<.ctor>b__5_0()

### Steps To Reproduce

1. download https://www.quicksfv.org/download.html and install it 
![image](https://github.com/files-community/Files/assets/94946192/053783a6-8245-4ff3-afbe-e4f2fd844777)
2. right click on a file and press create .sfv file 
![image](https://github.com/files-community/Files/assets/94946192/c3eb791c-4f3d-4b8a-9628-334ba606976a)
3. files crashes

### Requirements

- e.g. Fix crash that occurs when...
Pressing on ![image](https://github.com/files-community/Files/assets/94946192/c3eb791c-4f3d-4b8a-9628-334ba606976a)

### Files Version

2.5.14.0

### Windows Version

10.0.22621.1992

### Log File

[debug.log](https://github.com/files-community/Files/files/12062720/debug.log)

**Comment by GalaxyVOID** [comment]
It only happens in files, in the normal file explorer it works like normal

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
@GalaxyVOID can you check if this is fixed in the latest preview build? https://files.community/download
