### ISSUE TITLE
Crashed when folders contain more than 1000 files(images)

### ISSUE THREAD

**Issue by ZhenglinPan** [files-community/Files#12953]
### Description

Crashed when opening a folder contains many(>1000) files. It happens all the time, very unstable.

### Steps To Reproduce

1. Open a folder contains many images.
2. Wait it crash.

### Requirements

- e.g. Fix crash that occurs when open a folder with more than 1000 images(or other files).

### Files Version

2.5.10.0

### Windows Version

10.0.22631 Build 22631

### Log File

[debug.log](https://github.com/files-community/Files/files/12062043/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #12581. You can check there or click subscribe in the right sidebar for updates.
