### ISSUE TITLE
Files Crashed while copying data from usb

### ISSUE THREAD

**Issue by mpsandhu** [files-community/Files#12956]
### Description

It just crashed saying "An error occurred"
I was lucky my USB drive is safe.
but this type of error can damage our external drives

### Steps To Reproduce

Insert any sd card reader having at least 8 gb to PC
select and copy at least any folder having 0.2 to 0.5 GB of data
paste it to your PC SSD location
repeat it at least 5 times one by one without any delay.

### Requirements

- e.g. Fix crash that occurs when...
Copying files from USB drive or sd card to pc

### Files Version

2.5.13.0

### Windows Version

10.0.22621.2066

### Log File

[debug.log](https://github.com/files-community/Files/files/12063189/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report. Can you give the following information.
- What's the contents of the folder your pasting too
- What layout are you using

**Comment by Josh65-2201** [comment]
@mpsandhu Can you answer the above questions please.
