### ISSUE TITLE
Replace File Pickers with Files

### ISSUE THREAD

**Issue by BranchGleaner** [files-community/Files#12957]
### What feature or improvement do you think would benefit Files?

I really like the UI style of the Files, for me it's so much better than the Explorer that comes with the system. 
But unfortunately, when I'm asked to select a file in another program, I still have to select it in the default file picker. 
So, I hope the Files will add the ability to replace the default file pickers.

### Requirements

The following figure shows the system's default file pickers. I hope that Files will replace this window and repaint it with the File's UI style. This would not only be pleasing to the eye, but it would also allow for the interactive logic and tabs provided by Files when selecting a file.
![image](https://github.com/files-community/Files/assets/117826541/94dbc25a-b211-4bf2-9119-05431bbb796b)

### Files Version

2.5.10.0

### Windows Version

10.0.22621.1992

### Comments

Nothing.

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #6314. You can check there or click subscribe in the right sidebar for updates.
