### ISSUE TITLE
Strings use "you" and "us" (etc) where it could/should be avoided

### ISSUE THREAD

**Issue by Jay-o-Way** [files-community/Files#12967]
### Description

Looking at Crowdin, I see a lot of string that use a colloquial style with "we", "you", "us" and so on. I think these styles should be avoided/changed to a more neutral style. Examples:

> To get started, you'll need to grant us permission to display your files. This will open a Settings page where you can grant us this permission. You'll need to reopen the app once you've completed this step. 

> We weren't able to delete this item

> Did you delete this folder?

### Steps To Reproduce

N/A

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

latest/source

### Windows Version

10.0.19045.3155

### Log File

N/A

**Comment by Josh65-2201** [comment]
Thanks for the feedback. What would you change them to?

**Comment by Jay-o-Way** [comment]
For example:

- Files needs permission to access files. This will open a Settings page where permission can be granted. Files needs to be reopened after this step is completed.

- Unable to delete this item

- Was this folder deleted?

In general: KISS - Keep It Short n' Simple

**Comment by yaira2** [comment]
I like keeping it simple but I'm not sure agree that "Was this folder deleted?" is better than "Did you delete this folder?". It depends on the string but "you" is a lot more personal and it friendly.

**Comment by Jay-o-Way** [comment]
> Did **you** delete this folder?

implies/assumes I am responsible and sounds like you are blaming "me". Wouldn't call that friendly.

**Comment by yaira2** [comment]
My apologies if it came off that way, the main point is that there are arguments for both ways and each instance needs to be evaluated. For now, I think it's best to leave them alone because any changes will reset the translations.

**Comment by Jay-o-Way** [comment]
What I mean is that these are just 3 examples, but I've seen many instances. If you want me to list it all up I can do that, but the point of examples is that there are more.

**Comment by Jay-o-Way** [comment]
If you want to see a full list + suggestions, I can create a pr?

**Comment by yaira2** [comment]
> grant us permission

This string is quite outdated and should be replaced with "Grant Files permission..".

> If you want to see a full list + suggestions, I can create a pr?

This is something that needs to be decided on a per string basis. It's something we'll want to address in the future but it's not a priority right now.
