### ISSUE TITLE
Bug: Details pane is missing the item properties

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12964]
### Description

I'm reaching out again because even after two patches, I am still experiencing the same issue. When I enable the preview pane and switch the pane to the "Preview" section, and then proceed to click on multiple files in succession, once I switch to the "Details" section, no information is displayed except buttons "Edit Tags" and "Properties". However, if I perform the same action and switch to the "Details" section on a folder, the information is displayed. This problem only appears in the column layout or when switching from the column layout to another layout.

### Steps To Reproduce

1. Display the preview pane
2. Set the preview pane on preview
3. Go to a file or folder
4. Go to a other file or folder
5. Switch preview pane to details

### Requirements

Investigate and identify the cause of the missing information in the Details view when clicking on multiple files in the Preview section.
Fix any bugs that prevent the display of information in the Details view.

### Files Version

2.5.15.0

### Windows Version

22H2 22621.1992

### Log File

![Capture d'écran 2023-07-17 210106](https://github.com/files-community/Files/assets/128183422/b9e400ae-b726-4dbd-98fd-762ba0e535fa)

**Comment by Lukiluc29** [comment]
This issue persists more and more on my end. When I switch from one document to another using the preview pane and then switch to the details pane, it displays no information except for the name, the tag button, the properties button, and the document preview, instead of the icon.
![Capture d'écran 2023-11-10 185111](https://github.com/files-community/Files/assets/128183422/5be89320-cc2c-4559-bcf1-2399f201a69e)

**Comment by yaira2** [comment]
After a lot of trial and error, I finally found steps to repro this issue.
1. Switch to the column layout
2. Turn on the info pane
3. Switch to the preview pane
4. Select a folder in the column layout
5. Select a file (in the parent folder, not a sub item from the folder that was just selected)
6. Switch to the details pane
