### ISSUE TITLE
Feature: Delay loading Properties button until details are finished loading

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12963]
### Description

I have noticed that when the preview pane is open and I click on a folder or file, the Property button appears before the file information. It would be preferable if the Property button appeared after the file information, similar to the "Edit Tags" button.

### Steps To Reproduce

1. Open preview pane
2. Click on a file or folder

### Requirements

Modify the code to ensure that the Property button appears after the file information in the preview pane.

### Files Version

2.5.14.0

### Windows Version

22H2 22621.1992

### Log File

![Capture d'écran 2023-07-17 203946](https://github.com/files-community/Files/assets/128183422/23774be7-ab95-4620-8200-7d44c289262d)

**Comment by yaira2** [comment]
Thank you for the feedback
