### ISSUE TITLE
Crashes on initiation

### ISSUE THREAD

**Issue by tRahErug7sTi** [files-community/Files#12966]
### Description

App starts, but crashes while loadng the windows

### Steps To Reproduce

Just start the applicaiton after Win 11 fully launched

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

Sorry  can't get it due to app creashing

### Windows Version

Win 11 22621.1992

### Log File

[debug.log](https://github.com/files-community/Files/files/12074615/debug.log)

**Comment by tRahErug7sTi** [comment]
Good luck with it, hope you can fix it.  I really like the app, much stronger than the native Windows app.

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by tRahErug7sTi** [comment]
Okay, the previous version installs normally and does not crash.  Working fine.

**Comment by yaira2** [comment]
Thanks for the report, if it's working in the preview build, the fix will be available for the stable version in a few weeks.
