### ISSUE TITLE
Bug: Recycle Bin combine "group/sort" with Original path/folder

### ISSUE THREAD

**Issue by Jay-o-Way** [files-community/Files#12973]
### Description

I'm looking at my Recycle Bin and the groups are not sorted alphabetically. I was looking at the **full path**.

![image](https://github.com/files-community/Files/assets/65828559/752d2e6f-fa7a-465e-9267-5a4630d51cfa)

This can be explained because the function is using the name of the **folder** only.

Now when I set **Group** to **None**, then **Sort** to **Original path**, there's one more glitch. There's no explanation for this.

![image](https://github.com/files-community/Files/assets/65828559/ab181676-7a2a-4dd9-8a83-c1431119654e)

### Steps To Reproduce

- Open Recycle Bin (make sure to have items from different locations)
  - set **Group by** to **Original folder**, _or_
  - set **Group by** to **None** and **Sort** by **Original path**
- look at the full paths

### Requirements

Either use full path or folder name; in both the UI and the code-behind.

### Files Version

2.5.15.0

### Windows Version

10.0.19045.3155

### Log File

[debug.log](https://github.com/files-community/Files/files/12089446/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
> I'm looking at my Recycle Bin and the groups are not sorted alphabetically. I was looking at the full path.

@Jay-o-Way it looks like you still have it set to sort by name, can you see if changing the sort option to "path" works as expected?

**Comment by Jay-o-Way** [comment]
Everything now works as expected. Thanks :)

**Comment by yaira2** [comment]
Thanks for the update
