### ISSUE TITLE
Feature: Save and restore tabs when restart the computer with Files running.

### ISSUE THREAD

**Issue by IzayoiSake** [files-community/Files#12988]
### What feature or improvement do you think would benefit Files?

I raised issue#11949 before.
This problem still exists today, directly shutting down or restarting the computer does not trigger Window_Closed() or AppUnhandledException(). Therefore, SaveSessionTabs() will not be executed.
I implemented this logic through other methods(https://github.com/IzayoiSake/Files), and the implementation method is as follows:
1.Add a new List CurrentTabsList in GeneralSettingsService.
2.When Tab changes, write Tabs containing ID information into SharedMemory and CurrentTabsList.
3.If ContinueLastSessionOnStartUp is checked, it will detect whether SharedMemory matches CurrentTabsList when starting the Files program.
4.If it does not match, it means that the computer restarted or the Files program was unexpectedly closed without triggering SaveSessionTabs().
5.Restore Tabs recorded in CurrentTabsList.
After running it on my computer, no abnormalities have been found for the time being. I want to pull a request for the code, but I am not sure whether it needs approval as written in ACKNOWLEDGE.
Affected functions include: OnNavigatedTo() and SaveSessionTabs() of Class MainPageViewModel.
Added some variables and functions (especially in MainPageViewModel).

### Requirements

-a approval to pull a request

### Files Version

2.5.10.0

### Windows Version

10.0.22621.1992

**Comment by yaira2** [comment]
@IzayoiSake would you like to open a PR?

**Comment by IzayoiSake** [comment]
yes

**Comment by yaira2** [comment]
Merging with #12624
