### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by jokbon** [files-community/Files#12989]
### What feature or improvement do you think would benefit Files?

Files slow startup frustrates the user when something needs to be quickly done.
Starting files is extremely slow.

### Requirements

- Suggesting adding gpu aceleration. 
- Gpu texture uncompresion.
- Reducing files cpu usage. (no folder recalculations enabled and it alredy made me wake up by buzzing of procesor early morning before even before my alarm was set up)

### Files Version

2.5.14.0

### Windows Version

22621.1848

### Comments

![image](https://github.com/files-community/Files/assets/29400409/e840cdd7-36b4-4c98-a965-557626e1e8c0)
![image](https://github.com/files-community/Files/assets/29400409/66c079c5-7c44-461c-ad09-c972d5f94976)

**Comment by yaira2** [comment]
Thank you for your feedback, we're working on improvements to performance (tracking in #4180) and improvements to startup speed are being worked on as well.

**Comment by yaira2** [comment]
We're excited to share that startup performance will be significantly improved in the upcoming release of version 3. You can download the preview version from our website https://files.community/download.

**Comment by yair100** [comment]
@jokbon we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
