### ISSUE TITLE
Selected Item Preview Pane

### ISSUE THREAD

**Issue by eraychumak** [files-community/Files#130]
By the default, there's a lot of empty space on the right section of the explorer, it would be a nice addon to be able to preview your selected file _(very rough example below...)_ so you don't have to install applications like QuickLook to do the same thing.

![file_uwp](https://user-images.githubusercontent.com/44278658/58911049-e99a3480-870e-11e9-81c5-dcb8b96102e4.png)

**Comment by Poopooracoocoo** [comment]
File Explorer calls it Details Pane and Preview Pane fyi

**Comment by yaichenbaum** [comment]
Files UWP works with QuickLook, is there a benefit of including similar functionality when QuickLook already does this?

**Comment by duke7553** [comment]
This would be a new experience powered by QuickLook (if possible)

**Comment by EukalyptenHD** [comment]
> Files UWP works with QuickLook, is there a benefit of including similar functionality when QuickLook already does this?

Why download an entirely separate app for this one feature when you can just support it natively?

**Comment by yaichenbaum** [comment]
@EukalyptenHD The reason would be is the QuickLook provides additional functionality, of course having a built in option would be nice as well, but for the meantime, I would recommend trying out QuickLook.

**Comment by duke7553** [comment]
Considering a separate app exists (and is now integrated with Files), I don't think this will be an area of focus for near future unless we hear more about how something like this can add unique value to the experience.

**Comment by callmehanu** [comment]
Yep, for me **preview pane** is also really necesary. Quicklook works greate but need an extra trigger. For example if I looking for a photo, I need to select photos one by one and after hit spacebar, this is really tiresome. Yep, Quicklook is pretty and fancy but for "real work" lack of convenience. 

On other hand, [Metro Ccommander](https://www.microsoft.com/store/productId/9WZDNCRFJB30) offers a **full screen** preview pane with many powerfull shorcuts but with this we loose the focus. 

I think a preview pane can really be a greate tool for hard users and the most simple way to find folders and files on the fly,

And if you need help maybe I can work the design, I'm ux designer!

**Comment by yaichenbaum** [comment]
@callmehanu A preview pane is on our backlog. We would love to work with the community towards creating a design to base the feature off of. Concepts are welcome, but keep in mind that the final decision is up to the maintainers of the app.

**Comment by winston-de** [comment]
I've been working on making a preview pane the past couple of weeks (#2756).
Since I don't have the time to cover all file types, what would you guys consider the most useful? 

So far I have support for pdfs, videos, audio files, images, markdown, and text files.

**Comment by yaichenbaum** [comment]
> I've been working on making a preview pane the past couple of weeks (#2756).
> Since I don't have the time to cover all file types, what would you guys consider the most useful?
> 
> So far I have support for pdfs, videos, audio files, images, markdown, and text files.

This seems like a good starting point, any future file types can be added later on either in the app or via an extension.

**Comment by yaichenbaum** [comment]
@eraychumak #2756 implements this feature request, please let us know if you have any feedback.
