### ISSUE TITLE
Irrelevant storage information for Sidebar cloud drives

### ISSUE THREAD

**Issue by iamr8** [files-community/Files#13007]
### Description

After updating to the latest version through Microsoft Store, I'm encountering strange behavior that shows the same details for all the Cloud Drives on the sidebar when I hover the mouse over them.

### Steps To Reproduce

1. Open up the App
2. Hover the mouse over the Side-bar Cloud Drivers until the Detail Flyout shows up!

https://github.com/files-community/Files/assets/4571571/ea372c6b-3e1d-4f55-9bcd-d3426250df69

### Requirements

It must show the detail for each Cloud Drive, according to its data, not One Storage Data for all of them at the same time.

### Files Version

2.5.20.0

### Windows Version

Windows 11 22H2  22621.1992

### Log File

[debug.log](https://github.com/files-community/Files/files/12114163/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #11326. You can check there or click subscribe in the right sidebar for updates.

The current goal is to show the correct information for drive that can and disable them for the reset.
