### ISSUE TITLE
Bug: Opening properties for OneDrive file causes the item to be downloaded

### ISSUE THREAD

**Issue by Silther** [files-community/Files#13006]
### Description

if you open the properties of OneDrive, it will start to download all the files, probably to calculate the size of the OneDrive folder.

that shouldn't happen

### Steps To Reproduce

1. open the properties of your OneDrive folder
2. Windows notification will tell you that files are automatically downloaded
3. it only stops if all files have been downloaded 

### Requirements

Viewing the properties shouldn't download the file.

### Files Version

2.5.20.0

### Windows Version

10.0.22621.1992

### Log File

[debug.log](https://github.com/files-community/Files/files/12114043/debug.log)

**Comment by yaira2** [comment]
> probably to calculate the size of the OneDrive folder

Does turning the option off help?

**Comment by yaira2** [comment]
I misunderstood the issue, I thought you were using the option to calculate folder sizes.

**Comment by GGProGaming** [comment]
Oh word. This is why I had that issue. I had 400gb that was trying to redownload and I had no clue why it was doing so. This needs to be fixed!

**Comment by yaira2** [comment]
> probably to calculate the size of the OneDrive folder

Your theory was correct! This issue should be fixed in the next update.
