### ISSUE TITLE
One of my drives/partitions doesn't show up in the Navigation

### ISSUE THREAD

**Issue by Jay-o-Way** [files-community/Files#13002]
### Description

I have an SSD with two main partitions: `C` and `O`. `C` shows up, but `O` is gone. Weird thing: it was visible in the past. I have restarted and toggled the setting for "default explorer" on and off.
![image](https://github.com/files-community/Files/assets/65828559/bb77ffff-7a11-41b8-b138-a35ab304adcb)

Navigate via the adressbar does work.

### Steps To Reproduce

Have an SSD with more then one partition?

### Requirements

All partitions shown in "Stations"

### Files Version

2.5.15.0

### Windows Version

10.0.19045.3269

### Log File

[debug.log](https://github.com/files-community/Files/files/12112326/debug.log)

**Comment by Jay-o-Way** [comment]
Oh, nevermind. Just updated to 2.5.20.0 and now it's back 😄

**Comment by yaira2** [comment]
@Jay-o-Way there was indeed an issue here but it was fixed, thanks for the report.
