### ISSUE TITLE
change the onedrive icon

### ISSUE THREAD

**Issue by xIUPITERx** [files-community/Files#13005]
### What feature or improvement do you think would benefit Files?

change the onedrive icon in the cloud drive section from this 

![image](https://github.com/files-community/Files/assets/97352673/8082a560-aa61-4fb4-8ab2-00e57a0dc5d2)

to that

![image](https://github.com/files-community/Files/assets/97352673/1d4f493c-17d6-4b6f-9723-3ac71120ce7e)

### Requirements

- better design
- more overview
- greater consistency with windows files explorer

### Files Version

2.5.20.0

### Windows Version

10.0.22621.1992

**Comment by yaira2** [comment]
@xIUPITERx this is what we're already using, if it's displaying differently, it might depend on your screen resolution or display scale.
![image](https://github.com/files-community/Files/assets/39923744/8bf00055-6a69-4623-b42d-be3a006c2ba5)

**Comment by yaira2** [comment]
The icons aren't hardcoded for legal reasons, instead they are taken from File Explorer at run time.

**Comment by yaira2** [comment]
We appreciate the feedback but it's important to note that consistency with File Explorer isn't something we work on. That said, the sidebar icons depend on what Windows provides for the requested size (I think this is 16x16).
