### ISSUE TITLE
Bug: App gets stuck on splash screen after updating

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#13001]
### Description

Files gets stuck on the splash screen after installing an update, closing the app and opening it again fixes the issue.

### Steps To Reproduce

1. Install update by clicking the icon on the toolbar
2. After the app reopens, observe that it gets stuck on the splash screen

### Requirements

- Fix issue where the app gets stuck on the splash screen

### Files Version

v2.5.20

### Windows Version

Windows 11

### Log File

NA

**Comment by hishitetsu** [comment]
There is no problem when updating from Microsoft Store.

**Comment by yaira2** [comment]
I can confirm that, it's only when we use do the update through the app.
