### ISSUE TITLE
Crash when working with a folder containing a large number of MKV files

### ISSUE THREAD

**Issue by random4t4x14** [files-community/Files#13004]
### Description

When opening and scroll through a folder with a large number of MKV files, and attempting to open one of the files in an external program, the application crashes.

### Steps To Reproduce

1. Open a folder with lots of MKV files
2. Scroll through and open a file with an external program (in this case MediaInfo)
3. Boom

### Requirements

The expected behavior is that the app doesn't crash, despite the large file set.

### Files Version

2.5.10.0

### Windows Version

Windows 10 Pro Version	22H2 OS build	19045.3208 Windows Feature Experience Pack 1000.19041.1000.0

### Log File

[debug.log](https://github.com/files-community/Files/files/12113651/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report. Can you update and see if this is an issue in 2.5.20.

**Comment by Josh65-2201** [comment]
@random4t4x14 Can you please see if this is an issue in 2.5.21.0 for you.
