### ISSUE TITLE
more accessible show/hide dot files button

### ISSUE THREAD

**Issue by xIUPITERx** [files-community/Files#13008]
### What feature or improvement do you think would benefit Files?

add an option to show/hide dot files in this menu

![image](https://github.com/files-community/Files/assets/97352673/12f3d070-395e-4c74-88e0-1d0e240447ff)

### Requirements

- better overview
- more accessible

### Files Version

2.5.20.0

### Windows Version

10.0.22621.1992

### Comments

in the most use cases you don't need them, so they should be hidden, but if you need them, opening the settings is to slow.

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #8423. You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
> add an option to show/hide dot files in this menu

Thank you for your feedback, we don't plan to add this option to the menu because it's very specific and not used on a regular basis. That said, we're working on a command palette #12977 that will make it easier to access this action and many others.
