### ISSUE TITLE
Mebibyte vs megabyte

### ISSUE THREAD

**Issue by Silther** [files-community/Files#13009]
### What feature or improvement do you think would benefit Files?

the properties uses "MB" which stands for megabyte, but it calculates with 2^20 bytes not 10^6 bytes.

![image](https://github.com/files-community/Files/assets/97352673/2e598671-ac29-43ba-89ee-6c1950646c78)

so either change it to MiB or calulate with 10^6.

### Requirements

- uses the correct term

### Files Version

2.5.20.0

### Windows Version

10.0.22621.1992

### Comments

https://simple.wikipedia.org/wiki/Mebibyte#:~:text=A%20mebibyte%20(a%20contraction%20of,or%20computer%20storage%2C%20symbol%20MiB.&text=The%20mebibyte%20is%20closely%20related,see%20binary%20prefix%20for%20background).

**Comment by 0x5bfa** [comment]
@yaira2 I suggested this before. What do you think of this again?

**Comment by Leopold702** [comment]
I also suggested this in #10545, in was just today combined with #10075.

**Comment by yaira2** [comment]
Merging with #10075
