### ISSUE TITLE
Progress when copying files - please make that visible!

### ISSUE THREAD

**Issue by fredphoesh** [files-community/Files#13016]
### What feature or improvement do you think would benefit Files?

Hi,
I often have to copy large files from my SD card to the computer and very much want to see progress, so I know it's happening, how long it might take, if there is any issue, speed it's transferring at etc etc... 
I don't see a setting to make this visible, but it's definitely something i miss a lot, using Files instead of Windows File Explorer.
Thanks,
Mark.

### Requirements

- This proposal will accomplish ability to see whether your files are indeed being copied, how long it might take, at what speed, if there are issues...

### Files Version

2.5.13.0

### Windows Version

10.0.22631.2048

### Comments

Thanks for the great app.

**Comment by fredphoesh** [comment]
Additionally, when the copy process is finished, I have no way of knowing if and when this has happened, making it a risk to my SD disk if I eject it prior to completing the copy process. Thanks.

**Comment by yaira2** [comment]
@fredphoesh there is a button on the toolbar that shows when a file operation is ongoing, is it not displaying?

**Comment by Josh65-2201** [comment]
Its the icon next to settings one on the top right. As for speed this is being tracked in #11265. You can check there or click subscribe in the right sidebar for updates. 
Also if you safety eject the SD card from the taskbar USB icon it will tell you if content is being written to it.

**Comment by fredphoesh** [comment]
Hi Josh, nope, I don't see any button next to the settings (other than the update button which I've just used), only the search field.
But can't this be made to be a popup like Windows Explorer does? Or some way to make it always visible. I would always want to see progress when copying important files!
![image](https://github.com/files-community/Files/assets/5565996/cce78e45-421a-4aba-bc90-ab7aec2eab95)

**Comment by Josh65-2201** [comment]
It only shows for that session right now. Did you try doing a file transfer and then checked?

**Comment by fredphoesh** [comment]
Hi Josh, no I hadn't tried that but just did now. Interesting that when I copy from HD to HD I get the regular windows popup, but when copying from SD card to HD that copy status button appears... so it seems it "could" have the windows popup at all times, just it's been partially removed?

**Comment by Josh65-2201** [comment]
Files doesn't have any popups as Files hasn't made any. It will another program making them.

**Comment by fredphoesh** [comment]
That's weird... that the windows popup happens when copying HD to HD but not SD to HD... and conversely, the Files "button" only appears when there is no Windows popup!
