### ISSUE TITLE
change the tags icons in the settings menu

### ISSUE THREAD

**Issue by xIUPITERx** [files-community/Files#13017]
### What feature or improvement do you think would benefit Files?

change the tags icons in the settings menu to the new ones as they scale badly on high resolution monitors

![image](https://github.com/files-community/Files/assets/97352673/2b834522-7047-44ef-88f2-1f8cb063480b)
 

### Requirements

- This proposal will accomplish a better design

### Files Version

2.5.20.0

### Windows Version

10.0.22621.1992

**Comment by yaira2** [comment]
Thank you for your feedback, this issue is resolved in our dev branch. We're also working on updating the tag icon in the different layouts so there is no need to open an issue for that 🙂
