### ISSUE TITLE
Bug: Layout button is not highlighted when adaptive layout is turned off

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#13010]
### Description

When I turn on adaptive layout, the highlight on the layout button will disappear. But when I turn off adaptive layout by the toggle switch, the highlight on the button of the originally selected layout is still missing.

![image](https://github.com/files-community/Files/assets/66369541/4e93038d-249c-4561-abb8-319bd66436d2)

### Steps To Reproduce

1. Turn off adaptive layout by the toggle switch.
2. See no layout buttons are not highlighted.

### Requirements

The button of the current layout should be highlighted.
I think it should even when the adaptive layout is enabled.

### Files Version

2.5.20.0

### Windows Version

10.0.22621.1992

### Log File

n/a

**Comment by yaira2** [comment]
Thank you for reporting this issue.
