### ISSUE TITLE
Feature: Allow manually checking for updates

### ISSUE THREAD

**Issue by cartifanwlr** [files-community/Files#13018]
### What feature or improvement do you think would benefit Files?

Files automatically checks for updates, but there should be an option for manual checking as well.

### Requirements

- A check for updates button should be implemented that checks when clicked. 

### Files Version

2.5.1.0

### Windows Version

10.0.22631.2048

**Comment by yaira2** [comment]
@cartifanwlr thank you for your feedback, can you share your use case for this?

**Comment by cartifanwlr** [comment]
> @cartifanwlr thank you for your feedback, can you share your use case for this?

The automatic update system seems slow to me, it doesn't find the new update immediately. A manual update system can mitigate this issue.

**Comment by Josh65-2201** [comment]
Updates are check for when Files is opened so it's as fast as it gets and a manual button wouldn't change that.

**Comment by yaira2** [comment]
What Josh said is correct, the automatic update system checks for updates whenever the app is launched. If you download Files from the Microsoft Store, you have the added benefit of background updates as well.
