### ISSUE TITLE
Bug: Right clicking folder when it's still loading causes app to crash

### ISSUE THREAD

**Issue by Pietro228** [files-community/Files#13015]
### Description

Hi,

Files sometimes crashes when I want to open file or right click on it. It happens very often and it's really annoying and it's getting unusable for me.

In this picture I can't click anything and it's just a static window. It happens on other files and not only this one. Sometimes when I click a folder it also freezes.
![obrazek](https://github.com/files-community/Files/assets/53868994/5bc697c3-fd50-4f77-aa43-6cf60789147b)

Maybe it's because of the right pane. I'll try to use Files without it and I'll update if it crashes again or not.

### Steps To Reproduce

1. Click or right click on a file while folder is still loading
2. Application freezes

### Requirements

- Right click menu should appear.

### Files Version

2.5.10.0

### Windows Version

10.0.22631.2048

### Log File

[debug.log](https://github.com/files-community/Files/files/12120930/debug.log)

**Comment by Pietro228** [comment]
It still appears in 2.5.21.0

**Comment by yaira2** [comment]
I'm not seeing anything in the log file, @hishitetsu any ideas?

**Comment by Pietro228** [comment]
It appears when I open a tab / folder and quickly right click the file.

**Comment by hishitetsu** [comment]
Right now I have no idea. What about this?

> Maybe it's because of the right pane. I'll try to use Files without it and I'll update if it crashes again or not.

**Comment by Pietro228** [comment]
I now use Files without the right pane but it still crashes.

**Comment by hishitetsu** [comment]
I found a way to reproduce it. If I right-click immediately after the application starts with some folder that is not the home page, it will definitely freeze.

**Comment by Pietro228** [comment]
Yep, that's it
