### ISSUE TITLE
f

### ISSUE THREAD

**Issue by burugaia** [files-community/Files#13027]
### What feature or improvement do you think would benefit Files?

I would like to be able to send feedbags from within the app.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.5.21.0

### Windows Version

10.0.19045.3208

**Comment by Josh65-2201** [comment]
You can in Files Settings > About > Send feedback

**Comment by burugaia** [comment]
It would be easier to send feedbags from within the app than to send feedbags from a browser.
