### ISSUE TITLE
Thumbnails in zip files

### ISSUE THREAD

**Issue by shravan2x** [files-community/Files#13029]
### What feature or improvement do you think would benefit Files?

Thumbnails currently don't show when viewing compressed files. Could there be an option to enable this?

### Requirements

- Add option to display thumbnails for media in compressed files, for perf reasons since not everyone would want it.
- When opening a compressed file, generate thumbnails for media if the option is set.

### Files Version

2.5.21.0

### Windows Version

22621.1992

**Comment by yaira2** [comment]
@shravan2x thank you for your feedback, thumbnails aren't available for compressed files by design. You can however extract the archives to view them.

**Comment by shravan2x** [comment]
@yaira2 Can you clarify why we want this behavior by design? It seems like it would be a useful feature.

**Comment by shravan2x** [comment]
@yaira2 Bump, could you clarify the above?

**Comment by yaira2** [comment]
I'm not sure the reasoning behind this but it's consistent with the behavior in File Explorer as well.

**Comment by Josh65-2201** [comment]
It isn't possible when compressed as Files (Windows File Explorer too) would have to decompress the archive to get the correct data for that file and then generate the thumbnail. It wouldn't make sense to auto extract archive as you browsed through it.

**Comment by shravan2x** [comment]
I agree that it's consistent with the behavior in File Explorer. But File Explorer is an outdated tool. That's what makes Files.app so amazing - it feels like it's built for 2023!

Yeah, you'd have to decompress the archive to get the correct data for each file. But if done with virtualization in mind, you'd only have to decompress the _images_ and _videos_ that are visible in the current frame. On modern systems, this is usually an acceptably expensive operation, especially keeping in mind that user convenience would take priority.

I've also personally built a similar feature - the performance hit isn't much on a modern multi-core machine.

**Comment by GPBeta** [comment]
I'm looking for an modern file explorer to preview images in zips too.
It's disappointing that Files refuse doing it, but my workaround is use something like WinMount to mount the zip file and preview images inside with the old school file explorer or Files.app,

**Comment by jmonachesi** [comment]
> I'm not sure the reasoning behind this but it's consistent with the behavior in File Explorer as well.

I just want to point out that the only reason I'm looking for a replacement for Windows Explorer is that exact same feature. I don't think missing features are things to be considered as consistent behavior but in any case it's your software.
