### ISSUE TITLE
Files is slow to open folders

### ISSUE THREAD

**Issue by michelepoletto3d** [files-community/Files#13024]
### Description

When I open any folder in Files, it doesn't open immediately but takes about 2 seconds to display the contents of the main folder.

I have a PC with 128GB ram, usually 110 free, GPU Nvidia RTX 3080, CPU AMD Ryzen Threadripper 3960X, 
disk C (system) = 1TB SSD
disk D (data) = 4TB HHD
disk E (backup) = 4TB HHD

3 account of google drive in streaming (disk G, H, I)

### Steps To Reproduce

1. Open Files.

### Requirements

- Please speed up the time it takes to open a folder to a few milliseconds. No more than 500ms.

### Files Version

2.5.20.0

### Windows Version

10.0.22621.1992

### Log File

[debug.log](https://github.com/files-community/Files/files/12130004/debug.log)

**Comment by yaira2** [comment]
@michelepoletto3d can you clarify if you're referring to startup speed or something else?

**Comment by michelepoletto3d** [comment]
I'm referring to the startup time, every time I open an instance of Files.

**Comment by yaira2** [comment]
Startup performance is one of our highest priorities and something we’re working on improving. We’d like the progress to be faster but unfortunately there are some limitations in the WinAppSdk framework. We hope these limitations will be resolved in future versions of WinAppSdk, but in the meantime, we’ve been working on a lot of smaller optimizations that we hope will add up over time.

**Comment by yaira2** [comment]
Merging this with #4180

**Comment by yair100** [comment]
@michelepoletto3d we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
