### ISSUE TITLE
Feature: Show edit tag button in details pane at all times

### ISSUE THREAD

**Issue by RunicLena** [files-community/Files#13025]
### What feature or improvement do you think would benefit Files?

Having the button only appear when there are already tags on the file is annoying. The user must instead right click the file to add a tag, and *then* the button appears, after it's use was fulfilled by something else.

### Requirements

Simply keep the button on the pane when no tags are present on the file. Maybe move it next to properties so there's no empty tags section?

### Files Version

2.5.21.0

### Windows Version

10.0.22621.1992

**Comment by Josh65-2201** [comment]
Thanks for the feedback, I've added this to the project board.

**Comment by yaira2** [comment]
@RunicLena this issue is fixed in our dev branch and will be included in the next release.
