### ISSUE TITLE
Support for PowerToys Peek

### ISSUE THREAD

**Issue by hAug0** [files-community/Files#13037]
### What feature or improvement do you think would benefit Files?

There should be support for the PowerToys tool Peek which in my case is activated with the shortcut Crtl and space.

### Requirements

-Recognizing pattern and letting the app open the preview window

### Files Version

2.5.21.0

### Windows Version

10.0.19045.3208

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #12432. You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
@hAug0 thank you for your feedback, we're ready to add this feature to Files but PowerToys doesn't have an API that'll enable us to do this.
I opened an issue on the PowerToys repo to start the discussion on creating an api for third party file managers https://github.com/microsoft/PowerToys/issues/26422
