### ISSUE TITLE
Sudden crash while removing graphic-files.

### ISSUE THREAD

**Issue by tarokawa516** [files-community/Files#13032]
### Description

1. Open a folder which contains many graphics.
2. Select many old files.
3. hit delete key to remove old files. - while removing graphics, unexpected crash happens. 

### Steps To Reproduce

1. Open a folder which contains many graphics.
2. Select many old files.
3. hit delete key to remove old files. - while removing graphics, unexpected crash happens. 

### Requirements

Yearh please do not crash lol

### Files Version

2.5.21.0

### Windows Version

10.0.22621.1992

### Log File

[debug.log](https://github.com/files-community/Files/files/12135738/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, by `graphics` do you mean images?

**Comment by tarokawa516** [comment]
Yes. JPEG, PNG images.
This crash happens rarely. Tried again, then removed successfully. (This means hard to reproduce again...)

Might be related to preview function? I always open preview pain on right-side.

Files app was full sized, using 4K monitor. Usually showing about 100 images on screen, removing about old about 100 images from containing about 200 images folder.

**Comment by Josh65-2201** [comment]
This may be related to #12581

**Comment by yaira2** [comment]
@tarokawa516 which layout were you using when the crash occured?

**Comment by tarokawa516** [comment]
Well, I share screenshot of my layout. 4K-Fullscreen is used for this folder. After then, no crashes again.
![screenshot-sample](https://github.com/files-community/Files/assets/65443988/7d13c491-bd6c-41de-8750-31e979a09faf)

**Comment by yaira2** [comment]
It may have just been a one off, has it happened again since then?

**Comment by tarokawa516** [comment]
No, never happen. Thumbnails improved rapid and updated version never crash.
Thank you!

**Comment by yaira2** [comment]
Awesome! If you haven't already, you can get the preview version of Files from https://files.community/download
