### ISSUE TITLE
Please provide a preview option

### ISSUE THREAD

**Issue by ShikhnadiDhokla** [files-community/Files#13034]
### What feature or improvement do you think would benefit Files?

**1.)** If i hover over some **video or other file**, it should preview them and start to play them .

It really helps to know which file is that without opening it.

Please add this function. 

( PS you can see , when i hover over a video in my current file explorer, the video becomes big and it begins to play.  )

![image](https://github.com/files-community/Files/assets/105537985/fe362c6e-f474-4008-a87b-b9ede5d8f49c)

**2).** Also if possible please add a preview window on right side, so we can **preview files / pdf** without opening them .

(PS - you can see the pdf i selected started to preview it self on right side )

![image](https://github.com/files-community/Files/assets/105537985/edb5843c-b92d-45c2-b90b-8fe5e5ce4a20)

### Requirements

- This proposal will accomplish saving time while hovering over files. 

### Files Version

2.5.21.0

### Windows Version

10.0.19045.3208

**Comment by ferrariofilippo** [comment]
> **2).** Also if possible please add a preview window on right side, so we can **preview files / pdf** without opening them .

This feature is already implemented, you can toggle it either by using `Ctrl + P` or clicking this button in the toolbar
![image](https://github.com/files-community/Files/assets/102259289/03d39c5e-8122-4588-9b3d-eb5c61e75ebc)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, you can use Quick look or Seer Pro and then press space to view them.
You can also use the preview pane, right now there isn't an auto play feature but is being tracked in #12879. You can check there or click subscribe in the right sidebar for updates.

If you want it to work with hover you can enable Files settings > Folders > Select files and folders when hovering over them

**Comment by ShikhnadiDhokla** [comment]
yeah but , we cannot see it by hovering over it

hovering function would be good

**Comment by Josh65-2201** [comment]
Files will likely go the direction of adding auto play on the preview pane. Then with the select files on hover option it would work.

**Comment by ShikhnadiDhokla** [comment]
"  Files will likely go the direction of adding auto play on the preview pane. Then with the select files on hover option it would work. "

Sorry didnt got you

**Comment by ShikhnadiDhokla** [comment]
hi , there are 2 more issues with the preview option , that you have made in files 

1). While opening a pdf for preview , it provides for left to right view (see pic1) , rather than top to down. it would be better to have top to down preview.  (see pic 2)

2. The clarity of current preview is not very good (at least as far as pdf are concerned)  (again see pic 1 vs pic 2  preview quality)


**PIC 1** 

![image](https://github.com/files-community/Files/assets/105537985/70a6ecec-edb5-4adc-9ea9-460e8a8dcc9f)


**PIC 2** 


![image](https://github.com/files-community/Files/assets/105537985/3b82979d-2fc7-40c3-82f2-a9e08cd83600)

**Comment by Josh65-2201** [comment]
You can make a separate feature request to have PDF be vertical rather then horizontal scrolled.
The low quality PDF preview are tracked here #5117

**Comment by yaira2** [comment]
@ShikhnadiDhokla have you tried QuickLook? It allows you to preview many file types without opening them.

**Comment by ShikhnadiDhokla** [comment]
@yaira2 , have tried Quick look, but have to press space bar to view content., It does not makes it that user friendly.

**Comment by yaira2** [comment]
@ShikhnadiDhokla once the QuickLook preview is open, you can use the arrow keys to switch between previews. I agree that having a built-in preview when hovering over files would be convenient, but it wouldn't be able to support all the file types it wouldn't exactly be good for performance.
