### ISSUE TITLE
Files - MS Explorer Manager Alternative

### ISSUE THREAD

**Issue by ExoticImages** [files-community/Files#13031]
### What feature or improvement do you think would benefit Files?

I've reviewed many alternatives, and they all sport new features, yet the one feature that is missing, has been since Win7, is the ability to truly customize the explorer to suit a person's need to have a worthy file manager.

In Win7, I could, as a photographer, add one or many, of my photographs as a "BACKGROUND right inside explorer. The font's color and lettering outlines changed automatically to match the colors of the images. In other words, a light photo would produce a black font with a white outline, or precision shadow around it. Likewise, a dark image would generate a white font with black, red, or blue outline at the choice of the user.

When someone goes back in time to produce such a file manager, that would be an awesome sight to see, and a file manager that would never be boring. Thanks, Alexa Shaw, Just A Simple Photographer

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.0

### Windows Version

Windows 11 22H2

### Comments

It'll be nice to see such an open source addition to the PC world.

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Are you talking about set a image as Files background?

**Comment by mdtauk** [comment]
> Thanks for the feedback, Are you talking about set a image as Files background?

I read that as the Desktop Wallpaper from within Explorer.

This can still be done in File Explorer 
![image](https://github.com/files-community/Files/assets/7389110/a07bc2a6-9057-45a0-af8b-edf7af699faa)

As well as with Files
![image](https://github.com/files-community/Files/assets/7389110/a9500c9f-34ae-435f-a7d3-9182bc3957f7)

**Comment by yaira2** [comment]
@ExoticImages can you clarify?
