### ISSUE TITLE
Bug: Files opens on all Explorer calls (Desktop included) on Windows beta

### ISSUE THREAD

**Issue by cartifanwlr** [files-community/Files#13030]
### Description

If Files is set as default file manager, running Explorer will open Files instead. This is not what used to happen, folders opened from the desktop would still open in Files but Explorer could still launched from Run/CMD.

### Steps To Reproduce

1. Make Files the default file manager.
2. Open the Run prompt.
3. Type "explorer"
4. Observe bug as Files opens in place of Windows Explorer.

### Requirements

- Return to the old behavior where Explorer could still be launchable.

### Files Version

2.5.21.0

### Windows Version

10.0.22631.2050

### Log File

[debug.log](https://github.com/files-community/Files/files/12134924/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, but this is intended as the option replace all calls to Windows File Explorer. You can still open it by putting a path in like `c:` this also works in Files address bar.

**Comment by cartifanwlr** [comment]
> Thanks for the feedback, but this is intended as the option replace all calls to Windows File Explorer. You can still open it by putting a path in like `c:` this also works in Files address bar.

It wasn't like this though. I could open Explorer just fine before the update. In fact, it has come to the point where when I start Windows, the shell won't load as it will not load Explorer and instead start Files.

**Comment by Josh65-2201** [comment]
Can you try turn the option off and confirm it's from Files causing the desktop to load. You can also turn it back on and see if it fixes it.

**Comment by Josh65-2201** [comment]
Since your on the beta branch of Windows did it update before the issue started

**Comment by cartifanwlr** [comment]
> Can you try turn the option off and confirm it's from Files causing the desktop to load. You can also turn it back on and see if it fixes it.

I did check Task Manager. With the option on, the desktop won't load but there is one Files instance active. Running explorer repeatedly seems to get it through, but several Files instances open this time.

> Since your on the beta branch of Windows did you update before the issue started

I did. Maybe it's issues with the updates WinUI3 explorer that's causing it.

**Comment by Josh65-2201** [comment]
Can you try turning the option off and see if the desktop is ran like normal.
If it does it's very likely a Windows issue and Files probably wont be able to fix it for awhile.

**Comment by cartifanwlr** [comment]
> Can you try turning the option off and see if the desktop is ran like normal. If it does it's very likely a Windows issue and Files probably wont be able to fix it for awhile.

The desktop launches as normal when the option is turned off.

**Comment by Josh65-2201** [comment]
Thanks for the information, I've added this to the project board.

**Comment by yaira2** [comment]
@cartifanwlr thank you for your feedback, this is indeed one of the side effects of modifying the registry keys. I'm not sure why the behavior was different before (we didn't make any changes that I'm aware of), but it's possible that it depends on the Windows version. We've shared this feedback with Microsoft and requested a built-in setting for changing the default file manager, but until then, this is one of the reasons why the setting is still experimental.
