### ISSUE TITLE
Desktop folders not opening via Files.

### ISSUE THREAD

**Issue by ShikhnadiDhokla** [files-community/Files#13035]
### Description

When I open folders in my desktop , they open via windows file explorer , rather than files.

(I already have selected the option to make files as my default file viewer. ) 

![image](https://github.com/files-community/Files/assets/105537985/48407d8d-0f95-4f24-a6a0-7ca7a71fea7e)

### Steps To Reproduce

Open folders in your desktop- like THIS PC

### Requirements

- e.g. Fix crash that occurs when...
Windows files explorer opens , instead of files.

### Files Version

2.5.21.0

### Windows Version

10.0.19045.3208

### Log File

[debug.log](https://github.com/files-community/Files/files/12136600/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report. Can you give the following information.
- Does open the file explorer program open Files?
- If not can you try turning the option off then on again.

**Comment by ShikhnadiDhokla** [comment]
Does opening the Windows File Explorer itself open Files?--- yes , positive, when i open the file explorer from my taskbar short cut, it will open up files .

**Comment by Notarin** [comment]
> "Does opening the Windows File Explorer itself open Files?"--- yes , positive, when I open the file explorer from my taskbar shortcut, it will open up files.

just for extra clarification, does Win + E do the same?

**Comment by ShikhnadiDhokla** [comment]
> > "Does opening the Windows File Explorer itself open Files?"--- yes , positive, when I open the file explorer from my taskbar shortcut, it will open up files.
> 
> just for extra clarification, does Win + E do the same?

yes, positive

**Comment by yaira2** [comment]
@ShikhnadiDhokla can you try following these steps to see if the issue is resolved?
1. Uninstall Files
2. Launch File Explorer using `win` + `e`, there should be a message that Files was removed and that the registry changes are being reverted
3. Install Files again and set it as the default

**Comment by yaira2** [comment]
@ShikhnadiDhokla when you try these steps, it might be a good idea to do them in the preview build https://files.community/download.
