### ISSUE TITLE
Start Pin

### ISSUE THREAD

**Issue by Stixz** [files-community/Files#13036]
### Description

When I pin an app to the start menu, it has a default icon of the app (Files). Am I missing something, can this be changed?

### Steps To Reproduce

Find an app not pinned to the start menu.
Right-click and go to more options.
Click the pin to start
Click yes
Look at the start, it now has the pin but with Files as the icon.

### Requirements

Correct a bug?

### Files Version

2.5.21.0

### Windows Version

10.0.23403.1001

### Log File

[debug.log](https://github.com/files-community/Files/files/12136658/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #12191. You can check there or click subscribe in the right sidebar for updates.
