### ISSUE TITLE
Feature: Switch git account and log out

### ISSUE THREAD

**Issue by ferrariofilippo** [files-community/Files#13049]
### What feature or improvement do you think would benefit Files?

At the moment you can't log out easily of git. You need to open Windows credential manager and then delete the token.
I think we can improve the UX of git adding a `git` section in the settings, where the user can manage the account they want to use  

### Requirements

- Add a `Git` section in settings
- Add a button to `Log out`
- Add a button to `Sign in`

### Files Version

2.5.21

### Windows Version

Windows 11Pro 10.0.22621.1992

**Comment by yaira2** [comment]
> Add a Git section in settings

Should this have a separate page?

> Add a button to Switch account

Can you be signed into multiple accounts at the same time?

**Comment by ferrariofilippo** [comment]
> > Add a Git section in settings
> 
> Should this have a separate page?

We should use either `Advanced` page  or a new one


> > Add a button to Switch account
> 
> Can you be signed into multiple accounts at the same time?

I guess we can do it. We might have a popup when there are two or more accounts

**Comment by mdtauk** [comment]
If you do add a Settings Page - I have made a Toggle Icon for it
![image](https://github.com/files-community/Files/assets/7389110/12d21ff4-4bf6-4836-a245-8b071ce320b2)

**Comment by yaira2** [comment]
@ferrariofilippo is "Switch account" the same as logging out?

**Comment by ferrariofilippo** [comment]
> @ferrariofilippo is "Switch account" the same as logging out?

Actually not but it may be confusing. I think it's better to simply log out.
