### ISSUE TITLE
PDF be vertical rather then horizontal scrolled in preview section

### ISSUE THREAD

**Issue by ShikhnadiDhokla** [files-community/Files#13044]
### What feature or improvement do you think would benefit Files?

1.) PDF  preview to be vertical  (PIC 2 )  rather then horizontal scrolled (PIC 1 )in preview section (PIC1 is current, PIC 2 is what we can have)

2.  ) Also increase the resolution of PDF preview.

**(PIC 1)**

![image](https://github.com/files-community/Files/assets/105537985/44aa23e6-846b-4311-8b0a-c7caee08a21f)

**(PIC 2)**

![image](https://github.com/files-community/Files/assets/105537985/ee7bc2d2-0f69-4f4c-9d1d-b4b1f54a419f)

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.5.21.0

### Windows Version

10.0.19045.3208

**Comment by yaira2** [comment]
> PDF preview to be vertical (PIC 2 ) rather then horizontal scrolled (PIC 1 )in preview section (PIC1 is current, PIC 2 is what we can have)

Thank you for your feedback, is vertical better than horizontal for your use case or is this just because File Explorer has it like this?

**Comment by ShikhnadiDhokla** [comment]
vertical allows for better reading experience . It feels like a continues reading flow as I can r**ead continuously and scroll up and down between pages.** This makes it more continuous and maintains the flow.

In horizontal I only have one page and have to scroll  to read more which is **not continuous and breaks continuity**, when reading a big document.

**Comment by mdtauk** [comment]
> > PDF preview to be vertical (PIC 2 ) rather then horizontal scrolled (PIC 1 )in preview section (PIC1 is current, PIC 2 is what we can have)
> 
> Thank you for your feedback, is vertical better than horizontal for your use case or is this just because File Explorer has it like this?

I would say so yes - however, how well this works with a landscape PDF is less good.

Would it make sense to use Pagination controls, instead of a scrolling list?

![image](https://github.com/files-community/Files/assets/7389110/2e67625a-6fc2-495b-95e5-44febcf9bdd1)

![image](https://github.com/files-community/Files/assets/7389110/7644acb0-139b-484b-b328-8351baea20cb)

**Comment by mdtauk** [comment]
We could have borders show up top or bottom as your scroll to hide the cut off
![image](https://github.com/files-community/Files/assets/7389110/44a0aa06-43a6-4758-9e58-95a5bfdc52f2)

**Comment by Lukiluc29** [comment]
> We could have borders show up top or bottom as your scroll to hide the cut off ![image](https://user-images.githubusercontent.com/7389110/256195274-44a0aa06-43a6-4758-9e58-95a5bfdc52f2.png)

I find that both concepts are very beautiful but personally I prefer the first.

**Comment by mdtauk** [comment]
> I find that both concepts are very beautiful but personally I prefer the first.
>
If by the first you mean the first scrolling design?  Then it may not be possible to achieve the clean closing lines of the cut off items, and so we need to adjust the design.

**Comment by Lukiluc29** [comment]
> If by the first you mean the first scrolling design? Then it may not be possible to achieve the clean closing lines of the cut off items, and so we need to adjust the design.

Yes, I'm talking about the first design without the closing lines. I prefer this design because the other disturbs me a little with the lines that protrude on the side. After all, that's just my opinion.

**Comment by mdtauk** [comment]
This is how it would look without the lines
![image](https://github.com/files-community/Files/assets/7389110/3fa5a5a8-e5cb-43fd-bfa7-5b7983085451)

**Comment by Lukiluc29** [comment]
I like both of them there: (but I still prefer the one without the lines)
![256488176-3fa5a5a8-e5cb-43fd-bfa7-5b7983085451](https://github.com/files-community/Files/assets/128183422/01740f04-bb82-40c4-a3a3-fbff58d232e3)
![255720572-7644acb0-139b-484b-b328-8351baea20cb](https://github.com/files-community/Files/assets/128183422/8915a834-7cc1-4f8a-8634-03ee89d337fa)

**Comment by mdtauk** [comment]
> I like both of them there: (but I still prefer the one without the lines) ![256488176-3fa5a5a8-e5cb-43fd-bfa7-5b7983085451](https://user-images.githubusercontent.com/128183422/256491715-01740f04-bb82-40c4-a3a3-fbff58d232e3.png) ![255720572-7644acb0-139b-484b-b328-8351baea20cb](https://user-images.githubusercontent.com/128183422/256491719-8915a834-7cc1-4f8a-8634-03ee89d337fa.png)

As do I, but I am not sure it is achievable, especially when you get to the end of an item as it goes out of view

**Comment by Lukiluc29** [comment]
> As do I, but I am not sure it is achievable, especially when you get to the end of an item as it goes out of view

There may be workarounds to have this design and that we can navigate the document without having any worries.

**Comment by yaira2** [comment]
This feature is implemented in `main` and will be included in the next release.
