### ISSUE TITLE
Bug: Unpinning a pinned favorite crashes the app

### ISSUE THREAD

**Issue by LexaWitch** [files-community/Files#13042]
### Description

Unpinning any default pin will crash Files

### Steps To Reproduce

Install Files
Run Files
Unpin anything that was pinned by default
Files will crash.

### Requirements

Fix the crash

### Files Version

2.5.20.0

### Windows Version

Windows 11 Home 22H2 22621.1992

### Log File

[debug.log](https://github.com/files-community/Files/files/12137442/debug.log)

**Comment by yaira2** [comment]
Thank you for reporting this issue.

**Comment by hishitetsu** [comment]
I'll work on this.
