### ISSUE TITLE
Cannot unpin from favourites - but get missing folder message

### ISSUE THREAD

**Issue by fredphoesh** [files-community/Files#13057]
### Description

See the pic, every time I start Files, I get this error message, it probably pertains to the O drive which is an external USB drive which is usually OFF. 

I have used the RH menu button in Files to choose to Remove From Favourites, so I no longer get this message, but Remove From Favourites does not work with a drive that is not mounted... yet it assumes that when the drive is OFF, that it has been deleted. I don't know if this is a bug or a need for a feature request, but needed to be reported. 
![files-deleted-folder-mystery](https://github.com/files-community/Files/assets/5565996/bd9bce84-8c81-47bc-9967-54021e58fa7c)

Thanks,
Mark.

### Steps To Reproduce

add a USB drive to favourites
eject USB drive
reboot system.

### Requirements

1/ be able to remove unmounted drives from favourites
2/ be able to have unmounted drives in favourites without getting an error message about it being deleted.

### Files Version

2.5.21.0

### Windows Version

10.0.22631.2050

### Log File

[debug.log](https://github.com/files-community/Files/files/12147642/debug.log)

**Comment by yaira2** [comment]
Thank you for reporting this issue, this issue is resolved in our dev branch and will be included in the next release.

**Comment by hishitetsu** [comment]
@yaira2 Do you say about #13042? This seems another issue.

**Comment by yaira2** [comment]
I think it's the same, in both cases it's where the folder cannot be located.

**Comment by hishitetsu** [comment]
How about this?

> 2/ be able to have unmounted drives in favourites without getting an error message about it being deleted.

**Comment by yaira2** [comment]
That part wasn't resolved 👍
