### ISSUE TITLE
Feature: Display keyboard shortcuts in the right click menu

### ISSUE THREAD

**Issue by StanFromTraction** [files-community/Files#13055]
### What feature or improvement do you think would benefit Files?

Over the years I got used to do right-click>W>F to create a new folder for instance.

Win11 dropped those kb shortcuts (thanks MSFT), so the goal would be to equate Win10's.

### Requirements

- This proposal will accomplish having the same KB shortcuts in the cintextual menu as Win10 does

### Files Version

2.5.21.0

### Windows Version

10.0.22621.1926

**Comment by yaira2** [comment]
Thank you for your feedback, we already have the code for this in place so it's just a matter of identifying why it's not displaying them. My guess is that it's a bug in the CommandBarFlyout control but it's something to investigate.

**Comment by yaira2** [comment]
@zhuxb711 have you found a way to workaround this issue?

**Comment by zhuxb711** [comment]
Not sure what you are pointing at actually.
![image](https://github.com/files-community/Files/assets/42038175/1610f7e2-4749-4572-b107-1812343aacf0)

**Comment by yaira2** [comment]
@zhuxb711 my mistake, I thought we were already setting the shortcuts and that they weren't showing up.
