### ISSUE TITLE
App window should be brought to front when Files is used to open an archive

### ISSUE THREAD

**Issue by mon-jai** [files-community/Files#13056]
### What feature or improvement do you think would benefit Files?

When opening an archive with Files (like clicking on an archive in Chrome's downloads manager), Files' window should be brought to front, just like what happens when we open a file with other apps.

### Requirements

- When opening an archive with Files, Files' window should be brought to front

### Files Version

2.5.21.0

### Windows Version

10.0.22000.2176

**Comment by Josh65-2201** [comment]
Thanks for the feedback, I've added this to the project board.

**Comment by yaira2** [comment]
Thank you for your feedback, we're going to continue tracking this in #13064.
