### ISSUE TITLE
Feature: Shortcut for Pane Focus Toggle in Dual Pane Mode

### ISSUE THREAD

**Issue by Mthia727** [files-community/Files#13069]
### What feature or improvement do you think would benefit Files?

When using the dual pane mode, it would be beneficial to have a shortcut that allows users to easily toggle focus between the panes. Currently, the only way to switch focus is by repeatedly pressing the "Tab" key or "Shift + Tab" until it moves to the other pane. To enhance the user experience, a more efficient shortcut is suggested: "Shift + Arrow keys" (left / right) to quickly toggle focus between the panes.

### Requirements

- Add functionality to recognize the "Shift + Arrow keys" (left / right) combination in the dual pane mode.

### Files Version

2.5.21.0

### Windows Version

10.0.22621.1992

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by Mthia727** [comment]
There is already a shortcut for that. Ctrl + Shift + Arrow Keys
