### ISSUE TITLE
Bug: App crashes when opening Recycle Bin in the Columns Layout

### ISSUE THREAD

**Issue by guimaletta** [files-community/Files#13063]
### Description

If you set the program to go automatic to columns (Layout mode), when you open the recycle bin it crashes.

### Steps To Reproduce

1. Set layout mode to columns
2. Open Recycle Bin

### Requirements

Fiz crash that occurs when recycle bin is opened when the layout mode is set to columns

### Files Version

2.5.21.0

### Windows Version

10.0.19045.3208

### Log File

[debug.log](https://github.com/files-community/Files/files/12152750/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
@Josh65-2201 are you able to reproduce this issue?

**Comment by yaira2** [comment]
@guimaletta when you open Recycle Bin, are you opening it from the sidebar?

**Comment by Lukiluc29** [comment]
@yaira2 This issue has been previously reported #12664

**Comment by yaira2** [comment]
Merging with #12664
