### ISSUE TITLE
Feature: Bring the focus to the newly opened tab.

### ISSUE THREAD

**Issue by mvartuc** [files-community/Files#13064]
### What feature or improvement do you think would benefit Files?

Current behavior: 
1- I have a folder called 'A' on my desktop
2- I have a current Files instance with some tabs already open
3- When clicked on 'A', Files opens the folder in a new tab, without shifting the focus (bringing the window to the front)

Proposed behavior:
3-> When clicked on 'A', Files opens the folder in a new tab and immediately brings the windows to the front of everything else.

### Requirements

- This proposal will bring back the native feel and it'll improve user experience significantly

### Files Version

2.5.21.0

### Windows Version

10.0.19045.3208

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
Thank you for your feedback, we're currently tracking this issue in #10844. Please subscribe to that issue to be notified when it's resolved.

**Comment by yaira2** [comment]
This issue will be resolved with #13588.
