### ISSUE TITLE
App crush

### ISSUE THREAD

**Issue by KomiONE** [files-community/Files#13066]
### Description

My app suddenly crushed. After that it lunches again with all my open tabs. 
Sometimes heppen that my app crushes and than it won't open on it's own. i have to oppen it.

### Steps To Reproduce

1. App crushed
2. App reopen

1. App crushed
2. App didn't open

### Requirements

- e.g. Fix crash that occurs when I don't do anything.

### Files Version

2.5.21.0

### Windows Version

10.0.22621.1265

### Log File

[debug.log](https://github.com/files-community/Files/files/12162045/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, What were you doing when the app crashed?

**Comment by KomiONE** [comment]
I just wait to reload itself or if it can't reload itself I open the
browser myself. It's kinda annoying to be honest :/
It can happen xx times throughout the day :/

út 25. 7. 2023 v 16:04 odesílatel Josh65-2201 ***@***.***>
napsal:

**Comment by Josh65-2201** [comment]
So it happens if you open Files and wait on the home page only?

**Comment by KomiONE** [comment]
It happens to me when I work with few files, multiple tabs even if I only
have window open on background or minimized. From time to time the
application also report some problem, crashes and starts again. Sometimes
it reports an error and just shuts down. Then I have to launch it again and
reopen the closed tabs/files.

Dne út 25. 7. 2023 19:25 uživatel Josh65-2201 ***@***.***>
napsal:

**Comment by KomiONE** [comment]
Also when I want to export PDF file and I have open same folder where I
need it to export, it just report to me as error and I have to close that
folder to get out of that folder.

Dne st 26. 7. 2023 9:06 uživatel Ota Komárek ***@***.***> napsal:

**Comment by yaira2** [comment]
I see some exceptions in the log file related to the recent files widget.

**Comment by yaira2** [comment]
@KomiONE depending on what caused the crash, we don't always have a chance to save and restore the tabs. That said, we'd like to fix the underlying crash so if it happens again, make sure to open an issue and include the steps to reproduce the crash.

**Comment by KomiONE** [comment]
Well, I really don't know what I do wrong, because it can crash under high
processing activities or also out of nowhere. Just closes the app. Nowadays
it's doing that the app crashes and reboot with all the apps. This is
happening several times through the day. Also sometimes it just closes and
with that all of my open tabs.
I will send report file when it happens again.

Dne út 12. 9. 2023 23:21 uživatel Yair ***@***.***> napsal:

**Comment by KomiONE** [comment]
To me it' appear randomly. Sometimes it happens while copying files from
one folder to another folder, or if I want to coppy files from a zip file.
I use 7-zip.
Or sometimes it happens while I want to rename a folder or file. It just
crashes.

st 13. 9. 2023 v 15:46 odesílatel Yair ***@***.***> napsal:
