### ISSUE TITLE
Feature: Redesign Sidebar control

### ISSUE THREAD

**Issue by 0x5bfa** [files-community/Files#13067]
## Motivation and Context

The current sidebar control that is based on NavigationView so far is very good, but it is a little inconvenient to resize the pane, and there is a problem with the design of the items on the pane, so it became necessary to devise a whole new design and create a new control.
Unlike before, the new controls are custom controls using resource dictionaries, which is expected to improve the readability and maintainability of the codebase.

### Development & co-authors

- #13052
- @yaira2
- @mdtauk
- @chingucoding
- @0x5bfa 

# Specs

### Definition
```cs
[Microsoft.UI.Xaml.Markup.ContentProperty(Name="Content")]
public class SidebarView : Control
```

### Description
Handles Sidebar controls comprehensively.

### Status
- [x] Drafted
- [ ] Implemented

### Properties
Property name|Type|Description
---|---|---
HeaderItemsSource|object|Gets or sets the object that represents the sidebar items to be used in the header menu.<br/>Normally, this type is IList\<SidebarViewItemBase\>.
MenuItemsSource|object|Gets or sets the object that represents the sidebar items to be used in the main menu.<br/>Normally, this type is IList\<SidebarViewItemBase\>.
FooterMenuItemsSource|object|Gets or sets the object that represents the sidebar items to be used in the footer menu.<br/>Normally, this type is IList\<SidebarViewItemBase\>.
DisplayMode|SideBarDisplayMode|Gets a value that specifies how the pane and content areas of a SidebarView are being shown.
Content|object|Main file list content.
Header|object|Hold TabView and Addressbar.
IsPaneOpen|bool|Is SidebarSplitView's pane open.
SelectedItem|SidebarViewItemBase|Represents an item selected.
CompactPaneLength|double|Gets or sets the length of the pane in compact mode.
OpenPaneLength|double|Gets or sets the length of the pane in expanded mode (when pane is opened).

### Pseudo code template (not actual usage)
```xaml
<Grid>

    <ContentPresenter Grid.Row="0" Content="{TemplateBinding Header}" />

    <SidebarSplitView
        Grid.Row="1"
        DisplayMode="{TemplateBinding DisplayMode}"
        IsPaneOpen="{TemplateBinding IsPaneOpen}"
        CompactPaneLength="{TemplateBinding CompactPaneLength}"
        OpenPaneLength="{TemplateBinding OpenPaneLength}">

        <SidebarSplitView.Pane>

            <ItemsRepeater Grid.Row="0" ItemsSource="{TemplateBinding HeaderItemsSource}" />

            <ItemsRepeaterScrollHost Grid.Row="1">
                <ScrollViewer>
                    <ItemsRepeater ItemsSource="{TemplateBinding MenuItemsSource}" />
                </ScrollViewer>
            </ItemsRepeaterScrollHost>

            <NavigationViewItemSeparator Grid.Row="2" />

            <ItemsRepeater Grid.Row="3" ItemsSource="{TemplateBinding FooterMenuItemsSource}" />

        </SidebarSplitView.Pane>

        <SidebarSplitView.Content>
            <ContentPresenter Content="{TemplateBinding Content}" />
        <SidebarSplitView.Content>
    </SidebarSplitView>
<Grid/>
```

### Remarks
- The pane toggle button must be implemented in AddressBar.

### Definition
```cs
[Microsoft.UI.Xaml.Markup.ContentProperty(Name="Content")]
public class SidebarSplitView : Control
```

### Description
Implements pane collapse, expanded, and overlay(minimal) modes.

### Status
- [x] Drafted
- [ ] Implemented

### Properties
Property name|Type|Description
---|---|---
DisplayMode|SideBarDisplayMode|Define display mode.
Pane|object|Gets or sets the pane content.
Content|object|Gets or sets the main content. This would display the storage item list view.
CompactPaneLength|double|Gets or sets the length of the pane in compact mode.
OpenPaneLength|double|Gets or sets the length of the pane in expanded mode (when pane is opened).

### Pseudo code template (not actual usage)
```xaml
<Grid>

    <Grid>
        <ContentPresenter Content="{TemplateBinding Pane}" />
    </Grid>

    <Grid Grid.Row="1">

        <ContentPresenter Content="{TemplateBinding Content}" />

        <!--  Light Dismiss  -->
        <Rectangle />

    </Grid>

<Grid/>
```

### Definition
```cs
public class SidebarViewItemBase : ContentControl
```

### Description
Represents base item class for SidebarViewItem, SidebarViewHeader, and SidebarViewSeparator.

### Status
- [x] Drafted
- [ ] Implemented

### Properties
Property name|Type|Description
---|---|---
IsSelected|bool|Gets or sets the value that indicates whether an item item is selected.<br/>Selection indicator will be shown.<br/>Header item should not be selectable when pane is in expanded mode, while it should be selectable in compact mode.
IsHeader|bool|Gets or sets the value that indicates whether an item is header.<br/>Chevron will be displayed in the right side.<br/>The content foreground will be secondary brush.<br/>The content font weight will be SemiBold.<br/>The icon will be hidden.

### Definition
```cs
public class SidebarViewItem : SidebarViewItemBase
```

### Description
Implemnts an item of the Sidebar and handles item slelection.

### Properties
Property name|Type|Description
---|---|---
IsSelected|bool|Gets or sets the value that indicates whether an item is selected.<br/>selection indicator will be shown.
IsPinned|bool|Gets or sets the value that indicates whether an item is pinned.<br/>Pin glyph will be shown in the right side.
IsCompacted|bool|Gets or sets the value that indicates whether an item's icon only should be displayed. <br/>Flyout will be shown when clicked an item.
Icon|IconElement|Gets or sets the icon to show the left side of the item text. OpacityIcon cannot be used.
Content|object|Main content. Usually this will be a string text.

### Remarks
- TODO: Reorder implementation.
- TODO: Drag & Drop implementation.

### Pseudo code template (not actual usage)
```xaml
<Grid>

    <ContentPresenter Grid.Row="0" Content="{TemplateBinding Icon}" />

    <ContentPresenter Grid.Row="1" Content="{TemplateBinding Content}" />
    <FontIcon Grid.Row="1" Glyph="{StaticResource SidebarViewItemPinGlyph}" Visibility="Collapsed" />

<Grid/>
```

### Definition
```cs
public class SidebarViewItemHeader : SidebarViewItemBase
```

### Description
Implemnts an header of the Sidebar. Handle item collase/expand children.

### Status
- [x] Drafted
- [ ] Implemented

### Properties
Property name|Type|Description
---|---|---
Content|object|Main content. Usually this will be a string text.
IsCompacted|bool|Gets or sets the value that indicates whether the item's icon only should be displayed. Flyout will be shown when clicked an item.
IsExpanded|bool|Gets or sets the value that indicates whether children should be shown.

### Pseudo code template (not actual usage)
```xaml
<Grid>

    <ContentPresenter Grid.Column="0" Content="{TemplateBinding Content}" />

    <FontIcon Grid.Column="1" Glyph="{StaticResource SidebarItemHeaderChevronDownGlyph}" />

<Grid/>
```

### Definition
```cs
public class SidebarViewItemSeparator : SidebarViewItemBase
```

### Description
Implemnts separator between the main pane content and footer content.

### Status
- [x] Drafted
- [ ] Implemented

### Properties
*None*

### Pseudo code template (Not actual usage)
```xaml
<Grid>
    <Rectangle Fill="{ThemeResource SidebarViewItemSeparatorForeground}" />
</Grid>
```

### Definition
```cs
public sealed partial class Sidebar : SidebarView
```

### Status
- [x] Drafted
- [ ] Implemented

### Properties
Property name|Type|Description
---|---|---
ViewModel|SidebarViewModel|Get the ViewModel of the Sidebar.

### Pseudo code (not actual usage)
```xaml
<SidebarView
    x:Class="Files.App.UserControls.Sidebar"
    DataContext="{x:Bind ViewModel, Mode=OneWay}"
    ItemsSource="{x:Bind ViewModel.Items, Mode=OneWay}">

    <FlyoutBase.AttachedFlyout>
        <MenuFlyout x:Name="SidebarRootContextMenu" />
    </FlyoutBase.AttachedFlyout>

    <SidebarView.Resources>
        <ResourceDictionary /> <!--  DataTemplates  -->
    <SidebarView.Resources>

    <SidebarView.MenuItemTemplateSelector>
        <templateselectors:SidebarItemTemplateSelector />
    </SidebarView.MenuItemTemplateSelector>

</SidebarView>
```

### Sample actual usage in MainPage
```xaml
<Sidebar>
    <Sidebar.Header>
        <Grid>
            <Grid.RowDefinitions>
                <RowDefinition Height="Auto" />
                <RowDefinition Height="Auto" />
            </Grid.RowDefinitions>

            <TabView Grid.Row="0" />
            <AddressBar Grid.Row="1" />

        </Grid>
    </Sidebar.Header>

    <InnerNavigationBar />
    <ContentPresenter />
</Sidebar>
```

### Definition
```cs
public enum SidebarDisplayMode
```

### Description
Defines constants that specify how the pane is shown in a SidebarView.

### Status
- [x] Drafted
- [ ] Implemented

### Fields
Field name|Value|Description
---|---|---
Compact|0|The pane always shows as a narrow sliver which can be opened to full width.
Expanded|1|The pane stays open alongside the content.
Minimal|2|Only the toggle button remains fixed. The pane shows and hides as needed.

# Concepts

made by @mdtauk

**Overlay mode**
![image](https://github.com/files-community/Files/assets/62196528/f634889e-01b3-4937-b9c4-70ffb3414502)

**Divider and footer items**
![image](https://github.com/files-community/Files/assets/62196528/3d9a1a6c-212c-44ab-aa8b-d83b56a97722)

**Visual states of SidebarItem 1**
![image](https://github.com/files-community/Files/assets/62196528/df3d267a-0a5b-454b-b659-a331689686bc)

**Visual states of SidebarItem 2**
![image](https://github.com/files-community/Files/assets/62196528/4c2349fc-1c7c-4756-b59d-33e5a19cc6e6)

**Comparison among Collapsed, Expanded, and Overlay**
![image](https://github.com/files-community/Files/assets/62196528/4dde4ee9-759d-420f-9749-28af7eb3b236)

**Comparison between Dark and Light theme**
![image](https://cdn.discordapp.com/attachments/1067978814904340641/1133603765296037938/image.png)
![image](https://cdn.discordapp.com/attachments/1067978814904340641/1133603765937770496/image.png)

**Comment by 0x5bfa** [comment]
---

**Rough spec text**

### Visual States

#### SidebarNavigation

**LAYOUTGROUP**

- Expanded
- Compacted
- Overlay

#### SidebarNavigationItem

**STATEGROUP**

- Normal
- PointerOver
- Pressed
- Disabled
- Selected
- PointerOverSelected
- PressedSelected
- DisabledSelected

**LAYOUTGROUP**

- Expanded
- Compacted

**STATUSGROUP**

- Pinned
- Unpinned

**PRESENTERGROUP**

- Inline
- Flyout

#### SidebarNavigationGroup

**STATEGROUP**

- Normal
- PointerOver
- Pressed
- Disabled

**EXPANSIONGROUP**

- Opened
- Closed

**LAYOUTGROUP**

- Expanded
- Compacted

SidebarNavigation.BottomItems ---

**DIVIDERGROUP**

- DividerVisible
- DividerCollapsed

**LAYOUTGROUP**

- Expanded
- Compacted

### Template Parts + Properties

#### SidebarNavigationItem

- PART_Content (Label)
- PART_Icon (FontIcon, Icon, SymbolIcon, PathIcon, ThemedIcon, WinShellIcon, BitmapIcon, etc)
- PART_PinnedIndicatorIcon
- PART_SelectionIndicator
- PROP_IsEnabled
- PROP_IsPinned
- PROP_IsSelected
- PROP_Background
- PROP_Foreground
- PROP_IsCompact

#### SidebarNavigationGroup

- PART_Content (Label)
- PART_Icon (FontIcon, Icon, SymbolIcon, PathIcon, ThemedIcon, WinShellIcon, BitmapIcon, etc)
- PART_ExpansionIndicator (Chevron)
- PROP_IsEnabled
- PROP_IsOpened
- PROP_Background
- PROP_Foreground
- PROP_IsCompact (if IsCompact = True, then close and hide sub-items and use flyout instead)

#### SidebarCompactFlyout (this will present child SidebarNavigationItems in a flyout)

*None*

---

**Comment by 0x5bfa** [comment]
Please give me one more day to elaborate more! @chingucoding But you can adjustto some extent.

**Comment by yaira2** [comment]
> Header

What does this have to do with the sidebar control?

**Comment by 0x5bfa** [comment]
#13052

**Comment by mdtauk** [comment]
We would also want a top item area, the main item area, and a bottom item area.  Binding to a singular items source is not ideal.

Not sure we need to have a separate Header item, as with the WIP version, the Sidebar Items can have children, which determines if it follows the header styling or not.

We don't need to use Menu items, when the Sidebar items are enough.

Also be incorporating the Address Bar and the Tab Bar - this is becoming a Shell page, and not a control that is also usable for Properties and Settings dialogs.

We would need to be able to use our Opacity/Themed Icons which should have Normal, Selected, Disabled, and HighContrast states.

**Comment by 0x5bfa** [comment]
> a top item area

SidebarView.Header (to put tabview & addressbar)

> the main item area

SidebarView.MenuItemsSource

> a bottom item area

SidebarView.FooterMenuItemsSource

> Also be incorporating the Address Bar and the Tab Bar - this is becoming a Shell page, and not a control that is also usable for Properties and Settings dialogs.

I fixed samples

> We would need to be able to use our Opacity/Themed Icons which should have Normal, Selected, Disabled, and HighContrast states.

Then, we need icon property to be object, not IconElement.

**Comment by mdtauk** [comment]
> > a top item area
> 
> SidebarView.Header (to put tabview & addressbar)
>
I would like Tabs and Address Bar to be totally separate from the Sidebar control.

> 
> > the main item area
> 
> SidebarView.MenuItemsSource
> 
> > a bottom item area
> 
> SidebarView.FooterMenuItemsSource
> 
![image](https://github.com/files-community/Files/assets/7389110/618f1a29-c874-46ff-9026-f1d23c92bc60)



> > Also be incorporating the Address Bar and the Tab Bar - this is becoming a Shell page, and not a control that is also usable for Properties and Settings dialogs.
> 
> I fixed samples
> 


> > We would need to be able to use our Opacity/Themed Icons which should have Normal, Selected, Disabled, and HighContrast states.
> 
> Then, we need icon property to be object, not IconElement. Should I change?
I am not sure how Marcel is handling this, but this is a sore spot in the app for now.  Keeping the Icon as a content element will allow the most flexibility, but ideally we would have an Icon control, with the visual states, so the SidebarItem can set the state to match it's selected and pointer over states

**Comment by 0x5bfa** [comment]
> I would like Tabs and Address Bar to be totally separate from the Sidebar control.

I did so.

> [the image]

Doo you want to fix Home item? even if so, is that approved by @yaira2? otherwise, not need to be separated.

**Comment by mdtauk** [comment]
> > I would like Tabs and Address Bar to be totally separate from the Sidebar control.
> 
> I did so.
> 
> > [the image]
> 
> Doo you want to fix Home item? even if so, is that approved by @yaira2? otherwise, not need to be separated.

Home at the top always was the plan.  Other groups possibly customisable in settings

**Comment by 0x5bfa** [comment]
I didn't know that. Let me fix.

**Comment by 0x5bfa** [comment]
@chingucoding @mdtauk, all done. we can regard this as guideline..
