### ISSUE TITLE
Disable Dual Pane?

### ISSUE THREAD

**Issue by y0himba** [files-community/Files#13070]
### What feature or improvement do you think would benefit Files?

I am not finding a way to disable the right hand widget pane with drives and tags in it.  I'd like to open a single directory.

### Requirements

On smaller resolutions (1080p) this will show less clutter, and for me at least it's faster to use a single pane with tabs. The pane should be optional please?

### Files Version

2.5.21.0

### Windows Version

10.0.22621.1992

### Comments

Just an option to disable this behavior would be nice.

**Comment by Josh65-2201** [comment]
The close pane option is in the `...` menu on the toolbar
![image](https://github.com/files-community/Files/assets/26977075/afeeaf14-5812-4576-8ce3-566d3ffc9d07)

**Comment by y0himba** [comment]
Oh holy crap.  I blame being old.  Thank you VERY much.
