### ISSUE TITLE
Open Command Prompt Here

### ISSUE THREAD

**Issue by y0himba** [files-community/Files#13071]
### What feature or improvement do you think would benefit Files?

It's hard trying to open a command prompt from the right click menu in a full folder. Currently I need to right click a folder, show more options, open command prompt, then cd .. to the directory I want to be in.

Under settings-->context menu options can we add "show open command prompt here", or place a small icon to open a command prompt at the top of the right click menu where the cut, copy, paste, rename, share and delete icons are?

### Requirements

Under settings-->context menu options can we add "show open command prompt here". 
Place a small icon to open a command prompt at the top of the right click menu where the cut, copy, paste, rename, share and delete icons are.

Both will allow easier access to a command prompt.

### Files Version

2.5.21.0

### Windows Version

10.0.22621.1992

### Comments

Thank you

**Comment by Josh65-2201** [comment]
This might be better as a toolbar option but Terminal will probably be used with it since it more universal as it can open and run any command line environment and installed by default. For now you can use the space in between the size column and preview pane.

**Comment by Mthia727** [comment]
If you want to open a command prompt in your current folder, you can type "cmd" into search bar, it will open a cmd in your current path.

**Comment by yaira2** [comment]
![image](https://github.com/files-community/Files/assets/39923744/2c98d129-d20c-47dc-9f2d-c9be0c244f07)
@y0himba even better than the context menu, you can use these keyboard shortcuts to launch Windows Terminal.

**Comment by TheWonderfulTartiflette** [comment]
> Thanks for the feedback, there already is the `Open in Terminal` option which open at the right clicked directory. If you don't want it in a show more menu you can disable it in Files settings > General > Move shell extensions into a sub menu. You can also click anywhere in the blank spaces to not have to do `cd ..`

To be honest, I don't see this option, has this been removed or something ?
![image](https://github.com/user-attachments/assets/dde84f12-920d-4c09-8b4c-1d9636031e41)

**Comment by Josh65-2201** [comment]
It's controlled by Windows Terminal, why it doesn't show for some people we don't know but you can use the shortcuts Yair showed above
