### ISSUE TITLE
Bug: Divider color is red in High Contrast

### ISSUE THREAD

**Issue by 0x5bfa** [files-community/Files#13077]
### Description

As the title

![image](https://github.com/files-community/Files/assets/62196528/4fce6f07-34ff-4bb6-a58f-808b97745bc9)

### Steps To Reproduce

1. Make Windows HC
2. Open Files

### Requirements

- Fix divider brushes

### Files Version

2.5.20

### Windows Version

10.0.22000

### Log File

*None*

**Comment by Jay-o-Way** [comment]
Could it be `ControlStrokeColorDefault`?

**Comment by yaira2** [comment]
@0x5bfa I have a fix for this but I'm waiting for the sidebar control to be merged before opening a PR.

**Comment by yaira2** [comment]
> Could it be `ControlStrokeColorDefault`?

That's good for light mode and high contrast, but it doesn't work in dark mode so we'll have to create something custom.

**Comment by 0x5bfa** [comment]
This is what I think and I replaced them with DoviderStrokeBrushDefault

**Comment by yaira2** [comment]
@0x5bfa how does that look in dark mode?

**Comment by yaira2** [comment]
@0x5bfa is this still an issue in `main`?
