### ISSUE TITLE
Feature: Request for Distinct Editability Indicators in "Details" Category of Properties Window

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#13073]
### What feature or improvement do you think would benefit Files?

I have a feature request regarding the Details page in the properties. Currently, we can click on each line, but we can't modify them. I propose that lines which should not be edited be treated similarly to the "More Details" section in the properties page, making them non-modifiable. On the other hand, lines like "Title," "Subject," or "Comment" should remain editable.

### Requirements

Implement a differentiation between non-modifiable lines and those that should remain editable, as suggested.

### Files Version

2.5.21.0

### Windows Version

22H2 22621.1992

**Comment by mdtauk** [comment]
I don't think any of the fields in the Details pane should be editable.  Doing it through the Properties dialog, allows the user to close the dialog to back out of any changes they may have made.

**Comment by Lukiluc29** [comment]
> I don't think any of the fields in the Details pane should be editable. Doing it through the Properties dialog, allows the user to close the dialog to back out of any changes they may have made.

I believe I didn't express myself clearly. I would like some fields in the "Details" category of the properties window to be non-clickable, while others remain editable. Let me explain further; essentially, I want the fields that cannot be modified to appear like the fields in the "More Details" category on the "General" page of the properties, which are non-editable and have no aura around them. Meanwhile, the editable fields should remain as they are.

**Comment by Lukiluc29** [comment]
This may help people distinguish fields that are editable from those that are not.

**Comment by mdtauk** [comment]
> > I don't think any of the fields in the Details pane should be editable. Doing it through the Properties dialog, allows the user to close the dialog to back out of any changes they may have made.
> 
> I believe I didn't express myself clearly. I would like some fields in the "Details" category of the properties window to be non-clickable, while others remain editable. Let me explain further; essentially, I want the fields that cannot be modified to appear like the fields in the "More Details" category on the "General" page of the properties, which are non-editable and have no aura around them. Meanwhile, the editable fields should remain as they are.

Ah ok in the Properties Dialog.  I agree, read-only fields should not use the TextBox on Hover.

**Comment by yaira2** [comment]
I'd argue that it's best to have consistency between the items, that said, the hover background is different on the disabled items so it still indicates which properties can be edited.

**Comment by Lukiluc29** [comment]
Alternatively, I suggest that non-editable fields remain clickable, but without displaying a border when hovered over. On the other hand, editable fields should have a border that appears when hovered over.
