### ISSUE TITLE
Bug: Backplates will be displayed when hovering in High Contrast

### ISSUE THREAD

**Issue by 0x5bfa** [files-community/Files#13078]
### Description

As the title

![image](https://github.com/files-community/Files/assets/62196528/0d10297d-0305-4c72-9156-91a77055eb85)

### Steps To Reproduce

1. Make Windows HC
2. Open Files
3. Hover something that have TextBlock.

### Requirements

- Remove backplates

### Files Version

2.5.20

### Windows Version

10.0.22000

### Log File

*None*

**Comment by yaira2** [comment]
Is this only on the sidebar and details layout?

**Comment by mdtauk** [comment]
> Is this only on the sidebar and details layout?

This is what ``UIElement.HighContrastAdjustment``  will handle

https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.highcontrastadjustment?view=winrt-22621

**Comment by 0x5bfa** [comment]
So all controls using UIElement have this issue.

**Comment by yaira2** [comment]
Is this really an issue? Why isn't that property the default behavior?

**Comment by yaira2** [comment]
@0x5bfa

**Comment by mdtauk** [comment]
> @0x5bfa

By default they want to prioritise the readability of text.  But because it is not visually appealing, they allow you to set the High Contrast Adjustment - to remove this behaviour | as long as the app developer has ensured the text contrast is readable.

If you want to remove the backplate, check every element to ensure text is always readable

**Comment by yaira2** [comment]
![image](https://github.com/files-community/Files/assets/39923744/58a35f8c-b162-4fcf-b091-3f9c7b97410f)
What's the expected design for this?

**Comment by yaira2** [comment]
So is the expected design to have black text without a backplate?

**Comment by mdtauk** [comment]
> So is the expected design to have black text without a backplate?

Anything highlighted, needs the correct text colour.

**Comment by yaira2** [comment]
There appears to be an issue where setting the property in app.xaml doesn't work. We can work around by setting it on the individual page, but we'd prefer to avoid doing this.

**Comment by 0x5bfa** [comment]
> There appears to be an issue where setting the property in app.xaml doesn't work. We can work around by setting it on the individual page, but we'd prefer to avoid doing this.

I should work though, [when I tried last time I worked well](https://github.com/files-community/Files/pull/13054/files#diff-dc0184eeec8db43468bd55586c4362feb47f4fa7a2af809f828f42c5cb1eeb5aL2). But Dialog class and MenuFlyout class doesn't respect this setting in App.xaml so need to set indivisually or we can find another way if any.

**Comment by yaira2** [comment]
@0x5bfa it's not too bad if it's just dialogs and menu flyouts. Let's do this 👍

**Comment by 0x5bfa** [comment]
Alright!

**Comment by yaira2** [comment]
This should be resolved in `main`.
