### ISSUE TITLE
Can't open the software

### ISSUE THREAD

**Issue by cynide00** [files-community/Files#13083]
### Description

Nothing happens after clicking the icon. There was no problem with the previous version.

### Steps To Reproduce

clicking the icon.

### Requirements

make the software run

### Files Version

2.5.21.0

### Windows Version

23493.1000 arm64

### Log File

I can't provide logs due to this issue

**Comment by Josh65-2201** [comment]
Thanks for the report. Can you upload the log file by navigating to 
`%localappdata%\Packages\<Look for a folder with Files>\LocalState`

**Comment by cynide00** [comment]
> Thanks for the report. Can you upload the log file by navigating to `%localappdata%\Packages\<Look for a folder with Files>\LocalState`

Sorry，i can't find any log files in this folder, It's like the software has never been opened.

**Comment by Josh65-2201** [comment]
Can you see if there an error in event viewer. You can see it by clicking on Files then typing Event view in the Windows search bar > Windows logs > Application > Look for and error event related to Files

**Comment by yaira2** [comment]
@cynide00
