### ISSUE TITLE
Bug: Missing "Start in" label in the shortcut properties

### ISSUE THREAD

**Issue by LucasOe** [files-community/Files#13081]
### Description

When inspecting the properties of a file shortcut there is a text field below arguments for the "Start in" property without a label next to it. In the default Windows Explorer this property is called "Start in" and lets users select the directory in which a shortcut is executed.

The text field "C:\Users\lucas\Desktop" doesn't have any description:
![image](https://github.com/files-community/Files/assets/16548335/c09be518-d445-4259-b092-ee6af42222c5)

### Steps To Reproduce

1. Open the properties for an shortcut to an executable using the context menu or through the quick actions at the top.
2. Navigate to the "Shortcut" options on the left menu.
3. The text field below "Arguments" doesn't have a label.

### Requirements

The "Start in" property should be properly labeled. An option without any description can be unintuitive for users.

### Files Version

2.5.21.0

### Windows Version

22H2 Build 19045.3208

### Log File

[debug.log](https://github.com/files-community/Files/files/12176257/debug.log)

**Comment by yaira2** [comment]
Thank you for reporting this bug.

**Comment by romw314** [comment]
I don't know where is the bug but these lines are important:
- https://github.com/files-community/Files/blob/7de0fa4786e1b445fde661a597532e61b5308a5b/src/Files.App/Views/Properties/ShortcutPage.xaml#L64-L70
- https://github.com/files-community/Files/blob/7de0fa4786e1b445fde661a597532e61b5308a5b/src/Files.App/Strings/en-US/Resources.resw#L531-L533

**Comment by Jay-o-Way** [comment]
I still don't understand why `x:uid=` isn't being used...

**Comment by yaira2** [comment]
@Jay-o-Way x:Uid isn't very readable.

**Comment by yaira2** [comment]
This issue is resolved in `main`.
