### ISSUE TITLE
Add the option to paste files or directories in the clipboard as a shortcut

### ISSUE THREAD

**Issue by LucasOe** [files-community/Files#13082]
### What feature or improvement do you think would benefit Files?

In the Windows Explorer, users have to option to paste files or folders as shortcuts using the right click context menu. I think a similar option would be useful to have inside of Files.

### Requirements

- Add a "Paste shortcut" option to the context menu for files and folders in the clipboard

### Files Version

2.5.21.0

### Windows Version

22H2 Build 19045.3208

### Comments

![image](https://github.com/files-community/Files/assets/16548335/a1382949-d473-4e79-a20c-05f3bc7c3f83)

**Comment by yaira2** [comment]
Thank you for your feedback, we're currently tracking this request in #8705.
