### ISSUE TITLE
Unable to select files through the "Create a new shortcut" dialogue

### ISSUE THREAD

**Issue by LucasOe** [files-community/Files#13080]
### Description

When trying to create a new shortcut to a file using the "New" -> "Create a new shortcut" dialogue, I am unable to select a file through the explorer as the shortcut target, despite the description saying "Create shortcuts to local network programs, **files**, folders, computers or Internet addresses".

I categorized this issue as a Bug because the description makes it sound like selecting files should be something a possibility.

### Steps To Reproduce

1. Create a new Shortcut using the top bar or the right click context menu.
2. Click on "Browse" and navigate to the file you want to create a shortcut for.
3. Users are only able to select a folder, and not a single file in the explorer.

### Requirements

Allow users to select local network programs, files, folders, computers and Internet addresses as the dialogue textbox says.

### Files Version

2.5.21.0

### Windows Version

22H2 Build 19045.3208

### Log File

[debug.log](https://github.com/files-community/Files/files/12176192/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
@LucasOe does entering the path manually work?

**Comment by LucasOe** [comment]
Manually entering the path does work as intended. I was thinking there might be a flag for changing the behavior of the file explorer when invoking it.

**Comment by yaira2** [comment]
There isn't a flag that allows picking files & folders from the same picker, but perhaps we can have a combo box to let users choose between files and folders.

**Comment by yaira2** [comment]
@LucasOe there isn't a flag that allows both, but I just checked File Explorer and they have the same behavior. My recommendation is to use picker to locate the folder, and to manually enter that item name at the end of the path.
