### ISSUE TITLE
Erro on one drive

### ISSUE THREAD

**Issue by ArturoVela** [files-community/Files#13088]
### Description

Good, I do not know if anyone else uses or has onedrive, but in the normal file browser, when you have a file comes out with an icon when it is in the cloud and another when it is on the device, I do not know if it is a bug in "files" but those icons do not come out.

### Steps To Reproduce

When uploading files the icon does not appear
when it is on the device it does not come out either

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

2.5.21.0

### Windows Version

10.0.22621.1992

### Log File

I don't know what to put here

**Comment by Josh65-2201** [comment]
Thanks for the report. Sorry for the delayed response, Can you give the following information.
- Are you talking about the sync status icons?
- What layout are you using?

**Comment by yaira2** [comment]
@ArturoVela
