### ISSUE TITLE
Option in appearance tab to control the level of transparency

### ISSUE THREAD

**Issue by onlytanmoy** [files-community/Files#13099]
### What feature or improvement do you think would benefit Files?

Title of this request basically. At the moment I am using Acrylic which is ok but if you can add this option wherein I can drag a bar on the transparency slider to review and set it as per my preference that will be great.

### Requirements

- This proposal will accomplish setting the desired level of transparency in the app

### Files Version

2.5.21.0

### Windows Version

10.0.22621.1992

**Comment by Josh65-2201** [comment]
You can already do this in Files settings > Appearance > Background > Click checker box > Change the A value
![image](https://github.com/files-community/Files/assets/26977075/72776eb0-be23-4d3a-915d-619e78e3e942)

**Comment by onlytanmoy** [comment]
@Josh65-2201 thanks for the clarification along with the supporting screenshot.

QQ- I have set Files as my default file manager app. In my browser Chrome when I go to Downloads i.e., chrome://downloads/ and against any downloaded files when I click on 'Show in folder' then it opens the downloads folder as a new tab in Files in a **minimized** state, any way to have Files pop up instead?

**Comment by Josh65-2201** [comment]
Not yet but it being tracked here #13064

**Comment by onlytanmoy** [comment]
Nice, thank you :)
