### ISSUE TITLE
Feature: Nilesoft Shell Extension

### ISSUE THREAD

**Issue by Vulcanraven91** [files-community/Files#13098]
### What feature or improvement do you think would benefit Files?

What feature or improvement do you think would benefit Files?

The current context menu in [Files Explorer](https://github.com/files-community/Files/) could be improved to provide a more powerful and customizable user experience. I propose to switch to the [Nilesoft Shell Extension](https://github.com/moudey/Shell) or at least provide users with the option to use either File Explorer's native context menu or the Nilesoft Shell Extension.

### Benefits
Nilesoft Shell Extension provides several benefits compared to the current context menu

- Customizable Context Menu: Users can handpick items to integrate into the context menu, create custom commands to access favorite web pages, files, folders, and launch any application directly from the context menu [github.com](https://github.com/moudey/Shell).

- Easy to Extend: Nilesoft Shell Extension makes it extremely easy to extend the context menu with new functions. Users can easily embed custom commands in the context menu, such as links to custom commands, files, folders, applications, and even websites [trishtech.com](https://www.trishtech.com/2022/02/nilesoft-shell-easy-context-menu-extender-for-windows/).

- User-friendly Configuration: Nilesoft Shell Extension comes with a configuration file (shell.shl) that can be easily edited to add or remove items from the context menu [trishtech.com](https://www.trishtech.com/2022/02/nilesoft-shell-easy-context-menu-extender-for-windows/). 

Why Use Shell [nilesoft.org/docs](https://nilesoft.org/docs)
> - Configuration in plain text.
> - Quick loading.
> - Minimal resource usage.
> - No limitations.
> - Embedded expressions syntax.
> - Built-in functions and predefined variables.
> - Multiple sources of images (embedded icons, image files, svg, glyphs, and colors).
> - Dynamic search and filter.
> - Support Taskbar context menu.
> - Full management of the context menu.

### Requirements

- [ ] Implement Nilesoft Shell Extension in Files Explorer.
- [ ] Provide an option for users to use either File Explorer's native context menu or Nilesoft Shell Extension.
- [ ] Allow users to customize the context menu items.
- [ ] Allow users to create custom commands in the context menu.
- [ ] Enable easy extension of the context menu with new functions.
- [ ] Include a user-friendly configuration file for adding or removing items from the context menu.
- [ ] Ensure compatibility with the current features of Files Explorer.

### Files Version

2.5.21.0

### Windows Version

10.0.22621.1848

### Comments

File-manage
<img src="https://github.com/moudey/Shell/blob/main/screenshots/file-manage.png?raw=true" width="50%" height="75%">

Taskbar:
<img src="https://github.com/moudey/Shell/blob/main/screenshots/taskbar.png?raw=true" width="50%" height="75%">

https://github.com/moudey/Shell/tree/main#screenshots

**Comment by Cambridgeport90** [comment]
That looks pretty cool, actually, and the way Files is written, I don’t see how we couldn’t have that,but the developers of the application would be better qualified to discuss that,probably.

From: Vulcanraven ***@***.***>
Sent: Friday, July 28, 2023 23:53
To: files-community/Files ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [files-community/Files] Nilesoft Shell Extension (Issue #13098)

What feature or improvement do you think would benefit Files?

What feature or improvement do you think would benefit Files?

The current context menu in Files Explorer<https://github.com/files-community/Files/> could be improved to provide a more powerful and customizable user experience. I propose to switch to the Nilesoft Shell Extension<https://github.com/moudey/Shell> or at least provide users with the option to use either File Explorer's native context menu or the Nilesoft Shell Extension.

Benefits

Nilesoft Shell Extension provides several benefits compared to the current context menu

  *   Customizable Context Menu: Users can handpick items to integrate into the context menu, create custom commands to access favorite web pages, files, folders, and launch any application directly from the context menu github.com<https://github.com/moudey/Shell>.
  *   Easy to Extend: Nilesoft Shell Extension makes it extremely easy to extend the context menu with new functions. Users can easily embed custom commands in the context menu, such as links to custom commands, files, folders, applications, and even websites trishtech.com<https://www.trishtech.com/2022/02/nilesoft-shell-easy-context-menu-extender-for-windows/>.
  *   User-friendly Configuration: Nilesoft Shell Extension comes with a configuration file (shell.shl) that can be easily edited to add or remove items from the context menu trishtech.com<https://www.trishtech.com/2022/02/nilesoft-shell-easy-context-menu-extender-for-windows/>.

Why Use Shell nilesoft.org/docs<https://nilesoft.org/docs>

  *   Configuration in plain text.
  *   Quick loading.
  *   Minimal resource usage.
  *   No limitations.
  *   Embedded expressions syntax.
  *   Built-in functions and predefined variables.
  *   Multiple sources of images (embedded icons, image files, svg, glyphs, and colors).
  *   Dynamic search and filter.
  *   Support Taskbar context menu.
  *   Full management of the context menu.

Requirements

  *   [ ] Implement Nilesoft Shell Extension in Files Explorer.
  *   [ ] Provide an option for users to use either File Explorer's native context menu or Nilesoft Shell Extension.
  *   [ ] Allow users to customize the context menu items.
  *   [ ] Allow users to create custom commands in the context menu.
  *   [ ] Enable easy extension of the context menu with new functions.
  *   [ ] Include a user-friendly configuration file for adding or removing items from the context menu.
  *   [ ] Ensure compatibility with the current features of Files Explorer.

Files Version

2.5.21.0

Windows Version

10.0.22621.1848

Comments

File-manage
[https://github.com/moudey/Shell/blob/main/screenshots/file-manage.png?raw=true]<https://github.com/moudey/Shell/blob/main/screenshots/file-manage.png?raw=true>

Taskbar:
[https://github.com/moudey/Shell/blob/main/screenshots/taskbar.png?raw=true]<https://github.com/moudey/Shell/blob/main/screenshots/taskbar.png?raw=true>

https://github.com/moudey/Shell/tree/main#screenshots

**Comment by yaira2** [comment]
Thank you for the feedback, Nilesoft is built primarily for File Explorer and they would have to do a lot of work on their end for it to work in Files. This is very applicable when it comes to options like changing the layout or toggling the rename action. If Nilesoft is interested in discussing this further, we'd be happy to chat with them and see if there is a way we can make this work but in the meantime, this isn't something either app supports.
