### ISSUE TITLE
Bug: Folders in tag section on home not localized to selected language

### ISSUE THREAD

**Issue by akschy** [files-community/Files#13093]
### Description

In the tags block of the home tag, the displayed folder name is the path name rather than the name defined in desktop.ini
![image](https://github.com/files-community/Files/assets/44605406/c5b4a1eb-570e-458b-baac-3f3296c4cc34)
![image](https://github.com/files-community/Files/assets/44605406/e913804f-0a30-41ac-a2c1-db208902b2cd)

### Steps To Reproduce

1. Set language to Chinese
2. The system default folder name will change to Chinese
3. Add tag to The system default folder
4. View the home tab, tags area

### Requirements

display match language with setting or Taking values from the configuration file

### Files Version

2.5.21.0

### Windows Version

windows 11  25915.1000

### Log File

no

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
This issue is fixed in the dev branch and will be included in the next release.
