### ISSUE TITLE
Bug: Error when creating new txt file

### ISSUE THREAD

**Issue by ArturoVela** [files-community/Files#13090]
### Description

When I create a new text document, it is always created in the download folder.

### Steps To Reproduce

1. Go to any folder
2. Add a text file using only the "New" button in the toolbar
3. Go to a second folder and repeat this operation

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

2.5.21.0

### Windows Version

10.0.22621.1992

### Log File

[debug.log](https://github.com/files-community/Files/files/12188662/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report.  Can you give the following information.
- Does File Explorer give any error message?
- Where are you trying to make the file?

**Comment by ArturoVela** [comment]
Here's a video, I think it's easier to understand.

https://github.com/files-community/Files/assets/116850718/31d8b628-e5dc-4bb1-bc57-e27203cb662b

**Comment by Lukiluc29** [comment]
> Does this only happen in the `d` drive?

I don't know because I can't test. However, I believe I've understood the error. When you create a text document in the "Document" folder, for example, and then you go to the "Music" folder, it will be created in the "Document" folder. To be clearer, when you create a text document in one folder, any other text documents you want to create in a different location will be created in the location where the first text document was created.

**Comment by yaira2** [comment]
Is this specific to the toolbar, or does it also affect the "new" option in the right click menu?

**Comment by yaira2** [comment]
@Lukiluc29

**Comment by Lukiluc29** [comment]
> @Lukiluc29

I just tested again in the latest version (2.5.30), and this issue still occurs.

**Comment by yaira2** [comment]
> Is this specific to the toolbar, or does it also affect the "new" option in the right click menu?

**Comment by Lukiluc29** [comment]
> > Is this specific to the toolbar, or does it also affect the "new" option in the right click menu?

Sorry, I mixed up the messages. When creating a text file through the context menu, the file is added correctly to the folder where I am.

**Comment by yaira2** [comment]
@Lukiluc29 can you share some updated repro steps and I'll add them to the description?

**Comment by Lukiluc29** [comment]
> @Lukiluc29pouvez-vous partager quelques étapes de reproduction mises à jour et je les ajouterai à la description ?

Of course, here they are:

1. Go to any folder
2. Add a text file using only the "New" button in the toolbar
3. Go to a second folder and repeat this operation

**Comment by yaira2** [comment]
Thank you
