### ISSUE TITLE
Add the option to view files and folders in different sections sorted by date

### ISSUE THREAD

**Issue by ArtexJay** [files-community/Files#131]
The downloads folder is an unorganized mess compared with what MS recently did to seperate it by days. If its possible could you do something similar?

**Comment by duke7553** [comment]
Thanks for the feedback. Since there seems to be some passionate people both for and against this feature, I'm going to mark this as a discussion.

**Comment by ArtexJay** [comment]
Or you could somehow make it so that it's an option that the user may either enable or disable. So those who want's it will get it but those who don't can still have it their way and turn it off.

I prefer it as it keeps the downloads folder very organized and makes it easier to find things that you have downloaded.

**Comment by yaichenbaum** [comment]
This is definitely something we should include as an option, it makes finding my downloads so much easier.

**Comment by yaichenbaum** [comment]
### **The plan is to accommodate all users**
In the future we will add an option in settings that will include this feature that users can be turned on or off.

**Comment by yaichenbaum** [comment]
Merging with #1874.

**Comment by yaira2** [comment]
@ArtexJay Support for grouping items by date is now available. You can download the latest version of Files from our website https://files.community/download
