### ISSUE TITLE
Bug: Files wont overwrite exported settings zip

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#13105]
### Description

*

### Steps To Reproduce

1. Export settings
2. Change a setting
3. Export settings over writing the first one
4. Import settings
5. See it using the first set of exported settings (Reverting the changed setting)

### Requirements

- Make sure zip file is overwritten with current settings

### Files Version

2.5.21.0

### Windows Version

10.0.22621.1992

### Log File

[debug.log](https://github.com/files-community/Files/files/12208915/debug.log)

**Comment by yaira2** [comment]
Thank you for reporting this issue

**Comment by yaira2** [comment]
This issue is fixed in the dev branch and will be included in the next release.
