### ISSUE TITLE
Slow start up

### ISSUE THREAD

**Issue by Mako5pwr** [files-community/Files#13106]
### Description

Files takes 5-8 seconds to start up, much slower than Explorer.  Any recommendations to improve start-up time?  

The system is a 2020 Razer Blade 15 Advanced w/ Intel Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz, RAM 32.0 GB (31.9 GB usable), SSD: Crucial CT4000P3SSD8 4TB PCIe 3.0.

### Steps To Reproduce

Double-click Files (on the Taskbar)

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

2.5.20

### Windows Version

Windows 11 Home Version 22H2, Build 22621.2070

### Log File

[debug.log](https://github.com/files-community/Files/files/12209364/debug.log)

**Comment by yaira2** [comment]
There aren't any solutions aside for leaving it open instead of closing it. That said, we're working on improving startup time with the biggest improvements coming once Microsoft solves some of the limitations in this area.

**Comment by yaira2** [comment]
We're excited to share that startup performance will be significantly improved in the upcoming release of version 3. You can download the preview version from our website https://files.community/download.
