### ISSUE TITLE
Add SharePoint sync directories

### ISSUE THREAD

**Issue by scottac30** [files-community/Files#1310]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
To add SharePoint sync directories like is available on the default explorer.

**Describe alternatives you've considered**
The alternative at the moment is to use the default Windows Explorer.

**Additional context**
Please find attached screenshot 

![Untitled](https://user-images.githubusercontent.com/56437496/86116335-262c9100-bac5-11ea-9def-cc1fce35f3ae.png)

**Comment by boscorelly** [comment]
hi,

i need this too, as we are using it too. It seems to be a great app, but the lack of this feature make it unusable for us :(

**Comment by yaichenbaum** [comment]
@scottac30 Thank you for opening this issue, can you check if SharePoint creates an environmental variable with the path?

**Comment by boscorelly** [comment]
@yair100 there is no env var for sharepoint.

maybe search for those informations in desktop.ini in the folder may help ?

[.ShellClassInfo]
IconResource=C:\Users\coe\AppData\Local\Microsoft\OneDrive\OneDrive.exe,2

**Comment by yaichenbaum** [comment]
@scottac30 This feature was implemented with #3572.
