### ISSUE TITLE
some request for visual designer 

### ISSUE THREAD

**Issue by lotusNoOne** [files-community/Files#13107]
### What feature or improvement do you think would benefit Files?

Found
https://www.aalab.com.cn/
A file manage app that have many feature for visual designer.

my request
- File batch naming function
- Same image detection, remove excess items
- Frame sequence merging display
- AI include

### Requirements

-

### Files Version

2.5.21.0

### Windows Version

10.0.22621.1992

### Comments

![image](https://github.com/files-community/Files/assets/7795183/1f9560f2-8ff3-4d14-a1b9-7226e0960fb6)

**Comment by Josh65-2201** [comment]
Thanks for the feedback. In future make a separate request for different feedback you have.

> File batch naming function

You can use Power Rename in Power Toys for this 

> Same image detection, remove excess items

Merging with #11385. You can check there or click subscribe in the right sidebar for updates.

> Frame sequence merging display

What do you mean by this?

> AI include

What do you mean by this?

**Comment by Josh65-2201** [comment]
@lotusNoOne Can you answer the above questions please
