### ISSUE TITLE
Bug: Can't save properties when adding comment

### ISSUE THREAD

**Issue by Henaneitor** [files-community/Files#13104]
### Description

When I go to add a comment to a file to be able to differentiate the different versions of the file, an error occurs in which it does not add the comment. The file is neither open nor in use, so I don't think it is a problem of the file being stuck.

![image](https://github.com/files-community/Files/assets/123067245/8cefe77f-bd49-4230-acaf-8020eab7733f)

### Steps To Reproduce

1. Go to the file and right click on "open properties".
2. Go to the details tab
3. Add the comment
4. Save the changes
5. Get the error

### Requirements

- e.g. Fix crash that occurs when the comment is added to the file and the file is saved

### Files Version

2.5.21.0

### Windows Version

10.0.22621.1992

### Log File

[debug.log](https://github.com/files-community/Files/files/12208900/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
@Henaneitor where is the item located? Does it work if you run Files as administrator?

**Comment by Lukiluc29** [comment]
> @Henaneitor where is the item located? Does it work if you run Files as administrator?

I have encountered this error before and I have performed some tests. Even as an administrator, this issue occurs. However, when I fill in the subject of an Office document (Word, PowerPoint, Excel...), this error doesn't occur. On the other hand, it still happens for other files.

**Comment by Qin-shihuang** [comment]
It seems that the "Title", "Author" and "Comment" properties are only valid for Office files(`.docx`,`.pptx`,`.xlsx` and other related types) and other file types do not have these properties. If you open an Office file as a compressed package, these properties are stored in the docProps/core.xml file.

**Comment by yaira2** [comment]
@Qin-shihuang have you been able to successfully write new properties to those file types? When I try on my side I run into this issue.

**Comment by Qin-shihuang** [comment]
@yaira2 Yes, I can modify these three properties (Title, Author, Comment) of such files, as long as they have been opened and written to by Office , thus having a complete structure. 
However, if it's a newly created file of size 0B or a corrupted file, then it will result in the same error.

**Comment by yaira2** [comment]
@Henaneitor can you check?
