### ISSUE TITLE
Change OneDrive Location

### ISSUE THREAD

**Issue by ericsingletary** [files-community/Files#13100]
### What feature or improvement do you think would benefit Files?

The OneDrive link in Files appears to be hard-coded to C:\users\%username%\OneDrive, but not everyone keeps their OneDrive folder in the default location.

I have yet to find a setting to change the location of my OneDrive folder in Files so the shortcut actually works when clicked.

### Requirements

Allow users to define their OneDrive location

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2070

**Comment by Josh65-2201** [comment]
Thanks for the feedback, This seem more like a bug as Files isn't hardcoding it. Can you delete the OneDrive folder in your user directory and restart Files.

**Comment by yaira2** [comment]
@ericsingletary can you check what you have set for the environmental variables in system settings?
