### ISSUE TITLE
Making the app minimize to tray when closing like ModernFlyouts or PowerToys.

### ISSUE THREAD

**Issue by Addster09** [files-community/Files#13103]
### What feature or improvement do you think would benefit Files?

I don't think this is a important feature or needed right now but I do recommend to add this as a quality of life or something so it opens instantly instead of showing the splash screen.

### Requirements

Making the app minimize to tray when closing like ModernFlyouts or PowerToys.

### Files Version

2.5.21.0

### Windows Version

10.0.19045.3271

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #11279. You can check there or click subscribe in the right sidebar for updates.
