### ISSUE TITLE
Feature: Automatically update date differences

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#13109]
### What feature or improvement do you think would benefit Files?

Currently, when a date is displayed by difference, its value is not updated unless the page is refreshed. Thus, creating a new file multiple times will all show "Now" or "1 second ago" even though they actually have different dates. If the date is displayed by difference, the value should be automatically updated.

### Requirements

If the date is displayed by difference, the value should be automatically updated.

### Files Version

2.5.21.0

### Windows Version

10.0.19045.3208

**Comment by yaira2** [comment]
Thank you for the feedback, I added this to the project board.
