### ISSUE TITLE
Bug: Cannot access taskbar when set to auto-hide 

### ISSUE THREAD

**Issue by retr0cube** [files-community/Files#13101]
### Description

For some reason when Files is in full screen I cannot access the Taskbar using the mouse, I can however access it with the "Win" key.

### Steps To Reproduce

1. Set taskbar to auto-hide in settings
2. Open Files
3. Try to access the Taskbar while it's hidden

### Requirements

- The ability to access the taskbar while it's set to auto-hide

https://github.com/files-community/Files/assets/61835816/c4964f07-5517-4264-a711-14008a8a1eea

### Files Version

2.5.21.0

### Windows Version

10.0.19041.1415

### Log File

[debug.log](https://github.com/files-community/Files/files/12207494/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #10767. You can check there or click subscribe in the right sidebar for updates.

This is currently block by WinUI, issue https://github.com/microsoft/microsoft-ui-xaml/issues/8431
