### ISSUE TITLE
Feature: Open in VS/VSCode button should open the root of the repo

### ISSUE THREAD

**Issue by heftymouse** [files-community/Files#13102]
### What feature or improvement do you think would benefit Files?

When browsing subfolders of a Git repo, the Open in VS(Code) button in the status bar should open the root of the repo instead of the current subfolders. Additionally, the button should show VS or VSCode depending on whether there is a .sln file in the root of the repo.

### Requirements

- This proposal will make the open in IDE button for Git repos take into account the root of the repo instead of the current subfolder

### Files Version

2.5.21.0

### Windows Version

10.0.25393.1

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
The eventual goal is to make this feature work in any folder, not just Git repos.

**Comment by yaira2** [comment]
@heftymouse what about showing a split button? We can make the primary option "Open in VS Code", and the secondary flyout can have an option to "Open repo in VS Code". If the folder isn't a Git repo, we can hide the secondary button.
