### ISSUE TITLE
Files uwp flashes back when transferring applications

### ISSUE THREAD

**Issue by battenmufang** [files-community/Files#1311]
<!-- 
🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨

Files uwp flashes back when transferring applications，
And it went on for a long time，It can only be closed manually through the task manager.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Comment by battenmufang** [comment]
The files uwp encountered an error while transferring the application and lasted a long time. It can only be closed manually through the task manager.

**Comment by yaichenbaum** [comment]
@battenmufang Is this still an issue in v0.23.1?

**Comment by yaichenbaum** [comment]
Thanks again for your feedback.

_Since we didn't hear from you on this topic for 3+ days, we'll assume everything is worked out and close this feedback item. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this._
