### ISSUE TITLE
Bug: Entering a directory with keyboard `Enter` causes focus loss of the directory pane.

### ISSUE THREAD

**Issue by cos1110** [files-community/Files#13121]
### Description

When you enter a directory using the Keyboard 'Enter' key, causes loss of focus of the directory pane, as well as deselection of the first directory item.

### Steps To Reproduce

```
Example of directory structure:

A
  A1
     Target
  A2
```

1. You see directory `A` and have it selected, you press 'Enter'.
2. Now you are inside `A` and you see directories `A1` and `A2`.
3. Chances are that you have lost the focus from the directory pane.
4. See the workaround bellow to navigate to the `Target` directory.

**WORKAROUND**
1. Press `Tab` once to restore focus to the pane.
2. Press `Down` (you are on `A2`) to invoke a keyboard update event.
3. Press `Up` (you are on `A1`) to update.
4. Now you have both the pane active and the item `A1` selected.

### Requirements

When you press Keyboard `Enter` in order to enter a directory, the directory pane should remain focused. This would allow fast keyboard-based navigation with keys `Enter | Up-Down | Alt-Up`.

### Files Version

2.5.21.0

### Windows Version

10.0.19045

### Log File

[debug.log](https://github.com/files-community/Files/files/12239309/debug.log)

**Comment by yaira2** [comment]
This is a regression from earlier versions of Files where this worked as expected.

**Comment by hishitetsu** [comment]
It seems to work fine if the folder has 32 items or more. And this number seems to depend on this code.
https://github.com/files-community/Files/blob/f5d3d0f3a10708d4ed19fc17651f184a11d11f1c/src/Files.App/Utils/Storage/Enumerators/Win32StorageEnumerator.cs#L114

But I have no idea why this happens.

**Comment by yaira2** [comment]
@cos1110 this issue is fixed in the dev branch and will be included in the next release.
