### ISSUE TITLE
Bug: App Freezes when Right-Clicking on a File or Folder Before Full Load

### ISSUE THREAD

**Issue by Mthia727** [files-community/Files#13126]
### Description

When opening the app, if I right-click on any file or folder before the app is fully loaded, the app freezes.

### Steps To Reproduce

1. Launch the app.
2. Right-click on any file or folder during the loading phase.
3. The app should freeze, becoming unresponsive.

### Requirements

The app should handle right-click interactions gracefully, even if it's not fully loaded. It should not freeze or become unresponsive and should instead display the right-click context menu once the loading process is complete.

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2070

### Log File

[debug.log](https://github.com/files-community/Files/files/12256022/debug.log)

**Comment by yaira2** [comment]
@Mthia727 thank you for reporting this issue, this issue was recently fixed in our dev branch and will be included in the next release.
