### ISSUE TITLE
Alex

### ISSUE THREAD

**Issue by konashevich** [files-community/Files#13135]
### What feature or improvement do you think would benefit Files?

Great app, devs! 
One suggestion: add in settings change of date format. Say I don't like to have days (Monday, Tuesday) in my sorting coilum. Only digits. 

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.5.21.0

### Windows Version

10.0.22621.1992

**Comment by Lukiluc29** [comment]
You can already do this in the settings by selecting "System" or "Universal".
![Capture d'écran 2023-08-06 092654](https://github.com/files-community/Files/assets/128183422/9cbfb6c9-6e90-4f51-a233-70c1d52b6dbf)
