### ISSUE TITLE
Code Quality: Create alike RichCommands inheritance

### ISSUE THREAD

**Issue by QuaintMako** [files-community/Files#13132]
### Description

Some of the existing Rich Commands have an implementation similar enough they could be deriving from a common base class. Such work as already be done for the Rotation or commands

### Concerned code

The following Rich commands should be fused:

- [ ] `Run as` commands
- [ ] `Compress into archive` commands
- [ ] `Decompress archive` commands
- [ ] `Restore recycle bin` commands
- [ ] `Tab closing` commands

### Gains

- Reduced duplication
- Centralized logic

### Requirements

- Akin rich commands are inheriting from the same base class

**Comment by yaira2** [comment]
Thank you for the feedback
