### ISSUE TITLE
Expand folder

### ISSUE THREAD

**Issue by fxgrmbl** [files-community/Files#13139]
### What feature or improvement do you think would benefit Files?

Like in the Windows Explorer, it would be nice to have "Expand to current folder" to have the navigation pane automatically expand to the current folder or drive as you open them in File Explorer

### Requirements

i don't know

### Files Version

2.5.21.0

### Windows Version

10.0.22621.1702

**Comment by yaira2** [comment]
Thank you for your feedback, adding a tree view is on our todo list and is being tracked in #1928. Please subscribe to that issue for further updates.
