### ISSUE TITLE
Bug: Issue with Folder Icons and Background in Preview Pane

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#13136]
### Description

Recently, I mentioned a bug where Git files or folders were not displaying properly in the preview pane, but somehow, this issue has been resolved, and I'm unsure how. However, a new problem has emerged - the folder icons in the preview pane now appear very small and have a black background. I also want to clarify that I am using Files Dev.

### Steps To Reproduce

1. Show preview pane
2. Go to a folder (for example, Users because it has a black background)

### Requirements

Investigate the recent changes or updates made to the system to understand how the previous bug was resolved.
Analyze the current preview pane settings and configurations to identify the cause of the small icons and black background issue.

### Files Version

2.5.21.0

### Windows Version

22H2 22621.1992

### Log File

No need.

**Comment by yaira2** [comment]
@Lukiluc29 can you try clearing the icon cache in File Explorer and seeing if the issue returns?

**Comment by Lukiluc29** [comment]
Thank you, my problem has finally been resolved thanks to your help.

**Comment by yaira2** [comment]
@Lukiluc29 thanks! Let us know if it returns.
