### ISSUE TITLE
Feature: Request to Adjust Button Margin for Property Alignment

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#13140]
### What feature or improvement do you think would benefit Files?

I have a request regarding the alignment of the properties button. Would it be possible to modify the button margin to align it with the text? Currently, the margin is set to 8, but I would like it to be 12 to achieve better alignment.

### Requirements

Adjust the margin settings to ensure proper alignment with the surrounding text.

### Files Version

2.5.21.0

### Windows Version

22H2 22621.1992

### Comments

Before
![Capture d'écran 2023-08-06 184941](https://github.com/files-community/Files/assets/128183422/8913f779-6b4e-4754-9b05-8aa34d1292c1)
After
![Capture d'écran 2023-08-06 184145](https://github.com/files-community/Files/assets/128183422/f368ecaa-f1b1-4518-a525-0a510330752a)
![Capture d'écran 2023-08-06 184613](https://github.com/files-community/Files/assets/128183422/40a7ad14-f4ee-47a9-bca6-08bac2854d86)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
@Lukiluc29 do you want to open a pull request with this change?

**Comment by yaira2** [comment]
I ended up fixing this in #13138

**Comment by Lukiluc29** [comment]
> I ended up fixing this in #13138

Perfect
