### ISSUE TITLE
Feature: Add support for searching for multiple tags

### ISSUE THREAD

**Issue by moneill29** [files-community/Files#13143]
### What feature or improvement do you think would benefit Files?

I would like the ability to search for files containing a combination of multiple tags. For example:

File 1: Tag A + Tag B + Tag C
File 2: Tag B+C
File 3: Tag B + Tag D

In this case I would like to search for files that only include the combination of Tag B + Tag C, therefor only showing Files 1 + 2, and not 3. I hope that makes sense

### Requirements

Search using tag combinations.
Get more specific search results

### Files Version

2.5.21.0

### Windows Version

10.0.22621.1992

### Comments

I am unsure if this is already a feature but so I haven't seem to find anything indicating it is. Thanks

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
@Josh65-2201 isn't this possible with search filters?

**Comment by Josh65-2201** [comment]
Normally you can use `AND` but Files will just show no results if used with tags when I tried it.

**Comment by hishitetsu** [comment]
It already does that. Type "tag:A,B" to search files that have both Tag A and Tag B.

**Comment by Josh65-2201** [comment]
This should be added to the docs
