### ISSUE TITLE
Files sometimes doen't start 

### ISSUE THREAD

**Issue by Mattiuz93** [files-community/Files#13156]
### Description

It happens that, when starting the PC with Windows 10, the app does not start showing a black screen. So I have to restart the pc to use it since a forced closure doesn't help either

### Steps To Reproduce

1. Start PC
2. Open the app (if doesn't work, reboot the PC)

### Requirements

The application should open and function normally

### Files Version

2.5.21.0

### Windows Version

10.0.19045.3271

### Log File

[debug.log](https://github.com/files-community/Files/files/12292157/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report. In future only upload the `debug.log` file not the entire directory settings directory.
- How are you opening Files? Through the start menu, using the task manager startup section or some other way.
- What happens if you wait a few seconds.

**Comment by Mattiuz93** [comment]
Directly from the application bar. If I wait nothing happen, only black screen

Sent with Spark
Il 8 ago 2023, 16:03 +0200, Josh65-2201 ***@***.***>, ha scritto:

**Comment by yaira2** [comment]
@Mattiuz93 thank you for the report, this appears to be an issue in the WinAppSdk framework. There is a new version of WinAppSdk coming out in a few months which we hope includes a fix for this issue.

**Comment by Mattiuz93** [comment]
Thanks!

Sent with Spark
Il 15 ago 2023, 17:05 +0200, Yair ***@***.***>, ha scritto:

**Comment by Mattiuz93** [comment]
I've tried your new app and it's more faster, smooth and - for now - it doesn't have the bug that I've wrote

Sent with Spark
Il Aug 31, 2023, 10:31 PM +0200, Yair ***@***.***> ha scritto:
