### ISSUE TITLE
Keeps opening random folders, isn't responsive.

### ISSUE THREAD

**Issue by aipa1oovik** [files-community/Files#13154]
### Description

It opens random folders, asks whether if want to delete a folder, and LAGS so much.

### Steps To Reproduce

Just open it.

### Requirements

- e.g. Fix crash that occurs when...
I can't be bothered to find that.

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2070

**Comment by Josh65-2201** [comment]
Thanks for the report. Can you check what Files settings > General > Startup settings is set to.

**Comment by yaira2** [comment]
@aipa1oovik can you clarify what you mean by opening random folders? The default behavior is to continue where you left off, but you can change this from the settings menu.

> asks whether if want to delete a folder

Is this when taking a specific action?

> and LAGS so much.

Thank you for sharing your concern, improving performance is a top priority for us and something we're putting a lot of work into. Is there a specific area that's slower than others?

**Comment by yaira2** [comment]
@aipa1oovik
