### ISSUE TITLE
Folders

### ISSUE THREAD

**Issue by Eaglemaster10** [files-community/Files#13159]
### Description

Can't make new folders with the latest version. 

### Steps To Reproduce

Right Click
New
Folder

### Requirements

Just blank nothing happens

### Files Version

2.5.21.0

### Windows Version

11

### Log File

Nothing to uplaod

**Comment by Josh65-2201** [comment]
Thanks for the report. Can you give the following information.
- Where are you making the folder
- Do you get any error message using Windows File Explorer

**Comment by Eaglemaster10** [comment]
I tried Dcouments, Downlaods, Desktop, Pics, one of my hard drives.

**Comment by yaira2** [comment]
@Eaglemaster10 please upload the log file so we can take a look.

**Comment by Eaglemaster10** [comment]
Here's the only log file. The Folder never even gets highlighted when pointing at it. I can select everything else,  and they all work.
[debug.log](https://github.com/files-community/Files/files/12299883/debug.log)

**Comment by Eaglemaster10** [comment]
Here's a video

https://github.com/files-community/Files/assets/141558043/5eb7292a-a9a3-4c1c-b848-b905268854b1

**Comment by Eaglemaster10** [comment]
Can't Select Folder Video

https://github.com/files-community/Files/assets/141558043/6b716e26-11f2-4038-9993-28ceecb91fef

**Comment by Eaglemaster10** [comment]
OK. I played with the settings and checked Open Folder in New Tabs. After I did that the Folder Option was highlighted and I could make a folder. If I click that off, the Folder option is again not highlighted and I cannot make a Folder.

**Comment by Josh65-2201** [comment]
The issue from the video is related to #10823. I don't believe open folders in new tab is the issue.

**Comment by Josh65-2201** [comment]
Can you use the new option in the tool bar. it under the address/path bar

**Comment by Eaglemaster10** [comment]
Yes, that seems to work. I'll use that instead of the right-click. Thanks for the pointer.

**Comment by Josh65-2201** [comment]
Thanks for the updates, Merging with #10823. You can check there or click subscribe in the right sidebar for updates.
