### ISSUE TITLE
Show full name of file/folder

### ISSUE THREAD

**Issue by RishiVora** [files-community/Files#13164]
### What feature or improvement do you think would benefit Files?

Currently, the file/folder name is truncated when in icon mode like this
![image](https://github.com/files-community/Files/assets/97402159/4bf5a212-f852-400d-8385-fc445405c2fb)

It would be nice to have an option to show full name like this
![image](https://github.com/files-community/Files/assets/97402159/15e8df5b-6c1a-400a-9d56-0416d76d14cb)

### Requirements

An option to toggle this in the settings

### Files Version

2.5.21.0

### Windows Version

10.0.22621.1555

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #1033. You can check there or click subscribe in the right sidebar for updates.
