### ISSUE TITLE
Feature: Separate startup settings based on how the app was closed

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#13165]
### What feature or improvement do you think would benefit Files?

I'm currently using the app with startup settings set to "Continue where you left off". But when the app is closed by closing the last tab, I'd like the home page to be displayed the next time the app is launched, not the closed tab. If there are separate startup settings for exiting the app by closing the window and for exiting an app by closing the last tab, that will accomplish what I want to do.

### Requirements

Separate startup settings for exiting the app by closing the window and for exiting an app by closing the last tab.

### Files Version

2.5.21.0

### Windows Version

10.0.19045.3324

**Comment by Josh65-2201** [comment]
Would it make more sense to use the same setting as is, but change the order of execution. When the last tab is closed it will edit the setting file last session section first to be nothing then close Files. Then on open if nothing is in the last session section it just open the home page.

**Comment by yaira2** [comment]
I think it's a bug where closing the last tab saves the session. The expected behavior is clear the list so the next session opens to the home page.

**Comment by hishitetsu** [comment]
Then, should I close this issue and open a new one as a bug?
