### ISSUE TITLE
Annotate tags with a cardinal number that represents total files that match the tag

### ISSUE THREAD

**Issue by ObiW4nKenobi** [files-community/Files#13161]
### What feature or improvement do you think would benefit Files?

I want all the tags to be annotated with a cardinal number, enclosed in a circle (or badge?), that represents how many files have been tagged with that specific tag. Much like the way Windows 10/11 shows the number of new notifications at the bottom right hand corner of the desktop. Much like many applications display notifications these days. Another example can be seen on Microsoft's "Mail" application.

A color of green on the badge could indicate everything appears legit. A red color could mean that there is a mismatch in the database of tagged files where the number of expected tagged files does not match.

### Requirements

- This proposal will allow users to see number of files with a selected/specific tag
- This proposal will alert users to possible tag issues when there is a cardinal mismatch between expected/actual tagged files
- This proposal will add consistency between applications in their approach to displaying meta-data.

### Files Version

2.5.21.0

### Windows Version

10.0.19045.3208

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
Thank you for the feedback, we'd like to learn more about your use case for displaying the count on the sidebar.

**Comment by ObiW4nKenobi** [comment]
It's just meta-data. I'm sure what else I can tell you. But if you have a specific question I can try to answer it. Microsoft Mail is an example of my feature request. It tells me how many new emails you have waiting unread. Same thing with the Windows 10/11 notifications in the bottom right corner of the desktop. It tells you how many new notifications you have that are unread. That's all this feature request is. A visual cardinal number indicator telling how many files are tagged with a specific tag. So, there would be one for each unique tag displayed over the tag in the most appropriately aesthetically pleasing manner left up to the developers.

**Comment by yaira2** [comment]
I understand what you're asking but I'm trying to understand the use case for displaying the number on the sidebar. Unlike notifications which require action, tags are just a way of organizing files, and the number of tagged items doesn't need to be displayed on the sidebar.

**Comment by ObiW4nKenobi** [comment]
Who makes the decision about whether it's required or not? Its just meta-data. When you click on a file you see meta-data about the file. It's just an interesting piece of data which would be pleasing to know at times. It could be a setting which is clicked on or off at will by the end-user. Let the user decide whether it needs to be displayed or not.

**Comment by yaira2** [comment]
I might have misunderstood the original request, I thought you were referring to the sidebar but looking at it again I see you didn't mention anything about the sidebar. You can find the count on the status bar when viewing the search results for a tag. Is this what you were looking for?

**Comment by ObiW4nKenobi** [comment]
They say a picture is worth a thousand words so let me try that:

![2023-08-17 12_26_11-tag_Documentation - Files](https://github.com/files-community/Files/assets/25889253/90bbc793-5980-4b50-b9c5-9699d73dd80d)

**Comment by yaira2** [comment]
Ah, so this was referring to the sidebar. I still don't see how the meta data is important enough to always display it on the sidebar, and I'm struggling to see a use case where seeing the number helps with productivity.

I'm not trying to shoot this down, but it might help if you explain how this feature would improve your workflow when using Files. Understanding the way you use the app will help me consider this request in the proper context.

**Comment by yaira2** [comment]
@ObiW4nKenobi
