### ISSUE TITLE
Group by date issue

### ISSUE THREAD

**Issue by newyork2003** [files-community/Files#13160]
### Description

IF you sort by date your download folders. Then every time you open it the files app do not start by showing the today but this month

### Steps To Reproduce

1-group by date a folder
2- close files app
3-open this same folder, it will show this month files not today`s files

### Requirements

fix so it shows today when opens up the folder

### Files Version

2.5.21

### Windows Version

windows 10 pro 22H2 19045.3208

### Log File

[debug.log](https://github.com/files-community/Files/files/12294879/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report. Can you give the following information.
- Do they show if you scroll up

**Comment by newyork2003** [comment]
> Thanks for the report. Can you give the following information.
> 
> * Do they show if you scroll up

yes if i scroll up its tyhere, but is a bummer cuz it should strt by today

**Comment by Josh65-2201** [comment]
Merging with #6186. You can check there or click subscribe in the right sidebar for updates.
