### ISSUE TITLE
Feature: Remove Diagonal Bar When Resizing Files Window

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#13172]
### What feature or improvement do you think would benefit Files?

I'd like to inquire if it's possible to remove the thin diagonal bar that appears when resizing the Files window.

### Requirements

Modify the code to disable the appearance of the diagonal bar.

### Files Version

2.5.21.0

### Windows Version

22H2 22621.1992

**Comment by Josh65-2201** [comment]
Thanks for the feedback. Are you talking about the cursor icon that show the window can be resized?

**Comment by Lukiluc29** [comment]
> Thanks for the feedback. Are you talking about the cursor icon that show the window can be resized?

No. Actually, when you resize the application window, a thin diagonal bar appears across the entire window. Here's a screenshot to demonstrate.
![Capture d'écran 2023-08-10 171741](https://github.com/files-community/Files/assets/128183422/1cc1d8eb-7ffe-4ed0-836a-e19a5ce482d1)

**Comment by Josh65-2201** [comment]
Thanks for the clarification, This seem like it would be a WinUI issue, I've added this to the project board.

**Comment by yaira2** [comment]
This appears to be an issue with WinAppSdk and there isn't anything we can do from our side. That said, we'll be sure to update WinAppSdk when a fix becomes available.
