### ISSUE TITLE
Bug: Display Issues in Disk and Cloud Drive Properties Panel

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#13177]
### Description

When I go into the properties of a disk or a cloud drive, the second panel where the storage is displayed in the details section doesn't have rounded corners, and the separator bar between the storage and "Disk Cleanup" extends beyond both sides, which is not the case in a regular folder.

### Steps To Reproduce

1. Go to a drive or Cloud drive
2. Right-click on a drive
3. Open "Properties"

### Requirements

Revamp the second panel on the "Details" page of the properties to match the others.

### Files Version

2.5.21.0

### Windows Version

22H2 22621.1992

### Log File

No need.

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
@Lukiluc29 do you want to work on this? It should be an easy fix.

**Comment by Lukiluc29** [comment]
I will look at it
