### ISSUE TITLE
App crashes when selecting files from within a .zip

### ISSUE THREAD

**Issue by jjongue** [files-community/Files#13170]
### Description

When in column view, after opening (double click) a zip file, if you select (left click) a file within the zip the app crashes and returns an error message pop (see attached)

### Steps To Reproduce

1. Open a zip file via double-clicking
2. Select (left mouse click) on any file within the zip
3. App crashes

### Requirements

- The zip file opens without issue
- Select contents within the zip file doesn't crash the app
- Ability to extract the contacts without app crashing

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2070

### Log File

![000033](https://github.com/files-community/Files/assets/141884406/e9dfdac2-e777-495a-a7ab-1263ec0363a7)

**Comment by ferrariofilippo** [comment]
Thank you for reporting this issue. Can you upload `log file`? You can find it at `Settings > About > Help and support > Open log location > debug.log`

**Comment by jjongue** [comment]
Please see attached

**Comment by ferrariofilippo** [comment]
> Please see attached

That is not the log file, that is the default message that pops up when Files crashes.
Sharing the log file would make it easier for us to identify what's causing the crash

**Comment by Josh65-2201** [comment]
Email attachments don't work by the way you have to open GitHub site and uploaded it in the comment box

**Comment by jjongue** [comment]
[debug.log](https://github.com/files-community/Files/files/12326675/debug.log)

**Comment by yaira2** [comment]
@jjongue thank you for the feedback, I'm not seeing this issue in the latest preview build so it's possiblee that it's already resolved. Can you test on your device and see if it's working as expected? https://files.community/download
