### ISSUE TITLE
The 'Show in Folder' option within MS Edge does not launch Files

### ISSUE THREAD

**Issue by jjongue** [files-community/Files#13171]
### Description

After setting Files as the default windows explorer app, when downloading a file using MS Edge, the option "Show in Folder" which typically launches windows explorer and takes you directly to the location of where the file was downloaded, this function no longer works. Nothing happens when clicking on 'Show in Folder' 

### Steps To Reproduce

1. Open MS Edge browser
2. Download a file
3. When file is finished downloading, click Show in Folder (see attached screenshot)
4. Nothing happens, Files or Windows Explorer does not launch.

### Requirements

The expected behaviour is that Files will launch taking me directly to the downloaded location where the file was saved under.

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2070

### Log File

![000034](https://github.com/files-community/Files/assets/141884406/85ba7b98-1f0e-454b-96f3-60dc49d3ec07)

**Comment by Josh65-2201** [comment]
Thanks for the report. Are you certain Files isn't open on the taskbar. Right now it doesn't focus the window

**Comment by jjongue** [comment]
I've tried both with files open on the taskbar as well as closed. I've
rebooted and tried again but same issue. I have to manually launch files
and navigate to the downloaded location.

**Comment by Lukiluc29** [comment]
I manage to reproduce the same problem

**Comment by Josh65-2201** [comment]
Thanks for the checking, I've added this to the project board.

**Comment by yaira2** [comment]
> I manage to reproduce the same problem

@Lukiluc29 can you repro this in older versions of Files?

**Comment by jjongue** [comment]
I've only just recently purchased files, I've never used it before. I
wanted something to mimic the column view experience that you get from Mac
OS.

**Comment by Josh65-2201** [comment]
@yaira2 I use to work

**Comment by yaira2** [comment]
@Josh65-2201 the question is if Microsoft changed something on their end or if it's a regression in Files.

**Comment by Lukiluc29** [comment]
> @Lukiluc29 can you repro this in older versions of Files?

I tried with an old version but this problem was still present (I don't use Files from the Microsoft Store).

**Comment by yaira2** [comment]
If that's the case, it would be a change in Microsoft Edge that's causing this issue. We're pretty much at the limits with what we can do with the registry and we'll need a proper setting from Microsoft for this to be resolved.
