### ISSUE TITLE
FUll file names

### ISSUE THREAD

**Issue by newyork2003** [files-community/Files#13175]
### What feature or improvement do you think would benefit Files?

In the icon layout the file names are too short, making the software unpractical to use.

### Requirements

- This proposal will accomplish proper use of the software
- This proposal will accomplish proper file management

### Files Version

2.5.21

### Windows Version

windows 10 pro 22H2 19045.3208

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #1033. You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
@newyork2003 thank you for your feedback. We don't have a solution right now as there aren't any WinUI Grid controls that will allow us to wrap file names without increasing the height of all the other rows, but we'll keep looking. We'll provide an update in #1033 when a solution is found.
