### ISSUE TITLE
Crash when loading/moving images

### ISSUE THREAD

**Issue by redluee** [files-community/Files#13178]
### Description

I just installed Files to organise my images. This application loads the image previews much faster than file explorer.
But sometimes when i open a folder with many images the program crash, or when i move images over to a different folder it also crashes. The images do get moved despite the crash.
I don't know if it only happens when moving images because i don't use the program that long. 

This doesn't happen 100% percent of time but it is a bit frustrating when it happens.
I hope it can be fixed.

### Steps To Reproduce

1. Open a folder in Files where your images are stored which you want to move.
2. Open another window where you want to move the images.
3. Move all the images over and when you do the program crashes sometimes.

### Requirements

I expect the crash not to happen when moving the files over to another folder or opening a folder with many images.

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2134

### Log File

[debug.log](https://github.com/files-community/Files/files/12315088/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #12581. You can check there or click subscribe in the right sidebar for updates.
