### ISSUE TITLE
Incorrect icons being chosen in directory list

### ISSUE THREAD

**Issue by Aurumaker72** [files-community/Files#13174]
### Description

The icons chosen in the directory list are incorrect.

### Steps To Reproduce

1. Install foobar2000 (or any other program which supports custom icon associations)
2. Open an audio file with foobar2000
3. Establish a custom icon association by checking "Always open with foobar2000"
4. Check File Explorer to see the icons in detail view
![image](https://github.com/files-community/Files/assets/48759429/ff945fdb-ecfd-45ee-9546-f3698dbab824)
5. Files in detail view, however, still uses the full-size icon
![image](https://github.com/files-community/Files/assets/48759429/704792d5-7af3-423f-a7c0-22d9d2df31d4)

### Requirements

The program is expected to correctly pick the icon type based on the directory view type (e.g.: extra large, detail...)

### Files Version

2.5.21.0

### Windows Version

10.0.22621.1992

### Log File

[debug.log](https://github.com/files-community/Files/files/12313087/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, the icons in Files are a little larger and aren't intended to be a 1:1 match with File Explorer.
