### ISSUE TITLE
Separator Options

### ISSUE THREAD

**Issue by zerquetch** [files-community/Files#13180]
### What feature or improvement do you think would benefit Files?

Can we remove alphanumeric separator from details list ? I think most of us know where "D" ends and "E" begins

### Requirements

Just need an option in either View, or settings. And a tree...

### Files Version

2.5.21.0

### Windows Version

23H2

### Comments

I know I haven't spent more than 12 minutes with it, but a Nav tree, and please toast the separator. Thank you, otherwise, it's quite charming.

**Comment by Josh65-2201** [comment]
Thanks for the feedback. If you mean the group by name option you can turn it off on the right of the toolbar
![image](https://github.com/files-community/Files/assets/26977075/c8e3a5d8-012a-49be-b3bc-6190d2d8c169)

**Comment by 0x5bfa** [comment]
clicking the Name header enables you to sort by name without that.
