### ISSUE TITLE
Bug: Hidden Git columns are still being calculated

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#13182]
### Description

The data for the Git columns is calculated even when the columns are hidden. This leads to unnecessary resource consumption and should be an easy way to improve performance in Git repos.

### Steps To Reproduce

1. Hide all the Git columns in the Details layout
2. Observe that the memory isn't freed up

### Requirements

- only load Git data for visible columns
- free up data if a column is hidden

### Files Version

v2.5.21

### Windows Version

Windows 11

### Log File

NA

**Comment by hishitetsu** [comment]
I'll see if I can fix it.
