### ISSUE TITLE
Feature: Choose different sort options for files and folders

### ISSUE THREAD

**Issue by fredphoesh** [files-community/Files#13188]
### What feature or improvement do you think would benefit Files?

In my folder view, I always want folders to be alphabetical so I can find them, BUT I always want my files to be chronological by default as I most usually want to access files I have recently accessed.
My feature request is for the sort mode to be split, Folders by Name and Files by Date.

On a side note, probs not the place to mention, I really dislike the grouping that Microsoft seems intent on pushing on us, and I've seen it sneak into Files, despite that fact I have grouping turned off in Files Settings.

Thanks!
Mark.

### Requirements

This feature will allow me to access what I want more quickly than if Files and Folders were either sorted by Name or by Date.

### Files Version

2.5.21.0

### Windows Version

11 Pro 23H2

**Comment by Josh65-2201** [comment]
Thanks for the feedback, I've added this to the project board.

As for you note. Where are you seeing this as Files doesn't do it change the grouping by default.

**Comment by fredphoesh** [comment]
> As for you note. Where are you seeing this as Files doesn't do it change the grouping by default.

Hey Josh, 
Thanks for adding my request.

I saw the Grouping this week, and If I see it again I will post a screen shot here. I don't see it at the moment... and I'm not 100% sure it wasn't File Explorer that I saw it on, perhaps after Files crashed or something (Files is set to replace Explorer by default so FExplorer would only show up Files wasn't running)

**Comment by fredphoesh** [comment]
> Thank you for the feedback, this is an interesting idea and something we'll consider. Have you seen this in any other apps?

Hi, no I have not seen this before, have no idea if it is even possible... but for me, it does make sense as I have far more files than folders, so scrolling alphabetically isn't a major hassle, but finding files that way, when you have hundreds or thousands of files, can be a pain ;)

**Comment by yaira2** [comment]
Thank you for your feedback. There doesn't look to be a lot of interest in this idea, so we won't be able to implement it now, but we'll be happy to reconsider if anything changes.
