### ISSUE TITLE
Display speed and time remaining when copying

### ISSUE THREAD

**Issue by LastuvkaLukas** [files-community/Files#13187]
### What feature or improvement do you think would benefit Files?

More visibility when copying, moving or deleting files and folders

### Requirements

- Display speed and time remaining when copying and display approximate time remaining to finish as in microsoft explorer. 
- Additionally the possibility to create a common window of all transfers in the queue.

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2134

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #11265 and #8207. You can check there or click subscribe in the right sidebar for updates.

I don't think time remaining is needed as it's very inaccurate and needs extra space to show.
