### ISSUE TITLE
mouse hover

### ISSUE THREAD

**Issue by gomeaqj** [files-community/Files#13189]
### What feature or improvement do you think would benefit Files?

I would like to add a feature that automatically activates a tab when the mouse hovers over it.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.5.21.0

### Windows Version

10.0.22621.525

### Comments

![2023-08-13_194044](https://github.com/files-community/Files/assets/11981750/10bd4cad-8f05-420e-90ce-1ab6b9af14b9)

**Comment by Josh65-2201** [comment]
Thanks for the feedback. How would this be more beneficial to you compared to click?

**Comment by yaira2** [comment]
Wouldn't it be quicker to click the tab?
