### ISSUE TITLE
Bug: The sidebar doesn't follow the custom font setting

### ISSUE THREAD

**Issue by RunicLena** [files-community/Files#13191]
### Description

As the title says, the new sidebar doesn't take custom fonts or compact into account ![Screenshot-2023-08-13 09_42-ToastWindow](https://github.com/files-community/Files/assets/117479618/31aaf32c-4b5c-40bc-9e1b-13345fd67765)

### Steps To Reproduce

-Set any custom font or enable compact view
-See the sidebar not cooperating

### Requirements

- Allow new sidebar to use these settings

### Files Version

2.5.22.0

### Windows Version

10.0.22621.2134

### Log File

[debug.log](https://github.com/files-community/Files/files/12329958/debug.log)

**Comment by yaira2** [comment]
@RunicLena thank you for reporting this issue.
