### ISSUE TITLE
Unable to resize from the top of the application window

### ISSUE THREAD

**Issue by jjongue** [files-community/Files#13199]
### Description

When attempting to resize the app window from the top, when the mouse cursor changes to the resize cursor (double arrow in opposite directions), clicking and dragging the app window doesn't resize. Instead, it moves the entire app window.

All other directions i.e. from the bottom of the app window, worked as expected. 

OS: Windows 11 (22H2)
Device: Surface Pro 8

### Steps To Reproduce

1. Open Files
2. Move mouse cursor to the top of the app window
3. Click and drag as though to resize the app window vertically (any direction)
4. The app window will move instead of resize.

### Requirements

The expected behaviour is for the app window to resize vertically. (Shirk or expand)

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2134

### Log File

[debug.log](https://github.com/files-community/Files/files/12341305/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #10813. You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
@jjongue thank you for reporting this issue, it appears that this is a problem with the WinAppSdk framework, but we'll continue looking for a solution and we'll comment in #10813 if an update is available.

**Comment by yaira2** [comment]
This issue is fixed in the development branch and will be included in the next release.

**Comment by hishitetsu** [comment]
@yaira2 why did you reopen this?

**Comment by Josh65-2201** [comment]
I'm guessing it was a mistake

**Comment by yaira2** [comment]
I'm sp used to clicking the "Close with comment" button that I sometimes forget that it's also the "reopen with comment" button.
