### ISSUE TITLE
Bug: Hide deleted items from the tags widget

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#13193]
### Description

I have encountered a problem related to label display and file deletion. When labels are displayed on the home page and a file with a label is deleted, if the category containing the file remains on the home page, the file appears under a different name both on the home page and in the search results when clicking on the category name for a search. Additionally, the displayed path leads to the Recycle Bin.

### Steps To Reproduce

1. Add tags in the homepage
2. Add File or Folder to tag
3. Delete file or folder without removing tag
4. Go to the homepage
5. Observe that the deleted item in recycle bin is still displayed in the list

### Requirements

Hide deleted items from the tags widget

### Files Version

6.5.22.0

### Windows Version

22H2 22621.1992

### Log File

<img width="186" alt="Capture d'écran 2023-08-13 190342" src="https://github.com/files-community/Files/assets/128183422/96b10fc6-47cd-4a37-90a0-0323b5050323">

**Comment by yaira2** [comment]
@Lukiluc29 thank you for the feedback, can you fill out the steps to repro so we can test on our end?

**Comment by Lukiluc29** [comment]
> @Lukiluc29 thank you for the feedback, can you fill out the steps to repro so we can test on our end?

It's good.

**Comment by yaira2** [comment]
Can you confirm if permanently deleting the item removes it from the list?

**Comment by Lukiluc29** [comment]
> Can you confirm if permanently deleting the item removes it from the list?

Yes, when an item is permanently deleted, the item disappears properly this time.
