### ISSUE TITLE
Bug: Deleting a file by any means crashes

### ISSUE THREAD

**Issue by RunicLena** [files-community/Files#13192]
### Description

Deleting files while a tab with that file is open crashes the app, even when the app itself did not delete it.
Note that the files do get successfully deleted before the crash

### Steps To Reproduce

-Open any folder
-Delete any file within that folder
-Watch the file get removed, and the app crash afterward

### Requirements

- Fix crash that occurs when deleting files

### Files Version

2.5.22.0

### Windows Version

10.0.22621.2134

### Log File

[debug.log](https://github.com/files-community/Files/files/12330002/debug.log)

**Comment by yaira2** [comment]
Thank you for reporting this issue, I'm able to reproduce it on my device in v2.5.22.
