### ISSUE TITLE
对使用files遇到的一些问题反馈

### ISSUE THREAD

**Issue by Aspirin-7** [files-community/Files#13205]
### What feature or improvement do you think would benefit Files?

files对文件拖动到其他软件打开的支持还不够好 很多软件目前还不支持直接拖动打开
files对优盘硬盘的占用导致必须将软件关闭才能卸载外资存储
files有时候打开文件夹不会默认弹到页面窗口顶部，仅是在后台打开
拖动只有左侧部分生效  右侧无法拖动窗口

然而并不影响他是一个优秀的插件

### Requirements

files对文件拖动到其他软件打开的支持还不够好 很多软件目前还不支持直接拖动打开
files对优盘硬盘的占用导致必须将软件关闭才能卸载外资存储
files有时候打开文件夹不会默认弹到页面窗口顶部，仅是在后台打开
拖动只有左侧部分生效  右侧无法拖动窗口

然而并不影响他是一个优秀的插件

### Files Version

2.5.2.1

### Windows Version

11

### Comments

.

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Please make sperate issues for different feedback.

> Files support for dragging files to other software to open is not good enough Many software does not currently support direct drag and open

Thanks for the feedback, Merging with #11735. You can check there or click subscribe in the right sidebar for updates.
Also what programs aren't working for you?

> Files occupies the USB hard disk so that the software must be closed to unmount foreign storage

What do you mean by this?

> Files Sometimes opening a folder does not pop up to the top of the page window by default, only opens in the background

Thanks for the feedback, Merging with #10844. You can check there or click subscribe in the right sidebar for updates.
This is currently blocked by WinUI and Files can not fix it right now

> Drag only takes effect on the left side The right side cannot drag the window

I don't have this issue, can you send a video recording of this issue.

**Comment by yaira2** [comment]
> Drag only takes effect on the left side The right side cannot drag the window

Does this mean dual pane?

**Comment by Aspirin-7** [comment]
https://github.com/files-community/Files/assets/55964882/0a45a35e-d911-4a00-9389-e8384fd1acc0

**Comment by Josh65-2201** [comment]
Resizing from the top is a known issue #10813. You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
The issue with resizing from the title bar will be fixed in v3.
