### ISSUE TITLE
Feature: Add KeyboardShortcut custom control

### ISSUE THREAD

**Issue by 0x5bfa** [files-community/Files#13200]
# Feature: Add KeyboardShortcut custom control

## Motivation and Context

Currently the Files displays keyboard shortcuts in TextBlocks and gives users no visual effect. Following the new keyboard shortcut custom control that Windows introduced in Windows 11, we introduce a new control. This can be used in the hotkey customization settings page that may be implemented in the future, in the command palette suggestion items, and even in the MenuFlyout items.

**I got inspiration from this UI**
![image](https://cdn.discordapp.com/attachments/1131136425111330877/1131567393181806632/image.png)

**Ugly look in the command palette**
![image](https://cdn.discordapp.com/attachments/1131136425111330877/1137760092180205619/256807827-358fdbf1-a713-44b3-955f-e3dd4c3abdb0.png)

### Development & co-authors

- #13201
- @0x5bfa 

# Specs

### Definition
```cs
public class KeyboardShortcut : Control
```

### Description
Handles KeyboardShortcut control comprehensively.

### Status
- [x] Drafted
- [ ] Implemented

### Properties
Property name|Type|Description
---|---|---
ShortcutText|string|Gets or sets the content that represents the keyboard shortcut to be displayed in the control

### Pseudo code template (not actual usage)
```xaml
<></>
```

### Remarks
_None_

# Concepts

Made by @mdtauk

**Default style**
![image](https://github.com/files-community/Files/assets/62196528/fb52ac3a-8eb4-4db1-8be7-fd87afc9608f)

**Accent style**
![image](https://github.com/files-community/Files/assets/62196528/d2854e32-e066-4724-9468-81e55c666165)

**Reveal style**
![image](https://github.com/files-community/Files/assets/62196528/1d63c683-a6ce-47fc-9591-703edd008373)

**Comment by yaira2** [comment]
Where is the control going to be used, and what functionality will it have?

**Comment by yaira2** [comment]
> This was approved by the owner before

The idea was approved in theory but we still need to work out the details.

**Comment by 0x5bfa** [comment]
Sure, ideally this would be used in command palette items.

**Comment by yaira2** [comment]
Is there anywhere else where you think it'll be useful?

**Comment by 0x5bfa** [comment]
I think this is useful only for this.

**Comment by 0x5bfa** [comment]
If we are going to have an ability to customize hot keys in Settings page, this control would be useful as a custom control.

**Comment by 0x5bfa** [comment]
@mdtauk can you tell me all sizes, such as margins, paddings, borderthicknesses, fontweight, min height, and min width?

![image](https://github.com/files-community/Files/assets/62196528/1354bade-849b-4c60-8cb5-73fbca4e56d2)

**Comment by yaira2** [comment]
@0x5bfa this can be done, but there needs to be an option to disable the backplate + border.

**Comment by 0x5bfa** [comment]
Ok could be Reveal styled:
![IMG_9617](https://github.com/files-community/Files/assets/62196528/2257ee6c-116a-4315-bd98-6c7140732d0a)

**Comment by yaira2** [comment]
On second thought, we might need a backplate to separate between multiple shortcuts 
![image](https://github.com/files-community/Files/assets/39923744/98b28a30-1043-48b1-a867-5ab428964176)
