### ISSUE TITLE
Feature Request: Ability to Pin Selected Files to the Top of a Specific Folder

### ISSUE THREAD

**Issue by mgargan1** [files-community/Files#13203]
### What feature or improvement do you think would benefit Files?

Feature Request: Ability to Pin Selected Files to the Top of a Specific Folder

I am looking for a way to conveniently access specific files in a folder without having to rename or search for them. In my case, I have a collection of resume documents stored in a single folder. I would love to have the ability to pin selected files, such as key resumes, to the top of this specific folder for easy and quick access.

To further explain, I have this folder pinned to my quick access in Windows File Explorer, so I frequently access it. My request is for a feature that allows us to pin selected files to the top of the folder, similar to how we can pin folders to quick access. This would allow me to immediately see my selected resume files at the top when I open this specific folder, instead of having to either rename them or use the search function to find them among a large number of files.

I understand that I can use the search bar and input keywords to find these files, but as many of us may have experienced, the Windows File Explorer searching function can sometimes be slow. There are instances when visually scanning for the file might be quicker, especially when there aren't many files in the folder.

Having a consistent method to pin important files to the top of a specific folder would greatly enhance the user experience and efficiency when navigating through files and folders in Windows.

Many thanks for considering this feature request, and I would greatly appreciate any feedback on this!

### Requirements

Requirements - To make the pinning of selected files to the top of a specific folder possible, the following high-level requirements are proposed:

**1. Develop a User Interface (UI) option for pinning/unpinning files:**
This proposal will introduce a right-click context menu option or a toolbar button in the File Explorer/Files App for pinning and unpinning selected files.

**2. Establish a Pinning System within the File System:**
This proposal will create a system for marking and recognizing files that have been pinned within the Windows File System.

**3. Display Pinned Files at the Top of the Folder View:**
This proposal will ensure that pinned files are visually distinct and are always displayed at the top of the folder, regardless of the current sorting method.

**4. Save and Retain Pinning Preferences:**
This proposal will make sure that the pinning preferences of a user are saved and retained, even after system reboots or updates.

**5. Integrate Pinning Feature into Quick Access:**
This proposal will allow pinned files in specific folders to also appear at the top when those folders are accessed via Quick Access.

**6. Ensure Security and Permissions Integrity:**
This proposal will confirm that the pinning feature respects and does not alter the existing file and folder permissions.

**7. Design for Performance and Efficiency:**
This proposal will ensure that the pinning feature is designed to have minimal impact on system performance and responsiveness.
________________________________________

These high-level requirements are designed to give a comprehensive overview of the necessary changes and considerations to make the feature of pinning selected files to the top of a specific folder possible. Each of these items would likely involve more detailed technical specifications in a full proposal.

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2134

**Comment by yaira2** [comment]
Thank you for your feedback, have you considered using the tagging feature?
