### ISSUE TITLE
Duplicate users in security tab

### ISSUE THREAD

**Issue by GGProGaming** [files-community/Files#13206]
### Description

This occurs when going to the security tab in the properties of a drive
![image](https://github.com/files-community/Files/assets/84688324/21a9442a-abaa-48b4-8ac6-ee621fa71a6e)
![image](https://github.com/files-community/Files/assets/84688324/3b77386d-ffec-4486-a232-f7e9a5510bed)

### Steps To Reproduce

1. Right click a drive
2. Select Properties
3. Security
4. Duplicates

### Requirements

Only one items from each instead of blank, empty ones.

### Files Version

2.5.22.0

### Windows Version

10.0.23521.1000

### Log File

[debug.log](https://github.com/files-community/Files/files/12362922/debug.log)

**Comment by Lukiluc29** [comment]
Can you check if Windows File Explorer shows the same?

**Comment by GGProGaming** [comment]
No problems in file explorer 
![image](https://github.com/files-community/Files/assets/84688324/a65efbde-728e-4ac0-9d9f-efeefda452d7)

**Comment by Josh65-2201** [comment]
Thanks for the report, Can you check the following
- Can you send a screenshot of the advanced section of Windows File Explorer security page?
- What page are you seeing the duplicate entries in Files?

**Comment by 0x5bfa** [comment]
Those two Authenticated Users entries have no problems. but why there's two SYSTEM entries in spite of the fact that there's only one SYSTEM entry in File Explorer's advanced permission page.


In File Explorer in security tab property page's entries are merged into unique ones. for example, if there's two entries seen in advanced permissions page, File Explorer merge them into one entry in properties security tab page. However, Files doesn't have such functionality.

And you are wondering why this selected item has no checks.

![image](https://github.com/files-community/Files/assets/62196528/70ace59a-3385-48c5-8e75-de67c3c17d80)

This security tab page checkboxes represents generic permissions, such as Read(combination of read permissions), Write(combination of write permissions), Modify(combination of write and read permissions).
But as you can see the entry in advanced permissions page, that entry only allow 'Create folder / append data' permission. this access control is included in Read permissions but not allowed all read permissions.

For more information, see https://learn.microsoft.com/en-us/windows-hardware/drivers/kernel/access-mask, [GENERIC_WRITE, STANDARD_RIGHTS_WRITE](https://learn.microsoft.com/en-us/windows/win32/secauthz/generic-access-rights)

**Comment by GGProGaming** [comment]
![image](https://github.com/files-community/Files/assets/84688324/b7816b18-bf5e-435e-ab88-fd4a409ea6f2)
I now have this one and only one dup which is authenticated users

**Comment by GGProGaming** [comment]
That was my C:/ drive. Doing my other ssd, every name has a dup and the long string is gone.

**Comment by GGProGaming** [comment]
![image](https://github.com/files-community/Files/assets/84688324/2171ecf6-a0b9-49da-95f4-f31b0d74c46c)
No such problem in File Explorer

**Comment by Josh65-2201** [comment]
The long string is the user ID of the unknown account so that's intentional.

**Comment by 0x5bfa** [comment]
the reason why it is unknown is often is that user is another logon user. that user info doesn’t save other user profile registry. it seems theres no problem

**Comment by 0x5bfa** [comment]
we can close.
