### ISSUE TITLE
Critical Issue with Git Repository Access and Files Responsiveness

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#13212]
### Description

Since the recent update to version 2.5.22.0, a significant problem has arisen when accessing a Git repository. Both folders and Git files within this repository are experiencing severe issues, rendering navigation within the repository impossible. Furthermore, Files occasionally becomes unresponsive and crashes, which is particularly disruptive.

### Steps To Reproduce

1. Go to the Git repository

### Requirements

Identify and fix any code conflicts or problems between the new version and Git integration.

### Files Version

2.5.22.0

### Windows Version

22H2 22621.1992

### Log File

[debug.log](https://github.com/files-community/Files/files/12381569/debug.log)

**Comment by yaira2** [comment]
@Lukiluc29 can you check if this is resolved with the latest commit in `main`? Please reset the app before testing...

**Comment by Lukiluc29** [comment]
You are magicians! To my great surprise, everything is better now, and there are no more bugs with Git elements.

**Comment by yaira2** [comment]
You can thank @hishitetsu

**Comment by Lukiluc29** [comment]
Thank you so much @hishitetsu
Besides @yaira2 , I wanted to know when the next version of Files was planned.

**Comment by yaira2** [comment]
We don't have a release date yet
