### ISSUE TITLE
CTD when opening folder containing files that open in vscode.

### ISSUE THREAD

**Issue by NicTanghe** [files-community/Files#1321]
**Describe the bug**
CTD when opening folder containing files that open in vscode.

**To Reproduce**

Need to also have vscode.

1. Go to folder
2. Click on new txfile change extention to .ps1 (also ahk breaks)
4. change the default program to open with to vscode 
3. open the file
4. close the file and files-uwp
5. navigate to The folder from step 1
6. CTD occurs

**Expected behavior**
it just dislpays the contents of the folder and doesnt crash after 0.5 seconds.

**Desktop (please complete the following information):**
 - OS: Windows 10 2004
 - App version: v0.11.0

**Additional context**
i made the super+e key launch your ap instead of the default explorer using powertoys and ahk. Using alt+e

**Comment by yaichenbaum** [comment]
@NicTanghe Is this still an issue is v0.20?

**Comment by yaichenbaum** [comment]
Thanks again for your feedback.

_Since we didn't hear from you on this topic for 5+ days, we'll assume everything is worked out and close this feedback item. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this._
