### ISSUE TITLE
Bug: Context menu issue when right clicking file in Columns layout

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#13217]
### Description

I've encountered an issue where, upon right-clicking a file within a folder in column layout, the context menu that appears is from the folder itself, with certain options grayed out. This occurs instead of showing the appropriate context menu for the file, which forces me to perform an additional right-click to access the correct file-specific context menu.

### Steps To Reproduce

1. Put Files in column layout
2. Go to a file on a folder
3. Right-click on a file

### Requirements

Identify the cause of the incorrect context menu display.
Verify that the folder context menu is not interfering with the file context menu's visibility or functionality.

### Files Version

2.5.22.0

### Windows Version

22H2 22621.1992

### Log File

<img width="774" alt="Capture d'écran 2023-08-09 185140" src="https://github.com/files-community/Files/assets/128183422/5f2b0458-0f79-440d-be5a-7e4ce1a2b128">

**Comment by yaira2** [comment]
Is this only an issue with the column layout or have you seen it in other layouts as well?

**Comment by Lukiluc29** [comment]
Yes, I forgot to mention that! Effectively, this problem is present only in the column layout.
