### ISSUE TITLE
Bug: App crashes and removes pinned items after reordering them

### ISSUE THREAD

**Issue by StanFromTraction** [files-community/Files#13215]
### Description

![image](https://github.com/files-community/Files/assets/105176736/a177f9c1-a949-4996-b317-e6521284f321)

### Steps To Reproduce

1. Reorder favourites
2. Yet another crash
3. Reopen Files
4. Favourites disappeared into unknown dimension

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2134

### Log File

[debug.log](https://github.com/files-community/Files/files/12387740/debug.log)

**Comment by Lukiluc29** [comment]
Me too sometimes this problem can happen to me.

**Comment by Josh65-2201** [comment]
Thanks for the report, Can you do the below
- Send a screenshot of Windows File Explorer favorites
- Can you try clearing the recent folders in Windows File Explorer > '...' menu > Options > Under Privacy clear button.

**Comment by yaira2** [comment]
This happened to me a couple of times as well.
