### ISSUE TITLE
Group By Tags bug

### ISSUE THREAD

**Issue by consciouspumpkin** [files-community/Files#13214]
### Description

The Group By Tags feature breaks when exiting the folder. All files that are tagged will be grouped under "Untagged" as soon as you leave the folder. The files will still retain their proper tag. 

### Steps To Reproduce

1. Tag a group of files in a folder 
2. Select Group By Tags
3. Back out of the folder and then re enter the folder 
4. The files will now be grouped by Untagged in a random sort order

### Requirements

- e.g. Fix crash that occurs when...
The files should remain under their grouped tag when exiting and reentering the folder

### Files Version

2.5.21.0

### Windows Version

10.0.19045.3324

### Log File

[debug.log](https://github.com/files-community/Files/files/12384953/debug.log)

**Comment by gave92** [comment]
Merging with #11759
