### ISSUE TITLE
Bug: Issue with Black Background on Icons and Context Menu in Files

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#13218]
### Description

I'm experiencing an issue with certain icons having a black background. When I right-click on an item and go to "Send to" in the context menu, some icons have a black background. Additionally, when I right-click on a folder and access its properties, the icon displayed there also has a black background.

### Steps To Reproduce

1. Go to the context menu of an element
2. Click on "Send to"
1. Go to the properties of an folder

### Requirements

Conduct extensive testing across different items, folders, and properties to ensure consistent icon appearance and background transparency.

### Files Version

2.5.22.0

### Windows Version

22H2 22621.1992

### Log File

<img width="175" alt="Capture d'écran 2023-08-01 222750" src="https://github.com/files-community/Files/assets/128183422/4b9d4cc5-d2ad-4322-83d6-e6b17c1ffd34">
<img width="662" alt="Capture d'écran 2023-08-20 193045" src="https://github.com/files-community/Files/assets/128183422/06d8b3a7-1c0e-4d11-8589-89b5c2330677">

**Comment by yaira2** [comment]
Does clearing the icon cache in Windows fix this issue? I'm pretty sure it's a Windows issue and not a Files one.

**Comment by Lukiluc29** [comment]
No, because I have tried on different computers and this issue persists.

**Comment by yaira2** [comment]
I'm still looking into the content menu, but I have a fix for the properties window.
