### ISSUE TITLE
When auto-hidden taskbar is enabled, Files prevent it from showing up

### ISSUE THREAD

**Issue by StanFromTraction** [files-community/Files#13216]
### Description

If you have auto-hidden taskbar enabled and you open Files in the foreground, moving your mouse towards the bottom of the screen won't make the taskbar appear like in every other Windows program

### Steps To Reproduce

1. Enbale auto-hidden taskbar
2. Try making it show up when the Files window in in the foregroung

### Requirements

- Fix bug that breaks auto-hidden taskbar

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2134

### Log File

- Fix bug that breaks auto-hidden taskbar

**Comment by gave92** [comment]
Thank you for reporting this. The issue was fixed in #13207. Fix will be included in the next Files release.
