### ISSUE TITLE
Bug: Files scrolls to the top when window is refocus

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#13220]
### Description

*

### Steps To Reproduce

1. Open a scrollable directory
2. Scroll down
3. Click off the window
4. Click on the window
5. See scrolled to the top

### Requirements

- Keep scroll position

### Files Version

2.5.22.0

### Windows Version

10.0.22621.2134

### Log File

[debug.log](https://github.com/files-community/Files/files/12388912/debug.log)

**Comment by yaira2** [comment]
Thank you for reporting this issue

**Comment by yaira2** [comment]
This issue seems to be caused by `ScrollViewer_GotFocus` in `StickyHeaderBehavior.cs`.
