### ISSUE TITLE
Bug: Files fails all admin oprations

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#13229]
### Description

It will give the prompt to use admin then if given it will still fail.

### Steps To Reproduce

1. Copy a folder/file
2. Paste it into C:\Program Files
3. Give admin access on prompt
4. See copy failed

### Requirements

- Use admin when given

### Files Version

2.5.22.0

### Windows Version

10.0.22621.2134

### Log File

[debug.log](https://github.com/files-community/Files/files/12398301/debug.log)

**Comment by yaira2** [comment]
Thank you for reporting this issue, I can repro it in `main`.

**Comment by gave92** [comment]
Linking related PR #13043.
