### ISSUE TITLE
Use same transparency as tabs for left pane

### ISSUE THREAD

**Issue by trmnrs** [files-community/Files#13223]
### What feature or improvement do you think would benefit Files?

This will help establish the folder contents section as the main workspace while representing the left pane as a sidebar. Similar to how the Photos app implements this.
![image](https://github.com/files-community/Files/assets/113248914/2b4a3ebb-8c3d-463c-963a-b9c439470d72)

### Requirements

- Change BG opacity level to match tab strip and ribbon
- Remove line in between tab strip and ribbon from lower content
- Round off top left corner of folder contents section, above command bar
![Screenshot 2023-08-21 000039](https://github.com/files-community/Files/assets/113248914/fa76e228-6406-4d0f-b4a2-02bad686f9d7)

### Files Version

2.5.21.0

### Windows Version

10.0.23521.1000

**Comment by yaira2** [comment]
Thank you for your feedback, you can adjust the transparency of the pane by editing the settings file. For more information, see our documentation page on custom themes [https:f](https://files.community/docs/configuring/custom-themes).

**Comment by yaira2** [comment]
I also want to point out that a number of the suggestions you made are already implemented in the latest preview build.
