### ISSUE TITLE
Ability to adjust font size

### ISSUE THREAD

**Issue by tksuoran** [files-community/Files#13227]
### What feature or improvement do you think would benefit Files?

I am unable to locate setting to change the font size. Even setting in the json file would do fine. Thanks.

### Requirements

- This proposal will accomplish ability to change font size

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2134

**Comment by yaira2** [comment]
Thank you for your feedback, this isn't really feasible to do from our side as there are many different font sizes used throughout Files. However, Windows has a couple of different settings built into the OS exactly for this scenario. From the Windows Settings app, you can change the font size as well as the display scale.
