### ISSUE TITLE
New Folder in Pop Up not Working

### ISSUE THREAD

**Issue by sirinath** [files-community/Files#13239]
### Description

When the pop up menu extends to the top like this:
 
![image](https://github.com/files-community/Files/assets/637415/4c28b7d2-2761-4bdb-983c-7aa0166b76fd)

It does not work. 

It acts as if like clicking the window's title bar.

If it is slightly below like this:

![image](https://github.com/files-community/Files/assets/637415/bb9629d7-c220-4977-9f28-98b32c24b82c)

It works.

### Steps To Reproduce

Right click and open the pop up menu. 
Go to new
Then new folder

If the folder is above the top menu and ribbon, it does not work.

### Requirements

New Folder should create a new folder

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2134

### Log File

[debug.log](https://github.com/files-community/Files/files/12428434/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #10823. You can check there or click subscribe in the right sidebar for updates.

**Comment by Josh65-2201** [comment]
You can use the new toolbar option for now
