### ISSUE TITLE
Preflight file crashes

### ISSUE THREAD

**Issue by scottkimbler** [files-community/Files#13235]
### Description

it keeps crashing when having more than 4 tabs open.

### Steps To Reproduce

open multiple tabs and start searching it will close out.

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

2.5.21.0

### Windows Version

Edition	Windows 11 Pro Version	22H2 Installed on	‎7/‎18/‎2023 OS build	22621.2134 Serial number	5CD319HTTK Experience	Windows Feature Experience Pack 1000.22659.1000.0

### Log File

[debug.log](https://github.com/files-community/Files/files/12413202/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Can you try clearing your recent items list. Open Windows File Explorer > Click `...` > Options > Under privacy 'Clear'

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by yaira2** [comment]
@scottkimbler
