### ISSUE TITLE
Multiple OneDrive accounts

### ISSUE THREAD

**Issue by BruceTheBear5** [files-community/Files#13231]
### Description

My student OneDrive account does not show up as a separate cloud drive. Only the first (personal) drive shows up as a separate location. 

Files -> no separate location for second OneDrive account: 
![image](https://github.com/files-community/Files/assets/72066978/5beca0c9-cdd9-4933-9565-10380087691a)

### Steps To Reproduce

Add a second OneDrive account

![partial_blur](https://github.com/files-community/Files/assets/72066978/8d6cdc41-523f-4c85-8a35-cd092cc3144c)

### Requirements

Expected behaviour as in File Explorer:
(separate locations for personal and student OneDrive)

![partial_blur(1)](https://github.com/files-community/Files/assets/72066978/32714026-4163-45d6-9153-7d1db4c75e76)

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2134

### Log File

[debug.log](https://github.com/files-community/Files/files/12402747/debug.log)

**Comment by yaira2** [comment]
Thank you for the feedback, we're tracking a similar issue in #4966 so we're going to merge the two. Please subscribe to that issue to be notified when it's resolved.
