### ISSUE TITLE
Any way to remove "Focus Outline" ?

### ISSUE THREAD

**Issue by sepsol** [files-community/Files#13232]
### What feature or improvement do you think would benefit Files?

The focus outline feature makes it really hard and unsatisfying when trying to get things done with only the keyboard, it really makes it hard to read the folder names.

![image](https://github.com/files-community/Files/assets/47871887/0666ff8c-8bf6-44cc-b607-807caf8c8908)

### Requirements

- Add an accessibility section in the app settings where users can enable or disable this feature at will.

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2134

**Comment by Josh65-2201** [comment]
Thanks for the feedback, the focus outline is to show were you are in navigation. The better solution would be centering the text vertically so it doesn't overlap the focus outline. Can you see if this is an issue in the preview version. https://files.community/download

**Comment by Jay-o-Way** [comment]
> The better solution would be centering the text vertically so it doesn't overlap the focus outline

Yes, it's always best to keep any overrides to a minimum.

**Comment by yaira2** [comment]
The alignment issue was recently fixed in the preview version, I think this solves the visibility concern but I'll give @sepsol a chance to try it out for themselves to see if it resolves the issue.

**Comment by sepsol** [comment]
I tested the beta version and I must say it is indeed much better than the current stable version. But still, I don't appreciate the focus outline design in Windows 11, it stands out way too much. It would be great if it could optionally be disabled or if the outline could be replaced by a bluish (or theme color?) background and border like in default File Explorer.

**Comment by yaira2** [comment]
I can see where you're coming from, but when it comes to accessibility, we believe Files should be consistent with the latest design guidelines for WinUI. We're not against adding an option if there is enough interest, but at the moment, I don't see a way to do this without creating a custom style for every control.

**Comment by sepsol** [comment]
That makes sense @yaira2. Thank you for your insight and for prioritizing the consistency with the latest WinUI design guidelines, as a result, the app definitely feels very native to Windows. I appreciate the team's effort on this project. Cheers! 👍🏻
