### ISSUE TITLE
Feature: Request for an Option to Toggle Ejecting Removable Drives in the Sidebar

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#13244]
### What feature or improvement do you think would benefit Files?

I'd like to propose the addition of a feature that allows users to enable or disable the ejection of removable drives in the sidebar through the settings. This feature would help to declutter the sidebar, especially when dealing with numerous drives on a compact interface such as a laptop.

### Requirements

Integrating a toggle button in the settings for ejecting removable drives.

### Files Version

2.5.23.0

### Windows Version

22H2 22621.1992

**Comment by yaira2** [comment]
Thank you for your feedback. We don't have plans to implement this option now, but we're open to reconsidering this in the future.
