### ISSUE TITLE
Bug: Sidebar sections with only one child item expand slowly

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#13245]
### Description

I've noticed that when I expand the "Network" section in Files, it takes longer to unfold than before, and it lacks the animation during the expansion, unlike the other sections.

### Steps To Reproduce

1. Expand the "Network" section

### Requirements

Slower Network Section Expansion and Missing Animation in File Explorer.

### Files Version

2.5.23.0

### Windows Version

22H2 22621.1992

### Log File

No need.

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
This seems to happen with sections that only have one child item.

**Comment by Lukiluc29** [comment]
Yes

**Comment by Loveay19** [comment]
Dana kembali
