### ISSUE TITLE
Collapsing Opening a Collapsed File Type Scrolls to the Right Most Position  

### ISSUE THREAD

**Issue by sirinath** [files-community/Files#13242]
### Description

Collapsing Opening a Collapsed File Type Scrolls to the Right Most Position  

### Steps To Reproduce

Open from a collapsed position.

Start

![image](https://github.com/files-community/Files/assets/637415/a587ba4b-97fa-40c9-b2e3-375616def18f)

Collapse

![image](https://github.com/files-community/Files/assets/637415/3b9f46e8-465b-4888-9fb6-6f88eb8838b7)

Reopen

![image](https://github.com/files-community/Files/assets/637415/adc72cec-4187-4c65-aed6-248d7286ad2d)

### Requirements

Should remember the position before opening

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2134

### Log File

[debug.log](https://github.com/files-community/Files/files/12429483/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #13220. You can check there or click subscribe in the right sidebar for updates.
