### ISSUE TITLE
Feature: Request to Disable Status Center Display in Background Mode for Files

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#13243]
### What feature or improvement do you think would benefit Files?

I have a suggestion regarding the Files application. Could it be possible to prevent the status center from appearing when I open Files with the "Leave app running in the background when the window is closed" mode enabled? Sometimes, I don't want to see my previous actions. Typically, when we close an application, we don't necessarily want to review our previous activities.

### Requirements

Identify the user preference for the visibility of the status center in the background mode.

### Files Version

2.5.23.0

### Windows Version

22H2 22621.1992

**Comment by Josh65-2201** [comment]
Thanks for the feedback, I've added this to the project board.

**Comment by yaira2** [comment]
I'm on board with this change as long as there are no ongoing operations.
