### ISSUE TITLE
The Displayed New File Type Names and Not What is Displayed in Windows. Also the listed options differ. There are repeated items.

### ISSUE THREAD

**Issue by sirinath** [files-community/Files#13240]
### Description

The displayed New File Type Names and Not What is Displayed in Windows

![image](https://github.com/files-community/Files/assets/637415/0309e121-1d6b-406b-8e81-847f56cecb06)

The icons are missing too.

1 items is repeated.

![image](https://github.com/files-community/Files/assets/637415/fa93df1a-4a0e-4b31-913e-1cd5c17902ed)

### Steps To Reproduce

Right click in both and go to new.

### Requirements

- e.g. Fix crash that occurs when...
Showing more options is better but the names should be clean

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2134

### Log File

[debug.log](https://github.com/files-community/Files/files/12428508/debug.log)

**Comment by yaira2** [comment]
@sirinath thank you for the feedback, after looking into this further, it appears that it's an issue with the way those applications handle localization. It's possible to patch things up by editing the registry, but I don't know enough about those applications to be able to walk you through the changes.

**Comment by sirinath** [comment]
The issue are with file types of very common programs:
- Microsoft Office
- LibreOffice
- Google Drive

I am using UK English as my local with region as Sri Lanka.
