### ISSUE TITLE
Bug: Eject option isn't displayed for external hard drives

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#13250]
### Description

I'm encountering an issue with my external hard drive. When I right-click on the external hard drive, the "Eject" button is not appearing. Additionally, the "Eject" button is also missing from the sidebar.

### Steps To Reproduce

1. Right-click on the hard disk

### Requirements

Show "Eject" button in context menu.

### Files Version

2.5.23.0

### Windows Version

22H2 22621.1992

### Log File

![Capture d'écran 2023-08-25 185603](https://github.com/files-community/Files/assets/128183422/1d47ab9e-fe11-4b95-96f5-8d7041146c6f)
[debug.log](https://github.com/files-community/Files/files/12442106/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Can you please upload (Do not copy and paste content) the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.

**Comment by Lukiluc29** [comment]
> Thanks for the report, Can you please upload (Do not copy and paste content) the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.

Ok, I added the file.

**Comment by Josh65-2201** [comment]
Thanks, I've added this to the project board.

**Comment by Jay-o-Way** [comment]
I think this is the reason: a drive is a _partition_, and is not the same as a _device_. For example - I have an external USB hard drive with 3 partitions. If I eject the _device_ (via Windows) then all partitions are unavailable. In other words: what should happen if you eject one partition??
![image](https://github.com/files-community/Files/assets/65828559/505328f6-a7f6-4555-9386-2ba1c8a30248)

**Comment by Lukiluc29** [comment]
> I think this is the reason: a drive is a _partition_, and is not the same as a _device_. For example - I have an external USB hard drive with 3 partitions. If I eject the _device_ (via Windows) then all partitions are unavailable. In other words: what should happen if you eject one partition??

My hard drive only has one partition, but when I try to eject it, it tells me it's in use, but I don't know by what.

**Comment by Triangle-GitHub** [comment]
> 我认为这就是原因：驱动器是一个_分区_，与_设备_不同。例如 - 我有一个带有 3 个分区的外部 USB 硬盘驱动器。如果我弹出_设备_（通过 Windows），则所有分区都不可用。换句话说：如果弹出一个分区会发生什么？ ![image](https://private-user-images.githubusercontent.com/65828559/274624775-505328f6-a7f6-4555-9386-2ba1c8a30248.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNzYxNDQsIm5iZiI6MTcxNTA3NTg0NCwicGF0aCI6Ii82NTgyODU1OS8yNzQ2MjQ3NzUtNTA1MzI4ZjYtYTdmNi00NTU1LTkzODYtMmJhMWM4YTMwMjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDA5NTcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5ZmQ1MTMzNjk4ZTM3ZDRiNzhiMGMzMjNhZjI2YWZhNWE5Y2EyODliZDQzNDdkNWU0ZjY2NGYwZDM2MTYxZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VwQHylsRVa8Ce8GS5BLg_giAqIjTJw0FUdzLVEALh7c)

我认为问题不在这里，我尝试了给U盘分多个区，Files会在每个分区都显示弹出图标，而我点击任意一个分区的弹出，Files都会弹出U盘的所有分区。

**Comment by yaira2** [comment]
@Lukiluc29 a fix for the eject option failing is included in #16124. As for the option not appearing, can you confirm if this is still the case?

**Comment by Lukiluc29** [comment]
> @Lukiluc29 a fix for the eject option failing is included in #16124. As for the option not appearing, can you confirm if this is still the case?

This problem is still present in the latest version of Files
![Capture d'écran 2024-09-06 180242](https://github.com/user-attachments/assets/53388875-b9b9-426f-a864-5c82b6f94eac)

**Comment by yaira2** [comment]
Thank you for checking. We're going to continue tracking this in #10154 (the underlying issue is the same).
