### ISSUE TITLE
Bug: Crash after searching and returning to original folder

### ISSUE THREAD

**Issue by Eaglemaster10** [files-community/Files#13253]
### Description

Crashes after doing a search and leaving to another folder.

### Steps To Reproduce

Do a Search
Return to the original folder
Try another search or go to another folder.

### Requirements

- e.g. Fix crash that occurs when...
Fix the problem with searching

### Files Version

2.5.21.0

### Windows Version

Edition	Windows 11 Home Version	22H2 Installed on	‎2/‎27/‎2023 OS build	22621.2215 Experience	Windows Feature Experience Pack 1000.22662.1000.0

### Log File

[debug.log](https://github.com/files-community/Files/files/12445097/debug.log)

**Comment by sthivaios** [comment]
Files 2.5.21.0 on Windows 11 Enterprise Evaluation, doesn't seem to have this problem.

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by Eaglemaster10** [comment]
Ok. Got the preview. Seemed to search okay. But then after the search, I went to an archived ZIP file. It opened and the program froze. Had to force a quit. I tried several different searches and went to other folders and it seemed to work fine until I grouped by Type. Then it crashed again.

Ernest
________________________________

**Comment by yaira2** [comment]
@Eaglemaster10 can you update the steps to reproduce the issue to include this info?

**Comment by yaira2** [comment]
@Eaglemaster10 I'm not able to repro this on the latest preview (v2.5.33). If it's still occurring for you, please upload the log file for the preview version and we'll take another look.
