### ISSUE TITLE
Feature: Don't focus Files window when dragging a file/folder

### ISSUE THREAD

**Issue by abs-c** [files-community/Files#13255]
### What feature or improvement do you think would benefit Files?

When trying to drag a file (or folder) from a Files window to other window, the Files windows will be focused and automatically jump to the top, covering other window that was originally above. It will be better if the window could stay behind.

It is necessary for the app popping onto the top when clicking on it, or dragging on some empty spaces., title bar, etc.. However, it would be more convenient if it could stay behind when dragging on a single file or the files selected. (That's how windows files explorer behaves on this situation.)

### Requirements

- When dragging an item from an unfocused Files window, the window should not be focused, stay behind, until the item is finally drop to the original window.
- If some of the files have been selected, the window should stay behind when dragging on those files, but get to the top when dragging on other unselected files.

### Files Version

2.5.21.0

### Windows Version

10.0.22631.2262

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board. Also you can hover over the program when dragging to focus it.

**Comment by yaira2** [comment]
This improvement will be included in the next update.
