### ISSUE TITLE
Bug: Request for a Fixed Scroll Bar in the Sidebar for Improved User Experience

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#13262]
### Description

As I extensively work on a laptop, my narrow sidebar requires a scrollbar due to limited space. However, I've encountered an issue where the scrollbar remains active even when not hovered over or used. When I launch the Files application, the scrollbar is not initially visible, but as soon as I interact with the sidebar, it appears and does not disappear consistently. Sometimes, after interacting with it, it does vanish, but not consistently.

### Steps To Reproduce

1. Have a sidebar with lots of items so as to have a scrollbar

### Requirements

Identify the specific conditions causing the persistent scrollbar behavior.

### Files Version

2.5.24.0

### Windows Version

22H2 22621.1992

### Log File

<img width="200" alt="Capture d'écran 2023-08-27 201714" src="https://github.com/files-community/Files/assets/128183422/158f7fce-b87c-466c-b703-57497988e179">

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
@chingucoding is this intentional?

**Comment by Lukiluc29** [comment]
I want to inform you that I notice that this is not only happening on the sidebar.

**Comment by chingucoding** [comment]
I don't think that's intentional. @Lukiluc29 in your screenshot, would you be able to scroll content or is it being shown without anything that could be scrolled?

**Comment by yaira2** [comment]
@Lukiluc29

**Comment by Lukiluc29** [comment]
> I don't think that's intentional. @Lukiluc29 in your screenshot, would you be able to scroll content or is it being shown without anything that could be scrolled?

Sorry for the delayed response. No, there is no impact on the sidebar; it remains scrollable. It's just that when I start scrolling it and my mouse leaves the sidebar, logically, it should disappear, but in this case, it stays visible.

**Comment by chingucoding** [comment]
This seems more like a WinUI bug to be honest, since we set the scroll bar visibility to auto 🤔

**Comment by Lukiluc29** [comment]
> This seems more like a WinUI bug to be honest, since we set the scroll bar visibility to auto 🤔

What should be done then?

**Comment by yaira2** [comment]
@chingucoding can it be a focus issue?

**Comment by chingucoding** [comment]
This could be the case, in that case clicking somewhere else should make it disappear after some time though.

**Comment by Lukiluc29** [comment]
> This could be the case, in that case clicking somewhere else should make it disappear after some time though.

I've tested it hundreds of times, and it hasn't made any difference.
