### ISSUE TITLE
UI Not Refreshed after File change operation

### ISSUE THREAD

**Issue by sirinath** [files-community/Files#13266]
### Description

UI Not Refreshed after File operation

### Steps To Reproduce

Delete a file

Especially true if it is a zip file.

### Requirements

UI should remove the deleted file from display

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2134

### Log File

[debug.log](https://github.com/files-community/Files/files/12454654/debug.log)

**Comment by sirinath** [comment]
I am not sure if I want to install the pre view version. When it is released I can try it out.

**Comment by yaira2** [comment]
@sirinath you can install it alongside the stable version, we believe the issue is already resolved but it'll help if you can confirm.

**Comment by sirinath** [comment]
This seams to be OK in the preview.
