### ISSUE TITLE
Problem with the taskbar

### ISSUE THREAD

**Issue by Capochin** [files-community/Files#13268]
### Description

Hi, the problem in this case is the taskbar when Files is maximized, I configured the taskbar to auto-hide, but the problem happens when Files is maximized and the taskbar is not displayed, it crashes. It's like being in full screen of a video game. I tried the "insider preview" version and it worked correctly.

### Steps To Reproduce

1-Turn on "automatically hide the taskbar" in windows options
2-Go to Files, maximize the window in a random directory
3-Try to move the mouse on the taskbar 

### Requirements

- e.g. Fix crash that occurs when...
I try to look the taskbar with the mouse when the window is maximized

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2215

### Log File

[debug.log](https://github.com/files-community/Files/files/12457607/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, this is fixed in the preview version https://files.community/download. There no timeline for it being on stable.
