### ISSUE TITLE
Open File Location Feature Request

### ISSUE THREAD

**Issue by ZehanWangAlbert** [files-community/Files#13263]
### What feature or improvement do you think would benefit Files?

In Windows search bar, when you type the name of a file or a program, the option “Open File Location“ shows up, but when you click it, the Files app opened, and opened at the root of C:\ drive (In my case).
One feature I wanted, is to properly open to the folder of that file, not to the C:\
Thank you.

### Requirements

- Probably update the navigation system of the Files app, to make it compatible with windows "Open File Location" feature.

### Files Version

2.5.24.0

### Windows Version

10.0.19045.3393

**Comment by Josh65-2201** [comment]
Please make a bug report as this isn't intended. Also include the file location of the item you are testing with
