### ISSUE TITLE
Bug: Textbox for renaming sometimes doesn't disappear after losing focus

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#13272]
### Description

This occurs when clicking on an empty space in the file list.

### Steps To Reproduce

1. Start renaming an item.
2. Click on an empty space in the file list.
3. The textbox doesn't disapper.

### Requirements

The textbox should disapper.

### Files Version

2.5.24.0

### Windows Version

10.0.19045.3324

### Log File

n/a

**Comment by yaira2** [comment]
Thank you for the feedback, is this a result of the fix for the scrolling issue when losing focus?

**Comment by hishitetsu** [comment]
> is this a result of the fix for the scrolling issue when losing focus?

I believe so.
