### ISSUE TITLE
Recent Crash

### ISSUE THREAD

**Issue by RichardMar** [files-community/Files#13270]
### Description

Crash when Tab Swiching

### Steps To Reproduce

Muti tabs open
Switch Tabs
Crash May occured

### Requirements

- e.g. Fix crash that occurs when switching tabs

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2134

### Log File

[debug.log](https://github.com/files-community/Files/files/12460468/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, I can't repro this in the latest preview, but it'll be good if you can confirm. Is this still an issue in the preview version? https://files.community/download/preview
