### ISSUE TITLE
When a Folder is Grouped by File Type, the File Type Headings Do Not Always Update

### ISSUE THREAD

**Issue by sirinath** [files-community/Files#13271]
### Description

When a Folder is Grouped by File Type, the File Type Headings Do Not Always Update.

E.g. instead of `Microsoft PowerPoint Presentation` it sometimes says ``pptx File`.

If you have 2 panes open, in one it may say `Microsoft PowerPoint Presentation` and the other pane it might say ``pptx File`.

### Steps To Reproduce

Keep opening folders with many file types.

Sometimes it fails to identify the descriptive time type. 

### Requirements

Be consistent. Use descriptive name.

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2134

### Log File

[debug.log](https://github.com/files-community/Files/files/12461089/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
Thank you for your feedback, we're going to continue tracking this in #14433.
