### ISSUE TITLE
Adding Resize Width to Split Column Display

### ISSUE THREAD

**Issue by shugo-chara** [files-community/Files#13275]
### What feature or improvement do you think would benefit Files?

The width of the list is fixed after it is set to split-column display. Long filename files will not display the full name. I would like to add resize width or adaptive width adjustment.

### Requirements

Adjusting the list width

### Files Version

2.5.24.0

### Windows Version

10.0.22621.2134

**Comment by yaira2** [comment]
Thank you for your feedback, support for resizing columns is on the todo list and is being tracked in #6534. You can click the subscribe button to be notified of updates on that issue.
