### ISSUE TITLE
Bug: Unable to perform network drive mapping

### ISSUE THREAD

**Issue by shugo-chara** [files-community/Files#13274]
### Description

When connecting to the NAS, whether using the network name, or the IP address, it prompts inaccessibility.
Error: 0x80070043
Cannot find network name

They have been accessing fine in explorer.

### Steps To Reproduce

1. Mapping network drives
2. Enter the address, account number and password
3.Error

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

2.5.24.0

### Windows Version

10.0.22621.2134

### Log File

[debug.log](https://github.com/files-community/Files/files/12462691/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
