### ISSUE TITLE
Bug: Issue with Column View Display in Git Repositories for Visual Studio Solution Files

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#13283]
### Description

I've encountered an issue where, when I navigate to a Git repository containing a Visual Studio solution file, nothing is displayed in column layout. This problem only occurs in the column layout, as the button is present and functional in the details layout.

### Steps To Reproduce

1. Select the column layout
2. Navigate to the Git repository containing the Visual Studio solution file

### Requirements

Check if the column view mode settings are correctly configured.

### Files Version

2.5.24.0

### Windows Version

22H2 22621.1992

### Log File

[debug.log](https://github.com/files-community/Files/files/12468726/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
This appears to be resolved in the latest preview.

**Comment by Lukiluc29** [comment]
It's not resolved on my end because the "Open in Visual Studio" button still doesn't appear in any layout.
![Capture d'écran 2023-10-26 102940](https://github.com/files-community/Files/assets/128183422/19fc70bb-0739-400f-9b82-46d170ce33fe)
![Capture d'écran 2023-10-26 103015](https://github.com/files-community/Files/assets/128183422/ef4ee42a-a132-4ffd-97af-9154032f6378)

**Comment by yaira2** [comment]
Can you share a screen recording? I'm having trouble reproducing this.

**Comment by Lukiluc29** [comment]
> Can you share a screen recording? I'm having trouble reproducing this.

https://github.com/files-community/Files/assets/128183422/b1a88938-e1f7-4e6a-846f-5d462e227932

**Comment by yaira2** [comment]
What happens if you open a new tab and navigate to the folder again?

**Comment by yaira2** [comment]
Can you reset the app and include opening the app in the screen recording? I want to make sure I am following the same steps.

**Comment by Lukiluc29** [comment]
> Can you reset the app and include opening the app in the screen recording? I want to make sure I am following the same steps.

https://github.com/files-community/Files/assets/128183422/a901ccef-0b64-4386-b0b4-6951dde28b93

**Comment by yaira2** [comment]
What happens if you select a folder in the Git repo?

**Comment by Lukiluc29** [comment]
> What happens if you select a folder in the Git repo?

It's same.
