### ISSUE TITLE
Bug: Option to initialize folder as Git repository isn't working

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#13280]
### Description

I recently tried using the Command Palette feature for the first time. While typing ">git" while being in a directory like "C:", I encountered an issue where Files crashed upon clicking "Initialize a Git Repository." This behavior shouldn't occur, and additionally, the created folder becomes hidden. Moreover, it might be beneficial to allow the creation of these folders only in the "repos" directory.

### Steps To Reproduce

1. Go to the "C:\" drive
2. Type ">git" in the address bar
3. Click on "Initialize to the Git repository"

### Requirements

Investigate and fix the crash that occurs when initializing a Git repository through the Command Palette.
Prevent the created folder from becoming hidden after initializing a Git repository.
Provide clear options to choose the target directory for creating Git repositories

### Files Version

2.5.24.0

### Windows Version

22H2 22621.1992

### Log File

[debug.log](https://github.com/files-community/Files/files/12466360/debug.log)

**Comment by yaira2** [comment]
As far as I'm aware, you should be able to initialize a drive root as a Git repo.

**Comment by ferrariofilippo** [comment]
> As far as I'm aware, there aren't any technical limitations on initializing drive roots as Git repos.

To initialize drive roots as Git repos, you should add `[safe] directories = *` in your `.gitconfig` file. Still, even using git from the CLI, you can't use those repos (I could neither `add` nor `commit`) since they are not `yours`. I tried both as a general user and as an admin, but it didn't work.

To fix the crash, we need to add a try-catch (and eventually an error modal)

**Comment by yaira2** [comment]
@ferrariofilippo do you want to work on this?

**Comment by ferrariofilippo** [comment]
I'll take that!
Is the modal fine?

**Comment by yaira2** [comment]
Is it possible to disable the action in advance? If not, a modal is fine..

**Comment by ferrariofilippo** [comment]
I'll disable the action in drive roots and I'll add a modal for other faulty paths (like WSL)
