### ISSUE TITLE
Select all Files in a Group

### ISSUE THREAD

**Issue by sirinath** [files-community/Files#13285]
### What feature or improvement do you think would benefit Files?

In Windows explorer you can select all files in a group by clicking the group name.

### Requirements

- Can you add button to collapse and expand
- Ability to select all files in group
- Select all files in multiple groups

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2134

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #9528. You can check there or click subscribe in the right sidebar for updates.
