### ISSUE TITLE
Bug: File selection commands don't appear in the command palette

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#13284]
### Description

File selection commands such as Select all, Clear selection, and Invert selection are already implemented, but they don't show up when the command palette is opened.

### Steps To Reproduce

1. Open a folder.
2. Open the command palette.
3. File selection commands don't appear.

### Requirements

File selection commands should show up when the command palette is opened.

- [ ] Select all
- [ ] Clear Selection
- [ ] Invert selection

### Files Version

2.5.24.0

### Windows Version

10.0.19045.3324

### Log File

n/a

**Comment by hishitetsu** [comment]
I think this is a Gool First Issue.

**Comment by whoscowboy** [comment]
Hi @yaira2 I would like to make this contribution. It will be my first. Could I have this assigned to me?

**Comment by HorseBandit** [comment]
@yaira2 May I please be assigned this issue? Thanks!

**Comment by Josh65-2201** [comment]
You can just open a pull request with the fix.

**Comment by HorseBandit** [comment]
Understood. Thanks Josh.
