### ISSUE TITLE
Use this files icon instead of the upcoming new files icon

### ISSUE THREAD

**Issue by foursplaysroblox** [files-community/Files#13289]
### What feature or improvement do you think would benefit Files?

In my opinion the new files icon is not nice in terms of colors because I do not really like a single color icon. 
For the preview and dev version there should be like that label "pre" and "dev" should be added back

### Requirements

- Changes the files app icon (preview and stable)
- or add a feature where you can use a custom files app icon and there will be default icon pack that includes the suggested files icon.

### Files Version

2.5.21.0 (Stable)

### Windows Version

10.0.25936.1000 (Windows 11 insider Preview Canary)

### Comments

![image](https://github.com/files-community/Files/assets/82078139/0660091c-cd4b-4ec9-bebf-b0a302cf3a0e)

**Comment by yaira2** [comment]
Thank you for your feedback, the feedback window for the new icon is complete and we'll be using the color palette that got the most votes.
