### ISSUE TITLE
I opened some new tabs, than while closing them, it crashed.

### ISSUE THREAD

**Issue by RobinCodestoGitHub** [files-community/Files#13297]
### Description

I opened like twenty tabs, which it handled perfectly, but then while closing 'em, it just crashed.

### Steps To Reproduce

Open a bunch of tabs (around twenty)
And close them quickly after each other

### Requirements

- e.g. Fix crash that occurs when...
The expected behavior is that it would just handle it, and close those tabs. 

### Files Version

2.5.24.0

### Windows Version

10.0.19045.3393

### Log File

[debug.log](https://github.com/files-community/Files/files/12484094/debug.log)

**Comment by yaira2** [comment]
@RobinCodestoGitHub can you clarify how you closed the tabs, was it with the `ctrl` + `w` shortcut?
