### ISSUE TITLE
In 2 Pannal Mode Please Highlight the Active Pannel

### ISSUE THREAD

**Issue by sirinath** [files-community/Files#13299]
### What feature or improvement do you think would benefit Files?

Currently the file bar shows a directory. Currently is it not easy to say which panel it relates to. This way we know which panel it relates to.

Also add the ability to have 2 directory bars.

### Requirements

- know what what panel is shown in the directory bar from
- highlighting the panel when one dir bar is shown
- by showing 2 dir bars

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2134

**Comment by yaira2** [comment]
@sirinath the bottom of the selected pane has a colored border, can you confirm if this is working for you?

**Comment by sirinath** [comment]
Ah Yes. It is working.

But this cannot be easily seen in dark mode when the scroll bar is active.

**Comment by sirinath** [comment]
Any way an option to have 2 title bars and searchers would be also great.

**Comment by yaira2** [comment]
Do you have a dark accent color? It's usually recommended to use a lighter accent color in dark mode.

**Comment by sirinath** [comment]
I am using the default. Did not change it.

I think Files can have a good present colour scheme depending on the mode.

**Comment by yaira2** [comment]
@sirinath thank you for the feedback. I can understand the frustration, but we can't account for every choice of accent. Otherwise, we would have to manually set every color and ignore the user's choice system wide.

A trick to match the path bar with the active panel is to look at the tab.
![image](https://github.com/files-community/Files/assets/39923744/f538a743-00fb-4d20-9352-e8262e8dbe5e)

**Comment by sirinath** [comment]
> but we can't account for every choice of accent. 

You need only 2. One for the light and other for the dark. If the user changes it then this is what will be used.

The full boarder of the active panel can be highlighted. Or at least both top and bottom.

![image](https://github.com/files-community/Files/assets/637415/a22cb3eb-4bcc-46af-b076-5e195fc4526b)

Currently only on the bottom:

![image](https://github.com/files-community/Files/assets/637415/0c5f0a39-8264-4f77-a61a-4bbd62160aea)

**Comment by yaira2** [comment]
Is the method of matching the tab title with the path bar working?

**Comment by sirinath** [comment]
I did not notice that before. Yes. It is also also is not working:

![image](https://github.com/files-community/Files/assets/637415/750392e7-f00a-4483-902a-fe69dd33621a)

The tab and dir is in sync above

![image](https://github.com/files-community/Files/assets/637415/2956ea84-3924-4f65-8f71-48143fd0b82f)

The tab is showing the other directory in the above.

**Comment by yaira2** [comment]
The tab shows both but it looks like it's getting cut off because of the long folder name.

**Comment by sirinath** [comment]
These are the names:
- A Comprehensive Course in Kannī Meditation
- 0008 - Hindrances 01 - Sensual Desire

In the latter case the tab should show "0008 - Hindrances 01 - Sensual Desire" or part of it, but it still shows a part of "A Comprehensive Course in Kannī Meditation", which is not the active panel.

**Comment by yaira2** [comment]
I see, in that case the tab isn't going to help with long names. Our recommendation is to use a lighter accent color so that the active pane stands out. We're also looking into the possibility of applying the color to all sides of the active pane, but we haven't finalized this yet.
