### ISSUE TITLE
Bug: Issue with File Preview for .ttf Files Since Office File Preview Implementation

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#13296]
### Description

Ever since the implementation of Office file previews, I've been encountering a problem with previewing .ttf files. I'm not certain if this issue is exclusive to this file type, but when I click on a .ttf file and access the preview pane, it displays strange in black-and-white.

### Steps To Reproduce

1. Click on the ttf. file
2. Open the preview pane

### Requirements

Ensure that the preview pane displays .ttf files accurately and coherently, as it does with other supported file formats.

### Files Version

2.5.25.0

### Windows Version

22H2 22621.1992

### Log File

<img width="190" alt="Capture d'écran 2023-08-31 100542" src="https://github.com/files-community/Files/assets/128183422/61940f6e-274e-4f42-bcb1-0af73394f9a3">

**Comment by yaira2** [comment]
@Lukiluc29 thank you for reporting this issue. I'm not sure we'll be able to fully solve this issue, but I can at least disable the shell preview to avoid the unexpected behavior. Please let us know if you notice this with any other file formats.
