### ISSUE TITLE
Bug: "File in use" error when deleting item open in preview pane

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#13302]
### Description

Trying to delete an item when it's being previewed via it's shell extension displays a file in use error.

### Steps To Reproduce

1. Open preview pane for office document
2. Try deleting the file

### Requirements

- Allow deleting files, even when they are being previewed.

### Files Version

v2.5.25

### Windows Version

Windows 11

### Log File

NA

**Comment by hishitetsu** [comment]
I am unable to reproduce it. I installed Microsoft 365 Apps for enterprise, opened .xlsx file in the preview pane, and deleted it. It worked fine.

**Comment by yaira2** [comment]
It's not either happening for me anymore
