### ISSUE TITLE
Bug: Leave app running cannot be started by specifying a location to open

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#13303]
### Description

If you enter "files C:" on the command line, the launched Files should open the C drive, but if leave app running is on, it will only open tabs according to the launch settings and will not open the C drive. This is also true if Files is the default file manager.

### Steps To Reproduce

1. Turn on leave app running.
2. Close the app.
3. Enter "files C:" on the command line.
4. The app will not open the C drive.

### Requirements

Open appropriate tabs as if leave app running were off.

### Files Version

2.5.25.0

### Windows Version

10.0.19045.3324

### Log File

n/a

**Comment by yaira2** [comment]
Thank you for reporting this issue.
