### ISSUE TITLE
Blur Icons 

### ISSUE THREAD

**Issue by sirinath** [files-community/Files#13305]
### Description

![image](https://github.com/files-community/Files/assets/637415/dccb9b1a-f163-478d-9a99-85b2bf54a7b5)

### Steps To Reproduce

None

### Requirements

No blur

### Files Version

2.5.24.0

### Windows Version

10.0.22621.2215

### Log File

[debug.log](https://github.com/files-community/Files/files/12495431/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, we're tracking a similar issue in #10067. You can click the subscribe button in that issue to be notified when the issue is resolved.
