### ISSUE TITLE
Show folder size in list view

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#1330]
**Is your feature request related to a problem? Please describe.**
Not really. Today, the folder size is only shown in properties and not in the list view. It'd be great if the size is shown in the list view.

**Describe the solution you'd like**
Add an optional feature that shows the size of a folder in the list view. It shouldn't be turned on by default.

**Describe alternatives you've considered**
None.

**Comment by XPoppyX** [comment]
Will it not affect performance? Or is the current calculation method sufficiently optimized?

**Comment by Jaiganeshkumaran** [comment]
> Will it not affect performance? Or is the current calculation method sufficiently optimized?
It obviously will. However, we can optimize the calculation and we can make this optional.

**Comment by yaichenbaum** [comment]
While this would affect performance, it's worth looking into how much it will be affected.
