### ISSUE TITLE
Feature: Support for starting tag search from details pane

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#13316]
### What feature or improvement do you think would benefit Files?

I propose adding a feature where, upon clicking an already assigned label in the preview pane, it displays all other items with the same label, similar to the behavior of label widgets where clicking the name displays all other item with the same label. Interacting with them in that manner would be a clever approach.

### Requirements

When clicking on the tag in the details pane, start a search for the tag.

### Files Version

2.5.25.0

### Windows Version

22H2 22621.1992

### Comments

![Capture d'écran 2023-09-02 163523](https://github.com/files-community/Files/assets/128183422/e531cf1d-2c58-4e99-9406-9a4d1c345831)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, I've added this to the project board.

**Comment by yaira2** [comment]
This feature will be available in the next update
