### ISSUE TITLE
Bug: Can't tags in the tag widget doesn't open them

### ISSUE THREAD

**Issue by Pietro228** [files-community/Files#13315]
### Description

Hi,

I can't left click my tags in Home and only right click works.

### Steps To Reproduce

1. Open Home page
2. Click Tag
3. Nothing happens

### Requirements

Make tags again clickable.

### Files Version

2.5.25.0

### Windows Version

10.0.22631.2265

### Log File

[debug.log](https://github.com/files-community/Files/files/12503874/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I'm unable to reproduce this. What are you trying to open in the tag widget?

**Comment by Pietro228** [comment]
Yes I'm trying to open them here
![obrazek](https://github.com/files-community/Files/assets/53868994/03bd1360-3d1a-475c-b3d4-98c73ce70230)

**Comment by Josh65-2201** [comment]
- Are those folders on network drives?
- Can you open them by navigating normally in Files?

**Comment by Pietro228** [comment]
1. No they are not.
2. Yes I can. Also I can just right click them and click "Open in a new tab"

**Comment by yaira2** [comment]
@Pietro228 is this still an issue in v3.0.3? If it is, can you upload the updated log file?

**Comment by Pietro228** [comment]
@yaira2 Sorry for my late response, I must've overlooked it :/ It works without any problems! Thanks
