### ISSUE TITLE
Jar files

### ISSUE THREAD

**Issue by illuminator3** [files-community/Files#13312]
### What feature or improvement do you think would benefit Files?

Being able to open jar files just like zip files, as they are just zip files in disguise

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2134

**Comment by Josh65-2201** [comment]
Thanks for the feedback, this has already been made and will be included in the next update.
