### ISSUE TITLE
"Drives" disappear from Sidebar and Quick Access

### ISSUE THREAD

**Issue by joe12south** [files-community/Files#13317]
### Description

Some time after launching, seemingly randomly, the "Drives" section of the sidebar and Quick Look area display nothing. (Yes, the drives are actually still mounted.) Opening and closing window doesn't help, but ending the task and relaunching the app does cause drives to reappear.

### Steps To Reproduce

Cannot determine steps to reliably reproduce. It happens consistently after some amount of use, but unsure what exactly triggers the bug. Ending Files tasks and relaunching the app temporarily resolves the issue, but it will start misbehaving again.

### Requirements

- e.g. Fix crash that occurs when...
System drives should always display correctly. 

### Files Version

2.5.23.0

### Windows Version

10.0.22621.2134

### Log File

[debug.log](https://github.com/files-community/Files/files/12504476/debug.log)
![Screenshot 2023-09-02 124143](https://github.com/files-community/Files/assets/967135/842c41b9-dc4c-4ce4-bf2d-dbce0d2fddcf)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
@joe12south does this issue also occur in v2.5.25?

**Comment by yaira2** [comment]
@joe12south
