### ISSUE TITLE
Bug: The placeholder for the shell extension submenu sometimes do not disappear

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#13329]
### Description

Some shell extensions appear on the main menu when I hold down the Shift key and right-click to open the context menu.
However, if the number of shell extensions is small and all shell extensions can be displayed on the main menu, the placeholder for the shell extension submenu will remain visible.
![image](https://github.com/files-community/Files/assets/66369541/15b657f0-5215-430a-b15d-6495fee22b9e)

### Steps To Reproduce

1. Right-click an item with holding down the Shift key.
2. You will see the placeholder for the shell extension submenu will remain visible if the number of shell extensions is small.

### Requirements

The placeholder should disappear once shell extensions are loaded.

### Files Version

2.5.25.0

### Windows Version

10.0.22621.2134

### Log File

n/a

**Comment by yaira2** [comment]
Thank you for reporting this issue, is this also present in v2.5.21?

**Comment by hishitetsu** [comment]
> Thank you for reporting this issue, is this also present in v2.5.21?

Yes
