### ISSUE TITLE
Bug: The font color sometimes doesn't change after changing the theme

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#13325]
### Description

Once a flyout is displayed, changing the theme doesn't change the font color.
![image](https://github.com/files-community/Files/assets/66369541/d0a3347b-eb43-4aaf-bd9b-278881bb25ff)

Restarting the app fixes it.

### Steps To Reproduce

1. Open a flyout.
2. Go to the settings.
3. Change the theme and close the settings dialog.
4. Open a flyout again.
5. You will see the font color doesn't change.

### Requirements

The font color should follow the theme settings.

### Files Version

2.5.25.0

### Windows Version

10.0.19045.3324

### Log File

n/a

**Comment by yaira2** [comment]
I think this is also a WinAppSdk issue

**Comment by hishitetsu** [comment]
Is this written anywhere as a known issue? This is about CommandBarFlyout, not MenuFlyout.

**Comment by hishitetsu** [comment]
I found that this also happens in 2.5.21.0. Therefore, it is not an effect of updating WASDK to 1.4, at least.

**Comment by yaira2** [comment]
It's an older issue, we might be able to find a workaround but I don't think we need to track this on our repo.

**Comment by hishitetsu** [comment]
I see, it may not be necessary to actively fix the issue, but I think it is better to leave it open so that others do not open the same issue.

**Comment by yaira2** [comment]
@hishitetsu there is an issue on the WinUI repo https://github.com/microsoft/microsoft-ui-xaml/issues/4970
