### ISSUE TITLE
Explorer Style Navigation Panel

### ISSUE THREAD

**Issue by sirinath** [files-community/Files#13323]
### What feature or improvement do you think would benefit Files?

Add explorer style navigation panel

### Requirements

Currently we don't have the file tree open in the side panel.

You can jump from folder to folder in the file tree.

### Files Version

2.5.24.0

### Windows Version

10.0.22621.2215

**Comment by yaira2** [comment]
Thank you for your feedback, we're tracking this request in #1928.

**Comment by yair100** [comment]
@sirinath Tree View is currently available in preview https://files.community/download. It will be included in the next stable release.
