### ISSUE TITLE
Bug: Flyout submenus ignore theme settings in Files

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#13324]
### Description

When Windows theme is set to light and Files theme is set to dark, context menus are displayed in dark theme but its submenus are displayed in light theme.
![image](https://github.com/files-community/Files/assets/66369541/4adf303d-a4a1-4509-ae36-03ef92e90402)

This does not occur with 2.5.21.0, so this may be an effect of upgrading to WinAppSDK 1.4.

### Steps To Reproduce

As stated in the description.

### Requirements

All UI elements should follow theme settings in Files.

### Files Version

2.5.25.0

### Windows Version

10.0.19045.3324

### Log File

n/a

**Comment by yaira2** [comment]
I think this is a WinAppSdk issue, if I recall correctly they listed this as one of the known issues for 1.4.

**Comment by hishitetsu** [comment]
It certainly listed.
https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel#version-14
> MenuFlyout background doesn't use the application's requested theme:
