### ISSUE TITLE
Moving files requiring administrator privileges causes the application to restart.

### ISSUE THREAD

**Issue by A-Right-Git** [files-community/Files#13328]
### Description

As told in the title.

### Steps To Reproduce

To get the copy to fail:
1. Copy file
2. Go to Windows/Literally Anything
3. Paste.

The process will start, fail, and in Ongoing Tasks the attempt will be recorded and highlighted in red.

To get the app to crash:
1. Click and hold a file.
2. Drag to Windows/Literally Anything
3. Paste...

And watch the app restart itself.

### Requirements

- e.g. Fix crash that occurs when...
Should paste admin priv files without errors and crashes.

### Files Version

2.5.21.0

### Windows Version

10.0.19045.3208

### Log File

[debug.log](https://github.com/files-community/Files/files/12516006/debug.log)

We could start a fire with this.
Get it?
Logs?

aha.

**Comment by yaira2** [comment]
File operations requiring admin privileges will prompt you to elevate the app starting in the next version of Files.
