### ISSUE TITLE
Sometimes the Favorites doesn't open.

### ISSUE THREAD

**Issue by fangoward** [files-community/Files#13338]
### Description

I use the Favorites a lot, to open Downloads, Desktop or other important folders, but sometimes when I open Files it  does't open, not even if we press the star icon. It's like nothing's there. 
Sometimes if I wait a couple minutes they show up, others I have to restart it completely. 

### Steps To Reproduce

1. Open the program and "have luck" that that will happen.

### Requirements

...

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2134

### Log File

[debug.log](https://github.com/files-community/Files/files/12536371/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, 
- Is there any errors? 
- What do you mean doesn't open? As it sound like your trying to pin a folder.

**Comment by fangoward** [comment]
No errors. 

The favorites aren't there, they don't show up when I open the program.

**Comment by Josh65-2201** [comment]
Can you send a screenshot of your favorites from Windows File Explorer

**Comment by fangoward** [comment]
On Windows File Explorer they're showing up always. On Files they are not showing: https://ibb.co/Bz4KdBQ

**Comment by Josh65-2201** [comment]
I know I'm asking for a screenshot of your favorites in Windows File Explorer not Files

**Comment by fangoward** [comment]
They're just the default folders from Windows.

**Comment by Josh65-2201** [comment]
This seems to be the same as #13116. You can check there or click subscribe in the right sidebar for updates.
