### ISSUE TITLE
Tags lost

### ISSUE THREAD

**Issue by elicec** [files-community/Files#13337]
### Description

network filesystem win sshfs. 

add a path to tags 165
![image](https://github.com/files-community/Files/assets/9591680/720d9ea9-b262-4506-977a-96c4ac2d15db)

I can see it in tags 165
![image](https://github.com/files-community/Files/assets/9591680/0074e595-9248-45e2-ab4f-0d026dbe5205)

after  while  it losts
![image](https://github.com/files-community/Files/assets/9591680/5ed50ed9-792d-4179-89be-c3745be971d6)

### Steps To Reproduce

1. add a path to a tags
2. after  few seconds , the  path in tags lost 

### Requirements

- e.g. Fix crash that occurs when...
It is  network  filesystem : win sshfs  https://github.com/winfsp/sshfs-win

### Files Version

2.5.21.0

### Windows Version

10.0.19045.3324

### Log File

I see the log ,it has nothing

**Comment by gave92** [comment]
Thanks for the report. Tags are only supported on NTFS. Should probably disallow creation on other FS.

**Comment by yaira2** [comment]
We should definitely disable it on unsupported file systems. I think this is being tracked in another issue.
