### ISSUE TITLE
Feature: Add support for .lzh archives

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#13330]
### What feature or improvement do you think would benefit Files?

.lzh was once the most popular archive format in Japan and is still occasionally seen in Japan.
Microsoft supported it until Windows 10 version 1607, but the support was removed after 1703.
If supported by Files, this would be convenient because it would eliminate the need for other archivers.
7-zip can extract files from .lzh but can't compress files to .lzh, so this support will be limited to extraction only.

### Requirements

Add a feature to extract files from .lzh

### Files Version

2.5.25.0

### Windows Version

10.0.19045.3324

**Comment by yaira2** [comment]
Thank you for your feedback, I'll work on this.
