### ISSUE TITLE
Libraries-feature [from Mocris File-Explorer] missing (in the Files-app)

### ISSUE THREAD

**Issue by miller3d09** [files-community/Files#13345]
### What feature or improvement do you think would benefit Files?

The libraries-feature is a very neat feature, because it is very useful. 

### Requirements

Hence, 'i' (& certainly many other present File-explorer-users) will merely be able to move-on from its sluggish performance (& crazy Mocris-managements' GUI-decisions) WHEN the libraries-feature (in ie. "Files") can be made available. 

### Files Version

2.5.21.0

### Windows Version

11

### Comments

[![image](https://github.com/files-community/Files/assets/4425150/b7e70a63-d166-423a-a186-9c8a14d15741)](https://www.elevenforum.com/attachments/libraries_on_navigation_pane_in_file_explorer-png.27241/)

**Comment by Josh65-2201** [comment]
This already exists, Right click the blank space in the sidebar.

**Comment by miller3d09** [comment]
Thanks.
