### ISSUE TITLE
Bug: The path bar displays wrong location when restarting the app

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#13340]
### Description

When background running is off, the path bar displays wrong location when restarting the app. For example, when the C drive is opened, the path bar displays OneDrive as the location.
![image](https://github.com/files-community/Files/assets/66369541/6e2f5547-ec20-4f8d-a0b9-e703746cddea)

### Steps To Reproduce

1. Set leave app running to off.
2. Open the C drive.
3. Close the app.
4. Restart the app.
5. The app will open the C drive, but the path bar will display OneDrive as the location.

### Requirements

Display right location.

### Files Version

2.5.29.0

### Windows Version

10.0.19045.3324

### Log File

n/a

**Comment by yaira2** [comment]
Thank you for reporting this issue.
