### ISSUE TITLE
Files App not Working

### ISSUE THREAD

**Issue by whalenspeed** [files-community/Files#13343]
[debug.log](https://github.com/files-community/Files/files/12551125/debug.log)
### Description

When viewing files, I cannot see the picture preview, then I receive an error message to report this issue. 

### Steps To Reproduce

click on files
open pic folder
get error message

### Requirements

have the files app function

### Files Version

unknown, downloaded 09/07/2023 from microsoft store

### Windows Version

Windows 11 Home

### Log File

Unavailable

**Comment by Josh65-2201** [comment]
Thanks for the report, Can you give the following information
- Files version. You can get it from Files Settings > About
- Can you please upload (Do not copy and paste content) the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.
- What's the error you get?
- What do you mean by picture preview. Are you using the preview pane, thumbnail or something else?

**Comment by whalenspeed** [comment]
Files, Version 2.5.21.0

**Comment by whalenspeed** [comment]
What do you mean by picture preview. Are you using the preview pane, thumbnail or something else? When I look at my pictures folder, with hundreds of blue file folders, it briefly loaded the picture preview, then immediately reverts to the blue folder icon. I need to see the picture.  Not sure if this is a setting problem, default windows setting, I am not sure.  This is a solution to view picture and vids from an external hard drive

**Comment by Josh65-2201** [comment]
Thumbnails are made by the default program that opens them, Files doesn't make them.

**Comment by whalenspeed** [comment]
same thing, that's why I thought the app would work

**Comment by Josh65-2201** [comment]
Unfortunately not, you need a program that can make the thumbnails.

**Comment by Josh65-2201** [comment]
Refunds are handled by Microsoft you will have to look at contacting them

**Comment by yaira2** [comment]
It sounds like a different issue, you mentioned the thumbnails show briefly before disappearing?

**Comment by yaira2** [comment]
It sounds like a different issue, you mentioned the thumbnails show brefily before disappearing?

**Comment by whalenspeed** [comment]
It was a setting or not a setting. I opened the file options in windows and
restored defaults and problem solved. Never thought to restore defaults
when I never made changes and everything looked correct.

Best Regards,
Heather

**Comment by yaira2** [comment]
That's good to hear, is everything working in Files as well?
