### ISSUE TITLE
Windows explorer also open when I open file location from browser or any other app

### ISSUE THREAD

**Issue by Skolap** [files-community/Files#13351]
### Description

I set Files App as default, but when I try to open file location from any other app, Files App open but after some second windows explore also opens.

App Version: 2.5.21.0 (Tried on Store and Appx version)
OS: windows 10 21H2 Build 19044.3324 Enterprise LTSC

### Steps To Reproduce

Set Files app ad Default.
Download any file from broeser.
Open file location

### Requirements

Only Files App should be open and not windows Explorer

### Files Version

2.5.21.0

### Windows Version

windows 10 21H2 Build 19044.3324 Enterprise LTSC

### Log File

[debug.log](https://github.com/files-community/Files/files/12576374/debug.log)

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by yaira2** [comment]
@Skolap
