### ISSUE TITLE
Crashing when running as administrator

### ISSUE THREAD

**Issue by QwerkyPengwen** [files-community/Files#13354]
### Description

Issue is, I want to run Files as admin because I need it to have the same elevated privileges as another application to be able to drag and drop files between them.
Unfortunately running as admin and trying to click and hold on a file to drag it crashes and restarts the app.

### Steps To Reproduce

1. Run Files as administrator.
2. Click and drag on any file to start moving it.

### Requirements

- e.g. Fix crash that occurs when...
You try to drag and drop items while the program is running as admin.

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2134

### Log File

[debug.log](https://github.com/files-community/Files/files/12581851/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Drag and drop doesn't work in admin due to a Windows limitation.

**Comment by yaira2** [comment]
This issue is resolved in the latest preview build https://files.community.
