### ISSUE TITLE
Code Quality: Break down service registration in App.xaml.cs into granular methods

### ISSUE THREAD

**Issue by HorseBandit** [files-community/Files#13350]
### Description

All Dependency Injection configurations are inside a single method. The ConfigureHost() method is becoming cumbersome and less manageable as services are added. I recommend an abbreviated ConfigureHost() method:

private IHost ConfigureHost()
{
    return Host.CreateDefaultBuilder()
        .UseEnvironment(ApplicationService.AppEnvironment.ToString())
        .ConfigureLogging( /* ... */ )
        .ConfigureServices(ConfigureServices) // This is where the specific registration methods get called**
        .Build();
}

and improved orchestration and navigation offered by the following:

private void ConfigureServices(IServiceCollection services)
{
    // General services
    RegisterGeneralServices(services);
    
    // Storage services
    RegisterStorageServices(services);
    
    // ViewModel services
    RegisterViewModelServices(services);
    
    // Additional services
    RegisterAdditionalServices(services); // If you have more services to add
}

private void RegisterGeneralServices(IServiceCollection services)
{
    services.AddSingleton<IUserSettingsService, UserSettingsService>();
    // ... other general services
}

private void RegisterViewModelServices(IServiceCollection services)
{
    services.AddSingleton<MainPageViewModel>();
    // ... other ViewModel services
}

// other services

### Concerned code

File: App.xaml.cs
		
		private IHost ConfigureHost()
		{
			return Host.CreateDefaultBuilder()
				.UseEnvironment(ApplicationService.AppEnvironment.ToString())
				.ConfigureLogging(builder => builder
					.AddProvider(new FileLoggerProvider(Path.Combine(ApplicationData.Current.LocalFolder.Path, "debug.log")))
					.SetMinimumLevel(LogLevel.Information))
				.ConfigureServices(services => services
					.AddSingleton<IUserSettingsService, UserSettingsService>()
					.AddSingleton<IAppearanceSettingsService, AppearanceSettingsService>(sp => new AppearanceSettingsService((sp.GetService<IUserSettingsService>() as UserSettingsService).GetSharingContext()))
					.AddSingleton<IGeneralSettingsService, GeneralSettingsService>(sp => new GeneralSettingsService((sp.GetService<IUserSettingsService>() as UserSettingsService).GetSharingContext()))
					.AddSingleton<IFoldersSettingsService, FoldersSettingsService>(sp => new FoldersSettingsService((sp.GetService<IUserSettingsService>() as UserSettingsService).GetSharingContext()))
					.AddSingleton<IApplicationSettingsService, ApplicationSettingsService>(sp => new ApplicationSettingsService((sp.GetService<IUserSettingsService>() as UserSettingsService).GetSharingContext()))
					.AddSingleton<IPreviewPaneSettingsService, PreviewPaneSettingsService>(sp => new PreviewPaneSettingsService((sp.GetService<IUserSettingsService>() as UserSettingsService).GetSharingContext()))
					.AddSingleton<ILayoutSettingsService, LayoutSettingsService>(sp => new LayoutSettingsService((sp.GetService<IUserSettingsService>() as UserSettingsService).GetSharingContext()))
					.AddSingleton<IAppSettingsService, AppSettingsService>(sp => new AppSettingsService((sp.GetService<IUserSettingsService>() as UserSettingsService).GetSharingContext()))
					.AddSingleton<IFileTagsSettingsService, FileTagsSettingsService>()
					.AddSingleton<IPageContext, PageContext>()
					.AddSingleton<IContentPageContext, ContentPageContext>()
					.AddSingleton<IDisplayPageContext, DisplayPageContext>()
					.AddSingleton<IWindowContext, WindowContext>()
					.AddSingleton<IMultitaskingContext, MultitaskingContext>()
					.AddSingleton<ITagsContext, TagsContext>()
					.AddSingleton<IDialogService, DialogService>()
					.AddSingleton<IImageService, ImagingService>()
					.AddSingleton<IThreadingService, ThreadingService>()
					.AddSingleton<ILocalizationService, LocalizationService>()
					.AddSingleton<ICloudDetector, CloudDetector>()
					.AddSingleton<IFileTagsService, FileTagsService>()
					.AddSingleton<ICommandManager, CommandManager>()
					.AddSingleton<IModifiableCommandManager, ModifiableCommandManager>()
					.AddSingleton<IApplicationService, ApplicationService>()
#if UWP
					.AddSingleton<IStorageService, WindowsStorageService>()
#else
					.AddSingleton<IStorageService, NativeStorageService>()
#endif
					.AddSingleton<IFtpStorageService, FtpStorageService>()
					.AddSingleton<IAddItemService, AddItemService>()
#if STABLE || PREVIEW
					.AddSingleton<IUpdateService, SideloadUpdateService>()
#else
					.AddSingleton<IUpdateService, UpdateService>()
#endif
					.AddSingleton<IPreviewPopupService, PreviewPopupService>()
					.AddSingleton<IDateTimeFormatterFactory, DateTimeFormatterFactory>()
					.AddSingleton<IDateTimeFormatter, UserDateTimeFormatter>()
					.AddSingleton<IVolumeInfoFactory, VolumeInfoFactory>()
					.AddSingleton<ISizeProvider, UserSizeProvider>()
					.AddSingleton<IQuickAccessService, QuickAccessService>()
					.AddSingleton<IResourcesService, ResourcesService>()
					.AddSingleton<IJumpListService, JumpListService>()
					.AddSingleton<IRemovableDrivesService, RemovableDrivesService>()
					.AddSingleton<INetworkDrivesService, NetworkDrivesService>()
					.AddSingleton<MainPageViewModel>()
					.AddSingleton<PreviewPaneViewModel>()
					.AddSingleton<SidebarViewModel>()
					.AddSingleton<SettingsViewModel>()
					.AddSingleton<DrivesViewModel>()
					.AddSingleton<NetworkDrivesViewModel>()
					.AddSingleton<OngoingTasksViewModel>()
					.AddSingleton<AppearanceViewModel>()
					.AddSingleton<IJsonValidator, JsonIntegrityChecker>()
				).Build();
		}

### Gains

Breaking down service registration into smaller, focused methods improves the code's organization, readability, and maintainability. 

### Requirements

Refactoring IHost ConfigureHost()

**Comment by 0x5bfa** [comment]
That would not be delightful, I believe. and I think where we register services must be the same method, the same class to avoid confusion. And also to fix this situation, I am going to introduce **AppLifecycleHelper** static helper class containg this too. That helper provides some methods that should be away from App class.

**Comment by HorseBandit** [comment]
@0x5bfa What's the state of this issue? I can refactor service registration immediately and we can close this issue. Please let me know.

**Comment by 0x5bfa** [comment]
@yaira2 can you move to Ready to Build?

Once approved, you would like to create AppLifecyleHelper class in App.Helpers namespace, and put configuration class to there.

**Comment by HorseBandit** [comment]
@0x5bfa Okay. This means I need to write the AppLifecycleHelper class in App.Helpers. I'll put the service registration methods there. Do I understand correctly?

**Comment by 0x5bfa** [comment]
Yes.

**Comment by yaira2** [comment]
@HorseBandit we're discussing this proposal and will let you know if we decide to move forward with it.

**Comment by d2dyno1** [comment]
It looks good! But I'd separate it into its own static helper class (`ServiceRegistrationHelpers`) to keep the code clean in App.xaml.cs

**Comment by 0x5bfa** [comment]
yes id suggested him to. @d2dyno1. but for now, we can put all static classes should be moved in the same class from App class
