### ISSUE TITLE
Multiple SharePoint organizations sync

### ISSUE THREAD

**Issue by mladen-mysynergy** [files-community/Files#13356]
### Description

I have following OneDrive synced folders:

- Personal OneDrive
- Work OneDrive
- Multiple folders from my work SharePoint
- External organization SharePoint site synced
Unfortunately I do not see my work organization SharePoint in Cloud Drives but only the external one because it was added last I think.

### Steps To Reproduce

1. Sync folder from 1 SharePoint organization
2. Sync folder from 2nd SharePoint organization
3. First SharePoint organization is not seen in Cloud Drives menu

### Requirements

- e.g. Fix crash that occurs when...
add ability to show multiple SharePoint organizations in Cloud Drives.

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2215

### Log File

[debug.log](https://github.com/files-community/Files/files/12584380/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #4966. You can check there or click subscribe in the right sidebar for updates.
