### ISSUE TITLE
Windows 11 urls and other shortcuts cannot be seen

### ISSUE THREAD

**Issue by bw889** [files-community/Files#13353]
### Description

Windows 11 urls and other shortcuts cannot be seen although they are in the folder because if you try again to move a url or shortcut it asks if you want to replace. 

### Steps To Reproduce

Create shortcut
Drag or copy / paste to folder

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

10.0.22621.2134

### Windows Version

11

### Log File

[debug.log](https://github.com/files-community/Files/files/12577920/debug.log)

**Comment by yaira2** [comment]
Thank you for the report, is this by any chance on a network drive?

**Comment by bw889** [comment]
No, standalone

**Comment by bw889** [comment]
Files Version
10.0.22621.2134

Some shortcuts are shortcuts to files on the hard drive, inside the OneDrive folder .... C:\Users\NAME\OneDrive\ .....
With urls I can drag them from a browser they just don't appear

**Comment by Josh65-2201** [comment]
> 10.0.22621.2134

Thats not the Files version this is a Windows version number

**Comment by bw889** [comment]
Oh sorry 2.5.21.0 
Thanks for trying to help by the way. And so quickly!

**Comment by Josh65-2201** [comment]
Have you try refreshing the folder (F5 key) after pasting it?
Can you also see if this is an issue in the preview version. https://files.community/download

**Comment by bw889** [comment]
Yes have tried refreshing and also going up and or back a couple of levels. And when I open the same folder in the Windows File Explorer it does appear. Apart from this one issue I much prefer Files to the Windows File Explorer.

**Comment by bw889** [comment]
Installing Preview version now ....

**Comment by yaira2** [comment]
Seems related to this issue https://github.com/files-community/Files/issues/12626#issuecomment-1712841136

**Comment by bw889** [comment]
No luck with the Preview version either

**Comment by bw889** [comment]
I have just noticed that the shortcuts and urls whilch were in folders before Files was installed can be seen, but new ones cannot.

**Comment by kerfuffley** [comment]
Just installed Files v2.5.21.0 on Windows 10 and I'm seeing this issue too. I see the issue in the preview version as well.

For one of the shortcuts, I tried copying it from File Explorer and pasting it into the same folder in Files, and then after refreshing, the original shortcut will show in Files, but not the copy.

All my shortcuts are in my OneDrive. So far it seems like the only shortcuts that don't show are ones pointing to some server (e.g. \\servername), but not all shortcuts to a server don't show up. Shortcuts to websites seem to work fine.

**Comment by Josh65-2201** [comment]
Should this be closed in favor of #15821?

**Comment by yaira2** [comment]
Sounds like a good idea
