### ISSUE TITLE
Portable version.

### ISSUE THREAD

**Issue by paolosezart** [files-community/Files#13367]
### What feature or improvement do you think would benefit Files?

Great file manager! I would like a portable version to always have with me on a USB flash drive. Is there any plans for the developer to make a portable version of the program?

### Requirements

Portable version of the program

### Files Version

v2.5.21

### Windows Version

10.0.xxxxxx.xxxx

**Comment by yaira2** [comment]
Thank you for your feedback, a portable version is not being planned right now. Please see #11403 for more details.
