### ISSUE TITLE
Bug: Crash occurs when opening Files via 3rd party app 

### ISSUE THREAD

**Issue by tacogerbil** [files-community/Files#13369]
### Description

I was opening a specific folder holding images (from the app Launchbox).  Files opened but crashed while accessing the specified folder.  Tried it a few more times and it did not re-occur.
![image](https://github.com/files-community/Files/assets/12961907/f713dd00-5f0d-4dcf-942e-bebb22e40618)

### Steps To Reproduce

Click on 3rd party app shortcut that would normally open Windows Explorer to proper folder.

### Requirements

- e.g. Fix crash that occurs when...
Folder should open as expected without crashing Files.

### Files Version

2.5.29.0

### Windows Version

10.0.22621.2215

### Log File

[debug.log](https://github.com/files-community/Files/files/12600287/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board but since you said it's not constantly reproducible it might not be something Files can fix.

**Comment by yaira2** [comment]
@tacogerbil were you able to reproduce the crash multiple times?

**Comment by tacogerbil** [comment]
> @tacogerbil were you able to reproduce the crash multiple times?

Yes but not very often and very randomly.  I couldn't pin down what I was doing that would trigger it.

**Comment by yaira2** [comment]
I don't see anything that can be causing it but it's possible that it's a WinAppSdk issue. Is the issue still present in the latest preview build?

**Comment by yaira2** [comment]
@tacogerbil
