### ISSUE TITLE
Incorporate Local/Cloud File Encryption (Using SecureFS)

### ISSUE THREAD

**Issue by nao9797** [files-community/Files#13365]
### What feature or improvement do you think would benefit Files?

If it's not too ambitious and too much to ask, it'd be really awesome if file encryption using [SecureFS](https://github.com/netheril96/securefs) was integrated into Files. Usually people use protocols like Cryfs, Ecryptfs, Encfs, etc. to securely encrypt files that are uploaded to their Cloud Drives. If Files integrated SecureFS for example with an interface like [SiriKali](https://github.com/mhogomchungu/sirikali), this would save people the trouble of installing both, running them, setting them up, etc and would allow probably the most seamless no-brainer experience for doing this. 

### Requirements

This proposal will accomplish allowing users to seamlessly encrypt their files locally as well as on Cloud Drives 

### Files Version

2.5.21.0

### Windows Version

Windows 10

**Comment by yaira2** [comment]
Thank you for the feedback. As discussed on Discord, we don't plan to build this functionality into Files, but if you're interested, you can take advantage of the features in Secure Folder FS https://github.com/securefolderfs-community/SecureFolderFS.
