### ISSUE TITLE
Bug: Clicking on (E:) on sidebar crashes app

### ISSUE THREAD

**Issue by nao9797** [files-community/Files#13363]
### Description

Pretty straightforward, one click on the Drive (E:) causes immediate crash
Renaming the drive to `main (e:)` works around the issue.

### Steps To Reproduce

Click on the Drive (E:)

### Requirements

- e.g. Fix crash that occurs when...
Crash occurs when opening a drive (E:)

### Files Version

2.5.21.0

### Windows Version

10.0.19045.3031

### Log File

[debug.log](https://github.com/files-community/Files/files/12597760/debug.log)

**Comment by yaira2** [comment]
Thank you for the report. Does this happen consistently?

**Comment by samfourie** [comment]
Have also Experienced it. My Drive was Drive D: 
Internal SATA Drive.
Windows 10 Pro - 22H2 - Build 19045.3393

**Comment by nao9797** [comment]
I had renamed my E: drive to just "E:" and this seems to have caused confusion in the app so I tried renaming it to "Main" (probably removing the colon helps) and it's working now

**Comment by samfourie** [comment]
After viewing my Log file I realized it was my Drive G - which has a issue when plugged in on a certain USB port even with windows file manager. so no error from File app here. Apologies

![Capture](https://github.com/files-community/Files/assets/6639868/78455c6a-f087-424c-bd86-01b401bd53ef)

**Comment by yaira2** [comment]
@nao9797 is this how the drive is displayed when you have the issue"
![image](https://github.com/files-community/Files/assets/39923744/5f4a896a-f8af-49b7-9777-9c4baa940eeb)

**Comment by yaira2** [comment]
@nao9797
