### ISSUE TITLE
Incorporate JPEG View as an alternative option vs Default Image Viewers

### ISSUE THREAD

**Issue by nao9797** [files-community/Files#13368]
### What feature or improvement do you think would benefit Files?

*Yet another :D* Incorporate JPEG View as the Default Image Viewer for Files. [JPEG View](https://github.com/sylikc/jpegview/releases) is a beautiful, lightweight FOSS Image Viewing App for Windows. It's less than 5MB in size, so my hopes is that incorporating it into Files as its own default Viewer is easy enough to pull off. Ideally this could be in the options as a toggle between "default image viewer / JPEG View." 
It'd be a nice option for all the FOSS enthusiasts such as myself and perhaps might make loading or opening images faster?

### Requirements

This proposal will incorporate JPEG View's Image Viewer natively into Files, allowing users to opt for using JPEG View to open/view images vs Windows Image Viewer by toggling the option in the settings

### Files Version

2.5.21.0

### Windows Version

Windows 10

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Files can already preview jpgs what benefit does that have?

**Comment by yaira2** [comment]
Are you refering to the preview pane?

**Comment by nao9797** [comment]
I am unfamiliar with both Quicklook and SeerPro. 
@yaira2 I am not referring to the preview pane, rather providing a built-in (the most lightweight) FOSS alternative for opening images for people who would like to opt-out of the Closed-Source alternatives / default image viewers that are built in to windows. 
I was able to find Quicklook on Github and will explore it, I wasn't however able to find SeerPro's github, if you could provide the links I will gladly install them and try them out @Josh65-2201

**Comment by yaira2** [comment]
Thank you for the response, our current approach is to leave the file previews to other applications as opposed to bundling extra software together with Files. The QuickLook integration is our recommendation if you're looking for a better way to preview files.
