### ISSUE TITLE
Bug: Issue when double clicking to expand the sidebar

### ISSUE THREAD

**Issue by Battler624** [files-community/Files#13360]
### Description

When double clicking the sidebar in the preview to make it smaller it good, but when double clicking to make it bigger again, it clicks on the folder at the same time.

Reported this on discord and was requested to post on reddit.

and video is uploaded to discord on this [link ](https://discord.com/channels/725513575971684472/1144296182483525732)(#thread in discord)

### Steps To Reproduce

Double-click sidebar to make it smaller
Double-click sidebar to make it bigger but click on a spot where if it extends to the bigger size your mouse cursor would be on top of a folder such as downloads or documents.

### Requirements

Its expected to just extend the sidebar to the original size without clicking on said folder

### Files Version

2.5.29

### Windows Version

Windows 11

### Log File

[debug.log](https://github.com/files-community/Files/files/12592698/debug.log)

**Comment by yaira2** [comment]
Thank you for the report, I can reproduce this as well. In the meantime, you can work around this by resizing the sidebar instead of double clicking.

**Comment by yaira2** [comment]
This issue should be fixed with #13366
