### ISSUE TITLE
Files shutdown on a click

### ISSUE THREAD

**Issue by anorserio** [files-community/Files#13375]
### Description

Surprising app shutdown when clicking on a folder

### Steps To Reproduce

[debug.log](https://github.com/files-community/Files/files/12614308/debug.log)

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

2.5.10.0

### Windows Version

10.0.19041.450

### Log File

[debug.log](https://github.com/files-community/Files/files/12614299/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, please update to 2.5.21.0 and try again.
