### ISSUE TITLE
Make a Portable version of Files

### ISSUE THREAD

**Issue by nao9797** [files-community/Files#13378]
### What feature or improvement do you think would benefit Files?

I would be most appreciative for a portable version of Files. Please if possible, consider this and thank you very much if even just considering this! 

### Requirements

- This proposal will accomplish providing a portable version of files

### Files Version

2.5.21.0

### Windows Version

W10

**Comment by Josh65-2201** [comment]
Thanks for the feedback, this isn't possible as Files and the dependences are packages, they also don't have a portable version to use.

**Comment by nao9797** [comment]
I am saddened by this.. oh well. Interesting that you pointed out that its dependencies are packaged, where can I see the dependencies in the code? (Like what line numbers and such) if you don't mind me asking

**Comment by yaira2** [comment]
@nao9797 you can find them in the `Files.Package.wapproj` files.

**Comment by nao9797** [comment]
I see, this is good to know. Maybe then you could have a feature-poor portable version (though maybe it would be so pruned it might defeat the purpose of files?) I wonder how many features would be sacrificed . Anyway Thanks for your reply!

**Comment by nao9797** [comment]
my hopes are that I at least made you laugh with my new term "feature-poor version" xD

**Comment by PaduaPlay** [comment]
> @nao9797 you can find the references in the `Files.Package.wapproj` file. It's less of an issue with the dependencies and has more to do with the features that rely on having a package identity.

Given the various package identity / dependency considerations for not being able to make a portable version - is it possible to provide an option of choosing where the app can be installed in a folder, in a drive other than the default C:\Users\***\AppData\Local\Microsoft\WindowsApps\ folder in the system drive?

Allowing usage of a different directory for all 'Files app' components - of course, other than whatever 'has' to be in the default directory for identities etc. - can be valuable when managing available system disk space is needed.

Thanks for considering.
