### ISSUE TITLE
Sort options for different folders 

### ISSUE THREAD

**Issue by datcu-octavian** [files-community/Files#13372]
### What feature or improvement do you think would benefit Files?

I want to be able to have the last sort option selected for a specific folder to be remembered the next I go to that folder. Right now, the sort option selected for a folder reverts back to the default sort option next time I open the same folder. 

### Requirements

-

### Files Version

2.5.21.0

### Windows Version

10.0.22631.2338

**Comment by Josh65-2201** [comment]
Thanks for the feedback, have you tried turning off Sync layout and sorting preferences across directories in Files settings > Folders
