### ISSUE TITLE
Bug: App crashes when adding a new file

### ISSUE THREAD

**Issue by jmob0** [files-community/Files#13374]
### Description

Crashed. had 4 tabs open. downloaded a file into the folder that was active. app crashed and restarted. it does not do this everytime. app had been running for 1-2 days.

### Steps To Reproduce

1. open some tabs
2. have the folder which is going to get new files written to it as 'active'
3. add new files to the folder above
4. boom!

### Requirements

- e.g. Fix crash that occurs when...
fix crash that occurs when during new file added refresh

### Files Version

2.5.29.0

### Windows Version

10.0.22621.2134

### Log File
[debug.log](https://github.com/files-community/Files/files/12641672/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board. In future UPLOAD the file and don't copy and paste the contents in.

**Comment by yaira2** [comment]
Are you able to consistently reproduce this, or is it random?

**Comment by jmob0** [comment]
This may be a red herring since I'm running a locally built, debug build. I'll try running release The crash is due to an assert getting fired.  Call stack below. A couple of other details of note: (1) The crash typically happens after waking up from sleep or hibernation (2) 4-5 tabs are open - 1 local folder, the other tabs are of network shares (the shares are all available).

Call Stack attached:
[files-debug-crash.txt](https://github.com/files-community/Files/files/12703947/files-debug-crash.txt)

**Comment by yaira2** [comment]
@jmob0 would you like to work on a fix?

**Comment by yaira2** [comment]
@jmob0 is this still reproducible?

**Comment by yaira2** [comment]
@jmob0

**Comment by jmob0** [comment]
It has not reproduced using a build from 10/31's main branch.  The crash was happening at least once a day in previous builds.

**Comment by yaira2** [comment]
Excellent, please let us know if it happens again.
