### ISSUE TITLE
Code Quality: Remove AssociatedInstance

### ISSUE THREAD

**Issue by 0x5bfa** [files-community/Files#13379]
### Description

associatedInstance usually used in so many method argument and those methods are tied that reference. Now we have the 'context' DI and are able to remove this reference.

### Concerned code

All

### Gains

- A better maintainability.

### Requirements

- Remove that argument in all codebase
- Add DI of IPageContext or something.

**Comment by yaira2** [comment]
How do you plan to approach this task?

**Comment by 0x5bfa** [comment]
Can be replaced by using IPageContext.ShellPage
