### ISSUE TITLE
Show directory tree in left navigation pane

### ISSUE THREAD

**Issue by vulchor** [files-community/Files#13385]
### What feature or improvement do you think would benefit Files?

There should be the option to show and expand the full directory tree when navigating folders. So when I click C: under Drives, the entire root folder structure should be able to be displayed. When I go into a sub-directory, the tree should automatically expand, allowing me to choose any sub-directory here, as well as in the previous level. This option still exists in Windows Explorer, though it is no longer the default behavior.

Example of what I mean from Windows Explorer:
<img width="166" alt="directory tree" src="https://github.com/files-community/Files/assets/29226816/05ec7ee4-5c0b-480d-967b-21847c4b2d57">

### Requirements

- This proposal will allow for far easier and quicker navigation of complex file systems for people accustomed to its layout, since this layout has been a standard since the early days of Windows.

### Files Version

2.5.21.0

### Windows Version

10.0.22631.2338

### Comments

This is the only feature missing from Files that keeps it from becoming my main file manager.

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #1928. You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
To expand on what Josh shared, adding a tree view in some form in on our todo list.

**Comment by yair100** [comment]
@vulchor Tree View is currently available in preview https://files.community/download. It will be included in the next stable release.
