### ISSUE TITLE
OneDrive icon shown as default folder icon

### ISSUE THREAD

**Issue by IsmaelMelt** [files-community/Files#13380]
### Description

I thought the OneDrive icon was missing but it is shown as it should in the default explorer. I have seen videos where the icon is displayed normally. Even in the Microsoft store screenshots the OneDrive folder has the clouds icon.

![image](https://github.com/files-community/Files/assets/131465617/27f20655-97f6-4b18-bb73-a3aa7c7c6303)
Left is default explorer, right is Files.

Sorry for bad English.

### Steps To Reproduce

1. Just open Files

### Requirements

- Show the OneDrive icon (or tell me how to fix it in my device)

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2283

### Log File

[debug.log](https://github.com/files-community/Files/files/12622222/debug.log)

**Comment by yaira2** [comment]
Thank you for the report, can you confirm if the OneDrive icon is displayed when using the preview version? https://files.community/download.

**Comment by yaira2** [comment]
Thank you for the report, can you confirm that the OneDrive icon is displayed when using the preview version? https://files.community/download.
