### ISSUE TITLE
Closing secondary pane causes crash

### ISSUE THREAD

**Issue by JJSax** [files-community/Files#13384]
### Description

Observing a crash when closing a pane.  I am not seeing this crash in most places, just in one place.  Logs say some exceptions from FileThumbnailHelper.  

It might have something to do with the size of the left hand pane.  It has 2500 items in it and 20 GBs of data, all music files I believe.

### Steps To Reproduce

1. Open files
2. Click 3 dots (under settings top right)
3. click new pane
4. Click 3 dots again
5. click close pane
6. observe crash

### Requirements

- e.g. Fix crash that occurs when closing a pane in this situation.

### Files Version

2.5.21.0

### Windows Version

10.0.19045.3324

### Log File

[debug.log](https://github.com/files-community/Files/files/12641767/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, what layout are you using?

**Comment by JJSax** [comment]
Layout mode (in settings > folders) is set to Tiles.
I hope that's what you're referring to.

**Comment by Josh65-2201** [comment]
Thanks for the info, this seem to be the same issue as #12581. You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
@Josh65-2201 are you sure this is the same? That's relating to loading items, whereas this issue relates to closing the second pane.

**Comment by Josh65-2201** [comment]
Not fully certain, It's the same error in the debug.log file but there are multiple in both issues so it might be a different one from this. There is also some people having it crash when deleting or moving a file so I am assuming it's can also happen when the layout change for the items.
