### ISSUE TITLE
Title Bar takes precedence over right-click menu

### ISSUE THREAD

**Issue by Twentydragon** [files-community/Files#13387]
### Description

When opening a right-click menu that has a lot of items, such as the Tags menu, if the menu is long enough, it will extend across the region of the window reserved by the Title Bar. This causes the option at the top to be unselectable, as clicking here will count as clicking on the Title Bar, as though to move the window.

This can currently be worked around by using keyboard navigation to select and activate the menu item.

### Steps To Reproduce

1. Create a lot of tags (at least 40).
2. Right-click an item to assign a tag.
3. Click on the first tag in the list.
4. Observe nothing seeming to happen.

### Requirements

Either:
A. Layer the right-click menu's interactability above that of the Title Bar, or
B. Prevent the right-click menu from intersecting with the Title Bar, by restricting its available screen space.

### Files Version

2.5.21.0

### Windows Version

10.0.19045.3448

### Log File

[debug.log](https://github.com/files-community/Files/files/12642390/debug.log)

**Comment by gave92** [comment]
Similar to #10823 but for submenus?

**Comment by Twentydragon** [comment]
> Similar to #10823 but for submenus?

Yeah, that seems to be a very similar issue.

**Comment by Josh65-2201** [comment]
Thanks for the report, this is fixed in the preview build https://files.community/download.
