### ISSUE TITLE
Change Application to open

### ISSUE THREAD

**Issue by uuc110** [files-community/Files#13386]
### What feature or improvement do you think would benefit Files?

It's just one of the mission feature which is not avaibale in FIles, while its there in Windows Explorer. Using this user can change the type of file user want to open with. 

### Requirements

- Can change the file type to open for all application
- Allow user to open file with its desired application

### Files Version

2.51.20

### Windows Version

1000.22662.1000.0

### Comments

Explorer:

![image](https://github.com/files-community/Files/assets/44457947/f3402d0e-450d-4ad1-beb1-51088d5101fe)

Files

![image](https://github.com/files-community/Files/assets/44457947/38f309ad-3b0e-4848-a3c8-2f3e3735f226)

there is no Change option in Files.

**Comment by Josh65-2201** [comment]
Thanks for the feedback, you can right click a file > Select `open with` > Select program to use > Click `Always` to change the default.
