### ISSUE TITLE
Mouse wheel scrolling not working

### ISSUE THREAD

**Issue by Gitme76269** [files-community/Files#13395]
### Description

Mouse wheel will not scroll folders in this app.   Windows file explorer scrolls with mouse wheel as it should.

Windows 10 Pro 22H2

### Steps To Reproduce

Open app
Select folder in left window using right click
move mouse wheel

### Requirements

Expected behavior is to scroll through folders in left pane of the app

### Files Version

2.5.21.0

### Windows Version

10.0.19045.3448

### Log File

[debug.log](https://github.com/files-community/Files/files/12658675/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report,
- Can you see if this is an issue in the preview version. https://files.community/download

- If so and you have software called XMouse control? if so you can try creating a separate profile for Files.exe > Options > enable `Disable Scroll Window Under Cursor`

- You can also try going to Windows Settings > Bluetooth & devices > Mouse > Enable `Scroll inactive windows when hovering over them`

**Comment by Gitme76269** [comment]
Hi,

 

Changing the mouse setting to Scroll inactive windows when hovering over them   allows scroll to work.

 

But that setting shouldn’t be necessary. So, I tried installing an older revision.    https://files.community/download    sends me to the Microsoft store, where I could not find prior revs of the software

 

Thanks,

 

David

**Comment by Josh65-2201** [comment]
Please check the preview version for the issue (Second button on the website), older ones are not available.

**Comment by Gitme76269** [comment]
Thanks Josh

 

Insider Preview fixed it.
