### ISSUE TITLE
Code Quality: Update the XAML styler check workflow to apply styling as well

### ISSUE THREAD

**Issue by 0x5bfa** [files-community/Files#13396]
### Description

As the title.

### Concerned code

The workflow that runs XAML styler console checker.

### Gains

- Better maintainability.

### Requirements

- Update the file to do so

### Comments

https://github.com/CommunityToolkit/Labs-Windows/blob/main/ApplyXamlStyling.ps1

**Comment by heftymouse** [comment]
Their [GitHub workflow](https://github.com/CommunityToolkit/Labs-Windows/blob/main/.github/workflows/build.yml#L48) only checks this, like what ours does already

**Comment by 0x5bfa** [comment]
@heftymouse https://github.com/CommunityToolkit/Labs-Windows/blob/main/ApplyXamlStyling.ps1#L100 See here.

@yaira2 Why did you close this issue?
