### ISSUE TITLE
[BUG] Why it does not show drive letter

### ISSUE THREAD

**Issue by MeiVinEight** [files-community/Files#13399]
### Description

![image](https://github.com/files-community/Files/assets/57023439/2b36c012-167f-42db-a69f-e104d1bbba0a)
It does not show drive letter

### Steps To Reproduce

As mentioned above

### Requirements

How to make it show drive letter, i need it.

### Files Version

2.5.21.0

### Windows Version

Windows 11 Pro Insider Preview - 22H2 - 23545.1000

### Log File

[debug.log](https://github.com/files-community/Files/files/12667747/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you send a screenshot of Windows File Explorer This PC section.

**Comment by MeiVinEight** [comment]
Okey
![image](https://github.com/files-community/Files/assets/57023439/4a791484-8cb6-46d7-a810-81ceb3759b63)
This is This PC in Files APP
![image](https://github.com/files-community/Files/assets/57023439/edcf9650-6997-408d-b36a-449ec4a9b976)
and this is Windows File Explorer This PC

**Comment by MeiVinEight** [comment]
Thank you, i had solved it, thanks again for spend time for me.

**Comment by yaira2** [comment]
@MeiVinEight what was the issue?

**Comment by cosmicr** [comment]
I am also having this issue. Any ideas?

**Comment by Josh65-2201** [comment]
Check Windows File Explorer if it also doesn't show them then you will rename the drives to add them.
