### ISSUE TITLE
Sort on file extension

### ISSUE THREAD

**Issue by dunbarrc** [files-community/Files#13390]
### What feature or improvement do you think would benefit Files?

Under Details layout columns:  add a column for File Extension, in addition to or (preferably) in place of Type. The file type verbiage can be quite verbose, which takes up too much horizontal screen space. 

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.5.21.0

### Windows Version

10.0.19045.3448

### Comments

I am a brand new (today) user of Files. I like what I see so far, and plan to use as often as possible in place of MS File Explorer and Avanquest PowerDesk. Many of the reviewers (as seen in the Microsoft Store) want to see Tree View, which you said is currently under development. I too look forward to having that very important feature asap. 
Informally stated, here are two other features I would like to see:
1)  Preview of Microsoft Office docs (docx, xlsx, xlsm, pptx, etc.  All I see now is the application logo.
2)  Ability to drag and drop files between folders in different panes; PowerDesk has long had that feature. 

Keep up the good work.

**Comment by Josh65-2201** [comment]
Thanks for the feedback, I've added this to the project board.

As for you comments
- Office preview is already available in the preview build. https://files.community/download
- Drag and drop already should work, What do you mean by panes?

**Comment by yaira2** [comment]
Thank you for your feedback, support for showing an extension column is being tracked in #8366.

**Comment by yaira2** [comment]
We're going to continue tracking this in #8366, you can add a comment or click subscribe to be notified when this feature is added.
