### ISSUE TITLE
Bug improvement 

### ISSUE THREAD

**Issue by Flowersmillion** [files-community/Files#13407]
### Description

Site improvements and bug fixes 

### Steps To Reproduce

Fix crashes 

### Requirements

- e.g. Fix crash that occurs when...
Fix crash navigations 

### Files Version

2.0.34.20

### Windows Version

27.28151.95

### Log File

@kahdarflowers

**Comment by yaira2** [comment]
Thank you for your feedback, we're constantly working on stability improvements. If there is a specific issue that you're experiencing, please open an issue with a clear description and step to reproduce the issue. This we can investigate and try to work on a fix.
