### ISSUE TITLE
App speed and column view

### ISSUE THREAD

**Issue by diegobarri00** [files-community/Files#13406]
### What feature or improvement do you think would benefit Files?

App speed:
Especially when you start the app from scratch, it takes a long time, just like searching for files or moving between folders, it would be nice if it were faster.

Column view:
The width of the columns is fixed, so it would be nice if it allowed you to modify it in some way because sometimes the file names are very long and you can barely see the title

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.5.20.0

### Windows Version

10.0.22621.2283

**Comment by yaira2** [comment]
Thank you for your feedback, support for resizing columns is being tracked in #6534. If you're interested in trying the preview version, there are some improvements to startup performance https://files.community/download.
