### ISSUE TITLE
Folder tree like KDE Dolphin File Manager

### ISSUE THREAD

**Issue by leuveg** [files-community/Files#13411]
### What feature or improvement do you think would benefit Files?

Hey,
i like Files, but one think i miss: the Folder Tree like KDE Dolphin File Manager.
What I'm missing, however, is the "Folder Tree" view of KDE Dolphin.
With this I can easily view the contents of the FOLDERS because the FOLDERS can be opened. Difficult to describe, see screenshot. :)
This allows me to quickly overview the contents of the folders and, above all, select files from the subfolders and then copy them into a new folder. For example, in a folder in the second panel. See Screenshot 2

![KDE Dolphin Folder Tree](https://github.com/files-community/Files/assets/72378134/f5731abe-a14f-49b4-868e-73aa44ad3bd1)
![KDE Dolphin Folder Tree 2](https://github.com/files-community/Files/assets/72378134/35608464-9a59-4f7b-a105-017d8483e73d)

### Requirements

This suggestion makes it easier for me to put together documents such as teaching materials that are organized in different folders.

### Files Version

2.5.21.0

### Windows Version

10.0.19045.3448

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #1928. You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
To expand on what Josh shared, this feature is on our todo list and you can follow the discussion in the issue Josh linked.

**Comment by yaira2** [comment]
We plan to start with the left side tree view, but we're currently blocked by some performance issues.
