### ISSUE TITLE
Feature: Status Center Logo Shouldn't Disappear After Clicking "Clear All"

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#13419]
### What feature or improvement do you think would benefit Files?

When I click on "Clear All" in the Status Center, the Status Center logo disappears. It should only disappear after I close it.

### Requirements

Identify the cause of the Status Center logo disappearing when you click on "Clear All".

### Files Version

2.5.29.0

### Windows Version

10.0.22621.2283

**Comment by yaira2** [comment]
Thank you for your feedback. The current design is for the status center to only be visible when there are notifications. We're talking about adding an option to always show the icon, but as of now this is the intended behavior.
