### ISSUE TITLE
Feature: Open New Tab with Middle Click over Navigation Pane item

### ISSUE THREAD

**Issue by HekutoruMAC** [files-community/Files#13410]
### What feature or improvement do you think would benefit Files?

Opening a new tab by middle clicking on a Navigation Pane item, offering the same functionality as Windows Explorer.

### Requirements

Middle clicking over a Navigation Pane item working just like the 'Open in New Tab' context menu option.

### Files Version

2.5.22.0

### Windows Version

10.0.22621.2283

**Comment by yaira2** [comment]
Thank you for your feedback

**Comment by yaira2** [comment]
Correct, it wasn't intentionally removed but must have been left out when we rewrote the sidebar.
