### ISSUE TITLE
Bug: Issue with selection rectangle in the column layout

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#13418]
### Description

I'm experiencing a problem when using the column view layout. When I try to select multiple folders, the first one unexpectedly opens. This behavior is not desired because when I'm in a subfolder of the folder I want to select, it closes that subfolder and opens the first selected folder. As a result, when I attempt to select multiple folders, the first one opens and then closes when I select an additional folder.

### Steps To Reproduce

1. Switch to the column layout
2. Select multiple folders using the selection rectangle
3. Notice that the first folder that's selected is opened for moment, but then closes after additional folders/items are selected

### Requirements

Delay opening the first folder if selected by the selection rectangle (in the columns layout)

### Files Version

5.5.29.0

### Windows Version

10.0.22621.2283

### Log File

...

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by patilniraj8** [comment]
can i try to solve this issue??

**Comment by Josh65-2201** [comment]
This hasn't been approved yet. If you want to contribute take a look at https://github.com/orgs/files-community/projects/3/views/7 and ones labelled `good first issue` in the labels section

**Comment by yaira2** [comment]
@Lukiluc29 is this with the selection rectangle?

**Comment by yaira2** [comment]
Thanks! I updated the steps to reproduce the issue.
