### ISSUE TITLE
Taskbar Inaccessible in FullScreen

### ISSUE THREAD

**Issue by karthikvijay5227** [files-community/Files#13414]
### Description

When the files app is used in full-screen maximise mode, the taskbar in auto-hide mode is not accessible until we go out of the entire screen.

### Steps To Reproduce

1. Open Files App, the taskbar should be in auto-hide mode
2. Make it maximise
3. The taskbar will not be visible if we hover to the bottom until we make the window small.

### Requirements

Occurs when maximising the files app with auto taskbar hide feature.

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2283

### Log File

[debug.log](https://github.com/files-community/Files/files/12705780/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, this has been fixed in the preview version. https://files.community/download

**Comment by karthikvijay5227** [comment]
Is preview version as much stable for normal use?

**Comment by Josh65-2201** [comment]
For me yes but it can depend on what you use Files for.

**Comment by karthikvijay5227** [comment]
Getting this error in parsing when trying to install preview

**Comment by Josh65-2201** [comment]
If you are trying to upload an image you have to do that from GitHub directly email attachments don't work.

**Comment by karthikvijay5227** [comment]
how to do,do i have to raise new bug or provide drive link

**Comment by Josh65-2201** [comment]
On your emails click view on GitHub button > Click the comment box at the bottom > copy and paste the image > wait a few seconds > Click comment button

**Comment by karthikvijay5227** [comment]
![Screenshot 2023-09-23 192916](https://github.com/files-community/Files/assets/77284874/3c659f43-60e3-4ed7-a904-ce5dcc90831f)

**Comment by Josh65-2201** [comment]
Can you try restarting your system
Updating app installer from the Microsoft Store. Click library > Check for updates

**Comment by rivman** [comment]
Issue appear on 3.9.1.0 with Windows 11 (10.0.22631.5262)
It was working fine few days then maximize ignore the taskbar.

**Comment by Josh65-2201** [comment]
Can you see if this is an issue in the preview version. https://files.community/download
