### ISSUE TITLE
Bug: Can't copy or cut folder

### ISSUE THREAD

**Issue by Pietro228** [files-community/Files#13412]
### Description

Hi,

I recently noticed that I sometimes can't copy a folder. I tried to click the copy button or CTRL + C, but nothing works.

![obrazek](https://github.com/files-community/Files/assets/53868994/c4513874-0aed-43ff-b417-018fa934aea8)

### Steps To Reproduce

1. Open folder that has a folder
2. Try to copy that folder inside
3. Nothing happens

### Requirements

Copy a folder.

### Files Version

2.5.29.0

### Windows Version

10.0.22631.2338

### Log File

[debug.log](https://github.com/files-community/Files/files/12700752/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you try copy and paste text. There bug in Windows which causes copy and paste to not work.

**Comment by yaira2** [comment]
@Pietro228

**Comment by Pietro228** [comment]
Sorry, I was on vacation. I'll try to copy text when it appears again.

**Comment by Pietro228** [comment]
Hi, I can't copy files, but I can copy text. It just doesn't work in Files.

**Comment by pot-code** [comment]
mine is can't cut folder

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by Pietro228** [comment]
For now it did not happen

**Comment by yaira2** [comment]
Thanks for checking. If it happens again, please let us know.
