### ISSUE TITLE
Crash on delete operation

### ISSUE THREAD

**Issue by avengero** [files-community/Files#13429]
### Description

deleting a folder or file (permanently or not) causes the app to crash

### Steps To Reproduce

1. select folder / file
2. hit delete
3. confirm in dialog
4. app crashes
5. files / folder are not deleted

### Requirements

Files get deleted and app doesn't crash

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2283

### Log File

[debug.log](https://github.com/files-community/Files/files/12730264/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, what is the path you are deleting the files from?

**Comment by avengero** [comment]
Tried deleting from my Download directory and another directory within my username folder. Just tried with file on another drive and it still happens.

**Comment by Josh65-2201** [comment]
Can you see if this is an issue in the preview version. https://files.community/download

**Comment by avengero** [comment]
Just tried and still happening.

**Comment by hez2010** [comment]
This is weird. You encountered a `NotImplementedException` on `ITaskbarList2.HrInit` but this shouldn't happen. Are you using a modified-version of Windows or some taskbar plugins?

**Comment by avengero** [comment]
Ah yes- using an app called startallback (https://www.startallback.com/) to modify taskbar appearance. Otherwise it's regular Windows 11 pro.

**Comment by avengero** [comment]
Strangely enough, after a seemingly unrelated windows update and reboot it now deletes properly.
