### ISSUE TITLE
Bug: Issue with Transparent Dropdown Menus

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#13422]
### Description

I've encountered an issue where, when I click on a dropdown menu like "New" to create a new item, "Copy" to copy a Windows version, or "Files," etc., the menu sometimes appears transparent.

### Steps To Reproduce

1. Click on a dropdown menu

### Requirements

Identify the root cause of the transparency issue in dropdown menus.

### Files Version

2.5.29.0

### Windows Version

10.0.22621.2283

### Log File

...

**Comment by yaira2** [comment]
This sounds like an issue with WinUI, can you report on their repo?
