### ISSUE TITLE
deleting files

### ISSUE THREAD

**Issue by kazugg56** [files-community/Files#13424]
### Description

when deleting >120 files issue ocurrs

### Steps To Reproduce

1. del >120 files at once 
2. see error

### Requirements

when deleting >120 files issue ocurrs

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2134

**Comment by Josh65-2201** [comment]
Thanks for the report, Can you answer the following
- What error are you seeing?
- Where are you deleting the files from?
- Can you please upload (Do not copy and paste content) the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.

**Comment by yaira2** [comment]
@kazugg56 is the app crashing?

**Comment by yaira2** [comment]
@kazugg56
