### ISSUE TITLE
Bug: .jpeg images open with Photos app instead of default app

### ISSUE THREAD

**Issue by arrhat** [files-community/Files#13425]
### Description

When opening an image file with a .jpeg extension, it always opens in the Photos app instead of the default app (which for me is IrfanView). Only occurs with .jpeg files; does not occur with .jpg files (or any other extension, that I've noticed). Issue is specific to Files -- doesn't happen when opening a file from File Explorer. 

### Steps To Reproduce

1) In Windows 10, set the default image viewer to something other than the Photos app
2) Open Files to a folder containing a .jpg image
3) Double-click the image; it should open in the default viewer
4) Rename the image to have a .jpeg extension
5) Double-click image; it should open in Photos instead of the default viewer

### Requirements

- e.g. Fix crash that occurs when...
When opening a .jpeg file, it should open in the default app, as set in the Windows system settings

### Files Version

2.5.21.0

### Windows Version

10.0.19045.3448

### Log File

n/a

**Comment by Josh65-2201** [comment]
jpg and jpeg are different extensions that you have to change the default programs on. You can right click the file > Open with > Select the program > Click always.

**Comment by arrhat** [comment]
> jpg and jpeg are different extensions that you have to change the default programs on. You can right click the file > Open with > Select the program > Click always.

Yes, that is what I'm saying. I have already set the file association for .jpegs (including via the method you mention here). The file association is set correctly -- it works as expected in File Explorer. Files (and _only_ Files) ignores the file association for .jpegs.

**Comment by arrhat** [comment]
[debug.log](https://github.com/files-community/Files/files/12717272/debug.log)

**Comment by yaira2** [comment]
I just tested by changing the default to Paint, and it's working as expected.

**Comment by yaira2** [comment]
Can anyone else reproduce this issue?

**Comment by yaira2** [comment]
Can you check what the Settings app shows for `.jpeg`?
![image](https://github.com/files-community/Files/assets/39923744/d68ab3ca-ca62-4687-80cd-6a812a65d85c)

**Comment by arrhat** [comment]
![image](https://github.com/files-community/Files/assets/55144575/5edcead8-4bab-4c52-b457-3af02c70eab3)

**Comment by yaira2** [comment]
Does this also happen if you set the default to Paint?

**Comment by arrhat** [comment]
> Does this also happen if you set the default to Paint?

Yes, same behavior: the .jpeg opens in Photos instead when opened from Files (but opens in Paint when opened from Windows Explorer).

**Comment by yaira2** [comment]
It's possible that it's an issue with specific versions of Windows, however, I haven't been able to reproduce it myself.

**Comment by yaira2** [comment]
@arrhat can you check if reinstalling Files fixes the issue?

**Comment by arrhat** [comment]
> @arrhat can you check if reinstalling Files fixes the issue?

Just did a fresh install of 3.1.1.0 and it seems to be fixed -- .jpeg files open in the default program, as expected. (Newest version also runs a lot smoother in general. Nice work to all the devs!)

**Comment by yaira2** [comment]
Thanks for letting us know!
