### ISSUE TITLE
Bug: App sometimes crashes when downloading item to the downloads folder

### ISSUE THREAD

**Issue by imanoobhehe** [files-community/Files#13426]
### Description

Files  - Preview shows an error upon a file being downloaded through Chrome in Incognito. This file was downloaded from Discord, but I doubt it's a general problem. I've attached the logs onto the issue for reference.

### Steps To Reproduce

1. Possibly open a website on incognito
2. Download any file
3. It shows an error that Files encounters with.

### Requirements

Not exactly a crash, but it's an error that was shown to me when i downloaded a file from discord through incognito. Don't know if it's just me, but further information is that I haven't set it as default launcher. 

### Files Version

2.5.29.0

### Windows Version

10.0.19045.3448

**Comment by Josh65-2201** [comment]
Thanks for the report
- Are you opening the file from chrome?
- What error are you seeing?
- Can you please upload (Do not copy and paste content) the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.

**Comment by imanoobhehe** [comment]
1. Yup, the file was opened from chrome. 
[debug.log](https://github.com/files-community/Files/files/12714746/debug.log)
There's the log file. 
As well as for the error, I don't see anything in particular, it's just a notification that files has encountered an error.

**Comment by yaira2** [comment]
Aside from the error, does everything work as expected?

**Comment by imanoobhehe** [comment]
Yes, everything else seems to be fine. I'll create more issues if I encounter anything more.

**Comment by yaira2** [comment]
What I meant was, is the app is crashing or does it just display a notification?

**Comment by imanoobhehe** [comment]
It only displays a notification.

**Comment by yaira2** [comment]
Thanks for the update. @hishitetsu are there any cases where we display the notification despite handling the error?

**Comment by hishitetsu** [comment]
I think it actually crashed and you just didn't notice that it automatically rebooted.

**Comment by imanoobhehe** [comment]
That may be a possibility, I admit I was focussing on the notification and not on the app. But I just tried reproducing the error right now, and it isn't showing the error anymore.

**Comment by yaira2** [comment]
I've had this happen a couple of times when downloading a file to the downloads folder, but the app didn't restart.

**Comment by yaira2** [comment]
@imanoobhehe is this still an issue in v2.5.33?

**Comment by imanoobhehe** [comment]
No, I cannot reproduce the issue right now.

**Comment by yaira2** [comment]
That's good to hear, thank you for checking.
