### ISSUE TITLE
FTP Support

### ISSUE THREAD

**Issue by hawkerm** [files-community/Files#1342]
Related #1059?

**Is your feature request related to a problem? Please describe.**
There's not great FTP support in Windows, it'd be great for File Explorer solution like this to just expose the ability to connect to a remote server and browse it like any other network storage.

**Describe the solution you'd like**
It'd be great to be able to have an FTP/remote section and add server/credentials to connect to a remote FTP server and browse/interact with it like a regular directory.

**Describe alternatives you've considered**
There's other clients out there, but would be nice to just have something integrated into shell and Files UWP seems like a great way to pave the future for that.

**Additional context**
Should just be another connection under network or something similar?

**Comment by yaichenbaum** [comment]
@hawkerm Would you expect features to manage saving files to the server or just support to view the files?

**Comment by hawkerm** [comment]
@yair100 idea would be to replace the need for having a dedicated FTP client.

Basically, being able to view/upload to the server seamlessly as if it was any other folder (once the connection is configured). E.g. it'd be great to have one window/tab open with my local folder and another with my FTP folder and be able to drag/drop between them.

**Comment by yaichenbaum** [comment]
@hawkerm this issue should be resolved with #5627.
