### ISSUE TITLE
Expand drives folders on the left pane

### ISSUE THREAD

**Issue by starbucks2010** [files-community/Files#13428]
### What feature or improvement do you think would benefit Files?

The possibility to expand drives folders on the left pane would be on pair with windows explorer

### Requirements

The possibility to expand drives folders on the left pane would be on pair with windows explorer

### Files Version

2.5.20

### Windows Version

Windows 11 22H2 22621.2283

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #1928. You can check there or click subscribe in the right sidebar for updates.

**Comment by yair100** [comment]
@starbucks2010 Tree View is currently available in preview https://files.community/download. It will be included in the next stable release.
