### ISSUE TITLE
Add Auto-updating from within the App 

### ISSUE THREAD

**Issue by nao9797** [files-community/Files#13430]
### What feature or improvement do you think would benefit Files?

It would be nice if one could update the app from within the app itself (maybe from the "About" section in the settings)
There are many reasons why I believe this would be beneficial for users

### Requirements

- Integrating a built-in function to manually or automatically enable updating the Files app within the app itself

### Files Version

2.5.21.0

### Windows Version

Windows 10

### Comments

Ty for your consideration~ Namaste

**Comment by Josh65-2201** [comment]
Files already auto updates or manual with a button next to the setting icon.

**Comment by nao9797** [comment]
Next to the setting icon is an "Ongoing Tasks" button in the version i have (2.5.21.0). I'm not sure im looking in the right place

**Comment by Josh65-2201** [comment]
You are already on the latest stable release so there is no update to show

**Comment by nao9797** [comment]
oh,.. hmm for some reason i thought i heard mentions of a new version, well ok! So when there is an update it will be in the ongoing tasks button then?

**Comment by Josh65-2201** [comment]
Next too, yes.

**Comment by nao9797** [comment]
noted! thanks
