### ISSUE TITLE
File Handler Icons have dark background

### ISSUE THREAD

**Issue by cardin** [files-community/Files#13436]
### Description

The background of file icons inside of the Open With menu, are oddly dark.

![image](https://github.com/files-community/Files/assets/553816/b8ac9380-a6a0-49df-92e2-dc94c78e360e)

### Steps To Reproduce

I'm not sure if it's relevant, but here are my Windows Light/Dark mode settings:
![image](https://github.com/files-community/Files/assets/553816/7aa05a90-73b5-4009-a119-3ff12f2a97f2)
![image](https://github.com/files-community/Files/assets/553816/4b18eaa6-231d-4664-aa8c-d12284c2cf5e)

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

2.5.21.0

### Windows Version

10.0.19045.3448

### Log File

not applicable

**Comment by cardin** [comment]
I just noticed Windows Explorer also has the same issue - I guess I hadn't been using Explorer for a while now haha.

**Comment by yaira2** [comment]
@cardin this issue is fixed in the preview version of Files. https://files.community/download

**Comment by cardin** [comment]
> @cardin this issue is fixed in the preview version of Files. https://files.community/download

Sort of fixed, but not quite either? (Files 2.5.29.0 Preview)
![image](https://github.com/files-community/Files/assets/553816/6ecc47db-2dca-4a50-b7d3-3d70fe632d64)
