### ISSUE TITLE
Bug: Issue with Search Page Layout Synchronization

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#13439]
### Description

I'm experiencing an issue with the search functionality on my computer. When I perform an initial search, the page displaying the items containing the desired keyword appears in detailed view. However, when I initiate a second search while still on the search page, the results of the second search are displayed correctly, but the layout is synchronized with the settings. In my case, for the second search, it displays in column view since I have synchronized this layout.

### Steps To Reproduce

1. Navigate to the settings, check "Sync layout and sorting preferences across directories", and make sure the column layout is selected in "Layout"
2. Perform a search from anywhere as long as you are in column mode.

### Requirements

Investigate why the search page layout is being synchronized with your settings.

### Files Version

2.5.29.0

### Windows Version

22H2 22621.1992

### Log File

...

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
Can you share a screen recording?
