### ISSUE TITLE
Feature Request: View and Edit MetaData

### ISSUE THREAD

**Issue by SandeeepKiran** [files-community/Files#13448]
### What feature or improvement do you think would benefit Files?

Feature Request: View and Edit Metadata
Of course, I understand this shouldn't be easily accessible to most users.

This does have uses when you frequently need to check and validate files. Or to make edits of my own.
This is the ONLY reason I use Directory Opus12, and I'd prefer to only need Files.

Example view on DOpus12 app.
This is in the Pane or preview pane.
![image](https://github.com/files-community/Files/assets/36911157/4cd25c83-9fc0-4910-a5db-1502d188ef70)

Expected View within Files app.
Here,
With more information shown (or a toggle in settings, so we can see more info - like how folder sizes have a toggle)
![image](https://github.com/files-community/Files/assets/36911157/63007e4d-e8fb-4d8b-8e14-6c7f09b24e49)

Finally,
To Edit the Metadata
Click on Properties
![image](https://github.com/files-community/Files/assets/36911157/f7b41f78-0b05-47ae-9147-ac48c3ed924f)

then,
Have more Information here.
There would be an Edit Button -> 'Yes I understand the risks of editing Metadata" -> ability to edit various metadata information.
![image](https://github.com/files-community/Files/assets/36911157/d222ee3b-3e34-4d58-a040-d23fccd89143)

Information from Metadata I usually look at and edit.

- Authors
- Last Author / Last Saved by
- Date Created
- Date Modified
- Title
- Copyright
- File Attributes
- Tags

Of course, the more info the merrier.
(Perhaps a plugin support, so only those who need this, can use it? I'd personally love to not bee the file ICON/Preview in the Details button cause it is there in the Preview button. But that is personal preference, so plugins by others would be an amazing idea.)

### Requirements

- This proposal will accomplish Edit and View various Metadata information.
- This proposal will accomplish Users validating and confirm if a File looks suspicious.
- This proposal will accomplish Toggles so the Files app is more customizable to the User.

(Perhaps a Tab in Settings called Customization/Preferences)?

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2361

### Comments

Btw, is the icon on the ReadMe files of this GitHub, different from the actual App icon?

ReadMe has a pure Yellow with darker yellow layers.
Actual App has a Blue water flow (Which I love the design of)

Took me a while to double-confirm I was looking at the right GitHub Repo.

**Comment by yaira2** [comment]
> Btw, is the icon on the ReadMe files of this GitHub, different from the actual App icon?

The icon in the readme is the new icon coming in v3.

**Comment by yaira2** [comment]
@SandeeepKiran you should already be able to edit metadata from the properties window, is this not working?

**Comment by SandeeepKiran** [comment]
> @SandeeepKiran you should already be able to edit metadata from the properties window, is this not working?

I am unable to edit the meta data. 
I would love to be able to see more Meta-data and view them more easily. But this does feel like a plugin sort of feature request. But I'd love to see a native ability.



> > Btw, is the icon on the ReadMe files of this GitHub, different from the actual App icon?
> 
> The icon in the readme is the new icon coming in v3.

Awwe, I prefer the current icon of Yellow with Blue wave. I will make a copy of the .ico file then. (hopefully an option to change icons)

(hope I am not making too many feature request.)

**Comment by yaira2** [comment]
What happens when you try editing meta data from the properties window?

**Comment by yaira2** [comment]
@SandeeepKiran
