### ISSUE TITLE
Can't install classic installer and Preview won't launch

### ISSUE THREAD

**Issue by ketonik** [files-community/Files#13445]
### Description

https://files.community/download

Files.preview.appinstaller won't install 
![Screenshot 2023-09-29 115127](https://github.com/files-community/Files/assets/49221849/9b07e03d-be9a-42de-aecd-6372924cc6f2)

![Screenshot 2023-09-29 115136](https://github.com/files-community/Files/assets/49221849/b319e265-e2ae-4aea-ae55-c105f020d1bb)

The Files.Stable.exe actually does install but it won't launch when not connected to the internet.
![Screenshot 2023-09-29 114444](https://github.com/files-community/Files/assets/49221849/4594bc8a-bf49-43d8-b021-089871aed2f9)

![Screenshot 2023-09-29 114456](https://github.com/files-community/Files/assets/49221849/e30a5173-9f31-4313-8090-23461744b806)

### Steps To Reproduce

Download https://files.community/download
https://files.community/appinstallers/Files.preview.appinstaller
results in 1.63KB file, it won't install with or without internet

Download https://files.community/appinstallers/Files.preview.appinstaller
Install refuses to install with no internet, will install with internet but only launches with internet.

### Requirements

- e.g. Fix crash that occurs when...
won't launch see screenshots of versions and errors.

### Files Version

well whatever the version is on those links

### Windows Version

Windows 11 Pro N 23H2 22631.2361

### Log File

[debug.log](https://github.com/files-community/Files/files/12755899/debug.log)

**Comment by Josh65-2201** [comment]
You can try
1. Opening PowerShell as administrator
2. Run this command
```Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/stable/Files.Package.appinstaller```
3. See if Files is in the start menu all apps section

**Comment by ketonik** [comment]
Hey Josh I ran this in Powershell:
Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/preview/Files.Package.appinstaller

and yeah it had some progress in the Powershell and then Files Preview populated in Start Menu Apps, and yes without internet it launched, but slowly.

Bizarre, seems the installer needed internet and the old installer needed internet to launch after app was installed.

Just noticed same issue with Notepads app https://www.notepadsapp.com
Just wouldn't launch without internet.

**Comment by Josh65-2201** [comment]
It could be an issue with your Windows Install. The slow opening is a general issue in stable that will be fixed for v3, there's no timeline line for when it will be released.

**Comment by ketonik** [comment]
Well same issue just happened, rebooted, and because I left Files open, and my machine does not auto connect to WIFI, Files shows that 'Can't open app package' error window. I have to close it, connect to WIFI then relaunch Files for it to open.
This is a new install since 2 hours ago .

![Screenshot 2023-09-29 193544](https://github.com/files-community/Files/assets/49221849/f4b0198d-8758-409b-b056-df34283e0b92)

What a lousy OS, everything's a drama, snipping tool as well, windows key+shift+S won't save the screenshot anywhere, not even a screenshot folder in Pictures...not even a save to folder preference in Snipping tool...wow.

**Comment by Josh65-2201** [comment]
Check the Microsoft store for updates as Snipping tool does have a save to pictures option in settings.
![image](https://github.com/files-community/Files/assets/26977075/745e0e54-6053-4739-80fc-cfc9312b572e)

**Comment by ketonik** [comment]
Screenshot here, there's no user defined save directory, it never asks to save even though the toggle is on, WTF??

![Screenshot 2023-09-29 200529](https://github.com/files-community/Files/assets/49221849/ce0a90cd-fa1d-4eff-a815-69431033f205)
