### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by pablo-hp** [files-community/Files#13446]
### Description

The application has been displaying an error message just for being open.

### Steps To Reproduce

The application has been displaying an error message just for being open.

### Requirements

The application has been displaying an error message just for being open.
[debug.log](https://github.com/files-community/Files/files/12762902/debug.log)

### Files Version

2.5.21.0

### Windows Version

22621.2361

### Log File

[debug.log](https://github.com/files-community/Files/files/12762920/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by yaira2** [comment]
Is the app actually crashing? Or is it just displaying a notification that an error occurred?
