### ISSUE TITLE
Background

### ISSUE THREAD

**Issue by pablo-hp** [files-community/Files#13444]
### What feature or improvement do you think would benefit Files?

It seems that when the application is closed, it does not continue running in the background.
I would like to suggest the option of allowing the application to run in the background, even after closing it.
This would speed up opening and closing the application.

### Requirements

- Possibility to minimize to the taskbar when closing.
- Continue running in the background in a hidden way.
- Always keep it initialized.

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2361

**Comment by yaira2** [comment]
Thakn you for your feedback, the preview version of Files has this option. You can download the preview from our website https://files.community/download.
