### ISSUE TITLE
Bug: BitLocker locked drive doesn't update on unlocking

### ISSUE THREAD

**Issue by baloo32** [files-community/Files#13443]
### Description

When viewing the drives list on the Home Tab, or under the Drives treeview option, the icon for a drive that is locked due to BitLocker correctly shows a standard Windows 10 drive with the lock icon:

![image](https://github.com/files-community/Files/assets/10596679/91f8cf6d-63f1-4834-bb7f-40dcdd463e15)

However, accessing the drive, then unlocking it does not refresh the view of the drive - the icon remains and there are no properties shown for the drive, even though it is now unlocked and accessible in both Files and File Explorer.

The navigation breadcrumb also remains showing "Network" rather than the drive name and letter:

![image](https://github.com/files-community/Files/assets/10596679/2f152b1c-057c-4f75-851c-f7bcdd32d421)

### Steps To Reproduce

1. Open Files app on a device with a locked (encrypted) BitLocker drive
2. Access the drive (click, whatever) and enter the requested password to unlock
3. Go back to Home or view Drives treeview option - icon not refreshed, no properties for drive shown, however is fully accessible in Files.

### Requirements

When accessing a BitLocker drive and unlocking, the icon and drive properties should be refreshed in Files to update the relevant properties for the drive in the display.

### Files Version

2.5.21.0

### Windows Version

10.0.19045.3516

### Log File

[debug.log](https://github.com/files-community/Files/files/12751333/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
Is everything displayed correctly after reopening Files? We're tracking the icon issue in #10367 & #6182.

**Comment by baloo32** [comment]
> Is everything displayed correctly after reopening Files? We're tracking the icon issue in #10367 & #6182.

The icon is refreshed correctly after closing and re-opening Files, as well as the drive stats on hover, but have noticed the navigation breadcrumb remains showing as "Network" rather than update to show the drive letter (so very minor).

![image](https://github.com/files-community/Files/assets/10596679/53acd1dd-d2c4-420f-85eb-f05ec4789d10)

**Comment by yaira2** [comment]
The breadcrumb issue is different, if it's still in issue the latest preview build, please open a separate issue so we can track it.
