### ISSUE TITLE
Compact view

### ISSUE THREAD

**Issue by alibaubau** [files-community/Files#13442]
### What feature or improvement do you think would benefit Files?

Files lacks a very compact view when user has to manage a lot of files or folders, as they are displayed in Explorer selecting WIN_key_5 and Compact View.
This requirement impacts, imho, a lot of people.

### Requirements

Comparaison of Windows Explorer and Files:
![explorer_NeCMJEh52i](https://github.com/files-community/Files/assets/100225750/095bde1c-31fa-42ff-8bf8-62fca7853ea9)

### Files Version

v2.5.21

### Windows Version

22H2 b22621

### Comments

Btw, congratulations for this otherwise excellent work!

**Comment by Josh65-2201** [comment]
Thanks for the feedback, I assume you want the list view

**Comment by yaira2** [comment]
Have you tried enabling the compact spacing option and switching to the details layout?

**Comment by alibaubau** [comment]
> Thanks for the feedback, I assume you want the list view from Windows File Explorer
Yes, it should be the List (Elenco in Italian version); my purpose is to scroll quickly through long list of files.
Anybody which have an extensive use of a pc does not use any touch screen and meets occasionally hundredths or thousands items in a single directory, and then Files become quite useless.

**Comment by alibaubau** [comment]
> Have you tried enabling the compact spacing option and switching to the details layout?

Yes, I tried it: the effect is the halving vertically of the Files windows and the inibition of any resizing of it.

**Comment by Josh65-2201** [comment]
Merging with #2509. You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
> the inibition of

That's correct, it's for a different use case, but I thought it might be a good workaround until we add the List View layout. Anyways, I suggest subscribing to #2509 to be notified when it's implemented.

**Comment by yaira2** [comment]
@alibaubau thank you for your patience, I'm excited to share that a List View layout will be included in the next release.
