### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by theoneand33** [files-community/Files#13449]
### Description

It just keeps crashing sometimes because I am trying to change system stuff but it mostly just randomly crashes (I am using files preview)

### Steps To Reproduce

1. open files (preview)
2. do other stuff.
3. wait
4. crash

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

2.5.29.0

### Windows Version

10.0.19045.3448

### Log File

[debug.log](https://github.com/files-community/Files/files/12772614/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, What are you doing before it crashes?

**Comment by yaira2** [comment]
@theoneand33
