### ISSUE TITLE
load shell extensions before opening context menu

### ISSUE THREAD

**Issue by mio-19** [files-community/Files#13450]
### What feature or improvement do you think would benefit Files?

Make context menu usable with shell extensions.
Currently the context menu changes its size and button positions after loading shell extensions. This results in misclick and an uncomfortable experience.

### Requirements

+ Load shell extensions faster https://github.com/files-community/Files/issues/11112
+ Don't show the context menu before shell extensions are fully loaded

### Files Version

2.5.29.0

### Windows Version

22621

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #11112. You can check there or click subscribe in the right sidebar for updates.

Right now doesn't make sense to delay the context menu showing as that make it less responsive. Instead you should enabled `Files settings > Genral > Move shell extensions into a sub menu` until the speed is improved
