### ISSUE TITLE
Details View, expand Sub folders to view contents

### ISSUE THREAD

**Issue by ketonik** [files-community/Files#13451]
### What feature or improvement do you think would benefit Files?

Will Files ever be able to allow user to expand Sub folders to view contents in Details View?

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z
This is a convenient way to deal with the directory structure, on such example is dealing with compressed archives, like zip, rar etc, often on windows people nest the files in a siping folder that’s inside the same name of the main folder, so user wants to move the files form those sub folders to the root of the directory. 

This procedure is a pain in the a$$ on M$ Windows, user has to fiddle around moving back and forward in the hierarchy, get the files, either copy and paste or have the root folder in another tab and drag the files too it.

This is way easier in List View on macOS.

### Files Version

all

### Windows Version

All

### Comments

see screenshots of macOS Finder List view sub folders example.

![image](https://github.com/files-community/Files/assets/49221849/4e7c5430-92b8-473c-a97b-e3f6b138efe1)

![image](https://github.com/files-community/Files/assets/49221849/d961d82e-f168-466d-9a86-e877c3a98c34)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #1928. You can check there or click subscribe in the right sidebar for updates.
