### ISSUE TITLE
Bug: File names don't update if renamed from the search results page

### ISSUE THREAD

**Issue by andstrat** [files-community/Files#13456]
### Description

A tagged file was not updated in the 'tags' view after renaming it in the respective 'tags' view. 

### Steps To Reproduce

1. Do a search and rename one of the files
2. Observe that the search page needs to be refreshed for the name to update

### Requirements

- Auto refresh the name without having to refresh the page

### Files Version

4.5.21.0

### Windows Version

22621.2361

### Log File

no log

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
I was able to reproduce this issue
