### ISSUE TITLE
Modal filecopy/filetransfer window dress and UX responsivity

### ISSUE THREAD

**Issue by nordquistdave** [files-community/Files#13453]
### What feature or improvement do you think would benefit Files?

Modal file transfer should bring an overall visual effect to the affected window relating its condition; users can be aware of large transfers and pending work to USB flash disks (by other than the arc over the Ongoing Tasks button and trying things to see if they're affected by modal copy.) Then people can switch focus to other matters pending operation completion!

### Requirements

//* Nope: it's not a dismissable window.  Clicking on the Ongoing Tasks status button will have its dialogue dismissable by Esc as well as clicking again on the same button.
Windows doing modal file transfer which are made busy more than a tooltip timeout (or say, 8 seconds) will have their lockouts visually indicated by a blue slash or arrow indicating the Ongoing Tasks button; people will know why their window action is unresponsive!

The window dress of a modal file transfer may warn of filesystem _lag_: 

- USB flash drive mounted for fast USB 3.2 transfers (in Windows,) or whether Windows has in fact hobbled things in the interest of user reportability (user eject stability, supposedly;) users may want to change the access type to fast in Device Manager, only that method forces a reset to be effective?!
- git, ftp, or cloud action affected by slow uplink as 30kbps or lower per returned TCP headers or (.....)

### Files Version

2.5.29.0

### Windows Version

10.0.22621.2283

**Comment by Josh65-2201** [comment]
Thanks for the feedback, this doesn't make sense what issue are you having with the ongoing task flyout?

**Comment by yaira2** [comment]
@nordquistdave can you try to clarify the feature request?

**Comment by nordquistdave** [comment]
Sorry, I expected the task flyout would be dismissed if I hit escape, but it isn't. On the other hand some things about the window are modal (the window can't be moved or resized?) and some are not (one can rightclick sidebar items to open new windows or perhaps tabs)...so maybe it's not quite modal? N0b to the product, sorry.

**Comment by yaira2** [comment]
It's a flyout menu, it's not a window...
