### ISSUE TITLE
Add Files as auto play target when inserting removable drives

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#1345]
Please register Files UWP as an AutoPlay target so that I can configure Files to launch when I insert a removable drive.

**Comment by hunterlan** [comment]
This screenshot and references will help you:

![image](https://user-images.githubusercontent.com/38838841/89122122-88662080-d4cd-11ea-8249-167840ce8ed1.png)

[Registering AutoPlay Event Handlers](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/windows-media-center-sdk/aa468474(v=msdn.10)?redirectedfrom=MSDN)
[How to Register a Handler for a Device Event](https://docs.microsoft.com/ru-ru/windows/win32/shell/how-to-register-a-handler-for-a-device-event?redirectedfrom=MSDN)

**Comment by yaichenbaum** [comment]
We don't have plans to implement this option however v2.0.34 added support for setting Files as the default file manager.
