### ISSUE TITLE
Show full path on mouseover or on rightclick to Properties

### ISSUE THREAD

**Issue by nordquistdave** [files-community/Files#13452]
### What feature or improvement do you think would benefit Files?

Add a properties RMB action to give a full path and/or Properties for a file (or multiselection.)

### Requirements

This proposal will accomplish feature parity with Properties (give or take file comments and security context) on UN*X and other platforms.
This proposal gives tooltip option with full path and file size.
This proposal offers normal visual closure for users looking at rightclick options.
Other user offerings than serotonin (from familiarity with Properties in rightclick menu,) can be made available at this UX point as product distinction; using conditioning to capsaicin, BL manga, magnet fuckery near a laptop hinge hall sensor, enby fun, car safety radio participation, or ATSC3 signal chain entry points.

### Files Version

2.5.29.0

### Windows Version

10.0.22621.2283

**Comment by Josh65-2201** [comment]
Thanks for the feedback, are you requesting that the full name of a file/folder is shown when hovering the textbox in the properties window?

**Comment by nordquistdave** [comment]
No, I couldn't find a way to open the properties window among rightclick options.
Now that I look, the full name of a file _is_ shown as a tooltip when hovered over. (Not so much folders.) The Preview pane offers that info along with full path, but not size totals for multiselection (not for .mkv files anyhow.) Maybe in dual-pane mode? What can the gloaming spinner mean is pending in background workers with my .rar or video file. is it silently judging?

**Comment by Josh65-2201** [comment]
Properties is opened with the wretch icon same as the tool bar at the top or bottom of the right click menu. 
File size is shown when selecting multiple files in the properties menu and bottom left of the status bar. If you want it for folders or a mix of files and folders you have to go to enable `Files settings > Folders > Calculate folder sizes`.
