### ISSUE TITLE
List view

### ISSUE THREAD

**Issue by cudBwrong** [files-community/Files#13459]
### What feature or improvement do you think would benefit Files?

A view (pane layout option) which corresponds to list view in File Explorer, so that it is possible to see many file names, in multiple columns within a single panel.  It now is possible to turn off all the columns except "Name" in detail view, but you are left with only a single column of names.  This requires a long scroll to find a file in a crowded folder.

### Requirements

A new pane layout option, corresponding to list view in file explorer, will improve usability.

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2283

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #2509. You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
@cudBwrong thank you for your patience, I'm excited to share that a List View layout will be included in the next release.
