### ISSUE TITLE
Nice to have for me at least.

### ISSUE THREAD

**Issue by mmz65** [files-community/Files#13455]
### What feature or improvement do you think would benefit Files?

I was trying to change some of the settings.  So I put in comments for the original items so I could undo the changes.  It would appear the comments may not be available for a configuration file.  The attached file includes one type of a comment.  I also tried /* */ and :: all of which failed.

It would not have to follow the C coding type of comment.  It could be a sample as placing a "#" that the beginning of the line as in Linux. 

Thank you for considering.

mmz

[user_settings.zip](https://github.com/files-community/Files/files/12775756/user_settings.zip)

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z
It has been years since I coded in C.
Therefore this would be outside of my knowledge.

### Files Version

2.5.21.0 

### Windows Version

Edition	Windows 11 Pro Version	22H2 Installed on	‎9/‎28/‎2022 OS build	22621.2361 Experience	Windows Feature Experience Pack 1000.22674.1000.0

### Comments

Thank you for the program.  I have used it to replace Windows Explorer following your directions.  This has allowed me to use Explorer Patcher and I now have it nearly setup to be usable again.

**Comment by Josh65-2201** [comment]
The files are stored as json you can try using `"_comment": "comment text goes here...",`

**Comment by mmz65** [comment]
Very good, it would appear that I was looking at C and I needed to be looking at json.
Thanks very much Josh65.
I would say at this point that this can be closed as not needed.

**Comment by Josh65-2201** [comment]
Great
