### ISSUE TITLE
Move and Cut Keyboard Shortcut not usable

### ISSUE THREAD

**Issue by jouyhouy** [files-community/Files#13460]
### Description

This is easily reproduced in preview. Just hold shift or ctrl when you drag files between folders. Usually the right click pop-up shows up and it's kind of a hassle to have to click again.

### Steps To Reproduce

Just hold shift or ctrl when you drag files between folders. 

### Requirements

when you drag files between folders. 

### Files Version

2.5.29.0

### Windows Version

22621.2283 (Windows 11)

### Log File

[debug.log](https://github.com/files-community/Files/files/12777748/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I am unable to reproduce this. What folders are you dragging to and from?

**Comment by jouyhouy** [comment]
I have an idea! I was moving a file from a folder in Files, to Desktop! This would do the trick. 
I tried and moving between Files is ok.

**Comment by jouyhouy** [comment]
The popup is actually the one you'll see if you move files with right mouse button.

**Comment by yaira2** [comment]
Thank you for your feedback. This feature isn't currently available, but is being tracked in #1396.
