### ISSUE TITLE
File Icons

### ISSUE THREAD

**Issue by saint4eva** [files-community/Files#1346]
Many files and media files do not have associated file icons for their file extension. So many files are just plain.

**Comment by duke7553** [comment]
@saint4eva What types of files? Is this a OneDrive folder?

**Comment by Talisman39ar** [comment]
I get this sometimes too. E.g. just looked in my downloads folder (so not OneDrive) and a couple of PDFs had blank icons. Or image files will show a generic image icon. If I switch from grid to list view, the icons appear properly, and then if toggle back to list view the icons are showing again (PDF icons, or image thumbnails). So just seems to be an icon rendering or cacheing issue.

**Comment by saint4eva** [comment]
> @saint4eva What types of files? Is this a OneDrive folder?

Media files - mkv and avi. And some pdf files

**Comment by RudySPG** [comment]
![image](https://user-images.githubusercontent.com/37492880/102127347-3f21c800-3e01-11eb-93e8-fc331fd3298a.png)
Having the same issue no icons at all only folders get icon everything else is just default

**Comment by yaichenbaum** [comment]
@saint4eva Is this still an issue in v1.5?
