### ISSUE TITLE
Consider Adding Sort By Time Taken for Images

### ISSUE THREAD

**Issue by jouyhouy** [files-community/Files#13461]
### What feature or improvement do you think would benefit Files?

When I import pictures from my phone, the photos are either sorted by time created or time edited, which both equal  the time they're imported. Since File Explorer supports sorting by time taken, could Files possibly have this? 

### Requirements

- This proposal will add sorting by shot time for pictures. 

### Files Version

2.5.29.0

### Windows Version

windows 11

**Comment by jouyhouy** [comment]
Actually that basically means Files add more columns of info for pictures. They can be resolution, time taken, etc. Just like the File Explorer does for pics.

**Comment by Josh65-2201** [comment]
Thanks for the feedback, this will likely be implemented with #8366. You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
As Josh shared, this will come together with #4432 and #8366.
