### ISSUE TITLE
Bug: Crash after changing column size

### ISSUE THREAD

**Issue by Blank-1973** [files-community/Files#13469]
### Description

Crashes after pressing "Size AII Columns to Fit" 
Crashes after changing, adding, or reducing column size
Not fixed from old version

### Steps To Reproduce

1.Press "Size AII Columns to Fit" 
2.Crash

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2361

### Log File

[debug.log](https://github.com/files-community/Files/files/12798679/debug.log)

**Comment by hishitetsu** [comment]
This seems to be a bug in LiteDB v4. We will need to upgrade to v5 or manually assign index numbers.
https://github.com/mbdavid/LiteDB/issues/1319

**Comment by Blank-1973** [comment]
I'm not very good at it and I don't know what to do.
If you don't mind, please let me know how to do it.

**Comment by hishitetsu** [comment]
Oh sorry, my comment is to the dev team.
If you have this problem going on, resetting Files app from Windows settings may solve the problem.

**Comment by yaira2** [comment]
> This seems to be a bug in LiteDB v4. We will need to upgrade to v5 or manually assign index numbers. [mbdavid/LiteDB#1319](https://github.com/mbdavid/LiteDB/issues/1319)

It would be great if we could update but I think there were some build errors.

**Comment by ferrariofilippo** [comment]
> This seems to be a bug in LiteDB v4. We will need to upgrade to v5 or manually assign index numbers. [mbdavid/LiteDB#1319](https://github.com/mbdavid/LiteDB/issues/1319)

In #11585, @hez2010 pointed out why we can't upgrade to v5

**Comment by yaira2** [comment]
Is this still relevant with WinAppSdk?

**Comment by hez2010** [comment]
We can move any LiteDB related operations to a singleton process so that it won't face concurrency issue.
Merging with #13632
