### ISSUE TITLE
Tag function improvement

### ISSUE THREAD

**Issue by psny83** [files-community/Files#13467]
### What feature or improvement do you think would benefit Files?

seems like the tag function is not fully functioning. tag only works on the current window, when I open a new window or tab tag disappears. I wish tags could be recognized throughout the whole file system. not only on the current window.

and also I was using quicklook, and it's been very glitchy with the app, let me know if this is a known issue.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.5.21.0

### Windows Version

10.0.19045.3448

**Comment by Josh65-2201** [comment]
Thanks for the report. Please use the bug report option including the location of files/folder you are applying the tags too. Also any issue you have with Quick look make a separate bug report.
