### ISSUE TITLE
Make a manager in the Files bucket. 

### ISSUE THREAD

**Issue by DarkTrailDog** [files-community/Files#13474]
### What feature or improvement do you think would benefit Files?

Make a manager in the Files bucket. I installed the application, but when you go to the trash, the old explorer still opens, how can I fix it? Or can I make more precise settings for this? So that the Files explorer is also in the trash.

### Requirements

Make a manager in the Files bucket. I installed the application, but when you go to the trash, the old explorer still opens, how can I fix it? Or can I make more precise settings for this? So that the Files explorer is also in the trash.

### Files Version

2.5.29.0

### Windows Version

windows 11 PRO 10.0.22621.2361

### Comments

Make a manager in the Files bucket. I installed the application, but when you go to the trash, the old explorer still opens, how can I fix it? Or can I make more precise settings for this? So that the Files explorer is also in the trash.

**Comment by Josh65-2201** [comment]
You can enabled the set as default option in Files settings > Advanced >set as default. This option is not always going to work due to Windows limitations and wont work for open/save dialogs.
