### ISSUE TITLE
Quality-of-Life/Safety features

### ISSUE THREAD

**Issue by HammerOfDaGods** [files-community/Files#13479]
### What feature or improvement do you think would benefit Files?

These are some features that, in my admittedly shallow knowledge of programing, seem fairly easy to implement, would improve the QoL of the program, and/or provide useful safety features that would allow some possible difficulties/bugs to be avoided or worked around, improving the overall usefulness of "Files".

### Requirements

**1. Add an option/toggle and/or preferably a hotkey (such as holding ctrl, alt, shift, or windows key, while right clicking) to allow users to use the default system right click menu.** Many users who would want to use this application are also the kind of people who are "Power Users" of Windows, and as such may be like me and have additional options or applications that interact with or change the right click menu. I, for example, have noticed a few issues with the "Files" right click menu interacting with my changes. 
- I use [NileSoft Shell](https://nilesoft.org/), so I already have a system-wide menu replacer that I like and provides all the functionality/style I need. It is actually quite similar to the one you have implemented in "Files" but is separate and completely configurable.
- I have made registry edits to give myself some custom right-click menu options and programs that also do this that I don't want to have to go through 3 menus to use (ex. 7-zip). 
- One application I use, [LinkShellExtension](https://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html), which is used to easily create symbolic/hard/etc. links, is being prevented from properly functioning. It is supposed to allow me to select a link source, and then the menu item changes to "Drop Here..." allowing me to select what type of link I would like to create. The right-click menu included in "Files" does not allow me to select my link source, only giving me the "Drop Here..." option, which ends up throwing an error since I was never allowed to select my source.

**2. Add an option to opt-out of the "Ongoing Tasks" feature, allowing the normal copy/move/delete/etc.** boxes to pop up like normal. I used "Files" long ago so this may no longer be as much of an issue, but back then I ran into multiple issues with file moving where the move process would freeze up with no easy way to terminate the process since it was integrated into this feature.

**3. Provide a method to enable/disable the default explorer.exe replacement feature (a script or .reg file provided on the GitHub page for example would do just fine), or provide a backup method that still allows me to launch the default explorer if needed.** The desire for this feature also stems from an issue I had when I used this program long ago, wherein when I started Windows in safe-mode with the replacement feature enabled, my entire explorer process, including the taskbar and start menu were completely unusable (would not launch at startup correctly and would crash when I tried to launch it manually). While that particular issue may or may not have been resolved, especially since Microsoft separated the file explorer from those processes, any fatal failure/crash of "Files" would leave some users completely unable to fix the issue since the only way to disable the feature is within the program that would be failing/crashing.

### Files Version

2.5.21.0

### Windows Version

10.0.22631.2338

**Comment by Josh65-2201** [comment]
Thanks for the feedback, In future please make separate issue for different feedback.

> allow users to use the default system right click menu

This isn't possible as Files doesn't have access to the code Windows File Explorer uses for there context menu


> Add an option to opt-out of the "Ongoing Tasks" feature,

Files is using the same system as Windows File Explorer just with a different UI. Improvement to the UI are coming in v3


> Provide a method to enable/disable the default explorer.exe replacement

There already is in Files settings > Advanced

**Comment by yaira2** [comment]
> This isn't possible as Files doesn't have access to the code Windows File Explorer uses for there context menu

Just to clarify, we could technically show the File Explorer context menu, but it wouldn't make sense for Files. For example, options like copy, paste, create new item, properties, layout mode, and sort by are linked to File Explorer. There are also a number of features present in the Files context menu that don't exist in the File Explorer menu. If there is a specific feature you feel is missing, please open a feature request and we'll take a look.

> I have made registry edits to give myself some custom right-click menu options and programs that also do this that I don't want to have to go through 3 menus to use (ex. 7-zip).

There is a setting to show shell extensions in the main menu, in the future we'd like to explore adding some more flexibility around this behavior, but perhaps this will help in the meantime.

> 2. Add an option to opt-out of the "Ongoing Tasks" feature, allowing the normal copy/move/delete/etc. boxes to pop up like normal. I used "Files" long ago so this may no longer be as much of an issue, but back then I ran into multiple issues with file moving where the move process would freeze up with no easy way to terminate the process since it was integrated into this feature.

We have a number of improvements coming to file operations in the next update. If you're still experiencing those issues after v3 is released, it'll be great if you could report them so we can investigate.

**Comment by HammerOfDaGods** [comment]
@Josh65-2201 
> In future please make separate issue for different feedback.

Will do. I thought it'd be better/cleaner to consolidate, but I will do it however the devs prefer.

> The option also doesn't replace or disabled explorer.exe so the safe mode issue is likely unrelated.

Like I said, it was a long time ago, so it probably isn't an issue anymore, although now I may test it. Keep in mind this was way back when the feature was in the "Experimental Features" section. It was however, caused by the replacement feature in "Files". I would go into safe-mode with the feature enabled and it would crash everything related to the explore.exe, then I would go back into normal mode and disable the feature, go back to safe-mode and everything would work.

> uninstalling Files will revert and tell you that it has when opening Windows File Explorer.

Great! This must be a feature implemented after I quit using "Files" the first time, because I remember trying uninstallation before when I had the issue and the issue persisted until I reinstalled "Files" and disabled the feature with the toggle. If uninstalling will revert the change now however, this satisfies my request.

@yaira2 
> If there is a specific feature you feel is missing, please open a feature request and we'll take a look.

I'll make separate requests for these issues per Josh's request, but I'll just mention them here. The LinkShellExtension mentioned in the OP is indeed broken with the current context menu, and the BitDefender context menu does not show up at all.
[LinkShellExtension support feature request](https://github.com/files-community/Files/issues/13481#issue-1930765313)
[BitDefender context menu feature request](https://github.com/files-community/Files/issues/13482#issue-1930767074)

> There is a setting to show shell extensions in the main menu

My mistake! This satisfies how I want it to work, although personally I would like the ability to make it show the whole menu without scrolling. I will make a separate request for that though. Apologies for my stupidity, I should have tested more options/configs.
[Context menu full menu vs. scrolling menu feature request](https://github.com/files-community/Files/issues/13483#issue-1930767731)

**Comment by yaira2** [comment]
> My mistake! This satisfies how I want it to work, although personally I would like the ability to make it show the whole menu without scrolling. I will make a separate request for that though. Apologies for my stupidity, I should have tested more options/configs.

No worries! We try to make all the settings easy to discover, but it's hard to learn everything at once :)
