### ISSUE TITLE
Quicklook

### ISSUE THREAD

**Issue by YaolinGe** [files-community/Files#13470]
### What feature or improvement do you think would benefit Files?

A quick-look preview would be fantastic to have as people from MacOS are used to using this feature to have a quick glimpse over the content of the file, image, or audio. It is very efficient. 

### Requirements

- This proposal will accomplish the quick-look preview over an individual file so that the user can use the space bar to activate the preview of the image, file or audio or other file types. 
- Try this feature on MacOS, then you will understand what I mean. 

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2283

**Comment by yaira2** [comment]
Thank you for your feedback. We are considering building a feature like this, but in the meantime, Files has support for QuickLook https://www.microsoft.com/store/productid/9NV4BS3L1H4S?ocid=pdpshare and SeerPro https://www.microsoft.com/store/productid/9PGVFJBVBZWX?ocid=pdpshare.
