### ISSUE TITLE
Feature: Change the status center/ongoing task icon to be more descriptive.

### ISSUE THREAD

**Issue by Aealith2839** [files-community/Files#13478]
### What feature or improvement do you think would benefit Files?

I believe there is something wrong with the way this works.
The first icon is I think quite clear and most users can uderstand a task is underway. Passing the cursor over popups the message 'Ongoing Tasks' which is equally perfectly clear.
Now, when the task is completed, the first icon is replaced with another one which is NOT clear at all. It has no meaning whatsoever. Worst, the message is strictly identical between the task going on and the task is completed. So that is confusing.

I believe you need a better second icon (simpler graphically and clear, obvious) and another message, distinct from the first one.

### Requirements

- Another icon
- A distinct message such as 'Done' or whatever

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2361

### Comments

Action going on:

![Capture d'écran 2023-10-05 205436](https://github.com/files-community/Files/assets/147099687/526e66f5-27ce-4013-9891-c249893ed97d)

Task completed:

![Capture d'écran 2023-10-05 205501](https://github.com/files-community/Files/assets/147099687/636fb7c5-d493-448c-8ca1-6debe02565ac)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, I've added this to the project board. Also ongoing tasks is the name of the flyout and doesn't mean that tasks are going on. In v3 this will be renamed to status center I believe anyway.

**Comment by yaira2** [comment]
This is addressed in the preview builds (some of the improvements are still in the development branch).

**Comment by Aealith2839** [comment]
Alright. Thank you !
