### ISSUE TITLE
save icons layout in  each folder  the  way  window xp  does  and   not  for  desktop only  

### ISSUE THREAD

**Issue by THEpErplexed** [files-community/Files#13475]
### What feature or improvement do you think would benefit Files?

it is the only one  feature that is missing  from  all  managres out there, even most popular ones ,
despite  it is  a very  intuitive  way  to manage files  and  folders .
it was  removed from  windows 8 and  beyond  allegedly  for  security  reasons but  it  could  have  been  remained  as  an   optional feature .
is  it  possible to  implement that   in  Files.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

all 

### Windows Version

win 10

**Comment by Josh65-2201** [comment]
Thanks for the feedback, can you clarify what you mean by icon layout. If you mean folder icons you can already change them in the properties of the folder.

**Comment by yaira2** [comment]
I think this is requesting support for dragging icons anywhere on the screen as opposed to aligning them to a grid. We've considered this idea but we don't currently have plans to add this feature.
