### ISSUE TITLE
Proton Drive not recognised as a Cloud Drive in Files Preview

### ISSUE THREAD

**Issue by runnylogan** [files-community/Files#13472]
### Description

After installation of the Proton Drive client, it doesn't appear under the Cloud Drives section of the navigation pane. The content is accessible by navigating through the C: drive folder structure.

### Steps To Reproduce

1. Install client available from https://proton.me/drive/download
2. Start Files Preview where Proton Drive is not listed
3. Restart PC
4. Start Files Preview where Proton Drive is not listed

### Requirements

- recognise the Proton Drive client and present it on the Cloud Drive section of the navigation pane.

### Files Version

2.5.29.0

### Windows Version

10.0.22622.575

### Log File

[debug.log](https://github.com/files-community/Files/files/12805950/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, support for Proton is available in the development branch and will be included when v3 is released..
