### ISSUE TITLE
Rounded App Corners

### ISSUE THREAD

**Issue by TheDolphinSlayer** [files-community/Files#13487]
### What feature or improvement do you think would benefit Files?

On windows 10, the default corners are sharp, can we have the option to have them rounded like windows 11?
![image](https://github.com/files-community/Files/assets/73983610/6e75c885-7878-402c-9485-0133b15d76a5)

### Requirements

Rounded Corners

### Files Version

2.5.29.0

### Windows Version

10.0.19045.3516

**Comment by Josh65-2201** [comment]
Thanks for the feedback, This doesn't make sense to add just for Files on Windows 10 as Files tries to follow Windows guidelines for looks and I'm not sure it even possible. But there are probably programs that can do this on a system level.

**Comment by yaira2** [comment]
@TheDolphinSlayer thanks for the feedback. The rounded corners are handled by Windows so you can get them by upgrading to Windows 11.
