### ISSUE TITLE
Allow full context menu without scrolling (Toggle in settings)

### ISSUE THREAD

**Issue by HammerOfDaGods** [files-community/Files#13483]
### What feature or improvement do you think would benefit Files?

Add a toggle in the settings to allow the full context menu to be shown without scrolling. I'm sure some like the more compact menu, but I personally just want to have quick view and access to all my context menu options.

### Requirements

Pretty straightforward. Provides more user choice/customization.

### Files Version

2.5.21.0

### Windows Version

10.0.22631.2338

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Are you talking about the more menu as that can already be turned off in Files settings > General > Move shell extensions into a sub menu

**Comment by HammerOfDaGods** [comment]
> Are you talking about the more menu as that can already be turned off in Files settings > General > Move shell extensions into a sub menu

No. Currently the options are to either have a small menu, moving additional context menu items to a sub-menu, or have all context menu items shown in a scrolling list. What I would like is for a full, long context menu with no scroll bar, like the one below.
![image](https://github.com/files-community/Files/assets/94164260/ec4435c7-a5a4-419e-943b-3dffdeb7b08b)

**Comment by Josh65-2201** [comment]
Thanks for the clarification, I've added this to the project board.

**Comment by yaira2** [comment]
Thank you for the feedback, we're tracking this one in #9506.

**Comment by HammerOfDaGods** [comment]
Wonderful! Thank you!

You may want to remove it from "Done" on the project board if it's still in progress.
