### ISSUE TITLE
Unable to use top of Files window to produce a shorter window height

### ISSUE THREAD

**Issue by nigiriemoji** [files-community/Files#13488]
### Description

For some reason when I have Files open, I cannot use the top bar to change the window size, specifically the height. I can adjust the left, right, and bottom edges of the window perfectly fine. But the top I cannot. I am on Windows 11. Click clicking on top edge and trying to reduce height, the entire window shifts down as if I'm clicking the tab bar section (where it would normally move a window).

### Steps To Reproduce

1. Open Files
2. Move mouse cursor over the top edge of the Files window
3. Attempt to click and hold mouse, see icon change to the north and south directional arrows icon
4. Move mouse cursor down
5. See bug of entire window moving downwards, rather than screen size going shorter

### Requirements

Expect top edge to allow resizable heights rather than shifting the whole window

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2361

### Log File

[debug.log](https://github.com/files-community/Files/files/12838841/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by nigiriemoji** [comment]
> Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

works fine on preview, i use windows store version. so just keep waiting?

**Comment by Josh65-2201** [comment]
Thanks for checking, if you want to continue using stable then yes.
