### ISSUE TITLE
Add BitDefender context menu support

### ISSUE THREAD

**Issue by HammerOfDaGods** [files-community/Files#13482]
### What feature or improvement do you think would benefit Files?

BitDefender adds a few context menus that are not shown in the "Files" context menu

BitDefender menu that is not showing up in the "Files" context menu
![image](https://github.com/files-community/Files/assets/94164260/29e47a35-3532-4326-8363-a9248aead035)
![image](https://github.com/files-community/Files/assets/94164260/1ce21284-22b0-4f21-b261-188eb395b4cf)

### Requirements

Allow the BitDefender context menus to appear in the "Files" context menu

### Files Version

2.5.21.0

### Windows Version

10.0.22631.2338

**Comment by Josh65-2201** [comment]
Thanks for the feedback. Last known it was an issue with bit defender and how it add shell options as said here https://github.com/files-community/Files/issues/10866#issuecomment-1485743785

**Comment by HammerOfDaGods** [comment]
Understood. That's fine, I never use the context menu options myself, just figured I'd report it for others just in case. Thank you for the quick response. In that case, you may close this request if you like.

**Comment by yaira2** [comment]
It might help to try reporting this to BitDefender, it would help if they used the regular shell apis.
