### ISSUE TITLE
Right click context menu is causing app to hang.

### ISSUE THREAD

**Issue by alexgorbatchev** [files-community/Files#13484]
### Description

Full freeze when right clicking on any item in the item view (sidebar works fine).

### Steps To Reproduce

1. Right click on an any item in the item view

### Requirements

Should open context menu.

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2283

### Log File

[debug.log](https://github.com/files-community/Files/files/12834797/debug.log)
[debug.txt](https://github.com/files-community/Files/files/12834798/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/12834799/debug_fulltrust.txt)

**Comment by Josh65-2201** [comment]
Thanks for the report, Can you send a screenshot of Windows File Explorer full (in the Show more) context menu

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by alexgorbatchev** [comment]
![image](https://github.com/files-community/Files/assets/65633/11a5791d-f285-49bb-8091-83ef41f698e2)

**Comment by alexgorbatchev** [comment]
Preview appears to be working

![image](https://github.com/files-community/Files/assets/65633/cbb5a316-6a27-4023-a410-7e6d2197ca1c)

**Comment by yaira2** [comment]
Great! The fix will be included when v3 is released.
