### ISSUE TITLE
Beta download failed

### ISSUE THREAD

**Issue by chezfo** [files-community/Files#13489]
### Description

When I downloaded the latest beta release, the download failed with an error message:

` Deployment Add operation with target volume C: on Package FilesPreview_2.5.29.0_neutral_~_wvne1zexy08sa from:  (Files.Package_2.5.29.0_x64_ARM64_Preview.msixbundle)  failed with error 0x80D02002. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues. (0x80d02002)`

The download fails at step 15

![תמונה](https://github.com/files-community/Files/assets/85172877/4c4a1d44-a91e-4df1-91b2-2eb617605e8b)

### Steps To Reproduce

1. Download Beta version Files.preview-1.appinstaller
2. Run the app installation

### Requirements

beta

### Files Version

2.5.29.0

### Windows Version

10.0.22621.2283

### Log File

--

**Comment by Josh65-2201** [comment]
Thanks for the report, Have you install a unofficial/modified (EG. Disabled windows update, removed the Microsoft store, used a debloat program/script) version of Windows?

**Comment by chezfo** [comment]
I use an official and valid version of Windows.

**Comment by Josh65-2201** [comment]
The error given says it related to Windows update not working. Have you check in `Windows Settings > Windows update > Check for updates` works?

**Comment by chezfo** [comment]
I use a filter by an external company
I will check with them if there is a blockage.

**Comment by Josh65-2201** [comment]
It would properly be your company blocking the download of Files.

**Comment by chezfo** [comment]
My girlfriend says she doesn't have the block.
 I tried to install another way and I got this message:
The application installer failed to install package dependencies.  Ask the developer for a package Microsoft.WindowsAppRuntime.1.4.

**Comment by Josh65-2201** [comment]
What's the other way your attempting to install?

**Comment by chezfo** [comment]
I downloaded the software (beta) from this link.  (I got to it through a traffic recording)
https://cdn.files.community/files/preview/Files.Package_2.5.29.0_Preview_Test/Files.Package_2.5.29.0_x64_ARM64_Preview.msixbundle

**Comment by Josh65-2201** [comment]
This is the dependency link
https://cdn.files.community/files/preview/Files.Package_2.5.29.0_Preview_Test/Dependencies/x64/Microsoft.WindowsAppRuntime.1.4.msix

**Comment by chezfo** [comment]
After all, apparently there was a block to my IP address.  (Not sure why...)
I changed the address and the matter was settled

**Comment by yaira2** [comment]
> message:

Was the block from the filter, or was it from the cdn?

**Comment by chezfo** [comment]
Not related to the filter
