### ISSUE TITLE
Bug: Alt+Up hotkey to go Up a folder doesn't work

### ISSUE THREAD

**Issue by AstudilloMarillo** [files-community/Files#13491]
### Description

Alt+Up hotkey to go Up a folder doesn't work. Nothing happens when the hotkey is pressed. Both for the latest version as well as the preview version.

### Steps To Reproduce

1. Open Files.
2. Go to a folder that has a parent folder.
3. Try the hotkey Alt+Up

### Requirements

The expected behaviour is that the hotkey will navigate to the parent folder.

### Files Version

2.5.21.0 + 2.5.29.0 (preview)

### Windows Version

10.0.19045.3324

### Log File

Doesn't seem necessary.

**Comment by Josh65-2201** [comment]
Thanks for the report, I am unable to reproduce this
- Can you see if the UI button works.
- Can you please upload (Do not copy and paste content) the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.

**Comment by AstudilloMarillo** [comment]
The UI button does work. Alt+Right / Alt+Left do work fine. Alt+Up does work correctly in Windows Explorer.

Log file:
[debug.log](https://github.com/files-community/Files/files/12841391/debug.log)

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

If it's still an issue, can you share screen recording?
