### ISSUE TITLE
Separate Behaviors for touch and mouse input

### ISSUE THREAD

**Issue by manmathew** [files-community/Files#13496]
### What feature or improvement do you think would benefit Files?

An issue that I have with Files and Windows Explorer is that you have to use the same click-to-open behavior for mouse and touch.
Touchscreen is an input that makes much more sense to allow for single-click input to open a folder or file.
Most people are already accustomed to Mouse requiring a double click to actually open something on any OS they use.

It would be great if there was an option to use single-click to open for touchscreens only while double-click for mice.

### Requirements

- This feature would require differentiating between touch and mouse inputs
- I don't know what else it would require.

### Files Version

2.5.29.0

### Windows Version

10.0.19045.3448

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #5052. You can check there or click subscribe in the right sidebar for updates.
