### ISSUE TITLE
Bug: Accessing WSL in column layout prompts for password

### ISSUE THREAD

**Issue by htrekker** [files-community/Files#13495]
### Description

When I want to see files in WSL,  the following dialog poped out:
![image](https://github.com/files-community/Files/assets/27626256/2aed53be-760d-46b8-a25e-6c943591df1c)
And I found a similar issue at here: [issue 11922](https://github.com/files-community/Files/issues/11922).  I'm using a newer version files than the solution mentioned. But, I haven't tried downgrading yet.

I'm using wsl2 with version **1.2.5.0**. And the linux distribution I use is: **Ubuntu 20.04** with kernel version **5.15.90.1**.

By the way, great work! Really enjoying using it : ).

### Steps To Reproduce

1. Open Files
2. Click WSL instance 

### Requirements

+ Expected to act as same as the native filesystem manager (i.e. No dialog should pop out,).

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2361

### Log File

[debug.log](https://github.com/files-community/Files/files/12847003/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by htrekker** [comment]
How do I download the previous version? The download page does not appear to have a link to download previous versions.

**Comment by Josh65-2201** [comment]
Click the option that says Insider preview

**Comment by htrekker** [comment]
Sorry for misread your message. The problem is still there in preview version. And I forget to mention, the problem only occurs when I'm using column layout. And it works fine when I switch to other layout.

**Comment by yaira2** [comment]
@htrekker this is fixed in the dev branch. Thanks for the report.
