### ISSUE TITLE
Bug: Crash after deleting files

### ISSUE THREAD

**Issue by xenos-github** [files-community/Files#13494]
### Description

I had selected multiple .txt files to delete. It crashed whilst deleting them. 

### Steps To Reproduce

1. Sort by file type. 
2. Select all .txt files.
3. Deselect the most recent files.
4. Click the del button on the warning dialog to remove deleted files. 

### Requirements

- e.g. Fix crash that occurs when...
I expected a refreshed view of the file listing, with the files selected for deletion now absent.
When inspecting the folder after the crash, the files selected for deletion appear to have been successfully deleted.

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2361

### Log File

[debug.log](https://github.com/files-community/Files/files/12844552/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by yaira2** [comment]
@xenos-github

**Comment by yaira2** [comment]
We're not able to repro this with the latest changes, but if it's still an issue, please upload the most recent log file and we'll take another look.
