### ISSUE TITLE
Very slow removal of large number of files

### ISSUE THREAD

**Issue by ruben2s** [files-community/Files#13499]
### Description

Today I had to remove some folders that contained a large number of files (10,000). I noticed that Files simply cannot do this as the app becomes unusable while it is doing that, both when moving to the recycling bin or permanently deleting them.

With this simple cmd `DEL /F/Q/S *.* > NUL`, it takes 3.2 seconds. But with Files I stopped counting at 4+ minutes and it wasn't even halfway done. The CPU usage was very high (>40%, and the RAM usage was >1GB), which made the OS pretty slow.

With `explorer. exe` these are the results of the benchmark:
Move to recycling bin: 1 min 4.1 s
Delete permanently: 5.3 s

You can make consistent benchmarks this with this script, which will create 10,000 `.txt` files.

`for /l %%x in (1, 1, 10000) do (
   echo %%x
   copy NUL %%x.txt
)
pause`

(save it as a .bat file)

### Steps To Reproduce

1. Create a lot of files by using the provided script
2. Delete them with Files
3. App becomes unusable, very slow deletion times (approximately 13,900 % more than a simple `del` command).

### Requirements

App does not freeze/get unusable and deletion times are comparable with those of `explorer.exe` or `cmd`

### Files Version

2.5.29.0

### Windows Version

10.0.22621.2361

### Log File

[debug.log](https://github.com/files-community/Files/files/12861032/debug.log)

**Comment by parfait8566** [comment]
I can confirm this even when then number of files isn't that big it still takes noticeably longer than File explorer

**Comment by yaira2** [comment]
@ruben2s are you referring to how long it takes to delete the items, or do you mean the amount of time before the confirmation prompt is displayed?

**Comment by ruben2s** [comment]
I am refering to how long it takes to delete the items

**Comment by yaira2** [comment]
Thanks for the response, we're tracking this in #7275, #13632 and #7518.
