### ISSUE TITLE
Bug: Dvd drive is missing tooltip on the sidebar

### ISSUE THREAD

**Issue by Jay-o-Way** [files-community/Files#13511]
### Description

Simple and low priority:
In the navigation, there's a DVD drive. It seems to have an empty tooltip. (including eject button)
![image](https://github.com/files-community/Files/assets/65828559/2e6c2e86-8085-4639-8c9e-1b8212fc03ee)

### Steps To Reproduce

In the left nav pane, hover the drive.

### Requirements

Tooltip with text. Either for the drive or the Eject button.

### Files Version

2.5.29

### Windows Version

10.0.22621.2361

### Log File

[debug.log](https://github.com/files-community/Files/files/12883393/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
@Jay-o-Way Is this still an issue in the preview version? https://files.community/download/preview

**Comment by 0x5bfa** [comment]
I fixed the issue where the Eject button's tooltip was not displayed ccorrectly in v2.5.32

> Dvd drive is missing tooltip
Can you share a screenshot that shows info instead of you hovering on Eject button?
