### ISSUE TITLE
Bug: Can't open screen saver (.SCR) files

### ISSUE THREAD

**Issue by xmha97** [files-community/Files#13517]
### Description

When I click on an SCR file, I see the configure window.

### Steps To Reproduce

1. Click on SCR file

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2428

### Log File

```
2023-10-14 05:06:25.9511|Information|App launched. Launch args type: LaunchActivatedEventArgs
2023-10-14 05:06:26.0949|Information|Adding cloud provider "pCloud Drive" mapped to P:\
2023-10-14 05:06:28.4157|Information|Drive added: C:\, Fixed
2023-10-14 05:06:28.7574|Information|Drive added: P:\, Removable
2023-10-14 05:06:32.2381|Information|STORE: Checking for updates...
2023-10-14 05:06:33.4109|Information|Running on ARM: False
```

**Comment by xmha97** [comment]
![image](https://github.com/files-community/Files/assets/23485114/0c2aaafc-820e-4dcd-99db-2b91e08ff616)

![image](https://github.com/files-community/Files/assets/23485114/0a82451a-2c74-4b2f-98dc-0d202b6609c7)

**Comment by Josh65-2201** [comment]
Thanks for the report.
- Can you please upload (Do not copy and paste content) the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.
- Why have you send screenshots of the registry's. Have to made your own changes to those values?

**Comment by xmha97** [comment]
> Thanks for the report.
> 
>     * Can you please upload (Do not copy and paste content) the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.
> 
>     * Why have you send screenshots of the registry, have to made your own changes to those values?

Ok, I added debug.log
I have also sent a screenshot of the registry so you can see that the Files app runs SCR files like EXE files.
Now must run SCR files with this parameter: `"%1" /S`

**Comment by Josh65-2201** [comment]
Can you send a screen recording of what happens when you open in Windows File Explorer vs Files.

**Comment by xmha97** [comment]
Can't Test (Run) Screensavers:

https://github.com/files-community/Files/assets/23485114/aa0d574a-6033-4197-8cfb-aa93de814c29

**Comment by Josh65-2201** [comment]
Thanks for the information, I've added this to the project board.

**Comment by yaira2** [comment]
According to the documentation, we need to use the `/s` switch https://learn.microsoft.com/en-us/previous-versions/windows/desktop/ms686421(v=vs.85)#command-line-options.
