### ISSUE TITLE
Bug: Crash when entering a certain folder

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#13519]
### Description

When I open my external local drive folder it will crash but doesn't always happen.

### Steps To Reproduce

1. Open drive B
2. Open folder with 2 Macrium reflect backups and .7z folder

### Requirements

- Fix crash when opening folder

### Files Version

2.5.30.0

### Windows Version

10.0.22621.2361

### Log File

[debug.log](https://github.com/files-community/Files/files/12909375/debug.log)

Exception from VS debug mode
![image](https://github.com/files-community/Files/assets/26977075/6413474f-6e34-4a5f-b798-b243df2364f7)

**Comment by yaira2** [comment]
Thank you for the report.

**Comment by yaira2** [comment]
1. Is it always the same folder?
2. Is it only on external drives, or does it happen if you copy the folder to a fixed drive as well?

**Comment by Josh65-2201** [comment]
It is always the same folder, I currently don't have enough internal storage it test with.

**Comment by yaira2** [comment]
Is this also an issue in stable?

**Comment by Josh65-2201** [comment]
Yes it is

**Comment by Josh65-2201** [comment]
Tested for a while seem to be fixed since 3.0.15.0
