### ISSUE TITLE
Feature: Open Files on Windows Startup in background

### ISSUE THREAD

**Issue by dragonofmercy** [files-community/Files#13510]
### What feature or improvement do you think would benefit Files?

Open Files on Windows Startup option is good but it can be better if Files starts in background (without displaying the window)

### Requirements

- Move existing option to "Open Files on Windows Startup" to the "Advanced" settings page
- Add sub setting to "Start minimized"

### Files Version

2.5.29.0

### Windows Version

Windows 11 22621.2361

**Comment by Josh65-2201** [comment]
Thanks for the feedback, I've added this to the project board.

**Comment by yaira2** [comment]
This is a common option in other apps, but considering we just added support for keeping Files in the background, we want to give some time for this feature to settle before making a decision on this.

**Comment by MarcAnt01** [comment]
> This is a common option in other apps, but considering we just added support for keeping Files in the background, we want to give some time for this feature to settle before making a decision on this.

Honestly I think this option should be default,  for me the main reason for having Files at startup is to avoid the really slow startup

**Comment by yaira2** [comment]
This feature will be included in the next update.
