### ISSUE TITLE
Pin Tab

### ISSUE THREAD

**Issue by xmha97** [files-community/Files#13515]
### What feature or improvement do you think would benefit Files?

Hi, I want to pin tabs (like browsers):

![image](https://github.com/files-community/Files/assets/23485114/78773f80-eeb7-4de3-a298-6f2b9a54d02a)

![image](https://github.com/files-community/Files/assets/23485114/2ccfff24-9976-46e4-af92-334d4cf96183)

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2428

**Comment by Josh65-2201** [comment]
Thanks for the feedback. The plan is to introduce workspaces, Merging with #11900. You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
As Josh mentioned, we don't have specific plans to support pinning tabs. However, you can pin folders to favorites and you can also set Files to open a specific set of tabs on startup.
