### ISSUE TITLE
Navigation with arrow keys

### ISSUE THREAD

**Issue by lAmeR1** [files-community/Files#13514]
### What feature or improvement do you think would benefit Files?

I really like to navigate through directories with my arrow keys. But even if I enter a directory with the Enter key, I can't you my arrow keys after entering.

I need to focus the tree list with my mouse, to navigate with my arrow keys again.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.5.21.0

### Windows Version

10pro, 22H2

**Comment by Josh65-2201** [comment]
Thanks for the feedback, This should already work, can you see if this is an issue in the preview version. https://files.community/download

**Comment by lAmeR1** [comment]
Hi indeed! It's working in the preview version- thanks!
