### ISSUE TITLE
Drag files from one pane to another

### ISSUE THREAD

**Issue by dunbarrc** [files-community/Files#13518]
### What feature or improvement do you think would benefit Files?

With two panes open, I would like to be able to drag files from folders one pane to folders in a different drive/partition displayed in the other pane. It is very helpful when the source and destination folders are far away from each other. In fact it would be desirable to be able to drag entire folders from one pane to the other.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.5.21.0

### Windows Version

10.0.19045.3570

### Comments

This feature has been available in PowerDesk for many years.

**Comment by Josh65-2201** [comment]
Thanks for the feedback, this is already implemented, Can you send a screen recording of the issue you are having.

**Comment by yaira2** [comment]
@dunbarrc
