### ISSUE TITLE
free Disk Space isn't updated when running App in background is enabled

### ISSUE THREAD

**Issue by A-Loot** [files-community/Files#13529]
### Description

When enabeling the option "Leave app running in the background when the window is closed" the free disk space is not updated. Normally in Explorer it's updated every time you oppen a new tab or refresh the page but in Files you have to completely stop the process and restart the App. This Problem does not exist in the "Properties" Window.

### Steps To Reproduce

1. Open Files
2. Delete or Add a large Folder/File
3. Look at the free disk space in Home or when hovering over the disk. The disk space should still be the same as before
4. Compare the value with the ones shown in Explorer or Properties, those two should show the correct value

#### Example: I deleted a 3 GB Folder

Files:
![image](https://github.com/files-community/Files/assets/105282948/8f5f9358-5203-45b7-bb2e-86d7ce990031)

Properties:
![image](https://github.com/files-community/Files/assets/105282948/9f69b23f-d278-431c-871e-60be27264609)

Explorer:
![image](https://github.com/files-community/Files/assets/105282948/e5a0c3de-7de2-4450-878b-bd34e704f9de)

### Requirements

-

### Files Version

2.5.30.0

### Windows Version

10.0.22635.2483

### Log File

-

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #6182. You can check there or click subscribe in the right sidebar for updates.
