### ISSUE TITLE
Auto-renaming items with numbers in the name has weird results

### ISSUE THREAD

**Issue by ruVic101** [files-community/Files#1352]
**Auto-renaming after copying of duplicate file is not consistent across different folder names.**
Copying a file with the same name as an existing file doesn't rename the new file correctly.

**To Reproduce**
**Scenario 1:**
1. Create new folder called "abc.123.2020-HD"
2. Copy the newly created folder "abc.123.2020-HD"
3. Paste it in the same directory as the source file.
4. Check the name of the newly renamed/copied/duplicate file.

**Scenario 2:**
1. Create new folder called "abc.123.Year(2020)-HD"
2. Copy the newly created folder "abc.123.Year(2020)-HD"
3. Paste it in the same directory as the source file.
4. Check the name of the newly renamed/copied/duplicate file.

**Expected behavior**
**Scenario 1:**
The expected file name of the duplicate file should have been appended by "(2)" at the very end of the file name.
**Scenario 2:**
The expected file name of the duplicate file should have been appended by "(2)" at the very end of the file name instead of incrementing the (2020) value to (2021).

**Screenshots**
 **Scenario 1:**
![image](https://user-images.githubusercontent.com/36847870/86528275-139ac900-bec4-11ea-84e0-2ced18b293bd.png)

 **Scenario 2:**
![image](https://user-images.githubusercontent.com/36847870/86528263-ff56cc00-bec3-11ea-9988-f779bb3d431a.png)

**Desktop:**
 - OS Version: [e.g. Windows 10 2004 19041.329]
 - App version: [v0.11.0]

**Comment by yaichenbaum** [comment]
@d2dyno1 Can you confirm that that your recent changes resolved this issue?

**Comment by d2dyno1** [comment]
Nope, that's not been fixed. @yair100

**Comment by gave92** [comment]
Note: this is an issue only when using the StorageFolder APIs, when renaming with the fulltrust process the new name has simply "- Copy" appended at the end. It's `NameCollisionOption.GenerateUniqueName` that returns those funny names.

**Comment by yaichenbaum** [comment]
@gave92 if that's the case, this would only an issue in network drives, does that make sense?

**Comment by gave92** [comment]
The above comment is wrong, the same happens in local drives as well, but you need to paste the same folder twice. In any case the behaviour is consistent with explorer as we only use system copy functions. Seems excessive to throw away automatic system renaming just for this.
