### ISSUE TITLE
Feature: Copy multiple paths at once when mutliple items are selected

### ISSUE THREAD

**Issue by shrublet** [files-community/Files#13527]
### What feature or improvement do you think would benefit Files?

This is a feature that I could've sworn already existed in Files, but it just allows copying the paths of an entire selection instead of just the first item of the selection.

### Requirements

- Copy multiple paths to the clipboard
- Should be newline separated
- ~~Include copy with quotes~~ (Related #13398)

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2428

**Comment by yaira2** [comment]
Thank you for the feedback, I'm not sure how often this will be used but I really like the idea.

**Comment by hecksmosis** [comment]
I'll do this
