### ISSUE TITLE
Ftp issue

### ISSUE THREAD

**Issue by akashsoni474** [files-community/Files#13522]
### Description

I am currently on windows 10, using files insider version as well as stable version, in both the versions I am facing issue when I am accessing my android device using ftp, it takes a lot of time displaying all the folders on my android device, whereas on the default file manager of windows 10 all the folders are displayed really quickly so please can you fix this in the next update?

### Steps To Reproduce

1. Add android device using ftp
2. Check when the loading is completed

### Requirements

- e.g. Fix crash that occurs when...
Please fix the slow loading in ftp 

### Files Version

2.5.30.0

### Windows Version

10.0.19045.3570

### Log File

[debug.log](https://github.com/files-community/Files/files/12918106/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
Thank you for your feedback, we're tracking performance issues in #4180. Can you add a comment there about this?
