### ISSUE TITLE
Bug: Drives don't show in the send to menu

### ISSUE THREAD

**Issue by sicilla** [files-community/Files#13538]
### Description

Нажимаю правой кнопкой меню, на файле, хочу отправить на флешку, а её нет в устройствах

### Steps To Reproduce

1. Правой кнопкой мыши на файле
2. Отправить в...
3. Флешки там нет

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

2.5.30.0

### Windows Version

10.0.19045.3570

### Log File

[debug.log](https://github.com/files-community/Files/files/13038452/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report. Does Windows File Explorer show this option?

**Comment by Josh65-2201** [comment]
Thanks for the information, I've added this to the project board.

**Comment by sicilla** [comment]
И ещё небольшая заметка, иконки папок маленькие, по сравнению с текстом. Смотрится не соразмерно. Увеличить бы их немного.Программа понравилась, огромное спасибо!19.10.2023, 17:53, "Josh65-2201" ***@***.***>:
Thanks for the information, I've added this to the project board.

**Comment by sicilla** [comment]
Здравствуйте, Josh65-2201.

Вы писали 19 октября 2023 г., 17:53:35:

> Thanks for the information, I've added this to the project board.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.
Good afternoon. This morning I launched your application, and the flash drives are in the context menu "Send to ...". Maybe there was some kind of glitch yesterday. Sorry to bother you! 

-- 
С уважением,
Артём
