### ISSUE TITLE
Renaming issues without privileges

### ISSUE THREAD

**Issue by ajilidali** [files-community/Files#1353]
When a file requires higher privileges, if you try to rename it, it will say that there's already a file named that way in same directory and will let you choose between two options, it crashes no matter what you choose
Clip : https://imgur.com/a/5IXhfsR

**Comment by ChihweiLHBird** [comment]
What's `higher privileges` required by the file?

**Comment by ajilidali** [comment]
Administrator rights

**Comment by yaichenbaum** [comment]
@ajilidali This feature was implemented in #4986.
