### ISSUE TITLE
The home page unpinned Onedrive folder crashed

### ISSUE THREAD

**Issue by xiaodu-du** [files-community/Files#13531]
### Description

The home page unpinned Onedrive folder crashed.

### Steps To Reproduce

1.Pin the Onedrive folder on the home page
2.Unpin

### Requirements

Hope to fix

### Files Version

2.5.21.0

### Windows Version

10.0.22631.2428

### Log File

[debug.log](https://github.com/files-community/Files/files/13026323/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report. What do you mean by pin to the home page? Are you using the favorites section?

**Comment by xiaodu-du** [comment]
Yes.

________________________________
发件人: ***@***.*** ***@***.***> 代表 Josh65-2201 ***@***.***>
发送时间: 2023年10月18日 06:35
收件人: files-community/Files ***@***.***>
抄送: xiaodu-du ***@***.***>; Author ***@***.***>
主题: Re: [files-community/Files] The home page unpinned Onedrive folder crashed (Issue #13531)


Thanks for the report. What do you mean by pin to the home page? Are you using the favorites section?

―

**Comment by Josh65-2201** [comment]
Can you see if this is an issue in the preview version. https://files.community/download

**Comment by yaira2** [comment]
There is a good chance this is fixed in the preview version, but it'll be good if you can confirm before we close the issue.

**Comment by xiaodu-du** [comment]
Tried it in the latest preview and it has been resolved
________________________________
发件人: ***@***.*** ***@***.***> 代表 Josh65-2201 ***@***.***>
发送时间: 2023年10月28日 06:34
收件人: files-community/Files ***@***.***>
抄送: xiaodu-du ***@***.***>; Author ***@***.***>
主题: Re: [files-community/Files] The home page unpinned Onedrive folder crashed (Issue #13531)


Can you see if this is an issue in the preview version. https://files.community/download

―

**Comment by Josh65-2201** [comment]
Thanks for checking.
