### ISSUE TITLE
Window not gaining focus on tab creation request

### ISSUE THREAD

**Issue by D-Maxwell** [files-community/Files#13541]
### What feature or improvement do you think would benefit Files?

Upon creation of a new tab, the window does not gain focus, nor does it move to the front layer.

That is the behaviour I would've expected, although I am unsure whether this feature is simply not handled at all by the application as it could simply be a limit of the framework it is built on top of, or if only some supported requests bring the window forward.
Note that I have no example in mind of the latter being an eventuality.

-----

Say I were to open the user's Downloads folder through their browser ; this would send a request to create a new dedicated tab, possibly in the last open Files instance or in a new one if there were none ; and that would be it.
The window would not gain focus, and would instead stay hidden in the background, without even pulsing its corresponding taskbar entry.

### Requirements

The ability to move the user's focus to an instance of the Files app on demand. Being able to ask the shell to do so I suppose.

### Files Version

2.5.21.0

### Windows Version

10.0.19045.2788 | Windows 10 Pro | Version 22H2 | OS build 19045.2788 | Windows Feature Experience Pack 120.2212.4190.0

### Comments

Given an endpoint, one could for instance make an AutoHotKey script that would then focus the window.
I have no knowledge of such an endpoint existing. Besides, that would not be a great workaround in the long term, as I assume this has not yet been resolved because of a limitation in the stack.

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #10844. You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
@D-Maxwell thank you for the detailed request, this is indeed a limitation with the framework (https://github.com/microsoft/microsoft-ui-xaml/issues/7595) but we're also tracking it in #10844.

**Comment by D-Maxwell** [comment]
My apologies, I was not certain this had the same root cause as #10844.

**Comment by yaira2** [comment]
@D-Maxwell we came up with a workaround in #13588.
