### ISSUE TITLE
Bug: Using Tab selection gets stuck resizing the sidebar

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#13548]
### Description

If I use tab to navigate in Files it will select the sidebar width divider and get stuck there. Tab, Shift + Tab will resize it to be bigger.

### Steps To Reproduce

1. Use Tab
2. Wait until sidebar is highlighted
3. See controls only make sidebar bigger

### Requirements

- Tab and shift tab should switch between elements and not resize.

### Files Version

2.5.30.0

### Windows Version

10.0.22621.2428

### Log File

[debug.log](https://github.com/files-community/Files/files/13059055/debug.log)

**Comment by hecksmosis** [comment]
Should we make the sidebar resizer not selectable using tab?

**Comment by yaira2** [comment]
> Should we make the sidebar resizer not selectable using tab?

It should be selectable so that you can resize the sidebar via keyboard, but it should also be possible to use the tab key to move to the next item.

**Comment by yaira2** [comment]
@chingucoding fyi

**Comment by hecksmosis** [comment]
> e selectable so that you can resize the sidebar via keyboard, but it should also be possible to use the tab key to move to the next ite

Ok, so we should change the resize command to not be tab
