### ISSUE TITLE
Feature Request: Hide the Search Bar

### ISSUE THREAD

**Issue by davidx007** [files-community/Files#13543]
### What feature or improvement do you think would benefit Files?

I would like to hide the search bar. 

### Requirements

Add a settings option to hide the search bar.

### Files Version

2.5.30

### Windows Version

22635.2483

**Comment by yaira2** [comment]
Thank you for your feedback, can you share the context behind this request?

**Comment by davidx007** [comment]
It takes up room from the path. I dont ever use the search bar.

**Comment by yaira2** [comment]
There is usually enough room for both,
- how long are the paths?
- is the window size small?

**Comment by yaira2** [comment]
We don't have plans to add this option, but we'd like to hear more about how you use the app in case we reconsider this in the future.
