### ISSUE TITLE
Unable to select 2nd level context menu items that overlap with the Window Title Bar

### ISSUE THREAD

**Issue by vadjle** [files-community/Files#13544]
### Description

When I utilize the right click context menu.  Sometimes the items which are in the extended context menu (ex. New, Show More Options) overlap the Title Bar of the window.  Whichever option overlaps the title bar is not selectable.

![image](https://github.com/files-community/Files/assets/70152576/f7928944-29f7-484c-85cc-4d1d4bd074cc)

### Steps To Reproduce

1. Reduce the File app window height
2. Right click in the window pane to open the context menu
3. Select the "New" option
4. Observe that the "Folder" option overlaps the Title Bar
5. Attempt to select the Folder option

### Requirements

Clicking the button performs the expected action.  Ex. Creating a new folder.

### Files Version

2.5.21.0

### Windows Version

10.0.22000.2416

### Log File

[debug.log](https://github.com/files-community/Files/files/13046221/debug.log)

**Comment by yaira2** [comment]
Thank you for the report, this issue is fixed in the dev branch and will be included in the next update.
