### ISSUE TITLE
Code Quality: Remove Open Dialog and Launcher from the main branch

### ISSUE THREAD

**Issue by heftymouse** [files-community/Files#13549]
### Description

This has not been seriously worked on [in years](https://github.com/files-community/Files/commit/24433cf5d7c493cf9a4ffa0a1a6ae34c4fe9ee58), and is clearly not a priority for the moment. I suggest moving this to a separate feature branch to make the codebase smaller, and prevent it from increasing build times and creating unwanted artifacts when building the entire solution.

### Concerned code

src/Files.App.OpenDialog
src/Files.App.Launcher

### Gains

- Prevents unwanted time-consuming C++ builds
- Removes unmaintained and unused code to create a leaner codebase

**Comment by yaira2** [comment]
Thank you for your feedback. We recently made some progress with the new option to keep Files open in the background. We still have some work to do with #12689 but I'd like to keep the project in `main` to make sure it's in place when we're ready to continue working on it.

**Comment by yaira2** [comment]
My suggestion for now is to unload the projects to reduce build time.
