### ISSUE TITLE
Copy button in Settings>About>Files should graphically indicate that it is a dropdown

### ISSUE THREAD

**Issue by D-Maxwell** [files-community/Files#13542]
### What feature or improvement do you think would benefit Files?

Perhaps the Copy button could use a tiny arrow signalling that it is not a single click, single action button but rather a dropdown leading to two options.

Or it could be split into two dedicated buttons.

This would be a very minor and subtle change, yet it has confused me from the very first time I had made use of it, and it keeps on doing so to this day, as it is what has driven me to request this improvement.

### Requirements

Dropdown modals have already been implented therefore there are no prior requirements to this improvement.

### Files Version

2.5.21.0

### Windows Version

10.0.19045.2788 | Windows 10 Pro | Version 22H2 | OS build 19045.2788 | Windows Feature Experience Pack 120.2212.4190.0

### Comments

![image](https://github.com/files-community/Files/assets/98100481/01fe7196-d76f-47f0-86cf-49184bc472e4)

**Comment by Josh65-2201** [comment]
Thanks for the feedback. The copy button isn't a drop down as it doesn't have sub options.

**Comment by yaira2** [comment]
What Josh said is correct, while chevrons are used to indicate when there is a drop down menu, it's not the design we use for regular buttons with a menu flyout.
