### ISSUE TITLE
Feature: Cycle tabs via mouse scrolling

### ISSUE THREAD

**Issue by HekutoruMAC** [files-community/Files#13550]
### What feature or improvement do you think would benefit Files?

Switch tabs using the mouse wheel while hovering over the tab bar.

### Requirements

Implement mouse wheel actions over the tab bar, I guess.

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2428

**Comment by Josh65-2201** [comment]
Thanks for the feedback, I've added this to the project board.

**Comment by meemore** [comment]
opps  I just posted this also, sorry about that

**Comment by Josh65-2201** [comment]
@Shadow912kage Please make a separate feature request for this.

**Comment by Shadow912kage** [comment]
Sorry, I made a new feature request for this. #16766
