### ISSUE TITLE
Bug: App crashes when pasting item

### ISSUE THREAD

**Issue by VergilTG** [files-community/Files#13559]
### Description

can't paste large files . software crashes . sometimes the progress doesn't show

### Steps To Reproduce

copy a large file
paste the file 
crashes

### Requirements

the file should be pasted and need a popup progress bar just like the default windows 10 one

### Files Version

22H2

### Windows Version

22H2

### Log File

[debug.log](https://github.com/files-community/Files/files/13066935/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by VergilTG** [comment]
windows verssion 10.0.19045.3570

Files preview latest version 2.5.31.0

**Comment by VergilTG** [comment]
extra detail : I was trying to copy from mobile to pc , but earlier had an another issue while pasting 100gb file and there was no progress at all long time , sometime it wont even show the progress . ALthough I was able to paste 27gb file today

**Comment by yaira2** [comment]
Is this the same as #13595?

**Comment by yaira2** [comment]
@VergilTG This seems like a different issue but I think it's fixed in v2.5.33, can you confrim?

**Comment by yaira2** [comment]
I did some more testing and it seems like this is resolved. If it's still happening for you, please let us know and we'll take another look.
