### ISSUE TITLE
Transparent-er Acrylic Background

### ISSUE THREAD

**Issue by D-Maxwell** [files-community/Files#13551]
### What feature or improvement do you think would benefit Files?

Currently, with an alpha of 0 and Acrylic set as the background material, this is the least opaque a Files instance can get :
![image](https://github.com/files-community/Files/assets/98100481/422bbdcb-e0c4-4e88-960d-5c89f3f38d1e)

Compared to other UWP apps that support acrylic backgrounds, or even ones that do through 3rd party apps like Mica for Everyone, that is still very much opaque.

![image](https://github.com/files-community/Files/assets/98100481/6d37b0d5-08de-49e2-87f5-ffabcab23344)

I wish there were a way to diminish the opacity of the background overlay even further.

### Requirements

Unsure what would be required given my lack of knowledge regarding your own specific implementation of an acrylic effect.

### Files Version

2.5.21.0

### Windows Version

10.0.19045.2788 | Windows 10 Pro | Version 22H2 | OS build 19045.2788 | Windows Feature Experience Pack 120.2212.4190.0

**Comment by yaira2** [comment]
> I wish there were a way to diminish the opacity of the background overlay even further.

Thank you for your feedback, this is already possible by following the instructions under "Glass theme" https://files.community/docs/configuring/custom-themes
