### ISSUE TITLE
Bug: Issue with Missing Drive Icon and Folder Display when Connecting Phone

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#13562]
### Description

When I click on my phone under the "Drives" section, the initial folder, which should appear with the drive icon as shown in the preview panel, doesn't display either next to the folder name or on the tab name at the top. This issue persists as I navigate through the folders. This issue occurs in all views for the tab icon problem, but for the icon next to the item name, it only happens in the column view.

### Steps To Reproduce

...

### Requirements

Address the problem of the initial folder not displaying as expected, both next to the folder name and in the tab name.

### Files Version

2.5.31

### Windows Version

10.0.22621.2428

### Log File

![Capture d'écran 2023-10-23 150554](https://github.com/files-community/Files/assets/128183422/07d6bba6-affb-422a-86ff-03aef38d537e)
![Capture d'écran 2023-10-23 150607](https://github.com/files-community/Files/assets/128183422/2a14cda2-dc7e-45d7-991d-11bdf951ed7d)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
Is this present in stable?

**Comment by Lukiluc29** [comment]
> Is this present in stable?

Yes

**Comment by yaira2** [comment]
Thanks!

**Comment by Lukiluc29** [comment]
I've noticed that when I open a folder with photos, videos, etc., and then open another folder, it appears empty even though there should be photos in it. This issue repeats for all the folders on my phone except the one I opened first.

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by yaira2** [comment]
> Steps To Reproduce

Can you fill this out for future reference?

**Comment by Lukiluc29** [comment]
@yaira2 Sorry for the delay. I am still able to reproduce this problem.
