### ISSUE TITLE
Feature: Add command line switch to open in new window

### ISSUE THREAD

**Issue by xmha97** [files-community/Files#13566]
### What feature or improvement do you think would benefit Files?

I need a command line to open the Files app on a new Window.
Like Google Chrome:
```shell
chrome /new-window www.google.com
```

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.0.36.0

### Windows Version

10.0.22621.1848

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by xmha97** [comment]
Thanks, also I need this feature for `files:` protocol.
Microsoft on Office protocols pass parameters:
```
powerpoint:ofe|u|https://www.fourthcoffee.com/AllHandsDeck.ppt
```
Maybe it's good:
```
files:newwindow|c:\windows
```

**Comment by xmha97** [comment]
Thanks, also I need this feature for `files:` protocol.
Microsoft on Office protocols pass parameters:
```
powerpoint:ofe|u|https://www.fourthcoffee.com/AllHandsDeck.ppt
```
Maybe it's good:
```
files:newwindow|c:\windows
```

**Comment by xmha97** [comment]
Thanks, also I need this feature for `files:` protocol.
Microsoft on Office protocols pass parameters:
```
powerpoint:ofe|u|https://www.fourthcoffee.com/AllHandsDeck.ppt
```
Maybe it's good:
```
files:newwindow|c:\windows
```

**Comment by yaira2** [comment]
Can you confirm if this is the same as #13021?

**Comment by xmha97** [comment]
> Can you confirm if this is the same as #13021?

Yes

**Comment by yaira2** [comment]
No worries, finding similar issues on GitHub can be hard.
