### ISSUE TITLE
Bug: Hash computation fails when office documents are opened

### ISSUE THREAD

**Issue by cardin** [files-community/Files#13564]
### Description

![image](https://github.com/files-community/Files/assets/553816/c0f149a5-39b9-4e00-9e5e-09985dc6a386)

If a Microsoft Office document (e.g. docx or pptx) is opened, Files will not be able to compute its hash.

### Steps To Reproduce

1. Create a MS Word document (empty, 0 KB is fine)
2. Open the document
3. Calculate the Hash

### Requirements

There should not be an error in debug.log and a more user-friendly message should be shown in the Hash UI, instead of a cryptic error.

### Files Version

2.5.21.0

### Windows Version

10.0.19045.3570

### Log File

[debug.log](https://github.com/files-community/Files/files/13110939/debug.log)

**Comment by yaira2** [comment]
Thank you for the report

**Comment by yaira2** [comment]
"The process cannot access the file 'file.docx' because it is being used by another process."

**Comment by yaira2** [comment]
I'm not sure if we can calculate the hash, but we can try to display a more user friendly error.
