### ISSUE TITLE
More obvious visual indicator of a file transfer starting or finishing

### ISSUE THREAD

**Issue by SgtSweetieBelle** [files-community/Files#13563]
### What feature or improvement do you think would benefit Files?

As it stands, the visual indicator for when a file transfer is starting or finishing is _incredibly_ subtle and very easy to miss because of how small and discreet the indicator is—it's a gray circle on a gray background! Can it be made more obvious how to check the status of ongoing file transfers, and when there's a change in status? Ideally with some kind of animation, a flashing icon, a temporary pop-up toast, popping the modal open, etc.?

Here's what it looks like now. It's not obvious what's happening, where you should be looking, or that the file transfer has started, especially if you're using copy/paste hotkeys, and especially if there are already ongoing transfers.
https://github.com/files-community/Files/assets/2397955/c4061ed3-93ff-410d-bd2a-27c1b8947735

Here's an example of what a download looks like in Edge; the modal flies open.
https://github.com/files-community/Files/assets/2397955/3ef325b8-0aae-4376-9035-d945be6ad08e

and in Chrome, the modal flies open _and_ a little icon appears and flies up towards the Downloads button.
https://github.com/files-community/Files/assets/2397955/84287fa0-f1e1-405f-815e-1707cdac3b78

### Requirements

Improve visibility of a file transfer action starting or finishing. Either by
- opening the file transfer modal when a transfer starts
- flashing the icon
- an animation that redirects a user's attention to the File Transfers button

### Files Version

2.5.14.0

### Windows Version

10.0.22621.2428

**Comment by Josh65-2201** [comment]
Thanks for the feedback. The color comes from the Windows accent color so dark mode with gray accent is not well anyway. Option to open the flyout is being discussed here #13560. You can check there or click subscribe in the right sidebar for updates.
