### ISSUE TITLE
Add support for Everything file search.

### ISSUE THREAD

**Issue by d0j1a1701** [files-community/Files#13568]
### What feature or improvement do you think would benefit Files?

Everything is a fast file search tool for searching files on NTFS volumes. It can complete a full disk index in just a few seconds, making it several times faster than Windows search. It also supports external API calls. Introducing it into Files can greatly enhance the user experience.

### Requirements

Add a setting that allows users to choose between using the default search or Everything.

### Files Version

2.5.31.0

### Windows Version

Windows 11 22H2 (23570.1000)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #5845. You can check there or click subscribe in the right sidebar for updates.
