### ISSUE TITLE
windows library columns view

### ISSUE THREAD

**Issue by genadil** [files-community/Files#13579]
### What feature or improvement do you think would benefit Files?

windows library columns view. each folder gets it's own column. enormously practical in windows but missing in files app.
![image](https://github.com/files-community/Files/assets/110672303/9d2a79e0-19c1-43f7-a7f6-246f204a2992)

### Requirements

- multitasking
- viewing many folders at the same time in a single window
- just try this, it's amazing
- i use it for many years

### Files Version

2.5.21.0

### Windows Version

10.0.19045.3570

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #2509. You can check there or click subscribe in the right sidebar for updates.
Note this is what it does list layout should do when grouping is enabled.

**Comment by yaira2** [comment]
@genadil thank you for your patience, I'm excited to share that a List View layout will be included in the next release.
