### ISSUE TITLE
Create tag from main window and context menu

### ISSUE THREAD

**Issue by Beuzbeuz78** [files-community/Files#13587]
### What feature or improvement do you think would benefit Files?

Hi,
Do you plane to add creating tag from main window and context menu ?
It would be more useful 
Thanks

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2428

**Comment by yaira2** [comment]
Thank you for your feedback, I think this can be done by adding an option to the "edit tags" menu to "Create tag". This option should deep link into the Tags setting page.
![image](https://github.com/files-community/Files/assets/39923744/2aa7e566-47d0-40d0-88a2-d2b82e343684)

**Comment by yaira2** [comment]
@Beuzbeuz78 It seems like we're already tracking this in #12146. You can get notifications if you click the subscribe button on that issue.
