### ISSUE TITLE
Unable to eject USB device

### ISSUE THREAD

**Issue by d0j1a1701** [files-community/Files#13589]
### Description

The "Eject Drive" option is not available in the Files menu, and when you try to eject a drive from the taskbar menu, it cannot be ejected because Files is using the drive (even if you haven't opened any directories on that drive). Even if you enable background running, the drive still cannot be ejected after closing all Files windows.

### Steps To Reproduce

1. Insert a USB flash drive.
2. Attempting to eject this USB drive.
3. You will find that it cannot be ejected.

### Requirements

Add a pop-up drive button in the right-click menu of Files, or at least release the handle when the drive is not open.

### Files Version

2.5.31.0

### Windows Version

Windows 11 22H2 (23570)

### Log File

none

**Comment by Josh65-2201** [comment]
Thanks for the report, Merging with #13250. You can check there or click subscribe in the right sidebar for updates.

**Comment by d0j1a1701** [comment]
Also: The USB drive I am using is based on solid-state drive particles and controllers, so this may be a problem specific to "external hard drives." A regular USB drive may not be able to reproduce it.

**Comment by yaira2** [comment]
That's what it seems like, we'll continue tracking this issue in #13250.
