### ISSUE TITLE
Bug: Srt files not visible in the app

### ISSUE THREAD

**Issue by Shah-do** [files-community/Files#13582]
### Description

Pretty self explanatory, srt files are just not visible in the app whatsoever

### Steps To Reproduce

open the app and check for an srt file

### Requirements

srt file not visible

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2428

### Log File

[debug.log](https://github.com/files-community/Files/files/13180573/debug.log)

**Comment by yaira2** [comment]
@Shah-do do you have any sample files I can test with?
