### ISSUE TITLE
Hide the PREVIEW tab

### ISSUE THREAD

**Issue by xmha97** [files-community/Files#13583]
### What feature or improvement do you think would benefit Files?

How can I hide the PREVIEW tab?

![image](https://github.com/files-community/Files/assets/23485114/a35ce8ae-6bf3-4036-9820-37d09717d701)

Like Windows Explorer:

![image](https://github.com/files-community/Files/assets/23485114/be5e465d-a156-4c68-809d-252123487e7f)

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.0.36.0

### Windows Version

10.0.22621.2428

**Comment by Josh65-2201** [comment]
You cant as it isn't a tab. It's a button to see a full preview of the file.

**Comment by xmha97** [comment]
> You cant as it isn't a tab. It's a button to see a full preview of the file.

OK, it's a button, not a tab.
I looking for an option to hide full preview button.
like Windows Explorer.

**Comment by Josh65-2201** [comment]
Windows File Explorer doesn't have a dedicated preview section just the small on at the top. What is the reason you want to hide it?

**Comment by yaira2** [comment]
@xmha97 can you confirm if this is the same as #12564?

**Comment by xmha97** [comment]
> @xmha97 can you confirm if this is the same as #12564?

No, I want the current Details tab without Preview tab.

**Comment by yaira2** [comment]
That's what #12564 is requesting. It's on our todo list and we'll continue tracking there.
