### ISSUE TITLE
Feature: Allow deleting of local Git branches

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#13592]
### What feature or improvement do you think would benefit Files?

*

### Requirements

- Add a delete button next to the local branch
- Show a delete branch confirmation content dialog

### Files Version

2.5.30.0

### Windows Version

10.22621.2428

**Comment by yaira2** [comment]
Thank you for your feedback

**Comment by yaira2** [comment]
Fyi @mdtauk
