### ISSUE TITLE
Bug: Copy to text overlay is stuck on screen

### ISSUE THREAD

**Issue by HyPeRXKo** [files-community/Files#13591]
### Description

Hi, when you drag and drop using WinRar to a folder in files, the copy to text is stuck on the screen, and stay on top no matter what.

### Steps To Reproduce

1. Drag and drop from winrar to a folder in files.
2. See the "copy to {folder}" text stays on the screen

### Requirements

Overlay text should be gone once WinRar start to decompress.

### Files Version

3.5.33.0

### Windows Version

W11 22H2 22621.2428

### Log File

N/A

**Comment by Josh65-2201** [comment]
Thanks for the report, Can you send a screen recording of this issue.

**Comment by yaira2** [comment]
I was able to repro this when dragging from the browser as well. Can you confirm if this is also an issue in stable versions of Files?

**Comment by yaira2** [comment]
Can you also upload the log file?

**Comment by yaira2** [comment]
This might have been fixed in v2.5.33, can you let us know?

**Comment by HyPeRXKo** [comment]
Still a bug on v2.5.33 : https://youtu.be/tiQcTm2Go44
Not sure if you still want the log, i checked and there is no error in it.

**Comment by yaira2** [comment]
That's too bad, thanks for checking!

**Comment by yaira2** [comment]
@HyPeRXKo can you check
1. Which layout are using?
2. Is this an issue in other layouts?

**Comment by HyPeRXKo** [comment]
1. Adaptative, but it's usually detailed i think.
2. Tested every one, one by one, every layouts are doing the bug.

**Comment by HyPeRXKo** [comment]
No idea what you did but it seems like it's fixed, thanks ! :)

**Comment by yaira2** [comment]
Often times fixing one bug solves another..
