### ISSUE TITLE
Bug: Items are being auto downloaded in OneDrive, and crash if I cancel download

### ISSUE THREAD

**Issue by CaptainSodium73** [files-community/Files#13593]
### Description

When I open a onedrive folder containing .exe file(s) in Files, it automatically download them. If I cancel it in onedrive download popup, the files crash. If I let it download, Files runs okay,

### Steps To Reproduce

1. Open folder containing .exe files
2. Onedrive download popup show
3. Press cancel download
4. Files crash

### Requirements

- fix crash
- stop auto downloading

### Files Version

2.5.21.0

### Windows Version

10.0.22635.2552

### Log File

[debug.log](https://github.com/files-community/Files/files/13195077/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by gave92** [comment]
Yup happend on latest `main` too.

**Comment by yaira2** [comment]
@gave92 do you have a stacktrace?

**Comment by yaira2** [comment]
I can't repro the crash but I can repro the auto downloading.
