### ISSUE TITLE
Bug: Files crashes when transferring a large file

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#13595]
### Description

I'm copying a Macrium reflect backup (400GB) Files will crash with 2GB of it done. I'm only able to reproduce it with the one file type.

### Steps To Reproduce

1. Create Marcum reflect backup
2. Copy it to any drive
3. Wait for a few minutes
4. Files crashes

### Requirements

- Fix crash when copying file

### Files Version

2.5.33.0

### Windows Version

10.22621.2428

### Log File

[debug.log](https://github.com/files-community/Files/files/13196966/debug.log)

**Comment by yaira2** [comment]
Thank you for the report

**Comment by yaira2** [comment]
Does this also happen in stable?

**Comment by Josh65-2201** [comment]
No

**Comment by yaira2** [comment]
@Josh65-2201 confirmed this is actually happening on stable as well so it's not a blocking issue for v3.

**Comment by Josh65-2201** [comment]
Fixed in 3.0.16
