### ISSUE TITLE
Sluggish File Navigation on Large Git Repository on WSL

### ISSUE THREAD

**Issue by cardin** [files-community/Files#13596]
### Description

Files Preview hangs for seconds during navigation into large git repositories on WSL.

I've attached a Video below to reproduce it.

https://github.com/files-community/Files/assets/553816/10b89a05-6454-468f-abfa-b8f03d22eca2

### Steps To Reproduce

1. Go to WSL
2. `git clone https://github.com/vuejs/core.git`
3. Navigate into the directory
4. Files starts to hang

There is no antivirus.
Whether a NodeJS installation exists, shouldn't affect the issue (probably).

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

2.5.31.0

### Windows Version

10.0.22621.2506

### Log File

There are no errors inside debug.log.
![image](https://github.com/files-community/Files/assets/553816/b2b677b4-2653-4fa7-afa6-e12339f4e2ba)

**Comment by cardin** [comment]
Here's a recording of Files Stable, which is _slightly_ jittery, but still responsive.

https://github.com/files-community/Files/assets/553816/cc08aa7f-6169-40f8-814b-c0b1210da451

**Comment by yaira2** [comment]
@cardin is this specific to Git repos or is it for all folders in WSL? If it's specific to Git, we're tracking a similar issue in #12737.

**Comment by cardin** [comment]
It _could_ be related.

There are some things I feel might indicate it's different. At least, when I use my reproduction dataset:
- The repro dataset doesn't affect Files Stable, only Files Preview
- The repro dataset only affects Files Preview if it's on WSL, and not if it's on Windows

So it's a regression, compared to #12737

**Comment by cardin** [comment]
No longer reproducible on Files v3.0.1.0. Great job guys!
