### ISSUE TITLE
Bug: App UI not loading

### ISSUE THREAD

**Issue by saisantoshkumarbattula** [files-community/Files#13597]
### Description

after opening unable to see drives. After sometime it is getting closed

### Steps To Reproduce

1. opening
2. after clicking drive, multiple times
3. force stop

### Requirements

- e.g. Fix crash that occurs when...
force stop

### Files Version

2.5.21.0

### Windows Version

1000.22674.1000.0

### Log File

[debug.log](https://github.com/files-community/Files/files/13198128/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by saisantoshkumarbattula** [comment]
same with preview version also
here is the attachment of what i see
[image: image.png]
after clicking drives, it forces closes showing the below notification
[image: image.png]

**Comment by Josh65-2201** [comment]
Attachments don't upload using email you will have to open and upload them using the GitHub comment box. What is in the drive you are trying to open?

**Comment by saisantoshkumarbattula** [comment]
came to know that the every option is not working, i cannot click any
option if click any it will force close

**Comment by saisantoshkumarbattula** [comment]
![image](https://github.com/files-community/Files/assets/115393884/ea791e7c-3d07-49b8-8441-06a75a333245)
i cannot choose any, any click leads to force close, showing a error, the below is the error poped up
![image](https://github.com/files-community/Files/assets/115393884/ec5703d4-8b44-4772-964b-10a0f3ebb502)

**Comment by yaira2** [comment]
I saw a similar report before, it seems to be a WinUI issue but it's hard to know for sure.

**Comment by yaira2** [comment]
@saisantoshkumarbattula can you upload the log file from the latest preview version (v3)?

**Comment by yaira2** [comment]
@saisantoshkumarbattula is this still an issue in v3.0.5?
