### ISSUE TITLE
Bug: Unexpected Toolbar Between Close Tab and Add Tab Icons

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#13602]
### Description

When I open Files, a small toolbar appears between the close tab 'X' and the add tab '+' icons.

### Steps To Reproduce

1. Open Files

### Requirements

Remove the unexpected small bar between the close 'X' and the add '+' icons when there is only one tab.

### Files Version

2.5.31

### Windows Version

10.0.22621.2428

### Log File

...

**Comment by yaira2** [comment]
I believe this is the default WinUI design, I suggest opening an issue on their repo.
