### ISSUE TITLE
Checking which files are in use and by which processes on all operations (delete, move, copy, etc)

### ISSUE THREAD

**Issue by xmha97** [files-community/Files#13607]
### What feature or improvement do you think would benefit Files?

Checking which files are in use and by which processes on all operations (delete, move, copy, etc)

![image](https://github.com/files-community/Files/assets/23485114/38761e2b-34e2-4304-9be2-2e8a23cbd6e2)

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.0.36.0

### Windows Version

10.0.22621.2428

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Files will already say what programs are using a file during an operation. I assume you also want an force close button.

**Comment by xmha97** [comment]
> Thanks for the feedback, Files will already say what programs are using a file during an operation. I assume you also want an force close button.

Yes, "force close" button on operations dialogs (rename, move and etc)

**Comment by yaira2** [comment]
Files will already display the process name if it's available, but sometimes it's not accessible. Fyi @gave92
