### ISSUE TITLE
Gigantic CPU spikes when opening settings window

### ISSUE THREAD

**Issue by OwlCacone** [files-community/Files#13601]
### Description

CPU usage spikes up to almost 90% when opening the settings window for Files.
For context, I am using a old CPU, a i3-9100F to be exact. 

![Files_XlfnMUi7xM](https://github.com/files-community/Files/assets/88836728/e6b8934d-5743-47ee-ba6d-f9f33e1ab4ac)

### Steps To Reproduce

1. Open Files
2. Open the top right settings menu, represented by a cog icon
3. Check CPU activity in task manager

### Requirements

- e.g. Have Files not use almost the entire CPU's resources when opening the settings window

### Files Version

2.5.21.0

### Windows Version

10.0.19045.3570

### Log File

[debug.log](https://github.com/files-community/Files/files/13198705/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by OwlCacone** [comment]
Sure thing, I'll post my results in a bit

**Comment by OwlCacone** [comment]
In the Preview build, the settings window utilizes a lot less of the CPU's resources, around 15% at peak. 

![Taskmgr_MrzU6ZPVd3](https://github.com/files-community/Files/assets/88836728/df86f1d2-f28d-4316-8b55-a6310454b87d)

Though, I did notice that quickly clicking through folders in the Favorites tab shot the CPU usage up to around 50% at peak.
This is still a gigantic improvement, but why would the program use so many resources just for switching folders?

![Files_ffbsCgAVWN](https://github.com/files-community/Files/assets/88836728/aa062ef0-98f6-41b6-bf72-dc4eb560aaa8)

**Comment by Josh65-2201** [comment]
Files has to load the contents of that folder and if you have `Files settings > Folders > Calculate folder sizes` enabled it uses more. General performance improvements are being made and tracked in #4180.
