### ISSUE TITLE
Bug: Issue with Tab Icon Loading

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#13600]
### Description

When I rapidly select folders, the tab icon keeps loading indefinitely, even when I deselect everything.

### Steps To Reproduce

1. Quickly select only folders

### Requirements

Prevent the tab icon from loading indefinitely during rapid folder selection

### Files Version

2.5.31

### Windows Version

10.0.22621.2428

### Log File

...

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.
