### ISSUE TITLE
Taskbar does not appear when 'Automatically hide taskbar' is enabled and Files app is maximised

### ISSUE THREAD

**Issue by Dev123456689** [files-community/Files#13606]
### Description

When the 'Automatically hide the taskbar' option is enabled in the taskbar settings on a Windows 11 (Version 22H2, Build 22621.2506) system, and the user opens the "Files" application (Version 2.5.21.0) in a maximized window, there is a bug that prevents the taskbar from popping up when the cursor is hovered over the bottom of the screen.

Environment:
Files App Version: 2.5.21.0
Taskbar Settings: 'Automatically hide the taskbar' enabled
Windows Edition: Windows 11
Windows Version: 22H2
OS Build: 22621.2506

### Steps To Reproduce

1. Turn on 'Automatically hide the taskbar' from the taskbar settings.
2. Open the "Files" application.
3. Maximize the "Files" window.
4. Hover the cursor at the bottom of the screen, expecting the taskbar to appear, but it doesn't.

### Requirements

When 'Automatically hide the taskbar' is enabled, Files app is maximised and the cursor is hovered over the bottom of the screen, the **taskbar should pop up as expected**. 

### Files Version

2.5.21.0

### Windows Version

11.0.22621.2506

### Log File

[debug.log](https://github.com/files-community/Files/files/13201075/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, this has been fixed in the preview version. https://files.community/download and will be available for stable in v3 when release.
