### ISSUE TITLE
Feature: Resizing the "+" Icon for Adding Tabs

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#13603]
### What feature or improvement do you think would benefit Files?

I would like to suggest the resizing of the height of the "+" icon for adding tabs to make it resemble the one in Windows File Explorer.

### Requirements

Modify the height of the "+" icon

### Files Version

2.5.31

### Windows Version

10.0.22621.2428

### Comments

![Capture d'écran 2023-10-29 211552](https://github.com/files-community/Files/assets/128183422/56e3671e-3fbe-4e82-a396-5b99f1cb125a)

**Comment by yaira2** [comment]
Thank you for feedback, the icon size in Files is designed to be touch freindly. We don't have plans to copy File Explorer here.

**Comment by Lukiluc29** [comment]
I believe this would have been better in terms of design, although what I'm suggesting is essentially the same as the File Explorer.
