### ISSUE TITLE
Bug: Occassional COMException crash when browsing large directory on WSL

### ISSUE THREAD

**Issue by cardin** [files-community/Files#13604]
### Description

Occassionally, when browsing a large directory (large as in quantity of files) on WSL, Files Preview will crash.

There is no antivirus.

### Steps To Reproduce

This is not consistently reproducible.
There's a less than 30% chance of me reproducing it, but once it crashes, I can't reproduce it until I after reboot my computer.

1. Go to WSL
2. Navigate to a large directory in WSL
   - `/usr/bin` or `~/miniconda/bin` seems to be good candidates. These are directories with about a hundred small files.
3. <10 seconds after navigation (and a bit of scrolling), Files Preview will crash

### Requirements

Files Preview is expected not to crash

### Files Version

2.5.31.0

### Windows Version

10.0.19045.3570

Also reproducible on Windows 11.

### Log File

[debug.log](https://github.com/files-community/Files/files/13199891/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.
