### ISSUE TITLE
Bug: App crashes when opening multiple Excel tables at the same time

### ISSUE THREAD

**Issue by catz1lla666** [files-community/Files#13622]
### Description

When you select several Excel table files and try to open them simultaneously, the program closes without any errors.

### Steps To Reproduce

1. Selecting multiple table files (the number of files does not matter - 2 or more).
2. Press Enter to open files.
3. Closing the Files application, opening tables does not occur. After restarting, the application returns to its default state - all previously open tabs are closed.

### Requirements

It is necessary to fix the error with the application crashing.

### Files Version

2.5.21.0

### Windows Version

10.0.19045.3570

### Log File

[debug.log](https://github.com/files-community/Files/files/13214438/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by catz1lla666** [comment]
Unfortunately, this version also crashes.

**Comment by catz1lla666** [comment]
There is no problem yet when running the application with administrator rights (in both versions)

**Comment by Josh65-2201** [comment]
Thanks for the information, I've added this to the project board.

**Comment by yaira2** [comment]
Is this a regular Excel file with the xlsx extension?

**Comment by catz1lla666** [comment]
That's right - regular Excel files with the xlsx extension.

**Comment by catz1lla666** [comment]
I mean running the program as administrator.
I noticed one more feature - if I open files with the right mouse button from the context menu, the application usually does not crash. The crash occurs exactly when I select several files and press Enter.

**Comment by yaira2** [comment]
We're going to continue tracking this in #13609.
