### ISSUE TITLE
Bug: Crashes when manipulating files on network drive (synology nas)

### ISSUE THREAD

**Issue by brett-baker** [files-community/Files#13623]
### Description

Selected multiple files.  Choose delete... crash.  

### Steps To Reproduce

Select multiple large files not contiguous on a network drive - synology.  Large is > 1 gb.

Right click, Delete.

Crash.  

Can't reproduce all the time.

### Requirements

Multiple exceptions in log file:

### Files Version

2.5.1.0

### Windows Version

Edition	Windows 11 Pro Version	23H2 Installed on	‎3/‎14/‎2023 OS build	22635.2552 Experience	Windows Feature Experience Pack 1000.22679.1000.0

### Log File

[debug.log](https://github.com/files-community/Files/files/13216156/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by yaira2** [comment]
@brett-baker
