### ISSUE TITLE
Bug: Improve reliability of the speed graph functionality

### ISSUE THREAD

**Issue by 0x5bfa** [files-community/Files#13624]
### Description

This will be used to track a bunch of issues listed below

- [x] When the graph reaches the maximum Y, the graph gets elevated.
- [x] When I select one or more folders only and initiate compression, then cancel it, it will incorrectly report a successful operation instead of marking it as canceled.
- [x] When I select one or more folders with one or more files and start compression, then cancel it, it will erroneously report a failure instead of marking it as canceled.
- [x] When I start decompression, then cancel it, it will indicate success instead of marking it as canceled.

### Steps To Reproduce

Written above

### Requirements

- Fix all

### Files Version

2.5.21

### Windows Version

10.0.22000

### Log File

_None_

**Comment by Lukiluc29** [comment]
> When I select one or more folders only and initiate compression, then cancel it, it will incorrectly report a successful operation instead of marking it as canceled.

This remains an issue.

**Comment by Lukiluc29** [comment]
> When I start decompression, then cancel it, it will indicate success instead of marking it as canceled.

This issue is also unresolved because when I extract a folder containing only a parent folder and cancel it, it is correctly displayed as canceled. However, when I extract a folder with a parent folder and a file, and then cancel it, it takes time to cancel and is displayed as successful.
