### ISSUE TITLE
Feature: Hide Unavailable Information in the Preview Pane

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#13626]
### What feature or improvement do you think would benefit Files?

When I navigate to my C: drive, for example, the creation date and modification date do not appear, which is a bit disappointing. I suggest that when a folder does not contain certain information, such as the modification or the creation date, it should not be displayed to avoid cluttering the preview pane with empty space.

### Requirements

Implement a mechanism that filters and displays only relevant folder information.

### Files Version

2.5.31

### Windows Version

10.0.22621.2428

**Comment by yaira2** [comment]
Thank you for the feedback, we're tracking this in #12597.
