### ISSUE TITLE
Bug: Dragging file to Notepad++ window to open does not show "Move" option

### ISSUE THREAD

**Issue by nrm6dr** [files-community/Files#13636]
### Description

When dragging a text file (.txt,.sh,.k) from Files to Notepad++, the file does not open. Instead of the typical "Move" option showing by the cursor, a circle with a line through it is shown to indicate that it won't work.

### Steps To Reproduce

1. Open files to a directory with a text file of any type
2. Open Notepad++
3. Click and drag text file from Files to Notepad++
4. See circle with a line through it.

### Requirements

- I expect the text file to open when dragged into Notepad++ and the mouse button is released

### Files Version

2.5.21.0

### Windows Version

Windows 11 Education 23H2 build 22631.2428 Windows Feature Experience Pack 1000.22674.1000.0

### Log File

[debug.log](https://github.com/files-community/Files/files/13228831/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, we're currently tracking this issue in #11735.
