### ISSUE TITLE
Files attempts to check for updates when there is no internet connection

### ISSUE THREAD

**Issue by d0j1a1701** [files-community/Files#13635]
### Description

When Files starts, it will attempt to check for updates using the "Windows App Installer". However, if there is no internet connection, the check will fail after several seconds of loading, resulting in a delay of several seconds for Files to load in a network-less environment. Is it possible to disable automatic updates and force manual updates?

### Steps To Reproduce

1. Unplug the network cable.
2. Open Files.

### Requirements

1

### Files Version

2.5.32.0

### Windows Version

10.0.23575.1001

### Log File

1

**Comment by Josh65-2201** [comment]
Thanks for the report, This is an issue with App Installer and there isn't a option to turn off update checking. Best thing to do is not close Files.

**Comment by d0j1a1701** [comment]
But it is not realistic to close Files, because if you are in a place without internet, you can't even view local files.

**Comment by d0j1a1701** [comment]
But it is not practical to close Files, because it does not automatically start when the computer is turned on

**Comment by yaira2** [comment]
This is an issue with AppInstaller. I know this solution won't help if you use the preview version, but if you use the Store version it won't have this behavior.
