### ISSUE TITLE
Bug: Opening Git directory automatically switches branches

### ISSUE THREAD

**Issue by Pietro228** [files-community/Files#13647]
### Description

Hi,

few weeks ago, I opened my project in Files and it prompted me tu sync it with Git - I clicked the second button to cancel it. Visual Studio said, that it needs a restart to apply new changes in my code (I though that it was because of one specific build error), so I restarted it. After opening VS, I was shocked. It removed my whole progress to the last commit, which was 4 hours of work. I had to write my code again, without any option to revert it.

Two days ago, I opened my project in Files and it prompted me to sync my progress on my branch with Git. I remembered, that last time I picked "Cancel", so now I picked to keep the local changes (I don't remember how it was named) on my branch. Luckily, it didn't remove my whole progress, but it brough back almost 2 month old changes that created merge conflicts. I had to resolve every conflict to get my progress back. It looked like it was merging with stashed changes (I really don't know why, because I didn't create them).

Why does it want to merge old random files and delete my progress when I'm on the same branch for like 3 months already? I did not change my branch at all. Files always showed my current branch whose name was correct.

For now I'll stop using Files until it's fixed.

### Steps To Reproduce

1. Open your project folder
2. There's a small chance that a content dialog appears with options what to do with your branch settings

### Requirements

1. Identify why the content dialog is displayed
2. Make sure it only shows if the user specifically chooses an action

### Files Version

3.5.31.0

### Windows Version

10.0.22635.2552

### Log File

[debug.log](https://github.com/files-community/Files/files/13244166/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by Pietro228** [comment]
Update: I found out that this is the dialog that randomly pops up. It's for switching the branch, but even when you click "Zrušit" (Cancel) it still removes your progress.
![obrazek](https://github.com/files-community/Files/assets/53868994/169bf6e9-95a5-451c-913f-19785f8c8546)


The second time I was it I chose the "Keep my changes on 'Beta'" (the 2nd one), but it created merge conflicts.

**Comment by Pietro228** [comment]
For now I have just revoked File's access to my GitHub account, which should make it safe to use without the bug appearing. This should disable the GitHub integration, right? :D

**Comment by yaira2** [comment]
@Pietro228 the GitHub integration is only for pushing changes to the remote repo. It sounds like this issue can still affect your local changes.

**Comment by Josh65-2201** [comment]
It wont be edited if you don't open the git folder with Files.

**Comment by yaira2** [comment]
Please let us know if anyone else is able to reproduce this issue.

**Comment by Pietro228** [comment]
> @Pietro228 the GitHub integration is only for pushing changes to the remote repo. It sounds like this issue can still affect your local changes.

That's a pity :(

> It wont be edited if you don't open the git folder with Files.

But I need to access it frequently, because I have to work with binaries.

> Please let us know if anyone else is able to reproduce this issue.

Alright.

**Comment by Josh65-2201** [comment]
You can change the branch in Visual studio or even the command line.

**Comment by Pietro228** [comment]
I know, but I don't want to change it. I'm a solo dev, so I don't need to switch it that frequently

**Comment by yaira2** [comment]
Thank you for taking the time to report this, we'll continue investigating and will let you know if/when we identify the cause.

**Comment by yaira2** [comment]
We still haven't been able to repro this issue but we'll keep looking.

**Comment by yaira2** [comment]
@Pietro228 have you been able to repro this since opening the issue?

**Comment by Pietro228** [comment]
@yaira2 I haven't used Files since then, because it's still not that stable for my needs. However when I try to reproduce it now, it doesn't appear. Maybe it could appear randomly one day, but I don't use Files on daily.

**Comment by yaira2** [comment]
> However when I try to reproduce it now, it doesn't appear

We've also been monitoring for similar reports and haven't heard any so it's likely our refactoring fixed the issue. That said, if anyone has is able to repro this issue, please let us know so that we can investigate further.
