### ISSUE TITLE
Bug: Missing tooltips for "Open" and "Open folder in VS Code"

### ISSUE THREAD

**Issue by A-Loot** [files-community/Files#13641]
### Description

When you are in a repository 3 buttons will show up at the bottom. The first displays and lets you change the current branch, the second shows incoming and outgoing commits and lets you Pull/Push, and the third lets you open the current folder/repository in VS Code (maybe other programs too, Idk). All except the third have tooltips.

### Steps To Reproduce

1. Open a repository in Files
2. Hover your mouse over the "Open" button. You will see that no tooltip appears.
3. Click on "Open" and then hover over one of the "Open with..." buttons. You will see it doesn't have a tooltip either.
4. Hover over any other buttons in the App, you will see all of them (should) have tooltips.

https://github.com/files-community/Files/assets/105282948/030e7564-eacf-4466-856c-9bc1df5ac5c3

### Requirements

- add a tooltip for the "Open" and "Open folder in ..." buttons

### Files Version

2.5.33.0

### Windows Version

10.0.22635.2552

### Log File

-

**Comment by yaira2** [comment]
This is fine for now as users can't assign custom keyboard shortcuts to these actions, but we'll want to display the tooltip once this is the case.
