### ISSUE TITLE
Feature: manage GitHub in Settings

### ISSUE THREAD

**Issue by A-Loot** [files-community/Files#13640]
### What feature or improvement do you think would benefit Files?

It would be nice to be able to manage the connection to your GitHub account in the Settings window. As far as i know you can only connect to an account when performing certain actions in a repository that require you to log in (e.g. Pull/Push from/to a private repo). And I'm pretty sure you can only disconnect in the GitHub settings but not in the App.

### Requirements

- Add the option to manage your GitHub connection to the Settings window

### Files Version

2.5.33.0

### Windows Version

10.0.22635.2552

**Comment by yaira2** [comment]
Thank you for your feedback, we're currently tracking this in #12798.
