### ISSUE TITLE
Locked tab

### ISSUE THREAD

**Issue by Shengwuei** [files-community/Files#13650]
### What feature or improvement do you think would benefit Files?

hope some of the tabs can be locked, ie. when a tab is locked, double click the folders within the tab will open a new tab, instead of go into the folder in the same tab.

for example, assume I have the below folders :

D:\folder_a
D:\folder_a\folder_b

if I have a folder_a tab, and the tab is locked, within the tab if I double click folder_b, a new tab with folder_b is created instead of changing the tab from folder_a to folder_b.

This feature is very useful for creating shortcuts of frequently used folders, would save a lot of time if these folders are within many levels of folder structure.

Thanks.

### Requirements

double click on a tab to lock/unlock the tab

### Files Version

the latest 

### Windows Version

Windows 11

**Comment by Josh65-2201** [comment]
Thanks for the feedback you can already middle click or right click > Open in new tab.

**Comment by yaira2** [comment]
There is also an option to always open folders in a new tab.
![image](https://github.com/files-community/Files/assets/39923744/3588a74c-087f-4b27-bd37-c50561690df9)

**Comment by Shengwuei** [comment]
always open folders in new tab does not fit my requirement

I am using Tabcalus explorer, below is a screen shot example :
![image](https://github.com/files-community/Files/assets/140904608/62ef5ee6-8242-4ce7-ba80-e95636b538fc)

as you can see, I have few locked tabs ("Datasheet", "Array US", "Weekly report"...) and some tabs are not locked ("File_explorers","20230830_SonitronGTS_ODM")

Say I want to find a file under "D:\GoogleDrive\Work\Datasheet\folder_a\folder_b\folder_c\folder_d\myfile.pdf", firstly I can directly click the "Datasheet" tab since it is locked so is always there(no need to start from "D:" then "GoogleDrive" then "Work"), and then I click "folder_a" to create a new tab(due to "Datasheet" is locked), then I click "folder_b" then "folder_c" then "folder_d" within the same tab(due to this tab is not locked) then I find my file, if a new tab is created each time I click a folder there will be too many useless tabs, hope I am clear about my usage situation.

**Comment by yaira2** [comment]
> always open folders in new tab does not fit my requirement

There is also the `ctrl` + `enter` shortcut to open a folder in a new tab.

**Comment by yaira2** [comment]
The option to lock tabs (not present in Files) is usually thought of to prevent accidentally closing the tab, but not to prevent navigating within the tab.

**Comment by yaira2** [comment]
@Shengwuei did you try the `ctrl` + `enter` shortcut?

**Comment by Shengwuei** [comment]
@yaira2 

yes ctrl+enter opens a folder in a new tab, thanks for letting me know this technique.

By the way, I just know I can add the most frequently used folders in the "favorites" so I can directly access them any time, items in the "favorites" can be add/remove or reorder, this feature is pretty identical to the locked tab, I should have noticed this feature earlier, thanks.

![image](https://github.com/files-community/Files/assets/140904608/68b79621-1d21-4dbc-bdb3-7e9b02954f30)
