### ISSUE TITLE
Show different IDE's for project files inside the directory

### ISSUE THREAD

**Issue by Founntain** [files-community/Files#13655]
### What feature or improvement do you think would benefit Files?

Currently, when you have a folder open that has a git repository inside it shows in the bottom left to open it with visual studio.

![image](https://github.com/files-community/Files/assets/28785685/c8fe952b-0ed7-4ecc-b93b-5779ac74a16b)

First I find it odd, that it even suggest Visual Studio as an option down there as I don't have Visual Studio installed on my system. 

![image](https://github.com/files-community/Files/assets/28785685/b9daecbf-32f6-4865-b0ff-e41e4c5ab04c)

If I click it, because I wondered it opened my Rider, which I totally like. So it somehow found my Rider installation and opened the solution. 
> *it maybe also just tried to open it with the app, that is set as default for .sln files*

### Requirements

I would love if it says Rider (or any other IDE that is set as default for .sln files) instead of Visual Studio, as [the statement to it](https://github.com/files-community/Files/issues/12632#issuecomment-1595940393) is misleading and wrong in my opinion. Because it would make it better because of the following reasons:

1. It's misleading as it doesn't open Visual Studio at all
2. It would make more sense to show the actual IDE it will try to open.

If it's not possible at all to implement it a different name would be more fitting for example. Open in IDE etc. etc. pretty generic and overall fitting name.

### Files Version

2.5.21.0

### Windows Version

OS Build: 22621.521 
Experience: 1000.22634.1000.0

**Comment by Founntain** [comment]
I was actually looking at the pull request of the implementation and it looks indeed like it, that it will use the default app for .sln files.

I don't know how much has changed since it, as I can't seem to find it in the current main branch.

https://github.com/ferrariofilippo/Files/blob/57b6240258310231ad28e414c839094a141758cb/src/Files.App/Actions/Open/OpenInVSAction.cs#L40

**Comment by yaira2** [comment]
@Founntain the current branch only shows for VS Code. We're tracking support for changing/adding IDEs in #12857.
