### ISSUE TITLE
Bug: Hebrew (R2L) file names not displaying correctly

### ISSUE THREAD

**Issue by yIsItSo** [files-community/Files#13658]
### Description

Hebrew file names should still display the file suffix on the right

![image](https://github.com/files-community/Files/assets/126057362/fbc59bbe-fc39-47d6-90c3-eddd763d59ba)

### Steps To Reproduce

create a file with Hebrew characters in the name

### Requirements

display correctly, as in Explorer

### Files Version

2.5.35.0

### Windows Version

10.0.22635.2700

### Log File

[debug.log](https://github.com/files-community/Files/files/13257262/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
@yIsItSo how are extensions displayed when renaming an item in File Explorer?

**Comment by yIsItSo** [comment]
I am not sure what the question is but when renaming in explorer the file name is highlighted by default ant not the extension.
This also happens in Files.


________________________________

**Comment by yIsItSo** [comment]
Right
![image](https://github.com/files-community/Files/assets/126057362/e6bbe2db-fed6-4a33-9a76-5c859e747e51)

**Comment by JaiganeshKumaran** [comment]
File extensions are always at the right; 'Pdf.שם-קובץ' would represent a different file in the filesystem.

**Comment by yIsItSo** [comment]
Pdf is the extension.
________________________________

**Comment by yaira2** [comment]
As far as the file structure goes, the extension is part of the file name. File Explorer seems to have custom logic but it's not something we plan to implement in Files.
