### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MMagine** [files-community/Files#13657]
### Description

When running files as administrator, files crash if you drag files

### Steps To Reproduce

1.run files as admin
2.drag a file

### Requirements

Hope to fix it soon as I need this feature very much

### Files Version

2.5.21.0

### Windows Version

11build25987.1000

### Log File

[debug.log](https://github.com/files-community/Files/files/13256819/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Drag and drop as admin is not supported due to Windows issues. It will be disabled on the next update so Files wont crash.

**Comment by yaira2** [comment]
@MMagine can you confirm if this is fixed in the latest preview version? https://files.community/download/preview
