### ISSUE TITLE
image preview not working

### ISSUE THREAD

**Issue by Shengwuei** [files-community/Files#13669]
### Description

image preview is not working (I've switched to "extra large icon")
![image](https://github.com/files-community/Files/assets/140904608/29a521e9-0e43-42c0-9808-798462235f86)

I have also turned the "Show thumbnails" on
![image](https://github.com/files-community/Files/assets/140904608/8d3f5bbc-125f-40ab-9e6a-d51849daa29f)

not sure if previewing images is supported or not ?

### Steps To Reproduce

1. go into any folders with images
2. image is not previewed

### Requirements

preview the images, not icons only

### Files Version

2.5.21.0

### Windows Version

Windows 11, 22H2

### Log File

there is no log

**Comment by Josh65-2201** [comment]
Thanks for the report. Can you give the following information.
- Can you see if this is an issue in the preview version. https://files.community/download
- If so do they show in Windows File Explorer?
- Where are they store (Cloud, local drive, network drive etc.)

**Comment by bilge-discobolus** [comment]
I have a similar problem with image display not working but it's seemingly random.  Sometimes all images in a folder display in full resolution, sometimes a few in full resolution and some in low-res, and other times all i see are generic icons and no pictures at all.  I have three monitors on my computer including the notebook screen, and this occurs on all three... moving Files to another screen does not fix the problem (I had wondered if it might be a video driver issue).

**Comment by yaira2** [comment]
@bilge-discobolus is this in OneDrive?

**Comment by bilge-discobolus** [comment]
No, local hard drive

Bill Gervasi
Memory Technology Analyst
Discobolus Designs
***@***.******@***.***>
+1-408-621-4157

**Comment by yaira2** [comment]
Which app do you have associated with those image files?

**Comment by bilge-discobolus** [comment]
Let’s see…

JPG = Photos
PNG = Photos

It’s a new computer, so I assume these are defaults.

Bill Gervasi
Memory Technology Analyst
Discobolus Designs
***@***.******@***.***>
+1-408-621-4157

**Comment by Josh65-2201** [comment]
Are you sure the default program for those files make thumbnails? 
If it does the Windows File Explorer modifications may have broken thumbnail generation too since Files gets thumbnails from Windows.

**Comment by yaira2** [comment]
@Shengwuei for testing purposes, can you see what happens if you clear the thumbnail cache in Windows, and change the default program for those files to the Photos app?

**Comment by Shengwuei** [comment]
> @Shengwuei for testing purposes, can you see what happens if you clear the thumbnail cache in Windows, and change the default program for those files to the Photos app?

Hi Yaira2,

I cleared the thumbnail cache and changed the default program to Photos,

![image](https://github.com/files-community/Files/assets/140904608/0e8a25c5-b3d9-4512-80bc-537ebf91c047)

![image](https://github.com/files-community/Files/assets/140904608/dc6d6512-0378-4fbc-ab87-b8c253697593)

but still not able to see thumbnails, thanks.

![image](https://github.com/files-community/Files/assets/140904608/dbe02a5e-dd16-4550-b57a-6763ed6751cc)

**Comment by yaira2** [comment]
Unfortunately this seems to be a Windows issue, if you want, you can see if running `sfc /scannow` helps.

**Comment by bilge-discobolus** [comment]
Same problem.

I also left the display mode as default; previously I had chosen a dark mode and had wondered if the display mode was the factor.

Bill Gervasi
Memory Technology Analyst
Discobolus Designs
***@***.******@***.***>
+1-408-621-4157

**Comment by bilge-discobolus** [comment]
Also verified that it fails on both notebook screen as well as external monitors.

Bill Gervasi
Memory Technology Analyst
Discobolus Designs
***@***.******@***.***>
+1-408-621-4157

**Comment by bilge-discobolus** [comment]
Ran sfc /scannow, no errors, did not fix the problem

Downloaded and installed Quick Picture Viewer, set this as the default for jpg, etc.  Problem went away.

Seems to be an incompatibility with Microsoft Photo Viewer?

Bill Gervasi
Memory Technology Analyst
Discobolus Designs
***@***.******@***.***>
+1-408-621-4157

**Comment by yaira2** [comment]
That could be the case.
