### ISSUE TITLE
Mapped network drives with duplicate drive letters

### ISSUE THREAD

**Issue by rfgamaral** [files-community/Files#13661]
### Description

Pretty much what the title says, but a screenshot will help:

![Screenshot 2023-11-05 102908](https://github.com/files-community/Files/assets/96476/9eb6bd12-1616-45fc-9009-277fcc6d8ac4)

As you can see, I have 3 mapped network drives, and they all have the drive letter duplicate in the name. Both in the sidebar but also in the Home widget.

### Steps To Reproduce

1. Create a mapped drive on Windows Explorer
2. Rename the mapped drive to something of your choosing (I did that to remove the network path from the name)
3. Check how Files has the drive letter duplicate in the mapped folder

### Requirements

- Only show the drive letter once for mapped network drives

### Files Version

2.5.21

### Windows Version

Windows 11 Pro, 23H2, 22635.2700

### Log File

I'm currently on a different computer, and don't have access to the log file. I can post it later if you really need it for this issue. Please let me know.

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by rfgamaral** [comment]
@Josh65-2201 Thanks for the quick reply.

I installed both versions on the current computer I'm using (not the same one where I originally found this issue), and I can reproduce it with the stable version, but the preview version does not have this problem 🥳

Hope you can push the preview version to stable soon 🤞, keep up the good work folks 👍

**Comment by Josh65-2201** [comment]
Thanks for checking. v3 with the fix is already being rollout to stable.

**Comment by rfgamaral** [comment]
> Thanks for checking. v3 with the fix is already being rollout to stable.

Oh, that's awesome, but I think the deployment failed:
![image](https://github.com/files-community/Files/assets/96476/3aaa8b1e-892f-439b-8bf4-b6ec02bf382c)

**Comment by Josh65-2201** [comment]
Those aren't relevant for making a update to Files as it already out. There just for testing PRs made work, not sure exactly what there testing for though.

**Comment by rfgamaral** [comment]
I just assumed because v3 is not available in the [Releases](https://github.com/files-community/Files/releases) page.
