### ISSUE TITLE
Bug: System.FormatException: The input string was not in a correct format

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#13663]
### Description

https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/3744342845u/overview

### Steps To Reproduce

Unknown

### Requirements

- Fix crash

### Files Version

v3

### Windows Version

10.0.22621

### Log File

System
Number.ThrowOverflowOrFormatException (ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
System
Number.ParseInt64 (ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
System.String.System
IConvertible.ToInt64 (IFormatProvider provider)
Files.App.ViewModels.Properties.FileProperty.<>c
<.cctor>b__79_1 (Object input)
Files.App.ViewModels.Properties
FileProperty.ConvertToString ()
Files.App.Views.Properties.DetailsPage
DetailsPage_obj8_Bindings.Update_ (FileProperty obj, Int32 phase)
ABI.Microsoft.UI.Xaml.Markup
IDataTemplateComponent.Do_Abi_ProcessBindings_1 (IntPtr thisPtr, IntPtr item, Int32 itemIndex, Int32 phase, Int32* nextPhase)
WinRT
ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0 (Int32 hr)
ABI.Windows.ApplicationModel.Core
IUnhandledErrorMethods.Propagate (IObjectReference _obj)
Microsoft.AppCenter.Utils
ApplicationLifecycleHelperWinUI.<ctor>b__0_3 (Object sender, UnhandledErrorDetectedEventArgs eventArgs)

**Comment by hecksmosis** [comment]
fyi, the app center link will only work for those with access to the organisation

**Comment by yaira2** [comment]
That's true, that's why I included the crash report. Unfortunately it doesn't include line numbers but this issue should be easy to find if you search for `ConvertToString`.
