### ISSUE TITLE
Feature: Add shortcut to open preview pane (as opposed to details pane)

### ISSUE THREAD

**Issue by winston-de** [files-community/Files#13679]
### What feature or improvement do you think would benefit Files?

A shortcut to allow users to switch between the details and preview views of the preview pane would make Files more accessible. 

### Requirements

- Allow users to switch between the preview and details view of the preview pane with a keyboard shortcut. 
- Proposed solution A: Use Alt+Shift+P (or similar) to open the preview, and Alt+P to open the preview.
- Proposed solution B: some other arbitrary keyboard shortcut to toggle between the two views.

### Files Version

3.0

### Windows Version

19045.3570

**Comment by yaira2** [comment]
@winston-de you can already use `ctrl + p` to open the pane, the way it's currently setup, it'll default to whichever pane was last selected.

**Comment by win7guru** [comment]
This solved my problem, thank you.
