### ISSUE TITLE
Bug: m4a files can't be played from the preview pane

### ISSUE THREAD

**Issue by mehrdel2002-hub** [files-community/Files#13674]
### Description

m4a files can't play in detail and preview pane. click on play button doing nothing.
Also click on detail tab in properties page make app crash.

### Steps To Reproduce

1. click on m4a file
2. click on play button in the detail pane

for detail crash:
1. click on m4a file
2. click on properties icon on top of pane
3. click on detail tab
4. crash!!!

### Requirements

- e.g. Fix crash that occurs when...
- fix crash that occurs when click on properties detail tab
- fix bug that m4a files can't be playing in the detail and preview pane

### Files Version

3.0.0.0

### Windows Version

10.0.22635.2700

### Log File

[debug.log](https://github.com/files-community/Files/files/13267685/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
@hishitetsu can you check if it's visible in the preview pane?

**Comment by yaira2** [comment]
This report in AppCenter might be related https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/1720556795u/overview

**Comment by hishitetsu** [comment]
It is displayed like this.
![image](https://github.com/files-community/Files/assets/66369541/3afd78c2-42e5-422e-b2ff-c901b0be4040)

**Comment by hishitetsu** [comment]
I don't know why the playback button doesn't show up, but I have found the cause of the crash and will fix it.

**Comment by yaira2** [comment]
@mehrdel2002-hub is this still an issue in v3.0.3?

**Comment by hishitetsu** [comment]
I have noticed that the controls may or may not show up depending on the environment. It shows up on a Windows 11 23H2 physical machine, but not on a 22H2 VM.

**Comment by yaira2** [comment]
That's strange, it should work across all platforms. We can work around this by removing the custom media preview and just relying on the shell, but unless you enable the classic Windows Media Player, the shell doesn't have any media preview by default.

**Comment by yaira2** [comment]
@mehrdel2002-hub Is this still an issue in the preview version? https://files.community/download/preview
