### ISSUE TITLE
Bug: High contrast icon is used when high contrast isn't enabled in Windows

### ISSUE THREAD

**Issue by Koichi-Kobayashi** [files-community/Files#13672]
### Description

I received an upgrade notification, so I upgraded and the icon seemed to have changed, but it was not colored.
The previous v2.5.21 had a blue icon similar to Windows 11 Explorer.

![2023-11-06_19h47_21](https://github.com/files-community/Files/assets/2451210/0fc49590-0abc-4f22-9513-8b3f8e4a768d)

### Steps To Reproduce

Upgrading from v2.5.21

### Requirements

To be an orange-based icon.

### Files Version

3.0.0.0

### Windows Version

10.0.25987.1000

### Log File

[debug.log](https://github.com/files-community/Files/files/13265616/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
This seems to be an issue in light mode, I'll take a look.

**Comment by yaira2** [comment]
I identified the issue and a fix will be released soon.
