### ISSUE TITLE
Silent Install of Files.Stable.exe?

### ISSUE THREAD

**Issue by DARO75** [files-community/Files#13683]
### What feature or improvement do you think would benefit Files?

what are the parameters for a silent installation?

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.0

### Windows Version

22635.2700

**Comment by yaira2** [comment]
Thanks for the feedback, the classic installer doesn't have a silent option but you can install via PowerShell `Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/stable/Files.Package.appinstaller`.

**Comment by boscorelly** [comment]
Hi,

that's not a solution.

It's not possible to deploy the app with intune for exemple.

Silent install must be mandatory.
