### ISSUE TITLE
tab divider is displayed at the selected tab

### ISSUE THREAD

**Issue by Silther** [files-community/Files#13688]
### Description

Something very minor
tab divider is displayed at the selected tab 
it should probable only be displayed between not selected tabs

![Screenshot 2023-11-06 193008](https://github.com/files-community/Files/assets/97352673/404ec5c5-cc67-4323-8960-083d860a2e15)

### Steps To Reproduce

1. create new tabs
2. switch between tabs
3. (sometimes it is also displayed if you hover over other tabs)

### Requirements

only shown tab divider between non selected tabs and stop it from flickering 

### Files Version

v3.0.0.0

### Windows Version

10.0.22621.2506

### Log File

[debug.log](https://github.com/files-community/Files/files/13272268/debug.log)

**Comment by yaira2** [comment]
Thanks for the feedback, I've been seeing quite a few of these reports. @chingucoding do you know if this is a bug with the WinUI tab control?

**Comment by chingucoding** [comment]
Since the issue is also present in the WinUI Gallery, I'm fairly sure its not on our end. The issue is that the divider is also present on the last tab even though it should be hidden which probably makes a workaround a bit harder to implement.
