### ISSUE TITLE
Wrong Icon after v3.0 Update

### ISSUE THREAD

**Issue by Silther** [files-community/Files#13687]
### Description

![Screenshot 2023-11-06 200146](https://github.com/files-community/Files/assets/97352673/57637ceb-51a6-4ccf-9e49-9d70db2132e4)

This icon is shown instead of:

![Screenshot 2023-11-06 212436](https://github.com/files-community/Files/assets/97352673/247c3601-b924-430b-85af-9a00741df18d)

### Steps To Reproduce

update to v3.0 (only on one of two PCs)

### Requirements

show the correct icon

### Files Version

3.0.0.0

### Windows Version

10.0.22621.2506

### Log File

[debug.log](https://github.com/files-community/Files/files/13272167/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report. this has been fixed in 3.0.1.0

**Comment by yaira2** [comment]
@Silther thank you for the report, this was indeed a bug with the icon in light mode. We have already deployed a fix and it should be available in a couple of hours.
