### ISSUE TITLE
Feature: Preview Pane for Multiple Selections

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#13685]
### What feature or improvement do you think would benefit Files?

When I select multiple items with the preview pane open, it only displays details for the first item. I suggest that when multiple items are selected, the preview pane should show an icon indicating multiple selections and provide information about the multiple selection, such as the path (all in...), similar to what the properties page does.

### Requirements

Develop a feature that indicates when multiple items are selected in the preview pane, such as an icon.
Ensure that the preview pane can display relevant information for multiple selections, like path.

### Files Version

3.0.1

### Windows Version

10.0.22621.2506

**Comment by yaira2** [comment]
Thank you for the feedback. We're tracking something similar in #12489, can you add a comment there regarding the preview aspect?
