### ISSUE TITLE
need to add traditional list view

### ISSUE THREAD

**Issue by onlysublime** [files-community/Files#1368]
**Is your feature request related to a problem? Please describe.**
The Files UWP doesn't have the traditional list view.  The list view looks like the traditional Details view.  While it matches the list view of things like OneDrive.com, it doesn't match the traditional list view.  The list view maximizes window space to see the most content.

**Describe the solution you'd like**
The Files UWP doesn't have the traditional list view.  The list view looks like the Details view.  While it matches the list view of things like OneDrive.com, it doesn't match the traditional list view.  

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by Jaiganeshkumaran** [comment]
@yaichenbaum Could you assign me on this issue?

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran Have you made any progress on this feature?

**Comment by yaichenbaum** [comment]
Merging with #2509.

**Comment by yaira2** [comment]
@onlysublime thank you for your patience, I'm excited to share that a List View layout will be included in the next release.
