### ISSUE TITLE
Make the app icon colored on taskbar, not a monochrome outline

### ISSUE THREAD

**Issue by luckyscooby** [files-community/Files#13686]
### What feature or improvement do you think would benefit Files?

Installed version 3 and I think the new app icon with yellow shades is awesome, the best so far among all file managers, in my opinion! But I got frustrated when it showed as a monochrome outlined icon on the taskbar 😞

### Requirements

- This proposal will accomplish a more consistent and elegant UI and product design.

### Files Version

3.0.0.0

### Windows Version

10.0.22621.2506

**Comment by Josh65-2201** [comment]
Thanks for the report. this has been fixed in 3.0.1.0

**Comment by yaira2** [comment]
@luckyscooby thanks for the report, this was indeed a bug with the icon in light mode. We already deployed a fix and it should be available in a couple of hours.
