### ISSUE TITLE
Bug: Proton drive is mapped to the wrong folder

### ISSUE THREAD

**Issue by Silther** [files-community/Files#13689]
### Description

if you click on the proton cloud drive in the side menu it opens the folder `C:\Users\USER\Proton Drive`, but the files you can actually sync are inside the folder `C:\Users\USER\Proton Drive\My files`.
this is a really strange way proton has structured their drive, but so far the following folder always opens, where you have to open the `My Files` folder to get to the actual data

![Screenshot 2023-11-06 220349](https://github.com/files-community/Files/assets/97352673/a6d50f5a-d56f-4258-ac77-20479f1894f4)

You cannot even put files into the `C:\Users\USER\Proton Drive` folder

### Steps To Reproduce

1. install proton drive
2. open it in files

### Requirements

make it so the proton drive button in the sidebar directly opens the `C:\Users\USER\Proton Drive\My files` folder if there is only a `My files` folder in it

### Files Version

3.0.0.0

### Windows Version

10.0.22621.2506

### Log File

[debug.log](https://github.com/files-community/Files/files/13272414/debug.log)

**Comment by yaira2** [comment]
Is "My files" always going to be there or can it be reconfigured?

**Comment by yaira2** [comment]
Can you also clarify what the behavior is in File Explorer?

**Comment by nephi-duff** [comment]
@Silther You can update it in the Proton Drive client

![image](https://github.com/files-community/Files/assets/70173112/dbf6de92-9675-4565-859a-ca3bb62f88d8)

**Comment by yaira2** [comment]
What happens if you open Proton in File Explorer?

**Comment by yaira2** [comment]
We could change the folder that gets pinned to the sidebar, but it would display the folder name instead of "Proton Drive". Is this what the community wants?

**Comment by yaira2** [comment]
The sidebar name is based on the path so it would show "My files".

**Comment by yaira2** [comment]
Thanks for the feedback
