### ISSUE TITLE
Offline or portable Installer

### ISSUE THREAD

**Issue by flappysquirrel** [files-community/Files#13696]
### What feature or improvement do you think would benefit Files?

With release of version 3.0, now would be an excellent time to provide an offline and/or portable installer.

### Requirements

Please provide a downloadable version that does not require an internet connection to install.

### Files Version

Version 3.0

### Windows Version

22H2

**Comment by yaira2** [comment]
Thank you for the feedback, you can download the offline installer here. `https://cdn.files.community/files/preview/Files.Package_3.0.1.0_Preview_Test/Files.Package_3.0.1.0_x64_ARM64_Preview.msixbundle`
