### ISSUE TITLE
Colored drive progress bar according to used space

### ISSUE THREAD

**Issue by dragoni7** [files-community/Files#13699]
### What feature or improvement do you think would benefit Files?

Have the drive progress bar change color according to it's used space percentage.
Use case: user wants to quickly be able to tell if their drive is near full by looking at the home page.

### Requirements

- Add a new property for drive progress bar color
- Change the xaml to include color for the drive's progress bar element

### Files Version

3.0.1.0

### Windows Version

10.0.19045.3570

**Comment by yaira2** [comment]
Thank you for your feedback, please see our discussion in #13553.

**Comment by yaira2** [comment]
I also want to point out the information icon that's displayed next to drives that are close to filled. This helps indicate when drives are getting full, and provides a shortcut to the storage settings in Windows.

**Comment by dragoni7** [comment]
I viewed the discussion and the reasoning for not implementing the feature
I understand that it would clash with themes
