### ISSUE TITLE
Background process

### ISSUE THREAD

**Issue by hacky4real** [files-community/Files#13705]
### Description

Background process: doesn't apply to Newly opened window, when an existing window exits 

### Steps To Reproduce

1. Open the files app
2. Minimise the window
3. Open a new window (I used Win+E)
4. The app reloads

### Requirements

Background process

### Files Version

3.0.1.0

### Windows Version

22H2

### Log File

1. Open the files app
2. Minimise the window
3. Open a new window (I used Win+E)
4. The app reloads

**Comment by yaira2** [comment]
Thank you for the feedback, this is because each window is its own instance. It's something we're working on changing and will be solved together with #12689.
