### ISSUE TITLE
Files download OneDrive's online file

### ISSUE THREAD

**Issue by CaptainSodium73** [files-community/Files#13704]
### Description

The lastest files: v3, I opened and picture folder on my onedrive, it download (make offline available) all the file. As well as another folder contain files. (problem not occur on folder just contain folder)
v2.5 just have these problem with .exe file, other not but now pictures file, iso file download, too

### Steps To Reproduce

1. Open Files app
2. Click onedrive folder
3. Open an folder in Onedrive contain file
4. files download popup

### Requirements

Fix that bug. 

### Files Version

3.0.1.0

### Windows Version

10.0.22621.2506

### Log File

[debug.log](https://github.com/files-community/Files/files/13279436/debug.log)

**Comment by yaira2** [comment]
@CaptainSodium73 thanks for the report, I updated #13593 with this information. I'm going to close this issue so we can continue tracking it in one issue.
