### ISSUE TITLE
Installation cannot be carried out

### ISSUE THREAD

**Issue by DARO75** [files-community/Files#13707]
### Description

Installation cannot be executed. A deactivated service prevents it. Which service is this and why is the installation dependent on Windows services? 

### Steps To Reproduce

.

### Requirements

- e.g. Fix crash that occurs when...
.

### Files Version

3.0.1

### Windows Version

22635.2700

### Log File

.

**Comment by yaira2** [comment]
Please try enabling the Windows Update and Delivery Optimization services on your device. Msix apps require these services as they contain the apis that are used to handle the packaging technology. It's a little counter intuitive that they are bundled with the Windows Update service but if it helps, you can disable the services after the installation is complete, they are only needed for installing or updating the app.
