### ISSUE TITLE
Bug: Progress status: UI and counter bugs

### ISSUE THREAD

**Issue by Jay-o-Way** [files-community/Files#13706]
### Description

When permanently deleting a large folder with many items:

- The header isn't fully readable.
- The speed isn't readable. (it overlaps with the graph)
- The _items-done_ exceeds _total-items_ (I'm guessing some type of files {like hidden} aren't added to the total count?)
  - Note that the graph also stops moving, because the _percentage_ > 100.

![image](https://github.com/files-community/Files/assets/65828559/1fe4d12a-5f97-48c9-90c7-ca3bf792abcc)

### Steps To Reproduce

- Have a large folder with many items. In my case: on a USB HDD
- Permanently delete the folder
- Watch the progress

### Requirements

- full description should be readable (e.g. with a tooltip, dynamic width or wrap to a new line)
- "speed" should always be readable
- Number of items done should always be less than the total number of items

### Files Version

2.5.32.0

### Windows Version

10.0.22621.2506

### Log File

[debug.log](https://github.com/files-community/Files/files/13281350/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
Merging with #13624

**Comment by Jay-o-Way** [comment]
@0x5bfa did this fall between the cracks? Not sure your pr would fix all of this...

**Comment by 0x5bfa** [comment]
- The header isn't fully readable.

You should be able to hover and read.

- The speed isn't readable

We are going to discuss another UI for speed text.

- The items-done exceeds total-items

This is an issue with OS probably. AFAIK, powershell does have this issue.

Thank you for reporting all:)

**Comment by yaira2** [comment]
> This is an issue with OS probably. AFAIK, powershell does have this issue.

![image](https://github.com/files-community/Files/assets/39923744/78c83494-ca54-42b7-9cf8-4fdd31bf9e31)

**Comment by yaira2** [comment]
Screenshot credits go to @hez2010

**Comment by mdtauk** [comment]
> * The header isn't fully readable.
> 
> You should be able to hover and read.
> 
> * The speed isn't readable
> 
> We are going to discuss another UI for speed text.
> 
> * The items-done exceeds total-items
> 
> This is an issue with OS probably. AFAIK, powershell does have this issue.
> 
> Thank you for reporting all:)

We did change the speed text so it was entirely in the padded top section for readability, I guess it didn't make it into the PRs for v3 release

**Comment by Jay-o-Way** [comment]
FYI - I spotted this in v 2.5._something_ and now using v3.0.3.0. Switching from _number-of-items_ to _size_  helps. But the tooltip fails shortly after starting the action and the speed info is in the same place.
![image](https://github.com/files-community/Files/assets/65828559/7b01aca1-adce-4f42-8f4a-5b9db848cef7)
