### ISSUE TITLE
Add way to open system explorer

### ISSUE THREAD

**Issue by MapleRecall** [files-community/Files#13718]
### What feature or improvement do you think would benefit Files?

Occasionally some low-frequency functions require the use of the system explorer, which becomes very cumbersome when set Files as default. It would be nice to add a button or menu item to open folder in the system explorer.

### Requirements

- Add a button in the context menu or details pane to open folder in the system explorer

### Files Version

3.0.1.0

### Windows Version

10.0.22631.2506

**Comment by Josh65-2201** [comment]
Thanks for the feedback. You already can by typing explorer before the path in the path bar. `explorer C:\`
