### ISSUE TITLE
Some pictures are blurry

### ISSUE THREAD

**Issue by Quietbeat** [files-community/Files#13711]
### Description

I've noticed that two instances when a picture(s) would appear initially blurry and only resolve when navigating away then back.

Instance 1. I have a folder containing additional folders of pictures; the number of pictures vary from 10 to 50. When I initially opened a sub-folder, only the first half of the pictures showed clearly and the rest were blurry.

Instance 2: When the layout was Large Icons, a folder with a picture and folders showed the picture as blurry.

### Steps To Reproduce

1. Open a folder with multiple pictures where the layout is Small/Medium/Large icons.
2. Examine the pictures.

### Requirements

- e.g. Fix crash that occurs when...
All of the pictures should be clearly shown and not blurry.

### Files Version

3.0.0.0

### Windows Version

10.0.22621.2506

### Log File

[debug.log](https://github.com/files-community/Files/files/13283781/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, we're tracking this request in #10067.

**Comment by yaira2** [comment]
Can you confirm if this is only an issue in OneDrive?

**Comment by Hyrules** [comment]
I have this issue as well i'm using Files 3.0.15.0 and the files are not on onedrive but a secondary nvme drive. Here is a screenshot of the issue : 
![image](https://github.com/files-community/Files/assets/3161577/f7f8377b-fcd0-4dc7-8519-dbc03681c116)

To reproduce I just have to open a folder with images for the first time and then some of the thumbnails are blurry and not full resolution. If I press F5 to refresh the screen the thumbnails then load properly. This does not happen in a folder where the thumbnails has already been loaded.
