### ISSUE TITLE
Bug: App loads slowly if opened from the browser

### ISSUE THREAD

**Issue by alfio95it** [files-community/Files#13710]
### Description

files is very slow to open the folder of the downloaded file, the first click loads immediately, if I try to do a second one later it takes a long time
![Screenshot 2023-11-06 210421](https://github.com/files-community/Files/assets/150169228/fad5a932-0cfc-48c8-9b6c-e1f0cdf01692)

### Steps To Reproduce

1. open download on browser 
2. click show in the folder (any downloaded file) 
3. files open the folder
4. Once the files have opened, close them and click show in the folder again (there will be much more than the first click)

### Requirements

the first click loads immediately, if I try to do a second one later it takes a long time

### Files Version

3.0.1.0

### Windows Version

10.0.22631.2506

### Log File

[debug.log](https://github.com/files-community/Files/files/13283338/debug.log)

**Comment by yaira2** [comment]
Which browser are you using?

**Comment by alfio95it** [comment]
brave

**Comment by yaira2** [comment]
Can you reproduce this issue with Edge?

**Comment by alfio95it** [comment]
same problem

**Comment by yaira2** [comment]
@alfio95it can you check if this is fixed in v3.0.5?

**Comment by yaira2** [comment]
@alfio95it can you confirm if it's opening a tab in the existing instance?

**Comment by alfio95it** [comment]
In what sense? sorry for my ignorance :(

**Comment by yaira2** [comment]
@alfio95it is it opening a new instance of Files or is it adding a tab to the existing instance?

**Comment by alfio95it** [comment]
with files already open it adds a new tab, but even with files open the second click always takes longer to load

**Comment by alfio95it** [comment]
I don't know whether to open another issue but, I discovered that a problem similar to this of the second click when you try to open file path from a shortcut on the desktop the context menu does not open immediately
![Screenshot 2023-11-20 163349](https://github.com/files-community/Files/assets/150169228/f1814f5d-4cd2-4c8d-acab-137510132f77)

**Comment by meemore** [comment]
windows defender?  I have had issues, with files on my daughter PC like this, and it was windows defender.

**Comment by yaira2** [comment]
@alfio95it is this still an issue in v3.1 when the option to keep Files in the background is enabled?
