### ISSUE TITLE
How can i keep the column on the left panel always expanded?

### ISSUE THREAD

**Issue by ipanko** [files-community/Files#13713]
### What feature or improvement do you think would benefit Files?

After this update, the column here keep hided and this is just ridiculous, i wish this  can keep always expanded like the previous versions
![Screenshot_303](https://github.com/files-community/Files/assets/73260893/102e8b78-c243-4ad4-bc95-c6391071200b)

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.0.1.0

### Windows Version

10.0.22631.2506

**Comment by yaira2** [comment]
You can expand the sidebar by resizing the column or alternatively by double clicking the border.

**Comment by ipanko** [comment]
> You can expand the sidebar by resizing the column or alternatively, by double clicking the border.

Yeah, i've noticed it now, my mistake srry
