### ISSUE TITLE
Search when type

### ISSUE THREAD

**Issue by Fefedu973** [files-community/Files#13717]
### What feature or improvement do you think would benefit Files?

Like in windows it would we nice to have the option to show search results at the same time i type in the search box

### Requirements

- This will acomplish faster search

### Files Version

3.0.1.0

### Windows Version

25987.1000

**Comment by yaira2** [comment]
Files has this as well, can you confirm if it's working?
![image](https://github.com/files-community/Files/assets/39923744/e6ca7385-936d-4721-af70-edf4b4a9f67e)

**Comment by Fefedu973** [comment]
![image](https://github.com/files-community/Files/assets/80718477/dd71b57f-3fe9-468e-a458-88bb343c2433)

**Comment by Fefedu973** [comment]
Oh ! it is working but it has a very long latence (more than 1 minute)

**Comment by Fefedu973** [comment]
is it planned to add search settings like this and it would be really nice to be able to search using everything (i dont know if they have an api) this would be game changer and they have way better search than windows. 
![image](https://github.com/files-community/Files/assets/80718477/b5f31ef8-c86b-465c-a788-c2b67a5bc898)

**Comment by Josh65-2201** [comment]
A UI filter is planned https://github.com/files-community/Files/issues/4813

**Comment by Fefedu973** [comment]
nice

**Comment by yaira2** [comment]
> Oh ! it is working but it has a very long latence (more than 1 minute)

This will get faster as we continue to improve search.
