### ISSUE TITLE
Bug: Missing Favorites/Files Crashing when adding Favorites

### ISSUE THREAD

**Issue by shadeslayur** [files-community/Files#13716]
### Description

When updating to the new version of Files (v.3.0) the Favorites list in the left hand pane is missing all previous favorites. Attempting to add a new favorited item causes Files to freeze completely. Only way to get out of Files is through Task Manager ending the program.

### Steps To Reproduce

1. Update to Files v3.0
2. Look for Favorites in left task bar <should be missing previously added favorites>
3. Right click on a file and hit "Add to Favorites"
4. Files crashes.

### Requirements

Fix crash that occurs when adding new Favorite item.

### Files Version

3.0.1.0

### Windows Version

10.0.22635 Build 22635

### Log File

[debug.log](https://github.com/files-community/Files/files/13284454/debug.log)

**Comment by yaira2** [comment]
Thank you for the report

**Comment by Josh65-2201** [comment]
Can you try clearing your recent folder by going to Windows File Explorer > `...` menu > Options > Clear File Explorer history and restart Files

**Comment by shadeslayur** [comment]
> Can you try clearing your recent folder by going to Windows File Explorer > `...` menu > Options > Clear File Explorer history and restart Files

Did this and the issue remains.

**Comment by shadeslayur** [comment]
Update! Restarted explorer.exe from the Task Manager and all my favorites reappeared in Files and can now pin new Favorites.

**Comment by shadeslayur** [comment]
![image](https://github.com/files-community/Files/assets/113036686/2e4623dc-df8d-4762-9482-5fcd0f7ecea1)

**Comment by yaira2** [comment]
Sounds like this was a temporary issue with File Explorer (favorites are handled through File Explorer), glad it's resolved!
