### ISSUE TITLE
More 'compact' Details view

### ISSUE THREAD

**Issue by AnthonyDimovski** [files-community/Files#13729]
### What feature or improvement do you think would benefit Files?

Is there any way we could have a more 'compact' view of the details view? Similiar to the details view in the legacy file explorer
![File_1](https://github.com/files-community/Files/assets/67245854/342e9274-48f3-4f60-8354-1ec05e405107)
![File_2](https://github.com/files-community/Files/assets/67245854/aa764c57-cb40-4f7a-8e71-50b26aea5fbe)

### Requirements

- Add an additional option in the settings menu

### Files Version

3.0.1.0

### Windows Version

Windows 11 Pro 22631.2506

**Comment by yaira2** [comment]
@AnthonyDimovski thank you for the question, you can enable compact spacing from settings > appearance > use compact spacing.
