### ISSUE TITLE
Win+E open new instance of Files instead new tab

### ISSUE THREAD

**Issue by PhunkyBob** [files-community/Files#13724]
### Description

_Files_ is my default file browser.
When I already have an open instance of _Files_ and I press `Win+E`, I expect to have my instance that pops up with a new tab. 
Instead, it opens a new instance of _Files_. 

### Steps To Reproduce

1. Set _Files_ as default file browser (experimental).
2. Press `Win+E`. 
-> An instance of _Files_ pops up.
3. Press `Win+E`. 
-> Another instance of _Files_ pops up.
-> I have 2 _Files_ windows in my taskbar and in my task manager. 

### Requirements

I expect the existing instance of _Files_ to be used to open a new tab. 

When I read this feature request 
https://github.com/files-community/Files/issues/10844
I understand it should be the expected behavior. 

Did I miss a parameter?

### Files Version

3.0.1.0

### Windows Version

Windows 10 22H2 build 19045.3636

### Log File

[debug.log](https://github.com/files-community/Files/files/13289525/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, this is the expected behavior but we're planning to add an option to open in the existing window instead. #9709
