### ISSUE TITLE
The app is laggy (constant low frame rate) dosen't happends with file v2

### ISSUE THREAD

**Issue by Fefedu973** [files-community/Files#13721]
### Description

The app is bellow 30fps and feels laggy (i have 165hz monitor i feel it). V2 didn't have this issue. I'm in windows canary and i have the same issue on all NON SYYSTEM APPS (settings, paint, notepa, ms store not affected) apps that have the new fluent ui like power toys, in the new home section of the file explorer, in phone link apps, in firecube fluent app if you know what is it. Maybe this is due yo the type of app ? (uwp vs win32 idk because files v2 didn't have this issue) and this is maybe a windows bug because sometimes after an update or a restart this bug sometimes diseapear for a little time until next restart or i dont know. (din't test with files but worked with ones i mentioned to have same issue earlier)

### Steps To Reproduce

1. use file v3
2. see that it is laggy (low fps)

### Requirements

- everytime everywhere

### Files Version

3.0.1.0

### Windows Version

25987.1000

### Log File

[debug.log](https://github.com/files-community/Files/files/13288513/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report. Files wasn't a UWP on v2 either. Since you are having this issue with many other programs it likely due to a bug in Windows canary and/or WinUI and not something Files can fix.

**Comment by Fefedu973** [comment]
Thanks but have you changed anything under the hood because this issue affects all affected apps at the same time and before v3, v2 didn't have this issue but the app mentioned had it. after the update it has the issue

**Comment by yaira2** [comment]
Thank you for the feedback, the only change that I can think of was updating the WinAppSdk dependency. Can you report this on the WinUI repo so that they are aware of the issue?
