### ISSUE TITLE
Add options for what to do when pressing Win+E and Files is already running

### ISSUE THREAD

**Issue by Quietbeat** [files-community/Files#13727]
### What feature or improvement do you think would benefit Files?

If Files is running (open or minimized), and I press Win+E, I'd like Files to be displayed on top of any windows.

### Requirements

Currently pressing Win+E creates another instance of Files so if this is a feature you want to keep, you should add a new option to the Settings and let the user decide what they want to happen.

### Files Version

3.0

### Windows Version

22H2 Build 22621.2506

**Comment by yaira2** [comment]
Thank you for the feedback, this is on our todo list and being tracked in #9709.
