### ISSUE TITLE
Details Layout Columns refresh issue

### ISSUE THREAD

**Issue by Quietbeat** [files-community/Files#13728]
### What feature or improvement do you think would benefit Files?

I have Files open and I'm looking at a folder. When I open Details Layout Columns and turn off 'Tag column', I don't see the 'Tag' column removed nor is it removed when I close the Settings dialog.

### Requirements

When the user makes changes to the Details Layout Columns, the changes should be applied immediately to all open Files.

### Files Version

3.0

### Windows Version

22H2 Build 22621.2506

**Comment by yaira2** [comment]
Thanks for the report, can you open a new issue using the bug report template?
