### ISSUE TITLE
Bug: Stuck on loading when starting on Windows logon

### ISSUE THREAD

**Issue by Yabino** [files-community/Files#13720]
### Description

When Files is configured to launch on Windows startup, it fails. It stays stuck on the loading page.

### Steps To Reproduce

Activate launch on Windows startup.

### Requirements

Fix the bug.

### Files Version

3.0.1.0

### Windows Version

Windows 11 Pro 23H2 22635.2700

### Log File

[debug.log](https://github.com/files-community/Files/files/13287860/debug.log)

**Comment by yaira2** [comment]
Is this only an issue on Windows startup?

**Comment by Yabino** [comment]
Yes, only on Windows startup.

Il mar 7 nov 2023, 22:06 Yair ***@***.***> ha scritto:

**Comment by yaira2** [comment]
Thank you for the report

**Comment by Yabino** [comment]
Sorry but the bug is still active here on my end.

[https://drive.google.com/file/d/1NAHuQ2D3KT1qu4l7U3CoPsO6y6TS_kyn/view?usp=sharing](url)

**Comment by Josh65-2201** [comment]
The fix hasn't been released as an update
