### ISSUE TITLE
Feature: Provide better separation between multiple shortcuts in the command palette

### ISSUE THREAD

**Issue by dracp** [files-community/Files#13737]
### What feature or improvement do you think would benefit Files?

Separation between keyboard shortcuts

I understand that the small separation between key combinations can be misleading.

### Requirements

The different possible key combinations for the same action should be more clearly distinguished.

### Files Version

3.0.1.0

### Windows Version

10.0.22621.2506

### Comments

![231107 Files 3 0 1 0_Separar atajos de teclado](https://github.com/files-community/Files/assets/102802425/39f1c5f0-29ce-4715-994c-b7589c035f4a)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, I've added this to the project board.
