### ISSUE TITLE
Drag and drop

### ISSUE THREAD

**Issue by ramsdu95** [files-community/Files#13735]
### What feature or improvement do you think would benefit Files?

Drag and drop no longer works since update 3.0.1.0

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.0.1.0

### Windows Version

10.0.22621.2506

**Comment by Josh65-2201** [comment]
If you are not running Files as admin (It's disabled to avoid a crash because of a Windows issue) please open a bug report with what isn't working with drag and drop.

**Comment by yaira2** [comment]
@ramsdu95 what happens when you try to drag & drop?

**Comment by ramsdu95** [comment]
I can't take the file and drag it nothing happens

**Comment by yaira2** [comment]
@ramsdu95 can you share a screen recording of the issue? Is the app running as admin?

**Comment by ramsdu95** [comment]
Yes I am admin

**Comment by yaira2** [comment]
Drag & drop isn't supported on admin (it's a platform issue). It should however work if you run the app without admin.

**Comment by ramsdu95** [comment]
Uploading files_EkEgG0fK.mp4…

**Comment by ramsdu95** [comment]
How to launch run the application without administrator.

**Comment by yaira2** [comment]
It should be the default, @Josh65-2201 do you have any ideas?

**Comment by Josh65-2201** [comment]
How are you open Files?

**Comment by ramsdu95** [comment]
double click on the application

**Comment by Josh65-2201** [comment]
From where? is it a shortcut on a program or desktop

**Comment by ramsdu95** [comment]
desktop

**Comment by yaira2** [comment]
@ramsdu95 I think I've seen this happen if UAC is completely disabled on the account, can you check what your setting is?

**Comment by Josh65-2201** [comment]
You can also check the shortcut properties > Advanced > Run as administrator is off

**Comment by ramsdu95** [comment]
it still does not work

**Comment by Josh65-2201** [comment]
Is Files still running as admin?

**Comment by ramsdu95** [comment]
NO

**Comment by Josh65-2201** [comment]
What isn't working, is still not doing anything when drag or not doing the operation when you let go?

**Comment by ramsdu95** [comment]
doesn't work at all I can't take a file

**Comment by yaira2** [comment]
@ramsdu95 I think I've seen this happen if UAC is completely disabled on the account, can you check what your setting is?

**Comment by ramsdu95** [comment]
when I reinstalled files it tells me that it is running as administrator how can I deactivate the administrator?

**Comment by Josh65-2201** [comment]
Turn on User Account control and also check the shortcut properties > Advanced > Run as administrator is off

**Comment by ramsdu95** [comment]
in the files application I no longer see this option : properties > Advanced > Run as administrator is off

**Comment by yaira2** [comment]
@ramsdu95 did you enable UAC in Windows?

**Comment by ramsdu95** [comment]
Ok c'est bon, merci beaucoup pour tous est ok de mon côté

**Comment by ramsdu95** [comment]
Ok that's good, thank you very much for everything is ok on my side
