### ISSUE TITLE
ALT, CTRL, and SHIFT are not working on Create a shortcut, Copy, or Move the file/folders.

### ISSUE THREAD

**Issue by Quietbeat** [files-community/Files#13730]
### Description

When I click and drag a folder from Files to another folder or the Desktop, pressing ALT, CTRL, or Shift does not give me the options to Create a shortcut, Copy, or Move the file/folders like it does with File Explorer.

### Steps To Reproduce

1. Click and drag a file from Files to the Desktop
2. Press ALT and the option to Create a Shortcut is NOT displayed.
3. Press CTRL and the option to Copy is NOT displayed.
4. Press SHIFT and the option to Move is NOT displayed.

### Requirements

1. Press ALT and the option to Create a Shortcut is displayed.
2. Press CTRL and the option to Copy is displayed.
3. Press SHIFT and the option to Move is displayed.

### Files Version

3.0

### Windows Version

22H2 Build 22621.2506

### Log File

[debug.log](https://github.com/files-community/Files/files/13291500/debug.log)

**Comment by yaira2** [comment]
Is this the same as #10469?

**Comment by gave92** [comment]
Shouldn't be, this is about left click drag + modifier, the other about right click drag.

**Comment by gave92** [comment]
The issue is only when draghing to the desktop right? Not also when drag&drop insider Files.

**Comment by yaira2** [comment]
Isn't that what #104

**Comment by gave92** [comment]
https://github.com/files-community/Files/assets/9673091/1d9bcf39-f0c4-4f99-b824-7b161dff8d0a
