### ISSUE TITLE
Feature: Add pin to start option for shortcuts linked to an exe file

### ISSUE THREAD

**Issue by CocoTang1024** [files-community/Files#13738]
### What feature or improvement do you think would benefit Files?

都很不错，就是右键没有固定到快捷访问，我想要固定到磁贴上面

### Requirements

- Check if shortcut file is going to an exe and add pin to start as a context menu option

### Files Version

3.0.1.0

### Windows Version

10.0.19045.2965

**Comment by Josh65-2201** [comment]
Thanks for the feedback. 
- Please send your Files and Windows version from `Files settings > About > Copy button`
- What are you trying to pin?
- Where are you trying to pin to?

**Comment by CocoTang1024** [comment]
button->Application version 3.0.1.0 ||||  Windows version 10.0.19045.2965
l want to take this，Place the application I selected below
![image](https://github.com/files-community/Files/assets/75608560/6ae9975a-256e-408f-b8ec-bc77dbf6d925)
Place it on the windows tile below
![image](https://github.com/files-community/Files/assets/75608560/48ac2871-d26f-4def-b25f-8f3686effb10)
Call Pin to Start Screen in the original taskbar

**Comment by Josh65-2201** [comment]
Thanks for the clarification

**Comment by yaira2** [comment]
This option will be available in v3.2
