### ISSUE TITLE
Feature: Compact view for folder pane

### ISSUE THREAD

**Issue by Funkem** [files-community/Files#13732]
https://github.com/files-community/Files/assets/40534662/bcf18c99-e7ff-43d5-a280-686955728d5f

### What feature or improvement do you think would benefit Files?

First, Files V3 is fast enought for daily use. Thanks you your work.

1.  Drag and Drop from Outlook attachments are not possible, it shows "copy to <folder>" but after release mouse btn not happens
2.  Please extend the compact view also to the folder pane

Thank you

### Requirements

Outlook 2019 for the drop and drop option

### Files Version

3.0.1.0

### Windows Version

10.0.19045.3570

**Comment by yaira2** [comment]
We're tracking the OutLook issue in #13646

**Comment by yaira2** [comment]
> Please extend the compact view also to the folder pane

Can you clarify what you mean by folder pane?

**Comment by Funkem** [comment]
I mean the Favorites on the left side.  Sorry for the mistake.

**Comment by Josh65-2201** [comment]
The favorites section on the sidebar is already in a compact view like the option does.

**Comment by yaira2** [comment]
Support for adjusting the sidebar density is on the todo list.
