### ISSUE TITLE
Tab Workspaces/Presets

### ISSUE THREAD

**Issue by klementineQt** [files-community/Files#13736]
### What feature or improvement do you think would benefit Files?

I believe adding some method of achieving workspace functionality (i.e. having the ability to invoke a certain set of tabs with a single launch parameter or by storing presets that can be saved and loaded) would hugely improve workflow for Files.

As of right now, I'm achieving this behavior with a lot of extra scripting and artificial waiting to ensure correct tab order (this is very important to me, and may be to others as well to ensure familiarity with the setup).

The functionality would essentially be an extension/improvement of the existing "Open a specific page or pages" startup setting allowing for different options based on either a launch parameter or a UI-integrated system that can save and load tabs and their order to a file (whether this is in additional individual files or appended to the existing config is up to whatever is deemed the optimal implementation).

### Requirements

- An in-UI way of saving/loading tab lists (and their specific orders) for ease and user-friendliness, ultimately to optimize workflows
- (Optionally) Ability to append multiple locations to open in-order when opened from the command line
- If tab lists are saved to individual files, the ability to handle the files (to open them if invoked from another instance/app i.e. the Open With option in the context menu)

### Files Version

3.0.1.0

### Windows Version

10.0.22621.2506

**Comment by klementineQt** [comment]
I suppose this has already been requested in #11900

**Comment by yaira2** [comment]
@klementineQt yeah, sems to be the same request.
