### ISSUE TITLE
Bug: Unable to set Files as default file manager on standard/non-administrator user

### ISSUE THREAD

**Issue by Ni7r4m** [files-community/Files#13734]
### Description

If you install Files on 2 (or possibly multiple) users, the option "Set Files as the default file manager" does not work and always set itself to off in the non-administrator account. The problem occurs regardless of the administrator account turning that option on or off.

### Steps To Reproduce

1. On both administrator and standard user, install the Files app
2. On the standard user, toggle on the "Set Files as the default file manager" option
3. Allow the UAC control
4. The option sets itself to off

### Requirements

Files should be able to be set as the default file manager for standard user and possibly multiple users.

### Files Version

3.0.1.0

### Windows Version

10.0.19044.3570

### Log File

[debug.log](https://github.com/files-community/Files/files/13294978/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
I think this might just be one of the limitations with the way this works. Fyi @gave92

**Comment by hbinhng** [comment]
@yaira2 I can see that you use a static .reg file to register Files and in that .ref file. I think, I just think, I haven't tried yet, you can create a template for reg file to use HKEY_USERS\<UID> instead of HKEY_CURRENT_USER. Current approach using HKEY_CURRENT_USER when execute in Admin session sets default shell of Admin only.

**Comment by yaira2** [comment]
Let me know if that works, we went through several iterations but it's been a while since we set this up and I don't recall if we had that at one point.

**Comment by Ni7r4m** [comment]
Just tried to use the SetFilesAsDefault.reg out of curiosity on the standard user, and while it does kinda help replace the default Windows Explorer to something else, trying to open explorer via Win+E is a problem, and the old explorer won't run until I run the UnSetFilesAsDefault.reg to revert everything. Maybe the feature can work in a way where it modifies the current user without asking for UAC? 
![image](https://github.com/files-community/Files/assets/82970389/f367e91d-9a37-409d-bfbb-9517c21ec4a1)

**Comment by Josh65-2201** [comment]
This issue seems it's talking about not showing the UAC prompt. It's needs admin to move the needed files and apply the registry change and it should be asking for UAC where you can enter the admin account information. You should not be applying the reg file yourself as it wouldn't work.

**Comment by yaira2** [comment]
@Ni7r4m thank you for your feedback. Currently, the functionality you’re requesting requires an official option in Windows to change the default file manager.

I know this isn't the same, but you can pin Files to the taskbar and quickly launch it by pressing `Win` + `1` (or the number key that matches its position on your taskbar).
