### ISSUE TITLE
Feature: Refresh Details Layout Columns after changing setting

### ISSUE THREAD

**Issue by Quietbeat** [files-community/Files#13747]
### What feature or improvement do you think would benefit Files?

I originally raised defect #13741 so here's the requested Feature Request.

By default, the 'Tag' column is shown and when turning off 'Tag column', I don't see the 'Tag' column removed nor is it removed when I close the Settings dialog.

![image](https://github.com/files-community/Files/assets/57841662/52f12d2b-6003-4490-9c90-72de80a010f9)

### Requirements

1. Open Files
2. Open Details Layout Columns
3. Turn off 'Tag' column

### Files Version

3.0

### Windows Version

22H2 Build 22621.2506

**Comment by yaira2** [comment]
Thanks for the feedback

**Comment by ferrariofilippo** [comment]
I'm not sure how this settings is supposed to work. 
Turning off a column should hide it in ALL the folders, overriding `Individual Folder Preferences`? Should it do so only if `Sync layout ...` is enabled?
If a column is turned off from the settings, should the user be able to toggle it using the context flyout?

**Comment by Josh65-2201** [comment]
The settings are for default columns, if the sync toggle is on then it should apply to all like now and refresh the open tabs, if not do nothing different then right now. It shouldn't change anything with the context menu toggles.

**Comment by yaira2** [comment]
> if the sync toggle is on then it should apply to all like now and refresh the open tabs

This feature isn't limited to when the 'sync folder options' setting is enabled. It should also apply to any tab where the folder preferences weren't overridden.

**Comment by ferrariofilippo** [comment]
> This feature isn't limited to when the 'sync folder options' setting is enabled. It should also apply to any tab where the folder preferences weren't overridden.

The PR I opened should already support this

**Comment by yaira2** [comment]
@Quietbeat this change will be included in the next update.
