### ISSUE TITLE
The Folder/File icons under New are not the same as other similar icons

### ISSUE THREAD

**Issue by Quietbeat** [files-community/Files#13744]
### Description

When I click the New dropdown, I noticed that the Folder icon doesn't have the same icon used for other folders such as My Documents:

![image](https://github.com/files-community/Files/assets/57841662/e1c1b822-62e8-4229-b18a-6aa6bf59f01a)

The File icon under new  is also just an outline but I feel like it too should should be different.

### Steps To Reproduce

1. Open Files
2. Click on the New dropdown
3. Examine the Folder and File icons

### Requirements

The Folder icon doesn't have the same icon used for other folders such as My Documents

### Files Version

3.0

### Windows Version

22H2 Build 22621.2506

### Log File

[debug.log](https://github.com/files-community/Files/files/13299084/debug.log)

**Comment by yaira2** [comment]
Thanks for the feedback, this is by design. The sidebar items are displaying the folder thumbnail whereas the new item menu shows a generic folder icon.
