### ISSUE TITLE
Details Layout Columns refresh issue

### ISSUE THREAD

**Issue by Quietbeat** [files-community/Files#13741]
### Description

By default, the 'Tag' column is shown and when turning off 'Tag column', I don't see the 'Tag' column removed nor is it removed when I close the Settings dialog.

### Steps To Reproduce

1. Open Files
2. Open Details Layout Columns
3. Turn off 'Tag' column

### Requirements

When the user makes changes to the Details Layout Columns, the changes should be applied immediately to all open Files.

### Files Version

3.0

### Windows Version

22H2 Build 22621.2506

### Log File

[debug.log](https://github.com/files-community/Files/files/13298906/debug.log)

**Comment by yaira2** [comment]
Can you toggle "sync folder settings" on & off to reset existing preferences, and then turn off the tag column?
![image](https://github.com/files-community/Files/assets/39923744/0762934a-dee3-492f-9747-f551182725e7)

**Comment by yaira2** [comment]
Can you send a screenshot of the configuration? You might need to renavigate to the directory for the changes to take effect.

**Comment by yaira2** [comment]
We actually have a todo for this in the code
![image](https://github.com/files-community/Files/assets/39923744/f1265f78-693b-42d5-b01f-6e72f2790b9f)

**Comment by yaira2** [comment]
Can you open a feature request for this?
