### ISSUE TITLE
Can't move/copy Favorite folders by drag n drop

### ISSUE THREAD

**Issue by Quietbeat** [files-community/Files#13745]
### Description

In File Explorer, I can Drag n Drop a favorite folder into a new position (rearrange my favorites) or into another folder. Pressing ALT gives me the option to create a link. These options are not available in Files.

### Steps To Reproduce

1. Click on a Favorite folder and drag it between another favorite to rearrange it.
2. Click on a Favorite folder and drag it over another Favorite folder to copy it into another folder.
3. Click on a Favorite folder and drag it over another Favorite folder then press ALT to create a link into another folder.

### Requirements

The user should be able to drag n drop favorite folders.

### Files Version

3.0

### Windows Version

22H2 Build 22621.2506

### Log File

[debug.log](https://github.com/files-community/Files/files/13299169/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, you can reorder favorites by right clicking them.

**Comment by yaira2** [comment]
Agreed, it's something we'd like to support but there are some performance issues so we have to use the dialog for now.
