### ISSUE TITLE
Columns are not movable

### ISSUE THREAD

**Issue by Quietbeat** [files-community/Files#13742]
### Description

I can not rearrange the columns, i.e., I can't move Date Created before Date Modified. 

### Steps To Reproduce

1. Open Files
2. Click on a column like Date Created and try to move it to another position.

### Requirements

The user should be able to rearrange the columns.

### Files Version

3.0

### Windows Version

22H2 Build 22621.2506

### Log File

[debug.log](https://github.com/files-community/Files/files/13298994/debug.log)

**Comment by yaira2** [comment]
Thanks for the feedback, we're tracking this in #8385
