### ISSUE TITLE
Checking for Updates

### ISSUE THREAD

**Issue by Quietbeat** [files-community/Files#13746]
### Description

In most apps, they show the current version, when it was last updated, and a button labeled "Check for updates" but I only see the current version...I'd like to see the aforementioned items.

I'd also like to know if your app automatically checks for updates.

![image](https://github.com/files-community/Files/assets/57841662/ccd6f61d-bcbe-4326-b43a-67183c65a71a)

### Steps To Reproduce

1. Go to Settings - About

### Requirements

Files needs to show:

- When it was last updated
- A button labeled "Check for updates"

### Files Version

3.0

### Windows Version

22H2 Build 22621.2506

### Log File

[debug.log](https://github.com/files-community/Files/files/13299350/debug.log)

**Comment by yaira2** [comment]
Thank you for the feedback, Files automatically checks for updates when the app is started and will display an icon on the toolbar if an update is available.
