### ISSUE TITLE
Button "Open in command prompt" when right click the folder

### ISSUE THREAD

**Issue by blueskin8** [files-community/Files#13753]
### What feature or improvement do you think would benefit Files?

A simple feature very useful for developers.
Just add a button, when we right click on the folder, to open it in terminal (command prompt) like in the original Windows File Explorer.

### Requirements

Add the button to open the current folder in command prompt

### Files Version

3.0.1.0

### Windows Version

10.0.22621.2361

### Comments

![screenshot](https://github.com/files-community/Files/assets/96547492/9b2d85df-db98-4ef7-8c16-f9d466c90a43)
(I use a french windows because i'm french ;) )

**Comment by Josh65-2201** [comment]
Thanks for the feedback, this is an issue with Windows terminal using the new method for adding context menu items. Support in Files is being tracked here #8251. You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
There is also a keyboard shortcut ctrl + `.
