### ISSUE TITLE
Files doesn't open properly after restarting my PC

### ISSUE THREAD

**Issue by Quietbeat** [files-community/Files#13750]
### Description

I had Files open and restarted my PC. When Files was displayed, it never showed the previously opened tab/folder but instead continuously showed a progress indicator. I've seen this issue 3 times.

### Steps To Reproduce

1. Open Files with one or more tabs
2. Restart the PC

### Requirements

Files should display the previously opened tab(s).

### Files Version

3.0.0.0

### Windows Version

10.0.22631.2506

### Log File

[debug.log](https://github.com/files-community/Files/files/13300646/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #13720. You can check there or click subscribe in the right sidebar for updates.
