### ISSUE TITLE
Changes to the Layout aren't displayed immediately and are not saved

### ISSUE THREAD

**Issue by Quietbeat** [files-community/Files#13759]
### Description

I've seen multiple instances where I'm customize the layout in Settings and/or per folder then later on Files reverts all layouts to the default. Similar to another bug I reported with Detail Layout Columns, changing the Layout mode doesn't change any open Files.

### Steps To Reproduce

1. Open Files
2. Change the layout and notice that the layout isn't changed dynamically...I have to navigate away then back which isn't acceptable.
3. Close then re-open Files...the last time I did this step Files reset the layout but not the second time.

### Requirements

Two things need to happen:

1. When the user changes the layout, the change should happen immediately without navigating away.
2. The user should be able to set the layout for every folder, certain folders, folder contents, etc. If I change the  layout in one folder, it effects every folder which isn't right.

### Files Version

3.0.0.0

### Windows Version

10.0.22631.2506

### Log File

[debug.log](https://github.com/files-community/Files/files/13302267/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report. If you want your settings to apply to all folders you need to turn on Files settings > Folder > Sync layouts

**Comment by yaira2** [comment]
@Quietbeat
