### ISSUE TITLE
Files crashes when drag-and-dropping a file

### ISSUE THREAD

**Issue by PatrickECleary** [files-community/Files#13754]
### Description

 Files immediately crashes when attempting to drag-and-drop a file.

### Steps To Reproduce

1. Open Files
2. Click-drag a file
3. Files crashes.

### Requirements

Expected behavior:
Files does not crash when click-dragging a file, whether to drag-and-drop within Files or to another program.

### Files Version

3.0.1.0

### Windows Version

10.0.22623.1245

### Log File

[debug.log](https://github.com/files-community/Files/files/13301460/debug.log)

**Comment by gave92** [comment]
You're launching Files as administrator right?

**Comment by PatrickECleary** [comment]
Nope. I'm launching it as a user.

**Comment by PatrickECleary** [comment]
I just tried launching it as administrator and click-dragging again. It crashed in the same way as before.

FWIW - The crash occurs with the view set to Details, Columns, or Tiles.

And when Files is run as admin - or for that matter, 90% of the time it's run normally - the app does not respond to keyboard shortcuts sent from AutoHotkey. As admin, this is expected (but not desired). But as user, it is unexpected and sporadic.

That said, I'm happy to log the keyboard shortcut issue separately :)

**Comment by yaira2** [comment]
@PatrickECleary how are you launching Files? Can you also check the trust level of the Files process via Process Explorer?

**Comment by gave92** [comment]
Which is in any case strange since we disabled drag&drop when Files is running as admin.

**Comment by yaira2** [comment]
https://github.com/files-community/Files/pull/13134#discussion_r1381765871

**Comment by PatrickECleary** [comment]
> @PatrickECleary how are you launching Files? Can you also check the trust level of the Files process via Process Explorer?

I normally launch it either via shortcut pinned to the taskbar, or via an AutoHotkey script that launches `files.exe` from the system PATH.

I'm new to Process Explorer. How do I find the trust level of a process?

**Comment by PatrickECleary** [comment]
Strangely enough, this issue appears to be sporadic. Files now launches & behaves normally. Drag-and-drop works as expected, and (crucially for me) it is receiving keystrokes sent from AutoHotkey (AHK). I did not reboot my computer or close/reopen any other processes.

**Comment by yaira2** [comment]
Related to #13394

**Comment by yaira2** [comment]
@PatrickECleary https://geek-university.com/view-integrity-levels/

**Comment by PatrickECleary** [comment]
> @PatrickECleary https://geek-university.com/view-integrity-levels/

Thanks for the link @yaira2 👍 

Right now Files is running with Medium integrity & is behaving normally. If/when it starts to misbehave again, I'll check the integrity level and get back to you.

**Comment by yaira2** [comment]
@PatrickECleary thanks! If it crashes again please let us know, otherwise we'll continue tracking the issue in #https://github.com/files-community/Files/issues/13394.
