### ISSUE TITLE
It takes two clicks to open the log location

### ISSUE THREAD

**Issue by Quietbeat** [files-community/Files#13751]
### Description

The first time Files is opened and I click on 'Open log location', it looks like the main window "flashes" but nothing happens. Clicking the same button again opens the folder to the log. I've seen this issue multiple times.

### Steps To Reproduce

1. Open Files for the first time
2. Click on Open log location (nothing happens)
3. Click on Open log location 

### Requirements

The log location should be shown the first time the button is clicked.

### Files Version

3.0

### Windows Version

22H2 Build 22621.2506

### Log File

[debug.log](https://github.com/files-community/Files/files/13300669/debug.log)

**Comment by yaira2** [comment]
Can you share a screen recording?
