### ISSUE TITLE
Strange white bar when maximizing files window on certain monitor(s)

### ISSUE THREAD

**Issue by JohRest** [files-community/Files#13763]
### Description

I've discovered that on my Dell E2011H (1600x900 native) monitor when in dark mode I do see a slim white bar at the top of the window when I maximize the window on that monitor. I do think it is the window border, which in windows is colored differently than the rest of the title bar. To make it even harder I do not see the same behavior on my main monitor. I think it's a minor thing, so yes, the priority of that is exceptionally low. But I wanted to file the issue as files is a great tool. It has replaced the windows inbox file explorer on all my windows machines :-)
![image](https://github.com/files-community/Files/assets/2835797/fdf2f048-e511-4fa9-994b-dbaf4ad4b729)

### Steps To Reproduce

switch to dark mode
bring files to specific monitor
expand it to fill the whole screen
a small white area appears on the very top

### Requirements

the expected behavior would be that the white area would be colored the same way as the rest of the title bar when the application windows goes full screen.

### Files Version

3.0.1.0

### Windows Version

10.0.22631.2506

### Log File

[debug.log](https://github.com/files-community/Files/files/13305068/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, this is a WinUI issue and Files can not fix it.

**Comment by yaira2** [comment]
This is a bit of an odd issue, but I agree with @Josh65-2201 that it looks like a WinUI issue. Can you report this on the WinUI repo?

**Comment by JohRest** [comment]
Thanks for looking into it!

**Comment by JohRest** [comment]
hm.. what is the correct repo url? then I'll do my best...

**Comment by yaira2** [comment]
https://github.com/microsoft/microsoft-ui-xaml

**Comment by JohRest** [comment]
Done. 


Issue is: https://github.com/microsoft/microsoft-ui-xaml/issues/9067

Thanks!

**Comment by yaira2** [comment]
@JohRest Microsoft just released a patch for this issue, so you can expect the fix to show up in one of the next updates to Files.
