### ISSUE TITLE
Please, leave a keyboard shortcut for creating a new item!!

### ISSUE THREAD

**Issue by RickyZhu-420** [files-community/Files#13760]
### What feature or improvement do you think would benefit Files?

One reason I like your Files app is that Ctrl+Shift+N shortcut can not only create a folder, but also different types of files, which is much better than Explorer. Creating an item without touching mouse is superb!
However, the latest V3 update changed the function of this, and the process of creating an item via Ctrl+Shift+N doesn't work, it just creates a folder. To create an item without a mouse, now we have to use Ctrl+Shift+P and search the prompt.(p.s. Command Palette is a great improvement indeed)
As always, I'd love to use Files, but I don't think that replacing the old one is a good idea.

### Requirements

Restore the Ctrl+Shift+N menu to its original functionality.
Alternatively, create a separate shortcut key for the "Create new item" menu.

### Files Version

3.0.2.0

### Windows Version

10.0.22621.2506

**Comment by yaira2** [comment]
Thank you for your feedback, the next update will use the `ctrl + shift + i` shortcut for creating new items.

**Comment by RickyZhu-420** [comment]
Thanks, you're making great things happen!
