### ISSUE TITLE
Copy paste box

### ISSUE THREAD

**Issue by meemore** [files-community/Files#13764]
### What feature or improvement do you think would benefit Files?

I mentioned this before, I hope this gains attention, all file managers have the same problem.  Its called copy paste, then hunting down the destination folder you want to paste to or move too.   There is only way to solve this problem.
![Screenshot_19](https://github.com/files-community/Files/assets/124497263/03db94fe-f952-43e4-b1b8-17a541df9723)

### Requirements

speed

### Files Version

3.0.2.0

### Windows Version

10.0.22621.2506

**Comment by yaira2** [comment]
@meemore thank you for your feedback, can you confirm if this is the same as #12490?
