### ISSUE TITLE
installation error "Class not registered"

### ISSUE THREAD

**Issue by mbahkantong7575** [files-community/Files#13767]
### Description

error "Class not registered" when install files v3

### Steps To Reproduce

install, then error

### Requirements

- e.g. Fix crash that occurs when...
error "Class not registered" when install files v3

### Files Version

3.0.2.0

### Windows Version

Windows 10 Pro Version	22H2 Installed on	‎5/‎3/‎2023 OS build	19045.2364 Experience	Windows Feature Experience Pack 120.2212.4190.0

### Log File

none

**Comment by Josh65-2201** [comment]
Thanks for the report. Have you install a unofficial/modified (like Disabled windows update, removed the Microsoft store, used a debloat program/script) version of Windows?

**Comment by mbahkantong7575** [comment]
Yes, i used unofficial Modified windows 10. Is that the problem?

Pada Kam, 9 Nov 2023 19.46, Josh65-2201 ***@***.***> menulis:

**Comment by Josh65-2201** [comment]
Yes, they aren't support as the remove thing that shouldn't be remove which is why you can not install Files. You only option will be to install and official version from Microsoft site.
