### ISSUE TITLE
Mouse scroll wheel support for tabs

### ISSUE THREAD

**Issue by meemore** [files-community/Files#13765]
### What feature or improvement do you think would benefit Files?

Mouse scroll wheel support for tabs  Hover the mouse over the tabs area, and roll the mouse wheel left or right to switch tabs fast instead of moving the mouse
![Screenshot_20](https://github.com/files-community/Files/assets/124497263/0a6d8c86-3a4b-484a-9856-6e375c6556b1)

### Requirements

speed

### Files Version

3.0.2.0

### Windows Version

10.0.22621.2506

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with https://github.com/files-community/Files/issues/13550. You can check there or click subscribe in the right sidebar for updates
