### ISSUE TITLE
Copy & Paste

### ISSUE THREAD

**Issue by thisisreallychris** [files-community/Files#13779]
### Description

For some reason I can't copy and paste after installing this?

### Steps To Reproduce

ctrl + c
ctrl + v

= nothing

### Requirements

- e.g. Fix crash that occurs when...
Help me copy and paste stuff please....

### Files Version

3.0.2.0

### Windows Version

10.0.22631.2506

### Log File

[debug.log](https://github.com/files-community/Files/files/13311089/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report
- Are you able to copy and paste in Windows File Explorer or text?
- Does restarting your system fix it?

**Comment by thisisreallychris** [comment]
Hey! All good - I restarted my system. 🖤
