### ISSUE TITLE
Bug: With 2+ tabs open and closing Files, the 1st tab's label is missing

### ISSUE THREAD

**Issue by Quietbeat** [files-community/Files#13780]
### Description

The label for the first tab is missing after closing/reopening Files. It's doesn't matter which tab has the focus when closing Files.

![image](https://github.com/files-community/Files/assets/57841662/a18f402d-e4a8-42ba-abe6-6ffc3bd38e96)

### Steps To Reproduce

1. Open Files with at least two tabs
2. Click on the 2nd tab
3. Close Files
4. Open Files

### Requirements

All tabs should display the name of the folder.

### Files Version

3.0

### Windows Version

22H2 Build 22621.2506

### Log File

[debug.log](https://github.com/files-community/Files/files/13311209/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
I can reproduce this as well

**Comment by Josh65-2201** [comment]
![image](https://github.com/files-community/Files/assets/26977075/df56da9b-9576-43dc-9a04-ebf9e2a2cfea)

This hasn't been fixed for me when using the `open a specific page or pages`
