### ISSUE TITLE
Bug: Double-click on column header to go to parent folder

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#13789]
### Description

Double-clicking on a column header in the details layout navigates the page to the parent folder as if double-clicking on an empty space.

### Steps To Reproduce

1. Double-clicking on a column header in the details layout.
2. It navigates the page to the parent folder.

### Requirements

It shouldn't navigate the page, but should switch between ascending and descending order.

### Files Version

3.0.3.0

### Windows Version

10.0.22631.2506

### Log File

n/a

**Comment by pomydoro** [comment]
Hello, I am interested in working on this issue. I am writing this comment to help prevent duplicate efforts from others.

**Comment by RieBi** [comment]
> Hello, I am interested in working on this issue. I am writing this comment to help prevent duplicate efforts from others.

I actually want to say that I started working on this issue earlier. I am writing this comment to help prevent duplicate efforts from others

**Comment by RieBi** [comment]
OK I think I fixed this issue, just need to make a pull request. Will do that in an hour or two

**Comment by pomydoro** [comment]
> I actually want to say that I started working on this issue earlier. I am writing this comment to help prevent duplicate efforts from others

Okay, nevermind, good luck with the PR

**Comment by RieBi** [comment]
> > I actually want to say that I started working on this issue earlier. I am writing this comment to help prevent duplicate efforts from others
> 
> Okay, nevermind, good luck with the PR

Ok, you  PR was faster. Should have mentioned earlier that I started working on the issue. My bad

**Comment by RieBi** [comment]
> > I actually want to say that I started working on this issue earlier. I am writing this comment to help prevent duplicate efforts from others
> 
> Okay, nevermind, good luck with the PR

Wait, actually I tested your PR and it doesn't work for me. The issue is still there

**Comment by RieBi** [comment]
OK so it's night and I will go to sleep soon so I would make my PR tomorrow. But I'm not really sure if I should do it or maybe let the @pomydoro figure it out because he was technically the first to tackle the issue and make a PR. Maybe @yaira2 could say if it's OK if I do it or I better leave the issue to @pomydoro

**Comment by RieBi** [comment]
Wait what was that PR not from @pomydoro but from @yaira2 and was the comment from @pomydoro not sarcasm? I am utterly confused right now with all of this

**Comment by yaira2** [comment]
@RieBi I stopped working on this after seeing the comment that you were.

**Comment by pomydoro** [comment]
@RieBi I didn't see your comments earlier, sorry for the confusion, now that I read my comment again, it sounds a little ambiguous, but no sarcasm was intended. And no, the PR is not mine.
