### ISSUE TITLE
Link Shell Extension replacement?

### ISSUE THREAD

**Issue by velocity7** [files-community/Files#13783]
### What feature or improvement do you think would benefit Files?

I'd like to see the same functionality from Link Shell Extension ported over to Files.
https://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html

### Requirements

- See Link Shell Extension webpage for extension, functionality, etc.

### Files Version

3.0.2.0

### Windows Version

10.0.22621.2428

**Comment by Josh65-2201** [comment]
Thanks for the feedback, is this the same as #9991?

**Comment by Cambridgeport90** [comment]
Implementing that would be cool; the easiest thing, from the context of the extension itself, sounds like it should be implemented on their side...for instance, asking which file manager are you using, Files or FileExplorer,and then the extension would be installed into either,depending on user option. That's the only thing that comes to the top of my head.

From: velocity7 ***@***.***>
Sent: Thursday, November 9, 2023 16:26
To: files-community/Files ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [files-community/Files] Link Shell Extension replacement? (Issue #13783)

What feature or improvement do you think would benefit Files?

I'd like to see the same functionality from Link Shell Extension ported over to Files.
https://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html

Requirements

  *   See Link Shell Extension webpage for extension, functionality, etc.

Files Version

3.0.2.0

Windows Version

10.0.22621.2428

Comments

No response

-

**Comment by yaira2** [comment]
If they have a shell extension, it should already be displayed in the context menu.

**Comment by velocity7** [comment]
I swore I closed this ticket because I soon found out that Link Shell Extension was already mentioned: 
https://github.com/files-community/Files/issues/13481#issue-1930765313
