### ISSUE TITLE
Focus/Activate existing tab instead of creating new one from other program.

### ISSUE THREAD

**Issue by WubTheGame** [files-community/Files#13781]
### What feature or improvement do you think would benefit Files?

If a specific directory is invoked by another program (i.e Free Download Manager, Everything, AutoHotkey) it'll be opened in a new tab instead of switching to the already existing tab if present.

Please provide a setting to change this to prefer the existing tab instead.

### Requirements

-Check the directory to open against directories already open.
-If identical to an already opened directory, switch to that tab instead.

### Files Version

3.0.2.0

### Windows Version

10.0.19045.2364

**Comment by Josh65-2201** [comment]
Thanks for the feedback, I've added this to the project board.

**Comment by yaira2** [comment]
Thanks for the feedback, we're tracking this in #9709.
