### ISSUE TITLE
Bug: The new item dialog cannot be canceled

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#13787]
### Description

When I press Ctrl+Shift+I, the new item dialog appears. But once creating a new item, this dialog cannot be canceled even if I press the Cancel button and a dialog to enter a new name will appear.

### Steps To Reproduce

1. Press Ctrl+Shift+I and create a new item.
2. Press Ctrl+Shift+I again.
3. Press Cancel on the dialog.
4. The operation is not canceled and a dialog to enter a new name appears.

### Requirements

The operation should be canceled when Cancel is pressed.

### Files Version

3.0.3.0

### Windows Version

10.0.22631.2506

### Log File

n/a

**Comment by yaira2** [comment]
Thanks for the report.

**Comment by yaira2** [comment]
I can't repro this issue

**Comment by hishitetsu** [comment]
> I can't repro this issue

I've updated the Steps To Reproduce because I've found that there are conditions under which the problem can occur.

**Comment by MrFrawsty** [comment]
I found the problem if I could be assigned to this issue so nobody else starts looking into it please :)
