### ISSUE TITLE
Sharing bug

### ISSUE THREAD

**Issue by andreibaraboi** [files-community/Files#13788]
### Description

Hi, there's a display overlapping in this "Share" file window between the label and the drop down menu.

![Screenshot 2023-11-10 064455](https://github.com/files-community/Files/assets/63355044/dad540a1-17c3-4153-a2bb-99728029446d)

### Steps To Reproduce

Select file
Click on "Share" button

### Requirements

- e.g. Fix crash that occurs when...
The labels should not be overlapped

### Files Version

3.0.3.0

### Windows Version

10.0.22000.2538

### Log File

[debug.log](https://github.com/files-community/Files/files/13316023/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report. Files uses the Windows share feature and is an issue with that. Please report it on Microsoft's Feedback hub
