### ISSUE TITLE
Files accumulates ram in the background

### ISSUE THREAD

**Issue by alfio95it** [files-community/Files#13784]
### Description

When the program is active in background mode, it accumulates RAM during its use

### Steps To Reproduce

activate background mode
use it normally or, go back and forth between quick accesses, disks etc.
from the taskmanager while you do all this you will see the RAM fill up and when closed the program remains unchanged

### Requirements

in the background it accumulates more RAM than expected (to the point of reaching 1.5GB 😅)

### Files Version

3.0.3.0

### Windows Version

10.0.22631.2506

### Log File

[debug.log](https://github.com/files-community/Files/files/13313356/debug.log)

**Comment by yaira2** [comment]
Thanks for the feedback, this is a known issue that we've been working on for a while. Initially, we weren't going to add an option to keep Files in the background for this reason, but the overwhelming feedback was to just go for it. That said, you can turn off the option from settings as a workaround. Merging with #4180

**Comment by alfio95it** [comment]
ok thank you very much, in fact I deactivated it

**Comment by yair100** [comment]
@alfio95it we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
