### ISSUE TITLE
Need option to disable (git) integration(s) completely

### ISSUE THREAD

**Issue by GameBurrow** [files-community/Files#13791]
### What feature or improvement do you think would benefit Files?

In general I think Files should allow users to enable and disable different integration. But what personally bugs me is the git integration - details view is slow even for smaller repos and other views (especially columns) gets slow with bigger repos.

Try setting default view as columns and open the files to a certain file from for example from vscode, it takes way too long to open files fully.

### Requirements

- Allow users to enable what they actually need/want
- Make details view usable, right now if you use that view and go to any git repo's, it's slow because it tries to get the commit info for each separate files
- Overall performance inpact

### Files Version

3.0.3.0

### Windows Version

10.0.22621.2506

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Performance issues are being discussed at https://github.com/files-community/Files/issues/12737. You can check there or click subscribe in the right sidebar for updates.
You can also turn off the columns by right clicking them and go under git for that content to not load.

**Comment by GameBurrow** [comment]
@Josh65-2201 
Even then I still think there should be options to disable and enable integrations completely for people who don't want them.

**Comment by yaira2** [comment]
Thank you for the feedback. Considering that the Git columns can be hidden (they are by default) and that the options on the status bar don't need to be used, we don't have plans to add this option. That said, we're aware of a performance issue and we're actively working on fixing it #12737.

**Comment by yaira2** [comment]
@GameBurrow thank you for your patience, the next release will have a fix for the performance issues. Not only that, the improvements work without disabling the git features so you'll be able to take advantage of them if you wish.
