### ISSUE TITLE
All animations inside Files app is capped at 60fps

### ISSUE THREAD

**Issue by pritster5** [files-community/Files#13790]
### Description

While the Files window can be dragged around at the same refresh rate as your monitor (e.g. 144hz), any animations inside the app run at 60fps. 

This includes animations like expanding menus and scrolling in any window within the Files app.

### Steps To Reproduce

1. Open the app on a high refresh rate display (120hz+)
2. Observe any animations that occur, and note the difference in framerate between dragging the window and scrolling inside the Files app.

### Requirements

- Allow all animations to run at up to the framerate of the display (e.g. if a monitor is 240hz, the animations in the app will run at 240fps).

### Files Version

3.0.3.0

### Windows Version

10.0.22631.2506

### Log File

[debug.log](https://github.com/files-community/Files/files/13317663/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, This is an issue with Microsoft's WinUI/WinAppSDK. Files unfortunately can not fix it.

**Comment by yaira2** [comment]
@Josh65-2201 Microsoft supposedly fixed this, has this been reported to them that it's still an issue?

**Comment by Josh65-2201** [comment]
People have comment that it hasn't been fixed on https://github.com/microsoft/microsoft-ui-xaml/issues/7373
