### ISSUE TITLE
Restore Drag & Drop in Files app

### ISSUE THREAD

**Issue by GCG1000** [files-community/Files#13799]
### What feature or improvement do you think would benefit Files?

Please restore, or implement, drag & drop feature in Files app.  Thank you.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.0.3.0

### Windows Version

10.0.22631.2506

**Comment by yaira2** [comment]
Drag and drop is already implemented, are you by any chance running the app as admin?

**Comment by xwghua** [comment]
Sorry, but I got a little bit confused. Should I run it as admin? Or should I turn the UAC off?
On my PC, I think it's running as admin now (I don't know how to run it without admin), and my UAC is "never notify" and "Disabled" in the Group Policy.
I'm using Win 11, please advise how I should do to enable drag and drop, thanks!

**Comment by Josh65-2201** [comment]
You need to turn on UAC or windows will run everything as admin. Due to Windows limitations Files can not enabled drag and drop when running as admin

**Comment by yaira2** [comment]
@xwghua can you confirm if following these steps helped?

**Comment by xwghua** [comment]
Yes! Thank you so much!
After I changed the UAC settings in the "Control Panel" from "never notify" to the recommend/default setting, and restarted my PC, it just work perfectly.

**Comment by GCG1000** [comment]
Ditto, changing UAC worked.  Thank you!
