### ISSUE TITLE
Bug: Overlay while renaming the file name

### ISSUE THREAD

**Issue by sfksuperman** [files-community/Files#13796]
### Description

While renaming any file, the interface is so transparent that it shows:

1. File type, for e.g. PNG, and
2. File size, for e,g. 1.58 MB

This makes it difficult to rename and check what is we typing there.

<img width="171" alt="1" src="https://github.com/files-community/Files/assets/34414624/23425722-6038-4036-bd60-6a17b3075a98">

### Steps To Reproduce

1. Select a file to rename
2. Choose the "rename" option
3. Type to rename and there you can see the issue before finishing renaming the file.

### Requirements

It should not be so transparent that it overlays on currently writing the names of the file.

### Files Version

3.0.3.0

### Windows Version

10.0.22631.2506

### Log File

[debug.log](https://github.com/files-community/Files/files/13320577/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Are you using the tiles layout?

**Comment by yaira2** [comment]
Looks like Tiles, can you repro in any other layouts as well?

**Comment by yaira2** [comment]
This should be resolved in the next release.

**Comment by sfksuperman** [comment]
> Thanks for the report, Are you using the tiles layout?

Yes
