### ISSUE TITLE
Add option to disable confirmation dialog when deleting files

### ISSUE THREAD

**Issue by seamlink-aalves** [files-community/Files#13792]
### What feature or improvement do you think would benefit Files?

Hi,

I'd like to have an option to disable the confirmation dialog to delete files and move the file directly to Recycle bin like in Windows Explorer.

I'm not aware if this option is available or not but I've searched for this option in settings and haven't found it.

Alexandre Alves

### Requirements

Add option in setting to disable confirmation dialog when deleting files.

### Files Version

3.0.3

### Windows Version

11

**Comment by Josh65-2201** [comment]
Thanks for the feedback, you already can in Files settings > Folders > Show confirmation dialogue box when deleting items
