### ISSUE TITLE
CTRL+INSERT and SHIFT+INSERT keyborad shortcuts

### ISSUE THREAD

**Issue by DarthJahus** [files-community/Files#13794]
### What feature or improvement do you think would benefit Files?

Would it be possible to enable CTRL+INSERT (copy) and SHIFT-INSERT (paste) keyboard shortcuts in the app? They work correctly on Windows Explorer (and pretty much everywhere, in fact).

As a Dvorak layout user, that's how I copy and paste, for it's easier than CTRL+C and CTRL+V. And since they are shortcuts that exist since the dawn of desktop computing, I believe it's worth adding them.

### Requirements

- Pressing CTRL+INSERT will copy whatever is selected.
- Pressing SHIFT+INSERT will paste from the clipboard (if a file is copied).

### Files Version

3.0.3.0

### Windows Version

10.0.19045.3208

**Comment by yaira2** [comment]
Thank you for your feedback, support for remapping shortcuts is on the todo list and is being tracked in #9559.

**Comment by DarthJahus** [comment]
Thank you. However, I wasn't suggesting a remapping, but support for (additional) widely used shortcuts. I believe the nuance is worth mentioning.

**Comment by yaira2** [comment]
It's worth considering that the suggested actions are already available. Support for remapping them will allow you to configure them as you wish (including adding multiple shortcuts for the same action).

**Comment by yaira2** [comment]
This feature will be included in the next release. Please see #9559 for more details.
