### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by RobertoConsultoria** [files-community/Files#13795]
### Description

Só aparece que tem erro, mas não é visível. ao meu ver este é um Bugnão visível ao usuário. 

### Steps To Reproduce

N/D

### Requirements

- e.g. Fix crash that occurs when...
Não tive como fazer teste, não apareceu a opção.

### Files Version

3.0.1.0

### Windows Version

10.0.22621.2506

### Log File

[debug.log](https://github.com/files-community/Files/files/13320121/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report. 
- What error are you seeing?
- What are you doing when the error appears

**Comment by RobertoConsultoria** [comment]
Uso a pouco tempo. Acontece quando estou salvando PDF.
