### ISSUE TITLE
Preview Pane keeps loading when folder selected

### ISSUE THREAD

**Issue by leafpmpmp** [files-community/Files#13809]
### Description

When I single click on a folder  i.e., not opening it, the Preview pane will stay at the state illustrated in the screenshot
<img width="1235" alt="image" src="https://github.com/files-community/Files/assets/49824741/41e23e87-1716-49e1-a7b9-5972ea631294">

### Steps To Reproduce

1. Open Files app
2. Single click any folder
note: If I click on a blank area of the folder, it will show the detail of the folder I'm currently at just fine.

### Requirements

- It should just show whatever it usually would of the folder I selected.

### Files Version

3.0.1

### Windows Version

10.0.22631.2506

### Log File

[debug.log](https://github.com/files-community/Files/files/13325818/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
This issue was fixed in v3.0.3.
