### ISSUE TITLE
slow response comparing to the other file explorer

### ISSUE THREAD

**Issue by Shengwuei** [files-community/Files#13805]
### What feature or improvement do you think would benefit Files?

speed of switching between different folders is slower comparing to the other file explorers, see the attached video, on the left is the "Files" and on the right is another file explorer I found in Microsoft store (https://www.microsoft.com/store/productId/9PDN2Q3DCQS3?ocid=pdpshare)

https://github.com/files-community/Files/assets/140904608/0808a04b-5ccc-4e43-a42e-a4436553e8f8

I switched between folder "ultrasound" and its sub-folder "components" three times, it is obvious that the "Files" is slower to display the folders in the "components" folder, is there a way to speed up the response time of "Files" ?

Thanks.

### Requirements

speed up the response time of displaying folders

### Files Version

2.5.21.0

### Windows Version

Windows 11, 22H2

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #4180. You can check there or click subscribe in the right sidebar for updates.

Files is always improving on performance, I recommended updating to v3.0.3.0 has there has been lots of performance and stability improvements.

**Comment by Shengwuei** [comment]
@Josh65-2201 

I've installed Files 2.5.21.0 and Files preview version 3.0.1.0
I just tried the preview version(3.0.1.0) and the response time is fairly the same with the stable version, i.e. slower than the other filer explorer I found in Microsoft store, thanks.

**Comment by yair100** [comment]
@Shengwuei we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
