### ISSUE TITLE
Context Menu

### ISSUE THREAD

**Issue by meqdadfn** [files-community/Files#13801]
### What feature or improvement do you think would benefit Files?

It would be great to add support to show old context menu instead of currently showing one.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.0.3.0

### Windows Version

10.0.22621.2428

### Comments

Replace this: ![New](https://github.com/files-community/Files/assets/128311643/a3048508-745c-4a7b-9a26-aa2f0ed4bbf3)
with this: ![Old](https://github.com/files-community/Files/assets/128311643/54bfde17-338f-453a-b19e-9611cb881e89)

**Comment by Josh65-2201** [comment]
Thanks for the feedback. the one you want to replace with is the style Files already uses and Files support displaying items better then Windows 11 one. As for the older style Windows 10 one it isn't possible as the code isn't available to Files.
