### ISSUE TITLE
Navigating folder structure becomes impossible when folder contains just 1 item

### ISSUE THREAD

**Issue by tesar-tech** [files-community/Files#13806]
### Description

https://github.com/files-community/Files/assets/33880579/ef3988b3-0cfd-4696-8347-e8cb5982ee12

I am using keyboard for navigating through folder structure. It is arrow up and down, also with alt to navigate back or one level higher.
When I reach folder with just one item (`OneFolder` in this case) pressing the arrows do nothing and the item is not highlighted, thus I cannot open it with Enter key.

Windows explorer has similar behavior, but when I press the arrow down or up it "highlights" the single item.

### Steps To Reproduce

1. Create such folder structure that ends with single folder (`OneFolder` in this case)
  ```    
  ├───Subfolder1
  │   └───OneFolder
  └───Subfolder2
  ```
2. Navigate by keyboard to `OneFolder`
3. Then you cannot open the `OneFolder` with just keyboard, which is the whole issue

### Requirements

- Single item should be able to open with just keyboard

### Files Version

3.0.2.0

### Windows Version

10.0.22621.2428

### Log File

[debug.log](https://github.com/files-community/Files/files/13325034/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #13774. You can check there or click subscribe in the right sidebar for updates.
