### ISSUE TITLE
Bug: Can't open images, of any kind

### ISSUE THREAD

**Issue by VijeshDatt** [files-community/Files#13803]
### Description

When attempting to open images of any kind, nothing happens. Double click or context menu > Open/Open With.

When attempting to do 'Open With', the following error appears:
![image](https://github.com/files-community/Files/assets/19395432/3b0a3831-fef0-418f-b33d-789712c3ea4e)

### Steps To Reproduce

1. Open any folder with images
2. Double click or context menu > open any image of any kind
3. Nothing happens...

### Requirements

Open image in the default previewer or even just the Photos App.

### Files Version

3.0.3.0

### Windows Version

W11 23H2 (22631.2506)

### Log File

[debug.log](https://github.com/files-community/Files/files/13324113/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Does it happen in Windows File Explorer?

**Comment by VijeshDatt** [comment]
Morning @Josh65-2201 nope, the native File Explorer works completely fine. Just Files does this. I can't tell if this happened in previous versions because I only started using Files since 3.0.2.0

**Comment by yaira2** [comment]
>    at Files.App.Utils.Shell.Win32API.<>c__DisplayClass3_0`1.<<StartSTATask>b__0>d.MoveNext()
2023-11-11 13:53:18.0899|Information|System.ComponentModel.Win32Exception (193): An error occurred trying to start process 'D:\Pictures\Memes\example.gif' with working directory 'C:\Windows\system32'. The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Files.App.Utils.Shell.LaunchHelper.<>c__DisplayClass3_0.<<HandleApplicationLaunch>b__0>d.MoveNext()

**Comment by yaira2** [comment]
@VijeshDatt what happens if you try running Files as admin?

**Comment by VijeshDatt** [comment]
@yaira2 Interesting, running Files as admin does allow the images to load in the default image viewer (Photos in my case)

**Comment by VijeshDatt** [comment]
Also to note, after running as Admin, closing and then running as normal, the images now open as they should.

**Comment by yaira2** [comment]
It might have just been a temporary issue, can you try restarting Windows?

**Comment by VijeshDatt** [comment]
Restarted and it still works fine, opens the images as expected. Non-admin mode.

**Comment by yaira2** [comment]
I guess we can close this for now, please let us know if it happens again.

**Comment by VijeshDatt** [comment]
Will do, thank you for your help ☺️
