### ISSUE TITLE
Add an option "open in terminal" in the context menu

### ISSUE THREAD

**Issue by ElReverso1900** [files-community/Files#13818]
### What feature or improvement do you think would benefit Files?

Please show an option "open in terminal" in the context menu when I right click in any blank space of a folder, like this:
![image](https://github.com/files-community/Files/assets/82226077/c453673d-8f22-41fd-b342-9842119a2be7)

### Requirements

- Show an option "open in terminal" in the context menu when I right click in any blank space of a folder.
- Open Windows Powershell in current folder after I click the option.

### Files Version

3.0.3.0

### Windows Version

windows 11 22H2 22621.2428

**Comment by yaira2** [comment]
Thanks for the feedback, this should already be supported. However, some versions of Terminal use the new format for shell extensions which isn't supported in Files yet #8251.
![image](https://github.com/files-community/Files/assets/39923744/c2afbb9e-7d0d-481d-b9dd-fa39b7bbf1ca)

**Comment by parfait8566** [comment]
> Thanks for the feedback, this should already be supported. However, some versions of Terminal use the new format for shell extensions which isn't supported in Files yet #8251. ![image](https://user-images.githubusercontent.com/39923744/282276727-c2afbb9e-7d0d-481d-b9dd-fa39b7bbf1ca.png)

Is there anyway to show "Open in Terminal" in the normal context menu without going to "Show more options"?

**Comment by yaira2** [comment]
You can change the behavior by turning off the option to move items into the sub menu.
![image](https://github.com/files-community/Files/assets/39923744/1f7b3650-ee8f-4cb0-996d-439d756466c3)

**Comment by parfait8566** [comment]
> You can change the behavior by turning off the option to move items into the sub menu. ![image](https://user-images.githubusercontent.com/39923744/283650823-1f7b3650-ee8f-4cb0-996d-439d756466c3.png)

Isn't there a more granular setting? So I can enable only certain shell extensions

**Comment by yaira2** [comment]
Not currently, but it's being discussed in #13463.
