### ISSUE TITLE
Context menu

### ISSUE THREAD

**Issue by ksognli** [files-community/Files#13810]
### What feature or improvement do you think would benefit Files?

Hi, I would like to use the old context menu in Files. Now I use the version 3.0.3.0

Is that possible? 

I could not find the feature in the menu setup. 

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.0.3.0

### Windows Version

10.0.22621.2428

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Windows 10 style it isn't possible as the code isn't available to Files.

**Comment by ksognli** [comment]
And yes I have the old context menu on the rest of windows 11, it's just missing from Files software.

**Comment by ksognli** [comment]
> Thanks for the feedback, Windows 10 style it isn't possible as the code isn't available to Files.

So I can have the old context menu on everything else, but not in files?

**Comment by Josh65-2201** [comment]
No Files doesn't have it.

**Comment by ksognli** [comment]
> No Files doesn't have it.

Allright, thanks for the info.
