### ISSUE TITLE
Annoying gap in details layout browser

### ISSUE THREAD

**Issue by 00000vish** [files-community/Files#13819]
### Description

There is an annoying gap between root grid and name column in the detailed layout browser. 

I am not sure why this magic number padding exist but its really unaesthetic IMO. 

![Screenshot 2023-11-11 212927](https://github.com/files-community/Files/assets/11762008/4f88da7a-e350-4f30-9046-aac1c62c9681)

### Steps To Reproduce

N/A

### Requirements

N/A

### Files Version

3.0.3.0

### Windows Version

N/A

### Log File

N/A

**Comment by yaira2** [comment]
Thanks for the feedback, the gap is to provide space for the selection rectangle.
