### ISSUE TITLE
Ability to turn on secondary  "drives sidebar" in dual pane view + shortcut for opening current directory in dual pane

### ISSUE THREAD

**Issue by theyv** [files-community/Files#13814]
### What feature or improvement do you think would benefit Files?

1. I would really like to see secondary sidebar. Dual pane is one of the best features, but for now I find it hard to navigate and not always I know if dual pane is opened or not.
![image](https://github.com/files-community/Files/assets/13101364/e2dc4be5-5b48-4e66-99ce-ab2c7550d846)

2. It would be nice if I could open current directory in dual pane (clone current folder) with hotkey

### Requirements

- Make setting to show second  sidebar in dual pane view
- Make hotkey for opening current folder in dual pane view

### Files Version

3.0.3.0

### Windows Version

10.0.22621.2500

**Comment by yaira2** [comment]
Thank you for your feedback, we don't have plans to duplicate the sidebar (both for performance and UX reasons). Can you open a separate feature request regarding the shortcut?
