### ISSUE TITLE
Files freezing in big folders

### ISSUE THREAD

**Issue by ElliotS2007** [files-community/Files#13815]
### Description

When navigating to a big folder Files sometimes freezes completly and never recovers. The folders i was navigating are multiple hundreds of gigabytes big 

### Steps To Reproduce

1. Open a big folder
2. Observe

### Requirements

Fix freeze that occurs when navigating big folders

### Files Version

3.0.3.0

### Windows Version

10.0.19045.3636

### Log File

[debug.log](https://github.com/files-community/Files/files/13326456/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, we're actively improving performance and tracking these types of issues in #4180.

**Comment by yair100** [comment]
@ElliotS2007 we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
