### ISSUE TITLE
Open Files ión Windows startup in the background

### ISSUE THREAD

**Issue by ElliotS2007** [files-community/Files#13812]
### What feature or improvement do you think would benefit Files?

Add a toggle in the settings to allow Files to open in the background at Windows startup instead of the foreground. This would in turn make the usage of Files faster as you wouldn't need to do a full cold start the first time you open Files on a fresh boot - together with 'Leave app running in the background when the window is closed' on of course.

### Requirements

- Add a toggle
- Add the underlying system

### Files Version

3.0.3.0

### Windows Version

10.0.19045.3636

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #13510. You can check there or click subscribe in the right sidebar for updates.
