### ISSUE TITLE
Copy & Paste filenames (Not files themselves)

### ISSUE THREAD

**Issue by infuriatedcodex** [files-community/Files#1381]
**Describe the bug**
You have 2 Tabs open in 2 different folders, for example, C:\Folder1 and C:\Folder2.
C:\Folder1 contains a pre-existing file called Image1.bmp
C:\Folder2 contains a brand new file called Newfile.bmp - (for exmaple created in Paint or snipping tool etc.)
You wish to copy just the filename Image1.jpg (using CTRL+C) and rename Newfile.jpg (selecting rename and then use CTRL+V).

Attempting this copies the file itself and not the filename string, from C:\Folder1 to C:\Folder2.

**To Reproduce**
1- Navigate to your C: Drive (or any temp location you fancy) and create a temp folder called Folder1
2- Click on the + and choose Bitmap image and label it Image1.bmp
3- Open the file in Paint and draw a line and then save it for good measure to ensure its registered as a BMP
4- Create a new temp folder called Folder2 in the same parent location as you did in Step 1
5- Create another Bitmap image in this location, same as Step 2 above and label it Newfile.bmp
6- Navigate back to Folder1 and right-click on Image1.bmp and choose rename
7- Use CTRL+C to copy the filename
8- Navigate to Folder2 and right-click on Newfile.bmp
9- Use CTRL+V to paste the copied filename from Folder1
10- Observe as the file is copied into Folder2 instead.

**Expected behavior**
Expect the filename to be copied into clipboard memory so that the string can be used in another filename or any Window that accepts strings.

**Screenshots**

**Desktop (please complete the following information):**
OS Version: [e.g. Windows 10 2004 19041.329]
App version: [v0.11.0]

**Additional context**
When at Step 7, instead of using CTRL+C, right-click and try using copy instead. You will notice a brief flash of the context menu before it quickly disappears.

I think this version of the cannot copy filenames into memory.
However if you have copied a filename from the native File Explorer, this version of the app will paste the filename.

**Comment by yaichenbaum** [comment]
This issue should be fixed in v0.21.
