### ISSUE TITLE
Bug? Files does not close if any other folder is selected apart from File Explorer from Start

### ISSUE THREAD

**Issue by VijeshDatt** [files-community/Files#13825]
### Description

If the Document, Pictures, Music or Videos folder option is selected from the Start Menu, Files opens in the background without minimizing the Start Menu like it does when you click the File Explorer folder icon. (Described icons that don't close the files app are highlighted in red).

Something to note is that Files is not crashing or misbehaving, the correct folder is opening based on the clicked folder button from the Start Menu, it's just that the start menu doesn't close automatically so it requires additional clicks.

![Screenshot 2023-11-12 205914-modded](https://github.com/files-community/Files/assets/19395432/fec03462-4a88-4a08-b6bb-0d2dc24ef0cf)

### Steps To Reproduce

1. Open files via the different folder icons from the Start Menu

### Requirements

Close the start menu and open the selected folder in the Files app in the foreground.

### Files Version

3.0.3.0

### Windows Version

W11 23H2 (22631.2506)

### Log File

[debug.log](https://github.com/files-community/Files/files/13327584/debug.log)

**Comment by yaira2** [comment]
This seems more like a start menu bug

**Comment by yaira2** [comment]
Thanks for the report, unfortunately this is a limitation with the method we use to set Files as the default file manager. Please submit this feedback to Microsoft and ask them for an official method of changing the default file manager.

**Comment by VijeshDatt** [comment]
So a little update on this, I recently discovered that if you have files already open, clicking on the icons for Document, Downloads, etc, will open it in Files in a new tab (based on the setting) and close the start menu.

The only time the start menu will not close on clicking those buttons if files was closed as has to open a new instance. Existing instances will close the start menu.
