### ISSUE TITLE
Bug: Images in some One Drive folders won't load the first time

### ISSUE THREAD

**Issue by leafpmpmp** [files-community/Files#13821]
### Description

All the images in my music library folder in One Drive would show the preview pane like the screenshot on the left when I clicked on it first time, and if I click on another item and back to this one it shows normally like the screenshot on the right.
<img height="600" alt="image" src="https://github.com/files-community/Files/assets/49824741/f97573ca-1e55-4035-9b49-5a634e2e56dc"><img height="600" alt="image" src="https://github.com/files-community/Files/assets/49824741/515007cd-9a40-40d6-b2d2-ee8952fdb683">

Additional info:
- The Pictures folder in my One Drive doesn't have this issue.
- The Pictures folder is ~400 MB and music folder is ~150 GB in size.
  So I did a test and copy an image from the Pictures folder to another folder that's ~27 GB, and it didn't load the first time either.

### Steps To Reproduce

1. Find an image in a fairly large folder in One Drive that's haven't been clicked yet
2. Click on it, and its image should not load in the preview pane
3. Click on anotehr item and click it again, it should show the image this time

### Requirements

- Make it load the first time I click on it, the same way when I click on a image in a smaller folder in One Drive or a local folder of any size.

### Files Version

3.0.3

### Windows Version

10.0.22631.2506

### Log File

[debug.log](https://github.com/files-community/Files/files/13327089/debug.log)

**Comment by yaira2** [comment]
Thanks for the feedback, I updated the title because this issue affects more than the just preview pane.

**Comment by yaira2** [comment]
We're going to continue tracking this in #14437
