### ISSUE TITLE
Files doesn't remember opened tabs if open while shutting down

### ISSUE THREAD

**Issue by Yabino** [files-community/Files#13826]
### Description

If I shutdown the computer when Files is open, it will not remember the previously opened tabs, although the feature to remember tabs is active in the settings.

### Steps To Reproduce

1. Open Files
2. Open various tabs
3. Let Files open
4. Shutdown the computer
5. Start the computer
6. Open Files
7. All previously opened tabs are gone

### Requirements

Make Files always remember the opened tabs

### Files Version

3.0.3

### Windows Version

Windows 11 Pro 23H2 22635.2700

### Log File

Sorry I'm on the road. But if you need the log I'll upload it at the end of the day.

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #12624. You can check there or click subscribe in the right sidebar for updates.
