### ISSUE TITLE
Linux version / support?

### ISSUE THREAD

**Issue by tbone2k-git** [files-community/Files#13824]
### What feature or improvement do you think would benefit Files?

Hello! o)

Does "Files" run on linux already or is there a plan to have a linux version one day?

From my point of view, there is a lack of decent file managers on linux, they fail in so many aspects, like:
- no custom button toolbars or context menus
- no scripting (get/set selected items by script e.g.)
- no custom (scripted) columns, commands
- fully customizable view (small fonts, spacing, no icons in the file/folder view for max. space/performance)
- lacking metadata / media info in columns or preview
- powerful tab handling
- extensive archive support (rar, zip etc.)
- performance
- function over form (no invisible scrollbars e.g.)
- powerful inline rename / mass renaming tool
- sync / mirror / compare folders functionality
- flat view of folder hierarchies
- ..

I was hoping to find some of these features in "Files" and of course linux support! o) 
There are decent file manager on windows, they are that good that it's hard to switch to Linux because of them being so much better. Will "Files" be to the rescue? A new file manager written from scratch, cross platform, powerful, customizable and extendable on all sides?

Thank you! o)

ps: I was looking for the "Question" type of issue, not there yet, so I chose the Feature request. o)

### Requirements

..

### Files Version

3.0.3.0

### Windows Version

Win10

**Comment by Josh65-2201** [comment]
Thanks for the feedback, see comment https://github.com/files-community/Files/issues/11260#issuecomment-1427037717
