### ISSUE TITLE
Bug: Folder size is missing when opening properties from the sidebar

### ISSUE THREAD

**Issue by leafpmpmp** [files-community/Files#13823]
### What feature or improvement do you think would benefit Files?

Currently folder size is not shown in properties of a side panel item, as shown in the first screenshot
But if I click on its parent folder and open its properties from there, it would, as shown in the second screenshot
<img width="660" alt="image" src="https://github.com/files-community/Files/assets/49824741/d3a5be55-ad4d-47a7-a952-27d880a896ab">
<img width="660" alt="image" src="https://github.com/files-community/Files/assets/49824741/33f2bfa4-2f66-4116-9d9a-fc052cadc8a4">

### Requirements

- Side panel folders should show its size in properties.

### Files Version

3.0.3

### Windows Version

10.0.22631.2506

**Comment by yaira2** [comment]
This seems like a bug, thanks for the report.

**Comment by yaira2** [comment]
This should be resolved in the next release
