### ISSUE TITLE
Opening Jar Files

### ISSUE THREAD

**Issue by NoahLake07** [files-community/Files#13827]
### What feature or improvement do you think would benefit Files?

Being able to open .jar files when double-clicked, rather than showing the jar contents as an archive. It seems strange that a files app that is so detailed and well-rounded wouldn't be able to open a .jar file.

### Requirements

- This proposal will result in a much better user experience for a ton of people that I know. The Windows file explorer keeps trying to make itself better, but as a result, they are slowing it down and not responding every time.

### Files Version

3.0.3.0

### Windows Version

10.0.22631.2428

**Comment by Josh65-2201** [comment]
You can already do this be assigning java to open jar files in the right click > Open with menu.

**Comment by yaira2** [comment]
@Josh65-2201 can you confirm that changing the default to Java will enable double clicking moving forward?
