### ISSUE TITLE
Change default "open with"

### ISSUE THREAD

**Issue by Yabino** [files-community/Files#13834]
### What feature or improvement do you think would benefit Files?

It would be great to have the ability to change the "open with" setting for file types.

For example if I want to change the default player for MP4 files.

### Requirements

Add the setting

### Files Version

3.0.3

### Windows Version

Windows 11 Pro 23H2 22635.2700

**Comment by yaira2** [comment]
You should be able to access this from the right click menu. Can you give this a try?

**Comment by Yabino** [comment]
You're right my mistake. I was trying to see the setting in the "properties" menu like on the Microsoft Explorer. Sorry.
