### ISSUE TITLE
Shell link extension doesn't work

### ISSUE THREAD

**Issue by jw0785** [files-community/Files#13836]
### Description

there should be a "pick link source" in the right click menu, then i can drop as symlink or hard link.

### Steps To Reproduce

1. select a file.
2. right click.
3. there's only "drop as", not "pick link source"
4. as a result, every time to create symlink, it requires open explorer or cmd.

### Requirements

Fix shell extension misbehavior

### Files Version

3.0.3

### Windows Version

1000.22678.1000.0

### Log File

[debug.log](https://github.com/files-community/Files/files/13330200/debug.log)

**Comment by yaira2** [comment]
Thanks for the report, we're tracking this issue in #13481.
