### ISSUE TITLE
Incorrect description of operations in the Status Center

### ISSUE THREAD

**Issue by dracp** [files-community/Files#13839]
### What feature or improvement do you think would benefit Files?

From the "_PRUEBAS" folder I have copied and deleted five items. (230530 Contactos 02.jpg, 230530 Contactos 03.jpg, 230530 Contactos 04.jpg, 230530 Contactos 05.jpg, 230530 Contactos 06.jpg,)

The action "Delete" in "Status Center" correctly describes the action performed: "Deleted 5 item(s) from _PRUEBAS".

However the "Copy" action in "Status Center" does not correctly describe the action performed: "Copied 5 item(s) to 230530 Contacts..." (Copied 5 item(s) to 230530 Contacts 06.jpg). 

I understand that by similarity with the action "Delete" it should describe something similar to :
"Copied 5 item(s) in _PRUEBAS" or "Copied 5 item(s) from _PRUEBAS"...?????

![231113 FILES 3 0 3 0_Status Center](https://github.com/files-community/Files/assets/102802425/33c61cc7-4a4c-4791-8fda-8dc31902bdb1)

Except that I do not understand very well the description of the action that Files wants to describe.  

### Requirements

- I understand that by similarity with the action "Delete" it should describe something similar to :
- "Copied 5 item(s) in _PRUEBAS" or "Copied 5 item(s) from _PRUEBAS"...

### Files Version

3.0.3.0

### Windows Version

10.0.22621.2506

**Comment by yaira2** [comment]
@dracp thanks for the report, this looks like a bug, can you open a new issue using the bug report template?

**Comment by yaira2** [comment]
Thanks!
