### ISSUE TITLE
Skinning Chrome style (2023 refresh)

### ISSUE THREAD

**Issue by Yabino** [files-community/Files#13833]
### What feature or improvement do you think would benefit Files?

I am amazed at how slick looks the new Chrome 2023 refresh.

The tabs and address bar flat clean style, and the reactivity/smoothness of the tabs when you move it in/out of a window or within the current window.

Would be could if it was possible to get Files to have different styles.

### Requirements

Ability to skin, change the visual assets.

### Files Version

3.0.3

### Windows Version

Windows 11 Pro 23H2 22635.2700

**Comment by Josh65-2201** [comment]
For tabs to be smooth Microsoft would have to update them in WinUI and for theming follow the instructions at https://files.community/docs/configuring/custom-themes

**Comment by yaira2** [comment]
@Yabino thanks for the feedback, you can build from source and customize the UI to fit your taste.

**Comment by Yabino** [comment]
Well, I'm only a basic end user. It's too deep for me to dive in the code. Thanks anyway!
