### ISSUE TITLE
Bug: Libraries section isn't loading

### ISSUE THREAD

**Issue by itxclan** [files-community/Files#13848]
### Description

The libraries section isn't loading any of the items

### Steps To Reproduce

1. Open app
2. Try expanding the library section on the sidebar

### Requirements
- Fix issue preventing the items from loading

### Files Version

3

### Windows Version

11

### Log File

[debug.log](https://github.com/files-community/Files/files/13337241/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
