### ISSUE TITLE
Can´t find inadvertently deleted files in windows recycle bin folder 

### ISSUE THREAD

**Issue by renegithub** [files-community/Files#13843]
### Description

Hello,
I´m using files version 3.0.3.
I inadvertently deleted a folder with about 50 files in it.
I want to recover the files and folder structure with the Win 11 recycle bin folder, but I can´t find any new deleted files from today.
In the files protocol in the upper right corner, one can see the that the files are permanently deleted. 
How can I recover the files?
How can I setup, that deleted files will be moved to the win recycle bin folder?
I think this is a very serious bug, or the basic setting of files should be modified to "move deleted files to recycle bin folder" instead of deleted it totally. 
How can I change the setting to "move deleted files to recycle bin folder" ?

### Steps To Reproduce

vbnv

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.0.3.0

### Windows Version

10.0.22621.2428

### Log File

[debug.log](https://github.com/files-community/Files/files/13334529/debug.log)
[user_settings.json](https://github.com/files-community/Files/files/13334539/user_settings.json)

**Comment by Josh65-2201** [comment]
Thanks for the report, Since you permently deleted them you can not unless you have a backup. Files by default will send items to the recycle bin if possible and does show a permently popup if not by default. You can make sure you didn't disable it in Files settings > Folders > Show confirmation dialog on deletion.

**Comment by yaira2** [comment]
I just noticed you uploaded the settings file (thank you!) and can confirm you have ""Show confirmation dialog when deleting items" set to always. Can you confirm if the confirmation prompt was displayed?

**Comment by renegithub** [comment]
Hello,
I can confirm, that I haven´t changed anything in the setting since I have installed your tool 3 days ago. That´s way I was so surprised, that my datas were lost now, without any warnings.

**Comment by renegithub** [comment]
I think the default setting should delete the files into the win recycle bin. Otherwise, there should be a message box with a text box to type "ok" to delete the data permanently.

**Comment by yaira2** [comment]
> I think the default setting should delete the files into the win recycle bin

Some items cannot be moved to recycle bin but that's the default when available. Can you confirm if you at least saw the confirmation prompt?

**Comment by yaira2** [comment]
How did you delete the files?

**Comment by renegithub** [comment]
I marked the folder with the mouse and press the delete  button on the keyboard. Within the folder, there were 4 subfolders and about 50 files.

**Comment by yaira2** [comment]
Can you repro the issue where the prompt doesn't display?

**Comment by renegithub** [comment]
I have recovered the files with the free recuva recovery tool. Now I´m on the way to check if all the files are ok, mostly .pdf.
Does your tool support the Windows files versioning (which was not enabled on my PC)?
But I guess Windows Versioning is only supporting some Win default folders like images, etc. but not specific custom folders an any hard drive, right?

**Comment by renegithub** [comment]
I tried to repro it on another drive with one folder, one subfolder and two files in it.
There I saw the first time the messagebox with the  checkbox "permanently delete".
I´m sure that I haven´t saw it at the first time and I whould not checked it.
Maybe for the future you can also add the explanation after the checkbox "permanently delete" the the files are not moved to the recycle bin.

P.S. The recovered files were mostly .pdf files, docx, xlsx and Windows-Links to other Win-folders. The biggest files size was about 4 MB

**Comment by yaira2** [comment]
I'm glad to hear you were able to recover the items. Files doesn't currently display the version tab in the properties window, but it's compatible with the feature in File Explorer.

**Comment by yaira2** [comment]
> I tried to repro it on another drive with one folder, one subfolder and two files in it.

Can you try from the same folder where the issue happened? Is it possible that you accidently hit the enter key without realizing?

**Comment by yaira2** [comment]
> Maybe for the future you can also add the explanation after the checkbox "permanently delete" the the files are not moved to the recycle bin.

I like your idea to require typing "delete" before the okay button becomes enabled.

**Comment by renegithub** [comment]
Sorry, I haven't got the time today to start another test. Maybe tomorrow.

**Comment by Jay-o-Way** [comment]
> if the items can't be moved to recycle bin, the \"permanently delete\" option will be selected automatically

See @yaira2 this is where an app should play it safe. Come Win Explorer: it throws another confirmation dialog. Honestly, this is a big mistake because of the huge impact.

**Comment by yaira2** [comment]
@Jay-o-Way the behavior in Files isn't any different than File Explorer. You can check this by deleting an item from Recycle Bin and confirming that the "permanently delete" option is selected. We can take this a step further and require the user to type confirmation to prevent any misunderstandings, but it should be **absolutely clear** that this is working as designed and is not a bug.
![image](https://github.com/files-community/Files/assets/39923744/c2482e2f-274a-4a94-aabf-4c717cc27003)

**Comment by yaira2** [comment]
What does require further investigation, however, is why the dialog wasn't displayed for @renegithub. Hopefully they can repro this issue so that we can work on a fix.

**Comment by yaira2** [comment]
@renegithub were you able to repro this issue again?

**Comment by yaira2** [comment]
@renegithub

**Comment by yaira2** [comment]
I’m closing this because due to inactivity and because we haven’t heard any other reports. However, due to nature of this report we’ll keep an eye out for similar reports.
