### ISSUE TITLE
Grouping doesn't work

### ISSUE THREAD

**Issue by stoph88** [files-community/Files#13844]
### Description

When "Group By" is set to "none" it groups by type.  I just want to see my downloads folder in order of the date the item was added, irrelevant of whether it's a folder or file, or of file type. 

### Steps To Reproduce

Just look at downloads and click to sort by date

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.0.3.0

### Windows Version

10.0.19045.3570

### Log File

BALLS

**Comment by yaira2** [comment]
Thank you for the report, please upload the log file so we can investigate this issue.
