### ISSUE TITLE
Infinite loading on system startup

### ISSUE THREAD

**Issue by benbrummer** [files-community/Files#13842]
### Description

Infinite loading on system startup
<img width="434" alt="2023-11-11 06_57_31-Files" src="https://github.com/files-community/Files/assets/24470839/2e71ce7c-51be-4d70-915f-54fecb258b30">

### Steps To Reproduce

1. Activate "Open Files on Windows startup"
2. Reboot Windows
3. Files is loading forever
4. Close Files
5. Start Files again

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.0.3.0

### Windows Version

Windows 11 23H2

### Log File

[debug.log](https://github.com/files-community/Files/files/13334149/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, This has been fixed and will be available in the next update.
