### ISSUE TITLE
Skip button for update

### ISSUE THREAD

**Issue by benbrummer** [files-community/Files#13841]
### What feature or improvement do you think would benefit Files?

When a new update has been found it should be possible to skip the update
![image](https://github.com/files-community/Files/assets/24470839/05e3d64b-b67c-4be0-a35a-67ceea36b475)
With weak or unstable data connection the app can not be used-

### Requirements

- App can be used, when an update is not possible or wanted

### Files Version

3.0.2.0

### Windows Version

Windows 11 23H2

**Comment by Josh65-2201** [comment]
Thanks for the feedback, This is apart of App installer and not Files so we can not change the functionally there. What happens if you press no?

**Comment by benbrummer** [comment]
Than i have just the "Update" button and the close "X". So no way to get into the app.

**Comment by yaira2** [comment]
This is a limitation with the sideload version, to work around this issue, we suggest using the Store version which doesn't have this problem.
