### ISSUE TITLE
Crash when I tried to click on Status center

### ISSUE THREAD

**Issue by Quentin-L-Inge** [files-community/Files#13855]
### Description

A crash occur when I delete a file and when I click on the button on the top right (I never used this software, I installed it a few minuts ago and tried it)
![Capture d'écran 2023-11-13 203948](https://github.com/files-community/Files/assets/75664985/aa853e10-caef-47ef-8043-c2982e47090e)

### Steps To Reproduce

1. Delete a file
2. Click on status center
3. Crash

### Requirements

Fix crash that occurs when I delete a file then when I click on the button on the top right

### Files Version

3.0.4.0

### Windows Version

Windows 11 build 22621.2428

### Log File

[debug.log](https://github.com/files-community/Files/files/13340330/debug.log)

**Comment by yaira2** [comment]
This is fixed in v3.0.5
