### ISSUE TITLE
Not working with OneDrive

### ISSUE THREAD

**Issue by Traxeronus** [files-community/Files#13850]
### Description

Instantly downloads all the files from cloud storage. It means once installed, the app attempts to download the whole content of your remote storage even the files there are marked as remote only. 

### Steps To Reproduce

Open Files
Open linked OneDrive folder

Maybe it could have something to do with Personal Vault as I noticed about 500 files in error in OneDrive app. These files appeared located in personal Vault even they've never been there. OneDrive asked me to unlock the Vault. Immediately after that OD said that all the files were deleted form the Vault (even they've never been there located ever before).

### Requirements

Keep the cloud files remote until I want to open them.

### Files Version

3.0.3.0

### Windows Version

10.0.22635.2700

### Log File

[debug.log](https://github.com/files-community/Files/files/13337916/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, This has been fixed and will be available in the next update.

**Comment by yaira2** [comment]
@Josh65-2201 the fix was included in v3.0.3.

**Comment by yaira2** [comment]
@Traxeronus do you have the option to calculate folder sizes turned on?

**Comment by Traxeronus** [comment]
@yaira2 No
[Files_3.0.3.0.zip](https://github.com/files-community/Files/files/13339222/Files_3.0.3.0.zip)

**Comment by yaira2** [comment]
> Open linked OneDrive folder

Is this the root directory of OneDrive?

**Comment by Traxeronus** [comment]
@yaira2 I'm actually not sure what caused that. I believe it was when opening "Documents" which are mapped to: C:\Users\User\OneDrive\Documents. I also opened the: C:\Users\User\OneDrive. 
Probably the first I opened the Documents folder.

**Comment by yaira2** [comment]
For testing purposes, can you
1. Create a new folder and add a couple of text files
2. Right click the files and free up space
3. Refresh the directory and see if the files are downloaded

**Comment by yaira2** [comment]
@Traxeronus

**Comment by yaira2** [comment]
Merging with #12774

**Comment by Traxeronus** [comment]
@yaira2 Sorry guys, I'm traveling these days, no time. I saw you found some fix, so once it'll be available in release, I check it out.
Thanks!

**Comment by yaira2** [comment]
Thanks!
