### ISSUE TITLE
App opens in 5-6 seconds

### ISSUE THREAD

**Issue by Saransh719** [files-community/Files#13864]
### Description

Whenever I open the files app, it takes 5-6 seconds to open(it keeps loading). I just wanted to know if there was any way to prevent this
Note-: I have already enabled "leave app running in background option" and files is my default manager

### Steps To Reproduce

Open Files app

### Requirements

The app should open instantaneously or withing 1-2 seconds

### Files Version

3.0.3.0

### Windows Version

19045.3570

### Log File

[debug.log](https://github.com/files-community/Files/files/13347581/debug.log)

**Comment by yaira2** [comment]
@Saransh719 the first launch can take some time, but it should be faster when resuming from the background, can you confirm if this is the case?

**Comment by Saransh719** [comment]
@yaira2 No I dont even shut down my laptop, it remains on sleep for most of the time. Even after the first launch files takes a long time to open. Is there a way to check if program is remaining open in the background or closing?

**Comment by yaira2** [comment]
1. Close the process from Task Manager
2. Launch Files (cold start)
3. Close the app normally
4. Open it again

**Comment by yaira2** [comment]
I think the process gets hidden from the main page but is visible in the details page.

**Comment by Saransh719** [comment]
https://github.com/files-community/Files/assets/115471237/674da5df-89e9-407d-a798-22654b1ebd42


This was after the "leave app running in background " option was **enabled**

**Comment by yaira2** [comment]
Can you try closing the process from Task Manager?

**Comment by Saransh719** [comment]
> Can you try closing the process from Task Manager?

Did that, still taking 5-6 seconds to load

**Comment by Jay-o-Way** [comment]
Yeah it usually takes a short time for me too. Maybe it's just a performance issue?

**Comment by yaira2** [comment]
Can you see if this helps?
1. Open the run dialog box `win + r`
2. Run `taskkill -f -im files.exe` and wait a couple seconds before doing step 3
3. Open Files from the **taskbar** and wait for it to load
4. Close the window normally
5. Open Files from **taskbar** again and see if it's faster

**Comment by Saransh719** [comment]
> Can you see if this helps?
> 
> 1. Open the run dialog box `win + r`
> 2. Run `taskkill -f -im files.exe` and wait a couple seconds before doing step 3
> 3. Open Files from the **taskbar** and wait for it to load
> 4. Close the window normally
> 5. Open Files from **taskbar** again and see if it's faster

Thank you very much this seems to have fixed the issue

**Comment by yaira2** [comment]
Thanks! In the future we hope to add an icon to the system tray to make this process easier.
