### ISSUE TITLE
App downloading in the void and for eternity at the start

### ISSUE THREAD

**Issue by Nicotibeuh** [files-community/Files#13863]
### Description

So when i start my PC Files App launch and load in the void like a Youtube video when u don't have connection. When i restart the app it's all good. 

### Steps To Reproduce

Restart PC
Files app launch
Files app load indefinitly
Restart app
All fix

### Requirements

- e.g. Fix crash that occurs when...
you start your pc

### Files Version

3.0.3.0

### Windows Version

W10 22H2

### Log File

No log files

**Comment by Josh65-2201** [comment]
Thanks for the report, this is fixed in 3.0.5.0

**Comment by yaira2** [comment]
@Nicotibeuh can you confirm if the fix is working for you?
