### ISSUE TITLE
BUG: Description of operations in the Status Center

### ISSUE THREAD

**Issue by dracp** [files-community/Files#13868]
### Description

From the "_PRUEBAS" folder I have copied and deleted five items. (230530 Contactos 02.jpg, 230530 Contactos 03.jpg, 230530 Contactos 04.jpg, 230530 Contactos 05.jpg, 230530 Contactos 06.jpg,)

The action "Delete" in "Status Center" correctly describes the action performed: "Deleted 5 item(s) from _PRUEBAS".

However the "Copy" action in "Status Center" does not correctly describe the action performed: "Copied 5 item(s) to 230530 Contacts..." (Copied 5 item(s) to 230530 Contacts 06.jpg). I understand that by similarity with the action "Delete" it should describe something similar to : "Copied 5 item(s) in _PRUEBAS" or "Copied 5 item(s) from _PRUEBAS"...

![231113 FILES 3 0 3 0_Status Center](https://github.com/files-community/Files/assets/102802425/d507b5bc-c82f-4c02-87f7-47d8374657b9)

Except that I do not understand very well the description of the action that Files wants to describe.

### Steps To Reproduce

1. Copy 5 elements
2. Delete 5 items
3. Open Status Center

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.0.3.0

### Windows Version

10.0.22621.2506

### Log File

I have reinstalled the system and no log file is available.

**Comment by yaira2** [comment]
Thanks for the report

**Comment by Josh65-2201** [comment]
@dracp Is this still an issue in 3.2.4 https://files.community/download

**Comment by yaira2** [comment]
We're having trouble reproducing this in the latest version of Files, please let us know if you can still repro and we'll try to investigate further.
