### ISSUE TITLE
Bug: UTF-8 characters replaced by symbol when previewing a text file

### ISSUE THREAD

**Issue by Androl404** [files-community/Files#13866]
### Description

Hi, I have a header file in which there are some UTF-8 caracters (principaly "é") which are replace by a symbol when I preview the file.

### Steps To Reproduce

1. Open Files
2. Go to a folder with one or more text files encoded in UTF-8
3. Left click one time on one file
4. Open the preview pane
5. Switch to the preview tab
6. Look at the preview of your text file, you'll remark that some characters are not previewed correctly

### Requirements

I expect from Files to correctly show the UTF-8 encoded characters (like "é").

### Files Version

3.0.5.0

### Windows Version

10.0.19045.3570

### Log File

[debug.log](https://github.com/files-community/Files/files/13349000/debug.log)

**Comment by yaira2** [comment]
@Androl404 what's the file extension?

**Comment by yaira2** [comment]
Thanks for the response.

**Comment by yaira2** [comment]
@Androl404 does it display correctly in File Explorer? I think our best option is to switch to the same preview that they use.

**Comment by Androl404** [comment]
No, it does not work in file explorer neither with `.h` files or `.cpp` files, but like in Files, it works with `.txt` files.

**Comment by antonioseet** [comment]
I am not encountering this issue in .txt, .cpp, & .h files

![image](https://github.com/files-community/Files/assets/28791910/d5030c21-61a6-44e4-8bfa-0029f0552dc9)

or am i missing something when it comes to "encoding" my files to UTF-8?

**Comment by kowalkos** [comment]
also seem to work fine for me

**Comment by Androl404** [comment]
Hi, after further investigation, it seems that Visual Studio was encoding my project files in a weird format (occidental alphabet (code pages 1252)). After re-encoding the files in a new format, it worked completely fine.

Maybe you could add a option for the preview encoding, but I guess I won't be really used and quite useless.

Sorry for the bothering.

**Comment by yaira2** [comment]
> Maybe you could add a option for the preview encoding, but I guess I won't be really used and quite useless.

I think that's a bit out of scope for the project. The preview pane is not intended to replace a proper editor but rather provide a little preview into the contents. Glad to hear it's working now!
