### ISSUE TITLE
Touch Pen Lag

### ISSUE THREAD

**Issue by nuomation** [files-community/Files#13867]
### Description

The touch interface on V3 lags when using a Surface Pen 2 Slim, on a Windows 11 / Surface Laptop Studio.
This didn't happen in the previous version V2.
When using the fingers it works fine but for some reason pen has a very noticeable lag

### Steps To Reproduce

Use pen on touch screen

### Requirements

- e.g. Fix crash that occurs when...
It should be reacting properly with fingers or pens on touch devices

### Files Version

3.0.5.0

### Windows Version

10.0.23555.1000

### Log File

[debug.log](https://github.com/files-community/Files/files/13349800/debug.log)

**Comment by yaira2** [comment]
Thanks for the report, do you mean when clicking elements via pen?

**Comment by yaira2** [comment]
The only change that we made in this area was updating to WinUI 1.4 in which case this affects other apps as well. Can you open a report in the WinUI repo? https://github.com/microsoft/microsoft-ui-xaml

**Comment by nuomation** [comment]
I wont be able sorry

**Comment by yaira2** [comment]
👍
