### ISSUE TITLE
Bug: Tooltip Issue on Action Titles

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#13873]
### Description

I've noticed that when I hover over the action title, the tooltip only appears when the action is not in progress.

### Steps To Reproduce

1. Initiate an action
2. Navigate to the status center
3. Hover over the title

### Requirements

Implement a solution that allows the tooltip for an action title to display in real-time, irrespective of whether the action is in progress or completed.

### Files Version

3.0.5.0

### Windows Version

10.0.22621.2506

### Log File

...

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
This in by design

**Comment by Jay-o-Way** [comment]
> This in by design

Sounds like I had the same feedback recently. How can this be by design? If you need it, you need it

**Comment by yaira2** [comment]
Not every action state has a tooltip at the moment
