### ISSUE TITLE
Bug: Exporting settings create a blank zip

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#13876]
### Description

*

### Steps To Reproduce

1. Go to Files settings > Advanced > Export
2. See exported zip is empty

### Requirements

- Export settings into zip

### Files Version

3.0.5.0

### Windows Version

10.22621.2506

### Log File

[debug.log](https://github.com/files-community/Files/files/13356140/debug.log)

**Comment by yaira2** [comment]
Thanks for the report
