### ISSUE TITLE
Bug: Changing column width sets any none visible ones to 0

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#13877]
### Description

Changing the name column the recycle bins original path and deleted date set to 0 same for git columns when not in a git directory

### Steps To Reproduce

1. Enable Files settings > Folders > Sync folder layout and preferences across directories
2. Change any column (Name is best to use)
3. Go to recycle bin or git directory.
4. See folder specific columns set to 0

### Requirements

- Don't change width of columns that are not dragged.

### Files Version

3.0.5.0

### Windows Version

10.22621.2506

### Log File

[debug.log](https://github.com/files-community/Files/files/13356221/debug.log)

**Comment by yaira2** [comment]
Thanks for the report
