### ISSUE TITLE
Bug: Compression Operation Reporting

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#13870]
### Description

I've noticed a problem when selecting one or more folders, initiating compression, then canceling it. Instead of marking the operation as canceled, it incorrectly reports a successful operation.

### Steps To Reproduce

1. Initiate compression of one or more folders
2. Cancel the compression

### Requirements

Improve error handling to distinguish between successful completions and canceled operations.

### Files Version

3.0.5.0

### Windows Version

10.0.22621.2506

### Log File

...

**Comment by Josh65-2201** [comment]
Thanks for the report, how is this different from #13872?

**Comment by Lukiluc29** [comment]
> Thanks for the report, how is this different from #13872?

Here we talk about compression while the one mentioned talks about extraction.

**Comment by yaira2** [comment]
It appears to be the same cause so I think we can track both there. Just to make sure we fix both, please mention this issue in the description.
