### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by BrotherStein** [files-community/Files#13875]
### What feature or improvement do you think would benefit Files?

Please add List to the layouts.  I use this layout more than any other.

### Files Version

3.0.5.0

### Windows Version

10.0.22631.2506

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #2509. You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
@BrotherStein thank you for your patience, I'm excited to share that a List View layout will be included in the next release.
