### ISSUE TITLE
Bug: Exchange of interface texts

### ISSUE THREAD

**Issue by dracp** [files-community/Files#13871]
### Description

There seems to be an error between Crowdin translation strings and their location in GUI 3.0.5.0. 

Description:
Toggles the details/preview pane > Description located as action.
Conmuta el panel de detalles/vista previa <> Muestra/Oculta el panel de detalles y vista previa

Action:
Toggle the details/preview pane > Action located as description.  
Conmutar el panel de detalles/vista previa <> Mostrar/Ocultar el panel de detalles y vista previa

![231114 Files 0 3 5 0 Error en interfaz](https://github.com/files-community/Files/assets/102802425/73d573f0-2b8e-40ff-907d-25a9f07a751d)

### Steps To Reproduce

....

### Requirements

- Swap text between action in command palette and tooltip in interface button

### Files Version

3.0.5.0

### Windows Version

10.0.22631.2506 (23H2)

### Log File
**NOTE
Check also in Crowdin the expressions "Toggle the details pane" in action and description.**
....

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
Thanks for the report, this will be fixed in the next update.
