### ISSUE TITLE
Cut/Paste file folder crashed app

### ISSUE THREAD

**Issue by roguex-tech** [files-community/Files#1388]
**Describe the bug**
**Cut a folder with files from my downloads folder and pasted that folder to my "_SORT" folder on my external hard drive**

**To Reproduce**
**1. Go to "Downloads" folder
2. right click folder to be cut, click cut
3. Navigate to external drive folder and right click, then click paste
4. See log files attached**

**Expected behavior**
Expected the folder and files within folder to be cut and pasted.
[debug.txt](https://github.com/files-community/files-uwp/files/4904723/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/files-uwp/files/4904724/debug_fulltrust.txt)

**Screenshots**

**Desktop (please complete the following information):**
 **- OS Version: [e.g. Windows 10 Pro 20161.200627-1754]
 - App version: [v0.11.2]**

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?
**Yes, it is continuing to do crash.**

**Comment by Thomas1664** [comment]
@roguex-tech Is this still an issue in the latest version?

**Comment by roguex-tech** [comment]
@Thomas1664 Not at this time. I can no longer reproduce it. Close her up...

**Comment by Thomas1664** [comment]
@yair100 You can close this issue and mark it as fixed.
