### ISSUE TITLE
Crash when dragging multiple files to the edge (to scroll the view)

### ISSUE THREAD

**Issue by superluig164** [files-community/Files#13889]
### Description

I grabbed a number of files on a USB drive with a lot of files.  When I attempted to drag them to the edge of the view to scroll it, Files hung then crashed.  I wasn't able to reproduce it at another location, so perhaps something to do with a file on the drive or something, but it's definitely reproducible in that location.

### Steps To Reproduce

1. Grab a few files at once.
2. Try to drag them to the edge of the view to scroll it.
3. Observe the crash.

### Requirements

I would expect the view to scroll up or down depending on which edge I drag my cursor to.

### Files Version

3.0.5.0

### Windows Version

10.0.22631.2428

### Log File

[debug.log](https://github.com/files-community/Files/files/13360276/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Can you confirm that this is the same as #11149

**Comment by superluig164** [comment]
Seems like it, though it only happens on this drive for me.  I was able to scroll the view fine on my internal drives, for now.
