### ISSUE TITLE
Code Quality: Add command parameter to IAction

### ISSUE THREAD

**Issue by 0x5bfa** [files-community/Files#13892]
### Description

Speaking of the general usage of the Button command, we would use Command and CommandParameter. Current implemenetation of the RichCommand doesn't have parameter to use inside of an IAction. I'd like to add parameter to it and expand ability of the RichCommand. With it, we are going to be able to use RichCommand even for commands in the SideBar control and Home page.

### Concerned code

- Files.App.Actions

### Gains

- An expanded usage of the RichCommand

### Requirements

- Add `object Parameter { get; }` to the certain action.

**Comment by 0x5bfa** [comment]
@d2dyno1 @cinqmilleans How can this be implemented?

Adding something like IFlexibleAction and enforce to have parameter property as a nullable? or just let actions to have or not to?

**Comment by 0x5bfa** [comment]
@yaira2 I think there's no way but letting actions decide to recieve parameter or not. Can I work on?

**Comment by yaira2** [comment]
👍

**Comment by 0x5bfa** [comment]
This is not what who have made Contexts expects.

We can create any contexts for anywhere. I wanted this for SideBar and Widgets, but I already added contexts for both and will change to use Actions for them.
