### ISSUE TITLE
I can't put de recycle bin in left bar favorites

### ISSUE THREAD

**Issue by RickyVercetti** [files-community/Files#13894]
### Description

Move from desktop to favorites app crash
i'd great put in preferences turn on/off 

### Steps To Reproduce

1. Move from desktop to favorites app crash

### Requirements

- e.g. Fix crash that occurs when...
Move from desktop to favorites app crash

### Files Version

3.0.5.0

### Windows Version

10.0.22631.2715

### Log File

[debug.log](https://github.com/files-community/Files/files/13366757/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, you should be able to type `Shell:RecycleBinFolder` into the path bar > Right click blank space > Add to favourites.

**Comment by RickyVercetti** [comment]
It works!!! Thank you so much!!!!!! :)
