### ISSUE TITLE
Bug: Copy & paste out of ZIP/archive file does not work

### ISSUE THREAD

**Issue by dharmababa** [files-community/Files#13898]
### Description

Copying and pasting one or multiple files out of a ZIP file updates the Status Center but the file does not appear.

### Steps To Reproduce

1. Open a ZIP file with multiple files.
2. Select one or more of the files
3. Hit Ctrl-C or right-click Copy
4. Navigate to another folder in that tab or another tab
5. Hit Ctrl-V or right-click Paste

### Requirements

Expected: file(s) appear in destination folder

Actual: Message in Status Center indicating the file(s) have been copied but they are not there.

### Files Version

3.0.5.0

### Windows Version

10.0.22631.2715

### Log File

[debug.log](https://github.com/files-community/Files/files/13369484/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by SimonFrank14** [comment]
Hey, the issue also exists on my side. When dragging a file out of a zip archive into another folder to copy process is just aborted with an error message.

**Comment by otDan** [comment]
providing video of the issue: 

https://github.com/files-community/Files/assets/59731738/69a33995-e2ee-4871-b5e0-6aa6b1a67214

**Comment by Lukiluc29** [comment]
I saw this problem appear from the moment the transfer speed graph was implemented.

**Comment by NightmareZero** [comment]
I have the same problem, and it is even more serious than this. After repeatedly experimenting with this feature, "Files" froze my clipboard, and I had to kill the Files process from TaskMgr to solve this problem (I have it set to run in the background)

**Comment by irk72ag** [comment]
I have same problem. On 3.1 version. Win11

**Comment by yaira2** [comment]
This issue should be fixed in the next release.

**Comment by dharmababa** [comment]
Confirmed fix in v3.3. Thank you team!

**Comment by yaira2** [comment]
Thanks for the confirmation
