### ISSUE TITLE
Bug: Unable to drag and drop any file onto .py files

### ISSUE THREAD

**Issue by AyanamiRei1** [files-community/Files#13890]
### Description

The drag-and-drop functionality seems to have a limitation, preventing the dragging and dropping of files with any file extension onto .py files.

This does not happen with .bat.

### Steps To Reproduce

1. Make a .py file
2. Try to drag any file onto it.

### Requirements

It should allow me to drag and drop file onto .py files, but it currently does not.

### Files Version

3.0.5.0

### Windows Version

10.0.22631.2506

### Log File

[debug.log](https://github.com/files-community/Files/files/13360569/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
I think this is custom behavior we had to add for batch files, I assume the same can be done for .py.

**Comment by antonioseet** [comment]
Got a fix going, will try to submit a PR tomorrow morning!

**Comment by antonioseet** [comment]
@yaira2 

After testing windows File Explorer with both python and batch files, when multiple files are dragged onto either python or batch, they are passed in as two parameters. But in the current Files implementation when two or more files are dragged onto the batch file, it opens an instance of the batch file per file that gets dragged in. (The same thing happens in my python fix implementation, multiple instances per file dragged.)

This seems like undesired behavior and I could work on getting both the python and batch files working as they do in File Explorer, but I would like to get some feedback before proceeding.

**Comment by yaira2** [comment]
Let's work on support for a single file first and once that's merged, we can take a look at the behavior for multiple files.
