### ISSUE TITLE
Display file path / location of files in search results window

### ISSUE THREAD

**Issue by JollyRoger8X** [files-community/Files#13897]
### What feature or improvement do you think would benefit Files?

There should be a way to quickly view the location of each file in the search results list.  A couple different ways come to mind:

* Display the selected item's path in the path bar at the top of the window.
* Display the selected item's path in the status bar at the bottom of the window.
* Display an item's path in a tooltip when hovering over an item in the list.

It could be useful to have multiple of these options (hover and path display in the window itself). 

I think one of the first two may be preferable since it may allow the user to copy the path to the clipboard.

On a related note, the contextual menu command "Open parent folder" should default to opening a new tab so that the search results list is not lost. That way you could view the location of each search result item without having to go back and search again.

### Requirements

- This proposal will allow users to quickly view the location of search result items.
- This proposal will allow users to copy the path of search result items.
- This proposal will allow users to open the parent folder of a search result item without losing the search results and having to perform the search again to go back to the list.

### Files Version

3.0.5.0

### Windows Version

Windows 10 Enterprise 22H2 build 19045.3324

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Files already has this you can enabled it by right clicking the name header and enable path.

**Comment by JollyRoger8X** [comment]
> Thanks for the feedback, Files already has this you can enabled it by right clicking the name header and enable path.

Unfortunately, something is preventing this column from displaying correctly for me. It is displayed with a minimal width that I cannot expand:

![Files - Path column in search results 1](https://github.com/files-community/Files/assets/6462046/b3699b36-508b-47ed-b8ab-5dfa50700a91)
![Files - Path column in search results 2](https://github.com/files-community/Files/assets/6462046/44d040c1-0417-42cf-88ee-d31fececbdf6)

**Comment by Josh65-2201** [comment]
Try going to Files settings > Advanced > Edit settings file > close Files (Make sure the background process is killed in task manager) > Search for `PathColumnWidth` > enter a value above 0

**Comment by JollyRoger8X** [comment]
Interesting. I exited Files and ended the background task, and I see it's already set to 200:

`  "PathColumnWidth": 200,`

I tried setting it to 100, then started Files again, but there is no change. 
I tried setting it to 0.
And I tried setting it to 450.
No change in behavior. It won't let me expand the width of that column with the mouse. Hmm...
