### ISSUE TITLE
Open Files as minimised on startup

### ISSUE THREAD

**Issue by imanoobhehe** [files-community/Files#13893]
### What feature or improvement do you think would benefit Files?

Doing this would probably hep users using Files as their default explorer, as it would keep the app running in the background but also minimised, so that you don't have to view Files immediately on startup

### Requirements

- This proposal will accomplish better accessibility and speed

### Files Version

3.0.5.0

### Windows Version

10.0.22631.2715

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #13510. You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
Thanks for the feedback, this actively being looked into.
