### ISSUE TITLE
Bug: Icon overlays for folders/files in Google Drive don't update

### ISSUE THREAD

**Issue by FAFCosta** [files-community/Files#13901]
### Description

There is a problem related to updating file icons when using Google Drive synchronization (Windows 11). Icons do not correctly inform the file/folder synchronization.

### Steps To Reproduce

In the windows explorer: When using Google Drive to synchronize files with the cloud, the icons are changed (they now have a small green badge at their base). During the process of syncing the files/folders, these green badges are changed to badge which informs you that those items are being synced. Once synchronized, the seal turns back to green. (informing you that the file/folder has been properly synchronized).

![Captura de tela 2023-11-15 222153](https://github.com/files-community/Files/assets/150982265/b1a20fa5-f3b5-48eb-9061-61b024c62903)
![Captura de tela 2023-11-15 222306](https://github.com/files-community/Files/assets/150982265/fcd77c73-13a8-40e2-a3a5-4188cca002d2)
![Captura de tela 2023-11-15 222153](https://github.com/files-community/Files/assets/150982265/ea09300c-2693-4109-91ad-558586c59861)

In the Files App: In the case of "Files App" during synchronization the badge changes to synchronization badge, but even when the synchronization ends, the badge does not return to its original shape giving the impression that the files/folders have not been synchronized or are still being synchronized, eternally. However, the files/folders have already been synced smoothly. The App just doesn't update the information.

![Captura de tela 2023-11-15 222153](https://github.com/files-community/Files/assets/150982265/21b1a056-8386-42e6-9661-b69c7681c089)
![Captura de tela 2023-11-15 222306](https://github.com/files-community/Files/assets/150982265/b589e2e3-68dc-4f37-a911-3bb7de3c0685)
![Captura de tela 2023-11-15 222306](https://github.com/files-community/Files/assets/150982265/94a9c92f-db5c-4404-8726-433dc3472bd8)

### Requirements

After the files/folders are synced, the sync badge should return to its original shape (green).

![Captura de tela 2023-11-15 222153](https://github.com/files-community/Files/assets/150982265/28c2e081-254b-4516-a207-10bade293b65)
![Captura de tela 2023-11-15 222306](https://github.com/files-community/Files/assets/150982265/d662a9da-d2a9-439e-98bf-fc7fd423cff5)
![Captura de tela 2023-11-15 222153](https://github.com/files-community/Files/assets/150982265/47b52104-7797-4dc8-a33a-83afc9e1b1c9)

### Files Version

3.0.5.0

### Windows Version

10.0.22631.2715

### Log File

[debug.log](https://github.com/files-community/Files/files/13371621/debug.log)

**Comment by yaira2** [comment]
Do they update if you refresh the folder?

**Comment by FAFCosta** [comment]
> Do they update if you refresh the folder?

No! When updating (F5) the folder does not update! Even when closing the Files App and reopening, it does not update. Updates only after the Files App has been closed/reopened for some time.

**Comment by yaira2** [comment]
@gave92 any thoughts?

**Comment by yaira2** [comment]
Do they update when you click "refresh" in the latest preview version? https://files.community/download/preview

**Comment by yaira2** [comment]
@FAFCosta do they automaticlly update in File Explorer or do you need to manually refresh the folder?

**Comment by yaira2** [comment]
@FAFCosta

**Comment by yaira2** [comment]
@FAFCosta do they automaticlly update in File Explorer or do you need to manually refresh the folder?
