### ISSUE TITLE
FilesV2 crashes when more than one tab is open

### ISSUE THREAD

**Issue by thisisartman** [files-community/Files#13905]
### Description

When I have FilesV2 open with more than one tab, it takes a toll on the program. It won't open the file.

Instead, it will crash FilesV2 and then only after you restart FilesV2, will it work.

This also causes FilesV2 to use a LOT of memory, as seen in the screenshot below.

![image](https://github.com/files-community/Files/assets/85949613/f3c21253-56e5-4087-9b33-0bf5376dde21)
 
270MB is hardly acceptable memory usage for having 2 tabs open.

### Steps To Reproduce

I'm not able to reproduce it since it happens randomly, but somehow EXACTLY when I need it to function properly.

### Requirements

It shouldn't crash when more than one tab is open.

### Files Version

3.0.5.0

### Windows Version

10.0.19045.3693

### Log File

[debug.log](https://github.com/files-community/Files/files/13377709/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, 270mb is normal usage but we are always try to make performance better and use less system resources.
As you said Files is crashing for you what are you doing when it crashes as it's unlikely caused by having the two tabs open. Are you attempting to open a file, if so what file is it?

**Comment by thisisartman** [comment]
Hi Josh!

> Thanks for the report, 270mb is normal usage but we are always try to make performance better and use less system resources.

Oh. Okay, my bad. It seems pretty high tho... Is it because it's a UWP app?

> As you said Files is crashing for you what are you doing when it crashes as it's unlikely caused by having the two tabs open. Are you attempting to open a file, if so what file is it?

Yeah, any file tbh. I usually have to open Excel files, but even a text file, an MP4 video, etc. Anything can trip it up.

**Comment by Josh65-2201** [comment]
It's a WinAppSDK/WinUI based app. Lot of memory issues come from Microsoft unfortunately. There's a know issue for excel files #13609 but no know cause right now.

**Comment by thisisartman** [comment]
> It's a WinAppSDK/WinUI based app. Lot of memory issues come from Microsoft unfortunately. There's a know issue for excel files #13609 but no know cause right now.

My issue is for almost any file type, not just Excel.

**Comment by yaira2** [comment]
@thisisartman can you see if the file works to open if you run Files as admin?

**Comment by thisisartman** [comment]
@yaira2 I will have to check for a while since I don't know when this will happen.
