### ISSUE TITLE
Search is not working correctly

### ISSUE THREAD

**Issue by OlegPospelov** [files-community/Files#13909]
### Description

1. I have a tab open with a 00 settings folder in it. I need to find it by searching for it. I start typing "settings" and nothing is found. However, if I start typing 00, a suggestion about this folder will pop up. in other words, if I search from characters that are not first, the search will fail. i can record a video if needed.

2. switching between open tabs - there is a delay of about one second. if the tab is the home page, there is no delay. 

### Steps To Reproduce

as described above

### Requirements

It would be nice to fix these problems of course, it's critical. if you need more information - I'm ready to send you everything you need.

### Files Version

3.0.5.0

### Windows Version

10.0.22621.2715

### Log File

[debug.log](https://github.com/files-community/Files/files/13379257/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report,
- Does it work in Windows File Explorer
- Are you sure the search finished (No loading icon on the tab).

**Comment by OlegPospelov** [comment]
1. yes
2. absolutely

I attach a screenshot that illustrates the problem well. 
there are two folders in the folder that contain the name rita. only the folder that starts with rita is highlighted - 00 is not offered. 

![Untitled-1](https://github.com/files-community/Files/assets/151050453/e17066d8-c553-48d6-86ac-b4f171414f19)

**Comment by Josh65-2201** [comment]
Thanks for the information, I've added this to the project board.

**Comment by yaira2** [comment]
@OlegPospelov does it work if you press enter?

**Comment by yaira2** [comment]
@OlegPospelov

**Comment by OlegPospelov** [comment]
@yaira2 Sorry for the delay with answer - 
![01](https://github.com/files-community/Files/assets/151050453/a4b1cb3e-8511-492f-905b-1787feef1699)
![02](https://github.com/files-community/Files/assets/151050453/085c4703-5cae-4ecb-9861-1a981231bf0c)
I just discovered that it depends on the folder and it's very strange. in my working folder it doesn't work in any way, the enter button doesn't help. look, i created a folder 00 tas - it can't be found. the problem is not in Russian, in another folder there are files with funny names and everything is perfectly searchable. i can't understand the pattern.... all folders are on the same disk.

**Comment by Josh65-2201** [comment]
Do you have Files settings > General > Include unindexed items in search results enabled?

**Comment by yaira2** [comment]
@OlegPospelov do you have that location set to be indexed in the Windows indexing settings?

**Comment by OlegPospelov** [comment]
> Do you have Files settings > General > Include unindexed items in search results enabled?

no, it was disabled. But when I enabled this setting, everything worked. bingo! thank you very much!

**Comment by OlegPospelov** [comment]
> @OlegPospelov do you have that location set to be indexed in the Windows indexing settings?

I'm not sure I know about this parameter.

**Comment by yaira2** [comment]
It's an option in the Windows Settings app where you can choose which locations are indexed by Windows.
