### ISSUE TITLE
`~` to reach the home folder `C:\Users\username` faster & scripts

### ISSUE THREAD

**Issue by Marin-Kitagawa** [files-community/Files#13903]
### What feature or improvement do you think would benefit Files?

Right now, unless pinned in Quick Access, it is not that easy to access the `%userprofile%` folder. Now, when I type `~` in the address bar of files, I get the below error:

<img width="269" alt="image" src="https://github.com/files-community/Files/assets/49131888/2767dcf7-67ca-4061-80fa-67ea77c2b6cb">

Sure, I can press `Win` key and click on the personal folder (fourth from the left in the belwo image) to directly open it. But it opens in File Explorer and not Files. So, this small addition would be a nice addition to the files. It is easier to Press `Ctrl+L`, then type `~` and press Enter. 

Also, I am aware that `~` is a special sign. That is, for eg., whenever you open a document, a temporary file will be created which will be prefixed with `~` which is like a lock file or backup file which can be used to restore (recover) the file later if needed. There may be other use cases. So, if this proposal doesn't conflict with the other use cases, you shall implement this. It need not be `~`, it can be any other non-conflicting symbol as well. Or there could be a shortcut in Files to go to that directory

Or if Files supports scripting, we can leverage them to create shortcuts, automate tasks and so on

### Requirements

This proposal will allow users to reach the personal folder (`%userprofile%`) faster using the `~` in the address bar

### Files Version

3.0.5.0

### Windows Version

10.0.22631.2715

**Comment by Josh65-2201** [comment]
Thanks for the feedback, This will properly be possible when #13251 is implemented. You can check there or click subscribe in the right sidebar for updates.
