### ISSUE TITLE
Copy/cut and paste a file to pc from a extral hard not working

### ISSUE THREAD

**Issue by deadlywhitesong** [files-community/Files#13910]
### Description

tryed to move folder not working

### Steps To Reproduce

unstalling it and reall the program still not working

### Requirements

- e.g. Fix crash that occurs when...
it also crashes on one single click for it

Edition	Windows 11 Pro
Version	23H2
OS build	22635.2700
64 gb of ram

### Files Version

3.0.5.0

### Windows Version

22635.2700

### Log File

their no log in windows 11

**Comment by Josh65-2201** [comment]
Thanks for the report,
- Can you upload (Do not copy and paste content) the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.
- Can you add the steps to reproduce. Like where your copying to and from, the file, any errors you see.

**Comment by deadlywhitesong** [comment]
their is no settings > About > Open log folder. in windows 11 

i was moving folder  from desktop to my external hard

**Comment by Josh65-2201** [comment]
In Files settings not Windows

**Comment by deadlywhitesong** [comment]
[debug.log](https://github.com/files-community/Files/files/13380759/debug.log)

**Comment by deadlywhitesong** [comment]
sorry

**Comment by deadlywhitesong** [comment]
i need to be able to move folders from desk to extranal hard its only let copy not move it

**Comment by yaira2** [comment]
@deadlywhitesong can you clarify the steps to repro this? Make sure to specify how you're copying the item (toolbar button, keyboard shortcut, context menu etc).

**Comment by yaira2** [comment]
@deadlywhitesong
