### ISSUE TITLE
Interface

### ISSUE THREAD

**Issue by pablo-hp** [files-community/Files#13913]
### What feature or improvement do you think would benefit Files?

First of all, I would like to congratulate you on making Files better every day. 
It is without a doubt an excellent application. 
I would like to suggest an improvement to make it even better than it already is. 
In the current version, 3.0.5.0, in the top right corner there are 3 dots with the following options: "new panel, new window, compact overlay".

I would like to request that you leave these 3 options visible, instead of leaving these options within a context menu, since I use these 3 options a lot and they are always hidden in the context menu, somewhat hindering the experience and usability of the application.

Thank you ever since for the excellent application and never stop perfecting or improving what already exists. 
Grateful.

### Requirements

Visibility of context menu options.

### Files Version

3.0.5.0

### Windows Version

Windows 11  22H2

### Comments

![Captura de tela 2023-11-16 154423](https://github.com/files-community/Files/assets/34690165/5d870c0f-451c-49b6-878d-268516c41990)

**Comment by pablo-hp** [comment]
![image (2)](https://github.com/files-community/Files/assets/34690165/21b5f779-e70f-42a5-89ca-ebda43c4e89f)
Small suggestion that can be improved.

**Comment by yaira2** [comment]
Thank you for your kind feedback, we'll keep working on improvements and updates. While we don't have plans to move to move these into the main toolbar area, I want to make sure you're aware of the keyboard shortcuts for those options.
1. Open New Window - `Ctrl + N`
2. Compact Overlay - `Ctrl + Alt + Up` and `Ctrl + Alt + Down`
3. New Pane
    Open selected folder in new pane - `Ctrl + Shift + Enter`
    Open new pane - `Alt + Shift + Plus`
    Close right pane - `Ctrl + Shift + W`

**Comment by yaira2** [comment]
We haven't ruled out a dedicated button for dual pane, but we'd like to make some improvements to the general dual pane experience before moving forward with it.
