### ISSUE TITLE
Context menu not displaying antivirus for file or folder scanning

### ISSUE THREAD

**Issue by jayinpr** [files-community/Files#13917]
### Description

The context menu is not showing the installed antivirus for quick scanning of files and folders. Normally in file explorer if you have Bitdefender or another antivirus installed, there will be an item in the context menu so that you can right-click and scan a file or folder easily.

### Steps To Reproduce

Right click any file or folder.
You will see that there is no menu item for scanning with installed antivirus.

### Requirements

This should be recognized automatically or for now address how we can incorporate this functionality manually by ourselves.

### Files Version

3.0.5.0

### Windows Version

Windows 11 Pro 23H2 Windows Feature Experience Pack 1000.22677.1000.0

### Log File

[debug.log](https://github.com/files-community/Files/files/13383099/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report. Last known it was an issue with bit defender and how it add shell options as said here https://github.com/files-community/Files/issues/10866#issuecomment-1485743785
