### ISSUE TITLE
Additional Columns in Details view (especially for audio files and images)

### ISSUE THREAD

**Issue by developer-controls** [files-community/Files#13918]
### What feature or improvement do you think would benefit Files?

Currently, Files only provides a few columns in Details view (Tag, Size, Type, Date). This renders Files relatively useless for any file types other than documents. For audio files (whether music or podcast/narration), we need Length, Bitrate, Track #, etc. For images we need Date Taken. And so on. 

Please make all the properties that can be shown in Windows File Explorer available in the Detailed view in Files.

Allow for standard selections on Folders and Subfolders so users can specify, for example, this folder and all subfolders will be used for audio files and show the Details columns associated with that folder type.

### Requirements

The full list of possible Detail columns can be found in Windows File Explorer by right-clicking on any column heading and select "More..." All of these Details should be available for columns in Files too, along with improvements on which folders contain which kinds of files (so that Music/Audio folders show different Details columns than images or documents or downloads). 

Please add all of these, or at least the most commonly used subset, to Files.

Specifically, for audio, I know that I also need at least Album, Album Artist, Bit rate, Length, Title, and #. And by default I sort on # (the track #).

### Files Version

3.0.5.0

### Windows Version

Windows 11 22H2, OS Build 22621.2715

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #8366. You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
This is on our todo list, please subscribe to #8366 to be notified when it's addressed.
