### ISSUE TITLE
Bug: Path bar isn't updating to tabs current path

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#13928]
### Description

When changing the tab the pervious tab path will be shown on all of them. There also the tab previews braking which im not sure if there related
![image](https://github.com/files-community/Files/assets/26977075/f8376914-b7a6-48fb-9be6-ffbe702b6075)

### Steps To Reproduce

1. Open some tabs
2. Go to different paths
3. Switch between other tabs
4. See the last loaded tabs path on all tabs

### Requirements

- Update paths to current tabs directory

### Files Version

3.0.6.0

### Windows Version

10.0.22621.2506

### Log File

[debug.log](https://github.com/files-community/Files/files/13391225/debug.log)

**Comment by yaira2** [comment]
@0x5bfa

**Comment by yaira2** [comment]
@0x5bfa I reverted the changes for now, but this should be addressed so that we can merge them back into `main`.
