### ISSUE TITLE
Bug: Don't install all selected fonts at once

### ISSUE THREAD

**Issue by ggtylerr** [files-community/Files#13922]
### Description

When installing multiple fonts, it should not try and install it at all once. Doing this with a large amount of fonts (e.g. with GH's monaspace) causes a couple hundred PS threads to launch, slowing down the system to a crawl.
![A screenshot of btop showing the CPU at max usage with a lot of powershell copy-item commands](https://github.com/files-community/Files/assets/28498877/b9d5b91f-1489-439b-a3b1-b08e7f462717)

### Steps To Reproduce

1. Download a large list of fonts to install.
    - A good example is [GH next's monaspace family, specifically their otf files.](https://github.com/githubnext/monaspace)
2. Select them all in files and press install
3. Watch as your computer explodes

### Requirements

- Don't launch 200 copy-item commands at once.
  - Probably can do one at time, or at most 5-10.
  - Possibly add a progress meter in the status center.

### Files Version

3.0.5.0

### Windows Version

10.0.22621.2428

### Log File

(it crashed and reopened files automatically when I did this, causing the log to wipe)

**Comment by yaira2** [comment]
@ggtylerr can you try to repro one more time to try and get the log file?

**Comment by ggtylerr** [comment]
Had to torture my computer a second time but here. I don't see anything relating to the font files here unfortunately.
[debug.log](https://github.com/files-community/Files/files/13385804/debug.log)

**Comment by yaira2** [comment]
Either way, the crash is probably caused by all the running processes.
