### ISSUE TITLE
Bug: Clicking on home page in sidebar crashes Files

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#13926]
### Description

*

### Steps To Reproduce

1. Click any folder/item on home page
2. Click home page in sidebar
3. See crash

### Requirements

- Load home page

### Files Version

3.0.6.0

### Windows Version

10.22621.2506

### Log File

[debug.log](https://github.com/files-community/Files/files/13391126/debug.log)

**Comment by 0x5bfa** [comment]
I cannot repro this issue.

**Comment by yaira2** [comment]
@Josh65-2201 is this consistent?

**Comment by Josh65-2201** [comment]
For me, yes

**Comment by yaira2** [comment]
Thanks! I reverted the changes that caused this issue.
