### ISSUE TITLE
Theme color doesnt apply to access denied dialog

### ISSUE THREAD

**Issue by Infraction7** [files-community/Files#13927]
### Description

![Files_NxFjCcCkOz](https://github.com/files-community/Files/assets/112822467/309e63dd-0160-412e-8dc0-237974129411)
The selected theme color override doesnt apply to access denied dialog. May also happen to other dialogs (didnt checked)

### Steps To Reproduce

1. Override theme color in settings.
2. Get the dialog.

### Requirements

Fix theme not applying to dialogs.

### Files Version

3.0.1.0

### Windows Version

Windows 10 Pro Release Version 21H2 | OS Build 19044.3086

### Log File

[debug.log](https://github.com/files-community/Files/files/13391151/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
This is currently by design, would you mind opening a separate issue using the feature request template so that we can track feedback from other users?
