### ISSUE TITLE
Preview (thumbnails) enabled, but png and jpg files not showing thumbnails

### ISSUE THREAD

**Issue by HamishRM** [files-community/Files#13931]
### Description

Installed and checked settings, but thumbnails not showing

### Steps To Reproduce

Newly installed

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.0.5.0

### Windows Version

10.0.22621.2715

### Log File

No log

**Comment by Josh65-2201** [comment]
Thanks for the report, you need a program that supports making thumbnails for those file types.

**Comment by yaira2** [comment]
1. Are the images located in OneDrive?
2. What program is set as the default application for those files?
3. Do the icons show in File Explorer?

**Comment by HamishRM** [comment]
Rebooted, reinstalled and it seemed to pickup and show thumbnails. Was odd that it didn't happen first-time, but seems ok now.
