### ISSUE TITLE
Add Compact View like in Windows Explorer

### ISSUE THREAD

**Issue by drfdr** [files-community/Files#13937]
### What feature or improvement do you think would benefit Files?

Look how thick they are and how much of an unnecessary space single file takes. 

![files1](https://github.com/files-community/Files/assets/5204839/3f2c32ef-838a-4308-90c4-26983721feb5)

### Requirements

Add Compact View like in Windows Explorer or even option for settings custom file Height

### Files Version

3.0.5

### Windows Version

Windows 11 22H2

**Comment by Josh65-2201** [comment]
Thanks for the feedback there is already a compact view in Files settings > Appearance > Use compact spacing in the details layout.
