### ISSUE TITLE
Add "Extract here (Smart)" to the context menu

### ISSUE THREAD

**Issue by parfait8566** [files-community/Files#13933]
### Requirements

Most people just want to extract their archive files to a folder if it contains multiple files/subfolders or just in the current directory if it's a single file/folder. This would make it much easier and faster.

- Add option to the extraction menu for "Smart extract"
- If there is only one file directly under the archive's root (same behavior as "Extract here").
- If there is only one directory directly under the archive's root, the directory will be extracted into the current working directory (same behavior as "Extract here")..
- Otherwise, all contents of the archive are extracted into a new directory named by the archive's stem (stem means the file name without the extension. (same behavior as "extract to \")

### Files Version

3.0.8.0

### Windows Version

10.0.22624.2361

**Comment by yaira2** [comment]
@parfait8566 thanks for the feedback, are you aware that you can already choose whether to extract the items to the current directory or not?

**Comment by parfait8566** [comment]
> @parfait8566 thanks for the feedback, are you aware that you can already choose whether to extract the items to the current directory or not?

Taken from here: https://sourceforge.net/p/sevenzip/discussion/45797/thread/cf0294d4/

> Basically, when you download an archive and want to extract it, there are 4 possibilities:
> 
> - archive root contains 1 file, you extract it here
> - archive root contains 1 file, you extract it to a subfolder
> - archive root contains multiple files, you extract it here
> - archive root contains multiple files, you extract to a subfolder
> 
> Half of those are exactly what we want: a single file right here and multiple files in a subfolder. The other half however is what we don't want: an excessive folder or a frag grenade of files.
> 
> To avoid the latter situations, we need to open any archive before extracting it and see if the root contains multiple files, then finally extract it afterwards. This has been bugging me and others forever.
> 
> "Smart extraction" would be an additional extraction option, toggleable via the settings just like the other extraction options, so that it doesn't get in the way of people who don't want it.
> 
> What it does is the following (refer to above):
> 
> - extract it here
> - extract it here
> - extract it to a subfolder
> - extract it to a subfolder
> 
> [T]he number of files could be configurable too. Default to 1 and let people increase it as they wish.
> 
> [S]mart extraction would not only be an option on the ["Extract to"] screen, but also in the context menu

**Comment by yaira2** [comment]
@parfait8566 this is already supported, you can choose between
- extract here
- extract to \
- extract to different location

**Comment by parfait8566** [comment]
> @parfait8566 this is already supported, you can choose between
> 
> * extract here
> * extract to \
> * extract to different location

Sorry, I should have been more clear. "Smart extraction" would do this for you automatically without having to open the archive.
You can see a few threads discussing this feature for NanaZip as well: https://github.com/M2Team/NanaZip/issues?q=is%3Aissue+smart

To elaborate a bit, clicking this new "Extract here (Smart)" option in the context menu would do the following:
- if the archive root contains 1 folder or file, extract here
- if the archive contains multiple files or folders, extract them to a new subfolder here

This is what most people want when extracting, but to do it they have to open the archive (otherwise they would lose track of the different files or end up creating subfolders for nothing).
It's also macOS' behavior when double-clicking an archive file. I think it'd be helpful and make extracting archives more brainless and smooth.

**Comment by yaira2** [comment]
Thanks for clarifying
