### ISSUE TITLE
no update size of drives

### ISSUE THREAD

**Issue by meemore** [files-community/Files#13934]
### Description

![Screenshot_1](https://github.com/files-community/Files/assets/124497263/c216024f-56dd-437b-a468-ebbb8414df34)

### Steps To Reproduce

speed

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.0.5.0

### Windows Version

10.0.22621.2715

### Log File

wont update drive sizes

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #6182. You can check there or click subscribe in the right sidebar for updates.
