### ISSUE TITLE
Add Proton Drive to Cloud Drives section - How?

### ISSUE THREAD

**Issue by rafikiphoto** [files-community/Files#13939]
### What feature or improvement do you think would benefit Files?

Is there a way I can add my Proton Drive folder to the Cloud Drives section?

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.5.21.0

### Windows Version

Windows 11 Pro 23H2

**Comment by Josh65-2201** [comment]
You install and setup the proton client then restart Files.

**Comment by rafikiphoto** [comment]
Thanks.

Proton Drive was already installed but not showing up in the Cloud Drive section. I tried uninstalling it and reinstalling then restarting Files but it's still a no-show.

B.

------ Original Message ------
From "Josh65-2201" ***@***.***>
To "files-community/Files" ***@***.***>
Cc "rafikiphoto" ***@***.***>; "Author" ***@***.***>
Date 18/11/2023 20:08:30
Subject Re: [files-community/Files] Add Proton Drive to Cloud Drives section - How? (Issue #13939)

**Comment by rafikiphoto** [comment]
Belay that. I just installed Files v3x and Proton Drive is there.

B.

------ Original Message ------
From "Brian Davies" ***@***.***>
To "files-community/Files" ***@***.***>
Date 19/11/2023 06:55:34
Subject Re[2]: [files-community/Files] Add Proton Drive to Cloud Drives section - How? (Issue #13939)
