### ISSUE TITLE
Bug: Selected files still got marked but not selected after being draged

### ISSUE THREAD

**Issue by leafpmpmp** [files-community/Files#13935]
### Description

When I select a file, drag it to another app then back to here, the file is no longer selected, but the blue mark on the left still exist.
<img width="872" alt="image" src="https://github.com/files-community/Files/assets/49824741/e46baee4-cef0-4eb4-944c-30794d0b3f00">

### Steps To Reproduce

1. select a file (or a few)
2. drag it whether to another app or just around in the same directory.
3. now that the file is automatically de-selected, but the mark does no disappear.

### Requirements

Take the deault file explorer as reference, the file should not be de-selected after being draged around.

### Files Version

3.0.8

### Windows Version

10.0.22631.2715

### Log File

[debug.log](https://github.com/files-community/Files/files/13399951/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Are you certain they are not copied/move when you let go of the drag?

**Comment by yaira2** [comment]
This is indeed an issue with the WinUI control and is being tracked in #11151.
