### ISSUE TITLE
How to open a directory tree

### ISSUE THREAD

**Issue by Suhebing** [files-community/Files#13948]
### What feature or improvement do you think would benefit Files?

Unable to find the directory tree. How can I turn on the directory tree function

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.0.5.0

### Windows Version

10.0.22000.2538

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #1928. You can check there or click subscribe in the right sidebar for updates.

There isn't one currently and it being disused on how it will be added.

**Comment by yaira2** [comment]
We're actively looking into this (tracking in #1928) but there are some memory issues that need to be worked out first.

**Comment by yair100** [comment]
@Suhebing Tree View is currently available in preview https://files.community/download. It will be included in the next stable release.
