### ISSUE TITLE
opening compressed file

### ISSUE THREAD

**Issue by Fokpi** [files-community/Files#13940]
### Description

Opening a compressed file outside of Files or desktop doesn't work, like you can't open when clicking directly on the download from browser you need to go inside Files

### Steps To Reproduce

1. Download a zip or a rar
2. Wait it to be downloaded
3. Try to open from browser

### Requirements

Make sure the zip can be opened from a browser

### Files Version

3.0.5.0

### Windows Version

22635.2771

### Log File

There is no log since files doesn't detect zip file

**Comment by Josh65-2201** [comment]
Thanks for the report, 
- Do you have Files set as default in Files settings?
- Do you have Files set as default to open zip files?
- What browser are you using?

**Comment by Fokpi** [comment]
Sorry for the delay, I wanted to let you know that the problem seems to be solved, I think the problem came from edge or something like that, thank you for your work and have a good day!
