### ISSUE TITLE
Dual Pane Switch (Vertical - Horizontal)

### ISSUE THREAD

**Issue by Wolfgodie** [files-community/Files#13943]
### What feature or improvement do you think would benefit Files?

This is one of my favorite features to see in the new files app. Having a dual pane is certainly a good feature to have especially when used in combination with colunm view. This works well until when you have to use the preview pane as well then space becomes a problem. It'd be nice if the dual pane could have a button to switch from Vertical to Horizontal and vice versa. 

This will create more space for horizontal column navigation whilst at the same time having the space to preview files on the preview panel. Moreover, if users are be able to save workspaces, this would certainly make files app more productive compared to other file managers out there.

### Requirements

- This proposal will need a Pane Button next to the preview button that will enable users to switch dual panes from vertical to horizontal.
- This proposal needs to have a settings option for users to be able to save different workspaces either by remembering the last active view of the explorer or by reverting to the default view upon relaunching the app.

### Files Version

3.0.5.0

### Windows Version

10.0.22631.2715

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #12427. You can check there or click subscribe in the right sidebar for updates.
