### ISSUE TITLE
Bug: DirectoryNotFoundException in PinToStartAction

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#13947]
### Description

System.IO.DirectoryNotFoundException: Attempted to access a path that is not on the disk.

### Steps To Reproduce

1. Use the pin to start action
2. App crashes

### Requirements

- Fix crash

### Files Version

v3.0.8

### Windows Version

Windows 11

### Log File

Files.App.Storage.NativeStorage
NativeStorageService.GetFolderAsync (String id, CancellationToken cancellationToken)
Files.App.Actions
PinToStartAction.ExecuteAsync ()
Files.App.Data.Commands.CommandManager
ActionCommand.Execute (Object parameter)
System.Threading.Tasks.Task
<>c.<ThrowAsync>b__128_0 (Object state)
WinRT
ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0 (Int32 hr)
ABI.Windows.ApplicationModel.Core
IUnhandledErrorMethods.Propagate (IObjectReference _obj)
Microsoft.AppCenter.Utils
ApplicationLifecycleHelperWinUI.<ctor>b__0_3 (Object sender, UnhandledErrorDetectedEventArgs eventArgs)

**Comment by d2dyno1** [comment]
:eyes:
