### ISSUE TITLE
Feature: Different background colour for each pane

### ISSUE THREAD

**Issue by jockstersi** [files-community/Files#13949]
### What feature or improvement do you think would benefit Files?

Having a user configurable different background color for each pane when multi panes are open at the same would make it easier for the user to see which pane they are in. Would be a clearer indication than the current scroll bar at the bottom.

### Requirements

- This proposal will accomplish user configurable background color for each pane when multiple panes displayed

### Files Version

3.0.5.0

### Windows Version

Windows 11 Pro 23H2

**Comment by Josh65-2201** [comment]
Thanks for the feedback, I've added this to the project board.

**Comment by yaira2** [comment]
Thanks for the feedback

**Comment by yaira2** [comment]
Thank you for your feedback. We don't have plans to support separate colors for each pane, but we're working to make the panes more distinct.

Our eventual goal is to make each pane "floating" with a distinct border on all sides.
![image](https://github.com/files-community/Files/assets/39923744/bd983509-6238-42bf-8399-68bcd98fc6fc)
