### ISSUE TITLE
Silent Preload Startup

### ISSUE THREAD

**Issue by D-Maxwell** [files-community/Files#13944]
### What feature or improvement do you think would benefit Files?

The newly added background service allows for much quicker app "launches", as all that is then required is to show a window rather than load the entire app ; however, it still requires a manual launch after every cold boot, which takes a bit of time to load.

There is an autostart option, however it seems to open a Files window instance as well.

I wish there were a way to preload the app, so that it still feels as snappy, although without explicitly showing a window, making the replacement of the default file manager seamless and just as fast.

### Requirements

Perhaps the default behaviour of the in-app autostart option could be modified accordingly, resulting in a background soft preload that doesn't involve the creation of a window ; this would leave the previous behaviour to the task manager startup entry, which I feel would make for a more consistent experience, inline with other MSWin applications.

Alternatively, yet another field could be added to the settings, which may be clearer to the end user ; although I fear this would clutter the UI a tad too much.

### Files Version

3.0.8.0

### Windows Version

10.0.19045.2788

**Comment by yaira2** [comment]
Thanks for the feedback, we're tracking this feature request in #13510.
