### ISSUE TITLE
Can you add a rename option for "Home"?

### ISSUE THREAD

**Issue by RemixPL1994** [files-community/Files#13953]
### What feature or improvement do you think would benefit Files?

Can you add a rename option for "Home"?

I would like to name "Home" as the name "This Computer" / "My Computer"

Currently I cannot do this.

Adding this option would be very helpful for me.

### Requirements

- Possibility to change "Home" to your own entered name

### Files Version

v3.0.8

### Windows Version

19045.3693

### Comments

![obraz](https://github.com/files-community/Files/assets/52541621/a175e650-4574-4306-b2e6-91933ee93292)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, What is your reason for wanting this has it doesn't have any real benefit to add?

**Comment by yaira2** [comment]
We don't have plans to change the name of the home page, but perhaps you'll like this even more
1. Enter `shell:::{20D04FE0-3AEA-1069-A2D8-08002B30309D}` into the address bar and press enter
2. Right click in the folder to pin to favorites
3. Change the layout mode to tiles
4. Right click and select "group by type"

Please let me know how it goes

**Comment by yaira2** [comment]
@RemixPL1994 did you try those steps

**Comment by yaira2** [comment]
Thanks for the feedback, at the moment we don't have plans to make this change, but we'll keep gathering feedback to gauge user interest.
