### ISSUE TITLE
Can you add the option to add bookmarks and their quick shortcuts?

### ISSUE THREAD

**Issue by RemixPL1994** [files-community/Files#13952]
### What feature or improvement do you think would benefit Files?

Can you add the option to add bookmarks and their quick shortcuts to open at the top of the explorer like in browsers?

I used to use Clover, which enabled this, but it has been out of development and no stable for Windows 10 for a long time and I had to abandon it.

Author's website: http://cn.ejie.me/

I would like Files.preview to be my default file explorer and every time I open "My Computer" "This Computer" only one tab would open as "Home" and it would not load or open other tabs from previous sessions but so that I could every time I open the home page, there are ready-made tabs and shortcuts at the top (with the option of changing the name) where I will be able to quickly move between them thanks to the fact that they will be ready, saved and always available to me after opening permanently.

### Requirements

- Ability to add bookmarks
- Possibility to change the names of added bookmarks
- Possibility to freely manually set the order in which tabs are displayed on the top bar

### Files Version

v3.0.8

### Windows Version

19045.3693

### Comments

If you reply that you need screenshots to show what it should look like, I will take them and send them.

If my description and message request are incomprehensible, let me know.

I will then send you screenshots showing what is going on.

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #6458. You can check there or click subscribe in the right sidebar for updates.

**Comment by Josh65-2201** [comment]
Right now you can use the tags feature to make this and middle click the sidebar or home page widget to have them open the folders in new tabs.
