### ISSUE TITLE
Feature: Context menu is slow

### ISSUE THREAD

**Issue by NoxArt** [files-community/Files#13957]
### What feature or improvement do you think would benefit Files?

When I right click to open context menu, it takes time to appear. When I then right click elsewhere it takes time for the old menu to disappear

### Requirements

- Speed up loading / responsiveness of context menu

### Files Version

3.0.5.0

### Windows Version

10.0.22621.2715

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
@NoxArt can you share a screen recording?

**Comment by yaira2** [comment]
@NoxArt can you also confirm what you have set for "display shell extensions in the sub menu"?

**Comment by NoxArt** [comment]
Yes, I should be able to provide the info later today, thank you

**Comment by parfait8566** [comment]
I can confirm it's a bit slow on my end as well

https://github.com/files-community/Files/assets/146892521/a2d9e14d-7273-4512-ab3d-1efc9dd8ee0b

**Comment by yaira2** [comment]
@parfait8566 loading shell extensions can take a bit of time, we recommend moving them into the sub menu for better performance.

**Comment by NoxArt** [comment]
Hello, sorry for late response. Today when I went to record it it suddenly isn't as bad as before, weird

https://github.com/files-community/Files/assets/291595/1e23a427-bdcf-4213-be2f-28168f154bfc

**Comment by yaira2** [comment]
We'll continue working on optimizations of course, but it mainly depends on how many shell extensions are on your device. Merging with #4180.

**Comment by yaira2** [comment]
More specifically, we're tracking context menu performance in #11112.
