### ISSUE TITLE
Add all options for "Conflicting file name(s)" in one menu

### ISSUE THREAD

**Issue by parfait8566** [files-community/Files#13956]
### What feature or improvement do you think would benefit Files?

Currently, if you have have a conflicting file, you will get this:
![image](https://github.com/files-community/Files/assets/146892521/b85724fb-f57b-4f4f-bd2b-e61e374e41ca)

If you wanted to replace the file, now you'll have to select "Replace" in the options and then "Continue" (also, I think the yellow text stands out a bit and doesn't look very nice).

Here is File Explorer's popup:
![image](https://github.com/files-community/Files/assets/146892521/f358857e-508b-4ea9-abc6-f6a39b4b2909)

Replacing the file is just one click away.

### Requirements

I think there should be new one-click-away options like File Explorer's, like "Replace all" or "Generate new name for all" to make the process easier and smoother.

### Files Version

3.0.8.0

### Windows Version

10.0.22624.2361

**Comment by Josh65-2201** [comment]
Thanks for the feedback, since Files lets you set them specifically for items also, having a another button with the options doesn't really work and is confusing. Files does save the last used option though so you can just click continue.

**Comment by yaira2** [comment]
To add to what Josh shared, the conflicts menu will remember the last selected option so assuming you want to use the same option, you can just click continue in the future.
