### ISSUE TITLE
Can you provide more options for changing the appearance and personalization of the "home page"?

### ISSUE THREAD

**Issue by RemixPL1994** [files-community/Files#13955]
### What feature or improvement do you think would benefit Files?

Can you provide more options for changing the appearance and personalization of the "home page"?

I would like to adapt it so that together with Files - Preview it would look the same / similar as it currently does on the original explorer, i.e.:

- larger bars to show disk usage
- the bars have different colors depending on the disk space

- on the left side under "Home" showing for me the Desktop and disks one below the other without categories for Favorites and Disks

I would like to just have it all displayed one under the other as a whole.

### Requirements

- Possibility to adjust the size of the disk usage bar icon
- Possibility to adjust the color of the disk usage bar icon
- Possibility to show icons for Desktop on the left side, disks as a whole side by side, immediately under "Home Page"

Currently this is separated into separate "Favorites" and "Drives" sections

I would like to have it the old way, just like I learned at home. ( screenshot )

### Files Version

v3.0.8

### Windows Version

19045.3693

### Comments

![obraz](https://github.com/files-community/Files/assets/52541621/28cfefc3-9eba-4892-9275-c3d8a48bf15b)

**Comment by yaira2** [comment]
Thank you for your feedback, this goes beyond the scope of what we plan to offer in Files (please see my comment in your other feature request about our approach to customization).
