### ISSUE TITLE
Bug: Microsoft Photos doesn't display Filmstrip of images in folder

### ISSUE THREAD

**Issue by teribol** [files-community/Files#13951]
### Description

This is not really a bug but an issue when another app is fired up inside Files. Photos (microsoft app) is not able to display Filmstrip of other photos in the folder when one of them is clicked for viewing. Also the navigating arrows (on the right and left (middle) sides are not displayed.  Photos will only show the photo that is being viewed. When I do this in the native File Explorer, Photos is able to display Filmstrip and navigate over all the photos in the folder.

### Steps To Reproduce

1. Open files
2. Navigate to a folder with multiple photos in it.
3. Make your default photo viewer be Windows Photo app.
4. Click on any picture.
5. On the Photos app, the navigating arrows on the left and right sides are not displayed.
6. When the Show Filmstrip (lower bottom most) icon is clicked, only the icon of the picture being viewed is displayed.

### Requirements

- navigating arrows must be displayed
- Filmstrip should show the icons of all the photos in the folder

### Files Version

3.0.5.0

### Windows Version

Windows 11 Insider Preview (build 25992)

### Log File

N/A

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
I'm having trouble reproducing this, by any chance, are the images located in OneDrive and are the downloaded to the device?

**Comment by teribol** [comment]
Hi.

I also tried viewing a group of pictures in other folders and Photos behaved as it should be but in this particular folder, I don't know why Photos is not able to display the group in the Filmstrip and also display the navigation arrow icons.

Let me show you images of the particular issue hoping it may help:

this picture shows Files displaying the folder in question (pls take note of the 4 folders and 5 photos):
![files photos 1](https://github.com/files-community/Files/assets/7020894/1be941a1-c853-479a-b04f-a694dfcdeb29)

this picture shows Photos displaying the photo I clicked on (pls take note of the absence of the nav arrow icons on both sides)
![files photos 3b](https://github.com/files-community/Files/assets/7020894/9a8d0976-e738-433e-b93e-752d923d48aa)

this picture shows the Filmstrip when I clicked on the Show Filmstrip icon (pls take note that only one photo thumbnail is shown)
![files photos 4b](https://github.com/files-community/Files/assets/7020894/01923394-950c-492a-bead-4e9612c41149)

Sorry to bother you if this is a Photos app problem (I used the native File Explorer viewing this folder in question, clicked on a photo and Photos behaved like it should - no problem)

**Comment by yaira2** [comment]
@teribol what happens if you select multiple photos and open them together?

**Comment by teribol** [comment]
Hi.

Result of selecting multiple photos (using Files) and viewing them on Photos (the last one of the selected photos is displayed in Photos but only one photo icon shown in the Filmstrip and still no navigation arrow icons on both sides:
![files photos 5b](https://github.com/files-community/Files/assets/7020894/0a896950-42bb-49db-8e88-ad89187d0e18)

**Comment by yaira2** [comment]
Is the behavior the same for pngs?

**Comment by teribol** [comment]
those are pngs

below pictures are for same folder but using native File Explorer:
![files photos 6b](https://github.com/files-community/Files/assets/7020894/a37064d2-947d-4dd5-b519-cfb3088fcb18)

![files photos 7b](https://github.com/files-community/Files/assets/7020894/1777708d-abe3-4ec7-831d-1810cba18488)

**Comment by teribol** [comment]
I think it must be a Photos problem. I copied the photos to another folder, clicked on one and Photos behaved like it should.

**Comment by teribol** [comment]
I copied the photos to another folder and Photos now behaving like it should:
![files photos 8](https://github.com/files-community/Files/assets/7020894/d02edfe2-7567-4c61-a962-4fa0675f2546)

**Comment by yaira2** [comment]
It could be a permissions issue with that location, can you report this issue in the Feedback Hub?

**Comment by hairama** [comment]
I thought I was having the same issue--but turns out I was looking at photos in a folder that was still zipped. When I opened the folder where the files were extracted, I didn't have the issue.

Putting this here in case anyone else goes looking for an answer.
