### ISSUE TITLE
Files crashes when dragging a file to the taskbar

### ISSUE THREAD

**Issue by dreamsynth** [files-community/Files#13950]
### Description

When you try to drag and drop a file into the browser (or other app) on the taskbar, the application crashes.

https://github.com/files-community/Files/assets/84819091/41e9ae1c-81f4-4efd-8b99-9f1a6c1be700

### Steps To Reproduce

1. Try drag and drop the file to the taskbar
2. App crashes

### Requirements

Fix crash

### Files Version

v3.0.8

### Windows Version

Windows 11 23H2 (22631.2715)

### Log File

[debug.log](https://github.com/files-community/Files/files/13402943/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Can you confirm this is only an issue with the grid layout.

**Comment by dreamsynth** [comment]
Yes, it only happens in the grid layout

**Comment by yaira2** [comment]
We're going to continue tracking in #11149. You can comment or click subscribe in that issue to be notified when it's fixed.
