### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by RemixPL1994** [files-community/Files#13965]
### What feature or improvement do you think would benefit Files?

Two questions:

1. How can I get the original windows default explorer font in the new explorer?

I would like the font and size to be the same.

2. How to turn off the selection squares on the left?

![obraz](https://github.com/files-community/Files/assets/52541621/fbe7cacb-316b-47cc-914e-bd35ad098986)

![obraz](https://github.com/files-community/Files/assets/52541621/6768b71b-5d48-4a07-b9ca-41f32a20f9de)

### Requirements

.

### Files Version

v3.0.8

### Windows Version

19045.3693

**Comment by yaira2** [comment]
> How can I get the original windows default explorer font in the new explorer?

See the documentation on custom themes for how to change the font https://files.community/docs/configuring/custom-themes

**Comment by yaira2** [comment]
Hovering directly over the thumbnail will always show the checkbox. The setting only controls hovering/clicking items.

**Comment by Josh65-2201** [comment]
There isn't a way of turning it off completely but since it only shows when overing over the icon you can just not hover over it.

**Comment by Josh65-2201** [comment]
Adding settings and features isn't always simple and Files development team is quite small so features/changes need to have a lot of user on board with it or a good reason to make.

Adding options for everything also isn't possible and Files is not Windows File Explorer nor is it trying to copy it completely.

**Comment by yaira2** [comment]
> I wonder why this was added if the original explorer didn't have it?

@RemixPL1994 Files is a very different app than File Explorer, there are a lot of similarities but this is one area where we decided to take a different approach.

**Comment by yaira2** [comment]
We're happy to have similar behaviors where it makes sense, but we certainly don't plan to have a 1:1 match with other applications.

**Comment by yaira2** [comment]
Thanks for the feedback, we value your feedback, but we would like to share our perspective. Some of the feature requests that we have received are requesting that we do everything the same as File Explorer with the reasoning that “more options are better”. We agree that options are good, and we aim to offer a reasonable amount of flexibility in allowing users to customize different behaviors, however, there is a balance between offering options that add value for the broader userbase vs only catering to a niche audience. Too many options make it harder for regular users to find different settings, they increase the risk of errors and bugs, and they can also be overwhelming. We know this isn't the exact response you were hoping for, but we hope this clears up our approach on customization.
