### ISSUE TITLE
Can I set the number of elements and their selected items to also appear on the home page?

### ISSUE THREAD

**Issue by RemixPL1994** [files-community/Files#13966]
### What feature or improvement do you think would benefit Files?

Can I set the number of elements and their selected items to also appear on the home page?

![obraz](https://github.com/files-community/Files/assets/52541621/fea1c235-9187-4f6c-a062-126e775b71d7)

And is it possible for this information to appear on the left side as in the original explorer instead of in the middle, taking up the working part of the displayed directories?

### Requirements

.

### Files Version

v3.0.8

### Windows Version

19045.3693

**Comment by Josh65-2201** [comment]
Thanks for the feedback, There isn't a way of making the status bar go over the sidebar, What reason would you want to see a number of elements on the home page?

**Comment by Josh65-2201** [comment]
Selecting items does show it on the status bar. Since you can't select/copy anything on the home page there is no reason to show it. The status bar is also big enough to show this information with it current size.

> after clicking, it goes to this catalog

What do you mean by this? Are you clicking off the items to unselect as this is what Windows File Explorer also does.

**Comment by Josh65-2201** [comment]
Can you share a screen recording of this.

**Comment by Josh65-2201** [comment]
There is no issue shown there. You can open and right click the drives the same as Windows File Explorer. There no reason to have them be selectable.

**Comment by Josh65-2201** [comment]
As for copying drive that could properly be added but right now you can open the drive and ctrl + A then copy them as normal.

**Comment by yaira2** [comment]
> Can I set the number of elements and their selected items to also appear on the home page?

Thanks for the question, in the current design the status bar is only supported in folders.
