### ISSUE TITLE
drag files failure 

### ISSUE THREAD

**Issue by sheiyll** [files-community/Files#13976]
### Description

Can't drag files 

### Steps To Reproduce

click and hold the files in the desktop and drag it to my folder

it  was not allowed.

### Requirements

- e.g. Fix crash that occurs when...
fix the issue

### Files Version

2.5.29.0

### Windows Version

10.0.22631.2715

### Log File

[debug.log](https://github.com/files-community/Files/files/13405252/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, please update to 3.0.8.0 and see if you can still reproduce this. https://files.community/download
