### ISSUE TITLE
3.0.5.0

### ISSUE THREAD

**Issue by dnmorrison** [files-community/Files#13970]
### Description

I can no longer cut and paste files in this version. If I select files, then copy them, then move to the destination directory, the paste control is no longer available.

Also I keep getting the **update Files** download arrow appearing in the app, but the download always fails. It used to be so robust. It looks as if we are up to version 3.0.8.0 and the cut/paste issue ir probably fixed in that version -- but it won't download properly,

### Steps To Reproduce

select a file
copy or cut it
try to paste it in the target directory
the paste control is not active

### Requirements

Fix the copy/cut paste functionality

### Files Version

3.0.5.0

### Windows Version

10.0.22000.2538

### Log File

[debug.log](https://github.com/files-community/Files/files/13404518/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, 
- Can you test if you can copy and paste outside of Files
- Can you also see if resting your system fixes it.

As for the update issue windows will sometimes cause issues with the auto update. You can try
1. Opening PowerShell as administrator
2. Run this command
```Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/stable/Files.Package.appinstaller```
3. See if Files is in the start menu all apps section

**Comment by dnmorrison** [comment]
Josh

See below


Don


*Don Morrison*

*The Morrison Company*
+ 44 783 125 6959 - Mobile
///dirt.will.merit <https://map.what3words.com/dirt.will.merit?maptype=map> -
Location


On Sun, 19 Nov 2023 at 20:21, Josh65-2201 ***@***.***> wrote:

> Thanks for the report,
>
>    - Can you test if you can copy and paste outside of Files I CAN
>    - Can you also see if resting your system fixes it. IT DOESN'T
>
> As for the update issue windows will sometimes cause issues with the auto
> update. You can try
>
I WILL TRY THIS LATER

**Comment by Josh65-2201** [comment]
If you send an attachment emails don't work, you need to open GitHub and uploaded it from the comment box

**Comment by dnmorrison** [comment]
That's what the instructions say ... and that's what I did. Using Files, I
dragged the log to the target box in your feedback form.

Don


*Don Morrison*

*The Morrison Company*
+ 44 783 125 6959 - Mobile
///dirt.will.merit <https://map.what3words.com/dirt.will.merit?maptype=map> -
Location

**Comment by dnmorrison** [comment]
Josh

I ran PowerShell following your instructions. It updated Files to v3.0.8
and resolved the cut/paste issue.

Thank you.

Don


*Don Morrison*

*The Morrison Company*
+ 44 783 125 6959 - Mobile
///dirt.will.merit <https://map.what3words.com/dirt.will.merit?maptype=map> -
Location
