### ISSUE TITLE
Drag n Drop from Outlook does not work

### ISSUE THREAD

**Issue by KeremArdicli** [files-community/Files#13979]
### Description

When I drag an attached file of an email via Outlook Desktop App, status center shows that file is copied but nothing is transferred actually.
![Ekran görüntüsü 2023-11-20 140052](https://github.com/files-community/Files/assets/72523365/4f0d63a3-f6b7-4663-bd84-4acff024ee51)

### Steps To Reproduce

Open Files.
Go to One Drive Folder.
Create a new Folder.
Open Outlook
Find an email with attachement (mine is a word document)
Drag the file into the Files window.

### Requirements

Files should be copied to the relevant directory

### Files Version

3.0.1.0

### Windows Version

10.0.19045.3693

### Log File

[debug.log](https://github.com/files-community/Files/files/13413114/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #13646. You can check there or click subscribe in the right sidebar for updates.
