### ISSUE TITLE
Steps for post-compilation? 

### ISSUE THREAD

**Issue by Skrell** [files-community/Files#13982]
### What feature or improvement do you think would benefit Files?

I managed to get all the tools installed needed to compile Files on my own but I'm not sure what steps are next? I see an *.exe that upon launch does nothing.   Can you please explain how I go from the output files to an *msix installable package for my PC? 

### Requirements

- This proposal will accomplish encouraging other people/would be developers to contribute to your project

### Files Version

3.0.8

### Windows Version

19045.3693

**Comment by Josh65-2201** [comment]
You don't get an install package for it. You go to Debug > Start debugging or press F5

**Comment by Skrell** [comment]
So that is the only way to launch the application once built?  There's nothing I can do with the files.exe to get it to execute?

**Comment by Josh65-2201** [comment]
No, dev builds aren't meant to be used as a normal install there for testing your changes.
