### ISSUE TITLE
Add right click & drag support

### ISSUE THREAD

**Issue by superluig164** [files-community/Files#13989]
### What feature or improvement do you think would benefit Files?

In the regular File Explorer, if you right click and drag a file/group of files/whatever, you can override the default decision of move/copy/create shortcut and decide what you want instead.  For example, you can right click and drag a file onto a flash drive, and choose to move it instead of the default action of copy.  It would be pretty nice if Files could preserve this feature, since I use it a lot and miss it dearly while trying to use Files instead.

### Requirements

- Allow right click & drag
- Pop up a menu asking what to do.

### Files Version

3.0.8.0

### Windows Version

10.0.22631.2428

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #1396. You can check there or click subscribe in the right sidebar for updates.

Right now the ctrl, shift and alt key should work to change the drag and drop setting
