### ISSUE TITLE
Save Tab Sessions

### ISSUE THREAD

**Issue by cardin** [files-community/Files#13988]
### What feature or improvement do you think would benefit Files?

Have Files be able to reliably save Tabs. One way to do this is to introduce the concept of Tab Session - a snapshot of the tabs being used.

This opens up a lot of possibilities, such as:
- being able to save sessions for Work, Personal, Gaming, etc.
- resuming a fixed set of tabs everytime Files is loaded after reboot

### Requirements

- Saving, deleting, and restoring a set of tabs (i.e. tab sessions)
- Setting a specific tab session as the Startup set of tabs

### Files Version

3.0.8.0

### Windows Version

10.0.19045.3693

**Comment by yaira2** [comment]
Thanks for the feedback, can you confirm if this is the same as #11900?

**Comment by cardin** [comment]
Indeed it is, with better elaboration as well. My issue is a duplicate.
