### ISSUE TITLE
Bug: Next cloud Icon missing

### ISSUE THREAD

**Issue by JohRest** [files-community/Files#13981]
### Description

I do see that my OneDrive Icon is there, but for my also present Nextcloud Integration the icon is left blank:
<img width="144" alt="image" src="https://github.com/files-community/Files/assets/2835797/f4a7d452-e9aa-4bc6-98da-0fe86ed52995">

### Steps To Reproduce

Start Files
On the left the Nextcloud Icon should appear. But it isn't.

### Requirements

- e.g. Fix crash that occurs when...
Expected is to have a similar Icon like the one that is showing for OneDrive...

### Files Version

3.0.8.0

### Windows Version

10.0.22631.2715

### Log File

[debug.log](https://github.com/files-community/Files/files/13415006/debug.log)

**Comment by yaira2** [comment]
Is the icon displayed on the tab if you open the cloud drive?

**Comment by yaira2** [comment]
@JohRest
