### ISSUE TITLE
 无法恢复系统 默认文件资源管理器

### ISSUE THREAD

**Issue by liangcz-8023** [files-community/Files#13992]
### Steps To Reproduce

3. 在Files -- 设置 -- 高级选项 -- 把 将Files设置为默认文件管理器 打开了；之后关闭了；系统无法恢复默认的文件管理器 
4. 尝试了 [#7210](https://github.com/files-community/Files/issues/7210) 问题的所有方法了，都无法恢复系统默认的文件管理器
5. 求助 我应该怎么恢复回来，使用win10 默认的文件管理器

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.0.8.0

### Windows Version

10.0.19045.3693

**Comment by Josh65-2201** [comment]
Download [UnsetFilesAsDefault.zip](https://github.com/files-community/Files/files/13425615/UnsetFilesAsDefault.zip) > Extract and run > See if you can open Windows File Explorer from the start menu.

**Comment by liangcz-8023** [comment]
我的问题解决了，我自己的问题。是我打开File的同时也打开了Q-Dir 这个软件导致的，使用#7210  提供的方法修改注册表，然后在Q-Dir文件中进行如下设置  
![QQ截图20231121193239](https://github.com/files-community/Files/assets/18186769/f58a8452-2db9-487b-9e60-50cc4d5b9dff)

下面截图的 全部都不勾选就可以恢复默认的文件管理器了
![QQ截图20231121193311](https://github.com/files-community/Files/assets/18186769/31c46cb9-7dff-4264-bfb2-528c20215f09)
