### ISSUE TITLE
Feature: Indicate when a OneDrive Folder is "Always Keep on Device"

### ISSUE THREAD

**Issue by cardin** [files-community/Files#13991]
### What feature or improvement do you think would benefit Files?

In OneDrive, there is a toggle setting called `Always keep on this device`.
![image](https://github.com/files-community/Files/assets/553816/e66a54a3-6d2c-4cb8-8b6a-bb920aa15954)

This option is supported on Windows Explorer through an indicator on the Right-Click Context Menu, as well as on the Column Status. 

Here, the Dark Green signifies `Always keep on this device`, while the Outline Green means `Synced`.

![image](https://github.com/files-community/Files/assets/553816/04d94c02-ec96-4a79-902c-1d2fcbc53058)

Files App doesn't support this feature - it doesn't distinguish between `Synced` and `Always keep on this device` statuses

both on the Right-Click Context Menu
![image](https://github.com/files-community/Files/assets/553816/875f1349-1c45-4f9c-a01b-c7e676ded2b3)

and on the Column Status
![image](https://github.com/files-community/Files/assets/553816/e7cef953-05a7-4dfd-914f-c4fdcc3e268f)

### Requirements

- Indicate on Context Menu when `Always keep on this device` is toggled
- Indicate the same thing on the Column Status

### Files Version

3.0.8.0

### Windows Version

10.0.19045.3693

**Comment by Josh65-2201** [comment]
Thanks for the feedback, I've added this to the project board.
