### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by daneel3001** [files-community/Files#13997]
### Description

Hello

The Store proposed a new version yesterday but the installation failed.
I have uninstalled the previous version and whenever I try to install Files now I get this error:

![image](https://github.com/files-community/Files/assets/570729/99687858-cdfc-4c85-b5e1-64ae799d8a3c)

### Steps To Reproduce

1. Install Files App via Store

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

Latest

### Windows Version

11 Pro Insider 25997

### Log File

None

**Comment by Josh65-2201** [comment]
Thanks for the report, This is an issue on the Microsoft stores end and not something Files can fix. You can try restarting your system or try install from https://files.community/download > Select classic installer under the preview button.

**Comment by daneel3001** [comment]
Hello

I have just tried and got an error installing the preview and same error code. Could it be due to some signing issue with this particular package as I only issues with this one.

App installation failed with error message: Deployment Add operation with target volume C: on Package FilesPreview_3.0.9.0_neutral_~_1y0xx7n9077q4 from:  (Files.Package_3.0.9.0_x64_arm64_Preview.msixbundle)  failed with error 0x87AF0813. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues. (0x87af0813)

**Comment by yaira2** [comment]
@daneel3001 can you try these steps
1. Uninstall all versions of Files
2. Run `wsreset` to reset the Microsoft Store
3. Restart Windows
4. Try to install Files through the Store

**Comment by daneel3001** [comment]
Thanks @yaira2 

I have tried this and it's still failing. Maybe it's an issue with the current insider build.

1. `remove-appxpackage -Package "49306atecsolution.FilesUWP_3.0.8.0_x64__et10x9a9vyk8t"`
2. `wsreset`
3. Reboot
4. Same error via Store or when installing Preview

I will report if the issue still happens with new insider.

**Comment by snickler** [comment]
Okay this is good to know. I'm encountering this same exact issue but with other apps, and I'm also running Insider Build 25997. Time to file

**Comment by snickler** [comment]
@daneel3001 - It's related to Windows App SDK and SQLite (0x87af0813 error code if you look in Event Viewer). Something with the the App State Repository and UNIQUE constraint failures.
