### ISSUE TITLE
Thumbnails take too long to load... Maybe time to use own thumbnailing system?

### ISSUE THREAD

**Issue by jokbon** [files-community/Files#13993]
### What feature or improvement do you think would benefit Files?

**Well it takes 3 to 5 minutes for thumbnails to load...**
probaly some corrupted thumbnail, or too much files causing this isusue, and you cant phisicaly find which one it is. 
So its better to make own thumbnailing system for files for more reliability. Well thanks guys if u do it...

### Requirements

- Separate thumbnails loader per folder
- Own generation of thumbnails
- Long loading thumbnails could have "taking too long to load" badge in from of thumbnail, so you could find corrupted ones easily.

### Files Version

3.0.8.0

### Windows Version

22621.2506

### Comments

Take into note system time -.-

![image](https://github.com/files-community/Website/assets/29400409/042fc120-caf5-477a-8071-83265211c10d)
![image](https://github.com/files-community/Website/assets/29400409/40addf9a-7e18-4108-93aa-637ab4caf1f8)

Seems like windows also having same isusues:
![image](https://github.com/files-community/Files/assets/29400409/be6d7405-ffd8-46f9-ac01-112765dbf7e7)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Is this consistent in the same and/or different folders?

**Comment by yaira2** [comment]
Is this an issue in other layouts or just grid?

**Comment by jokbon** [comment]
Other layouts too

**Comment by jokbon** [comment]
and it seems it completely freezes at times whole app, including windows explorer.

**Comment by yaira2** [comment]
Files uses the same thumbnail system as File Explorer, can you try clearing the thumbnail cache? Can you also confirm if it's specific to this location?

**Comment by jokbon** [comment]
can you try clearing the thumbnail cache? = iam strugling for 6 years with this bug apearing on every day, i endup deleting random stuff until it gets fixed, worst of all: i need restart of computer for things to take effect, and i dont even know what to delete most of times. its usualy 2 months of strugle trying to find item causing thumbnail corruption, then deleting it and after week or so geting another items which causing corruption from internet.

**Comment by jokbon** [comment]
the only reason i dowloaded files was hope that it uses diferent thumbnailing system than file explorer to be honest, since on linux i never fell into these bugs...

**Comment by yaira2** [comment]
Thumbnail systems are complicated and if we worked on our own, we wouldn't have time to work on the rest of the app. Is this also an issue in File Explorer?

**Comment by jokbon** [comment]
Yes this is also isusue on file explorer.

**Comment by yaira2** [comment]
@jokbon can you see if there is any different in the latest preview build (v3.1.6) https://files.community/download?
