### ISSUE TITLE
Automatic crash reporter

### ISSUE THREAD

**Issue by clackwell** [files-community/Files#13996]
### What feature or improvement do you think would benefit Files?

Does it have, or can you add an automatic crash report functionality? Because reporting crashes is challenging for simple end users. Ideally it should be as easy as, say, on Android.

### Requirements

- This proposal will accomplish semi-automatic reporting of crash reports.

### Files Version

3.0.8.0

### Windows Version

Windows 11

**Comment by Josh65-2201** [comment]
Thanks for the feedback, The way it is right now is as easy as it can get without major changes. Files does however report crashes automatically but it's only the error and how many times/user had it. So it not always as easy or fast to have fixed.

**Comment by yaira2** [comment]
@clackwell Files uses App Center to track crashes and it does help in many cases, but sometimes the error is too vague to fix without an actual report with steps to reproduce the issue.

**Comment by clackwell** [comment]
Trying 3.1.0, then 3.1.1 I see Files crash when typing on the keyboard while input focus is on the folder content list. The typing is done to select the respective file. The folder contains 880 items (my Downloads folder). After typing/searching like this in the list/table a few times, Files crashes.

What is missing for me as the user is a sense of where this leads. Will someone look at it? Am I supposed to file a bug report? 

Creating a bug report separate can be cumbersome for me as the user. If a popup would appear, asking me whether to send the crash report and whether I would like to add something to it, or comment, that might make it a bit more convenient to add some details, and maybe it paves the way to have the devs get back to me, too. (In our product we even have the problem reporter tool offer to collect some information, which sometimes may contain information related to the crash.)

Then I thought that I could perhaps at least try to attach to the process with Visual Studio 2019 or 2022, and try to get a backtrace from the crash, but while it detects that the process is .NET based, attaching fails with a popup...

---------------------------
Microsoft Visual Studio
---------------------------
Unable to attach to the process. A debug component is not installed.
---------------------------
OK   
---------------------------

![image](https://github.com/files-community/Files/assets/6651253/251d74f5-b75b-41ff-b060-abe62fe1724d)
