### ISSUE TITLE
Bug: Drag and drop from browser doesn't work

### ISSUE THREAD

**Issue by parfait8566** [files-community/Files#14008]
### Description

Dragging and dropping files from the browser doesn't work
I've only tested files from "Downloads", Microsoft Edge (works in File Explorer)

I searched for another browser drag and drop issue but I didn't find it/I missed it

### Steps To Reproduce

1. Download a file
2. Try to drag and drop it to Files

### Requirements

Recognize drag & drop

### Files Version

3.0.8.0

### Windows Version

10.0.22624.2361

### Log File

[debug.log](https://github.com/files-community/Files/files/13429870/debug.log)

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by parfait8566** [comment]
> Is this still an issue in the preview version? https://files.community/download/preview

Yes

**Comment by yaira2** [comment]
Which browser?

**Comment by yaira2** [comment]
Most likely the same as #6309

**Comment by parfait8566** [comment]
> Which browser?

Microsoft Edge

> Most likely the same as #6309

I'm not sure, dragging from/to the desktop seems to be working on my end
