### ISSUE TITLE
Add "Digital signatures" to the "Property" of .msix files

### ISSUE THREAD

**Issue by parfait8566** [files-community/Files#14004]
### What feature or improvement do you think would benefit Files?

.msix files have a "Digital signatures" tab in the "Property" menu:
![image](https://github.com/files-community/Files/assets/146892521/d4f9daa2-9a5a-453b-b84f-43529533a756)

Files doesn't have it.

### Requirements

You wouldn't be forced to open the property menu from File Explorer to install certificates (necessary to install the .msix)

### Files Version

3.0.8.0

### Windows Version

10.0.22624.2361

**Comment by yaira2** [comment]
Thanks for the feedback, can you confirm if this is the same as #3723?

**Comment by parfait8566** [comment]
> Thanks for the feedback, can you confirm if this is the same as #3723?

Yes sorry I didn't realize

**Comment by yaira2** [comment]
Thanks! It's on our todo list 👍
