### ISSUE TITLE
Bug: Scrolling in the conflicts dialog changes the chosen option

### ISSUE THREAD

**Issue by Jay-o-Way** [files-community/Files#14000]
### Description

The dialog that opens when pasting items that already exist, has a bug. When there are a few items that already exist, scrolling the list will change some of the settings for rename/overwrite/omit.

https://github.com/files-community/Files/assets/65828559/d0e6587e-c52c-45c5-91d5-c1996ffe0ab2

### Steps To Reproduce

1. Copy a number of folders and paste in a different location
1. Have a number of items with the same name
2. select a choice from the drop-down
3. scroll the list

### Requirements

Setting should stay

### Files Version

3.0.3.0

### Windows Version

10.0.22621.2715

### Log File

[debug.log](https://github.com/files-community/Files/files/13427958/debug.log)

<details><summary>On YouTube</summary>

https://youtu.be/cGhFSx9YVLA
</details>

**Comment by yaira2** [comment]
Thanks for the report, can you upload the video to GitHub as well?

**Comment by Jay-o-Way** [comment]
Looks like I can! (thought it would be too big)
