### ISSUE TITLE
Feature: Automatically create folders/files when adding an item instead of displaying dialog (discussion)

### ISSUE THREAD

**Issue by parfait8566** [files-community/Files#14005]
### What feature or improvement do you think would benefit Files?

If you make a new folder, you will get this:
![image](https://github.com/files-community/Files/assets/146892521/7c0d0eb6-3b54-4fc4-8b20-fb9e53ee12bb)

On File Explorer:
![image](https://github.com/files-community/Files/assets/146892521/505968c1-2724-4eee-848d-0c28234e91ed)

Add an option to behave like File Explorer when creating files/folders

### Requirements

On File Explorer you can create files/folders right away without having to insert a name, I think it's faster and smoother.

### Files Version

3.0.8.0

### Windows Version

10.0.22624.2361

**Comment by yaira2** [comment]
It's the same amount of steps, isn't it?

**Comment by parfait8566** [comment]
> It's the same amount of steps, isn't it?

No, because Files requires you to name the folder/file. For example, in File Explorer I can press ctrl+shift+n + Enter 5 times and I'd have 5 folders, I can't do something similar in Files.

**Comment by yaira2** [comment]
What's the use case for creating a bunch of folders without naming them? (I'm not against the idea but I'm trying to understand it better)

**Comment by parfait8566** [comment]
> What's the use case for creating a bunch of folders without naming them? (I'm not against the idea but I'm trying to understand it better)

I guess the point is more creating a bunch of folders right away and naming them afterwards. It makes more sense to me this way. Even if it's just one folder/file, it feels more natural to name it after (maybe I'm just too used to File Explorer's behavior lol)

**Comment by yaira2** [comment]
We'll leave this as a discussion for now to try and gather additional feedback.

**Comment by yaira2** [comment]
@parfait8566 we're going to continue tracking this in #9831, you can click subscribe or comment on the issue to be notified of any updates.
