### ISSUE TITLE
App is slow

### ISSUE THREAD

**Issue by parfait8566** [files-community/Files#14002]
### Description

Even with the "leave Files open in the background" option enabled, Files is still very slow to open if you had it closed for a while. It's especially more evident when opening it from the browser or other apps. The weird thing is, even if you're using Files windows, if you haven't opened a new one in a while it'll take time to load up. Left sidebar takes a while to load, so does the right-click context menu. I don't mind if it takes more RAM, but I'd like it to be more responsive.

### Steps To Reproduce

1. Open Files
2. Wait a for a few minutes
3. Open a new Files window and it'll take some time to load up

### Requirements

Make the app more snappy

### Files Version

3.0.8.0

### Windows Version

10.0.22624.2361

### Log File

[debug.log](https://github.com/files-community/Files/files/13429587/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, we're continuing to work on optimizations to improve bother the resource usage and performance. We're currently tracking performance related issues in #4180.

**Comment by yair100** [comment]
@parfait8566 we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
