### ISSUE TITLE
OneDrive selective download files are all downloaded

### ISSUE THREAD

**Issue by AkazaRenn** [files-community/Files#14006]
### Description

When accessing a OneDrive folder that is set to only download the files on request, all the files in this folder are downloaded:
<img width="262" alt="image" src="https://github.com/files-community/Files/assets/8340896/21c04f74-59bb-403d-87e9-ae80ac348b34">
My guess is that it may want to calculate the file size thus requested the file access.

### Steps To Reproduce

1. Link OneDrive account
2. Set any folder to be downloaded only on request
3. Enter that folder through Files app
4. See all the files are requested to be downloaded

### Requirements

Files only be downloaded when they are actually "used", only having them listed on the file list should not trigger that.

### Files Version

3.0.8.0

### Windows Version

10.0.22631.2715

### Log File

[debug.log](https://github.com/files-community/Files/files/13429786/debug.log)

**Comment by yaira2** [comment]
Merging with #12774
