### ISSUE TITLE
Files always looks for update when opening it when set as default app

### ISSUE THREAD

**Issue by FACTERINVURT** [files-community/Files#14018]
### Description

I have Files set as my default file utility for Windows, and every time I open it from the taskbar icon, it checks for an update - this takes at least 8-10 seconds and is a major interruption to workflow.

Is there an option for this to not look for an update every time I open it? I have looked but not able to find anything.

I even went to open a log file as  a part of this ticket, and when I went to open the log file it again told me it was checking for an update

### Steps To Reproduce

1. open files from taskbar
2. files looks for update
3. open log file from about section
4. asks to check for an update

### Requirements

- e.g. Fix crash that occurs when...
I would expect that Files would just open straight away and not hgave to look for an update every time I open it

### Files Version

3.0.8.0

### Windows Version

10.0.22631.2715

### Log File

it wont let me open the log file destination after it tries to update

**Comment by Josh65-2201** [comment]
Thanks for the report, This is an issue with app installer and can not be fixed by Files. You can use the Microsoft store version that doesn't have this issue but is paid.
