### ISSUE TITLE
Feature:The fonr size of the right-click menu may be smaller.

### ISSUE THREAD

**Issue by kpl0111** [files-community/Files#14015]
### What feature or improvement do you think would benefit Files?

The font in the current right-click menu is a little large, so that it may not be possible to display the full right-click menu at once, and a scroll bar will appear. 

Like this,

![right-click](https://github.com/files-community/Files/assets/73956723/72e23824-f1d8-4af4-ab66-d308f4886fe0)

 this is my right-click effect on my laptop desktop.

<img width="292" alt="desktop" src="https://github.com/files-community/Files/assets/73956723/cf3ff640-277b-4d8b-9edc-81a8a1a95898">

 The font is not so large, and the right-click menu can be fully displayed without scrolling the mouse, which may be better.

### Requirements

- reduce the font size of the right-click menu(or add a right-click menu font size customization function in the settings) so that it can be displayed completely

### Files Version

3.0.8.0

### Windows Version

10.0.22631.2506

**Comment by yaira2** [comment]
Thank you for your feedback, we're tracking this feedback in #9506.
