### ISSUE TITLE
Bug: Clicking on file in encrypted 7z archive freezes Files

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#14010]
### Description

*

### Steps To Reproduce

1. Create an encrypted 7z archive with files in
2. Open the archive
3. Enter password
4. Click on file
5. See Files freezes

### Requirements

- Open file clicked on

### Files Version

3.0.9.0

### Windows Version

10.0.22621.2506

### Log File

[debug.log](https://github.com/files-community/Files/files/13431051/debug.log)

**Comment by yaira2** [comment]
Is this an issue in stable?

**Comment by Josh65-2201** [comment]
Yes

**Comment by meemore** [comment]
Stable and Preview correct

7zip, when zipping it also pegs the cpu,  something to do with cores set affinity in task manager to fix this you have to remove a core, and it will crash files randomly.   also, if i     "do not"    use Files, or the Files Preview, and use 7zip with File Manager from the right click menu, it does not peg the CPU.  

I did test this when zipping a few folder with over 5gb's  and it will lockup Files.   If I wait and let the app hang, it will complete, but any attempt to use files, or navigate will crash files.    I have tried, ziping small folders, 200 mb zip,   Files is able to keep up. and is responsive.

My PC is 8 core 4.7ghz with 64gb of Ram, and I have 7zip set to do the work in the working folder not a temp folder.

I have tested this on a M2 drive, Sata and HDD drives and on USB external drive.   I believe it has something to do with "calculate files and folder sizes" when using windows ZIP or 7zip. or Winrar.  It also is connected to having the previews and details panel open at the same time.

**Comment by meemore** [comment]
Forgot to mention,  this is not encrypted zip but  this is just normal zip  but wanted to add this to this issue buddy mentioned as its related.

**Comment by yaira2** [comment]
@Josh65-2201 Is this still an issue in the preview version? https://files.community/download/preview
