### ISSUE TITLE
Bug: Context menu fails to show in an RDP session

### ISSUE THREAD

**Issue by jakebullet70** [files-community/Files#14019]
### Description

When connecting to another machine through an RDP session, Files! running on the connected machine fails to show the main contect menu but will display the context sub menu.
![image](https://github.com/files-community/Files/assets/14124210/a9de7885-2f25-464c-9dd8-d28ca99045ad)

### Steps To Reproduce

Connect with RDP to a machine running Files!
Try a to view the contect menu by right clicking on a file.
See pic. 
Machine used to connect is another Windows 10 Pro.

### Requirements

Show the main context menu.

### Files Version

3.0.8.0

### Windows Version

10.0.19045.3693

### Log File

[debug.log](https://github.com/files-community/Files/files/13437851/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, If you right click further down on Files does it still only show shell items?

**Comment by Josh65-2201** [comment]
Thanks for the information, I've added this to the project board but I believe this might be a Microsoft WinUI issue which Files wouldn't be able to fix on ourside.

**Comment by jakebullet70** [comment]
New info. It only fails when layout is set to 'details' - If I set it to 'tiles' or 'small icons' or anything but 'details' it works OK.

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by jakebullet70** [comment]
This is working in the preview version so I think this can be closed. I will go ahead and do some more testing on the preview version with my RDP connection.
