### ISSUE TITLE
cant save attached files in email (outlook) via drag & drop 

### ISSUE THREAD

**Issue by bnbagiz** [files-community/Files#14020]
### Description

i open up the mail, drag and drop the attachment to a location, but the files don't save, instead I need to save them through the context menu in my email client

### Steps To Reproduce

open email client
open mail
drag and drop attachment to location opened in files browser

### Requirements

files should be save in that directory

### Files Version

3.0.8.0

### Windows Version

Windows 10 Pro Version	22H2 19045.3693

### Log File

cant find the file

**Comment by JollyRoger8X** [comment]
> Is this still an issue in the preview version? https://files.community/download/preview

FYI, I filed https://github.com/files-community/Files/issues/13646 and just checked with Files Insider Preview 3.0.13.0 on Windows 10 Enterprise 22H2 build 19045.3324 (10.0.19045.3324), and the behavior is the same: Outlook attachments are not saved.

**Comment by yaira2** [comment]
Thanks! We're still tracking this in #13646.
