### ISSUE TITLE
Slow responsiveness when dealing with a huge number of files

### ISSUE THREAD

**Issue by parfait8566** [files-community/Files#14023]
### Description

I'm expanding a bit on #13499

Files gets very slow and takes a lot of memory (even after closing the windows/finishing all the cutting and pasting of files) when dealing with a huge number of files. 

### Steps To Reproduce

1. Create 500 empty files using Powershell:
```
for ($i = 0; $i -lt 500; $i++) {
  New-Item -ItemType File -Path "empty_file_$i.txt"
}
```
2. Files should already start slowing down/taking memory
3. If it doesn't, trying cutting and pasting the files somewhere else

### Requirements

Improve performance when dealing with a lot of files.

### Files Version

3.0.8.0

### Windows Version

10.0.22624.2361

### Log File

[debug.log](https://github.com/files-community/Files/files/13443552/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, this is going to be tracked in #13499

**Comment by yaira2** [comment]
Let's track this one here for now

**Comment by yaira2** [comment]
I just tested creating 15,000 blank files and it worked fine, the memory does increase while the items are being created but that's to be expected.

**Comment by parfait8566** [comment]
> I just tested creating 15,000 blank files and it worked fine, the memory does increase while the items are being created but that's to be expected.

Doesn't it slow down when cutting and pasting the files somewhere else? It's considerably slower on Files than on the regular File Explorer (on my end at least)

**Comment by yaira2** [comment]
That's a different type of file operation and is being tracked in #7275, #13632 and #7518.
