### ISSUE TITLE
Bug: TortoiseHg badges not updated promptly

### ISSUE THREAD

**Issue by jfsturtz** [files-community/Files#14026]
### Description

TortoiseHg (GUI front-end for Mercurial revision control system) places badges in the lower left corner of file icons, indicating status (e.g., a check mark to indicate file is up-to-date; an exclamation point to indicate file has been changed since last update).

![_img](https://github.com/files-community/Files/assets/21157737/dbfc54da-f6c1-40de-8102-13adfc30173a)

Files _does_ display the badges, but doesn't update them promptly.  If you modify a file in the repository, Windows Explorer will update the badge to exclamation point as soon as the file is saved.  Files seems not to update until the next OS reset.

I have tried:

- Refreshing the Files window
- Navigating away from the directory and back to it
- Executing the 'Update Icons' command from the TortoiseHg context menu

None seem to work.  Not until I restart Windows and then navigate to the repository will Files show the updated icon badges.

### Steps To Reproduce

1. Install TortoiseHg (if not already)
2. Navigate to a directory containing files and create a repository
3. Edit one of the files and save it

### Requirements

Expected behavior is that the TortoiseHg badge will change from check mark to exclamation point as soon as the file is saved.  Observed behavior is that it doesn't, until the next OS restart.

### Files Version

22631.2715

### Windows Version

Windows 11 Home 23H2 / Build 22631.2715

### Log File

[debug.log](https://github.com/files-community/Files/files/13445576/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
Is this the same as #13901?

**Comment by yaira2** [comment]
Merging with #13901
