### ISSUE TITLE
Bug: Files stop responding when downloading file stored in OneDrive

### ISSUE THREAD

**Issue by likkai** [files-community/Files#14036]
### Description

Files will stop responding when open a file stored in cloud only. The memory of the program is using will drop to 8 MB at minimum. At this point, Files cant be closed by task manager or other methods, it just stuck there. Files will only continue working after completing the download

### Steps To Reproduce

1. Double click to open file that is stored in cloud only
2. Files stop responding

### Requirements

- Open files stored in OneDrive but not local

### Files Version

3.0.8.0

### Windows Version

1000.22677.1000.0

### Log File

[debug.log](https://github.com/files-community/Files/files/13450276/debug.log)

**Comment by yaira2** [comment]
@likkai can you see what happens if you try opening a file while when Files as admin?

**Comment by likkai** [comment]
> @likkai can you see what happens if you try opening a file while when Files as admin?

same result, here is the screenshot for better reference. The file is an exe file
![Snipaste_2023-11-24_03-14-03](https://github.com/files-community/Files/assets/76016664/d6c32d96-5577-4e96-a5dc-b9d78ce50883)

**Comment by likkai** [comment]
> @likkai can you see what happens if you try opening a file while when Files as admin?

same result. The file is an exe file btw. Here is the screenshot 
![Snipaste_2023-11-24_03-14-03](https://github.com/files-community/Files/assets/76016664/b2ad6ee4-ae48-43b4-9ed9-b6822b2f2c78)

**Comment by yaira2** [comment]
Can you try deleting the log file and after reproducing the issue again as admin, upload it here?

**Comment by likkai** [comment]
Here is the log
[debug.log](https://github.com/files-community/Files/files/13453707/debug.log)

**Comment by yaira2** [comment]
Thanks! Same issue as before `2023-11-24 06:40:28.2078|Information|System.ComponentModel.Win32Exception (388): An error occurred trying to start process '****.exe' with working directory 'C:\Windows\System32'. The cloud sync provider failed to perform the operation due to network being unavailable.`

**Comment by yaira2** [comment]
@likkai can you confirm if this is still an issue in v3.6? Can you also check what happens when you try this in File Explorer?

**Comment by likkai** [comment]
Hello, the issue still persists even on 3.7.7.0
[debug.log](https://github.com/user-attachments/files/17268018/debug.log)

**Comment by yaira2** [comment]
I can't reproduce this in Files but I can repro it in File Explorer. Can you confirm what happens in File Explorer?

**Comment by likkai** [comment]
File explorer works normally (when the file explorer is default)

This is a screen recording of what happened on both applications:
https://1drv.ms/v/s!AjlVdnwJiU-2hcEdwqWPivqeUVqGMQ?e=QNkDAj
