### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by perscheffer** [files-community/Files#14038]
### Description

Installation fails using Microsoft Store, Classic Installer (Files.Stable.exe 3.0.8.0), and Insider Preview (Files.preview.appinstaller 3.0.10.0).

![1 1 Microsoft Store](https://github.com/files-community/Files/assets/114069484/c7cd6927-8e76-488a-8c42-f8fd09742839)
![2 1 Classic Installer](https://github.com/files-community/Files/assets/114069484/e8a4bc2f-fb4f-4b42-923e-fe333235f01e)
![3 1 Insider Preview](https://github.com/files-community/Files/assets/114069484/0574151f-66fc-439c-b520-76f680291551)

The common error number is 0x87AF0813.

I had Files Insider Preview (I think 3.0.1.0) installed previously. I uninstalled it from Windows settings. I then got an error when trying to install the latest Insider Preview.

Things I have tried:

- running `wsreset`
- Running
  - `dism/online/cleanup-image/checkhealth`
  - `dism/online/cleanup-image/scanhealth`
  - `dism/online/cleanup-image/restorehealth`
  - `sfc /SCANNOW`
- Restarting Windows

Delivery optimization and Windows Update services are enabled.

I tried installing another app (OneCommander) from the Microsoft Store, and it installed fine.

Related to #13997 and possibly #13861

### Steps To Reproduce

- Install Files from either
   - Microsoft Store
   - Files.Stable.exe
   - Files.preview.appinstaller

### Requirements

Installation succeeds.

### Files Version

3.0.8.0

### Windows Version

Windows 11 Pro Insider Preview 25997.1010

### Log File

[1.2 Microsoft Store Event Log.txt](https://github.com/files-community/Files/files/13451204/1.2.Microsoft.Store.Event.Log.txt)
[1.3 Microsoft Store AppxLog.txt](https://github.com/files-community/Files/files/13451208/1.3.Microsoft.Store.AppxLog.txt)
[2.2 Classic Installer Event Log.txt](https://github.com/files-community/Files/files/13451209/2.2.Classic.Installer.Event.Log.txt)
[2.3 Classic Installer AppxLog.txt](https://github.com/files-community/Files/files/13451210/2.3.Classic.Installer.AppxLog.txt)
[3.2 Insider Preview Error Message.txt](https://github.com/files-community/Files/files/13451211/3.2.Insider.Preview.Error.Message.txt)
[3.3 Insider Preview Event Log.txt](https://github.com/files-community/Files/files/13451212/3.3.Insider.Preview.Event.Log.txt)
[3.4 Insider Preview AppxLog.txt](https://github.com/files-community/Files/files/13451213/3.4.Insider.Preview.AppxLog.txt)

**Comment by Josh65-2201** [comment]
Thanks for the report, this is an issue with the current Windows Insider builds

**Comment by yaira2** [comment]
It's been reported to Microsoft so hopefully they fix it son.

**Comment by yaira2** [comment]
This only affects apps using WinAppSdk

**Comment by perscheffer** [comment]
It's good that we now have the information here that it's an issue with Windows Insider builds, so the next person can find it and not spend a lot of time in vain writing a thorough bug report.

**Comment by NBKRedSpy** [comment]
Install failure as well, not running Windows preview.

I'm running Windows 10, just downloaded stable version.  Not insider preview.  This is my development system running VS Community Editions for 2019 and 2022.

I think this is the WinAppSDK info:

```
(get-appxpackage micro*win*appruntime*).packagefullname

Microsoft.WindowsAppRuntime.1.2_2000.802.31.0_x86__8wekyb3d8bbwe
Microsoft.WindowsAppRuntime.1.2_2000.802.31.0_x64__8wekyb3d8bbwe
Microsoft.WindowsAppRuntime.1.3_3000.934.1904.0_x86__8wekyb3d8bbwe
Microsoft.WindowsAppRuntime.1.3_3000.934.1904.0_x64__8wekyb3d8bbwe
Microsoft.WindowsAppRuntime.1.1_1005.616.1651.0_x86__8wekyb3d8bbwe
Microsoft.WindowsAppRuntime.1.1_1005.616.1651.0_x64__8wekyb3d8bbwe
Microsoft.WindowsAppRuntime.1.4_4000.1010.1349.0_x64__8wekyb3d8bbwe
Microsoft.WindowsAppRuntime.1.4_4000.1010.1349.0_x86__8wekyb3d8bbwe
```

**Comment by yaira2** [comment]
> It's good that we now have the information here that it's an issue with Windows Insider builds, so the next person can find it and not spend a lot of time in vain writing a thorough bug report.

Absolutely, it took a couple reports before we realized this was a wider issue.

**Comment by Josh65-2201** [comment]
> Summary: Install failure as well. Latest stable classing installer. Not running Windows preview. Windows 10.

What error are you getting?

**Comment by yaira2** [comment]
@NBKRedSpy it might not be specific to Windows Insider, we're still trying to figure this out.

**Comment by NBKRedSpy** [comment]
Version 3.0.8.0.  Just says:  "Install failed.  Please contact your software vendor."  I don't see any option to get more info on the error.

**Comment by Josh65-2201** [comment]
You can try
1. Opening PowerShell as administrator
2. Run this command
```Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/stable/Files.Package.appinstaller```
3. See if Files is in the start menu all apps section

**Comment by NBKRedSpy** [comment]
The AppxPackage install did work.

Just FYI, tested the SFX on Windows Sandbox and a Windows VM and both worked.

The VM did not have VS installed, and was able to run the get-appxpackage.  

And returned:
```
Microsoft.WindowsAppRuntime.1.2_2000.802.31.0_x64__8wekyb3d8bbwe
Microsoft.WindowsAppRuntime.1.2_2000.802.31.0_x86__8wekyb3d8bbwe
Microsoft.WindowsAppRuntime.1.3_3000.934.1904.0_x86__8wekyb3d8bbwe
Microsoft.WindowsAppRuntime.1.3_3000.934.1904.0_x64__8wekyb3d8bbwe
Microsoft.WindowsAppRuntime.1.4_4000.1010.1349.0_x64__8wekyb3d8bbwe
```

**Comment by NBKRedSpy** [comment]
Just noticed this bug was closed.  Just to be clear, the SFX version on the main page fails to install.

**Comment by Josh65-2201** [comment]
This issue was closed as both issues are ones with Windows and not something Files can fix.

**Comment by JanRajnoha** [comment]
I have this problem during updating Dev Home. Did you found any workaround for you? I tried VS, but get DEP800 (I think it was) error, which blocked deployment because I could not insta runtime. So now in state, when I could not find way how to install it in my system.

**Comment by perscheffer** [comment]
Installation works again on Windows 11 Pro Insider Preview 26002.1000.
