### ISSUE TITLE
Bug: Drag-and-Drop Multiple Files Opens Multiple Instances Instead of Passing as Arguments for .py and .bat Files

### ISSUE THREAD

**Issue by antonioseet** [files-community/Files#14033]
### Description

When multiple files are dragged and dropped onto Python (.py) or batch (.bat) files in the app, the current behavior incorrectly opens multiple instances of the respective script, one for each file. Instead, it should open a single instance of the script and pass the paths of all selected files as arguments. This issue affects the usability and efficiency of script execution via drag-and-drop.

### Steps To Reproduce

1. Create a Python (.py) or batch (.bat) file that accepts file paths as arguments.
2. Select multiple files in the Files application.
3. Drag and drop these files onto the Python or batch file.

The application opens a new instance of the Python or batch script for each file dragged onto it, resulting in multiple script instances running separately.

### Requirements

The application should open only one instance of the script (Python or batch).
All dragged file paths should be passed to this instance.
The script should be able to process multiple arguments, with each argument representing the path of a dragged file.

This functionality is expected to align with typical command-line behavior where scripts can receive multiple arguments.

### Files Version

3.0.10.0

### Windows Version

Windows 11 Pro Version	23H2 22631.2715

### Log File

[debug.log](https://github.com/files-community/Files/files/13448740/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
@antonioseet did you want to work on this? If not, I was working on something similar for fonts and I can quickly port it over for this.

**Comment by antonioseet** [comment]
I would like to implememnt the changes, as it is part of a course I am taking if that's not too much to ask :)

**Comment by yaira2** [comment]
Okay, I'll let you do the changes 👍
