### ISSUE TITLE
Option to disable AutoCorrect

### ISSUE THREAD

**Issue by NoelShourai** [files-community/Files#14031]
### What feature or improvement do you think would benefit Files?

Right now it appears that AutoCorrect or some form of it is an undocumented function in Files that triggers when trying to rename filenames and extensions without the user's input, especially of words that this function does not find in its dictionary. If there currently isn't a way to disable this, can it be added?

### Requirements

- Add the option to disable AutoCorrect under the Settings page
- Boolean variable within user_settings.json

### Files Version

3.0.8.0

### Windows Version

Edition	Windows 11 Pro Version	23H2 Installed on	‎10/‎5/‎2023 OS build	22631.2715 Experience	Windows Feature Experience Pack 1000.22677.1000.0

### Comments

Discovered AutoComplete while trying to rename files. While trying to disable it, I was unable to find it in the Settings Page or user_settings.json, nor could I find it in online documentation. The only way I have been able to work around it is to add the problem words to its dictionary, but this doesn't always work.

In the below image as an example, upon attempting to rename a video file the function renames "mechwarrior" into "MechWarrior" and the "mkv" extension into a dictionary friendly word like "maki".
![image](https://github.com/files-community/Files/assets/19917103/d9f0a24d-16f4-4eb5-bc7a-38026551cb24)

**Comment by Josh65-2201** [comment]
Thanks for he feedback, Files doesn't have an auto correct feature, this would be an issue with Windows
