### ISSUE TITLE
God Mode not supported

### ISSUE THREAD

**Issue by maxib0n** [files-community/Files#14037]
### Description

The so called "God Mode", enabling the user to access all the system preferences from one place, is not supported in the current release

### Steps To Reproduce

1 - Create a Folder named "GodMode.{ED7BA470-8E54-465E-825C-99712043E01C}"
2 - Open in Files v3
3 - The folder is empty

### Requirements

- Show all the system preferences
<img width="973" alt="Screenshot 2023-11-23 162307" src="https://github.com/files-community/Files/assets/99250518/399332e6-230e-4f7a-b647-e5f2c374030e">

### Files Version

3.0.8.0

### Windows Version

10.0.22631.2715

### Log File

[debug.log](https://github.com/files-community/Files/files/13451591/debug.log)

**Comment by yaira2** [comment]
@maxib0n try `shell:::{ED7BA470-8E54-465E-825C-99712043E01C}`

**Comment by maxib0n** [comment]
> @maxib0n try entering `shell:::{ED7BA470-8E54-465E-825C-99712043E01C}` into the path bar. If it works, you can create a shortcut or pin it to the sidebar for easy access.

Thank you for the workaround
