### ISSUE TITLE
Bug: Files crashed when I was uploading a tons of files

### ISSUE THREAD

**Issue by Pedrostone** [files-community/Files#14039]
### Description

I was copying a folder with my pics to the nas, 80Go, take the night but didnt finish ans 20 min Files crashed.

### Steps To Reproduce

copy and paste the folder

### Requirements

- e.g. Fix crash that occurs when...
I was copying a folder with my pics to the nas, 80Go, take the night but didnt finish ans 20 min Files crashed.

### Files Version

3.0.8.0

### Windows Version

10.0.22631.2715

### Log File

[debug.log](https://github.com/files-community/Files/files/13452367/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
@Pedrostone Is this still an issue in the preview version? https://files.community/download/preview

**Comment by Pedrostone** [comment]
The second test has been a succes :)

**Comment by yaira2** [comment]
Thanks!
