### ISSUE TITLE
different theme for navbar and menu and else

### ISSUE THREAD

**Issue by gilnett** [files-community/Files#14043]
### What feature or improvement do you think would benefit Files?

could you add the possibility of modifying the theme of the navigation bar, the info panel and the window in separate ways c (change the color of one thing only)

### Requirements

color editable.
without touching the other displays.
available in the appearance section.
hover effect included in color changes.
on all windows.
navbar navigation pane,... all available in subsections on the appearance section.

### Files Version

3.0.8.0

### Windows Version

10.0.22631.2715

**Comment by Josh65-2201** [comment]
For theming follow the instructions at https://files.community/docs/configuring/custom-themes
