### ISSUE TITLE
Co-existance with PowerToys

### ISSUE THREAD

**Issue by szebegyi** [files-community/Files#14046]
### What feature or improvement do you think would benefit Files?

PowerToys offer various beneficial tools, some integrated with Windows Explorer. Most work fine with Files as well, however few may collide, namely:

- thumbnail preview and "normal" (Alt-P) preview. 
- Peak: PowerToys offers file peak preview with CTRL-Space shortcut. This is very similar to MacOS CMD-Space preview, which is great

==> it would be good if PowerToys could be used with Files efficiently.

### Requirements

- thumbnail preview integration with PowerToys
- normal" (Alt-P) preview integration with PowerToys
- PowerToys Peak integration with Files

### Files Version

3.0.8.0

### Windows Version

10.0.19045.3636

### Comments

Great work!

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Peek doesn't have an API to allow Files to use it. This is being tracked here https://github.com/microsoft/PowerToys/issues/26422
Thumbnail preview that PowerToys adds also work in Files
Files has a preview pane via the toolbar button.
![image](https://github.com/files-community/Files/assets/26977075/7b25f41c-10bb-4c5c-bcc7-6fc48cdc917a)
