### ISSUE TITLE
ALT-P preview extremely slow or not working

### ISSUE THREAD

**Issue by szebegyi** [files-community/Files#14047]
### Description

ALT-P preview of certain files (typically PDF and MS office documents): the preview to appear may take up to 20 seconds, sometimes not shown at all. In Windows Explorer those are shown within a fraction of a second.

### Concerned code

?

### Gains

ALT-P preview is a must for me (probably for many of us). Long and unpredictable delays have serious impact on usability.

### Requirements

To be identified by developers.

**Comment by Josh65-2201** [comment]
Please use the feature request template for feature requests

**Comment by yaira2** [comment]
The previews work via shell extensions, I'm not sure if there is much that can be done to improve the performance in this area but we'll keep working on improving overall performance.
