### ISSUE TITLE
Files doesn't update disk usage properly

### ISSUE THREAD

**Issue by Founntain** [files-community/Files#14048]
### Description

I was cleaning up my PC today and notices that Files wasn't updating the disk usage properly

Files shows only 440GB Free instead of 1.1 TB
![](https://gud.founntain.dev/f/4hFfFYJYY0.png)

### Steps To Reproduce

1. Cleanup PC
2. See that files doesn't update properly

### Requirements

Expected behaviour would be Files updating properly or give us a refresh button in the Home View so we can trigger an update of those values

### Files Version

3.0.8.0

### Windows Version

10.0.22631.2715

### Log File

[debug.log](https://github.com/files-community/Files/files/13458041/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with https://github.com/files-community/Files/issues/6182. You can check there or click subscribe in the right sidebar for updates.
