### ISSUE TITLE
Bug: A bug in the workflow file used for checking XAML formatting

### ISSUE THREAD

**Issue by Poker-sang** [files-community/Files#14054]
### Description

When a XAML file is deleted in the PR, the workflow for checking the format encounters an unexpected error. See [error log](https://github.com/Poker-sang/Files/actions/runs/6982293889/job/19001165290?pr=1).

### Steps To Reproduce

see commit in [example](https://github.com/Poker-sang/Files/pull/1).

### Requirements

Add `--diff-filter=d` to exclude deleted XAML files.
```
$changedFiles = (git diff --diff-filter=d --name-only HEAD~1) -split "\n" | Where-Object {$_ -like "*.xaml"}
```

### Files Version

Any

### Windows Version

Any

### Log File

None

**Comment by yaira2** [comment]
Thank you for reporting and fixing this issue.
