### ISSUE TITLE
Support for Windows PowerToys (Specifically Peek)

### ISSUE THREAD

**Issue by AstroFalconZ** [files-community/Files#14052]
### What feature or improvement do you think would benefit Files?

As a previous Mac user, I used to use the peek feature constantly. On Windows, I use it through PowerToys but would love to combine it with column view

### Requirements

Holding down Ctrl + Space to show a peek of the desired content, as well as other PowerToys content

### Files Version

3.0.8.0

### Windows Version

Edition	Windows 11 Pro Version	22H2 Installed on	‎14/‎11/‎23 OS build	22621.2715 Experience	Windows Feature Experience Pack 1000.22677.1000.0

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Peek doesn't have an API to allow Files to use it. This is being tracked here https://github.com/microsoft/PowerToys/issues/26422
