### ISSUE TITLE
Bug: Tabs in between the first and last one are blank on startup

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#14056]
### Description

![image](https://github.com/files-community/Files/assets/26977075/df56da9b-9576-43dc-9a04-ebf9e2a2cfea)

Same issue as #13780 but for me when using the `open a specific page or pages`

### Steps To Reproduce

1. Enable Files settings > Genral > Startup settings > Open a specific page or pages
2. Add at least three tabs to open
3. Restart Files
4. See middle tabs are blank

### Requirements

- Show all tabs icon and folder names

### Files Version

3.0.11.0

### Windows Version

10.0.22621.2715

### Log File

[debug.log](https://github.com/files-community/Files/files/13460959/debug.log)

**Comment by yaira2** [comment]
Thanks for the report
