### ISSUE TITLE
Bug: Path bar doesn't use localized name for system folders

### ISSUE THREAD

**Issue by Pedrostone** [files-community/Files#14055]
### Description

Files looks like translate some folder. When I recreate a folder it does not reproduce the error.
![image1](https://github.com/files-community/Files/assets/65383895/a372f292-3e9f-4c87-a3b3-739b84d9a3a9)
![image2](https://github.com/files-community/Files/assets/65383895/cedd0ccc-4187-4d93-91aa-9931a8f8ecd6)
![image3](https://github.com/files-community/Files/assets/65383895/c2234f8b-17f4-4d96-a544-a9253f234613)

### Steps To Reproduce

Copy paste to an another folder in split view

### Requirements

not crash but just translate

### Files Version

3.0.8.0

### Windows Version

10.0.22631.2715

### Log File

[debug.log](https://github.com/files-community/Files/files/13460734/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
What does it show in File Explorer?

**Comment by yaira2** [comment]
@Pedrostone

**Comment by Lukiluc29** [comment]
I can also reproduce this issue. In File Explorer it displays the folder name correctly.

**Comment by Lukiluc29** [comment]
![Capture d'écran 2024-01-16 163252](https://github.com/files-community/Files/assets/128183422/a5bdf825-4140-45d9-a156-c549dfcdb403)

**Comment by Lukiluc29** [comment]
There are indeed translation problems in the path bar.

**Comment by yaira2** [comment]
> What does it show in File Explorer?

**Comment by Lukiluc29** [comment]
> > What does it show in File Explorer?

Translations display correctly in File Explorer.
![Capture d'écran 2024-01-16 171048](https://github.com/files-community/Files/assets/128183422/89ebcf3f-66ab-41c5-b2c9-3e5d8136a223)
![Capture d'écran 2024-01-16 171053](https://github.com/files-community/Files/assets/128183422/b50fc75d-77fe-4cd2-9c5e-ce81c7458c17)

**Comment by yaira2** [comment]
A fix will be included in the next release
