### ISSUE TITLE
Option to show the status center flyout on activity

### ISSUE THREAD

**Issue by superluig164** [files-community/Files#14065]
### What feature or improvement do you think would benefit Files?

Like the title says, I'd love to see an option for the status center to open itself when something is happening there (like a file copy) and relatedly, it would be nice if it remembered whether or not the view was expanded, so I could see the speed immediately instead of requiring an interaction every time.  Not sure if I should make a new issue for this, but I also think the icon for the number of tasks should be revised, since right now it covers the first 3/4 of the circular progress bar all the time, which makes said progress bar kind of useless.  It should probably show that number in the center of the icon, or else only show it if 2 or more tasks are in progress.

### Requirements

- Show the status center automatically when there is activity.
- Remember whether the user wants the view expanded or not to see transfer speed.
- Revise the status center icon.

### Files Version

3.0.8.0

### Windows Version

10.0.22631.2428

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with https://github.com/files-community/Files/issues/13560. You can check there or click subscribe in the right sidebar for updates.

**Comment by superluig164** [comment]
Should I make a separate post about the suggested improvements to the status center icon?

**Comment by Josh65-2201** [comment]
Sorry didn't see that part, Yes you should.

**Comment by superluig164** [comment]
Got it.  Will do.
