### ISSUE TITLE
Ctrl+ S or Ctrl +O menu

### ISSUE THREAD

**Issue by DGreyyyy** [files-community/Files#14066]
### What feature or improvement do you think would benefit Files?

The app work verry good. But when i use Ctrl + S or Ctrl +O on another app it will send me to old file explore. Can you make the app work with that hotkey.
Ths for all sp about team. its a great app.

### Requirements

when use Ctrl + S or Ctrl +O on another app it will open the small menu off explore not default window exlpore

### Files Version

3.0.8.0

### Windows Version

window 11 23h2

**Comment by Josh65-2201** [comment]
Thanks for the feedback, This wont be possible until Microsoft give a way of doing so. You can make a request this on the Feedback Hub app
