### ISSUE TITLE
Works fine but...

### ISSUE THREAD

**Issue by yoyoda2048** [files-community/Files#14061]
### What feature or improvement do you think would benefit Files?

Hi
I have just two comments to make. Firstly, the first launch of the application always takes a very long time (10/15 seconds) but then it takes a second - is this normal? Secondly, I haven't found a way of moving the columns, for example I prefer to have the size right next to the name and in my case all the columns are fixed, is this normal?
Regards

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.0.8.0

### Windows Version

10.0.22631.2715

**Comment by Josh65-2201** [comment]
Thanks for the feedback, 
- That startup time is expected right now has it has to load the Files process. Improvements are being made.
- Reordering columns is being tracked in #8385. You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
To expand on what Josh already said, we'll continue working on improvements to startup performance, but in the meantime you can work around this a little bit by using the option to keep Files open in the background.
