### ISSUE TITLE
Feature: Show count in middle of the status center progress ring

### ISSUE THREAD

**Issue by superluig164** [files-community/Files#14072]
### What feature or improvement do you think would benefit Files?

I think it would be good for the icon for the number of tasks to be revised, since right now it covers the first 3/4 of the circular progress bar all the time, which makes said progress bar kind of useless. It should probably show that number in the center of the icon, or else only show it if 2 or more tasks are in progress.

### Requirements

- Changes to the layout of the icon

### Files Version

3.0.8.0

### Windows Version

10.0.22631.2428

**Comment by Josh65-2201** [comment]
Thanks for the feedback, I've added this to the project board.

**Comment by yaira2** [comment]
> It should probably show that number in the center of the icon, or else only show it if 2 or more tasks are in progress.

We explored this a while ago, but it didn't scale for triple digit file operations. It's true that it's a pretty niche scenario but it's something we need to account for.

**Comment by Josh65-2201** [comment]
What would it look like have three digits? If it went over the progress circle that would properly be acceptable as 999 active operations is quite impossible or even just showing it as 99+

**Comment by yaira2** [comment]
> What would it look like have three digits

It would be cut off

**Comment by Josh65-2201** [comment]
Honestly that seem acceptable to me, 99 active operations would very much have to be forced by the user and they would probably expect it to not show correctly.

**Comment by superluig164** [comment]
I don't see why it couldn't revert to the top corner if the number of file operations exceeds 99.  Most people are likely doing far less operations at once, and would rather see the progress bar.

**Comment by superluig164** [comment]
Additionally, I think the checkmark when everything is complete is a bit unnecessary, I think a status icon is only really necessary if something is ongoing or if there is an error.  That, or just change the icon of the status center entirely to a checkmark as opposed to it looking like an unseen notification or something.
