### ISSUE TITLE
Bug: Folder image preview not showing

### ISSUE THREAD

**Issue by fiendish55** [files-community/Files#14071]
### Description

In explorer if a folder has image file inside, the folder picks one random image to show its content over that folder front. This is not currently working in newest stable downloaded from microsoft store files app. 

### Steps To Reproduce

any folder dont show image preview.

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.0.8.0

### Windows Version

10.0.22621.2715

### Log File

[debug.log](https://github.com/files-community/Files/files/13464857/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
This issue should be resolved in the next release
