### ISSUE TITLE
select multiple files without using Ctrl

### ISSUE THREAD

**Issue by Rand-333** [files-community/Files#14073]
### What feature or improvement do you think would benefit Files?

It would be nice to have a button to select files in the current folder without holding the Ctrl key until the button is pressed again to turn this mode off.  

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.0.5.0

### Windows Version

10.0.22631.2715

**Comment by Josh65-2201** [comment]
Thanks for the feedback, you can already click the icon in details layout or the box in the top right corner to select with mouse only.
