### ISSUE TITLE
Application crashes when trying to add a program to the start menu from files

### ISSUE THREAD

**Issue by RaulKong898** [files-community/Files#14076]
### Description

Aplicația se blochează la încercarea de a adăuga un program în meniul de start din fișiere

### Steps To Reproduce

The steps to reproduce the behavior are as follows:

1. Open the program.
2. Right-click the program.
3. Select the "More options" option.
4. Select "Pin to start menu".
5. The application crashes and the program does not appear in the start menu.

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.0.8.0

### Windows Version

10.0.25997.1010

### Log File

[debug.log](https://github.com/files-community/Files/files/13465965/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by yaira2** [comment]
Thank you for your feedback, we're currently tracking this issue in #13947.
