### ISSUE TITLE
Bug: Delete folder make Files stucked

### ISSUE THREAD

**Issue by YT-Advanced** [files-community/Files#14077]
### Description

I'm Reverse Engineer so when I decompile a program, it will create some folder that have about 200.000-800.000 files, and when I finished my task, I deleted these folder via Files and Files got stucked like this
<img width="292" alt="image" src="https://github.com/files-community/Files/assets/70064328/ec27808f-b251-4643-96d1-0fc2288a279d">

### Steps To Reproduce

Delete a folder with large amout of files

### Requirements

None

### Files Version

3.0.8.0

### Windows Version

10.0.22621.1992

### Log File

[debug.log](https://github.com/files-community/Files/files/13466175/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Merging with #14057. You can check there or click subscribe in the right sidebar for updates.

Files isn't stuck it will still be going due to the amount of Files it may take time to start.

**Comment by yaira2** [comment]
@YT-Advanced does the task eventually start?

**Comment by YT-Advanced** [comment]
> @YT-Advanced does the task eventually start?

Now it started but the time it take is too much
