### ISSUE TITLE
offline installer request 

### ISSUE THREAD

**Issue by jungdee** [files-community/Files#14079]
### What feature or improvement do you think would benefit Files?

https://cdn.files.community/files/preview/Files.Package_3.0.1.0_Preview_Test/Files.Package_3.0.1.0_x64_ARM64_Preview.msixbundle

linke doesen't work offline installer please.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

latest

### Windows Version

windows 11

**Comment by hez2010** [comment]
We don't keep the link for older versions. 
The current version is 3.0.8 but you are trying to download 3.0.1.

**Comment by Josh65-2201** [comment]
This one is Files
https://cdn.files.community/files/stable/Files.Package_3.0.8.0_Stable_Test/Files.Package_3.0.8.0_x64_ARM64_Stable.msixbundle
This one is WinAppSDK which you might also need to install.
https://cdn.files.community/files/stable/Files.Package_3.0.8.0_Stable_Test/Dependencies/x64/Microsoft.WindowsAppRuntime.1.4.msix
