### ISSUE TITLE
Feature: Option in setting to set default create new tab into duplicate existing tab

### ISSUE THREAD

**Issue by MaxSteven** [files-community/Files#14078]
### What feature or improvement do you think would benefit Files?

Please consider to having an option in the setting that override the default behaviour of creating new tab.
By default Ctrl + T will create new tab but it will be great to have duplicate tab feature instead.
I know we have the specific shortkey for duplicate tabs but Ctrl + T will stay consistent between multiple apps
Or maybe give user ability to edit and customize the shortcut?

### Requirements

- This proposal will accomplish better user experience for specific cases
- This proposal will accomplish consistent between apps like edge and chrome
- This proposal will accomplish Z

### Files Version

3.0.8.0

### Windows Version

10.0.22631.2715

**Comment by Josh65-2201** [comment]
Thanks for the feedback. There already is using `Ctrl + Shift + K`, Remapping them is tracked in #9559. You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
This feature will be included in the next release. Please see #9559 for more details.
