### ISSUE TITLE
Bug: Navigation pane flickers

### ISSUE THREAD

**Issue by xmha97** [files-community/Files#14083]
### Description

The navigation pane flickers when it's long and scrolled to the end, and the Files app is full screen.

https://github.com/files-community/Files/assets/23485114/637de447-7fe8-4b1b-8f14-5a553ac72e1c

### Steps To Reproduce

1. Scroll the navigation pane to the end.
2. The navigation pane flickers.

### Requirements

The crash that occurs only when the Files app is on Full screen mode.

### Files Version

3.0.8.0

### Windows Version

10.0.22621.2428

### Log File

N/A

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
Seems like a WinUI rendering issue.
Fyi @chingucoding

**Comment by chingucoding** [comment]
Yeah this is probably a WinUI rendering issue.

**Comment by yaira2** [comment]
@xmha97 there doesn't seem to be much to do from our side, but hopefully this is fixed in a future WinUI update.
