### ISSUE TITLE
Feature: Hide pCloud from the drives section

### ISSUE THREAD

**Issue by xmha97** [files-community/Files#14081]
### What feature or improvement do you think would benefit Files?

Hi, please hide cloud drives from "Drives" group
![image](https://github.com/files-community/Files/assets/23485114/c0a7ea18-ccbc-4768-95a7-a13ab875969e)
Thanks

### Requirements

- Detect and remove PCloud drive in the drive section

### Files Version

3.0.8.0

### Windows Version

10.0.22621.2428

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Google drive one has already been fixed in the preview version.

**Comment by yaira2** [comment]
@Josh65-2201 @xmha97 can you see if this is resolved in #14084?
