### ISSUE TITLE
Feature: Rename "Drive" group to "Local Drive" group

### ISSUE THREAD

**Issue by xmha97** [files-community/Files#14082]
### What feature or improvement do you think would benefit Files?

Hi, please rename the "Drive" group to the "Local Drive" group,
because there are the "Cloud Drive" group and "Network Drive" group.

![image](https://github.com/files-community/Files/assets/23485114/77c72946-9bc4-4baf-9341-6b4c9240e98a)

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.0.8.0

### Windows Version

10.0.22621.2428

**Comment by Josh65-2201** [comment]
Thanks for the feedback, I've added this to the project board.

**Comment by yaira2** [comment]
"Drives" is meant to be a generic term because it includes removable drives, fixed drives, mounted etc. TLDR, we don't want to get too specific.
