### ISSUE TITLE
Automatically play on cursor hover to audio and video files

### ISSUE THREAD

**Issue by Ray-scatter** [files-community/Files#14089]
### What feature or improvement do you think would benefit Files?

I would like to see an option to have the audio or video file automatically play when the cursor is hovered over it.

This feature would be helpful when organizing materials for video editing.

### Requirements

Enable automatic playback of a wide range of formats including audio, video, and images with Carsol hover.

### Files Version

3.0.8.0

### Windows Version

10.0.22631.2715

**Comment by yaira2** [comment]
Thank you for your feedback, we don't have plans to build this feature directly into Files but we recommend using the QuickLook app which is supported in Files.

**Comment by Ray-scatter** [comment]
Thanks for the info on the app.

However, I think it would be more beautiful as an app if I could complete these things within a single app, but is that difficult?

I think it could be beautifully implemented just by placing a button like "Auto play when file selected" next to the preview playback seek bar.

**Comment by yaira2** [comment]
At this point in time, we'd prefer to put our efforts into improving performance, and to build features that need to be built directly into the app (eg tree view, additional layouts etc). Building a custom preview that can handle all the different codecs and file formats is a lot of work, so we'd prefer to leave it to QuickLook.

**Comment by Ray-scatter** [comment]
I understand.
I'm looking forward to the tree view as I'm hoping for it too.

I also mentioned a wide range of formats, but I think it would be worthwhile just to autoplay the ones that are supported at this stage, so I hope you will remember this request when you have time to do so again.

Thank you.

**Comment by yaira2** [comment]
Just to be clear, it's something that would be nice to have, it just that we don't have the resources to maintain such a feature right now.
