### ISSUE TITLE
Quick view of FTP files

### ISSUE THREAD

**Issue by gabatsek** [files-community/Files#14088]
### What feature or improvement do you think would benefit Files?

Quick view of FTP files on devices on the network. For example mobile phone content.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.0.12.0

### Windows Version

10.0.22631.2715

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Files can already view FTP content by typing `ftp://<ip>:<port>` into the path bar or right clicking the network sidebar item and adding it as a drive/folder.

**Comment by gabatsek** [comment]
Hello!
The image viewer does not allow moving more than 10 images within a folder.
Is there a solution for it?

**Comment by Josh65-2201** [comment]
What image viewer? If you just mean Files then try doing the same in Windows File Explorer. If Windows File Explorer works then please say where you are moving to and from.

**Comment by gabatsek** [comment]
Hello!

I use Microsoft photos by default.
Until now, if I opened a photo in a folder, I could move between the photos
with the mouse or buttons.
Now you have to select the pictures inside the folder, I can only move
between them and it allows a maximum of 10 pictures.

Thank you for your attention!

Josh65-2201 ***@***.***> ezt írta (időpont: 2024. máj. 25.,
Szo, 20:24):

**Comment by Josh65-2201** [comment]
Thats a different issue, We're tracking this in #15409. You can check there or click subscribe in the right sidebar for updates.
