### ISSUE TITLE
Crash when trying to go one directory up while being in disk root directory

### ISSUE THREAD

**Issue by nullptr-deref** [files-community/Files#14094]
### Description

While in a disk root directory (e.g. `C:\`), where I've got from "Home" tab, I tried to click "Up" button and application crashed.

### Steps To Reproduce

1. While in Files application, go to "Home" panel (left side panel).
2. Select any hard drive and move into it (for example, into `C:\` directory).
3. Press "Up" button (or hit `Alt-Up` as well).

### Requirements

While being in the root directory of any disk, this button should be either unavailable to press or should pass you to the "Home" panel.

### Files Version

3.0.8.0

### Windows Version

10.0.19045.3693

### Log File

[debug.log](https://github.com/files-community/Files/files/13478145/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by nullptr-deref** [comment]
No, this is resolved in Preview version.
Thanks for such a quick reaction.
