### ISSUE TITLE
Loading indicator when opening Cloud Drives/Network Drives

### ISSUE THREAD

**Issue by mariusfranzen** [files-community/Files#14098]
### What feature or improvement do you think would benefit Files?

When you open the drop down menu containing cloud and network drives there is a slight delay while Files is looking for the drives (I assume) and a spinning loading indicator while Files is looking for drives would improve the experience in my opinion.

### Requirements

- When you click "Cloud Drives" or "Network Drives" the arrow is replaced with a spinning style loading indicator
- The list is fully populated before actually displaying the drop down which will make it appear less "twitchy"
- Replace the loading indicator with the arrow again

### Files Version

3.0.12.0

### Windows Version

19045.3693

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Is there only one item in those categories?

**Comment by mariusfranzen** [comment]
> Is there only one item in those categories?

Yep

**Comment by Josh65-2201** [comment]
Thanks for the information, merging with #13245. You can check there or click subscribe in the right sidebar for updates.

The items are loaded and cached on startup. This is just an animation issue.
