### ISSUE TITLE
Add Library Support

### ISSUE THREAD

**Issue by Jiang10086** [files-community/Files#14092]
### What feature or improvement do you think would benefit Files?

Windows Explorer's library is of great use, wish it could also be synced and showed in the Files, it can access all folder of the same type quickly.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.0.5.0

### Windows Version

Windows 11 22H2 (22621.2715)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, you can already use libraires. Right click the sidebar blank space and enable it

**Comment by yaira2** [comment]
Is there a way we can make this easier to discover? For example, perhaps we can load them by default if it's already enabled in File Explorer.
