### ISSUE TITLE
not able to search sub-folder

### ISSUE THREAD

**Issue by Shengwuei** [files-community/Files#14091]
### Description

see below,  I have two files :

- D:\Test\test1.txt
- D:\Test\subfolder\test2.txt

![image](https://github.com/files-community/Files/assets/140904608/4f751509-808d-42b7-8b0c-117add93872e)
![image](https://github.com/files-community/Files/assets/140904608/8efbc6bc-53d7-47d8-824d-cdcba88d1405)

and if I search "test" under D:\Test, only "test1.txt" was found, "test2.txt" was not found
![image](https://github.com/files-community/Files/assets/140904608/02660245-deca-40fd-91c6-13ab724e5058)

finally I confirmed that only the files under the search folder can be found, files under sub-folders were not able to be found, is this normal or not ?

Thanks.

### Steps To Reproduce

search any file, only the files under the search folder can be found, files under sub-folders were not able to be found,

### Requirements

be able to search the files under sub-folders

### Files Version

3.0.5.0

### Windows Version

Windows 11, 22H2

### Log File

[debug.log](https://github.com/files-community/Files/files/13470098/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Files uses the same system as Windows File Explorer and does search subfolders. However it slow.
- Can you check that the tab icon isn't a loading circle
- Can you see if there found when searching in Windows File Explorer

**Comment by Shengwuei** [comment]
Hi @Josh65-2201 

Can you check that the tab icon isn't a loading circle
>> not a loading circle

Can you see if there found when searching in Windows File Explorer
>> sorry my Windows File Explorer is not working...

thanks.

**Comment by yaira2** [comment]
@Shengwuei do you have "enhanced indexing" turned on in Windows? This option is more resource intensive but you'll get better results when searching for files.
![image](https://github.com/files-community/Files/assets/39923744/fbecb98a-dda8-4ece-839f-bb598f047cf9)

**Comment by Shengwuei** [comment]
> @Shengwuei do you have "enhanced indexing" turned on in Windows? This option is more resource intensive but you'll get better results when searching for files. ![image](https://private-user-images.githubusercontent.com/39923744/291405351-fbecb98a-dda8-4ece-839f-bb598f047cf9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NTAzNDMsIm5iZiI6MTcwMjk1MDA0MywicGF0aCI6Ii8zOTkyMzc0NC8yOTE0MDUzNTEtZmJlY2I5OGEtZGRhOC00ZWNlLTgzOWYtYmI1OThmMDQ3Y2Y5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDAxNDA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2ZDBhNDJjNzY0NTA0NDFiOWYzODVlMjk1MDg0ZWZmMjk1MDA1ZjE4N2I3NTBkOTZkZDQ0ZjdmODkyODg4MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rAy5mYxB_Mfp-aZD5yiamrNL5KbjIEDRqSp4TzitgYI)

sorry and it is strange that I didn't find the "find my files" setting, I am using version 3.0.5.0, thanks.
![image](https://github.com/files-community/Files/assets/140904608/0d4a75f7-cc9e-494d-a464-4472857d7235)

**Comment by yaira2** [comment]
The option I mentioned is in the Windows Settings app.

**Comment by Shengwuei** [comment]
> The option I mentioned is in the Windows Settings app.

okay I found the setting and set to "enhanced", but the problem is the same
the problem is sub-folders are not included in the search, I don't consider the problem is related to the "find my files" setting

**Comment by yaira2** [comment]
It can take a little bit of time for Windows to index the folders. You can view the current progress in the Settings app.
![image](https://github.com/files-community/Files/assets/39923744/6093d7d6-1d8f-4fea-9863-736206958963)

**Comment by Shengwuei** [comment]
> It can take a little bit of time for Windows to index the folders. If it's still not working, it's possible the drive isn't being indexed at all and you'll have to add to the Windows search index.

Hi Yaira2,

looks like it will take many days to finish the indexing, below is current status
![image](https://github.com/files-community/Files/assets/140904608/a0d4babc-ba1a-413a-a85a-5d98fec0172b)

I just tried to search again, but still found that the app did not attempt to search sub-folders(got the "No items found" result immediately right after I press enter to search), not sure if it would make any difference if I waited for the indexing to be completed, just for your reference, thanks.
![image](https://github.com/files-community/Files/assets/140904608/b23f5a4c-dbdb-41d8-b4b8-a59a0bc90237)

**Comment by yaira2** [comment]
It's likely that it isn't indexed yet, you can make it a little more aggressive by turning off the option to respect power settings, but it still might take a while for Windows to catch up. Let me know what happens after it finishes indexing the files.
![image](https://github.com/files-community/Files/assets/39923744/043a7c07-8c94-43ce-b150-e464663a4dbf)

**Comment by Shengwuei** [comment]
Hi Yaira2,

Just let you know the indexing was finally completed, but the files app still does not find contents in sub-folders, thanks.

![image](https://github.com/files-community/Files/assets/140904608/55cd1b91-2775-4737-ac29-b8dc83dc2402)

**Comment by yaira2** [comment]
Can you try testing in the "downloads" folder? I'm wondering if there is also a permissions issue.

**Comment by Shengwuei** [comment]
> Can you try testing in the "downloads" folder? I'm wondering if there is also a permissions issue.

I created a "test" folder under Download folder, and add a file "my_test.txt" in this folder
![image](https://github.com/files-community/Files/assets/140904608/125d6a79-7258-4ecd-ad4e-84909ac84bb6)

then search "test" under the Download folder, BOTH the "test" folder and the "my_test.txt" file under "test" folder are found, so it looks correct
![image](https://github.com/files-community/Files/assets/140904608/8706ba43-9961-493c-a830-d5b2ebe190ff)


Then I go back to a normal folder named "Datasheet", find "test" under this folder, and amazingly a circle is running on the upper-left corner showing the files app starts to look into the sub-folders
![image](https://github.com/files-community/Files/assets/140904608/1b2c9ea9-0a83-4eb0-9d70-62e28d9a7dff)

finally a lot of folders/files with "test" are found
![image](https://github.com/files-community/Files/assets/140904608/39dd5162-90b3-4a39-9cb1-7bf31789920e)

it is strange to me that previously the files app does NOT find sub-folders but now it does, I cannot tell anything that I had done to the files app during these tests, anyway I am glad it works correctly now, thanks.

One thing to be noted is, it seems the files app shows searching result AFTER all the folders/files are scanned, so when there are a lot of folders/files to be searched it may takes minutes to get the searching result. On the other hand, I am also using other file explorers, when searching a large amount of folders/files, the searched result is displayed each time a new matching is found, this behavior is much more responsive when searching a large folder, thanks.

**Comment by yaira2** [comment]
> One thing to be noted is, it seems the files app shows searching result AFTER all the folders/files are scanned, so when there are a lot of folders/files to be searched it may takes minutes to get the searching result. On the other hand, I am also using other file explorers, when searching a large amount of folders/files, the searched result is displayed each time a new matching is found, this behavior is much more responsive when searching a large folder, thanks.

Thanks for getting back to us. Search performance is something we're hoping to improve but we're glad that it's displaying the files now.
