### ISSUE TITLE
OneDrive network shortcuts not loading properly

### ISSUE THREAD

**Issue by soleon** [files-community/Files#14107]
### Description

I have a folder in my OneDrive that contains some network shortcuts. These shortcuts can be created by "New > Shortcut" then enter a network location such as `\\host-name\c$\folder-name`. Each time I browse to this folder, only some of the shortcuts show up in Files.

After some testing, it seems that the shortcuts won't show in Files if the network location is not available at the time of opening the folder.

![image](https://github.com/files-community/Files/assets/780800/8d148827-0fe6-4e46-b480-24c87b9ec74b)

### Steps To Reproduce

1. Create a shortcut in OneDrive that points to a network location in Windows File Explorer.
2. Bring the network location offline or change the credential of the network location.
3. Navigate to the OneDrive folder in Files.

### Requirements

All network location shortcuts in OneDrive folder should be visible regardless of the availability of the network location.

### Files Version

3.0.12.0

### Windows Version

10.0.22631.2715

### Log File

[debug.log](https://github.com/files-community/Files/files/13494667/debug.log)

**Comment by yaira2** [comment]
Thanks for the report, I think we're tracking this in another issue but I don't recall the issue number.

**Comment by Josh65-2201** [comment]
There was comment about this but not a full issue on it here https://github.com/files-community/Files/issues/13353#issuecomment-1729941797 and mabey related #12626

**Comment by yaira2** [comment]
It's likely related, let's continue tracking this in #13353.
