### ISSUE TITLE
Installation fails with "There are no more endpoints available from the endpoint mapper"

### ISSUE THREAD

**Issue by Swarkin** [files-community/Files#14106]
### Description

Installation does not complete.
![image](https://github.com/files-community/Files/assets/102416174/ea3456cf-0010-4898-ba24-e0640b65b3b9)

### Steps To Reproduce

Launch Files.Stable.exe.

### Requirements

I expect the installation to succeed.

### Files Version

3.0.8.0

### Windows Version

10.0.19045

### Log File

![image](https://github.com/files-community/Files/assets/102416174/97f5d0f2-3109-4985-b661-8d4a999642de)

That log path does not exist on my system.

**Comment by Josh65-2201** [comment]
Thanks for the report, have you install a unofficial (like Atlas OS) or modified (like disabled windows update, removed the Microsoft store, used a debloat program/script etc.) version of Windows?

**Comment by Swarkin** [comment]
Yes, Im running a debloated install that I made.
I've tried enabling all related services and policies that I found but to no success. I guess microsoft store is required?

**Comment by Swarkin** [comment]
Is there no self contained exe to install this? So far, Ive never seen this installation dialog ever..

**Comment by Josh65-2201** [comment]
No as Files is package app and not a exe. The Microsoft store isn't needed but since these unofficial installs remove many thing that shouldn't be it usually not going to work.

**Comment by CortexReaver** [comment]
Having same issue here. Just an exe-installer would be great, if this is possible.

**Comment by CortexReaver** [comment]
Hm, maybe there is an microsoft store emulator exists somewhere...
