### ISSUE TITLE
Tab name unreadable on dark background

### ISSUE THREAD

**Issue by dhruvErryDrew** [files-community/Files#14105]
### Description

When the background color is a darker hue and the theme is set to light, the tab title text color is still black, so gets hard to read sometimes.

![Screenshot (336)](https://github.com/files-community/Files/assets/98417039/f3619e4b-0423-4ee7-a3a0-5c6863f9d027)

### Steps To Reproduce

1. Set theme to light
2. Choose a dark background color
3. Open multiple tabs

### Requirements

When background color is darker than a certain shade, lighten the tab title text color.

### Files Version

3.0.8.0

### Windows Version

10.0.19045.3448

### Log File

[debug.log](https://github.com/files-community/Files/files/13492639/debug.log)

**Comment by yaira2** [comment]
@dhruvErryDrew this is by design, dark background colors are best paired with dark mode.
