### ISSUE TITLE
File transfer dialogue shows incorrect information

### ISSUE THREAD

**Issue by isaacramthal** [files-community/Files#14102]
### Description

While transferring a Windows 11 iso from my pen drive to my hard drive it shows the source file size in TB instead of GB.

### Steps To Reproduce

1.  Copy Windows 11 ISO from an external pen drive
2.  Paste it on any folder in your hard drive
3. Open transfer Dialogue to see the bug.

### Requirements

- e.g. Fix wrong information that occurs when transferring large files.
![Screenshot 2023-11-28 224503](https://github.com/files-community/Files/assets/8232978/ab8082db-2209-45aa-b66d-6523f9cc819a)

### Files Version

3.0.8

### Windows Version

23H2

### Log File

[debug.log](https://github.com/files-community/Files/files/13491351/debug.log)

**Comment by yaira2** [comment]
Thank you for the report, we're tracking this issue in #13891.

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
