### ISSUE TITLE
Google Drive doesn't show up under Cloud Drives

### ISSUE THREAD

**Issue by swoodvitsoe** [files-community/Files#14100]
### Description

I have Google Drive for Desktop installed, which makes Google Drive available as logical drive G:.  I also have OneDrive installed. Only OneDrive shows under Cloud Drives - I have to navigate to G: to locate Google Drive.

### Steps To Reproduce

1. Open Files App with both Google Drive for Desktop and OneDrive installed.
2. Only OneDrive appears under Cloud Drives.

### Requirements

Google Drive should show up under Cloud Drives

### Files Version

3.0.8.0

### Windows Version

10.0.22631.2715

### Log File
[debug.log](https://github.com/files-community/Files/files/13490146/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, this has been fixed in the preview builds. https://files.community/download

**Comment by yaira2** [comment]
@Josh65-2201 the only change in preview was to hide it from the regular drives section, this issue sounds like it's not showing up at all.

**Comment by Josh65-2201** [comment]
Sorry, misread it

**Comment by yaira2** [comment]
@swoodvitsoe is Google Drive open on your device?

**Comment by swoodvitsoe** [comment]
If by open, you mean was I browsing the files - no. It is available via logical drive G but doesn't appear under Cloud Drives at all.

**Comment by yaira2** [comment]
@swoodvitsoe I meant is the Google Drive client opened in the background?

**Comment by yaira2** [comment]
@swoodvitsoe
