### ISSUE TITLE
Duplicate the circular progress bar on top of files part of an operation

### ISSUE THREAD

**Issue by superluig164** [files-community/Files#14110]
### What feature or improvement do you think would benefit Files?

Similar to MacOS and some Linux distros - show a circular progress bar not unlike the one on the icon of the status center on top of any files currently part of an operation.  If a file is part of a multi-file operation, the progress bar should be the progress of just that file, so say you drag a bunch of files to be moved somewhere, each of the progress circles will expire as that file becomes fully moved and becomes solid.  I envision the file fading out like it does when you cut, with the progress circle on top, and optionally perhaps the percentage in the middle, though I'm really not convinced that's necessary.  After all you can always open the status center to see the progress in more detail.

### Requirements

- Ability to draw a progress bar on top of a file icon.

### Files Version

3.0.8.0

### Windows Version

10.0.22631.2715

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Can you see if #12699 is the same as your request.
