### ISSUE TITLE
Add an area for window movement between tabs and the edge of the window, like in chrome

### ISSUE THREAD

**Issue by Ray-scatter** [files-community/Files#14112]
### What feature or improvement do you think would benefit Files?

If the number of tabs increases and fills up to the right edge of the window, it is inconvenient because the only space available to move the window is the right edge.
As in chrome, an area between tabs and the edge of the window should be added as an area for window movement.

### Requirements

As in chrome, an area between tabs and the edge of the window should be added as an area for window movement.

### Files Version

3.0.8.0

### Windows Version

10.0.22631.2715

**Comment by yaira2** [comment]
Thanks for the feedback, this used to be possible but it seems that Microsoft disabled this behavior in a recent WinUI update and there isn't anything we can do from our side. It's possible that they'll bring it back in a future update but we suggest opening a feature request on the WinUI repo.
