### ISSUE TITLE
Add strings for drive types

### ISSUE THREAD

**Issue by XPoppyX** [files-community/Files#1411]
Add strings for drive types so you have the ability to translate

**Comment by yaichenbaum** [comment]
@XPoppyX Is this something you would like to work on?

**Comment by XPoppyX** [comment]
@yaichenbaum Not this time, I don't know how to make them translatable

**Comment by nvi9** [comment]
Hi, I can start working on this soon if the [proposed solution here](https://github.com/files-community/Files/issues/3457#issue-802684987) is good enough

**Comment by yaichenbaum** [comment]
@XPoppyX This feature was implemented with #3466.
