### ISSUE TITLE
List view (similar to issue #13442)

### ISSUE THREAD

**Issue by wrishel** [files-community/Files#14117]
### What feature or improvement do you think would benefit Files?

The ONLY thing I miss in Windows File Explorer is the List view. It is extremely useful when managing very large directories. 

This would also be a solution to request #13442.

I'm not sure how to fulfill the requirement to "include a list of changes" but this might be what you want.
- create a very compact view that only shows file names with the smallest size icons.
- add this view under the layout icon in the toolbar.

I'm not sure what is expected under Requirements, below. Please advise if I should modify this perhaps giving exemplars.

These screenshots show how the feature is implemented in Windows Explorer. I'm not concerned that it be implemented exactly the same way, just to have a convenient and intuitive way to invoke the view.

![Screenshot 2023-11-29 100437](https://github.com/files-community/Files/assets/2015163/db2613c7-cbb1-4484-92b9-ce14dc2103af)
![Screenshot 2023-11-29 101051](https://github.com/files-community/Files/assets/2015163/abdd70e0-43ce-4035-b58a-ca8bba68ee2b)

### Requirements

- This proposal will make it easier to peruse and manage large directories of similarly named files.
- This proposal will add support for sysops.

### Files Version

3.0.8.0

### Windows Version

10.0.22631.2715

### Comments

Screenshots of the view in Windows Explorer are provided above.

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #2509. You can check there or click subscribe in the right sidebar for updates.

**Comment by wrishel** [comment]
Thanks for the immediate response. The issue to which it is linked and other similar issues are marked closed, although the feature is not available. Does this mean the request was denied or that it is planned for a future version?

**Comment by Josh65-2201** [comment]
It still planned, the issue I linked isn't closed. Other ones were merged with that one also.

**Comment by wrishel** [comment]
Thanks, Josh!

-- Wes

**Comment by yaira2** [comment]
@wrishel thank you for your patience, I'm excited to share that a List View layout will be included in the next release.
