### ISSUE TITLE
External Sharepoint not showing under Cloud Drives

### ISSUE THREAD

**Issue by SNIT-Lars** [files-community/Files#14113]
### Description

After synchronizing an external sharepoint site to my computer, it doesn't show up under Cloud Drives.
When i open File Explorer i can see the site normally.

### Steps To Reproduce

1. Sync external sharepoint site
2. Observe Cloud Drives-section in Files-application

### Requirements

Sharepoint site should show up under Cloud Drives after sync

### Files Version

3.0.8.0

### Windows Version

Versjon	Windows 10 Enterprise Versjon	22H2 Installert den	‎16.‎02.‎2023 Operativsystembygg	19045.3570 Opplevelse	Windows Feature Experience Pack 1000.19052.1000.0

### Log File

[debug.log](https://github.com/files-community/Files/files/13501610/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, do you have only that SharePoint added or multiple (Including OneDrive)

**Comment by SNIT-Lars** [comment]
I have 3 different entries that show up (1 personal Onedrive and 2 internal Sharepoint Sites). But i have 4 in total, counting the external Sharepoint Site

**Comment by Josh65-2201** [comment]
We're tracking issues with multiple share points in #4966. You can check there or click subscribe in the right sidebar for updates.
