### ISSUE TITLE
Remember network drives and folders

### ISSUE THREAD

**Issue by SteveThackery** [files-community/Files#14121]
### What feature or improvement do you think would benefit Files?

When clicking on "Network" in the left pane, there is a long pause (several seconds) while it discovers all the drives and servers on the network.  Even when discovered, they don't appear as a tree under the Network icon in the left pane.  The next time I open Files, it has to re-discover all the network drives, which again takes several seconds.  These long pauses are so frustrating and time-wasting.

On the same computer, Windows File Explorer remembers the network drives, plus it lists them as a tree under the Network icon, so access to drives, folders and files is effectively instant.

Please make Files work like File Explorer in this regard - it would be a great improvement.  Screenshots show the difference.

![Files network view](https://github.com/files-community/Files/assets/79258223/ed60ccf1-4982-47a4-bb1e-13e8ec34e775)
![File Explorer network view](https://github.com/files-community/Files/assets/79258223/b69f0711-380b-4dab-a8ad-b6b7b302e4ae)

### Requirements

Two aspects to this request:

1/ Remember the network servers and drives, so there is no delay

2/ Display them as a tree under 'Network' in the left pane, for rapid access

Both of these are how File Explorer does it.

### Files Version

3.0.8.0

### Windows Version

10.0.22631.2715

### Comments

If you are concerned that some of the network servers and drives may disappear (or appear) between sessions, thus rendering the remembered list out of date, I suggest a behaviour a bit like File Explorer, where it displays the remembered list immediately, and I believe scans the network in the background to update the list if necessary.

**Comment by yaira2** [comment]
Thank you for your feedback, we're tracking this request in #8304.
