### ISSUE TITLE
Bug: Typo in original localization

### ISSUE THREAD

**Issue by QuaintMako** [files-community/Files#14128]
### Description

The `ToggleInfoPaneDescription` has a typo inside the localization. The backslash should be a slash
```
  <data name="ToggleInfoPaneDescription" xml:space="preserve">
    <value>Toggle the info pane to view the detail\preview panes</value>
  </data>
```

### Steps To Reproduce

See EN-US localization.

### Requirements

- Fix typo in EN-US resource file.

### Files Version

3.0.14

### Windows Version

10.0.19045.3324

### Log File

N/A

**Comment by yaira2** [comment]
I'm fine with it either way, do you want to open a PR?

**Comment by yaira2** [comment]
This is resolved in `main`.
