### ISSUE TITLE
Can you provide a git feature switch? It greatly affects performance.

### ISSUE THREAD

**Issue by mokeyjay** [files-community/Files#14126]
### What feature or improvement do you think would benefit Files?

a git feature switch
When I browse some larger directories (such as the node_modules in front-end js projects), the files take a lot of time to check the git status, which greatly affects the usage

### Requirements

Perhaps this could be done on a separate thread? At least it should not affect graphical operations.

### Files Version

3.0.8.0

### Windows Version

10.0.22631.2715

**Comment by Josh65-2201** [comment]
Thanks for the feedback, The preview builds have performance improvements to Git features https://files.community/download You can also turn them off by right clicking the name header in the details layout > Git > Disable all or some of the options
