### ISSUE TITLE
Bug: Dragging from 7zip window does not work

### ISSUE THREAD

**Issue by yIsItSo** [files-community/Files#14125]
### Description

Unable to drag a file from a 7Zip window to a folder in Files

### Steps To Reproduce

1. Open a 7Zip window
2. Drag to a folder in Files
3. --> error: File not found
(works in explorer)

### Requirements

It should work

### Files Version

3.0.13.0

### Windows Version

10.0.22635.2776

### Log File

[debug.log](https://github.com/files-community/Files/files/13510545/debug.log)

**Comment by coasternd** [comment]
Having the say issue here, its really frustrating.

**Comment by yaira2** [comment]
We need some help with this one

**Comment by yIsItSo** [comment]
Dragging from 7zip to folder

[image: image.png]

**Comment by yaira2** [comment]
A fix will be included in the next release
