### ISSUE TITLE
Error when installing V3 on Windows 10

### ISSUE THREAD

**Issue by Asturias76** [files-community/Files#14131]
### Description

As there is no indication if V3 is only working on Windows 11, I don't know if it's a bug. I can't install V3 on Windows 10 x64 Pro. Translation : "Installation failed. Contact your software provider".

![Files_v3_bug](https://github.com/files-community/Files/assets/29236723/bb4f4faf-61ff-454f-a249-e30205247b81)

### Steps To Reproduce

Launch Files.stables.exe on Windows 10 x64 Pro 22H2

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.0.8

### Windows Version

Windows 10 x64 22H2

### Log File

No log

**Comment by Josh65-2201** [comment]
You can try
1. Opening PowerShell as administrator
2. Run this command
```Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/stable/Files.Package.appinstaller```
3. See if Files is in the start menu all apps section

**Comment by Asturias76** [comment]
Thanks. It works but why it doesn't work with the regular installer ?

**Comment by Asturias76** [comment]
Ok. For the next update, I have to do the same thing ?

**Comment by Josh65-2201** [comment]
Properly not, the app has auto update but if it doesn't work then yes just close Files and run the PowerShell command

**Comment by Asturias76** [comment]
Ok thanks.

**Comment by ShahriarKh** [comment]
Thanks @josh65-2201!
I think adding this alternative solutions to somewhere like a troubleshooting guide may be useful for new users.
