### ISSUE TITLE
Feature: Add a reverse panel order button

### ISSUE THREAD

**Issue by pablo-hp** [files-community/Files#14133]
### What feature or improvement do you think would benefit Files?

Since you mentioned that it will improve the function of the double panel, I suggest creating a button to invert the panel.
Send the panel from left to right and from right to left.
This is useful for when you need to reverse the order of the panels.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.0.8.0

### Windows Version

10.0.22621.2715

**Comment by yaira2** [comment]
@pablo-hp

**Comment by Josh65-2201** [comment]
I'm pretty sure they mean the duel pane.

**Comment by yaira2** [comment]
We don't have plans for this right now but we can reconsider if there is more interest.
