### ISSUE TITLE
Bug: Can't pin OneDrive Desktop to favorites

### ISSUE THREAD

**Issue by KristianJ79** [files-community/Files#14136]
### Description

I keep my dekstop in the cloud on OneDrive. I can pin any folder in my OneDrive to my favourites except my desktop, so I have managed to recreate every link from my Quick Access list in Windows Explorer in Files, all except the desktop, but I've no idea why

### Steps To Reproduce

Go to OneDrive
Right click the Desktop icon
Select 'Add to Favourites'

### Requirements

Make OneDrive Dektop folder pinnable to Favourites

### Files Version

3.0.8.0

### Windows Version

10.0.22621.2715

### Log File

[debug.log](https://github.com/files-community/Files/files/13532086/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
@KristianJ79 does it work if you pin it in File Explorer?

**Comment by KristianJ79** [comment]
> @KristianJ79 does it work if you pin it in File Explorer?

Hi @yaira2 You mean the Windows native File Explorer? 
Yes it does.

**Comment by yaira2** [comment]
Does it display in Files?

**Comment by KristianJ79** [comment]
@yaira2 Yes. I can navigate to the folder and open it/access all the files etc. It just won't pin to the favourites bar no matter how many times I try!

**Comment by yaira2** [comment]
I meant does it show in favorites in Files if you pin it in File Explorer?

**Comment by KristianJ79** [comment]
@yaira2 Ah, I see what you mean, apologies. Yes, it's already pinned in File Explorer

**Comment by KristianJ79** [comment]
@yaira2 No, that's the whole issue. It's pinned to Quick Access in Windows Explorer but won't pin to favourites in Files. I can navigate to and interact with the folder, I just can't pin it.

**Comment by KristianJ79** [comment]
@yaira2 I don't know if someone has fixed the bug, but when I opened my laptop today, my Desktop icon is now magically pinned to favourites! Shall I close the matter or wait for someone else to confirm?

**Comment by yaira2** [comment]
We recently released v3.0.15 so while we didn't specifically include a fix for this issue, it may have been fixed by another change.
