### ISSUE TITLE
Right click inoperative

### ISSUE THREAD

**Issue by Zouf4** [files-community/Files#14134]
### Description

Right click, "Open with" on files does nothing. Contextual menu settings all set 'on'. 

### Steps To Reproduce

Open app
Right click on any file.
Select Open With option

### Requirements

Expect list of possible apps to open.

### Files Version

3.0.8.0

### Windows Version

10.0.22621.1702

### Log File

[debug.log](https://github.com/files-community/Files/files/13531072/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, what happens if you try with Windows File Explorer on the same file?

**Comment by Zouf4** [comment]
Very good question. Generally, it crashes… directly on right-click. There’s a number of registry and other similar fixes that sometimes are successful for a while, but this bug returns rapidly. And it’s the reason I installed Files - at least I’m not forced to use the command line interface to delete files now…
________________________________
De : Josh65-2201 ***@***.***>
Envoyé : Saturday, December 2, 2023 4:47:27 AM
À : files-community/Files ***@***.***>
Cc : Zouf4 ***@***.***>; Author ***@***.***>
Objet : Re: [files-community/Files] Right click inoperative (Issue #14134)


Thanks for the report, what happens if you try with Windows File Explorer on the same file?

**Comment by yaira2** [comment]
Files make use of the same shell extensions as in File Explorer so if something is corrupted in Windows, that would explain this issue.
