### ISSUE TITLE
Bug: "Reopen closed tab" is always disabled

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#14148]
### Description

"Reopen closed tab" is always disabled when right-clicking on a tab even if there are closed tabs. Ctrl+Shift+T works as expected though.
![image](https://github.com/files-community/Files/assets/66369541/8056c757-c7fd-406f-aa2c-c123258eee3b)

### Steps To Reproduce

1. Close a tab.
2. Right-click on a remaining tab.
3. Observe "Reopen closed tab" is disabled.

### Requirements

"Reopen closed tab" should be enabled if there are closed tabs.

### Files Version

3.0.8.0

### Windows Version

10.0.22631.2715

### Log File

n/a

**Comment by hishitetsu** [comment]
Also affects 3.0.15.0.

**Comment by yaira2** [comment]
Thanks for the report
