### ISSUE TITLE
Bug: Hitting Up arrow in the navigation bar causes the application to crash

### ISSUE THREAD

**Issue by kimagin** [files-community/Files#14146]
### Description

When the user is in the **column** view,  if you navigate up a folder by hitting the arrow up icon in the navigation bar, when it reaches the last folder and if the user hit the arrow one more time, the application will crash.

![image](https://github.com/files-community/Files/assets/54755950/23d7a64c-1b51-4706-a36e-98bea2462301)

### Steps To Reproduce

1 - Switch the view style to the column view
2 - Start navigating into the folders
3 - Hit the up arrow in the navigation bar to move back one level up
4 - Keep clicking on the up arrow button until you reach the highest level of navigation
5 - application will crash

### Requirements

The expected behavior is, that when the user reaches the highest level, it should move to the Home directory and the up arrow button should be grayed out or disabled.

### Files Version

3.0.8.0

### Windows Version

10.0.22631 Build 22631

### Log File

[debug.log](https://github.com/files-community/Files/files/13539540/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by kimagin** [comment]
> Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

Hello,
Thank you so much for your prompt reply. I've just installed the Preview version and the issue appears to be there as well.
Let me know if you need anything else and I will be happy to help.

**Comment by yaira2** [comment]
Thank you for the detailed report
