### ISSUE TITLE
Graphical display of drive capacity in PC folder

### ISSUE THREAD

**Issue by Ray-scatter** [files-community/Files#14141]
### What feature or improvement do you think would benefit Files?

I would like the drive display in the PC folder to be able to graphically display used and free space, similar to Windows.

The inconvenience of this inability to display graphically prevents complete replacement from Windows Explorer.

### Requirements

Provide an easy-to-understand graphical display of used and free space on multiple drives.

### Files Version

3.0.8.0

### Windows Version

10.0.22631.2715

**Comment by yaira2** [comment]
@Ray-scatter those are visible on the home page
![image](https://github.com/files-community/Files/assets/39923744/110dcae1-7b51-46a0-90f4-d716da49f941)

**Comment by Ray-scatter** [comment]
I just noticed the home capacity indicator, thank you.
I just have a problem.
As you can see in the attached image, the used capacity is not colored and it's not very visible.
Where is the setting to add color?
![スクリーンショット 2023-12-03 135327](https://github.com/files-community/Files/assets/147126663/78f54fbb-8549-4908-a808-d0ece9238d7c)

**Comment by Ray-scatter** [comment]
The capacity color issue is self-resolving.
I see that the color setting on the Windows side is affecting it.

So, I would like to make a related request: I would like this capacity color display to be independent of the Windows color settings.

If you change the Windows color settings just for the Files capacity color, the usual appearance of Windows will become extremely lame.

This is sorely needed😭

**Comment by Ray-scatter** [comment]
Two more requests.

I think the display size needs to be further increased, as some drives do not display all of the text display of capacity as shown in the attached image, but instead omit it.

And although it would also be the same as the first request, I would like this display method to be available for PC folders as well.
![スクリーンショット 2023-12-03 165434](https://github.com/files-community/Files/assets/147126663/ee87bce7-79e4-4b85-b05a-1b213e51c6d3)

**Comment by yaira2** [comment]
> You should not use the "Windows" accent color setting, which has a different design philosophy.

The main reason to change the color of the progress bar is to indicate when the storage is getting full. We're both a little more technical than the standard user and we know what the color indicates, but let's be honest and admit that it doesn't mean anything for the regular user (it's also not accessible for users with vision problems). Taking this into account, and the reason I mentioned earlier, this isn't something we plan to change anytime soon. I also acknowledge that there is a use case to indicate when the drive is getting full, this is why we display an info icon and shortcut to storage settings in Windows.

**Comment by yaira2** [comment]
> The full name appears when the cursor is hovered over it, but this state is inconvenient and lame as a design feature.

We're exploring other layouts for the drive cards that might address this in the future.

**Comment by Ray-scatter** [comment]
> this isn't something we plan to change anytime soon.

Roger that.
I would appreciate it if you could put it on your todo list, even if it takes a while.

> We're exploring other layouts for the drive cards that might address this in the future.

Great, looking forward to the future.
