### ISSUE TITLE
Feature: Add support for using AND in tag searches

### ISSUE THREAD

**Issue by MacrosBlack** [files-community/Files#14151]
### What feature or improvement do you think would benefit Files?

Ability to do boolean searches on tags. e.g. search for all tages with X AND Y

### Requirements

Provide AND function in the search bar for Tags
Provide OR function in the search bar for Tags

### Files Version

3.0.8.0

### Windows Version

10.0.19042.2965

**Comment by MacrosBlack** [comment]
Thanks for the reply, but I probably didn't explain myself very well - sorry. 

The use of a comma was known, but this lists everything that in your example above has a Photo or Important tag. What I meant was all tags that only have Photo AND Important as tags i.e. the intersection of the two

**Comment by yaira2** [comment]
@MacrosBlack can you try `tag:Photos and tag:Important`?

**Comment by yaira2** [comment]
That's correct, there isn't supposed to be a space between the commas.

**Comment by MacrosBlack** [comment]
Yes, I think this is exactly what I wanted. I was confused because, in the first reply, it was mentioned that a space would provide a different result (everything in both tags), but this does not work.

Many thanks for clearing this up

**Comment by yaira2** [comment]
That was probably copied from our docs which had this mistake as well, I fixed it up to prevent confusion in the future. Thanks for bringing it to our attention!
