### ISSUE TITLE
Feature: Display the trash in the sidebar

### ISSUE THREAD

**Issue by Fefedu973** [files-community/Files#14153]
### What feature or improvement do you think would benefit Files?

It would be nice if we can disaply/pin the trash directly in the sidebar so we can access it directly and move items inside quickliy like in the file explorer (i'm don't want it in my favorite section but in it's own section at the bottom of the sidebar
![image](https://github.com/files-community/Files/assets/80718477/ef02d816-47c1-4bd4-8cbc-498eae314c66)

### Requirements

- Add a toggle in the settings to display the trash at the bottom of the sidebar like this
![Capture d’écran 2023-12-04 113431](https://github.com/files-community/Files/assets/80718477/babf70f8-7462-49f9-b7d4-1e5b0eae1f66)

- We can drag and drop files inside and access it's content

### Files Version

3.0.15.0

### Windows Version

10.0.26002.1000

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Files uses the favorite system for this (Type `Shell:RecycleBinFolder` into that path bar > right click > Pin to favourites) as there isn't a good reason to implement a dedicated section and item for it.
