### ISSUE TITLE
Feature: Add Visual Studios to the status bar open button.

### ISSUE THREAD

**Issue by mariusfranzen** [files-community/Files#14159]
### What feature or improvement do you think would benefit Files?

When you open a folder with a git repo connected to it (I assume) you get an "Open" button in the bottom. There you can select "open folder in vs code" and "open repo in vs code". I would like to add the alternative to open the project in visual studio 2022 if the folder contains a .sln file

### Requirements

- Check if folder contains .sln file
- If it does, add "Open project in Visual Studio 2022" to the "Open" menu in the bottom

### Files Version

3.0.14.0

### Windows Version

10.0.19045.3448

**Comment by Josh65-2201** [comment]
Thanks for the feedback, I've added this to the project board.

**Comment by yaira2** [comment]
Thank you for your feedback, we're tracking support for other IDEs in #12857
