### ISSUE TITLE
Feature: Recommended section in home tab

### ISSUE THREAD

**Issue by Fefedu973** [files-community/Files#14158]
### What feature or improvement do you think would benefit Files?

It would be nice for work to have a feature like the recommended section in the file explorer in files
![image](https://github.com/files-community/Files/assets/80718477/930e5cab-4e71-4f77-9726-d216a601bd08)

### Requirements

- Display the files that are related to me from onedrive

### Files Version

3.0.15.0

### Windows Version

10.0.26002.1000

**Comment by yaira2** [comment]
How would we know which files to recommend?
