### ISSUE TITLE
Feature: Access folder in the sidebar using a treeview

### ISSUE THREAD

**Issue by Fefedu973** [files-community/Files#14155]
### What feature or improvement do you think would benefit Files?

It would be nice if we can access any folder only using the sidebar and navigate inside those. It would make navigating much more pleasent, easy to use, easy to move files arround by drag and drop and allow feature parity with file explorer
![image](https://github.com/files-community/Files/assets/80718477/4a51f45c-51b3-47d1-9050-2beb0becf6e3)

### Requirements

- Add a toggle in the settings to enable tree view navigation

### Files Version

3.0.15.0

### Windows Version

10.0.26002.1000

**Comment by andrew-james-heard** [comment]
Just bought Files yesterday as Explorer replacement. Couldn't check until bought. Sad not to see this feature but at least it's being discussed.

**Comment by yair100** [comment]
@Fefedu973 @andrew-james-heard Tree View is currently available in preview https://files.community/download. It will be included in the next stable release.
