### ISSUE TITLE
Feature: Display disk with capacity

### ISSUE THREAD

**Issue by Fefedu973** [files-community/Files#14157]
### What feature or improvement do you think would benefit Files?

In the "This Pc" section display the disks with how much space is left lik in the home section
![image](https://github.com/files-community/Files/assets/80718477/7450a8ad-d44c-4780-83bb-f234ccb149ae)
![image](https://github.com/files-community/Files/assets/80718477/c0d2da5b-bcce-47a5-9efa-8d300469b453)

### Requirements

- Display disks in this pc the same way as in home

### Files Version

3.0.15.0

### Windows Version

10.0.26002.1000

**Comment by Josh65-2201** [comment]
Thanks for the feedback, File doesn't have a way of interacting with the shell sections and a new layout for it doesn't make sense. Files uses it own home page which can display anything that the This PC section does.

**Comment by Fefedu973** [comment]
Ok tanks
