### ISSUE TITLE
Bug: No drives appear with DVD drive installed

### ISSUE THREAD

**Issue by tduck973564** [files-community/Files#14160]
### Description

In the drives section of the app, no drives show up when a DVD drive is installed into the computer. When the DVD drive is disabled, the drives slowly start to appear one by one after a few minutes waiting. DVD drive appears if re-enabled in Device Manager while files is open.

### Steps To Reproduce

1. Have DVD drive
2. Open app to the home screen
3. Drives will not appear, and Files will lag

### Requirements

- Fix drives not showing in the drive pane when a DVD drive is installed
- Fix drives taking a long time to show, each one by one, when DVD drive is installed but disabled

### Files Version

3.0.15.0

### Windows Version

10.0.22635.2776

### Log File

[debug.log](https://github.com/files-community/Files/files/13546041/debug.log)

**Comment by tduck973564** [comment]
Just to let you know it does suddenly seem to be working now. I haven't changed anything since

**Comment by 0x5bfa** [comment]
@yaira2 can’t this be closed now?
