### ISSUE TITLE
Bug: Adding a file to an open Files directory causes a crash

### ISSUE THREAD

**Issue by JollyRoger8X** [files-community/Files#14169]
### Description

Often, I will have an imge file open in Photoshop 2023/2024 and when I "Save As" to create a new copy of the image file, Files will crash in the background.

This happens intermittently - not for every file I save as.

### Steps To Reproduce

1. Open a folder with images in Files.
2. Open an image in this folder with Adobe Photoshop 2023 or 2024.
3. In Photoshop, choose File > Save As, and give the new file a name similar to the original (for instance add " (large)" to the name.
4. Sometimes Files crashes as a result of the new file being added to the directory. Sometimes it does not crash.

### Requirements

As a user, I expect Files not to crash when files are added to an open directory.

### Files Version

3.0.14.0

### Windows Version

10.0.19045.3324

**Comment by yaira2** [comment]
@JollyRoger8X thanks for the report, can you add the log file as an attachment?

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by yaira2** [comment]
This issue should be resolved in the next release.
