### ISSUE TITLE
Allow customization for the number of items that show in search history

### ISSUE THREAD

**Issue by ragepaw-git** [files-community/Files#14168]
### What feature or improvement do you think would benefit Files?

Currently, Files shows the most recent 5 searches in the search box. The default in Windows is 10. It would be good to be able to see more than 5.

I suggest that the ability to increase or reduce the number of searches in the history displayed, perhaps with a maximum to prevent performance issues.

### Requirements

- This proposal will allow users to configure the number of results they would like to see for search history.

### Files Version

3.0.15.0

### Windows Version

Win11 - 10.0.22621.2715

**Comment by yaira2** [comment]
Files already supports showing 10 items in the dropdown

**Comment by yaira2** [comment]
Hmm, I actually see there is a case where it is sometimes limited to 5.
