### ISSUE TITLE
Bug: Third party licenses not showing

### ISSUE THREAD

**Issue by Fefedu973** [files-community/Files#14161]
### Description

The third party licenses are not showing in the settings
![image](https://github.com/files-community/Files/assets/80718477/2df21d0f-354d-4151-a66e-2095607d9b17)

### Steps To Reproduce

1. Open settings
2. Go to about sections
3. open third party licenses and see that it dosen't shows up

### Requirements

We should see a list with the first party licenses

### Files Version

3.0.15.0

### Windows Version

10.0.26002.1000

### Log File

[debug.log](https://github.com/files-community/Files/files/13547027/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #14149. You can check there or click subscribe in the right sidebar for updates.
