### ISSUE TITLE
Feature: Recognize Tilde as %USERPROFILE%

### ISSUE THREAD

**Issue by awderh** [files-community/Files#14166]
### What feature or improvement do you think would benefit Files?

The `~` (tilde) character is interpreted by *NIX shells as the current logged in user's home directory (HOME env on *NIX). On Windows, `HOME` (afaik) is `USERPROFILE`. Given the popularity of UNIX/LINUX, this feature may be highly desirable from a user perspective.

### Requirements

- This proposal will accomplish *NIX like tilde/`~` expansion, as defined:
  - The feature only applies to the **first** path component in a sequence of path components
  - The feature is functionally defined as a substitution of `~` to %USERPROFILE%
  - The feature shall then forward this substitution to the underlying API

### Files Version

3.0.15.0

### Windows Version

10.0.22631 Build 22631

**Comment by yaira2** [comment]
Thank you for your feedback

**Comment by awderh** [comment]
I was looking through the source, and it seems like there is already functionality with `~/`:

https://github.com/files-community/Files/blob/c7c8dd508b71d7663118c44b0cae53dfafe9442a/src/Files.App/ViewModels/UserControls/ToolbarViewModel.cs#L707

Which eventually references:
https://github.com/files-community/Files/blob/c7c8dd508b71d7663118c44b0cae53dfafe9442a/src/Files.App/Utils/Storage/Helpers/StorageFileExtensions.cs#L303-L317

This is verified working; although there isn't any indication in the suggestions dropdown:
<img width="125" alt="image" src="https://github.com/files-community/Files/assets/12786951/5836e371-8740-4e9b-a0f9-dad6f98d5d7e">

However, with `USERPROFILE`, there are some (but not all) suggestions:
<img width="189" alt="image" src="https://github.com/files-community/Files/assets/12786951/77e295c5-1a16-4a31-b238-815e5263be91">
(Note: my username is `Home` )

Anyways, I'll modify the helper and submit a PR. Impact will be [here ](https://github.com/files-community/Files/blob/c7c8dd508b71d7663118c44b0cae53dfafe9442a/src/Files.App/ViewModels/UserControls/ToolbarViewModel.cs#L707)and [here](https://github.com/files-community/Files/blob/c7c8dd508b71d7663118c44b0cae53dfafe9442a/src/Files.App/ViewModels/UserControls/ToolbarViewModel.cs#L814), which I see as OK.

Maybe suggestions can be address in a different issue.

**Comment by yaira2** [comment]
> This is verified working; although there isn't any indication in the suggestions dropdown:

It works for me but only if I start typing

**Comment by awderh** [comment]
> > This is verified working; although there isn't any indication in the suggestions dropdown:
> 
> It works for me but only if I start typing

Confirmed:
![image](https://github.com/files-community/Files/assets/12786951/70638b47-1565-4f7e-bb99-e2d9695bc060)

However, and this is a "me"/*nix-user issue, it doesn't work with forward slashes:
<img width="167" alt="image" src="https://github.com/files-community/Files/assets/12786951/660d470a-1fc9-4f2f-8afd-b95ccaec6fb3">

There is a [path normalization helper](https://github.com/files-community/Files/blob/c7c8dd508b71d7663118c44b0cae53dfafe9442a/src/Files.App/Helpers/PathNormalization.cs#L34-L56), but it doesn't include conversion of `/` to `\`, presumably for generic URL support?

Anyways, `CheckPathInputAsync` does normalize forward-slashes to backslashes: https://github.com/files-community/Files/blob/c7c8dd508b71d7663118c44b0cae53dfafe9442a/src/Files.App/ViewModels/UserControls/ToolbarViewModel.cs#L688-L694

But the normalization isn't included for suggestions.

I've submitted a PR to address this: https://github.com/files-community/Files/pull/14171
