### ISSUE TITLE
Animate Files when opening a new instance of the program (Discussion)

### ISSUE THREAD

**Issue by Omnimaxus** [files-community/Files#14165]
### What feature or improvement do you think would benefit Files?

Currently, Files does not animate when opening a new window.  It would be nice to have Files animate its opening sequence (like how File Explorer opens when window animations are enabled in Windows).  To me, this would make so much sense and should be easy to implement, especially since part of the point of Files is to have a file explorer that fits in better, aesthetically speaking, with Windows than Windows File Explorer does.  I hope this is done with the next release (whenever that will be).  Thanks.

### Requirements

N/A

### Files Version

3.0

### Windows Version

Windows 11 23H2

### Comments

N/A

**Comment by yaira2** [comment]
Thanks for the feedback, I'm a fan of animations myself, but the overwhelming feedback from users is that startup should be as fast as possible without any animations.

**Comment by Omnimaxus** [comment]
Well, can you make it an option, at least?  And a big thank you for such a speedy response, too.

**Comment by Dark-Peace** [comment]
Great, we found another way to reduce performances...

**Comment by yaira2** [comment]
> Well, can you make it an option, at least? And a big thank you for such a speedy response, too.

If there is enough interest

**Comment by VijeshDatt** [comment]
Having the ability to set the opening animation as an option would be ideal but as someone who deals with files a lot during their day for work, having the speediest startup possible is a must. At a certain point, you forget that the animations are even there when you're focused on the task at hand

**Comment by xsm2** [comment]
I don't think it will penalice performance too much, at least in my experience files' start up times are usually pretty fast and most performance problems appear when browsing folders (specially when you enter an uncached folder or one with a significant number of files). That said I'm using a Ryzen 5900X, so I understand that my performance it's probably abobe the average.

**Comment by heftymouse** [comment]
This is an unintentional side effect of showing an existing window instead of creating a new one. Should this be considered a bug?

**Comment by RihanArfan** [comment]
The animation should follow the Windows 11 pop-in animation used by other applications. Try opening Microsoft store, for example, and see how it zooms in quickly. https://fluent2.microsoft.design/motion

**Comment by Omnimaxus** [comment]
> I may have misunderstood, are you talking about animating the content in Files, or did you mean the window itself?

The window itself. Glad you asked to clarify.

**Comment by nopeless** [comment]
My two cents: unless the loading screen actually tells me useful information, it is not needed.

Here are useful loading screens
- pgadmin: shows what modules are being loaded at the time
- FML: shows which step the mod initialization is in
- gradle build: shows what threads are doing
- that one gacha game I'm playing: tells me which stage uses data or not

For files I sometimes see slow startup, and it would be nice to see and feel what exactly prevents it from initializing faster.
