### ISSUE TITLE
Bug: Delete button cropped in tags confirmation flyout

### ISSUE THREAD

**Issue by Fefedu973** [files-community/Files#14162]
### Description

When I want to delete a label in the setttings the delete button is cropped and the hover animation is bugged

https://github.com/files-community/Files/assets/80718477/b5c4cb64-5309-4140-a864-f1d7de6df692

### Steps To Reproduce

open settings
go to labels
click delete on one of the label
see the popup with bugged buttons

### Requirements

fix the button look and animation

### Files Version

3.0.15.0

### Windows Version

10.0.26002.1000

### Log File

[debug.log](https://github.com/files-community/Files/files/13547080/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.
