### ISSUE TITLE
Have an easily-accesible feedback form/page

### ISSUE THREAD

**Issue by 69RandomDude69** [files-community/Files#14174]
### What feature or improvement do you think would benefit Files?

Have an easily-accessible feedback form/page - I had to create a GitHub account to simply be able to provide three pieces of feedback. I would suggest most users -especially non tech-savvy- users will likely just move on, potentially abandon the app all-together. This in particular where the UNC path is concerned. The app is awesome -don't get me wrong-, but such a seemingly small functionality let's it down significantly. I -like many others- I am raising a concern about this yet again. Others may do the same, realize it's a pain in the arse to even provide feedback and decide it's just easier to move on. Probably not what the community would want as you never know how significant/important the feedback may be that you miss out on.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.0.15.0

### Windows Version

10.0.19045.3693

**Comment by yaira2** [comment]
Thanks for the feedback, ideally we'd have something like this in place, but the problem is that we wouldn't have a way of communicating with the user. Often times we have follow up questions, or at least want to respond to thank the user for their feedback and to let them know that we added their suggestion to the todo list.

By using GitHub, it allows the user to search for similar feedback before they make their request and it also makes it available for other contributors to see the feedback and open pull requests to address it.

**Comment by 69RandomDude69** [comment]
Thanks for the response. Whilst it may seem like a bit of a task from the outset, I would start with a name change, domain reg., the hosting will provide for emails in most cases, key staff access to emails, and issue resolved. High level and as such a bit loosey-goosey, but likely get the drift. You could potentially still tie it all back to github in the back end. Either way, I am just conscious of the loops required for the average user to try and obtain support, provide feedback and so forth,. Let's face it, git hub is dev. and IT fold aimed, not average 'joe blow'. 

Anyways, sorry if I may have overstepped a line of sorts; just really like the project and would love to see it gain market share and go places which I feel may be severely impacted at this point by name and marketing/reachability.

**Comment by yaira2** [comment]
Another factor to consider is that users can already submit feedback via the Microsoft Store (many users do) & on our Discord server. We prefer GitHub as it allows us to better manage the feedback, but I do my best to read and respond to every issue in the Store. I'm not going to rule this out in the future but in the meantime, I don't think we have the resources to manage another feedback spot right now.
