### ISSUE TITLE
Bug: Sidebar is stuck in the wrong state

### ISSUE THREAD

**Issue by daishanrenL** [files-community/Files#14178]
### Description

![2023-12-05_14-56-23](https://github.com/files-community/Files/assets/112452799/eab65f64-50e5-4702-a6dc-472928502fa2)

### Steps To Reproduce

Hide the area on the left, sometimes this happens when opening the software. Also, I personally feel that the area on the left doesn't look as good as before the larger version, and the icons seem very small

### Requirements

I hope it can be fixed. I often encounter this bug

### Files Version

3.0.15.0

### Windows Version

10.0.22631.2792

### Log File

[debug.log](https://github.com/files-community/Files/files/13556285/debug.log)

**Comment by daishanrenL** [comment]
> @daishanrenL what happens if you reset the app?
> 
> We're tracking support for changing the item size in #13954

It's not useful, restarting will still display an error, only when I drag it will it display as it is

**Comment by daishanrenL** [comment]
> Are the any steps to consistently reproduce this issue?

No, there is only a probability that this situation will occur every time it is opened

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by yaira2** [comment]
Can you also confirm if the app is opening with a maximized window when this issue occurs?
