### ISSUE TITLE
Recommend renaming the project/application from 'Files' to something else

### ISSUE THREAD

**Issue by 69RandomDude69** [files-community/Files#14173]
### What feature or improvement do you think would benefit Files?

This is a personal opinion, however most likely shared by anyone looking for support on the Files application.

Where from the outset it seems like an excellent as well as appropriate name for the application, in practice it makes it almost impossible to try and search/'google' for support on the product. Where this may be on purpose to try and force the 'Files' community/users to use the 'community', it is not practical to expect all users to be creating github and/or discord accounts for support

### Requirements

Rename the application to something more 'searchable'. FFSNav (File Folders Navigator), WinCommander (Windows Commander), etc... comes to mind. However literally anything would be better suited than 'Files' in this case. 

Microsoft use File Explorer, Apple uses Finder, Linux has Nautilus and so forth. What is common amongst all these is that none of them use the purpose/or part there-of as the name. ie. you would be hard pressed to locate service data on a vehicle named 'car' or 'vehicle'.... or try and download drivers for a laptop model 'laptop'... and so forth.

### Files Version

3.0.15.0

### Windows Version

10.0.19045.3693

**Comment by yaira2** [comment]
Thanks for the feedback, we've discussed renaming in the past and even ran some polls to gather some ideas, but the overwhelming feedback was that we should keep the name as "Files". In general, you can find documentation our https://files.community/ or by searching online for "Files App".
