### ISSUE TITLE
Implement Switch Tabs Keyboard Shortcuts with Ctrl + Page Up / Page Down

### ISSUE THREAD

**Issue by raynerdacruz** [files-community/Files#14184]
### What feature or improvement do you think would benefit Files?

Personally, I use Ctrl + Page Up & Ctrl + Page Down keyboard shortcuts to switch tabs in a browser instead of Ctrl + Tab & Ctrl + Shift + Tab, as they're ergonomically placed on my keyboard. It would be nice if someone could implement them.

### Requirements

Add new KeyPressEventListeners and map the actions as follows: 
switch tab right action -> Ctrl + Page up.
switch tab left action to Ctrl -> Page Down.

### Files Version

3.0.15

### Windows Version

10.19041.3693

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #9559. You can check there or click subscribe in the right sidebar for updates.
