### ISSUE TITLE
Slide attachment from Outlook to File does not work

### ISSUE THREAD

**Issue by frriv31** [files-community/Files#14185]
### Description

Can't slide an attachment from outlook to file.  It does not work.  I have to select and hit copy.  then paste into file.  then hit F5 to refresh.  if no.  can't see it.
The status centre say that it has been copied after sliding.  but it is not

### Steps To Reproduce

1. select attachment from outlook and hold left mouse button.
2.  slide to the file app and release the left mouse button
3. status centre says it has been completed
4. hit F5 and no files have been copied.

### Requirements

Can't slide an attachment from outlook to file.  It does not work.  I have to select and hit copy.  then paste into file.  then hit F5 to refresh.  if no.  can't see it.
The status centre say that it has been copied after sliding.  but it is not

### Files Version

3.0.15.0

### Windows Version

10.0.19045.3693

### Log File

[debug.log](https://github.com/files-community/Files/files/13574146/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #13646. You can check there or click subscribe in the right sidebar for updates.
