### ISSUE TITLE
Feature: Don't open root for libraries

### ISSUE THREAD

**Issue by xmha97** [files-community/Files#14189]
### What feature or improvement do you think would benefit Files?

# ❌ Actual Behavior
![image](https://github.com/files-community/Files/assets/23485114/5c516ae2-954e-4498-87f9-c4b7366aaea7)

# ✔️ Expected Behavior
![image](https://github.com/files-community/Files/assets/23485114/182d6ae6-f7b2-4059-9046-56857d625a04)

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.0.15.0

### Windows Version

10.0.22621.2428

**Comment by yaira2** [comment]
Thanks for the feedback
