### ISSUE TITLE
Batch Renaming upon File Transfer

### ISSUE THREAD

**Issue by samir-a-ali** [files-community/Files#14188]
### What feature or improvement do you think would benefit Files?

In Windows explorer, if you transfer more than one file, all files remain highlighted after transferring for additional manipulation. This includes batch renaming, where a single name (e.g. "batch") will then be prgressively named batch (1); batch (2) etc. in addition windows explorer takes into account the possibility of already existing names of batch (1); batch (2) and will rename the new files batch (3); batch (4) 

### Requirements

batch renaming

### Files Version

3.0.15.0

### Windows Version

10.0.22635.2841

**Comment by yaira2** [comment]
You can also take advantage of PowerToys which has support for bulk rename
