### ISSUE TITLE
Opaque thumbnail on First File Load

### ISSUE THREAD

**Issue by D-Maxwell** [files-community/Files#14183]
### Description

![image](https://github.com/files-community/Files/assets/98100481/b6c53a06-b2ce-4c56-9403-4c8048885ea2)

As shown above, image files that are meant to support transparency render their transparent parts as a fully opaque black background.

Upon hitting the reload button, this disappears ; although it would be appreciated not to be given such a sight.

![image](https://github.com/files-community/Files/assets/98100481/ddb9dadd-0980-427d-8763-2bee4875b0f7)

### Steps To Reproduce

Open never previously opened folder containing transparent images
Observe opaque background rendering
Reload
Thumbnail now renders properly

### Requirements

I would assume the necessary code lies in the instructions associated to the reload button, and that perhaps cross calling some of those could solve the issue before it even gets to be seen at all.

### Files Version

3.0.8.0

### Windows Version

10.0.19045.2788

### Log File

[debug.log](https://github.com/files-community/Files/files/13570220/debug.log)

**Comment by yaira2** [comment]
This has to do with the way Windows caches icons. Windows returns a very basic thumbnail the first time it's requested and then it works its magic in the background to cache the thumbnail. Our goal is to automatically refresh the icon once it's cached and we're tracking the progress in #12071.
