### ISSUE TITLE
File Preview Feature Request

### ISSUE THREAD

**Issue by HondaFit** [files-community/Files#14195]
### What feature or improvement do you think would benefit Files?

Software like QuickLook (by Paddy Xu) or Powertoys (microsoft) have the ability to temporally open and view (popup) files such as images, videos, documents, 3d, etc. When the user unfocused on the popup (clicking on something) it automatically closes. 

this makes viewing any file really easy. there's no need to open an separate software when you can quickly view it at a glance.

### Requirements

Ways to accomplish this
- Make a built in file preview feature 
- Make it work with power toys or Quicklook

### Files Version

3.0.15.0

### Windows Version

10.0.22621.2715

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Files already has a preview pane (Right of tool bar > 2nd button from the right). Quicklook already works when pressing space on the selected file. Power Toys Peek doesn't have a way for other programs to use it.
