### ISSUE TITLE
[Bug] Git integration doesn't work in symbolic links

### ISSUE THREAD

**Issue by A-Loot** [files-community/Files#14197]
### Description

I have a Git repository and a symbolic link that links to it. When I open the repo all Git features are avaiable but when I open it through the symbolic link they aren't.

I know that this is a very unusual setup and only a minor qol issue, so I understand if this Issue won't be fixed any time soon.

original repo:
![original](https://github.com/files-community/Files/assets/105282948/cd8a7bb1-e65a-4c27-9698-0ec6915b710b)

symbolic link of the repo:
![symboliclink](https://github.com/files-community/Files/assets/105282948/3d7e0069-1bad-4f56-8c9a-ebb4cee8be23)

### Steps To Reproduce

1. clone a repository
2. create a symbolic link to the clone
3. open the symbolic link, you'll see that the git integration is missing

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.0.15.0

### Windows Version

10.0.23595.1001

### Log File

[debug.log](https://github.com/files-community/Files/files/13600165/debug.log)

It warns me that the symbolic link of the repository is not owned by me (which is correct, I am only a collaborator), the same warning does not appear for the original

**Comment by awderh** [comment]
I checked it on my system, and Git integration works with symbolic links:
<img width="1134" alt="image" src="https://github.com/files-community/Files/assets/12786951/2ad71678-a077-4910-8a75-84c4eb7fa767">

The warning that you are seeing in the debug log is related to *filesystem* permissions/ownership.

Can you verify the ownership of the symlink matches that of the `.git` folder?
