### ISSUE TITLE
When I installed the update (3.0.12.0) it worked as intended but now the G drive is back.

### ISSUE THREAD

**Issue by xmha97** [files-community/Files#14191]
When I installed the update (3.0.12.0) it worked as intended but now the G drive is back.

![Screenshot 2023-11-26 154215](https://github.com/files-community/Files/assets/105282948/7ecf618a-29b4-4dbc-a345-f360637d7b6d)

_Originally posted by @A-Loot in https://github.com/files-community/Files/issues/14041#issuecomment-1826802996_

**Comment by yaira2** [comment]
The latest version is v3.0.15
