### ISSUE TITLE
Bug: Copy File from TeamViewer doesn't copy File Creation date attribute

### ISSUE THREAD

**Issue by AlquistArj** [files-community/Files#14199]
### What feature or improvement do you think would benefit Files?

When copying a file from a remote TeamViewer session the file creation time is not copied across (whereas it is with copy & paste into Windows File Explorer). I suspect Modified and Accessed are similarly ignored. Having these file attributes maintained is very helpful and ideally Files would behave in the same way as Windows File Explorer.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.0.15.0

### Windows Version

10.0.22631.2792

**Comment by yaira2** [comment]
Thanks for the report.
