### ISSUE TITLE
Aplicativo fechando inesperadamente

### ISSUE THREAD

**Issue by pablo-hp** [files-community/Files#14209]
### Description

Aplicativo fechando inesperadamente

### Steps To Reproduce

Aplicativo fechando inesperadamente

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.0.15

### Windows Version

11

### Log File

[debug.log](https://github.com/files-community/Files/files/13626077/debug.log)

**Comment by yaira2** [comment]
Thank you for the feedback, can you please fill out the issue template?
