### ISSUE TITLE
Progress Indicator Stays Still all Throughout any Operation

### ISSUE THREAD

**Issue by D-Maxwell** [files-community/Files#14203]
### Description

![image](https://github.com/files-community/Files/assets/98100481/547f1663-2d3a-4c55-b381-b95655d477fa)
![image](https://github.com/files-community/Files/assets/98100481/2ff52e33-32eb-4299-97e4-3b89e5d3c1c4)

### Steps To Reproduce

Begin any file operation
Title bar indicator stays still at 0 completion, despite actual progress being made and shown once clicked through a progress bar

### Requirements

The indicator should reflect the progress of the foremost ongoing operation at a glance, as such is its intended purpose.

### Files Version

3.0.8.0

### Windows Version

10.0.19045.2788

### Log File

[debug.log](https://github.com/files-community/Files/files/13617282/debug.log)

**Comment by D-Maxwell** [comment]
> Thanks for the report, Please update to 3.0.15.0 and try reproduce this. https://files.community/download

This has in fact been fixed, thank you for the help.
The reason I hadn't already updated is that it would seem that for some reason, the update button native to the app refuses to properly update the app (either loads forever, or disappears after a few seconds of loading).
Is this intended behaviour ? (Note that I have installed the app manually, and not through the store.)

**Comment by Josh65-2201** [comment]
The update issue is with Windows and doesn't work for everyone all the time.
