### ISSUE TITLE
Bug: App keeps crashing

### ISSUE THREAD

**Issue by Sacchid** [files-community/Files#14208]
### Description

App keeps crashing & gives notifications - 
`Something went wrong. File ran into problem that the developers didn't preapare for yet.`

`Error|System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.Actions.LaunchPreviewPopupAction.SwitchPopupPreviewAsync()`

Log file is attached.

### Steps To Reproduce

Randomly crashing although app restarts most of them time with open tabs & panes but didn't open 2-3 times.

### Requirements

- Fix crash that occurs when uncaught errors happen or at least tell why app crashed.

### Files Version

3.0.15.0

### Windows Version

10.0.22631.2792

### Log File

[debug.log](https://github.com/files-community/Files/files/13625669/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.
