### ISSUE TITLE
Right click menu transparency not correct

### ISSUE THREAD

**Issue by tianpu2014** [files-community/Files#14204]
### Description

The current update's right menu shows improper transparency. Please decrease the transparency level.  

### Steps To Reproduce

Mentioned above

### Requirements

- e.g. Fix crash that occurs when...ASAP

### Files Version

3.0.8.0

### Windows Version

10.0.22621.2792

### Log File

![image](https://github.com/files-community/Files/assets/36344837/4222c7e6-22c0-4b77-a91d-5e3bef14d3c0)

**Comment by yaira2** [comment]
Thanks for the report, this is a rendering issue with WinUI that sometimes occurs and isn't something we can control in Files. The good news is that Microsoft is working on a fix.
