### ISSUE TITLE
ability to stop grouping folders by date

### ISSUE THREAD

**Issue by wassysadmin** [files-community/Files#14207]
### What feature or improvement do you think would benefit Files?

I want to see my folders in strict alpha order, not grouped by recent, last year, etc

I'm sure others would want that too. I suspect you can do this in the edit the code file, but some of us are not savy to editing that file.

### Requirements

- This will allow anyone to get a strict alphabetic list of their folders
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.0.2.0

### Windows Version

22H2

**Comment by Josh65-2201** [comment]
Thanks for the feedback, you can already turn off grouping in the toolbar
![image](https://github.com/files-community/Files/assets/26977075/a4f62891-5d7e-4b11-85b3-3e66f66255b8)
