### ISSUE TITLE
Hard disk Eject option

### ISSUE THREAD

**Issue by Thepixchanger** [files-community/Files#14213]
### What feature or improvement do you think would benefit Files?

I need an external hard disk eject option near the disk name.

### Requirements

Just place eject option near the drive name in drive section.

### Files Version

3.0.8.0

### Windows Version

10.0.22631.2715

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #13250. You can check there or click subscribe in the right sidebar for updates.
