### ISSUE TITLE
Bug: Error descarga y subida

### ISSUE THREAD

**Issue by dracocraft** [files-community/Files#14210]
### Description

Cuando vas a descargar o subir archivos se ve el windows explorer y no files

### Steps To Reproduce

1. Intentar subir o descargar archivos

### Requirements

El error solo funciona al subir o descargar archivos (almenos que yo lo encontrase)

### Files Version

3.0.15.0

### Windows Version

10.0.22621.2792

### Log File

[debug.log](https://github.com/files-community/Files/files/13626524/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #6314. You can check there or click subscribe in the right sidebar for updates.
