### ISSUE TITLE
Folder View Layout List

### ISSUE THREAD

**Issue by Angell1993** [files-community/Files#14214]
### What feature or improvement do you think would benefit Files?

The most important folder view called list is missing..

I love the UI, But without the folder view called list, I can't switch..

### Requirements

From a visual point of view, all that is need is an icon + text then you make a list that will use the height to show a limited number of items, before going to a new column, and continues top to bottom within the view area, with only an horizontal scrollbar.. It would be great if the icon + text size is changeable, to get the perfect view.. 

### Files Version

3.0.15.0

### Windows Version

10.0.22631.2715

### Comments

Should be easy to check the default Window File Explorer for the List view..

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #2509. You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
@Angell1993 thank you for your patience, I'm excited to share that a List View layout will be included in the next release.
