### ISSUE TITLE
Hard disk is not ejecting

### ISSUE THREAD

**Issue by Thepixchanger** [files-community/Files#14212]
### Description

I set Files V3 application as my default file manager, but since then I have not been able to eject the external hard disk. I checked it with File Locksmith, and I found that the problem was caused by Files V3 application. I have attached the screenshots of the issue 
![Screenshot 2023-12-10 135936](https://github.com/files-community/Files/assets/153421403/b855779d-eded-4947-b935-ea1d28b1cc69)
![Screenshot 2023-12-10 140014](https://github.com/files-community/Files/assets/153421403/f141c2b0-181e-497c-8e3c-57ed1a1f330a)

### Steps To Reproduce

N/A I am just a user

### Requirements

N/A I am just a user

### Files Version

3.0.8.0

### Windows Version

10.0.22631.2715

### Log File

[debug.log](https://github.com/files-community/Files/files/13627057/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Do you have the drive open in a tab?

**Comment by Thepixchanger** [comment]
No it was closed I even closed the files app.

**Comment by yaira2** [comment]
What happens if you try ejecting the drive through Files?

**Comment by Thepixchanger** [comment]
There is no option visible to eject the drive in the first place everytime I have to go to taskbar to eject the harddisk

________________________________

**Comment by Jay-o-Way** [comment]
> I even closed the files app.

Could Files be running in the background? There's a setting for that.

**Comment by yaira2** [comment]
That should help as a workaround but ideally it shouldn't affect ejecting a drive.

**Comment by Thepixchanger** [comment]
See that's my concern without closing the files app you can't eject the hard disk. I want files to be open end of the day files app is a ( file manager or file explorer ) so I don't want to completely closed the app I want an option to eject the hard disk directly from files like those in mac. Inhope you guys are understanding the point I am making.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by yaira2** [comment]
Does this happen with other drives as well, or is it only this one?

**Comment by Thepixchanger** [comment]
I have two hard disk and I have tried with both of them it's not showing any eject option in files app nor its ejecting without completing closing the files app

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by 0x5bfa** [comment]
Could you try to close Files completely from Task Manager? I think it’ll help and some internal services are affecting such as drive change watchers.

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
