### ISSUE TITLE
Bug: Copy/Paste out of zip file doesn't work

### ISSUE THREAD

**Issue by Pandarte** [files-community/Files#14216]
### Description

When I try to copy a file inside a .zip file (or any compressed file) and paste it somewhere else, nothing happens, even though the status center tells me that the copy has been made.

### Steps To Reproduce

Open a .zip file
Copies a file contained in this .zip file to the clipboard
Paste it outside of the .zip file
`nothing happens... ┐(￣ヘ￣;)┌`

### Requirements

The file should be extracted and pasted where I tried to paste it.

### Files Version

3.0.15.0

### Windows Version

10.0.23601.1000

### Log File

[debug.log](https://github.com/files-community/Files/files/13628519/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
This issue should be fixed in the next release.
