### ISSUE TITLE
Bug: App crashes when resizing window

### ISSUE THREAD

**Issue by VovaChes** [files-community/Files#14223]
### Description

When I try to stretch the program window, it first freezes and then the program shuts down. The direction of window stretching does not matter. 

Enabled: 
Adaptive layer
The info panel Preview
Set Files as the default file manager

### Steps To Reproduce

1. Open app
2. Going to some folder where files are placed
3. Stretching or compressing the window

### Requirements

Fix crash that occurs when stretching or compressing a window

### Files Version

3.0.15.0

### Windows Version

10.0.22631.2792

### Log File

[debug.log](https://github.com/files-community/Files/files/13632945/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.
