### ISSUE TITLE
Please add an interface for displaying and managing all the fonts in the folder C:\Windows\Fonts

### ISSUE THREAD

**Issue by CavDev** [files-community/Files#14220]
### What feature or improvement do you think would benefit Files?

Explorer have already provides a user-friendly interface for the C:\Windows\Fonts folder. I hope Files can also have a similar interface to manage fonts.

### Requirements

null

### Files Version

3.0.15.0

### Windows Version

10.0.22631.2715

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Windows File Explorer doesn't use a different interface compared to Files. You can set it to grid view with the tool bar options.
![image](https://github.com/files-community/Files/assets/26977075/1d43ac48-86d8-42d4-a7f1-8848d3d8ae4a)
