### ISSUE TITLE
Bug: Error while in the background

### ISSUE THREAD

**Issue by Sacchid** [files-community/Files#14228]
### Description

Error while adding OneDrive - System.Runtime.InteropServices.COMException (0xC00D3E85)

### Requirements

Fix error pop-up / provide more info on how to resolve this OneDrive error

### Files Version

3.0.15.0

### Windows Version

10.0.22631.2792

### Log File

[debug.log](https://github.com/files-community/Files/files/13650710/debug.log)

**Comment by yaira2** [comment]
@Sacchid according to the log file, it looks like OneDrive was added without any issues.

**Comment by Sacchid** [comment]
Sorry I might have read it wrong. I still got 2-3 notifications to report errors, is there some other error?

**Comment by Sacchid** [comment]
Yes, It does crash but opened all tabs immediately. 

[debug.log](https://github.com/files-community/Files/files/13651510/debug.log)

**Comment by yaira2** [comment]
At which point is it crashing, right away on startup, or is it after you already start using the app?

**Comment by Sacchid** [comment]
While using app or even in the background when I have minimised it & using someother app.

**Comment by yaira2** [comment]
Can you confirm if it's the same as #13995?
