### ISSUE TITLE
Network shares in favorites delays start

### ISSUE THREAD

**Issue by stephan1827** [files-community/Files#14221]
### Description

When you add a network share to your favorites, but this share is not accessible, Files will freeze for about a minute on the first start. Attached is video of the issue.

### Steps To Reproduce

1. Add a network share to your favorites
2. Disconnect from the network so the share can no longer be accessed
3. Close all instances of Files including background services
4. Start Files

### Requirements

I would expect Files to be accessible immediately. Network shares that are not available should be greyed out.

### Files Version

3.0.15

### Windows Version

Windows 10

### Log File

[debug.log](https://github.com/files-community/Files/files/13632288/debug.log)

https://github.com/files-community/Files/assets/2972703/931dfd5f-f06d-43cd-966b-0542b2cf0da6

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #13087. You can check there or click subscribe in the right sidebar for updates.
