### ISSUE TITLE
Feature: Add support for changing File/Folder priority when sorting

### ISSUE THREAD

**Issue by azulika** [files-community/Files#14226]
### What feature or improvement do you think would benefit Files?

If I'm not missing something, the latest version does not allow us to choose whether to sort files first or folders first, and files are always listed after folders. I want to sort filers first like this https://github.com/files-community/Files/issues/9574#issuecomment-1715583055 .
The `Sort files and folders together` option does not really cover this feature as it just mixes them up together instead of prioritizing one or the other while keeping them separate.
This is probably the exact same feature request as https://github.com/files-community/Files/issues/5834, which somehow seems to be marked as completed.

### Requirements

- This proposal will allow the user to sort files first by adding a combo box to settings with options to
    1. Sort folders first
    2. Sort files first
    3. Sort files and folders together
- Add sub section to sort flyout on the toolbar with options to
    1. Sort folders first
    2. Sort files first
    3. Sort files and folders together 

### Relevant code
The relevant code for sorting can be found in `SortingHelper.cs` under the `OrderFileList` function

### Files Version

5.0.15.0

### Windows Version

10.0.22621.2715

**Comment by yaira2** [comment]
Are you sorting by type?

**Comment by yaira2** [comment]
If it's still not working, can you please open an issue with the bug report template so we can track this properly?

**Comment by azulika** [comment]
it's still not working.

## Ascending Sort
![image](https://github.com/files-community/Files/assets/104073882/0b663afb-eee6-4e01-8515-cb6e80b3b27d)
## Descending Sort
![image](https://github.com/files-community/Files/assets/104073882/d656aba1-5a1c-49c7-89aa-cec0d4bd8bdd)

As you can see, files always come after folders.
However, I noticed there does exist some folders that work as I desire, like this one

## Ascending Sort
![image](https://github.com/files-community/Files/assets/104073882/cbb48221-248f-4146-8518-baef05bc9ac1)
## Descending Sort
![image](https://github.com/files-community/Files/assets/104073882/89f5bd20-9a79-4281-a0b3-be1522428780)

But it doesn't work in most folders. I don't know what is exactly causing this, but I guess it's safe to say this is some kind of a bug.
At first I thought the size of a folder or the number of files might be doing something, but apparently it's irrelevant.
As suggested, I'll open an issue with the bug report template. I'll do a bit more research into the cause myself.

**Comment by yaira2** [comment]
It looks like you're sorting by date, is there any difference if you sort by type? Also, let's continue on the issue using the bug template.

**Comment by yaira2** [comment]
Apologies for jumping around, but now that we clarified the current behavior is working properly, let's move back to the feature request to see about adding support for this configuration.

**Comment by yaira2** [comment]
@azulika this feature will be included in the next update.
https://github.com/files-community/Files/assets/39923744/ac4ceb75-0a60-4bb2-9e70-16ba5547c529
