### ISSUE TITLE
Keyboard navigation in column view randomly changes focus out of column view

### ISSUE THREAD

**Issue by chaosemer** [files-community/Files#14236]
### Description

When I use keyboard navigation in column view, the focus seems to randomly go to the tab list as the top. I can not figure out what is causing this but it semi-reliably will happen when navigating through a deep folder hierarchy within one to two minutes. This change in focus makes it impossible to reliably use the keyboard to navigate folders.

### Steps To Reproduce

1. Set view to Column view.
2. Use up/down to switch selected file
3. Once you've selected a older, use right to go to its contents
4. Repeat steps 2 and 3 as needed. At some point the focus will switch to the tab list at the top.

### Requirements

I expect keyboard focus to stay in the column view unless I hit TAB or click the mouse.

### Files Version

3.0.8.0

### Windows Version

10.0.22631.2715

### Log File

[debug.log](https://github.com/files-community/Files/files/13666091/debug.log)

**Comment by yaira2** [comment]
Thanks for the report, this issue is being tracked in #13813.
