### ISSUE TITLE
Bug: Sorting by type isn't working properly

### ISSUE THREAD

**Issue by azulika** [files-community/Files#14231]
### Description

Moved from https://github.com/files-community/Files/issues/14226 . Please check the issue link first.

There is an inconsistency with the sorting option. I want folders always listed after files when sorting descendently, like this https://github.com/files-community/Files/issues/9574#issuecomment-1715583055 . However, in the latest version, regardless of the sorting order, files always come after folders in *most folders*.

## Ascending Sort
![image](https://github.com/files-community/Files/assets/104073882/0b663afb-eee6-4e01-8515-cb6e80b3b27d)
## Descending Sort
![image](https://github.com/files-community/Files/assets/104073882/d656aba1-5a1c-49c7-89aa-cec0d4bd8bdd)

However, I noticed there does exist some folders that work as I desire, like this one

## Ascending Sort
![image](https://github.com/files-community/Files/assets/104073882/cbb48221-248f-4146-8518-baef05bc9ac1)
## Descending Sort
![image](https://github.com/files-community/Files/assets/104073882/89f5bd20-9a79-4281-a0b3-be1522428780)

But as I said, it doesn't work like this in most folders. I don't know what exactly is causing this, or if it's even reproducible for others, given that there's been no current issue with this bug.

## What I currently know
- There is no difference in behavior if I sort by type, size, tag, name, or whatsoever.
- Folder's size seems to be irrelevant.
- When I create a new folder on Files and put some files and folders into it, the descending sort seems to always work correctly(files come first). Possibly there's something wrong with indexing function.
- The language setting is irrelevant. I usually use Files in Japanese, but the problem persists in other languages.

### Steps To Reproduce

1. Enable option to list files with folders
2. Sort items by type and change sort direction so that files get displayed first and folders last

You might as well uninstall Files before step 1 in order to perfectly reproduce the process.

### Requirements

Files should always come before folders when sorted descendently like this https://github.com/files-community/Files/issues/9574#issuecomment-1715583055 . Or add an option to change the priority of the order of files and folders if this approach is considered more desirable. 

### Files Version

4.0.15.0

### Windows Version

10.0.22621.2715

### Log File

[debug.log](https://github.com/files-community/Files/files/13655360/debug.log)

**Comment by azulika** [comment]
> sorting by type and enabling the option to sort files & folders

Do you mean sorting by type and enabling "List and sort directories alongside files"? In some folders it works, but it seems more of coincidence as most folders just become kind of unorganized. 
## Successful example
![image](https://github.com/files-community/Files/assets/104073882/8ac2d354-d4d8-442b-99a0-4ebf61f810fe)
![image](https://github.com/files-community/Files/assets/104073882/22b74942-b288-46d4-ac87-394b3adb4182)

## Failed example
![image](https://github.com/files-community/Files/assets/104073882/acd8b9e4-5fd6-4c4e-8d11-b898f63ba2e8)
![image](https://github.com/files-community/Files/assets/104073882/e4bbfa50-4a0e-4a4e-92f5-a5b87e8cb89b)

Also, sorting by date doesn't work even in the folders in which sorting by type and enabling "List and sort directories alongside files" worked

**Comment by yaira2** [comment]
I think it's sorting them alphabetically, in which case it's working as designed.

**Comment by yaira2** [comment]
Apologies for jumping around, but now that we clarified the current behavior is working properly, let's move back to the feature request to see about adding support for this configuration.
