### ISSUE TITLE
Files 3.0.15.0 request

### ISSUE THREAD

**Issue by ElQuia345** [files-community/Files#14235]
### What feature or improvement do you think would benefit Files?

Its more than one :-) .  1- Remember the exact layout of last window. 2- Add a feature to have up to ... n layouts saved. 3- Be able to mix icon sizes or layouts, say at left compact tree, opened to active pane folder, one thumbnail or big icon pane, and other pane with details.... sort of Total Commander. 4- Up to 5 horizontal panes for wide monitores, up to 3 to 4 for vertical monitors.

LOVE THE WORK, AND THE SPEED. I am on latest windows 10 Pro. Explorer es SOOOOO SLOWWWWW

Best, Pablo, from Argentina.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.0.15.0

### Windows Version

10.0.19045.3758

### Comments

![image](https://github.com/files-community/Files/assets/143661503/913a5820-340f-41cb-94cf-cae9f1554453)

**Comment by yaira2** [comment]
Thank you for the feedback

> Remember the exact layout of last window

If you're referring to the window size and position, this is handled by Windows but it should already behave the way you described.

> Add a feature to have up to ... n layouts saved

Can you explain what you mean by this? You can already have different layouts in different folders.
