### ISSUE TITLE
Bug: Keep getting prompted for GitHub account with every push/pull

### ISSUE THREAD

**Issue by JoseSanchez54** [files-community/Files#14234]
### Description

Why do I have to reconnect my account every time I push to GitHub? Whenever I click on Push I get the window to copy the verification code from github

### Steps To Reproduce

1. Click in push
2. Activate your github account
3. Click in push another time
4. Repeat in loop

### Requirements

- Whenever I click on Push I get the window to copy the verification code from github

### Files Version

3.0.15.0

### Windows Version

10.0.19045.3693

### Log File

[debug.log](https://github.com/files-community/Files/files/13659913/debug.log)

**Comment by ferrariofilippo** [comment]
Can you check if you can find "Files:https://github.com" in your Windows Password Manager?

**Comment by JoseSanchez54** [comment]
![image](https://github.com/files-community/Files/assets/55786662/766c3887-8cfb-4fb5-b817-1f4e4bded4c9)
Like this?

**Comment by ferrariofilippo** [comment]
> Like this?

Yes. So that's not the problem...
Can you find `Files App` on GitHub under `Settings > Integrations > Applications > Authorized  OAuth Apps`?

**Comment by ferrariofilippo** [comment]
Are you on Store/Stable/Preview version?

**Comment by ferrariofilippo** [comment]
Can you compile the source code? I think `Files` is throwing an exception at `Files.App.Helpers.CredentialsHelpers GetPassword()` but I can't reproduce it

**Comment by yaira2** [comment]
@ferrariofilippo can we just assume that's the case and handle the exception?

**Comment by ferrariofilippo** [comment]
> @ferrariofilippo can we just assume that's the case and handle the exception?

We're already catching that exception, but we can't really handle it: since Files can't get any password from the manager, we can either ignore it (but then the user wouldn't know the feature is not working), or show the popup to log-in

**Comment by yaira2** [comment]
We'll need more info on the exception to be able to workaround it

**Comment by ferrariofilippo** [comment]
I guess we should consider always logging exceptions in `catch` blocks (unless we know for sure what's the cause for them)

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
