### ISSUE TITLE
Bug: Defaulp app to open pdf files does not synchronize with windows settings

### ISSUE THREAD

**Issue by figelmigel** [files-community/Files#14238]
### Description

I have set SumatraPDF as default program to open pdf files with and it does work properly in windows file explorer. However Files, for some reason, tries to open them with Microsoft Edge (which i have removed btw) and that forces me to manually chose the desired program every time
![изображение](https://github.com/files-community/Files/assets/153452573/80dadd04-bb5b-4f2f-afb3-f15e36470333)
![изображение](https://github.com/files-community/Files/assets/153452573/fb346a11-3fbb-4771-b50d-f721d599153f)

### Steps To Reproduce

Unfortunately, I'm not too sure, since I don't remember ever opening pdfs with edge and everything was working as expected. I have recently run win-debloat-tools script which might have caused some problems

### Requirements

- synchronize default apps with windows settings
- add an option to switch default apps right in the Files menu

### Files Version

3.0.15.0

### Windows Version

10.0.22621.2715

### Log File

[debug.log](https://github.com/files-community/Files/files/13672910/debug.log)

**Comment by figelmigel** [comment]
When I hover the mouse over "open with" option in the context menu I get a list of apps I can use to open the file. There is also "choose another app" button which opens a pop up with an option to always use the selected app, but that does not help.

**Comment by yaira2** [comment]
I have the same version of Windows as you do and I can't reproduce this

**Comment by yaira2** [comment]
We're going to continue tracking this in #13425.

**Comment by figelmigel** [comment]
Reinstalling Files solved the issue👍

**Comment by yaira2** [comment]
That's interesting to note, thanks for letting us know.

**Comment by erosen03** [comment]
@figelmigel's solution of reinstalling Files also solved the issue for me.
