### ISSUE TITLE
Bug: App crashes when Github refuses to connect

### ISSUE THREAD

**Issue by KaiHuaDou** [files-community/Files#14239]
### Description

I'm using a proxy, I set hosts file like this:
``` host
127.0.0.1 github.com
```
Then my proxy will listen the 80 port.

When I try to login to Github without turning on the proxy, Files crashed.

### Steps To Reproduce

1. Set `127.0.0.1 github.com` in the hosts file.
2. Run Files
3. Login to Github in Files.
4. Files crash

### Requirements

The Files app should display a message like `Connect Refused` instead of crashing.

### Files Version

3.0.15.0

### Windows Version

10.0.19045.3516

### Log File

[debug.log](https://github.com/files-community/Files/files/13679319/debug.log)

**Comment by yaira2** [comment]
Thanks for the report
