### ISSUE TITLE
Files search functionality not working - Windows 11

### ISSUE THREAD

**Issue by ccrooks562** [files-community/Files#14230]
### Description

Hi there, whenever I try to search for anything in the files program, it does not work. Neither for external HDDs or internal HDDs. 

Is this bug curretnly being worked on?

Thank you,
C

### Steps To Reproduce

Open files
Try to search for anything
Does not work

### Requirements

Please fix the bug so that I can search for contents within my PC

### Files Version

3.0.15.0

### Windows Version

10.0.22631.2792

### Log File

[debug.log](https://github.com/files-community/Files/files/13654238/debug.log)

**Comment by yaira2** [comment]
Does it work if you enable the option to search for unindexed locations?

**Comment by ccrooks562** [comment]
I just found the option. It does not do anything even if I click that.

I am pressing "Enter" to search. Should I be doing that? And will the results show in the main window like windows file explorer?
It also will not search within a speicfic folder, it only searches when I press enter in the root folder.

Thoughts?

**Comment by Josh65-2201** [comment]
Did you give it time to load the results. It shows a loading icon in the tab when searching.
Does the main view say `no results found`?

**Comment by ccrooks562** [comment]
Correct. So basically I press enter, and then the text I entered in the search field disappears, and it says "no results found". I then tested this in the default windows explorer and it immediately finds the file.

Here are some problems I'm seeing:
Files only searches main folders and not folders within the root folder that I have specifically clicked for it to search.
Whenever I click enter or click the magnifying glass to search, the text disappears and nothing happens
I have now only gotten it to search successfully once, but it looks like a bugged window where it shows results (from the whole root folder) and then has a weird "no results found" text on top of the results. Sadly I thought I captured a screenshot, but I did not.

**Comment by ccrooks562** [comment]
Is it built to search whichever folder you are viewing in specifically? Or does it always search the root? 
And is it normal for it to take a long time for it to search?

Thank you

**Comment by yaira2** [comment]
> Is it built to search whichever folder you are viewing in specifically

There is a switch to only search the current folder, but by default it's designed to search the current directory and sub folders.

> And is it normal for it to take a long time for it to search?

It shouldn't take more than a few seconds if the items are indexed, otherwise it can take a couple minutes or longer to search unindexed items.

**Comment by yaira2** [comment]
If you're interested, you can try enabling the enhanced indexing option in Windows Settings.
![image](https://github.com/files-community/Files/assets/39923744/77e20379-5590-4bce-ba6f-95c69d00a41e)

**Comment by ccrooks562** [comment]
Thank you so much for this information!

Where is the switch to search only the current folder? I cannot find it. Thank you!

**Comment by ccrooks562** [comment]
> > Is it built to search whichever folder you are viewing in specifically
> 
> There is a switch to only search the current folder, but by default it's designed to search the current directory and sub folders.
> 
> > And is it normal for it to take a long time for it to search?
> 
> It shouldn't take more than a few seconds if the items are indexed, otherwise it can take a couple minutes or longer to search unindexed items.

Thank you so much for this information!

Where is the switch to search only the current folder? I cannot find it. Thank you!

**Comment by yaira2** [comment]
You can add `in:desktop` (replace "desktop with the current directory) to the search query.

**Comment by ccrooks562** [comment]
Sorry, I tried to figure out how to do this, and I cannot figure it out. 

Could you be a bit more descriptive? Sorry! I'm not as technical as you :). Do you mean that I replace "desktop" with the current directory? Could you send me a screenshot so I understand where to do this and how? I would super appreciate it!!

Thank you!

**Comment by ccrooks562** [comment]
Sorry, I just figured out what is happening. I thought Files performed exactly like Windows explorer, but it does not.

If I understand this correctly: When you click on a folder, you are still on that parent folder, in order to search the subfolder, you actually have to click on an item or folder _inside_ that subfolder in order to be "looking in" that folder to search. Correct? Because now search is functioning like it is supposed to.

**Comment by yaira2** [comment]
> Could you be a bit more descriptive? Sorry! I'm not as technical as you :). Do you mean that I replace "desktop" with the current directory? Could you send me a screenshot so I understand where to do this and how? I would super appreciate it!!

If you're in the desktop folder and only want to return results for the current folder, you can type `in:desktop` to hide results from sub folders
![image](https://github.com/files-community/Files/assets/39923744/6d43408c-ac08-4032-806a-0708a85d1729)
