### ISSUE TITLE
Feature: Show Disk Free Space on the status bar

### ISSUE THREAD

**Issue by jswinde** [files-community/Files#14233]
### What feature or improvement do you think would benefit Files?

Is there currently a way to display the free disk space in the status bar?  This used to be possible in File Explorer for Windows 7.  Unfortunately, Microsoft has removed this helpful feature.

### Requirements

I do not know.

### Files Version

3.0.15.0

### Windows Version

10.0.22631.2715

**Comment by yaira2** [comment]
This isn't currently supported, but you can get the same info by hovering over the drive on the sidebar.
