### ISSUE TITLE
Bug: Column headers scroll with the content until you resize one of them

### ISSUE THREAD

**Issue by dreamsynth** [files-community/Files#14237]
### Description

When viewing folders in column mode, the column headers do not remain fixed at the top and scroll with the content. This bug disappears if you change the width of one of the columns.

https://github.com/files-community/Files/assets/84819091/733073a2-bc1c-4839-b9e2-bce759921950

### Steps To Reproduce

1. Open any folder you haven't viewed before in column mode.
2. Scroll down.

### Requirements

- Fix the column headers so they don't scroll with the content

### Files Version

3.0.15.0

### Windows Version

Windows 11 23H2 22631.2861

### Log File

[debug.log](https://github.com/files-community/Files/files/13667825/debug.log)

**Comment by yaira2** [comment]
Thanks for the report, I added this to the todo list.
