### ISSUE TITLE
Adding Comments or Notes to a Folder

### ISSUE THREAD

**Issue by SgtSweetieBelle** [files-community/Files#14248]
### What feature or improvement do you think would benefit Files?

A feature that lets you add comments to a Folder, which would then appear in a toggleable column. 

![2023-12-16 13-07-38 — explorer 159A243CBF14E64C2506742167F1F6D7](https://github.com/files-community/Files/assets/2397955/fc9b4436-860a-4696-bea7-f1f961b27956)

This would be different from Tags, since they're not intended to be indexed and searchable. They're just there to add notes to a Folder so that it's more obvious what the Folder is for without having to change the Folder name (and thus break anything that might be dependent on the filepath).

The ability to add a Comment to a Folder can work like this:
* Right-clicking on the folder (or in a blank spot inside the folder)
* Clicking "Add Comment to Folder"
* A "Type your comment" popup appears with a blank field, and the user types in their comment and hits OK
* Files creates a `desktop.ini` file inside the folder (or modifies the existing one), gives it the Hidden and System attributes, then adds the following string:

`[.ShellClassInfo]
InfoTip=Your comment appears here`

Viewing comments would be as simple as
* Right-clicking the sorting headers
* Selecting "Comment"
A Comment column would appear on the right.

### Requirements

* A Comment column that can be toggled on and sorted
* An option in the right-click menu to add a Comment to a Folder

### Files Version

2.5.35.0

### Windows Version

22h2

**Comment by yaira2** [comment]
Thanks for the feedback. You can add comments from the properties window and we're tracking support for displaying more columns in #8366.

**Comment by SgtSweetieBelle** [comment]
Sorry, I'm not seeing any option to add Comments to a **folder** in the Properties window.

I can add a Comment to **files**, but not **folders**.

![2023-12-16 18-48-40 — Files Properties](https://github.com/files-community/Files/assets/2397955/941e8d6d-d622-449c-a186-f982df0f4666)

**Comment by SgtSweetieBelle** [comment]
@yaira2 based on my last post, would it be possible to reopen the request? or should i just make a new one

**Comment by yaira2** [comment]
If it's not showing for folders, there is a good chance this isn't supported by the file system.

**Comment by SgtSweetieBelle** [comment]
@yaira2 in my original post i outlined a way to make it work: by creating (or modifying) the `desktop.ini` file inside of a folder.

**Comment by yaira2** [comment]
That would only work for folders

**Comment by SgtSweetieBelle** [comment]
@yaira2 but that's fine, because there's already a way to do it for files. so it just needs to be enabled for folders too.

**Comment by yaira2** [comment]
Have you tried using the tags feature? It's not exactly intended to be used this way, but I think it'll do what you're looking for.
