### ISSUE TITLE
Feature: Group by Day

### ISSUE THREAD

**Issue by koppor** [files-community/Files#14249]
### What feature or improvement do you think would benefit Files?

Currently, Files allows to group by month:

![image](https://github.com/files-community/Files/assets/1366654/e1cac9e0-2ee3-47b6-9da6-6ca23d7ec7ea)

When sorting dozens of images of different locations, usually the trips / occasions differ by day (and not by month)

Thus, I would like to have "group by day". This would really speed-up sorting.

### Requirements

- Add "Day" to "Group By > Date modified"
- Add "Day" to "Group By > Date created"

### Files Version

3.0.15.0

### Windows Version

10.0.19045.3803

### Comments

Alternatively, the grouping could offer to group for "ISO date". May files are named YYYY-MM-DD HH.mm.ss; thus sorting by them is my "real" wish, but I think, adding grouping by Day is easier to implement.

Refs https://github.com/files-community/Files/issues/4432 (because of image handling)

Related SX question: https://superuser.com/questions/1670777/how-to-group-files-by-date-in-file-explorer

**Comment by Josh65-2201** [comment]
Thanks for the feedback, I've added this to the project board.

**Comment by yaira2** [comment]
This option will be included in the next update.
