### ISSUE TITLE
Files is crashing...

### ISSUE THREAD

**Issue by JustAFridg** [files-community/Files#14245]
### Description

The moment you try to pin a file to the start menu, the app crashes. I try it multiple times but it kept crashing...

### Steps To Reproduce

1. You find a file that you want to pin.
2. You right-click it and then click on more options.
3. After that click on 'Pin to start menu'
4. Then it crashes.

### Requirements

I'm not entirely sure what to put in here, but I'll try my best:
Fix crash that occurs when you try to pin some file to the start menu.

### Files Version

3.0.8.0

### Windows Version

10.0.22631.2861

### Log File

[debug.log](https://github.com/files-community/Files/files/13692023/debug.log)

Thanks for developing this, I love the project!

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #13947. You can check there or click subscribe in the right sidebar for updates.
