### ISSUE TITLE
file app too slow

### ISSUE THREAD

**Issue by micharbel** [files-community/Files#14241]
### Description

file app too slow

### Steps To Reproduce

too slow 

### Requirements

always crashed and slow very very slow 

### Files Version

3.0.15.0

### Windows Version

10.0.22631.2861

### Log File

[debug.log](https://github.com/files-community/Files/files/13682450/debug.log)

**Comment by micharbel** [comment]
please find a solution

**Comment by Josh65-2201** [comment]
Thanks for the report, please say what you are doing before the crash happens and add steps to reproduce this.

**Comment by yaira2** [comment]
Thank you for your feedback, we're working on improving performance and will continue releasing updates with this goal in mind.

**Comment by ach-raf** [comment]
Same here, I have 24GB of ram and the app is running super slow, who is this even made for?

**Comment by yaira2** [comment]
@ach-raf we're working to improve performance in all areas but it'll be helpful to know what you mean by super slow. Are you taking about the launch speed?

**Comment by ach-raf** [comment]
No, I'm talking about the full experience, when I open a folder I have to wait for more than 30 seconds to have control, each action takes more than 30s to 60s to complete, like right click on a file, that a 50second to have the menu shown, even switching between open folders, it takes a painful amount of time, I thought the app needs to build a database or index of some sort, it will be faster but nope, didn't happen each time even after restarting its so slow for every action, for me in this current state, its unusable.

**Comment by yaira2** [comment]
That's definitely not the intended experience, can you share a screen recording of the issue when opening folders and the context menu?

**Comment by mtoranzo** [comment]
same issue

![devenv_3ak0QIllXY](https://github.com/files-community/Files/assets/926024/d88a8f93-687f-4589-9e3e-14bc935c6de2)
![Files_JFbmw5S6v7](https://github.com/files-community/Files/assets/926024/7e2e692e-b655-4aff-b978-ced4b4dafb7b)
![Files_XLClvtwTJx](https://github.com/files-community/Files/assets/926024/15710186-a94c-4ea7-adc5-fc95c46e94bd)

**Comment by jesobreira** [comment]
I too am seeing an annoying startup time. I mean, it is fast, but not as fast as the native windows explorer, for example. Every time I open the Files app, it takes about 3 seconds to launch (stays in the loading screen). Folders with many files can take several seconds to list all the files (and then it stays fast for some time - probably a cache or so). These issues are not present on the native explorer (ok ok I know replacing years of work of tons of developers from a huge company like Microsoft is not easy and this comparison is unfair, but it's with feedbacks that we reach there).

The app is amazing, but as a power user, this 3 seconds startup delay every time I open the app is not allowing me to set it as my default file explorer.

**Comment by yaira2** [comment]
@mtoranzo do you have the option to keep Files running in the background enabled? That should help for startup speed...

**Comment by mtoranzo** [comment]
@yaira2 Yes, sometimes it works faster but 90% of the time it fails with that delay that you see

**Comment by yaira2** [comment]
I believe that's already fixed in our dev branch.

**Comment by fazioliamboina** [comment]
too slow for me too. first boot up was also a bad experience. it took 20 seconds for the UI to unfold and fill up with data.

**Comment by yaira2** [comment]
Thank you for your feedback, we're working on improving performance and will continue releasing updates with this goal in mind.
We're going to continue tracking this feedback in #4180

**Comment by meloff** [comment]
I tried the app, and yeah, it feels quite slow. Perhaps you could integrate the file index from Everything? https://www.voidtools.com/ The program would scan the file system once at startup (in the background) and then open folders instantaneously. In theory, this would make it blazing fast. However, you would need to implement a way to track changes for new or deleted files.

**Comment by Phayderz** [comment]
I too am having issues with it being very very slow and laggy and crashing ontop of it. Compared to Everything, File Pilot, and even default windows explorer. its just unusable atm for me, im using version 4.1.3 of Files.

**Comment by Josh65-2201** [comment]
We're tracking this in the below linked issue. You can check there or click subscribe in the right sidebar for updates.

For crashing please make a bug report, we can't fix what we don't know.

**Comment by yair100** [comment]
@micharbel we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
