### ISSUE TITLE
Feature: Minimalize the app running in the background to the system tray

### ISSUE THREAD

**Issue by 0x5bfa** [files-community/Files#14240]
### What feature or improvement do you think would benefit Files?

Currently, we don't have our own way to kill the app process running in the background except doing so from Task Manager. This enables us to kill the process quickly.

For more about the implementation, visit #13524

### Requirements

- Add SysTray manager.
- Manage the app lifecycle.

### Files Version

3.0.0

### Windows Version

10.0.22000

**Comment by yaira2** [comment]
You can also kill the process by turning off the option in settings
