### ISSUE TITLE
Allow reordering columns

### ISSUE THREAD

**Issue by assayire** [files-community/Files#14247]
### What feature or improvement do you think would benefit Files?

While Files currently supports show/hiding columns, there does not seem to be a way to reorder columns.

### Requirements

Provide option in settings to reorder columns. And also support mouse drap and drop to reorder columns directly in the Files UI.

### Files Version

3.0.3.0

### Windows Version

11

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #8385. You can check there or click subscribe in the right sidebar for updates.
