### ISSUE TITLE
Bug: Pasted image files have wrong file names

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#14242]
### Description

When an image on the clipboard is pasted, an image file is created. Its file name seems to be the current date and time, but has wrong date. For example, when I create an image file at 2023/12/15 16:37:46 (YYYY/MM/DD HH:MM:SS), its file name is `37-15-23-163746.png`.

### Steps To Reproduce

1. Copy an image to the clipboard.
2. Paste it to create an image file.
3. Observe its file name has wrong date.

### Requirements

Fix wrong date.

### Files Version

3.0.15.0

### Windows Version

10.0.19045.3803

### Log File

n/a

**Comment by yaira2** [comment]
Thanks for the report
