### ISSUE TITLE
High memory usage (when multiple tabs open)

### ISSUE THREAD

**Issue by jman61** [files-community/Files#14243]
### Description

Hello - kind 'bugfix' request - memory usage seems high for a file-management app. I have about 12 tabs open and notice the app is sluggish. Checking task manager I notice it's the highest-using app for memory, at over 1.3 gb used. If you know of suggestions to reduce memory usage from my side I'm open to it. I do have the app set to 'not run in background when windows is closed'. 
Thanks for your attention, and I appreciate your work!
![20231215092341](https://github.com/files-community/Files/assets/82738938/dc5216d9-252c-4eeb-bf31-51c3411703c7)

### Steps To Reproduce

1. running Files
2. Using multiple tabs (12 in this case)

### Requirements

Reduce excessive memory usage. 

### Files Version

3.0.15.0

### Windows Version

10.0.19045.3693

### Log File

[debug.log](https://github.com/files-community/Files/files/13686351/debug.log)
Log file uploaded for your review. Thanks again.

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #4180. You can check there or click subscribe in the right sidebar for updates.

The current performance issues are mostly on Microsoft part with WinAppSDK so it may take a while to fix.
Right now you can turn off `Files settings > Advanced > Leave app running in the background when the window is closed` and close Files every so often. Startup time will be slower however.

**Comment by jman61** [comment]
Thanks for the quick feedback, I appreciate your work. :)
