### ISSUE TITLE
Files crashed and a notification pop up says that Files occired an error

### ISSUE THREAD

**Issue by leafpmpmp** [files-community/Files#14255]
### Description

I actually have no clue. It just crashed with no sign of not responding or lagging.
And the notification asked if I'm gonna report it, so here I am.

### Steps To Reproduce

I was renaming a bunch of m4a files before the Files crashed, so...
1. click on a file
2. click it again to edit the name
3. rename done and hit enter
For like 25 times.
<img width="772" alt="image" src="https://github.com/files-community/Files/assets/49824741/3870b27f-1700-4fb4-b80c-c0dfe97e9297">

I was adding the numbers in front to have them sorted in order.
The crashed happened at around 15:58~16:00 in time from the log file.

### Requirements

- No requirement, it depends if devs are curious to look into it or not. (Since this issue is so vague anyway)

### Files Version

3.0.8

### Windows Version

10.0.22631.2861

### Log File

[debug.log](https://github.com/files-community/Files/files/13701087/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report this was fixed in 3.0.15. Please update https://files.community/download

If you are on preview you will need to the below one time
1. Export your settings by going to Files settings > Advanced > Export. 
2. Then uninstall and reinstall Files https://files.community/download
3. Import your settings from Files settings > Advanced > Import > Select previously saved zip.

**Comment by leafpmpmp** [comment]
> Thanks for the report this was properly fixed in 3.0.15. Please update https://files.community/download
> 
> If you are on preview you will need to the below one time
> 
> 1. Export your settings by going to Files settings > Advanced > Export.
> 2. Then uninstall and reinstall Files https://files.community/download
> 3. Import your settings from Files settings > Advanced > Import > Select previously saved zip.

Thanks for the heads up, I've already updated to 3.0.15 after the crash occured. I'll see if I'm gonna bump into it again.
BTW is the "UpdatePackage.msix" in the log folder the right way to update?
My MS Store can't complete installing Files for some reason so I used a classic installer.

**Comment by leafpmpmp** [comment]
> Thats what Files downloads to then install automatically on close or when pressing the download icon next to settings.

That's weird cuz I've seen neither of those happened over the past few months, I always run Files.Stable.exe to trigger it.
Anyway good to know that they exist.

**Comment by yaira2** [comment]
I don't see anything specific in the log file, but we recently fixed a crash that could occur when renaming files (it'll be included in v3.1). Please let us know if this issue happens again in v3.1.
