### ISSUE TITLE
Files "running as Administrator" issue

### ISSUE THREAD

**Issue by samfourie** [files-community/Files#14257]
### Description

Where do you switch off this option? With this option enabled your "Files" program is nothing more than window dressing!
Clicking right on the Icon show that the program is set not to run as Administrator already. No option to switch this off in windows 10 control panel (settings) either. Plase advise

(Ps.. installed from Microsoft Windows Sofwtare Store)

![Capture2](https://github.com/files-community/Files/assets/6639868/3318a768-0fba-4045-b2e5-1e61528771bb)
![Capture](https://github.com/files-community/Files/assets/6639868/ccf86efb-0fa0-449d-9ce7-0d97d1ff2153)

### Steps To Reproduce

Simple opening it with shortcut from dekstop or from windows menus

### Requirements

N/A

### Files Version

3.0.15.0

### Windows Version

22H2 - 19045.3803

### Log File

[debug.log](https://github.com/files-community/Files/files/13702544/debug.log)

**Comment by Josh65-2201** [comment]
You need to have UAC (User Account Control) enable otherwise Windows run every as admin by default.

**Comment by yaira2** [comment]
The underlying issue is from Windows (see more here https://github.com/microsoft/terminal/issues/7754) but there are ways to solve it, we're currently tracking this in #13394.

**Comment by ChristianMalazarte** [comment]
Wow, so can I request a refund? This sucks.

**Comment by yaira2** [comment]
@ChristianMalazarte you can get a refund through the Microsoft Store.
