### ISSUE TITLE
Bug: After creation of a new folder, it should be selected

### ISSUE THREAD

**Issue by koppor** [files-community/Files#14251]
### Description

When creating a new folder with <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>N</kbd>, it should be selected

### Steps To Reproduce

1. Press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>N</kbd>
2. Enter "Test"
3. Press <kbd>Enter</kbd>

- Expected result: Folder "Test" should be selected
- Actual result: nothing selected, explorer view stays same

### Requirements

- Select folder and keep it selected.

### Files Version

3.0.15.0

### Windows Version

10.0.19045.3803

### Log File

[debug.log](https://github.com/files-community/Files/files/13694961/debug.log)

**Comment by koppor** [comment]
I think, it happens if some activity is happening in a previously selected folder. E.g., counting items (which might be slow on a network drive which is currently indexed).

**Comment by Josh65-2201** [comment]
Thanks for the report, I can't reproduce this. 
- What drive are you on? (Network, local, cloud etc.)
- Is the folders contents still loading?

**Comment by yaira2** [comment]
On some network locations I think we refresh the whole folder when an item is added, otherwise the new folder would be selected.
