### ISSUE TITLE
Feature: Ctrl+T should duplicate the current view

### ISSUE THREAD

**Issue by koppor** [files-community/Files#14250]
### What feature or improvement do you think would benefit Files?

Currently, pressing <kbd>Ctrl</kbd>+<kbd>T</kbd> opens "Home".  Same for <kbd>Ctrl</kbd>+<kbd>N</kbd>.

I would like to have <kbd>Ctrl</kbd>+<kbd>T</kbd> duplicating the current view. Then, I can quickly navigate to a sister folder while keeping the current folder opened.

Alternatives:

- Always use "column view" and "Open in a new tab" -- too limiting, because other views are also great
- Copy the path, (navigate away from the path input, because ctrl+T does not work there), press <kbd>Ctrl</kbd>+<kbd>T</kbd>, paste the path -- way more interaction needed
- Select a sub folder, choose "Open in a new tab", navigate two levels up -- more interactions, sometimes no sub folder existing.

### Requirements

- <kbd>Ctrl</kbd>+<kbd>T</kbd> opens a new tab, and navigates to the folder where <kbd>Ctrl</kbd>+<kbd>T</kbd> was pressed.

### Files Version

3.0.15.0

### Windows Version

10.0.19045.3803

**Comment by koppor** [comment]
Oh, there is <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>K</kbd>.

Seems, I need to reconfigure keyboard shortcuts.

**Comment by yaira2** [comment]
We're planning to add support for remapping keys but in the meantime these shortcuts should work
