### ISSUE TITLE
Set Default Folders

### ISSUE THREAD

**Issue by MtnWindows** [files-community/Files#14263]
### What feature or improvement do you think would benefit Files?

I would like to be able to open Files with 2 panes defaulting to certain folders. One folder would be on a drive letter, but the other folder would be on an Android tablet, so it would look like "This PC\GalaxyTabA7\SD card\Pictures\Instagram".

### Requirements

Ability to set default folders including on externally connected Android devices.

### Files Version

3.0.15.0

### Windows Version

10.0.22621.2861

### Comments

Sometimes when I open those 2 folders and close Files and reopen it, those 2 folders do automatically open. But sometimes they don't, and it says something like "Windows recently opened files is disabled."

**Comment by yaira2** [comment]
Thanks for your feedback, you can do this by changing the startup setting to "Specific pages".
![image](https://github.com/files-community/Files/assets/39923744/3d0240d4-0b2f-46ca-83cc-f7db00eaf2f1)
