### ISSUE TITLE
force exit when I login by github 

### ISSUE THREAD

**Issue by tiam-bloom** [files-community/Files#14267]
### Description

force exit when I login by github 

### Steps To Reproduce

force exit when I login by github 

### Requirements

- e.g. Fix crash that occurs when...
force exit when I login by github 

### Files Version

1

### Windows Version

1

### Log File

1

**Comment by Josh65-2201** [comment]
This also may be fixed in the preview version https://files.community/download. Please try that before making another report

**Comment by yaira2** [comment]
I think this is fixed in the preview version v3.0.16.
