### ISSUE TITLE
Bug: Files crashes on the launch screen

### ISSUE THREAD

**Issue by matteom92** [files-community/Files#14266]
### Description

When I open files after 2-3 seconds it crash every time. I saw it not crash if I open it with administrator. It's normal? How can I open files to default with administrator? It's not comfortable every time right click, run like to administraor. Thanks

### Steps To Reproduce

open files (no admin)

### Requirements

crash when open file with no administrator

### Files Version

3.0.15.0

### Windows Version

10.0.22631.2861

### Log File

[debug.log](https://github.com/files-community/Files/files/13725708/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
Is this still an issue if you uninstall and reinstall the app?

**Comment by matteom92** [comment]
I have try to unistall and reistall more Times, but The problem it’s The same.

Arch. Matteo Morana
www.mtmrviz.com
Sent with Spark
Il 20 dic 2023, 15:47 +0100, Yair ***@***.***>, ha scritto:

**Comment by yaira2** [comment]
At what point is it crashing?

**Comment by matteom92** [comment]
After 1/2 seconds I open app

Arch. Matteo Morana
www.mtmrviz.com
Sent with Spark
Il 20 dic 2023, 21:54 +0100, Yair ***@***.***>, ha scritto:

**Comment by yaira2** [comment]
Can you send a screen recording? You should be able to upload directly to GitHub.

**Comment by matteom92** [comment]
Hi, I attach video of crash. Thanks

**Comment by yaira2** [comment]
It's not even getting past the splash screen, thanks!

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by yaira2** [comment]
@matteom92
