### ISSUE TITLE
Something went wrong notification

### ISSUE THREAD

**Issue by Pit1288** [files-community/Files#14265]
### Description

![image](https://github.com/files-community/Files/assets/154396564/1bca14cd-70c7-4fbd-8999-57f7e5e5464e)

### Steps To Reproduce

Use the computer

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.0.15.0

### Windows Version

10.0.19045.3803

### Log File

[debug.log](https://github.com/files-community/Files/files/13722569/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Please add the steps to reproduce.

**Comment by Pit1288** [comment]
I put "use the computer" cause I was not doing something special, just navigating thru a folder, before and after the notification appeared. Yes, Files crashed and restarted. I'll be uninstalling so take a look at the log included.

**Comment by yaira2** [comment]
I'm not seeing anything in the log regarding a crash but it's likely that it wasn't handled. Has this happened again or was it just once?

**Comment by Pit1288** [comment]
It happened once but I'm of no help as I had to uninstall the program cause
the drag files option was a nightmare.

**Comment by yaira2** [comment]
Please let us know if it happens again. Also, it might be best to open a new issue for this can can you share the issues you had with drag & drop?

**Comment by Pit1288** [comment]
How would I tell you if it happens again if I'm telling you I uninstalled
the program?

Also, I did open 1 for the drag and drop issue with details about it, check
all my tickets, maybe somebody closed it.

And please do not contact me for this app again. I tried it, didn't work
for me and reported issues but I'm not planning to get it again.

Thanks!
