### ISSUE TITLE
Directory Tree function on Left Panel

### ISSUE THREAD

**Issue by bdmacl1** [files-community/Files#14260]
### What feature or improvement do you think would benefit Files?

Ability to expand a drive to show the Tree view. It's second nature to do this in Windows, which helps you remember where you are in the hierarchy. I would love that addition to Files

### Requirements

- Shorter Learning Curve since this is a standard approach for navigating to Folder/Files
- Assist in remembering where you are in your Folder journey, which drive, etc.

### Files Version

138021

### Windows Version

1000.22681.1000.0

**Comment by yaira2** [comment]
Thanks for the feedback, this is on our todo list and is being tracked in #1928. In the meantime, we recommend trying the column layout to see if that helps.

**Comment by yair100** [comment]
@bdmacl1 Tree View is currently available in preview https://files.community/download. It will be included in the next stable release.
