### ISSUE TITLE
Bug: Wrong file size units in Catalan (N, KN, DT) 

### ISSUE THREAD

**Issue by marc-vallribera** [files-community/Files#14264]
### Description

Having the app in Catalan language, when showing files, the file size units are shown as N, KN, DT instead of B, KB, MB
![files catalan translation problems](https://github.com/files-community/Files/assets/7223004/1bd8d6b1-41b4-4ba6-a720-89d262f98c38)

### Steps To Reproduce

Open any folder with files of various sizes (B, KB, MB...) 

### Requirements

Units should be shown as in English: B for bytes, KB for kilobytes, MB for megabytes, etc.
I've checked the crowdin translation for Catalan and it seems to be correct there:
<img width="591" alt="image" src="https://github.com/files-community/Files/assets/7223004/9cec7e98-1c8a-4489-a3a6-a5b507de9973">

### Files Version

3.0.15.0

### Windows Version

10.0.22631.2861

### Log File

[debug.log](https://github.com/files-community/Files/files/13720487/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by marc-vallribera** [comment]
Just to add more detail, the bug seems to happen on all places where KB, MB, ... should be shown. For instance, in the progress indicator:
![image](https://github.com/files-community/Files/assets/7223004/949fdb20-9e6e-4b0d-9a6f-d7fafcce00ef)

**Comment by yaira2** [comment]
Upon checking, the file units are displayed as translated on Crowdin. If you believe it should be different, you should be able to suggest changes on Crowdin.
![image](https://github.com/files-community/Files/assets/39923744/b7e85d81-a3e1-4ec5-a3ef-d419aa11387f)
![image](https://github.com/files-community/Files/assets/39923744/91f51b92-abe8-4427-9c64-93dd9a124111)
