### ISSUE TITLE
Add option to add "Extract here (Smart)" to the context menu

### ISSUE THREAD

**Issue by parfait8566** [files-community/Files#14261]
### What feature or improvement do you think would benefit Files?

Currently, you have to get to "Extract" submenu to smart extract, which is annoying. Add an optional setting to add "Extract here (Smart)" directly to the context menu or even replace the normal "Extract" thing

### Requirements

This proposal will make it faster to smart extract after enabling the option

### Files Version

3.0.16.0

### Windows Version

10.0.22631.2861

**Comment by yaira2** [comment]
We don't have plans to do this, but you can use Ctrl + shift + e to extract without opening the context menu.
