### ISSUE TITLE
Installation asking for Proxy settings

### ISSUE THREAD

**Issue by El-Ktrin** [files-community/Files#14269]
### Description

I tried to install FILES (clasic installer: files_stable.exe). After uncompressing the packages it can not be installed due to the following message:
"Proxy authentication required (407)".

I couldn't find a setting or documentation on how I can add my proxy credentials.

### Steps To Reproduce

1- Download files from [WebPage](https://cdn.files.community/files/download/Files.Stable.exe).
2- Execute Files.Stable.exe
        After extracting files the error is displayed.
![image](https://github.com/files-community/Files/assets/154462586/a9e6db60-3b15-43a3-8949-0723f50df517)

### Requirements

- Offer a way to set up proxy info to allow product installation

### Files Version

stable version at 2023-12-20

### Windows Version

Windows 11

### Log File

No log available

**Comment by yaira2** [comment]
Does it work to install the preview version?

**Comment by El-Ktrin** [comment]
> Does it work to install the preview version? It sounds like the installer is failing to access the installation files from the server.

I dind't try the previous version. 

I need to mention our company implemented a proxy with user authentication and I need to use it while installing, that's why the installer can't access the server's files.

**Comment by Josh65-2201** [comment]
You can try use the below offline files
This one is Files
https://cdn.files.community/files/stable/Files.Package_3.0.15.0_Stable_Test/Files.Package_3.0.15.0_x64_ARM64_Stable.msixbundle
This one is WinAppSDK which you might also need to install.
https://cdn.files.community/files/stable/Files.Package_3.0.15.0_Stable_Test/Dependencies/x64/Microsoft.WindowsAppRuntime.1.4.msix

**Comment by yaira2** [comment]
> I dind't try the previous version.

I meant the **preview** version listed on the download page, this uses a different installer and it sometimes has better error handling when there is an issue with the installer.

**Comment by El-Ktrin** [comment]
> Reference

Perfec!!!

This installer already work for me.

Thank you!
