### ISSUE TITLE
Undo/Redo functionality

### ISSUE THREAD

**Issue by tcressy** [files-community/Files#14274]
### What feature or improvement do you think would benefit Files?

When moving, copying, renaming files, etc. it quickly becomes frustrating that there is no undo functionality. Please, can these features be added...

### Requirements

- Add undo/redo buttons to the toolbar.

### Files Version

3.0.15.0

### Windows Version

10.0.19045.3803

**Comment by Josh65-2201** [comment]
Thanks for the feedback, there already is with `Ctrl + Z` for undo and `Ctrl + Y` for redo

**Comment by yaira2** [comment]
I suppose it wouldn't hurt to show the option in the context menu as well

**Comment by tcressy** [comment]
Thanks! I couldn't find that in the documentation anywhere.
Could toolbar buttons be added though? (Like the quick access toolbad buttons in Windows Explorer)

**Comment by tcressy** [comment]
![image](https://github.com/files-community/Files/assets/47476731/a7282c19-7f25-4371-aaa0-ab046a6c7dff)
