### ISSUE TITLE
Several performance issues

### ISSUE THREAD

**Issue by Pit1288** [files-community/Files#14272]
### Description

Unfortunately I'll be uninstalling Files. The UI is great but the performance is way far from being acceptable

- Speed issues. After hours of use, the app will become slower and slower. If you sleep your computer, when you start up will take 3 seconds to open a folder and details/thumbnails will take forever to load and other will never load, the thumbnails will be the same for ALL the files.
![001](https://github.com/files-community/Files/assets/154396564/91d1b1de-f0c1-4372-84cd-21c4510bc437)

- Dragging files is an absolute nightmare. The whole column gets selected and you can't do this with programs on top, you can only drag to the taskbar, wait for the program to open, a "link" message appears and then it will open, so it takes 7 seconds to drag a file. 
![000](https://github.com/files-community/Files/assets/154396564/986fd1a0-0f95-4ada-8855-ce120086c917)

- If you are in a folder with lots of files, scroll down and switch the window, when you come back the window will scroll up itself.

Even though the best part is the UI, it does have minor details like the settings round square not being the same height as the search bar
![002](https://github.com/files-community/Files/assets/154396564/f18301e5-afad-4f1b-9493-7e12585befc1)

### Steps To Reproduce

Open notepad, select a .txt file and drag it to the app.

### Requirements

- e.g. Fix crash that occurs when...
With regular light use.

### Files Version

3.0.15.0

### Windows Version

10.0.19045.3803

### Log File

[debug.log](https://github.com/files-community/Files/files/13732297/debug.log)

**Comment by yaira2** [comment]
> Speed issues. After hours of use, the app will become slower and slower. If you sleep your computer, when you start up will take 3 seconds to open a folder and details/thumbnails will take forever to load and other will never load, the thumbnails will be the same for ALL the files.

This can happen as memory usage builds up, we'll continue looking for ways to optimize this behavior but the best workaround for now is to turn off the option to keep Files open in the background.

> Dragging files is an absolute nightmare. The whole column gets selected and you can't do this with programs on top, you can only drag to the taskbar, wait for the program to open, a "link" message appears and then it will open, so it takes 7 seconds to drag a file.

We'll need some more info on this, can you open a separate bug report so we can investigate the issue?

> If you are in a folder with lots of files, scroll down and switch the window, when you come back the window will scroll up itself.

Thanks for the report, this is currently being tracked in #13220. It's on our todo list to fix but it's proven to be a little tricky.
