### ISSUE TITLE
Unable to pin program to start menu

### ISSUE THREAD

**Issue by Krokochik** [files-community/Files#14275]
### Description

Attempting to pin .exe to start menu crashes the app

### Steps To Reproduce

As far as i understood, it is enough just to trynna pin .exe to start menu from the options menu

### Requirements

Pinning app to start menu, or, at least showing error dialogue w/o crash :)

### Files Version

3.0.15.0

### Windows Version

10.0.22631.2428

### Log File

[debug.log](https://github.com/files-community/Files/files/13732867/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/13732872/debug_fulltrust.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #13947. You can check there or click subscribe in the right sidebar for updates.
