### ISSUE TITLE
McAfee doesn't show in context menu

### ISSUE THREAD

**Issue by Cflogithub** [files-community/Files#14270]
### Description

When I try to scan a file with the mcafee antivirus from the context menu it does not run.

### Steps To Reproduce

Run Files application
Select a file to scan
Click on secondary mouse boton to open contextal menu 
Select Analize with Mcafee
Nothing happens

### Requirements

- e.g. Fix crash that occurs when...
Expected to rub the antivirus scan for the file selected 

### Files Version

3.0.15.0

### Windows Version

Edición Windows 11 Home Single Language Versión 23H2 Instalado el 29/09/2022 Versión del sistema operativo 22631.2861 Experiencia Windows Feature Experience Pack 1000.22681.1000.0

### Log File

[debug.log](https://github.com/files-community/Files/files/13731326/debug.log)

**Comment by yaira2** [comment]
Thanks for the report, we've found that the shell extensions for most anti-virus software aren't compatible with Files. We're not sure why this is the case but suggest sharing this feedback with McAfee in case they can fix the behavior.

**Comment by Cflogithub** [comment]
Thanks for your quick answer, then I will report this issue with McAfee support.

**Comment by yaira2** [comment]
Thanks! We'll keep tracking this here for the time being in case someone comes up with a workaround we can implement from our side.

**Comment by yaira2** [comment]
I think we can continue tracking this in #8251.
