### ISSUE TITLE
Put pCloud Drive back in the Drives list

### ISSUE THREAD

**Issue by Colin-VideoRevealed** [files-community/Files#14279]
### What feature or improvement do you think would benefit Files?

Quick access to pCloud

### Requirements

Allow user selectable cloud drives to also show in the Drives section. 
Maybe Right-click on the cloud drive and select Add To Drives

### Files Version

3.0.15.0

### Windows Version

10.0.22631.2861

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Have you used the cloud drives section in Files?

**Comment by yaira2** [comment]
Thanks for the feedback, pCloud can be found under the Cloud Drives section. If it's not displaying there, please let us know and open a bug report so that we can look into it.

**Comment by Colin-VideoRevealed** [comment]
I confused Explorer with Files. pCloud in Explorer shows up in Devices and Drives, which I like.

**Comment by yaira2** [comment]
Thanks for the clarification, we display it under cloud drives to be consistent with OneDrive and the other cloud drive providers.
