### ISSUE TITLE
Lock column headers in detail views

### ISSUE THREAD

**Issue by bdmacl1** [files-community/Files#14273]
### What feature or improvement do you think would benefit Files?

the column header row shouldn't scroll up and disappear IMHO. Especially with the different Date options, it's good to be able to quickly glance at that top row to remind yourself which Date item you are looking at. The original File Explorer with Windows has trained us to expect that feature.

### Requirements

- Allow a quick review of which columns have been selected in Detail view
- Allow for quick reference to which item you are looking at in the Detail view

### Files Version

3.0.15.0

### Windows Version

10.0.22631.2861

### Comments

Maybe this is possible already, but being a new user, I couldn't find it anywhere.

**Comment by Josh65-2201** [comment]
Thanks for the feedback, the headers scrolling out of view has been fixed and will be available on the next update.
