### ISSUE TITLE
Please include

### ISSUE THREAD

**Issue by ziggystardust47** [files-community/Files#14278]
### What feature or improvement do you think would benefit Files?

I use Norton Utilities and, in Windows Explorer, when I right-click on a file, 'Norton 360' appears and I can scan the file. Can this be included in the Files App?

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.0.15.0

### Windows Version

10.0.22631.2861

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Files doesn't support the new context menu Windows 11 uses yet, We're tracking this in #8251. You can check there or click subscribe in the right sidebar for updates. Right now Norton would have to add an option to support the older system.

**Comment by yaira2** [comment]
As a side point, I've found that most anti-virus software inject the context menu items directly into File Explorer instead of using the shell extension system that other apps use.

**Comment by ziggystardust47** [comment]
Thanks for the prompt reply. So, what your saying is that it's up to Norton to add this to your menu?
Rob
________________________________

**Comment by yaira2** [comment]
That’s correct, Files has support for regular shell extensions (this is how most apps add items to the context menu) but if Norton isn’t being shown, it’s likely that they’re adding the menu item differently and there’d have to add special support for Files. Just to confirm, did you check under the “show more options” menu?

**Comment by ziggystardust47** [comment]
Yes, I selected 'Show more options'. Still no Norton option.
Robert

Get Outlook for Android<https://aka.ms/AAb9ysg>
