### ISSUE TITLE
More options to sort files

### ISSUE THREAD

**Issue by Pit1288** [files-community/Files#14271]
### What feature or improvement do you think would benefit Files?

The app lacks important sorting options like duration. I work with videos and this not being available kills me. This is a good personalization that can be brought in from Windows, their options are endless.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.0.15.0

### Windows Version

10.0.19045.3803

### Comments

You have a native "tag" option, who tags files??? They even got their own section in Settings. This is like the "rating" feature that Windows had and nobody used.

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #8366. You can check there or click subscribe in the right sidebar for updates.

**Comment by Pit1288** [comment]
> Thanks for the feedback, We're tracking this in #8366. You can check there or click subscribe in the right sidebar for updates. The tags system also doesn't have to be used as a replacement for the rating features and isn't is only use case

So you are referencing a ticket from more that 1 year ago and still this was not added?

**Comment by Josh65-2201** [comment]
It will be made eventually but it isn't easy to implement since there a lot of code that wasn't well maintained, It's currently being fixed but will take time. Files also is community developed so people get to chose what they want to do and with the very small developer base Files has it hasn't been a priority.

**Comment by yaira2** [comment]
> So you are referencing a ticket from more that 1 year ago and still this was not added?

There are quite a few changes needed to make this one happens. More recently we laid the foundation for auto generating columns but there is still work to be done.
