### ISSUE TITLE
Bug: Drag and drop on duel pane crash

### ISSUE THREAD

**Issue by brett-baker** [files-community/Files#14286]
### Description

drag drop 48 files from new pane to standard pane on network synology drive.

### Steps To Reproduce

open nas directory
open sub dir in new pane
delete contents of directory
drag contents of sub folder to the original folder

### Requirements

-Fix crash that occurs when...

### Files Version

3.0.15.0

### Windows Version

10.0.22631.2861

### Log File

[debug.log](https://github.com/files-community/Files/files/13761666/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
This appears to be resolved in the preview version https://files.community/download/preview. If you're still able to reproduce this after updating, please let us know and we'll take another look.
