### ISSUE TITLE
Leave app running in background does not make much different

### ISSUE THREAD

**Issue by Dadangdut33** [files-community/Files#14280]
### Description

It seems like there is not much different between enabling or disabling the setting `leave app running in background`. The thing is even when i enable it, files will still need to load the previously opened folder first and this can take a lot of time considering how many folder that i have opened.

Shouldn't it just load instantly because it's in the background just like any other app (discord for example)?

### Steps To Reproduce

1. enable leave app running in the background
2. close files
3. open files

### Requirements

It should not need to load again because the app should still be running in the background

### Files Version

3.0.15.0

### Windows Version

Edition	Windows 11 Pro Version	23H2 Installed on	‎11/‎05/‎2023 OS build	22631.2861 Experience	Windows Feature Experience Pack 1000.22681.1000.0

### Log File

[debug - Copy.log](https://github.com/files-community/Files/files/13745329/debug.-.Copy.log)

**Comment by yaira2** [comment]
The feature is designed to bypass the splash screen, can you confirm if you are still seeing the splash screen?

**Comment by Dadangdut33** [comment]
The splash screen is still there for me (the one with the loading spinner)

**Comment by yaira2** [comment]
It's possible the existing instance is in a stuck state so it's trying to spin up a new one. You can force close the existing instance by running `taskkill -f -im files.exe` and then opening Files again.

**Comment by Dadangdut33** [comment]
doing `taskkill -f -im files.exe` seems to work. The splash screen is not there anymore.

But the tabs will still needs to load again, is that just how its intended? 

can you make it so that is just loads instantly instead. Maybe just hide the window or something. Files is really great except that it's sometimes slow like that

**Comment by yaira2** [comment]
> can you make it so that is just loads instantly instead. Maybe just hide the window or something. Files is really great except that it's sometimes slow like that

As far as leaving the tabs open, we want to have the smallest memory footprint possible when the app isn't actively being used. That said, you should be able to get close to this behavior by minimizing the app instead of closing the window.

**Comment by Dadangdut33** [comment]
Well if that's how it is then i kinda don't see any point in using this anymore. Guess i'm back with using onecommander.

**Comment by yaira2** [comment]
Did you try minimizing the window?

**Comment by Dadangdut33** [comment]
Well yes, but that's not really the point. It's just that there is that habit of closing unneeded windows when you are done with them. Sometimes you want your taskbar to be clean so that the alt tab is not cluttered.

Maybe you guys can implement the _keep tabs loaded_ or something as an option.

Don't worry I'll keep on checking files until it gets its big performance update

**Comment by yaira2** [comment]
@hishitetsu fyi

**Comment by hishitetsu** [comment]
The current implementation does not allow any processing when the app is in the background. Therefore, changes that occur while the app is in the background will not be reflected without reloading the tabs.
