### ISSUE TITLE
Feature: Allow disabling automatic scrolling to parent folder

### ISSUE THREAD

**Issue by siloricity** [files-community/Files#14282]
### What feature or improvement do you think would benefit Files?

I go in and out of folders often, and the way that it scrolls to the folder I entered is mildly annoying when I want to go to different folders quickly. It also just looks jank while trying to load all the icons and then jumping to the folder

### Requirements

Add a setting in Files to disable this behavior

### Files Version

3.0.15.0

### Windows Version

10.0.22621.2861

**Comment by yaira2** [comment]
Thank you for the feedback

**Comment by yaira2** [comment]
Support for disabling auto scroll will be included in the next release.
