### ISSUE TITLE
Startup Settings: Set Specific Page to Android Device Folder

### ISSUE THREAD

**Issue by MtnWindows** [files-community/Files#14284]
### What feature or improvement do you think would benefit Files?

Thanks for pointing out the Specific Pages option; however, I cannot set it to "This PC\GalaxyTabA7\SD card\Pictures\Instagram". It says, "Path does not exist." even though I can set it to that location by browsing in the app. Incidentally when I click on that folder location in the box it says "\\?\GalaxyTabA7\SD card\Pictures\Instagram", but that won't work as a Specific Page either.

### Requirements

Would allow a Specific Page Startup on an Android device folder.

### Files Version

3.0.15.0

### Windows Version

10.0.22621.2861

### Comments

Original request was Set Default Folders #14263

**Comment by yaira2** [comment]
Thanks for the feedback. This looks like a bug, can you open an issue as a bug report?
