### ISSUE TITLE
Bug: Taskbar Overlaps App in Full Screen Mode

### ISSUE THREAD

**Issue by Qin-shihuang** [files-community/Files#14292]
### Description

When entering full screen mode, part of the app is displayed beneath the taskbar.
Switching to the dev version 3.0.16.0 did not resolve the issue.
![image](https://github.com/files-community/Files/assets/68013339/04df218e-d7e2-4289-803d-6d426b49afb9)

### Steps To Reproduce

Press F11 or use command palette to enter full screen mode

### Requirements

The app should display above the taskbar, or the taskbar should hide

### Files Version

3.0.15.0

### Windows Version

10.0.19045.3693

### Log File

[debug.log](https://github.com/files-community/Files/files/13768550/debug.log)

**Comment by yaira2** [comment]
Thanks for the report, this was supposed to have been fixed in #13207 so we'll have to investigate why it's back.

**Comment by yaira2** [comment]
Does it also overlap when the taskbar is at the bottom of the screen?

**Comment by Qin-shihuang** [comment]
> Does it also overlap when the taskbar is at the bottom of the screen?

Yes, it occurs regardless of where the taskbar is positioned on the screen.

![image](https://github.com/files-community/Files/assets/68013339/9280c9ee-c511-4cd0-9130-232226cfece4)
![image](https://github.com/files-community/Files/assets/68013339/11c4c674-19ff-4cb9-9cc0-c43a27ff547f)

**Comment by Qin-shihuang** [comment]
I've noticed that commenting out the changes made in #13207 resolves this issue. This suggests that the problem is the opposite of #10767. I think it would be helpful to determine whether to display the taskbar by detecting the user's "Automatically hide the taskbar in desktop mode" setting.

**Comment by yaira2** [comment]
@Qin-shihuang would you like to work on this?

**Comment by Qin-shihuang** [comment]
@yaira2 thanks for asking.  I've already opened a PR #14300. However I'm new here so I'm not sure where to place the new method. I would appreciate any suggestions on coding styles and the project's structure. Thank you for your patience.
