### ISSUE TITLE
Feature: Display a list of paths previously entered in the path bar

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#14295]
### What feature or improvement do you think would benefit Files?

With the recent Windows 11 Explorer update, a list of paths previously entered directly into the path bar is now displayed if the path bar is empty or "Home". This feature is useful and I wish Files had it.
![image](https://github.com/files-community/Files/assets/66369541/489854f4-6598-48e8-8d0a-2ae8abe7fa8f)

### Requirements

When the path bar is in input mode, a list of paths previously entered directly into the path bar is displayed if the path bar is empty or "Home".

### Files Version

3.0.15.0

### Windows Version

10.0.19045.3803

**Comment by yaira2** [comment]
👍
