### ISSUE TITLE
Bug: the app won't run on the background if another branch of the app is running

### ISSUE THREAD

**Issue by 0x5bfa** [files-community/Files#14291]
### Description

As the title, the app won't run on the background if another branch version of the app is running on the foreground.

Code where the problem is caused; line 161

https://github.com/files-community/Files/blob/e2fb851cd4293d0f25a7b8f97026ea4aea098090/src/Files.App/App.xaml.cs#L159-L161

Could we change the process name according to the app branch name instead of just being "Files"?

### Steps To Reproduce

1. Run the app of a version; Dev, Preview, Stable
2. Run the app of another version.
3. Close the first one's window
4. The first one's process should run on the background but not.

### Requirements

- Force to run

### Files Version

2.0.50

### Windows Version

10.0.22000.0

### Log File

No particular log was output.

**Comment by 0x5bfa** [comment]
I found this when I was testing the system tray icon. Because of this issue, the icon won't be displayed as well.

**Comment by hishitetsu** [comment]
> Could we change the process name according to the app branch name instead of just being "Files"?

I've already created an issue on this. https://github.com/files-community/Files/issues/13112

**Comment by yaira2** [comment]
For this reason, the option is turned off by default on the dev branch. Either way, let's merge with #13112
