### ISSUE TITLE
Files will run any file without default opening method as executable

### ISSUE THREAD

**Issue by Qin-shihuang** [files-community/Files#14304]
### Description

The affected files exhibit the following characteristics:

1. Assume the file name is `filename.extname`.
2. There is an entry for its extension `.extname` under `HKEY_CLASSES_ROOT`.
3. Under `HKCR`, there is an entry corresponding to the `(Default)` value mentioned in point 2, and there's no subentry `shell\open\command` under this entry, or the subentry exists but the `(Default)` value is not valid.

Double-clicking such a file in Files will open it as if it were an executable file.

I believe we need to add some additional checks around line 639 in Files.App\Helpers\Navigation\NavigationHelpers.cs or fix openViaApplicationPicker logic.

### Steps To Reproduce

1. Choose a random file.
2. Change its extension to .cur (cursor file, which has no default opening method).
3. Double-click on the file.
4. If the file is executable, it will run; if not, an Win32Exception will be logged.

### Requirements

Files should display the "Open with" interface.

### Files Version

3.0.16.0

### Windows Version

10.0.1xxxx

### Log File

[debug.log](https://github.com/files-community/Files/files/13777964/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #14137. You can check there or click subscribe in the right sidebar for updates.

**Comment by Qin-shihuang** [comment]
@Josh65-2201 Yes, I had previously reviewed issue #14137, but this seems to be a different problem. The issue in #14137 appears to only affect specific .zip files, but this issue impacts the entire file extension.
