### ISSUE TITLE
Feature: Option to hide compression options from the context menu

### ISSUE THREAD

**Issue by Hisuinoi** [files-community/Files#14305]
### What feature or improvement do you think would benefit Files?

Hello,
I came across this Explorer alternative in mid-November. Because Explorer still causes far too many problems in Windows 11.

And I have to say I like it very much so far.
Except that "Files" still crashes a bit too often and I don't dare to do larger copy operations.

But I think this is more likely to happen with the integrated "7zip".
So far I've only noticed that it doesn't run reliably, crashes, doesn't unzip properly.  

My separate "7-zip" runs much more reliably and especially when it crashes the explorer/files are not taken away.

What I would like to see in Files in the future:
- More freedom in the individual menu
- Remove the menu item "Unzip" because I prefer to use 7-zip separately and don't want to see two entries in it! 

- Further improvements to stability and reliability

I don't need any more bells and whistles, I'm already very satisfied. You're already doing a lot better than fucking Microsoft. :D

I want to reinstall Windows 11 in February or March.
Since the upgrade did not go so well, because there are still one or two problems, especially massive problems with the WIN 11 23H2 update.

Perhaps some stability problems are related to this.
But the fact is that I don't like the fact that 7-zip was integrated directly. This simply allows far too many problems.

Better remove it again and install 7-zip separately and implement a better integration.

Thank you.

### Requirements

- Add option to context menu settings to hide compression options

### Files Version

3.0.15.0

### Windows Version

10.0.22621.2506

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Please open a bug report for each crash you have. As for the 7zip integration, you don't need to use it. You can change the default for archives to open with 7zip and it will show in the context menu for the options too.

**Comment by Hisuinoi** [comment]
I can NOT deactivate the integrated 7zip from you! That the menu entry from you disappears!

**Comment by Josh65-2201** [comment]
There isn't a way to or need do so, the normal 7zip program show there too and you can change the default archive to 7zip rather than Files in Right click > Open with > Select 7zip > Set as default.

**Comment by yaira2** [comment]
@Hisuinoi do you mean a way to hide the built-in options for extracting? We already have options to hide some of the other items so I don't see why we can't do this as well.
![image](https://github.com/files-community/Files/assets/39923744/2d3032da-fc84-4399-a6b0-46113e473ca1)

**Comment by yaira2** [comment]
@Hisuinoi this feature will be included in the next update.
