### ISSUE TITLE
Bug: Date Modified column does not display when searching in unindexed folders

### ISSUE THREAD

**Issue by Qin-shihuang** [files-community/Files#14307]
### Description

When searching in unindexed folders, the columns for Date Modified and Date Created in the search results are empty. The content for these two columns appears only after clicking on "Search unindexed items"

![image](https://github.com/files-community/Files/assets/68013339/5ce95ea1-78d6-42db-b445-c107e206a338)

### Steps To Reproduce

1. Create a folder in C:\
2. Create some files in the folder
3. Enter the folder and search for one file
4. The two columns are empty
5. Click "Search unindexed items"
6. The date information appears

### Requirements

Date Modified and Date Created should display

### Files Version

3.0.16.0

### Windows Version

10.0.22621.2861

### Log File

.

**Comment by yaira2** [comment]
Thanks for the report

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by Qin-shihuang** [comment]
No, the time is displaying now.
