### ISSUE TITLE
Recent files in Sidebar

### ISSUE THREAD

**Issue by AleMello** [files-community/Files#14308]
### What feature or improvement do you think would benefit Files?

Hate to say, one thing I like in File Explorer is that it shows some recent folders in the sidebar. It's very useful when we need to quickly select recurring folders. 
I'm adding this folders to favorites, reordering them to appear on top and when I finish the project I remove it.
But if these could appear automatically, it'd be great.

### Requirements

![image](https://github.com/files-community/Files/assets/4070249/fdb1f5c4-5866-49bc-814a-02350faeb6e3)
Just add  a couple of folders to the sidebar...

### Files Version

3.0.15.0

### Windows Version

11 pro 23H2 build 22631.2861

**Comment by yaira2** [comment]
Thank you for your feedback, the sidebar was designed to be static so displaying recent folders would go against the current design. I understand it's a little different than File Explorer and it might take a bit to get used to the different flow, but our intention was to let users decide which folders they need most. That said, the home page is a little more dynamic and is designed to show both recent folders and recent files so perhaps that can help.

**Comment by sebastianzander** [comment]
> [...] That said, the home page is a little more dynamic and is designed to show both recent folders and recent files so perhaps that can help.

How can I see recent folders in the home page? I only see recent files. I expect you use the same operating system functions to receive the list of recent folders, right? Because, I would expect a folder to appear at the top of the recent items even if I changed a file in the folder; and not only when the folder itself is somehow updated.

**Comment by Josh65-2201** [comment]
You can see 3 recent folder from Quick access on the home page but there isn't a dedicated section like recent files
