### ISSUE TITLE
Thumbnail previews for PSD and PSB Files

### ISSUE THREAD

**Issue by Thepixchanger** [files-community/Files#14310]
### What feature or improvement do you think would benefit Files?

Create thumbnail previews for PSD and PSB files in Files app

As a graphic designer, I often work with PSD files, which are the native format of Adobe Photoshop.  one drawback of PSD files is that they do not have thumbnail previews in Windows File Explorer and in Files app. This means that I have to open each file individually to see what it contains, which is time-consuming and inefficient.

That is why I would love to have PSD thumbnail previews in the Files app. This feature would allow me to quickly browse through my PSD files and find the ones I need without opening them. It would also help me organize my files better and avoid duplicates or unwanted files. PSD thumbnail previews would make my workflow much easier and faster, and I hope that the Files app will consider adding this feature in future updates, which will be a game-changer and a plus point for people to switch to the Files app rather than sticking to Windows File Explorer.

### Requirements

You can get a license for the PSD and PSB codec from Adobe. Mac users don’t need any additional software, as Apple provides a PSD and PSB codec in their Finder application. However, Windows doesn’t have this feature. If you add this feature, people will start switching to the Files app rather than sticking to Windows File Explorer.

### Files Version

3.0.15.0

### Windows Version

10.0.22631.2861

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Adobe would have to have support for thumbnail generation in Photoshop for Windows.

**Comment by yaira2** [comment]
Isn’t there a third party too, that can generate them as well?

**Comment by Thepixchanger** [comment]
There are some third-party tools like Mystic Thumbs and Sage Thumbs, but I heard they create some problems. I would like to have it as an inbuilt feature rather than a third-party one. If possible, please try to add it.

**Comment by yaira2** [comment]
Sage Thumbs is what I was thinking of. The thumbnail system in Files is the same one that File Explorer uses. Using an existing system allows us to focus on other improvements without getting caught up in the never ending task of creating previews for all the different file formats (not to mention that many file formats rely on proprietary code to generate the previews).

**Comment by Thepixchanger** [comment]
Okay, I understand. Thank you for the reply.
