### ISSUE TITLE
Feature: Support for larger thumbnails in the column layout 

### ISSUE THREAD

**Issue by fazioliamboina** [files-community/Files#14318]
### What feature or improvement do you think would benefit Files?

when using column mode, i can no longer see the thumbnail tiles properly. this renders the column mode completely impractical.

### Requirements

allow river view / tile view / filmstrip view / details view on the right pane, when using column mode.

### Files Version

3.0.15.0

### Windows Version

10.0.22631.2861

**Comment by Josh65-2201** [comment]
Thanks for the feedback, column mode isn't built for viewing videos and photos and wouldn't make sense for navigation. The features you want are likely in the preview pane (Alt+Ctrl+i)

**Comment by yaira2** [comment]
Thanks for the feedback, we’ll keep this in mind as we continue exploring additional density options for the different layouts.

**Comment by yaira2** [comment]
Thanks for the feedback. We don't have any plans to implement this feature, but we’ll keep it in mind as we continue exploring additional density options.
