### ISSUE TITLE
Search by date--essential

### ISSUE THREAD

**Issue by Mezzomamma** [files-community/Files#14311]
### What feature or improvement do you think would benefit Files?

I really have to search by date on a regular basis, but I can't find a way of doing this with Files--not just sorting a single file by date. Please tell me how or add it. I bought this product because my Files Explorer has failed, and even the Microsoft help line can't restore it.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

Don't know, just got it for emergency

### Windows Version

windows 11

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #4813. You can check there or click subscribe in the right sidebar for updates.

Right now you can use the same system as Windows File Explorer `date:<System time format>` for a specific day or `date:<` to search the entered date and above.

**Comment by Mezzomamma** [comment]
Thanks, I was entering datemodified: which didn't work. (Seriously stressed after hours spent on my own & then with MS support but with no result.)
Cheryl
