### ISSUE TITLE
Winget support

### ISSUE THREAD

**Issue by rumplin** [files-community/Files#14312]
### What feature or improvement do you think would benefit Files?

Make Files installable via winget.

On the Microsoft store it's called "Files App", here it's "Files". Neither is found on winget.

### Requirements

- Easier deployment on multiple machines
- Managment of versions
- More reach to potential new users

### Files Version

3.0.15.0

### Windows Version

10.0.22621.2861

### Comments

Command in terminal for winget: `winget search "Files"`

**Comment by yaira2** [comment]
Thanks for the question, please see our response here https://github.com/files-community/Files/issues/8653#issuecomment-1080781505.

**Comment by Danik1601** [comment]
https://github.com/files-community/Files/issues/8653#issuecomment-2065351806

**Comment by Josh65-2201** [comment]
@rumplin Files is now available to download on Winget

**Comment by rumplin** [comment]
Perfect!
