### ISSUE TITLE
Viewmode for fullscreen (slide style) browsing Like XnViewMP

### ISSUE THREAD

**Issue by fazioliamboina** [files-community/Files#14316]
### What feature or improvement do you think would benefit Files?

This viewmode will accomplish tagging or moving files based on hard to see details being viewed in fullscreen, or while 'consuming' videos and photos. XnViewMP and FastStone do this well, but suck at file management itself. Also WinAppSDK has better capabilities for video playback than XnViewMP and faststone give us. also nagivating trough files in fullscreen/slideshow will automatically select the last shown file. thats another integration issue we have when using external viewers.

### Requirements

- it has to support and play video files
- it has to support keyboard navigation for skipping 10 seconds forward or backwards in videos.
- it can show .txt or pdf files by their type thumbnails as if the thumbnail is the photo, the same way xnview would handle that scenario.
- image zooming needs to be possible.
- it needs to support fullscreen on black background.
- maybe overhead display showing filename and and file position like: 11/143

### Files Version

3.0.15.0

### Windows Version

10.0.22631.2861

**Comment by Josh65-2201** [comment]
Thanks for the feedback, have you tried using the preview pane (Alt+Ctrl+i) and expanding it to the left?

**Comment by fazioliamboina** [comment]
i have tried that. unfortunately XnViewMP is still my preffered application to manage videos and photo collections, because it is a fullscreen-first design.

the preview pane is only acceptable on ultrawide 21:9 monitors. unfortunately, my laptop is a 3:2 surface device. its also lacking zoom, and video skip-trough shortkeys.

**Comment by yaira2** [comment]
I know this isn't the response that you're looking for, but I want to be transparent that this feature request isn't in line with our vision for Files. The preview pane is designed to display a basic preview, but it's not intended to be a full-fledged viewer.
