### ISSUE TITLE
Source string "SecurityModifyLabel/Text" missing for most languages

### ISSUE THREAD

**Issue by Qin-shihuang** [files-community/Files#14314]
### Description

Currently, the "SecurityModifyLabel/Text" string for most languages is missing and it defaults to "Rediger" in Danish.

![image](https://github.com/files-community/Files/assets/68013339/b04ded47-e394-4ce1-aea5-a5bbf10f7919)
![image](https://github.com/files-community/Files/assets/68013339/daaac4fc-98a6-48e7-8078-8c27f987d930)

### Steps To Reproduce

Select a file, navigate to "Properties -> Security -> Advanced Permissions"

### Requirements

Add the string

### Files Version

3.0.16.0

### Windows Version

10.0

### Log File

.

**Comment by yaira2** [comment]
Thanks for the report. This is by design, if a string isn’t translated in one language, it’ll fall back to the closest language.

**Comment by Qin-shihuang** [comment]
I couldn't find a corresponding entry to translate on Crowdin. Should there be one there?

________________________________

**Comment by yaira2** [comment]
I see the issue now, I'll push a fix.
