### ISSUE TITLE
Lets raise our voice to microsoft for which WinUI features we need right now

### ISSUE THREAD

**Issue by fazioliamboina** [files-community/Files#14324]
### What feature or improvement do you think would benefit Files?

i know the title sounds like a joke, but this is a very serious commitment we have to make.

It will improve our entire App in ways we cannot manage by our own.

### Requirements

- we could post youtube videos with our needs and ask users to upvote them so it draws attention for microsoft
- we could add a "Dear microsoft" section in our files settings.

### Files Version

3.0.15.0

### Windows Version

11

**Comment by yaira2** [comment]
Thanks for the feedback, the best place to share this type of feedback is on the WinUI repo.

**Comment by fazioliamboina** [comment]
We are one of the most popular apps in the microsoft store. we can make microsoft sweat if we added a "dear microsoft" section in our app settings window. it might also help a lot to raise attention for winappSDK and WinUI. if we let users know what big a deal WinUI and WinAppSDK is, and what it is, more people can raise feedback and understand how this is the foundation of what all their inbox apps can do. Image how much WinUI can benefit if noob users also know about how it limits their computer.
