### ISSUE TITLE
every tagged file in the tags.db need to store the files hash for automatic recovery after files move.

### ISSUE THREAD

**Issue by fazioliamboina** [files-community/Files#14321]
### What feature or improvement do you think would benefit Files?

this will make tagged file more persistant and more backuppable, and it will allow me trust the platform for serious usage.

### Requirements

when a file gets tagged, get the file hash and store it in the DB.

### Files Version

3.0.15.0

### Windows Version

11

**Comment by Josh65-2201** [comment]
Thanks for the feedback, tags aren't stored in a database. They are attached to the files/folders with the NTFS ADS system. If you want to use the same tags on multiple systems use the import/export function in Files settings > Advanced.

**Comment by fazioliamboina** [comment]
but how to recover when the file paths change? export import cannot fix that?

**Comment by Josh65-2201** [comment]
It will follow the file automatically.

**Comment by yaira2** [comment]
The import/export is only needed to match the tag name to the hash in the data stream.
