### ISSUE TITLE
Feature: Add 10 seconds back and forward buttons in preview pane for videos (discussion)

### ISSUE THREAD

**Issue by fazioliamboina** [files-community/Files#14327]
### What feature or improvement do you think would benefit Files?

N/A

### Requirements

Display skip forward/backward buttons when the preview pane is wide enough

### Files Version

3.0.15.0

### Windows Version

11

**Comment by Josh65-2201** [comment]
Thanks for the feedback, I've added this to the project board.

**Comment by fazioliamboina** [comment]
+1 for comprehensive title change

**Comment by yaira2** [comment]
The default width of the preview pane is too small to accommodate these buttons but we can use some visual states to display them when the pane is wide enough.

**Comment by yaira2** [comment]
I looked into this, and it appears that while we can display the skip buttons, they will take preference over the seek bar on smaller screens.
![image](https://github.com/files-community/Files/assets/39923744/b0dcc655-02b7-4dbf-a26e-c6c40bbae2a3)

**Comment by x3rt** [comment]
> they will take preference over the seek bar on smaller screens
I believe that the seek-bar should take priority over the buttons as with shorter videos (Let's say 40 seconds) the buttons wouldn't really be of much help, whereas the seek-bar can do everything the buttons do, and it gives you more granular control, and helps you **preview** the contents of the video better (i.e you can quickly scrub through to preview)

**Comment by yaira2** [comment]
It's also worth pointing out that you can skip around by holding down the arrow keys.

**Comment by yaira2** [comment]
Thank you for reaching out with your feature request. We understand that having 10-second skip buttons in the video preview pane can be a convenient tool for navigating content. However, after careful consideration, we have decided not to implement this feature at the current time. We are committed to continuous improvement and will keep your suggestions in mind for future updates.
