### ISSUE TITLE
Tags need to be tree structure

### ISSUE THREAD

**Issue by fazioliamboina** [files-community/Files#14320]
### What feature or improvement do you think would benefit Files?

- Improved privacy (collapse private tags)
- improved functionality (better categorisation)

### Requirements

Add a ParentTagID column to the .db tag and you are done.

### Files Version

3.0.15.0

### Windows Version

11

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #12738. You can check there or click subscribe in the right sidebar for updates.
