### ISSUE TITLE
Issues with Classic Installer

### ISSUE THREAD

**Issue by writeadam** [files-community/Files#14329]
### Description

I haven't been able to get the application to install using the Classic Installer, - on either my work or my home computer.  In the install dialog, I get an error saying "An error occurred because a user was logged off". 

### Steps To Reproduce

Download & run the classic installer. 

### Requirements

- e.g. Fix crash that occurs when...
Fix installer so that it works. 

### Files Version

3.0.15.0

### Windows Version

10

### Log File

Not found.

**Comment by Josh65-2201** [comment]
Can you try the below
1. Opening PowerShell as administrator
2. Run this command
```Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/stable/Files.Package.appinstaller```
3. See if Files is in the start menu all apps section

**Comment by dannybonte** [comment]
I tried this and got this: Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF6, Het pakket kan niet worden geregistreerd.
fout 0x80070005: tijdens het verwerken van de aanvraag, kan de uitbreiding van de windows.firewall niet door het systeem worden geregistreerd vanwege de volgende fout: Toegang geweigerd.
.
NOTE: For additional information, look for [ActivityId] 6731a312-3bde-0007-ea42-3267de3bda01 in the Event Log or use the command line Get-AppPackageLog -ActivityID 6731a312-3bde-0007-ea42-3267de3bda01
At line:1 char:1
+ Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/s ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (https://cdn.fil...ge.appinstaller:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

**Comment by Josh65-2201** [comment]
Have you install a unofficial (like Atlas OS) or modified (like disabled windows update, removed the Microsoft store, used a debloat program/script etc.) version of Windows? If so these are not supported as the remove things that aren't suppose to be.

**Comment by dannybonte** [comment]
Acer Desktop PC, genuine Windows 11. OS: Microsoft Windows 11 Home (x64) Build 22621.2861 (22H2) HWInfo

**Comment by dannybonte** [comment]
In the app store: Code: 0x80070005. Can't install...

**Comment by Josh65-2201** [comment]
Since your issue is related to Windows and not Files only there not much I can help with. Seems something is blocking the use of Windows Firewall.

**Comment by yaira2** [comment]
@writeadam did you try allowing the installation through the firewall?

**Comment by writeadam** [comment]
I was able to install the preview Verizon without issue, so am using that
for now.

Adma
