### ISSUE TITLE
Expandable Folder View

### ISSUE THREAD

**Issue by fazioliamboina** [files-community/Files#14323]
### What feature or improvement do you think would benefit Files?

I can drag and drop files to parent folders or subfolders
i do not have to waste horizontal space in column view

### Requirements

view mode option "Expandable Folders"

### Files Version

3.0.15.0

### Windows Version

11

### Comments

![image](https://github.com/files-community/Files/assets/69403673/2e0abf78-c74d-44ed-9384-7fc7ea0b115b)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #1928. You can check there or click subscribe in the right sidebar for updates.

**Comment by fazioliamboina** [comment]
i am a winUI developer. is there any way i can help?
