### ISSUE TITLE
Feature: Fullscreen button to make preview pane fullscreen, and navigate trough files by arrow keys?

### ISSUE THREAD

**Issue by fazioliamboina** [files-community/Files#14325]
### What feature or improvement do you think would benefit Files?

preview pane is horribly small on 3:2 ratio monitors. and i consume media in fullscreen by default. not in a preview pane.

### Requirements

it really needs to be fullscreen with black empty surroundings

### Files Version

3.0.15.0

### Windows Version

11

**Comment by yaira2** [comment]
Thanks for the feedback. Based on your other requests, it sounds like you might be interested in the QuickLook integration which takes image previews to the next level. This isn’t to say that we won’t consider this request but it would be helpful if you can try QuickLook and see if it has what you’re looking for.

**Comment by fazioliamboina** [comment]
I have actually tried quicklook, but uninstalled it within 10 minutes. It is the opposite of what i want. I want to review my media in fullscreen. Quicklook adds extra clicks between seeing it in fullscreen and going back and forth to the file manager. i also want to set the file tags while in fullscreen.

**Comment by yaira2** [comment]
Regarding this specific feature request, you can already resize the preview pane for a larger preview. If this isn't what you meant, please help us better your use case for this feature so we can plan accordingly and gauge if there is wider interest in this option.

**Comment by fazioliamboina** [comment]
XnViewMP is an extremely popular image browser. And So is FastStone image browser. Both platforms have the feature to middle click a thumbnail, and it opens it in uncluttered fullscreen. no taskbar, no file list, no tabs. just blank space and the image, and zoom functionality. both platforms are Browsers with build in image viewers. i think any file browser without an build in image viewer and fullscreen is DOA. File browsers are used for managing photos and videos half of the time. and working with external viewers causes this disconnect in workflow that makes anyone want to pull a finger off.

XnViewMP is obviously prefered over the files app by most people, even as ugly and outdated as it is. most users start using it as their file browser, and have more xnviewmp windows open that explorer windows. beacuse if you encounter an image, you dont want to lose the tanglement between the image and the thumbnail list.

This formula is extremely succesfull for either platforms. They are the most used media browsers. But your Files app has abilities that XnViewMP and Faststone cannot have such as riverview. which is provided by WinAppSDK. The files app could destroy XnViewMP and Faststone if it had the middle click fullscreen feature. And the ability to flip trough photos in fullscreen, and when you leave the fullscreen view, the file list is scrolled to the image that you had open in full screen before closing fullscreen.

the 2nd usecase, is you get the best of both worlds: you have a bigger preview, but also a bigger itemview for thumbnails. Most people dont leave XnViewMP or faststone after getting used to middle click fullscreen. it even destroys quicklook (also proofed by download count).

an external image viewer is not enough. because if i open an file in xnviewmpMP and close it, the files app is not scrolled to the image that i worked with. This is why image browsers like faststone and xnviewmp are so succesfull.

i believe if you implement this feature, people will learn to use it automatically and see it as innovation. i also dont think anyone would see it as bloatware. if XnViewMP removed the feature, everyone would uninstall it the same day.

**Comment by yaira2** [comment]
> You already have tags, image rotation, etc. why not make it a photo viewer, and start with the most asked feature of a photo viewer? the viewer?

I did a search for XnViewMP on the GitHub repo and out of the thousands of feature requests, you're the only one who mentioned it...

> and working with external viewers causes this disconnect in workflow that makes anyone want to pull a finger off.

I hear the use case, removing the disconnect can be a big benefit. There are other applications out there that have this capability but it's often at the expense of other features so it would require a lot of thoughtful planning. I agree that it would be a good selling point and can help expand the user base, but our number one priority (based on feedback from existing users) is to continue working on improving the basics like performance, stability, list view, tree view etc.

**Comment by fazioliamboina** [comment]
sorry! i did not meant to say that it was the most asked feature for Files. i meant that the most important feature for "an image viewer".

**Comment by yaira2** [comment]
As posted in #14316, we don't have plans to add this option to Files.
