### ISSUE TITLE
Files display wrong disk space stats when a drive is almost full

### ISSUE THREAD

**Issue by mon-jai** [files-community/Files#14334]
### Description

The screenshot should be descriptive enough by itself. ("8.46 GB free" vs "76.7 MB free" on C drive)

![Screenshot (87)](https://github.com/files-community/Files/assets/91261297/d64464e9-db00-4e72-9b70-b7e56f3a90d7)

### Steps To Reproduce

1. Open files

### Requirements

- Fix disk space stats when a drive is almost full

### Files Version

3.0.12.0

### Windows Version

10.0.22621.2861

### Log File

Unfortunately I didn't export the log file when the bug occurred.

**Comment by Josh65-2201** [comment]
Thanks for the report, can you please try closing and reopening Files to see if they match.

**Comment by Lukiluc29** [comment]
Wouldn't this problem be equivalent to this one? #6182

**Comment by yaira2** [comment]
> Contributor

It probably is but will be confirmed if it updates after they restart Files.

**Comment by yaira2** [comment]
Thank you for the report, we're going to continue tracking this issue in #6182.
