### ISSUE TITLE
Replace the window of the selected file

### ISSUE THREAD

**Issue by Kagura-Nanaa** [files-community/Files#14333]
### What feature or improvement do you think would benefit Files?

Replace the file selection window opened by chrome or other applications with files

### Requirements

It's this window in the picture. It doesn't seem all that important, but this might enhance some of the comfort level.
I don't know if it's possible to realize.
![chrome_mM7zWtXoKU](https://github.com/files-community/Files/assets/44108528/b6edd98d-1d20-4813-838e-4e7bf6114b3a)

### Files Version

3.0.15.0

### Windows Version

10.0.23606.1000

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #6314. You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
Thanks for the feedback, this is a very difficult dialog to replace as it's bundled with Windows and there are multiple versions of the dialog used by different apps. That said, we have some ideas on how to do this and we're tracking it in #6314.
