### ISSUE TITLE
Ability to "pin" any of the options hidden in "show more options"

### ISSUE THREAD

**Issue by superluig164** [files-community/Files#14339]
### What feature or improvement do you think would benefit Files?

When opening the "show more options" menu, it shows any shell extensions you have.  My proposal is that you could right click on any of those items in the menu and "pin" them, such that, as soon as they are enumerated, they show up in the top level of the menu, similarly to what the option that shows all of them in the top level menu does, but without the clutter.  This way, I could pin, for example, "Open with HxD," "7-zip," and "What's using this file?" and those would show up below the "Show more options..." item in the top level menu.

Further, you could choose to pin, or pin for this file type, so for example I could pin an item only for .jpg files or only for .txt files.

As I write this, this could be extended to the "Open With..." menu as well, so you could have a specific program pinned there for certain file types or all files, and quickly open files with that program from the top-level menu.

My, writing this has really got my juices flowing.  The right click menu on a submenu item could show "Pin" (pin for every file), "Pin for this file type" (pin for any file with this type), "Pin in this folder" (pin for all files in this folder regardless of type), "Pin for this file" (pin on this exact file, and follow it if moved or copied with Files).  

Please excuse my stream of consciousness.  Here's a mockup I threw together illustrating what I mean.
![Screenshot 2024-01-01 200345](https://github.com/files-community/Files/assets/13702255/c452da93-4620-4a7f-916b-ed190e223d11)

### Requirements

Adding right clicking in a right click menu.

### Files Version

3.0.15.0

### Windows Version

10.0.22631.2861

**Comment by yaira2** [comment]
Thank you for your feedback, we're currently tracking this feature request in #13463. Please comment or subscribe to that issue to be notified of any updates.

**Comment by superluig164** [comment]
Got it, I'll add my thoughts there.
