### ISSUE TITLE
Memory usage keeps piling up when opening and closing files multiple time in the new preview version (3.0.17) 

### ISSUE THREAD

**Issue by Dadangdut33** [files-community/Files#14337]
### Description

I was trying out the new update in the preview version and found it weird that the memory usage is very high. I tried closing and opening it multiple times and that seems to be the cause of the problem. I have the `leave app running in background` option `checked`.

Here is a short recording of it 

https://github.com/files-community/Files/assets/57717531/3c71fdc3-c67e-4c02-b9d9-a6a128cbb601

### Steps To Reproduce

1. open files
2. close files
3. open files

### Requirements

- should not caused the memory usage to keep piling up

### Files Version

3.0.17.0

### Windows Version

10.0.22631.2861

### Log File

[debug.log](https://github.com/files-community/Files/files/13805419/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, memory leaks are known and closing Files will just minimize it to the tray with the leave running in background option on. You can kill it from task manager or turn the option off for now.

**Comment by Dadangdut33** [comment]
> 300mb is quite normal with multiple tabs open.

but it can get to 1gb and more if i just keep doing it. it was getting to 1gb before that's why i noticed it

**Comment by yaira2** [comment]
It creates a new tab each time you close and reopen the window. We're trying to find a way to clear up the memory when closing tabs, but it seems to be a bug in the WinUI tab control. To avoid the issue altogether, you can turn off the option to keep Files running in the background but the tradeoff is that it'll take longer for the app to start back up.
