### ISSUE TITLE
Files is freezing when I delete files

### ISSUE THREAD

**Issue by ThomasGerodimos** [files-community/Files#14349]
### Description

When I delete one or more files the application is stops responding

### Steps To Reproduce

1. Open Files
2. Select File to delete
3. Delete files

### Requirements

- e.g. Fix crash that occurs when...
The expected behavior is (and was at previous versions) to delete files instantly. Now if I delete 2 files I must wait at least 20 sec. 

### Files Version

3.0.15.0

### Windows Version

10.0.19045.3803

### Log File

[debug.log](https://github.com/files-community/Files/files/13813809/debug.log)

**Comment by ThomasGerodimos** [comment]
UPDATE:
When I delete the file if I check "Permanently delete" the file is deleted instantly. If I leave it unchecked then the 20sec delay and the freezing happens.

**Comment by yaira2** [comment]
Thank you for the report, this issue can occur when there are a lot of items in Recycle Bin. We're tracking this issue in #14108 and in the meantime you can work around the issue by emptying Recycle Bin.
