### ISSUE TITLE
Adjustable column width in column view

### ISSUE THREAD

**Issue by hoppenbm** [files-community/Files#14348]
### What feature or improvement do you think would benefit Files?

In the column view it would be nice to be able to alter the column width. At this moment when looking at files I'm not able to view the filenames completely and have to hover over to get the files required. 

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.0.15.0

### Windows Version

10.0.22621.2861

**Comment by yaira2** [comment]
Thank you for your feedback, this request is on our todo list and is being tracked in #6534. Please comment or subscribe to that issue to be notified of any updates.

**Comment by hoppenbm** [comment]
Hi Yair, 



Thank you I can see it now and subscribed. For GIThub it would be nice when starting the feedback it's searching the current reported/requested features and/or issue before submission. 

regards, Marco






---- On Tue, 02 Jan 2024 17:45:18 +0100 Yair ***@***.***> wrote ---





Thank you for your feedback, this request is on our todo list and is being tracked in https://github.com/files-community/Files/issues/6534. Please comment or subscribe to that issue to be notified of any updates.

**Comment by Josh65-2201** [comment]
You can search for issue on GitHub but GitHub also isn't controlled or owned by Files.

**Comment by yaira2** [comment]
> Thank you I can see it now and subscribed. For GIThub it would be nice when starting the feedback it's searching the current reported/requested features and/or issue before submission. 

Agreed, while you can search for existing issues, an AI feature that can suggest similar issues would reduce duplicate issues and save time when submitting feedback.

**Comment by hoppenbm** [comment]
I know and understand your response fully. We should do a GitHub Feature request     ---- On Tue, 02 Jan 2024 17:57:59 +0100  ***@***.***> wrote ----  
You can search for issue on GitHub but GitHub also isn't controlled or owned by Files.
