### ISSUE TITLE
Crash When Oppening Third Party Licenses

### ISSUE THREAD

**Issue by Macflylegamerlevrai** [files-community/Files#14344]
### Description

Hi! When I go in the settings then About and I click on Third Party Licenses the app crash.

### Steps To Reproduce

1. Go to the settings
2. Go to About
3. Click on Third party licenses

### Requirements

Fix crash that occurs when accessing Third Party Licenses in the app's settings. The expected behavior is that the application should not crash when the user clicks on 'Third Party Licenses' under the 'About' section. Instead, the application should smoothly display the Third Party Licenses information without any interruptions or crashes.

### Files Version

3.0.17.0

### Windows Version

10.0.22631.2861

### Log File

[debug.log](https://github.com/files-community/Files/files/13810799/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report this has been fixed and available in the next update
