### ISSUE TITLE
Bug: Drives and recent items icons randomly fail to load

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#14345]
### Description

I haven't found a way of reproducing this consistently.
![image](https://github.com/files-community/Files/assets/26977075/dc7aa855-bdd5-4ca3-97bd-cbaf5dd1831c)

### Steps To Reproduce

1. Open Files

### Requirements

- Load drives
- Load recent items icons

### Files Version

3.0.17.0

### Windows Version

10.0.22621.2861

### Log File

[debug.log](https://github.com/files-community/Files/files/13810912/debug.log)

**Comment by yaira2** [comment]
When did this start happening?

**Comment by Josh65-2201** [comment]
Yesterday, restarting my pc fixed it but it happen now too

**Comment by SakuraKade** [comment]
Do you have any network drives?

**Comment by Josh65-2201** [comment]
No, local and one external drive

**Comment by SakuraKade** [comment]
The logs mentions something about pcloud, have you ever used that service with files?
My best guess at the moment is that there might be something wrong with the CloudDriveDetector.

**Comment by SakuraKade** [comment]
I managed to reproduce the issue here are the steps:
1. Open registry editor
2. Create key `Computer\HKEY_CURRENT_USER\Software\pCloud`
3. Create string SyncDrive and set the contents to ``

@Josh65-2201 Can check the SyncDrive value in the registry?

Workaround:
Before you do this please save the contents of the SyncDrive value.
1. Open registry editor
2. delete key `Computer\HKEY_CURRENT_USER\Software\pCloud`

**Comment by Josh65-2201** [comment]
I installed then uninstalled it a while ago, there isn't a key/folder for pCloud either.

**Comment by SakuraKade** [comment]
Ok, It looks like the logs are not of much use in this case.
Gonna have to look closer at the code for loading recent items.

**Comment by yaira2** [comment]
@Josh65-2201 can you check if the icons for Recent Items load in #14423?

**Comment by Josh65-2201** [comment]
I haven't had this issue happen for a while now so cant be sure. But they do all still load in 3.1.2.0

**Comment by yaira2** [comment]
Should we close this for now?

**Comment by Josh65-2201** [comment]
I think this can be merged with #14440 since it still can be reproduce by others.
