### ISSUE TITLE
Single click support

### ISSUE THREAD

**Issue by Bobwattseface** [files-community/Files#14340]
### What feature or improvement do you think would benefit Files?

Possibly not too noticable but over time the Windows 11 UI has evolved to single click support. 

Windows File Explorer in many ways is the exception and while it does provide support for single click, this is not the default option. If the option is selected then a single click will open a folder or launch a file (through association). To allow differtiation between this behaviour and a simple select (e.g. to select items to copy), check boxes appear next to files/folders. 

Can this option be added to the Files App? Not only does it provide consistency is workflow but it's also very useful for people who suffer from RSI as a single click is less stress on the hands than a double click.

Thanks,
Leonard

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.0.15.0

### Windows Version

10.0.22631.2861

**Comment by yaira2** [comment]
Thanks for the feedback, single click is already supported. You can enable the option via the "Folders" settings page.
![image](https://github.com/files-community/Files/assets/39923744/671b7a71-38e4-45a0-9d06-5b40e758e71b)
