### ISSUE TITLE
Files is clashing when i clicked Third Party Lisence on settings -> about

### ISSUE THREAD

**Issue by Justice-Goto-3939** [files-community/Files#14343]
### Description

Files is clashing when i clicked Third Party Lisence on settings -> about.
Also, Background service is shutting down.

I'm sorry to write this report in  English.

### Steps To Reproduce

* Open Files' settings
* Click 'about'
* Click 'Third Party Lisence'

### Requirements

* Flies are Crash
* Background service is shutting down.

### Files Version

3.0.17.0

### Windows Version

1000.22682.1000.0 (Windows Insider Beta Channel)

### Log File

username in path is replacing with ****

[debug.log](https://github.com/files-community/Files/files/13810277/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report this has been fixed and available for the next update
