### ISSUE TITLE
Bug: Files Crashes a few seconds after opening

### ISSUE THREAD

**Issue by Sprinic** [files-community/Files#14358]
### Description

I bought it 2 days ago and it worked fine. Yesterday, after being open for a few seconds, it crashes everytime. I tried uninstall/intalling again and I restarted the comp; but its still doing it (today too).

### Steps To Reproduce

Open the app
Wait 10 seconds. 

https://github.com/files-community/Files/assets/155696194/7773f5a1-5626-41bf-b270-375ea3a7ea69

### Requirements

- e.g. Fix crash that occurs when I open the app. It shouldnt crash. 

### Files Version

3.0.15

### Windows Version

windows 11 version 22H2

### Log File

[debug.log](https://github.com/files-community/Files/files/13837002/debug.log)

**Comment by yaira2** [comment]
Thanks for the report, I don't see anything in the crash report but it's interesting that it was working for a bit.

**Comment by mursonic** [comment]
Similar issues over here. It sometimes crashes by itself after a while and always when opening the context menu of a file.

The only change to the system was an update to Win11 23H2.

**Comment by yaira2** [comment]
@Sprinic can you see if this is fixed in v3.1.1?

**Comment by mursonic** [comment]
I had the issue where the app would crash when pinning an executable file to the start menu.

This was fixed in 3.1.1.
