### ISSUE TITLE
Ctrl shortcuts are still not working well :(

### ISSUE THREAD

**Issue by seohyun1108** [files-community/Files#1435]
**Describe the bug**
Ctrl + C, Ctrl + V and all Ctrl shortcuts are not working well... 
So, I always click the "Copy" button. 

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 21H1 20161]
 - App version: [v0.11.0]

**Comment by Thomas1664** [comment]
I can't confirm any issues concerning shortcuts (at least on Windows 10 version 2004. For more information about shortcuts, see #9

**Comment by yaichenbaum** [comment]
@seohyun1108 Is this still an issue in v0.16?

**Comment by seohyun1108** [comment]
Now it's Ok. Thanks!
