### ISSUE TITLE
choose columns in detail view

### ISSUE THREAD

**Issue by unkilling** [files-community/Files#14355]
### What feature or improvement do you think would benefit Files?

It will be great to have an option to change columns we can see in the detail view. In example, seeing title, artist name, album name, etc about an audio file. 
Size, bitdepth for an image.
We have this king of infos in the detail panel but this is only one file at a time and it's not very conveniant.
Thank you

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.5.13.0

### Windows Version

10.0.19045.3803

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #8366. You can check there or click subscribe in the right sidebar for updates.
