### ISSUE TITLE
Powertoys Peek support

### ISSUE THREAD

**Issue by ElliotS2007** [files-community/Files#14354]
### What feature or improvement do you think would benefit Files?

Add support for Microsoft Powertoys Peek

### Requirements

- Possibly contact the Powertoys or make feature request on Powertoys for added support if necessary
- Add support

### Files Version

3.0.17.0

### Windows Version

10.0.19045.3803

**Comment by yaira2** [comment]
@ElliotS2007 thank you for your feedback, we're ready to add this feature to Files but PowerToys doesn't have an API that'll enable us to do this.
I opened an issue on the PowerToys repo to start the discussion on creating an api for third party file managers https://github.com/microsoft/PowerToys/issues/26422

**Comment by ElliotS2007** [comment]
Ah great! Let's hope that happens

**Comment by yaira2** [comment]
In the meantime, we recommend trying the other preview options listed on our documentation site https://files.community/docs/configuring/integrations

**Comment by ElliotS2007** [comment]
Will do, thanks!
