### ISSUE TITLE
Old OneDrive logo

### ISSUE THREAD

**Issue by ElliotS2007** [files-community/Files#14353]
### What feature or improvement do you think would benefit Files?

Update the OneDrive logo so it matches the desktop OneDrive app

### Requirements

- Find the logo
- Update logo

### Files Version

3.0.17.0

### Windows Version

10.0.19045.3803

### Comments

![image](https://github.com/files-community/Files/assets/67877214/f41fd712-2852-469e-8afc-62577a92ff39)

**Comment by yaira2** [comment]
Thanks for the feedback, the OneDrive icon is provided by whichever version of OneDrive installed on your device. Which version of OneDrive do you have installed?
![image](https://github.com/files-community/Files/assets/39923744/eaf99c9b-d22b-4443-92a3-4183ee72e987)

**Comment by ElliotS2007** [comment]
Here is the OneDrive version number:
Build 23.246.1127.0002 (64-bit)

**Comment by yaira2** [comment]
We fetch the icon directly from `imageres.dll`, so it has to the with version of Windows and not related to the version of OneDrive.

**Comment by yaira2** [comment]
Closing this issue as the icon is dependent on the version of Windows.
