### ISSUE TITLE
avi files are displayed like a image element instead of a mediaelement in the preview pane.

### ISSUE THREAD

**Issue by fazioliamboina** [files-community/Files#14359]
### Description

timebar also missing

### Steps To Reproduce

open preview pane
select avi file

### Requirements

n/a

### Files Version

3.0.15.0

### Windows Version

11

### Log File

no need

**Comment by Josh65-2201** [comment]
Thanks for the report, are you on the preview in the preview pane section?

**Comment by yaira2** [comment]
Files uses the same preview handlers as File Explorer so they should have the same behavior. What does File Explorer show for this format?

**Comment by yaira2** [comment]
@fazioliamboina

**Comment by fazioliamboina** [comment]
its too long ago to remember which file

**Comment by yaira2** [comment]
Are other avi files working as expected?
