### ISSUE TITLE
Archives extraction 

### ISSUE THREAD

**Issue by irk72ag** [files-community/Files#14364]
### Description

Files from the archive are not extracted by dragging and dropping from the archive opened in "Files" nor into second panel nor into any other location.

### Steps To Reproduce

1. Open archive
2. Try to drag and drop into other location

### Requirements

Bug or not functional

### Files Version

3.0.16

### Windows Version

22631.2861

### Log File

Not needed

**Comment by Josh65-2201** [comment]
Thanks for the report.
- Can you please upload (Do not copy and paste content) the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.

**Comment by irk72ag** [comment]
[debug.log](https://github.com/files-community/Files/files/13849624/debug.log)

**Comment by Josh65-2201** [comment]
We're tracking this in #13898. You can check there or click subscribe in the right sidebar for updates.
