### ISSUE TITLE
About the right click menu

### ISSUE THREAD

**Issue by bellpepper0606** [files-community/Files#14368]
### What feature or improvement do you think would benefit Files?

現在、右クリックで表示されるメニューはwindows11標準と同じですが、設定でwindows10標準に変更できるようにしたいです。そうすれば、少し特殊な操作をする人（プログラマーなど）でも負担なく操作できるようになり、さらに利用者が増えるのではないかと考えています。

DeeplTranslate
The menu displayed by right-clicking is now the same as the windows 11 standard, but we would like to be able to change it to the windows 10 standard in the settings. This would make it easier for people with slightly special operations (programmers, etc.) to operate the software without any burden, and we believe this would further increase the number of users.

### Requirements

右クリックメニューの使用に詳しくないので詳細はわからないが、「その他のオプションを表示」で表示されるもの、アイコンで表示されているもの(切り取り、コピー、貼り付け、プロパティなど)などを、すべてWndows10のように表示させるようにする。また、デフォルトは、今のままで、設定で上のようなことに変更できるようにする。
DeeplTranslate
I am not familiar with the use of right-click menus, so I don't know the details, but I would like to make all the things that are shown in "Show More Options" and those that are shown as icons (cut, copy, paste, properties, etc.) appear as they do in Wndows 10. Also, the defaults should remain as they are now, and be able to change to the above in the settings.

### Files Version

3.0.15.0

### Windows Version

10.0.22621.2861

**Comment by yaira2** [comment]
Thanks for the feedback, you can move shell extensions into the main menu from the "General" settings page.

**Comment by bellpepper0606** [comment]
Thank you.
