### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Horizon82** [files-community/Files#14360]
### What feature or improvement do you think would benefit Files?

Ability to sort within home Section
Ability to swap dual panel without clicking blank space (often times isn't a blank space) (maybe hover over, middle click, etc.)
have a copy/move/compare "midsection" between the two panels
option to add a 2nd independent tree to the 2nd panel
independent drive listing bars for dual panel
manually add/remove cloud drives in tree

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

Latest

### Windows Version

11

**Comment by Josh65-2201** [comment]
Thanks for the feedback, in future make separate issues for different feedback.

> Ability to sort within home Section

What do you want to sort in the home page?

> seperate actual drives with mapped drives in the home drive section

Assuming you mean network drives. We're tracking this in #5135. You can check there or click subscribe in the right sidebar for updates.

> Ability to swap dual panel without clicking blank space (often times isn't a blank space) (maybe hover over, middle click, etc.)
> have a copy/move/compare "midsection" between the two panels

What use case would you have? As you can use the toolbar, keyboard shortcuts (Ctrl + C and Ctrl + V) or drag and drop between them.

> option to add a 2nd independent tree to the 2nd panel
> independent drive listing bars for dual panel

Are these both talking about having another sidebar in duel pane? if so can you make a new feature request for this following the template properly

> manually add/remove cloud drives in tree

Can you make a new feature request for this following the template properly

**Comment by Horizon82** [comment]
Sorry, short of downloading a few things here and there I don't use github.

Regarding sorting in the homepage I suppose my biggest issue was grouping
mapped network drives with normal drives so being able to sort them on the
homepage was my thought. Sounds like you're already working on that.

For swapping panels I've found the only way to do it is by clicking a blank
space, actively clicking an item or clicking the very narrow slider at the
bottom.  Maybe there is a trick I'm not aware of but let's say I do have
something copied in the left pane and my right pane is filled to the brim
and I want to copy to that directory, it's difficult to activate that
panel.  i.e. a right click paste might paste to a folder within the
directory and not the actual directory.

The midsection copy/move/compare is kind of a seconding to the above
comment.  FreeCommander has this and it was very useful.  Highlight an item
in a panel, click move and it moves it over to the other panel's
directory.  The "midsection" is aware of which panel you're in and swaps
itself on the fly.  Much slicker than copy/pasting in the traditional sense.

Horrible naming on my part here but the "drive bar listing" I was
referencing is the field to the left of search where it lists the actual
full directory.  Currently it only lists the active tab. I felt having both
drive structures visible would be handy.

I'll submit a proper request for the 2nd independent tree and the manually
add/remove cloud drives.

**Comment by yaira2** [comment]
Thank you for all the feedback, it'll help us understand the different ideas and use cases if there is a separate request for each one. I'm going to close this in anticipation of the individual requests.
