### ISSUE TITLE
Please allow us to use the Peek feature on Powertoys

### ISSUE THREAD

**Issue by Angsimosaurus** [files-community/Files#14369]
### What feature or improvement do you think would benefit Files?

As far as I know, it supports one program besides Quick Look, can I also use Power Toy's Peek function?
I came across Fileapps by chance and it seems like it can be completely replaced with Windows's File Explorer.

### Requirements

- Powertoys - [https://learn.microsoft.com/en-us/windows/powertoys/](https://learn.microsoft.com/en-us/windows/powertoys/)
- Enable peek functionality within the Powertoys app
- Ultimately, file navigators such as Quicklook can preview selected files

### Files Version

3.1.0.0

### Windows Version

10.0.22635.2915

### Comments

It's a really great app.
How good would it be to use it officially by Microsoft?
😂

**Comment by Josh65-2201** [comment]
Thanks for the feedback, we're ready to add this feature to Files but PowerToys doesn't have an API that'll enable us to do this. I opened an issue on the PowerToys repo to start the discussion on creating an API for third party file managers https://github.com/microsoft/PowerToys/issues/26422. You can check there or click subscribe in the right sidebar for updates.
