### ISSUE TITLE
i understand why performance issues happen now

### ISSUE THREAD

**Issue by baselqt** [files-community/Files#14363]
### Description

i had files because i hated windows 10 file explorer, when i ran both files and file explorer the file explorer used to freeze and crash,also the performance in files app was way too slow (takes 30 seconds for every action)
but then i had enough and upgraded to windows 11 and i used files by accident, now after 2 days of usage (same version as before) files is way faster and its instant, no delay at all and i can use both explorers together, so is this a windows 10 specific problem?

### Concerned code

none

### Gains

- eg. A better readability.
- eg. Uncoupling concepts X and Y.
- eg. Clarifying the responsability of class C.

### Requirements

- eg. Using a specific design pattern.
- eg. Separating Interface I into three new interfaces I1, I2 and I3.
- eg. Regrouping the duplicated process into a new helper.

**Comment by Josh65-2201** [comment]
There shouldn't be any difference with 10 or 11 it was properly just with your install. Also please don't open code quality reports. If you have an issue use the bug template or a feature request. for questions it better to ask in the discord https://discord.gg/files

**Comment by yaira2** [comment]
@baselqt We often get reports when things go wrong so it’s great to hear that Files is working nicely, thank you for sharing! I don’t know if there is a clear answer as to why it’s performing better on Windows 11 but it might be due to the fact the WinAppSdk is targeting Windows 11 as its main platform these days.

**Comment by xman0980** [comment]
just wanted to add to this.

I was using the regular version (yellow icon) for the last few months, and kinda just dealt with the slow performance in win11. (it was still better than explorer)
i was close to dumping the program and switching to something else, but i tested the preview version (blue icon) after seeing you reference it in posts, and wow its a TON faster. I just installed it this morning, but the speed increase was noticed immediately. Great job!

**Comment by yaira2** [comment]
v3.2 was recently released to stable so you can get the same improvements without using the preview version.
