### ISSUE TITLE
Bug: App stuck on splash screen

### ISSUE THREAD

**Issue by DvanHartevelt** [files-community/Files#14366]
### Description

After learning of this program I decided to try it. I am running Windows 10 Business on a dell laptop. Using the classic installer I get no errors. However after launching Files, it gets stuck in an endless loading loop, making the program unusable.

### Steps To Reproduce

1. Downloading the classic installer from the website.
2. Executing the installer
3. instructing the installer to launch, selecting the option to launch after installation
4. after the instalation seems successful, the files application opens. it shows the icon with a loading symbol forever. It is also non responsive to windows.

### Requirements

After installation, if I open the program the crash happens.

### Files Version

3.1.0.0

### Windows Version

Edition	Windows 10 Business Version	22H2 Installed on	‎22/‎11/‎2022 OS build	19045.3803 Experience	Windows Feature Experience Pack 1000.19053.1000.0

### Log File

[debug.log](https://github.com/files-community/Files/files/13849988/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, is your computer managed by a company? They may be blocking thing Files needed to run.

**Comment by yaira2** [comment]
Considering you got the step where the app can be launched, I don't think this is related to the installer.

**Comment by mserwon** [comment]
I am having the same issue where app is stuck upon startup on spash screen on a dell computer managed by my company.  I am using windows 11 enterprise 10.0.22621.  I really was hoping that files would be my ticket out of file explorer.

**Comment by mserwon** [comment]
I tried both the Windows Store App and the preview app.

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by mserwon** [comment]
Yair,

I downloaded the Preview version today and did an upgrade and the preview version is still stuck.

I then uninstalled the preview version and reinstalled it and it is still stuck.

Michael
________________________________

**Comment by eduarddejong** [comment]
Same experience here, even when I build and deploy project from source here.
I tried both tag v3.4.1 and branch preview/3.4.5.

Running on Windows 11 Enterprise here too, indeed managed by a company, but with very limited/no enforced group policies.

Closing and reopening the window after launching it the first time does end the hang, contents are displayed the second time (when the application is actually already loaded in the background).

But still there is overall extreme slowness when navigating through drives and directories, many directories take about a full minute to load or something.

Sorry that I did look any further in the what could be reason yet.

But in fact, a seriously performant solution is the most important thing that I am looking for as well currently.

I am mostly driven by the _seriously_ laggy overall Microsoft Explorer experience in Windows 11 to be honest. This is not a good experience, to say it mildly.

**Comment by Josh65-2201** [comment]
Running from source is different then this. If your running in debug mode (F5) then it will be slow as it has to loaded debugging symbols. You should use the downloads from https://files.community/download

**Comment by eduarddejong** [comment]
> Running from source is different then this. If your running in debug mode (F5) then it will be slow as it has to loaded debugging symbols. You should use the downloads from https://files.community/download

Being aware of that, I tried it selecting the Preview and Store build configurations in Visual Studio indeed. Not Debug.

But maybe there's more to it than I know, I am not experienced with this type of applications myself.

I am now trying the preview from the link you mention, but I still experience a really long hang on startup, with the difference that it seems to have an end.
And navigation slowness is the same.

**Comment by yaira2** [comment]
Our main challenge with startup speed has been the absence of Native AOT in WinAppSdk. Fortunately, Microsoft is working to address this, and we hope to integrate these advancements later in the year.

> Being aware of that, I tried it selecting the Preview and Store build configurations in Visual Studio indeed. Not Debug.

Those still run with the debugger attached, the best way to test would be to run from the Start Menu.

**Comment by eduarddejong** [comment]
Ah, yep. JIT can also take time. Thanks for clarifying.

I did indeed launch these installed builds using the Start Menu, not using Visual Studio. So that's also not the issue I guess.

Maybe I need to try it at home on my own laptop.
There are more Windows Enterprise specific issues going then one may realize and the slow antivirus software used here is not the best one either.

**Comment by yaira2** [comment]
@DvanHartevelt can you check if this is resolved in v3.6? Thanks!
