### ISSUE TITLE
Pinning a program to start causes crash of files

### ISSUE THREAD

**Issue by Talal-Sharaa** [files-community/Files#14367]
### Description

I was attempting to pin the executable of the game called "Control" to the start menu, when "Files" crashed and asked me to report the error, I double checked and re-did my attempt, and got the same result.
Note: pin to start menu works with pinning folders, just not with executable files.

### Steps To Reproduce

1. Open Game Folder
2. Browse to Game exe and right click on it
3. choose pin to start menu option

### Requirements

1. Fix crash that occurs when attempting to pin executable (.exe) files in particular.

### Files Version

3.0.15.0

### Windows Version

10.0.22631.2861

### Log File

[debug.log](https://github.com/files-community/Files/files/13850255/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in https://github.com/files-community/Files/issues/13947. You can check there or click subscribe in the right sidebar for updates.
