### ISSUE TITLE
Bug: Right clicking files causes crash

### ISSUE THREAD

**Issue by Wolfkid200444** [files-community/Files#14361]
### Description

Trying to select multiple files and right clicking on them crashes the app completely
here is a video show it happens

https://github.com/files-community/Files/assets/32025746/8ec1cbd9-8ad4-4430-b434-613a7738b22e

### Steps To Reproduce

1. Select few files
2. Right Click on the files selected
3. Crash

### Requirements

- Not crash when right clicking on the files

### Files Version

3.1.0.0

### Windows Version

10.0.22631.2861

### Log File

[debug.log](https://github.com/files-community/Files/files/13845023/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
Is this only when selecting multiple files?

**Comment by Wolfkid200444** [comment]
it doesn't happen right clicking one file
it does happen when clicking multiple files

**Comment by yaira2** [comment]
What's the minimum number to repro? Also, is it with all file formats or is there a specific type?

**Comment by Wolfkid200444** [comment]
So it seems to not crash when having multiple folders chosen 
but it does crash having any type of files formats

**Comment by yaira2** [comment]
Does it happen with specific file formats?

**Comment by Wolfkid200444** [comment]
no it mostly happens with every single type of format except folders

but selecting multiple folders does not crash 
only different types of files like zip, dlls, pngs, jpegs, torrents, msi, mp4 and etc

selecting a folder and a different type of file format's does not crash
shown down below:

https://github.com/files-community/Files/assets/32025746/14e2bfcd-31c4-4baf-8f76-b30551e414fe

**Comment by MrFrawsty** [comment]
I was not able to reproduce this.

**Comment by yaira2** [comment]
Microsoft just updated WinAppSdk with a fix for the CommandBarFlyout so there is a good chance it fixes this issue.

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by Wolfkid200444** [comment]
Seems to still occuring on the preview version

App Version - 3.1.3.0
Windows Version - 10.0.22631.3007


https://github.com/files-community/Files/assets/32025746/64decee5-176a-444f-ba1a-91c608d07de4

**Comment by yaira2** [comment]
If you right click those items in File Explorer, what's displayed in the list of shell extensions?

**Comment by Wolfkid200444** [comment]
What is displayed the File Explorer is this

![image](https://github.com/files-community/Files/assets/32025746/79efd338-a70f-4f75-b43f-7485b708c037)

**Comment by Josh65-2201** [comment]
Can you click show more options and send a screenshot of that menu

**Comment by Wolfkid200444** [comment]
funny that u now mention this because it seems to be crashing as well on the default explorer when i clock "Show more options" which is weird since it didn't happen before

**Comment by yaira2** [comment]
It's probably one of the shell extensions but it wouldn't hurt to restart Windows to see if that fixes the issue.

**Comment by Wolfkid200444** [comment]
yeah ive already restarted windows and it still persist

**Comment by yaira2** [comment]
At this point I don't think it's related to Files, but you can try looking at your list of installed apps to try to and figure out which shell extension might be causing the issue.

**Comment by yaira2** [comment]
It's hard to know but there might be some third party apps that can display them.

**Comment by Wolfkid200444** [comment]
Ok it seems i found the culprit it was an app called "AirDroid" ive exacttly forgotten why i had this but after uninstalling it the context menu starting working on both Files and File explorer. thanks for the help

**Comment by Josh65-2201** [comment]
Great, thanks for the update.
