### ISSUE TITLE
Bug: Pinning programs to the start menu causes a crash

### ISSUE THREAD

**Issue by Qin-shihuang** [files-community/Files#14365]
### Description

Generally a user can pin folders or programs to the start menu. Folders behave normally, but pinning programs causes a crash.

### Steps To Reproduce

1. Select any .exe file
2. Pin it to the start menu
3. Observe the crash

### Requirements

Files should not crash and the program should be pinned.

### Files Version

3.0.16.0

### Windows Version

10.0

### Log File

[debug.log](https://github.com/files-community/Files/files/13849828/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #13947. You can check there or click subscribe in the right sidebar for updates.
