### ISSUE TITLE
Ability to rotate an image horizontally and vertically

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#1437]

**Comment by jaigak** [comment]
@yair100 Could you assign me on this issue?

**Comment by yaichenbaum** [comment]
This is already implemented with the shell extensions.

**Comment by jaigak** [comment]
@yair100 Ok, but I have an idea for a crop button built-in as well which File Explorer doesn't

**Comment by yaichenbaum** [comment]
How would it work, would it launch the photos app and auto select the crop option?

**Comment by jaigak** [comment]
@yair100 That's right but without opening the entire app itself. Photos app provides a Launch for results URI for cropping which will be done in a model dialog and hitting save will close it and no other options would be shown

**Comment by Jaiganeshkumaran** [comment]
It will not switch to the Photos app instead it will open as a dialog box with LaunchUriForResultsAsync and will provide options only for cropping.

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran That is an amazing idea! Can you please open a proposal for it?

**Comment by Jaiganeshkumaran** [comment]
Done #2099
