### ISSUE TITLE
Files, after starting is loading a very long time, when I'm not in my home network and the network shares are not reachable

### ISSUE THREAD

**Issue by rumplin** [files-community/Files#14370]
### Description

At home in my home network, Files open in a reasonable time.
I have some network shares mounted and they show up.

When I'm not in my home network, and I start Files for the first time, it takes minutes until I can use the app.

### Steps To Reproduce

1. mount network drive to one of the letters (Z:\)
2. leave home network
3. reboot machine
4. start Files app

### Requirements

Should load normally or in less than a minute.

### Files Version

3.0.15.0

### Windows Version

10.0.22621.2861

### Log File

[debug.log](https://github.com/files-community/Files/files/13853363/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Do you mean the home page and sidebar contents take longer to load or the Files app itself. Also can you do a test following the below
1. Open Files on your home network
2. Close Files
3. Disconnect home network
4. Open Files

**Comment by yaira2** [comment]
Are subsequent launches quicker?

**Comment by rumplin** [comment]
What I mean with long loading is, that this screen is there for a long time (~1 minute):
![image](https://github.com/files-community/Files/assets/35449956/4fe6d568-7185-4999-9dde-da6365536144)

After the initial launch, this long loading screen is not there anymore. It's just the first run.

**Comment by rumplin** [comment]
> Thanks for the report, Do you mean the home page and sidebar contents take longer to load or the Files app itself. Also can you do a test following the below
> 
>     1. Open Files on your home network
> 
>     2. Close Files
> 
>     3. Disconnect home network
> 
>     4. Open Files

I tried this and the following happens:

The first start is smooth.
I disconnect from home network.
open Files again
opening is smooth and quick
but now it still shows that my network drives are available, clicking on one of the drives makes the Files app unresponsive for about 30 seconds.
The next thing that happens is that it shows that these drives are still available with text: This folder is empty.
The title bar has the correct icon.

![image](https://github.com/files-community/Files/assets/35449956/740bdd38-a759-4e40-8661-dc7e97ef20ae)

**Comment by yaira2** [comment]
> After the initial launch, this long loading screen is not there anymore. It's just the first run.

It's not expected to take that long but as long as it's working on subsequent launches, I think it's okay.

> but now it still shows that my network drives are available, clicking on one of the drives makes the Files app unresponsive for about 30 seconds.

This sounds like a different issue where the sidebar isn't updating to reflect the drive was disconnected. Would you like to repurpose this bug report to track this issue, or would you prefer opening a new one from scratch?

**Comment by yaira2** [comment]
Sounds good, thanks for all the feedback!
