### ISSUE TITLE
Direct Extraction from Compressed File

### ISSUE THREAD

**Issue by Horizon82** [files-community/Files#14378]
### Description

I am unable to extract a file via drag & drop from within the compressed file. Both from within Files and from WinRar.  Winrar shows a crossed out circle stating it cannot extract but when opening the compressed file from within Files it looks like its ok to extract but doesn't.  Green checkmark shows successful extraction but file isn't there.  There is no relevent info in the log.

### Steps To Reproduce

Attempt to extract a file.

### Requirements

File should extract.

### Files Version

3.1.0.0

### Windows Version

11 Pro 23H2

### Log File

[debug.log](https://github.com/files-community/Files/files/13855334/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, We're tracking this in #13898. You can check there or click subscribe in the right sidebar for updates.
