### ISSUE TITLE
Bug: Files Crash while selecting properties in "Recent files" section in Home tab

### ISSUE THREAD

**Issue by AntijevicS** [files-community/Files#14379]
### Description

Files crash when wanting to view properties of a file in "Recent files" section in Home tab..

### Steps To Reproduce

1. Open Files and navigate to Home tab
2. Right click any file in Recent files section
3. Select "properties" of such file

### Requirements

In order to achieve this crash all you have to do is be on "Home tab" and select any file under "Recent files" section, right click that file and select properties...

### Files Version

3.1.0.0

### Windows Version

10.0.19041.3636

### Log File

[debug.log](https://github.com/files-community/Files/files/13855449/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
This seems to be related to #14283

**Comment by hishitetsu** [comment]
I rather think it is related to #14115.
@0x5bfa fyi

**Comment by yaira2** [comment]
> I rather think it is related to #14115. @0x5bfa fyi

Good catch, thanks for the fix!
