### ISSUE TITLE
Feature: Add more way to make a pane active

### ISSUE THREAD

**Issue by Horizon82** [files-community/Files#14376]
### What feature or improvement do you think would benefit Files?

Add another way to activate a given pane when in dual pane mode.  Due to lack of real estate (no open/black space) on full folders there isn't a place to click to activate a pane without activating a file or folder. Single click may activate a file or folder, right click brings up context menu.  The activated pane's blue scroll bar is very thin and not really an option to activate a pane and the tab at the top doesn't allow swapping between panes.

### Requirements

Feature could be a long hover, middle click, click the active tab or separate the toolbar for each pane that allows for activation.

### Files Version

3.0.15.0

### Windows Version

11 Pro 23H2

**Comment by Josh65-2201** [comment]
Thanks for the feedback, I've added this to the project board.

**Comment by yaira2** [comment]
Thanks for the feedback, you can always click in the space next to the file area. You can also use the `ctrl + shift + left arrow/right arrow` keyboard shortcuts to switch panes.
![image](https://github.com/files-community/Files/assets/39923744/8e029b73-277d-45cd-91db-da582f14b915)
