### ISSUE TITLE
Icons don't update on disconnected network drives

### ISSUE THREAD

**Issue by rumplin** [files-community/Files#14371]
### Description

When disconnecting from a network where we have mapped network drives, the drives appear as online in the left menu (sidebar):

![294775120-740bdd38-a759-4e40-8661-dc7e97ef20ae](https://github.com/files-community/Files/assets/35449956/9309a841-8190-4431-8c82-8729acf5cfe5)

### Steps To Reproduce

1. open Files app
2. map network drives
3. disconnect from network
4. open Files app again

### Requirements

should show network drives as disconnected.

### Files Version

3.0.15.0

### Windows Version

10.0.22621.2861

### Log File

no logs needed for this issue.

**Comment by yaira2** [comment]
Is there any other area where the icon doesn't update, or just the sidebar (we're tracking the sidebar icons in #10367)?

**Comment by rumplin** [comment]
It's just the sidebar.
I read the #10367 description, the only difference is here that the icons stay incorrect even after restart of Files app.

**Comment by Josh65-2201** [comment]
That issue was opened before Files added the stay in background option. Right now you can right click the system tray icon > quit or turn off `Files settings > Advanced > Leave app running in the background when the window is closed`

**Comment by yaira2** [comment]
> It's just the sidebar. I read the #10367 description, the only difference is here that the icons stay incorrect even after restart of Files app.

Thanks for confirming, hopefully we can get that sorted out so that the icons update right away.
