### ISSUE TITLE
Bug: Changing theme crashes Files

### ISSUE THREAD

**Issue by InomedisInc** [files-community/Files#14372]
### Description

When I changed from orange to default twice. it crashes

### Steps To Reproduce

go to setting menu, go to apparence, select clod theme then default and orange then default

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.1.0.0

### Windows Version

1000.26020.1000.0

### Log File

[debug.log](https://github.com/files-community/Files/files/13854848/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you reproduce this every time?

**Comment by yaira2** [comment]
Is this only affecting the theme settings or does it also crash when changing other settings?

**Comment by InomedisInc** [comment]
Hi
Just theme settings
________________________________
De : Yair ***@***.***>
Envoyé : dimanche 7 janvier 2024 16:06
À : files-community/Files ***@***.***>
Cc : InomedisInc ***@***.***>; Author ***@***.***>
Objet : Re: [files-community/Files] Bug: Changing theme crashes Files (Issue #14372)


Is this only affecting the theme settings or does it also crash when changing other settings?

**Comment by InomedisInc** [comment]
No
________________________________
De : Josh65-2201 ***@***.***>
Envoyé : dimanche 7 janvier 2024 15:34
À : files-community/Files ***@***.***>
Cc : InomedisInc ***@***.***>; Author ***@***.***>
Objet : Re: [files-community/Files] Bug when I want to change files theme (Issue #14372)


Thanks for the report, can you reproduce this every time?

**Comment by yaira2** [comment]
Are the themes applied when you restart the app?

**Comment by InomedisInc** [comment]
No, it remains on the default value.

**Comment by yaira2** [comment]
What happens if you edit the settings file manually? I'm curious if the changes apply https://files.community/docs/configuring/custom-themes

**Comment by yaira2** [comment]
@InomedisInc
