### ISSUE TITLE
Feature: Add and remove cloud drives from the sidebar section

### ISSUE THREAD

**Issue by Horizon82** [files-community/Files#14374]
### What feature or improvement do you think would benefit Files?

Have the ability to manually add/remove cloud drives in the side panel.

### Requirements

Add option in the context menu to edit the listing.

### Files Version

3.0.15.0

### Windows Version

11 Pro 23H2

**Comment by Josh65-2201** [comment]
Thanks for the feedback, I've added this to the project board.

**Comment by yaira2** [comment]
Thanks for the feedback, the cloud drives are based on the clients installed on the device. Can you clarify your use case for removing them from the sidebar?

**Comment by Horizon82** [comment]
I originally thought I had removed one-drive so that's why I wanted to remove it from Files. Come to find out I did not in fact remove it until just now.  Upon removing OneDrive and opening Files nothing loads and then about 60 seconds later the quick access loads but nothing else.  Directories do load when clicking on the favorites or on the quick access one it finally loads.  It's been about 5 minutes now and Drives have still not loaded.  I'm about to reboot and will update once that's done.

![image](https://github.com/files-community/Files/assets/155760601/92f21157-90d4-4529-8279-da199b064187)
[debug.log](https://github.com/files-community/Files/files/13881052/debug.log)

**Comment by Horizon82** [comment]
A reboot of windows did in fact restore everything at normal speeds.

**Comment by yaira2** [comment]
@Horizon82 what about OneDrive, is this issue resolved?

**Comment by Horizon82** [comment]
Yes it is.
