### ISSUE TITLE
Feature: Support `Files .` to open current path from cli

### ISSUE THREAD

**Issue by NightWatcher314** [files-community/Files#14381]
### What feature or improvement do you think would benefit Files?

For example, I can use "files.exe ." to open files.app in current path. Just same as "explorer.exe ." .
I don't know is there any cli.

### Requirements

- Post some clis

### Files Version

3.1.0.0

### Windows Version

10.0.22631.2861

**Comment by yaira2** [comment]
Thanks for the question, it doesn't look like `Files .` is supported yet but if you set Files as the default file manager, `explorer .` will open in Files.

**Comment by NightWatcher314** [comment]
I have set `files` as my default file manager and restart my computer. But when i  use `explorer .` or `explorer.exe .` in terminal, it still open win11's file manager.

**Comment by NightWatcher314** [comment]
> I have set `files` as my default file manager and restart my computer. But when i use `explorer .` or `explorer.exe .` in terminal, it still open win11's file manager.

OK, I have found the problem. When I use powershell, it won't work well, but cmd does.
Can you add support to powershell? Thanks.

**Comment by yaira2** [comment]
👍

**Comment by saikotek** [comment]
> > I have set `files` as my default file manager and restart my computer. But when i use `explorer .` or `explorer.exe .` in terminal, it still open win11's file manager.
> 
> OK, I have found the problem. When I use powershell, it won't work well, but cmd does. Can you add support to powershell? Thanks.

I tested `Files .` both in Powershell Core and Windows Powershell and it works as expected.
Ensure that you have path to Files application in PATH environment variable:
`$env:PATH -split ';' | Where-Object { $_ -like '*WindowsApps*' }`

**Comment by saikotek** [comment]
@yaira2 

I tried to invoke `Files` from either Powershell or cmd and I noticed that the method `Files.App.OnActivatedAsync()` is called with the `ILaunchActivatedEventArgs` type instead of the `ICommandLineActivatedEventArgs` type and the latter is the one that you'd expect and that contains current directory path. 
According to this: https://learn.microsoft.com/en-us/uwp/api/windows.applicationmodel.activation.commandlineactivatedeventargs?view=winrt-22621 application should define AppExecutionAlias which is already defined in Package manifest.

I'm not sure what could be causing it.

**Comment by hishitetsu** [comment]
It is difficult to fix this because it doesn't seem to be possible to get the current directory on the command line without an update to WinUI.
See #10575

**Comment by 0x5bfa** [comment]
- Create a .NET console project `Files.App.CLI` or `Files.App.Console`
- Register it as an alias `files.exe` of Files.App
```xml
<uap3:Extension Category="windows.appExecutionAlias" Executable="files-cli.exe" EntryPoint="Windows.FullTrustApplication">
    <uap3:AppExecutionAlias>
        <desktop:ExecutionAlias Alias="files.exe" />
    </uap3:AppExecutionAlias>
</uap3:Extension>
```
- Create and register some COM interfaces for Files to be able to receive a struct data.

**Comment by 0x5bfa** [comment]
A .NET console project `Files.App.CLI` or `Files.App.Console` and register it as an alias `files.exe` of Files.App
```xml
<uap3:Extension
    Category="windows.appExecutionAlias"
    Executable="files-cli.exe"
    EntryPoint="Windows.FullTrustApplication">
    <uap3:AppExecutionAlias>
        <desktop:ExecutionAlias Alias="files.exe" />
    </uap3:AppExecutionAlias>
</uap3:Extension>
```

Sample usage
```shell
C:\> files --help

Copyright (c) 2024 Files Community
Licensed under the MIT License.

files [[<drive>:]<path>] [-s|--select] [-f|--folder] [-v|--version] [-h|--help]

  -h, --help                Display usage of this CLI.
  -s, --select              Select one or more file(s) and folder(s) on folder view.
  -f, --folder              Go to a folder specified.
  -v, --version             Display current version of this CLI.

C:\> files --version

Copyright (c) 2024 Files Community
Licensed under the MIT License.

Files version: 3.5.25

C:\> files .

Launching Files on current folder...

C:\>
```

<details>
<summary>Semi-related matters</summary>
<p>

With this introduction, we'll have a strong power for FileOpenDialog and FileSaveDialog implementations.
Current technical issue with those overridden dialogs is where the project (Files.App.OpenDialog and .SaveDialog) cannot pass information of the dialog (dialog caller can modify footer content of the dialog, adding a button for example) to Files app via command-line (truly difficult because passing as string would require serialization and deserialization. If we introduced our own COM interfaces as IPC in Files app this issue could be fixed.

```xml
<com:Extension Category="windows.comServer">
    <com:ComServer>
        <com:ExeServer Executable="$targetnametoken$.exe" DisplayName="Files">
            <com:Class Id ="4B115281-32F0-11cf-AC85-444553540000" DisplayName="..." ProgId="Files.Commandline.1" VersionIndependentProgId="Files.Commandline">
            </com:Class>
        </com:ExeServer>
        <!– ProgId –>
        <com:ProgId Id="Files.Commandline" CurrentVersion="Files.Commandline.1" />
        <com:ProgId Id="Files.Commandline.1" Clsid="4B115281-32F0-11cf-AC85-444553540000" />
    </com:ComServer>
</com:Extension>
```

```xml
<com:Extension Category="windows.comInterface">
    <com:ComInterface>
    <!– Interfaces –>
    <!– IID_FilesCommandLineReciever –>
    <com:Interface Id="0BDD0E81-0DD7-11cf-BBA8-444553540000" UseUniversalMarshaler="true">
        <com:TypeLib Id="4B115284-32F0-11cf-AC85-444553540000" VersionNumber="1.0" />
    </com:Interface>
    <!– TypeLib –>
    <com:TypeLib Id="4B115284-32F0-11cf-AC85-444553540000">
        <com:Version DisplayName = "..." VersionNumber="1.0" LocaleId="0" LibraryFlag="0">
            <com:Win32Path Path="..." />
        </com:Version>
    </com:TypeLib>
</com:Extension>
```

```cs
[ComImport(...)]
public interface FilesFileOpenDialogReciever
{
    void Advise(IFileDialogClosedSink *pfdcs);

    void Launch(FileDialogInformation *pfdi);
}
```

```cs
[ComImport(...)]
public interface IFileDialogClosedSink
{
    void PostSelected(string path);
}
```

</p></details>

**Comment by 0x5bfa** [comment]
@yaira2 what do you think?

**Comment by yaira2** [comment]
Is this intended as a workaround, or does it have other advantages?

**Comment by 0x5bfa** [comment]
With an issue with WinUI, WinUI packaged application cannot output string to console using System.Console.Write or WriteLine. But this is actual .NET console application so you can output help message and anything that.

**Comment by yaira2** [comment]
I'd prefer for this to be resolved via the framework but it's good to have this option as a backup.

**Comment by Josh65-2201** [comment]
This will be available in the next update.
