### ISSUE TITLE
Panel management

### ISSUE THREAD

**Issue by sergodesit** [files-community/Files#14383]
### What feature or improvement do you think would benefit Files?

Good afternoon, when using two panels, for the convenience of moving files, there is a problem with switching between panels when folders are expanded. It would be more convenient to have separate panel tabs in the control panel, as in Chrome, for example.
![Снимок экрана 2024-01-08 142225](https://github.com/files-community/Files/assets/155973070/acf7fdc9-c30b-49ec-8a1d-0215dd9bd4d8)

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.1.0.0

### Windows Version

10.0.19045.3803

### Comments

These improvements will improve the user experience of the convenient explorer.

**Comment by yaira2** [comment]
> there is a problem with switching between panels when folders are expanded. 

Thanks for the feedback, can you clarify what you mean by switching panels?

> It would be more convenient to have separate panel tabs in the control panel, as in Chrome, for example.

Can you also clarify what you mean by panel tabs?

**Comment by sergodesit** [comment]
![Знімок екрана 2024-01-08 175738](https://github.com/files-community/Files/assets/155973070/86ddcc17-6f1f-4d52-9f25-6faaef2a0014)
![Знімок екрана 2024-01-08 180437](https://github.com/files-community/Files/assets/155973070/c06061d8-77ce-4950-a11d-ffd806651926)
Active tabs like in chrome
![Знімок екрана 2024-01-08 181229](https://github.com/files-community/Files/assets/155973070/26548bfa-2b9d-4c08-918e-9af29f5379e4)

**Comment by yaira2** [comment]
> When working in two-window mode with folders maximized, there is no empty space to activate the window with a mouse click; to switch between panels you need empty space and this is not always convenient.

There is empty space to the left of the file area, can you see if that works?

**Comment by sergodesit** [comment]
When working with folders there is no free space, you have to click on folders to switch the panel.
![Знімок екрана 2024-01-08 182002](https://github.com/files-community/Files/assets/155973070/239bc973-ebd4-482e-8c08-9d51be4b9fc2)

**Comment by sergodesit** [comment]
When working with folders there is no free space, you have to click on folders to switch the panel.[cid:a968f1a7-989f-4bf5-a969-90842f0d7428]
________________________________
Від: Yair ***@***.***>
Надіслано: 8 січня 2024 р. 18:17
Кому: files-community/Files ***@***.***>
Копія: sergodesit ***@***.***>; State change ***@***.***>
Тема: Re: [files-community/Files] Panel management (Issue #14383)


When working in two-window mode with folders maximized, there is no empty space to activate the window with a mouse click; to switch between panels you need empty space and this is not always convenient.

There is empty space to the left of the file area, can you see if that works?

**Comment by yaira2** [comment]
Please see the screenshot here https://github.com/files-community/Files/issues/14376#issuecomment-1880242871

**Comment by sergodesit** [comment]
thanks for answers

**Comment by sergodesit** [comment]
As an option, but it’s not always convenient to use a small space.[cid:5d047220-4775-4867-a9ba-c8798afde07f]
________________________________
Від: Yair ***@***.***>
Надіслано: 8 січня 2024 р. 18:30
Кому: files-community/Files ***@***.***>
Копія: sergodesit ***@***.***>; State change ***@***.***>
Тема: Re: [files-community/Files] Panel management (Issue #14383)


Please see the screenshot here #14376 (comment)<https://github.com/files-community/Files/issues/14376#issuecomment-1880242871>
