### ISSUE TITLE
Bug: Right click menu mouse pointer error

### ISSUE THREAD

**Issue by daishanrenL** [files-community/Files#14380]
### Description

When clicking on the right-click menu, the pointer will show a scaled pointer. Moving the mouse once will restore the default mouse pointer

There is one more small question When starting the computer, the software does not display on the screen and runs in the background. it will display on the screen, which is a bit uncomfortable. If I don't turn it on, it will start up slowly every time I turn it on for the first time

### Steps To Reproduce

Right click

### Requirements

repair

### Files Version

3.1.0.0

### Windows Version

10.0.22631.2861

### Log File

[debug.log](https://github.com/files-community/Files/files/13855597/debug.log)

**Comment by yaira2** [comment]
@hishitetsu fyi

**Comment by yaira2** [comment]
@daishanrenL can you upload a screenshot/screen recording showing what you mean?

**Comment by daishanrenL** [comment]
> @daishanrenL can you upload a screenshot/screen recording showing what you mean?

![$RSNIJEB](https://github.com/files-community/Files/assets/112452799/f3ac3786-75a3-430f-97a2-46eedf5c38e9)
Forgot to upload, sorry

**Comment by daishanrenL** [comment]
![Uploading 2024-01-09_08-41-11.gif…]()

**Comment by daishanrenL** [comment]
![Sometimes normal, sometimes incorrect](https://github.com/files-community/Files/assets/112452799/5469bba8-33bb-446b-89c2-b5bea7db33e6)

**Comment by daishanrenL** [comment]
![Uploading Sometimes normal, sometimes incorrect.gif…]()

**Comment by yaira2** [comment]
Are you by any chance using a custom cursor? It might have something to do with that as I haven't been able to repro this behavior and the cursor doesn't look familiar.

**Comment by yaira2** [comment]
@daishanrenL
