### ISSUE TITLE
App can't be moved to another drive via Windows Settings  > Apps > Move 

### ISSUE THREAD

**Issue by foxnoodles** [files-community/Files#14382]
### Description

Pretty much the title. If you try to move Files to another location using native 'move' option if will start the process and throw an error right when its about to finish. The error code is: 80073cf6. Other apps will 'move' just fine so has to be Files specific.

### Steps To Reproduce

Open Windows Settings
Go to Apps
Find Files app in the list and click on '...' button. 
Select 'Move'  and choose another Drive letter. 

### Requirements

Process should finish without any error and the app should be moved to the new location.

### Files Version

3.0.15

### Windows Version

22621.2861

### Log File

There is not log file for this, the error is package related not App related.

**Comment by yaira2** [comment]
Thanks for the feedback, Files doesn't have support for being moved to other drives. We disabled the option for the Store version to prevent confusion but as far as I'm aware, there isn't a way to do this for the sideload version.
