### ISSUE TITLE
Feature: Support for hiding more options from the context menu

### ISSUE THREAD

**Issue by tommkotzu** [files-community/Files#14389]
### What feature or improvement do you think would benefit Files?

Would be awesome to be able to fintune the settings for the context menue.
features like: create shortcut, compress, pinm etc are not needed for everyone. 

### Requirements

- Add option to hide "Create shortcut"
- Add option to hide pin/unpin
- Add option to hide "Copy path"

### Files Version

3.0.15.0

### Windows Version

11

**Comment by yaira2** [comment]
Thanks for the feedback

**Comment by yaira2** [comment]
Additional options will be available in the next release
