### ISSUE TITLE
Ability to cast media files to device

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#1438]
This can be achieved using the APIs in [Windows.Media.Casting](https://docs.microsoft.com/en-us/uwp/api/windows.media.casting?view=winrt-19041) namespace. Check this out: https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/media-casting.

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran This issue should be resolved in v0.21.
