### ISSUE TITLE
Show all Subfolders in Root Folder Layout

### ISSUE THREAD

**Issue by Raynbda** [files-community/Files#14393]
### What feature or improvement do you think would benefit Files?

I want to be able to look at all files inside a folder along with its subfolders in one view but separated by the subfolder's names. 
It would look like the group by view but instead it will be he subfolder's names
![explorer_8xQVka0Xct](https://github.com/files-community/Files/assets/116586370/d920c700-2609-45ab-8c17-8d049af9c607)

### Requirements

- This proposal will accomplish quicker multi folder navigation

### Files Version

3.1

### Windows Version

22H2

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #14319. You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
> I want to be able to look at all files inside a folder along with its subfolders in one view but separated by the subfolder's names.

You can do this with Libraries and grouping the items by location.
