### ISSUE TITLE
Feature: Filter current directory when typing into search box

### ISSUE THREAD

**Issue by cbadoud** [files-community/Files#14391]
### What feature or improvement do you think would benefit Files?

This feature is an absolute must-have for me: imagine a list of thousands of files, typing just "test" in the filter zone will display all the files or folders containing "test" in their name, it soooo useful, I'm using this search zone dozen times a day!

I'm still using [QTTabBar](http://qttabbar.wikidot.com/), but it's no more maintained, and bugs appear in Win11 23H2 after using ViVeTool for disabling the default Windows tabs.

### Requirements

1. Typing query into the search box should filter the items in the current directory
2. The dropdown menu should keep the existing behavior and continue to display suggestions
3. Pressing enter should start a full search
4. Removing the focus from the search box currently resets the search text, this behavior should be changed so that users can keep the current filter without keeping the focus on the search box.

### Files Version

v3.1

### Windows Version

10.0.22631.2861

### Comments

![file-filter](https://github.com/files-community/Files/assets/1422896/3d56b3bb-119f-4d35-8f97-9e458cbee048)

**Comment by yaira2** [comment]
Thanks for the feedback, I think this is a good feature to have and can make it easier to find files without a full search.

**Comment by yaira2** [comment]
I'd like to invite the community to share designs on how this can be implemented either in addition or as part of the existing search feature.

**Comment by DavidGP** [comment]
Thank you, looking forward to it!

**Comment by DavidGP** [comment]
Thanks yaira2 for linking to the parallel feature request.
I agree with cbadoud that a Live Filter Box is extremely useful. I've been using this feature hundreds of times a day in Dopus for decades. 
Just for convenience, I'm adding the animated screenshot from over there, showing an example of how this can look in its simplest form (click on the triangle at the top right of the screenshot to run the animation)
![FilterAsYouType](https://github.com/files-community/Files/assets/1527716/15d0d9a3-13c2-4866-a341-2946d69b029d)

**Comment by yaira2** [comment]
Some points to think about
1. Where to display the text box, it can be optional, but it needs to be integrated into the UI without looking out of place.
2. Is there a way that this can be added as part of the existing search feature? If so, how would users switch between the two modes?
3. Is the option needed in all layouts? If it's primarily used for the details layout, perhaps it can be an option when clicking columns headers. This would solve the UX challenges and would also allow filtering based on any column as opposed to just the item name.

**Comment by DavidGP** [comment]
The box doesn't take up much space and I think it should always be visible, just in the toolbar.
Sorry, I'm just starting to use Files, and it seems now that the search box top right almost does the same thing that is described here as a feature request? Except it's not filtering live "as you type".
Anyway, I use the Dopus filter box non-stop from morning to night in all list view modes including thumbnails. I almost never use normal file search features, in any file manager (instead I use Voidtools Everything). So in my view, the live filter feature could simply be integrated into the existing search box, or the search box could be replaced by the live filter feature.

**Comment by yaira2** [comment]
> Sorry, I'm just starting to use Files, and it seems now that the search box top right almost does the same thing that is described here as a feature request? Except it's not filtering live "as you type".

The search feature is a little heavier and not as predictable as simply filtering file names.

**Comment by RickeyWard** [comment]
Bringing the discussion to this issue (from the one I started 2 years ago closed above), 

Thoughts on the UI

Dolphin (KDE's file manager)  puts filter at the bottom, while search is at the top. Which is a little strange but not foreign.
![image](https://github.com/files-community/Files/assets/342468/f8c4abf9-442e-4ff2-9151-7d66ee5e9fd8)

Nautilus (Gnome's file manager) used to make the filter float below the window when you start typing but now they got rid of filter and changed typing to start a full search but allow for changing search depth to "never" search subfolders.

I'd personally be happy with either an icon drop down to change search to filter, or even a filter characters like if a search starts with a colon : or something just filter. or a keyboard shortcut that jumps to search in filter mode

My first thought is something like this:
![example_filter](https://github.com/files-community/Files/assets/342468/0cc1cc94-893a-402b-af73-06214e3e632c)

**Comment by yaira2** [comment]
What about filtering when typing into "search" and doing a full search when pressing enter or clicking the search icon?

**Comment by RickeyWard** [comment]
That sounds great! I really like that idea. I think the current mechanism of a dropdown search appearing while typing is very strange and would welcome seeing that replaced with filtering in the current window. Could show a box under it that says "filtering, press enter to search" for user clarity if needed

**Comment by yaira2** [comment]
Aside from users who like seeing the suggestions in the dropdown, are there any reasons that this behavior should be an option?

**Comment by RickeyWard** [comment]
There's always going to be those "I liked it better before" users. Some people miss windows xp 🤷If its not a lot of work to make it possible to toggle between current behavior and filter behavior certainly having an option will make more users happy

**Comment by cbadoud** [comment]
I see a lot of good suggestion here! My first idea was to keep everything simple, that's why I would prefer not to click twice for using the filter. Clicking twice for getting something simple is the new Microsoft paradigm, alas…

Something else now: in QTTabBar, it was possible to use a wildcard, e.g. typing "xy*z" would match every filenames containing "xy" followed by "z". It's so useful if you have many images beginning with "fruit", and you want only the "red" ones => search would be "fruit*red".

**Comment by yaira2** [comment]
> Something else now: in QTTabBar, it was possible to use a wildcard, e.g. typing "xy*z" would match every filenames containing "xy" followed by "z". It's so useful if you have many images beginning with "fruit", and you want only see the "red" ones => search would be "fruit*red".

This probably won't happen in the first implementation but it'll be a good feature to add once we get the basics figured out.

**Comment by RickeyWard** [comment]
Personally I'd prefer something closer to standard fuzzy. Like vscode does for filters. It's essentially requiring the characters all in the order present but with any number of characters between or before / after them.

Filter xyz is equivalent to regex .*x.*y.*z.*
