### ISSUE TITLE
Crash when clicking the 'Update Files' button

### ISSUE THREAD

**Issue by jeffwlawson** [files-community/Files#14390]
### Description

Today, when I opened the Files app, I saw the 'Update Files' button was visible.  When I clicked it the app crashed.

### Steps To Reproduce

1. Open Files app
2. Click 'Update Files' button

### Requirements

Fix crash that occurs when clicking the 'Update Files' button.

### Files Version

3.1.0.0

### Windows Version

Windows 11 Pro 22H2

### Log File

[debug.log](https://github.com/files-community/Files/files/13864265/debug.log)

**Comment by yaira2** [comment]
Can you try again now?
