### ISSUE TITLE
Custom Folder Templates

### ISSUE THREAD

**Issue by Raynbda** [files-community/Files#14392]
### What feature or improvement do you think would benefit Files?

There are 5 default folder templates: generic items, Music, Videos, Pictures and documents. They change the folder view based on the content of the folder.
These are not enough, i would like to have the ability to add more templates and customize them for Sfx, Project Files, Assets, Textures...
I would also like it if Files can recognize if the details view, preview pane, Item Checkboxes, Hidden Items ,Compact view... are on or off when making a new template and automatically turning on or off when that template is selected 

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z
-Add the ability to create new templates 
-Make the templates remember settings like preview pane

### Files Version

3.1

### Windows Version

22H2

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #5564. You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
This is probably a little more advanced than what's being tracked in #5564 but we might as well track them together. Can you add a comment to #5564?
