### ISSUE TITLE
How can I retrieve the directory of the current page through the API?

### ISSUE THREAD

**Issue by NightmareZero** [files-community/Files#14399]
### What feature or improvement do you think would benefit Files?

I have a software similar to Power Automate, through which I can perform some automated tasks. One of its features is to retrieve the current directory path. It works well in "explorer.exe", but it cannot be retrieved in "Files" (this is a compatibility issue). I want to know if this API has been implemented and if so, how to call it.
If there is no time or it is not possible to implement this function in a short period of time, can a button be added to open "explorer.exe" in the current path?

### Requirements

Implement an api to retrieve the current open directory path
or
add a button to open explorer.exe in the current directory.

(By the way, the API to retrieve selected files is available in the 'files' section.)

### Files Version

3.1.0.0

### Windows Version

10.0.22631.2861

**Comment by yaira2** [comment]
Thanks for the feedback, this isn't supported yet but it's being planned in #11765. In the meantime, you can automate focusing the path bar `ctrl` + `l`, select the text via `ctrl` + `a`, and then copy with `ctrl` + `c`.

**Comment by yaira2** [comment]
@NightmareZero an update has been posted in #11765 regarding this request.
