### ISSUE TITLE
Bug: Some folders do not show complete list of files on a local drive

### ISSUE THREAD

**Issue by gintasc** [files-community/Files#14397]
### Description

On Win 11 just installed "Files 3.1.0.0" and browsed thru folders containing pics in .jpg and .cr2 format on internal Seagate SATA 8TB HDD. Most folders open just fine, but not all. When trying to open a folder containing 54 .cr2 files the message "This folder is empty" appears, while checking Properties of a given folder the correct value of 1.54GB is displayed. And this is the case with multiple folders (but not all) containing .jpg and .cr2 files. Furthermore yet another folder opens but only displays 5 .jpeg files of total  17 .jpg and 15 .cr2 files. Again, checking Properties of the given folder it correctly shows 530MB. All files described above are not encrypted, hidden or password protected and easily accessable by generic Win 11 File explorer, OneCommander and Xplorer 2. or any Picture viewing apps.

### Steps To Reproduce

1. Open "Files" app.
2. Navigate to D:  (8TB HDD)
3. Navigate to a specific folder containing multiple .jpg and .cr2 (Canon RAW) files
4. Double click to open that folder to view files

### Requirements

Expect to correctly display .jpeg and .cr2 files residing in that folder but not display "This folder is empty" message or show incomplete list of files there.
PS: it would be devastating to delete precious photos assuming that folder is empty while it contains photos.

### Files Version

3.1.1.0

### Windows Version

Windows 11 32H2

### Log File

[debug.log](https://github.com/files-community/Files/files/13868251/debug.log)

**Comment by PetEile** [comment]
Same with me. Folder should contain 262 elements of same filetype. Only 260 are displayed.

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
