### ISSUE TITLE
sorry if this is not the place for basic questions

### ISSUE THREAD

**Issue by musicdream** [files-community/Files#14394]
### What feature or improvement do you think would benefit Files?

Can I compare similar folders?

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.1.0.0

### Windows Version

10.0.22631.2861

**Comment by yaira2** [comment]
Comparing folders isn't currently supported but you try to use the dual pane feature and see if it fits your needs.

**Comment by musicdream** [comment]
Thank you. That feature would be very useful.
