### ISSUE TITLE
Feature Request: Adjustable Spacing in Details View

### ISSUE THREAD

**Issue by DavidGP** [files-community/Files#14402]
### What feature or improvement do you think would benefit Files?

Hello Files Team,

I've noticed the spacing between entries in the details view is larger than in traditional file managers like Windows Explorer.

An option to adjust the spacing in details view would be great. This feature would allow for a more compact layout, improving visibility and efficiency, especially when working with large directories.

Thanks for considering this request!

### Requirements

**UI Option for Spacing Adjustment**: Implement a user interface control within the settings to adjust the spacing between entries in the details view.

**Spacing Scale Range**: Define a range for spacing adjustment, allowing users to choose from minimal to maximal spacing.

**Preview Functionality**: Include a live preview feature that demonstrates spacing changes in real-time as the user adjusts the settings.

**User Preference Memory**: Ensure the application remembers and applies the user's spacing preference across sessions.

### Files Version

3.1.1.0

### Windows Version

10.0.19045.3803

**Comment by yaira2** [comment]
Thank you for your feedback. We're planning to add more options to adjust the size in #10492 but in the meantime, you can already reduce the item height by turning on the option for "compact spacing".
![image](https://github.com/files-community/Files/assets/39923744/83e157a9-957b-46e9-ad20-282cee3a5c6c)

**Comment by yaira2** [comment]
Support for additional sizes is actively being worked on, you can track the latest progress in #10492.
