### ISSUE TITLE
files

### ISSUE THREAD

**Issue by deepskota** [files-community/Files#14406]
### What feature or improvement do you think would benefit Files?

please provide option to show folder  or drives properties in a separate window at the bottom of explorer so that when we want to know how much space is used and space available to copy more files ( especially when a external hdd or pen drive is connected )

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.1.1.0

### Windows Version

10.0.23612.1000

**Comment by yaira2** [comment]
Thank you for the feedback, can you check if this is covered by #12597?
