### ISSUE TITLE
Support environment variables in shortcuts

### ISSUE THREAD

**Issue by clackwell** [files-community/Files#14403]
### What feature or improvement do you think would benefit Files?

In Windows shortcuts I can use, for example, "%USERPROFILE%" in the shortcut fields "Target:" and "Start in:"

![image](https://github.com/files-community/Files/assets/6651253/ca228625-72c0-4b83-a6d2-83cf87b655a9)

(The shortcut editor goes above and beyond, and even offers completion from the path specified. This feels like it goes too far. I am an advanced user by editing the shortcut and using environment variables in it, I can copy and paste a path just fine. No need to waste time with corner-case hyper-convenience like this.)

But when executing such a shortcut via double click in Files one can see that the process gets launched with the environment specification as is, instead of evaluated. From Process Explorer:

![image](https://github.com/files-community/Files/assets/6651253/471f988b-9a2c-4061-a7ba-0e0e418f67e2)

The top entry is when launched from File Explorer.

The bottom entry is when launched from Files. Note the command line, which for the bottom entry still contains the environment variable placeholder.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.1.1

### Windows Version

Windows 11, 23H2

### Comments

Unrelated, but the "Windows Version" entry in the Feature Request form mentions "[...] access it from Settings -> About -> Copy -> Windows version", but in Windows 11 it is "[...] access it from Settings -> System -> About -> Copy -> Windows version" instead.

And even then there is no such succinct information as implied by the microcopy in the field:

![image](https://github.com/files-community/Files/assets/6651253/38438d9d-76ae-4c2e-9508-c985a91b8d69)

Instead I see this:

![image](https://github.com/files-community/Files/assets/6651253/3d3bda90-69a1-4517-b41a-c87d60745599)

What to provide in such a case?

**Comment by yaira2** [comment]
Thanks for the report, this definitely looks like a bug. Can you open a separate issue using the bug template? Worst case we can just edit this issue but a separate issue would be best.

> And even then there is no such succinct information as implied by the microcopy in the field:

Settings refers to the settings in Files
