### ISSUE TITLE
Pin to start behaviour inconsistent with file explorer & crashes pinned application

### ISSUE THREAD

**Issue by Yentis** [files-community/Files#14401]
### Description

When pinning to start using files, the icon will not match the exe that I pinned. It will instead show a generic folder icon.
The name also includes ".exe" while when pinning through regular file explorer it doesn't include this.
Additionally, when starting from the start icon it will crash some programs. I encountered it with games (Kingdoms of Amalur & Dust: An Elysian Tail).
Dust showed a DirectoryNotFound error:
![DustAET_bnRiFSwWxj](https://github.com/files-community/Files/assets/17981128/bed3fd74-6897-45e1-b58e-37572f061621)

### Steps To Reproduce

1. Pin a game exe to the start menu using files
2. See that icon & name doesn't match file explorer functionality
3. Click pinned icon
4. Crashes

### Requirements

- Icon should match the exe
- Name should not include ".exe"
- Application should not crash upon starting

### Files Version

3.1.1.0

### Windows Version

21H2 19044.3693

### Log File

[debug.log](https://github.com/files-community/Files/files/13874107/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, we're currently tracking this issue in #12191.

**Comment by Yentis** [comment]
The linked issue seems to only be for the icon, what about the other issues I mentioned?

**Comment by yaira2** [comment]
Just noticed that, can you open a separate bug report for the crash?

**Comment by Yentis** [comment]
https://github.com/files-community/Files/issues/14405
