### ISSUE TITLE
Flat View and Live File Filter Box

### ISSUE THREAD

**Issue by DavidGP** [files-community/Files#14409]
### What feature or improvement do you think would benefit Files?

Hello Files Team,

I'm proposing two features that would greatly enhance the utility of the Files file manager: **Flat View and a Live Filter field**.

**Flat View**: This feature would allow users to display all files from a selected folder and its subfolders in a single, flattened list. Having used this feature in Dopus for decades, I am convinced that it is incredibly useful for navigating and finding files in complex, nested directory structures.

**Live Filter Field**: Coupled with the Flat View feature, a Live Filter field enables users to dynamically filter the displayed files based on partial filename matches or specific file extensions. This functionality is essential for quickly locating files among hundreds or thousands of files in large directories, particularly while in Flat View.

These two features would significantly boost the efficiency of file searching and management, especially for users dealing with extensive folder hierarchies.

Below is a screenshot from Microsoft Access showing the principle of a Live Filter Box.

Thank you for considering these additions to Files.

![FilterAsYouType](https://github.com/files-community/Files/assets/1527716/19f6ba7e-4882-42ea-9bcc-5dfda5630ed9)

### Requirements

**Develop Flat View**: Implement a feature for displaying all files in a folder and its subfolders in a flat list.
**Integrate Live Filter**: Add a dynamic filter field for file name or extension-based filtering.
**UI Update**: Modify the user interface to incorporate Flat View and Live Filter.
**Optimize Performance**: Ensure efficient handling of large directories.

### Files Version

3.1.1.0

### Windows Version

10.0.19045.3803

**Comment by yaira2** [comment]
Thank you for the feedback, we're planning support for a filter feature in #14391 and a flat view in #14319 (you can already do something similar with libraries).

**Comment by DavidGP** [comment]
Thank you, looking forward to it

**Comment by yaira2** [comment]
If you have any design ideas on how this can be implemented either in addition or as part of the existing search feature, please us know in #14391.
