### ISSUE TITLE
Copy/Paste out of zip file doesn't work

### ISSUE THREAD

**Issue by Bobwattseface** [files-community/Files#14407]
### Description

See steps below. This works in Windows Explorer but not Files

### Steps To Reproduce

1. Click on zip file (e.g. containing a number of jpg files). Files correctly shows content of zip file with the option to 'Extract'
2. Do NOT extract, but select some or all of the files and select 'Copy'
3. Open a different tab to another folder location and select 'Paste' - NOTHING happens  

### Requirements

As above

### Files Version

3.1.1.0

### Windows Version

Windows 11 23H2

### Log File

.

**Comment by yaira2** [comment]
Thank you for the report, we're currently tracking this issue in #14216.
