### ISSUE TITLE
Rename Favorite/Quick Access Shortcuts

### ISSUE THREAD

**Issue by sdlaw-sdelorme** [files-community/Files#14404]
### What feature or improvement do you think would benefit Files?

I would like the ability to rename Folders and Destinations saved in Favorites/Quick Access without changing the name of the actual destination folder. Windows 7 allowed users to do this in the default Windows 7 File Explorer. With the introduction of Windows 10, Microsoft removed this ability. (It may have been removed in Window 8, but never used Windows 8 so I'm not 100% sure when the feature was removed)

I have several shared network locations that I keep pinned in Favorites that I can not change the name of without renaming the actual folder they are linked to. Back in the Windows 7 days I just renamed my pin in Quick Access to something that made more sense for my productivity. This had the advantage of not affecting the real folder name for other users on the network. It would be great if Files could bring back this older Windows File Explorer feature.

### Requirements

- Treat pinned Favorites as Shortcuts allowing the end user to change the name of the pinned item without changing the name of the destination

### Files Version

3.1.1.0

### Windows Version

10.0.19045.3803

**Comment by yaira2** [comment]
Thanks for the feedback, I hear the use case and perhaps it's a bit of clunky workaround, but you can technically do this by creating and pinning a library to the favorites section.

**Comment by yaira2** [comment]
@sdlaw-sdelorme did you have a chance to try this workaround?
