### ISSUE TITLE
Native Linux File System Support

### ISSUE THREAD

**Issue by karthikvijay5227** [files-community/Files#14400]
### What feature or improvement do you think would benefit Files?

There are lots of developers who also use linux as dual boot with windows But after giving partition for linux,that space seems wasted in windows as it can't be used there.But linux can use both.So if windows explorer can use both Windows and Linux drives,it will be good.

### Requirements

- Add Linux drives in Drives section
- Add support for ext3,ext4,brtfs drives

### Files Version

3.1.1

### Windows Version

10.0.22635.2915

**Comment by yaira2** [comment]
Thank you for your feedback, we're currently tracking this feature in #400.

**Comment by beedell-roke** [comment]
@yair100, there's a "Close as duplicate" option nowadays.

**Comment by Josh65-2201** [comment]
This was closed before that existed
