### ISSUE TITLE
Bug: Pin to start crashes pinned application

### ISSUE THREAD

**Issue by Yentis** [files-community/Files#14405]
### Description

When starting the pinned application it will crash some programs. I encountered it with games (Kingdoms of Amalur & Dust: An Elysian Tail).
Dust showed a DirectoryNotFound error:
![DustAET_bnRiFSwWxj](https://github.com/files-community/Files/assets/17981128/8dec8890-8e03-485b-8d73-e0dc9d167255)

### Steps To Reproduce

1. Pin a game exe to the start menu using files
2. Click pinned icon
3. Crashes

### Requirements

Application should not crash upon starting

### Files Version

3.1.1.0

### Windows Version

21H2 19044.3693

### Log File

[debug.log](https://github.com/files-community/Files/files/13876011/debug.log)

**Comment by yaira2** [comment]
Thanks for the report

**Comment by yaira2** [comment]
A fix will be included in the next release
