### ISSUE TITLE
Feature: Tagging & tag search improvements (add/search multiple tags, auto-sort tags, nested tags)

### ISSUE THREAD

**Issue by arrhat** [files-community/Files#14411]
### What feature or improvement do you think would benefit Files?

Thank you for this useful program! I have a few suggestions regarding the tagging functionality in Files:

1. Add an option to keep the "Edit tags" sub-menu open after selecting a tag, so that multiple tags can be added from the context menu with fewer input actions. Currently the "Edit tags" sub-menu closes after selecting a tag; if I want to add multiple tags to a file, I have to hover over "Edit tags" to reopen the sub-menu for each tag I want to add. If it stayed open, the user could just check all desired tags off the list, then click elsewhere to close the context menu.
2. Add an option to auto-sort tags in the context menu, sidebar, and tag widget alphabetically or by number of tagged files. A "sort by" button in the tags options dialogue would be a nice way to do this. That way the user could quickly auto-sort their tag list, but still manually edit the order of tags if they wanted to make changes from there.
3. In the context menu, sort tags starting from the "Edit tags" menu item, rather than always sorting top-to-bottom. This way, if the user is sorting tags by most-used, the most commonly used tags will be closest to the mouse cursor, regardless of whether the submenu is rendered above or below the "edit tags" menu item.
4. Display tags in the Details pane alphabetically. Currently tags display in the order that they were added to the file; having a consistent display order for tags would make it easier to parse at a glance what tags are associated with a file. (For example, if I have one file that I tagged "Photos" and "Work" -- in that order -- and another file that I tagged "Work" and then "Photos", the Details pane will currently display the first file's tags as "Photos", "Work" and the second file's tags as "Work", "Photos". It would be cleaner if tags were displayed in a consistent order, regardless of the order they were applied.)
~~5. Add an option to create nested tags, and have nested tags automatically apply parent tags (as suggested in #12738).~~
~~6. Allow the user to search for multiple tags or exclude tags from a search. For example, a user might search "tag:Work tag:Photos" to find all files with both the Work and Photos tags, or "tag:Work -tag:Photos" to find all files tagged Work that are _not_ tagged with Photos.~~

### Requirements

- Proposals 1, 2, 3, and 5 improve the user experience when adding tags to files.
- Proposals 2, 3, and 4 add more consistency and user control over how tags are displayed, making them easier to read and use.
- Proposals 5 and 6 improve the functionality of tags, making it easier to navigate files using tags.

### Files Version

3.1.1.0

### Windows Version

10.0.19045.3803

### Comments

Thank you very much for reading, and for your work on this project!

**Comment by yaira2** [comment]
Can you open a seperate feature request for each item we can track them properly?
