### ISSUE TITLE
Bug: The new shortcut page only allows selecting folders

### ISSUE THREAD

**Issue by Qin-shihuang** [files-community/Files#14418]
### Description

The "Browse" button on the new shortcut page only opens a window for selecting folders. To create shortcuts for other types, one must manually enter the filename. Explorer opens a "Browse for Files or Folders" window.

### Steps To Reproduce

1. Right-click on an empty space
2. Select New -> Shortcut
3. Click Browse 

### Requirements

There should be a window for selecting both files and folders.

### Files Version

3.1.1.0

### Windows Version

10.0.19045.3803

### Log File

.

**Comment by yaira2** [comment]
Thank you for your feedback, as far as I know there isn't a picker that allows both files and folders, but if anyone is aware, please let me know or open a PR.

**Comment by yaira2** [comment]
Thanks for the feedback, this option will be included in the next release.
