### ISSUE TITLE
right click and drag feature

### ISSUE THREAD

**Issue by Haque13** [files-community/Files#14428]
### What feature or improvement do you think would benefit Files?

right click and drag feature

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.1.1.0

### Windows Version

10.0.22621.2715

### Comments

please add a right click dragging like what we can do in normal explorer.
this feature is actually very useful.. 
for example:
- we can just right click and drag a zip file to a directory on the sidebar or tabs bar, and then just extract the files to that directory without needing to do any extra steps.
- we can just drag any files or folder to a directory on the sidebar or tabs bar, and then decide wether we want to just simply copy those files/folders into directory.. or we want to move those files/folders to that directory..

it's very very useful
![image](https://github.com/files-community/Files/assets/69665256/5787f543-2c10-4a33-bb0a-5ad9257b5ac7)

**Comment by yaira2** [comment]
Thank you for your feedback, this feature is on our todo list and is being tracked in #1396. You can click subscribe or comment on that issue to be notified when it's resolved.
