### ISSUE TITLE
Context Menu implovemrent

### ISSUE THREAD

**Issue by sovsiann** [files-community/Files#14421]
### What feature or improvement do you think would benefit Files?

Context menu is very slow to appear (on i7-1260P) - about 1-2 seconds.
Also, the grayed out "...Loading" sub menu is loading for additional 2-3 seconds (it has about 10 items).
It would be great to let user choose between the context menu types: Files original, Windows default, old windows style, etc.
Or let the user choose the context menu items and its order in custom manner.

### Requirements

- Full context menu opens in less than a second
- User is able to choose context menu style
- User is able to choose context menu items 
- User is able to change context menu items' order

### Files Version

3.1.1.0

### Windows Version

10.0.22621

**Comment by yaira2** [comment]
> Context menu is very slow to appear (on i7-1260P) - about 1-2 seconds.

Thank you for you feedback, this is likely related to the WinUI framework https://github.com/microsoft/microsoft-ui-xaml/issues/8359.

> Also, the grayed out "...Loading" sub menu is loading for additional 2-3 seconds (it has about 10 items).

Performance varies depending on the number of shell extensions, but I agree it can be better, we're tracking this in #11112.

> It would be great to let user choose between the context menu types: Files original, Windows default, old windows style, etc.

This isn't really feasible as the context menu items are specific to Files. If we displayed the File Explorer context menu, clicking on options like "rename" wouldn't do anything as it's meant for File Explorer and not Files. That said, we're planning support for a more compact menu in #9506 and you can already hide some of the built-in menu options from the settings dialog.
