### ISSUE TITLE
Bug: Taskbar icon isn't displayed

### ISSUE THREAD

**Issue by bellpepper0606** [files-community/Files#14427]
### Description

ウィンドウを閉じた後、タスクトレイのアイコンが表示されません。
また、挙動的には、バックグラウンドプロセスは稼働しているように見えます。
Deepl Translate
After closing the window, the task tray icon does not appear.
Also, behaviorally, background processes appear to be running.

### Steps To Reproduce

ウィンドウを閉じる。
Deepl Translate
Close the window.

### Requirements

しっかりと、新機能が稼働するようにすること。
Deepl Translate
Be firm and make sure that new features are up and running.

### Files Version

3.1.1.0

### Windows Version

10.0.22621.3007

### Log File

[debug.log](https://github.com/files-community/Files/files/13900197/debug.log)

**Comment by yaira2** [comment]
@bellpepper0606 thank you for the report, can you check if it appears after restarting Windows?

**Comment by jonolds** [comment]
basically the same logs for me. I set it to run in the background so it would hopefully open instantly like explorer. It's still pretty fast, but I'm getting the splash screen. Is that normal?

**Comment by yaira2** [comment]
@jonolds can you try force closing the app via task manager and then test again?

**Comment by bellpepper0606** [comment]
> @bellpepper0606 thank you for the report, can you check if it appears after restarting Windows?
書き忘れていましたが、解決しました。
I forgot to write it down, but I solved it.

**Comment by yaira2** [comment]
Thank you for getting back to us, glad to hear it's resolved!
