### ISSUE TITLE
Choose the color for each pane in dual pane mode

### ISSUE THREAD

**Issue by Gerrydg8** [files-community/Files#14424]
### What feature or improvement do you think would benefit Files?

Choosing a different color for each individual pane would make using dual pane more efficient.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.0.15.0

### Windows Version

10.0.22631.3007

**Comment by yaira2** [comment]
Thank you for your feedback, can you share more about the use case?

**Comment by yaira2** [comment]
We're going to continue tracking this in #13949 but it'll be great if you can comment on your use case.
