### ISSUE TITLE
Security window appears in background when using run as another user

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#1442]
**Describe the bug**
When you use the run as another user option, the security window to enter user credentials appears in the background.

**To Reproduce**
1. Right-click on an executable or installer file
2. Select run as another user
3. A security window will pop-up in the background

**Expected behavior**
The security window should appear in the foreground.

**Desktop:**
 - OS Version: Windows 10 Pro Insider Preview Build 20161.1000
 - App version: v0.12.0

**Additional context**
I don't know how to fix it since the FullTrustComponent has no visible windows so Windows opens the security windows in the background.

**Comment by yaichenbaum** [comment]
Merging with #985.
