### ISSUE TITLE
Possibility to customize tab name

### ISSUE THREAD

**Issue by davidbrisebois** [files-community/Files#14434]
### What feature or improvement do you think would benefit Files?

I use Files at work with several projects at the same time. I open one tab per project, but since each project has the same sub-directory structure, it is hard to see at a glance which tab is for which project. It would be nice if we could customize tabs name with a name we want instead of the current opened directory's name.

### Requirements

- By default, show current directory's name in the tab title like now
- In the right click menu, add an option to rename the tab.

### Files Version

3.1.1.0

### Windows Version

10.0.19045.3930

**Comment by yaira2** [comment]
Thank you for your feedback, we're tracking a solution to this issue in #14175.

**Comment by davidbrisebois** [comment]
I just read about it, and for me it is not exactly the same thing unless you have something else in mind that is not written in that issue or I misunderstand the solution. In my case, I don't really mind to know in what folder I am in the tab name as I have the path right underneath. Also, directory structure implies few child levels, so showing a hint like in #14175 wouldn't be of no help. That would make more sense if I could just manually rename first tab Project 1, second tab Project 2, etc. Name would stay until tab is closed regardless of current folder opened or if I navigate anywhere else.

Here is an example :
Tab 1 opened in Z:\Project 1\Photos\20240101
Tab 2 opened in Z:\Project 5\Communication\Client\

I would like to name tab 1 "Project 1" and tab 2 "Project 5".

**Comment by yaira2** [comment]
Thanks for the clarification, I see how the use case is a little different. We don't have plans to support alias folder names right now, however, you can hover over a tab to view the full path without needing to switch tabs.
