### ISSUE TITLE
Open tabs sometimes lost when Files crashes

### ISSUE THREAD

**Issue by clackwell** [files-community/Files#14432]
### Description

Sometimes when Files crashes (type while input focus is in file list, for example), upon restart Files has lost the information about the last open tabs. This is an annoyance, as those tabs are the "work setup" for some, and recreating this is feels cumbersome and unnecessary. Can the tab information be stored in a manner that recovery is always possible, and perhaps in a "transaction", so that a crash in the middle of writing the information does not lead to broken data?

### Steps To Reproduce

Have Files crash, for example by typing on the keyboard while input focus is in the file list.

### Requirements

The tabs should always be restored.

### Files Version

3.1.1.0

### Windows Version

10.0.22631.2861

### Log File

[debug.log](https://github.com/files-community/Files/files/13903914/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, there is a similar issue when shutting down Windows while Files is open. We're tracking this issue in #12624, you can add a comment or click subscribe in that issue to be notified when it's resolved.
