### ISSUE TITLE
Bug: Unable to drag and drop any file onto .ahk files

### ISSUE THREAD

**Issue by zZombieBatman** [files-community/Files#14430]
### Description

The drag-and-drop functionality seems to have a limitation, preventing the dragging and dropping of files with any file extension onto .ahk files.

I found a similar closed issue with .py files but that one has been fixed. Dragging and dropping doesn't seem to be an option.

### Steps To Reproduce

Make an .ahk file
Try to drag any file onto it.

### Requirements

It should allow me to drag and drop file onto .ahk files, but it currently does not. Essentially run that .ahk file with the filepath(s) as a parameter 

### Files Version

3.1.1.0

### Windows Version

10.0.22631 Build 22631

### Log File

[debug.log](https://github.com/files-community/Files/files/13903822/debug.log)

**Comment by yaira2** [comment]
Thanks for the report

**Comment by yaira2** [comment]
Fyi @antonioseet

**Comment by pojith** [comment]
can i solve this issue

**Comment by pojith** [comment]
what is knowledge required to solve the issue

**Comment by pojith** [comment]
; Enable drag-and-drop events
Gui +LastFound
Droplist := RegisterCallback("DropFiles")
DllCall("DragAcceptFiles", "Ptr", A_ScriptHwnd, "Int", 1)

; Create a simple GUI window
Gui, Margin, 10, 10
Gui, Add, Text, w300, Drag and Drop Files Here
Gui, Show, w320 h100, Drag-and-Drop Example
return

; Handle messages, including WM_DROPFILES
OnMessage(0x111, "WM_COMMAND")

; DropFiles subroutine
DropFiles(wParam, lParam) {
    ; Get the number of dropped files
    FileCount := DllCall("DragQueryFile", "Ptr", wParam, "Int", 0xFFFFFFFF, "UInt", 0)

    ; Loop through each dropped file
    Loop, %FileCount%
    {
        ; Get the length of the file path
        FileLen := DllCall("DragQueryFile", "Ptr", wParam, "Int", A_Index - 1, "Ptr", 0, "Int", 0) + 1

        ; Get the file path
        VarSetCapacity(FilePath, FileLen)
        DllCall("DragQueryFile", "Ptr", wParam, "Int", A_Index - 1, "Str", FilePath, "Int", FileLen)

        ; Display the file path (you can modify this part as needed)
        MsgBox, Dropped File: %FilePath%
    }

    ; Release resources
    DllCall("DragFinish", "Ptr", wParam)
}

; GUI close event
GuiClose:
ExitApp

is it correct?

**Comment by Josh65-2201** [comment]
This is already being worked on

**Comment by pojith** [comment]
ok bro
