### ISSUE TITLE
Tree view

### ISSUE THREAD

**Issue by akienm** [files-community/Files#14435]
### What feature or improvement do you think would benefit Files?

So I just purchased this, in part because of your rolling up of usage by folder. bravo!

But then I found I can't use the left tree view as a tree view of the drive. *boggle*. All my dev IDEs are that way, explorer is that way... I don't think I'm gonna be able to use this. Very sad.

### Requirements

Allow browse hard drives/network drives/and so on with a live tree view.

### Files Version

CBD4-8A8F

### Windows Version

10.0.19045.3930

**Comment by yaira2** [comment]
Thank you for your feedback, a tree view is on the todo list and is being tracked in #1928. You can add a comment or subscribe to the issue to be notified of any updates.

**Comment by yair100** [comment]
@akienm Tree View is currently available in preview https://files.community/download. It will be included in the next stable release.
