### ISSUE TITLE
Tags dissappeared

### ISSUE THREAD

**Issue by Vuccappella** [files-community/Files#14436]
### Description

The tags I had added in the settings menu and applied to files completely dissappeared both from the files they were applied to and the settings menu, seems like it was reset to default.

I don't know what caused that, definintely not me changing any settings or anything but I did swap out my mother board and noticed it a little after that so I'm suspecting that caused the issue. 

I'm looking to see if anyone has any idea it it would be possible to somehow restore them (especially to the applied files) or if this is common when swapping out mother boards or disconnecting hard drives for example and then re-connecting them.

### Steps To Reproduce

1. Have no idea how to reproduce as I don't know the cause

### Requirements

Tags should not dissappear randomly.

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2861

### Log File

[debug.log](https://github.com/files-community/Files/files/13908971/debug.log)

**Comment by yaira2** [comment]
Thanks for the report, v2.5.21 is an old version of Files and it might be a bit hard to debug what went wrong there. Tags are saved as a guid alternate data streams (this only works on drives formatted as NTFS) so even if the list of tags got removed from settings they are still present, and you can rebuild the list of tags using the guids.
1. To check if this is the case, open the settings dialog and there should be an option in the "Folders" page to show alternate data streams.
2. Navigate to a location that had tagged files and check if there are any alternate data streams displayed.

**Comment by Vuccappella** [comment]
Hi @yaira2 
Thanks for your reply, 

I do not have that option I believe in my Settings under Folders (or anyone else where I looked at):
![image](https://github.com/files-community/Files/assets/5423643/e33e273e-c31a-4565-ac9e-769aaf3d7e2f)
I can try and update the version (too bad I dont see an auto update log or something, I didnt realize its outdated) and then check again if that would help?

Much appriciated,

**Comment by Josh65-2201** [comment]
It's under the hidden items section.

**Comment by Vuccappella** [comment]
@Josh65-2201 Thanks! I've enabled the setting and I can now clearly see the adittional alternate data streams for the files that @yaira2  mentioned in folders where I have tagged items.

Adittionally, after checking the option General --> Customize the right click context menu --> Context Menu Options --> Show edit tags flyout or just after restarting the application I can now see a list of uknown Tags in my settings as well but that might of just been also picked up by me navigating to the folders where I had Unkown tagged items.

**Comment by Josh65-2201** [comment]
If there showing as unknown then at some point the information for what the tag should be was lost. If you don't have a backup from the import/export options then you will have to rename them from settings to see what files/folders there linked to and rename/color them as you want.

**Comment by Vuccappella** [comment]
@Josh65-2201 I think I can manage with that workaround but it seems that for some files the tags were lost while they still have an alternative data stream file that ends on :Zone:Identifier while the ones with unkown tags have the :files alternative datastream. 

I'm wondering if there is any way that these extra data streams can tell me what the tag names were for the files somehow. 

If not, I'll have to re-classify anyway and will make sure I do a backup of the settings once done as I'm experiencing issues with the computer and might have to swap other hardware soon as well.

**Comment by Josh65-2201** [comment]
Files only uses the `:files` end. zone identifier is for Windows defender use.

**Comment by yaira2** [comment]
It's a bit strange the swapping motherboards would cause this issue but I'm glad to hear the data streams are still present.
