### ISSUE TITLE
Ability to set the default option on colliding names

### ISSUE THREAD

**Issue by earshinov** [files-community/Files#14441]
### What feature or improvement do you think would benefit Files?

When I copy&paste files, sometimes the colliding name appear, and I want to quickly overwrite old file to new. To do so, I have to manually change "Generate new name" to "Replace existing" every time.

### Requirements

- Persist the "Generate new name" / "Replace existing" / etc. option selected in the top-right corner of the dialog for further operations.
- Alternatively, make the default option configurable via JSON settings. This would also be fine, although less user-friendly in my opinion

### Files Version

3.0.15.0

### Windows Version

10.0.22631.2861

### Comments

This is sort of a duplicate of #7926 , closed as to be fixed in #5645 / #8914, but never fixed (as it often happens).

**Comment by yaira2** [comment]
Thanks for the report, this is already supported but if it's not working, please open an issue with the bug report template so we can track this issue.
