### ISSUE TITLE
very slow performance with large zip file

### ISSUE THREAD

**Issue by jason919** [files-community/Files#14446]
### Description

very slow performance with large zip file that has many sub folders and files.
7 zip can open the zip file instantly, however, if I try to open it with Files, it just freezes

### Steps To Reproduce

open a large zip file that has many sub folders and files with Files App

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

large zip file that has many sub folders and files

### Windows Version

windows 11 pro, 23H2

### Log File

[debug.log](https://github.com/files-community/Files/files/13922558/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, we're tracking this in #9848.
