### ISSUE TITLE
Bug: Drives not loading in side menu

### ISSUE THREAD

**Issue by Aetherinox** [files-community/Files#14440]
### Description

At present, none of the drive letters appear on the left-side menu. They also do not appear in the **Home** page.
Drives do however, appear perfectly fine on the "This PC" tab.

![1](https://github.com/files-community/Files/assets/118329232/9c443a09-a7c2-4ded-a99f-688c3d37938e)

![2](https://github.com/files-community/Files/assets/118329232/8ce78805-c0fc-4c63-99a8-a35a35d027b8)

### Steps To Reproduce

1. Install latest version
2. Launch Files app
3. Compare results between clicking the **Drives** tab on left menu & the drive list on the **This PC** panel.

### Requirements

- e.g. Fix crash that occurs when...
Drives should populate as they do on the "This PC" tab.

### Files Version

3.1.1.0

### Windows Version

10.0.22631.2861

### Log File

[debug.log](https://github.com/files-community/Files/files/13914877/debug.log)

**Comment by yaira2** [comment]
>    at Vanara.Windows.Shell.ShellLink.get_Target()
   at Files.App.Utils.RecentItem.RecentItems.<>c__DisplayClass14_1.<ListRecentFoldersAsync>b__2()
2024-01-11 21:15:13.6780|Warning|System.ComponentModel.Win32Exception (15): The system cannot find the drive specified.
   at Vanara.PInvoke.Shell32.ShellUtil.GetShellItemForPath(String path)
   at Vanara.Windows.Shell.ShellLink.get_Target()

**Comment by yaira2** [comment]
Do you know if this was also an issue in previous versions?

**Comment by Qin-shihuang** [comment]
@yaira2 It seems to be the same issue as #14345, which I have encountered several times as well.

**Comment by yaira2** [comment]
The log file looks a little different but it's possible. Do you know when this issue started? I'm wondering if there is a bug in Windows.

**Comment by Aetherinox** [comment]
> Do you know if this was also an issue in previous versions?

Sadly, I was using an older version last night (probably six months behind), and after going through a few directories, I opted to update and noticed the lack of drives.

I'm going to do a wipe of the software today and go install an older version.

I also have a 2nd machine I'm going to try installing on.

Should be about an hour or two, and I'll report back.

**Comment by Aetherinox** [comment]
Just an interesting note.

I opted to try loading the latest stable build into a VMWare Virtual Machine with Windows 11. The drives loaded right up, without hesitation.

![bIdGz00](https://github.com/files-community/Files/assets/118329232/bcd495c7-cc98-4bc7-9d5d-585a1b81366e)

| App | Version |
| --- | --- |
| Files | `3.1.1.0` |
| Windows | `10.0.22621.3007` |

**Comment by Aetherinox** [comment]
A new interesting note.

A few minutes ago, I was working on my virtual machine. I was transferring a file from an old backup to load into my VM.
I noticed when it was transferring that I got an error that the virtual machine was currently in-use of a process called "COM Surrogate".

I went looking to see what COM Surrogate was, and that it "shouldn't" be force-closed, but it could be if it gives issues.
I had 4 instances of COM Surrogate running so I opted to shut them down. I figured if Windows needs them, they'll be re-launched.

The very second that I killed that task, I noticed on my other machine that my drives magically started loading.

I'm not too familiar with how the processes interact with Windows, but Files is now successfully showing every single drive.  I even closed the Files app and re-loaded it, and all the drives immediately load.

**Comment by yaira2** [comment]
> I had 4 instances of COM Surrogate running so I opted to shut them down. I figured if Windows needs them, they'll be re-launched.

Interesting, I suppose a safer method is to restart Windows.

I think we can chalk this up as a Windows issue but let us know if it happens again.
