### ISSUE TITLE
Bug: Crash when selecting the address bar with Shift + Tab

### ISSUE THREAD

**Issue by Qin-shihuang** [files-community/Files#14442]
### Description

https://github.com/files-community/Files/assets/68013339/49fd23c6-8311-4328-9d61-dc794fe80b60

### Steps To Reproduce

1. Navigate into a multi-level directory.
2. Click on the last-level directory in the address bar.
3. Click on the search bar, press Shift+Tab, observe the last-level directory being selected.
4. Click the address bar and enter its parent directory.
5. Click on the search bar, press Shift+Tab, observe the crash.
 

### Requirements

Files should not crash. The address bar may either select the parent directory or the root directory.

### Files Version

3.1.1.0

### Windows Version

10.0

### Log File

[debug.log](https://github.com/files-community/Files/files/13920597/debug.log)

**Comment by yaira2** [comment]
Thanks for the report, I was able to repro this on my end.

**Comment by yaira2** [comment]
Would you like to look into this one?

**Comment by yaira2** [comment]
`Shift` + `Tab` is a built-in behavior but it could it's trying to focus on the item that's no longer in the visual tree.

**Comment by hishitetsu** [comment]
```
2024-01-12 22:11:51.5256|Error|System.ArgumentOutOfRangeException: This collection cannot work with indices larger than Int32.MaxValue - 1 (0x7FFFFFFF - 1). (Parameter 'index')
   at ABI.System.Collections.IList.ToAbiHelper.EnsureIndexInt32(UInt32 index, Int32 listCapacity)
   at ABI.System.Collections.IList.ToAbiHelper.GetAt(UInt32 index)
   at ABI.System.Collections.IList.Vftbl.Do_Abi_GetAt_0(IntPtr thisPtr, UInt32 index, IntPtr* result)
```
This is one of the most frequent and the most annoying crash. This crash occurs in many situations, but AFAIK, this is the first time that a procedure has been discovered to reliably reproduce it.
I believe it is related to https://github.com/microsoft/microsoft-ui-xaml/issues/8684.
