### ISSUE TITLE
Add tooltip for item 

### ISSUE THREAD

**Issue by AzizAyoubi** [files-community/Files#14456]
### What feature or improvement do you think would benefit Files?

In default windows Explorer, when you hover over a file or folder, it shows tooltip with basic properties like size and date modified, I miss that in Files

### Requirements

- Tooltip for folders and files

### Files Version

3.1.1.0

### Windows Version

10.0.23615.1000

**Comment by yaira2** [comment]
Thank you for the feedback, hovering over items in the Grid Layouts will display a tooltip. The Details Layout used to have one as well but we removed it after receiving a lot of feedback that it's redundant since the Details Layout already displays the info.
