### ISSUE TITLE
Bug: CTRL+N opens a new tab rather than a new window

### ISSUE THREAD

**Issue by ccrooks562** [files-community/Files#14452]
### Description

Hi there,

With the latest update, whenever I use the shortcut "CTRL+N" for a new window in Files, it opens a new tab rather than a new window. This did not happen before the latest update. It also does not pop open a new window whenever a program attempts to open a window in the Files explorer (say after a download has completed. It just opens a new tab.

Could this please be fixed? 

Thank you!

### Steps To Reproduce

1. Enable `Files settings > General > Startup settings > Open tab in existing instance when opening Files from another app`
2. Press CTRL+N
3. It opens a new tab rather than a new window

### Requirements

Fix Files openings a new tab rather than a new window with shortcut. 

### Files Version

3.1.1.0

### Windows Version

10.0.22631.3007

### Log File

[debug.log](https://github.com/files-community/Files/files/13929726/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.


> It also does not pop open a new window whenever a program attempts to open a window in the Files explorer (say after a download has completed. It just opens a new tab.

With the `Files settings > General > Startup settings > Open tab in existing instance when opening Files from another app` enabled this is how it suppose to work.

**Comment by yaira2** [comment]
Thanks for the report, this is indeed a bug and we'll add it to our todo list.

**Comment by hishitetsu** [comment]
I found that opening a new window is not implemented as a RichCommand. It should be re-implemented as a RichCommand along with the bug fix.
