### ISSUE TITLE
Open files in a new window rather than new tab

### ISSUE THREAD

**Issue by ccrooks562** [files-community/Files#14451]
### What feature or improvement do you think would benefit Files?

Hi there,

With the latest update of Files, whenever I press the shortcut "CTRL + N" Files opens a new tab rather than a new window. How can I make it open a new window rather than a new tab? It used to not do this.

Thank you so much!

### Files Version

3.1.1.0

### Windows Version

10.0.22631.3007

**Comment by Josh65-2201** [comment]
Thanks for the feedback, This would be a bug can you please open a new issue using that template.

**Comment by Josh65-2201** [comment]
Right now you can turn off `Files settings > General > Startup settings > Open tab in existing instance when opening Files from another app`

**Comment by ccrooks562** [comment]
Understood. Thank you!

**Comment by ccrooks562** [comment]
> Thanks for the feedback, This would be a bug can you please open a new issue using that template.

Done. Thanks!
