### ISSUE TITLE
The app is not installing in my x64 pc

### ISSUE THREAD

**Issue by Dell-95** [files-community/Files#14459]
### Description

The app is not installing in my x64 1605 pc, Also I was not able find any installer for x64 please help. The executable file opens and starts extracting but crashes right after finishing 100 percent. If it is any issue from my part, please reply.

### Steps To Reproduce

Right after execution

### Requirements

please make it compatable with x64.

### Files Version

3.1

### Windows Version

Windows 10 Ltsb Enterprise edition 2016 1607 x64

### Log File

No logs

**Comment by Josh65-2201** [comment]
Your Windows version is too old to run Files, you will have to update to 19041 or above.

**Comment by yaira2** [comment]
I don't think there are newer versions of LTSB but you can get something similar with LTSC.

**Comment by Dell-95** [comment]
Is there any any way to upgrade from LTSB to LTSC with the LTSB product key
?

**Comment by yaira2** [comment]
I recommend contacting Microsoft support with that question
