### ISSUE TITLE
Can't install (WIndows 10)

### ISSUE THREAD

**Issue by olegthegreat** [files-community/Files#14450]
### Description

Using Classic Installer, opens the installation window, "Launch after install" is clicked... when then click on Install button, it returns with error that it can't install and to contact your software provider.  Tried in regular and admin mode, same thing.  Very interested in the program, but obviously can't do anything if I can't install it.

### Steps To Reproduce

See above

### Requirements

- e.g. Fix crash that occurs when...
?

### Files Version

3.1.1.0

### Windows Version

Windows 10 Pro

### Log File

n/a

**Comment by Josh65-2201** [comment]
Unfortunately this is a Windows issue that happens for some people, can you try
1. Opening PowerShell as administrator
2. Run this command
```Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/stable/Files.Package.appinstaller```
3. See if Files is in the start menu all apps section

**Comment by olegthegreat** [comment]
Thank you - that worked perfectly!  Since I have you, and apologies for silly question, but how do I show the tiered "folder view" (similar to the original file explorer)..all i see is a list of favorite and drives... thank you!

**Comment by Josh65-2201** [comment]
Glad it worked, If you mean a tree view there isn't one in Files yet but is being worked on in #1928. You can check there or click subscribe in the right sidebar for updates.

**Comment by iCanHazConfetti** [comment]
Fails to install. 

Description:
Using Classic Installer, (check the allow this file, etc in Properties) opens the installation window, "Launch after install" checkbox is either ticked (or not ticked) when then checkbox for "Launch when install completes" is ticked, then you click on "Install" button, it returns with the Error: "Install failed. Please contact your software vendor." Tried in both regular and "Run as administrator" mode, with the same results. Pretty screenshots, Comparing to OneCommander & XYPlorer, would like to get a hands-on trial with Files.community app... Like olegthegreat, I am also very interested in the program, but obviously can't do anything if I can't install it.

Steps To Reproduce:
See above

Requirements
e.g. Fix crash that occurs when...
?
Files Version
3.3.0.0

Windows Version
Windows 10 Pro x64
<img width="723" alt="## MODEL M 0001 session $SRC= tumblr_8454c19e3256f39ebca7d30069014123_ab661256_640 jpg JPEG PNG__e1 0= $crop= 2x3 $flip= h __save-as-copy" src="https://github.com/files-community/Files/assets/166200092/8f505fba-f0fa-4f5a-970c-4a71f626ef93">


Log File
n/a
<img width="492" alt="Files community Classic Installer v 3 3 0 0 Install Failed_ 2024 04 06 = 06 42 00 __Screenshot_1" src="https://github.com/files-community/Files/assets/166200092/69999cee-5034-4a1c-b1e1-1f3474fe1863">

**Comment by Josh65-2201** [comment]
@iCanHazConfetti if you want support please upload your own screenshot of the error not an url embed

**Comment by iCanHazConfetti** [comment]
@Josh65-2201  I had some growing pains with my newness to github... it took me a moment to get my screenshot uploaded. I tried the PowerShell method above and it fails on my machine too. Grabbing a screenshot of that to add...

Thanks for the quick reply!

**Comment by Josh65-2201** [comment]
What error do you get in Powershell?

**Comment by iCanHazConfetti** [comment]
See these screenshots: 
<img width="1152" alt="Files community Classic Installer v 3 3 0 0 Install Failed_PowerShell v 7 4 1_ 2024 04 06 = 07 19 00 __Screenshot_2" src="https://github.com/files-community/Files/assets/166200092/bf435be2-c7e6-489e-af6d-a6e4f999e7a1">
<img width="1152" alt="Files community Classic Installer v 3 3 0 0 Install Failed_PowerShell v 7 4 1_ 2024 04 06 = 07 19 00 __Screenshot_3" src="https://github.com/files-community/Files/assets/166200092/a5632cd7-ca38-46f1-921f-4e99b6413cf1">

**Comment by Josh65-2201** [comment]
You have to use Windows built in Powershell not the external Powershell 7

**Comment by iCanHazConfetti** [comment]
oh. Well. Hoping that works, and, will let you know.

**Comment by yair100** [comment]
@iCanHazConfetti Tree View is currently available in preview https://files.community/download. It will be included in the next stable release.
