### ISSUE TITLE
Date sorting is broken

### ISSUE THREAD

**Issue by StanFromTraction** [files-community/Files#14460]
### Description
Apparently 2 minutes ago is less recent than 2 days ago or months ago:

![image](https://github.com/files-community/Files/assets/105176736/f6f61260-c3aa-4a60-bf11-1bc59f80bee8)

### Steps To Reproduce

Sort a dir by date. Enjoy the random sorting.

### Requirements

- Fix sorting

### Files Version

3.1.1.0

### Windows Version

10.0.22631.2861

### Log File

[debug.log](https://github.com/files-community/Files/files/13933168/debug.log)

**Comment by yaira2** [comment]
Is that item a file or folder?

**Comment by StanFromTraction** [comment]
Thanks for the solution! 

I think having this option on by default is a terrible idea UX-wise. 
Most people expect date sorting to simply sort items by date, without applying an additional hidden sorting logic.

This behavior should also be made more obvious with headers like you have for the "Group by" option

**Comment by yaira2** [comment]
> I think having this option on by default is a terrible idea UX-wise.

I agree that this makes more sense, but the default behavior on Windows is to sort them separately and we feel it's important to be consistent in this area.

**Comment by StanFromTraction** [comment]
Hmm on which Windows version do you observe this behavior? I checked and none of the devices around do it, may it be on Win10 or 11

I don't remember changing the Windows Explorer, but it could still be
If that is indeed the default behavior, you are right since consistency is more important

**Comment by Josh65-2201** [comment]
Windows has always had the default to have folders and files sorted separately
