### ISSUE TITLE
lossless multipart video trim button appears when selecting a video file.

### ISSUE THREAD

**Issue by fazioliamboina** [files-community/Files#14467]
### What feature or improvement do you think would benefit Files?

Using FFMPEG, it is relatively easy to create a small video editor like losslesscut. I will be using this 10 times a day.

Have a Card design instead of a timeline design. it is much more compact. i have developed this program to do the same thing using ffmpeg and XAML:

![image](https://github.com/files-community/Files/assets/69403673/b65f7131-c5b4-4235-b2a1-c9460eeba6f7)

i discontinued it, because i dont have the time to make it popular. and its simple enough to fit it inside a file browser, and it should have all along.

you dont even need my source code, because ffmpeg is really that simple.

the button will be shown after selecting a video file, just like the rotate buttons for images.

### Requirements

ffmpeg

### Files Version

Not important

### Windows Version

11

### Comments

N/A

**Comment by fazioliamboina** [comment]
completed? what this means?

**Comment by yaira2** [comment]
@fazioliamboina I noticed that a lot of your feedback is along the lines of turning Files into a photo and video viewer/editor. We appreciate the feedback and we're certainly not ruling out adding some more photo/video options down the line (photo layout is on the todo list) but creating the ultimate photo/video app is not our primary goal. Our current focus is on improving stability, performance, and adding features that the broader user base is interested in.

**Comment by fazioliamboina** [comment]
te broader userbase is using XnViewMP and faststone and video editors.

**Comment by fazioliamboina** [comment]
xnviewmp does also have its fair share of issues and bugs. Its still popular because the features are worth it. you should not focus on performance and stability, because you are not going to beat other file explorers on that anyway. so thats not your selling point. you have to focus on features only. and when you have millions of users, the stability and performance comes easely because you will have the funds.

**Comment by fazioliamboina** [comment]
XnviewMP and faststone both have a steady donation depot
