### ISSUE TITLE
Bug: Switch file being renaming with tab key before refreshing file order

### ISSUE THREAD

**Issue by BillyBuerger** [files-community/Files#14471]
### Description

When I need to rename a number of concurred files, I'm used to renaming the first and then hitting tab to move to the next one to rename.  In Windows Explorer, it works as expected.  But in Files, the selection moves next based on the newly named file and not the original file name. 

### Steps To Reproduce

Here is a list of example file names...

Test 1 W.txt
Test 2 B.txt
Test 3 V.txt
Test 4 A.txt

1) Rename the W file to just W.txt and hit tab.  The expected result would be to start renaming the B file.  But W gets moved to the end and there is no next file so it stops renaming.
2) Rename the B file to just B.txt and hit tab.  It correctly selects the V file and starts renaming since B is still the first item in the list.
3) Rename the V file to just V.txt and hit tab.  The expected result would be to start renaming the A file.  But V is now before W so it starts renaming W.txt instead.

### Requirements

Rename "Test 1 W.txt" to W.txt and hit tab should move to "Test 2 B.txt" since that's the next item based on the previous name of the file.  When the tab button is pressed, the order has not changed so the next item should be determined first, then perform the rename and select this next file instead of finding the next file after the rename.

### Files Version

3.1.1.0

### Windows Version

10.0.22621.3007

### Log File

[debug.log](https://github.com/files-community/Files/files/13945575/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.
