### ISSUE TITLE
Bug: Files crash When I'm copying files to a network drive

### ISSUE THREAD

**Issue by mtoranzo** [files-community/Files#14474]
### Description

While I'm moving a file that's on a local drive, to a network drive, if at the same time I try to delete files from another tab or press "copy" on the file that's being moved to the network drive the crash occurs

### Steps To Reproduce

1. cut file from local drive (>100mb)
2. paste file in network drive
3. meanwhile, copy te origin file into other location / or delete other files in local storage

### Requirements

- e.g. Fix crash that occurs when...
no requirements

### Files Version

3.1.1.0

### Windows Version

10.0.22631.3007

### Log File

[debug.log](https://github.com/files-community/Files/files/13950681/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
@mtoranzo can you still repro this issue in v3.6?
