### ISSUE TITLE
Edit Settings file seems to be ephemeral

### ISSUE THREAD

**Issue by comertial** [files-community/Files#14472]
### Description

In the settings, under advanced option, when you click edit settings file, a file is opened with different options that you can change. When the changes are made and you save the file and restart files in order to take the new settings, this file is overwritten with the previous values.

So the settings file that we are changing seems to be ephemeral, or the actual settings file is somewhere else and not in the path that the files app opens.

### Steps To Reproduce

1. go to settings -> advanced -> edit settings file
2. do some changes and save the file
3. restart files
4. open again the settings -> advanced -> edit settings file
5. you will notice that previous changes are discarded

### Requirements

Settings file should be persistent for the user and not get overwritten.

### Files Version

3.1.1.0

### Windows Version

10.0.19045 Build 19045

### Log File

[debug.log](https://github.com/files-community/Files/files/13947167/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, We're tracking this in #10935. You can check there or click subscribe in the right sidebar for updates.

You have to fully close Files for changes to save in the settings file, as Files runs in the background that would be with right clicking the system tray icon or finding `files.exe` in task manager.
