### ISSUE TITLE
Open tabs where you left off 

### ISSUE THREAD

**Issue by EvilCheez** [files-community/Files#14478]
### What feature or improvement do you think would benefit Files?

When opening Files after you've shutdown or restart it would be nice to start with the tabs you had open if you have the option Continue where you left off enabled. 

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.1.1.0

### Windows Version

10.0.22631.3007

### Comments

I thought this is how it was working on the first place, but now, if you close Files from the tray or reboot/shutdown, when you open it again, it starts from Home with one tab.

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #12624 . You can check there or click subscribe in the right sidebar for updates.

**Comment by EvilCheez** [comment]
So, it seems that if you quit from the tray and do not close the window and then shut down or reboot, it works.
