### ISSUE TITLE
Files se cierra

### ISSUE THREAD

**Issue by Mariepiz** [files-community/Files#14476]
### Description

Aparece un mensaje "algo ha fallado" y se cierra el programa. 

### Steps To Reproduce

Aparece un mensaje "algo ha fallado" y se cierra el programa. 

### Requirements

Al descargar un archivo 

### Files Version

3.1.1.0

### Windows Version

10.0.19045.3930

### Log File

[debug.log](https://github.com/files-community/Files/files/13951921/debug.log)

**Comment by yaira2** [comment]
Thanks for the report, merging with #13995
