### ISSUE TITLE
Bug: Reorder on map drive 

### ISSUE THREAD

**Issue by mtoranzo** [files-community/Files#14475]
### Description

When I'm on a network drive, and I press to change the order (by any column) the application stops for several seconds (>30)

### Steps To Reproduce

1. access map drive
2. reorder file list 

### Requirements

- e.g. Fix crash that occurs when...
no requirements

### Files Version

3.1.1.0

### Windows Version

10.0.22631.3007

### Log File

![image](https://github.com/files-community/Files/assets/926024/5a6c6667-ce2e-4732-90fb-60070a081d64)

**Comment by mtoranzo** [comment]
It takes about 30 seconds for the list of files and folders to appear, and the application starts working properly again

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
