### ISSUE TITLE
Bug: Last modified date is missing from the properties window

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#14487]
### Description

I've noticed an inconsistency when clicking on a folder pinned to the sidebar and accessing its properties. Unlike when I'm inside the folder and check its properties, the last modified date is not displayed.

### Steps To Reproduce

1. Right-click a pinned folder from the sidebar
2. Click on "Properties"

### Requirements

Ensure that the last modified date is consistently displayed in the properties window, whether accessed from the sidebar or within the folder.

### Files Version

4.1.3.0

### Windows Version

10.0.22631.3007

### Log File

No need.

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by MrFrawsty** [comment]
I am currently looking into this. I should be able to figure out how to fix it just to avoid duplicate efforts

**Comment by MrFrawsty** [comment]
I ran out of time and couldn't figure it out exactly but for the next person it looks like when the folder gets pinned to the sidebar the modified date and some other folder properties aren't getting saved.
