### ISSUE TITLE
Bug: Items are sometimes not listed in Downloads folder

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#14482]
### Description

As described in the title. The status bar counts the number of items and there is no message that the folder is empty.
![image](https://github.com/files-community/Files/assets/66369541/5cdbb724-062e-4f90-aec6-59485ca5c03f)

### Steps To Reproduce

1. Download a file from the internet.
2. Launch Files.
3. Open Downloads folder.

### Requirements

List the items correctly.

### Files Version

3.1.1.0

### Windows Version

10.0.22631.3007

### Log File

No noteworthy logs are output.

**Comment by yaira2** [comment]
Thanks for the report

**Comment by yaira2** [comment]
I can reproduce this as well
1. Open large folder (Eg system32)
2. Switch between List View and Large Icons a bunch of times
![image](https://github.com/files-community/Files/assets/39923744/c27cca79-6e00-4fc0-8256-c198838d46b5)

**Comment by hishitetsu** [comment]
> I can reproduce this as well

This may be the same as the crash noted in #14580.
