### ISSUE TITLE
Files is just as slow as File Manager

### ISSUE THREAD

**Issue by MichaelCondry** [files-community/Files#14486]
### Description

 Here is a long running background
https://answers.microsoft.com/en-us/windows/forum/windows_11-files/windows-11-file-explorer-is-slow-lagging-hangs/30bc56ce-9a59-42ef-8fda-3b2fee603397?messageId=6c6e35e6-f71c-4733-ab10-a20a42db6ca4
I downloaded Files because comments on the web said it fixed thie issue of Windwos 11 File Manager being slow or non-functional with external drives connected on USB (A or C).  It does not do any better. Waste of moneylong-running

### Concerned code

See other comments

### Gains

MUCH better performance (at least as good as Windows 10 on file systems connected over USB. 

### Requirements

Better preformance than File Manager on Windows 11 for file systems connected over USB (not just a stick).performance

### Comments

https://answers.microsoft.com/en-us/windows/forum/windows_11-files/windows-11-file-explorer-is-slow-lagging-hangs/30bc56ce-9a59-42ef-8fda-3b2fee603397?messageId=6c6e35e6-f71c-4733-ab10-a20a42db6ca4

Files does not deliver the performnace expected. Wast of moneyWaste

**Comment by yaira2** [comment]
Thank you for your feedback, we're working on improving performance and will continue releasing updates with this goal in mind. 1. Can you elaborate on the performance issues you're experiencing on external drives?
2. Which version of Files are you using?

**Comment by MichaelCondry** [comment]
On Windows 11, Microsoft clearly did something to slow down local file access. Likely to sell more cloud storage.  

 

I sent a link to a long-running discussion on this https://answers.microsoft.com/en-us/windows/forum/windows_11-files/windows-11-file-explorer-is-slow-lagging-hangs/30bc56ce-9a59-42ef-8fda-3b2fee603397?messageId=6c6e35e6-f71c-4733-ab10-a20a42db6ca4

 

IF Files can fix this issue you will get many customers. No one has a good answer. 

 

If I search with File Manager, it will not find files it used to in Windows 10.  In Windows 10- we could download pictures from a phone, not Windows 11. 

 

With a USB 3.1 or USA C connection file access should be fast.  Many of us use external drives. 

 

Michael W. Condry, PhD, Life IEEE Fellow

IEEE IES, TEMS, Computer, and CTSoc

Chair, World Technology Summit

 ***@***.***> ***@***.***, ***@***.*** ***@***.***>

**Comment by yaira2** [comment]
> On Windows 11, Microsoft clearly did something to slow down local file access. Likely to sell more cloud storage.

This is a common complaint regarding File Explorer ever since they switched to WinAppSdk. It's a known fact that WinAppSdk is slower than previous app frameworks, but it seems to be worse in File Explorer for whatever reason.

Files uses WinAppSdk as well so certain features might be a little bit slower, but we'll do our best to optimize and work around the different limitations. I noticed that renaming files is singled out in that thread, are you able to repro this issue in Files?

**Comment by MichaelCondry** [comment]
Yes, in the past I could search a large directory of say music files for a name or singer. IT was quick even on external disk. Now it will not work.  Files is exceptionally slow here as well. Particularly, if multiple directories are involved. 

 

I can run a test for you.

 

Michael W. Condry, PhD, Life IEEE Fellow

IEEE IES, TEMS, Computer, and CTSoc

Chair, World Technology Summit

 ***@***.***> ***@***.***, ***@***.*** ***@***.***>

**Comment by yaira2** [comment]
A video recording would be great (you can upload videos directly to GitHub). It might be worth it to test using the preview version available here https://files.community/download

**Comment by MichaelCondry** [comment]
I am not sure how to  do a video screen shot. 

 

Michael W. Condry, PhD, Life IEEE Fellow

IEEE IES, TEMS, Computer, and CTSoc

Chair, World Technology Summit

 ***@***.***> ***@***.***, ***@***.*** ***@***.***>

**Comment by MichaelCondry** [comment]
The link just goes to the place I already downloaded and paid.

 

Michael W. Condry, PhD, Life IEEE Fellow

IEEE IES, TEMS, Computer, and CTSoc

Chair, World Technology Summit

 ***@***.***> ***@***.***, ***@***.*** ***@***.***>

**Comment by yaira2** [comment]
Click the download option for "preview", this will contain all the latest changes that haven't been released to stable yet.

**Comment by MichaelCondry** [comment]
Ok, will do and test tomorrow.

 

Michael W. Condry, PhD, Life IEEE Fellow

IEEE IES, TEMS, Computer, and CTSoc

Chair, World Technology Summit

 ***@***.***> ***@***.***, ***@***.*** ***@***.***>

**Comment by MichaelCondry** [comment]
Hello Yair-

OK, I downloaded the preview. Went to my “music” directory and did a search on “beach”  (I know I have beach boys songs, it is just a test).

 

It returned “No Items Found”. 

 

I have multiple beach boys directories and files.  So it is failing the search.   Also, the startup time to open Files is 10-30 seconds.  

 

Sorry, I am not sure how to do a video can or I could show you the results live with the timings.

 

Michael W. Condry, PhD, Life IEEE Fellow

IEEE IES, TEMS, Computer, and CTSoc

Chair, World Technology Summit

 ***@***.***> ***@***.***, ***@***.*** ***@***.***>

**Comment by yaira2** [comment]
Can you send a screenshot of the search results page?

**Comment by MichaelCondry** [comment]
Michael W. Condry, PhD, Life IEEE Fellow

IEEE IES, TEMS, Computer, and CTSoc

Chair, World Technology Summit

 ***@***.***> ***@***.***, ***@***.*** ***@***.***>

**Comment by yaira2** [comment]
I believe you need to upload the image directly to GitHub, attaching it via email isn't supported.

**Comment by MichaelCondry** [comment]
Ok, but I will try.  I went to a sub directory and listed the files. 

 

One call Surfer Girl – so I did a search on girl.  It failed. I will upload the images to github.

 

Michael W. Condry, PhD, Life IEEE Fellow

IEEE IES, TEMS, Computer, and CTSoc

Chair, World Technology Summit

 ***@***.***> ***@***.***, ***@***.*** ***@***.***>

**Comment by MichaelCondry** [comment]
List of files
[List of Files.pdf](https://github.com/files-community/Files/files/13980382/List.of.Files.pdf)
Search
[Search Result.pdf](https://github.com/files-community/Files/files/13980395/Search.Result.pdf)

**Comment by MichaelCondry** [comment]
Done

 

Shows list of Files.

 

Then

Search for ‘Girl” shows nothing found.

 

Please confirm you can see both images

 

Michael W. Condry, PhD, Life IEEE Fellow

IEEE IES, TEMS, Computer, and CTSoc

Chair, World Technology Summit

 ***@***.***> ***@***.***, ***@***.*** ***@***.***>

**Comment by yaira2** [comment]
It looks like that screenshot is from the stable version of Files, did you get a chance to test using the preview version? It contains some improvements for search and I'm curious if you notice a difference.

**Comment by MichaelCondry** [comment]
I did the preview version download. Is it a different icon?

 

Michael W. Condry, PhD, Life IEEE Fellow

IEEE IES, TEMS, Computer, and CTSoc

Chair, World Technology Summit

 ***@***.***> ***@***.***, ***@***.*** ***@***.***>

**Comment by yaira2** [comment]
The preview version has a blue icon
![image](https://github.com/files-community/Files/assets/39923744/a7ff86fd-1152-4950-9ade-b83f43a7c143)

**Comment by MichaelCondry** [comment]
Sorry, I did test the wrong one. The new one works!

 

Michael W. Condry, PhD, Life IEEE Fellow

IEEE IES, TEMS, Computer, and CTSoc

Chair, World Technology Summit

 ***@***.***> ***@***.***, ***@***.*** ***@***.***>

**Comment by MichaelCondry** [comment]
My mistake, the new one works for file search. Does it download pictures from the phone?

 

Michael W. Condry, PhD, Life IEEE Fellow

IEEE IES, TEMS, Computer, and CTSoc

Chair, World Technology Summit

 ***@***.***> ***@***.***, ***@***.*** ***@***.***>

**Comment by yaira2** [comment]
> Does it download pictures from the phone

It should but I've found it to be a little slow. That said, if you run into any issues, make sure to open a bug report so we can keep track.

**Comment by yaira2** [comment]
Are you referring to Auto Play?

**Comment by MichaelCondry** [comment]
NO. This is downloading pictures and videos from phone/tablet to your PC.   File Manager under Windows 10 does it perfect, you pick the target directory and ask it to organize by date taken.  It only uploads new files and sorts them into directories by date taken.

 

For folks like me, who makes home movies with photos and videos taken from multiple devices this is a great tool.  If windows 10 did it it must be possible. 

 

Michael W. Condry, PhD, Life IEEE Fellow

IEEE IES, TEMS, Computer, and CTSoc

Chair, World Technology Summit

 ***@***.***> ***@***.***, ***@***.*** ***@***.***>
