### ISSUE TITLE
Disable Smooth Scrolling

### ISSUE THREAD

**Issue by BoFiS** [files-community/Files#14483]
### What feature or improvement do you think would benefit Files?

Please add a setting to disable smooth scrolling throughout this app if possible, that one thing is what's keeping me using the Windows Explorer at this point.

### Requirements

- This proposal will accomplish getting rid of smooth scrolling when using a mouse wheel

### Files Version

3.1.1.0

### Windows Version

Edition	Windows 10 Pro Version	22H2 Installed on	‎06/‎08/‎2021 OS build	19045.3803 Experience	Windows Feature Experience Pack 1000.19053.1000.0

### Comments

Smooth scrolling is the worst, and should be able to be disabled

**Comment by Josh65-2201** [comment]
Thanks for the feedback, smooth scrolling is controlled by Windows and turned off there.

**Comment by yaira2** [comment]
> smooth scrolling is controlled by Windows and turned off there

Is there a setting?

**Comment by Josh65-2201** [comment]
The Windows animation effects setting should also turn off smooth scrolling. There an option for controlling animations Individually but I don't remember how to get to it.
