### ISSUE TITLE
Bug: Progress in Status Center is incorrect.

### ISSUE THREAD

**Issue by 443eb9** [files-community/Files#14488]
### Description

![PixPin_2024-01-18_20-43-04](https://github.com/files-community/Files/assets/50186452/3594b5ba-ddfe-4310-821d-6d77ef5b2368)

But the one in task bar is correct

![PixPin_2024-01-18_20-43-54](https://github.com/files-community/Files/assets/50186452/6e993173-9e6d-427e-8eaf-0cd9162f9fc4)

### Steps To Reproduce

Just delete a folder with many small files in it.

### Requirements

- Fix the incorrect progress display.

### Files Version

3.1.1.0

### Windows Version

Windows 11 Pro 23H2

### Log File

[debug.log](https://github.com/files-community/Files/files/13976737/debug.log)

**Comment by yaira2** [comment]
Thank you for the report, we're currently tracking this issue in #13860. You can add a comment or subscribe to be notified when it's resolved.
