### ISSUE TITLE
Change order of columns in details layout

### ISSUE THREAD

**Issue by emutter** [files-community/Files#14495]
### What feature or improvement do you think would benefit Files?

Would be nice to click and drag, or have an option to re-arrange the order of the columns shown in the details view. I prefer to have the size column be the first one shown next to the filename for easy comparisons especially if im in dual pane view, otherwise i have to scroll to the right to view the size in each pane.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.1.1.0

### Windows Version

10.0.19045.3930

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #8385. You can check there or click subscribe in the right sidebar for updates.
