### ISSUE TITLE
Files is running as administrator -  Due to platform limitations, drag and drop isn't available when running Files as administrator.

### ISSUE THREAD

**Issue by MATTPASSIONFORTECH** [files-community/Files#14498]
### Description

"I keep getting an error message whenever I try to open Files on my computer. This is preventing me from being able to drag and drop files, and it's becoming quite frustrating. Does anyone know of a workaround or a way to fix this bug? I want to find a solution to fix this issue. Keep in mind that using the Microsoft Store version of Files. Update: The same issues occur with Files Stable (Classic installer).

### Steps To Reproduce

How do I fix this?

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.1.1.0

### Windows Version

23H2 22631.3078

### Log File

https://github.com/files-community/Files/assets/157192867/19af60b6-9ec7-43ca-b013-eda64a273ef3

**Comment by Josh65-2201** [comment]
Thanks for the report. Make sure UAC (User Account Control) is not set to never notify.

**Comment by yaira2** [comment]
Thank you for your feedback, this is a limitation in WinAppSdk where drag & drop causes a crash when the app is running as admin. You can work around this limitation by re-enabling UAC on your device.

**Comment by ThisIsDelicious** [comment]
> Thank you for your feedback, this is a limitation in WinAppSdk where drag & drop causes a crash when the app is running as admin. You can work around this limitation by re-enabling UAC on your device.

There has to be a better way to prevent Files from running as Administrator. Enabling UAC is quite extreme. I'm still looking for a solution.

**Comment by Josh65-2201** [comment]
There isn't, With UAC off Windows will open everything as admin, same as if you right clicked > run as admin

**Comment by ThisIsDelicious** [comment]
> There isn't, With UAC off Windows will open everything as admin, same as if you right clicked > run as admin

That's unfortunate. Thanks for the info, I wasn't aware.

**Comment by yaira2** [comment]
Microsoft recently announced they are working on a fix for drag and dropping tabs. This is certainly a good step in the right direction, and it gives us hope that it will be fixed for other drag & drop scenarios as well.

**Comment by Iomegan** [comment]
Months have passed, but looks like the bug still persists. :(

**Comment by 0x5bfa** [comment]
FWIW, when your user account is part of Administrators group (it's by default from OOBE) and UAC is completely disabled, a certain Windows drag and drop handler still misunderstands that the app is running as privileged process token.

We [already worked on the preparation](https://github.com/files-community/Files/pull/16156) to be able to enjoy that fix/update Microsoft made but there's an increase crash in that version and we're waiting for further updates.

**Comment by gigend** [comment]
my windows is always as admin, any suggestion without enabling the UAC?

**Comment by Josh65-2201** [comment]
There isn't right now https://github.com/files-community/Files/issues/14498#issuecomment-2081823077

**Comment by minh-tonny** [comment]
I’m also encountering the same error as the original poster. Can someone guide me on how to fix it? I’ve customized the UAC as shown in the image (attached). Thank you!

![Image](https://github.com/user-attachments/assets/99839607-61d3-4077-a7e8-45cb9dc4bc05)
![Image](https://github.com/user-attachments/assets/3a705cb0-19fc-4559-bd8c-b9bc89e725f3)

**Comment by 0x5bfa** [comment]
How did you create the current user? Is it from the installation?

**Comment by 0x5bfa** [comment]
That is weird, I was wondering if you enabled Built-in Administrator, which is not a standard admin user but a super user, but apparently you didn't have it enabled and use it.

However, we check whether Files running as admin  in the very appropriate way.

- What we use (via a wrapper in C# that uses the windows api)
  - https://github.com/files-community/Files/blob/edeba8947aa160907b3e4f1a970ab3c748483ec3/src/Files.App/Services/Windows/WindowsSecurityService.cs#L14
  - https://github.com/dotnet/runtime/blob/6d344b35ff02e416304d7d25a8afb51b25d56c38/src/libraries/System.Security.Principal.Windows/src/System/Security/Principal/WindowsPrincipal.cs#L124-L130
- How Microsoft Terminal does (via the windows API)
  - https://github.com/microsoft/terminal/blob/3760caed97fa9140a40777a8fbc1c95785e6d2ab/src/types/utils.cpp#L1006

---

Can you check:
- if it fixes after restarting?
- how Windows Terminal shows when you only launch it, does it have a shield icon at the right top?

**Comment by minh-tonny** [comment]
Thank you for your response. I have thoroughly investigated the Built-in Administrator account.

1. Status of the Built-in Administrator Account:
   - I confirmed the status using the `net user Administrator` command in Command Prompt, and it shows "Account active: Yes" and "Password required: Yes,"
   - I also checked the account properties in lusrmgr.msc, where the "Account is disabled" checkbox is not checked, confirming the account is enabled.
2. I tested Windows Terminal, and I noticed the following:
  - When I launch Windows Terminal normally (left-click) in my standard admin account, it does not show a shield icon, which is expected as it runs without Administrator privileges.
  - However, when I launch Windows Terminal with Administrator privileges (right-click > Run as Administrator), the shield icon **still does not appear** (it remains colorless or is not visible at all).

![Image](https://github.com/user-attachments/assets/210c4e03-9713-4173-9fa9-2e519bbaa428)

**Comment by Josh65-2201** [comment]
The terminal image shows that your are running it as admin and on the built in Admin account. This account isn't supported and shouldn't be used, you will have to make a new normal account and switch to that if you want to use drag and drop.

**Comment by minh-tonny** [comment]
@0x5bfa Yes, it's true that I took a screenshot in admin mode.

**Comment by minh-tonny** [comment]
@yaira2 @Josh65-2201 Thank you very much

**Comment by Josh65-2201** [comment]
You can use an account that has admin access

**Comment by 0x5bfa** [comment]
@minh-tonny Can you check Task Manager > Details > Add a column for Elevated > see if `files.exe` has No. it's pretty weird that that dialog pops up.

**Comment by minh-tonny** [comment]
C

![Image](https://github.com/user-attachments/assets/e2873bab-d19c-4998-8635-c205c6dfe92d)
![Image](https://github.com/user-attachments/assets/489bf7d8-ecf1-49d8-81c4-5464a5396750)
![Image](https://github.com/user-attachments/assets/75f32178-3819-44a0-8049-07139b97b1b0)

ould everyone please guide me on how to create a user account? When I go to Settings / Accounts / Other Users / Add Account, a dialog box titled 'Local User and Group (local)' appears.

**Comment by Josh65-2201** [comment]
Right click `User` > New User > Enter name > OK > Close. If you want to add it to the admin group you can do that through the Other users page
