### ISSUE TITLE
Bug: Exiting from the system tray icon does not save the tabs

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#14493]
### Description

Exiting from the system tray icon when the app is in the background will only open the Home tab at the next launch, even if the startup setting is "Continue where you left off".

### Steps To Reproduce

1. Turn "Leave app running" on and set the startup setting to "Continue where you left off".
2. Open some tabs.
3. Close the app.
4. Exit the app form the system tray.
5. Start the app.
6. Observe only the Home tab is displayed.

### Requirements

The tabs that were open when the app was closed should be opened.

### Files Version

3.1.1.0

### Windows Version

10.0.22631.3007

### Log File

No noteworthy logs are output.

**Comment by yaira2** [comment]
Sounds like a regression, I’m pretty sure this worked in the original implementation. FYI @0x5bfa

**Comment by hishitetsu** [comment]
It may be due to my modifications. I'll take a look later.
