### ISSUE TITLE
Feature: When opening a new tab focus file list for tab selection first

### ISSUE THREAD

**Issue by rhlobo** [files-community/Files#14490]
### What feature or improvement do you think would benefit Files?

As the title implies, tabs and panels start unfocused, requiring mouse interaction to initially select a file so that I can resume/start keyboard navigation.

Although I have a mouse, I am mostly an shortcut/keyboard user, and the current behaviour for Files is far less fluent than if using Windows Explorer.

### Requirements

- When opening an tab or panel, pressing the arrow keys allow you to start navigating files instantly

### Files Version

3.1.1.0

### Windows Version

10.0.19045.3930

**Comment by rhlobo** [comment]
Currently, when the program starts, using the arrow keys cicle in tabs (between the initial tab name and the + for new tab creation)
![image](https://github.com/files-community/Files/assets/1222130/fe6a4080-3d43-4073-8500-d36eaf94a737)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
Thanks for the report, we're currently tracking this issue in #13774. You can add a comment or click subscribe to be notified when it's fixed.
