### ISSUE TITLE
JumpList Support

### ISSUE THREAD

**Issue by Unreasonable-User** [files-community/Files#14492]
### What feature or improvement do you think would benefit Files?

Completes feature parity with vanilla explorer. It's another usability option.

![image](https://github.com/files-community/Files/assets/36458737/311a40bf-721f-4ab5-a14f-75a7c433953e)

### Requirements

I don't know anything about actually coding

This maybe?

https://learn.microsoft.com/en-us/uwp/api/windows.ui.startscreen.jumplist?view=winrt-22621

### Files Version

3.1.1.0

### Windows Version

10.0.19045.3930

**Comment by yaira2** [comment]
Thanks for the feedback, Files already has jump list support. Can you clarify the request?

**Comment by Unreasonable-User** [comment]
If I right click on File Explorer in the taskbar I get a jump list filled with my quick access pinned items.
![image](https://github.com/files-community/Files/assets/36458737/0a90b7ac-7466-4664-81b0-2f665cf958b9)

If I right click on Files in the taskbar I get not really a jump list, just access to home in Files.
![image](https://github.com/files-community/Files/assets/36458737/3b64db7a-c43a-427f-9601-55b2ba1192c3)

Same holds true in the Start Menu.

I've tried running Files as admin and I don't see the setting if it's there, so I drew the conclusion that JumpLists just weren't supported at all.

I hope that clarification is useful, I apologize if I missed something.

**Comment by yaira2** [comment]
This appears to be a bug as pinned items are displayed on my end. Can you open a bug report so we can investigate the issue?
