### ISSUE TITLE
"The system cannot find the file specified"

### ISSUE THREAD

**Issue by KaKi87** [files-community/Files#14507]
### Description

The following error is thrown when trying to install the app using `Files.Stable.exe` :

> The system cannot find the file specified.

### Steps To Reproduce

1. Download https://cdn.files.community/files/download/Files.Stable.exe ;
2. Execute `Files.Stable.exe` ;
3. Click *Yes* on UAC prompt ;
4. Click *Install* ;
5. See error.

### Requirements

Installation succeeds.

### Files Version

3.1.1.0

### Windows Version

Windows 10 Pro 22H2 19045.2965

### Log File

No log since no install.

### Screenshot
![Recording 2024-01-21 at 14 52 03](https://github.com/files-community/Files/assets/21284089/29c9983b-58a4-4349-af86-714a527ea640)

**Comment by Josh65-2201** [comment]
Have you install a unofficial (like Atlas OS) or modified (like disabled windows update, removed the Microsoft store, used a debloat program/script etc.) version of Windows?

**Comment by KaKi87** [comment]
Actually I tried the normal user approach first : download https://cdn.files.community/files/stable/Files.Package.appinstaller in browser and double-click it.

It works fine !

So, please please provide that file instead, like it used to be before.

And yes I'm using Revi and have disabled everything.

**Comment by KaKi87** [comment]
Will you please use this link instead of the one that fails in the website so that people will no longer run into this ?

Thanks

**Comment by Josh65-2201** [comment]
There aren't plans right now to remove the installer on the website. The installer on the website is usually more reliable then Microsoft's app installer but both aren't perfect and people will have different things that work.

**Comment by KaKi87** [comment]
How about adding it as an "alternative" ?

**Comment by intothefirelilith** [comment]
none of the methods work for me, is there a normal installer that dont use anything from microsoft store?

**Comment by KaKi87** [comment]
> none of the methods work for me

Could you please be more specific ?

> is there a normal installer that dont use anything from microsoft store?

Being a UWP app is the reason of it for existing, so it can't not be an APPX.

However, APPX are installable without Microsoft Store, so you must have another problem.
