### ISSUE TITLE
Feature Request: Sort Videos by Length, and Undo Function

### ISSUE THREAD

**Issue by ialhabbal** [files-community/Files#14502]
### What feature or improvement do you think would benefit Files?

Thanks for the great program. Would be greatly helpful if you would add the possibility to sort video files by Length in addition to what's currently available. Also adding an Undo function for actions like delete, move, copy similar to what's available on Windows File Explorer on Windows 11.

### Requirements

- Adding Sort by Length will enable sorting of large database of video files by length
- Adding an Undo function will enable accidental moving, copying, or deleting files

### Files Version

3.1.1.0

### Windows Version

Windows 11 23H2 (22631.3007)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #8366. You can check there or click subscribe in the right sidebar for updates.

Undo is already available using `Ctrl + Z`
