### ISSUE TITLE
Feature: Add separate tab row to each pane

### ISSUE THREAD

**Issue by 82513931** [files-community/Files#14516]
### What feature or improvement do you think would benefit Files?

Right now it seems to only be possible to open a dual pane within a tab but speaking for my own workflow it would be better / simpler with having tabs within the 2 panes separately. I believe OneCommander does it like that if I recall right & would be good to look at for inspiration in regards to how the dual pane + tabs is handled.

### Requirements

- This proposal will accomplish better Workflow for some people like myself.
- This proposal will accomplish more features for Files.
- This proposal will accomplish a cleaner look.

### Files Version

3.1.1.0

### Windows Version

11

**Comment by Josh65-2201** [comment]
Thanks for the feedback, I've added this to the project board.

**Comment by yaira2** [comment]
Thanks for the feedback, we're tracking this feedback in #14377 (the issue highlights the path bar but it's not limited to it). You can add a comment or click subscribe in that issue to be notified of updates.
