### ISSUE TITLE
Custom Categories for Tags in the Sidebar

### ISSUE THREAD

**Issue by 82513931** [files-community/Files#14514]
### What feature or improvement do you think would benefit Files?

I think it would be great if you were able to add custom categories in the Sidebar for tags so you can group them in different categories.
![image](https://github.com/files-community/Files/assets/157329627/55610e0b-cf57-47d5-a01b-bbdcf06cbaec)

### Requirements

- This proposal will accomplish better Navigation
- This proposal will accomplish better Sorting
- This proposal will accomplish better Grouping

### Files Version

3.1.1.0

### Windows Version

11

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #12738. You can check there or click subscribe in the right sidebar for updates.
