### ISSUE TITLE
Bug: Crash when opening properties of a deleted file from "Recent Files"

### ISSUE THREAD

**Issue by Tamnac** [files-community/Files#14512]
### Description

Deleted files still show in the "Recent Files" widget (possibly separate issue) but when I as an unaware user try to open the properties of one, the whole app crashes with the notification "Something went wrong!"

### Steps To Reproduce

1. Open/create some file so it shows up in recent files
2. Delete said file
3. Try to access file's properties from "Recent Files" widget

### Requirements

Fix crash upon opening properties. Instead the app show indicate the file has been deleted and remove it from recents.

### Files Version

3.1.1.0

### Windows Version

10.0.22631.3007

### Log File

[debug.log](https://github.com/files-community/Files/files/14003759/debug.log)

**Comment by yaira2** [comment]
> Deleted files still show in the "Recent Files" 

Is the item visible in File Explorer?

**Comment by yaira2** [comment]
The item is supposed to be removed from the recent file list when it's deleted 🤔

**Comment by yaira2** [comment]
I've seen the reports in App Center but I haven't been able to repro the issue myself. It probably depends on whatever other operations File Explorer is working on at the time.

**Comment by yaira2** [comment]
I found this can happen with removable storage devices
