### ISSUE TITLE
Feature: Add drag region gap to right when tab row is full

### ISSUE THREAD

**Issue by mrmakethewatergofresh** [files-community/Files#14517]
### What feature or improvement do you think would benefit Files?

So, as with every Windows program, you can usually use the uppermost bar to move things around and reorder them. It works with Files too, unless... you got too many tabs open. No matter where you grab, you will always end up selecting a tab or a button. No area to grab and drag is left. That's super annoying because you either have to enlarge (stretch) the window to be able to move it around or close tabs.

### Requirements

- This proposal will accomplish a reliable grab & drag function

### Files Version

3.0.8.0

### Windows Version

10.0.19045.3930

**Comment by Josh65-2201** [comment]
Thanks for the feedback, I've added this to the project board.
