### ISSUE TITLE
Window size resets when computer is restarted

### ISSUE THREAD

**Issue by RhapsodySL** [files-community/Files#14513]
### Description

Restarting my computer after having changed the size of the window causes the window's size to reset next time the application is opened.

### Steps To Reproduce

1. Open Files, change size of window
2. Fully restart computer
3. Open Files, the window will have reset to its default size

### Requirements

Expected behavior is that the window stays at the specified size.

### Files Version

3.1.1.0

### Windows Version

10.0.22635.3061

### Log File

[debug.log](https://github.com/files-community/Files/files/14004245/debug.log)

**Comment by yaira2** [comment]
Thanks for the report, we're currently tracking this issue in #14192. You can add a comment or click subscribe to be notified of updates.
