### ISSUE TITLE
Bug: Opening tag from sidebar always opens in Details View

### ISSUE THREAD

**Issue by 82513931** [files-community/Files#14511]
### Description

When you click on a Tag in the Sidebar it always opens into a Column view of the tagged files regardless of whats set under Global Preferences.

### Steps To Reproduce

1. Turn on option to sync folder preferences
2. Set default layout to Grid
3. Click tag on the sidebar and see that it opens using Details

### Requirements

- Use the correct layout

### Files Version

Latest

### Windows Version

11

### Log File

[debug.log](https://github.com/files-community/Files/files/14003437/debug.log)

**Comment by yaira2** [comment]
Which version of Files are you using? "Latest" can mean different things to different people 🙂

**Comment by 82513931** [comment]
> Which version of Files are you using? "Latest" can mean different things to different people 🙂

3.1.1.0 Downloaded from the Microsoft Store on 21/01/2024.

**Comment by yaira2** [comment]
This will be resolved in the next release
