### ISSUE TITLE
Feature: Hover-scrub on the Thumbnail of Video-Files

### ISSUE THREAD

**Issue by keppn** [files-community/Files#14518]
### What feature or improvement do you think would benefit Files?

- Please include hover-scrub on the Thumbnail of Video-Files
- Please include an option to Auto-Playback Videos in the Preview Panel
- Please include an option to Auto-Open / Auto-Close the Preview Panel when an image or video is selected

### Requirements

- This proposal will make it very easy to manage video files with Files

### Files Version

3.1.1.0

### Windows Version

22631.3007

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Please open separate request for different feedback.

> Please include an option to Auto-Playback Videos in the Preview Panel

This isn't planned currently. https://github.com/files-community/Files/issues/12879#issuecomment-1704395870

> Please include an option to Auto-Open / Auto-Close the Preview Panel when an image or video is selected

Please open a new request for this

**Comment by yaira2** [comment]
Is this supported by File Explorer? Files uses the same thumbnailing system as File Explorer so it's subject to the same limitations.

**Comment by keppn** [comment]
> Is this supported by File Explorer? Files uses the same thumbnailing system as File Explorer so it's subject to the same limitations.

No, Hover-Scrubbing of Video Files is not supported by File Explorer. It's a feature commonly found in Digital Asset Managers like  Adobe Bridge, Eagle.app or Aalab's Found.

**Comment by yaira2** [comment]
Thanks for the response, I know this isn't the response you were hoping for, but this is currently out of scope for our plans for Files. 

Building a custom thumbnailing system that can support the many different file formats is a large undertaking and we just don't have the resources to do this. It's possible that we can revisit this in the future, but I wanted to be transparent regarding this request.

**Comment by keppn** [comment]
Thanks for explaining!
