### ISSUE TITLE
Bug: Crash with List View layout

### ISSUE THREAD

**Issue by Mantej-Singh** [files-community/Files#14521]
### Description

The app crashes when I use the List View layout on the latest preview version 3.1.4.0, but only if the window is maximized. My folder contains more than 1000 files.

### Steps To Reproduce

1. open a folder with multiple files
2. change the layout to List
3. make sure app window is maximized 

### Requirements

when you maximize the window with list view on

### Files Version

3.1.4.0

### Windows Version

10.0.23619.1000

### Log File

[debug.log](https://github.com/files-community/Files/files/14014711/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
Does the layout change to list or does it crash right away?

**Comment by Mantej-Singh** [comment]
It does change to list view.
Once the list view is applied, it crashed after 2-3 seconds

**Comment by yaira2** [comment]
Unfortunately the log file doesn't contain any info about the crash. Can you upload a screen recording?

**Comment by Mantej-Singh** [comment]
Yeah I figured, it was only 10kb.
Let me work on a screen recording

**Comment by Mantej-Singh** [comment]
Would you like a crash dump? 
I found it on my C:\Users\Mark-VI\AppData\Local\CrashDumps folder

**Comment by Mantej-Singh** [comment]
@yaira2 
here is video 

https://github.com/files-community/Files/assets/19365795/58eb81c6-5e51-4242-b6d1-e504b2facbb9

**Comment by yaira2** [comment]
Interesting, does it also crash if you maximize the window before switching to List View?

**Comment by Mantej-Singh** [comment]
yes.

**Comment by Mantej-Singh** [comment]
It only happens to folders with a lot of files

**Comment by yaira2** [comment]
I can repro this as well

**Comment by Mantej-Singh** [comment]
I appreciate you working on this. 
Did you figure out what the issue is?

**Comment by Mantej-Singh** [comment]
Thanks @marcelwgn

**Comment by Mantej-Singh** [comment]
@yaira2
When will the fix be available in the preview version?

**Comment by Josh65-2201** [comment]
It's in 3.1.6 right now

**Comment by Mantej-Singh** [comment]
thanks, updating it now.
![image](https://github.com/files-community/Files/assets/19365795/d7b56a2d-36ef-4d7e-8871-a820e3a8ab37)

**Comment by Mantej-Singh** [comment]
ahh guys, 
the whole app is freezing I am unable to access any file 
![image](https://github.com/files-community/Files/assets/19365795/972371d7-9563-47dd-9c3a-7f4659b5a584)

App Version: 3.1.6.0
Windows version: 10.0.23619.1000

**Comment by ElQuia345** [comment]
It is happening to me on 3.1.7.0 Windows 10.0.19045.3996, without changing windows size, I select list view. If folder has 95 items nothing happens. If it has 330 items it crashes when I change in to it

**Comment by Mantej-Singh** [comment]
I tested @hishitetsu patch and it is working fine.
![image](https://github.com/files-community/Files/assets/19365795/f4101e62-c28a-40af-b907-cd623b4bae55)

**Comment by ElQuia345** [comment]
> I tested @hishitetsu patch and it is working fine. ![image](https://private-user-images.githubusercontent.com/19365795/300183400-f4101e62-c28a-40af-b907-cd623b4bae55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNzkyNjgsIm5iZiI6MTcwNjM3ODk2OCwicGF0aCI6Ii8xOTM2NTc5NS8zMDAxODM0MDAtZjQxMDFlNjItYzI4YS00MGFmLWI5MDctY2Q2MjNiNGJhZTU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDE4MDkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0YTRiNjNlMzU1MTRkNjMwYjFhY2YxMGU0ZDU1OGMxYjNmZmU5ZmI1ZDk0ZTY4MmM0MzZkM2M1ZDVlZjU1NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NhylOEnZJEGELi9o7izPaiw1PbQIf25uEz8TP9uwOE8)

Is the patch downloadable and does it work on 3.1.7.0?

**Comment by Josh65-2201** [comment]
No, It's not available yet.

**Comment by ElQuia345** [comment]
> No, It's not available yet.

OK, will wait...  the list feature was one of the few things missing that stopped me from going default with Files..
BTW, it WOULD be nice if when in two pane mode, the divisor line between panes was more visible, thicker, aka some two pane file managers.... as it is it gets kind of confusing, not a problem, just hard on eyes
LOVE the work. Thanks

**Comment by yaira2** [comment]
Thanks for the feedback, this issue will be resolved in the next release.

**Comment by Mantej-Singh** [comment]
Crashing on 3.1.7.0. 
Is the fix pushed to 3.1.7.0 build?

![image](https://github.com/files-community/Files/assets/19365795/708eb402-1f77-4de3-bcf6-13f2ea444a57)

**Comment by hishitetsu** [comment]
No, you will have to wait until the next preview release (probably 3.1.8.0).

**Comment by Mantej-Singh** [comment]
Understandable, thanks.
