### ISSUE TITLE
Feature: Add support for jfif files to be set as wallpaper

### ISSUE THREAD

**Issue by AB10110F** [files-community/Files#14527]
### What feature or improvement do you think would benefit Files?

Jfif files are currently not supported to be set as wallpaper through Files App, It might be handy for people with pictures having that extension

### Requirements

- Since it is already available on the default file explorer, it will get the Files App closer to fully substitute it

### Files Version

3.1.1.0

### Windows Version

Windows 10

**Comment by Josh65-2201** [comment]
Thanks for the feedback, I've added this to the project board.

**Comment by yaira2** [comment]
Thanks for the feedback, this feature will be included in the next release.
