### ISSUE TITLE
Application date format not corresponded with selected format in settings

### ISSUE THREAD

**Issue by osieltorres** [files-community/Files#1452]
**Describe the bug**

**To Reproduce**
1. Go to Appearance settings
2. Click on Date format and select "System" option
4. When return to list of files and folders, some appears with date base in "Application" option, and some on selected "System" option.

**Expected behavior**
Date for files and folders should be formatted to selected option in Appearance settings.

**Screenshots**
![2020-07-14_115148](https://user-images.githubusercontent.com/3835402/87447522-af18f180-c5c8-11ea-9881-0a2916401925.png)
![2020-07-14_115321](https://user-images.githubusercontent.com/3835402/87447526-b04a1e80-c5c8-11ea-8de6-f337e719716d.png)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 2004 19041.329]
 - App version: [v0.12.0]

**Comment by Thomas1664** [comment]
I can confirm that issue. The changed date format is applied to none of the list items. The same bug appears in properties as well

**Comment by yaichenbaum** [comment]
This issue should be fixed with #2092.
