### ISSUE TITLE
Add the ability to change the column sequence in details view

### ISSUE THREAD

**Issue by snruebes** [files-community/Files#14531]
### What feature or improvement do you think would benefit Files?

Add the ability to change the column sequence in details view. The Windows File Explorer offers this option to change the sequence  of the columns in its details few. I like to have the freedom to change it to fit my needs. Would be awesome if you would implements this feature in files as well.

### Requirements

No special requirements

### Files Version

3.1.4.0

### Windows Version

10.0.22631.3007

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in https://github.com/files-community/Files/issues/8385. You can check there or click subscribe in the right sidebar for updates.
