### ISSUE TITLE
Add back the theming

### ISSUE THREAD

**Issue by jbugel-lol** [files-community/Files#14538]
### What feature or improvement do you think would benefit Files?

So yea please bring back the old theming 🙏🏻 

### Requirements

- This proposal will accomplish that all community made themes including my [favourite](https://github.com/catppuccin/windows-files) can still work

### Files Version

v3.1.1.0

### Windows Version

10.0.22631 Build 22631

### Comments

🙏🏻

**Comment by Josh65-2201** [comment]
Thans for the feedback, for theming follow the instructions at https://files.community/docs/configuring/custom-themes
and for that theme some has already showing what you need to change the values too. https://github.com/catppuccin/windows-files/issues/7#issuecomment-1793233936

**Comment by yaira2** [comment]
Thank you for your feedback, Files has a decent selection of built-in themes but if what you're looking for isn't already built-in, you can easily create your own in a couple of minutes by following the instructions in the link Josh shared.

**Comment by jbugel-lol** [comment]
alright ty guys
