### ISSUE TITLE
Windows PowerToys – Peek Utility

### ISSUE THREAD

**Issue by sichtmonitor** [files-community/Files#14549]
### What feature or improvement do you think would benefit Files?

It would be amazing if the peek utility provided by Microsoft PowerToys (enables a MacOS-like file preview by hitting ctrl+space or custom keyboard shortcut) could be enabled in Files. For now it only works in the explorer.

### Requirements

- implement Peek Utility

### Files Version

3.1.1.0

### Windows Version

10.0.22631.3007

**Comment by yaira2** [comment]
Thank you for your feedback, we're ready to add this feature to Files but PowerToys doesn't have an API that'll enable us to do this. I opened an issue on the PowerToys repo to start the discussion on creating an api for third party file managers https://github.com/microsoft/PowerToys/issues/26422
