### ISSUE TITLE
Bug: The 'Drives' widget displays inaccurate information about free space on drives.

### ISSUE THREAD

**Issue by rpk90** [files-community/Files#14542]
### Description

When you move, copy, or delete files, the 'Drives' widget on the 'Home' page does not update information about free space on the disks.

### Steps To Reproduce

1. Open 'Files' and select a drive.
2. Copy, move (to another drive), or delete files.
3. Navigate to the 'Home' page and check the free space on the selected drive.
4. Compare it with the free space displayed in Windows Explorer or Windows Settings.
5. Bug: The 'Drives' widget shows inaccurate information about free space on drives.

### Requirements

The 'Drives' widget displays accurate information about free space on drives.

### Files Version

3.1.1.0

### Windows Version

10.0.19045.3930

### Log File

![space_drives_widget](https://github.com/files-community/Files/assets/43038558/2ee99dfb-83d1-4a05-b83a-2a1ff124ff20)
![space_drives_explorer](https://github.com/files-community/Files/assets/43038558/d95d612c-31bf-4fad-8cbe-3beb45ee7e5e)
![space_drives_settings](https://github.com/files-community/Files/assets/43038558/c2770fb3-1de4-4f4e-8e29-ceb797fef2e8)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #6182 . You can check there or click subscribe in the right sidebar for updates.
