### ISSUE TITLE
Restore Folders and Tabs and History for Folders and Tabs

### ISSUE THREAD

**Issue by Dennis-AS** [files-community/Files#14545]
### What feature or improvement do you think would benefit Files?

Hello,

I have "Startup settings" set to "Continue where you left off" but occasionally, because of a crash or some other reason, it will not continue where I left off.
It would be good to have a way to recover from these incidents and I can think of two things that would help.

1. Edge and other browsers will usually detect if the browser did not close properly and will display a message on startup like "The browser closed unexpectedly, would you like to restore your previous session or continue with your startup tabs?" and will have Restore and Startup buttons (or something similar, I am going from memory). Please add the same feature to the Files app.
2. Please add a History menu to the Files app so we can manually restore individual tabs or a group of tabs when necessary.

Thanks

Dennis

Here are my Windows specifications from Windows Settings:
Edition	Windows 11 Enterprise
Version	23H2
Installed on	‎9/‎20/‎2022
OS build	22631.3085
Experience	Windows Feature Experience Pack 1000.22684.1000.0

### Requirements

- This proposal will allow users to "Continue where they left off" even in those instances where the Files app did not close properly.

### Files Version

3.1.1.0

### Windows Version

10.0.22631.3085

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #12624. You can check there or click subscribe in the right sidebar for updates.

**Comment by Josh65-2201** [comment]
The preview version also has a fix to make it more reliable when closing normally. https://files.community/download
