### ISSUE TITLE
Install Failed

### ISSUE THREAD

**Issue by kaufmanj1973** [files-community/Files#14553]
### Description

Tried installing from the downloaded installation .exe.  I get a message stating "Install failed. Please contact your software vendor."

![Files Error Msg](https://github.com/files-community/Files/assets/16485150/1ec5a8a7-06d7-4bf6-bf1a-bfbccbb76432)

### Steps To Reproduce

Tried installing multiple times, got the exact same error message.

### Requirements

I expected the software to install and be able to function without error messages.

### Files Version

3.1.1.0

### Windows Version

Windows 11 Pro Version	21H2 Installed on	‎10/‎25/‎2021 OS build	22000.2538 Experience	Windows Feature Experience Pack 1000.22001.1000.0

### Log File

![2024-01-25 14_57_22-Adobe Illustrator 2024](https://github.com/files-community/Files/assets/16485150/53e4210c-f19e-40d7-810d-bbba6c3691a1)

There is no directory matching the name you ask for.  I'm attaching the directory list to show that what you're asking for doesn't exist.

**Comment by Josh65-2201** [comment]
Thanks for the report, unfortunately that's caused by Windows, can you try
    1. Opening PowerShell as administrator
    2. Run this command
    ```Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/stable/Files.Package.appinstaller```
    3. See if Files is in the start menu all apps section

**Comment by kaufmanj1973** [comment]
Yes, that installation worked.  Still can't use it, though, because now my computer's drives don't display.  Should have a C, D, E, and F on there. Ugh.  I wish Microsloth would just abandon the current Explorer code and rebuild it from the ground up.

![image](https://github.com/files-community/Files/assets/16485150/ab376bd9-e373-41fb-b6ef-98f3e88577e4)

**Comment by justin-a30** [comment]
> Thanks for the report, unfortunately that's caused by Windows, can you try 1. Opening PowerShell as administrator 2. Run this command `Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/stable/Files.Package.appinstaller` 3. See if Files is in the start menu all apps section

Hello,

Thank you! this is working for me on Windows 10 22H2.
Everything seems working perfectly.
![image](https://github.com/files-community/Files/assets/51263008/51ff1c15-863b-4478-9d58-7c58891eb238)
