### ISSUE TITLE
Everytime I start files app (preview or stable channel) a terminal window from wsl opens up and it's very annoying and happening since a long time

### ISSUE THREAD

**Issue by Fefedu973** [files-community/Files#14558]
### Description

Everytime I start files app (preview or stable channel) a terminal window from wsl opens up and it's very annoying and happening since a long time

### Steps To Reproduce

1. Start files app
2. See the terminal window
![image](https://github.com/files-community/Files/assets/80718477/a77ae384-bf76-4c48-825d-c6958dfd94a8)

### Requirements

Happening everytime

### Files Version

3.1.7.0

### Windows Version

10.0.26020.1000

### Log File

[debug.log](https://github.com/files-community/Files/files/14068739/debug.log)

**Comment by Fefedu973** [comment]
uninstalling wsl fixes the issue. Maybe this is related to the fact that a wsl shortcut is on the sidebar on the classic file explorer and when files starts it tries to put this shortcut idk...

**Comment by Josh65-2201** [comment]
Thanks for the update on how you fixed the issue.

**Comment by yaira2** [comment]
It's been a while since I've used WSL but at the time it didn't have this issue. If anyone is able to repro this, please let us know so that we can investigate the issue.
