### ISSUE TITLE
Bug: Path icons are sometimes blurry

### ISSUE THREAD

**Issue by Fefedu973** [files-community/Files#14556]
### What feature or improvement do you think would benefit Files?

Changing this icon to something more like the other one provides a more coherent and design across the app

### Requirements

- Change the icon because first it is not displayed correctly and it looks bad and second because it is a bit off compared to the other ones
![image](https://github.com/files-community/Files/assets/80718477/12c8e174-d3c6-4451-98b9-051472891d72)

### Files Version

3.1.7.0

### Windows Version

10.0.26020.1000

**Comment by Josh65-2201** [comment]
Thanks for the report, are you talking about the list view icon being blurry?

**Comment by Fefedu973** [comment]
yes for exemple and not scaled proprely comapred to the other ones

**Comment by yaira2** [comment]
Thanks for the report, this issue comes down to the way XAML renders path icons and affects more than just the List View icon. For example, on my device it's the Details View icon that renders poorly, and List Layout is fine.
![image](https://github.com/files-community/Files/assets/39923744/e23e081c-8861-4e3c-8748-2a42a8da4641)

**Comment by Fefedu973** [comment]
Okay ! but i think it is still a bit too big compared to the others but idk

**Comment by yaira2** [comment]
I'll keep this open for now to track if there is any progress, but it might need some fixes from WinUI. We've tried different ways of rendering the path icons (with canvas, view box etc) but so far we haven't found any way that scales properly.

**Comment by Jay-o-Way** [comment]
@Fefedu973 what is the scale setting for your display?

**Comment by Fefedu973** [comment]
100%

**Comment by yaira2** [comment]
Thank you for your feedback, this is a regression in the way WinAppSdk renders path icons. We'll keep looking for a workaround, but we encourage you to report this in the WinUI repository so they can take your feedback into account. https://github.com/microsoft/microsoft-ui-xaml

An easy way to repro the regression is to follow these steps
1. Set screen scaling to 175%
2. Add this xaml to a blank page and compare WinAppSdk to UWP
```xml
<Canvas
    Width="28"
    Height="28"
    HorizontalAlignment="Center"
    VerticalAlignment="Center">
    <Path
        x:Name="Path1"
        Data="M5.25 10C4.55964 10 4 10.5596 4 11.25V15.75C4 16.4404 4.55964 17 5.25 17H9.75C10.4404 17 11 16.4404 11 15.75V11.25C11 10.5596 10.4404 10 9.75 10H5.25Z"
        Fill="white" />
    <Path
        x:Name="Path2"
        Data="M12 11.25C12 10.0074 10.9926 9 9.75 9H5.25C4.00736 9 3 10.0074 3 11.25V15.75C3 16.9926 4.00736 18 5.25 18H9.75C10.9926 18 12 16.9926 12 15.75V11.25ZM5.25 10.5H9.75C10.1642 10.5 10.5 10.8358 10.5 11.25V15.75C10.5 16.1642 10.1642 16.5 9.75 16.5H5.25C4.83579 16.5 4.5 16.1642 4.5 15.75V11.25C4.5 10.8358 4.83579 10.5 5.25 10.5Z"
        Fill="Black" />
    <Path
        x:Name="Path3"
        Data="M14.75 10.5C14.3358 10.5 14 10.8358 14 11.25C14 11.6642 14.3358 12 14.75 12H24.25C24.6642 12 25 11.6642 25 11.25C25 10.8358 24.6642 10.5 24.25 10.5H14.75Z"
        Fill="Black" />
    <Path
        x:Name="Path4"
        Data="M14.75 14.5C14.3358 14.5 14 14.8358 14 15.25C14 15.6642 14.3358 16 14.75 16H21.25C21.6642 16 22 15.6642 22 15.25C22 14.8358 21.6642 14.5 21.25 14.5H14.75Z"
        Fill="Black" />
</Canvas>
```

**Comment by yaira2** [comment]
@Fefedu973 this has been confirmed to be an issue in the WinUI framework and I opened an issue on their GitHub repo https://github.com/microsoft/microsoft-ui-xaml/issues/9338. Please consider contributing to the conversation by sharing with Microsoft how this issue impacts your experience with the Files app.
