### ISSUE TITLE
Bug: Quick access and drives on the home page are sometimes shown multiple times

### ISSUE THREAD

**Issue by hijiro-gthb** [files-community/Files#14555]
### Description

All quick access items will be displayed in duplicate.

![Files - quick access items are duplicated](https://github.com/files-community/Files/assets/157790562/8bffb51e-748c-444b-a570-8da0bbbe8e47)

### Steps To Reproduce

It happens just by starting it.

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.1.6.0

### Windows Version

10.0.19045.3996

### Log File

[debug.log](https://github.com/files-community/Files/files/14062015/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
Does this also occur if you turn off the option to "keep Files running in the background"?

**Comment by hijiro-gthb** [comment]
Sorry for the delay in response.
The relevant option was on, so I tried turning it off and restarting the "Files" process, but the phenomenon continues to occur.

**Comment by hijiro-gthb** [comment]
I made an operation error and closed it.
It is now open again.
Sorry.

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by hijiro-gthb** [comment]
To begin with, I was using the preview version while updating the version with Files' update function, and this phenomenon occurred even in the latest version 3.1.12.0.

So I uninstalled Files, downloaded the installer from "https://files.community/download/preview" & reinstalled it.
As a result, this problem appears to be resolved.

Does this mean that once this problem occurs, it is necessary to reinstall the corrected version instead of updating to the corrected version?

Thank you for your response.

![Files -  Solved quick access items are duplicated](https://github.com/files-community/Files/assets/157790562/6dea9934-3c9a-4ff7-9833-df10b605ffe2)

**Comment by yaira2** [comment]
> Does this mean that once this problem occurs, it is necessary to reinstall the corrected version instead of updating to the corrected version?

Did it occur again? It's posible that the app just needed to be restarted.

**Comment by Appuser080** [comment]
The same problem occurs in version 3.2.0.0.
The situation does not change even after I kill the background execution with Task Manager and re-launch Files. After uninstalling and reinstalling, the problem disappears for a while, but when I force close the program and start it up again, the same problem occurs.
I am using Windows 11.
![スクリーンショット 2024-02-13 185339](https://github.com/files-community/Files/assets/121074530/77f25284-fa9c-47e0-ab59-418551d5b4d2)

**Comment by Appuser080** [comment]
Additional Comments.
This phenomenon is unstable and may become normal after a complete exit and then start again.
I do not know under what circumstances the duplication occurs.
![スクリーンショット 2024-02-13 231048](https://github.com/files-community/Files/assets/121074530/a7f3f462-83b7-4d21-9120-0204b137342f)

**Comment by e1jo** [comment]
version 3.2.0.0
windows 11 10.0.22631.3155

![image](https://github.com/files-community/Files/assets/22039329/921ce4fd-5abe-4bf1-8603-3481d246444a)

**Comment by e1jo** [comment]
I also noticed that not only pinned items are displayed  and duplicated here, but also other recent folders where the user was

![image](https://github.com/files-community/Files/assets/22039329/9835e5e1-b8a6-4d5f-8532-220baf82c90d)

**Comment by 0x5bfa** [comment]
Thank you for letting us know! That's what we're working on. When we published a new release contains this fix, we'll let you know.

**Comment by hijiro-gthb** [comment]
I'm sorry.
Response delayed due to health reasons.

As others have commented, uninstalling and reinstalling seems to have resolved the issue, at least temporarily.
(I haven't had a recurrence, but I understand there have been instances where it has.)

By the way, the icon remains duplicated even after raising the version to 3.2.2.0 using the app's update function (via the down arrow update icon in the upper right corner of the app).

Thank you for saying that the correction is being addressed.

**Comment by 0x5bfa** [comment]
@yaira2 This seems not to be ready for build?

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by hijiro-gthb** [comment]
Sorry, I stand corrected.

I have not only updated the "Files" app, but also rebooted the PC, which eliminated the duplicate display of items.

(Perhaps running the command "taskkill -f -im files.exe" after updating the "Files" app might give the same result.)
