### ISSUE TITLE
The list view is crashing/taking enormous time to load when there is a lot of items and it makes the app freeze (not responding)

### ISSUE THREAD

**Issue by Fefedu973** [files-community/Files#14557]
### Description

The list view is crashing/taking enormous time to load when there is a lot of items and it makes the app freeze (not responding)

### Steps To Reproduce

1. Open Files app and goes to a direcrtory with a lot of files (multiples hundreds)
2. switch to list view
3. let the app freeze

### Requirements

- Fix the freeze

### Files Version

3.1.7.0

### Windows Version

10.0.26020.1000

### Log File

[debug.log](https://github.com/files-community/Files/files/14068646/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #14521. You can check there or click subscribe in the right sidebar for updates.

**Comment by Fefedu973** [comment]
ok thanks !
