### ISSUE TITLE
Tag is display as `Uknown`

### ISSUE THREAD

**Issue by kmitjpaul** [files-community/Files#14562]
### Description

"Files" documentation states:
```
Users to move files around without losing their tags.
```
```
 we store the tag information in the file itself using alternate data streams
 ```
but there is only an uuid in the `files` stream for my file:
```
>get-item file.pdf | Get-Content -stream files
d4b8d4bd-ceaf-4e58-ac61-a185fcf96c5d
```
and obviously it's not displayed on an another machine:

![image](https://github.com/files-community/Files/assets/80005727/8b637a22-dc78-47b6-9ed9-2c2b81929239)

### Steps To Reproduce

create file on one machine add custom tag for it for example `CV` 
sync it via shared folder to another machine 
it displayed as `Uknown` on the another machine

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.1.1.0

### Windows Version

10.0.19045.3930

### Log File

[debug.log](https://github.com/files-community/Files/files/14072991/debug.log)

**Comment by Josh65-2201** [comment]
Only the tag will be sync, you need to import the tags definition file over too. Files settings > Advance > Import/export

**Comment by kmitjpaul** [comment]
> Only the tag will be sync, you need to import the tags definition file over too. Files settings > Advance > Import/export

ok, so I need to create and issue for this page:
https://files.community/docs/features/tags

because all of this is false:
```
How do tags work behind the scenes?
Instead of creating a database with a list of files and tags, we store the tag information in the file itself using alternate data streams. This allows:

Users to move files around without losing their tags.
It decouples the tags feature from Files and allows other apps using the same system to support this feature.
```

**Comment by Josh65-2201** [comment]
While a section about the tags definition file should be added, that isn't wrong. The tag is still stored on the file rather then a database and is still there even without the tag definition.

**Comment by kmitjpaul** [comment]
> While a section about the tags definition file should be added, that isn't wrong. The tag is still stored on the file rather then a database and is still there even without the tag definition.

well, If files are synced using dropbox/windows shared dir then it's tedious to manage tags separately from files
