### ISSUE TITLE
Bug: List layout icon is blurry

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#14569]
### Description

Display scaling is 100%.
![image](https://github.com/files-community/Files/assets/66369541/d2c21ecd-125e-4809-88e1-2f53ebdda747)

### Steps To Reproduce

Show layout options flyout.

### Requirements

Fix the icon.

### Files Version

3.1.7.0

### Windows Version

10.0.22621.3007

### Log File

n/a

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #14556. You can check there or click subscribe in the right sidebar for updates.
