### ISSUE TITLE
App crash unexpectedly while it's opening

### ISSUE THREAD

**Issue by mtoranzo** [files-community/Files#14566]
### Description

The app closes unexpectedly while it's opening

### Steps To Reproduce

open the app

### Requirements

no requirements

### Files Version

3.1.1.0

### Windows Version

10.0.22631.3085

### Log File

[debug.log](https://github.com/files-community/Files/files/14073637/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download
