### ISSUE TITLE
Show Image Properties

### ISSUE THREAD

**Issue by nicksmr** [files-community/Files#14563]
### What feature or improvement do you think would benefit Files?

For image files, I'd like to see dimension, similar to Windows Explorer in Content view.

### Requirements

Dimensions 600x400

### Files Version

3.1.1.0

### Windows Version

10.0.19045.3930

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Properties already shows the dimensions of an image in the details section

**Comment by nicksmr** [comment]
Yes I found it shortly after posting.  Appreciate it!

Regards
Mark Nicks
***@***.******@***.***>
334 652-9944
