### ISSUE TITLE
Bug: Tab dropped into wrong position when moved between windows

### ISSUE THREAD

**Issue by el-ev** [files-community/Files#14568]
### Description

When dragging a tab within the same window, a placeholder for the target position appears in the tab bar. When the tab is dropped, it appears in the placeholder position. When dragging a tab across windows, the placeholder still appears, but the tab always appears at the far left of the tab bar.

### Steps To Reproduce

.

https://github.com/files-community/Files/assets/68013339/c5deb38c-0fb5-4ab7-9976-88dc4720a874

### Requirements

The tab should appear in the position indicated by the placeholder.

### Files Version

3.1.7.0 Preview

### Windows Version

10.0

### Log File

.

**Comment by yaira2** [comment]
Thanks for the report

**Comment by yaira2** [comment]
A fix will be included in the next update
