### ISSUE TITLE
Search is extremely slow close to unusable

### ISSUE THREAD

**Issue by iiwaasnet** [files-community/Files#14560]
### What feature or improvement do you think would benefit Files?

Search should be improved. Far or Explorer finds the same file way more faster, than Files. Search is completely not usable in Files.

### Requirements

Search should be at least as fast as it is in Explorer

### Files Version

3.1.1.0

### Windows Version

10.0.26020.1000

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #5845. You can check there or click subscribe in the right sidebar for updates.

Files uses the same system as Windows File Explorer. You can try set search to index everything in Windows settings > Privacy and security > Searching Windows > Enhanced

**Comment by yaira2** [comment]
@iiwaasnet thank you for the feedback, we have some improvements to search in the preview version of Files, can you give it a try and see if it helps? https://files.community/download
