### ISSUE TITLE
Feature: Hide Drives mounted as an NTFS folder (not drive letter)

### ISSUE THREAD

**Issue by BananaAcid** [files-community/Files#14564]
### What feature or improvement do you think would benefit Files?

Remove clutter: Not showing folder mountpoints as drives would be great, since they are not supposed to show up as drive, since they are mounted to a folder. (USB stick plugged onto the moitherbord internally for drivers, Swapfile drive, windows temp, onedrive, ...)

An option to toggle their visibility on the home and/or siedebar might do.

### Requirements

1. Add 1 or 2 options to the App settings.
2. Filter folder-mounts when generating lists?

### Files Version

3.1.1.0

### Windows Version

10.0.22000.2538

**Comment by Josh65-2201** [comment]
Thanks for the feedback, I've added this to the project board.

**Comment by yaira2** [comment]
We're currently tracking this feature in #9774, you can add a comment or click subscribe to be notified of any updates on the issue.
