### ISSUE TITLE
LiteDB Vulnerability?

### ISSUE THREAD

**Issue by pbeens** [files-community/Files#14576]
### Description

I admit I know nothing about Visual Studio so I'm following the instructions about how to deploy the package found at https://files.community/docs/contributing/building-from-source.

When I open `Files.sln` I get this warning:

<img width="259" alt="2024-01-29 Files_Vulnerability" src="https://github.com/files-community/Files/assets/1952535/274a4ee4-f504-4b9b-a1db-dbffd0b80354">

<br>...which leads me to this:

<img width="507" alt="2024-01-29 Files_Vulnerability_2" src="https://github.com/files-community/Files/assets/1952535/e71a0f14-8edb-4f8e-a507-0457ac8f0fd2">

<br>Should I be concerned? 

### Concerned code

Files.sln

### Gains

Addressing this in the installation instructions would help noobs like me. 

### Requirements

Not sure how this has to be addressed. Perhaps I just need reassurance that it's not a problem.

**Comment by hez2010** [comment]
We are not affected by the part that has vulnerability.
While I do have a plan to move to 5.x. By updating LiteDB we need to handle inter-process concurrency issue with care of not regressing performance, which is not a trivial work.

**Comment by pbeens** [comment]
> We are not affected by the part that has vulnerability. While I do have a plan to move to 5.x. By updating LiteDB we need to handle inter-process concurrency issue with care of not regressing performance, which is not a trivial work.

Thank so much for the quick and detailed update!
