### ISSUE TITLE
Files Preview 3.1.8.0

### ISSUE THREAD

**Issue by sergodesit** [files-community/Files#14577]
### Description

In the tested version of the application, the quick access folders are duplicated.  Thank you.

### Steps To Reproduce

![Знімок екрана 2024-01-29 190135](https://github.com/files-community/Files/assets/155973070/0b5e0aee-e843-47aa-9383-9fef541d379e)

### Requirements

There is a solution?

### Files Version

3.1.8.0

### Windows Version

10.0.26040.1000

### Log File

[debug.log](https://github.com/files-community/Files/files/14087518/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #14555. You can check there or click subscribe in the right sidebar for updates.
