### ISSUE TITLE
Feature: Add more padding to left on details layout

### ISSUE THREAD

**Issue by bokoiti** [files-community/Files#14587]
### What feature or improvement do you think would benefit Files?
(Since I use translation software, it is possible that the English may be poor.）

I would like to see the horizontal margins of the folders widened a bit.
When using the cursor to expand the selection to select multiple folders or files, the small margins do not allow for good range selection.
（It is difficult to explain, so I am attaching an image.）

![20240130_49](https://github.com/files-community/Files/assets/64144894/3b89c7a2-239a-41c8-a250-24a878bfa491)
![20240130_51](https://github.com/files-community/Files/assets/64144894/eecbba29-1bb6-4409-ad27-8fa486a6a5df)

### Requirements

- Double the padding area on the left of details layout

### Files Version

3.1.1.0

### Windows Version

10.0.22631.3007

**Comment by Josh65-2201** [comment]
Thanks for the feedback, in future please make separate requests different feedback
We're tracking 1 in https://github.com/files-community/Files/issues/8385. You can check there or click subscribe in the right sidebar for updates.

This issue will be open for your seconds request.

**Comment by yaira2** [comment]
Thank you for your feedback, we don't plan to make any changes to the margin at this time, but we'll keep your feedback in mind for the future.
