### ISSUE TITLE
Bug: Privacy Link Doesn't Open Privacy Policy

### ISSUE THREAD

**Issue by TheCrafters001** [files-community/Files#14583]
### Description

I noticed that the Privacy link isn't directed to the correct place anymore. Pretty minor bug. It tried to direct to https://github.com/files-community/Files/blob/main/Privacy.md instead of the new link, https://github.com/files-community/Files/blob/main/.github/PRIVACY.md

### Steps To Reproduce

1. Open Files
2. Open Settings
3. Go to About
4. Scroll down and click the Privacy button

### Requirements

Expected to open the correct link

### Files Version

3.1.1.0

### Windows Version

10.0.22631.3007

### Log File

Log file doesn't really show anything.
[debug.log](https://github.com/files-community/Files/files/14093676/debug.log)

**Comment by 0x5bfa** [comment]
Thank you for the bug report! I've already opened a PR to fix this.

**Comment by 0x5bfa** [comment]
Thank you for the bug report! I've already opened a PR to fix this.
