### ISSUE TITLE
Feature: Shortcut to open two specific folders in dual-pane

### ISSUE THREAD

**Issue by xellanix** [files-community/Files#14585]
### What feature or improvement do you think would benefit Files?

A shortcut that can be used to open two folders at the same time in dual-pane mode. In my idea, this shortcut can be created when the user is using dual-pane mode, so that the system can get the necessary information (such as the path and pane position) from the two currently open folders. This shortcut can be placed in a new section in the sidebar (like the tags section). With a shortcut like this, you can certainly save time and interaction in terms of opening the two desired folders periodically.

### Requirements

- "dual-paned folders" section in the sidebar
- button to create the shortcut in the "See more" (like where to create a new pane)
- when the shortcut is clicked, open two predefined folders with dual-pane mode. Set the position (left or right) according to the position stored in the shortcut.

### Files Version

3.1.1.0

### Windows Version

10.0.22631.3085

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Can you confirm this is the same as #11900.

**Comment by xellanix** [comment]
> Thanks for the feedback, Can you confirm this is the same as #11900.

Previously, I didn't know that issue existed. I think this is the same as that, only this one is a minimalist version.
