### ISSUE TITLE
Half the files don't have thumbnails

### ISSUE THREAD

**Issue by TheMikeyRoss** [files-community/Files#14586]
### Description

Hi, love this app

But for a while now the thumbnails of my files are not visible, I tried closing and opening it again and terminating the task but to no avail,
![image](https://github.com/files-community/Files/assets/97709651/b651a44d-4daa-476d-9d43-42ffe0626276)

### Steps To Reproduce

1. Open files (in Windows 10 Pro) Build: 19045.3086
2. see many of the thumbnails missing preview

### Requirements

all the thumbnails should be visible.

### Files Version

v3.1.1

### Windows Version

Windows 10 Pro Build: 19045.3086

### Log File

[debug.log](https://github.com/files-community/Files/files/14094812/debug.log)

**Comment by TheMikeyRoss** [comment]
I tried going to settings > folders> and turned off thumbnails and then turned it back again but still the same problem

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by TheMikeyRoss** [comment]
> it might be a good idea to clear the thumbnail cache in Windows to see if it makes a difference.

how can I do that?

**Comment by TheMikeyRoss** [comment]
> Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

I just installed the preview app (v3.1.9.0) and still the same problem:

![image](https://github.com/files-community/Files/assets/97709651/fedd5967-6059-435c-856d-bd0cff7756cf)

**Comment by Josh65-2201** [comment]
1. Search for the `Disk Cleanup` in the start menu.
2. Select the thumbnails from the list.
3. Then click on ok.
4. Restart Files

**Comment by TheMikeyRoss** [comment]
I just turned on my pc and open Files and all the thumbnails appear without having to clear any cache. 

I have a feeling the thumbnails will start disappearing by the end of the day after a 4+ hours of usage during the day. I'll report back

**Comment by yaira2** [comment]
Thanks for the report, let us know if it happens again while using the preview version and we'll reopen this issue.
