### ISSUE TITLE
Bug: Layout doesn't update on open tabs when the default layout changes

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#14580]
### Description

If I change the layout on one tab then switch to another tab the layout wont be using the same as the previous tab. Refreshing doesn't fix it but navigating to another folder in that tab shows that it is applied. 

There is also sometimes a crash from this when navigating around or clicking one of the flyouts in the tool bar

### Steps To Reproduce

1. Make sure `Files settings > Folders > Sync layout and sorting preferences across directories` is enabled
2. Open two tab
3. Change the layout in one tab
4. Switch to the other
5. See layout not synced

### Requirements

- Make sure all tab update the current layout when selected again

### Files Version

3.1.8.0

### Windows Version

10.0.22621.3007

### Log File

[debug.log](https://github.com/files-community/Files/files/14090494/debug.log)

**Comment by yaira2** [comment]
Thank you for the report, I think this is the same as #13747

**Comment by hishitetsu** [comment]
@Josh65-2201 Does this happen with prior to 3.1.8.0?

**Comment by yaira2** [comment]
Merging with #13747
