### ISSUE TITLE
Copy engine options

### ISSUE THREAD

**Issue by RespectIsEverything** [files-community/Files#14595]
### What feature or improvement do you think would benefit Files?

The absence of choosing a default copy handler, coupled with crashes, prevents the serious consideration of using Files.

While aesthetically polished, I'm unable to trust the application to carry out out move/copy operations.

### Requirements

- Separating the file operations module into a separate process or service.
     _If the main process crashes, any pending file operation would still be able to complete._
- Allow use of explorer.exe to conduct copy/move operations
     _If the main process crashes, any pending file operation would still be able to complete._
- Allow use of third party engines (Teracopy, Fastcopy, Richcopy, etc.)
    _If the main process crashes, any pending file operation would still be able to complete._

### Files Version

3.1.1

### Windows Version

22631.3085

### Comments

The use of 3rd party engine integration has been shot down several times which is why two other potential solutions are also listed.

**Comment by yaira2** [comment]
Thank you for the feedback, we're currently tracking this feature in #7518. You can add a comment or click subscribe to be notified of any updates.

**Comment by Josh65-2201** [comment]
Also any crash's you have please make a bug report so that they can be fixed.

**Comment by RespectIsEverything** [comment]
>File operations are already done though File Explorer and they will continue even if Files is closed.
This information is critical knowledge. It puts certain minds at ease.
Not that a crash dialog always displays, but perhaps worth including a blip about this in the crash dialog text.

> Also any crash's you have please make a bug report so that they can be fixed.
Egg-Chicken. After initial crash, if unwilling to trust the program to carry out file operations, further use of the application is discouraged.
