### ISSUE TITLE
Special "tree" view

### ISSUE THREAD

**Issue by Marginez** [files-community/Files#14594]
### What feature or improvement do you think would benefit Files?

It would be useful to be able to expand folders in the same view, as Apple Finder can do. Then you can simultaneously select files lying in different folders.

![image](https://github.com/files-community/Files/assets/107857807/667940e2-7fe6-4a33-98bc-3b49a70087c0)

### Requirements

- Easily select files from different folders to act on them (copy, delete, rename, etc.).

### Files Version

3.1.1.0

### Windows Version

10.0.22631.3085

### Comments

I am using this service for the first time, so if I am doing something wrong, I apologize.

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in https://github.com/files-community/Files/issues/1928. You can check there or click subscribe in the right sidebar for updates.
