### ISSUE TITLE
Add sftp integration, or better yet rclone.

### ISSUE THREAD

**Issue by paolosezart** [files-community/Files#14598]
### What feature or improvement do you think would benefit Files?

Rclone is a very functional program for mounting cloud disks. Unfortunately the configuration of this program is quite complicated (for a home user). Is it not possible to integrate rclone into your wonderful program?

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.1.2

### Windows Version

10.0.19045.2965

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #2407 . You can check there or click subscribe in the right sidebar for updates.
