### ISSUE TITLE
Bug: Program not properly maximizes window

### ISSUE THREAD

**Issue by pawelik001** [files-community/Files#14599]
### Description

When Files program is maximized, it displays the resize cursor, so it's not able to "catch" program on very top and move to the other screen or to close the program.

Video: https://imgur.com/a/eSY7RHh 

### Steps To Reproduce

1. Maximize Files.
2. Move your mouse to the very top of your screen.
3. Try to drag the program / close.

### Requirements

Expected behavoiur should be to don't dhow the resize cursor and not trigger this action.

### Files Version

3.1.1.0

### Windows Version

10.0.22631.3085

### Log File

[debug.log](https://github.com/files-community/Files/files/14104916/debug.log)

**Comment by yaira2** [comment]
Thank you for sharing your feedback, this is a known issue with the WinAppSdk framework where extending tabs into the title bar interferes with the ability to drag the window. As a workaround, you can drag the window from the empty space to the left of the caption buttons.

**Comment by 0x5bfa** [comment]
Framework issue: https://github.com/microsoft/microsoft-ui-xaml/issues/8805

**Comment by yaira2** [comment]
Microsoft recently fixed this issue and we'll include the fix in the next version of Files.
