### ISSUE TITLE
Hide task bar icon

### ISSUE THREAD

**Issue by fidelako** [files-community/Files#14606]
### What feature or improvement do you think would benefit Files?

this program rocks but I don't like that if you want it open in the background an icon appears in the task bar, I wish I were given the option to hide it and keep it hidden in the settings since it's really not necessary, I already have it pinned to the task bar as an icon and if i wanted to quit the program there are other ways, other than that this rocks

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.1.1.0

### Windows Version

10.0.19045.3930

**Comment by Josh65-2201** [comment]
Thanks for the feedback, you can already hide it from the taskbar by right clicking the task bar > Task bar settings > Other system tray icons > Click the toggle on Files.

**Comment by rugk** [comment]
Ah you mean this Windows setting?

![grafik](https://github.com/files-community/Files/assets/11966684/78745a08-da8c-4b8e-8225-3407180cdb4c)

Unfortunately, this means you need to toggle the main toggle, i.e. _hide all tray icons by default_. If I want to see all other icons _except_ Files, I would need to then re-enable all the other icons again...
Also, if new applications add new icons, they are likely then disabled aka not shown by default. Which again, I may not want.

Also, obviously, it's still visible in the overflow menu.

IMHO a simple files manager does not need a tray icon, especially as there are no context menu options being exposed or so. And I also have the file manager open at any times and pinned too at the main task bar.

Windows 10 here

**Comment by Josh65-2201** [comment]
The toggle doesn't hide them all by default, it just enables the option for overflow. New taskbar icons will show in that main one unless toggled off previously. 
The icon is also there as Files runs in the background now and it has the option to fully close it. There will be more functions added to it too.

**Comment by rugk** [comment]
Yeah, but you need to re-enable all icons and especially new ones. Also, as such, an option to hide it completely, even would be very much appreciated.

**Comment by yaira2** [comment]
We're working on a built-in setting for this in #15947.
