### ISSUE TITLE
Home page update

### ISSUE THREAD

**Issue by sergodesit** [files-community/Files#14608]
### Description

Hello, the main page does not update when you click on the update icon (I don’t know if anyone wrote about this error), the update works in folders.
![Снимок экрана 2024-02-01 002626](https://github.com/files-community/Files/assets/155973070/43483bb6-d659-4fbe-906e-cd00b3620739)

### Steps To Reproduce

1

### Requirements

there is a solution?

### Files Version

3.1.1.0

### Windows Version

10.0.19045.3996

### Log File

[debug.log](https://github.com/files-community/Files/files/14118041/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #6182 . You can check there or click subscribe in the right sidebar for updates.
