### ISSUE TITLE
Installation error with Files 3.1.1

### ISSUE THREAD

**Issue by NGatSH** [files-community/Files#14602]
### Description

Install fails with error message 'A Prerequisite for an install could not be satisfied.'

### Steps To Reproduce

1. Download latest build of Files self-extracting archive.
2. Run file.
3. Click 'Install' button to start installation.
4. Installation fails with error message noted above.

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.1.1

### Windows Version

Windows 10 Pro version 1909 build 18363.418

### Log File

Debug.log not created.

**Comment by yaira2** [comment]
Do you have an unofficial/modified (EG. Disabled windows update, removed the Microsoft store, used a debloat program/script) version of Windows?

**Comment by Josh65-2201** [comment]
You may also need to update Windows as the minimum is build 19041
