### ISSUE TITLE
Blocking. slowness and closing of the program unexpectedly

### ISSUE THREAD

**Issue by MMDNecrox** [files-community/Files#14605]
### Description

Constant errors:
- Very slow when selecting and navigating between tabs
- The program closes unexpectedly without an error message when viewing tabs with many files
- When starting the application it does not restore the current tabs
- When I visit the dashboard options, strangely the cpu usage is high for many seconds
​

### Steps To Reproduce

- Very slow when selecting and navigating between tabs
- The program closes unexpectedly without an error message when viewing tabs with many files
- When starting the application it does not restore the current tabs
- When I visit the dashboard options, strangely the cpu usage is high for many seconds

### Requirements

Constant errors:
- Very slow when selecting and navigating between tabs
- The program closes unexpectedly without an error message when viewing tabs with many files
- When starting the application it does not restore the current tabs
- When I visit the dashboard options, strangely the cpu usage is high for many seconds

### Files Version

3.1.1.0

### Windows Version

10.0.19045.3930

### Log File

[debug.log](https://github.com/files-community/Files/files/14114294/debug.log)

**Comment by MMDNecrox** [comment]
I have never reported program errors. I don't know if this form is written correctly.

**Comment by yaira2** [comment]
> Very slow when selecting and navigating between tabs

Thank you for your feedback, can you clarify what you mean by slow? On my side switching between tabs is instant.

> The program closes unexpectedly without an error message when viewing tabs with many files

There is a good chance this is fixed in the preview version https://files.community/download. If it's still happening, please open a bug report so we can investigate.

> When starting the application it does not restore the current tabs

The default is to continue where you left off, you can check if that's what you have set from the settings dialog.

> When I visit the dashboard options, strangely the cpu usage is high for many seconds

Can you clarify what you mean be "dashboard"?

**Comment by yaira2** [comment]
> I have never reported program errors. I don't know if this form is written correctly.

No worries 🙂 
It's a little bit technical so we appreciate the time you took to share your feedback. We usually suggest opening a separate report for each issue as it makes it easier to track the different feedback.

**Comment by MMDNecrox** [comment]
**> Thank you for your feedback, can you clarify what you mean by slow? On my side switching between tabs is instant.**
When you click on a tab, it does not appear instantly. There is a delay of almost a second. As if the application froze during that moment

**> The default is to continue where you left off, you can check if that's what you have set from the settings dialog.**
In "Settings" in the "startup settings" option, "continue where I left off" is selected. But when you start the application it does not restore

**> Can you clarify what you mean by "dashboard"?**
Sorry, possibly Google Translate did not work well in the translation. I am Spanish and I don't know English.
Regarding the problem comment, When entering "settings" when browsing the options, the cpu usage of this program increases to 100%.

Another problem encountered is:
- I can't do this application; "Run as administrator." The application does not start.

**Comment by yaira2** [comment]
> When you click on a tab, it does not appear instantly. There is a delay of almost a second. As if the application froze during that moment

I can't repro this, but we'll keep working on performance improvements.

> In "Settings" in the "startup settings" option, "continue where I left off" is selected. But when you start the application it does not restore

Can you open a seperate bug report so we can add this issue to the todo list?

> Regarding the problem comment, When entering "settings" when browsing the options, the cpu usage of this program increases to 100%.

Is there a specific settings section that has this issue more than others? I think it's mainly because of all the additional items added to the visual tree.

**Comment by MMDNecrox** [comment]
> Can you open a seperate bug report so we can add this issue to the todo list?
I'm sorry but I'm not going to create any more bug reports. It is very tedious to create a report and overwhelming for newbies like me.

**> Is there a specific settings section that has this issue more than others? I think it's mainly because of all the additional items added to the visual tree.**
With the preview version I no longer have high cpu problems in the options. In the previous version it generally occurred when displaying "Appearance"

As a detail, when the application closes unexpectedly when displaying tabs, there are residues that are seen in the Windows task manager. The file "File.App.Server.exe" may accumulate several times from attempts to test the application.

In the Preliminary version I continued with the problem that does not save the tabs and the application always starts by default

For the moment I continue using the "Q-Dir" application which works without problems.

I like your program more visually, the design and transparencies look very good. But it doesn't work for me and it's tedious to use because of the constant unexpected closures.

**Comment by MMDNecrox** [comment]
Is the problem possible when displaying the thumbnails? When I open a tab and see thumbnails, depending on the thumbnails the application closes unexpectedly

https://github.com/files-community/Files/assets/158310373/5beda73b-62d7-4603-a550-d68962884cb9

For example, if I navigate to image cards from the game "Koikatsu Party", the application closes unexpectedly.

**Comment by yaira2** [comment]
> As a detail, when the application closes unexpectedly when displaying tabs, there are residues that are seen in the Windows task manager. The file "File.App.Server.exe" may accumulate several times from attempts to test the application.

I suppose this is also why the tabs aren't being restored, we're tracking this issue in #12624.

> Is the problem possible when displaying the thumbnails? When I open a tab and see thumbnails, depending on the thumbnails the application closes unexpectedly

Are you able to repro this in the latest preview build (v3.1.10)?

**Comment by MMDNecrox** [comment]
**> Are you able to repro this in the latest preview build (v3.1.10)?**
In the preliminary version I continue with the same problem. Trying all themes, it always closes unexpectedly when showing some thumbnails

**Comment by MMDNecrox** [comment]
**> Can you attach the log file from v3.1.10?**
Yes.
[debug.log](https://github.com/files-community/Files/files/14116216/debug.log)

I can currently confirm that the app is having trouble displaying thumbnails.
If I look at a folder in list form, there is no unexpected closure but it is slow to display the items (much slower than the default Windows Explorer). But if I see content with "medium" size thumbnails, the application closes unexpectedly

**Comment by yaira2** [comment]
The log file looks like it's from the Store version, can you confirm you're testing using the preview version? I'm pretty sure the crash is already fixed in the preview build🙂

**Comment by MMDNecrox** [comment]
Uninstall everything related to this application. For some reason it always started the same version. I must be using the preview version now.
[debug.log](https://github.com/files-community/Files/files/14118139/debug.log)

**Comment by yaira2** [comment]
Yeah, looks like that's from the preview version but I'm not seeing any errors in the log file.

**Comment by MMDNecrox** [comment]
It seems that there are no unexpected closures now. But very slow when using tabs and viewing image thumbnails.

https://github.com/files-community/Files/assets/158310373/a3b40077-41b1-4f89-bae3-312ecbe0cb40


https://github.com/files-community/Files/assets/158310373/dbaf0921-25c4-4d0e-ab15-88325bee5f02


https://github.com/files-community/Files/assets/158310373/3abb5fd0-b50b-4e48-a7b6-c11e14d781d5


https://github.com/files-community/Files/assets/158310373/2a296a76-3561-4038-9cbe-39793748a1c7


​

**Comment by yaira2** [comment]
Thanks for the feedback, I'm happy to hear the crashes have been resolved. One of the crashes had to do with loading too many thumbnails at the same time, we addressed this by making the thumbnail loading less aggressive but the downside is that it's a little slower. That said, we're going to continue optimizing the performance so that we can get it back to the original speed without causing any crashes.

**Comment by MMDNecrox** [comment]
> Thanks for the feedback, I'm happy to hear the crashes have been resolved. One of the crashes had to do with loading too many thumbnails at the same time. We addressed this by making the thumbnail loading less aggressive but the downside is that it's a little slower. That said, we're going to continue optimizing the performance so that we can get it back to the original speed without causing any crashes.

Good. I will stay tuned for future updates.
And to avoid possible lack of performance, my pc is:
5800x3d + RTX4090 + 64Gb DDR4 4600Mhz
![a6568187b44c2a7c18d9a4240020fca3](https://github.com/files-community/Files/assets/158310373/2821ba7b-cf66-4e4d-84f9-4e6b6e2b004f)

**Comment by yaira2** [comment]
We have some ideas to improve the performance when scrolling but the main thing is to reduce the crashes.
