### ISSUE TITLE
Feature: Add Lucid Link cloud drive support

### ISSUE THREAD

**Issue by Colin-VideoRevealed** [files-community/Files#14612]
### What feature or improvement do you think would benefit Files?

LucidLink is buried in Volumes. Why couldn't it be displayed the same as Explorer?

![LucidLink-not-showing](https://github.com/files-community/Files/assets/93034904/737a82d6-490a-44d5-a783-28fa4e1bacf0)

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.1.1.0

### Windows Version

10.0.22631.3085

**Comment by Josh65-2201** [comment]
Thanks for the feedback, I've added this to the project board.

**Comment by Colin-VideoRevealed** [comment]
Wow, that was fast. Thanks!

**Comment by yaira2** [comment]
This documentation might be helpful https://support.lucidlink.com/hc/en-us/articles/4416950355085-Where-is-my-LucidLink-folder-and-data

**Comment by Colin-VideoRevealed** [comment]
I read the document but I'm thinking from a typical user's point of view not an enterprise or sysadmin scenario.
LucidLink is used by many remote video editors. They are not IT experts. They just want access to their files and Explorer does that with no extra setup (I didn't have to use a CLI). Having that appear in Files would be a good thing too.

**Comment by yaira2** [comment]
@Colin-VideoRevealed that comment was for whoever decides to implement this, sorry for the confusion.
