### ISSUE TITLE
Shrink sidebar on small windows sizes similar to the settings page

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#1461]

**Comment by soumyamahunt** [comment]
Settings has different icons for different sections, while sidebar will have same icons for many items. Hence shrinking like settings isn't going to be a good solution. In this case, sidebar should expand as an overlay when the pointer enters.

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran v0.20 has support for resizing the sidebar.
