### ISSUE TITLE
Bug: Crash when opening a Joplin backup with the info pane open.

### ISSUE THREAD

**Issue by jpnolanjr** [files-community/Files#14620]
### Description

I opened up a folder and Files crashed without opening the folder

### Steps To Reproduce

1. Navigate to Drive C / Users / myname / .config / joplin-desktop
2. Attempt to open JoplinBackup (this folder has a date stamp of 12/20/23). Rather than open, Files crashes with only the message requesting if I want to file a bug report
3. I was able to select that directory and open the details/preview pane - Property details shows 3 files, 2 folders, size as 37.69MB and recent Access, the attributes had the Read-only and Hidden boxes unchecked.  I was able to click on Preview and a Folder Icon appeared with a page in it,
4. So I closed the Details/Preview Pane and made another attempt at accessing the directory - IT WAS SUCCESFUL and allowed me to traverese the foders and files that it contained

### Requirements

- e.g. Fix crash that occurs when...
- Opening a folder, I was able to open other folders in the same (joplin-desktop) directory, but not the JoplinBackup folder

### Files Version

3.1.1.0

### Windows Version

10.0.19045.3930

### Log File

[debug.log](https://github.com/files-community/Files/files/14130048/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
