### ISSUE TITLE
Error show selected items in list view

### ISSUE THREAD

**Issue by RickyVercetti** [files-community/Files#14623]
### Description

Error show selected items in list view

### Steps To Reproduce

Don't know

### Requirements

- e.g. Fix crash that occurs when...
-

### Files Version

3.1.1.0

### Windows Version

10.0.22631.3085

### Log File

[debug.log](https://github.com/files-community/Files/files/14139896/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

If it still an issue please fill out the steps to reproduce.
