### ISSUE TITLE
Bug: Certain tags duplicate itself for certain folders

### ISSUE THREAD

**Issue by koh-kun** [files-community/Files#14622]
### Description

I have a folder with a tag, and it seems to always duplicate itself and even shows up when the tag has been deleted.

https://github.com/files-community/Files/assets/97654347/2402fd0f-6776-4eae-bc18-a725c64d9d1e

### Steps To Reproduce

1. Put tag
2. Refresh window

### Requirements

I would like the tag to only appear once, and be removed permanently if I remove the tag.

### Files Version

3.1.1.0

### Windows Version

10.0.19045.3930

### Log File

[debug.log](https://github.com/files-community/Files/files/14133353/debug.log)

**Comment by yaira2** [comment]
Is this by any chance a cloud drive?

**Comment by koh-kun** [comment]
Oh yes, it's linked to Google Drive.

**Comment by yaira2** [comment]
Can you try these steps:
1. Open settings > folders > hidden items
2. Enable the option to show alternate data streams
3. Refresh the folder with the tagged items
4. There should be a bunch of items ending in `:files:`
5. Try opening one of them and deleting one of the lines
6. Refresh the folder and see if a tag was removed

**Comment by koh-kun** [comment]
I followed steps 1 to 3, but I don't see the files you mentioned in Step 4.

**Comment by yaira2** [comment]
Do they show up in non Google Drive locations (make sure to refresh the folder after assigning a tag)?

**Comment by koh-kun** [comment]
Sorry, but they don't show up anywhere. Google Drive or not.

**Comment by koh-kun** [comment]
I see some files with **:Zone.Identifier** and **:SmartScreen** but not **:files:** when I check out local drives.

**Comment by yaira2** [comment]
That's interesting, are the tags still present when you restart the app?

**Comment by koh-kun** [comment]
Yes, they are. In the video I provide, it happens only with the "in progress" tag, but the same thing happens with the "complete" tag as well. It seems to duplicate itself. One thing that I noticed is that this does not happen if I make a new folder.

**Comment by koh-kun** [comment]
I found it interesting that copying the folder inherits the same issue, but making a new folder doesn't.

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
