### ISSUE TITLE
No thumbnails in about 60% of my jpg photos

### ISSUE THREAD

**Issue by MelecaOnce** [files-community/Files#14621]
### Description

I love Files app, but for some reason, around 60% of my pics are now showing their thumbnail.

Among those showing thumbnails, there are new and old photos. There are lots of photos taken by the same camera that are showing and not showing thumbnails. 

![image](https://github.com/files-community/Files/assets/124208104/d8a934c3-ead8-4cc0-91d5-c7e0dd0a49a0)

### Steps To Reproduce

just using the app with thumbnail view

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.1.1.0

### Windows Version

10.0.22635.3130

### Log File

[debug.log](https://github.com/files-community/Files/files/14130400/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by yaira2** [comment]
I can confirm this was fixed in the preview build, if for whatever reason it's still not working, please let us know and we'll take another look.

**Comment by yaira2** [comment]
@Armandl23
1. Is this a OneDrive location?
2. If you wait long enough, do the thumbnails load?

**Comment by Armandl23** [comment]
Yes all my files are bith on Onedrive and are Local on my PC (1 TB ssd)

**Comment by Armandl23** [comment]
Sorry item 2 : No the rebuild was done already a few days ago
