### ISSUE TITLE
Open New Tab in background

### ISSUE THREAD

**Issue by mikaeelg** [files-community/Files#14633]
### What feature or improvement do you think would benefit Files?

Currently, opening a folder/drive in a new tab (via middle click or via right click context menu) immediately switches focus to the newly opened tab. Add the option to open a folder in a a new tab (especially for those opened via middle click) in the background (i.e. not switch focus immediately). Usually, performing this action is done in the context of wanting to open many folders from a directory in new tabs at once.

### Requirements

Add the option to open a folder in a a new tab (especially for those opened via middle click) in the background (i.e. not switch focus immediately)

### Files Version

3.1.1.0

### Windows Version

10.0.19045.3996

**Comment by yaira2** [comment]
This is deffinitly the intended behavior (see #2512), it looks like this is a regression. Can you open a new issue using the bug report template?
