### ISSUE TITLE
Font size of sort by date month etc.

### ISSUE THREAD

**Issue by meemore** [files-community/Files#14639]
### What feature or improvement do you think would benefit Files?

the font size is too big, font makes it hard to see anything.

![Screenshot_3](https://github.com/files-community/Files/assets/124497263/dfd1bdd3-4ef1-474b-80d9-0b5df17d1de7)

### Requirements

visual

### Files Version

3.1.11.0

### Windows Version

10.0.22621.3085

**Comment by yaira2** [comment]
Thank you for your feedback, we don't currently have plans to change the default font size, but you can try the following:
- Enable compact spacing in Files > Settings > Appearance
- Reduce the font size or screen scaling in Windows Settings

**Comment by meemore** [comment]
then change the color from white to a light greyish shade
