### ISSUE TITLE
Folder Pane Tree Structure with Expand to Open Folder

### ISSUE THREAD

**Issue by bassgeeek** [files-community/Files#14648]
### What feature or improvement do you think would benefit Files?

I tried Files because MS Windows Explorer has a new bug where the folder pane no longer expands the tree to the open folder. I was disappointed that Files doesn't seem to have a tree view at all. I have some workflows that require me to move files between folders as tasks are completed. This is easy when the folder tree is expanded, so I can quickly drag from the open folder to the correct storage folder. I tried using the Files dual column layout with 2 open tabs, but it is cumbersome to get setup because the 2 panes are completely independent. 

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.1.1.0

### Windows Version

10.0.22631.3085

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #1928. You can check there or click subscribe in the right sidebar for updates.

**Comment by yair100** [comment]
@bassgeeek Tree View is currently available in preview https://files.community/download. It will be included in the next stable release.
