### ISSUE TITLE
Multiple Files Selection Issue, Tag Multiple Files Issue

### ISSUE THREAD

**Issue by haterslove4me** [files-community/Files#14652]
### Description

Whenever we select multiple files (esp. by using command shift+(select by clicking) to select files) or select multiple files and tag all of them combined, Files app automatically closes and a notification appears "Something went wrong", "Report an issue".
<img width="265" alt="Screenshot 2024-02-06 133107" src="https://github.com/files-community/Files/assets/137325847/17778ea1-cd56-4404-bcb3-bcc41eae1977">

### Steps To Reproduce

1. Fix tag issue
2. Fix multiple files selection issue

### Requirements

Please fix this crash...

### Files Version

version 3.1

### Windows Version

Version 22H2 (0S Build 22621.3085)

### Log File

<img width="265" alt="Screenshot 2024-02-06 133107" src="https://github.com/files-community/Files/assets/137325847/fa853fe8-8909-4c8b-9894-2e7338573e77">

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by haterslove4me** [comment]
Thanks ✌️

### **A Suggested Feature**

- [ ] Can you please add a manual sorting system for tags? I have multiple tags, whenever I have to go to a specific tag I have to scroll. If there were a sorting system that could be organized automatically and manually, it would be a useful addition!

**Comment by haterslove4me** [comment]
Thanks ✌️

**Comment by haterslove4me** [comment]
### Suggested Feature

- Add a tag button next to the _Properties_ icon on the top bar. Every time it consumes time to set by clicking right (or opening options). This would be a useful addition.

<img width="759" alt="nonsme" src="https://github.com/files-community/Files/assets/137325847/1dd34f4c-5f7b-40be-94c2-4a30e6190abd">
