### ISSUE TITLE
How we can use NavigationViewItem Style?

### ISSUE THREAD

**Issue by winuitester** [files-community/Files#14656]
### Description

i am trying to use your NavigationViewItem style i want to achive this:

![1](https://github.com/files-community/Files/assets/159169435/7390c821-ed43-4344-a460-36deae3b42a9)

but when i add `NavigationViewItemButtonStyle`
i get this:

![2](https://github.com/files-community/Files/assets/159169435/216b89af-edbd-40c7-a933-5f071f53e392)

as you can see Expander Title color is not same in above pic, also as you can see SubItems Margin is different.

### Steps To Reproduce

how i can fix this?

### Requirements

is there something i miss?

### Files Version

latest

### Windows Version

10.0.22621

### Log File

NO Log

**Comment by yaira2** [comment]
Thank you for the question, the styling in Files isn't possible with the regular NavigationView from WinUI. The sidebar is actually a custom control created by @marcelwgn. It was designed specifically for Files but you're welcome to copy it for your own use.

**Comment by winuitester** [comment]
> Thank you for the question, the styling in Files isn't possible with the regular NavigationView from WinUI. The sidebar is actually a custom control created by @marcelwgn. It was designed specifically for Files but you're welcome to copy it for your own use.

tnx, where i can copy it?

**Comment by marcelwgn** [comment]
Hi @winuitester, glad to hear you like the control. The control and all its subcomponents can be found here: https://github.com/files-community/Files/tree/main/src/Files.App/UserControls/SideBar

**Comment by winuitester** [comment]
tnx
