### ISSUE TITLE
Containers for Pinned Items on the Home Page

### ISSUE THREAD

**Issue by crashmit** [files-community/Files#1465]
This request is corresponding to the widget system announced in #366  

**Idea:**
My suggestion is to introduce a widget that allows users to create storage containers on the home page, which can be filled with links to folders, files and programs. This will enable them to access everything related to one topic from one location instantly, regardless of where the files are stored on the system, like the current explorer sidebar. But instead of having an unorganized and overloaded sidebar, this gives users flexibility and order. 

![image](https://user-images.githubusercontent.com/61259627/87483931-f8863280-c602-11ea-995f-552121a679b7.jpg)

@XPoppyX also suggested to allow different sorting any layout options for these containers, as he already included in this screenshot. Personally, I'm not sure about the layout modes, as the limited space doesn't really allow for different displays that would still stay clear, but this can of course be explored in the future.

**Dependencies:**
Currently Files UWP doesn't support drag and drop from one folder to another as far as I know, which makes filling these containers a bit more complicated. as a drag 'n' drop alternative and especially if this is nothing that will be possible in the future, I would suggest to offer a context menu entry. I know that the context menu is kind of sensible in the way that it gets confusing quickly with additional elements, but I don't really see any other viable solution. The only other thing I could think of is an own selection window, that could be opened from the target container.But this would be less user friendly imo.

**Comment by XPoppyX** [comment]
> as the limited space doesn't really allow for different displays that would still stay clear


maybe an option to resize containers could be added

**Comment by jpparametrics** [comment]
How about something along the lines of the tiles on the start menu? For resizing the containers.

My programming skills are limited so I really don’t even know if this can be done however if it can, it would be nice.

JP

**Comment by Talisman39ar** [comment]
I like this general idea. Reminds me of the Fences product from Stardock, however that works by creating customizable regions on the desktop. My desktop is always obscured, so it ends up not being that useful. But if done as the default view for the Files "explorer" it could be quite a bit more accessible. Personally I think icon view rather than list view is the way to go here - these are just jumping off points, kind of like an app folder on a smartphone.

**Comment by crashmit** [comment]
I will explore some options today and share my prototypes later. Just for clarification, is a drag-and-drop function across different tabs planned in the near future or should we look for different options to add elements? @yair100

**Comment by crashmit** [comment]
So this is my try on using tiles: I tried two sizes. 

![image](https://user-images.githubusercontent.com/58466626/87775660-c0f7d000-c826-11ea-9457-62f9c5323a14.png)

While the medium large tiles alleviate the issue of too little space for the label, I don't think anybody would benefit from larger Icons or Previews, as you usually only put things in there you use often and therefore already know the content of. But as mentioned, you have very little space for the file/folder/program name in the small tiles version.

I've also thought about scaling and I want to hear what you all think. For hand-scaling the containers, I would provide a hard grid based on the width and height of the fields. You can't increase the width by half a field, it will snap to the whole width immediately (like in the win10 startmenu). 
For window-scaling I'm not quite sure and it also depends on the implementation of the whole widget system. Generally, I would define a minimum and maximum width for a field and if it gets too short, either put the whole container into a second row below or move it beyond the window's right edge and make it side-scrollable. I would prefer to have a second row because you have everything visible at every moment. But I wouldn't have any issues with scrolling downwards or sidewards internally inside a container.

![image](https://user-images.githubusercontent.com/58466626/87776342-e802d180-c827-11ea-901a-38d00797fa9d.png)

In this screenshot I've also experimented with sorting. V2 would be the standard way the file explorer currently handles sorting by type. In v1, it gets more tidied up in my opinion, but at the cost of space. 

What do you think?

**Comment by yair100** [comment]
> I will explore some options today and share my prototypes later. Just for clarification, is a drag-and-drop function across different tabs planned in the near future or should we look for different options to add elements? @yair100

This has been implemented in the latest beta build.

**Comment by yaichenbaum** [comment]
Thank you for all your input, this widget has been approved for development. We are looking for someone to assign this to so let us know if you are interested in working on this.

**Comment by d2dyno1** [comment]
> Thank you for all your input, this widget has been approved for development. We are looking for someone to assign this to so let us know if you are interested in working on this.

Hmmm..

@yair100

**Comment by yaichenbaum** [comment]
@d2dyno1 Would you like to work on this widget?

**Comment by d2dyno1** [comment]
I'll see what I can do, but I can't promise anything. I've just started work on it, but it'll not come anytime soon cuz I'll be away for a week

**Comment by d2dyno1** [comment]
I'll also need some help on the UI

**Comment by crashmit** [comment]
I'm happy to help. Which way do you need help with the UI? Sadly my coding skills won't be enough for that, but if you need more Design work, I may help.

**Comment by d2dyno1** [comment]
I meant coding wise. I code in wpf and have little experience with uwp. The design is nicely explained there. Appreciate your will to help!

**Comment by d2dyno1** [comment]
#2881 :eyes:

**Comment by yaichenbaum** [comment]
This widget was implemented with #2881.
