### ISSUE TITLE
Switch between tabs by Ctrl + Page Up/Down

### ISSUE THREAD

**Issue by mokhtarivahid** [files-community/Files#14665]
### What feature or improvement do you think would benefit Files?

It would be nice to add shortcuts for switching between tabs by Ctrl + Page Up/Down, as it has become a standard and common shortcut.

### Requirements

Only requires adding two shortcuts.

### Files Version

3.1.1.0

### Windows Version

Windows 11

**Comment by Josh65-2201** [comment]
Thanks for the feedback, you can change them your self. https://files.community/docs/customize-settings/actions

**Comment by yaira2** [comment]
Thank you for your feedback, we don't have plans to have these shortcuts by default but you can follow the instructions Josh shared to set them up for yourself.
