### ISSUE TITLE
Bug: "Set As Desktop Background" doesn't work

### ISSUE THREAD

**Issue by QuaintMako** [files-community/Files#14660]
### Description

The command "_Set as Desktop Background_" seems to not be working with either `.jpg` and `.png` pictures. However, the command appears correctly in the context menu and the upper toolbar.

To be noted that the command "_Set as Desktop Slideshow_" is working, so it's probably coming from the "_Set as Desktop Background_" command call.

### Steps To Reproduce

1. Select a picture and execute the command "_Set as Desktop Background_"
2. Observe your background has not changed.

### Requirements

- The selected picture becomes your desktop wallpaper when using the command.

### Files Version

3.1.12.0

### Windows Version

10.0.19045.3086

### Log File

No useful log is added to the logfile for this issue.

**Comment by yaira2** [comment]
Thanks for the report

**Comment by 0x5bfa** [comment]
It's working either png or jpg on my end (In the latest build from the maim d814791).

Did you catch a dialog, which should be shown when the Shell32.IDesktopWallpaper.SetWallpaper() method call feailed?

**Comment by yaira2** [comment]
Likewise, it appears to work via the command palette, context menu, and toolbar.

**Comment by QuaintMako** [comment]
This is very strange, I cannot reproduce it on my main computer as well. 
I am not able to get logs regarding the supposed issue, or catch any exception. It might be blocked by another application on the computer I'm using Files on for work.
