### ISSUE TITLE
Feature: Show a notification when the app goes to the background for the first time

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#14668]
### What feature or improvement do you think would benefit Files?

By default, Files continues to run in the background even if the window is closed for faster startup. However, new users of the app may not be aware of this and may wonder when they find the icon in the system tray.
So, when the app goes to the background for the first time, it would be helpful to notify the user that the app continues to run in the background.

### Requirements

Show a notification when the app goes to the background for the first time.

### Files Version

3.1.1.0

### Windows Version

10.0.19045.3930

**Comment by yaira2** [comment]
Thank you for the feedback
