### ISSUE TITLE
Bug: Default layout is set to Grid when the app is updated to v3.2

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#14678]
### Description

If you set the default layout setting to Adaptive in v3.1, the setting is changed to Grid in v3.2. It is probably due to adding the list layout.

### Steps To Reproduce

Refer to description.

### Requirements

The settings should not change.

### Files Version

3.2.0.0

### Windows Version

10.0.19045.3930

### Log File

n/a

**Comment by yaira2** [comment]
This is due to us changing the enum, unfortunately I think it's too late to remedy this but let me know if you have any ideas.

**Comment by hishitetsu** [comment]
* Change FolderLayoutModes values to be consistent with the previous versions.
* Convert values when get/set SelectedDefaultLayoutModeIndex. https://github.com/files-community/Files/blob/d501d1d09e2b6d1c3897fb61c4dbb7b9f805a14d/src/Files.App/ViewModels/Settings/FoldersViewModel.cs#L27
