### ISSUE TITLE
Opening a link to a folder while using the columns layout freezes Files

### ISSUE THREAD

**Issue by Koning53** [files-community/Files#14671]
### Description

I've configured Files as my default file explorer. When opening a file from VS Code (file > context menu > reveal in file explorer) this crashes Files if I am using the columns layout as default.  

### Steps To Reproduce

1. Configure Files as the default file explorer
2. Configure the columns layout as your default folder layout
3. Open a file in explorer from Visual Studio Code (probably anywhere outside of Files) . VSCode > File > context menu > reveal in file explorer

It seems to happen only with files with a deep path, in my case 7 folders deep.

### Requirements

It should open the file location in Files

### Files Version

3.1.1.0

### Windows Version

10.0.22631.3007

### Log File

[debug.log](https://github.com/files-community/Files/files/14210327/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download
