### ISSUE TITLE
Incorrect display of icons

### ISSUE THREAD

**Issue by Z4N3XC** [files-community/Files#14670]
### Description

It occurs randomly that icons, folders, documents are displayed with a black background or are suddenly significantly smaller than the others. It usually always occurs when I change the display size. I don't have this problem in the Column or Detail view.

I would also like to see a feature that displays Adobe files with thumbnails instead of PS, AI, iD ... like in the Apple Finder 👌
![Screenshot 2024-02-08 140733](https://github.com/files-community/Files/assets/37667138/3ddccf4e-7ec1-4449-8a26-68b13ea8f50c)

cheers.

### Steps To Reproduce

Its random

### Requirements

- e.g. Fix crash that occurs when...
Its random

### Files Version

3.1.1.0

### Windows Version

10.0.22631.3007

### Log File

[debug.log](https://github.com/files-community/Files/files/14209656/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by Z4N3XC** [comment]
I have uninstalled/reinstalled everything again and also tried 3.1.13. Still have the error, but found out by accident what causes it. It only happens with folders that only contain other folders and not files such as a simple text file. I added a text file to Private and then the display error disappeared. Same with image files.

In addition, only 13.1.13 shows me the folder contents under Quick Share, for example.

Or is there a recommendation here? I always use the oldschool method of creating thumbnail.jpg files for my PSD projects so that I don't always have to open them :D

I know that neither the simple Windows Explorer nor Files can currently display thumbnails from e.g. Adobe - but it would be a very strong feature because SAGE is not really reliable either and temporarily creates huge thumb files, which is annoying.

![image](https://github.com/files-community/Files/assets/37667138/e03fe79d-14b4-4022-89b6-4dcb0e6894ec)

**Comment by yaira2** [comment]
> I would also like to see a feature that displays Adobe files with thumbnails instead of PS, AI, iD ... like in the Apple Finder 👌

It would be nice if we could generate thumbnails for every file format out of the box but unfortunately, generating thumbnails for proprietary file formats is no simple task. If a dedicated app like Sage Thumbs is struggling with this, it's hard to imagine we can do a better job when we have a lot of other features to focus on.

**Comment by yaira2** [comment]
I'm going to assume that updating to v3.2 and clearing the thumbnail cache resolved this issue, but if it's still occurring, please let us know and we'll try to assist.
