### ISSUE TITLE
Feature: Add drive-related options to toolbar and context menu

### ISSUE THREAD

**Issue by 0x5bfa** [files-community/Files#14683]
### What feature or improvement do you think would benefit Files?

Add drive options to context menu and toolbar.

### Requirements

- Add the following actions to the toolbar overflow menu (options should be displayed in root folders, and when no items are selected)
   - Manage BitLocker
   - Cleanup
   - Optimize
   - Format
- The options should also be displayed when right clicking the sidebar, widgets, and in the root folder.

### Files Version

v3.4.1

### Windows Version

11 23H2

**Comment by yaira2** [comment]
> Fix an issue where the drive-related items are shown in layout pages

We're tracking this in https://github.com/files-community/Files/issues/14058

**Comment by 0x5bfa** [comment]
> We're tracking this in https://github.com/files-community/Files/issues/14058

Thanks

> This is already supported

More options can be added

> I think this is already supported in the Properties Window

Right...

> I believe this was by design

Wdym? Not adding an icno for it?

**Comment by 0x5bfa** [comment]
I believe I should close lol. and request only adding icons and adding more options to context flyout.

**Comment by yaira2** [comment]
> More options can be added

I suppose we can add an option to the "Network" section to map a drive. Can you open a feature request to track this idea?

> Wdym? Not adding an icno for it?

The icons are meant to help the more common actions stand out. If everything had an icon, it would defeat the purpose of having them in the first place.

**Comment by 0x5bfa** [comment]
I was thinking that this looks very odd and was wondering why not create with arrow overlay icon as we already have pane icon with "+".

![image](https://github.com/files-community/Files/assets/62196528/82e025fb-5a5a-48e0-9e95-a79623d03503)
![image](https://github.com/files-community/Files/assets/62196528/82fd7cc6-cab6-4378-812c-006bc8efb768)

**Comment by yaira2** [comment]
> Add drive-related AppBarButtons to InnerNavigationToolbar

Which options do you have in mind?
