### ISSUE TITLE
Bug: Changing sort direction requires multiple clicks

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#14685]
### Description

Changing the sort direction from the Data Grid headers requires multiple clicks.

### Steps To Reproduce

1. Switch to Details View.
2. Click the date column header.
3. It should switch to sorting by date but due to this bug, it requires multiple clicks.
4. This same issue applies to changing the sort direction

### Requirements

- Change the sort mode and sort direction with a single click

### Files Version

v3.2

### Windows Version

Windows 11

### Log File

NA

**Comment by hishitetsu** [comment]
I am unable to reproduce it.

**Comment by yaira2** [comment]
@hishitetsu it seems to be a little random, but it might help to switch between different directories.

**Comment by Josh65-2201** [comment]
This also applies to the tool bar sort menu

**Comment by hishitetsu** [comment]
I found that this occurs when the sync setting is on.
