### ISSUE TITLE
Drag and drop of files to another windows files should not create a shadow with all column info

### ISSUE THREAD

**Issue by MarathonMax** [files-community/Files#14687]
### Description

When I drag and drop a file across apps, the "shadow" (or ghost) of the file being dropped includes all columns instead of just the file name.

### Steps To Reproduce

1. Drag a file from Files to another window
2. Ghost image of file includes all columns

### Requirements

- e.g. Fix crash that occurs when...
No crash, just change the ghost image

### Files Version

3.2.0.0

### Windows Version

11

### Log File

[debug.log](https://github.com/files-community/Files/files/14227392/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #12556. You can check there or click subscribe in the right sidebar for updates.

**Comment by MarathonMax** [comment]
tks
