### ISSUE TITLE
Display issues

### ISSUE THREAD

**Issue by MarathonMax** [files-community/Files#14686]
### Description

Files has improved a lot since the last time I used it about a year ago. It truly is a better UI ... but it still has some issues, like the display issue I am experiencing. I used it tucked to the right of my screen, and it switches to compact mode (without the side panel). Renaming folders does not display names correctly. I don't know if this has to do with compact mode, but I struggle to navigate up and down the folder hierarchy because folder names are messed up.

### Steps To Reproduce

1: hit F2 to rename file
2. Rename file and hit Enter to finish
3. Boom. Names are corrupt.

### Requirements

Renaming files should be an easy use case to solve.

### Files Version

3.2.0.0

### Windows Version

10.0.22621.3007

### Log File

[debug.log](https://github.com/files-community/Files/files/14227372/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Can you send a screenshot of what you mean by the names being messed up
