### ISSUE TITLE
Bug: Unable to click on the close button in the upper right corner when maximizing

### ISSUE THREAD

**Issue by MNDIA** [files-community/Files#14697]
### Description

Bug: Unable to click on the close button in the upper right corner when maximizing.

_describe_
When **maximizing**, the **close button** in the **upper right** corner of the files panel：

1. The mouse cannot click the "close" function on the pixel in its upper right corner. (Habitually throwing the mouse to the upper right corner of the screen to close the window to the limit)
![image](https://github.com/files-community/Files/assets/74826767/687f1eec-5625-4a16-95d6-f55dd175964f)

2. At its edge, **a row of pixels** (including the pixel in the upper right corner), the mouse will trigger the **zoom** window function. (Just a triggering function, cannot change the actual size seen)
![image](https://github.com/files-community/Files/assets/74826767/60174fb9-9bbb-4015-86b1-5842dbfe4462)
![image](https://github.com/files-community/Files/assets/74826767/45266c8d-9487-461f-a0c5-8daf020fb626)

3.It should be:
![image](https://github.com/files-community/Files/assets/74826767/644f1ef0-ab1c-49dd-93b1-57b0b4d534c1)

### Steps To Reproduce

1. Open the Files panel
![image](https://github.com/files-community/Files/assets/74826767/ffeddb9f-0b98-4b74-bf6a-40db5479e18b)

2. Maximize it
![image](https://github.com/files-community/Files/assets/74826767/8ce7277e-385c-44a9-9d39-1d8ac9264812)

3. The limit of throwing the mouse to the top right corner of the screen
![image](https://github.com/files-community/Files/assets/74826767/fc41d215-8b57-4be4-8427-ef14ff89a01a)

4. Unable to determine the close function

### Requirements

It should be **red color**:
![image](https://github.com/files-community/Files/assets/74826767/644f1ef0-ab1c-49dd-93b1-57b0b4d534c1)

And when When the mouse is **over edge pixels**
![image](https://github.com/files-community/Files/assets/74826767/9e4435a0-c788-4eaf-a187-996f0342f1e4)

### Files Version

3.2.0.0

### Windows Version

10.0.22621.2283

### Log File

[debug.log](https://github.com/files-community/Files/files/14233315/debug.log)

**Comment by MNDIA** [comment]
Personal analysis: When maximizing, the scaling function should not be triggered at the edge, which may be a UI layout issue

**Comment by yaira2** [comment]
Thank you for sharing your feedback. This is a known issue with the WinAppSdk framework where extending tabs into the title bar prevents users from dragging the window or clicking the close button from the top pixel. There isn't any workaround, but it would help if you shared this feedback with Microsoft on the WinUI repository to let them know this is impacting your workflow.
