### ISSUE TITLE
Flashing when copying/moving files

### ISSUE THREAD

**Issue by Raven-713** [files-community/Files#14690]
### Description

When moving or copying a file, once the action is executed the screen flashes as if reloading each time a file is moved. 

### Steps To Reproduce

1. select files 
2. select action (copy / Cut)
3. select location to move to
4. past
5. 

### Requirements

- e.g. Fix crash that occurs when...
preferable no flashing, p[possible a smoother screen experience similar to the original windows explorer will make it a more pleasing experience as well as interface look 

### Files Version

3.2.0.0

### Windows Version

10.0.22631.3085

### Log File

[debug.log](https://github.com/files-community/Files/files/14229640/debug.log)

**Comment by yaira2** [comment]
Thank you for the report, we're currently tracking this in #4214. The issue mentions renaming but it also applies to other file operations.
