### ISSUE TITLE
Does anyone want a macOS/iPadOS like column view?

### ISSUE THREAD

**Issue by TyJOrtiz** [files-community/Files#147]
![image](https://user-images.githubusercontent.com/25320332/59843303-210f0080-930d-11e9-9d54-215d3f9233e8.png)

**Comment by yaichenbaum** [comment]
Definitely not by default but having it as an extra option would be welcome.

**Comment by duke7553** [comment]
This can be part of the eventual tablet-optimized UI

**Comment by duke7553** [comment]
Great idea!

**Comment by yaichenbaum** [comment]
Oh, can't wait to see a tablet optimized option. Windows can really use one.

**Comment by Telescuffle** [comment]
Yes, please!

**Comment by duke7553** [comment]
@imthewiseguy Were you going to build this? I can assign it to you.

**Comment by imthewiseguy** [comment]
@duke7553 yeah

**Comment by imthewiseguy** [comment]
to preserve the existing functionality ill have the app to launch the column view in a new window, until i can  integrate it without breaking anything

**Comment by imthewiseguy** [comment]
sorry

**Comment by duke7553** [comment]
If you need any help finding your way around the code please let me know. I’m going to be AFK for one week, but I’ll try my best.

**Comment by duke7553** [comment]
I would recommend detecting if the device is in tablet mode and then navigate to the appropriate layout on startup.

**Comment by imthewiseguy** [comment]
![image](https://user-images.githubusercontent.com/25320332/60679613-1724eb80-9e3d-11e9-9df6-c07ba0837553.png)

I wanted to see what people thought of this. I put the context menu commands in the preview pane (I was playing around with styles, i wont leave it iOS-like lol)

**Comment by yaichenbaum** [comment]
That is sleek, can you share a screenshot of it in light mode?

**Comment by imthewiseguy** [comment]
![image](https://user-images.githubusercontent.com/25320332/60738875-a5b86c00-9f14-11e9-81b6-7cb369b028fb.png)

**Comment by duke7553** [comment]
@imthewiseguy Are these changes open sourced yet? I'd like to help you work on them.

**Comment by mkmukund** [comment]
i'm damm desperate for this feature.....

**Comment by imthewiseguy** [comment]
I’m sorry everyone, i haven’t had much progress on this because I’ve been dealing with a death in the family among other things. I’ll try to make headway on this project soon

**Comment by duke7553** [comment]
@imthewiseguy I'm really sorry to hear that. There's no rush at all for this. Take as long as you need.

**Comment by yaichenbaum** [comment]
@imthewiseguy It's totally ok if you are not going to finish this feature, would you mind giving us an update on your plans?

**Comment by imthewiseguy** [comment]
HI,

I need to get the latest version of the project. and then change some code and then integrate it. I'm going to be working on that today

**Comment by yaichenbaum** [comment]
Excellent, if you need any help with the code base just tag @duke7553.

**Comment by imthewiseguy** [comment]
[ColumnPage.zip](https://github.com/duke7553/files-uwp/files/3856193/ColumnPage.zip)

 here's the source code for the column view if anyone wants to do any change to it

**Comment by duke7553** [comment]
The work we've done should streamline some of the process of adding new layouts. Expect to hear more about this after Launch. 😉

**Comment by imthewiseguy** [comment]
That sounds cool! I've been working on this feature in the meantime just on a separate app so i don't break anything

**Comment by duke7553** [comment]
My vision is to allow contributors to work on/maintain their layouts without having to worry about breakage. We're in the process of abstracting away some of the tedious details of layout modes. I'm still using the work you submitted above to test against 😃

**Comment by Chris2011** [comment]
Yes, great work. I also wanted to add this feature right after I found thi great tool here 😀. Glad that still some other people are thinking about it :)

**Comment by mdtauk** [comment]
https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/bladeview

With some added shadows would be great.  There will also need to be some horizontal scrolling

**Comment by Chris2011** [comment]
Definitely, I don't like autoshrinking. I think the Mac OS finder has a setting for fixed width and if you have more columns than space on the screen, it get's a scrollbar.

**Comment by TyJOrtiz** [comment]
I'll be back on working on it then

**Comment by TyJOrtiz** [comment]
![image](https://user-images.githubusercontent.com/25320332/100693821-82c8fc00-3342-11eb-9fd5-5eaf30e3e5b0.png)

I'm getting the ColumnView working, I just need to know how can I create a dynamic list of items in a selected folder to open another column?

**Comment by yaichenbaum** [comment]
@TyJOrtiz You should be able to get the path of the selected item with `listedItem.Path`.

**Comment by TyJOrtiz** [comment]
I see that but I need to know how to create an ObservableCollection<ListedItem> with the files and folders contained in the `listedItem.ItemPath`

**Comment by yaichenbaum** [comment]
@TyJOrtiz ItemViewModel has both `EnumerateItemsFromStandardFolderAsync` and `EnumerateItemsFromSpecialFolderAsync`.
fyi @duke7553

**Comment by TyJOrtiz** [comment]
I got the column view working (sorta, none of the menu options except Layout Mode work)

![image](https://user-images.githubusercontent.com/25320332/100702970-80bd6800-3357-11eb-9151-c0cd6fbec5a6.png)

I'll create a pull request

**Comment by mdtauk** [comment]
You may want to consider the selected item styling for the inactive columns.  I believe only the active Colin should use the filled in accent colour style, whilst the inactive columns could use an accent coloured border instead, or filled in a grey colour.

It will help those with accessibility issues, and those using keyboarding to navigate, to tell where the active view is.

**Comment by TyJOrtiz** [comment]
![image](https://user-images.githubusercontent.com/25320332/100710647-da785f00-3364-11eb-9a0b-ff6fd7640cc5.png)

like this?

**Comment by TyJOrtiz** [comment]
![image](https://user-images.githubusercontent.com/25320332/100710799-23c8ae80-3365-11eb-8ab8-ae4f4c7980b8.png)

Light mode

**Comment by mdtauk** [comment]
That fits the bill yes!

**Comment by duke7553** [comment]
@TyJOrtiz Currently, we only have support for populating the read only observable collection FilesAndFolders which can be accessed from an instance of ItemViewModel. To populate the observable collection, the layout modes internally call RefreshItems(). 

If your layout mode has any specific needs from ItemViewModel, we can help you with that 🙂

**Comment by TyJOrtiz** [comment]
That would be great if there was a way to get an observable Collection like FilesAndFolders from a selected folder, the way I'm doing it now doesn't have support for OneDrive File availability or file icons.

**Comment by lucandrei** [comment]
> ![image](https://user-images.githubusercontent.com/25320332/100710647-da785f00-3364-11eb-9a0b-ff6fd7640cc5.png)
> 
> 
> 
> like this?

Phenomenal work! Keep it up ❤️❤️

**Comment by jimsalabim22** [comment]
This looks amazing, is there any way to test/ use it curently on my Pc?

**Comment by yaichenbaum** [comment]
This feature has been implemented in #4176. Please note that it's still under development and that further improvements can be expected before it's released in the Microsoft Store.
