### ISSUE TITLE
Bug: Some thumbnails display too small

### ISSUE THREAD

**Issue by Qin-shihuang** [files-community/Files#14705]
### Description

 In Tiles Layout and Grid Layout, certain file thumbnails appear smaller than normal and are positioned in the top-left corner.

<img width="346" alt="image" src="https://github.com/files-community/Files/assets/68013339/bba20ef5-7fe3-4e72-a18d-08a1ed5bb09c">

It seems that icons with smaller resolution cause this issue. The two icons in the screenshot have a resolution of 32x32.

[icon.zip](https://github.com/files-community/Files/files/14240143/icon.zip)

### Steps To Reproduce

1. Change layout to Tiles
2. Observe that some icons have incorrect size

### Requirements

Thumbnails should display correctly

### Files Version

3.2.0.0

### Windows Version

10.0.22631.3085

### Log File

No log for that.

**Comment by yaira2** [comment]
Thanks for the feedback, this was recently fixed in the dev branch and will be included in the next release.
