### ISSUE TITLE
Vertical scroll bar

### ISSUE THREAD

**Issue by Divers-Seki** [files-community/Files#14704]
### What feature or improvement do you think would benefit Files?

Vertical scroll bars are too small and difficult to move
I want it to be the same size as the standard Explorer

### Requirements

Vertical scroll bars are too small and difficult to move
I want it to be the same size as the standard Explorer

### Files Version

3.2.0.0

### Windows Version

10.0.19045.3930

### Comments

Vertical scroll bars are too small and difficult to move
I want it to be the same size as the standard Explorer

**Comment by Josh65-2201** [comment]
Thaks for the feedback, have you tried enabling Windows settings > Accessibility > Visual effects > Always show scrollbars?

**Comment by Divers-Seki** [comment]
Already enabled.
The problem is that the scrollbar itself is not thick enough.
They are too thin and difficult to move with the mouse.
See attached file.
If there were a large number of files in a folder, don't you think such a small thin scrollbar would be too thin to move with the mouse?


![20240213](https://github.com/files-community/Files/assets/92518847/349eb48e-a088-41d7-b5f5-3f4cd1ee006b)

**Comment by Josh65-2201** [comment]
The scrollbar is the same size as Windows File Explorer it just looks smaller because it not full width of the track but can still be dragged. Files also is using the styles of WinUI which is based on Windows 11 so the look of it probably won't change.

**Comment by Josh65-2201** [comment]
I have noticed that Files scroll bar doesn't responded when you fully move the mouse to the right of the screen. Is that what you are trying to do when scrolling?

**Comment by yaira2** [comment]
Thank you for your feedback, as Josh mentioned, Files is using the default WinUI styles for the ScrollBar and we don't have plans to change this. We encourage you to share this with Microsoft on their WinUI repo so they can take your feedback into account https://github.com/microsoft/microsoft-ui-xaml.
