### ISSUE TITLE
Popup when opening Files.

### ISSUE THREAD

**Issue by chooky19** [files-community/Files#14703]
### Description

Whenever I open Files, wsl.exe tries to open as well. Why is it looking for Linux? 

Win 11
![Files](https://github.com/files-community/Files/assets/51835591/2b65e9f3-ff9b-4fe0-a7cb-de25c71d4bf8)

### Steps To Reproduce

Open Files.

### Requirements

- e.g. Fix crash that occurs when...
Expected to be no popup.

### Files Version

3.2.0.0

### Windows Version

11pro 24H2

### Log File

[debug.log](https://github.com/files-community/Files/files/14238073/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, this is an issue with Windows Dev and Canary builds not Files.
