### ISSUE TITLE
Hardlinks in context menu

### ISSUE THREAD

**Issue by specurial** [files-community/Files#14702]
### What feature or improvement do you think would benefit Files?

there is app for add hard links (referred to herein as Hardlinks) "HardLinkShellExt_X64"
their website : https://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html
we need those item in context menu for Files App
![explorer_61RjArXUTl](https://github.com/files-community/Files/assets/75868341/11657730-7cb1-4a8e-acac-a6b7d53b8228)
![chrome_2alzYCbNE8](https://github.com/files-community/Files/assets/75868341/b33a86ea-7373-4ed4-8eb4-48622e800b28)
there is one of them right now but its not working at all cuz i cant drop any link when i didnt picked link source and when i tried to pick link source in windows file explorer and drop it when i use files app the option in context menu is disappear!
![Files_XUVBcap8jO](https://github.com/files-community/Files/assets/75868341/2d4ce2e0-ef97-4c46-a6b1-5c488cca8ee8)

btw they didnt update their app for long time, cuz it works good even in win11 :D so we cant ask them for add this option for your files app context menu

### Requirements

 Hardlinks in context menu
  - Pick link resource
  - drop as...
  - cancel link creation

### Files Version

3.2.0.0

### Windows Version

22631.3085

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #9991. You can check there or click subscribe in the right sidebar for updates.
