### ISSUE TITLE
Bug: The exe application launched through Files has an incorrect parent relationship in the task manager

### ISSUE THREAD

**Issue by MNDIA** [files-community/Files#14706]
### Description

After **double clicking in Files** to open Steam.exe, Discovered in task management 
![image](https://github.com/files-community/Files/assets/74826767/bd084e4a-3a7c-4026-a3fc-8cd3ede26b9c)
"Steam. exe" is identified as the process of "Files"
This context is **incorrect**, or there may be a **parent-child relationship**

Then I **double clicked on Steam. exe using the Explorer** to open it. The parent-child relationship is normal, and "Steam. exe" is in a separate background process.
![image](https://github.com/files-community/Files/assets/74826767/70cc0cb9-bcc9-4e9b-916f-fabb9ac63b9a)

Comparing and excluding methods, the only difference is whether to open Steam. exe through Files or Explorer

### Steps To Reproduce

1. Open Files
2. Move the mouse and double-click the Steam :(shortcut or directly open Steam.exe)
![image](https://github.com/files-community/Files/assets/74826767/e9959c8d-f7c0-4561-8849-e5abe10fb1fa)
![image](https://github.com/files-community/Files/assets/74826767/8afc4312-ae4c-4843-9883-b0ab87fda0ad)

4. Open Task Manager
5. Discovering chaotic ownership relationships
![image](https://github.com/files-community/Files/assets/74826767/07c241f1-c256-4847-bc36-fc2014f76411)

### Requirements

![image](https://github.com/files-community/Files/assets/74826767/256ada60-a4de-40f6-b6f9-ae7218524a2f)
This is the **result opened through Explorer**, **which should** have opened the same correctly running **result as Files**

### Files Version

3.2.0.0

### Windows Version

10.0.22621.2283

### Log File

[debug.log](https://github.com/files-community/Files/files/14241152/debug.log)

**Comment by 0x5bfa** [comment]
Can you check if this also happens with other executable files?

**Comment by MNDIA** [comment]
Not just Steam. For example, it will also:
![image](https://github.com/files-community/Files/assets/74826767/3cac95e4-550f-44d6-a57b-ddca1d4d0035)

After my investigation, I can confirm this issue.
1. It has no causal relationship with the "advanced testing function for modifying the registry"(Whether turned on or off, it does not affect the occurrence of problems)
![image](https://github.com/files-community/Files/assets/74826767/dff607af-b11e-4393-a410-6aefc776ea5c)

2. It is highly likely to be related to Webview2
![image](https://github.com/files-community/Files/assets/74826767/69336db7-0e92-4afc-9886-d4ce1d816267)
As far as I know, Steam uses the web to display some things
![image](https://github.com/files-community/Files/assets/74826767/62786b64-c259-4cc6-8ebc-76db980b4ac8)
And then another example in the first picture, "Nyanpsu", whose project requires a WebView2 environment to run
![image](https://github.com/files-community/Files/assets/74826767/fc380beb-4be8-4364-9193-85234aebbe6e)

**Comment by Josh65-2201** [comment]
Steam doesn't use Webview2 they bundle in there own chromium build for web content.

**Comment by MNDIA** [comment]
Okay, so the commonality of the problem should be related to the web, not necessarily webview2

**Comment by yaira2** [comment]
I'm pretty sure this behavior is intentional. Windows identifies the parent process (eg Files) that initiated the file. You can verify this by launching programs through PowerShell. When you open programs via File Explorer, they appear higher in the process tree because the Explorer shell acts as their parent process.

There are ways to work around this, but I don't think they are not officially supported and could potentially be viewed as malicious.
