### ISSUE TITLE
Titlebar Buttons Icons to be Made Platform Dependant

### ISSUE THREAD

**Issue by D-Maxwell** [files-community/Files#14712]
### What feature or improvement do you think would benefit Files?

hello there ;

As things currently stand, the Files App displays Windows11 styled buttons in its titlebar.
Having remained on Windows10 for the time being (LEENOOX, here I come ; eventually), these icons ever so slightly differ from those native to my system version.

### Requirements

I am not asking for these to respect any custom skin one may have applied one way or another ; for one, as there is no standardised way to do so on NT, and secondly, because that would be much too difficult and most likely not worth the effort ; nor am I asking for the UI to follow the general style of the OS, even though a roundedness of zero would be quite nice on Windows10.

Instead, I reckon a simple dictionary linking OS versions to a set of icons would be a nice solution.

### Files Version

3.2.0.0

### Windows Version

10.0.19045.2788

### Comments

This is of very little matter, and would only result in a difference of a few pixels ; I am fully aware of this, and would not be surprised if it were to be rejected. Although, given that this would require such little effort, this makes it quite a single task to check off the list of UI-to-system cohesion.

**Comment by yaira2** [comment]
Thank you for your feedback. If you have a good way to implement this, we'd be happy to accept but as far as we're aware this scenario isn't officially supported by WinAppSdk.
