### ISSUE TITLE
Bug: GitHub login prompt closes instantly

### ISSUE THREAD

**Issue by InfinityDevTech** [files-community/Files#14718]
### Description

Hello!

When I attempt to login with github, it ususally closes the settings modal and does nothing, but I have discovered that it is actually just flashing the login modal really fast then closing it.

### Steps To Reproduce

1. Download and install
2. Attempt to login to github
3. Sad.

### Requirements

- Be able to login to github
- Modal stays open
- More logs

### Files Version

3.2.0.0

### Windows Version

10.0.22631.3085

### Log File

[debug.log](https://github.com/files-community/Files/files/14274665/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board. Also how are you attempting to log in to GitHub?

**Comment by InfinityDevTech** [comment]
> Thanks for the report; I've added this to the project board. Also, how are you attempting to log in to GitHub?

![image](https://github.com/files-community/Files/assets/47366052/6c0d9027-61ca-4636-bcec-8ace1458f78a)

This button is in settings.

I think it has something to do with the settings, as I have imported the settings from a device I barely got it working on, and it worked on the first try. So there is something conflicting in there.

**Comment by yaira2** [comment]
This issue is fixed in our dev branch and will be included in the next release. In the meantime, trying to push to a Git repo will display a prompt to login so you won't miss any functionality.
