### ISSUE TITLE
Add a Length column for Details layout

### ISSUE THREAD

**Issue by FlyingToaster** [files-community/Files#14716]
### What feature or improvement do you think would benefit Files?

When viewing a folder with video or audio/music files in the Details layout, one column I often find useful in Windows Explorer is the Length column, which shows the length of video & audio files.  This is something I would find useful in Files (which has much fewer Details columns than Windows Explorer).

### Requirements

This will make it easy to see the lengths of video & audio files from within Files, without having to open the file in a player.

### Files Version

3.2.0.0

### Windows Version

10.0.22621.3007

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #8366 . You can check there or click subscribe in the right sidebar for updates.
