### ISSUE TITLE
Bug when making changes on document while having the side preview ON. 

### ISSUE THREAD

**Issue by Aghyads** [files-community/Files#14714]
### Description

When I edit a word or excel file, the current window moves from the word/excel app to the folder (files app) as there is a change made to the original document. This might be happening as I have side preview on. 

### Steps To Reproduce

1. Open the files app and enable side preview 
2. create new excel or word file
3. adjust/edit the excel/word file (inside the file) 
4. while editing/working on the file, if you have clicked on the file from the files window, then after that started working on the excel or word file, then you will see the problem. 

### Requirements

Fix crash that occurs when editing file and having the side preview on.

### Files Version

3.2.0.0

### Windows Version

10.0.19045.3996

### Log File

[debug.log](https://github.com/files-community/Files/files/14270787/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, we were last tracking in #13348 but we haven't been able to repro the issue for some time. Can you add a comment to #13348?
