### ISSUE TITLE
Change the distance between file name (like macos). Grid spacing and Icon size. 

### ISSUE THREAD

**Issue by Aghyads** [files-community/Files#14725]
### What feature or improvement do you think would benefit Files?

Can you please maybe add the same function of finder of MacOs. 
1- Grid spacing 
2- Icon size

Sometimes when the file or document has a long name, i'm not always able to preview the whole name with my preferred view. I should change the view to see the full name.

### Requirements

1- Grid spacing 
2- Icon size

### Files Version

3.2.0.0

### Windows Version

10.0.19045.4046

### Comments

Thnx!

**Comment by yaira2** [comment]
Thank you for your feedback, we're tracking this in #10492.
