### ISSUE TITLE
Bug: Path breadcrumb alignment is off except last segment

### ISSUE THREAD

**Issue by foriequal0** [files-community/Files#14722]
### Description

![image](https://github.com/files-community/Files/assets/5465658/6440649c-6a79-499f-a118-24f4fc9f6a4e)
The last segment seems to be aligned while the previous segments aren't.

I think `TextLineBounds = Full` here makes all text alignment a little bit off, especially for non-latin languages:
https://github.com/files-community/Files/blob/c6ad49c50b9c163cd4dab99d7d59dad9066b5240/src/Files.App/ResourceDictionaries/App.Theme.TextBlockStyles.xaml#L11
And I think this is why manual `Padding` adjustments are prevalent here and there:
https://github.com/search?q=repo%3Afiles-community%2FFiles%20padding&type=code
including the last segment of the path breadcrumb:
https://github.com/files-community/Files/blob/c6ad49c50b9c163cd4dab99d7d59dad9066b5240/src/Files.App/UserControls/PathBreadcrumb.xaml#L71

We might be able to utilize the typographic options.
https://blogs.windows.com/windowsdeveloper/2013/11/11/xaml-text-improvements-in-windows-8-1/
I believe that it would make the app more resilient to font-related alignment issues.

I think this is the right place to do:
https://github.com/files-community/Files/blob/c6ad49c50b9c163cd4dab99d7d59dad9066b5240/src/Files.App/ResourceDictionaries/App.Theme.TextBlockStyles.xaml#L4

### Steps To Reproduce

1. Navigate to some directories
2. See path segments

### Requirements

Baselines should be aligned.

### Files Version

3.2.0.0

### Windows Version

Windows 11, 23H2, 22631.3155

### Log File

-

**Comment by yaira2** [comment]
Thank you for your feedback, I think this is due to the bold font style.

**Comment by 0x5bfa** [comment]
@yaira2 A bit off. We could make a fix.

https://github.com/files-community/Files/assets/62196528/b2f083f2-c8f0-4334-a53e-dacbc689b8be

**Comment by foriequal0** [comment]
Thanks! I'll add some more examples here.

- search box
![image](https://github.com/files-community/Files/assets/5465658/854cc677-0d47-4124-82d0-15ab56116293)

- texts in the sidebar, tooltips
![image](https://github.com/files-community/Files/assets/5465658/9b3b8c92-721d-4d45-a3da-63171d85e368)

I think when `Padding` is manually adjusted for "Segoe UI" and 100% scale, non-Latin texts look off, and when isn't, Latin texts look off.

**Comment by 0x5bfa** [comment]
I'm a Japanese and it seems that this also happens in Japanese.

![image](https://github.com/files-community/Files/assets/62196528/a15d4e4d-7246-4bb3-a726-a91a2421b5c6)

**Comment by 0x5bfa** [comment]
@yaira2 Confirmed that using Segoe UI Variable fixes this perfectly. Hopefully looks like they made it default in v1.6 of WASDK. We can close I think.

**Comment by yaira2** [comment]
Great!

**Comment by yaira2** [comment]
@foriequal0 this issue should be resolved when the WinAppSdk framework is updated to 1.6. This depends on Microsoft's timeline but it should in the next few months.

**Comment by foriequal0** [comment]
They are much better now, but they're still 1px off...

**Comment by yaira2** [comment]
We haven't updated to WinAppSdk 1.6 yet.
