### ISSUE TITLE
标签查看错误

### ISSUE THREAD

**Issue by SimpleDeath** [files-community/Files#14729]
### Description

当设置分组时并按类型分组，点击标签内容空白

### Steps To Reproduce

hhh

### Requirements

- e.g. Fix crash that occurs when...
吱吱吱

### Files Version

3.2.0.0

### Windows Version

10.0.19045.4046

### Log File

jj

**Comment by Josh65-2201** [comment]
Thanks for the report, can you give the following infomation
- Steps to reproduce
- Can you please upload (Do not copy and paste content) the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.
- A screenshot of what you are seeing (Win + Shift + S)
