### ISSUE TITLE
Dragging a compressed file from 7Zip into the Files interface results in an error "File not found"

### ISSUE THREAD

**Issue by thebeersmith** [files-community/Files#14721]
### Description

Dragging a compressed file from 7Zip into the Files interface results in an error "File not found". The detailed message is "The file you are attempting to access may have been move or deleted"

### Steps To Reproduce

1. Open a compressed file in 7Zip.
2. Drag the files you wish to unzip to the target location within "Files"

### Requirements

- e.g. Fix crash that occurs when...
Error message: "File not found". The detailed message is "The file you are attempting to access may have been move or deleted"

### Files Version

3.2.0.0

### Windows Version

10.0.22631.3155

### Log File

The log contains work related information... not uploaded.

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #14636 . You can check there or click subscribe in the right sidebar for updates.
