### ISSUE TITLE
Opening a new file window won't bring the app to the front if it is behind another window.

### ISSUE THREAD

**Issue by Aghyads** [files-community/Files#14724]
### Description

Hello dear, 
So I have a shortcut for opening the files in Explorer with a keyboard shortcut. When I did that earlier with File Explorer, the window was coming to the front of the active screen. Now with the file app of yours, when I click the same shortcut, it will open a new window, but it won't bring it to the front; it will open a new window inside or near the old opened window, which is behind the active app, for example. 
Can you please fix that? 

### Steps To Reproduce

1. Open files.
2. Open any other app, like Chrome, and bring Chrome to the front.
3. Now click the shortcut to open a new window or the Files app again. 
4. It won't come to the front as an active window; it will stay in the background. Even when a new tap is opened,. 

### Requirements

Files stay in background when opening a new files tap or window. 

### Files Version

3.2.0.0

### Windows Version

10.0.19045.4046

### Log File

[debug.log](https://github.com/files-community/Files/files/14282640/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, What shortcut are you using? Is it done from another program?

**Comment by yaira2** [comment]
Can you please open this as a feature request? "Bring Files window to foreground when opening via win+e"
