### ISSUE TITLE
Remember opened tabs

### ISSUE THREAD

**Issue by MarathonMax** [files-community/Files#14736]
### What feature or improvement do you think would benefit Files?

Like with Chrome and other browsers, I would like Files to remember opened folders, tabs and windows when restarting.

### Requirements

- This proposal will improve Productivity
- This proposal will improve Usability

### Files Version

3.2.0.0

### Windows Version

10.0.22631.3155

### Comments

Merci

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #12624. You can check there or click subscribe in the right sidebar for updates.
