### ISSUE TITLE
Copied pdf cannot be deleted as it's open in Files

### ISSUE THREAD

**Issue by swoodvitsoe** [files-community/Files#14734]
### Description

When you make a copy of a pdf file then try to delete the copy, it says it's currently in use by Files.

### Steps To Reproduce

1. Copy some pdf files into a new (temporary) directory
2. Attempt to delete the directory
3. Any pdf files are shown as 'in use' by Files

### Requirements

It should be possible to delete pdf files which aren't open.

### Files Version

3.2.0.0

### Windows Version

10.0.22631

### Log File

I'm not permitted to as the device contains confidential items. But the issue happens every time with any .pdf file.

**Comment by swoodvitsoe** [comment]
The only way to get around this is to use Task Manager to locate and kill off the Files process, then restart it.

**Comment by yaira2** [comment]
Are the PDFs open in the preview pane?

**Comment by swoodvitsoe** [comment]
No, they have simply been copied but somehow that is causing them to be seen as open in files.
The last time I tried it, I copied 15 files including 3 pdfs. All other files could be deleted from the new folder, except the pdf files.

**Comment by yaira2** [comment]
Is this specific to pdf files?

**Comment by swoodvitsoe** [comment]
I've only seen it with pdf files, yes

________________________________

**Comment by yaira2** [comment]
Which PDF application do you have on your device?

**Comment by yaira2** [comment]
@swoodvitsoe fyi
