### ISSUE TITLE
Feature: Bring Files window to foreground when opening using shortcuts (Win + E)

### ISSUE THREAD

**Issue by Aghyads** [files-community/Files#14730]
### What feature or improvement do you think would benefit Files?

Hello dear, 
So I have a shortcut for opening the files in Explorer with a keyboard shortcut. When I did that earlier with File Explorer, the window was coming to the front of the active screen. Now with the file app of yours, when I click the same shortcut, it will open a new window, but it won't bring it to the front; it will open a new window inside or near the old opened window, which is behind the active app, for example. 
Can you please fix that? 

### Requirements

Steps To Reproduce
Open files.
Open any other app, like Chrome, and bring Chrome to the front.
Now click the shortcut to open a new window or the Files app again. 
It won't come to the front as an active window; it will stay in the background. Even when a new tap is opened.

### Files Version

3.2.0.0

### Windows Version

10.0.19045.4046

### Comments

Thank you!

**Comment by Josh65-2201** [comment]
Thanks for the feedback, I've added this to the project board.

**Comment by 0x5bfa** [comment]
This issue has been fixed and this fix will be included in the next release.

Thank you for the feedback, again.
