### ISSUE TITLE
Bug: Arrow key folder navigation uses pervious selected position when going in sub folders.

### ISSUE THREAD

**Issue by MarathonMax** [files-community/Files#14738]
### Description

When entering a folder containing subfolders and files, hitting the down arrow skips to the first file instead of going to the second folder

### Steps To Reproduce

1. Hit enter to go into a folder
2. First sub folder is selected
3. Hit down arrow to attempt to select second sub folder
4. Selection goes to first file (instead of second folder)

### Requirements

Make it so that second folder is selected instead of file

https://github.com/files-community/Files/assets/7364694/1879a2c8-a6f1-4a77-bdc4-78008f3e4660

### Files Version

3.2.0.0

### Windows Version

10.0.22631.3155

### Log File

[debug.log](https://github.com/files-community/Files/files/14304068/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
Thank you for the report, the underlying issue is the same as #13774. You can click subscribe or add a comment to be notified when it's resolved.
