### ISSUE TITLE
More Options in the 'Details' view

### ISSUE THREAD

**Issue by dercas79** [files-community/Files#14748]
### What feature or improvement do you think would benefit Files?

One feature that is necessary for me to even use this app is the ability to sort files quickly, not just by name, date and file size, but also by video length, audio bitrate and resolution.  As a video DJ, these are some of the tools that I use when I stream.

I very much like the look of the app so far though and I will stay tuned for future updates to see if this is implimented.  Thank you for your time and attention. ;-D

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z
See the above details.

### Files Version

3.2.0.0

### Windows Version

10.0.22631.3155

### Comments

I've never made a purchase on the Microsoft Store before tonight.  I hope that this app is continuing to be actively developed.

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #8366. You can check there or click subscribe in the right sidebar for updates.

**Comment by dercas79** [comment]
Thank you very much for the prompt notification. ❤️



"Gossip, Violence, Hate, Fear, and Anger.  I can choose not to let them
continue and to instead pass on Kindness and Joy." - Me

"Darkness cannot drive out darkness, only light can do that. Hate cannot
drive out hate, only love can do that."  - Dr. Martin Luther King Jr.
