### ISSUE TITLE
How to add cloud drives to the files program?

### ISSUE THREAD

**Issue by naumgod** [files-community/Files#14747]
### What feature or improvement do you think would benefit Files?

How to add cloud drives to the files program? Such as Google drive, Yandex drive, mail drive, webdav??? And you could add, for example, 10 different Google cloud drive accounts.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.2.0.0

### Windows Version

10.0.22631.3155

**Comment by Josh65-2201** [comment]
Please read https://files.community/docs/features/cloud-drives
