### ISSUE TITLE
Icon Packs Feature Request

### ISSUE THREAD

**Issue by katastrophe92** [files-community/Files#14740]
### What feature or improvement do you think would benefit Files?

Icons Packs for UI and the ability to set a Icon Pack to all Files and Folder at once
Other Icons in the _Customization Tab_ for Files and Folder besides the ones from C:\Windows\System32\SHELL32.dll

### Requirements

Open Source icon packs

### Files Version

3.2.0.0

### Windows Version

10.0.22631.3155

**Comment by yaira2** [comment]
Thank you for your feedback, we're currently tracking this request in #10941. It's mainly requesting folder icons but you can add a comment regarding file icons as well.
