### ISSUE TITLE
Bug: ALT+D makes Windows error sound

### ISSUE THREAD

**Issue by jefflord** [files-community/Files#14743]
### Description

ALT+D makes Windows error sound. It makes it sound like it's not working. Sometimes it seems like it does not but usually works fine. CRTL+L does not make the Windows error sound. 

### Steps To Reproduce

1. Push "ALT+D"
2. Unfocus path bar and see error

### Requirements

Find out what is causing the sound (is there a real error there also?) and fix it. 

### Files Version

3.2.0.0

### Windows Version

11

### Log File

NA

**Comment by yaira2** [comment]
Do you have sticky keys enabled?

**Comment by jefflord** [comment]
> Do you have sticky keys enabled?

Nope.

**Comment by yaira2** [comment]
It sounds like there is some sort of conflict, either with your keyboard or another program on your device. You can avoid this by either by changing the shortcut in Files https://files.community/docs/customize-settings/actions#:~:text=Ctrl%2BZ%22%20%7D-,Edit%20path,-Focuses%20the%20path or by using ctrl+l.

**Comment by yaira2** [comment]
I can repro this as well

**Comment by hishitetsu** [comment]
Not only the D key, but any key will make the sound. It seems a WinUI 3 issue.
https://github.com/microsoft/microsoft-ui-xaml/issues/8554

**Comment by yaira2** [comment]
@jefflord given this is an issue with the framework, we're going to close this issue in favor of the report on the WinUI repo. You can add a comment or click subscribe to be notified when Microsoft fixes the issue.
