### ISSUE TITLE
windows 10 taskbar not showing when set on autohide  

### ISSUE THREAD

**Issue by Morceguillo** [files-community/Files#14753]
### What feature or improvement do you think would benefit Files?

when using Files on full screen, windows taskbar not coming back when set on autohide so I have to press the windows logo key on my fisical keyboard to see it.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.5.21.0

### Windows Version

10.0.19045.3930

**Comment by Josh65-2201** [comment]
The is fixed in 3.2.0.0. https://files.community/download
