### ISSUE TITLE
Github Login doesn't work

### ISSUE THREAD

**Issue by sky47sky** [files-community/Files#14758]
### Description

When I click "Login" to Github the window just closes and nothing happens.

### Steps To Reproduce

click "Login" in the "Connect to Github" area.

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.2.0.0

### Windows Version

10.0.22621.3155

### Log File

[debug.log](https://github.com/files-community/Files/files/14320689/debug.log)

**Comment by yaira2** [comment]
Thank you for the report, this issue should be fixed in v3.2.2. In the meantime, trying to push to a Git repo will display a prompt to login so you won't miss any functionality.
