### ISSUE TITLE
Bug: Paste button doesn't enable when attempting to copy from a phone

### ISSUE THREAD

**Issue by austin-lai** [files-community/Files#14750]
### Description

unable to copy and paste - from and to - mobile - like samsung note 20

### Steps To Reproduce

1. Connect to Mobile Device using uUSB
2. Copy files from Mobile Device to Desktop

### Requirements

- e.g. Fix the access with read write to mobile device

### Files Version

3.2.0.0

### Windows Version

10.0.22631.3155

### Log File

No error message

**Comment by Josh65-2201** [comment]
Thanks for the report,
- What happens when you try?
- Can you please upload (Do not copy and paste content) the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.

**Comment by Josh65-2201** [comment]
Thanks for the info, I've added this to the project board.

**Comment by yaira2** [comment]
@austin-lai is this still an issue in v3.6?
