### ISSUE TITLE
Feature: Support for displaying "home" icon next to navigation buttons

### ISSUE THREAD

**Issue by MarathonMax** [files-community/Files#14755]
### What feature or improvement do you think would benefit Files?

Much like in other browsers, I would like to customize the toolbar. Notably, I would add a "Home" button to quickly go to ... home.

### Requirements

- This proposal will allow better navigation when Files is tucked away on the right side of my screen in a very narrow window (where the folders pane is hidden)

### Files Version

3.2.0.0

### Windows Version

10.0.22631.3155

**Comment by yaira2** [comment]
Thank you for your feedback

**Comment by yaira2** [comment]
@MarathonMax support for displaying a home button will be included in the next release.
