### ISSUE TITLE
Bug: Extracting items from 7zip to Files doesn't work

### ISSUE THREAD

**Issue by verdaderoken** [files-community/Files#14765]
### Description

It throws a **File Not Found** error when I try to drag items from 7zip to Files.

### Steps To Reproduce

https://github.com/files-community/Files/assets/88200096/1bf738fc-4f81-4aed-804b-e6fa76353ba2

### Requirements

- The items should be pasted/extracted inside the folder

### Files Version

3.2.2.0

### Windows Version

10.0.26058.1100

### Log File

[debug.log](https://github.com/files-community/Files/files/14324330/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #14636 . You can check there or click subscribe in the right sidebar for updates.
