### ISSUE TITLE
Bug: Ensure Files Application Opens in the Foreground

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#14763]
### Description

I've observed that when I launch the "Files" application, it opens in the background behind all other already-open windows. This necessitates clicking on the logo to bring it to the foreground.

### Steps To Reproduce

1. Launch Files

### Requirements

Ensure that when the "Files" application is launched, it consistently opens in the foreground, visible above other open windows.

### Files Version

3.2.2.0

### Windows Version

10.0.22631.3155

### Log File

No need.

**Comment by 0x5bfa** [comment]
Please tell us:
- Did you enabled "Set as default file explorer" in Files?
- Check this is the same as https://github.com/files-community/Files/issues/14730

**Comment by Lukiluc29** [comment]
> Please tell us:
> 
> * Did you enabled "Set as default file explorer" in Files?
> * Check this is the same as [Feature: Bring Files window to foreground when opening via win+e #14730](https://github.com/files-community/Files/issues/14730)

Yes, I have indeed enabled the "Set as default file explorer" option in Files. It seems to be the same, but it would be good to modify the label. Instead of "via win+e," it should be changed to "via all shortcuts."
