### ISSUE TITLE
Requires WSL to be installed when opening files

### ISSUE THREAD

**Issue by Kagura-Nanaa** [files-community/Files#14768]
### Description

On one of the recent updates, when opening files, a CMD window pops up and asks to install WSL. i'm not sure if this is a files problem or a windows problem.

### Steps To Reproduce

1.Open files
![explorer_w2bwdzFddb](https://github.com/files-community/Files/assets/44108528/1432c477-ee37-46ab-8328-1f8e18b75941)

### Requirements

When opening files, WSL is not required to be installed.

### Files Version

3.2.2.0

### Windows Version

10.0.26058.1100

### Log File

[debug.log](https://github.com/files-community/Files/files/14325335/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, this seems to be an issue with the recent Windows Insider builds and isn’t related to Files.
