### ISSUE TITLE
More integration with powertoys

### ISSUE THREAD

**Issue by German-Pine** [files-community/Files#14762]
### What feature or improvement do you think would benefit Files?

The Files software could be benefit from powertoys features such the Peek function

### Requirements

The power toys is opensource
Many people use it
the project becomes more compatible with other apps

### Files Version

3.2.0.0

### Windows Version

10.0.19045.4046

**Comment by 0x5bfa** [comment]
Thank you for your feedback. We're ready to build this feature but PowerToys doesn't provide a way to integrate such as CLI or API. We're tracking an issue on https://github.com/microsoft/PowerToys/issues/26422 You can comment on it or subscribe for further information.
