### ISSUE TITLE
Open new tab with current directory

### ISSUE THREAD

**Issue by littleboot** [files-community/Files#14767]
### What feature or improvement do you think would benefit Files?

I would like to have an option that opens the new tab with the same directory as the current tab.
This will improve productivity. I hope you will consider adding this as an options toggle.

### Requirements

- Add settings toggle to enable this feature.

### Files Version

3.2.2.0

### Windows Version

10.0.22621.3155

**Comment by yaira2** [comment]
Thank you for your feedback, we don’t plan to make this a default behavior but you can open a duplicate tab with ctrl + shift + k.

**Comment by littleboot** [comment]
> Thank you for your feedback, we don’t plan to make this a default behavior but you can open a duplicate tab with ctrl + shift + k.

Thank you for letting me know. To clarify I don't want this to be the default behavior for everyone, just an option to enable auto duplicate tab when new tab button is pressed. This would be a great addition, at least for me personally. Its very useful when working inside a project folder.
