### ISSUE TITLE
Bug: Phone icon is missing from the Home Page drives widget

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#14764]
### Description

I've noticed an issue with my phone's connectivity. While the icon in the sidebar under "Drives" displays correctly when I connect my phone, the same icon doesn't appear on the home page.

### Steps To Reproduce

1. Connect a phone

### Requirements

Ensure that when a phone is connected, the icon is synchronized to appear consistently, both in the sidebar under "Drives" and on the home page.

### Files Version

3.2.2.0

### Windows Version

10.0.22631.3155

### Log File

![Capture d'écran 2024-02-18 133756](https://github.com/files-community/Files/assets/128183422/fe6f8d3e-0cbe-435e-816f-edcc55449842)

**Comment by 0x5bfa** [comment]
Thank you for your feedback. I can repro as well.

![image](https://github.com/files-community/Files/assets/62196528/bb87ec98-4a65-4067-b28d-4186ab817513)

**Comment by yaira2** [comment]
Is this a new issue or was it present in older versions as well?

**Comment by yaira2** [comment]
@0x5bfa @Lukiluc29 is this fixed in `main`?
