### ISSUE TITLE
Copy/Move large amount of files (photos) dismally slow

### ISSUE THREAD

**Issue by bwh1969** [files-community/Files#14771]
### Description

Whenever I would need to move a large amount of photos, Files all but locks up for a very long time after "select all" is used then "cut" or "copy" is selected.  Using a Surface Pro Laptop 4 with 6 core Ryzen and 16 GB RAM.  Have gone back to native File Explorer which does not have this issue.

### Steps To Reproduce

1. Open a folder with many photos
2. Use ctrl A or some version of select all, then either use ctrl 
3. Files becomes mostly unresponsive for a very long time >> 1 minute.

### Requirements

- e.g. Fix crash that occurs when...
It should not perform significantly more poorly than native File Explorer when large amount of items (photos) are selected then copy or cut is used.

### Files Version

3.2.0.0

### Windows Version

10.0.22631.3155

### Log File

Not sure how to get a log file for this

**Comment by Josh65-2201** [comment]
Thanks for the report, 
- Is the folders contents loaded when you select all? 
- How many items are in this folder
- Where is the folder located (Local drive, Network drive, Phone)
