### ISSUE TITLE
Bug: 关于背景材质

### ISSUE THREAD

**Issue by JiZPaper** [files-community/Files#14770]
### Description

在设置中将背景材质更改为Acylic后，设置页面的背景材质依然是Mica变体。

### Steps To Reproduce

1.打开设置
2.选择外观
3.背景材质-Acylic变体

### Requirements

在使用”Acylic变体“背景材质时，一同改变设置页面的背景材质。

### Files Version

3.2.2

### Windows Version

Windows 11 Insider Preview Build 26058

### Log File

![屏幕截图 2024-02-19 193352](https://github.com/files-community/Files/assets/144446306/1c0d1940-9641-4116-8ec5-0aeffb4b46f9)

**Comment by JiZPaper** [comment]
it's a bug report, but i cant change the label "feature request" to "bug".

**Comment by Josh65-2201** [comment]
Thanks, Acrylic is working based on the screenshot, the settings dialog doesn't use either background material too. The color is coming from the background color you have selected

**Comment by yaira2** [comment]
> Thanks, Acrylic is working based on the screenshot, the settings dialog doesn't use either backdrop material too. The color is coming from the background you have selected

This is correct, while there are ways to apply the backdrop to dialogs, it's generally not used on content dialogs.
