### ISSUE TITLE
Files Bug

### ISSUE THREAD

**Issue by johnasmith13** [files-community/Files#14778]
### Description

![image](https://github.com/files-community/Files/assets/160532399/c512b2a1-bd49-48a8-b39b-d0de14efc98f)
File thumbnails show briefly and disappear...

### Steps To Reproduce

Happens all the time

### Requirements

- e.g. Fix crash that occurs when...
Open Files and thumbnail flash for a split second and disappear

### Files Version

3.2.2.0

### Windows Version

10.0.22621.3155

### Log File

[debug.log](https://github.com/files-community/Files/files/14335816/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, this is by design. File icons are shown while the real thumbnail is still loading because sometimes it can take several seconds for them to load. The alternative is to show a blank box while the thumbnail is loading but we felt it would be better to display the icon.

**Comment by johnasmith13** [comment]
Excel will eventually show up as the normal thumbnail, but the .PDF and Word (.docx) don't ever show up....

This can't be normal....

John

**Comment by Josh65-2201** [comment]
It is normal, PDFs and Word documents have thumbnails and excel doesn't. Files displays those thumbnails.

**Comment by yaira2** [comment]
If you prefer the icon over the thumbnail, you can adjust this from Settings > Folders > Show thumbnails.

**Comment by johnasmith13** [comment]
That fixed it!!  Thank you for your help and for the fast reply!!!

John
