### ISSUE TITLE
Bug: Google drive synced folders all show in the cloud drive section

### ISSUE THREAD

**Issue by mahtaran** [files-community/Files#14780]
### Description

Partial duplicate of #3500

I am logged in to two accounts on Google Drive (personal & work), and have all personal folders set up to sync to my personal drive. This however means that I have a lot of duplication in my drive view:

![image](https://github.com/files-community/Files/assets/22727323/599f9456-4634-4a02-8c70-366be60c874c)

### Steps To Reproduce

1. Be logged in to multiple Google Drive accounts
2. Sync some folders

### Requirements

(Duplicate of #3500) have all Google Drive drives hidden under the Drives tab.

Be able to disable showing synced folders or automatically hide folders which are favourites or libraries.

### Files Version

3.2.2.0

### Windows Version

10.0.26058.1100

### Log File

[debug.log](https://github.com/files-community/Files/files/14337317/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
@mahtaran are the paths for each location?

**Comment by mahtaran** [comment]
Not entirely sure what you mean, but my set-up is as follows:

- My personal Drive is mounted with drive letter G:
- My work Drive is mounted with drive letter H: (in other news, for some reason it disappeared from the drives tab, so that seems fixed)
- My personal folders (Desktop, Documents, Downloads, Music, Pictures, and Videos) are located in C:\Users\Mahtaran\ and are backed-up using Google Drive's sync feature

The "offending" piece of code seems to be [this](https://github.com/files-community/Files/blob/1de517a175c00f9d7393f26521f945dcf4edcf54/src/Files.App/Utils/Cloud/Detector/GoogleDriveCloudDetector.cs#L38-L66), which will create a `CloudProvider` for every synced folder. Could be useful in some cases, but in my case that's something I don't want.

**Comment by yaira2** [comment]
We already have code to filter out the items from the drives list, but it's possible that there is a race condition. What does File Explorer show under drives?

**Comment by mahtaran** [comment]
![image](https://github.com/files-community/Files/assets/22727323/fc46f9cf-1220-48b2-8e3a-3d984e16655a)

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
