### ISSUE TITLE
Files crashed under Windows heavy load

### ISSUE THREAD

**Issue by jpnolanjr** [files-community/Files#14787]
### Description

Win 10 System was under heavy load and I selected a different directory, there was a long pause, disk chattering (a real HDD) and then the Files window closed

### Steps To Reproduce

1. Run old system for a while with MS Edge and lots of tabs, several other large applications to produce heavy load on PC
2. Make possibly duplicate clicks to change directory displayed
3. Files crashed

### Requirements

- e.g. Fix crash that occurs when...
If multiple clicks are done under heavy load, recover gracefully

### Files Version

3.2.2.0

### Windows Version

10.0.19045.4046

### Log File

[debug.log](https://github.com/files-community/Files/files/14341903/debug.log)

**Comment by yaira2** [comment]
Thank you for the report, has this happened again since updating to v3.2.2? The crash logs are from v3.2.1.

**Comment by yaira2** [comment]
We believe this is resolved but please let us know if that's not the case.
