### ISSUE TITLE
Bug: Clicking on an empty space sometimes fails to deselect items

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#14785]
### Description

As the title describes. In this case, some hotkeys (Ctrl++, Ctrl+-, etc.) cannot be used, nor can multiple selections be made by dragging. Repeated navigation and layout changes may fix or reoccur.

### Steps To Reproduce

1. Set the layout to List.
2. Close the app window with the list layout open. (Make sure to set background running to off and startup settings to "Continue where you left off".
3. Restart the app.
4. Observe deselection doesn't work.

### Requirements

Make deselection, selection rectangles and hotkeys work.

### Files Version

3.2.2.0

### Windows Version

10.0.19045.4046

### Log File

No noteworthy logs are output.

**Comment by yaira2** [comment]
Is this new to v3.2.2?

**Comment by hishitetsu** [comment]
No, it also happens in v3.2.0.

**Comment by 0x5bfa** [comment]
Yeah, when I was playing around List layout, this issue, where selection rectangle won't work, happened.

**Comment by hishitetsu** [comment]
This seems to occur when the list layout is displayed before displaying the grid or tile layout. This will not occur when the list layout is displayed after displaying the grid or tile layout.
