### ISSUE TITLE
Avoid duplicate tabs for same folder/path

### ISSUE THREAD

**Issue by clackwell** [files-community/Files#14796]
### What feature or improvement do you think would benefit Files?

I am using the Downloads folder a lot. I open it via Firefox's respective option on a downloaded item (also in an attempt to select the downloaded file in that folder - which does not work for me so far anyway). However, by doing this, I keep accumulating tabs that all shows the contents of the Downloads folder, which clutters the tab bar and gets unwieldy with a certain amount of tabs.

I would like to configure individual folders and/or Files in general, to not open folders in new tabs under these circumstances, but instead switch to the existing tab.

Once such a feature is activated, one could argue that sometimes one may want to have the same folder open in multiple tabs, which should then still be possible. To address this, I could imagine an extra option in the context menu of the switched-to tab to duplicate the tab, but with the previous state (scroll position, selected items).

Then, if the same folder is open in multiple tabs due to user choice, one would consider which one of these Files should switch to, when the request arrives to open that folder (again triggered by, for example, Firefox).

(There are web browser extensions that aim to solve the same problem in that domain.)

### Requirements

- This proposal will avoid duplicate tabs for specific or all folders, simplifying the user experience by avoiding tab clutter

### Files Version

3.2.2.0

### Windows Version

10.0.22631.3155

**Comment by yaira2** [comment]
Thank you for your feedback, we're tracking a similar request in #6925. You can add a comment or subscribe to the issue to be notified of any updates.
