### ISSUE TITLE
Allow for file transfer progress or status center to be "popped out" into its own window

### ISSUE THREAD

**Issue by queenbiscuit311** [files-community/Files#14797]
### What feature or improvement do you think would benefit Files?

In Windows Explorer and most other file browsers, when you initiate a file transfer you get a window with the progress of the operations in progress (or sometimes multiple windows, one per file transfer) that is entirely independent from your main file explorer window. This is helpful because I can put this window off to the side and keep track of exactly how my file transfer is going. 

The status center as it appears to be now requires the main explorer window to be open and focused to see detailed progress. It would be a massive quality of life boost and would get files closer to being a perfect windows explorer replacement if I could click a button that would pop this menu or an individual file transfer out into a separate window.

(Please tell me if this is duplicate. I couldn't find any other issue requesting this, however)

### Requirements

- Allow for either status center in its entirety or individual file transfer to be moved to an independent window.
- Allow user to choose default behavior for new file transfers (in status center or in separate window)

### Files Version

3.2.2.0

### Windows Version

10.0.19044.1288

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #8207 . You can check there or click subscribe in the right sidebar for updates.
