### ISSUE TITLE
Question/Feature Request (if not currently possible) re: How to Run "Files" - 2 folders in Double Pane Files Window

### ISSUE THREAD

**Issue by noblemd00** [files-community/Files#14793]
### What feature or improvement do you think would benefit Files?

1. I am a new user of "Files"
2. Not sure if related to https://github.com/files-community/Files/issues/11900. 
(seems to be a more complicated request than my issue- also possibly related to 13515,13736,13988,14585)

3. Upon opening "Files" have two panes containing a specific folder open in the left pane and a different specific folder open in the right pane.

4. This can be done using "Continue where you left off", however if "Files" is closed while in a different folder(s) the current open folders are re-opened upon startup.

5. If opening dual panes with specific folders open is currently possible... 

What are the settings? 

6. I have tried numerous options but cannot get this to occur.

### Requirements

Currently get this (with below options):

![Options both](https://github.com/files-community/Files/assets/16325865/5341cd30-63cd-4ff6-9368-277179099b9a)

Want to get this upon opening "Files":

![240220 113623](https://github.com/files-community/Files/assets/16325865/1833fbac-6ebf-4a0a-a896-c278fe2fbf1f)

### Files Version

3.2.2.2

### Windows Version

Windows 11 Pro for Workstations 23H2

### Comments

Opening specific dual folders in dual panes should be an integral part of any dual pane capable file explorer.

**Comment by yaira2** [comment]
Thank you for your feedback, you can accomplish this via continue where you left off (as you already discovered). Otherwise this would be covered by the issue you linked for workspaces.
