### ISSUE TITLE
Checks for Updates on startup

### ISSUE THREAD

**Issue by brucewestfall** [files-community/Files#14798]
### What feature or improvement do you think would benefit Files?

Maybe i'm missing something but i would prefer the program not to check for updates when it starts.  I was in a huge hurry today and waiting for the little spinner or whatever was there drove me bonkies.  I do like updates, just not pushy ones.

### Requirements

- This proposal will stop automatic updates
- This proposal will also not even show the dialog at the beginning
- This proposal will accomplish world peace and happiness.

### Files Version

3.2.2.0

### Windows Version

10.0.22621.3155

### Comments

The only reason im giving a suggestion is that everything else is so wonderful!  You folks did an awesome job!

**Comment by Josh65-2201** [comment]
The popup issue comes from App Installer which is a Window issue. You can try
1. Export your settings by going to Files settings > Advanced > Export. 
2. Then uninstall and reinstall Files using https://cdn.files.community/files/stable/Files.Package_3.2.2.0_Stable_Test/Files.Package_3.2.2.0_x64_ARM64_Stable.msixbundle
3. Import your settings from Files settings > Advanced > Import > Select previously saved zip.

**Comment by yaira2** [comment]
Thank you for your feedback. The AppInstaller prompt isn't something we have control over but for what it's worth, the Store version doesn't have this issue.

**Comment by yaira2** [comment]
@Josh65-2201 I found a way to solve the prompt for appinstaller and I'm redeploying v3.2.2 with the fix.
