### ISSUE TITLE
Bug: `COM server is in use` prompt when closing Files sometimes

### ISSUE THREAD

**Issue by lotharschaberg** [files-community/Files#14794]
### Description

After closing a window or instance of "Files", sometimes a dialog box appears with the Message "COM server is in use" and the buttons "YES" and "No". It seems that this happens mainly after copying files between different folders.
Files Version 3.2.2.0, Windows 11 Home and Pro
![COM Server](https://github.com/files-community/Files/assets/20385649/cc6bd543-219d-423d-bf94-3607fe5d9f85)

### Steps To Reproduce

See description

### Requirements

See description

### Files Version

3.2.2.0

### Windows Version

10.0.22631.3155

### Log File

[debug.log](https://github.com/files-community/Files/files/14349465/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
@lotharschaberg thank you for the report, can you check if this is still an issue in the preview version v3.4.17? https://files.community/download/preview
