### ISSUE TITLE
Better implementation for command line arguments

### ISSUE THREAD

**Issue by soumyamahunt** [files-community/Files#1479]
**Is your feature request related to a problem? Please describe.**
The command line arguments currently implemented lack a lot of feature implemented with Windows Explorer.

**Describe the solution you'd like**
Command line arguments should support relative path along with absolute path, also passing environment variables as arguments should be supported.

**Additional context**
I am considering to implement it myself, but I want to ask community for guide what arguments should it support. Also, the current implementation is quite confusing in what it tries to do.

**Comment by soumyamahunt** [comment]
[These](https://winaero.com/blog/file-explorer-command-line-arguments-in-windows-10/#:~:text=You%20can%20use%20File%20Explorer%20command%20line%20arguments,Win%20%2B%20R%29%20or%20a%20command%20prompt%20instance.) are some of the command line arguments Windows Explorer implements.

**Comment by hez2010** [comment]
Found a full document about explorer command line arguments: https://ss64.com/nt/explorer.html

**Comment by HydrogenDeuterium** [comment]
one way to partl;y solve it:
add "function files. {files "$pwd"}" to powershell's profile,allows use `files.` to work as expected of  `files .`

**Comment by yaichenbaum** [comment]
> one way to partl;y solve it: add "function files. {files "$pwd"}" to powershell's profile,allows use `files.` to work as expected of `files .`

@HydrogenDeuterium do you want to implement this change?

**Comment by Josh-65** [comment]
Is this an issue in the preview version? https://files.community/download/preview
