### ISSUE TITLE
Buggy Sort by menu

### ISSUE THREAD

**Issue by Davikar** [files-community/Files#14815]
### Description

Changing the sort order doesn't always seem to apply correctly or doesn't correctly show the current sort order. I select sort by date for example and it still shows sort by name when I check the menu. Also after changing it I sometimes get a long delay when I try to open the submenu again in the top toolbar.

### Steps To Reproduce

1. Change sort order in Sort by
2. Open the menu and check

### Requirements

Should show the current sort order when opening the submenu.

### Files Version

3.2.2

### Windows Version

Windows 11 build 22631.3155

### Log File

[debug.log](https://github.com/files-community/Files/files/14374197/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #14685 . You can check there or click subscribe in the right sidebar for updates.
