### ISSUE TITLE
Bug: Drives section stopped loading

### ISSUE THREAD

**Issue by Zhnigo** [files-community/Files#14818]
### Description

The drives section is fully empty, both in Home and in the left toolbar.

### Steps To Reproduce

Sadly I am not sure. I left Files running overnight, and as I opened it in the morning, the bug has occured.

### Requirements

Prevent the drives section from becoming empty.

### Files Version

3.2.3.0

### Windows Version

10.0.19045.4046

### Log File

[debug.log](https://github.com/files-community/Files/files/14377304/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Can you send a screenshot of the This PC drives section in Windows File Explorer.

**Comment by Zhnigo** [comment]
Thanks for the quick reply!
![QCaD37D 1](https://github.com/files-community/Files/assets/20024669/aa78e625-3099-4841-86b9-42f9923ad4d4)

**Comment by Josh65-2201** [comment]
Thanks, does closing Files from the System Tray or Task manager then reopening show them?

**Comment by Josh65-2201** [comment]
Thanks for the information, I've added this to the project board.

**Comment by yaira2** [comment]
What happens if 
1. You run Files as admin
2. You restart Windows

**Comment by yaira2** [comment]
@Zhnigo

**Comment by Zhnigo** [comment]
Sorry for the delay.
When launching Files as admin, the app doesn't start at all.
When rebooting windows, I get stuck on a black screen with only the mouse
cursor visible, ended up having to cold reboot.
After rebooting, Files opens normally and displays the drives normally.

**Comment by yaira2** [comment]
Does it work to run as admin now?

**Comment by Zhnigo** [comment]
Nope, still no response when I try to run as admin. Otherwise it launches
normally, drives still visible so far

**Comment by yaira2** [comment]
Thank you for checking, I'll go ahead and close this since the drive issue has been resolved. If you are able, please open a new issue regarding the problem with running as admin so we can add it to the project board.
