### ISSUE TITLE
Bug: Files crashes when opening to the home page

### ISSUE THREAD

**Issue by JamieEff** [files-community/Files#14813]
### Description

So, am on a Surface Go 2 running Windows 11 latest build.  Have successfully installed the app on 2 other devices (Office desktop and home desktop) but for some reason trying to install on the Go 2 doesnt.

Once installed, try to launch it it goes through the motions of starting up but when it gets to the point of trying to add the 'quick access' area the app abruptly closes.

I have tried uninstalling and reinstalling and get the same result.

Thanks

Jamie

### Steps To Reproduce

Once installed, try to launch it it goes through the motions of starting up but when it gets to the point of trying to add the 'quick access' area the app abruptly closes.

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.2.2.0

### Windows Version

11 Home v 23H2  build 22631.3155

### Log File

[debug.log](https://github.com/files-community/Files/files/14373262/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board. The log doesn't show any errors so it this might be hard to find a fix.

**Comment by JamieEff** [comment]
I appreciate that and will keep trying.  Would it be helpful to video screenshot so you can see at what point it gives up?

**Comment by JamieEff** [comment]
ok so having just booted up the Surface Go2 just now I tried to run Files and for the first time it ran and opened fine on this device.  I then noticed that an app that I use to access a NAS remotely hadnt launched - its called Netdrive (https://www.netdrive.net/).  Am not sure if this is simply coincidence or related but figured that as part of its start up, Files is likely to try accessing any connected / mounted drives

Could this be the issue?

**Comment by Josh65-2201** [comment]
What happens when you close files from the system tray. Open Net drive then open Files again?

**Comment by JamieEff** [comment]
right, on further efforts it doesnt seem linked.  With netdrive closed down, Files still closes but it takes a little longer to do so.  Sorry :(

**Comment by yaira2** [comment]
Is this still an issue in the preview version (v3.4.1)? https://files.community/download/preview
