### ISSUE TITLE
Bug: Icons take a while to display under heavy load

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#14817]
### Description

Starting in v3.2, icons can take a while to display under heavy load (30+ seconds).

### Steps To Reproduce

**Issue 1**
1. Open large directory in Grid View
2. Scroll quickly
3. Some icons will take 30+ seconds to appear

**Issue 2**
1. After reproducing issue 1, navigate to a different location
2. Observe that navigating away doesn't clear the queue and that the second location has the same issue

In both cases, disabling thumbnails from settings or restarting Files resolves the issue.

### Requirements

- Load icons right away

### Files Version

v3.2.6

### Windows Version

Windows 11

### Log File

NA

**Comment by DaveFriedel** [comment]
Switching the setting off does not clear the problem.
It's not just caching, I can't get any folders to show icons even if they are just few images.
Using large icons, it won't display any at all.

**Comment by yaira2** [comment]
@DaveFriedel are you using the preview version of Files?
