### ISSUE TITLE
Feature: Use Humanizer instead of ByteSize & our own date time formatter

### ISSUE THREAD

**Issue by 0x5bfa** [files-community/Files#14811]
### What feature or improvement do you think would benefit Files?

Humanizer became inctive project themse weeks (maybe owner have been changed).

### Requirements

- Remove ByteSize
- Remove our own date time formatter
- Introduce Humanizer

### Files Version

-

### Windows Version

-

**Comment by yaira2** [comment]
Probably not the highest priority but I'm in favor of this change. It is also worth noting that Humanizer has a smaller package than ByteSize.

**Comment by 0x5bfa** [comment]
@yaira2 Do you want this to be kept just in your mind? Just not as an issue.

**Comment by yaira2** [comment]
How many changes are needed to make the switch?

**Comment by 0x5bfa** [comment]
https://github.com/search?q=repo%3Afiles-community%2FFiles%20ByteSize&type=code

https://github.com/search?q=repo%3Afiles-community%2FFiles%20Formatter&type=code

We should separate.

**Comment by yaira2** [comment]
For the first part, is it just a matter of switching the references, or do we need to rework the code?

**Comment by 0x5bfa** [comment]
Yeah sort of. I think not neeeded too much work. We could start soon.

**Comment by 0x5bfa** [comment]
Oh [Humanizer package](https://www.nuget.org/packages/Humanizer.Core) is 10 times bigger than ByteSize.

If we make our own one, we can save 10 times smaller though. It'd be not a priority but worth it?

Files.Core.Humanizer: our own implementation for byte size and date time dataa humanizing.

**Comment by 0x5bfa** [comment]
Closing for now. This should be included in the effort of reduction of external libraries along with other ones.
