### ISSUE TITLE
Favourites not showing

### ISSUE THREAD

**Issue by Danszerlied** [files-community/Files#14816]
### Description

Sometimes when I open files app, my favourites wouldn't load.

### Steps To Reproduce

Open files app

### Requirements

It happens when I open the app
![Screenshot 2024-02-22 230227](https://github.com/files-community/Files/assets/74824746/7aeb873d-1c05-4057-a9bb-1b2dccbe8cf1)

### Files Version

3.2.2.0

### Windows Version

10.0.26058.1000

### Log File

[debug.log](https://github.com/files-community/Files/files/14376267/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Can you send a screenshot of what is in favorites from Windows File Explorer

**Comment by yaira2** [comment]
Thank you for the feedback, we're currently tracking this in #13116. You can add a comment or click subscribe to be notified when it's fixed.

**Comment by Danszerlied** [comment]
> Thanks for the report, Can you send a screenshot of what is in favorites from Windows File Explorer

![image](https://github.com/files-community/Files/assets/74824746/92a639f4-e2ee-46ca-a832-60477de4b286)

**Comment by s4m2d** [comment]
Hey, I just wanted to add, I have the same problem, my "Windows Explorer" Favs look like this:
<img width="191" alt="favs" src="https://github.com/files-community/Files/assets/8577233/24545808-fe31-4eb9-ac54-7ab70c0632bd">

sometimes they show, sometimes they don't in the "files" app. I can't figure out why they sometimes don't.

**Comment by Josh65-2201** [comment]
There a different issues since this was made. Please see https://github.com/files-community/Files/issues/15410
