### ISSUE TITLE
Files 3.2.3 only on an admin account ?

### ISSUE THREAD

**Issue by gerard-durand** [files-community/Files#14827]
### Description

On my Windows 11 PC, files 3.2.3 installs and runs on the administrator account, but is very slow to start up. On a non-admin account, it is not even seen in the list of installed software, so does not launch... It seems to me that this wasn't the case on a previous version, maybe 3.0, but I can't remember. In short, disappointing, even if the look seems nice.

### Steps To Reproduce

no special steps

### Requirements

No crash, simply is not seen (so does not work) on a non-admin account

### Files Version

3.2.3

### Windows Version

11

### Log File

.

**Comment by Josh65-2201** [comment]
You have to install Files on the accounts you want to use it on it isn't a global install. As for startup it should run in the background after first launch for instant opening.
