### ISSUE TITLE
When open download filefolder, the position is not at the top

### ISSUE THREAD

**Issue by JTFA** [files-community/Files#14828]
### Description

When open download filefolder, the position is not at the top

### Steps To Reproduce

open a filefolder like [download] which is grouped by date and has a lot of files

### Requirements

 the position should be at the top

### Files Version

3.2.3

### Windows Version

Windows11 22631.3155

### Log File

[debug.log](https://github.com/files-community/Files/files/14393065/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #5825. You can check there or click subscribe in the right sidebar for updates.
