### ISSUE TITLE
3.2.3 files preview

### ISSUE THREAD

**Issue by gilnett** [files-community/Files#14825]
### Description

the preview version of Files is 3.2.2.0. On the other hand, the stable version is 3.2.3.0.
I'm not sure if it's a bug but I'll tell you anyway.

### Steps To Reproduce

1.download Files Preview installer and Files stable installer
2.start downloading Files Preview install
3.the downloader says that it is already the latest version that is installed(3.2.2.0)
4.start downloading Files stable install
5.start update to 3.2.3.0

### Requirements

- e.g. fixed the illogical version difference
- 

### Files Version

3.2.3.0

### Windows Version

22631.3155

### Log File

[debug.log](https://github.com/files-community/Files/files/14388918/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Stable had an update to fix an issue with App installer showing a checking for updates dialog when opening. Preview will have a higher version number when it has an update.
