### ISSUE TITLE
Sort & Group preferences for specific folders

### ISSUE THREAD

**Issue by kevingrand** [files-community/Files#14823]
### What feature or improvement do you think would benefit Files?

Currently when you add sort order or group by settings for a particular folder it goes away as soon as you go to another folder. I would like to be able to keep the settings - very important for something like a downloads folder where I need to see the most recent files before all others.

### Requirements

- The sort and group dropdown has a new button to "Save settings for this folder"
![filesapp-suggestion](https://github.com/files-community/Files/assets/17459245/330926ea-1122-4203-9cfc-e0fb54ce9771)

### Files Version

3.2.2.0

### Windows Version

10.0.19045.4046

**Comment by Josh65-2201** [comment]
Thanks for the feedback, If you turn off Files settings > Folders > Sync layout and sorting preferences across directories. You can edit sort options per directory

**Comment by kevingrand** [comment]
Hey there, thanks for the response. Is that supposed to be persistent? I followed the steps and the moment I leave the folder and come back, the custom sorting settings are reset.

**Comment by Josh65-2201** [comment]
Yes it is, are you using column view?

**Comment by kevingrand** [comment]
Yes I'm using columns. Tried again and still no luck getting it to save.

**Comment by Josh65-2201** [comment]
It's an known issue with the column layout not saving https://github.com/files-community/Files/issues/14801. You can check there or click subscribe in the right sidebar for updates.

**Comment by kevingrand** [comment]
Ok, sounds good. Thanks so much for your help!
