### ISSUE TITLE
Crashes when making new folder in Recycle Bin

### ISSUE THREAD

**Issue by pixl-8** [files-community/Files#1483]
Files UWP v0.12.0 Crashes when making a new folder in the Recycle Bin.

Desktop Version: Win 10 Home 20170.rs_prerelease

To Reproduce:
1. Enable Recycle Bin
2. Make a new folder inside Recycle Bin

Debug Files:
[debug.txt](https://github.com/files-community/files-uwp/files/4934972/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/files-uwp/files/4934973/debug_fulltrust.txt)

**Comment by Jaiganeshkumaran** [comment]
You can't create directories in the Recycle bin. It's only for storing temporarily deleted files and folders.

**Comment by pixl-8** [comment]
I actually right-clicked and had the option to add a folder (I thought this was strange) so I clicked it. But now, it doesn't have the option.

**Comment by gave92** [comment]
Ah the good old bug is back #1283

**Comment by Jaiganeshkumaran** [comment]
@gave92 Could you reopen that PR?

**Comment by Thomas1664** [comment]
Right now, the only way of creating a new folder in recycle bin is via ctrl+shift+n.

**Comment by gave92** [comment]
@Thomas1664 thanks for pointing this out. Needs to be corrected.
