### ISSUE TITLE
Bug: when navigating up to the previous folder, the page will flash at the top position and then jump to the previous position

### ISSUE THREAD

**Issue by JTFA** [files-community/Files#14830]
### Description

when navigating up to the previous folder, the page will flash at the top position and then jump to the previous position

### Steps To Reproduce

1. open [scroll to previous folder when navigating up] in settings.
2. open a folder which has a lot of folders.
3. Open any folder other than the first one.
4. navigating up to the previous level folder.

### Requirements

when navigating up, the page should be straightly at the previous position.

### Files Version

3.2.3.0

### Windows Version

Windows11 22631.3155

### Log File

[debug.log](https://github.com/files-community/Files/files/14395713/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, this is more of a performance issue as we can only scroll to the correct position after the items are loaded. Our goal is to get to a point where it's barely noticeable but in the meantime, you can track our progress in #4180.
