### ISSUE TITLE
Crashes on external monitor 

### ISSUE THREAD

**Issue by FastFarmer** [files-community/Files#14835]
### Description

This works fine on the laptop screen, but as soon as you plug the external monitor in, it freezes then crashes. It wont run on an external monitor. Loads, sits there for a second, crashes. No idea how to even troubleshoot this?
It's shity though, No other app has a problem.

### Steps To Reproduce

Run it with external display

### Requirements

Ah, not to crash and be usable...

### Files Version

Latest from Microsoft Store

### Windows Version

23H2

### Log File

Faulting application name: Files.exe, version: 1.0.0.0, time stamp: 0x65a80000
Faulting module name: Microsoft.UI.Input.dll, version: 10.0.22624.1061, time stamp: 0xb0e6654a
Exception code: 0xc0000602
Fault offset: 0x000000000006fd55
Faulting process id: 0x0x6D60
Faulting application start time: 0x0x1DA67ECBA66B4EF
Faulting application path: C:\Program Files\WindowsApps\49306atecsolution.FilesUWP_3.2.2.0_x64__et10x9a9vyk8t\Files.App\Files.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.4_4000.1136.2333.0_x64__8wekyb3d8bbwe\Microsoft.UI.Input.dll
Report Id: 1fc55c5a-8d02-46ca-bf44-38aa34c56dfc
Faulting package full name: 49306atecsolution.FilesUWP_3.2.2.0_x64__et10x9a9vyk8t
Faulting package-relative application ID: App

**Comment by yaira2** [comment]
Thank you for the report
1. Can you check if this is also an issue with other WinAppSdk applications like Phone Link?
2. Is this only an issue if you move Files to the other monitor?
3. In the future, please upload the log file as an attachment as it helps keep the report tidy and reduce extra scrolling on the GitHub page.

**Comment by FastFarmer** [comment]
Yes. There seems to be a conflict with -
https://www.microsoft.com/store/productId/9PF4KZ2VN4W9?ocid=pdpshare
Yes. Only happening when I plug in an external monitor.

**Comment by yaira2** [comment]
I don't think TTB is using WinAppSdk @sylveon

**Comment by sylveon** [comment]
It's not. Does the issue still occur if TTB isn't running.

**Comment by FastFarmer** [comment]
TTB running, files crashes.. wont load at all. 
TTB not running, files works fine.
Only occurs with external monitor connected.

**Comment by yaira2** [comment]
The only thing I can think of is that we set the `NonRudeHWND` property when "Automatically hide the taskbar" is enabled.

**Comment by sylveon** [comment]
Does this issue repro for you with Files Insider? I can't repro it there for me when adding a monitor to my VM.

Also, if you're able to, a memory dump would be helpful.

**Comment by FastFarmer** [comment]
I downloaded File Insider Preview. Is that what you are talking about? Same.

However, when I try and load files I now get -
![Screenshot 2024-03-04 072011](https://github.com/files-community/Files/assets/26688771/99ceb16c-d70f-4120-9b0f-bc44ccd2eb88)

**Comment by FastFarmer** [comment]
> Yes. There seems to be a conflict with - https://www.microsoft.com/store/productId/9PF4KZ2VN4W9?ocid=pdpshare Yes. Only happening when I plug in an external monitor.

FYI I cant reproduce this consistantly with TB running or not, so I dont think there is a conflict afterall

**Comment by yaira2** [comment]
> Can you check if this is also an issue with other WinAppSdk applications like Phone Link?
