### ISSUE TITLE
App Crashes when changing theme

### ISSUE THREAD

**Issue by pixl-8** [files-community/Files#1484]
The app crashes when changing the theme and hitting the back button.

To Reproduce:
1. Change theme from dark to light or light to dark
2. Press the back button in the corner

Windows Version: Win 10 Home 20170.rs_prerelease.200710-1419

**Comment by Jaiganeshkumaran** [comment]
@pixl-8 What's your Windows app theme? Could you post the log file?

**Comment by pixl-8** [comment]
Windows app theme is dark and the log files are here: 
[debug.txt](https://github.com/files-community/files-uwp/files/4935676/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/files-uwp/files/4935677/debug_fulltrust.txt)

**Comment by yaichenbaum** [comment]
Is this still an issue in v0.16?
