### ISSUE TITLE
Feature: Display Shell Paths Suggestions

### ISSUE THREAD

**Issue by D-Maxwell** [files-community/Files#14843]
### What feature or improvement do you think would benefit Files?

Whenever the user would begin to type `shell:` in the address bar, it would be nice for the Files app to suggest possible shell paths ; for instance `(common) startup`, `(common) start menu`, ...

### Requirements

A list of all shell locations would certainly be of use ; Windows stores its own at the following registry address : `HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FolderDescriptions`.

### Files Version

3.2.3.0

### Windows Version

10.0.19045.2788

### Comments

There is also the ability to preview the AppsFolder shell location, although that would most certainly warrant its own issue (which may already exist).

**Comment by Josh65-2201** [comment]
Thanks for the feedback, I've added this to the project board.

**Comment by yaira2** [comment]
Thank you for your feedback, we're currently tracking this in #13251. You can add a comment or subscribe to that issue to be notified of any further updates.
