### ISSUE TITLE
Sorting tags in the tag section

### ISSUE THREAD

**Issue by techi99** [files-community/Files#14844]
### What feature or improvement do you think would benefit Files?

Tagging in Files is a great feature with a fantastic implementation via alternate data streams! Having created a lot of new tags I would appreciate the possibility of  sorting my tags in the tags section in alphabetical order.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.2.2.0

### Windows Version

10.0.22631.3155

**Comment by Josh65-2201** [comment]
Thanks for the feedback, You can reorder then in Files settings > Tags via drag and drop

**Comment by techi99** [comment]
Yep, I tried this before, causing an app crash, so not sure, if sorting is implemented this way. I did a restart now and give it a new try: so far it works! Thx a lot. 
If I can reproduce the crash, I will open a bug request.
