### ISSUE TITLE
Bug: Some files do not show sync status

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#14841]
### Description

There are files that should actually be available offline but do not show a sync status when viewed in the details layout. This is happening with Excel files in my environment, but some Excel files show sync status.
Sync status is correctly displayed in the details pane.

![image](https://github.com/files-community/Files/assets/66369541/77ab81ab-3077-4438-9d7e-c701968caddb)

### Steps To Reproduce

1. Open a OneDrive folder in the details layout.
2. Observe some files don't show sync status.

### Requirements

Sync status should be displayed.

### Files Version

3.2.2.0

### Windows Version

10.0.19045.4046

### Log File

No noteworthy logs are output.

**Comment by hishitetsu** [comment]
One thing to note is that files that do not display cloud status also display differently in the File Type column. Thus, this may not be an issue limited to cloud status, but rather property retrieval in general.

**Comment by yaira2** [comment]
Can you repro this in other layouts as well?

**Comment by hishitetsu** [comment]
> Can you repro this in other layouts as well?

Yes.
I also found that Excel files that do not show a sync status do not show thumbnails either. Excel files that do not display thumbnails in Files do not display thumbnails in Explorer either, but the sync status is displayed correctly.

**Comment by yaira2** [comment]
The sync status is loaded after the thumbnail, so this indicates it's stuck on the thumbnail code. Do the icons load if you wait long enough?

**Comment by hishitetsu** [comment]
Yes, the icons load.

**Comment by yaira2** [comment]
I think it's related to #14817.

**Comment by hishitetsu** [comment]
In my environment the icons load relatively immediately. But I think it is true that there is some issue with thumbnails loading.

**Comment by yaira2** [comment]
I think it started after we limited extended properties to 50 items.
