### ISSUE TITLE
Search in hidden folders/files

### ISSUE THREAD

**Issue by picarica** [files-community/Files#14840]
### What feature or improvement do you think would benefit Files?

i tried out search and it doesn't seem like search searched in hidden folders and files, for example tried searching for afile that is located in AppData folder and it doesnt show up, i am tired of using third party search engines, so i would love if this would be implemented

### Requirements

- searching will also search in hidden folders, AppData for example

### Files Version

3.2.3.0

### Windows Version

10.0.19044.3324

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #5845 . You can check there or click subscribe in the right sidebar for updates.

Right now you can try removing the appdata folder exclusion in Windows Settings > Search > Searching Windows and make sure that enhanced is selected.
