### ISSUE TITLE
Initial display when selecting a folder

### ISSUE THREAD

**Issue by Divers-Seki** [files-community/Files#14849]
### Description

When a folder with a large number of files is selected, a list of files is displayed, but at the halfway point.

### Steps To Reproduce

Select and display folders with large numbers of files
The attached capture is the list of files in the folder displayed when the folder is selected.
The files that should be displayed should be at the top of the list.
This is a bug that the files that should be displayed at the top of the list are displayed at this position every time.

![ddd](https://github.com/files-community/Files/assets/92518847/6645a969-a4a6-46dc-8ffa-b2aec410e8cd)

### Requirements

- e.g. Fix crash that occurs when...
Even if you select a folder with a large number of files, the list of files displayed should show the top of the files

### Files Version

3.2.2.0

### Windows Version

10.0.19045.4046

### Log File

[debug.log](https://github.com/files-community/Files/files/14414605/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #5825 . You can check there or click subscribe in the right sidebar for updates.
