### ISSUE TITLE
Handling symbolic link

### ISSUE THREAD

**Issue by Timocaillou** [files-community/Files#14851]
### What feature or improvement do you think would benefit Files?

When you have a symbolic link (command mklink) in a folder, windows explorer tell you it's one and when opening it, you see that you're in another drive for example. Files see the link as a normal folder. 
I'm not sure if this count as a bug, anyway it can be nice to know your dealing with a symbolic link, I can imagine some very bad scenario coming from the confusion ^^

### Requirements

- Display symbolic link in another manner than usual folders
- Open the target folder instead of the virtual folder

### Files Version

3.2

### Windows Version

Windows 10

**Comment by Josh65-2201** [comment]
Thanks for the feedback, What does Windows File Explorer show for them?

**Comment by Josh65-2201** [comment]
@Timocaillou Can you provide the information requested in the last comment
