### ISSUE TITLE
Bug: Adaptive layout is broken

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#14854]
### Description

Starting in v3.2.4, adaptive layout is missing from the right click context menu, and doesn't work when toggled from the layout picker.

### Steps To Reproduce

1. Open layout picker
2. Toggle the option for adaptive
3. Nothing happens

### Requirements

- Correctly apply adaptive layout

### Files Version

v3.2.4

### Windows Version

Windows 11

### Log File

NA

**Comment by hishitetsu** [comment]
This occurs when "Sync layout and sorting preferences across directories" is on and also occurs in v3.2.2.
Adaptive layout seems to want to be disabled when the sync layout option is on.
https://github.com/files-community/Files/blob/63364eace9eede83fe11fa0028491b60f6d20bb3/src/Files.App/Data/Contexts/DisplayPage/DisplayPageContext.cs#L13

**Comment by yaira2** [comment]
You're right! I think we can address this confusion by taking these steps when syncing is enabled
1. Disable the adaptive switch in the Layout Picker (we can add a little info icon to explain)
2. Remove the option from the settings dropdown menu (we can display a teaching tip if adaptive is already selected and the user enables the syncing setting)
