### ISSUE TITLE
Multi pane (and other Move operations) - Right Click & Drag = MOVE compatibility

### ISSUE THREAD

**Issue by noblemd00** [files-community/Files#14859]
### What feature or improvement do you think would benefit Files?

I am new to the Files App so if there is a setting (other than Left Click-pressing the Shift Key) I have not found to accomplish this - please advise! 

Multi panes (& other move operations) - Right Clicking File/Folder and drag should either bring up a Copy/Move popup menu or do the same as Shift Drag (Move file) to facilitate easy transition.

Files App should have mouse commands compatible with other File Explorers/OS/Programs for consistent operation and easy transition.

### Requirements

1. Right Click and Drag - MOVE should be available for easy file manipulation (moving operations) without having the diversion of clicking a key on the keyboard. Good operating flow should not require diverting attention to the keyboard to press the shift key.
2. Right Click and Drag (Move) is the DeFacto standard in virtually every File Explorer type program.
3. Right Click and Drag (Move) is the DeFacto standard in virtually every program that moves or manipulates text/icons/and other items.
4. Right Click and Drag (Move) is the DeFacto standard in virtually every operating system.

### Files Version

3.2.2

### Windows Version

Windows 11  

### Comments

Right Click Drag = Move is an established standard. 
Adapting the Shift Drag code to Right Click Drag should be strait forward!

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #1396. You can check there or click subscribe in the right sidebar for updates.
