### ISSUE TITLE
Tagging OneDrive files

### ISSUE THREAD

**Issue by earion68** [files-community/Files#14867]
### Description

Files that are tagged are getting un-tagged for OneDrive files that are updated by other users.

### Steps To Reproduce

1. In a OneDrive folder, tag a specific file
2. Get this file updated by someone else and wait for OneDrive to re-sync
3. The tag on the file disappears

### Requirements

Once a file is tagged it should remain tagged.

### Files Version

3.2.3.0

### Windows Version

10.0.19044.3930

### Log File

[debug.log](https://github.com/files-community/Files/files/14446916/debug.log)

**Comment by 0x5bfa** [comment]
Thank you for the feedback.

If you have another cloud drive could you confirm this is not an issue with OneDrive specifically?

**Comment by yaira2** [comment]
@earion68 can you check the following?
1. Enable showing alternate data streams from Settings > Folders > Expand hidden items
2. After tagging a file and refreshing the folder, is there an additional file ending in `:files`?
3. Do that file sync to other devices? (you might need to install Files on the other devices to check)
![image](https://github.com/files-community/Files/assets/39923744/88d980ba-ad39-4c1f-98c4-f0100c100169)

**Comment by earion68** [comment]
@yaira2 
step 2: after file tagging, see below
![image](https://github.com/files-community/Files/assets/54678154/feb754ee-13f6-4523-ac5c-8380ebbf2bd2)

step 3, after another colleague updated the file, the hidden file disappears (and is anyway not stored on OneDrive)
![image](https://github.com/files-community/Files/assets/54678154/f3b5a6af-1523-4bdf-a7af-b3daa121d94b)

additionally, I wouldn't expect this :file to be synced to OneDrive, as my tags are mine only and my colleagues do not necessarily have the same

**Comment by earion68** [comment]
> Thank you for the feedback.
> 
> If you have another cloud drive could you confirm this is not an issue with OneDrive specifically?

Sadly I am only using OneDrive

**Comment by Josh65-2201** [comment]
Tags use ADS (Alternative Data Streams) to be saved, so `:file` would added for them. I believe Office must be removing them during saving as It was also mentioned here https://github.com/files-community/Files/issues/10186.

**Comment by earion68** [comment]
I assume while syncing from remote to local then, because syncing from local to remote seems to keep the :file 

Anyway, do you believe this can be fixed?

**Comment by Josh65-2201** [comment]
Microsoft would have to add an option to not remove them when saving in the Office suite.

**Comment by earion68** [comment]
Same happens with Word and PowerPoint documents. Did not try with other types.
Wouldn't it be possible to store the tags in a database instead?

**Comment by yaira2** [comment]
> Does that hidden file sync to other devices? (you might need to install Files on the other devices for this)

**Comment by earion68** [comment]
> > Does that hidden file sync to other devices? (you might need to install Files on the other devices for this)

doesn't look like it

**Comment by earion68** [comment]
To summarize:
- with regular (non-OneDrive) folders, file tagging works well
- with OneDrive folders, file tagging works well locally until a colleague updates a file and OneDrive re-syncs the file locally. I do have OneDrive folders that I am the only one to use, and never had any issue with tagging there.

**Comment by yaira2** [comment]
Unfortunately, this is a limitation with using alternate data streams (see the bottom of [docs](https://files.community/docs/features/tags)). Using a database would help in theory but that could get confusing if the user moved the file externally (eg via File Explorer) and the tag disappeared.

**Comment by yaira2** [comment]
> Anyway, do you believe this can be fixed?

I don't know the chances, but it should be fixed if Microsoft adds ADS support to OneDrive. The other scenario is that Windows gets native support for tags, and we can rework the system in Files to take advantage of this.

**Comment by earion68** [comment]
Got it, thanks for the explanation.
Possible workaround I'm thinking about : could I store the list of files I want to tag somewhere and have a script regularly re-tag the files on my side?

**Comment by yaira2** [comment]
We apologize for this limitation and hope a proper solution is found, but in the meantime your idea should work. Each tag has a guid that gets written to the alternate data stream (you can find the guids by exporting settings, or by manually copying them from the existing data stream files).

Here is an example script
```ps
# Specify the path to your target file
$filePath = "C:\Users\..."

# Content to write to the alternate data stream
$content = "79376daf-c44a-4fe4-aa3b-8b30baea453e,c84a8131-c4de-47d9-9440-26e859d14b3d,f7e0e137-2eb5-4fa4-a50d-ddd65df17c34"

# Create the alternate data stream
try {
    $streamName = ":files"
    Set-Content -Path "$filePath$streamName" -Value $content -NoNewline
    Write-Host "Alternate data stream created successfully in $filePath!"
} catch {
    Write-Host "Error creating alternate data stream: $_"
}
```

**Comment by yaira2** [comment]
@earion68 did you try the script?

**Comment by earion68** [comment]
@yaira2 I tried the code, it works well, thanks!

Now I need to write a listener script that will browse the folder and maintain the list of tagged file somewhere, and re-tag the items on which it is missing. It will take me some time.

**Comment by yaira2** [comment]
Thanks! Please consider sharing whatever solution you come up with so other can benefit from it as well.

**Comment by yaira2** [comment]
I created a script to export all tagged items to a csv file
``ps1
# Define the drive to iterate through
$drive = "C:\"

# Define the CSV file path
$csvFilePath = "C:\path\to\output.csv"

# Function to read ADS content
function Get-ADSContent {
    param (
        [string]$filePath,
        [string]$streamName
    )
    $adsPath = "$filePath$streamName"
    try {
        if (Get-Item -LiteralPath $adsPath -ErrorAction Stop) {
            return Get-Content $adsPath -Raw
        }
    } catch {
        return $null
    }
}

# Initialize the CSV file with headers
"FilePath,ADSContent" | Out-File -FilePath $csvFilePath -Encoding UTF8

# Iterate through every file on the drive
Get-ChildItem -Path $drive -Recurse -File | ForEach-Object {
    $filePath = $_.FullName
    $adsContent = Get-ADSContent -filePath $filePath -streamName ":files"
    if ($adsContent) {
        $csvLine = "$filePath,""$(($adsContent -replace '"', '""'))"""
        $csvLine | Out-File -FilePath $csvFilePath -Append -Encoding UTF8
    }
}
```
