### ISSUE TITLE
Background image support

### ISSUE THREAD

**Issue by kafuuchinolpx** [files-community/Files#14860]
### What feature or improvement do you think would benefit Files?

Can you provide support for custom background images?

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.2.2.0

### Windows Version

10.0.19045.4046

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #12636 . You can check there or click subscribe in the right sidebar for updates.
