### ISSUE TITLE
advices1

### ISSUE THREAD

**Issue by davidp88** [files-community/Files#14863]
### What feature or improvement do you think would benefit Files?

Sorry for repost,wait let all of your developers read it and then close or else mistakes will happen.If they completely think and work then bugs will be properly fixed

1.Think completely and work and that thinking should be done at once,do like this when writing also ,as little thinking causes mistakes.

2.think of each bit of how it can be improved but don't add useless and unnecessary features

3.Increase patience

4.do important work first

5.If u can't reproduce a bug normally then test thoroughly and try to reproduce for 2,3 times.

6.As far as possible try to reproduce bugs in win10 64bit as most of the users in the world use win10

7.also make the app look very beautiful by using beautiful toolbar icon's,nice looking breadcrumb bar etc..(read twice)

### Requirements

none

### Files Version

latest

### Windows Version

win10

**Comment by Josh65-2201** [comment]
You aren't going to get any different answer in your previous post. If you have a bug or feature request you can make the issue about them. Files already has methods and code guideline for development https://files.community/docs/contributing/code-style which have and continue to work. If changes need to be made then they will be as they need to be.

**Comment by Josh65-2201** [comment]
Styling is also following Windows 11 standard as that is the latest version of Windows and is the one that will continue development after 2025 (Windows 10 end of life). Files style is already nice in all areas and will continue to improve as features are added.

**Comment by davidp88** [comment]
pls reopen it as yaira2 is also a developer,let him also read it

**Comment by Josh65-2201** [comment]
Yair does read them, open or not. I would also like to advise you not to go posting in every repository with the same generic statements. You do not seem to have experience working with a team or those types of areas and not everyone use the same system 100% as it software doesn't work that way.

**Comment by davidp88** [comment]
u cant say surely that yair has read it so give me his mail id and all other dev's mail id
