### ISSUE TITLE
New function 

### ISSUE THREAD

**Issue by mihail8059784** [files-community/Files#14877]
### What feature or improvement do you think would benefit Files?

Adding the "open new tabs in the background" option to the context menu. Grouping and pinning tabs, just like in Microsoft Edge.

### Requirements

Adding the "open new tabs in the background" option to the context menu. Grouping and pinning tabs, just like in Microsoft Edge.

### Files Version

3.2.5.0

### Windows Version

10.0.26016.1012

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Are you asking for the same as #11900?

**Comment by mihail8059784** [comment]
Grouping, pinning tabs and workspaces too. Like Microsoft Edge. Very useful features.

**Comment by mihail8059784** [comment]
And also the option “open new tabs in the background” in the context menu.

**Comment by yaira2** [comment]
The expected behavior is that opening a folder in a new tab should open it in the background automatically. I've pushed a commit to resolve the issue and this will be fixed in the next release.
