### ISSUE TITLE
English Translation is incomplete

### ISSUE THREAD

**Issue by UthredRagnarson** [files-community/Files#14872]
### Description

There are a number of icon descriptions that have not been translated from French to English, i.e., Desktop = Bureau, DVD RW Drive = Lecteur DVD RW, Downloads = Telechargements, etc.

### Steps To Reproduce

Open Files on 'Home' page.

### Requirements

English translation from French is complete.

And happy to help with such translation if that would help.

[debug.log](https://github.com/files-community/Files/files/14452190/debug.log)

### Files Version

3.2.2.0

### Windows Version

10.0.22631.3155

### Log File

[debug.log](https://github.com/files-community/Files/files/14452313/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, pinned folders and quick access are based on the names provided by Windows. You can confirm this by checking File Explorer.

**Comment by UthredRagnarson** [comment]
Thank you

But I am also see the same issue in the context menu, i.e., where I am getting French for the MS part of the context menu description, i.e., "deverroullier avec File Lock Smith" where Explorer is showing "Unlock with File Lock smith". I believe that I should also be seeing the latter under Files, rather than the former?

Kind regards

Solly Charbit
________________________________

**Comment by yaira2** [comment]
It's hard to know what you mean without screenshots or steps to reproduce the issue but regarding folder names and shell extensions, they are retrieved from Windows and Files doesn't have any input.

**Comment by yaira2** [comment]
I want to clarify a misconception in the original post. Files is English by default, so if a string is displaying in another language, it would be because it's a folder name or shell extension that's not part of Files.

**Comment by UthredRagnarson** [comment]
Thanks for the further responses. I will double check what you say but it is seemingly strange that any other 'explorer'-type app that I have trialled or used has never displayed this behaviour, and my installation of Windows 11 is the English (United Kingdom) one from Microsoft, and all settings are for the English version although interestingly I do have the French lanuage pack installed for the dictionary when I write in French. Please see these settings below.

[cid:fe1b4aa3-2b4f-4e94-84a3-e9468c8e87fc]

I am therefore not sure as to why I would be seeing French text especially when the Windows Display language is English, and it states that "Windows features like Settings & File Explorer will appear in this language"...perhaps something somewhere in Files is 'defaulting'/using for some reason the French Language pack installed.

As a test I will remove the French Language pack, reboot and then try Files again to see if the behaviour is the same.

Kind regards, Solly



________________________________

**Comment by yaira2** [comment]
I should clarify, the default localization in the app is set to `Windows Default` so if you French Language that might explain why you're seeing French text. When I said Files is English by default, I meant that all text in the app starts off as English and then gets translated into other languages.

Can you check what happens if you change the language in Files to "English"?

**Comment by UthredRagnarson** [comment]
Hi Yair

Thanks for the suggestion...I have checked the Settings in Files and I had previously switched the Language setting to 'English (United Kingdom) prior to my noticing any of this happening.

More interestingly, if I remove the French Language pack from Windows the 'translations' disappear, and the literals concerned then show perfectly in English. So, as a control measure installed the Spanish Language pack and ran Files again...and...the translations which were in French when the French Language pack was installed are now in Spanish.

I suspect that I can try any other language and the results will be similar...some code, somewhere appears, in certain but unknown circumstances, to be referencing the language pack installed rather than using the language set under the 'Windows Display language' setting.

If I can provide additional information or is there is a way for me to provide you with a further logfile that might help then please let me know. For the time being I can remove the French Language pack (just means that when I want to write in French I will have to temporarily reinstall it, etc.).

Kind regards, Solly


________________________________
