### ISSUE TITLE
Multiple panes for files-uwp

### ISSUE THREAD

**Issue by soumyamahunt** [files-community/Files#1487]
**Is your feature request related to a problem? Please describe.**
Many file explorers implement multiple panes to navigate multiple folders at the same time. This is good for large screen to use complete screen estate.

![ApplicationFrameHost_anfqJel7q2](https://user-images.githubusercontent.com/51203900/87778171-6b341f80-c848-11ea-9b2e-f812db99096b.png)

**Describe the solution you'd like**
The default layout can be the same as of right now. User can use keyboard shortcut to split the pane horizontally or vertically. And each pane will have multiple tabs in them. The focused pane will have a different background than all other panes.

**Describe alternatives you've considered**
Since files-uwp now offers vertical the final design could be much cleaner than the screenshot I attached.

**Additional context**
Would be cool if there could be nested split panes like Windows Terminal offers. Should it be allowed with files-uwp??

**Comment by mdtauk** [comment]
This may cause issues with the navigation pane on the left, no longer being tied to the tabs to the right.  Making sure it reflects the active tab, and remains clear to read what is going on there should be considered.

**Comment by soumyamahunt** [comment]
> This may cause issues with the navigation pane on the left, no longer being tied to the tabs to the right.  Making sure it reflects the active tab, and remains clear to read what is going on there should be considered.

Rasing an event every time the focused pane changes, and navigation pane will make sure to reflect the changes. I don't think there will be any issue there.

**Comment by Jaiganeshkumaran** [comment]
@soumyamahunt Just snap two Files UWP window side by side.

**Comment by soumyamahunt** [comment]
> @soumyamahunt Just snap two Files UWP window side by side.

Snapping doesn't have the same kind of usability improvements as having multiple panes does. For example:
1. You have to take the full screen to do that, although you can use something like PowerToys to use other apps alongside two files-uwp apps, you don't have that much freedom in snapping than multiple panes.
2. Another major disadvantage is keyboard navigation, in snapping you get all the other apps to switch between them while in panes you can just switch between panes.
3. There is lots of freedom to resize window in multi-panes rather than in snapping.

**Comment by Jaiganeshkumaran** [comment]
@Jaiganeshkumaran We can have multiple panes for things like previews of files but not for directories. It doesn't make sense and it will make Files UWP harder to use. Instead, we can have freeform MDI child windows similar to Visual Studio.

**Comment by hunterlan** [comment]
@soumyamahunt, In my opinion, instead of Files UWP, you can use Total Commander or other application from family Commanders. The directed using multiple panes, but Files UWP isn't developing for it. Also, as user opinion, I don't need it.

**Comment by yaichenbaum** [comment]
Merging with #1674.
