### ISSUE TITLE
Windows Network Sharing

### ISSUE THREAD

**Issue by cybergeek1943** [files-community/Files#14873]
### What feature or improvement do you think would benefit Files?

When you right click on a folder in the default windows explorer you can press "Give Access to" or in Properties>Sharing you can share the folder over the network. I do not see this in this files app.

### Requirements

- Add a "Give Access To" button for folder context menus
- In the properties window of folders add a "Sharing" tab

### Files Version

3.2.2.0

### Windows Version

10.0.22631.3227

### Comments

[Here](https://support.microsoft.com/en-us/windows/file-sharing-over-a-network-in-windows-b58704b2-f53a-4b82-7bc1-80f9994725bf) is Microsoft's documentation with pictures and more information

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #5941 and #13761 . You can check there or click subscribe in the right sidebar for updates.
