### ISSUE TITLE
Status File Transfer

### ISSUE THREAD

**Issue by meemore** [files-community/Files#14870]
### What feature or improvement do you think would benefit Files?

Auto open and auto show file transfer speeds, and add a pin to stay open feature

![Screenshot_2](https://github.com/files-community/Files/assets/124497263/68138892-f46f-4923-bb91-28ec6f3e90b5)
![Screenshot_3](https://github.com/files-community/Files/assets/124497263/b2834fb0-6255-4da1-8228-576ec8c86081)

### Requirements

visual.

### Files Version

3.2.4.0

### Windows Version

10.0.22621.3227

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #13560 and #12699 . You can check there or click subscribe in the right sidebar for updates.
