### ISSUE TITLE
Bug: "Open with" icon on right

### ISSUE THREAD

**Issue by dracp** [files-community/Files#14888]
### Description

In some cases the "Open with" icon from the context menu is displayed to the right of the text.

![240303 Files 3 2 5 0_Icono a la dercha de_Abrir con](https://github.com/files-community/Files/assets/102802425/501e6e66-6d10-49c4-a747-de3cad8a27ee)

### Steps To Reproduce

1. Right click on item

### Requirements

Show icon to the left of the text "Open with".

### Files Version

3.2.5.0

### Windows Version

10.0.22631.3235

### Log File

None

**Comment by 0x5bfa** [comment]
Thanks for the feedback!
We’re aware of this, which is caused by introducing a new version of WinAppSdk, and concerning about reverting back to the previous version if we fail to find workaround. Anyways this will be definitely fixed soon; in the next or the next of that preview build.
