### ISSUE TITLE
App Update at App Startup

### ISSUE THREAD

**Issue by Kinhetic1** [files-community/Files#14887]
### What feature or improvement do you think would benefit Files?

It is not a convenient idea to have the app check for updates at each startup. It impacts negatively on productivity. It is better for updates to be checked in the background and also include an option in the settings for users to check for updates.

### Requirements

.

### Files Version

3.2.3.0

### Windows Version

10.0.22631.3155

**Comment by yaira2** [comment]
Files already checks for app updates in the background and only displays a notification in the toolbar if an update is available. Can you elaborate on the issue?

**Comment by emvaized** [comment]
> Files already checks for app updates in the background and only displays a notification in the toolbar if an update is available. Can you elaborate on the issue?

For me it isn't — I see this "update check" on every Files app startup, even when it's minimized to the system tray: 
 
![Screenshot 2024-03-05 085546](https://github.com/files-community/Files/assets/37851576/ed5f6a3d-e345-41f2-b5a6-30b9a8587405)

Probably OP experiences the same problem.

**Comment by Josh65-2201** [comment]
Are you on 3.2.3.0?

**Comment by Kinhetic1** [comment]
> ### What feature or improvement do you think would benefit Files?
> It is not a convenient idea to have the app check for updates at each startup. It impacts negatively on productivity. It is better for updates to be checked in the background and also include an option in the settings for users to check for updates.
> 
> ### Requirements
> .
> 
> ### Files Version
> 3.2.3.0
> 
> ### Windows Version
> 10.0.22631.3155
> 
> ### Comments
> _No response_

I do not know if it is due to installing the Files App using your classic installer as I had issues using my credit card on Microsoft store but anytime I click a folder to open from any location on my PC or launch the app freshly, what comes up first is an update check small window by the left which also attempts to load some other information. I may not be able to describe the accurate information it displayed as I already have it uninstalled, in as much as I find the app beautiful, but this behaviour is unproductive. I expect that the Files App will launch directly on each attempt and also that opening a folder from any location opens in the existing instance of the Files App but that's not the case as observed.

**Comment by Kinhetic1** [comment]
> Files already checks for app updates in the background and only displays a notification in the toolbar if an update is available. Can you elaborate on the issue?

I do not know if it is due to installing the Files App using your classic installer as I had issues using my credit card on Microsoft store but anytime I click a folder to open from any location on my PC or launch the app freshly, what comes up first is an update check small window by the left which also attempts to load some other information. I may not be able to describe the accurate information it displayed as I already have it uninstalled, in as much as I find the app beautiful, but this behaviour is unproductive. I expect that the Files App will launch directly on each attempt and also that opening a folder from any location opens in the existing instance of the Files App but that's not the case as observed.

**Comment by Kinhetic1** [comment]
> Are you on 3.2.3.0?

Yes

**Comment by yaira2** [comment]
@emvaized that prompt isn't from Files, it's from the App Installer component that's bundled with Windows. From what other users have reported, updating App Installer to the latest version fixes this issue. You can update it from the Microsoft Store app on your device, or by downloading and running the [installer](https://learn.microsoft.com/en-us/windows/msix/app-installer/install-update-app-installer).

**Comment by emvaized** [comment]
@yaira2 
Hm, I just tried running the installer, and it seems I'm already running the latest version of this component. It doesn't give me option to update, only to fully reinstall: 
![Screenshot 2024-03-05 172232](https://github.com/files-community/Files/assets/37851576/58b275de-c140-4e7e-839d-d6e0b69f8b00)

**Comment by yaira2** [comment]
It seems the installer is out of date because the newest version of App Installer is `1.23.532.0`.

You can find the installer on the WinGet repo https://github.com/microsoft/winget-cli/releases/tag/v1.8.532-preview (it's the one labeled as `Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle`.

**Comment by Kinhetic1** [comment]
> That prompt isn't from Files, it's from the App Installer component that's bundled with Windows. From what other users have reported, updating App Installer to the latest version fixes this issue. You can update the component from the Microsoft Store app on your device, or by downloading and running the [installer](https://learn.microsoft.com/en-us/windows/msix/app-installer/install-update-app-installer).

Ok. I tried this link but it points to the official release of AppInstaller which is up to date on my system, (Version: 1.22.10582.0). But the second link you shared points to the experimental version (Version: 1.23.532.0). I have now installed Version: 1.23.532.0 but the problem persists. I set the FilesApp to be the default File Explorer.

**Comment by yaira2** [comment]
You likely need to reinstall Files as well (uninstall first and then run the Files installer again).

**Comment by Kinhetic1** [comment]
> It seems the installer is out of date because the newest version of App Installer is `1.23.532.0`.
> 
> You can find the installer on the WinGet repo https://github.com/microsoft/winget-cli/releases/tag/v1.8.532-preview (it's the one labeled as `Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle`.

Ok. I tried this link but it points to the official release of AppInstaller which is up to date on my system, (Version: 1.22.10582.0). But the second link you shared points to the experimental version (Version: 1.23.532.0). I have now installed Version: 1.23.532.0 but the problem persists. I set the FilesApp to be the default File Explorer. 

If an instance of FilesApp is open and I tried launching another instance, the same box appears. If I attempt to open a folder from my desktop, the folder does not open, except that it attempts to open that same box but nothing gets shown afterwards. So, apparently, folders does not open if I attempt to launch from outside the FilesApp. Folders open only within the FilesApp and the update box keeps coming up.

![FilesApp1](https://github.com/files-community/Files/assets/125685627/0d5c0931-5483-47ac-ad48-8ffdce032318)
![FilesApp2](https://github.com/files-community/Files/assets/125685627/435842b6-6595-4329-a953-6cf60e688b8e)

**Comment by Kinhetic1** [comment]
> You likely need to reinstall Files as well (uninstall first and then run the Files installer again).

Still the same after upgrading the installer and uninstalling and re-installing the Files App.

**Comment by yaira2** [comment]
The other option is to:
1. Use the Store version, this doesn't use App Installer so it won't have this issue.
2. Try installing the msixbundle but it's possible that it'll still have this problem https://cdn.files.community/files/stable/Files.Package_3.2.3.0_Stable_Test/Files.Package_3.2.3.0_x64_ARM64_Stable.msixbundle

**Comment by emvaized** [comment]
@yaira2 
I just tried installing the package you shared, and it didn't have the loading popup on launch. Does it mean this version won't receive automatic updates in the future?

**Comment by yaira2** [comment]
It should still update as before, the only reason the other prompt is displayed is because of AppInstaller (it's not supposed to, but it seems to happen on some devices).

Why do we use AppInstaller? The msixbundle will only install if the other dependencies are installed first, the AppInstaller file takes care of this for users.

**Comment by Kinhetic1** [comment]
> The other option is to:
> 
> 1. Use the Store version, this doesn't use App Installer so it won't have this issue.
> 2. Try installing the msixbundle but it's possible that it'll still have this problem https://cdn.files.community/files/stable/Files.Package_3.2.3.0_Stable_Test/Files.Package_3.2.3.0_x64_ARM64_Stable.msixbundle

Hurray!. I installed the msixbundle through the powershell route. The update prompt no longer comes up. I have another observation though, but will open another thread for it. Thanks for the effort put in the making of the app. Will consider making some donation later on when I fix my credit card issue.

**Comment by yaira2** [comment]
Thanks for the update! We're glad it worked 👍 

A third option I forgot to mention is the Chocolatey method, it's not officially supported but it's another way to work around this issue.

**Comment by emvaized** [comment]
@yaira2 
Thanks for explanation! It clears it out. 

Is there any permanent link where most recent version could be downloaded as msixbundle? The "classic installer" option on the website only allows to download the regular AppInstaller version

**Comment by yaira2** [comment]
Just replace the version number in to match the latest release `https://cdn.files.community/files/stable/Files.Package_3.2.3.0_Stable_Test/Files.Package_3.2.3.0_x64_ARM64_Stable.msixbundle`

**Comment by emvaized** [comment]
> Just replace the version number in the link to match the latest release `https://cdn.files.community/files/stable/Files.Package_3.2.3.0_Stable_Test/Files.Package_3.2.3.0_x64_ARM64_Stable.msixbundle`

I tried to replace the number in link, and it doesn't work for recent version 3.3.0.0: 
`https://cdn.files.community/files/stable/Files.Package_3.3.0.0_Stable_Test/Files.Package_3.3.0.0_x64_ARM64_Stable.msixbundle` 

Result: 
`The specified blob does not exist`

**Comment by yaira2** [comment]
The link works on my end so it might be a caching issue in Cloudflare. I cleared the cache so you can try again and see if it works.

**Comment by emvaized** [comment]
> The link works on my end so it might be a caching issue in Cloudflare. I cleared the cache so you can try again and see if it works.

It still doesn't work for me. Maybe something wrong in the link I shared above?

**Comment by yaira2** [comment]
It's the correct link but `arm64` is no longer capitalized https://cdn.files.community/files/stable/Files.Package_3.3.0.0_Stable_Test/Files.Package_3.3.0.0_x64_arm64_Stable.msixbundle

**Comment by emvaized** [comment]
This one works. Thanks!

**Comment by emvaized** [comment]
> It's the correct link but `arm64` is no longer capitalized https://cdn.files.community/files/stable/Files.Package_3.3.0.0_Stable_Test/Files.Package_3.3.0.0_x64_arm64_Stable.msixbundle

This one works. Thanks!

**Comment by hthr24nzkyuc** [comment]
Is there a download link for the preview version?
Thanks!

**Comment by yaira2** [comment]
@hthr24nzkyuc https://files.community/download

**Comment by hthr24nzkyuc** [comment]
@yaira2 I meant the preview msixbundle file, thanks a lot!

**Comment by yaira2** [comment]
https://cdn.files.community/files/preview/Files.Package_3.5.8.0_Preview_Test/Files.Package_3.5.8.0_x64_arm64_Preview.msixbundle

**Comment by emvaized** [comment]
Unfortunately the update problem still occurs to me with latest App Installer `1.25.320.0`
