### ISSUE TITLE
Horizontal scroll in Column View

### ISSUE THREAD

**Issue by codingU4EA** [files-community/Files#14886]
### What feature or improvement do you think would benefit Files?

Make horizontal scrolling easier in column view. In many Windows applications such as a browser one is able to click the scroll wheel to scroll horizontally easily. Please enable this feature or one like it so that scrolling horizontally in column view easier. Right now user must use the horizontal scroll bar at the bottom of the window. 

### Requirements

Use modifier key (such as Shift) or click of scroll window to permit user to scroll horizontally in column view. 

### Files Version

3.2.2.0

### Windows Version

10.0.22631.3235

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #10006. You can check there or click subscribe in the right sidebar for updates.
