### ISSUE TITLE
Enlarge space for text in Spanish

### ISSUE THREAD

**Issue by dracp** [files-community/Files#14889]
### What feature or improvement do you think would benefit Files?

Present a coherent graphic image.

### Requirements

Enlarge space under "Tool" icon in context menu

![240303 Files 3 2 5 0_Falta espacio para_Abrir Propiedades](https://github.com/files-community/Files/assets/102802425/59396c0d-e167-4459-a3a4-d6587dbd51fd)

### Files Version

3.2.5.0

### Windows Version

10.0.22631.3235

**Comment by 0x5bfa** [comment]
Thanks for the feedback and using the app!
We’re aware of this issue, which is caused by introducing a new version of WinAppSdk 😅 and working on removal those labels.
