### ISSUE TITLE
Smooth Scroll

### ISSUE THREAD

**Issue by nimbus2332** [files-community/Files#14898]
### What feature or improvement do you think would benefit Files?

Hi guys, please make the built-in SmoothScroll support like Chrome.

Why is that? So that my eyes don't hurt/get tired, I have a 144 Hz monitor, and I use "Files" almost every day to view pictures, but even 144Hz doesn't help when I flip through pictures. 

Scrolling happens based on their WIndows settings, but it would be great if someone integrated smooth scrolling.

I must admit, the Files application made it much easier for me to view and filter images thanks to tags, thanks to all the development participants.

The "NOT" filter is still missing, when I want to see all the pictures that are not marked with the "Work" tag, I did not find such a function. 

Thank you!

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.2.6.0

### Windows Version

11. 2H24

**Comment by nimbus2332** [comment]
I know that there is a "smooth scrolling" in WIndows itself, but this is not enough when the images are zoomed to the maximum and there are jerks when scrolling.

I would like to get the same smoothness as Chrome with the enabled feature - chrome://flags/#smooth-scrolling

**Comment by yaira2** [comment]
Thank you for your feedback, Files already has smooth scroll so it's likely this is a framerate issue with WinUI. I recommend adding your feedback on the WinUI repo so Microsoft can take it into account and hopefully fix it in a future version.
https://github.com/microsoft/microsoft-ui-xaml/issues/7373

**Comment by yaira2** [comment]
Just to add on, you're not alone with this issue. Other users with high refresh rates have made similar comments but the improvements need to come from Microsoft.
