### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by davidp88** [files-community/Files#14890]
### Description

after installing it show this error and i can't run it

![f1](https://github.com/files-community/Files/assets/80623401/b0698191-ff55-44cf-bf5b-daa41e6ea8d0)

### Steps To Reproduce

none

### Requirements

shows the above error

### Files Version

3.2.3.0

### Windows Version

win10 22h2

### Log File

none

**Comment by Josh65-2201** [comment]
Are you using an unofficial (like Atlas OS or ReviOS etc.) or a modified (like disabled Windows update system, removed the Microsoft store, used a debloat program/script etc.) version of Windows?

If so
1. Make sure `Windows update` and `delivery optimization` services are enabled, restart Windows and try again.

2. You can also try
   1. Opening PowerShell as administrator
   2. Run this command
   ```Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/stable/Files.Package.appinstaller```
   3. See if Files is in the start menu all apps section

If you get the same error you will not be able to use Files as the modified versions of Windows are not supported and remove component's needed to install.
