### ISSUE TITLE
PDF file preview in Files and add Tags

### ISSUE THREAD

**Issue by BartHNL** [files-community/Files#14896]
### What feature or improvement do you think would benefit Files?

Hello,

I'm currently testing if Files (3) is the solution for my file management requirements.

For now (after 10 minutes of testing) I have two improvements I'd like to request:

1) I don't see a preview for a (selected) pdf file. Could that be added?
2) When I want to add a not-yet-existing tag to a file, I should be able to make the new tag on the fly and find it added to the Tags list afterwards. Could you make that possible?

GrZ Bart Hoeksel, Nedcom

### Requirements

- Adding PDF preview will make it possible to preview PDF files in Files
- Adding new Tags to files from contextual menu will make it possible to add new tags quicker

### Files Version

3.2.3.0

### Windows Version

Edition	Windows 11 Home Version	23H2 Installed on	‎28-‎9-‎2022 OS build	22631.3235 Experience	Windows Feature Experience Pack 1000.22687.1000.0

**Comment by Josh65-2201** [comment]
Thanks for the feedback, You can open the info pane (Ctrl + Alt + i) and click preview and were tracking your second request in #12146. You can check there or click subscribe in the right sidebar for updates.
