### ISSUE TITLE
Files does not allow Ejection of mounted virtual hard disk drives because it thinks they are Fixed Disk Drives

### ISSUE THREAD

**Issue by JollyRoger8X** [files-community/Files#14899]
### Description

I cannot eject a mounted virtual hard disk drive in Files because the Eject command is not shown in contextual menus when right-clicking on the mounted drive.

### Steps To Reproduce

1. Create a virtual hard disk drive VHDX file - [as shown here](https://www.tenforums.com/tutorials/138380-create-set-up-new-vhd-vhdx-file-windows-10-a.html).
2. Double-click the VHDX file to mount the drive.
3. In the File "Home" view, right-click the drive to view the contextual menu.
4. Note that the Eject command is not present.
5. Choose Properties from the contextual menu and note that Files shows the drive type as Fixed Disk Drive.

### Requirements

I expect Files to who the Eject command for all mounted drives, including mounted virtual hard disk drives.

### Files Version

3.2.6.0

### Windows Version

10.0.19045.3324

### Log File

not applicable

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #10154 . You can check there or click subscribe in the right sidebar for updates.
