### ISSUE TITLE
Bug: Video encode rate not shown correctly

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#14892]
### Description

*

### Steps To Reproduce

1. Open properties of video file
2. Click Details
3. See video encode as
![image](https://github.com/files-community/Files/assets/26977075/1bedf6ca-0f34-4170-8b70-dc35e6f66222)

### Requirements

- Show encode rate as MB/s

### Files Version

3.2.6.0

### Windows Version

10.0.22621.3155

### Log File

[debug.log](https://github.com/files-community/Files/files/14475001/debug.log)

**Comment by 0x5bfa** [comment]
I'll fix today.

**Comment by 0x5bfa** [comment]
This has been fixed and the fix will be included in the next release.
