### ISSUE TITLE
restart computer doesnt continue where left off

### ISSUE THREAD

**Issue by adhhrg** [files-community/Files#14909]
### Description

restart computer doesnt continue where left off

### Steps To Reproduce

have tabs open, 
restart
open files
doesnt reopen the tabs

### Requirements

will remember tabs when restart computer

### Files Version

3.2.3.0

### Windows Version

10.0.22631.3155

### Log File

no log

**Comment by yaira2** [comment]
Thank you for feedback, this was resolved in the preview version of Files and will be included in the next stable release.
