### ISSUE TITLE
Lagging

### ISSUE THREAD

**Issue by ajay-mishra7** [files-community/Files#14902]
### Description

This app takes 9x time to open the app, folder, file than the inbuild file explorer. The time gap between click and opening is 9.6 seconds which is 9x than file explorer i.e 1 seconds 

### Steps To Reproduce

1.Click on the file
2.Watch the startup time

### Requirements

Fix the startup time 

### Files Version

3.2.3.0

### Windows Version

10.0.22631.3235

### Log File

[debug.log](https://github.com/files-community/Files/files/14492786/debug.log)

**Comment by yaira2** [comment]
@ajay-mishra7 how does this compare to the preview version?
https://files.community/download/preview

**Comment by yaira2** [comment]
I'm assuming this is the first launch, how does resuming from the background compare to File Explorer?

**Comment by yaira2** [comment]
That's good to hear! As of now this only helps with a single window, but we're planning to make this work with additional windows as well.
