### ISSUE TITLE
[Request] Apply "compact" view to the "Tiles" view mode as well

### ISSUE THREAD

**Issue by emvaized** [files-community/Files#14906]
### What feature or improvement do you think would benefit Files?

When "Use compact spacing in the details layout" option is enabled in settings, it doesn't affect the "Tiles" view mode. However, it would be great if it reduced spacing and font size in "Tiles" view as well, as it could also be considered as one of the more "detailed" views. 

By default, "Tiles" view wastes too much screen space. 
Here's comparison with tiles from Windows Explorer: 
 
![Снимок экрана 2024-03-05 203010](https://github.com/files-community/Files/assets/37851576/409ec7c0-6465-4e0b-afd3-de529a4980e3)

### Requirements

- "Tiles" is a wonderful view mode, as it shows more text information for each element, while also preserving the thumbnail quite readable. This proposal will make it even more useful by increasing the information density. Current "tiles" design wastes too much screen space on spacing and unneccessary big file titles

### Files Version

3.2.3.0

### Windows Version

Windows 11 Pro 23H2 (22631.3155 )

**Comment by yaira2** [comment]
Thank you for your feedback, this is on our todo list. You can track the progress in #10492.
