### ISSUE TITLE
Bug: Unable to access administrative shares

### ISSUE THREAD

**Issue by nmangue** [files-community/Files#14903]
### Description

I am using Files in an enterprise environment to access a server administrative shares drive by using \\myserver\c$. Doing so I get an error message (cf. screenshot). The error occurs on the first call to WNetAddConnection3 on NetworkDrivesAPI@136 which returns Win32Error.ERROR_ACCESS_DENIED. This is normal since Files is running with a user account and I need to use an administrator account to access this share. However the rights elevation is currently not triggered. Reusing the following block to trigger the elevation does work.
![Capture d’écran 2024-03-05 091807](https://github.com/files-community/Files/assets/8030500/3af690d9-1f55-4f7b-97de-920eda8b306b)

### Steps To Reproduce

1. Launch Files with a "low-privileged" user account
2. Access a server adminsitrative share (\\myserver\c$)

### Requirements

Ask for credentials if the current user is not allow to access the share

### Files Version

3.2.3.0

### Windows Version

Windows 10 Entreprise 22H2 19045.3324

### Log File

NA

**Comment by 0x5bfa** [comment]
Thanks for the feedback.
Please get approval (Ready for build) from maintainers before working on issues to avoid work being wasted in the future.

**Comment by yaira2** [comment]
@nmangue thank you for the report and fix, this will be included in the next release.
