### ISSUE TITLE
Feature: Select file when using open file/folder location from other programs

### ISSUE THREAD

**Issue by ajay-mishra7** [files-community/Files#14901]
### What feature or improvement do you think would benefit Files?

This app doesn't highlight/indicate the file which i downloaded from browser and click on "Show in folder" option. Whenever i click on "Show in folder" it just open the folder where the file exists but doesn't shows which file i want to open.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.2.3.0

### Windows Version

10.0.22631.3235

**Comment by yaira2** [comment]
We're currently tracking this in #14429. You can add a comment or click subscribe to be notified of updates.

**Comment by yaira2** [comment]
> Last I heard it was removed due to code licensing issue in files launcher

It can be added back but we need to write the code from scratch (previously we used code from another project).
