### ISSUE TITLE
App Crashes when accessing ejected CD/DVD-Drive and no refresh

### ISSUE THREAD

**Issue by cocoon** [files-community/Files#1490]
**Describe the bug**
When accessing an ejected CD/DVD-Drive the app crashes.

**To Reproduce**
1. Mount an ISO file in Windows
2. Start Files UWP
3. Eject ISO
4. Try to access the drive in Files UWP

**Expected behavior**
Files UWP should recognize that a drive disappears and refresh the list and catch the exception without crashing.

https://github.com/files-community/files-uwp/blob/master/Files/BaseLayout.cs#L221

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS Version: Windows 10 2004
 - App version: v0.12.0

**Additional context**
-

**Comment by yaichenbaum** [comment]
@cocoon This issue should be fixed with #2406.
