### ISSUE TITLE
Bug: Unable to edit the properties of multiple items simultaneously

### ISSUE THREAD

**Issue by kierankihn** [files-community/Files#14900]
### Description

When using checkboxes to select multiple items, I am not able to simultaneously change the properties of multiple items.

### Steps To Reproduce

1. Use checkboxes to select multiple items
2. Right click and select properties
3. Select `hidden` in `general > properties`
4. Refresh and none of these files' properties has been changed

### Requirements

The files I selected should be hidden.

### Files Version

3.2.3.0

### Windows Version

10.0.19045.4123

### Log File

[debug.log](https://github.com/files-community/Files/files/14489669/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you make sure that you can apply it to a single file. Can you also try applying it to all the files you want in Windows File Explorer

**Comment by kierankihn** [comment]
Yeah, I am able to apply it to a single file, and I am also able to applying it to all the files in Windows File Explorer

**Comment by 0x5bfa** [comment]
Could you tell me types of files you selected, such as docx, folders, txt. or does that totally not matter?

**Comment by kierankihn** [comment]
I've tested cpp files, zip files, and folders. All of them didn't work.

**Comment by yaira2** [comment]
A fix will be included in the next update
