### ISSUE TITLE
Use Everything for search

### ISSUE THREAD

**Issue by fellipec** [files-community/Files#14916]
### What feature or improvement do you think would benefit Files?

Files could use, if installed, the app [Everything](https://www.voidtools.com/) for search. 
The app [Everything Toolbar](https://github.com/srwi/EverythingToolbar) may have useful code to show how to interact with the said app. 

### Requirements

Files should be able to detect the presence of Everything app, and when its present, use its engine for file search.
This will make any file search almost instantly

### Files Version

3.2.2.0

### Windows Version

10.0.22621.3155

### Comments

Everything index and searches through files faster and more efficient than Windows built-in search. Is a true game changer.

**Comment by yaira2** [comment]
Thank you for your feedback, we're currently tracking this in #5845. You can add a comment or click subscribe to be notified of updates.
