### ISSUE TITLE
Does not "Continue where you left off" when the user closes the last tab (instead of closing the app)

### ISSUE THREAD

**Issue by skst** [files-community/Files#14910]
### Description

The setting **Startup settings** = _Continue where you left off_ is not obeyed when Files is restarted after closing the last tab (instead of closing the app) by clicking the "x" (or pressing CTRL+W or CTRL+F4).

### Steps To Reproduce

1. Run **Files**.
2. Ensure Settings > **Startup settings** = _Continue where you left off_.
3. Navigate to a folder (e.g., `C:\OneDrive`).
4. Close the tab (which also closes Files) by clicking "x" on tab or pressing CTRL+W or CTRL+F4.
5. Run **Files** again.

Note that Files is showing the "Home" screen instead of the folder where you navigated in step 3 (e..g, `C:\OneDrive`).

### Requirements

Fix Files to restore the tab (and the folder that was open in it) when it was closed by the "x" (or CTRL+W or CTRL+F4) if the Settings > **Startup settings** = _Continue where you left off_ option is set.

### Files Version

3.2.2.0

### Windows Version

10.0.22621.3235

### Log File

[debug.log](https://github.com/files-community/Files/files/14504815/debug.log)

**Comment by 0x5bfa** [comment]
Thanks for the feedback.

**Comment by yaira2** [comment]
Closing a tab removes it from the tab list and it's how this is supposed to work (I believe Edge works the same way).

**Comment by skst** [comment]
That is only when more than one tab is open. When you close the LAST tab--which is what I specified in this bug report--in Edge, in Windows File Explorer, or in the Files app, the app itself closes.

**Comment by yaira2** [comment]
This matches the behavior in Edge and Chrome. If you'd like to continue where you left off, you can do so by closing the app instead of removing the tab.

**Comment by skst** [comment]
I see your point, but I'm not sure I understand why Files should act like a browser. 🤷‍♂️ 🙂

**Comment by yaira2** [comment]
Continue where you left off was inspired by the feature in browsers.
