### ISSUE TITLE
Please add "Owner" to Details layout columns

### ISSUE THREAD

**Issue by ja422fs** [files-community/Files#14919]
### What feature or improvement do you think would benefit Files?

I always show the "Owner" in File Explorer, but I would like to use Files instead.  The only feature not keeping me from doing so is having the "Owner" column.

### Requirements

Add an optional "Owner" column to the details layout.

### Files Version

3.2.2.0

### Windows Version

10.0.22631.3235

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #8366 . You can check there or click subscribe in the right sidebar for updates.
