### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MarathonMax** [files-community/Files#14915]
### Description

Shift right-click on a folder

### Steps To Reproduce

Shift right-click on a folder

### Requirements

Fix crash that occurs when Shift right-click on a folder

### Files Version

3.2.2.0

### Windows Version

11

### Log File

[debug.log](https://github.com/files-community/Files/files/14528832/debug.log)

**Comment by MarathonMax** [comment]
I was not trying to cast anything, just wanted to access the share with Google Drive menu which in Windows Explorer is shift right click and in Files is simply right click / More.

**Comment by yaira2** [comment]
Correct, but the "Cast to device" item is in the extended context menu. Does it crash consistently, or only for media files?

**Comment by yaira2** [comment]
If you don't need the extended menu, it's best to just right click normally.
