### ISSUE TITLE
Keyboard shortcuts on context menus

### ISSUE THREAD

**Issue by chuchanpr** [files-community/Files#1492]
**Is your feature request related to a problem? Please describe.**
Keyboard shortcuts on context menus

**Describe the solution you'd like**
after pressing the menu button on keyboard, i would like to have keyboard shortcuts to use most of the items listed

**Describe alternatives you've considered**
Using shortcuts for copy, cut, paste is available without using the context menus, however, certain functions would require the context menu usage, such as, open with code, properties, etc

**Additional context**
Not all list items in the context menu would need the shortcut

**Comment by yaichenbaum** [comment]
This issue should be resolved with #2163.
