### ISSUE TITLE
No thumbnails

### ISSUE THREAD

**Issue by DaveFriedel** [files-community/Files#14921]
### Description

When in a folder full of images, no thumbnails are displayed.  Changing to Medium or Large icons doesn't work. Changing the Files app settings to "show thumbnails" (even switching this back and forth) doesn't work.  Won't show thumbnails at all.

### Steps To Reproduce

Go to a folder full of images.  
No thumbnails show up.

### Requirements

Should show thumbnails if that setting is turned on.

### Files Version

3.2.2.0

### Windows Version

10.0.22631.3235

### Log File

[debug.log](https://github.com/files-community/Files/files/14541079/debug.log)

**Comment by DaveFriedel** [comment]
Sometimes it displays partial thumbnails.  Some files work, some don't.
![screenshot](https://github.com/files-community/Files/assets/221716/ed931c21-d7bb-4f67-bb92-9d5fc96109f3)

**Comment by Josh65-2201** [comment]
Thanks for the report, Are those files downloaded? Thumbnails can not be made for cloud only files.

**Comment by DaveFriedel** [comment]
Yes, they are all downloaded. It's partially displaying them as shown in my screenshot.  So it looks like it's trying to do it, but it's getting stuck.  Reloading the app works sometimes too to get more to show up.

**Comment by yaira2** [comment]
Thank you for your feedback, we’re currently tracking this issue in #14817. We’ve also made some improvements that will be included in the next release but more work is needed in this area.
