### ISSUE TITLE
Fix spelling error

### ISSUE THREAD

**Issue by lunathanael** [files-community/Files#14923]
### Description

Under .github/ISSUE_TEMPLATE/code_quality_issue.yml
In the `Gains` category, correct "responsability" to "responsibility".

### Concerned code

  - type: textarea
    attributes:
      label: Gains
      description: What would fixing this code quality issue bring to the source code? 
      value: |
        - eg. A better readability.
        - eg. Uncoupling concepts X and Y.
        - eg. Clarifying the responsibility of class C.

### Gains

Correct spelling

**Comment by 0x5bfa** [comment]
Thanks. Feel free to fix.
