### ISSUE TITLE
Copy To Mve To

### ISSUE THREAD

**Issue by 488GTB** [files-community/Files#14920]
### What feature or improvement do you think would benefit Files?

Can you please add "Copy To" and "Move To" the toolbar.  

### Requirements

- This proposal will accomplish better usability.
- This proposal will accomplish more intuitive interface.

### Files Version

3.2.2.0

### Windows Version

10.0.22631.3155

### Comments

I am using Open-Shell to provide these options, which is less than ideal.

**Comment by yaira2** [comment]
Thank you for your feedback, this isn't the first time this has been requested but as of now we don't have plans to add these to the toolbar. We'll keep tracking for similar feedback, and we might reconsider this in the future.
