### ISSUE TITLE
7 zip bug

### ISSUE THREAD

**Issue by TavenenoX** [files-community/Files#14928]
### Description

when trying to unzip a file with 7zip its says the file has been moved and it doesn't unzip
if i try it with windows explorer it goes normally

### Steps To Reproduce

1 open 7zip
2 drag file to Files folder
3. error message

### Requirements

- e.g. Fix crash that occurs when...
fix bug when unziping with 7zip

### Files Version

3.2.2.0

### Windows Version

10.0.19045.4046

### Log File

[debug.log](https://github.com/files-community/Files/files/14546942/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, this has been fixed in our dev branch and will be available in the next update.
