### ISSUE TITLE
filenme appearance

### ISSUE THREAD

**Issue by Arismac74** [files-community/Files#14927]
### What feature or improvement do you think would benefit Files?

Hi, would be convenient to see the whole filename in list view.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.2.2.0

### Windows Version

10.0.22631.3235

**Comment by Josh65-2201** [comment]
Thanks for the feedback, you can already hover over the file for the full name and some details about it or are you ask to allow changing the width of items in the layout?

**Comment by yaira2** [comment]
Thank you for your feedback, we don't have a solution right now as there aren't any WinUI Grid controls that will allow us to increase the item width of one column without increasing the width of all the other columns, but we'll keep looking. We'll provide an update in #1033 when a solution is found.
