### ISSUE TITLE
Feature: Add archive support for .mrpack

### ISSUE THREAD

**Issue by Tim-Odermatt** [files-community/Files#14938]
### What feature or improvement do you think would benefit Files?

.mrpack file Preview

the same feature as how the .jar preview works. just for a diverant file type.

.mrpack files are renamed .zip files which contain modpacks for the new modpack hosting site modrinth.com.

### Requirements

none

### Files Version

3.2.3

### Windows Version

10.19045.4123

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
Thank you for the feedback, this format will be included in the next release.
