### ISSUE TITLE
Gallery feature

### ISSUE THREAD

**Issue by ajay-mishra7** [files-community/Files#14930]
### What feature or improvement do you think would benefit Files?

Add Gallery option in files just like Gallery in File Explorer. This feature helps us to find all the images that exists on pc.

### Requirements

- Add Gallery to Files 

### Files Version

3.2.6.0

### Windows Version

10.0.22631.3235

**Comment by 0x5bfa** [comment]
Thank you for the feedback.
We’re tracking this in #5058. You can check out there or subscribe from the right sidebar to get further news.
