### ISSUE TITLE
Files is very slow and unresponsive on Windows 10

### ISSUE THREAD

**Issue by unfa** [files-community/Files#14939]
### Description

I've been using Files on and off for a few years now. I haven't been using it as my main file manager on Windows 10 because it's really slow.

Here's a video demonstration:
https://youtu.be/VZT9BjiBS3g

My hardware is Ryzen 3900X, 32G of RAM, and an NVMe SSD. This shouldn't lag as badly as it does.

Native Windows Explorer isn't super snappy either, but it's at least 2x-4x more responsive.

Recently I've done a clean WIndows 10 install and things aren't any faster.
On the same hardware on Arch Linux with KDE5 I don't have any of these issues using Dolphin file manager. Sure, if I'm hammering my drives then it's slow, but I know why and it's my doing. on Windows it's always like that.

Is it just nature of Windows? Or the nature of Files? Or maybe Files is optimized for Windows 11 (which I have no intetion of ever installing on my hardware) and Windows 10 is left by the wayside?

I was hoping that over the years Files would become faster, but it didn't. It crashes less, but often trying to just copy a bunch of files is a hassle, as drag and drop takes seconds to initialize and show what action it will do. Navigating folders keeps me waiting for a couple seconds just to go up and down a directory. Every time.

It feels like I'm running on a crusty HDD with terrible fragmentation and on a Core Duo with 4 GB of RAM.
It's been even worse on an (sneaky freaking SMR) HDD, but recently reinstalling Windows on an NVMe SSD didn't show a noticeable improvement here...

I wonder if anybody else has such issues...

### Steps To Reproduce

This is general issue, so it's hard to provide a step-by-step reproduction guide.

1. Install Windows 10
2. Install Files
3. Use the system
4. Notice how slow it is?

### Requirements

Expected behaviour would be:
1. navigating folders without 1-3 seconds of waiting each time.
2. Switching tabs without ~3 seconds of wait each time
3. Having the UI update mouse over immediatelly, and not with 0.1~0.2 second delay.

### Files Version

Every single one I've tried since 2021

### Windows Version

Edition	Windows 10 Home Version	22H2 Installed on	‎26/‎02/‎2024 OS build	19045.4046 Experience	Windows Feature Experience Pack 1000.19053.1000.0

### Log File

[debug.log](https://github.com/files-community/Files/files/14558367/debug.log)

And if you need more info about my system, here's DxDiag output:
[DxDiag.txt](https://github.com/files-community/Files/files/14558502/DxDiag.txt)

**Comment by yaira2** [comment]
Thank you for your feedback, Files uses WinUI 3 which tends to be a little more resource hungry. There are some framework improvements Microsoft has indicated will help with this in the future, but we'll continue to optimize Files from our end. From your end, you can get the best performance by disabling transparency in Windows Settings (this will help other apps as well) and by turning off the option to show thumbnails (Files > Settings > Folders > Show thumbnails).

To track further progress, please subscribe to #4180.

**Comment by joaofar** [comment]
Yeah, have exactly the same issue as you, it's so slow.... everything takes time, even context menus take so long, it's very frustrating. Also hope you guys manage to fix this, it looks like a really nice file manager.

So it works fine under win11?

**Comment by FuglyShmugly** [comment]
Used it for a day, 32gb ram, 5070 ti, 5700x3d. Windows 11 latest beta. Nice but slow, uninstalled. Not sure why you keep updating it with features when the main thing should be speed, which it lacks for the entire time it exists.

**Comment by foinf** [comment]
It is still a problem. Something is broken deep down because it transcends versions. You can really see this happening if you mount an iso and then unmount it. It just freezes for many many seconds before you can interact with it again.

**Comment by Josh65-2201** [comment]
This isn't a fully fixed issue and performance hasn't gotten worse with updates, see #4180

> Not sure why you keep updating it with features when the main thing should be speed

Speed is being worked on, stopping adding features would not help with it.

**Comment by tomkc** [comment]
At current stage this app is so laggy, it's not an option for quick and effective managing your files.  Tried few times over a span of 3 years, but sorry. This has a responsivness worse than ms teams ...

**Comment by yair100** [comment]
@tomkc did you try the preview version? https://files.community/appinstallers/Files.preview.appinstaller

**Comment by tomkc** [comment]
@yair100  no, maybe i'm gonna give it a try. But i don't know if it's worth tbh. I switched to multi commander and i fear it won't be even close.

**Comment by yair100** [comment]
@tomkc please let us know how it goes. I think you'll like the improvements 🙂
