### ISSUE TITLE
Feature: Translate the “Files" in opening page

### ISSUE THREAD

**Issue by JTFA** [files-community/Files#14931]
### What feature or improvement do you think would benefit Files?

<img width="1009" alt="屏幕截图 2024-03-10 161611" src="https://github.com/files-community/Files/assets/57850248/56e0924e-6404-49eb-91bd-3db947601a61">

### Requirements

Translate the “Files" in opening page or let users customize the content displayed on the opening page

### Files Version

3.2.3.0

### Windows Version

10.0.22631.3235

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Files is the name and names aren't translated
