### ISSUE TITLE
Regarding the issue of SVN status icons not displaying when using Files

### ISSUE THREAD

**Issue by Nronless** [files-community/Files#14944]
### Description

Hello, I'm a devoted user of the Files software. Recently, while using Files, I encountered some issues and would appreciate your assistance and feedback.

Due to the nature of my work, I need to synchronize my work documents to the company's SVN server for immediate archiving. When checking the SVN upload status, I noticed that only folders show a green checkmark (✓) indicating successful synchronization after submission or update, while files such as Word documents or Excel sheets do not display any icons. I attempted to resolve this issue using Google, but ultimately failed. However, when I switched back to the system's default file manager, I found that the status icons were indeed displayed.

I really like using Files, but file synchronization for the company is crucial work for me, and I need to monitor the synchronization status constantly. Therefore, I earnestly request the developers' assistance in resolving this issue. Thank you!

One potential solution is that I encountered a similar issue on a previous computer, where I was advised to modify the ShellIconOverlayIdentifiers related to SVN icon order in the system's registry. At that time, I hadn't yet started using Files, but this method was successful. I wonder if it could be helpful in resolving this issue for you.

I eagerly await your prompt feedback. Thank you!!
![1](https://github.com/files-community/Files/assets/50014024/867ad494-ee6a-4476-bdea-bc2c6605b693)
![2](https://github.com/files-community/Files/assets/50014024/25632e5f-52c2-462c-9ced-9c0ce578c976)

### Steps To Reproduce

1. Open Files.
2. Synchronize the files using SVN to any server.
3. Check the synchronization status (status icons for folders and files).
4. Use the system's default file manager to view the same synchronized folders and files.

### Requirements

I hope to make Files successfully display SVN synchronization status icons.
![3](https://github.com/files-community/Files/assets/50014024/355347f6-08e7-4297-bd7f-2342d3541b5a)

### Files Version

3.2.2.0

### Windows Version

10.0.22631.3235

### Log File

[debug.log](https://github.com/files-community/Files/files/14570312/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by Nronless** [comment]
![image](https://github.com/files-community/Files/assets/50014024/739a891c-4ff8-4ef1-8940-0efaa62b6320)
OMG it works! Thanks a lot!!! Amazing!!!

**Comment by yaira2** [comment]
@Nronless the fix will be included in the next feature release but in the meantime you can use the preview version.
