### ISSUE TITLE
Bug: Incorrect display of icons (maybe charset error)

### ISSUE THREAD

**Issue by vsTianhao** [files-community/Files#14943]
### Description

It's not clear what causes this, it may not be a problem with files, it may be a problem with all UWP programs or all WinUI programs
![{22B1C1C7-8C24-4863-BA29-F846E9269112}](https://github.com/files-community/Files/assets/32083528/c07caadd-228d-4ee0-9827-cb2a17e0e1af)
![image](https://github.com/files-community/Files/assets/32083528/3ebb941e-49e4-435c-9184-24a24d030f5f)

### Steps To Reproduce

No need to do anything, just open the files program and that's it

### Requirements

I use Simplified Chinese language

### Files Version

3.2.6.0

### Windows Version

10.0.19045.4046

### Log File

[debug.log](https://github.com/files-community/Files/files/14566837/debug.log)
It should have nothing to do with this file.

**Comment by vsTianhao** [comment]
I started the OS with Simplified Chinese, but then switched to English, so maybe there's a reason for that, but the font icons for all other programs are fine.

I've installed the WinUI 3 Gallery app from the Microsoft store and found that many of the icons there are also corrupted and incorrect, exactly as I did with this program.
![{D4906076-A1C2-4455-B003-231158A849C2}](https://github.com/files-community/Files/assets/32083528/d4b67465-13a5-473b-90ef-29840adc2388)

**Comment by yaira2** [comment]
Some icons were deprecated by Microsoft and are no longer supported in some regions, if you can send a list of all the places in the app with this issue, I can go through and fix them.

**Comment by yaira2** [comment]
I fixed the "layout" icon in the right click menu, but regarding the ones in the settings dialog, we're already using the updated icons so I don't know what else to do. Considering you're having the same issue in the WinUI 3 Gallery, it's possible it's a platform issue and that WinUI needs to fix the issue from their end.

**Comment by sekai830508** [comment]
@vsTianhao 不好意思，我有一样的问题，请问后来有办法解决了吗，版本是3.7.0.0

**Comment by 0x5bfa** [comment]
Which wrong icons are you seeing?

**Comment by sekai830508** [comment]
@0x5bfa Hi , please refer to the image.
![1](https://github.com/user-attachments/assets/be45edcc-8ec9-4486-8e1e-afa8d076df59)
