### ISSUE TITLE
Lost access to Windows Explorer and Control Panel

### ISSUE THREAD

**Issue by mondotoronto** [files-community/Files#14941]
### Description

I was unhappy with the Files app so I tried to remove it from my system but after I did, I could no longer access WinExplorer or Control Panel (accidentally, I found that I could access Explorer after I scanned something and then saved it - Explorer would pop-up but once I shut down or restarted my PC, it was gone again).

I reinstalled Files so I had some file organizer but I still don't like it; it constantly hangs and settings change on their own.  I have searched for solutions online but none of them have worked.  How can I uninstall Files and regain access to Explorer and Control Panel?

### Steps To Reproduce

1. Install Files app
2. Uninstall Files app
3. Windows Explorer and Control Panel are inaccessible.

### Requirements

- e.g. Fix crash that occurs when...
Windows Explorer and Control Panel are still on my system but almost entirely inaccessible.

### Files Version

3.2.3.0

### Windows Version

10.0.19045.4046

### Log File

Nothing happens when I click on "open log location".

**Comment by Josh65-2201** [comment]
Turn off (if already off turn on then off again) Files settings > Advanced > Set as default and try open Windows File Explorer

**Comment by yaira2** [comment]
@mondotoronto did you by any chance enable the experiential setting to replace File Explorer? If this is the case, you'll need to reinstall Files and toggle the option on & off to revert the registry edits.
![image](https://github.com/files-community/Files/assets/39923744/4d7c7c46-51da-4c5a-ac15-8e0fed871e60)

**Comment by mondotoronto** [comment]
Hi,
I appreciate the quick replies.
The "Set Files as the default file manager" setting has always been off (because of the warning!) and I'm not clear if Josh65 is suggesting that I enable it and then disable it.
I don't want to do anything that will make things worse.
Any further clarification or other suggestions are very welcome.
Thank you.Ron.
    On Monday, March 11, 2024 at 04:02:26 p.m. EDT, Yair ***@***.***> wrote:  
 
 


@mondotoronto did you by any chance enable the experiential setting to replace File Explorer? If this is the case, you'll need to reinstall Files and toggle the option on & off to revert the registry edits.
image.png (view on web)

**Comment by Josh65-2201** [comment]
Also email attachments don't work for uploading images. You will have to click the `View on GitHub` link at the bottom of the email > Copy and paste or click the add attachment button to select the file > Wait until you don't see `uploading` in the text > Click the green comment button.

**Comment by mondotoronto** [comment]
Hello,
This all began quite a while ago and, at the time, I didn't realize there was a forum for Files (it's such a generic name that online searches show too many useless results).
I've attached a screenshot of the error message I receive when I try to enter explorer.exe into the Run function.
For the Control Panel, I don't get any error message; it just doesn't open.
Thanks.    On Monday, March 11, 2024 at 05:30:52 p.m. EDT, Josh65-2201 ***@***.***> wrote:  
 
 


If you haven't ever turned the set as default option on then the issue is probably not from Files. Can you send a screenshot of what error you get when opening them.

**Comment by Josh65-2201** [comment]
Again email attachments don't work. You will have to click the `View on GitHub` link at the bottom of the email > Copy and paste or click the add attachment button to select the file > Wait until you don't see `uploading` in the text > Click the green comment button.

**Comment by mondotoronto** [comment]
Apologies
![image_2024-03-11_175618473](https://github.com/files-community/Files/assets/163040676/80f82787-253b-4515-bfdc-037f058f3973)

**Comment by Josh65-2201** [comment]
Thanks, the error isn't caused by Files, but you can try running the below reg script to restart the explorer path
[UnsetFilesAsDefault.reg.zip](https://github.com/files-community/Files/files/14564921/UnsetFilesAsDefault.reg.zip)

**Comment by mondotoronto** [comment]
Thank YOU!  That fix worked and I can now access both applications.

Now, as an amateur computer user, I am in no position to doubt you, but this problem arose immediately after I uninstalled Files, so I am not convinced that that didn't trigger something.

Added to that, your fix is labelled "Unset Files As Default" and it worked for me.  

I can't say absolutely (I'm 65 years old!) that I didn't enable that setting but it goes against my normal caution when warned about possible negative consequences, so it's difficult for me to imagine why I would ever do that.  At the time, I didn't like the Files app and wouldn't have wanted to make it the default file manager.

But, anyway, I am glad that those old apps have been restored.  Do you think it's best that I just leave Files on my computer or would deleting lead to more problems?

Thanks very much for your time and attention.  It is appreciated.

**Comment by Josh65-2201** [comment]
Glad it worked and you can uninstall Files if you want. Files doesn't do anything by default to the registry and the only way would have been if the set as default option was turned on at some point.

**Comment by mondotoronto** [comment]
Thanks again.
