### ISSUE TITLE
Feature Request: "Select All" Checkbox next to "Name" column in Details Layout

### ISSUE THREAD

**Issue by A-Loot** [files-community/Files#14940]
### What feature or improvement do you think would benefit Files?

Add a "Select All" checkbox next to the "Name" column in the Details Layout.

I know there's already a "select all" button in "Selection options", but the space next to the Name column is currently unused and most programs have a similar checkbox there.

The space I'm talking about:
![image](https://github.com/files-community/Files/assets/105282948/30f881e9-dedf-454d-99ec-d17cc4facfcc)

In Windows Explorer:
![image](https://github.com/files-community/Files/assets/105282948/2e967fae-0bcf-4da3-8d85-31f5fc1eb735)

### Requirements

- Add a checkbox next to the Name column in the Details Layout

### Files Version

3.2.3.0

### Windows Version

10.0.26058.1400

**Comment by yaira2** [comment]
Thank you for your feedback, we're tracking this feature request in #9528. Please add a comment to that issue to be notified when it's resolved.
