### ISSUE TITLE
Code Quality: Fix CA1859 and CA1829

### ISSUE THREAD

**Issue by gumbarros** [files-community/Files#14955]
### Description

.NET 8 introduce this 2 new analyzers to improve performance

https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1829
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1859
### Concerned code

CA1829:
https://github.com/files-community/Files/blob/27ef24943ddf8180d78d89859cbd91cb1038ef1f/src/Files.App/Services/JumpListService.cs#L165

CA1859:
https://github.com/files-community/Files/blob/27ef24943ddf8180d78d89859cbd91cb1038ef1f/src/Files.App/Data/Commands/Manager/ModifiableCommandManager.cs#L28

### Gains

- Better readibility (no useless casting at CA1859 )
- Better performance

### Requirements

- Refactor to the suggestions of the analyzer

### Comments

I created https://github.com/files-community/Files/pull/14951 but it was recused, it has compile errors and do more things, if authorized I can create a new PR

**Comment by yaira2** [comment]
@d2dyno1 @0x5bfa

**Comment by 0x5bfa** [comment]
Sounds good.
