### ISSUE TITLE
Feature: Make the progress bar bold

### ISSUE THREAD

**Issue by jiang2050** [files-community/Files#14959]
### What feature or improvement do you think would benefit Files?

![1](https://github.com/files-community/Files/assets/40513027/c9c87dc9-073a-4d32-8d9d-381e81ccdf82)
![1](https://github.com/files-community/Files/assets/40513027/d723fd97-7d53-42b8-8e5e-b09798d08459)

i hope files can make the disk capacity progress bar bold ,like win10 or win11 UI. 

### Requirements

Make the progress bar bold

### Files Version

3.2.3.0

### Windows Version

10.0.19045.4170

**Comment by jiang2050** [comment]
![2](https://github.com/files-community/Files/assets/40513027/efe14613-2995-4610-94dd-fe8e55f696ca)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, The currently used one is the WinUI standard following made guideline by Microsoft, they have yet to update Windows File Explorer with this. What reason would you want it to be bigger?

**Comment by 0x5bfa** [comment]
We have some plans to do that but it hasn't been decided yet and there's still rooms to be discarded.

@yaira2

**Comment by yaira2** [comment]
@jiang2050 thank you for your feedback, we don't have plans to implement this now but as mentioned, we're exploring other designs and we'll keep this feedback in mind.
