### ISSUE TITLE
Bug: Drag gap between tab bar and windows controls doesn't always happen

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#14958]
### Description

Currently sometimes show like this
![image](https://github.com/files-community/Files/assets/26977075/078e5237-0f9b-4b31-935c-ab48122e7fd3)

### Steps To Reproduce

1. Tested on resolution 1920x1080 and scaling 100%
2. Maximize window
3. Open new tabs until tab bar is full

### Requirements

- Make sure a drag gap is always present between the tabs and window controls

### Files Version

3.2.7.0

### Windows Version

10.0.22621.3155

### Log File

[debug.log](https://github.com/files-community/Files/files/14591229/debug.log)

**Comment by 0x5bfa** [comment]
I can repro.

![image](https://github.com/files-community/Files/assets/62196528/35565e72-b41e-4bce-88b4-cc0a7c78758f)

You can drag there and so you cannot add a new tab by the button, right?

**Comment by yaira2** [comment]
A fix will be included in the next release. Thank you @XTorLukas for your research on this issue and for contributing the fix.
