### ISSUE TITLE
Bug: Sorting by date types in ascending order is backwards (Oldest to newest)

### ISSUE THREAD

**Issue by v-aravind** [files-community/Files#14954]
### Description

Sorting has two elements - type and ascending/decending. When sorting by name, the intuitive order is ascending (A-Z). When sorting by date, the intuitive order is Newest to Oldest, but this is classified as Decending order by date. So if Ascending is selected, and you switch for sorting by name to sorting by date, then the oldest files are shown first, which is not intuitive. It is also the opposite of what happens in windows explorer. Aschending By Date should be Newest First, not Oldest First.

### Steps To Reproduce

1. Sort files by Name - Ascending
2. Sort files by Date

### Requirements

When sorting files by Date - Ascending, they should appear as Newest files first. 

### Files Version

3.2.2.0

### Windows Version

23H2 (22631.3235)

### Log File

[debug.log](https://github.com/files-community/Files/files/14588588/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by marianacarvalho16** [comment]
Hello. I find a way to solve this issue but when i try to open a pr, i get this:
![image](https://github.com/files-community/Files/assets/165893627/d843a341-dd61-4f86-9352-4dab0a612f99)

how do i solve this?

**Comment by Josh65-2201** [comment]
Are you creating a PR with your fork of Files? Selecting the correct branch, main on left, your branch on right

**Comment by marianacarvalho16** [comment]
> Are you creating a PR with your fork of Files? Files main on left, your fork and branch on right

yes

**Comment by marianalcar** [comment]
> Are you creating a PR with your fork of Files? Files main on left, your fork and branch on right

I was using the wrong account. I changed accounts and managed to do the pr

**Comment by Josh65-2201** [comment]
Great, If you continue to help work on Files please also only do ready to build listed issues https://github.com/orgs/files-community/projects/3/views/2

**Comment by 0x5bfa** [comment]
@yaira2 Waiting for approval.

**Comment by hishitetsu** [comment]
Explorer is also sorted from oldest to newest in ascending order as shown in this screenshot. (Sorry for Japanese, 更新日時 means update date and 昇順 means ascending.)
So, the behavior of Files is the same as Explorer, and I don't think it needs to be changed.

![スクリーンショット 2024-04-07 095453](https://github.com/files-community/Files/assets/66369541/c6cc254b-3471-4cd8-89b3-84536bdc9118)
