### ISSUE TITLE
PB instead of GB

### ISSUE THREAD

**Issue by star43able** [files-community/Files#14967]
### Description

while transfering 58gb of data it showed petabyte(PB) on one side on the other GB

### Steps To Reproduce

1) choose a file to copy
2) copy it to onedrive/Maybe any?
3)check status and you will see PB transferred out of GB

### Requirements

- e.g. Fix crash that occurs when...
i expect it to match how large of a file your transferring 

### Files Version

3.2.3.0

### Windows Version

1000.22687.1000.0

### Log File

[debug.log](https://github.com/files-community/Files/files/14622091/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #13891 . You can check there or click subscribe in the right sidebar for updates.
