### ISSUE TITLE
Bug: ComboBox list shift to the right when clicked on

### ISSUE THREAD

**Issue by TheChilledBuffalo** [files-community/Files#14965]
### Description

When clicking on a ComboBox list (list of selectable items) in Settings, the list moves away from under the cursor.

https://github.com/files-community/Files/assets/87632612/f9ab3841-c470-4430-a10c-33a00bfc5cb2

### Steps To Reproduce

1. Open Settings
2. Click on any ComboBox 
3. List moves to the right and is not at the same location as it was before.

### Requirements

Would be better if the list stays under the mouse cursor on being clicked.

### Files Version

Latest dev build (3.2.7.0)

### Windows Version

22631.3296

### Log File

[debug.log](https://github.com/files-community/Files/files/14611969/debug.log)

**Comment by TheChilledBuffalo** [comment]
I have found that setting a fixed `Width` or `MinWidth` for the `ComboBox` -es can solve this issue. Let me know if you guys think it is a viable option, and I'll make a PR for it.

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board. Please wait until the status is `Ready to build` on the right sidebar of this issue before opening a PR.

**Comment by TheChilledBuffalo** [comment]
Got it. I'll wait, Thanks!

**Comment by TheChilledBuffalo** [comment]
Yup I figured that out. So I can start working on this, now that its in "Ready to build" right?

**Comment by yaira2** [comment]
Yes, thank you! It might even be worth creating a custom resource dictionary for the ComboBox controls in settings so that we don't have to manually set this on every single instance.

**Comment by 0x5bfa** [comment]
This should be done by WinUI. I'll make a ticket for this in the repo and wait for a response.

**Comment by 0x5bfa** [comment]
Created: https://github.com/microsoft/microsoft-ui-xaml/issues/9567

**Comment by 0x5bfa** [comment]
Please thumb up and/or comment on the issue...
