### ISSUE TITLE
External Link not pre-select a file

### ISSUE THREAD

**Issue by Bolhoman** [files-community/Files#14969]
### Description

To simulate the problem, open Chrome, in the downloads list there is a button called "view in folder" when clicked, files does not select the file. This does not happen with Windows Explorer. Any program that pre-selects a file in a folder does not work with the files.

### Steps To Reproduce

Open Chrome
Go to Downloads
on the list, click on "view in folder"
link is slow, and not select the ffile.

### Requirements

Occurs when SELECTING files via external program links

### Files Version

3.2.4.0

### Windows Version

10.0.22621.3007

### Log File

Nao ha

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #14429 . You can check there or click subscribe in the right sidebar for updates.
