### ISSUE TITLE
Files Download Page

### ISSUE THREAD

**Issue by Squirrel2024** [files-community/Files#14968]
### Description

Unable to access Microsoft Store from the link. Selects new page and comes up with the About error. Also sound the classic installer link is non-selectable. It is highlighted as hyperlink but does not permit selection. Using the latest Windows 10 update on OS and the latest DuckDuckGo Browser.

### Steps To Reproduce

1. Select MS Store download link
2. New tab does not load page.
3. Attempt to click classic installer but nothing happens. 

### Requirements

- e.g. Fix crash that occurs when...
Fix the hyperlinks so that the MS Store link goes to the MS Store for Files download or requests access to the MS Store App.
Fix the hyperlink to classic installer so that it can be selected and the download starts.

### Files Version

3.2.3

### Windows Version

Edition	Windows 10 Home Version	22H2 Installed on	‎20/‎03/‎2021 OS build	19045.4170 Experience	Windows Feature Experience Pack 1000.19054.1000.0

### Log File

No log file

**Comment by 0x5bfa** [comment]
What the link did you access?

You can download Files from our website https://files.community/download

**Comment by yaira2** [comment]
The Store link will only work if you have the Microsoft Store installed on your device. It's also possible that this is an issue with the Duck Duck Go browser, we recommend trying Chrome or Edge and if it's still an issue, please let us know and we can try to provide further assistance.
