### ISSUE TITLE
Map network drives and show network drives

### ISSUE THREAD

**Issue by zhaoyycrow** [files-community/Files#1496]
I have several network drives mapped to my file explorer, but they don't show up in Files UWP. I also couldn't find a way to map new network drives in Files UWP (I tried right click and looked into settings but couldn't find any clue). 

Overall very great job! I love the neat UI. Thank you!

**Comment by zhaoyycrow** [comment]
Updates: network drives show up if they are connected. Still can't establish new connections.

**Comment by gave92** [comment]
Merging with#1593
