### ISSUE TITLE
Open Folder on hover

### ISSUE THREAD

**Issue by mikex2023** [files-community/Files#14960]
### Description

it is not clear to me when the desired folder is selected when hovering under the mouse pointer. it is obscured for me by the display of the information bar. furthermore, due to my poor eyesight, the time is too short before the folder opens and i can actually see which one is active.
unfortunately, i can't find a way to switch off the feature or to adjust the time for automatic opening.
as nice as files is, that's one reason why i don't want to work with it anymore. it's too uncertain where files might be moved or too tedious to switch back to the directory again and again.

### Steps To Reproduce

select a file and move hover an folder

### Requirements

there should be an option to deactivate the function, or it should also be possible to adjust the time when the folder opens itselfhere should be an option to deactivate the function, or it should also be possible to adjust the time when the folder opens itself

### Files Version

3.2.3.0

### Windows Version

10.0.19045.4046

### Log File

[debug.log](https://github.com/files-community/Files/files/14599887/debug.log)

**Comment by yaira2** [comment]
@mikex2023 can you clarify if you're talking about when drag and droping items?

**Comment by mikex2023** [comment]
@yaira2 yes exactly

**Comment by yaira2** [comment]
Thank you for the feedback, an option to disable this feature isn’t available but it should be fairly easy to add if there is enough interest. Can you open a new issue using the feature request template so we can this to our project board?
