### ISSUE TITLE
Bug: Seer preview should close when selecting a different file via the mouse

### ISSUE THREAD

**Issue by Nronless** [files-community/Files#14966]
### Description

Seer has a quick preview feature that I often use in my work. Its function is as follows: when any file/folder in the file manager is selected and the spacebar is pressed, it allows browsing the contents without directly opening it. This is particularly convenient for someone like me who works with numerous Word and Excel documents.

Files is my favorite file manager. However, when combining the two, there's a rather troublesome issue: once the quick preview feature is activated for the first time by pressing the spacebar, selecting any file thereafter or returning to the previous level folder will automatically invoke the quick preview feature, unless Seer is closed in the background to stop it. It's as if once the spacebar is pressed for the first time, every subsequent selection of any file/folder with the mouse automatically adds the quick preview feature corresponding to the spacebar. This is quite frustrating. Both applications are very useful, and I am reluctant to give up either.

Through testing, this issue does not occur with Seer and the default file manager of Windows. Currently, I am not sure whether the issue lies with Files or Seer, so I have submitted feedback for both applications, hoping to get help from the developers. I am very grateful for the excellent software you have developed and hope it can be further improved!

### Steps To Reproduce

1. When Seer and Files are running, but Seer has not yet been used for the first time (before the first press of the spacebar), clicking to select any file with the mouse does not present any issues.

[2024-03-15 17-22-13.mkv.zip](https://github.com/files-community/Files/files/14613585/2024-03-15.17-22-13.mkv.zip)

2. When Seer is running, pressing the spacebar on any file to use Seer's quick preview feature will lead to the automatic invocation of the quick preview feature upon any subsequent mouse selection of any file. It's as though every mouse click to select a file automatically presses the spacebar.

[2024-03-15 17-23-34.mkv.zip](https://github.com/files-community/Files/files/14613586/2024-03-15.17-23-34.mkv.zip)

### Requirements

 hope to prevent the automatic invocation of Seer's quick preview feature when using Files and Seer together, so that the feature is only used when I actively press the spacebar according to my needs.

### Files Version

3.2.7.0

### Windows Version

10.0.22631.3296

### Log File

[debug.log](https://github.com/files-community/Files/files/14613628/debug.log)

**Comment by yaira2** [comment]
What happens if you press the space bar again?

**Comment by Nronless** [comment]
> What happens if you press the space bar again?

The Quick Preview Window will disappear.

**Comment by ccseer** [comment]
@yaira2  hi, Seer hasn't been updated since last June.

**Comment by ccseer** [comment]
Let me know if there is anything I can do, @yaira2

**Comment by yaira2** [comment]
> > What happens if you press the space bar again?
> 
> The Quick Preview Window will disappear.

Is this a good workaround for now?

**Comment by yaira2** [comment]
> Let me know if there is anything I can do, @yaira2

@ccseer I think the fix can be from our side but if pressing space does the trick, I think it might be a good workaround for now.

**Comment by Nronless** [comment]
> > > What happens if you press the space bar again?
> > 
> > 
> > The Quick Preview Window will disappear.
> 
> Is this a good workaround for now?

I've updated to the latest version of Files, which is 3.3.0.0, and It appears to still exist.:'(

**Comment by yaira2** [comment]
We haven't made any changes to fix this. Our current intention is for users to use `space` or `esc` but we'll keep this on our project board as it's reasonable feedback.

**Comment by Nronless** [comment]
> We haven't made any changes to fix this. Our current intention is for users to use `space` or `esc` but we'll keep this on our project board as it's reasonable feedback.

OK! Thanks for your reply and care!!  :)

**Comment by ccseer** [comment]
wait, I guess we need more info. 
`Seer preview should close when selecting a different file via the mouse` is expected. And if user doesn't like it, there is an option to turn it off in Seer's Settings.

**Comment by ccseer** [comment]
@Nronless would you please hlep comfirm

**Comment by Nronless** [comment]
> wait, I guess we need more info. `Seer preview should close when selecting a different file via the mouse` is expected. And if user doesn't like it, there is an option to turn it off in Seer's Settings.

I've looked through Seer's setting, but counldn't find this item anyhow. Maybe it's because of different translation? Let me show u all the setting windows to locate it.

![image](https://github.com/files-community/Files/assets/50014024/5d1c89e5-f408-4dce-8157-66c41cf0cb7b)

![image](https://github.com/files-community/Files/assets/50014024/2297df16-fddf-4303-91a7-a8bd27c079e8)

![image](https://github.com/files-community/Files/assets/50014024/b8f32c06-8f27-4d18-835a-61066a2ff365)

![image](https://github.com/files-community/Files/assets/50014024/289ad1ea-651d-4788-91a2-838597bb6de0)

![image](https://github.com/files-community/Files/assets/50014024/c11b7efe-75c7-4510-9538-9eb703eb7327)

![image](https://github.com/files-community/Files/assets/50014024/86a96671-5e7c-498c-8b48-564057da3338)

![image](https://github.com/files-community/Files/assets/50014024/b918caec-686b-4608-bdfb-53aa83422e2a)

**Comment by ccseer** [comment]
@Nronless  The sixth tab, the second group `Others`, then `Track selected file in Explorer`.

**Comment by ccseer** [comment]
![image](https://github.com/files-community/Files/assets/15963166/63e37e36-4a86-4197-8bb8-f075ab56ec15)

**Comment by ccseer** [comment]
@Nronless  you can close the issue if it's solved.

**Comment by Nronless** [comment]
> ![image](https://private-user-images.githubusercontent.com/15963166/314402618-63e37e36-4a86-4197-8bb8-f075ab56ec15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5ODQ0MjIsIm5iZiI6MTcxMDk4NDEyMiwicGF0aCI6Ii8xNTk2MzE2Ni8zMTQ0MDI2MTgtNjNlMzdlMzYtNGE4Ni00MTk3LThiYjgtZjA3NWFiNTZlYzE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDAxMjIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MmU1ODBlNTgxYWU3NTYyYjU2YjA1MjFiNGE3NTBkYzgyOWNiY2NlOWJiOTFhZTFkZGFkYzlhYTQyMDkzYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._vo2SnAqUmA-ws-svQtUMxtQ9b4qYMCMA0eQstRqs50)

I've tried turning off this option, but still exists the same issue.

**Comment by yaira2** [comment]
@ccseer do you have docs on how we can detect that setting?

**Comment by ccseer** [comment]
yes, it has a priority

-  UWP
    1. %USERPROFILE%/Documents/Seer/uwp.ini
    2. %USERPROFILE%/appdata/Local/Corey/Seer/uwp.ini

- Win32:  
    1. %USERPROFILE%/Documents/Seer/config.ini
    2. **REG**:   "\\HKEY_CURRENT_USER\\Software\\Corey\\Seer"


The key is: 
`general` - `tracking_file`

**Comment by yaira2** [comment]
> %USERPROFILE%/appdata/Local/Corey/Seer/uwp.ini

This path doesn't seem to work

**Comment by ccseer** [comment]
the ini files under Documents are created by user. 
in some rare cases, the default path doesn't work, so I provided a solution for these user to have a new Settings path

**Comment by yaira2** [comment]
@Nronless this will be included in the next release.
