### ISSUE TITLE
Icons are very low resulation in 2k monitor. maybe vectorize them? 

### ISSUE THREAD

**Issue by RakibRyan** [files-community/Files#14963]
### What feature or improvement do you think would benefit Files?

(and no these photos aren't related. these are stock. here only to show the diffence)

![Screenshot (2)](https://github.com/files-community/Files/assets/85598032/d4e7d8a0-06d8-4342-a251-1b3ab7645474)

### Requirements

would cut out the ugliness of the file manager.

### Files Version

3.2.2.0

### Windows Version

10.0.22631.3296

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by RakibRyan** [comment]
From the testing in preview version it seems to be less noticable but still there. It seems to occure when i'm opening a folder with large amount of big files for the first time/ when i switch a drive and open folders. sometimes the problem occurs, sometimes it doesn't seem to occurr. when this occurs if i go back and open again it doesn't occur.

**Comment by yaira2** [comment]
Can you see what happens if you set a default layout in settings?

**Comment by RakibRyan** [comment]
still noticable low rez icon popping.

**Comment by yaira2** [comment]
@RakibRyan are sure you tested in the preview version? The preview version has the blue icon.

**Comment by RakibRyan** [comment]
yes I'm sure. literally downloaded this https://github.com/files-community/Files/issues/14963#issuecomment-1998322401

**Comment by yaira2** [comment]
Can you send a screenshot? Thanks!

**Comment by RakibRyan** [comment]
If you look at the bottom you can see I do have the preview version open.


![Screenshot (18)](https://github.com/files-community/Files/assets/85598032/0f0377d2-6162-4107-833c-7940155efbbc)

**Comment by yaira2** [comment]
Thank you for checking, the only time those icons are supposed to be blurry is when switching from a smaller layout to a larger layout. In that case the icons need a moment to reload so the lower resolution icon might be briefly visible.

**Comment by yaira2** [comment]
Can you do us a favor and see what happens if you try the following
1. Clear the Windows Thumbnail cache
2. Update the stable version of Files to v3.3
3. Set the default layout in Files to Grid and turn off the option to sync preferences across folders

![image](https://github.com/files-community/Files/assets/39923744/be69a01c-9b21-4d9b-9e67-3b1372a40dd7)

**Comment by BiosNod** [comment]
![2024-03-27 132844](https://github.com/files-community/Files/assets/16207244/02bba04a-2fc8-4a8f-8cdd-44336ffc57f2)
You can really see this for a while, especially if the computer is busy with something else

**Comment by yaira2** [comment]
If Windows doesn't have enough available resources then that can be another reason. What is your devices specifications?

**Comment by Josh65-2201** [comment]
@RakibRyan Can you provide the information requested in the last comment

**Comment by RakibRyan** [comment]
I'm sorry I was on vacation.@yaira2 doing what you said didn't show the low rez icons. However the load times seem to be significantly longer. 

I have a i5-11400, 32 GB ram and boot drive is samsung 980 pro. And the files were split between hp ex900 ssd and some sata ssd and hard drives.

**Comment by Josh65-2201** [comment]
Clearing the cache would make it take longer as it has to remake them.

**Comment by yaira2** [comment]
> I'm sorry I was on vacation. @yaira2 doing what you said didn't show the low rez icons. However the load times seem to be significantly longer.
> 
> I have a i5-11400, 32 GB ram and boot drive is samsung 980 pro. And the files were split between hp ex900 ssd and some sata ssd and hard drives.

Can you clarify if this resolved the resolution issue?

**Comment by RakibRyan** [comment]
yes, that fixed it.

**Comment by yaira2** [comment]
Thank you!
