### ISSUE TITLE
Bug: Files opens behind all other open apps on first start

### ISSUE THREAD

**Issue by jonesy-b-dev** [files-community/Files#14978]
### Description

WHen i open files for the first time it opens begind all other open apps. This is annoying and requires an extra click to open the app.

### Steps To Reproduce

1. Open files

### Requirements

Files should be opened in front of the other open windows like any other app does.

### Files Version

3.2.3.0

### Windows Version

10.0.23585.1001

### Log File

[debug.log](https://github.com/files-community/Files/files/14627598/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by jonesy-b-dev** [comment]
Yes it is!

**Comment by Josh65-2201** [comment]
Thanks for checking, how are you opening Files and do you have Files settings > Advanced > Set as default enabled?

**Comment by jonesy-b-dev** [comment]
Often im opening through the taskbar, but even when another app opens files it goes to the background. 
And yes `Set as default` is on

**Comment by soredake** [comment]
Same problem with other software:
https://github.com/M2Team/NanaZip/issues/86
https://github.com/microsoft/terminal/issues/6611

**Comment by jonesy-b-dev** [comment]
Personally don`t have the issue in terminal

**Comment by sebibasti0815** [comment]
Same problem here, but not only on first start. The app (window) opens in the background (behind all other windows from different apps) if I let files stay running after closing the window. The window should be pushed to the front, when I open Files.

**Comment by 0x5bfa** [comment]
Thought I fixed this issue.
It's interesting that the app opens behind the all other apps.

**Comment by sebibasti0815** [comment]
I "solved" the problem with adding 

`Win32Helper.BringToForegroundEx(new HWND(this.WindowHandle));`

to MainWindow.xaml.cs - InitializeApplicationAsync at the end:

<code>if (!this.AppWindow.IsVisible) {
			// When resuming the cached instance
			this.AppWindow.Show();
			Activate();
		}
		Win32Helper.BringToForegroundEx(new HWND(this.WindowHandle)); // here
		if (Windows.Win32.PInvoke.IsIconic(new HWND(this.WindowHandle)))
			Instance.Restore(); // Restore window if minimized
</code>

Sure not perfect, but it works for now (as long as a developer has time to look into it).

**Comment by 0x5bfa** [comment]
Yeah I made that helper.
Could you open a PR for the fix?

**Comment by jonesy-b-dev** [comment]
I also still struggle with this issue, it was fixed in the beta build I tried but now it's back again
