### ISSUE TITLE
Code Quality: `FileLogger` should send logs to a `BackgroundService`

### ISSUE THREAD

**Issue by gumbarros** [files-community/Files#14979]
### Description

[FileLogger](https://github.com/files-community/Files/blob/main/src/Files.Shared/Utils/Logger/FileLogger.cs) should send logs to a `BackgroundService` because `ILogger` is not meant to do IO operations.

Related issue:
https://github.com/dotnet/extensions/issues/2141

Related discussion:
https://github.com/dotnet/runtime/discussions/87949

### Concerned code
https://github.com/files-community/Files/blob/39c2f9cb4ebf16c6ad21f1737672b4fac829eae4/src/Files.Shared/Utils/Logger/FileLogger.cs

### Gains

- Better performance, logging would not block the app thread writing to the file
- Separations of concerns, `ILogger` is meant just to log the information, another class needs to do the heavy job

### Requirements

- Removing the IO operations from `ILogger`
- Create a `BackgroundService` to run the IO operations requested by a buffer

### Comments

Example `FileLogger` implementation:
https://github.com/JJConsulting/JJMasterData/blob/main/src/Commons/Logging/File/FileLogger.cs

Example `FileLogger` background service:
https://github.com/JJConsulting/JJMasterData/blob/main/src/Commons/Logging/File/FileLoggerBackgroundService.cs

**Comment by gumbarros** [comment]
I just saw my logs and the source code and the application barely makes use of `ILogger`, just for a few exceptions and some places. My issue makes more sense if it's a app with lots of logs. If you think it's not a priority, feel free to close the issue.

**Comment by yaira2** [comment]
I'm fine either way. Fyi @0x5bfa

**Comment by 0x5bfa** [comment]
I don't know about logging in Files.
@d2dyno1 what do you think?

**Comment by yaira2** [comment]
@gumbarros let's keep it as is for now. However, if we start to use the logger more, we should come back to this proposal.
