### ISSUE TITLE
Can't access Recent folder

### ISSUE THREAD

**Issue by QiTianzu** [files-community/Files#14972]
### Description

The Recent folder cannot be accessed in this application. Whether accessing from Favorites, Quick access or drive path, it says "Access Denied You don't have permission to access this folder". However, it is accessible in Windows File Explorer and Directory Opus.

![Screenshot 2024-03-17 135709](https://github.com/files-community/Files/assets/50047003/8996e047-3550-49a5-b696-b05daa85544e)

### Steps To Reproduce

Open Files application and just try to open Recent folder.

### Requirements

Access the Recent folder just like Windows File Explorer.

### Files Version

3.2.4.0

### Windows Version

10.0.19045.4170

### Log File

[debug.log](https://github.com/files-community/Files/files/14626196/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, this is fixed in the preview version (if you want to use it https://files.community/download) and will be available for next release
