### ISSUE TITLE
Can not drag-n-drop to open files in Corel applications (CorelDRAW, Corel PhotoPaint)

### ISSUE THREAD

**Issue by Zusurs** [files-community/Files#14977]
### Description

In the earlier (v2) versions of Files it was possible to drag-and-drop files (images, PDFs, etc.) from Files explorer in to the Corel applications to import them. For whatever reason it's not working anymore in Files v3 - trying to drag the image in to the Corel workspace leads to cursor pointer changing over to "Unavailable".

_A quick sidenote - Corel is the second most popular commercial graphic and vector editing software vendor in the world after Adobe Photoshop/Illustrator, used by millions of designers, artists, architects and engineers across the world._

### Steps To Reproduce

1. Open any folder containing valid images/PDFs in Files explorer.
2. Try to drag any applicable file over to any Corel application.
3. Instead of importing the file like it used before upgrading to Files v3, cursor changes to "Unavailable" icon and action is not possible.

### Requirements

Drag-n-drop should work as it did in Files v2.

### Files Version

3.2.2.0

### Windows Version

23H2 (OS build 22631.3155)

### Log File

---

**Comment by Josh65-2201** [comment]
Thanks for the report, We're tracking this in #11735. You can check there or click subscribe in the right sidebar for updates.
