### ISSUE TITLE
Feature: Show image resolution on hover information

### ISSUE THREAD

**Issue by kemar-christie** [files-community/Files#14975]
### What feature or improvement do you think would benefit Files?

Would love it if you added the feature in the original file explorer where when you hover over photos it shows the photo's dimensions. That could really come in handy. instead of going into the properties menu.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.2.4.0

### Windows Version

Windows 11 Pro 22631.3296

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by kemar-christie** [comment]
Your welcome thats the only issue i have. Otherwise this app is perfect keep it up. I hope you keep it for even windows 12 and onwards even tho we wont get windows 12 for now🤣. Great work i should be going into app development as well🔥

**Comment by yaira2** [comment]
@kemar-christie this feature will be included in the next release (v3.5).

**Comment by kemar-christie** [comment]
Noted with thanks

Kemar Christie
K.CHRISTIE
Email: ***@***.***
