### ISSUE TITLE
Search results can not be clicked if using Column layout

### ISSUE THREAD

**Issue by Zusurs** [files-community/Files#14973]
### Description

As the title says - if Files explorer is used in Column view mode, and then something is typed in the Search field, results that shows up are not clickable and doesn't open. Also - it's impossible to change the ison size in the search results view - neither the view menu buttons nor _Ctrl + scrollwheel_ or the _Ctrl + plus/minus_ combination works.

### Steps To Reproduce

1. Open Files explorer, navigate to any folder.
2. Change the view to Column layout.
3. Type something in Search field, and press Enter key, so that search result files are shown.
4. Try to double-click on any of the found files to open them - nothing happens. Also single-clicking doesn't show their preview in the Right-hand pane.

### Requirements

Files shown in search results should be openable by double-clicking, preview icon sizes should be changing when using the View menu, right-hand preview pane should show the selected file from search results. None of this works if initial layout is set to Column view.

### Files Version

3.2.2.0

### Windows Version

23H2 (OS build 22631.3155)

### Log File

[debug.log](https://github.com/files-community/Files/files/14627165/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #13311 . You can check there or click subscribe in the right sidebar for updates.
