### ISSUE TITLE
Right Click  Move to

### ISSUE THREAD

**Issue by meemore** [files-community/Files#14980]
### What feature or improvement do you think would benefit Files?

Right Click  Move to option needed 
![Screenshot_1](https://github.com/files-community/Files/assets/124497263/828e4fa0-3d06-42cb-87cf-5aa0afb8d802)

### Requirements

Please add this feature, to right click on a file or folder..   Sent to  and Move to

### Files Version

3.2.7.0

### Windows Version

10.0.22621.3296

**Comment by yaira2** [comment]
Thank you for your feedback, this isn't the first time this has been requested but as of now we don't have plans to add "move to" to the context menu. We'll keep tracking for similar feedback, and we might reconsider this in the future.
