### ISSUE TITLE
Ability to create/remove tags in the context window

### ISSUE THREAD

**Issue by LastuvkaLukas** [files-community/Files#14981]
### This feature will allow users to add and remove tags directly from the text box they are working in.

![image](https://github.com/files-community/Files/assets/84145589/1965490f-cf79-4669-8674-23cd48bf557b)

This feature would bring increased flexibility and speed in organizing and tagging content, making it easier for users to identify, locate, and manage information within their application or environment.

### Requirements

- Adding a tag could be done by simply clicking on the "Add Tag" button that would appear next to the text box.
- Users could also simply remove a tag by clicking the remove icon next to the tag, where the tag would be removed wherever it was used.

### Files Version

3.2.2.0

### Windows Version

10.0.22631.3296

**Comment by yaira2** [comment]
Thank you for your feedback. The ability to edit tags directly from the menu isn't a usual pattern but the idea behind this request is something we're thinking about and discussing in #12146. Please add a comment or click the subscribe button in that issue to be notified when it's implemented.
