### ISSUE TITLE
Can't drag the window when in Settings page

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#1498]
App version: 0.12.1
OS Version: Windows 10 Insider Preview 20170.100

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran Can you please add details like the app version

**Comment by XPoppyX** [comment]
This happens to me when I open the settings, close and reopen, and then I can no longer drag the window

**Comment by generalguy41** [comment]
This is still present in 0.14.0.0
