### ISSUE TITLE
OpenHashTab stuck

### ISSUE THREAD

**Issue by BiosNod** [files-community/Files#14985]
### What feature or improvement do you think would benefit Files?

I use Openhashtab to compare hashes for multiple files (https://github.com/namazo/openhashtab.git), in Windows 10 22H2 19045.3930 in Old Explorer all OK, but if I use it from the context menu of FilesApp I can't close OpenHashTab window.

I know that the FilesApp already have the ability to hash files in properties, but I can’t simultaneously calculate hashes for multiple files - so I still use Openhashtab and do it using context menu -> hashes.

How to reproduce:
1. Install OpenHashTab (https://github.com/namazo/openhashtab.git)
2. Select 1 or multiple files
3. Open context menu (right click)
4. Click "Hashes"
5. Hashes will be calculated but... Window can't be closed after this action

### Requirements

- Fix subwindows from another programs

### Files Version

3.2.2.0

### Windows Version

10.0.19045.3930

**Comment by yaira2** [comment]
Thank you for your feedback, this was reported earlier but it seems to be an issue in OpenHashTab and can't be fixed from Files. We suggest reporting this to the OpenHashTab developer. (https://github.com/files-community/Files/issues/12550#issuecomment-1740090182)

**Comment by yaira2** [comment]
> but I can’t simultaneously calculate hashes for multiple files

This is a good idea, can you please open a feature request so can add this to our todo list?

**Comment by BiosNod** [comment]
> This is a good idea, can you please open a feature request so can add this to our todo list?

Yes, here - https://github.com/files-community/Files/issues/14987
Sorry for duplicate, I searched using "Open issues" filter
