### ISSUE TITLE
Bug: `filestags.json` doesn't export probably 

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#14995]
### Description

The exported file is missing the line `"FileTagList": [` and the closing bracket at the bottom which stops it from importing and resets.

### Steps To Reproduce

1. Create a tag
2. Export from Files settings > Advanced > Export
3. Import settings
4. Restart Files
5. See the created tag is missing

### Requirements

- Fix file formatting for export zip

### Files Version

3.3.0.0

### Windows Version

10.0.22621.3155

### Log File

*

**Comment by Arnav-2004** [comment]
Hi @Josh65-2201, I would like to work on this issue. I found out that the `ExportSettings` method within the `FileTagsSettingsService` class is missing `"FileTagList"` line and the closing bracket in the exported JSON data.

**Comment by Josh65-2201** [comment]
Thanks, please open a PR when ready and link it to this issue
