### ISSUE TITLE
 New menu display issue in right-click menu  New menu display issue in right-click menu

### ISSUE THREAD

**Issue by akschy** [files-community/Files#14992]
### Description

![图片](https://github.com/files-community/Files/assets/44605406/b210b8d4-59b2-476f-954b-12aac9156ada)
I have customized a typedown project here, which is a software from Microsoft Store and the corresponding file format is markdown

### Steps To Reproduce

1. Use contextMenu Manager to customize the new menu and add the option to create a new markdown file
2. Right click in the directory

### Requirements

- e.g. Fix crash that occurs when...
Display as new typedown file

### Files Version

3.3.0.0

### Windows Version

22631.3296

### Log File

no

**Comment by Josh65-2201** [comment]
Thanks for the report, What are you expecting to happen?

**Comment by yaira2** [comment]
@akschy can you clarify the expected behavior and send a screenshot of the same menu in File Explorer?

**Comment by akschy** [comment]
> @akschy can you clarify the expected behavior and send a screenshot of the same menu in File Explorer?

Sorry, something happened recently and I didn't keep paying attention to this matter. This is the normal display in Microsoft's official resource manager.
![图片](https://github.com/files-community/Files/assets/44605406/0851a3f5-197b-4cb9-8185-b6c51f376a68)

**Comment by 0x5bfa** [comment]
Can you re-install?
And can do Setting > About > Open log location and go back one folder > go to extensions folder > take a screenshot of contents > send us.

**Comment by yaira2** [comment]
@akschy

**Comment by Josh65-2201** [comment]
Is this still an issue in 3.7.11?

**Comment by 0x5bfa** [comment]
Btw we enumerate registry entries that match ShellNew entry but there seems to be an COM interface to get all of them at once (D969A300-E7FF-11d0-A93B-00A0C90F2719) and we can use this via IContextMenu. Probably this way would solve localization issues and some other things. Just fyi for someone would like to look into.
