### ISSUE TITLE
Uploading files progress bar 

### ISSUE THREAD

**Issue by svatitel** [files-community/Files#14998]
### What feature or improvement do you think would benefit Files?

Kind of progress bar of uploading files to cloud storage like default windows explorer has.
![Screenshot 2024-03-19 175943](https://github.com/files-community/Files/assets/130915575/2d2c7260-11d0-4cd9-b073-d0e8066ae262)

### Requirements

Sometimes I can see that my uploading stuck on some file. I go to Files and see that some files are being uploaded but which ones exactly I don't see. I'd like to see progress bar under file's name, so I can see which files are being uploaded right now.

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3296

**Comment by yaira2** [comment]
Thank you for your feedback, can you confirm if this is the same as #8821 but in regard to uploading?

**Comment by 0x5bfa** [comment]
We are tracking this in that issue then.

**Comment by yaira2** [comment]
> Yes, the same.

Thank you for the reply, you can add a comment or click subscribe on that issue to be notified of further updates.
