### ISSUE TITLE
Poor performance in Release mode

### ISSUE THREAD

**Issue by AliElSaleh** [files-community/Files#14994]
### Description

Compared to the native Windows File Explorer, Files seems to stutter when scrolling through a list of files (sometimes the list goes invisible as you scroll fast enough and displaying an empty icon, signaling that it's loading something, which never appears to happen in the native file explorer). See video attached

https://github.com/files-community/Files/assets/19608222/10ea628a-52a0-4ac2-9920-7f7ef2db17bd

### Steps To Reproduce

1. Open up the Visual Studio Solution
2. Set configuration to Release mode
3. Hit Launch Machine
4. Then open up the native file explorer

Finally, compare and contrast with the performance of native Windows File Explorer vs Files

### Requirements

Silky smooth scrolling experience

### Files Version

3.3.0.0

### Windows Version

10.0.22621.2134

### Log File

The log file is not really needed, since it's more of a performance/visual bug. But i'll upload it here anyway. Note that what you see in the log file is not related to the performance issue. Since this field was mandatory i need to upload one
[debug.log](https://github.com/files-community/Files/files/14650579/debug.log)

**Comment by AliElSaleh** [comment]
I have not, let me give that a try though

**Comment by AliElSaleh** [comment]
Unfortunately the stable release version from that download page is not any better, it seems to have the same performance issues as the Release VS dev version. See video attached

https://github.com/files-community/Files/assets/19608222/6a8cbe23-5d6b-41e4-afa9-809dca0730f9

**Comment by Josh65-2201** [comment]
Yes the icon loading will be the same in any version, as I said above this will be improved where possible over time. The window movement however shouldn't be laggy.

**Comment by AliElSaleh** [comment]
Ok cool. Thats good. I am just confused as to why you've marked this issue as closed. Shouldn't we raise this issue up or maybe perhaps reclass this label under a new one called "performance-bugs"

**Comment by Josh65-2201** [comment]
We track them in #4180. but since this is also obvious an issue it doesn't need to be tracked as a separate issue

**Comment by yaira2** [comment]
There are two things going on here
1. Files loads thumbnails as they are scrolled into the view port whereas File Explorer loads everything at once.
2. WinUI isn't as performant as the frameworks File Explorer uses, Microsoft is working on improving this but that's another reason why performance is a little worse when quickly scrolling large lists.

**Comment by AliElSaleh** [comment]
I see. Do you guys have some ideas on this will be remedied

**Comment by yaira2** [comment]
Drastic changes don't happen overnight, but you can expect gradual improvements from both our side as well as from Microsoft in future updates to WinAppSdk.

**Comment by WarmWelcome** [comment]
> Drastic changes don't happen overnight, but you can expect gradual improvements from both our side as well as from Microsoft in future updates to WinAppSdk.

Cool, looking forward to it :)
The only thing stopping me from replacing file explorer completely after seeing this project just an hour ago is the poor performance. My download folder only has 500 files and stutters quite a bit. I'll be buying this on ms store as soon as this improves to file explorer load times. Thank you!

**Comment by yaira2** [comment]
@WarmWelcome regarding the downloads folder, you can check if turning off the "grouping" mode makes a difference.
