### ISSUE TITLE
Improve perceived startup time with multiple tabs

### ISSUE THREAD

**Issue by clackwell** [files-community/Files#14996]
### What feature or improvement do you think would benefit Files?

When starting, the tabs from the last session get restored. That takes 12 seconds on my fast system until I finally am in the "current" tab and it is done populating.

### Requirements

1) Create the "current" tab and switch to/stay at current tab for the next actions.
2) Populate the left/right side bar (with pinned items, etc.) of the current tab.
3) Populate the file system content of the current tab.

Steps 1, 2 should be instant (1 second max), 3 as fast as possible; loading and showing of icons seems like it could be lowest priority.

4) Create the non-current tabs.
5) Populate the left/right side bar (with pinned items, etc.) of the non-current tab.
6) Populate the file system content of the non-current tabs.

Steps 4, 5 should be instant (1 second max), 6 as fast as possible, but with lower priority than steps 1, 2, 3; loading and showing of icons seems like it could be lowest priority.

Consider populating the content of non-current tabs upon selecting them (lazy loading).

If user changes tab in this startup phase, check if the previous current tab can be paused/throttled and the now-current be given priority.

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3296

**Comment by yaira2** [comment]
Is this a fresh launch or is it when resuming from the background?

**Comment by clackwell** [comment]
This is from a fresh start after closing the window, with "Settings" > "Advanced" > Leave app running in the background when the window is closed" off.

**Comment by yaira2** [comment]
This is expected, we hope further improvements will come when WinAppSdk gets support for Native AOT but in the meantime the setting to keep Files running helps put Files on par with File Explorer which also stays open in the background.

**Comment by clackwell** [comment]
Hm, just to see, I enabled the "run in background" setting, closed the windows, waited 10 seconds, clicked on the Files task bar icon to launch it, the window shows immediately again, fully populated - but then it refreshes completely, rebuilding each tab, giving me the full 12 to 15 seconds of "startup time" again.

**Comment by yaira2** [comment]
It's pretty quick for a few tabs but I see there is a visible delay with more tabs. I'm going to add this feedback to #4180 and we'll add a comment when progress is made in this area.
