### ISSUE TITLE
Adding file preview...

### ISSUE THREAD

**Issue by Kryusss** [files-community/Files#15009]
### What feature or improvement do you think would benefit Files?

Hi,
Did I miss it ? But it seems we can't preview files content...
Thanks, fantastic app :)

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3296

**Comment by 0x5bfa** [comment]
Thanks for the feedback .

You can see preview in info pane you can toggle in the inner navigation toolbar.
