### ISSUE TITLE
Can't install using the classic installer (v3.3.0.0)

### ISSUE THREAD

**Issue by beavis82** [files-community/Files#15008]
### Description

When trying to install the latest version (3.3.0.0) using the classic installer, I receive the following error:

The provided package name does not match the expected package name. Check the AppXDeploy...

(the rest of the message is cut off).

![Files Stable_(4)_CsDy6iYMtp](https://github.com/files-community/Files/assets/118810918/bd0522eb-f690-469d-a533-8ecac794f6d2)

This happens on two different systems (one desktop, and one Surface Pro 8), both running Windows 11 Pro 22H2. Files 3.2.3.0 is already installed on both computers.

I have purchased Files through the store to help support the project, but I prefer to use the classic installer.

### Steps To Reproduce

1. Download the classic installer from the Files website.
2. Run the installer.

The error appears right at the start of the installation process.

### Requirements

Please fix the installer so that I can install the latest version of Files!

### Files Version

3.3.0.0

### Windows Version

Windows 11 Pro 22H2 22621.3296

### Log File

There isn't a log file - the error is in the installer.

**Comment by Josh65-2201** [comment]
Thanks for the report, please see https://files.community/docs/install#:~:text=starting%20an%20update.-,Steps%20required,-for%20the%20%E2%80%9Cclassic
