### ISSUE TITLE
Cached or Auto Refresh Pause: Add sorting by properties data

### ISSUE THREAD

**Issue by tidypy** [files-community/Files#15015]
### What feature or improvement do you think would benefit Files?

As I'm editing Video; I have Multiple versions of the same file.  Same for Audio.

**ISSUE**: Adding columns for ''Properties'': Bit-Depth, Duration, FPS, Codec, Frame height. Or any other MediaInfo.
 _Is resource intensive and slows_ explorer down to a crawl. Just like folder size.   

**Proposed solution**:  "Cached Mode"
properties info and Folder Size info indexed then "Cached" ? 

**Proposed solution 2**:  "Pause or Turn off auto refresh." 
And put an "Update" Button (that possibly changes color or shows last date of refresh on hover?)
Or put a dropdown quick button and 'pause refresh' for 1 hour or run once daily for example.

Proposed reasoning:  
1. Because the Properties of the files rarely change, Likewise the file itself would change names anyway.  
2. Some Users typically browse and sort more then they manipulate, 
3. Some do not care to update or refresh until intended or necessary; when their tasks are complete.
Example:  I will do alot of sorting, create many folders, Drag and drop from multiple windows.  I'm refreshing and optimizing all the time anyway as explorer lags.  But I can't stand freezing and 'stalled' window refreshing with every change. 
4. It is extraordinary tedious to R-click properties. Just to see that one property all the time, like 'bit depth' for example.
5. Allows users to save screen space, you can have the "Type Detail" shown in preview pane, no need for the column, or a super long filename column just to show the extension.

With a cached mode you don't have to troll through entire index but once, and just report the incremental. 
Your "Status Center" already does something similar.  

I don't think it needs to be memory based. Many file recovery tools cache the data in temp, or app-data.

Yeah; this is like several features...apologies in advance.

### Requirements

- This proposal will accomplish X:  Delays auto-refresh and vastly reduce response times. 
- This proposal will accomplish Y:  Adds various properties not easily found, that are resource heavy, and allows sorting them quickly.
- This proposal DRAWBACK is:   Non-updated windows will reference outdated data or data that doesn't exist.  (could be advantageous such as the 'status center')

### Files Version

3.3.0.0

### Windows Version

10.0.22621.3296

### Comments

![2024-03-20 20_47_06-New Issue · files-community_Files](https://github.com/files-community/Files/assets/50213641/3cadfc31-0194-42b2-975f-0481beb8255f)
![2024-03-20 20_50_47-E__test part_Hevc converted](https://github.com/files-community/Files/assets/50213641/2fc8de5a-416e-4464-b413-b4a1a222d054)
![2024-03-20 20_53_14-Videos (2) - Files](https://github.com/files-community/Files/assets/50213641/3405692a-25d4-4d33-bbd0-ac5079dcae18)
![2024-03-20 21_03_19-New Issue · files-community_Files](https://github.com/files-community/Files/assets/50213641/8b0f5ac1-d09a-4832-bb8a-bda04c1654f3)

**Comment by yaira2** [comment]
Thank you for the feedback, support for these columns is being tracked in #8366. As far as performance goes, we'll have to see as we get to implementing the feature, but in general these properties would only update if the file were modified. Feel free to add your feedback to that issue so we can keep your ideas in mind.
