### ISSUE TITLE
Allow hiding the tab bar

### ISSUE THREAD

**Issue by SebastianD334** [files-community/Files#15014]
### What feature or improvement do you think would benefit Files?

- Give users an option, perhaps even a shortcut, to hide the tab bar when there's only one tab in a window, finder on macOS allows this by going into the menus or pressing cmd+shift+t

### Requirements

- Add the ability to hide the tab bar
- Detect when a window has just one tab

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3296

### Comments

I often find myself frustrated with how much space is taken up by unnecessary options in file explorer, and unfortunately this still bothers me with files.
This would potentially also go well with customizing or consolidating the two bars below it, in finder you can individually toggle the path bar, status bar, and customize the whole toolbar to your liking, this can let you massively reduce clutter and increase the useful space inside the finder window.

Here's a comparison showing the difference in usable space between files and finder customized to my liking:
![files](https://github.com/files-community/Files/assets/50913320/7be207d6-56eb-47d6-a680-31893c5b234e)
<img width="1032" alt="finder" src="https://github.com/files-community/Files/assets/50913320/2c73d21c-c9da-446b-bcee-e252baf437b5">

**Comment by yaira2** [comment]
Thank you for your feedback. This isn't the first time this has been requested, but as of now we don't have plans to support hiding tabs or the address bar. That said, things are always changing so we'll continue to monitor for similar feedback and we're open to reevaluating this decision in the future.

**Comment by yaira2** [comment]
On a personal note I fully agree with this request, but the vast majority of our userbase makes use of tabs so it's hard to justify the investments it would take in adapting the UI based on which elements are enabled.
