### ISSUE TITLE
一个非常人性化的需求。

### ISSUE THREAD

**Issue by zc5162** [files-community/Files#15017]
### What feature or improvement do you think would benefit Files?

“在Crowdin上翻译此用”功能打开的连接应随应用语言而改变，如
默认语言打开https://crowdin.com/project/files-app，
设置成中文则打开https://zh.crowdin.com/project/files-app。

**Translated:**
The connection opened by the "Translate this on Crowdin" feature should change depending on the app language, e.g.
Default language is turned on [https://crowdin.com/project/files-app set](https://crowdin.com/project/files-app%EF%BC%8C)
to Chinese [https://zh.crowdin.com/project/files-app is turned on.](https://zh.crowdin.com/project/files-app%E3%80%82)

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.3.0.0

### Windows Version

10.0.26080.1400

**Comment by Josh65-2201** [comment]
Thanks for the feedback, why would you want this?

**Comment by yaira2** [comment]
It would be a nice touch but it's a bit beyond the scope of Files to do this. Does Crowdin not have a way to set the default language on their site?
