### ISSUE TITLE
希望能够支持压缩包内的文件拖拽

### ISSUE THREAD

**Issue by Seth2333** [files-community/Files#15018]
### What feature or improvement do you think would benefit Files?

目前在压缩包内的文件拖拽进Files窗口是不可用的，希望能够支持此操作，我使用的是bandizip

**Translated:**
Currently it is not possible to drag and drop files into the Files window in the archive, I hope to support this, I use bandizip

### Requirements

压缩包内文件拖拽至Files窗口即可直接解压文件到对应位置

### Files Version

3.3.0.0

### Windows Version

win11 23H2 22635.3350

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Files already support this, What issue are you having doing so and what are you using to extract the contents?

**Comment by Seth2333** [comment]
我仔细看了一下，当我选中的压缩包内文件包含文件夹的时候，拖拽便会导致不可用。同时，在banizip左侧列表中通过拖拽压缩包本身来进行创建以压缩包名称命名的文件夹并解压其中的文件这个操作也是不可用的

**Comment by Josh65-2201** [comment]
This sound like a bug, can you open a bug report please
