### ISSUE TITLE
Files trying to open deleted folder on startup (history feature)

### ISSUE THREAD

**Issue by jokbon** [files-community/Files#15013]
### Description

Since files wasn't not open at moment folder was deleted, it doesn't make sense to prompt user about deleted folder on first startup.

### Steps To Reproduce

- Delete folder that was opened on files
- Last Opened History turned on
- Close files
- Start files

### Requirements

- Delete folder that was opened on files
- Last Opened History turned on
- Close files
- Skip opening folder that was deleted during files startup.

### Files Version

3.2.3.0

### Windows Version

10.0.22631.3296

### Log File

-

**Comment by Josh65-2201** [comment]
Thanks for the report, Files can't know when you delete a folder on an open tab while Files is closed, this is working as expected.

**Comment by yaira2** [comment]
@Josh65-2201 I think this is requesting to not resume a tab if the location no longer exists
