### ISSUE TITLE
Feature: Add extra space in column layout for right clicking

### ISSUE THREAD

**Issue by rihards-simanovics** [files-community/Files#15012]
### What feature or improvement do you think would benefit Files?

Currently when using column layout there is no whitespace to right click in the folder itself especially if it's a parent fodler. I propose that some more whitespace got added to the left or preferably to the bottom of the list. MacOS appears to be having half the list item height for their implementation of the column tree, but I think 2/3 of the line item height would be better.

### Requirements

- This proposal will allow for better accessibility as it gives more space to right click
- It will also make it easier to share folders if usig OneDrive

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3296

**Comment by yaira2** [comment]
Thank you for your feedback, a 4px space is probably good but we'll need to do some testing to confirm.
