### ISSUE TITLE
Bug: "Replacing" FolderA with a zipped FolderA from Windows Explorer empties FolderA

### ISSUE THREAD

**Issue by AlsoBear** [files-community/Files#15010]
### Description

Hello,

Since I'm too lazy to _right-click -> Extract_ zipped files, I'm used to dragging contents from zipped files to where I want them.
I found that doing this through Files doesn't work properly yet, so I am still extracting via Windows Explorer. 

Issue:
I've taken a named folder from a .zip archive in Windows Explorer, and dragged it into Files, in a directory where a folder with the same name exists. Files asks to "replace" the folder with the same name, but does not mention replacing any of its contents. Clicking on Accept, replaces the existing named folder with a new, completely empty folder. All of the data is overwritten.

First time I noticed this was on 3.2.3.0, and I thought 3.3.0.0 might fixed this. So I uninstalled 3.2.3.0 and re-installed to 3.3.0.0 after.

### Steps To Reproduce

1. Create a regular file structure: **E:\Testing\FolderA\(any content)**
2. Create a zip file, containing any folder with an equal name: **E:\File.zip\FolderA\(any content)**
3. Open the path **E:\Testing** in Files
4. Open the path **E:\File.zip** in Windows Explorer
5. Drag **File.zip\FolderA** from Explorer to **E:\Testing** in Files
6. Upon notification "Conflicting file name(s)", select _Replace existing_ for FolderA and then _Continue_
7. End result: **E:\Testing\FolderA** is now completely empty.

### Requirements

- I expected the extraction to result in **E:\Testing\FolderA** being filled/mixed with the content from **E:\File.zip\FolderA**, or a failure to extract.

### Files Version

3.3.0.0 (also found on 3.2.3.0)

### Windows Version

10.0.22631.3296

### Log File

[debug.log](https://github.com/files-community/Files/files/14665304/debug.log)

**Comment by yaira2** [comment]
Thank you for the report, we'll try to sort this out but in the meantime, you might be interested in the `ctrl` + `e` and `ctrl` + `shift` + `e` keyboard shortcuts which auto extract archives.

**Comment by yaira2** [comment]
Thank you for the report, this should be resolved in the next update.
