### ISSUE TITLE
Uninstalled as instructed for upgrade cant install new app after 3 failed attempts

### ISSUE THREAD

**Issue by EdwinHolley** [files-community/Files#15029]
### Description

I get a error stating the file is not named correctly.

### Steps To Reproduce

1. Download from Website
2. Run installer
3. Select or Don't the Run option
4. Select Install

### Requirements

- e.g. Fix crash that occurs when...
- Fix the application failing security chech

### Files Version

3.3

### Windows Version

Edition	Windows 11 Home Version	23H2 Installed on	‎10/‎30/‎2023 OS build	22631.3296 Experience	Windows Feature Experience Pack 1000.22687.1000.0

### Log File

I could not get the application installed, so I have no crash logs

**Comment by EdwinHolley** [comment]
I have tried with and without Free Download Manager

**Comment by Josh65-2201** [comment]
Thanks for the report, Can you send a screenshot of the error you are getting.

**Comment by OddUnicorn** [comment]
Same error for me.

Edition	Windows 11 Pro
Version	23H2
Installiert am	‎13.‎12.‎2023
Betriebssystembuild	22631.3296
Leistung	Windows Feature Experience Pack 1000.22687.1000.0

![Files error](https://github.com/files-community/Files/assets/17065737/f25fff1d-daca-4b0d-b6f2-8887c9d8ea53)

**Comment by Josh65-2201** [comment]
See https://files.community/docs/install#:~:text=starting%20an%20update.-,Steps%20required,-for%20the%20“classic

**Comment by EdwinHolley** [comment]
Interesting as this was done, to no change, I just did it again and no change.  I do of course appreciate the charm of closing the ticket though.

**Comment by Josh65-2201** [comment]
Sorry, as the error is only shown if Files is installed and you didn't say anything about trying the above in your initial description I could only assume you didn't seen that page.

Can you try
1. Open an admin powershell window
2. Run `Get-AppxPackage -AllUsers | Where-Object { $_.Name -like "*Files*" } | Select Name, InstallLocation`
3. See if any packages show
4. If so run `Remove-AppxPackage -Package "package name"` replacing package name with the end of the string given with previous out put, example below.
![image](https://github.com/files-community/Files/assets/26977075/ef996343-e1c4-4fe5-8f36-0afc87f7afd2)

**Comment by OddUnicorn** [comment]
This worked for me, I was able to install 3.3.0.0.

> Steps required for the “classic installer” version after 3/21/2024
> Starting 3/21/2024, users of the sideload version (aka classic installer) will need to reinstall Files in order to continue receiving automatic updates. This is a one time requirement due to changes in the code signing certificate.
> Export your settings by going to Settings > Advanced > Export.
> Uninstall Files and restart Windows
> [Reinstall](https://files.community/download/) Files.
> Import your settings from Settings > Advanced > Import.

**Comment by yaira2** [comment]
If anyone else comes across this and is still having this issue, it's suggested to restart Windows before reinstalling Files.
