### ISSUE TITLE
External devices icon missing from left pane after connected

### ISSUE THREAD

**Issue by osieltorres** [files-community/Files#1502]
**Describe the bug**
When some external device is connected, is not showed automatically on left pane as it should, that makes you think even that the device was not connected properly. Happens with USB pendrives and external HDD.

**To Reproduce**
1. Plug in an external device such a pendrive or HDD.
2. Look for device icon on left pane.
3. There is no icon for plugged in external device.

**Expected behavior**
An icon for external device must appear on explorer left pane when device is ready to work with.

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 2004 19041.388]
 - App version: [v0.12.0]

**Comment by osieltorres** [comment]
Sorry, this is a duplicated  from #1467

**Comment by Jaiganeshkumaran** [comment]
> Sorry, this is a duplicated from #1467

No, this could be related but not a duplicate. That issue is for Root Drives not being added to taskbar jumplist when accessed.

**Comment by XPoppyX** [comment]
then it would be a feature request to auto-refresh the drive list

**Comment by Thomas1664** [comment]
To add additional context, this issue only occurs when you plug in a device that needs to be repaired.

**Comment by freispiel** [comment]
I have noticed something similar with TrueCrypt/VeraCryt volumes: No matter what you do, encrypted containers or partitions mounted as "removable medium" will not show up in Files. Even if you mount the container first and start Files afterwards, it will still not show the drive letter of the TC volume.

However, if you mount the container without checking "Mount volume as removable medium", then the new drive letter is displayed normally (after you restart Files).

**Comment by yaichenbaum** [comment]
This issue should be resolved in the `master` branch.
