### ISSUE TITLE
Loading time of context menu when 'Move shell extensions into a sub...' is off. 

### ISSUE THREAD

**Issue by Newerty** [files-community/Files#15020]
### Description

It takes around 2-3 seconds to load context menu when 'Move shell extensions into a sub...' is off. In my opinion its bit to long on modern hardware. 

### Steps To Reproduce

Turn off  'Move shell extensions into a sub...' and try to access context menu. 

### Requirements

Near instant. 

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3296

### Log File

[debug.log](https://github.com/files-community/Files/files/14704223/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, it's primarily for this reason that shell extensions are displayed in a sub menu. We're currently tracking this in #11112, feel free to add a comment or click subscribe on that issue to be notified when improvements are made.
