### ISSUE TITLE
Make drag-icon size constant and preferably small by default

### ISSUE THREAD

**Issue by soredake** [files-community/Files#15021]
### What feature or improvement do you think would benefit Files?

Right now when you set layout to "grid" and icon size to maximum size your drag-icon will become so big it will obstruct your view so you cannot reliably drop it to the application you want:
![image](https://github.com/files-community/Files/assets/5204968/2427c74d-2134-42b5-8da3-d5df8a0fbeb2)

Windows Explorer uses constant size for drag-icon on all layouts / thumbnail sizes:
![image](https://github.com/files-community/Files/assets/5204968/ca2b5ed5-5a8a-4522-9cd4-b5002b48fad0)

### Requirements

- Drag-icon will be constant size (small).

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3296

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #12556. You can check there or click subscribe in the right sidebar for updates.
