### ISSUE TITLE
Expand Files App after opening the folder on the desktop 

### ISSUE THREAD

**Issue by Sicquze** [files-community/Files#15023]
### What feature or improvement do you think would benefit Files?

It would be much more convenient if the application was expanded after opening the folder from the desktop, sometimes you do not always understand folder has opened or not, and you forget that you need to go to the application to make sure the folder is open or not

### Requirements

Expand App after opening the folder 

### Files Version

3.3.0.0

### Windows Version

10.0.19045.4170

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Do you mean focusing Files when you open a folder outside of Files?

**Comment by yaira2** [comment]
@Sicquze can you clarify what you mean by expand?

**Comment by Josh65-2201** [comment]
@Sicquze  Can you provide the information requested in the last comment
