### ISSUE TITLE
How to update from within app? 

### ISSUE THREAD

**Issue by seanbperiod** [files-community/Files#15028]
### What feature or improvement do you think would benefit Files?

Apologies if this has been answered (tried searching update here but couldn't find anything relevant) 

Is downloading from here the only way to update? I couldn't find an update module within the software. 

### Files Version

3.3

### Windows Version

11

**Comment by 0x5bfa** [comment]
3.3 is the latest version of Files as of 3/23/2024 now.
The app has automatic update service within the app so when you open for the first time for a while the app automatically recieve an update, download, kill itsself, install and restart

We have some feedback requiring a button to check manually in Settings > About page, though.
