### ISSUE TITLE
Bug: "Scroll to previous folder when navigating up" not working on network locations

### ISSUE THREAD

**Issue by kamtschatka** [files-community/Files#15024]
### Description

"Scroll to previous folder when navigating up" is not working in all scenarios.
When using a network location, enter a folder and go back, the folder will not be selected anymore.
This works fine on local drives and network drives.

### Steps To Reproduce

Does not work:
1. Make sure "Scroll to previous folder when navigating up" is enabled
2. Access a network location (in my case \\\\nas)
3. Enter a folder (let's say \\\\nas\\asdf)
4. Go back to the previous folder. It is reproducible for me with the controls at the top (left arrow and up arrow) and the special mouse key
5. The folder (asdf) is not selected

Works fine:
* Repeat the steps above, but instead of using a network drive, just use your C: drive
* Repeat the steps above, but use "Map network drive" to assign a drive letter to the network location

### Requirements

"Scroll to previous folder when navigating up" works consistently

### Files Version

3.3.0.0

### Windows Version

Windows 11 Pro 23H2 22631.3296

### Log File

[debug.log](https://github.com/files-community/Files/files/14706314/debug.log)

**Comment by yaira2** [comment]
Thank you for the report

**Comment by yaira2** [comment]
This should be resolved in the next update.
