### ISSUE TITLE
Paste option should refresh the list of items

### ISSUE THREAD

**Issue by osieltorres** [files-community/Files#1503]
**Describe the bug**
After "Paste" option is selected, list of items dont get updated, unless is manually done, causing sometimes duplicated pasted files

**To Reproduce**
1. Go and copy some files from any folder.
2. Go back to any other folder and paste them into.
3. Try to find the first item is being pasted.
4. No list of item is updated where you pasted the files.

**Expected behavior**
As soon as files starts to be pasted into the new place, they should be visible one by one in the list of items of place we are into.

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 2004 19041.388]
 - App version: [v0.12.0]

**Comment by Jaiganeshkumaran** [comment]
Files UWP is programmed to refresh the list as soon as something changes in that directory. Is there anything special about that folder?

**Comment by osieltorres** [comment]
Nothing special in folder, I have tried to recreate this bug to be more precise. Somehow is related with changing default configuration, for example, if I change Experimental option like "Double tap to rename files", in some copy & paste simply does not refresh after starting to be copied to folder, also the app crashes frequently.

**Comment by IanHead** [comment]
When I try pasting an item on a local drive, the refresh is automatic, but when pasting in a folder on a mapped network drive, the folder needs to be refreshed manually - the same is true when creating new items or deleting items on a mapped network drive.

**Comment by yaichenbaum** [comment]
Merging with #2042.
