### ISSUE TITLE
Feature: Open properties while holding down Alt and double-click on the item

### ISSUE THREAD

**Issue by Triangle-GitHub** [files-community/Files#15036]
### What feature or improvement do you think would benefit Files?

我注意到在[#12944](https://github.com/files-community/Files/issues/12944)中已经实现了Alt+Enter打开属性，能否使按住Alt双击项目也能打开属性？这会符合用户的使用习惯和更高效的操作。

**Translated:**
I've noticed that Alt+Enter has been implemented in https://github.com/files-community/Files/issues/12944 to open the property, could it be possible to hold down Alt and double-click on the item to open the property as well?

### Requirements

添加 Alt-双击作为打开属性窗口的热键

**Translated:**
Added Alt-double-click as a hotkey to open the properties window

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3296

**Comment by Josh65-2201** [comment]
Thanks for the feedback, I've added this to the project board.

**Comment by yaira2** [comment]
@Josh65-2201 wouldn't this be covered best under support for remapping actions?

**Comment by Josh65-2201** [comment]
Does it support mouse click ones?

**Comment by yaira2** [comment]
Not right now but it can be included

**Comment by Josh65-2201** [comment]
I would say so then

**Comment by yaira2** [comment]
@Triangle-GitHub thank you for your feedback, we're going to continue tracking this in #9559. Please add a comment with your feedback or click subscribe on that issue to be notified of further developments.
