### ISSUE TITLE
希望在文件属性中显示数字签名（如果有）

### ISSUE THREAD

**Issue by Triangle-GitHub** [files-community/Files#15032]
### What feature or improvement do you think would benefit Files?

我建议在文件属性（例如exe, dll）中显示其包含的数字签名，以便于检查文件是否有病毒。
<img width="370" alt="image" src="https://github.com/files-community/Files/assets/114236693/553c48ef-7a92-4b28-8eca-75f22a823779">

### Requirements

快速确认可执行文件的数字签名有助于排除恶意软件。

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3296

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #3723 . You can check there or click subscribe in the right sidebar for updates.
