### ISSUE TITLE
Bug: Files crash when double clicking and holding shift key

### ISSUE THREAD

**Issue by Triangle-GitHub** [files-community/Files#15037]
### Description

我注意到在任意一个文件夹里，按住Shift并双击其中一个文件夹会导致Files停止响应，并在数秒后崩溃。

实际上，我建议Files解决这个崩溃后，可以让按住Shift并双击成为一个热键，例如在新面板中打开。

**Translated:**
I've noticed that in any folder, holding down Shift and double-clicking on one of the folders causes the Files to stop responding and crash after a few seconds.

Actually, I'd suggest that Files, after fixing this crash, could make Shift-and-double-click a hotkey, e.g. open in a new panel.

### Steps To Reproduce

1. 打开任意一个文件夹，例如D:\SampleFolder
2. 选中其中一个文件夹，例如D:\SampleFolder\Folder3
3. 按住Shift并双击该文件夹或另一个文件夹
4. 观察到FIles在数秒后崩溃

**Translated:**
1. Open any folder, e.g. D:\SampleFolder
2. Select one of the folders, for example, D:\SampleFolder\Folder3
3. Hold down Shift and double-click on that folder or another folder
4. FIles were observed to crash after a few seconds

### Requirements

- Fix crash that occurs when 按住Shift并双击文件夹
- 让按住Shift并双击成为在新面板中打开的热键 (optional)

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3296

### Log File

2024-03-23 23:30:18.2025|Information|App launched. Launch args type: LaunchActivatedEventArgs
2024-03-23 23:30:18.5867|Information|Adding cloud provider "OneDrive" mapped to C:\Users\(my username)\OneDrive
2024-03-23 23:30:18.6146|Information|Drive added: C:\, Fixed
2024-03-23 23:30:19.0007|Information|Drive added: D:\, Fixed
2024-03-23 23:30:19.1323|Information|Drive added: E:\, Removable
2024-03-23 23:30:19.1516|Information|Drive added: G:\, Removable
2024-03-23 23:30:19.2146|Information|Drive added: E:\
2024-03-23 23:30:19.2232|Information|Drive added: G:\
2024-03-23 23:30:19.8059|Information|STORE: Checking for updates...
2024-03-23 23:30:22.1487|Information|Running on ARM: False

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by Triangle-GitHub** [comment]
![image](https://github.com/files-community/Files/assets/114236693/b568bcb9-ff55-455b-83c9-51394e1f3336)
我试了3.4.5.0，好像问题还在，现在它显示占用recycle bin文件夹

**Comment by yaira2** [comment]
I'm having trouble reproducing this issue, can you share a screen recording?

**Comment by Triangle-GitHub** [comment]
https://github.com/files-community/Files/assets/114236693/dd196b87-5af1-4c5a-abc4-09c93337cff7

感谢关注我的问题，这是复现视频。

**Comment by Josh65-2201** [comment]
Thats Windows File Explorer, not Files.

**Comment by Triangle-GitHub** [comment]
十分抱歉，我看成了对我的 [另一个issue](https://github.com/files-community/Files/issues/15320) 的回复。我重新测试了下，按住shift并双击的行为不再会造成崩溃，感谢修复。

**Comment by Josh65-2201** [comment]
Thanks for letting us know
