### ISSUE TITLE
Bug: Address bar is empty when opening an ftp server

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#15031]
### Description

![image](https://github.com/files-community/Files/assets/66369541/951bd2da-0f6a-4d03-bc7c-ca779e05b51d)

### Steps To Reproduce

1. Open an ftp server.
2. See the address bar.

### Requirements

Show the ftp server address.

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3296

### Log File

n/a

**Comment by yaira2** [comment]
Thank you for the report and fix.
