### ISSUE TITLE
Pinned, Quick Access and Recent Files are all empty, and nothing can be added to them

### ISSUE THREAD

**Issue by Wakers** [files-community/Files#15034]
### Description

When I first installed files, all of these features worked. 

Then yesterday when I started the PC, everything had been removed from Pinned, Quick Access and Recent Files, and now when I attempt to add a folder/shortcut/file to any of these, it doesn't work. There's no error message, just nothing happens.

![image](https://github.com/files-community/Files/assets/8877744/a4f11da7-2985-4d32-8136-7407053bac28)

### Steps To Reproduce

1. Open Files

### Requirements

Pinned, Quick Access and Recent Files should be populated, and I should be able to add items to these areas.

### Files Version

3.3.0.0

### Windows Version

10.0.22635.3212

### Log File

[debug.log](https://github.com/files-community/Files/files/14731243/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Can you try
- Restarting Windows 
- Clearing recent folders in Windows File Explorer > `...` button > Options > Clear > Restart Files from the system tray

**Comment by Wakers** [comment]
Hi, sorry for not getting back to you. I thought I had.

Your suggesting fixes the problem until the next reboot, at which point the problem occurs again. 

What information/data can I provide for you to help you look into this?

**Comment by Josh65-2201** [comment]
Can you try In the same page as clearing, turn off `Show recent folders` option then clear them again and see if it stays working.

**Comment by capz** [comment]
this seems to help keeping my desktop etc in the pinned list, will report back if this keeps happening. i seem to have the same issue as @Wakers

**Comment by Josh65-2201** [comment]
This seem to be a issue for a lot of users, right now we're tracking this in https://github.com/files-community/Files/issues/15120. You can check there or click subscribe in the right sidebar for updates.
