### ISSUE TITLE
Pin to Start causes the app icon to be Files icon

### ISSUE THREAD

**Issue by gumbarros** [files-community/Files#15038]
### Description

Pin to Start causes the app icon to be Files icon

![image](https://github.com/files-community/Files/assets/52143624/40bf6c76-461f-4f58-a4fd-d4440e958e35)
![image](https://github.com/files-community/Files/assets/52143624/c8904bd6-9b6d-4d38-bc7b-efc535a0ff40)

### Steps To Reproduce

1. Pin to Start
2. Check the icon

### Requirements

Icon should be the app icon

### Files Version

3.3.0

### Windows Version

11

### Log File

[debug.log](https://github.com/files-community/Files/files/14734050/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #12191 . You can check there or click subscribe in the right sidebar for updates.
