### ISSUE TITLE
file thumbnails not on details layout

### ISSUE THREAD

**Issue by siloricity** [files-community/Files#15039]
### Description

(I am assuming this is a bug)
When i updated to 3.3 I noticed that files did not have their images on details layout such as audio and video
This is a big reason why I use this file browser
![image](https://github.com/files-community/Files/assets/83559941/833eaa8f-8270-4fd1-9102-aeb0635c6c8e)

### Steps To Reproduce

Use layout that isn't Grid or Tiles

### Requirements

Add thumbnail for these views, or add option to

### Files Version

3.3.0.0

### Windows Version

11, 22631.3296

### Log File

No log necessary

**Comment by Josh65-2201** [comment]
Thanks for the report, this is working as intended as details layout is too small to show thumbnails of any use. You can use other layouts to see them.

**Comment by yaira2** [comment]
In the past we did show thumbnails in the Details View and they will likely be added back in a future update (when using the larger spacing options in the Details View).
