### ISSUE TITLE
New icons

### ISSUE THREAD

**Issue by EdlonJR** [files-community/Files#15046]
### What feature or improvement do you think would benefit Files?

I'd like to have the option to put my own icons for folders like KDE Linux themes. Being able to use folder icons, for example, like you have on the Samsung Note would be awesome. Truly the pinnacle of personalization. 

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.3.0.0

### Windows Version

10.0.26085.1

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #10941. You can check there or click subscribe in the right sidebar for updates.

Right now you can change the icons on folders individually
