### ISSUE TITLE
Classic installer for 3.3 upgrade gives error "The provided package name does not match the expected package name. Check the AppXDeployn""

### ISSUE THREAD

**Issue by Vortigern-The-Grey** [files-community/Files#15042]
### Description

When attempting to upgrade to Files 3.3 from 3.2.2, the classic installer gives this error:
![image](https://github.com/files-community/Files/assets/152357748/bdd1fc3a-9eea-4b0a-9c27-a24676d09ccd)

### Steps To Reproduce

1. Have Files 3.2.2 installed.
2. Download and run the classic installer for 3.3
3. Get this error:
![image](https://github.com/files-community/Files/assets/152357748/40a92a61-76fc-4512-b48d-2cebb9ac5377)

### Requirements

- Cannot proceed with installation/upgrade
- Does not work when run as Administrator
- On an upgraded Windows 11 Tablet Pro 7+

### Files Version

3.2.2.0

### Windows Version

10.0.22631.3296

### Log File

[debug.log](https://github.com/files-community/Files/files/14738614/debug.log)

**Comment by 0x5bfa** [comment]
Did you uninstall first?

**Comment by Josh65-2201** [comment]
See https://files.community/docs/install#:~:text=starting%20an%20update.-,Steps%20required,-for%20the%20%E2%80%9Cclassic

**Comment by yaira2** [comment]
Thank you for the feedback, to continue receiving updates for the sideload version (this doesn't apply to the Store version), a one time uninstall & reinstall is required. Please see the instructions Josh linked above for further details.
