### ISSUE TITLE
Bug: App crashing when pinning/unpinning from quick access

### ISSUE THREAD

**Issue by darklordcoz** [files-community/Files#15047]
### Description

Crashes very often. Unusable.

### Steps To Reproduce

1. Pin or unpin folder
2. See app crashes

### Requirements

To actually be able to use the app. 

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3296

### Log File

[debug.log](https://github.com/files-community/Files/files/14749750/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, can you clarify at which point the app is crashing (eg. on the splash screen, home page etc)?

**Comment by darklordcoz** [comment]
It just crashes at random times constantly. The quick access doesn't work either.

**Comment by yaira2** [comment]
Some issues are rare and specific to certain devices, so it's a little hard for us to investigate without more details. Would you be so kind as to list some more detailed steps on which buttons or actions you were using before the app crashed?
For example
1. Opened large folder with 2 million folders
2. Deleted all items and app crashed

**Comment by darklordcoz** [comment]
I really don't know how to explain. It is totally random and happens even when I don't have a window open. One specific I can mention is that messing with the quick access in anyway crashes it instantly. As for the other times it is just random I couldn't even begin to reproduce them. Whether I'm just browsing my files or I just leave a window open it will crash out of nowhere.

**Comment by yaira2** [comment]
That helps, let's try to figure out the issue with Quick Access
- Do you have a lot of items in Quick Access?
- Are they all local folders or are they on network drives?
- Is the issue when pinning a folder or is it when unpinning them?

**Comment by darklordcoz** [comment]
I have three local folders documents, desktop, and pictures. I have onedrive disabled if that means anything. It will crash if I try to pin or unpin any folders.

**Comment by yaira2** [comment]
This is what I see in the log file which indicates a problem with communication between Files and Windows. Can you check if it's working to pin/unpin items from File Explorer?
> 2024-03-25 16:21:47.9213|Error|System.Runtime.InteropServices.COMException (0x800706BE): The remote procedure call failed.

**Comment by darklordcoz** [comment]
File explorer works fine except for one issue. The reason I was looking for an alternative for file explorer is when I open a folder containing music files and just music files it takes file explorer anywhere from 5 minutes to 30 minutes to load the contents of the folder.

**Comment by nezumiCodes** [comment]
I have the same issue. I have downloaded both 'Files' and 'Files Preview' since the native file explorer would crash after a couple of clicks. 

When trying to pin a local folder it works fine, unpinning (either from pinned items in sidebar or right clicking the actual folder) it will cause the program to crash. Same thing happens when unpinning folders backed up in cloud drives, however when trying to pin one, Files won't do anything.

**Comment by yaira2** [comment]
@nezumiCodes can you upload the log file from the preview version?

**Comment by yaira2** [comment]
@darklordcoz Is this still an issue in the preview version (v3.5.24)? https://files.community/download/preview
