### ISSUE TITLE
deleted file does not disappear from the screen

### ISSUE THREAD

**Issue by dpbueno** [files-community/Files#15049]
### Description

When I delete a file or even in OneDrive files the screen does not update, that is, I need to update manually for the file to disappear

### Steps To Reproduce

1. select file
2. press DEL
3. The file remains on the screen

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.3.0.0

### Windows Version

10.0.19045.3930

### Log File

[debug.log](https://github.com/files-community/Files/files/14758616/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Do you mean you are deleting them outside of Files?

**Comment by dpbueno** [comment]
I'm deleting it in the "Files" itself

**Comment by yaira2** [comment]
@dpbueno we can't repro this issue in v3.6. If it's still occurring on your side, please let us know and we'll reopen this issue.
