### ISSUE TITLE
Bug: Not able to turn Files App into default manager

### ISSUE THREAD

**Issue by notRyuk** [files-community/Files#15040]
### Description

Inital configuration (in 23H1) **Files App** is the default manager, due to some requirements I had to turn this settings and use File Explorer as the default manager for some time. Recently when I updated my my windows from 23H1 to 23H2. After the update I'm not able to turn this option back on. 

### Running Files as Admin
The issue persists

### Steps To Reproduce

1. Open Files App
2. `Settings > Advanced > Set Files App as the Default Manager.` (Intially **off**)
3. Turn on this option

### Requirements

Expected to turn Files App into default manager (if not normally maybe when run as Admin in windows)

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3296

### Log File

[debug.log](https://github.com/files-community/Files/files/14735083/debug.log)

### Recording
https://github.com/files-community/Files/assets/72451243/881db8de-31b7-4b26-9840-5730ee15ef47

**Comment by Josh65-2201** [comment]
Thanks for the report, This is an issue with Windows making the option not compatible. The only known solution right now to reinstall Windows

**Comment by yaira2** [comment]
There is also the option to manually import the registry file but it has its own issues and isn't recommened.
