### ISSUE TITLE
Feature: Support "Thin acrylic" backdrop

### ISSUE THREAD

**Issue by ShashankKalwa** [files-community/Files#15045]
### Requirements

- Add support for "Thin acrylic"

### Files Version

3.3

### Windows Version

Windows 11 23H2 22635.3350

**Comment by Josh65-2201** [comment]
For theming follow the instructions at https://files.community/docs/configuring/custom-themes

**Comment by ShashankKalwa** [comment]
> For theming follow the instructions at https://files.community/docs/configuring/custom-themes

I want Glass theme without the Acrylic backdrop effect.

**Comment by Josh65-2201** [comment]
The glass theme is Acrylic backdrop on the full window.

**Comment by ShashankKalwa** [comment]
The First One Is The Latest Files

![Screenshot 2024-03-25 225751](https://github.com/files-community/Files/assets/93568767/50fab1a2-77d8-40e0-8c2b-9fe82dffad48)


Second One Is The Old One "Files V2"

![Screenshot 2024-03-25 225845](https://github.com/files-community/Files/assets/93568767/453e97af-ee53-440b-8696-c52bf1eb18ed)

Can you spot the difference?
The theme i wanted is the 2nd one from the screenshots

**Comment by Josh65-2201** [comment]
You didn't follow the instructions on the site. It works for me.

**Comment by yaira2** [comment]
@ShashankKalwa after enabling acrylic, there is the additional step of adjusting the opacity.

**Comment by ShashankKalwa** [comment]
> @ShashankKalwa after enabling acrylic, there is the additional step of adjusting the opacity.
> 
> 1. Open Files > Settings > Advanced > Edit settings file. This will open the settings file in your default text editor.
> 2. Before editing the settings file, you’ll need to close Files by right-clicking the icon in the system tray and clicking on “Quit”.
> 3. The settings file has a JSON format. You can use any text editor to open and modify it.
> 4. Search for the keys listed below and edit the values accordingly.
> 
> ```json
> "AppThemeBackgroundColor": "00000000",
> "AppThemeAddressBarBackgroundColor": "00000001",
> "AppThemeSidebarBackgroundColor": "00000001",
> "AppThemeFileAreaBackgroundColor": "00000001",
> ```


i have edited them but when i reopen the Files the changes are undone

How to save them?

**Comment by Josh65-2201** [comment]
You didn't put the # in before the numbers

**Comment by ShashankKalwa** [comment]
> You didn't put the # in before the numbers



Is this done right?

{
  "ShowSendToMenu": true,
  "ShowOpenInNewWindow": true,
  "AppThemeSidebarBackgroundColor": "#00000001",
  "ShowGitLastCommitDateColumn": false,
  "ShowOpenInNewPane": true,
  "DateTimeFormat": 0,
  "NameColumnWidth": 240,
  "GitStatusColumnWidth": 80,
  "OpenItemsWithOneClick": false,
  "FileTagsWidgetExpanded": true,
  "AppThemeBackgroundColor": "#00000000",
  "SelectFilesOnHover": false,
  "GitCommitAuthorColumnWidth": 140,
  "AppThemeFontFamily": "Segoe UI Variable",
  "ScrollToPreviousFolderWhenNavigatingUp": false,
  "ShowCreateFolderWithSelection": true,
  "DetailsViewSize": 2,
  "ShowCopyPath": true,
  "DoubleClickToGoUp": true,
  "DefaultSortDirectoriesAlongsideFiles": false,
  "ShowNetworkDrivesSection": true,
  "ShowQuickAccessWidget": true,
  "ShowDateColumn": true,
  "ShowCreateShortcut": true,
  "IsSidebarOpen": true,
  "GridViewSize": 8,
  "RestoreTabsOnStartup": false,
  "AppThemeAddressBarBackgroundColor": "#00000001",
  "ShowPinnedSection": true,
  "ShowGitLastCommitShaColumn": false,
  "ShowFileExtensionWarning": true,
  "DefaultDirectorySortDirection": 0,
  "ShowGitLastCommitMessageColumn": false,
  "ColumnLayoutOpenFoldersWithOneClick": true,
  "AlwaysOpenDualPaneInNewTab": false,
  "ShowSyncStatusColumn": true,
  "DefaultLayoutMode": 5,
  "GitLastCommitMessageColumnWidth": 140,
  "Actions": null,
  "ContinueLastSessionOnStartUp": true,
  "TypeColumnWidth": 140,
  "ShowCheckboxesWhenSelectingItems": true,
  "ShowGitStatusColumn": false,
  "ShowOpenInNewTab": true,
  "ShowDrivesSection": true,
  "ShowSizeColumn": true,
  "ShowFileExtensions": true,
  "SyncStatusColumnWidth": 50,
  "MoveShellExtensionsToSubMenu": true,
  "SidebarWidth": 255,
  "ShowTypeColumn": true,
  "GitLastCommitDateColumnWidth": 140,
  "DateModifiedColumnWidth": 200,
  "ShowProtectedSystemFiles": false,
  "ShowThumbnails": true,
  "ShowGitCommitAuthorColumn": false,
  "ListViewSize": 2,
  "OpenSpecificPageOnStartup": false,
  "ShowHiddenItems": true,
  "ShowFileTagsWidget": false,
  "IsEnabled": false,
  "ShowDateDeletedColumn": true,
  "AreAlternateStreamsVisible": false,
  "LeaveAppRunning": false,
  "ShowDotFiles": true,
  "RecentFilesWidgetExpanded": true,
  "ShowRecentFilesWidget": true,
  "ShowDateCreatedColumn": false,
  "OpenNewTabOnStartup": false,
  "ShowFileTagColumn": true,
  "DateCreatedColumnWidth": 200,
  "ShowPathColumn": true,
  "DeleteConfirmationPolicy": 0,
  "DrivesWidgetExpanded": true,
  "TabsOnStartupList": null,
  "SizeColumnWidth": 100,
  "ShowFileTagsSection": true,
  "OpenFoldersInNewTab": false,
  "SyncFolderPreferencesAcrossDirectories": false,
  "AppThemeBackdropMaterial": 3,
  "CalculateFolderSizes": true,
  "DefaultSortOption": 0,
  "ColumnsViewSize": 2,
  "ShowOriginalPathColumn": true,
  "ShowCloudDrivesSection": true,
  "ShowWslSection": true,
  "ShowLibrarySection": false,
  "PathColumnWidth": 200,
  "DateDeletedColumnWidth": 200,
  "DefaultGroupByDateUnit": 0,
  "FoldersWidgetExpanded": true,
  "GitLastCommitShaColumnWidth": 80,
  "DefaultGroupOption": 0,
  "OriginalPathColumnWidth": 200,
  "ShowCompressionOptions": true,
  "ShowEditTagsMenu": true,
  "LastSessionTabList": [
    "{\u0022InitialPageType\u0022:\u0022Files.App.Views.PaneHolderPage\u0022,\u0022NavigationParameter\u0022:\u0022Home\u0022}"
  ],
  "DefaultSortFilesFirst": false,
  "DefaultDirectoryGroupDirection": 0,
  "AppThemeFileAreaBackgroundColor": "#00000001",
  "TagColumnWidth": 140,
  "ShowDrivesWidget": true,
  "OpenTabInExistingInstance": true
}

**Comment by yaira2** [comment]
@ShashankKalwa it looks like it 👍

**Comment by ShashankKalwa** [comment]
Dhanyavad 🙏

**Comment by yaira2** [comment]
Did it work? 👀

**Comment by ShashankKalwa** [comment]
![Screenshot 2024-03-25 232701](https://github.com/files-community/Files/assets/93568767/6b5ac3f5-c749-476d-b4cb-986db174bfd6)


No, It did not work
Its looking same like before

**Comment by Josh65-2201** [comment]
What do you mean? That is the glass theme same as v2. If you mean they layout not the same then that isn't controlled by theming

**Comment by ShashankKalwa** [comment]
I don't mean layout.
I mean the background

See this is Files
![Screenshot 2024-03-25 233103](https://github.com/files-community/Files/assets/93568767/cc1f52fd-597d-4cb6-bef5-c4e16691fbb5)


this is V2
![Screenshot 2024-03-25 233118](https://github.com/files-community/Files/assets/93568767/31724336-1e1f-4655-ba8f-5833438ca083)

**Comment by ShashankKalwa** [comment]
The old V2 is clearer than latest files

**Comment by ShashankKalwa** [comment]
Guys please respond fast

**Comment by ShashankKalwa** [comment]
?

**Comment by Josh65-2201** [comment]
Unfortunately that's just how acrylic looks now. There isn't a setting to make it more clear and I don't think there can be.

**Comment by yaira2** [comment]
> Unfortunately that's just how acrylic looks now. There isn't a setting to make it more clear and I don't think there can be.

If you check the WinUI 3 Gallery, it looks like they also have an option for "Thin acrylic" which I think has the original behavior. @heftymouse fyi

**Comment by heftymouse** [comment]
The current acrylic backdrop is based on thin acrylic. To achieve a similar effect to base acrylic, you can increase the opacity of the default black background. There is a case to be made for adding base acrylic as a built-in option though

**Comment by yaira2** [comment]
I see, so I had it backwards. Let's try base acrylic then 👍 

Should we have both or should we switch to base?

**Comment by mdtauk** [comment]
Think about how you would give the theme the option to use a thin acrylic, and add opacity to the base background colour to make it more like the flyout acrylic.

**Comment by ShashankKalwa** [comment]
Is it still to make old Files V2 as default file explorer?

**Comment by ShashankKalwa** [comment]
> Is it still safe to make old Files V2 as default file explorer?

???

**Comment by 0x5bfa** [comment]
Yeah reg file has never been changed for a long time.
You can set but you must uninstall v3 first if you've installed before.

**Comment by yaira2** [comment]
> Is it still safe to make old Files V2 as default file explorer?

This is a bit off topic for this issue, but I'd advise against using v2 in general as we have many bug fixes and optimizations in v3.

**Comment by ShashankKalwa** [comment]
> > Is it still safe to make old Files V2 as default file explorer?
> 
> This is a bit off topic for this issue, but I'd advise against using v2 in general as we have many bug fixes and optimizations in v3. Regarding this feature request, it's been approved for development and it's on our todo list.

Ok
Thanks For considering my feature request.
