### ISSUE TITLE
Bug: Spamming detail/preview pane freezes app

### ISSUE THREAD

**Issue by jokbon** [files-community/Files#15055]
### Description

Files freeze by spamming previews.

When scrolling down while holding arrow keys, I observed GPU memory usage spikes exceeding 2gigabytes (from 0.5gb used originaly).

Its posible to crash it even by ocasionaly clicking layouts which trigger prievievs.

### Steps To Reproduce

1. Open location with many items
2. Enable preview or details pane
3. Hold down arrow key and observe that the app freezes

### Requirements

- add cooldown period before updating the pane

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3296

### Log File

-

**Comment by yaira2** [comment]
Thank you for the report
