### ISSUE TITLE
BUG:Folder partial match.. It shows pinned folder opened in sidebar (its not).

### ISSUE THREAD

**Issue by jokbon** [files-community/Files#15052]
### Description

![image](https://github.com/files-community/Files/assets/29400409/5f0301ee-28f8-43c3-bb31-f366b3afd1c8)

### Steps To Reproduce

1. Create sidebar folder entry with similar name prefix of one thats alredy opened.
2. Watch files show u that you are in that folder only cause it partialy matches.

### Requirements

Fully match folder names.

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3296

### Log File

-

**Comment by yaira2** [comment]
Is the pinned item a parent location of the current folder?

**Comment by mafra99** [comment]
I can reproduce the issue with the following directories
- C:\tmp\testdir1
- C:\tmp\testdir1 - Copy

If "testdir1" is pinned and you enter "testdir1 - Copy", "testdir1" is shown as active in the sidebar
