### ISSUE TITLE
Items processed invalid number count

### ISSUE THREAD

**Issue by Newerty** [files-community/Files#15053]
### Description

Items processed invalid number count
![Screenshot_1](https://github.com/files-community/Files/assets/6784826/08c04294-fbb1-442f-8423-b05e8e883be5)

### Steps To Reproduce

I was deleting files.  

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3296

### Log File

[debug.log](https://github.com/files-community/Files/files/14761741/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #13860. You can check there or click subscribe in the right sidebar for updates.
