### ISSUE TITLE
Allow the ability to right click and pin any header top bar operator to top level

### ISSUE THREAD

**Issue by Draise14** [files-community/Files#15058]
### What feature or improvement do you think would benefit Files?

![image](https://github.com/files-community/Files/assets/35357409/ddb66b42-059c-4c52-9011-66330a9eda29)

Allow the ability to pin any layout and view operators to go to a top level for user customizability. 

### Requirements

- Allow power user customizability
- Allow some user preferred operators to not be so deep or need to be reliant on a hotkey that may conflict with another software
- Allow to quickly use an operator with a single click (no menu) if needed

### Files Version

3.3.0.0

### Windows Version

10.0.22635.3350

### Comments

Typically this could be done using Dolphin or the W10 file explorer - where you can pin and re-order different operators to customize the explorer to your needs, like pin the ascending or descending toggles to a top level (instead of 3 deep)
![image](https://github.com/files-community/Files/assets/35357409/ba150af4-8f80-42b8-a4af-f9d409ec1c88)

**Comment by yaira2** [comment]
I think @Josh65-2201 has a similar request in another issue but I’ll need some time to locate it.

**Comment by Draise14** [comment]
Found it. Duplicate. 
https://github.com/files-community/Files/issues/14426
