### ISSUE TITLE
Image Icons not loading reliably

### ISSUE THREAD

**Issue by Draise14** [files-community/Files#15062]
### Description

![image](https://github.com/files-community/Files/assets/35357409/73464885-d6fe-4782-9b82-48b8ce617027)
![image](https://github.com/files-community/Files/assets/35357409/ed653d65-5119-463c-99ce-6a96538f246a)

I was about to make this my main explorer, but then I found the image thumbnail generation in Grid view or other layouts are unreliable.

After some time, the file previews will default to this:
![image](https://github.com/files-community/Files/assets/35357409/92b2edf6-d5c9-4391-85f2-e3afd0f63ccb)

This also seems to be corrupting thumbnails elsewhere in the OS, since other software and the default Explorer have troubles after trying to load thumbnails from those folders. 

File Explorer in W11 now freezes:
![image](https://github.com/files-community/Files/assets/35357409/93bb3af1-2662-49b4-8579-02676f102811)

Start11 also doesn't load icons:
![image](https://github.com/files-community/Files/assets/35357409/d9458125-a0c0-473c-9d32-8aa080a65996)

### Steps To Reproduce

1. Have a folder of many various image files and folders with varying dimentions (screen captures folder is a good one to test on)
2. Go to Grid view Layout (currently easiest with the hotkey CTRL+SHIFT+4)
3. Notice that some thumbnails don't load when scrolling down

### Requirements

Sometimes when scrolling to a small size, the thumbnails will generate, then store and work when scaling up. But not always. 

File mixtures can be *.jpg, *.mp4, *.png, *.gif, *.kra (krita) and *.blend (blender). 

Other codecs installed:
-  *.blend by Blender. 
- FastPictureViewer Codecs (for *.exr and others)
https://www.fastpictureviewer.com/downloads/

Other software that may be conflicting with icons and thumbnails (also bugs the icons after trying to load them in Files)
- Start11
https://www.stardock.com/products/start11/

### Files Version

3.3.0.0

### Windows Version

10.0.22635.3350

### Log File

[debug.log](https://github.com/files-community/Files/files/14775368/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Files doesn't change anything with other programs, Can you check your GPU VRAM and Memory usage is not running out in Task manager when this happens?

**Comment by Draise14** [comment]
![image](https://github.com/files-community/Files/assets/35357409/0eee9a66-8b77-4bba-954c-d00c082f79a7)

Computer has not spiked while hitting the error.

**Comment by Draise14** [comment]
I have since uninstalled the FastPictureViewer Codecs , seems more reliable now.

**Comment by Draise14** [comment]
Seems I have to re-register the thumbnail codecs for it to work reliably after installing Files. And also make sure I don't replace any JPG or vector codecs - and all good.

**Comment by yaira2** [comment]
This is good to know, thanks for the detailed report and the steps you took to resolve it.

**Comment by yaira2** [comment]
Did this also resolve the issue with the icons refreshing on zooming in/out?

**Comment by Draise14** [comment]
This did not resolve the zooming blink issue. That would be a separate issue. #15057

**Comment by Draise14** [comment]
**Note:**
- Powertoys from Microsoft with *.svg also is having issues.
