### ISSUE TITLE
Bug: Chose best layout text too long for layout picker in some languages

### ISSUE THREAD

**Issue by Koronfli** [files-community/Files#15063]
### Description

Window size is not enough to accomodate UI elements. The right side of a Files window is "cut" and there is not enough space for options text. Even though there is a scroll bar on the bottom, text is still concatenated. E.g. "aparênciaDesativado"

![Files feedback](https://github.com/files-community/Files/assets/165186473/f4ab66e3-a5fb-488c-a7fd-c6b6fe6e749e)

### Steps To Reproduce

1. Open Files
2. Click the icon to choose a icon layout

### Requirements

Fix window size to fit UI elements and descriptions.

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3374

### Log File

[debug.log](https://github.com/files-community/Files/files/14775894/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
Why is the text for that string so long?

**Comment by Josh65-2201** [comment]
This is what it translate too, I guess it old or not done well
Adaptive layout: Let me choose the best appearance

**Comment by Koronfli** [comment]
The translation is correct. Maybe the part "let me choose the best appearance" could be omitted. OR the window size issue can be fixed.

**Comment by yaira2** [comment]
The flyout was designed to be responsive for different languages, but we didn't expect translators to add additional words to the strings. I think the best path forward is for the localized string to be updated on Crowdin. https://crowdin.com/project/files-app

**Comment by yaira2** [comment]
Thank you!
