### ISSUE TITLE
Quick access

### ISSUE THREAD

**Issue by ajay-mishra7** [files-community/Files#15060]
### What feature or improvement do you think would benefit Files?

Add a feature to remove files/folders from quick access

### Requirements

Add "Remove from quick access option"

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3374

### Comments

I was trying to remove a unwanted folder which was added by mistake in quick access but unfortunately there is no such option to remove it from quick access.

**Comment by Josh65-2201** [comment]
Thanks for the feedback, you already can by right clicking the item > Unpin from sidebar
