### ISSUE TITLE
Hidden files

### ISSUE THREAD

**Issue by ajay-mishra7** [files-community/Files#15065]
### Description

Unable to simultaneously hide or unhide multiple files.. I have to 

### Steps To Reproduce

1. select multiple files 
2. click on properties
3. go to attributes 
4. select hiddden

### Requirements

- Fix a bug that occurs when i select multiple files to make it hidden but unfortunately it remains same 

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3374

### Log File

[debug.log](https://github.com/files-community/Files/files/14776082/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #14900. You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
@ajay-mishra7 is this issue new to v3.3?

**Comment by ajay-mishra7** [comment]
I have not encountered this issue previously because my actions were
limited to hiding and unhiding individual files, rather than attempting to
perform these actions on multiple files simultaneously.

**Comment by yaira2** [comment]
A fix will be included in the next update

**Comment by ajay-mishra7** [comment]
Awesome, thanks for the update! 👍
