### ISSUE TITLE
Feature: Use actual folder icons for breadcrumb flyout

### ISSUE THREAD

**Issue by Draise14** [files-community/Files#15061]
### What feature or improvement do you think would benefit Files?

![image](https://github.com/files-community/Files/assets/35357409/36e700ff-7dba-4b16-9d12-636f11e3ce77)

Make the cookie crumb paths in the header iconography the same as the folder iconography. 

### Requirements

- This proposal will allow for visual "tagging" of folders in a consistent way
- Allows to select folders from cookie crumb paths much quicker

### Files Version

3.3.0.0

### Windows Version

10.0.22635.3350

**Comment by yaira2** [comment]
This improvement will be included in the next release.
