### ISSUE TITLE
 Icon Design in Files Application

### ISSUE THREAD

**Issue by ajay-mishra7** [files-community/Files#15068]
### What feature or improvement do you think would benefit Files?

The utilization of green tick icons on images does not align with the contemporary aesthetic of the application. It imparts a dull impression that contradicts the modernity expected from this new files app. While acknowledging its significance, the icon's design should evoke a more favorable impression.

![Screenshot 2024-03-28 010659](https://github.com/files-community/Files/assets/70057599/64482213-4d7d-4123-9837-1691d0f339fe)

### Requirements

Consider updating the green tick icon on images to a more modern and aesthetic design.

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3374

### Comments

I would appreciate it if you recognize that I am emphasizing this feedback to benefit our files community

**Comment by Josh65-2201** [comment]
Thanks for the feedback, How do you expect a modern tick to look?

**Comment by yaira2** [comment]
The alternative is a check icon with a circle
![image](https://github.com/files-community/Files/assets/39923744/f173d6c6-25c2-41a1-95b1-203afc29b763)

**Comment by ajay-mishra7** [comment]
I have an idea to place a green tick in the right corner of an image.

Please see the attached image for reference, though it is just a rough idea
as I am not a designer😄.

**Comment by Josh65-2201** [comment]
Email attachments don't work. You will have to click the `View on GitHub` link at the bottom of the email > Copy and paste or click the add attachment button to select the file > Wait until you don't see `uploading` in the text > Click the green comment button.

Also I don't think having it in the thumbnail is a good idea as it would block quite a lot of it and the tick would also not be that visible depending on what's in the thumbnail

**Comment by yaira2** [comment]
Thank you for your feedback. We don't have plans to implement this specific request but we'll keep iterating and working on design improvements in this area.
