### ISSUE TITLE
Feature: Add thumbnails consistently to Details, List and Columns view

### ISSUE THREAD

**Issue by Draise14** [files-community/Files#15064]
### What feature or improvement do you think would benefit Files?

![image](https://github.com/files-community/Files/assets/35357409/00796ae3-cff5-46a3-9cbe-d378f231a270)

In Column, List and Details view, files with thumbnails then become icon only. It would be nice if they preserve thumbnails so it's easier to "see" what the files are before selecting (even if small).

![image](https://github.com/files-community/Files/assets/35357409/a5e498b2-a610-4885-8104-b0c483e60522)
This setting should affect all layouts. 

Here is an example where thumbnails toggle even when user has selected "Use Thumbnails" when switching layouts:
https://github.com/files-community/Files/assets/35357409/61bc5bfd-4051-40db-9a4a-b9fc33906eae

### Requirements

- This will keep the "Show Thumbnails" option as a consistent toggle for all layouts per user expectation
- This allow to select files in 3 different layouts without a "select blindly + preview + select blindly + preview.... then work" vs "see + select then work"

### Files Version

3.3.0.0

### Windows Version

10.0.22635.3350

**Comment by Josh65-2201** [comment]
Thanks for the feedback, that's not what the options does, it just mean that thumbnails are allowed to be displayed. Those layouts also don't have enough space to show a thumbnail. They may come back when adding more sizing options for these views

**Comment by Josh65-2201** [comment]
You may also be interested with the info pane (Ctrl + Alt + I) as that can show a preview of the selected file.

**Comment by yaira2** [comment]
It might be a good idea to change the setting to "Always show icons", the only reason it's worded as it is today is to be consistent with the other settings that start with "Show".

**Comment by yaira2** [comment]
It's also worth mentioning that thumbnails will be displayed in the Details View when we add logic to change the dimensions based on the selected size (see #10492),

**Comment by Draise14** [comment]
> You may also be interested with the info pane (Ctrl + Alt + I) as that can show a preview of the selected file.

This unfortunately the preview panel still is "blindly select then preview, blindly select then preview, blindly select..." it is not a good image workflow when working in the other views. This is also inconsistent UX with other explorers. 

Looking forward to the "Always Show Thumbnails" toggle. 

_Thanks for the good work, this Files really is shaping up to be a great alternative to the W11 explorer._
