### ISSUE TITLE
Pin to sidebar not working

### ISSUE THREAD

**Issue by Bismvth** [files-community/Files#15077]
### Description

Sometimes, nothing appears under "Pinned" in the sidebar. The issue survives even after hiding and unhiding the section from the sidebar. When adding new files to the sidebar nothing changes, and they are not added to pinned after rebooting Files (closing with Task Manager and reopening). Though rebooting will make the sidebar appear again, and things can be pinned again.

"Unpin from Sidebar" also doesn't work for Documents or Pictures.

### Steps To Reproduce

It happens only sometimes on launch. Have not been able to reproduce on purpose.

### Requirements

I want the "Pinned" section to appear, containing all the folders that I have previously selected to pin there.
When I click "Pin to Sidebar" I want the folder I clicked to appear on the sidebar, and remain there until I click "Unpin from Sidebar" upon which it will leave the sidebar.

### Files Version

3.3.0.0

### Windows Version

10.0.22621.3296

### Log File

[debug.log](https://github.com/files-community/Files/files/14806865/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, try clearing recent folders in File Explorer settings > `...` > Options > Clear

**Comment by Josh65-2201** [comment]
This seem to be a issue for a lot of users, right now we're tracking this in #15120. You can check there or click subscribe in the right sidebar for updates.

**Comment by ahmedhamdy2121** [comment]
I am experiencing an issue where I am unable to pin any additional folders to the Files sidebar on my device. Although I can unpin folders, I am not able to pin them back to the sidebar. The only available option for me is to pin them to the shelf. Kindly let me know if this problem is unrelated to the topic being discussed, and I will create a new issue to address it. Thanks.

**Comment by Josh65-2201** [comment]
This is a different issue, please make a new bug report for tracking

**Comment by ahmedhamdy2121** [comment]
Okay, will do, thanks for confirming.
