### ISSUE TITLE
Right-click context menu in dark mode unreadable

### ISSUE THREAD

**Issue by TadhgEomonn** [files-community/Files#15074]
### Description

Right-click, context menu in dark mode is unreadable.

### Steps To Reproduce

1. Right-click on a file or folder while in dark mode.
2.  try to read the context menu.

### Requirements

The context menu should use an appropriately visible colored font in the dark mode menu.

### Files Version

3.3.0.0

### Windows Version

10.0.22631

### Log File

[debug.log](https://github.com/files-community/Files/files/14799225/debug.log)

**Comment by 0x5bfa** [comment]
Thanks for the feedback.

Can you send a screenshot?

**Comment by yaira2** [comment]
What happens if you restart Windows? This is actually a known issue in. WinUI but restarting Windows usually solves the issue.

**Comment by TadhgEomonn** [comment]
My apologies. You are correct; the context menu is readable now. Sorry for taking up your time.
