### ISSUE TITLE
Bug: SVG thumbnails causes Files to freeze

### ISSUE THREAD

**Issue by Draise14** [files-community/Files#15072]
### Steps To Reproduce

1. Clear thumbnail cache in Windows
2. Set Files layout to Grid View
3. Go to a folder with various *.SVG files
5. Notice some won't load, and thumbnail generation ultimately stops
6. Thumbnails eventually load and subsequent refreshes work fine once the thumbnails are cached

### Requirements

Avoid freezes

### Files Version

v3.3.0.0

### Windows Version

10.0.22635.3350

### Log File

[debug.log](https://github.com/files-community/Files/files/14796241/debug.log)

**Comment by Josh65-2201** [comment]
This seem more like an issue with power Toys or your Windows install as Files is the only thing having the issue

**Comment by Draise14** [comment]
Files is the only one having issue with the SVG thumbnails. Powertoys with default Explorer works flawlessly.

**Comment by yaira2** [comment]
> This seem more like an issue with power Toys or your Windows install, as Files isn't the only thing having the issue

What else has this issue?

**Comment by Draise14** [comment]
Nothing else per say, after Files hits the issue, the rest of the OS has issues as defined above.

**Comment by yaira2** [comment]
Is this only for svg files?

**Comment by Draise14** [comment]
Correct, only SVG thumbnails from what I know. Could squarely reproduce and turn on/off the issue with that setting from Power Toys.

**Comment by yaira2** [comment]
I don't think this is related to PowerToys as I can repro the issue even without it by clearing the thumbnail cache in Windows and loading a folder with svg files.

**Comment by yaira2** [comment]
Generating svg thumbnails is intensive, so that is probably why the system is slowing down.

I have a fix that'll display a simple icon as a placeholder while the thumbnail is loading but I'm not sure what can be done about the actual thumbnail generation since that's handled by PowerToys.
