### ISSUE TITLE
About tags

### ISSUE THREAD

**Issue by CGlei** [files-community/Files#15081]
### What feature or improvement do you think would benefit Files?

Dear developer, hello. Regarding files, I would like to offer you a functional suggestion.
The tagging function of files is a good feature, but currently it is not intelligent enough, and it is cumbersome to manually tag files every time.
Can you consider adding a feature to automatically label files based on file type or extension?
For example, if I set up MP4 or MKV files in advance and mark them as Video, then when I download an MP4 or MKV, it will automatically mark it as Video, so there is no need to manually label the files, which undoubtedly improves efficiency.
I hope you can consider it, thank you!

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.0.5.0

### Windows Version

10.0.22631.3374

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #11992. You can check there or click subscribe in the right sidebar for updates.
