### ISSUE TITLE
Fullscreen removes the close, minimize and restore buttons

### ISSUE THREAD

**Issue by x-rated** [files-community/Files#15088]
### Description

When i enter fullscreen by hitting F11, close, minimize and restore buttons disappear.

### Steps To Reproduce

1. open the app
2. hit F11

### Requirements

All buttons should remain there.

### Files Version

3.3.0.0

### Windows Version

22635.3420

### Log File

[debug.log](https://github.com/files-community/Files/files/14816566/debug.log)

**Comment by TheChilledBuffalo** [comment]
Uh... isn't that the whole point of fullscreen?

**Comment by yaira2** [comment]
Thank you for your feedback, this is by design. If you prefer to keep these buttons, then you can maximize the window instead of making it full screen.
