### ISSUE TITLE
Bug: Impossible to drag the maximized window by the top border

### ISSUE THREAD

**Issue by x-rated** [files-community/Files#15086]
### Description

When i have the app in maximized window, after hitting top border of the window i cant drag it, instead resizing cursor appears. This also prevents me from closing the app by hitting the top right corner where is the close button.

### Steps To Reproduce

1. open the app in maximized window
2a. hit the top border of the app and press left mouse button to drag
2b. hit the top righ corner of the app and try to close the app

### Requirements

2a: the app should become draggable
2b: the app should close

### Files Version

3.3.0.0

### Windows Version

22635.3420

### Log File

[debug.log](https://github.com/files-community/Files/files/14816547/debug.log)

**Comment by yaira2** [comment]
This is unfortunately a bug in WinUI

**Comment by Jay-o-Way** [comment]
> This is unfortunately a bug in WinUI

Please do explain

**Comment by 0x5bfa** [comment]
https://github.com/microsoft/microsoft-ui-xaml/issues/8805

**Comment by BeaverSoftware** [comment]
I've solved that problem. 
I had this behavior when ExtendsContentIntoTitleBar = true; in winui3
All you need to do is to work with the InputNonClientPointerSource class and the SetRegionRects method where you can set the NonClientRegionKind of the top, left and right borders when in full screen mode.

**Comment by yaira2** [comment]
Thank you for your feedback, the issue reported here is caused by the WinUI framework. There is a report on the WinUI repo https://github.com/microsoft/microsoft-ui-xaml/issues/8805 but as of now this isn't something that can't be fixed from our end. Please consider contributing to that thread by sharing how this issue impacts your experience with the Files app.

**Comment by yaira2** [comment]
Microsoft recently fixed this issue and we'll include the fix in the next version of Files.
