### ISSUE TITLE
copy management

### ISSUE THREAD

**Issue by Cancerlcrh** [files-community/Files#15087]
### What feature or improvement do you think would benefit Files?

Hello, you can add functions similar to teracopy, to reduce the saturation between several threads, and it will prevent the application from crashing.

### Requirements

1.- Reduce copying time between threads
2.- Prevent the app from crashing

### Files Version

3.3.0.0

### Windows Version

10.0.19045.4170

### Comments

Thanks in advance

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Files shouldn't be crashing at all when doing file operations as it uses the same system as Windows File Explorer. if it is for you please open a bug report
