### ISSUE TITLE
Duplicated Quick access tiles

### ISSUE THREAD

**Issue by Vehlore** [files-community/Files#15099]
### Description

The quick access tiles on the Homepage are duplicated, unpinning/pinning the tiles again fixes the issue temporarily but it eventually comes back.

### Steps To Reproduce

1. No known way of reproducing the issue, this is a clean install of Files app

### Requirements

Fix the duplicated appearance of quick access tiles on the homepage

![image](https://github.com/files-community/Files/assets/70699825/b1898e8d-10e4-4e9f-a62b-5522f2cc441b)

### Files Version

3.3.0.0

### Windows Version

Edition	Windows 11 Pro Version	23H2 Installed on	‎22/‎06/‎2023 OS build	22635.3420 Experience	Windows Feature Experience Pack 1000.22700.1003.0

### Log File

[debug.log](https://github.com/files-community/Files/files/14829079/debug.log)

**Comment by 0x5bfa** [comment]
Thanks for the feedback.
We still haven't figured out the reason why but we're tracking this issue in #13555. Closing this issue as duplication but you can learn the further information there clicking Subscribe button from the right pane.
