### ISSUE TITLE
Bug: Opening Files from explorer.exe causes tabs to duplicate

### ISSUE THREAD

**Issue by gumbarros** [files-community/Files#15107]
### Description

WIN+E causes tabs to duplicate. If you have 1 tab, now you have 2. If you have 2, now you have 4, and so goes on.

### Steps To Reproduce

1. Opening 3 tabs
2. Using `Win`+`E`
3. The tabs are duplicated

~~Probably~~ this needs the option "Replace file explorer".

### Requirements

When Files is already opened tabs should remain the same.

### Files Version

3.3.0

### Windows Version

Version	10.0.22631 Build 22631

### Log File

[debug.log](https://github.com/files-community/Files/files/14845629/debug.log)

**Comment by gumbarros** [comment]
Update, managed to crash if you keep going:

https://github.com/files-community/Files/assets/52143624/5eb28cc5-3d8d-4015-b818-d80da8732eb4

**Comment by gumbarros** [comment]
Btw, tried to debug, but WIN+E causes to open the release version, not the VS one :(

**Comment by hishitetsu** [comment]
I was able to reproduce it.

> WIN+E causes to open the release version, not the VS one :(

This is a known issue discussed in https://github.com/files-community/Files/issues/13112.

**Comment by yaira2** [comment]
Let's merge with #13112

**Comment by yaira2** [comment]
> Btw, tried to debug, but WIN+E causes to open the release version, not the VS one :(

@gumbarros, you can change this from Windows Settings > Apps > Default Apps > Files. At the bottom of the page there should be an option for `URL:files-uwp` and you can click it to change to the dev version.

**Comment by hishitetsu** [comment]
@yaira2 the problem is not that Win+E opens another build, but that Win+E doubles open tabs.

**Comment by gumbarros** [comment]
> @yaira2 the problem is not that Win+E opens another build, but that Win+E doubles open tabs.

Exactly, but I think this will help in the debug.
