### ISSUE TITLE
Feature: Add a richer What's New dialog

### ISSUE THREAD

**Issue by 0x5bfa** [files-community/Files#15103]
### What feature or improvement do you think would benefit Files?

Current dialog is too neat for users to understand/ They hardly know function names what caused a crash or bugs.
We can explore the way to create and load xaml from raw json file.
I suggest something like this:

![image](https://github.com/files-community/Files/assets/62196528/93d1f295-8a05-4aea-b8bf-9360ddb25ead)

### Requirements

- Add a richer What's New dialog

### Files Version

3.3

### Windows Version

10.22000.0

**Comment by 0x5bfa** [comment]
Save this in https://github.com/files-community/Release-Notes and fetch the latest json to Files app.
```json
{
  "WhatsNew": {
    {
      "Title": "Redesigned layout picker",
      "Description": "We refreshed the layout picker with a cleaner and more functional design. The layout options are now displayed in a single row with large buttons, and the selected layout is highlighted using the system accent color.\r\n\r\nBeneath the the layout section, we added a slider to control the item sizes of the various views including Details, List, Grid, & Columns. Whether you prefer larger or smaller items, there is an option for your personal preference."
      "FooterLink": "https://files.community/docs/features/layout-picker"
    }
    {
      "Title": "Thumbnail performance and DPI support",
      "Description": "In v3.3, we continued working on thumbnail handling. While there is always room for improvement, you can anticipate a more reliable experience with fewer overall issues related to thumbnails.\r\n\r\nWhen a thumbnail takes longer to load, a shimmer animation will be displayed to indicate that the content is loading. Additionally, we added DPI support for icons on the home page, tabs, and left-hand sidebar."
    }
    {
      "Title": "Added a settings page to manage layout preferences",
      "Description": "We added a new settings page to simplify the management of your layout preferences. These options, formerly nested within submenus on the “Folders” settings page, are now more accessible and easier to locate. Additionally, the “Folders” page was renamed to “Files & folders”."
    }
    {
      "Title": "Continue where you left off when restarting Windows",
      "Description": "Continue where you left off now works when Windows is restarted. Previously this feature only worked if you closed Files before restarting Windows."
    }
  }
}
```

**Comment by yaira2** [comment]
> They hardly know function names what caused a crash or bugs

This is a fair point. I'll still include them in the blog post, but I'll stop adding them to the update popup.

Aside from that, what are the goals that you want to accomplish here?

**Comment by 0x5bfa** [comment]
Regarding feature requests, instead of "Introduced a new Layout Picker", we should tell users "The redesigned layout options" or something similar. This also can be said for "Integrated settings into tabs" instead of "Feature: Replace the settings dialog with tabs"

**Comment by 0x5bfa** [comment]
We can have a json file that represents them, parse it and load as XAML. Linking to a docs is also important requirement to be met.
