### ISSUE TITLE
Top title bar not adjusted to screen

### ISSUE THREAD

**Issue by Vehlore** [files-community/Files#15100]
### Description

Maximizing the application and bringing the mouse along to the top edge of the screen (to close the app on the X button, for example) shows the resize toggle on the mouse, making it annoying to h-ave to bring the mouse down a few pixels to close the window or switch between tabs. 

Unable to add a screenshot since mouse will not show in it.

This doesn't happend on the bottom edge of the app.

### Steps To Reproduce

1. Open the app
2. Maximize the window
3. Bring the mouse to the top edge of the screen to close the window

### Requirements

Fix the allignment of the maximized window to not show the resize 

### Files Version

3.3.0.0

### Windows Version

Edition	Windows 11 Pro Version	23H2 Installed on	‎22/‎06/‎2023 OS build	22635.3420 Experience	Windows Feature Experience Pack 1000.22700.1003.0

### Log File

[debug.log](https://github.com/files-community/Files/files/14829129/debug.log)

**Comment by yaira2** [comment]
Thank you for the report, this is currently a limitation in WinUI but we're tracking it here #15086.
