### ISSUE TITLE
Issue with Black Screen when Opening 'This PC' or 'Users' Files from Desktop

### ISSUE THREAD

**Issue by ajay-mishra7** [files-community/Files#15101]
### Description

When opening 'This PC' or 'Users' files from the desktop, a brief period of a completely black screen occurs before the normal screen appears.

### Steps To Reproduce

Navigate to the desktop of the system.
Double-click on the "This PC" icon or the "Users" folder icon.
Observe the screen closely as the action is performed.
Note the appearance of a complete black screen for a few seconds before the normal screen appears.

### Requirements

Ensure that when opening "This PC" or "Users" files from the desktop, the transition to the respective screen occurs smoothly without any significant delay or appearance of a black screen. Users should be able to access these folders seamlessly without experiencing any disruptions in the display.

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3374

### Log File

[debug.log](https://github.com/files-community/Files/files/14832638/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for thew report, I sound like Files is starting in with case there isn't anything Files can do as the contents need to load

**Comment by yaira2** [comment]
Do you have the option to keep Files running in the background enabled?

**Comment by ajay-mishra7** [comment]
Yes, it's enabled.

**Comment by yaira2** [comment]
We have been unable to reproduce this issue internally, however, we acknowledge that it has been reported on certain devices. It appears to be related to the WinAppSdk framework, which is beyond our direct control. At the same time, this also means that a fix can be added in future updates to the framework
