### ISSUE TITLE
UX: Opening file in new tab from right click context menu after search shouldn't be possible

### ISSUE THREAD

**Issue by Draise14** [files-community/Files#15104]
## Steps
![Files_y5Zyxhyzb1](https://github.com/files-community/Files/assets/35357409/e7c503f8-7e01-462e-9b58-82b7154acbdf)
## Result
![Files_aiesdeLmre](https://github.com/files-community/Files/assets/35357409/c9ffb159-e05e-4a8f-9e6e-bd6c3bb9cee6)

Right now you can "open file in new tab" from search results. This doesn't make too much sense since these are files, and this is a folder browser. 

## Expected UX
Ideally you should not be able to right click and open a file in window or tab, but instead "Open in Editor" or something similar. 

### Steps To Reproduce

1. Search in a folder that has files (python is a good one to test here)
2. Right click on the result
3. Click "Open in New Tab"
4. Tab loads then throws a notice/error

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.3.0.0

### Windows Version

10.0.22635.3420

### Log File

[debug.log](https://github.com/files-community/Files/files/14841560/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #14058. You can check there or click subscribe in the right sidebar for updates.
