### ISSUE TITLE
Bug: Crash after drag and drop on the addresses bar

### ISSUE THREAD

**Issue by MarathonMax** [files-community/Files#15105]
### Description

Crash after drag and drop

### Steps To Reproduce

Tried to move a folder to address bar (trying to go up a level in the folder structure). That was not allowed. Then tried to move the folder down a level (because it had somehow moved up a level) and app crashed. Note that I had previously invoked the app with the key combination: WIN-E which btw caused all three opened tabs to duplicate.

### Requirements

- e.g. Fix crash that occurs when...
Fix crashing issue

### Files Version

3.3.0.0

### Windows Version

W11 23H2

### Log File

[debug.log](https://github.com/files-community/Files/files/14841620/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, 
- Can you add the steps to reproduce.
- Are you using the grid layout?

**Comment by MarathonMax** [comment]
Hmmm, I thought that my staps were ok. Sure, not labeled as 1, 2, 3 but pretty much that. Using Detail view.

**Comment by Josh65-2201** [comment]
I can't reproduce the issue, moving a folder/file to the address bar does let you move it there and hovering over that will open the folder.

> WIN-E which btw caused all three opened tabs to duplicate
You should make a separate bug report for this

**Comment by gumbarros** [comment]
> WIN-E which btw caused all three opened tabs to duplicate.

I can also confirm this behavior.

**Comment by yaira2** [comment]
I've located this crash in Sentry https://files-org.sentry.io/issues/5533201465/events/f1b55a6279ce473eb3a0a4bb658e419f/
