### ISSUE TITLE
Bug: File extensions are not displayed in Recent files widget

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#15108]
### Description

Regardless of the extension display setting, file extensions are always not displayed in Recent files widget.
![image](https://github.com/files-community/Files/assets/66369541/ce33922b-6807-4dc0-8bfb-3a3c1b8891b9)

### Steps To Reproduce

Open Recent files widget and see file names.

### Requirements

File extensions should be displayed if the extension display setting is on.

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3296

### Log File

n/a

**Comment by yaira2** [comment]
For what it's worth, they are displayed in the full path.

**Comment by hishitetsu** [comment]
> For what it's worth, they are displayed in the full path.

Yes, but it is often too long to display the extension.
