### ISSUE TITLE
Add the ability to have individual layout settings for each folder

### ISSUE THREAD

**Issue by AngryDavid808** [files-community/Files#15112]
### What feature or improvement do you think would benefit Files?

I can't seem to find a way to personalize how I want each folder to look like, every time I change layout options for a folder, it affects the entire interface, or keeps defaulting back to adaptive layout whic is the default option. I use this feature a lot in Windows's File Explorer and I think it'd be amazing to have the ability to choose what each folder looks like, adding varity to the appearance of folders and also making it useful to differenciate among certain folders upon first look instead of having to look at the navigation bar.
![image](https://github.com/files-community/Files/assets/65258039/101df1b0-ba86-41f8-ab85-1b80ff1b0380)

### Requirements

- Add an option to customize how each folder looks like
- Make the option accessible through the layout drop-down menu as well as the layout section in settings
- Alternatively, an option to save layout settings for said specific folder could be implemented and added to the drop-down menu

### Files Version

3.3.0.0

### Windows Version

10.0.19045.4170

**Comment by Josh65-2201** [comment]
You can turn off adaptive layout in layout picker and you can change what layout a folders using there too
![image](https://github.com/files-community/Files/assets/26977075/cddcb3bc-a64f-4344-99b3-36b70a8f8873)

**Comment by AngryDavid808** [comment]
I have it turned off here. Still doesn't allow me to have individual settings.
![image](https://github.com/files-community/Files/assets/65258039/5abea1fe-4048-430f-81ff-91e14944e104)

**Comment by Josh65-2201** [comment]
Are you changing the size of grid view or the actual layouts?

**Comment by yaira2** [comment]
Try toggling the option for syncing preferences on & off to will reset the existing database.

**Comment by AngryDavid808** [comment]
> Are you changing the size of grid view or the actual layouts?

Mostly both, I actually change both to my liking

**Comment by AngryDavid808** [comment]
> Try toggling the option for syncing preferences on & off to reset the existing database.

Had that on then turned it off before issuing the request, but will try that now

**Comment by AngryDavid808** [comment]
Okay, I'm back! Just toggled the option for syncing preferences on & off and tried messing around again. It remembers the layout option for each folder just fine, it's just that the size of the icons specified for each layout that's not specific for each folder. I can have different layouts, just not different sizes.

**Comment by yaira2** [comment]
> it's just that the size of the icons specified for each layout that's not specific for each folder. I can have different layouts, just not different icon sizes. 

We'll continue to monitor feedback in this area but as of now we don't plan to support individual icon sizes in different folders.

**Comment by yaira2** [comment]
I’d like to clarify that this is just a reflection of our current plans for this feature. If we see more feedback expressing interest we’re open to reconsidering this.

**Comment by AngryDavid808** [comment]
Understood! Thanks for your input and help. ☺️
