### ISSUE TITLE
Option for opening upon start up without a new window opening/ Option for background start up

### ISSUE THREAD

**Issue by blueciffer56** [files-community/Files#15117]
### Option for files to open on startup without a new window opening/ Option for just background startup

Could we get an option for files to open in the background upon startup please? Files still takes about 10-15 seconds to start when it's not already running in the background after you close a window. I have to restart my PC quite often for development reasons. You can have Files startup but the opens a window that I don't need at that moment.  

### Files Version

3.3.0.0

### Windows Version

10.0.22621.3296

**Comment by Josh65-2201** [comment]
Thanks for the feedback, you already can by turning on Files settings > Advanced > `Open Files on Windows startup` and `Leave app running in the background when the window is closed`
