### ISSUE TITLE
Bug: Sort doesn't work by clicking a header

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#15121]
### Description

Sort doesn't work by clicking a header of the file list in the details layout. Nothing happens when clicking a header.

### Steps To Reproduce

1. Click a header of the file list in the details layout.
2. Nothing happens.

### Requirements

Sort files and folders when clicking a header.

### Files Version

3.3.1.0

### Windows Version

10.0.22621.3296

### Log File

n/a

**Comment by Josh65-2201** [comment]
Try doing clicking it multiple times, It's likely the same as #14685

**Comment by hishitetsu** [comment]
I don't think so. No matter how many times I click, it doesn't work.
This problem doesn't occur in v3.3.0.

**Comment by Josh65-2201** [comment]
Though I updated before testing. I can reproduce it now
