### ISSUE TITLE
Bug: Crash at 3.3.1 when saving"Sync layout and sorting preferences across directories option"

### ISSUE THREAD

**Issue by gumbarros** [files-community/Files#15124]
### Description

The apps crashes at 3.3.1 when saving"Sync layout and sorting preferences across directories option".

### Steps To Reproduce

1. Open settings
2. Toggle "Sync layout and sorting preferences across directories"

### Requirements

Fix crash that occurs when the option is saved.

### Files Version

3.3.1-preview

### Windows Version

Version	10.0.22631 Build 22631

### Log File

[debug.log](https://github.com/files-community/Files/files/14891330/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.
