### ISSUE TITLE
Bug: Opening explorer.exe from Start Menu causes Driver unplugged dialog

### ISSUE THREAD

**Issue by gumbarros** [files-community/Files#15127]
### Description

![image](https://github.com/files-community/Files/assets/52143624/65001d64-3fe2-4493-97e4-90ba7a1c01b7)
![image](https://github.com/files-community/Files/assets/52143624/f622bda4-6bc9-4ed1-bca5-2666ffa32099)

### Steps To Reproduce

1. Open explorer.exe from Start Menu
2. NotAFolder dialog appears 

### Requirements

- Files should just open with no dialog.

### Files Version

3.3.1-preview

### Windows Version

10.0.22631.3374

### Log File

Nothing worth, but here is the log:

[debug.log](https://github.com/files-community/Files/files/14892077/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, is this only the case when Files is set to start with This PC

**Comment by gumbarros** [comment]
More info: Also happening when opening from other places and tabs are duplicating like #15107

**Comment by yaira2** [comment]
Is this also in issue in v3.3?

**Comment by gumbarros** [comment]
> Is this also in issue in v3.3?

![image](https://github.com/files-community/Files/assets/52143624/08421097-4f0e-41e9-b70a-b8c04431d1d6)

Yes

**Comment by Josh65-2201** [comment]
@gumbarros Can you see if this is still an issue in the preview version. https://files.community/download. I can't reproduce it and it open This PC like normal

**Comment by gumbarros** [comment]
After a fresh install, everything is fine
