### ISSUE TITLE
Bug: Pinned items don't to load due to recent folders

### ISSUE THREAD

**Issue by kemar-christie** [files-community/Files#15120]
### Description

Ok, so at times when i open the app. The pinned tab is closed and when clicking the arrow to expand it doesn't expand. I have to force close the app from the side bar and reopen again for it to show the pinned tab expanded and working.
![Screenshot 2024-04-05 114839](https://github.com/files-community/Files/assets/75957251/a041f467-de94-4384-883d-eafb585bb7f9)

![Screenshot 2024-04-05 114844](https://github.com/files-community/Files/assets/75957251/9bf70d0e-7d25-4326-bbb5-4bc2c36e0990)

### Steps To Reproduce

Its random at certain times it happens.

### Requirements

- Fix error it seems like a bug

### Files Version

3.3.0.0

### Windows Version

Edition: Windows 11 Pro Version 23H2,  OS build 22631.3374, Experience Windows Feature Experience Pack 1000.22688.1000.0

### Log File

[debug.log](https://github.com/files-community/Files/files/14888072/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

right now you try clearing recent folders in File Explorer settings > ... > Options > Clear and disabling `show recent folders` in that same menu

**Comment by kemar-christie** [comment]
Great.

**Comment by Josh65-2201** [comment]
I have just found there already an issue open #13116. You can check there or click subscribe in the right sidebar for updates.

**Comment by kemar-christie** [comment]
oh so their is one already ok thanks for the update
