### ISSUE TITLE
Bug: At 3.3.1 the layout of "Layout Type" is wrong

### ISSUE THREAD

**Issue by gumbarros** [files-community/Files#15123]
### Description

Release:
![image](https://github.com/files-community/Files/assets/52143624/0aec8851-777f-42f7-8eef-43cfe64067c0)
Preview:
![image](https://github.com/files-community/Files/assets/52143624/208ebd8a-566d-4d5d-a43d-424f620dd5c9)

### Steps To Reproduce

1. Open settings
2. Check Layout->Layout Type

### Requirements

Layout should be like the release version.

### Files Version

3.3.1-preview

### Windows Version

11

### Log File

Not related.

### Additional info
My resolution is 1920x1080 with 1.5x scale, I don't know if this helps.

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by gumbarros** [comment]
![image](https://github.com/files-community/Files/assets/52143624/63005af8-689d-416f-9462-46262c6ea0fd)

I think this is an WinUI issue, everything is fine today (I turned off my computer at night)
