### ISSUE TITLE
Slower than frozen snot (3.3.0.0 - installer pkg) and it interferes with ProcExplorer

### ISSUE THREAD

**Issue by whawn1** [files-community/Files#15122]
### Description

It's slow -- very slow.  And I got a notice upon opening that, because it was running as admin, drag and drop wouldn't work (WTF???) and sure 'nough, drag-n-drop doesn't work.  Also, the app or perhaps only the installer interferes with Process Explorer -- somehow removing all text from the data window but leaving the color coding behind.  

### Steps To Reproduce

install 3300 from installer package
wait a long time
observe notice re: admin drag-n-drop failure
open ProcExplorer to kill process
all text missing from procexp!
use task manager to kill process from background processes
that doesn't work -- still running
finally able to kill it, once it showed up on the 'apps' tasklist
uninstall Files 3.3.0.0!

### Requirements

- e.g. Fix crash that occurs when...
The the app wold work pretty well

### Files Version

3.3.0.0

### Windows Version

10.0.19045.3693

### Log File

Upon attempting to include the log file, got this error msg:
```---------------------------
Visual Studio Just-In-Time Debugger
---------------------------
An unhandled exception occurred in [3688] PowerToys.MonacoPreviewHandler.exe. Just-In-Time debugging this exception failed with the following error: No installed debugger has Just-In-Time debugging enabled. In Visual Studio, Just-In-Time debugging can be enabled from Tools/Options/Debugging/Just-In-Time.

Check the documentation
[debug.log](https://github.com/files-community/Files/files/14890434/debug.log)
 index for 'Just-in-time debugging, errors' for more information.
---------------------------
OK   ---------------------------
Visual Studio Just-In-Time Debugger
---------------------------
An unhandled exception occurred in [3688] PowerToys.MonacoPreviewHandler.exe. Just-In-Time debugging this exception failed with the following error: No installed debugger has Just-In-Time debugging enabled. In Visual Studio, Just-In-Time debugging can be enabled from Tools/Options/Debugging/Just-In-Time.

Check the documentation index for 'Just-in-time debugging, errors' for more information.
---------------------------
OK   
---------------------------

---------------------------
and this one:
---------------------------
PowerToys.MonacoPreviewHandler.exe - Application Error
---------------------------
The exception unknown software exception (0xe0434352) occurred in the application at location 0x00007FFE7CABCF19.


---------------------------
OK   Cancel   
---------------------------```

**Comment by Josh65-2201** [comment]
Thanks for the report, you haven't said anything specific.
- Drag and drop doesn't work because of Windows issues and would crash Files otherwise.
- Why did you kill Files with Process Explorer? 
- The text being missing wouldn't likely be from Files alone.

**Comment by whawn1** [comment]
Without DnD the app is worthless
killed app w/proc Exp because I wanted it DEAD
Yes, it was Files, alone.
Then why did it show ONLY when I tried to insert the log into the Git hub form?

Have a good day

Won't be back

**Comment by Josh65-2201** [comment]
Sorry for you bad experience but you can enable drag and drop by enabling UAC (type User account control in the start menu > set it to the 3rd level from the bottom > Restart your computer) and not running Files as admin if you are (you don't need to anyway). If you don't have any other specific issue or not willing to give the information needed to fix it then we won't be able to help you

**Comment by yaira2** [comment]
Thank you for your feedback, there is a limitation in the WinUI framework that prevents drag & drop from working properly when the process is running as admin. Unfortunately, this also happens when user account control is disabled even if the app isn't running as admin. Microsoft is aware of this issue and they recently shared that they are working to address this limitation, but this is out of our hands and no timeline was provided.

I'm closing this issue for now as a workaround has been provided (enabling UAC) and because the limitation is from WinUI.
