### ISSUE TITLE
After file transfer the program usable/no trash can access either/ the file dose not update 

### ISSUE THREAD

**Issue by Honeybeefox** [files-community/Files#15132]
### Description

After file transfer the program usable/no trash can access either/ the file dose not update in the drives or in any folders after deleting a file

### Steps To Reproduce

After file transfer the program usable/no trash can access either/ the file dose not update in the drives or in any folders after deleting a file

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

2.0.34.0

### Windows Version

10

### Log File

No log file

**Comment by Josh65-2201** [comment]
Thanks for the report, Please update to 3.3.0.0 to continue receiving support https://files.community/docs/install#:~:text=Keep%20Files%20up%20to%20date. If this is still an issue please comment here
