### ISSUE TITLE
Ability of checking updates actively

### ISSUE THREAD

**Issue by hez2010** [files-community/Files#1513]
**Describe the solution you'd like**
An app can check for updates actively and request silent downloads and installation, see 
https://docs.microsoft.com/en-us/windows/uwp/packaging/self-install-package-updates.
It can keep users who disabled Automatically Update in Microsoft Store up-to-date, and it can also inform users about the up-coming update contents.

I think it's helpful for improving user experience.

**Comment by Jaiganeshkumaran** [comment]
Don't do this. I don't want Files UWP to become an app that keeps asking to install updates.

**Comment by hez2010** [comment]
@Jaiganeshkumaran I can give an option in settings for whether enable it or not.

**Comment by Thomas1664** [comment]
@yair100 Can you assign me?

**Comment by yaichenbaum** [comment]
@Thomas1664 Sure. Please make sure it is done in a way we can easily disable it in case we ship the app outside of the store as well.

**Comment by jaigak** [comment]
@yair100 This is the worst proposal ever. Microsoft Store exists so that apps don't need to worry about updates. Files is a store app, not a sideloaded app

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran Providing alternatives for users who do not have access to the store is part of the plan for the future.

**Comment by Jaiganeshkumaran** [comment]
But this is about checking updates for the store version. This shouldn't be done

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran Users should be informed about updates without having to open the Microsoft Store. This will help users stay up to date.

**Comment by Jaiganeshkumaran** [comment]
Provide an option called Check for updates like what Feedback Hub. Not a periodic 'Task'

**Comment by jaigak** [comment]
@yair100 This is a store app. Updates are performed automatically by Windows. To inform users, show a dialog after an update.

**Comment by Jaiganeshkumaran** [comment]
When Windows already checks for app updates, why should we? It is annoying to see apps asking for updates. Windows Store apps are better because updates are only applied after you are done with it.

**Comment by yaichenbaum** [comment]
@Thomas1664 It looks like there is a way to check if an update is mandatory, perhaps we should only check for updates if they are mandatory. Doing this will help make sure the app is updated if a critical update was sent out.

**Comment by Thomas1664** [comment]
@yair100 seems like you need to create a [Package Flight](https://docs.microsoft.com/en-us/windows/uwp/publish/package-flights) to enable me working on this according to [this issue](https://github.com/microsoft/WinDev/issues/22).
However, I can still work on it, but you need to test and may change the code afterwards.

**Comment by yaichenbaum** [comment]
@Thomas1664 We can use the beta testing flight group to test these changes, let me know when you are ready to submit the update.

**Comment by Thomas1664** [comment]
@yair100 I'm ready for testing.

**Comment by yaichenbaum** [comment]
@hez2010 The next release of Files will start checking if there are mandatory updates when launching the app. It won't force the user to install them, but it will inform them that it's available and give them the option to download it. @Thomas1664 Thank you for implementing this great feature!
