### ISSUE TITLE
No Pinned Shortcuts after Windows cold boot

### ISSUE THREAD

**Issue by Drakah** [files-community/Files#15135]
### Description

After every Windows boot up in the morning and launch Files, there are no Pinned files on the left populating at all, actually for anything at all except for the general items. Pinned is completely grey'd out and inaccessible. Drives and Cloud Drives are there. Network is there but only the word. Tags is completely grey'd out as well.

If I go into Task Manager and "End Task" Files, then re-launch it, all of the Pinned files come back as normal again.

### Steps To Reproduce

Enable the Files APP "Open Files on Windows Startup" and Cold boot the computer.

### Requirements

Files APP should open correctly on opening when you first open the APP after Windows startup. Currently it does not and you have to manually End Task the APP to get it to work again to reload it.

### Files Version

3.3.0.0

### Windows Version

10.0.19045.4239

### Log File

[debug.log](https://github.com/files-community/Files/files/14897433/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #13116. You can check there or click subscribe in the right sidebar for updates. There is also a workaround you can try listed at the top
