### ISSUE TITLE
Bug: Permanently delete doesn't work all the time

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#15133]
### Description

Currently when trying the prompt show and the permanently delete box is check after running the file/folder will disappear and Status center show it was successful. But refreshing the folder will show the file/folder again. 
Sometimes it also only delete the bottom most selected file and no the others.

### Steps To Reproduce

1. Select a file/folder
2. Shift delete
3. See prompt shown with check mark enabled
4. See file/folder looks deleted
5. Refresh folder

### Requirements

- permanently delete file/folder when checked

### Files Version

3.3.1.0

### Windows Version

10.0.22621.3374

### Log File

[debug.log](https://github.com/files-community/Files/files/14895620/debug.log)

**Comment by yaira2** [comment]
@Josh65-2201 is this also an issue in v3.3?

**Comment by hishitetsu** [comment]
I was able to reproduce it. I think its priority is urgent.

**Comment by Josh65-2201** [comment]
No 3.3.0.0 works as expected

**Comment by hishitetsu** [comment]
This appears to be caused by #14911.
@hez2010 can you take a look?

**Comment by yaira2** [comment]
> This appears to be caused by #14911. @hez2010 can you take a look?

That was my thought as well, it's a substantial change so issues like this are expected. The main thing is to identify the issues as soon as possible so we can patch them before releasing to stable.

**Comment by hez2010** [comment]
SetTags doesn't allow passing a null array to its `tags` parameter.
Note that CsWinRT with out-of-process server doesn't support passing null to an array parameter as well. 
We need to update all `SetTags(.., .., null)` to `SetTag(.., .., [])`.

**Comment by hishitetsu** [comment]
> We need to update all SetTags(.., .., null) to SetTags(.., .., []).

This may need to be fixed, but I think the `SetTags` error is a different issue, as I don't see any logs when the deletion fails in my environment.
@Josh65-2201 do you know when `System.Runtime.InteropServices.COMException (0x800706F4)
` occurred?

**Comment by Josh65-2201** [comment]
No

**Comment by hez2010** [comment]
> > We need to update all SetTags(.., .., null) to SetTags(.., .., []).
> 
> This may need to be fixed, but I think the `SetTags` error is a different issue, as I don't see any logs when the deletion fails in my environment. @Josh65-2201 do you know when `System.Runtime.InteropServices.COMException (0x800706F4) ` occurred?

It's the same issue.

```
System.Runtime.InteropServices.COMException (0x800706F4)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Files.App.Server.Database.IFileTagsDatabaseClassMethods.SetTags(IObjectReference _obj, String filePath, Nullable`1 frn, String[] tags)
   at Files.App.Utils.Storage.FileOperationsHelpers.<>c__DisplayClass17_1.<UpdateFileTagsDb>b__0()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions(Action action, ILogger logger, Type exceptionToIgnore)
```

Here we are calling `ABI.Files.App.Server.Database.IFileTagsDatabaseClassMethods.SetTags` which is calling the server method `SetTags` from the client. And either the calling itself failed or `SetTags` throws any exception will lead to `COMException` on the client without any additional exception message.

**Comment by hishitetsu** [comment]
Weird. The logs are not output in my environment, but surely fixing this solves the issue.
 I'll submit a PR. Thank you @hez2010!
