### ISSUE TITLE
Option to use "native" (wider) scrollbars

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [files-community/Files#15137]
### What feature or improvement do you think would benefit Files?

I put "native" into quotes because since this is written in C#, the existing scrollbars are probably native. What I mean is making it possible for the scrollbars to look and feel (or at least as wide) as those in Explorer, Task Manager, etc.

My personal use case: Due to RSI, I can't use scroll wheels and thin scrollbars are more difficult to grab with a Wacom pen.

### Requirements

- There is an option to use "native" (wider) scrollbars

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3296

### Comments

This screenshot compares scrollbar widths of Waterfox, Explorer and Files:
![Screenshot 2024-04-07 215430](https://github.com/files-community/Files/assets/16936908/0e693027-2443-435d-90fd-80fd802b0a01)

**Comment by yaira2** [comment]
Thank you for your feedback, Files uses the default scrollbars from WinUI and we don't have plans to change this. That said, we recommend sharing this feedback with Microsoft on the WinUI repo so that they can take your feedback into account.

**Comment by s-h-a-d-o-w** [comment]
Understandable, thanks.

(They've apparently gotten a lot of negative feedback over two years ago already but aren't bothered by it: https://github.com/microsoft/microsoft-ui-xaml/discussions/7422 )

**Comment by yaira2** [comment]
> Understandable, thanks.
> 
> (They've apparently gotten a lot of negative feedback over two years ago already but aren't bothered by it: [microsoft/microsoft-ui-xaml#7422](https://github.com/microsoft/microsoft-ui-xaml/discussions/7422) )

It's also worth pointing out the discussion you linked was started by a Microsoft employee.

**Comment by s-h-a-d-o-w** [comment]
Who said that they have no immediate plans to get to that. I noticed. 😄

It's a very common problem that managers only tend to care about new features, most engineers don't find addressing problems sufficiently exciting and sometimes, designers find it more important to actualize their aesthetic visions rather than provide UX that works well and is consistent.

**Comment by 0x5bfa** [comment]
They were moving forward.

https://github.com/microsoft/terminal/issues/9218#issuecomment-1349890391
