### ISSUE TITLE
Bug: Second item in sub menu is selected first when using arrow key navigation

### ISSUE THREAD

**Issue by andrew-james-heard** [files-community/Files#15138]
### What feature or improvement do you think would benefit Files?

file > context button or right-click > Open with (has focus) > right-cursor > submenu is displayed but nothing has focus...
but to give keyboard focus to the 1st item in the list I now have to press cursor-down (2nd item is selected), cursor-up (1st item is selected)
in other words it takes 1 less key to select the 2nd item than the 1st
I haven't discovered any other way from the keyboard to more efficiently select the 1st item in the sub-menu

### Requirements

* give 1st item in the sub-menu focus when cursor-right is pressed?

### Files Version

3.3.0.0

### Windows Version

11 23H2

**Comment by 0x5bfa** [comment]
Thanks for the feedback. I can repro.

https://github.com/files-community/Files/assets/62196528/f4ac0be4-f3fe-468f-b3c9-14e9ded5544f

**Comment by andrew-james-heard** [comment]
Thanks for the video - exactly. I wasn't going to presume it was a bug.

**Comment by yaira2** [comment]
File Explorer has the same bug so I assume this needs to be fixed by WinUI.

**Comment by andrew-james-heard** [comment]
confirmed same with Explorer ;-(
fixed by WinUI assuming both programs use the same menu handling code (but sounds like they do)

**Comment by yaira2** [comment]
Can you open a report on the WinUI repo?

**Comment by andrew-james-heard** [comment]
WinUI? official Windows User Interface? I have no idea how sorry. Suggestion?

**Comment by yaira2** [comment]
My apologies, WinUI is the UI framework used in Files https://github.com/microsoft/microsoft-ui-xaml/issues.

**Comment by andrew-james-heard** [comment]
I've created https://github.com/microsoft/microsoft-ui-xaml/issues/9519

**Comment by yaira2** [comment]
Thank you Andrew, once this is resolved with WinUI, we should be able to take the fix for Files.

I think we can close this issue now as it's being tracked on the WinUI repo.
