### ISSUE TITLE
Sidebar and home page fixed file option lost

### ISSUE THREAD

**Issue by BeautyLaTeX** [files-community/Files#15134]
### Description

Sidebar and home page fixed file option lost.
![Snipaste_2024-04-07_16-41-27](https://github.com/files-community/Files/assets/38369557/09176ae7-50c3-4be2-8ce3-bdf322a93169)
![Snipaste_2024-04-07_16-41-40](https://github.com/files-community/Files/assets/38369557/b599c47f-26a0-4c93-8475-15334b9a996e)

### Steps To Reproduce

I do not known, it is a problem.

### Requirements

Fix crash

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3374

### Log File

[debug.log](https://github.com/files-community/Files/files/14896488/debug.log)

**Comment by 0x5bfa** [comment]
Thank you for the feedback.
This seems one of the most common issue. We're tracking this issue in https://github.com/files-community/Files/issues/13116, and you can learn more info there or click Subscribe button in the right sidebar to get up-to-date.
