### ISSUE TITLE
My Files Crash when I open folders

### ISSUE THREAD

**Issue by Dansking54** [files-community/Files#15157]
### Description

My Files doesn't stop crashing randomly when I open folders with it and it's not on a specific folder but it happens completely randomly but it's when I do an action on it

### Steps To Reproduce

open Files
and do any action that is not related to the app settings

### Requirements

- e.g. Fix crash that occurs when... when I open folders with

### Files Version

when I open folders with

### Windows Version

22H2

### Log File

![image](https://github.com/files-community/Files/assets/97561780/63a58cef-2d7c-4014-90a2-1cca1b9bab87)

**Comment by Josh65-2201** [comment]
Thanks for the report, 
- What do you mean by action?
- What is your Files version. Files settings > About
- Can you please upload (Do not copy and paste content) the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.
