### ISSUE TITLE
Command palette not opening.

### ISSUE THREAD

**Issue by electricsteve** [files-community/Files#15153]
### Description

When pressing my command palette keybind (Ctrl+Shift+P) nothing happens, it just won't show up. I also manually set the command palette keybind: 
![image](https://github.com/files-community/Files/assets/96793824/19cc84d9-7880-4ae9-bd16-faa936cc1774)
Also i just realised that the +'s became \u002B is that normal?

### Steps To Reproduce

1. Install the program
2. Try the keybind, doesn't work
3. Manually set the keybind
4. Also doesn't work

### Requirements

The command palette opens

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3296

### Log File
[debug.log](https://github.com/files-community/Files/files/14935942/debug.log)

I did censor my school name before i accidentally dox myself.

(Also sorry if my spelling is incorrect, I'm dutch so my main language isn't English and I'm dyslectic)

Edit: missed 1 censor

**Comment by Josh65-2201** [comment]
Thanks for the report, `Ctrl + Shift + P` is the default and doesn't need to be added as a custom shortcut.
Where are you trying to open the command palette
Make sure Files is focused when trying to use the shortcut

**Comment by electricsteve** [comment]
- Ok, i removed it
- It is focused
- With file selected and with just nothing selected

**Comment by Josh65-2201** [comment]
What's you keyboard layout? As it works for me in English UK and US

**Comment by electricsteve** [comment]
![image](https://github.com/files-community/Files/assets/96793824/58ad788b-ef52-4e99-8d6d-012f528dd10e)
I also tested it in VScode, and there the keybind also doesn't work, so i'm tryin to figure out if another program is 'stealing' the keybind.

**Comment by electricsteve** [comment]
Welp, can't find it. I even tried booting in safe mode, but it still didn't work

**Comment by Josh65-2201** [comment]
You can try change the key bind to something other than `Ctrl + Shift + P` using the actions docs you used before.

**Comment by electricsteve** [comment]
Yep, rebinding works. Seems to be a pc issue.
