### ISSUE TITLE
Bug: File with double extensions don't open correctly

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#15164]
### Description

I have only test this with `.zip.txt` but I assume to affects others too.

### Steps To Reproduce

1. Create txt file with `.zip.txt` extension
2. Open file
3. VS code shows the path is

![image](https://github.com/files-community/Files/assets/26977075/2d2a6b05-bf63-4a86-a0f9-baef7a2201ab)

When it should be
![image](https://github.com/files-community/Files/assets/26977075/e80354b2-bd44-42a4-8816-dfb3d5ce5b0d)

### Requirements

- Make sure to only open files as the last extension type (.txt)

### Files Version

3.3.1.0

### Windows Version

10.0.22621.3387

### Log File

[debug.log](https://github.com/files-community/Files/files/14961949/debug.log)

**Comment by yaira2** [comment]
thank you for the report

**Comment by yaira2** [comment]
@Josh65-2201 I can't repro this in v3.6. Is this still an issue for you?

**Comment by Josh65-2201** [comment]
Still an issue with 3.6.11, I found that it only happens if I have a `.zip` file with the same name in the same folder with the `.zip.txt` one

**Comment by yaira2** [comment]
A fix will be included in the next release.
