### ISSUE TITLE
Bug: Can't open the recycle bin

### ISSUE THREAD

**Issue by T-i-a-7** [files-community/Files#15169]
### Description

When I try to open the recycle bin by clicking on the desktop icon, files shows the message that can be seen in the screenshot below _(Driver unplugged, not a folder)_.
However, if I restart the app, for example by changing the language, the recycle bin and the contained files are displayed correctly.

![Immagine 2024-04-13 144150](https://github.com/files-community/Files/assets/155762535/f90f749a-2c33-4e7a-b6a3-63887dc231a2)

### Steps To Reproduce

Simply open the recycle bin from the icon on the desktop.

### Requirements

Fix the bug described above so that the recycle bin can be displayed within files.

### Files Version

3.3.0.0

### Windows Version

10.0.19045.4291

### Log File

[debug.log](https://github.com/files-community/Files/files/14967457/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #15083. You can check there or click subscribe in the right sidebar for updates.

Please also try reinstalling Files.
