### ISSUE TITLE
Feature: record / sort by folder size

### ISSUE THREAD

**Issue by LikiaBili** [files-community/Files#15161]
### What feature or improvement do you think would benefit Files?

This is like the most thing I've wanted for the default windows explorer, to just show the folder size on the list
for now like I'm managing my steam games, I want to sort my games by size to delete the games occupy the most space and free up my disk space
but true most people won't need it and it will use a lot of resource by recursively scanning the file sizes
so here's two ways to done the idea:
- use a indexer to index every file in the computer, make size scanning faster to like 10-20ms?
- make user select to turn this feature on or just right click select "Scan Size" things etc.

### Requirements

- Record folder size in metadata
- Refresh loading folder size button as a icon in the size tab / record all selected folder's size in a right click menu

### Files Version

3.3.0.0

### Windows Version

10.0.19045.3930

### Comments

Image 1: Plan A - Make every folder in the size tab have a refresh button 
![image](https://github.com/files-community/Files/assets/103659676/dc45e0bb-aa53-4d23-825e-fa6afa2a8fb3)
Image 2: Plan B - Fetch folder size in the right click tab
![image](https://github.com/files-community/Files/assets/103659676/408e5e48-a684-45a9-b13d-8499bda3e07c)

**Comment by 0x5bfa** [comment]
Thanks for the feedback!
Let me clarify.

- You mean you want a page listing up all files sorted by Size?
  - If so, that is already requested as a feature of richer search options, while this feature requires much work to be done and we're exploring a new design to achieve more easily.
  - If not, and if you meant to sort by Size in a folder, you can already do that by clicking Size column. That sort setting will be saved in our database and so the sort settings are hold even after relaunch unless you clean up or uninstall.

> Make every folder in the size tab have a refresh button
We have a folder watcher to keep up with the latest information of folders and files. But if you want to do that manually you can click Refresh button on the address bar.

> Fetch folder size in the right click tab
You can get folder size from properties window. You might need to enable that option in Settings. You can find the option in Files & folders settings page.

**Comment by LikiaBili** [comment]
Yes, but the particular its listing the **folder**'s size instead of only listing the file's size.
I want the size can be stored and shown clearly in the size tab so that it can be faster when managing every folder to be deleted of not.
The properties window can only show one item at a time and it do not provides to sort every folder by size, that's what i meant.

P.S. the properties window recalculates the whole folder's size every time you opened it so the size data it's not stored, which can lead to issues.

**Comment by Josh65-2201** [comment]
You can already have Files calculate folder size in Files settings > Files & Folders > Calculate folder sizes. This will update when the changes to the folder.
