### ISSUE TITLE
Cannot start files on newly installed windows 11 box

### ISSUE THREAD

**Issue by JohRest** [files-community/Files#15162]
### Description

I recently had to fully reset my win 11 box. After installing everything I noticed that files does not even start. I added .net sdk 8 and also 7, but I can't get it to start. In eventlog I do see:

```
Application: Files.exe
CoreCLR Version: 8.0.324.11423
.NET Version: 8.0.3
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException: The type initializer for 'WinRT.ActivationFactory`1' threw an exception.
 ---> System.Runtime.InteropServices.COMException (0x80040154): class not registered (0x80040154 (REGDB_E_CLASSNOTREG))
   at WinRT.BaseActivationFactory..ctor(String typeNamespace, String typeFullName)
   at WinRT.ActivationFactory`1..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Windows.AppLifecycle.AppInstance.Make___objRef_global__Microsoft_Windows_AppLifecycle_IAppInstanceStatics()
   at Files.App.Program.Main()
```

### Steps To Reproduce

Reset win 11, try to install files via store app

### Requirements

expected is that the files app starts.

### Files Version

can't get version as the app doesn't start

### Windows Version

23H2 build 22631.3374

### Log File

no file available. Directory is empty.

**Comment by Josh65-2201** [comment]
Thanks for the report, are you using an unofficial (like Atlas OS or ReviOS etc.) or a modified (like disabled Windows update system, removed the Microsoft store, used a debloat program/script etc.) version of Windows? If so Modified versions of Windows are not supported.

**Comment by JohRest** [comment]
The issue was not with the machine nor the OS... I had issues with my router, which failed to resolve certain ips; Windows update was also affected; so I restored it from an known to work image... so all is good again. Closing this issue as no longer relevant. Thanks for taking the time to look at it!

**Comment by yaira2** [comment]
@JohRest thank you for the update!
