### ISSUE TITLE
wt | windows terminal option

### ISSUE THREAD

**Issue by TadhgEomonn** [files-community/Files#15165]
### What feature or improvement do you think would benefit Files?

Request: a right context menu option to start wt in the present folder as can be done in File Explorer (albeit after choosing more options).

### Requirements

- This proposal will accomplish an alternative method of initiating Windows Terminal without having to type a command in the address bar. I am not sure what requirements would be necessary.

### Files Version

3.3.0.0

### Windows Version

10.0.22631

### Comments

Alternatively (perhaps), add Windows Terminal to the command palette with a shortcut to activate it.

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Windows Terminal is responsible to adding itself in the context menu. You can however use `Ctrl + '` to open terminal at the current folder.
