### ISSUE TITLE
Bug: HWiNFO64 doesn't open

### ISSUE THREAD

**Issue by Ser2k2** [files-community/Files#15179]
### Description

I found a bug: it can't run HWiNFO64! I'm not sure if it's HWiNFO64 or the Files program causing the problem. Because I can run HWiNFO64 in Explorer without a problem.

### Steps To Reproduce

Run HWiNFO64  in Files.

### Requirements

Files can not run HWiNFO64

### Files Version

3.3.0.0

### Windows Version

Version 23H2 (OS Build 22631.3447)

### Log File

[debug.log](https://github.com/files-community/Files/files/14979127/debug.log)

**Comment by 0x5bfa** [comment]
Thanks for the feedback.

**Comment by Josh65-2201** [comment]
I'm unable to reproduce this, 
- When are you opening it from?
- Do you see the UAC admin prompt when opening?

**Comment by Ser2k2** [comment]
The Windows UAC prompt. After that, HWiNFO64 doesn't run.

**Comment by gave92** [comment]
Can reproduce, we get an error in HandleApplicationLaunch()
`System.ComponentModel.Win32Exception: 'An error occurred trying to start process 'C:\Users\gavet\Documents\HWiNFO64.exe' with working directory 'C:\Users\gavet\Documents'. Unsupported request.'`

**Comment by 0x5bfa** [comment]
If one of devs can repro, we might as well make this as Ready to build.
