### ISSUE TITLE
Bug: Increased crashes in v3.3.1 (preview)

### ISSUE THREAD

**Issue by join-xu2021** [files-community/Files#15172]
### Description

When there are too many files in a folder, opening the folder will be jammed.

### Steps To Reproduce

When there are too many files in a folder, opening the folder will be jammed.

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.3.1.0

### Windows Version

10.0.22635.3495

### Log File

[debug.log](https://github.com/files-community/Files/files/14970556/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, 
- What do you mean by jammed.
- Can you add the steps to reproduce.

**Comment by yaira2** [comment]
Thank you for your feedback, are you also able to repro these issues in v3.3 or is it only in the preview version?

**Comment by join-xu2021** [comment]
When there are too many files in a folder, I click on the folder and instead of seeing the files in the folder directly, it's in a loading state, and I'm not really sure how long this state lasts, and this state prevents me from manipulating other folders, and the whole software crashes. Only the preview version is used.

**Comment by yaira2** [comment]
Please let us know if this is also an issue in the stable release.

**Comment by join-xu2021** [comment]
I haven't found this type of problem in the stable version.

**Comment by join-xu2021** [comment]
I haven't found this type of problem in the stable version.
