### ISSUE TITLE
Bug: Git Submenu is shown for non GitHub Repos

### ISSUE THREAD

**Issue by domi-bue** [files-community/Files#15177]
### Description

The Git Submenu is empty for non GitHub Repos:
![image](https://github.com/files-community/Files/assets/138104893/27cffab5-0c22-493b-b335-fe07cd273cab)

### Steps To Reproduce

1. Clone a Repo from GitHub
2. Clone a Repo from e.g. GitLab
3. Go into the GitHub Repo and check the Git Submenu in the Contextmenu
4. Go into the GitLab Repo and  check the Git Submenu in the Contextmenu

### Requirements

Git Submenu shouldn't be empty for non GitHub Repos

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3447

### Log File

[debug.log](https://github.com/files-community/Files/files/14977758/debug.log)

**Comment by 0x5bfa** [comment]
Thanks for the feedback!

We currently support only GitHub. I'm not sure why parent menu is visible to begin with for non-GitHub repos, but we'll track this issue.

**Comment by yaira2** [comment]
Agreed, the menu option shouldn't be visible in the first place.
