### ISSUE TITLE
Pinned folders not loading

### ISSUE THREAD

**Issue by Bozo-Dubbed-Over** [files-community/Files#15170]
### Description

Intermittently does not load pinned folders, recent files, or quick access upon opening. Resolves with PC reboot, but this is inconvenient.

### Steps To Reproduce

Happens irregularly

### Requirements

Should load with all pinned folders, recent files, and quick access.

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3447

### Log File

[debug.log](https://github.com/files-community/Files/files/14967720/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #13116 . You can check there or click subscribe in the right sidebar for updates. There is also a workaround you can try in that issue
