### ISSUE TITLE
Feature: Add a tooltip on what the cloud drive status icon means

### ISSUE THREAD

**Issue by CanePlayz** [files-community/Files#15182]
### What feature or improvement do you think would benefit Files?

Right now, I think it can be hard to tell what exactly these icons mean, especially when you have two green ones which look pretty similar.

![image](https://github.com/files-community/Files/assets/81419612/6d205acb-48ca-4d98-95e5-1685ae52325b)

### Requirements

A UI change

### Files Version

3.3.0.0

### Windows Version

11

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
This feature will be included in the next update
