### ISSUE TITLE
feature like TreeComp

### ISSUE THREAD

**Issue by SimoneRaspagni** [files-community/Files#1518]
**Is your feature request related to a problem? Please describe.**
it could be interesting integrate, in future versions, a feature like TreeComp (https://lploeger.home.xs4all.nl/TreeComp.htm)

**Describe the solution you'd like**
---

**Describe alternatives you've considered**
---

**Additional context**
_TreeComp is an interactive utility to keep 2 directory trees and the files within the directories in sync. The combined tree is displayed using a treeview control with icons indicating the status per directory. Programs to view the differences (i.e. Microsoft's WinDiff or WinMerge) between files with the same name can be launched by double-clicking, as well as editors for a file residing in one of the 2 trees. After inspection files can be copied/deleted interactively as desired. In our organization we view this program as an indispensable tool that is far beyond xcopy /s /e._

**Comment by yaichenbaum** [comment]
@SimoneRaspagni Thank you for opening this issue, I am closing this issue since this feature request is out of scope for Files.
