### ISSUE TITLE
Close settings button is cut off

### ISSUE THREAD

**Issue by CanePlayz** [files-community/Files#15188]
### Description

No idea why, but this button is cut off on the right

![image](https://github.com/files-community/Files/assets/81419612/6e41600a-b909-425c-b8e3-9355a3dacbaf)

### Steps To Reproduce

Open the settings

### Requirements

Fix the UI not being properly displayed

### Files Version

3.3.0.0

### Windows Version

10.0.26100.1

### Log File

.

**Comment by yaira2** [comment]
Similar to #15192, I'm not able to repro this on my end. I suspect it's something to do with your screen scaling, but we'll need to repro this on our side to know for sure. In the meantime, I think we can merge these two.

**Comment by CanePlayz** [comment]
Alright, makes sense
