### ISSUE TITLE
Bug: Google Drive shows up two times under "Cloud Drives"

### ISSUE THREAD

**Issue by CanePlayz** [files-community/Files#15184]
### Description

![image](https://github.com/files-community/Files/assets/81419612/d80bc1fe-d206-4090-a918-580031fc968b)

### Steps To Reproduce

Have Google Drive v89 installed

### Requirements

Fix Google Drive showing up two times

### Files Version

3.3.0.0

### Windows Version

10.0.26100.1

### Log File

[debug.log](https://github.com/files-community/Files/files/14982896/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Do you have multiple Google Drive accounts connect or multiple folders being sync to Google Drive

**Comment by CanePlayz** [comment]
Nope, I'm just mirroring data from one Google Drive account with one Google Drive installation

**Comment by gave92** [comment]
Which of these options do you have in Google Drives settings?
![image](https://github.com/files-community/Files/assets/9673091/b9a0647e-3c9b-493e-9797-463d4ba3b689)

**Comment by CanePlayz** [comment]
Despite it being the "not so clean" version that is being shown now, it's only one, so I guess it's fixed, thanks :)

![image](https://github.com/user-attachments/assets/6512ce65-fb3f-4dc9-b8af-5cc87601594a)

**Comment by Josh65-2201** [comment]
Thanks for checking, The icon is set by the sync folder. If you go to where your drive is set to sync too > Open Folder properties > Customize > Browse > Go to the Google drive program (Usually in `C:\Program Files\Google\Drive File Stream\95.0.2.0`) > Change application extension above the open button to `.exe` > Click Google Drive FS.exe > Set the icon > Save > Restart Files

**Comment by CanePlayz** [comment]
Thanks
