### ISSUE TITLE
New option: Allow running the app in the background without tray icon

### ISSUE THREAD

**Issue by CanePlayz** [files-community/Files#15189]
### What feature or improvement do you think would benefit Files?

Some people like me don't like a try area that is too crowded, but would still like to benefit from the advantages of letting Files run in the background

### Requirements

Maybe give the user an additional option to manage if there is a try icon independently from the settings that lets Files run in the background

### Files Version

3.3.0.0

### Windows Version

10.0.26100.1

**Comment by Josh65-2201** [comment]
Thanks for the feedback, there isn't any plans on adding a option in Files. You can put it in the overflow via Windows Settings > Personalization > Taskbar > Other tray icons and then disable the overflow if you want.

**Comment by CanePlayz** [comment]
Ok, unfortunate but fair

**Comment by yaira2** [comment]
To be fair, this is something we're considering doing but we haven't committed to it just yet.

**Comment by CanePlayz** [comment]
Yeah, all good, it's not a huge problem anyways :P

**Comment by yaira2** [comment]
We're working on a built-in setting for this in #15947.

**Comment by CanePlayz** [comment]
Great, thanks
