### ISSUE TITLE
Startup settings are messed up in German

### ISSUE THREAD

**Issue by CanePlayz** [files-community/Files#15187]
### Description

Due to the text length, the settings look wrong in German:

![image](https://github.com/files-community/Files/assets/81419612/58c3b9df-105f-43c8-8fd3-4c8435c0b3ea)

![image](https://github.com/files-community/Files/assets/81419612/2186d99b-ecdb-48a4-979b-f672680e91dd)

### Steps To Reproduce

Set your language to German and open the settings

### Requirements

Fix this weird UI piece

### Files Version

3.3.0.0

### Windows Version

10.0.26100.1

### Log File

.

**Comment by yaira2** [comment]
Thank you for your feedback, are you referring to the way the dropdown menu is repositioned? If so, this is the expected design and the same should occur if you make the window width smaller.

**Comment by CanePlayz** [comment]
I see your point that this is expected, but in this case, there is more than enough space to position it normally I think

**Comment by yaira2** [comment]
There is some extra spacing, but that's also by design. That said, we plan to switch to the Toolkits setting control in the future and that will ensure greater consistency between Files and other inbox apps.

**Comment by CanePlayz** [comment]
Great to hear!
