### ISSUE TITLE
Bug: Advanced settings page does not animate correctly

### ISSUE THREAD

**Issue by CanePlayz** [files-community/Files#15185]
### Description

Sometimes, the fly-in animation of the text in the "Advanced" settings is bugged, and instead, the text just appears out of thin air. Weirdly, I've only observed this behavior when the language was set to German, not when it was set to English.

### Steps To Reproduce

Set your language to German and open the "Erweitert" page in the settings

https://github.com/files-community/Files/assets/81419612/cb2d47ce-3942-408f-acc7-386502b89de3

### Requirements

Fix the wrong animation of the text

### Files Version

3.3.0.0

### Windows Version

10.0.26100.1

### Log File

[debug.log](https://github.com/files-community/Files/files/14982910/debug.log)

**Comment by CanePlayz** [comment]
Same goes for this settings:

![image](https://github.com/files-community/Files/assets/81419612/76f74662-e278-4fc9-a329-48b358192bdc)

**Comment by yaira2** [comment]
I can repro this when running in dev mode

**Comment by 0x5bfa** [comment]
I've been able to repro for months.
Once we moved to tabs, won't we be going to remove navigation animations?

**Comment by yaira2** [comment]
We haven't planned that far but there is a good chance we'll move to something more subtle.

**Comment by yaira2** [comment]
This will be resolved in the next update.

**Comment by CanePlayz** [comment]
Perfect
