### ISSUE TITLE
Option to hide the OneDrive check mark on grid layout

### ISSUE THREAD

**Issue by VoidGS** [files-community/Files#15199]
### What feature or improvement do you think would benefit Files?

There isn't a option to hide the OneDrive on grid layout, but on the columns you can hide it, so it would be great to be able to hide it on the grid too. Also, the check mark is with the design kinda bugged, it's not centered on the line, seems that the style is broken.

Example:
![image](https://github.com/files-community/Files/assets/71122284/c2d1176b-fac9-4c82-b489-4a418e145cbd)

### Requirements

- This proposal will introduce a option to hide the status check from OneDrive in the grid layout

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3447

**Comment by yaira2** [comment]
Thank you for your feedback, we don't plan to support hiding the checkmark but we're working on an updated design that has a better layout for the status icons.

**Comment by VoidGS** [comment]
Thats great to hear, a better design would fit it too. Thanks.
