### ISSUE TITLE
Bug: MEGA cloud drive isn't detected correctly if Google drive was installed

### ISSUE THREAD

**Issue by HanOtten** [files-community/Files#15198]
### Description

MEGA is shown as Google drive in Cloud Drives
![Schermafbeelding 2024-04-16 17 00 51](https://github.com/files-community/Files/assets/167221180/7f385c6e-a323-430c-a6cd-cf8be3761e35)

### Steps To Reproduce

Simply start Files with an attached MEGA cloud share

### Requirements

Please fix the name 

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3447

### Log File

[debug.log](https://github.com/files-community/Files/files/14998975/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, have you previously had Google Drive installed?

**Comment by HanOtten** [comment]
Yes, I had Google drive installed previously.

**Comment by Josh65-2201** [comment]
This is probably from an issue with Google Drive not uninstalling property. Can you try opening the registry path `HKEY_CURRENT_USER\Software\Google` and see if `Drive` or `DriveFS` is shown, If so you can Right click > Delete on those folders only and restart Files from the system tray.

**Comment by HanOtten** [comment]
I did and it did not solve the problem.

**Comment by HanOtten** [comment]
I removed the folder C:\Users\JAOtt\AppData\Local\Google\DriveFS.
After that the MEGA entry completely disappeared.

**Comment by Josh65-2201** [comment]
The path is for the registry not normal file explorer.

**Comment by HanOtten** [comment]
I don't understand wath you say.

**Comment by Josh65-2201** [comment]
Type Registry in Windows start menu search bar > Open it > Enter the path from my first comment into the box that says `computer` follow the restart of the instructions.
![image](https://github.com/files-community/Files/assets/26977075/7179a12e-44b5-4af5-b11b-0cef85bde61e)

**Comment by HanOtten** [comment]
I'm a little confused
I removed the registry entry for Google drive as you mentioned before. It dit not change everything.
After that I removed the folder C:\Users\JAOtt\AppData\Local\Google\DriveFS. The result was that the MEGA disappeared from Cloud Drives
How do I get MEGA visible in Cloud Drives?

**Comment by Josh65-2201** [comment]
Did you fully close and reopen Files after?

**Comment by HanOtten** [comment]
Yes I did. To be sure I restarted Windows.

**Comment by Josh65-2201** [comment]
Thanks for the information. Mega should show without Google drive but I guess there's an issue with detection.

**Comment by yaira2** [comment]
@HanOtten it seems that one of the registry keys isn't configured properly, I can't say for sure, but there is a good chance reinstalling Mega will fix this issue.

Can you also confirm if Mega is displayed in File Explorer?

**Comment by HanOtten** [comment]
I reinstalled MEGA, but it is still not shown in cloud drives.
MEGA is shown in the Windows explorer.
Please, can you tell me wich registry key should be available for detecting MEGA?

**Comment by yaira2** [comment]
@Josh65-2201 do you know?

**Comment by Josh65-2201** [comment]
Have you fully restarted Files by quitting from the system tray?

**Comment by HanOtten** [comment]
That was the trick, after enebling MEGA file explorer integration it works.
Thanks for your help.

**Comment by Josh65-2201** [comment]
Great to know
