### ISSUE TITLE
Improvement: Add button to return to "Security" page from "Advanced permissions" page

### ISSUE THREAD

**Issue by CanePlayz** [files-community/Files#15191]
### What feature or improvement do you think would benefit Files?

Once you're here

![image](https://github.com/files-community/Files/assets/81419612/c940b991-d484-4ac4-a9c3-dd8c77cd3c39)

you cannot return to here

![image](https://github.com/files-community/Files/assets/81419612/90c74389-cce6-4689-bcd4-f921b85f9d31)

without closing the entire dialogue window.

### Requirements

Let the user go back one level without having to close the entire window

### Files Version

3.3.0.0

### Windows Version

10.0.26100.1

**Comment by Josh65-2201** [comment]
Thanks for the feedback, there already is a back button
![image](https://github.com/files-community/Files/assets/26977075/9a5efb32-c12a-4caa-a27d-3075f717a43c)

**Comment by CanePlayz** [comment]
Oh god, I am so blind, sorry 🤦‍♂️
