### ISSUE TITLE
Default and Save As

### ISSUE THREAD

**Issue by itsJavaCoder** [files-community/Files#1519]
Is there a way I can change the default so it opens files uwp when it tries to open file explorer? Also is there a 'save as' window like file explorer? If not then I would appreciate it if it was added.

**Comment by XPoppyX** [comment]
> Is there a way I can change the default so it opens files uwp when it tries to open file explorer?

https://github.com/files-community/files-uwp/wiki/Replacing-File-Explorer-with-Files-UWP

**Comment by JavaAppleJr** [comment]
what about the save as thing?

**Comment by JavaAppleJr** [comment]
ok.

**Comment by Jaiganeshkumaran** [comment]
Replacing File Explorer will prevent you from accessing the Control Panel. Instead consider adding the option to open a selected folder in Files UWP. Check this out: https://github.com/files-community/files-uwp/wiki/Add-Files-UWP-to-the-File-Explorer-context-menu
