### ISSUE TITLE
Feature: Support opening Explorer's Properties window

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#15196]
### What feature or improvement do you think would benefit Files?

Files has its own Properties window, but it doesn't support utilities that extend Explorer's Properties window. It is difficult to support these utilities, so it would be nice to have the ability to open Explorer's Properties window instead of Files' one as an alternative.
It can also be a stopgap to display data that cannot yet be displayed in the Files' properties window.

### Requirements

Open Explorer's Properties window instead of Files' one if a specific modifier key (Shift or Alt) is pressed when opening a Properties window.

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3447

**Comment by yaira2** [comment]
We don't want to expose this via the UI but we can add an action if there is enough interest. As a sidenote, it would be interesting if we had support for creating custom actions.

**Comment by hishitetsu** [comment]
> We don't want to expose this via the UI but we can add an action if there is enough interest.

Yes, I think it should be a so-called hidden function that is only available when a modifier key is pressed.

> As a sidenote, it would be interesting if we had support for creating custom actions in general.

You mean that users can define actions using scripts, right? That sounds interesting.

**Comment by yaira2** [comment]
Yes

**Comment by yaira2** [comment]
> You mean that users can define actions using scripts, right? That sounds interesting.

Yeah

**Comment by yaira2** [comment]
Do you think there should be a default key-binding?

**Comment by hishitetsu** [comment]
It would be Alt+Shift+Enter.
Also, pressing Properties button with holding Shift key would open Explorers' Properties window.

**Comment by yaira2** [comment]
If we add an action to "Run script", this will likely be possible once custom args are supported.

**Comment by yaira2** [comment]
> Also, pressing Properties button with holding Shift key would open Explorers' Properties window.

Do we have a way to do this?

**Comment by hishitetsu** [comment]
> > Also, pressing Properties button with holding Shift key would open Explorers' Properties window.
> 
> Do we have a way to do this?

I have made it possible with https://github.com/files-community/Files/pull/12728.

**Comment by yaira2** [comment]
Thanks! I've pushed the changes in #16031
