### ISSUE TITLE
New feature: Allow customizing which file types show up when pressing the "New" button

### ISSUE THREAD

**Issue by CanePlayz** [files-community/Files#15190]
### What feature or improvement do you think would benefit Files?

It would be great if we could customize which file types show up in this menu, so we actually have the ones we use the most often there

![image](https://github.com/files-community/Files/assets/81419612/fac7086f-1f16-415c-98ee-2aa1b63f536c)

### Requirements

Let the user customize which file types show up, essentially making file creation simpler and more efficient

### Files Version

3.3.0.0

### Windows Version

10.0.26100.1

**Comment by yaira2** [comment]
Thank you for your feedback, the list of file types is provided by the system registry. While we don't have support for editing the entries directly from Files, there are a number of third-party applications that can modify the list for you.

**Comment by CanePlayz** [comment]
Ok, thanks
