### ISSUE TITLE
Feature: Add an option to adjust the drag & drop sensitivity of "hover to open"

### ISSUE THREAD

**Issue by mlwdragon1** [files-community/Files#15200]
### What feature or improvement do you think would benefit Files?

While dragging and dropping files over folders, the folder expands. This is usually not the folder I wanted, but was to slow moving the mouse waiting for the correct folder to highlight. Also can you add the right click drag feature so you can force file to move and not assume you want to copy it.

### Requirements

Add an option to adjust the drag & drop sensitivity of "hover to open"

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3296

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
Would an option to adjust the sensitivity also work towards solving your use case?

**Comment by mlwdragon1** [comment]
It would, but honestly, I have never needed to open a folder to get to subfolders whiles moving or coping. The right click drag and drop to choose “move” or “copy” would be nice also.

Thanks

Michael

**Comment by yaira2** [comment]
@mlwdragon1 the next version of Files (v3.6) will reduce the sensitivity of "hover to open". If this isn't enough, please let us know and we'll work on further improvements in this area.
