### ISSUE TITLE
Bug: OneDrive items are auto downloaded

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#15202]
### Description

In recent preview builds, opening a OneDrive folder auto downloads the contents.

### Steps To Reproduce

1. Open OneDrive folder

### Requirements

- Don't auto download items

### Files Version

v3.3.2

### Windows Version

Windows 11

### Log File

NA

**Comment by yaira2** [comment]
I can confirm that this issue isn't present in bb8031c0aa8ec3632f74d61271c5c73cd48ff715

**Comment by yaira2** [comment]
Fyi @hez2010

**Comment by yaira2** [comment]
It appears that this issue was introduced with a0acba3e8d5201bd67d63c770e5f339e4d257a76.

**Comment by hez2010** [comment]
It turns out to be the tag initialization. Will be fixed in #15216.

**Comment by yaira2** [comment]
This issue is back

**Comment by yaira2** [comment]
I pushed a fix to `main`.
