### ISSUE TITLE
In Home, Quick and recent files are missing the content

### ISSUE THREAD

**Issue by Ser2k2** [files-community/Files#15218]
### Description

I'm experiencing a random bug in the Home view of Files Explorer. The quick access and recent files are missing their content. I have to quit the program and then open Files again to fix it.

![image_2024-04-17_094721224](https://github.com/files-community/Files/assets/167018435/8def91f1-a08c-42f1-9e5c-240840609f56)

### Steps To Reproduce

Open Files; random bug. I have the option selected: Open Files on Windows Startup and leave app running in the background when window is closed.

### Requirements

No crash, only missing the content.

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3447

### Log File

[debug.log](https://github.com/files-community/Files/files/15013431/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #13116. You can check there or click subscribe in the right sidebar for updates. There is also a work around listed at the top of the issue.
