### ISSUE TITLE
LISTARY SUPPORT

### ISSUE THREAD

**Issue by JImRock33** [files-community/Files#15211]
### What feature or improvement do you think would benefit Files?

Would be awesome ... thx _Emmanuell

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

last preview cersion

### Windows Version

Edition	Windows 11 Pro Version	23H2 Installed on	‎26/‎03/‎2024 OS build	22631.3447 Experience	Windows Feature Experience Pack 1000.22688.1000.0

**Comment by 0x5bfa** [comment]
We have it already .

**Comment by yaira2** [comment]
@JImRock33 thank you for your feedback. Listary support was recently added to the preview version of Files, but it requires Listary 6.3 before it will work.

**Comment by SpringsTS** [comment]
Perfect, the only missing feature that prevented me from using Files as default. Thanks!
