### ISSUE TITLE
Updating network navigation to long

### ISSUE THREAD

**Issue by Benx66** [files-community/Files#15215]
### Description

When I browse my network directories I always have a loading time. This can be seen in the tab at the top with the loading circle as well as on the icons.
This only happens in network directories, even if I've already explored the directory.

Via Windows Explorer I don't have this problem. 

### Steps To Reproduce

Network navigation

### Requirements

Laptop

### Files Version

3.3.0

### Windows Version

11 23H2

### Log File

not log file

**Comment by Benx66** [comment]
If i understand, there's no solution at the moment?

**Comment by Josh65-2201** [comment]
No, it requires code changes in Files.

**Comment by Benx66** [comment]
Files from "Files" or Windows?

**Comment by 0x5bfa** [comment]
"Files"
