### ISSUE TITLE
losing sidebar and panes sections, always///  thx for ur attention   Emmanuel

### ISSUE THREAD

**Issue by JImRock33** [files-community/Files#15212]
### Description

I always lose pinned or network sections,

### Steps To Reproduce

open file, use it max 25 min, then no more sidebar pinned, cetwork,and nothing more in panes items.  in pnesns and sidebar. have to quit and relaunch, with stable version as with preview, even on a fresh system...so have to switch back to windows explorer (  thx  thank you

Emmanuel

### Requirements

- e.g. Fix crash that occurs when...
expecting a stable interface )

### Files Version

last stable and preview

### Windows Version

Edition	Windows 11 Pro Version	23H2 Installed on	‎26/‎03/‎2024 OS build	22631.3447 Experience	Windows Feature Experience Pack 1000.22688.1000.0

### Log File

have uninstalled the app, that i purchased unfortunately, too frustrating and time consuming

**Comment by 0x5bfa** [comment]
Could you send me a screenshot of loosing sidebar items and pane items?

**Comment by JImRock33** [comment]
> Could you send me a screenshot of loosing sidebar items and pane items?
sure here it is...)
Btw as i suggested listary compatibility would be awesome, and another greatly missing functionnality to me: natively in windows 11 shift and right clivk opens up the extended contextual menu, wich doesn't work neither inside of files managers, and damned it's a huge time saver...))  thx for ur attention
E

**Comment by 0x5bfa** [comment]
Seems not to be able to see the screenshot. You can take a screenshot, copy to the clipboard with Ctrl+C, and paste here.

> shift and right clivk opens up the extended contextual menu

I think you can open it by right clicking and press the menu item on the bottom. Is that something different thing for you? If so, sorry but it’s not something we are planning.

**Comment by JImRock33** [comment]
> Seems not to be able to see the screenshot. You can take a screenshot, copy to the clipboard with Ctrl+C, and paste here.
> 
> > shift and right clivk opens up the extended contextual menu
> 
> I think you can open it by right clicking and press the menu item on the bottom. Is that something different thing for you? If so, sorry but it’s not something we are planning.
always confronted to this too: 
![Uploading image.png…]()

**Comment by 0x5bfa** [comment]
Waiting for the upload works for you.

**Comment by JImRock33** [comment]
> Seems not to be able to see the screenshot. You can take a screenshot, copy to the clipboard with Ctrl+C, and paste here.
> 
> > shift and right clivk opens up the extended contextual menu
> 
> I think you can open it by right clicking and press the menu item on the bottom. Is that something different thing for you? If so, sorry but it’s not something we are planning.

https://www.dropbox.com/scl/fi/5fgkkvf2b3cw52trda1xy/jjLb7uAi4Z.png?rlkey=bf5t4ytj37jt1t65y74svyy0c&dl=0

https://www.dropbox.com/scl/fi/j73843ygkj5triqzolbhz/TnjKbo6v8g.png?rlkey=e6akjzxihjam8qeap7sg4twjy&dl=0

https://www.dropbox.com/scl/fi/i5ul2gol1bwa4jdy6yrex/Files_ffTSNAzG2G.png?rlkey=078v3m4rj3egbyv9rfowmc57v&dl=0

thx )
E

**Comment by JImRock33** [comment]
yeah on windoows 11 desktop, without any add on, shift click a file folder or the desktop and it bypasses , the small contextual menu and u directly acess ur full menu... doesn't work in files ))  thx again !

**Comment by Josh65-2201** [comment]
Files will work with Listary 6.3

**Comment by JImRock33** [comment]
> Files will work with Listary 6.3


just tried, and it still doesn't. huge benefit of listary is the hovering ov er a destination folder wich is automatically updated in the open dialog box, and it perfectlu works in windows file manager, but even after my update to listary 6.3, hovering over a files window doesn't refresh directory in the import/open dialog box... 2 reboots, directory cleaning, and SFC scanow.
thx ))

**Comment by Josh65-2201** [comment]
You should make sure that Files is enabled in the integrations settings of Listary. Since 6.3 is beta only they may have not added it on their side so you may have to wait for the full release.

**Comment by Josh65-2201** [comment]
Also we're tracking the pins not showing in #13116. You can check there or click subscribe in the right sidebar for updates.
