### ISSUE TITLE
Bug: Tagged folders don't show on the home page widget

### ISSUE THREAD

**Issue by yIsItSo** [files-community/Files#15214]
### Description

On Home tab tagged folders are missing

![image](https://github.com/files-community/Files/assets/126057362/42cca791-30ff-4a3f-9d25-e2af6df93a3f)

### Steps To Reproduce

1. Open Home tab
2. Look in Tag groups for tagged folders

### Requirements

Work as previously

### Files Version

3.3.2.0

### Windows Version

10.0.22635.3495

### Log File

[debug.log](https://github.com/files-community/Files/files/15007592/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report,
- where are the folders located? 
- If you open the folders that are tagged do they show?

**Comment by yIsItSo** [comment]
Standard folders, on the disk

They are marked as tagged:
[cid:1d7f75e5-a989-44bd-ad09-de43d8a41545]

Open with no problems

Thanks

________________________________

**Comment by Josh65-2201** [comment]
If you tried uploading and image email attachments don't work. You will have to click the `View on GitHub` link at the bottom of the email > Copy and paste or click the add attachment button to select the file > Wait until you don't see `uploading` in the text > Click the green comment button.

**Comment by yIsItSo** [comment]
![image](https://github.com/files-community/Files/assets/126057362/8a7c3efe-f615-4da8-854c-06f7e5fec8a8)
![image](https://github.com/files-community/Files/assets/126057362/8971b270-536f-40f7-98de-3d9171e2d921)

**Comment by Josh65-2201** [comment]
Thanks for the information

**Comment by yaira2** [comment]
Do they show when you open them from the sidebar?

**Comment by tbytetbyte** [comment]
I have the same problem :(

**Comment by yaira2** [comment]
This usually happens when the tagged files aren't indexed by Windows. Please try enabling "Enhanced search" in the Windows settings app and let us know if this helped.

**Comment by tbytetbyte** [comment]
I have set Windows Search like this...
![image](https://github.com/files-community/Files/assets/139590826/bd39cb09-8732-4973-9e4c-4565bb87445e)

**Comment by tbytetbyte** [comment]
Hi Josh. I think this problem is HUGE, because, now, when I try to pen the tagged folders, the items dissapear! 
I shows all files inside the taged folder for 1 second, and after that, keep dissapearing from view!

**Comment by yaira2** [comment]
We are planning to move away from our approach that relies on the Windows Search Index. This change aims to address the issue and enhance overall reliability. Please refer to #15272 for further updates.
