### ISSUE TITLE
Change File customisation properties for subfolders

### ISSUE THREAD

**Issue by Titus104** [files-community/Files#15222]
### What feature or improvement do you think would benefit Files?

Hi,
I was hoping to use Files to handle a bug in Windows 11 File Explorer.
I want to be able to change the customise properties (specifically the type of file) for this folder and all subfolders.
I have loads of movies and TV series and I want change the file type from 'General Items' to 'Video'. With File Explorer I currently have to go through every folder and subfolder manually.
If this feature is already in Files then I apologise but I can'rt see it.

### Requirements

I don't have enough knowledge to be able to answer this.

### Files Version

3.3.0.0

### Windows Version

Edition	Windows 11 Home Version	23H2 Installed on	‎25/‎01/‎2023 OS build	22631.3447 Experience	Windows Feature Experience Pack 1000.22688.1000.0

**Comment by yaira2** [comment]
Thank you for your feedback, we're currently tracking this feature in #5564. You can add a comment or subscribe to the issue to get a notification regarding any updates.
