### ISSUE TITLE
BUG: Installing via classic installer Win 10 not working

### ISSUE THREAD

**Issue by eigenstil** [files-community/Files#15221]
### Description

The installation fails without any further notice:
![image](https://github.com/files-community/Files/assets/37832701/38985a92-10e0-49f8-a223-3250d8aad562)

Tried it with right clicking the exe file and execute as admin, as well as just only double clicking the installer

### Steps To Reproduce

1. Download the installer exe file from https://files.community/download
2. Double click it
3. Click "install"
4. wait for the error

### Requirements

I expect files to be instalable or give me a more detailed error message.

### Files Version

3.3..0.0

### Windows Version

Windows 10, version 22H2 (Build 19045.4291)

### Log File

no log file available, because I can't install the app.

**Comment by Josh65-2201** [comment]
Can you try
   1. Opening PowerShell as administrator
   2. Run this command
   ```Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/stable/Files.Package.appinstaller```
   3. See if Files is in the start menu all apps section

**Comment by eigenstil** [comment]
> Can you try
> 
> 1. Opening PowerShell as administrator
> 2. Run this command
>    `Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/stable/Files.Package.appinstaller`
> 3. See if Files is in the start menu all apps section

tried it. works. It appears in the start menu.
