### ISSUE TITLE
Files will suddenly start crashing and continue to crash when trying to open folder/drive

### ISSUE THREAD

**Issue by piperun** [files-community/Files#15223]
### Description

As of 3.3.2 Files keeps on randomly crashing and once it starts you're effectively stuck with it endlessly crashing (if you open any folder or drive), this is while having another Files open (which will also start crashing if you open any folder/drive).

### Steps To Reproduce

1. Open 2 Files windows
2. Use it as normal
3. It'll at some point crash and upon automatic restart it'll crash everytime you try to open any folder/drive

### Requirements

- Fix the crash that suddenly happens
- Fix the subsequent crashes that happens anytime you open any folder/drive.

### Files Version

3.3.2.0

### Windows Version

10.0.19045.4170

### Log File

[debug.log](https://github.com/files-community/Files/files/15030582/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, this is fixed in our dev branch and will be included in the next preview build. In the meantime we recommend using the stable version of Files which doesn't have this issue.
