### ISSUE TITLE
Wrong suggestion 

### ISSUE THREAD

**Issue by iramyaseen** [files-community/Files#15224]
### Description

I have tabs running and showing me something else in the suggestion while none of my tabs are running like this. It was the previous tab that I closed the window and when I opened it. If I click on the button, then the same video of mine which is shown in the screenshot is shown and even if I pause, the same video of mine stops which is showing in the screenshot, while in the side bar, I see another video. Appearing

### Steps To Reproduce

I have tabs running and showing me something else in the suggestion while none of my tabs are running like this. It was the previous tab that I closed the window and when I opened it. If I click on the button, then the same video of mine which is shown in the screenshot is shown and even if I pause, the same video of mine stops which is showing in the screenshot, while in the sidebar, I see another video. Appearing
![Screenshot 2024-04-19 124533](https://github.com/files-community/Files/assets/75573544/a6d31c01-23e2-4609-8d71-86475a2073de)

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

updated

### Windows Version

11

### Log File

Please check

**Comment by iramyaseen** [comment]
I think this issue is window issue can you please let me know where I
raised this issue for window 11

**Comment by 0x5bfa** [comment]
This must be an issue with Windows and this doesn’t seem to be severe one, so I’d suggest you should wait upcoming Windows Updates

**Comment by iramyaseen** [comment]
Ok Thank you
