### ISSUE TITLE
Bug: Column Layout - Clicking on folder "animates" back to position from a reset every folder click

### ISSUE THREAD

**Issue by Draise14** [files-community/Files#15230]
### Description

https://github.com/files-community/Files/assets/35357409/51fc72c7-9e3a-46b1-9f68-90fbd5c03a9e

### Steps To Reproduce

1. Go to Column view with a number of folder with sub-folders
2. Cilck on folder in a sub-fodler column
3. Notice the animation of the column reverts to itself

### Requirements

This didn't happen in the previous preview version

### Files Version

3.3.4.0

### Windows Version

10.0.22635.3495

### Log File

[debug.log](https://github.com/files-community/Files/files/15043244/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by 0x5bfa** [comment]
Here too?

**Comment by JotaRata** [comment]
It's still kinda broken if you have Open folders with a single click in column layout option disabled (open with double click)
