### ISSUE TITLE
FILES failure to install version - 3.3.0.0

### ISSUE THREAD

**Issue by P1A380** [files-community/Files#15233]
### Description

Filles; on installation, the app fails to install and says "The provided package name does not match the expected package name. Check the AppX

### Steps To Reproduce

download
install

### Requirements

- e.g. Fix crash that occurs when...
fix inability to install the basic version

### Files Version

3.3.0.0

### Windows Version

10.0.22631 Build 22631

### Log File

n/a

**Comment by 0x5bfa** [comment]
Thanks for the feedback, let us clear

- have you ever installed any version of Files?
- which version did you try with?
- Can you try:
  1. Opening PowerShell as administrator
  2. Run this command
Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/stable/Files.Package.appinstaller
  3. See if Files is in the start menu all apps section

**Comment by 0x5bfa** [comment]
Thanks for the feedback, let us know:

- have you ever installed any version of Files?
- which version did you try with?
- Can you try:
  1. Opening PowerShell as administrator
  2. Run this command
Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/stable/Files.Package.appinstaller
  3. See if Files is in the start menu all apps section

**Comment by Josh65-2201** [comment]
From the error it seems like Files is installed, please follow the instructions at https://files.community/docs/install#:~:text=starting%20an%20update.-,Steps%20required,-for%20the%20%E2%80%9Cclassic

If Files isn't shown in the start menu, try
1. Open an Admin powershell
2. run 
```
Get-AppXPackage Files* | Remove-AppXPackage
```
3. Follow the instructions at the link again

**Comment by Josh65-2201** [comment]
@P1A380 Can you try the steps requested in the last comment

**Comment by YannickBiet** [comment]
I was stucked here, thanks for posting the workaround @Josh65-2201 !
