### ISSUE TITLE
Performance issue on opening Files

### ISSUE THREAD

**Issue by LikiaBili** [files-community/Files#15239]
### What feature or improvement do you think would benefit Files?

When i open Files, it usually take like 3 seconds to start up and loads every tab that i don't need currently
I was thinking if instead of closing the window, hide it using the windows handle thing (that won't even show in the taskbar) and just unhide it when it was opened again
or just more simpler, only load the nessasary tabs that you opened Files for, like i have files as the default file manager, so if i open a folder, only load the tab of the folder and just ignore the other tabs until you switched to it

### Requirements

- Hide the window when closing
- Show window upon opening

(if the user set the Files to be opened in background)
or
- Ignore loading tabs you don't need

or both

### Files Version

3.3.0.0

### Windows Version

10.0.19045.3930

**Comment by LikiaBili** [comment]
yeah and also by the way, if the application is minimized, when you open a folder, it won't automaticly be put to the front of the screen

**Comment by yaira2** [comment]
Thank you for your feedback, you can configure this by changing the startup setting to "Open new tab".

**Comment by LikiaBili** [comment]
What if I want to preserve these tabs for later use?
Like I'm cleaning my desktop, ill look for which of these are useful and what I can delete, and I want to get back to work with my working tabs open
Nevermind ill just make the feature on my own and PR it

**Comment by Josh65-2201** [comment]
This is already being tracked here #11900

**Comment by yaira2** [comment]
> What if I want to preserve these tabs for later use?

It's not supported yet, but we're planning this in the issue @Josh65-2201 linked. We don't have a timeline yet, but it's a feature we've been looking forward to as well. You can subscribe to #11900 or add a comment to be notified when it's added.
