### ISSUE TITLE
Bug: Files window doesn't focus when opened from another program

### ISSUE THREAD

**Issue by join-xu2021** [files-community/Files#15234]
### Description

When I have launched the files app and I have a folder open, I minimize the interface and then I open a folder on the desktop, but the interface doesn't show up at the top, but I check and find that it does open the folder.

### Steps To Reproduce

1. Open folder a
2. Minimize the interface to the taskbar
3. Double-click to open another folder b
4. The software still appears in the taskbar, not at the top.
5. Check the software interface and find that folder b has been opened.

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.3.0.0

### Windows Version

10.0.22635.3500

### Log File

[debug.log](https://github.com/files-community/Files/files/15048370/debug.log)

**Comment by 0x5bfa** [comment]
Thank you for the feedback!

So, the issue you reported is where opening a folder doesn't bring the app window to the top foreground, where you can visually see?

**Comment by join-xu2021** [comment]
Yes, the folder is opened, but the software interface doesn't pop up and remains minimized in the taskbar.
