### ISSUE TITLE
Need Vertical List Layout

### ISSUE THREAD

**Issue by tabethereal** [files-community/Files#15237]
### What feature or improvement do you think would benefit Files?

Make the List layout vertical rather than horizontal

### Requirements

- make a vertical list layout
- or add grid layout with smallest icon in default windows explorer

### Files Version

3.3.00

### Windows Version

10.0.22621.1848

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Files can already go as small as Windows File Explorer using the grid view
![image](https://github.com/files-community/Files/assets/26977075/f455b30d-d9b6-481b-bb62-4a9f0f323b74)

What reason do you want a vertical list view?

**Comment by yaira2** [comment]
Thank you for your feedback, a vertical list view isn't currently planned, but you can access a smaller grid view as shown in the screenshot @Josh65-2201 posted.

**Comment by tabethereal** [comment]
Yea I know there's grid view in files, but even the smallest icons they are bigger than windows default explorer's small grid view, as shown in the pictures following:

![windows smallest grid](https://github.com/files-community/Files/assets/145373380/3edcdaa8-b770-44c5-8ffd-3c789f5e62a8)

![files smallest grid](https://github.com/files-community/Files/assets/145373380/5ffa614c-f221-4607-bc88-34d626087947)

I'm just used to view files in the smallest grid view in a folder. This helps me to see whats in this folder clearly. But in files the grid view's icons are too big, which means i can see fewer files in a view than before. I prefer the icons with the same size as the List view, but it is horizontal. So all I need is actually **a vertical view with smaller icons**.

> Thanks for the feedback, Files can already go as small as Windows File Explorer using the grid view ![image](https://private-user-images.githubusercontent.com/26977075/324209638-f455b30d-d9b6-481b-bb62-4a9f0f323b74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2ODUyNzksIm5iZiI6MTcxMzY4NDk3OSwicGF0aCI6Ii8yNjk3NzA3NS8zMjQyMDk2MzgtZjQ1NWIzMGQtZDliNi00ODFiLWJiNjItNGE5ZjBmMzIzYjc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDA3MzYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4NWU0MjY3MDlkMDgyMzA4NDNmMzU0MDg0ODBiZWVhYmNiMjRmMzM4NmU3OTU0ZTMzY2EzYzcxMDVlYWFmNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JlWMLsvt844xvufQEck3RT1y5ijETCpUesXpJUonBQQ)
> 
> What reason do you want a vertical list view?

**Comment by yaira2** [comment]
> I'm just used to view files in the smallest grid view in a folder. This helps me to see whats in this folder clearly. But in files the grid view's icons are too big, which means i can see fewer files in a view than before. I prefer the icons with the same size as the List view, but it is horizontal. So all I need is actually a vertical view with smaller icons.

Thank you for your feedback. We're open to reconsidering this in future, and we'll keep an eye out for similar feedback to see if there is additional interest.
