### ISSUE TITLE
Please allow a function to have the data transfer window not built in to the files app

### ISSUE THREAD

**Issue by MattPolster** [files-community/Files#15238]
### What feature or improvement do you think would benefit Files?

Hey I love this app! You've done overall an amazing job for making the ideal file explorer that Microsoft won't lol For whatever reason.

However one, small small thing... Would love to see the file transfers not being handled by this program. A function to disable that so the file transfer would pop up by default windows transfers or even Tera Copy pro. I find the file transfer feature in the top right hand corner a really bad implementation and not nearly as useful as the rest of the app is. It's too hidden, and not as feature rich as the rest of the app. I would love a feature to be able to just, turn that part off. 

Have a great day!

Cheers,

Matt

### Requirements

- This would make file transfers more native to what people would traditionally expect, and not question where their file transfers went
- Would allow the user to use whatever file transfer programs they would like to use and work in harmony with them (TeraCopy Pro)
- Overall, would allow more flexibility for the app, and less for it to have to manage, as this part of the app seems half baked.

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3447

**Comment by yaira2** [comment]
Thank you for your feedback, we're currently tracking this in #7518. You can add a comment of subscribe to that issue to be notified of any updates.
