### ISSUE TITLE
PREVIEW FILES WITH QUICK LOOK

### ISSUE THREAD

**Issue by SKU003** [files-community/Files#15241]
### Description

So I've been using Quick Look for a while so that I can enjoy the feature of previewing before opening, I've noticed that it works on your software however when you hold the space bar and then release after previewing, it doesn't disappear like the way the built-in Windows explorer does it. Instead, it stays there, so you have to press on the space bar to close it. I'm not sure if it's something that be done on your part or Quick looks part. I'm not sure if this is a bug or a feature to be added in the near future.

Also noticed your thing to copy the File Apps version or windows doesn't copy, checked my clipboard nothing there.

https://github.com/files-community/Files/assets/117542049/42eed681-7c48-4c7f-ada4-9da60f487efe

### Steps To Reproduce

1. Get Quick Look 
2. Go to Windows Explorer
3. Hold the space bar for it to preview.
4. Then release when you've seen enough and it'll close itself.
5. Do the same with the Files App.

### Requirements

— Fix Hot key function that occurs when using Quick Look.

### Files Version

3.3.0.0

### Windows Version

23H2 - 22631.3447

### Log File

[debug.log](https://github.com/files-community/Files/files/15051956/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, we're happy to see you taking advantage of this integration. Can you confirm if it's the same as this report #6620?

**Comment by SKU003** [comment]
It's somewhat close, he's more of an issue, while mine is more of it should work when you are holding the space bar and previewing it then release the Space bar automatically closes the preview.

**Comment by yaira2** [comment]
In any event they both refer to the same request, so I think we can continue tracking in #6620

**Comment by 0x5bfa** [comment]
@SKU003 You can comment on that issue about problem you concern and idea you have there.
For further news, you can click Subscribe in the right side panel of the issue's page.
