### ISSUE TITLE
Late Storage update

### ISSUE THREAD

**Issue by Aspirata** [files-community/Files#15243]
### Description

When I delete something, the amount of free disk space doesn't change, but after a while (Quite a long time, 10-30 minutes ig) it is being updated

### Steps To Reproduce

Uhhh, well, just delete something and then look at your free disk space at home page

### Requirements

pls fix that

### Files Version

3.3.0.0

### Windows Version

22635.3430

### Log File

[debug.log](https://github.com/files-community/Files/files/15052729/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #6182 . You can check there or click subscribe in the right sidebar for updates.

**Comment by Aspirata** [comment]
Ok, thanks 😀
