### ISSUE TITLE
Misaligned OneDrive sync status icon in Grid layout

### ISSUE THREAD

**Issue by jobsrobson** [files-community/Files#15242]
### Description

When a folder synced with OneDrive are displayed in grid layout, the sync status icon is misaligned with the file name. Even when there are no line breaks in any file name, this issue persists.

![misaligned_onedrive](https://github.com/files-community/Files/assets/60002861/904bbadf-7647-4cc2-a1b9-85a6a9a36b92)
__

### Steps To Reproduce

1. Open a folder synced with OneDrive
2. Select 'Grid' in Layout options

### Requirements

Expected behavior: Align the sync status icon with the first line of the file name.

### Files Version

3.3.0.0

### Windows Version

22631.3520

### Log File

[debug.log](https://github.com/files-community/Files/files/15051994/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, this issue is on our todo list to fix and is being tracked in #14332. Please subscribe to the issue or add a comment to be notified when it's resolved.
