### ISSUE TITLE
Music Column Names in folders containing audio files

### ISSUE THREAD

**Issue by erikuzsempai** [files-community/Files#15244]
### What feature or improvement do you think would benefit Files?

I work a lot with folders containing audio files, these are audio tracks for English Language classes, and I rely on watching the corresponding tags to identify them, like this:  

![image](https://github.com/files-community/Files/assets/98641363/55b1359c-5842-49ef-874f-4908a409bba3)

While in FILES the only I get is this:

![image](https://github.com/files-community/Files/assets/98641363/84829827-885e-4f8f-ada6-655ebd8cacff)

I use FILES every day for file exploring, but when I need to work with my audio files I'm obligated to use windows explorer. This is the only feature I need to switch to files completely. 

### Requirements

- This proposal will accomplish FILES to identify audio folders and show proper columns with tags view in details view

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3520

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #8366 . You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
Agreed, I'm looking forward to this as well. This is actually part of a broader feature request, and being tracked in the issue @Josh65-2201 linked above.
