### ISSUE TITLE
Bug: Run as admin doesn't show on `.ahk` files

### ISSUE THREAD

**Issue by MahmoudAli96505** [files-community/Files#15250]
### Description

I was trying to open .ahk file as admin but couldn't because I couldn't see that option

### Steps To Reproduce

1. Make a .ahk file from new menu
2. Right the .ahk file

### Requirements

- Show run as admin option on .ahk files

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3447

### Log File

[debug.log](https://github.com/files-community/Files/files/15083371/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
I'm working on this in #15417
