### ISSUE TITLE
Favorites are duplicated when double-panel mode is activated

### ISSUE THREAD

**Issue by axelitbue** [files-community/Files#15252]
### Description

When I open Files with "Double-Panel-Mode" my favourites are duplicated. On Single-Panel-Mode all is good (It's okay for "Sicherung")

![single-panel-mode](https://github.com/files-community/Files/assets/165209091/bc346ae5-7cf4-4a05-9766-f03889126c8f)
![double-panel-mode](https://github.com/files-community/Files/assets/165209091/3af50768-7dac-4812-a879-769ea2f8a41e)

### Steps To Reproduce

- Activate Double-Panel-Mode
- Restart Application

### Requirements

No special requirements, it happens all the time

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3447

### Log File

[debug.log](https://github.com/files-community/Files/files/15088079/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #14555. You can check there or click subscribe in the right sidebar for updates.
