### ISSUE TITLE
Virtual Desktop support

### ISSUE THREAD

**Issue by Izzmo** [files-community/Files#15258]
### What feature or improvement do you think would benefit Files?

I run multiple virtual desktops and it would be nice to better support this vs. when I open links or use the hot key "Windows + E" to not switch desktops but instead open a new instance of Files in that virtual desktop.

Maybe this already exists, but I haven't figured out how to do it if so.

### Requirements

**GIVEN** two virtual desktops, Desktop A and Desktop B
**AND** Desktop A has an instance of Files open
**AND** Desktop B is currently active
**WHEN** pressing the hotkey "Windows + E"
**THEN** it will stay on Desktop B and open a new instance of Files.

### Files Version

3.3.0.0

### Windows Version

10.0.22621.3527

**Comment by Josh65-2201** [comment]
Thanks for the feedback, This is already working as you described, can you see if this is an issue in the preview version. https://files.community/download

**Comment by yaira2** [comment]
@Izzmo we're having trouble reproducing this issue, if it's still an issue in v3.4.1, please let us know and we'll try investigating further.
