### ISSUE TITLE
I hope to support identifying files starting with "." as hidden files.

### ISSUE THREAD

**Issue by ji-jinlong** [files-community/Files#15255]
### What feature or improvement do you think would benefit Files?

I hope to support identifying files starting with "." as hidden files.

Many people use WSL now, but when Files opens WSL or the Windows personal directory, there are many files starting with ".", most of the time we don't need to open or modify these files, the best way is to hide them like in Linux.

### Requirements

- Identify files starting with "." as hidden files
- Set a switch for this feature to be turned on or off by those who need it
- Default to on when opening WSL

### Files Version

3.3.5.0

### Windows Version

10.0.22635.3500

**Comment by Josh65-2201** [comment]
Thanks for the feedback. You can already turn them off in Files settings > Files & Folders > Hidden items > Disable show dot files

**Comment by 0x5bfa** [comment]
Thanks for the explanation!

For example, you want to mark extension only file as a hidden file, such as .DS_Store and .gitignore?

**Comment by ji-jinlong** [comment]
> Thanks for the explanation!
> 
> For example, you want to mark extension only file as a hidden file, such as .gitignore? Do you wanna make option for folders too, such as .DS_Store?

@0x5bfa 

I do want to mark files like .gitignore and folders like .git as hidden. The current "Disable show dot" option already achieves this effect. But I don't have a Mac device around me, so I can't test .DS_Store.
![PixPin_2024-04-25_15-04-40](https://github.com/files-community/Files/assets/61379293/3f41fa52-a09a-4589-92fd-1f5579576cba)
![PixPin_2024-04-25_15-04-20](https://github.com/files-community/Files/assets/61379293/97430713-1414-4128-9fb7-2ef5a332ea0b)

**Comment by 0x5bfa** [comment]
So you wanna show dot files even hide files is turned on, and have that option in Files?

**Comment by ji-jinlong** [comment]
> So you wanna show dot files even hide files is turned on, and have that option in Files as a separate setting?所以你想显示点文件，即使打开了隐藏文件，并在文件中将该选项作为单独的设置？

@0x5bfa

**Comment by ji-jinlong** [comment]
> So you wanna show dot files even hide files is turned on, and have that option in Files as a separate setting?

@Josh65-2201 

This issue stemmed from my misunderstanding, there was no problem with the software itself. Sorry for taking up your valuable time. I will close this issue.
