### ISSUE TITLE
Crash on app start

### ISSUE THREAD

**Issue by NextinMono** [files-community/Files#1525]
Hello, I tried installing the app, but as soon as I open it (or a few seconds later) it crashes. I checked the log file and it seems like it's flagging a drive as a floppy drive due to the letter, and can't find it

[debug.txt](https://github.com/files-community/files-uwp/files/4955607/debug.txt)

**Comment by Talisman39ar** [comment]
It frequently crashes for me after 2-4 clicks into folders to get to a file. Happens on both my machines (both running Windows 2004, though it was also happening before either got updated). It's not consistent and I haven't found an underlying pattern
, but happens enough where it mostly discourages me from using the app unfortunately. Log file attached if that's helpful.

[debug.txt](https://github.com/files-community/files-uwp/files/5009214/debug.txt)

**Comment by hunterlan** [comment]
> Hello, I tried installing the app, but as soon as I open it (or a few seconds later) it crashes. I checked the log file and it seems like it's flagging a drive as a floppy drive due to the letter, and can't find it

I think, you have a hidden drive, and app can't recognize it.

**Comment by WindowsRed** [comment]
> > Hello, I tried installing the app, but as soon as I open it (or a few seconds later) it crashes. I checked the log file and it seems like it's flagging a drive as a floppy drive due to the letter, and can't find it
> 
> I think, you have a hidden drive, and app can't recognize it.

Funnily enough, the only hidden drive is the EFI partition

**Comment by yaichenbaum** [comment]
@NextinMono Is this still an issue in v0.21?

**Comment by NextinMono** [comment]
> @NextinMono Is this still an issue in v0.21?

I've tried, it works now!
