### ISSUE TITLE
Bug: Add shortcut/accelerator keys in the context menu

### ISSUE THREAD

**Issue by andrew-james-heard** [files-community/Files#15257]
### What feature or improvement do you think would benefit Files?

For a keyboard user, having to cursor+right or left through all the top or bottom menu items to get to the Open With flyout menu is quite tedious. Windows Explorer has shortcut keys.

### Requirements
- Show shortcuts in the context menu when pressing Alt

### Files Version

3.3.0.0

### Windows Version

23H2

### Comments

The following 2 screen caps of Files & Windows Explorer contrast the handling of the same file after the Windows context key is pressed on a selected file:

![Files](https://github.com/files-community/Files/assets/7908676/db96eef7-fc0f-4e97-b38a-4e5b7826c6c1)

![Windows Explorer](https://github.com/files-community/Files/assets/7908676/d4410e70-a5b0-4e5f-936e-585454f9ba5c)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, I've added this to the project board.

**Comment by yaira2** [comment]
Thank you for your feedback, we're currently tracking this in #7505. You can add a comment or subscribe to that issue to be notified of updates.
