### ISSUE TITLE
Make Powertoys Peek work with Files

### ISSUE THREAD

**Issue by xn0vv3r** [files-community/Files#15256]
### What feature or improvement do you think would benefit Files?

Integrate Powertoys Peek (https://learn.microsoft.com/de-de/windows/powertoys/peek) the same way as QuickLook & SeerPro work already.

If i have PowerToys from Microsoft installed, I want to start the preview with e.g. Strg+Space (default Shortcut).

It's another Option to have a preview and if (like me) PowerToys is already installed I don't need another application for the same UseCase.

### Requirements

- when I press the configured Shortcut (as defined in PowerToys configuration) for PowerToys Peek, I want a preview of the file to open.

### Files Version

3.3.0.0

### Windows Version

23H2

**Comment by Josh65-2201** [comment]
Thanks for the feedback, this currently isn't possible due to power toys peek not having a way of doing so https://github.com/microsoft/PowerToys/issues/26422
