### ISSUE TITLE
Support for PowerToys Peek

### ISSUE THREAD

**Issue by DeFaLT-dj** [files-community/Files#15262]
### What feature or improvement do you think would benefit Files?

Peek feature is one of the most used features of PowerToys so adding support to it might be very benefitical for Files

### Requirements

I am not sure if this feature should added by Files or PowerToys should be adding support for Files. But if it is something Files should be supporting, clicking CTRL+SPACE should be able to launch Peek UI of PowerToys like File Explorer can.

### Files Version

3.3.0.0

### Windows Version

10.0.26100.268

**Comment by Josh65-2201** [comment]
Thanks for the feedback, this currently isn't possible due to power toys peek not having a way of doing so https://github.com/microsoft/PowerToys/issues/26422
