### ISSUE TITLE
Column layout is really hard to use

### ISSUE THREAD

**Issue by JotaRata** [files-community/Files#15266]
### Description

I'm struggling to use the column layout in Files since every time I switch (or just click) on the parent column the column layout immediately resets, making the user unintentionally open whatever folder was under the mouse at that moment, this makes the whole process of moving or copying files to another folder in the parent column very annoying.

I attach a video describing this issue:
https://github.com/files-community/Files/assets/36273501/8efd206b-5cf7-4500-a362-8fcfd4aa1bc9

Notice the immediate jump in the column layout when I click outside the leftmost panel.
I also have enabled double click to open folders in column mode and still closes the leftmost panel with a single click outside of it. 

### Steps To Reproduce

1. Open Files in column layout mode
2. Go to a deep folder tree (i.e. I selected Appdata in my example) and open one of many sub-folders.
3. With a folder opened in the leftmost panel, click on any panel on the right
4. The layout should refresh now, leaving the clicked panel as the leftmost panel in the window.

Another Scenario:
1. Drag and drop any file from one opened folder to a folder in a parent column.
2.  The column layout should reset again and possibly making the user to drop the files on an unwanted location.

### Requirements

The current opened folder (leftmost panel) should remain opened even if the user selects a folder in a parent column, it should however change when the user opens a folder in the parent column.

The transition in the layout design should be smooth and avoid sudden jumps between the columns (perhaps follow the mouse?)

The total number of columns (either empty or not) should be conserved even of folder changes to avoid sudden changes in the design, maybe close them after a period of time.

Additionally, the columns layout design should have a little margin or padding in the columns to make selecting columns or drag and dropping files easier.

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3447

### Log File

Doesn't apply since this is not an error within Files but rather a design concern

**Comment by yaira2** [comment]
Thank you for the report, we're currently tracking this in #15230. The good news is that a fix is already being worked on and we'll comment in #15230 once more information is available.
