### ISSUE TITLE
Cant uninstall files anymore

### ISSUE THREAD

**Issue by jonesy-b-dev** [files-community/Files#15268]
### Description

I want to reinstall files because i cant update it. thing is i have no uninstaller for files. 

Searched for an unstaller with void tools everything.
Tried uninstall with Revo but there files isnt in the list. 
Tried manually removing the folder but that operation fails (C:\Program Files\WindowsApps\Files_3......
Tried removing the folder through cmd(admin) but dont have permission. 

How to i remove this now?

### Steps To Reproduce

1.  Have a messed up installation
2. Try to remove it

### Requirements

- Try to uninstall

### Files Version

3.2.3.0

### Windows Version

10.0.23585.1001

### Log File

[debug.log](https://github.com/files-community/Files/files/15143189/debug.log)

**Comment by Josh65-2201** [comment]
You can right Files in the start menu > Uninstall
