### ISSUE TITLE
Basic installer gives error and Microsoft Store will not download

### ISSUE THREAD

**Issue by SMRIGK094** [files-community/Files#15260]
### Description

Provided package name does not match expected package name. Check the XAppDeploy...

I'm a sponsor twice and my avatar does not show up, and i have bought on Microsoft Store and it will not download from there either.

How do i get updates?

Thanks
Stephen Rose

### Steps To Reproduce

download classic installer (Files Stable) and try to install.
Go to MS Store and click download at top and nothing happens.

### Requirements

How to get latest installer that works. I am stuck on 3.0.1.0
[debug.log](https://github.com/files-community/Files/files/15139014/debug.log)

### Files Version

3.0.1.0

### Windows Version

10.0.22631.3447

### Log File

[debug.log](https://github.com/files-community/Files/files/15139022/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for being a sponsor, MS store buys don't show anywhere and for GitHub you have make sure you made it a public donation.

As for the error it seems like Files is installed, please follow the instructions at https://files.community/docs/install#:~:text=starting%20an%20update.-,Steps%20required,-for%20the%20%E2%80%9Cclassic

If Files isn't shown in the start menu, try
1. Open an Admin powershell
2. run 
```
Get-AppXPackage Files* | Remove-AppXPackage
```
3. Follow the instructions at the link again

**Comment by SMRIGK094** [comment]
Hi Josh,

 

Thanks- I did do a public donation in GitHub but it does not show- $100.00 in March. I can send you the documentation.

 

The link is great- THANKS.

 

Yes, files is installed at 3.0.1.1 and I wanted to update it but just could not find how. OR, does the Update Files at the tip next to the settings gear do that?

 

Thanks again- fantastic program- I’ve added Mountain Duck to add my clous accounts to Files and this is the best File explorer I have ever used.

 

All the best

Steve Rose

**Comment by Josh65-2201** [comment]
Glad it's fixed, that would be a one time thing as Files certificated changed future update will be done in the background or show as a download icon in the right corner next to settings.

You also show for me in the sponsors section 
![image](https://github.com/files-community/Files/assets/26977075/3db029fd-a187-4037-bbbc-5ce051a1748e)
