### ISSUE TITLE
Bug: Extracting large Files from 7z archive cause Files and other program to not respond

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#15263]
### Description

I believe the issue comes from Files immediately opening the default program before extraction is complete. Where as 7zip will extract first then open the default program with the file.

### Steps To Reproduce

1. Compress a large video file (200mb at least)
2. Have Windows Media Player set to open that video file type
3. Open the compressed video file in the archive
4. See Windows media player open a lock up (Files also sometimes does)

### Requirements

- Extract the clicked on file first
- When done open program like normal

### Files Version

3.3.5.0

### Windows Version

10.0.22621.3447

### Log File

[debug.log](https://github.com/files-community/Files/files/15139915/debug.log)

**Comment by yaira2** [comment]
This will be covered with #15264.
