### ISSUE TITLE
Viewing files

### ISSUE THREAD

**Issue by dpbueno** [files-community/Files#15261]
### Description

I'm noticing some interesting and unproductive situations when I use Files with Cloud drives (Ondrive, Sharepoint, Sync Files Teams).

One example:
When I'm in an application with Powerpoint and I save a new file to a cloud drive, when I view the directory the file isn't displayed, and I have to press the refresh button for the file to be displayed from the viewer.

There are other variations, but they are always related to updating the view in Files.

In a way, I also notice worse performance on cloud drives.

### Steps To Reproduce

1. Open Files in a cloud directory
2. Open a file saved in a cloud directory, like sharepoint in powerpoint
2. Use the save as option in powerpoint and save the file under a different name, but in the same directory
3. Go back to Files and notice that the new file is not in the viewer
4. Press the refresh button and see that the file is displayed

### Requirements

- e.g. Fix crash that occurs when...
Cloud drive

### Files Version

3.3.0.0

### Windows Version

10.0.19045.3930

### Log File

no

**Comment by Josh65-2201** [comment]
Thanks for the report, Cloud drives shouldn't have any different in performance from local drives.
- Are the folders contents fully loaded? (No spinner in the tab where the icon would be)
- Can you reproduce this on none cloud drive folders?

**Comment by yaira2** [comment]
The only possibility that comes to mind is if there is an error in the file watcher code. We'd like to investigate this further, but we'll need the log file to do so. Please upload the log file to GitHub so we can look into this issue.

**Comment by dpbueno** [comment]
[Uploading debug.log…]()

**Comment by Josh65-2201** [comment]
The file wasn't finished uploading. Wait for it to not say uploading then press comment
