### ISSUE TITLE
Bug: Copy and Paste does not always work

### ISSUE THREAD

**Issue by kennethsnyder** [files-community/Files#15265]
### Description

When I want to copy file and paste into a separate window (not tab).  Sometimes the paste option is not visible.  I have to repeat the copy function (by right clicking on the file) again and then it will work.

### Steps To Reproduce

right click on file and choose copy
Move to destination window
Right click to choose paste but not visible.  
Go back to original window
Repeat and then it works.

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3447

### Log File

C:\Users\kenne\AppData\Local\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState

**Comment by 0x5bfa** [comment]
What do you mean by visible?
Copy and paste uses clipboard putting those paths,

**Comment by kennethsnyder** [comment]
when you go to destination window and right click the paste icon is not visible.  I sometimes prefer to use mouse versus hotkeys.   Ctrl-Paste seems to always work.  But why isn't the paste icon visible?

**Comment by 0x5bfa** [comment]
Thanks for the info, we have a detection function that is triggered when clipboard contents has been changed and its content is the Files format.
I can’t reproduce for now.

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
