### ISSUE TITLE
Update the discord server invite link

### ISSUE THREAD

**Issue by ThunderboltCommunicationsCorp** [files-community/Files#15274]
### Description

When the discord server invite link (files community) is pressed it redirects to a page saying the invite is invalid. Please fix the link

### Steps To Reproduce

1. Click on the discord server link
2. Get redirected
3. Get annoyed by the error saying invalid invite

### Requirements

Fix the invite link

### Files Version

None

### Windows Version

Unneeded

### Log File

No log

**Comment by Josh65-2201** [comment]
Thanks for the report, Where is this discord link at?

**Comment by ThunderboltCommunicationsCorp** [comment]
On the main page of the project here: https://github.com/files-community/Files

**Comment by Josh65-2201** [comment]
The Invite works for me. Are you sure your not on one of the old branch's readme's.

**Comment by 0x5bfa** [comment]
That link has no expiration date so it should work, at least for me it does.

**Comment by ThunderboltCommunicationsCorp** [comment]
Probably because I'm on the main branch and clicking on the link just redirects to an invalid request.

**Comment by kryzet** [comment]
I found that the same problem occurs at https://discord.gg/files, which can be accessed from the app's settings menu, in the About section.
![Image](https://github.com/user-attachments/assets/a3a5d0f1-2481-4341-8ab7-cf895ba65ddd)
![Image](https://github.com/user-attachments/assets/794d8afd-402c-42b8-9705-45634d562ab6)

Here's some debug info, in case you need it:

- **Files Version**: 3.8.0.0
- **Windows Version**: 10.0.22631.4460

**Comment by Josh65-2201** [comment]
It's a issue on Discord end or your Discord account is banned from the server, the link is correct and working for me

**Comment by kryzet** [comment]
If the link is correct and working for you, and I've never joined the server before, that must mean it's a problem with the server. I have indeed joined a few other Discord servers using custom invite links and they worked.
