### ISSUE TITLE
Anyway to have directory tree structure shown on left side for each drive?

### ISSUE THREAD

**Issue by kennethsnyder** [files-community/Files#15270]
### What feature or improvement do you think would benefit Files?

Option to Display Directory Tree structure versus using columns layout.

### Requirements

It will make it easier to copy / move files from one directory to another.   Column Layout utilizes too much space.

### Files Version

3.3.0.0

### Windows Version

Edition	Windows 11 Pro Version	23H2 Installed on	‎11/‎12/‎2023 OS build	22631.3527 Experience	Windows Feature Experience Pack 1000.22700.1003.0

### Comments

Similar to windows file explorer

**Comment by Josh65-2201** [comment]
Thanks for the feedback, The isn't an option currently, we're tracking this in #1928 . You can check there or click subscribe in the right sidebar for updates.
