### ISSUE TITLE
Wait.......what the hell!?

### ISSUE THREAD

**Issue by pranavinsight** [files-community/Files#15277]
### Description

This is not installing and always fails the smartscreen check 💢 
What have you done @files-community!!!! 😡 

### Steps To Reproduce

1. Just fix it so it is compatible to the SmartScreen...

### Requirements

- e.g. Fix crash that occurs when... I open the Microsoft Store.

### Files Version

idk

### Windows Version

20H2

### Log File

none

**Comment by 0x5bfa** [comment]
I'd like to remind you of the code of conduct.

Can you try install from https://files.community/download

**Comment by pranavinsight** [comment]
It comes like this:
![TTAAAAAAAAA](https://github.com/files-community/Files/assets/165383057/e0f468dd-0e22-412a-b9b6-608360420f2d)

**Comment by pranavinsight** [comment]
Package installer too didnt work.

**Comment by pranavinsight** [comment]
What shall i do?

**Comment by pranavinsight** [comment]
Sorry if i was rude....

**Comment by 0x5bfa** [comment]
No problem:)

This problem may be associated with timezone. Can you share your timezone or just check if it's correct?

**Comment by pranavinsight** [comment]
India Standard Time

**Comment by 0x5bfa** [comment]
I guess this is an issue around Windows since no one has ever reported this issue before.

**Comment by Josh65-2201** [comment]
SmartScreen is apart of Windows defender not Files so there isn't anything we can do there. As for the store you will likely have to be signed into a Microsoft account as it paid there for donation purposes.

You can try
1. Update security definitions. Windows Defender > Virus and threat protection > Protection updates > Check for updates
1. Opening PowerShell (Windows default not PowerShell 7) as administrator
2. Run this command
```Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/stable/Files.Package.appinstaller```
3. See if Files is in the start menu all apps section
