### ISSUE TITLE
Pinned items not loading after File's first start after Windows booted

### ISSUE THREAD

**Issue by emmi-ari** [files-community/Files#15278]
### Description

Sometimes the pinned section of the left sidebar is empty, when Files is started. I have to restart the app completely (close it through the tray icon) to have them reappear.
One restart has always been enough until now.
The issue only seems to happen when Files is started for the first time after starting Windows.

Here's how it looks like when pinned Items are not loaded:
![image|](https://github.com/files-community/Files/assets/28660694/87b81f71-f80c-4f21-b7a5-6828c299abee)

### Additional info
* Saving recent files and folders is disabled on the system.
* Files is set to automatically start upon Windows start

### Steps To Reproduce

1. Start Windows
2. Open a Files window

### Requirements

Expected behaviour is that my pinned items are shown upon opening a Files window after starting Windows

### Files Version

3.3.0.0

### Windows Version

Windows 10 Build 19045.4291 (22H2)

### Log File

[debug.log](https://github.com/files-community/Files/files/15162209/debug.log)

**Comment by yaira2** [comment]
We're currently testing a fix and we'll post an update in #13116 if it works.
