### ISSUE TITLE
'Save as...' dialog windows bugged

### ISSUE THREAD

**Issue by JustONOFF** [files-community/Files#15275]
### Description

I wanted to save files from programs or a browser (for example exporting a file as a PDF etc.) on multiple occasions now and usually a window pops up from the windows explorer where you can specify how you want to safe a file. But since I installed Files, no such window pops up, instead A Files window pops up but i cant do anything save-related, it just behaves like an ordinary Files window. Addditionally to that, a .txt file called 'save_dialog' gets created on my desktop folder, which confuses me why that happens. I then tried to uninstall Files from my computer and now no save window pops up on my system, instead an error pops up saying that files.exe could not be found. I tried to disable the 'set as default' option under the advanced settings and after uninstallation even tried to run a .reg file postet here on github to manually set the registry keys back to their default values. How can i revert the changes made by Files so a normal windows explorer save dialog does appear again so I can save my files as intended? Or alternativeley is there a way to get a save dialog in Files?

### Steps To Reproduce

1. Install Files
2. Set Files as the default browser and then unset it (Not sure how relevant this is)
3. Open a program or web browser to save something ('save', 'save as', 'export' etc.)
3a. _Now a Files window pops up but I can't save anything there_
4. Uninstall Files
4a.  _An error window pops up, saying files.exe cannot be found_

### Requirements

- Implement a proper save dialog window for Files
- Revert everything back after uninstallation so windows explorer can behave normally

### Files Version

3.3.5.0

### Windows Version

10.0.22631 Build 22631

### Log File

[save_dialog.txt](https://github.com/files-community/Files/files/15155883/save_dialog.txt)

**Comment by Josh65-2201** [comment]
Thanks for the report, Files doesn't change the save/open dialogs. Have you built from the source code before and enabled it there?

**Comment by Josh65-2201** [comment]
The option is a dev only feature. You will have to built it from source and turn the option off in Files settings > Advanced

**Comment by 0x5bfa** [comment]
@gave92 I do have the same issue.
When I try to open Save As and Open dialogs in Notpad it seems to hang; the window becomes uninteractive just like disabled but Windows seems not to be aware.
