### ISSUE TITLE
"GenerateMSBuildEditorConfigFile" does not exist in the project

### ISSUE THREAD

**Issue by ThunderboltCommunicationsCorp** [files-community/Files#15273]
### Description

I attempted to build version 0.6.5 of Files in Visual Studio 2022 and got the error "GenerateMSBuildEditorConfigFile" does not exist in the project after attempting to build the project

### Steps To Reproduce

1. Download the source code from Github
2. Opened the project in VS 2022
3. Attempted to build the project
4. Got the error "GenerateMSBuildEditorConfigFile" does not exist in the project

### Requirements

The expected behavior is for the application to be built and successfully opened. An appxbundle installer to install the app that way will fix my issue if provided.

### Files Version

0.6.5

### Windows Version

22631.3527

### Log File

There is no log in this case

**Comment by Josh65-2201** [comment]
Thanks for the report, version 0.6.5 isn't supported and make no sense to be installed or used. Why are you trying it install that one?

**Comment by ThunderboltCommunicationsCorp** [comment]
I am a Youtuber and I am attempting to collect as many old versions of Files at the moment and managed to get a few from 0.5 and earlier since there is a download for them, but all the other 0.x releases don't have downloads.

**Comment by Josh65-2201** [comment]
Since it old and very much not supported, the best bet is to try build 0.7.5 https://github.com/files-community/Files/tree/v0.7.5?tab=readme-ov-file#building-files-uwp-from-the-source-code and then see if you get the same error on 0.6.5 but there aren't downloads for it.

**Comment by ThunderboltCommunicationsCorp** [comment]
Thank you but I attempted that version as well and got the same error, so I tried to fix the older version's error. Thanks anyway

**Comment by ThunderboltCommunicationsCorp** [comment]
I attempted all the builds up to 1.5 and none of them work. It just got worse every time I tried a version higher than the previous one. Unfortunately I'll have to spend hours of searching on google for an unofficial source that still has these versions. Any help is appreciated. Thanks though.

**Comment by 0x5bfa** [comment]
You can see Releases tab and go to older. There're some releases which attached msixbundle file, which might enable you to install without building.

**Comment by yaira2** [comment]
It should still work to build the older versions, but we don't have a lot of documentation for them. It might be easier if you use VS 2019. Feel free to join our Discord (discord.gg/files) and we can try to provide additional help in the app-development channel.
