### ISSUE TITLE
Latest release returned missing tagged folders bug

### ISSUE THREAD

**Issue by yIsItSo** [files-community/Files#15287]
### Description

Latest release returned missing tagged folders bug

### Steps To Reproduce

see previous report

### Requirements

fix

### Files Version

3.3.6.0

### Windows Version

10.0.22635.3566

### Log File

[debug.log](https://github.com/files-community/Files/files/15184806/debug.log)

**Comment by Josh65-2201** [comment]
There wasn't a fix for that issue made. were keeping track in your original issue

**Comment by yIsItSo** [comment]
Strange,

I noticed it slowly "corrected itself" over time.
After installing the newest release the bug is back in full force and nothing so far seems to correct it.

Good luck

________________________________

**Comment by yIsItSo** [comment]
Just restarted Windows and now some folders (whose tag values I was
checking just before ?)  appear correctly.

**Comment by yaira2** [comment]
Can you link the other issue?

**Comment by Josh65-2201** [comment]
https://github.com/files-community/Files/issues/15214
