### ISSUE TITLE
Enhance Metadata Handling in Files: Display and Edit "Keywords" Metadata

### ISSUE THREAD

**Issue by Foadsf** [files-community/Files#15291]
### What feature or improvement do you think would benefit Files?

I am [trying](https://superuser.com/q/1841180/588662) to use metadata to organize and access my PDF files, specifically through the "Keywords" property, which I manage using a [PowerShell script](https://gist.github.com/Foadsf/51e6838e67390402431b54bbd3976149) with [ExifTool](https://exiftool.org/). Files does not display or allow editing of the "Keywords" metadata in the detailed view or property windows. Incorporating this functionality would significantly streamline workflows for users who rely on metadata for file management, reducing the need for external tools.

### Requirements

- Display "Keywords" Metadata in Detailed View: In the detailed view mode, allow the "Keywords" metadata to be visible alongside standard file attributes like Name, Type, and Date.
- Integrate Metadata Reading Functionality: Utilize tools like ExifTool to fetch and display metadata from files, allowing users to view metadata categories directly in Files.
- Enable Metadata Editing in Property Window: Provide functionality to edit metadata such as "Keywords" directly within the Files’ property window, enhancing user efficiency and interaction with file properties.
- Categorized Metadata Display in Navigation Panel: Implement a feature to categorize files based on their metadata in the navigation panel, offering users a quick way to filter and access files.
- Synchronization of Metadata Changes: To maintain consistency, ensure that any changes made to the metadata within Files are updated in the file properties and vice versa.
- User-Friendly Metadata Management Interface: Design the metadata features to be intuitive and seamlessly integrated into the existing Files UI, ensuring ease of use without overwhelming the user.
- Extend Support for Various File Types: While initially focusing on PDFs, gradually expand metadata support to other file types commonly used in professional environments.

### Files Version

3.3.0.0

### Windows Version

10.0.19045.4291

### Comments

Adding these features would position Files as a more robust and versatile file management tool, especially valuable for professionals who utilize metadata extensively. Integrating these capabilities directly into Files could potentially eliminate the need for several third-party tools, offering a more unified and streamlined user experience.

**Comment by yaira2** [comment]
Thank you for your feedback. Support for additional metadata (including from third parties) is being planned in #8366. Please subscribe to that issue to be notified when we have an update.
