### ISSUE TITLE
The right-click options  are very slow.

### ISSUE THREAD

**Issue by pranavinsight** [files-community/Files#15295]
### What feature or improvement do you think would benefit Files?

The right-click options always delay when i right-click any file/folder. If this was faster, it would be very nice... My previous issues were like an `unnecessary` report..... And i am sorry for that.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.3.0.0

### Windows Version

20H2

**Comment by 0x5bfa** [comment]
Sorry but this is the SDK problem.

Probably asking WinAppSdk repo team would be good.

**Comment by yaira2** [comment]
@pranavinsight thank you for your feedback, improving the performance when loading shell extensions is on the ToDo list (#11112). In the meantime, you can work around this by enabling the option to move them to a sub menu.
![image](https://github.com/files-community/Files/assets/39923744/8995c904-5a2e-448d-9833-a9104e75df17)

**Comment by pranavinsight** [comment]
Oh, okay! So, you can fix that in an update maybe? That's nice! And also I forgot to mention that it takes alot of memory from my PC. In short words, this is too hot for my potato windows 10🤣🤣🤣

**Comment by pranavinsight** [comment]
Thank You @yaira2 ! I can try that maybe...

**Comment by pranavinsight** [comment]
Oh... and also, for people using installer version of Files should get like some kinda alert message or an updating executable.... I see you are releasing a new version of files rn. 
I don't want to be having an outdated version like that!

**Comment by pranavinsight** [comment]
Maybe i should create a new issue about it?

**Comment by pranavinsight** [comment]
@yaira2 and @0x5bfa , it's in your hands to decide and solve the issue. Or atleast someone solve it(i am not being rude). And thank you for supporting me for installation of Files!

**Comment by pranavinsight** [comment]
And for a surprise, I forked you!!!!!!!! 🎉🎉🎉🎉

**Comment by pranavinsight** [comment]
And i am creating a new website.

**Comment by yaira2** [comment]
> Oh... and also, for people using installer version of Files should get like some kinda alert message or an updating executable.... I see you are releasing a new version of files rn. I don't want to be having an outdated version like that!

The sideload version of Files has built-in auto update.

**Comment by pranavinsight** [comment]
Where is it?
>The sideload version of Files has built-in auto update.

**Comment by pranavinsight** [comment]
Where is that 'sideload' version?

**Comment by pranavinsight** [comment]
Put it here. I need it. It's essential!

**Comment by Josh65-2201** [comment]
All versions have auto update, the installer is also the sideloaded version.

**Comment by pranavinsight** [comment]
Oh! Okay, how to update then? This file manager is gonna be intresting! 😄

**Comment by Josh65-2201** [comment]
It will do it in the background and/or show a install button next to settings if there is an update

**Comment by pranavinsight** [comment]
Okay...

**Comment by pranavinsight** [comment]
That's nice!

**Comment by pranavinsight** [comment]
Btw, check my new website! [MatrixType Second Generation(v.2.0.0](pranavinsight.github.io/matrixtype2.0)

**Comment by pranavinsight** [comment]
Btw, check my new website [MatrixType 2.0](pranavinsight.github.io/matrixtype2.0)

**Comment by pranavinsight** [comment]
> Btw, check my new website! [MatrixType Second Generation(v.2.0.0](pranavinsight.github.io/matrixtype2.0)

Uhh, why is my link going crazy???

**Comment by pranavinsight** [comment]
In the worst case scenario like this, i have another repository! [MatrixType 2.0](pranavinsight.github.io/MatrixType-v.2.0.0)

**Comment by pranavinsight** [comment]
> Btw, check my new website! [MatrixType Second Generation(v.2.0.0](pranavinsight.github.io/matrixtype2.0)

Noooo! This is also NOT working! Seriously GitHub? I guess it's just not the correct time to discuss another topic.
Another website link:
https:://pranavinsight.github.io/fivestarcoffeemakers2.0/

This is having a specialised theme, not to mention that it has an unavoidable bug that we will later fix in an update.

**Comment by pranavinsight** [comment]
Wait a minute, now i realized that only the MS Store version has the updating feature and they mentioned that only in that version you can recieve updates...

Can i believe you?

**Comment by Josh65-2201** [comment]
No where does it say Files only has auto update on the store. All version have auto update.

**Comment by pranavinsight** [comment]
> Please stop post random website links here.

Oh! I am sorry. Just for you to check one of my repos. I am sorry if it bothers you 😇

**Comment by pranavinsight** [comment]
> No where does it say Files only has auto update on the store. All version have auto update.

Ok, then when another update is coming? I am going to test that feature!

**Comment by pranavinsight** [comment]
Is that 3.0.2 or 3.0.1?

**Comment by Josh65-2201** [comment]
3.4.0.0 Is out now, It should have updated if you check Files settings > About, but if not you can try using the installer https://files.community/download as sometimes Windows causes issues with built in updater.

**Comment by pranavinsight** [comment]
Wait. I already have it
This? I installed that  when i was testing it, ( #15295)
Files Version: 3.4.0.0
