### ISSUE TITLE
Wait!!!!!!!!! A big thanks

### ISSUE THREAD

**Issue by pranavinsight** [files-community/Files#15294]
### What feature or improvement do you think would benefit Files?

Thank you files community for your support. And importantly, thank you @0x5bfa ! I love Files and, This is very awesome.
A solid Fivestar rating for the design!! ⭐ ⭐ ⭐ ⭐ ⭐ 

Thank you!
As always,
LOVE SUPRA, LOVE CARS!

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

just a thanks note!

### Windows Version

dsogykobnp['thjumbled random string

### Comments

xm,bnk=string

**Comment by 0x5bfa** [comment]
Thank you, we’re glad that you like the app.

Closing due to unrelativity.

**Comment by pranavinsight** [comment]
Wait...why???

**Comment by pranavinsight** [comment]
And, thank you once and for all! I personally like this app. Btw, itseems like you are on a hectic schedule on this repo... So, take care
