### ISSUE TITLE
Bug: Files doesn't open items by file name and uses selection order

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#15308]
### Description

*

### Steps To Reproduce

1. Using Windows media player and 6 videos files named 1 to 6
2. Drag select items starting from 6 to 1
3. Click play all on tool bar or enter on keyboard
4. See video files added to queue 6 to 1
5. Select from 1 to 6
6. Click play all on tool bar or enter on keyboard
7. See video files added to queue 1 to 6

### Requirements

- Make opening files always be based on file name order rather than selection order

### Files Version

3.3.6.0

### Windows Version

10.0.22621.3447

### Log File

[debug.log](https://github.com/files-community/Files/files/15214052/debug.log)
[debug_server.log](https://github.com/files-community/Files/files/15214053/debug_server.log)

**Comment by yaira2** [comment]
Thank you for the report. Can you confirm if this is the same as #8534?

**Comment by Josh65-2201** [comment]
This one doesn't involve drag and drop just directly using Files drag selecting. It could be the same fix.
