### ISSUE TITLE
Bug: Renaming in the conflict dialog leaves the copy operation in process

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#15303]
### Description

If I change the name in the conflict dialog when copying a file, the copy itself will be completed, but it will remain in process on the status center, and I will not be able to remove the badge.

### Steps To Reproduce

1. Copy a file to a folder with a file of the same name.
2. Change the name in the conflict dialog and press Continue.
3. The copy it self will be completed, but it will remain in process on the status center.

### Requirements

The status center should indicate that the copy is complete.

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3447

### Log File

n/a

**Comment by yaira2** [comment]
Thanks for the report
