### ISSUE TITLE
Slow Loading Icon in the App File

### ISSUE THREAD

**Issue by quyetnm2795** [files-community/Files#15311]
### Description

I love the App Files, which include the column view like MacOS (great to manage huge folders). The UI is even more native than the current File Explorer of W11. The only thing that it has the loading even when reload the old folder or running in the background for indexing

![Screenshot 2024-05-06 141340](https://github.com/files-community/Files/assets/90144628/2d483c39-7c4f-4e54-b5e5-ccf750bad6d6)

### Steps To Reproduce

Just open and use it

### Requirements

- e.g. Fix crash that occurs when...
Not showing loading

### Files Version

3.3.

### Windows Version

22631.3527

### Log File

[debug.log](https://github.com/files-community/Files/files/15218021/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback
1. How long does it take for the thumbnails to load?
2. Where are these items located (eg local drive, OneDrive etc)?

**Comment by quyetnm2795** [comment]
It is local, C and D. It takes like 1 2 sec only but we can see the
animation and how annoying it is


-- 

*Marcus / Manh Quyet* (Mr.)
----------------------

Phone    : (+84) 949 279 995 - Viber/Zalo/Telegram

**Comment by yaira2** [comment]
Improving the performance is high on the todo list, the struggle is balancing performance without affecting stability (loading too many thumbnails at the same time can crash the app). We're currently tracking this in #4180, please subscribe to that issue to be notified when further improvements are available.
