### ISSUE TITLE
Crashed and shutdown

### ISSUE THREAD

**Issue by jackalteoh** [files-community/Files#15319]
### Description

When i open folder, the software just shut down. 

### Steps To Reproduce

1. Just open particular folder from the sidebar
2. Not always will crash but when it crash, it will happen for few times

### Requirements

Fix crash that occurs when open a particular folder

### Files Version

3.3.5.0

### Windows Version

10.0.19045

### Log File

[debug.log](https://github.com/files-community/Files/files/15228785/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Please update to 3.3.7.0 and see if this is still an issue. https://files.community/download
