### ISSUE TITLE
My files started to crash on my Win11 today.  I used it for a few days and this only start today. when I open, it freezes and then disappears, everytime. any fix for it?

### ISSUE THREAD

**Issue by RyanL89** [files-community/Files#15317]
### Description

My files started to crash on my Win11 today.  I used it for a few days and this only start today. when I open, it freezes and then disappears, everytime. any fix for it?

I tried repair, reset, uninstall and reinstall. Tried restoring the Win11 to a few days before, it was good for one time and after I turned off the laptop it started to do the same thing again.
I tried the preview version, it has this issue too.

### Steps To Reproduce

Open files,
Unresponsive
Then disappears

### Requirements

- e.g. Fix crash that occurs when...
Everytime when open files

### Files Version

v3.3

### Windows Version

Windows 11 Home 23H2

### Log File

[debug.log](https://github.com/files-community/Files/files/15227599/debug.log)

**Comment by gave92** [comment]
Could you try disconnecting all removable/usb devices beifore starting Files if there's any difference?

**Comment by RyanL89** [comment]
> Could you try disconnecting all removable/usb devices before starting Files if there's any difference? From the log files looks like the crash happens when you connect some new drive.

Thanks for your comments. It works.
It was a ghost drive shown after my old ipod connected to the laptop.
It cannot be deleted, but after disconnecting the ipod and rebooting the laptop, the ghost drive disappeared and the files work normal again.
However, the windows file explorer and xyexplorer won't freeze when seeing the ghost drive.
Any chance you could make it the same in the next update??
Thanks a lot.

**Comment by yaira2** [comment]
A fix will be included in the next release.
