### ISSUE TITLE
Feature: Splitting translation for background settings

### ISSUE THREAD

**Issue by XTorLukas** [files-community/Files#15313]
I have a request to split these translations into two different ones, now when there will be an option to add an image, it would be good to name it as "background color", but this translation is also used to set it as background.

### Requirements

"`Background`" => "`Background color`"

![imgA](https://github.com/files-community/Files/assets/84145589/c343947c-09de-487c-b31d-b8669252cd1c)
![imgB](https://github.com/files-community/Files/assets/84145589/fd975365-9840-466f-9ca4-63dad4010a93)

"`Set as background`" => "`Set as desktop background`"

![imgC](https://github.com/files-community/Files/assets/84145589/28e305df-0cfd-4034-ae9e-a672ba861284)

### Files Version

3.3.6.0

### Windows Version

10.0.22631.3447

**Comment by 0x5bfa** [comment]
Thanks for the feedback.

**Comment by XTorLukas** [comment]
In my opinion it would be good to put 'System' or 'Auto' or similar instead of 'Default'

Theme "`Default`" => "`System`" / "`Auto`"

![imgD](https://github.com/files-community/Files/assets/84145589/cc234142-f340-4ab4-ac48-bcc94a51e55e)

**Comment by yaira2** [comment]
Can you confirm if your request is for us to rename "Background" to "Background" color?

**Comment by XTorLukas** [comment]
> Can you confirm if your request is for us to rename "Background" to "Background" color?

Yes, rename `Background` to `Background color`

**Comment by Josh65-2201** [comment]
> "Set as background" => "Set as desktop background"

It wouldn't make sense to change this as the option is also for setting the lock screen background

**Comment by yaira2** [comment]
> > "Set as background" => "Set as desktop background"
> 
> It wouldn't make sense to change this as the option is combined and also can set the lock screen background

It wouldn't hurt to add an option for "Set as app background".

**Comment by 0x5bfa** [comment]
> > "Set as background" => "Set as desktop background"
> 
> It wouldn't make sense to change this as the option is combined and also can set the lock screen background

This naming was from FE. Maybe we can think of another one.
