### ISSUE TITLE
Files运行时总是不能安全弹出移动硬盘

### ISSUE THREAD

**Issue by Triangle-GitHub** [files-community/Files#15320]
### Description

Files能识别U盘的插入并在旁边显示“弹出”按钮，然而移动硬盘插入后不仅不能正常识别为“可弹出的驱动器”，还会持续占用移动硬盘导致从任务栏上也无法安全弹出，除非我关闭所有Files窗口并在托盘图标中退出Files。

### Steps To Reproduce

1. 启动 Files 3.3
2. 插入移动硬盘 (SSD或HDD均可)
3. 观察到Files识别了硬盘，但没有发现它是可弹出的
4. 观察到Files占用硬盘，导致安全弹出报错
5. 完全退出Files进程，硬盘可以安全弹出

### Requirements

- 使Files不要占用移动硬盘
- 增加识别可弹出的移动硬盘的功能，以便于快速弹出

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3447

### Log File

日志文件认为我的移动硬盘和本地硬盘一样不可弹出。

**Comment by Triangle-GitHub** [comment]
我使用的移动硬盘是Kingston XS2000，但你应该能用任何功能完整的移动硬盘复现这个问题。

**Comment by Josh65-2201** [comment]
Thanks for the report, Can you confirm this is the same as #13250

**Comment by Triangle-GitHub** [comment]
> Thanks for the report, Can you confirm this is the same as #13250

#13250 似乎是一个功能请求，但我认为问题比“只是缺少eject button”严重一些，因为Files的进程还阻止我从系统的其他地方弹出移动硬盘，以至于我需要彻底关闭Files才能安全弹出，比较影响体验。

![image](https://github.com/files-community/Files/assets/114236693/6e0218e7-e9a5-4a10-806c-98ec3931faf4)
如图，由于Files进程的占用，即使用系统的“删除设备”也会失败。

**Comment by Triangle-GitHub** [comment]
你好！我做了一个复现视频，以便更好地排查问题：

https://github.com/files-community/Files/assets/114236693/a6c7da95-a523-465f-a34f-5b9877460834

**Comment by yaira2** [comment]
I've seen this as well

**Comment by yaira2** [comment]
This should be resolved in the next update.

**Comment by Triangle-GitHub** [comment]
many thanks.





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "files-community/Files"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月3日(星期二) 上午9:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [files-community/Files] Files运行时总是不能安全弹出移动硬盘 (Issue #15320)





 
This should be resolved in the next update.
