### ISSUE TITLE
recycle bin not working

### ISSUE THREAD

**Issue by waLkE21** [files-community/Files#15335]
### Description

recycle bin not working

### Steps To Reproduce

recycle bin not working

### Requirements

recycle bin not working

### Files Version

3.4.0.0

### Windows Version

10.0.22631.3527

### Log File

![1](https://github.com/files-community/Files/assets/169241060/cd90d3fe-7054-4711-8114-afb84311c541)

**Comment by Josh65-2201** [comment]
Thanks for the report, Please try reinstalling Files.

If that doesn't work, can you answer the following
- What isn't working about it, other than the text on the sidebar
- Can you please upload (Do not copy and paste content) the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.

**Comment by waLkE21** [comment]
when i try to pin recycle bin or network to explorer, it gives error. i upload another screenshot.
i add debug.log file too.
[debug.log](https://github.com/files-community/Files/files/15245914/debug.log)
![pin1](https://github.com/files-community/Files/assets/169241060/b50eec0f-ad14-4156-9698-3ca70bb5f7b3)

**Comment by Josh65-2201** [comment]
Did you try reinstalling Files?

**Comment by waLkE21** [comment]
yes. it solved problem. thanks.

**Comment by yaira2** [comment]
Thanks for letting us know!
