### ISSUE TITLE
Files

### ISSUE THREAD

**Issue by Spoomkalou** [files-community/Files#15338]
### Description

When opening Files on different screens, with dragging the window from one to another. 

### Steps To Reproduce

1.open files
2.select tab
3.drop window to another screen

### Requirements

Fix crash that occurs when selecting and dragging the tab to another monitor/screen

### Files Version

3.3.0.0

### Windows Version

Windows 11 Professionnel 23H2

### Log File

[debug.log](https://github.com/files-community/Files/files/15253017/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Please update to 3.4.0.0 and see if it's still an issue.

**Comment by Josh65-2201** [comment]
@Spoomkalou Please try the steps in the above comment
