### ISSUE TITLE
Bug: CommandManager.OverwriteKeyBindings System.ArgumentException

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#15331]
### Description

```csharp
System.ArgumentException: An element with the same key but a different value already exists. Key: 'Alt+Ctrl+Haut'
```

### Steps To Reproduce

NA

### Requirements

- Fix crash

### Files Version

v3.4

### Windows Version

Windows 11

### Log File

```csharp
System.Collections.Immutable.ImmutableDictionary`2
HashBucket.Add (TKey key, TValue value, IEqualityComparer`1 keyOnlyComparer, IEqualityComparer`1 valueComparer, KeyCollisionBehavior behavior, OperationResult& result)
System.Collections.Immutable
ImmutableDictionary`2.AddRange (IEnumerable`1 items, MutationInput origin, KeyCollisionBehavior collisionBehavior)
System.Collections.Immutable
ImmutableDictionary`2.AddRange (IEnumerable`1 pairs, Boolean avoidToHashMap)
Files.App.Data.Commands
CommandManager.OverwriteKeyBindings ()
Files.App.Utils.Serialization
BaseObservableJsonSettings.Set[TValue] (TValue value, String propertyName)
Files.App.Services.Settings
ActionsSettingsService.set_ActionsV2 (List`1 value)
Files.App.ViewModels.Settings
ActionsViewModel.ExecuteSaveCommand (ModifiableActionItem item)
CommunityToolkit.Mvvm.Input
RelayCommand`1.Execute (Object parameter)
ABI.System.Windows.Input.ICommand
Vftbl.Do_Abi_Execute_3 (IntPtr thisPtr, IntPtr parameter)
WinRT
ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0 (Int32 hr)
ABI.Windows.ApplicationModel.Core
IUnhandledErrorMethods.Propagate (IObjectReference _obj)
Microsoft.AppCenter.Utils
ApplicationLifecycleHelperWinUI.<ctor>b__0_3 (Object sender, UnhandledErrorDetectedEventArgs eventArgs)
```

**Comment by 0x5bfa** [comment]
Yeah when user set the same key to different commands, this happens. I’ve ever seen this crash before once.

before adding keybindings to dictionary, we can check if.

**Comment by yaira2** [comment]
> Yeah when user set the same key to different commands

Don't we already prevent duplicate key bindings?

**Comment by 0x5bfa** [comment]
If user set via text editor, we cannot prevent beforehand.

**Comment by 0x5bfa** [comment]
Oh, sorry. I didn't know this issue

**Comment by yaira2** [comment]
Done 👍

**Comment by 0x5bfa** [comment]
What approach is better? This is caused by editing the json wrongly.

1. Reset everything (emptying the collection)
2. Reset only the hotkey(s) which is the same as the other, which is set earlier.
3. Ignore everything, use defaults, then notify through a dialog?.

**Comment by yaira2** [comment]
> Reset everything (emptying the collection)

I don't think we need to go that far

A combination of approach two and three is best, we can display a prompt and ask if the user would like to reset the conflicting hotkeys or if they would like to manually edit the settings file themselves.

**Comment by 0x5bfa** [comment]
Int hat case Files has to know if the json has been corrected, and close the dialog, as the load is done once on startup. Also, the load of the custom hot keys is performed before MainWindow.Content is set; this issue was a blocker when I tried to prompt a dialog notifying incorrect of json format.

**Comment by yaira2** [comment]
If that's a blocker, we can go with option 2 and reset the conflicting key.
