### ISSUE TITLE
bitrate for audio files on file explorer v/s files app are different, possibly because of the way it is calculated?

### ISSUE THREAD

**Issue by benjaminfl721** [files-community/Files#15333]
### Description

So i made a feature request about something similar to this a little while ago, which was implemented  - about putting the bitrate for audio files in the details pane.  I also mentioned something about how bitrate shows up differently in files app for some reason, slightly off, for example 320kbps in file explorer would show up as 312.5kbps in files app.  As it was being worked on a developer commented a reason this might be happening: "From looking, that is most likely due to the calculation being done. 192000 / 1024 would be 187.5 and not 192. So, we could change this conversion to kilo-bits (kbps) instead of kilo-bytes (KBps)."  This might not be a bug per-se but it would certainly make much more sense if it was calculated this way as opposed to the way it is in files app currently.

### Steps To Reproduce

find an audio file, click on it and open details pane, and view the audio encoding bitrate section

### Requirements

change the way bitrate is calculated

### Files Version

3.4.0.0

### Windows Version

10.0.22631.3527

### Log File

[debug.log](https://github.com/files-community/Files/files/15243284/debug.log)

**Comment by Jay-o-Way** [comment]
Two quick thoughts:
- what if a file has a variable bitrate?
- one should be aware of the difference between kilobytes and kibibytes, they are notorious for being used incorrectly and even sometimes mixed...

**Comment by benjaminfl721** [comment]
NVM, it looks like this is fixed in the new files preview update
