### ISSUE TITLE
A lot of folder icons show a black background

### ISSUE THREAD

**Issue by SpiderPork** [files-community/Files#15334]
### Description

See attached image:
![immagine](https://github.com/files-community/Files/assets/28104908/105e0055-5e4e-40d8-a28a-0d3452529101)

### Steps To Reproduce

1. Open Files
2. Navigate file system

### Requirements

Folder icons should have all trasparent background

### Files Version

3.4.0.0

### Windows Version

10.0.22631.3527

### Log File

[debug.log](https://github.com/files-community/Files/files/15245106/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Can you try the below

1. Search for the Disk Cleanup in the start menu.
2. Select the C drive
3. Select the thumbnails from the list.
4. Then click on ok.
5. Restart Files

**Comment by yaira2** [comment]
@SpiderPork no worries, thank you for letting us know that the solution helped.
