### ISSUE TITLE
support alt + double click open properties

### ISSUE THREAD

**Issue by Morrigan-Ship** [files-community/Files#15336]
### What feature or improvement do you think would benefit Files?

support `alt + double click` open properties like windows explorer

### Files Version

3.4

### Windows Version

windows insider 26100

**Comment by Josh65-2201** [comment]
Thanks for the feedback, adding mouse support for actions is being tracking in #15151. You can check there or click subscribe in the right sidebar for updates. When implemented you can make the shortcut yourself.

**Comment by yaira2** [comment]
In the meantime, you can use the `alt` + `enter` shortcut to open properties.
