### ISSUE TITLE
Add necessary loading animations

### ISSUE THREAD

**Issue by JTFA** [files-community/Files#15343]
### What feature or improvement do you think would benefit Files?

In the 3.4.0.0 version, when open a large folder, at first the position is not correct, and after about a half second the position jump to the top (and the page cannot be operated before the jump). It is similar when navigating up to the previousfolder, the page will flash at the top position and then jump to the previous position. 
Since the performance issue has not been resolved yet, is it possible to add a loading animations to cover the error scene before jumping to the correct position?

### Requirements

Add necessary loading animations to cover the error scene before jumping to the correct position of the page.

### Files Version

3.4.0.0

### Windows Version

10.0.22631.3527

**Comment by yaira2** [comment]
Thank you for feedback, we're working on improving performance (please see #4180). In the meantime, you can work around this by turning off the option to scroll to the previous folder.
![image](https://github.com/files-community/Files/assets/39923744/06d74a50-456e-460f-bdcd-8a7e6942ce60)

**Comment by JTFA** [comment]
> Thank you for feedback, we're working on improving performance (please see #4180). In the meantime, you can work around this by turning off the option to scroll to the previous folder. ![image](https://private-user-images.githubusercontent.com/39923744/329279300-06d74a50-456e-460f-bdcd-8a7e6942ce60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNzE3MzYsIm5iZiI6MTcxNTI3MTQzNiwicGF0aCI6Ii8zOTkyMzc0NC8zMjkyNzkzMDAtMDZkNzRhNTAtNDU2ZS00NjBmLWJkY2QtOGE3ZTY5NDJjZTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDE2MTcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkMzA0NTU5MmMzOTE4M2UzZTc0M2ZhMzE5NWNjYjZkYTY2MWU3NDlhZDBkZGRjZmY1OGY5NzAzMTYwNGVjNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ltrPhxHOm1t-WJtFyQkNVXv5Tk5ExgrUucv-ta9X8c0)

However, the problem when opening a large folder cannot be avoided by settings. Hope this issue can be reasonably resolved.

**Comment by yaira2** [comment]
> when open a large folder, at first the position is not correct

Do you have group by date enabled?

**Comment by JTFA** [comment]
> > when open a large folder, at first the position is not correct
> 
> Do you have group by date enabled?



> > when open a large folder, at first the position is not correct
> 
> Do you have group by date enabled?

Yes, in the download folder, grouping by date is the most convenient.

**Comment by yaira2** [comment]
That's likely the cause, there is a known issue where grouping can mess with the scroll position.
