### ISSUE TITLE
Freezes after rearranging tabs

### ISSUE THREAD

**Issue by vovapaukoff** [files-community/Files#15345]
### Description

If tab dropped on top the another tab, it just freezes the tabs movement, you can click on tab but can't move them.
A few times Files stuked at "Not Responding" state, after moving new tab to before a few opened already tabs.

### Steps To Reproduce

Drag any tab on top of the another open tab.

### Requirements

Probably moving tabs freely without crushes and freezes

### Files Version

3.4.0.0

### Windows Version

Edition	Windows 11 Pro Version	23H2 Installed on	‎08/‎11/‎22 OS build	22631.3527 Experience	Windows Feature Experience Pack 1000.22700.1003.0

### Log File

[debug.log](https://github.com/files-community/Files/files/15259135/debug.log)

**Comment by vovapaukoff** [comment]
Uploading files freeze - Made with Clipchamp.mp4…

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #14726. You can check there or click subscribe in the right sidebar for updates.
