### ISSUE TITLE
Firewall going crazy when installing....

### ISSUE THREAD

**Issue by bukowa** [files-community/Files#15340]
### Description

Do it really need to connect to all these ips?

### Steps To Reproduce

Do it really need to connect to all these ips?

### Requirements

- e.g. Fix crash that occurs when...
Do it really need to connect to all these ips?

### Files Version

latest

### Windows Version

latest

### Log File

Do it really need to connect to all these ips?

**Comment by yaira2** [comment]
Thank you for your feedback, the sideload installation goes through Cloudflare. How that works in the background I don’t know, but from our end everything points to the same service.
