### ISSUE TITLE
Cut and copy

### ISSUE THREAD

**Issue by cppbelcom** [files-community/Files#15342]
### Description

Hello, when we perform a cut - paste operation from the menu bar when we want to Paste the cut file It sends it to the trash
![image](https://github.com/files-community/Files/assets/169318829/567267d6-f47b-4393-9831-0d86d7fb5111)
![image](https://github.com/files-community/Files/assets/169318829/51e9bce6-0f37-4296-97fe-21b1a68c30c7)

### Steps To Reproduce

1.Cut
2.Paste

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3527

### Log File

[debug.log](https://github.com/files-community/Files/files/15256337/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, the prompt you showed is from OneDrive moving the file it has to the recycle bin, not Files.

**Comment by yaira2** [comment]
As Josh mentioned, OneDrive is detecting that the original item was removed (as expected). File Explorer has the same behavior so we can see it's not specific to Files.
