### ISSUE TITLE
Missing option on right-click

### ISSUE THREAD

**Issue by tbytetbyte** [files-community/Files#15358]
### What feature or improvement do you think would benefit Files?

Some useful right-click options are not available on files. 
I need to use Scan with Windows Defender (or another anti-virus) and the option is not listed. It's not hidden on **Show more options** either.

### Requirements

- This proposal will accomplish adding _custom options_ depending of **file type**.

### Files Version

3.4.0.0

### Windows Version

10.0.22631.3527

**Comment by Josh65-2201** [comment]
Thanks for the feedback, This is an issue with Windows Defender and not something Files can fix. Please use Feedback Hub to send feedback to Microsoft on adding Windows defender to the normal shell context menu.

**Comment by yaira2** [comment]
This might be resolved with #8251
