### ISSUE TITLE
Crushed columns

### ISSUE THREAD

**Issue by 6mun** [files-community/Files#15356]
### Description

Hello !

I have a specific folder that behaves strangely :

![Files_5QIHd3MCIa](https://github.com/files-community/Files/assets/124860187/aa6bf938-ca8a-4c22-83ef-38b90c166edf)

If I use "set columns to fit". it won't do anything - after rebooting the computer, it went fine again. But it does it time to time again. That's my work folder - it have 21K+ files and about 900 folders (but nested), the main one just display 23 folders.

Also, if  I add a column, say "tags" for example, it's also minified, and I can't get it to resize manually. I've tried to tinker around, switch the toggle 'adaptative layout' but same here, am stuck
![Files_J3hW6pgMa9](https://github.com/files-community/Files/assets/124860187/4b66547a-feda-4aa7-a73f-4f2bc81cfea3)
_lastly, a quick question:_ is there a way to change/rearrange the column's order or 1. I've missed something while discovering your gem of an app 2. I should make a feature request cause it's not possible rn ?

### Steps To Reproduce

N/A

### Requirements

n/A

### Files Version

3.4.0.0

### Windows Version

10.0.22631.3527

### Log File

[debug.log](https://github.com/files-community/Files/files/15274434/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Can you try right clicking a working folder and click set as default, you can also try turning on Files settings > Layout > Sync layout and sorting preferences across directories > expand or shrink one of the columns slightly in a working folder.

**Comment by 6mun** [comment]
Hi Josh, And thanks for your swift reply! For time being, it’s just one column that behaves this way, the tag one, see attached screen grab ; I’ve done also all you have recommended, yet the pb is persistent, and I cannot expand this one no matter where am pulling.  Bah, the week-end is coming, I’ll try to do a fresh install, clear preferences etc etc see if things improve this way, and they will probably, cause that kind of thing sounds more like a ‘me-issue’ than a global one. All the best,Simon   From: Josh65-2201Sent: Friday, 10 May 2024 9:30 pmTo: files-community/FilesCc: 6mun; AuthorSubject: Re: [files-community/Files] Crushed columns (Issue #15356) Thanks for the report, Can you try right clicking a working folder and click set as default, you can also try turning on Files settings > Layout > Sync layout and sorting preferences across directories > expand or shrink one of the columns slightly in a working folder.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by 0x5bfa** [comment]
@yaira2 What do you think of the idea to set MinWidth (File Explorer does, around 60px?) directly to the DataGridHeader to privent such issue?

**Comment by yaira2** [comment]
There is already a min width

**Comment by 0x5bfa** [comment]
I dont think so.

![image](https://github.com/files-community/Files/assets/62196528/758be3eb-c291-4d24-9dd8-da4ca8d82805)

![image](https://github.com/files-community/Files/assets/62196528/2ac89900-7f88-4773-aaba-82ecb3c452ff)

**Comment by yaira2** [comment]
In the code behind

**Comment by 0x5bfa** [comment]
Every min width should be the same, so handling in xaml would be better.

**Comment by yaira2** [comment]
We can handle in XAML, but in theory it should be possible to get into such a state in the first place.

**Comment by 0x5bfa** [comment]
If LiteDB database is broken for some reasons, it for sure becomes like this. Setting static values in XAML makes definite confidence it won't happen again.

**Comment by yaira2** [comment]
Let's do this then

**Comment by yaira2** [comment]
Is this still an issue in the latest release v3.6?
