### ISSUE TITLE
Bug: Crash when creating keyboard shortcuts

### ISSUE THREAD

**Issue by Davikar** [files-community/Files#15354]
### Description

I was creating new shortcuts in the action settings.
First one went okay, but when trying to save the second one Files crashed and now it wont start, just shows the window with a loading circle.
I was assigning sort by name and date to alt+1 and alt+2.

I changed the shortcuts afterwards, but looking at the settings it seems the change was not saved and it saved alt+1 to both shortcuts... Removed the duplicate and now Files starts again.
Also, it seems deleting the shortcuts remove the key binding, it still complains that the key is taken.

### Steps To Reproduce

1. Create keyboard shortcut.
2. Save shortcut.

### Requirements

Fix crash that occurs when saving shortcut keys.

### Files Version

3.4

### Windows Version

Windows 11 22631.3527

### Log File

[debug.log](https://github.com/files-community/Files/files/15271198/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, right now you should be able to open Windows File Explorer > Put `%localappdata%\Packages\Files_1y0xx7n9077q4\LocalState\settings\user_settings.json` in the path bar > Delete the `ActionsV2` section > Open Files

**Comment by yaira2** [comment]
We're going to continue tracking this in #15331 and hope to have a fix soon.

Fyi @0x5bfa
