### ISSUE TITLE
Files take more than 30 seconds to launch

### ISSUE THREAD

**Issue by luislopezmoreno** [files-community/Files#15355]
### Description

After re-installing Files app in V3.4, I notices it takes way too long to start (with the animation of Files app), more than 30 seconds

### Steps To Reproduce

1. Open Files app
2. Test if it takes more than 30 seconds to launch or is it just me

### Requirements

- Fix loading time when opening a new window

### Files Version

3.4

### Windows Version

Windows 11 23H2

### Log File

[debug.log](https://github.com/files-community/Files/files/15272073/debug.log)

**Comment by yaira2** [comment]
Initial startup performance will be a lot better when the WinAppSdk framework get Native AOT support.
