### ISSUE TITLE
High CPU

### ISSUE THREAD

**Issue by mrzcn** [files-community/Files#15351]
### Description

only 2 tabs open but uses very high cpu
![Ekran görüntüsü 2024-05-10 003021](https://github.com/files-community/Files/assets/26885591/963ec2d5-a033-40a4-91eb-c2248fab2383)
![Ekran görüntüsü 2024-05-10 003003](https://github.com/files-community/Files/assets/26885591/6cd8dc51-d8da-4716-a6af-e291950410e3)

### Steps To Reproduce

just use it

### Requirements

- e.g. Fix crash that occurs when...
check the cpu usage

### Files Version

3.4.0.0

### Windows Version

10.0.19045.4355

### Log File

[debug.log](https://github.com/files-community/Files/files/15267845/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, does the CPU go down after a couple of seconds?

**Comment by SergeyTverye** [comment]
I think maybe it's related, but I also want to share that the app very strangely continuously consumes from 0.7 to 3.5% of CPU during background work (average is 2%), i.e. Files is not even open, it just hangs in the tray, but continuously does some work.

Files: 3.4.0.0
OS: Win 11 x64 23H2 22631.3447
CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz

![изображение_2024-05-10_014813497](https://github.com/files-community/Files/assets/26005038/04a60626-5166-4214-bddf-d3fdc2263be0)

**Comment by mrzcn** [comment]
I did not wait too much to monitor how the CPU went but I am restarting the files app if the CPU usage high

**Comment by yaira2** [comment]
Thank you for all the feedback, a small percentage of CPU is normal, it's also normal for it to jump when navigating between folders.

All that said, optimizing performance is an ongoing task. Please refer to #4180 to follow our progress.
