### ISSUE TITLE
Bug: Toolbar play/play all doesn't show for mkv files

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#15365]
### Description

*

### Steps To Reproduce

1. Select one or more mkv video files.
2. See toolbar doesn't show play option

### Requirements

- Add `.mkv` as a video type

### Files Version

3.4.0.0

### Windows Version

10.0.22621.3447

### Log File

[debug.log](https://github.com/files-community/Files/files/15280078/debug.log)

**Comment by yaira2** [comment]
@Josh65-2201 do you know want to open a PR? The code is the file extension helper.

**Comment by Josh65-2201** [comment]
Done
