### ISSUE TITLE
Creating a Temporary Drop Zone for File Transfer

### ISSUE THREAD

**Issue by DhananjayPorwal** [files-community/Files#15366]
### What feature or improvement do you think would benefit Files?

When moving multiple files from various locations, we typically have to transfer each folder's files individually. Creating a temporary drop zone to consolidate all files before moving them to the desired location can streamline the process.

![image](https://github.com/files-community/Files/assets/51775507/2a9583b4-f73c-4a36-9f4f-b8e83f38a1a2)

### Requirements

1. **Interface Modification:** Create a visually distinct area within the File Explorer interface to serve as the temporary drop zone.
2. **Drag and Drop Functionality:** Enable drag and drop functionality within the app to allow users to easily move files into the temporary drop zone.
3. **File Management Controls:** Implement controls such as buttons or context menu options to facilitate moving all files from the temporary drop zone to a user-defined destination.
4. **Customization Options:** Consider offering customization options such as the ability to change the temporary drop zone location or define default destination folders for transferred files.

### Files Version

3.4.0.0

### Windows Version

10.0.22631.3527

### Comments

https://youtu.be/1k1vz9PD7O4?si=KiKl4opbm6bsZck3&t=91

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #12490 . You can check there or click subscribe in the right sidebar for updates.
