### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by tbytetbyte** [files-community/Files#15360]
### What feature or improvement do you think would benefit Files?

It'll be perfect if I can change the size of fonts.
I know Files have already custom space between elements/icons, but it'll be better if font size could be customized as well.

### Requirements

- This proposal will improve readability on longer text labels, and benefits some languages (as Spanish & French which labels/folders name use to be longer than English)

### Files Version

3.4.0.0

### Windows Version

10.0.22631.3527

**Comment by yaira2** [comment]
Thank you for your feedback, while we don't have plans to implement this option right now, this isn't the first time it's been requested, and we remain open to the possibility of revisiting it in future discussions
