### ISSUE TITLE
Top edge of the window border is not visible/shown on windows 10

### ISSUE THREAD

**Issue by szebegyi** [files-community/Files#15369]
### Description

Files window has accent color border. The top edge of the accent color border is not visible/shown.
<img width="749" alt="files_01" src="https://github.com/files-community/Files/assets/64122585/05ce96fd-5abe-4fcb-bafb-d558963b091a">

### Steps To Reproduce

Set accent color
Open files

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.3.0.0

### Windows Version

10.0.19045.4291

### Log File

[debug.log](https://github.com/files-community/Files/files/15281834/debug.log)

**Comment by 0x5bfa** [comment]
This should be a Windows side issue.
Might be related with #14599

**Comment by yaira2** [comment]
This is indeed the same as #14599. I believe there is also an issue tracking this on the WinAppSdk repo.

**Comment by 0x5bfa** [comment]
https://github.com/microsoft/microsoft-ui-xaml/issues/8805

**Comment by szebegyi** [comment]
@0x5bfa, you closed this with "_This should be a Windows side issue._" If this was true then why this symptom is experienced with files only. All other applications (e.g. windows settings or MS team) display the window border properly.

**Comment by yaira2** [comment]
> All other applications (e.g. windows settings or MS team) display the window border properly.

@szebegyi Windows Settings is UWP and MIcrosoft Teams is another framework. This issue is specific to WinAppSdk, and even then, only when using extended title bars. 

I recommend adding your feedback to https://github.com/microsoft/microsoft-ui-xaml/issues/8805 as it's the community who can help increase the priority of these issues on Microsofts end.

**Comment by 0x5bfa** [comment]
Yes, Notepad and Paint uses XAML Island, Calculator, MS Store, Snipping Tool and Windows Terminal uses UWP, Discord app uses Web framework.

If you wanna see this issue in another app, you can download an app from Microsoft for developers like us: https://apps.microsoft.com/detail/9p3jfpwwdzrc

**Comment by yaira2** [comment]
Microsoft recently fixed this issue and we'll include the fix in the next version of Files.
