### ISSUE TITLE
CLASSIC, CONTEXT MENU

### ISSUE THREAD

**Issue by Vavilago** [files-community/Files#15363]
### What feature or improvement do you think would benefit Files?

Good afternoon.
I just installed Files in version 3.4, I've only been using this program for an hour, and I already feel "in love"
First of all, thank you very much for thinking of us and creating this wonder.
I have also looked for a way to return to the **classic** context menu (**those of us from the old school look for it and there are many of us**) and I cannot find this option.
You can add it in the next review please.
Thank you so much

_'A thousand apologies, I used Google translator._

### Requirements

- Esta propuesta logrará X- Esta propuesta logrará Y- Esta propuesta logrará Z

### Files Version

3.4.0.0

### Windows Version

Windows 11 single language, v22631.3447

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Using the Windows 10 style context menu is not possible because of it has to interact with Files and the difficulty of implementing it. If there's something missing for you please make feedback to add that to Files context menu.
