### ISSUE TITLE
Support icon overlays of TortoiseGit

### ISSUE THREAD

**Issue by 1466587594** [files-community/Files#1536]
**Is your feature request related to a problem? Please describe.**
With TortoiseGit icon overlays set, files icons will be like this, which not supported in files-uwp.
![image](https://user-images.githubusercontent.com/13366013/88190560-ffe5b580-cc6c-11ea-9c8f-54827a6e5fbd.png)

**Describe the solution you'd like**
Hope to support the above effect.

**Describe alternatives you've considered**
Nothing.

**Additional context**
Nothing.

**Comment by yaichenbaum** [comment]
@gave92 Can we reuse the code we used for OneDrive here?

**Comment by gave92** [comment]
@yair100 i don't think so. OneDrive stores the offline/online status in a file property. Tortoise likely uses "icon overlays". If so, you can surely get the icon from the fulltrust process, don't know if you can get it directly from uwp.
*Edit* found it's easy enough to get the overlay from the fulltrust process, I'll be opening a PR soon
