### ISSUE TITLE
Column View

### ISSUE THREAD

**Issue by amatthewr77** [files-community/Files#15364]
### What feature or improvement do you think would benefit Files?

I can't seem to find this feature, but if it's there already, please point me in the right direction.

Love this app by the way...perfect for what I'm looking for. When in column view, can there be a setting that auto adjusts the width of the column to the longest filename OR else auto adjust AND shrink the folder contents so the app interface doesn't get any larger? Hope that makes sense. Thank you.

### Requirements

I'm just the user! You're the dev! 

### Files Version

3.4.0.0

### Windows Version

10.0.22631.3527

**Comment by Josh65-2201** [comment]
Thanks for using Files, the option is in the layout picker on the toolbar
![image](https://github.com/files-community/Files/assets/26977075/0a5603c5-e52c-4626-87bd-aa516e00312c)
