### ISSUE TITLE
Bug: Folder contents don't show when item is tagged

### ISSUE THREAD

**Issue by tbytetbyte** [files-community/Files#15361]
### Description

I created 4 tags to identify some files. I assigned just 1 tag to test.
I closed Files, but when I open it, seems a little hang, shows no file tagged in Home, and when I try to open the selected tag, it keeps searching.

![image](https://github.com/files-community/Files/assets/139590826/7057fb1e-4e1d-4acc-b9d2-33ba8efb10ae)

![image](https://github.com/files-community/Files/assets/139590826/6123eb36-b2ee-485f-9f54-2be2591f6f9d)

### Steps To Reproduce

1. Created "Ver después" tag.
2. Close Files
3. Open Files, go to Home, and see nothing in "Ver después" tag field.

### Requirements

- Show files tagged as "Ver después"

### Files Version

3.4.0.0

### Windows Version

10.0.22631.3527

### Log File

[debug.log](https://github.com/files-community/Files/files/15276483/debug.log)

**Comment by tbytetbyte** [comment]
So, Indexing shoul be activated for this feature to work? I have files on interlan, external drives. And in OneDrive too. When I reopen Files, sometime it shows the tagged files, and sometimes not.

**Comment by yaira2** [comment]
> So, Indexing shoul be activated for this feature to work

Correct, we don't actually store a database of tagged files (we might change this in the future) so we rely on the Windows search index to locate tagged items.

**Comment by tbytetbyte** [comment]
The problem is, a few minutes ago, tagged files showed right. But after restarting Files again, TAGS don't work anymore. It's a random behavior. :(

**Comment by Josh65-2201** [comment]
If you open the folder with tags do they show? Seems like the same issue as #15214.

**Comment by tbytetbyte** [comment]
In this precise moment, not, but 30 minutes ago, yes. Seems like it's random.

**Comment by tbytetbyte** [comment]
Did **Files** support 3rd party search engines, like **Everything** (https://www.voidtools.com/support/everything/)

**Comment by Josh65-2201** [comment]
Files doesn't have any integration with other search engine's but it's been planned.

**Comment by tbytetbyte** [comment]
Hi Josh. I think this problem is HUGE, because, now, when I try to pen the tagged folders, the items dissapear!
I shows all files inside the taged folder for 1 second, and after that, keep dissapearing from view!

**Comment by tbytetbyte** [comment]
![image](https://github.com/files-community/Files/assets/139590826/748b0f0b-92e8-473d-903c-e56d1b9df050)

**Comment by Josh65-2201** [comment]
The tags issue might be coming from OneDrive as cloud drive don't work to weel with the tags system. As for the contents not showing are they there in Windows File Explorer?

**Comment by tbytetbyte** [comment]
- I tagged one folder in OneDrive, and the files inside keep dissapearing (from Files app).
- I tagged 2 files in different external SDD and HDD (both indexed) and files dissapearing in Files App. The files are right there when using Windows File Explorer. Please see the screenshot:

![image](https://github.com/files-community/Files/assets/139590826/e6663c77-9ad3-42aa-a29e-25b3c455fbf3)

**Comment by tbytetbyte** [comment]
The problem with this particular file, is that now I can't de-tag it... Can't remove the TAG because it dissapears from view - what a real problem here. 🫥

**Comment by tbytetbyte** [comment]
FYI, I deleted all custom TAGS, and now, the files show perfect in Files App. But, keeps showing a greyed-out "unknow" tag, like this.

![image](https://github.com/files-community/Files/assets/139590826/e4584be8-c7c0-4523-84ca-f013ed7583ff)

**Comment by tbytetbyte** [comment]
So, I guess TAGS in a not-so-working feature. I really want to use **Files** as my main file explorer, because it's very useful and nice, but I need this to be fixed, so I can use all the features.

**Comment by hez2010** [comment]
> * I tagged 2 files in different external SDD and HDD (both indexed)

Is your external device formatted with NTFS or ReFS? Tags won't work on other file systems.

**Comment by tbytetbyte** [comment]
Yes, it is:
![image](https://github.com/files-community/Files/assets/139590826/220ea42b-e951-49c2-a21e-92f2cfcf71af)

**Comment by tbytetbyte** [comment]
> The tags issue might be coming from OneDrive as cloud drive don't work to well with the tags system and usually remove them when syncing. As for the contents not showing are they there in Windows File Explorer?

No, it does not removed the tag after sync, see: 
![image](https://github.com/files-community/Files/assets/139590826/64b98c6e-7b7d-4287-b46a-6074a19bb42a)

**Comment by tbytetbyte** [comment]
I found what it could be a solution. It seems working now.
I have change settings in Windows Search, like this:

![image](https://github.com/files-community/Files/assets/139590826/1a1daa4f-d9eb-4701-aa5a-ca15567e7390)

And it seems to work faster, and the tags now are fully usable. However, Files don't show updated widgets on Home tab. To correctly see the files/tags you've added, Files need to be restarted, and after that, it shows the files inside widgets:

![image](https://github.com/files-community/Files/assets/139590826/72159b00-8c12-4ed2-b865-3dad22a1058c)

**Comment by yaira2** [comment]
Excellent!

> And it seems to work faster, and the tags now are fully usable. However, Files don't show updated widgets on Home tab. To correctly see the files/tags you've added, Files need to be restarted, and after that, it shows the files inside widgets:

This is a different bug that's high on our priority list to resolve. Merging with #6182.

**Comment by tbytetbyte** [comment]
Hi! Unfortunally, the problem is still present. I left my laptop powered off. Now, I turned it on, opened Filed, and all is a mess again. When I select a tag, it stucks "loading", and now, when I try to change view on a folder (to see thumbnails), files keep dissapearing. So, I think Files have serious bugs... it's kinda unusable.

**Comment by yaira2** [comment]
Is this in the tags view that they are disappearing, or is this a regular folder with tagged items?

**Comment by tbytetbyte** [comment]
At first, it only happened on tagged folders, but sometimes, it happens on not tagged folder -nor tagged file in these folders.

BTW
I'm using Files, and I notice this behavior.
Sometimes (when PC is switched on), and I open Files, the tags are vanished. But, if I open another instance of the app, it works ok (it shows tags normally).

I guess it have to do with a kind of delay in Windows Search. It's like, when Files is launched, Windows Search doesn't work at firrst... But, if you open another instance, seems like Windows Search -in some way, start to work and tags loads correctly.

Maybe this bug can be fixed adding some king of activator of Windows Search each time Files is launched.

**Comment by yaira2** [comment]
It can be the system is running out of memory for Files, you can try turning off the option to leave Files in the background to see if that helps.

**Comment by tbytetbyte** [comment]
That it strange, given that my laptop it's a i7, 16GB RAM + GeForce 6GB, it's a powerful laptop, and I disabled Files to run in background.

Maybe it's better to have it running on background, but it'll be there after a restart?

**Comment by yaira2** [comment]
We haven't exactly figured out why it's only an issue on some OneDrive accounts, but some users have had success with tagging cloud items while others have encountered the issue reported here. We're working to address this and will be tracking our progress in #15272.
