### ISSUE TITLE
"Run with PowerShell" starts in wrong directory

### ISSUE THREAD

**Issue by RuiNtD** [files-community/Files#15375]
### Description

Selecting the "Run with PowerShell" option in a `.ps1` file's context menu results in the script being run in `system32` instead of the current directory

### Steps To Reproduce

1. Download a PowerShell script that references the current directory: [Example](https://gist.github.com/RuiNtD/1f8a8b4e4168bde5752cfd0d05e44203)
2. Right click the file, go to "Show more options," and click "Run with PowerShell"

### Requirements

- The script runs in the current directory to match the behavior of `explorer.exe`

### Files Version

3.4.0.0

### Windows Version

10.0.22631.3527

### Log File

[debug.log](https://github.com/files-community/Files/files/15284090/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #12950. You can check there or click subscribe in the right sidebar for updates.
