### ISSUE TITLE
Huge performance issues

### ISSUE THREAD

**Issue by viruseg** [files-community/Files#15379]
### Description

Absolutely any action is accompanied by lag and interface sluggishness. Standard windows explorer performs any action instantly, but Files file manager works as if I have a computer from twenty years ago. My hardware: CPU i7-7700, 32 Gb ram, GPU GTX 1060 6Gb.

### Steps To Reproduce

Attempt any action.

### Requirements

Remove the delay on any action. Make the interface responsive to user actions.

### Files Version

3.4.0.0

### Windows Version

10.0.22631.3447

### Log File

[debug.log](https://github.com/files-community/Files/files/15285708/debug.log)

**Comment by yaira2** [comment]
Thank you for feedback, can give some more specifics of a specific action and share a screen recording?

**Comment by viruseg** [comment]
Going to the Program files folder takes 1.5 seconds. Clicking on other interface elements also has approximately one second delay. For comparison, going to the Program files folder in Explorer takes 0.3 seconds.
Clicking on the drop-down menu in the address bar is delayed by 0.5 seconds. In windows explorer, the same menu appears after 0.25 seconds and does not make clicking uncomfortable.
Navigating through different tabs in Settings is also delayed by up to one second. Such videos can be recorded about any part of the interface. Everywhere there will be a delay in the interface response to a user click.

https://github.com/files-community/Files/assets/919215/e16af736-339a-412a-8d2c-966036b30359


https://github.com/files-community/Files/assets/919215/0b8c74c8-32c5-482b-af46-f2fa9d24b027



https://github.com/files-community/Files/assets/919215/d961d044-1858-4c02-8194-be4a81e72ee0

**Comment by yaira2** [comment]
Thank you for your feedback, the delay is less on my device but unfortunately this is the norm with WinUI applications. We're doing our best to optimize from our end and there is more to do in this area, but the main thing depends on Microsoft improving the WinAppSdk framework (Native AOT support & IL Trimming are two areas Microsoft is working on that should help).

In the meantime, please subscribe to #4180 to be notified when improvements are available.
