### ISSUE TITLE
Bug: Sidebar pin reorder preview stays on screen when letting go over the same item

### ISSUE THREAD

**Issue by Paul-Coy** [files-community/Files#15374]
### Description

I tried to move a folder from the bottom upward. My hand slipped and the folder got stuck ABOVE another folder. Now I had the same folder twice. The original and the new stuck one. 
The stuck folder also had a "Move" icon above the === . 
The stuck folder was on my screen After shutting down the app. (not making this up, I swear!)
The stuck folder was on my screen ABOVE my background image!
I rebooted the PC and it went away finially.

### Steps To Reproduce

1. Right click over sidebar folder
2. Select Reorder Sidebar Items
3. Try to drag bottom folder upwards.

### Requirements

Have moving folders not get stuck, Please. 

### Files Version

3.4.0.0

### Windows Version

10.0.22621.3527

### Log File

[debug.log](https://github.com/files-community/Files/files/15282997/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
@Paul-Coy Despite multiple tries, I can't reproduce this state. Can you reproduce this consistently?

**Comment by Paul-Coy** [comment]
Sorry, I was not allowed from Github apparently to answer last week. I cannot duplicate this. Rather bizarre bug to be sure. Thanks for the update.

**Comment by yaira2** [comment]
Thank you for letting us know.
