### ISSUE TITLE
BUG: Disconnected from GitHub after a while

### ISSUE THREAD

**Issue by EDM115** [files-community/Files#15378]
### Description

There is an option on Settings -> Git which allows to connect to a GitHub account. However after a system restart, the connexion is gone.  
Note that :
- It works when I close and reopen the app. Only a system restart seems to cause the issue.
- The settings "Open on Startup" and "Keep running in the background when closed" are both disabled

### Steps To Reproduce

1. Open Files
2. Connect to GitHub
3. Restart the system
4. Open Files again
5. Notice that it asks to connect again

### Requirements

The connection should stay even after a system restart

### Files Version

3.4.0.0

### Windows Version

10.0.22635.3575 (Actually Windows 11 23H2 build 22635.3575)

### Log File

[debug.log](https://github.com/files-community/Files/files/15285681/debug.log)

**Comment by yaira2** [comment]
The GitHub login info is saved in the Windows Credentials in Control Panel. Do you have anything setup on your device that would wipe that on a restart?

**Comment by EDM115** [comment]
![image](https://github.com/files-community/Files/assets/82015596/02c83d05-c8c7-487e-be80-dcc40f406e76)
well the token is indeed saved, at first I thought it was a refresh issue but nope, it's a common PAT

![image](https://github.com/files-community/Files/assets/82015596/218fef28-7626-43bc-bb71-d8c9fc93cd22)
OG one, generated last week

![image](https://github.com/files-community/Files/assets/82015596/bf2947c1-d762-4eb2-8d56-3ea609ee853f)
and it have been generated when I connected back yesterday


I believe that when the token is created, the limit date is really small, thus forcing to either refresh it (if still within the time frame) or reconnect entirely if we're past it

**Comment by yaira2** [comment]
> I believe that when the token is created, the limit date is really small, thus forcing to either refresh it (if still within the time frame) or reconnect entirely if we're past it

I'm not sure, I've had the same token on my device for a couple of months. Maybe it's a Github setting?

**Comment by EDM115** [comment]
> Maybe it's a Github setting?

I doubt, I'm using some tokens for more than 2 years now

**Comment by yaira2** [comment]
@heftymouse fyi

**Comment by heftymouse** [comment]
@EDM115 just to confirm, after you restart, does it still show up in Windows' Credential Manager?

**Comment by EDM115** [comment]
well yes it shows up, but i believe it's time-related (not launching the app for 1 week)

**Comment by heftymouse** [comment]
So if you open Files immediately after a restart it still works?

**Comment by EDM115** [comment]
yes

**Comment by heftymouse** [comment]
Are you able to reliably reproduce it not working after some time?

**Comment by EDM115** [comment]
i'll tell you in one week :)

**Comment by EDM115** [comment]
seemed like a skill issue on my end

**Comment by EDM115** [comment]
yes  
I believe it's a 3rd party app like CCleaner which may have deleted it  
not an issue with Files itself
