### ISSUE TITLE
Bug: The app won't run as admin

### ISSUE THREAD

**Issue by 0x5bfa** [files-community/Files#15384]
### Description

When I try to run the app as admin, it won't just open while UAC prompt is shown.
It looks like the app crashes on startup.

Confirmed this happens, at least, from v3.4

### Steps To Reproduce

1. Run as admin
2. See the app won't run

### Requirements

- Open like normal execution

### Files Version

3.4.0

### Windows Version

23H2, 10.22631.3447

### Log File

Those come from Even Viewer.
Since it looks like there's something wrong with .NET Runtime, the app logger didn't record anything.
 
Source: .NET Runtime
```
Application: Files.exe
CoreCLR Version: 8.0.224.6711
.NET Version: 8.0.2
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException (0x80004005)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Files.App.Server.IAppInstanceMonitorStaticMethods.StartMonitor(IObjectReference _obj, Int32 processId)
   at Files.App.Server.AppInstanceMonitor.StartMonitor(Int32 processId)
   at Files.App.Program.Main()
```

Source: Application Error
```
Faulting application name: Files.exe, version: 1.0.0.0, time stamp: 0x65a80000
Faulting module name: KERNELBASE.dll, version: 10.0.22621.3447, time stamp: 0x3d876852
Exception code: 0xe0434352
Fault offset: 0x00000000000653ac
Faulting process id: 0x0x322C
Faulting application start time: 0x0x1DAA47F6640D7F2
Faulting application path: C:\Users\onein\source\repos\Files\src\Files.App (Package)\bin\x64\Debug\AppX\Files.App\Files.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: fe9d405d-14a6-4f5d-98f2-c1f9a02c3eae
Faulting package full name: FilesDev_3.4.0.0_x64__ykqwq8d6ps0ag
Faulting package-relative application ID: App
```

**Comment by yaira2** [comment]
Can you check if this happens in v3.3 and v3.2?

**Comment by hishitetsu** [comment]
This seems to occur when starting up the server process.
@hez2010 do you know anything about it?

**Comment by hez2010** [comment]
It seems that out-of-proc WinRT doesn't support elevated activation.

**Comment by yaira2** [comment]
What's the path forward to fix this regression?

**Comment by hez2010** [comment]
The server is not being used currently (there's no any effective functionality implemented in the server), I think we can stop activating the server on the startup for now.
