### ISSUE TITLE
Stucks after trying to access network.

### ISSUE THREAD

**Issue by RusKnyaz** [files-community/Files#15381]
### Description

It looks like the application sends some requests and connot switch to the local drives/folders unitl the reponse recieved

### Steps To Reproduce

1. Click on 'Network drives->Networl'
2. Click on 'Drives->(C:)'
Observed: waiting icon in the left corner of the application and empty files table, no drive content is shown
The content is shown after minutes.
Expected: Forget about network and show the local drive content immediately.

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.4.0

### Windows Version

Windows 11 pro 22631.3447

### Log File

[debug.log](https://github.com/files-community/Files/files/15286328/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #7259 . You can check there or click subscribe in the right sidebar for updates.
