### ISSUE TITLE
Add ability to configure application to open the GIT repository

### ISSUE THREAD

**Issue by RusKnyaz** [files-community/Files#15382]
### What feature or improvement do you think would benefit Files?

Currently I can just open the GIT repository in VSCode using 'Files'. It would be great if I could configure applications that can open the repository. For example, I want to open the GIT repository using GitExtensions application.

Perhaps there is such a setting somewhere, but I didn’t find it due to the lack of searching through the settings, who knows?

### Requirements

- Add configurable setting which allows to change (or add) the default application to be the GIT repository opened with.

### Files Version

3.4.0

### Windows Version

Windows 11

**Comment by yaira2** [comment]
Thank you for your feedback, this is an option we're actively planning. Please add a comment or subscribe to #12857 to be notified of further updates.
