### ISSUE TITLE
Error Files.preview

### ISSUE THREAD

**Issue by Dosik-krg** [files-community/Files#15395]
### Description

1- Files.preview стоит по умолчанию а при открытии ярлыка мой компьютер открывается стандартный проводник explorer. 
2- Нельзя скрыть значок уведомления в системном трее 

### Steps To Reproduce

1- Files.preview стоит по умолчанию а при открытии ярлыка мой компьютер открывается стандартный проводник explorer. 
2- Нельзя скрыть значок уведомления в системном трее 

### Requirements

- e.g. Fix crash that occurs when...
1- Files.preview стоит по умолчанию а при открытии ярлыка мой компьютер открывается стандартный проводник explorer. 
2- Нельзя скрыть значок уведомления в системном трее 

### Files Version

3.4.1.0

### Windows Version

10.0.19045.4239

### Log File

1- Files.preview стоит по умолчанию а при открытии ярлыка мой компьютер открывается стандартный проводник explorer. 
2- Нельзя скрыть значок уведомления в системном трее

**Comment by Josh65-2201** [comment]
Thanks for the report, What happens if you open Windows File Explorer from the start menu or press Win + E?

**Comment by Dosik-krg** [comment]
Из меню пуска и нажатием win+E открывается правильно через community/Files


вт, 14 мая 2024 г., 09:29 Josh65-2201 ***@***.***>:

**Comment by Josh65-2201** [comment]
Then the option works, Not all programs will open Files and this is something Files can't fix.

**Comment by Dosik-krg** [comment]
Как она работает если ярлык мой компьютер на рабочем столе открывается
через стандартный проводник


вт, 14 мая 2024 г., 16:14 Josh65-2201 ***@***.***>:

**Comment by Dosik-krg** [comment]
Хорошо понял. А что со вторым вопросом... ярлык в трее висит и никак его не
убрать не скрыть

вт, 14 мая 2024 г., 19:19 Yair ***@***.***>:

**Comment by yaira2** [comment]
Support for hiding the icon from the tray isn't currently supported.
