### ISSUE TITLE
Drag and drop two files in folder crashed

### ISSUE THREAD

**Issue by MarathonMax** [files-community/Files#15398]
### Description

Drag and drop two files in folder crashed

### Steps To Reproduce

1. Select first file
2. Shift click to select next file
3. Drag and drop onto foilder
4. Crash

### Requirements

Fix crash that occurs when this situation occurs

### Files Version

3.4

### Windows Version

W11 23H2

### Log File

[debug.log](https://github.com/files-community/Files/files/15310530/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Can you see if this is an issue in 3.4.1.0.
