### ISSUE TITLE
Wrong state icons on OneDrive

### ISSUE THREAD

**Issue by tbytetbyte** [files-community/Files#15392]
### Description

On the details view, files and folders inside OneDrive shows incorrect icons and some of them lacks additional "sharing" icon state.

Comparision:

![icons-state](https://github.com/files-community/Files/assets/139590826/227431fb-b38f-4bc0-a27e-520c4ba0b2be)
 

### Steps To Reproduce

Not aplicable

### Requirements

Files should show correct icons (diffent state ones + sharing state icons).

### Files Version

3.4.0.0

### Windows Version

10.0.22631.3527

### Log File

[debug.log](https://github.com/files-community/Files/files/15299155/debug.log)

**Comment by yaira2** [comment]
Files doesn't currently have an indication for the shared state (please open a feature request to track this). Regarding the state of icons, is this only with the details layout? Does restarting Windows help?
