### ISSUE TITLE
When I try to tag a file, the app crashes.

### ISSUE THREAD

**Issue by kapibagi** [files-community/Files#15396]
### Description

When I try to tag a file, the app crashes.
I am writing here because I received a popup saying, 'A problem has occurred. Files has encountered an issue that the developer did not anticipate.'

### Steps To Reproduce

1. Launch Files.
2. Right-click on any file and select 'Tag'.
3. The app crashes.

### Requirements

I was able to tag files as usual before updating the app, so I think the update might have affected something.

### Files Version

3.4.0.0

### Windows Version

10.0.22631.3527

### Log File

[debug.log](https://github.com/files-community/Files/files/15305651/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Can you see if this is an issue in 3.4.1.0.

**Comment by kapibagi** [comment]
The issue was resolved by updating. Thank you for your assistance.
