### ISSUE TITLE
Constant Background CPU Usage

### ISSUE THREAD

**Issue by D-Maxwell** [files-community/Files#15408]
### Description

Despite a lack of tasks to actually execute, the app is constantly chewing on my laptop's processor, significantly reducing its battery life for no seeming benefit.
This seems to be quite inconsistent however.

### Steps To Reproduce

Launch background process
Monitor and witness

### Requirements

I expect my CPU not to be used by the background service that is only meant to keep the process alive.

### Files Version

3.2.2.0

### Windows Version

10.0.19044.2486

### Log File

[debug.log](https://github.com/files-community/Files/files/15331325/debug.log)

**Comment by yaira2** [comment]
There are memory leaks that we're working on resolving, but that shouldn't affect CPU.

Do you have any ongoing file operations?

Even when not minimized, CPU should go down to less than 1% on idle.

**Comment by D-Maxwell** [comment]
> Do you have any ongoing file operations?
> 
> Even when not minimized, CPU should go down to less than 1% on idle.

I do, in fact, *not* have any task for the files app to execute.

If anything, I wish it would work some more as it also refuses to generate file icons for some reason, although I reckon this is a known issue.

**Comment by D-Maxwell** [comment]
I may add, however, that due to the relatively low raw processing power of that laptop of mine, it may be possible that you would be unable to reproduce this as you might overlook an ever so slight increase in consumption given the likely beefy nature of your own machine ; whereas the effect is quite felt on mine, given how process usage scales.

**Comment by yaira2** [comment]
The operation doesn't have to necessarily be from Files, it can be anything that's updating the file system on the device which causes the various file watchers in Files to be triggered.

Either way, we're constantly working on optimizations to reduce memory and CPU consumption. Please refer to #4180 for updates.

**Comment by yaira2** [comment]
What CPU do you have?

**Comment by D-Maxwell** [comment]
> What CPU do you have?

An Intel Celeron N4120 ; it clocks at 1.1GHz up to 2.5 on four cores of a single thread each.

This is clearly meant not to draw much power, at the cost of being extremely slow, making such tiny operations put a noticeable strain onto the processor.

**Comment by Josh65-2201** [comment]
For such a weak CPU this is expected. Files will continue to lower it resource usage on the system with updates but there only so far we can go.

**Comment by yaira2** [comment]
That's correct, we're doing our best to optimize but Intel Celeron is a weaker CPU and will not perform as well with Files.
