### ISSUE TITLE
Files does not remember custom set column widths 

### ISSUE THREAD

**Issue by TadhgEomonn** [files-community/Files#15400]
### Description

Adjust column widths as you would prefer them to be. Move to another folder, then return to the folder with edited column widths--all column widths reset to default: frustration.

### Steps To Reproduce

As in description.

### Requirements

- Program should remember column width adjustments.

### Files Version

3.4.0.0

### Windows Version

10.0.22631

### Log File

[debug.log](https://github.com/files-community/Files/files/15314687/debug.log)

**Comment by yaira2** [comment]
I can see some errors in the log for retrieving the preferences database. Can you see if this is resolved in the preview version of Files? https://files.community/download

**Comment by TadhgEomonn** [comment]
As you perhaps suspected, the forgetful column-width issue is not evident in preview version 3.4.1.0. So false alarm on my part. Thank you for your prompt response.

**Comment by 0x5bfa** [comment]
Thanks for the checking, we didn’t fix any problems around the layout preferences database between 3.4 and 3.4.1
If the issue happens again, let us know! As of now, closing.

**Comment by yaira2** [comment]
> As you perhaps suspected, the forgetful column-width issue is not evident in preview version 3.4.1.0. So false alarm on my part. Thank you for your prompt response.

@TadhgEomonn there actually was an issue regarding layout preferences introduced in v3.4 so this wasn't a false alarm 🙂 

v3.4.1 had a potential fix so it's good to hear your confirmation.

**Comment by TadhgEomonn** [comment]
Glad I could contribute. Keep up the good work.
