### ISSUE TITLE
Tweaks to Tags

### ISSUE THREAD

**Issue by makhren** [files-community/Files#15404]
### What feature or improvement do you think would benefit Files?

The option to add a tagging dropdown to the toolbar with cut/copy/paste instead of in the context menu. This could allow multi tagging without reentering the menu for each tag. Also, in the tag settings, add a toggle to display just the tag color or the tag color with the tag name as it currently displays. This would allow for a more condensed tag column for smaller screens like laptops.

### Requirements

Not a coder so I have no idea what the requirements would be.

### Files Version

3.4.0.0

### Windows Version

10.0.22631.3447

**Comment by yaira2** [comment]
Thank you for the feedback! We're currently tracking this feature request in #11475.

You can add a comment or subscribe to that issue to be notified of further updates.

**Comment by makhren** [comment]
Apparently I missed the duplicate request. But the second part still stands. Currently the Tag column overflows out of view when using multiple tags. Especially if they have longer names. Just adding a choice as to whether the name should be displayed or not would help with smaller screens.

**Comment by yaira2** [comment]
We don't have anything to share on that just yet, but we're exploring different solutions.
