### ISSUE TITLE
Bug: Problem with mapping certain keys in action section

### ISSUE THREAD

**Issue by XTorLukas** [files-community/Files#15403]
### I discovered a small bug where two characters are not displayed correctly:
![image](https://github.com/files-community/Files/assets/84145589/12c4f494-0d3b-4ca8-8e3f-2b239972f944)

 * KEY: `;` wrong map to  `´;`
 ![image](https://github.com/files-community/Files/assets/84145589/ef25a999-a87d-444c-84b5-e19d83b8c7df)

 * KEY: `)` wrong map to `¨)`
 ![image](https://github.com/files-community/Files/assets/84145589/d5cd1586-5a69-4d37-bde8-7f442aaf5164)

but this problem is only in the text string representation, the KEY function is recorded correctly

### Steps To Reproduce

1. Fix string representations mapping this keys

### Files Version

3.4.1.0

### Windows Version

10.0.22631.3593

### Log File

There are no errors

**Comment by yaira2** [comment]
Fyi @0x5bfa

**Comment by 0x5bfa** [comment]
Thanks for the feedback!

It looks like your keyboard is not US keyboard, what keyboard type are you using?
And, when you have a time to do, could you do that same in Windows Terminal > Settings > Actions? If it works well, it’s our problem, let me know:)

**Comment by XTorLukas** [comment]
> It looks like your keyboard is not US keyboard, what keyboard type are you using?

I use the Czech keyboard layout
![image](https://github.com/files-community/Files/assets/84145589/746dc3c0-673c-41ae-b645-3b5169e6e5dc)

**Comment by XTorLukas** [comment]
> And, when you have a time to do, could you do that same in Windows Terminal > Settings > Actions?

In other applications it works correctly

### PowerToys
<image src="https://github.com/files-community/Files/assets/84145589/a4c632b1-4aa7-48fa-90d9-ad089b48e37b" width="500">
<image src="https://github.com/files-community/Files/assets/84145589/d9a7ae03-a6f6-4a59-bd9b-05161956432c" width="500">

### Terminal
![image](https://github.com/files-community/Files/assets/84145589/3b1586cd-6059-4a69-a53a-3d82593c103a)
![image](https://github.com/files-community/Files/assets/84145589/e93da896-0cb5-443b-8098-cbeba3106f57)

**Comment by 0x5bfa** [comment]
Thanks! It looks like Files has an issue around humanizing input keys.

**Comment by XTorLukas** [comment]
### Maybe it will be useful.
I don't know how the implementation is used here, but I personally use this class:
```csharp
public class KeyCodeConverter
{
    [DllImport("user32.dll")]
    private static extern int ToUnicode(
        uint wVirtKey,
        uint wScanCode,
        byte[] lpKeyState,
        [Out, MarshalAs(UnmanagedType.LPWStr)] StringBuilder pwszBuff,
        int cchBuff,
        uint wFlags);

    [DllImport("user32.dll")]
    private static extern bool GetKeyboardState(byte[] lpKeyState);

    [DllImport("user32.dll")]
    private static extern uint MapVirtualKey(uint uCode, uint uMapType);

    [DllImport("user32.dll")]
    private static extern IntPtr GetKeyboardLayout(uint idThread);

    public static char ConvertKeyCodeToChar(Keys key)
    {
        char ch = '\0';
        byte[] keyboardState = new byte[256];
        if (!GetKeyboardState(keyboardState))
        {
            return ch;
        }

        uint virtualKey = (uint)key;
        uint scanCode = MapVirtualKey(virtualKey, 0);
        StringBuilder stringBuilder = new StringBuilder(2);

        int result = ToUnicode(virtualKey, scanCode, keyboardState, stringBuilder, stringBuilder.Capacity, 0);
        if (result > 0)
        {
            ch = stringBuilder[0];
        }

        return ch;
    }
```

### Use in code
```csharp
char character = KeyCodeConverter.ConvertKeyCodeToChar(keyData);
```

**Comment by 0x5bfa** [comment]
@yaira2 ToUnicode seems to be actually needed though I did remove. cinqmilleans's implementation is always correct...

I'll work on.

**Comment by yaira2** [comment]
Thanks!

**Comment by 0x5bfa** [comment]
It looks like we didn't remove that ToUnicode line.
I don't have a way to test.

@XTorLukas If you have a solution to this, do you wanna open a PR for this?

**Comment by XTorLukas** [comment]
@0x5bfa I have my general solution, but I'm here for a short time and need time to get my head around the code, it's not easy with complex code.

But I'm certainly willing to help if I know the solution, just the correct implementation is important.

**Comment by yaira2** [comment]
@XTorLukas thank you for your detailed report and fix!
