### ISSUE TITLE
Feature: Copy the image to AppData when it has been set as the app background

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#15402]
### What feature or improvement do you think would benefit Files?

Currently, if you rename or delete the image you have set as the app background, it will no longer load. To avoid this, I think it is better to copy the image to AppData when it has been set and always load the copied one.

### Requirements

- The image should be copied to AppData when it has been set as the app background
- The image copied in Appdata should be loaded when Files displays it as the app background

### Files Version

3.4.1.0

### Windows Version

10.0.19045.4412

**Comment by 0x5bfa** [comment]
It’s worth having a service called BackgroundImageService or WallpaperService including those functionalities and functionalities setting as desktop background and as Lock Screen (from WallpaperHelpers class)

**Comment by yaira2** [comment]
We could do this, but there are two downsides

1. Privacy
2. It will require using the UI and won't allow users to modify the path in the json file

**Comment by hishitetsu** [comment]
> It will require using the UI and won't allow users to modify the path in the json file

That's fair.

**Comment by yaira2** [comment]
Alternatively, we can keep a backup and resort to that when the path is invalid.

**Comment by hishitetsu** [comment]
In that case, the backup becomes out of date when the original file is updated.

**Comment by yaira2** [comment]
True
