### ISSUE TITLE
when I change my files tag , Files APP crash

### ISSUE THREAD

**Issue by rospirit** [files-community/Files#15413]
### Description

When I change my files tag , Files APP crash, like this:

![20240516_togithub02](https://github.com/files-community/Files/assets/81501083/2f4484a2-edd8-4320-961c-253cfb0f939b)

![20240516_togithub](https://github.com/files-community/Files/assets/81501083/0e1c7c2c-1055-4282-9677-b5f0fae44b4a)

### Steps To Reproduce

1. Right-click on the file to edit the tags.
2. Files APP crash.
3. (manually, not automatically) Reopen the files app.
4. Check this path: C:\Users\"myUserName"\AppData\Local\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState
Reopen the Files APP after it has crashed, and this path will add an new file.
"filestags-temp-1.db","filestags-temp-1-log.db",and 2,3,4,......

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.4.0.0

### Windows Version

10.0.22631.3593

### Log File

[debug.log](https://github.com/files-community/Files/files/15337870/debug.log)
[debug_server.log](https://github.com/files-community/Files/files/15337871/debug_server.log)

**Comment by yaira2** [comment]
Thank you for the report, can you confirm if this issue is fixed in the preview version? https://files.community/download/preview

**Comment by rospirit** [comment]
> Thank you for the report, can you confirm if this issue is fixed in the preview version? https://files.community/download/preview

It looks like it's been fixed,
But there's no old tags data in the preview version.
I forgot to explain to you how I use filesAPP,
And I'm not sure if I'm using it in a way that exceeds the load of FilesAPP?

1. I have at least 5,000 large files and tens of thousands of small files.
2. 40% of the files are labeled with at least 1 tag, 
3. and 20% of the files are labeled with 3-5 tags.
4. I copy my data, so the number of files, and the number of tags mentioned above are doubled.
5. In the last version, I didn't experience any serious problems with my Files APP. I can edit tags without any problem.
However, when I open FilesAPP, I have to wait at least 3 minutes before I can use it.
At this time, my mechanical hard disk will keep making noise.

**Comment by yaira2** [comment]
v3.4 unfortunately introduced an issue regarding tags, but we quickly created a patch and we're happy to hear your confirmation that the preview version no longer has this issue.

We already released this patch to the sideload version, but due to an issue with the Microsoft Partner Center, the Store version doesn't have this patch just yet. We're working with Microsoft to get this published to the Store as soon as possible.

**Comment by yaira2** [comment]
> I know I'm a heavy user, so I've tried to turn off as many unnecessary features as possible to minimize the burden.

This is very good feedback. There is more work to be done, but we're constantly working on optimizations to improve performance and the user experience.
