### ISSUE TITLE
Opening the log file folder from the app's about dialog does not close the dialog

### ISSUE THREAD

**Issue by MarathonMax** [files-community/Files#15411]
### Description

When submitting a bug report one needs to submit the debug.log file. A nifty feature that the software has a quick way to get to it ... BUT in 3.4 when doing so the dialog box no longer closesa

### Steps To Reproduce

When submitting a bug report one needs to submit the debug.log file. A nifty feature that the software has a quick way to get to it ... BUT in 3.4 when doing so the dialog box no longer closesa

### Requirements

When submitting a bug report one needs to submit the debug.log file. A nifty feature that the software has a quick way to get to it ... BUT in 3.4 when doing so the dialog box no longer closesa

### Files Version

3.4

### Windows Version

W11 23H2

### Log File

[debug.log](https://github.com/files-community/Files/files/15337319/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, It isn't suppose too as it open in Windows File Explorer by default, If you have Set as Default enabled then that's why it opens in Files.

**Comment by yaira2** [comment]
I'm not sure I understood correctly, but it sounds like this is a feature request asking for the settings dialog to close when clicking "open log location", can you confirm>

**Comment by yaira2** [comment]
This isn't a previous behavior, but I feel the same way about this behavior (at least when Files is set as the default). Can you do me a favor and open a separate feature request so we can start tracking this?

**Comment by MarathonMax** [comment]
what's the link to submit a new feature ?

Maxime

**Comment by yaira2** [comment]
https://github.com/files-community/Files/issues/new/choose
