### ISSUE TITLE
Feature: Close Settings Dialog when opening Debug Log file folder

### ISSUE THREAD

**Issue by MarathonMax** [files-community/Files#15415]
### What feature or improvement do you think would benefit Files?

Files should close Settings Dialog when opening Debug Log file folder when it's the default app because it not visually obvious that the action was taken. Folder opens in the background and again this is not clear.

### Requirements

- This will provide a cleaner UI
- It will provide a better visual feedback

### Files Version

3.4

### Windows Version

W11 23H2

**Comment by yaira2** [comment]
Thank you for the request, I'm working on this in #15416.
