### ISSUE TITLE
Tag still cause crash after the update, and the same thing happens in the preview version.

### ISSUE THREAD

**Issue by rospirit** [files-community/Files#15426]
### Description

This is a continuation of the question I asked last time.
I compared the preview version with the official version and recorded.

https://github.com/files-community/Files/issues/15413

- - -

The video shows the Preview Version without my old tag datas(in official version path), it doesn't crash.

https://github.com/files-community/Files/assets/81501083/0a767446-8c45-4f2c-b12f-24206d2627ea

When I copy the old Tag data into the Preview version path,
The Tags in perview Version  are  the same as the Tags in official  Version .

https://github.com/files-community/Files/assets/81501083/883dc85f-2be5-4a26-892b-752101cae7b2

### Steps To Reproduce

Steps To Reproduce
1. Right-click on the file to edit the tags.
2. Files APP crash.
3. (manually, not automatically) Reopen the files app.
4. Check this path: C:\Users"myUserName"\AppData\Local\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState
Reopen the Files APP after it has crashed, and this path will add an new file.
"filestags-temp-1.db","filestags-temp-1-log.db",and 2,3,4,......

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.4.1.0

### Windows Version

11

### Log File

[debug.log](https://github.com/files-community/Files/files/15368114/debug.log)

**Comment by hez2010** [comment]
We no longer use the LiteDB for tags storage anymore.
When you copy those files under `LocalState`, can you try skipping the `filetags.db`?

**Comment by rospirit** [comment]
Delete the old .db  files, The problem is solved..
