### ISSUE TITLE
Feature: Change default setting for disabled features to true in Debug mode

### ISSUE THREAD

**Issue by 0x5bfa** [files-community/Files#15427]
### What feature or improvement do you think would benefit Files?

As the title.

### Requirements

- Enable file tags widget
- Enable ADS
- …

### Files Version

3.4.0

### Windows Version

10.22000.0

**Comment by yaira2** [comment]
I prefer keeping dev builds as close as possible to the stable version. As long as you're not reinstalling the app, your personal preferences should be kept even when switching branches.
