### ISSUE TITLE
Install Error: provided .appinstaller URI is already being used 

### ISSUE THREAD

**Issue by TroySchnack** [files-community/Files#15424]
### Description

Version 3.4.1.0 Install error. The provided .appinstaller URI is already being used by another package family. Check the AppXDe ...
I cannot see the rest of the error. Running Win 11 64-bit 23H2. Preview of Files install works. Verified "Files" folder in AppData\Local removed from previous version left behind even after Uninstall.

### Steps To Reproduce

Run File.Stable.exe

### Requirements

Install should proceed

### Files Version

3.4.1.0

### Windows Version

Win 11 23H2 OS Build 22631.3527 Enterprise

### Log File

Since it doesnt install, I don't know where the log file might be located.

**Comment by Josh65-2201** [comment]
Please see https://files.community/docs/install#:~:text=starting%20an%20update.-,Steps,-required%20for%20the

**Comment by Josh65-2201** [comment]
Can you try
1. Make sure Files is closed from the system tray
2. Open an admin PowerShell window (Windows default not PowerShell 7)
3. Run the below
```
Get-AppXPackage Files* | Remove-AppXPackage
```
4. Check the Start menu > All apps for Files

**Comment by TroySchnack** [comment]
Even though it did not appear in Start Menu or Settings|Apps (after uninstall), the PowerShell command actually did something in the background that fixed the issue. Thanks

**Comment by TroySchnack** [comment]
Using the PowerShell command cleaned up the lingering issue. Install works fine now.

**Comment by C0ns0leC0wb0y** [comment]
I'm also having this exact issue however running the powershell command did not work. 
I will note that I did have a previous version of Files installed awhile ago.

**Comment by Josh65-2201** [comment]
Did you get any errors from PowerShell?

**Comment by C0ns0leC0wb0y** [comment]
Nope. Nothing returned. 

<img width="840" height="123" alt="Image" src="https://github.com/user-attachments/assets/034737c9-d6b8-4fbc-9d87-2076ff2e14b2" />

**Comment by C0ns0leC0wb0y** [comment]
Ran the winget code in admin mode on powershell and got it to fully install.
