### ISSUE TITLE
Bug: Can't access any items to display

### ISSUE THREAD

**Issue by theHeadlessGrapes** [files-community/Files#15437]
### Description

I'm unsure if this problem is being addressed or it is just not possible, but when trying to quickly navigate to different folders using the drop-down menus in the Files address bar while in a folder with a hidden attribute, you might encounter the message "Can't access any items to display" instead of seeing the expected contents like in the regular File Explorer.

![image](https://github.com/files-community/Files/assets/158155682/4440733f-ed9a-44b9-8240-405c2c0b1e04)

### Steps To Reproduce

1. Ensure you have a folder with the hidden attribute set by either creating a folder and set the attribute to be Hidden or navigate to any pre-existing hidden folders.
2. Open a folder that has the hidden attribute set and in the address bar, click on the drop-down menu to quickly access other folders.
3. From the drop-down submenu, it should display different folders to navigate to, but instead the message "Can't access any items to display" appears, preventing access to other folders quickly.

### Requirements

-  The contents of the selected folder should be displayed accurately, regardless of the hidden attribute of the initially accessed folder.
- The quick access feature via the address bar drop-down should not produce errors or obstruct the viewing of folder contents.

### Files Version

3.4.1.0

### Windows Version

10.0.22635.3640

### Log File

[debug.log](https://github.com/files-community/Files/files/15391720/debug.log)

**Comment by yaira2** [comment]
Does this happen everywhere, or just `AppData`?

**Comment by yaira2** [comment]
This is likely related to #8269

**Comment by yaira2** [comment]
Thank you for the report, we appreciate it!

We're going to continue tracking this in #8269. You can subscribe or add a comment to get notified when it's resolved.
