### ISSUE TITLE
Another way of adding a new tag

### ISSUE THREAD

**Issue by lcmuniz** [files-community/Files#15436]
### What feature or improvement do you think would benefit Files?

- Adding a tag via context menu.
- Subtags (tags inside tags)

### Requirements

 - I think there could be an option to create a new tag via the context menu by clicking on a file name. In fact, this could be done without the need to open a new window. An input field just appeared next to the menu to type in the name you want. If the tag already exists, it would just be applied. If not, a new tag would be created and applied. 
 - Another interesting feature would be the possibility of having subtags (tags within tags).

### Files Version

3.4.1.0

### Windows Version

Windows 11 Pro 23H2

**Comment by 0x5bfa** [comment]
Thank you for the feedback.

> Adding a tag via context menu.

This is something we already have, you can right click on an item and select whatever tag you’d like.

> Subtags (tags inside tags)

This is already reported in #12738. We’re tracking this feature request there, please subscribe it to get further info when we have news on this.

**Comment by lcmuniz** [comment]
Sorry, maybe I was not clear. Yes, you can use context menu to select a existing tag to add to a file. But it is not what I was suggesting. I was talking about add a new tag without the neeed to go another screen to create a tag and then return to the explorer. The user experience should be: right click the file, select 'add tag', type the tag name  and press ENTER. If the tag already exists it should be applied, if not it should be created and applied.
Thanks.

**Comment by 0x5bfa** [comment]
Thanks for the clarification, and sorry for the misunderstanding!

We are tracking this request in #12146.
Let me know if I’m right now:)

**Comment by yaira2** [comment]
> I think there could be an option to create a new tag via the context menu by clicking on a file name. In fact, this could be done without the need to open a new window. An input field just appeared next to the menu to type in the name you want. If the tag already exists, it would just be applied. If not, a new tag would be created and applied.

Thank you for your feedback, this sounds like the request @0x5bfa linked here #12146. It's on our todo list and we hope to add it in a future update.

> Another interesting feature would be the possibility of having subtags (tags within tags).

Nested tags is something we're discussing but we haven't made a decision whether or not to add this feature.
