### ISSUE TITLE
Each time you start Files, it will prompt you to install the Windows subsystem for Linux

### ISSUE THREAD

**Issue by Anyayay** [files-community/Files#15439]
### Description

I am a Chinese speaker, and the following are machine translations:

Whenever Films is launched, it prompts you to install WSL
and after closing the window, you can still use it normally.

> No Windows Subsystem for Linux is installed on this system. You can install it by running "wsl.exe --install".
> For more information, visit https://aka.ms/wslinstall
> Press any key to install the Windows Subsystem for Linux.
> Press CTRL-C or close this window to cancel.
> This prompt will time out in 60 seconds.
> ![image](https://github.com/files-community/Files/assets/37764175/29a4a9c3-212d-470d-86ab-4596d90929f2)

---
每次Films启动时，会提示要求安装 WSL，但关闭该窗口后，仍然可以正常使用

提示内容：

未安装适用于 Linux 的 Windows 子系统。可通过运行 “wsl.exe --install” 进行安装。
有关详细信息，请访问 https://aka.ms/wslinstall

按任意键安装适用于 Linux 的 Windows 子系统。
按 CTRL-C 或关闭此窗口以取消。
此提示将在 60 秒后超时。

### Steps To Reproduce

Films is launched

### Requirements

- Will not be prompted to install it

### Files Version

3.4.1.0

### Windows Version

10.0.26217.5000

### Log File

[debug.log](https://github.com/files-community/Files/files/15392872/debug.log)

**Comment by Anyayay** [comment]
Sorry, I found the same issue

**Comment by yaira2** [comment]
Is this Windows Insider or Windows stable?

**Comment by Josh65-2201** [comment]
Seems there using the insider canary build https://blogs.windows.com/windows-insider/2024/05/15/announcing-windows-11-insider-preview-build-26217-canary-channel/

**Comment by Anyayay** [comment]
> Is this Windows Insider or Windows stable?

Insider

**Comment by yaira2** [comment]
Thanks! We'd still like to find a workaround but it seems to be an issue with Windows Insider at the end of the day.

**Comment by dharmababa** [comment]
This is happening on release 24H2 builds that is now in stable release through the Copilot+ PC launch. I have a Surface Laptop 7 that is not enrolled in Insider and still seeing this issue.

**Comment by Josh65-2201** [comment]
It has been fixed and will be available in the next update
