### ISSUE TITLE
Bug: Address bar formatting causes issues when running commands through address bar 

### ISSUE THREAD

**Issue by FieryRMS** [files-community/Files#15447]
### Description

Commands run through the address bar are being formatted, which breaks some commands. For example, `//` and `/` are converted to `\` in the address bar. `https://github.com/files-community/Files` becomes `https:\github.com\files-community\Files`. This behavior is inconsistent with how windows explorer or run dialog handles commands.

This can cause issues with many commands that take links/paths/strings as parameters and expect a certain format, like `git`, `curl`. For example, running `git clone https://github.com/files-community/Files` does not work in Files but works in Windows explorer. `curl https://httpbin.org/get` does not work in Files for the same reason.

### Steps To Reproduce

1. run `ping https://github.com/files-community/Files` from the address bar. (we are only interested in the output, not if it pings)
2. Actual output: 
     ```Ping request could not find host https:\github.com\files-community\Files. Please check the name and try again.```

### Requirements

Expected output: 
```Ping request could not find host https://github.com/files-community/Files. Please check the name and try again.```

This is the behavior in Windows Explorer. More specifically, `https://github.com/files-community/Files`  remains unchanged when passed as a parameter to the command.

### Files Version

3.4.1.0

### Windows Version

10.0.22631.3593

### Log File

(not necessary)

**Comment by Josh65-2201** [comment]
Thanks for the report, the path bar isn't meant to be used for terminal commands or replace run dialog, at most it opens a program with a path added. We're tracking integrated terminals in #6235 . You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
> Thanks for the report, the path bar isn't meant to be used for terminal commands or replace run dialog, at most it opens a program with a path added. We're tracking integrated terminals in #6235 . You can check there or click subscribe in the right sidebar for updates.

@Josh65-2201 the original intention was for the address bar to help launch commands.
