### ISSUE TITLE
Bug: Not correct Default system language load for `MessageFormatExtensions`

### ISSUE THREAD

**Issue by XTorLukas** [files-community/Files#15440]
### Description

The system language is incorrectly defined, a problem occurs when Formater takes the default 'en' for parsing

### Screenshot problem
1. If I don't choose the exact language
![image](https://github.com/files-community/Files/assets/84145589/1e785f84-c200-4c9e-9801-e561efaa11ce)
2. Language not set to system language
![image](https://github.com/files-community/Files/assets/84145589/d5477314-8efa-453e-ad19-21a5eb164f08)
3. This causes the plural localization to function incorrectly
![image](https://github.com/files-community/Files/assets/84145589/489a9e43-9f1f-4748-99df-439cbe18e1dc)

### Steps To Reproduce

1. If not specified default language load OS default correctly

**Comment by XTorLukas** [comment]
We overlooked this because I had it selected explicitly, but I have a quick workaround

**Comment by yaira2** [comment]
Can we check if it's empty?

**Comment by XTorLukas** [comment]
It would be enough for this method to be static
https://github.com/files-community/Files/blob/b2863a3d483e338357d6a283f16cde702cb97088/src/Files.App/ViewModels/Settings/GeneralViewModel.cs#L146-L163

And then you could just use a similar condition for 'en' instead of CultureInfo.InstalledUICulture and store it in ApplicationLanguages.PrimaryLanguageOverride, I just don't know what the convention is for adding it to the App start method
https://github.com/files-community/Files/blob/b2863a3d483e338357d6a283f16cde702cb97088/src/Files.App/Extensions/MessageFormatExtensions.cs#L18
