### ISSUE TITLE
Bug: New floating style toolbar doesn't have mica effect

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#15450]
### Description

![image](https://github.com/files-community/Files/assets/26977075/5294e7fc-5768-4990-b9a2-a968eebe951c)

### Steps To Reproduce

1. Set Files to dark mode

### Requirements

- Have toolbar background follow folder items view background

### Files Version

Dev

### Windows Version

10,0,22621.3447

### Log File

*

**Comment by yaira2** [comment]
It has mica but it's a very subtle affect

**Comment by yaira2** [comment]
This is resolved in #15456
