### ISSUE TITLE
Bug: Address bar does not launch programs when path contains spaces and has parameters

### ISSUE THREAD

**Issue by FieryRMS** [files-community/Files#15455]
### Description

The Files app fails to find and launch programs if the path contains spaces and has parameters. Eg: running 
`D:\Folder With Spaces\program.exe param` from the address bar, Files tries to "execute" `D:\Folder` with params ` With Spaces\program.exe param`. The program still fails to run even if we explicitly specify the filename using quotes like, 
`"D:\Folder With Spaces\program.exe" param` .

### Steps To Reproduce

1. create a batch file named `test script.bat` with the follow script:
    ```cmd
    @echo off
    echo %*
    ```
2. execute the script with some parameters through the address bar, e.g.: `test script.bat param`. The script fails to run.
3. execute the script with quotes around the file name, e.g.: `"test script.bat" param`. The script fails to run.

### Requirements

Expected outcome was that it should've been able to run when filename was explicitly specified with quotes. (`"test script.bat" param`)

This bug is caused by this part of the code,
https://github.com/files-community/Files/blob/4b77a5a1c74ffaa5c2bd129fa97bc79009b23590/src/Files.App/ViewModels/UserControls/AddressToolbarViewModel.cs#L821-L828

I propose to check if the user provided `"` to avoid ambiguity. If the first character is a `"` we look for the next `"` and use that as the delimiter instead. If we cannot find the second `"` we use the whole input as `fileName`. This behavior should be consistent with how `cmd` handles spaces.
Here is a possible implementation.

```cs
private static async Task<bool> LaunchApplicationFromPath(string currentInput, string workingDir)
{
	currentInput = currentInput.TrimStart();

	var positionOfDelimiter = currentInput.IndexOf(' ');
	if (currentInput.ElementAt(0) == '"')
		positionOfDelimiter = currentInput.IndexOf('"', 1);

	// if no spaces or doesn't start with a '"'
	if (positionOfDelimiter == -1)
		positionOfDelimiter = currentInput.Length - 1;

	positionOfDelimiter += 1; // include delimiter in fileName
	var fileName = currentInput.Substring(0, positionOfDelimiter);
	var arguments = currentInput.Substring(positionOfDelimiter);

	return await LaunchHelper.LaunchAppAsync(fileName, arguments, workingDir);
}
```

### Files Version

3.4.1.0 - Dev

### Windows Version

10.0.22631.3593

### Log File

(not required)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
@FieryRMS would you like to open a PR?

**Comment by FieryRMS** [comment]
> @FieryRMS would you like to open a PR?

sure, I'll be glad to

**Comment by yaira2** [comment]
@FieryRMS thank you!
