### ISSUE TITLE
Bug: Pin to sidebar does not work

### ISSUE THREAD

**Issue by DuyTranSipher** [files-community/Files#15452]
### Description

- Pin a folder to the Sidebar does not work

### Steps To Reproduce

Just select any folder then choose option "Pin to sidebar"the 

### Requirements

The wanted folder should be pinned to the Sidebar

### Files Version

3.4.1.0

### Windows Version

Windows 11 22H2. OS build: 22621.3593

### Log File

[debug.log](https://github.com/files-community/Files/files/15410909/debug.log)

**Comment by 0x5bfa** [comment]
Thanks for the feedback.
Is that folder authorized to be accessed by you?

**Comment by DuyTranSipher** [comment]
> Thanks for the feedback. Is that folder authorized to be accessed by you?

Yes, that the Download folder of the OS

**Comment by Josh65-2201** [comment]
Is Files crashing for you or just not adding it.

**Comment by DuyTranSipher** [comment]
> Is Files crashing for you or just not adding it.

Ah I knew it. It was not "the Pin to sidebar feature doesn't work" 
Actually it still works but didn't meet my expectation, which the Pinned sidebar will automatically expand when I pin a folder.
Detail in the attachment video

https://github.com/files-community/Files/assets/92284695/52537eaf-3178-46d1-9892-51ca3d077d45

**Comment by 0x5bfa** [comment]
I guess this is by design.
Ability to collapse allows you to make it collapse anyways.

**Comment by yaira2** [comment]
I agree that this is by design.
