### ISSUE TITLE
Cut-pasting item in the same folder creates a copy of the item

### ISSUE THREAD

**Issue by soumyamahunt** [files-community/Files#1546]
**Describe the bug**
Cut-pasting an item from the same folder replaces the item with a copy of it and attaches "-Copy" to its original name.

**To Reproduce**
1. Open files-uwp app.
2. Cut an item from a folder
3. Try pasting the item in the same folder.

**Expected behavior**
A dialog should be prompted with option to either skip or cancel the operation.

**Screenshots**
![EwoK2txTc6](https://user-images.githubusercontent.com/51203900/88255564-4e7b6a00-ccd6-11ea-9066-d0fd311eef98.gif)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1903 18362.239
 - App version: v0.12.0

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?
Although it doesn't crash the app, the problem persists across restarts.

**Comment by yaichenbaum** [comment]
@soumyamahunt Would you like to work on this issue?

**Comment by yaichenbaum** [comment]
@soumyamahunt This issue should be resolved with #2742.
