### ISSUE TITLE
Bug: Search result stop showing when switching tabs

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#15464]
### Description

*

### Steps To Reproduce

1. Search for contents in one tab
2. Wait for search to finish and have all results show
3. Switch to another tab
4. Switch back to tab with search results on
5. See result disappear

### Requirements

- Keep results shown when switching tabs

### Files Version

3.4.2.0

### Windows Version

10.0.22621.3593

### Log File

[debug.log](https://github.com/files-community/Files/files/15441045/debug.log)

**Comment by yaira2** [comment]
Thank you for the report
