### ISSUE TITLE
Bug: Files does nothing exporting settings, crashes importing settings

### ISSUE THREAD

**Issue by FieryRMS** [files-community/Files#15465]
### Description

FIles does nothing when trying to export settings. It crashes when trying to import settings.

### Steps To Reproduce

1. `Settings -> Advanced -> Export settings` The button clicks, but nothing else happens.
2. `Settings -> Advanced -> Import settings` Files abruptly closes with no other messages.

### Requirements

1. Expected to show `Save File` dialog.
2. Expected to show `Open File` dialog.

### Files Version

3.4.2.0 - Preview

### Windows Version

10.0.22631.3593

### Log File

[debug-export-import-bug.log](https://github.com/files-community/Files/files/15442148/debug-export-import-bug.log)

**Comment by 0x5bfa** [comment]
Thanks I’ll fix soon.

**Comment by yaira2** [comment]
Thank you for the report, this is a regression in the preview version and we'll make sure to fix before releasing to stable.
