### ISSUE TITLE
Bug: When selecting multiple video files, the total duration is missing

### ISSUE THREAD

**Issue by AngryDavid808** [files-community/Files#15468]
### Description

When I select one video file and go to "Details" in "Properties", I can see its duration time just fine. However, the same does not apply when trying to observe the properties of multiple video files. The duration time is left blank.
![image](https://github.com/files-community/Files/assets/65258039/d47e6939-f671-4638-8ec9-091a48c5ee7c)

### Steps To Reproduce

1. Select 2 or more video files
2. Right-click on the video files and click the properties icon
3. Go to "Details" and scroll down to "Duration" in the "Media" section

### Requirements

- Implement the calculation of total duration time for multiple video files

### Files Version

3.4.1.0

### Windows Version

10.0.19045.4412

### Log File

[debug.log](https://github.com/files-community/Files/files/15444601/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
@AngryDavid808 this will be resolved in the next release.
