### ISSUE TITLE
Bug: Pin to sidebar doesn't add to pinned section

### ISSUE THREAD

**Issue by Assemblerguru** [files-community/Files#15460]
### Description

I move a folder "Downloads" from file view to the "pinned" folder under "Startpage" and noting happens. Also if I choose to call "Pin to sidebar" nothing happenes.

### Steps To Reproduce

1. Open a drive (e.g.D:)
2. Select a folder with RMB
3. Select menu entry "Pin to favourite  / add to pinned"

Expectation: The folder is show under the "pinned" folder on the left side
Result: Nothing happens

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.4.1.0

### Windows Version

10.0.22631.3593

### Log File

[debug.log](https://github.com/files-community/Files/files/15424573/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #15452. You can check there or click subscribe in the right sidebar for updates.

**Comment by 0x5bfa** [comment]
Thanks for the feedback.
We found that the linked issue was not similar to this issue.


Can you tell us:
- whether the app crash.
- whether the app still doesn’t show it even after restart Windows or the app.

**Comment by Assemblerguru** [comment]
Hi!

Well:

  *
the app does not crash
  *
Yes - after I restart the computer the pinned folders are available!

Thanks

kind regards,
André
________________________________
