### ISSUE TITLE
When deleting a large folder, the file count is incorrect

### ISSUE THREAD

**Issue by JTFA** [files-community/Files#15470]
### Description

When deleting a large folder, the file count is incorrect. The number of deleted files exceeds the displayed total number of files displayed.
![屏幕截图 2024-05-26 133455](https://github.com/files-community/Files/assets/57850248/840d41a6-b620-4eeb-8aeb-bbeb48575bcd)

### Steps To Reproduce

deleting a large folder and select permanent delete. (I only tested permanent delete.)

### Requirements

the file count should be correct

### Files Version

3.4.1.0

### Windows Version

10.0.22631.3593

### Log File

[debug.log](https://github.com/files-community/Files/files/15446220/debug.log)

**Comment by 0x5bfa** [comment]
Thank you for the feedback!

This looks like Windows issue since we've seen this in PowerShell too.
Still we're working on what we can do for this area.

**Comment by yaira2** [comment]
@0x5bfa isn't there an existing issue where we are tracking this?

**Comment by Josh65-2201** [comment]
There this one https://github.com/files-community/Files/issues/13860

**Comment by yaira2** [comment]
@JTFA thank you for the feedback, we're tracking this in #13860 and you can subscribe to that issue to be notified when it's fixed.
