### ISSUE TITLE
Feature: Add support for Infomaniak kDrive cloud

### ISSUE THREAD

**Issue by manfromarce** [files-community/Files#15475]
### What feature or improvement do you think would benefit Files?

kDrive ([https://www.infomaniak.com/kdrive](https://www.infomaniak.com/kdrive)) doesn't show up in the cloud section. The folder is usually located in the user profile folder.

### Requirements

- This proposal will make the kDrive folder appear in the cloud section in sidebar
- The standard cloud-specific operations and icons should be supported

### Files Version

3.4.1.0

### Windows Version

10.0.22621.3593

**Comment by Josh65-2201** [comment]
Thanks for the feedback, I've added this to the project board.

**Comment by yaira2** [comment]
This is now on our todo list

**Comment by yaira2** [comment]
For our own reference
> Hello, Thanks for integrating kDrive into your product!
> 
> "we would verify the installation of kDrive" => You can use the following PowerShell command.
> 
> ```
> PS C:\Users\Chris> get-package -Name kDrive
> 
> Name                           Version          Source                           ProviderName
> ----                           -------          ------                           ------------
> kDrive                         3.6.0                                             Programs
> ```
> 
> "retrieve its path to display in the cloud drives segment of our sidebar" => Are you talking about the path of the app or the synchronized folders? The exe path is: C:\Program Files (x86)\kDrive\kDrive.exe
> 
> You can find the synchronised folders by browsing Windows Registry keys in "Computer\HKEY_CURRENT_USER\Software\Classes\CLSID" and filter on "kDrive". The folder path is the value of the key "targetFolderPath" in "Computer\HKEY_CURRENT_USER\Software\Classes\CLSID<clsid>\Instance\InitPropertyBag"

**Comment by yaira2** [comment]
@manfromarce this feature will be included in our next release.
