### ISSUE TITLE
Bug: Changing layout mode switches focus in Dual Pane mode

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#15483]
### Description

When operating in Dual Pane mode, changing the layout mode (e.g., from grid to details) results in an unintended shift of focus to the other pane. This behavior disrupts user workflow as the focus moves away from the current pane, potentially leading to user confusion and inefficiency.

### Steps to repro

- Enable dual pane mode
- Change layout mode in left pane and see the focus switch to the right pane

### Files Version

v3.4.1

### Windows Version

Windows 11

**Comment by hishitetsu** [comment]
Isn't this the same as #15397?

**Comment by yaira2** [comment]
Yes, I thought there was an existing report 🙂
