### ISSUE TITLE
Bug: Changing heights when switching in dual pane mode

### ISSUE THREAD

**Issue by XTorLukas** [files-community/Files#15489]
### Description

When switching between panels in Dual Pane mode, the height of the panels changes.

![image](https://github.com/files-community/Files/assets/84145589/ba847d62-f82d-43ff-8e94-ae7938a518d0)
![image](https://github.com/files-community/Files/assets/84145589/9a897d1a-315a-4f26-9de1-88459d4eef81)

The solution will be to set an advanced `StatusBar` activation condition. That is, display it whenever Dual Pane mode is running and at the same time when it is not Home

### Steps To Reproduce

This problem occurs when one of the panels is `Home`.

### Files Version

3.4.4.0

### Windows Version

10.0.22631.3593

**Comment by 0x5bfa** [comment]
That’s by design.
We might restore but we’re going to hold this design.

**Comment by XTorLukas** [comment]
For me the height change is ok, but for a dual panel it's annoying

**Comment by 0x5bfa** [comment]
@yaira2 @mdtauk Like File Explorer does, why not show Total Count for Home?
I agree with @XTorLukas.
