### ISSUE TITLE
Strange behavior

### ISSUE THREAD

**Issue by Andrew-Sor** [files-community/Files#15495]
### Description

After some time of use as the default explorer, it begins to behave strangely.

Before:
https://github.com/files-community/Files/assets/133566800/edc7851a-dfc5-4ec5-ae19-646e664f5c8f

After:
https://github.com/files-community/Files/assets/133566800/e1c4b418-b658-427e-8b93-eb6986a49b31

### Steps To Reproduce

1. Set as default explorer.
2. Use it for a while.
3. Try opening the trash can or notice the absence of pinned items in the left panel or on the home.

### Requirements

Fix this strange behavior issue.

### Files Version

3.4.1.0

### Windows Version

Windows 11 Pro 23H2 OS build 22631.3593

### Log File

[debug.log](https://github.com/files-community/Files/files/15481620/debug.log)

**Comment by 0x5bfa** [comment]
Could you type "Shell:RecycleBinFolder" into the address bar?

**Comment by Andrew-Sor** [comment]
> Could you type "Shell:RecycleBinFolder" into the address bar and see if it works?

No, the result is the same

**Comment by Josh65-2201** [comment]
Please try reinstalling Files. (You can export your settings in Files settings > Advanced > Export/Import)

**Comment by Andrew-Sor** [comment]
By the way, this problem disappears after rebooting or terminating Files.

**Comment by Andrew-Sor** [comment]
> reinstalling Files

I tried it. After a while this happens again.

**Comment by yaira2** [comment]
Is this only when Files is set as the default?

**Comment by Andrew-Sor** [comment]
> Is this only when Files is set as the default?

To be honest, I haven't tried otherwise...😅😅😅 Then you will have to open the basket by inserting its address into the address bar, and I only found out about it today...😅

But I can say for sure that it must remain in the background, otherwise it will restart every time, and as you know, restarting cures this problem.

**Comment by Andrew-Sor** [comment]
I checked, this problem does not depend on the fact that Files is installed by default.

**Comment by Josh65-2201** [comment]
We're continuing to track this in #15083. You can check there or click subscribe in the right sidebar for updates.
