### ISSUE TITLE
Onedrive sync icon misaligned if label does not have 3 lines of text in grid view

### ISSUE THREAD

**Issue by CharlieEllman-NTTDATA** [files-community/Files#15498]
### Description

looks like the onedrive sync icon is set at a fixed level of the middle line of text. but some files only have one line and it looks off. please adjust the icon postioning to be dynamic

### Steps To Reproduce

have a folder of short named icons in onedrive. view in grid view.

### Requirements

sync icon should be aligned with the file labels, not floating beneath them

### Files Version

3.4.1.0

### Windows Version

10.0.22631.3593

### Log File

**Debug File:** [debug.log](https://github.com/files-community/Files/files/15486252/debug.log)

Files App - Icons with 1 line label. Sync icon is weirdly floating below the label.
![Files App - Icons with 1 Line](https://github.com/files-community/Files/assets/91145296/383a1eb4-4d7d-4693-a6dd-87363f93073b)

Files App - icons with 3 line labels. Sync icon is good on the big labels but floating on the small label.
![Files App - Icons With 3 Lines](https://github.com/files-community/Files/assets/91145296/a68c42d5-ca25-4764-a046-b7cd7042f767)

Windows 11 Explorer - icons with 1 line labels. Sync icon is inline on all files.
![Windows 11 File Explorer Normal View](https://github.com/files-community/Files/assets/91145296/9b881ea4-a0e0-418e-8d29-319ca69e09b6)

Windows 11 Explorer - icons with mixed line labels. Sync icon is i
![Windows 11 File Explorer - Multi Height File Labels](https://github.com/files-community/Files/assets/91145296/cae743ae-b11f-4ba5-afcc-54ce244f3322)
nline on all files.

**Comment by yaira2** [comment]
Thank you for the report, can you confirm if this is the same as #14332?

**Comment by CharlieEllman-NTTDATA** [comment]
related, but not identical. that seems to be about the line breaking of the name, and this is about the positioning of the sync icon.

**Comment by 0x5bfa** [comment]
I guess its the same. Its for cloud drive icon misalignment.
