### ISSUE TITLE
A normal installer w/o 3rd party sites, internet requirement, etc

### ISSUE THREAD

**Issue by LTGM** [files-community/Files#15491]
### What feature or improvement do you think would benefit Files?

Title. Why do we have to download questionable exe files from 3rd party sites when github has built-in functionality to post proper exe/installers?

### Requirements

People w/o the internet will be able to install it on their machines w/o the involvement of 3rd party sites and taking additional unnecessary risks?

### Files Version

123

### Windows Version

10

**Comment by 0x5bfa** [comment]
That's official site. https://files.community
The installer is not open sourced but in the future we might.

**Comment by yaira2** [comment]
Thank you for your feedback, you can find the official download on the Files website https://files.community/download.

Additional installation methods are also available here https://files.community/docs/install
