### ISSUE TITLE
I want to add functionality

### ISSUE THREAD

**Issue by gen5421** [files-community/Files#15494]
### What feature or improvement do you think would benefit Files?

I want you to add a function that allows you to expand the width by dragging the border of the column. Like a Mac Finder APP. 

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.4.1.0

### Windows Version

10.0.22631.3593

**Comment by 0x5bfa** [comment]
Thank you for the feedback.

We’re racking this issue in #6534, please subscribe the issue from the Subscribe button on the right pane to get further news.
