### ISSUE TITLE
Add a support for the 'Peek' PowerToys

### ISSUE THREAD

**Issue by CAPSLOOCK** [files-community/Files#15506]
### What feature or improvement do you think would benefit Files?

It would be amazing to be able to use the very good 'Peek' tool from 'PowerToys' in files app. 

### Requirements

- A support for this tool who works perfectly on windows explorer.

### Files Version

3.4.4.0

### Windows Version

10.0.26120.670

**Comment by Josh65-2201** [comment]
Thanks for the feedback, this currently isn't possible due to power toys peek not having a way of doing so https://github.com/microsoft/PowerToys/issues/26422

**Comment by 0x5bfa** [comment]
@CAPSLOOCK Thanks for reaching out and being late to provide more information. To elaborate on that a bit, we'd like to add support and we have the infrastructure ready to do so, but we're dependent on PowerToys creating an API for third party apps. In the meantime, we suggest trying QuickLook or SeerPro https://files.community/docs/features/integrations.
