### ISSUE TITLE
Make log files easier to identify

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#1550]
**Describe the solution you'd like**
Use the .log extension instead of txt. The log extension is used by many applications to distinguish log files from regular text files.

**Describe alternatives you've considered**
None

**Comment by soumyamahunt** [comment]
That's a good idea also we should add an environment variable that takes to the folder where log is stored, it is difficult for normal users to go to the application data folder.

**Comment by R3voA3** [comment]
> That's a good idea also we should add an environment variable that takes to the folder where log is stored, it is difficult for normal users to go to the application data folder.

The user can already access the log folder via settings.

**Comment by soumyamahunt** [comment]
> The user can already access the log folder via settings.

Yeah, but it opens the folder in Windows Explorer. This app is meant to make user less reliant on Windows Explorer.

**Comment by R3voA3** [comment]
> > The user can already access the log folder via settings.
> 
> Yeah, but it opens the folder in Windows Explorer. This app is meant to make user less reliant on Windows Explorer.

I agree. It should use the app instead.

**Comment by Jaiganeshkumaran** [comment]
@R3voA3 @soumyamahunt No need. What if there's a bug that prevented access? Using File Explorer is better.

**Comment by soumyamahunt** [comment]
> @R3voA3 @soumyamahunt No need. What if there's a bug that prevented access? Using File Explorer is better.

Every application can access its localdata folders without any permissions. So there wouldn't be any prevention in that case. If the app crashes on launch then user has to use explorer anyway.

**Comment by Jaiganeshkumaran** [comment]
> > @R3voA3 @soumyamahunt No need. What if there's a bug that prevented access? Using File Explorer is better.
> 
> Every application can access its localdata folders without any permissions. So there wouldn't be any prevention in that case. If the app crashes on launch then user has to use explorer anyway.

I'm not talking about permission. What if we had a bug where the app crashes when navigating or some other app bug that only occurs sometimes.

**Comment by R3voA3** [comment]
Then we should already start at ""What happens if the app crashes when navigating to the settings page". 

Isn't is possible to open the log folder automatically in explorer if the app crashes? I know some applications which automatically zip all relevant data and copy it on the desktop for easy access.

**Comment by Jaiganeshkumaran** [comment]
In older versions of Files UWP, a BSOD like page will appear with options to retry and send feedback. We could restore that page and add the option to open log location.

**Comment by yaichenbaum** [comment]
> > > The user can already access the log folder via settings.
> > 
> > 
> > Yeah, but it opens the folder in Windows Explorer. This app is meant to make user less reliant on Windows Explorer.
> 
> I agree. It should use the app instead.

@R3voA3 Using the app in this case can be a problem in the case the app is crashing when navigating to a directory.

**Comment by yaichenbaum** [comment]
It looks like the majority or in favor of switching to the file extension to log so I am approving this issue.

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran This issue should be resolved with #4442.
