### ISSUE TITLE
Bug: BaseLayoutPage.UpdateSelectionSize OverflowException

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#15500]
### Description

**BaseLayoutPage.UpdateSelectionSize ()**
System.OverflowException: Arithmetic operation resulted in an overflow.

### Steps To Reproduce

Unknown

### Requirements

- Resolve crash

### Files Version

v3.4.4

### Windows Version

Windows 11

### Log File

```csharp
System.Linq
Enumerable.Sum[TSource,TResult,TAccumulator] (IEnumerable`1 source, Func`2 selector)
Files.App.Views.Layouts
BaseLayoutPage.UpdateSelectionSize ()
Files.App.Views.Shells
BaseShellPage.FilesystemViewModel_DirectoryInfoUpdated (Object sender, EventArgs e)
System.Threading.Tasks.Task
<>c.<ThrowAsync>b__128_0 (Object state)
WinRT
ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0 (Int32 hr)
ABI.Windows.ApplicationModel.Core
IUnhandledErrorMethods.Propagate (IObjectReference _obj)
Microsoft.AppCenter.Utils
ApplicationLifecycleHelperWinUI.<ctor>b__0_3 (Object sender, UnhandledErrorDetectedEventArgs eventArgs)
```

**Comment by hishitetsu** [comment]
Does that mean the total file size exceeded 9 EB (9,000,000 TB)? Is that possible under normal use?

**Comment by yaira2** [comment]
I don't really know

**Comment by yaira2** [comment]
@hishitetsu I linked the report from Sentry but it doesn't really offer anything more than what we have here.

**Comment by hishitetsu** [comment]
The only difference is the advice given by the AI, which only states the obvious lol
