### ISSUE TITLE
Code Quality: Generative resource management using Source Generator

### ISSUE THREAD

**Issue by 0x5bfa** [files-community/Files#15504]
### Description

Instead of pasting raw string code of resources let’s have a source generator to use properties. The source generator will update the class right after resw file changed.

### Concerned code

None. Making new robust code.

### Gains

- Robustness

### Requirements

App.Strings.Strings partial class.

If comments start with `GENERIC` or something we can apart the class into Strings.Generic, Strings.Infecrectable, Strings.Settings, etc. this is just in my mind and not official proposal tho.

Here’s code:
```c#
// Strings.Inflectsble.cs
/// <auto-generated/>
public partial class Strings
{
    /// <summary>
    /// (generated comments from resw here)
    /// </summary>
    public string AddNewItem
        => “Add new items”;
}
``` 

```c#
Strings.AddNewItems.GetLocalized(itemCount);
```

If we want to make localization methods simplify, let's make Strings.Extension class file as partial.

```cs
// Strings.Extension.cs
[MarkupExtensionReturnType(ReturnType = typeof(string))]
public partial class Strings : MarkupExtension
{
    public string Name { get; set; }

    protected override object ProvideValue()
        => GetType().GetProperty(Name)?.GetValue(this);
}
```

**Comment by 0x5bfa** [comment]
No one reacts…

@XTorLukas fyi

**Comment by 0x5bfa** [comment]
If there’s slash the SG avoids to generate it, since we’re in a long term to reduce number of strings that contains it.

**Comment by XTorLukas** [comment]
Yes I agree that a plain RAW string is not quite suitable for finding errors and editing later. I would also omit the slash. But splitting would be useful e.g. Strings.KeyDelDescription.GetLocalized() --> Key: "Key.Del.Description" Value: "Del". Possible splitting according to a predefined parser that replaces 'Key' with 'Key.' ... This would not use a slash in user space but in the background of the code

**Comment by XTorLukas** [comment]
Generating a class using resx would certainly be useful, but creating it would not be trivial and the subsequent implementation would have to be on the git side. If you dare, I can possibly help you with creating a parser and implementing it in the project

**Comment by 0x5bfa** [comment]
Then replace it with underscore.

**Comment by 0x5bfa** [comment]
> Generating a class using resx would certainly be useful, but creating it would not be trivial and the subsequent implementation would have to be on the git side. If you dare, I can possibly help you with creating a parser and implementing it in the project

I guess Source Generator has features specifically for this kind of use case. CsWin32 uses it.

**Comment by XTorLukas** [comment]
> > Generating a class using resx would certainly be useful, but creating it would not be trivial and the subsequent implementation would have to be on the git side. If you dare, I can possibly help you with creating a parser and implementing it in the project
> 
> I guess Source Generator has features specifically for this kind of use case. CsWin32 uses it.

Unfortunately I don't know this, I haven't worked with this tool yet

**Comment by 0x5bfa** [comment]
Oh ok!

@yaira2 what do you think?
Like CsWin32 does we can generate string properties right after rests changed.

**Comment by XTorLukas** [comment]
> Then replace it with underscore.



> Then replace it with underscore.

Maybe, switch to '_', is OK.

**Comment by XTorLukas** [comment]
@0x5bfa I had an idea of how values could be approached.

### Type for keys
This would make it possible to group common keys
```csharp
 public class StringsStandartBase(string key)
 {
     public string Key => key;
     public string Localized(params object[] pairs) => StringsResourceLocalized.GetLocalized(Key, pairs);
 }

 public class StringsExtendedBase(string key, string title, string description) : StringsStandartBase(key)
 {
     public StringsStandartBase Title => new(title);
     public StringsStandartBase Description => new(description);
 }
```

### Strings
```csharp
// Strings.Inflectsble.cs
/// <auto-generated/>
public partial class Strings
{
    /// <summary>
    /// (generated comments from resw here)
    /// </summary>
    public static StringsStandartBase AddItem => new("AddItemKey");
    ...
    /// <summary>
    /// (generated comments from resw here)
    /// </summary>
    public static StringsExtendedBase ActionAddItem => new("AddItem", "AddItem_Title", "AddItem_Description");
    ...
}
```

### Use in code
```csharp
Strings.AddItem.Localized(itemCount);
Strings.ActionAddItem.Localized(itemCount);
Strings.ActionAddItem.Title.Localized(itemCount);
Strings.ActionAddItem.Description.Localized(itemCount);
```
What do you think of this concept? It seemed like a faster solution that would allow access by group.

----
Also, it would be good to somehow solve how many values can be used after the placeholders for the format, i.e. {0, number} {1, number} ,, then 2x must be used i.e. `Localized(itemCount1, itemCount2)`. If used incorrectly, this now raises an Exception which is ignored and the result is then string.Empty.

**Comment by 0x5bfa** [comment]
You sure this is faster? It looks promising and richer but I’m not against that idea. If @yaira2 thinks it’s good we can move forward with my concept.

**Comment by XTorLukas** [comment]
This is faster because all common keys are grouped under one object. I also thought of using ReadOnlySpan<char> instead of string, but then we would have to use ref struct instead of class This speeds up access to data

**Comment by 0x5bfa** [comment]
By the way tree yaml supported in Crowdin?
And comments too?

**Comment by XTorLukas** [comment]
yes it supports both
![image](https://github.com/files-community/Files/assets/84145589/a20fd000-37a5-4828-8316-288861123385)
![image](https://github.com/files-community/Files/assets/84145589/fb05bd2d-4063-4524-baaa-e89c6e43d971)

**Comment by 0x5bfa** [comment]
Wow!!
Comments can be place right above of the resource?

**Comment by XTorLukas** [comment]
> Wow!! Comments can be place right above of the resource?

Also why not, just they must always be written without the space e.i. "#Comments"

**Comment by XTorLukas** [comment]
I did a complex migration from RESW to YML, here I placed all comments above the values by default https://github.com/XTorLukas/Files/tree/xtorlukas/TestImplementYamlResourceManager/src/Files.App.Resources/Strings

**Comment by XTorLukas** [comment]
## My idea would be this:

### Structure for key string holder
```cs
public ref struct StringsStandartBase
{
    public required ReadOnlySpan<char> Key { get; init; }

    public static implicit operator StringsStandartBase(string key)
        => new() { Key = key };
}
```

### Structure for key string holder with specified properties
```cs
public ref struct StringsActionBase
{
    public readonly required StringsStandartBase Title { get; init; }
    public readonly required StringsStandartBase Description { get; init; }

    public static implicit operator StringsActionBase((string title, string description) keys)
        => new() { Title = keys.title, Description = keys.description };
}
```

### Extensions for Unicode formatter
```cs
public static class StringsExtensions
{
    public static string ToLocalized(this StringsStandartBase keyValue, params object[] pairs) => string.Empty;
}
```

### AutoGenerated class
```cs
public partial class Strings
{
    public static StringsStandartBase AddItem => "AddItemKey";
    public static StringsActionBase ActionAddItem => ("Title", "Description");

    public static StringsStandartBase SpecKey => "SpecKey";
}
```

### Use in code
```cs
 string value;
 value = Strings.ActionAddItem.Title.ToLocalized();
 value = Strings.ActionAddItem.Description.ToLocalized();
 value = Strings.AddItem.ToLocalized();
```

**Comment by 0x5bfa** [comment]
> This is faster because all common keys are grouped under one object.

I mean, wouldn’t it too rich for strings to instance a class just for strings? In my opinion, string types sufficiently well do.

**Comment by 0x5bfa** [comment]
@yaira2 i guess I can close this

**Comment by XTorLukas** [comment]
> @yaira2 i guess we can close this

I agree, that's already been resolved.

**Comment by yaira2** [comment]
@XTorLukas thank you for all your work on this!
