### ISSUE TITLE
Desktop Pin to Sidebar Pin Incorrect Folder

### ISSUE THREAD

**Issue by JDCNS** [files-community/Files#15516]
### Description

If you sync your Desktop folder with OneDrive, pinning the Desktop folder to the sidebar still chooses C:\User\<username>\Desktop in spite of it being redirected.

### Steps To Reproduce

Open OneDrive folder, right click on Desktop, choose Pin to Sidebar. Click on the pin, and it takes you to the old location under C:\Users\<username> instead of C:\Users\<username>\OneDrive.

### Requirements

Pins correct folder

### Files Version

3.4.1.0

### Windows Version

10.0.22635.3061

### Log File

[debug.log](https://github.com/files-community/Files/files/15505130/debug.log)

**Comment by yaira2** [comment]
I can't repro this issue on my side

Can you check what happens if you pin the folder from File Explorer and come back to Files?

**Comment by tanczosm** [comment]
Same thing happens to me..  exactly as described.

**Comment by yaira2** [comment]
@tanczosm Can you check what happens if you pin the folder from File Explorer and come back to Files?
