### ISSUE TITLE
ADD SUPPORT FOR MORE PROGRAMS ON THE CONTEXT MENU

### ISSUE THREAD

**Issue by ebh5e4bh5** [files-community/Files#15513]
### What feature or improvement do you think would benefit Files?

SUPPORT FOR MORE PROGRAMS INTEGRATIONS ON THE CONTEXT MENU

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.4.1.0

### Windows Version

10.0.19045.4474

**Comment by Josh65-2201** [comment]
Thanks for the feedback, What do you mean by more? Files already has support for other programs adding items to the context menu.

**Comment by 0x5bfa** [comment]
You mean like Windows 11 context menu? We have a similar request on it.

**Comment by yaira2** [comment]
@ebh5e4bh5 you can access the shell extensions from the "Show more options" menu. If this isn't what you're referring to, please let us know and we'll try to help.
![image](https://github.com/files-community/Files/assets/39923744/e128538e-ed64-4432-bb57-f157c2cc867a)

**Comment by ebh5e4bh5** [comment]
There are some programs and tweaks that are unsupported by files, for example: iobit unlocker, iobit uninstaller, and take ownership(regedit tweak,  just look it up on youtube, I cant send the file here), on top of that there are many complaints about your program malfunctioning, including mine( when I search for the take ownership regedit file it doesnt take me to the file, only to where is file is located and on top of that the software blinks twice and lags),  just review them on the comment section of youtube videos regarding your software, I will send one as an example. 

https://www.youtube.com/watch?v=KWYzcc1f71Y > 

[@afcreative-id]
1 month ago
Between likes and dislikes, because the longer you use it the slower it becomes, what's more, it's not well integrated with USB Phone Storage, it doesn't show a visual bar of how much storage is used, the file transfer system doesn't have a separate window like the default, but like the download system in browser so I can't see that progress in the taskbar. I think there should be an option to turn off the git feature too, I don't think there is a need for it, neither does the cloud or sync system, I don't use that either.

[@Samer_Design]
3 months ago
cool but hellllllllla alot of lag loading and been in this case for looooooong time , so sadly its nono for me

[@martsum398]
3 months ago
Been using it for a while. It's good as a file picker/browser. Sucks for anything too intense like a ton of sub-folders, or moving stuff in general. Copy/paste too... it's very iffy.


[@syatek]
a month ago
is it possible to make File Explorer a true OLED black theme?


[@truepeter]
2 weeks ago
Greetings from Moscow  <3
I am a developer with ten years of experience, and i was looking for something similar, and the first thing I came across was your project. I've been using it for a few days.
I really liked everything, except that in many moments it is much slower than the default explorer, and sometimes crashes, and after intensive work it starts to take up a lot of space in RAM (400-1000 mb).
My setup: X670E, Ryzen 9 7950X, RTX 4070 Ti, DDR5-6000, SSD RAID-0 10gb/s 

I hope you fix this and kick Microsoft's ass.
I have subscribed to you everywhere, and later, perhaps, I will be able to participate in your wonderful business.

[@speel1959]
3 months ago
I was just met with the error 'The remote procedure call failed' after installation.

[@SIN-kq2nj
3 months ago
Amazes me, after so many years and apps that the "large" thumbnail preview for these apps are still small. With larger screens and ultrawides there really is no excuse. I installed it to see if the thumbnails were larger, they weren't. So I'm going to remove.

Thanks for your work and hopefully you are able to fix these issues, if these issues are solved I will start supporting the development.

**Comment by yaira2** [comment]
Provided that these applications incorporate shell extensions, they will be displayed in the context menu. This approach is recognized as the conventional method for integrating additional functionalities into Windows file managers.

If for whatever reason these shell extensions are implemented and there is an incompatibility with Files, please let us know the details and we'll try to investigate. In most cases, however, shell extensions work out of the box without any additional changes on our end.

**Comment by ebh5e4bh5** [comment]
As mentioned before, these shell extensions are incompatible with files, why was my previous comment edited?

**Comment by yaira2** [comment]
I trimmed the comment to keep this thread on topic

**Comment by yaira2** [comment]
Can you clarify if those shell extensions are displayed in the "Show more options" menu?

**Comment by ebh5e4bh5** [comment]
They arent, actually I just found out right now the take ownership option is only displayed upon clicking on an exe file, if I right click on a folder and hover the mouse on show more options, it wont appear.

**Comment by ebh5e4bh5** [comment]
did you take notes of all these complaints I pasted here? The files also keeps blinking and lagging after right clicking on open file location of programs, etc..

**Comment by Josh65-2201** [comment]
The other issues you posted are already possible in Files or have there own issue tracking them.

**Comment by 0x5bfa** [comment]
Taking notes 😳 🗒️

**Comment by ebh5e4bh5** [comment]
Just a correction, the blinking part was actually the other folder paths and stuff previously left opened loading because I disabled the option to run on the background I think, but its still laggy briefly after opening the software, do I get priority for complaiunts and feature requests if I donate?

**Comment by Josh65-2201** [comment]
There is no priority system. There slow browsing performance is currently limited mostly from Microsoft with WinUI and WinAppSDK, so it will just take longer to get right.

**Comment by ebh5e4bh5** [comment]
So here is a suggestion for your team in order to increase revenue for the software development, give priority and/or more benefits for those that donate(especially on a monthly basis) or have paid for the app, you need to offer some sort of benefit for these people as incentivization for more people to support its development, and to answer your doubts, yes these options do appear in the context menu of the default windows file explorer, for all folders and files.

**Comment by ebh5e4bh5** [comment]
I´d say monthly based subscriptions with the most expensive having the option to chose from the default amount to a any higher amount is the most appropriate rather than just paying once for the software, and for those that are unable to pay, they will use the experimental version, to test new features and give out their suggestions and complaints, you might give them a 1 month trial on the stable version though.

**Comment by ebh5e4bh5** [comment]
You can download the softwares and regedit tweak I mentioned and test it out, but from my end I can say only the take ownership option appears for .exe dll dat txt files but not for folders, I also have  avast antivirus downloaded and its image isnt showing on its option on the context menu.

**Comment by ebh5e4bh5** [comment]
Please confirm to me if these issues have been taken note of, otherwise I will have to open a new thread.

**Comment by yaira2** [comment]
Thank you for your feedback, we've taken note of your suggestions.
