### ISSUE TITLE
BUGS 

### ISSUE THREAD

**Issue by ebh5e4bh5** [files-community/Files#15519]
### Description

BUGS:
files is not opened when I click to search for a file to export to my browser from my browser(google chrome latest stable version)

its been very laggy(sometimes it takes awhile to be able to move the window after its minimized)

Some programs are unsupported by the software context menu. (iobit unlocker and iobit uninstaller as far as im aware of)

Avast antivirus does not show its image on its option on the context menu

the regedit tweak to take ownership of files and folders is not displayed on the context menu upon clicking on folders
only on files.

Here are other suggestions from people on the comment section of a youtube video regarding files:

https://www.youtube.com/watch?v=KWYzcc1f71Y > 

[@afcreative-id]
1 month ago
Between likes and dislikes, because the longer you use it the slower it becomes, what's more, it's not well integrated with USB Phone Storage, it doesn't show a visual bar of how much storage is used, the file transfer system doesn't have a separate window like the default, but like the download system in browser so I can't see that progress in the taskbar. I think there should be an option to turn off the git feature too, I don't think there is a need for it, neither does the cloud or sync system, I don't use that either.

[@Samer_Design]
3 months ago
cool but hellllllllla alot of lag loading and been in this case for looooooong time , so sadly its nono for me

[@martsum398]
3 months ago
Been using it for a while. It's good as a file picker/browser. Sucks for anything too intense like a ton of sub-folders, or moving stuff in general. Copy/paste too... it's very iffy.

[@syatek]
a month ago
is it possible to make File Explorer a true OLED black theme?

[@truepeter]
2 weeks ago
Greetings from Moscow  <3
I am a developer with ten years of experience, and i was looking for something similar, and the first thing I came across was your project. I've been using it for a few days.
I really liked everything, except that in many moments it is much slower than the default explorer, and sometimes crashes, and after intensive work it starts to take up a lot of space in RAM (400-1000 mb).
My setup: X670E, Ryzen 9 7950X, RTX 4070 Ti, DDR5-6000, SSD RAID-0 10gb/s 
I hope you fix this and kick Microsoft's ass.
I have subscribed to you everywhere, and later, perhaps, I will be able to participate in your wonderful business.

[@speel1959]
3 months ago
I was just met with the error 'The remote procedure call failed' after installation.

[@SIN-kq2nj
3 months ago
Amazes me, after so many years and apps that the "large" thumbnail preview for these apps are still small. With larger screens and ultrawides there really is no excuse. I installed it to see if the thumbnails were larger, they weren't. So I'm going to remove.

mine:
I´d say monthly based subscriptions with the most expensive having the option to chose from the default amount to a any higher amount is the most appropriate rather than just paying once for the software, and for those that are unable to pay, they will use the experimental version, to test new features and give out their suggestions and complaints, you might give them a 1 month trial on the stable version though. You can also give the option to donate once apart from the monthly subscriptions.

### Steps To Reproduce

its been mentioned already

### Requirements

- e.g. Fix crash that occurs when...
its been mentioned already

### Files Version

3.4.1.0

### Windows Version

10.0.19045.4474

### Log File

[debug.log](https://github.com/user-attachments/files/15507178/debug.log)

**Comment by yaira2** [comment]
We greatly appreciate your feedback. To maintain clarity and efficiency, we track each bug report as an individual issue, which allows us to follow precise steps for reproduction.

The context menu concern you’ve raised is currently monitored under issue #15513. We will reopen this issue once we have delineated the necessary steps to replicate the problem.

In anticipation of detailed reports for each distinct item, I will be closing this issue. Thank you for your understanding and cooperation.
