### ISSUE TITLE
Shut Down

### ISSUE THREAD

**Issue by jbinnings** [files-community/Files#15511]
### Description

Was looking at files in a folder and the App just shut down.

### Steps To Reproduce

Not Sure

### Requirements

App just shut down unexpectedly

### Files Version

3.4.1.0

### Windows Version

11 Pro

### Log File

[debug.log](https://github.com/files-community/Files/files/15503766/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by yaira2** [comment]
I don't see anything in the log file but if it happens again in the preview version, please let us know and we can try to locate the crash via Sentry.
