### ISSUE TITLE
Bug: Can't edit contents of a zip archive

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#15518]
### Description

*

### Steps To Reproduce

1. Create or download zip file with contents
2. Attempt to delete one of the contents

### Requirements

- Fix deleting archive contents

### Files Version

3.4.4.0

### Windows Version

10.0.22621.3593

### Log File

[debug.log](https://github.com/user-attachments/files/15506221/debug.log)

**Comment by yaira2** [comment]
Is this new to preview?

**Comment by Josh65-2201** [comment]
No, but the permanently delete dialog shows in 3.4.1.0 where it doesn't in 3.4.4.0
