### ISSUE TITLE
【小优化 Minor optimizations】让硬盘或移动硬盘的属性界面相统一。Unify the properties interface of a hard disk or portable hard drive.

### ISSUE THREAD

**Issue by AnnualfireCHW** [files-community/Files#15526]
### What feature or improvement do you think would benefit Files?

统一成相同的界面。可以让程序的外观变得使人清晰易懂。Unified into the same interface. It can make the appearance of the program clear and easy to understand.
我注意到磁盘属性，有这两个界面。分别是主页时打开的界面和此电脑时打开的界面。很多用户习惯在桌面打开此电脑。
![image](https://github.com/files-community/Files/assets/121853113/fa7d5ac5-d32b-4311-9f3b-7dcf79139367)
【此电脑时】 ||  【On this computer】
![屏幕截图 2024-06-01 212608](https://github.com/files-community/Files/assets/121853113/8d6f17ca-0e4b-4573-8a96-e1c744e09771)
【在主页时】（个人认为最清晰易懂的界面）|| [On the homepage] (I personally think the clearest and most understandable interface)
可以将第一个界面统一成第2种。给用户带来更好的体验。It is possible to unify the first interface into the second type. Bring a better experience to users.

### Requirements

It is possible to unify the first interface into the second type. Bring a better experience to users.

### Files Version

3.4.1.0

### Windows Version

10.0.22631.3593

**Comment by 0x5bfa** [comment]
Thank you for the feedback!
We’re planning to introduce a single backend interface for properties, but it’ll take much time to get it done.

For the future reference, we’ll track this on in #4180.

**Comment by AnnualfireCHW** [comment]
> 感谢您的反馈！我们计划为属性引入一个单一的后端界面，但需要很长时间才能完成。
> 
> 为了将来参考，我们将在 #4180 中对此进行跟踪。
Do you mean that the problem I mentioned will be addressed in the link number you quoted?

**Comment by 0x5bfa** [comment]
Yep

**Comment by AnnualfireCHW** [comment]
> 是的。这实际上造成了内部麻烦，因此我们将其添加到待办事项中。

虽然上一次也是你关闭了我的问题。真让人感到不爽，但问题得到解决是让人心满意足的。
Although last time you also closed my issue. It's frustrating, but it's satisfying to have the problem solved. Have a nice weekend.:)
