### ISSUE TITLE
Cut Paste Files Crashed

### ISSUE THREAD

**Issue by jpnolanjr** [files-community/Files#15529]
### Description

I was cutting 2 files from one subdir and opened another subdir to paste them and Files crashed

### Steps To Reproduce

1. Open a SubDir
2. Select all files with dropdown box on tool line, 5th from the right
3. Select Cut from the tool line 2nd from the left
4. Go up to parent directory
5. Open a different SubDir
6. Select Paste from Tool Line 4th from the left

### Requirements

- This is a valid sequence of commands, the 2 files that were Cut from the First SubDir, should have been pasted in the Second SubDir without Files Crashing (as happened the 2nd time I tried it).

### Files Version

3.4.1.0

### Windows Version

10.0.19045.4412

### Log File

[debug.log](https://github.com/user-attachments/files/15524419/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by jpnolanjr** [comment]
I have not seen a reoccurrence of this problem.

**Comment by Josh65-2201** [comment]
Thanks for checking
