### ISSUE TITLE
File 3.4 the provided package name does not match the expected package

### ISSUE THREAD

**Issue by TonyCannon** [files-community/Files#15521]
### Description

When updating from Files 3.2.3 to 3.4.1 I downloaded the classic installer and ran it and got this message. This has happened with each of the previous updates I have tried. Help please!

### Steps To Reproduce

Download classic installer for Files 3.4.1.0
Run the files-stable exe file
I get this error message

### Requirements

Download classic installer for Files 3.4.1.0
Run the files-stable exe file
I get this error message

### Files Version

3.4.1.0

### Windows Version

Windows 11 Home 22631.3672

### Log File

Unknown

**Comment by yaira2** [comment]
@TonyCannon a onetime uninstall & reinstall is required to update from v3.2.3. Please see here for more details https://files.community/docs/install#:~:text=Steps%20required%20for%20the%20%E2%80%9Cclassic%20installer%E2%80%9D%20version%20after%203/21/2024.

**Comment by TonyCannon** [comment]
Thanks so much. I’ve never seen that error before! Tony
