### ISSUE TITLE
Feature: Add modern UI for formatting disk dialog

### ISSUE THREAD

**Issue by AnnualfireCHW** [files-community/Files#15525]
### What feature or improvement do you think would benefit Files?

为程序添加新的UI。Add a new UI to the program.
![image](https://github.com/files-community/Files/assets/121853113/0d191be4-fb4c-456e-975e-08216c45c873)
旧版本的UI，实在不堪入目。The old version of the UI is really unsightly.

### Requirements

应该将格式化磁盘的UI与程序相统一，而不是使用Windows的旧版UI
The UI for formatting the disk should be unified with the program instead of using the legacy UI of Windows

### Files Version

3.4.1.0

### Windows Version

10.0.22631.3593

**Comment by 0x5bfa** [comment]
@yaira2 If you agree upon this, I'll try to find APIs.

**Comment by yaira2** [comment]
I would prefer to see what Microsoft does in this area. In truth, disk formatting is a separate tool and might be beyond the scope of what we do in Files.

**Comment by 0x5bfa** [comment]
This dialog is in Shell32 and use low layer APIs and so I’m actually interested in. It looks like the actual API (FormatEx) is not fully documented but we can get its procedure via GetProcAddress.
It’s pretty low priority tho.

**Comment by 0x5bfa** [comment]
@yaira2 if we don't plan, will we close this?
My suggestion is just implement the dialog and run a command called 'format' or 'diskpart' in command prompt. Admin prompt might come up.

**Comment by yaira2** [comment]
This needs further discussion

**Comment by AnnualfireCHW** [comment]
看起来我的问题最后又会被搁置并且关闭。可能还会给我附送上一句“由于技术原因，我们做不了”。与其这样，我不如提前关闭此题。:(
Looks like my issue will end up being shelved and closed again. I may also be given a sentence saying "We can't do it for technical reasons". Rather than that, I might as well close this question early. :(

**Comment by 0x5bfa** [comment]
@AnnualfireCHW This is feasible definitely.
However, what we concern is whether it worth re-creating on our own and this is in Files app's scope.

**Comment by AnnualfireCHW** [comment]
> 这绝对是可行的。但是，我们关心的是它是否值得我们自己重新创建，这在文件应用程序的范围内。

以我的看法，我认为如果可行。那么这实现是很有必要的。因为我认为这个应用的初衷就是改写资源管理器中某些很不好看的地方，统一系统的界面。我认为这个应用很多方面做得已经很好了，虽然还是会有一些偶发性的问题。但是界面统一是值得称赞的。具体怎么做，还是要看你们。
In my opinion, I think this implementation is necessary if it is feasible. Because I think the original intention of this app was to rewrite some of the most unsightly aspects of Explorer, the unified interface. I think the app has done a good job in many ways, although there are still some occasional issues. But the interface uniformity is commendable. It's up to you exactly how to do it.

**Comment by AnnualfireCHW** [comment]
If a small change or a small interface update can unify the entire interface and improve the user experience. Isn't that a good thing?
Of course, I need to emphasize that the decision is in your hands, and if you feel that my opinion is useless, then you can do the same. After all, I'm just giving opinions. There is no right to decision-making.

**Comment by AnnualfireCHW** [comment]
> @AnnualfireCHW This is feasible definitely.
> However, what we concern is whether it worth re-creating on our own and this is in Files app's scope.

OK，I have given a specific reply, check it out

**Comment by 0x5bfa** [comment]
> Isn't that a good thing?

Putting aside good or not, we are not sure this is in scope of our work. As redesigning is unlimited, we have to decide the boundaries. But in my opinion, it might be a good idea.

Here's my concept.

![image](https://github.com/files-community/Files/assets/62196528/b8ea2fda-a737-4ccb-a046-ef89dff5d0a9)

**Comment by mdtauk** [comment]
We tend to decide to do our own UI for existing functionality, when we can add value and or offer a different way to do things.

The more things Files decides to do, the bigger the code base gets, and the more issues can crop up.

Right now, we are not sure what value or functionality we would be adding on top of the current experience, but we may decide in the future to implement it

**Comment by 0x5bfa** [comment]
if we can format Dev drive, it would be nice because that format setting is in deep inside of Windows Settings.

**Comment by AnnualfireCHW** [comment]
> > 这不是一件好事吗？
> 
> 撇开好与坏不谈，我们不确定这是否在我们的工作范围内。由于重新设计是无限的，我们必须决定边界。但在我看来，这可能是个好主意。
> 
> 这是我的概念。
> 
> ![图像](https://private-user-images.githubusercontent.com/62196528/341977015-b8ea2fda-a737-4ccb-a046-ef89dff5d0a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNjkxMDAsIm5iZiI6MTcxOTA2ODgwMCwicGF0aCI6Ii82MjE5NjUyOC8zNDE5NzcwMTUtYjhlYTJmZGEtYTczNy00Y2NiLWEwNDYtZWY4OWRmZjVkMGE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDE1MDY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4Yzg1MDRlMWIwYjZhNjk5ODAxMzU0ODlhYzc1OWJjZTc3OTM2Y2FhMmQzMDg4NzllMWZlZWI4Y2MwMGM1MTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WoeaJ3KVH00IxywInFa1Vh1T_1WMoiULJXm0_Mq8rns)

我觉得你提出的概念图设计方案很不错，这正是我想象中的样子，确定边界是有必要的，但我认为格式化是比较常用的功能还是应该重新设计的，毕竟微软的格式化UI也是个测试版，一直用了几十年。
能像你所说提供一个新UI界面，这是无与伦比的。
I think your concept art design is very good, which is exactly what I imagined it to be, and it is necessary to determine the boundaries, but I think formatting is a more common feature or should be redesigned, after all, Microsoft's formatting UI is also a beta version and has been used for decades.
It's great to be able to provide a new UI like you said

**Comment by AnnualfireCHW** [comment]
> 我们倾向于决定为现有功能做我们自己的 UI，当我们可以增加价值和/或提供不同的做事方式时。
> 
> Files 决定做的事情越多，代码库就越大，出现的问题就越多。
> 
> 目前，我们不确定将在当前体验的基础上添加什么价值或功能，但我们可能会决定在未来实现它

我能理解你的担忧，一个程序能做的东西越多，往往就意味着潜在的问题会更多，但是这是任何一个不断更新的程序都无法避免的，我明白在尽可能缩减不必要的功能，但格式化是一个比较常用的功能，至少在主页它位于右键菜单上，如果能重新设计它，就可以让我们的界面更统一，这是一件好事情
I can understand your concern, the more things a program can do, it often means more potential problems, but this is something that is unavoidable with any program that is constantly updated, I understand the need to reduce unnecessary features as much as possible, but formatting is a more commonly used feature, at least on the context menu of the home page, if we can redesign it, it can make our interface more uniform, which is a good thing

**Comment by yaira2** [comment]
> 看起来我的问题最后又会被搁置并且关闭。可能还会给我附送上一句“由于技术原因，我们做不了”。与其这样，我不如提前关闭此题。:( Looks like my issue will end up being shelved and closed again. I may also be given a sentence saying "We can't do it for technical reasons". Rather than that, I might as well close this question early. :(

@AnnualfireCHW we haven't decided one way or the other yet, I'd like to see what Microsoft does in this area before deciding.
