### ISSUE TITLE
Please add a subfolder search function

### ISSUE THREAD

**Issue by INNNNNY** [files-community/Files#15523]
### What feature or improvement do you think would benefit Files?

Hello.
I'm going to use this program for the first time today
When you search, only the top folder is exposed.
I want to search for files in subfolders, but I can't see the option.
Can I add that function?

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.4.1.0

### Windows Version

10.0.22631.3593

**Comment by 0x5bfa** [comment]
Thank you for the feedback!

Did you press Enter? It shows search result in subfolders too.

**Comment by INNNNNY** [comment]
I'm used to Windows Explorer, so I forgot to press Enter.
Thank you for your response

**Comment by 0x5bfa** [comment]
Good to hear that you solved!

FYI, in order to make shallow search easier and be one less step, we made it so.
