### ISSUE TITLE
Remove Community Toolkit notifications

### ISSUE THREAD

**Issue by heftymouse** [files-community/Files#15528]
### Description

The Tookit notifications package has been effectively replaced by WinAppSdk's app notification support. This is a dependency we can remove now.

### Concerned code

App.xaml.cs, AppLifecycleHelper, UIHelpers

### Gains

- Removes an unnecessary and outdated dependency

**Comment by heftymouse** [comment]
I currently have a PR ready for this

**Comment by yaira2** [comment]
@heftymouse thanks!
