### ISSUE TITLE
App opens a terminal on startup on systems without WSL installed

### ISSUE THREAD

**Issue by AkazaRenn** [files-community/Files#15524]
### Description

On startup, the app opens a terminal, seemingly trying to access the WSL. Since there's no WSL installed on the system, the terminal will stay there for 60 seconds before it closes itself. It might be a change of Windows 11 24H2.

<img width="854" alt="Screenshot 2024-06-01 084114" src="https://github.com/files-community/Files/assets/8340896/78a1f617-04e2-4d4a-bfb9-daff30b2d23e">

Here's my winver:
```
Edition          Windows 11 Pro
Version          24H2
Installed on     24/06/01
OS build         26100.1
```

### Steps To Reproduce

1. Install Windows 11 24H2
2. Make sure WSL is not installed
3. Start the app
4. See the error

### Requirements

The terminal should no appear on whether the systems with WSL installed or not.

### Files Version

3.4.1.0

### Windows Version

10.0.26100.1

### Log File

[debug.log](https://github.com/user-attachments/files/15521821/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, This is an issue with Windows Insider builds.
