### ISSUE TITLE
Drag and drop from Сhrome does not work

### ISSUE THREAD

**Issue by skosyrsky** [files-community/Files#15533]
### Description

When dragging and dropping links or images from chrome, the action doesn't happen.

### Steps To Reproduce

-

### Requirements

-

### Files Version

3.4.1.0

### Windows Version

10.0.19045.4412

### Log File

[debug.log](https://github.com/user-attachments/files/15525536/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #15147. You can check there or click subscribe in the right sidebar for updates.
