### ISSUE TITLE
Please add a setting  to disable tab mode

### ISSUE THREAD

**Issue by kennazeng** [files-community/Files#15547]
### What feature or improvement do you think would benefit Files?

Some people don't like to use Tab mode, or prefer multi-window mode over Tab mode, please add a setting to disable Tab mode.

### Requirements

- add a enable / disable tab mode item in settings.
- if disable tab mode, enable files open multi windows.

### Files Version

3.4.1.0

### Windows Version

 10.0.22631.3672

**Comment by 0x5bfa** [comment]
You can open folder in new window from context menu.

**Comment by Josh65-2201** [comment]
Thanks for the feedback, what reason would you need an option to turn them off? You don't have to use them and can still open a new window using the context menu or dragging a tab out.

**Comment by yaira2** [comment]
> Some people don't like to use Tab mode, or prefer multi-window mode over Tab mode, please add a setting to disable Tab mode.

Thank you for your feedback. We understand that preferences vary, and the option to disable Tab mode in favor of a multi-window experience is certainly a valid request.

We appreciate your input and want to assure you that we’re open to considering such enhancements. However, it’s important to note that the tabbed interface is deeply integrated with various elements of our app, including the toolbar and the layering of background colors. Introducing an alternative to the current design would necessitate significant changes, essentially requiring us to maintain two distinct versions of the app’s interface.

While we don't have plans to support this option right now, we will take your feedback into account as we continue to evolve the app.
