### ISSUE TITLE
It stops working and a notification appears that there is a problem that the developers have not solved

### ISSUE THREAD

**Issue by forsan97** [files-community/Files#15549]
### Description

![issue](https://github.com/files-community/Files/assets/162799617/a7cebdde-a243-4ac1-b56c-972e21ad368c)

### Steps To Reproduce

1.Run the program

### Requirements

Fix the problem of not working and continuing on the playback page

### Files Version

V 3.4.1

### Windows Version

الإصدار	Windows 10 Enterprise for Virtual Desktops ‏‏الإصدار	22H2 ‏‏تم التثبيت في	‏04/‏10/‏2021 بنية نظام التشغيل	19045.4412

### Log File

NO FILE

**Comment by 0x5bfa** [comment]
Could you do:
1. Go to `C:\Users\<USERNAME>\AppData\Local\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`
2. Paste `debug.log` here

**Comment by yaira2** [comment]
@0x5bfa the path can be different depending on the version being used.
