### ISSUE TITLE
Windows suddenly requires developer license for installation of classic installer

### ISSUE THREAD

**Issue by rklec** [files-community/Files#15546]
### Description

For me Windows Store is blocked (likely by group policy), so I cannot install the app from Windows Store. The traditional installation has worked in the past, but now fails, somehow?

### Steps To Reproduce

Download classic installer from https://files.community/download and try to install it.

![grafik](https://github.com/files-community/Files/assets/71322635/e8bc85fe-5827-4da4-a07a-1d96d8f09f22)

The same happens when I `choco upgrade` it:
```ps
> choco upgrade files -y
Chocolatey v2.2.2
Upgrading the following packages:
files
By upgrading, you accept licenses for the packages.
files is not installed. Installing...
Progress: Downloading files 3.4.1... 100%

files v3.4.1 [Approved]
files package files upgrade completed. Performing other installation steps.
ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Deployment failed with HRESULT: 0x80073CFF, Für die Installation dieser Anwendung wird eine Windows-Entwicklerlizenz oder ein sideloadfähiges System benötigt.

Fehler beim Bereitstellen des Pakets Files_3.4.1.0_neutral_split.scale-150_1y0xx7n9077q4 mit Paketursprung Unknown, da keine gültige Lizenz- oder Querladerichtlinie angewendet werden konnte. Möglicherweise ist eine Entwicklerlizenz (http://go.microsoft.com/fwlink/?LinkId=233074) oder eine Enterprise-Querladekonfiguration (http://go.microsoft.com/fwlink/?LinkId=231020) erforderlich.

NOTE: For additional information, look for [ActivityId] fb86e6ea-b1b7-000a-8510-43fcb7b1da01 in the Event Log or use the command line Get-AppPackageLog -ActivityID fb86e6ea-b1b7-000a-8510-43fcb7b1da01

The upgrade of files was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\files\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - files (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\files\tools\chocolateyinstall.ps1'.
 See log for details.
 ```

Roughly translated (with DeepL):
> Error deploying the Files_3.4.1.0_neutral_split.scale-150_1y0xx7n9077q4 package with package origin Unknown, because no valid licence or cross-loading policy could be applied. A developer licence (http://go.microsoft.com/fwlink/?LinkId=233074) or an Enterprise cross-loading configuration (http://go.microsoft.com/fwlink/?LinkId=231020) may be required.

### Requirements

- make it installable without silly Windows requirements(?) as before?

### Files Version

3.4.1.0

### Windows Version

10.0.19045.4291

### Log File

N/A

Edition	Windows 10 Enterprise
Version	22H2
Installiert am	‎******
Betriebssystembuild	19045.4291
Leistung	Windows Feature Experience Pack 1000.19056.1000.0

/cc @w0 as [apparently being the maintainer of the choco package](https://github.com/w0/au-packages/tree/master/files), although I want to stress the issue is reproducible with the official installer.

**Comment by rklec** [comment]
Happens too, wioth v3.3 apparently:;
```
> choco upgrade files --version 3.3 -y
Chocolatey v2.2.2
Upgrading the following packages:
files
By upgrading, you accept licenses for the packages.
files is not installed. Installing...
Progress: Downloading files 3.3... 100%

files v3.3.0 [Approved]
files package files upgrade completed. Performing other installation steps.
ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Deployment failed with HRESULT: 0x80073CFF, Für die Installation dieser Anwendung wird eine Windows-Entwicklerlizenz oder ein sideloadfähiges System benötigt.

Fehler beim Bereitstellen des Pakets Files_3.4.1.0_neutral_split.scale-150_1y0xx7n9077q4 mit Paketursprung Unknown, da keine gültige Lizenz- oder Querladerichtlinie angewendet werden konnte. Möglicherweise ist eine Entwicklerlizenz (http://go.microsoft.com/fwlink/?LinkId=233074) oder eine Enterprise-Querladekonfiguration (http://go.microsoft.com/fwlink/?LinkId=231020) erforderlich.

NOTE: For additional information, look for [ActivityId] fb86e6ea-b1b7-0009-4bb8-15fcb7b1da01 in the Event Log or use the command line Get-AppPackageLog -ActivityID fb86e6ea-b1b7-0009-4bb8-15fcb7b1da01

The upgrade of files was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\files\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - files (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\files\tools\chocolateyinstall.ps1'.
 See log for details.
 ```
 
 and 3.2.4:
 ```
 choco upgrade files --version 3.2.4 -y
Chocolatey v2.2.2
Upgrading the following packages:
files
By upgrading, you accept licenses for the packages.
files is not installed. Installing...
Progress: Downloading files 3.2.4... 100%

files v3.2.4 [Approved]
files package files upgrade completed. Performing other installation steps.
ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Deployment failed with HRESULT: 0x80073CFF, Für die Installation dieser Anwendung wird eine Windows-Entwicklerlizenz oder ein sideloadfähiges System benötigt.

Fehler beim Bereitstellen des Pakets Files_3.4.1.0_neutral_split.scale-150_1y0xx7n9077q4 mit Paketursprung Unknown, da keine gültige Lizenz- oder Querladerichtlinie angewendet werden konnte. Möglicherweise ist eine Entwicklerlizenz (http://go.microsoft.com/fwlink/?LinkId=233074) oder eine Enterprise-Querladekonfiguration (http://go.microsoft.com/fwlink/?LinkId=231020) erforderlich.

NOTE: For additional information, look for [ActivityId] fb86e6ea-b1b7-0007-4b12-0efcb7b1da01 in the Event Log or use the command line Get-AppPackageLog -ActivityID fb86e6ea-b1b7-0007-4b12-0efcb7b1da01

The upgrade of files was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\files\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - files (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\files\tools\chocolateyinstall.ps1'.
 See log for details.
 ```
 
 Ah the issue is apparently documented in https://files.community/docs/install#steps-required-for-the-classic-installer-version-after-3212024, though I have already (tried) reinstalling it.
 
 (Also the link [in that release here does not directly link to the URL](https://github.com/files-community/Files/releases/tag/v3.2.4), BTW.)
 
 That said, **the issue also happens for ` --version 3.2.3` now and ` --version 3.2.2`, which is really confusing... seems there is no way back.

**Comment by Josh65-2201** [comment]
Thanks for the report,
- Are you using an unofficial (like Atlas OS or ReviOS etc.) or a modified (like disabled Windows update system, removed the Microsoft store, used a debloat program/script etc.) version of Windows?
- Are you on a company controlled network or PC/laptop

**Comment by m-primo** [comment]
I think I have a similar issue

![image](https://github.com/files-community/Files/assets/44984918/735fc31b-714e-45d7-b213-6e3eeb305420)

**Comment by Josh65-2201** [comment]
That is a different issue. Please follow https://files.community/docs/install#:~:text=Steps%20required%20for%20the%20%E2%80%9Cclassic%20installer%E2%80%9D%20version%20after%203/21/2024

**Comment by rklec** [comment]
Yes, Windows Store is disabled (via group policy aka company controlled likely), that's the issue at hand. After all, that's why I use the classic installer/choco package.

**Comment by Josh65-2201** [comment]
If it's blocked by your company there isn't anything we can do, Why it work before I don't know but it possible Windows or your company updated to block it.

**Comment by BiosNod** [comment]
Developers can't build app running without licensing system and can't make offline installer? Trends of next-generation apps...

**Comment by Josh65-2201** [comment]
Licensing systems aren't new at all and if not disabled would work fine and there are offline installers
https://cdn.files.community/files/stable/Files.Package_3.4.1.0_Stable_Test/Files.Package_3.4.1.0_x64_arm64_Stable.msixbundle
https://cdn.files.community/files/stable/Files.Package_3.4.1.0_Stable_Test/Dependencies/x64/Microsoft.WindowsAppRuntime.1.5.msix

**Comment by rklec** [comment]
[`Files.Package_3.4.1.0_x64_arm64_Stable.msixbundle`](https://cdn.files.community/files/stable/Files.Package_3.4.1.0_Stable_Test/Files.Package_3.4.1.0_x64_arm64_Stable.msixbundle) does not work for me:

![grafik](https://github.com/files-community/Files/assets/71322635/81b73121-4439-4c4d-8241-63348772773a)

> Die Paketabhängigkeiten konnten von App-Installer nicht installiert werden. Fordern Sie beim Entwickler ein -Paket an.

Kinda translated (with the help of DeepL) like:
> The package dependencies could not be installed by App-Installer. Request a -package from the developer.

[`Microsoft.WindowsAppRuntime.1.5.msix`](https://cdn.files.community/files/stable/Files.Package_3.4.1.0_Stable_Test/Dependencies/x64/Microsoft.WindowsAppRuntime.1.5.msix) also does not work:

![grafik](https://github.com/files-community/Files/assets/71322635/17cb3212-0a00-48c2-bddc-3c32a98d262a)

> Fehler bei der App-Installation. Fehlermeldung: Der Bereitstellungsvorgang "Add" mit Zielvolume "C:" für das Paket "Microsoft.WindowsAppRuntime.1.5_5001.119.156.0_x64__8wekyb3d8bbwe" von " (Microsoft.WindowsAppRuntime.1.5.msix) " ist mit dem Fehler 0x8000FFFF fehlgeschlagen. Weitere Informationen zum Diagnostizieren von Problemen bei der Bereitstellung von Apps finden Sie unter "http://go.microsoft.com/fwlink/?LinkId=235160". (0x8000ffff)

Translated with DeepL:
> Error during app installation. Error message: The "Add" deployment operation with target volume "C:" for the package "Microsoft.WindowsAppRuntime.1.5_5001.119.156.0_x64__8wekyb3d8bbwe" from " (Microsoft.WindowsAppRuntime.1.5.msix) " has failed with the error 0x8000FFFF. For more information on diagnosing app deployment issues, see "http://go.microsoft.com/fwlink/?LinkId=235160". (0x8000ffff)

**Comment by Josh65-2201** [comment]
There isn't anything we can do. It would be an issue with your system or a company policy blocking the use of Windows update/Microsoft store features.

**Comment by rklec** [comment]
Thing is, the installation has worked before ([I tried (to upgrade to) the v3.2.4 of this](https://github.com/files-community/Files/releases/tag/v3.2.4) IIRC, as said.

**Comment by yaira2** [comment]
Did you try installing via PowerShell?

**Comment by rklec** [comment]
Yes, [even using the workaround suggested here](https://github.com/PowerShell/PowerShell/issues/13138#issuecomment-1820195503):
```
> & { $ProgressPreference = 'Ignore'; Import-Module Appx 3>$null }
> Add-AppxPackage -Path "...\Microsoft.WindowsAppRuntime.1.5.msix"
> Add-AppxPackage -Path "*****\Files.Package_3.4.1.0_x64_arm64_Stable.msixbundle"
Add-AppxPackage : Fehler bei Bereitstellung. HRESULT: 0x80073CFF, Für die Installation dieser Anwendung wird eine
Windows-Entwicklerlizenz oder ein sideloadfähiges System benötigt.
Fehler beim Bereitstellen des Pakets Files_3.4.1.0_neutral_split.scale-125_1y0xx7n9077q4 mit Paketursprung Unknown, da
keine gültige Lizenz- oder Querladerichtlinie angewendet werden konnte. Möglicherweise ist eine Entwicklerlizenz
(http://go.microsoft.com/fwlink/?LinkId=233074) oder eine Enterprise-Querladekonfiguration
(http://go.microsoft.com/fwlink/?LinkId=231020) erforderlich.
HINWEIS: Wenn Sie weitere Informationen wünschen, suchen Sie im Ereignisprotokoll nach [ActivityId]
a1f9852b-ceb0-0002-439b-7ba2b0ceda01, oder verwenden Sie die Befehlszeile Get-AppxLog -ActivityID
a1f9852b-ceb0-0002-439b-7ba2b0ceda01
In Zeile:1 Zeichen:1
+ Add-AppxPackage -Path "*****\Files.Package_3.4 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (*****...able.msixbundle:String) [Add-AppxPackage], Exception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand
```

Same error. As you can see installing `Microsoft.WindowsAppRuntime.1.5` this way seems to work though.

The gist seems to be:
> Error when deploying the package Files_3.4.1.0_neutral_split.scale-125_1y0xx7n9077q4 with package origin Unknown, because no valid licence or cross-loading policy could be applied.

So I guess the package is somehow not signed or signed in a different (not so much trusted?) way or something like that...
