### ISSUE TITLE
Bug: Crash when extracting a folder to a OneDrive folder (Business or personal)

### ISSUE THREAD

**Issue by CAPSLOOCK** [files-community/Files#15550]
### Description

The app crash systematically when extracting a folder from download to a folder in a OneDrive folder (personal or Business)

### Steps To Reproduce

1. Open files app
2. extract a full folder that you downloaded in a OneDrive folder
3. See the crash

### Requirements

- Fix crash that occurs when extracting a folder to a folder in OneDrive

### Files Version

3.4.4.0

### Windows Version

26120.751 (24H2)

### Log File

[debug.log](https://github.com/user-attachments/files/15566348/debug.log)

**Comment by CAPSLOOCK** [comment]
@yaira2 nope, just tested with everything being the same, it's all good

**Comment by yaira2** [comment]
> System.InvalidCastException: Unable to cast object of type 'Files.App.Utils.Storage.SystemStorageFolder' to type 'Windows.Storage.StorageFolder'.

I think this is related to the changes in #15341. @hishitetsu didn't you recently fix a similar issue?

**Comment by hishitetsu** [comment]
> @hishitetsu didn't you recently fix a similar issue?

I can't remember.

**Comment by yaira2** [comment]
@CAPSLOOCK Thank you for bringing this to our attention, a fix will be included in the next preview build.
