### ISSUE TITLE
Feature: Create a folder shortcut by dragging from the path bar

### ISSUE THREAD

**Issue by loshadki-dev** [files-community/Files#15557]
### What feature or improvement do you think would benefit Files?

This is a feature that is in windows 10/7.  It was removed in windows 11 for some evil reason.  

You simply click and drag the folder icon (at the base of the address bar) to another folder or the desktop to create a shortcut to that folder.  See the image and video below.

![image](https://github.com/files-community/Files/assets/60158760/5ab7eb37-7274-41f3-aa91-96cd7d8d4c88)

This youtube video shows how it worked in earlier versions of windows: https://www.youtube.com/watch?v=FQf2p7pbJtE

### Requirements

- See feature description above

### Files Version

3.4.1.0

### Windows Version

10.0.22631.3593

**Comment by hishitetsu** [comment]
Personally I am glad this feature is gone, because I frequently accidentally dragged the address bar and unintentionally created shortcuts.

**Comment by yaira2** [comment]
As evident by this request, there is obviously a use case for this feature. That said, when we ran our own polls on Discord (not scientific by any means), it turned out that most users weren't even aware of this feature. We were previously tracking this feature in #13086.

**Comment by yaira2** [comment]
We'll keep this issue open for some time to measure community interest. However, based on the feedback received to date, it appears that there isn’t a significant demand among the wider user base to justify the introduction of a new option.

**Comment by loshadki-dev** [comment]
Sad to hear that, but I understand you can't implement niche feature requests for individual users.  Hope the community shows some love because there isn't another easy way to create a shortcut to your current location (that I know of).  Without it you have to browse up one level, find the folder you were just in, right click and find the embedded "send to desktop" option, then you can move that desktop shortcut to the desired destination folder/quick links.

**Comment by yaira2** [comment]
The use case is definitely valid and hearing those details gives me an idea.

We offer have an "Action" to create shortcuts, and you can assign key bindings to it. Currently, this action is limited to the item selected, but we’re working on adding support for custom arguments. Once implemented, you’ll theoretically be able to set an argument like `{CurrentDirectory}` to create a shortcut to the current directory.

It's worth noting that multiple key bindings can be assigned tothe same action. With the upcoming introduction of arguments (args), you’ll have the flexibility to assign distinct args to each binding, enhancing customization.

**Comment by loshadki-dev** [comment]
Any workaround would be great for me.  Excited to see the new features as they come out.

**Comment by yaira2** [comment]
We're going to continue tracking in #15141.
