### ISSUE TITLE
Bug: Files slows to a crawl if opening a folder with lots of files (preview build)

### ISSUE THREAD

**Issue by piperun** [files-community/Files#15554]
### Description

Effectively if I open a folder that has lots of files with varying sizes (between 1kb-9GB), and the folder contains around 2000+ Files will just slow to a crawl until I close the tab with said folder.

### Steps To Reproduce

1. Open files
2. Navigate to the folder with 2000+ items
3. It'll slow to a crawl after a few seconds

### Requirements

To open the folder with minimum delay between reading/loading all the files in a folder with large amount of files.

### Files Version

3.4.5

### Windows Version

10.0.19045.4170

### Log File

[debug.log](https://github.com/user-attachments/files/15571927/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, can you check how long it takes to load `C:\Windows\System32`?

**Comment by piperun** [comment]
It's unable to load it (at you cannot interact with any file/folder).
It gets stuck at around 1645-4000 items.
![image](https://github.com/files-community/Files/assets/1145126/e43372eb-5f1c-4a0a-93ff-fb48cccbad48)

**Comment by 0x5bfa** [comment]
It seems like leaking memory.

**Comment by yaira2** [comment]
@piperun thank you for the response, can you try these two steps
1. Turn off the option to Files open in the background
2. Restart Windows

**Comment by yaira2** [comment]
Can you also confirm if you are using a Hard Drive or SSD?

**Comment by piperun** [comment]
> @piperun thank you for the response, can you try these two steps
> 
>     1. Turn off the option to Files open in the background
> 
>     2. Restart Windows

1. I've never had this option on
2. Tried it (+updated to latest version) and the same issue emerges.

> Can you also confirm if you are using a Hard Drive or SSD?

This happens on both HDD/SSD.

**Comment by yaira2** [comment]
What are your devices specs?

**Comment by piperun** [comment]
Processor	Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz, 4001 Mhz, 
32GB Ram
Nvidia GTX 980

**Comment by yaira2** [comment]
I just realized you're using the preview version. I checked the preview version and I can reproduce this issue as well.

Can you check in the stable version of Files?

**Comment by yaira2** [comment]
I traced this issue down to #15508

**Comment by piperun** [comment]
> I just realized you're using the preview version. I checked the preview version and I can reproduce this issue as well.
> 
> Can you check in the stable version of Files?

Works with no slowdown on  3.4.1

**Comment by yaira2** [comment]
Great! Thank you for helping us catch this issue in preview!

**Comment by yaira2** [comment]
@piperun this should be resolved in the latest preview build (v3.4.13).
