### ISSUE TITLE
Drag & Drop

### ISSUE THREAD

**Issue by AnNajib** [files-community/Files#15552]
### Description

When I upload files by drag it from app to Edge browser, app is Un-scrollable. I have to change to another folder and back to be able scroll again. *[NOT] sure to review the contributing guidelines and code of conduct.  I use 930MX GPU and put it to quality.

### Steps To Reproduce

1. select files
2. put it side-by-side with edge browser
3. drag files
4. put app to focus window and it can't scroll content

### Requirements

- e.g. Fix crash that occurs when...
Fix scroll feature after do drag and drop.

### Files Version

3.4.1.0

### Windows Version

10.0.19045.4474

### Log File

[debug.log](https://github.com/user-attachments/files/15567800/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download
