### ISSUE TITLE
Feature: Allow Column Resizing in Columns Layout

### ISSUE THREAD

**Issue by nicvlav** [files-community/Files#15566]
### What feature or improvement do you think would benefit Files?

A feature which would greatly improve the look and feel of Columns Layout in Files would be resizable columns. There is currently no way to see long file names without clicking the item with Info Pane visible, or right clicking the item and clicking Properties for the file. I believe this issue also affects List Layout. This feature would improve Files by giving more flexibility/customization in the main view modes and allowing more information to be shown for a better overview of a directory's contents.
![Screenshot 2024-06-07 145048](https://github.com/files-community/Files/assets/32722303/38fad385-8b97-4756-977b-c747fd0f2698)

### Requirements

- This proposal requires a resize bar on each vertical column separator line in Column Layout, which can be dragged to change column width in Column Layout. This would be similar, if not identical, to the how resizing works in Details Layout. 
- This proposal will accomplish resizable columns in Columns Layout
- This could also extend to List Layout which doesn't have a resize bar to increase the width of the visible contents.

### Files Version

3.4.1.0

### Windows Version

10.0.22631.3593

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #6534 . You can check there or click subscribe in the right sidebar for updates.
