### ISSUE TITLE
Don't use CPU in idle when a hard drive performs some work not related to Files app

### ISSUE THREAD

**Issue by BiosNod** [files-community/Files#15565]
### What feature or improvement do you think would benefit Files?

Less CPU usage in idle... Right now, the use of the processor is much larger than the classic old Windows 10 Explorer even if Files app do nothing

In some cases you can reproduce cpu usage in idle:
1. Open Files app and minimize
2. Open task manager and wait when Files will use 0% CPU
3. Don't maximize Files and run some copy or read operations using another apps like game updaters/launcher or do some massive operations using old Windows 10 explorer or copy files using SMB protocol from another PC
4. See task manager - Files App will use 10-15% CPU in idle (Ryzen 5 1600, 6 cores, 12 threads) in some cases (maybe Files app use some file system events in background?)
![изображение](https://github.com/files-community/Files/assets/16207244/ec23566f-ead5-4cd5-91c8-483439f54e37)

### Requirements

- disable FS event listeners in idle I guess (to avoid CPU usage when disk working in cases not related to Files app)

### Files Version

3.4.1.0

### Windows Version

10.0.19045.4291

**Comment by yaira2** [comment]
Thank you for your feedback, unless you're actively running a file operation, Files shouldn't use CPU on idle (and this is true even if the window is open).

**Comment by yaira2** [comment]
Thank again you for your feedback, we're working on improving performance and will continue releasing updates with this goal in mind. While we continue working on this, we'll track progress in #4180 along with other performance related issues.
