### ISSUE TITLE
Feature: Set wallpaper on all monitors

### ISSUE THREAD

**Issue by jano23** [files-community/Files#15568]
### Description

When an image is selected and the top menu option "Set as background > Desktop" only the main monitor background is changed. 
Windows File Explorer changes both monitors

### Steps To Reproduce

1. Select an image
2. On the top menu, select "Set as background > Desktop

### Requirements

Expect the background is changed on both monitors

### Files Version

3.4.1.0

### Windows Version

10.0.22635.2921

### Log File

[debug.log](https://github.com/user-attachments/files/15748375/debug.log)

**Comment by 0x5bfa** [comment]
Thank you for the feedback.
I can get it fixed soon.

Let’s get count of display monitors and set wallpaper for each.
https://github.com/files-community/Files/blob/main/src/Files.App/Utils/Global/WallpaperHelpers.cs#L22

**Comment by yaira2** [comment]
Thank you for the feedback. If this is the desired behavior, we can look into making this change.

**Comment by yaira2** [comment]
@0x5bfa this is ready to build.
