### ISSUE TITLE
Bug: Crash occurs when using Group by

### ISSUE THREAD

**Issue by xvzhenduo** [files-community/Files#15567]
### Description

app crshed when cancel group by in this view
![image](https://github.com/files-community/Files/assets/74353173/37a9ab67-89d0-40ff-97f3-a50ffe08039e)

### Steps To Reproduce

1. open any folder
2. set Group by
3. click any group titile and go into the view like this
![image](https://github.com/files-community/Files/assets/74353173/37a9ab67-89d0-40ff-97f3-a50ffe08039e)
4. cancle Goup by
5. app crashed

### Requirements

The application run normally

### Files Version

3.4.1.0

### Windows Version

10.0.26120.770

### Log File

[debug.log](https://github.com/user-attachments/files/15748190/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by xvzhenduo** [comment]
> Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

Yes,app still crash
[debug.log](https://github.com/user-attachments/files/15751377/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for checking

**Comment by yaira2** [comment]
This will be fixed in the next release
