### ISSUE TITLE
Feature: Change Display Size Names for Grid Layout

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#15569]
### What feature or improvement do you think would benefit Files?

I would like to propose an improvement regarding the display size options for items in the grid layout. I suggest changing the labels as follows:
- Tiny (instead of "small")
- Very Small (instead of "medium")
- Small (instead of "medium+")
- Slightly Small (instead of "medium++")
- Normal (instead of "medium+++")
- Slightly Large (instead of "medium++++")
- Large (instead of "medium+++++")
- Very Large (instead of "large")
- Extremely Large (instead of "large+")
- Gigantic (instead of "large++")
- Colossal (instead of "large+++")
- Enormous (instead of "very large")

This change improves the clarity and user experience by providing a more intuitive understanding of the relative sizes. Users can more easily select the display size that best fits their needs without confusion.

### Requirements

Change display size names for grid layout.

### Files Version

3.4.12.0

### Windows Version

10.0.22631.3672

**Comment by 0x5bfa** [comment]
I remember that you proposed this before in Discord.
Current ones make sense for screen recorder and avoid wording that is not able to be translated in other languages.
I think this also makes sense when using slider as @Josh65-2201 said before.

**Comment by Lukiluc29** [comment]
> I remember that you proposed this before in Discord. Current ones make sense for screen recorder and avoid wording that is not able to be translated in other languages. I think also makes sense when using slider as @Josh65-2201 said before.

I completely understand your reasoning! This is just a simple suggestion to have something more streamlined and avoid having lots of "+" signs, which I find not very aesthetically pleasing. I brought up this topic again because a friend of mine, to whom I suggested the app, frequently uses the grid layout and also mentioned that it would be nice to have words distinctly indicating each level instead of "+" signs.

**Comment by yaira2** [comment]
We value your feedback on improving the display size labels for the grid layout. While the existing labels are not ideal, they are short and simple. Currently, there are no immediate plans for changes in this area, but we remain open to future discussions on this topic

**Comment by yaira2** [comment]
It's also worth pointing out that the labels aren't relevant for most users.
