### ISSUE TITLE
Bug: MPC can't open files when using drag and drop

### ISSUE THREAD

**Issue by Prettywxs** [files-community/Files#15564]
### Description

Unable to open file as shown in the picture

### Steps To Reproduce

![1](https://github.com/files-community/Files/assets/119655402/95d4552d-ccca-4109-81e5-75b1ea996636)

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.4.1.0

### Windows Version

1000.22700.1009.0

### Log File

[debug.log](https://github.com/user-attachments/files/15741557/debug.log)

**Comment by yaira2** [comment]
@Prettywxs a fix will be included in the next update.

**Comment by yaira2** [comment]
Unfortatnetly the fix was reverted due to an unexpected issue.
