### ISSUE TITLE
Tab Group

### ISSUE THREAD

**Issue by PhilippeJust2c** [files-community/Files#15561]
### What feature or improvement do you think would benefit Files?

Hello,

It would be greatfull if you could add this feature to files : create some group on the tab with some different colors (as in microsoft edge) and the possibility to save the group and save it as favorite.

Thanks,

Philippe

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.4.1.0

### Windows Version

10.0.22635.3646

**Comment by yaira2** [comment]
Thank you for your feedback, as of now we don't plan to support grouping open tabs, but we're hoping to add support for saving tabs for later use #11900.
