### ISSUE TITLE
Files最大化后，屏幕最右上角不是关闭按钮的操作区域

### ISSUE THREAD

**Issue by Triangle-GitHub** [files-community/Files#15573]
### Description

将鼠标移到屏幕的最右上角以关闭最大化的窗口可以减少定位鼠标的时间从而提高效率；而现在最大化的Files的右上角是拖动窗口的操作区域，希望能改为关闭按钮的操作区域。

### Steps To Reproduce

1. 最大化Files窗口；
2. 将鼠标移动到屏幕右上角并单击；
3. 观察到没有执行关闭Files窗口的操作。

### Requirements

最大化Files时，将屏幕右上角改为关闭按钮的操作区域，而不是拖动窗口的。

### Files Version

3.4.12.0

### Windows Version

10.0.22631.3593

### Log File

-

**Comment by Josh65-2201** [comment]
Thanks for the feedback, the issue is caused by the WinUI framework https://github.com/microsoft/microsoft-ui-xaml/issues/8665. 
You can check there or click subscribe in the right sidebar for updates.
