### ISSUE TITLE
Drag and drop is not worked

### ISSUE THREAD

**Issue by truongan012** [files-community/Files#15576]
### Description

Drag and drop any files in Files is not worked.
Due to company policy of App Store, I've downloaded source code v3.4.1 and build the File Dev.
When it's launched, I tried to drag and drop files but it's not worked.
I can dot drag the file when holding left-click

### Steps To Reproduce

1. Open Files
2. Drag and drop any files
3. File is not dragged when holding left-button mouse
4. Then it can not be dropped when releasing left-button mouse

### Requirements

1. Open Files
2. Drag and drop any files
3. File should be dragged when holding left-button mouse
4. Then it can be dropped when releasing left-button mouse

### Files Version

3.4.1.0

### Windows Version

10.0.19043.928

### Log File

[debug.log](https://github.com/user-attachments/files/15756964/debug.log)

**Comment by truongan012** [comment]
change UAC and it's worked

**Comment by 0x5bfa** [comment]
Yeah, due to the platform limitation, we cannot support drag and drop when elevated. This issue also has in Windows Terminal because it uses the same fundamental framework. If I remember correctly, I remember they are working on fixing internally on Windows-side. @yaira2 fyi.
