### ISSUE TITLE
Available space is displayed incorrectly

### ISSUE THREAD

**Issue by Prettywxs** [files-community/Files#15570]
### Description

The capacity displayed on the disk free space does not seem to be updated in a timely manner

### Steps To Reproduce

<img width="1018" alt="Snipaste_2024-06-09_15-37-18" src="https://github.com/files-community/Files/assets/119655402/b0287054-15bf-42c5-addb-3aace0c93c7d">

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.4.1.0

### Windows Version

1000.26100.6.0

### Log File

[debug.log](https://github.com/user-attachments/files/15751046/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #6182 . You can check there or click subscribe in the right sidebar for updates.
