### ISSUE TITLE
Additional Navigation Actions

### ISSUE THREAD

**Issue by chadefranklin** [files-community/Files#15571]
### What feature or improvement do you think would benefit Files?

1. Action: Navigate to next sibling folder (the next folder within the parent directory of the current folder)
2. Action: Navigate to previous sibling folder (the previous folder within the parent directory of the current folder)

### Requirements

- This proposal will allow for more efficient navigation of folder structures

New default bindings would be required. I propose:
Ctrl+Alt+Left
Ctrl+Alt+Right

### Files Version

3.4.1

### Windows Version

Windows 10

**Comment by Josh65-2201** [comment]
Thanks for the feedback, these already exist using the Up (Alt + Up arrow) and Back actions (Alt + Left arrow)

**Comment by yaira2** [comment]
I think we're tracking a similar request for switching between sibling folders. The question with this is how do you determine the next folder? Depending on how you sort the items, the sibling folder can change.

**Comment by yaira2** [comment]
@chadefranklin
