### ISSUE TITLE
Sorting by video length

### ISSUE THREAD

**Issue by Oleksandrigo** [files-community/Files#15577]
### What feature or improvement do you think would benefit Files?

Add sorting by video length

### Requirements

Ability to sort files by video length

### Files Version

3.4.12.0

### Windows Version

11

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #8366 . You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
To expand on what Josh shared, we're planning to add support for all the columns and sorting options available in File Explorer.
