### ISSUE TITLE
Pinned folders doesn't show, restart app is required to see them

### ISSUE THREAD

**Issue by Compvictor** [files-community/Files#15591]
### Description

When restarting the pc, there are no Pinned folders, I have to finish and restart the application to see them. 

### Steps To Reproduce

1. Start the PC.
2. Open Files 

### Requirements

When opening Files, the Pinned folders should be there.

### Files Version

3.4.1.0

### Windows Version

10.0.22631.3737

### Log File

[debug.log](https://github.com/user-attachments/files/15824100/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #15410 . You can check there or click subscribe in the right sidebar for updates.
Please also try the workaround steps there.
