### ISSUE TITLE
Pinned Sidebar Blank

### ISSUE THREAD

**Issue by mitchmorgan36** [files-community/Files#15593]
### Description

After the most recent update, the "Pinned" section of the sidebar is unable to be populated. Folder locations can be right-clicked and "Pin to Sidebar" can be clicked but nothing gets added to the sidebar. The locations previously saved in the Pinned sidebar were also removed 
The Pinned section of the sidebar now has no links and is unable to be populated with any links.
![Screenshot 2024-06-14 091117](https://github.com/files-community/Files/assets/23455012/c709820d-6a50-4493-b532-1690b2898a38)

### Steps To Reproduce

1. Right click any folder
2. Select "Pin to Sidebar"

### Requirements

Restore previous Pinned Sidebar behavior.

### Files Version

3.4.13.0

### Windows Version

10.0.19045.4412

### Log File

[debug.log](https://github.com/user-attachments/files/15838537/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in https://github.com/files-community/Files/issues/15410 . You can check there or click subscribe in the right sidebar for updates.
Please also try the workaround steps there.

**Comment by mitchmorgan36** [comment]
Why was this bug report immediately marked as completed?

**Comment by Josh65-2201** [comment]
Because it the same as the one I linked

**Comment by mitchmorgan36** [comment]
Oh I didn't see that my fault. Thanks!

**Comment by yaira2** [comment]
Can you try the solutions mentioned here and let us know if they helped?
https://answers.microsoft.com/en-us/windows/forum/all/windows-11-quick-access-folders-gone-and-pin-to/49b3f66a-062f-43e6-8417-728e2a42c896
