### ISSUE TITLE
Bug: Files deleted my music by double clicking to open it

### ISSUE THREAD

**Issue by giou** [files-community/Files#15596]
### Description

The app hanged and I double clicked multiple times to open my music folder.

This is the folder deleted
F:\Users\g\Music\Soggfy\

Also, I have this enabled:
![image](https://github.com/files-community/Files/assets/5844127/d0febd37-6e2c-4945-81e9-1586a7e2562b)

### Steps To Reproduce

1. Click click
2. click click
3. click click
4. click click

### Requirements

- e.g. Fix crash that occurs when...
opening folder

### Files Version

3.4.1.0

### Windows Version

10.0.22631.3593

### Log File

[debug.log](https://github.com/user-attachments/files/15847703/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, The log doesn't show anything that would have deleted a folder.
- Are you using F drive for Windows install?
- Is the folder in the recycle bin?

**Comment by giou** [comment]
Is not in the recycle bin and windows is in C:\. I restarted the program a few times before looking at the log don't know if that has something to do with it.

**Comment by yaira2** [comment]
Opening isn't connected to deleting in any way, can you share more about how you were using Files at the time it crashed?

**Comment by yaira2** [comment]
A theory is that the item was drag and dropped by mistake but it's hard to know without any more info.

**Comment by yaira2** [comment]
I see some info in the log file but it indicates it was trying to open a file, not a folder.

**Comment by yaira2** [comment]
@files-community/files fyi

**Comment by yaira2** [comment]
```csharp
2024-06-15 14:54:14.2429|Information|System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'F:\Users\g\Music\Soggfy\11eter' with working directory 'C:\Windows\system32'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Files.App.Utils.Shell.LaunchHelper.<>c__DisplayClass3_0.<<HandleApplicationLaunch>b__0>d.MoveNext()
```

Is `11eter` a folder or file?

**Comment by 0x5bfa** [comment]
4. You sure this crashes and if you open the file is gone?
5. Could you check Windows Defender’s quarantine list

**Comment by giou** [comment]
1. Just opened it to browse for a song.
2. Is a folder for the artist
3. No way, I'm scared of losing more important data and uninstalled.
4. Is not a shared folder.

5. It crashed when I tried to open the folder of the artist, then I clicked some more and forced it to crash for the menu Windows menu that asks to close the program, closed the program, opened it again and the folder was gone.
6. Windows defender is disabled.
7. It's a mechanical drive, maybe the software crashed because I/O delay? The Files app crashed multiple times before in the same way.

**Comment by yaira2** [comment]
What happens when you try opening the folder with File Explorer?

> No way, I'm scared of losing more important data and uninstalled. (Don't have spare drives and my internet is very slow)

I understand, at the same time having a clear repro will help us investigate. If it helps, feel free to spin up a VM and test with fake data.

> Windows defender is disabled.

Do you have any other AV installed?

**Comment by yaira2** [comment]
> It's a mechanical drive, maybe the software crashed because I/O delay? The Files app crashed multiple times before in the same way.

That's an interesting theory, but I'm not sure how that can cause data loss.

**Comment by giou** [comment]
> What happens when you try opening the folder with File Explorer?
Normal behavior.
> > No way, I'm scared of losing more important data and uninstalled. (Don't have spare drives and my internet is very slow)
> 
> I understand, at the same time having a clear repro will help us investigate. If it helps, feel free to spin up a VM and test with fake data.
I've setup a VM sharing a copy of my music folder inside the same drive and couldn't replicate it, tried for 10 minutes opening folders. But it did crash.
[debugVM.log](https://github.com/user-attachments/files/15859887/debugVM.log)

> > Windows defender is disabled.
> 
> Do you have any other AV installed?
I don't.

I prior to the data loss I was using the Files app for about 1 month and in that time it crashed a lot. Maybe it has to crash in a very specific way...?
