### ISSUE TITLE
Bug: Shortcut set to run as Admin doesn't work if there are arguments

### ISSUE THREAD

**Issue by Johen8** [files-community/Files#15595]
### Description

I have a shortcut in my Desktop to connect to a local VM (using Windows vmconnect). It is set to run as administrator in the file properties and it has arguments to connect to the VM.
If I simply double click the shortcut, I get the elevation prompt, but vmconnect opens as if there were no arguments.
If I right click -> Run as administrator, it actually runs as it's supposed to be.

### Steps To Reproduce

1. Create a text file on your desktop called new1.txt
2. Create a shortcut to notepad.exe and pass the new1.txt path as argument
3. Set the shortcut to run as admin
4. If you double click the shortcut, you get the elevation prompt, but Notepad opens blank
5. If you right click -> run as administrator, it actually opens the file correctly 

![image](https://github.com/files-community/Files/assets/13229026/75fc51f0-86c5-491f-a171-e7dd8b8cd9d2)

### Requirements

Shortcuts should work as in default Windows Explorer, so if there's a shortcut to a program and it passes arguments, it should pass those arguments to the programs when you start it.

### Files Version

3.4.1

### Windows Version

23H2 Build 22631.3737

### Log File

[debug.log](https://github.com/user-attachments/files/15844592/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
This issue will be fixed in the upcoming v3.5 release.

**Comment by yaira2** [comment]
This fix ended up not being ready in time for v3.5, instead, it will be included in the v3.6 release.
