### ISSUE TITLE
Bug: Crash when opening files with two paths in command line

### ISSUE THREAD

**Issue by Mento** [files-community/Files#15597]
### Description

Files hangs and then crashes when i call it so: "files C: C:".

### Steps To Reproduce

1. Open cmd
2. Enter files C: C:
3. Press enter 

### Requirements

Files should not crash.

### Files Version

3.4.1.0

### Windows Version

10.0.22631.3737

### Log File

[debug.log](https://github.com/user-attachments/files/15848504/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.
