### ISSUE TITLE
Make powertoys peek work

### ISSUE THREAD

**Issue by DeltriDev** [files-community/Files#15598]
### What feature or improvement do you think would benefit Files?

I use the powertoys peek to quickly view files, and this app doesn't support it. Is it possible to add peek support?

### Requirements

- This proposal will accomplish powertoys peek to work in the files app

### Files Version

3.4.14.0

### Windows Version

10.0.19045.4529

**Comment by 0x5bfa** [comment]
Thanks for the feedback, this currently isn't possible due to power toys peek not having a way of doing so microsoft/PowerToys#26422

**Comment by yaira2** [comment]
To elaborate on that a bit, we'd like to add support and we have the infrastructure ready to do so, but we're dependent on PowerToys creating an API for third party apps. In the meantime, we suggest trying QuickLook or SeerPro https://files.community/docs/features/integrations.

**Comment by DeltriDev** [comment]
Thanks! I finally found a good file manager and got stuck on the peek thing
