### ISSUE TITLE
highlight the active pane with different color 

### ISSUE THREAD

**Issue by shelper** [files-community/Files#15613]
### What feature or improvement do you think would benefit Files?

i am using dual pane in files and currently the active pane is highlighted with very thin line in the bottom, this is not very noticeable, 
maybe gray out the inactive pane a little bit? and make the active pane slightly brighter?

i would also suggest to have an option to have separate address and search bars for each pane, so when i try to drag files between panes, i know the path of both sides.

### Requirements

- make the active pane among the dual pane view slightly brighter compared to the inactive pane
- provide option for each pane to have its own address and search bars in the dual pane view

### Files Version

3.4.1.0

### Windows Version

10.0.19045.4412

**Comment by yaira2** [comment]
Thank you for your feedback, we're excited to share this is already implemented in the preview version of Files and will be included in the next stable release as well.

**Comment by yaira2** [comment]
![image](https://github.com/files-community/Files/assets/39923744/5d3c153a-29ba-4b3c-8df0-02372f4ac395)
