### ISSUE TITLE
Bug: Issues with Access Denied and Folder Deletion Errors During Installation

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#15611]
### Description

I encountered an issue while downloading and installing components for Visual Studio through the Visual Studio Installer, with Files open at the same time. When I navigate to my local disk (where the installation is taking place), the local disk keeps reloading and constantly shows errors like "Access Denied" and "Did you delete this folder?" This should not happen as it makes navigation impossible during the installation.

### Steps To Reproduce

1. Start the installation of an application
2. Navigate to the disk where you are performing the installation

### Requirements

Identify why the local disk is reloading and causing "Access Denied" and "Did you delete this folder?" errors during the installation.

### Files Version

3.4.14.0

### Windows Version

10.0.22631.3737

### Log File

[debug.log](https://github.com/user-attachments/files/15871201/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Files will be refreshing because the files are being changed. Are you using column layout?

**Comment by Lukiluc29** [comment]
> Thanks for the report, Files will be refreshing because the files are being changed. Are you using column layout?

Yes, I use column layout

**Comment by Josh65-2201** [comment]
I'm guessing the folder is being select and opened. It would probably be fixed with #14011

**Comment by yaira2** [comment]
> I'm guessing the folder is being select and opened. It would probably be fixed with #14011

Agreed, let's merge the two.
