### ISSUE TITLE
Bug: Formatting Issue with Dimensions and Synchronization Labels

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#15610]
### Description

I have noticed a formatting issue with the labels "dimensions" and "synchronization" when hovering over an image. The colon is directly attached to the word "dimensions" resulting in "dimensions:" instead of "dimensions :". The same problem occurs with the "synchronization" line. To fix this, the colons should be removed from the following lines of code in the file "src/Files.App/Data/Items/ListedItem.cs" on line 49-50

```
if (!string.IsNullOrWhiteSpace(DimensionsDisplay))
    tooltipBuilder.Append($"{Environment.NewLine}{"PropertyDimensions".GetLocalizedResource()}: {DimensionsDisplay}");
if (SyncStatusUI.LoadSyncStatus)
    tooltipBuilder.Append($"{Environment.NewLine}{"syncStatusColumn/Header".GetLocalizedResource()}: {syncStatusUI.SyncStatusString}");
```

and ensure that "dimensions" and "dimensions:", as well as "status" and "status:", are properly localized.

### Steps To Reproduce

1. Hover over an image file
2. Hover over a file stored in the cloud

### Requirements

Correct the code so that the labels are formatted properly, with a space between the word and the colon.

### Files Version

3.4.14.0

### Windows Version

10.0.22631.3737

### Log File

![Capture d'écran 2024-06-17 125651](https://github.com/files-community/Files/assets/128183422/d9de06c9-7d0c-44d5-a01f-ba1fcf2bc841)

**Comment by yaira2** [comment]
There are two approaches to take here, the first is to have separate strings with and without the colons. The other approach is to have a dedicated string for colon.

**Comment by 0x5bfa** [comment]
As we have done, let's have `DimentionsWithColon`

**Comment by yaira2** [comment]
Sounds good

**Comment by 0x5bfa** [comment]
@Lukiluc29 Do you like to work on this?

**Comment by Lukiluc29** [comment]
> @Lukiluc29 Do you like to work on this?

I'm sorry, but I am unable to address this issue as I do not have a workstation to work on it.

**Comment by Lukiluc29** [comment]
If someone else is willing to take on this task, it would be greatly appreciated.

**Comment by 0x5bfa** [comment]
Sure! I'll address this issue and make sure this will be included in the next stable build!

**Comment by yaira2** [comment]
@0x5bfa if you don't mind, perhaps we can let someone else take this as it's good for a beginner.

**Comment by 0x5bfa** [comment]
Good idea! Let's leave.
