### ISSUE TITLE
Onstartup options should apply to only first instance of the app

### ISSUE THREAD

**Issue by soumyamahunt** [files-community/Files#1561]
**Is your feature request related to a problem? Please describe.**
The "OnStartup" preferences like opening specific set of pages applies to every instance of the app.

**Describe the solution you'd like**
The "OnStartup" preferences should only apply to the first instance of the app. This is default behavior from browsers and other multi-window solutions.

**Additional question**
Also, should the "open where left of" be applied to only first instance??

**Comment by Jaiganeshkumaran** [comment]
@soumyamahunt Continue where you left off hasn't been implemented yet.

**Comment by soumyamahunt** [comment]
> @soumyamahunt Continue where you left off hasn't been implemented yet.

I know, the question was when it will be implemented whether it should be for one instance or for multiple instance.

**Comment by d2dyno1** [comment]
@yaichenbaum Can you assign me?

**Comment by yaichenbaum** [comment]
@soumyamahunt Is this still an issue with v0.17?
