### ISSUE TITLE
Missing Background Process Icon

### ISSUE THREAD

**Issue by D-Maxwell** [files-community/Files#15629]
### What feature or improvement do you think would benefit Files?

When viewed from the task manager for instance, the Files process is missing an icon, thus defaulting to Windows' awful, and mainly, undifferentiable, generic one.

Having it not supply any icon whatsoever does not feel intended, nor proper. Were it to display that of the package, it would fit in a lot better as an actual app and not a bare service, whilst also showing its own identity, quickly identifiable from contrast alone.

### Requirements

I know not of any requirements that may have prevented this from ever being considered to begin with.

### Files Version

3.4.1.0

### Windows Version

10.0.19045.2788

### Comments

![image](https://github.com/files-community/Files/assets/98100481/f6c94466-b851-4429-9d2b-fab9cb3db165)
Here, the app itself has an associated icon, whereas the process does not.
![image](https://github.com/files-community/Files/assets/98100481/16ceb9b6-61cf-472d-815b-46e9d692085d)

**Comment by yaira2** [comment]
Thank you for your feedback, as far as I'm aware, this is a limitation with packaged apps and can't be supported. If someone knows otherwise, feel free to let us know and we'll reopen this issue.
