### ISSUE TITLE
Support archive formats other than ZIP

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#1562]
**Is your feature request related to a problem? Please describe.**
Not really. Although zip is universally supported, there are many other formats that offer better compression ratios and speeds. Today I need to install third-party apps just to extract these files since Microsoft doesn't provide support natively. The goal of Files UWP was always to provide a high-quality replacement for the decade-old File Explorer so we should support these file types in addition to ZIP.

**Describe the solution you'd like**
We can use the 7 zip library instead of SharpCompress: https://www.7-zip.org/sdk.html. 8 zip, a popular archiver for UWP uses this so it should be compatible. If the C# version isn't compatible, we could use the C++ version which should work since it doesn't have dependencies on .NET.

**Describe alternatives you've considered**
None.

**Comment by KAMiKAZOW** [comment]
Just FYI:

7-Zip's RAR support is based on unrar which restricts that this source must not be used to "re-create the RAR compression algorithm" and therefore not free software, ergo not compatible with Files's GPLv3. To quote from 7-Zip's License.txt:


    unRAR license restriction
    -------------------------

    The decompression engine for RAR archives was developed using source 
    code of unRAR program.
    All copyrights to original unRAR code are owned by Alexander Roshal.

    The license for original unRAR code has the following restriction:

    The unRAR sources cannot be used to re-create the RAR compression algorithm, 
    which is proprietary. Distribution of modified unRAR sources in separate form 
    or as a part of other software is permitted, provided that it is clearly
    stated in the documentation and source comments that the code may
    not be used to develop a RAR (WinRAR) compatible archiver.

One possible alternative could be https://github.com/libarchive/libarchive which is BSD-licensed and therefore completely free software. I didn't do a one to one comparison of supported formats but with ZIP, 7z, RAR, CAB, and all common TAR variants (incl. tar.gz and tar.bz2) being supported, the usual suspects are covered.

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
