### ISSUE TITLE
Original selection status of.docx file changes when it's opened

### ISSUE THREAD

**Issue by ubsshin** [files-community/Files#15633]
### Description

When "Show Hidden Items" is enabled, after opening a .docx file, the "selected file" changes from the original .docx file to a temporary file starting with ~$. Once the .docx file is closed, no files are selected.
![image](https://github.com/files-community/Files/assets/151832674/39d9561d-c621-402b-9f35-f663b39f8ad2)

### Steps To Reproduce

Ensure that "Show Hidden Items" is enabled.
Navigate to a directory containing a .docx file.
Select the "example.docx" file.
Double click the "example.docx" file to open it.
You can See "~$example.docx" is selected.
Close the .docx file and then nothing is selected.

### Requirements

Make sure that opening a file with temporary hidden files doesn't change the original selection status. Obviously, not just .docx files, but also .pptx, .xlsx, and other file formats that generate hidden temporary files will have this issue.

### Files Version

3.4.1.0

### Windows Version

10.0.22631.3737

### Log File

[debug.log](https://github.com/user-attachments/files/15912757/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #14011. You can check there or click subscribe in the right sidebar for updates.
