### ISSUE TITLE
Make the icon of libraries editable.

### ISSUE THREAD

**Issue by WindustH** [files-community/Files#15641]
### What feature or improvement do you think would benefit Files?

edit the icon more conveniently

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.4.17.0

### Windows Version

Windows 11 23H2

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #9445 . You can check there or click subscribe in the right sidebar for updates.
