### ISSUE TITLE
Files randomly crashed

### ISSUE THREAD

**Issue by MrSrc768** [files-community/Files#15644]
### Description

I was going through my vids that I recorded from my Handycam and opened the preview pane and the Files app crashed.

### Steps To Reproduce

1. open a folder where there many are .mpg files
2. click on one of them and open the preview pane
3. after some loading files crashes

### Requirements

- e.g. Fix crash that occurs when...
accessing video files in .mpg format and the video files are created by some old Sony Handycam

### Files Version

3.4.1.0

### Windows Version

10.0.22635.3790

### Log File

[debug.log](https://github.com/user-attachments/files/15936035/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by yaira2** [comment]
How large are the mpg files?

**Comment by MrSrc768** [comment]
> How large are the mpg files?

Ranging from  90MB to 1.3GB...Some are bigger
bitrate is almost 9356kbps

**Comment by yaira2** [comment]
@MrSrc768 I think this issue might be related to #14791. The good news is that I have a potential fix in the works! Please subscribe to #14791 to get notified when it’s ready for testing. Thanks for your patience!
