### ISSUE TITLE
Right Click Context Menu - return it to Windows Default

### ISSUE THREAD

**Issue by MattPolster** [files-community/Files#15646]
### What feature or improvement do you think would benefit Files?

I appreciate all the detail and passion that goes into this project cause as it stands you guys make one of the best current tab management tools for a better 'Windows Explorer' experience. That being said, the effort of customization to be unique is sometimes messy and not intuitive. A great example of this is, the right click context menu. When you go to right click anything in Files.. It's just an alien context menu that looks nothing and does not operate anything like a traditional windows experience. The same way the new Windows 11 Context Menu is convoluted and messy by making users do one more additional click to get to 'options' is a messy process, the same goes for the context menu when right clicking a file in Files. There is no need for cute icons and wrenches and weird menu items that mean nothing to me. Having uniformity to be efficient and productive is. To allow a feature to un-check the use of 'Files' Context Menu and have the traditional Windows right Click Context Menu would be a god send to those who are just trying to get stuff done, quickly and efficiently. I think this would be an awesome addition to this program / tool and make it seem serious about providing an efficient experience to the average user who's looking to boost their workflow

Cheers,
Matt

### Requirements

- This proposal will accomplish better efficiency and a welcome experience to a person who is used to the Windows Operating System
- This proposal will accomplish Uniformity, and better synergy with your tool, instead of trying to masquerade as another operating system on top of an already existing one. 
- This proposal will accomplish a cleaner look. The needless icons that are not very self explanatory are just bloat. Let the awesome Tab features work harmoniously with the rest of what Windows has to offer. Same could be said about your details/ properties feature. It doesn't have to be so different it's almost too different that it's a hassle. 

### Files Version

3.4.1.0

### Windows Version

10.0.22631.3737

### Comments

I hope this criticism helps as it isn't meant to bash the tool. It's awesome and shows amazing promise as a program that could stand out to show Microsoft what they're missing and how far out of touch they are with the things that matter.  You're really close but it could use a bit more refinement.

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Using Windows 10 context menu isn't possible as many options wouldn't work as they are build for and interact only with Windows File Explorer. It also doesn't follow the design Files uses.
You can turn off `Files settings > General > Move shell extensions into a sub menu` to make all options show like Windows 10 did and not adding extra steps. The icons on the top are also labeled when you hover over them, same base design as Windows File Explorer and stay in the same place so you can get use to it.
