### ISSUE TITLE
Code Quality: Remove INI Parser dependency

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#15650]
### Description

We currently utilize the INI Parser solely within the Adaptive Layout Helper and can easily replace with other code.

### Concerned code

Adaptive layout helper

### Gains

- Less dependencies
- More control over the code

**Comment by 0x5bfa** [comment]
Why not create a service, WindowsIniService.

```cs
public string GetValue(string section = string.Empty, string name = string.Empty);
```

If *section* is empty, returns the first item.

I found Win32 API for this but it is for 16-bit compat https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getprivateprofilestring. But worth taking a look.

**Comment by yaira2** [comment]
Something like this
```csharp
var lines = File.ReadLines(iniPath);
			var keys = lines.Select(line => line.Split('='))
								.Where(parts => parts.Length == 2)
								.ToDictionary(parts => parts[0].Trim(), parts => parts[1].Trim());
```

**Comment by 0x5bfa** [comment]
yeah but putting this in places where it needs makes you hard to maintain. Also, I like services because I plan to create Unit Tests for services in the future.

**Comment by 0x5bfa** [comment]
Can I work on?

**Comment by yaira2** [comment]
I meant that we can use that for the service.
