### ISSUE TITLE
Auto-switch to Details when no file is selected/only icon is previewed

### ISSUE THREAD

**Issue by maicol07** [files-community/Files#15656]
### What feature or improvement do you think would benefit Files?

When preview is selected in the right pane, when no file is selected the folder icon is shown or file icon is shown when file hasn't a preview provider. It's more useful to get the details of the icon instead of only showing its icon preview

### Requirements

- No requirements I think

### Files Version

3.4.1.0

### Windows Version

10.0.26120.961

**Comment by Josh65-2201** [comment]
Thanks for the feedback, If you are on the preview section of the info pane this is how it suppose to work. Other wise this should show details of the folder like normal.

**Comment by maicol07** [comment]
Yes, I know but maybe this behaviour can be changed to an autoswitch option in settings or a setting to disable preview in these cases

**Comment by yaira2** [comment]
> details of the icon instead of only showing its icon preview

Do you mean details of the file?

**Comment by maicol07** [comment]
> > details of the icon instead of only showing its icon preview
> 
> Do you mean details of the folder?

Sorry, I've missed your reply. Yes, I mean folder details

**Comment by yaira2** [comment]
The issue with this UX is that some users prefer the preview pane to remain selected. Implementing this change would require users to reselect the preview pane, which could be frustrating. One possible solution is to automatically switch back to the preview pane when a file is selected. However, this behavior might not be ideal, as most users expect the pane they actively select to stay selected.
