### ISSUE TITLE
Developer Option to Open in JetBrains IDEs

### ISSUE THREAD

**Issue by faakher** [files-community/Files#15664]
### What feature or improvement do you think would benefit Files?

Hi,
It will be really nice to have an option to select with which IDE we want to open folder/git repo.
Being specific, it should also provide an option to open folder/repo in JetBrains IDEs like phpStorm, pyCharm etc.

### Requirements

it will provide a better option for those users who are really not found of vs code

### Files Version

3.5.0.0

### Windows Version

10.0.22631.3737

**Comment by yaira2** [comment]
Thank you for your feedback, this is on our todo list and is being tracked in #12857.
