### ISSUE TITLE
Bug: Incorrectly resized column in Details View

### ISSUE THREAD

**Issue by tsvietOK** [files-community/Files#15665]
### Description

When I trying to resize any column in Details View its size changes not according to mouse move.

### Steps To Reproduce

1. Open any folder in Details View
2. Change width of the tag column
3. Check that the width of the column is changed not according to mouse move

### Requirements

Size of the column should be changed according to mouse move.

### Files Version

3.5.0.0

### Windows Version

10.0.22631.3737

### Log File

[debug.log](https://github.com/user-attachments/files/15959432/debug.log)

**Comment by yaira2** [comment]
Do you mean how the mouse moves faster than the size gripper?

**Comment by yaira2** [comment]
Thanks
