### ISSUE TITLE
Properties Window Starts Minimized 

### ISSUE THREAD

**Issue by SmallvilleClark** [files-community/Files#15668]
### Description

If I open the properties of ANY file the properties window starts off minimized and you have to click on taskbar to select and open.

### Steps To Reproduce

1. Right-Click any file (I was working on .pdf files) select the wrench
2. nothing seems to happen - check the taskbar the properties window is there, minimized.
3. click on properties window to open.
4. This only started happening since the last (Windows Store) update.

### Requirements

Fix Properties window starts off hidden/minimized.

### Files Version

3.5.0.0

### Windows Version

10.0.19045.4529

### Log File

[debug.log](https://github.com/user-attachments/files/15960066/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #13697. You can check there or click subscribe in the right sidebar for updates.
