### ISSUE TITLE
Recycle Bin: Driver Unplugged

### ISSUE THREAD

**Issue by andrew-james-heard** [files-community/Files#15661]
### Description

Apologies if this is already reported, but I can't get the Recycle Bin to open at all. Displays Driver Unglugged NotAFolder. Fortunately I can disable Files as default File Manager & Windows Explorer will correctly open the Recycle Bin.

### Steps To Reproduce

1. click on Recycle Bin

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.4.18.0

### Windows Version

11 23H2

### Log File

[debug.log](https://github.com/user-attachments/files/15950116/debug.log)

**Comment by 0x5bfa** [comment]
Thanks for the feedback, could you check this issue is the same as #15083

**Comment by andrew-james-heard** [comment]
duplicate of https://github.com/files-community/Files/issues/15083

**Comment by andrew-james-heard** [comment]
yes, it's the same issue sorry
