### ISSUE TITLE
Use consistent animation for menus or make animation customizable

### ISSUE THREAD

**Issue by RichardLuo0** [files-community/Files#15676]
### Description

Most menus use the same animation as UWP (the drop-down like animation). But the menu opened on file uses fade-in animation, however, the submenu opened in the menu uses drop-down animation again.
I quite like the UWP drop-down animation, so please make them all the drop-down animation or make the animation customizable.

### Steps To Reproduce

1. right click on a file
2. watch the animation

### Requirements

Use consistent animation for menus or make animation customizable

### Files Version

3.5.0.0

### Windows Version

22631.3737

### Log File

Doesn't help in this issue

**Comment by 0x5bfa** [comment]
You may refer to the context fly out when you right click on a file or a folder. It's called ContextFlyout and it acts like any other context fly out and we use it on purpose.

**Comment by mdtauk** [comment]
This is an issue with WinUI in that MenuFlyout and CommandBarFlyout does not have a matching animation.

https://github.com/microsoft/microsoft-ui-xaml/issues/6869

**Comment by RichardLuo0** [comment]
> This is an issue with WinUI in that MenuFlyout and CommandBarFlyout does not have a matching animation.
> 
> [microsoft/microsoft-ui-xaml#6869](https://github.com/microsoft/microsoft-ui-xaml/issues/6869)

Can `MenuFlyout` replace all `CommandBarFlyout`?
Does WinUI not allow anyone to change its animation?

**Comment by 0x5bfa** [comment]
Not to be confusing, they said as below in the issue:
> thank you for reporting this. The animations are different by design, there are no plans to make changes here.

**Comment by yaira2** [comment]
> Can MenuFlyout replace all CommandBarFlyout?

They serve different purposes so we can't just replace them all.
