### ISSUE TITLE
Quick access and Recent files disappear when launched on boot

### ISSUE THREAD

**Issue by clansty** [files-community/Files#15678]
### Description

Quick access and Recent files disappear when launched on boot. They will return if I manually quit and relaunch files

### Steps To Reproduce

1. Turn on "start files app on boot"
2. reboot and let files app auto launch in background
3. open a files window, the quick access and recent files section is empty

### Requirements

- e.g. Fix crash that occurs when...
Files app is launched on boot

### Files Version

3.5.0.0

### Windows Version

10.0.22631.3737

### Log File

[debug.log](https://github.com/user-attachments/files/15969551/debug.log)

**Comment by yaira2** [comment]
https://answers.microsoft.com/en-us/windows/forum/all/windows-11-quick-access-folders-gone-and-pin-to/49b3f66a-062f-43e6-8417-728e2a42c896
