### ISSUE TITLE
Show pined folders in jump list

### ISSUE THREAD

**Issue by RichardLuo0** [files-community/Files#15679]
### What feature or improvement do you think would benefit Files?

![image](https://github.com/files-community/Files/assets/22096448/65c35d71-be00-4f0c-b2bc-e4e539aa31c3)
In here, add pined folders or recent files.

### Requirements

 Add pined folders or recent files to the jump list

### Files Version

3.5.0.0

### Windows Version

22631.3737

**Comment by Josh65-2201** [comment]
Thanks for the feedback, pinned and recent should already be shown, please open a bug report.

**Comment by Josh65-2201** [comment]
Can you make sure to add what Windows File Explorer shows for the jump list

**Comment by yaira2** [comment]
@RichardLuo0 it looks like you ran into the same issue reported here #14526. Based on the log file, it seems to have something to do with permission to access the jumplist, but we haven't been able to repro on any of our developer devices yet.
