### ISSUE TITLE
打开特殊文件没有反应

### ISSUE THREAD

**Issue by xiaofengsoft** [files-community/Files#1568]
打开没有后缀名的文件(且没有绑定此文件打开方式的应用)时没有反应

**Comment by hez2010** [comment]
I cannot repro your problem.
On my computer, Windows will prompt you selecting the open method for your file.

**Comment by Jaiganeshkumaran** [comment]
@xiaofengsoft First, minimize all applications using Windows + M keyboard shortcut and then open FIles UWP again and make it maximized. Then the dialog will be shown.

首先，使用Windows + M键盘快捷键最小化所有应用程序，然后再次打开FIles UWP并将其最大化。 然后将显示对话框。

首先，使用Windows + M鍵盤快捷方式最小化所有應用程序，然後再次打開FIles UWP並將其最大化。 然後將顯示對話框。

**Comment by duke7553** [comment]
@Jaiganeshkumaran Is this still an issue? If so, can you describe it to me?

**Comment by yaichenbaum** [comment]
Thanks again for your feedback.

_Since we didn't hear from you on this topic for 7+ days, we'll assume everything is worked out and close this feedback item. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this._
