### ISSUE TITLE
钉住文件复制状态

### ISSUE THREAD

**Issue by AisinGioroKiIoi** [files-community/Files#15697]
### What feature or improvement do you think would benefit Files?

希望能钉住文件复制时的进度状态。当大文件复制时，需要一段时间等待，操作其它软件时，已经打开的文件复制进度窗口会自动关闭。希望能钉住，以便更直观的查看当前进度。

### Requirements

如上

### Files Version

3.5.0.0

### Windows Version

10.0.22631.3737

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #15431 . You can check there or click subscribe in the right sidebar for updates.
