### ISSUE TITLE
Bug: Google Drive doesn't show in Cloud Drives when mounts as a folder

### ISSUE THREAD

**Issue by kohyung** [files-community/Files#15698]
### Description

Google Drive didn't show up in Cloud Drives Sidebar, Dropbox & Onedrive got no problem.
![screenshot-1719384747145](https://github.com/files-community/Files/assets/65665469/7c6ffcb2-cfd9-4baa-a0c3-046732f6ca10)

### Steps To Reproduce

Just new install already like that.
![screenshot-1719384747145](https://github.com/files-community/Files/assets/65665469/8f821506-752d-4a8a-ad15-6c872e3c9df3)

### Requirements

New installation already like that.
![screenshot-1719384747145](https://github.com/files-community/Files/assets/65665469/7acd70ae-3307-4727-a305-40b48c442195)

### Files Version

3.5.0.0

### Windows Version

10.0.19045.4529

### Log File

[debug.log](https://github.com/user-attachments/files/15983692/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report. Have you set up the desktop client, opened it and restarted Files from the system tray?

**Comment by kohyung** [comment]
Hi, pls refer to the attachment, I have tried a few times.

**Comment by Josh65-2201** [comment]
Email attachments don't work. You will have to click the `View on GitHub` link at the bottom of the email > Copy and paste or click the add attachment button to select the file > Wait until you don't see `uploading` in the text > Click the green comment button.

**Comment by kohyung** [comment]
Hi, pls refer to the attachment, I have tried a few times.
![screenshot-1719404309390](https://github.com/files-community/Files/assets/65665469/f6cccedf-21bd-40f5-88ee-ea2d7ae1b2db)

**Comment by Josh65-2201** [comment]
Can you send a screenshot of the full Windows File Explorer window on `This PC`

**Comment by kohyung** [comment]
![Screenshot 2024-06-26 22 33 00](https://github.com/files-community/Files/assets/65665469/72f0fa90-2d14-49fe-8738-3f206a837919)

**Comment by Josh65-2201** [comment]
Need a screenshot from Windows File Explorer, not Files.

**Comment by kohyung** [comment]
![Screenshot 2024-06-26 22 37 44](https://github.com/files-community/Files/assets/65665469/423aadfe-bf9a-46cd-98eb-02b28faed95f)

**Comment by hez2010** [comment]
We don't support Google Drive mounting as a folder instead of a dedicate drive currently.

@yaira2 To detect the mounting point of Google Drive properly, we need to inspect the value of `PerAccountPreferences` in `HKEY_CURRENT_USER\Software\Google\DriveFS` from the Windows Registry.

**Comment by wharvex** [comment]
Hello, I would like to try to work on this if that is okay. I think I found the place in the source code where I would need to make changes, and I plan to start working on it tomorrow. I am aware of the contributing guidelines and will follow them.

**Comment by yaira2** [comment]
Thank you! Please reach out if you have any questions.

**Comment by wharvex** [comment]
No problem! I made some progress on exploring the problem today (see the notification above about the commit I just made that references this issue), and I'm hoping to submit a pull request sometime this weekend.

**Comment by yaira2** [comment]
@kohyung we've resolved the issue in our development branch, and it will be included in the next update. Huge shoutout to @wharvex for contributing this fix.
