### ISSUE TITLE
Bug: 3.5.1 won't install because PRI file fails to merge

### ISSUE THREAD

**Issue by ByronGarbutt** [files-community/Files#15699]
### Description

App installation failed with error message: Merge failure for shared merged PRI file : error 0x80070490 : Cannot register the FilesPreview_3.5.1.0_x64__1y0xx7n9077q4 package because there was a merge failure with the following file: C:\Program Files\WindowsApps\FilesPreview_3.5.1.0_neutral_split.scale-125_1y0xx7n9077q4\resources.pri (0x80070490)

### Steps To Reproduce

Apply 3.5.1 update

### Requirements

Files upgraded from 3.5 to 3.5.1

### Files Version

3.5.1

### Windows Version

11.0.26120.961

### Log File

[debug.log](https://github.com/user-attachments/files/15985202/debug.log)

**Comment by 0x5bfa** [comment]
0x80070490 seems to be an error code from Microsoft Store components.

Can you try to reinstall the app (firstly export your settings from Settings > Advanced)
If not fixed, try `"DISM.exe /Online /Cleanup-image /Scanhealth"`

**Comment by deviaze** [comment]
Exact same issue here (on reinstall). Last night I tried updating Files Preview but it failed silently & refused to open after that. Uninstalled and reinstalled Files Preview and got the same error as ByronGarbutt above.  

Surface Pro 9 (intel) Windows 11 Home 23H2.

**Comment by ByronGarbutt** [comment]
> 0x80070490 seems to be an error code from Microsoft Store components.
> 
> Can you try to reinstall the app (firstly export your settings from Settings > Advanced) If not fixed, try `"DISM.exe /Online /Cleanup-image /Scanhealth"`

Ran sfc /scannow and dism commands ScanHealth & RestoreHealth, rebooted, same issue ... tried it on another laptop with 23H2, same issue

**Comment by yaira2** [comment]
@Josh65-2201 can you repro this?

**Comment by Josh65-2201** [comment]
Yes

**Comment by yaira2** [comment]
This is resolved with v3.5.2.
