### ISSUE TITLE
Allow adjustable columns in column view

### ISSUE THREAD

**Issue by ccrooks562** [files-community/Files#15692]
### What feature or improvement do you think would benefit Files?

Hi there!

I love Files app, but the column view is not adjustable. Is it possible to add this? It would help so much, especially to view longer file names.

Thanks!

### Requirements

- This proposal will accomplish allowing us to view longer file names in column view.

### Files Version

3.5.0.0

### Windows Version

11

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #6534 . You can check there or click subscribe in the right sidebar for updates.
