### ISSUE TITLE
App Never Opens

### ISSUE THREAD

**Issue by EliasZeus** [files-community/Files#15703]
### Description

After installing and restating the computer, Files app 3.5 never opens. In this case, I open Task Manager to force quit the app.

### Steps To Reproduce

1. Install the App.
2. Restart the computer.
3. Open the App.
4. App never opens.

### Requirements

After installing and restating the computer, Files app 3.5 never opens. In this case, I open Task Manager to force quit the app.

### Files Version

3.5

### Windows Version

11

### Log File

Nothing to report here, app never opens, no LOG file to report.

**Comment by yaira2** [comment]
Does the splash screen display?

**Comment by 0x5bfa** [comment]
- Could you try to find Files app from `Windows logs` > `Application` > sort by `Source` > `.NET Runtime` in Event Viewer?
- Try to get log file:
  - If you're in Stable (Yellow):<br/>`C:\Users\USERNAME\AppData\Local\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState\debug.log`
  - If you're in Preview (Blue):<br/>`C:\Users\USERNAME\AppData\Local\Packages\FilesPreview_1y0xx7n9077q4\LocalState\debug.log`

**Comment by 0x5bfa** [comment]
- Could you try to find Files app from `Windows logs` > `Application` > sort by `Source` > `.NET Runtime` in Event Viewer?
- Try to get log file:
  - If you're in Stable from **Store** (Yellow):<br/>`C:\Users\USERNAME\AppData\Local\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState\debug.log`
  - If you're in Stable from **Website** (Yellow):<br/>`C:\Users\USERNAME\AppData\Local\Packages\Files_1y0xx7n9077q4\LocalState\debug.log`
  - If you're in Preview from **Website** (Blue):<br/>`C:\Users\USERNAME\AppData\Local\Packages\FilesPreview_1y0xx7n9077q4\LocalState\debug.log`

**Comment by EliasZeus** [comment]
This is what I get, see attached screenshot.



​Elias Sarantopoulos
www.pixelias.com<http://www.pixelias.com/>
www.churchofchora.com<http://www.churchofchora.com/>


________________________________

**Comment by EliasZeus** [comment]
None of these choices are available!



​Elias Sarantopoulos
www.pixelias.com<http://www.pixelias.com/>
www.churchofchora.com<http://www.churchofchora.com/>


________________________________

**Comment by Josh65-2201** [comment]
Email attachments don't work. You will have to click the `View on GitHub` link at the bottom of the email > Copy and paste or click the add attachment button to select the file > Wait until you don't see `uploading` in the text > Click the green comment button.

**Comment by EliasZeus** [comment]
![Screenshot 2024-06-26 215121](https://github.com/files-community/Files/assets/52591822/4f16be6c-c543-4e24-b225-7bbc7733e89f)

That is the only thing that happens, it won't open.

**Comment by yaira2** [comment]
Okay, so you got to the splash screen. In that case there should be a log file as well.

**Comment by EliasZeus** [comment]
[debug.log](https://github.com/user-attachments/files/15994885/debug.log)

Log file is attached.

**Comment by yaira2** [comment]
Thanks! Unfortunately it doesn't contain much info.

**Comment by yaira2** [comment]
Seems to be the same as #14366

**Comment by EliasZeus** [comment]
Sorry mate but I am giving up, spending too much time that I don't have.  I will try again, maybe another version.



​Elias Sarantopoulos
www.pixelias.com<http://www.pixelias.com/>
www.churchofchora.com<http://www.churchofchora.com/>


________________________________

**Comment by Josh65-2201** [comment]
Even if you can't do it now, please at some point check otherwise it unlikely to be fixed.

**Comment by yaira2** [comment]
Either way, we'll continue tracking in #14366 and trying to find a fix. I suspect it's a bug with the app framework, but we'll do our best to find a workaround.

**Comment by EliasZeus** [comment]
That would be wonderful! I know it is a lot of work being a developer and you have produced a great app. So, hopefully in the near future you will come across the bug. 👍
