### ISSUE TITLE
Bug: Extreme unresponsiveness in Dual Pane Mode and grid layout

### ISSUE THREAD

**Issue by rivahere** [files-community/Files#15705]
### Description

When I am in dual pane mode with two directories with many files (probably 500+; especially media) in grid view, there is extreme delays and lag. I was copying many files (50 - 1200) from individual directories into one single consolidated folder and things like Ctrl+A and back/forward navigations would take 10 - 15 seconds to register/take effect. When in details mode the issue is nearly fully remedied. This is also only an issue in dual pane mode, when I had the exact same directories and file transfers in two separate windows it was nearly remedied as well.

### Steps To Reproduce

1.) Open a large directory (preferably over 500 files and majority being photos/videos) in grid mode.
2.) Open a second similar or the same directory in the second/dual pane.
3.) Start copy/move or navigation actions between the two panes (still both in grid mode).

### Requirements

Like the built-in windows file manager, try to negate most if not all of the delay/hesitation issues in grid mode (and all modes if at all possible).

### Files Version

3.5.0.0

### Windows Version

Windows 11 Pro 22621.3810 (Ghost Spectre)

### Log File

[debug.log](https://github.com/user-attachments/files/15994172/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, we're working on improving performance and will continue releasing updates with this goal in mind. In the meantime, we'll be tracking this feedback in #4180.
