### ISSUE TITLE
Use Files as system/application Open/Save As dialog.

### ISSUE THREAD

**Issue by rivahere** [files-community/Files#15708]
### What feature or improvement do you think would benefit Files?

(Please forgive me if this is already an existing request, I do not entirely know how to find them/navigate github other than releases.) I would like to see if (in the future, if possible at all) to have the ability to set Files as the entire system-wide file manager; for Open, Save As..., and other dialogs typically done by explorer.exe.

### Requirements

Better continuity and overall system appearence/aesthetic.

### Files Version

3.5.0.0

### Windows Version

Windows 11 Pro 22631.3810

### Comments

Good work on this guys.

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #6314. You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
We're currently tracking this in #6314. The challenge is that Windows isn't designed for third party file managers, but we don't plan to let that stop us! We have some experimental work in this area but it needs a lot of work before we can release this feature.

**Comment by yaira2** [comment]
If you build Files from the source code, there is an option in the experimental settings page that you can try, but please keep in mind that it's not stable and may have issues.
