### ISSUE TITLE
Filder with image doesn't present images themself but the icons

### ISSUE THREAD

**Issue by InomedisInc** [files-community/Files#15704]
### Description

When you open a folder with pictures inside for the first time, you cannot see the preview but the pictures icons.
If you close the app and reopen, you have the preview. It's the same for the final or preview version,
![image](https://github.com/files-community/Files/assets/89644888/b8bce901-b0c6-4954-9ca8-be098c2e28be)

### Steps To Reproduce

Open a folder with pictures for the firstime
close the apps
open again and the preview appears.

### Requirements

No Crash

### Files Version

3.5.2.0

### Windows Version

10.0.19045.4598

### Log File

[debug.log](https://github.com/user-attachments/files/15992806/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Do you have Files on demand enabled in One Drive?

**Comment by InomedisInc** [comment]
Hi,
The files are already downloaded in the folder
The problem still the same outside onedrive folder


________________________________
De : Josh65-2201 ***@***.***>
Envoyé : mercredi 26 juin 2024 14:53
À : files-community/Files ***@***.***>
Cc : InomedisInc ***@***.***>; Author ***@***.***>
Objet : Re: [files-community/Files] Filder with image doesn't present images themself but the icons (Issue #15704)


Thanks for the report, Do you have Files on demand enabled in One Drive?

**Comment by yaira2** [comment]
Can you try clearing the thumbnail cache in Windows?

**Comment by InomedisInc** [comment]
Yes I do
It works
thank you


________________________________
De : Yair ***@***.***>
Envoyé : mercredi 26 juin 2024 16:07
À : files-community/Files ***@***.***>
Cc : InomedisInc ***@***.***>; Author ***@***.***>
Objet : Re: [files-community/Files] Filder with image doesn't present images themself but the icons (Issue #15704)


Can you try clearing the thumbnail cache in Windows?

**Comment by yaira2** [comment]
Great! Thank you for letting us know.
