### ISSUE TITLE
In the full screen of Files, a small white bar appears at the top

### ISSUE THREAD

**Issue by Anyayay** [files-community/Files#15702]
### Description

![image](https://github.com/files-community/Files/assets/37764175/2a457fc4-bc8d-4825-9897-357a72dec697)

### Steps To Reproduce

As long as the full screen will appear

### Requirements

Little white stripes don't appear

### Files Version

3.5.0.0

### Windows Version

22631.3737

### Log File

[debug.log](https://github.com/user-attachments/files/15990396/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, this is an issue with Microsoft WinUI https://github.com/microsoft/microsoft-ui-xaml/issues/9067.  You can check there or click subscribe in the right sidebar for updates. Please also add a comment or thumbs up to the issue so Microsoft can possible make it more priority
