### ISSUE TITLE
Pictures Icon has a black background

### ISSUE THREAD

**Issue by InomedisInc** [files-community/Files#15700]
### Description

Dear Developer
I'm working on windows 10 pro. I found in your app "Files 3.5" that background of "Pictures" folder is in black even if it's  dark or light mode.
![Capture_dark_mode](https://github.com/files-community/Files/assets/89644888/41b32cea-a235-4c41-85d8-f7e09c501677)
![Capture_light_mode](https://github.com/files-community/Files/assets/89644888/dda77448-e3be-4bcd-a573-3dacb7327560)

### Steps To Reproduce

Permanent issue

### Requirements

Change the backcolor adapted regarding the mode

### Files Version

3.5.0.0

### Windows Version

10.0.19045.4529

### Log File

[debug.log](https://github.com/user-attachments/files/15986303/debug.log)

**Comment by 0x5bfa** [comment]
Thanks for the feedback!

Can you try clearing Windows thumbnail cache.
1. Type Disk clean-up into the start menu
2. Press Enter on your keyboard or OK > Scroll to bottom > select thumbnails > Click Ok
3. Restart Files from the system tray

**Comment by InomedisInc** [comment]
Hello
Yes in file explorer icons display properly
[cid:61861c3b-064e-4728-b56e-32ecd1aebe98]
[cid:b1f588f8-ff91-4f24-baeb-77463ca7769a]
I used another computer and it's the same
[cid:a057729c-fe34-4115-bc03-e4ce2bc8fbc9]
[cid:eaba602c-6160-49cc-bb2b-9cc7a81f7ca1]
Also I tried to install the Files Preview version and I have this following message
[cid:a85fabed-09ed-4a74-9ebb-887d49289d24]
 " Merge failure for shared merged PRI file : error 0x80070490 : Cannot register the FilesPreview_3.5.1.0_x64__1y0xx7n9077q4 package because there was a merge failure with the following file: C:\Program Files\WindowsApps\FilesPreview_3.5.1.0_neutral_split.scale-125_1y0xx7n9077q4\resources.pri (0x80070490)"

Have a good day

________________________________
De : Yair ***@***.***>
Envoyé : mercredi 26 juin 2024 10:13
À : files-community/Files ***@***.***>
Cc : InomedisInc ***@***.***>; Author ***@***.***>
Objet : Re: [files-community/Files] Pictures Icon has a black background (Issue #15700)


Does the icon display properly in File Explorer?

**Comment by yaira2** [comment]
What about in the Grid Layout in Files?

**Comment by InomedisInc** [comment]
The grid layout seems ok
[cid:9e2978ca-315c-4cca-9650-f9c36f3ffb6c]
[cid:05529caf-6e29-44d5-af63-7dd0e622d1bb]

But as complementary information
It's the icons with the black color in background are from onedrive. thew problem appears only for list and details view
________________________________
De : Yair ***@***.***>
Envoyé : mercredi 26 juin 2024 11:42
À : files-community/Files ***@***.***>
Cc : InomedisInc ***@***.***>; Author ***@***.***>
Objet : Re: [files-community/Files] Pictures Icon has a black background (Issue #15700)


What about in the Grid Layout in Files?

**Comment by yaira2** [comment]
Seems to be the same as #14993, we'll continue tracking there and will post if we have any fixes.
