### ISSUE TITLE
Command bar 'New' button flyout menu position

### ISSUE THREAD

**Issue by froggz19** [files-community/Files#15709]
### What feature or improvement do you think would benefit Files?

UI consistency?

### Requirements

In file explorer, this flyout is shown below the button by default and above the button only when it goes out of screen bounds. Files seems to show this flyout menu above the button by default. If possible, can you make it behave the same as in file explorer?

The glyph on the button points down so I would expect the flyout to be shown under the button by default.

### Files Version

3.5.0.0

### Windows Version

10.0.22631.3810

### Comments

![image](https://github.com/files-community/Files/assets/8935954/391df837-018c-4596-a363-6532c8c62db0)

**Comment by yaira2** [comment]
This is due to the position of the window, if you move Files up a little bit the flyout will open downwards.

**Comment by froggz19** [comment]
I know but in Files this behavior is reversed. It is always shown above even when there's plenty of space to show it below the button.

**Comment by yaira2** [comment]
![image](https://github.com/files-community/Files/assets/39923744/23044230-8491-478c-988b-40d94f413573)

**Comment by froggz19** [comment]
Yes but that only because the window is close to the top screen edge... As you can see in the pic below, there's plenty of space to be shown under the button.

![image](https://github.com/files-community/Files/assets/8935954/de6a4a0d-9fb3-4ee8-9e47-25e41a8d3081)

**Comment by yaira2** [comment]
It's odd that it requires such a large amount of extra space before it displays downwards. Unfortunately we don't have any control over this, but you can try reporting this bug on the WinUI repo https://github.com/microsoft/microsoft-ui-xaml/issues.

**Comment by yaira2** [comment]
Actually, correction, I was looking in the wrong place.

**Comment by froggz19** [comment]
Nice to hear that. 
My english sucks and I did my best trying to explain the issue. (It's not really an issue but still)

**Comment by yaira2** [comment]
No worries! I understood the issue right away but I mistakenly thought it was a bug in the WinUI framework.
