### ISSUE TITLE
Recycle Bin Bug

### ISSUE THREAD

**Issue by Sergey842248** [files-community/Files#15714]
### Description

The Recycle Bin icon wont show empty if it's emptied by going in the Recycle Bin and click "Empty Recycle Bin". But if it's emptied by: right click on Recycle Bin > "Empty Recycle Bin" > *The Icon shows emptied*

https://github.com/files-community/Files/assets/125195195/1a0b345f-fe40-403e-9eac-450b344c2d02

### Steps To Reproduce

1. Open Files-App > Settings > Advanced > Activate "Set Files as the default file manager"
2. Move a File to the Recycle Bin
3. Open the Recycle Bin
4. Click "Empty Recycle Bin" > *The Recycle Bin Icon on the Desktop wont show empty*

### Requirements

Fix Bug that occurs when the Recycle is emptied by going in the Recycle Bin and click "Empty Recycle Bin", it show the filled Recycle Bin.

### Files Version

3.5.0.0

### Windows Version

10.0.22635.3790

### Log File

[debug.log](https://github.com/user-attachments/files/16011455/debug.log)

**Comment by Moose1005** [comment]
I am going through a similar bug with the recycle bin aswell. I cannot open the folder and an error shows up, saying that the drive is not connected? 

![github bin bug](https://github.com/files-community/Files/assets/58957306/d0a76302-90ee-4b21-a38d-f7d38f8de24d)

How strange indeed.
