### ISSUE TITLE
Files classic installer just carries on installing forever

### ISSUE THREAD

**Issue by firthm01** [files-community/Files#15710]
### Description

Downloaded the "classic installer" for Files Version 3.5.0.0 on Win 11 Pro
Just doesn't seem to get anywhere. Progress bar is scrolling away, but nothing happens, even after 20 min or so.

### Steps To Reproduce

1. Download classic installer
2. Run it

### Requirements

- Expected behaviour: installer completes, however, it just seems to get stuck in some eternal loop.

I'm not sure how to get any more diagnostics data from this.

### Files Version

3.5.0.0

### Windows Version

Windows 11 Pro 22621.3296

### Log File

I have no log file because the installer hangs

**Comment by yaira2** [comment]
Thanks for the report, can you check if the PowerShell method works?
https://files.community/docs/install

**Comment by firthm01** [comment]
That works. I had no return from the command but when I navigated to `https://cdn.files.community/files/stable/Files.Package.appinstaller`, downloaded and ran, it said it was already installed, so it probably did (?) I'm not sure what the expected return is. In any case, it's running.
I had forgotten it was running, but the installer is still toddling away in the background and doing the progress bar swipe.

**Comment by yaira2** [comment]
I guess you can just close the installer 🙂
