### ISSUE TITLE
File draging

### ISSUE THREAD

**Issue by Qingzi0428** [files-community/Files#15711]
### Description

While using Files app, I am unable to drag files to other places in my computer.

### Steps To Reproduce

While using Files app, I am unable to drag files to other places in my computer.

### Requirements

Fix this problem

### Files Version

3.5.0.0

### Windows Version

10.0.19045.3636

### Log File

1

**Comment by Josh65-2201** [comment]
Thanks for the report, 
- Please upload (Do not copy and paste content) the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder. 
- Are you running Files as admin and do you have UAC (User account control) turned off?
- Where are you dragging to?

**Comment by yaira2** [comment]
Did you see a prompt like this?
![image](https://github.com/files-community/Files/assets/39923744/d3798619-283a-4566-9a45-d959310c604f)

**Comment by Qingzi0428** [comment]
Yes, exactly. How to solve this problem?




晴子
***@***.***



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "files-community/Files"                                                                                    ***@***.***&gt;;
Date:&nbsp;Tue, Jul 2, 2024 10:54 AM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [files-community/Files] File draging (Issue #15711)





 
Did you see a prompt like this?
 image.png (view on web)

**Comment by Josh65-2201** [comment]
Follow the instructions on the prompt

**Comment by yaira2** [comment]
1. Open User Account control
2. Change the level from "Never notify" to the level above it. Restart Windows.
![image](https://github.com/files-community/Files/assets/39923744/d3923fa3-027f-4573-aca2-260b4b648fc2)

**Comment by Qingzi0428** [comment]
I have already made this changes and restarted my computer,&nbsp;

but the warning still appears.

And I am not able to drag files (see the video attached).




晴子
***@***.***



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "files-community/Files"                                                                                    ***@***.***&gt;;
Date:&nbsp;Tue, Jul 2, 2024 09:56 PM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [files-community/Files] File draging (Issue #15711)





  
Open User Account control
 
Change the level from "Never notify" to the level above it. Restart Windows.
 image.png (view on web)

**Comment by Josh65-2201** [comment]
How are you opening Files?
Also email attachments don't work. You will have to click the `View on GitHub` link at the bottom of the email > Copy and paste or click the add attachment button to select the file > Wait until you don't see `uploading` in the text > Click the green comment button.

**Comment by yaira2** [comment]
> I have already made this changes and restarted my computer, but the warning still appears. And I am not able to drag files (see the video attached).

I don't see the video as Josh mentioned, but can you check if it works to drag & drop tabs?

**Comment by Qingzi0428** [comment]
This is how I drag a file.
https://github.com/files-community/Files/assets/173972213/b190ef64-800e-4ec7-8fd7-38b8e5c89c13
And this is how I open and drag files.
https://github.com/files-community/Files/assets/173972213/021cf006-3d3c-4661-8df3-65986b6e7c77

**Comment by Qingzi0428** [comment]
I just upload it through Github. Can you see it now?




晴子
***@***.***



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "files-community/Files"                                                                                    ***@***.***&gt;;
Date:&nbsp;Wed, Jul 3, 2024 09:30 AM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [files-community/Files] File draging (Issue #15711)





  
I have already made this changes and restarted my computer, but the warning still appears. And I am not able to drag files (see the video attached).
  
I don't see the video (as Josh mentioned), but can you check if it works to drag &amp; drop tabs?

**Comment by Alexiiiander** [comment]
Hola respondiendo a la pregunta de @Qingzi0428  no se puede arrastrar Pestañas tampoco yo tmb tengo el problema de no poder arrastrar archivos dentro de una carpeta y/o similar.

**Comment by Josh65-2201** [comment]
Follow https://github.com/files-community/Files/issues/15711#issuecomment-2203260568

**Comment by Qingzi0428** [comment]
> 1. Open User Account control
> 2. Change the level from "Never notify" to the level above it. Restart Windows.
>    ![image](https://private-user-images.githubusercontent.com/39923744/345059245-d3923fa3-027f-4573-aca2-260b4b648fc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MDU1MzIsIm5iZiI6MTcyMTcwNTIzMiwicGF0aCI6Ii8zOTkyMzc0NC8zNDUwNTkyNDUtZDM5MjNmYTMtMDI3Zi00NTczLWFjYTItMjYwYjRiNjQ4ZmMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDAzMjcxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmNjU5MjEzOTFhN2NiOTFlOGY3NDM5OTcyYzUwMGMxYjE2OTMwMTY0YzE4MDc4NTQ1ZTcyYmFlMDY2ZDc5ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E-WyqOD-vmKXc4V3Q5xUWkkwIRkwYXKs9fZ6M6zkGbo)


https://github.com/user-attachments/assets/2374cc6d-a9b2-4308-8e0d-5f047a6c77c0

Can you see the video attached? I have changed the settings and restarted my computer. Dropping files still does not work.

**Comment by Josh65-2201** [comment]
It's possible this will be fixed with #15795
