### ISSUE TITLE
Bug: Unavailable buttons don't use grey icons

### ISSUE THREAD

**Issue by hluica** [files-community/Files#15712]
### What feature or improvement do you think would benefit Files?

Now in version 3.5, the usability of a button is not directly demonstrated by its appearance; only when the mouse passes over the button is there explicit feedback about whether it is usable or not.
In Windows File Explorer, as well as in most web browsers, the usability of buttons can be seen directly from their color - grey or black; this feature was also present in previous versions of the program. However, after updating to version 3.5, this feature is no longer available.

### Requirements

- If one function is unavailable, the button of it should be grey; instead of still be black like now.
- If one function is available, the button can be black.
- In any case, the availability of program buttons should not be displayed only when the mouse passes over the button icon, but should be presented in a clear manner at all times.

### Files Version

3.5.0.0

### Windows Version

10.0.26120.961

### Comments

These buttons should look like buttons in the same position in:
- File Explorer: ![屏幕截图 2024-06-27 111029](https://github.com/files-community/Files/assets/136835843/891ac988-94a0-493c-9487-850bdd2d5ba6)
- Microsoft Edge: ![屏幕截图 2024-06-27 111049](https://github.com/files-community/Files/assets/136835843/f633d76e-96b8-4810-a227-00b22a5312e2)
- Firefox: ![屏幕截图 2024-06-27 111103](https://github.com/files-community/Files/assets/136835843/a7367da8-f7f1-487c-9776-6b087fe1dbed)
- Even Apple OSs: ![20240627_031130000_iOS](https://github.com/files-community/Files/assets/136835843/90ad1c75-7132-43f2-8afb-40a6b22c0d0e)

Instead of what they are now.

**Comment by 0x5bfa** [comment]
We noticed this a few hours ago and will change to hide unavailable buttons.
Thanks!

**Comment by yaira2** [comment]
This is fixed in `main` and will be resolved in the next update.
