### ISSUE TITLE
Bug: Column layout selects first column folder when right or left clicking if it's scrollable

### ISSUE THREAD

**Issue by SrMizuki** [files-community/Files#15713]
### Description

While using the Columns view (one of the main reasons I would like to use Files App) after column 4 I can not select, and copy any folder on that same column. Sometimes it copies the folder of the 1st column and the right click on elements of the last column shows the controls menu but it disappears right away making it impossible to use it.

Another thing is that the path on the navigation bar should follow the last column opened, but it always stops at the 3rd column, everything I open after that does not count to the path. 

Besides that, the whole app it's to laggy to use in general

### Steps To Reproduce

1. Use column view layout
2. Open three folders levels
3. Right click folder in 3rd level
4. See right click menu open slower then normal and selection contently moving to first column and back

### Requirements

- Keep folder/file selection when right or left clicking a column

### Files Version

5.5.0.0

### Windows Version

10.0.22631.3810

### Log File

[debug.log](https://github.com/user-attachments/files/16011388/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board. Just to make sure when you are trying to copy a folder are you using the right click menu?

**Comment by SrMizuki** [comment]
Right mouse menu yes, it shows up and desapears right away, seems like it's
constantly loading/refreshing the column I'm in, that's my assumption. Wen
I copy on the top toolbar it copies the folder from the 1st column.

I hope this helps
Cheers,
Telmo a.k.a. SrMizuki

**Comment by yaira2** [comment]
Merging with #15776
