### ISSUE TITLE
Bug: Crash via CLI when using an invalid path

### ISSUE THREAD

**Issue by Mento** [files-community/Files#15717]
### Description

Files crashes if i do `files.exe -tag a /a`.

### Steps To Reproduce

files.exe -tag a /a

### Requirements

No crash

### Files Version

3.5.0.0

### Windows Version

10.0.22631.3737

### Log File

[debug.log](https://github.com/user-attachments/files/16014199/debug.log)

**Comment by yaira2** [comment]
This will be fixed in the next release
