### ISSUE TITLE
Can't open a file location from Chrome downloads

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [files-community/Files#15728]
### Description

When you have finished downloading a file on Chrome, you can press the folder icon which takes you to the file lcoation. Using Windows Explorer, this works, but not when Files is set as the default file app. When Files is the default app, it simply opens the folder in which the downloaded file is, but nothing more. It doesn't select it, and even less brings the user to it

### Steps To Reproduce

1. Download a file with Chrome
2. Press the folder icon

### Requirements

Always happens

### Files Version

3.5.0.0

### Windows Version

10.0.22631.3737

### Log File

[debug.log](https://github.com/user-attachments/files/16042180/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #14429 . You can check there or click subscribe in the right sidebar for updates.

**Comment by TheWonderfulTartiflette** [comment]
Sure, thanks a lot :)
