### ISSUE TITLE
memory

### ISSUE THREAD

**Issue by haracemko** [files-community/Files#15725]
### What feature or improvement do you think would benefit Files?

The program uses much more memory than the standard Windows explorer, and with each tab opened the situation gets worse, I'm testing XYxplorer and it is ten times lighter, please optimize it. Thanks.

### Requirements

Optimize the code

### Files Version

3.5

### Windows Version

w 10 21h2

**Comment by 0x5bfa** [comment]
Thank you for the feedback!

Currently we put resource intensive works at high priority and track it on in #4180. We're keep working on that area to improve performance.

**Comment by yaira2** [comment]
@haracemko we're tracking this in the issue @0x5bfa linked above. In the meantime however, we suggest turning off the option to keep Files running in the background.
