### ISSUE TITLE
Add Support for kDrive File Cloud Service

### ISSUE THREAD

**Issue by Guigui3o2oo** [files-community/Files#15727]
### What feature or improvement do you think would benefit Files?

This proposal aims to extend the Files application's compatibility by incorporating support for the kDrive file cloud service. This enhancement will enable users to seamlessly access their files stored on kDrive directly from the Files interface, just like they currently can with other major cloud storage solutions.

### Research and Analysis
- Investigate the kDrive API documentation and determine its suitability for integration with the Files application.
- Study the architecture and design patterns used in the existing integrations with Google Drive, Proton, OneDrive, and Dropbox.

### Development
- Implement authentication and authorization flows for kDrive.
- Develop the necessary APIs and interfaces to interact with the kDrive platform.
- Integrate the kDrive SDK into the Files application.

### Testing and Validation
- Perform thorough testing to ensure proper functioning and stability of the newly added kDrive integration.
- Validate the user experience and usability of the new feature.

### Documentation and Release
- Update the official documentation to include instructions on setting up and using the kDrive integration.
- Prepare release notes and announce the new feature to the user base.

### Files Version

3.5.0.0

### Windows Version

10.0.22631.3737

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #15475 . You can check there or click subscribe in the right sidebar for updates.
