### ISSUE TITLE
Opening the wsl.exe window

### ISSUE THREAD

**Issue by tomtaylor-kbg** [files-community/Files#15723]
### Description

![image](https://github.com/files-community/Files/assets/103009535/f5ad22d1-7799-44ba-9788-1096ae8b0ce9)
This window opens every time I run Files, this can be fixed.

### Steps To Reproduce

Cette fenêtre s'ouvre chaque fois 

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.5.0.0

### Windows Version

10.0.26120.961

### Log File

[debug.log](https://github.com/user-attachments/files/16032390/debug.log)

**Comment by yaira2** [comment]
Thank you for the report, this is due to a change in the latest version of Windows and we'll include a fix in the next update of Files.
