### ISSUE TITLE
Bug: Crash after trying to delete files from search results

### ISSUE THREAD

**Issue by Deniryer** [files-community/Files#15731]
### Description

So I switched to files after being tried of MS Explorer hiccups and shenanigans, but Files has some of its own imperfections. 
App hung up on a process of deleting txt files found via search bar, after it crashed at least ~~280 of them were actually deleted but they weren't transfer to bin.

just checked, it happens with other type of files too. 

### Steps To Reproduce

1. Create around 25500 txt files with varying degree of size and complexity, scattered around different folders on the same drive,
2. Try to first find them through search function then delete them,
3. Watch world burn. 

### Requirements

Stopped responding and crashed after trying to delete 25500 .txt files. 

### Files Version

3.5.0.0

### Windows Version

10.0.22631.3737

### Log File

[debug.log](https://github.com/user-attachments/files/16044218/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by hishitetsu** [comment]
Isn't this the same issue as #14108?
