### ISSUE TITLE
Default File Manager auto disabling

### ISSUE THREAD

**Issue by jdzoska** [files-community/Files#15735]
### Description

Whenever I toggle this on, it immediately toggles off, stable and preview

### Steps To Reproduce

Turn the option on in Advanced

### Requirements

Should activate when pressed

### Files Version

3.5.0.0

### Windows Version

10.0.22000 build 22000

### Log File

[debug.log](https://github.com/user-attachments/files/16055295/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, This is an issue with Windows making the option not compatible. The only known solution right now to reinstall Windows

**Comment by yaira2** [comment]
@jdzoska are you an admin user?
