### ISSUE TITLE
Rearranging Columns

### ISSUE THREAD

**Issue by valdeirseguros** [files-community/Files#15739]
### What feature or improvement do you think would benefit Files?

- It could have the option to **rearrange the columns** according to the **user's preference**, increasing customization.
- It could include groups to open folders, making it possible to group folders according to the subject and when opening various applications, it will be able to show the selected folders.

### Requirements

- Currently the Type column is after the modified date column and it would be interesting to change it to be after the file name field.
- When opening a group, the folders that are part of it will be opened and when you open another group, the same will occur, but with different folders, with this, we will be able to separate the contexts of each group, making it easier for those who are developers.

### Files Version

3.5.0.0

### Windows Version

10.0.22635.3858

**Comment by yaira2** [comment]
Thank you for your feedback, I added a similar request to our todo list a while ago, can you confirm if this is the same? #8385
