### ISSUE TITLE
Free space is not refreshed

### ISSUE THREAD

**Issue by peerobo** [files-community/Files#15730]
### Description

After deleting some files, the overall free space of the disk is not updated.

![image](https://github.com/files-community/Files/assets/4023681/e8641167-409f-4b6c-9fbe-d975df6a8366)

### Steps To Reproduce

[as in description]

### Requirements

[as in description]

### Files Version

3.5.0.0

### Windows Version

windows 10 22H2 19045.4529

### Log File

[as in description]

**Comment by 0x5bfa** [comment]
Thanks for the report!

We’re aware of this issue and tracking this on in #6182. To get further news, please click Subscribe button from the sidebar.
