### ISSUE TITLE
Bug: .Zip file extension isn't added when exporting settings

### ISSUE THREAD

**Issue by AisinGioroKiIoi** [files-community/Files#15737]
### Description

导出配置文件时，显示导出的文件是ZIP格式的，但实际上没有文件的拓展名。

### Steps To Reproduce

如上。

### Requirements

导出配置文件时，自动附加文件格式后缀。

### Files Version

3.5.0.0

### Windows Version

10.0.22631.3810

### Log File

[debug.log](https://github.com/user-attachments/files/16059796/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by 0x5bfa** [comment]
Fixed. The fix will be shipped as a part of the next preview build or stable build.
