### ISSUE TITLE
Feature Request: Display information of multiple files in the details panel when multiple files are selected

### ISSUE THREAD

**Issue by jordan-msftfan** [files-community/Files#15749]
### What feature or improvement do you think would benefit Files?

In classic Windows Explorer, if you select multiple files, the details pane will display information about those files, such as the total sizes and the intervals between modification and creation times.

![Snipaste_2024-07-03_19-33-02](https://github.com/files-community/Files/assets/77601580/aea3c565-0f7f-4cc3-b74b-87f505fc5809)

### Requirements

- This proposal will accomplish when multiple files are selected, the overall information of the files is displayed, such as size, creation time, modification time, eth.
- This proposal will accomplish when multiple files are selected, you can add tags to multiple files at once in the details pane.
- This proposal would additionally achieve when multiple media files are selected, metadata information such as the total duration of the media is displayed in the details pane(this is a explorer features).

### Files Version

3.5.0

### Windows Version

10.0.22621.xxxx

**Comment by 0x5bfa** [comment]
Thanks for the feedback.

The details of selected files/folders can be viewed in Info Pane; you can toggle visibility of it from the right side Toolbar.

**Comment by jordan-msftfan** [comment]
Thanks for your reply, but currently the details panel of Files App can only display the details of one file/single file, when you select multiple files, current version of details pane will show "No preview available". I also noticed that I can multi-select files and right-click Properties to see aggregate information in the Properties window, such as the total length of the media, but I need a more intuitive way.

**Comment by jordan-msftfan** [comment]
Thanks for the reply, I'm sure this is roughly the same feature request, i'm look forware to the implementation of this feature!
