### ISSUE TITLE
Bug: Recycle Bin Icon is full

### ISSUE THREAD

**Issue by Sergey842248** [files-community/Files#15740]
### Description

The Recycle Bin icon wont show empty if it's emptied by going in the Recycle Bin and click "Empty Recycle Bin". But if it's emptied by: right click on Recycle Bin > "Empty Recycle Bin" > *The Icon shows emptied*

https://github.com/files-community/Files/assets/125195195/1a0b345f-fe40-403e-9eac-450b344c2d02

### Steps To Reproduce

1. Open Files-App > Settings > Advanced > Activate "Set Files as the default file manager"
2. Move a File to the Recycle Bin
3. Open the Recycle Bin
4. Click "Empty Recycle Bin" > *The Recycle Bin Icon on the Desktop wont show empty*

### Requirements

Fix Bug that occurs when the Recycle is emptied by going in the Recycle Bin and click "Empty Recycle Bin", it show the filled Recycle Bin.

### Files Version

Fix Bug that occurs when the Recycle is emptied by going in the Recycle Bin and click "Empty Recycle Bin", it show the filled Recycle Bin.

### Windows Version

1000.22700.1025.0

### Log File

[debug.log](https://github.com/user-attachments/files/16063190/debug.log)

**Comment by 0x5bfa** [comment]
Thanks for the report!

Emptying in Files doesn't work (while on the surface seems to work) and in Desktop does work?

**Comment by Sergey842248** [comment]
Only the Icon don't update even if I update the Desktop. If I empty the Recycle Bin by right click on it and choose "empty Recycle Bin" it works fine.

**Comment by Josh65-2201** [comment]
We're tracking this in #9946 . You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
This is a known issue (see the link Josh shared above). Interestingly, opening the Recycle Bin folder from the desktop will update the icon.
