### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by leowankerddd** [files-community/Files#15746]
### What feature or improvement do you think would benefit Files?

Considering the original Windows File Manager cannot adjust the size of the font of the files, it would be a huge Advantage, especially for those of us with large monitors at high resolution and poor eyesight, to be able to increase the font size of the files.

I really like your user interface only I have stuck with another program called double Commander because the font size is adjustable, and the font type is adjustable.

### Requirements

I guess that's up to the developers.

### Files Version

3.5.0.0

### Windows Version

Edition	Windows 11 Home Version	23H2 Installed on	‎5/‎16/‎2024 OS build	22631.3810 Experience	Windows Feature Experience Pack 1000.22700.1020.0

**Comment by yaira2** [comment]
Thank you for your feedback. While we don’t plan to implement this option right now (supporting different font sizes is very challenging), we remain open to revisiting it in the future.
