### ISSUE TITLE
Can't switch contextual images when opening an image from Files

### ISSUE THREAD

**Issue by JTFA** [files-community/Files#15748]
### Description

for example, open an image from a folder which contains many images, when using windows default explorer, it can switch to the next or the previous image:
<img width="884" alt="屏幕截图 2024-07-03 140439" src="https://github.com/files-community/Files/assets/57850248/11800d17-dbca-4820-ad69-29218d394292">
However, when open the same image using Files, there is no button to switch to the next or the previous:
<img width="900" alt="屏幕截图 2024-07-03 140800" src="https://github.com/files-community/Files/assets/57850248/3b10fba3-68eb-45de-86dd-60b2a84ad3b2">

### Steps To Reproduce

open an image from a folder which contains many images.

### Requirements

the behavior should be the same as the windows default explorer

### Files Version

3.5.0.0

### Windows Version

10.0.22631.3810

### Log File

[debug.log](https://github.com/user-attachments/files/16077816/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, We're tracking this in #15409 . You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
I've been seeing more reports about this recently, I wonder if Microsoft made a change to the photos app 🤔
