### ISSUE TITLE
Feature: Add Everything search engine

### ISSUE THREAD

**Issue by LolBaum** [files-community/Files#15759]
### What feature or improvement do you think would benefit Files?

I would suggest to add the everything (by Voidtools) file search engine to Files to allow users to search for files way faster.
The windows default search is very slow and so is Files.
When I want to locate a certain file Win File Explorer and Files, both weren't able to show me a result in less than 10 seconds (and Files took even longer).
Everything is able to locate the same file almost instantly.

I've seen some Repos that integrate Everything and could be used as reference for that:
[EverythingToolbar](https://github.com/srwi/EverythingToolbar)
[EverythingPowerToys](https://github.com/lin-ycv/EverythingPowerToys)

### Requirements

- performance improvements for file searches
- any file should be located very fast (like when using `everything`)

### Files Version

3.5.0.0

### Windows Version

10.0.22631.3737

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #5845 . You can check there or click subscribe in the right sidebar for updates.
