### ISSUE TITLE
BUG: Panel arrangement actions. F.3.5.6.0.

### ISSUE THREAD

**Issue by dracp** [files-community/Files#15758]
### Description

The new panel arrangement functions do not work correctly. All panel arrangement actions and confirmations work the opposite of what is indicated. Checking or selecting "..Vertical" displays in Horizontal and vice versa. 

### Steps To Reproduce

0. With vertical panels...
1. Open "Commands palette"...
2. Click on "Arrange panes horizontally" > **It does not work.**
3. Click on "Arrange panes vertically" > **Panels are arranged horizontally.**

![240704 Files_3 5 6 0_Error en Organización de Paneles](https://github.com/files-community/Files/assets/102802425/782ce98b-f92c-4d1e-b2d4-094bea778046)

### Requirements

Match actions to the function actually performed. Vertical>Vertical; Horizontal>Horizontal 

### Files Version

3.5.6.0

### Windows Version

10.0.22631.3810

### Log File

-

**Comment by yaira2** [comment]
The actions are purposely worded as "arrange" and not split. You can also refer to the icon for a visual on how the panes will be arranged.

**Comment by yaira2** [comment]
This does highlight the fact that the command palette doesn't display icons, but we hope to add icons in the future.

**Comment by yaira2** [comment]
We'll continue monitoring this area for further feedback, but at the moment, it seems that the majority of users prefer the current wording.
![image](https://github.com/files-community/Files/assets/39923744/7f51d0aa-9162-4fff-a5db-76ebea3c43af)
