### ISSUE TITLE
Unable to Copy-Paste

### ISSUE THREAD

**Issue by blunweon** [files-community/Files#15757]
### Description

Hi, recently I was attempting to backup my C:\ as I was planning to reinstall Windows.

I then tried to copy-paste the entire C drive into my other hard drive in order to be able to have a view of whatever apps and files I had after I reinstalled Windows. While using Files to copy-paste into my other hard drive, it got stuck on "Processing" after awhile.

![image](https://github.com/files-community/Files/assets/169746148/bb417fa0-1f7d-4f97-978b-601b9a909834)

Being puzzled, I cancelled (which took a long time and still did not manage to cancel, I had to kill the process), and then tried Windows' native File Explorer and managed to start the process. I then noticed that there were roadblocks with trying to copy-paste the entire C drive due to permissions and temporary files. With Windows' File Explorer, there were confirmation dialog boxes to "Try Again", "Skip" or "Replace All", however, with Files, I found that it did not prompt me for those dialogs.

![image](https://github.com/files-community/Files/assets/169746148/b1ff9fa9-edba-417a-9ffe-76b30ba0b44b)

### Steps To Reproduce

1. Attempt to Copy & Paste entire boot drive to another hard drive.
2. Does not complete/Hangs on "Processing".
3. Attempt to Copy & Paste using native Windows File Explorer.
4. Encounter roadblock with copy-paste process.

### Requirements

Confirmation dialog box for "Try Again", "Skip", or "Replace All" for Files akin to Windows' native File Explorer.

### Files Version

3.5.0.0

### Windows Version

10.0.22631.3810

### Log File

[debug.log](https://github.com/user-attachments/files/16092097/debug.log)

**Comment by 0x5bfa** [comment]
Thanks for the report.

Unfortunately, due to the current codebase, we are not able to provide a way to skip, skip all, try again and pause. We have a request on Pause #14929.
@Josh65-2201 do you think we can merge into your issue?

**Comment by 0x5bfa** [comment]
Being stuck on processing when the operation goes through an error is an issue and we should fix that.
But we’re working on much bigger things (it’s still being planned), to re-create a whole storage access/operations with a well-abstracted architecture (`#8974`) to be able to do them with various file systems. When we implemented storage accessing methods we didn’t plan to create this modern status center.

**Comment by Josh65-2201** [comment]
The processing items part is likely Files doing the discovering phase since there are thousands of Files on the C drive and just not showing it. We're tracking this in #14057. You can check there or click subscribe in the right sidebar for updates.

**Comment by Josh65-2201** [comment]
@0x5bfa Files does have an in use and dialog with try again and cancel (Really acts like skip) it should show for all files it couldn't do at the end of an operation
![image](https://github.com/files-community/Files/assets/26977075/4cdec334-9082-49e7-ad25-903f0e316e42)

**Comment by Josh65-2201** [comment]
This is most like #15390 were going to continue tracking there.

**Comment by yaira2** [comment]
Processing can take a while, the issue Josh pointed to is to show the progress while the items are being processed.

**Comment by yaira2** [comment]
If there was an error while processing, I'm pretty sure it would display an indicator.
