### ISSUE TITLE
Confirmation Dialog box for folder drag & drop

### ISSUE THREAD

**Issue by Toneking77** [files-community/Files#15750]
### What feature or improvement do you think would benefit Files?

In Microsoft File Explorer, I have (more than a few times) accidentally dragged a folder and dropped it on top of another folder.  It happens so fast, I didn't know where the "missing" folder ended up.  

This feature request is for a User selectable option.  To prevent accidental drag & drop of a Folder by having a Confirmation Dialog box when dragging a folder.  Something like:  "Are you sure you want to merge these two Folders?"

I searched but didn't find this here in the Issues section.  

### Requirements

- This proposed Feature would prevent accidental merging of Folders by drag & drop.
- Would require a User selectable option
- Would need a Confirmation Dialog box
- 

### Files Version

3.5.4.0

### Windows Version

10.0.22631.3810

### Comments

Thank you for considering this request.

**Comment by yaira2** [comment]
Thank you so much for sharing your feedback. Having encountered this frustrating behavior in File Explorer myself, I completely understand where you're coming from.

With that in mind, the drag & drop functionality in Files is designed to be less sensitive by default, and personally, I haven’t experienced this problem during my use. Could you please clarify if you’ve encountered this issue within Files itself, or are you suggesting improvements based on past experiences with File Explorer?

**Comment by Toneking77** [comment]
Thank you for the follow-up.

I'm suggesting improvements based on my past experiences with File Explorer.

Thanks again!

**Comment by yaira2** [comment]
Thanks for the response, have you had this issue in Files?

**Comment by Toneking77** [comment]
I don't think so.  I apologize for the lame answer... I'm pretty sure it was just File Explorer and I assumed it was an issue in Files as well.  Again, I apologize!

**Comment by yaira2** [comment]
It's all good 🙂 

Make sure to reach out if you have additional feedback.
