### ISSUE TITLE
Bug: Crash when clicking on the Explorer icon

### ISSUE THREAD

**Issue by Ultra119** [files-community/Files#15761]
### Description

Crashes when clicking on the Explorer icon more than once, with the "Set Files as the default file manager" option enabled.

### Steps To Reproduce

1. Turn on "Set Files as the default file manager" 
2. Close Files
3. Click on the Explorer twice or more

### Requirements

- Fix Files crash when clicking on the Explorer icon more than once with the "Set Files as default file manager" option enabled

### Files Version

3.5.6 / 3.5

### Windows Version

10.0.22631

### Log File

[debug.log](https://github.com/user-attachments/files/16103155/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report. The log doesn't show any crash errors.
- What explorer icon do you mean? Is it a shortcut to Windows File Explorer on the desktop or the recycle bin/my computer icon
- Are you able to open Files normally from the start menu?

**Comment by Ultra119** [comment]
> Thanks for the report. The log doesn't show any crash errors.
> 
> * What explorer icon do you mean? Is it a shortcut to Windows File Explorer on the desktop or the recycle bin/my computer icon
> * Are you able to open Files normally from the start menu?

I apologize for the understatement. Above, I was referring to opening through the Windows Explorer icon on the taskbar. But the same happens with any Explorer-related icon on the desktop, including the Recycle bin. A black Files window opens for a split second and then disappears

**Comment by 0x5bfa** [comment]
It’s weird that the log has nothing to indicate.
Could you try to find Files app from `Windows logs` > `Application` > sort by `Source` > `.NET Runtime` in Event Viewer?

**Comment by Ultra119** [comment]
> It’s weird that the log has nothing to indicate. Could you try to find Files app from `Windows logs` > `Application` > sort by `Source` > `.NET Runtime` in Event Viewer?

[event logger.txt](https://github.com/user-attachments/files/16117405/event.logger.txt)

**Comment by 0x5bfa** [comment]
Nice!

@Ultra119 It looks like it’s crashing when checking background image from the INI file. Could you paste the file here?
