### ISSUE TITLE
Bug: Toolbar extract text not shown correctly with a small window width

### ISSUE THREAD

**Issue by Ocean-View-Games** [files-community/Files#15767]
### Description

The extract option is labled "E" when you resize your window down and the menu bar is reduced in size causing the "..." button to appear

![image](https://github.com/files-community/Files/assets/122894754/84e96ad5-838f-4ffc-bd32-360d768a3150)

### Steps To Reproduce

1. Resize window down that the menu bar has a "..." option
2. Select a zip folder
3. Click the "..." 

Notice extract is labled "E"

### Requirements

Fix Extract label on context menu

### Files Version

3.5.0.0

### Windows Version

1000.22700.1020.0

### Log File

[debug.log](https://github.com/user-attachments/files/16111356/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by 0x5bfa** [comment]
Isnt this the same as https://github.com/files-community/Files/issues/10291?

**Comment by Josh65-2201** [comment]
Yes, we can continue tracking there.
