### ISSUE TITLE
Missing elements in context menu

### ISSUE THREAD

**Issue by sho9029** [files-community/Files#15769]
### Description

"Open In Terminal" and "Open with Code (Insiders)" in explorer.exe are missing in Files.

context menu in Files
![files](https://github.com/files-community/Files/assets/49068710/3bfc631d-ec14-4008-a7c1-38c66913aba3)

context menu in explorer.exe
![explorer_1](https://github.com/files-community/Files/assets/49068710/e8539c43-cb28-421d-b1f5-6fe8ab47880d)
![explorer_2](https://github.com/files-community/Files/assets/49068710/b18db317-ba44-44dd-9f72-1c7f2e234b4a)

### Steps To Reproduce

1. Install vscode (insiders)
2. Open the context menu in Files

### Requirements

"Open In Terminal" and "Open with Code (Insiders)" are displayed.

### Files Version

3.5.6.0

### Windows Version

10.0.26100.1000

### Log File

[debug.log](https://github.com/user-attachments/files/16117092/debug.log)

**Comment by 0x5bfa** [comment]
Thank you for the feedback.

We’re tracking on in #8251. At the moment, we are not able to support this new type of context menu because Windows doesn't disclose its querying API to the public. We’ve revealed some but not completely, while the API to create the menu in this new type of menu is disclosed.

**Comment by sho9029** [comment]
My understanding is that the third photo is the legacy context menu, but is it not?

**Comment by Josh65-2201** [comment]
While it is the older version it still includes the new API items

You can open terminal using the keyboard shortcuts https://files.community/docs/customize-settings/actions#:~:text=%22Ctrl%2B%2C%22-,Open%20Terminal,-Opens%20folder%20in or typing `cmd <path>` into the path bar
