### ISSUE TITLE
Code Quality: Add an unit test for Files.App

### ISSUE THREAD

**Issue by 0x5bfa** [files-community/Files#15762]
### Description

My long-long-term plans have been to remove Utils namespace and unify with injectable Services via Ioc and thus to create unit test in terms of managed codebase.

The last try to create WinUI unit test was failed for some reasons.
When I referenced 'Files.Package' project it said unrecognizable platform identifiers, when I referenced 'Files.App' project it said it's not targetable iirc.

@marcelwgn I saw your Visual Studio template for WinUI unit tests, do you happen to know how to reference Files.App correctly and execute tests?

### Concerned code

- Whole Files.App

### Gains

- Better maintainable experience for us

### Requirements

- Have tests for Files.App.Services
- Have tests for some controls in UserControls such as ThemedIcon (we have an ongoing PR and it holds test window but it's not ideal at all.

**Comment by marcelwgn** [comment]
Yeah referencing a WinUI 3 app from another WinUI 3 app is not possible (or I don't know what would help). It seems we are not the only people with that issue: https://github.com/microsoft/microsoft-ui-xaml/issues/6279#issuecomment-1745324868

**Comment by 0x5bfa** [comment]
Thank you for the info. I’ll close as it requires WinUI effort…
