### ISSUE TITLE
Using search will only search open directory, no sub-directories.

### ISSUE THREAD

**Issue by rivahere** [files-community/Files#15768]
### Description

When in a folder and using search, it will not show any results for sub-directories.

### Steps To Reproduce

Just use search in a directory.

### Requirements

Recursive searching.

### Files Version

3.5.0.0

### Windows Version

Windows 11 Pro 22631.3810

### Log File

[debug.log](https://github.com/user-attachments/files/16113146/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, you have to press enter to do a full search, as just typing will search the current folder using a quicker method.

**Comment by yaira2** [comment]
@rivahere typing without pressing enter will filter the current directory (as Josh mentioned), can you confirm if pressing enter starts a regular search?
