### ISSUE TITLE
Any way to install it on Win 8.1 or rebuild for it? 

### ISSUE THREAD

**Issue by xbliss** [files-community/Files#15770]
### What feature or improvement do you think would benefit Files?

Any way to install it on Win 8.1 or rebuild for it? 

### Requirements

Any way to install it on Win 8.1 or rebuild for it? 

### Files Version

x

### Windows Version

8.1.1

### Comments

Any way to install it on Win 8.1 or rebuild for it?

**Comment by yaira2** [comment]
Unfortunately not, the WinAppSdk framework is only supported from Windows 10 onwards.
