### ISSUE TITLE
Bug: Column layout scrolls to first row when clicking

### ISSUE THREAD

**Issue by Lihael** [files-community/Files#15776]
### Description

When in column view, left clicking in empty space of any column causes a shift back to the first column until the click is lifted. Right clicking any file, folder, or empty space to open a context menu does the same thing until the context menu fully loads. 

Related to this issue: https://github.com/files-community/Files/issues/15713

Video of this behavior in action: https://github.com/files-community/Files/assets/41993141/01e2386f-0dbd-461f-8198-75e4a77f8d11

I'm not completely sure that the left click behavior is necessarily a bug. If it is intended, I think there should be an option to disable it as its quite annoying personally on top of being the cause of the right click behavior. 

### Steps To Reproduce

1. Use column view
2. Left click in empty space in any column. 
3. Or, right click any file/folder or empty space in any column

### Requirements

Left clicking empty space in a column should cause a change in directory to the folder representing the column that is clicked, not the first directory. 

Right clicking should open context menu of what is right clicked without shifting back to first column.

### Files Version

3.5.0.0

### Windows Version

10.0.22631.3810

### Log File

[debug.log](https://github.com/user-attachments/files/16128595/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
It seems to me almost as if the column is reopening and that's causing the scrolling.

**Comment by picknassaro** [comment]
I have this issue too, I can take a screen recording if it would help

**Comment by hiwer** [comment]
@yaira2 @Josh65-2201 

Hi there,
May I ask when this annoying bug will be fixed? It's really making my work life harder :D. Thanks for your response!

**Comment by Josh65-2201** [comment]
There is no timeline for when this will be fixed. As Files is community developed people pick what they want to work on.

**Comment by yaira2** [comment]
This issue is on the todo list, but as Josh mentioned, we usually don't offer specific timelines since some issues can be more challenging than others. However, Files is open source, and we always encourage developers to contribute if they have a solution or improvement.

**Comment by yaira2** [comment]
Thank you @gave92 for contributing a fix for this issue. The fix will be included in the next update.
