### ISSUE TITLE
Add note feature and support for third-party right-click menu 

### ISSUE THREAD

**Issue by 5418541** [files-community/Files#15774]
### What feature or improvement do you think would benefit Files?

could you please add a notes column to the detailed information view? It would be very convenient to have the ability to modify file notes via the right-click menu, especially for distinguishing between folders in different languages. This is one of the reasons I prefer third-party file managers over the system’s, as the remark feature in the system manager is not user-friendly.

Additionally, I noticed that the right-click menu functionality of Bandzip, a compression tool, doesn’t work within the Files application. Is it possible to add support for this feature, as it is available in the system file manager?

### Requirements

Add a remarks column to the detailed information list view.
The right-click menu can modify remarks.
The right-click menu can display the functions of Bandzip

### Files Version

3.5.0.0

### Windows Version

10.0.19044.2251

### Comments

![image](https://github.com/files-community/Files/assets/76186985/58d1bee9-8f6e-4cb2-8f77-132ef0bbd3c0)

**Comment by Josh65-2201** [comment]
Thanks for the feedback do you mean the same comments section that on Windows File Explorer?

**Comment by 5418541** [comment]
> 感谢您的反馈，您是指 Windows 文件资源管理器中的同一评论区域吗？

是的，Windows管理器中，有一个备注的功能，可以通过在详细信息中显示，但是不能直接修改

**Comment by 5418541** [comment]
![image](https://github.com/files-community/Files/assets/76186985/3af633e7-fb3e-42a4-b9b2-ebeeae042a67)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #8366 and Bandzip support #8251. You can check there or click subscribe in the right sidebar for updates.
