### ISSUE TITLE
use command line args to specify the start path

### ISSUE THREAD

**Issue by yeungchie** [files-community/Files#15775]
### What feature or improvement do you think would benefit Files?

In order to better replace `explorer`, it is hoped that it can support the same behavior as `explorer`:

```
explorer .
```

It will open the `explorer` in the current directory.

### Requirements

```
files [DIR]
```

`DIR` is optional argment and it controls the starting path for `files`. If it is not specified, `files` will start with the default path.

### Files Version

3.5.0.0

### Windows Version

10.0.19045.3930

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #14381. You can check there or click subscribe in the right sidebar for updates.
Files also already support opening with a path using `files.exe "<path>"`
