### ISSUE TITLE
Shrink path components when it can't be fit

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#1577]
**Is your feature request related to a problem? Please describe.**
Not really. In File Explorer. the path shown is automatically when it's too large to display in a way that the directory name is always shown. Files UWP doesn't do this and instead cuts the full path.

**Describe the solution you'd like**
The last portion should be always visible regardless of the screen size and the front portion can be trimmed if the path doesn't fit inside.

**Describe alternatives you've considered**
None.

**Additional context**

![FilesUWPGif_Trim](https://user-images.githubusercontent.com/45227503/88472568-cdb8aa00-cf31-11ea-9214-098c02cb9259.gif)

**Comment by d2dyno1** [comment]
Instead of cutting, scroll to the end?

**Comment by yaichenbaum** [comment]
@d2dyno1 That's the solution when ending up going with.
