### ISSUE TITLE
Can't return to default file explorer.

### ISSUE THREAD

**Issue by quo1** [files-community/Files#15778]
### Description

When I tried to install the default program, my explorer stopped running. Next, I copied the registry file (shown [here](https://github.com/files-community/Files/issues/8173)) and it got even worse - when you start Explorer, the desktop restarts

### Steps To Reproduce

1. set Files as default
2. use registry file from the link

### Requirements

how to return this???

### Files Version

3.5.0.0

### Windows Version

10.0.19044.19044

### Log File

i cant use explorer

**Comment by Josh65-2201** [comment]
Thanks for the report, Open Files settings > Advanced > turn Set as default off > Restart your computer

**Comment by quo1** [comment]
I have already reinstalled it many times. The checkbox is disabled. Maybe it's the registry?
The registry file that I installed:
```
Windows Registry Editor Version 5.00

; Revert Default (new)
[HKEY_CLASSES_ROOT\Folder\shell\explore]
"LaunchExplorerFlags"=dword:00000018
"MultiSelectModel"="Document"
"ProgrammaticAccessOnly"=""

[HKEY_CLASSES_ROOT\Folder\shell\explore\command]
@=-
"DelegateExecute"="{11dbb47c-a525-400b-9e80-a54615a090c0}"

[HKEY_CLASSES_ROOT\Folder\shell\open]
"MultiSelectModel"="Document"

[HKEY_CLASSES_ROOT\Folder\shell\open\command]
@=hex(2):25,00,53,00,79,00,73,00,74,00,65,00,6d,00,52,00,6f,00,6f,00,74,00,25,\
  00,5c,00,45,00,78,00,70,00,6c,00,6f,00,72,00,65,00,72,00,2e,00,65,00,78,00,\
  65,00,00,00
"DelegateExecute"="{11dbb47c-a525-400b-9e80-a54615a090c0}"

; Revert Default (old)
[HKEY_CURRENT_USER\SOFTWARE\Classes\Directory\shell]
@=-

[-HKEY_CURRENT_USER\SOFTWARE\Classes\Directory\shell\openinfiles]

; Revert Win+E
[-HKEY_CURRENT_USER\SOFTWARE\Classes\CLSID\{52205fd8-5dfb-447d-801a-d0b52f2e83e1}]
```

**Comment by quo1** [comment]
Or do I need to enable and disable the checkbox and then restart?

**Comment by Josh65-2201** [comment]
If it's already off then turn it off and on again. The registry file works for me when turning it on or off.

**Comment by quo1** [comment]
oh, when I turned on the checkbox, Files was closed with message on a blue background:
"There is a problem with Files."

**Comment by Josh65-2201** [comment]
Can you send a screenshot

**Comment by quo1** [comment]
it's on russian :) But i can
![image](https://github.com/files-community/Files/assets/73030723/d3653ced-e324-43f3-80c1-a504058c8d52)

**Comment by Josh65-2201** [comment]
Did you restart and does Windows File Explorer work now?

**Comment by quo1** [comment]
Oh, I'm sorry, please. I did not restart the computer after checking the box. Now, after restarting the computer, File Explorer starts if you open it through the shortcuts "This computer" or "File Explorer". Thanks! But when you start using the Win + E keyboard shortcut and through the quick access toolbar, errors pop up:
1. from quick access toolbar. "There is no application associated with this file to perform this action. Install the app"
![image](https://github.com/files-community/Files/assets/73030723/d00db025-f860-446e-9b2e-8ce391fca3da)
2. if using win + e. "The application was not found"
![image](https://github.com/files-community/Files/assets/73030723/60abfa32-3b53-4e55-ac3c-ddd94d7dc4dd)

**Comment by Josh65-2201** [comment]
Try running this file https://raw.githubusercontent.com/files-community/Files/main/src/Files.App/Assets/FilesOpenDialog/UnsetFilesAsDefault.reg

**Comment by quo1** [comment]
Do I have to install the whole file?

**Comment by Josh65-2201** [comment]
Yes, it the unset as default registry file.

**Comment by quo1** [comment]
Everything is fine, thank you very much! I will still use your explorer!

**Comment by Josh65-2201** [comment]
Great to hear and thanks for still using Files.
