### ISSUE TITLE
Bug: Files app background flickers when using a GIF

### ISSUE THREAD

**Issue by AffirmativeGuy** [files-community/Files#15779]
### Description

Whenever I use any animated(gif) background as my background in my files app, it starts flickering randomly.

### Steps To Reproduce

1 - Add a gif background
2 
![My background which found on google](https://github.com/files-community/Files/assets/100131691/d5a27229-30c8-4bae-80b3-3049d9d56561)
- Randomly wait for the error

### Requirements

A gif background

### Files Version

3.5.0.0

### Windows Version

10.0.19045.4598

### Log File

[debug.log](https://github.com/user-attachments/files/16132123/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
@AffirmativeGuy thanks for the report. Support for GIFs is available as an afterthought, but it’s not the primary intended use of the feature. The feature is mainly designed for static images, but all that being said, we can try to take a further look if you can upload a screen recording of the actual issue.

**Comment by AffirmativeGuy** [comment]
oh ok thanks for your time!

**Comment by yaira2** [comment]
@AffirmativeGuy although it's not the way we designed the feature, it wouldn't hurt to take a closer look. Do you think you can upload a screen recording?

**Comment by AffirmativeGuy** [comment]
Yeah sure

**Comment by AffirmativeGuy** [comment]
Well, that's a weird bug, whenever i record it, it just woudn't come

**Comment by yaira2** [comment]
It looks like this limitation is here to stay. GIFs aren’t really designed to be used as app backgrounds in an endless loop, as this puts extra strain on the system. I understand this isn’t the response you were hoping for, but we believe in being transparent.
