### ISSUE TITLE
The right-clicking panel is transparent

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [files-community/Files#15782]
### Description

![image](https://github.com/files-community/Files/assets/44057002/f52ea5d0-2c73-49c6-8653-fccfd7df6080)
When right-clicking on anything, the panel that pops up is transparent which greatly impacts visibility. A lot of panels are like that actually, even the one when you try to copy the versions, where it prompts you the Files version or Windows version
Maybe restarting Files will fix this, but in case I need to try things for debugging I won't restart it for now

### Steps To Reproduce

1. Right click on something

### Requirements

The panel shouldn't be transparent

### Files Version

3.5.6.0

### Windows Version

10.0.22631.3810

### Log File

[debug.log](https://github.com/user-attachments/files/16142586/debug.log)

**Comment by yaira2** [comment]
Thanks for the report, it looks like the acrylic backdrop isn't working. Can you do me a favor and check if the menus in the WinUI 3 Gallery have the same issue? https://www.microsoft.com/store/productId/9P3JFPWWDZRC?ocid=pdpshare

**Comment by TheWonderfulTartiflette** [comment]
On the "System Backdrops (Mica/Acrylic)" tab, when I press any button to "Create Window..." it works fine

**Comment by yaira2** [comment]
The window backdrop is different than the in app acrylic, can you check the menus in the WinUI Gallery?

**Comment by TheWonderfulTartiflette** [comment]
Yes, I said that I also checked the WinUI Gallery backdrop, on the "System Backdrops (Mica/Acrylic)" tab, when I press any button to "Create Window..." it works fine, it's not transparent. You're talking about this, right ? 
![image](https://github.com/files-community/Files/assets/44057002/16d23d1b-bb75-4ab8-a400-29030b8a81cf)

**Comment by Josh65-2201** [comment]
No, that's the background. Check in Menu flyout and Command bar flyout section

**Comment by TheWonderfulTartiflette** [comment]
My bad. Well, they all work fine 
![image](https://github.com/files-community/Files/assets/44057002/660060c2-13c5-4974-9d05-53f257e7d6a2)
![image](https://github.com/files-community/Files/assets/44057002/444095c1-1dc2-430a-abde-3f0198468162)

**Comment by 0x5bfa** [comment]
I believe the WinAppSdk package is broken or something similar.
File Explorer had the same issue but it had been fixed a while ago.
Could you reinstall the app (before that please make sure to retain your user settings from Settings > Advanced. > Export and import after that)

**Comment by 0x5bfa** [comment]
Thanks for checking

**Comment by yaira2** [comment]
> Well in the end restarting the Files app worked, do I really need to reinstall it then ?

I don't think reinstalling would have done anything regardless, anyways, happy to hear it's working now 🙂
