### ISSUE TITLE
Option to set default IDE

### ISSUE THREAD

**Issue by Polarzincomfrio** [files-community/Files#15789]
### What feature or improvement do you think would benefit Files?

Personally, i love to use jetbrains ide's and code editors, only being able to open VS Code and Visual Studio 20XX is a oversight, this could be done with the use of the popup that windows uses for the "Open With..." functionality, which is shown in the annexed image.
![image](https://github.com/files-community/Files/assets/69534455/57ab5937-de3a-437e-8bc5-109fd0850de6)

### Requirements

- This proposal will enable developers to open their desired IDE's and Code Editor's through the Files app

### Files Version

3.5.0.0

### Windows Version

10.0.22631.3880

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #12857 . You can check there or click subscribe in the right sidebar for updates.
