### ISSUE TITLE
How can I move files/folders?

### ISSUE THREAD

**Issue by TheMikeyRoss** [files-community/Files#15785]
### Description

If I click and drag a file to an external had drive i get an error that the file is too large to copy.

I can't left click and drag for some reason

There's no option to move items to external hard drive

### Steps To Reproduce

try to **move** a file/folder to an external hard drive

### Requirements

a way to move files/folders to external hard drive

### Files Version

3.5.0.0

### Windows Version

Windows 10 Pro Build: 19045.4591

### Log File

[debug.log](https://github.com/user-attachments/files/16157722/debug.log)

**Comment by 0x5bfa** [comment]
@TheMikeyRoss Does the instruction above helped you fix?

**Comment by TheMikeyRoss** [comment]
Yes but the right click + drag still doesn't work

**Comment by Josh65-2201** [comment]
Does it work in Windows File Explorer? If not try using cut (CTRL + X) and paste (CTRL + V)

**Comment by yaira2** [comment]
Is the external drive formatted as NTFS?

**Comment by TheMikeyRoss** [comment]
the "size too large" issue was resolved by following the link provided by @zaaakher ,

But I still can't drag anything with a right click, regardless of the file size. dragging with a right click doesn't seem to work at all

**Comment by yaira2** [comment]
Did you see this prompt when launching Files?
![image](https://github.com/files-community/Files/assets/39923744/87a20ca6-d9cc-4bb6-a098-0e1cbf0842e3)

**Comment by TheMikeyRoss** [comment]
> Did you see this prompt when launching Files?

Nope. 
And for good measure I opened files as an admin and I can't drag & drop with neither right nor left click (just as the prompt states).

I'm not running files as an admin, I'm running it as a normal user. And I can drag and drop with a **left+click** and that works fine, but it just copies files. And I want to move files by right-click and drag but when  nothing is dragged when I do **right-click**+drag

**Comment by yaira2** [comment]
My apologies, I missed the part about right click. This isn't supported yet but it's on our todo list #1396.

**Comment by TheMikeyRoss** [comment]
Awesome, thanks @yaira2 @zaaakher 👍
