### ISSUE TITLE
Bug: Per directory layout preferences reset to details when Files updates

### ISSUE THREAD

**Issue by andrew-james-heard** [files-community/Files#15797]
### What feature or improvement do you think would benefit Files?

Each time Files Preview is (silently) upgraded (is there a setting to turn it off?) I find the layout for each directory I have set (details/ list/ tiles/ grid), and column widths (for details) revert to the Details layout. Please preserve each layout after the upgrade. It is a big time waster having to remember (often forget) each layout & change back.

### Requirements

- hopefully have said enough?

### Files Version

3.5.6.0

### Windows Version

11 23H2

### Comments

apologies if already requested; did a cursory search w/o success

**Comment by Josh65-2201** [comment]
Thanks for the feedback,
- Can you please upload (Do not copy and paste content) the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.
- Do you have Files settings > Layout > Sync layout and sorting preferences across directories enabled?

**Comment by andrew-james-heard** [comment]
thanks Josh
sync is disabled

ohh BTW since my original post, the directory > Layout > Show file extensions, is now non-directory specific, changing it for the current directory changes it for all directories, so frustrating. Is that intentional?
[debug.log](https://github.com/user-attachments/files/16203802/debug.log)

**Comment by Josh65-2201** [comment]
Yes, show file extensions has always been globally applied.

**Comment by andrew-james-heard** [comment]
that's weird - could've sworn it was per directory; somewhat misleading having it displayed along with directory-specific layout settings; would it be better in global settings > Layout?

**Comment by Josh65-2201** [comment]
The layout picker isn't for per directory only. It's there to quickly change folder related settings and changes if you have Sync layout and sorting preferences across directories enabled.

**Comment by andrew-james-heard** [comment]
> Per directory layout preferences reset to details when Files updates
thanks Josh - I won't be updating until it's fixed then; but how to disable auto-update?

**Comment by Josh65-2201** [comment]
You can't disable auto update other then blocking Files from internet access. You would have to find a program to do that.

**Comment by andrew-james-heard** [comment]
OK, thanks Josh. Are the directory layouts in some form of text file that could be manually hacked/ restored after a auto update until the fix is rolled out?

**Comment by Josh65-2201** [comment]
Files currently store them in the registry so you can export the folder labeled as Files. @hez2010 would have to tell you what the path is as I'm unable to find it.

**Comment by andrew-james-heard** [comment]
Thanks Josh. Nothing obvious @ Computer\HKEY_CURRENT_USER\Software.

**Comment by andrew-james-heard** [comment]
just discovered have been auto updated to 3.5.15 & lost all my directory layout preferences again i.e. reset back to Details layout ;-( hoping @hez2010 can tell me where in the registry these values are saved

**Comment by 0x5bfa** [comment]
Registry is disabled in our application data folder. `%LOCALAPPDATA%\Packages\49306atecsolution.FilesUWP*`

As you can tell, load registry.dat (somewhere in the folder, I forgot) go to the FileTags node.
![image](https://github.com/user-attachments/assets/6d20e4f3-d8c5-4cff-b66c-0f4e69654da9)

**Comment by andrew-james-heard** [comment]
Thanks, but I don't have Computer\HKEY_CURRENT_USER\Software\Files Community* on my PC, or anything like it,
and I don't see any relevant file in %LOCALAPPDATA%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t
I'll just wait for the fix. I'm sure others must be having the same frustration - price of running the Preview version.

**Comment by hez2010** [comment]
> just discovered have been auto updated to 3.5.15 & lost all my directory layout preferences again i.e. reset back to Details layout ;-( hoping @hez2010 can tell me where in the registry these values are saved

The registry is virtualized, so it is package scoped, you won't be able to find it using regedit in regular ways. 
To view the registry values of Files, you need to install [Hover](https://www.advancedinstaller.com/hover.html), which is a tool to allow you inspect package content.
After installing Hover, launch it and select Files from the list on the left, then click `Regedit` to open registry editor for the package you selected.
Then you will be able to inspect the registry values of Files by navigating to `Computer\HKEY_CURRENT_USER\Software\Files Community`.

**Comment by andrew-james-heard** [comment]
Thanks @hex2010 - that seems to work.

**Comment by yaira2** [comment]
I can reproduce this as well

**Comment by yaira2** [comment]
A fix will be included in the next preview build.
