### ISSUE TITLE
Files 3.5 won't install on Windows 10

### ISSUE THREAD

**Issue by MikeBoardman47** [files-community/Files#15800]
### Description

I heard about the Files program a year or two ago and managed to install it successfully.
I have since tried to update it a number of times but it always fails with a message "Package failed updates, dependency or conflict validation".
I have uninstalled the original version in an attempt to resolve this, but without success.
I'm afraid the research I have done suggesting what might be wrong has only confused me more.
Can anyone suggest what I can do to sort this out?
Many thanks.
Mike

### Steps To Reproduce

Just try to install the download

### Requirements

Install successfully so that it can be used.

### Files Version

Files 3.5 (Not actually being used, as it won't install.)

### Windows Version

Windows 10 Enterprise 22H2 19045.4651

### Log File

I can't do this as it won't install to produce a log file.

**Comment by Josh65-2201** [comment]
Thanks for the report, can you try
1. Make sure Files is closed from the system tray
2. Open an admin PowerShell window (Windows default not PowerShell 7)
3. Run the below
```
Get-AppXPackage Files* | Remove-AppXPackage
```
4. Restart Windows and try install again

**Comment by MikeBoardman47** [comment]
Thanks for the reply.

 

I’ve tried that now, but the same result.

 

Do you have any further suggestions? If not, I’ll just give up.

 

Michael Boardman

**Comment by username-abhay** [comment]
Files 3.5 classic downloaded from the website does not installs on windows 10 says :
installation failed contact the vendor.
![image](https://github.com/user-attachments/assets/533f2f08-2a36-4d98-9092-342f9a86d77c)

**Comment by Josh65-2201** [comment]
You can try
1. Opening PowerShell as administrator
2. Run this command
```Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/stable/Files.Package.appinstaller```
3. See if Files is in the start menu all apps section

**Comment by dmitrymyl** [comment]
> You can try
> 
> 1. Opening PowerShell as administrator
> 2. Run this command
>    `Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/stable/Files.Package.appinstaller`
> 3. See if Files is in the start menu all apps section

That didn't help me &mdash; no Files in the Start menu

**Comment by MikeBoardman47** [comment]
Thanks for the suggestion.

 

I tried it and got the following result:

 

Add-AppxPackage : Deployment failed with HRESULT: 0x80073D19, An error occurred because a user was logged off.

Windows cannot install package Files_3.5.0.0_neutral_~_1y0xx7n9077q4 because a different package

Files_2.4.70.0_neutral_~_wvne1zexy08sa with the same name is already installed. Remove package

Files_2.4.70.0_neutral_~_wvne1zexy08sa before installing.

NOTE: For additional information, look for [ActivityId] d105c042-d814-0002-8091-06d114d8da01 in the Event Log or use

the command line Get-AppPackageLog -ActivityID d105c042-d814-0002-8091-06d114d8da01

At line:1 char:1

+ Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/s ...

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : NotSpecified: (https://cdn.fil...ge.appinstaller:String) [Add-AppxPackage], Exception

    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

 

It turns that Files 2.40.7 is on my PC, but does NOT show up in the list of installed programs. It will run, but I can’t see how it could be uninstalled!

 

Mike Boardman

**Comment by Josh65-2201** [comment]
Files is already installed according to that error message. The first message I sent should have uninstalled it, are you sure you did the instructions?

**Comment by dmitrymyl** [comment]
> @dmitrymyl did you get an error message in powershell?

No, but there was no success message as well

**Comment by dmitrymyl** [comment]
@Josh65-2201 but I also need to clarify that I am working on a corporate laptop (research institute), but have access to admin rights.

**Comment by yaira2** [comment]
> Thanks for the suggestion. I tried it and got the following result: Add-AppxPackage : Deployment failed with HRESULT: 0x80073D19, An error occurred because a user was logged off. Windows cannot install package Files_3.5.0.0_neutral_~_1y0xx7n9077q4 because a different package Files_2.4.70.0_neutral_~_wvne1zexy08sa with the same name is already installed. Remove package Files_2.4.70.0_neutral_~_wvne1zexy08sa before installing.

@MikeBoardman47 this can be resolved by following the steps listed [here](https://github.com/files-community/Files/issues/15800#issuecomment-2228316515). Make sure to let us know if you need further assistance 🙂

**Comment by JesseGuoX** [comment]
Same issure here: 
![image](https://github.com/user-attachments/assets/bc4b7777-8eb9-4c35-8d47-a344b6b975a7)
