### ISSUE TITLE
CommandBarFlyout Failed to Follow System Theme Change

### ISSUE THREAD

**Issue by Jack251970** [files-community/Files#15807]
### Description

The colour of the text in some menus of CommandBarFlyout does not adjust automatically when the Windows system theme switches between dark and light.

### Steps To Reproduce

1. Under light mode, set App theme to 'Default'.
2. Right click one item.

![image](https://github.com/user-attachments/assets/810bcbb2-1e6a-4202-b483-5292d18aba0f)
3. Don't close app, and change to dark mode.

![image](https://github.com/user-attachments/assets/29ddae2c-addc-4813-a972-19ade08d2711)

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.5.0.0

### Windows Version

Windows 11 23H2 (22631.3880)

### Log File

[debug.log](https://github.com/user-attachments/files/16249953/debug.log)

**Comment by yaira2** [comment]
Thanks for the report, this is a known issue with WinUI but Microsoft appears to have closed it due to inactivity. Please add a comment to let them know it's still an issue https://github.com/microsoft/microsoft-ui-xaml/issues/4970

**Comment by yaira2** [comment]
In the meantime, you can get the correct theme by restarting Files.
