### ISSUE TITLE
Last window size and position not remembered in some cases

### ISSUE THREAD

**Issue by soumyamahunt** [files-community/Files#1580]
**Describe the bug**
When last window closed for the app is a property window, in the next start up of the app, files-uwp opens with the size and position of property window instead of the main window's last size and position.

**To Reproduce**
1. Open files-uwp app.
2. Open properties for any folder.
3. Close the main window.
4. Close the properties window.
5. Relaunch files-uwp app.
6. See the error.

**Expected behavior**
App should remember only the main window's position and size and apply that when relaunched.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1903 18362.239
 - App version: v0.12.0

**Comment by yaichenbaum** [comment]
I suppose that closing any open property windows when the user closes the main app windows would be the correct action here.
