### ISSUE TITLE
軟件隨系統啓動時不加載已固定的文件夾

### ISSUE THREAD

**Issue by AisinGioroKiIoi** [files-community/Files#15816]
### Description

1. 軟件勾選了【在Windows啓動時打開files】選項，每次隨系統啓動後，不顯示已固定的文件夾。
2. 需要找到電腦右下角的系統托盤，退出，然後重新打開軟件，才能正常顯示已固定的文件夾。
3. 在兩臺PC上觀察均有該問題。

### Steps To Reproduce

如上

### Requirements

如上

### Files Version

3.5.0.0

### Windows Version

10.0.22631.3880

### Log File

[debug.log](https://github.com/user-attachments/files/16275256/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, We're tracking this in #15410 . You can check there or click subscribe in the right sidebar for updates.
