### ISSUE TITLE
There is still no drag and drop the pinned folder feature for four years

### ISSUE THREAD

**Issue by AyaseMitsukasa** [files-community/Files#15814]
I just search and found someone is requesting this basic feature in Oct 2020
Four years later there is still no such a thing just like the stock one
And this thing even sold on the ms store for 8 bucks, although u can grab the installer for free
But is it a joke?

**Comment by Josh65-2201** [comment]
There no timeline for any issues/requests and any updates will be posted on #15430. Adding the ability isn't as simple as changing a switch. You can however right click on one and click reorder.

Files is community developed for free and so people decide when and what they want to work on. Unfortunately there isn't many people working on Files so development is slower in general there nothing we can do about that. Files is also mainly free, the store is a way of donating to Files to keep paid services like the website going and doesn't have any extras compared to the site installers.

**Comment by yaira2** [comment]
I’d like to draw attention to our code of conduct. While we welcome discussions, the current tone of this issue isn’t conducive to a healthy conversation.

**Comment by yaira2** [comment]
Josh summarized it well, but let me elaborate a bit. Files is an open-source app with free support. Our ability to provide this service relies on the active involvement and support of the community. However, it’s essential to recognize that no one is entitled to anything.

Our contributors are volunteers who generously dedicate their time to enhancing features and assisting users. We encourage them to work on issues that interest them most, as this isn’t a paid job with assigned priorities.

While Files remains free, there are operational costs—such as Azure and Cloudflare—that need to be covered. That’s where the Store version comes in. Purchasing the Store version not only helps cover these expenses but also enables us to offer occasional code bounties.
