### ISSUE TITLE
Add support for changing which program a file opens in from the properties window

### ISSUE THREAD

**Issue by Rick-HM** [files-community/Files#1581]
Show which application opens the file, with a button to change the application
![Anotación 2020-07-26 180333](https://user-images.githubusercontent.com/61259627/88490570-88fd3500-cf6a-11ea-9e85-f67ce24754b5.png)

**Comment by Jaiganeshkumaran** [comment]
This is not open with, this is for changing the default application.

**Comment by ChihweiLHBird** [comment]
Maybe we can let this window pop up when clicking "open with"? It can does same thing (changing default app for the type of file).
![image](https://user-images.githubusercontent.com/43905414/88638033-cac3d380-d06f-11ea-8c35-0f88a9ea404d.png)

**Comment by yaichenbaum** [comment]
@Rick-HM does this have added value over the existing open with option that's in the context menu?

**Comment by Rick-HM** [comment]
@yaichenbaum For me from the properties window it feels a bit faster to change, actually it's only 1 step faster but in the end clicking "OK" to close the properties window doesn't feel annoying like having to close the file that was opened from the context menu, since when changing the program used from the context menu, the file will open.

Which one is better I suppose depends on what you will do after making the change, if you will **not** open the file it "feels" more comfortable from the properties window. If you will open the file at the end it is better from the context menu.

**Comment by yaichenbaum** [comment]
We don't have plans to implement this option. There are a couple reasons behind this decision
- The apis only allow us to change the default program when opening the file, this is not the behavior users expect from this option.
- Users can already change the default from the right click context menu (in fact, it takes the same number of clicks to do this)
- It would be out of place in the properties dialog, all other actions in the properties window are specific to the selected file whereas this option applies to the file type.
