### ISSUE TITLE
More Home Features

### ISSUE THREAD

**Issue by Aoan2011** [files-community/Files#15818]
### What feature or improvement do you think would benefit Files?

I think that there can be more widgets on the home page like weather and etc.

### Requirements

Add more features

### Files Version

3.5.9.0

### Windows Version

10.0.22635.3930

**Comment by 0x5bfa** [comment]
Thanks for the feedback.

What widgets specifically do you think it should have?

**Comment by Aoan2011** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by yaira2** [comment]
@Aoan2011 Thank you for your feedback. While the idea of adding a weather widget is something we've joked about in the past, it ultimately falls outside the scope of our plans for Files and is not planned for implementation. However, the good news is that Windows 11 offers multiple ways to access weather information, including through the lockscreen, taskbar, and the dedicated weather app, ensuring comprehensive coverage in this area.

**Comment by Aoan2011** [comment]
Thanks
