### ISSUE TITLE
open a folder from desktop in new window (setting)

### ISSUE THREAD

**Issue by hhielscher** [files-community/Files#15819]
### What feature or improvement do you think would benefit Files?

Current behavior: When I double click a folder on the desktop the folder opens in a new tab.
Expected behavior: The folder gets opened in a new window
Setting files and folders / opening items / open folders in new tab is disabled

### Requirements

- This proposal will accomplish to open folders from the desktop in a new window

### Files Version

3.5.0.0

### Windows Version

10.0.19045.4651

**Comment by Josh65-2201** [comment]
Thanks for the feedback, you can turn off the option in Files settings > General > Startup settings > Open tab in existing instance when opening Files from another app

**Comment by hhielscher** [comment]
None of the options in startup settings made a difference. If I open two folders from the desktop the second folder is always opened as a tab.

**Comment by Josh65-2201** [comment]
I can't reproduce that behaviors with the settings I said turned off.
- Are you opening both of them at the same time?
- Can you send a screenshot of your startup settings

**Comment by hhielscher** [comment]
There are several issues here:
1. I didn't see the toggle "open tab in existing instance ..." because I didn"t know there were hidden settings that are collapsed by default --> so this a discoverability issue and therefore another bug
2. with startup settings to "continue where you left off" it still looks as if the folder gets opened in a new tab, but instead a new window gets opened above the old window (at the same location, with the same size) and the tabs from the original window get restored and the tab is added.
I guess this is intentional since if you open a new window with Ctrl-N the tabs of the old windows are duplicated as well. I thought that "continue where you left off"  works like a session manager that restores your previous windows and tabs after a restart. --> so I guess it works as intended
