### ISSUE TITLE
BUG: Cut out Files

### ISSUE THREAD

**Issue by Sergey842248** [files-community/Files#15812]
### Description

If I select a file and click Strg + X nothing happens, but if I make a right click and choose cut out, everything works normal and then Strg + X works but only after I done it manually with the right click.

### Steps To Reproduce

1. Select a file
2. Press Strg + X (nothing will happen)
3. right click
4. choose Cut out (the scissors)
5. Paste it anywhere
6. press Strg + X at an other file (it will work for the whole session)

### Requirements

Fix crash that occurs when cutting out files

### Files Version

3.5.0.0

### Windows Version

10.0.22635.3930

### Log File

[debug.log](https://github.com/user-attachments/files/16260460/debug.log)

**Comment by 0x5bfa** [comment]
Thanks for the feedback.

- Are you facing at a crash of the application during Cut operation?
- When you do Ctrl+X, the selected items would be dimmed as File Explorer does?

**Comment by Sergey842248** [comment]
1. Sry, meant bug not crash
2. No, they aren't dimmed when Ctrl + X prsssed. Only if right click cut out and after this if pressed Ctrl +X.

**Comment by 0x5bfa** [comment]
Ctrl+X and Cut button uses the exactly same operation layer internally.

- Is your keyboard US layout or for Windows?
- Items will be dimmed when you click Cut icon on the toolbar?
- You can copy items with Ctrl+C?

**Comment by Sergey842248** [comment]
1. It's DE, so german keyboard for Windows
2. Yes
3. Yes
