### ISSUE TITLE
Home Tab Quick Access Bug

### ISSUE THREAD

**Issue by YigitcanDnc** [files-community/Files#15823]
### Description

Most of the time, no part other than the "Drivers" is visible on the home page. Even though I terminate the application and run it again, the problem is not resolved. I have to turn the computer off and on.
![image](https://github.com/user-attachments/assets/31c20059-9f7b-4239-b301-f29119900174)

### Steps To Reproduce

Just open the application.

### Requirements

I expect this bug to be fixed so that we can make the application more useful. I'm ready for any feedback.

### Files Version

3.5.0.0

### Windows Version

10.0.19045.4651

### Log File

[debug.log](https://github.com/user-attachments/files/16303012/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, We're tracking this in https://github.com/files-community/Files/issues/15410 . You can check there or click subscribe in the right sidebar for updates.
 Please also try the workaround steps there.

As for the network locations you have it collapsed click the arrow to expand it.
