### ISSUE TITLE
Text is not clear when scrolling

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [files-community/Files#15829]
### Description

When scrolling :
![Capture d'écran 2024-07-19 173659](https://github.com/user-attachments/assets/6d86ccb7-7224-4a98-b9e5-e0254cfaf1c0)
(a bit blurred
When not scrolling:
![Capture d'écran 2024-07-19 173750](https://github.com/user-attachments/assets/f0ec8118-5108-45c9-974a-25fadd406476)

It's like ClearType isn't active when scrolling ? It has been like that since I own Files, so like 2 months ago

### Steps To Reproduce

Scroll

### Requirements

Text should be as clear when not scrolling as when scrolling

### Files Version

3.5.10.0

### Windows Version

10.0.22631.3880

### Log File

[debug.log](https://github.com/user-attachments/files/16321488/debug.log)

**Comment by yaira2** [comment]
Thanks for the report, the low framerate issue is well known with WinAppSdk. It's gotten better over time, but as you can see here, there are still some issues. We recommend reporting this on the WinUI repo so they can take your feedback into account https://github.com/microsoft/microsoft-ui-xaml/issues/new/choose

**Comment by 0x5bfa** [comment]
What about this issue in MUXC? https://github.com/microsoft/microsoft-ui-xaml/issues/8773

**Comment by yaira2** [comment]
That seems to be related 👍 

@TheWonderfulTartiflette feel free to comment on the issue @0x5bfa linked above.

**Comment by TheWonderfulTartiflette** [comment]
This seems to be it indeed. But I wasn't talking about the low framerates, as the text gets clear as soon as the scroll ends, but thanks 👍

**Comment by yaira2** [comment]
Either way, let's hope Microsoft fixes it soon...
