### ISSUE TITLE
Bug: Run with PowerShell toolbar button doesn't show PowerShell window

### ISSUE THREAD

**Issue by ohhsodead** [files-community/Files#15826]
### Description

After selecting a file, specifically a PowerShell Script, from the listings and then clicking the button "Run with PowerShell" it doesn't do anything. No error messages or anything. @Josh65-2201 confirms it doesn't for them either too.

### Steps To Reproduce

1. Select a .ps1 file
2. Click "Run with PowerShell" at the top

### Requirements

PowerShell should open with the selected script and execute it

### Files Version

3.5.0.0

### Windows Version

10.0.19045.4651

### Log File

[debug.log](https://github.com/user-attachments/files/16315601/debug.log)

**Comment by Qin-shihuang** [comment]
Is it the case that PowerShell is actually running in the background without opening a terminal? On my end, a simple script like
```
New-Item -Path ~\test.txt -ItemType file
```
can prove this (the file is created).

**Comment by yaira2** [comment]
@ohhsodead this should be resolved in the next update.
