### ISSUE TITLE
Wrong Number of files while moving/deleting/coping

### ISSUE THREAD

**Issue by umerghafoor** [files-community/Files#15828]
### Description

Items moved/deleted/copied are more the total items found.

<img width="242" alt="Screenshot 2024-07-20 155229" src="https://github.com/user-attachments/assets/53f7e2d5-72ef-43a4-b044-79909c8f6743">
thethan the total items

### Steps To Reproduce

move/delete/copy file or folder With So many files i.e 100,000.

### Requirements

- e.g. Fix file count while moving/deleting/coping.

### Files Version

3.5.0.0

### Windows Version

10.0.22631.3880

### Log File

[debug.log](https://github.com/user-attachments/files/16319875/debug.log)

**Comment by 0x5bfa** [comment]
Thank you for the feedback!

I assume the app using shell api, and it has that issue. You are also able to confirm this issue in a PowerShell command let.

**Comment by yaira2** [comment]
@0x5bfa do we have an official issue tracking this?

**Comment by 0x5bfa** [comment]
we use this #13860 as a tracker.

**Comment by yaira2** [comment]
@umerghafoor we're currently tracking this issue in #13860, you can click subscribe to be notified when the issue is resolved.
