### ISSUE TITLE
Optimization of Code due to high memory intake and slower runtime

### ISSUE THREAD

**Issue by JAGDF** [files-community/Files#15820]
### Description

When opening Files, it will tend to load slow as well as increasing the CPU usage and memory. Therefore inputs will register seconds after the initial one. The code may have too much code focusing on the visual aspect which restricts some functionality of the application. I cannot make a pull request to make changes to the code as I do not have much knowledge of most of the programming languages involved in the development of this application.

### Concerned code

The UpdateTask.cs and WindowsStorageFolder.cs files _appear_ to be a bit cumbersome, but I may be wrong. However, code within the Data and UserControls (could just be named User Controls or Controls) have many files involved. 

### Gains

- Better runtime, and low(er) CPU usage; a discrepancy to this imperfect solution is that aesthetics may have a chance to render into downgraded versions of their images
- Optimization allows application to run on lower-end Windows devices (this includes Windows devices Windows 9 and onwards)
- Memory usage lowers, system interrupts will not frequent so much as to use up the CPU
- Allows for fast file searches for content that doesn't involve more than ~200 files (i.e. it will take approximately 1 second to get search results for about 35-40 files)

### Requirements

- Remove some code which has to deal with launching the app and the app's aesthetics. I know this is a big ask, but optimize the code without taking away too much of the quality of the icons. (Does the icons use bitmap or vector?)

### Comments

![Screenshot 2024-07-18 103740](https://github.com/user-attachments/assets/742b41b4-c980-4854-9906-99fb85b9050e)
Memory usage is not extremely high, but runtime is slow and system interrupts increase, leading to CPU usage of a minimum of 40% _without_ additional applications open (for Windows 11, this could be lowered to about 25%)
If code was optimized prior to this issue, this issue is of **secondary priority** 
This issue applies the most to Windows 10 users.

**Comment by yaira2** [comment]
Thank you for your candid feedback. The decision to utilize WinAppSdk and WinUI allowed us to leverage the latest UI advancements. As you correctly noted, this choice has a performance impact. However, we are continuously optimizing the application, and with ongoing improvements to the mentioned frameworks, performance will enhance over time. Performance is influenced by various factors, so enhancements are gradual, but they accumulate over time. You can learn more about our progress in issue #4180.
