### ISSUE TITLE
File Explorer not opening after making FILES the default app. 

### ISSUE THREAD

**Issue by bcugs95** [files-community/Files#15827]
### Description

I installed this app, finding it beautiful and packed with features, the main one for myself being the tags.
Thing is, it has been really slow/sluggish, even visually lagging when moving the window around.
Hence, I decided to return to return to Window's File Explorer.
I had chosen the experimental feature to make FILES my default app, so I unchecked it, removed it from start-up app. I have **not** uninstalled it since in case of needing my tags, I will still use it.

The is issue is: File Explorer is not accessible outside of opening the download folder in my browser.
I heve already run the UnsetFilesAsDefault.reg file and nothing has changed, apparently. 

I guess I am looking for what could have been specifically changed in the registry so that I can restore it to defaults. 

Some images of the issues:
(upon trying to open File Explorer from taskbar)
![BGYRMtpUaN](https://github.com/user-attachments/assets/0b1780ef-2f42-4003-a645-0d78e5651612)
 
(Win+E)
![image](https://github.com/user-attachments/assets/310ec286-60e0-4a61-a9b2-ca766fa06c4d)

(explorer.exe from C:\Windows )
![image](https://github.com/user-attachments/assets/da105b86-6025-42cd-bce1-8f16d73576f2)

(only way i have found to open File Explorer, so far: open browser>open downloads page>open "Show in folder" from a downloaded file)
![image](https://github.com/user-attachments/assets/1996468a-3b5d-4e5b-ab28-8caa19b71618)

### Steps To Reproduce

These are the solutions I have found, tried, but come up short:

1. Run UnsetFilesAsDefault.reg
2. Alternitavely, have tried running _SetFilesAsDefault.reg_ and THEN _UnsetFilesAsDefault.reg_
3.     3.1.1. Type "cmd" in windows search bar
        3.1.2. Right click on "Command Prompt"
        3.1.3. Select "Run as Administrator"
        3.1.4. Type "sfc /scannow" without quote and press ENTER
       Then :
       3.2.1. Type "cmd" in windows search bar
       3.2.2. Right click on "Command Prompt"
       3.2.3. Select "Run as Administrator"
       3.2.4. Type "DISM /Online /Cleanup-Image /CheckHealth" without quote and press ENTER
       3.2.5. Type "DISM /Online /Cleanup-Image /ScanHealth" without quote and press ENTER
       3.2.6. Type "DISM /Online /Cleanup-Image /RestoreHealth" without quote and press ENTER
4. Booted without uneccessary services by: Win+R>msconfig>services tab>check "Hide all Microsoft sevices" box>disable all services left>Restart
5. Restarted the device between all steps.

### Requirements

Use File Explorer as usual, before the FILES app.
I guess I am looking for what could have been specifically changed in the registry so that I can restore it to defaults. 

### Files Version

3.5.0.0

### Windows Version

Edition	Windows 11 Pro Version	24H2 Installed on	‎02/‎07/‎2024 OS build	26100.863 Experience	Windows Feature Experience Pack 1000.26100.6.0

### Log File

[debug.log](https://github.com/user-attachments/files/16316805/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, everything Files changes is in the unset registry script (you can see the paths it changes too). Are you sure the file opened?

**Comment by bcugs95** [comment]
Thank you for the quick reply!
The file did open and state to have updates, but will do so once more and post below:
![image](https://github.com/user-attachments/assets/32c63f0a-83dc-4f6a-a117-cc3a079fca8d)

As for an anti-virus, I am not currently running any; I use windows defender and it is currently down(manually).

**Comment by Josh65-2201** [comment]
Did you use the file I linked or the one you found?

**Comment by bcugs95** [comment]
To be honest, I don't even remember from which thread/user I got the file from.
Regardless, I did as per your instructions, and nothing has changed; File Explorer still does not open independently.

**Comment by yaira2** [comment]
> To be honest, I don't even remember from which thread/user I got the file from.
> 
> Regardless, I did as per your instructions, and nothing has changed; File Explorer still does not open independently.

Where you got it from can make a big difference, I recommend trying the version Josh sent as that's the most up to date.

**Comment by bcugs95** [comment]
> > To be honest, I don't even remember from which thread/user I got the file from.
> > Regardless, **I did as per your instructions,** and nothing has changed; File Explorer still does not open independently.
> 
> Where you got it from can make a big difference, I recommend trying the version Josh sent as that's the most up to date.

As mentioned above, I followed the steps given, to no avail as of yet.

**Comment by Josh65-2201** [comment]
Can you open the registry and go to `HKEY_CURRENT_USER\Software\Classes\Folder\shell\open\command` and send a screenshot of what in the default value

**Comment by bcugs95** [comment]
> Can you open the registry and go to `HKEY_CURRENT_USER\Software\Classes\Folder\shell\open\command` and send a screenshot of what in the default value

![image](https://github.com/user-attachments/assets/b83a6d02-2971-4cef-a8cc-e5e714a0ce2d)

**Comment by Josh65-2201** [comment]
Can you also show `HKEY_CURRENT_USER\Software\Classes\Folder\shell\explore\command`

**Comment by bcugs95** [comment]
> Can you also show `HKEY_CURRENT_USER\Software\Classes\Folder\shell\explore\command`

![image](https://github.com/user-attachments/assets/f2aa5814-98e0-4bab-a4b1-2c37981ae1e1)

**Comment by Josh65-2201** [comment]
It seems to be an issue with Windows as the changes are correct for unsetting as default. Try restarting Windows

**Comment by bcugs95** [comment]
I have done so multiple times, but will do so once more and report.

**Comment by bcugs95** [comment]
> I have done so multiple times, but will do so once more and report.

Done.

**Comment by Josh65-2201** [comment]
I don't know what the issue would be then. The registry changes are correct and Files doesn't change any others

**Comment by bcugs95** [comment]
:(

**Comment by TheyCallMeTojo** [comment]
```
Windows Registry Editor Version 5.00
[HKEY_CLASSES_ROOT\Folder\shell\explore\command]
@="%SystemRoot%\\Explorer.exe"
"DelegateExecute"="{11dbb47c-a525-400b-9e80-a54615a090c0}"
```

Save this to a reg file and try. 

From what I remember, and have checked on both my machines, "Folder" doesn't exist in HKEY_CURRENT_USER\Software\Classes

It should be in HKEY_CLASSES_ROOT\Folder\shell\explorer\command

**Comment by yaira2** [comment]
@bcugs95 any luck with the solution @TheyCallMeTojo shared?

**Comment by bcugs95** [comment]
@TheyCallMeTojo @yaira2 

Sorry for the late reply.
I have just tried the new reg file and still no luck.

![regedit_WKZhNVLhYh](https://github.com/user-attachments/assets/8a46ad0c-a8e0-445e-9c86-6f4cd3bafc36)

**Comment by bcugs95** [comment]
> @TheyCallMeTojo if you set Files as the default file manager again, does `win` + `e` open Files?

Yes, it does.

**Comment by 0x5bfa** [comment]
We truly apologize for this annoying inconvenience.

I assume you've already tried sfc and dism commands.
The options that I can imagine in this case is to go to Windows RE and do advanced repair or reinstall Windows after backing up everything you want to keep.

**Comment by TheyCallMeTojo** [comment]
The only other possible issue I can think of is if environment variable were changed. Ensure that the system environment variables are set correctly.

Right-click on This PC or Computer on the desktop or in File Explorer and select Properties.
Click on Advanced system settings.
Click on Environment Variables.
Ensure that the PATH variable includes the necessary system paths, such as C:\Windows\System32.

**Comment by yaira2** [comment]
> > @TheyCallMeTojo if you set Files as the default file manager again, does `win` + `e` open Files?
> 
> Yes, it does.

@bcugs95 does toggling it off from the app work?

**Comment by bcugs95** [comment]
> > > @TheyCallMeTojo if you set Files as the default file manager again, does `win` + `e` open Files?
> > 
> > 
> > Yes, it does.
> 
> @bcugs95 does toggling it off from the app work?

Turning off the option the have Files an the default app returns to the error reported.

**Comment by yaira2** [comment]
@gave92 do you have any ideas here? We've tried all the usual steps without any luck.

**Comment by TheyCallMeTojo** [comment]
Navigate to: 
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\MyComputer\NameSpace`

By Default it should contain the following: 

`
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\MyComputer\NameSpace]

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\MyComputer\NameSpace\DelegateFolders]

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\MyComputer\NameSpace\DelegateFolders\{289AF617-1CC3-42A6-926C-E6A863F0E3BA}]
@="DLNA Media Servers Data Source"

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\MyComputer\NameSpace\DelegateFolders\{35786D3C-B075-49b9-88DD-029876E11C01}]
@="Portable Devices"

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\MyComputer\NameSpace\DelegateFolders\{9113A02D-00A3-46B9-BC5F-9C04DADDD5D7}]
@="Enhanced Storage Data Source"

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\MyComputer\NameSpace\DelegateFolders\{b155bdf8-02f0-451e-9a26-ae317cfd7779}]
@="nethood delegate folder"

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\MyComputer\NameSpace\{088e3905-0323-4b02-9826-5d99428e115f}]
@="CLSID_ThisPCLocalDownloadsRegFolder"
"HiddenByDefault"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\MyComputer\NameSpace\{1CF1260C-4DD0-4ebb-811F-33C572699FDE}]
@="CLSID_ThisPCMyMusicRegFolder"
"HiddenByDefault"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\MyComputer\NameSpace\{24ad3ad4-a569-4530-98e1-ab02f9417aa8}]
@="CLSID_ThisPCLocalPicturesRegFolder"
"HiddenByDefault"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\MyComputer\NameSpace\{374DE290-123F-4565-9164-39C4925E467B}]
@="CLSID_ThisPCDownloadsRegFolder"
"HiddenByDefault"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\MyComputer\NameSpace\{3ADD1653-EB32-4cb0-BBD7-DFA0ABB5ACCA}]
@="CLSID_ThisPCMyPicturesRegFolder"
"HiddenByDefault"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\MyComputer\NameSpace\{3dfdf296-dbec-4fb4-81d1-6a3438bcf4de}]
@="CLSID_ThisPCLocalMusicRegFolder"
"HiddenByDefault"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\MyComputer\NameSpace\{A0953C92-50DC-43bf-BE83-3742FED03C9C}]
@="CLSID_ThisPCMyVideosRegFolder"
"HiddenByDefault"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\MyComputer\NameSpace\{A8CDFF1C-4878-43be-B5FD-F8091C1C60D0}]
@="CLSID_ThisPCDocumentsRegFolder"
"HiddenByDefault"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\MyComputer\NameSpace\{B4BFCC3A-DB2C-424C-B029-7FE99A87C641}]
@="CLSID_ThisPCDesktopRegFolder"
"HiddenByDefault"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\MyComputer\NameSpace\{d3162b92-9365-467a-956b-92703aca08af}]
@="CLSID_ThisPCLocalDocumentsRegFolder"
"HiddenByDefault"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\MyComputer\NameSpace\{f86fa3ab-70d2-4fc7-9c99-fcbf05467f3a}]
@="CLSID_ThisPCLocalVideosRegFolder"
"HiddenByDefault"=dword:00000001
`


If there's extra stuff, delete it.

**Comment by mrchillington** [comment]
![explorer_hyEvtYzVke](https://github.com/user-attachments/assets/ca2225d7-15fc-45a3-857f-0f6cd8087f4c)

**Comment by mrchillington** [comment]
i happened to uninstall Files without making sure that File Explorer still worked..... oops

**Comment by mrchillington** [comment]
> Thanks for the report, everything Files changes is in the unset registry script (you can see the paths it changes too). Are you sure the file opened? And that any anti-virus software didn't block it.
> 
> The file shouldn't be downloaded as a .zip either, can you use this https://raw.githubusercontent.com/files-community/Files/main/src/Files.App/Assets/FilesOpenDialog/UnsetFilesAsDefault.reg > Right click > save as > set "Save as type" to all files > Remove .txt from end of file name > Run the file

This worked...
I happened to uninstall Files without making sure that File Explorer still worked..... oops

**Comment by yaira2** [comment]
@bcugs95 I know this isn’t the solution you were hoping for, but since the usual fixes didn’t work, I recommend trying to create a new user account.
This reinforces our decision to keep this feature marked as experimental. We’re hopeful that Microsoft will eventually provide an official way to change the default file manager. In the meantime, we’ll continue refining this workaround and do our best to prevent this issue from happening again.
