### ISSUE TITLE
Feature: Optimizing File List Loading

### ISSUE THREAD

**Issue by Tptogiar** [files-community/Files#15830]
### What feature or improvement do you think would benefit Files?

When there are many files in a directory, such as 100,000 files, opening this directory can be very slow.

### Requirements

- Optimize the code logic for loading the file list

### Files Version

3.5.0.0

### Windows Version

10.0.22621.3737

**Comment by 0x5bfa** [comment]
Thank you for the report.
We're tracking this slowness in #4180. For the further updates, you can click Subscribe from the sidebar. Slowness often comes from the framework we use but we're trying to optimize to some degree by ourself.

**Comment by yaira2** [comment]
@Tptogiar Thank you for your feedback, we're working on improving performance and will continue releasing updates with this goal in mind. Most of the time, improvements are gradual, but we'll post in #4180 whenever a larger improvement is available.

**Comment by Tptogiar** [comment]
@yaira2 Thank you for your reply. I've attempted to optimize some of the logic during the file loading process in this PR.
https://github.com/files-community/Files/pull/15831

**Comment by yaira2** [comment]
Thank you @Tptogiar! We'll review your PR shortly.
