### ISSUE TITLE
error 0x80070422 during the installation

### ISSUE THREAD

**Issue by luvvboy** [files-community/Files#15838]
### Description

Hello, during the installation of the program, I encountered the following error: 
**Original(Russian)**
0x80070422, Указанная служба не может быть запущена, так как отключена либо она сама, либо все связанные с ней устройства
.
Указанная служба не может быть запущена, так как отключена либо она сама, либо все связанные с ней устройства.
Ошибка 0x80070422: сбой открытия пакета из расположения Files.Package_3.5.0.0_x64_arm64_Stable.msixbundle.

**Translated**
0x80070422, The specified service cannot be started because either it itself or all associated devices are disabled
.
The specified service cannot be started because either it itself or all associated devices are disabled.
Error 0x80070422: Failed to open a package from the location Files.Package_3.5.0.0_x64_arm64_Stable.msixbundle.

How can i solve it?
![Screenshot_3](https://github.com/user-attachments/assets/1656e869-9f35-4433-9de8-7c999d9f4364)

### Steps To Reproduce

1

### Requirements

error 0x80070422 during the installation

### Files Version

3.5

### Windows Version

19045.4239

### Log File

i havent got log files

**Comment by Josh65-2201** [comment]
If you're using an unofficial Windows install (AtlasOS, ReviOS, disabled Windows update system, removed the Microsoft store, etc.) these are not supported but you can try the below.

1. Type Services in Windows start menu > Open the `Windows update` and `Delivery optimization` services > Set startup type to automatic > Click ok > restart Windows and try installing again.

2. You can also try
   1. Opening PowerShell (Windows default not PowerShell 7) as administrator
   2. Run this command
   ```Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/stable/Files.Package.appinstaller```
   3. See if Files is in the start menu all apps section

If the above doesn't work you won't be able to use Files without reinstalling Windows using the official installer from https://www.microsoft.com/software-download/windows11.
