### ISSUE TITLE
Bug: Ctrl + scroll wheel not resizing icons.

### ISSUE THREAD

**Issue by nashiecrafter** [files-community/Files#15836]
### Description

Ctrl + scroll wheel not resizing icons. No indication of effect. 

### Steps To Reproduce

What it says on the tin.

### Requirements

Icons should scale like the original Windows file explorer feature. 

### Files Version

3.5.0.0

### Windows Version

Windows 10 Pro Version

### Log File

[debug.log](https://github.com/user-attachments/files/16326411/debug.log)

**Comment by yaira2** [comment]
Thank you for the report

**Comment by yaira2** [comment]
It seems that the keyboard shortcuts aren't working either.

**Comment by hishitetsu** [comment]
In the grid layout? I have tested it and it appears to be working without any problems.

**Comment by yaira2** [comment]
I can repro in all layouts

**Comment by hishitetsu** [comment]
Here is a video of rotating the scroll wheel while holding down Ctrl. Nothing strange.
https://github.com/user-attachments/assets/784b27f2-25c4-4943-97e4-480e769c76c1

**Comment by yaira2** [comment]
It started working on my end after restarting the app, I'll try to comment if the error occurs again.

**Comment by yaira2** [comment]
> It started working on my end after restarting the app, I'll try to comment if the error occurs again.

The issue comes back after switching directories. Interestingly, changing to a different layout and back re-enables the shortcuts.

**Comment by hishitetsu** [comment]
Thanks. I was able to reproduce it.

**Comment by hishitetsu** [comment]
It happens in the adaptive layout. I submitted a fix.
