### ISSUE TITLE
Wish the right-click customization menu was more flexible

### ISSUE THREAD

**Issue by heianyizu666** [files-community/Files#15833]
### What feature or improvement do you think would benefit Files?

I wish the right-click menu could be customized like the open source project Custom Context Menu

### Requirements

- I wish the right-click menu could be customized like the open source project Custom Context Menu

### Files Version

3.5.0.0

### Windows Version

10.0.22631.3880

**Comment by yaira2** [comment]
I'm not familiar with the app you mentioned, can you share some details on the customization features you're most interested in?

**Comment by heianyizu666** [comment]
> 我对您提到的应用程序不太熟悉，您能分享一些您最感兴趣的自定义功能的详细信息吗？
You can take a look at this project ,it can adds Custom Context Menu For Windows11. https://github.com/ikas-mc/ContextMenuForWindows11

**Comment by heianyizu666** [comment]
> I'm not familiar with the app you mentioned, can you share some details on the customization features you're most interested in?

You can take a look at this project ,it can adds Custom Context Menu For Windows11. https://github.com/ikas-mc/ContextMenuForWindows11

**Comment by yaira2** [comment]
You can add custom menu items in Files as well, is there a specific feature that you're looking for?

**Comment by 0x5bfa** [comment]
that is for supporting context menu of Windows 11 version. I saw this when i was exploring how to support it in Files but this is just using IExplorerCommand. one menu item can be added per application so this workarouds by putting all inside of it as sub menu items.
Any customizing application has to mess around registry.
