### ISSUE TITLE
Redundant folder tabs when opening a folder location from a third-party app

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [files-community/Files#15851]
### Description

(I'm not sure if this should be classified as a feature request or a bug)
When opening a folder location using a third-party app, Files does not verify if the folder is already open. As a result, it creates a new tab for the same folder, leading to duplicate tabs displaying the same folder

### Steps To Reproduce

1. Open a folder (C:/Test for example)
2. Have a third-party app to open that folder (That would be a Chrome download to C:/Test, and pressing the tab icon to open the download directory)

### Requirements

Files should check if, in the active tabs, the folder is opened or not. If it is, then redirect to that tab. Otherwise, create a tab for that folder

### Files Version

3.5.15.0

### Windows Version

10.0.22631.3880

### Log File

[debug.log](https://github.com/user-attachments/files/16354728/debug.log)

**Comment by yaira2** [comment]
Thank you for the feedback, can you confirm if this is the same as #6925?

**Comment by TheWonderfulTartiflette** [comment]
Oops my bad, indeed I should actually check before posting if it's a duplicate or not, but yes that the same as #6925
