### ISSUE TITLE
Bug: Home tab opened when opening file location with no active tabs and using continue where you left off startup setting.

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [files-community/Files#15857]
### What feature or improvement do you think would benefit Files?

Right now, when Files is closed and no tab is open (i.e., Files has been closed by closing the last active tab) and a folder has been opened by a third party app, Files will open the home tab and the desired folder.
I don't see what's the point of opening the home tab here. If Files has been directly opened by the user, okay, it's normal for Files to show at least a tab, but I don't think it's appropriate when Files has been opened by targeting a specific folder.
This also happens when opening a folder from the Windows search bar

### Requirements

Files should only open the targeted folder when it has been launched by targeting a specific folder

### Files Version

3.5.15.0

### Windows Version

10.0.22631.3880

### Comments

How it currently acts in Files: https://imgur.com/a/xAzg2eB
How it acts in Windows Explorer: https://imgur.com/a/Hhs3oVK

**Comment by Josh65-2201** [comment]
Thanks for the feedback, This is only an issue with the continue where you left off start up setting.

**Comment by yaira2** [comment]
The expected behavior of the Continue Where You Left Off feature is to restore the list of tabs from the previous session. I will conduct further research to verify the intended behavior when all tabs are closed, and the application is launched by a third-party.

**Comment by yaira2** [comment]
I have some changes in #15859 that will be tested in one of the next preview builds

**Comment by TheWonderfulTartiflette** [comment]
Hi, I'm not sure if it's fixed, for my part at least. I have just updated Files ( 3.5.23.0 ), but I'm still having this issue

**Comment by yaira2** [comment]
It'll be included in v3.5.24.

**Comment by TheWonderfulTartiflette** [comment]
Yep, that works 👍
