### ISSUE TITLE
Able to see full file name in column view 

### ISSUE THREAD

**Issue by tongyao-ux** [files-community/Files#15854]
### What feature or improvement do you think would benefit Files?

Problem: cannot see full file or folder name under column view
Work-around: click on file to see full info on the side panel, or change folder view into detailed list view, both not user-friendly in switching between large folder sets.

### Requirements

- This proposal will accomplish user is able to see full file name under column view whenever user wants

- Proposal  
Option 1: auto use full window width to view the file name for the last folder items
Option 2: enable user to adjust/drag column width of the last OR every column
Option 3: add a button to auto-fit column width to the longest file name for last OR every column

### Files Version

3.5.0.0

### Windows Version

10.0.22631.3880

**Comment by 0x5bfa** [comment]
Thanks for the report.

Can you check out if the issue is the same as #6534?

**Comment by tongyao-ux** [comment]
> Thanks for the report.
> 
> Can you check out if the issue is the same as #6534?

Yes. Glad to know there're already some discussion on this :)

**Comment by 0x5bfa** [comment]
If you have something worth mentioning regarding this issue, please comment on that issue, so we can profoundly investigate the issue.
With merging with #6534, you can click Subscribe button to be notified of further news on this matter 👍
