### ISSUE TITLE
Bug: Issue with Pane Arrangement

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#15866]
### Description

I have encountered a problem when trying to open a second pane and arrange them horizontally. When I click on "Arrange Horizontally," the panes are arranged vertically instead, and the reverse happens when I choose to arrange them vertically.

### Steps To Reproduce

1. Click on the "Tab actions menu" button
2. Click on "Arrange Horizontally"

### Requirements

Correct the logic for arranging the panes to ensure that the "Arrange Horizontally" option arranges the panes horizontally and the "Arrange Vertically" option arranges them vertically.

### Files Version

3.5.23.0

### Windows Version

10.0.22631.3880

### Log File

![Capture d'écran 2024-07-25 171600](https://github.com/user-attachments/assets/b40bc345-89c4-4187-a9d1-69f4b9bf0007)

**Comment by yaira2** [comment]
We have decided to use the term ‘Arrange Panes’ instead of ‘Split Panes’. Feedback and the response to polls on Discord indicate a preference for the current user experience, but this decision is not final, and we are actively monitoring feedback in this area.

**Comment by Lukiluc29** [comment]
Oh, I see. However, for me, it doesn't seem logical because when we see the icon showing the panes vertically, we expect the panes to be arranged vertically and not horizontally.

**Comment by yaira2** [comment]
> Oh, I see. However, for me, it doesn't seem logical because when we see the icon showing the panes vertically, we expect the panes to be arranged vertically and not horizontally.

I must have reversed the icons in #15843, I'll fix this shortly.
