### ISSUE TITLE
Type column in Details view changes from localized to none localized after folder is loaded

### ISSUE THREAD

**Issue by yi-Xu-0100** [files-community/Files#1586]
**Describe the bug**

In the file management interface, the first time you open or newly open a folder, the file or folder type will be refreshed from English to Chinese.

**To Reproduce**

1. Go to main interface.
2. Click on 'C:' or 'D:'.
4. See error.

**Expected behavior**

When switching between different folders, the page does not refresh, and the relevant language in the settings is displayed correctly.

**Screenshots**

![1](https://user-images.githubusercontent.com/25523606/88525671-7435a580-d02d-11ea-9ab4-ba18d7d2c859.gif)

**Desktop (please complete the following information):**

 - OS Version: Windows 10 1909 18363.959
 - App version: v0.12.0.0(Install from the Microsoft Store)
 - System language setting: Chinese
 - App language setting: English

**Additional context**

When I set the language to Chinese, there is still a refresh phenomenon, but it seems that only the file type needs to be refreshed. See GIF follow:

![2](https://user-images.githubusercontent.com/25523606/88525686-7bf54a00-d02d-11ea-8f18-220183870044.gif)

**Comment by yi-Xu-0100** [comment]
I see some issue about translation, but never mention the refresh phenomenon.

**Comment by Jaiganeshkumaran** [comment]
The item type is pulled from Windows so it remains in your system language and we can't do anything about that.

**Comment by yi-Xu-0100** [comment]
But it can be seen that he has a default value. Why not keep the default value, but need to refresh and replace it with the system value?

**Comment by yaichenbaum** [comment]
@gave92 would a cache similar to the one we use for thumbnails work to fix this issue as well?

**Comment by gave92** [comment]
Yeah it would, it would only load the localized type string for the first file of that type and then use that for every other file of the same type.

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?

**Comment by yaichenbaum** [comment]
> Is this still an issue in 2.3.3.0?

I believe so

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
Merging with #10320

**Comment by yi-Xu-0100** [comment]
I check in the latest version (v2.3.12.0 Windows store), This still seems to be an issue, and now in folders where a lot of files exist, it's less of a problem due to the slow loading of the file list. 👀
