### ISSUE TITLE
Files sometimes does not remember my sorting preferences for each folder

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [files-community/Files#15870]
### Description

For some folders, I have set the sorting to be A to Z, and in my Files app, the default sorting is most recent to least recent. I found that sometimes, Files does not remember that for this particular folder, I asked the sorting to be A to Z, and will do most to least recent
This is a bit similar to #15797 , but not entirely because I'm not sure that this happens only when updating, and I didn't understand how OP fixed the issue

### Steps To Reproduce

I don't really know, just have a folder to not be the same sorting as the default sorting

### Requirements

- e.g. Fix crash that occurs when...
Folder sorting preferences should always be remembered by Files

### Files Version

3.5.24.0

### Windows Version

10.0.22631.3880

### Log File

[debug.log](https://github.com/user-attachments/files/16382927/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, your likely having the same issue as you linked. Are you sure Files didn't update when you had the layouts reset? Also there's no fix for it right now just a workaround https://github.com/files-community/Files/issues/15797#issuecomment-2244450518

**Comment by TheWonderfulTartiflette** [comment]
My bad for duplicate actually yes that's the case, the sorting preferences got forgotten when my Files updated
