### ISSUE TITLE
Feature: [Accessibility Option] Disable folders opening when moving files inside.

### ISSUE THREAD

**Issue by HaggardHare** [files-community/Files#15881]
### What feature or improvement do you think would benefit Files?

I'm not used to folders opening when I drag files inside of them. It really throws me off while I'm organizing large directories. Apparently this was also a thing in default windows explorer but somehow I've managed to avoid it for years.  

I'm very sensitive to movement and my eyes keep having to shift back and forth as the pane reloads the I was in when I hit back.  It's putting a fairly big dint in my workflow, so I hope this is possible to implement. 

### Requirements

- Have something like a toggle on on/off feature in the settings.
- Dragging files into folders will keep the directory the same. 

### Files Version

3.5.0.0

### Windows Version

10.0.19045.4651

**Comment by Josh65-2201** [comment]
Thanks for the feedback, I have added this to the project board.

**Comment by yaira2** [comment]
@HaggardHare we recently reduced the sensitivity of this feature (#15694) have you tried the preview version of Files? https://files.community/download

**Comment by HaggardHare** [comment]
Yeah, I noticed some difference, _but I'm still too slow for it._ It would be cool if users could customize the sensitivity themselves in the settings.

**Comment by yaira2** [comment]
We'd prefer to settle on a default

**Comment by yaira2** [comment]
I've decreased the sensitivity by 30% in `main`. I think this will do the trick, but if you still have issues after the next preview update, please let me know and we'll investigate further.
