### ISSUE TITLE
Files UWP should auto refresh in the background and display the updated files like in file explorer.

### ISSUE THREAD

**Issue by 77376** [files-community/Files#1589]
when a file is created or deleted or downloaded ,those files/folders appear/removed immediately and instantly in default file explorer. but in files uwp you have to manually click refresh all the time.     Manually refreshing all the time is so boring  .                                                                                                                                                    

1. Download/create any type of file/folder.
2. It wont appear until you manually click refresh in files uwp

**Expected behavior**
Files UWP should auto refresh in the background and display the updated files like in file explorer.

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 2004 19041.264]
 - App version: [v0.12.4]

**Comment by yaichenbaum** [comment]
Can you confirm if you are still not seeing the correct behavior?
