### ISSUE TITLE
Tool bar thinks folders whose names end with ".zip" are archives

### ISSUE THREAD

**Issue by AkazaRenn** [files-community/Files#15892]
### Description

![Screenshot 2024-07-28 191736](https://github.com/user-attachments/assets/996271ca-e213-49ad-b190-e29c1b0cc82e)
As you can see in the screenshot, this folder named `MSYH_V20230523.zip` is recognized as a zip archive by the tool bar and shows the `Extract` button

### Steps To Reproduce

1. Create a folder whose name ends by `.zip`
2. Enter the folder, don't select anything
3. Observe the bug

### Requirements

The `Extract` button should not appear since it is not an archive and there's nothing to extract

### Files Version

3.5.0.0

### Windows Version

10.0.26100.1150

### Log File

[debug.log](https://github.com/user-attachments/files/16405534/debug.log)

**Comment by yaira2** [comment]
Thank you for the report, we're tracking a similar issue in #15886. The same fix can be used so we'll continue tracking there.

**Comment by yaira2** [comment]
A fix will be included in the next update.
