### ISSUE TITLE
In column view, backwards and forwards arrows in top left of app don't work

### ISSUE THREAD

**Issue by picknassaro** [files-community/Files#15904]
### Description

In column view, backwards and forwards arrows in top left of app don't work

### Steps To Reproduce

Enter column view, navigate around, attempt to click backwards and forwards buttons in top left of app

### Requirements

please make the backwards and forwards buttons work even in column view

### Files Version

3.5.0.0

### Windows Version

10.0.22631.3958

### Log File

[debug.log](https://github.com/user-attachments/files/16431455/debug.log)

**Comment by yaira2** [comment]
I believe this behavior is intentional. The navigation buttons are only enabled when changing locations, and in the Columns View, the location remains constant, and only the subfolders change.

**Comment by picknassaro** [comment]
Ok, I'll close the issue. I can use the column view in the way you intend.

**Comment by yaira2** [comment]
I meant to ask, what behavior did you expect here?

**Comment by npassaroPCH** [comment]
I would expect that hitting the back arrow would be the same as clicking the up arrow to go to the parent folder of the currently highlighted folder at the rightmost column, but hitting the forward arrow thereafter would go back to the folder that was highlighted before hitting the back arrow, essentially re-revealing the column that was originally rightmost.
