### ISSUE TITLE
files is very slow and often times unresponsive or crashes

### ISSUE THREAD

**Issue by DeerUwU** [files-community/Files#15901]
### Description

id love to use the program more but it always freezes up when i try to move files or do anything with it. it also takes a pretty long time to start in the first place. starting it up with 4 tabs takes about 20 seconds, when i delete a file or folder it freezes for at least 10 seconds or becomes unresponsive until i restart it. 

### Steps To Reproduce

1. open the program
2. move or delete any file or folder

### Requirements

- fix unresponsive behavior and very slow loading times

### Files Version

3.5.15.0

### Windows Version

10.0.19045.4651

### Log File

[debug.log](https://github.com/user-attachments/files/16426626/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, Files v3.5.15 is a preview build and crashes are to be expected. That said, the latest preview build (v3.5.25) should be a lot more stable as we're preparing it for general release. If you're still experiencing crashes in the latest preview, please let us know as soon as possible so we can investigate.

> when i delete a file or folder it freezes for at least 10 seconds or becomes unresponsive until i restart it.

We're tracking this issue in #14108, please subscribe to be notified of further updates.

**Comment by omersayli** [comment]
I agree that performance of the Files is rather "slow", I turned to XYplorer software for this reason.

**Comment by yaira2** [comment]
@omersayli the preview version is available on our download page https://files.community/download.
