### ISSUE TITLE
Please add Quick Look from Mac OS Finder to Files

### ISSUE THREAD

**Issue by picknassaro** [files-community/Files#15909]
### What feature or improvement do you think would benefit Files?

In Mac OS, there is a feature called Quick Look. It is triggered by selecting a file or folder and hitting Space. This brings up a floating preview of the file or folder. It can play videos, show images and text contents of a file, etc. But please make this feature work so that the preview window appears as its own separate window, rather than having it constrained to be inside the files app window. Please see this video to get the idea of the feature: https://youtu.be/IPKWGtp4HtY?si=bHicgztGiEoTdvo2

### Requirements

- This proposal will make file management and previewing much easier

### Files Version

3.5.0.0

### Windows Version

10.0.22631.3958

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Files already support Quick look https://apps.microsoft.com/detail/9nv4bs3l1h4s?hl=en-US&gl=US

**Comment by yaira2** [comment]
Additional info can be found on our documentation site https://files.community/docs/features/integrations

**Comment by yaira2** [comment]
@picknassaro in case you're interested, we have a Discord server where you can chat with us https://discord.gg/files without the need to create issues on GitHub.
