### ISSUE TITLE
Add keyboard shortcut to toggle viewing hidden files and dotfiles

### ISSUE THREAD

**Issue by picknassaro** [files-community/Files#15905]
### What feature or improvement do you think would benefit Files?

On Mac OS, I can hit CMD Shift period to toggle the ability to view hidden files and dotfiles. This is great for when I need to quickly find something. I would never want hidden and dot files to be visible at all times, so this quick shortcut to toggle comes in handy. Please replicate that feature in this Files app. Maybe Ctrl Shift period would be a sensible keyboard shortcut for it.

### Requirements

- This proposal will make managing hidden files and folders easier, without keeping them visible at all times. Keeping them visible at all times is bad because it risks accidental deletion and is generally cluttered.

### Files Version

3.5.0.0

### Windows Version

10.0.22631.3958

**Comment by yaira2** [comment]
Thank you for your feedback, you can toggle hidden items via the `ctrl` + `h` shortcut.

**Comment by yaira2** [comment]
Addition information about shortcuts, as well as actions that can be assigned shortcut can be found on our docs https://files.community/docs/customize-settings/actions

**Comment by yaira2** [comment]
I'll add a similar action for `dot files` in the next update.
