### ISSUE TITLE
Feature: Add a setting to disable two finger swipe navigation

### ISSUE THREAD

**Issue by picknassaro** [files-community/Files#15903]
### What feature or improvement do you think would benefit Files?

Please add the option to disable two finger swipe for backwards/forwards page navigation. It makes sense in web browsers, but in file managers, I prefer not to have that because I often accidentally trigger the swipe to go back when scrolling horizontally to view earlier columns in a multi-column layout.

### Requirements

I'd like to have a new option in the app's settings that lets me disable two finger swipe for backwards/forwards page navigation.

### Files Version

3.5.0.0

### Windows Version

10.0.22631.3958

**Comment by yaira2** [comment]
Thank you for your feedback

**Comment by yaira2** [comment]
@picknassaro we’re open to adding this option if there’s enough interest from our users. I know this isn't the response you were looking for, but at the moment, there doesn't seem to be a lot of interest. However, if we receive more requests for this feature, we’ll gladly reconsider including it in a future update.
