### ISSUE TITLE
Status bar is not visible

### ISSUE THREAD

**Issue by tsvietOK** [files-community/Files#1590]
**Describe the bug**
Status bar not visible when first time entering to folder after app launch.

**To Reproduce**
1. Launch app
2. Click on sidebar drive item
3. Status bar is not visible
4. Open any folder, now status bar is visible

**Expected behavior**
Status bar should be visible when entering to folder

**Screenshots**
![image](https://user-images.githubusercontent.com/20501502/88549083-8f51e680-d028-11ea-8ae4-0785f79ee787.png)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 2004 19041.388]
 - App version: [v0.12.0], [v0.12.3]

**Comment by generalguy41** [comment]
Still applies in 0.13.0.0. Happens for me when going from the Home page to any of my local drives (not network drives though).

**Comment by Thomas1664** [comment]
@tsvietOK @yair100 I think we can close this issue since the problem seems to be solved.
