### ISSUE TITLE
Bug: Pin to sidebar text missing

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#15917]
### Description

Currently just shows as an icon using Windows default as the language and on Windows it set to English UK

### Steps To Reproduce

1. Right click a folder

### Requirements

- Show text

### Files Version

3.5.27.0

### Windows Version

10.0.22621.3737

### Log File

*

**Comment by yaira2** [comment]
What's the string set to in Crowdin?

**Comment by Josh65-2201** [comment]
Can't log in to crowding right now but it should be here https://crowdin.com/editor/files-app/all/en-engb?view=comfortable&screenshot_id=78

**Comment by yaira2** [comment]
I fixed the translation in Crowdin.
