### ISSUE TITLE
New Feature

### ISSUE THREAD

**Issue by JimEngandela** [files-community/Files#15914]
### What feature or improvement do you think would benefit Files?

Add a Startup option to set the default layout.  Everytime I open Files I have to set the layout to Columns. This is not efficent.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.5.0.0

### Windows Version

10.0.22631.3958

**Comment by Josh65-2201** [comment]
Thanks for the feedback, you can change layout options in Files settings > Layout
