### ISSUE TITLE
App periodically forgets my preferred window size and starting position

### ISSUE THREAD

**Issue by picknassaro** [files-community/Files#15921]
### Description

A few separate times per day, when I go to open the Files app, it will open at the default size and position from a fresh install of the app, forgetting that I have resized it to be much smaller out of personal preference.

### Steps To Reproduce

I can't exactly say what's causing it, as it happens randomly, and only a few times per day at most.

### Requirements

I'd like Files to permanently remember the most recent window size and position, and have that remembered any time I resize the app. But if possible, an option to set a default window size would be nice.

### Files Version

3.5.0.0

### Windows Version

10.0.22631.3958

### Log File

[debug.log](https://github.com/user-attachments/files/16459488/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Window size and position is set and manage by Windows, Files doesn't change anything.

**Comment by yaira2** [comment]
@picknassaro Windows retains the application’s size and position settings only when it is closed properly. In instances where the application crashes, as indicated in the log file, these settings are not saved. We are actively working on enhancing stability to reduce this issue in the future. We are also exploring the option of managing the window size and position ourselves. However, this approach is quite complex and will be considered only as a last resort.

**Comment by picknassaro** [comment]
Window sizing and start position are available options in Windows Terminal (see screenshot). Is there no way for third-party apps to do this?
![Screenshot 2024-08-01 150340](https://github.com/user-attachments/assets/991a9d17-92de-42dd-b87e-72de6d7d64d2)

**Comment by yaira2** [comment]
> Also, Files is the only app on my computer that has this issue I'm describing, so something must be doable to fix the last set window size being forgotten at least?

You can probably work around this by turning off the option to keep Files open in the background.
