### ISSUE TITLE
列视图单机会返回主目录

### ISSUE THREAD

**Issue by JIANOP** [files-community/Files#15924]
### Description

> Translated

The column view menu returns to the home directory

### Steps To Reproduce

> Translated

In the column view of the
Multi-level folders.
Standalone returns to the home directory

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.5.0.0

### Windows Version

10.0.22631.3958

### Log File

[debug.log](https://github.com/user-attachments/files/16467120/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, It's unclear what your issues is can you upload a screen recording or add more detail of the issue.

**Comment by Qin-shihuang** [comment]
Translated: When left-clicking in multi-level folders in Column Layout, the page scrolls back to the root.
It's is the same issue as #15776 .

**Comment by JIANOP** [comment]
谢谢你
