### ISSUE TITLE
Feature: Don't use all CPU threads when compressing and decompressing

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#15926]
### What feature or improvement do you think would benefit Files?

7zip allow users to chose how many threads are used, while Files uses all of them. This makes compression/decompression faster but also lags out other programs especially when there playing audio.

### Requirements

- Set Files to leave 2 to 4 logical processor threads free
   - Alternate give user control on how many threads are used in settings

### Files Version

3.5.29.0

### Windows Version

10.0.22621.3737

**Comment by yaira2** [comment]
Does 7zip have this option when extracting archives?

**Comment by Josh65-2201** [comment]
It doesn't, I thought it used the same value as the create archive in 7zip interface but Files seem to be matching 7zip. This can be added for making an archive only
