### ISSUE TITLE
Wrong working directory when opening Emacs + sly + SBCL from context menu

### ISSUE THREAD

**Issue by BanishedBliss** [files-community/Files#15922]
### Description

Opening Emacs + SBCL from folder's context menu does not set it as a working directory for sly's REPL.

I suppose it's not the end of the world for me and it's very specific, but if it's an issue on my side, just let me know, please. (though it clearly is an inconsistency, as I see it) 

![image](https://github.com/user-attachments/assets/905ca28f-6e7b-4de1-93a6-cb769c435220)

Since replicating the issue itself is a difficult process because of the first step, I'm ready to perform any debugging steps necessary on my side, rather than expecting you to find out how to install the package for yourself.

### Steps To Reproduce

1. Install Emacs + sly + SBCL, which is a package for Common Lisp development.
2. Open an instance of Emacs in the same directory in both the default file explorer an Files.
3. In the sly REPL buffer type in `(print *default-pathname-defaults*)`  which prints out current working directory.
4. ???
5. See the difference.

### Requirements

I do not know just how deep the differences from regularily opening a folder in Emacs from file explorer go, but surely both opening it by right-clicking on a folder and on it's background result in the working directory not setting correctly. For some reason it always sets to system32 folder, where as simply opening emacs with no folder specified sets it to it's own installation directory. To sum it up: it works in the default file explorer, but bugs in Files.

The command in registery which opens Emacs from folder's context menu is this:
"*path\to\emacs\root*\emacs-29.3_2\bin\runemacs.exe"  "%V"

### Files Version

3.5.0.0

### Windows Version

10.0.22631.3958

### Log File

[debug.log](https://github.com/user-attachments/files/16464077/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Can you confirm this is the same as #12950.

**Comment by BanishedBliss** [comment]
@Josh65-2201 Yes, sounds very similar. Getting the same System32 directory.

**Comment by Josh65-2201** [comment]
Thanks, We're going to keep tracking this there. You can check there or click subscribe in the right sidebar for updates.
