### ISSUE TITLE
Bug: Can't put commands in shortcuts files

### ISSUE THREAD

**Issue by Steperman5692** [files-community/Files#15928]
### Description

In Windows, u can create command in a shortcuts and it worked well on file explorer however in Files u cant create a shortcut with a command in it (It only worked on the desktop).

### Steps To Reproduce

1. Right click in a random folder (e.g Music folder)
2. Click New and then Shortcut 
3. Try to put a command (e.g winget upgrade --all) and it would say "Invalid location"

### Requirements

Files would not allow to put commands in shortcut.

### Files Version

3.5.0.0

### Windows Version

22631.3958

### Log File

[debug.log](https://github.com/user-attachments/files/16478384/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I reproduced this issue and have added this to the project board.

**Comment by yaira2** [comment]
A fix has been merged into `main` and will be included in one of the next updates.

**Comment by Steperman5692** [comment]
Thanks :)

**Comment by Steperman5692** [comment]
Didnt work :(

**Comment by Josh65-2201** [comment]
This fix isn't in an update yet

**Comment by yaira2** [comment]
@Steperman5692 did you compile the `main` branch?

**Comment by Steperman5692** [comment]
what does it mean?

**Comment by yaira2** [comment]
The fix isn’t officially released yet, but you can access it by building from the source code. I apologize if I misunderstood your earlier comment—I thought you had already tried that and found the fix didn’t work.
