### ISSUE TITLE
recycle bin not showing files

### ISSUE THREAD

**Issue by Wajdi-Y** [files-community/Files#15944]
### Description

![image](https://github.com/user-attachments/assets/67c25685-ef95-4a56-b357-a6d7ad58dce1)
the recycle bin not showing the files ! 

### Steps To Reproduce

just showing the recycle bin show this 
![image](https://github.com/user-attachments/assets/c8acddc0-700a-404f-af9a-cef54f974c22)

### Requirements

please solve the issue because the files is the default file manager 

### Files Version

v3.5

### Windows Version

last one

### Log File

no log

**Comment by 0x5bfa** [comment]
Thanks for the report.

Could you check if this is the same as #15083?

**Comment by yaira2** [comment]
Merging with #15083
