### ISSUE TITLE
constant cpu usage even in background and while not at use

### ISSUE THREAD

**Issue by AK220011** [files-community/Files#15940]
### Description

Constant cpu of about 3% while in foreground even when not using the app (having it just open while using other programs) and when closed but process running in background cpu usage is on average 3-8% and ram usage is around 400mb+ and doesn't drop, while at startup of the app it's around 120mb, now the ram isn't much of an issue just an anomaly.

### Steps To Reproduce

1. Start program
2. Close the window but have the setting checked to still run in the background
3. To lower ram use, restarting the app is necessary

### Requirements

Expected cpu usage below 3%, on average 0-1% when window is open but app isn't being used or when window is closed and app is running in background. For ram to drop from 400mb+ to around 120mb (same as at time of launching the app, without background process running beforehand).
![FILESHighCpuUsageAsBackgroundProcess2024-08-05_03-14](https://github.com/user-attachments/assets/2e33907e-f8ad-4d00-bd7f-e78e1d068c4a)

### Files Version

3.5.0.0

### Windows Version

10.0.22631.3958

### Log File

[debug.log](https://github.com/user-attachments/files/16489569/debug.log)

**Comment by yaira2** [comment]
Thanks for your feedback! Some processor usage is normal (the percentage depends on its overall capacity) but we’re actively working on reducing it (#4180). If you’d like to close Files completely, you can disable the setting that keeps it running in the background.
