### ISSUE TITLE
Can't type in text field in customization in a folder properties

### ISSUE THREAD

**Issue by Steperman5692** [files-community/Files#15941]
### Description

I was going to change the icon of a folder but it wouldn't let type inn the text field it would only let me select icons from shell32.dll.
There is a workaround tho, by clicking the "Browse" button i can select my icon file but faster for me to just type it out :(

### Steps To Reproduce

1. Right click a folder and select properties.
2. Go to customization menu.
3. Try to type into the text field and it wouldn't work :(

### Requirements

It wouldn't let me type in the text field in the customization menu in a folder properties

### Files Version

3.5.0.0

### Windows Version

22631.3958

### Log File

[debug.log](https://github.com/user-attachments/files/16489658/debug.log)

**Comment by yaira2** [comment]
@Steperman5692 thank you for reaching out, the path box is read only by design and the correct workflow is to click browse. Can you confirm if the browse popup works properly?

**Comment by Steperman5692** [comment]
Yeah its works fine but it would be nice if we can type the the text field :(

**Comment by 0x5bfa** [comment]
Well, we can make it acceptable, while we need error handling for path validation.

**Comment by Steperman5692** [comment]
wdym by that?

**Comment by 0x5bfa** [comment]
It was to @yaira2 
I'm not sure we'll plan to prioritize but this is pretty easy work.

**Comment by Steperman5692** [comment]
that would be pretty nice :D

**Comment by yaira2** [comment]
> Yeah its works perfectly fine but it would be nice if we can type the the text field :(

We prefer using the dialog as it has validation and error handling built in.

**Comment by Josh65-2201** [comment]
You can also type the path/filename in the path box of the dialog

**Comment by Steperman5692** [comment]
it's just nicer it we can type in it :(

**Comment by yaira2** [comment]
I get your feedback, I haven't made a final decision so it's still under consideration.

**Comment by yaira2** [comment]
Support will be added in the next update.

**Comment by Steperman5692** [comment]
Thank you all so much for adding this feature :)

**Comment by yaira2** [comment]
Enjoy!
