### ISSUE TITLE
Files not opening at Windows 11 startup

### ISSUE THREAD

**Issue by smarianimore** [files-community/Files#15959]
### Description

I configured Windows 11 to launch Files app at startup, but it doesn't start. I have to start it manually. Files is NOT configured as default.

### Steps To Reproduce

1. configure Win 11 to open Files at startup by adding Files as app in startup menu
2. shutdown
3. boot
4. Files is not opening

### Requirements

- Files should be launching autonomously if added to windows 11 startup apps (no?)

### Files Version

3.6.0.0

### Windows Version

Version	10.0.22631 build 22631

### Log File

[debug.log](https://github.com/user-attachments/files/16508423/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Can you make sure it enabled in `Files settings > Advanced > Open on Windows startup` and Task manager

**Comment by smarianimore** [comment]
yeah, checked both: the setting is checked and Files appear under startup apps in Task Manager

**Comment by Josh65-2201** [comment]
Can you disable `Files settings > Advanced > Leave app running in the background when the window is closed` and then try

**Comment by smarianimore** [comment]
Now it works! Apologies, I didn't think there would be an interaction between these two things at first, but it may make sense...

**Comment by Josh65-2201** [comment]
I think the Open on startup option could be changed to Open in background on Windows startup since Windows can control if Files open or not.
