### ISSUE TITLE
Deleting directory / files bug

### ISSUE THREAD

**Issue by mtdownz** [files-community/Files#15953]
### Description

Deleting a directory with a large amount of files shows incorrect file count (refer to screenshot)
![filesappbug](https://github.com/user-attachments/assets/9f857e1e-6856-4a42-9d8b-51b8f257712b)

### Steps To Reproduce

Delete a directory with numerous files

### Requirements

Eventually completes

### Files Version

3.6.0.0

### Windows Version

11

### Log File

[debug.log](https://github.com/user-attachments/files/16504762/debug.log)

**Comment by 0x5bfa** [comment]
Thanks for the report.

We assume this is an issue with Windows since PowerShell has also this issue. We're tracking this on in #13860, you can check there or click Subscribe to get notified of the further news on this later.
