### ISSUE TITLE
I need a folder directory tree

### ISSUE THREAD

**Issue by yiranbingyu** [files-community/Files#15963]
### What feature or improvement do you think would benefit Files?

It can help me jump different folder by folder directory tree.

### Requirements

such as:
now,I have in a folder ,it name A 
but I wang jump to folder B 
so ,I can point B in folder directory tree

### Files Version

3.5.0.0

### Windows Version

10.0.22631.3958

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #1928. You can check there or click subscribe in the right sidebar for updates.
You can see the current issues with adding this feature to Files at https://github.com/files-community/Files/issues/1928#issuecomment-1634584639

**Comment by yair100** [comment]
@yiranbingyu Tree View is currently available in preview https://files.community/download. It will be included in the next stable release.

**Comment by yiranbingyu** [comment]
thanks everybody，files is a  beautiful files manager tools，but it's slowly !!!,I comeback to ms  explorer.

**Comment by yair100** [comment]
@yiranbingyu did you try the latest preview build? There are significant performance improvements currently being tested.
