### ISSUE TITLE
Buttons fro split panel

### ISSUE THREAD

**Issue by 7OH** [files-community/Files#15969]
### What feature or improvement do you think would benefit Files?

Hotkeys for split panel is not usable and we cannot remove split by hotkeys - need buttons on a panel

### Requirements

2 Buttons: 
split\unsplit vertically
split\unsplit horizontally

### Files Version

3.6.0.0

### Windows Version

10.0.22631.3958

**Comment by 0x5bfa** [comment]
Thanks for the feedback.

There're buttons for it at the top right of tabs. Can you check if those are what you're looking for?

**Comment by 7OH** [comment]
Cannot yfind any suitable button for show\hide this
![изображение](https://github.com/user-attachments/assets/da1bfd65-d979-4aac-b662-59de7fae7e0b)
alt+shift+v only show second panel\view - and cannot hide it

**Comment by 0x5bfa** [comment]
You can only hide active pane via Ctrl+Shift+W and you can switch focus via Ctrl+Shift+Right Arrow or Left arrow

**Comment by 7OH** [comment]
Will be usefull if it will be like in KDE's show\hide button + hotkey

**Comment by yaira2** [comment]
> Hotkeys for split panel is not usable

You can customize the key bindings from the Actions page in Settings, have you tried this yet?

**Comment by 7OH** [comment]
hotkey didnot hide, if panel already shows.
it's not about bad keys - it's about user experience.
pressing hotkey - it's good, but visible button for pressing with mouse with one hand - more usable.

**Comment by yaira2** [comment]
Got it! We don’t have plans for that at the moment, but we’re always keeping an eye on feedback and might adjust our plans in the future. In the meantime, could you help us out by confirming if you were able to assign a custom key binding?

**Comment by 7OH** [comment]
yes - i can. binding works,

**Comment by yaira2** [comment]
Thanks! And as I mentioned, we'll be watching for further feedback on this topic and will adjust our plans if/when interest picks up.

**Comment by mdtauk** [comment]
Does the Close Pane button, not do what you are asking?
![image](https://github.com/user-attachments/assets/5d70cd7e-855e-4501-a5e9-fe086c1d6122)

**Comment by yaira2** [comment]
@mdtauk I'm sure that it does, but it sounds like they wanted an easier to access button.

**Comment by yaira2** [comment]
I'll work on adding the option to the context menu.

**Comment by yaira2** [comment]
![image](https://github.com/user-attachments/assets/2408c996-06e3-444d-a29f-17e52742b87a)

**Comment by 7OH** [comment]
https://github.com/user-attachments/assets/a52bc075-5f8f-4b5b-b621-bf0ec1268421

So - from 1 button with 2 functions - hard to realise ?

**Comment by Lukiluc29** [comment]
> 2_func_button.mp4 
> So - from 1 button with 2 functions - hard to realise ?

Same as the button to display the information panel of a file?
![Capture d'écran 2024-08-11 180220](https://github.com/user-attachments/assets/4cf4389b-8cf4-4502-84fb-27b1080d23b1)

**Comment by yaira2** [comment]
> So - from 1 button with 2 functions - hard to realize ?

Unfortunately it's not as simple as it sounds. The toolbar in Files already has a lot of options, and adding more would make it quite crowded. We’re considering the possibility of allowing users to customize which options are shown on the toolbar, but we don’t have anything to share on that publicly just yet.

**Comment by 7OH** [comment]
> > 2_func_button.mp4
> > So - from 1 button with 2 functions - hard to realise ?
> 
> Same as the button to display the information panel of a file? ![Capture d'écran 2024-08-11 180220](https://private-user-images.githubusercontent.com/128183422/356890396-4cf4389b-8cf4-4502-84fb-27b1080d23b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzOTI0NzYsIm5iZiI6MTcyMzM5MjE3NiwicGF0aCI6Ii8xMjgxODM0MjIvMzU2ODkwMzk2LTRjZjQzODliLThjZjQtNDUwMi04NGZiLTI3YjEwODBkMjNiMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMVQxNjAyNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzg0ZTQ4NWYzNjM0NTIzYjUwZTJjNDY4OGRkYjcwMzUzZWJjYTk3NzJlYjkyNmU2N2Y1ZjE2YzdmMzljMzAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CBrMoMy2Rv8Jgz_xxX_blvaCWLzOVHMGZeeQQHYY5VQ)

On a video - not information. On a video ONE button.
For SHOW and for HIDE second panel.
Instead of holding in memory TWO separate hotkeys.

**Comment by Lukiluc29** [comment]
> ![image](https://private-user-images.githubusercontent.com/39923744/356888626-2408c996-06e3-444d-a29f-17e52742b87a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzOTI4MDIsIm5iZiI6MTcyMzM5MjUwMiwicGF0aCI6Ii8zOTkyMzc0NC8zNTY4ODg2MjYtMjQwOGM5OTYtMDZlMy00NDRkLWEyOWYtMTdlNTI3NDJiODdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDE2MDgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmNjk1N2Q5Yzc3ZTE1NTFmNjEzZjJmOTBmYzAyZTI3Y2VjMmMyOTA4NDIxZDYwNDBkYWJkOWZmMjI1ZjVlNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xGtI0v6zC6CAEqpNKjoGLaLMfjHmds_thnFNsedKVHU)

The context menu with the option to close the panel should also appear when you right-click on the home page, because currently, right-clicking on the home page does nothing.

**Comment by yaira2** [comment]
We're tracking a similar in #14426.
