### ISSUE TITLE
Feature: HotKey for start app

### ISSUE THREAD

**Issue by 7OH** [files-community/Files#15968]
### What feature or improvement do you think would benefit Files?

As in OneCommander - need hotkey to start app or even ability for replace original explorer

### Requirements

option with hotkey

### Files Version

3.6.0.0

### Windows Version

10.0.22631.3958

**Comment by 0x5bfa** [comment]
thanks for the feedback.

If you want to launch Files via global shortcut  you can set 'Set Files as default file manager' from Settings > Advanced. Also this option should work for you if you any Files when you click File Explorer icon or Explorer.exe file

**Comment by 7OH** [comment]
This options is good, but in some cases will be usefull to left original explorer as default.
Thanks in advance

**Comment by 0x5bfa** [comment]
It's interesting.
Redirecting to @yaira2.

**Comment by Josh65-2201** [comment]
You can pin Files to the task bar and put it as the first then use `Win + 1`

**Comment by yaira2** [comment]
Another option is to create a shortcut to `files.exe` and assign a key binding from the properties window. Ironically the ability to assign key bindings to a shortcut file isn't currently supported in Files so you'll have to use File Explorer to set this up.

**Comment by 7OH** [comment]
![изображение](https://github.com/user-attachments/assets/fb7d3aeb-d035-451d-aee2-605894bf39d6)
win+ and hotkey for another one shortcut - is's all - workarounds.
Understood, but WIN+  - already binded for my apps. 
And shortcut .... can easily forget - where this shortcut binded

**Comment by yaira2** [comment]
Did you try the option to replace File Explorer?
