### ISSUE TITLE
Error Installing

### ISSUE THREAD

**Issue by yayator** [files-community/Files#15967]
### Description

Hello

When trying to install, i get an error that says package name does not match expected package name. The rest of the message is cutted. See the capture of the installer.

Thanks and have a nice day.

### Steps To Reproduce

Install with installer.

### Requirements

- e.g. Fix crash that occurs when...
Install with installer

### Files Version

3.6.0.0

### Windows Version

22631.3958

### Log File

[debug.log](https://github.com/user-attachments/files/16517706/debug.log)
![Captura de pantalla 2024-08-07 045147](https://github.com/user-attachments/assets/ec2b3210-0d39-4d75-8d08-544b46f9e3fb)

**Comment by yaira2** [comment]
@yayator do any of the [alternative methods](https://files.community/docs/install#:~:text=Install%20via%20PowerShell) listed on our docs page work on your device?

**Comment by yayator** [comment]
Hello

Thanks for the quick response. I tried other methods, but don't work. Same error.
Attached screenshot of powershell


________________________________
De: Yair ***@***.***>
Enviado: miércoles, 7 de agosto de 2024 5:14
Para: files-community/Files ***@***.***>
Cc: yayator ***@***.***>; Mention ***@***.***>
Asunto: Re: [files-community/Files] Error Installing (Issue #15967)


@yayator<https://github.com/yayator> do any of the alternative methods<https://files.community/docs/install#:~:text=Install%20via%20PowerShell> listed on our docs page work on your device?

**Comment by 0x5bfa** [comment]
Sending message from email doesn't work with images. Please send it via GitHub directly

**Comment by Josh65-2201** [comment]
Can you try
1. Make sure Files is closed from the system tray
2. Open an admin PowerShell window (Windows default not PowerShell 7)
3. Run the below
```
Get-AppXPackage Files* | Remove-AppXPackage
```
4. Check the Start menu > All apps for Files
