### ISSUE TITLE
The ability to switch from Windows to Linux is Doalboot.

### ISSUE THREAD

**Issue by githuborcun** [files-community/Files#15970]
### What feature or improvement do you think would benefit Files?

The ability to switch from Windows to Linux is Doalboot.

### Requirements

- option with hotkey

### Files Version

3.6.0.0

### Windows Version

10.0.26120.1340

### Comments

The ability to switch from Windows to Linux is Doalboot.

**Comment by 0x5bfa** [comment]
Files is supported only on Windows.
We have no plan to transplant the codebase to be able to be built on Unix-like OS.

**Comment by yaira2** [comment]
@githuborcun I'm not sure I understand what you're requesting, can you provide some more info to help understand the request?
