### ISSUE TITLE
Performance Issues: Laggy and Unresponsive Compared to Windows Explorer

### ISSUE THREAD

**Issue by ShamsSayied** [files-community/Files#15978]
### Description

I'm experiencing significant performance issues while using the Files-Community software. The application is noticeably laggy and unresponsive, especially when compared to the native Windows Explorer. Navigating through directories, opening files, and performing basic file operations are much slower, leading to a frustrating user experience.

Details:
Version: Files-Community 3.5
Operating System: Windows 10
Hardware Specs: HP Pavilion 15 AU171TX i5 7th Gen With 12GB RAM

### Steps To Reproduce

Open Files-Community.
Navigate through multiple directories quickly.
Try to open a file or move between folders.
Notice the delay and lag in response time.

### Requirements

The application should be as fluid and responsive as Windows Explorer, providing a smooth experience when navigating files and directories.

### Files Version

3.5

### Windows Version

10

### Log File

n\a

**Comment by hez2010** [comment]
Can you update to Files 3.6 and try again?

**Comment by yaira2** [comment]
Thanks for your feedback! We’re working hard to improve performance, but it’s a gradual process. You can track our progress in issue #4180. In v3.6, we’ve made loading large folders smoother. We’re also working on improving startup time and hope to have more to share on this by early 2025. Stay tuned!
