### ISSUE TITLE
Provide `.MSIX` installation packages in `/releases`.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [files-community/Files#15973]
### What feature or improvement do you think would benefit Files?

As https://github.com/microsoft/winget-pkgs/issues/150390#issuecomment-2068318185 demonstrates, these are technically available for the stable version, but incredibly difficult to locate. That should be remediated when that issue is closed, but it doesn't apply to https://github.com/microsoft/winget-pkgs/issues/166364#issuecomment-2273528233, for which solely an interactive `.AppInstaller` file is provided.

### Requirements

I don't quite understand the purpose of this section, but there are no evident dependencies.

### Files Version

https://github.com/files-community/Files/releases/tag/v3.6 per https://github.com/files-community/Files/releases/latest

### Comments

https://github.com/PolyMC/PolyMC/issues/1601#issue-1877941253 provides additional rationale.

**Comment by Josh65-2201** [comment]
Thanks for the feedback, They already have a URL for both stable and preview and only need the version number updated. The issue I had wasn't with the URL and the current issue with adding it is likely on Winget side https://github.com/microsoft/winget-pkgs/pull/150504#issuecomment-2271593794

**Comment by yaira2** [comment]
We don’t offer standalone MSIX packages because they require specific dependencies to be installed beforehand, and we can’t provide the support needed for any confusion this might cause. However, you can access the MSIX file for the preview version here
`https://cdn.files.community/files/preview/Files.Package_3.6.0.0_Preview_Test/Files.Package_3.6.0.0_x64_arm64_Preview.msixbundle`.

**Comment by Josh65-2201** [comment]
They have both URLs for offline installs and Winget can install the dependencies. Right now there an issue with Winget installing them https://github.com/microsoft/winget-pkgs/pull/150504#issuecomment-2271593794 last time it was install VClibs

**Comment by Josh65-2201** [comment]
There has only been one case of the issue there having and it was report by the user it was on there side https://github.com/files-community/Files/issues/15162

**Comment by RokeJulianLockhart** [comment]
> https://github.com/files-community/Files/issues/15973#issuecomment-2273672086

@Josh65-2201, so you would suggest that I revert https://github.com/microsoft/winget-pkgs/issues/166364#issuecomment-2273660318, I expect?

**Comment by Josh65-2201** [comment]
I assume you mean not to use https://files.community/appinstallers/Files.preview.appinstaller, if so yes. 
When there made we can probably have the files community bot update the URL when there a new update for that version

**Comment by RokeJulianLockhart** [comment]
> https://github.com/files-community/Files/issues/15973#issuecomment-2273691466

@Josh65-2201, that's not what I meant. I should have been more clear by not using a double-negative. To rephrase: despite https://github.com/files-community/Files/issues/15973#issuecomment-2273648537, do you suggest that I use the MSIX package you've linked as the installer URI for the request? If so, why?

**Comment by Josh65-2201** [comment]
App installers files don't work according to them https://github.com/microsoft/winget-pkgs/issues/166364#issuecomment-2273528233 and the one I link is the same as format as stable is working.

The URL I gave is also is what used everywhere else and will be staying, it was discussed at some point that preview may get it own separate installer like stable one and the app installer URL won't be there if it happens

**Comment by Josh65-2201** [comment]
@RokeJulianLockhart Files is now available to download on Winget
