### ISSUE TITLE
Feature: Adjust spacing

### ISSUE THREAD

**Issue by BerndFC** [files-community/Files#15979]
### What feature or improvement do you think would benefit Files?

The distance between rows and columns is very high. Can this be reduced, e.g. from 1.0 to 0.5?
	 
 

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.6.0.0

### Windows Version

22631.3958

**Comment by yaira2** [comment]
@BerndFC you can adjust spacing from the layout picker.
![image](https://github.com/user-attachments/assets/eba8318f-6d33-47b5-86b4-240dc1a8d993)

**Comment by BerndFC** [comment]
Oh yes, great! I used this on ICON size, but did not recognize that it works also on detailed view line spacing.

Perfect!

Von: Yair ***@***.***>
Gesendet: Freitag, 9. August 2024 16:45
An: files-community/Files ***@***.***>
Cc: Bernd Fleckenstein ***@***.***>; Mention ***@***.***>
Betreff: Re: [files-community/Files] Feature: Adjust spacing (Issue #15979)


@BerndFC<https://github.com/BerndFC> you can adjust spacing from the layout picker.
image.png (view on web)<https://github.com/user-attachments/assets/eba8318f-6d33-47b5-86b4-240dc1a8d993>

**Comment by yaira2** [comment]
@BerndFC thanks for confirming.
