### ISSUE TITLE
Rename files of different file types without changing the file types

### ISSUE THREAD

**Issue by PBGH24** [files-community/Files#15977]
### What feature or improvement do you think would benefit Files?

It should be possible to select and rename multiple files, even if they are different file types. Renaming should not change the file type. After multiple selection and renaming, for example photo_, the renaming results should be photo_1, photo_2, photo_3 ect..... for all selected files.

### Requirements

1. multiple selection of files
2. rename function for files
3. renaming of file names without changing the file type (the file type should not be changed)
4. the new name should always be increased by a number in the name. New name photo_, then all marked files are renamed with photo_1, photo_2, photo_3 etc.

### Files Version

3.6.0.0

### Windows Version

10.0.22631.3958

### Comments

This would be another unique selling point compared to other file explorers and not even the Windows File Explorer can do this. It would also be a great relief if, for example, you could rename files from a theme with a name and subsequent numbers. For example:
Photo_2024_01, Photo_2024_02.tif, Photo_2024_03.jpg, Photo_2024_04.heic,.....
or
Housebuilding_2024_01.doc; Housebuilding_2024_02.xls, Housebuilding_2024_03.pptx,....

In the attachment you see rename function from Windows File Explorer with multi selected files (A), but the numbering is not very well (B), (C)., With files a renaming if not possible if you select more than one file (D).

![Renamefunction_WindowsExplorer](https://github.com/user-attachments/assets/b86ba19c-ee47-47b5-acbb-29ecbe692e6d)
![Renamefunction_Files_not_possible_with_multiselected_files](https://github.com/user-attachments/assets/c52e33c1-b660-4293-bdad-7f196662b556)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #8191. You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
In the meantime, we recommend the Power Reanme feature in PowerToys.
