### ISSUE TITLE
Feature: Add 'compress' attribute to folder/file

### ISSUE THREAD

**Issue by timofeika** [files-community/Files#15976]
### What feature or improvement do you think would benefit Files?

Tried to set extended attribute 'compressed' to big text file, and didn't find how to set this attribute. In properties of the file i can set only 'read only' and 'hidden'.

### Requirements

- Add checkbox to attributes section for "compress" (only for NTFS file systems)

### Files Version

3.6.0.0

### Windows Version

22635.4005

**Comment by 0x5bfa** [comment]
Thanks for the feedback.

Fyi this is an easy work; just call SetFileAttributesW using FILE_ATTRIBUTE_COMPRESSED flag, as we do similar for the hidden attribute.

**Comment by timofeika** [comment]
Sure, thinking to rewrite it to Rust, Kappa.

**Comment by yaira2** [comment]
Thanks for the feedback

**Comment by 0x5bfa** [comment]
Turned out that the dedicated function is DeviceIoControl with FSCTL_SET_COMPRESSION IOCTL control code. But still up-for-grabs.

**Comment by yaira2** [comment]
> Fyi this is an easy work; just call SetFileAttributesW using FILE_ATTRIBUTE_COMPRESSED flag, as we do similar for the hidden attribute.

@0x5bfa I've tried this but it doesn't seem to work. You can find my code in `ya/CompressedAttribute`.

**Comment by yaira2** [comment]
This feature will be included in the new update.
