### ISSUE TITLE
Typing to find file name in list doesn't bring highlighted file into view

### ISSUE THREAD

**Issue by outdoorsdev** [files-community/Files#15982]
### Description

Typing to find file name in list doesn't bring highlighted file into view.

i.e. You are in a folder with a lot file, you know the first few letters of the filename, start typing, and expecting it to be highlighted and brought into view. It's highlighted but not brought into view in List view.

### Steps To Reproduce

1. Be in list view in a folder with a large amount of files
2. Start typing filename to hightlight/move to file like in Windows Explorer
3. File is highlighted, but Files isn't hovered/centred to that file as expected

### Requirements

Change behaviour so selected file is centered on screen

### Files Version

3.6.0.0

### Windows Version

10.0.19045.4046

### Log File

Not needed

**Comment by Josh65-2201** [comment]
Thanks for the report, Are you using compact size (slider to lowest)?

**Comment by Josh65-2201** [comment]
Thanks for the information, We're tracking this in #15955. You can check there or click subscribe in the right sidebar for updates.
