### ISSUE TITLE
Crashes when trying to paste files

### ISSUE THREAD

**Issue by kwolf111316** [files-community/Files#1598]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Comment by yaichenbaum** [comment]
Does this issue still exist in v0.15.4?
