### ISSUE TITLE
Decouple SMB from UI

### ISSUE THREAD

**Issue by CaCTuCaTu4ECKuu** [files-community/Files#15986]
### What feature or improvement do you think would benefit Files?

While most of casual users will find Files better that explorer I'm sure there is A LOT of people, including casuals, who uses network shares, and I must say it's basically unusable when there's no high speed connection (and as I see from reports there a lot of smb issues).
From my point of view while you cant do a lot with smb when there's a bad connection it's unacceptable that application basically freezes while loading shares, directories and files (and I'm on adsl r.n. which is not so bad)
So my thought on that is next - is it possible to decouple application layer from presentation layer? Can it work in bg thread? I was thinking about it since explorer itself completely hung system up for *timeout* seconds when there's not access to file share when file dialog windows opens.
And moreover with multiwindow application, when you can open folder in one tab and switch to other it's even more unacceptable.

### Requirements

- Fixing bug with application freezing issue
- Incomparably better perceived user experience
- (Prospect) Remote folders caching
- Potentially fixing a lot of bugs regarding slow interactions with remote folders

### Files Version

3.6.0.0

### Windows Version

Win 11 22631.3880 (Windows Feature Experience Pack 1000.22700.1020.0)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #12704. You can check there or click subscribe in the right sidebar for updates.

Right now if you a lot of network drive you can still use Windows File Explorer along side Files. We're working on improvements to give it the same performance as local drives. Files freezing also happens on local drives but often they load faster so it doesn't show.
Caching the network drive often won't be usable either as it still has to load once and if the contents change outside of Files won't show the correct files/folders and have to reload with the same issues as now.

**Comment by CaCTuCaTu4ECKuu** [comment]
> We're tracking this in #12704
Yes, that's a issue as well, but I'm talking about different thing. Even when explorer open folder when connection is slow it's not a modern EX - nothing visibly loading, nothing showing, empty space or nothing happens at all and then suddenly something opens or error pops (nice to see error when you already moved to different place and folder)

I'm talking about UI/UX here, but to see it something must be changed.

Main claim - to have noticeable, contrast loading indicator on workspace or somewhere it's obvious
And of course app itself must stay interactive, if tab is opened you must be able to navigate other tabs and see when content is ready, situations when you need to do something quickly and in local folder, but have to wait until pinned and favorites locations accessibility complete before you can do anything at all should not happen



> Caching the network drive often won't be usable either as it still has to load once and if the contents change outside of Files won't

It's only my vision, not a current suggestion, but it would be very nice if you can open share and last files and folders are grayed or have some marking that they are from cache, while in BG it's loading. Main point is to be able to navigate and see files, not file caching ofc.
And if you navigate through there can be not so complicated logic how to react in the tab when opened.
Imagine how fast and responsive would it be if you can navigate to some folder on remote server and wait only fow loading structure of that last folder and not to wait all of them and is it's gone you just routed to last existing location with it already loaded actual structure
