### ISSUE TITLE
Autodesk cloud drive appears 30 times

### ISSUE THREAD

**Issue by bassgeeek** [files-community/Files#15980]
### Description

One of my cloud sources is Autodesk Drive. In Windows Explorer, the drive appears as a drive with nested folders as normal. In Files, Autodesk_C appears 12 times. All subfolders are also shown at the top level. 

### Steps To Reproduce

1. Open cloud sources
2. See duplicated Autodesk drive

### Requirements

This has been the condition since I first tried Files months ago.

### Files Version

3.6.0.0

### Windows Version

10.0.22631.3958

### Log File

[debug.log](https://github.com/user-attachments/files/16568442/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #15743. You can check there or click subscribe in the right sidebar for updates.
