### ISSUE TITLE
View settings outside of the main Files screen

### ISSUE THREAD

**Issue by outdoorsdev** [files-community/Files#15983]
### What feature or improvement do you think would benefit Files?

I'd like to be able to move the settings screen around outside of the Files screen so we can see the changes affecting the program.
Otherwise, each time I change a setting I have to close settings, check the change, open settings again, go back to the right tab, scroll to the setting, and change it again.

### Requirements

- Allow settings screen to be moveable

### Files Version

3.6.0.0

### Windows Version

10.0.19045.4046

**Comment by yaira2** [comment]
Thank you so much for your feedback! We’re excited to let you know that we’re working on moving the settings to a tab, similar to what you see in Edge. While it’s still in the planning stages and we don’t have much to share on GitHub just yet, we’re confident that this change will solve your use case.
