### ISSUE TITLE
Transparent context menu background

### ISSUE THREAD

**Issue by CaCTuCaTu4ECKuu** [files-community/Files#15985]
### Description

Can't work with this. It's just completely transparent

![image](https://github.com/user-attachments/assets/ce9df798-3bb6-4881-908f-e9376c1b873c)

### Steps To Reproduce

I have no clue how that happens. Before I notice I make only few interactions with settings:
1. Check over bg materials in appearance
2. Set as default File manager
3. ???

### Requirements

Whenever I call context menu, anywhere, context menu BG is missing, no matter of settings

### Files Version

3.6.0.0

### Windows Version

Win 11 22631.3880 (Windows Feature Experience Pack 1000.22700.1020.0)

### Log File

[debug.log](https://github.com/user-attachments/files/16570277/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Please try turning off `Windows Settings > Personalization > Colors > Transparency effects` > Restart Files from the system tray > See if the context menu background is shown.

**Comment by CaCTuCaTu4ECKuu** [comment]
Not from system tray, but closing it from Task manager and then again as Background task helped
Looks like when It was in deep sleep and not rebooted, love Windows ❤️
