### ISSUE TITLE
Git Pull doesn't work with GitHub Enterprise repos

### ISSUE THREAD

**Issue by jimtut** [files-community/Files#15996]
### Description

When a local repository is a clone from GitHub Enterprise the Git Pull operation does not work and gives a timeout. The time out occurs immediately, not after any delay. It seems as if the application is not using the git client and the ssh keys installed locally but must be doing something entirely contained inside the application. Please allow support for the git client installed on the computer, which would automatically allow support for GitHub Enterprise.

### Steps To Reproduce

Clone a repository from GitHub Enterprise using Git components installed on the PC. Then browse to that repository using this application and attempt to do a git pull.

### Requirements

Use the get components already installed on the PC so that no native git integration is not even needed in this application and then you can support any different number of git servers not just GitHub Enterprise.

### Files Version

3.6.0.0

### Windows Version

10.0.22621.3880

### Log File

[debug.log](https://github.com/user-attachments/files/16581630/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback! We’re actively tracking this issue in #14453.
