### ISSUE TITLE
grid view doesn't show any space characters in a filename

### ISSUE THREAD

**Issue by andrew-james-heard** [files-community/Files#15995]
### Description

Say I have file name "file name.txt". In grid view when I press F2 to rename the file & use the cursor to move between characters, the space character is not evident.

### Steps To Reproduce

1. In grid view press F2 to rename a file that contains 1 or more space characters in the name
2. the space character is not evident/ can't be deleted
3. press <space> anywhere & the name doesn't change/ the new characters are not evident

### Requirements

- e.g. Fix crash that occurs when...
make editing filenames more like Windows Explorer
note that editing in the Details view works fine

### Files Version

3.6.1.0

### Windows Version

23H2

### Log File

[debug.log](https://github.com/user-attachments/files/16578605/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I can't reproduce this. Can you send a screenshot of what your seeing

**Comment by andrew-james-heard** [comment]
For example, in this screen cap there is a space after each word in the filename. Observe the cursor position. When I press the cursor+right key the cursor ignores the space character & is then positioned after the next non-space character. Equally if say each word had 3 spaces between them, pressing the cursor+right key ignores all 3 spaces & the is still moved after the next non-space-character, ignoring the spaces.
![20240813-081105-Desktop (5) - Files](https://github.com/user-attachments/assets/25e836db-03f1-46c2-985c-1cc930780c16)

**Comment by Josh65-2201** [comment]
If the text cursor is positioned before the h then it's at the space character. This is how text box's work in Windows and would have the same behavior as other programs

**Comment by andrew-james-heard** [comment]
I would not expect pressing a cursor-right key to go directly from one non-space character to the next & essentially ignore 1 or more space characters in between. This is what currently happen(ed) in Grid view. When I checked in Explorer, it had the behavior I would expect - see screen cap
![20240815-144104-Desktop](https://github.com/user-attachments/assets/76a688e0-795e-422c-888a-a9aa3576f6e3)
but to my surprise, when I switch back to FilesPreview it is doing the same as Explorer too. So, like you, I can no longer reproduce it. Clearly it was happening otherwise I wouldn't have bothered to raise the issue. I'll wait until I experience it again for more info.

**Comment by yaira2** [comment]
@andrew-james-heard I was able to reproduce the behavior you’re describing when text wraps onto multiple lines. Interestingly, I noticed the same behavior in both Windows Notepad and File Explorer. Since this seems to be in line with the expected behavior, I’ll go ahead and mark this issue as resolved.
