### ISSUE TITLE
Unable to drag-and-drop video files onto Media Player Classic to open

### ISSUE THREAD

**Issue by saintcazaril** [files-community/Files#15994]
### Description

When I try to drag-and-drop a video file onto Media Player Classic (MPC-HC) from the Files window, it gives me an "Error when dropping file" error. The same occurs when trying to drag-and-drop a folder containing video files onto MPC-HC.

I do not get the error when using VLC, and I have no problems dragging and dropping into MPC-HC when using Windows Explorer. I tried other video files and multiple video filetypes (.mkv, .wmv, .mp4, .mov) and had the same result.

I also tried dragging and dropping other file types in other applications, but couldn't find any others that had the same behavior.

### Steps To Reproduce

1. Open Media Player Classic (MPC-HC from K-Lite Codec Pack)
2. Open Files to directory with video file(s)
3. Drag-and-drop video file (or folder containing video file(s)) onto MPC-HC window

### Requirements

Fix "Error when dropping file" error that occurs when dragging and dropping video files onto Media Player Classic

### Files Version

3.6.0.0

### Windows Version

10.0.22631.3958

### Log File

[debug.log](https://github.com/user-attachments/files/16577352/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, We're tracking this in #15564 . You can check there or click subscribe in the right sidebar for updates.
