### ISSUE TITLE
"Sync layout and sorting preferences across directories" appears to be on even when off 

### ISSUE THREAD

**Issue by Steperman5692** [files-community/Files#15991]
### Description

Basically I was just resizing items in a folder and I realize all my folder where the same size as the folder I change items size to; even thoughts I have disable "Sync layout and sorting preferences across directories" disable in settings.

### Steps To Reproduce

1. Go to Settings then click on Layout then turn off "Sync layout and sorting preferences across directories".
2. Quit the Settings, choose a folder that has files in it of your choice and now click the Layout Button on the top-right.
3. Choose whatever mode you want (I'm choosing Grid for this example).
4. Slide the slider to whatever you want.
5. Go to another folder that has files in it and you can see the files has the same size as the previous folder.

### Requirements

"Sync layout and sorting preferences across directories" technically is on even tho its off.
BTW it is worth noting that if "Sync layout and sorting preferences across directories" is on on the and you choose another layout it it will applied the layout you choose.
I dont mean that "Sync layout and sorting preferences across directories" is entirely broken; I'm just saying that one of its functionality is broken.

### Files Version

3.6.0.0

### Windows Version

22631.3958

### Log File

[debug.log](https://github.com/user-attachments/files/16575512/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback! The sync layout and sorting preferences setting is intentionally not applied to folder sizes. If you’re interested in a deeper dive into this topic, feel free to check out the ongoing discussion in issue #15984.
