### ISSUE TITLE
No Next/Prev buttons when opening a picture within a folder with many pictures.

### ISSUE THREAD

**Issue by northglide** [files-community/Files#15997]
### Description

opening a picture to open it in the Photos app, opens it as if it was a separate-single pic and the Next/Previous arrows aren't displayed and also don't work with the keyboard.

### Steps To Reproduce

1. Select OneDrive pictures folder 
2. open one picture
3. no option to switch to the next one

### Requirements

should be able to switch between pictures in the folder

### Files Version

3.6.0.0

### Windows Version

10.0.22631.3958

### Log File

can't see the option

**Comment by rihards-simanovics** [comment]
The issue persists to version 3.7.11.0.

Here is some other info about my OS:
Windows 11 version: 10.0.22631.4391

@northglide are you able to reopen the issue?

**Comment by Josh65-2201** [comment]
We're tracking this in #15409. You can check there or click subscribe in the right sidebar for updates.

**Comment by rihards-simanovics** [comment]
Hey @Josh65-2201, thanks. Thought this issue was the original.
