### ISSUE TITLE
Add support for multiple Onedrive instances

### ISSUE THREAD

**Issue by ghost** [files-community/Files#16]
Hey. I have both my work Onedrive and personal Onedrive on my computer. Could I have separate instances for it?

Also, SharePoint support would be great.

Great app!

**Comment by duke7553** [comment]
Hello, I'm working on a solution for this. In the mean time, try the solution listed here to see if Files Recognizes and displays the mapped drive. https://www.laptopmag.com/articles/map-onedrive-network-drive

**Comment by zbalkan** [comment]
While multiple sessions for One Drive is a great suggestion, it's not the same with the SharePoint. Because when you use something other than SharePoint you lose several capabilities like metadata, tags, indexing attributes, ACLs, versioning etc.

**Comment by zbalkan** [comment]
I have come across a shell extension called [SharePoint Shell Extensions](https://sse.technology/). The way they make use of metadata and other features SharePoint provides seems efficient. That eliminates the disadvantages I have mentioned [before](https://github.com/duke7553/files-uwp/issues/16#issuecomment-500157419).

**Comment by yaichenbaum** [comment]
Support for multiple OneDrive accounts will be implemented with #2215.
