### ISSUE TITLE
Pinned Folders Vanished

### ISSUE THREAD

**Issue by adamjameskramer** [files-community/Files#16007]
### Description

At random times for a few hours or longer the pinned folders will vanish. Closing & opening, restarting etc nothing brings them back. 
![Screenshot 2024-08-13 085018](https://github.com/user-attachments/assets/e45a4dbb-cc34-4df9-94cb-7af0cdfa40df)

### Steps To Reproduce

unknown

### Requirements

Bring back pinned folders. 

### Files Version

3.6.0.0

### Windows Version

10.0.19045.4717

### Log File

[debug.log](https://github.com/user-attachments/files/16599972/debug.log)

**Comment by adamjameskramer** [comment]
Enable Files settings > Advanced > Open Files on Windows Startup **Already on**
Enable Files settings > Advanced > Leave app running in the background when the window is closed **Already on**
Restart Windows **Did this 2 times and the pinned files came back**
Open Files
See pinned items are missing

Thanks

**Comment by Josh65-2201** [comment]
The instructions are to turn off `Files settings > Advanced > Leave app running in the background`

**Comment by adamjameskramer** [comment]
![Screenshot 2024-08-13 105057](https://github.com/user-attachments/assets/c0850ef2-1aac-499f-880f-a4ce83d17611)

See image of my settings. Advice if anything is wrong.

**Comment by Josh65-2201** [comment]
Turn **OFF** `Files settings > Advanced > Leave app running in the background` then close and open Files

**Comment by ccrowles** [comment]
> Turn **OFF** `Files settings > Advanced > Leave app running in the background` then close and open Files

I was having the same issue but this worked as a temporary fix for me, thanks. Hoping it will get properly fixed soon because that feature was very useful.
