### ISSUE TITLE
Improve handling of permission elevation

### ISSUE THREAD

**Issue by Hissymaster** [files-community/Files#16009]
### Description

for whatever reason, deleting files permanantly from the recycle bin is... odd...

### Steps To Reproduce

1. go to the recycle bin folder "Shell:RecycleBinFolder"
2. select a folder with many subfolders.
3. attempt deleting it
4. refresh
5. it's back? why?

### Requirements

- 

### Files Version

3.6.1.0

### Windows Version

10.0.22631.4037

### Log File

[debug.log](https://github.com/user-attachments/files/16607708/debug.log)

**Comment by 0x5bfa** [comment]
Thanks for reaching out.

How many (approx) did you delete?

**Comment by Hissymaster** [comment]
It appears to struggle with handling files managed or owned by an administrator account? Or at least an account in a higher level than a normal user.

**Comment by Hissymaster** [comment]
It not just the recycle bin.

**Comment by Hissymaster** [comment]
It appears to me that when it runs into a folder OR FILE that needs more permissions that a base user, it fails to properly ask or elevate and everything falls apart, but files doesn't properly catch that.

**Comment by 0x5bfa** [comment]
Thanks for the heads up.

- Does that happen only on delete operation?
- When deleting them, Status Center displays a status for it?

**Comment by Hissymaster** [comment]
It affects any action. And although it appears to be complete in the status centre, refreshing tells you otherwise.

**Comment by STGYO** [comment]
I am also facing the same issue here. If I want to empty my recycle bin from the files app in the sidebar, the file is not getting deleted at all and remains in the folder. I can only go to the desktop to empty my recycle bin. But from the desktop the recycle bin folder from the files app is not opening by double-clicking at all.

**Comment by Hissymaster** [comment]
And it also appears files struggles with a lot of bulk delete, bulk move and other bulk actions

**Comment by Hissymaster** [comment]
it also seems to struggle deleting empty folders, if that helps.

**Comment by 0x5bfa** [comment]
> it also seems to struggle deleting empty folders, if that helps.

Is that folder lesser permission? Like, you (if you're admin Administrators group otherwise Users group, more specifically your own) don't have permission of 'Delete' access control?

**Comment by Hissymaster** [comment]
It doesn't matter if you're admin. It won't delete empty folders.

**Comment by 0x5bfa** [comment]
I meant if you have sufficient permission to delete it.

**Comment by Hissymaster** [comment]
Even if you have sufficient permissions, it doesnt work

**Comment by Hissymaster** [comment]
it appears to be fixed in the latest preview.

**Comment by Hissymaster** [comment]
I Think it specifically struggles with folders with ONLY subfolders. I might open a new issue.
