### ISSUE TITLE
Bug: "Leave app running in the background when the window is closed" doesn't work as expected

### ISSUE THREAD

**Issue by SmokedPete** [files-community/Files#16002]
### Description

When the Files application is opened, the application icon appears in the Tray, but as soon as the close button (X) is clicked, the icon disappears from the tray. The application also takes longer to open afterwards and the splash screen can be seen.

This leaves me to believe the app isn't kept opened in the tray as expect but is in fact closed.

Opened:
![image](https://github.com/user-attachments/assets/e2cc6fec-4451-46a2-888a-83c90a6cbe24)

Closed:
![image](https://github.com/user-attachments/assets/eaddc397-c7e3-4470-95ca-555207139a9a)

### Steps To Reproduce

1. Install the Files app using the classic installer
2. Enable `Open Files on Windows startup`
3. Enable `Leave app running in the background when the window is closed`
4. Enable `Set Files as the default file manager`
5. Open the tray, notice the Files icon is present
6. Close the app using the "X" button at the top right of the window
7. Open the tray, notice the Files icon is gone

Optional:
8. Re-open the app, notice the splash screen is visible and the start time is slower (full boot up of the app)

### Requirements

- The app should remain opened in the background even after clicking the "X" button on the window.
- The app should re-open quicker than a cold boot when opened in the background

### Files Version

3.6.0.0

### Windows Version

10.0.22631.3958

### Log File

[debug.log](https://github.com/user-attachments/files/16592870/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you open task manager and kill any processes that say Files and try again

**Comment by SmokedPete** [comment]
Welp, seems like it was that simple. Sorry!

**Comment by Josh65-2201** [comment]
Great that it's working for you. It shouldn't get stuck like that often but if it does you can comment here.
