### ISSUE TITLE
Please remove "Is this folder removed" question!

### ISSUE THREAD

**Issue by Assemblerguru** [files-community/Files#16008]
### What feature or improvement do you think would benefit Files?

I get this message very often, even if I have previously read a USB stick and it is no longer available (sometimes you only use it for a short time ;.). This message really annoys me because it is completely useless. I can neither see the folder that has been deleted, nor can I do anything about the fact that the tab can no longer be displayed. Suggestion: Either display the tab with the info: e.g. "Removed folder 'H:\Ministick" (or similar) or simply remove the tab without a message. And/or you make it possible to set this via the options
*** Translated with www.DeepL.com/Translator (free version) ***

### Requirements

- This proposal will accomplish the described improvement above

### Files Version

3.6.0.0

### Windows Version

10.0.22631.4037

**Comment by Josh65-2201** [comment]
Thanks for the report, You can close the tab or drive that are unused/unplugged. Please also check Files settings > General > Startup settings

**Comment by Assemblerguru** [comment]
Hi ! Okay, I set this to "Never" (or german "Nie"). So the popup "Do you have deleted the folder" is coming again after restart... I have used double panel viel.
![Screenshot 2024-08-13 224033](https://github.com/user-attachments/assets/ba59dc01-4483-4bd7-a8fb-4b964a53d8a5)

**Comment by Assemblerguru** [comment]
Okay. So I always used the option to open the last folders (like it is in notepad++ to have all documents open ;-). But now i will  use "Open a new tab"... that also is very much faster to startup

Thank you !
