### ISSUE TITLE
Replace existing

### ISSUE THREAD

**Issue by HC1Gunner** [files-community/Files#16017]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Other - list in description

### Description

Is there a place in the settings to disable "Replace existing", I transfer tons of files / folder everyday and being asking every time if I want to overwrite the existing file is really slowing down the process, and very annoying.

![Replace existing](https://github.com/user-attachments/assets/65f1ecfc-0f86-4f7c-a466-daec8d619704)

### Steps To Reproduce

Copy/paste a file.

### Expected behavior

Don't be asked every time, just do it.

**Comment by yaira2** [comment]
@HC1Gunner Thanks for asking! Currently, turning off this confirmation prompt isn’t available, but your last selected action will be remembered

**Comment by HC1Gunner** [comment]
1. It's not remembering, daily to weekly I'm updating text documents and
transferring them to another drive for the purpose of backup. It asks me
every time whether I want to overwrite.
2. Not sure what it's using to make / measure the x-fer, but it's also
taking forever to complete. I transferred a 10mb folder over and it took
way too long to complete. My system is pretty snappy with drives that have
high read/write.

Do I need to make  a new ticket under Feature Request?

**Comment by yaira2** [comment]
I meant that the selection in the dropdown menu is remembered, but you still need to confirm it. This is unlikely to change because we want to avoid any scenarios where a user might lose data and hold us responsible for it. Thanks for understanding!

**Comment by HC1Gunner** [comment]
I have no idea what Files is doing during data transfer, but it's extremely
inefficient.
I did a copy/paste of (10) mkv video files with a total size of 34.7 GB,
and this took (18) minutes to complete. I make these kinds of transfers all
the time on a daily basis from the same two drives that have fast
read/write speeds.
I've use Tera Copy Pro for years as is much better than windows default,
plus its filled with features. Tera Copy would have complete this
transfer in under (10) minutes, half the time it took Files. Tera Copy is
not worried about being sued, it seems it more like you app is collect data
and sending to you. I've been using windows (almost 40 years) since v.3.1,
I never once had data loss during a transfer of files or folders. With Tera
Copy I can pause a transfer, Files give no options, I can't cancel. It
pretty bogus when you override Windows settings and take over something as
simple as file transfers.

1. One, if you are doing a copy paste (in my case) then there is no need to
worry about data loss as you still have the original file that was copied.

**Comment by Josh65-2201** [comment]
Files doesn't take over Windows transfers it uses the same system as Windows File Explorer does, Terra copy will override operations in Windows File Explorer which Files can't see. It's planned to be able to use them in #7518.
