### ISSUE TITLE
Context Menu

### ISSUE THREAD

**Issue by Eric-1951** [files-community/Files#16010]
### What feature or improvement do you think would benefit Files?

The context menu in Files 3.6 does not show all the options to click on like Microsoft's File Explorer context menu. See pics. The top pic is using Files 3.6.0.  The bottom pic is with Microsoft's File Explorer.

![image](https://github.com/user-attachments/assets/1ca03fc7-7cfc-43af-be1f-f0c4dea2bdc2)
![Contex Menu Show More Options from Files 3 6 0 Screenshot 2024-08-14 164427](https://github.com/user-attachments/assets/f397e51d-91cd-4f24-ade0-3e0c2493882d)

_________________________________________________________________
![Contex Menu Show More Options from Microsoft File Explorer Screenshot 2024-06-26 153526 png](https://github.com/user-attachments/assets/1247bccd-1285-4284-b7e5-6ed305a9fe9f)

### Requirements

Using Windows 11 24H2, Microsoft File Manager, Files 3.6.0.

### Files Version

3.6.0.0

### Windows Version

10.0.26100.1457

**Comment by yaira2** [comment]
Aside from `Cast to device` & Bitdefender, can you clarify which options are missing?

**Comment by Josh65-2201** [comment]
Image rotation and set as and properties are present in that main options. If the image related ones aren't there can you say what image file type your right clicking on

**Comment by Josh65-2201** [comment]
Give access to is also not supported yet by Files and is tracked here https://github.com/files-community/Files/issues/13761 . You can check there or click subscribe in the right sidebar for updates.

**Comment by Eric-1951** [comment]
The option I need the most is for Bitdefender or any other Virus or Malware checking software.

**Comment by yaira2** [comment]
I believe it requires implementing #8251. We're working hard on this but it's challenging due to the lack of documentation. You can subscribe to #8251 to get updates on our progress. Thanks for your patience!
