### ISSUE TITLE
Flyout Theme doesn't properly update after System Theme Changed

### ISSUE THREAD

**Issue by morning4coffe-dev** [files-community/Files#16019]
### Description

![image](https://github.com/user-attachments/assets/b2c6ea11-9278-47d0-a90e-fb6770e71cbc)

### Steps To Reproduce

1. Open Files
2. Go to Windows settings
3. Change the whole system Theme (apps and system)

### Requirements

- Fix a theme issue on the Text in the Files Flyout 
- Fix Flyout theme on Show more options

### Files Version

3.6.0.0

### Windows Version

10.0.26120.1350

### Log File

N/A

NOTE: I am happy to look into this issue and investigate more, if assigned.

**Comment by yaira2** [comment]
Thank you for bringing this to our attention! This is a known issue with WinUI, and the best place to track it is on their GitHub repo. I’ve linked an existing issue below. It would be great if you could add a comment to let Microsoft know it’s still happening:: [GitHub Issue #4970](https://github.com/microsoft/microsoft-ui-xaml/issues/4597).

**Comment by yaira2** [comment]
Thank you for bringing this to our attention! This is a known issue with WinUI, and the best place to track it is on their GitHub repo. I’ve linked an existing issue below. It would be great if you could add a comment to let Microsoft know it’s still happening:: [GitHub Issue #4970](https://github.com/microsoft/microsoft-ui-xaml/issues/4970).
