### ISSUE TITLE
シングルクリックで操作したい

### ISSUE THREAD

**Issue by stIprurIJu** [files-community/Files#16018]
### What feature or improvement do you think would benefit Files?

エクスプローラーを使っていて、ずっとシングルクリックに設定していたので、ダブルクリックが大変不便です。シングルクリックで操作できるように出来ませんか？ 宜しくお願い致します。

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.6.1.0

### Windows Version

10.0.22631.4037

**Comment by Josh65-2201** [comment]
The option is in Files settings > Files & Folders > Opening items > Open items with single click

**Comment by stIprurIJu** [comment]
Thank you very much. Thanks to your help, I was able to solve the problem.
