### ISSUE TITLE
Bug: Incorrect behavior when scrolling with ctrl pressed

### ISSUE THREAD

**Issue by AryaPaw** [files-community/Files#16014]
### Description

When you scroll with the Ctrl key pressed in the standard Windows Explorer, the icons of folders and files are enlarged or reduced depending on the scroll direction (up or down). In Files, this behavior is inverted and works the other way around.

### Steps To Reproduce

1. Open any folder.
2. Press ctrl and scroll the mouse wheel up and down.

Perform these steps in the standard Windows Explorer and in Files. Compare the results.

### Requirements

Modify the behavior: when scrolling up, the icons should increase in size, and when scrolling down, they should decrease.

### Files Version

3.6.0.0

### Windows Version

10.0.22631.4037

### Log File

Not required

**Comment by yaira2** [comment]
Thanks for the report! I was able to reproduce the issue on my end too. Kind of awkward 😂
