### ISSUE TITLE
Allow variable length columns in list view. 

### ISSUE THREAD

**Issue by im4aratu** [files-community/Files#16024]
### What feature or improvement do you think would benefit Files?

Names of files and directories are truncated in list view if they are too long. In Windows explorer for example the columns in list view adapt to show the full name of files and directories.

### Requirements

This proposal will allow better viewing of filenames or directory names in list view.

### Files Version

3.6.0.0

### Windows Version

23H2 22631.4037

**Comment by 0x5bfa** [comment]
Thanks for the feedback.

You can double click on the column splitter in the column header.
Is it not what you want?

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #1033. You can check there or click subscribe in the right sidebar for updates.

**Comment by im4aratu** [comment]
Ah so I see I'm not the only one noticing this :)) I'll subscribe to that thread.
