### ISSUE TITLE
Various requests

### ISSUE THREAD

**Issue by cippinocipollino** [files-community/Files#16021]
### What feature or improvement do you think would benefit Files?

* THE COLUMN DISPLAY SEQUENCE SHOULD BE EDITABLE AS ON WINDOWS EXPLORER (I mean: if I want put the columns name, dimensions, date ecc... in a certain sequence)
* I'D LIKE TO INCREASE THE SIZE AND APPEARANCE OF THE HD IN THE HOME VIEW BUT I CAN'T FIND THE WAY
* IN "THIS PC" I CAN CHANGE THE SIZE OF THE HD BUT I CAN'T SEE THE GRAPHIC BAR THAT INDICATES THE CAPACITY AND SIZE OF THE SINGLE HD (10GB AVAILABLE  OF 100GB for example)
* THE TAGS ARE A GREAT FEATURE BUT ARE NOT VERY USEFUL BECAUSE THEY ARE LIMITED TO NTFS HD AND I DON'T UNDERSTANDABLE WHY..., SINCE MANY PCS HAVE MULTIPLE HDS OFTEN FORMATTED IN EXFAT OR OTHER FS!!!
* I'D LIKE TO HAVE MORE FEATURES REGARDING THE APPEARANCE, CREATION OF DIFFERENT THEMES CUSTROM ICON SETS AND OTHER THINGS...
* WHEN I EXECUTE A COPY, A CUT OR A PASTE OPERATION THE STATUS BAR OF THE OPERATION DOES NOT APPEAR AND I CANNOT UNDERSTAND IF IT IS EXECUTING AND IF IS FINISHED OR NOT… I THINK IT'S A BUG. I use both the 3.6 FIles version and the Insider Preview: the result is the same.If a make copy, paste, cut in the windows explorer all works well. The problem is only in your program. I use the last version of Windows 11.

Thanks
Max

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.6 and Preview Insider

### Windows Version

10.0.22631 build 22631 23H2

### Comments

Bravi!

**Comment by yaira2** [comment]
Thank you so much for your feedback! 😊 Many of the items you’ve mentioned are already being tracked, and you can find them by searching for existing issues. For the others, could you please open individual feature requests? This will help us address each one more effectively. Thanks again!

**Comment by Josh65-2201** [comment]
Thanks for the feedback, please make future request separate per feedback.

> THE COLUMN DISPLAY SEQUENCE SHOULD BE EDITABLE AS ON WINDOWS EXPLORER

We're tracking this in #8385. You can check there or click subscribe in the right sidebar for updates.

> I'D LIKE TO INCREASE THE SIZE AND APPEARANCE OF THE HD IN THE HOME VIEW BUT I CAN'T FIND THE WAY
IN "THIS PC" I CAN CHANGE THE SIZE OF THE HD BUT I CAN'T SEE THE GRAPHIC BAR THAT INDICATES THE CAPACITY AND SIZE OF THE SINGLE HD (10GB AVAILABLE OF 100GB for example)

The size information is on the home page
![image](https://github.com/user-attachments/assets/c312cbd4-065f-4459-948d-33c7cfc65454)


> THE TAGS ARE A GREAT FEATURE BUT ARE NOT VERY USEFUL BECAUSE THEY ARE LIMITED TO NTFS 

There currently use ADS (Alternative data stream which are only available on NTFS or REFS drive). We're tracking expanding this in #15272. You can check there or click subscribe in the right sidebar for updates.

> WHEN I EXECUTE A COPY, A CUT OR A PASTE OPERATION THE STATUS BAR OF THE OPERATION DOES NOT APPEAR

It is shown in the top right next to the settings button. Showing this when it started is been tracked in #13560. You can check there or click subscribe in the right sidebar for updates.
