### ISSUE TITLE
Files a beta app at best- unloads ms explorer if probs

### ISSUE THREAD

**Issue by Pisseduser** [files-community/Files#16023]
### What feature or improvement do you think would benefit Files?

Files (like openshell):needs to be free & updated & improved for direct installation in Windows- this is ridiculous at best to have to be online & uninstalling ms file explorer is a braindead idea if something goes bad-apps like this are disservice to users when in "beta" yes I tried new version download, but it refers you to Ms store- now who wants to use ms spyware when getting apps even for free-ehole thing is out of control, but majorgeeks download is bogus-ware too, it does not install offline- who came up this bad idea-replace them, especially for trying to charge for using the spp6

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z
X=offline installation option & don't charge for app
Y=fix uninstall ms file explorer or don't uninstall it at all 
Z=fix ms store ver to be compatible w/ free offline ver

### Files Version

I have used them all from GitHub & files site & ms store

### Windows Version

Win 11 pro

### Comments

It's a pretty good app when it installs easily, but many people don't like being online for very long b/c of potential security probs & GitHub has some....a d discord itself has been hacked & ms owns site-...

**Comment by 0x5bfa** [comment]
Thank you for the feedback.

> needs to be free & updated & improved for direct installation in Windows

we already support offline installation via our own classic installer.

> this is ridiculous at best to have to be online & uninstalling ms file explorer is a braindead idea

I'm not sure I get what uninstalling file explorer means, but if you meant replacing default explorer with Files, it's in Advanced feature list and you can turn it on or off.

> I tried new version download, but it refers you to Ms store

If you have Files installed already, you don't need to install from MS store or from our website again but the app installs update by itself when online.

> now who wants to use ms spyware when getting apps even for free-ehole thing is out of control, but majorgeeks download is bogus-ware too, it does not install offline- who came up this bad idea-replace them, especially for trying to charge for using the spp6

Can you elaborate what you mean? If you are the people who don't want to use MS store you can use installer from our website.

**Comment by Pisseduser** [comment]
Hi GitHub person- in response partly to your response- why when trying to
install files it said- no such host is known, text associated with this
file could not be found, then it said purchase a store version.  And it
said after trying another approach- files has been uninstalled, restoring
file explorer- which failed....so what's the excuse now, and then when
online it installs... And it happens on 2 different PCs with win pro
11...updated 23h2???

This is beta app behavior for files, and open shell needs updating also...
Pisseduser.

**Comment by Josh65-2201** [comment]
Setting as default is experimental as Windows doesn't support it officially it says so on the option. 
At no point does Files say you have to buy the store version. it's a way of donating.

Offline installers are here
https://cdn.files.community/files/stable/Files.Package_3.6.0.0_Stable_Test/Files.Package_3.6.0.0_x64_arm64_Stable.msixbundle
This one is WinAppSDK which you might also need to install.
https://cdn.files.community/files/stable/Files.Package_3.6.0.0_Stable_Test/Dependencies/x64/Microsoft.WindowsAppRuntime.1.5.msix
