### ISSUE TITLE
I want to add the ability to modify fonts

### ISSUE THREAD

**Issue by mengzhishang123** [files-community/Files#16022]
### What feature or improvement do you think would benefit Files?

I failed to modify the Chinese font using the configuration file

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.6.0.0

### Windows Version

10.0.19044.4529

**Comment by mengzhishang123** [comment]
![PixPin_2024-08-17_10-20-25](https://github.com/user-attachments/assets/55fc4415-523f-4ba8-9ae8-04c04e425f9c)
di
The font and English font in the address bar are not modified successfully

**Comment by 0x5bfa** [comment]
Thanks for the feedback.

We support it our own. For more info, visit [our docs](https://files.community/docs/customize-settings/appearance#:~:text=%2300000000-,custom%20fonts,-There%20isn%E2%80%99t%20an). Some parts won't be modified and it's been tracked while it's not priority work.
