### ISSUE TITLE
Bug: Issue with Column View Navigation When Right-Clicking or Selecting Items

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#16020]
### Description

I have encountered an issue when using the column view mode. When I right-click or try to select items, and I have many folders open (resulting in many columns being displayed), the view jumps back to the first column and then returns to the last one. This disrupts the workflow and makes it difficult to manage files effectively.

### Steps To Reproduce

1. Open several folders to display multiple columns.
2. Right-click on an item
or
2. Select multiple items.

### Requirements

Fix the bug that causes the view to jump back to the first column when right-clicking or selecting items in column view mode.

### Files Version

3.6.1.0

### Windows Version

10.0.22631.4037

### Log File

No need.

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #15713. You can check there or click subscribe in the right sidebar for updates.
