### ISSUE TITLE
Bug: Tags can't be added to folder needing admin permission to change

### ISSUE THREAD

**Issue by TMTYD** [files-community/Files#16033]
### Description

I tried this, with the tags, but I always get this error message as shown in the screenshot. My drive is formatted in NTFS

![Screenshot 2024-08-19 193857](https://github.com/user-attachments/assets/05bbd04a-1beb-4f2f-be6d-b335f5a4f8c1)
![Screenshot 2024-08-19 194017](https://github.com/user-attachments/assets/c9964ade-7674-4b6e-ac5a-f53357b534fe)

### Steps To Reproduce

1. Right-click on folder
2. Select tag
3. Select color with tag

### Requirements

- If tag fails to apply prompt for admin permission and retry

### Files Version

3.6.0.0

### Windows Version

10.0.22621.4037

### Log File

[debug.log](https://github.com/user-attachments/files/16663580/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, What's the path your applying the tag too and Is the tag still being applied?

**Comment by TMTYD** [comment]
> Thanks for the report, What's the path your applying the tag too and Is the tag still being applied?

Apply the tag to this path: C:\Program Files\Blackmagic Design\DaVinci Resolve\Fusion

No, the tag disappears again

**Comment by Josh65-2201** [comment]
Thanks, that folder would needs admin to add files and is probably why the tag is not able to apply

**Comment by TMTYD** [comment]
![Screenshot 2024-08-21 164858](https://github.com/user-attachments/assets/da191479-eb95-4b97-8f93-007d9ff2be9f)
![Screenshot 2024-08-21 164917](https://github.com/user-attachments/assets/ccddaf97-d1f2-4de3-b0ce-238b90defc57)
![Screenshot 2024-08-21 164925](https://github.com/user-attachments/assets/1f4fdcf2-6e89-4189-8a79-3bd1c5c2810d)
![Screenshot 2024-08-21 165103](https://github.com/user-attachments/assets/15047735-9b85-442d-bad6-377eb8ababd1)


OK, that's logical why it doesn't work. The next problem is that when I try to change the permissions of the folder, it doesn't take effect, see screenshot.

Two administrators and two users are also displayed.

If I change the permissions in the standard explorer and then update the folder with files, the permissions aren't set either, even though I changed them.

**Comment by Josh65-2201** [comment]
Files doesn't have support for settings security permissions yet. It can only read them.
I don't recommend changing the permissions of the Program files folder it could brake things, but if you still do with Windows File Explorer you have to open advanced and make sure you set to `apply to this folder, sub folder and files` and `enable inheritance` You may also need to change the folder owner to your account.

**Comment by TMTYD** [comment]
Ok all clear thanks

**Comment by yaira2** [comment]
This will be addressed together with #15272.
