### ISSUE TITLE
Improve the launching speed

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#1603]
Although Files UWP is much better the File Explorer in my opinion, it is much slow to launch so if I want to access a folder quickly I can't use Files UWP. Please work on improving the performance of Files now that it's getting popular.

**Comment by SOI7** [comment]
Removing the splash screen could increase the boot speed I believe

**Comment by Jaiganeshkumaran** [comment]
Actually Files UWP is already configured to hide the splash screen but it only works when app launches fast enough. The splash screen isn’t the problem here.

**Comment by SOI7** [comment]
I see it all the time 🤷‍♀️

**Comment by MarcAnt01** [comment]
Can confirm I have this delay, Win32 explorer happens to be slow just with heavy folders while Files UWP has a little delay when opening a folder, even if it contains few elements.

**Comment by lukeblevins** [comment]
@yair100 recently enabled an optimization for .NET Native which should improve start up times.

Commit: https://github.com/files-community/Files/pull/2215/commits/3dcf530a891b7597d5f049cbdc402cc38c2591ad

**Comment by Cyberdroid1** [comment]
I recently started using Files again on my old PC with an HDD, and whenever launching Files for the first time, it took around 10 seconds for the app to load. Subsequent launches took 1-2 seconds, which is "acceptable". 

Can something be done to improve it? Thanks!

Files version 1.5.0.0
Windows 10 1809 LTSC  (17763.1935)

**Comment by sisrfeng** [comment]
too slow at many aspects

**Comment by yaira2** [comment]
We're excited to share that startup performance will be significantly improved in the upcoming release of version 3. You can download the preview version from our website https://files.community/download.
