### ISSUE TITLE
Files App needs to be update due to crash and bugs

### ISSUE THREAD

**Issue by QuanTheGamer7** [files-community/Files#16030]
### Description

i just brought this to replace the normal default file explore app but this app needs more updates and improvements please Fix 

### Steps To Reproduce

1. when i open the progream some of my icones like my drives are not displaying 
2 when i serach for files in mp4 or mp3 it didn't work

### Requirements

![Files_ubHCx5pcBF](https://github.com/user-attachments/assets/bda7b26d-f617-4f5d-ad92-d6b682b05fac)
![Files_xjWPq9Esiw](https://github.com/user-attachments/assets/c8ead0df-0c52-4b52-b25e-e80bd55be233)
![chrome_9RoYDHDR4I](https://github.com/user-attachments/assets/be15d71d-1a7f-4231-a600-8fd9badb300e)

### Files Version

3.6.0.0

### Windows Version

10.0.22631.4037

### Log File

[debug.log](https://github.com/user-attachments/files/16652710/debug.log)

**Comment by yaira2** [comment]
Do the pinned items display after restarting Windows?

**Comment by QuanTheGamer7** [comment]
sometimes yes other times no

**Comment by yaira2** [comment]
We're currently tracking this issue in #15410. In the meantime, you can workaround the issue by turning off the setting to keep Files in the background.

**Comment by Josh65-2201** [comment]
Can you try turning off `Files settings > Advanced > Leave app running in the background` then close and reopen Files. 
As for the drive unplugged notice are you having that only when trying to open the `this pc` folder? If so you can use home it shows the drives with more details and has the other widgets

**Comment by QuanTheGamer7** [comment]
> Can you try turning off `Files settings > Advanced > Leave app running in the background` then close and reopen Files. As for the drive unplugged notice are you having that only when trying to open the `this pc` folder? If so you can use home it shows the drives with more details and has the other widgets

i did that but i still get the Drives error

**Comment by Josh65-2201** [comment]
How are you opening Files?

**Comment by QuanTheGamer7** [comment]
yea
