### ISSUE TITLE
Request for Adding Details Column

### ISSUE THREAD

**Issue by mikan18** [files-community/Files#16042]
### What feature or improvement do you think would benefit Files?

When the layout is set to 'details,' please add columns to display the dimensions of images (width and height in pixels), the resolution, and the duration of videos and audio tracks.
I was searching for an app with a column layout feature for Windows and came across Files. I particularly love the design. However, since I frequently work with image and video data, it can be inconvenient when I can't switch to a detailed layout to view multiple files' information at once. I sincerely hope this can be addressed in a future update.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.6.0.0

### Windows Version

10.0.19045.4780

**Comment by yaira2** [comment]
Thanks so much for your feedback! We’re keeping an eye on this in issue #8366. Feel free to subscribe to that issue for any updates.
