### ISSUE TITLE
No keyboard combination to switch tabs

### ISSUE THREAD

**Issue by osieltorres** [files-community/Files#1604]
**Describe the bug**

**To Reproduce**
1. Open a tab
2. Go and open another tab
3. Try a keyboard combination to switch from tabs, currently I can't find any.
**Expected behavior**
As the design of tabs changed, it shoud be a way to switch from tabs without having to go to the "open tabs" button icon, that would be nice for those(like me), who uses more keyboard than the mouse.

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 2004 19041.388]
 - App version: [v0.12.4.0]

**Additional context**
I am not totally sure, previous version with tabs had any combination for tabs switching, but I consider that, it is completly a most have feature to make explorer to improve.

**Comment by yaichenbaum** [comment]
@osieltorres Have you tried using `ctrl + 1` - `ctrl + 9`?

**Comment by gave92** [comment]
I think Ctrl+Tab used to work but now does nothing

**Comment by osieltorres** [comment]
> @osieltorres Have you tried using `ctrl + 1` - `ctrl + 9`?

No, I have not, I suppose it works, but in this case, wouldn't it be better on a accessibility perspective, to set `ctrl + tab` for it?

**Comment by yaichenbaum** [comment]
> > @osieltorres Have you tried using `ctrl + 1` - `ctrl + 9`?
> 
> No, I have not, I suppose it works, but in this case, wouldn't it be better on a accessibility perspective, to set `ctrl + tab` for it?

`ctrl + tab` should work as well.

**Comment by osieltorres** [comment]
> > > @osieltorres Have you tried using `ctrl + 1` - `ctrl + 9`?
> > 
> > 
> > No, I have not, I suppose it works, but in this case, wouldn't it be better on a accessibility perspective, to set `ctrl + tab` for it?
> 
> `ctrl + tab` should work as well.

Not working then.

**Comment by winiston2212** [comment]
Ctrl+Tab and Ctrl+Shift+Tab seem to work when the vertical tab view flyout is open. When it's closed, it doesn't work.

**Comment by osieltorres** [comment]
I think this can be closed, currently in v0.12.5.0 works fine.

**Comment by osieltorres** [comment]
> Ctrl+Tab and Ctrl+Shift+Tab seem to work when the vertical tab view flyout is open. When it's closed, it doesn't work.

App crashes for me when I disable the multitasking flyout and try to open a new tab.

**Comment by yaichenbaum** [comment]
@osieltorres We are keeping this issue open as it still applies to the vertical tab flyout.

**Comment by yaichenbaum** [comment]
Merging with #1912.
