### ISSUE TITLE
Tab after rename move to next file

### ISSUE THREAD

**Issue by outdoorsdev** [files-community/Files#16044]
### What feature or improvement do you think would benefit Files?

Windows standard behaviour when pressing tab after renaming a file is to move to renaming the next file. Files in Grid layout and other doesn't do this, and instead moves to a previous file?

I can see other PRs/issues but can't see any that describe this specifically.

Please alter the behaviour to just move to next file in the list.

### Requirements

- This proposal will alter behaviour of tabbing after renaming a file to move to the immediate next file in the list

### Files Version

3.6.0.0

### Windows Version

10.0.19045.4046

**Comment by yaira2** [comment]
This feature is already implemented and working on my end. Additionally, pressing `Shift + Tab` switches to the previous file. I gather from here that it's not working for you, can you open a new issue as a bug report so we can better track this?
