### ISSUE TITLE
Opened File Explorer shows empty start page

### ISSUE THREAD

**Issue by TMTYD** [files-community/Files#16047]
### Description

When you open Files, it sometimes happens that the start page is completely empty, except for the drives. You then have to completely close Files via the Task Manager and then restart it. Then everything is displayed normally again.

### Steps To Reproduce

You can't reproduce it, it just happens

### Requirements

- e.g. Fix crash that occurs when...
You then have to close files in the task manager and restart it, then the start page will be displayed completely again

### Files Version

3.6.0.0

### Windows Version

10.0.22621.4037

### Log File

[debug.log](https://github.com/user-attachments/files/16694213/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, We're tracking this in #15410. You can check there or click subscribe in the right sidebar for updates.
Please also try the workaround steps listed in that issue.

**Comment by TMTYD** [comment]
ok thx
