### ISSUE TITLE
Maximum Zoom level could be slightly higher

### ISSUE THREAD

**Issue by heliole** [files-community/Files#16046]
### What feature or improvement do you think would benefit Files?

The main reason I switched to the Files app is because it offers better zoom functionality than Windows Explorer.
But the current maximum zoom level in the Files app is still limited to only a slightly better value, and I think the limit could be raised to a higher number while still not making the thumbnails look too blurry.

The reason for allowing more zoom is so that you don't have to use the preview pane to look clearly about what's happening in the picture/video.

### Requirements

Increase the max zoom limit

### Files Version

3.6.0.0

### Windows Version

Windows 10 Home 22H2

**Comment by yaira2** [comment]
Thank you for your feedback! The sizes in the Grid View are currently based on the default sizes provided by Windows. However, we are working on a dedicated photos layout that may better suit your needs. For more information, please refer to issue #5058

**Comment by mdtauk** [comment]
The icon grid views are optimised to support the icon sizes provided by the system, and so beyond a certain size, these views would end up looking odd.

There is a long standing ToDo for us to add a specific Photos content view, as well as refreshing the existing content views with updated designs.

**Comment by heliole** [comment]
> The icon grid views are optimised to support the icon sizes provided by the system, and so beyond a certain size, these views would end up looking odd.

I know, I mentioned this. But as I said, I think the limit could still be a little higher.
> There is a long standing ToDo for us to add a specific Photos content view, as well as refreshing the existing content views with updated designs.

Raising the limit slightly could be an easy temporary fix until this feature is implemented.
