### ISSUE TITLE
Classic installer fails with "the parameter is incorrect" on Windows 11

### ISSUE THREAD

**Issue by cbourner** [files-community/Files#16067]
### Description

I am unable to install the application on Windows 11 due to an error in the installer.

### Steps To Reproduce

Download from https://cdn.files.community/files/download/Files.Stable.exe
Run the installer
Installation does not proceed and stops with "The parameter is incorrect"

![image](https://github.com/user-attachments/assets/7bd1258f-89b7-4030-a63c-0e6d66bd9db0)

### Requirements

A more specific error would be helpful and may possibly lead to a solution.

### Files Version

3.6.0.0

### Windows Version

21H2 build 22000.2538

### Log File

I am unable to locate a log file.  If anyone has advice on how to log the failed installation, I'm willing to provide more information.

**Comment by Josh65-2201** [comment]
If you're using an unofficial Windows install (AtlasOS, ReviOS, disabled Windows update system, removed the Microsoft store, etc.) these are not supported but you can try the below.

1. Type Services in Windows start menu > Open the `Windows update` and `Delivery optimization` services > Set startup type to automatic > Click ok > restart Windows and try installing again.

2. You can also try
   1. Opening PowerShell (Windows default not PowerShell 7) as administrator
   2. Run this command
   ```Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/stable/Files.Package.appinstaller```
   3. See if Files is in the start menu all apps section

If the above doesn't work you won't be able to use Files without reinstalling Windows using the official installer from https://www.microsoft.com/software-download/windows11.

**Comment by cbourner** [comment]
2 (ii) was the solution.  I am not running anything non-standard, however, it looks like Delivery optimisation is enabled.

**Comment by cbourner** [comment]
OK, old version was still there after downloading and running https://cdn.files.community/files/stable/Files.Package.appinstaller.

Powershell option shown in the attachment:
![image](https://github.com/user-attachments/assets/392cedf7-d853-4b3f-9606-af4e3376eff3)

**Comment by yaira2** [comment]
As you can see from the output, we don't have any additional info to display. Anyways, can you confirm if Files is installed on your device?
