### ISSUE TITLE
In column-view, click or long-press scrolls horizontally back to first column

### ISSUE THREAD

**Issue by asimhamid** [files-community/Files#16063]
### Description

I am not sure if it is intentional or not, either way, this interactions serves no purpose. In column-view, click or long-press scrolls horizontally back to first column and back to the last column. This auto-scrolling issue is really a deal-breaker for using the column layout. 

https://github.com/user-attachments/assets/3a493d88-4211-4afe-9488-c7538ad926bc

### Steps To Reproduce

1. Right or left click on any "column" in column layout.

### Requirements

Right or left click should not do anything other than expected. Expected behaviour example: open a context menu (which it does but with the auto-scroll).

### Files Version

3.6.0.0

### Windows Version

10.0.22631.4037

### Log File

[debug.log](https://github.com/user-attachments/files/16729500/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, We're tracking this in #15713 . You can check there or click subscribe in the right sidebar for updates.

**Comment by asimhamid** [comment]
Got it, thanks!
