### ISSUE TITLE
 "Bug: black screen at startup for the Files app"

### ISSUE THREAD

**Issue by gilnett** [files-community/Files#16068]
### Description

"Every time I restart my computer, the Files app opens automatically and displays a black screen

![image](https://github.com/user-attachments/assets/8c2c616d-fd86-467b-8ed2-6d4ccfbc177d)

### Steps To Reproduce

1. Launch at startup must be enabled.
2. Completely shut down your computer.
3. Now turn it on, and the Files app will shows a black screen.

### Requirements

- fix black screen for the app at startup

### Files Version

3.6.3

### Windows Version

10.0.6.1000

### Log File

[debug.log](https://github.com/user-attachments/files/16736283/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Does it stay as a black screen or eventually show the tabs?

**Comment by gilnett** [comment]
No, the tabs don't appear; it stays black and shows the loading icon on the cursor. However, when I close the app and restart it, everything loads properly.

**Comment by Josh65-2201** [comment]
@0x5bfa is this the same as #16064

**Comment by 0x5bfa** [comment]
Most likely. I understand this issue relates with startuptask.

**Comment by STGYO** [comment]
I am also getting the same bug as this one. I have attached my debug.log file with this message. Hope this helps in fixing the bug. My Files(preview) Version is 3.6.3.0. The steps to reproduce are the same.

**Comment by STGYO** [comment]
[debug.log](https://github.com/user-attachments/files/16737229/debug.log)

**Comment by yaira2** [comment]
We’re currently tracking this in issue #16064. Could you please comment on the issue I linked so we can have the repro steps there? Thanks a lot!
