### ISSUE TITLE
Feature: Add support for pinning shortcuts to favorites

### ISSUE THREAD

**Issue by Rick-HM** [files-community/Files#1607]
### What feature or improvement do you think would benefit Files?
When a shortcut to a folder location is pinned to the sidebar favorites section. It shows as missing location when clicked it shows access denied.
![image](https://user-images.githubusercontent.com/26977075/189412784-ac4e68ae-f31f-4c80-88d5-6cc41e3cf808.png)

### Step to reproduce
1. Create a shortcut to a folder
2. Right click the created shortcut
3. Select pin to favorites
4. Open the pinned item
5. See Access denied

### Requirements

- Pinning a shortcut should pin the target destination to the sidebar

### Files Version

2.3.11.0

### Windows Version

10.19043.1899

### Logs
[debug.log](https://github.com/files-community/Files/files/9530950/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9530951/debug_fulltrust.log)

**Comment by MalteTasler** [comment]
Do you mean that the folder itself should get pinned? In that case, the context menu of the shortcut should have an option named "Pin the destination folder to favorites".

Pinning a shortcut itself would be useless, or does someone know what a possible usecase of that would be?

**Comment by yaichenbaum** [comment]
Merging with #3223

**Comment by hecksmosis** [comment]
Should pinning a shortcut just pin the referred folder or not?

**Comment by yaira2** [comment]
Yes, but this issue might actually be resolved with #10800

**Comment by yaira2** [comment]
@Rick-HM this is supported in v2.4.33.
