### ISSUE TITLE
Symbolic Link Shell Extension

### ISSUE THREAD

**Issue by sonofevil** [files-community/Files#16070]
### Description

There is a shell extension for Windows 10/11 which adds a convenient way to create symbolic links: https://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html

Currently this extension does not work correctly in Files. The "Pick Link Source" context menu item never appears, and the "Drop Here" menu always produces an error. In Windows Explorer it works correctly.

### Steps To Reproduce

1. Install Link Shell Extension as per instructions on website.
2. Open Files.
3. Right click any file or folder and navigate to shell extensions section.
(4. Interact with the "Drop Here" menu entry.)

### Requirements

- "Pick Link Source" should appear in context menu for files and folders
- "Drop Here" should only appear in context menu for folders, and only if a source has been picked (neither currently the case in Files)

The following functionality should be provided by the shell extension once the two conditions above are met:
- "Pick Link Source" should add a location to the shell extension's memory, whereupon "Drop Here" should allow creating symbolic links, hard links etc. at the destination. (By default this requires Admin privileges and should display the Admin prompt.)

### Files Version

3.6.0.0

### Windows Version

Edition	Windows 10 Pro Version	22H2 Installed on	‎13/‎07/‎2023 OS build	19045.3570 Experience	Windows Feature Experience Pack 1000.19052.1000.0

### Log File

Attempting to use the Drop Here -> Symbolic Link context menu option (no link source could be picked, so idk what it is trying to drop):
![2024-08-24 21_37_49-Window](https://github.com/user-attachments/assets/677e39f7-cd60-4694-945b-135d833e0d6d)
![2024-08-24 21_33_54-Window](https://github.com/user-attachments/assets/9dd86859-7181-4e57-ac14-cc5a06af51c1)

**Comment by sonofevil** [comment]
There is nothing relevant in the log, presumably because this is an error thrown by the shell extension, not Files.

**Comment by Josh65-2201** [comment]
Thanks for the report, We're tracking this in #9991. You can check there or click subscribe in the right sidebar for updates.

**Comment by sonofevil** [comment]
https://github.com/files-community/Files/issues/13481#issue-1930765313

**Comment by SilverGreen93** [comment]
I really use LinkShellExtension and I miss it in Files.
Just an update on this. The LinkShellExtension works properly in DirectoryOpus, another Windows Explorer alternative. Maybe it can be done in Files as well.
