### ISSUE TITLE
since last preview update 3.6.2, Files Preview starts with unresponsive blank screen 

### ISSUE THREAD

**Issue by andrew-james-heard** [files-community/Files#16077]
### Description

Windows Process Explorer shows 2 processes running with different command lines:
C:\Program Files\WindowsApps\FilesPreview_3.6.2.0_x64__1y0xx7n9077q4\Files.App\Files.exe
C:\Program Files\WindowsApps\49306atecsolution.FilesUWP_3.6.0.0_x64__et10x9a9vyk8t\Files.App\Files.exe
the FilesPreview icon in the middle of the startup window isn't displayed either

### Steps To Reproduce

1. simply boot PC

### Requirements

- e.g. Fix crash that occurs when...
both processes have to be manually killed, then re-run from start menu > Apps > FilesPreview

### Files Version

3.6.2

### Windows Version

11 23H2

### Log File

![20240826-074439-Process Explorer - Sysinternals_ www sysinternals com  DESKTOP-4CUJJG7_ajh](https://github.com/user-attachments/assets/37349443-3eb2-424a-8e42-b17b05fc8ec3)
[debug.log](https://github.com/user-attachments/files/16742061/debug.log)

**Comment by yaira2** [comment]
This is resolved in the latest preview v3.6.6.

**Comment by andrew-james-heard** [comment]
wow - quick response - thanks - I'll install immediately!!
