### ISSUE TITLE
Bug: Shift clicking properties option for sidebar items doesn't open Windows File Explorer properties

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#16074]
### Description

*

### Steps To Reproduce

1. Right click drive on sidebar
2. Hold shift and click properties
3. See Files properties open

### Requirements

- Shift click properties should open Windows File Explorer properties menu like the folder contents view one does

### Files Version

3.6.6

### Windows Version

10.0.22631.4037

### Log File

[debug.log](https://github.com/user-attachments/files/16741395/debug.log)

**Comment by 0x5bfa** [comment]
Unfortunately sidebar's context menu doesn't use RichCommands whereas should. Neither do Home page's.

There was a discussion how to handle what context the user is interacting with, such as SidebarContext, HomeContext snd ContentPageContext.
Then came into the conclusion to pass the context from context menu builder. So we need to implement it first before doing this.

**Comment by Josh65-2201** [comment]
Is there an issue on GitHub for that to merge this with?

**Comment by yaira2** [comment]
#15418

**Comment by 0x5bfa** [comment]
Also #14760 and #15283
