### ISSUE TITLE
Need the searching work on all file data

### ISSUE THREAD

**Issue by sweetieonion** [files-community/Files#16081]
### What feature or improvement do you think would benefit Files?

Searching in all file data

### Requirements

The default windows file explorer can search something in the data, but FILES just can search by the file name, would you improve the feature then? I think the funtions should not less then the default explorer at least.

### Files Version

3.6.0.0

### Windows Version

10.0.22631.4037

**Comment by 0x5bfa** [comment]
We don't have UI for searching metadata, we're tracking this on in #4813 and #16029.

However, we support it [with just ASQ text](http://learn.microsoft.com/windows/win32/lwef/-search-2x-wds-aqsreference).
Here's the support list, we'd want to implement them ultimately.
- ✅ ASQ
- ❌ Windows SQL
- ❌ ms-search

**Comment by yaira2** [comment]
@sweetieonion you can include file contents by prefixing `content:` to the search query before pressing enter.

**Comment by sweetieonion** [comment]
> @sweetieonion you can include file contents by prefixing `content:` to the search query before pressing enter.

thank you, that's worked.

**Comment by yaira2** [comment]
Awesome!
