### ISSUE TITLE
Display Total File Count in Folder When Using Attribute Function

### ISSUE THREAD

**Issue by ZhiQiu-Kinsey** [files-community/Files#16080]
### What feature or improvement do you think would benefit Files?

I am inclined to submit a request for a new feature related to the attribute function. When making use of the attribute feature, it would be extremely advantageous if the Files were capable of presenting the total count of files encompassed within the folder. Such an addition would significantly improve the user experience and offer a more lucid overview of the folder's contents. 

### Requirements

 I am submitting a feature request to enhance the folder attribute functionality. Specifically, I would like to see the implementation of a recursive file count feature within the folder attributes display.

### Files Version

3.6.0.0

### Windows Version

10.0.22631.4037

**Comment by 0x5bfa** [comment]
Thanks for the feedback.


You can see the total count from the folder's properties window,

**Comment by yaira2** [comment]
@ZhiQiu-Kinsey as @0x5bfa mentioned, you can access this info from the properties window. Does this help, or did you have something else in mind?

**Comment by yaira2** [comment]
@ZhiQiu-Kinsey as @0x5bfa mentioned, you can access this info from the properties window. Does this help, or did you have something else in mind?

**Comment by ZhiQiu-Kinsey** [comment]
@yaira2 @0x5bfa 
When my folder contains a symbolic link folder, it will cause the correct number of statistics toto not be counted
![image](https://github.com/user-attachments/assets/4d6426bd-77eb-46e6-9ece-26ecfbe8e06f)
![image](https://github.com/user-attachments/assets/8fdb17b4-418f-488a-b973-8205ccd0caac)

I looked at the source code and found the problem because this judgment skipped symbolic links and junctions.
This appears to have been done to fix this issue: [https://github.com/files-community/Files/issues/8216](url)
![image](https://github.com/user-attachments/assets/0f729f5c-2f36-44bf-9d16-963b563e3ccf)

**Comment by 0x5bfa** [comment]
@hishitetsu fyi
I didn't know so but there seems to be a case reparse point can point to another link and circular reference would happen, subsequently the counting won't finish.
How's File Explorer shown it?

**Comment by Josh65-2201** [comment]
@ZhiQiu-Kinsey Can you answer the above question
