### ISSUE TITLE
Drag files to other software to open them, and drag files to directories for quick cutting

### ISSUE THREAD

**Issue by smilesxsy** [files-community/Files#16109]
### What feature or improvement do you think would benefit Files?

Drag files to other software to open them, and drag files to directories for quick cutting

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.6.0.0

### Windows Version

11

**Comment by Josh65-2201** [comment]
Thanks for the feedback, It unclear what you want, Files already support drag to open and cut/copy, you can hold shift while dragging to switch.

**Comment by yaira2** [comment]
> Drag files to other software to open them, and drag files to directories for quick cutting

Thank you for your feedback, drag & drop is already implemented but there are currently some compatibility issues with some apps. Which app are you trying to drag items to?

**Comment by smilesxsy** [comment]
@yaira2 Image files to viewers, video files to players, etc. (BandiView, potplayer).  
I found that in the official File Explorer, I can hold down and shift and drag files to the parent directory (before Windows 10 I didn't need to press anything to drag), but in this File Explorer I didn't see the drag effect No matter how I pressed it

**Comment by smilesxsy** [comment]
@yaira2 @Josh65-2201 Here's a test video, I'm using the official manager on the left, and the files on the right

https://github.com/user-attachments/assets/f28824a7-94ac-496c-b3fd-90e722581771

**Comment by Qin-shihuang** [comment]
Due to some limitations of Windows, drag & drop is not supported when you run Files as admin. Can you try increasing the UAC level and then reopen Files (as a user)?

**Comment by smilesxsy** [comment]
@Qin-shihuang Oh oh, yes, thanks
