### ISSUE TITLE
Add the ability to move the tabs to the left,right,bottom side of the application.

### ISSUE THREAD

**Issue by gilnett** [files-community/Files#16108]
### What feature or improvement do you think would benefit Files?

Add the ability to change the location of the tabs.

### Requirements

- This proposal will accomplish The ability to move the tabs to the bottom, top, left, or right.
- This proposal will accomplish The ability to display the folder name when the cursor is hovering over it.

### Files Version

3.6.16

### Windows Version

22631.4112

### Comments

![image](https://github.com/user-attachments/assets/f0af2e22-4e56-425a-8579-48f074f6ef0e)

**Comment by yaira2** [comment]
Thank you for your feedback! While we appreciate your suggestion, moving the tabs is unlikely to happen as they are a crucial part of the app’s visual hierarchy. Shifting them to another location could cause conflicts with various other elements:

- Left side: Conflicts with the sidebar
- Right side: Conflicts with the preview pane
- Bottom: Conflicts with the status bar

Could you share more about your use case? Understanding your needs better might help us find a suitable solution.

**Comment by mdtauk** [comment]
It should also be noted that the official TabView control we use, only supports top as a placement option.

**Comment by gilnett** [comment]
first some People work differently, and giving them the choice to place tabs where they want can make the app more user-friendly.(to have a better visual with 2 app next to each other).(sorry if my english is pretty bad for this)
Nowadays, many apps prefer sidebars since they allow a better view of what's happening
also this is a more flexible tabs placement for user since lots of app switch for a left sidebar

**Comment by yaira2** [comment]
> first some People work differently, and giving them the choice to place tabs where they want can make the app more user-friendly.

I completely agree with you, and we generally try to cater to a broad user base. The challenge is that what might seem like a simple setting at first glance is actually quite complex. Implementing it would require four separate UIs, which isn’t the direction we’re planning to take. However, it would be really helpful to understand how this feature benefits your personal use case so we can keep it in mind for future improvements.

**Comment by gilnett** [comment]
You're welcome. I admit it's a big challenge, but since it stays within the style of what you've done, it seems pretty good to suggest it.
