### ISSUE TITLE
Recycle Bin is empty even though it has items in it

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#1611]
The Recycle Bin in the app does not list items, but the default Recyle Bin shows them.

![image](https://user-images.githubusercontent.com/17484252/88890227-9f90de00-d241-11ea-9d40-b635fbafdfef.png)

**Comment by gave92** [comment]
The fulltrust process may have crashed. Could you post the contents of the `debug_fulltrust.txt` file? Thanks!

**Comment by R3voA3** [comment]
[debug_fulltrust.txt](https://github.com/files-community/files-uwp/files/5003916/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/files-uwp/files/5003917/debug.txt)

**Comment by hunterlan** [comment]
> The Recycle Bin in the app does not list items, but the default Recyle Bin shows them.

Don't know, what have you done, but on my laptop, it works well.

![image](https://user-images.githubusercontent.com/38838841/89105666-d6c2e300-d42b-11ea-84e8-275f969d4ec1.png)

**Comment by yaichenbaum** [comment]
@R3voA3 Is this still an issue in v0.23.1?

**Comment by R3voA3** [comment]
Well, I wasn't able to reproduce it, but it also didn't happen always.

**Comment by yaichenbaum** [comment]
@R3voA3 I am going to close this for now, let us know if it happens again.
