### ISSUE TITLE
Files Wont Open

### ISSUE THREAD

**Issue by adamjameskramer** [files-community/Files#16110]
### Description

When double clicking a file it won't open, nor will it open when you select open with. 

![Screenshot 2024-08-30 153135](https://github.com/user-attachments/assets/40befe1a-0474-44f2-96c6-29549aef088d)

### Steps To Reproduce

Open finder and click on file. 

### Requirements

- e.g. Fix crash that occurs when...
[debug.log](https://github.com/user-attachments/files/16821467/debug.log)

### Files Version

3.6.0.0

### Windows Version

10.0.19045.4780

### Log File

[debug.log](https://github.com/user-attachments/files/16821483/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by Josh65-2201** [comment]
We're tracking this in #14788. You can check there or click subscribe in the right sidebar for updates.
