### ISSUE TITLE
Feature: Add action to open folder in new pane

### ISSUE THREAD

**Issue by x1angli** [files-community/Files#16115]
### What feature or improvement do you think would benefit Files?

it will benefit folder browsing pane, 
currently if I double-click (or single-click, depending on configuration) on items in a pane, it will be opened in the same pane
i am wondering if we could add option to 
1. open items/subfolders in the other pane
2. open items/subfolders in a new table

### Requirements

- Add action to open selected folder in new pane

### Files Version

3.6.0.0

### Windows Version

11

**Comment by 0x5bfa** [comment]
Thanks for the feedback!

As for opening an item in a new tab, we use middle click. As for in a new pane, could you elaborate how you expect you open in a new pane? Different shortcut or a user configuration?

**Comment by yaira2** [comment]
You can open folders in a new pane via the context menu, have you given this a try?

**Comment by x1angli** [comment]
> You can open folders in a new pane via the context menu; have you tried that?

Thanks for the suggestion. I did give it a try, but I find it inconvenient. Since I have to perform this action frequently, having to bring up the context menu and make a selection each time feels cumbersome. Ideally, I'd prefer a single-click solution to streamline the process.

**Comment by x1angli** [comment]
> Thanks for the feedback!
> As for in a new pane, could you elaborate how you expect you open in a new pane? Different shortcut or a user configuration?

Thank you as well!

I have a 21:9 ultra-wide monitor, which provides ample space to set up two panes side by side—one on the left and one on the right. Currently, when I single or double-click on items in the left pane, they get opened in the same left pane. What I'd like is for the content (e.g., the subfolders or children files) of a folder clicked in the left pane to be displayed in the right pane instead. It would be great if this behavior could be configured by end users.

**Comment by yaira2** [comment]
> Thanks for the suggestion. I did give it a try, but I find it inconvenient. Since I have to perform this action frequently, having to bring up the context menu and make a selection each time feels cumbersome. Ideally, I'd prefer a single-click solution to streamline the process.

Ideally there would be a shortcut

**Comment by yaira2** [comment]
Turns out there is already an action but it doesn't have a default shortcut. To assign a shortcut:
1. Open Settings > Actions
2. Click on "Add command"
3. Select "Open in new pane"
4. Choose your preferred keyboard shortcut

You'll now be able to open folders in new panes with a single action.

**Comment by x1angli** [comment]
thanks @yaira2 the shortcut is helpful, more convenient than context menu. Thanks for the valuable advice. 

Yet, it's not a single action, it's 2-step actions, 
1. left-mouse-click on items in the left pane
2. press the keyboard shortcut
then it will bring up contents in the right pane

wondering if making "1 left-mouse-click on an item in the left pane" would be sufficient?
specifically
In settings -> "files and folders" -> open items with a single click -> a binary toggle button
there is also a "open folders in new tab"
could we enhance it by adding a dropdown selector, "open folders in: same pane | new pane | new tab"? 
that would be perfect


the reason for me raising this request is, there are a 2 level folder structure as below
```
Root
├── Folder 1
│   ├── Item 1.1
│   └── Item 1.2
├── Folder 2
│   ├── Item 2.1
│   └── Item 2.2
└── Folder 3
    ├── Item 3.1
    └── Item 3.2
```

and i'd like to quickly iterate the folder 1, folder 2, folder 3 to check their children items one-by-one. such one-click to open in new pane would be super helpful

thanks a lot

**Comment by yaira2** [comment]
It sounds to me that you're looking for the Column View layout.

**Comment by x1angli** [comment]
sort of, the Column View layout is close to what I'm looking for.
except for that the left pane is not "frozen" at the current level

but don't worry, I could settle into this, and I definitely understand you have other priorities.  thanks
