### ISSUE TITLE
Sync items sizes across directories

### ISSUE THREAD

**Issue by Steperman5692** [files-community/Files#16114]
### What feature or improvement do you think would benefit Files?

So by default, Files sync items (Files & Folders) sizes across every directory, which I've find really annoying (Example: I want the the items inside a folder to be big because there only 2 items).
So I wonder if we could add an on\off toggle "Sync items sizes across directories" in the Layout menu in Files settings.

### Requirements

Add an on\off toggle "Sync items sizes across directories" in the Layout menu in Files settings.

### Files Version

3.6.0.0

### Windows Version

22631.4112

### Comments

P.S: IK the Layout menu is one of the most confusing and frustrating part in Files; just if its possible to add such option it would be really really appreciated :)

**Comment by yaira2** [comment]
Thank you so much for your feedback! We completely understand the use case and have given it a lot of thought. Unfortunately, for various reasons, we don’t plan to support this feature in Files right now. If anything changes and we do add this feature, we’ll be sure to mention it in the update changelog.
