### ISSUE TITLE
Highlight a file from other apps like file explorer 

### ISSUE THREAD

**Issue by XXABOM7MDXX505** [files-community/Files#16112]
### What feature or improvement do you think would benefit Files?

Hi, it would be nice to have auto highlight the file that choose to see in Files like going to Chrome downloads then click "show in folder" in file explorer will highlight the file so no need to search for it while Files can't do that only opens the path but doesn't highlight and auto scroll to that file like file explorer.  

https://github.com/user-attachments/assets/63d72fb7-d829-4213-ad5b-d1976a2bdde0

### Requirements

- auto highlight and auto scroll to that file from other apps 

### Files Version

3.6

### Windows Version

22631.3880

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #14429. You can check there or click subscribe in the right sidebar for updates.
