### ISSUE TITLE
Make Application smoother

### ISSUE THREAD

**Issue by Bhuvan9407** [files-community/Files#16117]
### What feature or improvement do you think would benefit Files?

Please add a smooth animation while opening the application when we set the files app as default files app in windows.
It looks kind of unstable because it flashes a solid black screen before opening, but once started your runs smooth as butter!!

### Requirements

This will make your application more stable while it is set as default files app in windows.

### Files Version

3.6.0.0

### Windows Version

10.0.22631.4112

**Comment by 0x5bfa** [comment]
Thanks for the feedback.

This application is win32 app and we have no control over the application's startup. The startup is managed by the framework WinAppSdk and hopefully it would improve the startup.
For your info, this would be slightly improved from the next update of WinAppSdk.
But we can't really do something for it.

**Comment by yaira2** [comment]
@Bhuvan9407 do you have the option enabled to keep Files open in the background?

**Comment by Bhuvan9407** [comment]
@yaira2 Yeah bro but it is still the same.

**Comment by yaira2** [comment]
Thanks for the response. As @0x5bfa mentioned, anything before the splash screen is out of our control but I hope this becomes a non issue with further improvements to the app framework.

**Comment by CLydq** [comment]
Would it be better if the splash screen is changed with a startup animation and put this as an optional setting into the settings menu?

**Comment by yaira2** [comment]
It's a matter of preference, and from our end, we'd prefer to improve performance enough that a splash screen isn't necessary.
