### ISSUE TITLE
barra lateral expandida

### ISSUE THREAD

**Issue by skyhalls** [files-community/Files#16128]
### What feature or improvement do you think would benefit Files?

Na barra lateral o fato de ela não expandir como acontece no win explorer inviabiliza a ferramenta que em todo o restante é muito boa!

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.6.0.0

### Windows Version

10.0.26100.1591

**Comment by yaira2** [comment]
Thank you for your feedback, adding a tree view is on our todo list but has proven quite a challenge. In the meantime, I recommend trying the Columns View layout to see if that helps for your use case.

We're going to continue tracking this feature request in #1928. Feel free to add a comment or subscribe to that issue to be notified of further updates.

**Comment by yair100** [comment]
@skyhalls Tree View is currently available in preview https://files.community/download. It will be included in the next stable release.
