### ISSUE TITLE
Не получается установить 

### ISSUE THREAD

**Issue by ZET1337** [files-community/Files#16123]
### Description

Add-AppxPackage : Сбой развертывания с HRESULT: 0x80070424, Указанная служба не установлена.
Указанная служба не установлена.
Ошибка 0x80070424: сбой открытия пакета из расположения Files.Package_3.6.0.0_x64_arm64_Stable.msixbundle.
ПРИМЕЧАНИЕ. Чтобы получить дополнительные сведения, найдите [ActivityId] 4c2d7c7f-fd6a-0007-4b87-2d4c6afdda01 в журнале
 событий или введите в командной строке Get-AppxLog -ActivityID 4c2d7c7f-fd6a-0007-4b87-2d4c6afdda01.
строка:1 знак:1
+ Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/s ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (https://cdn.fil...ge.appinstaller:String) [Add-AppxPackage], Exception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

### Steps To Reproduce

Add-AppxPackage : Сбой развертывания с HRESULT: 0x80070424, Указанная служба не установлена.
Указанная служба не установлена.
Ошибка 0x80070424: сбой открытия пакета из расположения Files.Package_3.6.0.0_x64_arm64_Stable.msixbundle.
ПРИМЕЧАНИЕ. Чтобы получить дополнительные сведения, найдите [ActivityId] 4c2d7c7f-fd6a-0007-4b87-2d4c6afdda01 в журнале
 событий или введите в командной строке Get-AppxLog -ActivityID 4c2d7c7f-fd6a-0007-4b87-2d4c6afdda01.
строка:1 знак:1
+ Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/s ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (https://cdn.fil...ge.appinstaller:String) [Add-AppxPackage], Exception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

### Requirements

- e.g. Fix crash that occurs when...
Add-AppxPackage : Сбой развертывания с HRESULT: 0x80070424, Указанная служба не установлена.
Указанная служба не установлена.
Ошибка 0x80070424: сбой открытия пакета из расположения Files.Package_3.6.0.0_x64_arm64_Stable.msixbundle.
ПРИМЕЧАНИЕ. Чтобы получить дополнительные сведения, найдите [ActivityId] 4c2d7c7f-fd6a-0007-4b87-2d4c6afdda01 в журнале
 событий или введите в командной строке Get-AppxLog -ActivityID 4c2d7c7f-fd6a-0007-4b87-2d4c6afdda01.
строка:1 знак:1
+ Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/s ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (https://cdn.fil...ge.appinstaller:String) [Add-AppxPackage], Exception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

### Files Version

3.6.0.0

### Windows Version

10

### Log File

Add-AppxPackage : Сбой развертывания с HRESULT: 0x80070424, Указанная служба не установлена.
Указанная служба не установлена.
Ошибка 0x80070424: сбой открытия пакета из расположения Files.Package_3.6.0.0_x64_arm64_Stable.msixbundle.
ПРИМЕЧАНИЕ. Чтобы получить дополнительные сведения, найдите [ActivityId] 4c2d7c7f-fd6a-0007-4b87-2d4c6afdda01 в журнале
 событий или введите в командной строке Get-AppxLog -ActivityID 4c2d7c7f-fd6a-0007-4b87-2d4c6afdda01.
строка:1 знак:1
+ Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/s ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (https://cdn.fil...ge.appinstaller:String) [Add-AppxPackage], Exception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

**Comment by Josh65-2201** [comment]
If you're using an unofficial Windows install (AtlasOS, ReviOS, disabled Windows update system, removed the Microsoft store, etc.) these are not supported but you can try the below.

1. Type Services in Windows start menu > Open the `Windows update` and `Delivery optimization` services > Set startup type to automatic > Click ok > restart Windows and try installing again.

2. You can also try
   1. Opening PowerShell (Windows default not PowerShell 7) as administrator
   2. Run this command
   ```Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/stable/Files.Package.appinstaller```
   3. See if Files is in the start menu all apps section

If the above doesn't work you won't be able to use Files without reinstalling Windows using the official installer from https://www.microsoft.com/software-download/windows11.

**Comment by Josh65-2201** [comment]
For future issues please actually follow the template and don't spam the same thing in every box
