### ISSUE TITLE
Opening images from Files to Photos (MS Photos app) is limited to just that file (can't scroll from there)

### ISSUE THREAD

**Issue by jh20001** [files-community/Files#16126]
### Description

I know the subject might be a little confusing as it was evading me on how to properly describe the issue.

But, when using Files app, when I double click on an image, to view it in Photos (Microsoft Windows 11 default app), I can't hit left or right on the keyboard and scroll through the other images in the folder. I can only see that image. I have to close Photos and one by one open each photo individually. 

Using Windows File Explorer (default Windows explorer), when you double-click on the image, Photos is able to scroll left or right through the other images in the directory (which makes sense). 

So it must be how Files is passing the file off to the related application? I don't know how to explain it any other way. 

### Steps To Reproduce

1. Find a folder with multiple images using Files app.
2. Open it in default "Photos" app in Windows 11
3. Try to scroll left or right to see additional images

### Requirements

I would expect things to function as it would if I opened the image in Windows Explorer/File Explorer. 

### Files Version

3.6.0.0

### Windows Version

22631.4037 (Windows 11, 23H2)

### Log File

NA

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #15409 . You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
As a workaround, you can select multiple files and open them together.
