### ISSUE TITLE
Bug: Crash when trying to preview a html page

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#16137]
### Description

*

### Steps To Reproduce

1. Select a html file
2. Open info pane
3. Select preview
4. Crash

### Requirements

- Display html render preview

### Files Version

3.7.2.0

### Windows Version

10.0.22631.4037

### Log File

[debug.log](https://github.com/user-attachments/files/16898718/debug.log)

**Comment by 0x5bfa** [comment]
Maybe [this comment](https://github.com/files-community/Files/pull/16135#issuecomment-2332257140) relates to this issue.
WebView2 is now decoupled from WinAppSdk and it'll be published as a separate NuGet package. cc @yaira2
