### ISSUE TITLE
UI Scaling

### ISSUE THREAD

**Issue by briankri** [files-community/Files#16130]
### What feature or improvement do you think would benefit Files?

Ability to change UI scale of everything in the app. By default on Windows 10 the spacing and text are a lot larger than the default Windows Explorer. It would be nice to be able to scale down to fit more in the same space.

### Requirements

- This proposal will allow a scale value (zoom) to be set to enlarge or reduce all elements inside the window uniformly.

### Files Version

3.6.0.0

### Windows Version

10.0.19044.1645

### Comments

![image](https://github.com/user-attachments/assets/b7687e0a-13bc-4e40-8110-1037022ddda9)

**Comment by yaira2** [comment]
Thank you for your feedback. Spacing the file area can be reduced from the layout flyout, and we're tracking other areas of the app in #9506 and #13954. Feel free to add a comment or subscribe to those issues to be notified of further updates.
