### ISSUE TITLE
Bug: Dates between 1 to 7 days are not shown when using Application format

### ISSUE THREAD

**Issue by Hissymaster** [files-community/Files#16133]
### Description

when a file's date created or date modified properties are more than 24 hours and less than 7 days using the "Application" date format. the property is empty instead of actually displaying anything.

### Steps To Reproduce

1. open files
2. navigate to any file or folder that was last created or modified between 1 and 7 days ago.
3. note how the property "last created" or "last modified" are oddly empty.
4. (to make it more obvious, group by date.)

### Requirements

- Fix the sting related to "(Number) days ago"

### Files Version

3.7.0.0

### Windows Version

10.0.22631.4112

### Log File

[debug.log](https://github.com/user-attachments/files/16882383/debug.log)

**Comment by Hissymaster** [comment]
![image](https://github.com/user-attachments/assets/0dfba5e3-6f17-45af-91e9-11319b64242c)
This folder is meant to show (2 days ago) in the properties after Tuesday, 3 September, 10:14 AM. however, nothing is being shown right now. curious.

**Comment by Josh65-2201** [comment]
Thanks for the report, I reproduced this issue and have added this to the project board.

**Comment by hishitetsu** [comment]
This seems to be due to a lack of translation for the en-GB locale.
https://github.com/files-community/Files/blob/6a335a9d35b6a2f8d9317c640d5f7b61676d2057/src/Files.App/Strings/en-GB/Resources.resw#L390-L395

**Comment by Hissymaster** [comment]
That did seem to be the problem. It has been fixed in the preview. Thank you.
