### ISSUE TITLE
Bug: Unable to open files from the context menu when more then 11 are selected

### ISSUE THREAD

**Issue by sho9029** [files-community/Files#16136]
### Description

When selecting multiple files, if more than 11 files are selected, “Open” does not appear in the context menu.
All files have the same extension. For example, when opening multiple JPG files in a photo application.

### Steps To Reproduce

1. Select more than 11 files
2. Open context menu

### Requirements

More than 11 files can be selected to be open.

### Files Version

3.7.0.0

### Windows Version

10.0.26100.1591

### Log File

[debug.log](https://github.com/user-attachments/files/16896106/debug.log)

**Comment by 0x5bfa** [comment]
Looks like @winston-de added that limitation which hadn't existed before in BaseLayout.cs in #4190 I have no idea why but we should be able to remove this limitation safely.

**Comment by yaira2** [comment]
@0x5bfa do you want to open a PR for this?

**Comment by winston-de** [comment]
> Looks like @winston-de added that limitation which hadn't existed before in BaseLayout.cs in #4190 I have no idea why but we should be able to remove this limitation safely.

When I was testing this (however many years ago that was), trying to open a large number of files at once would cause the computer to seize and/or crash the program. Adding a cap seemed like a better option than freezing the user's machine :)

**Comment by yaira2** [comment]
@winston-de are you still able to reproduce this?

**Comment by winston-de** [comment]
@yaira2 No; it was probably an issue when we were using UWP APIs for opening files. As a fun experiment I removed the hard stop and opened all of System32, which didn't freeze the system. However, mileage will vary based on how powerful your PC is. Worth noting that Windows will hide the open option after 15 selected files.

Anyways the hard code is located at line 25 of OpenItemAction.cs

**Comment by yaira2** [comment]
Thank you Winston! We're going to take the chance and remove the limit.
