### ISSUE TITLE
Change font size

### ISSUE THREAD

**Issue by sebibasti0815** [files-community/Files#16134]
### What feature or improvement do you think would benefit Files?

Please add the option to change the font or font size of the different elements. Main focus should be the treeview and the file-views.

Some people would like bigger or different fonts (dyslexia), some would prefer smaller fonts like the font used in explorer (me).

### Requirements

- add option for font for treeview/file views/maybe other elements
- make the different elements use this option

### Files Version

3.7.0.0

### Windows Version

10.0.26120.1542

**Comment by 0x5bfa** [comment]
Thanks for reaching out.

> Please add the option to change the font or font size of the different elements.

This should be out of scope of Files. You can change font size from Windows Settings > Accessibility.

> Main focus should be the treeview and the file-views.

Our priority tasks are already listed in [the app project board](https://github.com/orgs/files-community/projects/3/views/2).
As there're processes, we don't have immediate plan to implement tree view.
For more info, visit #1928

> Requirements

We'd appreciate if you create an issue per feature request in the future.

**Comment by sebibasti0815** [comment]
"You can change font size from Windows Settings > Accessibility."

This changes ALL font sizes, every other App has normal sizes, only Files has bigger than usual font sizes...

Yeah I get it, you don't have this priority, so I'll shut up.

**Comment by sebibasti0815** [comment]
I'm sorry my answer was so rude.

It's not a crucial use case, it's usability. I would expect to visualy get (more or less) the same (visual) result as I get using explorer.

I took a look at the source code this morning and I understand that the option to adjust the font size is not particularly appealing. If I see that correctly, a small change has to be made in many places, which is repetitive and annoying work. Maybe it is necessary to adjust the paddings etc.

Maybe it is not the fontsize, maybe it is the fontweight. I'm not sure, maybe it is both.

This is what I mean: Left is explorer, right is files.

<img width="1310" alt="Screenshot 2024-09-05 124617" src="https://github.com/user-attachments/assets/4764c68a-856d-4e6a-b61e-56246b5e6941">

But I think it's important to say: I really like Files at the moment. I've been trying out whether it can replace Explorer for a few versions now. And I think it won't be much longer before I can. Thanks for that!

**Comment by yaira2** [comment]
@sebibasti0815 Thank you for your feedback. Spacing the file area can be reduced from the layout flyout, and we're tracking other areas of the app in https://github.com/files-community/Files/issues/9506 and https://github.com/files-community/Files/issues/13954. Feel free to add a comment or subscribe to those issues to be notified of further updates.

It's not stated clearly in those issues, but when using compact spacing, the plan is for font sizes to be reduced.

**Comment by CBearr** [comment]
I see the same larger font in Files.
Here is a screenshot: left Files, right Win11 Explorer.
Same directory. You see the difference by comparing the file names. Files breaks 4 files to the next column. I use for this view type "list" in the smallest size.

![Image](https://github.com/user-attachments/assets/37e2f5b6-05ea-4d83-a7db-731c797bfbe6)

![Image](https://github.com/user-attachments/assets/810073be-b774-4fbb-86ec-897b571d735d)
