### ISSUE TITLE
Bug: Address breadcrumb dropdown appears twice

### ISSUE THREAD

**Issue by el-ev** [files-community/Files#16144]
### Description

Through `git bisect` , I located that the issue was caused by #16028.

**Before:**

https://github.com/user-attachments/assets/e13db5a9-d2c4-4ff0-b550-e666ec32ae4a

**After:**

https://github.com/user-attachments/assets/1bc70962-7d85-4c13-b388-b364c316ef5f

### Steps To Reproduce

1. Click the chevron on the address bar breadcrumb
2. Observe the dropdown appears, then quickly disappears and appears again

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.7.0.0

### Windows Version

10.0

### Log File

Not applicable

**Comment by yaira2** [comment]
Thank you for the report

**Comment by yaira2** [comment]
A fix will be included in the next release
