### ISSUE TITLE
Bug: Focus indicator not displayed when navigating in the sidebar using keyboard

### ISSUE THREAD

**Issue by Qin-shihuang** [files-community/Files#16145]
### Description

Navigate to the sidebar using `Tab`, then use up and down arrow keys to switch between items. It can observed that the focus indicator disappears and won't show until `Tab` is pressed again.

This is a regression issue introduced by #15949.

https://github.com/user-attachments/assets/da3ef91a-6a23-4531-ad2f-c5373df6f369

### Steps To Reproduce

As mentioned in the description.

### Requirements

The focus indicator should display

### Files Version

3.7.0.0

### Windows Version

10.0

### Log File

Not applicable

**Comment by yaira2** [comment]
Thank you for the report

**Comment by karman1111** [comment]
Hello, I'm a new contributor and I can fix this issue. Could you please assign it to me?

**Comment by yaira2** [comment]
Sure

**Comment by yaira2** [comment]
A fix will be included in the next release.
