### ISSUE TITLE
Error on closing Files 3.7

### ISSUE THREAD

**Issue by Sibelius58** [files-community/Files#16147]
### Description

Closing Files 3.7 gives the error you can see in the file attached
![2024-09-07_092519](https://github.com/user-attachments/assets/56aae0eb-a0df-442e-834b-e6c8a71f7ff4)

### Steps To Reproduce

Whenever you close Files 3.7. That doesn't happen with 3.6

### Requirements

Close Files 3.7 without error message

### Files Version

3.7.0.0

### Windows Version

10.0.22631.4112

### Log File

[debug.log](https://github.com/user-attachments/files/16915249/debug.log)

**Comment by 0x5bfa** [comment]
Thanks for reaching out.

We're aware of this issue, and this has been fixed in the latest dev branch and will be released in the next preview build.
