### ISSUE TITLE
after deleting a file the selected file is different to the keyboard focus 

### ISSUE THREAD

**Issue by andrew-james-heard** [files-community/Files#16148]
### Description

Using Details view (most likely others) I press Delete on a file mid way down the list. The selection rectangle is now around the 1st file in the list but when I press cursor+Down the file next after the deleted file shows the keyboard focus & selection rectangle, and the ticked checkbox on LHS. It is not consistent either.

### Steps To Reproduce

1. as above

### Requirements

- e.g. Fix crash that occurs when...
I think the keyboard focus & selection rectangle should always be on the same item.

### Files Version

3.7.0.0

### Windows Version

11 23H2

### Log File

[debug.log](https://github.com/user-attachments/files/16920242/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #16003 . You can check there or click subscribe in the right sidebar for updates.
