### ISSUE TITLE
Microsoft Fotos Navegation

### ISSUE THREAD

**Issue by dpbueno** [files-community/Files#16166]
### Description

Microsoft Photos application, when I open an image in the explorer and press the right or left arrow, the application displays the other images in the folder, while using Files this navigation is not possible.

### Steps To Reproduce

1 Open an image using the Microsoft Photos app
2 Navigate with the right or left arrows on the keyboard or use the arrows that are displayed on the screen
3 The other images in the folder are displayed

### Requirements

- e.g. Fix crash that occurs when...
nothing happens

### Files Version

3.7.0.0

### Windows Version

10.0.19045.4412

### Log File

n/a

**Comment by yaira2** [comment]
Thank you for the report, can you confirm if this is the same as #15409?
