### ISSUE TITLE
Quick Access and Pinned Shortcut Disappear 

### ISSUE THREAD

**Issue by fross100** [files-community/Files#16169]
### Description

Quick access and pinned folder disappear from side panel or in home panel, the bug often appears randomly, if the files are closed from task manager and opened again the problem will disappear
![{A9AE381A-46F7-46DF-BBEA-9AD5D87BEBAB}](https://github.com/user-attachments/assets/d02e132e-568f-4393-abc6-0232b0518b42)

### Steps To Reproduce

it has appeared randomly several times, but I find it difficult to make the bug appear intentionally

### Requirements

- fix the bug that make quick access and pinned folder disappear

### Files Version

3.7.0.0

### Windows Version

10.0.22635.4145

### Log File

[debug.log](https://github.com/user-attachments/files/16940100/debug.log)

**Comment by 0x5bfa** [comment]
Thanks for the report!

Can you check if this is the same as #15410?

**Comment by Josh65-2201** [comment]
This is the same as #15410. You can check there or click subscribe in the right sidebar for updates. Please also use the workaround steps listed on the issue.
