### ISSUE TITLE
Layout and sorting options reset after every app update 

### ISSUE THREAD

**Issue by PatrickDotStar** [files-community/Files#16162]
### Description

After every update of "Files" (I use the Windows Store), my layout and sorting preferences are reset to the default settings for each folder. This requires me to manually reapply these preferences after each update.

For example, I prefer to use the grid layout (to get thumbnails) with descending sorting by "Date created" in my Videos folder and all its subfolders. However, after every app update, these settings are reset to their defaults, and I have to manually reapply them to each folder.

I have been using "Files" for about 8 months, and this issue has been present the entire time.

### Steps To Reproduce

1. Open the "Files" app (Windows Store version).
2. Navigate to a folder (e.g., "Videos").
3. Set a custom layout (e.g., Grid layout).
4. Set a custom sorting option (e.g., "Date created" - Descending).
5. Install an app update via the Windows Store once available.
6. Reopen the same folder and observe that the layout and sorting preferences have been reset to their defaults.

### Requirements

The app should retain custom layout and sorting preferences across updates.

### Files Version

3.7.0.0

### Windows Version

22631.4112

### Log File

[debug.log](https://github.com/user-attachments/files/16931837/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, this issue has been fixed in v3.7 and will no longer occur with future updates.

**Comment by PatrickDotStar** [comment]
Oh man, I should have read the release notes first before posting. 🥲
Thanks for the quick reply 👍

**Comment by yaira2** [comment]
No problem! Unfortunately the fix only helps for updates after v3.7 but the main thing is that it shouldn't occur again,
