### ISSUE TITLE
Icon Labels in Files context menu and toolbars

### ISSUE THREAD

**Issue by Steperman5692** [files-community/Files#16174]
### What feature or improvement do you think would benefit Files?

So in Windows 11 24H2, Microsoft added icon labels to the context menu; it look something like this: 
![image](https://github.com/user-attachments/assets/1daf1bc2-de97-441f-9d9f-40ebe63a6f57)
So I was wondering if we could add this to Files context menu and toolbars & also add an on/off toggle in Appearance menu in settings called "Show icon labels in the context menu & toolbar" for people that want to disable this feature.

### Requirements

- Add icon labels to Files context menu & toolbar.
- Add an on/off toggle in the Appearance menu in settings called "Show icon labels in the context menu & toolbar".

### Files Version

3.7.0.0

### Windows Version

22631.4169

**Comment by 0x5bfa** [comment]
> in Windows 11 24H2


This was added in WinAppSdk 1.5, which is not an inbox component of Windows.

> added icon labels to the context menu

We realize there's such thing. Since we got this update, we've disabled this feature to avoid labels being clipped.
We have, afaik, no plan to enable this.

**Comment by Steperman5692** [comment]
Thanks for the respond! I'm looking forward to seeing this feature implemented in the future!

**Comment by XiaoTDM** [comment]
> This was added in WinAppSdk 1.5, which is not an inbox component of Windows.

Can we do this now? The built-in WinAppSDK should be higher than 1.5, and 24H2 has been vigorously promoted

**Comment by yair100** [comment]
@XiaoTDM we're currently tracking this in #17350.

**Comment by XiaoTDM** [comment]
> @XiaoTDM we're currently tracking this in #17350.

Is that both Tool Bar & Context Menu?
