### ISSUE TITLE
Error 0x80070003: AppManifest.xml failed with error

### ISSUE THREAD

**Issue by Arbiterz** [files-community/Files#16179]
### Description

App installation failed with error message: error 0x80070003: Opening file from location: AppxManifest.xml failed with error: The system cannot find the path specified.
. (0x80070003)

### Steps To Reproduce

Run Files.stable.appinstaller

### Requirements

Install Files app

### Files Version

3.7.0.0

### Windows Version

22621.4037

### Log File

No log file

**Comment by Josh65-2201** [comment]
Can you try
1. Opening PowerShell as administrator
2. Run this command
```Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/stable/Files.Package.appinstaller```
3. See if Files is in the start menu all apps section

**Comment by Arbiterz** [comment]
i get this error

Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF0, Package could not be opened.
error 0x80070003: Opening file from location: AppxManifest.xml failed with error: The system cannot find the path specified.                                                                                                                 .                                                                                                                                                                                                                                            NOTE: For additional information, look for [ActivityId] 3d68da06-064f-0009-560b-803d4f06db01 in the Event Log or use the command line Get-AppPackageLog -ActivityID 3d68da06-064f-0009-560b-803d4f06db01                                     At line:1 char:1                                                                                                                                                                                                                             + Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/s ...                                                                                                                                                                  + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (https://cdn.fil...ge.appinstaller:String) [Add-AppxPackage], FileNotFoundException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

**Comment by Josh65-2201** [comment]
Are you using an unofficial Windows install (AtlasOS, ReviOS, disabled Windows update system, removed the Microsoft store, etc.) If so these types of installs are not supported.

**Comment by Arbiterz** [comment]
No using offical windows install. I did remove windows apps before using WPD but the store is not removed.

**Comment by Josh65-2201** [comment]
Using those types of programs to uninstall default programs make it an unofficial copy. It likely something there is braking it. Have you tried installing the preview version?

**Comment by Arbiterz** [comment]
Just tried the preview version I get the same error

**Comment by Arbiterz** [comment]
Just tried installing again and both versions seem to work now. Im assuming maybe something about the windows update I just had fixed it.

**Comment by yaira2** [comment]
Sounds good! Please reach out if you have any other questions.
