### ISSUE TITLE
Add the ability to reorder columns in Details view.

### ISSUE THREAD

**Issue by phlaange** [files-community/Files#16171]
### What feature or improvement do you think would benefit Files?

Windows Explorer has had this feature since W95(?) and I rely on it to be able to show the most relevant information, for me, in the most prominent position. So...

Add the ability to reorder columns in Details view.

Or

Use the same order as that folder uses in Windows Explorer.

### Requirements

- The ability to drag and drop columns in Details view. Or use a settings screen.
- A setting that simply has "mimic Windows Explorer column order"

### Files Version

3.7.0.0

### Windows Version

10.0.19045.4842

**Comment by yaira2** [comment]
Thank you for your feedback, this feature is on our todo list and is currently being tracked in #8385. Please subscribe or add a comment there to be notified of further updates regarding feature.
