### ISSUE TITLE
Add file size in the file details pane

### ISSUE THREAD

**Issue by cybersphere9** [files-community/Files#16175]
### What feature or improvement do you think would benefit Files?

Add file size in the file details pane

### Requirements

- This proposal will match the functionality offered by Windows explorer and satisfy a common query people have

### Files Version

3.7.0.0

### Windows Version

10.0.22631.4037

**Comment by yaira2** [comment]
File sizes are already displayed in the status bar, can you help clarify the use case for duplicating this information in the details pane?

**Comment by cybersphere9** [comment]
I didn't notice it in the status bar when I first posted this. However, from a UI perspective, I just think it's better to have all the associated data in one location so the user doesn't have to hunt around to find it. Explorer has the file size info. in the details pane as well as the status bar.

**Comment by yaira2** [comment]
I hear the use case, it's not planned for now, but we'll keep it in mind for future updates.
