### ISSUE TITLE
Files stable

### ISSUE THREAD

**Issue by HC1Gunner** [files-community/Files#16173]
### What feature or improvement do you think would benefit Files?

How come the download for Files does not have a version number, I have no idea what I downloading, if the same version or a newer version.

Currently running v3.7.0.0, its this the latest?

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z
How come the download for Files does not have a version number,

### Files Version

3.7.0.0

### Windows Version

19045.4842

**Comment by Josh65-2201** [comment]
3.7 is the latest for stable. Files won't show an install update button if no updates available, you can also check the Files discord https://discord.gg/files app updates channel or the website blog posts https://files.community/blog for what the latest version is

**Comment by yaira2** [comment]
Thank you for your feedback, just to confirm, the confusion is that the website doesn't explicitly display the version number before you download?
