### ISSUE TITLE
File Folder - documents wont open

### ISSUE THREAD

**Issue by adamjameskramer** [files-community/Files#16170]
### Description

Files wont open. 
![Screenshot 2024-08-30 153135](https://github.com/user-attachments/assets/88fb94f7-05b7-4618-8409-ced48a89a5a4)

I sent a bug report and was told to download the files preview (blue app) however this app classes randomly. 

![Screenshot 2024-09-10 073848](https://github.com/user-attachments/assets/660bf522-3fa6-48b9-8f05-f627884c1503)

### Steps To Reproduce

Open, click. 

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.6.17.0

### Windows Version

10.0.19045.4780

### Log File

[debug.log](https://github.com/user-attachments/files/16944148/debug.log)

**Comment by Josh65-2201** [comment]
We're tracking this in https://github.com/files-community/Files/issues/14788. You can check there or click subscribe in the right sidebar for updates.
