### ISSUE TITLE
Bug: Git Information column are empty

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#16177]
### Description

It's working in 3.7.0.0
![image](https://github.com/user-attachments/assets/9356d07e-59ce-4878-bfa9-0ffe89750efd)

### Steps To Reproduce

1. Open a git repo
2. See no content loaded from git information 

### Requirements

- Load Git Information 

### Files Version

3.7.5.0

### Windows Version

10.022631.4169

### Log File

[debug.log](https://github.com/user-attachments/files/16969274/debug.log)

**Comment by yaira2** [comment]
@Josh65-2201 thank you for the timely catch! I discovered the cause was incorrect logic introduced in #16141 and I've pushed a commit to resolve this issue.
