### ISSUE TITLE
Constantly Closing

### ISSUE THREAD

**Issue by natasha1188** [files-community/Files#16184]
### Description

Over the past several days my files app has been crashing very often. 

### Steps To Reproduce

It doesn't seem like it is a specific thing that is happening. What I am working on is moving documents into folders. 

### Requirements

Fix crash that occurs when Files closes unexpectedly. 

### Files Version

3.7.0.0

### Windows Version

Edition	Windows 11 Home Version	23H2 Installed on	‎2024-‎06-‎24 OS build	22631.4169 Experience	Windows Feature Experience Pack 1000.22700.1034.0

### Log File

[debug.log](https://github.com/user-attachments/files/16983371/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by yaira2** [comment]
I don't see anything in the log file, but before trying to debug this further, please let us know if it's still an issue in v3.7.6.

**Comment by adamjameskramer** [comment]
Using apps, preview panel open, crashing periodically. 

App: 3.7.6.0
Version: 10.0.19045.4894
[debug.log](https://github.com/user-attachments/files/17155238/debug.log)

**Comment by yaira2** [comment]
Does closing the preview pane solve the issue? In the event that it does, this issue is most likely resolved with #16156.

**Comment by yaira2** [comment]
@natasha1188 @adamjameskramer
