### ISSUE TITLE
Feature request: Google Drive: show folder that is shared with you on top rather than somewhere on bottom

### ISSUE THREAD

**Issue by soredake** [files-community/Files#16187]
### What feature or improvement do you think would benefit Files?

Right now, in Windows Explorer folders from other Google Drive users are shown on top with other folder, and they have correct overlay icon.

But, in Files, folders that are shared with you are not shown on top, you need to scroll a lot to find them if you have hundreds of pictures like me, and shared folder have generic folder icon instead of google drive overlay icon.

### Requirements

1) Shared folders in Google Drive folder will be shown on top where they are easy to find.
2) Shared folders will use correct Google Drive overlay icon instead of generic folder icon.

### Files Version

3.7.6.0

### Windows Version

10.0.22631.4169

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Can you send a screenshot of how it looks in Windows File Explorer compared to Files

**Comment by soredake** [comment]
Windows Explorer:
![Без имени](https://github.com/user-attachments/assets/baa19bea-7fed-4dc6-baf9-865f7971e19d)

Nothing to show from Files side as there is no shared folders on top.

**Comment by yaira2** [comment]
How are you sorting the items in File Explorer?

**Comment by soredake** [comment]
@yaira2 by name + folders first (default, I think).

**Comment by yaira2** [comment]
And in Files?

**Comment by soredake** [comment]
> And in Files?

That is what I use in files.

**Comment by yaira2** [comment]
I meant a screenshot of what you see in Files.

**Comment by soredake** [comment]
I don't see a point of screenshoting what I see in Files, there's no shared folder (they are somewhere on the bottom) on top, just plain synced folders and files.

**Comment by yaira2** [comment]
It’s a bit tricky to visualize without actually using Google Drive, so it would be great if you could provide as much detail as possible. That said, folders should be treated the same way across all locations. By default, folders are sorted separately from files and appear at the top of the list. You can change this to show files first, or sort them together based on name, date, etc.
![image](https://github.com/user-attachments/assets/7048acea-0c48-4143-aacc-79e5cf22a74d)

**Comment by soredake** [comment]
Shared folder treated differently in Windows Explorer, and I already enabled "sort folder first", this will not help, Files need to explicitly add support for shared folders.

**Comment by Lamparter** [comment]
@soredake could you please provide a photo of what this looks like in Files for context?

**Comment by soredake** [comment]
Nothing to show here:
![изображение](https://github.com/user-attachments/assets/444b367a-c6de-4bba-a6dd-9800f1a2d52f)

**Comment by Lamparter** [comment]
@soredake is what you're trying to say that Windows Explorer groups the shared folders separately from the regular Drive folders, whereas in Files they are all grouped together?

**Comment by soredake** [comment]
@Lamparter Windows Explorer shows shared folders on top with regular synced folder, Files shows shared folder somewhere far on bottom, that's the problem, shared folder should be shown on top, not in random position on bottom.

**Comment by Lamparter** [comment]
> @Lamparter Windows Explorer shows shared folders on top with regular synced folder, Files shows shared folder somewhere far on bottom, that's the problem, shared folder should be shown on top, not in random position on bottom.

Are you sure you don't have alphabetical sort on?

**Comment by soredake** [comment]
Seems to be fixed now.

**Comment by yaira2** [comment]
Thanks
