### ISSUE TITLE
"Open Files UWP here" crashes app everytime

### ISSUE THREAD

**Issue by jonnypjohnston** [files-community/Files#1618]
**Describe the bug**
When I click on the "Open Files UWP here" in the context menu, the app crashes, every time...

**To Reproduce**
1. On my external hard-drive, open a folder location...
2. Right click to open the context menu...
3. Click on the "Open Files UWP here"...
4.

**Expected behavior**
Files UWP should open at that location

**Screenshots**
[debug.txt](https://github.com/files-community/files-uwp/files/5006784/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/files-uwp/files/5006785/debug_fulltrust.txt)
![files-uwp-context-crash-01](https://user-images.githubusercontent.com/3137489/89031193-0a085380-d300-11ea-8ae9-ee6c87475b22.png)

**Desktop (please complete the following information):**
OS-Ver: [Windows 10 Pro Insider Preview Build 20180.rs_prerelease.200725-1714]
AppVer: [v0.12.4 Preview] FROM THE STORE
Email:  [jonny@jpparametrics.com/jonnypjohnston@gmail.com]

**Additional context**
Add any other context about the problem here. For instance, are you building from source or using a precompiled build/snapshot?

**Comment by yaichenbaum** [comment]
@jonnypjohnston This method is no longer supported by Files.
