### ISSUE TITLE
QuickLook program does NOT LookQuick when attempting to use with version 3.7.6.0

### ISSUE THREAD

**Issue by TadhgEomonn** [files-community/Files#16198]
### Description

As the title states: QuickLook program for previewing files is not working with version 3.7.6.0 of Files. Also not working with File--Preview (blue version 3.7.6.0).

QuickLook has always been finicky when working with Files program: frequently requires restarting QuickLook. But now that no longer helps. 

QuickLook is working with Windows File Explorer, as is PowerToys' Peek. 

### Steps To Reproduce

Press the spacebar for a preview with QuickLook. Nothing happens.

### Requirements

Would like QuickLook to function with Files. 

And/or add the ability to use the PowerToys Peek program.

### Files Version

3.7.6.0

### Windows Version

10.0.22631.4169

### Log File

[debug.log](https://github.com/user-attachments/files/17006880/debug.log)

**Comment by yaira2** [comment]
Thank you for the report, this is already fixed in our `main` branch and will be released shortly 🙂

**Comment by TadhgEomonn** [comment]
Sorry to make extra work for you. Thanks for the quick fix.
