### ISSUE TITLE
Launch Preview doesn't work

### ISSUE THREAD

**Issue by mak-kawa** [files-community/Files#16192]
### Description

Installed QuickLook (3.7.3) doesn't launch from space key which is default action key.
No response, no error.
Maybe this issue is since Files 3.7.6 (or 3.7.0).

### Steps To Reproduce

1. select any previewable file.
2. push space key.
3. nothing happens.

### Requirements

Preview window of QuikLook opens.

### Files Version

3.7.6.0

### Windows Version

Windows 11 Home 23H2 22631.4169

### Log File

[debug.log](https://github.com/user-attachments/files/16999122/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, this has been fixed and will be available in the next update

**Comment by shantanub08** [comment]
Broken again in v3.9.1.0

Tried changing the shortcut key thinking it must be conflicting with PowerToys' Quick Peek feature but sadly no avail.
