### ISSUE TITLE
Bug: Files randomly starts using as much CPU usage as possible

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#16196]
### Description

After 3.7, Files randomly will use as much CPU as possible after navigating folders with no consistent way of triggering it. I have calculate folders sizes and leave running in the background turned off and I'm not running any file operations during or before this happens.

### Steps To Reproduce

Unknown

### Requirements

Unknown

### Files Version

3.7.6.0

### Windows Version

10.0.22631.4169

### Log File

[debug.log](https://github.com/user-attachments/files/17006392/debug.log)

**Comment by yaira2** [comment]
I haven't noticed any issues on my side but I haven't had any long sessions lately. Do you know around which preview build this started happening? Are you able to check earlier commits in `main` to try and figure out at which point it started occurring?

**Comment by Josh65-2201** [comment]
3.7.4 is the earliest I noticed it. I can try the commit but since it kind of random it could take a while

**Comment by yaira2** [comment]
Having a more specific commit would help debug, but either way I'm not sure how much I can do unless I can repro it as well 🙁

**Comment by yaira2** [comment]
@0x5bfa I think this might be the update where we removed WinUIEx.

**Comment by 0x5bfa** [comment]
@Josh65-2201 what if you open a property window, close the main window and move your cursor? If the same happens, it might be caused by my commit.

**Comment by Josh65-2201** [comment]
Doing that does have a noticeable 0.1% when not moving the cursor to about 25-30% when moving it

**Comment by 0x5bfa** [comment]
Do you mean preview is preview pane?
Consuming CPU just moving cursor is silly. If you pointer out of the widow does it fall down?

**Comment by Josh65-2201** [comment]
No, Files preview. With Files freshly open only moving the cursor around is causing high CPU usage, I haven't had Files start using as much as possible yet, but can try moving the cursor out the window when it happens

**Comment by yaira2** [comment]
Can you repro with #16100?

**Comment by Josh65-2201** [comment]
Moving the mouse out or minimizing the window doesn't lower CPU usage after it happens. Is #16100 based on 3.6.18? If so probably not since 3.7 doesn't have the issue

**Comment by yaira2** [comment]
Should be based on a commit with WinUIEx, but we've tested with a lot of branches and it's possible there are other changes as well.

**Comment by yaira2** [comment]
What about #16138?

**Comment by Josh65-2201** [comment]
I will build on that commit and try it for a few days see if it happens

**Comment by Josh65-2201** [comment]
I have been using dev on 3.7.7 for a few days and not had this issue. I'm uncertain if something wrong with my preview install/Windows or it fixed since 3.7.6, either way I don't think this is something Files can fix.

**Comment by 0x5bfa** [comment]
It might be a memory leak on pointer enter/exit events in some control but I'm uncertain if it's possible.

**Comment by Josh65-2201** [comment]
I have been using 3.7.8 after a reinstall of the app and have not had this issue since.
