### ISSUE TITLE
Bug: Refresh button on Home page doesn't work at all

### ISSUE THREAD

**Issue by 0x5bfa** [files-community/Files#16208]
### Description

When you navigate to Home and try to refresh the page for the page to be up-to-date it just doesn't work at all.

### Steps To Reproduce

1. Open Files
2. Go to Home
3. Click Refresh button

### Requirements

- Make the refresh button on Home page work

### Files Version

3.7.0

### Windows Version

10.22000.0

### Log File

Doesn't help. Just missing this ability in Files.

**Comment by 0x5bfa** [comment]
I filed this issue so others can look into as this should be easy one.

Also basically works as a workaround for #15410 instead of turning off the option to run the app on the background.

**Comment by yaira2** [comment]
Same as #6182?

**Comment by 0x5bfa** [comment]
I think that issue is for auto refresh when something was changed. Will we merge?

**Comment by Josh65-2201** [comment]
First part listed in it is to make the refresh button work

**Comment by 0x5bfa** [comment]
Ah I see, but we will have to update the different part for each.
I'll leave you to decide to close and merge this:)

**Comment by yaira2** [comment]
Lets merge
