### ISSUE TITLE
Files Not Working Properly

### ISSUE THREAD

**Issue by wyos1** [files-community/Files#16206]
### Description

Every time I open Files it takes forever to load now. Never was like that before. And occasionally it doesn't even do anything so I have to force close it.

Then, if it does work, it's incredibly slow. 

When I am able to use Files, it will constantly crash. I'm not able to pinpoint anything specific because it seems to be happening randomly. And a lot more often than before. 

This app has basically become useless in its current state. I don't know what's going on but I can't do anything.

### Steps To Reproduce

I don't really know how to reproduce the behavior because its so random.
1. Open Files
2. Open 2 Windows for different folders.
3. Try cutting one file from one folder into the other.

### Requirements

- Fix time it takes for Files to load when opened.

### Files Version

3.7.6.0

### Windows Version

10.0.22631.4169

### Log File

[debug.log](https://github.com/user-attachments/files/17017115/debug.log)

**Comment by yaira2** [comment]
> Every time I open Files it takes forever to load now. Never was like that before. And occasionally it doesn't even do anything so I have to force close it.

Do you have the option to keep Files open in the background enabled?

**Comment by wyos1** [comment]
To be honest, no. I wasn't paying attention at all.

But right after I left this feedback earlier, I tried using Files and couldn't.

It seemed like no matter what I did, it kept crashing. And it was always at random places. No specific way to pin it down to something.

**Comment by yaira2** [comment]
I don't see anything in the log file but it might help if you check Event Viewer.

**Comment by yaira2** [comment]
@wyos1 Is this still an issue in the preview version? https://files.community/download/preview
