### ISSUE TITLE
Show .mp3 tag information in Details view

### ISSUE THREAD

**Issue by rogercoder** [files-community/Files#16202]
### What feature or improvement do you think would benefit Files?

In Windows File Explorer, when I open a folder with mp3 files, I can see the Song Title, Artist Name, Album Title, etc. This is very useful for me.
In Files I just get generic file information. I didn't see any options to show anything different.
In the attached screenshot, Windows File Explorer is on top, Files on the bottom.

### Requirements

Allow users to customize what columns are shown for various media types. For instance, for folders of mp3 files, showing Song Title, Artist Name, Album Title, would be great.

### Files Version

3.7.7.0

### Windows Version

10.0.22631.4169

### Comments

![image](https://github.com/user-attachments/assets/b8ac269e-5507-4926-8b19-d1544da3143e)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #8366. You can check there or click subscribe in the right sidebar for updates.
