### ISSUE TITLE
Bug: Unable to pin folders to sidebar

### ISSUE THREAD

**Issue by Today20092** [files-community/Files#16209]
### Description

Trying to pin a folder to the sidebar does not do anything.

### Steps To Reproduce

1. select a folder
2. right click
3. select pin to sidebar

### Requirements

- folder should be pinned to the sidebar

### Files Version

3.7.6.0

### Windows Version

10.0.22621.4037

### Log File

[debug.log](https://github.com/user-attachments/files/17022922/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report.

**Comment by yaira2** [comment]
Does this happen for all folders or only folders in a specific location?

**Comment by Today20092** [comment]
> Does this happen for all folders or only folders in a specific location?

It happened in all locations, but it seemed to have fixed itself. Revoking access then restarting and giving access to all files again might have been the solution.

**Comment by yaira2** [comment]
Sounds good
