### ISSUE TITLE
Need options for more compact display

### ISSUE THREAD

**Issue by rogercoder** [files-community/Files#16201]
### What feature or improvement do you think would benefit Files?

I just installed Files and my first thought was "Ugh! Terrible information density!"  Windows 11 File Explorer has a tighter, more compact listing that is a must if you've got lots and lots of files. Despite your product having some cool features, I just can't bring myself to use it with the huge font size.

### Requirements

Have options for font (I believe you have this in Advanced settings, but make it easier to access than a .json file), font size, and row spacing.

### Files Version

3.7.7.0

### Windows Version

10.0.22631.4169

### Comments

![image](https://github.com/user-attachments/assets/0cbae692-1e6c-4172-aa59-6272c401dcca)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Files compact mode is the same sizing as Windows File Explorer, There has been no reason to make the font smaller as it wouldn't make anything else smaller.

**Comment by yaira2** [comment]
Reducing font sizing in smaller densities is on our todo list and is being tracked in #13954.
