### ISSUE TITLE
Bug: Exiting IrfanView when previewing image located inside archive crashes app

### ISSUE THREAD

**Issue by andrew-james-heard** [files-community/Files#16216]
### Description

open JPG within ZIP then exit -> immediate & silent crash
if I copy the JPG, then alt+cursor up, alt+cursor up, paste, then Enter/ Esc the viewer there is no problems i.e. the JPG is nothing special

### Steps To Reproduce

1. I have a ~600MB ZIP file
2. selected & pressed Enter
3. pressed Space to select folder inside
4. press Enter
5. there are 101 items in the ZIP
6. one item is a 300KB JPG
7. cursor right & press Enter to view JPG (without trouble) - is using IrfanView
8. press Esc to exit
9. immediate & silent crash
It doesn't appear the log file shows anything of much use.

### Requirements

Fix crash that occurs

### Files Version

3.7.6

### Windows Version

23H2

### Log File

[20240918 1543 debug.log](https://github.com/user-attachments/files/17038956/20240918.1543.debug.log)

**Comment by yaira2** [comment]
> press Esc to exit

Esc to in Files?

**Comment by andrew-james-heard** [comment]
correct

enter ZIP > select/ open JPG with viewer > Esc is naturally assumed to return to Files, but crashes

I just confirmed, it works fine with Windows Explorer

**Comment by yaira2** [comment]
Does closing the program normally also cause the issue?

**Comment by andrew-james-heard** [comment]
if I close the JPG viewer with alt+F4 or task swap back to Files Preview with alt+Tab, Files sometimes still crashes

**Comment by yaira2** [comment]
Does this happen with any other viewer?

**Comment by andrew-james-heard** [comment]
The "Open with" sub-menu doesn't work for the JPG within a ZIP file, so I have no way of knowing. I can't see it has anything to do with the JPG viewer though.

**Comment by yaira2** [comment]
Closing an external app shouldn't have anything to do with Files. I do wonder if the viewer tries to modify the file upon close. Can you try changing the default viewer from the Settings app?

**Comment by andrew-james-heard** [comment]
I changed the default app associated with JPG from IrfanView to GIMP, went thru the same procedure, clicked Enter on the JPG (within the ZIP) and 2s later, even before GIMP was stable, observed Files had silently disappeared from the taskbar.

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by andrew-james-heard** [comment]
just checked with 3.7.9 - all fixed, well done! was there a comment in the change notes? maybe "Fixed an issue with navigating photos on Windows 10."?

**Comment by yaira2** [comment]
The fix was for a different issue but I was curious if it also resolved this. Thank you for confirming.

**Comment by andrew-james-heard** [comment]
While you are there... I have a different issue, but maybe already open/ aware of, so will save me not reporting - sometimes, but only sometimes, when I press Enter on a file (eg. LibreOffice writer .odt or calc .ods) the application takes ages to open. It appears to stall. I discovered if I kill Files.exe from Sysinternals Process Explorer that the application opening resumes. I get the impression Files has temporarily/ incorrectly locked the file. If I open the application from Start menu instead of indirectly by file association, then never a problem. Seems to have started recently. Doesn't happen with Explorer.

**Comment by yaira2** [comment]
I have a good idea why this is, can you open an issue so we don't lose track?
