### ISSUE TITLE
Bug: Context menu is transparent

### ISSUE THREAD

**Issue by wwwyyl-stack** [files-community/Files#16218]
### Description

when right clicking a file in Files exe, the context menu is transparent, which is a problem because you can't read the options clearly. 
![image](https://github.com/user-attachments/assets/2d71bd88-db05-47d1-9659-f05b64428835)

### Steps To Reproduce

1. open the files exe
2. right click on the file
3. context will appear in a transparent background

### Requirements

Fix crash that occurs when right clicking the file and the context appears.

### Files Version

3.7.0.0

### Windows Version

10.0.19045.4894

### Log File

[debug.log](https://github.com/user-attachments/files/17043241/debug.log)

**Comment by yaira2** [comment]
Thank you for the report, this is likely an issue with WinUI but you can see if restarting Windows fixes the issue.
