### ISSUE TITLE
UI gets freeze when deleting multiple files

### ISSUE THREAD

**Issue by techo207** [files-community/Files#16214]
### Description

In the new version of Files, the UI freezes when deleting multiple files at once (I am deleting about 100 files). I think the deletion process is handling files one by one, which takes a lot of time. Additionally, the deletion process locks up the UI.

### Steps To Reproduce

1. install 3.7.6 version
2. delete 100 files at same time

### Requirements

the UI must not get locked

### Files Version

3.7.6.0

### Windows Version

Edition	Windows 10 Pro Version	22H2 Installed on	‎16/‎06/‎2023 OS build	19045.4894 Experience	Windows Feature Experience Pack 1000.19060.1000.0

### Log File

[debug.log](https://github.com/user-attachments/files/17033456/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Do you have many items in the recycle bin?

**Comment by techo207** [comment]
I had 3,174 files totaling about 200 MB. After emptying the Recycle Bin, I deleted multiple files, and it seemed to be a bit faster, but the UI is still unusable.

**Comment by yaira2** [comment]
Thank you for the report, we're going to continue tracking this issue in #14108.
