### ISSUE TITLE
Why only push pull sync but not commit

### ISSUE THREAD

**Issue by sukiyou-seven** [files-community/Files#16219]
### What feature or improvement do you think would benefit Files?

Why only push pull sync but not commit

### Requirements

add a commit thanks

### Files Version

3.7.7.0

### Windows Version

10.0.19045.2965

**Comment by yaira2** [comment]
Thank you for your feedback. It's important to note that Files are meant to complement existing Git tools, not replace them. That said, support for committing is being discussed in #12440 and we even shared some concepts on what this can look like.
