### ISSUE TITLE
"FILES" se cierra Inesperadamente

### ISSUE THREAD

**Issue by Alexiiiander** [files-community/Files#16225]
### Description

En muchas ocasiones ya sea queriendo abrir el panel de las herramienta o usando alguna herramienta como vista de detalles el programa se cierra automáticamente.

### Steps To Reproduce

Hacer uso de la Aplicación sin mas

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.7.7.0

### Windows Version

10.0.22631.4169

### Log File

[debug.log](https://github.com/user-attachments/files/17060910/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you send a screenshot of the button or menu that is causing the crash

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
