### ISSUE TITLE
Files Constant Crashes

### ISSUE THREAD

**Issue by fernandobuzi** [files-community/Files#16221]
### Description

Files crashes either on right click, or when previewing file. Closes itself. Needs to be reopend.

### Steps To Reproduce

1. Open files
2. Activate columns layout 
3. Toggle the Info Panel on (Preview Mode)
4. Navigate to a file PDF or PPT file located 3 or 4 levels down, starting from the parent folder.

### Requirements

Files should not timeout during navigation.

### Files Version

3.7.7.0

### Windows Version

10.0.19045.4894

### Log File

[debug.log](https://github.com/user-attachments/files/17054817/debug.log)

**Comment by yaira2** [comment]
Thank you, a fix for right clicking will be included in the next release.

**Comment by yaira2** [comment]
Thank you for the report, we're tracking this issue in #16193.
