### ISSUE TITLE
Pinned Files Icon Does Not Show

### ISSUE THREAD

**Issue by fernandobuzi** [files-community/Files#16222]
### Description

When pinned to the Windows task bar, the space is blank. The icon is there, but there is no icon shown.

### Steps To Reproduce

1. Install the Files app.
2. Pen the Files app.
3. Right click to pin it to the taskbar.
4. Close the Files app and look at the taskbar icon disappear location.
5. Click on the blank taskbar location to open the files app.

### Requirements

Fix icon that does not show on the windows taskbar.

### Files Version

3.7.7.0

### Windows Version

Windows 10 Home Single Language 22H2 (19045.4894)

### Log File

[debug.log](https://github.com/user-attachments/files/17054894/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Files doesn't control the icon on the taskbar, please try restart your PC

**Comment by yaira2** [comment]
Does restarting Windows help?
