### ISSUE TITLE
OneDrive not detected

### ISSUE THREAD

**Issue by TheR0cketMan** [files-community/Files#16220]
### Description

It's not detecting my OneDrive at all. Normal Windows File Explorer picks it up fine without issues but this Files app doesn't detect it which I found strange as it's supposedly supported.

**Edit:** It has now detected it, I had to restart Files (your software) a few times and restart my PC before it detected it and showed up.

### Steps To Reproduce

N/a

### Requirements

N/a

### Files Version

3.7.6.0

### Windows Version

10.0.22631.4169

### Log File

[debug.log](https://github.com/user-attachments/files/17047191/debug.log)

**Comment by yaira2** [comment]
It sounds like this is resolved. If the issue returns, please let us know and we'll take a look.
