### ISSUE TITLE
Cannot Set Files as default file manager

### ISSUE THREAD

**Issue by fernandobuzi** [files-community/Files#16223]
### Description

Whenever I toggle the "Set Files as default file manager" option on, Files switches it back off immediately.

### Steps To Reproduce

1. Open files
2. Got to settings/advanced/Experiemental Features
3. Toggle "Set Files as the default files manager"
4. Add Admin password for Registry Editor
5. Files toggles the button back off, even if the password was correct.

### Requirements

Ensure "Set Files as the default files manager" stays active.

### Files Version

3.7.7.0

### Windows Version

10.0.19045.4894

### Log File

[debug.log](https://github.com/user-attachments/files/17054977/debug.log)

**Comment by yaira2** [comment]
This usually indicates a permissions issue. Are you an administrator on the device?
