### ISSUE TITLE
Drag and Drop right click menu

### ISSUE THREAD

**Issue by mikulik86** [files-community/Files#16236]
### What feature or improvement do you think would benefit Files?

In Windows Explorer when dragging a file between locations using right mouse button, a menu appears letting the user decide between move, copy or shortcut:
![image](https://github.com/user-attachments/assets/1d3513b6-66fa-42fe-942b-c8bc8ddbd6a6)
I'm very used to this feature and would love to see it in Files.

### Requirements

??

### Files Version

3.7.6.0

### Windows Version

10.0.22631.4169

**Comment by 0x5bfa** [comment]
Thanks for the report.

This is the same issue as #1396. Click Subscribe on the side pane for the further news when we have an update for this.
