### ISSUE TITLE
Bug: Dates between 1 to 7 days are not shown when using Application format, English UK and AU

### ISSUE THREAD

**Issue by andrew-james-heard** [files-community/Files#16233]
### Description

are these reports worth posting?
I doubt there's anyway to reproduce this one although after a reboot it can still see it
see screen caps - 6 files don't display creation & modified dates (depending on the style of view), and the whole refresh of the directory feels like it has slowed right down & various operations (cursor up/ down, page up/ down) are slower
this directory has 195 items, all CSV
when I switched the default file manager to Explorer there were no problems; Explorer could display the file properties & I could see no issue with the creation & modified dates 

is it getting to some limitation on the # files per directory maybe?

### Steps To Reproduce

1. > 195 files in directory
2. observe (maybe) the modified date(s) not displayed

### Requirements

display file properties properly

### Files Version

3.7.6

### Windows Version

23H2

### User ID

files-community

### Log File

[debug.log](https://github.com/user-attachments/files/17068099/debug.log)
![20240920-072607-PC3-relay (5) - Files](https://github.com/user-attachments/assets/01d45310-b917-474d-a288-1fe3b51ca412)
![20240920-072832-20240916 csv Properties](https://github.com/user-attachments/assets/bd61567d-5fda-4811-8230-2d1348e8b849)

**Comment by Josh65-2201** [comment]
Thanks for the report, What language are you using in Files/Windows?

**Comment by andrew-james-heard** [comment]
english

**Comment by Josh65-2201** [comment]
There is multiple versions of English. Go to Windows Settings > Time & language > Language and region > Windows display language

**Comment by andrew-james-heard** [comment]
specifically "English (Australia)"

**Comment by Josh65-2201** [comment]
Seems to be the same issue as https://github.com/files-community/Files/issues/16133. English UK also has this issue again

**Comment by yaira2** [comment]
It seems like someone is messing the with English UK translations in Crowdin.
