### ISSUE TITLE
Tags - Group By

### ISSUE THREAD

**Issue by victorVanVolcemSomko** [files-community/Files#16238]
### Description

Here a simple example:
I have assigned a tag to my favorite files. I want them to be listed above the unlisted file.
For this I have done the following:
- Created the tag
- Assigned them to the desired items
- Sort by: Alphabetically
- Group by: Tags
Resulting in this, which is what I am aiming for
![image](https://github.com/user-attachments/assets/8fd2c8ec-de50-4bac-9248-19893218dffb)

Problem is that if I leave the "Marvel Heroes" folder and then reopen it, it looks like this:
![image](https://github.com/user-attachments/assets/1a284ee5-678d-409c-be49-78a0de7272a2)
It still "applies" my sort by and group by preferences (as you can tell, there is still a group called "Untagged") but my tagged items are now also in it. The group with my favorite heroes which was above the Untagged group is now gone.

### Steps To Reproduce

1. Create a tag (Favorites for example)
2. Assign the tags to some items (folders, files, videos, ...)
3. Set the Group By to be "Group By: Tags"
4. Leave the folder in which you applied these tags and group by preferences
5. Reopen the folder. The items still have tags but are under the group "Untagged" instead of the tag group they have assigned.

### Requirements

I expect the group by to still work properly after leaving the folder. It does still apply it on some level (Untagged group is still present)

### Files Version

3.7.6.0

### Windows Version

10.0.22631.4169

### User ID

files-community

### Log File

[debug.log](https://github.com/user-attachments/files/17083891/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #15530. You can check there or click subscribe in the right sidebar for updates.
