### ISSUE TITLE
Feature: Show new file/folder text in "Enter an item name" dialog

### ISSUE THREAD

**Issue by RWeigelt** [files-community/Files#16239]
### What feature or improvement do you think would benefit Files?

When I create a new folder, I get the following dialog:
![image](https://github.com/user-attachments/assets/8208aa06-f199-443d-ac80-db87e99ab62e)

When I create a new file, the dialog that appears looks the same.

Just by looking at the dialog, I have no way to figure out what I am about to do (create a folder or a file).
I don't even see that I am about to create something new.

So, to improve the user experience, the UI texts should describe the current action.

Title: Create new folder
Prompt in textbox: Enter a folder name
Left Button: Create

vs.

Title: Create new file
Prompt in textbox: Enter a file name
Left Button: Create

### Requirements

- The title of the "Enter an item name" should reflect the current action
- The button text "Set name" should describe the end goal, i.e. to **create** something instead of the (more technical) aspect of setting the name

### Files Version

3.7.7.0

### Windows Version

10.0.22631.4169

**Comment by Josh65-2201** [comment]
Thanks for the feedback

**Comment by yaira2** [comment]
This will be included in the next update.
