### ISSUE TITLE
I can't install version 3.7.7.

### ISSUE THREAD

**Issue by gilnett** [files-community/Files#16231]
### Description

It's simple, I'm stuck on version 3.7.6, and when I use the installer, it only offers me 3.7.6, not 3.7.7.

### Steps To Reproduce

1.Download the installer
2. run the update check and that's it.

### Requirements

fix bad installer???

### Files Version

3.7.6

### Windows Version

10.0.22631.2715

### User ID

files-community

### Log File

[debug.log](https://github.com/user-attachments/files/17066597/debug.log)
[debug.log](https://github.com/user-attachments/files/17066597/debug.log)

**Comment by yaira2** [comment]
v3.7.7 is currently only available for the store. We will release to everyone else once our Code Signing service revalidates our certificate.
