### ISSUE TITLE
Adjusting Highlight Color for Selected Items

### ISSUE THREAD

**Issue by saulob** [files-community/Files#16247]
### What feature or improvement do you think would benefit Files?

I'm experiencing an issue with the visibility of selected items in the program, specifically when using the light theme. In the first image (photo 1), it's quite difficult to distinguish the selected item because the gray color is too light. I added a blue arrow to help identify the selected item (photo 2).

In the dark theme (photo 3), it's easier to identify the selected items, but I would like to have better visibility in the light theme as well. I looked through the theme settings but couldn't find any option to adjust or customize the color for selected items.

Is there a way to increase the contrast or customize the selection color? If not, could this be implemented in future updates to improve visibility in the light theme?

Images:

Photo 1: Light theme, selection hard to see.
Photo 2: Arrow added for better clarity.
Photo 3: Dark theme, selection easier to distinguish.
Thanks in advance for your help!

![image](https://github.com/user-attachments/assets/648d6ec8-4932-4929-88fd-508bbb2f9f80)
![image](https://github.com/user-attachments/assets/933ed694-59ea-4b10-917c-97cc85fb4674)
![image](https://github.com/user-attachments/assets/90e360fb-27b7-4822-8ccc-61c3a4484edc)

### Requirements

Requirements:

**Theme Customization Options**: Introduce an option in the settings to allow users to customize the color for selected items, independent of the theme (light or dark).

**Increase Contrast for Default Light Theme**: Increase the contrast of the default selected item highlight in the light theme to make it more noticeable.

**User-Defined Color Settings**: Provide the ability to choose a custom color for selected items within both light and dark themes to cater to different visibility preferences.

**Presets or Contrast Scaling**: Implement presets or a contrast scaling feature that automatically adjusts the highlight color based on the theme or overall system preferences.

### Files Version

3.7.6.0

### Windows Version

10.0.22621.4169

**Comment by yaira2** [comment]
We have a new design for the grid layouts that includes a border. While we’re still polishing the details and haven’t implemented it yet, rest assured that the updated design will address your concerns about contrast.
