### ISSUE TITLE
Proton Drive support

### ISSUE THREAD

**Issue by benjamin-Keller** [files-community/Files#16243]
### What feature or improvement do you think would benefit Files?

Adding `Proton Drive` support will be good as it acts similar to `OneDrive` on the regular File Explorer, however it does not get shown in `Files`. Screenshots follows:

<details>
<summary>File Explorer</summary>

![image](https://github.com/user-attachments/assets/3b029a38-2c32-4fcc-9ab5-ca936f18d10d)
</details>

<details>
<summary>Files</summary>

![image](https://github.com/user-attachments/assets/42c6e3ee-49e0-4c66-a6b7-01ada9c3faef)
</details>

### Requirements

- Similar to OneDrive support, allow Proton Drive to be shown as a drop-in replacement

### Files Version

3.7.7.0

### Windows Version

10.0.22631.4169

### Comments

Not great with feature requests, however this is just to try bring `Proton Drive` to `Files`

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Files should already support this, Please make sure you have the cloud drive section enabled on the sidebar by right clicking the blank part.

**Comment by benjamin-Keller** [comment]
I saw a previous post, I forgot to take out "is open" on the search filter and saw I had to just restart Files, thanks for coming to this as fast as you did!
