### ISSUE TITLE
Recycle Bin shown as Shell:RecycleBinFolder

### ISSUE THREAD

**Issue by STGYO** [files-community/Files#16248]
### Description

The Recycle Bin is having errors. Please look into the Steps to Reproduce on how that error occured. I have described it there. I have no idea what is causing this kind of behaviour, so I don't know  what the issue is. Thanks!

### Steps To Reproduce

1. Ensure that The Files App is configured to open at Start
![Screenshot 2024-09-23 205931](https://github.com/user-attachments/assets/317059c9-3013-4cba-8b11-34e88557837d)
2. Open the  app
 ![Screenshot 2024-09-23 205739](https://github.com/user-attachments/assets/e22b19bf-fa29-471a-a7ff-721b3d98faa1)
3. You will notice at the sidebar that the Recycle Bin is shown as Shell:RecycleBinFolder and after clicking into it, an error pops up.
![Screenshot 2024-09-23 205827](https://github.com/user-attachments/assets/f561b09f-e927-4a2a-8298-615fa92350c2)
4. You can also fix it by closing the files app and quiting the background process.
 ![Screenshot 2024-09-23 205756](https://github.com/user-attachments/assets/5acf4578-c49e-413b-aaa1-5630bf2ea3da)
5. Restart the Files App and the Recycle Bin is restored as it should be and also working as normal
![Screenshot 2024-09-23 211739](https://github.com/user-attachments/assets/6fb1183b-6556-460a-ab43-25e1189fb2ca)

### Requirements

This Error should be fixed as soon as possible as it gets annoying to restart the Files App everytime that happens.

### Files Version

3.7.6.0

### Windows Version

10.0.22631.4169

### User ID

files-community

### Log File

[debug.log](https://github.com/user-attachments/files/17100192/debug.log)

**Comment by 0x5bfa** [comment]
Thanks for the report.

This is the same as #15083. Click Subscribe to get notified of the further info on this when we have an update.

**Comment by 0x5bfa** [comment]
One thing I can tell since I got started working on shell namespaces, navigations via shell namespaces in some place seem to be working.

**Comment by STGYO** [comment]
Can it be fixed by myself as said in the workaround  in Issue #15083?

**Comment by Josh65-2201** [comment]
Try it and see
