### ISSUE TITLE
Can't download v3.7.7

### ISSUE THREAD

**Issue by spinstartshere** [files-community/Files#16245]
### Description

Using the classic installer or the preview installer files on the download page only allows me to install v3.7.6, which I already have installed. v3.7.7 was released a week ago.

### Steps To Reproduce

Download the classic installer or the insider preview installer from https://files.community/download

### Requirements

Update installation to v3.7.7

### Files Version

3.7.6.0

### Windows Version

10.0.26100.1742

### User ID

files-community

### Log File

N/A

**Comment by yaira2** [comment]
v3.7.7 is currently only available for the Store version. It will be deployed for the non-store version when our code signing certificate is finished being renewed.
