### ISSUE TITLE
QuickLook stopped opening previews in Files

### ISSUE THREAD

**Issue by vTOKAREVv** [files-community/Files#16246]
### Description

Just stopped working QuickLook in Files, in Windows Explorer everything works. I can't tell if it was caused by windows updates or not, it happened at a random moment. Files and QuickLook have been reinstalled, but that didn't solve the problem. I've tried different files, QuickLook doesn't respond to them in any way.

### Steps To Reproduce

1. Start Files and QuickLook.
2. Select any file.
3. Press space.

### Requirements

Solve the problem with opening QuickLook previews in Files

### Files Version

3.7.6.0

### Windows Version

10.0.22631.4169

### User ID

files-community

### Log File

[debug1.log](https://github.com/user-attachments/files/17091555/debug1.log)

**Comment by yaira2** [comment]
Thank you for the report. This is a known issue with version 3.7.6 and has been resolved in version 3.7.7. If you have the Microsoft Store version of Files, the fix should already be available. For the non-Store version, the update will be available once our code signing certificate renewal is complete.

**Comment by Cris--** [comment]
Same problem here with Files 3.9.1.0 (Store version), Windows 11 24H2 26100.4061 and QuickLook 4.0.1

[debug.log on pastebin...](https://pastebin.com/NuAiFZVm)

**Comment by yaira2** [comment]
Please make sure QuickLook is open and running the background.

**Comment by Cris--** [comment]
> Same problem here with Files 3.9.1.0 (Store version), Windows 11 24H2 RP 26100.4061 and QuickLook 4.0.1
> 
> [debug.log on pastebin...](https://pastebin.com/NuAiFZVm)

It works now after a restart, weird.  :/
