### ISSUE TITLE
I want a font selection feature.

### ISSUE THREAD

**Issue by QuestDragon** [files-community/Files#16249]
### What feature or improvement do you think would benefit Files?

It's been a while.
I previously posted an issue on a different topic.
Thank you for your time.

Regarding this issue, I know that you can change the font from a Json file, but **I thought it would be convenient to have an option to change the font in the UI**, so I created an issue.

Also, I'd like to ask for your advice, but what font name should I specify in `AppThemeFontFamily`?

- Font file name (the part before otf or ttf)
- The part of the font name that appears in the upper left corner when you open the font preview
- The part of the font name that appears when you display the font list from the control panel

By the way, I am Japanese, so I would like to specify a Japanese font, **but even when I specify it, the font does not change**, and it is replaced with a character code _(such as u30d2)_, so I am wondering what to do.

I would appreciate it if you would consider my proposal and also let me know the details of my consultation.

### Requirements

- Place a combo box in the settings screen and allow font selection from here

### Files Version

3.7.6.0

### Windows Version

10.0.19045.4894

**Comment by 0x5bfa** [comment]
Thanks for the feedback.
フィードバックありがとうございます。

> I thought it would be convenient to have an option to change the font in the UI

Redirecting to @yaira2 

> what font name should I specify in AppThemeFontFamily?

The font name displayed in font viewer.
フォントビューアーに表示されている名前です。

**Comment by mak-kawa** [comment]
日本語フォント名には，対応する英語フォント名があります．例えばメイリオは『Meiryo』です．これを設定すれば JSON 上の文字化けは無くなりますが．．．残念ながら Files の表示フォントはなぜか変わりません．Segoe UI Variable のままのように見えます．私にはその理由は分かりません．

Google translation :
Japanese font names have corresponding English font names. For example, メイリオ is "Meiryo". Setting this will eliminate garbled characters in JSON... but unfortunately, the font displayed in Files actually does not change for some reason. It appears to remain as Segoe UI Variable. I don't know why.

**Comment by Josh65-2201** [comment]
Make sure to close Files from the system tray when editing the settings file.

**Comment by mak-kawa** [comment]
Thank you for quick response
I confirmed font change by the JSON editing as you said.
Files displayed in "MS Mincho" font is really funny...

**Comment by 0x5bfa** [comment]
I'm wondering if the serializer just serialize properly.
Sorry but this feature isn't supported any more and we have another plan, we would not fix issue unless a contributor tries.

**Comment by QuestDragon** [comment]
> Thanks for the feedback. フィードバックありがとうございます。
> 
> > I thought it would be convenient to have an option to change the font in the UI
> 
> Redirecting to @yaira2
> 
> > what font name should I specify in AppThemeFontFamily?
> 
> The font name displayed in font viewer. フォントビューアーに表示されている名前です。
> 
> > even when I specify it, the font does not change
> 
> Paste here the font name. What happens if you set a font something called in English? フォント名はなんですか？ 英語表記のフォントを設定した場合正しく表示されますか？

If you specify a font name in English, it will not be replaced with the character code, **but at the same time it will not be reflected.**

Of course, if you use a Japanese font with English characters such as `Meiryo UI`, the font will be displayed correctly and no character code conversion will be performed.

The font name I am trying to set is:
 "Kozuka Gothic Pro B" 
"小塚ゴシック Pro B"

I also tried specifying various other Japanese font names, and also tried a variety of other things that I thought might be font names, such as the font file name and the font name displayed in the font viewer, but it didn't work with fonts with Japanese names.

**Comment by mak-kawa** [comment]
I don't really understand the reason, but... what would happen if you wrote it like this, font-family name without "B"?
"AppThemeFontFamily": "Kozuka Gothic Pro",

I don't have Kozuka Gothic Pro, so I wrote Kozuka Gothic Std in the JSON and it works properly.
"AppThemeFontFamily": "Kozuka Gothic Std",

**Comment by QuestDragon** [comment]
**It has indeed been changed!**
But it is not the same as the file name of the font, and I cannot find the name “Kozuka Gothic Pro” when I use the font viewer.
Where can I find the English name of these Japanese fonts?

**Comment by QuestDragon** [comment]
I've managed to find out, so I'll let you know.
It seems that you can reflect this by using **FontForge**, loading the font file from the` Fonts folder`, opening `Element `-> `Font Info`, and specifying the name listed in the `Family Name` column in the JSON file.

However, it's a bit disappointing that for font files that offer several thickness variations, such as bold, you cannot specify the thickness you want.
There may be a way to specify it, but I don't know what it is...

**Comment by mak-kawa** [comment]
I think the reason is... File app uses different font weight/style in various portion chosen from one specific font family, e.g. Kozuka Gothic Pro.
For example, see the breadcrumb list at the top of the window. The last path is displayed by bold style different from the other path with normal style.

So, if the File app wholly uses the font of single weight (e.g. Kozuka Gothic Pro B), such discriminating display would be impossible, I think.

Excuse me if I am wrong.

**Comment by 0x5bfa** [comment]
> File app uses different font weight/style

Yeah but don't specify font name for bold or light weight fonts just set a property for it.

---

For example, "Segoe UI Variable Text" works as expected, iirc there's weight specific fonts for it and the framework changes based on the property I guess.

**Comment by 0x5bfa** [comment]
> File app uses different font weight/style

Yeah but we don't specify font name for bold or light weight fonts just set a property for it.

---

For example, "Segoe UI Variable Text" works as expected, iirc there's weight specific fonts for it and the framework changes based on the property I guess.

**Comment by 0x5bfa** [comment]
Fwiw (just ignore this), maybe we should [specify all Unicode range](https://learn.microsoft.com/api/system.text.json.jsonserializer.deserialize?view=net-8.0#system-text-json-jsonserializer-deserialize(system-text-json-nodes-jsonnode-system-type-system-text-json-jsonserializeroptions)). If someone can work on this, I'd be happy to review and help them out.

We serialize here:
https://github.com/files-community/Files/blob/99b840889768921a6eb5e09b6e15c9f53a021315/src/Files.App/Utils/Serialization/Implementation/DefaultJsonSettingsSerializer.cs#L17
Deserialize here:
https://github.com/files-community/Files/blob/99b840889768921a6eb5e09b6e15c9f53a021315/src/Files.App/Utils/Serialization/Implementation/DefaultJsonSettingsDatabase.cs#L122
