### ISSUE TITLE
Files UI isn't used when Windows prompts you to open a file

### ISSUE THREAD

**Issue by VanillaGT** [files-community/Files#16244]
### Description

Just a simple issue that occurs when Windows prompts to open a file within a program or similar process.

![image](https://github.com/user-attachments/assets/31eefb7a-2443-4bb2-868d-485ab7464972)

### Steps To Reproduce

1. Simply find a program or process that allows you to choose and open files to spawn the explorer process.

### Requirements

I would hope that Files would be used as the default process when Windows asks the user to open or select a file within a program.

### Files Version

3.7.6.0

### Windows Version

10.0.22631.4169

### User ID

files-community

### Log File

[debug.log](https://github.com/user-attachments/files/17091254/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, This isn't something Files can change right now as Windows doesn't have a way of doing so.

**Comment by yaira2** [comment]
The Open and Save dialogs are integral parts of the Windows OS, and currently, there is no official method to replace them with third-party apps like Files. Should Microsoft introduce support for this feature, we would be eager to implement it. In the meantime, we encourage you to share your feedback with Microsoft via the Feedback Hub.
