### ISSUE TITLE
Keep acrylic effects even when unfocused

### ISSUE THREAD

**Issue by SeleDreams** [files-community/Files#16257]
### What feature or improvement do you think would benefit Files?

Right now, when Files loses focus, it loses the acrylic effect and disables all effects for a flat color, it feels very jarring. (right is focused, left is unfocused)

![{116AFCDA-9BF8-4C00-B210-1FD0F687085D}](https://github.com/user-attachments/assets/c46ccde6-dbae-4519-b160-47307a85e397)

It would be good to have a feature to preserve the applied background effect even when unfocused.

### Requirements

- Adjusting the behaviour of the background rendering to apply the effect when unfocused

### Files Version

3.7.7.0

### Windows Version

10.0.22631.4169

**Comment by mdtauk** [comment]
It is worth noting, this is currently the default and recommended way Acrylic works for performance reasons.

**Comment by SeleDreams** [comment]
> It is worth noting, this is currently the default and recommended way Acrylic works for performance reasons.

I do understand this aspect, i think having an option about it could be the best way to go about it. like a boolean toggle

**Comment by 0x5bfa** [comment]
I don't think we're going to the undocumented world. There isn't an official way to reenable. As @mdtauk mentioned this is disabled because of performance and battery aspects.

**Comment by mdtauk** [comment]
> I don't think we're going to the undocumented world. There isn't an official way to reenable. As @mdtauk mentioned this is disabled because of performance and battery aspects.

It would require abandoning the official way to handle it, and may not be compatible with Mica - even though it is technically possible as evidenced by Windows Terminal.

**Comment by Josh65-2201** [comment]
Yair has spoken on this https://github.com/files-community/Files/issues/3200#issuecomment-764373382

**Comment by yaira2** [comment]
Our position remains consistent with issue #3200. While we are not opposed to the idea in principle, the change would need to be implemented by the WinUI team. We encourage you to share your feedback with Microsoft through the Feedback Hub and the WinUI GitHub repository.
