### ISSUE TITLE
Set naam when adding a file or folder from toolbar in Dutch language

### ISSUE THREAD

**Issue by lfrvasseur** [files-community/Files#16259]
### What feature or improvement do you think would benefit Files?

When you add a file or folder a popup appears with the text Set Naam instead of Naam wijzigen. This is not translated well.
![Schermafbeelding 2024-09-25 143000](https://github.com/user-attachments/assets/0c2c5d8d-b63b-4fdc-81d3-923cc8399d79)
So Set Naam should be Naam wijzigen

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.7.7.0

### Windows Version

10.0.22631.4169

**Comment by yaira2** [comment]
Thank you for your feedback! Translations are managed through Crowdin. Could you please update the translation there?https://crowdin.com/project/files-app

**Comment by lfrvasseur** [comment]
Hi,

I did it and also translated some open strings.

Met vriendelijke groet,
Lawrence Vasseur
________________________________
Van: Yair ***@***.***>
Verzonden: Wednesday, September 25, 2024 10:08:54 PM
Aan: files-community/Files ***@***.***>
CC: lfrvasseur ***@***.***>; Author ***@***.***>
Onderwerp: Re: [files-community/Files] Set naam when adding a file or folder from toolbar in Dutch language (Issue #16259)


Thank you for your feedback! Translations are managed through Crowdin. Could you please update the translation there?https://crowdin.com/project/files-app

**Comment by yaira2** [comment]
Thank you! They will be included in the next update.
