### ISSUE TITLE
Bug: Can't open files set to open with UWP app

### ISSUE THREAD

**Issue by SeleDreams** [files-community/Files#16255]
### Description

I've set up several files to run via the UWP version of VLC, however when i double click them from Files, UWP vlc doesn't actually launch.
right clicking and manually selecting "open with" for the uwp vlc results in an error about a method not being found.
doing the same but for standard desktop vlc media player works fine.

### Steps To Reproduce

1. Install the UWP VLC from the microsoft store and set it as the default for opening mp4 files.
2. Start Files and try to open an mp4 file.

### Requirements

- Ensure Files properly starts the UWP program to load the specified file.

### Files Version

3.7.7.0

### Windows Version

10.0.22631.4169

### Log File

[debug.log](https://github.com/user-attachments/files/17115705/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report.

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
