### ISSUE TITLE
Developer performance - Console window integration

### ISSUE THREAD

**Issue by BlueDevDreamy** [files-community/Files#16252]
### What feature or improvement do you think would benefit Files?

Developers often use command lines, executing git commands or whatever.
The suggestion is to integrate command line windows as a bottom tab or sidebar inside the main window so that the user can work comfortably while working with file lists as well as cmd.

### Requirements

- Add "Use command line integration" item the "Developer Tools" option. Available options for position selectbox should be "Bottom, Right".
- Show command line panel inside the main window according to above setting.

### Files Version

3.7.6.0

### Windows Version

10.0.22000.2538

**Comment by 0x5bfa** [comment]
Thanks for the feedback.

This is the same as #6235. Also we've already worked on and now polishing it.

![image](https://github.com/user-attachments/assets/631fc2c2-3932-4a84-9627-f8b53d61b4d7)

**Comment by 0x5bfa** [comment]
I probably can't say anything particular but this is the first prototype and surely it won't be included in the first introduction afaik.

**Comment by yaira2** [comment]
> Multi tabs are possible? It should be helpful.

We would like to support that, but we need to some more exploration on the performance impact etc.
