### ISSUE TITLE
Developer Tools - IDE Integration

### ISSUE THREAD

**Issue by BlueDevDreamy** [files-community/Files#16253]
### What feature or improvement do you think would benefit Files?

I'm an Android developer as well as Java backend developer which means I don't use VS Code so much for my work.
But when I use Files, only available "Open IDE" option for now is "VS Code".
Customizing "Open IDE" option might helpful for many developers.

### Requirements

- Inside "Developer Tools" option, add "Available IDEs" item and let the user can add IDE executables with parameters and quick IDE detection setting. Each IDE item should include following suboptions: executable path (browsable, required), command line args (text input, optional), quick detection directories (text input, optional)
- At "Open" button action of the bottom bar on main window, set IDE list should appear.

### Files Version

3.7.6.0

### Windows Version

10.0.22000.2538

### Comments

Some IDEs should require additional parameters to accept the following path as opening workspace.
For example, the command should look like this: 
_my_ide.exe /s D:\workspace\project1_ 
while others look like: 
_ide.exe D:\workspace\project2_
to accept the current directory as opening workspace.
To fully support this, default appending command line arguments must be set.

Quick detection mode is a setting to determine which IDE should be preferred as default for selected directory.
Most IDEs and editors have settings & build directories or configuration files with unique names like:
_.vscode
.idea
package.json
apktool.yml
*.vcproj_

This can be used as an identifier with alone or combination of list like:
Android Studio:  _.idea_
Intellij:  _.idea_
VS Code:  _.vscode_
PhpStorm:  _.idea, index.php_ (combination - PhpStorm will be available as default when both identifiers are found.)
Sublime Text:  (no identifiers)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #12857 . You can check there or click subscribe in the right sidebar for updates.
