### ISSUE TITLE
Option to Expand to Open Folder in Files App (Like in Windows Explorer)

### ISSUE THREAD

**Issue by saulob** [files-community/Files#16250]
### What feature or improvement do you think would benefit Files?

In Windows Explorer, there's an option under Folder Options > View called "Expand to open folder." This feature automatically expands the folder structure in the sidebar to display the currently open folder, making it easier to navigate and see the folder hierarchy (as shown in the first image).

In Files, I would like to know if there's a similar option to automatically expand the sidebar to display the currently open folder, as in Windows Explorer (demonstrated in the second image). This functionality is helpful for easily navigating through different folder levels while keeping the structure visibl

![image](https://github.com/user-attachments/assets/9e25228d-0436-4d08-8007-24a1f5367271)
![image](https://github.com/user-attachments/assets/6f34e911-8887-4858-b8bc-535e20f4e771)

### Requirements

- Add an option similar to "Expand to open folder" in the Files app.
- Automatically expand the folder structure in the sidebar when navigating through directories.
- Ensure that this feature behaves similarly to Windows Explorer, where each open folder is visibly expanded in the sidebar.

### Files Version

3.7.6.0

### Windows Version

10.0.22621.4169

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #1928.  You can check there or click subscribe in the right sidebar for updates.
Right now Files doesn't have folder tree support at all.
