### ISSUE TITLE
Feature: Reduce minimum window height

### ISSUE THREAD

**Issue by Kamik423** [files-community/Files#16265]
### What feature or improvement do you think would benefit Files?

I frequently have my main screen taken up by an IDE while my file explorer is off in a corner. However, Files is just a bit too big to tile down into the height I want it (~1/3 screen height). I would appreciate the minimum window size being reduced a bit.

I don't see the reason to cap the size at this particular threshold, I can easily imagine a window being even half that height.

![image](https://github.com/user-attachments/assets/27bc742f-08f0-4288-a420-e09b4c34dbf8)

Thanks for your consideration.

### Requirements

- The minimum window height can be reduced

### Files Version

3.7.7.0

### Windows Version

10.0.22631.4169

**Comment by yaira2** [comment]
This is a reasonable request, I think we can set the minimum height to be the same as the Windows Settings app.

**Comment by Kamik423** [comment]
Nice, thank you!
