### ISSUE TITLE
Context menu "More options" missing items

### ISSUE THREAD

**Issue by fredericoregateiro** [files-community/Files#16260]
### Description

I use HP Wolf security, came installed on my HP laptop.
When a file is downloaded it's bloqued by the wolf security program and if we trust the file we must remove the protetion to open the file normally.

The remove option is missing from the context menu
![image](https://github.com/user-attachments/assets/b9d49c37-9b74-4365-aa16-35413171b287)

On the windows file manager the option is there
![image](https://github.com/user-attachments/assets/e57a0038-b84a-4375-9f9a-2cc1cb061892)

### Steps To Reproduce

1. Wolf Security installed
2. download a pdf file
3. try to remove the protetion created by the Wolf security

### Requirements

- The remove protetion option should appear no the context menu

### Files Version

3.7.7.0

### Windows Version

11

### User ID

files-community

### Log File

[debug.log](https://github.com/user-attachments/files/17138931/debug.log)

**Comment by 0x5bfa** [comment]
thanks for the report.

What happens if you just right click? It is supposed to show a context menu like ours. It's there?

**Comment by fredericoregateiro** [comment]
No, that option is only present if we right click on the file and the file was locked by the Wolf security program.

And just noticed that the context menus are in diferent languages, but it should be in english? I have english as a display language and a portuguese locale.

I can create another issue if this is not right.
The app definition
![image](https://github.com/user-attachments/assets/f511b084-6f13-43d7-9db3-373c3c885e23)

The windows definition
![image](https://github.com/user-attachments/assets/cd50bb44-2d5d-4497-91ba-ea582ef7e716)

**Comment by 0x5bfa** [comment]
I mean if you're on win11 that context menu style in file explorer isn't supposed to be shown when you just right click. Did you customize it or right clicked with shift pressed?

**Comment by fredericoregateiro** [comment]
No that options appear if i click in "Show more options"


https://github.com/user-attachments/assets/0a99edbf-3465-4798-b525-4cda611e9ea8

**Comment by Josh65-2201** [comment]
It could be something Wolf Security is doing to blocking visibility in other programs, Most security/malware scanners right now have this issue.

**Comment by fredericoregateiro** [comment]
@Josh65-2201 is there anything i could do to see if it's the case, or to try to fixit?

**Comment by Josh65-2201** [comment]
Not right now

**Comment by yaira2** [comment]
We're going to continue tracking this in #8251.
