### ISSUE TITLE
Tag can contain other Tags

### ISSUE THREAD

**Issue by topcoder0** [files-community/Files#16263]
### What feature or improvement do you think would benefit Files?

I want to organize tags like several trees, eg, 'work' contains ‘project1’，‘project2’...
when I tag a file with a sub-tag, its father tag automatically be attached to the file.

### Requirements

- organize tags like trees

### Files Version

3.7.7.0

### Windows Version

win11

**Comment by yaira2** [comment]
Can you confirm if this is the same request as #12738?

**Comment by topcoder0** [comment]
yes, thank you for your comment. I'll close it.

**Comment by topcoder0** [comment]
yes, thank you for your comment. I'll close it.
