### ISSUE TITLE
Bug: Can't drag and drop from Outlook

### ISSUE THREAD

**Issue by rayyesboulous** [files-community/Files#16266]
### Description

I am not able to drag and drop in files from outlook. i have to drop it on desktop than drag it to files

### Steps To Reproduce

1.Drag and drop a file from outlook
2. Files doesnt let you

### Requirements

- e.g. Fix crash that occurs when...
it should let you drop files from anywhere

### Files Version

3.7.7.0

### Windows Version

10.0.26100.1876

### User ID

files-community

### Log File

no log file

**Comment by Josh65-2201** [comment]
Thanks for the report.

**Comment by yaira2** [comment]
This issue appears to be a duplicate of issue [#13646](https://github.com/files-community/Files/issues/13646). Please follow the progress there for updates. This issue will be closed to consolidate the discussion.
