### ISSUE TITLE
Setup IDE

### ISSUE THREAD

**Issue by stanlrt** [files-community/Files#16269]
### What feature or improvement do you think would benefit Files?

The developer options offer to open folders in the IDE. But it does not allow choosing which IDE. I use Cursor, not VSCode.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

latest

### Windows Version

11

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #12857 . You can check there or click subscribe in the right sidebar for updates.
