### ISSUE TITLE
File copy - corrupted content

### ISSUE THREAD

**Issue by jerryx-jx** [files-community/Files#16268]
### Description

When copying large files (710MB+) over the network (mounted Synology drive, local Wi-fi), the contents of the destination file are always corrupted. Only parts of file - corrupted content have only zero bytes (00 00 00 00 00 ...).
Local copy is OK.

The bug only occurs on version 1.1.18 and 1.1.17. 
Version 1.1.16 is OK. 
I have done many tests - always the same result.

Double Commander - MAC versions:
Double Commander
Version: 1.1.18 gamma
Revision: 568
Commit: c45365d1b
Build date: 2024/09/21
Lazarus: 3.5.0.0
FPC: 3.2.2
Platform: aarch64-Darwin-cocoa
OS version: Mac OS X 15.0.0

### Steps To Reproduce

File copy over network, compare content.

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

1.1.18-568

### Windows Version

no win, macOS Sequoia 15.0

### User ID

files-community

### Log File

Log have only:
Done: Copy file /Users/petr/Temp/movies/TEST.mp4 -> /Volumes/video/#recycle/TEST.mp4

**Comment by Josh65-2201** [comment]
This is the wrong repository. https://files.community

**Comment by yaira2** [comment]
Thank you for reaching out and submitting an issue. It looks like this issue pertains to a different project. This repository is for Files, a modern file manager for Windows.

**Comment by jerryx-jx** [comment]
I'm sorry for my mistake ... wrong window :-P Thank you
