### ISSUE TITLE
pin no longer displays

### ISSUE THREAD

**Issue by ramsdu95** [files-community/Files#16273]
### Description

When I use files after a certain time the folders that I have pinned are no longer displayed and I have to close the application via the task manager to reopen it and see the elements in the pinned ones again
![Files no favoris](https://github.com/user-attachments/assets/038a426a-1854-4d57-8de0-e8514ee0431b)
![épinglé apres fin de tache](https://github.com/user-attachments/assets/9ba2216d-aa67-4298-8cea-ca4c6b156e56)

### Steps To Reproduce

![Files no favoris](https://github.com/user-attachments/assets/6190aaaf-e44d-4fbe-a714-f4e7dfd5d2f7)
![épinglé apres fin de tache](https://github.com/user-attachments/assets/f5a1d420-774f-4d8e-aafa-a02b0eacd212)

### Requirements

- e.g. Fix crash that occurs when...
![Files no favoris](https://github.com/user-attachments/assets/2cf80b0d-43c4-4338-b3a6-d85f0a1079a4)
![épinglé apres fin de tache](https://github.com/user-attachments/assets/b0762f14-3d57-4fd5-a2ef-bc2364801937)

### Files Version

3.7.7.0

### Windows Version

10.0.22621.4169

### User ID

files-community

### Log File

![Files no favoris](https://github.com/user-attachments/assets/18b6b8a4-fdf8-485d-a92e-c560cec9655f)
![épinglé apres fin de tache](https://github.com/user-attachments/assets/fe81c76c-bc84-40c8-ae3b-be7f05aac381)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #15410 . You can check there or click subscribe in the right sidebar for updates. Please also use the workaround listed and for future issues don't post the same screenshots in all of the text box's, it makes the issues unnecessarily long and hard to read.

**Comment by yaira2** [comment]
> [!Important]
> Current work around is to turn off `Files settings > Advanced > Leave app running in the background` then close and reopen Files. If the issue still happens try the instructions [here](https://answers.microsoft.com/en-us/windows/forum/all/windows-11-quick-access-folders-gone-and-pin-to/49b3f66a-062f-43e6-8417-728e2a42c896) and restart your computer.
