### ISSUE TITLE
Setting default manager wont work

### ISSUE THREAD

**Issue by eqemenesen** [files-community/Files#16274]
### Description

I cannot set it as my default app in the Files settings. 
Also tried the run as administrator.
The toggle is moves on and goes off again.

Files Version:
- 3.7.7.0
- C72F-4390

Windows Version:
- Edition	Windows 11 Home Single Language
- Version	23H2
- Installed on	‎11/‎29/‎2023
- OS build	22635.2771
- Experience	Windows Feature Experience Pack 1000.22679.1000.0

### Steps To Reproduce

1. just download the app and try to make it default

### Requirements

- I think it should give me a panel for accepting to changes in registry editor.

### Files Version

3.7.7.0

### Windows Version

10.0.22635 Build 22635

### User ID

files-community

### Log File

[debug.log](https://github.com/user-attachments/files/17177135/debug.log)

**Comment by yaira2** [comment]
To set Files as the default app, your user account must have administrator privileges. If it does and you’re still encountering issues, the permissions for the WindowsApps folder might be corrupted. Unfortunately, the most reliable way to fix these permissions is to reset Windows.
