### ISSUE TITLE
My  files crash when I open preview,it died and excit by self.

### ISSUE THREAD

**Issue by yiranbingyu** [files-community/Files#16270]
### Description

My  files crash when I open preview,it died and excit by self.

### Steps To Reproduce

1.open prefiles window
2.change any files,point one by one,so,sometimes ,files crash....
3.files runing slowly ,when open multi-tab.

### Requirements

- e.g. Fix crash that occurs when...
fix bug and optimize run by multi-tab.

### Files Version

3.7.7

### Windows Version

win11  22631.4169

### User ID

files-community

### Log File

[Files.exe.13768.dmp](https://github.com/user-attachments/files/17166831/Files.exe.13768.dmp)
[Files.exe.24944.dmp](https://github.com/user-attachments/files/17166832/Files.exe.24944.dmp)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #16226 . You can check there or click subscribe in the right sidebar for updates.
