### ISSUE TITLE
Pin To Start as default

### ISSUE THREAD

**Issue by Darkbluetest** [files-community/Files#16275]
### What feature or improvement do you think would benefit Files?

Hello

I don't know if I should post this here or as bug. The issue is that when right clicking an exe file, and wanted to pin it to start menu, the "pinning" is not the same as in vanilla explorer. And this has some consequences:

Tested in W11:
- If pinned from vanilla W11 explorer, the pinned app/exe shows its icon, its name is the file name (without extension) and it has 5 options in its context menu: move it, unpin it, run as admin, open file location, uninstall. Quite useful.
- If pinned from Files app, the pinned app shows Files yellow icon, its name is the file name with extension (!) and has only 3 options in context menu: move it, unpin it, run as admin.

Please, could it be possible that Files executes the same code/way to pin apps than the vanilla explorer? I found theses differences annoying. I don't know why it does not the same way: I tried running Files as admin, but no change.

Another important point is for people that uses ExplorerPatcher or similar to put back Windows 10 start menu (including tiles) in W11. This works very well by itself but the Files app way of pinning apps does not work at all (it does nothing), but still pinning the same app using vanilla W11 explorer, pins it normally (yes, even in ExplorerPatcher W10 menu, running in W11).

I know a lot of people that are using W11 BUT with W10 start menu (mainly with ExplorerPatcher), inlcuding myself (most of the time).

Thanks

### Requirements

- Could it be possible that Files executes the same code/way to pin apps than the vanilla explorer?

### Files Version

3.7.7.0

### Windows Version

W11 22631.4169

**Comment by 0x5bfa** [comment]
Thanks for the report.

Can you check if this is the same as #12191?

**Comment by Darkbluetest** [comment]
Well, kinda. Indeed is the same when checking in W11 start menu. Maybe both posts could be merged if when looking for a solution, it could be checked that it works in the W10 start menu replacement too.

**Comment by Josh65-2201** [comment]
We will continue tracking in #12191
If the start menu patcher copies the information from the normal start menu then it would be fixed there too, if not it would be up to the patcher to fix.
