### ISSUE TITLE
Window dragging is laggy

### ISSUE THREAD

**Issue by jackTabsCode** [files-community/Files#16272]
### Description

Dragging the window appears to be running at 60 FPS. I have a 240 Hz monitor and it's very apparent how laggy window dragging is compared to other apps.

### Steps To Reproduce

Have a high refresh rate monitor and drag the windo waround.

### Requirements

Investigate why the window dragging is not smooth and resolve it.

### Files Version

3.7.7.0

### Windows Version

10.0.22635.3139

### User ID

I don't see this option.

### Log File

[debug.log](https://github.com/user-attachments/files/17173522/debug.log)

**Comment by jackTabsCode** [comment]
It seems like the preview version is a bit better. To my eye, it looks like it's dragging at maybe 90-120 FPS. But still, it's not as smooth as any other app on my system

**Comment by Josh65-2201** [comment]
Thanks for the report, this is an issue with Microsoft WinUI please report it there https://github.com/microsoft/microsoft-ui-xaml/issues/new/choose

**Comment by jackTabsCode** [comment]
@Josh65-2201 Is there is an existing issue filed by your team? I don't really think it makes sense for me, a user of a software that uses an SDK I am completely unfamiliar with, to file an issue with that SDK.

**Comment by 0x5bfa** [comment]
Lagginess is what WASDK has been said. I think WinAppSdk 1.6 has fixed to some extent and we have plan to upgrade from 1.5

**Comment by yaira2** [comment]
Unfortunately, this issue is beyond our control, but we expect improvements with future WinUI updates. We encourage users to provide feedback directly to Microsoft, as real-world feedback helps them prioritize and address issues more effectively.
