### ISSUE TITLE
UI covering folder after jumping by typing letter

### ISSUE THREAD

**Issue by TomerGadol** [files-community/Files#16281]
### Description

When using the smallest size in 'details' layout and jumping to a folder by typing its first letter, the UI is covering about 6 rows of folders including the desired folder.
If I switch to the 2nd smallest size, the issue doesn't happen.

### Steps To Reproduce

1. Open a folder containing many subfolders
2. Use 'details' layout with smallest size
3. Search for a folder by typing its first letter

### Requirements

Fix the bug where the UI is covering the desired folder

### Files Version

3.7.7.0

### Windows Version

10.0.19045.4957

### User ID

files-community

### Log File

[debug.log](https://github.com/user-attachments/files/17185791/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #14739. You can check there or click subscribe in the right sidebar for updates.

**Comment by TomerGadol** [comment]
Okay thanks, I looked for similar issues but didn't see that one.

**Comment by yaira2** [comment]
No worries, searching for issues in GitHub can be a challenge.
