### ISSUE TITLE
Bug: Some files types take a while to open

### ISSUE THREAD

**Issue by andrew-james-heard** [files-community/Files#16286]
### Description

sometimes, but only sometimes, when I press Enter on a file (eg. LibreOffice writer .odt or calc .ods) the application takes ages to open. It appears to stall. I discovered if I kill Files.exe from Sysinternals Process Explorer that the application opening resumes. I get the impression Files has temporarily/ incorrectly locked the file. If I open the application from Start menu instead of indirectly by file association, then never a problem. Seems to have started recently. Doesn't happen with Explorer.

### Steps To Reproduce

1. select a file with cursor+Up/ Down
2. press Enter
3. default app associated with file will be opened, and passed the path
4. observe (sometimes) the sequence is delayed because, maybe, Files.exe has not let go of the file?

### Requirements

- e.g. Fix crash that occurs when...
.

### Files Version

3.7.9

### Windows Version

10.0.22631.4169

### User ID

a89c587c-81e1-4f41-826c-5c87169b5c2b

### Log File

[debug.log](https://github.com/user-attachments/files/17198123/debug.log)

**Comment by andrew-james-heard** [comment]
Yair - please update the Summary to something you know is better.

**Comment by yaira2** [comment]
@andrew-james-heard do you know which file formats have this issue? We have two different code paths for launching files and depending on the file extension, we use the method that works best.

**Comment by andrew-james-heard** [comment]
I mentioned LibreOffice writer .odt & calc .ods. I've only experienced this huge  (like a minute+) slowdown. A bit more than "a while". Delete Files.exe & instantly the opening continues.

**Comment by andrew-james-heard** [comment]
unrelated but when ctrl+shift+N is used to create a new folder the textbox no longer has focus, you have to press Tab 1st; doesn't seem worth creating a new bug report for that; pretty sure it used to be the case after ctrl+shift+N you just started typing the name

**Comment by yaira2** [comment]
This is an issue with WinUI and will hopefully be resolved on their end.

**Comment by andrew-james-heard** [comment]
WinUI for ctrl+shift+N? Can't be 100% but though it only started happening recently. Write your own "Enter an item name" dialog?
![image](https://github.com/user-attachments/assets/16ac7597-1e26-46a9-bc44-67268f5957c5)

**Comment by andrew-james-heard** [comment]
I just upgraded to 3.7.10 & now the textbox above has initial focus in the dialog when ctrl+shift+N is pressed. Expected?

**Comment by yaira2** [comment]
v3.7.9 had a newer version of WinUI that we were testing out.

**Comment by andrew-james-heard** [comment]
3.7.9 had the reported issue, apparently fixed (changed?) in 3.7.10; it's only a very minor point

**Comment by yaira2** [comment]
Can you check if this issue applies when turning off your anti-virus? It's possible that it scans files when opened from a third-party process such as Files and can potentially cause a slowdown depending on the size.

**Comment by andrew-james-heard** [comment]
Sorry but I've stopped using files. It was too sluggish on my PC. Sadly reverted to Explorer.
