### ISSUE TITLE
Files only shows one Google Drive under drives

### ISSUE THREAD

**Issue by razorsoup** [files-community/Files#16284]
### Description

Mapping more than one Google Drive account to drive letters results in only one of them displaying in the Drives section of Files
![image](https://github.com/user-attachments/assets/8186b754-c2ac-40a4-a97d-76b348d20b1d)

### Steps To Reproduce

Map two separate Google Drives as streaming drives / drive letters.

### Requirements

Show all mapped Google Drives.

### Files Version

3.7.7.0

### Windows Version

10.0.22631.3593

### User ID

files-community

### Log File
[debug.log](https://github.com/user-attachments/files/17196809/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, Can you close Files from the system tray and reopen

**Comment by razorsoup** [comment]
I have exited from the system tray and reopened Files and tried rebooting my computer but there is no change in behaviour

**Comment by Josh65-2201** [comment]
Thanks for checking, We're tracking this in #15098. You can check there or click subscribe in the right sidebar for updates.
