### ISSUE TITLE
tagged files are missing after each update

### ISSUE THREAD

**Issue by Silther** [files-community/Files#16288]
### Description

Files are missing from the tags section on the home screen after each update
![image](https://github.com/user-attachments/assets/83a20cb1-57af-49a2-bb77-2b5ca941047d)
but if you go to the folder with the missing files you can see that they are still tagged correctly
![image](https://github.com/user-attachments/assets/e4d67ecf-0d29-48a7-aaea-3d54b256d416)

### Steps To Reproduce

1. tag some files of your choosing
2. update the files app
3. open it and see the tagged files gone

Additional Information:
1. most of the tagged files are in a OneDrive folder synced with a PC with the same tagged files and naming scheme
2. sometime after an restart missing tagged files reappear under "unknown tag"

### Requirements

- tagged files should not disappear after updating

### Files Version

3.7.7.0

### Windows Version

10.0.22631.4249

### User ID

files-community

### Log File

[debug.log](https://github.com/user-attachments/files/17206292/debug.log)

**Comment by yaira2** [comment]
A fix for this issue was added in v3.7.7. Unfortunately, the fix only helps for updates following v3.7.7. However, you can be assured that the issue has been resolved and should not occur again.
