### ISSUE TITLE
For My Download folder sorting is not working

### ISSUE THREAD

**Issue by sudhanshoosaxena** [files-community/Files#16280]
### Description

Hi Team,
I have observed, that for my Download folder in windows 10, your product is not working well. Sorting is not working here properly.
Whatever latest folders are there its not showing those, even I sort them.
So latest updated folders are present there but application sorting feature is not showing those.

### Steps To Reproduce

1. go to the download folder and sort them
2. check for the latest updated folder inside the download folder.
3. It should show those latest updated folder first.

### Requirements

- It should show the folders whichever latest updated inside a folder le download.

### Files Version

3.7.7.0

### Windows Version

10.0.19045.4957

### User ID

files-community

### Log File

No Log file is required

**Comment by Josh65-2201** [comment]
Thanks for the report, 
- Can you say what your sorting and grouping options are set to in Files.
- Can you send a screenshot of Windows File Explorer compared to Files

**Comment by yaira2** [comment]
Does refreshing the folder update the sort order?

**Comment by Josh65-2201** [comment]
@sudhanshoosaxena Can you answer the above questions
