### ISSUE TITLE
File copy/cut from MTP device (e.g. mobile phone) does not paste into Windows File Explorer

### ISSUE THREAD

**Issue by eclipse666** [files-community/Files#16285]
### Description

Copy/Cut does not work correctly when selecting from MTP device files (e.g. mobile phone) and pasting into Windows File Explorer. The paste operation does nothing in Windows File Explorer. Copy/cut/paste between Files and Windows File Explorer works correctly with regular files.

### Steps To Reproduce

Connect your mobile phone (in my case an Android phone) to the PC and select the "transfer files" option when the phone prompts you. Using Files, navigate to any file on the phone, select it and select the "copy" option. Switch to Windows File Explorer and select paste - nothing happens. "Cut" has the same problem

### Requirements

The file(s) should be copied/cut into Windows Explorer

### Files Version

3.7.7.0

### Windows Version

10.0.22631.4169

### User ID

files-community

### Log File

[debug.log](https://github.com/user-attachments/files/17196819/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #14416. You can check there or click subscribe in the right sidebar for updates.
