### ISSUE TITLE
About copying files between VMware virtual machines

### ISSUE THREAD

**Issue by J1oo** [files-community/Files#16282]
### Description

When I copied the entire folder to the vmware virtual machine, only the folder shell was copied, and the contents of the folder were not copied over

### Steps To Reproduce

1. copy the folder
![image](https://github.com/user-attachments/assets/1597f6ad-6b0a-45c3-920b-1aad9e780160)
2.Paste to VM
![image](https://github.com/user-attachments/assets/052dd6f8-0b47-4b74-9a2c-eea11b31cb98)
3.I found that the contents of the folder were not copied.
![image](https://github.com/user-attachments/assets/2d1693b3-f67a-42cc-b317-aa898eae41d8)

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.7.7.0

### Windows Version

10.0.22631.4037

### User ID

files-community

### Log File

[Uploading debug.log…]()

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #12543 . You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
It's interesting to note that the folder was copied, if I recall correctly, in the past, nothing was copied at all.
