### ISSUE TITLE
Separate Input Field for Folder Path in Dual-Pane Mode

### ISSUE THREAD

**Issue by mirgorodalexander** [files-community/Files#16287]
### What feature or improvement do you think would benefit Files?

Currently, the dual-panel view in Files lacks separate input fields for each panel where the folder path is directly visible. To view or copy the current path, the user must first click on the desired panel and then on the address bar, resulting in additional, unnecessary steps. Adding a distinct address field for each panel would streamline workflows, allowing users to quickly view or copy paths without repetitive clicking.

Use Case:
When navigating in a two-panel layout, users often need to know the exact paths they are working with in both panels. This feature would reduce the number of clicks required, enhancing user experience by making navigation more efficient and less cumbersome. It’s particularly useful for users who frequently copy paths or work with numerous folders and files simultaneously.

Here is how it can looks like:

![image](https://github.com/user-attachments/assets/56f838b9-f07a-4ec5-b174-eb3092bde453)

### Requirements

- Add Separate Input Fields: Implement a visible and editable folder path field for each of the two panels in dual-pane mode.
- Direct Access to Path Field: The path field should be always accessible, allowing users to view, edit, and copy paths without needing to first click into the panel.
- Synchronization with Panel Selection: Ensure the address field is dynamically updated as the user navigates through folders in each panel.
- Visibility Adjustment: The input fields should be prominently visible but should not take up excessive screen space; balance visibility with screen real estate.
- Copy Functionality: Users should be able to click and copy, cut, edit the path directly from the input field without additional interactions.
- User Interface Consistency: Maintain a design that fits seamlessly with the existing visual style of Files.
- Configurable Option: Provide users with the option to toggle these input fields on or off to cater to varying preferences.

### Files Version

3.7.7.0

### Windows Version

10.0.22631.4169

### Comments

Thank you, files are really awesome! <3

**Comment by 0x5bfa** [comment]
Thanks for the feedback.

Can you check if this is the same as #14377

**Comment by mirgorodalexander** [comment]
Yes, it's exactly what im talking about :)

**Comment by 0x5bfa** [comment]
Please click Subscribe to be notified of the further news in case we have in the future.
