### ISSUE TITLE
Ability to print a selected file

### ISSUE THREAD

**Issue by lfrvasseur** [files-community/Files#16299]
### What feature or improvement do you think would benefit Files?

If you select a file in Files, it would be more productive if you could print the document directly in the pop-up menu (by right-clicking), now there is a possibility to power-rename or combine in Adobe but printing is not possible.
![Schermafbeelding 2024-10-03 153613](https://github.com/user-attachments/assets/73ea9412-d0ac-4f6e-b5cd-531b809e8288)

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.7.7.0

### Windows Version

10.0.26100.1882

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Does Window File Explorer show an option to print?

**Comment by lfrvasseur** [comment]
No, explorer does not. It did in Windows 10 actually ;)

​Met vriendelijke groet,
Lawrence Vasseur | 0657108755
________________________________
Van: Josh65-2201 ***@***.***>
Verzonden: Thursday, October 3, 2024 7:48:06 PM
Aan: files-community/Files ***@***.***>
CC: lfrvasseur ***@***.***>; Author ***@***.***>
Onderwerp: Re: [files-community/Files] Ability to print a selected file (Issue #16299)


Thanks for the feedback, Does Window File Explorer show an option to print?

**Comment by yaira2** [comment]
"The shell extensions in Files are identical to those in File Explorer. If the print option was removed in Windows 11, unfortunately, we can't reinstate it as it’s managed directly by Windows.
