### ISSUE TITLE
Bug: Right click in column view in WSL crashes app

### ISSUE THREAD

**Issue by asorge-intrepid** [files-community/Files#16292]
### Description

When browsing a WSL directory in column layout, right-clicking any element crashes the app every time

### Steps To Reproduce

1. Browse a WSL directory
2. View using "Columns" layout
3. Right-click any element
4. -- Crash --

### Requirements

Context menu opens successfully and no crash

### Files Version

3.7.7.0

### Windows Version

10 & 11 (tested on multiple machines)

### User ID

files-community

### Log File

[debug.log](https://github.com/user-attachments/files/17219188/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by asorge-intrepid** [comment]
It still has the same crashing behavior with the preview version.
I tried the other layout options, none of the other ones crash, just the column layout.

**Comment by elcamil0** [comment]
I have the same problem, the application closes very frequently, has anyone been able to solve it?

**Comment by yaira2** [comment]
We're currently tracking this in #16193.
