### ISSUE TITLE
Feature: Select tab when clicking above in the drag area

### ISSUE THREAD

**Issue by Disketaa** [files-community/Files#16293]
### What feature or improvement do you think would benefit Files?

It would be nice to have a similar feature like in Chrome where you can move cursor on-top of a tab, even higher than tab itself, but it will selected anyway

![image](https://github.com/user-attachments/assets/9a2abc67-3108-4ec6-a4c8-9dc986022d7f)
![image](https://github.com/user-attachments/assets/69cfb4d2-c085-45c7-a968-33315fb38a9d)

### Requirements

Hover tab a bit higher than the tab itself

### Files Version

3.7.9.0

### Windows Version

10.019045

**Comment by 0x5bfa** [comment]
Didn't we do this on purpose for users to be able to drag on the whole upper area?

**Comment by Josh65-2201** [comment]
I believe so but other tab based programs remove the drag gap when the window is maximized. #14958 could be a blocker if this was made.

**Comment by 0x5bfa** [comment]
FYI, https://discord.com/channels/725513575971684472/958783217941487616/1203011431432200243

**Comment by yaira2** [comment]
As @0x5bfa mention, the area is designed to be draggable and we don't plan to change this. However, nothing is final and if anything changes in the future, we'll make sure to include it in the changelog.
