### ISSUE TITLE
Add a "Check for update" button in Files info 

### ISSUE THREAD

**Issue by Steperman5692** [files-community/Files#16297]
### What feature or improvement do you think would benefit Files?

So when Files get an update it doesnt notice me right away & it could be quite annoying from time to time; so I was wondering what if we add a "Check for update" button in Files info next to the "Copy" button in the About section in Settings.

### Requirements

- Add a "Check for update" button next to the "Copy" button in Files info section in the About section in Settings

### Files Version

3.7.7.0

### Windows Version

22631.4249

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #15681. You can check there or click subscribe in the right sidebar for updates.
