### ISSUE TITLE
Feature: Allow organization of groups in sidebar

### ISSUE THREAD

**Issue by cmpdc** [files-community/Files#16290]
### What feature or improvement do you think would benefit Files?

While I like how the current layout is organized: `Pinned`, `Libraries`, `Drives`, `Cloud Drives`, `Network`, `WSL`, and `Tags`, an ability to reorganize these groups will be huge.

I have multiple `Cloud Drives`—more specifically, multiple OneDrives and an iCloud. I think it would be beneficial to allow users to organize the groups however they want. Personally, I want to have my `Cloud Drives` above `Pinned`.

This implementation does not need to be drag-and-drop. It can be just the way how `Reorder sidebar items` works when triggering context menu from the `Pinned` group.

### Requirements

N/A

### Files Version

3.7.8.0

### Windows Version

Windows 11 23H2 (OS Build 22631.4169)

### Comments

N/A

**Comment by 0x5bfa** [comment]
Thanks for the feedback.

Is this the same as #13440?

**Comment by yaira2** [comment]
> Thanks for the feedback.
> 
> Is this the same as #13440?

Looks like it
