### ISSUE TITLE
New version crashes

### ISSUE THREAD

**Issue by ren46566** [files-community/Files#16295]
### Description

Hi,

I love the Files app.  Unfortunately, the most recent version crashes a lot.  I trust you're already aware of this and will correct in future versions. 

### Steps To Reproduce

It fairly random, but happens a lot.

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.7.7.0

### Windows Version

10.0.22631.4249

### User ID

files-community

### Log File

[debug.log](https://github.com/user-attachments/files/17234229/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

If so can you say what you are doing and if you have the info/preview pane open

**Comment by yaira2** [comment]
Thank you for letting us know, we believe this is resolved in the preview version, but it'll be best if you can confirm.
