### ISSUE TITLE
Rename icon not working when selecting multiple files

### ISSUE THREAD

**Issue by ckerno** [files-community/Files#16294]
### Description

In File Explorer, when I select multiple files and right-click them, I then click the Rename icon to rename them. In Files, when I do the same and try to click on the Rename icon, nothing happens. Note: If I have only one file selected, Rename icon works, but if I have multple files selected, nothing happens.

### Steps To Reproduce

1. Open Files
2. Select more than one file
3. Right-click on the files selected (or just click the Rename icon on the toolbar)
4. Click the Rename icon at the top of the menu
5. Nothing happens

### Requirements

I should be able to rename the multiple files selected.

### Files Version

3.7.6.0

### Windows Version

10.0.22000.2538

### User ID

files-community

### Log File

[debug.log](https://github.com/user-attachments/files/17232595/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, This is already added for the next update

**Comment by yaira2** [comment]
The preview version has support for renaming multiple files together. https://files.community/download
