### ISSUE TITLE
when set files as OS default file manager , wps office open file source dir function is not work

### ISSUE THREAD

**Issue by LucienYang** [files-community/Files#16301]
### What feature or improvement do you think would benefit Files?

I want wps open file dir is supported
![image](https://github.com/user-attachments/assets/1130996a-026f-4198-a894-111f7a7c375d)

### Requirements

- I want wps open file dir is supported 

### Files Version

3.7.7.0

### Windows Version

10.0.22635.4225

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Can you open a bug report and also check if pressing Win + E or opening Windows File Explorer opens Files

**Comment by LucienYang** [comment]
您好，收到这封邮件，代表您发的邮件我已收到，请放心
