### ISSUE TITLE
Bug: Incorrect number of files in Recycle Bin

### ISSUE THREAD

**Issue by jano23** [files-community/Files#16304]
### Description

Files Insider Preview 3.7.9.0 is showing the wrong amount of items in the Recycle Bin. I am sending screenshots of both Files versions.
I have tried uninstalling and reinstalling and running only Insider Preview version.

### Steps To Reproduce

1. Open Files Insider Preview
2.  Click on Recycle Bin
![Files3 7 7 0](https://github.com/user-attachments/assets/c28f9f0f-b5d3-4607-9e04-45396635c5aa)
![FilesPreview3 7 9 0](https://github.com/user-attachments/assets/b1c8e4a0-dca6-42f1-8803-6d4a1efa8ef7)

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.7.9.0

### Windows Version

10.0.22631.4249

### User ID

files-community

### Log File

[debug.log](https://github.com/user-attachments/files/17260127/debug.log)

**Comment by firelabs-io** [comment]
im no coder here, is probally on src/Files.App.Storage/Watchers/RecycleBinWatcher.cs or something like that

**Comment by 0x5bfa** [comment]
What version is that (the first one)?

**Comment by jano23** [comment]
> What version is that (the first one)?

3.7.7
The latest in production. 
And it coincides with what Windows Files Explorer reports

**Comment by yaira2** [comment]
@0x5bfa do you think this is related to #15773?

**Comment by 0x5bfa** [comment]
But I introduced it even before 3.7.7. Feel weird that these show different numbers. @jano23 can you try clean all items, recycle some times and see if the same issue persists?

**Comment by jano23** [comment]
> But I introduced it even before 3.7.7. Feel weird that these show different numbers. @jano23 can you try clean all items, recycle some times and see if the same issue persists?

I moved all the files from Recycle Bin to a temp folder and cleaned up some duplicates so that the Recycle Bin was empty. I then deleted the files in that temp folder. Ver 3.7.7.0 shows the correct amount of files in the Recycle Bin (172). Ver 3.7.9.0 shows the folder as empty. "This folder is empty"

**Comment by jano23** [comment]
Additional information: I have the Recycle Bin pinned to the Sidebar and I also have "Calculate folder sizes" enabled. When I hover over the Recycle Bin in the Sidebar, ver 3.7.9.0 shows the correct files size for the current contents in the Recycle Bin

**Comment by jano23** [comment]
BAM! 3.7.10 fixed the problem!!

**Comment by yaira2** [comment]
Thanks for letting us know
