### ISSUE TITLE
SFTP support

### ISSUE THREAD

**Issue by pnoelfr** [files-community/Files#16303]
### What feature or improvement do you think would benefit Files?

Can you add an SFTP built-in ???

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

Next

### Windows Version

Windows 10 et 11

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in https://github.com/files-community/Files/issues/2407. You can check there or click subscribe in the right sidebar for updates.
