### ISSUE TITLE
two little conveniences:

### ISSUE THREAD

**Issue by mvsteen** [files-community/Files#16308]
### What feature or improvement do you think would benefit Files?

Hi, i'd love these two little convenience features:

- ability to create a folder upon right clicking when having another item or folder selected. 
_In windows explorer, you can always right click to create a new folder in the current folder, there is no need for the mouse to be over whitespace. For clarity some context could be added to the 'new folder' string. Perhaps simply "new folder (current dir)"?_
- button or shortcut to open windows explorer when needed. _(such as for changing the 'show recent files' options)_

Thanks!

### Requirements

- This proposal will mimic a useful behavior from windows explorer.
- This proposal will allow opening windows explorer when needed in a quick and easy fashion.
- This proposal will reduce overal friction.

### Files Version

3.7.7.0

### Windows Version

10.0.22631.4249

### Comments

Oh and as an aside; can anything be done about the lagginess or the context menu? It's barely better than windows 11's default one, which apparently can get so laggy due to the XAML implentation.

**Comment by yaira2** [comment]
> ability to create a folder upon right clicking when having another item or folder selected.

Right clicking an empty space will deselect the existing item, consistent with the behavior in File Explorer.

> button or shortcut to open windows explorer when needed

We don't have plans to support this in Files, but you can always use the `win + e` shortcut to launch File Explorer.
