### ISSUE TITLE
powertoys "peek" integration

### ISSUE THREAD

**Issue by danielrdotcom** [files-community/Files#16300]
### What feature or improvement do you think would benefit Files?

Power toys "peek" feature is what I'm using instead of quicklook (hasnt been updated in a couple years). The keybind ctrl spacebar doesnt invoke peek in files like it does in explorer

### Requirements

integrate/allow powertoys "peek" with files

### Files Version

3.7.7.0

### Windows Version

10.0.22631.4169

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Peek doesn't have a way for Files to do this yet https://github.com/microsoft/PowerToys/issues/26422

**Comment by yaira2** [comment]
@danielrdotcom we encourage you to share this feedback with Microsoft. Files is ready and already has the foundation to support third-party previews, but it requires support from other parties as well. In the meantime, we recommend trying our supported options like QuickLook or SeerPro. https://files.community/docs/features/integrations
