### ISSUE TITLE
CRASH WHILE REPLACING FILES

### ISSUE THREAD

**Issue by nyoussefian** [files-community/Files#16312]
### Description

crashes while coping files.![Image](https://github.com/user-attachments/assets/b56cf68c-709c-402f-a77b-e77b3c608b07)

### Steps To Reproduce

open secondary pane
go to the google drive folder
copy local files
pasting on google drives folder, askint to skip duplicated files
app crashes

### Requirements

- e.g. Fix crash that occurs when...
![Image](https://github.com/user-attachments/assets/b55ca7d3-de0c-495d-96bb-d7baac4c5de2)

### Files Version

3.7.7.0

### Windows Version

Version	10.0.19045 Build 19045

### User ID

18860ED0-B7A8-412B-94F7-9973646EAE3F

### Log File

[debug.log](https://github.com/user-attachments/files/17278661/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by nyoussefian** [comment]
just by restarting the app, 2nd try went well.
Shouldn't I have reported it as an issue?

*----------------------------------------*
*Nicolás Agustín Youssefian*
Diseñador Audiovisual
+541152602254

**Comment by yaira2** [comment]
It never hurts to report an issue 🙂 

If it happens again, please let us know.

**Comment by nyoussefian** [comment]
thank you!

*----------------------------------------*
*Nicolás Agustín Youssefian*
Diseñador Audiovisual
+541152602254
