### ISSUE TITLE
Window Size and Position Not Persistent

### ISSUE THREAD

**Issue by HobbesKo** [files-community/Files#16315]
### Description

Since about v3.7.9 of Files Preview, when launching the app, the last used window size and position is not retained.
The issue is not present if Files is already running in the background or if it is minimized.

I'm using Files Preview v3.7.10.0 and this issue is still present.

### Steps To Reproduce

Launch Files when it is not already running.

### Requirements

The last used window size and position should be retained through app launches, just as it used to do with previous versions.

### Files Version

Files Preview v3.7.10.0

### Windows Version

Windows 11

### Log File

-

**Comment by yaira2** [comment]
Does this also apply to Files stable?

**Comment by HobbesKo** [comment]
No. Files stable v3.7.7.0 works as expected.

**Comment by yaira2** [comment]
A fix will be included in the next update.
