### ISSUE TITLE
Bug: "Pinned" section doesn't load

### ISSUE THREAD

**Issue by dmizz** [files-community/Files#16329]
### Description

Every other time I open Files the "pinned" section with my desktop, downloads... doesn't load. The area appears as if there are no pinned directories.

### Steps To Reproduce

open files.

### Requirements

Have pinned load reliably.

### Files Version

3.7.7.0

### Windows Version

24H2

### Log File

[debug.log](https://github.com/user-attachments/files/17318043/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #15410. You can check there or click subscribe in the right sidebar for updates.
