### ISSUE TITLE
Bug: double click this pc，I think I should open the homepage, but now it says it is not a folder.

### ISSUE THREAD

**Issue by qwer130140190** [files-community/Files#16326]
### Description

double click this pc，I think I should open the homepage, but now it says it is not a folder.![Image](https://github.com/user-attachments/assets/d4081224-30ce-4c51-8913-6b30f7ce6f4c)

### Steps To Reproduce

double click this pc

### Requirements

double click this pc

### Files Version

3.7.7.0

### Windows Version

10.0.26100.1882

**Comment by yaira2** [comment]
Did you pin "This PC" to the sidebar?

**Comment by qwer130140190** [comment]
> Did you pin "This PC" to the sidebar?

No, I didn't pin any directories. Additionally, the recycle bin in the sidebar doesn't display properly
![Image](https://github.com/user-attachments/assets/f31835de-f3a5-4d2d-ba7a-9e51c7ec5cc0)

**Comment by yaira2** [comment]
How are you launching This PC? Does restarting Windows help?

**Comment by yaira2** [comment]
Can you clarify how you're opening This PC in Files? Are you entering the path in the address bar?

**Comment by qwer130140190** [comment]
> Can you clarify how you're opening This PC in Files? Are you entering the path in the address bar?

![Image](https://github.com/user-attachments/assets/a3c811ff-95e5-43bc-9861-a4c5094f5eb3)

**Comment by Josh65-2201** [comment]
Please try reinstalling Files. You can backup your settings in Files settings > Advanced > Export/Import

**Comment by yaira2** [comment]
@qwer130140190 did reinstalling Files resolve the issue?

**Comment by qwer130140190** [comment]
> [@qwer130140190](https://github.com/qwer130140190) did reinstalling Files resolve the issue?

No, the problem still exists. It only occurs when the app is cold launched through Explorer

**Comment by yaira2** [comment]
We're going to continue tracking this in #15083.
