### ISSUE TITLE
Bug: Black Screen when opening Files

### ISSUE THREAD

**Issue by chmichael** [files-community/Files#16333]
### Description

Hello,
  I get a black screen for 1-2 seconds when i open Files.

### Steps To Reproduce

1. Open Files

### Requirements

  I get a black screen for 1-2 seconds when i open Files.

### Files Version

3.7.7.0

### Windows Version

Windows 11 24H2

### Log File

[debug.log](https://github.com/user-attachments/files/17333723/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, This is normal as Files has to load, startups improvements are being worked on but will take time.
