### ISSUE TITLE
Feature: Create alternate data streams

### ISSUE THREAD

**Issue by Zac0511** [files-community/Files#16337]
### What feature or improvement do you think would benefit Files?

I noticed that Files could view and delete alternate data streams, so it could be useful to be able to **create** alternate data streams too.
The user could right-click an existing file, click `create alternate data stream`, the user would choose a name (`[orignal file name, not editable]:[file name chosen by user]`).

### Requirements

- Add a `Create alternate data stream` button when right-clicking on a file

### Files Version

3.7.11.0

### Windows Version

10.0.22631.4317

**Comment by Josh65-2201** [comment]
Thanks for the feedback.

**Comment by yaira2** [comment]
It's a cool idea, we'll need to explore what goes into this as well a UX.

**Comment by Josh65-2201** [comment]
I would make sure it doesn't show when right clicking the blank space in drive root. As you need to reformat the drive to remove it.

**Comment by yaira2** [comment]
How should it work if there are multiple items selected?

**Comment by Josh65-2201** [comment]
I think it would make sense to add the ADS with the same name on all selected

**Comment by yaira2** [comment]
@Zac0511 this feature will be included in the next release.
