### ISSUE TITLE
Feature: Misaligned design

### ISSUE THREAD

**Issue by czargab18** [files-community/Files#16336]
### What feature or improvement do you think would benefit Files?

These two details bother me a lot!
![Image](https://github.com/user-attachments/assets/2e42084f-038a-421f-893a-f9df4ef8257e)

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.7.11.0

### Windows Version

23h2

**Comment by Josh65-2201** [comment]
Thanks for the feedback, you can change the sidebar width by dragging the divider, The extra space on the right is used for dropping to that folder if you have the columns maximizing the space

**Comment by czargab18** [comment]
> Thanks for the feedback, you can change the sidebar width by dragging the divider, The extra space on the right is used for dropping to that folder if you have the columns maximizing the space

I can't make the width down to what I want. The app minimizes the sidebar.
![Image](https://github.com/user-attachments/assets/50b3ba0e-7102-4995-895b-723c9a49a2d2)

**Comment by yaira2** [comment]
Thanks for your feedback! These are different areas of the app, and aligning them just for visuals would make the sidebar too narrow. However, you can enable the 'Home' button (Settings > Appearance) to offset the address bar. Hope this helps!

**Comment by czargab18** [comment]
> Thanks for your feedback! These are different areas of the app, and aligning them just for visuals would make the sidebar too narrow. However, you can enable the 'Home' button (Settings > Appearance) to offset the address bar. Hope this helps!

👍 👍 
![Image](https://github.com/user-attachments/assets/ca077e93-26d5-48c1-a3e8-b0a210907039)
