### ISSUE TITLE
Bug: Windows App Installer popup when launching Files App

### ISSUE THREAD

**Issue by cameron-fit** [files-community/Files#16335]
### Description

Hi Files-Community,

I noticed an odd bug when installing the Files App on a particular PC.

When launching the Files App, it pops up a Windows App Installer screen, as seen below: 
![Image](https://github.com/user-attachments/assets/e4b6f532-252d-461b-bfad-a889023a1983)

I've tried disabling Automatic Updates, Repairing, Reinstalling, Restarting, etc. 

Install methods: 
- Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/stable/Files.Package.appinstaller
- Files Classic Installer from the Website <https://files.community/download>

The Files App does launch after this occurs; it's just annoying that it doesn't load without showing this screen.

Please advise.

Cheers, 
Cameron 

### Steps To Reproduce

1. Launch Files App
2. * Windows App Installer "Checking for updates for your app ......"

### Requirements

- Fix bug that displays a Windows App Installer screen "Checking for updates for your app ...." when loading the Files App.

### Files Version

3.7.11.0

### Windows Version

10.0.22631.3880

### User ID

81bc7bd2-4795-445f-b85f-1e37a375dbf4

### Log File

[debug.log](https://github.com/user-attachments/files/17344185/debug.log)
[debug.log](https://github.com/user-attachments/files/17344184/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, This is an issue with App installer and there isn't anything Files can do. Please make sure Windows is up to date and App installer is from the Microsoft store

**Comment by yaira2** [comment]
I've found this issue to be resolved after updating App Installer to the latest version.

**Comment by yaira2** [comment]
Another option is to use the Store version which isn't installed via App Installer.

**Comment by cameron-fit** [comment]
The app installer was using the latest version.

I found the issue was caused by the network connection being in Metered Mode. 

Thanks for your assistance.
