### ISSUE TITLE
Bug: Recycle Bin won't show as empty in icon in the pinned section and on the home page of Files

### ISSUE THREAD

**Issue by brazenserpent7** [files-community/Files#16334]
### Description

Hi team, just wanted to let you know that the recycle bin isn't showing the emptied version after I've manually removed the files from the bin. Please fix this in a coming update.

### Steps To Reproduce

1. Open Files app on Windows 11
2. See Quick Access (Pinned folders) 
3. Notice that the Recycle Bin still looks full in the icon, but in reality, it's already been emptied.

### Requirements

Recycle Bin should show as empty in the Quick Access once the end user has emptied its contents.

### Files Version

3.7.11.0

### Windows Version

10.0.22631.4249

### User ID

ec92267f-dbf8-4ace-9da4-a2578d4a93cc

### Log File

[debug.log](https://github.com/user-attachments/files/17336026/debug.log)
![Image](https://github.com/user-attachments/assets/b8f7c055-e1c8-421b-b857-7b412d03b044)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #10367. You can check there or click subscribe in the right sidebar for updates.

**Comment by brazenserpent7** [comment]
Appreciate that. Looking forward to the update. Have an epic weekend!

Ben
