### ISSUE TITLE
Bug: Files is not fully working when Memory Integrity is turned on on Windows

### ISSUE THREAD

**Issue by BenCheung0422** [files-community/Files#16343]
### Description

All the pinned entries and entries of Quick access, as well as recently used files do not show up in the app after turning on Memory Integrity. Is that something expected, that the app is incompatible with Memory Integrity?

### Steps To Reproduce

1. Turn on Memory Integrity in Core Isolation in Windows Security
2. Reboot
3. Start Files

### Requirements

All the entries should show as normal.

### Files Version

3.7.11.0

### Windows Version

10.0.22631.4317

### Log File

[debug.log](https://github.com/user-attachments/files/17377889/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, We're tracking this in #15410. You can check there or click subscribe in the right sidebar for updates. Please try the workaround there. Memory integrity shouldn't be related to this issue.

**Comment by BenCheung0422** [comment]
Okay thanks. It happened when I firstly turned on Memory integrity, and at the same time, a gigabyte driver was disabled by Security. The second time I reinstalled gigabyte center and returned on integrity. It does now show up. I doubt the issues here, but I did not restart Files after opening the app and I do have starting on startup on.
