### ISSUE TITLE
Bug: Everytime I open Files, it shows the updating dialogue which is annoying

### ISSUE THREAD

**Issue by SamPat8876** [files-community/Files#16345]
### Description

Remove the updating window which appears when I open FIles

### Steps To Reproduce

-

### Requirements

- e.g. Fix crash that occurs when...
-

### Files Version

3.7.11.0

### Windows Version

23H2

### Log File

[debug.log](https://github.com/user-attachments/files/17378908/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, this is an issue with Windows/App installer please make sure both of them are updated. App installer can be done from the Microsoft store

**Comment by yaira2** [comment]
@SamPat8876 there are two known possibilities that can cause an update prompt:
- Windows is offline or on a metered connection
- The AppInstaller component on your device is an old version, if this is the case, you can find a newer version on the WinGet [repo](https://github.com/microsoft/winget-cli/releases/download/v1.9.1551-preview/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle).

Alliteratively, you can use the Microsoft Store version which doesn't use AppInstaller.
