### ISSUE TITLE
Bug: Low DPI "Add" button

### ISSUE THREAD

**Issue by Lamparter** [files-community/Files#16347]
### Description

This is probably a duplicate issue, but I've noticed that the little icon used for creating a new item is somewhat low-quality and should be better contrast. This is rather specifically in dark mode, but the issue is still apparent in light mode, just not as prevalently.

---

Surely a font icon like `&#xECC8;` would be appropriate here? The contrast of the dark icon and the dark app appearance makes the current icon feel slightly out of place...

![Image](https://github.com/user-attachments/assets/836c6006-0dc3-424b-bccd-0f3549642126)

### Steps To Reproduce

1. Open any view
2. Look at the "Add..." button in the top left corner of the toolbar

### Requirements

- See if this is a DPI scaling issue
- Consider replacing the icon with a different font icon

### Files Version

3.7.7.0

### Windows Version

10.0.22631.4317

### User ID

N/A

### Log File

N/A

**Comment by yaira2** [comment]
Thanks for the report, this is a known issue with WinUI 3 but the good news is a fix is being targeted for 1.7.

https://github.com/microsoft/microsoft-ui-xaml/issues/9338

**Comment by 0x5bfa** [comment]
We still use 1.5 (it is the version of API framework we mainly use called WinAppSdk and we're having an issue with 1.6) and 1.7 will come out by the first half of 2025.

**Comment by yaira2** [comment]
We received word from Microsoft that they had more work than anticipated for WinAppSdk 1.7, and consequently, several tasks have been deprioritized, including the issue with path rendering.
