### ISSUE TITLE
Bug: Files installation failed

### ISSUE THREAD

**Issue by Skrillx13** [files-community/Files#16344]
### Description

I tried to install Files through the classic installer. I visited this GitHub Repo README, and simple clicked on the "Classic Installer" button, which lead me to download `Files.stable.appinstaller`. When attempting to install Files, the installation fails, and gives me the following output:

```
Files_3.7.11.0_x64__1y0xx7n9077q4 because this package depends on a framework that could not be found. Provide the framework "Microsoft.WindowsAppRuntime.1.5" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 5001.178.1908.0, along with this package to install. The frameworks with name "Microsoft.WindowsAppRuntime.1.5" currently installed are: {Microsoft.WindowsAppRuntime.1.5_5001.275.500.0_x86__8wekyb3d8bbwe Microsoft.WindowsAppRuntime.1.5_5001.275.500.0_x64__8wekyb3d8bbwe} (0x80073cf3)
```

### Steps To Reproduce

1. Download the Files app directly from the GitHub Repo by clicking the "Classic Installer" button on the GitHub README.
2. Opened the file, and attempt to install it.
3. It fails and I get an error message.

### Requirements

I expected the installation to happen successfully but it didn't work.

### Files Version

Unsure, 3.7.11.0

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎15/‎10/‎2024 OS build	22000.2538 Experience	Windows Feature Experience Pack 1000.22001.1000.0

### Log File

Unable to access the log files as I cannot even open the Files app, the installation fails. The error message is stated above.

**Comment by yaira2** [comment]
Please try removing existing installations of WinAppSdk from the Settings app. It's possible that one of them is in a bad state.

**Comment by Skrillx13** [comment]
> Please try removing existing installations of WinAppSdk from the Settings app. It's possible that one of them is in a bad state.

How should I do this

**Comment by Josh65-2201** [comment]
If you have already tried the PowerShell method I said above. Open Windows Settings > Apps > Installed apps > Search `Windows app runtime` > Click `...` > Uninstall for all them

**Comment by Skrillx13** [comment]
> If you have already tried the PowerShell method I said above. Open Windows Settings > Apps > Installed apps > Search `Windows app runtime` > Click `...` > Uninstall for all them

ok thanks. I tried that and the files installation succeeded. Thanks for the help.
