### ISSUE TITLE
Feature: Remove expander button calculate folder size setting in settings

### ISSUE THREAD

**Issue by Lamparter** [files-community/Files#16349]
### What feature or improvement do you think would benefit Files?

Currently, the "Calculate folder size" setting in the app settings has an expander to show or hide the info bar that displays a warning.

![Image](https://github.com/user-attachments/assets/5f923773-c0cb-422c-b198-7d8832fce8dd)

This is simply unnecessary in my opinion, as the info bar control is tiny and the user has no interest in closing or opening it.

### Requirements

- Hide expander button calculate folder size setting in settings

### Files Version

3.7.7.0

### Windows Version

10.0.22631.4317

**Comment by 0x5bfa** [comment]
I don't think it does really matter to Files.
We can't show the InfoBar inside the Settings card. AFAIK the WCT one also can't. I really wonder it worth taking a look.

**Comment by yaira2** [comment]
I'm not opposed to hiding the button, but the expander control is the best way to group the banner with the setting.

**Comment by Lamparter** [comment]
Yes I agree.

**Comment by yaira2** [comment]
Let's go ahead with this

**Comment by yaira2** [comment]
@Lamparter to clarify, the expected behavior is to keep the expander but to hide the expand button.

**Comment by yaira2** [comment]
It appears that the entire expander header functions as a single button, and there isn't currently a way to remove the button using a custom style. For now, we'll keep the control as it is. However, we can revisit this issue if we transition to the Toolkit Setting control.

**Comment by yair100** [comment]
Since my last comment, we are now using the Toolkit Setting control. @Lamparter do you know if this is a simple change?

**Comment by Lamparter** [comment]
@yair100 it looks like the WCT expander doesn't expose a property yet that allows hiding the expander without creating a custom style.

**Comment by Lamparter** [comment]
https://github.com/CommunityToolkit/Windows/discussions/835
