### ISSUE TITLE
Code Quality: Introduce `Directory.Packages.props` for better dependency management

### ISSUE THREAD

**Issue by Lamparter** [files-community/Files#16356]
### Description

Similar to #14826, which would allow for seamless property management across projects, but instead this would allow for seamless _package_ management. This would allow for easier ability to update dependencies across projects.

### Concerned code

All projects.

### Gains

- Better ability to update dependencies
- Easier way to see all the dependencies used by the projects and quickly identify each of them
- Offers similar benefits to using `Directory.Build.props`

### Requirements

Very easy:
- Create `Directory.Packages.props` file
- Migrate package references into the file
- Remove version references from project files
- Add package references to project files

**Comment by 0x5bfa** [comment]
We can merge this into https://github.com/files-community/Files/issues/14826

**Comment by Lamparter** [comment]
Umm.. sure...

**Comment by yaira2** [comment]
Great minds think alike
