### ISSUE TITLE
Bug: Lag

### ISSUE THREAD

**Issue by mo-ibrahim17112** [files-community/Files#16357]
### Description

The app is lagging too much, my system is running windows 11 with i5 11400f + GTX 1660s + 16gb Ram

### Steps To Reproduce

Open app
Use app

### Requirements

- e.g. Fix crash that occurs when...
Fix the lag
Add an option to disable animations

### Files Version

3.7.11.0

### Windows Version

10.0.22631.4317

### User ID

17d77b4e-eb5b-4e1c-94fc-29fc683ac441

### Log File

[debug.log](https://github.com/user-attachments/files/17408654/debug.log)

**Comment by 0x5bfa** [comment]
Thanks for the feedback.

> The app is lagging too much

When does the app specifically lag? On startup, on navigating a folder, on operating some files or navigating between tabs?

> Add an option to disable animations

You cannot disable animations application-wide. Whereas, you can disable it system-wide from Windows Settings > Accessibility > Visual effects > Animation effects (toggle off).

**Comment by yaira2** [comment]
Thank you for your feedback. Animations are for the most part already removed from Files, but the few that are there can be disabled by following the steps @0x5bfa mentioned above. We'll also continue working to improve performance in future updates.
