### ISSUE TITLE
Code Quality: Collapse `Files.Package` project

### ISSUE THREAD

**Issue by Lamparter** [files-community/Files#16351]
### Description

It's unnecessary to have a packaging project, since integrating the package into the code project is possible.

### Concerned code

All of [`Files.Package`](https://github.com/files-community/Files/tree/db3491617d7e8d46fef01d798006ab96d3be88e7/src/Files.App%20(Package))

### Gains

- Current method is unnecessary
- Makes more sense for consumer to set startup project as "Files.App"

### Requirements

- Migrate AppX runtime files such as `Package.appxmanifest`/`appxmanifest.xml` to `Files.App`
- Enable MSIX deploy to `Files.App` project (...)

### Comments

Not very high priority obviously...

**Comment by 0x5bfa** [comment]
- Single packaging project doesn't support msixbundle deployment
- Moving the appxmanifest to another place would break the auto update mechanism (im still not sure how).

**Comment by Lamparter** [comment]
> Moving the appxmanifest to another place would break the auto update mechanism (im still not sure how).

Really? Who said that..?

**Comment by yaira2** [comment]
The generated app installer path and file names are based on the packaging project name.

**Comment by Lamparter** [comment]
This should probably be marked as **not planned**.
