### ISSUE TITLE
Code Quality: Rename "Files.App (Package)" to "Files.Package" in the directory tree

### ISSUE THREAD

**Issue by Lamparter** [files-community/Files#16350]
### Description

It's unnecessary and somewhat confusing to have the name "Files.App (Package)" in the directory tree (`src`). It should better be named `Files.Package` to match the configuration manager.

### Concerned code

N/A

### Gains

- Better understanding of folder structure
- Developer will understand the link between "Files.App (Package)" and "Files.Package" as it appears in the editor.

### Requirements

- Rename directory "Files.App (Package)" to "Files.Package"

**Comment by 0x5bfa** [comment]
- moving appxmanifest to another place would break the auto update

**Comment by 0x5bfa** [comment]
To rename, Files.App.Package makes more sense but we'd not rename or move until msixbundle is supported in the single packing project.

**Comment by Lamparter** [comment]
> To rename, Files.App.Package makes more sense but we'd not rename or move until msixbundle is supported in the single packing project.

Yes you're right, like in FluentHub. However, that's how it currently is (Files.Package in Configuration Manager)

**Comment by yaira2** [comment]
https://github.com/files-community/Files/pull/12475#issuecomment-1566150396

**Comment by Lamparter** [comment]
It's possible to publish a package from a single package project though, right?

**Comment by yaira2** [comment]
Bundles aren't supported yet
