### ISSUE TITLE
Bug: Photos/images when opened in windows photos app cant scroll through

### ISSUE THREAD

**Issue by wilig123** [files-community/Files#16359]
### Description

Hi, I seem to have an issue when I open image files from the Files app in Windows Photos (or Photos legacy). It does not let you scroll through the photos using arrow keys, mouse wheel etc - you're stuck on the photo you open. If you open a photo from the native windows file explorer into these apps I am able to, so assume there is an issue with the way Files is opening images into the viewer apps.

### Steps To Reproduce

1. Using Files app, go to a folder that has multiple image files in it
2. open an image into windows Photos (or Photos Legacy)
3. Attempt to scroll through to other images in the Photos app

### Requirements

Should be able to scroll through images in Photos when opened from Files.

### Files Version

3.7.11.0

### Windows Version

10.0.22631.4317

### User ID

0d6e5db5-727f-4c2d-b0a0-eea356ef329a

### Log File

[debug.log](https://github.com/user-attachments/files/17423471/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #15409. You can check there or click subscribe in the right sidebar for updates.
