### ISSUE TITLE
Bug: Close current tabs before closing the window

### ISSUE THREAD

**Issue by kryzet** [files-community/Files#16367]
### Description

Whenever I open Files after closing it, the screen that was previously open when I closed it appears briefly before the Home screen is loaded.

### Steps To Reproduce

1. Open Files.
2. Navigate to a non-Home screen, such as a drive partition (C, D, etc.) or folder.
3. Close Files.
4. Open Files again.

### Requirements

- Flush GPU memory associated with a Files window when closing it.
- Automatically navigate to the Home screen (or any other startup screen that has been configured) before closing the current window.

### Files Version

3.7.11.0

### Windows Version

10.0.22631.4317

**Comment by Josh65-2201** [comment]
Thanks for the report, Can you send a screen recording of this.

**Comment by kryzet** [comment]
> This sounds like you have the "Startup Settings" set to "Continue where you left off" instead of "Open a new tab"? ![Image](https://github.com/user-attachments/assets/b06c9ef9-6336-4097-908c-b037553053e8)

![Image](https://github.com/user-attachments/assets/1b18aeeb-2c77-4319-aaca-b72dc05004b0)
 
> Also, you may want to remove the log file as it has you email in there, which you might not want publicly visible (This is from your Google Driver and One Drive providers)

Thank you very much! I didn't realize that.

**Comment by kryzet** [comment]
> Thanks for the report, Can you send a screen recording of this.

The problem is, if I make a recording of this it will likely reveal a folder with files I have in it, and I'm not sure how to redact that information from the video. I tried setting the startup directory to a Windows library and reproducing the issue, but it didn't occur.

**Comment by yaira2** [comment]
What option do you have set for the startup setting?

**Comment by kryzet** [comment]
I already shared a screenshot of the current startup setting. I tried to set it to open a specific page (a Windows Library) and then attempted to reproduce the issue, but that was in vain.

**Comment by yaira2** [comment]
My apologies, I missed the earlier comments. Is everything good now?

**Comment by kryzet** [comment]
It's fine. We all miss things from time to time. As for your question, no; the issue persists. It's just that I can't record a video to demonstrate it.

**Comment by yaira2** [comment]
Is this correct?
1. Set startup setting to "Open new tab".
2. Navigate to a folder (eg. `Downloads`).
3. Close the window (with the option to keep Files running in the background enabled).
4. Open Files and the previous location is briefly shown before the app navigates to the home page.

**Comment by kryzet** [comment]
Yes.

**Comment by yaira2** [comment]
@hishitetsu this seems to occur because the existing tab list is only cleared when resuming a session. Do you recall if there was a limitation that caused us to write the logic this way?

**Comment by hishitetsu** [comment]
I believe the tab list is cleared before sleep. But subsequent UI updates are asynchronous, so I think this problem is caused by the UI update not completing before sleep.
