### ISSUE TITLE
Feature: Add github action workflow to update winget-pkg files on every release

### ISSUE THREAD

**Issue by jo-chemla** [files-community/Files#16374]
### What feature or improvement do you think would benefit Files?

At the moment, the `FilesCommunity.Files` package has been removed from microsoft/winget-pkgs. Looks like the latest available version was [3.6.0.0](https://github.com/microsoft/winget-pkgs/pull/150504) on the linked PR. Is this because of a bug during validation of the package as seem to be mentioned in the PR listed, or becasue there is not Github Action pushing new releases to the repo? 
Two linked closed issues here: 
 - https://github.com/files-community/Files/issues/12099
 - https://github.com/files-community/Files/issues/15973

### Requirements

Have the `FilesCommunity.Files` available so user can install Files via `winget install files` or `winget install FilesCommunity.Files`

### Files Version

3.6.0.0

### Windows Version

10 + 11

**Comment by Josh65-2201** [comment]
Thanks for the feedback, The package would have to be added by the Winget team. The one working on it before stop and the PR was closed for inactivity https://github.com/microsoft/winget-pkgs/pull/150504#issuecomment-2273691802, last issue they had with validation was on there side too. A GitHub action isn't needed to add programs.

**Comment by Josh65-2201** [comment]
I have made a new PR in hopes that it get added https://github.com/microsoft/winget-pkgs/pull/184766

**Comment by jo-chemla** [comment]
Thanks for doing the new PR, hope it gets merged by winget team!

Yes anyone can indeed submit PRs to have packages added - as long as they follow their recommendations and the submitted manifests pass testing. The github action is a nice way to avoid having a middleman required to push new package releases to winget-pkgs. 

There are a minimal set of requirements for the automated way to work smoothly which are: 
 - there has to be at least one version of the package with the given identifier - eg FilesCommunity.Files - before the winget-releaser action can push new releases. 
 - the user doing the pushes (can belong to the repository) has to have a fork of [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under the same account/organization as the project's repository. If you are forking winget-pkgs on a different account (e.g. bot/personal account), you can use the fork-user input to specify the username of the account where the fork is present.
 - a github classic Personal Access Token (PAT) with public_repo scope has to be created and this token should be added as a repository secret by creating a [new repo secret](https://github.com/Jacalz/rymdport/settings/secrets/actions/new) with name WINGET_ACC_TOKEN and value the token

**Comment by jo-chemla** [comment]
Glad to see that `Files 3.7.11.0` has finally made it to the winget package repository! Also saw you used `wingetcreate` to push `FilesPreview` https://github.com/microsoft/winget-pkgs/pull/191569

To automate the release on every github release of Files, if the builds were pushed to this repo releases, then the Github Action workflow file could look like the following. Note at the moment, the build files are stored at a cdn https://cdn.files.community/files/preview/Files.Package_3.7.12.0_Preview_Test/Files.Package_3.7.12.0_x64_arm64_Preview.msixbundle. 

But first the build or CI action would have to push the msixbundle files to github releases. 

```yaml
name: Publish to WinGet
on:
  release:
    types: [ released ]
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@v2
        with:
          identifier: FilesCommunity.Files
          token: ${{ secrets.WINGET_TOKEN }}
          installers-regex: 'Files\.Package\_\w*\_x64\w*.msixbundle$' 
```

**Comment by Josh65-2201** [comment]
While they will have the VClib validation issue a bot would make updating a lot easier still and should still be looked into. Right now for manual we have to 
1. Submit a PR removing the old version
2. Update the folder version and files info
3. Submit a PR with the new version

**Comment by jo-chemla** [comment]
Thanks for the replies, understood.
You don't necessarily have to remove previous Files version before pushing the latest release to winget-pkgs. There are also some helper utilities like [komac](https://github.com/russellbanks/Komac) to handle package manifest creation and updates

**Comment by 0x5bfa** [comment]
That workflow promising. Once their problem fixed we may want to take a look.

Btw, @Josh65-2201 we probably should improve the license url in the next update as it indicates to the github repo's main page.

**Comment by jo-chemla** [comment]
I think the VCLib depency issue has been resolved - deps can now be passed to pakage manifests, and the recent PRs I did to integrate new packages to winget mostly all got merged, and I did not stumble upon this issue anymore. 

Are you interested in building an automated github action workflow to push every new Files release to winget-pkgs? 

Note it would be probably easier for that workflow if the Files builds (msix x64) would be published as github release as well.

**Comment by Josh65-2201** [comment]
As of 3 weeks ago it isn't https://github.com/microsoft/winget-pkgs/pull/294440#issuecomment-3379334702 , the issue isn't that VClibs couldn't be put in the package manifest, it isn't up to date on WinGet and fails the automatic pipeline they have

**Comment by jo-chemla** [comment]
Oops thanks for the heads-up, you guys live in the future! Understood!
