### ISSUE TITLE
Bug: Multiple rename seems to  randomly reorder file names

### ISSUE THREAD

**Issue by cliffmcl** [files-community/Files#16376]
### Description

The multiple rename is a big step forward, however it currently seems to be somewhat random in how it numbers the renamed files. If I have a folder with 10 files named 1 to 10 (just numbers and sorted on Name, and I highlight them all and press F2 and renames the photos the appended numbers bear no apparent relation to the original file names. However in Windows explorer, I if I select the last file and shift select the first and rename, they rename numerically

### Steps To Reproduce

Select first or last file 
Shift select last or first file or Ctrl A
Press F2 and add a name
Files are not renamed in order

### Requirements

Files should be renamed in the sequence they were ordered

### Files Version

3.7.11.0

### Windows Version

10.0.22631.4317

### User ID

fc4f5a14-58db-4b8c-b104-431f0f836b14

### Log File

[debug.log](https://github.com/user-attachments/files/17471290/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report.
