### ISSUE TITLE
Bug: Error in labels

### ISSUE THREAD

**Issue by DragonrisesRRR** [files-community/Files#16372]
### Description

![Image](https://github.com/user-attachments/assets/c9425938-af72-437d-a98e-93cd2fa61dda)
As shown in the figure, when the drive is NTFS, the label function still cannot be used normally.

### Steps To Reproduce

I apply it to folders.
I'm going to go to labels.
Appears errors.

### Requirements

Fix in the application of labels

### Files Version

3.7.11.0

### Windows Version

10.0.22635.4225

### User ID

cc6da31c-d00a-4ae1-9f2a-f09029a370a3

### Log File

[debug.log](https://github.com/user-attachments/files/17451303/debug.log)

**Comment by DragonrisesRRR** [comment]
In order to better explain the problem, I would like to add some information. This problem occurs in folders such as Program Files and Users, and any files in these folders cannot be tagged. I can confirm that my file system is NTFS.![Image](https://github.com/user-attachments/assets/0fdacb7e-273c-4348-8208-90321b1ebbcd)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in https://github.com/files-community/Files/issues/15272. You can check there or click subscribe in the right sidebar for updates.

Right now you can't add them to folder that need admin to edit

**Comment by yaira2** [comment]
This error message is sometimes displayed when there is an issue applying the label. The issue @Josh65-2201 linked will hopefully take care of this problem as well.
