### ISSUE TITLE
Bug: No option to disable splash screen

### ISSUE THREAD

**Issue by jay-ramani** [files-community/Files#16379]
### Description

There's no option to disable the splash screen. This should ideally be configurable.

Files version: 3.7.11.0
OS version: Windows 11 23H2 (Build 22631.4317)

Cheers.

### Steps To Reproduce

Execute the Files application

### Requirements

There should be an option to disable the splash screen. This is instead forced upon the user.

### Files Version

3.7.11.0

### Windows Version

23H2 Build 22631.4317

### Log File

No log file required

**Comment by Josh65-2201** [comment]
Thanks for the feedback, This isn't a bug as there splash screen is there while Files is loading. There is no reason to have this turned off. Startup performance will be improved with future updates.

**Comment by jay-ramani** [comment]
How about having the option to turning off the splash screen as an ehnacement?

**Comment by 0x5bfa** [comment]
Disabling splash screen enhances nothing. The window is still black or not shown yet. Btw, we have a plan to boost the startup (x2 at maximum) and hopefully it reduces wasting time.

**Comment by jay-ramani** [comment]
> Disabling splash screen enhances nothing. The window is still black or not shown yet. Btw, we have a plan to boost the startup (x2 at maximum) and hopefully it reduces wasting time.

It's not just about enhancement. How about a user not wanting the splash screen being displayed?

**Comment by 0x5bfa** [comment]
Can you elaborate why users don't want the app to display the splash screen? Splash screen is enabled by default on UWP apps such as Microsoft Store, Windows Settings, Clock, this is because developers and designers know this reduces user's frustration with waiting contents are fully loaded (prevents users from thinking they really clicked on the app icon and trying to click again to check). Splash screen has loaded contents and a progress ring that indicates users that contents are being loaded.
IMO, it's better to put our resources onto boosting the startup. fyi @yaira2

**Comment by 0x5bfa** [comment]
> the user not wanting the splash screen displayed.

Can you elaborate the reason why.

**Comment by yaira2** [comment]
To clarify, the splash screen is not just for decoration. It serves as a loading screen for the app, giving users visual feedback that the app is in the process of starting up. As startup times improve, the duration of the splash screen will naturally decrease.

We're happy to consider settings if there is a valid use case, but the alternative in this scenario is to display nothing until the app is done loading.

**Comment by jay-ramani** [comment]
> We're happy to consider settings if there is a valid use case, but the alternative in this scenario is to display nothing until the app is done loading (depending on the device, this can be a few seconds on the initial start).

So are you saying the user not wanting to see the splash screen as an option is an invalid use case?

**Comment by yaira2** [comment]
We'd like to gather more feedback from users before making a final decision. That said, it would be helpful if you could explain how hiding the loading screen would improve your workflow. From my perspective (though others may have different opinions), not displaying feedback while the app is launching could be confusing. Users might think the app has failed to open and click the icon again, potentially resulting in multiple instances opening.
