### ISSUE TITLE
Feature: Add support for pasting items as shortcut

### ISSUE THREAD

**Issue by Steperman5692** [files-community/Files#16371]
### What feature or improvement do you think would benefit Files?

> First improvement: Paste shortcut

In File Explorer, when you copy something, you you have two option to paste it, either "Paste" or "Paste Shortcut" which basically paste but its a shortcut to original file which look something like this:
![Image](https://github.com/user-attachments/assets/13d6b9d5-de2b-4c37-ac16-667d2f218c4a)

So I was wondering if we could add the "Paste Shortcut" option in Files context menu specifically in one of these places:
![Image](https://github.com/user-attachments/assets/882b7303-78bd-4a7f-b966-6d53e8754d45)

### Requirements

1. Add a "Paste shortcut" action
2. Add an option to the Files context menu.

### Files Version

3.7.11.0

### Windows Version

10.0.22631.4317

**Comment by yaira2** [comment]
Thank you for your feedback. I've edited the proposal to include the first request, can you please open a second feedback item for the other request?

**Comment by Steperman5692** [comment]
Of course, here it is https://github.com/files-community/Files/issues/16387.

**Comment by yaira2** [comment]
Thank you, I added both items to our todo list.

**Comment by Steperman5692** [comment]
You're welcome :)
