### ISSUE TITLE
Bug: Unexpected application shutdown

### ISSUE THREAD

**Issue by AndresMarulanda10** [files-community/Files#16375]
### Description

What happens is that when opening the application it takes a long time to load, besides that, when moving files or doing something directly from the application, the application closes completely and you have to reopen it.

### Steps To Reproduce

1. Opening the program
2. The program freezes or takes a long time to load
3. Do any action such as copy, paste, move, cut, rename, etc. At any moment the program closes

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.7.11.0

### Windows Version

10.0.22631.4317

### User ID

6b9849b1-c1f8-41ce-af5d-e46ab2c0d173

### Log File

[debug.log](https://github.com/user-attachments/files/17464116/debug.log)

**Comment by VDPR** [comment]
I am also experiencing the exact same issue.
Files Version
3.7.11.0

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue 3.8.0.0. https://files.community/download

**Comment by Josh65-2201** [comment]
Thanks for the information, We're tracking info pane crash in #16226. You can check there or click subscribe in the right sidebar for updates.
