### ISSUE TITLE
Bug: Selection is cleared when canceling drag & drop

### ISSUE THREAD

**Issue by Laesx** [files-community/Files#16388]
### Description

When you make a selection and drag it, the selection gets cleared, I think the current selection should persistent be prioritized above all (this is normal explorer behavior).

### Steps To Reproduce

1. Select one or multiple files
2. Start dragging and let go in the same directory to cancel operation
3. Selection gets cleared

### Requirements

- Selection remains when dragging files

### Files Version

3.7.11.0

### Windows Version

10.0.22631.4391

### Log File

[debug.log](https://github.com/user-attachments/files/17533506/debug.log)

**Comment by Laesx** [comment]
I just noticed that it's similar to #2856 but that one doesn't mention the selection clearing when dragging the files

**Comment by yaira2** [comment]
@Laesx I tried dragging files to another location and the dropped items were selected. Are you seeing a different behavior?

**Comment by Laesx** [comment]
> [@Laesx](https://github.com/Laesx) I tried dragging files to another location and the dropped items were selected. Are you seeing a different behavior?

No, that works fine, what I mean is in the same folder containing the selected items, when you start the drag all of them deselect.

Video: https://github.com/user-attachments/assets/52064691-7d5b-4bae-a339-1d504f53a03b
