### ISSUE TITLE
Feature: Please add a function to make the settings window draggable, because I want to preview the switched theme

### ISSUE THREAD

**Issue by Super1Windcloud** [files-community/Files#16386]
### What feature or improvement do you think would benefit Files?

 #   Please add a function to make the settings window draggable, because I want to preview the switched theme

### Requirements

Feature: Please add a function to make the settings window draggable, because I want to preview the switched theme

### Files Version

latest 

### Windows Version

win11

**Comment by yaira2** [comment]
While we haven't announced our plans publicly yet, we’re working on revamping the settings to appear as a tab, similar to the settings in Microsoft Edge. Although we don’t have an ETA at this time, we believe this change will address the core reason behind your request.
