### ISSUE TITLE
Bug: Log File Collects PII

### ISSUE THREAD

**Issue by kryzet** [files-community/Files#16383]
### Description

When uploading the log file for a bug report, personally identifiable information (PII) is included in the log, such as email addresses (and possibly full names). I did not thoroughly investigate the issue.

### Steps To Reproduce

Open a log file from one of the [GitHub Issues](https://github.com/files-community/Files/issues).

### Requirements

A good solution might be to:
- Redact log lines that include PII
- Entirely avoid logging events that might involve PII

### Files Version

3.7.11.0

### Windows Version

10.0.22631.4317

### Log File

[debug.log](https://github.com/user-attachments/files/17508824/debug.log)

**Comment by kryzet** [comment]
If you check the log file, you will find redacted lines that included my email address. You will also find lines that were redacted despite not including personal information, but that were related to the other lines that were redacted. Every line was either left unmodified or redacted with a comment explaining what information was stored on that line.

**Comment by yaira2** [comment]
In line with our [privacy policy](https://github.com/files-community/Files/blob/main/.github/PRIVACY.md?form=MG0AV3&form=MG0AV3#information-we-collect), only non-identifiable information is uploaded to Sentry. The local log file you're referring to generally doesn't contain private information, although it does log drive paths for fixed and cloud drives. This log file is never shared with us, but it can be incredibly helpful for debugging issues when users choose to upload it to GitHub.

If you find differently, please let us know. However, it's most likely that the email address you found in the log file is the name for a Google Drive or iCloud account listed in the sidebar.

**Comment by kryzet** [comment]
> If you find differently, please let us know. However, it's most likely that the email address you found in the log file is the name for a Google Drive or iCloud account listed in the sidebar.

Isn't that problematic?

**Comment by kryzet** [comment]
You could redact _just_ the email addresses and leave the rest. If you need to distinguish between multiple cloud provider drives, you can assign every email address an anonymous identifier, such as `<email #>`.
