### ISSUE TITLE
Feature: Better files search?

### ISSUE THREAD

**Issue by ThakurIsFast** [files-community/Files#16389]
### What feature or improvement do you think would benefit Files?

Searching for files is not good. because, if you go to a drive [C:] in windows files explorer and search for any file it will search inside every folder but in FILES it only searches for folders in drive not files in folders

Note: I am new to FILES, I searched every setting, but I can't fix it I don't know if there is already a setting 
if there is any, please tell me

### Requirements

- Search feature is not good
- only search for folders
- Didn't search files inside the folders

### Files Version

3.7.11.0

### Windows Version

10.0.19045.5011

### Comments

![Image](https://github.com/user-attachments/assets/3455fc18-cd8d-4674-8def-be7b6f64c0e9)   (FILES)

![Image](https://github.com/user-attachments/assets/d639f5cb-4f4b-4c76-90eb-0d7f306adbf2)     (Windows File Explorer)

**Comment by Josh65-2201** [comment]
Thanks for the report, It look like you didn't press enter, please try it

**Comment by ThakurIsFast** [comment]
I clicked 😃... but nothing happeed 😔

**Comment by Josh65-2201** [comment]
Clicked what? If you mean you pressed enter did you have the search box input selected first? When it searching a loading icon will also be in the tab bar

**Comment by ThakurIsFast** [comment]
I think it started searching after clicking enter but 
here is a new suggestion:- search speed is very very slow,can it be fixed?

**Comment by Josh65-2201** [comment]
It the same system as Windows File Explorer. Faster and better version is being tracked in #5845. You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
Typing in the search box without pressing Enter will quickly filter the current directory based on file names, addressing most use cases. Pressing the Enter key will search using the Windows search index, this takes longer but includes results from subfolders. I agree that the UI could be improved to make this distinction clearer, but either way, I hope this explanation helps clear up some confusion.
