### ISSUE TITLE
Bug: Follow OS specified in the registry

### ISSUE THREAD

**Issue by jay-ramani** [files-community/Files#16380]
### Description

I have set an alternate font OS-wide (using [Winaero Tweaker](https://winaerotweaker.com/)). However, Files does not obey the global setting. Every other application obeys the change.

### Steps To Reproduce

Execute the Files application

### Requirements

Files should obey the font specified OS wide in the registry

### Files Version

3.7.11.0

### Windows Version

23H2 Build 22631.4317

### Log File

![Image](https://github.com/user-attachments/assets/ff71cfb0-c797-41c9-92b5-a9893a4752a7)

**Comment by Josh65-2201** [comment]
Thanks for the report, You can change the font in Files json. https://files.community/docs/customize-settings/appearance#:~:text=%2300000000-,Custom%20fonts,-There%20isn%E2%80%99t%20an

**Comment by jay-ramani** [comment]
Thanks for the quick response. However, for an end user, if not respecting the OS-wide font, this should be configurable through the application's interface for settings, instead of having to edit the json file.

**Comment by jay-ramani** [comment]
> Thanks for the report, You can change the font in Files json. https://files.community/docs/customize-settings/appearance#:~:text=%2300000000-,Custom%20fonts,-There%20isn%E2%80%99t%20an Instructions for editing the file are above

Thanks for the quick response.

Btw, changing the font via this option to "Ubuntu Condensed" (part of the [Ubuntu font family](https://assets.ubuntu.com/v1/0cef8205-ubuntu-font-family-0.83.zip) installed into %WINDIR%\fonts) does not work. Where is the application picking up the fonts to select from?

Also, for an end user, if not respecting the OS-wide font, this should be configurable through the application's interface for settings, instead of having to edit the json file.

**Comment by 0x5bfa** [comment]
Setting other fonts than Segoe UI as a system fonts isn't what Windows itself supports its UI. Likewise, we don't have to provide a way to set fonts, plus some places don't respect that font setting because of the framework issue.

> Btw, changing the font via this option to "Ubuntu Condensed" (part of the [Ubuntu font family](https://assets.ubuntu.com/v1/0cef8205-ubuntu-font-family-0.83.zip) installed into %WINDIR%\fonts) does not work.

We just set FontFamily string property of all TextBlock styles. Have you set the correct name? It's what Font Viewer shows as Font name.

**Comment by jay-ramani** [comment]
> We just set FontFamily string property of all TextBlock styles. Have you set the correct name? It's what Font Viewer shows as Font name.

I have set the correct font name (per what Font Viewer shows).

**Comment by yaira2** [comment]
Winareo would likely need to add support for WinUI applications to make this work. It's worth noting that most customization apps in Windows tend to struggle with UWP and WinUI so I'm not sure if this is possible.
