### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by oblipix** [files-community/Files#16385]
### Description

Hi, I installed it and the main one is not showing up for me.

### Steps To Reproduce

![Image](https://github.com/user-attachments/assets/a1721f83-7218-472e-8bf2-e120402b5bb9)

### Requirements

the main name is not appearing

### Files Version

 v3.7.11

### Windows Version

11

### Log File

the main name is not appearing

**Comment by Josh65-2201** [comment]
Thanks for the report. you will need to
- Give more details on what isn't working
- Provide actual steps to reproduce your issue
- Upload (Do not copy and paste content) the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.

**Comment by Lamparter** [comment]
@oblipix do you mean the home page?

**Comment by oblipix** [comment]
yes, the branch indicator did not appear for me

**Comment by Josh65-2201** [comment]
If your talking about Git features you need to be in a git repository folder, which you aren't in the screenshot

**Comment by oblipix** [comment]
I was in a folder that I had cloned from github...

**Comment by oblipix** [comment]
Is there any way I can replace the default Windows folders with this one?

**Comment by oblipix** [comment]
thanks <3
