### ISSUE TITLE
Feature: Naming a shortcut while creating it

### ISSUE THREAD

**Issue by Steperman5692** [files-community/Files#16387]
### What feature or improvement do you think would benefit Files?

In File Explorer, when you create a shortcut after you put the path to the shortcut; File Explorer will next prompt you to name the shortcut, it look something like this:
![Image](https://github.com/user-attachments/assets/e4bfe94e-2a9c-4eac-8d7d-42d8fbb384ff)

So I was wondering if we can add this to Files, it will make creating and naming shortcuts much easier & more user-friendly.

### Requirements

- Naming a shortcut while creating it.

### Files Version

3.7.11.0

### Windows Version

10.0.22631.4391

**Comment by yaira2** [comment]
Thank you for opening this request

**Comment by ferrariofilippo** [comment]
What design are we gonna use? A two-step modal (Explorer-like) or something else?
If we decide to use a one-step modal, should the name box be always visible or should it behave like in the video below

https://github.com/user-attachments/assets/8fb94a8d-ee92-4dbe-a345-19afb0711657

**Comment by yaira2** [comment]
1. We might as well have it on the same page.
2. The text box should be displayed by default. However, we may need to experiment with auto-filling the name when the path changes.

**Comment by ferrariofilippo** [comment]
> 2. The text box should be displayed by default. However, we may need to experiment with auto-filling the name when the path changes.

I guess we have two ways to go:
- always change the name when a new destination is selected
- change the name only when it has not been edited by the user

Also, should we allow the user to set a name only if the destination is valid?

**Comment by yaira2** [comment]
> always change the name when a new destination is selected

This sounds reasonable

> change the name only when it has not been edited by the user

Or alternatively, we only auto fill the name if the field is empty.

> Also, should we allow the user to set a name only if the destination is valid?

The 'create' button will be disabled in that case so I don't think this is necessary.

**Comment by yaira2** [comment]
Is there a benefit of a two-step model? Generally, it adds more steps for users, while having everything on the same page allows users to see all available options in advance.

**Comment by Steperman5692** [comment]
True, but generally people that use Files are people that used File Explorer in the past. It just a matter of familiarity.

**Comment by yaira2** [comment]
This feature will be included in the next update

**Comment by Steperman5692** [comment]
Thanks! :)
