### ISSUE TITLE
Bug: 性能太差

### ISSUE THREAD

**Issue by Jiang10086** [files-community/Files#16384]
### Description

好看是好看，但性能太差，我没有把Shell右键菜单收到子栏，设置为点击右键就全部展示，然后我每次右键都得等四秒⸺毫不夸张。最新预览版和正式版都试过了，都这样

### Steps To Reproduce

1. 右键点击任何文件或文件夹
2. 等四秒才能展示全部右键菜单

### Requirements

 秒显示完

### Files Version

3.7.11.0

### Windows Version

10.0.26100.2033

### User ID

caa6a700-af5f-412a-b115-021842928a4f

### Log File

[debug.log](https://github.com/user-attachments/files/17515196/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, we're working on improving performance and will continue releasing updates with this goal in mind.

Depending on the number of shell extensions, the context menu may take longer to load. We strongly recommend enabling the setting to "Move shell extensions into a sub menu". This enables the best performance and will hopefully improve your experience.![Image](https://github.com/user-attachments/assets/1558b421-1cdb-455f-a0e8-795ba12ae464)
