### ISSUE TITLE
Feature: The sidebar hopes to add a file tree function

### ISSUE THREAD

**Issue by Nashiyi** [files-community/Files#16394]
### What feature or improvement do you think would benefit Files?

I hope to add a file tree function to the sidebar. The first picture is the system default file explorer. The second picture is of Files. I hope that I can expand folders and subfolders in the sidebar, so that I can directly right-click to open some of my commonly used folders.
![Image](https://github.com/user-attachments/assets/e1c1da25-1efe-4f25-b002-8a801c2647dc)
![Image](https://github.com/user-attachments/assets/fe0dc5d2-4251-4a64-b66a-d6977586facc)

### Requirements

- You can expand and collapse cloud disks and pinned items in the sidebar.

### Files Version

3.7.11.0

### Windows Version

10.0.22631.4317

**Comment by yair100** [comment]
@Nashiyi Tree View is currently available in preview https://files.community/download. It will be included in the next stable release.
