### ISSUE TITLE
Bug: Crashes in Column View with Right-Click

### ISSUE THREAD

**Issue by icefiore** [files-community/Files#16397]
### Description

I'm experiencing issues with the current version of Files App (which I just downloaded onto my computer with Windows11Pro) in Column View mode, where the app either crashes or behaves unexpectedly during navigation. Here are the details:

When using the column view, right-clicking on items in the rightmost column causes the cursor to momentarily change to a loading or window-resizing symbol. Shortly after, the application unexpectedly crashes.

### Steps To Reproduce

1. Open Files App and switch to Column View.
2. Navigate to the rightmost column containing child files.
3. Right-click on one of the files.

### Requirements

When using the column view, right-clicking on items in the rightmost column causes the cursor to momentarily change to a loading or window-resizing symbol. Shortly after, the application unexpectedly crashes.

### Files Version

3.7.11.0

### Windows Version

Edizione	Windows 11 Pro Versione	24H2 Data installazione:	‎18/‎10/‎2024 Build sistema operativo	26100.2033 Esperienza	Windows Feature Experience Pack 1000.26100.23.0

### Log File

the problem is again at 28/10/2024 13:55
[debug.log](https://github.com/user-attachments/files/17542789/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #16193. You can check there or click subscribe in the right sidebar for updates.
