### ISSUE TITLE
Bug: Pinned network drives have empty name when device is offline

### ISSUE THREAD

**Issue by BiosNod** [files-community/Files#16395]
### Description

Files app vs classic win10 explorer:
![Image](https://github.com/user-attachments/assets/9c51d4cf-e179-4882-b0d7-65e1a419ee90)

### Steps To Reproduce

1. Just pin some network drives in quick access (in classic Win10 explorer just drag and drop to pin)
2. Turn off devices with this drives
3. Go to Files app and see empty names (for example GIGABYTE-B85 is offline, MSI-B450 online)

### Requirements

- See full names even if offline

### Files Version

3.7.11.0

### Windows Version

10.0.19045.5011

### Log File

[debug.log](https://github.com/user-attachments/files/17541522/debug.log)
Guess debug log is useless

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #13880. You can check there or click subscribe in the right sidebar for updates.
