### ISSUE TITLE
Feature: Reordering Columns

### ISSUE THREAD

**Issue by valdeirsoares** [files-community/Files#16401]
### What feature or improvement do you think would benefit Files?

It could have the option to reorder the columns in details mode, the way the user wants, either directly in the Explorer or in the settings, making the application even more customizable, attracting more users to it.

### Requirements

- This proposal will enable better customization of the system.

### Files Version

3.7.11.0

### Windows Version

10.0.26120.2200

**Comment by 0x5bfa** [comment]
Thank you for the feedback.

We're tracking this on in #8385. To get notified, click Subscribe on the right pane in that issue page.
