### ISSUE TITLE
Bug: Right Arrow Key causing lockout

### ISSUE THREAD

**Issue by mathewdyck** [files-community/Files#16407]
### Description

When navigating in Columns view, pressing the right arrow key to navigate into a folder causes the app to lock. No arrow keys will work and no keyboard shortcuts will function until the user uses the mouse cursor to select something within the app.

*Issue is intermittent. 9/10 will occur.

### Steps To Reproduce

1. Open Files in Columns view.
2. Select anything in your directory then navigate to a folder.
3. Right the right arrow key to move into the open folder.

### Requirements

Fix so that arrows work to navigate back and forth between folders and subfolders.

### Files Version

3.7.11.0

### Windows Version

10.0.22631.4391

### User ID

741f6fcb-1a57-4fce-9859-3b22b27b74c9

### Log File

[debug.log](https://github.com/user-attachments/files/17564168/debug.log)

**Comment by mathewdyck** [comment]
It is similar, but the issue I am having does not relate to the Tabs Action
menu.

**Comment by Josh65-2201** [comment]
Tab action menu is just where the keyboard focus is going for them when using the right arrow, is it staying on the folder in the column for you?

**Comment by mathewdyck** [comment]
No, the focus stops.
Nothing is focused.

**Comment by Josh65-2201** [comment]
This will likely be fixed with that one.

**Comment by mathewdyck** [comment]
Issue persists in version 3.8.0.0
