### ISSUE TITLE
Right-click menu on homepage

### ISSUE THREAD

**Issue by zsr-lukezhang** [files-community/Files#16403]
When you maximized the Files window and then right-click the item on the right side of the page of the homepage, you will get a menu leaked outside the screen - I can't see it.
Just like this:
![Image](https://github.com/user-attachments/assets/ca1d795e-8653-466e-a76e-5cdddf5bf83d)
This doesn't happen on any other pages.
Please fix it - although I don't think it's really necessary.
Thanks!

**Comment by Josh65-2201** [comment]
Please follow issues templates

**Comment by zsr-lukezhang** [comment]
> Please follow issues templates

Oh GitHub doesn't give me a template just now. I think there's something wrong with my network since I'm in China mainland🙃.
I'm so sorry.

**Comment by Josh65-2201** [comment]
Does https://github.com/files-community/Files/issues/new/choose not work for you?

**Comment by 0x5bfa** [comment]
Btw I think this issue comes from the underlying UI framework and we have nothing we can do.

**Comment by zsr-lukezhang** [comment]
> Does https://github.com/files-community/Files/issues/new/choose not work for you?

Now it works.

**Comment by zsr-lukezhang** [comment]
> Now it works.

I didn't use that link https://github.com/files-community/Files/issues/new/choose but just clicking on "New Issue".
GitHub then give me a false link github.com/issues/new. I changed the link into github.com/files-community/Files/issues/new/
