### ISSUE TITLE
Feature: Folder Settings

### ISSUE THREAD

**Issue by valdeirsoares** [files-community/Files#16402]
### What feature or improvement do you think would benefit Files?

You could have the option to configure multiple folder groupings, leaving the choice of which groupings to open at the beginning of the system. Thus, it could have several different selections of folders, where the user could configure them by context.

For example: you could have a folder grouping with the name "Development", where you would open the folders configured in this grouping and you could have another grouping, with the name of "Music" or "Videos", which would open the folders configured for this grouping, showing the media folders configured by the user.

### Requirements

This proposal would increase the customization of the system and the use according to the context that the user is going to use at the moment.

### Files Version

3.7.11.0

### Windows Version

10.0.26120.2200

**Comment by yaira2** [comment]
Are you refering to [tags](https://files.community/docs/features/tags)?

**Comment by valdeirsoares** [comment]
No, I'm referring to the folders and tabs opened when starting the application, as today we can only configure a group of folders to open and I suggest having folder groups when configuring and starting the application.

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by yaira2** [comment]
Thank you for clarifying, can you confirm if this is the same as #11900?

**Comment by valdeirsoares** [comment]
Yes, mine is a simple version compared to the suggestion in this Issue.

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by yaira2** [comment]
We will keep tracking and planning this feature in #11900. The concept is still in its early stages, and we have a few different directions we can take. Your input is valuable, so please share your thoughts on that issue.
