### ISSUE TITLE
Bug: Right-click menu on homepage

### ISSUE THREAD

**Issue by zsr-lukezhang** [files-community/Files#16404]
### Description

When you maximized the Files window and then right-click the item on the right side of the page of the homepage, you will get a menu leaked outside the screen - I can't see it.
Just like this:
![Image](https://github.com/user-attachments/assets/ca1d795e-8653-466e-a76e-5cdddf5bf83d)
This doesn't happen on any other pages.
Please fix it - although I don't think it's really necessary.
Thanks!

### Steps To Reproduce

1. Click on the navigation bar on the left to open Homepage.
2. Maximize the Files window.
3. Right-click an item on the right side like this:![Image](https://github.com/user-attachments/assets/8d235914-c7f3-41e8-872c-9894d70b9f93)
4. You will find the problem.

### Requirements

- e.g. Fix right-click menu leak when clicking on a right side item on the homepage.

### Files Version

3.7.11.0

### Windows Version

10.0.26100.2033

### User ID

a2a077a5-f4d9-4311-98d4-155b85123aa6

### Log File

[debug.log](https://github.com/user-attachments/files/17556912/debug.log)
I think there's nothing on the log file.

**Comment by 0x5bfa** [comment]
Thanks for the feedback.

I can't think of anything that we can do for this. Suspect this comes from the underlying UI framework we use.

**Comment by zsr-lukezhang** [comment]
> Thanks for the feedback.
> 
> I can't think of anything that we can do for this. Suspect this comes from the underlying UI framework we use.
> 
> OR do we need this? ShouldConstrainToRootBounds

But only the homepage has this bug.

**Comment by yaira2** [comment]
It turns out `ShouldConstrainToRootBounds` is true by default. Instead, I was able to resolve this by changeing the `FlyoutPlacementMode`.

**Comment by 0x5bfa** [comment]
@zsr-lukezhang This was fixed by @yaira2 and will be included in the upcoming release.
