### ISSUE TITLE
Bug: RecycleBin and ThisPC can only be open correctly at the first time

### ISSUE THREAD

**Issue by DovIn0613** [files-community/Files#16416]
### Description

When file is installed , it run well . But after a restart , the RecycleBin and ThisPC can't be open correctly ,unless I reinstall file or closing the files app and quiting the background process. And this problem will still happen after my next restart.
It will give me a noticement like the following picture,it means : Drive unplugged Not a folder
![Image](https://github.com/user-attachments/assets/2d6f8383-2d5c-4169-a4ff-64d8812e74bc)

### Steps To Reproduce

1.Install
2.Restart the computer
3.Try to open the RecycleBin or ThisPC

### Requirements

- e.g. Fix crash that occurs when...
Hope you can solve this problem or tell me how to avoid it

### Files Version

3.7.11.0

### Windows Version

10.0.22631.4391

### User ID

5898c372-7d8e-4fab-9fe6-a853c2607f20

### Log File

[debug.log](https://github.com/user-attachments/files/17590677/debug.log)
<!-- Uploading "debug.log"... --

**Comment by Lamparter** [comment]
This looks similar to #16326

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #16326. You can check there or click subscribe in the right sidebar for updates.
