### ISSUE TITLE
Feature: Add the ability to close all tabs with Ctrl+Shift+W

### ISSUE THREAD

**Issue by Lamparter** [files-community/Files#16414]
### What feature or improvement do you think would benefit Files?

> Similar to #16346

Files already has the (browser-like) functionality to close the current tab with <kbd>Ctrl+W</kbd>, open a new tab with <kbd>Ctrl+T</kbd>, restore a previously closed tab with <kbd>Ctrl+Shift+T</kbd> and open a new window with <kbd>Ctrl+N</kbd>, but a way to take this one step further is by adding <kbd>Ctrl+Shift+W</kbd> which is already a feature in Edge and allows the user to close all tabs at once. This is different from pressing the **Close** caption button in the top right or pressing <kbd>Alt+F4</kbd> because this does not restore the tabs on startup as it closes each one individually.

### Requirements

- ~~Add button to close all tabs to tab context menu~~
- Add keybind to close all tabs, namely <kbd>Ctrl+Shift+W</kdb>
- #16346

### Files Version

3.7.11.0

### Windows Version

10.0.22631.4391

**Comment by yaira2** [comment]
Thank you for the feedback

**Comment by yaira2** [comment]
As far as adding this option to the menu, I think there is some overlap with #7501.

**Comment by Lamparter** [comment]
Adding such a button wasn't the original meaning of my issue as much as the keyboard bind itself: <kbd>Ctrl+Shift+W</kbd> is a basic functionality for any tab-based app, much like <kbd>Ctrl+W</kbd> and <kbd>Ctrl+T</kbd>.

**Comment by yaira2** [comment]
Let's focus on the keyboard shortcut and action.
