### ISSUE TITLE
Feature:When auto-hidden taskbar is enabled, it can't be shown when using files in fullscreen

### ISSUE THREAD

**Issue by DovIn0613** [files-community/Files#16411]
**Description**
I have auto-hidden taskbar enabled and open Files in the foreground, moving my mouse towards the bottom of the screen won't make the taskbar appear like in every other Windows program

**Steps To Reproduce**
Enbale auto-hidden taskbar
Try making it show up when the Files window in in the foregroung
**Requirements**
Fix bug that breaks auto-hidden taskbar
**Files Version**
3.7.11.0

**Windows Version**
10.0.22631.4391

**Comment by 0x5bfa** [comment]
@yaira2 Here's the fix #16412 I know you are working on removing this with WinAppSdk 1.6 but we don't know how long it'll take to be merged

**Comment by yaira2** [comment]
@DovIn0613 thank you for the report. This is a known issue with WinAppSdk, but thankfully they fixed it in their latest 1.6 update and we're working to bring this to Files.

**Comment by yaira2** [comment]
> [@yaira2](https://github.com/yaira2) Here's the fix [#16412](https://github.com/files-community/Files/pull/16412) I know you are working on removing this with WinAppSdk 1.6 but we don't know how long it'll take to be merged

Hopefully soon.
