### ISSUE TITLE
マイクロソフトのフォトとの連携

### ISSUE THREAD

**Issue by stIprurIJu** [files-community/Files#16415]
### What feature or improvement do you think would benefit Files?

エクスプローラーでマイクロソフトのフォトを使い画像を開くと、左右のキーで画像が切り替えられて便利なのですが、この機能が欲しいです。

フォトだけでなく、他のアプリでも同じ動きをする物があるので、この機能が付けば、他のアプリでも同時に解決するのではないかと、予想しています。

### Requirements

解りません。

### Files Version

3.7.11.0

### Windows Version

10.0.22631.4317

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #15409. You can check there or click subscribe in the right sidebar for updates.
