### ISSUE TITLE
Feature: drop stack

### ISSUE THREAD

**Issue by wada3n** [files-community/Files#16417]
### What feature or improvement do you think would benefit Files?

**Introduction**
I am writing to request the addition of a Drop Stack feature to the Files app. This feature has been previously implemented in the Path Finder file manager on macOS and is also available in current applications such as Dropover. The Drop Stack feature allows users to temporarily store files from different locations in a virtual shelf, making it easier to manage and organize files.

**Feature Description**
The Drop Stack feature enables users to drag and drop files from the file manager into a temporary shelf. Users can then decide where to place the files later by dragging them to a folder, uploading them in bulk to a website, or performing a series of actions such as renaming or compressing the files.

### Requirements

**Improved File Management:** Users can collect files from various locations and organize them in one place before deciding on their final destination.

**Increased Efficiency:** The ability to perform bulk actions on files, such as renaming or compressing, saves time and effort.

**Enhanced User Experience:** The Drop Stack feature provides a more intuitive and user-friendly way to manage files.

### Files Version

v3.7.11

### Windows Version

22631.4391

### Comments

https://github.com/user-attachments/assets/34fa3713-e57d-4771-9b3f-be34ae178eae

2- 

https://www.youtube.com/watch?v=eSy0P96xl0g

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #12490. You can check there or click subscribe in the right sidebar for updates.
