### ISSUE TITLE
PDF files opened in Acrobat (not default)

### ISSUE THREAD

**Issue by yIsItSo** [files-community/Files#16413]
### Description

After a reset double clicking on a PDF file opens it in Adobe Acrobat Viewer, which is not the default app.
After manually selecting the correct app (open with ..) the correct app becomes default.

Also the icon for PDF files is (and remans Acrobat).

Neither of these happen in explorer

### Steps To Reproduce

Reset
Double click on a PDF file, Acrobat is installed but not default

### Requirements

Default PDF file application should be respected

### Files Version

3.7.11.0

### Windows Version

10.0.22635.4435

### User ID

59a0be4e-33e4-4ed3-9aea-1b696654473d

### Log File

[debug.log](https://github.com/user-attachments/files/17586672/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, the icon won't change if you change the default program until you refresh the folder. Also did setting the default again keep the change in Files correctly?

**Comment by yaira2** [comment]
Can you confirm if uninstalling and reinstalling Files resolves this issue?

**Comment by yIsItSo** [comment]
Uninstall / reinstall seems to have fixed the issue.

BTW - did a save and restore of settings. Tag information, names and tags
of folders, was not restored.

Thanks
