### ISSUE TITLE
Bug: can not pin a folder

### ISSUE THREAD

**Issue by eqemenesen** [files-community/Files#16428]
### Description

I cannot pin ay folder to the files app. ı can see already pinned apps as unpin in right click but pin no visable pins in the app and pinning button wont work

### Steps To Reproduce

1. right click to folder
2.  push the pin button

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.7.11.0

### Windows Version

10.0.22635.2771

### User ID

69be7b3c-f4f0-486c-b9c2-b74ad2940950

### Log File

[debug.log](https://github.com/user-attachments/files/17608162/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you send a screenshot of the Files window

**Comment by yaira2** [comment]
1. Does it work if you restart Windows?
2. Does pinning the folder in File Explorer display the pinned folder in Files?

**Comment by Josh65-2201** [comment]
@eqemenesen Can you answer the above questions

**Comment by MagidElgady** [comment]
> 1. Does it work if you restart Windows?
> 
>     2. Does pinning the folder in File Explorer display the pinned folder in Files?

Here are my responses to this issue:

1) No, restarting Windows has no effect. It still breaks.

2) No, the pinned folders in my File Explorer do not show here at all.

This is the only issue I have so far with using the Files app. It's such a basic feature that should not be this difficult to fix.

I have attached a screen recording showing this issue when clicking on "Pin to Sidebar". Hope this helps.

https://github.com/user-attachments/assets/722bd4a0-c2c5-4a03-b05f-394d1b5a9742

**Comment by Josh65-2201** [comment]
Can you try turning off `Files settings > Advanced > Leave app running in the background` then close and reopen Files

**Comment by MagidElgady** [comment]
Worked like a charm. Thank you!

**Comment by Josh65-2201** [comment]
Great, We're tracking fixing this in https://github.com/files-community/Files/issues/15410. You can check there or click subscribe in the right sidebar for updates.
