### ISSUE TITLE
Feature: Make an ability of custom icons for Files in Personalization*

### ISSUE THREAD

**Issue by Adonyashka** [files-community/Files#16429]
### What feature or improvement do you think would benefit Files?

I would like to change basic icon of Files to my own icon, but I can't do that. Moreover, I can't find the way to .exe to make an icon for desktop and change it. I think that feature of changing icon is nice solvation of this problem and also cool ability for customizing. Thank You!

### Requirements

there is no special requirements

### Files Version

3.7.11.0

### Windows Version

10.0.19045.5011

**Comment by Josh65-2201** [comment]
Thanks for the feedback, this can't be done without building from source https://files.community/docs/contributing/building-from-source with the changed icons. To make a shortcut you can drag Files from the start menu to the desktop.
