### ISSUE TITLE
Feature: remove tab bar margin. Extend tabs to the top of the titlebar.

### ISSUE THREAD

**Issue by Erquint** [files-community/Files#16424]
### What feature or improvement do you think would benefit Files?

I need the waste of space above the tab bar gone.
![Image](https://github.com/user-attachments/assets/13b88486-a186-4c05-8557-ecc2080652e3)
It makes me miss the tabs with my mouse pointer by going too high.  

It's not even like it can be used for dragging the window. 🤷‍♂️

### The actual drag handle
![Image](https://github.com/user-attachments/assets/b9fc8f07-60ae-4ca4-9e2d-c4280629564a)

I'm using Files fullscreen anyway.
The only purpose I'm noticing so far of that margin is to make my life harder.
Either make it an option, make it adapt or get rid of it completely.

There's a reason web browsers extend tabs all the way to the top of the titlebar when fullscreen.
### Windowed

![Image](https://github.com/user-attachments/assets/216c363e-b909-4302-8c49-9f8ca0e4ccc6)

### Fullscreen

![Image](https://github.com/user-attachments/assets/2b33d9d9-72d1-4e45-bb19-fdb85c0d7614)

They also leave additional space between the tab controls and the window controls as a fallback at all times, which is fine, I guess.

Think I cropped the screenshots short..? Try with your own browser of choice and see for yourself.

Please use their insight.

### Requirements

In fullscreen mode, the very top pixel row of the screen must accept tab clicks from the mouse pointer.

### Files Version

3.7.11.0

### Windows Version

10.0.19045.4412

**Comment by Lamparter** [comment]
This is an interesting proposal. The TabView control is designed to have this margin to be in alignment with the WinUI design language, don't you think that removing the margin would betray that?

**Comment by Josh65-2201** [comment]
Thanks for the feedback, the drag area between window controls and tabs are suppose to be like browsers but doesn't always so. We're tracking this in #14958. You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
Please refer to #16427. I agree in principle about removing the gap in full screen mode. In fact, earlier versions did not have this gap, but the overwhelming feedback indicated that it's natural for users to move the cursor to the top of the screen to grab the window.

**Comment by Erquint** [comment]
Those issues are distinct.  

> Requirements
> In fullscreen mode, the very top pixel row of the screen must accept tab clicks from the mouse pointer.

vs

> Requirements
> Make sure a drag gap is always present between the tabs and window controls

vs

> Requirements
>  - move the location of open tabs (if the user wants this option active).
>  - change in the location of some buttons.

As for:
> overwhelming feedback indicated that it's natural for users to move the cursor to the top of the screen to grab the window

That really sounds like one of those collective misunderstandings of own needs and misrecollection of own experiences.  
If they had such a habit from other tabbed programs — it would most probably be from browsers.  
But browsers don't in fact leave a gap on top as I pointed out.  
My reasoning is based on a commonly accepted design principle all users are well-accustomed to in actual practice.  

I showed what Edge does.  

## Firefox

### Windowed

![Image](https://github.com/user-attachments/assets/6509624f-c25d-4504-9507-ff88721a84f3)


### Fullscreen

![Image](https://github.com/user-attachments/assets/4b0e8e97-51d7-4f78-b5ff-2ae8cc34e02a)

Yes, no difference.  

## Chrome

### Windowed

![Image](https://github.com/user-attachments/assets/832bbf96-fb38-45a2-bfa5-fd9faf361a27)

### Fullscreen

![Image](https://github.com/user-attachments/assets/a06c351b-0a4a-4a73-906a-c1305d18dd92)

Yes, no difference either.

Edge adapts unlike other ones.  
But **all** browsers have the top row of pixels pick tabs.  
Not one leaves a gap there. Dead or draggy.  

So as much as I despise saying it: users don't know what they want.

**Comment by Erquint** [comment]
### Windows 11 Explorer.

## Windowed

![Image](https://github.com/user-attachments/assets/13126e8d-5989-4890-9154-de1419b24cfb)

## Fullscreen


![Image](https://github.com/user-attachments/assets/c1b1e9bb-4cdd-4f1b-8282-0a08c878f119)

It adapts like Edge.  
M$ seems to like adapting.

**Comment by yaira2** [comment]
If feedback suggests that the gap should be removed when maximized, I'm open to the idea. Personally, I favor matching the behavior of web browsers. However, this approach was previously tried in Files (we had a neat helper class to detect the window state), but users requested to revert the behavior in favor of having a drag region (which, unfortunately, is currently non-functional due to a bug in WinUI).

That was a couple of years ago, so things might be different now. I'll keep an eye out for similar feedback and will remain open to reconsidering this if there's more interest in heading in that direction.

**Comment by Josh65-2201** [comment]
I would also prefer it act like a browser but #14958 might need to be fixed first

**Comment by yaira2** [comment]
I haven't been able to repro that but hopefully both issues will be solvable when the WinUI TitleBar control is released.

**Comment by yair100** [comment]
> I would also prefer it act like a browser but [#14958](https://github.com/files-community/Files/issues/14958) might need to be fixed first

@Josh65-2201 do you know if this still occurs?

**Comment by Josh65-2201** [comment]
I can't get it to happen in 4.0.24.0
