### ISSUE TITLE
Feature: Save the size of a folder.

### ISSUE THREAD

**Issue by czargab18** [files-community/Files#16423]
### What feature or improvement do you think would benefit Files?

Sometimes I need to know the size of a folder. But if I leave this option active, I will have CPU problems.

The application could evaluate the folder size once, only when it is modified, or place an option in the navigation bar to calculate this (this last option would change the folder size value.

![Image](https://github.com/user-attachments/assets/410343de-464d-41e0-bfa5-7360fdcc74fc)

![Image](https://github.com/user-attachments/assets/effffbc7-80f4-4c7c-8d13-8c89b63cd71c)

### Requirements

- save the folder size value: without calculating every time I open a folder. 
- the user has the option to update the folder size with a button on the navigation bar.

### Files Version

3.7.11.0

### Windows Version

10.0.22631.4391

**Comment by Lamparter** [comment]
Perhaps this could be done using a hashing algorithm 👀

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #13752. You can check there or click subscribe in the right sidebar for updates.
You can right now you the properties window
