### ISSUE TITLE
Feature: change where open tabs are displayed.

### ISSUE THREAD

**Issue by czargab18** [files-community/Files#16427]
### What feature or improvement do you think would benefit Files?

Sometimes I get bothered by this huge empty space. It would be useful for some users if there was an option to change the display location of open tabs.

As it currently stands:
![Image](https://github.com/user-attachments/assets/05dcd4b9-802e-481d-abe4-4b84b002a5d0)

First, I find it strange that when opening the app there is this "home" page button separate from the others that are together under "pinned". I could be with that group.

When removing it from that location, the tab that is currently open would be displayed there. Or two, one below the other, if the user has two tabs divided. 

As demais abas abertas ficariam em um grupo "outras abas abertas" logo abaixo.Caso não tenha outras abas, esse grupo não seria exibido.

I'm not an expert in graphic design but I tried to make an outline of what I'm talking about. Below, see what it would look like:
![Image](https://github.com/user-attachments/assets/2cbf2143-24bf-49b2-8318-315fd7e954b3)

The options to close, minimize and maximize the size of the app could be in the position of the image above or the image below.
![Image](https://github.com/user-attachments/assets/4a7a1e56-5a98-4aa6-b118-3fb7a95ca70f)

### Requirements

- move the location of open tabs (if the user wants this option active).
- change in the location of some buttons.

### Files Version

10.0.22631.4391

### Windows Version

3.7.11.0

**Comment by Josh65-2201** [comment]
Thanks for the feedback, the home page is Files specific and isn't the one in Windows File Explorer. Pins are separate user changeable and sync with Windows File Explorer pins.

**Comment by yaira2** [comment]
Thank you for your feedback! The area above the tabs is designed to serve as a drag area. Unfortunately, there's a known issue in WinUI where this drag area conflicts with the resizing area of the title bar. We're hopeful this will be resolved soon. In the meantime, we're planning to keep this gap to be prepared for whenever Microsoft fixes this issue.
