### ISSUE TITLE
Feature: Fix window dimensions whenever you open the app.

### ISSUE THREAD

**Issue by czargab18** [files-community/Files#16421]
### What feature or improvement do you think would benefit Files?

Add option to enter the dimensions, height and width, that the window will always have to open. It bothers me sometimes when I open the app and it comes with a very small dimension or very disproportionate to the width and height. Could it be possible for the user to choose a window size model when opening the application?

Note: The user could continue changing the dimensions to the best fit, even with this option active.

![Image](https://github.com/user-attachments/assets/38a22817-047d-41b4-a7d3-9a5c02ef1a3b)

### Requirements

- app size option when opening it.

### Files Version

3.7.11.0

### Windows Version

23H2

**Comment by yaira2** [comment]
The startup dimensions are based on what they were when you last closed the window. If you're looking for more control to be able to change the size on demand, there are apps like Auto Sizer that let you quickly change a window's size to a preset using a keyboard shortcut.
