### ISSUE TITLE
Code Quality: Improve the way packages are managed in the codebase

### ISSUE THREAD

**Issue by Lamparter** [files-community/Files#16430]
### Description

Currently, local NuGet Packages, Link Libraries and Windows Metadata files are managed in a very messy way:

- They are stored in `src/Files.App/nupkgs` which is not a PascalCase folder like others
> Preferably, they should be stored in a place like `pkgs/*` or `src/Packages/*` etc.

- ~~App extension files (link libraries) are stored in the root `src/Files.App` directory.~~
> ![src/Files.App/*.dll](https://github.com/user-attachments/assets/bfb5d5e2-141e-4232-ab3b-d2b24bca85dc)
> 
> ~~This is a bad idea as it clutters the codebase when they could more neatly be organised in the same directory as the NuGet package store, or inside another folder altogether.~~

- The NuGet Gallery server entry is duplicated in the NuGet package manager
> ![NuGet packages for Solution...](https://github.com/user-attachments/assets/cadf58d9-7c59-48d0-9d7d-95da164e52aa)
> 
> This is because the NuGet Gallery endpoint is also listed inside Files's `nuget.config` file which it _should not_ as this entry is already provided automatically by Visual Studio.

### Concerned code

- https://github.com/files-community/Files/blob/a4641ff9bcc5c6224982fddc6e2f28d798185bac/nuget.config#L4
- https://github.com/files-community/Files/blob/a4641ff9bcc5c6224982fddc6e2f28d798185bac/nuget.config#L5
- ~~`src/Files.App/*.dll`~~
- `src/Files.App/nupkgs/`

### Gains

- Better codebase structure
- Less confusion when choosing a package source
- Central store for NuGet Packages, Link Libraries and Windows Metadata files

### Requirements

This should be removed.
```diff
-         <add key="NuGet official package source" value="https://api.nuget.org/v3/index.json" />
```

---

This should be changed to a different pattern that matches with the rest of the codebase.

```diff
-         <add key="Local Packages" value="src/Files.App/nupkgs" />
+         <add key="Local Packages" value="src/Files.App/Packages" />
```
```diff
-         <add key="Local Packages" value="src/Files.App/nupkgs" />
+         <add key="Local Packages" value="src/Packages" />
```
```diff
-         <add key="Local Packages" value="src/Files.App/nupkgs" />
+         <add key="Local Packages" value="nupkgs" />
```
```diff
-         <add key="Local Packages" value="src/Files.App/nupkgs" />
+         <add key="Local Packages" value="pkgs" />
```

---

~~The `dll` files should also be migrated to the same or a similar store.~~

### Comments

N/A

**Comment by 0x5bfa** [comment]
IMO, I literally don't care about it.

**Comment by yaira2** [comment]
@Lamparter pending approval, would you like to work on this?

**Comment by 0x5bfa** [comment]
I don't like these but if you move MainWindow to Views folder and adjust the namespace, I'd be happier.
