### ISSUE TITLE
Bug: El visor de archivos funciona mal querer visualizar archivos en formato PDF

### ISSUE THREAD

**Issue by grabago61** [files-community/Files#16436]
### Description

La parte que no funciona correctamente es el visualizador de archivos, sobre todo al ver los archivos en formato de PDF, porque me saca del programa y aunque vuelva a ingresar y vuelvo a intentar ver el archivo PDF, vuelve a hacer el mismo efecto de sacarme del programa. Les pido que resuelvan ese problema con una actualización del programa. Y si me pueden enviar correo indicándome si ya se solucionó y con cual actualización puedo correr para probar si ya funciona correctamente. Gracias. Buen día.

### Steps To Reproduce

Seleccionar un archivo con formato PDF
Seleccionar que se vea el contenido del archivo del lado derecho
A los pocos segundos, el programa Files se cierra. Y adicional esto, si funciona en algún momento, tarda mucho tiempo en aparecer la imagen del archivo que quiero visualizar del formato PDF.

### Requirements

- e.g. Fix crash that occurs when... I tried to view a file in format PDF and then crash y be close without option about it, and the I have to restart.

### Files Version

3.7.11.0

### Windows Version

10.0.19045.5011

### User ID

f8bc2dbc-00f5-4d96-967b-ff8e9953d859

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #16226. You can check there or click subscribe in the right sidebar for updates.
