### ISSUE TITLE
app crashes when copy folder to NAS drive

### ISSUE THREAD

**Issue by Yehorchenkov** [files-community/Files#1644]
When I try to copy folder from a local drive to NAS drive via ctrl+c, ctrl+v, app crashes. New folder on NAS drive is created but it is empty.

**Comment by yaichenbaum** [comment]
@Yehorchenkov Is this still an issue in v0.21.1?

**Comment by Yehorchenkov** [comment]
You fixed this, for now app don't crash. But it don't refresh file list after coping and have to do this manually.
