### ISSUE TITLE
Code Quality: Improve UITests

### ISSUE THREAD

**Issue by Lamparter** [files-community/Files#16446]
### Description

Right now, the UITests app is left in a rather sorry state:

![Image](https://github.com/user-attachments/assets/783e02d5-cfc7-421f-8a2b-efebc8f6f235)
> broken sidebar

![Image](https://github.com/user-attachments/assets/528662de-2249-41a7-8956-afeb545eb9a8)
> bad icon

![Image](https://github.com/user-attachments/assets/54298cf8-e217-4752-bcaf-2db5b4d6ffdb)
> bad taskbar name

![Image](https://github.com/user-attachments/assets/07a1da5a-6ce7-4149-b65c-d7d9e98a719a)
> homepage is empty

So I'd like to take the effort to make it a little bit better.

### Concerned code

`tests/Files.App.UITests/`

### Gains

- Easier navigation
- App is more recognisable

### Requirements

- [x] Change app name from _Files ui tests app_ to _Files UI Tests_
- [x] Add app logo (here's a quick mockup I made based on the original logo!)
> <img width=120 src="https://github.com/user-attachments/assets/b8513d76-4c90-4af1-a317-bde6d93a487a" alt="Files UITests">

- [x] Upgrade WinAppSdk to 1.6 (supposedly a bit quicker than #16156 lol)
- [ ] Add homepage
- [ ] Fix sidebar
- [x] Fix taskbar name
- [ ] ~~Add a code section to each control to see how to implement it (probably going a bit too much into a gallery app than a controls demo)~~

### Comments

I have already made a start at [`Lamparter:uitests`](https://github.com/Lamparter/Files/tree/uitests) which I'll create a PR for once this I get the go-ahead on this.

---

![Files UI Tests in the taskbar](https://github.com/user-attachments/assets/85ef7df6-64be-43fd-bac1-5cbf6bc4ee45)

**Comment by 0x5bfa** [comment]
> broken sidebar

I was going to use ToggleSwitch on the right side of the caption buttons on the top of the window. But I didn't have much time to remake it and also this isn't user-facing, therefore I don't find it should be updated now.

> bad icon

I find it cool but maybe we'd like to keep the repo smaller and again it's not user-facing therefore I don't find it good idea. We should improve this project as we update controls.

> bad taskbar name

I guess, we can move forward this.

> homepage is empty

I was going to add cards for the controls but we don't have as many controls as we can create them on the best layout.

> App is more recognisable

As you know, currently only Yair, Martin and sometimes me use this project just to test control accessibilities.

Speaking what controls we are going to put, I expect we're going to add SidebarView, Toolbar, Omnibar and FolderView, all of which aren't standalone'd as of now.

> Upgrade WinAppSdk to 1.6

We'd do this only when we have to use APIs or controls that are available only in 1.6

**Comment by Lamparter** [comment]
> > probably going a bit too much into a gallery app than a controls demo
> 
> Additionally, Should we decide to distribute these controls to public on NuGet.org (it'd be cool but it costs more our work), these changes would be good idea. But for now, we have never decided.

This is exactly what I had in mind.

**Comment by 0x5bfa** [comment]
Ask @yaira2 if the logo should be added or not.
I think I can review other things.

> Add a code section to each control to see how to implement it

We don't need it yet.
