### ISSUE TITLE
Feature: right click drag-n-drop

### ISSUE THREAD

**Issue by BedBug2479** [files-community/Files#16443]
### What feature or improvement do you think would benefit Files?

show different options when a folder/file is drag-n-droped using right-click
similar to that in windows explorer

![Image](https://github.com/user-attachments/assets/6dc80060-1f8e-48e8-9a2a-e5512c6ca64e)

### Requirements

This should display the below options when done the above task
-Copy here
-Move here
-Extract Here
-Cancel
-7zip/TeraCopy options

### Files Version

3.7.11.0

### Windows Version

10.0.19045.5073

**Comment by yaira2** [comment]
Thank you for your feedback. This feature is on our todo list and is being tracked in #1396. Please subscribe to #1396 to be notified of further updates.
