### ISSUE TITLE
Bug: When deleting a file, it will get stuck until the deletion is complete

### ISSUE THREAD

**Issue by ShuangTianSheng** [files-community/Files#16449]
### Description

When deleting a file, it will get stuck until the deletion is complete, even a small file takes 4 seconds to complete

### Steps To Reproduce

1,select a file;
2,Ctrl+D;

### Files Version

3.7.11.0

### Windows Version

19045.4651

### Log File

[debug.log](https://github.com/user-attachments/files/17678953/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, what do you mean by stuck, is the file not getting deleted?

**Comment by ShuangTianSheng** [comment]
> Thanks for the report, what do you mean by stuck, is the file not getting deleted?

During the deletion process, the software will lose response until the deletion is complete, which takes about 4 seconds to wait，I can reproduce this issue on both Win11 22h2 and Win10, it is a newly installed software

**Comment by yaira2** [comment]
Can you confirm if this is still an issue after emptying Recycle Bin?

**Comment by ShuangTianSheng** [comment]
Thank you for your answer,Taking inspiration from your response, I have found that whenever I manipulate files in the Recycle Bin (such as deleting a file through Files or Explorer), the CPU usage of the Huorong security software increases, and Files lose response until the operation is completed before they return to normal. This occurs in events related to the Recycle Bin, which may seem to be caused by Huorong security software, but Explorer remains in a normal state throughout the process!![Image](https://github.com/user-attachments/assets/2708fd56-2ab9-4d9e-866e-df2c98aced87)

**Comment by 0x5bfa** [comment]
I assume it's suspecting Files might be a malware  because deleting recycled items isn't re-doable. While it's concerning, that's not what Yair meant. 

There were a few reports that say that deleting finishes instantaneously after emptying Recycle Bin, we wanted to confirm this is the same issue as these reports.

**Comment by Lamparter** [comment]
I've had issues with Huorong virus protection software detecting WinUI3 apps as malware in the past.
Probably unrelated but there's a slim chance it isn't a coincidence.

**Comment by yaira2** [comment]
@ShuangTianSheng what I meant was, does this issue go away after emptying Recycle Bin?

"Regarding the issue you mentioned with Huorong, it's possible that they perform extra scanning when file operations are initiated by a third-party process, unlike File Explorer where these operations are triggered directly by Windows.
