### ISSUE TITLE
Bug: Open Storage Sense button missing

### ISSUE THREAD

**Issue by BedBug2479** [files-community/Files#16448]
### Description

Title

![Image](https://github.com/user-attachments/assets/57d679e0-295e-4479-826d-9446f2123161)

### Steps To Reproduce

Open Home page

### Files Version

3.7.11.0

### Windows Version

10.0.19045.5073

### Log File
[debug.log](https://github.com/user-attachments/files/17659205/debug.log)

**Comment by BedBug2479** [comment]
it is always for C and F only

**Comment by 0x5bfa** [comment]
Please erase your log and UPLOAD instead.

**Comment by 0x5bfa** [comment]
Also we don't show that unless drive usage exceeds 90%.

**Comment by BedBug2479** [comment]
> Please erase your log and UPLOAD instead as we phrase out that with bold font.
> 
> ![Image](https://github.com/user-attachments/assets/315b7d1b-e34f-44b1-b651-9f71723f2cba)

done

**Comment by yaira2** [comment]
> Also we don't show that unless drive usage exceeds 90%.

As @0x5bfa shared, the button only shows if the drive is close to full, so it looks like it's working as expected.
