### ISSUE TITLE
Bug: The right-click menu is missing items that are only in the new version of Win11 menu

### ISSUE THREAD

**Issue by PandaFiredoge** [files-community/Files#16453]
### Description

![Image](https://github.com/user-attachments/assets/04230b72-32c7-4b4d-a738-2691d3a11eb9)
These things are missing from the right-click menu of Files

### Steps To Reproduce

1. Find a file 
2. Right-click

### Files Version

3.7.11.0

### Windows Version

10.0.26100.2161

### User ID

18f8c936-5e4e-438c-9082-948a200d4eb0

### Log File

[debug.log](https://github.com/user-attachments/files/17691216/debug.log)

**Comment by 0x5bfa** [comment]
Thank you for the feedback.

We're tracking on in #8251. Click Subscribe to get notified of further news.
