### ISSUE TITLE
Bug: Crashing constantly when viewing files

### ISSUE THREAD

**Issue by omen124** [files-community/Files#16459]
### Description

When using the application it will consistently crash after a short period of usage or after viewing a small amount of files.

### Steps To Reproduce

1. Set the app to column view
2. Set the app to have the preview pane on the side
3. Go to a folder with multiple files (preferably a mix of files e.g. jpg, pdf, zip)
4. Select one then use the arrow keys to go up and down quickly, it should crash quickly.

### Files Version

3.7.11.0

### Windows Version

10.0.26100.2033

### User ID

15d75c8c-70f2-4296-b816-31958e2508a3

### Log File

[debug.log](https://github.com/user-attachments/files/17701242/debug.log)

**Comment by yaira2** [comment]
Thank you for the report, we're going to continue tracking this in #15505.

**Comment by omen124** [comment]
I have done further testing and it will still crash without the preview pane active.
