### ISSUE TITLE
Feature: +button

### ISSUE THREAD

**Issue by meemore** [files-community/Files#16457]
### What feature or improvement do you think would benefit Files?

please add the + button to the left side

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.7.11.0

### Windows Version

10.0.22621.4387

### Comments

![Image](https://github.com/user-attachments/assets/ad597e15-1722-47fe-821b-f6984fc57dc3)

**Comment by Josh65-2201** [comment]
Do you mean tree view?

**Comment by meemore** [comment]
yes sir tree view

**Comment by Josh65-2201** [comment]
Thanks for confirming, We're tracking this in #1928 . You can check there or click subscribe in the right sidebar for updates.

**Comment by yair100** [comment]
@meemore Tree View is currently available in preview https://files.community/download. It will be included in the next stable release.
