### ISSUE TITLE
Bug: Can't remove "Type" column

### ISSUE THREAD

**Issue by HC1Gunner** [files-community/Files#16456]
### Description

Under settings I have Type set to disabled, yet the column is still showing. Is there a way to drag-n- drop to swap columns, move left and right? I want to be able to see the "Size" column.

### Steps To Reproduce

1. Went into settings \ layout \ columns, and disabled Type, yet its still showing.
![Image](https://github.com/user-attachments/assets/fcefc997-a68e-4ab4-ac9e-b7536c600d5d)

### Files Version

3.7.11.0

### Windows Version

24H2 26100.2161

### Log File

[debug.log](https://github.com/user-attachments/files/17691975/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, you can't reorder them yet, We're tracking this in #8385. You can check there or click subscribe in the right sidebar for updates.

Do you have Sync layout and preferences at the top of those options on?

**Comment by yaira2** [comment]
The column options in settings are the defaults, but they won't affect folders where the defaults were already overridden. You can reset all those locations by toggling the setting to sync folder preferences on and off.

**Comment by HC1Gunner** [comment]
Sync is set to off.

Not sure what or where the right sidebar is located.

"You can check there or click subscribe in the right sidebar for updates".

**Comment by yaira2** [comment]
Try toggling sync on and off, that should reset any overrides previously set in folders.
