### ISSUE TITLE
Feature: Sync tags with cloud drive providers

### ISSUE THREAD

**Issue by Lamparter** [files-community/Files#16458]
### What feature or improvement do you think would benefit Files?

Currently, tags that are attached to files in cloud storage providers aren't necessarily synced with the native tag functionality Files uses. It would be interesting to see tags created in cloud storage interfaces, particularly OneDrive, also appear on the disk in Files.

### Requirements

- Find how to obtain cloud provider tags
- Implement service to scan and attach tags to files using ADS or a list stored on disk
- Match cloud tags with native tags

### Files Version

3.7.12

### Windows Version

N/A

### Comments

Might not be easy but it's an interesting proposal. 

---

> Is there a way to synchronize tags of files saved in OneDrive?

_Originally posted by **Peter the Great** in [`Files Community > #support`](https://discord.com/channels/725513575971684472/1305439851071541258/1305439851071541258)_

**Comment by yaira2** [comment]
Do you mean to sync tags applied in Files across cloud drives?

**Comment by Lamparter** [comment]
Yes sort of
OneDrive has support for tagging files, and my request was that it would be possible for those tags applied on the OneDrive interface would appear natively in Files as well.

**Comment by yaira2** [comment]
Seeing as this data isn't exposed to Windows, the only way would be to go through the cloud provider APIs, and that's out of scope for Files.
