### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by Darkbluetest** [files-community/Files#16451]
### Description

Files crashes with error message "System detected an overrun of a stack-based buffer in this application" when the preview panel is active and selecting some files (I tested with docs and pdfs). 

### Steps To Reproduce

1. Open Files normally
2. Open preview panel
3. Navigate to pdf and Word files, and select them allowing the preview panel to show them, then select another file, same or another type, and repeat several times (maybe 10 or 15 times, sometimes with a single time it crashes, others you need to repeat more). 
4. If it has not crashed yet, navigate through other folders and select (and preview) other files, sometimes accelerates the crash.

### Files Version

3.7.11.0

### Windows Version

Windows 11 23H2 (22631.4391)

### Log File

[debug.log](https://github.com/user-attachments/files/17688669/debug.log)

**Comment by yaira2** [comment]
This sounds like #16254, can you confirm if this is the case?

**Comment by Darkbluetest** [comment]
Yes, it seems the very same! I see there is no solution for now...Pity, the preview window was one of the main reasons I used it.

**Comment by yaira2** [comment]
Hopefully we'll find a fix
