### ISSUE TITLE
Bug: When opening MS Office Template files, Files opens an instance of file, rather than template

### ISSUE THREAD

**Issue by Gumwars** [files-community/Files#16464]
### Description

Files right click contextual menu "Open" option opens instance of MS Office template file, not template file itself.

### Steps To Reproduce

1. Right click on MS Office template file
2. Click "Open"
3. Document opens as an instance of the template, not the template.

### Files Version

3.7.11.0

### Windows Version

Edition	Windows 11 Pro Version	24H2 Installed on	‎10/‎28/‎2024 OS build	26100.2033 Experience	Windows Feature Experience Pack 1000.26100.23.0

### Log File

[debug.log](https://github.com/user-attachments/files/17721841/debug.log)

**Comment by yaira2** [comment]
After some testing, I think I understand what you were referring to. It appears that double-clicking a file in File Explorer behaves differently from using the "Open" option in the context menu. In Files, however, double-clicking a file and selecting "Open" from the context menu result in the same behavior (opening the file in read only mode). While we aim to make most behaviors in Files consistent with File Explorer, we believe our current behavior is more intuitive.

The good news is that you can still achieve what you're trying to do by holding down the Shift key when opening the context menu and selecting "Edit." I hope this provides an immediate solution.

**Comment by Gumwars** [comment]
That solution is more than equitable.  Thank you for looking into this so quickly.

**Comment by yaira2** [comment]
We're happy to hear this resolved the issue.
