### ISSUE TITLE
Feature: Enable draging/movement of Settings window

### ISSUE THREAD

**Issue by BedBug2479** [files-community/Files#16461]
### What feature or improvement do you think would benefit Files?

Add this feature so that if any setting is enabled/disabled what changes are done can be seen directly without closing the settings page

![Image](https://github.com/user-attachments/assets/3ae0bd09-5e12-4ce5-8b5a-30040bc00cbe)

Else if possible open the settings page in another Files tab

### Requirements

Check the changes done to the folder/file when a setting is enabled/disabled

### Files Version

3.7.11.0

### Windows Version

10.0.19045.5073

**Comment by 0x5bfa** [comment]
Thanks for the feedback.

Yair already has commented on this in another issue: https://github.com/files-community/Files/issues/16386#issuecomment-2440040005
