### ISSUE TITLE
Feature: Add Expand Drive (atleast 1lvl) at the left panel

### ISSUE THREAD

**Issue by BedBug2479** [files-community/Files#16460]
### What feature or improvement do you think would benefit Files?

![Image](https://github.com/user-attachments/assets/c8fe5b34-d2bb-49de-bf1c-98cc1c124ede)

### Requirements

This will show all the folders present in that particular folder

### Files Version

3.7.11.0

### Windows Version

10.0.19045.5073

**Comment by 0x5bfa** [comment]
Thanks for the feedback and please search before filing a new issue.

This is tracked on in #1928.

**Comment by 0x5bfa** [comment]
Thanks for the feedback.

This is tracked on in #1928.

Please search before filing a new issue like the issue form tells you exactly the same thing at the top of it.
![Image](https://github.com/user-attachments/assets/85f8d2f4-0f43-4d42-85c8-e76e2fad35b2)

**Comment by yair100** [comment]
@BedBug2479 Tree View is currently available in preview https://files.community/download. It will be included in the next stable release.
