### ISSUE TITLE
Bug: Right-Click not working correctly

### ISSUE THREAD

**Issue by mathewdyck** [files-community/Files#16476]
### Description

Right-clicking on anything (file or folder) is not functioning properly. sometimes it will not load the right-click menu but most of the time it will cause the app to completely freeze then crash.

### Steps To Reproduce

1. Right-click on a file or folder.

### Files Version

3.7.11.0

### Windows Version

10.0.22631.4391

### User ID

741f6fcb-1a57-4fce-9859-3b22b27b74c9

### Log File

[debug.log](https://github.com/user-attachments/files/17783175/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, what layout are you using?

**Comment by lyyQwQ** [comment]
> Thanks for the report, what layout are you using?

I have the same problem. I am using Windows 10, and I have the latest version from the Microsoft Store. I use the list view layout. One possible workaround is to pin some folders on the left side, then right-click one of them and wait for it to load; there is a higher probability that right-clicking in the right window will not crash. However, there is still a small probability that it will cause a right-click crash. I have added a custom registry entry, adding the "Open with VSCode" option to the right-click menu. I don't know if this is related.

**Comment by mathewdyck** [comment]
I'm using Columns view and no custom registry entries.

**Comment by Josh65-2201** [comment]
Thanks for the information, We're tracking this in #https://github.com/files-community/Files/issues/16193. You can check there or click subscribe in the right sidebar for updates.
Please also see https://github.com/files-community/Files/issues/16193#issuecomment-2486831940
