### ISSUE TITLE
Feature: Drag to move window in titlebar anywhere no interactive elements (including space between tab item and window border).

### ISSUE THREAD

**Issue by SuGar0218** [files-community/Files#16473]
### What feature or improvement do you think would benefit Files?

If user can drag the space between interactive elements and window border in title bar to move the window, it is more intuitive.
![Image](https://github.com/user-attachments/assets/d9096ab6-1e3b-4f38-92e0-c9647b15d943)

### Requirements

- Dragging the space in title bar anywhere no interactive element, including the space between interactive elements and window border, similar to Chrome title bar.

### Files Version

3.7.11.0

### Windows Version

10.0.22631.4317

**Comment by yaira2** [comment]
Thank you for reaching out. The drag region is already set to include all the non-interactive areas. However, there is a known issue in WinUI with drag regions being affected on the top portion of the title bar. This has been reported on the WinUI repository and will hopefully be resolved in future versions of WinUI.

**Comment by SuGar0218** [comment]
﻿Currently, I tried to MainWindow.Instance.SetTitleBar(TabControl) in MainPage when TabBar loaded, then use InputNonClientPointerSource to passthrough TabViewItems and buttons in TabBar every time TabStripFooter SizeChanged and TabBar SizeChanged. By doing so, space at top of tab items can be drag to move. Could you accept the solution? If accept, I can create a pull request or you can have a look on code at my fork https://github.com/SuGar0218/Files.在 2024年11月15日，23:29，Yair ***@***.***> 写道：﻿
Thank you for reaching out. The drag region is already set to include all the non-interactive areas. However, there is a known issue in WinUI with drag regions being affected on the top portion of the title bar. This has been reported on the WinUI repository and will hopefully be resolved in future versions of WinUI.

**Comment by yaira2** [comment]
If I recall correctly, `SetTitleBar` had some issues that prevented us from using it in Files. In any case, we're planning to use the new TitleBar control (I believe it's planned for the next version of WinUI) which will hopefully resolve all these issues.
