### ISSUE TITLE
Feature: Setting to always focus newly opened tabs

### ISSUE THREAD

**Issue by ilko-k** [files-community/Files#16474]
### What feature or improvement do you think would benefit Files?

Such a good stock explorer replacement but it lacks an essential feature related to tabs : they are not brought to front. This is very frustrating when browsing implies countless clicks to access some files.

### Requirements

- Setting to always focus newly opened tabs
- This will affect the 'open in new tab' action
- This will affect middle clicking items in the sidebar and file area

### Files Version

3.7.12.0

### Windows Version

10.0.26100.2161

**Comment by yaira2** [comment]
There are several ways to open new tabs, and the behaviors can differ depending on the method you use. Can you clarify how you are opening the new tabs?

**Comment by ilko-k** [comment]
I usually (and surely most of people) use the **middle mouse button** and on some cases **CTRL+LMB**. None of these actions bring the new tab to front, neither via **right click → open in new tab**.

**Comment by yaira2** [comment]
Thank you for clarifying, it sounds like it is working as expected. The behavior was designed to be consistent with web browsers.

**Comment by ilko-k** [comment]
Modern web browser do include that feature, Firefox for example :
![Image](https://github.com/user-attachments/assets/8e970de1-9327-49d3-bb47-c028e0895fa1)

**Comment by yaira2** [comment]
Fair enough, I was looking mainly at Edge and Chrome. That said, if there is enough interest for a setting, we'll consider adding one to Files.

**Comment by yaira2** [comment]
This feature will be added in the next update.

**Comment by ilko-k** [comment]
Awesome ! Thanks you alll.
