### ISSUE TITLE
Bug: No right click drag of files

### ISSUE THREAD

**Issue by yIsItSo** [files-community/Files#16486]
### Description

Right click-drag does not work at all. Nothing happens, no drag.

### Steps To Reproduce

right click on a file
drag the file while maintaining the right click

### Files Version

3.7.13.0

### Windows Version

10.0.22635.4510

### User ID

59a0be4e-33e4-4ed3-9aea-1b696654473d

### Log File

[debug.log](https://github.com/user-attachments/files/17811040/debug.log)

**Comment by 0x5bfa** [comment]
Thanks for the feedback.

We're racking this on in #1396. Click Subscribe to get notified of the further news when we have.
