### ISSUE TITLE
Small translate issue in French

### ISSUE THREAD

**Issue by PruvostMaxime** [files-community/Files#1649]
**Is your feature request related to a problem? Please describe.**
Just a small translation issue in French language

**Describe the solution you'd like**
Change the text from "Trajets" to "Disques" or "Péripheriques et lecteurs"
Change text to "Assez bon" in "Properties" to "OK" like in english

**Describe alternatives you've considered**
Reporting the issue ? 

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?
Windows 10 Pro,latest version
![Capture](https://user-images.githubusercontent.com/29450888/89335131-e2b2dd00-d697-11ea-83ee-725944a199dd.PNG)

**Comment by yaichenbaum** [comment]
@PruvostMaxime Would you like to work on this issue?

**Comment by PruvostMaxime** [comment]
Yeah,it's would be a pleasure !
So i could even check if there is other missings translations :D

**Comment by yaichenbaum** [comment]
@PruvostMaxime That is great! Let us know if you have any questions.

**Comment by PruvostMaxime** [comment]
Thanks !
And no problem,i'm gonna do it this weekend.

**Comment by yaichenbaum** [comment]
@PruvostMaxime Is this still an issue?

**Comment by PruvostMaxime** [comment]
Sup,
I forgot to do the translations because i have more work than planned (moving out,exams..)
Really sorry,still need to do them

**Comment by PruvostMaxime** [comment]
Looks like the translations are done now (wasn't running the latest version of Files)
So the issue can be closed
