### ISSUE TITLE
Feature: Enhancing File Sorting with Multiple Tag Filtering

### ISSUE THREAD

**Issue by StantantTheMan** [files-community/Files#16490]
### What feature or improvement do you think would benefit Files?

(~Currently, Files allows users to assign multiple tags to files and folders, but you can only filter by a single tag at a time. The proposed feature is to allow users to refine their tag-based searches by applying multiple tags at once, enabling a more specific/precise filtering experience. For example:~) 

As mentioned by @Josh65-2201, it appears we are able to sort through multiple tags. Would it be possible to implement a feature to allow for multiple filter sorting for those who use devices with touchscreen? For example, I utilize my Surface Pro without keyboard allot and majority of the Files app works flawlessly without one. However, it seems in order to sort with multiple tag filtering's, I would require a keyboard.
 
Improved Accessibility for Touchscreen Users
> - Allowing touchscreen users to filter by multiple tags without needing a keyboard would provide a smoother, more intuitive experience for those who prefer or rely on touch-based input. This would make the app more versatile and accessible for users who use their devices in tablet mode or on the go. This would greatly enhance the experience for those using tablets or 2-in-1 laptops.

### Requirements

**Possible Implementation for Both Keyboard and Touchscreen Users:**
Ideally, the implemented would be done in a way that accommodates both users who use a keyboard and touchscreen tablet - like the Surface Pro. I propose the following behavior:
 
1. Single Tag Selection:
> - When a user wants to filter by just one tag, they can simply select the tag, but to deselect it before selecting a new one, they would click again (or tap again) on the same tag. This would ensure that only one tag is active at a time.
 
2. Stacking Multiple Tags:
> - For multi-tag filtering, users can stack tags without deselecting any of them. On both desktop and touchscreen devices, they can continue adding tags to the filter. For example, after selecting "Music," users can add "Country" to narrow the search to only files tagged with both "Music" and "Country."
 
This approach would ensure an intuitive experience across both desktop (with keyboard) and touchscreen devices, making it easy to either apply a single tag or combine multiple tags quickly.

### Files Version

3.7.12.0

### Windows Version

24H2

### Comments

And lastly, I wanted to say thank you for the work you do. Files is fantastic, and it provides tremendous value. I truly appreciate the effort that goes into its development. I primarily use it on my Surface Pro 11, and I’m happy to report that it works flawlessly on ARM—at least, I haven’t encountered any issues so far.

**Comment by Josh65-2201** [comment]
Thanks for the feedback, you can already search with multiple tags, using `tag:name1,name2` you can do it on the home page to search the fully system or in a folder for that folder and sub folders

**Comment by yaira2** [comment]
Also worth noting #4813 which is intended to make it easier to use search filters.

**Comment by StantantTheMan** [comment]
> Also worth noting [#4813](https://github.com/files-community/Files/issues/4813) which is intended to make it easier to use search filters.

Hi @yaira2.

Question. I went over that thread; however, it doesn't seem to address my amended feature request. I apologize if I missed it, it was a lengthy read. Essentially, I'm looking to see if a feature could be implement to allow for multiple tag sorting using just the tag buttons on the side menu. This would allow users with tablets or 2-in-1 laptops, the ability to do so, without a keyboard.

**Comment by Josh65-2201** [comment]
The idea is that search filter will be a UI version of options you would have to normally type include `tag:` options

**Comment by yaira2** [comment]
> Question. I went over that thread; however, it doesn't seem to address my amended feature request. I apologize if I missed it, it was a lengthy read. Essentially, I'm looking to see if a feature could be implement to allow for multiple tag sorting using just the tag buttons on the side menu. This would allow users with tablets or 2-in-1 laptops, the ability to do so, without a keyboard.

It probably won't be directly via the sidebar, but the goal is for users to be able to filter a drive or folder by selecting tags (or other attributes) from a menu.
