### ISSUE TITLE
Bug: Win+E no longer opening File Explorer

### ISSUE THREAD

**Issue by phooBarred** [files-community/Files#16496]
### Description

I had changed the setting in Files to be the default instead of File Explorer. The toggle never stayed in the on position, but it was behaving as if the toggle stayed on (for example, Files would open if I pressed Win + E.
I wanted to turn off this default behavior, but I was unable to, since the toggle always remains off. So I uninstalled Files, but now Win + E give the following error:
[Window Title]
Explorer.EXE

[Content]
Application not found

[OK]

### Steps To Reproduce

Toggle default file explorer setting to on
uninstall Files
Press Win + E

### Files Version

3.7.11.0

### Windows Version

23H2

### Log File

I uninstalled Files, so I cannot include a log file. I'm guessing this is a registry issue and I am hoping that you already have the answer to this issue.

**Comment by Josh65-2201** [comment]
Sorry for the inconvenience, can you open this https://raw.githubusercontent.com/files-community/Files/main/src/Files.App/Assets/FilesOpenDialog/UnsetFilesAsDefault.reg > Right click anywhere > Save as > Set "Save as type" (Around the bottom) to all files > Remove .txt from the end of file name > Run the file

**Comment by phooBarred** [comment]
Thank you, that fixed it!
