### ISSUE TITLE
Feature: Drag selected file to an upper window

### ISSUE THREAD

**Issue by Jack251970** [files-community/Files#16503]
### What feature or improvement do you think would benefit Files?

This is the function that default File Explorer supports. For the files that have been already selected, you can drag it to an upper window.

https://github.com/user-attachments/assets/dd35cf4d-8513-463f-b111-f0c9b024bd4c

### Requirements

.

### Files Version

3.7.11.0

### Windows Version

10.0.26100.2314

**Comment by Josh65-2201** [comment]
Thanks for the feedback, you will need to clarify what you mean and what you expect to happen.

**Comment by Jack251970** [comment]
As the video shows, after I select the txt file, I can drag it into an upper window Files.

For Files, if you do the same thing, Files will be the topmost window which can cover the upper window, and thus you cannot drag this txt file to an upper window.
https://github.com/user-attachments/assets/ec336959-07d5-4a49-a7a3-dd85772fc203

This function can help you easily drag a file to the input control in the another window. For instance, I need to drag a video to Github for uploading like this:
https://github.com/user-attachments/assets/acc01847-3cf1-4aa1-912a-cb5d7eae6332

**Comment by Josh65-2201** [comment]
Thanks for the clarification, We're tracking this in #13255. You can check there or click subscribe in the right sidebar for updates.

**Comment by Jack251970** [comment]
Thank you!
