### ISSUE TITLE
Properties: Add "Details" tab

### ISSUE THREAD

**Issue by XPoppyX** [files-community/Files#1650]
Add the "Details" tab in the properties window to show extra file information
First step to implement: #691 and #1103 

-------------------------------
![Anotación 2020-08-04 171335](https://user-images.githubusercontent.com/61259627/89345956-4cba8a80-d676-11ea-9961-9bf25e500978.png)

**Comment by AqilCont** [comment]
Yes, I would love one for videos and other file types where some quick info like bitrate, fps, and resolution would be handy :D

**Comment by candrapersada** [comment]
Add the "[MediaInfo](https://mediaarea.net/en/MediaInfo/Screenshots)" tab in the properties window to show extra file information
![image](https://user-images.githubusercontent.com/36833664/89868124-7fb3cf80-dbdc-11ea-8c7d-dbbdd1af2175.png)

**Comment by winiston2212** [comment]
How does this look for image files?
![image](https://user-images.githubusercontent.com/59544401/90562317-d8441900-e156-11ea-9911-687659a33778.png)

**Comment by XPoppyX** [comment]
@winiston2212  What about "Dimensions" instead of "Size"? also show "Width", "Height" and "Bit depth"

![image](https://user-images.githubusercontent.com/61259627/90563393-be63ff80-e171-11ea-8908-11981847af0c.png)

**Comment by winiston2212** [comment]
I feel like having both dimensions and width/height is redundant. What about having a more detailed description in a tooltip? Like this:
![image](https://user-images.githubusercontent.com/59544401/90567265-bd75a280-e15e-11ea-944c-a497d9df233b.png)

**Comment by yaichenbaum** [comment]
> @XPoppyX I feel like having both dimensions and width/height is redundant. What about having a more detailed description in a tooltip? Like this:
> ![image](https://user-images.githubusercontent.com/59544401/90567265-bd75a280-e15e-11ea-944c-a497d9df233b.png)

I think it's better to display both in the dialog without using a tooltip since the properties dialog should have all the main details displayed. Additionally, there is enough room for it so it should cause any space issues.

**Comment by duke7553** [comment]
Hi there @winiston2212 .

It made my day to see your diligent effort getting this implemented. 

Certainly let us know if you're in doubt with any of the less obvious details. For instance, I would recommend tailoring this experience for desktop power users by packing in many relevant properties. It looks like that's what you're doing, so I'll be very excited to review this one with @yaichenbaum 

Some initial thoughts:
- Should we hide the entire field for a property if it isn't available/relevant or allow users to set the property from that field?
- Shouldn't the background of the horizontal NavigationView match the rest of the window when in Acrylic mode?
- I noticed you're using Windows.Storage which is the best way, but I wonder how fast the properties load for an item?

**Comment by yaichenbaum** [comment]
@duke7553 This is a work in progress between @winiston2212 and myself, we are working on getting location for geo tags on photos working before turning to the design and code of the implmentation.

**Comment by winiston2212** [comment]
@duke7553 I'm glad you like it!

> Should we hide the entire field for a property if it isn't available/relevant or allow users to set the property from that field?

Currently, any set of properties (excluding the core properties) that is completely null is hidden. I think it's better this way since there are a lot of sections. However, I am considering adding a "show all button" in case users wanted to add properties themselves. 

> Shouldn't the background of the horizontal NavigationView match the rest of the window when in Acrylic mode?

You're right, it should. I will fix that.

> I noticed you're using Windows.Storage which is the best way, but I wonder how fast the properties load for an item?

Currently, getting the properties takes about 17 milliseconds on my core i5-8250U processor. I'm not sure how much this will increase as more properties are added.
