### ISSUE TITLE
Feature: Don't show tab count on taskbar

### ISSUE THREAD

**Issue by sofianhit** [files-community/Files#16517]
### What feature or improvement do you think would benefit Files?

hi
**files items or tabs on windows taskbar (the taskbar that show start menu button , time & date , opening programs icons)**

![Image](https://github.com/user-attachments/assets/011f6485-eff2-424e-b8bb-022a52d73bb8)

the image explain what i mean in this feature

### Requirements

remove the tabs amount
resize the folder/file icon
remove the word "files"
display the folder/file name + small icon only

### Files Version

3.7.11.0

### Windows Version

10.0.19045.5198

**Comment by yaira2** [comment]
This change will be included in the next release.
