### ISSUE TITLE
Bug: Cloud Drives Seadrive shows File not found

### ISSUE THREAD

**Issue by jmbenevise** [files-community/Files#16528]
### Description

Cloud Drives Seadrive shows File not found

### Steps To Reproduce

Seadrive, cloud drive app from Seafile shows File not found when trying to open or copy a file

### Files Version

3.8

### Windows Version

Windows 10 22H2 Build 19045.5131

### User ID

00a62d69-2daa-413f-aab9-8abcaec1ca24

### Log File

[[debug.log](https://github.com/user-attachments/files/17898562/debug.log)
](url)

**Comment by yaira2** [comment]
@jmbenevise can you help clarify which steps to take to reproduce this issue?
