### ISSUE TITLE
Bug: 'Open the current directory in Visual Studio Code' and similar commands don't work if VS Code Insiders is installed

### ISSUE THREAD

**Issue by abdulrahim-ss** [files-community/Files#16520]
### Description

Every feature that has to do with invoking opening VS Code doesn't work if the normal VS Code is not installed and only Insiders is.

Please add settings options to edit paths for such actions, or the ability to edit actions in general!

### Steps To Reproduce

Write 'Open the current Directory in Visual Studio Code' in the command palette, or try opening VS Code in a git repo from the 'Open IDE' menu in the status bar.

### Files Version

3.8.0.0

### Windows Version

24H2 build 26100.2454

### Log File

[debug.log](https://github.com/user-attachments/files/17893687/debug.log)

**Comment by yaira2** [comment]
Thank you for the feedback, support for changing the ide is being tracked in #12857. You can also find a workaround for VS Code Insider here https://github.com/files-community/Files/issues/12857#issuecomment-1953198961.
