### ISSUE TITLE
Feature: delete the tooltips when hover on sidebar items .

### ISSUE THREAD

**Issue by sofianhit** [files-community/Files#16533]
### What feature or improvement do you think would benefit Files?

hi
the tooltips bother the eyes ,
and bother mouse pointer,
and cover items .
when hover on items .
so please delete it , i think we dont need it , because we know where are we on File and we have the full path at top . 

![Image](https://github.com/user-attachments/assets/4aa81346-5a11-4314-a788-4d111a8a8040)

### Requirements

1- on sidebar items hover on any item 
2- tooltip will display
3- if the path is long , it will cover other items 
4- it prevent the hover from being smooth 

### Files Version

3.7.11.0

### Windows Version

10.0.19045.5198

**Comment by yaira2** [comment]
Thank you for your feedback. It's true that you can view the full path after opening the folder, but the tooltips fill a specific need to view the path **before** opening the folder. This is especially useful when there are multiple folders with the same name.
