### ISSUE TITLE
Feature:  offline installer version

### ISSUE THREAD

**Issue by bestv5** [files-community/Files#16537]
### What feature or improvement do you think would benefit Files?

电脑不能联网，从哪里能下载离线安装版本？

### Requirements

电脑不能联网

### Files Version

1

### Windows Version

win1022h2

**Comment by Josh65-2201** [comment]
WinAppSDK: (Install this first)
https://cdn.files.community/files/stable/Files.Package_3.8.0.0_Stable_Test/Dependencies/x64/Microsoft.WindowsAppRuntime.1.5.msix
Files: 
https://cdn.files.community/files/stable/Files.Package_3.8.0.0_Stable_Test/Files.Package_3.8.0.0_x64_arm64_Stable.msixbundle

**Comment by mkeseattle** [comment]
@Josh65-2201 

One question: where can find the latest version of the offline installer on Files website? 

See the download section and can't find a current link and additionally this page is not well optimized for mobile view in portrait mode and landscape mode.

https://files.community/download

I use Microsoft Edge 135 on Android devices. Here are some screenshots.

![Image](https://github.com/user-attachments/assets/44685639-ff5a-4ccd-94dd-02d2990331c7)

![Image](https://github.com/user-attachments/assets/2580066d-00ae-474d-9b0c-4f919f94b2f8)

**Comment by Josh65-2201** [comment]
Offline download links aren't on the site I have linked the latest stable version below. As for it looking broken Files isn't for mobile and it doesn't make sense to spend time optimizing the site layout for it.

WinAppSDK: (Install this first)
https://cdn.files.community/files/stable/Files.Package_3.9.1.0_Test/Dependencies/x64/Microsoft.WindowsAppRuntime.1.5.msix
Files:
https://cdn.files.community/files/stable/Files.Package_3.9.1.0_Test/Files.Package_3.9.1.0_x64_arm64.msixbundle

**Comment by mkeseattle** [comment]
> WinAppSDK: (Install this first) https://cdn.files.community/files/stable/Files.Package_3.9.1.0_Test/Dependencies/x64/Microsoft.WindowsAppRuntime.1.5.msix Files: https://cdn.files.community/files/stable/Files.Package_3.9.1.0_Test/Files.Package_3.9.1.0_x64_arm64.msixbundle

I have just tested it and it does not work. The first file could be installed. During the installation of the second file:

**This app package is not supported for installation by App Installer because it uses certain
restricted capabilities.**

Use Windows 11 24H2 in a virtual machine and on a real computer.

**Comment by Josh65-2201** [comment]
You can try
1. Opening PowerShell as administrator
2. Enter `Add-AppxPackage -AppInstallerFile "<Path to file>"`
3. Wait until the blue bar at the top doesn't show
4. See if Files is in the start menu all apps section

**Comment by mkeseattle** [comment]
> You can try
> 
>     1. Opening PowerShell as administrator
> 
>     2. Enter `Add-AppxPackage -AppInstallerFile "<Path to file>"`
> 
>     3. Wait until the blue bar at the top doesn't show
> 
>     4. See if Files is in the start menu all apps section
> 
> 

Not working.

**Comment by Josh65-2201** [comment]
Can you show the full PowerShell window

**Comment by mkeseattle** [comment]
> Can you show the full PowerShell window

Sure.

![Image](https://github.com/user-attachments/assets/c2269289-ab96-43a6-ad8d-7f0a619e6492)

**Comment by Josh65-2201** [comment]
Sorry it's `Add-AppxPackage "<Path to file>"`

**Comment by mkeseattle** [comment]
> Sorry it's `Add-AppxPackage "<Path to file>"`

Same issue.

![Image](https://github.com/user-attachments/assets/d9cf1949-9354-4212-8345-f2ee48083ebd)

**Comment by Josh65-2201** [comment]
Install https://cdn.files.community/files/stable/Files.Package_3.9.1.0_Test/Dependencies/x64/Microsoft.VCLibs.x64.14.00.Desktop.appx and try again

**Comment by mkeseattle** [comment]
> Install https://cdn.files.community/files/stable/Files.Package_3.9.1.0_Test/Dependencies/x64/Microsoft.VCLibs.x64.14.00.Desktop.appx and try again

Same error message with these 3 commands in PowerShell.

**Comment by mkeseattle** [comment]
> 
> > According to the check, only this layout under this URL https://files.community/download is affected. Everything is fine in other places. Can you fix it?
> 
> Again Files is for PC only so there isn't a reason to spend time fixing it

The problem also exists with Desktop browsers for PC only. Make the browser window smaller and then there are similar layout problems only with this URL.

**Comment by Josh65-2201** [comment]
This one should work if it doesn't please send the PowerShell window screenshot
https://cdn.files.community/files/stable/Files.Package_3.9.1.0_Test/Dependencies/x64/Microsoft.VCLibs.x64.14.00.appx


> The problem also exists with Desktop browsers for PC only. Make the browser window smaller and then there are similar layout problems only with this URL.

You can make a new issue about this but since it only happens if the window is very small it probably won't be fixed.

**Comment by mkeseattle** [comment]
> 
> > The problem also exists with Desktop browsers for PC only. Make the browser window smaller and then there are similar layout problems only with this URL.
> 
> You can make a new issue about this but since it only happens if the window is very small it probably won't be fixed.

Only use Windows 11 Snap feature. See picture with desktop browser.

![Image](https://github.com/user-attachments/assets/8f0bdf01-24c1-423a-a5f0-36d41b98f98f)

**Comment by mkeseattle** [comment]
> This one should work if it doesn't please send the PowerShell window screenshot https://cdn.files.community/files/stable/Files.Package_3.9.1.0_Test/Dependencies/x64/Microsoft.VCLibs.x64.14.00.appx
> 

It worked wonderfully.

![Image](https://github.com/user-attachments/assets/da288c4a-ab69-4d75-bd1d-3a11c2addddf)

![Image](https://github.com/user-attachments/assets/eba25178-e8ee-4fee-a116-f2eb61e01415)

**Comment by bestv5** [comment]
> Install https://cdn.files.community/files/stable/Files.Package_3.9.1.0_Test/Dependencies/x64/Microsoft.VCLibs.x64.14.00.Desktop.appx and try again

Can the file downloaded from this link be installed offline （my computer is not connected to the Internet.）?

**Comment by Josh65-2201** [comment]
Yes

**Comment by mkeseattle** [comment]
> > Install https://cdn.files.community/files/stable/Files.Package_3.9.1.0_Test/Dependencies/x64/Microsoft.VCLibs.x64.14.00.Desktop.appx and try again
> 
> Can the file downloaded from this link be installed offline （my computer is not connected to the Internet.）?

Yes currently requires 4 files.

It works under Windows 10 22H2 and Windows 11 24H2.

1.
WinAppSDK: (Install this first)
https://cdn.files.community/files/stable/Files.Package_3.9.1.0_Test/Dependencies/x64/Microsoft.WindowsAppRuntime.1.5.msix

2.
https://cdn.files.community/files/stable/Files.Package_3.9.1.0_Test/Dependencies/x64/Microsoft.VCLibs.x64.14.00.appx

3.
https://cdn.files.community/files/stable/Files.Package_3.9.1.0_Test/Dependencies/x64/Microsoft.VCLibs.x64.14.00.Desktop.appx

4.
Files:
https://cdn.files.community/files/stable/Files.Package_3.9.1.0_Test/Files.Package_3.9.1.0_x64_arm64.msixbundle

**Comment by bestv5** [comment]
thanks  

于 2025年4月16日 GMT+08:00 上午6:26:19，mkeseattle ***@***.***> 写道：
