### ISSUE TITLE
Bug: Home Page Drive space doesn't update

### ISSUE THREAD

**Issue by leafpmpmp** [files-community/Files#16539]
### Description

When I move files around and make a difference in the space taken in a drive, the capacity shown on the home page doesn't change until I reopen the Files app, though properties does reflect it correctly.

Here the number shown is different from the properties.↓ (D:)
![Image](https://github.com/user-attachments/assets/2bfd9bbb-4532-432f-9605-518918d84134)

### Steps To Reproduce

1. copy some files into the drive or delete something
2. open the Home Page and see the Drives section

### Files Version

3.8

### Windows Version

10.0.22631.4541

### User ID

96a498d2-7152-4a22-8212-8e8ad62fdeb1

### Log File

[debug.log](https://github.com/user-attachments/files/17916644/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #6182 . You can check there or click subscribe in the right sidebar for updates.
