### ISSUE TITLE
Feature: Drag and Drop (Drag a url from a browser and drop into Files as a shortcut

### ISSUE THREAD

**Issue by DLachance74** [files-community/Files#16535]
### What feature or improvement do you think would benefit Files?

Windows explorer allows you to drag the URL from a browser address bar and drop it into explorer, which will automatically create a shortcut to the URL using the website title as the shortcut name.  This does not work at all for Files.  The only workable option is to create a new shortcut in files and paste the URL into the shortcut, then rename the shortcut.

### Requirements

- This proposal will allow a url dragged from a browser to create a shortcut in Files
- This proposal will copy the URL target as the shortcut target
- This proposal will copy the URL titl;e as the shortcut filename

### Files Version

3.8.0.0

### Windows Version

10.0.19045.5131

**Comment by Josh65-2201** [comment]
Thanks for the feedback, this should already work and seems like a bug, 
- Does drag and drop work in Files at all?
- What browser are you using?
- Where are you trying to drag to.

**Comment by DLachance74** [comment]
Drag and Drop works fine for file objects from other Files windows & tabs, file explorer, and other file managers.

I have tried dragging the highlighted url text from the address bar of Chrome (Version 131.0.6778.86), Edge (Version 131.0.2903.63), and Firefox (Version 132.0.2) all 64-bit.

I have tried dragging onto the file area, the left sidebar, and a tab.  In all cases, the tooltip changes from the crossed circle to the text "copy to ...", but no file is copied.



________________________________

**Comment by Josh65-2201** [comment]
We're tracking this in #15147. You can check there or click subscribe in the right sidebar for updates. While the title does say for images the issue and end result is the same
