### ISSUE TITLE
Bug: Details / List view - file icon size

### ISSUE THREAD

**Issue by rhubarbz69** [files-community/Files#16542]
### Description

Can the icon size (or s there a way to change the icon size) in the Detail layout view so that file and folder icons are using the 16x16 icon as is the case in the default Windows Explorer? The icons for files/folders seem to be using a scaled version of another icon size and look distorted. (Sorry - know this screenshot isn't the best - but hope it shows what I mean).
![Image](https://github.com/user-attachments/assets/765006ab-b3a5-455e-8ff7-4fb89f466f2f)

### Steps To Reproduce

1. Open Files app.
2. Navigate to a folder.
3. Change layout to 'Details'
4. Change icon size to 'Compact'

### Files Version

3.8.0.0

### Windows Version

10.0.22631.4460

### User ID

efe9bb7b-a172-4a40-afde-d3172eed4227

### Log File

[debug.log](https://github.com/user-attachments/files/17938440/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, this isn't a bug as Files icons show bigger then Windows File Explorer and use the x32 version so there not blurry.

**Comment by yaira2** [comment]
> (Sorry - know this screenshot isn't the best - but hope it shows what I mean).

No worries, I understand what this is referring to and it's something we've been planning for some time. It requires some other changes to be made first, but in any case, we're going to continue tracking in #10492.
