### ISSUE TITLE
Bug: Right clicking on the root dir of a drive makes the copy icon disappear

### ISSUE THREAD

**Issue by leafpmpmp** [files-community/Files#16544]
### Description

When I right click on drive D: , the top left corner, where the copy button should be, is cut off.
![Image](https://github.com/user-attachments/assets/b9b32ef7-7423-4a7f-992c-cbf681e71f45)
https://github.com/user-attachments/assets/7b8ee06f-6fba-46d8-ac47-82dc20508609
This happens in the root of C: as well (not always, for some reason), but doesn't in the sub folders.
~Please don't cut corners on my root, I'm already way too edgy.~

### Steps To Reproduce

1. go to the root dir of any physical drive
2. right click there

### Files Version

3.8

### Windows Version

10.0.22631.4541

### User ID

96a498d2-7152-4a22-8212-8e8ad62fdeb1

### Log File

[debug.log](https://github.com/user-attachments/files/17950668/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in https://github.com/files-community/Files/issues/16499. You can check there or click subscribe in the right sidebar for updates.
