### ISSUE TITLE
Feature:Add shortcut key function for editing file tags

### ISSUE THREAD

**Issue by EricWONGEric** [files-community/Files#16540]
### What feature or improvement do you think would benefit Files?

I hope to add shortcut keys for editing file labels and label prompts for drives that are currently only compatible with NTFS format. I also hope to increase support for exFAT format drives.

### Requirements

1. I hope to add shortcut keys for editing file labels and label prompts for drives that are currently only compatible with NTFS format. 
2. I also hope to increase support for exFAT format drives

### Files Version

3.8.0.0

### Windows Version

10.0.19045.5131

**Comment by yaira2** [comment]
Thank you for your feedback. We're currently tracking this under #15272. Feel free to add a comment or subscribe to that issue to be notified of any changes.
