### ISSUE TITLE
Bug: Tag widget is not updated when tags are edited

### ISSUE THREAD

**Issue by ferrariofilippo** [files-community/Files#16541]
### Description

Tags in the home page widget are not updated when they are edited.
Refreshing the page or opening a new tab doesn't solve the issue.

https://github.com/user-attachments/assets/b20c26ed-b8b9-466b-a020-64cdffa6107f

### Steps To Reproduce

1. Open the `Home` page
2. Open `Settings/Tags`
3. Edit and/or remove tags
4. Close the dialog and see that the widget has not been updated 
5. See that refreshing the page or opening a new tab won't solve the issue

### Files Version

3.8.0.0

### Windows Version

10.0.22631.4541

### User ID

8467f272-08cd-4a50-93e0-39458990bdc4

### Log File

Not relevant

**Comment by 0x5bfa** [comment]
Yeah we need huge overhaul in tags service. We should do the same as Recent Files (and Tags settings service has over-responsibility rn), I did the same for Quick Access in my PR. The refresh button also doesn't work for now but there's an idea for this after we finished overhauling the services regarding the widgets.

**Comment by Josh65-2201** [comment]
We're tracking this in #6182
