### ISSUE TITLE
Bug: Files crashes

### ISSUE THREAD

**Issue by szebegyi** [files-community/Files#16543]
### Description

After a while Files regularly crashes

### Steps To Reproduce

file selection changes

### Files Version

3.8.0.0

### Windows Version

10.0.19045.5131

### User ID

2327550f-33aa-469b-9e74-13445e325480

### Log File

[debug.log](https://github.com/user-attachments/files/17947133/debug.log)

**Comment by madixo** [comment]
Do you have a preview pane open by any chance?

**Comment by Josh65-2201** [comment]
Thanks for the report, The log doesn't show any crash
- Can you type Event Viewer into the Windows start menu search > Click Windows logs > Click Application > Screenshot any errors that have Files.exe shown on the first line
- Can you give steps to reproduce or what you where doing when it crashed

**Comment by abdulrahim-ss** [comment]
Hi!
I have the same issue, it crashes quite often. Here's the log screenshot for the crash event:
![Image](https://github.com/user-attachments/assets/7a197ba0-010d-48ac-99ae-5d083201f257)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #16226. You can check there or click subscribe in the right sidebar for updates.
