### ISSUE TITLE
 Compatibility with Desktop

### ISSUE THREAD

**Issue by seohyun1108** [files-community/Files#1655]
**Describe the bug**
I can't copy and paste or do other tasks between Files UWP and Desktop.

**Expected behaviour**
make Compatible with Desktop, please

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 21H1 20180]
 - App version: [v0.12.0]

**Comment by yaichenbaum** [comment]
@seohyun1108 Is this still an issue in v0.17?
