### ISSUE TITLE
Bug: Changes don't save in Security tab

### ISSUE THREAD

**Issue by iTsMike78** [files-community/Files#16553]
### Description

Does not save changes made in the Security tab settings.

### Steps To Reproduce

Right click on any file
Select open properties
Select security tab
Select your username in groups or user names section

Changes don't save in Permissions for 'YourName'

### Files Version

3.8.0.0

### Windows Version

10.0.26100.2314

### User ID

af44b7f8-7db4-4cfa-b50c-eed1a7ecfce6

### Log File

[debug.log](https://github.com/user-attachments/files/17966377/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #11549, #11550 and #11551 . You can check there or click subscribe in the right sidebar for updates.
