### ISSUE TITLE
Bug: Auto refresh does not work on network shares

### ISSUE THREAD

**Issue by morm24** [files-community/Files#16555]
### Description

So I started using files in my company environment because of the "split area" feature. 
We are mainly using network shares as drive spaces and hardly use any build in storage. 
When copying/creating files / folders on a network share, I have to refresh with F5/the refresh button on the top left, to see the created/copied/moved item in the explorer window. 
The wished behaviour, auto refreshing the explorer, works fine in storage connected directly to my pc e.g. M.2. (didnt try sata, but should be same behaviour). Also normal windows explorer works fine either with "offline" and network drives.

### Steps To Reproduce

1. connect Network dirve to your windows
2. move/copy/create File or folder 
3. Item is not shown in the "explorer" view
4. refresh to show Item 

### Files Version

3.7.11.0

### Windows Version

19045.4894

### Log File

[debug.log](https://github.com/user-attachments/files/17988393/debug.log)

**Comment by morm24** [comment]
Ok, seems like my first issue search wasn't good. There is already an issue with a similar Problem: 
https://github.com/files-community/Files/issues/5869
imo it's odd, that this isn't fixed after three years.

**Comment by yaira2** [comment]
> Ok, seems like my first issue search wasn't good. There is already an issue with a similar Problem:

GitHub issue search can be hard to use, don't worry about it...

As mentioned, we're currently tracking this in #5869. Some of the challenges involved are also mentioned there.
