### ISSUE TITLE
Bug: Files start crashing after a few days of normal use

### ISSUE THREAD

**Issue by leafpmpmp** [files-community/Files#16554]
### Description

I updated Files to v3.8 a week ago, and was using it just fine. Today it just started to crash randomly and constantly.
I can't see anything weird in the log file, but here's the error from the event viewer. All four crashes are logged properly(all the same).
![Image](https://github.com/user-attachments/assets/65d5aad1-0b70-46e7-984d-2b3d900bd913)

### Steps To Reproduce

1. Open Files
2. Do anything, from navigating between folders to copy and paste files, or open some files.
3. It may crash ( My Files crash any% record was about 30 seconds)

### Files Version

3.8

### Windows Version

10.0.22631.4541

### User ID

96a498d2-7152-4a22-8212-8e8ad62fdeb1

### Log File

[debug.log](https://github.com/user-attachments/files/17980083/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, We're tracking this in #16378. You can check there or click subscribe in the right sidebar for updates.
