### ISSUE TITLE
Bug: When batch selecting file (holding left mouse button), the scroll wheel does not work.

### ISSUE THREAD

**Issue by HD6630M** [files-community/Files#16568]
### Description

I want to select a few files, and when I want to hold down the left mouse button and drag out a box, the mouse wheel becomes unresponsive and I can only move the pointer to the edge of the window to scroll.

### Steps To Reproduce

Launch the app
Go to a random folder that contains a list of files longer than the window height
Select several files by holding down the left mouse button
Scroll the mouse wheel up/down
Scroll wheel does not respond

### Files Version

3.8.0.0

### Windows Version

10.0.22631.4541

### User ID

e026b727-8550-4980-859e-05c46a0e415e

### Log File

[debug.log](https://github.com/user-attachments/files/18032008/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #14313. You can check there or click subscribe in the right sidebar for updates.
