### ISSUE TITLE
外部调起Files略显迟缓

### ISSUE THREAD

**Issue by ouyang7923** [files-community/Files#16561]
### What feature or improvement do you think would benefit Files?

files已设置接管文件管理，比如浏览器下载文件后点击打开，会触发打开files软件，此过程等待时间略长略显迟缓。

### Requirements

在files内部右键 在新标签中打开 则是相对更快的。帮忙看看还有没有优化空间

### Files Version

3.8.0.0

### Windows Version

10.0.22631.4541

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Are you talking about Files opening or making a new tab?

**Comment by ajtn123** [comment]
> ### What feature or improvement do you think would benefit Files?
> 
> files已设置接管文件管理，比如浏览器下载文件后点击打开，会触发打开files软件，此过程等待时间略长略显迟缓。

“_Files_ has been set to be the default file explorer. For example, clicking to open a downloaded file in an internet browser will trigger to open _Files_, but the opening process seems to be slow and unresponsive.”

> ### Requirements
> 
> 在files内部右键 在新标签中打开 则是相对更快的。帮忙看看还有没有优化空间

“In contrast, opening a new tab in an existing _Files_ window is relatively faster. Is there any space for Optimizations?”

Just a translation. It would be difficult to optimize this process. However, turn on the `Leave app running in the background` option in settings may help a little if haven’t already.

**Comment by yaira2** [comment]
Thank you for your feedback! We're continuously working on performance improvements. You can follow our progress in issue #4180.
