### ISSUE TITLE
Bug: Abnormal scrollbar and right-click in list mode cause program crash

### ISSUE THREAD

**Issue by aipman** [files-community/Files#16560]
### Description

In list mode, if there are too many layers of nested folders opened, resulting in a scrollbar that exceeds the screen width, selecting from the opened subfolders will cause the scrollbar to scroll abnormally, and right clicking will cause the program to crash.

### Steps To Reproduce

1. Enable list mode
2. Open multi-layer folder
3. Drag and select files in the innermost folder
4. Abnormal scrolling of the scrollbar,Automatically scroll to the left end
5. Right click on a blank folder or file
6. Collapse occurs

### Files Version

3.8.0.0

### Windows Version

10.0.27754.1000

### User ID

37854118-12d7-490a-bbd7-e52b395975fc

### Log File

[debug.log](https://github.com/user-attachments/files/18015699/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you send a screen recording of the issue

**Comment by yaira2** [comment]
@aipman are you refering to the Column View layout?

**Comment by aipman** [comment]
> Thanks for the report, can you send a screen recording of the issue

I just updated to version 3.8.1.0, but the issue still persists.
