### ISSUE TITLE
Bug: App is crashing

### ISSUE THREAD

**Issue by typografika-print** [files-community/Files#16562]
### Description

When i open the app, it wont stay open no more than 1 or 2 minutes. Tried in two different machines with the same result. 

### Steps To Reproduce

open the app

### Files Version

3.8

### Windows Version

win 10

### User ID

ef891f2a-ba20-405a-a246-3271c2245a72

### Log File

[debug.log](https://github.com/user-attachments/files/18024061/debug.log)
[filetags.json](https://github.com/user-attachments/files/18024315/filetags.json)
[user_settings.json](https://github.com/user-attachments/files/18024316/user_settings.json)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you type Event Viewer into the Windows start menu search > Click Windows logs > Click Application > Screenshot any errors that have Files.exe shown on the first line

**Comment by typografika-print** [comment]
![Image](https://github.com/user-attachments/assets/40bec438-a525-4d2b-bbda-0fa65dcbfef3)
![Image](https://github.com/user-attachments/assets/d8b0c723-f983-4b26-b20e-2b0e3b5530c9)

**Comment by typografika-print** [comment]
![Image](https://github.com/user-attachments/assets/f46e1427-468a-4078-ac37-bbaddedbd11f)

**Comment by Josh65-2201** [comment]
Thanks, We're tracking this in #16226. You can check there or click subscribe in the right sidebar for updates.
