### ISSUE TITLE
Bug: App crashes when previewing PDFs in the Preview Pane

### ISSUE THREAD

**Issue by Lockframe** [files-community/Files#16574]
### Description

Previewing any PDF file through the Preview Bane causes Files to crash, either immediately after alternating between the details and preview tabs, or after the window loses focus.

This does not happen with any other file format I've tried.

Restarting Files does not affect this issue.

https://github.com/user-attachments/assets/6f6b3070-5ef9-4b17-b178-652a66d61de1

### Steps To Reproduce

1. Open Files
2. Select any PDF file and open the preview pane
3. Alternate between the details and the preview tab

### Files Version

3.8.0.0

### Windows Version

Windows 11 Pro 23H2 22631.4460 Windows Feature Experience Pack 1000.22700.1047.0

### Log File

[debug.log](https://github.com/user-attachments/files/18048883/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #16226. You can check there or click subscribe in the right sidebar for updates.
