### ISSUE TITLE
Bug: Cannot drag and drop files in to Adobe Lightroom Classic

### ISSUE THREAD

**Issue by psiongraham** [files-community/Files#16573]
### Description

Adobe Lightroom Classic supports the dragging and dropping of files in the Library module to import files. However, Files does not seem to allow this. When I drag a file to import, the cursor changes to an arrow with the text "Move", but when released it does nothing. In Windows Explorer this works fine.

### Steps To Reproduce

Open Adobe Lightroom
Open Files
Navigate to folder containing images
Drag image file(s) from Files window over to Adobe Lightroom Library window in large thumbnails area in centre of window
Release mouse.

### Files Version

3.8.0.0

### Windows Version

10.0.26100.2454

### User ID

8be43ceb-5105-4b04-80ea-fd633fff6ed1

### Log File

[debug.log](https://github.com/user-attachments/files/18048529/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #11735. You can check there or click subscribe in the right sidebar for updates.
