### ISSUE TITLE
Context menu:  "Open" does not appear for folder shortcut

### ISSUE THREAD

**Issue by Rick-HM** [files-community/Files#1657]
![Anotación 2020-08-05 170128](https://user-images.githubusercontent.com/61259627/89463853-7db1c280-d73d-11ea-895a-a23606942270.png)

**Comment by BanCrash** [comment]
This issue seems to be solved (Open = Abrir).

![image](https://user-images.githubusercontent.com/11770760/131905838-883adc61-d80d-46a3-af64-86267d420608.png)

**Comment by BanCrash** [comment]
@yaichenbaum
