### ISSUE TITLE
Feature: Hide toolbar when in homepage

### ISSUE THREAD

**Issue by Lamparter** [files-community/Files#16577]
### What feature or improvement do you think would benefit Files?

Currently, the toolbar displays "home" when in the homepage:

![Image](https://github.com/user-attachments/assets/c6e3e76c-78ee-4fb5-a7d4-eff75c271966)

This isn't really necessary as "Home" is already displayed in the address bar and also the side pane. The toolbar should be hidden when inside the homepage for maximum UI simplicity

### Requirements

- Hide toolbar when in homepage

### Files Version

3.8.1.0

### Windows Version

10.0.22631.4541

**Comment by 0x5bfa** [comment]
I think we've got a plan to add Copy and drive operation commands there. What's the plan around here @yaira2?

**Comment by yaira2** [comment]
We're going to move forward with this
