### ISSUE TITLE
Feature: Add option to display full path in title

### ISSUE THREAD

**Issue by alexander-clarke** [files-community/Files#16571]
### What feature or improvement do you think would benefit Files?

I want an option to display the full path in the title, instead of just the name of the current folder.
This is an option which exists in the windows file explorer

Use cases:
I use external software (https://talonvoice.com/) with reads the title in order to provide contextual actions. Currently this cannot work with the application
If you had two same named folders in different paths when alt tabbing currently you can't see between which one is which

Related to: #8316 (requested this feature aswell), #14175 

### Requirements

- This feature will add the option to display full path in title

### Files Version

3.8.0.0

### Windows Version

10.0.22631.4460

**Comment by yaira2** [comment]
Thank you for your feedback! Currently, we don't plan to display the full path in the tabs. However, we're addressing the underlying issue you've mentioned in #14175 to better handle multiple tabs with the same title.

**Comment by alexander-clarke** [comment]
Thanks for the response! I do want to point out though that #14175 is relating to tab title which is not necessarily the window/application title.

**Comment by yaira2** [comment]
Files doesn't display a title on the window, only on the taskbar.
