### ISSUE TITLE
Feature: Add custom applications to first context menu

### ISSUE THREAD

**Issue by JackSparrow006** [files-community/Files#16575]
### What feature or improvement do you think would benefit Files?

Use Case:
I need the ability to customize the "Open with" context menu to prioritize Notepad++ and remove the default Notepad option, while ensuring compatibility with PowerToys Peek -since this is also not working, both, are updated. This would streamline my workflow as Notepad++ is my primary text editor, and I want to maintain quick preview functionality while customizing my context menu options.

### Requirements

Requirements:

1. Add ability to customize the right-click context menu options
2. Allow users to add third-party applications (like Notepad++) to the main context menu
3. Enable reordering of context menu items to prioritize frequently used applications
4. Provide option to hide or remove default applications (like Notepad) from the menu
5. Maintain full compatibility with PowerToys Peek functionality (SHIFT + SPACEBAR preview)
6. Persist custom context menu settings across sessions
7. Include a reset option to restore default context menu settings

### Files Version

V3.8

### Windows Version

23H2

### Comments

Additional Information:
This improvement would enhance productivity by reducing the number of clicks needed to open files in preferred applications, while preserving the quick preview functionality of PowerToys Peek. Many users rely on alternative text editors and would benefit from the ability to customize their context menu to match their workflow, especially when used in conjunction with PowerToys features.

**Comment by yaira2** [comment]
Thank you for your feedback. You can display shell extensions in the main menu by turning off the setting to move them to a sub menu. Support for customizing shell extensions directly from Files is being tracked in issue #13463.
