### ISSUE TITLE
Feature: Display even amount of recommended files in homepage

### ISSUE THREAD

**Issue by Lamparter** [files-community/Files#16578]
### What feature or improvement do you think would benefit Files?

A tiny thing that just bugs me in the back of my head, and that's that the recommended items appearing under Quick Access in the homepage aren't always even.

![Image](https://github.com/user-attachments/assets/a1e28336-a65e-4b37-8b77-75446cabf2bd)

> that one extra folder named "Assignment" appears

Even when resizing the window, the cards don't reorganise.

![Image](https://github.com/user-attachments/assets/07cd59b1-23dd-4c9e-8404-bc27ebb5a19d)

### Requirements

- Limit the cards to display only an even amount of recommended items

### Files Version

3.8.1.0

### Windows Version

10.0.22631.4541

**Comment by yaira2** [comment]
I understand that it can be a bit annoying when the items under Quick Access aren't even. However, the number of displayed items depends not only on the recent folders (which happens to be an even number), but also on the pinned folders. To maintain an even number of items, I recommend having an even number of pinned folders. If we were to change the behavior to display only three recent folders, it would introduce inconsistency and limit functionality.
