### ISSUE TITLE
Feature: Add support for Lucid Link v3+

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#16586]
### What feature or improvement do you think would benefit Files?

They have updated the file structure and no longer give a path for the cloud spaces in v3.

### Requirements

- Search `C:/Volumes` and find all system link paths to display as Lucid link drives this would work for v2 and v3 clients

### Files Version

3.8.1.0

### Windows Version

10.0.26100.2314

**Comment by Lamparter** [comment]
What would the symlinks be called?

**Comment by Josh65-2201** [comment]
It's based on what the user enters as a name, problem is the developers don't put that name anywhere in the files for v3 as far as I can see.

**Comment by Lamparter** [comment]
So how are you meant to be able to tell whether it's a LucidLink drive or not?

**Comment by Josh65-2201** [comment]
If someone puts their own system link in the `C:\Volumes` then we couldn't but I don't see that accidentally happening.

**Comment by yaira2** [comment]
Can there be multiple folders under `volumes`?

**Comment by Josh65-2201** [comment]
Yes it a folder per workspace that contains a system link per file space

**Comment by yaira2** [comment]
So there can be multiple workspace folders and multiple file space folders?

**Comment by Josh65-2201** [comment]
Yes
