### ISSUE TITLE
Code Quality: Files is still using 7z 21.01 Alpha

### ISSUE THREAD

**Issue by Pinguin2001** [files-community/Files#16581]
### Description

Files uses an outdated version of 7-zip is vulnerable and the dependency should be updated

### Concerned code

src/Files.App/7z.dll
src/Files.App/7z64.dll
src/Files.App/7zArm64.dll

### Gains

- Address recently surfaced 7-zip CVE

### Requirements

- Replace all three dlls with their latest version

**Comment by yaira2** [comment]
Thank you. Do you know the easiest way to find the most up to date dlls?

**Comment by Pinguin2001** [comment]
> Thank you. Do you know the easiest way to find the most up to date dlls?

I downloaded them from the official website(https://7-zip.de/download.html) and replaced them manually.

**Comment by yaira2** [comment]
Resolved with #16585
