### ISSUE TITLE
Feature: Eject Context Menu option for mounted VHDs

### ISSUE THREAD

**Issue by jmarshall90** [files-community/Files#16590]
### What feature or improvement do you think would benefit Files?

Need eject button for mounted drives. There is an option to mount VHDs but no option to eject/unmount them

### Requirements

- This proposal will keep me from having to go to the normal file explorer to unmount the drive

### Files Version

3.8.0.0

### Windows Version

10.0.26100.2454

### Comments

Loving the app overall though. nice work

**Comment by yaira2** [comment]
Thank you for your feedback, can you confirm if this is the same as #10154?

**Comment by jmarshall90** [comment]
Yes, this is the issue I'm having

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
