### ISSUE TITLE
Bug: serious lag at startup

### ISSUE THREAD

**Issue by whes1015** [files-community/Files#16599]
### Description

https://github.com/user-attachments/assets/17978a04-0dcc-4467-8a20-71a56d07a71e

### Steps To Reproduce

1. Open the Files

### Files Version

3.8.0.0

### Windows Version

22631.4460

### User ID

5f94dc44-df39-42c2-b6c0-13aed9a247ab

### Log File

[debug.log](https://github.com/user-attachments/files/18102105/debug.log)

**Comment by yaira2** [comment]
Is this every launch, or just the first one?

**Comment by whes1015** [comment]
> Is this every launch, or just the first one?

Every launch,there is a second startup in the video.

**Comment by yaira2** [comment]
You can work around this by enabling the option to keep Files open in the background, however, we're also tracking performance for a cold start in #4180.

**Comment by whes1015** [comment]
> You can work around this by enabling the option to keep Files open in the background, however, we're also tracking performance for a cold start in [#4180](https://github.com/files-community/Files/issues/4180).

There will still be problems

**Comment by whes1015** [comment]
https://github.com/user-attachments/assets/06f59498-c906-443c-97a8-434613a0ef7c

**Comment by whes1015** [comment]
The entire window seems to be frozen, and I can't even drag the window position.

**Comment by yaira2** [comment]
It doesn't look like the option is working correctly, try running `taskkill -f -im files.exe` and testing again.

**Comment by whes1015** [comment]
> taskkill -f -im files.exe

thx
