### ISSUE TITLE
Add a settings page to customize keyboard shortcuts

### ISSUE THREAD

**Issue by Rick-HM** [files-community/Files#1660]
**Concept**:

![89137108-d1859700-d504-11ea-8516-eac9c3e33027](https://user-images.githubusercontent.com/61259627/89478376-d3966280-d75d-11ea-8d2f-d26bc1cb6ddc.png) ![89137066-9e430800-d504-11ea-82f1-7641b23c9998](https://user-images.githubusercontent.com/61259627/89478381-d5f8bc80-d75d-11ea-85fa-3c10bddac697.png)

**Comment by gabrieldelaparra** [comment]
I find this one cool. Would it be possible to include a launcher ? As in the launcher (Ctrl+Shift+P) in VSCode?

**Comment by yaichenbaum** [comment]
@gabrieldelaparra Someone just opened an issue for that over here #2780.

**Comment by yaichenbaum** [comment]
@XPoppyX Which keyboard shortcuts do you want to remap? We are trying to see how this feature would be used.

**Comment by XPoppyX** [comment]
That is something that other users must answer, I opened this feature request based on another one with a concept that I commented on how the design of the keyboard shortcut page could be, and I added that of being able to remap as an extra that surely others would be interested

**Comment by Josh-65** [comment]
Merging with #9559

**Comment by yaira2** [comment]
@Rick-HM this feature will be included in the next release. Please see #9559 for more details.
