### ISSUE TITLE
Feature:

### ISSUE THREAD

**Issue by Minus10Celcius** [files-community/Files#16604]
### What feature or improvement do you think would benefit Files?

I sometimes put .ico files to customize my file explorer, but it can be exhausting to put .ico files over and over. Can we put a default file and/or .ico file and add a mass apply .ico?

### Requirements

- **Default icon files**

You can put a setting to add your .ico file in "Appearance" or "Files and Folders"

- **Mass apply .ico files**

You can add a checkbox for the files and go to "Properties" > "Customize"

### Files Version

3.8.0.0

### Windows Version

10.0.22631.4602

**Comment by yaira2** [comment]
Thank you for your feedback, can you confirm if this is the same as #10941?

**Comment by Minus10Celcius** [comment]
> Thank you for your feedback, can you confirm if this is the same as [#10941](https://github.com/files-community/Files/issues/10941)?

Yeah, I think it's the same 😅

**Comment by yaira2** [comment]
Let's continue tracking in #10941.
