### ISSUE TITLE
Feature: Set the right-click menu to the system default

### ISSUE THREAD

**Issue by zhishidangao1020** [files-community/Files#16607]
### What feature or improvement do you think would benefit Files?

More customizable right-click menu

### Requirements

-Can be set as system default
-Can check the required options from the system default menu
-When you right-click and drag an item, you can choose to move or copy it to the current location

### Files Version

3.8.1.0

### Windows Version

Windows 11 Professional 24H2
Operating System Version 26100.2605
Experience Windows Feature Experience Pack 1000.26100.36.0

**Comment by xsm2** [comment]
> Thank you so much for your feedback! While we could technically display the File Explorer context menu, it wouldn't provide the best experience. For example, menu options like changing the layout, copying, pasting, creating new files, viewing properties, and sorting are all linked to File Explorer and wouldn't have any effect if used in Files. Plus, there are many unique features in the Files context menu that you won't find in File Explorer. If there's a specific feature you're missing, please feel free to open a feature request, and we'll be happy to take a look!

I understand that the default context menu will not provide the best experience, but it will enable it's replacement with something like [Nilesoft Shell ](https://github.com/moudey/Shell) which is faster and more customizable, and it lets you hide any option that doesn't work
