### ISSUE TITLE
Bug: 最新版无法拖拽文件

### ISSUE THREAD

**Issue by HeavenCui** [files-community/Files#16600]
### Description

拖拽文件或文件夹毫无反应，桌面上的文件也无法拖进APP。

顺便建议，可否增加横向书签栏布局？侧边栏也可以当书签栏但多一种选择也挺好。

### Steps To Reproduce

公司电脑，不方便录视频等操作。

### Files Version

3.8.0.0

### Windows Version

Windows 11 企业版 LTSC 2024 26100.1742

### Log File

因为影响使用已经暂时卸载，忘了要这个了。。。

**Comment by HeavenCui** [comment]
所有的都不行。从里往外，从外往里，Files内部拖拽都不行。鼠标点击并长按之后连文件被选定的焦点都没有。

**Comment by HeavenCui** [comment]
[debug.log](https://github.com/user-attachments/files/18119235/debug.log)

重新安装了，问题依旧。上传了log。

**Comment by Josh65-2201** [comment]
It seems like you are running Files as admin or have UAC (User Account Control) off. Please type `uac` into Windows search > Set the slider to 3rd or above level from the bottom > Restart Windows.

**Comment by HeavenCui** [comment]
可以用了。谢谢。

**Comment by xweier** [comment]
> 看来您正在以管理员身份运行“文件”或已关闭 UAC（用户帐户控制）。请`uac`在 Windows 搜索中输入 > 将滑块移至倒数第三级或以上 > 重启 Windows。

https://meee.com.tw/LakPJdb

请问是这样吗？

**Comment by Josh65-2201** [comment]
That correct if that's what you mean. If not please give more details
