### ISSUE TITLE
Bug: Sidebar Items Vanish

### ISSUE THREAD

**Issue by McMacabre** [files-community/Files#16605]
### Description

Very often, perhaps once a day, a few to most, sometimes even all, the shortcut items in the sidebar vanish. The only way to fix this bug seems to open up two tabs in one window, and drag the second tab to create a new window, which forces the explorer to restart and reset the sidebar.

I should note that I've set Files as the default file manager (perhaps this is causing an issue?)

### Steps To Reproduce

1. Open Files (bug randomly occurs)
2. Sidebar Shortcuts missing
3. Open a folder in a new tab in the same window
4. Drag the second tab out of window, into it's own window
5. Files resets, and all the Sidebar Shortcut appear again

### Files Version

3.8.0.0

### Windows Version

10.0.22631.4602

### User ID

f85ac294-de92-4e3f-9551-7c5679b7784d

### Log File

[debug.log](https://github.com/user-attachments/files/18137808/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, do you mean just the pins or all items?

**Comment by McMacabre** [comment]
It's pretty inconsistent.

Sometimes it will be every shortcut, other than my pinned shortcut items (under the pinned section). Other times it's everything, this includes Drives, Libraries, Cloud Drives, etc. including the Pinned section, leaving "Home" as the only item in the sidebar. Don't know what could be triggering it.

**Comment by Josh65-2201** [comment]
Thanks for the Information, can you turn off `Files settings > Advanced > Leave app running in the background` then close and reopen Files

**Comment by McMacabre** [comment]
That seems to fix the problem because it launches a new initialization each time. However, now it's no longer as fast to open up.

**Comment by Josh65-2201** [comment]
We're tracking a fix for this in #15410. You can check there or click subscribe in the right sidebar for updates.

**Comment by McMacabre** [comment]
Thanks, will keep an eye out for a fix
