### ISSUE TITLE
Bug: Files launcher opens splash screen but gets stuck

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#16619]
### Description

It seems this has been removed in favor of separate branch but the launcher hasn't been updated to use them.

### Steps To Reproduce

1. Enable Files settings > Advanced > Set as default
2. Try open Files with Win + E
3. See a prompt to select what files-uwp opens (Preview won't be an option)

### Files Version

3.8.2.0

### Windows Version

10.0.26100.2605

### User ID

3372b393-b294-495c-9814-4e5b48d9fd8d

### Log File

[debug.log](https://github.com/user-attachments/files/18202353/debug.log)

**Comment by yaira2** [comment]
This is resolved in `main`.

**Comment by yaira2** [comment]
The underlying issue is that the launcher project isn't being compiled after the CI modifies the branch.
