### ISSUE TITLE
Feature: Make it optional to use the background transparency optimizations.

### ISSUE THREAD

**Issue by dedestem** [files-community/Files#16615]
### What feature or improvement do you think would benefit Files?

Hello,
The background transparency theme looks really good however when the window gets unfocused it gets disabled and goes to 0 opacity ):

I understand that this is for performance reasons on low end devices but on my main rig it is fine and looks nice.
Please make an toggle under it like

Disable theme optimizations when the window gets unfocused.

Thank you.

### Requirements

 - Toggle in settings
 - IF statement

### Files Version

3.8.0.0

### Windows Version

10.0.26100.2605

**Comment by yaira2** [comment]
This behavior is controlled by Windows, and not something we have direct control over in Files. Officially, it's designed this way for optimization purposes and to ensure that the focused window receives the user's attention. I suggest submitting this feedback directly to Microsoft via Feedback Hub or on the WinUI GitHub repo.

**Comment by dedestem** [comment]
Okay
