### ISSUE TITLE
Bug: Transparent Menus barely legible

### ISSUE THREAD

**Issue by granterogers** [files-community/Files#16614]
### Description

The context menu transparency is high that I cannot read the content of the menu

![Image](https://github.com/user-attachments/assets/253ea527-7fdf-4448-9fdb-cad3d754fa21)
![Image](https://github.com/user-attachments/assets/bd67e7db-4665-4755-b549-342df1bda7b7)

I don't see any option to disable transparency, thank you.

### Steps To Reproduce

Right click, open context menu.

### Files Version

3.8.0.0

### Windows Version

10.0.26100.2605

### User ID

2a28f23f-bd03-438a-822c-a8fb1ed16cbb

### Log File

[debug.log](https://github.com/user-attachments/files/18170310/debug.log)

**Comment by yaira2** [comment]
This is a known issue that sometimes occurs with WinUI apps. The solution is to fully close and reopen the app.
