### ISSUE TITLE
Feature: File Drag & Drop Capability

### ISSUE THREAD

**Issue by welchwellbeing** [files-community/Files#16618]
### What feature or improvement do you think would benefit Files?

Hi!

Presently, I drag and drop video files from Windows Explorer into PowerDirector 365.

It appears I cannot drag and drop files from the Files app. 

Because I have to repeat this process around 30 times a week, it prevents me from making Files my default app. Is this a new feature, or something in my set up I can do to resolve?

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.8.0.0

### Windows Version

10.0.26100.2605

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Are you not able to drag and drop anything in Files or is it just when dropping to PowerDirector 365?

**Comment by welchwellbeing** [comment]
Hi, I really appreciate the reply.

Good question, so I had a little experiment. Here's the results:

Test 1: Drag and drop a mp4 from Files to Windows Explorer (Pass)
Test 2: Drag and drop a jpeg from Files to Canva Windows Client (Pass)
Test 3: Drag and drop mp4 from Windows Explorer to PowerDirector 365 (Pass)
Test 4: Drag and drop jpg from Windows Explorer to PowerDirector 365 (Pass),
Test 5: Drag and drop mp4 file from Files to PowerDirector (Fail)
Test 6: Drag and drop jpg from Files to PowerDirector 365 (Fail)
Screen capture shows the "stop symbol" that appears beside the jpg file being dragged over PowerDirector 365.
[cid:4E8ED5D8-757D-4FA9-A2D0-6CD5C9A11C19]
Thank you for your attention to this, I hope it helps.



Best regards, Lee
On Dec 20, 2024, 7:49 PM +0000, Josh65-2201 ***@***.***>, wrote:

Thanks for the feedback, Are you not able to drag and drop anything in Files or is it just when dropping to PowerDirector 365?

**Comment by welchwellbeing** [comment]
![Image](https://github.com/user-attachments/assets/1b6b4df0-5662-4c39-9e1e-c6f000885322)

**Comment by Josh65-2201** [comment]
Thanks for checking, We're tracking this in #11735. You can check there or click subscribe in the right sidebar for updates.

There is also a potential fix in #16628 when merged it will be available next update
