### ISSUE TITLE
Bug: Folder icon is not showing on Tiles and beyond but it shows in List layout

### ISSUE THREAD

**Issue by dhbtfs** [files-community/Files#16629]
### Description

Folders do not show their set icons in TIles layout but if I change it to List or small type folder size view, it shows up. 
I have even reset Files by deleting the userconfig file and still has this issue.

![Image](https://github.com/user-attachments/assets/0b9d4b49-ec28-4a3c-86ea-710186509e95)
![Image](https://github.com/user-attachments/assets/1f0b1b56-66e4-4985-849d-49e5ba6a281a)

### Steps To Reproduce

1. Make a folder and set an icon for it.
2. Put layout on Tiles, its not showing
3. Put layout on List, it shows up.

### Files Version

3.8.0.0

### Windows Version

10.0.22631.4602

### User ID

7e1c66f5-57d1-48d5-ac76-294a1bf498f0

### Log File

[debug.log](https://github.com/user-attachments/files/18216569/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, this is intended as it showing thumbnails. you can turn off Files settings > Files & Folders > Show thumbnails.

**Comment by dhbtfs** [comment]
@Josh65-2201 
That option seems unnecessary or it is incomplete.   
Turning off "Show Thumbnails" completely disables thumbnail previews for movie files and for folders that don’t have specific icons.   
Could we please have an option that allows us to keep thumbnails enabled while still displaying custom icons for folders that have specific icons assigned? OR separate this for folders entirely?
