### ISSUE TITLE
Bug: Files is not recognised correctly when opened from the command line with a relative path

### ISSUE THREAD

**Issue by sho9029** [files-community/Files#16624]
### Description

When invoking Files from the command line, relative paths are not recognized correctly when entered as arguments.

When running `start files-preview .\`, the expected behavior is that the current directory is opened, but it is not opened correctly.

### Steps To Reproduce

1. Run `start files-preview .\`

### Files Version

3.8.10.0

### Windows Version

10.0.26100.2605

### User ID

82ac0941-3dfe-4f9d-95f1-03fd3754e7ad

### Log File

[debug.log](https://github.com/user-attachments/files/18212400/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #14381. You can check there or click subscribe in the right sidebar for updates.
