### ISSUE TITLE
Bug: Selected item is partially hidden under column headings

### ISSUE THREAD

**Issue by howff** [files-community/Files#16625]
### Description

When trying to navigate to an item using the keyboard (possibly also in other circumstances) the desired item is hidden underneath the column headings:
![Image](https://github.com/user-attachments/assets/410d8790-87aa-4b09-98a0-06ce98091098)
(in this example I'm trying to get to Desktop)

### Steps To Reproduce

1. open folder
2. start typing
3. hidden

### Files Version

3.8.0.0

### Windows Version

11 24H2

### Log File

There's nothing in the log file

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #15955 . You can check there or click subscribe in the right sidebar for updates.

**Comment by howff** [comment]
Sorry for the duplicate issue (I didn't find it when searching).
