### ISSUE TITLE
Bug: Drag to apply tags doesn't work

### ISSUE THREAD

**Issue by AuroraStarstorm** [files-community/Files#16637]
### Description

According to: [https://files.community/docs/features/tags](https://files.community/docs/features/tags)

Assigning tags can be done via:

"Using drag and drop

    Select the items you wish to tag
    Drag and drop the items onto an existing tag in the sidebar"

However it seems to be bugged. I'm trying to do it with jpg and png files

### Steps To Reproduce

1. Grab an image file
2. Move it to the tag in the Tags section of the sidebar
3. The 🛇 symbol persists and dropping on tags does not assign the tag

### Files Version

3.8.0.0

### Windows Version

10.0.22631.4602

### User ID

ab67c9cf-ccbe-4a7f-95a3-0ad311a9fe5e

### Log File

[debug.log](https://github.com/user-attachments/files/18220310/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report.

**Comment by gave92** [comment]
![Image](https://github.com/user-attachments/assets/3f6f43e5-dd14-4ff6-9227-00863b4f245e)

It appears intentional :) guess we're missing the implementation.
