### ISSUE TITLE
Bug: Files cannot launch

### ISSUE THREAD

**Issue by sho9029** [files-community/Files#16632]
### Description

With the “Set Files as the default file manager” option enabled, when I try to start Files by “Win + E” or “Settings->About->Open log location” in Files, I get the following screenshot is displayed and it does not start.
![Image](https://github.com/user-attachments/assets/670ea8bf-1712-4d6e-9c8f-b1b1d110de8c)
Translation:
This application cannot be run on your PC
Check with your software publisher for the version of the app that can be used on this PC.

### Steps To Reproduce

1. Enable “Set Files as the default file manager” option
2. Win + E
3. Click “Settings->About->Open log location”

### Files Version

3.8.10.0

### Windows Version

10.0.26100.2605

### User ID

82ac0941-3dfe-4f9d-95f1-03fd3754e7ad

### Log File

[debug.log](https://github.com/user-attachments/files/18218527/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, You have to turn off Files settings > Advanced > Set as default, then reinstall Files and turn it on again.

**Comment by sho9029** [comment]
I tried it once and it didn't work out.

**Comment by Josh65-2201** [comment]
Did you reinstall files before turning it on again?

**Comment by sho9029** [comment]
I did it again and it worked.
I don't think I did the procedure wrong last time, but it worked this time anyway.
Thanks for the response.
