### ISSUE TITLE
Bug: List view shows shortened filenames with no way to show the full name

### ISSUE THREAD

**Issue by scotscoder** [files-community/Files#16634]
### Description

When viewing a folder in List view mode, the file and folder names are truncated due to the fixed width of columns used for this view, with no way to adjust the column width.  Windows Explorer, on the other hand, sets the column width to be the same as the longest filename without any truncation.

A setting is needed to allow the column size to automatically adapt to the longest filename, since that's kind of the point of a list view. 

### Steps To Reproduce

1.  Switch any folder's view mode to List
2.  See that longer file and folder names are truncated by an invisible and non-adjustable column boundary

### Files Version

3.8.0.0

### Windows Version

10.0.26100.2605

### User ID

ecf97199-f561-4b3e-b065-e3d9bda36c13

### Log File

Log isn't necessary since this isn't a crash report.

![Image](https://github.com/user-attachments/assets/54045716-07bb-48ea-a084-008fbed313ea)

**Comment by yaira2** [comment]
Thanks for the feedback, we're currently tracking this in #1033. You can check there or click subscribe in the right sidebar for updates.
