### ISSUE TITLE
Bug: Right-click on a file or folder in Column mode navigates BACK

### ISSUE THREAD

**Issue by SirClickALot** [files-community/Files#16630]
### Description

The Column display mode is indispensable in my view BUT, when you right-click on a file or folder, the view frequently scrolls back to the leftmost column! It does not ALWAYS do it, and sometimes it does it, then scrolls forward again and displays the context menu as desired.

### Steps To Reproduce

Set a view Column mode - mine is the default.
Navigate along to a fairly deeply embedded folder such that the horizontal scrolling takes place.
Locate a file and attempt to pop-up the context menu.
You'll see what happens, when it happens.

### Files Version

3.8.0.0

### Windows Version

10.0.22635.4655

### User ID

7a655b4b-4d4d-4809-8bec-f9c3d989c76c

### Log File

[debug.log](https://github.com/user-attachments/files/18217442/debug.log)

**Comment by 0x5bfa** [comment]
Thank you for the report.

We're aware of this frustrating issue and tracking this issue on in #15776. Please click Subscribe for the further information.
