### ISSUE TITLE
Feature: Add option to move file to specified path

### ISSUE THREAD

**Issue by Lamparter** [files-community/Files#16643]
### What feature or improvement do you think would benefit Files?

A context menu option should be created (and hidden by setting) to move the selected folder or file to a specified path. Pressing this button should open a content dialogue that allows the user to enter a path in the system to move the file to.

### Requirements

- Add action to context menu to move to specified path
  - Handle action being called with a content dialogue

### Files Version

`3.8.5.0`

### Windows Version

`10.0.22631.4391`

**Comment by yaira2** [comment]
Merging with #15981
