### ISSUE TITLE
Feature: Separate command palette and address bar

### ISSUE THREAD

**Issue by Lamparter** [files-community/Files#16644]
### What feature or improvement do you think would benefit Files?

Currently, the command palette is integrated with the address bar (invoked by entering `>` in the address bar). This proposal is to move the command palette to a new place, more like command palettes in other apps like GitHub and Discord.

![Image](https://github.com/user-attachments/assets/ebddaf6d-391a-459e-8cd3-e2ddfd2fa850)

The UI would look similar to the above, with a larger bar and a shade over the app and recommended areas to look in such as special locations, libraries and frequently/recently accessed locations.

### Requirements

- Plan UI implementation
- Implement command palette control with recommended locations (reusing Quick Access code)

### Files Version

`3.8.5.0`

### Windows Version

`10.0.22631.4391`

**Comment by yaira2** [comment]
Merging with #16029
