### ISSUE TITLE
Feature: Creating a file with a slash in its name should create a new folder

### ISSUE THREAD

**Issue by Lamparter** [files-community/Files#16647]
### What feature or improvement do you think would benefit Files?

Currently if you create a file with a slash in its name (e.g. `example/file.txt`) both Files and File Explorer report that such a name is invalid (files cannot contain slashes). The proposal is to allow slashes in file name creation, which instead creates a new directory - in the example, creating the text file would create a new directory named `example` with a file named `file.txt`)

### Requirements

- Detect if file name has a slash inside it during creation/rename
- Create new directory on demand

### Files Version

`3.8.5.0`

### Windows Version

`10.0.22631.4391`

### Comments

An extended implementation of this could be that putting `../` in the file name would place it in the previous directory.

**Comment by Josh65-2201** [comment]
Isn't this the same as #15745

**Comment by Lamparter** [comment]
Yes
