### ISSUE TITLE
Feature: Add a folder called `..` to easily navigate to previous directory

### ISSUE THREAD

**Issue by Lamparter** [files-community/Files#16648]
### What feature or improvement do you think would benefit Files?

This would be disabled by default, but an extra folder could be added to every directory called `..` that does the same as the navigate up action. This is a common feature of GitHub and many shells, and will make it easier to navigate for those who are used to it.

### Requirements

- Add folder called `..` to every folder tree that allows navigating back to the previous directory
  - This should be hidden at root folders like the root directory of a drive

### Files Version

`3.8.5.0`

### Windows Version

`10.0.22631.4391`

**Comment by yaira2** [comment]
We've implemented this behavior slightly differently, using a double-click gesture. While we could theoretically copy GitHub's approach, our current method works quite well.

**Comment by Lamparter** [comment]
This would be another alternative to that. The feature request is about implementing different ways to make Files more familiar for its wide audience.

**Comment by yaira2** [comment]
Unless there's a strong preference for one implementation over the other, we'd like to stick with a single approach instead of adding a setting. Plus, we already have a button in the address bar and a keyboard shortcut for quick access.
