### ISSUE TITLE
Feature: undo function

### ISSUE THREAD

**Issue by omarbey** [files-community/Files#16656]
### What feature or improvement do you think would benefit Files?

Double click the left mouse button to get the stretch feature

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.8.0.0

### Windows Version

10.0.22631.4602

**Comment by Josh65-2201** [comment]
Thanks for the feedback, you will have to add more Information on what you mean

**Comment by yaira2** [comment]
What do you mean by "stretch feature"?
