### ISSUE TITLE
Bug: Tag Color Inconsistency

### ISSUE THREAD

**Issue by MANTISoo7** [files-community/Files#16652]
### Description

The tags assigned to file in the file explorer exhibit inconsistent color coding. While the majority of tags are correctly color-coded, some entries deviate from the expected color scheme, creating confusion in categorization.

### Steps To Reproduce

1. In "Details" view.
2. Click sort by tags. (on 2 or more tags, i tested 3 tags)
3. ![Image](https://github.com/user-attachments/assets/5aceac30-b492-4c1f-9f57-46235724e11f)

### Files Version

3.8.0.0

### Windows Version

10.0.22631.4602

### User ID

639bed26-a7ce-4c31-97c1-4b31282bc40e

### Log File

[debug.log](https://github.com/user-attachments/files/18232078/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, This has already been fixed and will be available in the next update
