### ISSUE TITLE
Bug: при попытке открытия корзины вылазит ошибка: error not a folder

### ISSUE THREAD

**Issue by makokkordo** [files-community/Files#16655]
### Description

[](url)

### Steps To Reproduce

![Image](https://github.com/user-attachments/assets/c7130b03-954c-42e5-bed4-6a6de6b4122c)

### Files Version

3.8.0.0

### Windows Version

10.0.26100.2605

### User ID

894c4993-f6e7-4e9d-a79e-fa0a1915f42c

### Log File

Bug: при попытке открытия корзины вылазит ошибка: error not a folder

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #15083. You can check there or click subscribe in the right sidebar for updates.
