### ISSUE TITLE
Bug: Pinned folders disappear unexplained

### ISSUE THREAD

**Issue by CarlosRivera4726** [files-community/Files#16662]
### Description

When I'm working with Files, the pinned folders disappear unexplained and I need to close forcedly with task manager or new method for developers 'end task', I don't know hos to reproduce this bug.

this error makes it seem as if I have no anchored element, is more, disappears the arrow to show/hide the list items once restart with the task manager reappears

### Steps To Reproduce

before to reload the "files app"
![Image](https://github.com/user-attachments/assets/503eb70c-e550-49ce-8023-732b84ea35fa)

after reload with task manager:
![Image](https://github.com/user-attachments/assets/09541805-952c-418f-ade6-126d41e2d546)

### Files Version

3.8.0.0

### Windows Version

24H2 COMPILATION 26100.1591

### User ID

f3a85879-45a6-4b6d-935a-2b3e42c591a1

### Log File

[debug.log](https://github.com/user-attachments/files/18267940/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #15410. Please use the workaround there, you can check there or click subscribe in the right sidebar for updates.
