### ISSUE TITLE
Bug: When copying or moving files, the Status Centre progress dropdown shows 0b of 0b

### ISSUE THREAD

**Issue by scotscoder** [files-community/Files#16660]
### Description

When I copy or move files to an external flash drive, the progress dialogue does not show the amount of bytes being transferred or the remaining bytes remaining.

![Image](https://github.com/user-attachments/assets/a4440916-dba9-4a67-9cde-918f259ffdc5)

### Steps To Reproduce

1.  Drag file or folder to external flash drive
2.  Check the Status Centre dropdown
3.  See that no bytes are shown in the amount of transfer / amount remaining

### Files Version

3.8.0.0

### Windows Version

10.0.26100.2605

### User ID

ecf97199-f561-4b3e-b065-e3d9bda36c13

### Log File

No log required

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #16538. You can check there or click subscribe in the right sidebar for updates.
