### ISSUE TITLE
Show which app is preventing a file from being deleted

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#1681]
**Is your feature request related to a problem? Please describe.**
Not really. In File Explorer when you try to delete, rename or move a file that's being used by another process, it would show the process name as well along with an message. This could be useful at times when an unwanted process like a malicious application has locked your file. Files UWP currently only displays an message and doesn't show the process name of the process that locked it.

**Describe the solution you'd like**
We could show the process name in the dialog.

**Describe alternatives you've considered**
None.

**Additional context**
This is a bit tricky to implement but we could try to do this.

**Comment by yaichenbaum** [comment]
Merging with #5628

**Comment by gave92** [comment]
How to check for processes locking a file: https://stackoverflow.com/questions/317071/how-do-i-find-out-which-process-is-locking-a-file-using-net/317209#317209. Appears to work pretty well.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #8809
