### ISSUE TITLE
Compact overlay mode

### ISSUE THREAD

**Issue by winston-de** [files-community/Files#1691]
I think it would be great to have a compact overlay mode for the file browser, like the Windows calculator or Notepads app. This would make it much more convienient to quickly drag and drop files into a website or document. Some quick access options like "open folder in new compact window" or "open tab in new compact window" would also be nice. 

Grid view:
![FUWP CO GridView concept](https://user-images.githubusercontent.com/59544401/89745199-18c0da00-da67-11ea-9c6c-5f79784f4a39.png)

List view:
![FUWP CO List View concept](https://user-images.githubusercontent.com/59544401/89745201-1c546100-da67-11ea-948e-b5d61234dfe1.png)

**Comment by kleenkanteen** [comment]
What use case exactly do you have for this?

**Comment by winston-de** [comment]
Here's a couple I came up with.

1. User has a folder with some images they would like to add to a Word document. With this feature, they could keep Files on top of Word, and conveniently drag an image from Files into the word document when they need it
2. User is using Tablet Mode or Windows 10x, where windowing is limited to split screen, and would like to keep Files conveniently accessible
