### ISSUE TITLE
Change selected tab icon foreground to accent color

### ISSUE THREAD

**Issue by XPoppyX** [files-community/Files#1692]
![Anotación 2020-08-09 205433](https://user-images.githubusercontent.com/61259627/89745550-8dedd880-da82-11ea-960f-cc99d218ff64.png)

**Comment by tsvietOK** [comment]
![image](https://user-images.githubusercontent.com/20501502/89787930-06a67080-db27-11ea-84b0-cf8a9f0ba715.png)
It could be unreadable for some colors.

**Comment by XPoppyX** [comment]
the color change is for the icon, not the background

**Comment by tsvietOK** [comment]
Oops, sorry.
![image](https://user-images.githubusercontent.com/20501502/89793673-cfd45880-db2e-11ea-8242-fb46fe5e5951.png)
I think there is no sense in changing icon color.

**Comment by XPoppyX** [comment]
If the two tab states (selected and unfocused) have exactly the same color, users could still get confused with dark backgrounds  (and in dark mode), then the problem they mentioned about the user having trouble identifying which tab they are in is still unsolved.

But well, if you think that those things don't make sense, that's fine, I'll respect the decisions

**Comment by duke7553** [comment]
I think the selected tab is visible enough because of the other design features. Do we really need an accent colored icon here?

**Comment by generalguy41** [comment]
Could always make it an option in the Settings > Appearance pane. I do agree that on a dark background, it could be slightly difficult to tell which tab is active/selected:
![image](https://user-images.githubusercontent.com/8879244/90696469-51706880-e24a-11ea-9145-e366cd83a032.png)
I don't think it would hurt to at least add an option.

**Comment by duke7553** [comment]
Whenever I see accent color, I think something should be interacted with. The fact we might have different tabs with different icon colors would seem distracting. Looking back at this, I think we should focus more on improving the color palate to make the tabs more visible without use of accent color.

**Comment by duke7553** [comment]
@generalguy41 We've done work to improve the contrast here, and no longer think the accent colored tab icons would fit the design well. I'll close this now, but please keep the design feedback coming!
