### ISSUE TITLE
Increase the size of the touch target for the chevron on the Breadcrumb Bar levels

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#1695]

**Comment by mdtauk** [comment]
32 x 32 is the recommended target size as a minimum with WinUI - but if you wanted to differentiate between mouse or touch, then perhaps 24 x 32 may work.

As well as the larger hit target, you may also want to use a border or distinctive Hover state to improve confidence for the user when trying to tap or click it to display the folder list.

**Comment by Jaiganeshkumaran** [comment]
Not just for touch even with mouse it's difficult to select the small >.
