### ISSUE TITLE
App crashed and freezed when removing site which is opened on startup

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#1714]
[debug.txt](https://github.com/files-community/files-uwp/files/5063537/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/files-uwp/files/5063539/debug_fulltrust.txt)

**Comment by yaichenbaum** [comment]
@R3voA3 Is this still an issue in v0.21.1?

**Comment by R3voA3** [comment]
Unfortunately, yes.

[Uploading debug_fulltrust.txt…]()

**Comment by yaichenbaum** [comment]
@R3voA3 Can you share some steps to reproduce this issue?

**Comment by yaichenbaum** [comment]
We need a little more information from you in order to investigate this issue, please reopen this issue once you provided steps to reproduce this issue.
