### ISSUE TITLE
Files should switch to new tab when one is opened

### ISSUE THREAD

**Issue by generalguy41** [files-community/Files#1726]
**Is your feature request related to a problem? Please describe.**
Not related to a problem

**Describe the solution you'd like**
Files should automatically switch to the new tab when one is opened.

**Describe alternatives you've considered**
If not enabled by default, there should at least be an option in settings to enable it.

**Comment by yaichenbaum** [comment]
@soumyamahunt Can you confirm that you are still working on this?
