### ISSUE TITLE
Drag&Drop not working as intended

### ISSUE THREAD

**Issue by Duffy-y** [files-community/Files#1731]
**Is your feature request related to a problem? Please describe.**
Not related to a problem

**Describe the solution you'd like**
![video](https://user-images.githubusercontent.com/53657346/90161981-3e662000-dd94-11ea-89c0-98914c175c8a.gif)
![Capture](https://user-images.githubusercontent.com/53657346/90162259-ab79b580-dd94-11ea-8b7f-bb8a6b6d6ff9.PNG)

When I try to move the folder "test" inside another folder, I have to point the folder (C:\ in this case). But Files UWP should allow drag&drop inside the red box on the screenshot. 

**Additional context**
Windows 10 Version 1909, Files UWP 0.13.0.0

**Comment by Talisman39ar** [comment]
Drag and drop is now working for me with the latest version, thank you! But yes I have this same issue.
I usually like to try and drag into an open area if I can to avoid inadvertently dropping something into a folder (esp if it's nothing but folders shown in the list)

**Comment by Duffy-y** [comment]
I made an error, the drag&drop feature in the void is working in every view type except in list mode/view. 
Maybe the issue should swap to bug and not feature-request.
