### ISSUE TITLE
Files looks worse in high contrast themes

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#1753]
**Describe the bug**
Currently Files UWP doesn't work properly in high contrast themes and there are a lot of issues.

**To Reproduce**
1. Switch to any high-contrast theme
2. Open and use Files UWP
3. You'll notice that the design is inconsistent and worse

**Expected behavior**
App should look like any other app in high contrast themes.

**Screenshots**

![திரைப்பிடிப்பு (17)](https://user-images.githubusercontent.com/45227503/90478475-d07e7780-e14a-11ea-907b-8be85bb776a7.png)

![திரைப்பிடிப்பு (23)](https://user-images.githubusercontent.com/45227503/90478597-fb68cb80-e14a-11ea-8d89-14e84c95f614.png)

![திரைப்பிடிப்பு (22)](https://user-images.githubusercontent.com/45227503/90478581-f60b8100-e14a-11ea-8871-9d50b47a367c.png)

![திரைப்பிடிப்பு (21)](https://user-images.githubusercontent.com/45227503/90478565-ebe98280-e14a-11ea-9c91-5063438c8202.png)

![திரைப்பிடிப்பு (19)](https://user-images.githubusercontent.com/45227503/90478533-df652a00-e14a-11ea-91ba-c2d6aeb746f6.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Pro 20H1
 - App version: v0.13.0

**Comment by duke7553** [comment]
Thank you for creating this feedback item. A solution for it is currently being reviewed as a PR (pull request) to our active development branch. We'll let you know once it's merged.
