### ISSUE TITLE
Highlight folder when back button is pressed

### ISSUE THREAD

**Issue by Daksh777** [files-community/Files#1763]
**Is your feature request related to a problem? Please describe.**
When in the file explorer (windows default app), I open a folder and press backspace or the back button and go back, it highlights that opened folder. In this app, nothing is highlighted and the view is scrolled back up to the top.

**Describe the solution you'd like**
Highlight the folders when backspace or back button is pressed and scroll the view to it.

**Describe alternatives you've considered**
Windows file explorer?

**Additional context**
- OS Version: Windows 10 Pro 1909 18363.418
- App version: v0.13.1.0

**Comment by d2dyno1** [comment]
:eyes: hmmm....

**Comment by d2dyno1** [comment]
I'll :eyes: into that too

**Comment by yaichenbaum** [comment]
This issue should be resolved with #2499.

**Comment by Daksh777** [comment]
Amazing!
