### ISSUE TITLE
Show permanent deletion warning

### ISSUE THREAD

**Issue by X-Jackdaw** [files-community/Files#1768]
**Is your feature request related to a problem? Please describe.**
If I close the delete confirmation, the app will not confirm even if I delete a very big file or folder that cannot put it in the recycle bin. However, Windows explorer will warn you that this action will delete the file or folder permanently.

**Describe the solution you'd like**
When the file will be permanently deleted, I hope the app to warn the users regardless of whether the users turn on the delete confirmation.

**Comment by esibruti** [comment]
@yair100 I think we can close this

**Comment by yaichenbaum** [comment]
@esibruti this is still an issue in `main`.

**Comment by gave92** [comment]
Ugh on `main` you get the warning but then the file is deleted anyway.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5741.
