### ISSUE TITLE
Add support for View Alternate Data Streams

### ISSUE THREAD

**Issue by zbalkan** [files-community/Files#177]
I have been looking for ways to view Alternate Data Streams of NTFS in Explorer. I have used [Streams ](https://docs.microsoft.com/en-us/sysinternals/downloads/streams)from [Sysinternals ](https://docs.microsoft.com/en-us/sysinternals/) for CLI and [AlternateStreamView](https://www.nirsoft.net/utils/alternate_data_streams.html) from [NirSoft](https://www.nirsoft.net/) for UI. But I could not manage to do it in a proper way.

I'd like to have an alternative like "Show Hidden Files" but a "Show Alternate Data Streams" so that I can view them as casual files.

Although hidden files are shown with some transparency, alternate data streams can be shown as semitransparent like them but with some tricks like a different color in titles or any icon identifier like shortcuts does. That would be awesome.

**Comment by duke7553** [comment]
Unfortunately the current Windows.Storage APIs don't support displaying these yet. Keeping open for now while I investigate ways to work around this limitation.

**Comment by zbalkan** [comment]
I believe [AlphaFS](https://github.com/alphaleonis/AlphaFS) would suit better for all file system needs instead of System.IO and Windows.Storage in many cases. For future releases, that would probably accelerate your features.

**Comment by yaichenbaum** [comment]
@zbalkan does AlphaFS work with UWP applications?

**Comment by zbalkan** [comment]
@yair100 It's a drop in replacement for `System.IO`, so it won't be a problem, I assume. I have never used it with a UWP project.

**Comment by yaichenbaum** [comment]
It looks promising, @duke7553 can you investigate if this will work in a UWP app? If it does then we can solve many open issues by switching to this.

**Comment by zbalkan** [comment]
At this point, I believe "developing things that work" is better than "developing thing that does more". My feature suggestion may not be a must, but using AlphaFS might be helpful. I hope it would accelerate your efforts.

**Comment by Jaiganeshkumaran** [comment]
If it's not supported in UWP, we can use the full trust component similar to other features that aren't possible in UWP.

**Comment by gave92** [comment]
AlphaFS "works" in UWP but has all the same limitations as System.IO functions (AccessDenied everywhere).
For Alternate Data Streams we could use `FindFirstStreamW` in the fulltrust process to enumerate streams and than `OpenFileFromApp` from uwp *may* work to open them.

**Comment by duke7553** [comment]
@gave92 Do you mean `CreateFileFromApp`?

**Comment by Jaiganeshkumaran** [comment]
We should use CreateFile2 not CreateFileFromApp. According to the documentation, CreateFileFromApp is only available for Desktop apps that needs the security of UWP (eg: Packaged desktop apps.)

**Comment by gave92** [comment]
@Jaiganeshkumaran CreateFileFromApp should be available to UWP apps together with FindFirstFileExFromApp (which we're using), DeleteFileFromApp, MoveFileFromApp and others.
So once you get the list of ads using the fulltrust process you can do everything else in uwp maybe.

**Comment by Jaiganeshkumaran** [comment]
@gave92 The documentation is a little weird. The list of support Win32 APIs contains CreateFileFromApp but the API documentation says that it's desktop only. Maybe they haven't updated it.

**Comment by duke7553** [comment]
@Jaiganeshkumaran Indeed. I noticed with a lot of the FromApp APIs, they never categorized them as usable from a UWP app. They certainly are though.

**Comment by gave92** [comment]
Regarding support for shortcut files I think it's worth mentioning an alternative to using the fulltrust process which is using this library to directly parse the lnk file as binary in uwp -> https://github.com/EricZimmerman/Lnk

Since this is not "official" I would be more in favour of using the Win32 api in fulltrust process, but this is also viable

**Comment by Jaiganeshkumaran** [comment]
Regarding shortcuts, we can actually don’t need the full trust component since the Win32 APIs that we use do work for shortcut.

**Comment by gave92** [comment]
I was thinking about shortcuts to *folders*, we need to know the destination to navigate to it

**Comment by Jaiganeshkumaran** [comment]
@gave92 We can use the library you mentioned but everything can be done from UWP. No need to use the Full Trust component for enumerating shortcuts.

**Comment by gave92** [comment]
@Jaiganeshkumaran yeah for enumerating shortcuts we're good, I was thinking on what to do when the user tries to open one :)

**Comment by gave92** [comment]
Is anyone already working on this? If not I can start adding support for .lnk and .url shortcuts

**Comment by gave92** [comment]
@duke7553 could you remove my assignment on this issue? Support for shortcuts was introduced but I'm not currently working on the other features mentioned here. Thanks!

**Comment by yaichenbaum** [comment]
> @duke7553 could you remove my assignment on this issue? Support for shortcuts was introduced but I'm not currently working on the other features mentioned here. Thanks!

@gave92 Done. Thank you so much for your help with adding support for shortcuts.

**Comment by zbalkan** [comment]
If I get it right, the shortcuts can be used as of now. But accessing the Alternate Data Streams feature of NTFS is missing. Is it correct?

**Comment by Jaiganeshkumaran** [comment]
@zbalkan Yeah

**Comment by yaichenbaum** [comment]
@gave92 Can you confirm if all that's left to his issue is hidden items?

**Comment by gave92** [comment]
Alternate Data Streams as well
@yair100 not sure if this will solve #2104 which is about folder access permissions

**Comment by yaichenbaum** [comment]
Support for shortcuts and hidden items have been added to Files, we are still exploring ways to add support for alternate data streams.

**Comment by gave92** [comment]
Turns out that Alternate Data Streams can be listed directly from UWP using GetFileInformationByHandleEx. [Here's](https://github.com/files-community/Files/tree/alternate_streams) a test banch that adds support for including ADS in the file list.

**Comment by zbalkan** [comment]
This is huge. How do you think it should be handled in UI?

**Comment by gave92** [comment]
@zbalkan if you wish to check it out you can download the build from [here](https://dev.azure.com/filescommunity/db556b89-8bf0-4c03-8053-434c8f8714ff/_apis/build/builds/11542/artifacts?artifactName=drop&api-version=7.0&%24format=zip). It installs alongside your existing Files version.
Listing / copying / moving /renaming / deleting / viewing ADS should be working. You can enable ADS from Settings > Preferences > Files and folders. Currently ADS look like hidden files (semitransparent) under the main stream and are recognizable by the name in the format "file_name:ads_name".

**Comment by zbalkan** [comment]
I tried and saw that it works smoothly. The only difference I saw with ADS and normal files is that, when you remove an alternate data stream, it does not trigger a refresh after completion. When manually refresh is done, it is visible that ADS is removed. Otherwise, it looks really good.

**Comment by gave92** [comment]
Thanks for the feedback. I'm afraid we won't be able to add auto-refresh for ADS at the moment. The filesystem does not give change notifications for ADS.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #9234
