### ISSUE TITLE
'New Folder' option not obvious at first

### ISSUE THREAD

**Issue by thomiel** [files-community/Files#1786]
**Is your feature request related to a problem? Please describe.**
I didn't find out how to create a new folder at first. Finally, after taking some time and pressing any possible button, I discovered that this function could have been found below the '+' icon. I assumed this whould have to do more something like 'add window' because it sits in the window menu.

**Describe the solution you'd like**
Add a 'Create Folder' item to the context menu of all folders and drive letters (along with the other creates, separated by a line to 'New Tab' and 'New Window'. 

**Describe alternatives you've considered**
Replace the '+' button with a box with an asterisk or folder icon with asterisk, symbolizing a creation better than the '+' icon. (from a hermeneutics standpoint an addition is an operation between existing objects, and not so much associated with a creation.) But this may be due to my personal taste or pictogram dyslexia. The context menu item would have solved my problem rightaway, so if you don't want to change the icon, at least populate the context menu (and maybe put the '+' icon before the context menu item, so the chance to make the connection with the window menu item '+' is increased.

**Additional context**
I looked for an alternative to the standard Windows Explorer, because the latter let me wait severals seconds up to half a minute, becoming unresponsive. I mitigated it a bit by disabling the Windows search service, but Defender seems to prevent access especially with .zip files. So I used Files UWP to some extent the last weeks, without knowing how to create folders. (Integrating zip archives would be another killer feature btw., but I don't dare to ask for it while the software is in beta state.)

**Comment by thomiel** [comment]
not in current version 0.13.1:

![grafik](https://user-images.githubusercontent.com/11477743/91044318-5c921280-e615-11ea-80c6-03f6f9f083f4.png)

**Comment by thomiel** [comment]
ah, now I get it: you right-clicked on the empty forders content area! but what will you do, if the folder is full of files and you don't find an empty area to right-click on?

right-clicking on a folder or drive should allow the user to create a subfolder (or bitmap image, or text document).

**Comment by d2dyno1** [comment]
I don't really think I'd be very convinient, I'd say it would confuse some users as to where the folder is created. There is just enough space on the left side to open a context menu on a folder with current implemenation:
![image](https://user-images.githubusercontent.com/53011783/91324331-3c538680-e7c2-11ea-8073-4fa413640e3e.png)

Though, I think changing the '+' icon is a possibility, what do you think @yair100 ?

**Comment by yair100** [comment]
> Though, I think changing the '+' icon is a possibility, what do you think @yair100 ?

@d2dyno1 That is definitely a possibility, how about changing the icon of the button and changing the menu to have the same items as the right click context menu?

**Comment by d2dyno1** [comment]
@yair100  That'd be great! The '+' would finally have a purpose

**Comment by thomiel** [comment]
> I don't really think I'd be very convinient, I'd say it would confuse some users as to where the folder is created. There is just enough space on the left side to open a context menu on a folder with current implemenation:

Now that you mention it: yes there are a few pixels left and right of the list item. But that's not obvious. Rather a hidden feature.
