### ISSUE TITLE
The mapped network driver does not show up fully in the list.

### ISSUE THREAD

**Issue by Czile-create** [files-community/Files#1789]
After I have mapped my network drive (NAS) using Microsoft's File Manager, if I disconnect, when I click the icon again, it tries to reconnect. But in this file manager, the icon will just disappear. Also, this file manager doesn't use the mapped network drive feature and to reconnect I have to open the file manager that comes with the system, which causes me a lot of trouble.

我使用微软的文件管理器对我的网络硬盘（NAS）做了映射之后，如果断开了连接，当我再次点击图标时，会尝试重新连接。但是在此文件管理器中，图标会直接消失。并且，此文件管理器没用映射网络驱动器功能，要想重新连接，我不得不打开系统自带的文件管理器，这对我造成了很大的困扰。

system info：win10 Home 1909 /18363

**Comment by yaichenbaum** [comment]
@Czile-create Is this still an issue in v1.3?
