### ISSUE TITLE
show the onedrive-personal tab

### ISSUE THREAD

**Issue by seinlen** [files-community/Files#1794]
**Is your feature request related to a problem? Please describe.**
I link to both ondrive-personal and onedrive for business services, but on the side panel there's only onedrive for business tab.

**Describe the solution you'd like**
Add a new tab for onedrive-personal, like traditional file explorer.

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by yaichenbaum** [comment]
This issue should be resolved with v0.20.
