### ISSUE TITLE
Quick access

### ISSUE THREAD

**Issue by MarcAnt01** [files-community/Files#1805]
**Is your feature request related to a problem? Please describe.**
I like the possibility to have access to frequently used folders without having to look for them manually.

**Describe the solution you'd like**
Include a Quick access area in the sidebar, allowing to pin folders and to automatically display the most-used ones

**Describe alternatives you've considered**
None

**Additional context**
![image](https://user-images.githubusercontent.com/43090263/91314513-ee855100-e7b6-11ea-8fba-28aaba4122a9.png)

**Comment by Jaiganeshkumaran** [comment]
@MarcAnt01 You can already pin a folder the sidebar by right clicking on a folder and selecting 'Pin to sidebar'.

**Comment by yaichenbaum** [comment]
@MarcAnt01 You can already see recently opened folders on the jumplist, however, adding a quick access section is something we can look at doing as well.

**Comment by yaichenbaum** [comment]
Merging with #692.
