### ISSUE TITLE
App crashes occasionally during launch

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#1825]
**Describe the bug**
Sometimes when opening Files UWP it crashes for no reason.

**To Reproduce**
1. Open Files
2. Switch to some other app for some time and switch back to Files UWP
3. It may crash

**Expected behavior**
Files UWP shouldn't crash.

**Desktop :**
 - OS: Windows 10 Pro Version 2004
 - App version: v0.13.4.0

**Additional context**
Add any other context about the problem here. For instance, are you building from source or using a precompiled build/snapshot?
I am using the Microsoft Store version.

**Log file**
Please post the log file here so that we can understand your problem better. You can access it from Settings->About->Open log location.

```
2020-08-27 14:45:06.5512|ERROR|Files.App|Invalid pointer
Error trying to serialize the value to be written to the application data store|System.NullReferenceException: Invalid pointer
```

**Comment by Jaiganeshkumaran** [comment]
This also occurs while navigating through the UI like the settings page.

**Comment by gave92** [comment]
Looks similar to #1809. Crash during launch should be fixed now

**Comment by Jaiganeshkumaran** [comment]
@gave92 But for me it really crashes.

**Comment by duke7553** [comment]
@Jaiganeshkumaran Just wanted to confirm with you. Is this one still an issue?

**Comment by Jaiganeshkumaran** [comment]
@duke7553 Yes I still saw this issue but this time when navigating inside Files it simply crashes.

**Comment by yaichenbaum** [comment]
I am closing this issue since we haven't seen any reports of this issue in the last couple of months.
