### ISSUE TITLE
Right clicking rename box closes rename mode

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#1834]
**Describe the bug**
When you right-click the text box shown in rename mode it gets closed.

**To Reproduce**
1. Hit rename on any item
2. Right click or long press
3. It will get closed

**Expected behavior**
It shouldn't close until the users hits enter or space or any other standard key for closing something.

**Screenshots**
Recorded video of the problem:
https://app.box.com/s/met1ry3heo6nutt9kwdhzbcci4fclu8a

**Desktop:**
 - OS Version: Windows 10 version 2004
 - App version: v0.13.4.0

**Comment by Jaiganeshkumaran** [comment]
For some reason the context menu isn't captured by the video but when I right click I does show a menu flyout for a second and then it goes away.

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran This issue should be resolved with #2749.
