### ISSUE TITLE
Executable files that are opened in Files UWP are opened in the last viewed folder. 

### ISSUE THREAD

**Issue by GittyMac** [files-community/Files#1844]
**Describe the bug**
In the "Recent Items" page on the "Home" tab, if you run an executable, it will open in the folder that you last viewed in the Files UWP tab.  It defaults to C;\Windows\System32 if no folders are opened. 

**To Reproduce**
1. Run an executable that opens/creates files in the folder that it is ran in.
2. Go to any other folder.
3. Click on the "Home" tab.
4. Open the executable in "Recent Items".
5. It will write/open a file where it is running from.

**Expected behavior**
The executable should be ran in the folder it is stored at.

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 2004 19041.450]
 - App version: [v0.13.1.0]

**Comment by MeirKlemp** [comment]
I would like to be assigned to this issue.
