### ISSUE TITLE
Duplicate window opens when moving tab to tab strip from another window

### ISSUE THREAD

**Issue by tsvietOK** [files-community/Files#1848]
**Describe the bug**
When moving(drag'n'drop) tab from another window it opens this tab and opens new window with this tab.

**To Reproduce**
1. Open any folder
2. Open any folder in another tab
3. Move second tab outside window
4. Move tab from just created window back to main window
5. Dragged tab opens in both windows.

**Expected behavior**
Tab should be opened only in one window.

**Screenshots**
![image](https://user-images.githubusercontent.com/20501502/91751233-19afdc00-ebcd-11ea-9c77-1ceacee19a4e.png)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 2004 19041.450]
 - App version: [v0.13.6]

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
