### ISSUE TITLE
Item list isn't reordered when you create an item

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#1857]

**Comment by osieltorres** [comment]
I would also aggregate that on rename sometimes also happens. 
Example:
I have three files, let's say E8.mp4, E9.mp4 & E10.mp4, if I rename E8.mp4 to E11.mp4, works fine, it goes to the list bottom, but when I rename it back to E8.mp4, it remains on the bottom until you refresh the view.
