### ISSUE TITLE
Modern navigation and commanding

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#1872]
**Is your feature request related to a problem? Please describe.**
Although the current navigation bar and status bar looks good and works fine, it's plain and boring. Also many options are buried in the more button which makes it difficult to use.

**Describe the solution you'd like**
A single compact header at the top with all information about the current directory with all the options inline depending on the screen size.

**Describe alternatives you've considered**
None.

**Additional context**
I'll work on this

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran Before opening a pull request, can you share some concepts of what you have in mind?

**Comment by Jaiganeshkumaran** [comment]
@Jaiganeshkumaran Something like Groove Music's album but smaller. I didn't start working on this yet.

**Comment by Jaiganeshkumaran** [comment]
The idea is to combine the status bar and path bar into one single panel. Also put the options front and center for easy access.

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran Looking forward for some concepts so we can discuss it and provide input.

**Comment by duke7553** [comment]
@Jaiganeshkumaran Do you have any concepts for this? It's been a while since this one was opened.
