### ISSUE TITLE
Grouping Folder Contents (Group By)

### ISSUE THREAD

**Issue by AlexDavies8** [files-community/Files#1874]
**Is your feature request related to a problem? Please describe.**
Cannot group folder contents like in File Explorer

**Describe the solution you'd like**
Add a 'Group By' option, allowing folder contents to be automatically grouped.

**Describe alternatives you've considered**
None

**Additional context**
![image](https://user-images.githubusercontent.com/52012013/92308031-91498680-ef92-11ea-8024-681006a08b3c.png)
![image](https://user-images.githubusercontent.com/52012013/92308081-16cd3680-ef93-11ea-8023-96cdfc3c549d.png)

**Comment by tsukiaru** [comment]
I don't know if it's common practice on github to up issues to show interest, but I would also love to see this feature added – At least a "group by time" option, which allows files to be grouped in "Today - Yesterday - Last week - etc" categories, like in File Explorer and Finder.

**Comment by PINPAL** [comment]
+1 to this. It’s also set to group by date by default for the Downloads folder in recent builds of Windows 10.

**Comment by yaichenbaum** [comment]
@AlexDavies8 This feature was implemented in #4826.
