### ISSUE TITLE
After changing the file extension, the file icon is not updated automatically to reflect the new extension, and it needs to be manually refreshed

### ISSUE THREAD

**Issue by KafuuNeko** [files-community/Files#1878]
重命名文件后缀名后文件图标无法及时更新成与后缀名相对应的图标，需要手动刷新后才更新

**Comment by gave92** [comment]
I'll assume this means something like:
> "After changing the file extension, the file icon is not updated automatically to reflect the new extension, and it needs to be manually refreshed"

😂

**Comment by yaichenbaum** [comment]
This issue should be resolved with v0.21.1.
