### ISSUE TITLE
SSHFS slowdowns after 0.13.0

### ISSUE THREAD

**Issue by asuetin** [files-community/Files#1880]
**Describe the bug**
Opening a SSHFS drive and folders within it is slow in comparison to other drives. The context menu is also slower to open.

**To Reproduce**
1. Download and install [WinFsp](https://github.com/billziss-gh/winfsp/releases)
2. Download and install [SSHFS-Win](https://github.com/billziss-gh/sshfs-win/releases)
3. Create a SSHFS drive pointing to a Linux server or a WSL2 instance
4. Compare the speed between the newly created drive and any other drive

**Expected behavior**
Loading the drive and folders should be nearly instant.

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2 19042.487]
 - App version: [v0.14.0]

**Additional context**
The problem started in 0.13.0. I was using a non-Insider Windows build when it did.

**Log file**
[debug.txt](https://github.com/files-community/files-uwp/files/5179170/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/files-uwp/files/5179171/debug_fulltrust.txt)

**Comment by yaichenbaum** [comment]
@asuetin The slower context menu is due to the new shell integration support and we are tracking the issue here #1873.

**Comment by duke7553** [comment]
@asuetin Thanks for the great issue report. We made some changes which improve perceived loading speeds overall. If you still notice an issue with SSHFS drives specifically, can you provide us a status on the situation?

Otherwise, we'll assume this was resolved for you after several days.

**Comment by yaichenbaum** [comment]
@duke7553 The issue is by design since we use the StorageFolder APIs for this type of drive.

**Comment by lukeblevins** [comment]
@yair100 The user reported that this regressed after a certain version number. Perhaps, the StorageFolder abstraction is our only option.

**Comment by yair100** [comment]
> @yair100 The user reported that this regressed after a certain version number. Perhaps, the StorageFolder abstraction is our only option.

I was wondering about that because pre v0.13, this directory shouldn't have loaded at all. Either way, because of the recent changes we made to improve the speed of displaying items, as well as improvements coming down the list with an improved data grid control, I think we can close this issue.

**Comment by asuetin** [comment]
> @asuetin Thanks for the great issue report. We made some changes which improve perceived loading speeds overall. If you still notice an issue with SSHFS drives specifically, can you provide us a status on the situation?
> 
> Otherwise, we'll assume this was resolved for you after several days.

Just to confirm: SSHFS is much faster now to the point where I'd consider this issue resolved.
