### ISSUE TITLE
Unnecessary scrollbar below the Home page tiles

### ISSUE THREAD

**Issue by asuetin** [files-community/Files#1892]
**Describe the bug**
A scrollbar appears when you hover the cursor below the Home page tiles even if the window is wide enough for it to not be necessary.

**To Reproduce**
1. Maximize the Files UWP window
2. Hover the cursor below the tiles

**Expected behavior**
The scrollbar should not appear if the window is wide enough.

**Screenshots**
![image](https://user-images.githubusercontent.com/37500046/92450566-42833300-f1c4-11ea-96b2-b73a0919f9b7.png)

**Desktop**
 - OS Version: Windows 10 20H2 19042.487
 - App version: v0.14.0

**Comment by Jaiganeshkumaran** [comment]
This is there for all pages in Files UWP not just the home tiles.

**Comment by duke7553** [comment]
Thank you for creating this feedback item. A solution for it is currently being reviewed as a PR (pull request) to our active development branch. We'll let you know once it's merged.
