### ISSUE TITLE
Support overwrite experience during paste operation

### ISSUE THREAD

**Issue by asuetin** [files-community/Files#1893]
**Is your feature request related to a problem? Please describe.**
When you're pasting a file to a folder that already has a file with the same name, there is no choice to overwrite it - the app always creates a copy.

**Describe the solution you'd like**
Offer a dialog with the choice of either overwriting or creating a copy.

**Additional context**
App version: v0.14.0

**Comment by yaichenbaum** [comment]
@asuetin This issue should be resolved with #2712.

**Comment by RickStanley** [comment]
Hello, was this released to version 1.1.0.0? Didn't find any mention of this in the release notes for the most recent release (v1.1, Jan. 15). Installed through MStore.

I can't paste and overwrite the file.

![image](https://user-images.githubusercontent.com/23178554/105622110-e7558400-5de4-11eb-9879-95723446c538.png)

Options:
- New name for file (appends - Copy)
- Existing file or
- Cancel

From https://github.com/files-community/Files/pull/2712 shouldn't the second option be "Ersetzen" (overwrite)?
