### ISSUE TITLE
Add shell extension support for the right click context menu on drives in the sidebar

### ISSUE THREAD

**Issue by AngelZeur** [files-community/Files#1895]
![Screenshot_2](https://user-images.githubusercontent.com/60907149/92502751-b6c6d200-f1d6-11ea-84e7-5bdf0354649c.png)
![Screenshot_1](https://user-images.githubusercontent.com/60907149/92502755-b75f6880-f1d6-11ea-9632-d03c5bd469c5.png)

**Describe the bug**
A clear and concise description of what the bug is and why it is more urgent than other issue reports. Can't answer this? Please return to the previous page and file a regular bug/feature report.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Additional context**
Add any other context about the problem here. For instance, are you building from source or using a precompiled build/snapshot?

**Log file**
Please post the log file here so that we can understand your problem better. You can access it from Settings->About->Open log location.

**Comment by AngelZeur** [comment]
Put all these option of the original Windows 10 File Explorer when I click with the right mouse bhutan on a device and drive as my USB STICK to have this in The UWP Files - Preview when I click with the right-click bhutan on a Device or drive in The UWP Files - Preview like for example this my USB Pendrive from Print Screen and appear all these option in The UWP Files - Preview please

**Comment by yaichenbaum** [comment]
@AngelZeur Can you please fill out the issue template to better help us understand the feature proposal?

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5836.
