### ISSUE TITLE
Follow the system setting for showing the accent color on the title bar

### ISSUE THREAD

**Issue by jcg3675** [files-community/Files#1897]
**Is your feature request related to a problem? Please describe.**
No problem.

**Describe the solution you'd like**
Irrespective of Light and Dark theme, there should be an option to set the title bar--as in the horizontal strip that contains the tabs--to my system accent color.

**Describe alternatives you've considered**
No alternatives.

**Additional context**
Using Files v. 0.14.0.0 on Asus Zen AiO Pro with mouse and keyboard.

**Comment by lukeblevins** [comment]
@yair100 Maybe before we set our custom title bar, we can retrieve the [background color](https://docs.microsoft.com/en-us/uwp/api/windows.ui.viewmanagement.applicationviewtitlebar.backgroundcolor?view=winrt-19041#Windows_UI_ViewManagement_ApplicationViewTitleBar_BackgroundColor) and handle it appropriately if its not a default color?

**Comment by yaichenbaum** [comment]
@duke7553 We should only use the background color if the user turned on the setting to display the accent color in the title bar.

**Comment by mdtauk** [comment]
If you query the registry to see if the Show Color on Titlebar setting is on, you could use a tinted Acrylic brush for the top bar/tab area.  And then if the Acrylic setting is turned off in the app or the system, the fallback colour can match the Accent Colour used for the titlebars.

**Comment by yaichenbaum** [comment]
We no longer plan on implementing this feature since Files extends the UI into the title bar.
