### ISSUE TITLE
Put all of these original Windows 10 File Explorer option owned by Files and Folders please

### ISSUE THREAD

**Issue by AngelZeur** [files-community/Files#1898]
![Screenshot_4](https://user-images.githubusercontent.com/60907149/92552771-c1658380-f237-11ea-8906-bd910f01d69d.png)
![Screenshot_3](https://user-images.githubusercontent.com/60907149/92552773-c1fe1a00-f237-11ea-836c-c5cfd29e54ac.png)
![Screenshot_2](https://user-images.githubusercontent.com/60907149/92552774-c296b080-f237-11ea-8b14-3310cc7dd0cc.png)
![Screenshot_1](https://user-images.githubusercontent.com/60907149/92552776-c296b080-f237-11ea-916d-21dd3197312d.png)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by XPoppyX** [comment]
Details: #1650 
Security: #1647

**Comment by gave92** [comment]
A quick and dirty solution for this is to offer an option to open the standard windows explorer properties window instead of app's. Could this satisfy "power" users until we have a full uwp implementation?

**Comment by yaichenbaum** [comment]
@AngelZeur Please subscribe to #1647 and #1650 to get notified when these features are implemented.
@gave92 It's better to continue working on a full solution, @winiston2212 is working on the details page and there is already an open pull request #1952.
