### ISSUE TITLE
Settings page distracts users

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#1899]
**Is your feature request related to a problem? Please describe.**
Today the settings button opens in full screen and distracts users.

**Describe the solution you'd like**
Since it has only a few options, consider making a side panel something like in the Mail app.

**Describe alternatives you've considered**
None.

**Comment by yaichenbaum** [comment]
Based off analytics, the settings page is not opened very often so there shouldn't be an issue of it being distracting. It's also important to note that the settings page is going to get more options over time so it is probably best to continue with the current format.

**Comment by jaigak** [comment]
@yair100 But it wastes a lot of space and since those controls aren't going to probably use horizontal scrolling in the future.

**Comment by Jaiganeshkumaran** [comment]
How about making it another tab or even another window?

**Comment by yaichenbaum** [comment]
> How about making it another tab or even another window?

Another tab can definitely work but it will be confusing if the user hid the tabs. Opening it in another window might cause a disconnected experience. One of the things we intend on doing is to make the settings pages a richer experience. We can do this by adding tips and links to related settings in the unused space.

**Comment by Talisman39ar** [comment]
Having Settings be modal where it takes over the whole app is how MS is doing things with its most contemporary apps, e.g. Your Phone and To-Do. Unless there is a compelling reason to be doing something in Settings *while* also manipulating something else, then I would say stick with that established pattern.

**Comment by Jaiganeshkumaran** [comment]
@Talisman39ar But in the app's setting page you don't get a sidebar or something.

**Comment by Talisman39ar** [comment]
@Jaiganeshkumaran Do you mean in apps like To-Do and Your Phone the settings themselves don't have a sidebar? If so, that's true, both have all settings on a single page. In the case of Your Phone that's getting to be a long list, in that respect I think the current Files arrangement of having categories in the sidebar is arguably simpler (though it requires more clicks). 

Maybe you can be more specific about what you mean by "distracting"? That term is ambiguous. Do you mean it pulls the user's attention away from something else they should be looking at? Or it's not well organized and is confusing? Or...? Just trying to understand what the problem is you're seeing.

**Comment by yaichenbaum** [comment]
>  In the case of Your Phone that's getting to be a long list, in that respect I think the current Files arrangement of having categories in the sidebar is arguably simpler (though it requires more clicks).

The Your Phone app is actually switching it's setting page to use the same design we use in Files UWP.

**Comment by Jaiganeshkumaran** [comment]
@Talisman39ar When I am browsing through files I have to open the full screen settings, find the menu item, click on it and hit the option, Then I need to comeback. Instead a dialog or flyout will be better since I can change the option instantly and see the change.

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran That is a valid point, however, most settings are very clear in what they do and some of them even include a description with more details.

**Comment by jaigak** [comment]
@yair100 Don't just copy apps like Your Phone because they were designed for a different use case. Microsoft doesn't provide a common guideline for app settings and even their apps have different ways based on the app.

**Comment by yaichenbaum** [comment]
There doesn't seem to be a lot of users finding the settings page distraction, however, to be consistent with the other sidebar items, I don't see an issue adding a right click context menu with the option to open the settings page in a new window.

**Comment by osieltorres** [comment]
I personally don't think setting page may be a distraction, although I do think there should be a save action on settings back arrow button after user change any setting. Currently if you do so, you would need to restart the app for changes to have effect.

**Comment by yaichenbaum** [comment]
After creating a poll to ask users about this, most users asked us to keep the settings page how it is. This can be evaluated again in the future if this changes.
