### ISSUE TITLE
Make a website.

### ISSUE THREAD

**Issue by pixl-8** [files-community/Files#1903]
You guys should make a website for your Files UWP that explains info and stuff.
If you need a domain just get one at [Freenom](https://freenom.com).
I was thinking of a domain like files-uwp.tk or files-uwp.com.

**Comment by yaichenbaum** [comment]
@pixl-8 The wiki already includes a lot of info, however, creating a dedicated site is something we can look into once the app leaves beta.

**Comment by pixl-8** [comment]
Good idea.

**Comment by yaichenbaum** [comment]
@pixl-8 Our website just went live, you can find it over [here](https://files-community.github.io/files.github.io/).
