### ISSUE TITLE
Tab crash bug

### ISSUE THREAD

**Issue by pixl-8** [files-community/Files#1905]
There is an issue with Files UWP when you press CTRL + T more than four times and then manually close about three. This issue is pretty rare because I've only had it happen once.

Windows 10 Version: Build 20170.rs_prerelease (Windows 10 home)
Files UWP Version: 0.14.0.0

**Comment by Jaiganeshkumaran** [comment]
@pixl-8 Could you share the log file?

**Comment by duke7553** [comment]
@pixl-8 Yeah. This seems like an edge case. Can you please share your debug log file, so we can track down this one?

**Comment by duke7553** [comment]
@pixl-8 Thanks again for your feedback. 

_Since we didn't hear from you on this topic for several days, we'll assume everything is worked out and close this feedback item. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this._
