### ISSUE TITLE
"Empty Recycle Bin" context menu entry is grayed out

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#1910]
The option is grayed out, even though there are files in the Recycle Bin

![image](https://user-images.githubusercontent.com/17484252/92918353-9fceec80-f42f-11ea-942f-c58c2794837f.png)
[debug_fulltrust.txt](https://github.com/files-community/files-uwp/files/5208517/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/files-uwp/files/5208518/debug.txt)

**Comment by SOI7** [comment]
Sorry to reopen this, but the issue still exists on 0.15.4.0 :x

![image](https://user-images.githubusercontent.com/50930970/94693467-0f037680-0334-11eb-96b2-af0c9cb19167.png)
