### ISSUE TITLE
Control + Tab doesn't work always

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#1912]
**Describe the bug**
A clear and concise description of what the bug is and why it is more urgent than other issue reports. Can't answer this? Please return to the previous page and file a regular bug/feature report.

Control + Tab is an essential feature of any tab based app and after you threw away the WinUI Tab view and went with your own, I've seen a lot of issues especially with the Control + Tab shortcut. It doesn't work always properly.

**To Reproduce**
1. Open Files UWP and have multiple tabs open
2. Click inside a BaseLayout instance
3. Control + tab will not work unless you put your cursor over the tab view

**Expected behavior**
It should work regardless of the focus state.

**Desktop (please complete the following information):**
 - OS: 2004 Pro
 - App version: v0.14.0

**Comment by yaichenbaum** [comment]
> Control + Tab is an essential feature of any tab based app and after you threw away the WinUI Tab view and went with your own, I've seen a lot of issues especially with the Control + Tab shortcut. It doesn't work always properly.

We are still using the WinUI TabView, the issue with the shortcut is likely due to moving the code for detecting shortcuts to a different file, this will require some investigation to confirm.

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran this issue should be resolved with #4973.
