### ISSUE TITLE
Please add an option to turn off animation

### ISSUE THREAD

**Issue by ColbertBrave** [files-community/Files#1920]
In the last version(0.12 or 0.13), there isn't animation at the address bar when I open an folder, it looks very good for me and many people. In the latest version, developers add the animation feature. It is also good but not for some people. I hope to add an option to turn off animation just as what Apple did in the IOS when IOS7 first appeared. In a addition, the file explorer is really stunning and it‘s UI is the best. Thanks.

**Comment by yaichenbaum** [comment]
> In the last version(0.12 or 0.13), there isn't animation at the address bar when I open an folder, it looks very good for me and many people. In the latest version, developers add the animation feature. It is also good but not for some people. I hope to add an option to turn off animation just as what Apple did in the IOS when IOS7 first appeared. In a addition, the file explorer is really stunning and it‘s UI is the best. Thanks.

@ColbertBrave Can you share a screen recording of the animation you are referring to?

**Comment by Colbert-Ran** [comment]
@yair100 This is a screenshot of the animation and it marks the location of animation. The animation occurs when I open an folder. The animation there is distractive for some people. I wish to add an option to turn off it. Thank you very much.
![image](https://user-images.githubusercontent.com/32506859/93019300-bed4a680-f608-11ea-8d26-8ec4ebc42163.png)

**Comment by yaichenbaum** [comment]
@ColbertBrave Are you talking about the reveal animation on the border of the navigation bar?

**Comment by SOI7** [comment]
I think he means the progress bar that appears each time you open a folder

**Comment by Colbert-Ran** [comment]
@yair100 Yes. Please consider adding an option to turn off it. It is really distractive. THANKS.

**Comment by Jaiganeshkumaran** [comment]
No need for an option. Files UWP probably uses Composition or XAML for animations, so disabling system animations from Settings->Ease of access->Display should also disable Files UWP animations.

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran Is correct, closing this issue.
