### ISSUE TITLE
Add support for OneDrive personal vault

### ISSUE THREAD

**Issue by asuetin** [files-community/Files#1924]
**Describe the bug**
Files UWP displays the [Personal Vault](https://www.microsoft.com/en-us/microsoft-365/onedrive/personal-vault) as a shortcut when it's not open. When you click on it and log in, the app crashes. If you open OneDrive after that, the shortcut is nowhere to be found.

**To Reproduce**
1. Lock the Personal Vault in OneDrive
2. Open it in Files UWP

**Expected behavior**
The Personal Vault should open like a regular folder after logging in.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.508
 - App version: v0.14.0

**Log file**
[debug.txt](https://github.com/files-community/files-uwp/files/5216490/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/files-uwp/files/5216491/debug_fulltrust.txt)

**Comment by gave92** [comment]
As of 0.20.0.0 app won't crash anymore but won't show items is the Vault folder

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.11.0 or above?

**Comment by asuetin** [comment]
@Josh-65 it's not. Thanks to whoever fixed this❤️
