### ISSUE TITLE
List and sort directories alongside files

### ISSUE THREAD

**Issue by rc1** [files-community/Files#1929]
**Is your feature request related to a problem? Please describe.**
Directories contain files and sub-directories. When listing a directory, I expect the contents to be sorted by date or alphabetically. However, the typical design pattern on Windows is to have a list of directories sorted then list of files. Here is an illustration of a situation where this causes a problem: when I unzip a directory from a zip flie in my downloads folder, I need to remember the zip files name, scroll up and find the name in the list of directories, 

**Describe the solution you'd like**
An option in settings to list directories alongside files

**Describe alternatives you've considered**
I'm sure this isn't to everyone's taste. But this pattern of separating files and folder only happens on Windows. Mac and Linux typically don't use this pattern. I'm not sure why people like this Windows pattern. Maybe because Windows doesn't have this feature: #1928

**Additional context**
Could you point me to the code where this would be implemented? I'd like to try make a PR for learning purposes.

**Comment by Talisman39ar** [comment]
As someone who used Macs for many years, totally agree! I still find it takes me longer to find things on Windows because of this. Would love to see an option to force alphabetical (or whatever sort mechanism) regardless of whether folder or file.

**Comment by yaichenbaum** [comment]
@rc1 Sorry about the long delay on this, I took a look and ended up implementing it myself when I saw how simple it is 😆. You can check out the pull request here #2606.
