### ISSUE TITLE
Problem with using track pad to scroll mid way during use

### ISSUE THREAD

**Issue by wongdom** [files-community/Files#1930]
**Describe the bug**
Problem with using track pad to scroll mid way during use. another thing - even the touch screen scrolling didn't work. the side bar scroll didn't work as well

**To Reproduce**

**Expected behavior**
Well , I'm using a surface pro 7 - I can use the trackpad to scroll in windows explorer

**Screenshots**

**Desktop (please complete the following information):**
Version	10.0.19042 Build 19042

**Additional context**
app worked after srestarting

**Log file**
Please post the log file here so that we can understand your problem better. You can access it from Settings->About->Open log location.

[debug.txt](https://github.com/files-community/files-uwp/files/5231533/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/files-uwp/files/5231534/debug_fulltrust.txt)

**Comment by yaichenbaum** [comment]
This issue appears to be resolved in `main`.
