### ISSUE TITLE
App Crashes every time space bar is pressed upon a file 

### ISSUE THREAD

**Issue by rachit1601** [files-community/Files#1931]
**Describe the bug**
The App crashes whenever I press space bar when a file is selected

**To Reproduce**
1. Go to Any folder
2. Click on any file
3. Press Space Bar
4. See error ( App crashes & closes

**Expected behavior**
I expected it to open quick look but I even tried it without quick look still it crashes

**Desktop (please complete the following information):**
 - OS Version:Windows 10 1809 17763.316
 - App version: [v0.14.0.0]

**Additional context**
This problem occurs every time even after reinstalling the apps

**Log file**
Please post the log file here so that we can understand your problem better. You can access it from Settings->About->Open log location.
[debug.txt](https://github.com/files-community/files-uwp/files/5232419/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/files-uwp/files/5232420/debug_fulltrust.txt)

**Comment by yaichenbaum** [comment]
@rachit1601 Is this still an issue in v0.21.1?

**Comment by yaichenbaum** [comment]
Thanks again for your feedback.

_Since we didn't hear from you on this topic for 3+ days, we'll assume everything is worked out and close this feedback item. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this._
