### ISSUE TITLE
ctrl + z command for restoring deleted files and folders is not working restoring in the same previous place as the files and folders were before deleting

### ISSUE THREAD

**Issue by AngelZeur** [files-community/Files#1932]
**Describe the bug**
A clear and concise description of what the bug is and why it is more urgent than other issue reports. Can't answer this? Please return to the previous page and file a regular bug/feature report.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Additional context**
Add any other context about the problem here. For instance, are you building from source or using a precompiled build/snapshot?

**Log file**
Please post the log file here so that we can understand your problem better. You can access it from Settings->About->Open log location.

**Comment by AngelZeur** [comment]
ctrl + z command for restoring deleted files and folders is not working restoring in the same previous place as the files and folders were before deleting

**Comment by yaichenbaum** [comment]
This issue should be resolved in the `master` branch.
