### ISSUE TITLE
The Title Bar is messed up

### ISSUE THREAD

**Issue by Cyberdroid1** [files-community/Files#1936]
**Describe the bug**
After changing multitasking from adaptive to vertical, the title bar is messed up and file path bar covers the close, minimize, maximise buttons. 

**Expected behavior**
There should be a gap between them

**Screenshots**

![image](https://user-images.githubusercontent.com/51435948/93465091-e927ac00-f907-11ea-89b1-b3252ddcd883.png)

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 20H2 19042.508]
 - App version: [v0.14.1.0]

**Comment by Cyberdroid1** [comment]
This issue happened again. 

![image](https://user-images.githubusercontent.com/51435948/98135674-1e06b700-1ee6-11eb-958f-3636fce45d4d.png)

Please reopen this issue again.

App version -- v0.19
Windows version -- Windows 10 19042.572

**Comment by stamminator** [comment]
@Cyberdroid1 Is this still happening? If so, what is your OS's display scaling set to?

**Comment by Cyberdroid1** [comment]
My display scaling is set to 100%. 

I haven't tried to recreate this issue. I will try to do the same and will update you :)

**Comment by yaichenbaum** [comment]
@Cyberdroid1 This issue should be resolved with #3797.
