### ISSUE TITLE
Add timestamp to current time after copying

### ISSUE THREAD

**Issue by jzt835** [files-community/Files#1948]
**Is your feature request related to a problem? Please describe.**
I am always frustrated, when I copy folders and files to an external hard drive (NTFS and exFAT) that the timestamps for modification time are not set to the current time.

**Describe the solution you'd like**
It should be added options in preferences that allow users to decide if the timestamp should be set to current time when copying folders and files.

This is how it should look like.

Set timestamp to current time after copying

```
Folder:
Modification time (on/off)
Access time (on/off)
Creation time (on/off)
Change time (on/off) - What is change time? See more under Additional context.

File:
Modification time (on/off)
Access time (on/off)
Creation time (on/off)
Change time (on/off) - What is change time? See more under Additional context.
```

**Describe alternatives you've considered**
There is no alternative, I am waiting for such a function since the first Windows File Explorer version.

**Additional context**
Additionally there should be the possibility to show change time (MFT Modified) e.g. for the NTFS file system.

See the table under this link: https://wiki.sleuthkit.org/index.php?title=Mactime_output

I use the current Windows 10 (2004 - 10.0.19041.508) version and Files UWP v0.14.

**Comment by yaichenbaum** [comment]
@gave92 do you know if this is still an issue in `main`.?

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.11.0 or above?
