### ISSUE TITLE
Preview for media

### ISSUE THREAD

**Issue by AbelTheGeorge** [files-community/Files#1950]
Im always frustrated when I have to slowly one by one open up multiple audio or video files to find the one im looking for

I recently installed a plugin in the default file explorer that brings up a mini player that plays the media when the mouse hovers over it. I have attached a gif of me doing it below. It quickly plays any audio, video or gif as soon as the cursor hovers over it...

So I think if u can do a similar feature where a mini window opens for a video and a small bar opens for audio it would be awesome.

It would also be nice if it supported a wide variety of file types and containers... wav, mpeg, mov etc etc

Thanks in advance

![FilesUWP](https://user-images.githubusercontent.com/63577249/93717620-93b3ff00-fb94-11ea-858b-93a9b31e7dea.gif)

**Comment by AqilCont** [comment]
Have you tried [QuickLook](https://github.com/QL-Win/QuickLook)? It's completely compatible with Files UWP out of the box, and is less annoying than a hover pop-up imo. It even has a nice UI....

**Comment by AbelTheGeorge** [comment]
Thanks for the suggestion it's a fantastic app...

**Comment by AqilCont** [comment]
No problem :D If you think the current functionality is fine, you can probably close this.

**Comment by duke7553** [comment]
@AbelTheGeorge Closing this since @AqilCont suggested QuickLook which Files has support for.
