### ISSUE TITLE
RED please make a red secction

### ISSUE THREAD

**Issue by Ramses-Oliveros-Santos** [files-community/Files#1951]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by Jaiganeshkumaran** [comment]
@Ramses-Oliveros-Santos Please explain properly. I don't understand what do you mean.

**Comment by duke7553** [comment]
@Ramses-Oliveros-Santos 
Thanks for your feedback. We're having trouble understanding what you're requesting and need additional information to investigate this item. Please re-open when you've filled out the issue template to the best of your ability.
