### ISSUE TITLE
Suggestion： Error notification

### ISSUE THREAD

**Issue by XSH-Hero** [files-community/Files#1960]
Hi！ I want the button “Report this issue” from the error notification link to Github , not Files UWP

**Comment by XSH-Hero** [comment]
![files](https://user-images.githubusercontent.com/69738882/93902614-5b462980-fd2a-11ea-8c7d-787690d44673.png)

**Comment by yaichenbaum** [comment]
@XSH-Hero This issue should be resolved when we release the next update.
