### ISSUE TITLE
What an awesome app UWP is, but Dropbox context menu will be even better to have :)

### ISSUE THREAD

**Issue by jakguzik** [files-community/Files#1963]
**Is your feature request related to a problem? Please describe.**
I can't reach my dropbox files context menu what is crucial for using any fil explorer.

**Describe the solution you'd like**
To have stadard dropbox features in the context menu for files and folders.

**Describe alternatives you've considered**
Honestly I don't know any.

**Additional context**
Classical desktop Win10, I gues you know what I am writing about :)

**Comment by yaichenbaum** [comment]
@jakguzik Can you fill in details like the version number? It will also help if you shared screenshots of what you expect to come up.
