### ISSUE TITLE
App doesn't allow to copy file's or folder's name

### ISSUE THREAD

**Issue by Tester09** [files-community/Files#1965]
**Describe the bug**
To copy file's or folder's name in the Explorer you should select it and press F2 or _rename_ in the RMB context menu then coping the name by Ctrl+C or by copy in the context menu but same actions aren't working in Files UWP and have very glitchy behaviour.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any location 
2. Select any file or folder and press F2
3. Try to copy its name by RMB context menu or by Ctrl+C 
4. _Copy text_ menu will appear on a second and then close name editing field, Ctrl+V will duplicate file or folder

**Expected behavior**
File's and folder's name should be copyable from the context menu or with shortcuts

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 2004 20215.1000]
 - App version: [v0.14.2]

**Comment by jaigak** [comment]
@yair100 Could you assign me on this issue?

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran Sure, however, you already have a number of assigned issues that you haven't opened pull requests for.
