### ISSUE TITLE
More Language Support

### ISSUE THREAD

**Issue by aunight** [files-community/Files#1972]
Such as Traditional Chinese
I can help to translate

**Comment by gave92** [comment]
In case you're willing you can translate the app yourself.
Here's the guide: https://github.com/files-community/Files/wiki/Translating-Files-UWP-into-your-language

**Comment by AnLazyOtter** [comment]
> In case you're willing, you can translate the app yourself.
> Here's the guide: https://github.com/files-community/Files/wiki/Translating-Files-UWP-into-your-language

现在，该帮助页面的超链接已经修改为：
Now, the guide page change into:
https://github.com/files-community/Files/wiki/Translating-Files-UWP-into-your-language

**Comment by yaichenbaum** [comment]
@AnLazyOtter The updated link is [here](https://github.com/files-community/Files/wiki/Translating-Files-into-your-language).
