### ISSUE TITLE
Missing Selection Mark

### ISSUE THREAD

**Issue by RiemaruKarurosu** [files-community/Files#1978]
I would be perfect if the app coud hace a Selection Mark as the main windows file explorer.
![imagen](https://user-images.githubusercontent.com/45057400/94380047-88635500-00f9-11eb-8b0f-12b7371dca82.png)

Most of the file explorers out there have this function. It would be a nice feature.

**Comment by duke7553** [comment]
@RiemaruKarurosu This is a Duplicate of #94
