### ISSUE TITLE
Crashing Application upon Ctrl + C / V / X

### ISSUE THREAD

**Issue by ilikec** [files-community/Files#1982]
**Describe the bug**
Upon pressing Ctrl + C / V / X after selecting any file, Files UWP crashes without further notice. All three functions work fine via context-menu

**To Reproduce**
1. Go to 'Documents','Pictures' or an external hard drive
2. Click on any given file
3. Press Ctrl + C or Ctrl + X or Ctrl + V
4. The application crashes

**Expected behavior**
The file is either copied or cutout to clipboard or pasted, depending on the used shortcut.

**Desktop (please complete the following information):**
 - OS Version:  Windows 10 17763.1457
 - App version: [v0.15.0.0]

This problem reoccurs even after several system-reboots and application restarts.
[debug.txt](https://github.com/files-community/Files/files/5292261/debug.txt)

**Comment by gave92** [comment]
Thanks for the report. This appears to be a pretty common stacktrace.
Could you check if the issue is present also if you set Tile view instead of Details view?

**Comment by ilikec** [comment]
Can reproduce in both tileview and gridview.
[debug.txt](https://github.com/files-community/Files/files/5296778/debug.txt)
