### ISSUE TITLE
Files UWP crashes when dragging and dropping files onto folders

### ISSUE THREAD

**Issue by Nuzza** [files-community/Files#1987]
**Describe the bug**
Upon releasing the left click button while dragging a file or several files over a folder, causes Files UWP to crash.

**To Reproduce**
1. Drag and Drop a file or several files onto a folder (move to that folder)
2. Files UWP crashes

**Expected behavior**
The zip file(s) are moved to the folder when releasing the left click over a folder while dragging a file or several 

files.

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 2004 20221.1000]
 - App version: [v0.15.0.0]

**Additional context**
Sometimes I can move files to a folder via drag and drop but when it does cause a crash, relaunching the Files UWP doesn't fix the issue when attempting to perform the same action again.

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5298481/debug.txt)

**Comment by gave92** [comment]
Thanks for the report. This issue is fixed on master -> #1983

**Comment by yaichenbaum** [comment]
@Nuzza Is this still an issue in v0.21.1?

**Comment by Nuzza** [comment]
Nope, just tested it and the issue seems to be resolved, thanks.
