### ISSUE TITLE
When I go to rename the name of some File Files UWP - Preview it closes automatically appearing this error to me saying this print screen correct this please so I can rename the name of all Files

### ISSUE THREAD

**Issue by AngelZeur** [files-community/Files#1997]
![Screenshot_1](https://user-images.githubusercontent.com/60907149/94609413-20397e00-0275-11eb-80d8-527877213560.png)

**Describe the bug**
A clear and concise description of what the bug is and why it is more urgent than other issue reports. Can't answer this? Please return to the previous page and file a regular bug/feature report.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Additional context**
Add any other context about the problem here. For instance, are you building from source or using a precompiled build/snapshot?

**Log file**
Please post the log file here so that we can understand your problem better. You can access it from Settings->About->Open log location.

**Comment by AngelZeur** [comment]
When I go to rename the name of some File Files UWP - Preview it closes automatically appearing this error to me saying this print screen correct this please so I can rename the name of all Files

**Comment by yaichenbaum** [comment]
@AngelZeur Can you try updating to v0.15 and let us know if you still see this issue?
