### ISSUE TITLE
Add "Sent To" option in right click menu

### ISSUE THREAD

**Issue by askfriends** [files-community/Files#1998]
i have a feature request so im bypassing your template, hopeu wont mind.

1. Add "Send to" option in right click menu, for example when i right click on any folder to send it to USB drive, there should be send to option which makes it easy to send files to usb drive and this option is available in windows right click menu.

2. when i copy a folder from Drive1 and right click in Drive2 to paste it, but cant find Paste option in right click menu. fix it too

**Comment by gave92** [comment]
Merging with #285

**Comment by yaichenbaum** [comment]
Merging with #285.
