### ISSUE TITLE
Explorer crashes after attempting to copy any file, without copying them

### ISSUE THREAD

**Issue by Gizmotronn** [files-community/Files#2001]
**Describe the bug**
Selecting any file or folder, or groups of either, and attempting to copy it results in the application crashing

**To Reproduce**
1. Open two windows or tabs
2. On one tab/window, choose a file to copy
3. On the other tab/window, choose a folder to copy that file into

**Expected behavior**
Application crashes without copying files

**Screenshots**

I've done a screen recording

[Files - Preview 2020-09-30 12-50-04.zip](https://github.com/files-community/Files/files/5303161/Files.-.Preview.2020-09-30.12-50-04.zip)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1903 18362.175]
 - App version: latest version as of today

**Additional context**
None

**Log file**
Please post the log file here so that we can understand your problem better. You can access it from Settings->About->Open log location.

[debug.txt](https://github.com/files-community/Files/files/5303163/debug.txt)

**Comment by Jaiganeshkumaran** [comment]
@Gizmotronn Explorer crashes or Files UWP crashes?

**Comment by Gizmotronn** [comment]
Files UWP, sorry

**Comment by yaichenbaum** [comment]
@Gizmotronn What version of the app are you using?

**Comment by Gizmotronn** [comment]
Latest version from the releases as of today.

**Comment by yaichenbaum** [comment]
@Gizmotronn Can you confirm that it's v0.15.4?

**Comment by Gizmotronn** [comment]
0.15.0 actually, my mistake @yair100

**Comment by yaichenbaum** [comment]
@Gizmotronn Does it still exist in v0.15.4?

**Comment by natiT** [comment]
Hello, i got the same Problem in 0.15.4.0. Error Logs also write "Access Denied" but i have Access to the Source and Destination Path. 
[debug.txt](https://github.com/files-community/Files/files/5333904/debug.txt)

**Comment by duke7553** [comment]
There's a potential improvement in this area being authored by @gave92 with #2269 . I'm going to close this since we already have other issues tracking the exceptions.
