### ISSUE TITLE
Ability to use horizontal scrolling with grid view

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#2003]
**Is your feature request related to a problem? Please describe.**
Although Microsoft recommends vertical scrolling, horizontal scrolling can sometimes be useful especially for large screens.

**Describe the solution you'd like**
A toggle to use horizontal scrolling instead of vertical scrolling.

**Describe alternatives you've considered**
None.

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?
This feature should be hidden on small-screen tablets/laptops because horizontal scrolling makes it hard to navigate on such devices.

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran We don't have any plans to implement this.
