### ISSUE TITLE
Ability to pin a folder to start

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#2006]
**Is your feature request related to a problem? Please describe.**
In File Explorer, you can pin a folder to the start menu, and clicking on it will open in it in File Explorer. 

**Describe the solution you'd like**
We can add an option to pin a folder like that however it should open it in Files without making it the default shell file manager.

**Describe alternatives you've considered**
None.

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?
I'll work on this

**Comment by jaigak** [comment]
@yair100 Could you assign me on this issue?

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran Is it possible to use a shell extension menu item in the context menu?

**Comment by yaichenbaum** [comment]
Merging with #782.

**Comment by gave92** [comment]
@yair100 i was not able to get the "pin to start" option from explorer to work (I get a nice UnauthorizedAccessException). I guess we could implement this internally I guess.

**Comment by Jaiganeshkumaran** [comment]
@gave92 That will only use the Explorer implementation which will actually use the default shell explorer and not Files. We can use a secondary tile which always launches Files.
