### ISSUE TITLE
Multiselect

### ISSUE THREAD

**Issue by yanjingtui** [files-community/Files#2008]
**Is your feature request related to a problem? Please describe.**
Please add multi select features for touch screen and mouse

**Describe the solution you'd like**
Long press a file, hold your finger and use another finger to select another file. Just like this at 1:34 https://youtu.be/I5EA8il5ojQ
For mouse users, just select file by clicking and dragging. 

**Describe alternatives you've considered**
Just add a select and modify mode

**Additional context**
![image](https://user-images.githubusercontent.com/18437653/94722053-08d2c180-0357-11eb-9cdf-37fc8902a35a.png)

**Comment by gave92** [comment]
An alternative way for touch would be a long press that triggers a "multiple selection mode" where checkboxes appear next to items
![image](https://user-images.githubusercontent.com/9673091/99309862-66b15f00-285a-11eb-8629-ba2859d2d2c2.png)

**Comment by yaichenbaum** [comment]
This feature was recently implemented in `main`.
