### ISSUE TITLE
Option to sort pinned files (items)

### ISSUE THREAD

**Issue by whdmike** [files-community/Files#2011]
**Is your feature request related to a problem? Please describe.**
I would like to be able to sort pinned items (on a left). Now I can pin them, but if I want to change the order of importance for me, I can't.

**Describe the solution you'd like**
be able to sort pinned files (items)

**Describe alternatives you've considered**
just that, option to sort pinned files. Windows file explorer can do, you can do also

**Additional context**

**Comment by DanielSlincak** [comment]
Hi, could I work on this issue? @yair100

**Comment by yaichenbaum** [comment]
@DanielSlincak Sure!

**Comment by DanielSlincak** [comment]
I'll make a pull request by the end of the week. I'm working on two ways on how to sort the pinned items. The first is by dragging and dropping them - the implementation for this is finished. The second one is by right-clicking and selecting from pre-determined sort options - name, date added, ascending and descending. I'm still working on a few details with this implementation.

**Comment by yaichenbaum** [comment]
@DanielSlincak Sort by date is not necessary, we only plan to implement the option to reorder the pinned items manually.

**Comment by DanielSlincak** [comment]
@yair100 Okay, should I disable it, or remove all the code for the implementation as well? You can check it in the pull request.

**Comment by yaichenbaum** [comment]
@DanielSlincak You should probably remove the code for the sorting option.

**Comment by whdmike** [comment]
I see that this feature is already "implemented", but still in the last 0.21 version I am not able to sort pinned folders. Am I missing something? Thanks

**Comment by yaichenbaum** [comment]
@whdmike The code is already there and implemented, however we are waiting on a fix in the WinUI library for an issue that breaks this functionality before we enable it.

**Comment by whdmike** [comment]
> @whdmike The code is already there and implemented, however we are waiting on a fix in the WinUI library for an issue that breaks this functionality before we enable it.

I think there are few options how sorting can be done - in a case you have problems with code and you are not able to implement it - one option is drag and drop like windows file explorer and another option is like most of other file explorers have, separate option to sort/manage pinned/favorite folders (xyplorer, zabkat,Freecommander, ,..). Just an idea if might help.

**Comment by yaichenbaum** [comment]
@whdmike The feature was implemented using the drag and drop option, however there is currently an issue where drag and drop isn't working https://github.com/microsoft/microsoft-ui-xaml/issues/3290.
