### ISSUE TITLE
fake D: drive that crashes the app

### ISSUE THREAD

**Issue by tal-sitton** [files-community/Files#2019]
**Describe the bug**
there wasn't any USB connected, but it showed that there is. I clicked on it and it crashed

**To Reproduce**
1. Go to the "driver" section
2. Click on "USB drive D:"
3. See error

**Expected behavior**
I don't know, there wasn't any USB connected so I don't know why it showed there is.

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.546
 - App version: v0.15.4.0

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
Please post the log file here so that we can understand your problem better. You can access it from Settings->About->Open log location.

[debug.txt](https://github.com/files-community/Files/files/5317326/debug.txt)

**Comment by jaigak** [comment]
@yair100 This a bug in Windows 10 and I've noticed it too. Explorer hides it but the drive will appear in the disk management tool.
