### ISSUE TITLE
Random quit when in Downloads folder.

### ISSUE THREAD

**Issue by RadioActiveEssence** [files-community/Files#2021]
I had just downloaded a video from my whatsapp web, and was about to delete it because it had downloaded twice. I right-clicked to select delete, but then decided to press delete on the keyobard. The app decided to quit, and i got a windows notification asking me to report the problem. I don't have any screenshots.

OS: Windows 10 Pro 10.0.19042 Build 19042(I am in the Windows Beta Insider programme). 
App Version: 0.15.4.0
[Zip.zip](https://github.com/files-community/Files/files/5321435/Zip.zip)

**Comment by CodeDevTurbo** [comment]
Also i had downloaded the app from the Windows Store

**Comment by yaichenbaum** [comment]
@RadioActiveEssence Is this still an issue in v0.21.1?

**Comment by yaichenbaum** [comment]
Thanks again for your feedback.

_Since we didn't hear from you on this topic for 7+ days, we'll assume everything is worked out and close this feedback item. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this._
