### ISSUE TITLE
Zip File support

### ISSUE THREAD

**Issue by RadioActiveEssence** [files-community/Files#2022]
I have noticed that when opening a Zip file in your app, it opens it in Windows Explorer and not in Files. This is annoying because i have to switch inbetween two file viewers when accessing my Zip files. If this could be fixed then it would be good because it is a basic feature in all File Explorer apps

**Comment by XPoppyX** [comment]
Duplicate of #45

**Comment by RadioActiveEssence** [comment]
Ok. Sorry i didn't realise because that was a long time ago.
