### ISSUE TITLE
Allow drag and drop from other apps

### ISSUE THREAD

**Issue by MangoAJust** [files-community/Files#2023]
**Is your feature request related to a problem? Please describe.**
Yes. I'm always frustrated when, for example, I've got a zip file open with WinRar, I can't drag and drop and I'm forced to use the default (ugly) windows file, explorer.

**Describe the solution you'd like**
I'd like to be able to select a file, drag and drop it, from/to an external app or website, and to be able to move files using drag-and-drop directly in the Files app.

**Describe alternatives you've considered**
I've considered nothing that better and that fast so far

**Comment by erikmf12** [comment]
This feature already exists, although not very intuitive. It works if you drop the file onto one of the address bar folder names. You can also drag a file in the app if you select it first, and then drop the file either on some other app or again on a folder name in the address bar or side bar.

**Comment by gave92** [comment]
Reading around it appears to be a known uwp limitation. UWP can only receive files if they point to physical location on disk.
If you drag a file from e.g winrar it will crash with a `System.Exception Invalid FORMATETC Structure`
I wouln't know how to solve this
(Obviously we can at least handle the error to avoid the crash and show an error message instead)

**Comment by gave92** [comment]
Ok, I found a "very creative" solution to this issue.
1) In Files `DragOver` event handle the `System.Exception: Invalid FORMATETC Structure` that is generated
2) If the exception was caught, the fulltrust process shows a semitransparent window over the Files app
3) The user can drop the files
4) The fulltrust process will copy/move the dropped files to the destination folder

_Please, find a better solution :)_

![ezgif com-gif-maker](https://user-images.githubusercontent.com/9673091/97918798-fdf4bd80-1d56-11eb-9afd-ebc1eb5138da.gif)

**Comment by yaichenbaum** [comment]
> Ok, I found a "very creative" solution to this issue.
> 
> 1. In Files `DragOver` event handle the `System.Exception: Invalid FORMATETC Structure` that is generated
> 2. If the exception was caught, the fulltrust process shows a semitransparent window over the Files app
> 3. The user can drop the files on this window
> 4. The fulltrust process will copy/move the dropped files to the destination folder
> 
> _Please, find a better solution :)_
> 
> ![ezgif com-gif-maker](https://user-images.githubusercontent.com/9673091/97918798-fdf4bd80-1d56-11eb-9afd-ebc1eb5138da.gif)
> 
> _Edit_
> In case you decide to proceed as above the code is [here](https://github.com/files-community/Files/tree/fix_dragdrop).

This doesn't look like such a bad solution, I think we should go for it.

**Comment by gave92** [comment]
@yair100 if you like it, you can give it a try. The code in the branch "fix_dragdrop" should be already working (though based on an old master)

Edit: just saw your PR, if you find issues I may be able to help a little

**Comment by yaichenbaum** [comment]
This issue should be fixed with #2511.
