### ISSUE TITLE
Opening Compressed files (ZIP)

### ISSUE THREAD

**Issue by Atlasim1** [files-community/Files#2026]
**Is your feature request related to a problem? Please describe.**
It isnt really a problem BUT i would like the files beta app to be able to open .ZIP compressed "folders"

**Describe the solution you'd like**
if you try to open a .ZIP file and that your default program is windows explorer it should open it inside of the files beta app insted of windows' explorer.exe

**Describe alternatives you've considered**
not doing  anything i guess is a alternative

**Additional context**
uhh what should i put here this is only a suggestion not a bug report

**Sorry for bad english**

**Comment by Atlasim1** [comment]
this is not a bug
it is a feature request

**Comment by XPoppyX** [comment]
Duplicate of #45

**Comment by duke7553** [comment]
Marking this as a duplicate of #45
