### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by RexTremendae** [files-community/Files#2027]
I installed this project from Windows Store and I already love it! I would like to help out if possible, but following the instructions for cloning and building the project causes VS to report build errors.

![image](https://user-images.githubusercontent.com/6555002/95023522-d76f3400-067d-11eb-80b6-78885dab482e.png)

VS suggested I should install C++ SDK or something like that, which I did.
If some other prerequisites are missing, it would be great to have the instructions describe what is needed.

**Comment by duke7553** [comment]
@RexTremendae Hi there.

Please make sure you have selected Files.Package in Visual Studio. You may also want to try restarting VS and cleaning and rebuilding once you've selected Files.Package and your PCs architecture.

Does this help?

**Comment by RexTremendae** [comment]
No, that did not help. After spending some more time I found out that it has to do with the "Target platform version" on the project Files.Extensions. It seems that I don't have the correct version installed on my system (and I don't know how to get it).

My solution was to change that version on the project to match what is installed on my system. An update to the documentation would really be appreciated to make the experience more smooth for newcomers, something like "Prerequisite: download and install SDK found on <some URL>".

**Comment by duke7553** [comment]
@RexTremendae You can install the required SDKs through Visual Studio Installer under the UWP section.
We require the 19041 SDK

**Comment by RexTremendae** [comment]
Yes, that is exactly what I did and it does not work with the current state of the master branch. Current checked-in version is 18362, when I changed to 19041 it worked.

**Comment by RexTremendae** [comment]
Added PR #2038

**Comment by duke7553** [comment]
@RexTremendae Thanks for catching this inconsistency btw. I think VS would preinstall the 1903 SDK and I always instructed users to install the one for 2004, so that's why I was confused 😊
