### ISSUE TITLE
Slow double click shows rename option

### ISSUE THREAD

**Issue by HentaiOusama** [files-community/Files#2029]
**Describe the bug**
If the double click on a highlighted folder/file is not very fast, then instead of opening the folder/file, it shows the rename option.

**To Reproduce**
1. Single click on any file or a folder
2. Make a normal double click to open that highlighted file
3. (Change the time gap between the two clicks of a double click)
4. Unless the double click is not very very fast, it will show the rename option instead of opening the file / folder

**Expected behavior**
In the normal file explorer (the one that comes with windows) or even on our desktop, even if the time gap between the two clicks of a double click is large, it will be considered as a double click and it opens the files. To enter the rename option, we have to wait like 1-2 seconds before making a single click on a HIGHLIGHTED file / folder to rename it. But in the Files Beat, it's like we have to focus on double click and make the two clicks very very quickly or as on the first click of the double click, it will show the rename option.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 2004]
 - App version: [v0.15.4.0]

**Additional context**
None

**Log file**
None

**Comment by boscorelly** [comment]
i can't reproduce it. I use the same time on explorer and Files, and it works the same way for me

**Comment by HentaiOusama** [comment]
> i can't reproduce it. I use the same time on explorer and Files, and it works the same way for me

Is the file highlighted before making a double click on it?

**Comment by HentaiOusama** [comment]
> Yes

I don't know then.... But for me it definitely shows rename option. Unless I really focus and make the double click very quick. I don't think that i can show it clearly even if i screen recorded it. 😅

**Comment by yaichenbaum** [comment]
This is because of the way the DataGrid is made, an easy work around is to click to the right of the file name and that way you won't run into this issue.
