### ISSUE TITLE
Unable to reach navigation bar in properties

### ISSUE THREAD

**Issue by Thomas1664** [files-community/Files#2040]
**Describe the bug**
In the properties dialog the navigation menu is not reachable via keyboard which prevents users to access shortcut page via keyboard.

**To Reproduce**
1. Open properties for a shortcut
2. Use `Tab` and try to reach navigation bar

**Expected behavior**
Focus should put at navigation view items

**Desktop (please complete the following information):**
 - OS Version: [2004]
 - App version: [`master`]

**Comment by yaichenbaum** [comment]
This issue appears to be resolved in `main`.
