### ISSUE TITLE
Access share

### ISSUE THREAD

**Issue by boscorelly** [files-community/Files#2041]
hi,

when i try to access a root share on my server, ie \\192.168.254.204, when i am originally located on my usb HDD, it loop back to my HDD.

when i try to access a share from the drop down list shown from typing the ip address and clinking on the name of the shared folder, it show this : 
![image](https://user-images.githubusercontent.com/3873787/95187650-b0bf1380-07cb-11eb-9f22-ab88dfd21fd0.png)
![image](https://user-images.githubusercontent.com/3873787/95188029-32af3c80-07cc-11eb-98ba-4801099839d3.png)

BUT ! if i manually enter the shared path, it works

v 0.15.4.0

**Comment by yaichenbaum** [comment]
@boscorelly is this still an issue in v2.0.34?

**Comment by boscorelly** [comment]
nope :)

tested in 2.0.42
