### ISSUE TITLE
Pasting to shared folder/mapped drive doesn't trigger refresh

### ISSUE THREAD

**Issue by boscorelly** [files-community/Files#2042]
Hi,

when pasting to a shared folder or a mapped drive is not causing refresh of the windows as it is done on a local folder, and there is no progress windows shown. It is a problem when pasting large files (WIM file 10Gb ie).

v 0.15.4.0

**Comment by duke7553** [comment]
@boscorelly When you paste many items, does the StatusCenter show a banner during the process?

**Comment by boscorelly** [comment]
@yair100 the issue related is yes linked, but there is no problem when pasting files to local drive

@duke7553 i can't answer : v0.17 is no more workink on network path, i have this error when accessing a shared folder :
Value does not fall within expected range.

**Comment by yaichenbaum** [comment]
Related to #2080.

**Comment by osieltorres** [comment]
Version 0.20.5.0 also happening this issue, current location not refreshed after pasting files, I needed to refresh manually to see new pasted files.

**Comment by Fa310tx** [comment]
This also happens when you have 2 network shares open as different tabs and drag (move) a file between them.
Neither list refreshes, automatically.
JJ

**Comment by ylefebvre** [comment]
A related issue I've experienced is that if I try to create a folder on a network drive, I manually have to refresh before I see the new folder. Should that be logged separately?

**Comment by yaichenbaum** [comment]
@ylefebvre It's probably a similar issue, but can you open a separate issue so we can track it?

**Comment by yaichenbaum** [comment]
@osieltorres This issue should be resolved with #4999.
