### ISSUE TITLE
Support "putting away" a group of tabs for later use in Windows Timeline

### ISSUE THREAD

**Issue by whdmike** [files-community/Files#2043]
**Is your feature request related to a problem? Please describe.**
When you are working with file manager it is always good to be able to minimize app to tray, not to have too many windows open when you don't need them.

**Describe the solution you'd like**
Minimize to tray when you press minimize

**Describe alternatives you've considered**
just that

**Additional context**
thanks for your hard work

**Comment by yaichenbaum** [comment]
@whdmike Can you explain a scenario where this feature would be helpful? The notification tray is not really meant to be used in this way and is discouraged unless there is a good reason for using it.

**Comment by whdmike** [comment]
I don't like to start a file manager all the time, when for example if I work inside of a particular folder. I like to close my file manager to tray, that I don't have too many windows open at the time and when I need again that folder I was working in, I don't need to search for it (open file manager again and search for it). The main reason is that inside windows I prefer not to have too many windows open. At the moment I am using XYplorer, that enables that and I like it, it is practical.

**Comment by yaichenbaum** [comment]
@whdmike Have you enabled the "Continue where you left off" option?

**Comment by whdmike** [comment]
It is not that practical. My thinking was to suggest this feature and if more people like it, do it, if not, it is also ok. Put it to vote. Thanks

**Comment by yaichenbaum** [comment]
The continue where you left off feature is equivalent to minimizing to the tray, but it helps the user know that pressing on the close button is really closing it. In any case, if we did minimize to the tray, it would do the same thing by enabling the continue where you left off option and just relaunching the app for you when you hit the icon.

**Comment by whdmike** [comment]
I appreciate your effort to help me, but I have my own system of working with computer and I don't want to have enabled an option to continue where I left. My default option is to open disc D. And I like minimize to tray when I am working. Thank you for your hard work anyway.

**Comment by yaichenbaum** [comment]
@whdmike I understand your use case for opening by default to your drive, while minimizing the app to keep tabs open. Can you help us by letting us know what you would expect to happen if you launched the app from the taskbar again?

**Comment by whdmike** [comment]
Thanks for reopening. First app lounches faster and you just continue 
where you have been working. I am very practical person and I like 
order. I don't like to have many windows open and for me it turned out 
very practical if I can have a file manager, that I can open and it 
starts with my favourite folder - ususaly I use dual pane explorer like 
Zabkat or XYplorer -  I can minimize it to tray while I don't work with 
it and when I continue I just reopen it. For me it is all about 
practicality and order and working fast. And for you as developer, if 
you make this function and let users choose to enable it inside of 
settings or not, it is a winner. I have also  a business mail (Mailbird) 
that I minimize to tray, I would do it with word processor if it was 
possible. It is just simple, it works for me, if this file manager will 
not have this function, I might not use it, I just suggested, maybe 
someone else would like it.


------ Original Message ------

**Comment by duke7553** [comment]
@whdmike Files already takes advantage of lifecycle features for modern apps which allow us to run in the background for faster startup times. If you're not satisfied with the startup time, please verify you have background app permission enabled for Files in Windows Settings. With this enabled, the app starts as fast as other native apps like Settings and Mail.

![image](https://user-images.githubusercontent.com/20365014/95524976-d3565580-09a0-11eb-8150-918c36f9a314.png)
_Files is prefetched in the background upon first open. As you can see, Files is not currently open but ready to load into memory faster._

Paired with "Continue where you left off" feature, the behavior should be virtually identical to minimizing it to the system tray. 

For these reasons, we have no plan to support system tray integration in Files.

**Comment by duke7553** [comment]
@whdmike We're going to reopen this issue. We gave it some thought, and we like some of the ideas you bring up about wanting to get back into the flow easily. I just don't think the system tray is the best approach for this. We're going to explore allowing users to "put away" a group of tabs to the Windows Timeline for later. This will be an arguably better version than what you mentioned, because users will have more control for _what_ group of tabs they'd like to open.

**Comment by duke7553** [comment]
Sorry for completely misinterpreting your feature idea 🙂

**Comment by yaichenbaum** [comment]
We don't have plans to implement this feature request.
