### ISSUE TITLE
Home page narrator issue

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#2054]
**Describe the bug**
Currently, if you focus a location item on the home page, Narrator says it's a button which it should say so that you can know what it is but it doesn't say the name of it. Maybe ToString isn't implemented for the custom model which .NET uses as the default name to send to Windows

**To Reproduce**
1. Go to home page and focus a location item with keyboard

**Expected behavior**
It should also say the name.

**Desktop (please complete the following information):**
 - OS: 20H2 Release Preview
 - App version: v0.15.5

**Comment by yaichenbaum** [comment]
This is probably since we are not setting the Automation Property name, this needs to be set in the code behind so that the narrator picks it up.

**Comment by jaigak** [comment]
@yair100 Why can't we do it in XAML? Why code behind?

**Comment by yaichenbaum** [comment]
Because the location for each item is different.

**Comment by jaigak** [comment]
@yair100 Well we can do bind that to a string in the model

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran That can work, would you like to work on this?
