### ISSUE TITLE
Can't focus regular sidebar items list with keyboard (only drives)

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#2055]
Can't focus on the regular sidebar items list with the keyboard (only drives section). I need to use the mouse but if I'm blind I can't. Both should be separated and the tab key should move between each section if the navigation view control is focused via keyboard. Today it's not really possible to access these items with the keyboard.

**Comment by duke7553** [comment]
@Jaiganeshkumaran Was this fixed by #2036 ?

**Comment by Jaiganeshkumaran** [comment]
@duke7553 Works now
