### ISSUE TITLE
Some apps executed via Files don't have access to files in a folder

### ISSUE THREAD

**Issue by HenryOfCarim** [files-community/Files#2064]
**Describe the bug**
I have a python app which runs normally via Explorer but via Files, it shows an error which indicates it doesn't have access to files in its folder. Same happens when I try this app in Explorer's Quick Access section. But some sneaky python app is not only one with strange behaviour.  When in the folder with a bunch of pictures you try to open one with MS Photos you won't be able to go to others.

**To Reproduce**
1. Go to a folder with few pictures
2. Open one with MS Photos
3. Try to open another one with scrolling or arrow keys
4. See nothing

**Expected behavior**
MS Photo should see all pictures in the folder
**Screenshots**
The python app in Explorer
![normal](https://user-images.githubusercontent.com/18252816/95663735-48b15a00-0b4a-11eb-8f77-70719f8c2d45.gif)
The python app in Files
![filesUWP](https://user-images.githubusercontent.com/18252816/95663763-7ac2bc00-0b4a-11eb-959c-3ac04774598d.gif)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 2020]
 - App version: [v0.16.0]

**Log file**
Please post the log file here so that we can understand your problem better. You can access it from Settings->About->Open log location.

**Comment by yaichenbaum** [comment]
@HenryOfCarim is this still an issue in v1.5?
