### ISSUE TITLE
Folder should open in new tab if you hold down the Control key while opening it

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#2066]

**Comment by boscorelly** [comment]
hi,

good request ! i will add the suggestion of an option to open in new tab or in new windows, or use the setting existing in settings tab.

**Comment by khiivl** [comment]
middle mouse button would be nice too.

**Comment by yaichenbaum** [comment]
We don't have plans to implement this change as it would get in the way of selecting items.
