### ISSUE TITLE
Error when installing MsixBundle: low version of Microsoft.UI.Xaml

### ISSUE THREAD

**Issue by ZzzzzzzSkyward** [files-community/Files#2070]
I encountered a error that the UI Xaml is outdated(mine 2.4.2005, required 2.4.2007) when installing Msix using Powershell.  
```
Add-AppxPackage "E:\FilesUWP-0.16.Msixbundle"  
```
However I cannot find resolution from Google.  
Everything I tried is install Microsoft.UI.Xaml.2.5 with nuget but it didnt work.  
```
nuget.exe install Microsoft.UI.Xaml
Install-Package Microsoft.UI.Xaml  -Source E:\Microsoft.UI.Xaml.2.5.0-prerelease.200923002\  
```
With the above code I succeeded in downloading a folder with the exactly same name, but nothing happened further. And I'm left confused.

**Comment by yaichenbaum** [comment]
@ZzzzzzzSkyward Have you tried running the msix file outside of Powershell?

**Comment by ZzzzzzzSkyward** [comment]
> 
> 
> @ZzzzzzzSkyward Have you tried running the msix file outside of Powershell?

Excuse me, I am using win10 and I've not installed Visual Studio. I wonder what kind of application I can use to run the msix file. It is foreign to me and I am unable to find any useful ideas.

**Comment by ZzzzzzzSkyward** [comment]
Plus, I have succeeded in installing v0.13, but failed at v0.14.

**Comment by ZzzzzzzSkyward** [comment]
The problem seems to be my Microsoft UI Xaml, which I have no way to update, despite the Install-Package command.

**Comment by lukeblevins** [comment]
@ZzzzzzzSkyward I think @yair100 meant you should try to run the MSIX file by double clicking it.

**Comment by ZzzzzzzSkyward** [comment]
> 
> 
> @ZzzzzzzSkyward I think @yair100 meant you should try to run the MSIX file by double clicking it.

I find the defalut application to run MSIX file is the  Microsoft WinRT Storage, which gives the error information as "invalid registry value".

**Comment by duke7553** [comment]
@ZzzzzzzSkyward Can you post some screenshots?

**Comment by ZzzzzzzSkyward** [comment]
image when double clicking the MSIXBundle(in CHinese):
![图片](https://user-images.githubusercontent.com/55184223/97597044-5dde2200-1a40-11eb-89d9-2100b06bb61a.png)
information when using Powershell to add-appxpackage(in Chinese):
```
add-appxpackage : 部署失败，原因是 HRESULT: 0x80073CF3, 包无法进行更新、相关性或冲突验证。                              Windows 无法安装程序包 49306atecsolution.FilesUWP_0.16.0.0_x64__et10x9a9vyk8t，因为此程序包依赖于一个找不到的框架。请随 要安装的此程序包一起提供由“CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US”发布的框  架“Microsoft.UI.Xaml.2.4”(具有中性或 x64 处理器体系结构，最低版本为 2.42007.9001.0)。当前已安装的名称为“Microsoft.UI .Xaml.2.4”的框架为: {Microsoft.UI.Xaml.2.4_2.42005.18002.0_x86__8wekyb3d8bbwe Microsoft.UI.Xaml.2.4_2.42005.18002.0_x6 4__8wekyb3d8bbwe}                                                                                                       注意: 有关其他信息，请在事件日志中查找 [ActivityId] 20572be8-adee-0005-623f-5820eeadd601，或使用命令行 Get-AppPackageLo
g -ActivityID 20572be8-adee-0005-623f-5820eeadd601
所在位置 行:1 字符: 1
+ add-appxpackage
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (E:\FilesUWP-0.16.Msixbundle:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand
```

**Comment by yaichenbaum** [comment]
@ZzzzzzzSkyward Can you try again with the latest release?

**Comment by yaichenbaum** [comment]
Thanks again for your feedback.

_Since we didn't hear from you on this topic for 7+ days, we'll assume everything is worked out and close this feedback item. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this._

**Comment by ZzzzzzzSkyward** [comment]
update: finally I was able to download Files from Microsoft Store. Somehow it managed to install the application and I'm happily using Files now. :)

**Comment by nono22300** [comment]
HEllo
When downloading MSIXBundle version 1.5 i have this message
Le programme d'installation d'application n’a pas pu installer les dépendances du package. Demandez au développeur le package Microsoft.UI.Xaml.2.5. 

so pb linked to package Microsoft.UI.Xaml.2.5. 

how can i move forward?

Thanks

BR
Nono
