### ISSUE TITLE
Provide a appx(app package) for isntalltion on windows 10 devices

### ISSUE THREAD

**Issue by fisforfaheem** [files-community/Files#2079]
not all people can install through store we need an app package so we could install through usb and enjoy.

**Comment by boscorelly** [comment]
why can't you install through the store ? As it is the aim of a store, i am surprised

**Comment by yaichenbaum** [comment]
@fisforfaheem You can find the latest package on the release page [here](https://github.com/files-community/Files/releases/download/v0.16/FilesUWP-0.16.Msixbundle).

**Comment by fisforfaheem** [comment]
their should be an option for offline distribution of app not everyone has
internet on pc these days :)

**Comment by boscorelly** [comment]
this has no sense : if you want to deploy an online content on computer without internet, at one time, you need to have access to internet...

**Comment by fisforfaheem** [comment]
offline deployment using usb
