### ISSUE TITLE
Add support for Colorize extension

### ISSUE THREAD

**Issue by amartidev** [files-community/Files#2083]
<! -
🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨

RECONOZCO LO SIGUIENTE ANTES DE CONTINUAR:
1. Si elimino toda esta plantilla y sigo mi propio camino, el equipo central puede cerrar mi problema sin más explicaciones o compromisos.
2. Si enumero varios errores / inquietudes en este único problema, el equipo central puede cerrar mi problema sin más explicación o compromiso.
3. Si escribo un problema que tiene muchos duplicados, el equipo central puede cerrar mi problema sin más explicación o compromiso (y sin necesariamente perder tiempo para encontrar el número de identificación duplicado exacto).
4. Si dejo el título incompleto al presentar el problema, el equipo central puede cerrar mi problema sin más explicaciones o compromisos.
5. Si presento algo completamente en blanco en el cuerpo, el equipo central puede cerrar mi problema sin más explicación o compromiso.

¿Todo bien? ¡Entonces proceda!
->

** ¿Su solicitud de función está relacionada con un problema? Por favor describa.**
Una descripción clara y concisa de cuál es el problema. Ex. Siempre me frustra cuando

Re: Mi solicitud esta basada en una función que me gustaría que implementaran.

** Describe la solución que te gustaría **
Una descripción clara y concisa de lo que quieres que suceda.

Re: Me gustaría que implementaran al hacer click derecho sobre una carpeta poder cambiar el color de las carpetas para tener un mejor orden ya que esto ayuda a recordar que archivo tenemos en dicha carpeta.

** Describe las alternativas que has considerado **
Una descripción clara y concisa de cualquier solución o característica alternativa que haya considerado.

Re: Ya que uso una herramienta en el explorador de Windows para cambiar las carpetas de color llamada Colorize pero en el explorador Beta no funciona esta aplicación

** Contexto adicional **
Agregue cualquier otro contexto o capturas de pantalla sobre la solicitud de función aquí. Ej .: ¿Qué tipo de dispositivo / diseño de interfaz de usuario y versión de la aplicación?

![image](https://user-images.githubusercontent.com/72811527/95882018-318b8b80-0d47-11eb-8ac2-2ac7d401f921.png)

**Comment by gave92** [comment]
I don't suppose @yair100 you would accept something like the following to solve this issue, right? (would solve #519 as well I think)

<img src="https://user-images.githubusercontent.com/9673091/96033695-b7e7c080-0e60-11eb-9705-49b607f63b0f.png" width="600"/>
(That is, showing the same icon explorer does)

**Comment by yaichenbaum** [comment]
@gave92 It depends on how the extension works, if all it does is change the folder icon, then I think #519 would solve it. If it works differently then we should explore to find out how it does it.

**Comment by gave92** [comment]
I just tried with that extension and it looks like it works the same as #519 example.
The picture above is real -> you can see that two icons pick up the color set through the Colorize extension

**Comment by yaichenbaum** [comment]
Is there a way to take the icon only when it's a custom one?

**Comment by gave92** [comment]
I don't think you can distinguish whether the icon is a default one using `StorageFolder.GetThumbnailAsync`
You'd probably be able to do this from the fulltrust process..

**Comment by yaichenbaum** [comment]
@gave92 Is this something you can work on?

**Comment by gave92** [comment]
Just to be sure: is the following the expected result?
(All default Files folder icons except for the 2 custom ones)

![Immagine 2020-10-14 213142](https://user-images.githubusercontent.com/9673091/96036673-1616a280-0e65-11eb-94df-283447c46da0.png)

**Comment by duke7553** [comment]
Related: Official support for tagging folders is tracked here: https://github.com/files-community/Files/issues/1161
