### ISSUE TITLE
CTD on opening tabs

### ISSUE THREAD

**Issue by DorukSega** [files-community/Files#2090]
I opened more than one tabs at a fast pace while it was parsing the existing tab and it crashed to desktop, I don't know any symptoms more than that

**Comment by yaichenbaum** [comment]
@DorukSega Can you post the log file?

**Comment by DorukSega** [comment]
sorry, but where can I find it?

**Comment by yaichenbaum** [comment]
You can access it from Settings->About->Open log location.
