### ISSUE TITLE
Code improvements in details page of properties dialog

### ISSUE THREAD

**Issue by Thomas1664** [files-community/Files#2093]
The details page of properties dialog has several issues:
- Property names are not localized
- You can edit read-only properties (e.g. `DateModified`)
- Code needs refactoring

**Comment by Thomas1664** [comment]
@yair100 Can you assign me on this as well?

**Comment by duke7553** [comment]
@Thomas1664 You bet!

**Comment by winston-de** [comment]
@Thomas1664 What changes have you been working on and/or are planning to work on? I'm asking because I have been working on moving the properties to a ListView bound to a single list of properties, and don't want our changes to conflict.

**Comment by Thomas1664** [comment]
@winston-de I didn't chang much of the layout so there should be no conflicts. I focused more on codebehind. My plan is to add translation strings but maybe it is discussable which properties actually need to be on the details tab since some are already included in the general page.

I will open a PR in a few hours.

**Comment by gave92** [comment]
@Thomas1664 while reviewing your PR (nice job anyway!) I found a couple of additional issues with the current implementation of the Details tab:
1- For some file types it will show properties the file doesn't have: e.g ".txt" files don't have a "Title" property
2- For some file types app will crash when clicking "Clear Personal Info" button

**Comment by yaichenbaum** [comment]
@Thomas1664 Do you still plan to work on this issue? #2289 should take care of the code improvements, but the other things on this list should still be done.

**Comment by Thomas1664** [comment]
> @Thomas1664 Do you still plan to work on this issue? #2289 should take care of the code improvements, but the other things on this list should still be done.

@yair100 No. Since @winston-de implemented this feature, he probably knows better than me how to fix the remaining issues.

**Comment by winston-de** [comment]
@yair100 @Thomas1664 
The read only text editing issue has been solved.

As for the localization, I added all the property names to the en-us string resource file, which updated the multilingual resource files. However, I don't have an Azure subscription, so I can't use the Multilingual Editor's translation providers.
