### ISSUE TITLE
When copying and pasting folders, the program will automatically restart

### ISSUE THREAD

**Issue by ColbertBrave** [files-community/Files#2096]
When I copy the folder and paste it to a location, the program restarts. In addition, when I rename the file, the file type is automatically converted to "file" instead of the original file type.

The debug.txt may be helpful.
[debug.txt](https://github.com/files-community/Files/files/5381905/debug.txt)

**Comment by duke7553** [comment]
Thank you for creating this feedback item. This issue is currently resolved in our release branch and should be available from the Microsoft Store. Please subscribe to our releases to be notified when fixes like this are available.
