### ISSUE TITLE
Built-in option to crop an image

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#2099]
**Is your feature request related to a problem? Please describe.**
Today if you need to crop an image, I need to open it with Photos, hit crop, and go back. Since it's opening a separate window, it distracts users and no that quick and first.

**Describe the solution you'd like**
Photos app provides a special service via Launch for results WinRT contract the lets your app access the crop experience in your own app without writing your own or launching it externally.
 
**Describe alternatives you've considered**
None.

**Comment by yaichenbaum** [comment]
We don't have plans to implement this feature.
