### ISSUE TITLE
Video files don't play on dragging

### ISSUE THREAD

**Issue by golamrabbiazad** [files-community/Files#2111]
**Describe the bug**
When I select a video file and then drag it **(which is annoying to me because direct dragging not works)** to the MPC-HC video player it shows on player **link** (other players such as vlc, wmp shows copy on dragging and plays smoothly) and doesn't play that dragged file.

**Expected behavior**
I expected every video file plays on dragged to the player.

**Screenshots**
![capture](https://user-images.githubusercontent.com/35021384/96363684-91bf6a80-1157-11eb-83f7-17c26c75eaee.gif)

**Desktop:**
 - OS Version: [ Windows 10 2004 19041.572]
 - App version: [v0.17.0]

**Logfile**
Please post the log file here so that we can understand your problem better. You can access it from the Settings->About->Open log location.
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5397293/debug_fulltrust.txt)

**Comment by yaichenbaum** [comment]
This issue appears to be resolved with v0.21.1.
