### ISSUE TITLE
[Feature] Always on acrylic

### ISSUE THREAD

**Issue by KristofKekesi** [files-community/Files#2112]
**Is your feature request related to a problem? Please describe.**
When I click on something else than Files, the acrylic is switched to a static color. If there was an option in the settings like '`Always on acrylic`' that would be great. 

**Describe the solution you'd like**
'`Always on acrylic`' switch in the settings

**Comment by gave92** [comment]
I believe this is not allowed by windows. From the docs:
> Background acrylic will replace its translucency and texture with a solid color:
When an app window on desktop deactivates
...
