### ISSUE TITLE
Drag and Drop

### ISSUE THREAD

**Issue by pitchtheripoff** [files-community/Files#2118]
**Is your feature request related to a problem? Please describe.**
I hate that I can't drag stuff into other folders and have to always Ctrl+C Ctrl+V everything. It gets annoying.

**Describe the solution you'd like**
Give us the ability to drag files from folder to folder.

**Describe alternatives you've considered**
I haven't considered any. 

**Additional context**
App version: 0.17.0.0

**Comment by gave92** [comment]
Curious you should be able to. Have you tried clicking on an item first and then click a second time to drag it?
![ezgif com-gif-maker](https://user-images.githubusercontent.com/9673091/96488445-4cc23380-123e-11eb-904b-9fa09c3ffba2.gif)

**Comment by pitchtheripoff** [comment]
> Curious, you should be able to. Have you tried clicking on an item first and then click a second time to drag it?
> 
> ![ezgif com-gif-maker](https://user-images.githubusercontent.com/9673091/96488445-4cc23380-123e-11eb-904b-9fa09c3ffba2.gif)

Yes, I tried that. It seems to not work for stuff like shortcuts.

**Comment by gave92** [comment]
@pitchtheripoff correct shortcuts can't be dragged. (UWP limitation don't know a way around)

**Comment by pitchtheripoff** [comment]
So it's impossible to make shortcuts dragged?

**Comment by gave92** [comment]
Currently it's not possible. Hopefully we can find a way to enable it.

**Comment by pitchtheripoff** [comment]
Oh, that's a bummer. Thank you for elaborating.
