### ISSUE TITLE
Pin option for Copy dialog box, as well more background progress of copying

### ISSUE THREAD

**Issue by komals1** [files-community/Files#2121]
Copy dialog box auto hides every time, please add pin option for that, and as well the process of copying are not accurate and not very interactive, would be great either to see all processes in new tab, or to have UI like the window copy system have, just to interact with it more easily for now.

**Comment by yaichenbaum** [comment]
@duke7553

**Comment by osieltorres** [comment]
Would be great if an independent UI could be added for operations, but different from current implementation, or at least, that the right bottom operation panel shows inmediately after opration starts, it would give to the user better experience as well as notify that the operation is happening. For me, it has happened that I have pasted some copy, but I am never sure that is being happening until I open the panel.

**Comment by duke7553** [comment]
@osieltorres We have plans to improve the Status Center UI, and the first step in doing that involves improving user awareness of the existing UI. PR #2273 will add a new double-pulse animation when a new progress banner is posted. If you have any suggestions for future animations (e.g. operation failure and completion) we'd love to hear it on the PR.

**Comment by duke7553** [comment]
@komals1 Could you be a bit more specific on how you'd like to see the UI and progress reporting improved? Screenshots work great too.

**Comment by duke7553** [comment]
Thanks for your feedback. We're having trouble understanding what you're requesting and need additional information to investigate this item. Please re-open when you've filled out the issue template to the best of your ability.
