### ISSUE TITLE
Make the library cards customizable like the sidebar

### ISSUE THREAD

**Issue by GameBoyYeet** [files-community/Files#2131]
**Is your feature request related to a problem? Please describe.**
No, this feature request is not related to a problem.

**Describe the solution you'd like**
I want a Desktop tile on the Home tab (look at additional context to see what I mean)

**Describe alternatives you've considered**
None

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?
![image](https://user-images.githubusercontent.com/45149431/96805112-aa34bc80-13c5-11eb-9d37-78211e9ecd4d.png)

**Comment by Jaiganeshkumaran** [comment]
Actually, we should make it more customizable and more colourful and add more options.

**Comment by GameBoyYeet** [comment]
I agree with @Jaiganeshkumaran, there should be much more customization like in Windows Explorer

**Comment by yaichenbaum** [comment]
This issue should be resolved with #2802.
