### ISSUE TITLE
Selection rectangle: Don't clear selection if ctrl is pressed

### ISSUE THREAD

**Issue by Thomas1664** [files-community/Files#2137]
**Describe the bug**
When starting selection rectangle and holding CTRL, the current selected item gets deselected.

**To Reproduce**
1. Select an item
2. Hold `CTRL`
3. Trigger selection rectangle

**Expected behavior**
Don't clear selection

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 2009]
 - App version: [master]

**Comment by yaichenbaum** [comment]
@Thomas1664 This issue should be resolved with #2716.
