### ISSUE TITLE
Winrar Icons are flipped

### ISSUE THREAD

**Issue by Lolihunter1337** [files-community/Files#2140]
**Describe the bug**
Some icons are flipped in the right click menu. i can only see this with the winrar icon so not sure if there are more
**To Reproduce**
1. Go to any Winrar file ( or any item where the "winrar options" show )
2. Right click it
3. See the winrar icon flipped

**Expected behavior**
Icon should not be flipped

**Screenshots**
Files UWP 
![image](https://user-images.githubusercontent.com/17437302/97099859-03367600-168e-11eb-91d0-87f5712af388.png)

Explorer
![image](https://user-images.githubusercontent.com/17437302/97099863-12b5bf00-168e-11eb-827c-31d152f084c7.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 2004 (Build 19041.572)
 - App version: [v0.17.3.0]

**Additional context**
Problem stays after restarting or reinstalling

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5434216/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5434217/debug_fulltrust.txt)

**Comment by gave92** [comment]
@Lolihunter1337 thanks for reporting this. I think this was reported before but I could not reproduce it.
What version of winrar do you have installed?

**Comment by Lolihunter1337** [comment]
@gave92 
![image](https://user-images.githubusercontent.com/17437302/97103350-16583e80-16ac-11eb-835e-2b41ec265f17.png)

**Comment by gave92** [comment]
@Lolihunter1337 thanks I can confirm this too
