### ISSUE TITLE
Bug: App crashes when opening a lot of tabs

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#2145]
**Steps to reproduce**
- Open many tabs very quickly by holding CTRL + T.

**Requirements**
Fix crash when opening many tabs

[debug_fulltrust.txt](https://github.com/files-community/Files/files/5434978/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/5434979/debug.txt)

**Comment by yaichenbaum** [comment]
This issue appears to be resolved in `main`.

**Comment by duke7553** [comment]
Reopening to track potential regressions here after #4209

**Comment by yaichenbaum** [comment]
@duke7553 Everything looks good with your latest changes.

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.11.0 or above?

**Comment by yaichenbaum** [comment]
Yes

**Comment by QuaintMako** [comment]
The crash seems to only happen when using the keyboard accelerator. Tried to open 40 tabs at the same time using another path of call. Reducing the accelerator to "one press = one use" should do the trick.

**Comment by yaichenbaum** [comment]
Seems like a reasonable solution, I think we do something similar with the back/forward buttons.

**Comment by QuaintMako** [comment]
Are you talking about those accelerators?

![image](https://user-images.githubusercontent.com/110472580/198656088-0751ad58-a13d-4ad1-9845-ad71c9cfa66f.png)

**Comment by yaichenbaum** [comment]
It might have actually been the refresh button but similar idea.

**Comment by QuaintMako** [comment]
@gave92 the work done in #10648 doesn't seem to fix that issue for me. Is there some work left to do on the basis of it?

**Comment by gave92** [comment]
Could be, as I could never reproduce the issue in the first place.
But I expected #10648 to have the same effect as #10385 (wait until a tab has been opened before adding the next tab). Does #10385 fix the issue if applied on current `main`?

**Comment by QuaintMako** [comment]
#10385 does not seem to solve the crash entirely anymore. If anything, it makes the issue a lot less worse. 

Instead of crashing after 1 tab on `main` when holding the shortcut, it crashes after ~70 tabs for me. Better, but still not a fix.

I'm closing #10385 to investigate a better solution.

**Comment by yaira2** [comment]
@QuaintMako I opened an issue to track your idea for solving this #11737.
