### ISSUE TITLE
Tab bar does interfere with close, minimize and maximize button

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#2146]
1. Use the app in full screen mode
2. Create so many tabs that the whole screen width is used
![image](https://user-images.githubusercontent.com/17484252/97111761-de1f2300-16e0-11eb-8c55-fbd2c46d8d14.png)

3. Resize the app window
![image](https://user-images.githubusercontent.com/17484252/97111770-ea0ae500-16e0-11eb-8a76-6cb189d35f84.png)

4. Use the app again in full screen mode
5. Note how the tab bar now covers the app buttons in the top right corner.
![image](https://user-images.githubusercontent.com/17484252/97111779-f42ce380-16e0-11eb-8802-4d12697a6450.png)

**Comment by gave92** [comment]
Looks like #2024
