### ISSUE TITLE
KERNELBASE.dll Crash

### ISSUE THREAD

**Issue by Jackaroo05** [files-community/Files#2150]
Hello. Every once in a while, the application crashes with that action center pop up and when I go to event viewer, It shows that it crashed from KERNELBASE.dll.

I am running the beta.

`Faulting application name: Files.exe, version: 1.0.0.0, time stamp: 0x5f94e799
Faulting module name: KERNELBASE.dll, version: 10.0.19041.572, time stamp: 0x1183946c
Exception code: 0xc000027b
Fault offset: 0x000000000010b65c
Faulting process id: 0x4318
Faulting application start time: 0x01d6aaf20b5df6cf
Faulting application path: C:\Program Files\WindowsApps\49306atecsolution.FilesUWP_0.17.3.0_x64__et10x9a9vyk8t\Files.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: d3e82df7-0450-4140-bf1c-57f167d11af8
Faulting package full name: 49306atecsolution.FilesUWP_0.17.3.0_x64__et10x9a9vyk8t
Faulting package-relative application ID: App`

**Comment by gave92** [comment]
@Jackaroo05 could you post the app's log files? You can access them from Settings->About->Open log location. Thanks!

**Comment by duke7553** [comment]
@Jackaroo05 Thanks again for your feedback. 

_Since we didn't hear from you on this topic for 7+ days, we'll assume everything is worked out and close this feedback item. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this._

**Comment by nayar34** [comment]
I have a customer who is receiving this error on two devices with OneDrive crashing.  They started to get this after upgrading to 2004 on one device and upgrading to 20H2 on the other device. 

Log Name:      Application
Source:        Application Error
Date:          11/2/2020 2:55:37 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      
Description:
Faulting application name: OneDrive.exe, version: 20.169.823.8, time stamp: 0xb1f6c17e
Faulting module name: KERNELBASE.dll, version: 10.0.19041.572, time stamp: 0x979ddb1d
Exception code: 0x80000003
Fault offset: 0x0015f592
Faulting process id: 0x10f4
Faulting application start time: 0x01d6b16b3c744bf6
Faulting application path: C:\Users\StacieCapelli\AppData\Local\Microsoft\OneDrive\OneDrive.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 6f78bc92-fdd8-4e54-a34c-94bf7a42c12a
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-11-02T22:55:37.9687478Z" />
    <EventRecordID>2634</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>NDWE-SC-LT</Computer>
    <Security />
  </System>
  <EventData>
    <Data>OneDrive.exe</Data>
    <Data>20.169.823.8</Data>
    <Data>b1f6c17e</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.19041.572</Data>
    <Data>979ddb1d</Data>
    <Data>80000003</Data>
    <Data>0015f592</Data>
    <Data>10f4</Data>
    <Data>01d6b16b3c744bf6</Data>
    <Data>C:\Users\StacieCapelli\AppData\Local\Microsoft\OneDrive\OneDrive.exe</Data>
    <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data>
    <Data>6f78bc92-fdd8-4e54-a34c-94bf7a42c12a</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>


- EventData 

   OneDrive.exe 
   20.169.823.8 
   b1f6c17e 
   KERNELBASE.dll 
   10.0.19041.572 
   979ddb1d 
   80000003 
   0015f592 
   10f4 
   01d6b16b3c744bf6 
   C:\Users\StacieCapelli\AppData\Local\Microsoft\OneDrive\OneDrive.exe 
   C:\WINDOWS\System32\KERNELBASE.dll 
   6f78bc92-fdd8-4e54-a34c-94bf7a42c12a
