### ISSUE TITLE
Win+E

### ISSUE THREAD

**Issue by Eyji** [files-community/Files#2159]
**Is your feature request related to a problem? Please describe.**
Open the file manager with the standard Win+E shortcut.

**Describe the solution you'd like**
An option to activate the Win+E shortcut

**Describe alternatives you've considered**
- Switching back to Microsoft's solution
- Edit the registry myself
- Replace the file manager but it's unsupported, right ?

**Additional context**
Win+E is a lifesaver. I need Win+E because it's cute and it appreciates my personality.

**Comment by yaichenbaum** [comment]
The best option is to try editing the registry or to use software to remap the keys. We don't plan to edit the registry from the app because it can cause issues if the user were to uninstall the app at some point.

**Comment by skyduy** [comment]
You can do this by compiling this script with AutoHotKey:
```ahk
FilesUWPTitle := "Files ahk_class ApplicationFrameWindow ahk_exe ApplicationFrameHost.exe"
FilesUWPLocation := USERPROFILE . "\AppData\Local\Microsoft\WindowsApps\files.exe"

; Win + E
#e::
    if WinExist(FilesUWPTitle) {
        WinActivate % FilesUWPTitle     ; Set focus
        SendInput ^t                    ; Send CTRL + t shortcut to open a new tab
    } else {
        Run % FilesUWPLocation          ; Start FilesUWP
        WinWait % FilesUWPTitle         ; Wait for it ...
        WinActivate % FilesUWPTitle     ; Set focus
    }
return
```

**Comment by yaichenbaum** [comment]
@skyduy Thank you for sharing that, I created a [Wiki ](https://github.com/files-community/Files/wiki/Configuring-Files-to-launch-with-Win---E-shortcut)page for it.
