### ISSUE TITLE
Files as default explorer

### ISSUE THREAD

**Issue by Diazz72** [files-community/Files#2161]
Hi, is there an option to make File a default explorer ( for example in Chrome if I select Show file to open it in Files ), if not...is there a plan to add this feature in the future ( if possible )?

Regards, Diazz72.

**Comment by gave92** [comment]
There is procedure you can follow to achieve this -> see [here](https://github.com/files-community/Files/wiki/Replacing-File-Explorer-with-Files-(Unsupported)).
But I think it has more downsides than ups (e.g losing access to control panel).

**Comment by Diazz72** [comment]
Thanks, this will be gr8 :).
