### ISSUE TITLE
Files crashes when attempting to access unmounted ISO

### ISSUE THREAD

**Issue by fasolatha** [files-community/Files#2164]
**Describe the bug**

**To Reproduce**
1. Ensure that there is ISO mounted via Windows Explorer.
2. "Eject" said ISO from Windows Explorer
3. Attempt to view file contents from ISO mount path in Files under Drives

**Expected behavior**
ISO should be removed dynamically when Ejected from Windows E
[debug.txt](https://github.com/files-community/Files/files/5448739/debug.txt)
xplorer or options to 'Eject' media via Drives in Files.

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
Please post the log file here so that we can understand your problem better. You can access it from Settings->About->Open log location.

**Comment by igoragm** [comment]
This is basically the same issue as #2190 
@yair100 Could you assign me please, I can modify my initial solution for the #2190 to handle a wider range of exceptions.
