### ISSUE TITLE
OneDrive

### ISSUE THREAD

**Issue by Hockenhorn** [files-community/Files#2172]
**Describe the bug**
Opened the synchronized OneDrive folder. Opened a Word sheet and added a letter and saved. An error message appears and the app closes.

**To Reproduce**
1. Open the synchronized OneDrive folder with "Files - Preview"
2. Open a word file in this folder
3. Add a letter to the document
4. Save the document
5. "Files - Preview" closes and an error message appears.

**Expected behavior**
-

**Screenshots**
![image](https://user-images.githubusercontent.com/73600301/97504550-63236a00-1977-11eb-9624-7ce720d9908e.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10
 - App version: V0.17.0

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5455189/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5455190/debug_fulltrust.txt)

**Comment by gave92** [comment]
@Hockenhorn thanks for reporting this.
From the stacktrace I believe this issue happens when temporary files are created and quickly deleted (which often  happens when Word is saving files and/or OneDrive is syncing)
