### ISSUE TITLE
Thumbnails for images appears only after opening them in MS Photos

### ISSUE THREAD

**Issue by Tester09** [files-community/Files#2175]
**Describe the bug**
In folders with many images, Files shows blank icons on some of them and they remain the same even after pressing F5, to fix it you should open every image with the blank icon with the MS Photos and after this press F5

**Expected behavior**
Thumbnails should generate after pressing F5

**Screenshots**
![image](https://user-images.githubusercontent.com/18252816/97646679-f2547e80-1a58-11eb-9c3c-2d5bd3e9f076.png)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 2004]
 - App version: [v0.18.0]

**Comment by yaichenbaum** [comment]
@Tester09 Can you still reproduce this issue in v0.23.1?

**Comment by HenryOfCarim** [comment]
@yair100 Everything looks OK now
