### ISSUE TITLE
Use accent color for selection rectangle

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#2186]

**Comment by scriptBoris** [comment]
I completely agree. Otherwise, it turns out that the program looks gray

**Comment by scriptBoris** [comment]
![Uploading image.png…]()

**Comment by Jaiganeshkumaran** [comment]
@scriptBoris This is about the recently added cursor selection being blue always instead of the system settings but I don't like the trend of gray backgrounds.

**Comment by scriptBoris** [comment]
> @scriptBoris This is about the recently added cursor selection being blue always instead of the system settings but I don't like the trend of gray backgrounds.

Sorry, my bad. BUT Drive "SSD" can't see line? Or am I wrong?

**Comment by Jaiganeshkumaran** [comment]
@scriptBoris Can you open an issue about that? It supposed to fill used/free space with different colors.

**Comment by scriptBoris** [comment]
> @scriptBoris Can you open an issue about that? It supposed to fill used/free space with different colors.

Will be done

**Comment by scriptBoris** [comment]
> @scriptBoris Can you open an issue about that? It supposed to fill used/free space with different colors.

Sorry, this problem occurs when using this color in Windows 10
![image](https://user-images.githubusercontent.com/29772096/98464796-20c41d80-2200-11eb-8995-fc99f0dc14ec.png)

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran This issue should be resolved with #2650.
