### ISSUE TITLE
In Recent item: It will be much better if you include the option in setting to show recently accessed file and not to show recently accessed file option 

### ISSUE THREAD

**Issue by yaba101** [files-community/Files#2187]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by yaba101** [comment]
In Recent item: It will be much better if you include the option in setting to show recently accessed file and not to show recently accessed file option!

**Comment by yaichenbaum** [comment]
@yaba101 We are having trouble understanding this proposal, can you please add a little more context to help us understand this feature request?

**Comment by yaichenbaum** [comment]
Thanks again for your feedback.

_Since we didn't hear from you on this topic for 6+ days, we'll assume everything is worked out and close this feedback item. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this._
