### ISSUE TITLE
Add a drives widget to the home page

### ISSUE THREAD

**Issue by askfriends** [files-community/Files#2188]
I have a feature request, so i am bypassing template.

I cant select "This PC"  in startup settings, it says "you cant open this location in this app...." so please add option to use this location on startup, because sometimes i want to see how much space is used or free in each drive.

**Comment by yaichenbaum** [comment]
@askfriends This will be an option once a drives widget is added as proposed in #366.

**Comment by yaichenbaum** [comment]
@askfriends This has been implemented with #2196.

**Comment by askfriends** [comment]
> @askfriends This has been implemented with #2196.

thanks, thats really great.
but i still cant see that option, when this update will be released?

**Comment by yaichenbaum** [comment]
@askfriends This was included in v0.19, you should be able to get the update from the Microsoft Store.
