### ISSUE TITLE
Add Office programs to the New menu in the Context (right click) menu

### ISSUE THREAD

**Issue by Nuzza** [files-community/Files#2192]
**Is your feature request related to a problem? Please describe.**
Basically, File Explorer has a really useful feature that Files UWP doesn't have which allows the user to easily create Word, PowerPoint, Excel, etc files in the current directory right from the New menu in the context (right click) menu.

**Describe the solution you'd like**
Depending if Office is installed on the user's device, show the Office programs within the New menu of the context menu.

**Describe alternatives you've considered**
Why yes, there are alternatives to achieve this by saving the file to the directory, simply allowing the ability to right click, select New, and selecting Microsoft Word Document, etc would be greatly beneficial for the user.

**Additional context**
![image](https://user-images.githubusercontent.com/29596317/97793304-3d79b780-1c3a-11eb-8b35-31d041f463c0.png)
![image](https://user-images.githubusercontent.com/29596317/97793311-49fe1000-1c3a-11eb-82b3-67f87e9c5343.png)

**Comment by yaichenbaum** [comment]
@Nuzza This issue should be resolved with #2644.

**Comment by Nuzza** [comment]
Awesome, thanks for implementing the idea.
