### ISSUE TITLE
能不能设计个exe版的，UWP版本权限太低了

### ISSUE THREAD

**Issue by moshiangel** [files-community/Files#2194]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
Please post the log file here so that we can understand your problem better. You can access it from Settings->About->Open log location.

**Comment by gave92** [comment]
"Can you design an exe version, the UWP version permissions are too low"

Thanks for reporting this, merging with #1194
