### ISSUE TITLE
 A window with a list of all disks and their content, different designs of plates that appear when you hover over a file

### ISSUE THREAD

**Issue by dkostarnov** [files-community/Files#2206]
I would very much like a window, like in a stranded explorer, where you can see the load on system drives and other drives. Don't really like the design of highlighting files on hover, maybe do it like in the "Search" menu in the Windows 10 2004 panel, but slightly reduce the shadows? Also, if Files is open in full screen, this selection is very long, can it be cropped to the "size" table? The volumetric selection will just fit.

I hope that in the future these ideas will appear in Files and I can install this explorer as standard :)

**Comment by yaichenbaum** [comment]
@dkostarnov Can you please share some concepts and add to your description to better help us understand your proposal?

**Comment by dkostarnov** [comment]
> @dkostarnov Can you please share some concepts and add to your description to better help us understand your proposal?


As it turns out, you've already introduced a special widget to display disk usage. Well, it will be easier for me to describe a proposal for too long a choice in contention, dkostarnov # 0991
