### ISSUE TITLE
App crashes on launch

### ISSUE THREAD

**Issue by notgarette** [files-community/Files#2208]
**Describe the bug**
The app will not open at all -- it crashes on startup. You cannot use the app at all due to this.

**To Reproduce**
1. Open app
2. Wait 1-2 seconds
3. App crashes

**Expected behavior**
The app opens and is navigable.

**Screenshots**
This is as far as the app gets without crashing.
![image](https://user-images.githubusercontent.com/41551490/97903538-32438c00-1d0d-11eb-92cb-68a77aabbb65.png)

**Desktop (please complete the following information):**
 - OS: 20H2 OS Build 19042.572
 - App version: [v0.18.0]

**Additional context**
I've used the releases from this github and I've downloaded Files from Microsoft Store. This has been happening for roughly 5-6 months, possibly longer.

**Log file**
Unable to navigate to settings to get log files. Is there a directory I can manually go to?

**Comment by gave92** [comment]
You can find them here `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`

**Comment by notgarette** [comment]
Hey, sorry for the delay, had issues with power.
[debug.txt](https://github.com/files-community/Files/files/5489099/debug.txt)

**Comment by yaichenbaum** [comment]
@notgarette Is this still an issue in v1.3?

**Comment by notgarette** [comment]
Yessiir, the app still crashes on launch. It actually seems to crash a little bit earlier than before. It now crashes at the startup splash screen rather than a blank view of the UI.

**Comment by gave92** [comment]
@notgarette could you upload the log file again?

**Comment by notgarette** [comment]
[debug.txt](https://github.com/files-community/Files/files/6179027/debug.txt)
Here you go--thanks for the help.

**Comment by notgarette** [comment]
I took ownership and enabled every permission of "**%localappdata%\Packages\**" and the log file is identical.

**Comment by notgarette** [comment]
Fixed on the latest version -- thanks!

**Comment by yaichenbaum** [comment]
@notgarette Thanks for the update!
