### ISSUE TITLE
Highlighting after selecting folder on the sidebar doesn't turn off 

### ISSUE THREAD

**Issue by Tester09** [files-community/Files#2212]
**Describe the bug**
When you selecting some folder from the sidebarr highlighting effect stand still and doesn't turn off

![image](https://user-images.githubusercontent.com/18252816/97943472-2697aa00-1d8d-11eb-83e2-13f59c2cf7cc.png)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 2004 20246]
 - App version: [v0.18.1]

**Comment by yaichenbaum** [comment]
This issue is fixed in the master branch.
