### ISSUE TITLE
Please add an option to disable the "double-click rename" feature.

### ISSUE THREAD

**Issue by MashukeAlam** [files-community/Files#2218]
**Is your feature request related to a problem? Please describe.**

Yes, the feature request is related to a problem. The problem is double click to rename. **In Windows' default File Explorer which has double-click rename feature which is already disgusted by many. This Files app that you guys are creating for the good for all of us (thanks for that though!) shouldn't have that feature. It's conflicting behaviour when opening a file is annoying.** That's why I'm suggesting to add an option to disable this double-click rename fuction. 

**Describe the solution you'd like**

I'd like to have a radio button type toggler to turn this functionality off. Like a "Disable double click to rename" toggle button. 

**Describe alternatives you've considered**

_Or we can just get rid of the whole double click rename thing. Bet it is not widely used. _

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

Device type: Lenovo Laptop 
App version: Latest Beta

**Comment by yaichenbaum** [comment]
@MashukeAlam Please fill out the issue template with details such as the version number.

**Comment by MashukeAlam** [comment]
> @MashukeAlam Please fill out the issue template with details such as the version number.

Sorry for that. I'm new here... Can you please guide me where to fill this template that you are talking about.

**Comment by MashukeAlam** [comment]
> > @MashukeAlam Please fill out the issue template with details such as the version number.
> 
> Sorry for that. I'm new here... Can you please guide me where to fill this template that you are talking about. 

Owh got it...

**Comment by yaichenbaum** [comment]
@MashukeAlam Can you provide details on how it interferes with opening items? We added a considerable delay to prevent this issue so a screen recording would help.

**Comment by yaichenbaum** [comment]
Thanks again for your feedback.

_Since we didn't hear from you on this topic for 7+ days, we'll assume everything is worked out and close this feedback item. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this._
