### ISSUE TITLE
Pasting file from Remote Desktop to local PC causes crash

### ISSUE THREAD

**Issue by GSonofNun** [files-community/Files#2220]
**Describe the bug**
If I am connected to a remote PC through Remote Desktop Connection, and I copy a file from that remote PC, then try to paste  it in this app on the local PC, this app will crash.

**To Reproduce**
1. Connect to Remote PC via Remote Desktop Connection
2. Copy file from Windows Explorer on Remote PC
3. Open Files app on Local PC
4. Navigate to a directory (I navigated to the Desktop directory)
5. Right-click on background to open context menu
6. Click Paste
7. Observe crash

**Expected behavior**
I would expect a normal file copy operation to happen.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.572
 - App version: v0.18.0.0

**Additional context**
N/A

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5483917/debug.txt)

**Comment by gave92** [comment]
Thanks for this feedback! Sadly common issue, merging with #2023
