### ISSUE TITLE
Paste option in context menu doesn't always enable

### ISSUE THREAD

**Issue by GSonofNun** [files-community/Files#2221]
**Describe the bug**
When copying from Windows Explorer to Files, the Paste command in the context menu is disabled until you navigate to a different directory.

**To Reproduce**
1. Open Files and navigation to a directory (i.e. Desktop)
2. Open Windows Explorer, find a file, and copy it
3. Right-click in Files, Paste shows as disabled
4. Navigate to other directory in Files
5. Right-click in Files, Paste now shows as enabled

**Expected behavior**
I expect the Paste command to be enabled

**Screenshots**
![image](https://user-images.githubusercontent.com/3924712/98038780-b2402380-1deb-11eb-9404-3163f8c8c9fe.png)
Copying from Explorer

![image](https://user-images.githubusercontent.com/3924712/98038828-c08e3f80-1deb-11eb-9ea1-11b7e8f584c6.png)
Paste Disabled in Files

![image](https://user-images.githubusercontent.com/3924712/98038915-e4ea1c00-1deb-11eb-9abe-57a721ff41e7.png)
Now Paste is enabled after navigating to a different directory

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.572
 - App version: v0.18.0.0

**Additional context**
N/A

**Log file**
(There doesn't appear to be anything useful to this bug in the log file)

**Comment by yaichenbaum** [comment]
@GSonofNun This issue should be fixed with #2792.
