### ISSUE TITLE
Feature request: Teracopy / Teramove support

### ISSUE THREAD

**Issue by Firehawke** [files-community/Files#2222]
I find that TeraCopy provides the best overall copy/move experience on Windows and I would like to be able to have the option to have Files use TeraCopy for file copy and move operations.

Perhaps a settings switch (defaulting to off, of course) that has all appropriate file operations go to TeraCopy when it's detected on the machine is most appropriate here. Defaulting to 'off' makes the most sense if it was implemented.

**Comment by gave92** [comment]
Doesn't TeraCopy add items to the right-click context menu for files and folders? Like a "copy with TeraCopy" contextmenu?
If yes those items should be working in Files

**Comment by yaichenbaum** [comment]
Thanks again for your feedback.

_Since we didn't hear from you on this topic for 7+ days, we'll assume everything is worked out and close this feedback item. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this._

**Comment by Firehawke** [comment]
Sorry, I'm really late in responding-- I've had serious internet issues.

No, Files does not actually show it in the right click menu.

![image](https://user-images.githubusercontent.com/34792592/99026219-be348f80-2527-11eb-8f9c-a0289c4cd5a3.png)

**Comment by gave92** [comment]
@Firehawke at least for me the "teracopy" context menu item is present and working.

![image](https://user-images.githubusercontent.com/9673091/99156902-34222d80-26c5-11eb-995f-f4ac1ce6efd0.png)

I understand that anyway this is not as handy as having TeraCopy as the default copy handler, where drag and drop and ctrl-c/ctrl-v automatically use TeraCopy..
