### ISSUE TITLE
Custom folder icons appear blurred

### ISSUE THREAD

**Issue by Cyberdroid1** [files-community/Files#2229]
**Describe the bug**
I have used registry to change the default folder icon to a custom one. While the folder icons appear crisp in windows explorer, the Files app makes them look blurred. 

**Expected behavior**
The blur should not have been there. 

**Screenshots**

![image](https://user-images.githubusercontent.com/51435948/98138234-e77e6b80-1ee8-11eb-88a1-4fd77bc00b38.png)
Windows explorer

![image](https://user-images.githubusercontent.com/51435948/98138318-fbc26880-1ee8-11eb-96f2-9a62f9eabaa0.png)
Files app

![image](https://user-images.githubusercontent.com/51435948/98139089-c8340e00-1ee9-11eb-9398-3e3615d17ab9.png)
Comparison

(try zooming in to see the blur)

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 2009 19042.572]
 - App version: [v0.19.0]

**Additional context**
The icon files that I use are 1024x1024, and also appear clear in the windows explorer.

**Comment by XPoppyX** [comment]
This happens with all icons and thumbnails. I submitted a feature request about that: #1152

**Comment by gave92** [comment]
Merging it with #1152
