### ISSUE TITLE
Selecting an item, deselecting it and then selecting it again triggers rename

### ISSUE THREAD

**Issue by XPoppyX** [files-community/Files#2231]
When you want to rename with double click you must first select the item and then click again. But if you cancel and try to do it again with **the same item**, the rename function starts with a single click.

As you can see in the gif, in the first attempt it works correctly, the rename function starts in the second click after selecting first.
**But from the second time, it starts with a single click**

![rename3](https://user-images.githubusercontent.com/61259627/98165025-ed158a80-1ec3-11eb-93fc-8d9e2cbf131b.gif)

**Comment by yaichenbaum** [comment]
@XPoppyX Is this still an issue in v0.21.1?

**Comment by generalguy41** [comment]
@yaichenbaum I can reproduce it in 0.21.1.0

**Comment by XPoppyX** [comment]
@yaichenbaum yes, it is still an issue with the latest changes to "master"

**Comment by yaichenbaum** [comment]
@XPoppyX This issue should be solved with #2813.
