### ISSUE TITLE
Issues with responsive design of the new drives widget

### ISSUE THREAD

**Issue by crashmit** [files-community/Files#2236]
**Describe the bug**
Currently, the maximum capacity number of a drive, gets cut off under specific window widths instead of breaking to a new line or moving elements below. This happens in english as well as german. This is a minor issue as you still have the graph above but is still worth adressing imo.

**Screenshots**
![image](https://user-images.githubusercontent.com/58466626/98219045-cf403800-1f4c-11eb-9de6-fd76020a3ea0.png)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 2004]
 - App version: [v0.19.0]

**Comment by yaichenbaum** [comment]
@crashmit You can hover over the widget to see a tooltip with the full text.

**Comment by crashmit** [comment]
> @crashmit You can hover over the widget to see a tooltip with the full text.

Thank you, this was less a usability issue and more a design problem :) Therefore really low priority

**Comment by Jaiganeshkumaran** [comment]
Actually, we could wrap the text so it fills the screen and goes to the new line. This will be better.

**Comment by crashmit** [comment]
I thought this whole issue was due to me having too many drives, but even on my laptop that only has one drive, the text gets cut off, which doesn't really make sense, considering the amount of space, there is.

![image](https://user-images.githubusercontent.com/58466626/98831912-76850980-243c-11eb-8d7b-2238388e860e.png)
