### ISSUE TITLE
Feature: Add an option to consolidate nested paths consisting of multiple empty directories to single

### ISSUE THREAD

**Issue by dkgv** [files-community/Files#2238]
### What feature or improvement do you think would benefit Files?
It would be neat if a GitHub-like feature was added that consolidated multiple empty directories into single entry, allowing for rapid navigation of nested content.

As an example, 1 click on GitHub would take me directly to `gradle/wrapper` instead of first to `gradle` and then afterwards to `wrapper`.
![image](https://user-images.githubusercontent.com/11279580/98240801-43d59f80-1f6a-11eb-9041-abe9de36018d.png)

### Requirements

- 

### Files Version

2.3.11.0

### Windows Version

10.19043.1899

### Comments

Would need to consider the fact that it in some cases might be desirable to navigate to `gradle` rather than `wrapper`. Perhaps this could be toggled via a hover timer, i.e. if user hovers >1s-2s before clicking, they should be allowed to pick from the individual directories that make up the consolidated entry. Alternatively, straight up allow each individual directory to be clickable through their own UI component but display in a compact manner like GitHub does.

**Comment by kleenkanteen** [comment]
> if user hovers >1s-2s before clicking, they should be allowed to pick from the individual directories that make up the consolidated entry.
Are you saying when hovering it should collapse automatically and show all individual directories?

**Comment by kleenkanteen** [comment]
> **Is your feature request related to a problem? Please describe.**
> It would be neat if a GitHub-like feature was added that consolidated multiple empty directories into single entry, allowing for rapid navigation of nested content.
> 
> **Describe the solution you'd like**
> As an example, 1 click on GitHub would take me directly to `gradle/wrapper` instead of first to `gradle` and then afterwards to `wrapper`.
> ![image](https://user-images.githubusercontent.com/11279580/98240801-43d59f80-1f6a-11eb-9041-abe9de36018d.png)
> 
> **Additional context**
> Would need to consider the fact that it in some cases might be desirable to navigate to `gradle` rather than `wrapper`. Perhaps this could be toggled via a hover timer, i.e. if user hovers >1s-2s before clicking, they should be allowed to pick from the individual directories that make up the consolidated entry. Alternatively, straight up allow each individual directory to be clickable through their own UI component but display in a compact manner like GitHub does.

test

**Comment by yaichenbaum** [comment]
I'm not a fan of this behavior but I'm curious what use cases there are for implementing.
