### ISSUE TITLE
Drives widget storage details don't update without reopen

### ISSUE THREAD

**Issue by generalguy41** [files-community/Files#2242]
**Describe the bug**
Drives widget storage details don't update without reopen of Files.

**To Reproduce**
1. Go to the Home page.
2. Note the size of a drive.
![image](https://user-images.githubusercontent.com/8879244/98316259-10b20100-1fa8-11eb-92da-c3ec87b71a06.png)
3. Change the files in that drive (delete everything, add a big file, etc.)
![image](https://user-images.githubusercontent.com/8879244/98316307-27585800-1fa8-11eb-9116-d9a7c602d59d.png)
4. Go back to the Home page. The size won't be updated no matter if you switch directories. Only updates if you restart/open a new window.
![image](https://user-images.githubusercontent.com/8879244/98316649-d006b780-1fa8-11eb-83aa-4c5593d133c0.png)

**Expected behavior**
Drives should refresh on navigation to the Home page.

**Desktop:**
 - OS Version: Windows 10 2004 20246.1
 - App version: v0.19.0.0

**Comment by timsu92** [comment]
Addition to this, I have another feature request：enable the refresh button in home page to do this job, so we can either go to another folder and come back or just refresh this page to see the refreshed disk capacity.

**Comment by yaichenbaum** [comment]
@generalguy41 Is this still an issue in v1.5?

**Comment by josh-65** [comment]
Any updates on this been added/fixed I have also noticed it doesn't update drive space changes.

**Comment by yaichenbaum** [comment]
> Any updates on this been added/fixed I have also noticed it doesn't update drive space changes.

@josh-65 we haven't worked on this yet.

**Comment by Duckloveshack** [comment]
Bumping issue. Still wasn't fixed, and it's annoying to re-open Files just to view the free space in my volumes.

**Comment by yaichenbaum** [comment]
> Bumping issue. Still wasn't fixed, and it's annoying to re-open Files just to view the free space in my volumes.

Thank you for your feedback, this issue is currently on our todo list, but we don't have a timeline for when it will be fixed.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #9235
