### ISSUE TITLE
Program crash when disk if full.

### ISSUE THREAD

**Issue by yxhl** [files-community/Files#2243]
2020-11-03 10:45:11.4446|INFO|Files.Filesystem.DrivesManager|Drive added: Z:\, Network|
2020-11-06 10:36:21.4477|ERROR|Files.App|The disk is full. (Exception from HRESULT: 0x80070027)|System.Exception: The disk is full. (Exception from HRESULT: 0x80070027)
2020-11-06 10:36:36.7469|INFO|Files.App|App launched|

**Comment by yaichenbaum** [comment]
@yxhl Can you please fill out the issue template?

**Comment by yxhl** [comment]
**Describe the bug**
Program crash when disk if full. 

**To Reproduce**
Steps to reproduce the behavior:
1. I open two remote directory A and B though samba.
2. I copy a directory from dir A to dir B.
3. the program crash.
4. I see the log show disk is full error.

**Expected behavior**
Commenting me the disk full and stop action but not crash.


**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 2004 19041.508]
 - App version: [v0.19.0]

**Additional context**

**Log file**
2020-11-06 10:36:21.4477|ERROR|Files.App|The disk is full. (Exception from HRESULT: 0x80070027)|System.Exception: The disk is full. (Exception from HRESULT: 0x80070027)
2020-11-06 10:36:36.7469|INFO|Files.App|App launched|

**Comment by duke7553** [comment]
@yxhl Can you check if the crash occurs in the latest version from the Store?

**Comment by yxhl** [comment]
> @yxhl Can you check if the crash occurs in the latest version from the Store?

The latest version I've seen in Strore is V0.19.0. It's the same as the crashed version. And my disk has been cleaned by me, so I can't test it any time soon

**Comment by yaichenbaum** [comment]
@yxhl v0.20 just rolled out, can you try updating?

**Comment by yaichenbaum** [comment]
Thanks again for your feedback.

_Since we didn't hear from you on this topic for 7+ days, we'll assume everything is worked out and close this feedback item. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this._
