### ISSUE TITLE
Ongoing Task dialog progress not updating

### ISSUE THREAD

**Issue by generalguy41** [files-community/Files#2244]
**Describe the bug**
Task dialog box not updating.

**To Reproduce**
1. Copy a large number of items to Files.
2. Click on the Ongoing Tasks dialog.
3. Dialog stuck at 0%

**Expected behavior**
Dialog should show progress.

**Screenshots**
![image](https://user-images.githubusercontent.com/8879244/98319556-fa5b7380-1fae-11eb-9dc4-021a06dfefdb.png)

**Desktop**
 - OS Version: Windows 10 2004 20246.1
 - App version: v0.19.0.0

**Additional context**
- This was when copying a large amount of files from Explorer to Files.
- This was transferring between two usb thumb drives.
- Task still completed successfully:
![image](https://user-images.githubusercontent.com/8879244/98319755-75bd2500-1faf-11eb-9311-54af17a3374a.png)

**Comment by generalguy41** [comment]
Adding more details discovered in 0.21.0.0:
- If an error pops up during the transfer, the dialog will just be stuck and the progress in general will be halted with no explanation. For example:
  - Transfer a file to a USB that doesn't have enough space (or do some other operation that leads to an error)
  - In explorer, there's a message that says such, but for files, the task is stuck at 0% with no explanation of what the issue is.
- "File is in use" task item is poorly cropped. (I can move this to a separate ticket if necessary)
  ![image](https://user-images.githubusercontent.com/8879244/100411849-d97fbe80-3040-11eb-85e3-a63eb382c534.png)

**Comment by yaichenbaum** [comment]
@generalguy41 This issue should be fixed with #2708.
