### ISSUE TITLE
Library cards' corners covered on hover

### ISSUE THREAD

**Issue by AnugrahJames** [files-community/Files#2246]
**Describe the bug**
Not a bug, but a small visual issue. I noticed that the library cards on the 'Home' section which enlarges on hovering gets covered at the corners. This also holds for the 'Drives' cards. Another thing I noticed is that it happens only when 'Recent Items' are enabled, otherwise the animations are not covered.

**To Reproduce**
1. Make sure "Recent Items' is enabled.
2. Hover over any card (Library or drive)
3. See the corners covered.

**Screenshots**
![Screenshot (751)_LI](https://user-images.githubusercontent.com/70474434/98328820-a8e9cd80-201c-11eb-8067-4b00b9018c41.jpg)
![Screenshot (753)_LI](https://user-images.githubusercontent.com/70474434/98328835-b43cf900-201c-11eb-8e40-eccef597d775.jpg)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2 19042.610]
 - App version: [v0.19.0.0]

**Comment by AnugrahJames** [comment]
Additionally the cards are covered when the window size is very low (even when 'Recent Items' are not enabled).

![image](https://user-images.githubusercontent.com/70474434/98329894-46460100-201f-11eb-9d0c-81b1ee881f9a.png)

**Comment by Jaiganeshkumaran** [comment]
When the application is run on larger window size, the corners are overlapping sometimes.

**Comment by yaichenbaum** [comment]
@AnugrahJames This issue should be resolved in `main`.
