### ISSUE TITLE
Drag & Drop file from WinRar to Files (Beta)

### ISSUE THREAD

**Issue by scriptBoris** [files-community/Files#2255]
🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨

**Describe the bug**
Bad drag and drop

**To Reproduce**
1. Open Files (Beta)
2. Open Winrar archive
3. Drag and drop file from archive to Files (Beta)
4. See error :(

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Comment by gave92** [comment]
Merging with #2023
