### ISSUE TITLE
Files chashes on draging more than 8 files

### ISSUE THREAD

**Issue by bogdanbryzh-official** [files-community/Files#2256]
**Describe the bug**
Trying to drag-and-drop 8+ files to any item on the sidebar. Files crashes.

**To Reproduce**
1. Go to any folder on your PC
2. Choose 8 or more files
3. Drag them to any item on the sidebar
4. Files crashes

**Expected behavior**
Moving my files to the chosen place

**Screenshots**
![image](https://user-images.githubusercontent.com/66746788/98441545-c2b40f00-2107-11eb-85fb-45152869ec07.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 20H2 19042.572
 - App version: v0.19.0.0

**Additional context**
Restarted my PC. Nothing changed))

**Logfile**
[LocalState.zip](https://github.com/files-community/Files/files/5504744/LocalState.zip)

**Comment by yaichenbaum** [comment]
@bogdanbryzh-official Is this still an issue in v0.21.1?

**Comment by bogdanbryzh-official** [comment]
No, it's gone)) The bug is fixed I guess?)
I didn't use new Files for a while. Have to say now it's blazing fast and super comfortable)) Thanks!
