### ISSUE TITLE
Freedom for Folders (just like macos)

### ISSUE THREAD

**Issue by khrmndgn** [files-community/Files#2259]
Freedom for Folders (just like macos)

![cluttered-finder-mac-osx](https://user-images.githubusercontent.com/11201074/98445310-120a3780-2128-11eb-96c4-35fc6e3e743a.png)

**Comment by duke7553** [comment]
Thanks for your feedback. We're having trouble understanding what you're requesting and need additional information to investigate this item. Please re-open when you've filled out the issue template to the best of your ability.
