### ISSUE TITLE
Etwas ist schiefgelaufen

### ISSUE THREAD

**Issue by wumpoth** [files-community/Files#2261]
**Describe the bug**
A clear and concise description of what the bug is and why it is more urgent than other issue reports. Can't answer this? Please return to the previous page and file a regular bug/feature report.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Additional context**
Add any other context about the problem here. For instance, are you building from source or using a precompiled build/snapshot?

**Log file**
Please post the log file here so that we can understand your problem better. You can access it from Settings->About->Open log location.
Files hat ein Problem,auf das die Entwickler nicht vorbereitet sind.  
Windows version 20251.fe release 201030-1438

**Comment by gave92** [comment]
Thanks for your feedback. We need additional information to investigate this item. Please re-open when you've filled out the issue template to the best of your ability.
