### ISSUE TITLE
Command line/terminal open 

### ISSUE THREAD

**Issue by cambo2015** [files-community/Files#2262]
**Is your feature request related to a problem? Please describe.**
This is a FEATURE REQUEST and is not a bug or direct problem with the current software.

**Describe the solution you'd like**
In terminal/cmd you can open files in file explorer by running "start ." which opens the current directory in Explorer. It would be great to run "files ." in a terminal and have it open the Files App in the current working directory. IN-DETAIL: Open command prompt or a terminal app in win 10. Then cd into any directory such as user/username/downloads. Then run "files ." inside the said terminal app. Files App should open to user/username/downloads. Tada! It is the same as running "start ." except the files app opens and is more beautiful and awesome. 

**Describe alternatives you've considered**
"files filename" or "files foldername"

**Additional context**
The files app does indeed open when you run "files ." but it does not open the current cmd directory. This would be a feature in 0.20 or 0.21

**Comment by gave92** [comment]
Yup, currently Files supports a command like `files c:\users\someone\documents` (absolute paths only)

**Comment by cambo2015** [comment]
That's great! Thanks!

**Comment by cambo2015** [comment]
For what it is worth if anybody else has trouble I was able to go to Settings>Preferences>terminal Applications and edit the json file there. Here is my code: `{
  "version": 1,
  "defaultTerminalPath": "cmd.exe",
  "terminals": [
    {
      "name": "CMD",
      "path": "cmd.exe",
      "arguments": "",
      "icon": ""
    },
    {
      "name": "WT",
      "path": "wt",
      "arguments": "",
      "icon": ""
    }
  ]
}`

Hopefully, this can help others.
