### ISSUE TITLE
Left clicking then Right clicking a file opens it if I am in the "Home" tab

### ISSUE THREAD

**Issue by masrawyremix** [files-community/Files#2272]
**Describe the bug**
Left clicking then Right clicking a file opens it.

**To Reproduce**
1. Left Click on a file in the "recent" menu
2. quickly after right click the same file
3. tada, my .mp4 file just opened in VLC

**Expected behavior**
uhh, maybe I get the right click drop menu? I don't get it at all and the file just opens. I can't say the same in other folders. The issue is only reproducible in the "recent items" list.

**Screenshots**
no need for screenshots

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2]
 - App version: [v0.19.0.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
Please post the log file here so that we can understand your problem better. You can access it from Settings->About->Open log location.

**Comment by yaichenbaum** [comment]
Opening files on the home page only requires one click.
