### ISSUE TITLE
Allow Files UWP application run as administrator，允许“文件”应用以管理员身份运行

### ISSUE THREAD

**Issue by Gaoyifei1011** [files-community/Files#2280]
目前的版本中，文件应用只是一个纯UWP应用，好像不能以管理员身份运行。但是在文件操作方面，总是要涉及到权限问题。例如在C盘的根目录下存放了一些文件，文件应用不能将其删除，也不会提示有关权限的涉及，必须通过传统的资源管理器提升权限后可以删除。我希望未来的文件应用也能够像Windows Terminal一样，结合Project Union，在Win32/64应用中插入UWP的特性，允许以管理员身份运行，执行一些提权操作。

The current version, the file is just a pure UWP application, if did not run as an administrator.But in terms of file operations, always involves permission problems.For example, in C disk to store some documents, the root of the file application cannot be deleted, also won't tip involves about permissions, must through the traditional resource manager permissions can be deleted after ascension.I want the future to file applications can also like Windows Terminal, combined with the Project Union, inserted in the Win32/64 UWP features, allowed to run as an administrator, perform some power operation.
就像这样,Such as this.
![image](https://user-images.githubusercontent.com/49179966/98502252-83fb9180-228c-11eb-8852-345ee2e3a4e2.png)
目前没有这个功能，But now it does not have this feature.
![image](https://user-images.githubusercontent.com/49179966/98502273-8fe75380-228c-11eb-945a-34acab524a8a.png)

**Comment by gave92** [comment]
Thanks for the feedback, merging with #1194
