### ISSUE TITLE
Merging two windows by dragging the tabs causes a crash

### ISSUE THREAD

**Issue by LukeGotBored** [files-community/Files#2284]
**Describe the bug**
Merging two tabs from separated windows crashes the program

**To Reproduce**
1. Open two windows
2. Drag the tab from one window onto the other window
3. Wait a few seconds
4. the program crashes

**Expected behavior**
The two windows should merge in one

**Screenshots**
It's not screenshottable

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.19.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5511321/debug.txt)

**Comment by yaichenbaum** [comment]
@LukeGotBored Please try updating to v0.19 to see if this issue is fixed.

**Comment by LukeGotBored** [comment]
i am already on v0.19
![image](https://user-images.githubusercontent.com/20886839/98559608-1ad54780-22a7-11eb-9a39-b00272412c8e.png)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #2285.
