### ISSUE TITLE
Files app crashes on Windows 10 pro when opening. It tries to load and then immediately closes.Version is 0.19.0.0

### ISSUE THREAD

**Issue by michaelrizzo2** [files-community/Files#2293]
**Describe the bug**
A clear and concise description of what the bug is and why it is more urgent than other issue reports. Can't answer this? Please return to the previous page and file a regular bug/feature report.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Additional context**
Add any other context about the problem here. For instance, are you building from source or using a precompiled build/snapshot?

**Log file**
Please post the log file here so that we can understand your problem better. You can access it from Settings->About->Open log location.

**Comment by yaichenbaum** [comment]
@michaelrizzo2 Can you please fill out the issue template?

**Comment by duke7553** [comment]
@michaelrizzo2 We haven't heard anything back from you for almost two days, and we typically close issues without a filled-out template after three days of inactivity. Please fill out the issue template and include a copy of your log file. Otherwise, we'll assume you resolved this and close this feedback report.

**Comment by michaelrizzo2** [comment]
Expected behavior
The app should open and I should be able to browse the files. What happens is when the Files app tries to open , it shows everything then the something went wrong dialog box shows up in the notification.

Screenshot
![files issue ](https://user-images.githubusercontent.com/8195851/98853331-f7d1a180-2426-11eb-9a22-a25b777e07f5.png)

Desktop (please complete the following information):

OS: Windows 10 pro 20H2 build 19042.630
App version: 0.19.0.0

**Comment by duke7553** [comment]
@michaelrizzo2 Thanks. Can you also upload your log files (*.txt) from: 

C:\Users\[USERNAME]\AppData\Local\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState

**Comment by michaelrizzo2** [comment]
Hello Luke,

I just updated to app version 0.20.0.0 and the issue is gone. This issue can be closed.

Let me know if you need anything else.

Michael Rizzo
