### ISSUE TITLE
Searching Home gives no result

### ISSUE THREAD

**Issue by Cyberdroid1** [files-community/Files#2295]
**Describe the bug**
When searching Home in the navigation bar of the app, it gives No Results, but when pressed enter, it jumps to Home tab. This No Results part should be fixed.

**Screenshots**

![image](https://user-images.githubusercontent.com/51435948/98660069-e1fea680-236a-11eb-9f87-32fa182b1113.png)

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 2009 19042.610]
 - App version: [v0.20.0]

**Comment by dkgv** [comment]
See https://github.com/files-community/Files/issues/333

**Comment by d2dyno1** [comment]
@dkgv It's actually not search, it's direct pathbox navigation. It should say "Navigate to home" or something like this

**Comment by yaichenbaum** [comment]
This behavior is on the intended behavior.
