### ISSUE TITLE
Add Network Tab in sidebar

### ISSUE THREAD

**Issue by Steve01010** [files-community/Files#2296]
**Is your feature request related to a problem? Please describe.**
Can't see devices on network like in file explorer.

**Describe the solution you'd like**
Add a network tab to the sidebar just like in file explorer.
![image](https://user-images.githubusercontent.com/26387656/98695993-4278ee00-2341-11eb-8ad1-90ef7c47a6bd.png)

**Comment by yaichenbaum** [comment]
@Steve01010 Files already includes support for network drives, is there a specific use case you had in mind?

**Comment by Steve01010** [comment]
@yair100 There is no button to see the network drives in the sidebar.

**Comment by yaichenbaum** [comment]
@Steve01010 Right now network drives show up under the drives section, but we plan to split that up in the future. Merging with #692.
