### ISSUE TITLE
Unable to build from source

### ISSUE THREAD

**Issue by dkgv** [files-community/Files#2298]
**Describe the bug**
I'd like to help out with a few of the open issues but I'm having trouble building/launching the solution after following the instructions from README.md:

```
3>  ..\Files.Package\Package.appxmanifest(64,10): warning APPX0006: This project uses the 'runFullTrust' capability. You should use the Windows Application Packaging Project to produce the store and sideload packages. See https://go.microsoft.com/fwlink/?linkid=871803 for more information.
3>  C:\Users\admin\Desktop\Files\Files\bin\x86\Debug\AppxManifest.xml : error APPX0501: Validation error. Exception from HRESULT: 0x8051100F
3>  Done building target "_ValidateAppxManifest" in project "Files.csproj" -- FAILED.
3>
3>  Done building project "Files.csproj" -- FAILED.
3>
3>  Build FAILED.
```

I'm on Windows 10 Pro, x64. Any suggestions?

Edit: Just for reference, I've tried the `master`, `0.19.7`, `0.19.8` branches. Additionally, I've also tried excluding the `Assets` folder from the Files.Package project (as in https://github.com/files-community/Files/issues/354) without luck.

**Comment by duke7553** [comment]
@dkgv Thanks for letting us know. Have you tried selecting the Files.Package project in the Visual Studio dropdown near the run button?

**Comment by dkgv** [comment]
@duke7553 Yes, that is the one that results in the output I included above.

**Comment by duke7553** [comment]
@dkgv Sorry that you're experiencing this difficulty while trying to contribute.

Have you tried deleting from disk and re-cloning the solution?

**Comment by dkgv** [comment]
@duke7553 Yes, I've tried all the usual suspects multiple times (re-cloning, restarting, clearing various caches, reinstalling).

**Comment by dkgv** [comment]
Reopening this.

It's turned out to be a bit of a hit and miss for me; it seems like 9/10 times when I try to build it fails with the following error:
`3>C:\Users\admin\.nuget\packages\microsoft.net.uwpcoreruntimesdk\2.2.10\tools\CoreRuntime\Microsoft.Net.CoreRuntime.targets(238,5): error : CopyWin32Resources failed with exit code 701`

**Comment by d2dyno1** [comment]
Did you try commenting out TerminalController.Init?
![image](https://user-images.githubusercontent.com/53011783/99405220-d07a4900-28ec-11eb-99f3-da2dcdd96772.png)

**Comment by yaichenbaum** [comment]
Thanks again for your feedback.

_Since we didn't hear from you on this topic for 7+ days, we'll assume everything is worked out and close this feedback item. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this._
