### ISSUE TITLE
Acrylic Opacity Settings

### ISSUE THREAD

**Issue by jrkmtf** [files-community/Files#2301]
**Is your feature request related to a problem? Please describe.**
No, this feature request is simply aesthetic.

**Describe the solution you'd like**
I would like to be able to adjust the acrylic opacity, similar to opacity options provided by Windows Terminal or TaskbarX. 

**Describe alternatives you've considered**
I tried searching for a settings.json file to edit, similar to the current Windows Terminal settings (Windows Terminal does not have a settings UI yet) but access is blocked by my organization.

**Additional context**
None.

**Comment by yaichenbaum** [comment]
@jrkmtf We don't have any plans to give this leval of customization for the sidebar.
