### ISSUE TITLE
Improve support for hidden items

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#2303]
- [x] Navigating to a hidden directory from the path bar throws an unauthorized error.
- [ ] #8269
- [x] The possibility to mark a file as hidden or not from properties page
- [x] Hidden items should be distinguishable in the UI
- [x] Hidden items have no thumbnail
- [x] Cannot move or permanently delete a hidden folder (moving will result in the folder being copied and the new folder loses the hidden attribute)
- [x] Opening a hidden folder in a new tab will crash the app (ItemViewModel->CurrentFolder is null)
- [x] Properties opened by clicking a hidden folder empty space will show properties of the parent folder (ItemViewModel->CurrentFolder is not updated)

**Comment by gave92** [comment]
Also it's missing the possibility to mark a file as hidden or not from properties page.
This can be done using SetFileAttributes (available in uwp)
Plus hidden items should be distinguishable in the ui
