### ISSUE TITLE
The last chevron in the breadcrumb bar should be hidden when there are no sub folders in the current directory

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#2304]
![ஸ்கிரீன் கிளிப்பிங் 2020-11-11 101846](https://user-images.githubusercontent.com/45227503/98770078-69015c80-2407-11eb-945f-d491da761e20.png)

**Comment by yarikv8601** [comment]
Why? In Windows Explorer the > symbol indicates that there's further path (another folder(s) in current folder) and it's hidden only when there's no any folders in current folder.

**Comment by Jaiganeshkumaran** [comment]
@yarikv8601 Ok but it doesn't work in Files and clicking on it doesn't show folders in the current folder.

**Comment by yaichenbaum** [comment]
We don't have plans to make this change
