### ISSUE TITLE
The phantom file of folder from year 1601

### ISSUE THREAD

**Issue by Tester09** [files-community/Files#2305]
**Describe the bug**
Sometimes I see in the opened tab a file or folder without a name which was created 1 January 1601
![image](https://user-images.githubusercontent.com/18252816/98796104-b1267c00-2413-11eb-80b5-82e3558d8e3c.png)

**Comment by lukeblevins** [comment]
@yair100 This may be related to what I assumed wasn't a bug for anyone else
#2300

**Comment by lwndwsk1** [comment]
Hi, i´ve found exactly the bevahior. Tested on Windows 10 Home (20H2, 19042.685). The Software crashes without any error Messages. After opening up again, the phantom File ist gone. 

<img width="767" alt="screenshot" src="https://user-images.githubusercontent.com/13572147/103037878-33ef3a80-456d-11eb-95bc-8f95d0d1f719.png">

**Comment by yaichenbaum** [comment]
@gave92 Do you know if this is still an issue?

**Comment by yaichenbaum** [comment]
This issue appears to be resolved in `main`.
