### ISSUE TITLE
Deleting protected files does not delete them yet the icon vanishes

### ISSUE THREAD

**Issue by AnugrahJames** [files-community/Files#2307]
**Describe the bug**
Whenever I try to delete a protected file, the file just disappears without showing a 'Folder Access Denied' dialog box. But can be found after a refresh.

**Expected behavior**
Files might still not support deleting protected files, but it would  be better to let the user know that the task failed and the icon should not disappear if the file has not been deleted. 

PS: A 'Task Failed' dialog box would be a great addition. 

**Screenshots**
![image](https://user-images.githubusercontent.com/70474434/98801741-420f4e80-2438-11eb-95de-f807bb664355.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.630
 - App version: v0.20.0.0

**Comment by erayrafet** [comment]
That's a problem I have as well with deleting folders from the C: directory. Although they appear as deleted, upon a refresh, they just come back.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #2638.
