### ISSUE TITLE
Select Items using Space key

### ISSUE THREAD

**Issue by antnauman** [files-community/Files#2310]
The keyboard shortcut of selecting an item using space key is not there yet. Kindly implement this functionality.
Thank you.

**Comment by yaichenbaum** [comment]
@antnauman how is this shortcut supposed to work?

**Comment by antnauman** [comment]
In File Explorer, hold Ctrl key and move around the items using arrow keys, then press space key and you will notice the highlighted item gets selected/unselected.

This behavior is not available in Files.

Ahmed Nauman Tariq

**Comment by yaichenbaum** [comment]
@antnauman we're planning to use the space key to toggle the preview pane, is there a reason that you would want to unselect an item?

**Comment by yaichenbaum** [comment]
@antnauman what's the use case where you would want to deselect an item?

**Comment by antnauman** [comment]
When Ctrl key is pressed and we are using mouse, we can select/unselect an item using Left Mouse Click. Similarly if we are using just keyboard, we can do the same selecting/unselecting an item using space key.

**Comment by antnauman** [comment]
It's ok.
