### ISSUE TITLE
Files UWP failing to open

### ISSUE THREAD

**Issue by DogeLord081** [files-community/Files#2314]
**Describe the bug**
When I open Files UWP it just shows the logo and then is stuck on the loading screen where it just shows the logo forever.

**To Reproduce**
1. Open Files UWP
2. The screen will just show the logo forever and no buttons appear or anything

**Expected behavior**
For it to open and let me do stuff

**Screenshots**
![2020-11-11](https://user-images.githubusercontent.com/71139863/98879953-a9d39280-2454-11eb-94e0-b07a7b046f5e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1909 18363.1139
 - App version: v0.20

**Additional context**
Add any other context about the problem here. For instance, are you building from source or using a precompiled build/snapshot?

**Log file**
Please post the log file here so that we can understand your problem better. You can access it from Settings->About->Open log location.

**Comment by yaichenbaum** [comment]
@DogeLord081 Can you please upload the log file?

**Comment by DogeLord081** [comment]
It wont work when i go into settings about i dont see a log thing

**Comment by yaichenbaum** [comment]
@DogeLord081 https://github.com/files-community/Files/wiki/Opening-the-log-file

**Comment by DogeLord081** [comment]
K ill try this tomorrow

**Comment by danukim** [comment]
@yair100 I didn't find a debug.txt i think its because it didn't crash or anything, it just didn't open

**Comment by yaichenbaum** [comment]
@DogeLord081 Can you check if resetting the app fixes the issue?

**Comment by yaichenbaum** [comment]
Thanks again for your feedback.

_Since we didn't hear from you on this topic for 7+ days, we'll assume everything is worked out and close this feedback item. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this._

**Comment by danukim** [comment]
@yair100 how do I reopen it? also I already tried resetting it. It didn't work

**Comment by DogeLord081** [comment]
can someone put this in the to do list? its in the closed right now because it got reopened

**Comment by yaichenbaum** [comment]
@DogeLord081 Can you try resetting the app again?

**Comment by danukim** [comment]
@yair100 ok i just tried. It didnt work

**Comment by danukim** [comment]
Well, isnt anyone going to work on this? Also, @yair100 can u put the triage approved label on it again?

**Comment by yair100** [comment]
> Well, isnt anyone going to work on this? Also, @yair100 can u put the triage approved label on it again?

We need to investigate this, being that we can't reproduce this on our end, we can't start working on a fix yet. Can you try updating to v0.21 to see if the issue is fixed?

**Comment by danukim** [comment]
> > Well, isnt anyone going to work on this? Also, @yair100 can u put the triage approved label on it again?
> 
> 
> 
> We need to investigate this, being that we can't reproduce this on our end, we can't start working on a fix yet. Can you try updating to v0.21 to see if the issue is fixed?

I tried to install the new version but it keeps getting stuck at 16%

**Comment by yaichenbaum** [comment]
Thanks again for your feedback.

_Since we didn't hear from you on this topic for 7+ days, we'll assume everything is worked out and close this feedback item. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this._

**Comment by DogeLord081** [comment]
Woah woah woah why does it keep getting closed

**Comment by yaichenbaum** [comment]
@DogeLord081 We cannot reproduce this issue on our end, can you check if this is still an issue with v0.21.1?

**Comment by danukim** [comment]
@yair100 sure ill try
