### ISSUE TITLE
The right-click menu does not pop up

### ISSUE THREAD

**Issue by wlj1243** [files-community/Files#2318]
This app is very useful, like.

Right-clicking on a file can cause the program to get stuck.
There is no problem right-clicking the folder, and there is no problem right-clicking in the folder space.

**Comment by yaichenbaum** [comment]
@wlj1243 Can you try restarting Windows to see if that solves the issue?

**Comment by Jaiganeshkumaran** [comment]
@wlj1243 Can you provide more info like app version and Windows version?

**Comment by wlj1243** [comment]
> @wlj1243 Can you try restarting Windows to see if that solves the issue?

restarting windows can not resolve the problem

**Comment by wlj1243** [comment]
> @wlj1243 Can you provide more info like app version and Windows version?

the app version is 0.20.0.0
the windows version is win10 ltsc  1809  17763.1577

**Comment by Sanlorng** [comment]
I also encountered the same problem, and after the problem occurred, the content of the context menu in the folder and the blank space of the folder changed
![Uploading Snipaste_2020-11-13_16-43-45.png…](before)
![Uploading Snipaste_2020-11-13_16-44-07.png…](after)

**Comment by yeduzhouzi** [comment]
> 
> 
> I also encountered the same problem, and after the problem occurred, the content of the context menu in the folder and the blank space of the folder changed
> ![Before](https://user-images.githubusercontent.com/26089739/99047839-c0eabf80-25cf-11eb-9395-e27fcb7031f4.png)
> ![After](https://user-images.githubusercontent.com/26089739/99047868-ccd68180-25cf-11eb-86e4-09ff435f1dad.png)

Did you find a way to solve it? I got the same problem here. The app could not retrieve the system context menu at all.

**Comment by yaichenbaum** [comment]
@Sanlorng @yeduzhouzi This happens with the full trust process crashes but stays open in the background. You can force close the full trust process by running this command `taskkill -f -im filesfulltrust.exe`. You should see the regular context menu again the next time you open Files.

**Comment by yeduzhouzi** [comment]
> 
> 
> @Sanlorng @yeduzhouzi This happens with the full trust process crashes but stays open in the background. You can force close the full trust process by running this command `taskkill -f -im filesfulltrust.exe`. You should see the regular context menu again the next time you open Files.

Thanks. But for me every time I click on a file, the problem will be back again. That said, the full context menu only works for folders or blank spaces, but not for a single file.
