### ISSUE TITLE
Replace build-in file explorer

### ISSUE THREAD

**Issue by Lukasz-egg** [files-community/Files#2319]
Is it possible to replace build-in file explorer with this? I mean opening shortcuts from desktop with this app/when saving file from browser to appear this explorer instead of build-in. This will be so good feature, but I dont know is it possible. Have a nice day :)

**Comment by gave92** [comment]
There is a tutorial here: https://github.com/files-community/Files/wiki/Replacing-File-Explorer-with-Files-(Unsupported)
But note that it's unsupported and has side-effects like loosing the ability to access the control panel
