### ISSUE TITLE
Drives on homepage not clickable until app restart

### ISSUE THREAD

**Issue by Dem1se** [files-community/Files#2320]
**Describe the bug**
When you turn on the show drives option in home page, the drives get added, but clicking on them don't do anything (they don't take you to the drive). Exiting the app after altering the setting and re-opening the app fixes the the problem and makes the drive tiles in homepage navigate to the drive on click. Settings > Widgets > Show drives in homepage 

**To Reproduce**
1. Go to "Settings > Widgets"
2. Click on 'Show drives in homepage '
3. Go back to the home page, and notice that the drives are shown now.
4. Click on one of the shown drives, and notice that it doesn't navigate anywhere.

**Expected behavior**
The app should navigate to the drive's path (C:\) for example.

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version:
![image](https://user-images.githubusercontent.com/22272753/98914051-367e5f00-24ee-11eb-902f-90988b01abbd.png)

 - App version: [v0.20.0.0]

**Additional context**
The problem gets fixed after restarting the app, and behaves as expected.

**Log file**
Couldn't find any text files that were actual logs here:
![image](https://user-images.githubusercontent.com/22272753/98914545-d20fcf80-24ee-11eb-95f2-2118bbc858cb.png)

**Comment by gave92** [comment]
Thanks for the feedback
Navigating away from the homepage and navigating back to it also solves the issue.
Still something we need to fix.

**Comment by yaichenbaum** [comment]
@Dem1se Is this still an issue in v0.23.1?

**Comment by gave92** [comment]
Yeah it is, toggling the show drives option makes the drives unclickable

**Comment by gave92** [comment]
Changes in #2727 seems to have magically solved this issue
