### ISSUE TITLE
Back(Mouse4) and Forward(Mouse5) buttons don't navigate backdwards/forwards

### ISSUE THREAD

**Issue by Dem1se** [files-community/Files#2321]
**Is your feature request related to a problem? Please describe.**
The windows default file explorer supports the forward and backward binding that gaming mice have by default. Chrome and Firefox and most applications that have navigation supports the Forward and Backwards keys. It's a very quick and convenient way to move back and forth without moving the mouse away from the main panel. I must say this is the first time I've clicked that button due to muscle memory (it's everywhere) and not seen its work :D 

**Describe the solution you'd like**
The file explorer to take the same action as the forward and backward button in the 
![image](https://user-images.githubusercontent.com/22272753/98915099-772aa800-24ef-11eb-9127-564b509ba2bd.png)
like most other application.

**Describe alternatives you've considered**
Using `alt+arrow keys` or using `backspace` for going back. Anything as long as I don't have to move the mouse too much.

**Additional context**
App version: 0.20.0.0 (Microsoft store)
Winver: ![image](https://user-images.githubusercontent.com/22272753/98915614-249dbb80-24f0-11eb-8349-216fb0d5397a.png)

I'm certain this is just a dedicated key that windows provides for the forward and backward navigation. It's not a proprietary thing that a lot of people have chosen to support.  It's like the media keys in the Fn row.
![image](https://user-images.githubusercontent.com/22272753/98916493-3df33780-24f1-11eb-9a84-4bb492ce208d.png)

**Comment by gave92** [comment]
Hi @Dem1se thanks for this feedback.
Alt+arrow keys should be working, but is something we'll want to add as well

**Comment by yaichenbaum** [comment]
@gave92 We implemented support for the side mouse buttons a couple of months ago, perhaps it's not working because of the refactors that were recently done. https://github.com/files-community/Files/blob/7d1be782971dd57637fc46338e0a716f2b9679e4/Files/Views/ModernShellPage.xaml.cs#L264

**Comment by generalguy41** [comment]
Back/Forward mouse buttons are working for me on 0.20.0.0 with two separate mice (Razer Basilisk Ultimate and Logitech MX Master).

**Comment by Dem1se** [comment]
> Back/Forward mouse buttons are working for me on 0.20.0.0 with two separate mice (Razer Basilisk Ultimate and Logitech MX Master).

This is bizarre, it's working now for me too... 😅. I'll report back if this is inconsistent or what's the deal, because it sure wasn't working earlier.
