### ISSUE TITLE
Smart Quick Access for Recent Folders in Sidebar

### ISSUE THREAD

**Issue by jordanisaacs** [files-community/Files#2322]
In the traditional windows 10 file explorer there are constantly updating quick access folders in the sidebar. This allows for quick navigation to folders that I have been using recently. It would be extremely useful to have a feature like that in files. It is the feature that I use a lot in the normal file explorer that is missing from files.

**Comment by gave92** [comment]
This is the same as #1805 right?

**Comment by jordanisaacs** [comment]
@gave92 pretty much, but I would think pinning folders and smart quick access would be separate features.

**Comment by yaichenbaum** [comment]
> @gave92 pretty much, but I would think pinning folders and smart quick access would be separate features.

I think that merging the two features would make sense, quick access would show some recent directories, but it would also let you pin them to the quick access section.

**Comment by yaichenbaum** [comment]
Merging with #692.
