### ISSUE TITLE
OneDrive that appears in app is the one associated with my organization

### ISSUE THREAD

**Issue by iseeghosts** [files-community/Files#2330]
**OneDrive shown in app isn't the personal account**
I'm genuinely enjoying this app, but I would highly appreciate it if the publisher would either choose OneDrive personal account for OneDrive integration or display both along with SharePoint folders in the navigation pane. Right now, it says OneDrive which one can confuse with personal account but it's the Organization account.
To avoid such confusion, Windows Explorer shows the Organization OneDrive as "OneDrive - _Name of Org_ ", but this isn't the case with 'Files - Preview' app.

**To Reproduce**
1. Have both personal and organizational OneDrive signed in.
2. Click on 'OneDrive' in the navigation-pane of Files - Preview app downloaded from Microsoft Store.
3. Check the Path - it's your organizational account.

**Expected behavior**
1. If it's org account, the navigation pane should show OneDrive as "OneDrive - _Name of org_ ", if it's just "OneDrive", this should be the location of Personal account, or, 
2. There can be both, OneDrive & OneDrive for business link along with SharePoint Folders, or, 
3. One should be able to choose which OneDrive account they want to use

**Screenshots**
![image](https://user-images.githubusercontent.com/34771316/99138388-41540380-2656-11eb-8211-f89d9f19c880.png)
![image](https://user-images.githubusercontent.com/34771316/99138393-44e78a80-2656-11eb-8e38-9a7a3382e161.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 build 19042.610
 - App version: [v0.19.0.0]

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5540118/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5540119/debug_fulltrust.txt)

**Comment by gave92** [comment]
@iseeghosts thanks for this feedback. Issue should be solved in version 0.20.0.0 (both accounts will be pinned to the sidebar)
Feel free to reopen if updating does not solve the issue
