### ISSUE TITLE
Files not opening in the latest version

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#2333]
https://app.box.com/s/oubgw7qg8ggfcyrzjbx6gx9oe1vjxal9
App version: 0.20

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran Can you share the log file?

**Comment by Rasmagoric** [comment]
Same issue here with v0.20

**Comment by alunosnet** [comment]
Same problem, files only open if selected open with and then ok.

**Comment by yaichenbaum** [comment]
@alunosnet Does resetting the app fix the issue?

**Comment by alunosnet** [comment]
> @alunosnet Does resetting the app fix the issue?

Yes, thanks.

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran @Rasmagoric Can you check if resetting the app fixes the issue?

**Comment by Rasmagoric** [comment]
@yair100 yeah. I reinstalled the app and it works fine now. thanks
