### ISSUE TITLE
Implement Optional White Icon

### ISSUE THREAD

**Issue by aaronth07** [files-community/Files#2339]
I have every pinned app using a white icon for aesthetic purposes. I do this by setting a custom icon for the shortcut. But since Files is a UWP app, this is not possible. Even creating a separate shortcut does save the icon when pinning.

[Example](https://imgur.com/a/XOMu4ex)

Not asking for that icon specifically of course, i'm just posting that icon as an example, along with a comparison of the current icon.

**Comment by yaichenbaum** [comment]
![image](https://user-images.githubusercontent.com/39923744/99159405-0380ca80-26aa-11eb-8389-60266bf9b67b.png)
@aaronth07 Is this what you were looking for?

**Comment by aaronth07** [comment]
Yep, or something like that.

**Comment by yaichenbaum** [comment]
@aaronth07 While we won't add the option to change the icon for Files, we will make sure to add icons for high contrast themes. To create a shortcut with a custom icon, create a new shortcut and set the target path to `Files.exe`.

**Comment by aaronth07** [comment]
Unfortunately, that doesn't work for me. It was the first thing I have
tried. I think it has something to do with the UWP format.
