### ISSUE TITLE
MVVM

### ISSUE THREAD

**Issue by d2dyno1** [files-community/Files#2341]
**Is your feature request related to a problem? Please describe.**
WPF and UWP technologies were intentionally designed to work with MVVM pattern. Files follows it very poorly as majority of the code is hidden in the code-behind files (MainPage.xaml.cs)

**Describe the solution you'd like**
A loosely coupled code achieved with MVVM would be more maintainable and would make the entire codebase more professional. The code would also be more efficient and more flexible. Less boilerplate, copied-over code. Not only that, project with implemented MVVM, if designed well, could work on multiple platforms.
Implementing MVVM would mean a huge rewrite of Core Files functionalities and would take a huge amount of time, but in the end I believe the change would be worth it. 

(This would mean we'd had to delete the code-behind (e.g. MainPage.xaml.cs) and move it over to ViewModel class (e.g. MainPageViewModel.cs))

**Additional context**
I always code my applications following MVVM pattern and I don't regret doing so.

**Comment by yaichenbaum** [comment]
@d2dyno1 Moving towards MVVM is a long-term goal and we have made several steps in this direction with some of the recent refactoring we have done. Is this something you are interested in helping with?

**Comment by d2dyno1** [comment]
I'll make sure my next PRs follow the MVVM pattern

**Comment by yaichenbaum** [comment]
@d2dyno1 That sounds great, one of the things we can already start doing is moving some of the core functions out of the code-behind into a separate "commands" folder for features such as copying, pasting etc.

**Comment by d2dyno1** [comment]
@yair100  Are you referring to new changes in #2358? In the means of copying, moving, deleting items, the (new, reworked) `IFilesystemOperations` needed its own special place. I intentionally didn't keep it in the Commands directory because `Commands` are specifically reserved for UI elements functionality implementation (`ICommand`). The new `IFilesystemOperations` is a part of Files' underlying FS.

**Comment by yaichenbaum** [comment]
@d2dyno1 No, I was just saying in general.

**Comment by duke7553** [comment]
@d2dyno1 We do need to rename the "Commands" folder to something less confusing.

**Comment by d2dyno1** [comment]
I'd create a ViewModel folder for all View Models. I'll open a PR regarding this - How I'd do it, how I see it done - as soon as #2358 is merged, and #1763, #2117 is completed

**Comment by yaichenbaum** [comment]
@d2dyno1 We already have a ViewModel folder.

**Comment by d2dyno1** [comment]
👀

**Comment by yaichenbaum** [comment]
> @d2dyno1 We do need to rename the "Commands" folder to something less confusing.

It depends, at the time we were going to put the command in their own files but now it looks like we will be putting them in the View Models.

**Comment by d2dyno1** [comment]
We're still working on the infrastructure redesign. You can help by ornganizing the namespaces. Since we've moved the code to separate projects, some namespaces need updating too. We're looking for updating the namespace `Files.*` for Files.Uwp project to `Files.Uwp.*` 🙂

**Comment by devovercome** [comment]
I want to upwote and encourage this topic.
I just realized that most work is going under the Files.Uwp solution, which contains a tons of xaml.
Any tiny change in code forces to wait for 2 minutes for rebuild entire xaml for no reason.

It would be great, if the code gonna be as loosly coupled from xaml as possible. 
Meaning, even the UI logic could be placed in separate project, which leads to significant development efficiency increase.

@d2dyno1 I think, there should be some roadmap, some guideline for this. Random devs has no idea which places are legal to touch. And how to sync the changes with current Files codebase - thats the question as well. 

I want to join to this refactoring, since I strongly encourage code debts decrease.

Best regards,
Alex

**Comment by d2dyno1** [comment]
Looks like I haven't got any response from @MarkIvanDev. Could you implement [this](https://github.com/files-community/Files/issues/2341#issuecomment-1086183793) one as a starting ground? @devovercome

**Comment by devovercome** [comment]
@d2dyno1, Need to rename namespace `Files.*` -> `Files.Uwp.*`? Sure, will do!

**Comment by cinqmilleans** [comment]
Dividing the front into several projects allows
- improve compilation time
- better manage external and internal dependencies
- to better structure the tree structure of each project
- to have one file per class for more readability
- It gives an interest to the internal elements

Here are some suggestions
- Files.Backend.Storage: Contains StorageFile, StorageFolder, ... which have many classes and external dependencies. I am already working on this.
- Files.Backend.Item: Uses Files.Backend.Storage to provide common ListedItem interfaces, associated viewmodels
- Files.Front.Setting: Contains settings classes, backup/restore tools, config window, ...
- Files.Application: Contains the main application, which only assembles controls and services from other projects and configures everything with the settings.
- Files.Front.Preview: A PreviewPane control that receives a file and displays its preview.
- Files.Front.Navigation: Contains navigation controls
We can make an exhaustive list.

**Comment by yaichenbaum** [comment]
Bugs don't get fixed on their own (well, they occasionally do), even if you can't contribute to the codebase directly, issue reports go a long way towards helping us improve the app and we encourage you to continue opening them.
