### ISSUE TITLE
Switch the right click context menu to CommandBarFlyout

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#2342]
Here is a concept from https://twitter.com/zeealeid/status/1327710601691455488?s=20

![image](https://user-images.githubusercontent.com/39923744/99173711-596c6700-26d8-11eb-991e-16af32ebb164.png)

**Comment by d2dyno1** [comment]
> Here is a concept from https://twitter.com/zeealeid/status/1327710601691455488?s=20
Does the author of this tweet know about Files? Maybe if we dm them, he could bring some creative ideas to Files... 🤔
