### ISSUE TITLE
OneDrive tab under drives is missing

### ISSUE THREAD

**Issue by Final-Hawk** [files-community/Files#2344]
**Describe the bug**
OneDrive tab under drives is missing. On the sidebar of the app the OneDrive option under drives is missing. In settings the pin OneDrive is greyed out. (see image)

**To Reproduce**
1. Open files app
2. Look at sidebar or drives widget
3. See error (OneDrive Not showing)

**Expected behavior**
A OneDrive tab is supposed to be on the side and in drives widget.

**Screenshots**
![image](https://user-images.githubusercontent.com/63589370/99180040-879c8600-276e-11eb-8feb-5ba53a691884.png)
![image](https://user-images.githubusercontent.com/63589370/99180042-98e59280-276e-11eb-95ec-acb3e5804bef.png)

**Desktop (please complete the following information):**
 - OS Version: 19042.630 20H2
 - App version: [v0.20.0]

**Additional context**
Does not come back after restart or reinstall

**Log file**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5541996/debug_fulltrust.txt)

**Comment by yaichenbaum** [comment]
@Final-Hawk This issue should be fixed when we roll out the next update.
