### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by MaxYaffe** [files-community/Files#2348]
Is there a Roadmap for Files?  I'd hate to submit requests only to get back -- it's already on the roadmap but hasn't been implemented yet.  Or worse, it's there but I haven't discovered it.

For what its worth I really miss the Quick access list from Windows 7 File Manager.  I really like the clarity of relying on Drives and Folders as the chief organizing metaphor. MS has managed to mangle that completely in the evolution of File Manager.

Thanks for this effort,
Max

**Comment by gave92** [comment]
Hi @MaxYaffe you can refer to Github issues or the [project board](https://github.com/files-community/Files/projects/1) to know what it's currently planned or being worked on.
For example a search for "quick access" leads to issue #2322 which sounds like what you are requesting here.
The "triage approved" label means that a feature request is on the roadmap but hasn't been implemented yet.

**Comment by yaichenbaum** [comment]
@MaxYaffe As @gave92 said, you can check the project board to see what's already been approved. If you don't see an issue for a feature you would like added, make sure to open a proposal so that we can review/add it to the plans 😃.
