### ISSUE TITLE
"OneDrive commercial" label in the sidebar is misleading

### ISSUE THREAD

**Issue by MarcAnt01** [files-community/Files#2350]
I use it for the account managed by my university, so commercial is definitely out of context. I think it could ba a better idea to show the full name like it's done by the official file explorer and it's already shown by Files in the path
![image](https://user-images.githubusercontent.com/43090263/99198708-a9136700-279a-11eb-94da-1f8cbdb13974.png)

**Comment by yaichenbaum** [comment]
@MarcAnt01 Do you think it's best to add a string for it in the resource files?

**Comment by tsvietOK** [comment]
@yair100 I think what he means is to change the name from "OneDrive" or "OneDrive Commercial" in SideBar to the real name of the folder.

**Comment by Jaiganeshkumaran** [comment]
Instead of OneDrive commercial, it could be OneDrive for Work or School.

**Comment by MarcAnt01** [comment]
@yair100 sorry I don't understand what you mean,

@Jaiganeshkumaran  I don't think it's a good idea, how are you going to get that info?

@tsvietOK I think OneDrive personal could be kept, since it's the main account, but change as you've proposed the one of the school/work account

![image](https://user-images.githubusercontent.com/43090263/99232320-13a3c180-27f2-11eb-8847-2ac3ad7642bc.png)

**Comment by yair100** [comment]
> @yair100 I think what he means is to change the name from "OneDrive" or "OneDrive Commercial" in SideBar to the real name of the folder.

That's probably the best way to do it.

**Comment by AndyMDoyle** [comment]
@MarcAnt01, issue #3095 and the resulting PR #3177 will address this issue for you. With this change Files will correctly list every OneDrive business accounts you use with the relevant company name instead of "OneDrive - Commercial".

I hope this helps.

**Comment by sos34211** [comment]
Fr
