### ISSUE TITLE
Can not show hidden files. and another maybe a translate issue

### ISSUE THREAD

**Issue by mokeyjay** [files-community/Files#2351]
**Describe the bug**
- the `Show hidden files, folders, and drives` switch is disable  
[![Snipaste-2020-11-16-11-02-38.jpg](https://i.postimg.cc/rptQfHDk/Snipaste-2020-11-16-11-02-38.jpg)](https://postimg.cc/yJsmdvhQ)
- [this guy](https://github.com/files-community/Files/commit/b39e744ea5a6fd2f2f6d094b4d7894dbc7ff0b57#diff-0e44270c7e1774ce04ab6c347f6cfb64d756ebc98e3cf6f9e614f1a377754066) change all `Show hidden files, folders, and drives` to `Show hidden files and folders`, but in my case it always show the first one
- Chinese display is incomplete. i was checked the `Files.zh-Hans.xlf`, it's complete. but some sentence always show English, as show in the picture above

**To Reproduce**
1. Go to **Microsoft Store**
2. Download the **File - Preview** (v0.20)
3. Run it, and then they appeared.

**Expected behavior**
- can switch the  `Show hidden files, folders, and drives`
- chinese translation full display

**Screenshots**
[![Snipaste-2020-11-16-11-02-49.jpg](https://i.postimg.cc/tgZp29d4/Snipaste-2020-11-16-11-02-49.jpg)](https://postimg.cc/Ty6zPMHz)

**Desktop (please complete the following information):**
- OS Version: Win10 1903 18362.1139
- Another OS Version: Win10 2004
- App version: [v0.20.0.0]

**Additional context**
i also try to download this app from [Github Release](https://github.com/files-community/Files/releases/tag/v0.20), but the bug still here. By the way, this package's version maybe wrong
[![Snipaste-2020-11-16-12-39-24.jpg](https://i.postimg.cc/y8W2mvBm/Snipaste-2020-11-16-12-39-24.jpg)](https://postimg.cc/RW5P91Wh)

**Log file**
[LocalState.zip](https://github.com/files-community/Files/files/5544152/LocalState.zip)

**Comment by yaichenbaum** [comment]
@mokeyjay This feature is included in the `master` branch but has not been shipped to users yet.
