### ISSUE TITLE
Drag and Dropping

### ISSUE THREAD

**Issue by DashCruft** [files-community/Files#2352]
Hey there!
It would be awesome if you guys add the feature where you can drag and drop the files/items into like discord or somewhere!

**Comment by AnugrahJames** [comment]
@DashCruft The feature is already present in Files. It's just that dragging isn't very fast currently. You need to drag a bit slower to see it work.

**Comment by DashCruft** [comment]
and can you guys solve that in future updates?

**Comment by yaichenbaum** [comment]
@DashCruft Drag and drop should be available with v0.23.1.
