### ISSUE TITLE
Add a double click gesture and setting to let the user customize the action

### ISSUE THREAD

**Issue by mokeyjay** [files-community/Files#2355]
**Is your feature request related to a problem? Please describe.**
No, just a feature

**Describe the solution you'd like**
double click in red box area back to upper folder
![Snipaste_2020-11-16_15-46-33](https://user-images.githubusercontent.com/6757507/99225416-ff2bed00-2822-11eb-8b6c-f7119d29477c.jpg)

the [QTTabbar](http://qttabbar.wikidot.com/)、[Clover](http://cn.ejie.me/) all support this feature, It's very useful

**Comment by d2dyno1** [comment]
There's more popular approach to this problem:
![image](https://user-images.githubusercontent.com/53011783/99257418-4ad89980-2817-11eb-9ed2-a22d631171d9.png)
Adding a special item that navigates up a directory.

> double click in red box area back to upper folder
That would create a problem of accidental clicks.

**Comment by yaichenbaum** [comment]
@mokeyjay I am not against this idea but what value would this have over clicking to the button that is already there for this?

**Comment by mokeyjay** [comment]
@yair100 Because of its high frequency of use, it does not require precise positioning as opposed to the click of a button, making it quick and easy to use.
It's a feature that's hard to get rid of once you get used to it. Maybe you should try [QTTabbar](http://qttabbar.wikidot.com/) .

**Comment by clutz2000** [comment]
This is a very handy feature once you get used to it. It is in another browser that many use in which my firm is trying to get rid of.  I would recommend adding it as an option so it can be turned on / off. That way for those that do not like it, they do not have to use it.

**Comment by gforien** [comment]
Agree, this is a very useful feature, already implemented in Clover or QTTabBar.
It allows to navigate much faster in and out of folders.

**Comment by gforien** [comment]
For anyone using [AHK](https://www.autohotkey.com/), here is a simple script that works for me

```ahk
; Double-click in Files = go back to parent directory
#IfWinActive, ahk_exe ApplicationFrameHost.exe
    ~LButton::
    if (A_PriorHotkey != "~LButton" or A_TimeSincePriorHotkey > 200) {
        KeyWait, LButton
    } else {
        MouseGetPos, MouseX, MouseY
        PixelGetColor, color, %MouseX%, %MouseY%
        background = 0x202020
        ; (change variable 'background' depending on your Files theme)
        ; dark theme = 0x202020      //        light theme = 0xF3F3F3
        if (color == background ) {
            Send {Backspace}
        }
    }
    return
#IfWinActive
```

**Comment by clutz2000** [comment]
This feature would make Files the top File Explorer for me. I miss this feature greatly (previously used Clover).

This could be a setting so people that do not want it, can leave it unset. But those of us that do want it, can set it to go back a folder. Could have many other options also.

Any chance this can be added anytime soon?

**Comment by 1300371** [comment]
Just discover _Files_. Seems great!
And like others, i'm a current user of Clover and I really enjoy this feature.

So I add my humble comment hoping it can be added. 🤞

**Comment by Allen1351** [comment]
I will second this!!! I was using an old version of Clover and I lost it, now the new ones are I think full of malware. So I discovered this and this is the only thing I am missing. Oh and Bookmarks on top like a Browser, but that can be replaced my quick access.

**Comment by zicai1026** [comment]
Please, make this happen!!!
This feature is very importent for us!!!

**Comment by Cris--** [comment]
I'm a QTTabBar user and after uninstalling QTTabBar i still double-click in Explorer or Files empty space to go up in the folder hierarchy..but it didn't work!  😢 

Hope Files will have this also near future .. next week?

**Comment by Josh-65** [comment]
Double click to go up is already a thing in 2.3.12 and above.

**Comment by Cris--** [comment]
> Double click to go up is already a thing in 2.3.12 and above.

Ahhh, correct. I didn't realized it. ☘️

**Comment by Josh65-2201** [comment]
@yair100 Should this be closed or updated for customizing/disabled the action it does

**Comment by yaira2** [comment]
There doesn't seem to be much interest in customizing the action.

**Comment by d2dyno1** [comment]
Apparently there are 10 likes on this issue...

**Comment by yaira2** [comment]
> Apparently there are 10 likes on this issue...

That's for the double click feature.
