### ISSUE TITLE
StatusBar control is not touch-friendly

### ISSUE THREAD

**Issue by MarcAnt01** [files-community/Files#2357]
**Is your feature request related to a problem? Please describe.**
Using it with touch buttons are to close to each other

**Describe the solution you'd like**
Use default uwp font size and button size

**Describe alternatives you've considered**
None

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?
![image](https://user-images.githubusercontent.com/43090263/99240516-e14b9180-27fc-11eb-89c7-9d98c19a12f8.png)

**Comment by yaichenbaum** [comment]
@MarcAnt01 The plan is to add an option to adjust the spacing and size of controls as part of #737.

**Comment by MarcAnt01** [comment]
@yair100 I don't really like the idea, all UWP controls are thought to be touch friendly by default. Files app is very good with touch, I don't think making this control bigger would have any cons.

**Comment by yaichenbaum** [comment]
@MarcAnt01 Files is used by both touch users and mouse users, therefore, instead of making the app oriented to just one kind of input we are going to add an option for the user to choose the mode themselves.

**Comment by MarcAnt01** [comment]
@yair100 I don't agre with this strategy, all the new parts of Windows 10 are made a bit bigger for touch users, moving on your path is a legacy way. Also the web is slowly moving towards touch-friendly UIs first

**Comment by yaichenbaum** [comment]
Touch friendly is important, however apps with a lot of options need to be careful to leave enough space to view the main content. Of course the touch user will prefer larger buttons over more space to view content and that is why we will make sure to provide that for them.

**Comment by MarcAnt01** [comment]
Sure, but I don't think that a bit of additional space for those buttons will reduce the available space

**Comment by yaichenbaum** [comment]
@MarcAnt01 Perhaps making them wider is fine, making them taller would require the options I mentioned above.

**Comment by MarcAnt01** [comment]
I don't think around 5 pixel could affect the overall space, while they could improve touch-screen experience

**Comment by MarcAnt01** [comment]
But it's your choice in the end

**Comment by mdtauk** [comment]
For what it's worth, I think touch should be the default affordance with the UI.

Then include an option to resize UI to optimize for mouse.  With a warning that this will make it hard to use on touch screens.

It's WinUI, the underlying assumption should be touch.  If only for consistency with other modern apps and the modern shell.

**Comment by yaichenbaum** [comment]
@mdtauk Once the setting is implemented we will actually set the default based on if the device is a touch screen or not.

**Comment by mdtauk** [comment]
> @mdtauk Once the setting is implemented we will actually set the default based on if the device is a touch screen or not.

That is a thing used by invokable UI, like context menus and flyouts. Not for entire apps.

You could detect if a device has no touch capability and use a Teaching Tip to inform the users wish to optimise for mouse.

But first presentation of the UI should use the same Metrics and sizing as all WinUI apps.
