### ISSUE TITLE
Drag and Drop from 7zip to any folder Crashes the app

### ISSUE THREAD

**Issue by agoogleuser** [files-community/Files#2359]
The app doesn't work nicely at the event of Drag & Drop from 7zip

1.open a compressed file/folder using 7z.
2. select a file and drag it to the destination folder in the Files - Preview app.
3. See error

The app craches giving a notification in action center called "New Notification".

 - OS Version: Windows 10 20H2 build 19042.630
 - App version: v0.20.0

**Log files**
[LocalState.zip](https://github.com/files-community/Files/files/5546605/LocalState.zip)

**Comment by gave92** [comment]
Merging with #2023
