### ISSUE TITLE
Suggestion For Files - Preview Always work using Adobe Creative Cloud for everything from every transparent interface to every All Files Designer - Preview always using Adobe Creative Cloud to always perfect everything from Files - Preview please Link For Site Oficial Adobe https://www.adobe.com/

### ISSUE THREAD

**Issue by AngelZeur** [files-community/Files#2367]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by AngelZeur** [comment]
Always work using Adobe Creative Cloud for everything from every transparent interface to every All Files Designer - Preview always using Adobe Creative Cloud to always perfect everything from Files - Preview please Link For Site Oficial Adobe https://www.adobe.com/

**Comment by mijorus** [comment]
please close this

**Comment by yaichenbaum** [comment]
@AngelZeur We are having trouble understanding this feature request, can you please fill out the template to give us a better idea what you are requesting?

**Comment by d2dyno1** [comment]
Some advertising spam
