### ISSUE TITLE
Cannot Open Items With Touch

### ISSUE THREAD

**Issue by TarsChiu** [files-community/Files#2369]
1. Go to start uwp
2. Click  **any** folder or  files on the **touch screen**
3. See error.**you can't open it**

 **- OS Version: [Windows 10 20H2 19042.630]**
 **- App version: [v0.20.0.0]**

**Comment by hez2010** [comment]
I cannot repro your issue.

**Comment by Jaiganeshkumaran** [comment]
@TarsChiu Could you try reinstalling the app from the Store?

**Comment by TarsChiu** [comment]
This issue just like you use the powerpoint on the touch screen ,it is hard to operat
You clicked but it is hard to poen it

**Comment by duke7553** [comment]
@TarsChiu Does this occur in ListView mode only or GridView also?

**Comment by TarsChiu** [comment]
Ehh,I‘m not sure that gridview mode was the same,
but i'm sure that listview mode must have this situation,
I will test gridview mode tomorrow.

**Comment by TarsChiu** [comment]
@duke7553 I have tested it today,this issue only occurs on listview mode,other mode is OK.

**Comment by BabaJJ** [comment]
doesn't work on Lenovo Yoga C640. Reinstall didn't help.

**Comment by TarsChiu** [comment]
@BabaJJ I have no Lenovo Yoga C640,and reinstall the issue still.

**Comment by Jaiganeshkumaran** [comment]
@TarsChiu Is this because of it's too small? Try pressing hard so we can make sure sizing is a problem.

**Comment by duke7553** [comment]
@Jaiganeshkumaran Yes. I should have been more clear with the reason why it's hard to tap items in the DataGrid. The rows are simply too small of a touch target. We have issues open for introducing custom sizing to the DataGrid.

**Comment by Jaiganeshkumaran** [comment]
@duke7553 The default control sizing works well on both mouse and touch input but we could automatically change the sizes when running in tablet mode to make it more touch friendly.

**Comment by yaichenbaum** [comment]
Merging with #2279.
