### ISSUE TITLE
Use acrylic for tabs background but solid color for sidebar by default

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#2371]

**Comment by mdtauk** [comment]
There is an already an Acrylic setting, and it is un-needed complication to have separate options for both the Tab/Title Bar and the Sidebar.

**Comment by Jaiganeshkumaran** [comment]
@mdtauk No I want acrylic always for tabs and optional acrylic for sidebar

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran We don't plan to add this level of customization, the best option would be to turn on the acrylic setting.
