### ISSUE TITLE
Add a way to quit the QuickLook preview by pressing Esc key

### ISSUE THREAD

**Issue by Cyberdroid1** [files-community/Files#2377]
**Is your feature request related to a problem? Please describe.**
It sometimes bugs me that I cannot exit the quicklook preview by pressing Esc. 

**Describe the solution you'd like**
Program it so that pressing Esc closes it, just like how the independent app works

**Additional context**
Also, make it so that when I change the selection of file, the preview should switch to preview of the newly-selected app.

**Comment by yaichenbaum** [comment]
Merging with #792 #1373.
