### ISSUE TITLE
Why not add double-click Settings?

### ISSUE THREAD

**Issue by i-curve** [files-community/Files#2379]
I'm used to selecting the file/folder by click, and opening file/folder by double click.

I don't find this setting. Why not add the feature?

**Comment by yaichenbaum** [comment]
@i-curve We are having trouble understanding this feature proposal, can you please fill out the issue template to better help us under your feature request?

**Comment by R3voA3** [comment]
The feature you describe is the default behaviour of Files.

**Comment by i-curve** [comment]
No, Single click will open folder. I want to open a folder by double click

**Comment by R3voA3** [comment]
Have you checked the settings?

**Comment by i-curve** [comment]
Oh, I didn't notice that. All right

**Comment by i-curve** [comment]
😄
