### ISSUE TITLE
Able to preview contents inside a folder

### ISSUE THREAD

**Issue by MrStefanW** [files-community/Files#2380]
**Is your feature request related to a problem? Please describe.**
It's not related to a problem in Quicklook, but something that is on MacOSX and would like to see on Windows.

**Describe the solution you'd like**
On MacOSX there is a column view that you can view contents of a folder when clicking on it. For my suggestion I have 2 ideas how it could be implemented.

**Copying the MacOSX feature.**
You will be able to switch between certain layouts one of these will be column view that works the exact same as on MacOSX. When clicking on a folder you get a preview on the right, if you decide to open the folder it moves to the left and continues to go on as far as the folders go.

**A popup that shows the contents inside**
Right click and select "Preview contents" or hit a keybind on the keyboard to open a popup that previews the contents of the folder. This will open a popup which you can interact with (such as scrolling, clicking on an image to preview it).

**Describe alternatives you've considered**
An alternative I have found which is very outdated was posted on [SuperUser](https://superuser.com/questions/1141631/make-windows-10-file-explorer-look-like-mac-osx-finders-column-view).

Additional context
[Suggestion #1 Screenshot](https://i.imgur.com/PCZ1h70.png)
[Suggestion #2 Screenshot](https://i.imgur.com/cq0rWfw.png)

**Comment by yaichenbaum** [comment]
Merging with #147 #130.
