### ISSUE TITLE
Right click animations and speeds.

### ISSUE THREAD

**Issue by MrStefanW** [files-community/Files#2381]
**Is your feature request related to a problem? Please describe.**
Currently when you right click on something it slides in at a speed that's too slow for me. 

**Describe the solution you'd like**
What I would like to see is being able to customize the animations for the right click menu to come in, and the speed of it. For me that would be a fade in for 1/4th of a second.

**Describe alternatives you've considered**
[WindowsFX](https://www.stardock.com/products/windowfx/) from Stardock, which does not work with Files.

**Comment by perplexityjeff** [comment]
I agree I would like to see at least options to change the animation speeds. From a productivity tool standpoint this change will make it a bit easier and faster to use.

**Comment by yaichenbaum** [comment]
@MrStefanW This issue should be resolved with #2805.
