### ISSUE TITLE
Rearrange "Open a specific page or pages"

### ISSUE THREAD

**Issue by ldsands** [files-community/Files#2383]
**Is your feature request related to a problem? Please describe.**
After I add pages to the "Open a specific page or pages" option in the "On Startup" tab in Settings there is no way to rearrange those folders.

**Describe the solution you'd like**
I can think of two options off the top of my head:
1. Click and drag these pages to create the order desired (my preferred option)
1. In the three dot menu next to each page add a move up or move down option.

**Describe alternatives you've considered**
I think the only ways to do this now is to delete each starting page and then recreate them

or

Use the change page location at the top and do that for each page going down

**Additional context**
![image](https://user-images.githubusercontent.com/7889104/99562779-23f0a380-298e-11eb-9380-1e4701f04ff6.png)

Unnecessary context: I'm in grad school and thus my starting folders change every semester. I would like to be able to change the order whenever I need to rather than having to delete all of the pages and then recreate them in the order I want.

**Comment by yaichenbaum** [comment]
@ldsands This feature was implemented in #3744.
