### ISSUE TITLE
Can you port the app over to windows phone 10??

### ISSUE THREAD

**Issue by fisforfaheem** [files-community/Files#2385]
it would be so cool! to use it on that lumia phone too! also please add subtle lottie live tiles

**Comment by yaichenbaum** [comment]
@fisforfaheem Windows Phone is no longer supported by Microsoft and many of the APIs that we rely on are not available for Windows Phone.

**Comment by fisforfaheem** [comment]
oh :( Really wanted this on my lumia though! anyway! keep improving the
explorer i hope it becomes faster in next release on hard disks. right now
it is very slow on mycore2duo
