### ISSUE TITLE
Drives space in Home widgets are not being updated after operations

### ISSUE THREAD

**Issue by osieltorres** [files-community/Files#2387]
**Describe the bug**
The disks space are not updated after `deleting`/`copying` files into it, it is necessary to restart the application to update.

**To Reproduce**
1. Go to application
2. Enter a disk, make any operation like `paste`/`delete` files, that modifies the space of the disk.
3. Go to *Home* view, and check the disk space.
4. The current space of the disk is the same as before `copy`/`delete` files.

**Expected behavior**
The disks widgets to be updated after files modification inside of the disk, or at least when we visit the *Home* view.

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2 19042.630 ]
 - App version: [v0.20.1.0]

**Additional context**
Currently, after the restart of the application, the disks space are updated. My suggestion will be to update the disks space everytime the *Home* view is displayed.

**Comment by gave92** [comment]
Merging with #2242
