### ISSUE TITLE
[Feature] translated element type in Drives Properties page

### ISSUE THREAD

**Issue by KristofKekesi** [files-community/Files#2394]
**Is your feature request related to a problem? Please describe.**
When I open the properties page of a drive every text is translated except the `element type`.

**Describe the solution you'd like**
Ability to translate the options.

**Additional context**
![005](https://user-images.githubusercontent.com/64812024/99698977-ba59bd80-2a91-11eb-8b4b-f14637d59961.PNG)

**Comment by XPoppyX** [comment]
Is it about the drives type translation?

**Comment by KristofKekesi** [comment]
Yes it is

**Comment by XPoppyX** [comment]
**See:** _Added localization for drive types_ #3466
