### ISSUE TITLE
QuickLook launching using space instead of menu

### ISSUE THREAD

**Issue by AndrewDaGuy** [files-community/Files#2404]
**Is your feature request related to a problem? Please describe.**
nope

**Describe the solution you'd like**
Just like the actual Quicklook app, you long-press space for Quicklook to open instead of going to the context menu.

**Describe alternatives you've considered**
Maybe you can also add as a setting for example:

**QuickLook** (ON/OFF)

**Additional context**
I saw QuickLook on the third party licenses so I assumed Quicklook was implemented or it's my Quicklook activating.

**Comment by yaichenbaum** [comment]
@AndrewDaGuy Do you have QuickLook installed? Pressing the space bar should already open QuickLook so let us know if you see anything different.

**Comment by osieltorres** [comment]
@yair100 why QuickLook is no longer supporting close when pressing ESC key in the app, as it currently does in windows file explorer? I think pressing Space key again to close is a little confusing, perhaps the app could support both methods.

**Comment by yaichenbaum** [comment]
Merging with #792.
