### ISSUE TITLE
Poor contrast of Status Center flyout in dark mode

### ISSUE THREAD

**Issue by duke7553** [files-community/Files#2405]
**Describe the bug**
Compared to light mode the status center flyout has poor contrast with the page background in dark mode.

**To Reproduce**
1. Open Status Center flyout at bottom right

**Expected behavior**
We should improve this so users understand the Flyout is present

**Screenshots**
![image](https://user-images.githubusercontent.com/20365014/99855947-f191a280-2b55-11eb-8538-70192b9fa5e5.png)

**Desktop (please complete the following information):**
 - OS Version: Dev Channel
 - App version: v0.20.2

**Comment by d2dyno1** [comment]
Status Center is lacking dropshadow.

**Comment by R3voA3** [comment]
It has a drop shadow for me and I personally find the contrast alright.

**Comment by mdtauk** [comment]
Drop Shadows are not very effective in Dark Themes, and so perhaps a highlight border around the flyout/dialog should be added (set to Transparent in Light Theme)

 
![image](https://user-images.githubusercontent.com/7389110/99874007-1e889880-2bdc-11eb-9f31-50c807215e49.png)

![image](https://user-images.githubusercontent.com/7389110/99874013-2a745a80-2bdc-11eb-975f-13136ab6fc33.png)

![image](https://user-images.githubusercontent.com/7389110/99874019-3d872a80-2bdc-11eb-91b0-fc97fe90672a.png)

![image](https://user-images.githubusercontent.com/7389110/99874025-50016400-2bdc-11eb-8000-134fc23bea32.png)

**Comment by yaichenbaum** [comment]
@duke7553 This issue should be resolved once we switch the colors of the content area with the colors of the sidebar.

**Comment by duke7553** [comment]
@yaichenbaum I'm not sure I follow. We need to change the background color of the Flyouts to something which differentiates it from the page background in dark mode.

**Comment by duke7553** [comment]
@mdtauk As always, thank you for these awesome visuals. 

We can definitely consider adding a border to the flyouts in dark mode, but I feel like it is more of an issue with the color itself because WinUI assumes apps use the default background color in dark mode. Since we use custom colors, the flyouts seem less differentiated when visible.

I'd wonder if there are there better background colors we can use exclusively with Flyouts rather than the defaults.
