### ISSUE TITLE
Crashes while inverting selection

### ISSUE THREAD

**Issue by Tombstone2K** [files-community/Files#2408]
**Describe the bug**
There are 1947 files in the folder. When I select one of them and proceed to invert selection, Files Beta crashes.
It works fine when the I tried it in a folder with 12 files.

**Comment by gave92** [comment]
Thanks for the report @Tombstone2K. Please fill out the issue template with the app version anche the log files to help us investigate the issue.

**Comment by duke7553** [comment]
Thanks again for your feedback. 

_Since we didn't hear from you on this topic for 3+ days, we'll assume everything is worked out and close this feedback item. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this._
