### ISSUE TITLE
Make text in the properties dialog responsive

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#2410]
When using the German localisation, the right attribute text is cut off due to the window being too narrow.

![image](https://user-images.githubusercontent.com/17484252/99872511-6f02f480-2be2-11eb-9fbd-05cf3de470e0.png)

**Comment by duke7553** [comment]
@R3voA3 
Thank you for creating this feedback item. A solution for it is currently being reviewed as a PR (pull request) to our active development branch. We'll let you know once it's merged.

**Comment by duke7553** [comment]
Thank you for creating this feedback item. This issue is currently resolved in our active development branch and will be shipped soon once we've validated that everything works properly. Please subscribe to our releases to be notified when this is available.
