### ISSUE TITLE
Increase margin between drives on the homepage

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#2411]
![image](https://user-images.githubusercontent.com/17484252/99873835-20a22580-2be3-11eb-85a4-527d495ef6a7.png)

The zoom effect causes them to overlap.

**Comment by yaichenbaum** [comment]
@R3voA3 I am keeping this open for now but it should be fixed when we ship the next beta build.

**Comment by R3voA3** [comment]
Fixed in current beta
