### ISSUE TITLE
.exe programs take a long time to load

### ISSUE THREAD

**Issue by i-curve** [files-community/Files#2413]
I suddenly realized that it couldn't run the ".exe" program and can't delete shutcut on desktop.

Is that a bug?

**Comment by yaichenbaum** [comment]
@i-curve What version of Windows are you running?

**Comment by i-curve** [comment]
20H2  (19042.630).
The software is too stuck in this version.

**Comment by i-curve** [comment]
To correct it, it is not that it does not run, but it takes a long time. Sometimes it just won’t run

**Comment by i-curve** [comment]
The same is true for other functions

**Comment by duke7553** [comment]
@i-curve Can you fill out the issue template to the best of your ability? We'd like to fix this one eventually, but we need more info from you first. 🙂

**Comment by duke7553** [comment]
Thanks for your feedback. We're having trouble understanding what you're requesting and need additional information to investigate this item. Please re-open when you've filled out the issue template to the best of your ability.
