### ISSUE TITLE
Make a way to use files as the default file explorer for windows please

### ISSUE THREAD

**Issue by Saihaan06** [files-community/Files#2416]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by yaichenbaum** [comment]
https://github.com/files-community/Files/wiki/Replacing-File-Explorer-with-Files-(Unsupported)
