### ISSUE TITLE
Add support for cloud storage options besides for OneDrive

### ISSUE THREAD

**Issue by moutasem1989** [files-community/Files#242]
I don't use onedrive but the icon is still there.. cant remove it
I use google drive and mega but they are not there...
maybe a way to get this through explorer API ?

**Comment by yaichenbaum** [comment]
If it is just a regular folder on your device we should be able to add a way to detect them and pin to the sidebar, however since this is not a Google Drive client

**Comment by yaichenbaum** [comment]
I suppose we can add a way to remove the OneDrive icon, as for other services you can right click on the folder and press pin to side bar.
![image](https://user-images.githubusercontent.com/39923744/67873445-d9de1b00-fb09-11e9-9301-853d07fd4e31.png)

**Comment by szaimen** [comment]
I would also appreciate this feature. 
And I would like to see Nextcloud added to the list.

**Comment by szaimen** [comment]
Google Drive File Stream and Nextcloud's Virtual Drive are probably much more complicated to add, am I right?

**Comment by yaichenbaum** [comment]
Its something we will look in to in the future but first we plan on a tighter OneDrive integration.

**Comment by yaichenbaum** [comment]
In recent versions of Files UWP, you can turn off the OneDrive integration if you don't want it.

**Comment by Jaiganeshkumaran** [comment]
Most cloud storage services provide client apps that sync your files similar to OneDrive. We could pin their folders if their client app is installed on the PC.

**Comment by yaichenbaum** [comment]
Support for Dropbox, Google Drive and Mega was implemented with #2311.
