### ISSUE TITLE
No copy/move progress screen is shown

### ISSUE THREAD

**Issue by askfriends** [files-community/Files#2423]
**Describe the bug**

**To Reproduce**
1. Go to 'any location'
2. Copy File/Files
3. Go to another folder/location
4. Paste and you wont see any copy progress dialog

**Expected behavior**
Please fix it so that copy/move files dialog must be shown

**Screenshots**
not necessary

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 20H2 19042.630]
 - App version: [v0.20.0]

**Comment by askfriends** [comment]
> @askfriends Do you have a status center on the bottom right of status bar? It should flash when an item operation starts.

oh i just noticed that and after playing with it i just noticed copy progress is not shown in real time, it says 0% and then finally say its 100%. it doesn't show copy speed or items being copied.
btw it should show windows like copy window and not small icon in bottom

**Comment by yaichenbaum** [comment]
@askfriends Can you open/upvote on existing issues regarding the issue where the progress is stuck?
