### ISSUE TITLE
Errore when lanch Debug

### ISSUE THREAD

**Issue by LucaRossi02** [files-community/Files#2424]
**Describe the bug**
When I debug, I get the error
"Exception thrown:" System.InvalidOperationException "in FilesFullTrust.exe
No handled exception of type "System.InvalidOperationException" in the
FilesFullTrust.exe private package identity process. (Exception from HRESULT: 0x80073D54)

'FilesFullTrust.exe' (CLR v4.0.30319: FilesFullTrust.exe): Speech bubble that says' C: \ Program Files (x86) \ Microsoft Visual Studio \ 2019 \ Enterprise \ Common7 \ IDE \ Remote Debugger \ x64 \ Runtime \ Microsoft.VisualStudio . Debugger.Runtime.dll "completed. Cartoon symboli ignored. The module is optimized and comes with the" User Code Only "debugger enabled.

The program "[9544] FilesFullTrust.exe: Program Trace" is terminated with code 0 (0x0).
The program "[9544] FilesFullTrust.exe" is terminated with code -1 (0xffffffff).
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
Please post the log file here so that we can understand your problem better. You can access it from Settings->About->Open log location.

**Comment by yaichenbaum** [comment]
@LucaRossi02 Make sure to set the Files.Package project as the startup project.

**Comment by LucaRossi02** [comment]
VS hadn't downloaded all the necessary files.
Now works!
