### ISSUE TITLE
Allow the user to add separators to the side bar

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#2426]
The context menu of the side bar should have an option to add a separator. This would make organizing custom entries easier.

Example:
![image](https://user-images.githubusercontent.com/17484252/100092735-d923cf80-2e56-11eb-9673-1fd345de4e27.png)

Alternatively allow the user to define a new header similar to **Drives**

**Comment by yaichenbaum** [comment]
I am going to merge this with #692. It is an interesting idea and it would be good to hear what other users think.
