### ISSUE TITLE
Integration with Bitdefender context menu

### ISSUE THREAD

**Issue by flumiie** [files-community/Files#2431]
**Describe the solution you'd like**
Add a context menu specifically for Bitdefender's. I'm not sure if it requires a special API or such, but that has been missing in the menu.
![FileExplorer](https://user-images.githubusercontent.com/8995187/100173494-3c683d00-2efd-11eb-8281-c67e4ecea80e.png)
![FilesUWP](https://user-images.githubusercontent.com/8995187/100173743-ada7f000-2efd-11eb-9a44-1b9018cd230a.png)

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?
- Desktop OS Version: [Windows 10 20H2 19042.662]
- App version: [v0.21.0]

**Comment by yaichenbaum** [comment]
@flumiie is this still an issue?

**Comment by flumiie** [comment]
I still don't have the option

**Comment by flumiie** [comment]
I might close this as it seems to be very specific to one software. I guess it's "impossible" for now. It's been 1.5 years and I'm now on Windows 11
