### ISSUE TITLE
Abnormal change the file name

### ISSUE THREAD

**Issue by YuJianghan** [files-community/Files#2433]
**Describe the bug**
When I change the file name, right-click in the options panel will flash back to disappear

**To Reproduce**
1. Select any one file
2. Right click - renamed
3. Right click

**Expected behavior**

**Screenshots**
![20201125_125105](https://user-images.githubusercontent.com/58395036/100184758-2bc7bf00-2f1d-11eb-8404-85a711f2f3ee.gif)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 2004 20262.1010]
 - App version: [v0.20.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?
Yes.

**Log file**
Please post the log file here so that we can understand your problem better. You can access it from Settings->About->Open log location.
[LocalState.zip](https://github.com/files-community/Files/files/5594498/LocalState.zip)

**Comment by gave92** [comment]
Thanks for the feedback. Merging with #1034
