### ISSUE TITLE
Feature: Support for showing shortcuts and hidden files in network drives

### ISSUE THREAD

**Issue by StijnBousard** [files-community/Files#2436]
**Describe the bug**
When using the Files app, I noticed that shortcuts were only shown in local drives, not in mapped network drives.

**Requirements**
- Network drives should display hidden files and folders when the option to show hidden items is turned on
- Network drives should display shortcuts

**Comment by yaichenbaum** [comment]
@gave92 do you know if this is resolved in `main`?

**Comment by gave92** [comment]
Nope

**Comment by gave92** [comment]
For reference: https://github.com/microsoft/WindowsAppSDK/discussions/83?sort=old

**Comment by JGomsss** [comment]
Hello, 
Do you have enough elements to resolve this issue.

**Comment by JGomsss** [comment]
> @JGomsss do you want to work on this?

Sorry I can't work on this but I can do tests as needed to upload logs.
