### ISSUE TITLE
Add menu option for pin an open tab.

### ISSUE THREAD

**Issue by osieltorres** [files-community/Files#2438]
**Is your feature request related to a problem? Please describe.**
I always working with many tabs inside the app, but, it is difficult for me each time I need to have a new tab pinned, to go to Settings and add the location for the new tab.

**Describe the solution you'd like**
I think would be better for if there is an option on the tab contextual  menu as example, to pin the current tab, adding that tab automatically to the list of pinned tabs in the Settings.

**Additional context**
Windows 10 version 10H2 [build 19042.630]
Files version: 0.20.6.0

**Comment by yaichenbaum** [comment]
Merging with #260.
