### ISSUE TITLE
App crashes when refresh if external application made change in folder opened by Files

### ISSUE THREAD

**Issue by osieltorres** [files-community/Files#2442]
**Describe the bug**
Files crashes and exit if any external application make some operation in a folder opened in Files when you refresh it.

**To Reproduce**
1. Go to application, open folder with files inside.
2. Click on open external app and perform operation over files inside same folder.
3. Go back to Files app and refresh current folder.
4. Files app crashes and exit without any message.

**Expected behavior**
The Files app to refresh and update changes made by other application in the current folder.

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2 19042.630]
 - App version: [v0.20.6.0]

**Additional context**
This happened while using an IDE, deleting some files in project folder, and then refresh in Files app. Also, looking at the log files, nothing is recorded related to the crash.

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5599204/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5599205/debug_fulltrust.txt)

**Comment by osieltorres** [comment]
The simplest test is to open the windows default explorer and create a folder while having opened same location in Files, then just go to the app and refresh the location, then the Files app crashes.

**Comment by gave92** [comment]
Thank for the report @osieltorres. I can't currently reproduce your issue and unfortunately since 0.20.0 a bug prevents the log file from being updated :/ Does this happen in an folder? Does it happen also when you perform operations on files using windows explorer and then refreh Files?

**Comment by osieltorres** [comment]
> Thank for the report @osieltorres. I can't currently reproduce your issue and unfortunately since 0.20.0 a bug prevents the log file from being updated :/ Does this happen in any folder? Does it happen also if the "external application" is windows explorer?

@gave92 Yes, as long as I have tested, happens on any folder, and also with windows explorer as the external app.

**Comment by gave92** [comment]
@osieltorres version 0.21.0 will be out soon. v0.21 restores the logging functionality, could you test whether the issue is still present and in that case upload the debug file? Thanks!

**Comment by osieltorres** [comment]
@gave92 I have tested after last app update to v0.20.7.0 and it seems the issue is solved, no crashes reported.
Thanks!

**Comment by gave92** [comment]
Feel free to reopen if you notice the issue in the latest version
