### ISSUE TITLE
Feature: Add support for searching in recycle bin

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#2447]

**Comment by gave92** [comment]
Searching inside a hidden folder crashes the app with UnauthorizedAccessException
`2020-12-15 19:55:53.7967|ERROR|Files.App|Accesso negato. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))|System.UnauthorizedAccessException: Accesso negato. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
   at Files.Filesystem.Search.FolderSearch.SearchForUserQueryTextAsync(String userText, String WorkingDirectory, Int32 maxItemCount)
   at Files.Views.Pages.ModernShellPage.ModernShellPage_SearchTextChanged(AutoSuggestBox sender, AutoSuggestBoxTextChangedEventArgs args)
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()`

**Comment by Hefaistos68** [comment]
Shouldnt Search show up in the "Ongoing Tasks" window?

**Comment by Hefaistos68** [comment]
[x] show somewhere what the search was about (currently it shows only "search results in (location)" )
[x] support for patterns, regex, history

**Comment by tech189** [comment]
Support for saving and opening already Saved Searches (.search-ms) files would be nice too. Pinning them to the sidebar would be awesome.

**Comment by eraychumak** [comment]
When searching in e.g. `Downloads` folder and pressing enter, pressing on `Downloads` in the sidebar should remove the search results override and show `Downloads` items as normal instead of having to first click on e.g. `Desktop` and then back to `Downloads` to see everything again.

**Comment by winston-de** [comment]
I noticed that you can't select search results from the drop down with arrow keys. Attempting to use the down-arrow key will open the first item. 
I'd like to add that to the list.
