### ISSUE TITLE
"Open items with a single click" doesn't always work

### ISSUE THREAD

**Issue by AkazaRenn** [files-community/Files#2448]
**Describe the bug**
When "Open items with a single click" is turned on, single click a folder sometimes doesn't open it (behaves like when the option is off). Even if the folder is opened, there would be some latency in between.

**To Reproduce**
1. Go to `Settings` - `Files and Folders`
2. Turn on `Open items with a single click`
3. Single click on folders to try to open it

**Expected behavior**
Items are always instantly opened without latency

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2
 - App version: 0.20.0.0

**Comment by yaichenbaum** [comment]
@AkazaRenn Thank you for opening this issue, I am going to mark this as fixed as I can't reproduce it in `main`.
