### ISSUE TITLE
Support to be able to set Files as the default file explorer

### ISSUE THREAD

**Issue by mister-hunter** [files-community/Files#2449]
**Is your feature request related to a problem? Please describe.**
It's not a problem, just a convenience request and a question

**Describe the solution you'd like**
Support to be able to set Files as the default file explorer

**Describe alternatives you've considered**
The default files explorer, but if that was good enough, I wouldn't be here :D

**Additional context**
![image](https://user-images.githubusercontent.com/49814847/100329276-bff15f00-2fcd-11eb-884d-02491fec3988.png)

Also, is there a Discord for Files?

**Comment by yaichenbaum** [comment]
You can already do this but it's not recommended because of the side effects, see [here](https://github.com/files-community/Files/wiki/Replacing-File-Explorer-with-Files-(Unsupported)) for more information.
