### ISSUE TITLE
Feature: Details Pane 

### ISSUE THREAD

**Issue by mbeps** [files-community/Files#2450]
**Is your feature request related to a problem? Please describe.**
Viewing details about specific files already exists. It should be possible to add a details pane on the side similar to the built-in File Explorer. This will allow the user to view file details without going to the properties. 

**Describe the solution you'd like**
In the settings, add an option to show the details pane similar to File Explorer. Once enabled, the details pane should be on the right side showing the details about the file selected. If nothing is selected, the pane should show the details about the current folder. The details pane should not disappear when nothing is selected as this will cause confusion and cause the icons in the folder to move around unnecessarily. 

**Describe alternatives you've considered**
Add a shortcut key that would automatically open a flyout showing the details. Possibly open the properties and automatically go the details tab automatically. 

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?
![image](https://user-images.githubusercontent.com/58662575/100360994-86cae600-2ff1-11eb-9dcd-e710c1b8188d.png)

**Comment by winston-de** [comment]
@yair100 Can you please assign me to this?

**Comment by yair100** [comment]
> @yair100 Can you please assign me to this?

Sure! Do you have any designs in mind before you start?

**Comment by winston-de** [comment]
@yair100 My plan is to use the design and most of the code from the properties: details page, but without the section headers and the clear properties button.
I was also planning on adding the file icon, an "open properties window" button, and ok/cancel buttons (that are revealed when the user makes a change) like Windows Explorer has.

**Comment by yaichenbaum** [comment]
What do you think about adding a grid splitter so users can resize the pane?

**Comment by winston-de** [comment]
@yair100 Good idea.

**Comment by mdtauk** [comment]
I think this is a space where some thought of information design could be put in.

Text hierarchy

![image](https://user-images.githubusercontent.com/7389110/102031143-f6d8ba80-3dac-11eb-986f-31da1a10c116.png)


Headers and body text, and ways to visualise the non-text based data.

Grouping of information such as permissions and status, and ordering these groups based on what typical file information a user wants to see.

Different filetypes may also display their file details in different ways.  Photos may focus on dimensions, the preview, as well as file size and formats.

**Comment by winston-de** [comment]
@mdtauk 
I agree with everything you said.

Personally I like the idea of using icons (like the one in the google photos sample). It would make it much more compact when the details pane is narrowed.

You also mentioned previews for photos, but what if we did previews for most file types? I think the way OneDrive does this is pretty solid.
<img src="https://user-images.githubusercontent.com/59544401/102420640-7639da00-3fb7-11eb-9a83-eac3403109c0.png" width="200"/>

**Comment by yaichenbaum** [comment]
@winston-de I think that this feature can be merged with #130.

**Comment by winston-de** [comment]
@yair100 Sounds good to me.

**Comment by winston-de** [comment]
Here's a rough mockup I made.

https://user-images.githubusercontent.com/59544401/102841205-5b9da180-43b9-11eb-8ff0-bbcc10c36d0c.mp4

**Comment by yaichenbaum** [comment]
@mbeps #2756 implements this feature request, please let us know if you have any feedback.

**Comment by mbeps** [comment]
I have not received the update yet via the Microsoft Store. I will let you know when I receive it.
