### ISSUE TITLE
Feature: Preview Content

### ISSUE THREAD

**Issue by mbeps** [files-community/Files#2451]
**Is your feature request related to a problem? Please describe.**
Allow user to preview certain type on content by using keyboard shortcut. Something similar to QuickLook. This should work with major file types such as png, jpg, pdf, etc. 

**Describe the solution you'd like**
Allow the user to press a certain key combination (for example Ctrl Space) to open a preview of a certain file that is selected. This will then open a small preview window for that file. Opening previews should be fast. 

**Describe alternatives you've considered**
No other alternatives found 

**Additional context**
![image](https://user-images.githubusercontent.com/58662575/100361463-17a1c180-2ff2-11eb-920a-31ed48bae20c.png)
Image from Brodenz

**Comment by yaichenbaum** [comment]
@mbeps Is there a reason that you would prefer this to Quick Look?

**Comment by mbeps** [comment]
I was asking for something similar to this to be implemented natively into the app. It's not important as you can still use the QuickLook app on Files UWP but a native implementation could have been more efficient and easier to find.

**Comment by yaichenbaum** [comment]
@mbeps We don't have any plans to build the Quick Look functionality into Files, however, we are looking at adding a preview pane #130.
