### ISSUE TITLE
Display Changelog on app start

### ISSUE THREAD

**Issue by d2dyno1** [files-community/Files#2454]
**Is your feature request related to a problem? Please describe.**
Many users don't know what's new in recent updates. Although there's already Releases tab on GitHub, and a changelog on Discord, many users aren't aware of that and don't bother checking. 

**Describe the solution you'd like**
Create a changelog tab in the settings menu with the most recent changes (and previous updates).

**Additional context**
Maybe we could get the GitHub changelog data via some api?

**Comment by yaichenbaum** [comment]
@d2dyno1 There is a link to the latest changelog in the settings page, is there an added benefit of building the release notes into the app?

**Comment by d2dyno1** [comment]
It's an accessibility feature, quality of life change. Users won't have to go to the Github page. Everything could be done on the Files' level.

**Comment by d2dyno1** [comment]
...or if making separate tab is not convincing enough, we could settle somewhere between, and add a popup dialog when starting Files right after updating, with information about latest changes. (And add "Learn more about recent updates" link, that would redirect to Github releases page)

I personally think that's the way of solving it, because many users expect to get some kind of information about the latest update

@yair100

**Comment by R3voA3** [comment]
When a new version is started for the first time a small **!** could be added to the status bar. Upon clicking on it, it would either link to the release page here on GitHub or show most important changes in the app.

**Comment by yaichenbaum** [comment]
After reviewing this proposal, we have decided against implementing this change. Users who are looking for the changelog can find it in the dedicated section in the Microsoft Store and on the GitHub release page.

**Comment by d2dyno1** [comment]
:/

**Comment by CyrilCharlier** [comment]
just a link ... super decision thanks .. so i can't be alert that a new version is installed ... with new features .. fix ,.. 
It is some communication  ; have you ever heard about it ? You know **geek** don't like it but **users**  love it !
