### ISSUE TITLE
Google Drive files not accessible

### ISSUE THREAD

**Issue by foggywindow2001** [files-community/Files#2456]
**Describe the bug**
the program cannot access or show folders and files stored in a linked google drive
[sorry if this is not clear, windows file explorer can access google drive files and folders using "google drive file stream" program, this does not seem to be working in this files app]
**To Reproduce**
1. Go to 'Drives'
2. Click on 'My Drive'
3. N/A
4. See error: displays "this folder is empty" when it should show folders and files stored in google drive

**Expected behavior**
I would expect the program to allow me to view, move and open folders and files stored in my google drive as the regular files program can do (once "file stream" has been installed.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 
 - App version: [v0.21.0.0]

**Additional context**
N/A

**Log file**
N/A

I'm sorry if this should be submitted as a feature request and not a bug, it's genuinely such an amazing app I really want to use it however this bug/missing feature is a deal-breaker for me. Anyways, amazing work, this app is otherwise stunning! 😍😍😍

**Comment by michaelhthomas** [comment]
+1, though this may apply to network locations in general, as file stream appears to mount the disk like a network share.

**Comment by yaichenbaum** [comment]
fyi @gave92

**Comment by gave92** [comment]
@foggywindow2001 thanks for this report.
Do the missing folders appear if you enable "show hidden files" in Files settings? (please try even if those files/folders are not hidden)
