### ISSUE TITLE
I can't open video files

### ISSUE THREAD

**Issue by whdmike** [files-community/Files#2460]
**Describe the bug**
I can't open video files .mp4 .mkv when I double click on a file. I cam open them through dialog open with and then choosing MP-HC in my case.

**To Reproduce**

I can't open video files .mp4 .mkv when I double click on a file. I cam open them through dialog open with and then choosing MP-HC in my case.

**Expected behavior**
open video files normally

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Additional context**
Add any other context about the problem here. For instance, are you building from source or using a precompiled build/snapshot?

**Log file**
Please post the log file here so that we can understand your problem better. You can access it from Settings->About->Open log location.

**Comment by yaichenbaum** [comment]
@whdmike Can you fill out the template with the version numbers?

**Comment by whdmike** [comment]
Latest app version 0.21, latest windows 10 home
PS: As I remember it was working in 0.20

**Comment by whdmike** [comment]
App is working now again normally. Could be that it didn't work just after update. Now after computer was restarted several times it opens video files again normally.
