### ISSUE TITLE
Files opens and closes after call start . from a CMD as admin

### ISSUE THREAD

**Issue by Chris2011** [files-community/Files#2462]
**Describe the bug**
When I open a CMD Line as an administrator and I want to call files from the cmd within a specific folder I type `start .` to open files. It opens and closes immediately.

**To Reproduce**
1. You need to register Files inside of the registry as your default explorer, see wiki
2. Open cmd as admin
3. Type `start .` and hit enter
4. See files open and closing immediately.

**Expected behavior**
Files should open, probably as an admin.

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2 19042.630]
 - App version: [v0.21.0.0]

**Log file**
https://pastebin.com/auZUF6fz

**Comment by yaichenbaum** [comment]
Merging with #1479.
