### ISSUE TITLE
ALT + Enter opens Properties window and selects next file/folder

### ISSUE THREAD

**Issue by Chris2011** [files-community/Files#2463]
**Describe the bug**
When I select a file or a folder and hit `ALT + Enter` it opens the dialog to see the information of that selected item and in the background, it will select the next item in the list.

**To Reproduce**
1. Open a folder with Files
2. Select a file or a folder
3. Hit `Alt + Enter`
4. Info window opens, next item will be selected

**Expected behavior**
The file/folder that I selected before I hit the shortcut, should still be selected and not changing the focus.

**Screenshots**
![alt+enter-problem](https://user-images.githubusercontent.com/795658/100456624-007dd500-30c1-11eb-901b-00b1aec82200.gif)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2 19042.630]
 - App version: [v0.21.0.0]

**Comment by yaichenbaum** [comment]
@Chris2011 This issue should be resolved with #3732.
