### ISSUE TITLE
Animation when closing the settings page is not smooth

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#2471]
The animation when opening the settings page appears smooth. When closing the settings however, the animation ends very abruptly.

Version: 0.21.0.0

**Comment by Jaiganeshkumaran** [comment]
@R3voA3 This is due to the way the settings page is layered. The navigation view is slightly different and it on the main page there's tabs so it may cause this visual glitch.

**Comment by yaichenbaum** [comment]
This issue appears to be resolved in `main`.
