### ISSUE TITLE
Folder and Icons are visualised when pinned to side

### ISSUE THREAD

**Issue by erosyte** [files-community/Files#2472]
**Is your feature request related to a problem? Please describe.**
One of the most important features tha Microsoft still hasn't aknowledge fully is the importance of being able to personalize icons. I use this on a daily basis via my quick access bar, with differentiated icons of folders. 

**Describe the solution you'd like**
Right now i see that, when pinning folders to the bar they retain a standard yellow folder icon, it would be great if they could follow that folder's unique icon instead.

**Describe alternatives you've considered**
The basic file explorer does this.

**Additional context**
I donated cuz of the quality of the app, keep up the great work guys!

**Comment by yaichenbaum** [comment]
@erosyte Is a picker like this what you had in mind, or are you looking for the option to use any image there?
![image](https://user-images.githubusercontent.com/39923744/103605776-c8995700-4ee2-11eb-80f3-aa11b12aa350.png)

**Comment by erosyte** [comment]
This is undoubtedly a step in the right direction, it would be a lot better already.

To maximize functionality, I would keep the icons flat (monochrome) , and let the user decide what color they want from a palette (like you do in windows personalization menu).

**Comment by yaichenbaum** [comment]
This issue should be resolve in `main`.
