### ISSUE TITLE
Change the color of base Windows System Icons

### ISSUE THREAD

**Issue by erosyte** [files-community/Files#2473]
**Is your feature request related to a problem? Please describe.**
Right now, the whole app uses the same color for everything, which in my case is white since I'm using the dark mode.
Something that is very useful when navigating through the various folders is being able to recognize a folder from it's icon color. 

**Describe the solution you'd like**
It would be great if 
1. You could change all Microsoft folder's color ( Like Music, Pictures, Documents etc.) with one color selector (kind of like the one in the system settings for the system's color.
2. You could change drive's individual color( and maybe the option to apply that same color to all of that drive's subfolders)
3. in general, a basic array of standard icons for folders + ability to choose that icon's color (games, screenshots, discs, installers, and other types of basic icons)

**Describe alternatives you've considered**
Changing the icons on Windows is a painstaking and fidgety process, you need to select each one manually.

**Additional context**

**Comment by duke7553** [comment]
@erosyte Unfortunately, we don't have plans to support modifying the color of system icons on a per-folder basis. However, support for color tags is planned for the future.

Please follow: #1161
