### ISSUE TITLE
The Name property of a focusable element must not be null. (ListView in the about page)

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#2478]
This is for list view items in about page

The following accessibility issue needs investigation.

**App:** Files

**Element path:** ListView items in the about page

**Issue Details:** The Name property of a focusable element must not be null. [Section 508 502.3.1](https://www.access-board.gov/guidelines-and-standards/communications-and-it/about-the-ict-refresh/final-rule/single-file-version#502-interoperability-assistive-technology)

**How To Fix:** Provide a UI Automation Name property that concisely identifies the element.

This accessibility issue was found using Accessibility Insights for Windows, a tool that helps debug and find accessibility issues earlier. Get more information and download this tool at https://aka.ms/AccessibilityInsights.

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran Do you have more information for which button or control has this issue?

**Comment by duke7553** [comment]
Thanks for your feedback. We're having trouble understanding what you're requesting and need additional information to investigate this item. Please re-open when you've filled out the issue template to the best of your ability.
