### ISSUE TITLE
Add a smaller version of the GridView layout mode

### ISSUE THREAD

**Issue by BooBerry** [files-community/Files#2479]
I'll keep this simple, I feel Layout mode > Grid View (Small)'s icon size is still too large, even on a 1440p screen (with Windows' scaling unchanged at 100%). Grid View (Small) would be more-or-less equal to File Explorer's View > Large icons in this case, and there's no size smaller than this (I use File Explorer's View > Medium icons by default in Windows 10).

**Is your feature request related to a problem? Please describe.**
Even with layout mode set to Grid Mode (Small) the icons still are too large, in my opinion. It's an aesthetic type of problem, but a problem nonetheless.

**Describe the solution you'd like**
A new option for an even smaller Grid View, e.g. **Grid View (Smaller)**. Grid View (Smaller)'s icons should be more-or-less equal to the size of File Explorer's View > Medium icons option.

**Describe alternatives you've considered**
The only alternative right now is Grid View (Small), but it leaves a lot to be desired as it's too large.

**Additional context**
Since this app's goal is to reach parity with File Explorer, adding this new Grid View option would make sense.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #2550.
