### ISSUE TITLE
Some folders don't appear on Local Disk in Files app

### ISSUE THREAD

**Issue by ahmedWaelSalem** [files-community/Files#2480]
**Describe the bug**
In Local Disk (E:) I have 205 GB and it's full/ only 7.42 GB free. The problem is not of these files is shown in Files - Preview.
even the app reads it's full. and on Files explorer everything is ok.

**To Reproduce**
1. Go to 'Drivers'
2. Click on 'Local Disk'
3. See error

**Expected behavior**
I should see my files.

**Screenshots**
![Files error](https://user-images.githubusercontent.com/40278600/100518758-465b9b80-319c-11eb-9c85-cf41993101c2.png)
![Files error 02](https://user-images.githubusercontent.com/40278600/100518777-612e1000-319c-11eb-9d8d-b64297896261.png)

**Desktop (please complete the following information): **
 - OS: 
Edition	   |   Windows 10 Pro
Version       |  20H2
OS build	   |  19042.630
Experience  |  Windows Feature Experience Pack 120.2212.31.0

 - App version: [v0.21.0]

**Additional context**
I use Microsoft store version

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5610776/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5610777/debug_fulltrust.txt)

**Comment by gave92** [comment]
@ahmedWaelSalem thanks for this report.
Do the folders appear if you enable "show hidden files" in Files settings? (even if those folder are not hidden)

**Comment by ahmedWaelSalem** [comment]
Yes, when I enable show hidden files and folders, folders appear. But I have on other drivers hidden files and folders appear correctly.
those folders and files aren't hidden. there is only 1 hidden folder and 2 unhidden

**Comment by ahmedWaelSalem** [comment]
It's a fix for now but I don't need to show hidden files.

**Comment by gave92** [comment]
Thanks for the confirmation, and yes this is just a temporary workaround
