### ISSUE TITLE
This folder is empty message

### ISSUE THREAD

**Issue by alunosnet** [files-community/Files#2486]
When pasting files into a empty folder the message that states the folder is empty should disapear.

Create a new folder, select files to copy, open the empty folder and paste.

As the files start to show the message should go away.
Version 0.21.0.0

![image](https://user-images.githubusercontent.com/6307206/100556101-a3884780-3297-11eb-8355-202c4ade081a.png)

**Comment by PrivOci** [comment]
If you click "refresh" or F5 it will disappear, but I agree it needs to be fixed

**Comment by yaichenbaum** [comment]
This issue should be resolved with #2504.
