### ISSUE TITLE
Arrange Items on the sidebar

### ISSUE THREAD

**Issue by AndrewDaGuy** [files-community/Files#2488]
**Is your feature request related to a problem? Please describe.**
nope

**Describe the solution you'd like**
Ability to move/arrange the items on the sidebar in settings.

**Describe alternatives you've considered**
`+ -` icons for adding/removing sidebar items and a new option in settings maybe called Sidebar or add it in appearance.

**Additional context**
There will be a preview of the sidebar and you'll be able to:
- Remove and Add items
- Move items but maybe they'll be sandboxed in there own place (C drive cannot be in the middle of docs and music) 
- Favorites?

Edit: Fixed where the plus and minus signs wont show up due to markdown.

**Comment by yaichenbaum** [comment]
Merging with #1069.
