### ISSUE TITLE
Dowload Redesign?

### ISSUE THREAD

**Issue by AndrewDaGuy** [files-community/Files#2489]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to sort my date modified but then when I go to my other stuff I have to sort by name again.

**Describe the solution you'd like**
Add headers or something like what the explorer uses with them displaying something like:
```
DOWNLOADS
_________________________

[Today]
foo.txt
bar.exe 

[Yesterday]
baz.js
qux.cs

[Last Week]
quux.cpp
waldo.css
```

**Comment by yaichenbaum** [comment]
Merging with #1874.
