### ISSUE TITLE
Border radius not applied

### ISSUE THREAD

**Issue by Sav22999** [files-community/Files#2491]
**Describe the bug**
Buttons (not selected/focussed) don't have the border-radius, they are "squared", as you can see in the screenshots

**To Reproduce**
1. Go to a generic Folder
2. Click on '[three dots at the top-right]'
3. Click on "New" then "Text document"
4. See the error

**Expected behavior**
The buttons should have the border radius

**Screenshots**
![image](https://user-images.githubusercontent.com/32335378/100590472-bf6e0680-32f4-11eb-8185-beac13257701.png)
![image](https://user-images.githubusercontent.com/32335378/100590513-cac13200-32f4-11eb-89be-8f990d97a647.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Pro 20H2 19042.630
 - App version: v0.21.0.0
**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Comment by yaichenbaum** [comment]
This issue should be resolved with #2503.
