### ISSUE TITLE
Create a "New (generic) file"

### ISSUE THREAD

**Issue by Sav22999** [files-community/Files#2492]
**Is your feature request related to a problem? Please describe.**
You can just create a "Text document", a "Folder" and a "Bitmap Image".

**Describe the solution you'd like**
I think it would be very great if you could create a "File" which is a generic file, without any extensions and, if you want to insert an extension, just write "Name.Ext"

**Comment by JER-ry** [comment]
***(I Am Not One of the Developers)***

Maybe this is more useful than the feature requested in #2192... However, it would be best if you can support all "Create New" options available on a certain PC.

By the way, the feature requested here is already provided by VSCode and seems good.

**Comment by Sav22999** [comment]
@JER-ry yeah, but it's useful (for me) if you can create a "empty" file.

You can create also on Explorer > Create a "txt" file > Then rename it and change the extension. But it's not the best practice, because this feature should be supported by default

**Comment by yaichenbaum** [comment]
@Sav22999 This issue should be resolved with #2644.
