### ISSUE TITLE
Crash on Delete

### ISSUE THREAD

**Issue by duke7553** [files-community/Files#2496]
**Describe the bug**
Delete throws an unhandled exception. This can be reproduced 100 percent of the time in my testing.

**To Reproduce**
1. Navigate to Downloads folder (likely any location)
2. Delete an item (not permanently) 
3. The app will crash, but it DOES look like the item was moved to the Recycle Bin as expected

**Expected behavior**
The app should NOT crash after deleting individual files as per the basic scenario above.

**Desktop (please complete the following information):**
 - OS Version: Dev Channel
 - App version: v0.21.0 (built from master)

**Additional context**
I suspect the problem comes from recent changes to the delete operation. 

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5618908/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5618910/debug_fulltrust.txt)

**Comment by duke7553** [comment]
FYI @d2dyno1

**Comment by yaichenbaum** [comment]
@duke7553 I can't reproduce this on my end, is this in debug mode?

**Comment by lukeblevins** [comment]
@yair100 Yes. Let me verify again that I have the latest changes.

**Comment by lukeblevins** [comment]
@yair100 I have the latest commits from master, but noticed this only occurs when deleting a single item only.

**Comment by duke7553** [comment]
![image](https://user-images.githubusercontent.com/20365014/100671637-d0d40480-332e-11eb-9609-70d2299dac54.png)
Helpful image from debugger

**Comment by Thomas1664** [comment]
Maybe it's my fault. Is this method called twice?

**Comment by duke7553** [comment]
@d2dyno1 Were you going to fix this one?

**Comment by d2dyno1** [comment]
I'll fix it in 1-2days

**Comment by d2dyno1** [comment]
Fixed with #2585?
