### ISSUE TITLE
Items Restored from Recycle Bin have no file extension

### ISSUE THREAD

**Issue by duke7553** [files-community/Files#2498]
**Describe the bug**
Restoring any items from Recycle Bin causes the newly returned items to lack a file extension

**To Reproduce**
1. Delete item with file extension
2. Navigate to Recycle Bin from Files
3. Invoke restore on the item(s)

**Expected behavior**
Items restored should keep their file extension regardless of user opting to have extensions hidden by default.

**Screenshots**
![image](https://user-images.githubusercontent.com/20365014/100671927-39bb7c80-332f-11eb-9f84-c4e7266c278c.png)

**Desktop (please complete the following information):**
 - OS Version: Dev Channel
 - App version: v21.0.0 (built from master)

**Additional context**
Reproducible regardless of how many items are deleted/restored at once.

**Log file**
Excluded for this, but will add on request

**Comment by yaichenbaum** [comment]
Merging with #1089.

**Comment by gave92** [comment]
Also related to #873
