### ISSUE TITLE
Shortcut to toggle hidden files

### ISSUE THREAD

**Issue by shubhammehra4** [files-community/Files#2502]
**Is your feature request related to a problem? Please describe.**
Currently to toggle hidden files you have to go in settings and toggle which is very inefficient.

**Describe the solution you'd like**
A keyboard shortcut to toggle hidden files or options to do it in the title menu.
**Describe alternatives you've considered**
A checkbox option in the menu situated at bottom-right corner to toggle the hidden files.

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by yaichenbaum** [comment]
@shubhammehra4 It looks like you have two feature requests, can you split up the issues and fill out the feature template?

**Comment by yaichenbaum** [comment]
@shubhammehra4 This issue should be resolved with #2854.
