### ISSUE TITLE
Right Click Animation Direction

### ISSUE THREAD

**Issue by Olcay91** [files-community/Files#2506]
If the mouse is on the upper half, the context menu is above the mouse cursor, but the animation is starting at the top instead of at the position, where the cursor is.

**Is your feature request related to a problem? Please describe.**
As far as i know, no

**Describe the solution you'd like**
It'd feel more natural if the animation would start from the cursors position upwards.

**Describe alternatives you've considered**
It'd also be possible to fade in the context menu without sliding it in, but it'd be less pleasant.

**Additional context**
![Image of Yaktocat](https://i.postimg.cc/nrZvg12Z/screen.jpg)

**Comment by yaichenbaum** [comment]
This appears to be an issue with the WinUI control and there isn't anything we can do. The best option is to turn off the animation from the settings page.
