### ISSUE TITLE
Cannot copy/paste to folders that require administrator access.

### ISSUE THREAD

**Issue by Sank30** [files-community/Files#2513]
> **Describe the bug**
> When I am trying to copy a file from one folder (Specifically C:/ folder) to another folder (In a C;/ folder only), the app does not show any status or progress and stays idle.
> 
> **To Reproduce**
> Copy a file form C:\Program Files (x86)\Google
>Goto option and try to paste, paste option will be disable
>Close the application and start again. 
>copy the same file again and then go to different folder C:\Program Files (x86)\Mozilla Firefox
> And try to paste in C:\Program Files (x86)\Mozilla Firefox(Or any app folder) you can see now a Paste option unable.
>On Paste It will show blue blink on the process button or stays idle.
>Now it will not copy anything in that folder just seats idle.

> **Expected behaviour**
> It should show the progress of the copying of a file or show a warning or error message if any restrictions or anything.
> 
> **Screenshots**
> 
![image](https://user-images.githubusercontent.com/73607086/100964170-099df480-354e-11eb-840a-0c36e730f4c3.png)
![image](https://user-images.githubusercontent.com/73607086/100964183-0efb3f00-354e-11eb-8ca6-8dabed64c7ed.png)
![image](https://user-images.githubusercontent.com/73607086/100964187-13275c80-354e-11eb-9101-ff9c3d875f6a.png)
![image](https://user-images.githubusercontent.com/73607086/100964196-17ec1080-354e-11eb-9540-b97a2270aef4.png)

> 
> **Desktop (please complete the following information):**
> 
> * OS Version: [e.g. Windows 10 1903 18362.175]
Edition	Windows 10 Home Single Language
Version	20H2
Installed on	‎01-‎11-‎2020
OS build	19042.630
> * App version: [v0.21.1.0]
> 
> **Additional context**
> Add any other context about the problem here. Does this problem occur again after restarting the app?
> 
> **Logfile**
> Please post the log file here so that we can understand your problem better. You can access it from Settings->About->Open log location.
[31dc1d55-2510-4715-985a-5c1a2e4a14b7.txt](https://github.com/files-community/Files/files/5633678/31dc1d55-2510-4715-985a-5c1a2e4a14b7.txt)
[debug.txt](https://github.com/files-community/Files/files/5633680/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5633681/debug_fulltrust.txt)

**Comment by yaichenbaum** [comment]
We usually expect users to fill out the issue template when reporting a bug, please reopen this issue when you have filled out the issue template.

**Comment by Sank30** [comment]
Requested Data
> **Describe the bug**
> When I am trying to copy a file from one folder (Specifically C:/ folder) to another folder (In a C;/ folder only), the app does not show any status or progress and stays idle.
> 
> **To Reproduce**
> Copy a file form C:\Program Files (x86)\Google
>Goto option and try to paste, paste option will be disable
>Close the application and start again. 
>copy the same file again and then go to different folder C:\Program Files (x86)\Mozilla Firefox
> And try to paste in C:\Program Files (x86)\Mozilla Firefox(Or any app folder) you can see now a Paste option unable.
>On Paste It will show blue blink on the process button or stays idle.
>Now it will not copy anything in that folder just seats idle.

> **Expected behaviour**
> It should show the progress of the copying of a file or show a warning or error message if any restrictions or anything.
> 
> **Screenshots**
> 
![image](https://user-images.githubusercontent.com/73607086/100964170-099df480-354e-11eb-840a-0c36e730f4c3.png)
![image](https://user-images.githubusercontent.com/73607086/100964183-0efb3f00-354e-11eb-8ca6-8dabed64c7ed.png)
![image](https://user-images.githubusercontent.com/73607086/100964187-13275c80-354e-11eb-9101-ff9c3d875f6a.png)
![image](https://user-images.githubusercontent.com/73607086/100964196-17ec1080-354e-11eb-9540-b97a2270aef4.png)

> 
> **Desktop (please complete the following information):**
> 
> * OS Version: [e.g. Windows 10 1903 18362.175]
Edition	Windows 10 Home Single Language
Version	20H2
Installed on	‎01-‎11-‎2020
OS build	19042.630
> * App version: [v0.21.1.0]
> 
> **Additional context**
> Add any other context about the problem here. Does this problem occur again after restarting the app?
> 
> **Logfile**
> Please post the log file here so that we can understand your problem better. You can access it from Settings->About->Open log location.
[31dc1d55-2510-4715-985a-5c1a2e4a14b7.txt](https://github.com/files-community/Files/files/5633678/31dc1d55-2510-4715-985a-5c1a2e4a14b7.txt)
[debug.txt](https://github.com/files-community/Files/files/5633680/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5633681/debug_fulltrust.txt)

**Comment by gave92** [comment]
@Sank30 does this happen also hen you try to paste to the Documents or Downloads folder?
Pasting to the Program Files folder is not working due to permission issues (you need to be administrator usually)

**Comment by Sank30** [comment]
No. It does not happen in that case.

**Comment by tasty0tomato** [comment]
**Please** fix it. It is a kind of annoying bug.

**Comment by yaichenbaum** [comment]
@Sank30 This feature was implemented in #4986.
