### ISSUE TITLE
Create New Folder with selected files

### ISSUE THREAD

**Issue by Olcay91** [files-community/Files#2517]
**Describe the solution you'd like**
As the title says, it'd be nice to have a feature where you can select multiple files and rightclick create a new folder where the selected files will be moved to.

**Additional context**
This feature is available a long time in macs Finder and helped me many times

![GitHub Logo](https://i.postimg.cc/Prjy2B29/screen.jpg)
Format: ![Alt Text](url)

**Comment by yaichenbaum** [comment]
Duplicate of #283.
