### ISSUE TITLE
Replace the Windows native file explorer

### ISSUE THREAD

**Issue by Michaelzhouisnotwhite** [files-community/Files#2518]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

我希望能直接替换windows的资源管理器，我非常喜欢你们的做品，希望将来有这样的途径

**Comment by yaichenbaum** [comment]
We usually expect users to fill out the issue template when reporting a bug, please reopen this issue when you have filled out the issue template.
