### ISSUE TITLE
 replace the native windows explorer.

### ISSUE THREAD

**Issue by Michaelzhouisnotwhite** [files-community/Files#2519]
**Is your feature request related to a problem? Please describe.**

i'm always frustrated when i press the button of  _downloads_  in chrome and then the native windows explorer is opened,but i want the **Files** UWP open.

**Describe the solution you'd like**
just like i describe above, i wish the uwp can replace the native windows explorer.

**Describe alternatives you've considered**
may be modify the reg.

**Additional context**
the latest version in Microsoft Store

**Comment by yaichenbaum** [comment]
You can follow this guide for instructions on settings Files as the default https://github.com/files-community/Files/wiki/Replacing-File-Explorer-with-Files-(Unsupported).
