### ISSUE TITLE
iCloud folder names are not shown right

### ISSUE THREAD

**Issue by jayasio** [files-community/Files#2521]
**Describe the bug**
Folder names from iCloud are not right; it shows some internal identification string instead.

**To Reproduce**
1. Open 'Files'
2. Click on 'iCloud'
3. See error

**Expected behavior**
Show the actual name as seen in Apple devices and win32 FIle Explorer..

**Screenshots**
![Screenshot (1)](https://user-images.githubusercontent.com/34701149/100961166-d9ebee00-3547-11eb-83d7-6beaa29ab927.png)

**Desktop**
 - Windows 10 2004 20262.1010
 - Files v0.21.2.0

**Log file**
Nothing from the log files.

**Comment by Jaiganeshkumaran** [comment]
@jayasio Those a virtual folders which may need to be queried separately. Are you using the Store version of iCloud or the desktop version?

**Comment by jayasio** [comment]
Desktop version... it's the same folder, just the naming is different in the app.

**Comment by gr3yta5ks** [comment]
I have the same issue too. Any updates or patches?

**Comment by gave92** [comment]
Fixed in latest code.
