### ISSUE TITLE
Opening files

### ISSUE THREAD

**Issue by Tucko29** [files-community/Files#2522]
I have issues with opening files. Every time I need to **right click** and choose **open with** after that files opens in corespodenting application. I have to do this every time, like it does not remembers. 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
Please post the log file here so that we can understand your problem better. You can access it from Settings->About->Open log location.

**Comment by yaichenbaum** [comment]
@Tucko29 We usually expect users to fill out the issue template when reporting a bug, please reopen this issue when you have filled out the issue template.
