### ISSUE TITLE
Context Menu Slow to Open

### ISSUE THREAD

**Issue by sguergachi** [files-community/Files#2527]
**Is your feature request related to a problem? Please describe.**

When I right click on a file item the right click context menu takes at least a few seconds, which is considerably slower than native File Explorer and frequently interrupts my flow of using this app, making it unusable for me.

**Describe the solution you'd like**

I want it to show context menu as soon as possible, and if need be, load additional context menu items asynchronously, that way items that should be readily available  (cut, copy paste) don't need to wait for context items that need more time to load in.

**Describe alternatives you've considered**

Using native file explorer.

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

This is my context menu for reference 
![image](https://user-images.githubusercontent.com/615386/101061125-25a99200-355e-11eb-98d4-7e1496e3f96e.png)

**Comment by sguergachi** [comment]
Basically if we can have an instant access to these items on right click and load in the rest as they come in, that would improve UX by a lot

![image](https://user-images.githubusercontent.com/615386/101061370-6d301e00-355e-11eb-847e-0896d0748e46.png)

**Comment by ShankarBUS** [comment]
How about using a CommandBarFlyout instead of a MenuFlyout?

Would that cause any problems?

**Comment by Chris2011** [comment]
I can reproduce it. But IMHO it is more a bug or misbehaviour than a new feature.

**Comment by gave92** [comment]
Some findings on this.

I've added a stopwatch in a couple of checkpoints to see what is taking the longest:
- [QueryContextMenu](https://github.com/files-community/Files/blob/master/Files.Launcher/Win32API_ContextMenu.cs#L231), 1 line
- [LoadContextMenu](https://github.com/files-community/Files/blob/master/Files.Launcher/Program.cs#L262) function in fulltrust process, which includes [1]
- [SetShellContextMenu](https://github.com/files-community/Files/blob/master/Files/BaseLayout.cs#L218) function, which includes [1] and [2] and is the total time taken to show the menu items

| QueryContextMenu [ms] | LoadContextMenu [ms] | SetShellContextmenu [ms] |
|:-----------------:|:-----------------: |:--------------------: |
|57                       |70                       |93                            |
|334                     |368                     |420                          |
|1576                   |1609                   |1681                        |
|2208                   |2232                   |2285                        |

More than 80% of the time is taken by the single line QueryContextMenu and the time taken by it varies greatly from a few milliseconds to more that two seconds. Anything above ~800ms is perceivable as a delay.
QueryContextMenu is pretty much a single Win32 API call so I'm not really sure on how to improve this.
One possibility is to call this without passing the `CMF_SYNCCASCADEMENU` option (synchronously load submenus), need to check if there are any unwanted side effects.

**Comment by Jenriksen** [comment]
If I can assist with solving this issue by any means please let me know. 
The project looks very promising, but almost 2 sec to open a context menu is just too much for most people.
I have some c# skills to utilize.

**Comment by sguergachi** [comment]
This should be included in work done in #4180

**Comment by pklion** [comment]
Can't we improve performance by hiding no-needed items?
I think it'll be better if the editor of right-click menu which valid only for Files available.

**Comment by Chris2011** [comment]
I think this just make sense when you select a file. In the normal explorer we have different entries for File, Folder and nothing is selected.

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.

**Comment by yair100** [comment]
The context menu is noticeably faster in the latest stable version Files v4.2.9. https://files.community/download
