### ISSUE TITLE
double click can not open file

### ISSUE THREAD

**Issue by linuxduduniao** [files-community/Files#2533]
files version: 0.21.1.0
window version: win10 profession 20251.1
--------------
double click file dose not work , and [Open] button on right menu does not work.
but [Open With] can open file success.
![image](https://user-images.githubusercontent.com/44915655/101109681-6cf15a80-3612-11eb-85db-f7ecab2b5119.png)

**Comment by yaichenbaum** [comment]
@linuxduduniao This issue should be fixed in `master` and will roll out when we ship the next update, in the meantime, try setting the sort option to sort by name.
