### ISSUE TITLE
The settings button is not in the correct place after updating to WinUI 2.5

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#2536]

**Comment by mdtauk** [comment]
Is this because of the new Bottom Items support in the NavigationView control?

**Comment by yaichenbaum** [comment]
> Is this because of the new Bottom Items support in the NavigationView control?

Yes, it's a little bit more than just changing the xaml in our case because of the setup we have but @duke7553 is planning to work on a fix.
