### ISSUE TITLE
Opening the properties window from the sidebar crashes the app after updating to WinUI 2.5

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#2537]
`2020-12-07 00:55:31.1217|ERROR|.ctor|The application called an interface that was marshalled for a different thread.`

**Comment by lukeblevins** [comment]
@yair100 Does the log file contain sufficient information for this crash?

**Comment by yaichenbaum** [comment]
@duke7553 I updated the description.

**Comment by osieltorres** [comment]
I have to say that the crash happens on every possible partition, not only for system, and not only from the sidebar.

**Comment by winston-de** [comment]
I believe the source of the issue is the NavigationView in Properties.xaml as the window will launch properly when it is removed.

**Comment by winston-de** [comment]
Using Windows.Ui.NavigationView instead of Microsoft.Ui.Xaml.NavigationView seems to be a workaround to this issue.
