### ISSUE TITLE
Properties window shows storage for current directory

### ISSUE THREAD

**Issue by nickhasoccured** [files-community/Files#2538]
**Describe the bug**
When opening the properties of a folder __pinned to the sidebar__, the storage information displayed will be for the currently open directory, not the one clicked.

**To Reproduce**
1. Navigate into any directory
2. Right-click a folder (other than your current folder) from the sidebar, then select Properties.
3. Observe the storage information (size, contains) in the properties window.

**Expected behavior**
The information displayed will be for the folder you clicked on. Instead, it displays your current directory's information.

**Screenshots**
![screenshot_1](https://user-images.githubusercontent.com/58091943/101202583-518c4c80-361e-11eb-9d6b-a46bb30c8095.png)
![screenshot_2](https://user-images.githubusercontent.com/58091943/101202596-551fd380-361e-11eb-9ee2-93576d230290.png)
![screenshot_3](https://user-images.githubusercontent.com/58091943/101202604-57822d80-361e-11eb-864f-26790cc15e13.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.630
 - App version: 0.21.1.0

**Additional context**
The problem is persistent, doesn't go away after restarting the app, and (from what I can tell) this bug occurs every time.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #2629.
