### ISSUE TITLE
all the icons of the folder full of videos and photos when I open the folder do not appear the icons showing does not load the icons is like this way of the photo I'm showing the print screen taking too long even to load correct it please

### ISSUE THREAD

**Issue by AngelZeur** [files-community/Files#2539]
**Describe the bug**
A clear and concise description of what the bug is and why it is more urgent than other issue reports. Can't answer this? Please return to the previous page and file a regular bug/feature report.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Additional context**
Add any other context about the problem here. For instance, are you building from source or using a precompiled build/snapshot?

**Log file**
Please post the log file here so that we can understand your problem better. You can access it from Settings->About->Open log location.
![Screenshot_1](https://user-images.githubusercontent.com/60907149/101207686-bca24700-364f-11eb-8a9a-421d552a9df6.png)

**Comment by duke7553** [comment]
@AngelZeur Please fill out the issue template to the best of your ability and re-open this. Thank you!
