### ISSUE TITLE
Folder icons not showing up

### ISSUE THREAD

**Issue by erayrafet** [files-community/Files#2542]
**Describe the bug**
A single folder icon is missing / not shown.

**Expected behavior**
All the default folder icons on the left to be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/34194191/101259394-57268700-3731-11eb-8d71-897c1f4f5b92.png)
![image](https://user-images.githubusercontent.com/34194191/101259510-b389a680-3731-11eb-895b-f7daa4112477.png)

**Desktop (please complete the following information):**
 - OS Version: 20270
 - App version: [v0.21.2.0]

**Additional context**
Can be seen in a few directories -- not specific to one but still random.

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5647557/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5647558/debug_fulltrust.txt)

**Comment by duke7553** [comment]
This was probably fixed with #5242, so I'll close this. Definitely open a new ticket if you see the problem occur again with the latest builds.
