### ISSUE TITLE
Ongoing Tasks when file copying reports too slow in chunks instead of realtime.

### ISSUE THREAD

**Issue by infuriatedcodex** [files-community/Files#2543]
**Describe the bug**
The Ongoing Tasks doesn't give real-time progress like the built in Windows File explorer does when copying files to network locations (SMB or UNC path). This becomes very obvious when copying a large amount of data (files and folders) around 10GB for example.

**To Reproduce**
1. Open 2 tabs, source and destination tabs
2. Select your files/folders that total a large amount e.g. 10GB (Video files are good example).
3. Watch as progress is reported in batches instead of realtime. e.g. shows 0% then 15or16%, the 35%, then 67% etc etc.

**Expected behavior**
Would expect streaming like continuous updates

**Screenshots**
Not possible or applicable based on the explanation above.

**Desktop (please complete the following information):**
 - OS Version: Window 10 20H2 build 19042.662
 - App version: [v0.21.1.0]

**Additional context**
Persistent in this version but never thought to look in early for comparison

**Log file**
N/A.

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
