### ISSUE TITLE
Can't open documents

### ISSUE THREAD

**Issue by Jon-Florin** [files-community/Files#2548]
I can't open the documents when typing or clicking. I just see the icon for the docutment but can't open it working on a surface pro x (ARM).

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
Please post the log file here so that we can understand your problem better. You can access it from Settings->About->Open log location.

**Comment by yaichenbaum** [comment]
@Jon-Florin We usually expect users to fill out the issue template when reporting a bug, please reopen this issue when you have filled out the issue template.
