### ISSUE TITLE
Right Click not working when the app stays idle for a few minutes

### ISSUE THREAD

**Issue by prakharsinghal001** [files-community/Files#2555]
When the Files UWP stays idle for about 3-5 minutes, right click somehow doesn't work. The problem is very annoying, please look after this bug.

**Comment by gave92** [comment]
@prakharsinghal001 thanks for this report. Please add the Files version to the issue description.
"Right click not working" means that the context menu does not appear at all? 
Does the app keep working or does it freeze?
