### ISSUE TITLE
Increase max GridView size for ctrl + scroll

### ISSUE THREAD

**Issue by Dylan-Osborne** [files-community/Files#2560]
**Is your feature request related to a problem? Please describe.**
In the current master branch, the max GridView size achievable by _ctrl + scroll_ is 220. It would be really appreciated if that max could be increased without modifying the default GridView layout sizes in the master branch ie. leaving the large, medium and small defaults as 220, 160 and 100 as set in #2479

**Describe the solution you'd like**
Increase the max GridView size achievable by _ctrl + scroll_. Windows Explorer's "Extra large icons" are approximately 270x275, so somewhere around there should be good, but it may be worth setting the max around 320 just to give users a little extra flexibility.

**Additional context**
Max GridView of 220 (as in master)
![Max 220](https://user-images.githubusercontent.com/46000533/101513657-1a52ce00-3985-11eb-8ffa-7549488a6570.jpg)

Proposed Max GridView of 320 (only achievable by _ctrl + scroll_ or _ctrl + +_ ie. not a default in the layout options flyout)
![Max 320](https://user-images.githubusercontent.com/46000533/101513666-1cb52800-3985-11eb-8df6-840dcfb778d9.jpg)

If you're happy with this proposal, can you assign me to it?

**Comment by yaichenbaum** [comment]
@Dylan-Osborne I believe this is already implemented.

**Comment by Dylan-Osborne** [comment]
@yair100 Running the current master I can't get past GridView size 220, here's what I mean
![Files-Dev-2020-12-08-20-00-07-Tr](https://user-images.githubusercontent.com/46000533/101522723-4aec3500-3990-11eb-8703-c1347cc6d643.gif)

If I'm correct the offending line is https://github.com/files-community/Files/blob/7b5aa84e92a03183b325431c8b684f153cba923b/Files/View%20Models/SettingsViewModel.cs#L651 as it's checked if the new value is smaller than Constants.Browser.GridViewBrowser.GridViewSizeLarge which is set to 220, this effectively limits the max size to 220.

**Comment by yaichenbaum** [comment]
@Dylan-Osborne I see it now, if you want to work on adding an option for 260, go ahead. I wouldn't add a menu option for this, instead, it can be accessed using `ctrl + +`.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #2561.
