### ISSUE TITLE
Quick Switch to "legacy" Explorer

### ISSUE THREAD

**Issue by rihards-simanovics** [files-community/Files#2565]
**Is your feature request related to a problem? Please describe.**
I find it frustrating to not be able to quickly switch from UWP Explorer to "Legacy" Explorer when you need to do something that is not supported in UWP explorer.

**Describe the solution you'd like**
I think it would be useful to have a context menu item, such as, "Open in Legacy Explorer" so that when you need to do something that is not supported by modern explorer, you can immediately open legacy explorer (in the current location but in new window) and do it there, rather than opening "legacy" explorer and navigating to the place you left of, it really hurts the flow and discourages from using UWP explorer. See the example below.

**Describe alternatives you've considered**
So, this one is slightly more difficult and probably less preferable but maybe try and emulate "legacy" explorer within the UWP? This will completely eliminate the need in use of the legacy explorer, and you could probably even integrate it in the tabs. See the example below.

**Additional context**
![image](https://user-images.githubusercontent.com/52106095/101584668-22872980-39d6-11eb-930b-3d579f49c890.png)
![image](https://user-images.githubusercontent.com/52106095/101585126-0afc7080-39d7-11eb-8a55-7124f620bba0.png)

**Comment by yaichenbaum** [comment]
@GreatRequest Can you try following the instructions [here](https://github.com/files-community/Files/wiki/Add-Files-to-the-File-Explorer-context-menu) by replacing the path for Files with the path for File Explorer?

**Comment by GreatRequest** [comment]
Hi @yaichenbaum , Thanks for the suggestion. Hmm, it would seem that File Explorer is unable to execute the script, please see the screenshot below.
![image](https://user-images.githubusercontent.com/52106095/101959667-a66f2a80-3bfd-11eb-9ba2-38a37b9a18bb.png)

**Comment by fisforfaheem** [comment]
would love to see it coming before 2020

**Comment by yaichenbaum** [comment]
@rihards-simanovics Can you share the script you tried running?

**Comment by rihards-simanovics** [comment]
hi @yaichenbaum , It's in the link you have posted above, "[Add Files to the File Explorer context menu](https://github.com/files-community/Files/wiki/Add-Files-to-the-File-Explorer-context-menu)".
```
; "Files" Files

[FilesHereInstall]
CopyFiles = Files.Files.Inf
AddReg    = FilesHere.Reg

[DefaultInstall]
CopyFiles = Files.Files.Inf
AddReg    = FilesHere.Reg

[DefaultUnInstall]
DelFiles  = Files.Files.Inf
DelReg    = FilesHere.Reg

[SourceDisksNames]
55="Files Here","",1

[SourceDisksFiles]
FilesHere.INF=55

[DestinationDirs]
Files.Files.Inf = 17

[Files.Files.Inf]
FilesHere.INF

[FilesHere.Reg]
HKLM,%UDHERE%,DisplayName,,"%FilesHereName%"
HKLM,%UDHERE%,UninstallString,,"rundll32.exe syssetup.dll,SetupInfObjectInstallAction DefaultUninstall 132 %17%\FilesHere.INF"
HKCR,Directory\Shell\FilesHere,,,"%FilesHereAccel%"
HKCR,Directory\Shell\FilesHere,Icon,,"%FilesHereIcon%"
HKCR,Directory\Shell\FilesHere\command,,0x00020000, "%%LOCALAPPDATA%%\Microsoft\WindowsApps\files.exe -Directory" ""%1""
HKCR,Directory\Background\Shell\FilesHere,,,"%FilesHereAccel%"
HKCR,Directory\Background\Shell\FilesHere,Icon,,"%FilesHereIcon%"
HKCR,Directory\Background\Shell\FilesHere\command,,0x00020000, "%%LOCALAPPDATA%%\Microsoft\WindowsApps\files.exe -Directory" ""%V""
HKCR,Drive\Shell\FilesHere,,,"%FilesHereAccel%"
HKCR,Drive\Shell\FilesHere,Icon,,"%FilesHereIcon%"
HKCR,Drive\Shell\FilesHere\command,,0x00020000, "%%LOCALAPPDATA%%\Microsoft\WindowsApps\files.exe -Directory" ""%1\""

[Strings]
FilesHereName="Files"
FilesHereAccel="Open Files"
UDHERE="Software\Microsoft\Windows\CurrentVersion\Uninstall\FilesHere"
FilesHereIcon=""%%LOCALAPPDATA%%\Microsoft\WindowsApps\files.exe",0"
```

**Comment by yaichenbaum** [comment]
@fisforfaheem That was just an example as a starting point, you would need to modify the script in order for it to launch file explorer.

**Comment by rihards-simanovics** [comment]
@yaichenbaum I guess the previous comment was for me. Now I see. Unfortunately, it wasn't too clear in the instructions that it was a template as it simply instructed to copy, paste and then install the script. So maybe perhaps it would be a good idea to mention the script provided in the wiki is a template.

Would you be able to give me a rough idea of what to edit as I am mostly a web developer and only do software development on the side as a hobby?

**Comment by rihards-simanovics** [comment]
@yaichenbaum Ok, now that I am on holidays, I can actually have some time to invest into `.inf` structure research. I must say it was fun as it brought back some good memories of Win XP days when you had to create an inf file for CD Auto Exec! Anyway back to the point, I got it to work but you may wont to refine it a little, as I am sure there is room to improve, the initial file had a major issue with the [Version] missing so that's why I couldn't install it on Win 10. Now without further due, here is my final result:

``` inf
; "Files" Files

[FilesHereInstall]
CopyFiles = Files.Files.Inf
AddReg    = FilesHere.Reg

[Version]
Signature   = "$WINDOWS NT$"
Provider    = %INF_Provider%
DriverVer   = 12/25/2020,1.0.0.1

[DefaultInstall]
CopyFiles = Files.Files.Inf
AddReg    = FilesHere.Reg

[DefaultUnInstall]
DelFiles  = Files.Files.Inf
DelReg    = FilesHere.Reg

[SourceDisksNames]
55="Files Here","",1

[SourceDisksFiles]
FilesHere.INF=55

[DestinationDirs]
Files.Files.Inf=17

[Files.Files.Inf]
FilesHere.INF

[FilesHere.Reg]
HKLM,%UDHERE%,DisplayName,,"%FilesHereName%"
HKLM,%UDHERE%,DisplayVersion,,"%FilesHereVer%"
HKLM,%UDHERE%,Publisher,,"%INF_Provider%"
HKLM,%UDHERE%,displayIcon,,"%FilesHereIcon%"
HKLM,%UDHERE%,UninstallString,,"rundll32.exe syssetup.dll,SetupInfObjectInstallAction DefaultUninstall 132 %17%\FilesHere.INF"
HKCR,Directory\Shell\FilesHere,,,"%FilesHereAccel%"
HKCR,Directory\Shell\FilesHere,Icon,,"%FilesHereIcon%"
HKCR,Directory\Shell\FilesHere\command,,0x00020000, "explorer.exe /n," ""%1""
HKCR,Directory\Background\Shell\FilesHere,,,"%FilesHereAccel%"
HKCR,Directory\Background\Shell\FilesHere,Icon,,"%FilesHereIcon%"
HKCR,Directory\Background\Shell\FilesHere\command,,0x00020000, "explorer.exe /n," ""%V""
HKCR,Drive\Shell\FilesHere,,,"%FilesHereAccel%"
HKCR,Drive\Shell\FilesHere,Icon,,"%FilesHereIcon%"
HKCR,Drive\Shell\FilesHere\command,,0x00020000, "explorer.exe /n," ""%1\""

[Strings]
FilesHereVer = 1.0.0.1
FilesHereIcon=""explorer.exe",0"
FilesHereName = "Open with ""Legacy"""
FilesHereAccel = "Open with ""Legacy"""
INF_Provider = "Griffin Web Studio, Ltd."
UDHERE = "Software\Microsoft\Windows\CurrentVersion\Uninstall\FilesHere"
```

PS: I have thoroughly tested it, and it shouldn't leave any reg keys behind, for some reason on the first run it left some stuff behind.

**Comment by rihards-simanovics** [comment]
Here is the final look:
![image](https://user-images.githubusercontent.com/52106095/103142926-31731900-4704-11eb-9633-a898fcce7eb5.png)

Just one problem, it opens behind the Files, not quite sure why, probably something to do with the fact how the explorer is called, oh well I can live with that, not that i will use it much anyway!

**Comment by fisforfaheem** [comment]
Looks great!

**Comment by yaichenbaum** [comment]
@rihards-simanovics That looks great!

**Comment by fisforfaheem** [comment]
looking forward to see this in windows 10 app
