### ISSUE TITLE
Improve App Startup Performance

### ISSUE THREAD

**Issue by dreaddr** [files-community/Files#2568]
**Describe the bug**
Slow to start, almost sluggish. I have an SSD and this hasn't happened before, overall the app feels laggy to use.

**To Reproduce**
1. Start the app and use it.

**Expected behavior**
Be fast and not be laggy.

**Screenshots**
How to add screenshots of the lag? 

**Desktop (please complete the following information):**
 - OS Version: 
Edition	Windows 10 Pro
Version	20H2
Installed on	‎11/‎18/‎2020
OS build	19042.630
Experience	Windows Feature Experience Pack 120.2212.31.0

 - App version: [v0.21.1.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app? **Yes.**

**Log file**
Please post the log file here so that we can understand your problem better. You can access it from Settings->About->Open log location.
[debug.txt](https://github.com/files-community/Files/files/5666643/debug.txt)

**Comment by fisforfaheem** [comment]
takes some time to load..

**Comment by dreaddr** [comment]
> takes some time to load..

It usually does, yes, but these wait times can be the difference between switching or sticking with native file explorer.

**Comment by yaichenbaum** [comment]
@dreaddr Do you have the setting to continue where you left off turned on? This can cause the app to load a little slower.

**Comment by dreaddr** [comment]
@yair100 nope, its turned off but I did toggle and try experimental features a bit, though it's the same performance even if I use experimental or not (its not noticeable) (Version 0.23.1.0 seems a bit smoother but maybe that has more to do with the animations or me having confirmation bias)

**Comment by dreaddr** [comment]
As of version 1.5.2.0, the app has become significantly more fluid and fast in its animations and transitions. It still needs refinement to get on par with explorer. One app I've seen that matches or even exceeds expectations of loading times is Notepads (also found in the MS Store) although its definitely not the same category of apps, maybe the devs can look into methods they've used to make sure the app loads fast.

**Comment by fisforfaheem** [comment]
Thanks! hoping to see this app improve over time and rival MSFt version

**Comment by gulshanmudgal** [comment]
The load time of files and folders is quite slow, After loading the application it takes at least 2-3 seconds to load all the drives and all the folders.

Another issue is, if any folder is opened then the folder icons don't appear at once, instead appear one by one.

**Comment by fisforfaheem** [comment]
i don't understand but version 2 seems so bland to me too ??? version 1 in
2020 was so much more than the current version??? why this happened?
version 1 was basically truly a good version back then new version UI is so
BLAND


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
08/08/21,
08:28:39 PM

**Comment by duke7553** [comment]
We're aware of an issue with virtually all versions of Files where we aren't making full use of the application prelaunch feature. Stay tuned!

**Comment by kaina-agency** [comment]
Would it be possible to allow the app to run in the background and launch on startup, so it's always ready to go?

**Comment by yaichenbaum** [comment]
> Would it be possible to allow the app to run in the background and launch on startup, so it's always ready to go?

We've been working on something similar but we ran into some issues getting it to properly work.

**Comment by duke7553** [comment]
In addition to the work implemented previous releases, we're exploring a new feature to drastically improve the startup time. The Files team takes pride in fully leveraging OS features where it makes sense, and application startup times are a high priority for us.

Fingers crossed we'll have this done for the next release.

**Comment by yaichenbaum** [comment]
Thank you for your feedback, we're continuously working to improve the startup speed of Files.

**Comment by yaira2** [comment]
We're excited to share that startup performance will be significantly improved in the upcoming release of version 3. You can download the preview version from our website https://files.community/download.
