### ISSUE TITLE
A11y: Progressbars for volumes don't have a UIA name

### ISSUE THREAD

**Issue by chingucoding** [files-community/Files#2569]
**Describe the bug**
When opening Files, the progressbars indicating the "fill up" of the volumes have no UIA name leaving the user with having to guess what the progress could indicate

**To Reproduce**
1. Open Files
2. Visit ProgressBars for volumnes using narrator item mode
3. Observe announcement

**Expected behavior**
ProgressBars should have a descriptive name
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Insider Build 10.0.20262 Build 20262
 - App version: 0.21.1.0

**Additional context**
Add any other context about the problem here. For instance, are you building from source or using a precompiled build/snapshot?

**Log file**
Please post the log file here so that we can understand your problem better. You can access it from Settings->About->Open log location.

**Comment by mdtauk** [comment]
Should it be a "friendly" readout of the storage?  So something like
**Internal Drive C.  Two Hundred and Ten Gigabytes of space remaining, out of Five Hundred Gigabytes capacity.**

**Comment by chingucoding** [comment]
If you visit the progressbar, it should only read out something like "80% of storage used" or something like that, the information which drive it is or how much storage is used exactly is already brough to the user through the label above and below the progress bar.

But you are touching another good point here: The label currently is announced as "two hundered and ten GB free of five hundered GB". I think it could be better to have the UIA name announce "gigabyte" instead of "GB" here.

**Comment by yaichenbaum** [comment]
@chingucoding Should the UIA name be added to the progress bar or should it be added to the parent control which in this case is a button?

**Comment by chingucoding** [comment]
Either add it to the progressbar so it get's announced in a helpful way (Narrator would announce "..., 80%, ProgressBar" instead of "80%, ProgressBar") or remove it from the control tree through the [AutomationProperties.AccessibilityView](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.automation.automationproperties.accessibilityviewproperty?view=winrt-19041).
