### ISSUE TITLE
A11y: Website link on abouts page should not be announced as "Link"

### ISSUE THREAD

**Issue by chingucoding** [files-community/Files#2571]
**Describe the bug**
The link to the website on the abouts page should not be announced as "link" but rather "Link, website" or something similar as in it's current form, it's hard to tell where the link will take you to if invoked.

**To Reproduce**
1. Go to about page
2. Visit Website link with narrator
3. Observe announcement "link"

**Expected behavior**
It should announce something like "Link, Website" to let users know what to expect.
**Screenshots**

**Desktop (please complete the following information):**
 -OS: Insider Build 10.0.20262 Build 20262
- App version: 0.21.1.0

**Additional context**

**Log file**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5668017/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/5668018/debug.txt)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #2574.
