### ISSUE TITLE
A11y: Properties window contains image without alt text

### ISSUE THREAD

**Issue by chingucoding** [files-community/Files#2572]
**Describe the bug**
Open a "properties" window of a folder, observe that the folder image has no alt text.

**To Reproduce**
1. Open folder in Files
2. Open properties panel
3. Observe narration of image being "image"

**Expected behavior**
Either leave out the image from the control tree or provide a descriptive name

**Desktop (please complete the following information):**
- OS: Insider Build 10.0.20262 Build 20262
- App version: 0.21.1.0

**Comment by yaichenbaum** [comment]
@chingucoding This issue should be resolved with #2670.
