### ISSUE TITLE
A11y: Info link next to date format dropdown has invalid UIA name

### ISSUE THREAD

**Issue by chingucoding** [files-community/Files#2573]
**Describe the bug**
The info link next to the date format dropdown on the appearance page has an invalid UIA name (single unicode character in the private UTF space). Instead it should have an appropriate UIA name describing it's purpose.

**To Reproduce**
1. Open appearence on settings page
2. Visit info link next to date format with narrator
3. Observe announcement: ""

**Expected behavior**
UIA name should be descriptive.

**Screenshots**

**Desktop (please complete the following information):**
- OS: Insider Build 10.0.20262 Build 20262
- App version: 0.21.1.0

**Comment by yaichenbaum** [comment]
This issue should be resolved with #2574.
