### ISSUE TITLE
Request: Consider a Slider for adjusting layout sizing

### ISSUE THREAD

**Issue by mdtauk** [files-community/Files#2575]
## Is your feature request related to a problem? Please describe.

With more sizing "breakpoints" being added for the keyboard shortcuts of resizing the Icon Views, It may be worth adding a slider for adjusting the sizing view Menus used with the mouse.

@yaichenbaum asked me to make this focused issue.
>Can you open a new proposal for this? Luke started work on a concept a couple of months ago that's similar to what you are describing.
>
![image](https://user-images.githubusercontent.com/39923744/101674400-6f92ec00-3a26-11eb-8d6f-23b2a3c75219.png)

## Describe the solution you'd like

A slider is often used when offering resize or zoom scenarios, and has been used by the existing File Explorer.  I would personally avoid using the term "Density" as it seems to apply more to padding and margins, than actual sizing.  The Tooltip and label for the slider value, should probably use friendly language like "Extra Large" and "Small"

## Describe alternatives you've considered

You can use Ticks to match the set sizes that exist in code.  It adds a little more complexity, in that it will no longer make much sense having named breakpoints - and there are also the different modes such as Lists, Tiles, Groups, which don't fit in as well as a plain icon view with sizing names.

## Additional context

![image](https://user-images.githubusercontent.com/7389110/101677076-fca06a00-3a53-11eb-9547-1341cd384a9e.png)

![image](https://user-images.githubusercontent.com/7389110/101677156-1641b180-3a54-11eb-92a7-f684c4b63994.png)

**Comment by yaichenbaum** [comment]
Fyi @duke7553

**Comment by yaichenbaum** [comment]
Merging with #1940.
