### ISSUE TITLE
Crash notifications are not working

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#2578]
It just says new notification

**Comment by duke7553** [comment]
Thanks for your feedback. We're having trouble understanding what you're requesting and need additional information to investigate this item. Please re-open when you've filled out the issue template to the best of your ability.

**Comment by gave92** [comment]
In recent versions when the app crashes the crash toast notification does not display the "report issue" button anymore but simply contains the text "new notification"

**Comment by gave92** [comment]
Fixed in #2752
