### ISSUE TITLE
Feature: Prompt user for credentials when connecting to smb-server the first time

### ISSUE THREAD

**Issue by szaimen** [files-community/Files#258]
**Describe the bug**
If I want to access my smb-server the first time, I type in \\\smb-server and press enter, then I don't get asked for my credentials. But if I do the same in file explorer, I get asked for the credentials and afterwards can access the server also with the files uwp app.

**Requirements**
- User is prompted with modal to enter password
- Modal has text feild to enter password
- Modal has connect button
- Modal has cancel button

**Comment by yaichenbaum** [comment]
Thank you for opening this issue.

**Comment by joshcangit** [comment]
This bug is also on my setup.
- OS Version: Windows 11 21H2
- App version: v2.1.24

**Comment by radu-cernatescu** [comment]
I'll be picking up this issue, thanks!

**Comment by szaimen** [comment]
🎉🎉🎉
