### ISSUE TITLE
Home page elevation effect overlay for folder shortcuts

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#2580]
**Describe the bug**
The elevation effect that comes when a folder shortcut is hovered overlays with the next folder on larger windows sizes.

**To Reproduce**
1. Go to Files
2. Hover on a folder item
3. See issue

**Expected behavior**
It should not overlay

**Screenshots**

![திரைப்பிடிப்பு (151)](https://user-images.githubusercontent.com/45227503/101870666-181c8980-3ba8-11eb-9fac-b4170981bc7a.png)

**Desktop:**
 - OS Version: Windows 10 version 20H2
 - App version: [v0.21.4]

**Comment by lukeblevins** [comment]
@yair100 Isn't this by design to imply elevation?

If so, we can close this.

**Comment by Jaiganeshkumaran** [comment]
@duke7553 I don't mean the elevation itself but if you see carefully on larger screen sizes it overlays the next box which doesn't occur in small screen sizes.

**Comment by generalguy41** [comment]
Here's a closer image of what I believe the issue is. You can see that there is an overlap that shouldn't be there. This is on 0.21.1.0 as well.
![image](https://user-images.githubusercontent.com/8879244/101914252-0def9080-3b92-11eb-993b-3490b66fc7e3.png)

**Comment by yaichenbaum** [comment]
@duke7553 This is a bug, the reason it happens is that the center point is not set correctly for those items.

**Comment by yaichenbaum** [comment]
Merging with #2246.
