### ISSUE TITLE
Add option to remove shortcut overlay

### ISSUE THREAD

**Issue by pgirzalsky** [files-community/Files#2581]
**Is your feature request related to a problem? Please describe.**
Customization is really important to me, and I would imagine, many others. Thus, I'd like the option to remove the shortcut arrows from icons, as it is possible in the default explorer as well. 

**Describe the solution you'd like**
Use the registry key that is set and used by the default explorer as well. Explanation of the key that is used to generate blank shortcut arrow: https://winaero.com/remove-shortcut-arrow-overlay-in-windows-10/

**Describe alternatives you've considered**
An additional option maybe in the app's settings but I imagine that would be more cluttered than my first approach.

**Additional context**
Example of what it looks like in "Files" and what it should look like as done by the Windows explorer:
![image](https://user-images.githubusercontent.com/48622652/101894351-57e27180-3ba6-11eb-8d0d-44d97bd8534f.png)

**Comment by yaichenbaum** [comment]
@pgirzalsky does the registry change work in Files?

**Comment by pgirzalsky** [comment]
@yair100 Sorry, never got a notification about this one!
No it doesn't. I have it set and it still shows the arrow shortcut in files.
