### ISSUE TITLE
Bug: File preview thumbnails not showing in grid and tile view's

### ISSUE THREAD

**Issue by pgirzalsky** [files-community/Files#2582]
### What feature or improvement do you think would benefit Files?
I'd like to be able to preview common file-types like psd, pdf, svg, ai etc. natively inside Finder. If that will be implemented, it would be great to have that preview appear also in the "details" layout mode. If you don't want that that to be the default for any reason, please add an option in the settings or so do to enable that. That is one of the best features of Mac's Finder for me so it would be a dream come true to have exactly the same behaviour in Windows!

### Requirements

- 

### Files Version

2.3.11.0

### Windows Version

10.19043.1899

**Comment by yaichenbaum** [comment]
Merging with #130.

**Comment by fisforfaheem** [comment]
any updates?

**Comment by ChildishGiant** [comment]
Would these implementations to add it to the explorer help?
https://github.com/tibold/svg-explorer-extension
https://github.com/microsoft/PowerToys/pull/5048

**Comment by Allen1351** [comment]
I really don't know if it is Windows or Foxit who handles my pdf thumbnail, but in Windows Explorer, I can see the thumbnail but in Files, I cannot. In the preview panel, it does show the thumbnail correctly.

**Comment by jobukkit** [comment]
> I really don't know if it is Windows or Foxit who handles my pdf thumbnail, but in Windows Explorer, I can see the thumbnail but in Files, I cannot. In the preview panel, it does show the thumbnail correctly.

If Foxit is your default PDF reader, then thumbnails are handled by Foxit. If you use Okular, which lacks thumbnail support on Windows, then Windows Explorer doesn't show thumbnails either.

Files should generate PDF previews by itself so that they work regardless of what PDF reader you use.

**Comment by Tarek-Hasan** [comment]
As I mentioned in #9842, you can use KDE's file manager [Dolphin](https://apps.kde.org/en-gb/dolphin/)'s thumbnail APIs which can generate thumbnail of audio, video, photo (including raw image), books (comic, e-book), documents (DOCX, PDF etc), graphics (SVG, PSD) and many more. These APIs are open source and well maintained. And also gets new file type support from time to time.
Useful links:
https://invent.kde.org/system/dolphin
https://invent.kde.org/multimedia/ffmpegthumbs
https://invent.kde.org/network/kio-extras/-/tree/master/thumbnail

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by Allen1351** [comment]
I tried a counterintuitive option and it fixed the issue of the thumbnails for me. I turned off the option inside the app that says "Show thumbnails" and now all thumbnails are showing correctly. So, if this option was indicating that the app itself should generate the thumbnails, that's the root of the problem.

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview builds?

@Allen1351 can you try with show thumbnails turned on?

**Comment by Allen1351** [comment]
![image](https://user-images.githubusercontent.com/41306138/191884049-885dad1d-9fd3-49a9-bea8-0bb06d5c80a3.png)
![image](https://user-images.githubusercontent.com/41306138/191884079-5a23a872-d3fe-4990-a375-bf8cc798e695.png)
![image](https://user-images.githubusercontent.com/41306138/191884093-baf26c95-b654-49be-9745-c9068cab4e78.png)

Here you can see what changes with the option on or off.

**Comment by yaichenbaum** [comment]
That's not the latest preview build, we made some changes that might of fixed this. https://files.community/download/preview

**Comment by Allen1351** [comment]
Ups. My bad. Didn't read the "preview" part. Now it works!!!

**Comment by yaichenbaum** [comment]
That's great news!
