### ISSUE TITLE
Use of partial path from enviroment variable

### ISSUE THREAD

**Issue by gmmazza** [files-community/Files#2586]
**Is your feature request related to a problem? Please describe.**
Is not a problem, just a feature. 

**Describe the solution you'd like**
The situation is this. I want to paste a partial path like "OneDrive\work\project 1" and the native file explorer will take the environment variable with OneDrive to fill the complete path to the local copy of OneDrive.

**Comment by MalteTasler** [comment]
it opens the file explorer for me, when typing something like "OneDrive\Pictures" into the address bar. So, it seems you have to set Files as default to make it work as expected. Is this already known?
