### ISSUE TITLE
Add a feature to also hide files that start with a "dot"

### ISSUE THREAD

**Issue by DiegoMagdaleno** [files-community/Files#2587]
**Is your feature request related to a problem? Please describe.**

Normally on Linux/macOS dotfiles are hidden, while this isn't the case on Windows systems, many apps still do a dotfile in the "home" directory, for example scoop:

`C:\Users\User\.scoop`

While in Windows you are supposed to hide folders using the hidden attribute, some Apps don't like this. This clutters the home folder with dotfiles, and makes the UI look a lot less clean, specially since they are always located at the start of the listing.

**Describe the solution you'd like**

I would love if we had a setting, inside "Files and folders" to "Also hide files starting with a dot", that is disabled by default, so that way users that don't want this feature aren't bothered by it, but users like me that want or wish to hide their "dotfiles" can do so.

Thanks for the amazing software!

**Comment by yaichenbaum** [comment]
@DiegoMagdaleno Can you check if turning off the option to show hidden items hides dot files?

**Comment by DiegoMagdaleno** [comment]
@yair100 i dont have that option enabled

**Comment by Jaiganeshkumaran** [comment]
@DiegoMagdaleno This doesn't make sense in Windows because Windows 10 treats dot files as regular files so users may get confused why their files are hidden.

**Comment by yaichenbaum** [comment]
> @DiegoMagdaleno This doesn't make sense in Windows because Windows 10 treats dot files as regular files so users may get confused why their files are hidden.

@Jaiganeshkumaran The feature request is about adding an option to hide them, the default will remain the way it is so that users don't get confused.

**Comment by R3voA3** [comment]
Why limit this to "." Giving the user an option to define wildcards would be neat as well.

**Comment by yaichenbaum** [comment]
@R3voA3 do you have a use case where that would make sense?

**Comment by DiegoMagdaleno** [comment]
@yair100 Tbh it sounds like a good feature, some users might want to assign their own patterns or wildcards to be able to hide files, it would be great if we could do that + it would be a unique feature.

**Comment by R3voA3** [comment]
Well, we could even go a bit further an talk about Regex. This would make this super customizable. All kinds of files in huge folder could be hidden.

@yair100  I work a lot with files which start with _ or __ these files clutter some folders a bit, so for me it would certainly be useful. With Regex I could even hide files with specific endings. The usecases are endless.

**Comment by yaichenbaum** [comment]
Do you have any concepts/mockups for how this could work?

**Comment by DiegoMagdaleno** [comment]
@yair100 Maybe something like this, is not an exact mockup, but its something i quickly designed on Adobe XD with Microsoft's Guidelines


<img width="918" alt="Screen Shot 2021-06-06 at 6 04 32 PM" src="https://user-images.githubusercontent.com/38844659/120942989-dc472480-c6f1-11eb-9e0f-2345cdea04b6.png">

<img width="925" alt="Screen Shot 2021-06-06 at 6 04 39 PM" src="https://user-images.githubusercontent.com/38844659/120942991-dfdaab80-c6f1-11eb-9a59-afca14383095.png">

**Comment by tyvsmith** [comment]
For folks that use WSL integration, this would be a big nice to have, as all linux distributions treat dot prefixed files as hidden

**Comment by d2dyno1** [comment]
@DiegoMagdaleno Closed with #8169
