### ISSUE TITLE
Add the option to filter items by from the column headers in the DataGrid layout

### ISSUE THREAD

**Issue by Vixb1122** [files-community/Files#2588]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
Nope

**Describe alternatives you've considered**
Nope

**Additional context**
![image](https://user-images.githubusercontent.com/17810492/101999644-1541a600-3d1a-11eb-9515-8c27b36f28fe.png)

In the file explorer, you can filter the entries by clicking on the arrow beside of button.

**Comment by yaichenbaum** [comment]
@Vixb1122 We usually expect users to fill out the issue template when reporting a bug, please reopen this issue when you have filled out the issue template.

**Comment by Vixb1122** [comment]
@yair100 reopen please.

**Comment by yaichenbaum** [comment]
This issue will be resolved with #6679
