### ISSUE TITLE
How to add registry entries that can be detected by Files

### ISSUE THREAD

**Issue by Vixb1122** [files-community/Files#2589]
1. Add a entry to context menu by follow code.
```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\Directory\Background\shell\self]
@=""
"MUIVerb"="Operate"
"Position"="top"
"SubCommands"="Restart Explorer;Restart;Shutdown"
```
2. Can't detect this entry

**Comment by gave92** [comment]
@Vixb1122 Files does not currently show the context menu items that appear when right clicking on a folder background/empty space, but only the ones that appear when right clicking on a folder item.
HKEY_CLASSES_ROOT\Directory\Background\shell won't work
HKEY_CLASSES_ROOT\Directory\shell should

**Comment by yaichenbaum** [comment]
Thanks again for your feedback.

_Since we didn't hear from you on this topic for 3+ days, we'll assume everything is worked out and close this feedback item. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this._
