### ISSUE TITLE
Can't display the directory that contains system in it's attributes

### ISSUE THREAD

**Issue by Vixb1122** [files-community/Files#2590]
**Describe the bug**
Can't display the directory that contains system in it's attributes

**To Reproduce**
1. open C:\Windows
2. retrieve fonts folder(with mode `d-r-s`)

**Expected behavior**
The directory contains fonts.

**Screenshots**
![image](https://user-images.githubusercontent.com/17810492/101983865-8a7c8f00-3cb8-11eb-98a7-ee668a6ac6d0.png)

![image](https://user-images.githubusercontent.com/17810492/101983807-3c678b80-3cb8-11eb-9723-cc105b16d5fe.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 2004
 - App version: v0.21.1.0

**Comment by yaichenbaum** [comment]
@duke7553 Is this the intended behavior?

**Comment by lukeblevins** [comment]
@yair100 It was. We should investigate whether this attribute type can work with our filesystem operations.

**Comment by yaichenbaum** [comment]
@duke7553 It should work but it should probably be behind a setting.

**Comment by gave92** [comment]
I've just tested this:
- Browsing system folders works
- Copying system files works
- All other operations (rename, move, delete) fail without crashing the app

I guess we can enable this, since rename, move, delete also fail for windows explorer if user is not administrator
What do you think?

**Comment by yaichenbaum** [comment]
@gave92 Do you think those issues can be solved by implementing an elevated full trust process?

**Comment by gave92** [comment]
@yair100 that would help I believe, some files you can delete only if you are admin.
System files can't be deleted even by admin unless the file owner/permissions are changed first (an elevated process should be able to change file permissions as well)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #2638.
