### ISSUE TITLE
Use translate platform to maintenance translate file.

### ISSUE THREAD

**Issue by Vixb1122** [files-community/Files#2592]
**Is your feature request related to a problem? Please describe.**
Some texts are not localized

**Describe the solution you'd like**
Use translate platform to maintenance translate file.

**Describe alternatives you've considered**
https://crowdin.com (non-free)
https://www.oneskyapp.com (non-free)
https://poeditor.com (free less than 1 000 Strings)

**Comment by smarquespt** [comment]
I also would like to have this. It more user friendly than messing with resource file.

> https://crowdin.com (non-free)

I'm not sure wht you've meant by non-free but crowdin as a free plan for oss - https://crowdin.com/page/open-source-project-setup-request

Also transifex has a free plano for oss - https://docs.transifex.com/projects/open-source-project

**Comment by yaichenbaum** [comment]
We don't have plans to setup a translation service at this time, however, you can try using the tools linked to in the [documentation](https://files-community.github.io/docs/#/articles/translating-files) to make translating Files easier.
