### ISSUE TITLE
Files does not open

### ISSUE THREAD

**Issue by JanKrulak** [files-community/Files#2597]
Dear Developers,

I have downloaded the Files today - looking really good. However, when I try to open any file (MS word, pdf, cad file, etc.), it does not open at all.

On the following link, you can see me trying to open files. https://www.dropbox.com/s/ttdm7rajrp9x586/Screen%20Recording%202020-13-12%20at%2018-09-07.mp4?dl=0

Kind regards,

Jan Krulak

**Comment by yaichenbaum** [comment]
@JanKrulak Can you try changing the sort mode? The store release has an issue where changing the sort mode can prevent opening items.

**Comment by JanKrulak** [comment]
Hi,
Yes, that solved the issue. I have changed it from sort by type to sort by name and it worked.
Many thanks!
Kind regards,
Jan
    On Sunday, 13 December 2020, 18:11:52 GMT, Yair Aichenbaum <notifications@github.com> wrote:  
 
 


@JanKrulak Can you try changing the sort mode? The store release has an issue where changing the sort mode can prevent opening items.

**Comment by yaichenbaum** [comment]
@JanKrulak Thank you for letting us know, we fixed the issue in `master` and it will be available with the next update.
