### ISSUE TITLE
Please display folder sizes beside them, its my biggest gripe with file explorer.

### ISSUE THREAD

**Issue by doggo404** [files-community/Files#2598]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by yaichenbaum** [comment]
@doggo404 Displaying the folder sizes will have a considerable impact while loading directories, we would like to display them however we are not aware of an efficient way to do so.
