### ISSUE TITLE
Context menu for tabs

### ISSUE THREAD

**Issue by szaimen** [files-community/Files#260]
**Is your feature request related to a problem? Please describe.**
I would like to change the sort order of tabs and open already open tabs in new windows

**Describe the solution you'd like**
I would like to pull one tab out of the tab row to let it open in a new window. (you can do this in edge) and change the sort order of tabs through pulling

**Describe alternatives you've considered**
Maybe you could also enable us to right-click on tabs to get e.g. the following options (most of the are also seen e.g. in Edge):
- [x] duplicate tab
- [x] **move tab to new window** (most important in my opinion)
- [x] close tabs to the right
- [ ] pin tab
- [x] new tab

**Additional context**
![image](https://user-images.githubusercontent.com/42591237/67966370-155d1000-fc04-11e9-9062-46b734c1b77b.png)

**Comment by yaichenbaum** [comment]
You can already change the order of tabs through pulling if you build the application of the master branch.
The other stuff we plan on doing, thanks fro creating this issue to keep track of it.

**Comment by yaichenbaum** [comment]
I updated the original pitch with some more information, I also realized that you might have meant pulling tabs for touch which is not implemented at the moment. I had originally tested with a mouse. I think this pitch now includes what we need so I will go ahead and approve this.

**Comment by szaimen** [comment]
Maybe "move tab to new window" could get updated to "move tab to new window or to an already open other one"? 
I can do this if you agree.

**Comment by yaichenbaum** [comment]
I don't want to add too many options to the menu but if enough people would find it helpful then we can explore adding a second option "Move to an open window" and that would have a sub menu with the other open windows.

**Comment by yaichenbaum** [comment]
Improvements to touch and pulling tabs should come in a future update of WinUI.

**Comment by Jaiganeshkumaran** [comment]
This is no longer relevant since the latest version has removed TabView.

**Comment by szaimen** [comment]
> This is no longer relevant since the latest version has removed TabView.

Why, do you have a screenshot of the new tab layout?

**Comment by Jaiganeshkumaran** [comment]
Here's the new layout. Tabs are no longer stacked on the tab like a browser. Instead, there's now a button for switching between and adding new tabs.
![திரைப்பிடிப்பு (7)](https://user-images.githubusercontent.com/45227503/87798950-3cc73c00-c86a-11ea-9281-34825c99a6c5.png)

**Comment by szaimen** [comment]
Thanks for the screenshot!

**Comment by generalguy41** [comment]
> Here's the new layout. Tabs are no longer stacked on the tab like a browser. Instead, there's now a button for switching between and adding new tabs.

This is optional... right?

**Comment by szaimen** [comment]
> This is optional... right?

I am afraid, it is not optional.

**Comment by Jaiganeshkumaran** [comment]
@szaimen You're right. This is not optional. The entire tab system has been rewritten.

**Comment by generalguy41** [comment]
@Jaiganeshkumaran that's really unfortunate.

**Comment by Jaiganeshkumaran** [comment]
Horizontal tabs are back in the latest preview.

**Comment by d2dyno1** [comment]
![itachi_mangekyou_sharingan_eyes](https://user-images.githubusercontent.com/53011783/109724848-7efe7d00-7bb0-11eb-8ea2-2e223fef58d8.png)

**Comment by d2dyno1** [comment]
I'll work on "close tabs to the right" :+1:

**Comment by d2dyno1** [comment]
@szaimen @yaichenbaum #3929

**Comment by yaichenbaum** [comment]
Merging with #3068.
