### ISSUE TITLE
Support launching more items from Path Box like Windows Explorer

### ISSUE THREAD

**Issue by ZENGJIACOM** [files-community/Files#2600]
Displayed when the start command WT of Windows Terminal is entered in the address bar ![Error Image](https://user-images.githubusercontent.com/58651265/102046578-8bc3ce00-3e16-11eb-8167-581d2ae2639f.png),But it is normal in file Explorer

**Comment by duke7553** [comment]
@ZENGJIACOM The path box currently doesn't use the user's environment variable Path as context when launching items. This means you can only enter absolute paths or type to find an item from the working directory. 

However, we can triage this as a feature request.

**Comment by yaichenbaum** [comment]
@ZENGJIACOM The `wt` command will only work if you added a profile for Windows Terminal in preferences, have you tried doing that?

**Comment by yaichenbaum** [comment]
Thanks again for your feedback.

_Since we didn't hear from you on this topic for 3+ days, we'll assume everything is worked out and close this feedback item. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this._
