### ISSUE TITLE
Add Third Party Cloud Storage Support

### ISSUE THREAD

**Issue by mbeps** [files-community/Files#2603]
**Is your feature request related to a problem? Please describe.**
Allow users to use another cloud storage provider other than Microsoft OneDrive. If Google Drive Sync is installed then 

**Describe the solution you'd like**
For example, if Google Drive Backup & Sync is installed, then it should automatically be displayed on the 'Drives' section where OneDrive is. Additionally, if OneDrive is not installed, then it should not be displayed in the 'Drives' section.

**Describe alternatives you've considered**
The user can manually add cloud storage locations from the settings. For example, the user can go to settings, add a cloud storage provider manually, and locate the folder for cloud storage. 

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by yaichenbaum** [comment]
@mbeps this is already implemented in v0.21.1, can you fill out the issue template so we can investigate why it's not working on your device?
