### ISSUE TITLE
When there are no search results, show text: "No items match your search"

### ISSUE THREAD

**Issue by Rick-HM** [files-community/Files#2605]
Show this text when there are 0 results:
![Captura de pantalla 2020-12-14 231808](https://user-images.githubusercontent.com/61259627/102159684-c6ebee80-3e62-11eb-8972-c656c3cd35cf.png)

**Comment by duke7553** [comment]
@XPoppyX Thank you for bringing this to our attention. @yaichenbaum added this to #2447 for visibility

**Comment by BanCrash** [comment]
This was added with #5842
