### ISSUE TITLE
Context Menu is not in the window when using keyboard 'Menu' Button

### ISSUE THREAD

**Issue by MadhiasM** [files-community/Files#2609]
**Describe the bug**
When trying to open the context menu (usually using right mouse click) with my keyboard menu button (see image 1), the menu appears at the top of the screen with the upper half cut off when it should appear starting at the selected element. 
(Image 2)

**To Reproduce**
1. Select a file or folder in the explorer
2. Hit the 'Menu' button on your keyboard
3. Menu appears at the wrong position

**Expected behavior**
The context menu should appear starting at the selected element. (Image 3)
**Screenshots**
[
![image](https://user-images.githubusercontent.com/47840254/102236575-f565da00-3ef3-11eb-8d22-8efb7a18221d.png)
](url)
![Screenshot (28)_LI](https://user-images.githubusercontent.com/47840254/102237529-0fec8300-3ef5-11eb-8b74-6891d6e34651.jpg)
![Screenshot 2020-12-15 164721](https://user-images.githubusercontent.com/47840254/102237767-4a562000-3ef5-11eb-8e68-e2aee3a2ed37.jpg)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 10.0.19042 Build 19042]
 - App version: [v0.21.1.0]

**Comment by gave92** [comment]
I'm also pretty sure that the shown menu is related to the folder you are in and not to the currently selected item.
Grid view works correctly

**Comment by MadhiasM** [comment]
> I'm also pretty sure that the shown menu is related to the folder you are in and not to the currently selected item.
> Grid view works correctly

Yes, you are right, it is the menu of the folder, but since the item is selected, the menu should actually refer to the selected item like in MS explorer. Plus the menu is cut off due to its position in any case. For reference I attached a gif of the issue while using keyboard inputs plus the same for MS explorer. Files actually unselects the file when hitting the menu key and thus shows the menu for the current folder.

![Animation_2020-12-17-18-40-31](https://user-images.githubusercontent.com/47840254/102523894-7f4ea800-4098-11eb-8d11-43b4500c205e.gif)


![Animation_2020-12-17-18-50-15](https://user-images.githubusercontent.com/47840254/102524059-bae97200-4098-11eb-9643-e386599ef1dd.gif)

**Comment by gave92** [comment]
@MadhiasM same in my testing, thanks for the confirmation.
Only difference is that for me the menu appears on the left of the file list (but anyway is the menu for the wring item)
Does it make a difference if the Files window is smaller/not maximized?

**Comment by MadhiasM** [comment]
Yes, you're right, whenn the window is not maximized the menu will appear in different positions. The position depends on where the not maximized windows is located :If there is a lot of space on the left it will appear on the left and so on. (Same for Top, Bottom, Right). In that case, the menu is not cut off, but still not the correct menu

**Comment by Cyberdroid1** [comment]
Seems like the files inside the folder aren't getting focused.

**Comment by Jaiganeshkumaran** [comment]
@MadhiasM Does this issue only occur in list view layout mode or in all layout modes?

**Comment by MadhiasM** [comment]
Good observation, it seems that this only occurs in list view

**Comment by yaichenbaum** [comment]
Thank you for opening this issue, it's something we would like to resolve but we are held back because the DataGrid control is outdated. WinUI is planning to create a new DataGrid control, I am linking the discussion here so you can upvote/comment on the issue and hopefully increase the priority for Microsoft. https://github.com/microsoft/microsoft-ui-xaml/issues/1500
