### ISSUE TITLE
Icons are not shown the first time you open the app

### ISSUE THREAD

**Issue by alberto-diaz15** [files-community/Files#2614]
When i open the app, all thumbnails look the same but next times it's corrected:

![image](https://user-images.githubusercontent.com/72040488/102369378-2578b000-3fbc-11eb-894b-d9feddf20e6c.png)

![image](https://user-images.githubusercontent.com/72040488/102369432-36292600-3fbc-11eb-934e-2f84fac377c5.png)

**Comment by gave92** [comment]
@alberto-diaz15 can you confirm that this only happens if you enable the "continue where you left off" option in Files settings?

**Comment by alberto-diaz15** [comment]
I had enabled "Open new window"

**Comment by gave92** [comment]
Same effect, thanks for the info!

**Comment by alberto-diaz15** [comment]
When i said "open new window" i meant "open new tab", sorry because i have the program in spanish.  With "continue where you left off" I have the same issue.

And yes, if i wait 3-5 seconds the app loads all the thumbnails correctly

**Comment by yaichenbaum** [comment]
@alberto-diaz15 Thank you for opening this issue, this issue should be resolved with #2637.
