### ISSUE TITLE
AutomationProperties not set in vertical tab strip

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#2624]

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran Can you please add more details such as which controls in the tab strip are missing AutomationProperties?

**Comment by jaigak** [comment]
@yair100 The add tab button has no automation properties set and since it has an icon, XAML doesn't set it automatically. Also list view items there don't report the tab names by overriding ToString()

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran Would you like to work on this issue?

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
