### ISSUE TITLE
Turkish Translation error

### ISSUE THREAD

**Issue by KeremArdicli** [files-community/Files#2625]
**Describe the bug**
Translation of "Drives" for Turkish is stated as "Sürüşler" whereas it is originally translated as "Sürücüler" in regular File Explorer. And "Sürücüler" is the correct one.

Settings is also translated as " Özellikler " which means "features". When I click on the button, "Ayarlar (Settings)" page is opened. I think this also should be corrected.

**To Reproduce**
1. Open tha app.
2. Look at the left pane.
3. See errors.

**Expected behavior**
A proper translation is needed. Actually origianl app has a very concise and professional translation.

**Screenshots**
![bug report 1](https://user-images.githubusercontent.com/72523365/102486268-d5602300-4079-11eb-965a-fbd40aec7ddb.JPG)
![bug report 2](https://user-images.githubusercontent.com/72523365/102486266-d42ef600-4079-11eb-88e9-ac1c1b1ba8eb.JPG)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app? YES. ISSUE consists.

**Log file**
Please post the log file here so that we can understand your problem better. You can access it from Settings->About->Open log location.

**Comment by yaichenbaum** [comment]
@KeremArdicli Would you like to fix this issue?

**Comment by KeremArdicli** [comment]
Sure. I can accord the translations with the current file explorer. I have realized couple of more translation errors.

How should we proceed?

**Comment by yaichenbaum** [comment]
@KeremArdicli You can find a guide with information about translationing Files in the [Wiki](https://github.com/files-community/Files/wiki/Translating-Files-into-your-language).

**Comment by KeremArdicli** [comment]
I would be happy to help. However, it is not easy to follow the
instructions.

I have downloaded all required apps. Yet your introductions are not noob
friendly :)
I could not open Files UWP in Visual Studio I could not even locae Files
UWP folder in the system.

Is there a visual guide to help likes of me?




Yair Aichenbaum <notifications@github.com>, 3 Oca 2021 Paz, 23:10 tarihinde
şunu yazdı:
