### ISSUE TITLE
Pin folders by dropping them on left pane

### ISSUE THREAD

**Issue by KeremArdicli** [files-community/Files#2626]
**Is your feature request related to a problem? Please describe.**
I'm frustrated to see that I cannot pin any folder to left pane. When i tried to do so, my folder is copied under a folder present on the pane.

**Describe the solution you'd like**
Users should be able to pin folders under a Quick Access tab.

**Describe alternatives you've considered**
Existing File Explorer solution is just fine.

**Additional context**
![feature request](https://user-images.githubusercontent.com/72523365/102486910-cded4980-407a-11eb-9772-d1a48fa659af.jpg)

**Comment by mrr07** [comment]
There is a option in context menu

![image](https://user-images.githubusercontent.com/69007625/102492122-7d252300-4071-11eb-80f2-cc369853d04d.png)

**Comment by KeremArdicli** [comment]
Drag and drop should be an option. Dont you think so?

**Comment by KeremArdicli** [comment]
BTW, thnx for the info. I have dropped using it just bcs of this so-called-missing feature.

**Comment by Cyberdroid1** [comment]
Dragging and dropping is a lot more Intuitive than having to right click.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #6129.
