### ISSUE TITLE
Enable "one click-and-hold to drag" feature

### ISSUE THREAD

**Issue by KeremArdicli** [files-community/Files#2627]
**Is your feature request related to a problem? Please describe.**
When i want to move a folder, simple one "click and hold to drag" is not working. You need to select the folder first and that should click again and drag it.

**Describe the solution you'd like**
Clicking and holding on a folder/file should be enough. Users should not need to select file/folder first and thgen click again to move/copy it.

**Describe alternatives you've considered**
The way it works on current File Explorer is just fine.

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by Dylan-Osborne** [comment]
Possible duplicate of #673

**Comment by KeremArdicli** [comment]
Yeah exactly.

Dylan Osborne <notifications@github.com>, 17 Ara 2020 Per, 16:15 tarihinde
şunu yazdı:
