### ISSUE TITLE
Request: Change the font and size or the height of each file in settings

### ISSUE THREAD

**Issue by Sim233** [files-community/Files#2639]
**Is your feature request related to a problem? Please describe.**
It seems that I cannot change the font and size in settings now. Personally, I think the font size is okay for viewing, but only a small number of files (about 18) can be displayed on one page, which makes it a bit hard to use when there's a lot of files under the path.

**Describe the solution you'd like**
Give a select box to select the font and size in setting. Or give a select box to select the height of each file/folder.

**Describe alternatives you've considered**
The buttons (Back, Forward, Up, Refresh, Search, More options) can be put upwards, together with the path (to save some space in the layout).

**Additional context**
None.

**Comment by gave92** [comment]
Merging with #1943
