### ISSUE TITLE
Request: Pull the pinned shortcuts in the sidebar to rearrange the sequence

### ISSUE THREAD

**Issue by Sim233** [files-community/Files#2641]
**Is your feature request related to a problem? Please describe.**
I added several paths to be pinned to sidebar, but it's ordering by the pinned time, and I cannot change the sequence by pulling the items.

**Describe the solution you'd like**
Pull the items to rearrange the sequence, like the win10 build-in file explorer.

**Describe alternatives you've considered**
Right click on the items pinned to sidebar, select up or down in the right-click menu. (Sorry, I don't know the term in English...)

**Additional context**
None. By the way, thanks for your application! It's wonderful!

**Comment by gave92** [comment]
Merging with #1069
