### ISSUE TITLE
Sidebar's device FullPath is shown after hovering on it

### ISSUE THREAD

**Issue by d2dyno1** [files-community/Files#2643]
**Describe the bug**
A device's path is shown after hovering on a device (phone).

**Expected behavior**
Show only device name in this particular case.

**Screenshots**
![image](https://user-images.githubusercontent.com/53011783/102699260-bdd49600-4243-11eb-887b-17e04a4edc91.png)

**Comment by yaichenbaum** [comment]
@d2dyno1 Would you like to work on this issue?

**Comment by d2dyno1** [comment]
I'll try after bundles are ready
