### ISSUE TITLE
Add an option to have a simple right click context menu

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#2656]
**Is your feature request related to a problem? Please describe.**
Today there's an option to show some items in a more flyout to declutter the menu, but I want an option to completely get rid of them within Files.

**Describe the solution you'd like**
A simple toggle to hide all custom context menu items.

**Describe alternatives you've considered**
None.

**Comment by gave92** [comment]
@Jaiganeshkumaran is your request to be able to hide them all in a submenu, or the ability to turn the feature completely off (and gain a faster context menu opening)?

**Comment by Jaiganeshkumaran** [comment]
@gave92 An option to completely turn off the feature and only have required options shown

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran We don't plan to implement this specific change, but we are looking at using the CommandBarFlyout control which will significantly decrease the size of the context menu.
