### ISSUE TITLE
Icons/Thumbnails become blurry when switching from Details View

### ISSUE THREAD

**Issue by generalguy41** [files-community/Files#2660]
**Describe the bug**
Any icons become blurry when switching from Details view to Grid or Tiles view.

**To Reproduce**
1. Go to a directory with icons/thumbnails that are clear in Grid view.
2. Switch to Details view.
3. Switch back to Grid or Tiles view.
4. See issue.

**Expected behavior**
Icons/Thumbnails should remain clear when switching views.

**Screenshots**

https://user-images.githubusercontent.com/8879244/102845288-3a4dad00-43db-11eb-8485-66893ebf6851.mp4

**Desktop (please complete the following information):**
 - OS Version: Windows 10 2004 20279.1
 - App version: 0.23.0.0

**Additional context**
Icons are clear after restarting the app, but issue is reproduceable.

**Log file**
No issues in log file.

**Comment by yaichenbaum** [comment]
@generalguy41 This issue should be resolved with #2669.

**Comment by candrapersada** [comment]
How to automatically switch from Details view to Grid or Tiles view for Thumbnails view and switching from Grid or Tiles view to Details view for folders?
