### ISSUE TITLE
Selecting 'Open in new tab' on the Sidebar Recycle Bin opens a new tab instead

### ISSUE THREAD

**Issue by Teraskull** [files-community/Files#2661]
**Describe the bug**
Selecting 'Open in new tab' or 'Open in new window' on the Sidebar Recycle Bin opens a new tab instead.

**To Reproduce**
1. Right click "Recycle Bin" on the sidebar.
2. Click on 'Open in new tab' or 'Open in new window'.
3. A new tab/window is opened instead of the Recycle Bin.

**Expected behavior**
The Recycle Bin tab/window should be opened.

**Screenshots**
Issue is self-explanatory.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 2004 21277.1000
 - App version: v0.23.0.0

**Additional context**
This issue does not occur with any other items pinned to the sidebar.

**Log file**
Nothing is logged when reproducing the issue.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #2703.
