### ISSUE TITLE
update inside MS Store not working for ver 0.23

### ISSUE THREAD

**Issue by whdmike** [files-community/Files#2664]
**Describe the bug**
A clear and concise description of what the bug is and why it is more urgent than other issue reports. Can't answer this? Please return to the previous page and file a regular bug/feature report.

**To Reproduce**
1. Go to  MS Store'
2. Click on UPDATE 
3. Doesn't work (for me)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Additional context**
Add any other context about the problem here. For instance, are you building from source or using a precompiled build/snapshot?

**Log file**
Please post the log file here so that we can understand your problem better. You can access it from Settings->About->Open log location.

**Comment by yaichenbaum** [comment]
@whdmike Files is rolled out in stages so it might be a couple days before it's available for your device.
