### ISSUE TITLE
Microsoft Defender menu item is missing it's icon

### ISSUE THREAD

**Issue by Gaoyifei1011** [files-community/Files#2665]
Right-click menu of "using Windows Defender scanning" this option of Windows Defender blue icon does not show, hope to add as soon as possible
右键菜单关于"使用 Windows Defender 扫描"的这一选项的Windows Defender 蓝色图标不会显示，希望尽快添加
![image](https://user-images.githubusercontent.com/49179966/102902497-09887900-44aa-11eb-848d-5764f05e2b85.png)

**Comment by yaichenbaum** [comment]
@Gaoyifei1011 Can you provide some more details? It looks like Microsoft Defender is the second option in your screenshot.

**Comment by Gaoyifei1011** [comment]
Above the right-click menu of the Windows default Microsoft Defender blue icon and tinder the yellow icon of security software is shown, but the Files UWP icon does not show the above Microsoft Defender blue, yellow tinder security software icon will display normally, hope to be able to fix the problem
![image](https://user-images.githubusercontent.com/49179966/103459067-6eb05a00-4d47-11eb-9443-3edd25b6374d.png)
![image](https://user-images.githubusercontent.com/49179966/103459083-81c32a00-4d47-11eb-9970-4cc7f279baf7.png)

**Comment by gave92** [comment]
Merging with #3834
