### ISSUE TITLE
It would be nice to be able to customize the icon for one I want.

### ISSUE THREAD

**Issue by guiramsor** [files-community/Files#2668]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by guiramsor** [comment]
It would be nice to be able to customize the icon for one I want.

**Comment by yaichenbaum** [comment]
@guiramsor We usually expect users to fill out the issue template when reporting a bug or submitting a feature request, please reopen this issue when you have filled out the issue template.
