### ISSUE TITLE
Lag in more than 10 seconds between pressing delete button and appearing dialogue window

### ISSUE THREAD

**Issue by Tester09** [files-community/Files#2672]
**Describe the bug**
When I'm trying to delete any files in Files app dialogue window appears to confirm the deletion (which in itself is not good, Explorer allows you to turn off confirmation for moving to recycle bin) but the biggest problem is that it appears with a terrible lag of more than 10 seconds.

**To Reproduce**
1. Go to any directory
2. Select any file or folder
3. Press Del button on the keyboard or choose  Delete from context menu
4. Wait

**Expected behavior**
There should be no delay 

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 2004 20279 fe]
 - App version: [v0.23.1]

**Log file**
Please post the log file here so that we can understand your problem better. You can access it from Settings->About->Open log location.

**Comment by gave92** [comment]
Related to having many files in the recycle bin -> see #2738
