### ISSUE TITLE
After the latest update as of this issue, app opens then crashes mere seconds later.

### ISSUE THREAD

**Issue by WinstonSepruko** [files-community/Files#2674]
**Describe the bug**
The app crashes 1-2 after opening, it remains unresponsive during the time it takes to crash.

**To Reproduce**
1. Open "Files - Preview"
2. Wait 1-2 seconds as it remains unresponsive.
3. See as it crashes.

**Expected behavior**
The app opens, responds to inputs and does not crash.

**Screenshots**
N/A

**Desktop:**
 - OS: Windows 10 1909 18363.1256
 - App version: v0.23.0

**Additional context**
Downloaded and installed using the Microsoft Store.

**Log file**
[debug.txt](https://pastebin.com/StAGydkk)

[debug_fulltrust.txt](https://pastebin.com/ataCApRq)

**Comment by yaichenbaum** [comment]
@WinstonSepruko you can acess the log file by following this [guide](https://github.com/files-community/Files/wiki/Opening-the-log-file).

**Comment by WinstonSepruko** [comment]
[debug.txt](https://pastebin.com/StAGydkk)

[debug_fulltrust.txt](https://pastebin.com/ataCApRq)

**Comment by gave92** [comment]
This should be fixed in 0.23.1
