### ISSUE TITLE
Keep settings - column width and view

### ISSUE THREAD

**Issue by whdmike** [files-community/Files#2675]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I would like that app keeps last state of column width after is restarted. Default column is many times too narrow and i don't like to adjust it every time I start Files. Option are just to keep last column width or to make an option inside of settings to save current state.

In the same way, I like to have each time I start app the same view settings. For me would be detail view. I might use grid view, but when I start next time Files, I really don't like that again I need to put on a details view. 

The best way is to adjust the settings (start folder, column width, view) and save it inside settings - save settings or keep current position (view) .

**Describe alternatives you've considered**
Option are just to keep last column width or to make an option inside of settings to save current state. 

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by gave92** [comment]
This should probably be build upon #2667

**Comment by whdmike** [comment]
I think #2667 <https://github.com/files-community/Files/pull/2667> is 
way too complicated. I can't imageine who would really benefit from that 
beside some hard core programmer. Keep things simple and normal user 
friendly, please.

**Comment by gave92** [comment]
@whdmikeit will be an option,  we are planning to allow the user to decide whether to save view settings per folder or globally

**Comment by aljazd** [comment]
I think app should respect windows view settings per folder.

**Comment by gave92** [comment]
This is implemented with the new details view.

**Comment by yaichenbaum** [comment]
@gave92 It is posible to exlude the icon column from being saved?
