### ISSUE TITLE
Error on used storage with OneDrive

### ISSUE THREAD

**Issue by alberto-diaz15** [files-community/Files#2678]
If you don´t have any account linked to OneDrive and you select the "Properties" option, it will show you the properties of your internal storage. 
Image attached:
![image](https://user-images.githubusercontent.com/72040488/103019156-aa2c7680-4546-11eb-96ac-8455021f0de1.png)

Also I would like to ask you if you could add an option to disable or hide the "OneDrive" folder/storage, as many users won't use it.

**Comment by yaichenbaum** [comment]
@alberto-diaz15 You can remove the OneDrive option by deleting the environmental variable in Windows.

**Comment by alberto-diaz15** [comment]
> @alberto-diaz15 You can remove the OneDrive option by deleting the environmental variable in Windows.

Thank you
