### ISSUE TITLE
Files Aplication crashes when you open the aplication

### ISSUE THREAD

**Issue by andro095** [files-community/Files#2680]
**Describe the bug**
When I'm opening Files - Preview (Windows Store Version), automaticaly the aplication crashes and closes without start.

**To Reproduce**
1. Click in Aplication Icon to open the app
2. Wait

**Expected behavior**
The aplication opens and loads the information

**Screenshots**

https://user-images.githubusercontent.com/35317562/103044405-f6c38200-4545-11eb-8875-e607635fd00c.mp4

**Desktop (please complete the following information):**
 - OS: [Windows 10 20H2 19042.685]
 - App version: [v0.23.0]

**Log file**
Please post the log file here so that we can understand your problem better. You can access it from Settings->About->Open log location.

**Comment by gave92** [comment]
Thanks for this report, please add the debug files to the issue description.
You can find the log files following [this guide](https://github.com/files-community/Files/wiki/Opening-the-log-file)

**Comment by yaichenbaum** [comment]
@andro095 This issue should be fixed with #2688.
