### ISSUE TITLE
Files process crashes when opening the context menu

### ISSUE THREAD

**Issue by InfiniteSynthesis** [files-community/Files#2683]
Please support more software right-click options, e.g., winrar, onedrive, local emulator.

**Comment by yaichenbaum** [comment]
@InfiniteSynthesis Those options should already be there, can you help us with some information by uploading the log files and sharing the app version number?

**Comment by InfiniteSynthesis** [comment]
@yair100 I'm using v0.23.0.0, seems the latest. The right-click menu does not show any additional options. Errors occur when I right-click files.

See:

> 2020-12-23 23:33:32.8439|INFO|FilesFullTrust.Program|Argument: LoadContextMenu|
> 2020-12-23 23:33:32.9846|ERROR|FilesFullTrust.Program|A generic error occurred in GDI+.|System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
>    at System.Drawing.Image.FromHbitmap(IntPtr hbitmap, IntPtr hpalette)
>    at System.Drawing.Image.FromHbitmap(IntPtr hbitmap)
>    at Vanara.PInvoke.GdiObjExtensions.ToBitmap(HBITMAP& hbmp)
>    at FilesFullTrust.Win32API.GetBitmapFromHBitmap(HBITMAP hBitmap)
>    at FilesFullTrust.Win32API.ContextMenu.EnumMenuItems(IContextMenu cMenu, HMENU hMenu, List`1 menuItemsResult, Func`2 itemFilter)
>    at FilesFullTrust.Win32API.ContextMenu.GetContextMenuForFiles(ShellItem[] shellItems, CMF flags, Func`2 itemFilter)
>    at FilesFullTrust.Win32API.ContextMenu.GetContextMenuForFiles(String[] filePathList, CMF flags, Func`2 itemFilter)
>    at FilesFullTrust.Program.HandleMenuMessage(ValueSet message, DisposableDictionary table)
>    at FilesFullTrust.Win32API.ThreadWithMessageQueue`1.<>c__DisplayClass6_0.<.ctor>b__0()
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart()
> 

I also upload the full log, hope it can help you.
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5738266/debug_fulltrust.txt)

**Comment by yaichenbaum** [comment]
@InfiniteSynthesis Thank you, this may be fixed with v0.23.1 but I will keep this issue open until then so that we can confirm.

**Comment by gave92** [comment]
@InfiniteSynthesis could you share a screenshot of the right click menu that appears in Windows Explorer when you click one of the files that crash Files Fulltrust process?
Does the same error also happens if you click on a folder (restart the app before checking)?

**Comment by InfiniteSynthesis** [comment]
@gave92 The folder menu works well at the first time when I open the app. However, after I right-click some files, the folder menu no longer shows those options (and no crash log for this).

Here's the screenshot when I right-click exe file in File Explorer:

![image](https://user-images.githubusercontent.com/20440018/103101956-7baeaa00-45df-11eb-8c6c-cd5babcd0390.png)

Here's the menu of the same exe in Files (no winrar, one drive, local emulator options):

![image](https://user-images.githubusercontent.com/20440018/103101982-a3057700-45df-11eb-98e1-827f9e6db1c7.png)

**Comment by yaichenbaum** [comment]
@InfiniteSynthesis This issue should be resolved with #2702.
