### ISSUE TITLE
"Open in terminal" doesn't work

### ISSUE THREAD

**Issue by linsui** [files-community/Files#2684]
**Describe the bug**
The "Open in terminal" doesn't work. There are powershell, CMD and Windows Terminal but none of them works. I can click it but nothing happens.

**To Reproduce**
1. Go to a directory
2. Click on Open in Terminal
3. Nothing happens

**Expected behavior**
A terminal is opened

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2 19042.685]
 - App version: [v0.23.1.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
```
2020-12-24 16:44:05.7916|INFO|.ctor|App launched|
2020-12-24 16:44:06.3466|INFO|.ctor|Drive added: C:\, Fixed|
2020-12-24 16:44:06.4186|INFO|.ctor|Drive added: D:\, Fixed|
2020-12-24 16:44:06.4656|INFO|.ctor|Drive added: E:\, Fixed|
```

This is the only log. Looks like there is nothing useful.

**Comment by yaichenbaum** [comment]
@linsui Can you share your terminal profile here?

**Comment by linsui** [comment]
```json
{
  "version": 1,
  "defaultTerminalPath": "wt.exe",
  "terminals": [
    {
      "name": "CMD",
      "path": "cmd.exe",
      "arguments": "",
      "icon": ""
    },
    {
      "name": "PowerShell",
      "path": "powershell.exe",
      "arguments": "-noexit -command \"cd '{0}'\"",
      "icon": ""
    },
    {
      "name": "PowerShell Core 6",
      "path": "pwsh.exe",
      "arguments": "-WorkingDirectory \"{0}\"",
      "icon": ""
    },
    {
      "name": "Windows Terminal",
      "path": "wt.exe",
      "arguments": "-d .",
      "icon": ""
    }
  ]
}
```

**Comment by yaichenbaum** [comment]
@linsui Can you see if removing the command prompt profile fixes the issue?

**Comment by linsui** [comment]
It works now though I didn't touch any profiles. IIRC, I notice that there were only some bulit-in options in the context menu but now there are much more options such as power rename. Maybe it start working after a Windows restart. I'll close this issue as I can't reproduce it any more. If this issue happens again I'll reopen it. Thanks!
