### ISSUE TITLE
The sidebar shows that there are two drive D, in fact there is only one

### ISSUE THREAD

**Issue by QiuYukang** [files-community/Files#2686]
**Describe the bug**
The sidebar shows that there are two drive D, in fact there is only one！

**To Reproduce**
This phenomenon occurs when I open the software for the first time after turning on the computer. After closing the software and opening it again, the display is normal, the position of the second `Data D:` will become `OneDrive`.

**Expected behavior**

**Screenshots**
![files-preview-bug](https://user-images.githubusercontent.com/39994066/103077228-5d11d880-460a-11eb-8349-a10dde62df2b.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10  20H2
 - App version: [v0.23.1.0]

**Additional context**

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5738950/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5738952/debug_fulltrust.txt)

**Comment by gave92** [comment]
This issue has been fixed.
