### ISSUE TITLE
Addition of code linter, unit testing

### ISSUE THREAD

**Issue by jeffsieu** [files-community/Files#269]
I was wondering if the addition of [unit testing](https://docs.microsoft.com/en-us/visualstudio/test/walkthrough-creating-and-running-unit-tests-for-windows-store-apps?view=vs-2019), and code linters like [FxCop Analyzers](https://docs.microsoft.com/en-us/visualstudio/code-quality/install-fxcop-analyzers?view=vs-2019) would be added to the project. I think it'll be a good idea to automate some (if not all) of the testing in the app.

Also, code linting will help to ensure that code from various contributors will have styles consistent with one another.

**Comment by yaichenbaum** [comment]
Absolutely, I am in agreement with this. If Luke agrees we can get this set up.

**Comment by yaichenbaum** [comment]
@jeffsieu Is this something you have experience with? Neither Luke or I have done this before but would be interested in doing this to improve the quality of Files code base.

**Comment by jeffsieu** [comment]
@yaichenbaum Nope, haha. I've never tried this before too. Maybe we can start small by adding an automated test to verify code formatting first, once that is up and running then we can start adding the actual unit and integration tests within the app.

**Comment by yaichenbaum** [comment]
This is something we're continuing to work towards but I think we can close this issue for now.
