### ISSUE TITLE
Option to hide filenames

### ISSUE THREAD

**Issue by Rasmagoric** [files-community/Files#2692]
**Is your feature request related to a problem? Please describe.**
One of the features i missed from windows 7 explorer (it was removed in w10) was the ability to hide filenames. 
This was an option on designated picture type folders, you had the option to right click anywhere and toggle the option to view or hide filenames. This was great for viewing folders with hundreds of pictures.

**Describe the solution you'd like**
It would be great if this option was remembered per folder where it was toggled instead of a global option. 

**Additional context**
I did a quick image edit just to see what it would look like: 
![Untitled-1](https://user-images.githubusercontent.com/24687648/103103731-11b3f600-461b-11eb-9e63-f49f85c39010.jpg)

**Comment by yaichenbaum** [comment]
@Rasmagoric what do you think about merging this with #5058?

**Comment by Rasmagoric** [comment]
I'd prefer this to be an individual feature (for the icons layout mode) independent of another mode. 
But whatever it also would be cool for it's own layout mode.
Your call if you want to merge it.

**Comment by yaichenbaum** [comment]
=

**Comment by yaichenbaum** [comment]
@Rasmagoric do you have a use case where you'd want to hide file names for regular files?
