### ISSUE TITLE
New file option not working

### ISSUE THREAD

**Issue by payambordbar** [files-community/Files#2695]
**Describe the bug**
Nothing happens after selecting the new file option

**Screenshots**
![Screenshot 2020-12-25 031602](https://user-images.githubusercontent.com/45229646/103111226-e43d6b80-465f-11eb-93fd-a901154c5095.png)

 - App version: [v0.23.1.0]

**Comment by yaichenbaum** [comment]
@payambordbar This issue should be resolved with #2702.
