### ISSUE TITLE
DragDrop Default action - Give the user a choice

### ISSUE THREAD

**Issue by infuriatedcodex** [files-community/Files#2710]
**Is your feature request related to a problem? Please describe.**
Partially related to a "problem".
The default action (in the native explorer) when dragging files/folders to another location is to MOVE the file if it is the same logical drive or COPY if dragging to a different logical drive.

In this app, the only action it performs is a MOVE, which may Not be the users intention.

**Describe the solution you'd like**
Either - change the behaviour to function like the native explorer DragDrop.
OR
Provide a setting to allow the user to choose the behaviour.

**Describe alternatives you've considered**
N/A

**Additional context**
Test this with 2 fixed logical drives on your system to see what I am describing.

**Comment by gave92** [comment]
Thanks for this suggestion!

As an alternative / in addition we should also support overwriting the default action when the user presses shift or control key:
- Ctrl+Drag will copy the file
- Shift+Drag will move the file (in situations where copy is the default)
- Alt+Drag will create a shortcut to the file in the new location

**Comment by XPoppyX** [comment]
It should show the move or copy options if you drag and drop with the right click, like in native file explorer

![Right-Click-Held-Options](https://user-images.githubusercontent.com/61259627/103153987-71251980-4773-11eb-82c9-0905bb251ddf.png)

**Comment by yaichenbaum** [comment]
Merging with #1396.
