### ISSUE TITLE
Remember folder layout view perfs - Detailed, Grid View etc.

### ISSUE THREAD

**Issue by infuriatedcodex** [files-community/Files#2711]
Currently users are limited to a single Layout view for every folder in the system, regardless of the folder type.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Would be great if the app remembered the Layout you choose for any given folder.
Example, I set Detailed View for Documents but set Grid View (Small) on Pictures with native style Thumbnails.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by gave92** [comment]
This has been implemented -> #530/#2667 and will ship in the next public version 👍

**Comment by infuriatedcodex** [comment]
Beautiful !
