### ISSUE TITLE
Closing folder properties window just after folder size has been calculated causes crash

### ISSUE THREAD

**Issue by winston-de** [files-community/Files#2714]
**Describe the bug**
Closing folder properties window just after folder size has finished calculating causes a crash.

**To Reproduce**
1. Open folder properties
2. Just after the folder size has finished calculating (or when the loading icon disappears), close the window
3. See error

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: 21277.1000
 - App version: v0.23.1.0

**Additional context**

**Error**
```
(4be4.1b8c): Unknown exception - code 80010012 (first chance)
(4be4.1b8c): Unknown exception - code 80010012 (first chance)
(4be4.1b8c): Unknown exception - code 80010012 (first chance)
(4be4.26f0): Windows Runtime Originate Error - code 40080201 (first chance)
(4be4.26f0): C++ EH exception - code e06d7363 (first chance)
(4be4.26f0): Security check failure or stack buffer overrun - code c0000409 (!!! second chance !!!)
Subcode: 0x7 FAST_FAIL_FATAL_APP_EXIT 
ucrtbase!abort+0x4e:
00007ffa`983ecafe cd29            int     29h
```

Edit: replaced incorrect error information

**Comment by gave92** [comment]
@winston-de thanks for this feedback item. Does this happen regularly or does it seem random? Is the above the full stacktrace (i looks clipped)?

**Comment by winston-de** [comment]
@gave92 It's consistent, though you have to close the window right when the folder size has finished calculating, so unless you're looking for it it's decently uncommon.
Also, you're right, it looks like I didn't quite copy the full stack trace. I just updated it.

**Comment by gave92** [comment]
Thanks the above screenshot looks related to the Delete keyboard key being pressed, so maybe unrelated.
Could you try to delete the `debug.txt` file and than trigger the bug again?

**Comment by winston-de** [comment]
@gave92 I think the error I posted may be completely unrelated. I deleted the log file like you asked, then reproduced the bug, and no errors were reported. All there is is the loading info.
```
2020-12-26 11:55:07.9309|INFO|.ctor|App launched|
2020-12-26 11:55:09.5638|INFO|.ctor|Drive added: C:\, Fixed|
2020-12-26 11:55:09.8698|INFO|.ctor|Drive added: D:\, Removable|
2020-12-26 11:57:18.4276|INFO|.ctor|App launched|
2020-12-26 11:57:19.9498|INFO|.ctor|Drive added: C:\, Fixed|
2020-12-26 11:57:20.3916|INFO|.ctor|Drive added: D:\, Removable|
```
Gimme a minute, I'll try doing it with a debugger attached.

**Comment by gave92** [comment]
I knew it, the same happens for me :)

**Comment by winston-de** [comment]
> I knew it, the same happens for me :)

@gave92 Good catch lol.

I'm getting the same error code from the debugger as you, but a different message.
```
(4be4.1b8c): Unknown exception - code 80010012 (first chance)
(4be4.1b8c): Unknown exception - code 80010012 (first chance)
(4be4.1b8c): Unknown exception - code 80010012 (first chance)
(4be4.26f0): Windows Runtime Originate Error - code 40080201 (first chance)
(4be4.26f0): C++ EH exception - code e06d7363 (first chance)
(4be4.26f0): Security check failure or stack buffer overrun - code c0000409 (!!! second chance !!!)
Subcode: 0x7 FAST_FAIL_FATAL_APP_EXIT 
ucrtbase!abort+0x4e:
00007ffa`983ecafe cd29            int     29h
```
