### ISSUE TITLE
Proposal: move classes to the proper namespace

### ISSUE THREAD

**Issue by gave92** [files-community/Files#2715]
**Is your feature request related to a problem? Please describe.**
The following classes (among others) are defined in an "improper" namespace
| Class | Current Namespace | Suggested Namespace | Notes |
| :----------: | :----------: | :----------: |:----------: |
| ModernShellPage | Files.Views.Pages | Files.Views | All other pages are in Files.Views |
| CloudProviders | Files.Filesystem | Files.Enums | With the other enums |
| StringExtensions | Files.Helpers | Files.Extensions | With the other extensions |
| Win32FindDataExtensions | Files.Helpers | Files.Extensions | With the other extensions |
| SidebarControl | Files.Controls | Files.UserControls | All other usercontrols are in Files.UserControls |
| DriveWidget | Files | Files.UserControls.Widgets | With the other usercontrols |
| LibraryCards | Files | Files.UserControls.Widgets | With the other usercontrols |
| RecentFiles | Files | Files.UserControls.Widgets | With the other usercontrols |
| InteractionViewModel | Files.Controls | Files.View_Models | With the other viewmodels |
| GenericFileBrowser | Files | Files.UserControls.LayoutModes | With the other usercontrols |
| GridViewBrowser | Files | Files.UserControls.LayoutModes | With the other usercontrols |
| YourHome | Files | Files.Views | With the other pages |

**Describe the solution you'd like**
Move the classes to the correct namespace

If you agree, I can make a PR with this 👍

**Comment by d2dyno1** [comment]
Class | Current Namespace | Suggested Namespace | Notes
-- | -- | -- | --
InteractionViewModel | Files.Controls | Files.View_Models | With the other viewmodels

`Files.View_Models` - without the `_` here

**Comment by gave92** [comment]
@d2dyno1 agreed, `View_Models` is the currently used name, but we may as well change it here.

**Comment by yaichenbaum** [comment]
@gave92 We can also take this opportunity to rename the `View Models` folder to `ViewModels`.
