### ISSUE TITLE
Feature request: Add a recent items page

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#2718]
**Is your feature request related to a problem? Please describe.**
I often want a way to view a list of recently opened directories and files. While there is an optional widget that can be pinned to the home page, that is limited to displaying files, and it has some other limitations as well.

**Describe the solution you'd like**
A proper recent items page that will display files and folders with the same flexibility as any other directory would be ideal. This includes the options to search, change the layout mode, sort items etc. The user should also have the option to pin this page to the sidebar as prototyped in #692.

| Capability | Priority |
|-|-|
| Have an option to pin/unpin the recent items page to the sidebar by right clicking on the recent items page | Must |
| The recent items page should be the second pinned item on the sidebar by default | Must |
| User can navigate to the page by typing "recents" in the path bar | Must |
| Supports searching recent items | Must |
| Adds "Open item location" in right click context menu for files | Must |
| Adds "Remove from recent items" in right click context menu for files and folders | Must |
| Adds "Clear recent items" in right click context menu when clicking in a blank space | Must |
| Supports changing the layout mode | Should |
| Supports sorting items | Should |
| Can be set as a startup page | Should |

**Describe alternatives you've considered**
An alternative would be to show recent directories on the sidebar, but that would come without the flexibility mentioned above and would also crowd the sidebar.

**Comment by Jaiganeshkumaran** [comment]
This is unnecessary since the MRU list only holds 25 items at a time and can fit in the home page

**Comment by Josh-65** [comment]
Is this still relevant with the way Files is going?

**Comment by sthivaios** [comment]
What are you talking about? It is right here 

-->

![image](https://user-images.githubusercontent.com/109022579/195330859-d3b7a5e1-63f1-4c09-a5dc-904b7c3c0009.png)

**Comment by Josh-65** [comment]
There's are thing that aren't implemented from the priorities list. This also takes about having the recent as a full page rather than just a widget

**Comment by sthivaios** [comment]
> What are you talking about? It is right here...
> 
> ![image](https://user-images.githubusercontent.com/109022579/195330859-d3b7a5e1-63f1-4c09-a5dc-904b7c3c0009.png)

Yep, I just read the issue further and realized what they are actually talking about and the little table.

**Comment by yaichenbaum** [comment]
One of the benefits of a dedicated page over the existing widget is that it would allow for advanced searches, grouping/sorting and different layout modes.
