### ISSUE TITLE
When changing from a tab page to a new window, it will return to the home page instead of the original page.

### ISSUE THREAD

**Issue by XUANJI233** [files-community/Files#2721]
**Describe the bug**
When changing from a tab page to a new window, it will return to the home page instead of the original page.

**To Reproduce and Screenshots**
![1](https://user-images.githubusercontent.com/56026539/103173030-fbb06a80-4892-11eb-9c1d-5822724826b6.png)
![2](https://user-images.githubusercontent.com/56026539/103173034-ff43f180-4892-11eb-889d-58e2af56ff9c.png)

**Desktop (please complete the following information):**

OS Version: 20H2 Pro
App version: 0.23.1.0

**Comment by yaichenbaum** [comment]
@XUANJI233 This issue should be resolved in `main`.
