### ISSUE TITLE
Some side effects after replacing file Explorer with a file

### ISSUE THREAD

**Issue by XUANJI233** [files-community/Files#2723]
**Describe the bug**
Some side effects after replacing file Explorer with a file

**To Reproduce**
1.Trying to open recycle will Open the homepage.
2.In the Task Manager, trying to open location  file no response.
3.Right click on "this PC -> Properties",will Open the homepage.

**Desktop (please complete the following information):**
OS Version: 20H2 Pro
App version: 0.23.1.0
**I think it originated from the same problem, so I wrote it together**

**Comment by gave92** [comment]
Thanks for opening this feedback item. Please note that replacing file explorer with Files is not supported and known to have undesired side effects.

[Internal comment] we might want to add the above issues to the wiki description, so it's clear that there are additional issues wrt to the Control Panel not opening
