### ISSUE TITLE
Crashes when opening certain folders

### ISSUE THREAD

**Issue by fake3h** [files-community/Files#2724]
**Describe the bug**
Clicking on certain folders causes the app to crash and shows a notification. It first happened when I clicked on the Downloads folder, however after deleting some files in it, it opens like normal. Now it happens when I click on the Pictures and the Music folder. Maybe there's more.

**To Reproduce**
1. Open the app
2. Click on Pictures folder
3. App crashes and shows a notification

**Expected behavior**
Opens the folder I click on.

**Screenshots**
![1](https://user-images.githubusercontent.com/26138383/103173859-a0817680-4898-11eb-8079-cec10c1a568f.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Home 1909 18363.1256
 - App version: v0.23

**Additional context**
i am on arm64 device (surface pro x)

**Log file**
![Screenshot 2020-12-27 231729](https://user-images.githubusercontent.com/26138383/103174020-b6436b80-4899-11eb-88e4-44bcbecd55aa.png)

**Comment by gave92** [comment]
Thanks for opening this ticket. From AppCenter this looks a pretty common error and really needs fixing.
- Does the crash happen every time you open the Picture (or one of the other affected folders) folder?
- Does it make any difference if you sort the folders by name or by date or by something else?
[Btw it appears that the crash notification is *still* not working]

**Comment by yaichenbaum** [comment]
@gave92 It looks like it's coming from `502308486u`.

**Comment by gave92** [comment]
@yair100 and all the reports seem to be coming from Surface Pro X / windows on arm

**Comment by fake3h** [comment]
> @fake3h Thanks for opening this ticket. From AppCenter this looks a pretty common error which needs fixing.
> 
> * Does the crash happen every time you open the Picture folder (or one of the other affected folders) or does it look random?
> * Does it make any difference if you sort the folders by name or by date or by something else?
> 
> [Btw it appears that the crash notification is _still_ not working]

1. From what I've tested its not random. It crashes everytime.
2. No difference

**Comment by yaichenbaum** [comment]
@fake3h This issue should be fixed with #2886.
