### ISSUE TITLE
Feature: Image preview

### ISSUE THREAD

**Issue by rounk-ctrl** [files-community/Files#2725]
Could there be a image preview of image file instead of the photos app icon?

**Comment by rounk-ctrl** [comment]
The image preview weirdly works in the recent items.

**Comment by gave92** [comment]
@rounk-ctrl Please fill out the issue template to the best of your ability and re-open this. Thank you!

Anyway when in Grid view mode you should get a preview for image files but there was a bug recently fixed preventing that.
