### ISSUE TITLE
Image preview not working

### ISSUE THREAD

**Issue by rounk-ctrl** [files-community/Files#2726]
**Describe the bug**
Image preview wont work when switched from details view to other file view types. The problem fixes when restarted.

**To Reproduce**
1. Go to any folder that has images
2. Select Details view(if already not)
3. Then select any view type other than Details View
4. Images wont preview

**Expected behavior**
Images to preview

**Screenshots**
![image](https://user-images.githubusercontent.com/70931017/103175611-a53c2f80-4884-11eb-9f1e-0715d63b93c4.png)

**Desktop:**
 - OS Version: Windows 10 20h2 19042.685
 - App version: v0.23.1

**Comment by gave92** [comment]
Thanks @rounk-ctrl I can confirm this issue has been fixed in the internal development version and will ship with the next public release 👍

**Comment by rounk-ctrl** [comment]
Ok thank you :)
