### ISSUE TITLE
[Codebase] Fody.PropertyChanged

### ISSUE THREAD

**Issue by d2dyno1** [files-community/Files#2735]
**Is your feature request related to a problem? Please describe.**
Whenever we interact with the UI (via Properties) we always need to raise `OnPropertyChanged `.  This creates a lot of boilerplate code and it looks messy. It's also easy to forget about.

**Describe the solution you'd like**
There's a NuGet package called 'Fody.PropertyChanged' that injects the logic of `OnPropertyChanged` to any property. With it, simple `{ get; set; }` is enough to update the View. It works like magic.

**Notable Information**
The logic can be overridden by implementing property's `{ get; set; }`

**Describe alternatives you've considered**
(Discuss)

**Additional Context**
This NuGet extension has over 4.45M+ downloads.
Personally, I have used this extension multiple times in my projects and have not seen any performance drop to this day

**Comment by yaichenbaum** [comment]
@d2dyno1 Can you check what kind of impact this NuGet package will have on startup performance?

**Comment by d2dyno1** [comment]
Device specifications
---
Processor: Intel i5-8400 | 2.80GHz
RAM: 16GB
Grapics Card: GTX1070

Files without `Fody.PropertyChanged`
---
[Release][x64] (Newest commit) (Not started via Visual Studio)

\#1: 1.53
\#2: 1.45
\#3: 6.35
\#4: 5.56
\#5: 3.70

Average: ~3.72

Possible margin of error: 250ms

Files with `Fody.PropertyChanged`
---
[Release][x64] (Newest commit) (Not started via Visual Studio)

\#1: 1.64
\#2: 2.12
\#3: 2.56
\#4: 2.03
\#5: 1.38

Average: ~1.95

Possible margin of error: 250ms

Conclusion:
---
Startup times on both builds are very random.
It seems like though, adding `Fody.PropertyChanged` won't make any visible difference in startup the time.


Note:
\* `BaseLayout.NotifyPropertyChanged()` `private` modifier had to be changed to `protected`
<br/>
@yair100

**Comment by yaichenbaum** [comment]
@d2dyno1 I am not sure we want to implement this change, while the performance impact might be negligible on a more powerful device, adding another dependency is likely to have an impact on lower end devices. I think we should try to run more tests comparing the two to see how large of an impact it actually has.

**Comment by d2dyno1** [comment]
https://github.com/Fody/PropertyChanged

@yair100

**Comment by tsvietOK** [comment]
@d2dyno1 I don't think we are need all properties with injected PropertyChanged event.

**Comment by d2dyno1** [comment]
Hey @tsvietOK! You can specify properties that you don't want to have the injected code. Take a look here: https://github.com/Fody/PropertyChanged/wiki/Attributes

There's a attribute called `[DoNotNotify]`

**Comment by d2dyno1** [comment]
What's your opinion on this change? 

@tsvietOK @gave92 @duke7553

**Comment by tsvietOK** [comment]
Since we are not getting any other advantages except less code, i think we are don't need this package. WCT MVVM package doing almost the same thing and it is pretty comfortable to use it.

**Comment by lukeblevins** [comment]
@d2dyno1 I'm leaning towards a no vote on taking this dependency. Wouldn't it be better practice to have those defining a property make the explicit decision to raise PropertyChanged notifications rather than merely opting out of them?

@yair100 Besides that, I think any performance hit would be negligible unless there's something I haven't researched yet.

**Comment by yaichenbaum** [comment]
@d2dyno1 Thank you for the suggestion, it's not something we are looking at doing right now but we can reevaluate in the future if the need comes up.
