### ISSUE TITLE
Bug: Time Zone display error

### ISSUE THREAD

**Issue by Sim233** [files-community/Files#2737]
**Describe the bug**
I'm in UTC+08, but when I changed me files, Date Modified column shows the time in UTC, which is 8 hours earlier.

**To Reproduce**
1. Copy or move a file in the app.
2. The Date Modified column doesn't show the time in my time zone.

**Expected behavior**
Expect a correct display of time, which correspond to my windows system setting.

**Screenshots**
![image](https://user-images.githubusercontent.com/52943930/103189006-b24d3300-4905-11eb-8aca-2818caa5ff66.png)
But I changed these files in about 12:00 UTC+08, and my system setting is UTC+08.

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 1909 18363.1256]
 - App version: [v0.23.1.0]

**Comment by heistema** [comment]
I tried to reproduce the bug creating a simple text file. The bug only occurs in the folder view (It does not occur in Properties dialog for the specific file).

The bug occurs if and only if the setting for time zone is set to "System".

**Comment by Vixb1122** [comment]
same bug，and date format is "Application"
![image](https://user-images.githubusercontent.com/17810492/106476912-89125a80-64e2-11eb-81a5-846344e798ff.png)

**Comment by pklion** [comment]
Same here. (UTC+09, the date format is "System")
![image](https://user-images.githubusercontent.com/78145811/109880332-23201b00-7cba-11eb-95f2-c401473321d0.png)
I created this file now, but the timestamp isn't correct.

**Comment by yaichenbaum** [comment]
@Sim233 This issue should be resolved in `main`.
