### ISSUE TITLE
[Codebase] Overhaul for logging and debugging

### ISSUE THREAD

**Issue by d2dyno1** [files-community/Files#2740]
**Is your feature request related to a problem? Please describe.**
There's little to none information we can get from users from the debug files when trying to fix an issue. It always seemed like some issues are only occuring for some users and not for others.

**Describe the solution you'd like**
In code, put a Logging function to every { major/minor function, try-catch block, point of interest }. Then additionaly, add a button in settings, that opens (pseudo) console window (or something like that [Discussion]) that'd display all events that had occured within the App. (Obviously, the logging will be done in background) (Ultimately, if app crashes, export entire instance log to a file)

**Why this?**
Though, we already are logging exceptions, it's sometimes not enough to investigate an issue. Currently in `debug.txt` you can mainly see the information of loaded drives 💁‍♂️ ... and in `debug_fulltrust.txt` it's pretty similar situation.

**Describe alternatives you've considered**
(Discuss)

**Additional context**
There are a lot of issues we're not able to solve because we don't get enough information on them. By having more precise instance logging I believe majority of these issues will be easier to solve.

**Comment by yaichenbaum** [comment]
@d2dyno1 We get additional info in AppCenter and for the most part, @gave92 was able to solve many crashes from looking at the reports there.
