### ISSUE TITLE
Recommend appearance settings based off system spec

### ISSUE THREAD

**Issue by jebeld17** [files-community/Files#2741]
**Is your feature request related to a problem? Please describe.** 
     A: _**No**_

**Describe the solution you'd like**
     A: **_Recommend app appearance settings based off system hardware spec and inferred system performance._**

**Describe alternatives you've considered**
     A: **_Any alternative would be to not have the solution at all, to keep the current app as-is, or to educate the user that certain appearance settings may directly impact app performance and system performance while the app is open._**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by yaichenbaum** [comment]
@jebeld17 We are having a little trouble understanding this feature proposal, can you add a little more detail?

**Comment by yaichenbaum** [comment]
@jebeld17 The default settings in Files are what we recommend from a performance perspective. The only appearance setting that has an impact is the acrylic setting which is why it's turned off by default.
