### ISSUE TITLE
No icon shown when pinned to taskbar.

### ISSUE THREAD

**Issue by 321cheese123** [files-community/Files#2745]
**Describe the bug**
Bug is, Icon doesnt show when pinned to taskbar, Instead of showing the app icon, it shows nothing. 

**To Reproduce**
1. Pin to taskbar
2. Look at the icon.

**Expected behavior**
The Files icon would show in the taskbar.

**Screenshots**
![image](https://user-images.githubusercontent.com/70666613/103255559-81eab080-4968-11eb-9b2a-25db43d7c78a.png)

**Desktop:**
 - OS Version: Windows 10 2004, 20175.1000
 - App version: 0.23.1.0 

**Additional context**
Yes, problem still occurs after restarting the app. Nothing i tried fixed it.

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5749449/debug.txt)

**Comment by duke7553** [comment]
@321cheese123 It appears you're using a custom theme. Does the Files icon show on your taskbar with all modifications to the system taskbar theme disabled?

**Comment by 321cheese123** [comment]
> @321cheese123 It appears you're using a custom theme. Does the Files icon show on your taskbar with all modifications to the system taskbar theme disabled?

No.

**Comment by yaichenbaum** [comment]
@321cheese123 This might be a bug with Windows, can you report this issue on Feedback Hub?

**Comment by yaichenbaum** [comment]
Thanks again for your feedback.

_Since we didn't hear from you on this topic for 3+ days, we'll assume everything is worked out and close this feedback item. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this._

**Comment by Libroru** [comment]
3 years later and I am experiencing this issue with both of the Files versions.

Stable on the left, insider on the right.

![image](https://github.com/files-community/Files/assets/47794032/2d36a879-a9f1-4ba5-86fb-b55fb867c950)

**Comment by yaira2** [comment]
@Libroru this is a known issue with Windows 11, if you try unpinning the icon and pinning it again it usually fixes the issue.

**Comment by Libroru** [comment]
@yaira2 Already tried that but no luck so far... I'll look into that then if it's a windows issue. Thanks!

**Comment by yaira2** [comment]
That's odd, are you using a modified version of Windows?

**Comment by Libroru** [comment]
Nope, plain old Windows 11.

**Comment by Libroru** [comment]
Update: I found a fix for that.

For anyone reading this in the future:
I followed [this guide](https://beebom.com/fix-taskbar-icons-missing-windows-11/).
