### ISSUE TITLE
Integration with folder opening actions (e.g., AutoHotKey, search open folder, show file location, etc.)

### ISSUE THREAD

**Issue by wanderseeme** [files-community/Files#2746]
**Is your feature request related to a problem? Please describe.**

Integration with folder opening actions (e.g., AutoHotKey, search open folder, show file location, etc.).
For example, I set a shortcut "Windows+Shift+0" in AutoHotKey to open Users folder, but it opens in default Windows Explorer, NOT Files.
For another example, I right click an application icon in start menu and select "Show file location", it opens in default Windows Explorer, NOT Files.
For a third example, I search a folder in start menu or Listary (or any other search ultilities), it opens in default Windows Explorer, NOT Files.

**Describe the solution you'd like**
As far as I'm understanding, it's related to some "hook" feature in Windows? Could you "hook" folder opening actions?

**Describe alternatives you've considered**
N/A.

**Additional context**
N/A.

**Comment by duke7553** [comment]
@wanderseeme Thanks for the feature request. It seems that the robust hooking feature of Windows Explorer and other Win32 apps isn't supported by the WinRT app model (for apps like Files).

Sorry for the inconvenience, but I'll close this now.
