### ISSUE TITLE
Code base: Merge context menus so they can be reused in different layouts

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#2747]
**Is your feature request related to a problem? Please describe.**
We currently reimplement the right click context menu in every layout. This leads to duplicate code and can make the context menu a little harder to work with.

**Describe the solution you'd like**
The context menus that are reused can be merged so that changes will only need to be made once.

**Comment by d2dyno1** [comment]
`BaseContextMenu`?

**Comment by duke7553** [comment]
@d2dyno1 Yeah named something like that. It will be universal to all layout modes. We could also add the ability to add custom items to the flyout based on your layout mode later on, but this is a good start.

**Comment by lukeblevins** [comment]
@yair100 I'll start on this

**Comment by Jaiganeshkumaran** [comment]
I have found that resource dictionaries can have code-behind files.

**Comment by Jaiganeshkumaran** [comment]
I have found that resource dictionaries can have code-behind files.

**Comment by gave92** [comment]
@duke7553 you were working on this? If not, @Jaiganeshkumaran would you like to be assigned on this?

**Comment by winston-de** [comment]
Maybe #2342 could be included in this?

**Comment by yaichenbaum** [comment]
@winston-de This change should make #2342 a little easier to implement but they are two different changes and should be kept separate.
