### ISSUE TITLE
Custom terminal cannot be saved

### ISSUE THREAD

**Issue by stelulocom** [files-community/Files#2748]
**Describe the bug**
Custom terminal application error

**To Reproduce**
1. Go to 'personalise'
2. Click on 'Edit terminal application'
3. No response after finishing editing
4. Click again to become the default template

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/76684088/103268277-2d8a1400-49ee-11eb-8387-5bbbcb7b81ef.png)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10  20h2]
 - App version: [v0.23.1.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?
yes
**Log file**
Please post the log file here so that we can understand your problem better. You can access it from Settings->About->Open log location.
[debug.txt](https://github.com/files-community/Files/files/5749961/debug.txt)

**Comment by yaichenbaum** [comment]
@stelulocom Do the new terminals show up after restarting the app?

**Comment by yaichenbaum** [comment]
Thanks again for your feedback.

_Since we didn't hear from you on this topic for 4+ days, we'll assume everything is worked out and close this feedback item. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this._

**Comment by linsui** [comment]
@yair100 Hi, I have the same issue. I can add powershell core. But if I add Windows terminal, the block wiil be removed when I start Files. Files can only recognize Windows terminal from Microsoft Store. And the default terminal wiil be set to cmd even if the cmd block is removed.

Oh, I found an interesting thing. If I do not follow the document and set the name of `Windows Terminal` as `WindowsTerminal`, `Windows Terminals` or `Window Terminal`, it works. Looks like Files hates the name.:joy:

**Comment by yaichenbaum** [comment]
@linsui Terminal profiles need to have separate names in order to work because that's how we differentiate between them.

**Comment by linsui** [comment]
> Terminal profiles need to have separate names to work because that's how Files differentiates between them.

I only have one block about Windows Terminal.

**Comment by linsui** [comment]
@yair100 This is my `terminal.json` which works

```
{
  "version": 1,
  "DefaultTerminalName": "cmd",
  "terminals": [
    {
      "name": "PowerShell",
      "path": "powershell.exe",
      "arguments": "-noexit -command \"cd '{0}'\"",
      "icon": ""
    },
    {
      "name": "PowerShell Core",
      "path": "pwsh.exe",
      "arguments": "-WorkingDirectory \"{0}\"",
      "icon": ""
    },
    {
      "name": "WindowsTerminal",
      "path": "wt.exe",
      "arguments": "-d \"{0}\"",
      "icon": ""
    }
  ]
}
```

while this does not work

```
{
  "version": 1,
  "DefaultTerminalName": "cmd",
  "terminals": [
    {
      "name": "PowerShell",
      "path": "powershell.exe",
      "arguments": "-noexit -command \"cd '{0}'\"",
      "icon": ""
    },
    {
      "name": "PowerShell Core",
      "path": "pwsh.exe",
      "arguments": "-WorkingDirectory \"{0}\"",
      "icon": ""
    },
    {
      "name": "Windows Terminal",
      "path": "wt.exe",
      "arguments": "-d \"{0}\"",
      "icon": ""
    }
  ]
}
```

**Comment by yaichenbaum** [comment]
@linsui Are you using v1.1?

**Comment by linsui** [comment]
@yair100 Yes

**Comment by linsui** [comment]
@yair100

https://github.com/files-community/Files/blob/34c69f40a06de67e4ff3bfdab51c844ac144dae3/Files/Controllers/TerminalController.cs#L120-L131

I guess I found what happened. I installed Windows Terminal from scoop so Files thought that it's not installed and remove the block.

**Comment by yair100** [comment]
> @yair100
> 
> https://github.com/files-community/Files/blob/34c69f40a06de67e4ff3bfdab51c844ac144dae3/Files/Controllers/TerminalController.cs#L120-L131
> 
> I guess I found what happened. I installed Windows Terminal from scoop so Files thought that it's not installed and remove the block.

Perhaps we should stop removing the Terminal block if we can't detect Terminal. Although, the better solution would be if we could use the package name from Scoop to detect if it's installed.

**Comment by linsui** [comment]
@yair100
> Although, the better solution would be if we could use the package name from Scoop to detect if it's installed.

I thought it can be detected by `Test-Path "$env:SCOOP/apps/windows-terminal"`.

**Comment by linsui** [comment]
@yair100 Could you please reopen this issue?

**Comment by yair100** [comment]
> @yair100 Could you please reopen this issue?

If you can find the package name, I should be able to fix this in a simple PR. Can you try running this command `Get-AppxPackage -AllUsers`?

**Comment by linsui** [comment]
@yair100 I ran `Get-AppxPackage -AllUsers | Select-String "Terminal"` and got nothing. Scoop does not install it but unpack the installer.

**Comment by yaichenbaum** [comment]
@linsui Can you open a new issue for detecting windows terminal from a scoop installation?

**Comment by linsui** [comment]
@yair100 OK!
