### ISSUE TITLE
icon can not fit the HR screen

### ISSUE THREAD

**Issue by fanstyle-cmd** [files-community/Files#2751]
the icon was blurry when it was showed on the 4K screen

**Comment by gave92** [comment]
Thanks for your feedback. We're having trouble understanding what you're requesting and need additional information to investigate this item. Please open a new issue filling out the issue template to the best of your ability. Screenshots and the app version are of particular importance.

**Comment by fanstyle-cmd** [comment]
[cid:image003.png@01D6DFC3.BEA99590]
Thanks for your reply. Except for the icon of the file folder, the other icons were not clear on my 4K display, the app version is 0.23.1.0. if any other information was needed, please feel free to contact me. This app is really amazing.
发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Marco Gavelli<mailto:notifications@github.com>
发送时间: 2020年12月29日 23:14
收件人: files-community/Files<mailto:Files@noreply.github.com>
抄送: fanstyle-cmd<mailto:fanstyle@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [files-community/Files] icon can not fit the HR screen (#2751)


Thanks for your feedback. We're having trouble understanding what you're requesting and need additional information to investigate this item. Please open a new issue filling out the issue template to the best of your ability. Screenshots and the app version are of particular importance.

―

**Comment by gave92** [comment]
@fanstyle-cmd thanks for the additional info. This issue has been resolved in the development branch. The fix will ship with the next public version.
