### ISSUE TITLE
Width of Columns

### ISSUE THREAD

**Issue by 9xr42** [files-community/Files#2755]
**Is your feature request related to a problem? Please describe.**
It's frustrating when the columns reset every time the app is opened, as it cuts off the information and it makes me have to resize the columns every time.

**Describe the solution you'd like**
I would like a feature that allows us to save the size of the columns that we set and to have different sized columns for each folder. Each folder has different naming types and file types, and so saved column widths for each folder would be appreciated.

**Describe alternatives you've considered**
A feature where the columns are set to fit to the longest name/info in each column would also serve the purpose.

**Additional context**
Windows 10 with a 3840x2160 4K display.

**Comment by yaichenbaum** [comment]
Merging with #2675.
