### ISSUE TITLE
View Format

### ISSUE THREAD

**Issue by 9xr42** [files-community/Files#2757]
**Is your feature request related to a problem? Please describe.**
It's frustrating when the files in the Pictures and Videos folders are the same view format as the Documents or Downloads.

**Describe the solution you'd like**
Similar to the default File Explorer on Windows, a change of view based on the type of folder. For example, have the Pictures and Videos folders use Grid View Medium by default and Documents use List View, and have the ability to save what view format was chosen for each folder.

**Describe alternatives you've considered**
NA

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by yaichenbaum** [comment]
@9xr42 This feature was implemented with #2667 and will be available with the next update.
