### ISSUE TITLE
Add support for pinning hidden folders to the sidebar

### ISSUE THREAD

**Issue by youngerstar** [files-community/Files#2763]
**Describe the bug**
Cannot pin hidden folder to sidebar. 
无法把隐藏的文件夹固定到侧边栏。

**To Reproduce**
1. Left click on hidden folder
2. Right click
3. Click 'Pin to sidebar'

**Expected behavior**
The hidden folder is pinned to the sidebar. 

**Screenshots**
![image](https://user-images.githubusercontent.com/46211595/103349025-b1b7c680-4ad6-11eb-8d66-58bc00d1715c.png)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2 19042.685]
 - App version: [v0.23.1.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
Please post the log file here so that we can understand your problem better. You can access it from Settings->About->Open log location.

**Comment by yaichenbaum** [comment]
@youngerstar This issue should be resolved with #3277.
