### ISSUE TITLE
Application crashes when clicking sorting by name twice on a plain drive (no subfolder)

### ISSUE THREAD

**Issue by heistema** [files-community/Files#2775]
**Describe the bug**
When having navigated directly onto a drive (like C:, D:, ...) the whole file manager crashes when I click on the "Name" tab in the header twice in order to sort the files by name in ascending and then descending order.

**To Reproduce**
1. Go to any drive (like C:). It doesn't matter whether you do this by using the Drive button in the sidebar or if you use the one on the main page
2. In the header of the file contents table click on "Name". Your drive contents will get sorted.
3. Click again on the "Name" header button....
4. ...Visual Studio will stop the debugging of the application because in the file "ViewModels/FolderSettingsViewModel.cs" an exception is thrown in the method: `WriteLayoutPreferencesToSettings(string folderPath, LayoutPreferences prefs)`. Exception is shown in Screenshot below.

**Expected behavior**
I would expect Files to simply change the sorting order of my files and folders on my (external) hard drive.

**Screenshots**
![image](https://user-images.githubusercontent.com/76635240/103380747-1d575f00-4aea-11eb-82f0-6d99f8e5855d.png)
Despite using an english version of Windows and Visual Studio somehow the error still seems to be in german... I am really sorry for that it translates into: "The given path is invalid".

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2 19042.685]
 - App version: [v0.11.0]??? Current master branch on files-community/Files

**Additional context**
The issue seems to be that whenever a naked drive is sorted instead of some folder the path ends with '\\' so e.g. "C:\\". If a folder is opened up there would be no such trailing '\\', e.g. "C:\someFolder". Every path which ends with a trailing backslash or encoded as '\\' is not a valid path?!
A quick fix seems to modify the property "public SortDirection DirectorySortDirection" as follows:
`
        public SortDirection DirectorySortDirection
        {
            get => LayoutPreference.DirectorySortDirection;
            set
            {
                if (SetProperty(ref LayoutPreference.DirectorySortDirection, value, nameof(DirectorySortDirection)))
                {
                    // Workaround for the case that the directory path is a drive. Then the trailing '\' needs to be removed
                    String workingDirectoryPath = associatedInstance.FilesystemViewModel.WorkingDirectory.EndsWith('\\') ? associatedInstance.FilesystemViewModel.WorkingDirectory.TrimEnd('\\') : associatedInstance.FilesystemViewModel.WorkingDirectory;
                    UpdateLayoutPreferencesForPath(workingDirectoryPath, LayoutPreference);
                    SortDirectionPreferenceUpdated?.Invoke(this, new EventArgs());
                }
            }
        }
`
I do know the codebase not that well yet. But I think a better solution might be to modify the method "public async Task<FilesystemResult> SetWorkingDirectoryAsync(string value)" in "ItemViewModel.cs" as it sets the directory path used in "DirectorySortDirection"... Is this approach correct? Was somebody able to reproduce the issue?

**Log file**
Please post the log file here so that we can understand your problem better. You can access it from Settings->About->Open log location.
[debug.txt](https://github.com/files-community/Files/files/5755725/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5755726/debug_fulltrust.txt)

**Comment by gave92** [comment]
@heistema thanks a lot for the issue report and the proposed solution.
I believe the best solution for this is to make the changes inside `UpdateLayoutPreferencesForPath`, something like:
```cs
if (App.AppSettings.AreLayoutPreferencesPerFolder)
{
    if (!WriteLayoutPreferencesToAds(folderPath.TrimEnd('\\'), prefs))
    {
        WriteLayoutPreferencesToSettings(folderPath.TrimEnd('\\'), prefs);
     }
}
```
Do you wish to open a pull request with this changes yourself?

**Comment by heistema** [comment]
Yes, would be awesome. Thank you very much

**Comment by heistema** [comment]
I fixed it using a conditional assignment on folderPath (see comment in code). That's because "TrimEnd(..)" returns null if not successful. So normal paths to folders would become null because they have no trailing '\\'.
