### ISSUE TITLE
Feature: Add command palette

### ISSUE THREAD

**Issue by winston-de** [files-community/Files#2780]
**Is your feature request related to a problem? Please describe.**

One of my favorite features in Windows Terminal and Visual Studio Code is the command palette. It makes it very easy to quickly access commands from the keyboard without having to memorize a keyboard shortcut or grab the mouse and locate a button. 

This would also be very helpful when trying to find a shell command, because there can be quite a few of them to sift through in a context menu:

![image](https://user-images.githubusercontent.com/59544401/103386263-e4e85e80-4ab2-11eb-8fdb-3a4a98df9652.png)

I think this would also give Files more of an appeal over Windows Explorer, where finding the button you need is like finding a needle in a haystack.

Since Files is quickly gaining more features (which is great!), I think it may be worth considering this.

**Describe the solution you'd like**

A command pallet like the one in Windows Terminal would be nice.

**Describe alternatives you've considered**

**Additional context**
Windows terminal command pallet:
![image](https://user-images.githubusercontent.com/59544401/103385508-a3a27f80-4aaf-11eb-92a5-41910263a538.png)

**Possible commands**
- shell context menu items for selection
- cut, copy, paste selection
- enable dual pane
- switch to tab
- new tab
- close other tabs
- go up directory
- navigate back, forward
- search

**Comment by heistema** [comment]
Would be awesome if this could get integrated into the search bar... So you have on bar for everything.

**Comment by yaichenbaum** [comment]
@winston-de I think we can go ahead on this feature without a spec sheet since we can pretty much follow the design in Windows Terminal (obviously with our own tweaks to the design).

**Comment by winston-de** [comment]
@yair100 Great!

Code wise, I think the best way to go about this is to have all the commands/actions implement a single interface, and then adding them to a master list that a ListView (the commands) can bind to.

What are your thoughts?

**Comment by yaichenbaum** [comment]
@winston-de That's the goal, in fact, it will make implementing #1660 easier if all the code relating to keyboard shortcuts is in one place. We already are part of the way there with `Interaction.cs`, but there is a lot of room for improvement.

**Comment by yaichenbaum** [comment]
@cinqmilleans we haven't created a design for this yet but it'll be a good idea to keep this in mind when planning the shortcut work.

**Comment by QuaintMako** [comment]
This feature might be a breeze to implement once we're done with Rich Commands?

**Comment by yaira2** [comment]
Yes
