### ISSUE TITLE
When marking a folder as hidden the folder view does not update itself automatically

### ISSUE THREAD

**Issue by heistema** [files-community/Files#2785]
**Describe the bug**
When any folder is set to a hidden folder by using the properties window the folder view does not update itself automatically. So after closing the properties window the folder icon still is shown as if the folder is being visible.

**To Reproduce**
1. Go to any folder and right click on it
2. Click on 'Properties' and enable the checkbox on 'Hidden'
3. Click on 'OK'. This closes the dialog and applies the hidden property.
4. As can be seen the folder icon still gives the impression of the folder being a visible one. But in fact it's not. Manual reload (e.g. by changing folder back and forth) solves the issue

**Expected behavior**
Right after closing the properties dialog the folder icon should change to its respective transparent brother

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2 19042.685]
 - App version: Current master

**Additional context**
None. As mentioned above a manual refresh of the folder view solves the problem.

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5756177/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5756178/debug_fulltrust.txt)

**Comment by yaichenbaum** [comment]
@heistema Do you want to work on this?

**Comment by heistema** [comment]
@yair100 Yes, will do.
