### ISSUE TITLE
File properties page does not support RTL

### ISSUE THREAD

**Issue by Don-Vito** [files-community/Files#2786]
**Describe the bug**
File details do not support RTL

**To Reproduce**
1. Open file properties by right-clicking the file and choosing properties

**Expected behavior**
The page is RTL

**Screenshots**
![image](https://user-images.githubusercontent.com/4639110/103390796-ee0f1500-4b1e-11eb-911b-f74cab62ddb2.png)

**Desktop (please complete the following information):**
 - App version: v0.23.9.0

**Comment by yaichenbaum** [comment]
@Don-Vito I will work on fixing this issue. Also, do we finally have someone who can help with the Hebrew translation??

**Comment by yaichenbaum** [comment]
@Don-Vito This issue should be resolved with #2788.

**Comment by Don-Vito** [comment]
> 
> 
> @Don-Vito I will work on fixing this issue. Also, do we finally have someone who can help with the Hebrew translation??

Yep, I can help :)
