### ISSUE TITLE
Right click menu animation drops down from the top when the menu is upon the cursor

### ISSUE THREAD

**Issue by zhangtianli2006** [files-community/Files#2793]
Right click menu animation drops down from the top when the menu is upon the cursor

![Screenshot 2020-12-31 223052](https://user-images.githubusercontent.com/49156174/103414200-e5b6e880-4bb7-11eb-94bb-9f0ef344353b.jpg)

**Comment by yaichenbaum** [comment]
@zhangtianli2006 This is the intended behavior when the menu has a lot of items. The next update will come with an option to disable the animation, and we will work on reducing the size of the menu as well in a future update.
