### ISSUE TITLE
Code base: Rewriting/improving the FullTrustProcess

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#2794]
**Is your feature request related to a problem? Please describe.**
The current FullTrustProcess does what it's meant to do, but the code base is kind of messy and hard to work with, additionally, it uses more system resources than a project of this size should.

**Describe the solution you'd like**
Rewriting the FullTrustProcess seems likely to happen at this point, while it doesn't need to be done in c++, once the effort is being made, using c++ might be a good choice in order to squeeze the maximum performance that we can while using as little system resources as possible.

**Describe alternatives you've considered**
Improving the current code for this process to use better practices and to try to reduce the memory usage.

**Comment by gave92** [comment]
@yair100 @duke7553 correct if I'm wrong: I understood that the plan is to switch sometimes in the future to using net5 + winui desktop. 
This would make unnecessary to have a fulltrust process separated from the main app
Depending on if and when the above is going to happen it may or may not make sense to rewrite the Fulltrust process to C++.

We could anyway check if there is any performance gain in loading the context menu (this is the most noticeably slow part of the Fulltrust process) by switching to c++

**Comment by yaichenbaum** [comment]
@gave92 We haven't made any decision around that yet, it's going to be quite a while before WinUI Desktop is going to be ready for us to use. Taking that into account, if we were to make the switch, it won't be for a while and I wouldn't like that to hold us back on improving what we have now. That being said, if sticking with c# will make it easier to move over to WinUI Desktop in the future, than we should instead work on reducing the memory usage of the current code.

**Comment by gave92** [comment]
Not for the faint of hearts:
you can find [here](https://github.com/files-community/Files/tree/cpp_fulltrust) a branch with a skeleton for the rewritten fulltrust process in C++.

What works @01/01/2021:
- AppService connection

I'm going to try and see how to port the context menu stuff to check if there's any performance gain.

In case someone else wants to get his/her hands dirty.. contributions are welcome :)

**Comment by d2dyno1** [comment]
Wooow @gave92!!
Amazing work! Didn't know you know c++ too!

**Comment by yaichenbaum** [comment]
@gave92 Perhaps we should do this on a branch in the main repo so that it gets more visibility?

**Comment by d2dyno1** [comment]
For #4180

**Comment by yaichenbaum** [comment]
@gave92 Did we want to continue this or was the plan to wait for WinUI Desktop?
