### ISSUE TITLE
Add support to pin an item by dragging it to the sidebar

### ISSUE THREAD

**Issue by gsingh13** [files-community/Files#2800]
**Is your feature request related to a problem? Please describe.**
- Not related to a problem.

**Describe the solution you'd like**
1. Be able to drag and drop items I'd like to pin to the sidebar. 
2. Be able to drag and reorient items in the left pane.

**Describe alternatives you've considered**
- I can pin items by right-clicking and selecting "Pin to Sidebar", however, it'd be nice to do 1 & 2 from above in one action.

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?
- Device: Beelink GT-R running Windows 10 Version 20H2 Build 19042.685
- Files Version 0.23.1.0

**Comment by gave92** [comment]
Merging with #2626
