### ISSUE TITLE
splitted windows 

### ISSUE THREAD

**Issue by bronewi4ok** [files-community/Files#2801]
Your app is one of the best for Windows and looks really awesome. But it'll be great to improve one feature to make it even better. When I open two windows at the same time it feels like I use two different apps to solve one problem. Is there a way to gather it in splitted one? Like a modernized total commander, something similar to a Linux file manager called Nemo:
https://user-images.githubusercontent.com/31940713/47256700-2bad8900-d452-11e8-82a5-920343b325e8.png
https://i.imgur.com/BTjhRXT.png

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨

I ACKNOWLEDGE THE FOLLOWING BEFORE PROCEEDING:
1. If I delete this entire template and go my own path, the core team may close my issue without further explanation or engagement.
2. If I list multiple bugs/concerns in this one issue, the core team may close my issue without further explanation or engagement.
3. If I write an issue that has many duplicates, the core team may close my issue without further explanation or engagement (and without necessarily spending time to find the exact duplicate ID number).
4. If I leave the title incomplete when filing the issue, the core team may close my issue without further explanation or engagement.
5. If I file something completely blank in the body, the core team may close my issue without further explanation or engagement.

All good? Then proceed!
-->

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by gave92** [comment]
![image](https://user-images.githubusercontent.com/9673091/103423753-a6cd6680-4ba8-11eb-8a27-81dd35be4d2e.png)

**Comment by bronewi4ok** [comment]
That's the best news in file managers' history! Can't wait for the next release. Happy New Year!

**Comment by bronewi4ok** [comment]
But will a second window have an own independent tabs panel?

**Comment by gave92** [comment]
Nope there will be a single tabs panel, inside each tab you can have one or two panes open

**Comment by bronewi4ok** [comment]
Your approach is good too. Probably enough for all my wishes. Thanks!

**Comment by gave92** [comment]
> That's the best news in file managers' history!

Thank you and happy new year ;)
