### ISSUE TITLE
Remove grey outline around unfocused tabs

### ISSUE THREAD

**Issue by Shadowblitz16** [files-community/Files#2806]
**Is your feature request related to a problem? Please describe.**
Can you remove the outline around unfocused tabs?
for example the downloads tab in this pic..
![image](https://user-images.githubusercontent.com/2453707/103434686-b99c6700-4bb9-11eb-9b64-5951f3d2768b.png)

**Describe the solution you'd like**
just make it flat when its not hovered or selected

**Describe alternatives you've considered**
none

**Additional context**
I use windows 10 pro 64 bit

**Comment by d2dyno1** [comment]
Making it flat would confuse users

**Comment by Shadowblitz16** [comment]
No it wouldn't. besides if you didn't want to confuse users Microsoft wouldn't be using a mobile gui framework in a desktop environment
you can make the tab a solid color instead of of a outline that way it looks better and you can still see where it is

**Comment by yaichenbaum** [comment]
@Shadowblitz16 We would love to have a discussion around the outline, but before making any design change, we need to go through what's wrong with the current design and what change can fix it.
