### ISSUE TITLE
bug反馈与功能反馈

### ISSUE THREAD

**Issue by Fishcat6012** [files-community/Files#2809]
Bug：当进行有关快捷方式时候应用崩溃（直接卡死）
功能反馈：建议在应用侧边栏添加一个C盘的按钮（方便使用）

**Comment by yaichenbaum** [comment]
@Fishcat6012 Can you add some more details? We usually expect users to fill out the issue template when reporting a bug or submitting a feature request.

**Comment by d2dyno1** [comment]
Please write bug reports in English

**Comment by heistema** [comment]
Google Translate:

The application crashes when performing related shortcuts (directly stuck)
Feature feedback: It is recommended to add a C drive button in the sidebar of the application (easy to use)

**Comment by ColbertBrave** [comment]
@Fishcat6012 应用侧边栏可以添加驱动器啊。在设置里修改。这个开发者是老外，要用英语。

**Comment by yaichenbaum** [comment]
@Fishcat6012 We need a little more information from you such as the app version and steps to reproduce the issue, please reopen this issue when you have filled out the issue template.
