### ISSUE TITLE
Safe file copy method that doesn't crash as in explorer

### ISSUE THREAD

**Issue by heistema** [files-community/Files#2815]
**Is your feature request related to a problem? Please describe.**
Whenever I copy huge amounts of date e.g. from one drive to another the default explorer.exe keeps on crashing from time to time. Which is especially annoying when you don't know where it stopped. As a workaround I use "TeraCopy", but it would be awesome if my favourite file manager could do this on his own (and more elegant, lightweight and beautifully).

**Describe the solution you'd like**
It would be awesome if we could introduce a raw file copy method (could also be optional for a start). There might even be libraries out there which already could deliver such a solution.

**Describe alternatives you've considered**
Well the alternative is to restart the process trying to find the corrupted file or sth. Or you could use Tools or Linux.

**Additional context**

**Comment by d2dyno1** [comment]
Could you provide log files?

**Comment by heistema** [comment]
I had no crash in Files yet. I assume that Files will have the same issues as the APIs are the same as explorer uses, right?

**Comment by d2dyno1** [comment]
Files uses `IStorageItem` calls which are the same that file explorer uses

**Comment by yaichenbaum** [comment]
@heistema While Files uses a lot of the same APIs as File Explorer, there is no guarantee that it has the same crashes, can you run some tests and upload the logs if Files does indeed crash?

**Comment by heistema** [comment]
@yair100 Yes, I will try to reproduce this using Files.

**Comment by yaichenbaum** [comment]
Thanks again for your feedback.

_Since we didn't hear from you on this topic for 5+ days, we'll assume everything is worked out and close this feedback item. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this._
