### ISSUE TITLE
Allow expansion of left-hand menu in settings when window is not maximised

### ISSUE THREAD

**Issue by va-it** [files-community/Files#2821]
**Is your feature request related to a problem? Please describe.**
When the window is not maximised it is impossible to expand the left-hand menu

**Describe the solution you'd like**
Either an option to expand the menu (like the hamburger menu on Start) or leave the left-hand menu always open (like the Windows Settings)

**Describe alternatives you've considered**
None

**Additional context**
Touch-screen laptop - 1920x1080 - App version: 0.23.1.0

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
