### ISSUE TITLE
A new cloud feature

### ISSUE THREAD

**Issue by Magangel** [files-community/Files#2826]
Please, add the ability to sign up to more than one onedrive personal account, or at least, to one custom account different from the one synchronized with the onedrive app.
Greetings and keep the great work

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by yaichenbaum** [comment]
@Magangel This issue should be resolved with #3177.
