### ISSUE TITLE
Could you speed up interface loading？

### ISSUE THREAD

**Issue by ColbertBrave** [files-community/Files#2827]
Dear developers,

Compared with the file explorer in win 10, the  interface loading speed in **Files** is much slower. Could you speed it up? Thanks.

**Comment by yaichenbaum** [comment]
@ColbertBrave The startup speed is something we are working on improving over time, merging this issue with #2568.

**Comment by yaira2** [comment]
We're excited to share that startup performance will be significantly improved in the upcoming release of version 3. You can download the preview version from our website https://files.community/download.
