### ISSUE TITLE
All my files are gone after cut/paste-ing multiple folders

### ISSUE THREAD

**Issue by MatejaSrejic** [files-community/Files#2828]
Okay, I tried to cut/paste 5 folders full of my valuable scripts and programs, and what do you know, only the folders were moved, with no files inside of them. Seriously, I just lost 500+ programs of mine and ended up with empty folders. I thought the process wasn't finished, so I left it for half an hour, came back, empty folders. I started panicking, I didn't know what to do, I quickly tried CTRL + Z, nothing. I hoped it was a visual bug, went inside the regular File Explorer, empty folders! Panic, panic, panic! I started restoring all my 6000+ files from the recycle bin, hoping the scripts were there, and what do you know, they weren't. Luckily, I got myself out of the trap by installing Recuva (not an ad lol). So yeah, I just want to warn the peeps here to never, ever move important files with this program, you might end up in this situation.

**Comment by yaichenbaum** [comment]
@MatejaSrejic First of all, our apologies about this issue, we are working on improving the quality of copy/paste and as we get close to releasing v1, we are going to make sure this feature works as expected. Can you share with us the version number you had this issue on?

**Comment by MatejaSrejic** [comment]
Don't know if it helps, but I installed the latest version three days ago. If that doesn't help, I'll check which version I used tomorrow (I don't have my computer on me)

**Comment by d2dyno1** [comment]
@yair100 is the newest version after #2742 patch?

**Comment by gave92** [comment]
#2742 doesn't help I'm afraid
The move operation is implemented as a Copy + (permanent!) Delete, Delete should only be done if the copy operation returns success.... except after investigation it appears that Copy *always* returns success regardless of the actual result.
@d2dyno1 could you check as well?
Thanks @MatejaSrejic for bringing this out, we'll be sure to fix it.

**Comment by MatejaSrejic** [comment]
Thank you. I made a huge mistake but I luckily got out of it.

**Comment by d2dyno1** [comment]
@gave92 indeed. We should take the result of `errorCode` variable.

**Comment by gave92** [comment]
@d2dyno1 I'd be careful with that. What we do with `errorCode` in a lot of places is incorrect:
```cs
var returnStatus = NO_ERROR;
errorCode.ProgressChanged += (s, e) => returnStatus = e.ToStatus();`
...
errorCode?.Report(SOME_ERROR);
----> do not expect that here returnStatus == errorCode :(
```

**Comment by d2dyno1** [comment]
Hmm..
I suggest disabling the Move operation in a patch update for now to prevent further damage until the issue is resolved.

@yair100

**Comment by gave92** [comment]
Or at least sending the stuff to recycle bin instead of permanent delete. Anyway it should not be too hard to fix.

**Comment by yair100** [comment]
> Hmm..
> I suggest disabling the Move operation in a patch update for now to prevent further damage until the issue is resolved.
> 
> @yair100

This can be done but we are so close to releasing v1 that it might be just as fast to fix the actual bug and ship out v1 then to ship a change that disables the feature.

**Comment by yaichenbaum** [comment]
@MatejaSrejic This issue should be fixed with #2830, we are going to do some extensive testing first but you can expect this update to be available in around a week or two.

**Comment by MatejaSrejic** [comment]
Cool, thanks.

**Comment by MatejaSrejic** [comment]
Oh no, looks like Recuva didn't recover some of the files properly. When opened in Notepad++ it only has `NUL` over and over. F*** me. I'm screwed... can anyone recommend what to do. 😭😭
