### ISSUE TITLE
Consider creating a new folder with the current selection

### ISSUE THREAD

**Issue by szaimen** [files-community/Files#283]
**Is your feature request related to a problem? Please describe.**
On macos finder you have the option to create a folder from the current selection. So it creates a folder and move the current selection automatically inside the folder. Afterwards you get asked for the name for this folder.

**Describe the solution you'd like**
Show when right-clicking on the current selection the option to create a folder with the current selection. Could be a thing to consider.

**Describe alternatives you've considered**
No ideas in the moment

**Additional context**
On macos it looks like this.
![image](https://user-images.githubusercontent.com/42591237/68514014-d884bf00-027c-11ea-9d79-bf90c1434a9f.png)

**Comment by yaichenbaum** [comment]
I like this idea, is this something other people would want as well?

**Comment by szaimen** [comment]
Maybe you could also pin this issue to improve the discoverability of this topic to get more opinions from the community?

**Comment by yaichenbaum** [comment]
@szaimen I pinned this issue, the plan is to leave it there for a few weeks and try to get some more feedback.

**Comment by lorisobi** [comment]
this Feature would be really nice. i can imagine very well to integrate this in my workflow.

**Comment by mrjnklva** [comment]
Upvote:)

**Comment by yaichenbaum** [comment]
@szaimen This feature request was implemented with #4672.
