### ISSUE TITLE
Unable to drag shortcuts (lnk) files to move them

### ISSUE THREAD

**Issue by Tech-How** [files-community/Files#2832]
**Describe the bug**
When you have a shortcut file, like an *lnk file, you can't drag it to different places.

**To Reproduce**
1. Create a shortcut with Windows' File Explorer.
2. Locate that shortcut in the Files app.
3. Now try to move it by dragging.

**Expected behavior**
I expected to be able to drag it to another folder, but nothing happens when you drag shortcuts.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 (OS Build 19042.685) 
 - App version: [v0.23.1.0]

**Additional context**
Even after restarting _and_ uninstalling the app, the issue is still present.

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5761836/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5761837/debug_fulltrust.txt)

**Comment by gave92** [comment]
Thanks for opening this feedback item. Unfortunately due to UWP limitations this is (to my knowledge) simply impossible.
Copy/Cut/Pasting shortcuts instead should be working.

**Comment by gave92** [comment]
I was correct the first time :)

Previous comment:
Due to UWP limitations dragging shortcut files is sadly impossible. The same goes for hidden files/folders.
Copy/Moving/Pasting instead should be working.
