### ISSUE TITLE
Add "Shortcut" option to the new menu

### ISSUE THREAD

**Issue by Tech-How** [files-community/Files#2833]
**Is your feature request related to a problem? Please describe.**
I wouldn't call it a problem, but it is a bit of an annoyance when I have to open the Windows File Explorer to create shortcuts.

**Describe the solution you'd like**
In the new menu in the Files app, there should be an option to create a shortcut.

**Describe alternatives you've considered**
I would normally have to open the Windows File Explorer to create a shortcut.

**Additional context**
Windows 10 Version 20H2 (OS Build 19042.685)
App Version 0.23.1.0

**Comment by yaichenbaum** [comment]
Merging with #1671.
