### ISSUE TITLE
 unpacking winrar

### ISSUE THREAD

**Issue by dkostarnov** [files-community/Files#2838]
I will describe the process as I unpack the files. I open the archive in WinRAR, drag a folder from there, the unzip process starts, but it stops at 99 percent without error. But when I unpack the archive through the context menu, everything is fine. But this method does not always suit me. If there is a folder with a password inside the archive, then winrar does not fill in the password, but simply unpacks the folders without a password

**Comment by gave92** [comment]
Is this behaviour consistent? Does it work if you drag&drop a single file from the zip? Does a semitransparent window appear over Files (saying "Drop here") when you are about to drop the items?

**Comment by dkostarnov** [comment]
> Is this behaviour consistent? Does it work if you drag&drop a single file from the zip? Does a semitransparent window appear over Files (saying "Drop here") when you are about to drop the items?
> Could you fill the issue description with app version and log files?

When dragging, a semi-transparent "Drop here" box appears. And everything that I described in the post comes through every time I try to pull files from the archive. I have the latest release of faith

**Comment by yaichenbaum** [comment]
Thanks again for your feedback.

_Since we didn't hear from you on this topic for 3+ days, we'll assume everything is worked out and close this feedback item. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this._
