### ISSUE TITLE
Cannot run CMD files as administrator.

### ISSUE THREAD

**Issue by Tech-How** [files-community/Files#2845]
**Describe the bug**
I noticed with a recent update, you've added the ability to run programs as an administrator. Which I love, but I write a lot of CMD files, and the "Run as administrator" option is not present in the right-click context menu for CMD files.

**To Reproduce**
1. Locate a CMD file.
2. Right-click; there is no "Run as administrator" option.

**Expected behavior**
I expected there to be a "Run as administrator" option.

**Screenshots**
![image](https://user-images.githubusercontent.com/76794507/103597625-b6adb900-4ece-11eb-8ff4-9364d3b31a52.png)
![image](https://user-images.githubusercontent.com/76794507/103597709-e0ff7680-4ece-11eb-9412-a39bb2194c48.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Version 20H2 (OS Build 19042.685)
 - App version: [v0.23.1.0]

**Additional context**
This problem does occur after restarting the app. I have also noticed this issue is still present in lnk files, BAT files, and some others.

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5767658/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5767661/debug_fulltrust.txt)

**Comment by yaichenbaum** [comment]
@Tech-How This issue should be resolved with #2846.
