### ISSUE TITLE
Add "send to Desktop (Create link)" to right-clicking on a file or folder

### ISSUE THREAD

**Issue by szaimen** [files-community/Files#285]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to remember a file or beeing able to send a shortcut to my desktop very quick to afterwards beeing able to open the folder or file very fast.

**Describe the solution you'd like**
Please add "send to Desktop (Create link)" to right-clicking on a file or folder

**Describe alternatives you've considered**
Maybe this could get implemented like in the current file explorer: to show the "send to" button and when hovering over it seeing the option to "send to Desktop". (and probably also "create zip file"?)

**Additional context**
Currently nothing

**Comment by yaichenbaum** [comment]
Thank you for opening this issue.

**Comment by gave92** [comment]
This would be solved together with #1397

**Comment by R3voA3** [comment]
I like that idea.

**Comment by yaichenbaum** [comment]
We don't have plans to implement this feature.
