### ISSUE TITLE
Crash when more than 10 tabs opened

### ISSUE THREAD

**Issue by sanbrother** [files-community/Files#2850]
Crash when more than 10 tabs opened

**To Reproduce**
1. Ctrl + T to open a new tab
2. Repeat step 1 (at least 10 times)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2 19042.685]
 - App version: [master]
 
**Screenshot**
![Capture](https://user-images.githubusercontent.com/817077/103649289-2daf8400-4f99-11eb-9d08-d9897a52764f.PNG)

**Comment by yaichenbaum** [comment]
Merging with #2145.

**Comment by gave92** [comment]
This happens even if you open tabs "slowly" unfortunately and 100% of time

**Comment by yaichenbaum** [comment]
@gave92 It only seems to happen if the last tab is selected when opening the new tabs.
