### ISSUE TITLE
Search in trash crash the apps

### ISSUE THREAD

**Issue by maxicraftplus** [files-community/Files#2852]
**Describe the bug**
When searching for something via search menu in trash it totally crash the app after one letter

**To Reproduce**
1. Go to trash
2. Click on search menu
3. put anything inside
4. 

**Expected behavior**
the app should freeze for a sencode or two and crash without error code

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 2004 19041.685]
 - App version: [v0.23.1.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5771524/debug.txt)

**Comment by gave92** [comment]
Thanks for reporting this. In version 1.0 (next public version) the crash has been fixed but the ability to search in recyclebin is not implemented yet.
