### ISSUE TITLE
.NET Framework Initialization Error

### ISSUE THREAD

**Issue by phamwon** [files-community/Files#2860]
**Describe the bug**

FilesFullTrust.exe - .NET Framework Initialization Error
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscoreei.dll could not be loaded

**Desktop (please complete the following information):**
 - OS Version: Windows 10 21277.1000
 - App version: 0.23.1

**Additional context**
Error when open Files

**Comment by gave92** [comment]
Thanks for this report. It looks more like a Windows issue that a Files issue.
Are you getting the same error in any other program?
Last answer [here](https://answers.microsoft.com/en-us/windows/forum/windows_10-performance-winpc/error-microsoftnetframeworkv4030319mscoreeidll/0aaef68c-5f61-45f7-bdb8-bb7280140995) suggests a way to fix the issue

**Comment by yaichenbaum** [comment]
Thanks again for your feedback.

_Since we didn't hear from you on this topic for 4+ days, we'll assume everything is worked out and close this feedback item. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this._

**Comment by kn0xit** [comment]
I have the same issue. Would greatly appreciate help on this.

See error message:
![files-screenshot-errormessage](https://user-images.githubusercontent.com/40426730/105699602-e5d0ac80-5f07-11eb-8319-ac4374cef04e.jpg)

The message pops up three times in a row in overlapping dialogs.

I am not receiving this message in any other programs.

Files Version 1.1.5.0 did not resolve the issue.
Resetting the app did not help.
I am on Windows Insider Build 210115-1423, but the Problem existed for a while already.
I am on Windows on Arm on a Surface Pro X.

debug.txt content from last launch:

`2021-01-25 12:14:52.0375|INFO|GetClassFullName|App launched|`
`2021-01-25 12:14:52.5244|INFO|GetClassFullName|Drive added: C:\, Fixed|`
`2021-01-25 12:16:43.3654|INFO|GetClassFullName|Running on ARM: True|`


mscoreei.dll exists in folder C:\Windows\Microsoft.NET\Framework64\v4.0.30319 with file version 4.8.4161.0 
All users or group have at least "Read & execute" permission

**Comment by tuncs** [comment]
Same issue here.

**Comment by zeusongit** [comment]
Still getting this error, on latest 2022

**Comment by Josh-65** [comment]
Try the preview version https://files.community/download/preview

You can also try running these in an admin CMD terminal then restart when there finished.
sfc /scannow
dism /online /cleanup-image /restorehealth`
