### ISSUE TITLE
The Uids of the details and tiles view buttons are different in string resources

### ISSUE THREAD

**Issue by XPoppyX** [files-community/Files#2862]
**StatusBarControl.xaml**

**Id** end in "**... views**" instead of "**... view**", was this intended?

![Captura de pantalla 2021-01-06 074259](https://user-images.githubusercontent.com/61259627/103759692-e3f38780-4ff2-11eb-8846-dc699df80388.png)
![Captura de pantalla 2021-01-06 074308](https://user-images.githubusercontent.com/61259627/103759697-e524b480-4ff2-11eb-883e-1addaaaa96c6.png)

**Strings:**

![Captura de pantalla 2021-01-06 074520](https://user-images.githubusercontent.com/61259627/103759998-43519780-4ff3-11eb-9f03-703fd4f445b7.png)
![Captura de pantalla 2021-01-06 074540](https://user-images.githubusercontent.com/61259627/103760005-4482c480-4ff3-11eb-843e-3f5d565b85e9.png)
![Captura de pantalla 2021-01-06 074553](https://user-images.githubusercontent.com/61259627/103760007-4482c480-4ff3-11eb-875c-bc5f8ea340f3.png)
------------------------

I have a PR ready to fix this if it should end in "**... view**"

**Comment by gave92** [comment]
Agreed some resources are different from the "Uid", if you can fix them it would be great.

**Comment by XPoppyX** [comment]
but is it okay that it ends in "..views" instead of "... view"?

**Comment by gave92** [comment]
As long as they are uniform it's ok but "view" makes more sense
