### ISSUE TITLE
Back button in the settings doesn't work from the first try

### ISSUE THREAD

**Issue by Tester09** [files-community/Files#2866]
**Describe the bug**
When I open the settings I can't go back with one click on the back button. This requires 2-4 clicks

**To Reproduce**
1. Go to 'settings'
2. Click on the 'back' button
3. Repeat until success

**Expected behavior**
Back button should work with one click

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 2004 20279.fe]
 - App version: [v1.0]

**Comment by gave92** [comment]
Merging with #2810
