### ISSUE TITLE
Hold Shift/Ctrl to change file copy/move behavior

### ISSUE THREAD

**Issue by Tech-How** [files-community/Files#2869]
**Is your feature request related to a problem? Please describe.**
I think it is easier to drag files to perform copy/move operations. But when I drag files across drives, the operation is always "copy". And when I drag files to locations on the same drive, the operation is always "move".

**Describe the solution you'd like**
Just like Windows Explorer, I would appreciate it if when you held the shift key while dragging a file, it would move it. And if you hold the Ctrl key while dragging a file, it would move it.

**Describe alternatives you've considered**
I would normally have to press Ctrl+C or Ctrl+X, then move to that location to paste it. Holding shift/ctrl works better for me.

**Additional context**
Windows 10 Version 20H2 (OS Build 19042.685)

Files:
App Version: 0.23.1.0

**Comment by gave92** [comment]
Thanks for this suggestion. Merging with #1396

**Comment by Fa310tx** [comment]
I would like to point out that if you drag a file to another tab (even if it's a different drive), it will move the file.
That does not conform to the normal Windows move/copy functionality where a different drive is copy.
That was the behavior that I was expecting.

I did not realize that the modifier keys were options with File Explorer (as Tech-How mentioned).
I would not recommend changing the default behavior of just dragging files, though, as move within the same drive and copy to another drive is standard (and in my case) assumed.
Thanks...
JJ
