### ISSUE TITLE
Bug report: Item selection count is not displaying on status bar in any of the GridView layouts

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#2872]
**Describe the bug**
Status information for the selection count or item size is not being displayed on the status bar in the grid view layout modes.

**To Reproduce**
1. Go to any directory with items
2. Set the layout mode to a grid view layout
3. Click or select any item

**Expected behavior**
The expected behavior would be to display the correct information on the status bar.

**Comment by gave92** [comment]
Correct if I'm wrong, this only happens if you change layout right? If the folder is already in GridView then it works.
