### ISSUE TITLE
right-click menu

### ISSUE THREAD

**Issue by wycnet** [files-community/Files#2874]
Why did the latest version of the right-click menu turn gray?

**Comment by gave92** [comment]
Is this consistent? Or restarting the application fixes this?

**Comment by Jaiganeshkumaran** [comment]
Yes I have noticed this issue in WinUI menu flyout. You can try restarting your PC

**Comment by yaichenbaum** [comment]
Thanks again for your feedback.

_Since we didn't hear from you on this topic for 4+ days, we'll assume everything is worked out and close this feedback item. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this._
