### ISSUE TITLE
Duplicate items in SMB drive after "Cache files and folders for better performance" enabled

### ISSUE THREAD

**Issue by EdiTurn** [files-community/Files#2878]
**Describe the bug**
While "Cache files and folders for better performance" is enabled (seems default on), the file/folder list in a mounted SMB drive will duplicate after every refresh. 

**To Reproduce**
1. Enable "Cache files and folders for better performance"
2. Open a mounted SMB drive
3. refresh

**Screenshots**
![屏幕截图 2021-01-07 162642](https://user-images.githubusercontent.com/5492805/103869421-3ae98180-5105-11eb-91bb-765572cae3c6.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 21286
 - App version: 1.0.0.0

**Comment by gave92** [comment]
@jakoss could you take a look at this?

**Comment by jakoss** [comment]
@gave92 At first glance i think there's problem with equality check in OrderFiles function:
![image](https://user-images.githubusercontent.com/3933348/103878806-327a5200-50d7-11eb-8f74-64b2056c5e12.png)

I'll debug this in spare time

**Comment by jakoss** [comment]
@gave92 At a first glance i think that's an issue with loading files via `AddFileAsync`. It adds file by file without clearing `_filesAndFolders` first (it was cleared earlier before, but it got populated with cache). I think it might be necessary to list files to temporary table and after loading display them at once
