### ISSUE TITLE
Unable to eject drives while open

### ISSUE THREAD

**Issue by Tech-How** [files-community/Files#2884]
**Describe the bug**
When a removable drive is connected and opened in the Files app, right-clicking it in the sidebar displays an error message. (Screenshot attached.)

**To Reproduce**
1. Connect a removable drive.
2. Open it in the Files app.
3. Right-click on it in the sidebar.
4. See error.

**Expected behavior**
I think what should happen, is when you eject it this way it could automatically return to the home screen, and then eject the device.

**Screenshots**
![image](https://user-images.githubusercontent.com/76794507/103802216-cdfabc80-501c-11eb-9b1f-65e59720f2fc.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Version 20H2 (OS Build 19042.685)
 - App version: 0.23.1.0

**Additional context**
Yes, this issue has occurred ever since you added the option to eject removable drives.

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5777333/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5777334/debug_fulltrust.txt)

**Comment by Josh-65** [comment]
Meerging with #9560
