### ISSUE TITLE
Allow displaying deletion date in recycle bin and sorting by it

### ISSUE THREAD

**Issue by C0ffeeCode** [files-community/Files#2885]
**Is your feature request related to a problem? Please describe.**
I want to restore recently deleted files, but the recycle bin view does not allow to view or sort by deletion date.

**Describe the solution you'd like**
Show deletion date in recycle bin and allow sorting by it.

**Describe alternatives you've considered**
Using the regular Windows Explorer.

**Comment by yaichenbaum** [comment]
@C0ffeeCode This issue sould be resolved with #2892.
