### ISSUE TITLE
Add ability to search by date, size or other file property

### ISSUE THREAD

**Issue by 8888markmax** [files-community/Files#2888]
**Describe the bug**
I am not a programmer. Rather, a simple user. I was trying to use the search feature to search for a file within a certain date range (something I cannot seem to do with Windows 10 file explorer no matter how hard I try or how many advices I read). I do not see any options in the Search feature, except for typing in a name. Where are the Search features, such as, as I mentioned, date-range search? Thank you!

**Comment by d2dyno1** [comment]
Please don't write description in title, use the template provided

**Comment by gave92** [comment]
@8888markmax thanks for this report. I took the liberty of moving your description from the title of the issue to the proper place

**Comment by gave92** [comment]
@8888markmax what you suggest should be already possible. You can search for files modified in a date range typing in the searchbox e.g.:
`date:05/11/2020..08/01/2021`
