### ISSUE TITLE
Bug report: Opening the properties window from the sidebar causes multiple windows to pop up

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#2891]
**To Reproduce**
1. Right click an item on the sidebar
2. Click on 'properties'
3. See error

**Expected behavior**
The expected behavior is for only one window to open.

**Desktop (please complete the following information):**
 - App version: [v1.0]

**Comment by gave92** [comment]
Is this still an issue on master after #2867?

**Comment by yaichenbaum** [comment]
> Is this still an issue on master after #2867?

Yes, I tested with the latest in `master`.
