### ISSUE TITLE
Automatically switch to grid mode when the majority of items are photos

### ISSUE THREAD

**Issue by Tech-How** [files-community/Files#2893]
**Is your feature request related to a problem? Please describe.**
When I open a folder that contains mostly pictures, I wish I didn't have to manually switch to grid view.

**Describe the solution you'd like**
It would be helpful if when the majority of items in a folder (like with an exception of 5 or something) were pictures, the layout could automatically switch to the small grid view and back again when you exit.

**Describe alternatives you've considered**
I would change it myself each time I enter/exit.

**Additional context**
Windows 10 Version 20H2 (OS Build 19042.685)

Files:
App Version: 0.23.1.0

**Comment by nathanielcwm** [comment]
Windows Explorer also marks such folders with a tag. You might be able to read that tag.

**Comment by d2dyno1** [comment]
Ok!

**Comment by d2dyno1** [comment]
Check out #3526

**Comment by yaichenbaum** [comment]
This feature was implemented with #3526.
