### ISSUE TITLE
Some previews of pictures don't show in grid view

### ISSUE THREAD

**Issue by Tech-How** [files-community/Files#2894]
**Describe the bug**
When you switch to grid view, some previews of files don't show. Instead, there is a blurry picture of the default Windows file icon. (Screenshot included below)

**To Reproduce**
1. Open a folder that contains pictures.
2. Switch to grid view. (It doesn't matter which size.)
3. Notice how some files do not have a preview.

**Expected behavior**
I would expect all of the files to have their appropriate thumbnails.

**Screenshots**
![image](https://user-images.githubusercontent.com/76794507/104032072-a3833d80-519b-11eb-9e82-43e528be93e8.png)
![image](https://user-images.githubusercontent.com/76794507/104032262-e9d89c80-519b-11eb-8258-8d41ebe02b2a.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Version 20H2 (OS Build 19042.685)
 - App version: 0.23.1.0

**Additional context**
This also applies to almost any file. Sometimes refreshing fixes it, but most of the time it does not. This seems to only occur when the mode is switched while the app is already running. If the grid view mode it set by default when the app opens, the issue is not present.

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5787935/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5787937/debug_fulltrust.txt)

**Comment by gave92** [comment]
Thanks for opening this feedback item. This issue has been resolved in the development branch and the fix will ship with Files v1.0
