### ISSUE TITLE
Show system folders icons

### ISSUE THREAD

**Issue by Senliast** [files-community/Files#2895]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Please add option to take system folder icon as folder icon. Because, i for example, have a custom icons theme installed, and the custom icons for all files are visible in the Files app, but for folders there are default folders icons from the Files app visible. Could you add a toggle to use system folder icon, so that if users have custom icons installed, custom folder icons are visible too?

**Describe alternatives you've considered**
None

**Additional context**
Latest app Version from MS Store, latest Windows 10 20H2 Build.

**Comment by duke7553** [comment]
@Senliast We don't have plans to support custom modifications to your Windows theme at this time, but I'll leave this open to see if there's a better way we can load folder icons.

**Comment by yaichenbaum** [comment]
@Senliast Files should already load custom icons, what version of Files do you have?

**Comment by Senliast** [comment]
@yair100 yes it does, but not the custom icons of the folders. The lastest version from MS Store.

**Comment by yaichenbaum** [comment]
@gave92 Can you check this on your end when you get a chance?

**Comment by Senliast** [comment]
P.S. the custom folders icons will be installed by patching imageres.dll and imageresx86.dll so i think it would be enough if the app just uses the default system folder icon, like it does for files.

**Comment by gave92** [comment]
@yair100 currently we show custom icons for folder only if the icon file is outside the c:\windows folder. This is to avoid showing the standard folder icons instead of the Files one.

**Comment by gave92** [comment]
Next version will use system icons for folders.
