### ISSUE TITLE
Files doesn't obey custom folder icon settings.

### ISSUE THREAD

**Issue by nathanielcwm** [files-community/Files#2896]
**Is your feature request related to a problem? Please describe.**
When you manually change the icon in Windows Explorer and open said folder in Files it just shows the generic folder icon instead of the custom icon.

**Describe the solution you'd like**
Ability to obey custom folder icons by default / a toggle to enable using them.

**Describe alternatives you've considered**
Having the option to also manually change the icon in Files.

**Additional context**
#2895 looks related but appears to be about system wide icon change rather than folder level changes.

Windows Explorer behavior:
![image](https://user-images.githubusercontent.com/22572406/104087166-b7f93000-5298-11eb-9fce-d72c09fc046d.png)

Files behavior:
![image](https://user-images.githubusercontent.com/22572406/104087173-c2b3c500-5298-11eb-8931-7f56d79fb3ad.png)

How Explorer handles changing icons:
![image](https://user-images.githubusercontent.com/22572406/104087187-d9f2b280-5298-11eb-9dcf-c96394ce5d1e.png)
![image](https://user-images.githubusercontent.com/22572406/104087189-de1ed000-5298-11eb-9234-035dc4134fe0.png)

**Comment by gave92** [comment]
Yeah, atm Files only loads a custom folder icon if the icon is outside the `C:\Window` folder

**Comment by nathanielcwm** [comment]
#2899 appears to be about the same thing.

**Comment by duke7553** [comment]
![image](https://user-images.githubusercontent.com/20365014/113971498-e5596980-9806-11eb-909b-9f722fada258.png)
UI is very unfinished right now, but I'm planning to finish something like this which allows for getting values from desktop.ini and setting custom icons from a dll or ico file.

This feature will also include an easy way to restore the default icon.

**Comment by yaichenbaum** [comment]
@duke7553 This change isn't going to fix this issue unless you start loading icons from the Windows folder as well.

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
