### ISSUE TITLE
A lot of empty space in settings pages when viewed on large monitor

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#2898]
![image](https://user-images.githubusercontent.com/17484252/104102717-73709300-529e-11eb-9805-e33addeb6a91.png)

I think the image says it all. Right now I am working on an 34" 2560x1440p monitor and the settings waste tons of space.

Would it be possible to have an alternate view once the screen exceeds a certain size? This issue has bugged me with most UWP apps in the past.

**Comment by yaichenbaum** [comment]
@R3voA3 There are plans to add tips and useful information on the settings page in the future but even with that, there will still be a lot of empty space. One possibility is to display a content dialog for the settings page on large displays.

**Comment by R3voA3** [comment]
What about dropping the list on the side on larger display and put the options into a gridView?

**Comment by Jaiganeshkumaran** [comment]
I told Yair already to use a dialog or panel but the design trend seems to be to use full-screen settings pages which waste too much space even if you add content on the right like links. Take the settings app as an example. In my app, I use multi-column layouts on larger displays but don't know whether Files would accept it.

**Comment by Jaiganeshkumaran** [comment]
Instead of separate pages with a navigation view, we could use a multi-column layout will all settings on one page

**Comment by R3voA3** [comment]
> Instead of separate pages with a navigation view, we could use a multi-column layout will all settings on one page

Yes, I like the idea. I have seen that in some other app and it's much better

**Comment by mdtauk** [comment]
Another option could be to display Settings in a pane when the window is particularly wide.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5077.
