### ISSUE TITLE
Respect folder configurations by reading desktop.ini metadata

### ISSUE THREAD

**Issue by Starz0r** [files-community/Files#2899]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Desktop.ini is the invisible file that tells Explorer how to display the content in that folder, and it only appears if you change the default settings of folders. However, by default in newer installations of Windows, folders `Desktop`, `3D Objects`, `Documents`, `Downloads`, `Music`, `Pictures`, `Videos`, and the `Recycle Bin`, all have their own optimized desktop.ini configuration.

What does this mean exactly? Let's take `Music` for example, instead of displaying the default `Name`, `Date modified`, `Type`, and `Size`, it'll show more relevant info like `Name`, `Song Number`, `Title`, `Contributing artists`, and `Album`.

We seem to have non-compliant partial support in the form of https://github.com/files-community/Files/pull/2892 and https://github.com/files-community/Files/pull/2094. Both of these implementations ask the shell for information on the folder, when in reality, we should just be reading the metadata from the desktop.ini file when available.

**Additional context**
More information on desktop.ini can be found [here](https://docs.microsoft.com/en-us/windows/win32/shell/how-to-customize-folders-with-desktop-ini).

**Comment by gave92** [comment]
Hi @Starz0r thanks for this suggestion. The `desktop.ini` contains a lot less info that you may think.
Stuff like display mode, sort direction, shown columns, etc. is not stored (anymore?) in `desktop.ini` but in the registry under the `Shell\Bags` keys. The only interesting thing remaining in the ini file it's pretty much only the custom icon.

For example this is what I get from `deskto.ini` in Music (lacalized name and icon only):
```
[.ShellClassInfo]
LocalizedResourceName=@%SystemRoot%\system32\windows.storage.dll,-21790
InfoTip=@%SystemRoot%\system32\shell32.dll,-12689
IconResource=%SystemRoot%\system32\imageres.dll,-108
IconFile=%SystemRoot%\system32\shell32.dll
IconIndex=-237
```

**Comment by Starz0r** [comment]
@gave92 It seems that Microsoft may not have documented this as much as I thought. Creating a folder optimized for `Documents` created a `desktop.ini` file that looks like this:
```ini
[ViewState]
Mode=
Vid=
FolderType=Documents
```
If I change it back now the file exists permanently like this:
```ini
[ViewState]
Mode=
Vid=
FolderType=Generic
```

Looks like most of the technical-ly useful information is stored in the Registry like you said. I do still think exposing this information might be useful, but as it stands, I do no longer think reading `desktop.ini` would give as many useful gains as I previously thought.
