### ISSUE TITLE
Toggle for Bulk Selection

### ISSUE THREAD

**Issue by szaimen** [files-community/Files#290]
**Is your feature request related to a problem? Please describe.**
The current Selection UX isn't working without a keyboard and is therefore not touch-optimized: So you cannot make a custom selection of folders/files with only touch input.

**Describe the solution you'd like**
Maybe you could add a "Bulk" button to the "Layout" Ribbon Section to enable Bulk selection.

**Describe alternatives you've considered**
After Pressing the button every file/folder, that you touch is getting added or removed from the selection with one click. Additionally, if https://github.com/duke7553/files-uwp/issues/94 was implemented, you than could also add a bunch of files to the selection which would be very handy. 

**Additional context**
Maybe if you already have selected a few files/folders and use the rectangle to select the same files and one additional one, the currently selected files remain selected + the additional one. Only if you select only files/folders with the rectangle, that are already selected, they should get removed from the current selection imo.

**Comment by yaichenbaum** [comment]
I feel like #94 would address the issue about touch input. One of the things we are doing while creating this app is rethinking which features are needed for a file explorer app that is both powerful and simple. Just because a feature is in File Explorer it does not mean that we will add it to Files, in this case if the selection rectangle solves the problem on hand I don't think we need an extra option.
In any case thank you for bringing this up and regardless of if your ideas are implemented or not please keep them coming! They are helping us understand the direction this app needs to go in and is reminding us of all the small details that need to be addressed.

**Comment by szaimen** [comment]
Actually this feature isn't implemented into file explorer to my knowledge.
It is something I thought about, that would make sense and would improve the UX for selecting files with touch input imho.

**Comment by yaichenbaum** [comment]
How about check boxes at the left of every file? Once you check one then you will be able to tab on any file to select or deselect it.

**Comment by szaimen** [comment]
> How about check boxes at the left of every file? Once you check one then you will be able to tab on any file to select or deselect it.

That sounds like another good way to do this. If you like this better, I am okay with it.

But I think my Proposal is design-wise cleaner (but maybe not UI- or UX-wise), because it doesn't need the checkboxed at the left on every file/folder.

**Comment by yaichenbaum** [comment]
For a cleaner design how does it sound if the check boxes are hidden until the mouse is near by or someone touches near there?

**Comment by szaimen** [comment]
That sounds already better to me but then you would be in the situation of having an empty column between the navigation bar on the left and the title column...

**Comment by szaimen** [comment]
> How about check boxes at the left of every file? Once you check one then you will be able to tab on any file to select or deselect it.

What about putting the check boxes at the right of every file. This would solve the empty column problem.

It think combined with this idea:

> For a cleaner design how does it sound if the check boxes are hidden until the mouse is near by or someone touches near there?

It would be kind of perfect. Also on the right it is probably better reachable for most people (that are right-handed).

**Comment by EasyRhinoMSFT** [comment]
This feature is also an accessibility improvement for impaired mouse users, so don't focus solely on the touch scenario. Windows Explorer provides an option for displaying checkboxes at the left side of each item.

**Comment by yaichenbaum** [comment]
@EasyRhinoMSFT You brought up a good point about accessibility, Files will probably include this as an option, and if possible, we will enable it by default when the device has a touch screen.

**Comment by Barina** [comment]
I have an alternative suggestion.

What about not using checkboxes at all? 
We can use the file\folder icon as our "selection mode" trigger.

So when we mouse click or touch the icon of the item it will start a selection mode where we can select\deselect other items by simply clicking them or their icon and to deselect everything we can click an empty area or deselect the last selected item.

This way we can also click and drag from the icon to quickly select (additional) multiples (just like how the rectangle selection works).
The rectangle selection mode usability won't change.
To grab the items we can drag them from their name (or other parts that is not the icon).

I did something similar for an old WPF application I wrote years ago.
I thought about this usability while using the "Details view" layout but I think it can work on other layouts too.

What say you? :)

**Comment by yaichenbaum** [comment]
> We can use the file\folder icon as our "selection mode" trigger.

The issue with that is that it's not as intuitive as a check box and it can be confusing if someone tries opening a file only to see something else happen.

**Comment by Barina** [comment]
I agree, but only if it'll be shipped pre-enabled with Files. which I assume isn't the case..?

**Comment by yaichenbaum** [comment]
If possible, it will automatically be turned on for devices with touch displays, otherwise, you will be able to turn it on/off from the settings.

**Comment by Barina** [comment]
Yes and it's also possible to show a mini guide popup with animation\video when the feature is automatically turned on.

**Comment by EasyRhinoMSFT** [comment]
I'd love to see a prototype of this if someone has time...

**Comment by Barina** [comment]
> I'd love to see a prototype of this if someone has time...

I tried to find something in Google search but there's something very similar actually in Google Photos Android app.
Long click a picture there and then drag to select others.

**Comment by winston-de** [comment]
@yaichenbaum I intend to start working on this, can you please assign me?

**Comment by winston-de** [comment]
I think the best way to approach this is to have a toggle for multiselect in the selection flyout.
Here's a mockup I made with the GridView.

https://user-images.githubusercontent.com/59544401/105762228-fd5c6500-5f08-11eb-81f4-8c6856d14e4c.mp4

Please let me know what you guys think of this.

**Comment by szaimen** [comment]
> Please let me know what you guys think of this

Looks good to me, I like it! 👍

**Comment by EasyRhinoMSFT** [comment]
@winston-de is that a persistent setting? I always need multi-select enabled and I definitely don't want to have to enable it every time. That's why Windows has this as a global setting.

**Comment by winston-de** [comment]
@EasyRhinoMSFT At the moment, it is not, however I could add a setting to enable multiselect by default. Would that work?

**Comment by yaichenbaum** [comment]
> @EasyRhinoMSFT At the moment, it is not, however I could add a setting to enable multiselect by default. Would that work?

That is how we envisioned this feature.

**Comment by winston-de** [comment]
@yaichenbaum

> That is how we envisioned this feature.

I was a bit confused about the previous discussion. Would there be a way to temporarily switch modes (to multiselect mode, or vice versa)?
My reasoning for not making the toggle in the flyout persistent (as an app setting) is that it would provide a way for the user to quickly enable multiselect when they needed it. For example, if they had a tab open where they were moving a bunch of files around, they could switch to multiselect without having it enabled for the rest of their tabs.

> It would be a bonus if this feature was on by default for devices with a touch display.

My only concern with this is that having a touch screen does not mean the device is being used as a tablet. For example, most of the time I use my touch device in a "hybrid" sort of manner. If I want to select multiple files, I hold the Ctrl key while tapping the files with my finger. I think a better solution would be to enable multiselect when no physical keyboard is detected, and the device has a touch screen. Windows has similar features to this, like making taskbar icons bigger and increasing the size of buttons in Explorer when no keyboard is detected.

**Comment by yaichenbaum** [comment]
@winston-de When I was thinking about how to implement this feature, the idea I had in mind was to have a setting where the user can turn on/off this feature. The default setting would be to keep this turned off, however, on touch devices, the default setting will be turned on. You mentioned a good point where some users have a touch display but prefer the mouse + keyboard option, in a case like that, the user can turn off this setting.
I don't think there should be a temporarily toggle, I am pretty sure the users either like this feature and want it to always be available, or they don't find a use for it and just want it out of the way.

**Comment by winston-de** [comment]
@yaichenbaum I think we both might be thinking of different things.
I was thinking that clicking any part of the file selects it. That's why I was proposing a temporary toggle, since it would interfere with normal usage.
You're thinking about having a smaller clickable region to select, correct?

**Comment by yaichenbaum** [comment]
@winston-de Correct, I am talking about a little check box next to every item.

**Comment by winston-de** [comment]
@yaichenbaum Ahhhh, glad were on the same page now.

My prototype used the default GridView multiselect, which selects an item when you click it.
It will take me a while to make a custom selection box.

**Comment by winston-de** [comment]
@yaichenbaum I guess my only concern is that the little checkmarks can be a real pain to press. Maybe it's just me though cause I have big fingers.

**Comment by szaimen** [comment]
Hm... I still think that [this proposal](https://github.com/files-community/Files/issues/290#issuecomment-767099900) is better than small checkboxes next to each item. 
IMO, those small checkboxes next to each item just don't look good and aren't good to use, either.

**Comment by yaichenbaum** [comment]
@szaimen @winston-de Once you toggle one of the check boxes, I think you can select/deselect an item just by clicking on it.

**Comment by szaimen** [comment]
> @szaimen @winston-de Once you toggle one of the check boxes, I think you can select/deselect an item just by clicking on it.

Yes but showing a checkbox next to each item only for beeing able to toggle one of the checkboxes once to activate this feature doesn't seem like the best idea in terms of UI (and UX), IMO.

Thats why I voted for a toggle instead of a checkbox next to each item from the beginning on and thats why I still think that [this proposal](https://github.com/files-community/Files/issues/290#issuecomment-767099900) is superior.

**Comment by yaichenbaum** [comment]
I just noticed the proposal, that looks good to me.

**Comment by szaimen** [comment]
> There should still be a way to multiselect items without going through a menu as it seems like extra steps and can be annoying for users who use touch screens.

I would suggest adding this option on tablets either in the top menu bar or in the bottom menu bar:
![image](https://user-images.githubusercontent.com/42591237/105924566-d1db9680-603e-11eb-980a-edc839bbcd79.png)
Most likely the bottom bar is better...

**Comment by winston-de** [comment]
@yaichenbaum @szaimen What if there was an option to "pin" the multi select button to the status bar?

**Comment by winston-de** [comment]
@yaichenbaum I remember you saying something about adding toolbar customization. Maybe an option to pin multiselect could be a part of that?

**Comment by szaimen** [comment]
> @yaichenbaum @szaimen What if there was an option to "pin" the multi select button to the status bar?

Either this or just show it on touch devices in the bottom menu bar and on other devices hidden in the selection menu.

**Comment by winston-de** [comment]
> Edit: or just hide it on non-touch devices completely? (I am not sure if it is of any use on non-touch devices)

I'd say it's better to provide an option. The user could have a drawing pad, prefer being able to click to select without holding down the control key, or some other reason they would want to pin a multiselect option.

**Comment by yaichenbaum** [comment]
@winston-de Do you want to remove the setting now and turn on the feature by default?

**Comment by winston-de** [comment]
@yaichenbaum Yeah, probably. I'll make a pr to do that.

**Comment by yaichenbaum** [comment]
@szaimen This feature is implemented in `main`.
