### ISSUE TITLE
Enabling Dual Pane mode occasionally removes opening items in new tabs from context menu

### ISSUE THREAD

**Issue by generalguy41** [files-community/Files#2902]
**Is your feature request related to a problem? Please describe.**
Not related to a problem. Enabling Dual Pane mode should not remove opening items in new tabs from context menu. 

**Describe the solution you'd like**
Should just be a new option along side "Open in New Tab" and "Open in New Window".

**Describe alternatives you've considered**
Middle clicking the folder still allows opening in a new tab.

**Additional context**
- OS Version: Windows 10 2004 21286.1000
- App version: v1.0.0.0

**Comment by gave92** [comment]
@generalguy41 which context menu are you referring to? Could you post a screenshot showing the issue?

**Comment by generalguy41** [comment]
@gave92 Right click context menu. There is no more option for opening in new tabs/windows.
![image](https://user-images.githubusercontent.com/8879244/104132107-39100000-5349-11eb-9a22-411d1f39137c.png)
Upon further testing, it seems that when you enable Dual Pane mode the first time, all the right-click menu options are there, but upon restarting they disappear. The reverse seems to be happening too where if I disable Dual Pane mode, there are no "Open in ..." options at all until restart.

**Comment by generalguy41** [comment]
It seems to be sporadic, as I can't reproduce it consistently. Sometimes it will work, others it won't.

**Comment by generalguy41** [comment]
Going to close this for now as I can't seem to reproduce regularly in v1.2.2.0. I'll reopen if I see it happen again.
