### ISSUE TITLE
Add support for canceling a file operation

### ISSUE THREAD

**Issue by lionnesquaer** [files-community/Files#2904]
**Describe the bug**
Canceling Copy/Moving file operation from "Ongoing Task Menu" dont work, and continues even then Files app closed.

**To Reproduce**
1. Copy/Move any file
2. Click "X" in the ongoing task menu
3. You will see that current task in menu is close, but copy/move files operation continues. Closing Files app also dont canceling operations.

**Expected behavior**
Fix canceling copy/move files operations

**Screenshots**
nothing to shot sorry

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H1 19042.685
 - App version: v1.0

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?
Yes

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5793180/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5793181/debug_fulltrust.txt)

**Comment by yaichenbaum** [comment]
@duke7553 The "X" button is currently just a button to dismiss the item in the status center, what are your thoughts about repurposing the button to cancel the operation?

**Comment by pavvelb** [comment]
@yair100 Congrats with 1.0 version! 
Cant even imagine, i dont have UI/UX design exp. Need to be Stop and Cancel button, like native windows explorer transfering files dialog.
Also please, take a look what about percantage status meter in the ongoing task menu, it is dont work.

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
