### ISSUE TITLE
Video preview in settings page

### ISSUE THREAD

**Issue by d2dyno1** [files-community/Files#2905]
**Is your feature request related to a problem? Please describe.**
As descibed in #2898, the settings page contains a lot of unused free space. I consider this as a missed opportunity.

**Describe the solution you'd like**
A short generic video clips describing what a feature does. Those will feature 3-8s short videos of what the setting does - Just click on a setting and a preview video will display on the right side of the screen.

**Describe alternatives you've considered**
A description, but it is very boring.

**Additional context**
This is nicely executed by the OneLocker app:

https://user-images.githubusercontent.com/53011783/104134060-a6428600-5387-11eb-990a-4adf8e9ca401.mp4

(But without the description 😀)

**Comment by d2dyno1** [comment]
@yair100 What are your insights on this?

**Comment by yaichenbaum** [comment]
This issue is no longer relevant with #5077.
