### ISSUE TITLE
Add an option to choose default folder layout

### ISSUE THREAD

**Issue by rafal06** [files-community/Files#2907]
## **Is your feature request related to a problem? Please describe.**
I prefer the grid layout over list view and it's very frustrating when I have to manually set it to every new folder I visit

## **Describe the solution you'd like**
I would love to have ability to choose default layout of folders that I didn't manually set view.

## **Additional context**

https://user-images.githubusercontent.com/70489677/104137353-4904ff80-539c-11eb-91f7-a7544d703a20.mp4

I'm using Windows 10 in S mode, version 20H2.
Files version 1.0.0.0

**Comment by gave92** [comment]
You can already do that but it's not super intuive:
- In Settings > Files and folders, turn *off* "Enable individual preferences for individual directories"
- Go to any folder and set your desired view mode
- In Settings > Files and folders, turn back on "Enable individual preferences for individual directories"
