### ISSUE TITLE
Refreshing folders within mounted network drives causes visible items to duplicate

### ISSUE THREAD

**Issue by KCS007** [files-community/Files#2908]
**Describe the bug**
All visible folders/files within a mounted network drive are duplicated upon refresh of the directory. Items are retained even after browsing to other network or local folders. It seems the app fails to purge previous on-screen entries when refreshing the contents of a network folder.

**To Reproduce**
1. Map network drive through traditional explorer.exe
2. Browse to any folder within the new network drive in Files UWP
3. Refresh the folder once items have loaded

**Expected behavior**
Refresh items

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: 
Edition	Windows 10 Pro Insider Preview
Version	2004
Installed on	‎12/‎11/‎2020
OS build	21277.1000
Experience	Windows Feature Experience Pack 220.32303.0.2003

 - App version: v1.0.0.0

**Additional context**
Occurs after application restart. Does not occur on my desktop with v0.23.1.0

**Log file**
"Open Log Location" button is non-functional.

**Comment by gave92** [comment]
Try disabling "Cache files and folders for better performance" option in Files settings

**Comment by tgrelka** [comment]
I can confirm this issue and also report that, for me, disabling cached files fixes this behaviour and displays only a single entity for each folder present in a network drive.

**Comment by gave92** [comment]
@tgrelka thanks for the feedback, this has been fixed in #2880. I'll leave this open till confirmation from @KCS007
