### ISSUE TITLE
Security tab feature

### ISSUE THREAD

**Issue by Seraphim7** [files-community/Files#2909]
**Is your feature request related to a problem? Please describe.**
My feature is not related to a problem

**Describe the solution you'd like**
I would like to see the security menu tab on the properties page on the context drop down menu.

**Describe alternatives you've considered**
I have not considered any alternatives.

**Additional context**
![image](https://user-images.githubusercontent.com/22435977/104141278-bf890980-536a-11eb-9f97-a7a93177c134.png)

**Comment by XPoppyX** [comment]
Duplicate of #1647
