### ISSUE TITLE
Programs open in background from contextual menu

### ISSUE THREAD

**Issue by chdelacr** [files-community/Files#2911]
**Describe the bug**
When the user selects an option from contextual menu that will basically open the file/folder in a selected app, or just perform an action under a directory, the program starts in background and the user needs to select the new program window in order to see it. In Windows File explorer, any program opens in foreground from contextual menu.

**To Reproduce**
1. Go to any file/folder or a blank place under a directory
2. Right click on it
3. Select a contextual menu entry to open the file/directory, or just to perform an action under a directory
4. See bug

**Expected behavior**
The program selected to perform an action from contextual menu should open in foreground.

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.685
 - App version: v0.23.1.0

**Additional context**
This happens no matter what file/folder is right-clicked.

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5794232/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5794233/debug_fulltrust.txt)

**Comment by gave92** [comment]
#985 is back
