### ISSUE TITLE
Closing settings requires an additional click each time

### ISSUE THREAD

**Issue by tgrelka** [files-community/Files#2912]
**Describe the bug**
When opening the settings window, closing it requires an additional click each time.
So at first, it behaves like expected, closing when clicking the arrow in the top left corner.
Once you open the settings again, you need two clicks to close the window, next time three etc. Tested up to 11 clicks.

**To Reproduce**
1. Open Settings.
2. Click on arrow in top left corner.
3. Open settings again.
4. Click on arrow in top left corner => Settings don’t close.
5. Click on arrow again => Settings now close.
6. Repeat as you see fit, needs one more click each time.

**Expected behavior**
Settings should close on first click of back (arrow) butten.

**Desktop**
 - OS Version: Windows 10 Build 19042.685
 - App version: v.1.0.0.0

**Log file**
Nothing interesting here, just two lines about the app launch.

**Comment by gave92** [comment]
Fixed in #2867
