### ISSUE TITLE
Pressing 'back' arrow from any category in Settings brings you to 'Appearance' instead of closing 

### ISSUE THREAD

**Issue by tgrelka** [files-community/Files#2913]
**Describe the bug**
While doing some testing for #2912, I noticed that clicking one of the other settings categories (e.g. About) and then trying to close settings requires two clicks on the back (arrow) button.

**To Reproduce**
1. Go to Settings
2. Click on 'About'
3. Click on arrow in top left corner.
4. Get brought back to 'Appearance' instead of closing settings.

**Expected behavior**
Since all the categories are in the same level of hierarchy, I would expect the back button to close the settings window instead of taking me to the first item in the list.

**Additional info**
I also tried selecting multiple items before pressing the arrow button, but wasn’t brought through them in a sort of history mode (like, pressing About, then Widgets, I thought, maybe pressing the arrow will bring me to Widgets first, before going to Appearance), instead I was brought back to the first item in the list each time.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 19042.685
 - App version: v1.0.0.0

**Log file**
Just the application launch, no exceptions.

**Comment by gave92** [comment]
Fixed in #2870
