### ISSUE TITLE
MD5Hash Error

### ISSUE THREAD

**Issue by rounk-ctrl** [files-community/Files#2914]
**Describe the bug**
MD5Hash doesn't display when you go to properties and click Details and then click General.

**To Reproduce**
1. Open app
2. Right Click on Any File (not folder)
3. Open Properties
4. Go to Details in Properties.
5. Then go to General.
6. See Error

**Expected behavior**
MD5Hash to display instead of a blank line

**Screenshots**
![Reference](https://user-images.githubusercontent.com/70931017/104157724-2955f180-5405-11eb-9da2-197e68b275dd.gif)

**Desktop (please complete the following information):**
 - OS Version:  Windows 10 20h2 19042.685
 - App version: v1.0

**Comment by Josh-65** [comment]
Should this be closed since MD5Hash isnt included anymore
