### ISSUE TITLE
Replacing Windows Explorer

### ISSUE THREAD

**Issue by Loldogs** [files-community/Files#2915]
**Is your feature request related to a problem? Please describe.**
I have tried the methods to try replacing Windows Explorer with the Files app, including the method mentioned in the [wiki](https://files-community.github.io/docs/#/articles/replace-file-explorer). 

**Describe the solution you'd like**
If there are any other method(s) or a script I could use to replace Windows Explorer with the Files app.

**Describe alternatives you've considered**
I tried this [method](https://www.winhelponline.com/blog/winkey-e-shortcut-target-change/), but it didn't work for me. I have also looked at similar issues, but they've all been redirected to the wiki link. I have also tried using the Files app as is without the registry tweak to replace Windows Explorer, but its a huge deal-breaker for me.

**Comment by yaichenbaum** [comment]
@Loldogs Can you share more information about what didn't work for you?

**Comment by Loldogs** [comment]
The method mentioned in the wiki to replace Windows Explorer with Files didn't work even after I restarted my computer, I pressed "my downloads" on my browser to test if it worked and it still opened Windows Explorer instead of Files.

**Comment by yaichenbaum** [comment]
@Loldogs Some browsers still point to File Explorer, which browser are you using that causes this issue?

**Comment by Loldogs** [comment]
Microsoft Edge (Chromium)

**Comment by astraelise** [comment]
> Microsoft Edge (Chromium)

@yair100, it doesn't seem like a browser issue, since the folder hyperlinks in the start menu and search when pressed opens Windows Explorer instead of Files and the control panel can still be launched. I must note that I'm using the microsoft store version.

**Comment by yaichenbaum** [comment]
@Loldogs We are working on updating the documentation on this to hopefully solve this issue.
