### ISSUE TITLE
Date (resp. time) of modification is (still) wrong

### ISSUE THREAD

**Issue by Ein-Tim** [files-community/Files#2917]
**I saw #836 and #773, these were closed since this should be fixed, but in version 1.0 I still see this wrong behaviour.**

**Describe the bug**
I'm using Windows 10 with German language and my time is set to UTC +01:00.
Now, when looking at the date of modification from files/folders I see that Files shows the wrong date of modification (it is one or two hours before the real time).

**Expected behavior**
Date of modification should be correct.

**Screenshots**
This is a screenshot form the System32 folder, on the left in the Windows Explorer and on the right from Files
![104209733-5ec50400-5432-11eb-8d0f-7c872e42e5ac](https://user-images.githubusercontent.com/67682506/104213683-ddbc3b80-5436-11eb-8c6f-4181dd514dc3.png)

**Desktop:**
 - OS Version: Windows 10 20H2 Build 19042.685
 - App version: 1.0.0.0 - 1.3.0.0

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5797166/debug.txt)

**Comment by kunalspathak** [comment]
+1

**Comment by Zakees** [comment]
+1

**Comment by PMExtra** [comment]
This issue is still in 1.3.0.0. I will look back later.

**Comment by PMExtra** [comment]
OK, I found this issue has been fixed in latest "main" branch.

**Comment by Ein-Tim** [comment]
@PMExtra 

So this will be fixed with the next release?

**Comment by PMExtra** [comment]
@Ein-Tim As it should be, but I couldn't find which commit fixed the problem.

**Comment by PMExtra** [comment]
@yair100 I couldn't find any commit that about this issue after tag 1.3. But it really has been fixed in master but 1.3 not.
Could you check why this happens? Then you can close this issue if it has been really fixed.

**Comment by Ein-Tim** [comment]
@PMExtra 

This is fixed if you choose "Application" in the "Appearance" settings, but if you set it to system, you'll see that the time still differs from the one shown in the explorer:

Having the time on my machine set to UTC +1, but seems like files is showing just the UTC time (or some other time, since the time sometimes differ more than one hour.

**Comment by PMExtra** [comment]
@Ein-Tim Thanks for your analysis. You are right! I will dig it later.

**Comment by yaichenbaum** [comment]
@Ein-Tim This issue should be resolved with #3776.

**Comment by Ein-Tim** [comment]
@yair100 

So this will be part of the next release, correct? 

@PMExtra 
Thanks for fixing!

**Comment by stevenbrix** [comment]
What release will this be in? I'm seeing this issue in 1.5.0.0

**Comment by yaichenbaum** [comment]
@stevenbrix It'll be part of the v2 release, we don't have any timeline on when that will though. But if you're up to it, you can join the preview flight.
