### ISSUE TITLE
List Layout Mode And Option To Define Size

### ISSUE THREAD

**Issue by Fa310tx** [files-community/Files#2920]
**Is your feature request related to a problem? Please describe.**
In normal File Explorer, I almost always use the List view.
It gives the ability to see the most files in a single screen.
Plus, I can select a file and see things like size or right-click and see additional properties.

When using a tablet, I like the Content view for similar reasons.
I would use the List view, but the items are just too small.
If you created a List view and gave the user the ability to choose a font size, that would be perfect.
Honestly, though, I think the font size you use with Detail is great.
It would probably suffice for desktop and tablet use.
I don't find it too big for desktop use and there is enough spacing that I think fingers would be ok.

You might ask why not just use the Tiles view.
Well, it arranges items from left-to-right and then top-to-bottom.
I prefer to arrange top-to-bottom and then left-to-right.
I guess an easier option might just be to give an arrangement option.
But, Tiles would be too big for desktop usage.
Again, definable font sizes are great.

**Describe the solution you'd like**
Something similar to File Explorer's List view.

**Describe alternatives you've considered**
Just sticking with Details will suffice, for now (or I just will continue using File Explorer).

**Additional context**
N/A

**Comment by yaichenbaum** [comment]
Merging with #2509.

**Comment by yaira2** [comment]
@Fa310tx thank you for your patience, I'm excited to share that a List View layout will be included in the next release.
