### ISSUE TITLE
Details View Size Field For Folders

### ISSUE THREAD

**Issue by lp-001** [files-community/Files#2921]
**Is your feature request related to a problem? Please describe.**
If running a daily/monthly etc backup it is handy to be able to easily compare the number of files in a folder to help ensure all files are being backed up and check that none are missing.

**Describe the solution you'd like**
When viewing the size column in the Details View it could be handy to be able to see the number of files in a folder in this column which is currently blank. This might read as '5 Files'.

**Describe alternatives you've considered**
Alternatively this could show the file size of the folder/files within it. If this was the case a user controlled option to switch between these would be best.

**Additional context**
Running app version 1.0.0.0

**Comment by yaichenbaum** [comment]
@lp-001 This is something we have looked at in the past and decided against implementing due to the performance issues involved. Calculating the size of folders requires a lot of processing power and it's the reason the file manager app on both Windows and Mac OS don't have this feature.
