### ISSUE TITLE
Custom Action Buttons Next to Directory Controls

### ISSUE THREAD

**Issue by lp-001** [files-community/Files#2922]
**Is your feature request related to a problem? Please describe.**
There are often frequent features that might be in context menu's that could be more difficult to use or slower to use in certain situations. For example: with mutliple files selected, or performing multiple rapid tasks on files in a folder.

**Describe the solution you'd like**
The option to define custom actions that could be shown as buttons to the right of the directory controls (back/forward, up and refresh). These range of actions this could include: Copy/Cut, Paste, New Folder/File, Rename, Open In Terminal, Properties.

**Describe alternatives you've considered**
Alternatively this area could be used to show context aware buttons depending what is selected or the types of files in a folder: 
- 'Pictures' folder could show the Layout button
- 'Music' & 'Videos' could show a play button that plays the file selected or first file in your default music player
- 'Recycle Bin' could show a button to empty the folder or restore
- External storage drives could show a button to safely remove the drive

**Additional context**
Using app version v1.0.0.0

**Comment by yaichenbaum** [comment]
> My original comment from #3883:
> 
> Seeing how the action bar below the address bar has a lot of free space, I think a redesign of the buttons and the overflow menu leads to usability improvements.
> 
> I tend to use New and New Pane quite often, not always reaching for the shortcuts though, especially since both are three-stroke-shortcuts. I’d suggest placing these buttons next to the Search and Toggle Preview Pane buttons.
> I’d also like to see the open in Terminal button there, I haven’t found a shortcut for that one yet.
> 
> I believe this can be improved even further: The New Tab and New Window buttons can stay in that overflow menu, for all I care. But given how the New Tab button is already placed at a different spot, one where it makes sense from a usability point of view - in the tab bar, maybe consider adding the/a Copy Location button to the addres bar, to the side of it or only show it when the bar is selected, like the clear button. Something like this is common practice in many web apps, even GitHub itself has this, if you click the green ↓Code button in any repository, any of the links will have a Copy To Clipboard action right next to them.
> 
> Overall, the overflow menu seems a bit all over the place right now, especially since the dual-bar design (address bar and action bar) leaves a ton of free room for two more buttons without adding much clutter.
> 
> I might suggest a smart overflow menu which places more and more of the options in the action bar as the window grows bigger / hides them as the window shrinks. That way, clutter will be low when the window is small, but usability will be improved as the window gets bigger.
> 
> The Toggle Preview Pane may make more sense down in the Display Options menu at the bottom of the window, and personally I’d have the search button at the very right, with the expanding search bar pushing the other items to the side or overlaying them.

@tgrelka I moved your comment here.

**Comment by tgrelka** [comment]
Thanks!

**Comment by CF-71** [comment]
My suggestion would also be to move the option-buttons (selection, display, panel, three-point menu) **and** the information "items / items select / tasks" into **ONE** line. This line then still has enough space for further buttons.

Whether this line/bar is then positioned, at the bottom or at the top, is certainly a matter of taste.

I think it's a waste of space to use two lines for so little information / buttons.
The second line would then be superfluous and the space could be better used for the display of folders and files (less scrolling).

**Comment by yaichenbaum** [comment]
We are looking into which actions should show in the toolbar, when you select a file or folder, would you prefer static items regardless of the file type e.g cut, copy, rename, open, delete. Or would you prefer the actions to change based on the item type? If the actions change based on the item type, can you provide some examples on what kinds of actions you would like for different item types?

**Comment by hiranmayd** [comment]
> When you select a file or folder, would you prefer static items regardless of the file type e.g cut, copy, rename, open, delete. Or would you prefer the actions to change based on the item type? If you prefer for the actions to change based on the item type, can you provide some examples on what kinds of actions you would like for different item types?

Yeah, I'd love the latter one, my idea is there have to be universal actions, copy, paste, delete, all these should be there regardless of the file type or context, maybe decide on what we want as universal ones, and then the remaining space will be occupied by context-aware or morphing actions, alternatively I'd love the user to have full control on this, so imagine if the user can set universal icons, how about a system where-in if I right-click an action on the bar, I get a chance to "pin" it.

**Comment by yaichenbaum** [comment]
@hiranmayd Can you provide some examples on what kinds of custom actions you would like for different item types?

**Comment by hiranmayd** [comment]
Maybe like rotate, edit for pictures, open in video editor for videos, something like that, one more thing I have in mind is, what if it shows icons of the app i can open my file type in, not just default apps.

**Comment by yaichenbaum** [comment]
> Maybe like rotate, edit for pictures, open in video editor for videos, something like that

Good feedback!

> one more thing I have in mind is, what if it shows icons of the app i can open my file type in, not just default apps.

How would that work if there are multiple apps that can open the file?

**Comment by hiranmayd** [comment]
>How would that work if there are multiple apps that are able to open the file?

That's exactly where it'll shine, multiple app icons so that I can choose where to open it.

**Comment by voiiden** [comment]
a disadvantage to having content aware context menus could be less predictability. when the menu is static, you always know where the buttons are, which makes you faster.

**Comment by hiranmayd** [comment]
one set of icons as i said will be universal and wont change, its just the other sets which will be adaptive.

**Comment by tgrelka** [comment]
> That's exactly where it'll shine, multiple app icons so that I can choose where to open it.
I think this would be great with an overflow menu. Display the default app as the icon, with an arrow next to it, opening an overflow menu to show more registered apps for this file type. That way, visual clutter is avoided if there’s many apps to choose from.
Or maybe limit the selection to three? That way it’s still fast.

While typing this I also though of something Total Commander does. It allows you to choose a text editor and have, I believe F4, to open any file currently selected in that text editor.
This would work extremely well with Visual Studio Code, for example, which has plugins to even be compatible with image and binary files.
I believe Directory Opus has a similar option, letting you place your own buttons in the action bar, to e.g. open files with a specific app. 

Providing some monochrome icons for common apps would be nice, to make them fit in with the rest of the UI.

(I’m just rambling, collecting ideas, if that’s fine.)

**Comment by hiranmayd** [comment]
> Or maybe limit the selection to three? That way it’s still fast.

absolutely. maybe three and then an overflow menu.

**Comment by yaichenbaum** [comment]
While we haven't quite added support for custom actions, we have made some enhancements to improve the toolbar area and we believe they make the toolbar much more useful.
