### ISSUE TITLE
Improve contrast between dark accents and background in drive capacity bars

### ISSUE THREAD

**Issue by Flawedspirit** [files-community/Files#2925]
**Is your feature request related to a problem? Please describe.**
I currently use the dark gray Windows accent color (#4C4A48) and coupled with the dark gray of the indicator bars on the drives, makes the capacity impossible to see. I like this shade, and the dark gray accent is rather popular with a wide swath of users, so

**Describe the solution you'd like**
A few solutions I can think of:
- Make the background a lighter gray (this pushes the issue onto others that use that color scheme though)
- Make the background black/very dark, and add a border around the bar so users can still tell the full width of the bar
- Allow users to set an accent that overrides the Windows colors (probably the best option)

**Additional context**
Windows is set to dark mode.

Image of issue: ![ZcJIPLf 1](https://user-images.githubusercontent.com/2686889/104265444-799f7480-5442-11eb-9960-b810678ca96c.png)

**Comment by yaichenbaum** [comment]
@Flawedspirit This issue might be a little hard to solve due to your choice of accent color. This is actually the default behavior of the WinUI progress bar so we would recommend opening an issue on their repo over [here](https://github.com/microsoft/microsoft-ui-xaml).
