### ISSUE TITLE
Add possibility to move the tab bar to the sides or bottom like the windows taskbar 

### ISSUE THREAD

**Issue by nimmiexe** [files-community/Files#2926]
please add update button and preview pane there, at right, left, bottom or top adjustment, and make it possible that the tab pane must be shifted left, right, top or bottom as we can do with taskbar so to make sense and more space for some time, and make flexibility to shift back and forward arrows down or at any side

**Comment by yaichenbaum** [comment]
@nimmiexe You can switch the tab strip to a vertical flyout under multitasking settings, can you check if this solves your issue?

**Comment by yaichenbaum** [comment]
Thanks again for your feedback.

_Since we didn't hear from you on this topic for 3+ days, we'll assume everything is worked out and close this feedback item. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this._
