### ISSUE TITLE
Suggestions for search

### ISSUE THREAD

**Issue by nimmiexe** [files-community/Files#2927]
also make possibility to add custom themes, make it fast and when we drop down to hide it must act like as happened in MAC OS it goes shaking, and make it possible that the search icon must be expanded and get hidden and become icon by clicking its properties and make it into center as present in Windows setting app, and make it possible that in setting icon there's history, AI recognition, search via picture or audio, and make it round corner option there

**Comment by yaichenbaum** [comment]
Merging with #2447.
