### ISSUE TITLE
Resize gridview size when resizing Files window?

### ISSUE THREAD

**Issue by nimmiexe** [files-community/Files#2929]
Add a way to move up or down or to pin the left pane items, and when we try to readjust the windows of files via any side into small or big via mouse arrow it not adjusted its folders and files inside the files window automatically

**Comment by yaichenbaum** [comment]
@nimmiexe You can change the layout mode and size from the layout button on the status bar, can you confirm if this solves your issue?

**Comment by yaichenbaum** [comment]
Thanks again for your feedback.

_Since we didn't hear from you on this topic for 3+ days, we'll assume everything is worked out and close this feedback item. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this._
