### ISSUE TITLE
Framework Microsoft.UI.Xaml.2.5 not Found. 

### ISSUE THREAD

**Issue by hackingguy** [files-community/Files#2930]
**Describe the bug**
Was Unable to install Msix Bundle By Clicking Simply Clicking On it.
I tried using Administrative Powershell to execute ```Add-AppxPackage ./Files.msixbundle```

And Got The Error
```
Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF3, Package failed updates, dependency or conflict
validation.                                                                                                             Windows cannot install package 49306atecsolution.FilesUWP_0.23.1.0_x64__et10x9a9vyk8t because this package depends on   a framework that could not be found. Provide the framework "Microsoft.UI.Xaml.2.5" published by "CN=Microsoft           Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and    minimum version 2.52012.2002.0, along with this package to install. The frameworks with name "Microsoft.UI.Xaml.2.5"    currently installed are: {}
NOTE: For additional information, look for [ActivityId] 67fe02c6-e896-0002-16a0-006896e8d601 in the Event Log or use
the command line Get-AppPackageLog -ActivityID 67fe02c6-e896-0002-16a0-006896e8d601
At line:1 char:1
+ Add-AppxPackage .\Files-0.23.1.Msixbundle
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\akash\...23.1.Msixbundle:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand
```

**Screenshots**
![brave_5cXKeYAJSS](https://user-images.githubusercontent.com/28388650/104282183-a734fe00-54d4-11eb-8175-406d6e54cf38.png)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1904.1645]
 - App version: Latest

**Comment by yaichenbaum** [comment]
@hackingguy Thank you for opening this issue, this issue can happen if you are missing some required dependencies on your device. An alternative download can be found [here](https://files-community.github.io/package.github.io/Files.Package/Files.Package.appinstaller).

**Comment by FunctionDJ** [comment]
> @hackingguy Thank you for opening this issue, this issue can happen if you are missing some required dependencies on your device. An alternative download can be found [here](https://files-community.github.io/package.github.io/Files.Package/Files.Package.appinstaller).

How can i run or use this file to add the missing dependencies?

**Comment by yaichenbaum** [comment]
@FunctionDJ You should be able to run it just by opening it.

**Comment by FunctionDJ** [comment]
> @FunctionDJ You should be able to run it just by opening it.

did not work (asks me which program to open it with). i assume it's because Windows Store is blocked by corporate guidelines.

**Comment by yaichenbaum** [comment]
@FunctionDJ Unfortunately, there isn't any way to get Files on your device without AppInstaller, can you see if you can add AppInstaller to your device?

**Comment by FunctionDJ** [comment]
> @FunctionDJ Unfortunately, there isn't any way to get Files on your device without AppInstaller, can you see if you can add AppInstaller to your device?
I don't think so. Windows Store is completely blocked, even though i'm an Admin on this machine.

**Comment by sangafabrice** [comment]
**1/ Download the required Framework**
[https://github.com/files-community/package.github.io/blob/main/Files.Package/Dependencies/x64/Microsoft.UI.Xaml.2.5.appx](url)
**2/ Provision your image using dism command tool (administration priviledges required)**
```
dism /online /add-provisionedappxpackage /packagepath:\\fullpath\\to\\Microsoft.UI.Xaml.2.5.appx /skiplicense
```

**Comment by corewwwi** [comment]
this way worked with me
https://superuser.com/questions/1500314/cannot-reinstall-calculator-microsoft-ui-xaml-2-0-missing
