### ISSUE TITLE
App not showing C: drive in neither navigation pane nor Home.

### ISSUE THREAD

**Issue by iseeghosts** [files-community/Files#2931]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find the log file manually by following [this](https://github.com/files-community/Files/wiki/Opening-the-log-file) guide.

**Comment by gave92** [comment]
@iseeghosts thanks for this report. Please add your app version to the issue description and post the log files

**Comment by yaichenbaum** [comment]
Thanks again for your feedback.

_Since we didn't hear from you on this topic for 3+ days, we'll assume everything is worked out and close this feedback item. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this._
