### ISSUE TITLE
Put folders above files when "Sorted by Name"

### ISSUE THREAD

**Issue by crashmit** [files-community/Files#2933]
I don't know if this is just trained through yearlong usage of the windows explorer, but I am so used to having all my folders on top of the files when I sort by name. This makes it much faster for me to go down the folder structure, as I know "Navigation" is on top and "Content" is below. I know, I could sort by type - but this would leave me without alphabetical order of the files below. Would it be possible to do this similar to the Win32 Explorer? 

![image](https://user-images.githubusercontent.com/58466626/104294955-266c0700-54c0-11eb-921c-ecb2465d6d57.png)
 vs
![image](https://user-images.githubusercontent.com/58466626/104295034-426fa880-54c0-11eb-8168-721a46fb01bb.png)

**Comment by gave92** [comment]
This should already by an option. Look for "Sort folders alongside files" setting and see the difference turning it on or off

**Comment by crashmit** [comment]
Oh thank you, I didn't recognize this setting as the one i was looking for.
