### ISSUE TITLE
Entering nothing as path and then pressing enter crashes the program

### ISSUE THREAD

**Issue by ToothyDev** [files-community/Files#2935]
**Describe the bug**
Program closes when trying to go to a blank path

**To Reproduce**
1. Click on the URL / path bar
2. Delete whatever is there, so nothing is left
3. Press enter

**Expected behavior**
Program either stays in current folder or defaults to C:/

**Screenshots**
![image](https://user-images.githubusercontent.com/55001472/104313492-60e19e00-54d8-11eb-9c51-fa5b49d96ae4.png)
Pressing enter here crashes it ^^

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.685
 - App version: v1.0.0.0

**Additional context**
Problem is stable to reproduce every time

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5801976/debug.txt)
^^ Has some german stuff in it, no clue how, I reinstalled my entire PC fully in english, anyway

**Comment by yaichenbaum** [comment]
@ToothyDev Thank you for reporting this issue, it should be resolved with #3007.
