### ISSUE TITLE
Program taskbar preview has media buttons

### ISSUE THREAD

**Issue by ToothyDev** [files-community/Files#2936]
**Describe the bug**
When hovering over the icon on the taskbar when Files is open, there will be greyed out media buttons

**To Reproduce**
1. Open files
2. Hover over the taskbar icon
3. See media buttons

**Expected behavior**
No media buttons; Audio files open in Groovy so I'm sure this is a bug

**Screenshots**
![image](https://user-images.githubusercontent.com/55001472/104314813-3bee2a80-54da-11eb-9f56-f496f38c747d.png)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2 19042.685
 - App version: v1.0.0.0

**Additional context**
Problem occurs reliably on every start

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5802058/debug.txt)

**Comment by gave92** [comment]
Unfortunately this is a Windows issue which we can't fix.

**Comment by mdtauk** [comment]
> Unfortunately this is a Windows issue which we can't fix.

Are you sure, other UWP apps seem to support Jumplists without the media controls?

**Comment by gave92** [comment]
It's only an issue for UWP apps that use a Fulltrust component

**Comment by mdtauk** [comment]
> It's only an issue for UWP apps that use a Fulltrust component

Ah, have you brought this up in the WinUI repo, and the ProjectReunion repo?  This seems like the sort of thing that needs to be fixed.
