### ISSUE TITLE
Copying doesn't copy to clipboard

### ISSUE THREAD

**Issue by ToothyDev** [files-community/Files#2937]
When you right click > copy, you can paste it where you like. Simple. But if you want to copy a file and then paste it in e.g. Discord or any program, it won't paste because it didn't copy to Windows Clipboard (? i guess that's how it works).
This is related to the drag and drop being a bit wonky: You need to first properly click the file you want to drag and drop before you can actually drag and drop it. My suggestion, if you drag any file, selected or not, that file will be dragged. It's annoying to always having to select the file, because that is currently the only way to get a file "out of Files" into another program since copy won't do it

**Comment by gave92** [comment]
Could you provide some more info?
- What version of the app are you using?
- Does copying a file from Files app and paste it inside Files work?
- Does copying a file from Files app and paste it to windows explorer work?

**Comment by ToothyDev** [comment]
v1.0.0.0
Yes, copying and pasting within files works as expected.
Copying files from files > explorer works fine as well
However, when I copy a file and try to CTRL+V it into any other program, it won't work, it also doesn't show up in Win+V in case its an image

**Comment by yaichenbaum** [comment]
@ToothyDev Is this still an issue in v1.5?
