### ISSUE TITLE
Bring back the preview pane please!

### ISSUE THREAD

**Issue by oOII-J4HN-IIOo** [files-community/Files#2938]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The preview pane from the legacy file explorer is a feature that I find really useful just to peek at different documents to view their contents... That's one thing that I'd say is missing from my perfect experience with Files.

**Describe alternatives you've considered**
None

**Additional context**
N/A

**Comment by gave92** [comment]
Duplicate of #130
