### ISSUE TITLE
Detect folders as image folders and adjust grid view

### ISSUE THREAD

**Issue by ToothyDev** [files-community/Files#2939]
**Is your feature request related to a problem? Please describe.**
I have about 30 picture folders. If I don't want the list view, but the small / medium grid view to view the previews, I would have to do it for all thirty folders.

**Describe the solution you'd like**
If there's a majority of pictures in a folder, detect it as picture folder and set the grid view to a userdefined preset (grid view medium / small in my case). This would help save time

**Describe alternatives you've considered**
Being able to change grid views in bulk by selecting some folders, then changing the grid layout. This would apply to, selectively, only the selected folders or for all child folders as well

**Comment by gave92** [comment]
Merging with #2893
