### ISSUE TITLE
Add "Send To" right-click context menu.

### ISSUE THREAD

**Issue by NConley9** [files-community/Files#2940]
**Is your feature request related to a problem? Please describe.**
I work as a graphic designer and send many proofs via email every day.  My fastest workflow is to find the file, right click > Send To > Mail Recipient.  The share menu does not offer my email client (eM Client).  I also use "Send To" often to create Zip files.

**Describe the solution you'd like**
Either implement the "send To" context menu, or add another option to open the default mail client and attach the file to a new message.

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by yaichenbaum** [comment]
Merging with #285.
