### ISSUE TITLE
Ability to close second pane

### ISSUE THREAD

**Issue by ToothyDev** [files-community/Files#2941]
**Is your feature request related to a problem? Please describe.**
When I need to do some stuff with the secondary pane, I'd love to close it again without having to open a whole new tab.
I tried my best but can't find a way to close secondary panes again

**Describe the solution you'd like**
Either a small X somewhere, or when you right click a free space, it would say "close secondary pane"
Alternatively / additionally: Resizing a secondary pane to the very far right / left will also close it

**Comment by gave92** [comment]
You can close the pane by dragging it all the way to the right.
Pressing Ctrl + Shift + W also closes the oane

**Comment by yaichenbaum** [comment]
@gave92 What do you think of adding a menu option to close panes?

**Comment by gave92** [comment]
> @gave92 What do you think of adding a menu option to close panes?

Can be done. Added to the right pane triple-dot menu

**Comment by yaichenbaum** [comment]
> Can be done. Added to the right pane navbar triple-dot menu?

Yes, additionally, it should only show when there are two panes open.

**Comment by gave92** [comment]
It would be only in the right pane so it's only visible when it's open ;)

**Comment by yaichenbaum** [comment]
@gave92 Shouldn't it show in both panes so that the user can decide which pane to close?

**Comment by gave92** [comment]
@yair100 the left pane is the main pane and includes the sidebar. Atm there's no possibility to close it. Also something that can be done but more work is needed.

**Comment by eamodio** [comment]
It might be nice as a toggle button or something, so it could be easy toggled on/off

**Comment by FireCubeStudios** [comment]
good

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5237.

**Comment by panyann** [comment]
Guys, what am I doing wrong? Where is that button? There is no option to close the second pane... Only `Ctrl + Shift + W` works.
https://www.youtube.com/watch?v=Cn6eOM0895Y

**Comment by Josh65-2201** [comment]
You have to right click the pane you want to close or use the button on the left of the tab bar

**Comment by panyann** [comment]
@Josh65-2201 Ok, I can see that, thanks!
