### ISSUE TITLE
WSL2 shows duplicate folders and files

### ISSUE THREAD

**Issue by carlosvsilva** [files-community/Files#2943]
**Describe the bug**
When i stick the WSL2 home folder \\wsl$\Ubuntu\home\username to my sidebar and then open it I see duplicates and triplicates of folders and files inside home in WSL2

**To Reproduce**
1. Stick \\wsl$\Ubuntu\home\username to sidebar
2. Enable Dual Pane view
3. Open 'username' folder clicking the sidebar
4. See error of many copies of the same file and folders.

**Expected behavior**
Only a single file and single folder should be seen for each item

**Screenshots**
![Files](https://user-images.githubusercontent.com/40889421/104338073-0a7f5a00-54ee-11eb-8a8e-3a63953a22d4.png)

**Desktop (please complete the following information):**
 - OS Version: Microsoft Windows [Version 10.0.19042.685]
 - App version: [v1.0.0.0]

**Comment by yaichenbaum** [comment]
@jakoss Can you confirm if this is related to the caching feature?

**Comment by gave92** [comment]
Yup should be same issue as network drives. Issue solved in development branch.
Workaround is disabling "Enable cache" setting

**Comment by jakoss** [comment]
I was pretty sure that this fix was incorporated with 1.0.0 :)

**Comment by gave92** [comment]
@jakoss #2880 made it to 1.0.2 I think
