### ISSUE TITLE
Context menu opens explorer

### ISSUE THREAD

**Issue by Sebastia181** [files-community/Files#2946]
Los menús contextuales van muy lentos, al marcar una carpeta o archivo el menú contextual a veces aparece y otras se abre con la APP EXPLADOR DE ARCHIVOS DE WINDOWS, EN GENERAL PINTA MUY BIEN, pero aun falta pulirla bastante 
-----------------------------
Context menus are very slow, when marking a folder or file the contextual menu sometimes appears and other times it opens with the WINDOWS FILE EXPLORER

**Comment by Hefaistos68** [comment]
Yes, context menus can be extremely slow to show up first time, I see here between 3-6 seconds on most items. 

Maybe a nice idea would be to have by default just the standard file or folder context menu entries, and all extension entries (COM type, through file extension or otherwise) in an optional submenu. (this is not Windows Explorer like but would speed up working with files and folders tremendously)

**Comment by gave92** [comment]
@Sebastia181 could you clarify what "other times it opens with the WINDOWS FILE EXPLORER" means? What menu items cause windows explorer to open?

**Comment by flobo09** [comment]
Same, just discovered this app earlier today and it looks great but context menu are so slow to appear i thought they weren't supported. 

It takes "at beast between 3 to 5 seconds for a context menu to appear.

**Comment by gave92** [comment]
Issue of slow context menu it's tracked #2527. Keeping this open for the "context menu opens windows explorer" issue.

Thanks a lot @flobo09, we're working to improve this 👍

**Comment by Sebastia181** [comment]
**Todos los problemas residen cuando utilizas el modo táctil,** 
_Con el ratón tarda muy poco en abrir el menú contextual, y va todo muy fluido,_ 
En modo táctil al seleccionar una carpeta tarda bastante, pero abre también la carpeta, también a veces no se abre un archivo que seleccionas con el dedo y seleccionas otro y entonces este se abre, pero abre la AAP correspondiente pero no se muestra en pantalla queda abierta en la barra de tareas.
Lo de abrir con  del Explorador de archivos de Windows 10, era una capeta o archivo pero no me acuerdo fue al principio y fue muy rápido, lo que si que al Desbloquear el Almacén Personal en ONEDRIVE se abre con Explorador de Archivos 
Iré mirando, pero esto es norma al principio, FILES ES UNA APP DE ARCHIVOS MUY BUENA y será aun mejor con el tiempo. 
Un saludo a todos

**Comment by gave92** [comment]
@Sebastia181 thanks for the additional info. We'll work to improve the points you mentioned.

-----------------------------------
All problems reside when you use touch mode,
With the mouse it takes very little time to open the context menu, and everything goes very smoothly,
In touch mode when selecting a folder it takes a long time, but it also opens the folder, also sometimes a file that you select with your finger and select another does not open and then it opens, but it opens the corresponding AAP but it is not shown on the screen. open in the taskbar.
The opening with the Windows 10 File Explorer, it was a folder or file but I do not remember it was at the beginning and it was very fast, so when Unlocking the Personal Store in ONEDRIVE it opens with File Explorer
I'll go looking, but this is the norm at the beginning.

**Comment by Sebastia181** [comment]
Tengo instalado el programa FOLDERPAINTER y en el Explorador de archivos me aparecen  en el menú contextual tres entradas uno de colores y las otras dos diseños de Carpetas, en FILES me aparecen pero en modo texto, adjunto capturas de pantalla

![2021-01-14-EXPLORER](https://user-images.githubusercontent.com/77354322/104656380-7bc23700-56bf-11eb-9125-1c65b308ebcb.png)
![2021-01-14-EXPLORER-2](https://user-images.githubusercontent.com/77354322/104656383-7c5acd80-56bf-11eb-8ac9-1c6ba9be01f9.png)
![2021-01-14-EXPLORER-3](https://user-images.githubusercontent.com/77354322/104656384-7cf36400-56bf-11eb-9b66-b1f5d4eab690.png)
![2021-01-14-FILES](https://user-images.githubusercontent.com/77354322/104656386-7cf36400-56bf-11eb-801b-c6d9a9154d34.png)
![2021-01-14-FILES-2](https://user-images.githubusercontent.com/77354322/104656388-7d8bfa80-56bf-11eb-8832-0ef14f082575.png)
![2021-01-14-FILES-3](https://user-images.githubusercontent.com/77354322/104656389-7e249100-56bf-11eb-8b31-36b81e1cf58d.png)

**Comment by duke7553** [comment]
@Sebastia181 La adición de etiquetas de color a archivos y carpetas se está rastreando actualmente en otro elemento de comentarios https://github.com/files-community/Files/issues/1161

**Comment by Sebastia181** [comment]
Muchas gracias por la información
Sebastià Tost

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Luke Blevins<mailto:notifications@github.com>
Enviado: dijous, 28 de gener de 2021 4:11
Para: files-community/Files<mailto:Files@noreply.github.com>
CC: Sebastia181<mailto:sebas.tj@live.com>; Mention<mailto:mention@noreply.github.com>
Asunto: Re: [files-community/Files] Context menu opens explorer (#2946)


@Sebastia181<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSebastia181&data=04%7C01%7C%7C8513a5cd61bb408f415408d8c33a5d21%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637474002717117761%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=eEEwKixK66qAY2QoQwceBYOlkTNVyKdEZ3GYlvmYJFw%3D&reserved=0> La adición de etiquetas de color a archivos y carpetas se está rastreando actualmente en otro elemento de comentarios #1161<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffiles-community%2FFiles%2Fissues%2F1161&data=04%7C01%7C%7C8513a5cd61bb408f415408d8c33a5d21%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637474002717127717%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=NLlWh46Z0AWLApYIMAAEwbxV9V3NXlyrwWGCojh8fpc%3D&reserved=0>

**Comment by kennymckormick** [comment]
Are there any early versions free from this problem? If so, we users can use old versions instead.
