### ISSUE TITLE
Drag and Drop from Virtualbox works after multiple tries

### ISSUE THREAD

**Issue by kevinstsauveur** [files-community/Files#2948]
**Describe the bug**
If I want to drag and drop from a Virtualbox machine, File sometimes recognize that he has to copy the content.
I am able to drag and drop from a Virtualbox virtual machine to the Native File Explorer without having to struggle.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Files to a directory that you want to copy a file.
2. Go into a Virtualbox virtual machine that the _Drag and drop_ from the VM to the host is _enabled_. 
3. Drag a file from the Virtualbox virtual machine to Files.
4. To make files recognize the Drag and drop, enter your mouse into the window of File and then outside multiple times (it's not consistent).
5. The transfer is working as expected.

**Expected behaviour**
Files accept drag and drop files as expected.

**Screenshots**
![2021-01-12](https://user-images.githubusercontent.com/25964106/104362153-6becfc00-54e1-11eb-9050-2b516e9f242c.gif)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 Education 20H2 19042.685]
 - App version: [v1.0.0.0]

**Additional context**
 - Oracle VirtualBox V6.1.16 r140961 (Qt5.6.2)

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5804332/debug.txt)

**Comment by gave92** [comment]
Do you experience the same when dragging a file from windows explorer into Files?
Does it work better if you drag the file from the top of the Files window instead of the bottom?

**Comment by kevinstsauveur** [comment]
Dragging a file from windows explorer into Files is working everytime.
It does work better if I drag the file from the right side of Files.

A restart of Files and of the computer does not affect this behaviour.

**Comment by gave92** [comment]
Closing as #5273 changed how D&D from external programs is handled.
