### ISSUE TITLE
Crashing when opening download folder (Windows on ARM)

### ISSUE THREAD

**Issue by Raffomatiko** [files-community/Files#2949]
**Describe the bug**
When I open the download folder, the App just crashes. There´s no way to avoid this. I get an error notification with the possibility to submit this issue.

**To Reproduce**
1. Go to App "Files"
2. Click on 'Download'
3. Scroll down to: instantly crashes
4. See error "Something went wrong"

**Expected behavior**
It should open the download folder and present me my downloads.

**Screenshots**
![image](https://user-images.githubusercontent.com/76536666/104368781-d5d6c700-551c-11eb-8ea2-e271d07e5046.png)
This is the error message in German.

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 on ARM 20H2 19042.685]
 - App version: [v1.0.0.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?
Yeah, it restarts every time after it crashes.

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find the log file manually by following [this](https://github.com/files-community/Files/wiki/Opening-the-log-file) guide.
[debug.txt](https://github.com/files-community/Files/files/5804658/debug.txt)

**Comment by gave92** [comment]
Thanks for this report. This is an issue specific to WoA. It has been in the development branch and a fix will ship with the next public version.
If after the next update u still experience this issue please let us know.
At the moment we don't have a workaround for this issue.
