### ISSUE TITLE
"Default File Explorer Option"

### ISSUE THREAD

**Issue by heshgohar** [files-community/Files#2950]
There must be an option to use your app as a default file explorer ..

**Comment by gave92** [comment]
There's an unsupported method of doing it explained here: https://files-community.github.io/docs/#/articles/replace-file-explorer

**Comment by seiyria** [comment]
Is there an easy way to get an update on this? I planned to sub to this issue but I'm not sure if there's a better place to get news.

**Comment by gave92** [comment]
@seiyria the guide at the link above has been updated. If you have any issue following it feel free to post it here and we'll try to help

**Comment by seiyria** [comment]
@gave92 I saw that it still said (Unsupported) at the end, and I wasn't sure if this was the new guide or not. Thanks!

**Comment by gave92** [comment]
@seiyria yeah it's still "unsupported" as it requires changes to the windows registry *for which we do not take responsibility* ;)
