### ISSUE TITLE
Use check boxes to select items

### ISSUE THREAD

**Issue by pokeseeker** [files-community/Files#2951]
**Is your feature request related to a problem? Please describe.**
No it is not.

**Describe the solution you'd like**
It would be nice to have the use check boxes to select items option from file explorer in Files.
![2021-01-12 14_54_17-Folder Options](https://user-images.githubusercontent.com/18503714/104384316-18c97800-54e6-11eb-90a7-7b534f5d9681.png)

**Describe alternatives you've considered**
None.

**Additional context**
Latest app Version from MS Store, on build 20H2.

**Comment by yaichenbaum** [comment]
Merging with #290.
