### ISSUE TITLE
There is no "Paste" option on context menu when I want to paste file in folder

### ISSUE THREAD

**Issue by McPwner** [files-community/Files#2952]
**Describe the bug**
There is no "Paste" option on context menu when I copy/cut file or folder and RMB click on folder where I want to paste. On the other hand if I open desired folder and then RMB click, there is "Paste" on context menu.

**To Reproduce**
1. Right mouse button click on any file/folder
2. Click on copy/paste
3. Click on (RMB) folder where you want to paste file/folder
4. See error: there is no "Paste" option

**Expected behavior**
There should be "Paste" option.

**Screenshots**
On first screenshot you can see that there is "Cut" at context menu (witch I have clicked):
![Files - SS1 (1)](https://user-images.githubusercontent.com/72248348/104386504-a3859380-5535-11eb-8305-2c0a8f0547a4.png)

On second screenshot you can see that after I do right mouse click on folder, there is no "Paste" option in context menu.
![Files - SS1 (2)](https://user-images.githubusercontent.com/72248348/104386505-a41e2a00-5535-11eb-86f8-edda2b0dd6e2.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 build 19042.685, Experience Pack 120.2212.551.0
 - App version: [v1.0.0.0] (Microsoft Store)

**Additional context**
On attached video you can see how that looks:
https://user-images.githubusercontent.com/72248348/104389096-f746ab80-553a-11eb-8a59-55e8e866f295.mp4

Same thing is happening after: restarting app, resetting app (from Apps & features->Files->Advanced options), reinstalling.

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5805368/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5805369/debug_fulltrust.txt)

**Comment by yaichenbaum** [comment]
@McPwner This issue should be resolved with #4541.
