### ISSUE TITLE
Slow move operation

### ISSUE THREAD

**Issue by McPwner** [files-community/Files#2955]
**Describe the bug**
A very slow move operation.
When I want to move file(s)/folder(s) to new location that is on same (physical partition/disk), move operation is very slow. Looking on Task manager, I can see that there is heavy transfer operation. Problem is there is no any visual indicators in Files.
I guess app is doing full copy of file and after that it deletes it from original location (as I can see file(s) on original location 'till this is finished).   

**To Reproduce**
1. Move file from one folder to other on same disk/partition
2. File appears on new location with size 0kb
3. File is still at old location
4. After some time (depending of size of file and disk speed) file on old location disappears.

**Expected behavior**
Moving files/folders on same partition should be nearly instantaneous. 

**Screenshots**

https://user-images.githubusercontent.com/72248348/104391972-5dcec800-5541-11eb-9907-58984138df31.mp4

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.685
 - App version: [v1.0.0.0]

**Additional context**

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5805689/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5805690/debug_fulltrust.txt)

**Comment by gave92** [comment]
> I guess app is doing full copy of file and after that it deletes it from original location

Your analys is correct ;)

**Comment by yaichenbaum** [comment]
@McPwner This issue should be addressed with #2955.
