### ISSUE TITLE
App freezes after copying name of file/folder

### ISSUE THREAD

**Issue by McPwner** [files-community/Files#2956]
**Describe the bug**
App freezes after copying name of file/folder.

**To Reproduce**
1. Rename file/folder (F2 or from context menu)
2. RMB click on file/folder name
3. Click "Copy"->Enter (or click anywhere)
4. App freezes.

**Expected behavior**

**Screenshots**
After 8th second I'm trying RMB click on background and selecting files. 
https://user-images.githubusercontent.com/72248348/104392653-d8e4ae00-5542-11eb-82f6-9219fdee70f6.mp4

**Desktop (please complete the following information):**
 - OS Version:  Windows 10 20H2 19042.685
 - App version: [v1.0.0.0]

**Additional context**
If I pres F2 to rename file/folder and Ctrl+C on keyboard (so, not trough context menu with RMB) everything is fine and app doesn't freeze.

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5805742/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5805743/debug_fulltrust.txt)

**Comment by yaichenbaum** [comment]
This issue appears to be resolved in `main`.
