### ISSUE TITLE
Cannot double click with touch

### ISSUE THREAD

**Issue by jkane12** [files-community/Files#2959]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find the log file manually by following [this](https://github.com/files-community/Files/wiki/Opening-the-log-file) guide.

**Comment by duke7553** [comment]
We have a setting which enables single tap to invoke items.
![image](https://user-images.githubusercontent.com/20365014/104653937-574b6800-5689-11eb-963f-1929625e0aa7.png)

Please re-open this issue with more information if this setting isn't what you had in mind.
