### ISSUE TITLE
Change Icons/Symbols of Folder

### ISSUE THREAD

**Issue by Raffomatiko** [files-community/Files#2966]
**Is your feature request related to a problem? Please describe.**
Well, in the normal Explorer it´s possible to change the icon/symbol of specific folders. I use this to have a better overview, so I can open folders quicker, because I don´t always need to read the name.

**Describe the solution you'd like**
When clicking on "properties" there should be an option "change icon/symbol". 

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?
![image](https://user-images.githubusercontent.com/76536666/104416884-cf743980-5574-11eb-897e-5d4cce462656.png)

I use a Surface Pro X with Windows on ARM.

**Comment by yaichenbaum** [comment]
Merging with #1015.
