### ISSUE TITLE
Double clicking on name of selected items always enters "rename" mode

### ISSUE THREAD

**Issue by Hefaistos68** [files-community/Files#2967]
**Describe the bug**
When I select an item in the files list (details view), file or folder, and then double click on the name, instead of opening the file or opening the folder, it goes into rename mode where I can change the name. This does not happen when clicking anywhere else in the area of the selected item, only in the area of the "name" column.

**To Reproduce**
Open any folder location, switch to "Detail view", select a file or folder by single clicking it, then double click in the "Name" column area of selected item. 
The "Rename" mode will be initiated where you can alter the items name, instead of opening the item.

**Expected behavior**
I expect an item to open when double clicking it, selected or not.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Home, Version 20H2, OS Build 19042.746, Windows Feature Experience Pack 120.2212.551.0
 - App version: 1.0.0.0
 - Hardware:
Processor	Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz   1.99 GHz
Installed RAM	12.0 GB (11.9 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

**Additional context**
No change in context, misbehaviour is constant.

**Log file**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5808293/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/5808294/debug.txt)

**Comment by gave92** [comment]
@Don-Vito we might need to reintroduce the debounce before starting rename

**Comment by Don-Vito** [comment]
> 
> 
> @Don-Vito we might need to reintroduce the debounce before starting rename

@gave92 - I hope we not :blush: Need to debug this. We have tested this scenario when applying the fix. Guess there is some sort of race that we need to understand.

**Comment by gave92** [comment]
@Don-Vito not sure we tested this. The change was to fix the issue when you click outside the datagrid.
In this case you click once to select an item and then double click on the name. Since renaming starts at first tap and files open on double tap, renaming wins

**Comment by Don-Vito** [comment]
> not sure we tested this. The change was to fix the issue when you click outside the datagrid.
> In this case you click once to select an item and then double click on the name. Since renaming starts at first tap and files open on double tap, renaming wins I guess :)

@gave92 -  Yeah.. it looks so.. I would expect the DataGrid to solve this for us. I am taking a look if we can somehow avoid it.. If not I will return the debouncer  😢

**Comment by gave92** [comment]
Thanks. Explorer has a debounce as well so it's not the end of the world

**Comment by Don-Vito** [comment]
So it looks, that the double tap is not a part of the DataGrid state machine, so it really seems our responsibility to debounce.

**Comment by Don-Vito** [comment]
@gave92 - btw, my major problem with tap debouncer that it doesn't take the cell into consideration. I mean if during the debounce time someone selects another cell we gonna open it.

**Comment by yaichenbaum** [comment]
@Hefaistos68 This issue should be resolved with #3000.

**Comment by gave92** [comment]
Reopened, issue is back.
