### ISSUE TITLE
Wrong translation to Italian

### ISSUE THREAD

**Issue by squalo80** [files-community/Files#2968]
**Describe the bug**
Wrong translation on Italian

**To Reproduce**
1. Go to 'SETTINGS'
2. Click on 'APPEARANCE'
3. Take a look on screenshot

**Expected behavior**
Just correct the language

**Screenshots**
![2021-01-13 131232](https://user-images.githubusercontent.com/40205934/104450931-2263e600-55a1-11eb-9e8f-9f266be444c7.jpg)

**Desktop (please complete the following information):**
 - OS Version:  Windows 10 20H2 19042.685
 - App version: v1.0.0

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find the log file manually by following [this](https://github.com/files-community/Files/wiki/Opening-the-log-file) guide.

**Comment by gave92** [comment]
Ciao grazie del feedback.
Could you confirm that the app version you're using is v1.0.0?

**Comment by squalo80** [comment]
Confirmed v 1.0.0

**Comment by yaichenbaum** [comment]
@squalo80 Would you like to try fixing this?

**Comment by squalo80** [comment]
@yair100 Yesterday I tried to check the file Files.it-IT.xlf but it is already translated there. 
I can try, but my experience on coding isn't at this level.

**Comment by yaichenbaum** [comment]
@squalo80 It's very possible that this issue was already fixed and will be included in the next update. Please reopen this issue if you can still reproduce it when v1.1 rolls out.
