### ISSUE TITLE
Network Folder Duplication Bug

### ISSUE THREAD

**Issue by Obsidiannite21** [files-community/Files#2972]
**Describe the bug**
When I open a network folder (i.e. \\mediacenter-pc) it duplicates the 3 subfolders each time the path is opened. Currently, it shows I have 33 folders, all named the same, when there are 3. 

**To Reproduce**
1. Go to the path and type in \\network location
2. See screenshot.

**Expected behavior**
An accurate listing of the folders. 

**Screenshots**
![13-01-2021 07-55-24](https://user-images.githubusercontent.com/28603530/104455043-bc616980-5574-11eb-89ea-a54293a7fb98.jpg)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 2004 / 19041.746
 - App version: [v0.11.0]

**Additional context**
I've closed and re-opened the app, all it does is add more folders (now at 42). 

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find the log file manually by following [this](https://github.com/files-community/Files/wiki/Opening-the-log-file) guide.
[debug.txt](https://github.com/files-community/Files/files/5808699/debug.txt)

**Comment by gave92** [comment]
Thanks for this report. This issue has been fixed.
As a workaround you can disable the "Enable file cache" option in Files settings
