### ISSUE TITLE
Focus loss in detail pane

### ISSUE THREAD

**Issue by Hefaistos68** [files-community/Files#2977]
**The bug**
When you click outside the information area in the detail pane (the area AFTER the last column) you lose focus  and keyboard navigation with up/down or left/right arrows doesnt work anymore. You have to effectively tab through all the controls to get back to the detail list. Shift+Tab is a shorter path, but still there are a few controls to shift+tab through to get back.

**To Reproduce**
Select an item in detail view, click in the empty area after the last column (Size usually), the selected item loses selection and focus, keyboard navigation is no longer possible.

**Expected behavior**
Keep the input focus on the detail list and return selecting an item with up/down arrows.

**Desktop (please complete the following information):**
- OS Version: Windows 10 Home, Version 20H2, OS Build 19042.746, Windows Feature Experience Pack 120.2212.551.0
- App version: 1.0.0.0
- Hardware:
Processor Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz 1.99 GHz
Installed RAM 12.0 GB (11.9 GB usable)
System type 64-bit operating system, x64-based processor
Pen and touch No pen or touch input is available for this display

**Additional context**
Compare with default behaviour of the Windows Explorer, focus always returns to the detail list when using the arrow keys.

**Log file**
Nothing useful in them related to this issue.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7425
