### ISSUE TITLE
Navigation/Selection error on Alt+Enter

### ISSUE THREAD

**Issue by Hefaistos68** [files-community/Files#2980]
**The bug**
Pressing Alt+Enter on a selected item in Detail view, advanced the selection to the next item in the list, but also opens the properties of the currently selected item (as expected)

**To Reproduce**
Open any folder with some items in Detail View, select the first item, press Alt+Enter. The properties of that item are shown, but selection advances to the next item.

**Expected behavior**
Show Properties and keep selection on the item.

**Desktop (please complete the following information):**
- OS Version: Windows 10 Home, Version 20H2, OS Build 19042.746, Windows Feature Experience Pack 120.2212.551.0
- App version: 1.0.0.0
- Hardware: Processor Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz 1.99 GHz
Installed RAM 12.0 GB (11.9 GB usable)
System type 64-bit operating system, x64-based processor
Pen and touch No pen or touch input is available for this display

**Log file**
Nothing useful in the log related to this issue

**Comment by gave92** [comment]
See #2463
