### ISSUE TITLE
Search box doesn't put focus when opened first time via keyboard

### ISSUE THREAD

**Issue by chingucoding** [files-community/Files#2982]
**Describe the bug**
When opening a folder and open the search box for the first time, focus is not put on the search box for the first time. Closing the search box and reopening it will then put focus on the search box.
**To Reproduce**
1. Open folder
2. Open search box using keyboard by hitting space/enter on search icon
3. Observe that focus is on button, not on search box

**Expected behavior**
Focus should land consistently on search box (x)
![Gif showing how focus order moves back and forth and skips search box when opened for the first time](https://user-images.githubusercontent.com/16122379/104468714-0c155480-55b8-11eb-9b09-213da750c95f.gif)
or button
**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: Windows 10 10.0.19042
 - App version: 1.0.0

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find the log file manually by following [this](https://github.com/files-community/Files/wiki/Opening-the-log-file) guide.
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5809381/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/5809382/debug.txt)

**Comment by yaichenbaum** [comment]
@chingucodingThank you for opening this issue, do you want to try fixing this?

**Comment by chingucoding** [comment]
I'll take a look at this and see what I can find.
