### ISSUE TITLE
Windows Menu key not working in Detail View

### ISSUE THREAD

**Issue by Hefaistos68** [files-community/Files#2983]
**The bug**
The Windows Menu key doesnt work when in detail view.

**To Reproduce**
Switch to Detail view, select an item (by mouse or keyboard) and press the Windows Menu key.

**Expected behavior**
Context menu should appear as it does on Right-Clicking an item, or when using the same key in any of the other views.

**Desktop (please complete the following information):**
- OS Version: Windows 10 Home, Version 20H2, OS Build 19042.746, Windows Feature Experience Pack 120.2212.551.0
- App version: 1.0.0.0
- Hardware: Processor Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz 1.99 GHz
Installed RAM 12.0 GB (11.9 GB usable)
System type 64-bit operating system, x64-based processor
Pen and touch No pen or touch input is available for this display

**Comment by gave92** [comment]
Merging with #2609
