### ISSUE TITLE
Application hang

### ISSUE THREAD

**Issue by Hefaistos68** [files-community/Files#2984]
**The bug**
Full application hang after resizing the app window and clicking on "Home", app became unresponsive and had to be killed.

**To Reproduce**
Definitely cant find a solid repro case. just happend after resizing the window and then clicking on Home. 

**Expected behavior**
no crash or hang ever ( wishful thinking is allowed, isnt it. )

**Screenshots**
![image](https://user-images.githubusercontent.com/8855055/104471419-bf7b4a80-55b2-11eb-85a0-5b509275b995.png)

**Desktop (please complete the following information):**
- OS Version: Windows 10 Home, Version 20H2, OS Build 19042.746, Windows Feature Experience Pack 120.2212.551.0
- App version: 1.0.0.0
- Hardware: Processor Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz 1.99 GHz
Installed RAM 12.0 GB (11.9 GB usable)
System type 64-bit operating system, x64-based processor
Pen and touch No pen or touch input is available for this display

**Log file**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5809483/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/5809484/debug.txt)

Information from the Event Log:
```
Log Name:      Application
Source:        Application Hang
Date:          13/01/2021 15:10:59
Event ID:      1002
Task Category: (101)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      AUP-AS
Description:
The program Files.exe version 1.0.0.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 15fc
 Start Time: 01d6e9be2595a104
 Termination Time: 4294967295
 Application Path: C:\Program Files\WindowsApps\49306atecsolution.FilesUWP_1.0.0.0_x64__et10x9a9vyk8t\Files.exe
 Report Id: d67caa4f-b5cf-4680-98b8-9148c87b4e57
 Faulting package full name: 49306atecsolution.FilesUWP_1.0.0.0_x64__et10x9a9vyk8t
 Faulting package-relative application ID: App
 Hang type: Cross-thread

```
```
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Hang" />
    <EventID Qualifiers="0">1002</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>101</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-01-13T15:10:59.7250657Z" />
    <EventRecordID>27531</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>AUP-AS</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Files.exe</Data>
    <Data>1.0.0.0</Data>
    <Data>15fc</Data>
    <Data>01d6e9be2595a104</Data>
    <Data>4294967295</Data>
    <Data>C:\Program Files\WindowsApps\49306atecsolution.FilesUWP_1.0.0.0_x64__et10x9a9vyk8t\Files.exe</Data>
    <Data>d67caa4f-b5cf-4680-98b8-9148c87b4e57</Data>
    <Data>49306atecsolution.FilesUWP_1.0.0.0_x64__et10x9a9vyk8t</Data>
    <Data>App</Data>
    <Data>Cross-thread</Data>
    <Binary>430072006F00730073002D007400680072006500610064000000430072006F00730073002D00700072006F0063006500730073000000410063007400690076006100740069006F006E0000000000</Binary>
  </EventData>
</Event>
```

**Comment by yaichenbaum** [comment]
@Hefaistos68 I just want to give a big thank you for opening all these detailed issue reports! A detailed report goes a long way towards making issues easier to understand and troubleshoot.

**Comment by yaichenbaum** [comment]
@Hefaistos68 Can you reproduce this issue consistently or did it only happen once?

**Comment by Hefaistos68** [comment]
> @Hefaistos68 I just want to give a big thank you for opening all these detailed issue reports! A detailed report goes a long way towards making issues easier to understand and troubleshoot.

You are welcome, I think its worth to report anything odd in an application that is useful. Only this way it will ever be "perfect". And as we all know, on the dev's machine it always runs perfectly. While on any other machine/user it shows all its evil sub routines.

**Comment by Hefaistos68** [comment]
> @Hefaistos68 Can you reproduce this issue consistently or did it only happen once?

So far I can not reproduce it on demand. Happened twice, both times seemingly related to resizing the window and then changing tab contents.

**Comment by yaichenbaum** [comment]
@Hefaistos68 Is this still an issue in v1.3?

**Comment by Hefaistos68** [comment]
Tried but havent seen anything like that happening anymore. Seemingly ok in 1.3
