### ISSUE TITLE
Mounted but not connected network drives do not produce warnings or errors

### ISSUE THREAD

**Issue by Hefaistos68** [files-community/Files#2985]
**The bug**
When you have a network drive mounted as a local drive but its not connected, then selecting this drive will show it as empty in the detail pane, all operations are available as if its a working drive, but none is actually executed but also no errors are shown.

**To Reproduce**
Connect any network folder as a local drive through the windows explorer (e.g.: Drive N:\), disconnect the network (or restart windows without connection to the network), then select it in the drive list, shown as "sharename (\\networkpath) (N:)".

The right side pane will show the drive as empty drive, no files, no folders, no errors. Context menu is available but doesnt do anything.

**Expected behavior**
Show information that the drive is not available, disconnected, etc. but not show it as empty drive.

**Screenshots**
![image](https://user-images.githubusercontent.com/8855055/104473177-9a87d700-55b4-11eb-81ee-e5702bafc165.png)

**Desktop (please complete the following information):**
- OS Version: Windows 10 Home, Version 20H2, OS Build 19042.746, Windows Feature Experience Pack 120.2212.551.0
- App version: 1.0.0.0
- Hardware: Processor Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz 1.99 GHz
Installed RAM 12.0 GB (11.9 GB usable)
System type 64-bit operating system, x64-based processor
Pen and touch No pen or touch input is available for this display

**Log file**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5809556/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/5809557/debug.txt)

**Comment by Hefaistos68** [comment]
Oh and, selecting properties of a network drive does open two properties windows of the same.

**Comment by yaichenbaum** [comment]
Merging with #1100.
