### ISSUE TITLE
Changing attributes in properties does not update item in detail view

### ISSUE THREAD

**Issue by Hefaistos68** [files-community/Files#2988]
**The bug**
When changing attributes in the Properties window of an item (file or folder) the item icon is not updated to reflect the change. Only when changing ALSO the name, the item is updated.

**To Reproduce**
1) Select a file or folder in any location, open its properties, change the Hidden attribute and click OK. The item icon is not updated to reflect the new state.

2) Select a file or folder in any location, open its properties, alter its name by clicking on the current name, change the Hidden attribute and click OK. Now the item icon is updated to reflect the new state together with the new name.

**Expected behavior**
Update icon state to reflect the hidden attribute without changing the name.

**Comment by gave92** [comment]
What happens if you change attribute only but hit "refresh"?

**Comment by Hefaistos68** [comment]
> What happens if you change attribute only but hit "refresh"?

Updates the icon correctly

**Comment by Hefaistos68** [comment]
Just tried to repro it cleanly, started the Files App, selected a folder, opened it, selected a file, right click -> properties, enabled Hidden, clicked on Ok -> app disappeared.

Application Error in Event log:
```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2021-01-13T16:50:51.0768167Z" /> 
  <EventRecordID>27550</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>AUP-AS</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>Files.exe</Data> 
  <Data>1.0.0.0</Data> 
  <Data>5ff23af1</Data> 
  <Data>ucrtbase.dll</Data> 
  <Data>10.0.19041.546</Data> 
  <Data>43cbc11d</Data> 
  <Data>c0000409</Data> 
  <Data>000000000007287e</Data> 
  <Data>1944</Data> 
  <Data>01d6e9c8b0a0360a</Data> 
  <Data>C:\Program Files\WindowsApps\49306atecsolution.FilesUWP_1.0.0.0_x64__et10x9a9vyk8t\Files.exe</Data> 
  <Data>C:\WINDOWS\System32\ucrtbase.dll</Data> 
  <Data>e7cf56b5-5d1f-49e9-b288-1a5ac16ac3f8</Data> 
  <Data>49306atecsolution.FilesUWP_1.0.0.0_x64__et10x9a9vyk8t</Data> 
  <Data>App</Data> 
  </EventData>
  </Event>
```

**Comment by gave92** [comment]
Thanks for the info. I'm closing this as duplicate as both issue listed are already tracked. I'll post their reference here.

**Comment by Hefaistos68** [comment]
duplicate of #2785
