### ISSUE TITLE
Duplicates of files/folders with Cache enabled

### ISSUE THREAD

**Issue by tristansuttle** [files-community/Files#2989]
-->

**Describe the bug**
If the "Cache Files and Folders for Better Performance" is enabled under experimental features, it duplicates all files and folders within the app. Note: they are not actually duplicating. Opening "File Explorer" shows only one copy of each. So the there is an issue with cache in the "File" app. Also, this so far only seems to impact network attached drives, and does not effect the local "C:" Drive.

**To Reproduce**
1. Launch App
2. Click on any network drive
3. Click on a separate drive or location
4. Go back to original drive and everything is doubled, then tripled, and so on.

**Expected behavior**
I expect to not see multiples of files and folders.

**Screenshots**
![Screenshot (2)](https://user-images.githubusercontent.com/41719615/104480875-5085fd80-5582-11eb-8cc3-958a2aaf4c6e.png)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 [19042.685]
 - App version: [v1.0.0.0]

**Additional context**
Closing the app clears out the issue, as does turning off the feature. 

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5809925/debug.txt)

**Comment by gave92** [comment]
Thanks for the report. The issue has been resolved and the fix will be included in the next version
