### ISSUE TITLE
Refreshing after Creating New Folder Shows Too Many Folders

### ISSUE THREAD

**Issue by redkian** [files-community/Files#2990]
**Describe the bug**
In a network share, I navigated to a folder with a single sub-folder. I then created a new sub-folder and Files did not show it to me. So I hit Refresh and then I had two of the original sub-folder and one of the new one. Every time I hit refresh I saw a copy of each folder get added to my view. Checking in File Explorer, I see that everything is fine so this is a visual bug only.
![explorer_LJg8R8tNnZ](https://user-images.githubusercontent.com/27744606/104483929-85438600-557d-11eb-9d65-d3ef05548c04.png)
Note that Files is on the left and File Explorer is on the right.

**To Reproduce**
1. Create new folder in network share
2. Folder does not show. Refresh (F5 OR button OR context menu)
3. Duplicates shown
4. Refresh again
5. More duplicates added
6. Rinse and repeat as many times as you like

**Expected behavior**
I expected to not have to refresh after creating a new folder. However, if I do have to refresh I expect to not see additive copies of the existing folders.

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175] 20H2 19042.685
 - App version: [v0.11.0] v1.0.0

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?
YES! This happened again when reloading the app. I used the Jump List to get back to the folder (love that!!) and it showed 2 more copies. Everything I saw prior plus 2 new ones as it refreshed on its own.
![ApplicationFrameHost_u0yOcLWUzs](https://user-images.githubusercontent.com/27744606/104484448-2d594f00-557e-11eb-964b-680d7d976c0c.png)

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find the log file manually by following [this](https://github.com/files-community/Files/wiki/Opening-the-log-file) guide.
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5810064/debug_fulltrust.txt)

**Comment by gave92** [comment]
Workaround is turn off "Enable file cache" option in Files setting

**Comment by redkian** [comment]
Thanks! That did work. Would be great if you could fix the caching but this certainly helps.

**Comment by gave92** [comment]
@redkian thanks for confirming. The issue with caching had been solved and will be included with the next version
