### ISSUE TITLE
Network Share Navigation

### ISSUE THREAD

**Issue by redkian** [files-community/Files#2991]
**Is your feature request related to a problem? Please describe.**
I haven't spent a ton of time in the app yet but I have noticed that network shares are not easy to use. As an IT professional I was able to get there once I figured where to click but mapped drives don't seem to come through in the app. Network share load times are also pretty terrible. File Explorer can load the share in less than a second but Files takes 2-3 seconds for a small share and more if there are a lot of files or folders to list out.

**Describe the solution you'd like**
A speed improvement. More obvious navigation for network shares

**Describe alternatives you've considered**
I have not considered any alternatives. However, in my job I spend a lot of time in network shares and this speed issue makes files a non-starter for it. In my home life I also spend a lot of time working with network shares for my media server and again, this becomes problematic and time consuming.

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?
Not sure you need this, but I am running Windows 10 on multiple machines varying between 20H2 and Insider Dev Channel. Desktops and Dell 2-in-1

**Comment by gave92** [comment]
Merging with #2932
