### ISSUE TITLE
Add an option to show checkboxes for accessible multi-select

### ISSUE THREAD

**Issue by EasyRhinoMSFT** [files-community/Files#2992]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
As in Windows Explorer, Files should provide optional checkboxes in the file list to allow impaired users to more easily select multiple items.

**Describe alternatives you've considered**
N/A

**Additional context**
None

**Comment by yaichenbaum** [comment]
Merging with #290.

**Comment by yaichenbaum** [comment]
@EasyRhinoMSFT Thank you for opening this issue, I am merging it with #290 since it's a similar feature request.
