### ISSUE TITLE
Quick Look doesn't update when selecting other files with the keyboard.

### ISSUE THREAD

**Issue by ignasicl** [files-community/Files#2993]
**Describe the bug**
Quicklook is previewing with space button but it doesn't update when I scroll to another image like it does in File Explorer.

**To Reproduce**
1. Go to any folder and select any file.
2. Press space bar.
3. Press down arrow or up arrow.
4. In order to see an update I have to press space again. 

**Expected behavior**
In vanilla File Explorer, Quicklook updates automatically without the need to press the space bar again.

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2 19042.746]
 - App version: [v1.0.0.0]

**Comment by gave92** [comment]
See #1773
