### ISSUE TITLE
Feature request: Recent files widget should follow the "Open items with one click" setting

### ISSUE THREAD

**Issue by WillC34** [files-community/Files#2994]
I recently installed this program on my PC and I really like using it. I much prefer the experience to the Windows File Explorer. As a musician, I download a lot of .pdf sheet music to practice, and when I double clicked on a file in the 'recently opened' tab, the same file opens twice. This could come down to me missing a particular setting, or that this could only apply to .pdf files that open in Microsoft Edge. 

1. Open a new instance of the app
2. Navigate to the 'recently opened' section
3. Double click on a file
4. See that the same file opens twice

Expectations:
I thought that when I double clicked on the file to open it, it would launch just like any other program or file in Windows. This could once again come down to be missing a setting, even though I confirmed that 'open files with single click- was disabled.

Desktop:
 - OS Version: Windows 10 20H2 , build 19042.746
 - App version: v.1.0

**Comment by yaichenbaum** [comment]
@WillC34 The behavior on the recent files widget is by design, perhaps we should align it with the setting you mentioned in order to make this more intuitive for users.

**Comment by WillC34** [comment]
@yair100 thank you very much!

**Comment by gave92** [comment]
Mering with newer #6074
