### ISSUE TITLE
Files itemlist duplicates after refreshing trough the button

### ISSUE THREAD

**Issue by MeltixDev** [files-community/Files#2997]
**Describe the bug**
This bug appears when looking inside a device memory (in this case, my own smartphone). Whenever i reload the list trough the refresh button, the list items gets duplicated.

**To Reproduce**
1. Attach a device or smartphone
2. Open device's storage
3. Open a folder
4. Refresh the list

**Expected behavior**
The list should just be reloaded and show the updated list of file. The files list items should not get duplicated.

**Screenshots**
![image](https://user-images.githubusercontent.com/43494249/104503669-a8a01c80-55e1-11eb-8df6-9c88a31867ae.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Home 19042.685
 - App version: [v1.0.0.0]

**Additional context**
The problem keeps presenting itself even after restarting the app.

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5810814/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5810815/debug_fulltrust.txt)

**Comment by gave92** [comment]
Workaround is to disable the "Enable file cache" option in Files settings
