### ISSUE TITLE
Add "Date created" to the column

### ISSUE THREAD

**Issue by sara945** [files-community/Files#2998]
**Is your feature request related to a problem? Please describe.**
I have been using Windows since 2001 (Windows XP) and Windows File Explorer always has the option to add "Date created" to the column.

This timestamp - Date created (crtime) - is very important for me and Files has no function where the user can add "Date created" to the column.

**Describe the solution you'd like**
Just add "Date created" that users can add it to the column.

**Describe alternatives you've considered**
There is no alternative, I use Files because of the beautiful design and I don't want to use Windows File Explorer anymore.

**Additional context**
Here is a screenshot of my Windows 10 (20H2) device with Files (1.0.0.0) and Windows File Explorer.

You can see on the screenshot that Windows File Explorer has "Date created".

![Capture](https://user-images.githubusercontent.com/77406557/104508268-4565b880-55e8-11eb-9d0a-44338f71a7ce.PNG)

**Comment by ahmednrana** [comment]
This is much need feature

**Comment by gave92** [comment]
Date created column has been added.
