### ISSUE TITLE
Keep "Date created" when copying local files and folders

### ISSUE THREAD

**Issue by sara945** [files-community/Files#2999]
**Is your feature request related to a problem? Please describe.**
I am very frustrated that Files does not keep the "Date created" when copying local files and folders.

**Describe the solution you'd like**
Files keep the "Date created" timestamp when copying local files and folders, just like the source.

**Describe alternatives you've considered**
There is no alternative.

**Additional context**
Currently, Files keeps only for "Date modified" (`mtime`) when copying local files and folders.

But for "Date created" the support is missing. That means you just have to use the same behavior as for "Date modified".

**Comment by gave92** [comment]
This is the same behaviour as windows explorer isn't it?
At most the issue is that the creation date resets when *moving* files

**Comment by sara945** [comment]
> This is the same behaviour as windows explorer isn't it?
It is the same behavior as Windows File Explorer. But I want the user to be able to change it.

I know only one file manager (GUI) on Windows that keeps creation date when copying local files and folders. Should I name the software or am I not allowed?

> At most the issue is that the creation date resets when _moving_ files

Is there any way to change this behavior?
I want to keep the original timestamp, which is the creation date.

I know robocopy via cmd supports it.
https://en.wikipedia.org/wiki/Robocopy

**Comment by gave92** [comment]
@sara945 you're surely allowed to name it!
In nay case I was merely wanted to confirm that this is a "feature request" and not a "bug report".
Adding an option to keep the creation date on copy is something we can totally consider and we thanks you for the suggestion.
The issue of losing the date when moving instead is a known problem we're already working to fix

**Comment by sara945** [comment]
> you're surely allowed to name it!

Here is the name: Multi Commander
There is also a portable version. Just download it from this site.
http://multicommander.com/downloads

A store edition of Multi Commander is also available.
https://www.microsoft.com/store/apps/9NBLGGH4NFS5

I can confirm that it keeps the creation date for copied folders and files for all Microsoft file systems (NTFS, exFAT and FAT32) that users use on a daily basis.

> * Adding an option to keep the creation date on copy is something we can totally consider and we thanks you for the suggestion.

That would be very good because I like Files, it uses the Microsoft Fluent design.

A question if the option is available, will the option be enabled by default or is the behavior dependent on what Microsoft does with Windows File Explorer by default in future Windows 10 versions?

**Comment by gave92** [comment]
The default option value will likely match the current explorer behavior but you'll be able to switch it on and off independently of what Microsoft decides to do with explorer.

**Comment by Josh-65** [comment]
Is this an issue in the preview version? https://files.community/download/preview
