### ISSUE TITLE
NFS File shares duplicate the folder contents with every refresh

### ISSUE THREAD

**Issue by pironic** [files-community/Files#3001]
**Describe the bug**
When navigating an nfs share via windows 10 it seems to add a file to the list every time it refreshes regardless of already being shown... this means that duplicates appear if you hit f5 or navigate away and back to a folder.

**To Reproduce**
1. Go to an nfs mounted share via a letter.
2. Press f5 to show the contents of the folder more than once.

**Expected behavior**
either merge the contents from the last time the nfs server returned the folder contents with the existing list or replace it entirely. only 1 copy of each file should be shown in a folder.

**Screenshots**
![image](https://user-images.githubusercontent.com/541154/104512043-d9189400-55aa-11eb-950f-a4e54f8e8bd8.png)
![image](https://user-images.githubusercontent.com/541154/104512078-e33a9280-55aa-11eb-9ef2-7266339b7d69.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Pro 20H2 19042.685 w/ Windows Feature Experience Pack 120.2212.1070.0
 - App version: v1.0.0.0

**Additional context**
Can close the app and restart the app and it still cached the folder contents...

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5811155/debug.txt)

**Comment by gave92** [comment]
Workaround is to turn off the "Enable file cache" option in Files settings.
