### ISSUE TITLE
Arabic language pack

### ISSUE THREAD

**Issue by mumenAlmadaineh** [files-community/Files#3002]
Hi

I want to thank the application developer for this wonderful work. I wish an Arabic language package to be added to the application and I am ready to help with translation

**Comment by mumenAlmadaineh** [comment]
Hi

I want to thank the application developer for this wonderful work. I wish an Arabic language package to be added to the application and I am ready to help with translation

**Comment by yaichenbaum** [comment]
@mumenAlmadaineh Thank you for opening this issue, you can find instructions on translating Files over [here](https://files-community.github.io/docs/#/articles/translating-files).
