### ISSUE TITLE
Selection rectangle visible under StatusBarControl

### ISSUE THREAD

**Issue by tsvietOK** [files-community/Files#3004]
**To Reproduce**
1. Start selecting using mouse
2. Move cursor outside window

**Screenshots**
![image](https://user-images.githubusercontent.com/20501502/104533199-9d1d1780-561a-11eb-8a49-c7a554872d58.png)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2 19042.746]
 - App version: [v1.0.3]

**Comment by nvi9** [comment]
Removing the line below is a possible solution for this issue:

https://github.com/files-community/Files/blob/5f6571da945a6d8378ca355ed10e6b73dbb10fe5/Files/Views/ModernShellPage.xaml#L205

@yair100 is it needed there, or can be removed? AFAIK it was added in #2851

**Comment by yaichenbaum** [comment]
@nvi9 The line was added as part of the dual pane feature so it shouldn't be removed.

**Comment by nvi9** [comment]
> @nvi9 The line was added as part of the dual pane feature so it shouldn't be removed.

True, didn't checked that 😐

**Comment by yaichenbaum** [comment]
@nvi9 This can probably be solved by editing the thickness of the border depending on which pane is selected.

**Comment by nvi9** [comment]
@yair100 I'm not sure how this could be done. Maybe some of you who worked on the redesign recently might have a better overview of this part.

The idea I've had recently on this topic is to move the `SelectionRectangle` Canvas from GridViewBrowser and GenericFileBrowser to ModernShellPage, but it's just theoretical, no trials yet.

**Comment by yaichenbaum** [comment]
@gave92 Do you have any thoughts on this?

**Comment by gave92** [comment]
Lately I think the selection rectangle is actually above the status bar for some reason..

**Comment by yaichenbaum** [comment]
@gave92 There are really two different issues, one is that there is extra space underneath the status bar, and the second is that the selection rectangle overlays on top of the status bar.

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
