### ISSUE TITLE
Changing theme breaks text components color

### ISSUE THREAD

**Issue by DarkEyeDragon** [files-community/Files#3005]
**Describe the bug**
Changing theme and (spam) clicking the back button results in text components not being displayed in the right color (see screenshot)

**To Reproduce**
1. Go to Settings
2. Switch to dark mode
3. Spam click the back button (it sometimes hangs too?)
4. Go back to settings and change theme back to light (or os default)
4. Boom broken text components

**Expected behavior**
Text should be the proper color. It seems to correct itself when the components move out ov view and back into it (probably redrawn with the correct color)

**Screenshots**
![image](https://user-images.githubusercontent.com/6131099/104532952-b5d4ff80-5611-11eb-8ecc-fe3d154d484e.png)
![image](https://user-images.githubusercontent.com/6131099/104533705-31837c00-5613-11eb-8f45-dcae9704b6da.png)

**Desktop (please complete the following information):**

OS Name: Microsoft Windows 10 Pro
Version: 10.0.19041 Build 19041

**Additional context**
It seems to only happen occasionally, i haven't found a way to get it to break every time.

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find the log file manually by following [this](https://github.com/files-community/Files/wiki/Opening-the-log-file) guide.

Log didn't show anything worthwhile so didn't include it

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
