### ISSUE TITLE
Unable to pin "Downloads" folder to the sidebar.

### ISSUE THREAD

**Issue by ShubhamVerma1811** [files-community/Files#3006]
**Describe the bug**
Unable to pin "Downloads" folder to the sidebar.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open "Downloads" folder.
2. Right-click anywhere and select "Pin to the sidebar"

**Expected behaviour**
The "Downloads" Folder should get pinned to the sidebar.

**Screenshots**
![Screenshot (436)](https://user-images.githubusercontent.com/25576658/104533641-c5b40a00-5638-11eb-95ae-46cc607d85a2.png)
![Screenshot (437)](https://user-images.githubusercontent.com/25576658/104533642-c77dcd80-5638-11eb-9d17-f564c309284f.png)

**Desktop (please complete the following information):**
 - OS Version: Edition	Windows 10 Home Single Language
Version	20H2
Installed on	‎02-‎Jun-‎20
OS build	19042.685
Experience	Windows Feature Experience Pack 120.2212.551.0

 - App version: 1.0.0.0

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?
YES

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find the log file manually by following [this](https://github.com/files-community/Files/wiki/Opening-the-log-file) guide.
[debug.txt](https://github.com/files-community/Files/files/5811923/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5811924/debug_fulltrust.txt)

**Comment by gave92** [comment]
Thanks for the report.
Do you find this happening only with the downloads folder? (except for hidden folders which are known not to pin)
Could you see what happens if you manually add the download folder path to this file?
`%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalCache\PinnedItems.json`

**Comment by Hefaistos68** [comment]
Tried that here, works just fine for me. Works too for Documents, Music, Pictures, etc.

**Comment by Hefaistos68** [comment]
>
> (except for hidden folders which are known not to pin)
> 
Just tested: pin a folder, make it hidden, restart Files, it no longer appears as pinned, also is removed from the PinnedItems.json file

**Comment by gave92** [comment]
Thanks for the additional info.
Hidden folders are known not to work -> tracked in #2763

I didn't get if you tested manually adding the Downloads folder to the PinnedItems.json and if that solves the issue?

**Comment by Hefaistos68** [comment]
> I didn't get if you tested manually adding the Downloads folder to the PinnedItems.json and if that solves the issue?

Sorry, been unclear. I meant, adding the "Downloads" folder works by pinning, just as expected. No need to edit the JSON file.

**Comment by ShubhamVerma1811** [comment]
>     * %localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalCache\PinnedItems.

I didn't try it every folder, but with most of them and yes only issue with DOwnloads.
Tried adding it manually in JSON file and when I restart Files it gets removed from the JSON
It's like the JSON file is only removing the "downloads" path everything else remains.

`{
  "items": [
    "C:\\Users\\Shubham\\Documents",
    "C:\\Users\\Shubham\\Pictures",
    "C:\\Users\\Shubham\\Music",
    "C:\\Users\\Shubham\\Videos",
    "C:\\Users\\Shubham\\Desktop",
    "C:\\Users\\Shubham\\Downloads",
    "D:\\Codes"
  ]
}`

gets changed to 

`{
  "items": [
    "C:\\Users\\Shubham\\Documents",
    "C:\\Users\\Shubham\\Pictures",
    "C:\\Users\\Shubham\\Music",
    "C:\\Users\\Shubham\\Videos",
    "C:\\Users\\Shubham\\Desktop",
    "D:\\Codes"
  ]
}`

Apart from this The menu on right click takes 1-2sec to load, not sure if its already reported.

**Comment by gave92** [comment]
@ShubhamVerma1811 thanks for the check. It may be that you have some permissions issue on the downloads folder.
Slow context menu has been reported 👍

**Comment by ShubhamVerma1811** [comment]
@gave92 Omg when I checked the properties now, The folder was hidden 🤦‍♂️
No idea when I did that.
Anyways I unhide it, everything works.
Sorry from my side for opening the issue.

**Comment by gave92** [comment]
No problem. Hidden folders are a known issue.
