### ISSUE TITLE
Add an option to switch to Compact theme of WinUI for desktop usability

### ISSUE THREAD

**Issue by trama** [files-community/Files#3009]
In a desktop productivity vision, I am a little bit frustrated by the really large paddings and borders of the different controls, while a more dense view in Files would enhance productivity for classic mouse and keyboard interaction.

Hence, what I am proposing is to add for an _option_ in the settings panel to enable this feature for those who prefer a non-touch interaction.

 This should not be regarded as something so much strange, imho. For instance, in OSX the Finder applications has really narrow spaces (borders and paddings) and no one complain about that, even more it is one of the most loved productivity app on a Mac...
I mean, I totally understand the fact that WinUI (3) cares about unified interaction, so taking touch interaction into consideration, and that using WinUI those are the common spacing applied. However, both needs might be served: the needs of a set of users that interact through touch screens -hence needing larger controls-in this way would not impact on the productivity needs of desktop/power users.  In the end, the same WinUI3 APIs already took this into consideration by design.

To be honest, I think that Files has all the potentialities (given the current development point) to be even better (For instance, Files has a native dual pane, multiple tabs is more efficient), but being more compact in desktop environments would be fantastic.

I was looking into the WinUI controls that already foreseen a "compact" mode in their default resources:
https://docs.microsoft.com/it-it/windows/uwp/design/style/spacing

There is an example already provided by Microsoft about this: https://github.com/Microsoft/Xaml-Controls-Gallery
and maybe some more tunings are needed.
I typically refrain from asking, but in this case I am not able to try to implement a pull request by myself, since I am not a GUI programmer.

I hope there should be an option soon. You have carried out a fantastic work so far, and Files is totally stable now...so that I would use it for each task, provided it is as usable as other for power users.

**Comment by yaichenbaum** [comment]
@trama A compact mode is something we have been wanting to do for a while. Being that Files is built for Windows, things are a little different from what you would expect on MacOS. Windows supports touch screens, and a lot of controls were built with that in mind. That being said, the majority of users use the mouse and keyboard to interact with Files, making the large touch targets unnecessary. Unfortunately the DataGrid control we currently use doesn't support the compact theme so we will need to wait for the new WinUI DataGrid to implement this correctly.

**Comment by yaichenbaum** [comment]
Merging with #1940.

**Comment by pritster5** [comment]
Absolutely phenomenal job with this you guys. 

It's a shame that the compact mode relies on the WinUI DataGrid implementing it. Is there anyway to raise this issue to them?

And is there any timeframe we can expect on compact mode?   
It's the only real issue that still exists before this becomes objectively superior to the default file explorer IMO.
