### ISSUE TITLE
Display refresh issues when files added outside of files to network share

### ISSUE THREAD

**Issue by PMillard5000** [files-community/Files#3011]
I have seen an issue that if you browse to a network share within files app and then save a file to this share in another application then the files app does not automatically refresh to review the new files that have been added.

Also, when you click the refresh button to refresh the view to see the new files the Files app shows multiples of the same file with the same file name when there is and can only be one unique filename.

![files_error](https://user-images.githubusercontent.com/25932017/104577990-0bc99780-5652-11eb-94df-e5b17a99beb6.jpg)

**Comment by gave92** [comment]
To fix the issue of duplicate files workaround is to disable the "Enable file cache" option
Missing autorefresh is tracked in #2042
