### ISSUE TITLE
Visual state of selected items not correctly updated

### ISSUE THREAD

**Issue by Hefaistos68** [files-community/Files#3012]
**The bug**
When you drag-select items and then unselect them by clicking outside the column area in detail view, the previous first selected item remains in its visual selected state until you hover the mouse over it again.

In this item below, only the first item is selected, the others are previously selected items.
![image](https://user-images.githubusercontent.com/8855055/104576616-56e2ab00-5650-11eb-85d0-3038096800b6.png)

**To Reproduce**
Open any folder, switch to detail view, drag select one or more items (click and drag over one one or more items) then click in the area outside the last column. The selection made will be unselected but the first item remains in its selected, unfocused, visual state.

**Expected behavior**
Reset all items visually to their unselected, unfocused state.

**Screenshots**
![Files - drag select](https://user-images.githubusercontent.com/8855055/104577802-d0c76400-5651-11eb-9b36-937055776ce2.gif)

**Desktop (please complete the following information):**
- OS Version: Windows 10 Home, Version 20H2, OS Build 19042.746, Windows Feature Experience Pack 120.2212.551.0
- App version: 1.0.0.0
- Hardware: Processor Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz 1.99 GHz
Installed RAM 12.0 GB (11.9 GB usable)
System type 64-bit operating system, x64-based processor
Pen and touch No pen or touch input is available for this display

**Comment by gave92** [comment]
In addition to visual issue after you click outside the datagrid you can't start a selection rectangle again on the same items

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main.
