### ISSUE TITLE
Support drop targets 

### ISSUE THREAD

**Issue by Hefaistos68** [files-community/Files#3013]
**Enhance usability and compatibility**
When dragging items in the file or folder view (any view style) applicable drop targets are not recognized and thus an item can not be dropped onto it.

Compare here Files and Explorer actions
![Files - drop target Explorer](https://user-images.githubusercontent.com/8855055/104578927-3831e380-5653-11eb-9f25-8f791fcf001d.gif)
![Files - drop target Files](https://user-images.githubusercontent.com/8855055/104578933-39631080-5653-11eb-9b57-9865b0ab4226.gif)

**Comment by gave92** [comment]
Correct, only dropping in folders is currently supported

**Comment by yaichenbaum** [comment]
@Hefaistos68 This feature request was implemented with #4737.
