### ISSUE TITLE
Maintain selection and focus when switching layout mode

### ISSUE THREAD

**Issue by Hefaistos68** [files-community/Files#3014]
**Feature for usability**
When making a selection in any view and then switching to another view, the selection is not maintained and the focus returns to the first item in the view. 

The expected behaviour would be that the selection is maintained and the focus (visual and otherwise) remains in the view on the item(s) as in the previous view.

**Comment by yaichenbaum** [comment]
@gave92 You can probably confirm, but I think your recent changes to the layout modes partially solves this when switching between the grid layouts.

**Comment by gave92** [comment]
Yes needs to be tested but I think it only resets selection going from list to tiles/grid

**Comment by gave92** [comment]
Merging with #2656
