### ISSUE TITLE
Bug: Drag selection does not work in tiles or grid view when started on item

### ISSUE THREAD

**Issue by Hefaistos68** [files-community/Files#3015]
**The bug**
When in tiles or any grid view, starting a drag-select does not work when you start ON an item. Only when started outside any item.

**To Reproduce**
See screen recording

**Expected behavior**
- Be able to drag-select from anywhere
- Only drag item if it's selected

**Screenshots**
![Files - drag select](https://user-images.githubusercontent.com/8855055/104580982-daeb6180-5655-11eb-8746-595f1b9d5912.gif)

**Comment by DevMark-code** [comment]
Thank you

**Comment by Josh-65** [comment]
This is expected as dragging an item will move/copy it too wherever you stop holding left click.

**Comment by yaira2** [comment]
> This is expected as dragging an item will move/copy it too wherever you stop holding left click.

File Explorer works around this by only dragging an item if it was already selected.

**Comment by hishitetsu** [comment]
> File Explorer works around this by only dragging an item if it was already selected.

File Explorer starts selection if the item isn't selected _AND_ you start dragging from the edge of the grid. If you start dragging from the center of grid, the item will be dragged even if it wasn't selected.
