### ISSUE TITLE
Empty folders shown without icon

### ISSUE THREAD

**Issue by Hefaistos68** [files-community/Files#3016]
**The bug**
Sometimes empty folders appear without the folder icon, without any icon at all.
![image](https://user-images.githubusercontent.com/8855055/104581623-bb086d80-5656-11eb-8dbc-cc4d79d41ee4.png)

**To Reproduce**
Could not find an pattern to repro it, seems to happen sometimes when you switch folders after drag-drop operations.

**Desktop (please complete the following information):**
OS Version: Windows 10 Home, Version 20H2, OS Build 19042.746, Windows Feature Experience Pack 120.2212.551.0
App version: 1.0.0.0
Hardware: Processor Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz 1.99 GHz
Installed RAM 12.0 GB (11.9 GB usable)
System type 64-bit operating system, x64-based processor
Pen and touch No pen or touch input is available for this display

**Log file**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5813937/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/5813938/debug.txt)

**Comment by gave92** [comment]
Merging with #2542.

Thanks for the insight that it only happens with empty folders ;)
