### ISSUE TITLE
DFS Network Shares are shown mutiple times !

### ISSUE THREAD

**Issue by Majocchi** [files-community/Files#3017]
**Describe the bug**
Folders are shown mutiple times on mapped Network share

**To Reproduce**
map a network share with DFS targets

[https://docs.microsoft.com/en-us/windows-server/storage/dfs-namespaces/dfs-overview#:~:text=%20To%20install%20DFS%20by%20using%20Server%20Manager,to%20install.To%20install%20the%20DFS%20Namespaces...%20More%20](url)

**Screenshots**
[![network-share-bug.png](https://i.postimg.cc/cC5F1DjT/network-share-bug.png)](https://postimg.cc/YLY6bxtm)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 2004 and 20h2 (19042)
 - App version: [v1.0.0.0]

**Additional context**
Workaround:
When disabling cache in experimetal settings the behavior is correct
[![experimentell.png](https://i.postimg.cc/XXSygdy4/experimentell.png)](https://postimg.cc/gLsJzwDT)

**Comment by gave92** [comment]
Thanks for the report. The issue has been fixed and you have already discovered the workaround 👍
