### ISSUE TITLE
Crashing when hitting enter on empty folder path

### ISSUE THREAD

**Issue by hugomostar** [files-community/Files#3018]
**Describe the bug**
Application crashes when hitting enter on empty folder path.

**To Reproduce**
Click on current folder path, delete everything and hit enter.

**Screenshots**
![image](https://user-images.githubusercontent.com/11904128/104584775-64556080-5663-11eb-928f-6316295acbef.png)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 Pro 2004 19041.685]
 - App version: [v1.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5814091/debug.txt)

**Comment by gave92** [comment]
Fixed in #3007
