### ISSUE TITLE
Windows 10X support

### ISSUE THREAD

**Issue by MBuelowius** [files-community/Files#3019]
**Is your feature request related to a problem? Please describe.**
Since we got a new Windows 10X build and 10X is near to release it would be great if there was a version of Files at launch of 10X.

**Describe the solution you'd like**
10X doesn't support full trust apps but Files is one so need would a version of files without full trust

**Describe alternatives you've considered**
Alternatively, you could just ignore Windows 10X

**Additional context**
Windows 10X

**Comment by yaichenbaum** [comment]
@MBuelowius Unfortunately apps like Files are not supported on Windows 10X. Implementing a separate version of Files is technically possible, but it would come at the expense of most the features currently in Files, and it would be closer to the File Explorer app already found on Windows 10X. Is this still something you are interested in?

**Comment by MBuelowius** [comment]
I'm still interested in it since Files has a more powerful UI with Tabs, Dual Pane and so many excellent features enriching the user experience. If 10X support isn't something you have in mind I could create my own fork and try to implement it myself while getting better with C#.

**Comment by yaichenbaum** [comment]
Features such as tabs would remain, but many of the features that you described as "enriching the user experience" rely on APIs that are not supported on Windows 10X.

**Comment by yaichenbaum** [comment]
@MBuelowius Files already works on Windows 10X, however, some features like deeper shell integration won't work due to the structure of the operating system.
