### ISSUE TITLE
Thumbnails loading cause the OneDrive files to be downloaded to device

### ISSUE THREAD

**Issue by dckface** [files-community/Files#3020]
**Describe the bug**
After opening a folder on OneDrive and switching into thumbnails view, Files causes all the files in the folder to get downloaded. When "Free up space" is used on the files afterwards, the thumbnails disappear and are not shown. That is in contrast with behaviour of File Explorer, which is able to show files thumbnails without downloading them from OneDrive.

**To Reproduce**
1. Go to OneDrive folder.
2. Browse to any directory with pictures, which were all set to online access ("Free up space").
3. Watch all files to get downloaded.
4. After right click -> Free up space, and after refreshing, the thumbail is gone.

**Expected behavior**
I'd expect Files to have the same behaviour as File Explorer, i.e. to obtain thumbnails of OneDrive file without downloading the file itself, or possibly to cache the thumbnails, so they're available even after the files on OneDrive are made online.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Pro, Version 20H2, OS build 19042.746
 - App version: v1.0

**Comment by gave92** [comment]
Thanks for this report.
Can you confirm this is not an issue when viewing the folder in List view?

**Comment by dckface** [comment]
Yes, when the directory is viewed in List view, the files aren't downloaded. 

Also, I just did multiple tests in different directories on OneDrive, and the thumbnails sometimes got loaded without the files being downloaded, so it doesn't seem like consistent bug. However, sometimes they're stuck on default thumbnail icon, and it takes multiple refreshes before they're loaded.

**Comment by yaichenbaum** [comment]
Is this still an issue in the latest preview build? https://files.community/download/preview
