### ISSUE TITLE
Missing D:\ (SD card slot drive) on Surface Pro 4

### ISSUE THREAD

**Issue by dckface** [files-community/Files#3021]
**Describe the bug**
On Surface Pro 4, the SD card slot drive (D:\) is never visible in Files. However, it is still accessible by explicitly typing "D:\" in the address bar.

**To Reproduce**
1. Insert SD card into the slot (it is normally visible and accessible in File Explorer).
2. Open Files.
3. The drive isn't shown anywhere (neither in Home or in the sidebar).
4. Typing "D:\" into the address bar and hitting enter causes Files to correctly access the SD card drive.

**Expected behavior**
The drive should be visible in both Home and sidebar.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Pro, Version 20H2, OS build 19042.746
 - App version: v1.0

**Comment by gave92** [comment]
Could you attach the log files to the issue description? Thanks!

**Comment by dckface** [comment]
If I insert the SD card after opening Files, the drive is shown as removable drive.

Here are both log files. In the debug.txt, you can see that I added the SD card after opening Files at the time 16:39:03. Afterwards, I closed the app and opened it again at 16:40:05, and the drive wasn't listed this time.
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5815389/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/5815387/debug.txt)

Also, it's worth noting that the SD card slot in SP4 behaves differently from the usual SD card slot, as it has dedicated icon (the picture below), it never triggers the AutoPlay prompts after inserting an SD card to it, and unlike other removable devices, the inserted SD card is never visible in navigation pane in File Explorer.
![Screenshot 2021-01-14 164550](https://user-images.githubusercontent.com/3797371/104613907-fec79b00-5687-11eb-94bf-36d10dd02e8c.png)
