### ISSUE TITLE
Duplicate Files and folders are showing on connecting external storage 

### ISSUE THREAD

**Issue by souvik362** [files-community/Files#3023]
**Describe the bug**
Showing duplicate file instances when using FILES to view my phone files by connecting usb  **See the video in Screenshot Section**

**To Reproduce**
1. Connect a phone with usb and turn on file sharing option
2. Go inside the phone storage , [your phone name] > internal shared storage > android
3. now go back  to internal shared storage 

**Expected behavior**
There should be one main file showing, not duplicates

**Screenshots**
A video showing the bug
https://user-images.githubusercontent.com/58888934/104607087-7278a080-56a6-11eb-9afa-28ae84b55250.mp4

**Desktop:**
 - OS Version: [Windows 10  20H2 19042.746]
 - App version: [v1.0.0]

**Additional context**
This problem occur even after restarting the app and reconnecting the usb

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5815185/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5815188/debug_fulltrust.txt)

**Comment by gave92** [comment]
Thanks for the report. The issue has been fixed.
For now the workaround is to turn off the "Enable file cache" setting

**Comment by DevMark-code** [comment]
I’m JUST learning Git from GitHub and I’m liking it EXCEPT a bunch of people will come in and fix up and finish My program before I even have a chance to finish reading everything. I love the concept but I NEED TO LEARN HANDS ON OR ELSE THE LESSON WONT STICK IN MY MIND. I know I’m slow in completing them but one I do have a life that requires My  benevolent soul to dominate her. 12.20/21.01

**Comment by souvik362** [comment]
@DevMark-code Your thought is learning center which actually great, this is a public repository and have many helpful people like you,

If you want to learn handson try 
 [good first issue](https://goodfirstissue.dev/)
Or 
Learn from successful closed pull request.
