### ISSUE TITLE
Ejecting removeable drives should close related tabs

### ISSUE THREAD

**Issue by Hefaistos68** [files-community/Files#3026]
**The bug(s)**
Related to #2516, #2916, #2884

When you remove a USB drive, any open tab/window remains open. If you don't close them manually, next time Files is starting you get this error:
![image](https://user-images.githubusercontent.com/8855055/104624032-fd4ba200-568a-11eb-9d36-25e62f62dea1.png)

Opening a new Window will re-sort the drives list:
![image](https://user-images.githubusercontent.com/8855055/104628547-44886180-5690-11eb-9960-bec4d65ca12f.png)

**Desktop (please complete the following information):**
 - App version: v1.0.0.0

**Comment by gave92** [comment]
@Hefaistos68 thanks for the report. We usually try to have each issue separate.
- When a USB drive is connected and any tab/window is open with it, you can not eject it  -> #2884
- When you open it from the drives list, the content is still shown -> #2916 
- Not removed from drive list -> #2516
