### ISSUE TITLE
Tab navigation in Properties window not working (correctly)

### ISSUE THREAD

**Issue by Hefaistos68** [files-community/Files#3027]
**The bug**
In the Properties windows of a file, where you have two tabs General and Detail, navigation by keyboard is clumsy and weird. One would expect to switch tab with Ctrl+Tab and Ctrl+Shift+Tab, both dont work. Tabbing around brings the focus on lots of controls, some not visually showing it, some strangely showing it. Eventually one ends on the tabs and can switch with the left/right arrows.

![Files - prop navigation](https://user-images.githubusercontent.com/8855055/104630699-fe80cd00-5692-11eb-9d8f-7c2398124096.gif)

**Expected behavior**
At least Ctrl+Tab should work, and on the details page some items should not take focus

**Desktop (please complete the following information):**
 - App version: 1.0.0.0

**Comment by yaichenbaum** [comment]
Merging with #2040.
