### ISSUE TITLE
UNC path with one subfolder - F5 causes repeated duplicate expansion of existing folder.

### ISSUE THREAD

**Issue by DualBrain** [files-community/Files#3032]
**Describe the bug**

After install, browsed to a UNC path ("\\styx\zeus\voices\v12) which displays a single folder (which is correct) of "processed".  Press F5, now have two folders named "processed".  Use the Refresh menu item, now have 3 folders named "processed".  Exit and restart the application, still have problem and can continue to expand.  There should only be one...

**To Reproduce**

See description.

**Expected behavior**

If I press F5, the content of the folder should be what is seen... not many copies of a single folder.

**Screenshots**

n/a

**Desktop (please complete the following information):**
 - OS Version: Windows 10 with all the latest updates
 - App version: v1.0.0.0

**Additional context**

Does this problem occur again after restarting the app? Yes.

**Log file**

n/a

**Comment by yaichenbaum** [comment]
@DualBrain Thank you for reporting this issue, a patch is now in certification and will hopefully roll out in a couple of days.
