### ISSUE TITLE
Control + Tab only works when used twice on the last tab

### ISSUE THREAD

**Issue by KibSquib48** [files-community/Files#3037]
**Describe the bug**
When on the last tab, `ctrl+tab` must be hit twice to switch back to the first tab

**To Reproduce**
1. Go to the last tab
2. Hit `ctrl+tab`
3. Tab doesn't switch, do it again
4. _Now_ the tab switches.

**Expected behavior**
The tab should switch immediately the first time the keyboard shortcut is used.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.685
 - App version: 1.0.0.0

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
