### ISSUE TITLE
App is freezing every 4 seconds on Linux local Network (Synology)

### ISSUE THREAD

**Issue by Wanooo0** [files-community/Files#3043]
'Files' is freezing every 4 seconds on Linux local Network (Synology) - The app is very slow on network and its freezing when browsing folders, open new tab etc.
Windows 10 64-bit 2004 (19041.746)
Synology DS718+ | DSM 6.2.3-25426 Update 2

https://user-images.githubusercontent.com/77484326/104706871-f28d1d80-571b-11eb-898e-d3799113a619.mp4

**Comment by yaichenbaum** [comment]
@Wanooo0 Is this still an issue in v1.3?
