### ISSUE TITLE
Folder size

### ISSUE THREAD

**Issue by PaymonK** [files-community/Files#3046]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
In the list of files and folders, the Size column shows the file size, but the folder column does not. A cached approximate folder size will be a great help for many day to day working scenarios. It can be visually indicated with an icon that it's approximate, along with a button to refresh it on demand if required.

**Describe alternatives you've considered**
There are third party tools that do it separately. But it's really required in the normal file explorer.

**Additional context**

**Comment by gave92** [comment]
This is something we have looked at in the past and decided against implementing due to the performance issues involved. 
The recently added cache feature may somewhat help with this though.
