### ISSUE TITLE
Folders duplicate on a network drive

### ISSUE THREAD

**Issue by TjarkD** [files-community/Files#3053]
**Describe the bug**
https://user-images.githubusercontent.com/59528960/104730454-5de5e800-573a-11eb-8b66-ace923d5c777.mp4

**To Reproduce**
1. Go to a network drive 
2. Click on refresh
3. See error

**Expected behavior**
No folder duplication

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1909 18363.1316
 - App version: v.1.0.0.0

**Comment by yaichenbaum** [comment]
@TjarkD This issue should resolved with the latest update to the store v1.1.

**Comment by Darkwater23** [comment]
I downloaded the store version just a couple of days ago and just had this issue today. Did the store get updated recently?

<img width="633" alt="Screenshot 2021-01-15 075653" src="https://user-images.githubusercontent.com/6684788/104740067-1c8b1380-570d-11eb-93e6-de93996f9854.png">
<img width="579" alt="Screenshot 2021-01-15 080024" src="https://user-images.githubusercontent.com/6684788/104740076-1dbc4080-570d-11eb-8214-1548e5f89688.png">

**Comment by yaichenbaum** [comment]
@Darkwater23 v1.1 just started rolling out today so it's possible you didn't get the update yet. You can double check what version you have from the about page in settings.
