### ISSUE TITLE
Incorrect drive type

### ISSUE THREAD

**Issue by duckheadsoftware** [files-community/Files#3054]
**Describe the bug**
Drive A: is represented as a Floppy Disk - When in fact on my machine it is an internal hard drive

**To Reproduce**
1. In Disk Manager, change a second drives' drive letter to A:

**Expected behavior**
It's type is of hard disk

**Comment by gave92** [comment]
Thanks for the report. Drive A is just assumed to be a floppy drive (a bit old school)

**Comment by duckheadsoftware** [comment]
> Thanks for the report. Drive A is just assumed to be a floppy drive (a bit old school)

LOL - I guess so, I remember the world before floppy's came to be - I often map A: to a NAS or USB drive nowadays. (HEIC to JPEG - dev)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #3211.
