### ISSUE TITLE
Feature or Option to hide Folder & Files starting with "."

### ISSUE THREAD

**Issue by smjltd** [files-community/Files#3055]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when Folders and Files used by visual studio on my home directory 

**Describe the solution you'd like**
Option in Settings to Hide All Files and Folders starting with ".", Like in Linux & Mac

**Describe alternatives you've considered**
I tried asking windows team for years but with no result, when i found your application i was fascinated with capabilities and immediately shifted to it.

**Comment by gave92** [comment]
Merging with #2587
