### ISSUE TITLE
Ordenar archivos

### ISSUE THREAD

**Issue by breidyfunes** [files-community/Files#3056]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by XPoppyX** [comment]
Podrías dar más detalles sobre tu problema o petición por favor

**Comment by breidyfunes** [comment]
Cuando se muestra iconos grandes no se puede ordenar, como la galería de imágenes, la opción de ordenar los archivos esta solo si se ven en forma de detalle. Explorador de Windows si tiene esta opción.

![Captura de pantalla 2021-01-17 133916](https://user-images.githubusercontent.com/48229287/104853890-6d476b80-58c9-11eb-9a6d-d481b38c3bc1.png)

![Captura de pantalla 2021-01-17 133151](https://user-images.githubusercontent.com/48229287/104853787-b4812c80-58c8-11eb-91c6-4f20f3b8f4f6.png)

**Comment by gave92** [comment]
@breidyfunes you can change sort option by right clicking in the empty space.
