### ISSUE TITLE
Same folder shown multiple times for network folder

### ISSUE THREAD

**Issue by jain65731** [files-community/Files#3057]
**Describe the bug**
Whenever i enter network drive from the Files app each folder is seen multiple times
**To Reproduce**
1. Go to 'Network Drive'

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/77452439/104739306-91416a80-576c-11eb-8078-50068829d701.png)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find the log file manually by following [this](https://github.com/files-community/Files/wiki/Opening-the-log-file) guide.

**Comment by gave92** [comment]
Workaround is to turn off the "Enable file cache" option is file settings
