### ISSUE TITLE
Option to consider for P/Invoke and Native COM interfaces - Vanara

### ISSUE THREAD

**Issue by dahall** [files-community/Files#3058]
**Is your feature request related to a problem? Please describe.**
Not really, other than providing a potential means of accelerating development of native capabilities.

**Describe the solution you'd like**
I maintain a set of assemblies that P/Invoke over 200,000 methods from the Windows API (https://github.com/dahall/Vanara), including all of the Shell, Kernel, User and other core options. Each library is nearly 100% complete in its capture of the native functions available in the respective DLLs. I'd like to partner with you to integrate those libraries into this project to provide greater modularity and improvement of both code bases.

**Describe alternatives you've considered**
My project is already being used by a number of other UWP, WPF and WinForm projects as it builds against all major versions of .NET, .NET Core and .NET Standard. Or, you can keep doing it native to the project.

**Additional context**
Give it a look and let me know if you'd like to proceed together. I think it could be a valuable partnership.

**Comment by gave92** [comment]
@dahall hi, you may remember me. I opened a few issues for the Banana library xD
We are already using your amazing library for a host at features

**Comment by gave92** [comment]
@dahall I wanted to ask you for some time if you have any plan to make your library available on NET5 (currently looks like it's not supported)

**Comment by dahall** [comment]
Great news! I think that as of about a month ago, all of the 66 libraries support the .NET 5.0 Windows variant.

**Comment by dahall** [comment]
If you have a road map of some of the features you will implement, show me where to find them and I will make sure Vanara has the API calls you need for them.

**Comment by dahall** [comment]
@gave92 Glad to connect the person to the project. I was wondering, do you have an interface-based model for exposing services that provide TreeView and main window content (with toolbar and context menus)? If so, I'm curious if you'd be interested in extending the use of this program to supporting some of the MMC solutions like Task Scheduler, Device Manager, Service Manager, etc.? I've been looking for a solution for a while to let me modernize the Task Scheduler. My other popular library is [Task Scheduler](https://github.com/dahall/TaskScheduler) and I get regular requests to provide an updated management tool.

**Comment by duke7553** [comment]
@dahall We have been leveraging Vanara for native functionality, and will continue to look for ways to make Files feel at home on Windows desktop whether it's through your great library or CsWin32. Your library has served us well for some time now, so I'll close this issue.
