### ISSUE TITLE
Once a file/folder is selected, I am not able to open a file or folder through double-click

### ISSUE THREAD

**Issue by szaimen** [files-community/Files#306]
**Is your feature request related to a problem? Please describe.**
Once a file/folder is selected, I am not able to open a file or folder through double-click because it let me rename this file/folder.

**Describe the solution you'd like**
Once a file/folder is selected and you click on it again, files uwp should wait whether I want to make a double click on that file/folder or click just one time and not instantly let me rename the file/folder.

**Describe alternatives you've considered**
So a step by step guide would be:
1. select a file/folder
a. double click on that selected file/folder to open it or
b. click one time that selected file/folder to rename the file

Currently it always starts the renaming and doesn't check if the user wanted to do a double click.

**Additional context**
I am on v0.6.5

BTW: If I select a file, click anywhere else to deselect it and click on this file again to select it, the renaming process starts. (shouldn't start the renaming process but just select the file)

**Comment by yaichenbaum** [comment]
@jeffsieu can you reproduce?

**Comment by duke7553** [comment]
This is reproducable and I'm planning on including this in our immediate v0.6.6 release.

**Comment by duke7553** [comment]
I guess I spoke too soon. I cannot reproduce this.

**Comment by yaichenbaum** [comment]
"There's a couple bugs around inline renaming
 - Can't open something if it's already selected (tries to rename)
 - Select, deselect, and select the same thing again. It tries to rename instead of selecting it.
 - Doesn't work for icon layout"

**Comment by R3voA3** [comment]
This needs to be fixed. It destroys the workflow when using Files UWP. Alternatively, what about adding a setting to toggle this off/on?

**Comment by yaichenbaum** [comment]
I agree, I am pretty sure this comes down to a WinUI issue and in fact they are working on a new DataGrid control but we should definitely try to find a workaround.
Once we finish modularizing settings then it should be fairly easy to add an option to turn this off as well until we do find a workaround.

**Comment by duke7553** [comment]
@R3voA3 This is a bug with the Toolkit DataGrid control we're using. I cannot find a way to fix it. Sorry, I'm looking into other solutions

**Comment by yaichenbaum** [comment]
@R3voA3 I found a temporary solution is to click further to the right of the selected item in order to open it.

**Comment by yaichenbaum** [comment]
There is a new pull request https://github.com/duke7553/files-uwp/pull/624 that adds a feature flag which lets you turn off double tap to rename.

**Comment by XPoppyX** [comment]
Is it possible to add a delay or something like that to the rename function when clicking?, about 500 milliseconds maybe, so it gives you enough time to double click

**Comment by yaichenbaum** [comment]
This issue should be resolved with #2142.
