### ISSUE TITLE
Refreshing directory of mapped drive duplicates all entries

### ISSUE THREAD

**Issue by mikevh** [files-community/Files#3060]
ack

**Describe the bug**
When viewing a mapped drive then clicking the refresh icon or pressing F5, the file list is duplicated. If there was one file name foo.txt, after refreshing there are now two files shown named foo.txt

**To Reproduce**
1. Map a network drive
2. Click the mapped drive in the left pane
3. Note the list of files in the mapped drive.
4. Click the refresh icon or press F5

**Expected behavior**
List of files is refreshed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.746
 - App version: v1.0.0.0

**Additional context**
The file are not actually copied, just listed twice.  Each additonal refresh creates another copy of the file. The duplicate entries seem to persist during app restart.

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find the log file manually by following [this](https://github.com/files-community/Files/wiki/Opening-the-log-file) guide.

**Comment by mikevh** [comment]
This does _not_ repro on v1.1.0.0

**Comment by gave92** [comment]
Yep this was fixed in 1.1
