### ISSUE TITLE
Folders are on bottom instead of top when sorting by date

### ISSUE THREAD

**Issue by tony-ze-yi** [files-community/Files#3063]
**Describe the bug**
When sorting by descending date, the folders are on the bottom vs. on the top in the Explorer.

**To Reproduce**
1. Switch to details and sort by descending date
2. Switch to large icons view mode

**Expected behavior**
The folders should be on the top; however, they are on the bottom.

**Screenshots**
![bug](https://user-images.githubusercontent.com/24402057/104753441-fd4cb000-5725-11eb-800a-a000199f8249.PNG)

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 20H2 19042.685]
 - App version: [v1.1.0.0]

**Additional context**
The bug does still happen when restarting the app.

**Log file**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5821784/debug_fulltrust.txt)

**Comment by yaichenbaum** [comment]
@tony-ze-yi This issue should be resolved with #3069.
