### ISSUE TITLE
Rename if only change letter-case.

### ISSUE THREAD

**Issue by PMExtra** [files-community/Files#3064]
**Describe the bug**
Rename a file or folder that only change the letter-case.

**To Reproduce**
1. Create a folder `example`
2. Rename it with `Example`
3. Files regard the new name `Example` is conflict with the exists name, it will pop a dialog to hint this.

**Expected behavior**
Just rename it without any disturb.

**Screenshots**
![image](https://user-images.githubusercontent.com/11289158/104756968-70423f00-5797-11eb-851b-d731e06d50a3.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2
 - App version: 1.1.0.0

**Comment by yaichenbaum** [comment]
@PMExtra This issue should be resolved with #3067.
