### ISSUE TITLE
UAC privilege evaluation if write to a system path.

### ISSUE THREAD

**Issue by PMExtra** [files-community/Files#3065]
**Is your feature request related to a problem? Please describe.**
When I create or paste a file to the drive root or system path (eg. `Program Files` or `Windows`), explorer will pop a UAC dialog to evaluate privilege. But Files will do nothing without any hint.

**Describe the solution you'd like**
Just the same behavior as explorer.

**Describe alternatives you've considered**
Pop a message to hint users if any operation that forbidden.

**Comment by gave92** [comment]
Merging with #2713
