### ISSUE TITLE
Add the option to pin tabs

### ISSUE THREAD

**Issue by zadquieljlp** [files-community/Files#3068]
It will be great to be able to pin tabs, so whenever I open the app those pinned tabs will be open

**Comment by gave92** [comment]
@zadquieljlp you can choose which tabs will open on app start. You can find the options in Files settings > Startup

**Comment by zadquieljlp** [comment]
Right, but I mean that it is in the menu options when you right-click the tab, something like this:
![image](https://user-images.githubusercontent.com/63886303/104791301-b637dc80-5770-11eb-96b3-13221b230c33.png)
And that works with double pane tabs.

**Comment by yaichenbaum** [comment]
@zadquieljlp v2.1.5 has support for reopening that most recent set of tabs.
