### ISSUE TITLE
package depends on a framework that could not be found. Provide the framework "Microsoft.UI.Xaml.2.5"

### ISSUE THREAD

**Issue by cmarkwick365** [files-community/Files#3070]
**Describe the bug**

Attempted to install with Files-1.1.Msixbundle in Powershell:
Add-AppxPackage D:\Downloads\Files-1.1.Msixbundle  

**Log file**
Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF3, Package failed updates, dependency or conflict            validation.
Windows cannot install package 49306atecsolution.FilesUWP_1.1.0.0_x64__et10x9a9vyk8t because this package depends on a
framework that could not be found. Provide the framework "Microsoft.UI.Xaml.2.5" published by "CN=Microsoft
Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and
minimum version 2.52012.2002.0, along with this package to install. The frameworks with name "Microsoft.UI.Xaml.2.5"
currently installed are: {Microsoft.UI.Xaml.2.5_2.5
Windows cannot install package 49306atecsolution.FilesUWP_1.1.0.0_x64__et10x9a9vyk8t because this package depends on a
framework that could not be found. Provide the framework "Microsoft.UI.Xaml.2.5" published by "CN=Microsoft
Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and
minimum version 2.52012.2002.0, along with this package to install. The frameworks with name "Microsoft.UI.Xaml.2.5"
currently installed are: {Microsoft.UI.Xaml.2.5_2.52012.2002.0_x86__8wekyb3d8bbwe}
NOTE: For additional information, look for [ActivityId] c758918e-eb74-0003-f9b6-5bc774ebd601 in the Event Log or use
the command line Get-AppPackageLog -ActivityID c758918e-eb74-0003-f9b6-5bc774ebd601
At line:1 char:1
+ Add-AppxPackage D:\Downloads\Files-1.1.Msixbundle
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (D:\Downloads\Files-1.1.Msixbundle:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

**Comment by cmarkwick365** [comment]
Found duplicate.

**Comment by FunctionDJ** [comment]
For reference: #2930
