### ISSUE TITLE
Support ~/ to type paths from the home folder

### ISSUE THREAD

**Issue by eamodio** [files-community/Files#3072]
**Is your feature request related to a problem? Please describe.**
I often try to type/navigate to folders in my home folder, and using `C:\Users\<username>` is less than ideal 😄 

**Describe the solution you'd like**
Allow the use of `~/` or `~\` to mean the home folder, so I can type `~/foo` and get to `C:\Users\username\foo`

**Comment by yaichenbaum** [comment]
@eamodio This issue should be addressed with #3098.
