### ISSUE TITLE
Folder Tree Option and Right-Click support on Drag and Drop

### ISSUE THREAD

**Issue by TheAndyMac** [files-community/Files#3076]
**Is your feature request related to a problem? Please describe.**
I use drag and drop with the right-click menu together with the folder view in Explorer on many occasions, especially when organising files. Files does not seem to offer this currently. Also I often create copies of files by drag and drop with right-click to select the Copy option.

**Describe the solution you'd like**
To make Files as easy to use as Explorer it would be really helpful to offer a tree-view of the folders, which can be extremely useful for drag and drop copying/moving (and other Right-Click drag and drop operations) as well as making it easier to find specific folders. This could be a secondary left bar (in a similar way as OneNote for Windows 10 behaves) or under the favourites, in a similar way to Explorer.

In addition, having access to the Right-Click options when dragging and dropping, with the minimum Copy/Move options but also the ability for these to be extended with e.g. tools that provide Hard/Symbolic links, etc. would complete this. It would also allow easy drag and drop Copying of a file in the same folder.

**Describe alternatives you've considered**
Can't think of any other ways to do this.

**Additional context**
Specifically targeted at mouse/keyboard navigation, so that I can use just one file manager for 99%, if not 100% of use cases.

**Comment by gave92** [comment]
Thanks for the suggestions.
See #1396 for right click drag and #3051 for folder tree
