### ISSUE TITLE
Make option to close second pane more visible

### ISSUE THREAD

**Issue by TheAndyMac** [files-community/Files#3077]
**Is your feature request related to a problem? Please describe.**
Having set Files to be dual pane view, it then opens in that mode unless I go to settings, switch the mode off and then restart Files.

**Describe the solution you'd like**
~~Having the option to open the second pane from e.g. the More Options menu or the Display Options menu would make this more discoverable. Maybe even having a right-click context option when on a folder to "Open in Second Pane".~~ *Removed as this is already there if Two Panes option is on - thanks for the clarification @gave92*

Once open, having a close option [X] on the pane as well as similar options in the More Options or Display Options would make this more user friendly as a way of switching it on/off. *Still think that this would be a great addition to the (not so obvious) Ctrl-Shift-W and drag options detailed by @gave92* 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by gave92** [comment]
@TheAndyMac the possibility to do what you describe should be already present.
- Right clicking on folders should give you an option to open the folder in the second pane, same when right clicking on a sidebar item 
- In the "..." menu in the navigation bar you should have an option to open a new pane
- You can close a pane by dragging it all the way to the right or by pressing Ctrl Shift W
- In settings you can choose whether new tabs open with two panes open or not

**Comment by TheAndyMac** [comment]
@gave92 thanks - have updated my original description and title to reflect this.

**Comment by gave92** [comment]
Thanks for the clarification. Merging with #2941
