### ISSUE TITLE
Multiple Windows Open on right click

### ISSUE THREAD

**Issue by rusti4** [files-community/Files#3078]
**Describe the bug**
When right clicking on a folder in the sidebar and selecting properties, it resizes the main window, flickers, then opens multiple property windows for the same folder.

**To Reproduce**
1. Right click a folder in the sidebar.
2. Left click properties
3. Watch everything flash and the main window resizes
4. Multiple property windows open.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.746; Windows Feature Experience Pack 120.2212.551.0
 - App version: 1.0.0.0

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find the log file manually by following [this](https://github.com/files-community/Files/wiki/Opening-the-log-file) guide.
[debug.txt](https://github.com/files-community/Files/files/5824412/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5824413/debug_fulltrust.txt)

**Comment by gave92** [comment]
@rusti4 Thanks for the report. Could you confirm that the issue of multiple windows opening does not happen after a fresh app start but only after e.g you went to the settings page and back or after switching tabs? If so this issue has been already fixed 👍

**Comment by rusti4** [comment]
Thanks, yes i noticed that the app has recently updated itself also, and it hasn't occurred today.
