### ISSUE TITLE
Add more date/time formats or the option to set a custom one

### ISSUE THREAD

**Issue by sara945** [files-community/Files#3082]
**Is your feature request related to a problem? Please describe.**
I have been using Windows File Explorer since Windows XP and like the time format that is displayed by default in the list view column. It is more precise for me and has more details.

**Describe the solution you'd like**
An option should be added to change the time format, just like Windows File Explorer.
More time format should also be supported where users can select manually. An example to display the seconds and milliseconds because NTFS file system stores it for files and folders.

**Describe alternatives you've considered**
There is no alternative.

**Additional context**
Here is a screenshot of how it looks in Windows File Explorer compared to Files.

https://github.com/files-community/Files/issues/2998

Files shows at folder for example:
- 12 minutes ago
- Saturday, December 7, 2019
- 1 hours ago

Windows File Explorer shows this for the same folders:
- 1/13/2021 9:05 PM
- 12/07/2019 10:14 AM
- 1/13/2021 7:23 PM

**Comment by gave92** [comment]
You can find this option in Files Settings, there's an option called "Date Format" which you can set to "System" to get the same date fomat as explorer

**Comment by sara945** [comment]
@gave92 
But it lacks seconds and milliseconds + customize it for power users.

**Comment by gave92** [comment]
@sara945 I thought you just wanted to use the same format as the default one of explorer. Instead you would like more date format options in additions to the two already present, correct?

**Comment by sara945** [comment]
> @sara945 I thought you just wanted to use the same format as the default one of explorer. Instead you would like more date format options in additions to the two already present, correct? Perhaps an option to set any custom date/time format?

Exactly that I still want additional option to set custom date/time format.

**Comment by Barina** [comment]
But when you choose system you can change the format to whatever you like.
Like this way:
![image](https://user-images.githubusercontent.com/370379/104839702-818c6800-58cb-11eb-8074-244391955f6d.png)

I agree its less "simple" or maybe too cumbersome for some users.. but it's limitless.

**Comment by dynamiquel** [comment]
I don't think the app cares about your system's date format. My system is set to dd.mm.yyyy but the app is showing everything in mm.dd.yyyy. It's also displaying everything in 12 hour instead of 24 hour.

I agree with the other guy about just allowing us to customise it ourselves. It will make everyone happy and will probably be easier for the developers.

**Comment by gave92** [comment]
Merging with #2207
