### ISSUE TITLE
Add support for Amazon Drive

### ISSUE THREAD

**Issue by v-aravind** [files-community/Files#3084]
**Describe the bug**
My Amazon drive is not showing up under drives alongside google drive, dropbox, onedrive, etc. it also does not appear under my user account folder - it does appear fine in windows explorer, just not in this app.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Enterprise 20H2
 - App version: v1.1

**Comment by gave92** [comment]
Thanks for this report. I've changed this to feature request as Files atm needs to add support for each cloud provider separately.
Workaround is to manually pin the Amazon drive folder to the sidebar.

**Comment by v-aravind** [comment]
Thanks. However, I can't manually pin the Amazon Drive Folder because the Amanzon Drive Folder does not even show up in the explorer window, so I can't right click on it to pin it.

**Comment by yaichenbaum** [comment]
@v-aravind This feature was implemented with #3091.
