### ISSUE TITLE
Unexpected and color of file when switching theme

### ISSUE THREAD

**Issue by kimlimjustin** [files-community/Files#3085]
**Describe the bug**
Unexpected and color of files in the explorer when switching theme.

**To Reproduce**
1. Open `files`
2. Switch app theme from Windows default to light theme
3. Reopen `Files`
4. Switch app theme from light theme to windows default

**Expected behavior**
Files on `files` displayed with the color what it is supposed to be

**Screenrecord**
https://user-images.githubusercontent.com/61906684/104816127-9cb79300-584b-11eb-9735-eeecdc1a72d8.mp4

**Desktop (please complete the following information):**
 - OS Version: Microsoft Windows 10 Home Single Language 10.0.18363 N/A Build 18363
 - App version: 1.1.0.0

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5824665/debug.txt)

**Comment by gave92** [comment]
Merging with #3005
