### ISSUE TITLE
Files Ran Into a Problem when Path is Empty

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#3086]
**Describe the bug**
The `Files` application will close unexpectedly when a path is empty then we hit enter.

**To Reproduce**
1. Open `Files`
2. Go to `Path / Tab`
3. Clear Everything so it's clear / empty
4. Hit `Enter` Key
5. See error

**Expected behavior**
It will back to Base Directory / Home

**Screen Record**

https://user-images.githubusercontent.com/69080584/104816156-c4a6f680-584b-11eb-839c-c5ca85fc4e0c.mp4

**Desktop (please complete the following information):**
 - OS Version: Windows 10 OS Version 2009 (Build 19042.746)
 - App version: v1.1.0.0

**Additional context**
This problem occurs every time although I have restarted the application.

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find the log file manually by following [this](https://github.com/files-community/Files/wiki/Opening-the-log-file) guide.
- [debug.txt](https://github.com/files-community/Files/files/5824667/debug.txt)

**Comment by gave92** [comment]
Thanks for this report. I can confirm this issue has been fixed in the development branch and the fix will ship with the next public version.

**Comment by stanleyowen** [comment]
Thanks!
