### ISSUE TITLE
Multitasking settings are not getting saved

### ISSUE THREAD

**Issue by coldwinds** [files-community/Files#3088]
Hello,

Is it possible to list tabs vertically or like a tree but not horizontally? 

Because if you have too many tabs opened there will not be enough space to list them all in one screen.

It will work like tree-style-tab in firefox or sidewise-tree-style-tabs in google chrome: 

https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/

https://chrome.google.com/webstore/detail/sidewise-tree-style-tabs/biiammgklaefagjclmnlialkmaemifgo

**Comment by duke7553** [comment]
@coldwinds Hi. We have an option for this under multitasking in the app settings. Is this what you had in mind?

![image](https://user-images.githubusercontent.com/20365014/104974110-c6e09080-59c4-11eb-8c91-59f4ba40fde5.png)

**Comment by coldwinds** [comment]
Hello, @duke7553 I enabled this option but looks like the tabs are still listed in horizon, and I have relaunch the app, am I missing something?

**Comment by yaichenbaum** [comment]
@coldwinds That's a bug, and I think there is another issue for that. Does everything work properly once you restart the app?

**Comment by rusti4** [comment]
When I went to this setting; it didn't allow me to even select the bubble. It doesn't activate. It's clickable and hoverable, but not activated.

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
