### ISSUE TITLE
Add an optional preview pane on the right side of the screen

### ISSUE THREAD

**Issue by scottr10** [files-community/Files#3089]
I would like the option to add a preview pane on the right side of the screen so I can quickly see files I might open without having to fully open them such as pictures, documents and many other things. This would help save time and get the right files quickly and efficiently.
![Screenshot (18)](https://user-images.githubusercontent.com/77546805/104819393-2db24e00-57fb-11eb-90a5-ebf6ec77c813.png)

**Comment by gave92** [comment]
Thanks for the suggestion. Merging with #130
