### ISSUE TITLE
Integration with third-party software

### ISSUE THREAD

**Issue by ReyMagos** [files-community/Files#3090]
**Feature description**
Third-party software like JetBrains IDE provides opening file in explorer, but it always opens files in default explorer, even when Files replaced it through regedit.

**Additional context**
I understand that replacing default file manager with Files is unsupported, but may be this way exists. Is it feature planned in the future or is this problem belongs to a third-party software?

**Comment by gave92** [comment]
Hi @ReyMagos  the reg files included below should do the trick.
All the usual warning about registry editing apply, most notably:
- We take 0 (zero) responsibility for anything bad that may happen
- Take a backup of the registry before running this scripts
[SetUnsetFilesAsDefault_Bad.zip](https://github.com/files-community/Files/files/5825020/SetUnsetFilesAsDefault_Bad.zip)
Extract the two files and place them *on the desktop*
Run `SetFilesAsDefault_Bad.reg`
"Open in explorer" commands should now be opening in Files
