### ISSUE TITLE
Cut/Copy Paste Doesn't Work At All

### ISSUE THREAD

**Issue by PrecisioData** [files-community/Files#3092]
**Describe the bug**
I cannot copy or cut any files. I tried several locations but nothing works i.e. downloads, documents, thumb drive, etc...

The only workaround I found was to open another FILES window and drag and drop from the source to the destination. For some reason, this works.

**To Reproduce**
1. Right click, select copy.
2. Go to a destination such as downloads, right click and select paste.
3. Nothing happens. No user dialog, error or anything.

**Expected behavior**
Copy/Cut and Paste function correctly.

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: Windows 10 - Version 10.0.18363 Build 18363
 - App version: 1.1.0.0

**Additional context**

* I tried using other file managers on the windows store such as "Modern File Explorer" and I don't have these issues.
* My boot drive is a RAID0 setup with 4 SSDs on a PCIExpress card. The only reason I mention this is that that a friend of mine has the same hardware configuration as me, and he also cannot copy/cut paste files. This could be completely irrelevant and maybe related to some other HW configuration that we have in common. 
* If I try files on my Windows 10 laptop that has a standard SSD configuration, I can use FILES normally.

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find the log file manually by following [this](https://github.com/files-community/Files/wiki/Opening-the-log-file) guide.

**Comment by userexit** [comment]
Commenting to note that cutting and pasting works fine for me. In regards your Additional context, I do not have a RAID0 setup.

**Comment by Z-beam** [comment]
Hi! I have the same problem!
Just add, hotheys Ctrl+C and Ctrl+V aren't work too. 
OS: Windows 10 19042
App Version: 1.1

**Comment by mengxun1437** [comment]
i have the same problem too

**Comment by babs232** [comment]
For me file copy internally works but the copy dialog never appears. In the ongoing tasks view it gets stuck at 0% & when the copy is completed, it shows 100%. No update given in-between.

**Comment by yaichenbaum** [comment]
@PrecisioData is this still an issue in Files v2.0?
