### ISSUE TITLE
Manually re-arranging libraries in side panel

### ISSUE THREAD

**Issue by Keefaetana** [files-community/Files#3094]
**Is your feature request related to a problem? Please describe.**
I'm used to a certain order of libraries in the side panel of the default explorer view. Files deviates from that order by default.

**Describe the solution you'd like**
I'd love a way to drag and drop the libraries in any order I prefer, for example having Downloads just under Documents.

**Comment by gave92** [comment]
Merging with #1069
Until it's implemented , the not-so-handy workaround is to manually edit this file:
"%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalCache\PinnedItems.json"
