### ISSUE TITLE
Windows terminal support

### ISSUE THREAD

**Issue by shassaan** [files-community/Files#3097]
I want to open the windows terminal in a certain folder as we have in windows explorer.

Add option for open with windows explorer in the context menu.

I have to manually go to that path in the windows terminal

we can take help from the windows terminal repo for the same issue.

**Comment by gave92** [comment]
Hi this should be already possible. Look in Files settings and set the following option to "Windows Terminal"
![image](https://user-images.githubusercontent.com/9673091/104822586-e43a2100-5843-11eb-9e1a-f23e08c9b369.png)

**Comment by shassaan** [comment]
got it !
