### ISSUE TITLE
Box Sync not recognized

### ISSUE THREAD

**Issue by v-aravind** [files-community/Files#3100]
My Box drive folder is not showing up under Drives. 

Please add support for Box as a cloud drive. 

Desktop (please complete the following information):
    OS Version: Windows 10 Enterprise 20H2
    App version: v1.1

**Comment by gave92** [comment]
Box support is already present so this sounds like a bug.
Could you check if this file is present on your pc and check if it contains the box folder path?
"%localappdata%\Box\Box\data\shell\sync_root_folder.txt

**Comment by v-aravind** [comment]
The issue appears to be that my sync_root_folder.txt file is in a different path %localappdata%\Box Sync\
The box folder itself is located here C:\Users\XXXX\Box Sync

I use Dropbox, Box and Amazon (for various reasons)... 

I have always been on the look out for a 'modern' file explorer so hope you won't mind a few bug reports as I check out this app more in detail :-)

**Comment by gave92** [comment]
@v-aravind thanks for the info. Apparently there are two Box clients: Box sync and the (newer?) Box Drive which is already supported. It shouldn't be too hard to add Box sync support as well.

**Comment by yaichenbaum** [comment]
@v-aravind This issue should be resolved with #3242.
