### ISSUE TITLE
Renaming a file can cause a reproducible crash

### ISSUE THREAD

**Issue by m4lebranche** [files-community/Files#3104]
**Describe the bug**
Renaming a file directly after another file (in the same directory) was renamed can cause a crash. 

**To Reproduce**
I reproduced this bug by having two files, "aa" and "ab" in the same directory, and have that directory sorted in a default way (alphabetically by title)
1. Rename "aa" file to "aaa" (can be anything else, as long as the sorting order is maintained, like "a1")
2. Press enter. That file will be renamed accordingly, and the pointer now points to the second file, "ab"
3. Try to rename "ab" via context menu or F2, and the program crashes

**Expected behavior**
renaming should work just fine

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: Windows 19042.746 (20H2)
 - App version: v1.0.0.0 (edit: tested in v1.1.0.0 and it crashes as well)

**Additional context**
Tested multiple times with renaming via context menu and F2. It seems that the bug occured when the first renaming procedure maintains the order of the file. But renaming "aa" after "ab" was renamed in a way that maintains the order (for example "ac") works just fine, so I might be wrong.

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5825625/debug.txt)

**Comment by gave92** [comment]
Merging with #3205
