### ISSUE TITLE
Issues with double-click to open folder/file

### ISSUE THREAD

**Issue by v-aravind** [files-community/Files#3106]
**Describe the bug**
When set to the default 'double click to open' mode, if you single click and then wait a second and click again, it opens the file/folder name for editing, that's fine. But if you single click and then double click the same file/folder, you can't open it, it opens the file/folder name again for editing. 

**To Reproduce**
1. Go to any folder
2. Single Click on file or sub-folder
3. Double Click on same file or sub-folder
4. See error (opens name for editing rather than opening the file/folder)

**Expected behavior**
When you single click to select a file/folder, and then you double click on the same file/folder, it should open it.

**Desktop (please complete the following information):**
- OS Version: Windows 10 Enterprise 20H2
- App version: v1.1

**Comment by gave92** [comment]
Thanks for the report. I can confirm this issue has been fixed in dev branch
