### ISSUE TITLE
Issue with single-click to open items after scrolling

### ISSUE THREAD

**Issue by v-aravind** [files-community/Files#3107]
**Describe the bug**
When set to the default 'open items with single click' mode, when you click on a folder that you need to scroll to reach, and then you go 'back' and scroll down and click on that same folder again (which is already selected from the previous click event, it does not open it.

**To Reproduce**

    In settings, enable the 'open items with single click' option 
    Go to any folder
    Scroll down to show a sub-folder which is outside the visible view (i.e. can only be seen if you scroll down)
    Single Click sub-folder to open it
    Go back to the parent folder
    Scroll down again and single-click on the same sub-folder as before (which should already be highlighted from previous click)
    See error (does not open the folder)

**Expected behavior**
The folder should open 

**Additional context**
This does not happen with folders which are visible without scrolling down. Those show the correct expected behaviour, even if you scroll. 

**Desktop (please complete the following information):**
    OS Version: Windows 10 Enterprise 20H2
    App version: v1.1

**Comment by yaichenbaum** [comment]
@winston-de is this still an issue with the new details layout?
