### ISSUE TITLE
Replace Folders with 'Recent Folders'

### ISSUE THREAD

**Issue by v-aravind** [files-community/Files#3108]
**Is your feature request related to a problem? Please describe.**
Recent Folders not shown anywhere, Recent items only shows files.

**Describe the solution you'd like**
Replace the Folders section with Recent Folders

**Describe alternatives you've considered**
Show recent folders in some other location, like sidebar, similar to Windows Explorer? But due to larger item size, this might not be a good idea.

**Additional context**
![File FR1](https://user-images.githubusercontent.com/69113302/104837565-51ce6780-58ad-11eb-91de-4afd16b80382.png)

**Comment by yaichenbaum** [comment]
Merging with #2718.
