### ISSUE TITLE
Add option in the settings to show checkboxes to select items.

### ISSUE THREAD

**Issue by Barina** [files-community/Files#3110]
**Is your feature request related to a problem? Please describe.**
It'll be nice to have the ability to "one hand select" items.

**Describe the solution you'd like**
Adding an option in the settings to enable checkboxes besides items to be able to add\remove items from selection. regardless of using the keyboard. (screenshots below)

**Describe alternatives you've considered**
N/A

**Additional context**
The equivalent option in Windows Explorer folder options:
![image](https://user-images.githubusercontent.com/370379/104839210-4b99b480-58c8-11eb-9911-c71d7edd4464.png)
A reference screenshot of the checkboxes in Windows File Explorer:
![image](https://user-images.githubusercontent.com/370379/104839152-0ecdbd80-58c8-11eb-99ba-2f51004e798e.png)

**Comment by gave92** [comment]
Merging with #299
