### ISSUE TITLE
Right click context menu for a folder within itself.

### ISSUE THREAD

**Issue by Barina** [files-community/Files#3111]
**Is your feature request related to a problem? Please describe.**
It's always frustrating when you need for example to go to the properties of the current folder, but right click on an empty area won't bring you the context menu you've expected. then you have to go "up" or "back" and right click the folder to access its context menu.

**Describe the solution you'd like**
Adding a basic right click context menu for the current folder when right clicking empty area within it.

**Describe alternatives you've considered**
N/A

**Additional context**
Equivalent feature in Windows File Explorer:
![image](https://user-images.githubusercontent.com/370379/104839457-f2328500-58c9-11eb-8279-11e0b7837ec1.png)

**Comment by gave92** [comment]
@Barina could you post a screenshot of the context menu you get in Files when right clicking the empty area? Properties menu item should be present

**Comment by Barina** [comment]
Oh.. so nothing happened anywhere when I right click in Files. So I just restarted my machine and now there's a legit context menu.
Maybe a first use bug? (I just installed Files :) )

**Comment by gave92** [comment]
Thanks @Barina I'm going to close this as the issue "fixed itself" xD. If you find additional problems related to this feel free to comment here and we'll reopen this.
