### ISSUE TITLE
"Open With" Button Seems not to Work In Specific Extension of File (.js, .py, etc)

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#3112]
**Describe the bug**
`Open With` button seems not to work in specific extension of file, such as Javascript (.js), Python (.py), etc. In `File Manager`, you will find out a several of options to like Open With Visual Studio Code.

**To Reproduce**
1. Open `Files`
2. Find any files' with either `js` or `py` extensions
3. Right Click and Click `Open With`
4. Nothing Happens

**Expected behavior**
It is going to pop out some options of app I would like to open with (such as Visual Studio Code)
![Bug](https://user-images.githubusercontent.com/69080584/104839893-c4b00080-58f6-11eb-8989-db27be316464.jpg)

**Screen Record**

https://user-images.githubusercontent.com/69080584/104839455-d643d900-58f3-11eb-8651-d0d41ce37c24.mp4

**Desktop (please complete the following information):**
 - OS Version: Windows 10 OS Version 2009 (Build 19042.746)
 - App version: Version 1.1.0.0

**Additional context**
This problem occurs every time although I have restarted `Files`

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find the log file manually by following [this](https://github.com/files-community/Files/wiki/Opening-the-log-file) guide.

- [debug.txt](https://github.com/files-community/Files/files/5825984/debug.txt)

**Comment by guilhermetod** [comment]
Same here. I'm also missing all the extra context menu option, such as "Open with code". I might be missing something, but I even did a fresh install and still not able to get the context menu like a few weeks ago.

![image](https://user-images.githubusercontent.com/53096593/109399115-a0950580-791f-11eb-8298-676b7a469749.png)


![image](https://user-images.githubusercontent.com/53096593/109399127-aee32180-791f-11eb-8ad9-d246f1acf81b.png)


[debug.txt](https://github.com/files-community/Files/files/6055311/debug.txt)

**Comment by stanleyowen** [comment]
This issue has been resolved in v1.5.67.0.
