### ISSUE TITLE
Add shell context menu to drives widget

### ISSUE THREAD

**Issue by Sayor0630** [files-community/Files#3114]
In windows explorer, I can copy or format on the context menu which comes by left-clicking on Local Disk. But your **Files** doesn't have that.

I think if you add this context to the main window of **Files** where I can select as windows explorer this would be very great.

![Screenshot (87)](https://user-images.githubusercontent.com/77576588/104845224-6be46600-58fe-11eb-8c87-45b3efe60392.png)
![image](https://user-images.githubusercontent.com/77576588/104845255-8cacbb80-58fe-11eb-8096-278820bb55c8.png)

*****************Sorry for my poor English!***********************

**Comment by josh-65** [comment]
Any updates on when this can be added?

**Comment by Sayor0630** [comment]
Unfortunately no.

**Comment by BanCrash** [comment]
All I can say is that this will be added when someone works on it. Since AFAIK no one is working on this there is no possible ETA.

**Comment by Sayor0630** [comment]
HMM

**Comment by Josh-65** [comment]
Merging with #5888
