### ISSUE TITLE
Add a real scrollbar

### ISSUE THREAD

**Issue by btxtiger** [files-community/Files#3115]
**Is your feature request related to a problem? Please describe.**
I always use the scrollbar to scroll. Yeah - despite I have a mouse wheel.

**Describe the solution you'd like**
Option to permanently display the scrollbar, instead of this thin line

**Describe alternatives you've considered**
Being able to control the thickness of the scrollbar, so it could get 100px

~~**Additional context**~~

**Comment by yaichenbaum** [comment]
@btxtiger You can adjust this from the Windows 10 Settings App > Ease of Access > Display Settings > Automatically hide scroll bars in Windows.

**Comment by jonaaix** [comment]
oh cool, thanks @yair100
