### ISSUE TITLE
Add icons for the different cloud providers

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#3116]
**Is your feature request related to a problem? Please describe.**
Right now, all cloud providers use the generic cloud icon, it might improve the user experience if there were different icons for each cloud provider.

**Describe the solution you'd like**
A solution might be to add custom glyphs to the custom glyph font family.

Dropbox [**uF10D**] - Google Drive [**uF10C**]
![Captura de pantalla 2021-01-17 171218](https://user-images.githubusercontent.com/61259627/104858731-245ed980-5900-11eb-80c2-a20f34e43af6.png)

iCloud [**uF110**] - OneDrive [**uF10E**]
![Captura de pantalla 2021-01-17 171547](https://user-images.githubusercontent.com/61259627/104858733-25900680-5900-11eb-848f-9abaecba0704.png)

Amazon Drive [**uF111**] - Mega [**uF10F**]
![Captura de pantalla 2021-01-17 172016](https://user-images.githubusercontent.com/61259627/104858735-25900680-5900-11eb-9249-5e8d8bc9365b.png)

**Comment by yaichenbaum** [comment]
@XPoppyX Any thoughts on this?

**Comment by XPoppyX** [comment]
with colors?

**Comment by yaichenbaum** [comment]
@XPoppyX That's a possibility, however, if we did that, we would need new icons for everything in the sidebar.

**Comment by XPoppyX** [comment]
ok, i'm going to look for monochrome icons

**Comment by XPoppyX** [comment]
Dropbox, Google Drive
![Captura de pantalla 2021-01-17 171218](https://user-images.githubusercontent.com/61259627/104854777-6fb8be00-58e7-11eb-9aba-d7b5212d0085.png)
Alternative:
![Captura de pantalla 2021-01-17 171045](https://user-images.githubusercontent.com/61259627/104854871-ef468d00-58e7-11eb-899d-a4da39fd61ed.png)

------------------
icloud, OneDrive
![Captura de pantalla 2021-01-17 171547](https://user-images.githubusercontent.com/61259627/104854875-f66d9b00-58e7-11eb-9459-004dc2315cf3.png)

-----------------------

Amazon Drive, Mega

![Captura de pantalla 2021-01-17 172016](https://user-images.githubusercontent.com/61259627/104854932-49dfe900-58e8-11eb-9f8f-67b099c8caec.png)
I didn't find a better icon for amazon drive

-----------------------------
Box drive
![Captura de pantalla 2021-01-17 172254](https://user-images.githubusercontent.com/61259627/104854982-acd18000-58e8-11eb-8b4e-60b9b0a18d34.png)
I also didn't find a better icon for this one.

Alternative:
![Captura de pantalla 2021-01-17 173014](https://user-images.githubusercontent.com/61259627/104855114-b6a7b300-58e9-11eb-978b-1cfe9548153d.png)

**Comment by yaichenbaum** [comment]
@XPoppyX The one with the outline look a little better since they match the other icons used in Files.

**Comment by XPoppyX** [comment]
What about the Box drive icon?

**Comment by yaichenbaum** [comment]
> What about the Box drive icon?

Maybe we should stick to the generic cloud icon for the Box for now. In the future, we might end up switching to colored icons on the sidebar in which case we would probably use the solid icons.

**Comment by XPoppyX** [comment]
I am ready to create a PR

**Comment by yaichenbaum** [comment]
@XPoppyX Sounds good! These should probably be used on the tabs as well.

**Comment by XPoppyX** [comment]
Someone else will have to work on the code to use them, the PR is just for adding the icons, just to clarify.

**Comment by yaichenbaum** [comment]
That's fine, thank you so much for all your contributions!

**Comment by Jaiganeshkumaran** [comment]
Instead of those monochrome icons, we should use the official logo of the service
