### ISSUE TITLE
Enhancement: Improve the default folder icon used in Files

### ISSUE THREAD

**Issue by graffitt** [files-community/Files#3118]
**Is your feature request related to a problem? Please describe.**
pretty terrible looking default folder icon

**Describe the solution you'd like**
change it to modern looking icon, like an application icon

**Describe alternatives you've considered**
I attach an archive with an example of an icon
[icon.zip](https://github.com/files-community/Files/files/5826429/icon.zip)

**Comment by yaichenbaum** [comment]
@graffitt Thank you for opening this issue, can you help us with a little more info such as why you dislike the current icon for folders, and why you think you have a better one?

**Comment by XPoppyX** [comment]
Comparison:

**Before:**
![Captura de pantalla 2021-01-17 140835](https://user-images.githubusercontent.com/61259627/104850695-54da4f80-58cf-11eb-9ce3-436f71f6f2ee.png)

**After (_Concept_):**
It looks better to me because of the color

![Captura de pantalla 2021-01-17 1408352](https://user-images.githubusercontent.com/61259627/104850697-560b7c80-58cf-11eb-83ab-bc5ed54cb844.jpg)

**Comment by Sayor0630** [comment]
This is great! I think they should use this.

**Comment by EvilGamer0406** [comment]
So there should be some kind of gradient in it or just a darker color?
Is the shape of the folder ok?

**Comment by yaichenbaum** [comment]
This concept looks good to me, is anyone interested in implementing this change?

**Comment by tsvietOK** [comment]
@XPoppyX Can you show how it looks with light app theme, please?

**Comment by XPoppyX** [comment]
**Concept:**
![Captura de pantalla 2021-01-18 135022](https://user-images.githubusercontent.com/61259627/104943470-954fd100-5994-11eb-860d-4240db29496a.jpg)

**Comment by Sayor0630** [comment]
yes. you should use it.

**Comment by yaichenbaum** [comment]
@XPoppyX Do you want to replace the SVG files we are currently using for these assets?

**Comment by XPoppyX** [comment]
@yaichenbaum I am testing now. 
It's a bit hard for me not to make it look blurry, but at the moment it looks fine

![Captura de pantalla 2021-03-10 104110](https://user-images.githubusercontent.com/61259627/110638400-4866ca80-818d-11eb-8308-b62a011794d5.png)

**Comment by yaichenbaum** [comment]
@XPoppyX The main thing is that it's an improvement over the current icon.
