### ISSUE TITLE
Cut & paste into a cloud share folder will delete permanently your files

### ISSUE THREAD

**Issue by Yaredito** [files-community/Files#3121]
**Describe the bug**
When cut a folder and paste into another, the folder just disappear, no warnings  nothing

Update
After repeating the process I find out the problem happens only in Cloud shared folders i.e. Google Drive (in my case)

**To Reproduce**
Steps to reproduce the behaviour:
**make a copy of a folder**
1. Cut a folder, by command or prompt menu
2. Go to **cloud shared folder** an paste it by command or prompt menu
3. See no
[debug.txt](https://github.com/files-community/Files/files/5826607/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5826608/debug_fulltrust.txt)

 error, nothing will happened but your files will be gone

**Expected behavior**
Nothing will happened but your files will be gone, no trash nowhere

**Screenshots**

**Desktop (please complete the following information):**
Edizione	Windows 10 Pro
Versione	20H2
Data installazione:	‎14/‎10/‎2020
Build sistema operativo	19042.746
Esperienza	Windows Feature Experience Pack 120.2212.551.0

**Additional context**
It does the thing every time, I lost many files and every time I replicated the cut & paste process it delete the folder

**Log file**

**Comment by yaichenbaum** [comment]
@Yaredito Which version of Files do you have?

**Comment by Yaredito** [comment]
> @Yaredito Which version of Files do you have?

Hi there 

Version 0.23.1.0

**Comment by gave92** [comment]
This bug was corrected in #2830 which was first included in version 1.0.0.0

**Comment by Yaredito** [comment]
Thanks
