### ISSUE TITLE
Duplicated entries for Google Drive under Drives section

### ISSUE THREAD

**Issue by rafifos** [files-community/Files#3125]
**Describe the bug**

The drives section in the sidebar has duplicated entries for Google Drive, it seems that it shows the same folders that you choose to sync inside Backup and Sync's settings. These entries already exists just above the drives section, like Videos and Music.

**To Reproduce**

1. Install [Backup and Sync](https://www.google.com/drive/download/) and Login with your Gmail account
2. Choose a Library from your user to be synced
3. Open Files, there will be duplicated entries for these libraries in the sidebar

**Expected behavior**

Since they're duplicates, the best option in my opinion is to show only the Backup and Sync virtual drive

**Screenshots**

![Captura de tela 2021-01-17 192404](https://user-images.githubusercontent.com/12601769/104857820-de067c00-58f9-11eb-877c-c76c6407df21.png)

**Desktop:**

 - OS Version: Windows 10 Pro **20H2 build 19042.746**
 - App version: **v1.1.0.0**

**Additional context**

--

**Log file**

--

**Comment by rafifos** [comment]
It's failing this check somehow: https://github.com/files-community/Files/blob/f602cfc5940f41dccdcb42806041c9e965ed967e/Files/Filesystem/Cloud/Providers/GoogleDriveCloudProvider.cs#L56

**Comment by gave92** [comment]
Also Google drive client has changed since then.
