### ISSUE TITLE
Problem with copying and pasting

### ISSUE THREAD

**Issue by Obianuju7** [files-community/Files#3128]
I believe that Files is an amazing application. However, it is quite different, in some ways, better than File Explorer. A major problem with the application is that it is so hard to copy and paste between applications. Please fix this issue. Thank you.

**Comment by ellipticview** [comment]
I would expect Ctrl-Drag to copy a file, rather than move the file. Because that is the way the Windows Explorer behaves.

**Comment by yaichenbaum** [comment]
@Obianuju7 Is this still an issue in v1.5?

**Comment by Obianuju7** [comment]
I don't know, I changed back to File Explorer.

**Comment by yaichenbaum** [comment]
@Obianuju7 Thanks for the update, I'll close this issue since we can't reproduce it anymore.
