### ISSUE TITLE
Links on "About" page don't open anything

### ISSUE THREAD

**Issue by geedotk** [files-community/Files#3129]
In Version 1.1.0.0, running on Windows 10, the links on the Settings | About page don't work. This includes the "Submit Feedback", "Release Notes", "Contributors", "Support Us", "Website", and "License". The "Open log location button work ok.

1. Go to 'Settings | About'
2. Click on any of the links (except for "Open log location") and see that they don't open up a browser as expected

 - OS Version: [e.g. Windows 10 Enterprise Version 1809 (OS Build 17763.1637) 
 - Files version: [v1.1.0.0]

Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5827433/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5827434/debug_fulltrust.txt)

**Comment by yaichenbaum** [comment]
@geedotk Is this still an issue in v1.5?

**Comment by geedotk** [comment]
It is fixed in v1.5.

**Comment by yaichenbaum** [comment]
> It is fixed in v1.5.

Thanks for the update!
