### ISSUE TITLE
Change "OK" action in properties dialog to Accent style

### ISSUE THREAD

**Issue by Tropix126** [files-community/Files#3130]
**Is your feature request related to a problem? Please describe.**
Currently in the properties dialog, there are two options: "OK" and "Cancel". These both use reveal style, however I think that it would both look better and improve the user experience by distinguishing these two buttons better.

**Describe the solution you'd like**
Change "OK" button in properties dialog to `AccentButtonStyle` to highlight the primary action of the dialog.

**Describe alternatives you've considered**
None

**Additional context**
![image](https://user-images.githubusercontent.com/42101043/104869476-bfa97c00-590b-11eb-9ea2-abeb94a8b331.png)

**Comment by yaichenbaum** [comment]
@Tropix126 Would you like to make this change?

**Comment by Tropix126** [comment]
> @Tropix126 Would you like to make this change?

I have basically zero experience actually working with XAML or the structure of the files source code. The screenshot is just spliced together in microsoft paint from XAML studio :p

**Comment by XPoppyX** [comment]
Testing
![Captura de pantalla 2021-01-18 133219](https://user-images.githubusercontent.com/61259627/104941330-b4009880-5991-11eb-8066-49e6b76167b6.png)
![Captura de pantalla 2021-01-18 133233](https://user-images.githubusercontent.com/61259627/104941332-b4992f00-5991-11eb-853a-cc6e9503e4d2.png)

**Comment by mdtauk** [comment]
The accent button style is traditionally used for "default actions", so the action that will be performed when you press Enter, because that item has focus.

In modern UI, it is also used to distinguish destructive actions, or actions that will change something.

So its important to not only change the style, but to examine the behaviour of the button too.
