### ISSUE TITLE
Add percentage text to drive allocation indicator in properties

### ISSUE THREAD

**Issue by Tropix126** [files-community/Files#3131]
**Is your feature request related to a problem? Please describe.**
When opening the properties dialog on a drive listed in the sidebar, there is no easy way to view the percentage allocated even though a chart is present.

**Describe the solution you'd like**
Display text in the center of the allocation chart which displays the percentage rounded to the nearest whole number.

**Describe alternatives you've considered**
None

**Additional context**
![image](https://user-images.githubusercontent.com/42101043/104869840-96d5b680-590c-11eb-9d53-d6a980b9a0b2.png)

**Comment by Sayor0630** [comment]
You're right.

**Comment by perplexityjeff** [comment]
This is a great suggestion!

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5939.
