### ISSUE TITLE
Drive allocation chart and allocation key do not reflect system accent color

### ISSUE THREAD

**Issue by Tropix126** [files-community/Files#3132]
**Describe the bug**
When viewing the properties dialog of a drive, the chart showing allocated space do not reflect the system accent color and instead remain a fixed blue.

**To Reproduce**
1. Select any drive from the sidebar.
2. Right click it and open it's properties dialog.

**Expected behavior**
Chart key and fill color should reflect the system accent color.

**Screenshots**
![image](https://user-images.githubusercontent.com/42101043/104871003-8b37bf00-590f-11eb-9f0f-4c71a437f14b.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2
 - App version: 1.0.0.0
 
**Additional context**
None

**Log file**
not relevant

**Comment by mdtauk** [comment]
Might I suggest you put a border around those colour key rectangles, to ensure they are not confused for CheckBoxes

**Comment by tsvietOK** [comment]
There possible color contrast problem, if you select dark gray color in Windows settings.

**Comment by mdtauk** [comment]
> There possible color contrast problem, if you select dark gray color in Windows settings.
> UPD:
> ![image](https://user-images.githubusercontent.com/20501502/104954634-47a58980-59d1-11eb-99f8-907687e781e3.png)

To be fair, it is a silly choice to make, when the Accent Colour is functional as well as an aesthetic one.

You can't expect every app to "correct" a mistake made by the user.

**Comment by yaichenbaum** [comment]
@mdtauk There are lots of things that users don't expect developers to go through the trouble of, but we try to do them anyways since details matter.

**Comment by yaichenbaum** [comment]
@Tropix126 This issue should be resolved with #3161.
