### ISSUE TITLE
Feature request: Add support for extensions in the properties dialog

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#3133]
**Is your feature request related to a problem? Please describe.**
Some users may be looking for additional functionality in the properties dialog, whether it's more information about the file hash, a breakdown of which items are taking up space in a folder or some other integration, there are lots of ways a user might want to extend this feature.

**Describe the solution you'd like**
Support for extensions was recently implemented for the item preview pane, we can add support for extensions to the properties dialog as well.

**Describe alternatives you've considered**
Build these advanced properties into Files itself, reducing the need of any third-party extensions.

**Comment by winston-de** [comment]
I think it would be hard to implement this feature in the same way as the preview pane, as it would be extremely difficult to make an interactive ui using just the Xaml loader since it doesn't support event handlers.
However, there's this project reunion proposal which I think could make this much easier to implement.
Particularly the part about allowing uwp apps to embed controls provided by other uwp apps.

https://github.com/microsoft/ProjectReunion/issues/66

I know I'm pretty late, but I came across this proposal and I thought it was relevant to this.

**Comment by yaichenbaum** [comment]
@winston-de I came across this repo which might make things easier, https://github.com/LokiMidgard/AppPlugin.

**Comment by winston-de** [comment]
@yair100 That repo does make it much easier to use app services, unfortunately it doesn't get around the limitations of the xaml loader, which is the only way (that I know of) to get a native control from an app service: 
- If extensions want to add event handlers, Files must add them in code by referencing objects obtained from within the object tree structure of the Load result, and then send a request to the service when the event handler is fired
- No bindings to code behind
- extensions can only use namespaces already available to Files, and if its through a nuget package the extension developer must make sure they are writing for that version
- much harder to write and debug

Although possible, it would be a lot of work for Files to implement and for extension devs to work with.

I believe embedding a view from an extension would be a much simpler way to go about this, and I believe is similar to [how Windows Explorer currently does this](https://docs.microsoft.com/en-us/windows/win32/shell/how-to-register-and-implement-a-property-sheet-handler-for-a-file-type).

**Comment by yaichenbaum** [comment]
@winston-de Embedding a view would make the most sense, but from my understanding, that isn't available yet.

**Comment by winston-de** [comment]
> @winston-de Embedding a view would make the most sense, but from my understanding, that isn't available yet.

Right, but I thought I should mention it here because the project reunion issue seemed to be looking for scenarios in which such a feature would be useful.
