### ISSUE TITLE
quickly play audio files like MacOS

### ISSUE THREAD

**Issue by meowao** [files-community/Files#3134]
**Is your feature request related to a problem? Please describe.**
I have a large number of sound effect files to manage, and sometimes I need to listen to some files. Is it possible to provide the function of quickly playing audio files?

**Describe the solution you'd like**
Like MacOS, just click on the preview to quickly play sound effects
![M9Z3 HZWB6%D VQ`AEE 13R](https://user-images.githubusercontent.com/13918627/104874248-6f72fe00-598d-11eb-91e2-dbbce0833a3b.png)

**Comment by gave92** [comment]
A preview pane is coming in which you'll be able to preview/play photos, videos, audio 👍

**Comment by meowao** [comment]
> A preview pane is coming in which you'll be able to preview/play photos, videos, audio. Would this cover your use case?

Yes, I have been looking for similar software on windows.
