### ISSUE TITLE
Highlight of selected item is changed to next item when using Alt + Enter to view properties

### ISSUE THREAD

**Issue by quyleanh** [files-community/Files#3135]
**Describe the bug**
Highlight of selected item is changed to next item when using <kbd>Alt + Enter</kbd> to view properties

**To Reproduce**
1. Go to whatever folder
2. Click on whatever file/folder
3. Press <kbd>Alt + Enter</kbd> to view properties
4. The highlight of selected item is changed to next item on folder

**Expected behavior**
The highlight of selected item is kept.

**Screenshots**
There is no screenshot.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Pro. Version 20H2. OS Build 19042.746
 - App version: 1.1.0.0

**Additional context**
No additional context.

**Log file**
No need to provide log file.

**Comment by gave92** [comment]
See #2463
