### ISSUE TITLE
App crash when I copied a large file

### ISSUE THREAD

**Issue by Chucky2401** [files-community/Files#3136]
Hello,

**Describe the bug**
I launched the copy of a video file of 1.35 Gb on an USB key

**To Reproduce**
1. Open two folders with the second panel on the USB key
2. Copy a large file on the USB key by drag and drop
3. Wait
4. Error

**Expected behavior**
A copy of my file without corruption.

**Screenshots**
Sorry, but no screenshot to provide, the app crashed

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Additional context**
I didn't try again to copy the file, but I will.
Also, I didn't have the possibility to see the progress of the copy.

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5828474/debug.txt)

**Comment by KAMiKAZOW** [comment]
Can confirm this. Tried to copy an 8GB file today. Got a crash. v1.2.2

**Comment by yaichenbaum** [comment]
@gave92 can you confirm if this issue is resolved in `main`?

**Comment by gave92** [comment]
Yup and progress works too
