### ISSUE TITLE
[Translation] NLD translations are wrong

### ISSUE THREAD

**Issue by guidorobben** [files-community/Files#3138]
**Describe the bug**
Translations are wrong for NLD

**To Reproduce**
1. start App

**Expected behavior**
Ritten -> Stations
Folders -> Mappen

There is another issue. The Program is in Dutch, but the Library items are in english.

**Screenshots**
![image](https://user-images.githubusercontent.com/11609736/104888843-9c171d80-596d-11eb-9cdc-30357b401b58.png)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find the log file manually by following [this](https://github.com/files-community/Files/wiki/Opening-the-log-file) guide.

**Comment by gave92** [comment]
Yeah, translations are not complete for every language and are community driven (not always updated with the app)
If you're interested you can contribute the translations yourself: https://files-community.github.io/docs/#/articles/translating-files
