### ISSUE TITLE
Crash while closing file properties

### ISSUE THREAD

**Issue by d2dyno1** [files-community/Files#3139]
**Describe the bug**
App crashes when closing folder properties. I've noticed it only crashes when immediately closing properties while counting folder size is in progress

**To Reproduce**
1. Open file properties (tested on: "C:\Program Files")
2. Close immediately after (Click cancel), when counting folder size is in progress
3. Application Crashes everytime

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5829134/debug.txt)

**Comment by m4lebranche** [comment]
This was reported already in #2714

**Comment by d2dyno1** [comment]
Merging with #2714 and closing and closing #3139
