### ISSUE TITLE
copy indicator on 0% when copying to SD card

### ISSUE THREAD

**Issue by Buzzraider** [files-community/Files#3142]
**Describe the bug**
When copying file from hdd to SD card, the file is being copied but there is no visual indication of it happening. When I check the status on "Ongoing task" it's stuck at 0% until the file is actually copied (it was 2,5GB file)

**To Reproduce**
1. Go to any file on HDD (I've chosen 2,5Gb because it takes some time)
2. Click on drag and drop file to SD card 
3. check the ongoing operations on the right side bottom corner
4. the progress bar is stuck at 0% until the file is actually copied then it shows "copy complete"

**Expected behavior**
It should visually show what is the status of the copied file in % and graph.

**Screenshots**

![image](https://user-images.githubusercontent.com/69143224/104902157-a7267980-597e-11eb-9f15-2304e646391f.png)

**Desktop (please complete the following information):**
 - OS Version:  Windows 10 20H2 19042.746
 - App version: v1.1.0.0

**Additional context**
N/A

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find the log file manually by following [this](http
[debug.txt](https://github.com/files-community/Files/files/5829515/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5829516/debug_fulltrust.txt)

s://github.com/files-community/Files/wiki/Opening-the-log-file) guide.

**Comment by gave92** [comment]
Merging with #2543
