### ISSUE TITLE
rendering of typography and icons blurry

### ISSUE THREAD

**Issue by Vanillabacke** [files-community/Files#3143]
At first thanks for the App, was looking for something like this a long time!

The rendering of the typography and some icons are a bit blurry. 
Is it possible, that the icons were scaled or a bit off from the pixelgrid?

![image](https://user-images.githubusercontent.com/56526856/104902272-d341fa80-597e-11eb-8b53-b90e4f869320.png)

**Comment by yaichenbaum** [comment]
@yoshiask Will using your library fix the issue with the icons?

**Comment by yoshiask** [comment]
Depends on which one you use. The original Fluent.Icons package would probably fix it, but it's quite large. Fluent.Icons.Compact is much smaller, but that's because it uses a custom font behind the scenes and is likely to have similar issues.

**Comment by yaichenbaum** [comment]
It sounds like we need to wait for a fix from FluentUI.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #3864.
