### ISSUE TITLE
No Windows Terminal context menu option for root directory

### ISSUE THREAD

**Issue by kostya9** [files-community/Files#3144]
**Describe the bug**
The context menu (right click) does not contain the option to open folder in Windows Terminal when the folder is the root directory of a drive (e.g. C:\)

**To Reproduce**
1. Go to folder C:\
2. Right click
3. See no option to open in Windows Terminal

**Expected behavior**
An option to open the root directory Windows Terminal is present

**Screenshots**
Root folder right click
![image](https://user-images.githubusercontent.com/3115913/104908428-215efa00-598f-11eb-961f-5977a20f70a3.png)

Subfolder right click
![image](https://user-images.githubusercontent.com/3115913/104908492-3b98d800-598f-11eb-81a4-7a9c805d58f9.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Pro 10.0.19042 Build 19042
 - App version: v1.1.0.0

**Comment by gave92** [comment]
Closing this as Files shows the same context menu as Explorer. Explorer does not show that menu item either for root drives.
You can still use the "Open in Terminal.." menu item which you can set to open Windows Terminal in Files settings.
