### ISSUE TITLE
Improve Consistency and Legibility of UI Elements

### ISSUE THREAD

**Issue by Vanillabacke** [files-community/Files#3145]
There a a lot of different button styles.
![image](https://user-images.githubusercontent.com/56526856/104909099-a5ad7f00-5987-11eb-94cf-03f0c3e2cc09.png)

I think you should get rid of the zooming effekt as it is in the current state. Avoid scaling typography. If you are sticking to that effect, I would recommend, that you should only scale the box around and the text is just fixed.

The tilting effect is really subtle and can be removed. If you wanna stick to it, make it dynamic with the pointer position and change the tilt during the movement of it.

![image](https://user-images.githubusercontent.com/56526856/104909856-c924f980-5988-11eb-935d-400fd32005c2.png)
The contrast of the pressed state of the button is a bit too low.

![image](https://user-images.githubusercontent.com/56526856/104910147-3042ae00-5989-11eb-9e29-60f54a661cd1.png)
I would prefer a hard pixel border instead  of that blurry blue border for the focus

![image](https://user-images.githubusercontent.com/56526856/104910448-9e877080-5989-11eb-89d5-1b6b60ef61b6.png)
The three icons looking like from three different icon sets. The first and the second looks mainly different because of the render sharpness.

![image](https://user-images.githubusercontent.com/56526856/104910808-2b322e80-598a-11eb-86dc-64c3d640baf8.png)
Looks like, you are using a group label as an operation label.
Labels like "move overflow items into a sub menu" should have a smaller font size. Have a look to the windows settings, how it is used:
![image](https://user-images.githubusercontent.com/56526856/104911056-8f54f280-598a-11eb-96da-eb87334a0201.png)

Is there any design file for the whole ui and iconset?

Cheers!

**Comment by XPoppyX** [comment]
Before:
![](https://user-images.githubusercontent.com/56526856/104910147-3042ae00-5989-11eb-9e29-60f54a661cd1.png)

After:
![Captura de pantalla 2021-01-18 094707](https://user-images.githubusercontent.com/61259627/104918690-e1d6e480-5973-11eb-98f3-8d51af855156.png)

--------------------------------------------
Before:
![Captura de pantalla 2021-01-18 105248](https://user-images.githubusercontent.com/61259627/104923820-5d885f80-597b-11eb-85e9-736393922209.png)

After:
![Captura de pantalla 2021-01-18 104946](https://user-images.githubusercontent.com/61259627/104923829-611be680-597b-11eb-943a-d7dc722c8f4c.png)

-----------------------------------------------

**Before:**

![Captura de pantalla 2021-01-18 110000](https://user-images.githubusercontent.com/61259627/104924777-adb3f180-597c-11eb-9473-7bc5e14732e5.png)
-----

**After:**

![Captura de pantalla 2021-01-18 110018](https://user-images.githubusercontent.com/61259627/104924789-b1477880-597c-11eb-9549-9faa42ddd1d1.png)

**Comment by Vanillabacke** [comment]
looks a way better!
It looks like, you are using the FluentUI of Microsoft. Maybe you should have a look into these files ( [https://www.microsoft.com/design/fluent/](https://www.microsoft.com/design/fluent/) ). There is an example for the textfield:
![image](https://user-images.githubusercontent.com/56526856/104930270-39417880-59a5-11eb-9a9d-9533f86a6dff.png)

**Comment by yaichenbaum** [comment]
> The tilting effect is really subtle and can be removed. If you wanna stick to it, make it dynamic with the pointer position and change the tilt during the movement of it.

The tilt effect is being from WinUI in the near future as part of an overall UI refresh, I suggest we wait for some of these changes before making any decisions here.

**Comment by Tropix126** [comment]
As mentioned earlier, some of these should probably be issues for the microsoft-ui-xaml repo instead of here. For example, the textfield is simply part of fluent as is. The button issue is a side-effect of using "reveal style" buttons, which is one of 3 button styles. The style you saw in settings was the standard style as opposed to the reveal style. I'm personally in favor of switching to standard style in the future though, but that's a personal preference.

> looks a way better!
> It looks like, you are using the FluentUI of Microsoft. Maybe you should have a look into these files ( https://www.microsoft.com/design/fluent/ ). There is an example for the textfield:
> ![image](https://user-images.githubusercontent.com/56526856/104930270-39417880-59a5-11eb-9a9d-9533f86a6dff.png)

FluentUI might as well be a completely different design language than XAML fluent, as basically every control is off spec in some way. That and it's a web framework and not possible without custom styling.

I (personally) don't think straying from the xaml controls is a good idea, as it only brings more inconsistency into the app.

**Comment by Tropix126** [comment]
I might also add that the guys at the xaml repo have been doing some major changes to stuff like this, and most components will look different in the future. Example:

**Comment by XPoppyX** [comment]
For now we can discuss about this:

### **Before:**

![Captura de pantalla 2021-01-18 110000](https://user-images.githubusercontent.com/61259627/104945263-3475c800-5997-11eb-804b-0087785487ef.png)

--------------------

### **After:**

![Captura de pantalla 2021-01-18 111251](https://user-images.githubusercontent.com/61259627/104945272-36d82200-5997-11eb-92c3-c5105923fe96.png)

**Comment by yaichenbaum** [comment]
@XPoppyX What font size are you using for the toggle switch headers?

**Comment by XPoppyX** [comment]
14

**Comment by Tropix126** [comment]
> For now we can discuss about this:
> 
> ### **Before:**
> ![Captura de pantalla 2021-01-18 110000](https://user-images.githubusercontent.com/61259627/104945263-3475c800-5997-11eb-804b-0087785487ef.png)
> 
> ### **After:**
> ![Captura de pantalla 2021-01-18 111251](https://user-images.githubusercontent.com/61259627/104945272-36d82200-5997-11eb-92c3-c5105923fe96.png)

Agreed here, though what's with those 2px border toggleswitches in the first screenshot?

**Comment by XPoppyX** [comment]
@Tropix126 Because I took that screenshot from Blend and it looks thicker there. I will change it

**Comment by mdtauk** [comment]
The actual settings app on Windows 10 is still using the old control designs, they didn't move to WinUI 2

**Comment by mdtauk** [comment]
> There a a lot of different button styles.
> ![image](https://user-images.githubusercontent.com/56526856/104909099-a5ad7f00-5987-11eb-94cf-03f0c3e2cc09.png)
> 
Not everything you click in a UI is or should be a button.  Some things are Icons, Tiles, List Items, and yes Buttons.

Having defined styles for each of the discreet UI concepts is important, and these can be visually distinctive from each other, but should be used consistently and within the correct context.

> The tilting effect is really subtle and can be removed. If you wanna stick to it, make it dynamic with the pointer position and change the tilt during the movement of it.
>
The Tilt effect is being removed from the WinUI design language, so I would imagine it would go from Files too.  Especially with double click to open items, the tilt effect is deceptive making you feel like an action will be performed on a single click.

**Comment by Vanillabacke** [comment]
> Not everything you click in a UI is or should be a button. Some things are Icons, Tiles, List Items, and yes Buttons.
> 
> Having defined styles for each of the discreet UI concepts is important, and these can be visually distinctive from each other, but should be used consistently and within the correct context.
> 
Yes, the word "button" was a bit of missleading. Mainly I wanted to say, that there are to many different styles in the UI.

**Comment by Vanillabacke** [comment]
@yair100 are there any layout or wireframes files for this project?

**Comment by yaichenbaum** [comment]
@Vanillabacke There are not, is this something the community would like to help with?

**Comment by Shomnipotence** [comment]
> @Vanillabacke没有，社区需要帮助吗？

I think your team does not need to make too many improvements, just follow the updates of WinUI3 and XAML Control. XAML control styles are constantly changing. I really don’t understand why Microsoft is so obsessed with this, instead of focusing on updating the old interface in the system to Fluent Design as soon as possible.

**Comment by Vanillabacke** [comment]
well, it seems like you are sticking to the style of that components and not really open to improvements. so there is no need for layouts or wireframes to proof / improve the concept.

is  there any date for the update release of WinUI3 / XAML control?

**Comment by Shomnipotence** [comment]
> well, it seems like you are sticking to the style of that components and not really open to improvements. so there is no need for layouts or wireframes to proof / improve the concept.
> 
> is there any date for the update release of WinUI3 / XAML control?

https://github.com/microsoft/microsoft-ui-xaml/issues?q=refresh

**Comment by Vanillabacke** [comment]
@Shomnipotence thx

**Comment by yaichenbaum** [comment]
Thank you for all your feedback in this thread. A lot of the issues you brought up, are being resolved in the WinUI library, please open a new issue if you notice a specific UI issue that you feel should be addressed.
