### ISSUE TITLE
Auto fit columns by double clicking

### ISSUE THREAD

**Issue by eraychumak** [files-community/Files#3146]
**Is your feature request related to a problem? Please describe.**
User Experience

**Describe the solution you'd like**
Being able to double click on the right edge of a column header to make it auto-fit to the widest content.

**Describe alternatives you've considered**
I guess another way would be to add an "Auto fit columns" button into the "More options" menu that would apply it to all columns and/or have it as a checkbox "Automatically auto fit columns to content width" in settings (`Preferences` or `Files and Folders`).

**Additional context**
N/A

**Comment by yaichenbaum** [comment]
This issue should be resolved in v2.
