### ISSUE TITLE
Tab highlighted on start

### ISSUE THREAD

**Issue by eraychumak** [files-community/Files#3147]
**Describe the bug**
On start up, the tab is highlighted as if tab (btn) was used to go to it.

**To Reproduce**
1. Open the app

**Expected behavior**
It should just be highlighted normally unless used tab (btn) to go to it.

**Screenshots**
![image](https://user-images.githubusercontent.com/44278658/104912628-67fb2700-5984-11eb-9987-a53d60ebdcf2.png)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Additional context**
N/A

**Log file**
N/A

**Comment by yaichenbaum** [comment]
@eraychumak Did you open Files using the `win` + `e` shortcut?

**Comment by eraychumak** [comment]
> @eraychumak Did you open Files using the `win` + `e` shortcut? In that case, this is the expected behavior for keyboard navigation.

Na I opened it through start menu and then pressed the enter key.

**Comment by yaichenbaum** [comment]
@eraychumak Thank you for the extra info, in that case, it's the expected behavior since you launched Files using the keyboard.
