### ISSUE TITLE
OneDrive Link but OneDrive Uninstalled.

### ISSUE THREAD

**Issue by sk8erjdy** [files-community/Files#3149]
**Describe the bug**
I have completely uninstalled OneDrive from my system, yet the Files app still is showing it as an option. Clicking said link results in the program saying the location does not exist. I have the Files app installed on the system prior and it was not showing so I'm not sure why it is now showing this broken link.

**To Reproduce**
1. Uninstall OneDrive from the PC
2. Remove any Folders left behind in User App Data folder
3. Install and open Files App
4. Observe that the OneDrive Link is present
5. Press the OneDrive Link and observe that the app can not find this link.

**Expected behavior**
I would expect that since this folder is not valid that the App would not display it.

**Screenshots**
![image](https://user-images.githubusercontent.com/77621828/104917580-d3c39c80-5950-11eb-8baa-18af32ac731d.png)
![image](https://user-images.githubusercontent.com/77621828/104917668-f35ac500-5950-11eb-824b-1c153419d931.png)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 Home 2004 19041.746]
 - App version: [v1.1.0.0]

**Additional context**

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5830270/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5830271/debug_fulltrust.txt)

**Comment by sk8erjdy** [comment]
Fixed by going to env labels

**Comment by AndyMDoyle** [comment]
@sk8erjdy, PR #3177 will resolve this issue by changing how OneDrive accounts are found.
This will prevent the issue you ran in to, and mean a user doesn't need to manually remove the OneDrive environmental variables.

**Comment by sk8erjdy** [comment]
@AndyMDoyle Sounds good! New to github so I didn't properly search correctly to find the other post that was answered a while ago with that solution. It's gone now and love the progress! Can't fully commit yet, but once I get used to it I hope to make Files the primary tool for me :)
