### ISSUE TITLE
Can You Please Add a Bookmarks Bar?

### ISSUE THREAD

**Issue by Peregrine-Falcon11** [files-community/Files#3150]
**Is your feature request related to a problem? Please describe.**
There isn't enough space for shortcuts in the sidebar.

**Describe the solution you'd like**
Can you please add a bookmarks bar to the top? Thanks!

**Describe alternatives you've considered**
An app called clover.

**Additional context**
Version 1.1.0.0

**Comment by yaichenbaum** [comment]
While we don't plan to add a bookmarks bar to Files, the next version of Files will have the option to collapse sections in the sidebar, this should provide more room to store your favorite items.
