### ISSUE TITLE
[OneDrive] OneDrive Commercial do not show additional synced locations

### ISSUE THREAD

**Issue by heikobischoff** [files-community/Files#3151]
After OneDrive connected with your business account, you can manage files in your personal OneDrive folder. This is implemented right now. 
While working with Teams and SharePoint Online, you can sync additional locations with your OneDrive client. They will appear in Windows Explorer. This feature is currently missing in Files, would be great when this could be implemented.

![tempsnip](https://user-images.githubusercontent.com/34372415/104919501-a568b000-5996-11eb-82ed-cda790933ac9.png)

**Comment by TimotheFCN** [comment]
You can manually go to the location where the folder is synced with on your local disk and pin the folder in Files. Files sync status is still showed like with Onedrive tabs

**Comment by gave92** [comment]
See #3005

**Comment by gave92** [comment]
@heikobischoff apologies, I misinterpreted your request. It should still make sense to merge the two together as the implementation should take care of both at once.

**Comment by gave92** [comment]
#1310 is the correct duplicate
