### ISSUE TITLE
Xaml 2.5 needed, but no auto-downloaded or help getting it.

### ISSUE THREAD

**Issue by rwperrott** [files-community/Files#3152]
**Describe the bug**
Xaml 2.5 missing, but no auto-download or other help provided to get it.

**To Reproduce**
Attempt install using Powershell.

**Expected behavior**
I expect missing dependencies to be auto-downloaded or at least a **non-store** link provided; non-store because I want nothing to do with microsoft store, not even for _free_ stuff.  I only want to _side-load_ software.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Pro 20H2 19042.685
 - App version: V1.1

**Comment by yaichenbaum** [comment]
@rwperrott You can download an alternative installer over [here](https://files-community.github.io/package.github.io/Files.Package/Files.Package.appinstaller).
