### ISSUE TITLE
Folder starting with a dot like .test on network drive cannot be opened

### ISSUE THREAD

**Issue by TimotheFCN** [files-community/Files#3153]
**Describe the bug**
If a folder located on a network drive starts with a dot, it doesn't appear even if "show hidden files" is enabled.
When enterring the direct URL, the message "ERROR_UNAUTHORIZED" appears.
The folder is accessible in windows explorer.
The same folder but on a local disk is shown in the list and can be opened.

**To Reproduce**
1. Connect a network drive
2. Add a folder with a dot at the beginning (like .test) with windows explorer
3. Add some content in this folder
4. Try to access the folder from Files-Community

**Expected behavior**
The folder should appear and open like it would on a local disk.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.630
 - App version: [v1.1]

**Log file**
No error reported

**Comment by TimotheFCN** [comment]
On OneDrive, the folder beahvior seems to be normal.

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.11.0 or above?

**Comment by h1g0** [comment]
The exact same problem occurs in my environment.

OS: Windows 11 21H2 (10.0.22000.856)
App: 2.3.11.0
