### ISSUE TITLE
Hide OneDrive (or other drives) from the list

### ISSUE THREAD

**Issue by gumbarros** [files-community/Files#3155]
**Is your feature request related to a problem? Please describe.**
I want to remove the OneDrive from the drives list

**Describe the solution you'd like**
A option on right-click to hide a driver

**Describe alternatives you've considered**
Hide all drives, but I need the others.

**Comment by yaichenbaum** [comment]
@gumbarros Thank you for opening this issue, you should be able to remove OneDrive from the list by removing the environment variables for OneDrive.

**Comment by gumbarros** [comment]
It worked guys, thanks!
