### ISSUE TITLE
Fuzzy text after hoovering over button

### ISSUE THREAD

**Issue by itmk64** [files-community/Files#3158]
When I hoover over button the clear and nice font always went to be little bit fuzzy (see screenshot).
Same behavior for each button in the "Folders" menu and "Units" menu.
Same behavior always (doesn't matter if you restart app, Windows or not)

**resolution:** 1920x1080px

**OS version:** Windows 10 Home 19042.746
**App version:** 1.1.0.0

**Expected behavior:** Clear sharp font on the hoovered button

![image](https://user-images.githubusercontent.com/77584270/104953541-e24c9b00-59c6-11eb-99f6-11fc6416ee37.png)

![image](https://user-images.githubusercontent.com/77584270/104954078-e927dd80-59c7-11eb-86ec-dc61084c7446.png)

**Comment by gave92** [comment]
See #3143
