### ISSUE TITLE
Fresh installed app crashed 

### ISSUE THREAD

**Issue by anatoly-kryzhanovsky** [files-community/Files#3167]
**Describe the bug**
After launching fresh installed app and navigate to drive application was crashed

**To Reproduce**
1. install app from Windows Store
2. Click on any folder on left panel or on any disk in main panel
3. Application hangs for 1-2s and crash after that

**Expected behavior**
Application open desired component

**Desktop (please complete the following information):**
 - OS Version: Windows 10 10.0.19042 buikd 19042
 - App version: v1.10.0

**Additional context**
none

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5833990/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5833994/debug_fulltrust.txt)

**Comment by yaichenbaum** [comment]
@anatoly-kryzhanovsky Can you check if Files has access to the file system under Privacy Settings in Windows 10?

**Comment by anatoly-kryzhanovsky** [comment]
yes, i checked and see that apps have access to file system.
also i try to run Files as administrator - with no luck

for additional information about environment:
i also installed Files son my home pc and only one different - on my work pc i have some network mounted drive and drive mounted with subst

**Comment by tsvietOK** [comment]
@yair100 looks like it is the same bug as reported on our Discord server #general chat.

**Comment by yaichenbaum** [comment]
@anatoly-kryzhanovsky Is this still an issue in v1.3?

**Comment by anatoly-kryzhanovsky** [comment]
sorry for delay. no, after update application works stable without crash
