### ISSUE TITLE
Корявые значки файлов

### ISSUE THREAD

**Issue by AleksHitch** [files-community/Files#3168]
Доброго.
При выборе вида таблицей, иконки файлов очень размытые
![image](https://user-images.githubusercontent.com/77663477/105004985-bcb2a680-5a45-11eb-9344-6b11983a8ac4.png)
![image](https://user-images.githubusercontent.com/77663477/105005044-d7851b00-5a45-11eb-9577-ca13651f08c6.png)
Если переключить в другой вид, то разрешение в норме
![image](https://user-images.githubusercontent.com/77663477/105005113-ec61ae80-5a45-11eb-9601-ba0d13a8c3f6.png)
Прошу поправить по мере возможности
Заранее благодарю, у вас очень крутой проект!

**Comment by tsvietOK** [comment]
Спасибо за отзыв! Мы уже знаем об этой проблеме и исправим её по мере возможности. Что-то бы не дублировать информацию, я закрываю этот issue в пользу [ранее созданного](https://github.com/files-community/Files/issues/1152).
