### ISSUE TITLE
Crashes Upon Load

### ISSUE THREAD

**Issue by SteveP757** [files-community/Files#3169]
[debug.txt](https://github.com/files-community/Files/files/5836456/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5836457/debug_fulltrust.txt)

**Comment by gave92** [comment]
@jakoss clues?

**Comment by jakoss** [comment]
The only thing that comes to mind is some string modification on compile/linker? Maybe some strange string encoding? It's super weird that first character is wrong..

**Comment by jakoss** [comment]
@gave92 Do you think it's reasonable to wrap first db connection with try/catch and just disable SQLite caching on exception? Memory Cache will still work like before

**Comment by Curcul** [comment]
Has anything came up on how to fix this issue?

**Comment by jakoss** [comment]
My PR with a fix is waiting for review

**Comment by yaichenbaum** [comment]
@SteveP757 This should be resolved with #2944.
