### ISSUE TITLE
Default view

### ISSUE THREAD

**Issue by HttpJacobo** [files-community/Files#3170]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by yaichenbaum** [comment]
@HttpJacobo Thank you for opening this issue, we usually expect users to fill out the issue template when reporting a bug or submitting a feature request, please reopen this issue when you have filled out the issue template.
