### ISSUE TITLE
When accessing %appdata% over WIN+R an error occurs

### ISSUE THREAD

**Issue by MMMMartyyyy** [files-community/Files#3172]
**Describe the bug**
When Files is being set to default and you try to access %appdata% over the Run menu Windows shows an error saying it cannot access it.

**To Reproduce**
1. Set Files to default in Registry
2. Open Run menu (WIN+R)
3. Type %appdata%
4. Press enter
5. See error

**Expected behavior**
It should open the AppData folder

**Screenshots**
![image](https://user-images.githubusercontent.com/70663072/105054044-d9fd6a00-5a71-11eb-9e56-b5b85d2215c7.png)
It is in german. Sorry about that

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.746
 - App version: 1.1.0.0

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5836772/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5836773/debug_fulltrust.txt)

**Comment by Starstrike** [comment]
Yeah I also noticed this issue. Here's a screenshot in English.

![image](https://user-images.githubusercontent.com/1996734/112630043-7560e180-8e0b-11eb-9e61-f078bf40fa5b.png)

**Comment by winston-de** [comment]
Looking at the stack trace, it would *seem* that the system is getting an access denied error when trying to access and launch the Files executable. It would also appear that this is a bug with the app execution alias APIs. I'm still unsure what about the appdata folders is different that this error would only occur when launching them. 

Here's the stack trace for the error if anyone else is interested:
```
(704.2be8): Windows Runtime Originate Error - code 40080201 (first chance)
onecore\base\appmodel\appexecutionalias\lib\appexecutionaliasapis.cpp(237)\apisethost.appexecutionalias.dll!00007FF8CCE12638: (caller: 00007FF8CCE12073) ReturnHr(1) tid(2be8) 80070005 Access is denied.
 info: Skipping license manager: PFN 49306atecsolution.FilesUWP_1.5.25.0_x64__et10x9a9vyk8t (InvokeLicenseManagerRequired)
```

Some other notes:
- This occurs when invoking the app data path directly in run (eg. ```C:\Users\<username>\AppData\Roaming```)
- This occurs with ```AppData/Local```, ```AppData/LocalLow```, as well as ```AppData/Roaming```
- This does not occur when accessing child directories of either of those three folders (eg ```%userprofile%\AppData\Local\Discord```)
- Running %userprofile%\AppData works just fine

**Comment by yaichenbaum** [comment]
@Starstrike try putting Files before the variable.

**Comment by Ryderjj89** [comment]
@yair100 Yes this appears to work correctly. Is this going to be changed in the future so that it's not necessary to put files before each of these?
