### ISSUE TITLE
Files list not refreshed after pasting file(s) into phone drive

### ISSUE THREAD

**Issue by osieltorres** [files-community/Files#3174]
**Describe the bug**
The file list is not refreshed automatically after pasting any files into folder of phone drive.

**To Reproduce**
1. Go to Files application
2. Connect your phone
3. Go to the phone drive, copy some files/folders inside the phones drive.
4. After finishing pasting the files/folders, the list of them is not refreshed to add new pasted files/folders.

**Expected behavior**
The files list to be automatically refreshed after pasted new ones.

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2 19042.746]
 - App version: [v1.1.4.0]

**Comment by gave92** [comment]
Merging with #2042 as the cause is the same
