### ISSUE TITLE
Recycle bin is not translated the very first time after app install

### ISSUE THREAD

**Issue by cristiansgm** [files-community/Files#3175]
**Describe the bug**
In the sidebar of the explorer the trash does not appear translated into Spanish at the first start.

**To Reproduce**
1. Go to 'Files'
2. Look in 'Sidebar'

**Expected behavior**
That it was translated into the language of my system at the first start.

**Screenshots**
https://i.imgur.com/ajWontA.png

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 1809 17763.1697 & Windows 10 20H2 19042.746]
 - App version: [v1.1.0.0]

**Comment by XPoppyX** [comment]
Al reiniciar ya debería de mostrarse en español. Es algo que suele pasar al instalar por primera vez o reinstalando.

**Comment by cristiansgm** [comment]
> Al reiniciar la app ya debería de mostrarse en español. Es algo que suele pasar al instalar por primera vez o reinstalando.

Tienes razón, lo dejo por si consiguen solucionar lo del primer inicio.

Muchas gracias!

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.11.0 or above?
