### ISSUE TITLE
Files ignores the Windows theme

### ISSUE THREAD

**Issue by 10011** [files-community/Files#3176]
**Describe the bug**
When setting the App theme under settings you have three options: Windows default, light and dark. Dark and light works as expected but Windows default ignores the Windows theme you have.

**To Reproduce**
Open files
Click on Settings
Choose Windows default as your app theme
See it ignore your theme (if using another one than Windows standard light/dark)

**Expected behavior**
I expected and would like it to match the theme I'm using for Windows.

**Screenshots**

![Screenshot](https://i.imgur.com/Xf4W4MK.jpg)

Files to the left, standard Explorer to the right. Files ignores the theme, Explorer respects it.

**Desktop (please complete the following information):**
 - Win 10 Home 19041.746
 - Files 1.1.0.0

**Additional context**
Nah, I just feel like the dev didn't consider themes.

**Suggestion**
Have Files read the relevant color values and stuff from the current theme Windows is using instead of hard-coding them into three options.

**Comment by yaichenbaum** [comment]
@10011 Did you set Windows to use dark mode? By thy way, what's the other app in the screenshot?

**Comment by 10011** [comment]
> 
> 
> @10011 Did you set Windows to use dark mode? By thy way, what's the other app in the screenshot?

Yeah it works better as a base for the theme I'm using. And Files to use the Windows theme.

There are two programs in the screenshot - Files to the left and the standard Windows File Explorer to the right, highlighting what I expected to see in Files when it comes to colors etc.

**Comment by duke7553** [comment]
@10011 Sorry. We don't have plans to support custom themes from Explorer. 

Closing this now.
