### ISSUE TITLE
Pin Directories 

### ISSUE THREAD

**Issue by RocketNinja15** [files-community/Files#3178]
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
On your "Folders" Page or Below, the ability to "pin" a directory or file, so when you click on it... It will either open, or go to that directory.
**Describe alternatives you've considered**
Rightclick directory, then click "pin" or "uppin"
**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

![image](https://user-images.githubusercontent.com/50027436/105099032-d9f46e80-5a5f-11eb-9fe9-3be016f52ae0.png)

**Comment by gave92** [comment]
Did you have in mind something like this? -> #2881 If yes, we're implementing it :)

**Comment by RocketNinja15** [comment]
> Did you have something like this in mind? -> #2881 If yes, we're implementing it :)

Pretty Much.... I guess the ability to pin a directory like how "drives" or folders are

**Comment by yaichenbaum** [comment]
Merging with #2881.
