### ISSUE TITLE
.EXE or .MSI

### ISSUE THREAD

**Issue by thevitormanuel** [files-community/Files#3179]
I need a **.EXE** or **.MSI** installer, Where I can find? Thanks.

**Comment by gave92** [comment]
Thre's no exe/msi for UWP apps. Here you can find the equivalent -> https://github.com/files-community/Files/releases/download/v1.1/Files-1.1.Msixbundle

**Comment by thevitormanuel** [comment]
And a portable version?

**Comment by gave92** [comment]
No portable versions are possible for uwp apps either :(
