### ISSUE TITLE
Preview

### ISSUE THREAD

**Issue by BRabbitG** [files-community/Files#3181]
Hi,
Files could be greater with files preview. In the conventional explorer I have listed my files in a folder and in the right I have the preview. With this I can read a pdf file without opened it, also see imaged, excel, word files, etc...

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by adriansalvatori** [comment]
This behavior is easily achieved by adding "QuickLook", as the official website explicitly communicates. 

https://www.microsoft.com/en-us/p/quicklook/9nv4bs3l1h4s?SilentAuth=1

**Comment by gave92** [comment]
Preview pane is coming! -> #2756
