### ISSUE TITLE
Double click in blank space should take the user one level up. 

### ISSUE THREAD

**Issue by adriansalvatori** [files-community/Files#3183]
**Is your feature request related to a problem? Please describe.**
Not a problem, actually. It's only that I come from solutions like Clover and ExplorerMax. In these tools, the user can go Up one level when double-clicks in the blank space. Not really a big deal, but I kinda miss it using Files. Thought it would be a nice touch to add that function. 

**Describe the solution you'd like**
As easy as that. When the user double clicks any blank space in the file viewer, he should be taken up one level in folder structure.

**Comment by gave92** [comment]
Merging with #2355
