### ISSUE TITLE
Extend the left sidebar to the title bar (tab page bar) area, and limit the tab page bar to the right area of ​​the window (as shown in the figure)

### ISSUE THREAD

**Issue by Shomnipotence** [files-community/Files#3184]
**Is your feature request related to a problem? Please describe.**
Please build a more holistic interactive interface. In this interface, there are two levels of navigation, one is the left sidebar navigation, and the other is the tab navigation. How to deal with the relationship between the two is a very troublesome thing.

Theoretically speaking, the tab page should be the first-level navigation, and the sidebar is the second-level, indicating the folder where the tab page is located. Therefore, the tab bar runs through the top of the entire window, which makes logical sense.

![image](https://user-images.githubusercontent.com/6630660/105139410-3d020600-5b31-11eb-8681-5ef6100a0c75.png)
OS X 10.0+-macOS 10.14, Finder Screenshot

**Describe the solution you'd like**
But this is not the case. With the continuous development of the times, the design has been evolving.

First of all, Windows 10 uses the left and right structure to organize the interface for the first time. The left side is a sidebar with acrylic effect, and the right side is a black background.

![image](https://user-images.githubusercontent.com/6630660/105139512-5efb8880-5b31-11eb-8a92-e7437b305dad.png)
Windows 10 Setting

Next, macOS 11 Big Sur also adopted a similar structure

![image](https://user-images.githubusercontent.com/6630660/105139628-789cd000-5b31-11eb-9848-f509cd23d268.png)
macOS 11 Finder

So how to deal with the tab bar?

The answer given by macOS is
![image](https://user-images.githubusercontent.com/6630660/105139733-9bc77f80-5b31-11eb-9a12-e7894b8c02c6.png)
![image](https://user-images.githubusercontent.com/6630660/105139680-83576500-5b31-11eb-8a99-4a7351265429.png)

I think this solution is excellent, it brings a more overall and more beautiful design, it maintains the left and right structure of "transparent on the left and opaque on the right".

I think Files should also adopt this structure, or at least as an option.

![未标题-222](https://user-images.githubusercontent.com/6630660/105139801-bdc10200-5b31-11eb-997a-f7703b437c58.png)
Files conceptual design

**Describe alternatives you've considered**
There is no other solution, Files is the only file explorer with Fluent Design available on Windows

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by gave92** [comment]
@Shomnipotence thanks for the suggestion. Files used to be like you describe till not so long ago.
￼

**Comment by Shomnipotence** [comment]
> @Shomnipotence thanks for the suggestion. Files used to be like you describe till not so long ago.
> I'll let someone else explain why it was changed as I was never quite sure xD
I remember this change at least a year ago. I guess its logic is probably that the tab bar is the first-level navigation bar, and the sidebar is the second-level, which is logically correct, but there is no need to do so.

![image](https://user-images.githubusercontent.com/6630660/105141585-56588180-5b34-11eb-99e5-f7b448cc92e7.png)

As shown in the picture, the entire interface is divided into three parts, plus the floating tab buttons, the entire interface appears to be fragmented and broken.

**Comment by yaichenbaum** [comment]
@Shomnipotence As Gave92 mentioned, this was how it used to work. We changed the design because users were getting confused with the different navigation layers, however, it could be that this won't be an issue anymore since we have the new detached tab design.

**Comment by yaichenbaum** [comment]
We are open to making this change, but we would some feedback from the community before committing to it.

**Comment by generalguy41** [comment]
I for one love the idea of a fully extended sidebar like the concept shown. I think it looks much cleaner and less disjointed than the current implementation. I was a big fan of the original design before the change to the current implementation, though I understand the reasoning behind the change.

**Comment by XPoppyX** [comment]
+1

**Comment by mdtauk** [comment]
I wonder if its the visual distinction between top acrylic and the side acrylic.  You know I have been suggesting using a single Acrylic for both regions, with the content area rounded and shadowed. @yair100 

Rather than just the Tabs being indented away from the edge

**Comment by tsvietOK** [comment]
I'll just post my previous app design concept for further discussion.
![image](https://user-images.githubusercontent.com/20501502/105217093-1ad1ad80-5b5c-11eb-946e-0d95ada4f502.png)

**Comment by mdtauk** [comment]
Posting my concept also, with one Acrylic surface for tabs and sidebar.
![image](https://user-images.githubusercontent.com/7389110/105219104-f66ed480-5b4d-11eb-98fc-dd4d019f98a7.png)

**Comment by generalguy41** [comment]
Bringing it back to one of the earlier threads about this, I think there were a number of good discussions in #520. I already pointed out a number of potential ideas in [this comment](https://github.com/files-community/Files/issues/520#issuecomment-610745600). (Perhaps this thread should be merged with #692 like that one was?)

Also, I'm personally still a fan of this file explorer concept that's been floating around for a while, though that might be dragging up too much of an old argument about "user confusion".
![image](https://user-images.githubusercontent.com/8879244/105226555-20b09a00-5b2e-11eb-891e-760057040e0e.png)

**Comment by Shomnipotence** [comment]
> 我将发布我以前的应用程序设计概念以供进一步讨论。
> ![图片](https://user-images.githubusercontent.com/20501502/105217093-1ad1ad80-5b5c-11eb-946e-0d95ada4f502.png)

I prefer this one，but the currently selected tab may need more obvious marking

**Comment by R3voA3** [comment]
https://user-images.githubusercontent.com/8879244/105226555-20b09a00-5b2e-11eb-891e-760057040e0e.png
This looks much cleaner.
