### ISSUE TITLE
Add a checkbox to select all files from a list

### ISSUE THREAD

**Issue by osieltorres** [files-community/Files#3187]
**Is your feature request related to a problem? Please describe.**
It would be nice from an accesibility perspective, if the list of displayed could have a checkbox(previous to the *Name* field) for selecting all files, as not every user knows about the `Ctrl+A` shortcut.

**Describe the solution you'd like**
Adding a checkbox for selecting all files would add some accesibility plus for other not so advanced users.

**Describe alternatives you've considered**
I have no other alternatives as it would be the simplest way.

![image](https://user-images.githubusercontent.com/3835402/105188677-27291c80-5b02-11eb-9a6d-4ee7da4cd466.png)

**Comment by gave92** [comment]
In the lower right corner you have the option to select all files, but not very discoverable.
Merging this with #290

**Comment by osieltorres** [comment]
@gave92 I am aware of what you say, but like you also said, is not very discoverable, either eyes friendly, and that's why I created this request. Current way is not first look accessible.

**Comment by gave92** [comment]
@osieltorres There's #290 that is about adding check boxes for multiselection. This would also add a select-all checkbox in the top left of the list as you suggest.
But perhaps your suggestion can be implemented on its own, reopening.

**Comment by yaichenbaum** [comment]
@gave92 This is technically already implemented with the option on the status bar, regarding the check box, I think that should go together with #290.
