### ISSUE TITLE
Sort content by creation date.

### ISSUE THREAD

**Issue by Kuroncho** [files-community/Files#3189]
****Is your feature request related to a problem? Please describe.**
User Experience

**Describe the solution you'd like**
Sort the columns by Creation Date. Add to the list the option to sort by Creation Date and that the option can be added from the right button on the column titles.

**Describe alternatives you've considered**
Alternatively, add the option from Sort By to the right button over any area where it is clicked.

**Additional context**
N/A

**Comment by gave92** [comment]
Being implemented in #3123

**Comment by yaichenbaum** [comment]
This feature was implemented with #3123.
