### ISSUE TITLE
Not showing complete list of drive 

### ISSUE THREAD

**Issue by gmusa** [files-community/Files#3190]
**Describe the bug**
Not showing complete list of drives or option to chose witch drives to show

**Expected behavior**
Be able to access information on any of my drives

 

**Desktop :**
 - OS Version: Windows 10 2004 Os Build 20277.1
 - App version: [v1.1.0.0]
 
 **Screenshots**
 
 ![image](https://user-images.githubusercontent.com/742233/105208777-d88e7900-5b27-11eb-962f-93cf8f8ad1ee.png)

_VS_
 
![image](https://user-images.githubusercontent.com/742233/105209056-273c1300-5b28-11eb-8c5f-a730dc18fb87.png)

**Debug**

[debug_fulltrust.txt](https://github.com/files-community/Files/files/5843972/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/5843973/debug.txt)

**Comment by gave92** [comment]
Could you verify that:
- In Windows Settings > Privacy > File system permission is turned on for Files
- Can you access any folder in those missing drives if you type the path in the navigationbar?

**Comment by gmusa** [comment]
"In Windows Settings > Privacy > File system permission is turned on for Files" resolved the issue thank you!
