### ISSUE TITLE
add separators between files/folders to type organization

### ISSUE THREAD

**Issue by migueljgoliveira** [files-community/Files#3192]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I want files and folders to be separated as it happens in File Explorer/Finder, when organised by type. 

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by gave92** [comment]
Merging with #1874
