### ISSUE TITLE
Folder and Files Not Deleting Due to Insufficient Administrator Permissions

### ISSUE THREAD

**Issue by TheTechGeekMicx** [files-community/Files#3193]
### **The Bug:**
There is a bug on the Files app when you try and delete a file or folder that requires administrator approval before deleting or moving. When you try, you just get an error thrown at you on the 'Ongoing Tasks' section.

### **Steps to reproduce:**
1. Right click on a folder which require administrator approval
2. Click delete
3. Click the 'Ongoing Tasks' button
### **Additional Information:**
The problem occurs on version 1.1.0.0.

### **Log File:**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5845093/debug_fulltrust.txt)

**Comment by gave92** [comment]
Merging with #2513
