### ISSUE TITLE
Snip & Sketch app bug

### ISSUE THREAD

**Issue by farolillo** [files-community/Files#3194]
**Describe the bug**
If I do a snip of the screen and i have some files windows open (but not at the front), doing a snip automatically brings files to the front.

**To Reproduce**
1. Open a Files window.
2. Open something on top of the Files windows.
3. Open the Snip & Sketch app.
4. Take a snip.
5. The Files windows is on top.

**Expected behavior**
Should not be on top. Just don't change where it is.

**Desktop**
 - OS Version: Windows 10 20H2
 - App version: [1.1.0.0
 - Snip & Sketch version: 10.2008.2277.0

**Log file**
Nothing useful.

**Comment by winston-de** [comment]
I'm having this issue with all UWP apps, not just Files.
I think it's probably an issue with Snip & Sketch and/or Windows, not Files.

**Comment by farolillo** [comment]
yes, just checked and it also happens with other UWP apps like the Microsoft Store and the Xbox app.

**Comment by winston-de** [comment]
In that case, you should file a bug report in the [Feedback Hub](aka.ms/feedbackhub).
