### ISSUE TITLE
Context Menu randomly crashes Files

### ISSUE THREAD

**Issue by KibSquib48** [files-community/Files#3196]
**Describe the bug**
In some folders, right clicking crashes Files completely.

**To Reproduce**
1. Go to a folder
2. Right click
3. **boom** crashed

**Expected behavior**
The context menu is supposed to show up

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.746
 - App version: 1.1.4.0

**Additional context**
The problem still happens when I restart the app and try again, but after a few tries it seemed to work again. But then I restarted the app and it happened again

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5846136/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5846137/debug_fulltrust.txt)

**Comment by KibSquib48** [comment]
Update: Happens more frequently on 1.1.5.0, and this time nothing seems to help

**Comment by gave92** [comment]
Hi @KibSquib48 could you post the log files again with 1.1.5? Possibly right after you got a crash due to context menu

**Comment by yaichenbaum** [comment]
@KibSquib48 Thank you for taking the time to report this issue. We need a little more information from you in order to investigate this issue, please reopen this issue when you get a chance to upload the more recent log files.
