### ISSUE TITLE
Search engine problems

### ISSUE THREAD

**Issue by DeViL-CU** [files-community/Files#3197]
When you try to use the search engine to find files, it never finds the files

**Comment by okey2k** [comment]
Yes, indeed.

Already use everything toolbar to mitigate this.

**Comment by yaichenbaum** [comment]
Does turning on the setting to search un-indexed items improve this behavior?

**Comment by DeViL-CU** [comment]
> Does turning on the setting to search un-indexed items improve this behavior?

Ready, the search works for me, thanks
