### ISSUE TITLE
File preview in FILES 1.1.0.0

### ISSUE THREAD

**Issue by sanbausan** [files-community/Files#3198]
**Is your feature request related to a problem? Please describe.**
NO
Everything is fine with the application, it is very intuitive and easy to use.

**Describe the solution you'd like**
I would like it to be able to preview the files like Windows explorer does.

**Describe alternatives you've considered**
There is an application in Microsoft Store called QuickLook that with the space bar shows a preview of the files, I would like a similar function to be added to "FILES".

**Comment by Shomnipotence** [comment]
Files supports QuickLook, you can search the knowledge base to find more content.

**Comment by yaichenbaum** [comment]
@sanbausan Thank you for opening this issue, as mentioned by Shomnipotence, Files already supports QuickLook. If you are looking for something built in, we are working on a preview pane which is almost ready.
