### ISSUE TITLE
Allow change position of tabs and sidebar

### ISSUE THREAD

**Issue by primorolo** [files-community/Files#3199]
it´s so crazy, but would be amazing can invert the position of the tabs and sidebar:

The tabs in the left side or bottom, the side bar in the left or rigth or even top, like a ribbon-Style

**Comment by Shomnipotence** [comment]
The workload of this work may be relatively large, and I personally think that it is necessary to focus on the current functional improvement.

**Comment by yaichenbaum** [comment]
@primorolo Thank you for opening for this issue, this feature request is a little out of scope and we don't have any plans to implement it.
