### ISSUE TITLE
Improve the acrylic brush so that the transparent effect is still retained even when out of focus.

### ISSUE THREAD

**Issue by Shomnipotence** [files-community/Files#3200]
**Is your feature request related to a problem? Please describe.**
Although losing transparency when inactive windows can help improve battery life, there is no doubt that if the transparency effect persists, it will make the interface look more dynamic

**Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/6630660/105281906-1b178a80-5be8-11eb-9081-6a67ebe6499d.png)
In this application, the application window is not a front-end window, and still retains the acrylic transparency effect. Thanks to its improved acrylic brush, I think it can be done technically.

The application is open source, you can also directly contact the developer of the application, I think he is willing to help you.
https://www.notepadsapp.com/

**Describe alternatives you've considered**
no

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by yaichenbaum** [comment]
@Shomnipotence Thank you for opening this issue, as mentioned in your proposal, Acrylic can have an impact on battery life. However, there is another reason that apps switch to the fallback when they are not focused, it's because Acrylic draws the attention of the eye and the attention should usually be on the focused window. While implementing an always-on Acrylic brush isn't impossible, we don't have plans to make this change for the reasons outlined above.

**Comment by D-Maxwell** [comment]
> @Shomnipotence Thank you for opening this issue, as mentioned in your proposal, Acrylic can have an impact on battery life. However, there is another reason that apps switch to the fallback when they are not focused, it's because Acrylic draws the attention of the eye and the attention should usually be on the focused window. While implementing an always-on Acrylic brush isn't impossible, we don't have plans to make this change for the reasons outlined above.

Considering the current state of things, could we perhaps get a setting to decide for ourselves ? I would certainly disable this on my laptop due to the aforementioned drawbacks, however I would gladly have it enabled on my desktop.

**Comment by yaira2** [comment]
@D-Maxwell Technically it's not impossible for us to create a custom brush, but it's out of scope for Files. At the end of the day, the default behavior is managed by Windows so I would refer you to the Feedback Hub.

**Comment by D-Maxwell** [comment]
> @D-Maxwell Technically it's not impossible for us to create a custom brush, but it's out of scope for Files. At the end of the day, the default behavior is managed by Windows so I would refer you to the Feedback Hub.

We both know that the latter "solution" isn't one. If you are unwilling to consider the idea of deviating from Microsoft's guidelines (which it has barely respected itself prior to Windows 11 regardless), could a fully transparent material be considered ? This way, the backdrop material could be applied from third party software and other system modifications.
