### ISSUE TITLE
Auto expand sidebar when hovering over it with the mouse

### ISSUE THREAD

**Issue by primorolo** [files-community/Files#3201]
there are posibilities that the sidebar compact to icons for default and expand automatically when the cursor is positioned over it.

This is a cool alternative for smaller screens or when two panels side by side are open

**Comment by Shomnipotence** [comment]
I love it

**Comment by yaichenbaum** [comment]
@primorolo would you expect it to collapse again once the mouse is no longer hovering over it?

**Comment by primorolo** [comment]
> @primorolo would you expect it to collapse again once the mouse is no longer hovering over it?

Of course, like the "vertical Tabs" in Microsoft edge.

**Comment by yaichenbaum** [comment]
Thank you for your feedback, we don't have plans to implement this particular feature request but we'll continue to keep it in mind.

**Comment by yaichenbaum** [comment]
Thank you for your feedback, we don't have plans to implement this particular feature request.
