### ISSUE TITLE
App crashes while renaming files

### ISSUE THREAD

**Issue by pratik-choudhari** [files-community/Files#3205]
**Describe the bug**
I was renaming .png files and here's what happened. When one file is renamed the pointer moves onto next file automatically now when I press F2(rename shortcut) the app crashes every time, even after restart.

**To Reproduce**
1. Go to any folder with multiple files/folders
2. Click on a file and rename it
3. After renaming the cursor moves down a file automatically and now press F2
4. App crashes with report message

**Expected behavior**
Either the file should get renamed or wait for me to explicitly click on file to rename rather than auto scrolling one file down.

**Screenshots**
App  crashes after this screen
![crash](https://user-images.githubusercontent.com/40862682/105311166-611e1f80-5be3-11eb-809f-9e86a75702d2.png)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1909 18363.1316]
 - App version: [v1.1.0.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?
No other issues

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`, you should see a file in this directory called debug.txt or/and debug_fulltrust.txt.
[debug.txt](https://github.com/files-community/Files/files/5847407/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5847408/debug_fulltrust.txt)

**Comment by gavinayling** [comment]
This happens to me regularly. Is there a workaround until it's fixed?

**Comment by pratik-choudhari** [comment]
Yeah, instead of relying on files to move on to the next file
automatically, you can manually click and rename the files you want to
rename.

**Comment by BanCrash** [comment]
In Files v2.0, and probably on lower versions, after you rename a file the selection will gone and none file will be selected. Pressing F2 after doing that won't make Files crash, even without a file selected. So I think this is solved.

![GIF 02-09-2021 22-00-34](https://user-images.githubusercontent.com/11770760/131908428-4aba3e29-0408-44ef-8562-7e3d0177e109.gif)

@yair100
