### ISSUE TITLE
Add SVN integration (icons status and TortoiseSVN to contextual menu)

### ISSUE THREAD

**Issue by melon-boy** [files-community/Files#3206]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add integration with Tortoise SVN. Show SVN icons in a repository folder and add Tortoise SVN to contextual menu.

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by gave92** [comment]
Both functionalities should be already present. Installing tortoise svn should be enough for it to popup in the context menu and icon overlays.
Do you see them in explorer but not in files? Even after restarting Files?

**Comment by yaichenbaum** [comment]
@melon-boy We need a little more information from you in order to investigate this issue, please reopen this issue once you have filled out the issue template.

**Comment by masta** [comment]
This is probably related to #8633 as the TortoiseGIT/SVN items aren't shown in the context menu on empty folder areas.
