### ISSUE TITLE
I can't see the files in Onedrive 

### ISSUE THREAD

**Issue by ernestomiralles** [files-community/Files#3208]
Hi,

I have any files in my onedrive but "files" can't show me.

Thanks.

Ernesto.

**Comment by gave92** [comment]
Could you share a screenshot of your OneDrive folder as it appears in Files and Windows Explorer?

**Comment by yaichenbaum** [comment]
@ernestomiralles We need a little more information from you in order to investigate this issue, please reopen this issue once you have filled out the issue template.
