### ISSUE TITLE
recicle bin

### ISSUE THREAD

**Issue by LazaroBC** [files-community/Files#3209]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`, you should see a file in this directory called debug.txt or/and debug_fulltrust.txt.

I was hoping I could empty the trash can, but it says it's empty when it's not.

Windows 10 Education N
20H2
19042.746
APP version: 1.1.0.0

![Captura de pantalla 2021-01-21 112205](https://user-images.githubusercontent.com/55431104/105337859-2c0dcf00-5bdb-11eb-8c74-e9bc64d835c4.png)

**Comment by gave92** [comment]
Thanks for the report.
- could you post the app log files?
- could you check if in task manager you see a process called "FilesFullTrust.exe"?
- also happens when there are more files in recycle bin?

**Comment by yaichenbaum** [comment]
@LazaroBC We need a little more information from you in order to investigate this issue, please reopen this issue once you have filled out the issue template.
