### ISSUE TITLE
Tab Pin

### ISSUE THREAD

**Issue by gusgeek** [files-community/Files#3210]
I would like that in the tabs you can pin each one to a reference folder as happens in current browsers. In my case I usually open the same directories, this possibility would be excellent.

**Comment by gave92** [comment]
Same as #3068?

**Comment by gusgeek** [comment]
> ¿Igual [que #3068?](https://github.com/files-community/Files/issues/3068)

Exactly, but I see that at least in the Microsoft Store version this option is not available, I will check with the package they have on GitHub to see what results it gives me.
<img src="https://i.ibb.co/w4f8Grw/Captura-de-pantalla-2021-01-21-170343.png">

**Comment by gusgeek** [comment]
Nope, I don't see it in the Package they have on Github either. Will it be coming in a next update?

**Comment by gave92** [comment]
It's still an open issue so it's not implemented yet. As it's the same request I'm going to merge this two issues together

Merging with #3068
