### ISSUE TITLE
The program crushes when i click on any drive on my pc 

### ISSUE THREAD

**Issue by AbdoLaatiba** [files-community/Files#3212]
**Describe the bug**
when i click on my c drive or any other drive the application crushes 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`, you should see a file in this directory called debug.txt or/and debug_fulltrust.txt.

**Comment by gave92** [comment]
Please add Files app version and the log files to the issue description

**Comment by yaichenbaum** [comment]
@AbdoLaatiba We are having a little trouble investigating this issue, please reopen this issue when you have filled out the issue template.
