### ISSUE TITLE
Sidebar default links and library cards widget paths should follow Windows defaults

### ISSUE THREAD

**Issue by meow81** [files-community/Files#3216]
**Is your feature request related to a problem? No

**Describe the solution you'd like**
I have multiple drives for different purposes: C: solid state with only Windows and programs for fast loading.  I've set up my documents, music, photos, videos to be saved on my user files HDD (E:) through the windows storage setting.  In Files, I'd like the library cards widget to open the correct libraries given this set up.  Given it's a standard setting in Windows to be able to change the default location for different libraries, I'd expect Files to take me to the correct location when I click the library cards widget links or the default links in the sidebar.

![image](https://user-images.githubusercontent.com/22875048/105405091-be709b80-5bf8-11eb-86ac-ddb88065b090.png)

I've removed and added the correct libraries in the sidebar, just can't do something similar in the widget space.
![image](https://user-images.githubusercontent.com/22875048/105405167-d516f280-5bf8-11eb-8427-3b7d4c62a542.png)

**Describe alternatives you've considered**
None that I know of.

**Additional context**
v1.1.0.0

**Comment by gave92** [comment]
@meow81 could you check if deleting this file: "%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalCache\PinnedItems.json" make the sidebar pick up the new paths?
Note: you'll loose manually pinned folders

**Comment by meow81** [comment]
@gave92 just deleted it, restarted the app and it did reset the sidebar, but still points to C: (windows drive) default paths.

**Comment by yaichenbaum** [comment]
Merging with #2709.
