### ISSUE TITLE
View does not update after pasting and replacing file

### ISSUE THREAD

**Issue by tgrelka** [files-community/Files#3218]
**Describe the bug**
When pasting a file into a folder and replacing an already existing one, the view will not automatically update to reflect changes, e.g. Last Changed date.

**To Reproduce**
1. Copy any file.
2. Open a folder containing a different file with the same name.
3. Paste and select Replace.
4. See view not update to reflect change.

**Expected behavior**
If I copy and paste a new file, replacing an existing one, I expect to see the file’s information like size and last changed to update.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Pro 20H2 19042.746
 - App version: 1.1.0.0

**Comment by yaichenbaum** [comment]
@tgrelka Is this still an issue in v1.5?
