### ISSUE TITLE
Date modified get updated real time [Feature Request]

### ISSUE THREAD

**Issue by kimlimjustin** [files-community/Files#3221]
**Is your feature request related to a problem? Please describe.**
Date modified is always staying on a specific time ago without getting updated. Ex: I download a file and it keeps showing 0 seconds ago as Date modified.

**Describe the solution you'd like**
Date modified get updated.

**Describe alternatives you've considered**
Showing the exact date modified instead of "time" ago. Ex: showing 22/01/2021 21:25:00 instead of "... seconds ago"

**Additional context**

https://user-images.githubusercontent.com/61906684/105503616-64a3ca80-5cf9-11eb-8fb0-a514b8a60b27.mp4

**Comment by gave92** [comment]
@kimlimjustin you can show the exact date by changing the "date format" option to "System" in Files settings

**Comment by kimlimjustin** [comment]
Oh, okay thanks

> @kimlimjustin you can show the exact date by changing the "date format" option to "System" in Files settings

**Comment by alnz123** [comment]
but the date format is not in the local time i.e. it shows UTC+00:00
