### ISSUE TITLE
Quick view using spacebar

### ISSUE THREAD

**Issue by MarathonMax** [files-community/Files#3222]
On my iMac, I looooooove using the spacebar to get a quickpreview of the file. One COmmander has implemented this feature in Windows but the overall UI is far from being as clean as yours. I understand that Windows has only a limited number of builtin viewers (for example it can't preview RAW files from My Nikon camera).

**Comment by yaichenbaum** [comment]
@MarathonMax Files comes with support for [QuickLook](https://github.com/QL-Win/QuickLook).

**Comment by MarathonMax** [comment]
Man this is goooood !
