### ISSUE TITLE
Add option to pin shortcuts to the sidebar

### ISSUE THREAD

**Issue by MarathonMax** [files-community/Files#3223]
Hey maybe this one has been requested before ... but a drag and drop of a folder or file in a reserved Shortcut collapsible section would be great. By collapsible, I mean to see a open / close triangle to expand and retract (collapse) a section. This could / should be added to the Drives section and maybe the Home section (this section is yet unnamed but starts with the Home location and ends with the Recycle bin).

**Comment by yaichenbaum** [comment]
Merging with #1607
