### ISSUE TITLE
Files crashes

### ISSUE THREAD

**Issue by Josue7425** [files-community/Files#3225]
The app closes when i'm doing a Backup.
Version: 1.1.0.0
[LocalState.zip](https://github.com/files-community/Files/files/5860618/LocalState.zip)

**Comment by gave92** [comment]
Hello @Josue7425 please add the app version and the log files to the issue description

**Comment by yaichenbaum** [comment]
@Josue7425 Is this still an issue in v1.5?

**Comment by Josue7425** [comment]
> @Josue7425 Is this still an issue in v1.5?

The app works normally.
