### ISSUE TITLE
Graphical elements like files and folders take too long to render

### ISSUE THREAD

**Issue by carlosvsilva** [files-community/Files#3227]
**Describe the bug**
Files and folders take too long to "render" (or maybe even be found) when opening a new folder. Sometimes there's a quick render that's erased and replaced with another after a few seconds.

**To Reproduce**
1. Double click any folder
2. Wait for files and folders to appear while sipping from a cup of tea

**Expected behavior**
It should display elements like files and folders as fast as MS Windows Explorer

**Screenshots**
Happens anywhere.

**Desktop (please complete the following information):**
 - OS Version: Microsoft Windows [Version 10.0.19042.746]
 - App version: v1.1.0.0

**Additional context**
Occurs every time

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`, you should see a file in this directory called debug.txt or/and debug_fulltrust.txt.
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5857311/debug_fulltrust.txt)

**Comment by yaichenbaum** [comment]
@carlosvsilva This behavior has seen some significant improvements and will be included with the next release. We still have some work to do here... but I don't think you will have enough time for that tea anymore 😂.

**Comment by carlosvsilva** [comment]
eheheh thanks! cheers
