### ISSUE TITLE
Errores en la compilacion

### ISSUE THREAD

**Issue by salmantino** [files-community/Files#3229]
Good afternoon, I get the following in the compilation
************************************************** ************************************************** ****************
Compile operation started ..
1> ------ Compile operation started: project: Files.Launcher, configuration: Debug Any CPU ------
1> CSC: error CS0006: Metadata file 'F: \ files \ Common \ bin \ Debug \ netstandard2.0 \ Common.dll'
2> ------ Compile operation started: project: Files.Package, configuration: Debug x86 ------
2> F: \ files \ Files \ Files.csproj (941,5): warning: Files.csproj is Multilingual build enabled, but the Multilingual App Toolkit is unavailable during the build. If building with Visual Studio, please check to ensur Good afternoon, I get the following in the compilation
************************************************** ************************************************** ****************
How do I solve it?

Greetings .............. Miguel

**Comment by XPoppyX** [comment]
@salmantino Sigues teniendo este problema actualmente?

**Comment by salmantino** [comment]
Si, es con Windows 7

Enviado desde el móvil

**Comment by XPoppyX** [comment]
Supongo que ese es el problema, La mayor parte de esta app es compatible **solo con windows 10**, y los desarrolladores **no** tienen planes por el momento de hacer un backport a windows 7.

**Comment by XPoppyX** [comment]
@yaichenbaum I think this can be closed, he is trying to compile on windows 7, so...

**Comment by salmantino** [comment]
Gracias por la contestación, era lo que me suponía, en W10 la tengo y me gusta mucho
