### ISSUE TITLE
Allow extensions to provide file/folder actions

### ISSUE THREAD

**Issue by winston-de** [files-community/Files#3232]
**Is your feature request related to a problem? Please describe.**
This would allow UWP apps (and packaged desktop applications) to provide similar utilities to Windows shell extensions like "open folder with Code", "open folder in Windows terminal", "Power Rename", "image resizer", etc, for Files.

**Describe the solution you'd like**
Similar to the preview pane extension implementation, extensions would register their app service, and have a Json file containing something like the following:
- A list of supported file types (including folders)
- A list of localized names for the action
- A path to the action's icon
- Whether or not multiple items are supported

The action could then be shown in the context menu for selected items, if the selection is supported by the extension.
When the action is invoked, the extension would receive an access token for the file (s) or folder. 
After being invoked, the service could then return a status code (failure, success, etc) to Files. 

**Describe alternatives you've considered**
- have apps use Windows shell extensions
- build integration with other apps into Files

**Additional context**

**Comment by duke7553** [comment]
Would these extensions be coded specifically for Files, or would they work for other participating apps by default?
Here's a mock-up I created earlier this year.
![Potential design](https://user-images.githubusercontent.com/20365014/105606151-a79b8780-5d65-11eb-848e-d5b0c82963a6.png)

**Comment by winston-de** [comment]
Any UWP or packaged desktop application would be able to function as an extension for Files. All that has to be done is create an app service, and add that service to the app manifest with the proper name.

My thinking was that the extensions would serve the same purpose as the context menu shell extensions in Windows Explorer do now, and could also be displayed in a similar manner as they are now.

**Comment by winston-de** [comment]
At the time of writing, I did not realize that UWP applications could register file explorer context menu items. Since Files already can show those, there isn't much point in implementing this.
