### ISSUE TITLE
QuickLook does not work

### ISSUE THREAD

**Issue by Ein-Tim** [files-community/Files#3233]
**Describe the bug**
I installed [QuickLook](https://github.com/QL-Win/QuickLook) from the Microsoft Store and it is working correctly with the Windows Explorer. However, if I hit the Space key for a file in Files, nothing happens.
Since I am a newbie using QuickLook, it is possible that I did something wrong. 

**To Reproduce**
1. Download QuickLook from the Microsoft Store
2. Use it in the Windows Explorer -> working
3. Try to use it with Files -> nothing happens

**Expected behavior**
The pop up showing the content of a file should pop up after hitting the space key.

**Screenshots**
/

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Home Version 20H2 (Build 19042.746)
 - App version: 1.1.0.0

**Additional context**
As stated above, it could be possible that I am doing something wrong. If so, maybe somebody could help me 😊
Thanks for this great App!

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5858101/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5858102/debug_fulltrust.txt)

**Comment by gave92** [comment]
@Ein-Tim reopening this as the cause looks different

**Comment by Ein-Tim** [comment]
Thanks @gave92. Please leave it open for a bit. It is working with the .msi installer I downloaded from https://github.com/QL-Win/QuickLook/releases. I will test again with the Microsoft Store Version.

**Comment by Ein-Tim** [comment]
Okay, now working with version from the Microsoft Store too. I really don't know why it was not working before.
Sorry for this (unnecessary) issue. 

Have a nice evening
