### ISSUE TITLE
Visual Studio context action opens built-in File explorer instead of Files

### ISSUE THREAD

**Issue by v-zubritsky** [files-community/Files#3241]
**Describe the bug**
Even though Files integration is enabled (by registry modification), built-in file explorer opens instead of Files. So it means integration doesn't cover some entry points.

**To Reproduce**
1. Open any solution in Visual Studio
2. Execute `Open in file explorer` solution explorer context action on any project

**Expected behavior**
Files is opened

**Actual behavior**
Windows original file explorer is opened instead

**Screenshots**
<img width="287" alt="VS-UI" src="https://user-images.githubusercontent.com/5411526/105580202-05e35d00-5d9c-11eb-8239-6cc42e46f0c7.png">

**Desktop (please complete the following information):**
OS Name: Windows
OS Version: 10.0.18363
OS Platform: Windows
RID: win10-x64
Files version: 1.1.0.0
Visual Studio version: Visual Studio Community 2019 16.8.3

**Comment by gave92** [comment]
See #3090

**Comment by v-zubritsky** [comment]
@gave92 thanks. Going to test it.
Maybe it makes sense to add it to the documentation with some "danger" label, so that you don't receive additional duplicates of this issue :)

**Comment by v-zubritsky** [comment]
@gave92 Works now. Closing.
