### ISSUE TITLE
Add MFT Entry modified timestamps for NTFS filesystem

### ISSUE THREAD

**Issue by ungubajue90k** [files-community/Files#3244]
**Is your feature request related to a problem? Please describe.**
There is no file manager (GUI) on Windows 10 that displays MFT Entry modified timestamps.

The vision of Files is:
> Later on, the project will reach a point where we can fully celebrate our core audience by adding sought-after power user features. Stay tuned!

**Describe the solution you'd like**
Because it is a function for power user there should be an option in settings to decide if it will be displayed in list view column.

**Describe alternatives you've considered**
N/A

**Additional context**
MFT Entry modified timestamps is compared to Linux file systems e.g Btrfs or ext4 -> change time.

Here more information:
https://forensixchange.com/posts/19_04_22_win10_ntfs_time_rules/

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
@ungubajue90k I'm not very familiar with this so forgive the rookie question, can you give a short description on what this is and how it'll help your workflow?

**Comment by Josh-65** [comment]
@ungubajue90k can you add the asked infomation
