### ISSUE TITLE
Shortcut Windows + R C:\ doesn't open Files but Windows File Explorer

### ISSUE THREAD

**Issue by scls19fr** [files-community/Files#3248]
Hello,

Replacing File Explorer with Files is possible according https://files-community.github.io/docs/#/articles/replace-file-explorer
It's an unsupported method but which works fine in my case except when using shortcut Windows + R C:\ 
In such a cas Windows File Explorer is opened instead of files.
but it's quite surprising to notice that Windows + R C:\Windows opens this folder using Files.
Any idea ?

Kind regards

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
