### ISSUE TITLE
Folder options(from classic explorer)

### ISSUE THREAD

**Issue by tomyan112** [files-community/Files#325]
[#177] show hidden files, folders and drives
[#261] Single-click to open an item (point to select)
- [ ] Option to hide empty drives

- [x] Hide extensions for known files types
- [ ] Underline item titles only when I point at them

**Comment by yaichenbaum** [comment]
Thank you for opening this issue. You should already be able to hide extensions for known file types. We will look into supporting the other options requested in the future.

**Comment by yaichenbaum** [comment]
Merging with #795.
