### ISSUE TITLE
Window cannot be moved by dragging header

### ISSUE THREAD

**Issue by SimonCDalzell** [files-community/Files#3250]
**Describe the bug**
Often, the window cannot be moved by dragging the header. This appears to have something to do with the multitasking mode.

**To Reproduce**
Attempt to move window by clicking and dragging it. Window does not move. Sometimes resizing the window until the layout changes (when adaptive mode is on of course) allows the window to be moved.

**Expected behavior**
Windows moves always.

**Screenshots**
Here's a [video.](https://user-images.githubusercontent.com/19229302/105626309-81461c80-5e37-11eb-8002-d047268dd088.mp4)

The window closing at the end was an unexpected crash that I haven't run in to before.

**Desktop (please complete the following information):**
Windows 10 1809 17763.1679
1.1.0.0

**Additional context**
I have not had much luck tracking down exactly when this happens or doesn't. 

**Log file**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5861876/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/5861877/debug.txt)

**Comment by glitchcodes** [comment]
It seems that this only happens when Tab Customization setting is set to Vertical Mode

**Comment by Ein-Tim** [comment]
I've set it to adaptive and experience this too.

**Comment by glitchcodes** [comment]
Heres a comparison between Vertical and Adaptive:

https://user-images.githubusercontent.com/56838797/107347317-a8bc0b00-6b00-11eb-8656-4ea9e5c6b0dc.mp4


https://user-images.githubusercontent.com/56838797/107347521-e02ab780-6b00-11eb-8b9a-8dadc0dd3411.mp4

**Comment by yaichenbaum** [comment]
@SimonCDalzell This issue should be resolved in `main`.
