### ISSUE TITLE
Please, allow several OneDrive in FILES. 

### ISSUE THREAD

**Issue by irslo** [files-community/Files#3251]
**Is your feature request related to a problem? Please describe.**

_I use several OneDrives (1 personnal and 2 pro accounts) and 2 Sharepoints accounts. In the Windows Explorer, I can see this 5 OneDrives/SharePoints. In Files, I only see my personnal OneDrive and a Shrepoint account (pro)._ 

**Describe the solution you'd like**
_I'd like to see all my OneDrives and Sharepoints in Files, in order to work only in files._ 

**Describe alternatives you've considered**
_I don't have an alternative._ 

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

Thank you for your work !

**Comment by gave92** [comment]
Multiple OneDrive accounts support was added in #3177. For SharePoint merging with #1310

**Comment by irslo** [comment]
I'm sorry I only have one onedrive personnal account and one professionnal sharepoint account. 
Multiple account seem not being supported in the version i use (1.1.0.0 )
![image](https://user-images.githubusercontent.com/7957514/105638548-65606c00-5e73-11eb-9e55-a39eaab87bb5.png)
![image](https://user-images.githubusercontent.com/7957514/105638558-75784b80-5e73-11eb-8a5d-731522086808.png)

If I can help giving logs or anything else...

**Comment by irslo** [comment]
Here is what I have in the Windows Explorer : 
![image](https://user-images.githubusercontent.com/7957514/105638731-9c834d00-5e74-11eb-9180-27131f13ca95.png)

**Comment by gave92** [comment]
@irslo sorry if I misinterpreted, Files currently supports:
- A single personal account
- A single business account
- Sharepoint accounts are not supported, status tracked here -> #1310
- Multiple business accounts support is being tested in beta version and will ship to everyone with the next public version
