### ISSUE TITLE
Unpin folder failed

### ISSUE THREAD

**Issue by fxzxmicah** [files-community/Files#3255]
**Describe the bug**
Unable to unpin this pinned folder, and this folder has been deleted.

**To Reproduce**
1. Go to Start Menu
2. Right Click on “Files” icon
3. Clicking Unpin has no effect

**Expected behavior**
Unpin this pinned folder

**Screenshots**
![image](https://user-images.githubusercontent.com/48860358/105629980-2507ea80-5e81-11eb-8460-58179d54af1c.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.746
 - App version: v1.1

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5862189/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5862190/debug_fulltrust.txt)

**Comment by yaichenbaum** [comment]
@fxzxmicah The pinned items on the jumplist is a Windows feature and is a different list than the sidebar in Files.

**Comment by fxzxmicah** [comment]
@yair100 So there's no way to solve it?

**Comment by yaichenbaum** [comment]
@fxzxmicah Are you trying to remove OneDrive from the sidebar?

**Comment by fxzxmicah** [comment]
@yair100 I didn't pin the Onedrive folder to the sidebar, and I tried to pin and remove it, but it didn't work.

**Comment by fxzxmicah** [comment]
@yair100 It seems to have been solved after clearing "%APPDATA%\Microsoft\Windows\Recent\AutomaticDestinations" and "%APPDATA%\Microsoft\Windows\Recent\CustomDestinations".

**Comment by yair100** [comment]
> @yair100 It seems to have been solved after clearing "%APPDATA%\Microsoft\Windows\Recent\AutomaticDestinations" and "%APPDATA%\Microsoft\Windows\Recent\CustomDestinations".

Thanks for the update, I am glad you were able to work it out.

**Comment by fxzxmicah** [comment]
I think it would be better if the pinned list is consistent with the software sidebar. What do you think? After all, Windows Explorer is like this.

**Comment by yaichenbaum** [comment]
> I think it would be better if the pinned list is consistent with the software sidebar. What do you think? After all, Windows Explorer is like this.

I agree, I am not sure we have the same permission as File Explorer in this area, but we can look into it. Can you open a separate issue for tracking this?

**Comment by fxzxmicah** [comment]
> > I think it would be better if the pinned list is consistent with the software sidebar. What do you think? After all, Windows Explorer is like this.
> 
> I agree, I am not sure we have the same permission as File Explorer in this area, but we can look into it. Can you open a separate issue for tracking this?

Certainly.

**Comment by fxzxmicah** [comment]
@yair100 https://github.com/files-community/Files/issues/3311

**Comment by yair100** [comment]
> @yair100 #3311

Thank you.
