### ISSUE TITLE
SideBar missing OneDrive Business account

### ISSUE THREAD

**Issue by okey2k** [files-community/Files#3258]
**Describe the bug**
Only one OneDrive Business shown in the sidebar while multiple OneDrive Business accounts logged on.

**To Reproduce**
1. Open Files.
2. Check the Number of OneDrive Commercial.

**Expected behavior**
List all logged OneDrive accounts in the sidebar as File Explorer does.

**Screenshots**
![Screenshot 2021-01-24 151205](https://user-images.githubusercontent.com/32120698/105633014-91b9bf80-5e56-11eb-918a-89eafd7cf235.png)
![Screenshot 2021-01-24 150953](https://user-images.githubusercontent.com/32120698/105633017-92525600-5e56-11eb-8ec2-1e04dea69571.png)
![Screenshot 2021-01-24 151039](https://user-images.githubusercontent.com/32120698/105633018-92525600-5e56-11eb-909f-cf3da896fe54.png)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 Pro 20H2 19042.746 ]
 - App version: [v1.1.0.0]

**Comment by gave92** [comment]
Implemented in version 1.1.5. This will be included in the next public release.
