### ISSUE TITLE
Lagging on 4k screens

### ISSUE THREAD

**Issue by ahmednrana** [files-community/Files#3260]
**To Reproduce**
1. Open the app
2. Using it on 4k screen causes lagging. Although the laptop has good specs and other apps works well
3. Works fine if I use it to an external screen

**Expected behavior**
Should be smooth

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2 19042.746]
 - App version: [v1.1.0.0]

**Comment by gavinayling** [comment]
I am running on a 4K screen and only a 7th gen i7 - it runs smoothly here.

**Comment by ahmednrana** [comment]
I see .
You using a graphics card?
You using it on a laptop screen? because if its laptop screen windows does not use the graphics card but the internal Intel graphics chip for desktop apps which is not as performant as graphic cards

**Comment by gavinayling** [comment]
I have a laptop with an nVidia and Intel, as you describe.

**Comment by ahmednrana** [comment]
Ok then it could be my machine only
