### ISSUE TITLE
Crash when opening a new tab

### ISSUE THREAD

**Issue by gavinayling** [files-community/Files#3262]
**Describe the bug**
I have only been using Files for a couple of days and when I opened a new tab one time, it force-closed and asked me if I wanted to submit a bug report.

**To Reproduce**
1. Open a tab. Use that for a long time.
2. Right-click on a folder in the first tab's sidebar and choose open in new tab.

**Expected behavior**
A new tab would open and Files would not force-close.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.782 (Insider)
 - App version: v1.1.0.0

**Additional context**
The program has force-closed twice, but only once did it offer a bug report.

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location.
[debug.txt](https://github.com/files-community/Files/files/5862441/debug.txt)

**Comment by gave92** [comment]
@gavinayling thanks for this report. The log file contains only one crash report: a crash happened (today) upon pressing "F2" to rename a file.

**Comment by gavinayling** [comment]
I was not aware that it had crashed when renaming a file, but that was much earlier than the force-close. Perhaps the cause of the crash was not caught by the logs?

**Comment by gave92** [comment]
> Perhaps the cause of the crash was not caught by the logs?

@gavinayling yeah I feared that much :)

**Comment by yaichenbaum** [comment]
@gavinayling Is this still an issue in v1.5?

**Comment by gavinayling** [comment]
It does not appear to be!!
[bitmoji](https://sdk.bitmoji.com/render/panel/2063b3b3-2054-4a07-83b6-0a10a04de771-721131e3-0798-46ac-a25c-b68f3a3c5b3f-v1.png?transparent=1&palette=1&width=246)
