### ISSUE TITLE
selecting files

### ISSUE THREAD

**Issue by mrcoder991** [files-community/Files#3263]
**Describe the bug**

**To Reproduce**
1. Go to 'any folder say D drive '
2. Click on 'try selecting multiple items by clicking and dragging'
3. error is when view is set to grid view (small) i can select multiple files but when i choose to view in detailed list mode i can't click and drag to select 
4. there is another bug or performence  glich i experienced that is the context menu doesn't appear as soon as i click right click there is a lag in that so sometimes i feel like i didn't clicked correctly or there is fault in my mouse

**Expected behavior**
the click and drag should work in every case 
and there is need to fix lag in context menu opening

**Screenshots**
![image](https://user-images.githubusercontent.com/66244185/105634296-508bd480-5e83-11eb-967f-428cca6cb23b.png)
![image](https://user-images.githubusercontent.com/66244185/105634324-744f1a80-5e83-11eb-882a-3039f8d05953.png)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2 120.2212.31.0]
 - App version: [v1.1.0.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?
sometimes it fixes itself the feature which is not working previously starts working after restart but that is annoying it should work as expected right out of the box
**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`, you should see a file in this directory called debug.txt or/and debug_fulltrust.txt.
[debug.txt](https://github.com/files-community/Files/files/5862495/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5862496/debug_fulltrust.txt)

**Comment by rusti4** [comment]
I tried doing what you have explained and didn't get any issues. I'm also running Version 1.1.0.0. But I have a newer Windows version it seems. 120.2212.551.0

**Comment by mrcoder991** [comment]
Actually at first I opened the app it was error but when I was posting and
it asked for screenshot It somehow worked I don't know why it should work
at first time I opened

I tried to drag and drop files when I first opened but it didn't work also
so I thought it seems developer doesn't added that feature but somehow 3 or
4 th time I opened app it worked

I think it's a glitch that should be fixed or some new users can be
misunderstood and can uninstall app right away

**Comment by generalguy41** [comment]
It seems this actually works correctly when in details view in dual pane mode (v1.1.0.0, Windows 10 Pro 2004 21301.1000).

https://user-images.githubusercontent.com/8879244/106362011-7cc5ac00-62ee-11eb-86b1-dc4a1f56b43f.mp4

**Comment by yaichenbaum** [comment]
This issue appears to be resolved in `main`.
