### ISSUE TITLE
application crashed when changing name

### ISSUE THREAD

**Issue by OlegSolomatin** [files-community/Files#3268]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`, you should see a file in this directory called debug.txt or/and debug_fulltrust.txt.

**Comment by gave92** [comment]
Add app version and log files please :)

**Comment by yaichenbaum** [comment]
@OlegSolomatin We need a little more information from you in order to investigate this issue, please reopen this issue once you have filled out the issue template.
