### ISSUE TITLE
[Bug] UI bugs with Bundles widget

### ISSUE THREAD

**Issue by KristofKekesi** [files-community/Files#3269]
##  **Describe the bug**
UI Bugs in version 1.1.5.0
### 1.
When I create a bundle (from the big + icon), type in the name and press enter, I get input field empty warning. (the input isn't empty)

### 2.
When I create a bundle from the right side three dots, the popup is out of theme. (I'm using dark theme in the app and light in windows)

### 1.
Make a bundle without any warning.

### 2.
Dark theme poup.

### 1.
![iuzlokftzgduj](https://user-images.githubusercontent.com/64812024/105636713-de5ac600-5e69-11eb-81a9-dcb4fbc5e3c6.PNG)

### 2.
![ghjzfvljuh](https://user-images.githubusercontent.com/64812024/105636874-9c7e4f80-5e6a-11eb-960b-1146b3b8e43b.PNG)

## **Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2 19042.746]
 - App version: [v1.1.5.0]
 
**Log file**
Nothing suspicious.

**Comment by yaichenbaum** [comment]
@d2dyno1

**Comment by d2dyno1** [comment]
as soon as #3215 is merged

**Comment by d2dyno1** [comment]
@yair100 #3286
