### ISSUE TITLE
[Feature request] Add shortcut support to Bundles

### ISSUE THREAD

**Issue by KristofKekesi** [files-community/Files#3270]
**Is your feature request related to a problem? Please describe.**
I cannot add Microsoft Store apps to the bundle. I tried making shortcuts and use them to add them to a bundle, but it didn't worked.

**Describe the solution you'd like**
Ability to add files and folders to bundles from shortcuts. (As well something with adding MS Store apps)

**Comment by d2dyno1** [comment]
It'll be added with my Improved Bundles PR, you can see list of these changes here under the "**Future Bundles PR**": 
https://github.com/files-community/Files/pull/2881

**Comment by yaichenbaum** [comment]
@KristofKekesi This enhancement was implemented with #3637.
