### ISSUE TITLE
The app freezes sometimes when you leave it in the background

### ISSUE THREAD

**Issue by Rick-HM** [files-community/Files#3272]
This does not always happen, leaving it in the background tends to freeze.

**1.** Open Files
**2.** Leave it open and go to another window / software
**3.** There is a chance that it will freeze when returning to the Files window

There is nothing in the log to help

![freeze](https://user-images.githubusercontent.com/61259627/105640334-38548f00-5e5c-11eb-9a21-d69b1b1c2d48.gif)

**Comment by rusti4** [comment]
I've found this too, but it will randomly hang and then just crash and close.

**Comment by SOI7** [comment]
Happens to me sometimes as well. Can't really figure out what triggers it

**Comment by winston-de** [comment]
I've noticed that if I minimize it then restore the window a few times, it will usually start responding again.

**Comment by nt4f04uNd** [comment]
same thing

https://user-images.githubusercontent.com/39104740/112202348-56532b80-8c22-11eb-9741-1afe47b3b25f.mp4

**Comment by winston-de** [comment]
I believe this is an issue with the app coming out of the suspended state.
Interestingly, opening a folder pinned to the start menu will "reactivate" the app, and it will start responding again.

**Comment by josh-65** [comment]
This has happens a lot for me in 1.9.28.

**Comment by josh-65** [comment]
Is there any way around the windows suspension stuff. ideally just for files. In v2 it gotten to the point were the is unusable for me.

**Comment by winston-de** [comment]
There is, but it requires special permission to use in the store (rescap). With v2 i have personally stopped having this issue at all. 
Out of curiosity, what windows version are you using?

**Comment by josh-65** [comment]
10.0.19043.1202

**Comment by Rick-HM** [comment]
@yaichenbaum for me it no longer happens
