### ISSUE TITLE
Search doesn't work in a big folder

### ISSUE THREAD

**Issue by Laser42** [files-community/Files#3275]
**Describe the bug**
I have a folder E:/Movies which contains videofiles as well as subfolders. The total size is 1.2 Tb. In a Files UI, I go inside E:/Movies and start typing in search input. No suggestions is available and when I finish typing and push enter, no search results are displayed. When I type in search input in disk root (E:/), I see the suggestions, but not for the files in E:/Movies. If I type name completely, there is no result from E:/Movies too.

**To Reproduce**
1. Go to really big folder filled by mkv files (1-8 GB)
2. Click on search icon
3. Type the begining chars of existing file's name
4. See nothing search results

**Expected behavior**
Search result which includes searched file

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: Windows 10.0.19041
 - App version: [v1.1.0.0]

**Additional context**
Restart doesn't help, this is constant behavior

**Log file**
Seems to have no errors

**Comment by yaichenbaum** [comment]
Is the folder indexed?
