### ISSUE TITLE
Crashes clicking a drive

### ISSUE THREAD

**Issue by xSojo** [files-community/Files#3280]
**Describe the bug**
When I click any driver the app crashes.

**To Reproduce**
Click any Drive.

**Expected behavior**
Open the drive folder.

**Desktop:**
 - OS Version: Windows 10 20H2 19042.631
 - App version: 1.1.0.0

**Additional context**
It happens always.

**Log file**
[log.txt](https://github.com/files-community/Files/files/5863390/log.txt)

**Comment by gave92** [comment]
Related appcenter: [1693596875u](https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/1693596875u/overview)

Appcenter points to [this line](https://github.com/files-community/Files/blob/v1.1/Files/Views/MainPage.xaml.cs#L270), and I don't know what it means.

**Comment by yaichenbaum** [comment]
@xSojo This issue should be resolved in v1.3.
