### ISSUE TITLE
When using Ctrl + X in the Recycle Bin the file name changes

### ISSUE THREAD

**Issue by EtianAM** [files-community/Files#3281]
**Describe the bug**
When you use "Ctrl + x" in the Recycle Bin, the file name is left with a strange name.

**To Reproduce**
1. Delete a file
2. Go to Recycle Bin
3. Cut the file to a folder
4. The file name will have changed

**Expected behavior**
The name should not have changed

**Screenshots**
![image](https://user-images.githubusercontent.com/42478705/105652513-102a5780-5e7f-11eb-80b5-bd9e257168ad.png)
![image](https://user-images.githubusercontent.com/42478705/105652583-3819bb00-5e7f-11eb-9efe-f5c778d4f85e.png)
![image](https://user-images.githubusercontent.com/42478705/105652613-4b2c8b00-5e7f-11eb-91ac-b4d8d71fe7e9.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.746
 - App version: v1.1.0.0

**Additional context**
The file extension does not change and the file is not corrupted in any way. I'm not entirely sure, but the file name always starts with a "$". In the log there is an error, however I think this error is from yesterday's crash.

**Log file**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5863752/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/5863753/debug.txt)

**Comment by gave92** [comment]
Thanks for this feedback. That's the name files have in the recyclebin. Cut pasting from the bin should be disallowed until we properly support it.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5406.
