### ISSUE TITLE
No se puede mover la ventana sino es con los atajos de teclado.

### ISSUE THREAD

**Issue by dconstanti** [files-community/Files#3287]
Hola!
Descubrí vuestra herramienta la semana pasada y me parece una genialidad y posible candidata a sustituir al explorer. De todos modos, no me acaba de funcionar bien. Se cuelga bastante y no puedo mover la ventana por la pantalla, a no ser que lo haga con los atajos de teclado (Windows + cursor). 

Tampoco me carga bien los estados de los ficheros de onedrive. Tengo ficheros sincronizados que no me los marca como tal. 

La versión de files que tengo es la 1.1.0.0 y mi versión de windows es 10.0.19042.746.

Adjunto log de registro por si fuera de utilidad.

Felicidades por esta aplicación que promete!

[debug.txt](https://github.com/files-community/Files/files/5865655/debug.txt)

**Comment by XPoppyX** [comment]
Los desarrolladores preferirían que se publiquen los problemas por separado, para estar más organizado.

**Comment by dconstanti** [comment]
¿Debo abrir la incidencia de nuevo? Daniel Constantí Sánchez De: RichardEnviado: lunes, 25 de enero de 2021 12:14Para: files-community/FilesCC: dconstanti; AuthorAsunto: Re: [files-community/Files] Excelente descubrimiento de herramienta (#3287) Los desarrolladores preferirían que se publiquen los problemas por separado, para estar más organizado.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by XPoppyX** [comment]
Puedes editar el titulo y descripción de este para poner el bug de no poder mover la ventana, y publicas en uno nuevo lo de onedrive

**Comment by dconstanti** [comment]
Claro.   Daniel Constantí Sánchez De: RichardEnviado: lunes, 25 de enero de 2021 13:37Para: files-community/FilesCC: dconstanti; AuthorAsunto: Re: [files-community/Files] Excelente descubrimiento de herramienta (#3287) Puedes editar el titulo y descripción de este para poner el bug de no poder mover la ventana, y publicas en uno nuevo lo de onedrive—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by dconstanti** [comment]
Hecho. Daniel Constantí Sánchez De: MarleandoEnviado: lunes, 25 de enero de 2021 14:45Para: files-community/Files; files-community/FilesCC: dconstanti; AuthorAsunto: RE: [files-community/Files] Excelente descubrimiento de herramienta (#3287) Claro.   Daniel Constantí Sánchez De: RichardEnviado: lunes, 25 de enero de 2021 13:37Para: files-community/FilesCC: dconstanti; AuthorAsunto: Re: [files-community/Files] Excelente descubrimiento de herramienta (#3287) Puedes editar el titulo y descripción de este para poner el bug de no poder mover la ventana, y publicas en uno nuevo lo de onedrive—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
