### ISSUE TITLE
Context Menu shell menu items slow to appear after app startup

### ISSUE THREAD

**Issue by Sibyl666** [files-community/Files#3292]
**Describe the bug**
Context menu "open with" buttons takes arount 10 seconds to appear. I should wait for a while to see "open with" buttons

**To Reproduce**
1. Open folder
2. Right Click

**Expected behavior**
on first right click i should see "open with" buttons

**Screenshots**
This is the first time i open the folder and right click on blank area
![FirstRightClick](https://user-images.githubusercontent.com/54271295/105734222-75478100-5f43-11eb-8132-d0cab131612a.png)
After waiting for a while more "open with" options appear
![AfterWaitingForAWhile](https://user-images.githubusercontent.com/54271295/105734215-74aeea80-5f43-11eb-9ff1-0ce6ee271f5d.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.746
 - App version: 1.1.0.0

**Additional context**
Does this problem occur again after restarting the app? Yes
Problem occur even after i restart pc

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5867944/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5867945/debug_fulltrust.txt)

**Comment by Shomnipotence** [comment]
I ran into the same problem

**Comment by yaichenbaum** [comment]
@Sibyl666 Does this happen if you open the context menu a second time or is it only the first time?

**Comment by Shomnipotence** [comment]
> @Sibyl666 Does this happen if you open the context menu a second time or is it only the first time?

Ones,secound,everytime.....

**Comment by metkm** [comment]
@yair100 Yes it does happen. After around 10 seconds it fixes itself

**Comment by yaichenbaum** [comment]
@Sibyl666 This issue appears to be resolved in `main`.
