### ISSUE TITLE
Info icon next to date format picker redirects to old GitHub Wiki

### ISSUE THREAD

**Issue by rafal06** [files-community/Files#3293]
**Describe the bug**

Info icon Info icon next to date format picker in appearance settings redirects to old [GitHub Wiki](https://github.com/files-community/Files/wiki/Date-formats) instead of the [new one](https://files-community.github.io/docs/#/articles/date-formats).

**To Reproduce**
1. Go to Settings
2. Click on !['i' icon](https://user-images.githubusercontent.com/70489677/105747187-c30eba00-5f40-11eb-9bc2-7bf1ffc4adfd.png) in `Date format` section.

**Expected behavior**
Clicking the icon redirects to Date formats in [new wiki](https://files-community.github.io/docs/#/articles/date-formats)

**Screenshots**

https://user-images.githubusercontent.com/70489677/105748053-dff7bd00-5f41-11eb-9a7e-2bc877e13f25.mp4

**Desktop (please complete the following information):**
 - OS Version: Windows 10 in S mode 20H2 19042.746
 - App version: 1.1.0.0

**Comment by yaichenbaum** [comment]
@rafal06 This issue should be resolved in `main`.
