### ISSUE TITLE
Taskbar shows Media Play Buttons

### ISSUE THREAD

**Issue by ccory2004** [files-community/Files#3298]
**Describe the bug**
The little popup when hovering over the application icon in the taskbar also shows media buttons, see screenshot below:

**To Reproduce**
1. Open Files
2. Hover over icon in taskbar

**Expected behavior**
Not show media play buttons

**Screenshots**
![image](https://user-images.githubusercontent.com/32803874/105796457-851b9100-5f54-11eb-88c1-f275e8799f94.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Version 20H2 Build 19042.746
 - App version: v1.1.0.0

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?
Yes, have also tried reinstallation

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location.
[debug.txt](https://github.com/files-community/Files/files/5871028/debug.txt)

**Comment by yaichenbaum** [comment]
This was a Windows bug and it appears to be fixed with the recent Windows Insider builds.
