### ISSUE TITLE
Files omitted some special files and folders

### ISSUE THREAD

**Issue by hez2010** [files-community/Files#3299]
**Describe the bug**
Files doesn't list some special files and folders

**To Reproduce**
Navigate to `C:\Windows`, you will find some special files and folders such as `Downloaded Program Files`, `Fonts` and `bootstat.dat` don't appear in the list.

**Comment by gave92** [comment]
Do they appear if you uncheck "hide system files and folders" in Files settings?

**Comment by hez2010** [comment]
> Do they appear if you uncheck "Hide protected operating system files" in Files settings?

Still doesn't appear.

**Comment by gave92** [comment]
Strange:
![image](https://user-images.githubusercontent.com/9673091/105811929-9e9cf700-5fad-11eb-8135-7617603a0a0c.png)

**Comment by xumepoc** [comment]
Did you refresh the tab after you activated "Hide protected operating system files"? I had to do manually refresh the tab in order for the files/folder to appear.

**Comment by hez2010** [comment]
> Did you refresh the tab after you activated "Hide protected operating system files"? I had to do manually refresh the tab in order for the files/folder to appear.

Yes I did refresh. 
In addition my system is Windows 10 Dev Insider 21296, I think this may be relevant.

**Comment by generalguy41** [comment]
> Yes I did refresh.
> In addition my system is Windows 10 Dev Insider 21296, I think this may be relevant.

I have the same Windows Insider version and they showed up for me after disabling the "Hide system files" on v1.1.0.0

**Comment by hez2010** [comment]
My mistake. I just incorrectly activated another toggle "Show all files and folders".
I'm closing this issue.
