### ISSUE TITLE
Path gets cut off - Justify right

### ISSUE THREAD

**Issue by v-aravind** [files-community/Files#3302]
**Describe the bug**
When you navigate to more than 2 or 3 folder levels deep, the path extends beyond the width of the path field. 
In the Windows file explorer, the path is right justified, so the current folder and higher level folders are visible but if the path is too long, the highest level folders are cut off, not the current folder. 
This is a much better way to implement from a usability perspective.

**To Reproduce**
1. Open Files
2. Navigate to 3rd or 4th level folder

![File FR2](https://user-images.githubusercontent.com/69113302/105861711-eab85d80-5fe6-11eb-81b9-20043b32ae0c.png)

**Expected behavior**
The folder path shows the open folder, and higher level folders, justified Right, so the open folder is always visible and the immediate higher level folders are visible, and if the path length exceeds available space, the highest level folders are cut off.

Desktop (please complete the following information):
OS Version: Windows 10 Enterprise 20H2
App version: v1.1[](url)

**Comment by yaichenbaum** [comment]
@v-aravind This issue will be solved when we start using the WinUI breadcrumb control, it's still a work in progress on their end so I can't give an ETA but I am happy to share the link where this control is being planned. https://github.com/microsoft/microsoft-ui-xaml/issues/3326
