### ISSUE TITLE
Gap between title bar and address bar doubles when tabs are enabled

### ISSUE THREAD

**Issue by SOI7** [files-community/Files#3303]
**Describe the bug**
When the app uses the tabs layout, the gap between the address and title bar becomes too tall, and wastes a lot of space. It almost looks like there's another title bar below the actual one

**To Reproduce**
Open the app in Vertical layout, then in Horizontal/Adaptive layout, and compare them

**Expected behavior**
Gap should stay the same across both modes

**Screenshots**
Vertical layout:
![Immagine 2021-01-26 192004](https://user-images.githubusercontent.com/50930970/105887520-1ef24500-600c-11eb-8e42-1456d45c970a.png)
Horizontal/Adaptive layout (aka. with tabs):
![Immagine 2021-01-26 192042](https://user-images.githubusercontent.com/50930970/105887587-36313280-600c-11eb-9a47-80ca1d756f2b.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2
 - App version: v1.1.5.0

**Comment by yaichenbaum** [comment]
@SOI7 This issue should be resolved with #3797.
