### ISSUE TITLE
Ability to drag / reorder pin folders

### ISSUE THREAD

**Issue by Ricky55** [files-community/Files#3306]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by Ricky55** [comment]
Title speaks for its self. Just the ability to drag / reorder pin folders in the side bar

**Comment by yaichenbaum** [comment]
This feature was implemented but is currently blocked by an issue with the WinUI repo, I am linking it here so you can upvote the issue and hopefully increase the priority for Microsoft https://github.com/microsoft/microsoft-ui-xaml/issues/3290.
