### ISSUE TITLE
Shortcuts are not loading correctly

### ISSUE THREAD

**Issue by XPoppyX** [files-community/Files#3310]
When opening the app, the shortcuts are shown with a different arrow icon:

![Captura de pantalla 2021-01-26 230509](https://user-images.githubusercontent.com/61259627/105931980-f463b480-602a-11eb-9251-30f6667d283b.png)

And not only that, when you right click and see its properties, the **"Details"** tab appears instead of **"Shortcut"**, clicking on **"Details"** causes a crash:

![CRASH](https://user-images.githubusercontent.com/61259627/105932232-5e7c5980-602b-11eb-8a2a-2b465eed79ad.gif)

----------------------

**LOG:**

**Folder shortcuts:**

`2021-01-26 22:57:50.8058|ERROR|Files.App|Object reference not set to an instance of an object.|System.NullReferenceException: Object reference not set to an instance of an object.
at Files.Views.PropertiesDetails.Properties_Loaded(Object sender, RoutedEventArgs e)
`

**Application shortcuts:**

`2021-01-26 22:52:28.7296|ERROR|Files.App|Acceso denegado. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))|System.UnauthorizedAccessException: Acceso denegado. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
   at Files.ViewModels.Properties.FileProperties.GetSystemFileProperties()
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()
`

------------------------

Refreshing the directory shows the correct icon and there are no problems with the properties

![gif2](https://user-images.githubusercontent.com/61259627/105932944-70123100-602c-11eb-8ef3-c531b5fb5402.gif)

**Comment by SOI7** [comment]
Shortcuts also open in Win32 Explorer instead of Files now

**Comment by XPoppyX** [comment]
Still happening after #3434

_I already tried deleting the cache_

**Comment by XPoppyX** [comment]
Fixed with #3514
