### ISSUE TITLE
Tab title does not follow the localization settings

### ISSUE THREAD

**Issue by fxzxmicah** [files-community/Files#3313]
**Describe the bug**
The title of the opened folder does not follow the localized folder name set in the desktop.ini file, even if it has been pinned to the sidebar and its localized name has been correctly identified in the sidebar.

**To Reproduce**
1. Go to a sidebar folder
2. Edit desktop.ini file
3. Modify `LocalizedResourceName` entry
4. See that its sidebar name is different from the tab title name

**Expected behavior**
See the localized name of this folder in the tab title.

**Screenshots**
![image](https://user-images.githubusercontent.com/48860358/105957616-76e48680-60b4-11eb-8fcf-2348b2d243e4.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.746
 - App version: v1.1

**Log file**
Nothing useful.

**Comment by gave92** [comment]
Thanks for this feedback. Please see #1226 and #3195 for duplicate issues

**Comment by fxzxmicah** [comment]
OK, Thanks.

**Comment by suvrat29** [comment]
@fxzxmicah Can you please share your desktop.ini contents for the `LocalizedResourceName` entry?

**Comment by fxzxmicah** [comment]
> @fxzxmicah Can you please share your desktop.ini contents for the `LocalizedResourceName` entry?

[desktop.ini.zip](https://github.com/files-community/Files/files/5880024/desktop.ini.zip)
The file is encoded as GB2312 or GBK.

**Comment by yaichenbaum** [comment]
@fxzxmicah This issue should be resolved with #3319.
