### ISSUE TITLE
The sincronization with onedrive doesn't work properly

### ISSUE THREAD

**Issue by ghost** [files-community/Files#3315]
Hi! 
I reopen the issue with more information. In the left side you can see the Files tool with a folder of my one drive. In the right side, you can see the same folder with Windows Exploter. 

Note that the "attachment" folder shows as sincronized in Files but in the cloud in Windows Explorer. 

I think that it's incorrect, isn't it?

Thnx in advance.

![files](https://user-images.githubusercontent.com/68429586/105967462-27876180-6086-11eb-86e7-44063734b1c8.png)

**Comment by d2dyno1** [comment]
The issue should be fixed.
