### ISSUE TITLE
Teracopy in Files UWP

### ISSUE THREAD

**Issue by AbdulRafay517** [files-community/Files#3316]
It would be nice to have teracopy integrated into the app. Thanks.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by yaichenbaum** [comment]
@AbdulRafay517 Thank you for opening this issue. We usually expect users to fill out the issue template when reporting a bug or submitting a feature request, please reopen this issue when you have filled out the issue template.
