### ISSUE TITLE
Pasting to MTP devices does not work

### ISSUE THREAD

**Issue by AbdulRafay517** [files-community/Files#3317]
It would be great to have MTP Support.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by gave92** [comment]
Hello could you add some more details? MTP devices like android phone storage are already supported.

**Comment by AbdulRafay517** [comment]
It is supported but I can't transfer files.

**Comment by gave92** [comment]
@AbdulRafay517 thanks for the info. Don't trust the percentage, also after pasting try refreshing the folder and see if the files were copied. If not please let us know.

**Comment by ezxpro** [comment]
Pasting from MTP devies doesn't work either.

**Comment by Chintan8169** [comment]
I had same problem in my laptop.
Copying files from phone's internal storage to laptop works but if I try to copy files in phone's internal storage from laptop it does not work.
Also do note that in neither of above case it shows percentage of transfer complete. It stuck at 0%.
Also If I try to copy small files like 1 GB and it works but big files does not works.

**Comment by aboalwi** [comment]
I can't copy photos from my android phone to my pc too.. tried USB File Transfer mode and PTP .. tried dragging to desktop copy here and copy pasting.. nothing is copied..

**Comment by Josh-65** [comment]
Merging with #9003
