### ISSUE TITLE
Add detection for Windows Terminal when installed from Scoop

### ISSUE THREAD

**Issue by linsui** [files-community/Files#3318]
**Describe the bug**

**To Reproduce**
1. Install Windows terminal from Scoop
2. Add it into terminal.json
3. Restart files
4. The related block is removed

**Expected behavior**
Windows Terminal installed from Scoop is detected and added to terminal.json

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: Windows 10 2004
 - App version: 1.1

**Additional context**
https://github.com/files-community/Files/blob/34c69f40a06de67e4ff3bfdab51c844ac144dae3/Files/Controllers/TerminalController.cs#L120-L131

**Comment by linsui** [comment]
[windows-terminal](https://github.com/ScoopInstaller/Extras/blob/master/bucket/windows-terminal.json)

**Comment by yaichenbaum** [comment]
@linsui I meant the package name that's displayed when you run `Get-AppxPackage -AllUsers`.

**Comment by linsui** [comment]
It's not installed but simply unpacked, so there is no package name.

**Comment by yaichenbaum** [comment]
@linsui looking at the script, it's using the same package as the store version so it should work now.

**Comment by linsui** [comment]
Scoop uses the same package but doesn't install it. So I doubt if it works. But I don't use scoop anymore so I can't check it.
