### ISSUE TITLE
Crash when opening newly created ("empty") shortcuts

### ISSUE THREAD

**Issue by wond4200** [files-community/Files#3320]
Hello, I have a few questions about your great project "files", but something is missing!
When you right-click and "new", then "create shortcut" is missing!
So when you create a single file for which you put .lnk, nothing happens, but when you "open the file location", the application crashes.
I would love for these bugs to be fixed, but otherwise a nice application!
WONDER GAMING

**Comment by gave92** [comment]
Thanks for the report. For the create new shorcut: feature request tracked in #2833

**Comment by yaichenbaum** [comment]
@wond4200 This issue should be resolved with #3469.
