### ISSUE TITLE
Customisable sidebar for pinned folders

### ISSUE THREAD

**Issue by Tolo789** [files-community/Files#3325]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I try to find a folder among multiples ones that I've pinned on my sidebar, they are all clumped together and they all look the same.

**Describe the solution you'd like**
I'd love to be able to create custom groups in my sidebar, similarly to the already existing "Drives" one. And then being able to freely move one pinned folder from one group to another.
If those groups can be collapsable it would be even better.

**Describe alternatives you've considered**
Adding colors to pinned folders could also improve readability.
Having something similar to a web-browser bookmark bar is a similar alternative.

**Additional context**
The customisable sidebar I'm thinking of is really like Slack's one, which totally boosted how efficiently I can retrieve my pinned items. (screenshot taken from [this article](https://www.theverge.com/2020/3/18/21184865/slack-redesign-update-sidebar-changes-available-now-download))
![image](https://user-images.githubusercontent.com/16037393/106127002-61c43200-615e-11eb-9498-f1ef4c4096f1.png)

**Comment by gave92** [comment]
We're working to improve the sidebar -> see #632. If you're suggestions are not already included there, feel free to add them there.
