### ISSUE TITLE
Live Folder Thumbnails using Folder.* image convention

### ISSUE THREAD

**Issue by AbraamNader** [files-community/Files#3326]
**Is your feature request related to a problem? Please describe.**
- Having all yellow folders look the same can make it harder to identify.
- Customizing each folder with an icon can be a boring mundane task.

**Describe the solution you'd like**
- Reusing windows explorer convention for creating live folder thumbnails when adding an image file named folder (e.g. folder.png or folder.jpg) inside any folder would make it the main folder thumbnail image.
- Adding an overlay to folder icon indicate that it is a folder, not just an image.

This way users migrating from Windows Explorer will feel they did not lose this functionality and would not need to do anything to customize their folders.

**Describe alternatives you've considered**
Just use Windows Explorer, or perhaps if Files could make it easier to choose an image as a folder icon.

**Additional context**
This is the Windows Explorer folder overlay:
![image](https://user-images.githubusercontent.com/899978/106132587-d00ff100-616c-11eb-8beb-9cb78a0584fe.png)

I would suggest something that I think would render faster that looks similar to the shortcut overlay:
![image](https://user-images.githubusercontent.com/899978/106133165-8ffd3e00-616d-11eb-8810-6f90df8aedf8.png)

**Comment by SOI7** [comment]
OneDrive uses this layout for folders with pictures. Perhaps Files could use the same layout

![IMG_20210128_125746](https://user-images.githubusercontent.com/50930970/106135914-d43a0f80-6168-11eb-86be-3efed0ff1836.jpg)

**Comment by CF-71** [comment]
Folder-images could certainly improve the overview.

I use a large number of folders. And in _Files_ you always look at those "big yellow things" that all look the same. The folders are difficult to distinguish and you have to search for a long time to find the folder you want. This also significantly reduces the productivity of daily work.

**Comment by TizianoMad** [comment]
Posted a similar answer [here.](https://github.com/files-community/Files/issues/4301#issuecomment-981260643)
Maybe could be included.

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
