### ISSUE TITLE
non standard right click menu items missing in store 1.1.5

### ISSUE THREAD

**Issue by rubberdecoy** [files-community/Files#3328]
[debug.txt](https://github.com/files-community/Files/files/5888618/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5888619/debug_fulltrust.txt)

**Describe the bug**
When I use 1.1.5 (most recent store version at time of writing) I lose most of the right click menu options that would appear in regular explorer. Rolling back to 1.1.0 from Github and all the menu options re-appear. 

**To Reproduce**
Steps to reproduce the behaviour:
1: Run 1.1.5 (Store)

**Expected behaviour**
Non-standard items in right click menu to appear. 

**Screenshots**
![Actual](https://user-images.githubusercontent.com/1424781/106135818-56720600-6160-11eb-9f2d-0e195a886fcd.JPG)

![Expected](https://user-images.githubusercontent.com/1424781/106135822-570a9c80-6160-11eb-9457-05ee50153efb.JPG)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2 19042.746]
 - App version: [1.1.0 / 1.1.5]

**Additional context**
Reboots / Restarts do not affect this. Only way to get back to expected menu appearance is to roll back to 1.1.0. 

edit: this affects any 3rd party right-click entry, so VLC, WinRAR etc do not show their actions when I right click on .mp4 / .rar etc etc

thx!

edit2: attached logs as requested, but they don't contain much.

**Comment by gave92** [comment]
Hello thanks for the report. Please attach the log files to the issue description.
Do you happen to have uninstalled/disconnected OneDrive?

**Comment by rubberdecoy** [comment]
> Do you happen to have uninstalled/disconnected OneDrive?

Yes I have. I don't use or need OneDrive at all.

**Comment by gave92** [comment]
@rubberdecoy thanks for the info. This is an issue affecting everyone who has uninstalled OneDrive. I can confirm that a fix will be included in the next version.

**Comment by rubberdecoy** [comment]
> I can confirm that a fix will be included in the next version.

Outstanding. Thank you!
