### ISSUE TITLE
Implement search options

### ISSUE THREAD

**Issue by mbeps** [files-community/Files#333]
When searching nothing happens.

**Comment by yaichenbaum** [comment]
Search has not been implemented yet.

**Comment by mbeps** [comment]
Hello, I am looking forward to the app as I am looking for a replacement for the current file explorer. Can you make files an folders open with 1 tap when using touch. You could collaborate with another developer who is currently making a file explorer like yourself. His email is dev.neolyon@gmail.com. You combine both of your apps you can create the perfect file explorer. Thank You. From: Yair AichenbaumSent: 08 December 2019 16:11To: duke7553/files-uwpCc: mbeps; AuthorSubject: Re: [duke7553/files-uwp] Search not working (#333) Search has not been implemented yet.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by yaichenbaum** [comment]
We are tracking this issue here #8. Thank you for contributing to Files UWP.

**Comment by yaichenbaum** [comment]
We are moving the tracking back to this issue, we are sorry if this confused anyone.

**Comment by jaigak** [comment]
@yair100 I'm still working on this and I will reopen the PR soon. Please assign me to this.

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran Are you still working on this issue?

**Comment by jaigak** [comment]
@yair100 Yes I am still working and PR is coming soon.

**Comment by d2dyno1** [comment]
There's an app called Everything it has a nice search engine

**Comment by d2dyno1** [comment]
Real quick and efficient

**Comment by d2dyno1** [comment]
Here are some useful links:

Debate over releasing Everything's source code:
https://www.voidtools.com/forum/viewtopic.php?t=590

Everything's SDK (.dll):
http://support.voidtools.com/everything/SDK

A C# example implementing the Everything's SDK:
http://www.voidtools.com/support/everything/sdk/csharp


@Jaiganeshkumaran @yair100

**Comment by d2dyno1** [comment]
I believe the searching process will be to just pass in the matching files (and folders) from the SDK to the ListViewBrowser Page's constructor

**Comment by d2dyno1** [comment]
I'm able to help if you want @Jaiganeshkumaran

**Comment by jaigak** [comment]
@yair100 Is the search box necessary for the settings page?

**Comment by d2dyno1** [comment]
Probably no, the settings page already covers the entire explorer

**Comment by yair100** [comment]
> @yair100 Is the search box necessary for the settings page?

As we add more settings, it is going to be necessary.

**Comment by yaichenbaum** [comment]
> @yaichenbaum Yes I am still working and PR is coming soon.

Just checking up to see if you are still working on this or if you need any help.

**Comment by d2dyno1** [comment]
I'll try to look into that.
Is it ok if I was to use Everything's SDK?

> There's an app called Everything it has a nice search engine

**Comment by Jaiganeshkumaran** [comment]
@d2dyno1 You can use it but I have discovered some issues with it. First, the user needs to install the right version. Note that the light version will not work. Since it provides separate DLLs for a different architecture, the user also needs to install the appropriate version. Also since it's Win32 based we need to use from the full trust component and pass it to the main executable. Currently, Files uses AppService but it's not really designed for large transfer. I would recommend memory-mapped files as an alternative.

**Comment by d2dyno1** [comment]
> I'll try to look into that.
That turned out to be not so easy thing to do. I'm not sure I'll manage to get it working by myself. I'll need some help from anyone that's interested in working with such a enormous task.

**Comment by d2dyno1** [comment]
> I'll try to look into that.

That turned out to be not so easy thing to do. I'm not sure I'll manage to get it working by myself. I'll need some help from anyone that's interested in working with such a enormous task.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #2446. Further improvements to the search feature are being tracked over here #2447.
