### ISSUE TITLE
Cut and paste doesnt work

### ISSUE THREAD

**Issue by HamidRezaAshkiyan** [files-community/Files#3330]
Most of the times i want to move some file or videos to a new folder. I cut them make a new folder and then paste them there. but nothing works. 

Windows 10 20H2
latest version of app.

**Comment by yaichenbaum** [comment]
@HamidRezaAshkiyan Can you fill out the issue template?

**Comment by HamidRezaAshkiyan** [comment]
I have switched to Ubuntu but I will try to install and test it another time so i can provide more info. 
As long as i remember i had this issue long tine with different versions.
