### ISSUE TITLE
App crashes 

### ISSUE THREAD

**Issue by mbeps** [files-community/Files#3332]
**Describe the bug**
When trying to launch the app it crashes. A notification is sent informing me that something went wrong. This only happens when installing on another account. Documents, photos, videos are all saved on a different drive but the apps are installed on the C drive. 

**To Reproduce**
1. Create a new Windows user
2. Set where documents, music, photos, and videos are saved to D drive
3. Set the account to a normal user and not administrator
4. Install and launch the app

**Expected behavior**
The app should launch normally. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Version 20H2 Build 19042.746
 - App version: [v1.1.0.0]

**Additional context**
The problem does not seem to appear when the account is set to administrator. 

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5890018/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5890019/debug_fulltrust.txt)

**Comment by gave92** [comment]
Could you check if in Windows Settings > Privacy > File system permission is turned on for Files?

**Comment by mbeps** [comment]
@gave92 Yes, it's enabled.

**Comment by yaichenbaum** [comment]
@mbeps Is this still an issue in v1.5?
