### ISSUE TITLE
New office files made by Files open in a protected view

### ISSUE THREAD

**Issue by pklion** [files-community/Files#3333]
**Describe the bug**
When I open new blank office files made by Files, they open in a Protected view.
If I make them by old explorer, they don't open in a Protected view.

**To Reproduce**
1. Make blank office files using Files (e.g. .docx, .xlsx, .pptx)
2. Open it

**Expected behavior**
I would like to do not open new office files made by Files in a protected view.

**Screenshots**
![image](https://user-images.githubusercontent.com/78145811/106206195-0304c400-6203-11eb-9fcb-21f7f2712708.png)

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 20H2 19042.746]
 - App version: [v1.1.0.0]

**Additional context**

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5890308/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5890309/debug_fulltrust.txt)

**Comment by yaichenbaum** [comment]
@gave92 were you able to reproduce this?
