### ISSUE TITLE
Search box should be always expanded on larger display

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#3336]
**Is your feature request related to a problem? Please describe.**
Today you need to click on the search icon to show the search box and it gets hidden afterwards. While this should be the case on smaller displays to save screen space, on larger displays it makes more sense to keep it expanded always.

**Describe the solution you'd like**
The search box will be automatically expanded on larger screens.

**Describe alternatives you've considered**
None

**Comment by yaichenbaum** [comment]
This feature request doesn't fit with our plans for Files, we will have more to share about this soon.
