### ISSUE TITLE
Can't use tab navigation to go outside after focusing the path box

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#3337]
**Describe the bug**
After clicking on the path box to see the full location, I can't get to the next element via the tab key. Esc key works but it wrongly focuses the selection box button instead of the next element after it.

**To Reproduce**
1. Go to a folder
2. Click on the path box
3. Press tab

**Expected behavior**
It should go to the next element like normal

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Pro version 20H2
 - App version: v1.1.5.0

**Comment by yaichenbaum** [comment]
This issue appears to be resolved in `main`.
