### ISSUE TITLE
[Feature] Windows Terminal Preview support

### ISSUE THREAD

**Issue by KristofKekesi** [files-community/Files#3339]
**Describe the solution you'd like**
An option for Windows Terminal Preview in terminal selector.

**Comment by XPoppyX** [comment]
**Did you add this? :**

_{
      "name": "Windows Terminal",
      "path": "wt.exe",
      "arguments": "-d \"{0}\"",
      "icon": ""
}_


I just tested and it works with terminal preview

**Comment by KristofKekesi** [comment]
Oh thanks for the snippet but I don't know C and I have no idea in which file to put that json.
I'm only making translations here.

**Comment by XPoppyX** [comment]
There is an edit button next to the combo box

![Captura de pantalla 2021-01-29 121111](https://user-images.githubusercontent.com/61259627/106292073-2fccd180-622b-11eb-8af4-394afb845cbf.png)

**Comment by KristofKekesi** [comment]
Thanks for the step by step. It launches the normal Windows Terminal not the Preview. And It has a crash like message as well
(```[error 0x8007010b when launching `cmd.exe']```).

Thanks for your time.

**Comment by XPoppyX** [comment]
mm, I guess you should uninstall the normal version if you only want to use the preview version

Strange that it crashes with cmd

**Comment by gave92** [comment]
For terminal preview the exe might be "wtd.exe"

**Comment by KristofKekesi** [comment]
No :( 
![image](https://user-images.githubusercontent.com/64812024/106363403-9f74b680-6328-11eb-9bc3-8c4694c62185.png)
(Could not find the file wtd.exe)

**Comment by yaichenbaum** [comment]
Both Windows Terminal and Windows Terminal Preview use the same app execution alias `wt`. If you would like `wt` to launch the preview version, you should be able to change this under the app execution alias settings page in the Settings app.
