### ISSUE TITLE
Details Pane like Windows Explorer

### ISSUE THREAD

**Issue by ziplock9000** [files-community/Files#3341]
Windows Explorer lets you enable a details pane which will show stats regarding the current object.

This is much quicker than right-clicking and digging intro properties. It also shows a subset of info that is more datatype specific

It's also much better than details view for many reasons.

<img width="556" alt="msedge_enjZgdc9k5" src="https://user-images.githubusercontent.com/5209752/106279979-32342900-6235-11eb-8978-737c5e9d2721.png">

**Comment by XPoppyX** [comment]
Details / preview pane has already been implemented (#2756) and will be available in next update
