### ISSUE TITLE
Feature: Add the ability to close the primary/left panel

### ISSUE THREAD

**Issue by JuanChiogna** [files-community/Files#3342]
**Requirements**
- Add support for closing the left pane

**Comment by gave92** [comment]
See #2941

**Comment by yaichenbaum** [comment]
> See #2941 for a similar request. Adding an option to close the left pane is more complicated as the left pane is the "main pane" and the sidebar is part of it, I'm keeping this open a feature request for this.

@gave92 can we decouple the sidebar from the panes?

**Comment by gave92** [comment]
That statement in not true anymore, Sidebar is now part of MainPage.

**Comment by Josh-65** [comment]
https://files.community/docs/configuring/custom-themes

**Comment by yaichenbaum** [comment]
Yes, but I think it'll be resolved with #10161

@lukeblevins can you confirm?

**Comment by lukeblevins** [comment]
@yair100 Can confirm that's in the works. 👍🏻

**Comment by Wholesomebruh** [comment]
Hey, what's the status?

**Comment by yaira2** [comment]
@Wholesomebruh there isn't a timeline yet.

**Comment by 0x5bfa** [comment]
Now this is feasible by introducing the new sidebar control? @yaira2

**Comment by yaira2** [comment]
We'll need to implement #11955.

**Comment by yaira2** [comment]
We're actively working on the foundation for this feature.

**Comment by yaira2** [comment]
I’m excited to share that this enhancement will be included in the upcoming v3.5 release.
