### ISSUE TITLE
The "Date modified" of all files and folders are showing wrong value.

### ISSUE THREAD

**Issue by RohitBag** [files-community/Files#3345]
**Describe the bug**
The "Date modified" of all files and folders are showing wrong value. My timezone is GMT+5.30

**To Reproduce**
1. Open any folder and create anew file or change any existing file.
**Expected behavior**
Time should correspond default system time.

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1909]
 - App version: [v0.11.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`, you should see a file in this directory called debug.txt or/and debug_fulltrust.txt.

**Comment by yaichenbaum** [comment]
@RohitBag Which version of Files do you have this issue with?

**Comment by XPoppyX** [comment]
After comparing the modification date of several files, I can confirm that they are displayed with a different timezone

**Comment by Ein-Tim** [comment]
I've already reported this in #2917
