### ISSUE TITLE
Drag and Drop in Search mode

### ISSUE THREAD

**Issue by TheUnsleepingAlchemist** [files-community/Files#3348]
**Describe the bug**
Drag & Drop in Search mode not working.

**To Reproduce**
1. Go search for some files.
2. Click on random file.
3. Try to drag or drop file anywhere.

**Expected behavior**
In search mode I expected normal drag and drop behavior.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Pro 1909 18363.1316
 - App version: [v1.1.0.0]

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5842.
