### ISSUE TITLE
Cannot drag/move app from it's tabs section

### ISSUE THREAD

**Issue by glitchcodes** [files-community/Files#3351]
**Describe the bug**
As the title says. Dragging/Moving the app window from its tabs section doesn't do anything. But moving/dragging the app from a little space in app before the file location bar/home works

**To Reproduce**
1. Drag/Move the app from Tab Section/Top side of the app
2. You can't move it

**Expected behavior**
You can move the window

**Screenshots**

https://user-images.githubusercontent.com/56838797/106343715-b217cd00-62e1-11eb-98cd-f178461b1cb3.mp4

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 [19042.746]
 - App version: [v1.2.0.0]

**Additional context**
This problem persists even after restarting the app

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5897176/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5897177/debug_fulltrust.txt)

**Comment by gave92** [comment]
Merging with #3250
