### ISSUE TITLE
Crash at start-up

### ISSUE THREAD

**Issue by Zabijak05** [files-community/Files#3354]
**Describe the bug**
The Files app launches, stays open for 2 seconds without being able to interact with any buttons, and crashes

**To Reproduce**
Start the Files app
Wait
*Crash*

**Expected behavior**
App starts normally

**Screenshots**
N/A

**Desktop (please complete the following information):**
OS Version: Windows 10 Version 2002 Build 21292.1010
App version: [v1.1.0.0]

**Additional context**
I have not been able to start this app since discovering it

Log file
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5897860/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/5897861/debug.txt)

**Comment by gave92** [comment]
@jakoss could you take a look at this? Have we seen this before?

**Comment by jakoss** [comment]
Seems to be a duplicate to https://github.com/files-community/Files/issues/3169.

I'll catch and ignore this error in my next PR. No idea how this is happening

**Comment by gave92** [comment]
Closing this in favor of #3169
