### ISSUE TITLE
Copying big files freezes app

### ISSUE THREAD

**Issue by jmoo2** [files-community/Files#3355]
**Is your feature request related to a problem? Please describe.**
When copying files, especially large ones over 1GB, there is no notication. The app also seems to lock until the file has been copied (from one drive to another). I see there is a noticiation area bottom right but that doesn't seem to display anything.

**Describe the solution you'd like**
I'd like a progress bar. Unlike Windows File Explorer, I would like it built into the app rather than a seperate dialog box. Perhaps down the bottom you can have a small area running the entire width of the app for a progress bar (and even other notifacations)?

**Describe alternatives you've considered**
Another option is to display a dialog box like File Explorer.

**Comment by gave92** [comment]
The progress report for now only works when copying multiple files, not with a single big file (#2543)

**Comment by jmoo2** [comment]
Thanks for the update

**Comment by KAMiKAZOW** [comment]
Dupe of #3136?

**Comment by yaichenbaum** [comment]
@jmoo2 This issue should be resolved with #3573.

**Comment by jmoo2** [comment]
Great!

*James*

**Comment by KAMiKAZOW** [comment]
May I suggest to release v1.2.3 as soon as possible? I consider this fix and  #2944 pretty important.

**Comment by yaichenbaum** [comment]
@KAMiKAZOW v1.2.3 is still in testing, in addition, we are trying to investigate some other crashes before releasing the next update.
