### ISSUE TITLE
Feature: Disable splash screen on UWP

### ISSUE THREAD

**Issue by 0x5bfa** [files-community/Files#3356]
### Summary

Disable splash screen.
Considering that "files", which is an alternative to windows explorer, is the most used app by users, I think it is useless if the startup time is long, so I think it is better to disable the splash screen like windows terminal.

**Comment by gave92** [comment]
Related #2568

**Comment by yaichenbaum** [comment]
> Related #2568
> 
> Splash screen can be made optional but on its own it does not really improve startuptime.
> <uap:SplashScreen ... uap5:Optional="true" />

The splash screen is already set to "optional" but as mentioned by @gave92, it isn't the only factor in startup time. There is an ongoing effort to improve the startup time so you can expect to see these improvements over the next couple of months. We are going to merge this with #2568 to continue the discusion.

**Comment by onein528** [comment]
Oh, sorry....

**Comment by XiiZii** [comment]
I like to take risks
