### ISSUE TITLE
Dragging images from browser saves them incorrectly

### ISSUE THREAD

**Issue by generalguy41** [files-community/Files#3357]
**Describe the bug**
Not sure if this is a UWP limitation or not, but when dragging images from the browser to Files, the image doesn't save as the right name/format.

**To Reproduce**
1. Go to a site with an image you want to save.
2. Drag the image to Files.
3. See that the image is not the right name/format.

**Expected behavior**
Files will save the image properly.

**Screenshots**

https://user-images.githubusercontent.com/8879244/106361182-8fd67d00-62ea-11eb-8db5-519b21803502.mp4

**Desktop (please complete the following information):**
 - OS Version: Windows 10 2004 21301.1000
 - App version: v1.1.0.0

**Additional context**
Right-clicking and saving saves the image fine.

**Comment by gave92** [comment]
+ @winiston-de

**Comment by winston-de** [comment]
I believe this is an issue with Firefox, not with Files, as I cannot reproduce it with Edge. It also looks like this bug affects all apps *except* Windows explorer. I tried dragging an image from Firefox into any other app, and I have the same issue.

I think these are related to your issue:
https://bugzilla.mozilla.org/show_bug.cgi?id=557708
https://bugzilla.mozilla.org/show_bug.cgi?id=1191462

**Comment by generalguy41** [comment]
Fair, it's only a minor annoyance anyway, and there are workarounds. I'll close this.
