### ISSUE TITLE
Support Folder Name Created by Windows Store Application

### ISSUE THREAD

**Issue by ariadevl** [files-community/Files#3359]
**Is your feature request related to a problem? Please describe.**
Folder name supposed to be the name of application installed

**Describe the solution you'd like**
example folder created by 8zip app, view in file explorer
![image](https://user-images.githubusercontent.com/61529802/106371187-578f7700-639c-11eb-83df-10c75ccc1839.png)
view in Files app
![image](https://user-images.githubusercontent.com/61529802/106371192-77269f80-639c-11eb-8616-ebdac618778c.png)

**Additional context**
OS Version: [Windows 10 20H2 19042.685]
App version: [v1.1.0.0]

**Comment by gave92** [comment]
Likely fixed together with #1226

**Comment by yaichenbaum** [comment]
We don't have plans to implement this change.
