### ISSUE TITLE
Python Files report being in C:\WINDOWS\system32

### ISSUE THREAD

**Issue by Simplicitus** [files-community/Files#3360]
**Describe the bug**
Python scripts report having their working directories in `C:\WINDOWS\system32`  even though being somewhere else

**To Reproduce**
1. Go to a random directory and create a python file with content like this:
```
import os

print(os.getcwd())  # prints working directory
```
2. Execute it
3. See that the working directory isn't the one the file is located in, but `C:\WINDOWS\system32`

**Expected behavior**
Show the correct working directory. If it's executed in `C:\Users\User\Desktop` then the directory shouldn't be `C:\WINDOWS\system32`

**Screenshots**
![Screenshot 2021-01-31 015623](https://user-images.githubusercontent.com/50057034/106371691-922aec80-6367-11eb-9aea-13a580eba673.png)

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 20H2 19042.746]
 - App version: [v1.1.0.0]

**Additional context**
The problem doesn't go away, even if I restart my PC or switch to another computer

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState
`, you should see a file in this directory called debug.txt or/and debug_fulltrust.txt.
[debug.txt](https://github.com/files-community/Files/files/5899027/debug.txt)

**Comment by gave92** [comment]
Can't reproduce in Files v2
