### ISSUE TITLE
Start application with Win + E shortcut key.

### ISSUE THREAD

**Issue by BreezyMain** [files-community/Files#3364]
In RX Explorer (another UWP Explorer), I can open it with the Win + E shortcut key, which allows me to use it instead of the system's own Explorer, which is very convenient. I like the UI design and animation of Files very much, but unfortunately there is no shortcut key for Win + E. If this function can be added, I think it will be perfect.

**Comment by BreezyMain** [comment]
I know that the application can be launched through Win + E in other ways, but it will be perfect if it can be built in.

**Comment by gave92** [comment]
@BreezyMain As you may know already you can use [this method](https://files-community.github.io/docs/#/articles/configure-win-e) to open Files on Win E.
Rx-Explorer actually uses the same method (the registry one) but bundles the .reg files within the app.

@yair100 should we consider doing the same? Opening on Win+E should be safe enough (not like fully replacing explorer with Files)

**Comment by yaichenbaum** [comment]
@gave92 I am a little hesitant to build this in, although we provide instructions, it still has some risks involved and I don't think we want to make it an official solution.
