### ISSUE TITLE
Add animation to status center to indicate when an operation is complete

### ISSUE THREAD

**Issue by kimlimjustin** [files-community/Files#3368]
**Is your feature request related to a problem? Please describe.**
There's no animation/notification that pops up when copying files/folders which sometimes makes me confused whether it is done.

**Describe the solution you'd like**
An animation that shows the progress of copying files/folders.

**Describe alternatives you've considered**
A popup notification tells me that it's finished.

**Comment by Ein-Tim** [comment]
Hey @kimlimjustin 

If you copy/paste something you should see a blue point in the "Ongoing Tasks" menu.
The "Ongoing Tasks" menu looks like this:
![image](https://user-images.githubusercontent.com/67682506/106392775-b7653c80-63f3-11eb-8b69-9f1de2d3fdfa.png)  

and can be found in the bottom right corner.

Can you confirm that this menu is there and if you copy something you see the blue point in it?

**Comment by TheXamlGuy** [comment]
> Hey @kimlimjustin
> 
> If you copy/paste something you should see a blue point in the "Ongoing Tasks" menu.
> The "Ongoing Tasks" menu looks like this:
> ![image](https://user-images.githubusercontent.com/67682506/106392775-b7653c80-63f3-11eb-8b69-9f1de2d3fdfa.png)
> 
> and can be found in the bottom right corner.
> 
> Can you confirm that this menu is there and if you copy something you see an animation like this:
> ![image](https://user-images.githubusercontent.com/67682506/106392930-59852480-63f4-11eb-9779-af0eff963f03.png)

An option for the "Ongoing task" menu to pop open automatically may be a good idea, for ease of discovery.

**Comment by kimlimjustin** [comment]
Thanks for your reply, I can see the ongoing task animation right now, but it will be easier if the ongoing task menu pops up automatically as what @TheXamlGuy mentioned.

**Comment by KAMiKAZOW** [comment]
Solution: https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/toast-progress-bar?tabs=builder-syntax

**Comment by TheXamlGuy** [comment]
@KAMiKAZOW Good find!

**Comment by KAMiKAZOW** [comment]
For the ultimate winning move multiple Progress Toasts for multiple file operations and a progress bar behind the taskbar icon for the sum of all progress. That's pretty much exactly how I saw file managers on other systems behave. That's pretty great because for exact progress you can look at the toast (and collapse it into the notification area when you don't care about details) and just look at the taskbar icon when a rough estimate is enough.

**Comment by yaichenbaum** [comment]
@kimlimjustin This issue should be resolved in v1.5.
