### ISSUE TITLE
Show additional terminal options in sub menu when holding down shift key

### ISSUE THREAD

**Issue by Nisgrak** [files-community/Files#3370]
### Is your feature request related to a problem? Please describe.

I have multiple terminal profiles and I must remember the name and write in navbar.

### Describe the solution you'd like

* The "Open in Terminal" is a button with an optional list, if I click it go to default profile, if I hover it's showed a list to select between all profiles
 * Show all profiles in "Open in Terminal" button that always shows a list
![image](https://user-images.githubusercontent.com/19597708/106394372-99500a00-63fc-11eb-81e6-9bb16ef6e20c.png)

### Describe alternatives you've considered

Write the profile name in the navbar

### Files version

2.3.12.0

### Windows version

10.0.19043.2006

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
Based on some polls and feedback we've been gathering, the custom terminal feature isn't used very often. I think we should gather some more feedback before making further changes to the feature.
