### ISSUE TITLE
Scrolling stutters/jumps in v1.2

### ISSUE THREAD

**Issue by eamodio** [files-community/Files#3371]
**Describe the bug**
Scrolling seems worse than in 1.1 -- even in a directory that only has a handful of folders and files. It kind of seems to get stuck at certain points when scrolling and then continues (or jumps). After a restart (well actually a crash where the window just disappeared which I will file in a separate bug), things are better, but still stuttery/jumpy. 

From watching how it stutters/jumps, it is somewhat related to showing the highlighted item under the mouse, or at least it seems worse when that happens. Although it still seems to happen without that happening, but its far less stuttery.

**To Reproduce**
1. Open a folder with like 20-50 folders or files
2. Scroll with the mouse wheel -- note, I am using a Logitech MX Master 3 mouse with a very fast wheel, so you might need to scroll quite quickly.

**Expected behavior**
Smooth scrolling

**Desktop (please complete the following information):**
 - OS Version: [10.0.19042 Build 19042]
 - App version: [v1.2.0.0]

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5900628/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5900629/debug_fulltrust.txt)

**Comment by yaichenbaum** [comment]
@eamodio Is this also an issue in the grid layout modes or is it only in the details layout?

**Comment by eamodio** [comment]
Grid mode seems very snappy.

**Comment by yaichenbaum** [comment]
> Grid mode seems very snappy. Same with Tiles. Only Details seems slow.

This looks like it might be an issue with the DataGrid control, the good news is that Microsoft is working on a new DataGrid control. I am linking the issue here so you can add your feedback regarding scrolling https://github.com/microsoft/microsoft-ui-xaml/issues/1500.

**Comment by eamodio** [comment]
Did something change though that could have impacted things negatively between 1.1 and 1.2? Because I don't remember experiencing this with 1.1

**Comment by yaichenbaum** [comment]
@hez2010 Do you know if you changes would have made an impact here?

**Comment by makcim392** [comment]
Hi, when using a high refresh rate monitor (165Hz, I'm using an HP Omen 27") there's a lot of jittering. I happen to have another 60hz screen and it's working fine. I suspect the stuttering it's due to the higher refresh rate. 

Hope I've been helpful.

**Comment by generalguy41** [comment]
Not sure if it will help, but I did some testing as well. Done on a Gigabyte M27Q 170Hz monitor with an MX Master using the fast scrolling. App version 1.2.0.0, Windows 10 Pro Insider Preview 2004 21301.1000. 

Seems to me there is very minor stuttering when scrolling normally. The only more significant stuttering I see is when you are actively moving the cursor up and down while scrolling (as seen in the later half of the video). I don't think it's a big deal personally, but it might be different on others computers so it may still be worth looking into.

https://user-images.githubusercontent.com/8879244/106399467-c0034600-63e6-11eb-81e9-9661f24509f8.mp4

**Comment by hez2010** [comment]
> @hez2010 Do you know if your changes would have made an impact here?

The only thing in my changes would impact here is the semaphore while acquiring enumerator in `BulkConcurrentObservableCollection` which introduced by #3290:
https://github.com/files-community/Files/blob/1f872f745f7e53340e9772294495c28ecfb6a4b8/Files/Helpers/BulkConcurrentObservableCollection.cs#L195

But I don't think this would result in too much scrolling stutters.

**Comment by hez2010** [comment]
@yair100  I've sent a fix in PR #3386

**Comment by eamodio** [comment]
I also am seeing that using the arrow keys to scroll the view, is VERY slow and stuttery too.
