### ISSUE TITLE
I find it hard to know which Tab or UI element is active/selected

### ISSUE THREAD

**Issue by eamodio** [files-community/Files#3374]
**Describe the bug**

I find it hard to tell which of these tabs is the active one. And with only 2 tabs I find it MUCH harder.

![image](https://user-images.githubusercontent.com/641685/106398162-53d11400-63df-11eb-9c99-e3845397429c.png)
![image](https://user-images.githubusercontent.com/641685/106398201-7400d300-63df-11eb-937c-2c8d5ae29e09.png)

In that 2nd image, I really think the first tab is the active one, but it's the 2nd.

I also find it hard to tell which one of these items is currently selected

![image](https://user-images.githubusercontent.com/641685/106398138-1d939480-63df-11eb-92a1-aef86af38439.png)

**Expected behavior**
Make the active/selected state clearer.

**Desktop (please complete the following information):**
- OS Version: [10.0.19042 Build 19042]
- App version: [v1.2.0.0]

**Comment by yaichenbaum** [comment]
@eamodio The second issue seems to be because of the accent color you are using, other than changing the color to something else, do you have any ideas how we can improve this behavior?

**Comment by eamodio** [comment]
Maybe a border?

**Comment by yaichenbaum** [comment]
> Maybe a border?

Wouldn't a border have the same issue if the accent color matches the button backgroun?

**Comment by eamodio** [comment]
Yeah, the border would have to be some color calculated from the accent color -- to be either brighter or darker (or more saturated, etc) depending on the theme.

**Comment by XPoppyX** [comment]
What about something like this? _(Without acrylic effect)_



![Captura de pantalla 2021-01-31 183951](https://user-images.githubusercontent.com/61259627/106399487-a8808900-63f7-11eb-80f8-d52424983f34.png)

**Comment by R3voA3** [comment]
![image](https://user-images.githubusercontent.com/17484252/106403006-b1d81880-642c-11eb-875b-4757e63b39e5.png)
This is how Mail app does it. Maybe apply accent color to the font?

**Comment by SOI7** [comment]
![image](https://user-images.githubusercontent.com/50930970/106466257-6577f180-649b-11eb-87e0-0d7113627b52.png)

@XPoppyX I'm in love with this layout, seriously. It should absolutely make its way into the app

**Comment by osieltorres** [comment]
I agree @XPoppyX, but like @R3voA3 says, think would be also better if font also could reflect the focus on the selected tab.

**Comment by XPoppyX** [comment]
Is the outline a final solution or is it a "first step" to do something else?

Now it's even harder to identify the focused tab

![Captura de pantalla 2021-02-02 161613](https://user-images.githubusercontent.com/61259627/106650819-1ea8fb00-6572-11eb-8aed-7d4c903e5cf4.png)

_the right one is the focused tab_

**Comment by h38d7v** [comment]
I notice that edge has the active tab in the lighter colour. Perhaps this is also leading to some confusion with the files approach. I would also suggest only showing the full borders when the tab is in a hovered state. Refer to image below for comparison. Personally I have always preferred the active tab having a connection to the window (again, like in edge). 

![image](https://user-images.githubusercontent.com/78543179/106894218-54c3b780-66f7-11eb-9f72-90e28e16ac0b.png)

**Comment by SOI7** [comment]
> I notice that edge has the active tab in the lighter colour. Perhaps this is also leading to some confusion with the files approach. I would also suggest only showing the full borders when the tab is in a hovered state. Refer to image below for comparison. Personally I have always preferred the active tab having a connection to the window (again, like in edge).
> 
> ![image](https://user-images.githubusercontent.com/78543179/106894218-54c3b780-66f7-11eb-9f72-90e28e16ac0b.png)

The problem is that new Edge doesn't have an acrylic title bar, so they can use the lighter color without issues, unlike Files. That's why I approve xPoppyx's idea of using the accent color. Tbh the accent color's adoption in the app is quite scarse atm, so the more the better to me

**Comment by yaichenbaum** [comment]
> > I notice that edge has the active tab in the lighter colour. Perhaps this is also leading to some confusion with the files approach. I would also suggest only showing the full borders when the tab is in a hovered state. Refer to image below for comparison. Personally I have always preferred the active tab having a connection to the window (again, like in edge).
> > ![image](https://user-images.githubusercontent.com/78543179/106894218-54c3b780-66f7-11eb-9f72-90e28e16ac0b.png)
> 
> The problem is that new Edge doesn't have an acrylic title bar, so they can use the lighter color without issues, unlike Files. That's why I approve xPoppyx's idea of using the accent color. Tbh the accent color's adoption in the app is quite scarse atm, so the more the better to me

I don't think acrylic will be an issue once #3184 is done.

**Comment by yaichenbaum** [comment]
![image](https://user-images.githubusercontent.com/39923744/109752119-d0f1d380-7bad-11eb-9061-846fb84f607d.png)

Our recent changes to the tab design seems to solve this issue. By removing the background and border on unselected tabs, it makes the selected tab stand out a little more. Does anyone have feedback on this solution?

**Comment by h38d7v** [comment]
Definitely an improvement. It would be good to see the dark mode also. 

I still think however that there is a slight issue with the colour gradation. The main container window is too similar in colour to the inactive tab. The colour of the main container should be closer to the active rather than inactive tab I would suggest. I understand this may cause issues with address bar.

**Comment by SOI7** [comment]
> ![image](https://user-images.githubusercontent.com/39923744/109752119-d0f1d380-7bad-11eb-9061-846fb84f607d.png)
> 
> Our recent changes to the tab design seem to solve this issue. By removing the background and border on unselected tabs, it makes the selected tab stand out a little more. We also made the font bold on the selected tab to better indicate that it's the selected tab. Does anyone have feedback on this solution?

I think it already solves the majority of the current issues, the different shades of white help a lot. My only feedback is that the active tab could still use the accent color somehow, like the text or the icon

**Comment by generalguy41** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/39923744/109752119-d0f1d380-7bad-11eb-9061-846fb84f607d.png)
> 
> Our recent changes to the tab design seem to solve this issue. By removing the background and border on unselected tabs, it makes the selected tab stand out a little more. We also made the font bold on the selected tab to better indicate that it's the selected tab. Does anyone have feedback on this solution?

I like it, it definitely helps, though I'm curious how it looks with multiple unselected tabs. Is it easy to differentiate between each? I get that there's probably a hover effect, just would be good to see how it looks. I also agree that there should be an accent colour somewhere.

On an aside, does that Ubuntu icon mean coloured icons are possible/coming to the sidebar? 👀

**Comment by R3voA3** [comment]
The new changes look good although I'd still prefer this.

![image](https://user-images.githubusercontent.com/17484252/109816731-58345b00-7c31-11eb-893a-0d556cdc090c.png)

**Comment by yaichenbaum** [comment]
> I think it already solves the majority of the current issues, the different shades of white help a lot. My only feedback is that the active tab could still use the accent color somehow, like the text or the icon

@SOI7 @generalguy41 We haven't finalized anything yet, but we are looking at using colored icons in a couple of different places.
