### ISSUE TITLE
The Arabian message is shown when I set language to Japanese

### ISSUE THREAD

**Issue by pklion** [files-community/Files#3375]
**Describe the bug**
The Arabian message is shown when I set language to Japanese, as following screenshots.

**To Reproduce**
1. Change language to Japanese.
2. Go to setting.

**Expected behavior**
Please show the Japanese message instead of the Arabian message.

**Screenshots**
![image](https://user-images.githubusercontent.com/78145811/106399129-270e1280-645a-11eb-9ff4-7e200ab271bd.png)

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 20H2 19042.746]
 - App version: [v1.2.0.0]

**Additional context**

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5900762/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5900764/debug_fulltrust.txt)

**Comment by XPoppyX** [comment]
I checked and those strings are not translated into Japanese, that's why they are shown in another language.

However, they should be shown in the original language (English) in these cases.

**Comment by R3voA3** [comment]
Guess because many changes were done by an Arabic contributor in version 1.2.0.0? German localisation is almost done except a few new keys and they are Arabic too.

**Comment by XPoppyX** [comment]
@pklion I guess this no longer happens after #4171 and #4131

**Comment by pklion** [comment]
@XPoppyX Yes. Thank you!
