### ISSUE TITLE
Tab's name becomes like "DOWNLO~1"

### ISSUE THREAD

**Issue by pklion** [files-community/Files#3377]
**Describe the bug**
When I open folders using Files from other applications(e.g.Chrome), the tab's name becomes like "DOWNLO~1."

**To Reproduce**
Example of open Files from Chrome.
1. Open Chrome
2. Download something.
3. Right-click on it and open the folder. 

**Expected behavior**
Please show the full name of the folder.

**Screenshots**
![image](https://user-images.githubusercontent.com/78145811/106400078-a225f780-645f-11eb-92df-8273ecdef01f.png)

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 20H2 19042.746]
 - App version: [v1.2.0.0]

**Additional context**

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5900762/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5900764/debug_fulltrust.txt)

**Comment by Josh-65** [comment]
Hasnt this been fixed
