### ISSUE TITLE
v1.2.0.0 Performance is incredible bad. Almost unusable.

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#3380]
The performance seems to have become worse with the recent update, even though the changelog suggests otherwise. Opening a folder with a few items takes 1-2 seconds, the search is incredible slow, and overall the current experience is very "laggy".

[debug_fulltrust.txt](https://github.com/files-community/Files/files/5901098/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/5901099/debug.txt)

**Comment by yaichenbaum** [comment]
@R3voA3 Do you have the setting to cache items turned on?

**Comment by R3voA3** [comment]
Yes, I tried with it and without. Seems to make no noticeable difference @yair100

**Comment by yaichenbaum** [comment]
@R3voA3 It's possible that this is because we changed how the cache system works, can you try resetting Files? Alternatively, you can try deleting this file `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalCache\cache.db`.

**Comment by R3voA3** [comment]
I did both and it seems to be a bit faster, but I still get a 1+ second delay when opening a folder.

**Comment by yaichenbaum** [comment]
@R3voA3 That's expected, there is an ongoing effort to improve this behavior. Do you at least notice an improvement over v1.1?

**Comment by R3voA3** [comment]
Can't really tell since I don't have both versions side by side. So probably not really =(

**Comment by perplexityjeff** [comment]
I do notice a big difference between versions however I hope that the ongoing effort to improve it further will continue as things do still seem a bit weird at times. 

Where I do notice lag is when navigating quickly out of a directory A in to another directory B when things in the directory A seem to not have finished loading yet. It lags probably to stop a process? of loading directory A and moves into directory B.

**Comment by yaichenbaum** [comment]
@R3voA3 Thanks for the information, closing this issue since it was resolved with clearing the cache.

@perplexityjeff There is an ongoing effort to improve this area, thank you for your feedback.
