### ISSUE TITLE
Small icons next to folder appear blurred with Grid View (large)

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#3382]
Small icons next to folder appear blurred with Grid View (large).

![image](https://user-images.githubusercontent.com/17484252/106403127-43e02100-642d-11eb-91ce-faacbe42975f.png)

Perhaps https://github.com/microsoft/fluentui-system-icons ?

**Comment by yaichenbaum** [comment]
@R3voA3 The fluent icon is already used, @gave92 should be able to confirm, but I think this icon is used as fallback.

**Comment by R3voA3** [comment]
Any update on this? For me, no fluent icons are showing next to the folders.

**Comment by yaichenbaum** [comment]
@R3voA3 is this still an issue in the preview version? https://files.community/download/preview

**Comment by R3voA3** [comment]
![image](https://user-images.githubusercontent.com/17484252/168492232-f2d88066-bfbb-4795-b01b-f22291a297bc.png)

It still is.

**Comment by R3voA3** [comment]
![image](https://user-images.githubusercontent.com/17484252/168492253-5e5e9318-358c-4cbc-9c46-7010cdb1a285.png)

It still is.

**Comment by yaichenbaum** [comment]
What kind of folder is this?
