### ISSUE TITLE
Remember prior sort order for column

### ISSUE THREAD

**Issue by Talisman39ar** [files-community/Files#3383]
**Is your feature request related to a problem? Please describe.**
I *love* that I can now co-mingle files and folders when sorting alphabetically (I missed this from my Mac days). However I have a request for how sort order is handled when switching between columns. For example:
1. Open a folder
2. Defaults to Name column from lowest to highest (A->Z). Fine if I haven't specified otherwise
2. Decide I want to view most recent file, switch to sorting by Date Modified. This defaults to oldest->newest for some reason, so I hit it again to reverse the order (when do I ever want to see the oldest file? 99% of the time I want the latest)
3. Switch back to Name column, it's still on A->Z
4. Switch back to Date Modified, and it's returned to default of oldest->newest. I have to hit it again to put it back to where I left it a few seconds ago.
5. Double click a folder to view its contents. Even though previous folder had been sorted by Date Modified, the one I opened is now sorted by Name....

**Describe the solution you'd like**

1. Columns remember what their last manually-set sort order was (low to high or high to low) and revert to that when selected.
2. Which column, and the direction its sorting in, stays consistent as one navigates folder structure within a Files window.

(Files does remember which column and sort order are being used once I've manually set them for a specific directory, even after returning to it after closing the session - that's great. What I'm talking about here is how sort order behaves when switching between columns)

**Additional context**
Part 2 above (staying consistent at which column is used for sorting) is not how Windows Explorer works - it will default to Name sort unless user selects another column (that is then remembered and honored). In my experience, if I'm date sorting then it's usually because I'm looking for the latest thing, and it's helpful to have that date sort stay consistent as I'm drilling through folders looking for the thing I want, as if it's a recent file then the folder it's in will also be recently updated. At the very least I find it distracting to have to figure out what the sort order is each time I go into a new folder, rather than it just staying the same.
You can run into a conflict between staying consistent when drilling down into a folder structure, and then hitting a folder where user had previously set a manual sort order for that specific folder. In that case it's probably best to honor the manually set one (it's being a few years since I've used a Mac, but IIRC that's how MacOS handles it)

**Comment by yaichenbaum** [comment]
This issue should be resolved in main.
