### ISSUE TITLE
Files 1.2.0.0 can't start

### ISSUE THREAD

**Issue by ManFridayy** [files-community/Files#3384]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState
[debug.txt](https://github.com/files-community/Files/files/5901589/debug.txt)
`, you should see a file in this directory called debug.txt or/and debug_fulltrust.txt.

**Comment by yaichenbaum** [comment]
@ManFridayy Can you please upload the log files?

**Comment by rusti4** [comment]
@yair100 

I too am having this issue. App store just updated it. Opens, then hangs and then crashes.

[debug.txt](https://github.com/files-community/Files/files/5901716/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5901717/debug_fulltrust.txt)

Edition:	       Windows 10 Pro
Version:	       20H2
OS build:	       19042.782
Experience:       Windows Feature Experience Pack 120.2212.2020.0

**Comment by yaichenbaum** [comment]
@ManFridayy We need a little more information from you in order to investigate this issue, please reopen this issue once you have filled out the issue template.

**Comment by yaichenbaum** [comment]
@rusti4 We are testing a new version that may fix this issue, please let us know if you still have this issue after we release v1.3.
