### ISSUE TITLE
German translation uses wrong (non-english) fallback

### ISSUE THREAD

**Issue by tgrelka** [files-community/Files#3385]
**Describe the bug**
When using Files with German translation, some strings have the wrong translation fallback (and even are left to right!) - I don’t know what language, but definitely not English.
When setting Files to English manually, everything works fine.

**To Reproduce**
1. Have Windows language be German.
2. Open Files with language setting set to “windows default”.
3. See wrong fallbacks for translation.

**Expected behavior**
Either German translation or English fallback.

**Screenshots**
![image](https://user-images.githubusercontent.com/22134144/106420677-69841f00-645b-11eb-9ba8-be44fd1a1bc7.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.746
 - App version: 1.2.0.0

**Comment by PkLion** [comment]
Maybe this is the same problem as #3375.

**Comment by R3voA3** [comment]
These strings are not translated into English yet. Only language available is Arabic.

**Comment by tgrelka** [comment]
> These strings are not translated into English yet. Only language available is Arabic.

That’s not true - when setting Files to use English instead of system default, all those strings are English.
I’ve also seen some of these strings in German before, I’m pretty sure.

![image](https://user-images.githubusercontent.com/22134144/106562056-09a87980-652a-11eb-815a-5bf251e558ef.png)
![image](https://user-images.githubusercontent.com/22134144/106562082-12994b00-652a-11eb-8a9f-aeee2f6f8721.png)
![image](https://user-images.githubusercontent.com/22134144/106562105-1b8a1c80-652a-11eb-9439-bb0a3f301650.png)

**Comment by LoganTann** [comment]
> > These strings are not translated into English yet. Only language available is Arabic.
> 
> That’s not true - when setting Files to use English instead of system default, all those strings are English.
> I’ve also seen some of these strings in German before, I’m pretty sure.

This bug also occurs for me, but I think it have been fixed with #3361
[*Files.de-DE.xlf* Line 2063](https://github.com/files-community/Files/blob/main/Files/MultilingualResources/Files.de-DE.xlf#L2063)

so we just need to wait for the changes to takes effects in a future build.

**Comment by carlosvsilva** [comment]
It's happening here using the Portuguese language as well, I would expect the fallback language to be english, not arabic. Thanks

**Comment by yaichenbaum** [comment]
@tgrelka Do you want to update the German translation?

**Comment by tgrelka** [comment]
@yair100 Sure, I can help!
Would you mind pointing me in the right direction?

**Comment by yaichenbaum** [comment]
@tgrelka Thank you! You can find instructions here https://files-community.github.io/docs/#/articles/translating-files.

**Comment by tgrelka** [comment]
@yair100 Ah! I was hoping I could simply edit localization files. I only use Files on my work machines running windows, everywehre else I’m using Linux and have no Visual Studio available.

**Comment by yaichenbaum** [comment]
@tgrelka You can edit the `xlf` file in any text editor, just make sure you adjust the [state](https://files-community.github.io/docs/#/articles/translating-files?id=different-states) when you translate a string.

**Comment by R3voA3** [comment]
How is this an issue with the translations? I made sure to update them all and it works for me 1.4.1.0

Edit: @yair100 I've just noticed tgrelka is using version 1.2.0.0. This version had the issue with the wrong language being used as fallback but it should not be the case for 1.3.0

**Comment by yaichenbaum** [comment]
@R3voA3 That might be the case, thanks for clearing it up!

**Comment by tgrelka** [comment]
@R3voA3 @yair100 When I reported the issue, 1.2.0.0 was the latest version. I had seen correct localization before, thus the original issue title and description „...uses wrong (non-english) fallback“.

**Comment by tgrelka** [comment]
I believe this is fixed now. I only found one string not localized to German, that one was in English in 1.3.0.0.
Closing.
