### ISSUE TITLE
JSON/cs/java files not properly scrollable in preview pane

### ISSUE THREAD

**Issue by benschlegel** [files-community/Files#3388]
**Describe the bug**

**To Reproduce**
1. Go to any folder with a JSON/cs/java file in it that have content longer than the default preview pane so you have to scroll (this potentially involves other file types too)
2. Click on the preview pane icon if its not already enabled
3. Unlike with html/md/text and other files, you are not able to scroll the content, unless you focus the scrollbar

**Expected behavior**
Be able to scroll anywhere in the preview pane

**Desktop (please complete the following information):**
 - OS Version: Windows 10 19042
 - App version: 1.2.0.0

**Additional context**
This also happens if you resize the pane or restart or go to different folders.

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5903117/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5903124/debug_fulltrust.txt)

**Comment by yaichenbaum** [comment]
@benschlegel This issue should be resolved with #3404.
