### ISSUE TITLE
Files freezes/crashes when enabling preview on big files (.reg)

### ISSUE THREAD

**Issue by benschlegel** [files-community/Files#3389]
**Describe the bug**
Files freezes indefinitely until you restart and sometimes crashes when enabling preview pane on big .reg files (tested with 2 ~270mb .reg files)

**To Reproduce**
1. Start Files
2. Navigate to folder containing big .reg file
3. Click on big .reg file
4. Enable preview

**Expected behavior**
No crash and proper preview like with smaller files

**Screenshots**
Preview when clicking on big .reg file:
![image](https://user-images.githubusercontent.com/31989404/106442651-d0193500-647b-11eb-8ff5-b60e7e8a754a.png)

Preview with smaller .reg files:
![image](https://user-images.githubusercontent.com/31989404/106443271-95fc6300-647c-11eb-9fbb-d659b3d13b2a.png)

**Desktop**
 - OS Version: Windows 10 19042
 - App version: 1.2.0.0

**Additional context**
The animations when hovering over items etc still works, however you are unable to click anything. Interestingly it once didnt crash by first enabling preview pane and then clicking on .reg file

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5903174/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5903175/debug_fulltrust.txt)

**Comment by winston-de** [comment]
The problem is that it's trying loading the entire contents of the file at once, which jams the UI thread. Anyway, #3349 adds a file size cap, which fixes this issue.
