### ISSUE TITLE
Remember preview pane state when restarting Files

### ISSUE THREAD

**Issue by benschlegel** [files-community/Files#3391]
**Is your feature request related to a problem? Please describe.**
Having to manually enable preview pane every time i start files.

**Describe the solution you'd like**
A toggle in settings ("on startup") that allows you to switch on and off preview pane by default.

**Describe alternatives you've considered**
Manually opening up preview pane every time i start files.

**Additional context**
Im using app version 1.2.0.0, i dont think screenshots make sense as the request is fairly straight forward.

**Comment by yaichenbaum** [comment]
@benschlegel This issue should be resolved with #3914.
