### ISSUE TITLE
Preview pane doesnt keep size if navigated to different folder

### ISSUE THREAD

**Issue by benschlegel** [files-community/Files#3392]
**Describe the bug**
If you adjusted the size of the preview pane and navigate to a different folder or close and open it, the size resets to default.

**To Reproduce**
1. Enable preview pane
2. Resize preview pane
3. Navigate to different folder or close and open preview pane
4. Preview pane has default size again

**Expected behavior**
Preview Pane keeping same size after navigating to different folder or closing and opening preview pane.

**Screenshots**
Before:
![image](https://user-images.githubusercontent.com/31989404/106444906-a9103280-647e-11eb-91c6-6141a893dab6.png)

After reopening or navigating to different folder:
![image](https://user-images.githubusercontent.com/31989404/106445095-e5dc2980-647e-11eb-9b97-6be48ab016c9.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 19042
 - App version: 1.2.0.0

**Additional context**
Also happens when you restart

**Log file**
This doesnt really make sense as it doesnt crash but here you go anyway
[debug.txt](https://github.com/files-community/Files/files/5903287/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5903288/debug_fulltrust.txt)

**Comment by winston-de** [comment]
This bug was fixed with #3349#3282
