### ISSUE TITLE
Turkish language has so many Arabic text

### ISSUE THREAD

**Issue by burakdede2001** [files-community/Files#3394]
**Describe the bug**
App settings are %70 Arabic and %30 Turkish while using Turkish language.

**To Reproduce**
1. Go to Settings
2. Set language to Turkish
3. Settings will be Arabic mostly

**Expected behavior**
Turkish language should make the app Turkish

**Screenshots**
![Ekran görüntüsü 2021-02-01 145517](https://user-images.githubusercontent.com/29973158/106455670-90634500-649d-11eb-9811-8df09fab1849.jpg)
![image](https://user-images.githubusercontent.com/29973158/106456086-1d0e0300-649e-11eb-8f2b-fbef4877ab24.png)
![image](https://user-images.githubusercontent.com/29973158/106456122-25fed480-649e-11eb-868f-b9d549d43d8d.png)
![image](https://user-images.githubusercontent.com/29973158/106456147-2d25e280-649e-11eb-90c5-4d7372fa644c.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Education 20H2 19042.746
 - App version: 1.2.0.0

**Additional context**
It happens while it's set to Windows default (which is Turkish in my case) or Turkish in settings.

**Comment by gave92** [comment]
Merging with #3385
