### ISSUE TITLE
"Item already exists..." - which item?

### ISSUE THREAD

**Issue by oOII-J4HN-IIOo** [files-community/Files#3395]
**Is your feature request related to a problem? Please describe.**
**When copying more than one file from one location to another, if there is a duplicate, Files will display the message:
"Item already exists. An item with this name already exists in this directory".

**Describe the solution you'd like**
**It would be helpful to know which files exactly require attention before pasting to the new location (especially if there are hundreds of folders/files being transferred!).** 
**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by vsopko** [comment]
Also it would be great to edit new file name while copiyng instead of finding later what name the programm gives to the file copy. Like in Directory Opus:
![image](https://user-images.githubusercontent.com/15255277/106463090-ff459b80-64a7-11eb-9959-890add739d0d.png)

**Comment by rusti4** [comment]
This is the issue I had in my ticket #3283

**Comment by yaichenbaum** [comment]
@oOII-J4HN-IIOo This issue should be resolved with #4411.
