### ISSUE TITLE
crash after renaming pdf

### ISSUE THREAD

**Issue by fakepasta** [files-community/Files#3396]
application crashed after I renamed a pdf 
entered new name of pdf --> pressed TAB to switch to the next pdf and thus confirming the change in the first pdf --> name of second pdf was editable --> then Files application crashed

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`, you should see a file in this directory called debug.txt or/and debug_fulltrust.txt.

**Comment by gave92** [comment]
Thanks for the report. Please also post the app log files so we can better diagnose the issue.

**Comment by gave92** [comment]
Merging with #3205. Please post the log files anyway
