### ISSUE TITLE
Copy/Paste/Move multiple files

### ISSUE THREAD

**Issue by vsopko** [files-community/Files#3397]
1. Copy/paste multiple files dialog must have checkbox "Replace all" to replace all existing files instead of selecting "Replace" button on each one. Replacing a lot of files without this becomes very long.
2. Copy/paste multiple files with drag drop must have an option to move files, not just copy (drag with +shift or +ctrl)
3. Replace files dialog must show source and target files comparision on file size and create/modified dates

**Comment by crashmit** [comment]
The second point is standard in win32, I really miss it.
