### ISSUE TITLE
Version 1.2.0.0 translation bug

### ISSUE THREAD

**Issue by lmms500** [files-community/Files#3399]
**Describe the bug**
After updating to version 1.2.0.0, the translation failed in some parts of the application (the screenshots show more details), I use my system in Portuguese, I don't know if this error is only in my language.

**Screenshots**
![Screenshot bug 2 png](https://user-images.githubusercontent.com/78367179/106484928-dbc22700-648e-11eb-80e8-a67b4f994341.png)
![Screenshot bug 3 png](https://user-images.githubusercontent.com/78367179/106484933-dc5abd80-648e-11eb-91c6-9042cf89b2a4.png)
![Screenshot bug 4 png](https://user-images.githubusercontent.com/78367179/106484934-dc5abd80-648e-11eb-97ea-09f5279702e7.png)
![Screenshot bug 5 png](https://user-images.githubusercontent.com/78367179/106484938-dcf35400-648e-11eb-869b-3e7d9485a6ec.png)
![Screenshot bug 6 png](https://user-images.githubusercontent.com/78367179/106484940-dcf35400-648e-11eb-9341-bfc677e4c350.png)
![Screenshot bug 7 png](https://user-images.githubusercontent.com/78367179/106484946-dd8bea80-648e-11eb-83b6-2bf1e3b4b8d7.png)
![Screenshot bug 8 png](https://user-images.githubusercontent.com/78367179/106484947-de248100-648e-11eb-8f3f-3e7f00eebf92.png)
![Screenshot bug png](https://user-images.githubusercontent.com/78367179/106484949-de248100-648e-11eb-9776-a8b55dc985a2.png)

**Desktop**
 - OS Version: [e.g. Windows 10 20H2 19042.782]
 - App version: [v1.2.0.0]

**Additional context**
The problem happened after the 1.2.0.0 update

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5904952/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5904953/debug_fulltrust.txt)

**Comment by XPoppyX** [comment]
It's because those are not translated into Portuguese.
As I said in another issue, they should be shown in English in these cases

**Comment by gave92** [comment]
Merging with #3385. Happens with any language with incomplete translation. The fallback language really should be English.
