### ISSUE TITLE
Preview pane for folders

### ISSUE THREAD

**Issue by KristofKekesi** [files-community/Files#3400]
**Describe the solution you'd like**
Some additional informations about the folder (like how much sotrage does it take, how much files does it contain, or how much files with x file extension).

**Comment by yaichenbaum** [comment]
@KristofKekesi This enhancement was implemented with #3639.

**Comment by winston-de** [comment]
Unfortunately, Folder previews were not finished in #3639, and were disabled.

I made a new PR where I will continue work on implementing this, #3773.

Also, here's what folder previews look like so far. 
![image](https://user-images.githubusercontent.com/59544401/109431243-5ad94b00-79ba-11eb-9627-e6a1a804d240.png)
