### ISSUE TITLE
Navigation Pane Dropdown (Like in original file explorer)

### ISSUE THREAD

**Issue by dragonBall561** [files-community/Files#3401]
**Is your feature request related to a problem? Please describe.**
Not really, just something I miss from original WE(Windows Explorer)

**Describe the solution you'd like**
In WE, there is a dropdown menu from 'This PC', 'OneDrive', etc. I would like that in Files.

**Describe alternatives you've considered**
I don't know any alternitaves

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

here is a screenshot:

![image_2021-02-01_125235](https://user-images.githubusercontent.com/61358474/106497677-5b022b80-648c-11eb-996a-4f7b2956c5d2.png)

**Comment by XPoppyX** [comment]
Making headers collapsible is part of #692

**Comment by gave92** [comment]
Yup but even #692 does not cover a full tree view in the sidebar (where you can expand e.g the C:\ drive to any folder depth).
Not quite sure if it would be ok to show a full tree view in the sidebar.. perhaps we could implement a tree view layout instead (#1928)

**Comment by yaichenbaum** [comment]
We don't have any plans for a full tree view in the sidebar, but we do have plans for a tree view layout. Make sure to check #1928.

**Comment by yair100** [comment]
@onlycs Tree View is currently available in preview https://files.community/download. It will be included in the next stable release.
