### ISSUE TITLE
Feature: Show picture thumbnails in Details view

### ISSUE THREAD

**Issue by asuetin** [files-community/Files#3402]
**Is your feature request related to a problem? Please describe.**
It's hard to identify pictures at a glance when they all use the same generic picture icon.

**Describe the solution you'd like**
Show small thumbnails:
![image](https://user-images.githubusercontent.com/37500046/106511918-f8d41580-64e1-11eb-88d8-7be980b349e4.png)
Instead of the generic icon:
![image](https://user-images.githubusercontent.com/37500046/106511983-0d181280-64e2-11eb-83e9-636ab744b087.png)

**Comment by yaichenbaum** [comment]
@asuetin This behavior is consistent with File Explorer, can you let us know if you think implementing this change will improve the experience, because after all, the icons will anyways be small and hard to see.

**Comment by asuetin** [comment]
> @asuetin This behavior is consistent with File Explorer

If you select the small icons view in File Explorer and zoom in with Ctrl + mouse wheel a couple of steps, you can achieve visible thumbnails that are smaller than the icons in Files' Details view. So if anything, I'm not sure why Microsoft decided to hide them in Details view :P

> can you let us know if you think implementing this change will improve the experience, because after all, the icons will anyways be small and hard to see

I feel like being able to identify pictures at a glance improves the experience. 

See the example screenshot above: I have a folder with a bunch of wallpapers. The filenames are non-descript, yet I remember the general look and color palette of the wallpaper I want, so even though the icon is small, I can still identify it instantly and set it as a wallpaper from the context menu.

In Files I'd have to either change the view or open them in the preview pane/image viewer one by one.

**Comment by 1EnderStore** [comment]
I support
It is very difficult for me to find the folders with images I need without previewing

**Comment by lucas-thiebaut** [comment]
@yair100 
![Capture d’écran (16)](https://github.com/files-community/Files/assets/128183422/af377a46-b4f9-4714-9165-19bae199be1a)
I think the problem has been solved

**Comment by asuetin** [comment]
Yeah, it's solved.

**Comment by LesFerch** [comment]
I'm using Files 3.8.0.0 and I can only see thumbnails in Tiles and Grid views. Details, List, and Columns view show the associated program icon. What am I missing?

**Comment by yaira2** [comment]
After trying both options, we've settled on the recommended behavior of only showing thumbnails for larger sizes.

**Comment by LesFerch** [comment]
Thanks for the reply! It's good to know I wasn't missing something obvious.

**Comment by LesFerch** [comment]
But why not make it a user selectable option since you have code to do it either way?

**Comment by Josh65-2201** [comment]
This is a 3 year old request. The code for this has changed a lot and probably removed for the details layout.

**Comment by yaira2** [comment]
Currently, our focus is on maintaining consistency with the thumbnail system in File Explorer. Past attempts at implementing custom features in this area have resulted in numerous issues.
