### ISSUE TITLE
Can't drag & drop shortcuts

### ISSUE THREAD

**Issue by pklion** [files-community/Files#3403]
**Describe the bug**
I couldn't drag & drop shortcuts from Files.

**To Reproduce**
1. Make a shortcut.
2. Drag it into Desktop or something from Files.

**Expected behavior**
Support dragging shortcuts.

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 20H2 19042.746]
 - App version: [v1.2.0.0]

**Additional context**

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5907244/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5907246/debug_fulltrust.txt)

**Comment by gave92** [comment]
Sadly this is a limitation of the uwp platform. Shortcuts (and hidden files) can only be copy/pasted, not dragged.

**Comment by pklion** [comment]
OK, I understand.
Thank you :)
