### ISSUE TITLE
新标签页中的文件夹希望可以进行自定义的设置

### ISSUE THREAD

**Issue by 1091515459** [files-community/Files#3408]
**Is your feature request related to a problem? Please describe.**

新标签页的文件夹部分无法进行增减和删除，但是我并不想用默认提供的几个选项，这让我很困扰

**Describe the solution you'd like**

希望增加对新标签页的文件夹部分进行增减和删除的功能

**Describe alternatives you've considered**

null

**Additional context**

![image](https://user-images.githubusercontent.com/33256117/106546358-002d0a80-6546-11eb-842d-f6fa3b34b288.png)

**Comment by gave92** [comment]
Merging with #3426
