### ISSUE TITLE
希望能提高打开文件夹的速度

### ISSUE THREAD

**Issue by 1091515459** [files-community/Files#3409]
**Is your feature request related to a problem? Please describe.**

当它打开文件夹很慢的时候，我总是很烦躁

**Describe the solution you'd like**

希望打开文件夹并显示器中的文件的速度可以和windows本身的资源管理器一样

**Describe alternatives you've considered**

null

**Additional context**

null

**Comment by yaichenbaum** [comment]
@1091515459 Can you fill out the issue template?

**Comment by gave92** [comment]
Merging with #3373
