### ISSUE TITLE
希望能在一级菜单显示全部右键功能项

### ISSUE THREAD

**Issue by 1091515459** [files-community/Files#3410]
**Is your feature request related to a problem? Please describe.**
每次我对着文件夹右键的时候第三方提供的右键功能大部分都被放在了二级菜单，这让我很困扰

**Describe the solution you'd like**
希望可以自定义一级菜单显示第三方软件提供的右键功能的显示数量，或者直接给一个开关用来控制是否将更多地第三方软件的右键功能显示在一级菜单中

**Describe alternatives you've considered**
null

**Additional context**
![image](https://user-images.githubusercontent.com/33256117/106548860-beeb2980-654a-11eb-9305-92a474afcc5f.png)
![image](https://user-images.githubusercontent.com/33256117/106549210-754f0e80-654b-11eb-81b2-ff2f4ce4997e.png)
![image](https://user-images.githubusercontent.com/33256117/106549248-8a2ba200-654b-11eb-8733-110382eb00b8.png)

**Comment by yaichenbaum** [comment]
@1091515459 Thank you for your feedback, you can change this behavior by turning off the "Move overflow items into a sub menu" option under the Appearance settings page. Please let us know if this is what you were looking for.

**Comment by 1091515459** [comment]
oh,my fault,thank you
