### ISSUE TITLE
Files makes me feel like I have a HDD...

### ISSUE THREAD

**Issue by oOII-J4HN-IIOo** [files-community/Files#3413]
**Describe the bug**

I have Files version 1.20 (on 1st Feb 2021) installed and at this point, I'm only using it because it looks better. Otherwise, IT IS SO SLOW. I feel like it's as if my OS is on a HDD (I'm running an SSD). Whether that's relevant or not, the UI "speed and responsiveness" needs to be improved ASAP. 

I feel like it's especially slow when either (a) opening large folders or (b) using "Bundles" shortcuts. But when I need to access files quickly, I find myself wanting to switch back to Windows' File Explorer (which I don't want to do!).

**To Reproduce**
1. Go to Files
2. Click on anything, literally
3. See error

**Expected behavior**
A waiting time like no other...
**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2]
 - App version: [v1.2.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`, you should see a file in this directory called debug.txt or/and debug_fulltrust.txt.

**Comment by R3voA3** [comment]
> It's possible that this is because we changed how the cache system works, can you try resetting Files? Alternatively, you can try deleting this file `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalCache\cache.db`.

Try if this helps a bit

**Comment by oOII-J4HN-IIOo** [comment]
> > It's possible that this is because we changed how the cache system works, can you try resetting Files? Alternatively, you can try deleting this file `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalCache\cache.db`.
> 
> Try if this helps a bit

To be honest, not really. It still "loads" before opening the next folder. I feel like the loading times are very random - sometimes it will load instantly (which is ideal!) but other times it takes a few seconds before bringing up the next page... I think I'll just have to wait for the next performance update!

**Comment by Wanooo0** [comment]
@oOII-J4HN-IIOo Hi ! Same issue here... I'm working on Linux server network (Synology) and the Files performance is very very slow... Files still "loads" at every folder opening (loading blue bars are sliding at least 3 times)... I'm back on Windows Explorer for the moment... :(
(a french user)

**Comment by carlosvsilva** [comment]
I had slow load times in File 1.1 but when it failed to update through Microsoft Store to 1.2, I reset it, uninstalled v1.1 and installed v1.2 . Now performance is more acceptable.

**Comment by thepoweroftwo** [comment]
Unfortunately this is what keeps me from using Files too.. I really want to like it, the interface is beautiful and functional. But the responsiveness does feel too slow for a file browser.
I tried deleting the cache db with no improvements.

**Comment by yaichenbaum** [comment]
@oOII-J4HN-IIOo Is this still an issue in v1.3?

**Comment by oOII-J4HN-IIOo** [comment]
> @oOII-J4HN-IIOo Is this still an issue in v1.3?

No, it's no longer _as big_ an issue in v1.3. It still a tad slower than File Explorer which I'm sure will improve over time.

**Comment by Msouza91** [comment]
I didn't experience the older versions, but I wouldn't say this is fixed. I started using it just this week, but performance is quite bad, specially in OneDrive folders, trying to move files around the cloud drive took me too much time, deleting files took anywhere from 30 seconds to a minute. Rough...

**Comment by yaira2** [comment]
We're excited to share that startup performance will be significantly improved in the upcoming release of version 3. You can download the preview version from our website https://files.community/download.
