### ISSUE TITLE
unable to copy path

### ISSUE THREAD

**Issue by HydrogenDeuterium** [files-community/Files#3416]
**Describe the bug**
i choose to "copy path",and windows told me err occurs,and its "unknown error".
it also ask me to report it ,and i do so.

**To Reproduce**
choose to copy path

**Expected behavior**
path copied to my clipboard

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: win 10 2004
 - App version: 1.1.0.0

**Additional context**
Does this problem occur again after restarting the app?
- yes

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`, you should see a file in this directory called debug.txt or/and debug_fulltrust.txt.
[debug.txt](https://github.com/files-community/Files/files/5911151/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5911157/debug_fulltrust.txt)

**Comment by yaichenbaum** [comment]
@HydrogenDeuterium Is this still an issue with v1.2?

**Comment by HydrogenDeuterium** [comment]
okay,i see
