### ISSUE TITLE
Add Ctrl+scrollUp and Ctrl+ScrollDown shortcut

### ISSUE THREAD

**Issue by LoganTann** [files-community/Files#3420]
**Is your feature request related to a problem? Please describe.**
Sometimes, the font/layout is too small. I have the habit to change the font size using `CTRL` `Scroll Up/Down`.
This shortcut is the alias of `CTRL` `+` / `-`, which already exists in the explorer.

**Describe the solution you'd like**
Make an alias shortcut where `CTRL` `SCROLL UP` = `CTRL` `+` and `CTRL` `SCROLL DOWN` = `CTRL` `-`. 

**Describe alternatives you've considered**
`CTRL` `+` and `CTRL` `-`

**Additional context**
#2575 mentionned this idea but using a slider.

**Comment by XPoppyX** [comment]
Ctrl + scroll up and Ctrl + scroll down is already supported

**Comment by LoganTann** [comment]
oh I tried it with the trackpad of my laptop... I had to use the two fingers zoom shortcut  instead of ctrl + finger scrolls
sorry for the disturbing
