### ISSUE TITLE
Feature: Add support for setting an alias name for favorites

### ISSUE THREAD

**Issue by tirsocarranza** [files-community/Files#3422]
Can you please allow pinned folders to be renamed?
To be clear, I don't want the original folder to be renamed, just the name of that folder on the list.

Thanks!

**Comment by yaichenbaum** [comment]
@tirsocarranza Can you give a little more detail on how renaming the item on the sidebar will be helpful for you?

**Comment by KristofKekesi** [comment]
It would be useful when there is a typo. It would reduce clicks made by unpinning renaming and pinning again.

**Comment by X0rg** [comment]
I am facing similar problem as @ndsvw: I have folders with the same name, so it is hard to know which one correspond to a given project.
Most file explorers for GNU/Linux (like Thunar) allow to rename a pinned folder (without renaming the target folder obviously).

**Comment by yaichenbaum** [comment]
We don't have plans to support this feature.

**Comment by stijnherreman** [comment]
When I pin a network share like `\\FOOSERVER\c$` it is displayed as `c$`. That quickly becomes an issue as you pin more network shares with that name.

**Comment by Josh-65** [comment]
Merging with #7256

**Comment by yaichenbaum** [comment]
Reopening since https://github.com/files-community/Files/issues/7256 is a different request

**Comment by sthivaios** [comment]
#7256 I think that they are both the same thing...

**Comment by yaira2** [comment]
@tirsocarranza does File Explorer have anything equivalent to this?

**Comment by yaira2** [comment]
It looks like the recommended solution is to pin libraries to Quick Access, have you tried this?
