### ISSUE TITLE
Dragging and dropping file takes me to the destination folder

### ISSUE THREAD

**Issue by 10catsinspace** [files-community/Files#3423]
In Windows Explorer, if I drag and drop a file then I remain in the source folder. This means I can quickly organize files. For instance, I can navigate to Documents, then drag ten different files into ten different subfolders quickly without having to navigate back.

In Files, when I drag and drop a file I am immediately taken to the destination folder. So if I'm in Documents and drag a file to Documents/Work then I am navigated to Documents/Work and have to press back to continue organizing files in Documents.

Please offer an option to toggle this behavior -- it makes file organization a chore.

**Comment by yaichenbaum** [comment]
Ideally, navigating to a destination folder should only happen when hovering over an item for a couple of seconds.

**Comment by ReyMagos** [comment]
Folder opens a little bit more than 2 second after. Can you decrease this time? Somewhere between 1.75 and 2.0?

**Comment by yaichenbaum** [comment]
@10catsinspace This issue should be resolved with #3468.
