### ISSUE TITLE
3D Objects Folder

### ISSUE THREAD

**Issue by johan-perso** [files-community/Files#3425]
**Is your feature request related to a problem? Please describe.**
In the classic Windows Explorer, there is a folder pinned in the quick access named "3D Objects". I want this folder can be accessible from the Quick Access of Files.

**Describe the solution you'd like**
Add the folder "3D objects" to the quick access of Files.

**Describe alternatives you've considered**
I actually no alternative except to use the classic explorer.exe of Windows.

**Comment by yaichenbaum** [comment]
@johan-perso Can you try right clicking on the "3D Objects" folder and clicking on pin to sidebar?

**Comment by johan-perso** [comment]
yes but there is not the 3d objects icon

**Comment by yaichenbaum** [comment]
@johan-perso We don't have plans to use the 3d objects icon on the sidebar, please let us know what kind of impact this will have on your usage of Files.
