### ISSUE TITLE
Choose what folders are displayed on home page

### ISSUE THREAD

**Issue by johan-perso** [files-community/Files#3426]
**Is your feature request related to a problem? Please describe.**
I want the possibility of add file / folder to the quick access.

**Describe the solution you'd like**
Add a button when we right click on a file/folder to add him on the quick access, or choose what is displayed in the settings (like if I want to unshow the Music folder I can unshow him from the settings or with a right click on it)

**Describe alternatives you've considered**
I actually found no alternative..

**Comment by johan-perso** [comment]
I speak of this quick access
![image](https://user-images.githubusercontent.com/41506568/106745560-8f5b2080-6621-11eb-8104-96bbb0352c62.png)

**Comment by yaichenbaum** [comment]
Merging with #3962.
