### ISSUE TITLE
Too many Cloud Folders

### ISSUE THREAD

**Issue by MarathonMax** [files-community/Files#3427]
Just installed Files on a new laptop and it has too many cloud folders. Like false positives.

For example "Google Drive (Bureau)" (aka Desktop in French) points to "C:\Users\maxim\OneDrive\Bureau"

![image](https://user-images.githubusercontent.com/7364694/106682275-22e41100-6590-11eb-906a-0f38d7880619.png)

**Comment by yaichenbaum** [comment]
@MarathonMax Would you expect to only have the Google Drive item on the sidebar?

**Comment by 10catsinspace** [comment]
To add on to this -- it would be great if we could simply hide any unwanted cloud folders. For instance, I have a permanent shortcut to OneDrive even though I don't use it.

This would also allow users to hide any duplicate entries (as a short term fix)

**Comment by yaichenbaum** [comment]
@10catsinspace as a short-term fix, you can already remove the OneDrive entries by using the registry editor. In the future, you will be able to collapse sections as well.

**Comment by gave92** [comment]
See #3125 for the same bug
