### ISSUE TITLE
downloads sorted by download date

### ISSUE THREAD

**Issue by GreenBanana10** [files-community/Files#3429]
**Is your feature request related to a problem? Please describe.**
downloads are kinda useless right now, because its all sorted like a normal folder.

**Describe the solution you'd like**
sort by download date

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by d2dyno1** [comment]
You can already choose how files are sorted by clicking either of these columns:
![image](https://user-images.githubusercontent.com/53011783/106732563-1fdd3500-6611-11eb-83ca-3d18b9b3040d.png)

**Comment by XPoppyX** [comment]
@GreenBanana10  you mean grouping? 

![Captura de pantalla 2021-02-03 110845](https://user-images.githubusercontent.com/61259627/106758495-549cbc80-6610-11eb-8aeb-a1bcd4ee5bc9.png)

**Comment by GreenBanana10** [comment]
> You can already choose how files are sorted by clicking either of these columns:
> ![image](https://user-images.githubusercontent.com/53011783/106732563-1fdd3500-6611-11eb-83ca-3d18b9b3040d.png)

but that will always sort folders at the top. an option where the ONLY thing it sorts by is download date will make it alot better.

**Comment by carlosvsilva** [comment]
I agree, folder like downloads should sort by added date by default.

**Comment by yaichenbaum** [comment]
@GreenBanana10 The next update will have a column for the date created.
