### ISSUE TITLE
Files crashes when opening file location of shortcuts

### ISSUE THREAD

**Issue by pklion** [files-community/Files#3431]
**Describe the bug**
Files crashes when opening the file location of shortcuts.

**To Reproduce**
1. Make a shortcut.
2. Open file location of it.
3. See an error

**Expected behavior**
I would like you to change the files' behavior not crash.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 20H2 19042.789]
 - App version: [v1.2.0.0]

**Additional context**
This problem occurs again after restarting the app.

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5918301/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5918302/debug_fulltrust.txt)

**Comment by yaichenbaum** [comment]
@pklion This issue should be resolved with #3469.
