### ISSUE TITLE
KEEP THE FILE APP ON LAST TAB CLOSE

### ISSUE THREAD

**Issue by SiddharthSharma16923** [files-community/Files#3433]
I think the title itself explains the FEATURE REQUEST🙃

**Comment by yaichenbaum** [comment]
@SiddharthSharma16923 In order to stay consistent with other apps such as Microsoft Edge and Chrome, we don't have plans to make this change. However, we would be interested in hearing your use case to have a better understanding of what you are looking for in a file manager.

**Comment by SiddharthSharma16923** [comment]
point.
