### ISSUE TITLE
Bug on Portuguese (Brazil) translate

### ISSUE THREAD

**Issue by gilvandev** [files-community/Files#3435]
**Describe the bug**
When you choose "Portugues (Brasil)" as the default language, the app show some areas in another language (I really don't know what is)

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Preferences'
3. On App Language select "Portugues (Brasil)"
4. Restart the app. 
5. If you go to settings, will see the properties in another idiom. I've attached the print to illustrate

**Expected behavior**
All the interface shows on Portugues (Brasil)

**Screenshots**

![image](https://user-images.githubusercontent.com/671468/106802878-4f586580-6642-11eb-9311-a0a44d0d6582.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Pro 20H2 19042.746
 - App version: 1.2.0.0

**Additional context**
The problem persist after restart the app or the computer

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5921194/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5921195/debug_fulltrust.txt)

**Comment by gave92** [comment]
Merging with #3385
