### ISSUE TITLE
hide OneDrive

### ISSUE THREAD

**Issue by myersware** [files-community/Files#3436]
Make it possible to hide OneDrive in sidebar

**Comment by yaichenbaum** [comment]
@myersware Thank you for opening this issue, you can already remove OneDrive from the sidebar by following this [guide](https://answers.microsoft.com/en-us/msoffice/forum/msoffice_onedrivefb-mso_win10-mso_o365b/delete-onedrive-from-regedit/a1fa7fc5-3077-46b4-a325-01fa79b64ed6#:~:text=delete%20OneDrive%20from%20regedit.%201%20Press%20Windows%2BR%20and,data%20to%200.%20%20See%20More....%20See%20More.).
