### ISSUE TITLE
Add the editor of the context menu

### ISSUE THREAD

**Issue by pklion** [files-community/Files#3438]
**Is your feature request related to a problem? Please describe.**
There are so many items in the context menu and it contains unnecessary items.

**Describe the solution you'd like**
Please add the editor of the context menu to remove unnecessary items.

**Describe alternatives you've considered**
N/A

**Additional context**
![名称未設定 1](https://user-images.githubusercontent.com/78145811/106824540-62147e00-66c6-11eb-9608-7b5bd6b8b914.jpg)

**Comment by yaichenbaum** [comment]
@pklion Thank you for opening this issue, these menu items are stored in the registry and Files doesn't have access to manage them. I recommend checking out tools like ShellMenuView from Nirsoft to manage the context menu.

**Comment by pklion** [comment]
Thank you and understood.
