### ISSUE TITLE
Search doesn't work in any folder.

### ISSUE THREAD

**Issue by BreezyMain** [files-community/Files#3439]
**Describe**
As the title says, search doesn't work in any folder. even through I search a exit file, it still says the search result in xxx in empty. Is this a bug or an unfinished feature? idk.
**To Reproduce**
Just use search feature in any normal folder.
**Screenshots**
![屏幕截图 2021-02-04 125028](https://user-images.githubusercontent.com/61371380/106846392-bf6cf700-66e7-11eb-973c-d5003bdfdb9e.png)
![屏幕截图 2021-02-04 125105](https://user-images.githubusercontent.com/61371380/106846397-c136ba80-66e7-11eb-862c-cc3c882fef2a.png)
![屏幕截图 2021-02-04 125121](https://user-images.githubusercontent.com/61371380/106846399-c1cf5100-66e7-11eb-8b15-1a1e787e6168.png)
Desktop:
- OS Version: Windows 10 20H2 19042.746
- App Version:  1.2.0.0 (Download in Microsoft APP Store)
**Log File**
[LocalState.zip](https://github.com/files-community/Files/files/5923311/LocalState.zip)

**Comment by XPoppyX** [comment]
Do you have indexing enabled?

**Comment by BreezyMain** [comment]
> Do you have indexing enabled?

idk. But could you tell me how to enable it? Maybe this thing is causing the problem.

**Comment by BreezyMain** [comment]
> Do you have indexing enabled?

It works, but windows explorer can search file without index.

**Comment by gave92** [comment]
@BreezyMain there's an option in settings to search unindexed locations

**Comment by BreezyMain** [comment]
> @BreezyMain there's an option in Files settings to search unindexed locations

Oh, Sorry...........

**Comment by gave92** [comment]
@BreezyMain no worries :) let us know if toggling the setting fixes this issue.

**Comment by mathslimin** [comment]
can give a tip if not open the unindexed locations when search return blank
