### ISSUE TITLE
Can't delete files that require admin privileges.

### ISSUE THREAD

**Issue by Vixb1122** [files-community/Files#3441]
**Describe the bug**
Can't delete files that require admin privileges.

**To Reproduce**
1. open a directory that contains high-privilege file (eg: DUMP.tmp)
2. remove this file

**Expected behavior**
require admin privileges and remove this file.

**Screenshots**
![image](https://user-images.githubusercontent.com/17810492/106857801-a4a47d80-66fb-11eb-99f2-9daea8d51b81.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.789
 - App version: v1.2.0.0

**Additional context**

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5923867/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5923868/debug_fulltrust.txt)

**Comment by gave92** [comment]
Merging with #2513

**Comment by yaichenbaum** [comment]
This issue should be resolved with #4203.
