### ISSUE TITLE
Auto suggestions when searching are imprecise

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#3443]
**Describe the bug**
When typing into the auto suggestion box, the suggestions might be totally unrelated to what I typed.

**To Reproduce**
Just search for something

**Expected behavior**
File names should contain the string I typed into the box

**Screenshots**
![image](https://user-images.githubusercontent.com/17484252/106918179-4383a680-6709-11eb-93d8-d3ec395c36e9.png)

**Desktop (please complete the following information):**
 - OS Version: 
Edition	Windows 10 Pro
Version	20H2
Installiert am	‎19.‎06.‎2020
Betriebssystembuild	19042.746
Leistung	Windows Feature Experience Pack 120.2212.551.0

 - App version: [v0.12.0]

**Comment by gave92** [comment]
@R3voA3 maybe the files listed contain the search string? or maybe they are inside a folder matching the search string?

**Comment by R3voA3** [comment]
Name: string seems to work. So by default it searches the files' content? Sound like a weird behaviour. Most ppl will expect to only search for files containing the string in the name.

**Comment by gave92** [comment]
@R3voA3 by default It searches both (like windows explorer) but maybe we have the sorting wrong (matching file name should probably come before matching file contents)

**Comment by duke7553** [comment]
@gave92 @R3voA3 I'll take a look at this one.

**Comment by duke7553** [comment]
To fix this, we'd need to evaluate whether a setting which prepends "name:" to the beginning of the search query is desirable. Some users want to search file names by default rather than in item contents.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5842.
