### ISSUE TITLE
"Remove all Properties" button is hidden in Property Dialog

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#3444]
Because the default size of the dialog is too small, the button is hidden. It appears when increasing the size of the dialog.

**Default**
![image](https://user-images.githubusercontent.com/17484252/106919366-5f3b7c80-670a-11eb-8909-0969e3acac3c.png)

**Increased Size**
![image](https://user-images.githubusercontent.com/17484252/106919694-a9246280-670a-11eb-8784-686a0c3ceb07.png)

**Comment by winston-de** [comment]
The clear properties button is displayed at the bottom of the list of properties, so when the window is smaller scrolling down will reveal it.

https://user-images.githubusercontent.com/59544401/107068989-25b05300-6796-11eb-8b26-8ebbcf0bc47d.mp4

**Comment by R3voA3** [comment]
While this is true, it's very intuitive since the other buttons are "pinned" at the bottom.

**Comment by XPoppyX** [comment]
Should it always be visible as in the default file explorer?

![Captura de pantalla 2021-03-19 115739](https://user-images.githubusercontent.com/61259627/111800034-52ce4600-88aa-11eb-959d-ea590c3fec15.png)

**Comment by winston-de** [comment]
> Should it always be visible as in the default file explorer?
> 
> ![Captura de pantalla 2021-03-19 115739](https://user-images.githubusercontent.com/61259627/111800034-52ce4600-88aa-11eb-959d-ea590c3fec15.png)

Sure.

**Comment by yaichenbaum** [comment]
@R3voA3 This issue should be resolved with #4191.
