### ISSUE TITLE
Preview pane should say no item selected when there's no selected item

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#3446]
Today preview pane says no details available / no preview available but when there's no selected item it should say "No item selected. Please select one to view it's details and preview"

**Comment by R3voA3** [comment]
in Windows Explorer it just shows the number of items in the current folder. 
![image](https://user-images.githubusercontent.com/17484252/107010372-8d669e00-6796-11eb-95a9-4f74355ed08b.png)

**Comment by ReyMagos** [comment]
In my opinion when no items selected preview must disappeare. Then it won't interfere looks and feel.

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran This enhancement was implemented with #3639.
