### ISSUE TITLE
Opening a folder reloads the parent folder first

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#3447]
I think the video explains it quite well.

https://user-images.githubusercontent.com/17484252/107011513-07e3ed80-6798-11eb-9630-b1c5c4ceb042.mp4

**Comment by generalguy41** [comment]
Not a dev, but I believe it may be related to the change in layout for each directory? Seems to refresh the current directory in the layout version of the target directory, as seen below. Still happens even if the layouts are the same type.

https://user-images.githubusercontent.com/8879244/107054500-349b0380-679e-11eb-976d-ec814f9f8139.mp4

**Comment by gave92** [comment]
Since #2962

**Comment by yaichenbaum** [comment]
@R3voA3 This issue should be resolved with #3464.
