### ISSUE TITLE
Erasing elements at c: drive level doesn't work

### ISSUE THREAD

**Issue by pabloderen** [files-community/Files#3448]
**Describe the bug**
Erasing elements at c: drive level doesn't work, it only prompts option to erase permanently but nothing happen after confirmation.

**To Reproduce**
1. Go to c: drive root level.
2. Right Click on an file/folder
3. If prompted accept to erase permanently
4. See error, file is still there 

**Expected behavior**
after process, file/folder is deleted

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: Windows 10 19041 10.0.19041
 - App version: v1.2.0

**Additional context**

**Log file**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5932468/debug_fulltrust.txt)

**Comment by gave92** [comment]
@pabloderen do the files require administrator access?

**Comment by okey2k** [comment]
@gave92 I incurred the same situation with Pablo, all actions on C: need admin access doesn't work with Files. I understood there is a separate issue related to this. But it seems in that issue no specific plan mentioned solving this problem.

**Comment by gave92** [comment]
Merging with #3441
