### ISSUE TITLE
Warning about existed bundle name

### ISSUE THREAD

**Issue by ReyMagos** [files-community/Files#3449]
**Feature**: Attempting to create bundle with existed name will has no effect but showing something like a warning can be useful and conveniently. For example, when user types existed bundle name warning text (yellow, of course) appears under the input area.

**Comment by d2dyno1** [comment]
I've added it to #2881 under the **Future Bundles PR** section. I'll make a PR in the coming days

**Comment by yaichenbaum** [comment]
@ReyMagos This enhancement was implemented with #3637.
