### ISSUE TITLE
Search causes app to crash

### ISSUE THREAD

**Issue by LaneTOGA** [files-community/Files#3450]
**Describe the bug**
Search for *.jpg causes app to crash

**To Reproduce**
1. Enter search field
2. Type *.jpg
3. Press enter

**Expected behavior**
Not crash (duh), and then show all files with .jpg extension

**Screenshots**
![Screenshot 2021-02-05 160339](https://user-images.githubusercontent.com/76738433/107050810-f7e60100-67cb-11eb-868a-750186afb207.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10.0.21301
 - App version: v1.2.0.0

**Additional context**
Does this problem occur again after restarting the app? YES
Now it seems to happen as soon as I type * or anything in the search, before hitting enter.

**Log file**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5933391/debug_fulltrust.txt)

**Comment by gave92** [comment]
@Lane-HOY Could you post the other log file ("debug.txt") as well?

**Comment by yaichenbaum** [comment]
@LaneTOGA Thank you for reporting this issue. We need a little more information from you in order to investigate this issue, please reopen this issue once you have uploaded the log file.
