### ISSUE TITLE
Shortcuts not sorting properly in Recycle Bin

### ISSUE THREAD

**Issue by Tech-How** [files-community/Files#3453]
**Describe the bug**
When the Recycle Bin is sorted by "Date deleted," any shortcut (.lnk) files will either appear on top or on the bottom.

**To Reproduce**
1. Create a shortcut using the Windows Explorer, let's say, with the letter K.
2. Move that shortcut to the Recycle Bin.
3. Open the Recycle Bin in the Files app, and sort it by "Date deleted."
4. Even though the name of that shortcut is in the middle of the alphabet, that shortcut will appear either on the top or the bottom.
5. This may not seem like a big deal, but it is quite annoying when I have a lot of shortcuts that I have to scroll through before I can reach what I am trying to find.

**Expected behavior**
I would expect the shortcut files to also follow the same sorting rules you specified for the entire Recycle Bin.

**Screenshots**
![image](https://user-images.githubusercontent.com/76794507/107063465-6c0ead80-67a8-11eb-9b7d-8d04ac56df83.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Version 20H2 (OS Build 19042.746)
 - App version: v1.1.0.0

**Additional context**
This problem has always occurred since the Recycle Bin could be sorted by date deleted. I have also noticed that the text under date deleted reads "0 seconds ago" for all the shortcuts. Could this possibly be because it is referring to the date deleted of the item the shortcut points to, and not the shortcut itself? Because the actual file was never deleted.

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5934045/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5934055/debug_fulltrust.txt)

**Comment by yaichenbaum** [comment]
@Tech-How This issue should be fixed with #3462.
