### ISSUE TITLE
Side bar management

### ISSUE THREAD

**Issue by chenha1** [files-community/Files#3456]
**Is your feature request related to a problem? Please describe.**
I wish there is a way to hide / unhide drives (i.e. cloud drive / c drive etc. ) and re-order pinned folders on the sidebar
**Describe the solution you'd like**
Drag and drop for re-ordering folders just like the original file explorer. 

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by ReyMagos** [comment]
Is possible to return directory to sidebar? Occasionly I unpinned the Documents folder.

**Comment by gave92** [comment]
This suggestioms should be covered by #1069 and #692
