### ISSUE TITLE
Add possibility to localize type of drives

### ISSUE THREAD

**Issue by nvi9** [files-community/Files#3457]
**Is your feature request related to a problem? Please describe.**

Currently the type of drives comes from the result of an enum to string conversion. Thus it has limitations (eg. no spaces allowed) and cannot be localized either.

Setting of item type:

https://github.com/files-community/Files/blob/a97af604f3019abf06c255b27bea44c7fecbc128/Files/ViewModels/Properties/DriveProperties.cs#L29

The `DriveType` enum:

https://github.com/files-community/Files/blob/a97af604f3019abf06c255b27bea44c7fecbc128/Files/Filesystem/DriveItem.cs#L195-L207

The result:

![image](https://user-images.githubusercontent.com/42123156/107117127-5963a980-6878-11eb-89af-c6d72b43bd3c.png)

**Describe the solution you'd like**

We could add new resource strings for all the `DriveType` enum values to make these type names localizable and change the line above in `DriveProperties.cs` to something like this:

```csharp
ViewModel.ItemType = string.Format("DriveType{0}", Drive.Type).GetLocalized();
````

**Additional context**
App version: 1.2.0.0

**Comment by gave92** [comment]
Requested first in #1411. Feel free to work on this if you wish 👍
