### ISSUE TITLE
Undesired tooltips on some sidebar items

### ISSUE THREAD

**Issue by nvi9** [files-community/Files#3458]
**Describe the bug**
The tooltip shown on some of the sidebar items could be simply improved. The tooltip text represents the path of each item except if if contains a `?` character. See line below:

https://github.com/files-community/Files/blob/a97af604f3019abf06c255b27bea44c7fecbc128/Files/Filesystem/LocationItem.cs#L17

This could be improved with a bit more checking, I don't know if I've found all the cases, there might be more.
The problematic items so far:
- Home (always shows "Home", disregarding the app language settings)
- Recycle Bin (shows "Shell:RecycleBinFolder")

**To Reproduce**
1. Move the cursor over either Home or Recycle Bin on the sidebar
2. See tooltips

**Expected behavior**
The Home and Recycle Bin items should show the same text in their tooltips as their name is. It can be done with assigning the value of the Title instead of the Path property, like this:

```csharp
HoverDisplayText = Path.Contains("?") || Path == "Home" || Path.StartsWith("Shell:") ? Text : Path;
```

Or (if preferred) show no tooltip on these items, since their "path" has no additional information as in case the other items.

**Screenshot**

![image](https://user-images.githubusercontent.com/42123156/107117765-caa55b80-687c-11eb-983c-1ba9e102dca1.png)

**Desktop:**
 - OS Version: Windows 10 20H2 19042.746
 - App version: v1.2.0.0

**Comment by KristofKekesi** [comment]
Similar issue: #1226

**Comment by nvi9** [comment]
@KristofKekesi no, it's a different thing. The referenced issue and similar ones are about to load the localized name from the system, this is about not showing werid/untranslated tooltips on sidebar items
