### ISSUE TITLE
Using back/forward mouse buttons in dual pane broken

### ISSUE THREAD

**Issue by TineSvete** [files-community/Files#3463]
**Describe the bug**
Using back/forward mouse buttons in dual pane causes both panes to go FW/BW Irregardless of where mouse cursor is when clicked.

**Comment by generalguy41** [comment]
Out of curiosity, I mentioned in [this ticket](https://github.com/files-community/Files/issues/2910#issuecomment-770238017) that it also affects other tabs. Does this fix that as well, or should I open a new ticket?

**Comment by yaichenbaum** [comment]
@TineSvete This issue should be resolved with #3465.
