### ISSUE TITLE
Can't move windows from title bar

### ISSUE THREAD

**Issue by SpyrosRai** [files-community/Files#3467]
**Describe the bug**
Can't move the app window when dragging the title bar, where the tabs are

**To Reproduce**
1. Go to any part of the interface (except settings) 
2. Click on the title bar
3. Drag it anywhere

**Expected behavior**
The windows moves around

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2 19042.789]
 - App version: [v1.2.0.0]

**Additional context**
The window can still be dragged from below the title bar or near the minimize button

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5937334/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5937335/debug_fulltrust.txt)

**Comment by Ein-Tim** [comment]
This is already tracked in #3250
