### ISSUE TITLE
Ctrl-L not working in Home screen

### ISSUE THREAD

**Issue by KAMiKAZOW** [files-community/Files#3470]
The Ctrl-L shortcut seems to work everywhere except the Home screen.

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2
 - App version: 1.2.0.0

**Comment by d2dyno1** [comment]
I'll fix

**Comment by yaichenbaum** [comment]
@KAMiKAZOW This issue should be resolved with #3473.
