### ISSUE TITLE
Missing Transition When Clicking Desktop, Documents, Downloads... from side-menu

### ISSUE THREAD

**Issue by EriKWDev** [files-community/Files#3475]
**Describe the bug**
When I click the Desktop/Downloads/Documents...-cards from the home-page, there is a nice transition into the corresponding folder. This transition is missing when clicking from the side-menu.

**To Reproduce**
1. Go to 'Home'
2. Click on 'Desktop'-card
3. See transition

4. Click on 'Home'
5. Click on 'Desktop' in side-menu
6. No transition to be seen.

**Expected behavior**
There should be a transition both from the card and from the side-menu.

**Screenshots**
### Expected Transition:
There is a slight slide-up animation when entering Dekstop from the Card.
![ezgif-3-61025e6a3d09](https://user-images.githubusercontent.com/19771356/107142432-30eab680-692f-11eb-83aa-b34700cc673d.gif)

### No Transition:
There is a jarring jump to the Desktop when entering from the side-menu.
![ezgif-3-be0e2775200f](https://user-images.githubusercontent.com/19771356/107142408-039e0880-692f-11eb-93f0-c7ee842377ae.gif)

**Desktop:**
 - OS Version: Windows 10 19041.746
 - App version: v1.2.0.0 (Latest from Microsoft Store)

**Comment by BanCrash** [comment]
This issue seems to be solved on 2.0 (and probably on lower versions).

![GIF 02-09-2021 22-12-03](https://user-images.githubusercontent.com/11770760/131909685-e930e97f-decd-4d38-9415-e0b3e37a6a17.gif)


@yair100
