### ISSUE TITLE
Cloud Drives online files invisible

### ISSUE THREAD

**Issue by szalka66** [files-community/Files#3479]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by gave92** [comment]
Could you add some more details? Are we talking about Onedrive?
Could you post a screenshot of how the folder appears in windows explorer VS Files? Thanks!

**Comment by yaichenbaum** [comment]
@szalka66 Thank you for reporting this issue, we need a little more information from you in order to investigate this issue, please reopen this issue once you have filled out the issue template.
