### ISSUE TITLE
[Open in explorer] context menu item.

### ISSUE THREAD

**Issue by PMExtra** [files-community/Files#3481]
**Is your feature request related to a problem? Please describe.**
I use **Files** as my preferred file browser (replace **Explorer** with **Files**). But **Files** is not so stable and powerful like **Explorer** so far. In many cases, I still need to use **Explorer** to finish the specified operations. I hope there is a convenient way to switch between **Files** and **Explorer**.

> There are some cases I need to use **Explorer**:
> - Some operations that need privilege escalation
> - View file property details, such as certificate information, or check file hash by HashTab. (They are shown in Property panel in **Explorer** but not in **Files**)
> - Search files with [**Listary**](https://www.listary.com/)
> - Copy / move folders that with so many files or complex structure (such as node.js project or git repo). (This operation may be failed in **Files**, even make **Files** exit unexpected)

**Describe the solution you'd like**
A context menu item such as [Open in explorer].

**Describe alternatives you've considered**
I know this is a niche feature. (I'm not sure the word `niche` is suitable, I means this feature is not common, it only needed by a few people)
So I think we can make an switch option in settings to control this feature enabled.

**Additional context**
If you welcome this feature, I may implement it by myself and contribute.

**Comment by gave92** [comment]
Note:
Even if we add an "open in explorer" option in the context menu, I'm afraid that if you replace Explorer with Files things are going to get messy: once Explorer is open clicking on any folder will trigger Files to open again.

**Comment by R3voA3** [comment]
What about "Open with default file browser/explorer" 😁

**Comment by PMExtra** [comment]
@R3voA3 I'm not sure what you mean. The current "Open" is already truly "Open with default file browser".
This issue is talk about a way to quick switch between **Files** and **Explorer**.

**Comment by PMExtra** [comment]
@gave92 I agree with you. This is truly a problem. But it won't hinder me in my use cases. I use **Files** to navigate in paths, I hardly click folder in **Explorer**.
This feature is just a fallback solution in transition. It will be removed after we solve the all use cases that need **Explorer**.

**Comment by PMExtra** [comment]
@gave92 @yair100 So would you approve this feature if I implement it?

**Comment by yaichenbaum** [comment]
@PMExtra We would like to keep this open for a little bit longer to gather more feedback from other users.

**Comment by yaichenbaum** [comment]
@PMExtra After thinking this through I apologize that we are not going to approve this issue, however, you can still add this menu item by following the instructions in #2565.
