### ISSUE TITLE
Selection rectangle overlays preview pane

### ISSUE THREAD

**Issue by d2dyno1** [files-community/Files#3482]
**Describe the bug**
Selection rectangle overlays preview pane

**Expected behavior**
Stop the rectangle at the preview pane's border

**Screenshots**
![image](https://user-images.githubusercontent.com/53011783/107157376-1858bb80-6984-11eb-8d39-d1e56a8446c2.png)

**Additional context**
This is a visual issue

**Comment by winston-de** [comment]
Likely related to #3004.

**Comment by nvi9** [comment]
Both this and #3004 could be solved with limiting the width and height of `selectionRectangle` in the DrawRectangle method (see below), but a cleaner solution would be better than checking bounds of the list view each time cursor moves...

https://github.com/files-community/Files/blob/f86be9ce53cde71af1f6a6bbc58a4f1647841485/Files/UserControls/Selection/RectangleSelection.cs#L71-L112

**Comment by nvi9** [comment]
Yesterday I've made some trials with this proposal, it only helped with the horizontal limiting issue (this one), but not with the other in case of a view with scrolling content (when the items overflow and the selection rectangle is visible during scrolling up). So (this time) I think it would be better to try to solve them independently 😅 this one from the C# side, the other one from the XAML side with making the statusbar to hide the selection rectangle on the bottom side too.

I'll make a PR for this one in the next days if it's okay to you. And maybe to the other one too if I find something usable.

**Comment by yaichenbaum** [comment]
@d2dyno1 This issue should be resolved with #3520.
