### ISSUE TITLE
Add switch to not remember recent files

### ISSUE THREAD

**Issue by paucp** [files-community/Files#3483]
**Is your feature request related to a problem? Please describe.**
I really like this app but there's a feature that puts me off. You can't disable the recent files area in the home tab. 

**Describe the solution you'd like**
Adding a switch in the settings to disable the feature.
Instead of looking this this:
![image](https://user-images.githubusercontent.com/20616716/107158600-8bb1fb80-698b-11eb-8a89-b1354d7a8ba5.png)

It'd look like this:
![image](https://user-images.githubusercontent.com/20616716/107158564-4db4d780-698b-11eb-9ea4-e6c6991beb73.png)

**Describe alternatives you've considered**
I don't think there's a more user friendly way to implement a feature like this than a simple switch in the settings tab.

**Comment by gave92** [comment]
There's already an option in settings for this, under "Widgets" 👍
