### ISSUE TITLE
no inicia la aplicación

### ISSUE THREAD

**Issue by angel2973** [files-community/Files#3484]
![Captura de pantalla 2021-02-07 184526](https://user-images.githubusercontent.com/78706701/107161860-dfb1e580-6975-11eb-89d2-5c02fafb24fb.png)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`, you should see a file in this directory called debug.txt or/and debug_fulltrust.txt.

**Comment by XPoppyX** [comment]
@angel2973 Sigues teniendo este problema?

**Comment by angel2973** [comment]
yes Enviado desde Correo para Windows 10 De: RichardEnviado: viernes, 19 de marzo de 2021 10:22 a. m.Para: files-community/FilesCC: angel2973; MentionAsunto: Re: [files-community/Files] no inicia la aplicación ***@***.*** Sigues teniendo este problema?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by XPoppyX** [comment]
Para saber cual podría ser el problema es importante que subas aquí los archivos `debug.txt` y `debug_fulltrust.txt` (arrastrando y soltando), que está en:

`%userprofile%\AppData\Local\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState\`

Y por favor, trata de responder entrando directamente al enlace que te trae aquí en GitHub, porque desde el correo se envía muchas cosas innecesarias lo cual hace difícil encontrar y leer tu respuesta. Gracias.
