### ISSUE TITLE
Add support for Xbox

### ISSUE THREAD

**Issue by Nun-z** [files-community/Files#3486]
**Describe the bug**
After installing this app to an Xbox in dev mode with all the required dependencies, the app crashes immediately when launched.

**To Reproduce**
1. Start the Xbox in dev mode.
2. Install Files to the Xbox through the Xbox Device Portal with all dependencies.
3. Attempt to launch the app on Xbox.
4. See the error: "That didn't work for some reason.  (0x80070057)

**Expected behavior**
The app should launch without crashing.

**Screenshots**

**Desktop (please complete the following information):**
 - Xbox Series X
 - App version: [v1.2]

**Additional context**
The problem persists after restarting the Xbox.

**Comment by yaichenbaum** [comment]
@Nun-z Files doesn't support Xbox, but we can keep this issue open to investigate adding support.

**Comment by DeveloperWOW64** [comment]
Is Files a UWP app?

**Comment by Nun-z** [comment]
@DeveloperWOW64 Yes, see here: https://www.windowscentral.com/files-uwp-preview-stunning-start-uwp-file-explorer

**Comment by DeveloperWOW64** [comment]
If it is UWP, why doesn't it have support for Xbox? Is it because the files app can't read Xbox file system?

**Comment by yaichenbaum** [comment]
@DeveloperWOW64 Files is a UWP application but we rely on shell integratiosn to support many of the app's features.

**Comment by DeveloperWOW64** [comment]
ahh ok. PowerShell or just normal cmd?

**Comment by josh-65** [comment]
I would like to see this too if its possible.

**Comment by yaichenbaum** [comment]
Closing as Xbox doesn't have support for applications like Files.

**Comment by Nun-z** [comment]
@yair100 What do you mean by Xbox not having support for applications like Files?  There are a few file managers on the Microsoft store that work on Xbox.  For example, see My Files Explorer here: https://www.microsoft.com/en-us/p/my-files-explorer/9msrp54s8d43?activetab=pivot:overviewtab
