### ISSUE TITLE
Crash when viewing properties of hidden/system file

### ISSUE THREAD

**Issue by KaiHuaDou** [files-community/Files#3488]
When I view the detail of the C:\Users\Administrator\Music\desktop.ini, my app crashed.
these are my debug.txt and debug_fulltrust.txt
[debug.txt](https://github.com/files-community/Files/files/5941771/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5941772/debug_fulltrust.txt)

**Comment by yaichenbaum** [comment]
@KaiHuaDou This issue was fixed with #3295.
