### ISSUE TITLE
Can't Mount Virtual Drive (Vhdx)

### ISSUE THREAD

**Issue by FrozenVertx** [files-community/Files#3490]
Hello Everyone,
Today I mount my vhdx. When I click Files prompt for admin(filesfulltrust.exe) I give permission but after that It gives me error :There was a error mounting the file (See Screenshot). I tried many times even reboot but error remains same. The mounting works from file explorer. I think same problem with vhd also I had not tested it
![Mount Problem](https://user-images.githubusercontent.com/72699730/107209286-99698e80-6a28-11eb-84f8-704178e5d786.png)

I also noticed one more issue there is no eject option for virtual drives(e.g. vhdx) like file explorer.
So please fix issue and add option for virtual drives.

**Comment by gave92** [comment]
Thanks for this report. Atm Files does not support operations that require admin access. We'll check if there's a workaround for mounting vhds (e.g launching an elevated powershell)

**Comment by josh-65** [comment]
Still happens on 1.5.32. Any update on this?

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5206.
