### ISSUE TITLE
Share Point support

### ISSUE THREAD

**Issue by Fromit** [files-community/Files#3491]
I cannot see my SharePoint folders in "Files".
Do i need to change something or the app don't support this kind of connections?

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by gave92** [comment]
Merging with #1310
