### ISSUE TITLE
App crashed when emptying recycle bin

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#3493]
There were around 90 items in the Recycle Bin and I tried to empty it via the context menu. App started deleting items and then crashed. Recycle Bin was empty afterward though.

[debug_fulltrust.txt](https://github.com/files-community/Files/files/5945749/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/5945750/debug.txt)

**Comment by boscorelly** [comment]
which version of windows and app ?

**Comment by duke7553** [comment]
@gave92 Similar stacktrace to #4316 and #4330

**Comment by gave92** [comment]
@duke7553 yeah, it's been around since 1.2 and I can't figure it out :(

**Comment by yaichenbaum** [comment]
@R3voA3 is this still an issue?
