### ISSUE TITLE
It does not work the explorer when copying.

### ISSUE THREAD

**Issue by LuisCRamirezA** [files-community/Files#3497]
**Is your feature request related to a problem? Please describe.**
You should put a kind of HUD or a popup when copying o cutting something, because the explrorer gets stuck and the user doesnt know what is the porcentaje of copying. The option in right bottom doesnt work, everything gets stuck when copying large archives.

**Describe the solution you'd like**
A popup like windows showing a porcentaje o a porcentaje bar, and that the explorer keep usable when doing this actions (Gets stuck everything when copying things)

**Describe alternatives you've considered**
Its a little slower than the explorer from windows

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by gave92** [comment]
Same issue as #3355
