### ISSUE TITLE
Small window issues

### ISSUE THREAD

**Issue by nvi9** [files-community/Files#3498]
**Describe the bug**
When the window is resized to small, there are 1) some top menu items overflowing and 2) sidebar items on Settings page don't fill up the whole height of the window.

**To Reproduce**
1. Resize the window to as small as possible
2. Stay on file browser page for 1) or go to Settings page for 2)
3. See error

**Expected behavior**
I'm including these issues in one because they both might be solved with setting the minimum size of the window. If it should be avoided, then we can split this up into two separate issues.

For 1) some items could be automatically moved to the More options flyout menu when the window size is not wide enough to show all of them.

For 2) it might be related to the fact there is the Settings item on the browser page sidebar at that position the same place where is an empty slot on the sidebar of the Settings page, so I suppose they're using the same layout (didn't checked yet). In that case the solution could be hiding that secion on the Settings page.

**Screenshots**
For 1) see middle of the picture with Refresh and Search buttons over each other:

![image](https://user-images.githubusercontent.com/42123156/107287979-0732ac00-6a63-11eb-8616-c44fec6a0adb.png)

For 2) see empty space at the bottom left corner on the sidebar:

![image](https://user-images.githubusercontent.com/42123156/107288455-c5eecc00-6a63-11eb-8c8b-9eb4aa618433.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.789
 - App version: v1.2.0.0

**Comment by lukeblevins** [comment]
@yair100 For the navigation toolbar items being clipped off, would it help if we switched to a customized version of the CommandBar control?

**Comment by yaichenbaum** [comment]
@duke7553 The toolbar items will be fixed in the future when we move some items around. The goal is to switch to a regular command bar so the items can overflow.

**Comment by lukeblevins** [comment]
@yair100 Right, that's what I was referring to. We'd just need to customize the item style so toolbar buttons look like they do now.

**Comment by yaichenbaum** [comment]
With the other changes I have in mind, the styles likely won't need to be changed very much.

**Comment by yaichenbaum** [comment]
@nvi9 The first issue is now resolved in `main`,  can you check if the second issue is an issue with the NavigationMenu?

**Comment by nvi9** [comment]
@yair100 the first issue is resolved, but there is another instead: the Search and the More options buttons are hidden on the right.

![image](https://user-images.githubusercontent.com/42123156/109783432-48555080-7c0a-11eb-8eb0-24120c0e99ca.png)

And the sidebar can be resized to as wide as the smallest window, I don't know if this was intentional or not.

![image](https://user-images.githubusercontent.com/42123156/109783732-99654480-7c0a-11eb-9f0c-bc1224dca7d8.png)

The second one is probably an issue with the NavigationView control, `IsSettingsVisible="False"` ([here](https://github.com/files-community/Files/blob/6e3ee8fc5fd1d0b7a9408e4eab308675bd5d493a/Files/Views/Settings.xaml#L60)) seems to hide the settings item instead of collapsing it.

![image](https://user-images.githubusercontent.com/42123156/109785365-599f5c80-7c0c-11eb-9737-1d4bf0f0e686.png) ![image](https://user-images.githubusercontent.com/42123156/109785796-ca467900-7c0c-11eb-916d-cb0a08ac17eb.png)

**Comment by yaichenbaum** [comment]
@nvi9 Do you want to fix the issue with the sidebars max width?

**Comment by nvi9** [comment]
@yair100 yes, that would be a partial solution.

To prevent hiding by overflow of the path bar and the search button ([see screenshot](https://user-images.githubusercontent.com/42123156/109783432-48555080-7c0a-11eb-8eb0-24120c0e99ca.png) from the previous comment) we could set min width of the sidebar to a lower/percent value or collapse it automatically as it was suggested on Discord (#design) on Friday.

**Comment by yaichenbaum** [comment]
@nvi9 That's a great idea, do you want me to assign you this issue?

**Comment by nvi9** [comment]
@yair100 I don't know how much time I'll have for this in the next days/week, but we can give it a try.

First I'll try to implement the collapsing NavigationView based on the width of the window, then find some solution for the overflowing parts, then dig deeper about hiding the settings item completely on the bottom of settings navigation view.
Do you think we should split this up into different PR-s (and issues) or we're good with one?

**Comment by yaichenbaum** [comment]
@nvi9 I think it can be done in one PR.

**Comment by nvi9** [comment]
Problem 2) is a known issue, there is a PR for it already: https://github.com/microsoft/microsoft-ui-xaml/pull/4193
