### ISSUE TITLE
Feature: Support multiple Google Drive accounts

### ISSUE THREAD

**Issue by cobbettjp** [files-community/Files#3500]
**Is your feature request related to a problem? Please describe.**
I have 2 Google Drive accounts, one which syncs to (C:) and and another to (D:). Under 'Cloud Drives' Files only shows the account associated with (C:).

**Describe the solution you'd like**
The functionality to be added to display multiple Google Drive accounts.

**Additional context**
I am using Files version 1.2.

**Comment by metallicgloss** [comment]
+1 for this feature enhancement, would be very nice to see.

I'd also like to note that this doesn't necessarily only occur when the Google Drive folders are on different drives; I have two folders on my C: drive that link to two different Google Drive accounts and only the first is detected. The ability to display multiple at once, or even for users to manually manage them (so you can manually create/hide a specific cloud drive) would be appreciated.

**Comment by maelchiotti** [comment]
This is an old issue that is partially resolved for me.

I have two Google Drive accounts on the same drive. I have Files setup to automatically start with Windows, and to remain in background.

When it first starts, Files only displays mt first Google Drive account. However, if I manually exit Files and then restart it, it correctly displays my two accounts.

**Comment by Josh65-2201** [comment]
Can you see if this is still an issue in the preview version. https://files.community/download

**Comment by maelchiotti** [comment]
I haven't encountered the issue anymore in some months, even though I forgot to mention it. I can't really tell when it began to work correctly again.

**Comment by Josh65-2201** [comment]
Thanks for letting us know

**Comment by maelchiotti** [comment]
I just remembered that I do not use the options to auto start with windows and stay opened in the background, because of the issue with pinned items disappearing. So this is probably why I haven't encountered the issue.

Anyway, when I can enable these options again, if the issue comes up I'll open a new issue referencing this one.
