### ISSUE TITLE
Automatically preview readme files when no file is selected

### ISSUE THREAD

**Issue by andrew-stclair** [files-community/Files#3502]
**Is your feature request related to a problem? Please describe.**
Not a problem, just an idea i had for implementing something from the XP days.

**Describe the solution you'd like**
When in a folder with no file or files selected, the preview pane should preview a file (if it exists) with a specific name, like README.md

**Describe alternatives you've considered**
Only alternative i have come up with is to just click on README.md with the preview pane open

**Additional context**
(This but without me having to select the file)
![image](https://user-images.githubusercontent.com/4944499/107349032-d8c4d780-6b1b-11eb-861e-4604db7926af.png)

**Comment by yaichenbaum** [comment]
@andrew-stclair This is an interesting idea, and I can see it being useful for a lot of users.

**Comment by R3voA3** [comment]
Love the idea. Not sure if useful, but maybe a setting where the user can define the name of the file?

**Comment by d2dyno1** [comment]
How about it previewed the current directory you're in?

**Comment by winston-de** [comment]
What if, instead, the file was automatically selected when the user navigated to a folder that contains a readme file? This way, if the file is quickly accessible to open (or right click) and would show the preview. The user would also be able to set names/extensions (eg: .sln file, .csproj) that they would want to quickly be able to access/preview when opening a folder.

**Comment by d2dyno1** [comment]
e

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5393.
