### ISSUE TITLE
Distributing development versions

### ISSUE THREAD

**Issue by pklion** [files-community/Files#3503]
**Is your feature request related to a problem? Please describe.**
I want to make development versions of Files feedback, but I couldn't build it because I haven't used VS.

**Describe the solution you'd like**
Please distribute development versions.

**Describe alternatives you've considered**
I'm sorry, I couldn't find it.

**Additional context**
N/A

**Comment by yaichenbaum** [comment]
@pklion You can join the insider flight group by filling out this [form](https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAO__Qw_X6FUM0pUSzMxNUlCWE1FVENKVlVNVUNTRVpOUS4u).

**Comment by pklion** [comment]
Thank you!
