### ISSUE TITLE
Navigate with Mousebutton affects all Tabs

### ISSUE THREAD

**Issue by TheR00st3r** [files-community/Files#3505]
**Describe the bug**
Navigation using the mouse Keys affects all opened Tabs  and SplitViews.

**To Reproduce**
1. Open at least 2 Tabs (for better visual Control in split view)
2. Navigate a few times in each Tab
3. Press Backbutton on Mouse
4. See all Tabs are navigating one step back

**Expected behavior**
I would expect that only the focused Tab is navigating back.

**Screenshots**
Not required

**Desktop (please complete the following information):**
 - OS Version: Windows 10 17763 Build 17763
 - App version: 1.2.0.0

**Additional context**
Effect stays after restart

**Log file**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5951231/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/5951233/debug.txt)

**Comment by gave92** [comment]
Thanks for the report. This issue has been fixed -> #3463
