### ISSUE TITLE
Open file location in Task Manager doesn't work with Files.

### ISSUE THREAD

**Issue by PMExtra** [files-community/Files#3519]
**To Reproduce**
1. Open "Task Manager", switch to "Details" tab.
2. Select any process, right click and select "Open file location".
3. **Files** will open and exit immediately unexpected.

**Expected behavior**
Files will open and located the selected process file.

**Screenshots**
![image](https://user-images.githubusercontent.com/11289158/107487772-7e7e5200-6bc1-11eb-8f70-58bb3addd7ca.png)

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 20H2 19042.746]
 - App version: [v1.2.0.0]

**Log file**
```
Cannot create instance of type 'Microsoft.UI.Xaml.Controls.XamlControlsResources' [Line: 26 Position: 40]|Windows.UI.Xaml.Markup.XamlParseException: The text associated with this error code could not be found.

Cannot create instance of type 'Microsoft.UI.Xaml.Controls.XamlControlsResources' [Line: 26 Position: 40]
```

**Comment by gave92** [comment]
Same as #3117. Files can't run as administrator.
