### ISSUE TITLE
Bug while copying

### ISSUE THREAD

**Issue by ReyMagos** [files-community/Files#3522]
Bug description:
Error happens while copying multiple folders with inner files to external drive (redmi phone storage).

[debug.txt](https://github.com/files-community/Files/files/5959793/debug.txt)

**Comment by gave92** [comment]
@ReyMagos was this happening when copying items, when pasting items or when navigating between folders? Were the items copied or drag/dropped?

**Comment by ReyMagos** [comment]
There were folders in the Dowloads. I **_selected_** and **_cutted them via context menu_**. Next I went to folder on Redmi drive and **_pasted folders via Ctrl+V_**. After nothing happens, not folders, not progressbar (I'll create separate issue for progressbar feature). I thought that Files don't support Ctrl+V and **_pasted folders via context menu_**. A few seconds later I got several messages "Item already existed" and after I closed all of them error occured.

**Comment by KAMiKAZOW** [comment]
> After nothing happens, not folders, not progressbar (I'll create separate issue for progressbar feature).

Exists already: #3368

**Comment by ReyMagos** [comment]
So, I didn't create another one)

**Comment by yaichenbaum** [comment]
@ReyMagos Is this still an issue in v1.5?

**Comment by ReyMagos** [comment]
No, it isn't. "Item already exists" messages appearing without any probems.
