### ISSUE TITLE
file icons are blurred when switching between DETAILS and GRID VIEW modes.

### ISSUE THREAD

**Issue by kleuton05** [files-community/Files#3529]
this occurs with all file types

https://user-images.githubusercontent.com/51864325/107619009-3e56b800-6c31-11eb-86b2-f25773a8a105.mp4

**Comment by kleuton05** [comment]
![SharedScreenshot](https://user-images.githubusercontent.com/51864325/107619159-807ff980-6c31-11eb-9d94-301e6a2d050a.jpg)

**Comment by gave92** [comment]
Should be fixed in version 1.3.5 (beta), if it's still happening please let us know.
