### ISSUE TITLE
the application crashes when copying files

### ISSUE THREAD

**Issue by kleuton05** [files-community/Files#3530]
this occurs in all directories and file types
v 1.2.2

**Comment by gave92** [comment]
@kleuton05 thanks for this report could you post the debug files?

**Comment by kleuton05** [comment]
[debug.txt](https://github.com/files-community/Files/files/5968993/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5968994/debug_fulltrust.txt)

**Comment by gave92** [comment]
@kleuton05 is the crash happening when copying files, pasting files or navigating to a folder? Did you get a notification when the app crashed?

**Comment by kleuton05** [comment]
The moment I paste a file, the app freezes and only unfreezes again after the transfer is completed.

**Comment by gave92** [comment]
If the app is not crashing (closing unexpectedly) than this is the same as #3355

**Comment by gave92** [comment]
@kleuton05 could you confirm whether the app is *crashing* (closing unexpectedly) or *freezing*? Thanks!

**Comment by kleuton05** [comment]
freezing

**Comment by gave92** [comment]
Thanks fixed in version 1.2.3 (#3350)
