### ISSUE TITLE
Files closes immediately after the start

### ISSUE THREAD

**Issue by Wurstautomat** [files-community/Files#3531]
**Describe the bug**
If I start Files it closed immediately. I tested maybe 35 times and only 5 times it doesn't close. The problem appears after patch 1.2.0.0. Double window mode was active and I deactivated it. Maybe the index could be the problem. I attached the logfile

**Expected behavior**
If I start Files it closed immediately. I tested maybe 35 times and only 5 times it doesn't close

**Desktop **
 - OS Version: [e.g. Windows 10 20H2 19042.804]
 - App version: [v1.2.2.0] Problem started after 1.2.0.0

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5964175/debug.txt)

**Comment by AlteredCarbonate** [comment]
Same here!

It seems to depend on the Directory size. Small Dirs load fast, but big ones (3 TB)
Crash in an instant.

**Desktop **
OS Version: Windows 10 Pro 10.0.19041 Build 19041
App version: v1.2.2.0

**Comment by Wurstautomat** [comment]
After patch 1.3.0.0 no more crashes. I started "Files" 30 times and had no crashed or other problems.

**Comment by wheeljack73** [comment]
I've just got round to installing Files again, v1.3.0.0 and can confirm it is no longer crashing for me on startup.
Keep up the good work, and thank you very much for your efforts!

**Comment by yaichenbaum** [comment]
@Wurstautomat Thank you for the update!

**Comment by Humphrzy** [comment]
I have just installed the app from the Microsoft store. I had never use it before. it crushes few second after launching. 
![2021-05-17_12h03_28](https://user-images.githubusercontent.com/17433401/118463052-fe0f4600-b707-11eb-961b-20fa00cd11ed.png)
 this is the screen that it displays a few second then it closes.
 my Files version is 1.5
OS version is 2004
