### ISSUE TITLE
Can't access to my cloud files

### ISSUE THREAD

**Issue by Hardawks** [files-community/Files#3532]
The problem :
When I want to open one of my cloud storages (Google Drive or Onedrive) the software freezes and then crashes. I can't open any folder from my drive in the file explorer. 
Maybe it can't access to the cloud servers, idk i'm not an expert.
![image](https://user-images.githubusercontent.com/78914202/107643470-77654b80-6c76-11eb-8c2b-2912bd362585.png)

I hope being able to acces any cloud storage soon, because all my files are in it.
Sincerely

**Comment by Hardawks** [comment]
up; now it works, quite strange...

**Comment by gave92** [comment]
@Hardawks thanks for this report. Even if now it's working could you post the debug files?

**Comment by Hardawks** [comment]
Infact I figured out that the bug appears only on the first 30s/1min when I open the software. I tried a second time and same problem. When I open the software, click on "Google drive" or "Onedrive" and then I try to open one of my folders : freeze and crash

**Comment by gave92** [comment]
Is this still an issue with Files 1.3? Is so, could you post the app's log files?

**Comment by Hardawks** [comment]
Thanks for your answer, I just tested with the new version and it seems to work ! I attached the logs to this email.
Have a good day,
Tom

________________________________
De : Marco Gavelli <notifications@github.com>
Envoyé : jeudi 4 mars 2021 18:48
À : files-community/Files <Files@noreply.github.com>
Cc : Hardawks <hardawks@outlook.fr>; Mention <mention@noreply.github.com>
Objet : Re: [files-community/Files] Can't access to my cloud files (#3532)


Is this still an issue with Files 1.3? Is so, could you post the app's log files?
