### ISSUE TITLE
App crash when I open a folder on my USB drive

### ISSUE THREAD

**Issue by MitoCodeGithub** [files-community/Files#3535]
**Bug description**
When I open a folder on my USB drive, the app crashes for no reason. I still can open any folder on all other hard drives.

**To Reproduce**
1. Click on the USB drive
2. Open any folder

**Screenshots**
![image](https://user-images.githubusercontent.com/46863322/107661948-10ea2880-6c8a-11eb-9e9b-c9d357bb6c89.png)
![image](https://user-images.githubusercontent.com/46863322/107662061-30815100-6c8a-11eb-822f-05555de7f2be.png)

**Desktop:**
 - OS Version: 10.0.18363 Build 18363
 - App version: v1.22.0

**Additional context**
Does this problem occur again after restarting the app? **Yes**

**Log file**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5966666/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/5971919/debug.txt)

**Comment by gave92** [comment]
@MitoCodeGithub thanks for this report. Could you also post the other debug file? It's called "debug.txt"

**Comment by Alternative415** [comment]
I think I have a simmilar problem. Except that in my case, it crashes on almost every folder.
Version 1.2.2.0, Windows 10 20H2. This has never happened in 1.1.1.0
Attaching my logs:
[debug.txt](https://github.com/files-community/Files/files/5971434/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5971435/debug_fulltrust.txt)

**Comment by MitoCodeGithub** [comment]
> 
> 
> @MitoCodeGithub thanks for this report. Could you also post the other debug file? It's called "debug.txt"

Sure. I've edited my previous post.

**Comment by gave92** [comment]
I *think* this issue is the same as #3504 (fixed).
Is the issue happening also if you change the current folder layout mode to Grid View before attempting to double click a folder?

**Comment by gave92** [comment]
@MitoCodeGithub does the name of the folder you're trying to open start with a "!" ?

**Comment by gave92** [comment]
Hopefully the same as #3504.
- Could you check if the crash happens also if you put the current folder in Grid View before going to that folder?
- Could you check if the crash happens also if you enable the "open items with one click" option in Files settings?

**Comment by Alternative415** [comment]
> Hopefully the same as #3504.
> 
> * Could you check if the crash happens also if you put the current folder in Grid View before going to that folder?
> * Could you check if the crash happens also if you enable the "open items with one click" option in Files settings?

Yeah, when I put it in grids view or make folders open at double click, everything works well. Sorry for the duplicate. I hope there is a hotfix update comming soon because with this fixed, I can consider moving on from 1.1.0.0.
Thanks for your commitment and feedback. Have a good day!

**Comment by gave92** [comment]
Fixed in 1.3!
