### ISSUE TITLE
Creating Bundle: Dialog shows incorrect localisation

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#3538]
![image](https://user-images.githubusercontent.com/17484252/107666293-a4255d00-6c8e-11eb-8c3d-e152166c6b25.png)

The underlined text should use the same localisation key as in the "Rename Bundle" dialog.

**Comment by yaichenbaum** [comment]
@R3voA3 Was this fixed in your pull request?

**Comment by R3voA3** [comment]
No it wasn't.

**Comment by yaichenbaum** [comment]
Fyi @d2dyno1

**Comment by yaichenbaum** [comment]
@R3voA3 The different dialogs have different keys by design.
