### ISSUE TITLE
Fluent icons are blurry

### ISSUE THREAD

**Issue by yarikv8601** [files-community/Files#3539]
**Describe the bug**
Side panel icons are blurry at 100% system UI scale.

**To Reproduce**
Launching the Files app at 100% UI scale is enough.

**Expected behavior**
Icons must look sharp like in Chromium Edge or recently updated UWP apps.

**Screenshots**
Files app
![изображение](https://user-images.githubusercontent.com/52413473/107667995-3898bb00-6ca1-11eb-9bb6-6a9b68be94b5.png)
Side panel mock up in UWP using icons from https://github.com/yoshiask/FluentSystemIconsUWP
![изображение](https://user-images.githubusercontent.com/52413473/107667458-a395c200-6ca0-11eb-9c72-2d5e72fb8cdf.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.804
 - App version: v1.2.2.0

**Additional context**
Current icons obviously lacks hinting (currently used icons are ttf font?).

**Comment by yaichenbaum** [comment]
This issue should be resolved with #3864.
