### ISSUE TITLE
Enhancement: Add info when disk is almost full

### ISSUE THREAD

**Issue by pafase** [files-community/Files#3540]
**Is your feature request related to a problem? Please describe.**
Not a problem but it would be very useful.

**Describe the solution you'd like**
Add a link to storage sense when the disk is almost full.

**Comment by ZackaryH8** [comment]
This feature should be optional and toggleable in settings. It's the one reason I don't like the actual windows explorer!

**Comment by XPoppyX** [comment]
The problem is, what will be the default color? blue? If the accent color is used, in my case I wouldn't notice it because I set it to red.

Maybe an alternative could be to show a warning icon or something like that

**Comment by ZackaryH8** [comment]
Even better, make default behavior the same as Windows and allow for hex color input in the settings for what would be blue and red in Windows.

**Comment by yaichenbaum** [comment]
@farolillo I am not against this idea, but can you provide a little more context on how this will improve the experience for you?

**Comment by R3voA3** [comment]
> Even better, make default behavior the same as Windows and allow for hex color input in the settings for what would be blue and red in Windows.

While I like the idea, I'd prefer a color picker control.

**Comment by nvi9** [comment]
How about simply making the text red (and maybe bold) below the bar in this case? This way the bar could keep the actual accent color, but the state could be indicated without any extra icon or anything.

![image](https://user-images.githubusercontent.com/42123156/107755611-59095980-6d23-11eb-9b8c-c11f7701f92e.png) ![image](https://user-images.githubusercontent.com/42123156/107755548-4131d580-6d23-11eb-8e87-27df95fc61d4.png)

**Comment by ZackaryH8** [comment]
> How about simply making the text red (and maybe bold) below the bar in this case? This way the bar could keep the actual accent color, but the state could be indicated without any extra icon or anything.

I like this approach better, but I still think it should be an optional feature

**Comment by nvi9** [comment]
@ZackaryH8 I agree, and maybe also providing the possibility of selecting different methods for determining "almost full" state. I mean, in Explorer there is a fix percentage (~10%, [not editable](https://answers.microsoft.com/en-us/windows/forum/windows_7-performance/incorrect-low-space-warning-red-usage-bar-in/b42d61fd-9f5b-41d3-939a-83724aabab71)), we could have some options on the Settings page, like:

- not indicating it at all
- show if less than 10% free space left
- show adaptively based on the drive size (customizable)
  - when the total size is above a specified value and the free space is below another value (eg. when the total size is above 10 GB and the free space is below 1 GB) - suitable for large storage drives
  - when the total size is below the specified value, show if less than 10% free space left - suitable for SD cards, pendrives, etc.

If there is no one against it, I'll start a PR with these improvements. Of course further ideas, discussion is more than welcomed.

**Comment by yaichenbaum** [comment]
@nvi9 I would hold off on a PR for now, I would like to learn more about how this would improve the user experience before approving this issue.

**Comment by R3voA3** [comment]
> @nvi9 I would hold off on a PR for now, I would like to learn more about how this would improve the user experience before approving this issue.

Well, it's known that SSDs become slower if they are full. So indicating that a drive is almost full >80% or so might make user aware of that.

**Comment by yaichenbaum** [comment]
@R3voA3 The progress bar is meant to do the same thing, and changing the color seems a little redundant. What if there was some sort of icon or link that would take the user to the system settings storage sense page? This way, users can see what's taking up the space and try to free some up.

**Comment by R3voA3** [comment]
You could also add a little "!" next to the disk icon or something like that.

**Comment by d2dyno1** [comment]
Should the option to go to Storage Sense be in a context menu of the drive? Or where else?

**Comment by yaichenbaum** [comment]
@d2dyno1 What about having an info icon on the top right of the drive? Clicking on the icon can launch Storage Sense.

**Comment by yaichenbaum** [comment]
@d2dyno1 If you plan to work on this, you can probably reuse some of the code from #3975.

**Comment by yaichenbaum** [comment]
@pafase This issue should be resolved with #4409.
