### ISSUE TITLE
Crashing on startup.

### ISSUE THREAD

**Issue by Curcul** [files-community/Files#3541]
**Describe the bug**
On start up of the program 'Files' it freezes then crashes. A pop up in the corner shows up to report the problem. Even after a restart of my computer nothing is fixed. I have attached the debug.txt file.

**To Reproduce**
1. Open 'Files'
2. After a few seconds it crashes.

**Expected behavior**
The program 'Files' is to startup and work like a normal file explorer.

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: Windows 10.0.19042 Build 19042
 - App version: [v1.2]

**Additional context**
Every time you open the program it crashes.

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5967849/debug.txt)

**Comment by gave92** [comment]
Merging with #3169
