### ISSUE TITLE
Translation Error In Brazilian Portuguese - Version 1.2.0.0 and Above

### ISSUE THREAD

**Issue by SnyPer456** [files-community/Files#3542]
Since the update to the version 1.2.0.0 the Files app have been showing some parts in other language different from the selected one. If I use it in English, for example, it's fine. But if I select to use the system language (pt-br), it's mixing with other language. Thanks for this great app, and keep it up the good work!

![image1](https://user-images.githubusercontent.com/78930117/107687566-65d77000-6c85-11eb-8ee2-a9526c942dac.jpg)
![image2](https://user-images.githubusercontent.com/78930117/107687570-67089d00-6c85-11eb-9060-9927ad55f3cb.jpg)
![image3](https://user-images.githubusercontent.com/78930117/107687572-67089d00-6c85-11eb-9438-c3a2483d4ba0.jpg)
![image4](https://user-images.githubusercontent.com/78930117/107687576-67a13380-6c85-11eb-832b-7bf659bfa361.jpg)
![image5](https://user-images.githubusercontent.com/78930117/107687581-6839ca00-6c85-11eb-9552-8e1c94014e3b.jpg)
![image6](https://user-images.githubusercontent.com/78930117/107687584-6839ca00-6c85-11eb-8991-c4d6ffb1f906.jpg)

**Comment by gave92** [comment]
Merging with #3385
