### ISSUE TITLE
Crashes while opening folders

### ISSUE THREAD

**Issue by XYZ12715** [files-community/Files#3543]
when i open a folder the app just crashes!!!

**Comment by danmarshall** [comment]
Same here. Looking at the Microsoft Store, it says the app was installed today. So this new version might have the bug.

**Comment by gave92** [comment]
@XYZ12715 thanks for this report could you post the log files?

**Comment by R3voA3** [comment]
Same happened to me:

[debug.txt](https://github.com/files-community/Files/files/5970515/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5970517/debug_fulltrust.txt)

**Comment by hiddensanctum** [comment]
Issue is present in `v1.2` and `v1.2.2` but not `v1.1` for me. App works again after downgrading to `v1.1`

**Comment by theuniquejohnny** [comment]
My log files. Crashes for me as well.

[debug.txt](https://github.com/files-community/Files/files/5970945/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5970946/debug_fulltrust.txt)

**Comment by gave92** [comment]
I *think* this issue is the same as #3504 (fixed).
Is the issue happening also of you change the current folder layout mode to Grid View before attempting to double click a folder?

**Comment by ztgasdf** [comment]
@gave92 This error doesn't happen with those other layout modes. Enabling "Open items with a single click" stops this crash from occurring.

If it's possible, could someone build a new package and release it? I did see #3504 and that does appear to fix it, the only problem being that this error occurs on the latest version and I suspect there will only be more and more issues like these appearing until a new release comes out.

---

Off-topic: I'm unable to drag files or folders anywhere, it just stays in place. Running 1.2.2.

**Comment by gave92** [comment]
@ztgasdf I agree the fix should be released as soon as possible.

Off-topic: try to click once to select the item and then click and hold to start dragging.

**Comment by bl-ue** [comment]
When are we going to get a new release for this?  I can't use files at all.

**Comment by XPoppyX** [comment]
```
ERROR|Files.App|This collection cannot work with indices larger than Int32.MaxValue - 1 (0x7FFFFFFF - 1).
Parameter name: index|System.ArgumentOutOfRangeException: This collection cannot work with indices larger than Int32.MaxValue - 1 (0x7FFFFFFF - 1).
Parameter name: index
   at System.Runtime.InteropServices.WindowsRuntime.ListToBindableVectorAdapter.EnsureIndexInt32(UInt32 index, Int32 listCapacity)
   at System.Runtime.InteropServices.WindowsRuntime.ListToBindableVectorAdapter.GetAt(UInt32 index
```)

**Comment by bl-ue** [comment]
FYI guys&mdash;if you navigate with the arrow keys and descend into folders with the Enter key, Files won't crash.

**Comment by kiikoh** [comment]
@bl-ue Been having the issue and it seems using the mouse is related...

**Comment by tth05** [comment]
Same problem here, don't know when or why it happens
```
2021-01-16 20:31:32.8713|ERROR|.ctor|Index was outside the bounds of the array.|System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Internal.Runtime.CompilerHelpers.ThrowHelpers.ThrowIndexOutOfRangeException() + 0x25
   at Files.App.<OnActivated>d__36.MoveNext() + 0xac7
```

**Comment by bl-ue** [comment]
off-topic: why is the bot reacting negatively to its own comments? :smile:

**Comment by bl-ue** [comment]
@gave92 / @yair100 you can close this now.  v1.3 was release which fixed it.
