### ISSUE TITLE
Change CoreCursorType when hovering over certain UI elements

### ISSUE THREAD

**Issue by nuttyNaoko** [files-community/Files#3544]
**Is your feature request related to a problem? Please describe.**
No, this is simply a feature that could improve the feel of the app

**Describe the solution you'd like**
Change the way the cursor looks when clicking different areas of the app. Anything that has to do with hovering buttons or tabs should show the pointer hand cursor instead of the default arrow. If you're dragging and dropping an item, the cursor would change to a grabbing hand. Same goes for grabbing tabs and moving them around, even in the menu that pops up when right clicking items. Not sure if this can be done for grabbing the entire window itself and closing the app.I'm sure there is a way to do that, this is the best i can describe them. I feel like this brings you closer to the interface, it's a small but impactful change that i would love to see added. Of course this needs experimenting as not all tabs and buttons will need that. But it's a welcome change. Hope this helps!

**Describe alternatives you've considered**
No alternatives needed for this i think?

**Additional context**
This could be added to a new version.

**Comment by duke7553** [comment]
@nuttyNaoko Thank you for reporting this. I'm planning which areas of the app need a custom cursor, and it would help me if you could reply with a list containing each area of the app that needs a custom cursor and the desired cursor you feel makes sense.

For instance, I'm thinking that the hover button for the vertical tabs flyout needs the "hand" Windows cursor. You can find a comprehensive list [here](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Core.CoreCursorType?view=winrt-19041)

**Comment by nuttyNaoko** [comment]
Okay so where do I start.

All items that are in the left column, including the settings button should have a a **HAND** cursor when hovering over them.
Same goes for hovering over _**different tabs.**_
Same goes for hovering over _**different drives in the home page.**_
Same goes for hovering over _**the back, forward, up a directory, reload buttons, the 3 buttons on the bottom and the 3 buttons on the top right. All while also having the **HAND** cursor in the contextual menu's that can be hovered. When it's information about a file that cannot be modified, it should stay as arrow. But VERY important, change the cursor to **BEAM** when some text can be highlighted. Make sure the user can then copy/paste or even get a small dropdown menu next to the cursor to do so. This seems fine for the most part though.**_

I was almost certain windows had a grabbing hand cursor, but the list doesn't show it. Maybe I saw a custom cursor somewhere.

A **GRABBING** hand cursor would be used for everything that needs dragging like **_rearranging the tabs, dragging a file into a folder,_** ONLY change the cursor to grab when you actually start grabbing like in a tab, you should still be able to see the **HAND** cursor when clicking into a tab. Here is an example of what a grabbing hand would look like.
![image](https://user-images.githubusercontent.com/61063450/107837871-4a628700-6da3-11eb-82ed-9ffe19d0bf23.png)


Anything that needs **_double clicking for it to be accessed_** like entering a directory, should be an **ARROW**, though, this can be overridden when drag-selecting a number of items. In that case you would use a **CROSS** cursor. 

When selecting single different items using CTRL, the cursor should change to a **HAND** cursor as it would feel more like a button, though moving outside the purple area as shown in the picture below, the cursor would turn back to **ARROW**. So only hovering should change to **HAND**, in selection mode. Otherwise it's **ARROW** for Folders, **HAND** for files

![image](https://user-images.githubusercontent.com/61063450/107837340-bbed0600-6da0-11eb-816c-7a7cfcd4e983.png)

In this situation, I selected a couple files, held down CTRL and selected another couple files. When making a selection in this way, the cursor should always stay as **CROSS**, doesn't matter if you're hovering or not.

The 'URL' bar is near perfect, when editing as text, the X on the right should also have the **HAND** cursor when hovering. That also applies to the X in the tabs and the + for creating a tab. The X should also have it's own small box when hovering over it.

I hope this is will help, I figured that if I'd be doing this, I might as well explain it in detail.

**Comment by yaichenbaum** [comment]
@nuttyNaoko While we can override the default cursor types in Files, there are some ongoing discussions in the WinUI repository about making these changes on their end. I think we should wait to see where that effort leads to prevent duplicate work.

**Comment by nuttyNaoko** [comment]
All good!

**Comment by yaichenbaum** [comment]
Thank you for your feedback, we're going to stick with the default behavior for now.
