### ISSUE TITLE
Program is chrashing, when I want to open a folder

### ISSUE THREAD

**Issue by develdan** [files-community/Files#3547]
**Describe the bug**
Hey,
As of today there is a problem with the program. Whenever I want to open a folder (double click on it), the window freezes and the program crashes after a short time. I noticed that this mainly happens with large folders (> 1GB). Smaller folders (e.g. with only one file) can be opened without problems.

Please fix that. I really like your work and using it every day.
Thank you.

**To Reproduce**
double click on a large folder
[debug.txt](https://github.com/files-community/Files/files/5971074/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5971077/debug_fulltrust.txt)

**Desktop (please complete the following information):**
- Windows 10 20H2 19042.804]
 - App version: [v1.2.2.0]

**Additional context**
Also after restarting the app

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`, you should see a file in this directory called debug.txt or/and debug_fulltrust.txt.

**Comment by TGDTom** [comment]
Experiencing the same since today, before it seemed to work great.

**Comment by gave92** [comment]
Likely same issue as #3504 or #3525.
@develdan does the issue happen also if you change the current folder layout mode to Grid View before double clicking  on a folder?
Does the issue also happen if you enable the "open files with a single click" in Files settings?

**Comment by DotDebian** [comment]
Having the same crash issue, not happening when setting the layout to Grid View.

**Comment by develdan** [comment]
@gave92 and @DotDebian,
thx, with the "single click" feature or the grid view it worked for me, but it's not the same as before. Then I prefer the detailed view and a "double click". And I'm using the app nearly every day before, without any problems. Could be the issue a windows update, that I executed few days ago?

**Comment by gave92** [comment]
@develdan thanks for the infos. I've only suggested those checks as workarounds and to better understand the issue, we're planning to fix this properly :)

**Comment by carloscr99** [comment]
Hi,
I was checking that app today, and I detected the same problem, I have the "open files with a single click" disabled.
If I put he list view and enter a few folders, the app close suddenly, and doesn't matter if the folder that I want open is empty or not. 
I detected that error in Details view, but not in Gird View (small), I still cheking it a few days

**Comment by gave92** [comment]
Fixed in 1.3!
