### ISSUE TITLE
Not all settings persist

### ISSUE THREAD

**Issue by tarasius** [files-community/Files#3549]
**Describe the bug**
App theme setting is not saved after change.

**To Reproduce**
1. Open Settings -> Appearance -> App theme
2. Change from Windows default to Dark
3. Close app
4. Start app
5. See that theme is light and setting is set back to Windows default.

**Expected behavior**
Dark theme is kept selected after restart.

**Desktop (please complete the following information):**
Windows 10 Enterprise, build 18363
Ver 1.2.2.0 from Microsoft Store.

**Log file**
No relevant log found

**Comment by gave92** [comment]
Merging with #3291
