### ISSUE TITLE
Text issue

### ISSUE THREAD

**Issue by rafaelsouzams** [files-community/Files#3550]
Brazilian Portuguese have some words in Arabian language on the Settings menu.
![Captura de tela 2021-02-12 093327](https://user-images.githubusercontent.com/25182245/107768552-6881a600-6d15-11eb-91a3-9d8ea8363497.png)

**Comment by Alternative415** [comment]
Same with Korean. File size(MB, GB etc) is displayed in Arabic.

**Comment by gave92** [comment]
Merging with #3385
