### ISSUE TITLE
Extracting a file using WinRar the app closed suddenly

### ISSUE THREAD

**Issue by lettucemarcvel** [files-community/Files#3551]
**Describe the bug**
I have a file in .zip, so I have installed it WinRar 5.70, trying to unzip the file the app closed suddenly.
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5973123/debug_fulltrust.txt)

**To Reproduce**
1. Select the file.
2. Right Click in the file.
3. Select the option extract to
4. App closed

**Expected behavior**
Do not close the app.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS Version: Windows 10 19042.746
 - App version: 1.2.2.0

**Additional context**
When you open the app the file was extracted successfully, so I delete the extracted file, and I did it again and no issue.

**Log file**
Attached

**Comment by gave92** [comment]
@lettucemarcvel thanks for this report. There should be a second log file called "debug.txt". Could you upload that as well?

**Comment by lettucemarcvel** [comment]
[debug.txt](https://github.com/files-community/Files/files/5973702/debug.txt)

Hi Marco,
Attached! Thanks

**Comment by gave92** [comment]
@lettucemarcvel where you trying to unzip the file in the directory you where currently viewed in Files?

**Comment by lettucemarcvel** [comment]
![2021-02-12_16-23-01](https://user-images.githubusercontent.com/78508675/107823988-b070ef00-6d4e-11eb-89ad-e0058f61e278.jpg)
Here is the location that I have my .zip file and tried to unzip in this same location.

**Comment by gave92** [comment]
@lettucemarcvel thanks I'm thinking the issue is that one of the files in the archive was a shortcut file or a hidden/system file. #3295 should fix that.

**Comment by yaichenbaum** [comment]
@lettucemarcvel This issue should be resolved with #3295.
