### ISSUE TITLE
ArgumentOutOfRangeException with connected Smartphone (windows phone)

### ISSUE THREAD

**Issue by jp-weber** [files-community/Files#3553]
**Describe the bug**
By connecting the smartphone, the app can no longer be run, as it crashes again every time it is started.

**To Reproduce**
1. Connect the smartphone
2. Start the app
3. The app crashes
4. See log

**Expected behavior**
The app should not crash.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2
 - App version: 1.2.2.0

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5974029/debug.txt)

**Comment by gave92** [comment]
Same stacktrace as #3531

**Comment by gave92** [comment]
Merging with #3531, same error.
