### ISSUE TITLE
Application crashes on launch

### ISSUE THREAD

**Issue by wheeljack73** [files-community/Files#3554]
I hadn't used the app in a while, but when I have used it before I've had no issues.  However, I had done some updates through the Microsoft store, and this was one of the updates.    Application just crashes on launch now.

**Describe the bug**
'Something went wrong' error message on application launch.

**To Reproduce**
1. Go to Start menu.
2. Click on 'Files'.
3. Applcation opens for a second then closes, with an error message stating 'Something went wrong - Files ran into a problem that the developers haven't prepared for yet.' 

**Expected behavior**
Application to open normally without issue.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS Version: Windows 10 64 bit [20H2 19042.804]
 - App version: Doesn't open so can't see.  Whatever latest version is available on the Microsoft Store as of today.

**Additional context**
Remove and reinstallation of the app had no affect.  Also reset app through W10 settings with no change.

**Log file**
Files attached.
[debug.txt](https://github.com/files-community/Files/files/5974246/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5974247/debug_fulltrust.txt)

**Comment by gave92** [comment]
Same stacktrace as #3543

**Comment by wheeljack73** [comment]
Done, as per additional context on post :)

**Comment by gave92** [comment]
No issue, thanks for the infos.
