### ISSUE TITLE
Closes when opening a folder 

### ISSUE THREAD

**Issue by 1EnderStore** [files-community/Files#3555]
**Describe the bug**
Closes when opening a specific folder.

**To Reproduce**
1. We follow the path `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`
2. Open the `Microsoft` folder 

**Expected behavior**
I wanted to open the folder and see what was in it. It should have opened: D 

**Desktop:**
 - OS Version: Windows 10 20H2 19042.804
 - App version: v1.2.2.0

**Log file**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5974594/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/5974595/debug.txt)

**Comment by gave92** [comment]
Same as #3551
