### ISSUE TITLE
Selection rectangle doesn't work in list view mode

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#3556]
**Describe the bug**
For some reason, Selection rectangle doesn't work in the list view mode (DataGrid control) however it works on all other layout modes.

**To Reproduce**
1. Open a folder
2. If you are in another mode, switch to the list view mode
3. Try dragging with a mouse for selection

**Expected behavior**
Selection rectangle should work in list view mode

**Desktop (please complete the following information):**
 - OS Version: Windows 10 version 20H2
 - App version: 1.2.2.0

**Comment by generalguy41** [comment]
Same as #3263?

**Comment by Jaiganeshkumaran** [comment]
@generalguy41 Yes I didn't see that
