### ISSUE TITLE
Media Player controls in taskbar tooltip

### ISSUE THREAD

**Issue by KAMiKAZOW** [files-community/Files#3560]
Title basically says it all. The Windows taskbar's tooltip for Files shows controls for a media player. Version 1.2.2 / Win 20H2.

![files-tooltip](https://user-images.githubusercontent.com/3259076/107847825-29c01e80-6def-11eb-8305-44ab85c49842.png)

**Comment by gave92** [comment]
Unfortunately this is a Windows issue which we can't fix.

**Comment by yaichenbaum** [comment]
@KAMiKAZOW This issue should be resolved in the next update to Windows 10.
