### ISSUE TITLE
Implement 'Multi Path Selection' & 'Batch Selection'

### ISSUE THREAD

**Issue by JVariance** [files-community/Files#3562]
Hi,
1. I would appreciate a way to have a persisting selection, when switching folders. So you can pool some files in a selection from multiple paths/directories.
2. A batch selection tool would be amazing. It would help if you want to for example select all audio files in the current directory or maybe just all mp3 files.

I did a mockup with how it could look like in a side panel.

![windows-files-selection](https://user-images.githubusercontent.com/62245444/107856669-fa7ad300-6e29-11eb-91ab-2ce7ff47c009.jpg)

**Comment by torgeros** [comment]
While this could be useful when integrated into the workflow, especially when moving or copying files, it might overload the user with UI.

If this gets implemented, I would like it to be either an OPT-IN feature or maybe even an addon (if addons are possible with UWP)

**Comment by josh-65** [comment]
couldn't you just search *.mp3 in the directory then ctrl + a

**Comment by yaichenbaum** [comment]
> While this could be useful when integrated into the workflow, especially when moving or copying files, it might overload the user with UI.
> 
> If this gets implemented, I would like it to be either an OPT-IN feature or maybe even an addon (if addons are possible with UWP)

It's something the user would have to toggle first so that shouldn't be an issue.

**Comment by JVariance** [comment]
> 
> 
> Couldn't you just search *.mp3 in the directory then ctrl + a.

If I'd just want the mp3 files, of course. But if I want to select all audio files, this becomes a needlessly complicated process.

**Comment by JVariance** [comment]
@yair100 You could additionally consider an entry 'selection' in context menu (when right-clicking on file). 
Example:
User rightclicks mp3 file.
...
'Selection'
 |- 'select all of type'
 |- 'select all audio files'
...

**Comment by hiranmayd** [comment]
https://twitter.com/zeealeid/status/1302277651466420225?s=20 
a flyout like this might be a great solution for being able to select multiple files at once

**Comment by cinqmilleans** [comment]
@JVariance A management of search filters is being implemented #4813.
It will be very easy to display only files of a specific type (audio, video, pdf, ...).

**Comment by yaichenbaum** [comment]
![image](https://user-images.githubusercontent.com/39923744/121248435-7386b600-c871-11eb-9c1b-9ca0ececf88d.png)

While this concept was designed for creating archives, it's a good example of how something like this can work.

**Comment by mdtauk** [comment]
For this scenario in particular, Multi Path and Batch, you could "stash" files in a sidebar UI, and then perform an operation on all the files in the "stash"

**Comment by mdtauk** [comment]
Something like this maybe?
![image](https://user-images.githubusercontent.com/7389110/121259925-954f5f80-c8a8-11eb-8104-c9a7f73ce93a.png)

**Comment by yaichenbaum** [comment]
Merging with #6514.
