### ISSUE TITLE
Unpin directory from sidebar in the "Cloud Drives" section

### ISSUE THREAD

**Issue by carloscr99** [files-community/Files#3563]
Hi,

I only suggest the option to Unpin directory from sidebar in the "Cloud Drives" section, because in you stay in other folder, they give you that option:
![image](https://user-images.githubusercontent.com/33683416/107857582-5dbb3400-6e2f-11eb-9fe6-8b3f9e6133dc.png)

But if you situated in one of your Cloud Drives, like OneDrive, they don't give me that option:

![image](https://user-images.githubusercontent.com/33683416/107857625-b5599f80-6e2f-11eb-824d-6b8a16c7ab28.png)

They only give me the option to add (again?) that directory on the sidebar, but I can't deleted from the Cloud Drive section, or I don't find that option.

Carlos

**Comment by gave92** [comment]
I'm not sure we're going to add the possibility to hide/unpin the cloud folders one by one. I know the plan is to make the sidebar sections collapsible (#692) and perhaps to show/hide each section. @yair100?

**Comment by yaichenbaum** [comment]
@gave92 Thats correct, we will likely add the option to unpin sections, but we don't plan to let the user unpin individual cloud providers.
