### ISSUE TITLE
"Open Folder" Bug

### ISSUE THREAD

**Issue by LawMontagut** [files-community/Files#3567]
**Describe the bug**
App crash when I try open a folder.

**To Reproduce**
1. Open the App
2. Double Click on a folder
3. App crash

**Expected behavior**
See folder content.

**Desktop (please complete the following information):**
Edición	Windows 10 Pro
Versión	20H2
Se instaló el	‎28/‎01/‎2021
Compilación del SO	19042.804
Experiencia	Windows Feature Experience Pack 120.2212.551.0
"FIles" Version: 1.2.2.0

**Additional context**
The problem is constant.

**Log file**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5976931/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/5976932/debug.txt)

**Comment by Kroneaux** [comment]
I have the same issue, but it doesn't happen if I browse with the keyboard (hit Enter on folders instead of double-click).

**Comment by gave92** [comment]
Hopefully the same as #3504.
- Could you check if the crash happens also if you put the current folder in Grid View before going to that folder?
- Could you check if the crash happens also if you enable the "open items with one click" option in Files settings?
- Do get a notification saying "something went wrong" when the crash happens? (I'm guessing not)

**Comment by LawMontagut** [comment]
> Thanks for this report. This is a known issue with 1.2.2 and looks like #3504 which should be now fixed.
> 
> * Could you check if the crash happens also if you put the current folder in Grid View before going to that folder?
> * Could you check if the crash happens also if you enable the "open items with one click" option in Files settings?
> * Do get a notification saying "something went wrong" when the crash happens? (I'm guessing not)
> 
> Merging with #3548/#3547

Thanks for reply, now I check that and this is the news:
1. I can "solve" the problem if I put another view like Grid, but I need do 4 clicks to open folders, the app blinks and be late to open.
2. With one click there is not problems.
3. I don´t see any notifications about that.
