### ISSUE TITLE
"Slow Right Click" Bug

### ISSUE THREAD

**Issue by LawMontagut** [files-community/Files#3568]
Describe the bug
Right click takes time to open the context menu.

To Reproduce

1. Open the App
2. Right Click on a folder or blank space.

Desktop (please complete the following information):
Edición Windows 10 Pro
Versión 20H2
Se instaló el ‎28/‎01/‎2021
Compilación del SO 19042.804
Experiencia Windows Feature Experience Pack 120.2212.551.0
"FIles" Version: 1.2.2.0

Additional context
The problem is constant.

Log file
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5976942/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/5976943/debug.txt)

**Comment by gave92** [comment]
Merging with #2527
