### ISSUE TITLE
Crashing when opening OneDrive synced folder

### ISSUE THREAD

**Issue by TineSvete** [files-community/Files#3570]
**Describe the bug**
When trying to open OneDrive (or OneDrive Business) folder the program crashes. Behavior is the same in synced and 'placeholder' folders. Opening files on OneDrive root works fine, opening folder crashes every time I tried.

**To Reproduce**
1. Click "OneDrive" folder on tree structure.
2. Double-click any folder
3. Boom

**Expected behavior**
No crash :)

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS Version: [19042.804]
 - App version: [v1.2.2.0]

**Additional context**
N/A

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5977525/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5977526/debug_fulltrust.txt)

**Comment by gave92** [comment]
And again the dreaded ArgumentOutOfRangeException.. thanks for this report, merging with #3531 (same stacktrace)

**Comment by gave92** [comment]
@TineSvete could you check if enabling "open files with a single click" option in Files settings "fixes" the issue? Thanks!

**Comment by TineSvete** [comment]
Yes, 'single-click' option seems to work OK in this scenario.
