### ISSUE TITLE
Crashes When trying to see ongoing tasks

### ISSUE THREAD

**Issue by pandu200** [files-community/Files#3571]
**Describe the bug**
Program crashes when trying to see ongoing tasks when deleting a folder.

**To Reproduce**
1. Select a file / folder
2.  Delete it
3. Click on ongoing tasks
4. Crash
**Expected behavior**

**Desktop (please complete the following information):**
 - OS Version: [ Windows 10 1903 18362.356]
 - App version: [v1.22.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?
Yes.

LOG FILE
[debug.txt](https://github.com/files-community/Files/files/5977677/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5977678/debug_fulltrust.txt)

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`, you should see a file in this directory called debug.txt or/and debug_fulltrust.txt.

**Comment by yaichenbaum** [comment]
@pandu200 Is this still an issue in v1.3?
