### ISSUE TITLE
Add group by feature to folders

### ISSUE THREAD

**Issue by koushikb19** [files-community/Files#3577]
**Is your feature request related to a problem? Please describe.**
When there a lot of files and folders in a file, it is useful to have a group by feature which will group files and folders together just like in the window's default file explorer

**Describe the solution you'd like**
I want the files and folders in a directory to be grouped by a catogory.

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by gave92** [comment]
Thanks for the suggestion. Merging with #1874
