### ISSUE TITLE
Crash when double clicking certain folders (but not when right clicking -> open)

### ISSUE THREAD

**Issue by jojos38** [files-community/Files#3579]
**Describe the bug**
When double clicking some folders (not all of them!) such as Program Files (x86) the app shows the loading bar working at the top of the window and then crash after 2 seconds or so.
Right clicking the folder and pressing "Open" does not crash however.

**To Reproduce**
Open the app
Double click on C drive
Double click on Program Files (x86) or any other folder that causes a crash

**Expected behavior**
The folder to open. (like when I right click and press open)

**Screenshots**
Not applicable

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Pro 20H2 build 19042.804
 - App version: v1.2.2.0

**Additional context**
 - All settings left by default
 - I tried to repair / reset / reinstall the app, didn't fix the issue
 - I know this is a duplicate from other posts but I also provided a Crash Dump which thought might be useful to find the issue...
[Files.exe.6836 CrashDumps.zip](https://github.com/files-community/Files/files/5978337/Files.exe.6836.CrashDumps.zip)
[debug.txt](https://github.com/files-community/Files/files/5978338/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5978339/debug_fulltrust.txt)

**Comment by gave92** [comment]
Thanks for the report. Merging with #3525, description matches the video posted on that issue.
