### ISSUE TITLE
Shared Printers

### ISSUE THREAD

**Issue by perplexityjeff** [files-community/Files#3582]
When navigating to a computer that is sharing a printer on the network in the File Explorer you are able to do `\\<computername>` and see not only the file shares if they are available you can as well see the printers if they are shared. 

When right-clicking on that printer you are able to Install it for that user. 

This is a function that I would love to see in Files as well. Files (1.2.2) currently only lists the shares and not the printers.

Below is an example from a computer that is sharing folders and printers.

![printers](https://user-images.githubusercontent.com/19505844/107929066-6c156700-6f79-11eb-81d7-ae03500612d1.png)

**Comment by Josh-65** [comment]
Is this still an issue?

**Comment by perplexityjeff** [comment]
Hi @Josh-65,

Shared Printers are still not visible in version 2.3.12. When going to the network path using \\<computername> it simply does not list printers.

**Comment by yaira2** [comment]
@perplexityjeff thank you for the update, can you open a new feature using the template so that we can track this better?
