### ISSUE TITLE
App crashes or freezes when plugging in, ejecting or removing a flash drive with multiple partitions

### ISSUE THREAD

**Issue by ma-er233** [files-community/Files#3584]
(English is not my native language, please excuse my grammar and spelling errors. Thanks!)

**Describe the bug**
App crashes or freezes when plugging in, ejecting or removing **a flash drive with two (and above) partitions**. It happens very often.

**To Reproduce**
 - Method A: Open the app, plug in a flash drive which has multiple partitions, then the app will crash or freeze.
 - Method B: Eject or physically remove the flash drive which has multiple partitions, then the app will crash or freeze.

**Expected behavior**
 - When I plug in the flash drive, all the partitions of the drive should be listed without crashing or freezing.
 - When I eject or physically remove the drive, all the partitions should disappear from the list without crashing or freezing.

**Screenshots**
 - Crash when ejecting the drive:
https://user-images.githubusercontent.com/79030457/107971041-eb904e00-6fec-11eb-8707-4415fdce043c.mp4
 - Crash when plugging in the drive:
https://user-images.githubusercontent.com/79030457/107971292-42962300-6fed-11eb-8b69-1172c86aa794.mp4
 - Freeze when removing the drive:
https://user-images.githubusercontent.com/79030457/107971516-8a1caf00-6fed-11eb-8e33-b8effc2fafb4.mp4
 - Crash notification:
![crash notification](https://user-images.githubusercontent.com/79030457/107971750-d36cfe80-6fed-11eb-96b5-1d8115df1066.png)

(And there is a weird phenomenon when the drive was successfully ejected, but 
I failed to reproduce it.)
![1](https://user-images.githubusercontent.com/79030457/107971804-e54ea180-6fed-11eb-9714-ecd0cc879ee3.png)

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 Home   Version 20H4   Build 19042.804]
(I re-installed the system about a month ago, now it’s smooth and stable)
 - App version: [v1.2.2.0]
(latest in the Microsoft Store till this bug report was written)

**Additional context**
(When the app "crashes", the window disappeared and showed a crash notification. When "freezes", the sidebar stops working. And if you click anything in the homepage, the page will go blank. But the animations still work, the window can still be moved and if you click the “+” button to create a new tab, everything will go back to normal.)
(Crashes are the most common, freezes are rarer)

[4-7 are some findings during my attempt to reproduce. They may be not quite reliable as the crashes and freezes happen so randomly.]
1. It only happens when plugging in, ejecting or removing a USB flash drive with multiple partitions. And it won't happen when plugging in, ejecting or removing a flash drive with a single partition or removable HDD with single or multiple partitions.
2. No matter in what method that I choose to eject, it will crash or freeze. 
The methods I've tried including: (in app) right-click the drive in homepage or in the list on the sidebar;
(in explorer) right-click the drive and click eject in This PC and sidebar and the eject button on taskbar; 
(in diskpart) select the volume and "remove all dismount".
3. If the window of the app is minimized before plugging in, eject or remove the drive, it won’t crash or freeze.
4. If there are several windows, mostly only the active one or the newly created one will crash. But sometimes they crash randomly.
5. If there are several tabs, the crashes and freezes will be somehow less likely to happen.
6. If you are in a folder or drive instead of the home page, the crashes and freezes will be somehow less likely to happen.
7. I've tried different combinations of file system and partition amount and found that both FAT32 and exFAT will cause crashes and freezes. While NTFS is somehow less likely to cause crashes or freezes. And it tends to cause freezes instead of crashes.

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5982845/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5982848/debug_fulltrust.txt)

Many thanks to you guys for creating this beautiful software!

**Comment by gave92** [comment]
Thanks for the report. In the log files it has the same stacktrace as #3531.

**Comment by gave92** [comment]
@ma-er233 would you be willing to try the following?
- Delete the two log files
- Trigger the crash again
- Post the new log files

**Comment by ma-er233** [comment]
@gave92    Here:
 - Log 1:
[1 debug.txt](https://github.com/files-community/Files/files/5984822/1.debug.txt)
[1 debug_fulltrust.txt](https://github.com/files-community/Files/files/5984823/1.debug_fulltrust.txt)
I turned on the app, plugged in the drive, then ejected. And it crashed.

 - Log 2:
[2 debug.txt](https://github.com/files-community/Files/files/5984828/2.debug.txt)
[2 debug_fulltrust.txt](https://github.com/files-community/Files/files/5984829/2.debug_fulltrust.txt)
I turned on the app, plugged in the drive, then it crashed.

 - Log 3:
[3 debug.txt](https://github.com/files-community/Files/files/5984831/3.debug.txt)
[3 debug_fulltrust.txt](https://github.com/files-community/Files/files/5984832/3.debug_fulltrust.txt)
I plugged the drive in, turned on the app, then removed the drive without ejecting, And it crashed.

**Comment by ma-er233** [comment]
Crashes can still be triggered in the same way in v1.3.0.0. But they're much rarer to happen.

**Comment by AndrewLaganaro** [comment]
Just happened to me right now when plugging a regular flash drive with only one partition (regular FAT32 partition for flash drives)

Random crashes algo occur when new folders or files are created or when I press "update" (F5) on the program.

**Comment by yaichenbaum** [comment]
@ma-er233 is this still an issue in v2.3.11?

**Comment by ma-er233** [comment]
@yair100 No, it no longer crashes or freezes when handling my flash drives. But there are still some issues:
- After ejecting and unplugging a flash drive, the drive list sometimes won't update:
![5](https://user-images.githubusercontent.com/79030457/189397534-7d3fdc32-1e43-4114-abc6-5ba92f0acf18.png)
Click on one of them and the app will return this prompt: 
![image](https://user-images.githubusercontent.com/79030457/189398084-270cf329-412b-4e6c-8307-7e4892324cc1.png)
But now if I plug in another thumb drive and click on them, it will open the newly plugged drive without updating the name or the free space information. Refreshing the homepage will update the free space information, but still not the list and names.
![image](https://user-images.githubusercontent.com/79030457/189399521-a6f3bfb7-6777-4dd0-a0d7-cdc6397cc174.png)
(Flash drives with both single and multiple partitions will trigger this.)

- Often free space information won't show up correctly on one of the partitions:
![image](https://user-images.githubusercontent.com/79030457/189396561-e88fa59c-ba13-4c93-b66a-94930a7c38f1.png)
![1](https://user-images.githubusercontent.com/79030457/189393672-86294c6f-5be7-43fc-98c8-9f3013706cb7.png)
![3](https://user-images.githubusercontent.com/79030457/189393662-9c901e89-3da6-4cc3-a387-8f6a2e752a44.png)
(Happens only when plugging in a removable hard drive or thumb drive with multiple partitions, like this one.)
![image](https://user-images.githubusercontent.com/79030457/189394160-67ef60ac-8849-4832-aa37-0f7b6c6be44b.png)

Here are the log files:
[debug.log](https://github.com/files-community/Files/files/9537380/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9537381/debug_fulltrust.log)

Operating system version: Windows 10 Home Version 21H2 Build 19044.1889
App version: 2.3.11.0

**Comment by gave92** [comment]
Thanks for the update. Closing this in favor of #6439.
