### ISSUE TITLE
Double click issue

### ISSUE THREAD

**Issue by koosha72** [files-community/Files#3585]
I've to systems one laptop and another pc.
both of them use AMD Ryzen and Zen 2.
On my laptop the app works perfectly. But on my pc it crashes when I double click on a folder. If I right click and select open it will open without any problems. And if I change my settings so that folders open with a single click there will be no problem either.
So clearly this is a problem with double click not opening folders

Edit: It seems that this problem only persists in details layout. Double click works fine on Grid view layout.

**Comment by Ein-Tim** [comment]
This is already tracked in #3457.

**Comment by gave92** [comment]
Thanks for the report @koosha72. Merging with #3547
