### ISSUE TITLE
Renaming of system drives.

### ISSUE THREAD

**Issue by dustojnikhummer** [files-community/Files#359]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Currently, every picked up local (not external) drive, including Network Drives, gets called "Local Disk". Allow us to rename them just like explorer.exe.

**Describe alternatives you've considered**
Also separate network shares. Also off topic, add support for Back and Forward buttons on mice.

**Comment by yaichenbaum** [comment]
I think this can definitely be added as a long term goal, in the meantime I think we should detect the proper name instead of local disk.

**Comment by yaichenbaum** [comment]
@dustojnikhummer Is this still an issue in v0.7.5?

**Comment by dustojnikhummer** [comment]
Only one of my 3 internal drives got recognized, but with a proper name. 

Network drives are not shown and when manually opened they show an empty folder, explorer.exe does not

https://i.imgur.com/YgOM9bs.png

**Comment by yaichenbaum** [comment]
@dustojnikhummer Have you given Files UWP permission to access the file system?

**Comment by dustojnikhummer** [comment]
Yes
![image](https://user-images.githubusercontent.com/3268305/79692681-ce70de80-8266-11ea-9631-97da9936d146.png)

**Comment by yaichenbaum** [comment]
@dustojnikhummer Were there any specific parts of the older design that you liked better?

**Comment by dustojnikhummer** [comment]
Well, the main thing I don't like is the sidebar going all the way to the top. IRRC before it looked more like explorer, just with Fluent

**Comment by yaichenbaum** [comment]
I will admit that at first I felt the same about the new design, but after some time I realized the goal of the app is not just a rewrite of File Explorer, but rather a whole new take on what a File Explorer should be. Keeping that goal in mind, the new design makes a lot of sense.
The new design is still not done and we will do further work to make the tabs and sidebar more responsive when resizing the app.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #2239.
