### ISSUE TITLE
Program Crashes Constantly In Latest Update

### ISSUE THREAD

**Issue by cmactavish** [files-community/Files#3590]
**Describe the bug**
The program hangs and then closes when you try to navigate to anything beyond the root level of any drives.

**To Reproduce**
1. Open 'Files'
2. Click on any drive
3. Try to open a folder on that drive
4. Program hangs and eventually closes

**Expected behavior**
To navigate successfully to desired folder

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Home 19042.804
 - App version: [v1.2.2.0]

**Additional context**
I have some success navigating via the shortcuts on the left hand pane, but again, when you try to navigate around from there, it hangs and crashes.
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5986571/debug_fulltrust.txt)

**Log file**
Attached
[debug.txt](https://github.com/files-community/Files/files/5986575/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5986576/debug_fulltrust.txt)

**Comment by Ein-Tim** [comment]
@cmactavish 

Does this only happen in details mode or also in grid mode?

If it doesn't happen in grid mode it's already tracked in #3547. (:

**Comment by BobbyESP** [comment]
This bug happens to me too. The app crashes in anyways.

**Comment by BobbyESP** [comment]
i cant use the explorer

**Comment by gave92** [comment]
A known issue causing this has been fixed in version 1.2.3 which is now in beta testing and should be available to everyone in a few days.
In the meantime a workaround for some is to enable the "open items with one click" option in Files settings.

**Comment by BobbyESP** [comment]
ok, i will try
Thx for the info.

**Comment by BobbyESP** [comment]
Yup, now works. Thanks!4

**Comment by yaichenbaum** [comment]
@cmactavish This issue should be resolved with v1.3.
