### ISSUE TITLE
Close when double click on folders

### ISSUE THREAD

**Issue by Fvalley** [files-community/Files#3597]
**Describe the bug**
When i try to open a folder double clicking the whole program shuts down

**To Reproduce**
1. Go to the any direction with a folder
2. Double click on the folder
3. See error

**Expected behavior**
That the whole program doesnt close trying to open a folder

**Screenshots**
[Recording](https://user-images.githubusercontent.com/16322640/108121561-46847c80-70a3-11eb-83fe-05c28b0226dc.mp4)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.804
 - App version: v1.2.2.0

**Additional context**
I used explorer++ before using Files, maybe some of the configuration would affect Files, but not the native explorer

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`, you should see a file in this directory called debug.txt or/and debug_fulltrust.txt.
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5991663/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/5991664/debug.txt)

**Comment by gave92** [comment]
Thanks for this report. This is a known issue of version 1.2.2. Should be fixed in 1.2.3 which is releasing on the Store in a few days.
In the meantime the workaround is to enable the "open items with one click" option in Files settings.
