### ISSUE TITLE
Crash when opening a folder containing many Tiff files

### ISSUE THREAD

**Issue by NeigeDay** [files-community/Files#3598]
the application closes when inside a folder there are many tif format files in a folder, the error happens to me day by day and the only way to open those folders is by right clicking open in a new tab
[debug.txt](https://github.com/files-community/Files/files/5991884/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5991886/debug_fulltrust.txt)

**Comment by gave92** [comment]
Thanks for the report. Could you try the following?
- Delete the debug files
- Open Files and trigger the crash again
- Upload the new log files
Thanks!

**Comment by gave92** [comment]
@NeigeDay could you check if the issue is still present with the new version of Files (1.3)?
