### ISSUE TITLE
Double Click on a folder shuts down Files app

### ISSUE THREAD

**Issue by MarkkuMT** [files-community/Files#3599]
**Describe the bug**
 When I open Files, I can go to my directories etc. by clicking any of the options on the home page. Once in a directory, if I double click on a sub-directory or a file, the app shuts down after a few seconds. However, I can open the directory or file using a context click and context menu. When I change options to open folders or files with a single click, it works fine.

**To Reproduce**
1. Launch Files app.
2. On Home page, click a directory option
3. On selected directory double click a sub-directory or a file
4. App appears to be working on it but then shuts down after a a couple of seconds.
5. When I change options to open directories or files with a single click, it works fine

**Expected behavior**
I would expect the app to open the selected sub-directory or file if I double click on it.

**Screenshots**
No time for screenshots as app shuts down in a couple of seconds.

**Desktop (please complete the following information):**
 - OS Version: [ Windows 10 Home OS Build 19041.804]
 - App version: [v1.2.2.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app? Yes

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`, you should see a file in this directory called debug.txt or/and debug_fulltrust.txt.

[debug.txt](https://github.com/files-community/Files/files/5991876/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5991878/debug_fulltrust.txt)

**Comment by fbtwitter** [comment]
Adding for the problem behavior, 
the files app close whenever i press "double click" on the folder.
instead, the folder still can be open by using "enter" or by using "open new tab"

**Comment by gave92** [comment]
Thanks for this report. This issue should be fixed in version 1.2.3 coming to the Store in a few days. 
In the meantime the workaround is to enable the "open items with one click" option in Files settings.
