### ISSUE TITLE
External drives not supported

### ISSUE THREAD

**Issue by amda-phd** [files-community/Files#3600]
**Describe the bug**
The software freezes and closes after a few seconds whenever I try to reach any externally connected drive, like an Android tablet or a USB hard drive.

**To Reproduce**
1. Open files
2. Click any external unit
3. Try to browse its root contents

**Expected behavior**
I would expect to be able to browse the files and folders of external drives.

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version:  Windows 10 20H2 19042.804
 - App version: 1.2.2.0

**Additional context**
I connect my external drives through a USB dock, but Windows Explorer accesses them without any issue

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5992075/debug.txt)

**Comment by rafifos** [comment]
Probably a duplicate of https://github.com/files-community/Files/issues/3504
Can you try to change the View Mode to Grid?

**Comment by gave92** [comment]
Thanks for this report. Merging with #3531, same stacktrace.

**Comment by amda-phd** [comment]
Grid view seemed to do the trick for a couple of steps. As soon as I dived
a couple of folders into the external drive, the software went into freeze
and then shut down mode, and couldn't  be opened back.
