### ISSUE TITLE
Add some advanced paste options

### ISSUE THREAD

**Issue by ma-er233** [files-community/Files#3601]
(English is not my native language, please excuse my grammar and spelling errors. Thanks!)

**Is your feature request related to a problem? Please describe.**
RoboCopy is a good tool. And it's a built-in function in the Windows 10. But it has no GUI, which certainly prevents a lot of people benefiting from it.
So why not add some advanced paste options based on RoboCopy to make the copy procedure easier?

**Describe the solution you'd like**
In the right-click menu, add a ">"button to the "Paste" option. If I click the left side of that option, the app will copy files as usual. And if I click the ">"button, a sub-menu with advanced paste options will pop up.
As for the advanced paste options, here is an example:
![Paste options](https://user-images.githubusercontent.com/79030457/108149330-8ed88480-710d-11eb-8d8e-85e8674b522b.jpg)
Some reasons for these options:
 - "Update": replace the older files with newer one without asking the user. That should be useful when making some quick backups.
 - "Replace folders without merging": In explorer, folders with same names are merged by default. But sometimes I just want to replace it.
 - "Exclude temp files": there're always some .tmp files created by Photoshop and ~$ files created by Microsoft Office in my folders. And somehow they were not deleted after closing the program. They're often large or messy so it's quite annoying to delete them before copy.
(Though I'm not sure if these options are useful for the majority. Some discussions in the community might be great.)

**Describe alternatives you've considered**
Maybe we can integrate something like a simplified version of [ChoEazyCopy](https://github.com/Cinchoo/ChoEazyCopy) ?😂

**Additional context**
（I'm not quite familiar with the manners on writing a request. If I appear to be a bit rude, that's not my intention. Sorry for that.)

**Thanks!**

**Comment by yaichenbaum** [comment]
This seems like a useful feature, being that it's more of an advanced feature, what if it only showed when holding down the `shift` key?

**Comment by yaichenbaum** [comment]
This feature has been approved for development. Being that it's a bit of an advanced feature, it will only show when the menu is opened while holding down the `shift` key at the same time.

**Comment by ma-er233** [comment]
> This feature has been approved for development. Being that it's a bit of an advanced feature, it will only show when the menu is opened while holding down the `shift` key at the same time.

Thanks a lot!  (｡･ω･｡)

**Comment by yaichenbaum** [comment]
Files now includes a conflicts dialog, while it doesn't support every single option, the main ones are covered.
