### ISSUE TITLE
Files installation fails (0x8000ffff)

### ISSUE THREAD

**Issue by ANF-Studios** [files-community/Files#3604]
**Describe the bug**
The app installation fails:
> App installation failed with error message: Deployment Add operation with target volume C: on Package 49306atecsolution.FilesUWP_1.2.2.0_neutral_~_et10x9a9vyk8t from:  (Files-1.2.2.Msixbundle)  failed with error 0x8000FFFF. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues. (0x8000ffff)

**To Reproduce**
1. Run the installer
2. See error

**Expected behavior**
Application installs without any errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/68814933/108194597-cf6fd800-70e4-11eb-8b59-0482cf8a1630.png)

![image](https://user-images.githubusercontent.com/68814933/108194650-de568a80-70e4-11eb-8912-018058bf674f.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 x64 10.0.19042
 - App version: 1.2.2

**Additional context**
The error keeps occurring regardless.

**Log file**
There is no log file

**Comment by ANF-Studios** [comment]
Oh and, I installed it through Choco for now and it initially failed. I was then able to fix that with issue [600](https://github.com/chocolatey/ChocolateyGUI/issues/600#issuecomment-437615284). I was using the CLI, but they do the same thing at the end of the day.

![image](https://user-images.githubusercontent.com/68814933/108195419-ba477900-70e5-11eb-9655-ec105db6e43c.png)

But that's not what the issue is about, it's that the msix bundle fails to install.

**Comment by yaichenbaum** [comment]
@ANF-Studios The msix installer doesn't include the dependencies, can you try using the app installer [here](https://files-community.github.io/package.github.io/Files.Package/Files.Package.appinstaller)?

**Comment by ANF-Studios** [comment]
> @ANF-Studios The msix installer doesn't include the dependencies, can you try using the app installer [here](https://files-community.github.io/package.github.io/Files.Package/Files.Package.appinstaller)?
Alright, so at first sight, I saw what you'd expect:
![image](https://user-images.githubusercontent.com/68814933/109381954-62f69500-78ab-11eb-970a-3e5453a3468e.png)
Now, when I pressed update (since, as mentioned earlier, I already had it installed):
![k5YGryabVo](https://user-images.githubusercontent.com/68814933/109382006-b5d04c80-78ab-11eb-9605-cfc81113dd6e.gif)

Now, I've been having this controversy that it succeeded because I already had it installed. But, there's that, it installed successfully.

**Comment by yaichenbaum** [comment]
@ANF-Studios Can you confirm that Files is launching correctly?

**Comment by ANF-Studios** [comment]
It does launch correctly and everything is working as expected.
![image](https://user-images.githubusercontent.com/68814933/109418549-eb9e2f80-7996-11eb-9577-d4550af670be.png)
