### ISSUE TITLE
[BUG] network drive crash

### ISSUE THREAD

**Issue by Neikon** [files-community/Files#3607]
**Describe the bug**
When click inside network drive, files closes it

**To Reproduce**
1. Click in a network drive
2. Maybe you can see a folder or whatever have the network drive
3. try to open a folder
4. App will close

**Expected behavior**
you should be able to browse without any problems regardless of whether the files are local or on another network device

**Screenshots**
![imagen](https://user-images.githubusercontent.com/1765319/108250958-2adaae00-7157-11eb-90a6-06a9b28e7d1e.png)
If i try to open "mdavid" folder app will close

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2 19042.804]
 - App version: [v1.2.2.0]

**Additional context**
This happend always, I can not use nothing on my LAN

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5997815/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5997816/debug_fulltrust.txt)

**Comment by gave92** [comment]
Thanks for this report. I'm positive the issue has been resolved in version 1.2.3 which is coming to the store in a few days.
In the meantime could you try enabling the "open items with one click" option in Files settings?

**Comment by Neikon** [comment]
> 
> 
> Thanks for this report. I'm positive the issue has been resolved in version 1.2.3 which is coming to the store in a few days.
> In the meantime could you try enabling the "open items with one click" option in Files settings?

It works fine with "open with one click". Good to know until the next version arrives. Thanks you.

**Comment by DrumSlayers** [comment]
By my side, opening network share freeze the File app and freeze the windows network stack (yes..)
Doesn't happen with Explorer.exe

**Comment by DrumSlayers** [comment]
You closed this thread but the mentioned one is not in english? bruh

**Comment by yaichenbaum** [comment]
@DrumSlayers This issue was closed as it was resolved in v1.3.

**Comment by DrumSlayers** [comment]
> @DrumSlayers This issue was closed as it was resolved in v1.3.

Oh ok nice, thank you
