### ISSUE TITLE
Libraries missing

### ISSUE THREAD

**Issue by andyfmidd** [files-community/Files#3611]
**Describe the bug**
None of my (self created) libraries are showing up: not in the navigation, nor in the details.
"System" libraries do appear.
No library options in context menu

**To Reproduce**
Just start the app.
Use the original explorer to confirm the library does exist.

**Expected behavior**
My Libraries to appear in the navigation bar.

**Screenshots**

**Desktop (please complete the following information):**
 -Windows 10 Insider preview 21313. Experience pack 321.2706.0.3
 - App version: 1.2.2.0

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app? Yes.
Cloud drives are shown.
I can't find an option to show/hide libraries. Or create/delete one.
Has all library support been removed?

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t
[debug.txt](https://github.com/files-community/Files/files/6001719/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6001721/debug_fulltrust.txt)

\LocalState`, you should see a file in this directory called debug.txt or/and debug_fulltrust.txt.

**Comment by gave92** [comment]
Support for libraries is not currently implemented. See #2709.
