### ISSUE TITLE
Can't change anything in folders with denied access

### ISSUE THREAD

**Issue by quhxl** [files-community/Files#3612]
**Describe the bug**
If you try to paste, change the name of a file or edit anything else in a folder you don't have access to you dont get an error message, no request for permission and nothing happens.

**To Reproduce**
1. Go to any Folder where you have don't have permissions
2. Change anything
3. Nothing happens

**Expected behavior**
I would expect an error message and a request for permission. (Like in the Windows Explorer, where you have to confirm with administrator rights)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 2004 19041
 - App version: 1.2.2

**Log file**
First error when I pasted a file into the folder and the second when tried to create a shortcut:
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6003310/debug_fulltrust.txt)

The other debug file seems inconspicuous

**Comment by gave92** [comment]
Merging with #3511 etc
