### ISSUE TITLE
Unable to copy/cut paste

### ISSUE THREAD

**Issue by OviiiOne** [files-community/Files#3615]
**Describe the bug**
Whenever I copy/cut paste anything I am only able to paste it on the Desktop, if I try to paste it in any other folder it just won't do anything.

**To Reproduce**
1. Go to any folder you have.
2. Right-click on an archive/shortcut within the folder and click on copy/cut
3. Go to a different folder and paste the archive(s).
4. Nothing will happen

**Expected behavior**
The archives are pasted in the new folder.

**Screenshots**
https://i.imgur.com/sNlQdim.gif (the same happens if you click copy instead of cut)

**Desktop:**
 - OS Version: Win 10 Pro 1909
 - App version: v1.2.2.0

**Additional context**
Restarting the app doesn't fix the problem

**Log file**
[debug.txt](https://github.com/files-community/Files/files/6005633/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6005634/debug_fulltrust.txt)

**Comment by yaichenbaum** [comment]
@OviiiOne is this still an issue in Files v2.0?
