### ISSUE TITLE
How to automatically switch from Details view to Grid or Tiles view for Thumbnails view and why the filename is incomplete when using grid mode

### ISSUE THREAD

**Issue by candrapersada** [files-community/Files#3616]
How to automatically switch from Details view to Grid or Tiles view for Thumbnails view and switching from Grid or Tiles view to Details view for folders?

**Comment by gave92** [comment]
Same as #2893?

**Comment by candrapersada** [comment]
> Same as #2893?

yes but for video and audio.

**Comment by gave92** [comment]
Automatic layout mode based on content is being implemented -> #3526
The issue of filenames being "cut" in gridview is tracked in #1033.
