### ISSUE TITLE
Files crashes when launching. Just installed

### ISSUE THREAD

**Issue by johnnydement** [files-community/Files#3618]
**Describe the bug**
Files crashes when launched

**To Reproduce**
1. Install Files
2. Click on 'launch'
3. See it die
4. Cry T_T

**Expected behavior**
Files works flawlessly and replaces explorer.exe

**Screenshots**
![image](https://user-images.githubusercontent.com/1867306/108446767-f5b98300-725e-11eb-8305-739c289e65f4.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.804 
 - App version: 1.2 MS Store & 1.2.2 github

**Additional context**
This happens every time I try to launch files, trieed reset ;)

**Log file**
[debug.txt](https://github.com/files-community/Files/files/6007146/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6007149/debug_fulltrust.txt)

**Comment by gave92** [comment]
Thanks for this report. Merging with #3531. Known issue with version 1.2.2.
