### ISSUE TITLE
Files crash immediately after install

### ISSUE THREAD

**Issue by bebeo92** [files-community/Files#3620]
**Files crash immediately after install**
Not sure what exactly the problem

**To Reproduce**
1. Go to ms store
2. Click on install files
3. Open it
4. Yayyyyyy. It crash

**Expected behavior**
Files run normal

**Screenshots**
![image](https://user-images.githubusercontent.com/9253836/108449756-98412880-7296-11eb-847d-b7970645eb15.png)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2]
 - App version: latest

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
[debug.txt](https://github.com/files-community/Files/files/6007298/debug.txt)

**Comment by gave92** [comment]
Thanks for this report. Merging with #3531. Known issue with version 1.2.2. Should be fixed in 1.2.3.
