### ISSUE TITLE
App crashes when opening any folder after manually entered a path

### ISSUE THREAD

**Issue by Under-estimate** [files-community/Files#3622]
**Describe the bug**
After manually enter a valid path in the path input box and press enter, double clicking on any folder attempting to open it will cause the app to crash. But it's possible to open a folder by selecting "open" in the right click menu.

**To Reproduce**
1. Click on the path input box.
2. Type or paste a valid path.
3. Press enter, Files will navigate to the path entered.
4. Open any folder in that path with double click.
5. The app freezes and then crashes.

**Expected behavior**
Files is expected to open the double-clicked folder, after the navigation in step 3.

**Screenshots (GIF)**
![troubleshoot](https://user-images.githubusercontent.com/55307932/108464348-e6682300-72ba-11eb-9e36-83774eb4864a.gif)

**Desktop**
 - OS Version: Windows 10 1903 18363.1379
 - App version: v1.2.2.0

**Additional context**
The problem will always occur when performing the steps described above.

**Log file**
I noticed this problem today(19 Feb 2021), but the log file does not seems to contain any information associated with errors that 
occurred today.
[debug.txt](https://github.com/files-community/Files/files/6007962/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6007963/debug_fulltrust.txt)

**Comment by gave92** [comment]
Thanks for this report. Known issue with version 1.2.2. Should be fixed in 1.2.3.
In the meantime a workaround is to enable the "open items with one click" option in Files serttings.
