### ISSUE TITLE
Recycle bin won't refresh automatically after clearing it

### ISSUE THREAD

**Issue by weiba0** [files-community/Files#3623]
回收站 清空后 不会自动刷新
希望增加 磁盘 自定义图标功能

**Comment by gave92** [comment]
Thanks for the report. Could you post the app version and the app's log files?

**Comment by weiba0** [comment]
rightapp V1.2.2.0








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "files-community/Files"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月19日(星期五) 下午2:23
收件人:&nbsp;"files-community/Files"<Files@noreply.github.com&gt;;
抄送:&nbsp;"尾巴"<1252978231@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [files-community/Files] 清除回收站不会自动刷新 (#3623)





 
Thanks for the report. Could you post the app version and the app's log files?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

debug.txt (6.5K, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=5f6365363dd7c99a568dcb7c1631044a07075c50060653544c5a500f091c02515106480f095201485354500e075352525200530630383601040110511e454e11615e&t=exs_ftn_download&code=ace6016e




debug_fulltrust.txt (204.1K, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=2a643934baaace9c558a977e1e65004c565608015b0601024f070e565b480650575c140d5e00064e575500075c56065404515f0c3876320707064c536703470f0e104b414b111c171a103909&t=exs_ftn_download&code=bd948e2c

**Comment by gave92** [comment]
My best guess is that it's a consequence of #3123
