### ISSUE TITLE
Crash when accessing Recycle Bin from side bar

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#3624]
App just crashes, 100 % reproduceable .

[debug_fulltrust.txt](https://github.com/files-community/Files/files/6008734/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6008735/debug.txt)

Files Version : 1.2.3

**Comment by boscorelly** [comment]
same here.
[debug.txt](https://github.com/files-community/Files/files/6009207/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6009208/debug_fulltrust.txt)

**Comment by boscorelly** [comment]
2021-02-19 10:40:18.6020|ERROR|.ctor|The UTC time represented when the offset is applied must be between year 0 and 10,000.
Parameter name: offset|System.ArgumentOutOfRangeException: The UTC time represented when the offset is applied must be between year 0 and 10,000.

**Comment by gave92** [comment]
Fixed in 1.2.4 (#3295)
But if 1.2.3 is not yet on the store, this fix could be backported... @yair100 ?

**Comment by boscorelly** [comment]
1.2.4 is published for insiders ?

**Comment by yair100** [comment]
> Fixed in 1.2.4 (#3295)
> But if 1.2.3 is not yet on the store, this fix could be backported... @yair100 ?

@gave92 v1.2.3 isn't going to be a release so the fix should be part of the v1.3 release.
