### ISSUE TITLE
Lack of file transfer progress information 

### ISSUE THREAD

**Issue by cinnyboy** [files-community/Files#3625]
**Describe the bug**
During file transfer operations there is no progress bar or any kind of information.

**To Reproduce**
1. Go to any drive and pick a file.
2. Copy or move it to another location.
3. Check lower right corner and open the transfer window.
4. The transfer progress stays at 0%. However there is confirmation when the operation ends.

**Expected behavior**
Clear and constantly refreshed progress bar.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Home 20H2 19042.804
 - App version: 1.2.2.0

**Log file**
[debug.txt](https://github.com/files-community/Files/files/6009111/debug.txt)

**Comment by gave92** [comment]
Merging with #2523. Progress currently only updates when copying multiple files.
