### ISSUE TITLE
Error on opening subfolder of any folder

### ISSUE THREAD

**Issue by ajafov98** [files-community/Files#3626]
**Describe the bug**
Crashing when accessing subfolder of a folder

**To Reproduce**
1. Go to any folder from sidebar or drives
2. Try to open a subfolder
3. Crashing without a message

**Expected behavior**
Had to open the subfolder

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS Version: Version	10.0.19041 Build 19041
 - App version: v1.2.2.0

**Additional context**
The problem occurs every time I try to open subfolder of a folder
Error Log from Microsoft Event Viewer
[error.txt](https://github.com/files-community/Files/files/6009303/error.txt)

**Log file**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6009271/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6009272/debug.txt)

**Comment by gave92** [comment]
Thanks for this report. This should be fixed in version 1.2.3 coming to the store in a few days.
In the meantime the workaround is to enable the "open items with one click" option in Files settings.
