### ISSUE TITLE
Issues with Google Drive and Onedrive folders

### ISSUE THREAD

**Issue by sh1nyfox** [files-community/Files#3627]
**Describe the bug**
When trying to open synced Google Drive folders in the app it causes a total crash. 

**Expected behavior**
The main Google Drive folder shows files and folders fine, but then trying to open a folder within that causes the app to crash entirely. Attempted same thing with OneDrive and get same behaviour. 

**Desktop (please complete the following information):**
 - OS Version: 19042.804
 - App version: 1.2.2.0

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState
[debug.txt](https://github.com/files-community/Files/files/6009729/debug.txt)
`, you should see a file in this directory called debug.txt or/and debug_fulltrust.txt.

**Comment by gave92** [comment]
Thanks for this report. This issue should be fixed in 1.2.3.
Please add the log files to the issue description so we can verify.
Could you try to enable the "open items with one click" option in Files settings and see if it solves this issue?
