### ISSUE TITLE
Rectangle selection sometimes selects parent directory

### ISSUE THREAD

**Issue by winston-de** [files-community/Files#3633]
**Describe the bug**
Rectangle selections seems to select the parent directory when you select then unselect an item a few times. 

**To Reproduce**
1. Go to folder
2. Use rectangle selection to select/deselect a few times
3. Right click, see menu for parent folder
5. Open preview pane, see no preview/details available although it should be

**Expected behavior**
Item dragged over should be selected.

**Screenshots**

https://user-images.githubusercontent.com/59544401/108548222-62a13d00-72a0-11eb-962d-bcbaa45af2af.mp4

**Desktop (please complete the following information):**
 - OS Version: 19043.844
 - App version: 1.2.3.0

**Additional context**
This is a minor issue, and only occurs through irregular usage.

**Comment by BanCrash** [comment]
@winston-de could you confirm that this is no longer an issue? I didn't see it on a normal use and I tried your steps but I wasn't be able to replicate it.

**Comment by winston-de** [comment]
Doesn't seem like it
