### ISSUE TITLE
Hola desde este nuevo Files, no puedo ejecutar las aplicaciones .exe tampoco tengo entorno r.e.d.

### ISSUE THREAD

**Issue by mcervantesr** [files-community/Files#3635]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`, you should see a file in this directory called debug.txt or/and debug_fulltrust.txt.

**Comment by BobbyESP** [comment]
Hola. No soy del equipo de Files, pero te recomiendo que en el formulario completes todos los pasos que se necesitan para que el bug ocurra y lo hagas en inglés, ya que si no, el equipo (de Files) lo eliminará (o eso creo). Graciass

**Comment by BobbyESP** [comment]
De todas formas ya hay un caso parecido al tuyo en #3607 así que puedes mirar ahí si eso es lo que te ocurre.

**Comment by mcervantesr** [comment]
Gracias eso hare y buscare el link de lo que me cuentas ... a ti te
funciona las opciones de red y puedes instalar aplicaciones desde el mismo
Flie, como se hace normalmente con el Explorador de Windows.




Atte,

Ing. Angel Cervantes Ramirez

ArasystemPeru

RPM: #998566920  Whatsapp: +51998566920
E-mail: arasystemperu@gmail.com  E-mail: mcervantesr@gmail.com
Enviado desde Linux Debian

*P* *Evite imprimir, piense en su compromiso con el Medio Ambiente*


La información contenida en esta comunicación, no representa el
consentimiento de Arasystem Perú para la celebración de un contrato, por lo
tanto cualquier información brindada en esta comunicación, solo representa
las opiniones y puntos de vista del autor, no obligando a Arasystem Perú.

Este mensaje se encuentra dirigido exclusivamente para uso del destinatario
previsto y contiene información confidencial y/o privilegiada. Si Ud. no es
el destinatario al que se dirigió el mensaje, se le notifica por este medio
que la divulgación, copia, distribución o cualquier actividad tomada a
partir del contenido de este mensaje se encuentra terminantemente prohibida
y es sancionada por la ley. Si Ud. ha recibido este mensaje por error por
favor proceda a eliminarlo y notificar inmediatamente al remitente.

**Comment by bl-ue** [comment]
>ya que si no, el equipo (de Files) lo eliminará (o eso creo).

@BobbyESP just FYI, they won't delete it, they'll just close it if they don't get cooperation from the OP, in English :+1:

**Comment by BobbyESP** [comment]
Okk

**Comment by yaichenbaum** [comment]
@mcervantesr Can you fill out the issue template?
