### ISSUE TITLE
Fatal crash opening the app

### ISSUE THREAD

**Issue by Xelit3** [files-community/Files#3640]
**Describe the bug**
Application crashes once is opened, no more information provided by the app
**To Reproduce**
1. Open the app

**Expected behavior**
I expect to open the app without errors

**Screenshots**
![image](https://user-images.githubusercontent.com/55638917/108577183-6f657580-7320-11eb-9176-873cbb183726.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2
 - App version: [v0.11.0]

**Additional context**
I remember to have installed QuickLook which has compatibility with Files, and then unistalled, since then seems is crashing but not sure if it's a possible reason or not.

QuickLook was also installed from Microsoft Store

**Log file**
[debug.txt](https://github.com/files-community/Files/files/6013862/debug.txt)

**Comment by gave92** [comment]
Merging with #3531
