### ISSUE TITLE
Files Crashing while opening folders

### ISSUE THREAD

**Issue by shgaurav** [files-community/Files#3643]
**Describe the bug**
I believe Files is the most well-designed Windows 10 Application I have used. Being a developer myself, I acknowledge and understand the effort and time that went into this. I am facing an issue with Files where when I go into Folders, the Files app suddenly crashes. And I have tried to locate a pattern but I feel it's happening at random times with random folders (in documents, different drives etc).

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Documents
2. Click on a folder
3. The application would crash.

**Expected behaviour**
I believe the application should not crash this often. I love the design and the overall aesthetics. I have been going back and forth between default explorer and this because of this issue. I am curious if anyone else has reported a bug as well?

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 Home version 20H2 build 19042.804]
 - App version: [v1.2.2.0]

**Additional context**
Yes, the problem occurs even after restarting the application.
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6014081/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6014082/debug.txt)

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`, you should see a file in this directory called debug.txt or/and debug_fulltrust.txt.

**Comment by gave92** [comment]
Thanks for this report. This issue has been fixed in the development version.
As a workaround you can enable the "open items with one click" option in Files settings.
