### ISSUE TITLE
Add a "Shortcut" dialog

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#3644]
**Is your feature request related to a problem? Please describe.**
Not related to a problem

**Describe the solution you'd like**
Microsoft Teams and Discord for example have these nice dialogs which display all shortcuts. Would be nice to have something similar for Files as well as some point, since the amount of shortcuts is getting bigger and bigger.

Teams:
![image](https://user-images.githubusercontent.com/17484252/108589577-3e586580-735f-11eb-8df8-439c50920f2f.png)

Discord:
![image](https://user-images.githubusercontent.com/17484252/108589595-58924380-735f-11eb-8c11-16a76bfda2c2.png)

**Comment by gave92** [comment]
#1660?

**Comment by R3voA3** [comment]
I hate it. I searched for "shortcut" and either I missed this one or it didn't show up. Sorry!

**Comment by gave92** [comment]
No problem xD
