### ISSUE TITLE
Pressing F1 should bring up the Files Wiki

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#3645]
**Is your feature request related to a problem? Please describe.**
No problem

**Describe the solution you'd like**
File Explorer opens a google search when pressing F1 with related help topics.
Files should open up the Files Wiki or Files Homepage when pressing F1

**Comment by yaichenbaum** [comment]
@R3voA3 This enhancement was implemented with #3647.

**Comment by R3voA3** [comment]
Awesome =)
