### ISSUE TITLE
[Bug report] - crashing on opening any folder

### ISSUE THREAD

**Issue by Notatea** [files-community/Files#3646]
<!-- 
🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨

**Describe the bug**

Program is crashing, when trying to open any folder on any disk

**To Reproduce**
1. Open the program
2. Click on any disk
3. Open any folder
4. Program closes

**Expected behavior**
See the inside of a folder

**Screenshots**
https://user-images.githubusercontent.com/61663117/108589581-a1e69100-7367-11eb-8b66-880ba7cc7773.mp4

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Pro 21H1 19043.844 (Insider preview Beta channel)
Windows Feature Experience Pack 120.2212.2020.0

 - App version: [v1.2.2.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?
Yes, the problem remains even after restarting the PC

**Log file**

[debug_fulltrust.txt](https://github.com/files-community/Files/files/6014432/debug_fulltrust.txt)

**Comment by Notatea** [comment]
I noticed that "open with one click" works as a wokraround

**Comment by Notatea** [comment]
https://user-images.githubusercontent.com/61663117/108589847-1e2da400-7369-11eb-9c68-aa987191d06d.mp4

[debug_fulltrust.txt](https://github.com/files-community/Files/files/6014442/debug_fulltrust.txt)

**Comment by gave92** [comment]
Thanks for this report. This issue has been fixed in the development version.
As you know the workaround for now is to enable the "open items with one click" option in Files settings.
