### ISSUE TITLE
Open new tab with middle mouse click

### ISSUE THREAD

**Issue by Razblade** [files-community/Files#3649]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by Razblade** [comment]
esta muy bueno el explorador, una joya, lo único que me molesta un poco es la opción de abrir en una nueva pestaña, en un explorador de internet sea opera, firefox o el que sea es posible abrir en una nueva pestaña con el botón central del ratón mientras que en files no, para la próxima versión sería bueno que piensen en la posibilidad de agregar esta función mas que nada para aumentar el flujo de trabajo con el explorador de archivos, ya que hacer esto es mucho mas rápido y sencillo que hacer click derecho y seleccionar la opción de abrir en una nueva pestaña. desde ya muchas gracias y espero que sigas trabajando en éste magnífico explorador de archivos.

**Comment by yaichenbaum** [comment]
@Razblade This feature is already implemented in the latest version of Files. You might want to check if you are running an updated version.
