### ISSUE TITLE
Close constantly with big folders

### ISSUE THREAD

**Issue by dieggono** [files-community/Files#3650]
**Describe the bug**
The app close constantly when I try to open folders with a lot of files or heavy files

**To Reproduce**
1. Go to 'My documents'
2. Double Click on 'Photography'
3. App close

**Expected behavior**
I expect to open those folders and get access to my files

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10 20H2 19042.804
 - App version: 1.2.2.0

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6015214/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6015215/debug.txt)

**Comment by gave92** [comment]
Thanks for this report. This issue has been fixed in version 1.3 which is going to be available on the store in a few days.
In the meantime as a workaround you can enable the "open items with one click" option in Files settings.
