### ISSUE TITLE
Include access for network locations

### ISSUE THREAD

**Issue by dieggono** [files-community/Files#3651]
**Is your feature request related to a problem? Please describe.**
I can't get access for Network locations

**Describe the solution you'd like**
Get access in the UI for network locartions

**Describe alternatives you've considered**
I come back to file explorer

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by gave92** [comment]
Support for network locations has been added in 1.3 which is going to be released on the store in a few days 👍
