### ISSUE TITLE
Bug: Launching Files from PowerShell prevents entering additional commands

### ISSUE THREAD

**Issue by HydrogenDeuterium** [files-community/Files#3652]
**Describe the bug**
run files in powershell terminal,the terminal is fixed and could do nothing before close the window.

**To Reproduce**
call files through pwsh(cmd no simailar problem)

**Expected behavior**
terminal open the window,and ready to my next input

**Screenshots**
![image](https://user-images.githubusercontent.com/36532302/108600281-45b85700-73d1-11eb-87e2-87711998e151.png)

**Desktop (please complete the following information):**
 - OS Version: win 10 2004
 - App version: [v0.11.0]1.2.2.0

**Additional context**
when i choose to run with"start-process files",it works as i wished.
another uwp app works so,and the developer asked me to run it with start-process,
i think it's a tiny issue and easy to fix(unforturnly,i know lettle about uwp app develop,otherwise i will fix it myself)

**Comment by enisn** [comment]
As a workaround using launching with 'start' works well

```bash
start files
```

**Comment by Josh-65** [comment]
Is this still an issue?

**Comment by yaira2** [comment]
Yes

**Comment by Lukiluc29** [comment]
I reproduced your action and whether I write "files" or "start files" it opens with version 2.4.80

**Comment by heftymouse** [comment]
I looked into this some more, and it seems it's not an issue exclusive to Files - I can reproduce this on many packaged apps made with a variety of frameworks and languages. I'm still not clear on what exactly is causing this.

**Comment by hishitetsu** [comment]
I found a PowerShell issue on this.
https://github.com/PowerShell/PowerShell/issues/9970

**Comment by hishitetsu** [comment]
As a side effect of Leave app running, if Files is launched from Powershell while it is in the background, the prompt returns immediately.

**Comment by yaira2** [comment]
Considering this issue is with the platform, and the fact that the issue doesn't occur when Files is open in the background, I think we no longer need to track this issue. For further updates, we suggest subscribing to the issue on the PowerShell repo https://github.com/PowerShell/PowerShell/issues/9970.
