### ISSUE TITLE
allow to change directory at cli calling

### ISSUE THREAD

**Issue by HydrogenDeuterium** [files-community/Files#3653]
**Is your feature request related to a problem? Please describe.**
when i am working in cli,sometimes i want to have work done in gui for effciency.so i would like use `explorer {directory}` to do so. when i changed to files uwp,i found i can't do so.

**Describe the solution you'd like**
when calling app in cli,add a parameter to choose which directory to open.

**Describe alternatives you've considered**
still using old explorer,and suffer for its ui.

**Additional context**
when i type `files C:/`,i would like to have the wiondow oped like so:
![image](https://user-images.githubusercontent.com/36532302/108600872-6cc45800-73d4-11eb-945a-fa824fb3d5ba.png)

i think it's not a very personal demand and it can improve the cli performance and benefit many people.

**Comment by gave92** [comment]
Hi thanks for this report. This feature is implemented already but atm only supports absolute folder paths.
Does something like `files c:\\users` not work for you?

**Comment by HydrogenDeuterium** [comment]
@gave92 yes it does work after if i changed "/" to"\".
in fact,`files c:\\users` not work,but`files c:\users` works.
i expected it will make no difference because powershell seems always auto change it.
also,if it's possible to use `files .`,`files ..`?(current directory and parent directory)
it is very useful to open a seslected folder at work,
ps: may i ask what does "atm" means? i guess it does not means atmosphere or Automated teller machine,i'm not familiar at these abbreviation.

**Comment by gave92** [comment]
Relative paths as "files ." and similar do not currently work but we're looking to add support for those.
I meant "at the moment" ;)

**Comment by gave92** [comment]
Merging with #1439

**Comment by yaira2** [comment]
@gave92 is `Files .` supposed to work?
