### ISSUE TITLE
The program crashes when opening a folder

### ISSUE THREAD

**Issue by Vadimmercury** [files-community/Files#3655]
**Describe the bug**
When I open a folder in the program, the application exits without showing any error

**To Reproduce**
1. I open the application
2. I double click on any folder
3. The program crashes

**Expected behavior**
Opening a folder

**Screenshots**
No screenshots

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.804
 - App version: [v1.2.2.0]

**Additional context**
The problem remains after restarting the application

**Log file**
[debug.txt](https://github.com/files-community/Files/files/6015361/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6015362/debug_fulltrust.txt)

**Comment by gave92** [comment]
Thanks for this report. This issue has benn fixed in version 1.3 releasing to the store in a few days.
In the meantime you can enable the "open items with one click" option in Files settings.

**Comment by Vadimmercury** [comment]
Thank you very much for your answer!
