### ISSUE TITLE
Add select box for one clic to open option for tablets

### ISSUE THREAD

**Issue by dieggono** [files-community/Files#3656]
**Is your feature request related to a problem? Please describe.**
Click and hold doesn't work for select multiple items

**Describe the solution you'd like**
Select boxes of tap/click and hold can be useful for multi-select items

**Describe alternatives you've considered**
I discover that ctrl+click works! :D but maybe some basic users or tablet user can't find this

**Additional context**
Or maybe and initial tutorial for the app can be useful too, sorry for a lot of comments but I love your app and I want it to improve its user experience. I donate as soon as I can I promise!

**Comment by gave92** [comment]
Thanks for the suggestion, this is partially implemented for Grid View. Merging with #290.
