### ISSUE TITLE
Force close on shortcut to non-existent file

### ISSUE THREAD

**Issue by gavinayling** [files-community/Files#3657]
**Describe the bug**
I right-clicked on a shortcut file and clicked properties. The file that the shortcut pointed to had been moved, so the shortcut was invalid. Files force closed.

**To Reproduce**
1. Create a shortcut to a file
2. Move or delete the file
3. Right click on the shortcut
4. Click properties

**Expected behavior**
Properties window opens

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 10.0.19042 Build 19042]
 - App version: 1.2.0.0

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`, you should see a file in this directory called 
[debug.txt](https://github.com/files-community/Files/files/6015932/debug.txt)
debug.txt or/and debug_fulltrust.txt.

**Comment by gave92** [comment]
@gavinayling thanks for this report. This issue has been fixed in version1.3 which is releasing on the store in a few days.
