### ISSUE TITLE
Re-imagining the Home Page Experience

### ISSUE THREAD

**Issue by The-Noah** [files-community/Files#366]
### Creating a Fresh Home Page Experience
We're looking to make improvements to the Home page in the near future (with help from the community), are now ready to share the set of goals which will guide this effort. We anticipate lots of support from the community!

**Current Home Page Design**
![image](https://user-images.githubusercontent.com/35819660/71684253-99458c80-2d5a-11ea-83c4-7117dca96b76.png)
To put it simply, the current design of this page remains mostly redundant. The list of cards on top simply mirror some of the sidebar locations and look aesthetically-unpleasant. Further, the recent items list display EVERY file and folder opened, leading users to clear it frequently. This results in a bad design which disrupts the user and wastes space.

**Goals to Address**
1. Utilitarian: The new home page design will display information that is useful to the user _most of the time_ rather than _some of the time_. If space is taken up, it should be utilized with purpose.
2. Helpful: After having the privilege to question some of my less tech-savvy colleagues about what would add the most value to their computing experience, they overwhelmingly stated a similar problem: organization. From this, I concluded that for them, organizing information is almost as difficult and time-consuming as finding it! Thus, the items suggested for a user to invoke must make it easier for them to get work done. Our current approach is the usability version of leading a tourist to a new city and letting them go without a map. 
3. Universal: What about the enthusiast who would hardly find use for a map? Files should not only accommodate them, but help them access information most users do not need.
4. Necessary: With all improvements, we should question whether we're duplicating existing functionality found in Windows, or adding value in a new way.

While I can't promise every suggestion will be implemented, I sincerely encourage the community to seek inspiration from the rising elements of our intent-based future. These include other projects like [Mercury OS](https://www.mercuryos.com/) or Google's [Ambient Mode](https://www.youtube.com/watch?v=vaRzJo_19nY).

**Comment by yaichenbaum** [comment]
![image](https://user-images.githubusercontent.com/39923744/71684328-2bea2980-2d63-11ea-8469-fd48e593a7ce.png)

**Comment by yaichenbaum** [comment]
You beat us to it! We were planning on opening an issue just for this, one idea for the home page was to change it in to a timeline where you can go back and see recently opened files. I am open to hearing more ideas, I pinned this discussion so that it can get more visibility.

**Comment by duke7553** [comment]
I'll edit this issue then with additional info based on @The-Noah 's suggestion.

**Comment by SOI7** [comment]
Personally I'd just want an overview of the drives with their current space usage, like in the Win32 File Explorer

**Comment by yaichenbaum** [comment]
@SOI7 I had thought you wanted a dedicated drives page but not necessarily for the home page, am I correct or would you like the home page to be the drives one?
Another option is to let users choose between whatever page we set as the default and something else like a directory they always want to open the app to.

**Comment by SOI7** [comment]
> @SOI7 I had thought you wanted a dedicated drives page but not necessarily for the home page, am I correct or would you like the home page to be the drives one?
> Another option is to let users choose between whatever page we set as the default and something else like a directory they always want to open the app to.

Welp, it wasn't me actually, but the discussion was in this post: #210
In Win32, you have in the main page (AKA Home or This PC) two sections: Favorites (on top) and a bottom area where you can choose if to show the recent items (as Files currently do) or an overview of the drives. If we want to follow the Win32 Explorer, we could add an option in the Preferences section in Settings to choose between Recents or Drives below the Favorites in the Home page

**Comment by The-Noah** [comment]
If you don't have drives on the home page at least have the option to show them, as one common thing I do is access other drives so it would be nice to have it right there when I start it up.

**Comment by generalguy41** [comment]
> Another option is to let users choose between whatever page we set as the default and something else like a directory they always want to open the app to.
This please.

**Comment by R3voA3** [comment]
I'd like to see a layout similar to the following:

First row: Favorites, but not the ones we already have in the side panel, but ones I pinned there before
Second Row: Drive letters which show available space, also network drives
Third Row: Recent Files, but not as listView / listBox as it currently is, because those waste a lot of space.

**Comment by duke7553** [comment]
Here's a mock-up of what I was trying to come up with:
![image](https://user-images.githubusercontent.com/20365014/72122826-591f7480-332d-11ea-87b0-adba06f5e387.png)
Any suggestions?

**Comment by yaichenbaum** [comment]
What if we had suggested actions like you showed on top and the the option of a drives list or timeline on underneath?

**Comment by R3voA3** [comment]
Please, do not use a list view for recent items. It uses so much space, just for five entries.

**Comment by duke7553** [comment]
@R3voA3 We'll certainly take your thoughts about the ListView into account when making future improvements to the Home page.

**Comment by Darhagonable** [comment]
TBH I pretty much mostly want some something similar to This PC in explorer. Easy access to my library folders (documents, pictures etc). The Drives or Storage medias section is also great since it shows one the amount of storage left and easy access to the drives themselves. It also gives fast access to the disk cleanup. 
Another idea though would be to have something similar to chrome as well where it would show a few commonly used folders or files or both depending on what one chooses and a button to add a new one manually. This could be an equivalent to quick access but with more user control.
![Files UWP mockup](https://user-images.githubusercontent.com/14127357/73311140-1105ba80-4226-11ea-96f4-a325381aa515.png)

**Comment by duke7553** [comment]
Questions:
How useful is the list of Recent Files at the bottom for productivity? Why?

If necessary, please elaborate on what could be done to improve the list for your use case.

**Comment by duke7553** [comment]
Also, are there any times you absolutely don't need to see the list, or things you wish you could see in the list?

**Comment by yaichenbaum** [comment]
@Darhagonable do you specifically want a "This PC" page to be the startup page? Because in the future we plan to add a "This PC" page, as well as an option to set the startup page.
The goal of this issue is to get an ideal setup that works for most users that we can set as the default.

**Comment by lampenlampen** [comment]
I would go with a modular "homepage". We provide some custom controls like "Drives", "Library" "Recent Files", ... and the user can select in the settings which control he wants to be displayed.

It is then easy to add new controls and customize the page for you own liking.

**Comment by Darhagonable** [comment]
@yair100 i guess but i also do want such shortcuts as in my mockup. I don't see what else one would want instead.

**Comment by yaichenbaum** [comment]
@Darhagonable Can you clarify the shortcuts you are talking about?

**Comment by Darhagonable** [comment]
@yair100 Shortcuts / Bookmarks / Quick Access or whatever one want's to call it. This could be mixed with recently/commonly used items/folders. Similar to the "new tab" page in google chrome.

**Comment by yaichenbaum** [comment]
What I had in mind was a page similar to the Windows 10 Photos app that lets you scroll to any date and find files your created then, there can definitely be widgets and the like so keep sending ideas and concepts that improve on each others ideas.

**Comment by Darhagonable** [comment]
I guess that's an interesting idea... I am not finding that super useful though but maybe that is because I haven't really tried integrating it into my workflow. I think having it as an option would be cool though.

**Comment by duke7553** [comment]
@lampenlampen I like that idea. How useful would the Libraries one be if you have the sidebar, though?

**Comment by lampenlampen** [comment]
Dunno, these are only examples, i collected from this thread.

**Comment by lampenlampen** [comment]
I think all the ideas in this thread could be realized with a "Drives", a "Favorites", a "Recently used Items" and a "Timeline" control.

**Comment by generalguy41** [comment]
> I would go with a modular "homepage". We provide some custom controls like "Drives", "Library" "Recent Files", ... and the user can select in the settings which control he wants to be displayed.
It is then easy to add new controls and customize the page for you own liking.

I like this idea. Maybe a new user gets a type of "onboarding" page when they start the app for the first time giving them an option to "Customize Your Home Page", and gives them a list of options they can choose (and change later), which include options to show on the page (Drives, Quick Access, Recent Files, etc) and an option on how to display them (list view, icon view, etc). Obviously this would be a lot of work, but just throwing it out there.

**Comment by yaichenbaum** [comment]
Some feedback I have after using the app as a full replacement for File Explorer for some time.

1. The cards on the home page are really helpful even though the locations are already on the sidebar, the cards are larger and easier to click on compared to the sidebar. However since it's possible that not everyone feels the same, it should be easy to remove this widget.

2. The recent items list is very helpful, however it should have the option to be hidden if the user wants.

3. If we add a drives page, it would make sense to add an optional widget to the home page as well.

**Comment by xPoppyx** [comment]
![home-tab](https://user-images.githubusercontent.com/61259627/80286636-8f290e80-86fa-11ea-96b3-842938003ee7.png)
-------------------------------------------------------------------
![home-tab2 - copia](https://user-images.githubusercontent.com/61259627/80286917-42dece00-86fc-11ea-9ddd-f6b3da06dd2d.png)

**Comment by SOI7** [comment]
As @lampenlampen said, a modular Home page where you can choose what to show would be ideal

**Comment by xPoppyx** [comment]
and i agree, it's just to get an idea of ​​what it would look like

**Comment by yaichenbaum** [comment]
We have been exploring different possibilities to improve the home page and one of the ideas was to create a widget system where anyone can contribute widgets for the home page that can be pinned or unpinned to meet the users needs.
If this is something the open source community would be interested in working on, please let us know your thoughts and ideas for setting up the widget architecture.

**Comment by crashmit** [comment]
Hi there, first time poster here.

I drew out a quick Idea I had. My proposal would be to allow for "storage containers" which you can create and delete as you like. They can be called whatever a users wants and can be filled by simply dragging and dropping item into the container. I am always annoyed by filling up my sidebar with quick access shortcuts without any sorting and having it all filled up. Using these containers, you can have all folders/files/programs corresponding to a topic in one place, even if they're distributed over different drives/services (my uni stuff is spread out over Google Drive, local files and Adobe Creative Cloud f. ex.). This is just a rough sketch I did in the past 10 minutes, so it's more about the idea than the visuals.

Looking forward to your feedback!

<img width="1458" alt="Files UWP Home" src="https://user-images.githubusercontent.com/58466626/87429589-4ccdea00-c5e4-11ea-8917-5e014cf5a27a.png">

**Comment by lukeblevins** [comment]
@yair100 Take a look at [this](https://github.com/files-community/files-uwp/issues/366#issuecomment-658172746) when you get a chance! 😀

**Comment by jpparametrics** [comment]
I like that idea. ALOT...

**Comment by crashmit** [comment]
Well thank you very much! 😄

**Comment by crashmit** [comment]
If you need somebody to help with designing the feature to full detail, I'd be happy to help out.

**Comment by XPoppyX** [comment]
![concept](https://user-images.githubusercontent.com/61259627/87466645-a209fb80-c5e4-11ea-9e7d-2add63ab8cb3.jpg)

**Comment by crashmit** [comment]
Those sorting options would definitely be useful, but I'd suggest using the "Add new Storage" or at least its icon as a button instead burying it in a menu? Also, if there were multiple widgets there should be a way to change their order.

**Comment by XPoppyX** [comment]
Maybe an option to show or hide a "+" button to add containers, and enable it by default.

**Comment by crashmit** [comment]
I don't think showing it permanently would annoy anyone or do you think it would?

**Comment by XPoppyX** [comment]
well, for me for example I don't really like a giant "add" button

**Comment by crashmit** [comment]
Well yes agreed, the add in my first proposal is pretty big, but I would put the "add storage" on the top level next to the three dots, that you proposed. You already use that pattern for "New File" in regular folders. But as the pattern is already connected to new file there maybe needs to be a different icon than a plus.

![image](https://user-images.githubusercontent.com/58466626/87481973-cdb2d300-c630-11ea-9f74-3914642164b3.png)

**Comment by XPoppyX** [comment]
I see, in that case there is no problem in showing it permanently, I thought you were referring to the other big button

**Comment by XPoppyX** [comment]
maybe this icon could be used

![Anotación 2020-07-14 182936](https://user-images.githubusercontent.com/61259627/87482710-fec6df80-c5ff-11ea-88b9-b08603c7ad0c.png)

**Comment by crashmit** [comment]
Absolutely, that fits perfectly I think.

**Comment by yaichenbaum** [comment]
@crashmit This is an excellent idea! I would like to take this chance to announce our vision for the home page moving forward.

We have heard from our users that they would like modular home page where they can pin cards depending on their needs. We are working on building out a widget system where users will be able to pin\unpin and reorder widgets to their liking. From the start, there will already be two widgets available, the favorites and recent files widget. Other ideas for widgets are
- Drives widget
- Pinned items widget
- Recently downloaded items widget

With this system, anyone can build their own widget and if it makes sense, we will merge it in. It's important to note that all new features and controls should be approved in an issue before being developed. We still haven't finished building the infrastructure for the new widget system but if you are interested in starting, please open an issue for the widgets you would like to see so we can discuss and approve them for development. Looking forward to seeing all your ideas!

**Comment by yaichenbaum** [comment]
With the new widget system, users can choose which widgets to show on the home page and they can even contribute new widgets if they have an idea. The widget system is still basic, but over time we will enhance the actual widgets as well as the system for managing them based on your feedback.
