### ISSUE TITLE
Issue renaming files when "open items with one click" is enabled

### ISSUE THREAD

**Issue by AisinGioroKiIoi** [files-community/Files#3660]
选择单击以打开文件时，对文件重命名会打开文件，无法完成重命名工作。望解决，ᠪᠠᠨᡳᡥᠠ（巴尼哈/谢谢）

**Comment by gave92** [comment]
When you enable the "Open items with one click" option you can rename by:
- Right clicking and selecting "rename" in the context menu
- Pressing "F2" on the keyboard

**Comment by AisinGioroKiIoi** [comment]
使用的F2或者右键“重命名”，之后如果是对文件重新命名，没有问题。如果是使用鼠标选中其中几个字符进行修改的话，会把文件打开。望解决，ᠪᠠᠨᡳᡥᠠ（巴尼哈/谢谢）

**Comment by yaichenbaum** [comment]
@AisinGioroKiIoi This issue should be resolved with #3669.
