### ISSUE TITLE
Exit when I try to open a folder

### ISSUE THREAD

**Issue by HaoxuanDi** [files-community/Files#3662]
## Example:

![image](https://user-images.githubusercontent.com/57934391/108612622-5397c780-7425-11eb-995b-dffa41ccf8aa.png)

When I try to open any a folder in picture, App Crash back .

**This situation always happens, not accidentally.**

**Comment by HaoxuanDi** [comment]
not any, but folder which include a lot of files

**Comment by gave92** [comment]
Thanks for this report. This has been fixed in 1.3.
