### ISSUE TITLE
Some UI elements take a long time to load when opening a new Files window

### ISSUE THREAD

**Issue by asuetin** [files-community/Files#3664]
**Describe the bug**
Some UI elements take up to 30 seconds to load when you open a new Files window. If you then open a new tab in the same window, they load instantly.

The list of elements:

1. The "Cloud Drives" section on the sidebar
2. The "Network Drives" section on the sidebar
3. Bundles on the home page (they also load one by one, sometimes one shows up instantly while the rest take a few seconds to appear)
4. The free space percentage bars on the drive cards

**To Reproduce**
1. Open a new Files window

**Expected behavior**
All elements should load instantly or at least much faster

**Desktop (please complete the following information):**
 - OS Version: Windows 10 21H1 19043.844
 - App version: v1.3.0.0

**Additional context**
The problem was also present on the 20H2 build of Windows

**Log file**
[debug.txt](https://github.com/files-community/Files/files/6017314/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6017315/debug_fulltrust.txt)

**Comment by yaichenbaum** [comment]
@asuetin This issue should be resolved with #3669.
