### ISSUE TITLE
Add a larger Details View layout

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#3665]
- All layout modes should support size changing (Currently only for Grid View)
- CTRL + mouse wheel scrolling should change the zoom/size of currently layout mode (This shortcut is for example default for browsers and many other common application)
- ALT + mouse wheel scrolling should change the layout mode, but preserve previously set zoom
- Zoom level should be indicated in the status bar (%) or via slider in the layout menu

**Why would we need size changing for other layout modes?**
![image](https://user-images.githubusercontent.com/17484252/108621304-2e5d8600-7432-11eb-85c0-218fb51d0d5b.png)

On larger screen (larger resolution) the details layout for example, rarely fills the whole screen for me. Having the option to adjust the zoom would reduce the wasted space increase the legibility for me.

**Comment by yaichenbaum** [comment]
@R3voA3 We don't plan on implementing a zoom option, however, we can look at adding another size for the details layout once the WinUI DataGrid becomes available.

**Comment by yaichenbaum** [comment]
@R3voA3 I think the extra space will be better used by showing more columns once they are added. The details layout is intended for viewing a lot of files in a list and a larger size would defeat the purpose, would the grid layout be a better choice to maximize the screen space?
