### ISSUE TITLE
Column View like macOS / One Commander

### ISSUE THREAD

**Issue by AaravHattangadi** [files-community/Files#3666]
**Is your feature request related to a problem? Please describe.**
Yes. I am a huge organization freak, and I have multiple nested folders. While searching for a file, I sometimes get lost. In these cases, I usually use OneCommander, but your UI is drawing me towards Files.

**Describe the solution you'd like**
I would want a column view. Something like the macOS Finder, or the one in your competing application, One Commander.

**Describe alternatives you've considered**
I've not really thought of any alternatives.

**Additional context**
Win10/Desktop

**Comment by gave92** [comment]
Thanks for the suggestion, merging with #137

**Comment by AaravHattangadi** [comment]
> Thanks for the suggestion, merging with #147

Thanks.. Is there any plan to implement it in the near future? like the next 1 year?

**Comment by gave92** [comment]
@AaravHattangadi implementation was started by sadly never completed -> you can follow development at #2500

**Comment by AaravHattangadi** [comment]
> @AaravHattangadi implementation was started but sadly never completed -> you can follow development at #2500

Ok.. Thanks
