### ISSUE TITLE
Click with Wheel on Subpath on PathBar -> Open in new Tab

### ISSUE THREAD

**Issue by bliet** [files-community/Files#3667]
**Is your feature request related to a problem? Please describe.**
When I click with the mouse wheel on a subpath, the field changes to edit mode. It would be greate if a new tab would be open.
Same behaviour could be added to the navigation buttons "back" and "up".

**Describe the solution you'd like**
Change the behaviour. 

**Describe alternatives you've considered**
?

**Additional context**
Example: At the moment files shows the folder "C:/Users/max/Documents/work/importan" . Now I want to open "C:/Users/max/Documents/work" in a new tab. I have to go up and click with the mouse wheel on the subfolder to open it again. It would be faster if i could open an parent folder (or the parent of the parent ...) directly in a new tab.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7126.
