### ISSUE TITLE
Double Click on Sub-folder Makes Crash

### ISSUE THREAD

**Issue by EanraigZhang** [files-community/Files#3671]
<h3>[Description]</h3>
When I double click sub-folder  , the file will run hard for a long while then crash out.
<h3>[Reproduce]</h3>

1.Click disk icon</br>
2.Double click parent folder</br>
<i>3.Double click sub-folder</i>
<h3>[Expected Behaviour]</h3>
When I click these sub-folders , the file could open them fluently.
<h3>[Desktop]</h3>
OS :Windows 10 21H1 19043.844</br>
App Version :1.2.2.0</br>
</br>
<p># I am not a native English speaker , #</br># my English may be strange #</br># but I sincerely hope this app will be perfect. #</br># Thanks. #</p>

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
