### ISSUE TITLE
Right clicking crashes the app

### ISSUE THREAD

**Issue by linds-codes** [files-community/Files#3680]
**Description**
Right clicking on anything crashes the app.

**To Reproduce**
1. Go to any folder
2. Right click on a file
3. Error notification pops and app either crashes or hangs.

**Expected behavior**
The right click options should show instead of a crash!

**Screenshots**

**Desktop (please complete the following information):**
Device name	Inspiron14
Processor	11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz   1.69 GHz
Installed RAM	16.0 GB (15.7 GB usable)
System type	64-bit operating system, x64-based processor

**Additional context**
Happens on every app use.

**Log file**
[debug.txt](https://github.com/files-community/Files/files/6022246/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6022247/debug_fulltrust.txt)

**Comment by gave92** [comment]
Thanks for this report. Could you check if  before the app crashes there a process called "FilesFullTrust.exe" running in task manager? Thanks!

**Comment by OviiiOne** [comment]
Can reproduce.
There is indeed a process called "FilesFullTrust.exe" running.
[debug.txt](https://github.com/files-community/Files/files/6023398/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6023399/debug_fulltrust.txt)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #3684.
