### ISSUE TITLE
Feature: Add setting to select files and folders when hovering over them with the mouse

### ISSUE THREAD

**Issue by eliezerjrs** [files-community/Files#3682]
**Requirements**
- Add setting to preferences setting page "Select files and folders when hovering over them with the mouse"
- Setting should be turned off by default

**Comment by LukoFoks** [comment]
v2.0 was an **amazing** update, but honestly, I would expect this feature to be part of it.
It is really annoying to select folders with `CTRL`. Please apply this feature.

**Comment by yaichenbaum** [comment]
> v2.0 was an **amazing** update, but honestly, I would expect this feature to be part of it. It is really annoying to select a folder with `CTRL`. Please build it into the app.

Would you like to work on this issue?

**Comment by yaichenbaum** [comment]
> v2.0 was an **amazing** update, but honestly, I would expect this feature to be part of it. It is really annoying to select a folder with `CTRL`. Please build it into the app.

@LukoFoks would you like to work on this issue?

**Comment by LukoFoks** [comment]
> @LukoFoks would you like to work on this issue?

Sorry, I have no idea of UWP or C#. I'm rather a web developer.

**Comment by R3voA3** [comment]
Please make this a priority. Working with files when files are being opened by one click without this functionality is cumbersome.

**Comment by karanrahar** [comment]
This is the only thing preventing me from using Files. Please can we have this>?

**Comment by ferrariofilippo** [comment]
Can I work on this?
