### ISSUE TITLE
Would anyone like a list view like macOS?

### ISSUE THREAD

**Issue by MartinezEzequiel1991** [files-community/Files#3683]
This is one of the best features in my opinion about mac... you can see the folder's children without having to enter and exit each folder... does anyone think this could be done? (or knows anything like this for Windows?). Thanks
![image](https://user-images.githubusercontent.com/61179137/108749492-a1dcc180-751e-11eb-820f-130b5504caaa.png)

**Comment by gave92** [comment]
Thanks for the suggestion, it's already in our todo list -> #1928
