### ISSUE TITLE
external device opening failure 

### ISSUE THREAD

**Issue by Sagar-v4** [files-community/Files#3687]
**Describe the bug**

**To Reproduce**
1. Go to '....'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2 19042.804]
 - App version: [e.g. v1.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`, you should see a file in this directory called debug.txt or/and debug_fulltrust.txt.

**Comment by gave92** [comment]
Hello @Sagar-v4 could you add more details? What's the app version? What happens when you try to open the external device?
