### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by pklion** [files-community/Files#3689]
**Is your feature request related to a problem? Please describe.**
There is a description of when Files was a beta version.

```
## Vision for Files
In the short term, we plan to focus on crucial functionality to achieve parity with Windows File Explorer. Before leaving beta, we'll address many of these pain points and improve accessibility. Later on, the project will reach a point where we can fully celebrate our core audience by adding sought-after power user features. Stay tuned!
```

**Describe the solution you'd like**
Please update the description.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by gave92** [comment]
\+ @yair100

**Comment by yaichenbaum** [comment]
```## Vision for Files
The vision for Files is to make it the best file manager while keeping it simple and easy to use. Whether it's implementing new features, or pushing the boundaries of the platform, your input will help shape the future of Files.```

**Comment by yaichenbaum** [comment]
@pklion Would you like to work on this issue?

**Comment by pklion** [comment]
> ```
> The vision for Files is to make it the best file manager while keeping it simple and easy to use. Whether it's implementing new features, or pushing the boundaries of the platform, your input will help shape the future of Files.```
> ```
I think this is a brilliant description, so I'll make the PR.
