### ISSUE TITLE
Search results include folders

### ISSUE THREAD

**Issue by v-aravind** [files-community/Files#3691]
**Is your feature request related to a problem? Please describe.**
When I use the search function, it only returns files, not folders. I have a lot of folders and in Windows Ecplorer it is often faster for me to use the search to find a folder than to scroll down to it. But in the Files app, the search function only returns files, not folders.

**Describe the solution you'd like**
The search function should return folders (at the top of the list) alongside files.

**Comment by yaichenbaum** [comment]
@v-aravind Are the folders you're searching for indexed?
