### ISSUE TITLE
Multi-select checkbox

### ISSUE THREAD

**Issue by v-aravind** [files-community/Files#3692]
**Is your feature request related to a problem? Please describe.**
One of the more useful features of Windows Explorer is the multi-select checkbox. Currently in Files, when you need to select multiple items, you need to hold down the Ctrl keywhile clicking. This isn't very compatible when using the touchscreen, and in general when multi-selecting a lot of items, you don't want to keep one finger constantly on the crtl key. The lack of a check-box becomes all the more challenging when the single-click to select functionality is enabled, as I have.

**Describe the solution you'd like**
Please could you implement multi-select checkboxes, and an option to always show the checkboxes in the left most column, for instance when hovering over an item, like Windows Explorer does, or always visible, which would be ideal for touchscreen interfaces.

**Comment by gave92** [comment]
Merging with #290. This has been implemented for GridView as an experimental feature, ListView is still missing.
