### ISSUE TITLE
Gaming services' links aren't rendered properly

### ISSUE THREAD

**Issue by militaryCoder** [files-community/Files#3695]
### Bug description
Steam, EpicGames, Uplay and other gaming services' games links are not shown properly.

### How to reproduce
1. Go to any folder containing links used for Steam games launch (in my case, I placed shortcuts on desktop).
2. Enjoy the result.:)

### Expected behavior
Links should should be rendered properly.

### Screenshots
This is how it looks like in Files:
![image](https://user-images.githubusercontent.com/55032128/108816075-904ef480-75c6-11eb-88af-6020bb7d9e17.png)

And this is how it should look like:
![image](https://user-images.githubusercontent.com/55032128/108816281-f76ca900-75c6-11eb-9e35-2d7790937da8.png)

### OS and application Info
 - OS Version: Windows Feature Experience Pack 120.2212.551.0, build 19042.804, version 20H2
 - App version: 1.3.0.0

### Log file
[debug.txt](https://github.com/files-community/Files/files/6027461/debug.txt)

**Comment by yaichenbaum** [comment]
@militaryCoder This issue should be resolved with #3746.

**Comment by nullptr-deref** [comment]
@yair100 When I'll see the result?

**Comment by yaichenbaum** [comment]
@militaryCoder The result is immediate in `main`, however, the next store release isn't going to be for around a month.
