### ISSUE TITLE
Show custom drive icons on homepage

### ISSUE THREAD

**Issue by saxobroko** [files-community/Files#3697]
**Describe the bug**
Personalised drive icons don't show only the default drive icons show.

**To Reproduce**
1. Put a .ico photo in root of a drive.
2. Set up autorun.inf

**Expected behavior**
The icon for the drive should change to whatever was customized, as is what happens in windows 10 file explorer.

**Screenshots**
![image](https://user-images.githubusercontent.com/18757374/108836942-99bb7980-7625-11eb-93af-3b4598874114.png)
![image](https://user-images.githubusercontent.com/18757374/108836993-a93ac280-7625-11eb-9276-3910183c13d2.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 10.0.19042
 - App version: 1.3.0.0

**Comment by boscorelly** [comment]
Hi,

it is just not implemented.

Please close the issue and open a feature request :)

**Comment by yaichenbaum** [comment]
Merging with #1015.
