### ISSUE TITLE
Sidebar does not honour changed libraries locations

### ISSUE THREAD

**Issue by boscorelly** [files-community/Files#3698]
hi,

when you move your download folder to another place (ie onedrive), the path in the left tab is still c:\Users\%username%\Downloads instead of the new location.

The result is that download folder is pointing to an empty place.

But in the libraries widgets, the problem doesn't appear.

**Comment by gave92** [comment]
Could you try deleting this file: %localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalCache\PinnedItems.json and see if the new path is picked up?
NOTE: you will loose your pinned folders!

**Comment by yaichenbaum** [comment]
Merging with #692.
