### ISSUE TITLE
Files-1.3.Msixbundle asset missing on v1.3 GH release

### ISSUE THREAD

**Issue by bl-ue** [files-community/Files#3700]
Hello!  There's no `Files-1.3.Msixbundle` asset attached to the [v1.3 release on GitHub](https://github.com/files-community/Files/releases/tag/v1.3), as there normally is.  Is this intentional?  Thank you!

**Comment by bl-ue** [comment]
cc @yair100

I feel like this is urgent because I can't download from the store and at 1.2.2 Files is completely unusable.

**Comment by yaichenbaum** [comment]
@bl-ue The v1.3 release was recently uploaded.

**Comment by bl-ue** [comment]
Thank you!
