### ISSUE TITLE
Some keyboard shortcuts don't work when the focus isn't on the file content area

### ISSUE THREAD

**Issue by winston-de** [files-community/Files#3702]
**Describe the bug**
When Files is opened with a path parameter, whether that be through the terminal, search, power run,  etc., most keyboard shortcuts seem to stop working. 

Ctrl+T and Ctrl+W, however, do still seem to work.

**To Reproduce**
1. Run command ```files c:\users\```
2. Press Alt+Up on keyboard
3. Selection is moved up instead of going up a directory

**Expected behavior**
Keyboard shortcuts should work normally.

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: 19043.844
 - App version: 1.3.0.0

**Additional context**
I'm guessing this is caused by the ContentPage stealing keyboard input for the filter type feature, preventing it from reaching ModernShellPage, where all the key bindings are handled. 

**Log file**
No helpful information.

This also seems to break the type to find thing for the content page.

**Comment by gave92** [comment]
This might be fixed in version 1.3.5 (beta), to be verified.

**Comment by winston-de** [comment]
@gave92 That seems to be the case.
