### ISSUE TITLE
"Group by" function, Lettering of folders/files

### ISSUE THREAD

**Issue by CF-71** [files-community/Files#3704]
The "Sort by" function is available. But could the "**Group** by" function (as in Windows File-Explorer) also be implemented for the views of a window/folder?
I find it more clearly presented if you can also group folders and files.

And the lettering (font size) of individual folders and files is quite large. Especially in the "Tile" layout mode. This takes up a lot of space on a notebook (15 inch display). It would be nice if the user could better fine-tune the size of the symbols (folders, files) and their labeling.

By the way: A good and useful app! Great work so far. Thanks for the development!

**Comment by yaichenbaum** [comment]
Merging with #1874.
