### ISSUE TITLE
Sorting with Groups

### ISSUE THREAD

**Issue by LeNinjaHD** [files-community/Files#3706]
**Is your feature request related to a problem? Please describe.**
In the normal Windows Explorer, I have the ability to sort Files and Folders in groups.

**Describe the solution you'd like**
It would be nice, If this feature would be implemented in Files.

**Describe alternatives you've considered**
I dont have alternatives.

**Additional context**
Example:
![grafik](https://user-images.githubusercontent.com/58134535/108966342-593c1a00-767e-11eb-920a-163b40419ca1.png)

**Comment by gave92** [comment]
Thanks for this suggestion, this is already on our todo list. Merging with #1874
