### ISSUE TITLE
Show icons in the context sub-menus

### ISSUE THREAD

**Issue by Nisgrak** [files-community/Files#3708]
**Describe the bug**
When click the More ("Más" in the image) in the context menu it's shows the other options, but doesn't have icons like in Explorer.

**To Reproduce**
1. Right-Click in a folder in Files
2. Click "More" button
3. Make the same but in the Explorer.
4. See the differences in icons and options

**Expected behavior**
Shows the same options and icons in Files and Explorer.

**Screenshots**
See for example "What's locking this folder?"(LockHunter), in Explorer have icon, in Files no.
Files
![image](https://user-images.githubusercontent.com/19597708/108983498-38c88b80-768f-11eb-9e96-e10378073a2b.png)

Explorer
![image](https://user-images.githubusercontent.com/19597708/108983486-35cd9b00-768f-11eb-9b90-9e058c67b58c.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.804
 - App version: 1.3.0.0

**Log file**
[debug.txt](https://github.com/files-community/Files/files/6035069/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6035070/debug_fulltrust.txt)

**Comment by okey2k** [comment]
On the converse, I prefer to have a clean sub-menu as-is without icons.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5081.
