### ISSUE TITLE
Assign a hotkey for opening Files.

### ISSUE THREAD

**Issue by ya-nsh** [files-community/Files#3709]
When "Win + E" is pressed, the explorer opens up. It would be great if something similar is used for opening Files.

**Comment by pklion** [comment]
I'm not the participants, but this is already developed.
https://files-community.github.io/docs/#/articles/configure-win-e
If you want to replace the explorer with Files, view [this](https://files-community.github.io/docs/#/articles/replace-file-explorer). :)

**Comment by ya-nsh** [comment]
Thanks. This is exactly what I needed.
