### ISSUE TITLE
Support nanoseconds (NTFS)

### ISSUE THREAD

**Issue by vanessa794h** [files-community/Files#3711]
**Is your feature request related to a problem? Please describe.**
NTFS stores timestamps with an accuracy of 100 nanoseconds.

**Describe the solution you'd like**
Add an option to display 100 nanoseconds for NTFS medium.

**Describe alternatives you've considered**
N/A

**Additional context**
The advantage is that I don't always have to manually start cmd and external software.

Instead, I can display the nanoseconds for my files and folders directly in Files (GUI) in a user-friendly way and can also use other functions of Files (GUI) at the same time.

**Comment by gave92** [comment]
Thanks for this suggestion. Merging with #2207
