### ISSUE TITLE
Files crashed when I tried to open a long path (>256)

### ISSUE THREAD

**Issue by ResearcherSearching** [files-community/Files#3712]
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6037281/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6037283/debug.txt)

**Describe the bug**
I tried to open a long path with more then 256 signs, and files crashed.

**To Reproduce**

1. Create a folder inside a folder inside a folder with long folder names (alltogether longer than 256 signs)
2. Try to open the last one with files.
3. See error

**Expected behavior**

The file explorer should be able to work with long file paths.

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.804
 - App version: 1.3.0.0

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

Yes

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`, you should see a file in this directory called debug.txt or/and debug_fulltrust.txt.

**Comment by yaichenbaum** [comment]
@ResearcherSearching This issue should be resolved with #3716.
