### ISSUE TITLE
Vbs scripts runs from wrong directory

### ISSUE THREAD

**Issue by Inogami** [files-community/Files#3713]
**Describe the bug**
VBS script execution directory always C:\Winows\System32

**To Reproduce**
1. Create vbs script with code
2. `Dim fso Set fso = CreateObject("Scripting.FileSystemObject") curDir = fso.GetAbsolutePathName(".") WScript.Echo curDir `
3. Run it
4. It will return alert windows with C:\Winows\System32 path printed

**Expected behavior**
Expected to return path to directory In which the file is located

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Pro 20H2 19042.844
 - App version: 1.3.0.0

**Additional context**
It occur after restart

**Log file**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6037308/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6037309/debug.txt)

**Comment by gave92** [comment]
Thanks for the report. Merging with #3360 (working folder not respected)
