### ISSUE TITLE
Thanos snap

### ISSUE THREAD

**Issue by rocksdanister** [files-community/Files#3714]
**Is your feature request related to a problem? Please describe.**
As a amateur data hoarder one of my problem is trying to select files to delete to free up space.
Deleting all the files is not a good idea, I would like to keep some files.

**Describe the solution you'd like**
Delete 50% of the files/folder at random from selected folder/drive contextmenu.

**Describe alternatives you've considered**
Writing PowerShell script.

**Additional context**
Some fading/dust animation for deleted files would be nice.

**Comment by yaichenbaum** [comment]
@rocksdanister This feature does not match of vision for Files.
