### ISSUE TITLE
Suspend tab if not used for a long time

### ISSUE THREAD

**Issue by JaiganeshKumaran** [files-community/Files#3718]
**Is your feature request related to a problem? Please describe.**
Today adding more and more tabs increasing memory usage by a large amount. On older, weaker devices it may be an issue with lots of tabs open.

**Describe the solution you'd like**
When switching from a tab, start a timer that would fire at a specific interval. If the user doesn't use the tab for a long time, consider clearing content and then reload when he/she actually comes back

**Describe alternatives you've considered**
None

**Comment by d2dyno1** [comment]
I'd add a toggle in settings to 'put tabs to sleep'

**Comment by gave92** [comment]
At the moment we can't even free the memory when a tab is closed 😅

**Comment by duke7553** [comment]
@gave92 Is there a way we can manually unload the whole tab's visual tree when closing them?

**Comment by yaichenbaum** [comment]
@duke7553 we can probably clear the visual tree by navigating to an empty page in the background.
