### ISSUE TITLE
Folder icon issue

### ISSUE THREAD

**Issue by Motauer84** [files-community/Files#3721]
**Describe the bug**
As it is shown in the following picture, the folder icon do not appear when I start files program. I tried to re-install the program but the issue continue. Is there any thing I can do for resolving this problem? Thanks

**Screenshots**
![image](https://user-images.githubusercontent.com/79630102/109123555-44c55380-774a-11eb-9431-f410697af450.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 SO 19041.804
 - App version: 1.3

**Comment by yaichenbaum** [comment]
@Motauer84 Is this still an issue in v1.5?

**Comment by Motauer84** [comment]
The issue still continue.

**Comment by yaichenbaum** [comment]
Can you try turning off the setting to cache items?
