### ISSUE TITLE
Feature: Add hashes tab to the properties window

### ISSUE THREAD

**Issue by PMExtra** [files-community/Files#3722]
### Describe the solution
[HashTab](http://implbits.com/products/hashtab/) is a plugin of Windows Explorer.

![image](https://user-images.githubusercontent.com/11289158/109131328-a78c0e80-778d-11eb-9186-78b11bcd1ff6.png)

I want the same feature that build in Files.

### Requirements
- Add hashes tab to the properties windows
- Display hashes (starting with CRC32, MD5 and SHA-1) in the list (should follow the design pattern in the details tab)

### Files version

2.3.12.0

### Windows version

10.0.19043.2006

**Comment by PMExtra** [comment]
@yair100 Please let me know if you'd like to implement it or welcome the PR.

**Comment by yaichenbaum** [comment]
@PMExtra A PR would be great, would you like to work on this?

**Comment by Josh-65** [comment]
Thought to add since 7zip is now integrated the hash features might be in it too. The 7zip program support these.
![image](https://user-images.githubusercontent.com/26977075/185786097-078fdbde-bfda-4c50-9282-95078797a127.png)

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
What kinds of settings are available in HashTab?

**Comment by sthivaios** [comment]
> What kinds of settings are available in HashTab?

I just installed HashTab on a VM.

It has the following features :
- A link to license the software, that seems like it doesn't work anymore
- A settings link, which opens the following window : https://user-images.githubusercontent.com/109022579/195403031-21ea85ba-4dba-4685-aee0-5b45d8b4de4c.png
- A "Hash Comparison" text box, and a "Compare a file..." button
- The "main" thing that shows the hash values.


That is a screenshot of the full window : 

![image](https://user-images.githubusercontent.com/109022579/195403307-10ea5b02-e907-4a30-9c90-d178ed324c13.png)



PS : You might have meant a completely different think by saying "What kind of settings are available in HashTab?", but, that is what I understood... I don't have any idea how to code so I cannot get involved anymore in this thread.

**Comment by yaichenbaum** [comment]
I think we can start with the most common hashes and track requests for additional ones later one. That being said, we need a design before starting on this.
