### ISSUE TITLE
Autofocus on text field

### ISSUE THREAD

**Issue by rusti4** [files-community/Files#3724]
When renaming a folder and similar, please make the window jump to and autofocus to the text field so you can begin typing instead of having to click the field.

**Comment by d2dyno1** [comment]
:eyes:

**Comment by gave92** [comment]
Not sure if I understood your request.
When you're not renaming a file typing on the keyboard will scroll the list to show the first file matching the typed letters.
When a file is highlighted pressing F2 will start renaming it.

**Comment by d2dyno1** [comment]
Did you mean the dialog rename textbox?

**Comment by gave92** [comment]
@dyno1 could you remind me in what occasions is that rename dialog shown?

**Comment by d2dyno1** [comment]
I can't think of any, but I thought the autor had that in mind. Actually that is an issue and it will be fixed in #3637 via https://github.com/files-community/Files/pull/3637/commits/673ffd071b5819d65cfbcdfacaf2e5c98e9f4839

@gave92

**Comment by rusti4** [comment]
Apologies, its when you create a new folder and it has the dialog box popup up. You have to either click or press 'tab' for it to become active. 
@gave92 @d2dyno1

**Comment by d2dyno1** [comment]
@rusti4 Ok! This is fixed in #3637
