### ISSUE TITLE
Some bugs i´ve found on W10 Pro x64 20H1 update

### ISSUE THREAD

**Issue by Abnger1** [files-community/Files#3725]
**Describe the bug**
1. When i open Files, and navigate trough my folders and files, he suddenly crash. This happens after the update through Microsoft Store from 1.1 to 1.2 version. But when i uninstall the update, and reinstall it, the software runs very well.
2. When i select the black theme and close Files and open it again, it shows the white theme.
3. The software stay every time at the top, maybe an option to send it back. It happens with Illustrator projects for example, I open it and llustrator stay in background,

**Expected behavior**
1. Not to crash will be amazing
2. Select the black theme and stay :)
3. An option to send Files to background when open files like Illustrator projects

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Pro 20H1 v2004 compilation: SO 19041.508
 - App version: 1.2

**Comment by gave92** [comment]
Update to 1.3 and the first two issues will be gone 👍

**Comment by Abnger1** [comment]
thanxs, ive updated to 1.3 and actually works fine 👍
