### ISSUE TITLE
Shortcuts like delete don't work. Please fix the hotkeys, thank you very much for making this project free and open sourced!

### ISSUE THREAD

**Issue by 1keyjee1** [files-community/Files#3726]
**Describe the bug**

**To Reproduce**
1. Go to '....'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2 19042.804]
 - App version: [e.g. v1.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`, you should see a file in this directory called debug.txt or/and debug_fulltrust.txt.

**Comment by gave92** [comment]
Thanks for this report. Do they never work or does closing and reopening the app a couple of times fix this?

**Comment by 1keyjee1** [comment]
Unfortunately they never do, I switched from Linux to Windows, and I hate
using this operating system, if it wasn’t for your project I would not be
able to bare the operating system at all. Glad to report an issue, I wish
this project to succeed! My favorite file manager is dolphin but
unfortunately it is not possible to have anything close to it with regards
to customizations. Anyways, have a good day.

**Comment by gave92** [comment]
Merging with #3702
