### ISSUE TITLE
App Crashes when double clicking to open folders or files

### ISSUE THREAD

**Issue by Alessia362** [files-community/Files#3727]
**Describe the bug**

-**The App Crashes when double-clicking to open any folder.**
-The issue happens both when "Open Items with Single Click" is enabled and when it is disabled. (When enabled, using single click to open folders works perfectly).
-The issue happens no matter the directory, the size of the folder, the drive or whether the folder is stored locally or in the cloud.
-The issue is not there when double-clicking to open files, or when double clicking in an empty area. It only happens when double-clicking on a folder.

**To Reproduce**
1. Open the app, try double-clicking on any folder.

**Expected behavior**
Double-clicking on a folder, should open the folder if "Open Items with Single Click" is Disabled.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.844
 - App version: 1.2.2.0

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

The problem occurs even after restarting the app, restarting the laptop.

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`, you should see a file in this directory called debug.txt or/and debug_fulltrust.txt.

[debug_fulltrust.txt](https://github.com/files-community/Files/files/6045651/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6045652/debug.txt)

**Comment by d2dyno1** [comment]
The issue has been resolved with 1.3.0.0. Make sure you've got latest version of Files installed.

**Comment by Alessia362** [comment]
Oh I hadn't noticed the update available! 
I can confirm this works now! Thanks! :D
