### ISSUE TITLE
Text bug on PT-BR Language. 

### ISSUE THREAD

**Issue by MrJeff47** [files-community/Files#3728]
**Describe the bug**

Some options in Settings are is Arabic insted of Portuguese (Brasil), i can't understand some settings, this also happen in some "Titles" in the UX of the app.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Preferences'
3. Change 'App language' to 'Portuguese (Brasil)'
4. See the bug in some Settings texts and the UX.

**Expected behavior**
These texts must be in Portuguese (Brasil) or at least in Roman alphabet.

**Screenshots**

![Print 1 (Settings)](https://user-images.githubusercontent.com/79664514/109214563-c344e400-7790-11eb-9abc-b732f1f9922f.png)
![Print 2 (Initial Page)](https://user-images.githubusercontent.com/79664514/109214581-c8a22e80-7790-11eb-9ee9-e555b31a00f9.png)

Link to the Screenshots in Imgur: https://imgur.com/a/UBv2lMh

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 20H2 19042.804]
 - App version: [v1.3.0.0]

**Log file**

[debug.txt](https://github.com/files-community/Files/files/6045655/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6045656/debug_fulltrust.txt)

**Comment by gave92** [comment]
Thanks for the report. Merging with #3385
