### ISSUE TITLE
Make the Files App available in Linux through snap

### ISSUE THREAD

**Issue by jesusdpa1** [files-community/Files#3731]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Would be great to see this project expanding to Linux (Ubuntu, Debian, etc) as an alternative to nautilus.
**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by duke7553** [comment]
@jesusdpa1 Sorry, but the way we built Files relies on Windows-only code, so we cannot make Files available on non-Windows platforms. Thanks for your enthusiasm.
