### ISSUE TITLE
Client-server software directory, such as ownCloud, doesn't appear where it is located.

### ISSUE THREAD

**Issue by cabg2101** [files-community/Files#3734]
**Describe the bug**
Client-server software directory, such as ownCloud, doesn't appear where it is located.
My ownCloud access is a subfolder of "%userprofile%". When viewing the folder "%userprofile%", ownCloud is not visible. But if I manually type "%userprofile%\ownCloud" in the address bar, then I can view ownCloud's folders.

**To Reproduce**
1. Install ownCloud as a subfolder of "%userprofile%";
2. View contents of "%userprofile%" folder;
3. Manually type "%userprofile%\ownCloud" in the address bar.

**Expected behavior**
You should not see ownCloud from "%userprofile%", but you should be able to access it by manually typing it in the address bar.

**Screenshots**
![image](https://user-images.githubusercontent.com/43766269/109249370-90611700-77b5-11eb-9424-87c76040161b.png)
![image](https://user-images.githubusercontent.com/43766269/109249404-a078f680-77b5-11eb-955f-106624bea7d1.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.804
 - App version: 1.3.0.0

**Additional context**
Should always occur.

**Log file**
Should not be necessary, but I'll upload it upon request.

**Comment by Msouza91** [comment]
I have experienced this too, if I type the address of the folder in the path bar it opens normally, but it doesn't show up as a cloud drive or a normal folder...

**Comment by Drannor-Dosalith** [comment]
I have experienced this too, with owncloud and google drive.

**Comment by Msouza91** [comment]
Update:
Installed files again, now on windows 11, 2.1.13 the cloud drive shows up on the %userprofile% folder with the correct icon, but still isn't recognized as a cloud drive.

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?

**Comment by cabg2101** [comment]
I think not, but I don't use ownCloud anymore. I'm only going off of what I remember ~8 months ago. If other people could chime in to confirm, that would be nice.
