### ISSUE TITLE
Explode tabs view

### ISSUE THREAD

**Issue by HenryOfCarim** [files-community/Files#3740]
**Is your feature request related to a problem? Please describe.**
One thing that forces me to go back to Explorer is that sometimes I need more than 2 opened window ( often I need 5 or 6) and explorer gives the opportunity to make compact windows and arrange them with the Fancy Zones

**Describe the solution you'd like**
I guess "explode tabs" functionality which turns tabs into compact windows and maybe leave the side panel as a master window for them would help. Also, the master window should "reunite" functionality to bring back ordinary view with tabs.

**Describe alternatives you've considered**
Maybe there isn't the best solution and Doble Panel view will develop to Multi Panel view, IDK

**Additional context**
![Untitled-1](https://user-images.githubusercontent.com/18252816/109280090-40b93480-7823-11eb-8b47-db42718a39b5.png)

**Comment by yaichenbaum** [comment]
@gave92 Is it possible to expand dual pane to allow more than two panes?

**Comment by gave92** [comment]
@yair100 some work is necessary but it's not impossible. All panes will have its own navigationbar.

**Comment by yaichenbaum** [comment]
@gave92 This may be something to look into especially for users with larger screens.

**Comment by gave92** [comment]
@yair100 both multi pane and column view probably

**Comment by yaichenbaum** [comment]
@gave92 Column view is a little different since it only gets one nav bar.

**Comment by yaichenbaum** [comment]
@HenryOfCarim we don't have any plans to implement compact tabs however you can take advantage of the dual pane feature to achieve a similar setup.
