### ISSUE TITLE
Add support for third-party copy engines

### ISSUE THREAD

**Issue by EgorBryantsev** [files-community/Files#3742]
**Is your feature request related to a problem? Please describe.**
I do not really like the copy aspect of files, no offense. It is normally slower than windows copy and doesn't show the progress or time remaining as precisely. This is one of the biggest reasons I still haven't switched to files. 

**Describe the solution you'd like**
I would like for there to be an option to copy files with native file explorer instead of the files, or if possible to add support for third-party copy software like TeraCopy. 

**Describe alternatives you've considered**
Either giving an option to enable windows file copy or enable third-party copy software would be nice.

**Additional context**
I do not know much about app design, I am only giving my input as to what would make the app better. If this is impossible or too hard to do then do not worry about it.

**Comment by djmodeste** [comment]
This request is the exact reason I came here.  I primarily transfer between drives/NAS and set Teracopy as my default file copy manager.  I would very much like to be able to use external file copy managers and this is the primary reason I have not switched to Files as my primary file explorer.

**Comment by vivadavid** [comment]
I use Teracopy for all my copying purposes and I'd love to be able to use it in Files too, especially to take advantage of the hashcheck.

**Comment by d2dyno1** [comment]
@yair100 What's your word on this one?

**Comment by yaichenbaum** [comment]
@EgorBryantsev does tera copy add an option to the context menu?

**Comment by yaichenbaum** [comment]
@Ciberbago we're working on adding a speed graph to Files. Rather than adding integrations for third-party solutions, we'd rather improve the built-in option.
