### ISSUE TITLE
Enable right click sidebar to map drive and disconnect drive

### ISSUE THREAD

**Issue by jesusdpa1** [files-community/Files#3745]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I think it will be really useful to have enable the option to right click on top of Drives in the sidebar to map additional drives instead of having to go to home to map the network drive. It will also useful to include, as in nautilus, an arrow by the side of mounted drives network or physical to unmount them.
**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by Josh-65** [comment]
This has been added in 2.1.12.0
