### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by dreaddr** [files-community/Files#3747]
**Describe the bug**

**To Reproduce**
1. Go to '....'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: Edition	
Windows 10 Pro
Version	20H2
Installed on	‎03-‎Feb-‎21
OS build	19042.804
Experience	Windows Feature Experience Pack 120.2212.551.0

 - App version: [v1.2.20]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`, you should see a file in this directory called debug.txt or/and debug_fulltrust.txt.
[debug.txt](https://github.com/files-community/Files/files/6052264/debug.txt)

**Comment by dreaddr** [comment]
Also, just a suggestion as I imagine these crashes happen often, a button to send the System information and Debug information with a single click (stripped of personal identifying information) would be nice.

**Comment by yaichenbaum** [comment]
We need a little more information from you in order to investigate this issue, please reopen this issue once you have filled out the issue template.

**Comment by dreaddr** [comment]
I believe all I did was wake the system from sleep and then when I unlocked to the desktop, a crash notification awaited me in the action center. 

Restarted the app, decided to report it and realized I hadn't updated to the latest version, rocking 1.3 now.

Can the devs add one button debug reports to be sent with the consent of the users though? That would save a ton of time for these random crashes, without having to make an entire GitHub issue. #3755 and #3762 voice similar suggestions.

**Comment by bl-ue** [comment]
>please reopen this issue once you have filled out the issue template.

@yair100 FYI&mdash;when a repository collaborator closes an issue, the OP can't reopen it.  If the OP closed it, he can reopen it, but if a collaborator closed it, no one but other collaborators can reopen it.

**Comment by yaichenbaum** [comment]
@dreaddr Is this still an issue with v1.3?

**Comment by dreaddr** [comment]
> @dreaddr Is this still an issue with v1.3?

Nope, just occasionally the app freezing and hanging, but no crashes yet since then, although I must imagine there are edge cases to be ironed out now, maybe this was one of them.
