### ISSUE TITLE
Details View issue  

### ISSUE THREAD

**Issue by ShroniX** [files-community/Files#3749]
**Describe the bug**
if change the size of the detailed view top bar (Name , type, size etc.) and i close the app and open it back up the sizes resets to the default.

**To Reproduce**
1. Go to '....'

**Expected behavior**
To stay what i changed to.

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: 21H1 19043.844
 - App version: v1.3.0.0

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`, you should see a file in this directory called debug.txt or/and debug_fulltrust.txt.

**Comment by gave92** [comment]
Merging with #2675
