### ISSUE TITLE
Single click

### ISSUE THREAD

**Issue by ShroniX** [files-community/Files#3750]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
An option to chose to Open files and folders with double or single click like in the original windows file explorer

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by yaichenbaum** [comment]
We need a little more information from you in order to investigate this issue, please reopen this issue once you have filled out the issue template.
