### ISSUE TITLE
Error extracting .zip

### ISSUE THREAD

**Issue by rusti4** [files-community/Files#3753]
When right clicking on file > more > 7zip > extract, it brings up an error as per the image.

![image](https://user-images.githubusercontent.com/24264511/109373863-936b1d00-7905-11eb-955e-6d588b08f03a.png)
![image](https://user-images.githubusercontent.com/24264511/109373936-dfb65d00-7905-11eb-9af7-c31a5c9fca1c.png)

Edition	Windows 10 Pro
Version	21H1
Installed on	‎28/‎10/‎2020
OS build	19043.844
Experience	Windows Feature Experience Pack 120.2212.3030.0

[debug.txt](https://github.com/files-community/Files/files/6053634/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6053635/debug_fulltrust.txt)

**Comment by gave92** [comment]
Mm cannot reproduce. Does this happen in any folder? Or just when extracting in certain folders? Do the other 7zip menu items work?

**Comment by rusti4** [comment]
Its intermittent it seems. I just had this issue (see picture) where it didn't even give me the option to "Open With". Then it crashed and I reopened and its now working.
![screenshot](https://user-images.githubusercontent.com/24264511/109733799-f1547900-7c13-11eb-8a39-b665c7dc35c3.jpg)
![Picture3_LI (2)](https://user-images.githubusercontent.com/24264511/109733812-f7e2f080-7c13-11eb-8305-bacff3b234d5.jpg)

**Comment by gave92** [comment]
@rusti4 could you try to delete the two log files and, if the issue (crashing/missing menu items) happens again, post the new log files? Thanks!

**Comment by rusti4** [comment]
I cant seem to "break" it. I will keep my eye on it and see what happens. Happy for you to close if you prefer and I can come back to it if it persists.
