### ISSUE TITLE
using "git push" in command line still says ""master" instead of "main"

### ISSUE THREAD

**Issue by sman40901** [files-community/Files#3754]
**Describe the bug**
"git push" without upstream yields following result:
fatal: The current branch master has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin master // instead of "master" this should be "main"

**To Reproduce**
1. Go to 'command prompt' and do 'git push'

2. See error
fatal: The current branch master has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin master 

**Expected behavior**
fatal: The current branch master has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin main

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2 19042.804]
 - App version: [e.g. v1.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`, you should see a file in this directory called debug.txt or/and debug_fulltrust.txt.

**Comment by gave92** [comment]
Closing this as unrelated to Files. If you need help with git let us know
