### ISSUE TITLE
Random Crashes

### ISSUE THREAD

**Issue by GiornoJJ** [files-community/Files#3755]
Hello,
I have been using the app for a month now I believe and I get random crashes very often. While I am simply browsing the app it fails to load my files and soon after crashes. Moreover, if the app is idle for a long time say about 15 mins, it crashes.
I hope that you will look into the problem because regular problems like this makes it difficult to use the app as a daily driver.
Thank You,
Have a good day.

**Comment by gave92** [comment]
Hello thanks for this report. Please add the app version and the log files to the issue description.
