### ISSUE TITLE
Active Tab Accent Colour or Bold Text on Active Tab

### ISSUE THREAD

**Issue by infuriatedcodex** [files-community/Files#3756]
**Is your feature request related to a problem? Please describe.**
[FEAT Request]
This is based on the App Theme using "Dark" Mode or even "Windows Default" when system is set to Dark mode.
It is much more difficult to see which tab is currently Active when compared to Light Mode.

**Describe the solution you'd like**
When using Dark Mode, either the Active tab has a noticeable lighter accent/shade compared to the inactive tab.

**Describe alternatives you've considered**
Give the active tab text a different colour e.g. standard white for inactive and Light Blue for active (or a settings choice).

**Additional context**
See attached example of how light mode tabs are so much easier to see compared to dark.
![Dark](https://user-images.githubusercontent.com/40537324/109384584-bdace280-78e5-11eb-9d2d-a59b478cdd52.jpg)
![Light](https://user-images.githubusercontent.com/40537324/109384590-c43b5a00-78e5-11eb-904d-e3e7dfaf1ba3.jpg)

**Comment by gave92** [comment]
Thanks for this report, this is something we're looking to improve. Merging with #3384
