### ISSUE TITLE
File thumbnails are not loaded

### ISSUE THREAD

**Issue by CRH380AM0204** [files-community/Files#3757]
I like your software very much. Your software is taking me away from Windows Explorer.
But there is a problem that always bothers me, when I want to find pictures quickly, I can't easily find them in the Files, I think thumbnail is very important, so please add it, it will make your software more perfect.

**Comment by gave92** [comment]
Hello, thanks for this report. Thumbnails should be present in Grid View. Are you not getting them?

![image](https://user-images.githubusercontent.com/9673091/109386825-bc87af80-78fd-11eb-9c23-2509542dc05d.png)

**Comment by CRH380AM0204** [comment]
I saw only a small percentage of images with thumbnails, and when there were more images in a single folder, the program reported an error and shut down automatically
![微信截图_20210227201837](https://user-images.githubusercontent.com/53986798/109386922-004bda80-7939-11eb-924e-c7eac71d69cc.png)

**Comment by gave92** [comment]
Does refreshing the folder make the thumbnails appear?
Could you post the app's log files? Thanks!

**Comment by CRH380AM0204** [comment]
I don't know where to find the log File. The version I downloaded is UWP version so I can't find the File directory.

**Comment by gave92** [comment]
Log files:
You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`, you should see a file in this directory called debug.txt or/and debug_fulltrust.txt.

App's version is in Settings:
![image](https://user-images.githubusercontent.com/9673091/109387047-2ce30080-78ff-11eb-924d-0cd9bfbae86b.png)

**Comment by CRH380AM0204** [comment]
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6054401/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6054402/debug.txt)

**Comment by yaichenbaum** [comment]
@CRH380AM0204 This issue should be resolved with #3760.
