### ISSUE TITLE
Ctrl + N Shortcut misbehaviour

### ISSUE THREAD

**Issue by DanteJenzie** [files-community/Files#3767]
Shortcut Ctrl + N opens 2 new instances of Files instead of 1

**Expected behaviour**
To open a new instance of Files, instead of 2.

**Screenshots**
![image](https://user-images.githubusercontent.com/66542187/109411431-16ed4280-79c8-11eb-9038-7257b7e54c24.png)

 - OS Version: Windows 10 20H2 19042.844]
 - App version: v1.3

**Additional context**
Does this problem occur again after restarting the app? Yes

**Comment by yaichenbaum** [comment]
@DanteJenzie This issue should be resolved with #3770.
