### ISSUE TITLE
Add an option to remove Recent Items in home folder

### ISSUE THREAD

**Issue by alladinmf99** [files-community/Files#3772]
**Is your feature request related to a problem? Please describe.**
I think you should have an option to remove the tab due to privacy concerns. 
For example if some is standing behind you, you might not want them to see what you where just looking at/doing.

**Describe the solution you'd like**
Add an option under Settings > Preferences to remove the feature.

**Describe alternatives you've considered**
Could add exceptions to chosen folders, ie don't show recent files/folders in folder X.

**Additional context**
![Recent Items](https://user-images.githubusercontent.com/76444330/109419998-79e2d780-79d0-11eb-91c9-f1ba07ad9f84.png)

**Comment by gave92** [comment]
Hi, there's already a setting for this -> Settings > Widgets > Show recent items on homepage

![image](https://user-images.githubusercontent.com/9673091/109420203-726ffe00-79d1-11eb-86a9-778a3ec7291f.png)
