### ISSUE TITLE
Executeable files cannot be run

### ISSUE THREAD

**Issue by Ma-ikaJT** [files-community/Files#3780]
Executeable files can be shown just fine in the Files view, but cannot actually be executed in any display mode the way they can be in File Explorer. Running Windows 10 Insider build 21322 on two different PCs (Microsoft Surface Pro 7 and a custom-built desktop PC), both of which exhibit this issue.

**Comment by gave92** [comment]
This is a known problem of windows insider builds. I'd bet that also the context menu only shows some basic items and not the full explorer menu.
