### ISSUE TITLE
Do these files need to update?

### ISSUE THREAD

**Issue by pklion** [files-community/Files#3785]
The following files have versions and copyright in them.
https://github.com/files-community/Files/blob/main/MessageRelay/Properties/AssemblyInfo.cs
https://github.com/files-community/Files/blob/main/Files.Launcher/Properties/AssemblyInfo.cs
https://github.com/files-community/Files/blob/main/Files/Properties/AssemblyInfo.cs
https://github.com/files-community/Files/blob/main/Files/Package.appxmanifest
Do these files need to update?

**Comment by yaichenbaum** [comment]
@pklion Those files are fine, we can leave them how they are.

**Comment by pklion** [comment]
Understood.
