### ISSUE TITLE
Add a Split view in tab

### ISSUE THREAD

**Issue by Octoton** [files-community/Files#3787]
Tab are a great addition to the windows file experience, however when comparing two folder/transfering files from one to another a split view inside the explorer is even coller to have.
You could open two explorer and put them one left of the screen, one right but you lose a lot of horizontal space because of the sidebar (can be a problem on small screen) and if you are doing this for multiple project at the same time, you can easily loose track of which folder where compared to which other, the ability to group them is simpler on the mind

On the linux world, kde plasma dolphin app (the offical file app) does this great:
![split](https://user-images.githubusercontent.com/56130419/109641656-3e701680-7b52-11eb-8f1b-200e54b920b5.jpg)

**Comment by yaichenbaum** [comment]
@Octoton A dual pane feature is already available, you can turn this feature on from the multitasking settings page. Is this what you were looking for?

**Comment by Octoton** [comment]
I miss it
