### ISSUE TITLE
deleting bug

### ISSUE THREAD

**Issue by iamhashimov** [files-community/Files#3788]
**Describe the bug**

**To Reproduce**
1. Go to '....'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2 19042.804]
 - App version: [e.g. v1.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`, you should see a file in this directory called debug.txt or/and debug_fulltrust.txt.

**Comment by d2dyno1** [comment]
Could you explain where the issue lies, and provide a log file?

**Comment by iamhashimov** [comment]
when im trying to delete something(big files or folder) app just closing

**Comment by yaichenbaum** [comment]
@iamhashimov What version of Files do you have?
