### ISSUE TITLE
Does not show timestamps at "Date Created" and "Date Modified" (partially) when Android devices are connected

### ISSUE THREAD

**Issue by createdtime** [files-community/Files#3792]
**Is your feature request related to a problem? Please describe.**
Files (1.3) shows timestamp at "Date Created" for Android devices although android devices do not support it.

**Describe the solution you'd like**
No time is displayed at "Date Created" exactly the same behavior as with Windows Explorer (Windows 10).

It is well known that Android system does not support created time. The Android emulated file system does not store created time and generally Linux system does not support it. I hate Android and Linux.

**Describe alternatives you've considered**
n/a

**Additional context**
Dear Files developer, when Android devices are connected, the first view you see is the "Internal Storage".

Here you will see "Date modified" and "Date created". This is wrong this area generally does not support timestamps. In Windows Explorer (Windows 10), the user has no way to view "Date modified" and "Date created" because it is a drive that does not behave properly as a normal USB external hard drive. This is also the reason why Microsoft does not display it in Windows Explorer, because Android devices are not good and Linux systems are bad. User unfriendly behavior and the google developers have created inferior system.

Note: Windows has supported created time for 20 years. Since at least Windows XP (2001) for the users.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@createdtime, the comment about whether Android and Linux are 'good' is utterly irrelevant to a bug-report.
