### ISSUE TITLE
Shows wrong folder active

### ISSUE THREAD

**Issue by rusti4** [files-community/Files#3794]
**Describe the bug**
OneDrive folder is open but the line next to the active folder is incorrect.

**Screenshots**
![image](https://user-images.githubusercontent.com/24264511/109735369-c28bd200-7c16-11eb-9e63-bff3c78adb55.png)

**Desktop (please complete the following information):**
Edition	Windows 10 Pro
Version	21H1
Installed on	‎28/‎10/‎2020
OS build	19043.844
Experience	Windows Feature Experience Pack 120.2212.3030.0

 - App version: 1.3.0.0

**Log file**
[debug.txt](https://github.com/files-community/Files/files/6072883/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6072884/debug_fulltrust.txt)

**Comment by duke7553** [comment]
@rusti4 Is this still an issue on the v2 release?
