### ISSUE TITLE
Open With doesn't work

### ISSUE THREAD

**Issue by rusti4** [files-community/Files#3796]
**Describe the bug**
Open With doesn't work for non standard file types. i.e.   .rb (ruby program)

**To Reproduce**
Right click on a file and attempt to open with.

**Expected behaviour**
Open window with options for opening file.

**Screenshots**
https://user-images.githubusercontent.com/24264511/109736632-c882b280-7c18-11eb-8a88-9f1685c7345a.mp4

**Desktop (please complete the following information):**
Edition	Windows 10 Pro
Version	21H1
Installed on	‎28/‎10/‎2020
OS build	19043.844
Experience	Windows Feature Experience Pack 120.2212.3030.0

 - App version: 1.3.0

**Log file**
[debug.txt](https://github.com/files-community/Files/files/6072911/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6072912/debug_fulltrust.txt)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5674.
