### ISSUE TITLE
Add the option to hide columns in the details layout mode

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#380]
We should add the option to edit which columns show.

**Comment by Cyberdroid1** [comment]
When will this be included? I am waiting for it to arrive to make this app much more better.

**Comment by yaichenbaum** [comment]
@Cyberdroid1 #2622 resolves this issue, so it should be available in one of the next updates.

**Comment by Cyberdroid1** [comment]
Thanks!
