### ISSUE TITLE
Bug when trying to change Multitasking settings

### ISSUE THREAD

**Issue by Cyberdroid1** [files-community/Files#3802]
**Describe the bug**
When trying to change the Multitasking settings in Files, I often face this bug where I choose an option among the 3, change the settings tab to any other part (say, the About window) and when I get back to Multitasking tab, it either would not remember the setting, or no option is selected.

**To Reproduce**
1. Go to Setting > Multitasking
2. Click on one of the non-selected options
3. Change to any other tab in settings, and then change back to Multitasking

**Expected behavior**
It should remember which setting I had chosen.

**Screenshots**

![image](https://user-images.githubusercontent.com/51435948/109781587-0f2ed780-7c2e-11eb-9b4e-16315341316a.png)

**Desktop (please complete the following information):**
 - OS Version: e.g. Windows 10 20H2 19042.844
 - App version: 1.3.0.0

**Additional context**
I have a video recording.

https://user-images.githubusercontent.com/51435948/109781870-4a310b00-7c2e-11eb-96ad-90bd1d071a58.mp4

**Log file**

No error was caught in the log files :/

**Comment by Cyberdroid1** [comment]
Maybe #3088 is similar?

**Comment by gave92** [comment]
@yair100 does #3798 fix this?

**Comment by yair100** [comment]
> @yair100 does #3798 fix this?

@gave92 It doesn't look like it, we can probably fix this by switching to a dropdown menu instead of radio buttons.

**Comment by yaichenbaum** [comment]
@Cyberdroid1 This issue should be resolved with #3849.
