### ISSUE TITLE
[Enhancement] Improve performance for opening, closing, and switching tabs

### ISSUE THREAD

**Issue by winston-de** [files-community/Files#3805]
**Is your feature request related to a problem? Please describe.**
There are some performance issues with opening, closing, and switching tabs. This reduces their usefulness.

- Opening a new tab takes around 1-2 seconds
- Switching tabs can take several seconds. This is worse for large folders, eg system32
- Closing tabs can also take several seconds

For reference purposes, I'm on an i5-8250U with 8gb of ram.

**Describe the solution you'd like**
I think some investigation should be done into ways to improve performance for these operations. I'll start looking myself, and if I find anything I'll add them to this issue.

Some initial thoughts I had:
- Use a single new home page instance across the entire app instance, so that it doesn't have to re-load when a tab is opened
- Do clean-up operations for closing tabs after the tab has closed, so there isn't a visible delay for closing tabs

**Describe alternatives you've considered**
N/A

**Additional context**
Maybe it would be worth considering making a tab performance benchmark test to make it easier to locate any issues. 

Also, I'm guessing this is at least somewhat related to #2843

**Comment by winston-de** [comment]
I believe the cause of this issue is the amount of layout that has to be done when a tab is opened or switched. This can be especially hard on devices with low GPU resources.

However, as far as I can tell, this issue has been mostly solved in the main branch.
#3737 seems to have significantly reduced the amount that has to be laid out, speeding up the process for opening and switching tabs.

I do not believe there is much else that can be done for this issue, although it may be worth looking at improving efficiency overall in the future.

**Comment by YuanfengZhang** [comment]
> I believe the cause of this issue is the amount of layout that has to be done when a tab is opened or switched. This can be especially hard on devices with low GPU resources.
> 
> However, as far as I can tell, this issue has been mostly solved in the main branch.
> #3737 seems to have significantly reduced the amount that has to be laid out, speeding up the process for opening and switching tabs.
> 
> I do not believe there is much else that can be done for this issue, although it may be worth looking at improving efficiency overall in the future.

I don't think #3737 is related to this issue. Switching between two tabs of empty folder still lags for about 1 sec.
Configure: 32GB 3600MHz RAM, NV GTX 1070Ti(only 0.1% used by Files when switching tabs), AMD R5 3600X(5% used). 

Maybe there is plenty of scope to increases GPU utilization for better performance.
