### ISSUE TITLE
Copying files between any two folders is invalid and nothing happens

### ISSUE THREAD

**Issue by sansuijiuhenku** [files-community/Files#3811]
**Describe the bug**

**To Reproduce**
1. Go to '....'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2 19042.804]
 - App version: [e.g. v1.3.0.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`, you should see a file in this directory called debug.txt or/and debug_fulltrust.txt.

**Comment by gave92** [comment]
Is this happening when doing ctrl+c / ctrl+v? Or also when using copy/paste from the context menu?
Could you post the app's log files?

**Comment by sansuijiuhenku** [comment]
[debug.txt](https://github.com/files-community/Files/files/6089271/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6089272/debug_fulltrust.txt)



Is this happening when doing ctrl+c / ctrl+v? Or also when using copy/paste from the context menu?——YES

Happy thing, when I just verified this problem, I found that it was all right.

**Comment by gave92** [comment]
Thanks for the info. Closing this for the moment. If it happens again, please let us know ;)
