### ISSUE TITLE
Sidebar path

### ISSUE THREAD

**Issue by sansuijiuhenku** [files-community/Files#3812]
**Describe the bug**
The sidebar does not support custom sorting

**To Reproduce**
1. Go to '....'

**Expected behavior**
Hope you can customize the sorting

**Screenshots**
http://jinlan.synology.me:25227/image/JFD

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2 19042.804]
 - App version: [e.g. v1.3.0.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`, you should see a file in this directory called debug.txt or/and debug_fulltrust.txt.

**Comment by gave92** [comment]
Thanks for this report. Please describe this issue with more details and post the log files.

**Comment by PMExtra** [comment]
@gave92 He is request a new feature: resorting the Pinned directory in sidebar.

**Comment by gave92** [comment]
Thanks for clarifying, I misread this.
Unfortunately the requested feature is already implemeted but disabled due to a bug in the WinUI library
