### ISSUE TITLE
Hitting the spacebar to toggle the file/folder preview pane when quicklook is not installed

### ISSUE THREAD

**Issue by erayrafet** [files-community/Files#3813]
**Describe the solution you'd like**
I would like to have the spacebar trigger the folder/file preview pane on the right, similar to the Finder app on MacOS.
https://computing.which.co.uk/hc/en-gb/articles/207764589-Use-Quick-Look-in-Mac-Finder#:~:text=Mac%20Finder%20has%20a%20little,the%20Spacebar%20on%20your%20keyboard.

**Additional context**
As of right now, the spacebar does the same as enter, so remaping that won't break anything.
![image](https://user-images.githubusercontent.com/34194191/109920739-68951600-7cc3-11eb-9dbd-e9edb0c077b8.png)

**Comment by Ein-Tim** [comment]
@erayrafet 

If you have QuickLook installed on your machine and you hit the space bar you can preview files.

**Comment by erayrafet** [comment]
@Ein-Tim Yeah, but having the same spacebar key, in the absence of QuickLook, toggling the built-in preview option would be nice to have.

**Comment by Josh-65** [comment]
Merging with #9559
This will be an option when made.

**Comment by cmactavish** [comment]
Was this implemented in the most recent release? Have tried searching for the option, but can't find it.

**Comment by yaira2** [comment]
@erayrafet This feature will be included in the next release. Please see #9559 for more details.

**Comment by yaira2** [comment]
> Was this implemented in the most recent release? Have tried searching for the option, but can't find it.

@cmactavish this feature isn't available yet but it will be included in v3.4.
