### ISSUE TITLE
Confusing inconsistency with a draggable zone on the top of the sidebar

### ISSUE THREAD

**Issue by Tester09** [files-community/Files#3815]
**Describe the bug**
Almost every windows' app with the sidebar has a draggable area on top of it and it's almost a habit to drag the window from here but Files didn't support this feature. The previous design wasn't so frustrating because it was copying an internet browser UX where you have only a small draggable area near the minimize button. However, with the old-new UI, the old frustration is back.
The most confusing thing is that you can open the Files' setting and get the draggable area what you expect.

**To Reproduce**
1. Go to 'settings'
2. Click and drag on the top of the sidebar
3. Go back to Files
4. See the undruggable thin line in the same area

**Expected behavior**
IDK is it possible at all to add this draggable area for the main windows but without it will be always an eyesore 

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: Windows10 21322.1
 - App version: 1.3.5

**Comment by yaichenbaum** [comment]
Merging with #4144.
