### ISSUE TITLE
Making a template for PR

### ISSUE THREAD

**Issue by pklion** [files-community/Files#3816]
**Is your feature request related to a problem? Please describe.**
There are templates for issues. but for PR aren't.

**Describe the solution you'd like**
I think making a template for PR would be better.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by yaichenbaum** [comment]
@pklion Would you like to work on this?

**Comment by pklion** [comment]
Yes, I'll make one so please wait.
