### ISSUE TITLE
File extension change warning dialog not fully localized

### ISSUE THREAD

**Issue by nvi9** [files-community/Files#3820]
**Describe the bug**
The title and buttons of the file extension change warning dialog are not localized, they're always in English.

**To Reproduce**
1. Change app language to anything else but English (or System default if it is English)
2. Select any file
3. Right click > Rename / press F2
4. Change extension part of the filename
5. See dialog with only the message localized

**Expected behavior**
The title and the button texts should show localized texts.

**Screenshot**

![image](https://user-images.githubusercontent.com/42123156/109975760-45865880-7cfb-11eb-938b-2b8e3e97cd01.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.804
 - App version: v1.3.0

**Comment by nvi9** [comment]
Can be fixed with adding `.GetLocalized()` extensions here and using the already defined resource strings for the buttons (`ButtonYes.Content` and `ButtonNo.Content`) and maybe a new one for the title or reuse `BaseLayoutItemContextFlyoutRename.Text`:

https://github.com/files-community/Files/blob/52489fd9336711e7f45106e50e11be53f63a5a61/Files/Filesystem/FilesystemOperations/Helpers/FilesystemHelpers.cs#L763

**Comment by yaichenbaum** [comment]
@nvi9 Do you want to work on this issue?

**Comment by yaichenbaum** [comment]
@nvi9 This issue should be resolved with #4992.
