### ISSUE TITLE
Acrylic gone in 13.5.0 (Is that intentional?)

### ISSUE THREAD

**Issue by SOI7** [files-community/Files#3821]
**Describe the bug**
Reveal effects in the Home page are gone. Is that intentional?

**To Reproduce**
Just hover the mouse over the Home page buttons

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2
 - App version: v1.3.5.0

**Comment by yaichenbaum** [comment]
@SOI7 Thanks for asking! The removal of reveal on the widgets was intentional, we are still working on the widgets design and will ship further improvements in future insider builds.
