### ISSUE TITLE
Horizontal space between Drives header and "..." menu is too large

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#3822]
![image](https://user-images.githubusercontent.com/17484252/110000470-9d30be00-7d13-11eb-8b87-171103e1f95c.png)

In my opinion, the "..." menu should be placed directly next to the header. Same goes for Bundles.

![image](https://user-images.githubusercontent.com/17484252/110000939-247e3180-7d14-11eb-89f1-7804a5826d19.png)

**Comment by asuetin** [comment]
I think this approach should only apply to cases where the space between the text and the button can scale indefinitely. So I agree with the home page headers part, not so much with the bundles part. 

I also think it'll look better if the buttons remain in the same "column", with the spacing being dependent on the width of the longest header ("Recent items" currently).

**Comment by yaichenbaum** [comment]
Merging with #7287
