### ISSUE TITLE
QuickLook doesn't work!

### ISSUE THREAD

**Issue by Saeed-Tavoosi** [files-community/Files#3823]
**Describe the bug**

I have Files, and also installed QuickLook (*.msi) but it only works with Windows 10 File Explorer, not with Files App.
**To Reproduce**
1. Go to 'Files'
2. Click on 'any file'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version:  Windows 10 21H1 19043.844 (Beta Channel)
 - App version: 1.3.0.0
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6085729/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6085731/debug.txt)

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`, you should see a file in this directory called debug.txt or/and debug_fulltrust.txt.

**Comment by gave92** [comment]
Known issue of newer insider builds. Something we expect Microsoft to fix.

**Comment by Saeed-Tavoosi** [comment]
> Known issue of newer insider builds. Something we expect Microsoft to fix.
> 
> @Saeed-Tavoosi could you post a screenshot of the right click context menu that appears in Files so I can confirm the issue?

![Screenshot 2021-03-04 220534](https://user-images.githubusercontent.com/78601755/110012486-cfebae00-7d35-11eb-87fb-3f198c3150d7.jpg)

**Comment by gave92** [comment]
Nope, not the issue I expected. Thanks @Saeed-Tavoosi, we'll investigate this.

**Comment by gave92** [comment]
@Saeed-Tavoosi just one thing: quick look must be opened *before* opening files, could you check if closing/reopening the app fixes this?

**Comment by Saeed-Tavoosi** [comment]
> Nope, not the issue I expected. Thanks @Saeed-Tavoosi, we'll investigate this.

When I set Files as default File Explorer, QuickLook worked. but when I select files with arrow keys (while in QuickLook), quicklook doesn't refresh and I should press space for every file.

**Comment by Saeed-Tavoosi** [comment]
> @Saeed-Tavoosi just one thing: quick look must be opened _before_ opening files, could you check if closing/reopening the Files app fixes this?

It was open, windows file explorer worked fine with that.

**Comment by gave92** [comment]
> When I set Files as default File Explorer, QuickLook worked.

Thanks for the info

> When I select files with arrow keys (while in QuickLook), quicklook doesn't refresh and I should press space for every file.

Yeah that's known

**Comment by Raithlin** [comment]
Is this still an issue? I am unable to replicate the issue using QuickLook 3.7.1 and Files 2.0.34 (set as default File Explorer or not makes no difference).
