### ISSUE TITLE
Re-order Sidebar

### ISSUE THREAD

**Issue by Saeed-Tavoosi** [files-community/Files#3824]
**Is your feature request related to a problem? Please describe.**
We can't order Sidebar items.

**Describe the solution you'd like**
drag items to re-order.

**Describe alternatives you've considered**

**Additional context**

**Comment by gave92** [comment]
This feature was already implemented but is currently blocked by an issue with the WinUI repo, I am linking it here so you can upvote/comment on the issue and hopefully increase the priority for Microsoft microsoft/microsoft-ui-xaml#3290.
