### ISSUE TITLE
Playback buttons in taskbar

### ISSUE THREAD

**Issue by Saeed-Tavoosi** [files-community/Files#3827]
**Describe the bug**
in the preview of Files in taskbar, there is playback buttons, and sonetimes when changing volume it appears as a media app.

**To Reproduce**
1. Go to Files's Icon on taskbar
2. hover mouse on that
3. See playback buttons

**Expected behavior**
Should not see any playback button!

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/78601755/110024398-725e5e00-7d43-11eb-8017-e9e9fbe1e278.jpg)

**Desktop (please complete the following information):**
 - OS Version:  Windows 10 21H1 19043.844 (beta Channel)
 - App version: 1.3.0.0

**Additional context**

**Log file**
[debug.txt](https://github.com/files-community/Files/files/6086406/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6086409/debug_fulltrust.txt)

**Comment by yaichenbaum** [comment]
@Saeed-Tavoosi This issue was an issue with some versions of Windows but it appears to be fixed in the latest Windows Insider build.

**Comment by Saeed-Tavoosi** [comment]
> @Saeed-Tavoosi This was an issue with some versions of Windows but it appears to be fixed in the latest Windows Insider build.

I have latest version of beta build, ok then I'll wait for next patch.
