### ISSUE TITLE
UI design suggestions after 1.3.5.0

### ISSUE THREAD

**Issue by asuetin** [files-community/Files#3830]
**Is your feature request related to a problem? Please describe.**
I feel like the UI design in 1.3.5.0 is a little confused between the classic UWP two-pane aesthetic and the Chromium Edge aesthetic with more solid grays, which results in the app being just kind of a gray mess where everything blends together.

![image](https://user-images.githubusercontent.com/37500046/110080891-2c81b400-7d9c-11eb-9623-d1587220f707.png)
![image](https://user-images.githubusercontent.com/37500046/110082293-33112b00-7d9e-11eb-9d74-d691d825a62c.png)

**Describe the solution you'd like**
Stick to the UWP two-pane aesthetic with an acrylic/gray sidebar and white content area. I think it works and looks better in a file manager where all pages have a uniform background color, unlike Edge where each page is unique.

Also, the preview pane button and the overflow menu having a whole row to themselves seems very strange. Either move them to the same row as the address bar, or fill the row with the commands from the overflow menu, only showing the three dots when the window isn't wide enough.

I've made some mockups:

![image](https://user-images.githubusercontent.com/37500046/110081029-60f57000-7d9c-11eb-845a-8e9739d070a0.png)
![image](https://user-images.githubusercontent.com/37500046/110081063-6ce13200-7d9c-11eb-9cae-c43736ebcf07.png)

**Comment by SOI7** [comment]
Agree on the icons being on the same row, but the different shades of white/grey help a lot at separating each part of the container, and the old, full white layout made the app also harder on the eyes

**Comment by asuetin** [comment]
> Agree on the icons being on the same row, but the different shades of white/grey help a lot at separating each part of the container

Does it need further separation though? The address bar spanning nearly the entire width of the window and the vertical spacing between the bar and the content already serve the separation needs well IMO. The border isn't needed for resizing either. 

Painting the area gray just seems like ruining the two-pane look for no tangible benefit.

> and the old, full white layout made the app also harder on the eyes

That's fair. I find white backgrounds both easier on the eyes _and_ better-looking. That's all subjective of course, but I think my case is helped by the fact that white backgrounds are standard practice nowadays, and breaking from that requires strong justification.

**Comment by yaichenbaum** [comment]
> That's fair. I find white backgrounds both easier on the eyes and better-looking. That's all subjective of course, but I think my case is helped by the fact that white backgrounds are standard practice nowadays, and breaking from that requires strong justification.

@asuetin This practice is starting to change, you can expect to see inbox apps and other apps start to adapt similar style over the next few months to what we are doing in Files.

**Comment by asuetin** [comment]
> @asuetin This practice is starting to change, you can expect to see inbox apps and other apps start to adapt similar style over the next few months to what we are doing in Files.

@yair100 Really? Is there an article/design spec where I can read about this? This is not a gotcha, I'd genuinely love to know.

**Comment by yaichenbaum** [comment]
@asuetin It's still in the experimental phase and it's not final, but you can find the pull request from WinUI over here https://github.com/microsoft/microsoft-ui-xaml/pull/3898.

**Comment by asuetin** [comment]
> @asuetin It's still in the experimental phase and it's not final, but you can find the pull request from WinUI over here [microsoft/microsoft-ui-xaml#3898](https://github.com/microsoft/microsoft-ui-xaml/pull/3898).

@yair100 Huh, okay then. Thanks for the info.

Still, even if the grays have to stay, I think the design could be improved:

![image](https://user-images.githubusercontent.com/37500046/110143413-4b0d9c80-7de8-11eb-8e07-fac4ba896e7c.png)

1. Removed the unnecessary row with the details button and the overflow menu
2. Added an Edge-like slight drop shadow around the address bar
3. Added an Edge-like 1px border between the top bar and the content
4. Added a drop shadow between the sidebar and the main content area to better separate them
5. Removed the gray background on the bottom bar for a cleaner and more File Explorer-like look

**Comment by asuetin** [comment]
Could also do this for a more uniform right pane (I like this one the most):

![image](https://user-images.githubusercontent.com/37500046/110148831-5c59a780-7dee-11eb-9ca2-d039f36688ef.png)

Or just ditch the acrylic altogether and go full Edge:

![image](https://user-images.githubusercontent.com/37500046/110148932-7abfa300-7dee-11eb-8287-6d1a0fc2834b.png)
![image](https://user-images.githubusercontent.com/37500046/110148949-7eebc080-7dee-11eb-8fee-6b19e02d4355.png)

**Comment by asuetin** [comment]
Another option is ditching the acrylic altogether and going full Edge (but I'm in favor of retaining at least some acrylic):
![image](https://user-images.githubusercontent.com/37500046/110151122-22d66b80-7df1-11eb-80d6-bcc165e7f550.png)
![image](https://user-images.githubusercontent.com/37500046/110151134-279b1f80-7df1-11eb-9b0e-64bee2707f01.png)

**Comment by yaichenbaum** [comment]
> Removed the unnecessary row with the details button and the overflow menu

This row is necessary, we are still working on it, but we plan on adding more buttons there in the future.

> Added an Edge-like slight drop shadow around the address bar

Great feedback! This is something that we plan to do.

> Added a drop shadow between the sidebar and the main content area to better separate them

There is already a shadow there, but it looks like it's hard to see. Can you open a new issue for this?

> Removed the gray background on the bottom bar for a cleaner and more File Explorer-like look

This is something we can explore, can you open a seperate issue to start a discussion?

**Comment by asuetin** [comment]
> > Added a drop shadow between the sidebar and the main content area to better separate them
> 
> There is already a shadow there, but it looks like it's hard to see. Can you open a new issue for this?

#3850

> > Removed the gray background on the bottom bar for a cleaner and more File Explorer-like look
> 
> This is something we can explore, can you open a seperate issue to start a discussion?

#3851

**Comment by yaichenbaum** [comment]
@asuetin Thank you for opening those issues, I am going to close this issue since we are tracking the other issues separately.
