### ISSUE TITLE
Windows show the apps has media controls

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#3832]
**Describe the bug**
Not sure if this is suppose to happen but windows will treat the app as if it was a media player. It has the media controls on the taskbar windows preview

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.804
 - App version: 1.3.0.0

**Comment by gave92** [comment]
Windows issue we can't fix :(

**Comment by yaichenbaum** [comment]
@gave92 This is fixed in the Windows Insider builds.
