### ISSUE TITLE
Random scroll bar were settings button is

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#3833]
**Describe the bug**

**Screenshots**
![image](https://user-images.githubusercontent.com/26977075/110109052-dc5b1f80-7da4-11eb-8e92-c2cab9f2b09f.png)
![image](https://user-images.githubusercontent.com/26977075/110109091-e5e48780-7da4-11eb-9e7e-38ac24f29505.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.804 
 - App version: 1.3.0.0

**Comment by yaichenbaum** [comment]
@josh-65 This issue was fixed in a recent commit in the WinUI library so it will automatically be fixed in Files when we update to the latest WinUI release.
