### ISSUE TITLE
Bug: Shell extensions in context menu are missing their icons

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#3834]
**Describe the bug**
Custom program icons on the right click menu don't work.

**Steps to reproduce**
- Install 7zip
- Right click file or folder in Files and observe that 7zip doesn't have an icon
- Right click file or folder in File Explorer and observe that 7zip **does** have an icon

**Requirements**
- Icons should be consistent with File Explorer

Current missing ones
- [ ] VLC
- [ ] 7-zip
- [ ] WinRAR
- [ ] Google drive
- [ ] Avast anti-virus

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.804
 - App version: 1.3.0.0

**Comment by gave92** [comment]
Could you check is this is the same as #3708?
Are icons shown in the first level of the context menu?

**Comment by josh-65** [comment]
Some are. The screen shots are from the first level of the context menu. 7-zip and macrium reflect icons don't show up.

**Comment by josh-65** [comment]
Any update on this. 1.5.26 still has this issue.

**Comment by josh-65** [comment]
Still an issue with 1.5.46

![image](https://user-images.githubusercontent.com/26977075/123307250-2dd91700-d51a-11eb-83ce-a76c686c1117.png)

**Comment by josh-65** [comment]
Still an issue in 1.9.14. Updated non icon list: 7-zip, Backup and sync, Avast, Macrium reflect, Bit locker (except the c drive)

**Comment by gave92** [comment]
I don't think we can fix this, all uwp file managers seem to have this issue on the same elements.

**Comment by josh-65** [comment]
Oh disappointing. Could it be fix using the full trust part of files or WinUI?

**Comment by josh-65** [comment]
Closing due to WinUI limitations.

**Comment by PavelDobCZ23** [comment]
WinRar, Change File Extension and Windows Defender icons are missing.
Windows Explorer:
![image](https://user-images.githubusercontent.com/62188082/151662880-8db2dda0-b027-47fb-9efc-c89bc06b7996.png)
Files:
![image](https://user-images.githubusercontent.com/62188082/151662888-7ec06922-bd80-422c-aa1c-783dac413c9f.png)

**Comment by yaichenbaum** [comment]
@Josh-65 is this still an issue?

**Comment by Josh-65** [comment]
yep

**Comment by PavelDobCZ23** [comment]
> @Josh-65 is this still an issue?

yes

**Comment by yaichenbaum** [comment]
Which options are missing?

**Comment by Josh-65** [comment]
Currently these and avast anti virus (I dont have it anymore but was still missing the time it was uninstalled).
![image](https://user-images.githubusercontent.com/26977075/157322440-50157163-7820-4f66-83a4-65b9d417070f.png)

This is what they are in file exploer
![image](https://user-images.githubusercontent.com/26977075/157322511-51a9524e-636c-41c6-8924-4f60ad37478a.png) 
![image](https://user-images.githubusercontent.com/26977075/157322530-821105cb-e823-4ac7-bb07-e06faf077354.png)

**Comment by yaichenbaum** [comment]
@gave92 any ideas now that we're using WinAppSdk?

**Comment by yaira2** [comment]
I tried debugging but the API isn't returning the icon, @Josh-65 is this an issue in Explorer++ as well?

**Comment by Josh-65** [comment]
No icons there show the same as File explorer

**Comment by hishitetsu** [comment]
Icons for items without submenus are displayed by `MenuFlyoutItemWithImage` class.
https://github.com/files-community/Files/blob/main/src/Files.App/UserControls/Menus/MenuFlyoutItemWithImage.xaml.cs

However, there is no `MenuFlyoutSubItemWithImage` class, so icons for items with submenus are not displayed.
`MenuFlyoutItemWithImage` extends `MenuFlyoutItem`, but `MenuFlyoutSubItem` is sealed and can't be extended.

**Comment by yaira2** [comment]
@hishitetsu this is a limitation with the context menu?

**Comment by yaira2** [comment]
@hishitetsu looking into this further, it appears that we can set a BitmapIcon without extending the class.

**Comment by hishitetsu** [comment]
> @hishitetsu looking into this further, it appears that we can set a BitmapIcon without extending the class.

True, but I thought only static image resources could be used for BitmapIcon?

**Comment by yaira2** [comment]
Aren't the context menu icons static?

**Comment by hishitetsu** [comment]
Yes, they are dynamically retrieved as HBITMAP when the shell extensions are loaded.

**Comment by yaira2** [comment]
By static, do you mean as opposed to changing the icon after the item is already added to the menu?

**Comment by hishitetsu** [comment]
I mean resources that can be specified by URI.
