### ISSUE TITLE
Reserve space for sync status icons on cloud drives in Tile and Grid views

### ISSUE THREAD

**Issue by asuetin** [files-community/Files#3837]
**Is your feature request related to a problem? Please describe.**
Currently, when opening a cloud drive or folder, the app doesn't reserve space for sync status icons in Tile and Grid views. As a result of this, the names and icons of files/folders jump to the right once their status actually loads and the sync icons appear.

**Describe the solution you'd like**
Reserve space for the sync icons to avoid the jumpy behavior.

**Describe alternatives you've considered**
Provide a placeholder "loading sync status" icon.

**Comment by yaichenbaum** [comment]
@asuetin This issue should be resolved with #4945.

**Comment by esibruti** [comment]
@yair100 we can close this issue
