### ISSUE TITLE
QuickLook doesn't open when hitting the space bar

### ISSUE THREAD

**Issue by Ein-Tim** [files-community/Files#3838]
**Describe the bug**
QuickLook doesn't work in Files. Neither with the version from the Microsoft Store nor the .msi from [here](https://github.com/QL-Win/QuickLook/releases/tag/3.6.10).
You can open QuickLook by opening the context menu and clicking on "QuickLook", but QuickLook doesn't open when hitting the space bar. 
QuickLook works as intended in the native file explorer.

**To Reproduce**
1. Install Quick Look 
2. Open Files
3. Select a file/folder
4. Hit the space bar
5. Nothing happens

**Expected behavior**
The QuickLook preview of the file/folder should be shown.

**Screenshots**
Not possible here since nothing happens.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 Build 19042.844
 - App version: 1.3.0.0

**Additional context**
QuickLook is showing up in the context menu.
Seems like you are [aware](https://github.com/files-community/Files/issues/3823#issuecomment-790827579) of this issue, but only with insider builds.

**Log file**
[debug.txt](https://github.com/files-community/Files/files/6091267/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6091268/debug_fulltrust.txt)

**Comment by yaichenbaum** [comment]
Merging with #3823.

**Comment by Ein-Tim** [comment]
@yair100 Are you sure that this is the same issue?

**Comment by yaichenbaum** [comment]
@Ein-Tim If it's coming up in the context menu, it might be a different issue, I will reopen this.

**Comment by Ein-Tim** [comment]
Thank you 👍

**Comment by trama** [comment]
I would like to confirm the same happens to me.
QuickLook worked well up to Files 1.2, but now with v1.3 it doesn't work anymore.

Strangely, QuickLook works perfectly with classic explorer and in any other application.
Morever, the QuickLook option appears in the context menu, but again, nothing appears on the screen.

**Comment by trama** [comment]
Dear all,
with the recent update of Windows insider to 21337 all the above now works pretty good.
Both QuickLook and the Cloud service folders (i.e. Onedrive)

What does not work is the automatic update of Files, which in my case is still at 1.3 while the 1.5 is out...

Thank you for the beautiful work.

**Comment by Ein-Tim** [comment]
Can confirm fix, works as intended now. 

Thanks!

**Comment by yaichenbaum** [comment]
@trama v1.5 is rolling out in stages, so it's possible it's not yet available for your device.

@Ein-Tim Thanks for letting use know!
