### ISSUE TITLE
Wrong German translation of QuickLook in the context menu 

### ISSUE THREAD

**Issue by Ein-Tim** [files-community/Files#3839]
**Describe the bug**
The text which is shown in the pop up after right clicking a file/folder for QuickLook is wrongly translated with "Links" instead of "QuickLook" in German.

**To Reproduce**
1. Install QuickLook
2. Open Files
3. Set language to German
4. Open context menu of any file/folder
5. See wrong translation

**Expected behavior**
"QuickLook" should be translated as "QuickLook" and not as "Links".

**Screenshots**
![image](https://user-images.githubusercontent.com/67682506/110133524-b184c180-7dcc-11eb-992b-eb8a1556ee5b.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 Build 19042.844
 - App version: 1.3.0.0

**Log file**
[debug.txt](https://github.com/files-community/Files/files/6091267/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6091268/debug_fulltrust.txt)

**Comment by yaichenbaum** [comment]
@Ein-Tim Would you like to fix this issue?

**Comment by Ein-Tim** [comment]
@yair100 

Working on it

**Comment by Ein-Tim** [comment]
@yair100 I hope #3843 is good 👍

**Comment by yaichenbaum** [comment]
@Ein-Tim Great work, thank you!
