### ISSUE TITLE
Default windows explorer window

### ISSUE THREAD

**Issue by mlagardenhose** [files-community/Files#3841]
Hitting "**Win key + E**" opens windows explorer. Can "Files" be the default explorer window so that the shortcut opens "Files" instead of current default windows explorer window. 
Thanks in advance.

**Comment by yaichenbaum** [comment]
@mlagardenhose The answer is yes 🎉. You can find instructions on our documentation site https://files-community.github.io/docs/#/articles/configure-win-e.
