### ISSUE TITLE
Every time I open a folder with a lot of content, or a folder that takes up a lot of space, the software suddenly freezes and exits. 

### ISSUE THREAD

**Issue by CRH380AM0204** [files-community/Files#3844]
Every time I open a folder with a lot of content, or a folder that takes up a lot of space, the software suddenly freezes and exits. This is my crash log.
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6091715/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6091716/debug.txt)

**Comment by gave92** [comment]
Thanks for this report. When this happens do you get a crash notification in the action center?

**Comment by CRH380AM0204** [comment]
Occasionally you will receive a notification, but for the most part you will not.

**Comment by yaichenbaum** [comment]
Thank you for your feedback, we recommend updating to the latest version of Files to get the best experience.
