### ISSUE TITLE
file extensions not shown in search results

### ISSUE THREAD

**Issue by drbryce** [files-community/Files#3847]
**Describe the bug**
When using the search function, file extensions are not visible in the results.

**To Reproduce**
1. Ensure "show extensions for known file types" is enabled
2. Click on the search button
3. Type in a search query
4. No file extensions are shown in the results list.

**Expected behavior**
I expected to see the file extensions of the files listed in the results. They are visible when browsing directories normally.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Pro 20H2 19042.804
 - App version: v1.3.0.0

**Log file**
[debug.txt](https://github.com/files-community/Files/files/6092286/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6092287/debug_fulltrust.txt)

**Comment by winston-de** [comment]
This bug should be fixed in #3639.

taken from v1.3.5.0 (insider):
![image](https://user-images.githubusercontent.com/59544401/110161206-e7608080-7da1-11eb-9582-709730b04099.png)

**Comment by drbryce** [comment]
Awesome! I'm really excited to see this program continue to grow.
