### ISSUE TITLE
Navigate folder structure shortcuts

### ISSUE THREAD

**Issue by mlagardenhose** [files-community/Files#3848]
In windows explorer, using the shortcuts ALT + UP (or DOWN) navigates the folder structure to one hierarchy up or down.
Also, ALT + LEFT (or RIGHT) key combination shortcuts takes you one step forward (or backward) in the navigation history.

Would be a great help if these shortcuts work in "Files" as well.
Thanks.

**Comment by gave92** [comment]
Hello these shortcuts are already implemented but sometimes they do not work. Closing and reopening the app a couple of times usually fixes this. Closing this as the shortcut not working issue is already tracked.
