### ISSUE TITLE
Make drop shadow between the sidebar and the main content area more prominent

### ISSUE THREAD

**Issue by asuetin** [files-community/Files#3850]
**Is your feature request related to a problem? Please describe.**
In light theme, the sidebar often blends with the main content area because their colors end up being nearly the same.

![image](https://user-images.githubusercontent.com/37500046/110173468-adc65e80-7e0f-11eb-97d7-8eeda57466ef.png)

**Describe the solution you'd like**
Add a prominent drop shadow between the sidebar and the main content area.

![image](https://user-images.githubusercontent.com/37500046/110173786-2fb68780-7e10-11eb-91e6-2d9a9f627651.png)

**Comment by yaichenbaum** [comment]
@asuetin This issue should be resolved with #3863.
