### ISSUE TITLE
Enhancement: Remove background color on the status bar

### ISSUE THREAD

**Issue by asuetin** [files-community/Files#3851]
I think the app would look cleaner if the bottom bar didn't have a separate background color. This also has the added bonus of being consistent with File Explorer.

Before:

![image](https://user-images.githubusercontent.com/37500046/110174735-9daf7e80-7e11-11eb-8be2-db51e935b6e1.png)

After:

![image](https://user-images.githubusercontent.com/37500046/110174756-a6a05000-7e11-11eb-9c89-af9fa69e07e7.png)

**Comment by generalguy41** [comment]
I like it. Looks much cleaner imo

**Comment by pklion** [comment]
I think so too.

**Comment by yaichenbaum** [comment]
@generalguy41 Can you clarify if you prefer it with or without the background?

**Comment by generalguy41** [comment]
@yair100 without. All one colour looks cleaner.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #3871.
