### ISSUE TITLE
[Feature request] Change launch handling to allow opening in new tabs instead of new instances for different launch types

### ISSUE THREAD

**Issue by winston-de** [files-community/Files#3852]
**Is your feature request related to a problem? Please describe.**

Currently, when Files is launched using command line arguments, it opens in a new instance instead of a new tab. When Files is set as the default explorer, folders opened through Search, PowerToys run, and VSCode all open in new windows instead of tabs.

Also, when Files is launched with no arguments from the start menu, it opens a new instance. This is annoying as opening a new instance is slower, and pressing other apps on the start menu such as edge open the current instance, not a new one.

**Describe the solution you'd like**
- Adjust the launch event handing in Program.cs to open in a new tab when launched with CommandLineArgs. 

- Remove requirement for arguments to open in a new tab instead of instance so that launching from start opens the current instance

- ~~I also think the "when launching from the jump list -> open new tab / new instance" option should be changed to a universal setting for opening new windows or tabs when launched.~~ It appears this is already the case, it's just that it's labeled oddly. I think the label should be changed to say "When opening a folder in Files".

**Describe alternatives you've considered**

**Additional context**
I have already done the work for it and will open a PR soon. :)

**Comment by gave92** [comment]
In the future for command line launch there could be a command line argument to overwrite this behaviour:
`Files c:\users` -> honours the startup setting
`Files c:\users -newwindow` -> opens new window
`Files c:\users -newtab` -> opens new tab (or new instance if not running)

**Comment by gave92** [comment]
I'm not sure if opening from the start menu should open a new tab.. why would you click on the start menu tile instead of opening a new tab from the app? Should the setting when launching with a path be distinct from the setting when no argument is specified?
\+ @yair100?

**Comment by winston-de** [comment]
> I'm not sure if opening from the start menu should open a new tab.. why would you click on the start menu tile instead of opening a new tab from the app? Should the setting when launching with a path be distinct from the setting when no argument is specified?
> + @yair100?

My reasoning is that it's easier to use the start menu to access the current Files instance than hunt through currently open windows in the task viewer or task bar (depending on whether you're using tablet mode and how many windows you have open).
I can change the behavior to not open a new tab if there is already one open and the args are null.
