### ISSUE TITLE
Files freezes when right-clicking files/folders

### ISSUE THREAD

**Issue by kimlimjustin** [files-community/Files#3855]
**Describe the bug**
Files freeze when right-clicking files/folders and sometimes it crashes. And if this happens, closing and reopen Files will showing the Home tab instead of continuing where you left off.

**To Reproduce**
1. Open Files
2. Right click on a folder/files
3. Files freeze/crashes (it's more frequent to freeze rather than crashes)

**Expected behavior**
Files doesn't freeze or crash

**Screenshots**
https://user-images.githubusercontent.com/61906684/110193845-05dd7f00-7e69-11eb-9fff-0a1271564aad.mp4

**Desktop (please complete the following information):**
 - OS Version: Microsoft Windows 10 Home Single Language 10.0.18363 N/A Build 18363
 - App version: 1.3.0.0

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app? Yes

**Log file**
[debug.txt](https://github.com/files-community/Files/files/6094620/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6094621/debug_fulltrust.txt)

**Comment by gave92** [comment]
Is there any difference if you wait 1 sseconds before right clicking?

**Comment by kimlimjustin** [comment]
> Is there any difference if you wait 10 seconds before right clicking? (until a few more items appear on the sidebar)

No, no difference at all.


https://user-images.githubusercontent.com/61906684/110195919-77222f80-7e73-11eb-8243-546aec18e2f6.mp4

**Comment by Abdennournemr213** [comment]
same, first time using the app

**Comment by gave92** [comment]
@kimlimjustin could you try the following?
- create an empty folder
- set Files to open this folder on startup
- check if right-click is working

**Comment by kimlimjustin** [comment]
> check if right-click is working (in the folder empty space)

No, it's not working and resulting Files freeze.

> do shortcut files (.lnk) appear for you in Files?

Sometimes I need to wait a long time to let it appears in Files, but right-clicking also not working too after it appears. But sometimes although I waited for a long time, it still doesn't appear, IDK why tho.

> have you had this issue with previous versions of Files?

I remember version 1.1.0 had no this bug, but I'm not really sure (I know it's 1.1.0 because I opened a bug soon after trying Files and I check back that version). The thing I can sure of is the bug occurs recently.

**Comment by Abdennournemr213** [comment]
> @kimlimjustin could you try the following?
> 
> * create an empty folder
> * open Files
> * navigate to the folder using the navigationbar
> * check if right-click is working (in the folder empty space)
> 
> Also:
> 
> * do shortcut files (.lnk) appear for you in Files?
> * have you had this issue with previous versions of Files?

1.context does not work on empty folders either
2.i created a shortcut for a folder(quick access then changed it to wt.exe) and when entering the folder with "files" it gets stuck on loading as shown:
![capture](https://user-images.githubusercontent.com/53940415/110207200-2d8d1100-7e82-11eb-96c3-f5ca2028b18d.gif)

**Comment by j4t1nd3r** [comment]
I have this issue too.  Different folders have different right click menu appear times. The time to wait is also consistent for each folder.

**Comment by LJoonas** [comment]
> I have this issue too. Different folders have different right click menu appear times. The time to wait is also consistent for each folder.

Horribly slow right click menu times for me as well.

**Comment by kimlimjustin** [comment]
> > I have this issue too. Different folders have different right click menu appear times. The time to wait is also consistent for each folder.
> 
> Horribly slow right click menu times for me as well.

It's more frequent to be freeze in my case which is even worse xd.

**Comment by wsor4035** [comment]
I also have this issue

**Comment by Robin-vandenberg** [comment]
I also have the same issue. Left-clicking navigates properly, but as soon as I right-click it just gets stuck. First time user of the app btw.

**Comment by Robin-vandenberg** [comment]
Reporting back here after #4033 has been merged, and the right-click issue is fixed with me. Thanks for the quick fix!

**Comment by kimlimjustin** [comment]
It's fixed on mine since version 1.5.0.0 released, so I'm going to close this issue, thanks for the quick fix!

**Comment by sleepylucy** [comment]
I'm still getting the exact same issue, with version 1.5.2.0, windows 20H2

**Comment by yaichenbaum** [comment]
This issue should be resolved with #4625.
