### ISSUE TITLE
Change screenshots on the Microsoft store

### ISSUE THREAD

**Issue by pklion** [files-community/Files#3856]
**Is your feature request related to a problem? Please describe.**
The app design has been changed.

**Describe the solution you'd like**
Change screenshots on the Microsoft store.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by yaichenbaum** [comment]
@pklion The screenshots on the Microsoft Store properly reflect the current design in the store. We will update the screenshots when the new design is released.
