### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by ReyMagos** [files-community/Files#3859]
I've been recorded video from screen with OBS and then opened Files. Moved to the videos location and then error occured. It could have happened because I opened folder during video file saving.
[debug.txt](https://github.com/files-community/Files/files/6095405/debug.txt)

**Comment by yaichenbaum** [comment]
@ReyMagos Can you please add details like the version of Files and Windows?

**Comment by ReyMagos** [comment]
Files: 1.3.0.0
Windows: 10 Pro 19042.746

**Comment by yaichenbaum** [comment]
@ReyMagos Does this issue go away after restarting Files?

**Comment by ReyMagos** [comment]
Yes, it doesn't exists anymore.
