### ISSUE TITLE
Image preview

### ISSUE THREAD

**Issue by Mattiuz93** [files-community/Files#3866]
I can't see the preview of the images, only the icon. Is this a bug?

**Comment by yaichenbaum** [comment]
@Mattiuz93 What version of Files do you have?

**Comment by Mattiuz93** [comment]
The last of the Microsoft store. Anyway after a reboot now it's all ok 🤗

Inviato da Pixel 4a (5G) 📱

Il dom 7 mar 2021, 07:00 Yair Aichenbaum <notifications@github.com> ha
scritto:
