### ISSUE TITLE
Enhancement: Improving the library section on the sidebar

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#3869]
- [x] Remove desktop item from library section.
- [x] The app requires a restart after hiding or showing the library section.
- [x] Right clicking on a library item shows the option to unpin the item, the unpin option should only show when right clicking on a pinned item.
- [x] Pinned folders are not saved
- [x] You can add the same folder to the sidebar multiple times
- [x] If you delete the PinnedItems.json file, on the next startup libraries folders will be added to the first sidebar section (not to the library section) -> this is apparently by design? By default the documents folder will be shown in both sections.
- [x] Libraries are displayed in English instead of the system language
- [ ] Code in LibraryManager has unrelated method names (e.g. `EnumerateDrivesAsync`)

**Comment by yaichenbaum** [comment]
@gave92 It seems like right clicking on library items will still show the unpin from sidebar option.

**Comment by yaichenbaum** [comment]
@d2dyno1 Do you want to work on this?

**Comment by lukeblevins** [comment]
@yair100 This seems to be completely resolved now.

**Comment by yaichenbaum** [comment]
@duke7553 The last item in the list doesn't seem to have been implemented yet. Let's reopen this for now.
