### ISSUE TITLE
Update/change some icons (Proposal)

### ISSUE THREAD

**Issue by XPoppyX** [files-community/Files#3870]
### **Proposal:**
----------

### **Before:**
 
Preview/Details pane
![before3](https://user-images.githubusercontent.com/61259627/110246662-3dbaf400-7f47-11eb-801d-6acae50c37e6.png)

Context menu/ Open in Terminal...
![before4](https://user-images.githubusercontent.com/61259627/110246674-4f9c9700-7f47-11eb-9d66-4e307971ccbd.png)

Layout mode icons
![before](https://user-images.githubusercontent.com/61259627/110246715-78249100-7f47-11eb-8a91-a869489e901f.png)

Layout mode icons alignment
![before-alig](https://user-images.githubusercontent.com/61259627/110247105-3a286c80-7f49-11eb-8cf6-76ed13a69cfb.png)

Invert selection
![before2](https://user-images.githubusercontent.com/61259627/110247880-2e3ea980-7f4d-11eb-9c48-fabfa63cafd4.png)

Context menu/Open with
![Captura de pantalla 2021-03-07 143958](https://user-images.githubusercontent.com/61259627/110249078-005c6380-7f53-11eb-8042-0e894f51273c.png)

---------------

### **After:**

Preview/Details pane
![after](https://user-images.githubusercontent.com/61259627/110247136-722faf80-7f49-11eb-9f02-302709694fde.png)

Context menu/ Open in Terminal...
![after3](https://user-images.githubusercontent.com/61259627/110247142-7b208100-7f49-11eb-8624-c44b1f101298.png)

Layout mode icons
![after2](https://user-images.githubusercontent.com/61259627/110247143-81166200-7f49-11eb-94c4-dc6ae7b2103e.png)

Layout mode icons alignment
![after-align](https://user-images.githubusercontent.com/61259627/110247332-845e1d80-7f4a-11eb-9885-c017b90632c0.png)

Invert selection
![after4](https://user-images.githubusercontent.com/61259627/110247886-34cd2100-7f4d-11eb-8a47-0a3e67a33012.png)

Context menu/Open with
![Captura de pantalla 2021-03-07 143450](https://user-images.githubusercontent.com/61259627/110249069-f33f7480-7f52-11eb-9739-707e111c4aa7.png)

---------
All icons are from **"Segoe fluent icons"**

**Comment by yaichenbaum** [comment]
@XPoppyX Looks good! Can you open a PR?
