### ISSUE TITLE
Widgets backgrounds are not updating after changing the theme

### ISSUE THREAD

**Issue by XPoppyX** [files-community/Files#3874]
When changing the theme from light to dark, widget backgrounds do not update

![background](https://user-images.githubusercontent.com/61259627/110257588-475f4e80-7f7d-11eb-8976-ad6801a463ab.gif)

**Comment by yaichenbaum** [comment]
@duke7553 Did you use theme resource for the widgets?

**Comment by d2dyno1** [comment]
It looks like it's no longer an issue!

**Comment by yaichenbaum** [comment]
@d2dyno1 Have you tested this in all the widgets?

**Comment by d2dyno1** [comment]
All widgets behave fine

**Comment by yaichenbaum** [comment]
@d2dyno1 It looks like it's still an issue on `main`.

**Comment by d2dyno1** [comment]
https://user-images.githubusercontent.com/53011783/111213274-e2d16e80-85d0-11eb-8d58-438a4d9af354.mp4

@yaichenbaum

**Comment by yaichenbaum** [comment]
@d2dyno1 It could an it's only an issue when the Windows theme is different from the app theme.

**Comment by d2dyno1** [comment]
> @d2dyno1 It could be it's only an issue when the Windows theme is different from the app theme.

But I had this issue in the past

**Comment by XPoppyX** [comment]
Now this issue happen differently.
When the app is in light mode, first go to another directory from the sidebar and go back to "Home", now when changing to dark mode the background is not updated

**Comment by yaichenbaum** [comment]
@XPoppyX This issue should be resolved with #4092.
