### ISSUE TITLE
Files does not open relative paths when launched from command line

### ISSUE THREAD

**Issue by winston-de** [files-community/Files#3876]
This is a small change, and I'll be opening a PR to fix this issue in a minute, so I don't think it's necessary to fill out the fill issue template. 

## To reproduce
```1.  Open terminal```
2. Enter command ```files appdata``` or other relative directory
3. Files opens to new tab page instead

**Comment by gave92** [comment]
Merging with #1751

**Comment by winston-de** [comment]
woops my bad sorry
