### ISSUE TITLE
files had a problem

### ISSUE THREAD

**Issue by realsaaw** [files-community/Files#3878]
I tried to make a file research in a big folder (near 60/70GB) when, after some second of the searching line was sliding on the screen, the app has [crashed.]
Follow the debug log file...
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6098148/debug_fulltrust.txt)

Thank you for the beautiful app!
**Desktop:**
 - OS Version: [Windows 10 Pro 20H2 19042.804]
 - App version: [v1.3.0.0]

**Comment by gave92** [comment]
Thanks for this report. Could you post the other debug file as well? (debug.txt)

**Comment by gave92** [comment]
Merging with #3844
