### ISSUE TITLE
Library widget: Add right click menu option to pin to sidebar

### ISSUE THREAD

**Issue by Rick-HM** [files-community/Files#3880]
**Problem:**
Currently you must go to the users folder to pin the libraries from there and it's annoying.

**Solution:**
Add the option to pin to the sidebar.

**Additional request:**
Maybe add all possible options like: **Open, open in new tab / window / pane, Copy, Open in terminal... , Pin to sidebar and properties.**

**Comment by yaichenbaum** [comment]
Closing this issue since the library widget has been removed.
