### ISSUE TITLE
Feature request: Vertical tabs

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#3882]
**Placement**: Left of the sidebar
**Display options**: Expanded, collapsed, expanded on hover

**Comment by voiiden** [comment]
Microsoft Edge has a great implementation of this. 

https://user-images.githubusercontent.com/31285047/115144483-3827f200-a04d-11eb-9f35-85ed2f3705c4.mp4

**Comment by hiranmayd** [comment]
This is great but where will the main sidebar go?

**Comment by voiiden** [comment]
next to the vertical tabs I would assume

**Comment by hiranmayd** [comment]
yes, but personally i don't think that'd be user-friendly, having two side-bars stacked side by side isn't an optimal solution.

**Comment by yaichenbaum** [comment]
> yes, but personally i don't think that'd be user-friendly, having two side-bars stacked side by side isn't an optimal solution.

This is the main issue preventing us from implementing this feature.

**Comment by hiranmayd** [comment]
I see. It might be a good idea to just keep the idea of vertical tabs aside

**Comment by RokeJulianLockhart** [comment]
> https://github.com/files-community/Files/issues/3882#event-4829523268

@yaira2, this is marked as implemented, but how does one enable it?

**Comment by Josh65-2201** [comment]
This isn't marked as implemented and isn't available since it conflicts with the existing sidebar

**Comment by yaira2** [comment]
@RokeJulianLockhart I think this issue was closed before GitHub had a way to mark issues as not planned.

**Comment by yaira2** [comment]
Vertical tabs aren't planned but we do have other tab management features that are being looked into.
