### ISSUE TITLE
Redesign Overflow Menu for Action Bar

### ISSUE THREAD

**Issue by tgrelka** [files-community/Files#3883]
**Describe the solution you'd like**
Seeing how the action bar below the address bar has a lot of free space, I think a redesign of the buttons and the overflow menu leads to usability improvements.

I tend to use New and New Pane quite often, not always reaching for the shortcuts though, especially since both are three-stroke-shortcuts. I’d suggest placing these buttons next to the Search and Toggle Preview Pane buttons.
I’d also like to see the open in Terminal button there, I haven’t found a shortcut for that one yet.

I believe this can be improved even further: The New Tab and New Window buttons can stay in that overflow menu, for all I care. But given how the New Tab button is already placed at a different spot, one where it makes sense from a usability point of view - in the tab bar, maybe consider adding the/a Copy Location button to the addres bar, to the side of it or only show it when the bar is selected, like the clear button. Something like this is common practice in many web apps, even GitHub itself has this, if you click the green ↓Code button in any repository, any of the links will have a Copy To Clipboard action right next to them.

Overall, the overflow menu seems a bit all over the place right now, especially since the dual-bar design (address bar and action bar) leaves a ton of free room for two more buttons without adding much clutter.

I might suggest a smart overflow menu which places more and more of the options in the action bar as the window grows bigger / hides them as the window shrinks. That way, clutter will be low when the window is small, but usability will be improved as the window gets bigger.

The Toggle Preview Pane may make more sense down in the Display Options menu at the bottom of the window, and personally I’d have the search button at the very right, with the expanding search bar pushing the other items to the side or overlaying them.

**Comment by SOI7** [comment]
Perhaps follow the Windows 10X route, where there are some quick action buttons (with the Accent color) that change according to the folder or the item selected?

![image](https://user-images.githubusercontent.com/50930970/110320639-eaad7380-8010-11eb-8f5a-757e28132d65.png)


![image](https://user-images.githubusercontent.com/50930970/110320596-d8333a00-8010-11eb-91f7-981a7aaa4d98.png)

For example, when you select a file or a folder, a set of actions like Copy, Cut etc. appear below the navbar

**Comment by tgrelka** [comment]
> For example, when you select a file or a folder, a set of actions like Copy, Cut etc. appear below the navbar

I believe these kinds of actions for a specific item are placed well in their respective context menus. What you showed is more friendly to touch users, but leads to A LOT of clutter on desktop and the tough decision what to leave in a context menu and what to put in the action bar.

For me, it’s all about the actions for the working folder aka the one whose path is in the action bar, listed in the overflow menu to the right, since most of the time that’s what you want to use without selecting a specific file.

**Comment by yaichenbaum** [comment]
Merging with #3265.
