### ISSUE TITLE
Can't open specific folder

### ISSUE THREAD

**Issue by TAICHIHUNG-JPG** [files-community/Files#3884]
**Describe the bug**

**To Reproduce**
1. Go to '....'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2 19042.804]
 - App version: [e.g. v1.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`, you should see a file in this directory called debug.txt or/and debug_fulltrust.txt.

**Comment by gave92** [comment]
Please add more details and post the app's version and log files

**Comment by TAICHIHUNG-JPG** [comment]
When I open a folder, the whole app crashed. I close the app and open the folder again and it crashed again. Back and forth several times.

Best Regards
Zhihong Dai

**Comment by duke7553** [comment]
@TAICHIHUNG-JPG We cannot fix this without the uploaded log files.

**Comment by TAICHIHUNG-JPG** [comment]
I uploaded the log file the first time I sent the email. You didn’t received the log file?

Best Regards
Zhihong Dai

**Comment by yaichenbaum** [comment]
@TAICHIHUNG-JPG It looks like the upload didn't work, can you try adding the logs and version info to the issue description?

**Comment by TAICHIHUNG-JPG** [comment]
Couldn‘t find the log file, I will sent it to you again when I have this issue again. Thanks though!

Best Regards
Zhihong Dai

**Comment by yaichenbaum** [comment]
@TAICHIHUNG-JPG Thanks for the update! Please reopen this issue if it happens again.
