### ISSUE TITLE
Favorites and Libraries section headers are selectable

### ISSUE THREAD

**Issue by nvi9** [files-community/Files#3885]
**Describe the bug**
The Favorites and Libraries sidebar menu section headers are selectable like any real sidebar entry (Home, Recycle bin, C: drive, etc.).

**To Reproduce**
1. Click on either Favorites or Libraries on the sidebar
2. See colored selection appearing on them

**Expected behavior**
Act like other section headers do, allow selection on subitems only.

**Video**

https://user-images.githubusercontent.com/42123156/110328962-492c1f00-801c-11eb-9609-fc1e6def57ec.mp4

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.804
 - App version: built from main (probably since #3761)

> PS. might be merged with #3869

**Comment by yaichenbaum** [comment]
@nvi9 This issue should be resolved with #3881.
