### ISSUE TITLE
Update Turkish localization

### ISSUE THREAD

**Issue by jaw3l** [files-community/Files#3887]
**Describe the bug**
When I changed the application language to Turkish but app became a mix of Arabic and Turkish.

**To Reproduce**
1. Go to 'Settings > Preferences'
2. Click on 'Application Language'
3. Change language to 'Turkish'
4. See Arabic letters everywhere instead of Turkish.

**Expected behavior**
I expected Turkish letters, but only few of the words are Turkish. As shown in the screenshot the left panel is fully Turkish but the actual context panel in the middle is mixed with Arabic, English and Turkish.

**Screenshots**
![ApplicationFrameHost_2021-03-08_19-28-38](https://user-images.githubusercontent.com/16852455/110351996-6f66b480-8046-11eb-83a9-55e915ee76ef.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.804
 - Windows Feature Experience Pack 120.2212.551.0
 - App version: v1.3.0.0

**Additional context**
This problem occurs again after restarting the app. I tried changing application language back to English than Turkish again but the result was the same.  And lastly I checked `Files/MultilingualResources/Files.tr-TR.xlf` and it looks alright.  It shouldn't be the problem.

**Log file**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6102849/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6102850/debug.txt)

**Comment by yaichenbaum** [comment]
@jaw3l This can happen when a localization is out of date, do you want to update the Turkish translation of Files?

**Comment by jaw3l** [comment]
Yes, I can do that.

**Comment by jaw3l** [comment]
Do I have to translate the entire xlf file? I can't see the existing translations.
