### ISSUE TITLE
 Proposal for icon changes (2)

### ISSUE THREAD

**Issue by XPoppyX** [files-community/Files#3889]
Other changes that I propose:

### The icons are from "Segoe fluent icons"
-----

### **Before:**

More options...
![before](https://user-images.githubusercontent.com/61259627/110365076-57ca0480-8023-11eb-8bfd-551b0bd8a898.png)

Context menu:
![before2](https://user-images.githubusercontent.com/61259627/110365082-58fb3180-8023-11eb-896c-500e75310f0b.png)
![before3](https://user-images.githubusercontent.com/61259627/110365083-58fb3180-8023-11eb-855e-62a17cbace06.png)

----------

### **After:** 
**_More consistency and cleaner_**

More options...
![after](https://user-images.githubusercontent.com/61259627/110365169-76300000-8023-11eb-8c36-acd6995eb954.png)

Context menu:
![Captura de pantalla 2021-03-08 123253](https://user-images.githubusercontent.com/61259627/110365173-77612d00-8023-11eb-8800-22d309c9548a.png)
![after2](https://user-images.githubusercontent.com/61259627/110365172-77612d00-8023-11eb-9bfe-307ee8f2e0c1.png)

-----------

**Comment by yaichenbaum** [comment]
@XPoppyX This looks great! Can you open a PR?
