### ISSUE TITLE
Reduce spacing between text in the tab control

### ISSUE THREAD

**Issue by edge261** [files-community/Files#3891]
**Describe the bug**
The title of the tabs have a weird spacing, looks like it have a double spacing instead of only one space.

**Expected behavior**
To have a single space between words.

**Screenshots**
![image](https://user-images.githubusercontent.com/79731301/110370188-ff8a0700-8010-11eb-8a08-8fa53910e4d9.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Dev, latest build.
 - App version: v 1.3.5.0

**Comment by yaichenbaum** [comment]
@edge261 This issue should be resolved in `main`.
