### ISSUE TITLE
Crash on Start up

### ISSUE THREAD

**Issue by TRANATAM** [files-community/Files#3898]
Hello, 

The app closes instantly after launch on Windows 10 Pro 20H2 (x86 Intel) Files v1.3

I tried to reset and repair the app with the windows options
I tried with Github and Windows store file's 
I tried by disabling the antivirus (Kasperky)
I tried restart my computer
Nothing changes   

I installed anothers apps from the Windows Store to test, no problem, works

I read in the comments of the windows store that we were several to have the same problem

Regards

**Comment by TRANATAM** [comment]
**I found 
To launch app do not forget to allow access to system files in confidentiality**

**Comment by vovapaukoff** [comment]
Have the same issue.
Can you explain exactly were and how you allow that permission?
