### ISSUE TITLE
Cloud drives status doesn't always show

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#3904]
**Describe the bug**
My personal google drive and work OneDrive doesn't not show it status when there clients are open. but my person OneDrive does. even when clients are closed the last know status should show.

**Expected behaviour**
Status bar should always show on all cloud drives.

**Screenshots**
![image](https://user-images.githubusercontent.com/26977075/110482888-0ed88580-80e1-11eb-9231-302f51df3fe6.png) ![image](https://user-images.githubusercontent.com/26977075/110482916-1566fd00-80e1-11eb-9757-0d8154f26fa0.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.844
 - App version: v1.3.0..0

**Log file**
[debug.txt](https://github.com/files-community/Files/files/6109051/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6109054/debug_fulltrust.txt)

**Comment by gave92** [comment]
In the Google drive folder, do files and folders show the sync status in the file icon?

**Comment by josh-65** [comment]
Some times one or two do but the icons change from the normal folder to shared folder or the synced folder every refresh.

**Comment by gave92** [comment]
Could you post a screenshot/video of this?

**Comment by josh-65** [comment]
The missing icon in this ones is the sheared folder
![image](https://user-images.githubusercontent.com/26977075/110519554-612b9d80-8105-11eb-9d7d-cdc140c13ba8.png)
![image](https://user-images.githubusercontent.com/26977075/110519580-67217e80-8105-11eb-9250-cbee2754d3eb.png)
![image](https://user-images.githubusercontent.com/26977075/110519603-6ee12300-8105-11eb-94b3-9c7bb2660045.png)

**Comment by josh-65** [comment]
The issues of google drive icons not changing has been fixed in 1.4.1, However my school OneDrive account still doesn't have the sync tab details like it should. I also think that google drive should also have the sync tab stuff.
![image](https://user-images.githubusercontent.com/26977075/111178754-5d839500-85a3-11eb-9720-3e48ed4b0c37.png)

**Comment by josh-65** [comment]
Fixed in 1.5.67
