### ISSUE TITLE
Place cursor in dialog box when creating folder

### ISSUE THREAD

**Issue by Talderon** [files-community/Files#3908]
**Is your feature request related to a problem? Please describe.**
Feature Request: When I was copying files, I selected the destination folder and created a new folder. When the dialog box appeared to enter the name, I started typing. Nothing. I had to click the text entry box to start typing. 

**Describe the solution you'd like**
Would be nice if the Dialog Box had focus and the cursor was in there without having to take further action.

**Describe alternatives you've considered**
Not sure what could be an alternative.

**Additional context**
Nothing further to add.

**Comment by d2dyno1** [comment]
@Talderon It's been already fixed in #3637, please wait for the next release with the changes \:)
