### ISSUE TITLE
Enhancement: Hide the cloud drives section on the sidebar if no drives are detected

### ISSUE THREAD

**Issue by XPoppyX** [files-community/Files#3912]
The Cloud drives section is always visible and I don't have any cloud drives.

![Captura de pantalla 2021-03-09 190907](https://user-images.githubusercontent.com/61259627/110544878-2b89b300-810b-11eb-8ddb-eca73db35923.png)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5082.
