### ISSUE TITLE
Crash When Searching Dropbox

### ISSUE THREAD

**Issue by stanidesis** [files-community/Files#3918]
**Describe the bug**

Files instantly crashes when I enter my Dropbox cloud drive directory and begin to search for a file.

**To Reproduce**
1. Open a dropbox cloud drive folder
2. Begin searching for a document
3. Type anything that returns results
4. Crash?

**Expected behavior**

Should show the results

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: Windows [Version 10.0.19042.804]
 - App version: 1.3.0.0

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`, you should see a file in this directory called debug.txt or/and debug_fulltrust.txt.

[LocalState-Stanley-Idesis.zip](https://github.com/files-community/Files/files/6112439/LocalState-Stanley-Idesis.zip)

**Comment by rfv-370** [comment]
Yes I confirm sadly. Unstable with Dropbox.
Searching but also just copying between dropbox folder makes it crash.
I also got some freeze at some point.
Also it takes  several seconds before my cloud drives appears at start_up (dropbox, onedrive,...). I have to wait up to 10 secs or more - it is long... - while all is fine in File Explorer
My log is attached in case it is useful.
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6187992/debug_fulltrust.txt)

I like the idea of Files but still unstable sadly....

unrelated but I had issue also accessing Samba drive some delay in showing up the contents - while the standard file explorer was fine - so it was not a network issue.

**Comment by yaichenbaum** [comment]
@stanidesis is this still an issue in Files v2.0?
