### ISSUE TITLE
Enhancement: Move the loading indicator to the tab icon

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#3922]
- Replace the loading indicator with the progress ring in the tab.

**Comment by gave92** [comment]
Where will it be shown when the vertical multitasking is enabled?

**Comment by yaichenbaum** [comment]
@gave92 The same place, the vertical tab control is just a modified template of the regular tab control.

**Comment by d2dyno1** [comment]
@yair100 How would it look like with dual pane tabs? Would there be two progress rings?

**Comment by yaichenbaum** [comment]
@d2dyno1 Just one...

**Comment by mdtauk** [comment]
Rather than moving or removing the Progress Bar as the view populates, how about adding a delay to when it displays, so faster drives or more empty folders, can have a chance of displaying before the progress bar displays.

**Comment by gave92** [comment]
In main it ready behaves a bit like that.

**Comment by R3voA3** [comment]
Love that change!
