### ISSUE TITLE
More columns in Details view please

### ISSUE THREAD

**Issue by marcerickson** [files-community/Files#3927]
This app has a lot of features that I use frequently when manipulating files on my Linux computer - Thank you!  The two features I need to use Files instead of [Windows] Explorer on my Windows 10 computer is the ability to add more file property columns to the details view and to set that view as the default.  

I have a lot of music and some of it is duplicated.  I want to cull duplicates, keeping the highest resolution files and discarding the lower resolution duplicates.  Windows has a lot of choices for properties columns to add (attached Choose details.jpg) that cover business, art, sound, and many more.  Having length and bit rate columns set in the view makes keeping the higher resolution file and deleting the lower resolution one much easier (attached details.jpg).
![Choose details](https://user-images.githubusercontent.com/29455237/110587996-38b59a80-8129-11eb-8a10-a178d1ff8f18.jpg)
![Details](https://user-images.githubusercontent.com/29455237/110588036-4b2fd400-8129-11eb-94ab-9d01d955221b.jpg)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by R3voA3** [comment]
If this gets implemented, is there a way to auto translate the properties? There are a lot and it is a pain to translate all of them. I hope MS has some sort of library for that 🙄

**Comment by yaichenbaum** [comment]
Merging with #8366

**Comment by yaichenbaum** [comment]
> If this gets implemented, is there a way to auto translate the properties? There are a lot and it is a pain to translate all of them. I hope MS has some sort of library for that 🙄

@R3voA3 I'm not sure about that but either way, I wouldn't want to rely on those as they aren't always accurate.
