### ISSUE TITLE
Feature: Add size on disk info to the properties dialog for better cloud management

### ISSUE THREAD

**Issue by rilflair** [files-community/Files#3930]
**Is your feature request related to a problem? Please describe.**
I have always used the files information on windows files explorer to check size on disk, so that I can manage my files either to delete or free up space (keep in OneDrive), and it would be nice to see the same feature on this project.

**Describe the solution you'd like**
Enable to compute and view size on disk, rather than just size when viewing files properties.

**Describe alternatives you've considered**
not sure

**Additional context**
This is an example from windows files explorer:
![image](https://user-images.githubusercontent.com/80393588/110617774-052e4b00-81d1-11eb-8b8c-10bad062676e.png)

and this is from current files app:
![image](https://user-images.githubusercontent.com/80393588/110617916-2c851800-81d1-11eb-9e8f-2ab17dfc2f15.png)

(note that this is the same file)

Thank you!

**Comment by octopushugger** [comment]
I use NTFS LZX compression on many files and need this feature to view their actual size.

**Comment by yaira2** [comment]
@rilflair @octopushugger this feature will be included in the upcoming v2.5.20 release.
