### ISSUE TITLE
Cant drag and drop multiple files into 7zip UI

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#3937]
**Describe the bug**
I can't drag and drop multiple selected files to be archived in 7zip.

**Expected behaviour**
I should be able to select files and folder and drag them into the 7 zip window to ad them into an archive.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.844
 - App version: v1.3.0.0

**Comment by josh-65** [comment]
ok so now it working not sure why

**Comment by gave92** [comment]
Let us know is it happens again :)
