### ISSUE TITLE
Side bar options are limited

### ISSUE THREAD

**Issue by jacobc94** [files-community/Files#3945]
When trying to update a pinned svn folder I cannot do it from the sidebar. Please add the same options to sidebar folders. 
![image](https://user-images.githubusercontent.com/57271649/110681766-076fb580-818f-11eb-8399-1f7fcf8bedc7.png)

**Comment by yaichenbaum** [comment]
@jacobc94 Are you looking to add an option to rename folders from the sidebar?

**Comment by gave92** [comment]
I think he's asking to show the full context menu for sidebar items

**Comment by yaichenbaum** [comment]
Merging with #1895.
