### ISSUE TITLE
Feature: Support a select switch for command line arguments

### ISSUE THREAD

**Issue by winston-de** [files-community/Files#3947]
**Is your feature request related to a problem? Please describe.**
Windows explorer supports the select switch, which selects the specified file or folder in the given path. This would allow Files to integrate better with features like "reveal in file explorer" in VSCode. This would also make it easier to quickly access files from the command line with Files.

**Describe the solution you'd like** 
```files "D:\test\testimage.png" -s```
```files "D:\test\testimage.png" --select```
```files /select,"D:\test\testimage.png"```

The last one is how explorer does it, so it should exist to provide support for this when Files is set as the default file explorer. 

**Describe alternatives you've considered**
Select file manually.

**Comment by hishitetsu** [comment]
This is already implemented.
`files.exe -select _PathOfFileToSelect_`
