### ISSUE TITLE
Side bar suggestions

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#3948]
1. Add an option to hide the collapsible header if only on sub-item is available
![image](https://user-images.githubusercontent.com/17484252/110707438-90bbd200-81f9-11eb-988c-4eea36657fa2.png)

2. OneDrive and other Cloud Folder should be expandable like in Explorer. Otherwise I could just pin OneDrive to the side bar and would have the same functionality.

3. Libraries do not show custom created Libraries

**Comment by yaichenbaum** [comment]
> Add an option to hide the collapsible header if only on sub-item is available
image

Can you open a new issue for this to start a discussion?

> OneDrive and other Cloud Folder should be expandable like in Explorer. Otherwise I could just pin OneDrive to the side bar and would have the same functionality.

This is beyond the scope of our current vision for the sidebar.

> Libraries do not show custom created Libraries

Thank you for bringing this up, right now the library section is limited to the default libraries, however, we plan to detect all libraries in the future, can you open a separate issue to track this feature?
