### ISSUE TITLE
Folder should be renamed to Libraries on the home page

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#3949]
![image](https://user-images.githubusercontent.com/17484252/110707700-f7d98680-81f9-11eb-8ad0-c518fa7b97d3.png)

We got the Settings:

1. Show Libraries on Side bar
2. Show Libraries on Home

Yet they are named differently.

![image](https://user-images.githubusercontent.com/17484252/110707786-1b9ccc80-81fa-11eb-8b16-89ef254907fe.png)

**Comment by yaichenbaum** [comment]
@R3voA3 The folders section will display more than just libraries, so I think it makes sense to keep the current title.
