### ISSUE TITLE
Hide recent files widget if there are no recent files

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#3950]
In my opinion there is no need to tell the user that there are no recent files available. Instead just hide the widget if there is no content to be shown.

![image](https://user-images.githubusercontent.com/17484252/110707962-556dd300-81fa-11eb-85b3-a18b7a2fbc04.png)

**Comment by yaichenbaum** [comment]
@R3voA3 Being that the user can turn on or off the widget, do you think the user will be confused if the widget doesn't show even after they turned it on?

**Comment by R3voA3** [comment]
Don't really think it would be confusing, but there is only one way to find out.

**Comment by yaichenbaum** [comment]
We don't have plans to implement this change.
