### ISSUE TITLE
App crashes when opening folders

### ISSUE THREAD

**Issue by mikl04** [files-community/Files#3951]
Describe the bug
The app crashes when opening any sort of folder, whether it be downloads, program files, etc.

To Reproduce
Click on any folder as if you were going to open it. The app freezes then automatically closes.
After a few tries, the folder will open, but not before crashing at least twice.

Expected behavior
I expected the folder to just open normally.

Screenshots
https://user-images.githubusercontent.com/80429764/110708313-575e7480-81af-11eb-9488-e96f0cc464d8.mp4

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Home, version 10.0.19042 build 19042
 - App version: 1.3.0.0

Additional context
This issue occurs almost every time I try to go into a folder.

I've tried a reinstall, that didn't work.

Log files
[debug.txt](https://github.com/files-community/Files/files/6119232/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6119233/debug_fulltrust.txt)

**Comment by gave92** [comment]
Thanks for this report:
- Are you still experiencing this issue?
- If so, could you try if it works is you disable these two settings (turn off caching) under Experimental?

![image](https://user-images.githubusercontent.com/9673091/110851026-ce2f6680-82b0-11eb-8974-599e144ff399.png)

**Comment by yaichenbaum** [comment]
This issue should be resolved in v1.5.
