### ISSUE TITLE
Feature request: Add drag & drop support for shortcut files

### ISSUE THREAD

**Issue by Igor-da-SilvaRodrigues** [files-community/Files#3952]
**Is your feature request related to a problem? Please describe.**
It is not yet possible to move a shortcut by Dragging and Dropping.

**Describe the solution you'd like**
Implement the ability to move a shortcut by Dragging and Dropping at the desired location.

**Describe alternatives you've considered**
There are no real alternatives to this feature, since it is already implemented in the default windows file explorer

**Additional context**
none

**Comment by gave92** [comment]
To my knowledge this is currently impossible with UWP :/ We'll keep looking for ways around this.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5810.
