### ISSUE TITLE
Feature Requests for left wing quick access bar

### ISSUE THREAD

**Issue by kilian102201** [files-community/Files#3953]
**Is your feature request related to a problem? Please describe.**
This is not related to a specific problem so far.

**Describe the solution you'd like**
I want to be able to rearrange pinned locations just as I can in windows file explorer.
I want to be able to close a head category down to a single row as I can in windows file explorer

https://user-images.githubusercontent.com/80431760/110714487-bf3eaa80-8203-11eb-987c-38cff55e95a7.mp4

**Describe alternatives you've considered**
I haven't considered any alternative solutions for this specific part

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?
I'm using the latest version of Files 1.3.0.0. 
I'm running on Windows 10 Pro version 20H2 Build 19042.844 (Windows Feature Experience Pack)
Processor	Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz  -  RAM-Memory 32,0 GB (31,9 GB Available)

**Comment by yaichenbaum** [comment]
@kilian102201 We are tracking the option to rearrange pinned items here #1069. The other enhancements you requested should be resolved in `main`.
