### ISSUE TITLE
Instant crash

### ISSUE THREAD

**Issue by nakedlunch02** [files-community/Files#3955]
Instantly crashes when I try to launch

**To Reproduce**
1. launch app
2. App launcher'

I expected the app to not instantly crash and open up so I can use it

unable to grab screen shot because message disappears almost instantly as well

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1909[18363.418]
 - App version: [1.3]

**Comment by yaichenbaum** [comment]
@nakedlunch02 Can you upload the log files?

**Comment by multicron** [comment]
I also have an instant crash.  I've attached my log files (they're quite brief!).  For what it's worth, C:, D:, M:, and X: are all accessible with File Explorer (although D: is an empty CDROM drive).

Windows 10 Pro 1809 [17763.973]
App Version 1.3

[debug.txt](https://github.com/files-community/Files/files/6123284/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6123285/debug_fulltrust.txt)

**Comment by yaichenbaum** [comment]
@multicron Does the app launch if you give Files access to the file system from the settings app?

**Comment by multicron** [comment]
Yes!  That worked!  Thank you!

**Comment by yaichenbaum** [comment]
@nakedlunch02 Can you see if that solution works for you as well?

**Comment by nakedlunch02** [comment]
I just switched to an earlier version for now and seems to be working fine. It's not a necessity, I just wanted to try it out.

Sent from Yahoo Mail on Android 
 
  On Thu, Mar 11, 2021 at 10:57 AM, Yair ***@***.***> wrote:   


@nakedlunch02 Can you see if that solution works for you as well?

**Comment by nakedlunch02** [comment]
If you want a log file for the version that was crashing, I tried but couldn't even get that far.Thats why I went with a previous version that did work.

Sent from Yahoo Mail on Android 
 
  On Thu, Mar 11, 2021 at 11:18 AM, Mark ***@***.***> wrote:   I just switched to an earlier version for now and seems to be working fine. It's not a necessity, I just wanted to try it out.

Sent from Yahoo Mail on Android 
 
  On Thu, Mar 11, 2021 at 10:57 AM, Yair ***@***.***> wrote:   


@nakedlunch02 Can you see if that solution works for you as well?
