### ISSUE TITLE
Double Clicking OR Open options in the context menu don't work for any file

### ISSUE THREAD

**Issue by anonymoususer1001** [files-community/Files#3957]
**The Open options for any file in the Context Menu don't do anything**
When I double click to or use the context menu to open a file, it does nothing

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'any file'
2. Double Click any file OR Click on 'Any Open Option in the Context Menu (Open, Run as Another User, Run as Administrator)'
3. See error: (nothing happens)

**Expected behaviour**
I expected the file to Open, Run as Another User or Run as Administrator, depending on what I chose from the Context Menu

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Pro Insider Preview Build 21332.rs_prerelease.210306-1859
 - App version: v1.3.0.0

**Additional context**
The Problem Persists After uninstalling and reinstalling the app
**Log file**
[debug.txt](https://github.com/files-community/Files/files/6120193/debug.txt)

**Comment by gave92** [comment]
Known issue with the newer insider builds. This is probably for microsoft to fix.
In order to confirm the issue, could you post a screenshot of the right click context menu of Files? Thanks!

**Comment by anonymoususer1001** [comment]
Edit: I'm using a Windows 10 Pro Preview, and it Doesn't work for any file.

![image](https://user-images.githubusercontent.com/69528792/110873754-738e0e80-82a0-11eb-8e23-a7edcfffc7fe.png)

**Comment by gave92** [comment]
Thanks for this report. I can confirm this is fixed on the development branch and a fix will be included with the next public release.
