### ISSUE TITLE
Cut & Paste overwrote the directory

### ISSUE THREAD

**Issue by banoctopus** [files-community/Files#3958]
When I was cutting a directory to paste it in a different location, instead of merging the two folders together, it overwrote my original files and I was left with the new files

**Comment by banoctopus** [comment]
I've also tested it with copy & paste with the same results.  If the two folders have the same name, "Generate new name" creates a separate folder, but "Replace existing item" will overwrite anything in the destination folder with the current items.  I hope that helps :)

**Comment by yaichenbaum** [comment]
@banoctopus The replace existing item option is not a merge option so this is the expected behavior. We are looking at adding a merge option though. Merging with #4601.
