### ISSUE TITLE
Tried Files for the first time this evening and immediately noticed that the left sidebar did not contain a "Quick Access" section like Win10's File Explorer. I use Quick Access a lot, and I suspect that many others to as well. Please consider adding that feature.

### ISSUE THREAD

**Issue by rayAtFlightTestDotUs** [files-community/Files#3960]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by R3voA3** [comment]
The latest version (might be insider only) feature a Favorites section which is exactly the same as Quick Access.

**Comment by josh-65** [comment]
you can right click on files or a folder and add them to the sidebar witch acts like quick access. just isn't labed in the current 1.3 version.
