### ISSUE TITLE
Hide the collapsible header if only on sub-item is available image

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#3961]
Add an option to hide the collapsible header if only on sub-item is available image. 

1. Advantage: Less clutter in the sidebar which has no use.

**Comment by yaichenbaum** [comment]
@R3voA3 Thank you for opening this issue, this enhancement has been approved for development.

**Comment by yaichenbaum** [comment]
This is no longer planned as we have added additional options when right clicking the headers.
