### ISSUE TITLE
Add proper support for libraries

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#3962]
Libraries are currently limited to the default Library folder created by Windows. However, main purpose of Libraries is it to create custom ones which serve as an access point to related data.

- [x] Show all user created libraries in the sidebar
- [x] Show all the grouped data in libraries instead of just the default folder

**Comment by nvi9** [comment]
For including multiple locations in library pages, we might need to implement the grouping feature (#1874) to show the entries from different directories separated.

Also, to keep the design consistent, we should create the mapping of all possible windows shell library icons to the fluentui glyphs for user created libraries or just simply show the same one for these...

**Comment by nvi9** [comment]
> @nvi9 We could probably group all the data together without #1874, but that would definitely be an improvement. Do you want to work on this?

@yair100 you're right, it can be implemented without grouping. I don't have multiple directories in my libraries, for some reason I could only imagine it that way.

So yes, I'll try working on this with no grouping first when I'm done with the sidebar.

**Comment by yaichenbaum** [comment]
@R3voA3 This issue is for the most part resolved with #4134.
