### ISSUE TITLE
Item Count property is not translated in the preview pane

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#3963]
![image](https://user-images.githubusercontent.com/17484252/110767569-ae6b5480-8256-11eb-8362-75056d9bea94.png)

**Comment by XPoppyX** [comment]
That string was added in #3773 but the multilingual resources was updated in #3938, one hour after your translations was merged xd

![Captura de pantalla 2021-03-11 091628](https://user-images.githubusercontent.com/61259627/110786100-7e1db900-824a-11eb-9fae-8e827a02fd8f.png)

**Comment by R3voA3** [comment]
:D
