### ISSUE TITLE
Ability to Pin Controls Above Main File List

### ISSUE THREAD

**Issue by Kelderic** [files-community/Files#3969]
**Is your feature request related to a problem? Please describe.**
I toggle between views frequently. Windows Explorer has a Views tab in the ribbon which is easy to get to, but in Files, I have to use the context menu, then open a nested Layout Options menu, before I finally get to where I need to go. It takes more clicks and more time to get to what I need.

**Describe the solution you'd like**
 I would love to have the ability to select which options I'd like to have persistently available. Example, the Search function is persistent, because the magnifying glass icon is always on the upper right of the window. Same with Info. Having the ability to customize which options are pinned in that spot is what I'd like to see.

![image](https://user-images.githubusercontent.com/1747252/110788661-e6fe3480-823c-11eb-9cec-81e83a658864.png)

**Describe alternatives you've considered**
Continue to use Windows Explorer.

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by XPoppyX** [comment]
> I toggle between views frequently. Windows Explorer has a Views tab in the ribbon which is easy to get to, but in Files, I have to use the context menu, then open a nested Layout Options menu, before I finally get to where I need to go. It takes more clicks and more time to get to what I need.

There is a view options button on the bottom bar

![Captura de pantalla 2021-03-11 113020](https://user-images.githubusercontent.com/61259627/110802710-318fa900-825d-11eb-8a27-45b7d429e567.png)

**Comment by yaichenbaum** [comment]
Merging with #2922.
