### ISSUE TITLE
i dont can run app Files.

### ISSUE THREAD

**Issue by PGStudioGH** [files-community/Files#3972]
I try run app Files. Suddenly the program is unexpectedly closed. I dont know why.

Windows 10 20h2

**Comment by gosndule** [comment]
Happened to me too right now (I'm a first time user tho). Version 1.2 works on my system so I installed that instead.

**Comment by gave92** [comment]
@PGStudioGH, @gosndule please post the app's log files so we can analyze the issue.

**Comment by PGStudioGH** [comment]
> Happened to me too right now (I'm a first time user tho). Version 1.2 works on my system so I installed that instead.
> Maybe see if you are running any apps that might be conflicting. I tried exiting an app called Dexpot that I use for multiple desktops & multiple desktop folders and now 1.3 works.

Thank you!

**Comment by xx-t** [comment]
> I try run app Files. Suddenly the program is unexpectedly closed. I dont know why.
> 
> 
> 
> Windows 10 20h2

I had this issue. For me, it seems turning on "File System" permissions in Settings>Privacy fixed it. Maybe you can try.
