### ISSUE TITLE
Double clicking specific folder with anything selected causes app to crash

### ISSUE THREAD

**Issue by kokidoki** [files-community/Files#3973]
**Describe the bug**
When opening a specific folder on my D: drive with double click, the application will crash if I have anything selected. Right clicking and using open works; as well as double clicking with nothing selected, but when doing so some file icons appear missing. Other folders in the directory work, and the one I am attempting to open only contains PDFs.

**To Reproduce**
_(As of right now I am unsure as to how to recreate an afflicted folder; but the log should reveal a more general issue)_
1. Open app
2. Navigate to pinned directory in D: drive
3. Select any folder
4. Double click the afflicted folder

**Expected behavior**
I expected the folder to open without crashing..

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Home 20H2 19042.804
 - App version: 1.3.0.0

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
[debug.txt](https://github.com/files-community/Files/files/6123391/debug.txt)

**Comment by gave92** [comment]
Thanks for this report. When the app crashes, are you getting a "something went wrong" notification?

**Comment by Fantazyjny** [comment]
Hello,
Same thing happens to me. Mostly it crash when I try to open game folder Kingdom Come Deliverance and Metro Exodus. Root folder of Kingdom come have like 81 folders and files and Metro have 132. There isn't "something went wrong" notification. 

[debug.txt](https://github.com/files-community/Files/files/6125771/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6125772/debug_fulltrust.txt)

**Comment by gave92** [comment]
Does the issue happen every time on the same folder or is it king of random?
Could you try if it works is you disable these two settings under Experimental? (warning: probably won't change a thing)
![image](https://user-images.githubusercontent.com/9673091/110851026-ce2f6680-82b0-11eb-8974-599e144ff399.png)

**Comment by Fantazyjny** [comment]
Default I had second option enabled and third disabled. After disable second option it doesn't crash. When I re-enabled it just crashes after few tries.

So that's it :)

**Comment by Fantazyjny** [comment]
That's how it looks like:

https://user-images.githubusercontent.com/8149819/110852836-25363b00-82b3-11eb-8a96-a51125745269.mp4

**Comment by gave92** [comment]
Thanks a lot @Fantazyjny! If confirmed that's very good to know. @kokidoki could you try the same?

@Fantazyjny if it happens again with those settings disabled, please let us know.

**Comment by kokidoki** [comment]
I was able to test and it works! The app can consistently open with the feature turned off and crash with it turned on. And upon removing a majority of the files it wouldn't crash; so I can confirm I think it's the number of files

**Comment by gave92** [comment]
Thanks for the confirmation. Keeping this open since this is something we want to fix.

**Comment by yaichenbaum** [comment]
@kokidoki is this still an issuei n v2.1.13?
