### ISSUE TITLE
Preview pane:  Crash when clicking on a folder shortcut

### ISSUE THREAD

**Issue by XPoppyX** [files-community/Files#3978]
**1-** Enable preview pane

**2-** Click on a folder shortcut

**3-** Crash

![crash](https://user-images.githubusercontent.com/61259627/110820056-80ddd580-826d-11eb-9698-b560f6a8859b.gif)

**Log:**
`2021-03-11 13:19:36.3294|ERROR|Files.App|Acceso denegado. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))|System.UnauthorizedAccessException: Acceso denegado. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
   at Files.ViewModels.Previews.FolderPreviewViewModel.LoadPreviewAndDetailsAsync()
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()
`

**Comment by winston-de** [comment]
My bad, I'll have a fix within the hour.
