### ISSUE TITLE
File operations on drives mounted via rclone (FUSE) behaving incorrectly.

### ISSUE THREAD

**Issue by mononen** [files-community/Files#3984]
**Describe the bug**
i.e., copying/moving files from local file system to rclone drive, the process will complete in the 'ongoing tasks' menu, however only one or two files will have transferred over, then after some waiting, the files will slowly start to appear in the new location and will be removed off the host.
When deleting files, the behavior is mostly normal, until you cancel the operation in 'ongoing tasks', where even after being cancelled, it will continue as if it weren't cancelled.

**To Reproduce**
1. Mount a drive using rclone/fuse.
2. Copy files over.
3. Witness odd behavior
Or
1. Mount a drive using rclone/fuse.
2. delete some files
3. cancel the deletion operaion
4. watch your files still get deleted.

**Expected behavior**
Files get copied with a representation in the ongoing tasks menu, and deletion operations actually get cancelled.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 2004, 19041.804
 - App version: v1.3.0.0

**Additional comments**
I can upload screencaptures of this behavior happening if necessary, but I think I've done a decent enough job of explaining it.

**Log file**
[debug.txt](https://github.com/files-community/Files/files/6126405/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6126407/debug_fulltrust.txt)

**Comment by gave92** [comment]
Thanks for this report. For the first point: the issue is that ongoing task menu is reporting completed while the operation is actually still in progress right?

**Comment by mononen** [comment]
> * For point 1: the issue is that ongoing task menu is reporting completed while the operation is actually still in progress right?

Yes exactly. The progress bar goes from 0 to 100% almost instantly (<5 s for a 50+gb copy), and none of the files show up, but as the window refreshes, the files will slowly appear.
Also during the initial copy, source files will flash/jump around in the destination folder, but never stick around.

**Comment by KAMiKAZOW** [comment]
Same for a USB flash drive (NTFS, in case that matters):

![image](https://user-images.githubusercontent.com/3259076/149569178-fd15c212-049b-4c19-8e45-6e52a8386bfe.png)


In reality only the first two files had been completed at that point.
