### ISSUE TITLE
Add ability to apply all

### ISSUE THREAD

**Issue by likkai** [files-community/Files#3985]
Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. 
Feature request: Common explorer function

Describe the solution you'd like
Please add a feature: 'Do this for all current items', as shown in the image

Additional context
I'm at the latest app version

![image](https://user-images.githubusercontent.com/76016664/110880606-dd96ca00-8319-11eb-8ca3-1fb07cf52093.png)

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
