### ISSUE TITLE
Add UI for changing icon and folder type in folder properties

### ISSUE THREAD

**Issue by aolko** [files-community/Files#3996]
**Is your feature request related to a problem? Please describe.**
Currently folder icons (via `desktop.ini`) are not supported, defaulting to a generic folder icon, please add support for them

**Describe the solution you'd like**
I'd like Files to read `desktop.ini` inside the folders and apply changes accordingly

**Describe alternatives you've considered**
An alternative would be doing it the way `explorer.exe` does

**Additional context**
![](https://i.imgur.com/URlVpTh.png)

**Comment by gave92** [comment]
Could you post an example desktop.ini containing a custom icon for a folder?

**Comment by aolko** [comment]
> Could you post an example desktop.ini containing a custom icon for a folder which doesn't work? Custom icons should be already supported. But the pointed icon must be _outside_ the C:\Windows folder.

```
[.ShellClassInfo]
IconResource=C:\WINDOWS\System32\SHELL32.dll,299
[ViewState]
Mode=
Vid=
FolderType=Generic
```
the one from **Dummy folder**

**Comment by gave92** [comment]
If you try with an icon outside the windows folder it will (should) work. Support for folder type has been added in the development branch.

**Comment by aolko** [comment]
> If you try with an icon outside the windows folder it will (should) work. Support for folder type has been added in the development branch (#3526)

Also there's to `settings` tab in folder `preferences`, to tweak `desktop.ini`-based settings, including folder icon, image and type

**Comment by CF-71** [comment]
@ gave92


> 
> 
> ... Custom icons should be already supported. ...

Really? Where can I find the setting? I couldn't find it in Files 1.3 yet.

**Comment by yaichenbaum** [comment]
Let's continue the conversation over here #1015.
