### ISSUE TITLE
Allow to change bundle size and view

### ISSUE THREAD

**Issue by aolko** [files-community/Files#3997]
**Is your feature request related to a problem? Please describe.**
Currently you are stuck with large bundles with list view. It would be great if you could change the view and budle size similar to start menu tiles (expact +1 more which sets the bundle height to items (files) height)

**Describe the solution you'd like**
see above

**Describe alternatives you've considered**
Currently there's no alternatives except not using bundles at all.

**Additional context**
![image](https://user-images.githubusercontent.com/581458/110925153-e5636800-8333-11eb-9195-80b22b224e12.png)

**Comment by sarjuathwal** [comment]
It would also be good to be able to resize Bundles larger. Currently there appears to be a limit of 8 items per bundle. It would good if the size of the Bundle could be manually reshaped, or to have different view options - grid, list, tile etc.

**Comment by CF-71** [comment]
I would also like to be able to adjust the size of the group-tiles. If they contain only a few (for example two or three) files/folders they take up a lot of space. So I think the idea of a size selection (for example like the tiles in the Windows start menu) is good.

**AND:** Could the activation/deactivation of the group-tiles be made more easily accessible? For example via the three-point-menu in the top right. 

![Screenshot](https://user-images.githubusercontent.com/79550364/111056883-35047980-8483-11eb-9107-ae8a9a75eafb.png)

**Comment by Josh-65** [comment]
Considering the tags feature is replaceing bundles so im going to close this.
