### ISSUE TITLE
Check boxes in directory listing

### ISSUE THREAD

**Issue by DavidotNet** [files-community/Files#4000]
This is a feature request.

I'm new to this app and I perused and did not find a setting similar to Windows File Explorer -enable check boxes. So, this feedback may not be relevant if that exists.

I would like to see check boxes displayed next to each (folder / file), can be selected [x] for keystroke.
When drag & drop (or delete) selected items, a prompt to move, copy, confirm delete should appear.

THANK YOU.

**Comment by gave92** [comment]
Thanks for this suggestion. Merging with #290.
