### ISSUE TITLE
Crash with multiple tabs open

### ISSUE THREAD

**Issue by gbroadbent67** [files-community/Files#4001]
**Describe the bug**
When I have 9 tabs open and I am refercing SharePoint sync'd folders the application crashes  (with 8 Tabs open the system is very slow) and upon re-launch it does not revert back to the tabs that were open. 

**To Reproduce**
1. Go to New Tab
2. Click on SharePoint folder that is locally sync'd
3. Go to New tab
4. Click on SharePoint folder that is locally sync'd
5. Repeat this until you have 8 tabs open.  
6. On the 9th tab that you open the application crashes

**Expected behavior**
No crash

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Pro Version	10.0.19042 Build 19042
 - App version: 1.3.0.0

**Additional context**
problem is repeatable
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6130413/debug_fulltrust.txt)

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`, you should see a file in this directory called debug.txt or/and debug_fulltrust.txt.

**Comment by yaichenbaum** [comment]
@gbroadbent67 is this still an issue in the preview version? https://files.community/download/preview
