### ISSUE TITLE
Weird Korean strings

### ISSUE THREAD

**Issue by Alfex4936** [files-community/Files#4002]
I checked out the korean translation files, but they look ok and I don't know these letters but seems to be latvian from the last commit message?

They are mixed up... (other korean strings are fine)

**Problems in**
Home: GB free of GB ({0} free of {1} saying like "Fr `unknown words` ee xGB `unknown words` yGB...)
Folders: Size info

![1](https://user-images.githubusercontent.com/2356749/110949405-e624ea00-8385-11eb-98c3-b412507da809.png)
![2](https://user-images.githubusercontent.com/2356749/110949409-e6bd8080-8385-11eb-9ba3-1ea7203b1049.png)

**Comment by XPoppyX** [comment]
should it look like this?

![Captura de pantalla 2021-03-12 122152](https://user-images.githubusercontent.com/61259627/110960514-99adc000-832d-11eb-8a55-4016e50113ba.png)

**Comment by Alfex4936** [comment]
@XPoppyX Yeah! exactly, thanks for trying to fix it
