### ISSUE TITLE
B

### ISSUE THREAD

**Issue by 1121b** [files-community/Files#4004]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by duke7553** [comment]
@1121b Thanks for your feedback. We're having trouble understanding what you're requesting and need additional information to investigate this item. Please open another issue when you've filled out the template to the best of your ability.
