### ISSUE TITLE
Cannot Drag Folders to Bundle - Instant Crash

### ISSUE THREAD

**Issue by mannycastaneda** [files-community/Files#4007]
**Describe the bug**
Cannot drag folder into a bundle. When I do, Files crashes

**To Reproduce**
1. In dual-pane view drag a folder (after opening in primary pane) to a bundle on the secondary pane
2. Files crashes

**Expected behavior**
The folder appears in the bundle

**Screenshots**
https://www.dropbox.com/s/t0qbksom7sguwv8/2021-03-12_11-05-09.mp4?dl=0

**Desktop (please complete the following information):**
 - OS Version: Windows  Version 10.0.17763 Build 17763

 - App version: [e.g. v1.0]
1.3.0.0

**Additional context**
The problem occurs every time
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6131481/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6131482/debug.txt)

**Log file**
attached

**Comment by yaichenbaum** [comment]
@mannycastaneda this issue should be resolved.
