### ISSUE TITLE
7-Zip built in intergration

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#4009]
**Describe the solution you'd like**
Don't know if it possible but there is a command line version of 7zip so i don't know if there could be a small version of 7 zip integrated with buttons to run the commands.

**Describe alternatives you've considered**
If it not possible with 7zip maybe WinRAR can be used.

**Additional context**
The buttons could be layed out like the 7 zip currently does and the settings menu could have a 7zip tab for settings on what to show or hide in the context menu.

**Comment by gave92** [comment]
Merging with #45
