### ISSUE TITLE
Dynamic bundles

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#4020]
**Describe the solution you'd like**
It would be good if we could set a bundle to monitor a folder to update and display its contents like it would now if we drag and drops folders in.

**Comment by d2dyno1** [comment]
This kind of defies the use of Bundles. They are meant to provide a quick access to select files/folders. This can be already achieved by navigating to directory and having this kind of functionality in Bundles is redundant. Even more, single bundle wouldn't be able to fit large directories in the first place!

**Comment by duke7553** [comment]
@d2dyno1 We could eventually figure out which items a user opens the most and prompt them to add the item(s) to a bundle

**Comment by d2dyno1** [comment]
> @d2dyno1 We could eventually figure out which items a user opens the most and prompt them to add the item(s) to a bundle

Good idea! However it's not related to the issue.
