### ISSUE TITLE
Right-Click causes application to not function.

### ISSUE THREAD

**Issue by Sirhc72** [files-community/Files#4021]
**Describe the bug**
When attempting to open a context menu using right click on any file or folder the application locks up.  I am unable to navigate the directory or get any button presses to work other than to close the application.

**To Reproduce**
1. Go to any file or folder.
2. Right-Click on any file or folder.
3. The application becomes not responsive

**Expected behavior**
When I right-click a file or folder I expect to see a context menu and I should be able to navigate the directory.

**Screenshots**
Not available

**Desktop (please complete the following information):**
 - OS Version:  Windows 10 10.0.18363
 - App version: 1.3.0.0

**Additional context**
I have observed when the application restarts itself It works as expected.  I am able to see the context-menu and navigate the directory without an issue.  However once I close the application and restart it the negative functionality returns.

**Log file**
[debug.txt](https://github.com/files-community/Files/files/6133412/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6133244/debug_fulltrust.txt)

**Comment by gave92** [comment]
Thanks for this report. Merging with #3855.
