### ISSUE TITLE
Progressbar of disks space isn't showing.

### ISSUE THREAD

**Issue by Fantazyjny** [files-community/Files#4022]
**Describe the bug**
Progressbar of disk space isn't showing for some of drives after opening application. In my case it always shows progressbar for C: drive, sometimes for D: drive and never for E: and F:. I have to enter into folder/drive and get back.

**To Reproduce**
1. Run Files

**Expected behavior**
Progressbar should be visible for all driver after running application.

**Screenshots**
![image](https://user-images.githubusercontent.com/8149819/111008071-97308200-8390-11eb-8b7a-071476142bc6.png)
![image](https://user-images.githubusercontent.com/8149819/111008075-9992dc00-8390-11eb-8b48-79db926f18a0.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.867
 - App version: 1.3.0.0

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?
Yes.

**Log file**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6133539/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6133540/debug.txt)

**Comment by gave92** [comment]
Thanks for this report. Merging with #3701.
