### ISSUE TITLE
Ctrl+Tab to Switch tabs

### ISSUE THREAD

**Issue by wmyers5701** [files-community/Files#4025]
Hi there,
Simple request, though I'm new to the app. My apologies if there is another way to do this already in place. I'd simply like to press Ctrl+Tab to switch tabs. Just like that function in Chrome for example.
Thanks!

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by gave92** [comment]
There's currently a bug preventing this, see #3840
