### ISSUE TITLE
Sometimes there is no context menu and the program becomes impossible to control

### ISSUE THREAD

**Issue by Timur78** [files-community/Files#4026]
Sometimes when you right-click on a file/folder, the object is highlighted, but there is no context menu and the program becomes impossible to control(there is no reaction to buttons and HOTKEYS)
------ normal, the context menu appears immediately

After restarting the application, the error may disappear

 - OS Version: Windows 10 pro 1909 18363.1379]
 - App version: 1.3.0.0

Video:
https://user-images.githubusercontent.com/80568319/111022821-519ea400-83e6-11eb-9676-cc5261489978.mp4

Logfile:
[debug.txt](https://github.com/files-community/Files/files/6134339/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6134340/debug_fulltrust.txt)

**Comment by gave92** [comment]
Thanks for this report. Merging with #3886.
