### ISSUE TITLE
Files shows temporary files created when opening Word or AutoCad even if they're hidden files

### ISSUE THREAD

**Issue by JanKrulak** [files-community/Files#4028]
Hello,

I think it would be great if after opening the actual file additional file(s) would not appear in the folder. For instance, when I open dwg file, additional two files open at the same time, see attached.

Kind regards,
[Screen Shot 2021-13-3 at 11-48-32.pdf](https://github.com/files-community/Files/files/6134721/Screen.Shot.2021-13-3.at.11-48-32.pdf)

Jan [Krulak[](url)](url)

**Comment by gave92** [comment]
Hello those are temporary created by the application (AutoCad?). Do they appear also when using Windows Explorer?

**Comment by JanKrulak** [comment]
Hi Marco,
Thank you for your response.
No, they do not appear when using Window Explorer. It is not just when AutoCad is open, it is the same for Microsoft Word.
Kind regards,
Jan    On Saturday, 13 March 2021, 12:40:05 GMT, Marco Gavelli ***@***.***> wrote:  
 
 


Hello those are temporary created by the application (AutoCad?). Do they appear also when using Windows Explorer?

**Comment by gave92** [comment]
@JanKrulak thanks for the info.
- Could you check if they appear in explorer if you set it to show hidden files and folders?
- Do they disappear in Files if you refresh the folder?

**Comment by JanKrulak** [comment]
Marco,
Yes, they appear when I tick 'hidden items'. Please see attached.
Jan
    On Saturday, 13 March 2021, 13:14:21 GMT, Marco Gavelli ***@***.***> wrote:  
 
 


@JanKrulak thanks for the info.
   
   - Could you check if they appear in explorer if you set it to show hidden files and folders?
   - Do they disappear in Files if you refresh the folder?

**Comment by yaichenbaum** [comment]
@JanKrulak This issue should be resolved with #4199.

**Comment by JanKrulak** [comment]
Morning Yeir,
Thank you for your email. 
It seems that the additional files still open for me, even if I updated Files to version 1.5.00.
Kind regards,
Jan


    On Thursday, 25 March 2021, 22:45:07 GMT, Yair Aichenbaum ***@***.***> wrote:  
 
 


@JanKrulak This issue should be resolved with #4199.

**Comment by yaichenbaum** [comment]
@JanKrulak As of now the issue has been fixed in `main`, it hasn't been shipped in a release yet.

**Comment by JanKrulak** [comment]
Yeir,
I see. Thanks for letting me know.
Kind regards,
Jan
    On Friday, 26 March 2021, 14:09:51 GMT, Yair Aichenbaum ***@***.***> wrote:  
 
 


@JanKrulak As of now the issue has been fixed in main, it hasn't been shipped in a release yet.
