### ISSUE TITLE
The status of the “Always keep on this device” is not displayed in the context menu

### ISSUE THREAD

**Issue by masontikhonov** [files-community/Files#4029]
**Describe the bug**
In the context menu of a file or directory, the “Always keep on this device” switch related to OneDrive does not display the status: whether it is enabled or not.

**To Reproduce**
1. Open “Files”
2. Right-click on any file or directory

**Expected behavior**
It is expected that opposite the switch its status will be displayed, in the form of a checkbox, as it is implemented in Windows Explorer, or in another way.

**Screenshots**
![Files_keep-on-this_1](https://user-images.githubusercontent.com/32432324/111029203-6857f180-840c-11eb-878d-9e8395b5ded3.png)
![Files_keep-on-this_2](https://user-images.githubusercontent.com/32432324/111029202-67bf5b00-840c-11eb-9054-e9f1d63dcf17.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 21H1 19043.867]
 - App version: v1.3.0.0

**Additional context**
— Does this problem occur again after restarting the app?
— Yes.

**Log file**
[debug.txt](https://github.com/files-community/Files/files/6134734/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6134735/debug_fulltrust.txt)

**Comment by gave92** [comment]
Thanks for this report. Merging with #3834 / #3708.
