### ISSUE TITLE
Add items to Bundles via context menu

### ISSUE THREAD

**Issue by d2dyno1** [files-community/Files#4031]
**Is your feature request related to a problem? Please describe.**
Sometimes it's impractical/unreliable to drag and drop items to Bundles. 

**Describe the solution you'd like**
Add a context menu option to add selected items to a bundle when the bundles widget is turned on.

**Additional context**
This has been originally suggested by @R3voA3 [here](https://github.com/files-community/Files/pull/3637#issuecomment-784565502) but I've opened this issue to keep track of it.

**Comment by R3voA3** [comment]
Thanks for opening this issue. I highly recommend to look into implementing that. Dragging is a nice gimmick but not really good from a usability point of view.

**Comment by Josh-65** [comment]
Should this be closed since tags are replacing bundles?
