### ISSUE TITLE
Freeze when opening Context menu

### ISSUE THREAD

**Issue by FenixAlfa159** [files-community/Files#4035]
**Describe the bug**
Most the time, when I right click a folder to open the context menu, it will freeze the app completely.

**To Reproduce**
1. Go to 'D drive,'
2. right click on any folder on any directory.
3. The app will freeze completely.

**Expected behavior**
I expect the program to not freeze, so I can access the context menu with no problems.

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Pro 1909 - 18363.1440
 - App version: 1.3.0.0

**Additional context**
Sometimes it works correctly, but pretty much 90% of the time it freezes when doing that.

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`, you should see a file in this directory called debug.txt or/and debug_fulltrust.txt.
[debug.txt](https://github.com/files-community/Files/files/6135610/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6135611/debug_fulltrust.txt)

**Comment by gave92** [comment]
Thanks for this report. Merging with #3855
