### ISSUE TITLE
Navigate to another folder very slow: 1-4 seconds

### ISSUE THREAD

**Issue by ellipticview** [files-community/Files#4037]
**Describe the bug**
Performed a fresh install of version 1.3

**To Reproduce**
1. Navigate to any folder (local disk). This can be down a level or up a level.
2. The blue progress indicator starts "swiping". Sometimes less than once. Often twice. Sometimes more than twice.
3. Then the folder is displayed
4. A little after, the progress indicator stops swiping

**Expected behavior**
Almost immediate display of folder, similar to Windows explorer. And the swipe indicator stops as soon as the folder is displayed. Because the progress indicator keeps moving even after the folder display, it seems even slower then it actually is.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Version 2004 19041.746
 - App version: v1.3.0.0

**Additional context**
Same behavior after restarting the app

[debug.txt](https://github.com/files-community/Files/files/6136224/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6136225/debug_fulltrust.txt)

**Comment by Daydream404** [comment]
Sometimes this also happens to me... or even not loading at all just stuck loading and nothing is displayed

**Comment by gave92** [comment]
￼

**Comment by ChildishGiant** [comment]
Generally the app is very slow to load, select items etc overall for me. I'm happy to do diagnostics if this is unusual but for now I'm using explorer again

**Comment by gave92** [comment]
Closing as folder loading speed was improved in main (#4922)
