### ISSUE TITLE
 Crush after cut & paste

### ISSUE THREAD

**Issue by aslongaspossible** [files-community/Files#4038]
**To Reproduce**
1. Cut multiple files (more than one)
2. Go to another directory and paste
3. Go back to the original directory
4. Crush

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 家庭中文版 19041.867]
 - App version: [v1.3.0.0]

**Comment by gave92** [comment]
Thanks for this report. Please post the app's log files so we can analyze the issue.
