### ISSUE TITLE
Double click to open file in "Recent Item" instead of one time click

### ISSUE THREAD

**Issue by kimlimjustin** [files-community/Files#4042]
I don't know this is a bug or a feature request, but, I think it's better to open a file in the "Recent Items"  section of "Home" by double click it instead of a one-time-click. To open a file in another folder, it requires a double click but IDK why a one-time click can open a file in the "Recent Items" section, which is very annoying when users tend to right-click it instead of opening it (by clicking it once to select, then right-click).

**Comment by gave92** [comment]
I agree it should respect the "Open items with one click" option

**Comment by yaichenbaum** [comment]
Merging with #2994.
