### ISSUE TITLE
Add a new issue template for crashes

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#4045]
- [ ] Should explain where log files are found (At the top of the text! In the current template it's at the bottom where it's easily missed)
- [ ] Should add an special label to the issue

**Comment by yaichenbaum** [comment]
@R3voA3 Thanks for the suggestions, we specifically leave out the labels because we found that users often used to the wrong template when creating issues. It saves more time when we add labels to the issues ourselves. Do you want to make the change with the instructions for the log files?

**Comment by R3voA3** [comment]
```
<!---⬆Select Preview for easier reading⬆
🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
I ACKNOWLEDGE THE FOLLOWING BEFORE PROCEEDING:
1. Issue might get deleted if it is not following the template
2. Only post one issue per bug report
3. Try to avoid duplicates. Do a quick search before posting
4. Add a descriptive title
--->

**Describe the bug**
A clear and concise description of what the bug is.

**To reproduce**
Steps to reproduce the behavior:
1. Go to '....'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Log file**
Please upload the log file here so that we can understand your issue better. 
* You can access it from Settings->About->Open log location. 
or 
* `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 
 
You should see a file in this directory called debug.txt or/and debug_fulltrust.txt.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**System Information**
 - OS Version: [e.g. Windows 10 20H2 19042.804] (Press WIN + PAUSE/BREAK, use the copy button at them bottom)
 - App version: [e.g. v1.0] (In the app, go to Settings -> About, the version is shown at the top)

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?
```

That's how I would change it.

1. It's a bit shorter now, less reading required
2. Added shortcut to get the system information quicker
3. Log entry was moved up to it's not missed (Scrolling was needed before)

**Raw text**
![image](https://user-images.githubusercontent.com/17484252/111072195-c1da2200-84d9-11eb-9379-2edaff6e41f6.png)
**Preview***
![image](https://user-images.githubusercontent.com/17484252/111072161-96efce00-84d9-11eb-8a73-554a1982f2d8.png)

**Comment by yaichenbaum** [comment]
@R3voA3 Thank you!
