### ISSUE TITLE
"Files ran into a problem the developers didn't prepare for yet" notification

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#4046]
**Describe the bug**
files crash with above error.

**Log file**
[debug.txt](https://github.com/files-community/Files/files/6137008/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6137009/debug_fulltrust.txt)

**System Information**
 - OS Version: Windows 10 20H2 19042.844
 - App version: v1.3.0.0

**Comment by gave92** [comment]
Hello thanks for this report. If you refer to the last crash (14/03 @ 15:52) I can confirm that the issue has been fixed in the development version.

**Comment by josh-65** [comment]
i deleted a file and went onto the home page before the crash
