### ISSUE TITLE
Implement color icons

### ISSUE THREAD

**Issue by marcpinet** [files-community/Files#4047]
**Is your feature request related to a problem? Please describe.**
I feel like the file explorer lacks in color for the Disks, Clouds or any other storage icons (Documents, Downloads, Pictures, etc...) The design is really cool, I love it. Simple, modern but still lacks in color...

**Describe the solution you'd like**
I would edit the icons I circled in red with more colorful ones (with the same shape)

**Describe alternatives you've considered**
Unfortunately, I don't think I've considered any alternative, but I would suggest to let the user decide whether to use the basic ones or the colored ones. There should even be an option where you can add your owns ?

**Additional context**
![pic](https://i.imgur.com/AbPtSve.png)

**Comment by Timur78** [comment]
I like it anyway. If you add a colour, it will be ugly. It's such a modern design. I think.

**Comment by R3voA3** [comment]
A setting to switch between the current once and coloured once would be welcome indeed. Question is, are there colored icons in fluent design?

**Comment by yaichenbaum** [comment]
@R3voA3 We are working on some custom icons based off on the fluent icon font. We don't plan to add a setting to switch between different icons sets, but I believe there are a couple of open issues about choosing custom icons for the widgets and sidebar.

**Comment by R3voA3** [comment]
Right now the option to set custom icons for folder and items is missing anyway, so maybe this issue becomes more relevant when/if that is implemented.

**Comment by osieltorres** [comment]
Perhaps, and I am not sure about this(just an idea), could setup icon color according the current accent color set from Settings?

**Comment by yaichenbaum** [comment]
This issue should be addressed with the latest changes in `main`.
