### ISSUE TITLE
Can you give me instructions on packing files from github into .msix or .appx using " makeappx"

### ISSUE THREAD

**Issue by Timur78** [files-community/Files#4050]
Can you give me instructions on packing files from Github into .msix or .appx using " makeappx"? Please. I want to pack your files from GitHub to .msix or .appx windows 10 app. By myself.
Sorry for my English

**Comment by gave92** [comment]
Hello, you can reach us on Discord for this. In any case you can either:
- download the compiled .msix for github (there's always one update with the latest changes)
- compile the app yourself
