### ISSUE TITLE
add outlines around file icons

### ISSUE THREAD

**Issue by kleuton05** [files-community/Files#4054]
![1](https://user-images.githubusercontent.com/51864325/111080357-e257ab80-84dc-11eb-8b16-47719c06ac4c.png)

add outlines around the files to look like a 3d effect, so the presentation of the files would be more beautiful.

**Comment by yaichenbaum** [comment]
@kleuton05 We don't have any plans to implement a custom style here, however, you can expect some changes to this UI come in one of the next updates.
