### ISSUE TITLE
add the option to choose the default layout mode for all directories.

### ISSUE THREAD

**Issue by kleuton05** [files-community/Files#4055]
add app settings to choose between details, block views ... by default for all directories.

**Comment by gave92** [comment]
1. Turn Off "Enable individual preferences for individual directories" in Settings > Files and Folders
2. Go to any folder and set your desired layout mode
3. Opz: Turn "Enable individual preferences for individual directories" back on

The selected layout at step 2 will be the default

**Comment by kleuton05** [comment]
does not work

**Comment by gave92** [comment]
@kleuton05 please define "does not work", what about if you only do point 1 and 2?

**Comment by kleuton05** [comment]
works on 1.4.1, thanks.
