### ISSUE TITLE
Add Windows 7 support

### ISSUE THREAD

**Issue by Bellisario** [files-community/Files#4056]
**Is your feature request related to a problem? Please describe.**
Actually, you can only download this app via Microsoft Store or msixbundle file, that aren't supported by Windows 7.

**Describe the solution you'd like**
Add a simple .exe file for non Windows 10 computers.

**Describe alternatives you've considered**
I use Windows 7 that is actually not supported legally, but actually supported, yet, by most apps... so, I can't change Windows only because I love this app.

**Additional context**
/

**Comment by yaichenbaum** [comment]
@Bellisario Thanks for opening this issue, Files relies on APIs and features that are only available on Windows 10. While we don't plan on backporting Files to Windows 7, Files is an open source project so anyone would be welcome to give it a try.
