### ISSUE TITLE
propriété

### ISSUE THREAD

**Issue by c4coer** [files-community/Files#4057]
it is missing when you right click on a file or a folder. it lacks in property, the security part, so it is a problem.
![Capture d’écran 2021-03-14 201042](https://user-images.githubusercontent.com/26404638/111080992-6c197000-8501-11eb-8463-6eeb8db752db.jpg)
![Capture d’écran 2021-03-14 200951](https://user-images.githubusercontent.com/26404638/111080995-6e7bca00-8501-11eb-8c23-df056ac2e743.jpg)

**Comment by gave92** [comment]
Thanks for this suggestion! Merging with #1647
