### ISSUE TITLE
Crash on search

### ISSUE THREAD

**Issue by Sturmeko** [files-community/Files#4061]
**Describe the bug**
App crashes when I click search icon and start typing. It doesn't happen all the time. I found that crash happens when search string contains character combinations "el", "ek", "kr", but only if there are some search results to display. I have some files in latvian language with special characters like "ķ", "ā", "š" etc, so it might be related to problem, this is just a wild guess though.

**To reproduce**
1. Go to 'Documents'
2. Click on 'search icon'
3. Start typing anything with "el", "ek", "kr" which give search results

**Expected behavior**
Show search results
[debug.txt](https://github.com/files-community/Files/files/6137865/debug.txt)

**System Information**
 - OS Version: Windows 10 Home 20H2 19042.867
 - App version: 1.3.0.0

**Additional context**
It happens every time I start the app.

**Comment by gave92** [comment]
This should be fixed in version 1.4.1 (insiders only)
