### ISSUE TITLE
"Close tabs to the right" is shown even when there is only one tab opened

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#4062]
**Describe the bug**
"Close tabs to the right" is shown even when there is only one tab opened

**To reproduce**
Just open a tab and right click on it

**Screenshots**
![image](https://user-images.githubusercontent.com/17484252/111088599-389e0c00-8528-11eb-8b7c-6915fef3f51b.png)

**System Information**
Edition	Windows 10 Pro
Version	20H2
Installed on	‎6/‎19/‎2020
OS build	19042.867
Experience	Windows Feature Experience Pack 120.2212.551.0

App: 1.4.1.0

**Comment by nvi9** [comment]
It seems DataContext occasionally can be null on the first context menu item (opening and closing some tabs usually make it work again). Somehow fixing this and maybe a value check (`if (MainPage.AppInstances.Count == 1 || MainPage.AppInstances.IndexOf(tabItem) ...`) could solve this.

![image](https://user-images.githubusercontent.com/42123156/111172093-d257ce80-85a5-11eb-8b3a-1a6a7c111548.png)

@R3voA3 was your On startup setting set to "Open a specific page or pages"? I managed to reproduce the null DataContext issue in that case (so far).

**Comment by R3voA3** [comment]
It was set to continue where I left off. One tab was open.

**Comment by yaichenbaum** [comment]
@R3voA3 This issue should be resolved with #4198.
