### ISSUE TITLE
Tab context menu shows entries which are not available "grayed out"

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#4063]
**Describe the bug**
Entries in the context menu are grayed out and not accessible.

**Expected behavior**
I think it would be better to hide inaccessible entries.

**Screenshots**
![image](https://user-images.githubusercontent.com/17484252/111088599-389e0c00-8528-11eb-8b7c-6915fef3f51b.png)

**System Information**
Edition	Windows 10 Pro
Version	20H2
Installed on	‎6/‎19/‎2020
OS build	19042.867
Experience	Windows Feature Experience Pack 120.2212.551.0

App: 1.4.1.0

**Comment by yaichenbaum** [comment]
@R3voA3 we show the items grayed out to improve discoverability and to indicate that such an option exists.
