### ISSUE TITLE
ERROR: Files (APP) stops working when drag and drop an tab from other tab in left side to right side mode.

### ISSUE THREAD

**Issue by johanftg** [files-community/Files#4064]
**Describe the bug**
When I have two tabs, and I wish to put these tabs on the left and right side of my screen, respectively, I have an error: the first tab gets crashed or stops working.

**To reproduce**
1.  Open 2 tabs in the same window.
2. Split one tab on the left side of the screen.
3. OPEN LIST OF TABS IN THE RESPECTIVELY BUTTON.
4. Drag and drop the other tab to the right side of the screen.
5.  [ERROR] It creates a window for the tab that I drag and drop, but the first window (left side) or tab gets crashed. 

**Expected behavior**
I prefer in step 5, we can create two windows with the first and second tabs respectively.

**Log file**
[debug.txt](https://github.com/files-community/Files/files/6137894/debug.txt)

**Screenshots**
STEP 1: 
![image](https://user-images.githubusercontent.com/57734829/111088730-987bbf00-84f6-11eb-8a39-ef0ac4a66084.png)
STEP 2: 
![image](https://user-images.githubusercontent.com/57734829/111088738-9f0a3680-84f6-11eb-8749-21b216e55057.png)
STEP 3: 
![image](https://user-images.githubusercontent.com/57734829/111088745-a7627180-84f6-11eb-9ece-0c68b295a977.png)
STEP 4: 
![image](https://user-images.githubusercontent.com/57734829/111088750-af221600-84f6-11eb-821c-fed30c12f113.png)
STEP 5: 
![image](https://user-images.githubusercontent.com/57734829/111088753-b9441480-84f6-11eb-85fe-5ef939535002.png)

**System Information**
WINDOWS 10

- Edition	Windows 10 Pro
- Version	20H2
- Installed on	‎10/‎26/‎2020
- OS build	19042.804

FILES 1.3.0.0

**Additional context**
I don't speak English, only Spanish. Sorry for the errors.

**Comment by gave92** [comment]
Mybe related: [3208733906u](https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/3208733906u/overview)

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
