### ISSUE TITLE
Erros em traduções

### ISSUE THREAD

**Issue by Acacieliton** [files-community/Files#4066]
**Describe the bug**

**To reproduce**
1. Go to '....'

**Expected behavior**

**Log file**
Please upload the log file here so that we can understand your issue better. 
* You can access it from Settings->About->Open log location. 
or 
* `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 
 
You should see a file in this directory called debug.txt or/and debug_fulltrust.txt.

**Screenshots**

**System Information**
 - OS Version: [e.g. Windows 10 20H2 19042.804] (Press WIN + PAUSE/BREAK, use the copy button at the bottom)
 - App version: [e.g. v1.0] (In the app, go to Settings -> About, the version is shown at the top)

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

Apresenta erro de tradução (PT-BR) 
![SharedScreenshot2](https://user-images.githubusercontent.com/60496124/111101225-d5a87700-851f-11eb-8533-47b719fe7f46.jpg)
![SharedScreenshot](https://user-images.githubusercontent.com/60496124/111101228-d6d9a400-851f-11eb-828e-eb0e29b11fe1.jpg)
![SharedScreenshot3](https://user-images.githubusercontent.com/60496124/111101241-df31df00-851f-11eb-8bf1-c7e9d51e29aa.jpg)

**Comment by gave92** [comment]
Merging with #3385
