### ISSUE TITLE
Hello! I using your project "files". Every 2 hours you doing something on the GitHub project. But the new versions of app "files" is very rare. Can you please start doing beta versions of your app for example 1 in the day?

### ISSUE THREAD

**Issue by Timur78** [files-community/Files#4067]
Hello! I using your project "files". Every 2 hours you doing something on the GitHub project. But the new versions of app "files" is very rare. Can you please start doing beta versions of your app for example 1 in the day?
What do you think about this?
Sorry for my english!

**Comment by d2dyno1** [comment]
@Timur78 Insider versions are already available. Join Files' [discord server](discord.gg/mr5hVu8) to see the Insider changelog and additionally gain access to Insider versions!

**Comment by Timur78** [comment]
@d2dyno1 And ho to download the .msix file from there?

**Comment by d2dyno1** [comment]
Reachout to Yair. He'll give you access to Store Insider previews

**Comment by Timur78** [comment]
Thank you!
