### ISSUE TITLE
Add possibility to pin tabs

### ISSUE THREAD

**Issue by AriKnight** [files-community/Files#4068]
**Is your feature request related to a problem? Please describe.**
when finding folders, like i have a lot of folders even though it was well-organized. sometimes it confuses me to find the one i'm finding. so there i want a feature like bookmarks and pinning a tab, it should be usefull to pin a tab we don't wanna miss and bookmark a folder location to make working easier with them.

**Describe the solution you'd like**
the tab pin and bookmarks should be same as what our internet browser did.

**Describe alternatives you've considered**
no, i don't have any alternative solutions.

**Additional context**
Device : Laptop
UI : Windows 10

**Comment by gave92** [comment]
@AriKnight thanks for this suggestion. You can already pin a folder to the sidebar, could you elaborate on how this would be different?

**Comment by AriKnight** [comment]
> @AriKnight thanks for this suggestion. You can already pin a folder to the sidebar, could you elaborate on how this would be different?

i wanted to check it but when i right click the folder i wanted to pin, the app freeze (will confirm after i can check on it)
and the pin i mentioned above was like this one on my attachment
![image](https://user-images.githubusercontent.com/43218677/111115186-3a56e680-859f-11eb-9e2e-cbdc03046249.png)

**Comment by d2dyno1** [comment]
Thanks for the suggestion! This has been already referenced here #260

**Comment by AriKnight** [comment]
> Thanks for the suggestion! This has been already referenced here #260

Oh i see, don't forget about "bookmarks" in my suggestion.

Thank you

**Comment by Konrad-Morawski** [comment]
@gave92 

> You can already pin a folder to the sidebar

How? I can't find such an option. I tried right-clicking on the tab, dragging the tab onto the sidebar, the context menu for the open folder, even Settings...

**Comment by gave92** [comment]
@Konrad-Morawski it's in the context menu that appears when you right click on a folder in the file list (or in the "empty" space of the file list)

**Comment by yaichenbaum** [comment]
Merging with #3068.

**Comment by Konrad-Morawski** [comment]
@yair100 
 
> it's in the context menu that appears when you right click on a folder in the file list (or in the "empty" space of the file list)

Huh, indeed. That was easy, although totally not aligned with my intuition.

I would propose that the option be available in the context menu for the tab - the same way it works in browsers, text editors, IDEs (that I'm familiar with).

Anyway, thanks for the clarification.
