### ISSUE TITLE
Target the .NET 5 framework

### ISSUE THREAD

**Issue by vanillajonathan** [files-community/Files#4070]
**Is your feature request related to a problem? Please describe.**
The old legacy .NET 4.7.2 Framework is holding the project back and reduces ability of cross-platform, portability, cloud builds.

**Describe the solution you'd like**
I would like to see the project target a modern version of .NET such as .NET 5 or the upcoming .NET 6.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by yaichenbaum** [comment]
@vanillajonathan Thank you for opening this issue, we are currently held back because there isn't any official support for .NET 5 and UWP applications right now. We will definitely upgrade to newer versions of .NET when it becomes a possibility in the future.

**Comment by vanillajonathan** [comment]
Oh, UWP is coming in .NET 6 in November.
