### ISSUE TITLE
Close disc tray

### ISSUE THREAD

**Issue by d2dyno1** [files-community/Files#4071]
**Is your feature request related to a problem? Please describe.**
A nice accessibility feature that's not present in Files is to close the disc tray. We can already open the tray but not close it.

**Describe the solution you'd like**
Add an ability to close the disc tray from within Files in context menu option.

**Additional context**
A piece of code that might help:
```csharp
private string returnString = "";

public void OpenTray(char cdDriveLetter)
{
    mciSendStringA("open " + cdDriveLetter + ": type CDaudio alias drive" + cdDriveLetter, returnString, 0, IntPtr.Zero);
    mciSendStringA("set drive" + cdDriveLetter + " door open", returnString, 0u, IntPtr.Zero);
}

public void CloseTray(char cdDriveLetter)
{
    mciSendStringA("open " + cdDriveLetter + ": type CDaudio alias drive" + cdDriveLetter, returnString, 0, IntPtr.Zero);
    mciSendStringA("set drive" + cdDriveLetter + " door closed", returnString, 0u, IntPtr.Zero);
}

[DllImport("winmm.dll", CallingConvention = CallingConvention.StdCall, CharSet = CharSet.Auto)]
[return: MarshalAs(UnmanagedType.I8)]
internal static extern long mciSendStringA([In][MarshalAs(UnmanagedType.LPStr)] string lpstrCommand, [In][Out][MarshalAs(UnmanagedType.LPStr)] string lpstrReturnString, [In][MarshalAs(UnmanagedType.U4)] uint uReturnLength, [In] IntPtr hwndCallback);
```

**Comment by nvi9** [comment]
I'm not sure if all hardware support this (especially in laptops). Is it possible to detect the close disc tray feature?

**Comment by d2dyno1** [comment]
> I'm not sure if all hardware support this (especially in laptops). Is it possible to detect the close disc tray feature?

I dunno if that's possible. The disc tray won't close after selecting the option I guess (?)

**Comment by d2dyno1** [comment]
@yair100 This one stayed in `discussion` for quite some time. Could you decide on it?

**Comment by yaichenbaum** [comment]
@d2dyno1 I'm fine with this as long as it only shows up on supported devices.

**Comment by d2dyno1** [comment]
> @d2dyno1 I'm fine with this as long as it only shows up on supported devices.

As far as I'm aware, there exists no win32 function to detect if the cd door can be closed. Instead, we could opt-in for "Try close door" option.

**Comment by yaichenbaum** [comment]
Is there a use case for this menu item?

**Comment by d2dyno1** [comment]
Well, the same could be asked for opening the cd tray option. So the use case for this would be closing the tray. If the user opened the tray via Files, they would be able to also conveniently close it from the app.

**Comment by yaichenbaum** [comment]
> Well, the same could be asked for opening the cd tray option. So the use case for this would be closing the tray. If the user opened the tray via Files, they would be able to also conveniently close it from the app.

@d2dyno1 agreed, I can't think of a use case for that either. The APIs to auto eject are useful when burning files to dvds but I'm not sure if either option makes sense in a file manager.

**Comment by d2dyno1** [comment]
We already have the first one, so I figured we might as well add the other one since no one else has that in store.

**Comment by yaichenbaum** [comment]
> We already have the first one, so I figured we might as well add the other one since no one else has that in store.

@d2dyno1 do you think we should remove it? It doesn't make sense to have something we can't really think of a use case for 😆

**Comment by d2dyno1** [comment]
Closed. Explanation: https://github.com/files-community/Files/pull/7255#issuecomment-991974054
