### ISSUE TITLE
Recent items on the home screen directory's text not that visible.

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#4073]
**Is your feature request related to a problem? Please describe.**
the text for recent items is small and grey into the background.

**Describe the solution you'd like**
Making the text look like the other text like directory path at the top or tabs.

**Additional context**
![image](https://user-images.githubusercontent.com/26977075/111180174-ac7dfa00-85a4-11eb-9f0f-6951d0a782b3.png)

**Comment by yaichenbaum** [comment]
@josh-65 What version of Files are you using?

**Comment by yaichenbaum** [comment]
@josh-65 This issue should be resolved with #4146.
