### ISSUE TITLE
Add the option to display recent folders in the "Recents" widget

### ISSUE THREAD

**Issue by ghost** [files-community/Files#4074]
**Is your feature request related to a problem? Please describe.**
I frequently need to return to a previously used folder to open related files to the one I'm currently working on .

**Describe the solution you'd like**
That the "Recents" widget also displays recent folders alongside recent files.  This feature would be similar to the recent folders in the favorite section in Windows Explorer, but for Files this would clutter the left pane, it is more consistent for Files to add recent folders to the Recents widget.

**Describe alternatives you've considered**
The recent folders lists appears on the FIles icon Jumplist on the taskbar, but it requires a "mental context switch" if you already have the Files app open.  I've also dragged frequently used folders to one Bundle but this is not convenient for rarely used folders.

**Additional context**
This could be implemented in tandem with [issue #2718](https://github.com/files-community/Files/issues/2718) that suggests a recent items page.

**Comment by XPoppyX** [comment]
Just a concept:

![Captura de pantalla 2021-03-15 180435](https://user-images.githubusercontent.com/61259627/111221812-bf4ef980-85b9-11eb-9baa-1c81c55182a8.png)

**Comment by marcovrv** [comment]
I see your point, it gives choice to the user.  May I suggest to use switches instead of single choice? That way it needs only two lines:

[    O] On    
Show recent files on the home page

[   O] On    
Show recent folders on the home page

In fact, to further simplify the visuals, the whole Widgets settings panel may be renamed to "Home Page Widgets"  to get rid of repetitive "on the home page" for each option.

**Comment by XPoppyX** [comment]
Option 1:
![Captura de pantalla 2021-03-15 180435](https://user-images.githubusercontent.com/61259627/111225683-de9c5580-85be-11eb-910e-44349714c733.png)

Option 2:
![opcion2](https://user-images.githubusercontent.com/61259627/111225888-1e633d00-85bf-11eb-8210-50f170e62093.png)

**Comment by mv-rodriguez** [comment]
Why no just this?

![recent folders](https://user-images.githubusercontent.com/75141668/111229027-d2a69880-85aa-11eb-99db-a8fb33576b3e.png)

The main "recent items" switch may be inferred by an OR operation of these two.

**Comment by yaichenbaum** [comment]
I should probably point out that the settings page for widgets is temporary. The actual settings will be moved to the home page at some point.

**Comment by mv-rodriguez** [comment]
Maybe we got a bit carried away by the visuals.  My apologies.

Directly related to the feature request, while my original suggestion was to add recent folders to the "Recents" widget, I do see the merit of @XPoppyX proposal to give choice to display just files, just folders, or both in the "Recents" widget.
