### ISSUE TITLE
Macrium reflect mounted backups

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#4075]
**Is your feature request related to a problem? Please describe.**
When mounting macrium reflect backups the drives can not be ejected via files but can in file explorer.

**Describe the solution you'd like**
If it possible detect if its a macrium reflect image that's mounted and add a eject option when right clicking.

**Additional context**
![image](https://user-images.githubusercontent.com/26977075/111183829-3c717300-85a8-11eb-85f2-d1bca0b80183.png)
![image](https://user-images.githubusercontent.com/26977075/111183881-498e6200-85a8-11eb-840e-31bf3aa6c65a.png)

**Comment by gave92** [comment]
Thanks for this report. This will be fixed together with #3114.
