### ISSUE TITLE
App is Slow!

### ISSUE THREAD

**Issue by arthuredgary24** [files-community/Files#4076]
The current version of Application has good design and animations. But the Application is too slow compared to the original from windows. Please make animations and other process faster!

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by yaichenbaum** [comment]
@arthuredgary24 Can you describe where animations are slowing down the app?

**Comment by arthuredgary24** [comment]
Yeah when The App is trying to open folder / whenever I Right-click on the Files. Plus I don't know when I try to open a folder, there is an Animation, thus it makes the App feels so much slower than the original Windows Version of File Explorer. Hope You understand.
Thanks

**Comment by yaichenbaum** [comment]
@arthuredgary24 You should already be able to turn of the animation for the right click context menu from the app's settings (under appearance). We are also working on other solutions to improve the speed when right clicking on files. What layout mode are you using when you find the animation slowing down the app?

**Comment by gave92** [comment]
I think he's referring to the progress bar. We should turn it off as soon as the first elements appear maybe.

**Comment by yaichenbaum** [comment]
> I think he's referring to the progress bar. We should turn it off as soon as the first elements appear if we're not doing that already.

If that's the case, it should be resolved with #3922.

**Comment by CF-71** [comment]
At least for me, the **start** of the files-app is also a bit slow. It takes a good 2.5 seconds for the workspace (Home) to appear.

Windows-Explorer appears to me immediately.

**Comment by kennymckormick** [comment]
It takes more than 1s to open a typical directory, while opening the context menu via right-click takes around 5 seconds.

**Comment by AshleighAdams** [comment]
@kennymckormick Same here, Explorer and Files side by side, explorer is instant, whereas Files takes about a second or more to load a directory.

**Comment by yaichenbaum** [comment]
There isn't one thing we can do to make Files faster, but we try to optimize the app with every update, and we believe the next update will come with further improvements to speed.

**Comment by Xairoo** [comment]
Yeah the speed is slow compared to Windows Explorer.
No matter if there are many files (like a node project with about ~1500 folders) or only 2.
It feels like accessing a network share.

Hope this will be hardly improved and finally the same speed as the Explorer.

Don't get me wrong, but things to consider:
For example I use VS Code too, it's blazing fast, also Atom. There you haven't such slow loading/listing times for folders.
Atom is based on electron (js, html, css), perhaps that would be a great base for an Explorer alternative. Thinking at Atom, using customs styles would be really easy, guess many users would love to use such an hackable Explorer alternative.

**Comment by timluther** [comment]
Not sure why this is closed because this is so very _slow_


https://user-images.githubusercontent.com/4411129/198825612-3b4c4846-a1e0-41f6-be15-83f7664503ee.mp4

**Comment by Josh-65** [comment]
This was closed since it old and nonspecific. try the preview version https://files.community/download/preview as its faster in most cases
