### ISSUE TITLE
Bug in display folder list

### ISSUE THREAD

**Issue by megaten** [files-community/Files#4080]
The folders with an updated icon are not displayed.

PS: I change the icons of some folders with the  'Rainbow folder'.
      There is the same trouble if I change the icons with th windows standard process.

Hope to be useful

**Comment by gave92** [comment]
Thanks for this report. Could you post a screenshot with Files vs Windows Explorer?

**Comment by gave92** [comment]
Thanks @megaten I've seen the screenshot. Where are those colored folders icons taken from (path on disk)?
Inside the folders with the custom icon there should be a file called "desktop.ini" (it's hidden), could you post it here?

**Comment by megaten** [comment]
So  I've done a new standard explorer with folder update on USB1 et USB2
![New explorer display](https://user-images.githubusercontent.com/6340400/111209257-16f66080-85cc-11eb-8b40-8329f568d25b.jpg)

Following the desktop.ini USB1

![USB1 folder-Desktopini](https://user-images.githubusercontent.com/6340400/111209390-3f7e5a80-85cc-11eb-8b2a-8951d94aceb8.jpg)

Following the desktop.ini Produits
![Produits folderini](https://user-images.githubusercontent.com/6340400/111210252-507b9b80-85cd-11eb-83d6-d2d8421464aa.jpg)

PS os PS: There is an another trouble between the  windows folder display timestamp and the Files display!

**Comment by megaten** [comment]
I've done the test with some other tools to change the icons color, the results are impredictable. 
So the trouble is more general not specific to one tools.

**Comment by yaichenbaum** [comment]
@megaten is this an issue in v2.0.34?
