### ISSUE TITLE
 Bug in display folder list (#4080)

### ISSUE THREAD

**Issue by megaten** [files-community/Files#4081]
Sorry I forgotten to join the picture.
![Files](https://user-images.githubusercontent.com/6340400/111200691-50c26980-85c2-11eb-8d3d-37abda6b86b4.jpg)
![Std Explorer](https://user-images.githubusercontent.com/6340400/111200774-5c159500-85c2-11eb-82f3-25d8e6a64215.jpg)

**Comment by XPoppyX** [comment]
You would have put the screenshots in the comments of the previous issue that you opened or editing the description, not necessarily opening a new issue

**Comment by gave92** [comment]
Redirecting to #4880

**Comment by megaten** [comment]
Thanks for your help.
So I add a new screen shot: USB1 and USB2 aicins are modified thru the standard windows process.
![New explorer display](https://user-images.githubusercontent.com/6340400/111207748-4a37f000-85ca-11eb-9e01-33122f5a42fe.jpg)
Behind the desktop.ini for folder Produits and USB1 to check the content.

So there is an another trouble in the folder timestamp between the time on the wondows display and the fils display.
Would you like that I add a new issue?

**Comment by gave92** [comment]
Sorry I think the "desktop.ini" was not uploaded, could you post it again?

Regarding the wrong date I think we have another similar issue opened.
