### ISSUE TITLE
Creating new folders on network drive does not refresh application

### ISSUE THREAD

**Issue by ylefebvre** [files-community/Files#4085]
**Describe the bug**
When creating a new folder on a network drive, the new folder is created but does not appear in the Files application unless I force it to refresh.

**To reproduce**
1. Go to a network drive
2. Right-click and select New | Folder
3. Give the new folder a name and click on Set Name
4. The new folder does not appear
5. Click on the refresh button and you will see the new folder appear

**Expected behavior**
Expect the new folder to be immediately visible

**Log file**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6144183/debug_fulltrust.txt)

**Screenshots**
Not applicable

**System Information**
 - OS Version: Windows 10 20H2 19042.867]
 - App version: 1.3.0.0

**Additional context**

**Comment by gave92** [comment]
Merging with #2042. At some point we changed how we listen for folders update, the "old" method would be working in this case.
