### ISSUE TITLE
Feature: Show menu when right clicking back/forward buttons to show history

### ISSUE THREAD

**Issue by winston-de** [files-community/Files#4098]
**Is your feature request related to a problem? Please describe.**
It's can be annoying clicking back (or pressing Alt+left arrow) countless times to go back to a folder I was using previously, it would be nice to have a convenient way to view the history for a tab.

**Describe the solution you'd like**
I think right clicking the back or forward buttons should show a popup of the tabs history.

**Describe alternatives you've considered**
Navigate manually. 

**Additional context**
Web browsers have this feature, this is how it is in Edge.
![image](https://user-images.githubusercontent.com/59544401/111264518-e8d14a80-85e4-11eb-9d41-c1dad48cc481.png)

**Comment by yaira2** [comment]
@winston-de this feature will be included in the next release.
