### ISSUE TITLE
Some similar function are not working. Files insider 1.4.1.0

### ISSUE THREAD

**Issue by Timur78** [files-community/Files#4099]
**Describe the bug**
Some similar functions in Files insider 1.4.1.0 and another "stable" versions are not working:
1. The network tab does not appear immediately and does not work.
2.  OneDrive tab doesn't work. 
3. Open in the terminal does not work. 

**To reproduce**
Steps to reproduce the behaviour:
1. Go to files
2. Click on OneDrive,  network tab or Open in the terminal
4. See an error

**Expected behaviour**
I  expected to happen saw the result of those functions.

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6147800/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6147801/debug_fulltrust.txt)

**System Information**
 - OS Version:  Windows 10 1909 18363.1440
 - App version: Files insider v1.4.1.0

**Comment by yaichenbaum** [comment]
@Timur78 Please open separate issues so we can track them better.
