### ISSUE TITLE
Brazilian Portuguese translation is out of sync

### ISSUE THREAD

**Issue by Lucas11200YT** [files-community/Files#4102]
I use Files in brazilian portuguese but some things are in other language, like the notifications, configuration and other texts.
![image](https://user-images.githubusercontent.com/80770315/111328279-dd196e80-864c-11eb-83b9-7b7396e8d594.png)

**Comment by yaichenbaum** [comment]
@Lucas11200YT This can happen when a translation is out of date, do you want to update the translation?

**Comment by gave92** [comment]
Known issue for a long time. Merging with #3385.

**Comment by yaichenbaum** [comment]
@gave92 The issue happens when translations are out of date, I think it's best to keep it open for every langage that's out of date so we can keep track.

**Comment by gave92** [comment]
The biggest issue is that the fallback language should always be English I think. Language files are always going to be a little out of sync.

**Comment by yaichenbaum** [comment]
@gave92 If possible, we should do that as well. However, translations that are out of sync for a while will be removed.

**Comment by yurnasg** [comment]
I will try to update the translation files. Having the English version, I redo it to Portuguese, If not too difficult. But this is a "solution" in case of delayed translation, since it is easier to understand English than Arabic.

> The biggest issue is that the fallback language should always be English I think. Language files are always going to be a little out of sync.

**Comment by yaichenbaum** [comment]
This issue will be resolved in the next release.
