### ISSUE TITLE
File Transfer progress indicator

### ISSUE THREAD

**Issue by SiRo24** [files-community/Files#4103]
**Describe the bug**

**To reproduce**
1. Go to '....'

**Expected behavior**

**Log file**
Please upload the log file here so that we can understand your issue better. 
* You can access it from Settings->About->Open log location. 
or 
* `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 
 
You should see a file in this directory called debug.txt or/and debug_fulltrust.txt.

**Screenshots**

**System Information**
 - OS Version: [e.g. Windows 10 20H2 19042.804] (Press WIN + PAUSE/BREAK, use the copy button at the bottom)
 - App version: [e.g. v1.0] (In the app, go to Settings -> About, the version is shown at the top)

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

When I copy/paste a File, the popup menu of the button in the bottom right corner displays the ongoing tasks as expected.
But the issue is, the Percentage is stuck on 0% until it switches to green and tells it is finished.

Due to this behavior I am never sure whether it is actually copying the files and have to double-check it.

When the program is asking me if it should replace files with the same name after the copying process went for a while, the percentage jumps.

Files version: 1.4.1.0
Windows version: Windows 10 Home Insider Preview  21332.1000

**Comment by gave92** [comment]
Thanks for this report. Merging with #2543.
