### ISSUE TITLE
Folder content not showing up

### ISSUE THREAD

**Issue by SiRo24** [files-community/Files#4104]
**Describe the bug**

**To reproduce**
1. Go to '....'

**Expected behavior**

**Log file**
Please upload the log file here so that we can understand your issue better. 
* You can access it from Settings->About->Open log location. 
or 
* `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 
 
You should see a file in this directory called debug.txt or/and debug_fulltrust.txt.

**Screenshots**

**System Information**
 - OS Version: [e.g. Windows 10 20H2 19042.804] (Press WIN + PAUSE/BREAK, use the copy button at the bottom)
 - App version: [e.g. v1.0] (In the app, go to Settings -> About, the version is shown at the top)

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

When I click on the path, to change the viewed folder, the content is not showing up. I have to jump back to the folder's root and click back to the location I was before.

Files version: 1.4.1.0
Windows version: Windows 10 Home Insider Preview 21332.1000

**Comment by gave92** [comment]
Thanks could you post a screenshot of Files when this issue happens?

**Comment by yaichenbaum** [comment]
@SiRo24 This issue should be resolved with #4196.
