### ISSUE TITLE
Save As replaced by Files

### ISSUE THREAD

**Issue by SiRo24** [files-community/Files#4106]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

I replaced the Windows File Explorer with your program, and I am very happy with it.
There are only a few moments the implementation is not that perfect.

For example if i search for a Folder in win search, and open it, nothing happens.
When i plug in a USB drive, and selected the autoplay feature to "show files", the old explorer opens instead.

So here is my feature request:
When i safe a file from another program, the little popup "safe as" is using the old file explorer.
It would really make the experience perfect, if even this popup is shown by your Files app.

I don't know if that is possible, but I hope so, because I really like your program

**Comment by gave92** [comment]
Thanks for this report. Unfortunately, to my knowledge, replacing the "open with" and "save as" dialogs is "impossible". Perhaps someone else knows more.

**Comment by jordan-msftfan** [comment]
This needs to replace File Dialog, and it's not a part of the File Explorer.
I don’t think there is any way to do it at the software level.

**Comment by yaichenbaum** [comment]
@gave92 It's possible to replace these dialogs by redirecting the GUIDs, but due to the complexity, we don't have plans to implement this right now. Maybe @ADeltaX will want to give it a try at some point 😆.
