### ISSUE TITLE
Just crashed during usage is all

### ISSUE THREAD

**Issue by mtratchet16** [files-community/Files#4107]
**Describe the bug**

**To reproduce**
1. Go to '....'

**Expected behavior**

**Log file**
Please upload the log file here so that we can understand your issue better. 
* You can access it from Settings->About->Open log location. 
or 
* `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 
 
You should see a file in this directory called debug.txt or/and debug_fulltrust.txt.

**Screenshots**

**System Information**
 - OS Version: [e.g. Windows 10 20H2 19042.804] (Press WIN + PAUSE/BREAK, use the copy button at the bottom)
 - App version: [e.g. v1.0] (In the app, go to Settings -> About, the version is shown at the top)

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Comment by gave92** [comment]
Hello thanks for this report When opening an issue please always specify the app version and post the app's log files so we can investigate the issue. Feel free to edit this issue description and we'll reopen this ;)

**Comment by mtratchet16** [comment]
Oops! Thanks! I wasn't quite sure how to submit that stuff, I'm pretty new
to Github.
