### ISSUE TITLE
Open in new tab

### ISSUE THREAD

**Issue by SiRo24** [files-community/Files#4108]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

I replaced the standard File Explorer with Files.
When I open Files through another program like Firefox, it always starts in a new instance. 
It would be great if there were a setting, to toggle if it should open in a new instance or a new tab when opening it from another program by clicking on "show location".

**Comment by gave92** [comment]
Thanks for this suggestion. This is currently being implemented as part of #3382
