### ISSUE TITLE
Pin Specific Folder Shortcuts to Start!

### ISSUE THREAD

**Issue by mtratchet16** [files-community/Files#4109]
**Is your feature request related to a problem? Please describe.**
Not exactly; request would just get me to use it entirely instead of the native app.

**Describe the solution you'd like**
If possible, some option to pin shortcuts to folders to Start. This is essential for my personal workflow!

**Describe alternatives you've considered**
No other alternatives except for changing my workflow into being less concise.

**Additional context**
As of now, you have the ability to pin any folders to the Start menu (even the recycle bin, control panel, etc!). My workflow consists of having folders pinned to the Start menu so that I can access them quickly without needing to navigate to them. (Namely, I keep my college related folder pinned, as well as a shortcut to my external harddrive). As of now, there is no option for this using this new app. It's difficult for me to switch (despite all of the cool features and the beautiful build) because probably only 20% of the time do I launch the File Explorer by clicking on the File Explorer icon. About 80% of the time, I'm using shortcuts I have pinned on the Start menu. I'm not certain if this request is possible, but it would help tremendously.

**Comment by gave92** [comment]
Thanks for this suggestion. We're currently implementing this :). Progress tracked in #782.

**Comment by mtratchet16** [comment]
You're awesome, keep up the good work!
