### ISSUE TITLE
Properties

### ISSUE THREAD

**Issue by SiRo24** [files-community/Files#4110]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

I really like the property windows, and they are often quite extensive (Photo properties)

But some features are missing, like changing folder/shortcut icons or adding a key combination to a file shortcut or changing the owner or starting .exe in compatibility mode...

I don't know if all these features are realizable, or if it's not possible due to security reasons. But I would rather have the old properties window show up, when I try to change the owner or something like that, instead of not being able to do it at all.

**Comment by yaichenbaum** [comment]
@SiRo24 Some of the things you mentioned such as changing icons already have open issues, for the other options, can you please open separate issues for those?
