### ISSUE TITLE
File sorting

### ISSUE THREAD

**Issue by SiRo24** [files-community/Files#4111]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

I like, how you can set an individual sorting and Layout type for every folder.
I disabled the "sort folders alongside files" feature, because I like them separated.
But I really wish, I could enable it for folders which are sorted by date, particularly the Downloads and Recycle Bin Folder.
Here it is quite confusing seeing a newer file below an older Folder.

An option which disables the mixing of file types would be very great as well

**Comment by yaichenbaum** [comment]
Merging with ##1874.
