### ISSUE TITLE
File transfer progress bar/ background File transfer

### ISSUE THREAD

**Issue by SiRo24** [files-community/Files#4112]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

The title pretty much describes the feature.
A progress bar at the bottom of the screen next to the button to show the ongoing tasks, 
which shows the progress of the current file transfer.

The other part of this feature is file transfer in the background, meaning that if you close Files the files are still getting copied or moved in the background.
The cherry on top would be, that if files are getting transferred in the background, the progress is shown with a progress bar in the action center.

The file transfer should be in a separate part of the program, so if Files crashes, the files are still getting transferred.

**Comment by yaichenbaum** [comment]
@gave92 Can this can be done when we switch to using the shell functions for file transfer operations?

**Comment by gave92** [comment]
@yair100 yep

**Comment by gh0sti** [comment]
Did you guys remove the planning project for this feature request? I don't see it in under progress or To-Do if you changed up the flow of progress of features. I really believe this feature should be added soon for showing progress of transferring files, bc otherwise I can't tell when files are done transferring from one directory to the next or from external drives.

**Comment by yaichenbaum** [comment]
@gh0sti I'm not quite sure how it got removed from the project, thanks for bringing it up.

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
