### ISSUE TITLE
Internet shortcuts and UAC

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#4114]
**Describe the bug**
 When opening a internet shortcut it will bring the UAC prompt up. I can press yes or no and it will still open the internet shortcut like it should.

**To reproduce**
Steps to reproduce the behaviour:
1. create a shortcut in old file explore
2. add internet URL and name
3. open it
4. UAC prompt shows

**Expected behaviour**
it should open the internet shortcut straight away with out the prompt

**Log file**
[debug.txt](https://github.com/files-community/Files/files/6151296/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6151297/debug_fulltrust.txt)

**System Information**
 - OS Version: Windows 10 20H2 19042.844
 - App version: v1.4.1.0

**Comment by gave92** [comment]
Thanks for this report. Could you confirm that this only happens with web shortcuts (".url" files) and not with regular shortcuts (".lnk" files)?

**Comment by josh-65** [comment]
So it most shortcuts it happens on. Doesn't happen with system shortcuts like OneDrive, folders, and the system tools that windows has but it will with all external programs.

**Comment by josh-65** [comment]
ok so going through my start menu folder of shortcuts it only happens when try to use discord (not sure if that's a discord bug though).

**Comment by yaichenbaum** [comment]
@josh-65 This issue should be resolved with #4202.
