### ISSUE TITLE
Add support for third party/optional widgets

### ISSUE THREAD

**Issue by d2dyno1** [files-community/Files#4115]
**Describe the solution you'd like**
Add support for third party widgets to the widgets tab via app extensions -> add third-party Weather widget integration in Files to match the upcoming Sun Valley Windows update.

**Additional Context**
Add more widgets to Files.

**Comment by gave92** [comment]
Having the possibility to add new widgets using app extensions it's very interesting. I'd probably not include a weather widget by default though :)
> Mainly we get to use more weather widgets around Windows

There are going to be too many weather widgets already, no need to add ours xD

**Comment by d2dyno1** [comment]
> Having the possibility to add new widgets using app extensions it's very interesting. I'd probably not include a weather widget by default though :)

:/ This was discussed on the [UWP Community](https://discord.gg/X4kZhfw8) server though. @gave92

**Comment by gave92** [comment]
Oooh a weather widget in a file manager.. ok why not.

**Comment by gave92** [comment]
Still makes 0 sense to me to have that included by default but if it's third party / option totally agreed 😂

**Comment by FireCubeStudios** [comment]
We need this. Weather widgets will provide useful insights in file management operations for example if there is a weather widget a user will be able to know the current temperature of the weather outside and use that information to process how many files to delete in a folder for a peak efficient file deletion temperature ratio to prevent overheating of CPU and increase the life span of the CPU which delays the need to replace the CPU or computer in the long run and saves money for the user.

**Comment by winston-de** [comment]
I got optional packages set up and working, I can merge it so that the code can be written to utilize them if its wanted.
![image](https://user-images.githubusercontent.com/59544401/111382928-cda61f80-8664-11eb-9079-2dc6f884ec74.png)

**Comment by d2dyno1** [comment]
Quick weather widget concept I did in Paint 3D:

![20210316_221230](https://user-images.githubusercontent.com/53011783/111384978-6dd26780-86aa-11eb-8c0f-87316d5ebbc2.png)

**Comment by yaichenbaum** [comment]
> I got optional packages set up and working (as was discussed in discord), I can merge it so that the code can be written to utilize them if its wanted.
> ![image](https://user-images.githubusercontent.com/59544401/111382928-cda61f80-8664-11eb-9079-2dc6f884ec74.png)

That would be great! Do you think we can do something similar for #3133?

**Comment by winston-de** [comment]
@yair100 Totally!

**Comment by winston-de** [comment]
Interestingly, you have to use a workaround to get optional packages to work with xaml controls.
https://stackoverflow.com/a/63823702/12493282

**Comment by winston-de** [comment]
![image](https://user-images.githubusercontent.com/59544401/111413364-5b9cfd00-869b-11eb-8c1f-4c7a7364b1bb.png)

**Comment by SOI7** [comment]
A Phone hub widget (perhaps a streamlined version of the YourPhone app, or like the ChromeOS Phone hub) would be an overkill feature to me

**Comment by Jaiganeshkumaran** [comment]
If the feature is used for something related to Files, it's fine but Weather has nothing to do with Files and you are using a WebView which uses a lot of memory and doesn't even cleanup properly.

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran This issue is about adding support for third party widgets, a weather widget is just the example we are using to developer the feature.
