### ISSUE TITLE
Enhancement: Move the options to customize widgets to the home screen

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#4116]
- [x] Remove the widgets settings page.
- [x] Add a flyout to the home page with a list of widgets that users can add to the home screen.
- [ ] Add a button that will show the option to unpin widgets and reorder them #2263.

**Comment by winston-de** [comment]
Maybe something similar to the edge ntp page?
![image](https://user-images.githubusercontent.com/59544401/111372757-4b176300-8658-11eb-9bf5-1b2489fe044c.png)

**Comment by yaichenbaum** [comment]
@winston-de I was thinking of having it work closer to the way you can add widgets to the home screen on Android.

**Comment by yaichenbaum** [comment]
@winston-de Since there are only a couple widgets right now, I ended up using that design, thanks for the idea!

**Comment by mangoepic** [comment]
I really like this feature idea because there are like 10 buttons on Home page, one of which i occasionally use. I would probably like to just get it clean
![image](https://user-images.githubusercontent.com/71931749/118393321-de601b00-b63e-11eb-871c-78cb065e7ef6.png)

**Comment by MalteTasler** [comment]
close?
