### ISSUE TITLE
The properties window background is white in dark mode

### ISSUE THREAD

**Issue by XPoppyX** [files-community/Files#4122]
With the app in dark mode, the properties window background is white

![Captura de pantalla 2021-03-16 200056](https://user-images.githubusercontent.com/61259627/111398087-8ab66d00-86a1-11eb-9f67-b7c3c92921a9.png)

**Comment by d2dyno1** [comment]
Also, the background here is black:

![image](https://user-images.githubusercontent.com/53011783/111493439-d74f8600-873d-11eb-818d-4f2a9a50bbf6.png)

**Comment by yaichenbaum** [comment]
@XPoppyX This issue should be resolved with #4145.
