### ISSUE TITLE
The Network tab functions don't work.

### ISSUE THREAD

**Issue by Timur78** [files-community/Files#4126]
**Describe the bug**
Network tab functions in Files insider 1.4.1.0 and another "stable" versions are not working:
The network tab(Сетевые диски - сеть) does not appear immediately and does not work.

**Steps to reproduce the behaviour:**

1. Go to files
2. wait
3. Click on the network tab
4. See an error

**Expected behaviour**
I expected it to happen saw the network tab.

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6147800/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6147801/debug_fulltrust.txt)

**System Information**
OS Version: Windows 10 1909 18363.1440
App version: Files insider v1.4.1.0

**Comment by gave92** [comment]
@Timur78 could you post a short cideo / screenshots to show the issue? Thanks!

**Comment by Timur78** [comment]
https://discordapp.com/channels/725513575971684472/772262608602529792/821085571606118411

**Comment by Timur78** [comment]
@gave92 https://discordapp.com/channels/725513575971684472/772262608602529792/821085571606118411

**Comment by gave92** [comment]
Thanks @Timur78, is this still an issue with Files 1.5?
If so, could you post the log files again?

**Comment by Timur78** [comment]
No, the problem has not disappeared. files insider 1.5.2.0.
[debug.txt](https://github.com/files-community/Files/files/6215655/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6215656/debug_fulltrust.txt)

**Comment by gave92** [comment]
@Timur78 there's something strange going on.. could you try to delete the two log files and post them again after triggering the issue?
Plus I'm led to believe that network tab not working it's the least of your problems.. is recycle bin for example working for you?

**Comment by Timur78** [comment]
> is recycle bin for example working for you?
No! :)
> could you try to delete the two log files and post them again after triggering the issue?
[debug.txt](https://github.com/files-community/Files/files/6215957/debug.txt)




Ок!

**Comment by gave92** [comment]
Could you check if while the app is running you see a process called "Filesulltrust.exe" in task manager? If not..

> debug_fulltrust.txt gone

I think it's time for uninstall Files -> _reboot_ -> reinstall Files :/

**Comment by Timur78** [comment]
> you see a process called "FilesFulltrust.exe" in task manager?

No. 
![image](https://user-images.githubusercontent.com/80568319/112980476-9c4c4a00-9162-11eb-9574-902b64753f5f.png)

>I think it's time for uninstall Files -> reboot -> reinstall Files :/

What for? And where is this function?

**Comment by gave92** [comment]
I mean please try to reinstall the app and reboot windows :) hopefully it will fix the issue.. if not I'm stumped
