### ISSUE TITLE
Application crashes after starting when invoked from Power Automate Desktop

### ISSUE THREAD

**Issue by na51hog** [files-community/Files#4127]
**Describe the bug**
Application opens then crashes
![PAD Command Line](https://user-images.githubusercontent.com/20238795/111466884-bbd38380-871b-11eb-8a0f-5db3fdc5f3c4.jpg)
![App Details](https://user-images.githubusercontent.com/20238795/111466887-bc6c1a00-871b-11eb-9392-ff3ca542dd2b.jpg)

https://user-images.githubusercontent.com/20238795/111467541-7499c280-871c-11eb-86f5-884fc9558e6d.mp4

[debug_fulltrust.txt](https://github.com/files-community/Files/files/6156355/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6156356/debug.txt)

 when invoked from Power Automate Desktop

**To reproduce**
Determine the PackageFamilyName and App name using Powershell Command lines
Get-AppxPackage -Name "*Files*" -> 49306atecsolution.FilesUWP_et10x9a9vyk8t
(Get-AppxPackage -Name "*Files*" | Get-AppxPackageManifest).package.applications.application -> App

Invoke the app using Run in Power Automate Desktop - see images and video
shell:appsFolder\49306atecsolution.FilesUWP_et10x9a9vyk8t!App

**Expected behavior**
Files should open and behave normally

**Log file**
You should see a file in this directory called debug.txt or/and debug_fulltrust.txt.
Attached

**Screenshots**
Attached

**System Information**
 - OS Version: 
Edition	Windows 10 Pro
Version	20H2
Installed on	‎24/‎02/‎2021
OS build	19042.867
Experience	Windows Feature Experience Pack 120.2212.551.0

 - App version: 
 - 1.3.0.0

**Additional context**
Does this problem occur again after restarting the app? - Yes

**Comment by na51hog** [comment]
Apologies - 2 images got uploaded twice in error because the original mp4 was over 10mb

**Comment by Hounsvad** [comment]
The same occurs when I launch files from powershell or cmd, under the name files.
It does not occur if an instance of files is already running.

**Comment by yaichenbaum** [comment]
@na51hog is this still an issue?

**Comment by Hounsvad** [comment]
> 

I do not experience the issue anymore, but I cannot speak to the original issue.

**Comment by na51hog** [comment]
I stopped using the Files product it wasn't ready for production, sorry.
________________________________
