### ISSUE TITLE
Remember sidebar items state

### ISSUE THREAD

**Issue by d2dyno1** [files-community/Files#4128]
**Is your feature request related to a problem? Please describe.**
After the sidebar is retracted and extended again, all sidebar menus are collapsed.

**Describe the solution you'd like**
Remember what sidebar menus were expanded and restore them when the sidebar is extended again.

**Comment by d2dyno1** [comment]
@yaichenbaum Could you please put this in TODO :grin: 🙏

**Comment by touzel** [comment]
Hi, 
It would be lovely to see this feature implemented. Thanks in advance!

**Comment by yaichenbaum** [comment]
This issue should be resolved with #8886
