### ISSUE TITLE
File gets stuck loading a directory and then crashes

### ISSUE THREAD

**Issue by timcanham** [files-community/Files#4133]
**Describe the bug**

When clicking on various "standard" directories (Desktop, Downloads, etc) the directory view gets stuck loading (a bar slides back and forth) and never shows or takes a long time (minutes) to display the contents of the directory. When you kill the program, it crashes.

**To reproduce**

1. Run app
2. Select any one of the predefined directories
3. Watch "loading bar spin slide and slide and slide...
4. Exit program
5. Crash!

**Expected behavior**
I expected the directory to load quickly. Sometimes it does.

**Log file**

[debug.txt](https://github.com/files-community/Files/files/6157223/debug.txt)

[debug_fulltrust.txt](https://github.com/files-community/Files/files/6157225/debug_fulltrust.txt)

**Screenshots**

![image](https://user-images.githubusercontent.com/8086374/111487793-e0b50000-86f5-11eb-8484-f009d0fb5dc9.png)

**System Information**

 - OS Version: [e.g. Windows 10 20H2 19042.804] (Press WIN + PAUSE/BREAK, use the copy button at the bottom)

Windows 10 Enterprise
Version 1909
OS build 18363.1440

 - App version: [e.g. v1.0] (In the app, go to Settings -> About, the version is shown at the top)

1.3.0.0

**Additional context**

It is a constant issue. I do have WSL2 installed and network mounts for WSL2 and OneDrive.

**Comment by gave92** [comment]
Thanks for this report. This issue should be fixed in version 1.4 (beta).
