### ISSUE TITLE
Language Portuguese! It is not completely defined.

### ISSUE THREAD

**Issue by luisnt** [files-community/Files#4136]
Language Portuguese! It is not completely defined. What has not been translated should be in the universal English language. Being that it is in a Persian or Arabic ligible ineligible for mere mortals.

![image](https://user-images.githubusercontent.com/10253238/111509594-a403fb80-872b-11eb-8943-2e3385de0ebe.png)

English language OK.
 
![image](https://user-images.githubusercontent.com/10253238/111509762-d0b81300-872b-11eb-8c69-3695f6db6d22.png)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #4131.
