### ISSUE TITLE
Error in the traduction to portuguese

### ISSUE THREAD

**Issue by Vi-op** [files-community/Files#4137]
**Describe the bug**
When I use the app in the portuguese appear some phrases in Arabic

**To reproduce**
1. Go to 'Settiings'
2. Click on 'Preferences and switch the language to portuguese'
3. Go to 'Settings again'
5. See error

**Expected behavior**
It is expected that the translation will be done correctly

**Log file**
Please upload the log file here so that we can understand your issue better. 
* You can access it from Settings->About->Open log location. 
or 
* `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 
 
You should see a file in this directory called debug.txt or/and debug_fulltrust.txt.
[https://drive.google.com/file/d/1GPQ7R9eYICqFb_HhcqCGcbUvrWu4P6R-/view?usp=sharing](url)

**Screenshots**
[https://drive.google.com/file/d/1Vt6znqvnM7F0_kWpgy5p_kxR6YyaOS32/view?usp=sharing](url)

**System Information**
 - OS Version: [e.g. Windows 10 20H2 18363.14440] (Press WIN + PAUSE/BREAK, use the copy button at the bottom)
 - App version: [e.g. v1.3.0.0] (In the app, go to Settings -> About, the version is shown at the top)

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?
Everytime

**Comment by yaichenbaum** [comment]
This issue should be resolved with #4131.
