### ISSUE TITLE
Play/pause bar appears when focusing in taskbar

### ISSUE THREAD

**Issue by GardenSandwich** [files-community/Files#4140]
**Describe the bug**
When hovering over the icon in taskbar, a play/pause set of buttons appears.

**To reproduce**
Open application
Move cursor over icon in taskbar and hold it there
See preview window

**Expected behavior**
Play/pause button should not appear, considering that opening a playable file will use another application

**Log file**
2021-03-17 15:56:01.6488|INFO|.ctor|App launched|
2021-03-17 15:56:02.0964|INFO|.ctor|Drive added: C:\, Fixed|
2021-03-17 15:56:12.3833|INFO|.ctor|Adding cloud provider "OneDrive" mapped to C:\Users\**keeping name for privacy**\OneDrive|
2021-03-17 15:56:27.1374|INFO|.ctor|Running on ARM: False|

**Screenshots**
![image](https://user-images.githubusercontent.com/80854305/111531353-cb15f980-873a-11eb-8dd2-65a3c2cf065f.png)

**System Information**
Edition	Windows 10 Pro
Version	20H2
Installed on	‎1/‎30/‎2021
OS build	19042.867
Experience	Windows Feature Experience Pack 120.2212.551.0

Version 1.3.0.0

**Additional context**
Appears consistently, and is greyed out permanently.

**Comment by yaichenbaum** [comment]
@GardenSandwich This issue should be resolved in the next update to Windows 10.
