### ISSUE TITLE
Context Menu - Modern share integration

### ISSUE THREAD

**Issue by LordMethenor** [files-community/Files#4141]
**Is your feature request related to a problem? Please describe.**
A little bit of backstory: cross-device sharing is a bit of a mess. Outside of Apple's walled garden, Microsoft and Google both have options, confusingly named "Nearby Share" and "Nearby Sharing". I use a free service called Send Anywhere that lets me share between my phone, PC, and Chromebook or any web browser and to generate links to share with people who don't have an account. It's a lot simpler and more specialized than, say, Dropbox. It doesn't use any fancy Wifi direct or Bluetooth shenanigans, but it's essentially one-click. On Android, you can both create a link/code or directly send to your registered device as share menu items, but on Windows, one-click sharing only works through dynamic context menu items.

**Describe the solution you'd like**
I have noticed that the Files app supports all context menu items, including dynamic ones, so I have two requests.
1. In conjunction with context menu customization requests, add the ability to execute selected menu items from the modern share UI, with png or svg icons.
2. Spinoff app or extension that bridges context menu, command line, and modern share UI.

**Describe alternatives you've considered**
I have been trying to find a way to convert those items to command line so I can make a shortcut and add them to Windows 10's modern share, but aside from some abandonware that doesn't support dynamic items, I've found nothing.
**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
@LordMethenor do you have a shell extension that provides this functionality? I'm not sure this is something we'd build directly into Files.

**Comment by LordMethenor** [comment]
No, I don't.

**Comment by yaichenbaum** [comment]
It seems like Microsoft is working towards this with the built-in share menu so I'm going to close this for now.
