### ISSUE TITLE
The Arabian message is shown for byte size unit when I set language to Korean

### ISSUE THREAD

**Issue by amarese** [files-community/Files#4148]
**Describe the bug**
The Arabian message is shown for byte size unit when I set language to Korean, as following screenshots.

**To reproduce**
1. Change language to Korean.
2. See any folder or files.

**Expected behavior**
Korean unit should be shown otherwise English would be better alternative.

**Screenshots**
![image](https://user-images.githubusercontent.com/3795252/111602233-7cd62880-8816-11eb-9896-e1e91fc1f490.png)
![image](https://user-images.githubusercontent.com/3795252/111602300-8f506200-8816-11eb-8a95-96bec01fd3f6.png)

**System Information**
 - OS Version: [Windows 10 20H2 19042.746]
 - App version: [e.g. v1.3.0]

**Comment by XPoppyX** [comment]
> The Arabian message is shown for byte size unit when I set language to Korean

That should be fixed with #4006. It will be available in the next update.
