### ISSUE TITLE
Display full path in tooltip when hovering over a tab

### ISSUE THREAD

**Issue by alan-strickland** [files-community/Files#4149]
**Is your feature request related to a problem? Please describe.**
A regularly have to access shared folders over a network on multiple servers often the the shared folders have the same name or are the admin shares of the servers. For example: \\server1\d$ and \\server2\d$. In the tabs there is no indication of which server the share belongs too so I end up with lots of tabs with the same name.

<img width="620" alt="files-tabs-share-computername" src="https://user-images.githubusercontent.com/2310848/111606714-76708e00-87cf-11eb-896b-7cc0e115a1e4.png">

**Describe the solution you'd like**
When accessing a network path show the computer name in the tab. Something like "server1 - Current Directory Name", "server2 - Current Directory Name"

**Comment by yaichenbaum** [comment]
@alan-strickland is this still an issue in the preview version? https://files.community/download/preview

**Comment by alan-strickland-red** [comment]
@yair100 yes this is still in an issue in the preview version.

<img width="662" alt="image" src="https://user-images.githubusercontent.com/103668835/169046655-b8b749a3-4c27-462b-833f-b57bf9507c4b.png">

![image](https://user-images.githubusercontent.com/103668835/169046707-8a424d8c-4c16-4d7f-af96-12ca91c0906c.png)

**Comment by alan-strickland-red** [comment]
Ideally showing the machine name then the directory name would be great something like "machine: d$", but even showing the full path in the tooltip when you hover the tab would make it a little better.

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
This is technically an issue for any folder with the same name, tabs are meant to reflect the actual folder but we should be able to solve this by showing the path in a tooltip.

**Comment by blouflashdb** [comment]
This issue can be closed as this feature is already implemented.
