### ISSUE TITLE
This program doesnt read the files and directories

### ISSUE THREAD

**Issue by Bunter221** [files-community/Files#4150]
**Describe the bug**

**To reproduce**
1. Go to '....'

**Expected behavior**

**Log file**
Please upload the log file here so that we can understand your issue better. 
* You can access it from Settings->About->Open log location. 
or 
* `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 
 
You should see a file in this directory called debug.txt or/and debug_fulltrust.txt.

**Screenshots**

**System Information**
 - OS Version: [e.g. Windows 10 20H2 19042.804] (Press WIN + PAUSE/BREAK, use the copy button at the bottom)
 - App version: [e.g. v1.0] (In the app, go to Settings -> About, the version is shown at the top)

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Comment by Bunter221** [comment]
I was checking if the backup had been done tonight.

Files 1.3.0.0 said not done.. Opened file explorer see image it had in fact been done but not read by files.

Program removed as its not valid in what it is displaying..

![image](https://user-images.githubusercontent.com/4508935/111623775-f1bd5880-883e-11eb-92be-857a65425c0c.png)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6163909/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6163910/debug.txt)
[debug.txt](https://github.com/files-community/Files/files/6163911/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6163912/debug_fulltrust.txt)

**Comment by Bunter221** [comment]
hope I have helped.

**Comment by XPoppyX** [comment]
You closed the issue
