### ISSUE TITLE
Drag and Drop

### ISSUE THREAD

**Issue by mtratchet16** [files-community/Files#4151]
**Is your feature request related to a problem? Please describe.**
Not sure if it's possible, but having the ability to drag/drop outside of the window (i.e. to import Lightroom photos).

**Describe the solution you'd like**
Having the ability to drag/drop outside of window.

**Describe alternatives you've considered**
This is really the only alternative for this feature.

**Additional context**
N/A

**Comment by gave92** [comment]
Thanks for this report. Could you confirm that dropping to Windows Explorer works for you? 
If it does it means the external program is not playing nicely with UWP I guess..

**Comment by mtratchet16** [comment]
> Thanks for this report. Could you confirm that dropping to Windows Explorer works for you?
> If it does it means the external program is not playing nicely with UWP I guess..

I actually just messed around with it a bit and found out how. In order for me to drag and drop, I have to first select (Ctrl + Click) and then drag. I have single click to open off, is there any way to enable single clicking to select so I don't have to hold down Ctrl?

**Comment by gave92** [comment]
At the moment to enable single click to select you need to disable "open items with one click" option.
We're looking for a way to enable dragging without selecting the item first.

**Comment by honsontran** [comment]
I also wanted to add onto this that I'm unable to drag files into the files windows as well.

Just for some context, UAC is disabled and Explorer.exe is also on admin privs.

I can drag stuff out of files, but not onto them. I'm on Files v1.3.0.

I know this has been discussed before:
https://github.com/files-community/Files/issues/834

However, it's still not fixed for me. Any ideas?

**Comment by VOOM108** [comment]
I can d&d files from Files to a desktop app only, if more than one file is selected and I press Ctrl. after starting to drag until releasing. I found no way to drag a single file into those apps. Also if I start to press Ctrl. before I start to drag, it does not even work with several files. "Open with" would not help because this is about dragging files to an email in Outlook (open with would start a new mail) or media to Davinci Resolve etc.
