### ISSUE TITLE
Side bar doesn't update when devices are unplugged

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#4152]
**Describe the bug**
When unplugging devices the side bar wont update and they will stay there

**Expected behaviour**
Device unplugged should disappear

**System Information**
 - OS Version: Windows 10 20H2 19042.844
 - App version: 1.4.1.0

**Comment by gave92** [comment]
Thanks for this report. What kind of devices? Usb keys / mounted .iso / external hard drives..

**Comment by josh-65** [comment]
I've only tried with my tab and my external HDD.

**Comment by yaichenbaum** [comment]
@josh-65 This issue should be resolved with #4192.
