### ISSUE TITLE
Legacy Renaming

### ISSUE THREAD

**Issue by mtratchet16** [files-community/Files#4153]
**Is your feature request related to a problem? Please describe.**
Not really a problem as much a loss of productivity (though I admit, not by much).

**Describe the solution you'd like**
Being given the option to rename files in the manner by which the legacy Explorer has an option to: By clicking the file name (twice) and typing the name. As of now, it demands a right-click, finding "rename" and then typing the name.

**Describe alternatives you've considered**
Maybe having an option in the settings to turn on/off some legacy features such as this one. I'm sure some people despise this manner of renaming so having it optional would be best.

**Additional context**
N/A

**Comment by josh-65** [comment]
you can do this in version 1.4.1 not sure when the update will be out and not sure if it works with 1.3.

**Comment by mtratchet16** [comment]
> you can do this in version 1.4.1 not sure when the update will be out and not sure if it works with 1.3.

Awesome, I'm still waiting on that update but glad it's been introduced!

**Comment by yaichenbaum** [comment]
@mtratchet16 This feature has been included in Files since v1.0, what version of Files do you have?

**Comment by mtratchet16** [comment]
> @mtratchet16 This feature has been included in Files since v1.0, what version of Files do you have?

I have 1.3, but clicking on the label (or double clicking) does not allow me to rename; I'm only able to via right-clicking.

**Comment by yaichenbaum** [comment]
@mtratchet16 Do you have this issue in all the layout modes?

**Comment by generalguy41** [comment]
#2976 👀

**Comment by yaichenbaum** [comment]
Merging with #2976
