### ISSUE TITLE
Custom Folder Icons

### ISSUE THREAD

**Issue by mtratchet16** [files-community/Files#4154]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem, but a preference.

**Describe the solution you'd like**
An option to customize the folder icons.

**Describe alternatives you've considered**
Possibly not having an in-app option to customize folder icons (you can do this now via legacy File Explorer), but at least recognizing the icon being changed and showing that image.

**Additional context**
I use the custom folder icons for most every-day folders I use. While Files _does_ recognize custom icons (as in if you physically upload an image you want to have used for a folder), it does not recognize it if you replace a folder icon with one of the other default system icons. To customize a folder icon, in File Explorer, right click the folder > properties > customize > change icon... 

I'm not interested in the sidebar for Files recognizing the icons necessarily, but I definitely feel like while browsing, these folder icons should be visible; even if Files has its own "interpretation" of the specific icons, that's fine by me.

**Comment by yaichenbaum** [comment]
Merging with #4154.
