### ISSUE TITLE
Feature: Add option to choose the default layout mode

### ISSUE THREAD

**Issue by mtratchet16** [files-community/Files#4155]
**Is your feature request related to a problem? Please describe.**
I like to view my files in medium or large icons, but it's defaulted at list view. 

**Describe the solution you'd like**
To have an option to default the view for _all_ folders would be great. I only recently found out that the legacy File Explorer has such an option (Set folders to preferred size, then go to view > options > view > apply to folders > apply/okay). If there were an option in the settings that's more straightforward ("layout mode: [large/medium/small/tiles/details]") that would be awesome!

**Describe alternatives you've considered**
Not sure of any other potential alternatives.

**Additional context**
N/A

| Capability | Priority |
| :---------- | :------- |
| This proposal will add a combo box to the folder preferences section allowing users to select the default layout mode | Must |

![image](https://user-images.githubusercontent.com/39923744/189020124-07d5c41f-82c4-42f9-b02c-d9d0f95fc2e0.png)

**Comment by gave92** [comment]
Thanks for this suggestion. You should already be able to set a default layout by:
- turning off "enable individual preferences for folders"
- setting your desired layout mode for any directory
- turning back on "enable individual preferences for folders"

**Comment by mtratchet16** [comment]
> Thanks for this suggestion. You should already be able to set a default layout by:
> 
> * turning off "enable individual preferences for folders" option in Files settings
> * setting your desired layout mode for any directory
> * turning back on "enable individual preferences for folders"
> 
> But it's not really straight forward. (Plus this may not work anymore the latest version)

AH THANK YOU!

**Comment by AndrewLaganaro** [comment]
Thanks. This solved my issue. Really sorry for opening an issue on this but I really couldn't find a way to do it.

I think the option "enable individual preferences for folders" is kinda vague about its functionality. I suggest changing it to make it more clear, like **"Use one layout in all folders"**, **"Use the same layout in all folders"** or something on that sort.

**Comment by yaichenbaum** [comment]
> Thanks. This solved my issue. Really sorry for opening an issue on this but I really couldn't find a way to do it.
> 
> I think the option "enable individual preferences for folders" is kinda vague about its functionality. I suggest changing it to make it more clear, like **"Use one layout in all folders"**, **"Use the same layout in all folders"** or something on that sort.

This is more of a workaround as this setting affects other preferences beyond the layout mode.

**Comment by vincenormand** [comment]
> Thanks for this suggestion. You should already be able to set a default layout by:
> 
> * turning off "enable individual preferences for folders" option in Files settings
> * setting your desired layout mode for any directory
> * turning back on "enable individual preferences for folders"
> 
> But it's not really straight forward. (Plus this may not work anymore the latest version)

FYI, this does not work anymore + I cannot even save a layout to a single folder...
Is there another workaround ?

**Comment by furopi** [comment]
Thanks that worked for me, but I must say... the way of disabling and re-enabling is not very intuitive... Maybe you can find a more user friendly way of achieving the same goal! Cheers, and thank you for the great tool you provide to us!!!
