### ISSUE TITLE
Files crashes almost immediately

### ISSUE THREAD

**Issue by BradMBurke** [files-community/Files#4156]
**Describe the bug**
When I open "Files", it shows me the interface for a few seconds and then crashes. (Closes)

**To reproduce**
1. Launch "Files"
2. It crashes....
3. No error displayed other than "Something went wrong"... Report? 
4. When I select "Yes", it takes me to GitHub.

**Expected behavior**
Files should work.

**Log file**
 
[debug.txt](https://github.com/files-community/Files/files/6165205/debug.txt)

[debug_fulltrust.txt](https://github.com/files-community/Files/files/6165208/debug_fulltrust.txt)

**System Information**
![image](https://user-images.githubusercontent.com/80538625/111651116-8e461300-87cb-11eb-9bf0-d6e11b1eff3f.png)

**Comment by gave92** [comment]
Thanks for this report. This issue should be fixed in version 1.4.
Could you confirm you're asking Files 1.3?

**Comment by baalho** [comment]
same exact issue, and i can confirm i am on v 1.3
