### ISSUE TITLE
Allow pinning external drives to the sidebar

### ISSUE THREAD

**Issue by mtratchet16** [files-community/Files#4157]
**Is your feature request related to a problem? Please describe.**
Legacy File Explorer allows for pinning external drives to the sidebar. While the path leads to an error if the drive is disconnected, it's very useful for those who use it on desktops as extra "permanent" storage.

**Describe the solution you'd like**
An option to pin drives to the sidebar.

**Describe alternatives you've considered**
Not sure of any alternatives to this. 

**Additional context**
While I'm personally not in the group that uses their external drive as permanent extra storage, as a content creator I use it very regularly when I'm on the go with my laptop. So having it as a quick access item is very useful.

**Comment by yaichenbaum** [comment]
@mtratchet16 This issue should be resolved in the preview version. https://files.community/download/preview
