### ISSUE TITLE
Idioma

### ISSUE THREAD

**Issue by SouzadxsadcsdffcswcfwsGabriel2018** [files-community/Files#4159]
![image](https://user-images.githubusercontent.com/42853069/111677397-f1509d80-87fd-11eb-86c7-44c419185864.png)

Algumas partes estão em árabe no programa.

**Comment by XPoppyX** [comment]
É porque ainda não foram traduzidos para o português. Já existe uma solução para que o texto não traduzido para o seu idioma apareça em inglês em vez de árabe.
Não posso garantir quando a tradução para o seu idioma será atualizada.
**(Tradutor do Google)**

**Comment by gave92** [comment]
Thanks for this report. This issue has been fixed in development version.
