### ISSUE TITLE
ongoing tasks does not seem to work correctly

### ISSUE THREAD

**Issue by jadamnoah** [files-community/Files#4160]
I have a linux server managing a raid array and keep a bunch of files on it. Many of them are large. I copy them back and forth between my windows computers and the server.

The bottom right hand notification area does not seem to calculate the percent of task completed for network transfers. They do complete, but it just says 0% the entire time until it updates with task completed.

This seems to happen every time I copy a large file over the network.

It would be if the status was made more prominent (not hidden in icon) and indicated rate of transfer as well as correct percent of task completed.

**Comment by gave92** [comment]
Merging with #2543. Currently progress is only updated after each file has been copied.
