### ISSUE TITLE
Files crashes on deleting files used by another process and clicking Ongoing tasks icon

### ISSUE THREAD

**Issue by bogdanbryzh-official** [files-community/Files#4162]
**Describe the bug**
Tried to delete "ChromeSetup.exe" after installing Chrome. Files told me that this file is used by another process. Then "Ongoing Tasks" started to glow. I clicked and Files crashed.

**To reproduce**
1. Try to delete a file used by some process.
2. Confirm deletion.
3. Confirm that file is used by another process ("Ongoing tasks"'s icon starts glowing).
4. Click "Ongoing Tasks".
4. Files crashes.

**Expected behavior**
Just not to crash)

**Log file**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6166931/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6166932/debug.txt)

**Screenshots**
![image](https://user-images.githubusercontent.com/66746788/111690733-3d1f3900-8836-11eb-8f1b-fda1098ca578.png)
![image](https://user-images.githubusercontent.com/66746788/111690776-4a3c2800-8836-11eb-93ca-9a7b8127829c.png)
![image](https://user-images.githubusercontent.com/66746788/111690816-558f5380-8836-11eb-881e-7d55ae4557f3.png)
![image](https://user-images.githubusercontent.com/66746788/111690862-617b1580-8836-11eb-87bd-318f5321ab56.png)
![image](https://user-images.githubusercontent.com/66746788/111690899-6b047d80-8836-11eb-9b81-ef547975f746.png)

**System Information**
 - OS Version: Windows 10 20H2 (OS Build 19042.631)
 - App version: Version 1.3.0.0

**Additional context**
An error occurs on every file I have tried.

**Comment by bogdanbryzh-official** [comment]
Either way, bug still exists

**Comment by gave92** [comment]
Thanks for this report. I can confirm this issue is fixed in the development branch and the fix will be included in the next public version.

**Comment by bogdanbryzh-official** [comment]
Thanks!👍
