### ISSUE TITLE
Duplicate WSL sidebar items

### ISSUE THREAD

**Issue by winston-de** [files-community/Files#4164]
**Describe the bug**
On occasion, WSL sidebar items will be loaded multiple times.

**To reproduce**
Does not seem to reproduce consistently, happens on occasion. The number of duplicates varies.

**Expected behavior**
Should only load once.

**Log file**
Nothing related to WSL seems to be in the logs, will try debugging this myself to find anything else.

**Screenshots**
![image](https://user-images.githubusercontent.com/59544401/111711362-e4de3c00-8821-11eb-903d-54fd92ce30db.png)

**System Information**
 - OS Version: build 21337.1000
 - App version: 1.4.42.0

**Additional context**

**Comment by yaichenbaum** [comment]
@winston-de This issue should be resolved with #4193.
