### ISSUE TITLE
The backgrounds of the new tab page widgets are weird

### ISSUE THREAD

**Issue by pklion** [files-community/Files#4169]
**Describe the bug**
The backgrounds of the new tab page widgets are weird.

**To reproduce**
1. Change the theme to light
2. Open a new tab

**Expected behavior**
Restore the behavior.

**Log file**
Please upload the log file here so that we can understand your issue better. 
* You can access it from Settings->About->Open log location. 
or 
* `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 
 
You should see a file in this directory called debug.txt or/and debug_fulltrust.txt.

**Screenshots**
![image](https://user-images.githubusercontent.com/78145811/111760642-4a91fd00-88e2-11eb-9f51-d1bf722443cf.png)

**System Information**
 - OS Version: Windows 10 20H2 19042.868
 - App version: v1.4.42.0

**Additional context**
N/A

**Comment by XPoppyX** [comment]
With the latest changes to `main`, it looks like this currently:

![Captura de pantalla 2021-03-19 082250](https://user-images.githubusercontent.com/61259627/111772984-505cf380-888c-11eb-8451-aaa2cac13939.png)

**Comment by pklion** [comment]
OK, I understand.
