### ISSUE TITLE
Make Files to the resident program

### ISSUE THREAD

**Issue by pklion** [files-community/Files#4170]
**Is your feature request related to a problem? Please describe.**
I think Files's startup performance is a bit slow.

**Describe the solution you'd like**
Make it to the resident program to improve performance.

**Describe alternatives you've considered**
N/A

**Additional context**
![image](https://user-images.githubusercontent.com/78145811/111762189-11f32300-88e4-11eb-9a9d-1ff3f3b698a6.png)

**Comment by ttalonso** [comment]
In my case it is true that on an average computer (intel i3) it is somewhat slow, but on my Ryzen 5600x desktop with Nvme, you can barely appreciate the charging icon and it is very fast.

**Comment by yaichenbaum** [comment]
@pklion We don't have any plans for this right now, Files already uses pre launch which should help Files open faster over time. We are also making improvements to performance with every update so you can expect Files to get faster over time.

**Comment by yaira2** [comment]
We're excited to share that startup performance will be significantly improved in the upcoming release of version 3. You can download the preview version from our website https://files.community/download.
