### ISSUE TITLE
Clearcase menu item not showing in context menu

### ISSUE THREAD

**Issue by TheYggdrazil** [files-community/Files#4172]
ACK

**Describe the bug**
The IBM Rational Clearcase context menu sub-menu is not visible.

**To reproduce**
0) Have IBM Clearcase installed and running...
1) Right-click on a clearcase view folder in Explorer.exe, check that the Clearcase sub-menu is available
2) Right-click on a clearcase view folder in Files, check that the Clearcase sub-menu is nowhere visible

**Expected behavior**
The Clearcase sub-menu shall appear in the context menu

**Log file**
[debug.txt](https://github.com/files-community/Files/files/6170818/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6170819/debug_fulltrust.txt)

**Screenshots**
![Explorer exe](https://user-images.githubusercontent.com/17179073/111775355-f02c7880-88b0-11eb-8601-6c9c17bd2a1a.png)
![Same folder in Files](https://user-images.githubusercontent.com/17179073/111775467-15b98200-88b1-11eb-88fe-7326ee953e3f.png)

**System Information**
Windows 10 version 1909 build 18363.1377
App version 1.3.0.0

**Additional context**
N/A

**Comment by yaichenbaum** [comment]
Merging with #8251
