### ISSUE TITLE
Folder size

### ISSUE THREAD

**Issue by yann-mrt** [files-community/Files#4174]
Good Day,
Not sure if this was already asked, if it was sorry about this, I didn't find it in the previous request:
Would it be possible to have the size of the folder appear like it is appear for the files ?

**Is your feature request related to a problem? Please describe.**
-> not problem, just feature request

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?
-> Version 1.3.0.0

**Comment by yaichenbaum** [comment]
Merging with #3944
