### ISSUE TITLE
Desktop and Downloads missing from the sidebar

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#4179]
**Log file**
[debug.txt](https://github.com/files-community/Files/files/6172865/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6172867/debug_fulltrust.txt)

**Screenshots**
![image](https://user-images.githubusercontent.com/26977075/111814928-fa5f6e80-88d2-11eb-9b20-299fd75eadd9.png)

**System Information**
 - OS Version: Windows 10 20H2 19042.80
 - App version: v1.4.42.0

**Comment by yaichenbaum** [comment]
Merging with #3962.

**Comment by josh-65** [comment]
why was this merged it doesn't seem related. The bug is that there now missing when they were there previously in 1.4.0.0.

**Comment by yaichenbaum** [comment]
@josh-65 right now the default libraries are hardcoded, #3962 will show all libraries and will resolve this issue.

**Comment by josh-65** [comment]
Ok sure but desktop and downloads are default library arnt they?

**Comment by nvi9** [comment]
FYI Desktop and Downloads are not libraries.
Libraries can be found in `%appdata%\Microsoft\Windows\Libraries` folder with `.library-ms` extension.
