### ISSUE TITLE
New Directory

### ISSUE THREAD

**Issue by CyrilCharlier** [files-community/Files#4183]
**Is your feature request related to a problem? Please describe.**
Not a big problem : When you want create a new directory, the focus is not in the zone where you type the name of the new directory. I must click in the zone and after i can name the directory. 

**Describe the solution you'd like**
Please, get the focus in this zone, then i will save a click ;)

**Describe alternatives you've considered**
Just click in the zone before typing

**Additional context**
I talk about this zone : version 1.3.0.0
![image](https://user-images.githubusercontent.com/11455745/111861785-39340980-8951-11eb-9493-69505cf99257.png)

**Comment by gave92** [comment]
Thanks for this report. This issue has been fixed on the development version.
