### ISSUE TITLE
Make card backgrounds on the home page lighter

### ISSUE THREAD

**Issue by asuetin** [files-community/Files#4184]
**Is your feature request related to a problem? Please describe.**
Update 1.4.42.0 made card backgrounds much darker than 1.4.1.0. I think the new color looks worse with the black text and sticks out too much compared to the rest of the UI.

**Describe the solution you'd like**
Bring back the old lighter color.

**Comment by josh-65** [comment]
They apparent remove it temporally for WinUi 2.6 update.
