### ISSUE TITLE
Move the home button on top out of favourites

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#4185]
**Describe the solution you'd like**
Moving it to the top makes more sense since then it will always be there collapsed or not and accessible without favourites open.

**Comment by yaichenbaum** [comment]
The home item will eventually have the option to unpin it just like any other page, keeping this in mind, I am not sure it's a good idea to move it out of the favorites section.

**Comment by d2dyno1** [comment]
> The home item will eventually have the option to unpin it just like any other page

If that's gonna happen, #4132 will become more relevant @yair100

**Comment by yaichenbaum** [comment]
@josh-65 Should we keep this open to continue the discussion?

**Comment by josh-65** [comment]
Don't think it necessary as you said the home button going to act like a pin able thing like the others anyway

**Comment by yaichenbaum** [comment]
Sounds good, thanks!
