### ISSUE TITLE
Cloud Drives and Network drives show up after 10secs

### ISSUE THREAD

**Issue by sfksuperman** [files-community/Files#4186]
It happens all the time that "Cloud Drives" and "Network Drives" in the left side appears after 5-10 sec delay. Check the before and after pics in the screenshot.
![image](https://user-images.githubusercontent.com/34414624/111878559-a4232600-89cd-11eb-8cdc-11dc60fee672.png)

**Comment by gave92** [comment]
Thanks for this report. This issue has been fixed in he development version.

**Comment by sfksuperman** [comment]
Fixed? When? I'm using 1.3.0.0 version and faced this issue just after installing it like 2 hours ago.

**Comment by gave92** [comment]
Fixed in _the development version_, it's beta and not yet released to everyone :)

**Comment by sfksuperman** [comment]
> Fixed in _the development version_, it's beta and not yet released to everyone :)

Unless you release that version, why you closed this bug? Can we have the ETA of it's release?

**Comment by gave92** [comment]
> Why you closed this bug?

Because open bugs here means that a contributor may pickup the issue and try to fix it, but this is fixed already in the latest code.

> Can we have the ETA of it's release?

Perhaps @yair100 can give an estimate.

**Comment by sfksuperman** [comment]
> Perhaps @yair100 can give an estimate.

Can we have a reply from him?

**Comment by yaichenbaum** [comment]
@sfksuperman This issue was closed since it's no longer an issue in the `main` branch, we are still testing the latest changes but a release will probably be availible in a couple of weeks.

**Comment by sfksuperman** [comment]
> @sfksuperman This issue was closed since it's no longer an issue in the `main` branch, we are still testing the latest changes, but a release will probably be available in a couple of weeks.

"couple of weeks" is a long run to go. But anyways, I'm looking forward to it since it's very annoying to use inbuilt file manager when you have an alternative one.

**Comment by gave92** [comment]
@sfksuperman if you wish to get access to more frequent updates, you can join the insider flight group by filling out this [form](https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAO__Qw_X6FUM0pUSzMxNUlCWE1FVENKVlVNVUNTRVpOUS4u).
Please note that the insider version may have additional issues / unstable features.

**Comment by sfksuperman** [comment]
> @sfksuperman if you wish to get access to more frequent updates, you can join the insider flight group by filling out this [form](https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAO__Qw_X6FUM0pUSzMxNUlCWE1FVENKVlVNVUNTRVpOUS4u).
> Please note that the insider version may have additional issues / unstable features.

Ok I did filled it. But see, I will be reply every then and now if I believe that something is not working and may suggest features too.
Note: When will I come to know that this bug is fixed and released? Like where to get the notification?

**Comment by gave92** [comment]
> I will be reply every then and now if I believe that something is not working and may suggest features too.

Users feedback is important to us, so please do :)

> When will I come to know that this bug is fixed and released?

If you open a bug report on github you'll get notified when it's been reaolved. For  insiders version I believe the changelog is only published on [Discord](https://discord.gg/mr5hVu8)
