### ISSUE TITLE
Unable to access FTP Folder which is created in inbuilt file explorer of Windows 10

### ISSUE THREAD

**Issue by sfksuperman** [files-community/Files#4187]
Two issues:

Unable to access a FTP folder created in inbuilt file explorer (of win 10) using this file explorer. Clicking on it just says "The folder is empty". Check out the screenshots where you can see that I am able to access the ftp folder of my phone in inbuilt file explorer but not in this.

Also, there is not option to "Add a network location" via which I can set up a ftp folder using this file explorer.

![image](https://user-images.githubusercontent.com/34414624/111879937-a89c0e80-89ce-11eb-964e-d03a24b21064.png)

**Comment by gave92** [comment]
Thanks for this report. Please post the app's debug files and specify the apps' version and Windows 10 version so we can investigate the issue 👍

**Comment by gave92** [comment]
PS: you can "Add a network location" from Files from the homepage (works both for mapping network drives and adding network locations):

![image](https://user-images.githubusercontent.com/9673091/111881594-631d1880-89b1-11eb-9e9b-1591d04fecc5.png)

Note: the dialog will likely open behind the Files window.

**Comment by sfksuperman** [comment]
> PS: you can "Add a network location" from Files from the homepage (works both for mapping network drives and adding network locations):
> 
> ![image](https://user-images.githubusercontent.com/9673091/111881594-631d1880-89b1-11eb-9e9b-1591d04fecc5.png)
> 
> Note: the dialog will likely open behind the Files window.

I couldn't see any option here:

![image](https://user-images.githubusercontent.com/34414624/111881756-084ae780-89d8-11eb-9cfa-4f4c822a470f.png)

**Comment by gave92** [comment]
I think you've hidden the drives from the homepage, check here:
![image](https://user-images.githubusercontent.com/9673091/111881816-92805500-89b2-11eb-9c92-ea90cffef7f0.png)

**Comment by sfksuperman** [comment]
> I think you've hidden the drives from the homepage, check here:
> ![image](https://user-images.githubusercontent.com/9673091/111881816-92805500-89b2-11eb-9c92-ea90cffef7f0.png)

Ok yeah it's fine and I can see that and that was my second question. But here is the thing for the first question which is, Why the already created FTP folder isn't showing anything at all? Also, when I checked the details of it, it is showing me that it's not a ftp server folder but a recycle bin. Please check why the folder is not working.

![image](https://user-images.githubusercontent.com/34414624/111881911-c1112680-89d8-11eb-9473-a0b5d4c5b2cd.png)

**Comment by gave92** [comment]
Please post the app's debug files and specify the apps' version and Windows 10 version so we can investigate the issue.

* You can access debug files from Settings->About->Open log location. 
or 
* `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 
 
You should see two files in this directory called debug.txt and debug_fulltrust.txt.

**Comment by sfksuperman** [comment]
Ok sharing it with you the 2 log files:
Files: v1.3.0.0
Windows 10: Version: 20H2 (OS Build 19042.868)
Please keep my details safe and intact and don't share it with third parties. And fix the issue please.

[debug.txt](https://github.com/files-community/Files/files/6176193/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6176194/debug_fulltrust.txt)

**Comment by gave92** [comment]
[Internal comment]
FTP works fine for me in latest main but the issue of showing Recycle bin properties for root ftp folders is still present.

**Comment by gave92** [comment]
@sfksuperman as it may be relevant, what app are you using on your phone side for FTP?

**Comment by sfksuperman** [comment]
> @sfksuperman as it may be relevant, what app are you using on your phone side for FTP?

I used [this](https://play.google.com/store/apps/details?id=com.medhaapps.wififtpserver&hl=en_SG&gl=US) app. But I haven't tried any other app like Mix Xplorer or other file managers.

**Comment by Josh-65** [comment]
Is this still an issue?

**Comment by sfksuperman** [comment]
I have to check this, but for now please close this issue. If it persists, I will re-open it.
Thanks.
