### ISSUE TITLE
Refresh?

### ISSUE THREAD

**Issue by DaveUnicorn** [files-community/Files#4197]
Hello
I wanted to confirm that you have to manually refresh, that you cannot set refresh to automatic..

I was unable to locate a setting, so I am double checking.

Thanks

**Is your feature request related to a problem?**
A clear description of what the problem is.

**Describe the solution**
A clear description of what you want.

**Describe alternatives you've considered**
A clear description of any alternative solutions or features you've considered.

**Additional comment**
Add any other comment or screenshots about the feature request here. What device type/UI layout and app version?

**Comment by gave92** [comment]
Hello @DaveUnicorn, you shouldn't have to refresh a folder manually, it should be automatic so this sounds like a bug.
Could you add more details:
- App version
- When do you find its is not refreshing? After creating, pasting a file?

**Comment by DaveUnicorn** [comment]
My issue may now be resolved. I was unable to duplicate the problem as described below

 Below was what I originally observed with 1.3.0.0
1. I right click deleted a file. 
2. File did not disappear
3. clicked the Refresh icon
4. File was gone

**Comment by DaveUnicorn** [comment]
Thanks for following up !
