### ISSUE TITLE
File preview is broken in debug mode

### ISSUE THREAD

**Issue by d2dyno1** [files-community/Files#4206]
**Explain the bug**
The details of file preview are not shown, only folder previews are displayed correctly. Additionally the UI of sound and video files is broken

**Screenshots**
 Working (old):
![image](https://user-images.githubusercontent.com/53011783/111916887-6da4e400-8a7d-11eb-9568-9b67312139ff.png)

 
Broken (new):
![image](https://user-images.githubusercontent.com/53011783/111916877-6382e580-8a7d-11eb-8fa9-12032ee65707.png)

**Comment by d2dyno1** [comment]
Fyi @winston-de

**Comment by winston-de** [comment]
@d2dyno1 Thanks for reporting this.
Are you referring to the messed up icons in the player, or the details not showing?

**Comment by d2dyno1** [comment]
@winston-de both.

**Comment by winston-de** [comment]
@d2dyno1 
The messed up icons are an issue with WinUI 2.6, not with Files.
![image](https://user-images.githubusercontent.com/59544401/111917198-e71be280-8a3b-11eb-8a97-f11dc7e3296c.png)

As for the details not showing, I can't reproduce the issue, do you have any other information or a specific file I could test with?
![image](https://user-images.githubusercontent.com/59544401/111917410-197a0f80-8a3d-11eb-9930-54d0affa0c43.png)

**Comment by yaichenbaum** [comment]
@d2dyno1 I can't reproduce this issue in v1.4.46.

**Comment by d2dyno1** [comment]
@winston-de Samle .mp3 file that neither works:

https://drive.google.com/file/d/1jeUUo55WWuHI8ruVwpqtBNSpfx_n7sDC/view?usp=sharing

**Comment by yaichenbaum** [comment]
@d2dyno1 What version of Files do you have?

**Comment by d2dyno1** [comment]
That was the latest commit where the Interaction was removed on

**Comment by d2dyno1** [comment]
@yair100 @winston-de Update: This was not caused by #4189. I've cloned the commit before that, and the issue was still present

**Comment by winston-de** [comment]
@d2dyno1 I'm testing on the latest version of main, and the file works as expected.
![image](https://user-images.githubusercontent.com/59544401/111922492-505d1f00-8a57-11eb-9665-a43751295ea0.png)

**Comment by d2dyno1** [comment]
@winston-de "Works on my machine" 😂

**Comment by d2dyno1** [comment]
Yo, even the icons are aligned!

**Comment by winston-de** [comment]
@d2dyno1 Wait, that was the wrong screenshot

![image](https://user-images.githubusercontent.com/59544401/111922573-d4afa200-8a57-11eb-9e0a-7f0913489d39.png)

**Comment by d2dyno1** [comment]
What? Then why were they aligned in the previous one?

**Comment by winston-de** [comment]
@yair100 On the subject, would it be alright if I made the logger in App.xaml.cs a public property, and used it to log errors caught when loading the preview and/or details? This would make it much easier to debug issues such as this.

**Comment by winston-de** [comment]
@d2dyno1 I accidently tested on the release version instead of my local dev build.

**Comment by winston-de** [comment]
@d2dyno1 I know it's asking a lot, but could please clone [this branch](https://github.com/winston-de/Files/tree/PreviewPaneErrorHandling), do the same thing with it, then upload the log files afterwards? 
This will help debug the issue.

**Comment by d2dyno1** [comment]
Sure, but I'll do it tomorrow

**Comment by yaichenbaum** [comment]
> Yo, even the icons are aligned!

The icon alignment is an issue with WinUI.

**Comment by d2dyno1** [comment]
@winston-de I've just tested your branch and it still doesn't work :(

**Comment by winston-de** [comment]
@d2dyno1 Yeah I didn't expect it to, could you upload the log file please?

**Comment by d2dyno1** [comment]
@winston-de Here it is: [debug.txt](https://github.com/files-community/Files/files/6184372/debug.txt)

**Comment by winston-de** [comment]
@d2dyno1 Thanks. This is very interesting.
```
2021-03-22 19:04:50.2768|ERROR|Files.App|System.Exception: A security problem occurred. (Exception from HRESULT: 0x800C000E)
   at Files.ViewModels.Properties.FileProperty.RetrieveAndInitializePropertiesAsync(StorageFile file, String path)
   at Files.ViewModels.Previews.BasePreviewModel.GetSystemFileProperties()
   at Files.ViewModels.Previews.BasePreviewModel.LoadAsync()|System.Exception: A security problem occurred. (Exception from HRESULT: 0x800C000E)
   at Files.ViewModels.Properties.FileProperty.RetrieveAndInitializePropertiesAsync(StorageFile file, String path)
   at Files.ViewModels.Previews.BasePreviewModel.GetSystemFileProperties()
   at Files.ViewModels.Previews.BasePreviewModel.LoadAsync()
```
I have never seen this before, but I will see if I can fix it.

**Comment by d2dyno1** [comment]
Could it be because I'm running in debug mode?

**Comment by winston-de** [comment]
@d2dyno1 This doesn't occur with the store version, correct?

**Comment by d2dyno1** [comment]
> @d2dyno1 This doesn't occur with the store version, correct?

It does not. The store version works as intended.

**Comment by winston-de** [comment]
@d2dyno1 what build are you on?

**Comment by d2dyno1** [comment]
(From MS Store) 
![image](https://user-images.githubusercontent.com/53011783/112040803-eec7ae00-8b45-11eb-966e-fa584924e41f.png)

**Comment by winston-de** [comment]
@d2dyno1 there dont seem to be any changes since 1.3 that changed that part of the code, so yes, I think this is an issue that occurs in debug mode. If you see this occur in a release build, please let me know.

**Comment by yaichenbaum** [comment]
@duke7553 Is this specific to debug mode?
@d2dyno1 Can you check if this is still an issue with the latest in `main`?
