### ISSUE TITLE
Some menu items and options in the navigation toolbar don't work

### ISSUE THREAD

**Issue by winston-de** [files-community/Files#4211]
**Explain the bug**
Write a clear description of what the bug is.

**To reproduce**
1. Go to any folder
2. Open selection flyout, click on select all
3. Nothing happens
4. Repeat for all other options in flyout with same result

**Expected behavior**
The flyout items should perform their tasks.

**Logfile**
Nothing relevant. 

**Screenshots**

https://user-images.githubusercontent.com/59544401/111933877-8ca37600-8a7d-11eb-8e93-198d3d23c2e5.mp4

**System Information**
 - OS Version: 21337.1010
 - App version: 1.4.47.0

**Additional comment**
Restart does not fix.
The keyboard shortcuts, however, do still work.

**Comment by yaichenbaum** [comment]
@winston-de I can't reproduce this issue on my end.

**Comment by winston-de** [comment]
@yair100 I can reproduce this in both the stable version and in the latest version of main. I'll see if I can debug it.

**Comment by winston-de** [comment]
This issue does not actually seem to be limited to the selection options, new tab, new window, and new pane in the ... menu are not working either. Changing the toggles for show file extensions and show hidden items in the display options flyout dont work either.
It looks like the issue is that none of the RelayCommands are getting fired when a flyout item is pressed, but I don't know much more. I'll look more into it in the morning.

**Comment by yaichenbaum** [comment]
@winston-de I was able to reproduce it with the latest changes.

**Comment by winston-de** [comment]
I just tested, it works pre-#4189. 
fyi @d2dyno1

**Comment by d2dyno1** [comment]
![when-1](https://user-images.githubusercontent.com/53011783/112020981-1d875980-8b31-11eb-96e8-f36eefaae454.png) @winston-de Thanks for the report. I'll look into it. Is there anything more broken besides this?

**Comment by winston-de** [comment]
@d2dyno1 There's a few other things, but they appear to have been broken before your commit.
