### ISSUE TITLE
This PC icon from desktop should open Files App.

### ISSUE THREAD

**Issue by harismuntazir** [files-community/Files#4223]
Can you make This PC icon from desktop open Files app instead of File Explorer from windows. Thanks..

**Comment by josh-65** [comment]
I'm pretty sure that would be a windows limitation. You could try using the registry edit to make files the default explorer.
https://files-community.github.io/docs/#/articles/replace-file-explorer

**Comment by gave92** [comment]
You may look at the comment in #3090 for a way to do that. Note that there may be additional problems, eg you'll loose access to the control panel.

**Comment by yaichenbaum** [comment]
Merging with #6462.
