### ISSUE TITLE
Option to choose Details or Icons once for everwhere.

### ISSUE THREAD

**Issue by harismuntazir** [files-community/Files#4224]
Like in windows explorer there is a option to choose whether we want Details view or Icon view by default everywhere. That allows us to choose the view for every file and folder to be either Details or Icons Style..
Its located in windows explorer at
This PC
View Tab 
then in Options Section.

**Comment by gave92** [comment]
You should be able to:

1. Turn Off "Enable individual preferences for individual directories" in Settings > Files and Folders
2. Go to any folder and set your desired layout mode
3. Optional: Turn "Enable individual preferences for individual directories" back on

The selected layout at step 2 will be the default.
