### ISSUE TITLE
Open file location doesn't show path properly.

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#4225]
**Explain the bug**
When I open a file/programs location via the start menu the path bar will not display the folders name correctly. Content will also not be displayed when clicking on paths in the path bar.

**To reproduce**
1. Type a program name in start menu
2. Click on "open file location"
4. See the broken folder.

**Expected behaviour**
It should display the path like if I went to it manually and the programs files should be displayed.

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6184296/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6184297/debug_fulltrust.txt)

**Screenshots**
![image](https://user-images.githubusercontent.com/26977075/112035254-44e12500-8b37-11eb-9035-dd1e496c2f0a.png)

**System Information**
 - OS Version: Windows 10 20H2 19042.870
 - App version: 1.4.47.0

**Comment by gave92** [comment]
I assume you have Files set as default explorer right?

**Comment by josh-65** [comment]
yeah the screen shot is what i get when clicking it

**Comment by josh-65** [comment]
So I think the issue is with longer then 6 character folder it will do the old windows limitation and add ~1 witch the folder doesn't exist so it doesn't load anything.

**Comment by josh-65** [comment]
Ok so it seem to open the folders content more often in 1.5 but still has the path bar issues and doesn't always work.
