### ISSUE TITLE
Properties window multiple background colors

### ISSUE THREAD

**Issue by KristofKekesi** [files-community/Files#4226]
**Explain the bug**
In the properties window below the window's title the dialog tab has a wrong background.

**To reproduce**
1. Right click
2. Click properties on the context menu

**Expected behavior**
Same background across the window.

**System Information**
 - OS Version: Windows 10 Pro 21H1 19043.899
 - App version: 1.4.49.0

**Comment by yaichenbaum** [comment]
This is the expected design, but we can look into changing it.
