### ISSUE TITLE
.zip files do not have an icon

### ISSUE THREAD

**Issue by kaname-png** [files-community/Files#4228]
**Explain the bug**
The icon of the files with .zip extension do not appear, in the windows explorer the compressed files of .zip format always have an icon, since the windows explorer itself can open .zip files.

**To reproduce**
1. Go to 'Folder with .zip file'
2. Click on 'No'
3. Scroll down to 'No'
4. See the error

**Expected behavior**
File icon.

**Logfile**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6185953/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6185955/debug.txt)

**Screenshots**
![image](https://user-images.githubusercontent.com/56084970/112072395-5b877c00-8b37-11eb-9066-64b22d512615.png)

**System Information**
 - OS Version: Windows 10 20H2 19042.870
 - App version: 1.3.0.0

**Additional comment**
No

**Comment by gave92** [comment]
Thanks for this report. Merging with #3834.
