### ISSUE TITLE
Enhancement: Add a way to cancel a search

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#4231]
**Explain the bug**
There seems to be no way to cancel the search and the search seems to be going on forever.

**To reproduce**
1. Navigate to a folder
2. Search for something which is not in that folder

**Expected behavior**
Search should either be cancelable or should stop pretty quickly saying that no item with given name was found

https://user-images.githubusercontent.com/17484252/112075809-81357500-8b79-11eb-97bf-955d64251e80.mp4

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5842.
