### ISSUE TITLE
Slide menu should move to normal state when clicking on the items in collapsed state

### ISSUE THREAD

**Issue by chuchanpr** [files-community/Files#4232]
**Is your feature request related to a problem?**
Slide menu should move to normal state when clicking on the items in collapsed state instead of showing items in a fly out menu.

**Describe the solution**
Either one:

1. When clicking on a item on a collapsed side menu, un-collapse the side menu
2. Provide an option in settings for existing working model and new model; allowing user to choose their preferance

**Describe alternatives you've considered**
Keep the side bar un-collapsed

**Additional comment**
We can add a setting to follow both options

**Comment by yaichenbaum** [comment]
Thank you for your feedback, we don't have plans to make this change.
