### ISSUE TITLE
Provide option to resize widgets

### ISSUE THREAD

**Issue by chuchanpr** [files-community/Files#4233]
**Is your feature request related to a problem?**
Provide option to resize widgets. The Bundles take up a lot of space nevertheless of the number of items on the bundle

**Describe the solution**
Following options can be considered:
1. Allow option to resize the widgets
2. The size of the bundles can be predefined to a smaller size and the widget can increase in size (both x and y) based on number of items on the bundle
3. Keep the bundle to a fixed size (small/big); when clicking on the bundle open the bundle in a flyout menu to show all items

**Describe alternatives you've considered**
No alternatives considered at this time

**Additional comment**
The bundle should also provide option to add more than 8 items

**Comment by yaichenbaum** [comment]
Thank you for your feedback. We don't have plans to implement this option.
