### ISSUE TITLE
Files keep showing previous files and folders inside a drive when it is unplugged or access denied.

### ISSUE THREAD

**Issue by kimlimjustin** [files-community/Files#4235]
**Explain the bug**
FIles keep showing previous files and folders inside a drive when it is unplugged or access to read to drive is denied.

**To reproduce**
1. Plug a drive/USB
2. Open the drive/USB inside Files
3. Unplug it
4. Files will show a popup saying drive unplugged
5. FIles will show the previous files and folders inside the unplugged drive

**Expected behavior**
Just return to home or don't show anything

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6187549/debug.txt)

**System Information**
 - OS Version: Microsoft Windows 10 Home Single Language 10.0.18363 N/A Build 18363
 - App version: 1.3.0.0

**Additional comment**
Also happens when the access to read the drive is denied.

**Comment by gave92** [comment]
What happens if you turn off the caching option in Files settings > Experimental?

**Comment by kimlimjustin** [comment]
> What happens if you turn off the caching option in Files settings > Experimental?

It shows "This folder is empty"

**Comment by gave92** [comment]
Thanks for confirming, so it's good.
