### ISSUE TITLE
Network drive listed under "Drives"

### ISSUE THREAD

**Issue by Dylan-Osborne** [files-community/Files#4236]
**Explain the bug**
Network drive mounted using [RaiDrive](https://www.raidrive.com/) is listed under "Drives" instead of "Network drives". In my case the I am using RaiDrive to mount Nextcloud storage with WebDAV.

**To reproduce**
1. Install RaiDrive and setup a WebDAV storage account.
2. Open Files.
3. Mounted drive is listed under "Drives" instead of "Network Drives".

**Expected behavior**
Network drive should be listed in the "Network Drives" section instead of "Drives".

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6187896/debug.txt)

**Screenshots**
Files:
![image](https://user-images.githubusercontent.com/46000533/112114193-6f2af500-8bc0-11eb-8ae9-96ff35382406.png)
File Explorer:
![image](https://user-images.githubusercontent.com/46000533/112114237-7b16b700-8bc0-11eb-8091-489a1db53163.png)

**System Information**
 - OS Version:
Version	20H2
OS build	19042.868
Experience	Windows Feature Experience Pack 120.2212.551.0

 - App version: 1.5.0.0

**Additional comment**
The log indicates that the drive is a network drive (`2021-03-23 10:08:12.4217|INFO|.ctor|Drive added: Z:\, Network|`) and the drive also uses the default Files network drive icon
![image](https://user-images.githubusercontent.com/46000533/112114954-52db8800-8bc1-11eb-97e5-38d1bbb42c2d.png)
Is it possible that it's being listed under "Drives" because it has has assigned a drive letter without manually mapping the network drive (It's mounted automatically by RaiDrive)?

**Comment by gave92** [comment]
Thanks for this report. Currently "network drives" section is a misnomer, it should be "network locations". Mapped drives are indeed under Drives.

@yair100 what's your opinion on this? Move network drives under the network section?

**Comment by yaichenbaum** [comment]
@gave92 Mapped drives can be move to the network section. However, we should continue to display them in the drives widget.

**Comment by spAnser** [comment]
Maybe there should be a network locations widget.

That is one of the main reasons I have not fully switched to files over file explorer. I can see all my network locations under This PC in the windows file explorer but that doesn't appear to be an option in this.

**Comment by yaichenbaum** [comment]
Merging with #5135
