### ISSUE TITLE
Issues with Google Drive through Google Drive FS

### ISSUE THREAD

**Issue by crashmit** [files-community/Files#4238]
**Explain the bug**
App crashes. First, I had it crash when chaning the layout mode on a Google Drive folder. Later, navigation to a Google Drive folder would leave the content pane empty and crash after a few seconds.

**To reproduce**
1. Go to Google Drive Folder
2. App Crash

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6190320/debug.txt) <-- contains relevant inforation
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6190324/debug_fulltrust.txt)

**Screenshots**

![image](https://user-images.githubusercontent.com/58466626/112161965-e924a380-8beb-11eb-9da0-4cf029f94d88.png)

**System Information**
 - Files v1.5, Windows 20H2

**Additional comment**
Does happen after restarting. I use GoogleDriveFS which is technically an enterprise software that also runs on regular accounts. It creates a virtual Drive G: that contains the Files. It uses FileStream so only used or selected files are permanently saved, the others are streamed if required.

**Comment by crashmit** [comment]
Resetting the app solved the app crashes, wouldn't expect to need to do this on every major update.

**Comment by crashmit** [comment]
Same behaviour again, a day later. Guess reinstalling the app was only a very temporary fix.

**Comment by gave92** [comment]
This is fixed on main.
