### ISSUE TITLE
Display Options flyout disappears after a few seconds only for Details and Tiles view

### ISSUE THREAD

**Issue by generalguy41** [files-community/Files#4240]
**Explain the bug**
Display Options flyout disappears after a few seconds only for Details and Tiles view.

**To reproduce**
1. Go to any directory.
2. Change layout views between all views.
3. See issue.

**Expected behavior**
Either the panel will not disappear for Details and Tiles view, or it will disappear for the Grid views.

**Logfile**
Nothing in log files.

**Screenshots**

https://user-images.githubusercontent.com/8879244/112167899-35112180-8bc7-11eb-8bd7-63155e3f0258.mp4

**System Information**
 - OS Version: 
Edition	Windows 10 Pro Insider Preview
Version	Dev
Installed on	‎2021-‎03-‎17
OS build	21337.1010
Experience	Windows 10 Feature Experience Pack 321.5601.0.3

 - App version: v1.5.0.0

**Additional comment**
Have run into a couple of instances where the flyout does **not** disappear when switching to Details view. I thought it may be related to the timeout after the mouse moves off the flyout. If you move the mouse away very quickly, you can make the flyout disappear in grid view as well, but even then it's inconsistent.

https://user-images.githubusercontent.com/8879244/112169101-44449f00-8bc8-11eb-8308-0b1833e3c0bb.mp4

**Comment by yaichenbaum** [comment]
This issue appears to be resolved in `main`.
