### ISSUE TITLE
Open items from the sidebar in a new tab by clicking on the mouse wheel

### ISSUE THREAD

**Issue by SiRo24** [files-community/Files#4241]
**Is your feature request related to a problem?**
A clear description of what the problem is.

**Describe the solution**
A clear description of what you want.

**Describe alternatives you've considered**
A clear description of any alternative solutions or features you've considered.

**Additional comment**
Add any other comment or screenshots about the feature request here. What device type/UI layout and app version?

It would be very intuitive if one could open a folder in a new tab by clicking it with the middle mouse button

**Comment by yaichenbaum** [comment]
This feature is implemented in v1.5.

**Comment by SiRo24** [comment]
But not when clicking on the pinned folders on the left side

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
