### ISSUE TITLE
Customizable sidebar

### ISSUE THREAD

**Issue by SiRo24** [files-community/Files#4242]
**Is your feature request related to a problem?**
A clear description of what the problem is.

**Describe the solution**
A clear description of what you want.

**Describe alternatives you've considered**
A clear description of any alternative solutions or features you've considered.

**Additional comment**
Add any other comment or screenshots about the feature request here. What device type/UI layout and app version?

It would be great if it was possible to change the order and name or even icon of the folders pinned to the left panel.

**Comment by yaichenbaum** [comment]
Merging with #1069.
