### ISSUE TITLE
Recycle bin crash back and the display is very confusing

### ISSUE THREAD

**Issue by 00LT00** [files-community/Files#4245]
**Explain the bug**
1. When I enter the recycle bin from sidebar, it will crash back
2. There is an error in the deletion time of the deleted shortcut like below. I don't know if there will be other files with the same problem. (Both chose to sort by time)
![image](https://user-images.githubusercontent.com/47566260/112182634-6aa22300-8c38-11eb-8795-8680d8df4b26.png)
3. Error in displaying folder name. (I scrolled down a distance to avoid the wrong shortcut)
![image](https://user-images.githubusercontent.com/47566260/112183547-53176a00-8c39-11eb-9f68-e214871864f4.png)

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6191373/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6191374/debug_fulltrust.txt)

**System Information**
版本	Windows 10 家庭中文版
版本号	20H2
安装日期	‎2020/‎11/‎8
操作系统版本	19042.867
体验	Windows Feature Experience Pack 120.2212.551.0

**Additional comment**
Every time you open it, it takes a long time to display whether it is a recycle bin or an ordinary folder, but this is not the focus of this issue

**Comment by yaichenbaum** [comment]
@00LT00 Is this still an issue in v1.5?

**Comment by 00LT00** [comment]
@yair100 I don't know. Because I'm still v1.3. Microsoft Store didn't remind me to upgrade. Do you have some other way to download?

**Comment by 00LT00** [comment]
I upgrade to 1.5 by downloading the app directly from MCS.
The folder name has become normal.
But the shortcuts were still error 
![image](https://user-images.githubusercontent.com/47566260/112266541-1ede9080-8caf-11eb-8c43-d7d1b0175e28.png)

**Comment by 00LT00** [comment]
Any update?

**Comment by yaichenbaum** [comment]
@00LT00 The issue has been added to the backlog.
