### ISSUE TITLE
Custom themes show always show up in settings.

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#4246]
**Is your feature request related to a problem?**
When there are no themes it disperses entirely making it confusing it find. It should also have a button next to it to open the themes folder.

**Describe the solution**
Have it always be there and show only the default option if no themes are present. And add a button like the date format one to open the themes folder.

**Additional comment**
![image](https://user-images.githubusercontent.com/26977075/112186173-cc429d00-8bf8-11eb-8194-5168eea369a7.png)

**Comment by josh-65** [comment]
I should also add it should look for new themes files when clicked on so that we only need to restart once it can be slow on some older or less capable machines.

**Comment by yaichenbaum** [comment]
@josh-65 The custom theme options are meant for advanced users, showing the empty combo box will likely be confusing to users even if we include a teaching tip. I am not sure showing the combo box will be any more helpful than the link to the documentation on the about page.

**Comment by josh-65** [comment]
Not sure how it wold be confusing for users it just hiding functionality. Since there is also a public themes repository it a simple of putting a file in the themes folder if users knew it was there.

**Comment by yaichenbaum** [comment]
@josh-65 The settings in Files should work as is, an empty combo box isn't something that works out of the box. Adding a link can help teach the user how to use the feature, but it's not something that we can show by default until the setting works out of the box. We don't have much to share right now, but we are looking into the possibility of including a couple themes by default and providing an optional package for the user to access additional themes without importing them on their own.

**Comment by yaichenbaum** [comment]
@josh-65 Should we keep this open to continue tracking it? We are working on including some themes with the app by default.

**Comment by josh-65** [comment]
I thought it wasn't needed as there now a themes extension in the store for easy access and since there going to be some included by default anyway.
