### ISSUE TITLE
open github discussions

### ISSUE THREAD

**Issue by nt4f04uNd** [files-community/Files#4250]
**Is your feature request related to a problem?**
as titled

**Describe the solution**
open github discussions, so we could create discussions without polluting the issue tracker.

**Describe alternatives you've considered**
none

**Additional comment**
as a use case of discussions, i wanted to open one to ask - i really like this project, is there a chance you are going to intergrate it with microsoft as an official explorer revamp?

**Comment by yaichenbaum** [comment]
@nt4f04uNd Discussions for Files happen on Discord and it's been working pretty well so unless that changes, we don't plan to open up discussions on GitHub.

**Comment by nt4f04uNd** [comment]
ok
