### ISSUE TITLE
Number of files in Recycle Bin persists after emptying

### ISSUE THREAD

**Issue by MattBDev** [files-community/Files#4251]
**Explain the bug**
After emptying the Recycle Bin using the context menu in the file list, the number of items in the Recycle Bin is still the original number of items before being emptied. I had 93 items in my Recycle Bin and when I emptied it, the folder still said 93 items until I refreshed it. 

**To reproduce**
1. Go to Recycle Bin
2. Right click on empty space inside the file list.
3. Click Empty Recycle Bin
4. Watch files get deleted.
5. Folder should be empty but the number of files at the bottom of the screen is wrong.

**Expected behavior**
I expected to see the number of files in the Recycle Bin listed as 0. The screenshot included below shows what I saw and what I expected to see. 

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6191979/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6191980/debug_fulltrust.txt)

**Screenshots**
The picture of my Recycle Bin after the files were deleted:
![image](https://user-images.githubusercontent.com/4009945/112199161-40bf1100-8be4-11eb-9dce-ac2077202d32.png)
What I expected to see after my files were deleted: 
![image](https://user-images.githubusercontent.com/4009945/112199477-972c4f80-8be4-11eb-846a-f064c1f03807.png)

**System Information**
 - OS Version: Windows 10 21H1 build 19043.899
 - App version: 1.5.0.0

**Additional comment**
The number of items in the Recycle Bin is correct after refreshing the folder.

**Comment by trama** [comment]
@MattBDev as you said, however, the empty bin operation is actually carried out, it is only the view that is not refreshed upon operation conclusion.
So I infer it is more a matter of triggering a periodic refresh of the view after the user click on Empty bin, isn't it?

**Comment by yaichenbaum** [comment]
This issue is resolved in `main`.
