### ISSUE TITLE
file is deleted on drag and drop from desktop cancel

### ISSUE THREAD

**Issue by nt4f04uNd** [files-community/Files#4252]
**Explain the bug**
if you have a file "A" in folder, then you drag and drop another "A" to this folder from the desktop and press "Cancel", the original file is deleted

**To reproduce**
see above

**Expected behavior**
file not to be deleted on cancel

**logfiles**
[debug.txt](https://github.com/files-community/Files/files/6192061/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6192062/debug_fulltrust.txt)

**System Information**
 - OS Version:  Windows 10 2004 19041.867
 - App version: 1.5.0.0

**Additional comment**
no

https://user-images.githubusercontent.com/39104740/112201666-8b12b300-8c21-11eb-93eb-4e6a86d8866c.mp4

**Comment by yaichenbaum** [comment]
@gave92 Were you able to reproduce this?
