### ISSUE TITLE
allow drag and drop from explorer

### ISSUE THREAD

**Issue by nt4f04uNd** [files-community/Files#4253]
**Is your feature request related to a problem?**
no

**Describe the solution**
as titled

**Describe alternatives you've considered**
none

**Additional comment**

https://user-images.githubusercontent.com/39104740/112202674-b21db480-8c22-11eb-855b-a22252b8dee8.mp4

**Comment by gave92** [comment]
Thanks for this report. Could you check if you can drop the file on the sidebar or the navigation bar of Files?

**Comment by gave92** [comment]
Merging with #4130.

**Comment by nt4f04uNd** [comment]
oh this is actually a bug, i see
to reproduce it, you need to open the same directory in both Files and explorer

i don't see how this is similar to #4130, because there he cannot d&d at aloo

> Could you check if you can drop the file on the sidebar or the navigation bar of Files?

i met a lot of weird bugs after i tried this, trying to isolate and summarize them
