### ISSUE TITLE
drag and drop label artifacts

### ISSUE THREAD

**Issue by nt4f04uNd** [files-community/Files#4256]
**Explain the bug**
sometimes when drag and drop a file there will occur some artifacts on the label. tried with Russian and English - happens to both

**To reproduce**
drag and drop some file

**Expected behavior**
no artifacts

**Logfile**
n/a

**System Information**
 - OS Version:  Windows 10 2004 19041.867
 - App version: 1.5.0.0
 - Monitor: 144hz 1440p
 - Video card: RTX 2060

https://user-images.githubusercontent.com/39104740/112208264-396e2680-8c29-11eb-92e0-a02e38ec6cc1.mp4

https://user-images.githubusercontent.com/39104740/112208275-3c691700-8c29-11eb-8285-1025c1e1a7a5.mp4

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
