### ISSUE TITLE
Cloud drives (OneDrive) makes Files crash

### ISSUE THREAD

**Issue by RGarrido03** [files-community/Files#4258]
**Explain the bug**
When opening any folder but OneDrive, _Files_ works as expected. However, when opening the app and choosing firstly OneDrive, _Files_ stays loading the folder forever.
After the bug occurs, I need to close and reopen the app in order to run properly. If I don't do that, every folder starts to crash and keep loading forever.

**To reproduce**
1. Go to OneDrive (either personal or work/school accounts) folder.

**Expected behavior**
Work as expected

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6195855/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6195856/debug_fulltrust.txt)

**Screenshots**
![image](https://user-images.githubusercontent.com/57329376/112219276-acbd6b80-8c1c-11eb-8128-9a9ce6c3fc67.png)

**System Information**
 - OS Version: Windows 10 21337.1010 x64 en-US
 - App version: 1.5 from Microsoft Store

**Additional comment**
This problem happens with OneDrive, I don't know about other cloud drives since I don't have any.

**Comment by gave92** [comment]
Also #4269

**Comment by RGarrido03** [comment]
I attached the logs on the first post. However, here they go too:
[debug.txt](https://github.com/files-community/Files/files/6195839/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6195840/debug_fulltrust.txt)

Yup it's the same issue as #4269

**Comment by RGarrido03** [comment]
After upgrading to today’s Insider Preview build (21343), the issue is not there anymore. I don’t know what changed, but the fact is that now everything is working 😅
Closing the issue. Thank you.
