### ISSUE TITLE
no "Open" and "Open with" buttons on .zip archives

### ISSUE THREAD

**Issue by nt4f04uNd** [files-community/Files#4259]
**Explain the bug**
as titled

**To reproduce**
right click on .zip file

**Expected behavior**
there should be missing options

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6192947/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6192948/debug_fulltrust.txt)

**System Information**
 - OS Version:  Windows 10 2004 19041.867
 - App version: 1.5.0.0

**Screenshots**
actual

![actual](https://user-images.githubusercontent.com/39104740/112223994-b99d8780-8c3b-11eb-9015-f5d90a5eaf1c.png)

expected

![expected](https://user-images.githubusercontent.com/39104740/112224144-f4072480-8c3b-11eb-8b0f-46863920309c.png)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #6002.
