### ISSUE TITLE
Add Intelligent Adaptive Layout

### ISSUE THREAD

**Issue by d2dyno1** [files-community/Files#4260]
**Is your feature request related to a problem?**
The current logic implementation of Adaptive Layout works fine, but it might not suit all users and their needs. Moreover it isn't that "Adaptive" because it always follows a set of rules that cannot be changed by user. It can be annoying sometimes and force users to disable it completely.

**Describe the solution**
Take the advantage of inbuilt Machine Learning library ML.NET to accelerate the accuracy of predictions. This obviously will be needed to be toggleable so we can also add triple split button accordingly, to.. Disable, Enable, Use AI Acceleration (for Adaptive Layout).

**Comment by d2dyno1** [comment]
@yair100 I'd like to be assigned to this.

**Comment by duke7553** [comment]
@d2dyno1 Can you describe how you'll leverage ML.NET for this one? For instance, which models will you use and how will you train them?

**Comment by d2dyno1** [comment]
@duke7553 The [Recommendation Task](https://docs.microsoft.com/pl-pl/dotnet/machine-learning/tutorials/movie-recommendation#other-recommendation-algorithms) seems like the best choice of all of the [other options](https://docs.microsoft.com/pl-pl/dotnet/machine-learning/tutorials/). I have a [file](https://github.com/files-community/Files/files/6199726/PreferredLayoutData.txt) with inputs we could use to train the model on.. but no data.

**Comment by duke7553** [comment]
@d2dyno1 What inputs would you use to train the model? I don't think this scenario needs ML and a fixed set of rules works fine here. Unless you can describe a case where a fixed set of rules isn't sufficient, I'm still confused about your rationale for using ML here.

**Comment by d2dyno1** [comment]
Closing. Current Adaptive Layout is good enough
