### ISSUE TITLE
Add protocol tags and file types to be able to make it the default in system settings

### ISSUE THREAD

**Issue by MalvadoChefe** [files-community/Files#4261]
I would really like to make this program the default for display, but it does not use the same tags as Windows Explorer.
I'm not sure if I'm being clear, but I'm referring to the "Settings> Applications> Default apps> Choose default apps by protocol // Set defaults by app.
I'm not sure if, making this change, I would be able to use it correctly, but I believe it would work.

Anyway, this is just a comment. Good job, people! :)

**Comment by gave92** [comment]
Thanks for this report. To set Files as default file explorer, you can follow the method explained here: https://files-community.github.io/docs/#/articles/replace-file-explorer
