### ISSUE TITLE
Navigation by Scrolling?

### ISSUE THREAD

**Issue by oOII-J4HN-IIOo** [files-community/Files#4267]
Navigation by Scrolling?

**Is your feature request related to a problem?**
A clear description of what the problem is.
No issue, just a request which I think would really improve the UX.
**Describe the solution**
A clear description of what you want.
Just as with web browsing/navigation with MS Edge, Chrome etc., it would be really nice to have page navigation through scrolling (i.e. scrolling 'back' to the previous page, or 'forwards' to the last visited page), instead of having to click the 'back' and 'forward' arrows like it always has been. This would especially improve the UX with laptop users that use trackpads instead of mice.
**Describe alternatives you've considered**
A clear description of any alternative solutions or features you've considered.

**Additional comment**
Add any other comment or screenshots about the feature request here. What device type/UI layout and app version?

**Comment by Jaiganeshkumaran** [comment]
You mean swiping with a touch screen or a trackpad?

**Comment by oOII-J4HN-IIOo** [comment]
> You mean swiping with a touch screen or a trackpad?

Both, I guess, but I meant trackpads.

**Comment by yaichenbaum** [comment]
Merging with #100.
