### ISSUE TITLE
gridviewitem.ContentTemplateRoot as Grid returns null

### ISSUE THREAD

**Issue by TyJOrtiz** [files-community/Files#4268]
![screenshot](https://user-images.githubusercontent.com/25320332/112264265-dc28a400-8c2d-11eb-95cb-e3f271c5ace3.png)

I don't know if it's a fluke but a suggestion would be to use UWP Toolkit's `FindDescendant<>()`

**Comment by winston-de** [comment]
I noticed this too. @TyJOrtiz If you hover over the ContentTemplateRoot property, it should tell you what type it actually is.

**Comment by TyJOrtiz** [comment]
It says the ContentTemplateRoot is a Border control. Which changing also causes the `FindName("ItemName) as TextBlock` to fail.

As a workaround I would suggest:

`GridViewItem gridViewItem = FileList.ContainerFromItem(item) as GridViewItem;`
`TextBlock textBlock = gridViewItem.FindDescendant("ItemName") as TextBlock;`

**Comment by winston-de** [comment]
@TyJOrtiz Yeah, it was a border control for me too. Thanks for the workaround!

**Comment by TyJOrtiz** [comment]
The weird this is that it wasn't doing this in previous versions but now it's an issue

**Comment by winston-de** [comment]
@TyJOrtiz I'm guessing it has to do with the new WinUI 2.6 styles, which may be adding a border around the list view items to change the look.

**Comment by TyJOrtiz** [comment]
it's also causing issue with `x:Load` for the OneDrive SyncStatusUI glyphs

**Comment by duke7553** [comment]
@winston-de Just doing some cleanup. Was this one fixed?

**Comment by winston-de** [comment]
@duke7553 Yeah, there's a workaround in place now.
