### ISSUE TITLE
Crashing while Using OneDrive Folder

### ISSUE THREAD

**Issue by oOII-J4HN-IIOo** [files-community/Files#4269]
**Explain the bug**
Write a clear description of what the bug is.
Files crashes randomly while using the OneDrive Folder.
**To reproduce**
1. Go to OneDrive Folder
2. Use OneDrive as you would. Copy, cut, paste, move, go forwards/backwards, open files, anything. After a couple of minutes it might crash!

**Expected behavior**
Write a clear description of what you expected.
I expected it not to crash.
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6194873/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6194875/debug.txt)

**Logfile**
Upload the log file here for us to understand your issue better. 
- You can access it from Settings->About->Open log location. 
or 
- Copy the debug.txt and debug_fulltrust.txt from the following directory, and upload the files here.
`%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 

**Screenshots**
Add screenshots to help explain your problem if needed.

**System Information**
 - OS Version: [e.g. Windows 10 20H2 19042.804] (Press WIN + PAUSE/BREAK, use the copy button at the bottom)
 - App version: [e.g. v1.0] (In the app, go to Settings -> About, the version is shown at the top)

**Additional comment**
Add any other comment about the problem here. Does this problem happen again after restarting the app?

**Comment by yaichenbaum** [comment]
@oOII-J4HN-IIOo is this still an issue in Files v2.0?

**Comment by oOII-J4HN-IIOo** [comment]
> @oOII-J4HN-IIOo is this still an issue in Files v2.0?

I don't think so.

**Comment by yaichenbaum** [comment]
@oOII-J4HN-IIOo thanks for the update.
