### ISSUE TITLE
Android MTP Does not show real progress bar

### ISSUE THREAD

**Issue by pc-v2** [files-community/Files#4270]
**Explain the bug**
Write a clear description of what the bug is.
the progress bar does not showing if I copy/cut files/folders from mtp or vice versa

**To reproduce**
1. copy/cut files/folders from mtp and vice versa

**Expected behavior**
Write a clear description of what you expected.

show progress bar 

**Screenshots**

![image](https://user-images.githubusercontent.com/58063311/112273567-1044a900-8cb0-11eb-9464-a1f25b2cd5b1.png)

**System Information**
 - 21H2 19043.899
 - 1.5 Microsoft Store

**Comment by gave92** [comment]
Thanks for this report. Merging with #2543.
