### ISSUE TITLE
ctrl c ctrl v error

### ISSUE THREAD

**Issue by mengxun1437** [files-community/Files#4273]
**Explain the bug**
when i use this plugin,i find that i can not use 'Ctrl + C' and 'Ctrl + V' to copy my files from one place to another,besides using right-click terminal to copy files doesn't work

**Logfile**

[debug.txt](https://github.com/files-community/Files/files/6195586/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6195587/debug_fulltrust.txt)

**System Information**
 - OS Version:
 版本	Windows 10 专业版
版本号	20H2
安装日期	‎2/‎6/‎2021
操作系统内部版本	19042.867
体验	Windows Feature Experience Pack 120.2212.551.0
 - App version: 1.5.0.0

**Comment by yaichenbaum** [comment]
@d2dyno1 Can you check this out?

**Comment by mengxun1437** [comment]
> @d2dyno1 Can you check this out?

**Comment by mengxun1437** [comment]
> @d2dyno1 Can you check this out?

i have reinstalled your product minutes ago but now it still doesn't work

i have searched similar issues just a moment ago,and i found that a lot of people have the same problem like mine(the issues are still opened),so i think maybe it's a common bug.

Perhaps this bug happens from time to time , my roommate use  your product too , but he can cut and paste without error.

If i found something other later, i will report to your team,thank for your patient.

**Comment by d2dyno1** [comment]
Sorry, but I wasn't able to reproduce the issue. Are you still experiencing it? Are these normal fixed drives you're copying from/to? What kind of items are you copying?

**Comment by yaichenbaum** [comment]
@mengxun1437 is this still an issue in Files v2.0?
