### ISSUE TITLE
Layout changes when the display option is pressed twice

### ISSUE THREAD

**Issue by generalguy41** [files-community/Files#4276]
**Explain the bug**
The layout changes when the display option is pressed twice.

**To reproduce**
1. Go to a directory.
2. Change the layout to something different.
3. Click the same layout option again.
4. See that it changes to either Details or Tiles view.

**Expected behavior**
Layout doesn't change

**Logfile**
Nothing of use in log files.

**Screenshots**

https://user-images.githubusercontent.com/8879244/112318521-82eb5f80-8c83-11eb-9926-a3549ae6d4f7.mp4

**System Information**
 - OS Version: 
Edition:	Windows 10 Pro Insider Preview
Version:	Dev
Installed on:	‎2021-‎03-‎17
OS build:	21337.1010
Experience:	Windows 10 Feature Experience Pack 321.5601.0.3

 - App version: v1.5.0.0

**Additional comment**
Seems to either revert back to its previous layout or to whatever the adaptive layout set it as initially.

**Comment by yaichenbaum** [comment]
@generalguy41 This is the expected behavior, by default, Files will automatically select a layout based on the directories content. You can override this by selecting a different layout, but you can also go back to the automatic selection by clicking on the layout option a second time.

**Comment by generalguy41** [comment]
@yair100 Understood. On a separate note, I just noticed that the item count is wrong when switching between the two. Should I open a new ticket for that, or just change this one? May be related to #4251?

**Comment by yaichenbaum** [comment]
@generalguy41 Can you open a new issue? I am not sure that it's related to #4251.

**Comment by generalguy41** [comment]
@yair100 #4281
