### ISSUE TITLE
[Enhancement] Add option to search unindexed items at bottom of search results.

### ISSUE THREAD

**Issue by winston-de** [files-community/Files#4278]
**Is your feature request related to a problem?**
Generally, I only need to search through unindexed items when I didn't find what I was looking for in the indexed results, so it doesn't make sense for me to always enable unindexed search.

**Describe the solution**
I think it would be nice to add an option to show unindexed results at the bottom of the search results.

**Describe alternatives you've considered**
A switch in search results to show unindexed items.

**Additional comment**
![image](https://user-images.githubusercontent.com/59544401/112346268-05275400-8c83-11eb-80f4-bed4bb0abaa0.png)

**Comment by yaichenbaum** [comment]
@winston-de This is a great idea! Would you like to work on this?

**Comment by winston-de** [comment]
@yair100 Sure!
