### ISSUE TITLE
Please Add these features , I will be highly thankful

### ISSUE THREAD

**Issue by YHZ-EPIC** [files-community/Files#4280]
--> Please add this Folder Preview Affect in Files UWP,

![Screenshot 2021-03-24 231729](https://user-images.githubusercontent.com/59396511/112363267-2033ab80-8cf7-11eb-8641-b5f4a335deae.png)

--> Please add an Option to Apply a (Layout Mode) to a folder and all its subfolders and files.
--> Kindly, try to add Advanced utilities in Properties Tab , just like in Windows File Explorer.

**Comment by yaichenbaum** [comment]
@YHZ-EPIC Please open new issues and upvote existing ones for each item here.
