### ISSUE TITLE
Bug: Item count is missing when switching from adaptive to tiles

### ISSUE THREAD

**Issue by generalguy41** [files-community/Files#4281]
**Explain the bug**
Item count not properly displayed when switching between display options.

**To reproduce**
1. Go to a directory.
2. Switch layout options.
5. See that item count is the same as the previous directory that had an adaptive layout set.
4. Switch layout back by pressing the same layout option.
5. See that item count is correct again.

**Expected behavior**
Item counts are properly displayed

**Logfile**
Nothing of use in logs

**Screenshots**

https://user-images.githubusercontent.com/8879244/112382875-c4e7c600-8cc2-11eb-9594-cbc1b5159731.mp4

**System Information**
 - OS Version:
Edition:	Windows 10 Pro Insider Preview
Version:	Dev
Installed on:	‎2021-‎03-‎24
OS build:	21343.1000
Experience:	Windows 10 Feature Experience Pack 321.7401.0.3

 - App version: v1.5.0.0

**Additional comment**
On startup, occasionally when switching display options, there won't be an item count at all.

**To reproduce**
1. Open Files for the first time.
2. Switch layout options.
3. See item count is not displayed.
4. Switch layout back by pressing the same layout option.
5. See that item count is correct again.

**Screenshots**

https://user-images.githubusercontent.com/8879244/112383456-856da980-8cc3-11eb-94ca-4179a8bb4010.mp4

**Comment by generalguy41** [comment]
Still an issue in 2.0.0.0

**Comment by generalguy41** [comment]
Still an issue in 2.0.33.0

**Comment by yaichenbaum** [comment]
@d2dyno1 do you want to work on this?

**Comment by d2dyno1** [comment]
Is it present on the latest version? @yair100

**Comment by yaichenbaum** [comment]
Yes
