### ISSUE TITLE
Crash when i going to C:\Users and other folders

### ISSUE THREAD

**Issue by Kirill-Oleynik-11** [files-community/Files#4282]
**Explain the bug**
Write a clear description of what the bug is.

**To reproduce**
1. Go to '....'
4. See the error

**Expected behavior**
Write a clear description of what you expected.

**Logfile**
Upload the log file here for us to understand your issue better. 
- You can access it from Settings->About->Open log location. 
or 
- Copy the debug.txt and debug_fulltrust.txt from the following directory, and upload the files here.
`%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 

**Screenshots**
Add screenshots to help explain your problem if needed.

**System Information**
 - OS Version: [e.g. Windows 10 20H2 19042.8
[debug.txt](https://github.com/files-community/Files/files/6200787/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6200788/debug_fulltrust.txt)

04] (Press WIN + PAUSE/BREAK, use the copy button at the bottom)
 - App version: [e.g. v1.5] (In the app, go to Settings -> About, the version is shown at the top)

**Additional comment**
Add any other comment about the problem here. Does this problem happen again after restarting the app?
[debug.txt](https://github.com/files-community/Files/files/6200783/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6200784/debug_fulltrust.txt)

**Comment by gave92** [comment]
Thanks for the report:
- Does the issue happen every time on the same folder or is it kind of random?
- Could you try if it works is you disable these two settings (turn off caching) under Experimental? (warning: probably won't change a thing but it's worth trying)

![image](https://user-images.githubusercontent.com/9673091/110851026-ce2f6680-82b0-11eb-8974-599e144ff399.png)

**Comment by SMSourov** [comment]
> Thanks for the report:
> 
> * Does the issue happen every time on the same folder or is it kind of random?
> * Do you get a notification saying "something went wrong" or does the app just close?
> * Could you try if it works is you disable these two settings (turn off caching) under Experimental? (warning: probably won't change a thing but it's worth trying)
> 
> ![image](https://user-images.githubusercontent.com/9673091/110851026-ce2f6680-82b0-11eb-8974-599e144ff399.png)

This also happens with me. The problem appears at random. I applied the setting you told. The application is not crashing anymore.

**Comment by Kirill-Oleynik-11** [comment]
I tried what you said and didn't get any effect. Crashing randomly, in
almost every folder in which there are several files. I don't get a
notification, the application just crashes and that's it.

чт, 25 мар. 2021 г. в 09:56, SMSourov ***@***.***>:

**Comment by emilnymann** [comment]
Probably related to #4304 since both seem to only happen in details view.

**Comment by gave92** [comment]
Indeed, merging with #4304.

**Comment by DeveloperWOW64** [comment]
Also related to #4439, and so all similar duplicates are merging with #4304
