### ISSUE TITLE
1.5 Pin to Start not showing up

### ISSUE THREAD

**Issue by mtratchet16** [files-community/Files#4284]
**Explain the bug**
Just updated to v1.5 and I still don't seem to have the ability to pin folders to the Start.

**To reproduce**
1. Go to a folder.
2. Right Click.
3. No option to pin to Start.

**Expected behavior**
I should be given an option next to "Pin to sidebar" that allows me to pin folders to Start.

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6201143/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6201144/debug_fulltrust.txt)

**Screenshots**
![Screenshot 2021-03-24 200614](https://user-images.githubusercontent.com/59448599/112399339-70514480-8cdc-11eb-96de-bb5bb227f658.jpg)

**System Information**
 - Windows 10 21H1 19043.899
 - Version 1.5.0.0

**Additional comment**
Restarted app and still have the problem. I also noticed that Drives cannot be pinned to Start or the sidebar. Not sure if this is a related bug or something that has not been requested/implemented. Personally, that's more important to me than pinning folders considering I use external hard drives often.

**Comment by XPoppyX** [comment]
Shift + Right Click ?

**Comment by yaichenbaum** [comment]
@mtratchet16 You can find the pin to start option by holding the shift key and right clicking on a directory.

**Comment by mtratchet16** [comment]
> @mtratchet16 You can find the pin to start option by holding the shift key and right clicking on a directory.

Gotcha, I see that now. Why not just have it under right-click?

**Comment by yaichenbaum** [comment]
@mtratchet16 This isn't an option people use every day, and it would make the menu even bigger.

**Comment by ntelas** [comment]
But pinning *.exe files to start doesn't seem possible even with shift + right click. Correct me if I'm wrong. This is a must for me that I have all my apps in folders on the start menu.

**Comment by yaichenbaum** [comment]
@ntelas I think it's only for folders right now, can you open a new feature request for supporting files?
