### ISSUE TITLE
Files acts more like Mac Finder and NOT Windows Explorer

### ISSUE THREAD

**Issue by cyberczar** [files-community/Files#4285]
**Files acts more like Mac Finder than Windows Explorer and This Is a Bad Thing™**

There needs to be a HUGE warning within the app for users that expect Files to act like Windows Explorer because Files most certainly does NOT act like Windows Explorer when it comes to file copy operations. It acts more like Mac OS Finder.

In Explorer, it is a common task to cut/ copy a folder and paste it into a new location.

If that folder already exists in the destination, Windows Explorer will simply *merge* the contents of the two folders.

Granted, Files does prompt you that you already have a destination folder that already exists and asks you if you want to replace any files **but this is incredibly misleading**.

Because Files is asking you if you want to completely replace the contents of the destination directory, but the logical assumption (because you're on a Windows box and *not* on a Mac) is that Files is actually asking you if you want to overwrite any destination files that may already exist.

Files either needs to be modified to *merge* the contents of the files, or be explicit and ask the user what they want to do.

Something like:
> The destination folder already exists. Do you want Files to either:
> [ ] Merge the contents
> [ ] Replace the contents

Seeing as I'm now restoring a backup, I can only wonder how many other users are being bit by this.

**To reproduce**
1. Go to 'Copy a folder that already exists in your %user_proflie%'
2. Click on 'Paste the folder into another location.'
3. Have Files replace the contents of the destination with the contents of the source instead of merging the folder contents like what is the normal and expected behavior under Microsoft Windows.

**Expected behavior**
A replacement or alternative for Windows Explorer should behave like Windows Explorer, and Windows Explorer merges the contents of folders whose source and destination are the same.

Files is behaving more like Mac OS Finder that replaces the contents of a destination folder if it is the same as the source folder during file copy or move operations.

**Comment by yaichenbaum** [comment]
@cyberczar This is a known bug and we are working on resolving it #3958.
