### ISSUE TITLE
Change Folder Icons

### ISSUE THREAD

**Issue by mtratchet16** [files-community/Files#4286]
**Is your feature request related to a problem?**
Preference more so than problem.

**Describe the solution**
An option to change folder icons similarly to the same option in the Windows 10 default File Explorer.

**Describe alternatives you've considered**
N/A

**Additional comment**
This is especially helpful when having folders pinned to Start. It allows for quick and easy discernment between tiles.

**Comment by mdtauk** [comment]
Would be good to create an icon pack format (zip with JSON perhaps) which allows swapping out a known set of icons, or individually assigned icons for folders

**Comment by yaichenbaum** [comment]
Merging with #1015.
