### ISSUE TITLE
Right click > open terminal doesn't work

### ISSUE THREAD

**Issue by kimlimjustin** [files-community/Files#4287]
**Explain the bug**
Right-click > open terminal doesn't work 

**To reproduce**
1 .Open Files
2. Right-click inside a folder
3. Click "Open in Terminal"
4. Terminal won't open 

**Expected behavior**
Open in Terminal work

**Logfile**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6201546/debug_fulltrust.txt)

**System Information**
 - OS Version: Microsoft Windows 10 Home Single Language 10.0.18363 N/A Build 18363
 - App version: 1.5.0.0

**Comment by gave92** [comment]
Thanks for this report. From the log file I'd expect that #3855 is not solved for you either, could you share a screenshot of the context menu?
Anyway please try to reboot your PC, and see if this issue gets fixed.

**Comment by kimlimjustin** [comment]
Right-clicking works fine for me since version 1.5 released (with little latency tho, but it's ok), but open in terminal doesn't work. Here's screen record:

https://user-images.githubusercontent.com/61906684/112429544-62003880-8d6f-11eb-89b5-9951b52f904b.mp4

NB: I just update to version 1.5 this morning, and I never clear the log yet.

**Comment by SMSourov** [comment]
Can you go to Settings > Preferences and check Terminal applications. It is working for me. I've check CMD, PowerShell and Windows Terminal. All of them are working.

**Comment by kimlimjustin** [comment]
> Can you go to Settings > Preferences and check Terminal applications. It is working for me. I've check CMD, PowerShell and Windows Terminal. All of them are working.

I tried them all, nothing works...

**Comment by gave92** [comment]
@kimlimjustin that is _not_ a working context menu :) it should show all elements from windows explorer.

**Comment by kimlimjustin** [comment]
> @kimlimjustin that is _not_ a working context menu :) it should show all elements from windows explorer.
> 
> If you haven't already, do you mind trying a system reboot? From the log file it looks like it may fix both issues.

Eh, I"m sorry I just realize that the context menu when right-clicking in FIles and File Explorer is different. For the system reboot, I am not very convenient at the moment because I got a lot of school projects (I'm still a student xd), but I'll try to reinstall Files.

**Comment by kimlimjustin** [comment]
I reinstall it but still doesn't work.

**Comment by gave92** [comment]
I'll keep hoping a reboot will fix it (from the log it looks like a system issue). When you have time to try that let me know how it goes.

**Comment by LKMMKL** [comment]
I aso found this question!! my os version is 1909 18363.1256

**Comment by c1oser** [comment]
me too, it's really annoying

**Comment by PranavSakthivel** [comment]
I have the same issue, Windows 1909
