### ISSUE TITLE
Folders are not showing at top

### ISSUE THREAD

**Issue by SMSourov** [files-community/Files#4291]
**Explain the bug**
The folders are not showing at top.

**To reproduce**
1. Browse any path that has multiple files and folder.
2. Sort everything in an ascending order by name.

**Expected behavior**
The folders should be at top.

**Logfile**
I don't think log file is needed.

**Screenshots**
Add screenshots to help explain your problem if needed.
![Screenshot 2021-03-25 123853](https://user-images.githubusercontent.com/81343486/112429823-6d4f6600-8d67-11eb-9971-61c685295f12.png)

**System Information**
 - Latest stable version of Windows 10 including all updates.
 - App version : 1.5.0.0

**Additional comment**
Add any other comment about the problem here. Does this problem happen again after restarting the app?

**Comment by gave92** [comment]
Thanks for this report. There's an option in Files settings to turn this on or off, "Sort folders together with files" or similar.

**Comment by SMSourov** [comment]
Thanks.
