### ISSUE TITLE
No warnings.

### ISSUE THREAD

**Issue by SMSourov** [files-community/Files#4294]
**Explain the bug**
If/when a task cannot be done, it doesn't show any warning/error.

There are several ways to reproduce the bug.
1. Copy file.
2. Go to C:/Program files/Windows Mail
(I'm using this directory since there is a high chance that this directory will be in your PC.)
(Any other random folder should also reproduce the problem.)
3. Now paste that file.

**Expected behavior**
The task will not complete at the first place or fail to do the task and it will show a error/warning. 

**Logfile**
- Copy the debug.txt and debug_fulltrust.txt from the following directory, and upload the files here.
[debug.txt](https://github.com/files-community/Files/files/6204059/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6204061/debug_fulltrust.txt)

**Screenshots**
No screenshots needed.

**System Information**
 - OS Version: [e.g. Windows 10 20H2 19042.804]
 - App version: 1.5.0.0

**Comment by yaichenbaum** [comment]
This issue will be solved together with #2513.
