### ISSUE TITLE
Add Support For folder.jpg When Showing Directories as Icons

### ISSUE THREAD

**Issue by torstees** [files-community/Files#4297]
**Is your feature request related to a problem?**
This is a cosmetic fix but does allow user to customize what they see to be more productive and is currently supported by Windows File Explorer

**Describe the solution**
In windows explorer, directories that contain an image file named folder.jpg, the image is integrated into the thumbnail preview. Windows overlays this ontop of a folder icon, but apple just replaces the icon with the thumbnail itself. Honestly, I'd prefer to let the user determine what the see (i.e. not overlay the image ontop of the folder icon), but it's not hugely important which approach is used.

**Describe alternatives you've considered**
I'm not sure this has an alternative

**Additional comment**
I'm on a desktop computer and use this feature with windows' explorer to help me more quickly find the directory I'm looking for when I have directories with a lot of contents.

**Comment by yaichenbaum** [comment]
Merging with #99.
