### ISSUE TITLE
Folder content preview

### ISSUE THREAD

**Issue by winston-de** [files-community/Files#4301]
In the latest insider builds, thumbnails of folders no longer contain a preview of the contents of the folder, and has been replaced with a standard icon. 

Possible alternatives:
- OneDrive style, where the first item is shown 
![image](https://user-images.githubusercontent.com/59544401/112505921-7bdb5480-8d4a-11eb-94d2-4f5992a38fd4.png)
- Slideshow of item thumbnails
- Contents in a GridView
- Remake the classic explorer one (with more fluent)
![image](https://user-images.githubusercontent.com/59544401/112506265-cf4da280-8d4a-11eb-911b-71673dbd3b24.png)

**Comment by d2dyno1** [comment]
Could this be toggleable because it doesn't look good for me. Also if we're planning to implement such feature, wouldn't it be nice if it instead showed the contents on mouse hover? It'd bump the performance.

**Comment by winston-de** [comment]
@d2dyno1 This isn't a new feature. However, the API (StorageFile thumbnails) it depends on has changed in the latest dev builds and no longer shows a preview of the folder contents and instead just shows a folder icon. This issue is about possibly replacing it. 

This is what it looked like before the latest dev build:
![image](https://user-images.githubusercontent.com/59544401/112531501-e1d4d580-8d64-11eb-95e1-4c4f1076ff52.png)

With the latest dev build:
![image](https://user-images.githubusercontent.com/59544401/112531673-121c7400-8d65-11eb-83cc-e0e20658ac9d.png)

**Comment by mistic100** [comment]
+1 for this, the current state is the step back from the standard explorer when navigating into galleries

also linked to #3326 which is a very handy feature for music albums

**Comment by TizianoMad** [comment]
This [portable app](https://github.com/hahagu/WindowsThumbnailGenerator/releases) makes them look a bit better.

**Comment by yaichenbaum** [comment]
This is a great idea, let's wait to see what Microsoft does in this area in order to prevent duplicate work.

**Comment by yaichenbaum** [comment]
This issue was resolved in Windows 11 22557.1.
![image](https://user-images.githubusercontent.com/39923744/154330256-09cccc65-ea50-4afe-aaf8-2df2dff69555.png)
