### ISSUE TITLE
Crash when accessing AppData/LocalLow and sub-directories

### ISSUE THREAD

**Issue by emilnymann** [files-community/Files#4304]
**Explain the bug**
Write a clear description of what the bug is.

**To reproduce**
1. Replace Explorer with Files using the registry files from the documentation.
2. Navigate to C:/Users/username/AppData/ (sometimes it crashes already here.)
3. Navigate to LocalLow and keep navigating through sub-directories.
4. At some point the loading bar will appear for a few seconds and then the app crashes with no error.

**Expected behavior**
Being able to navigate to AppData and subdirectories

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6206873/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6206874/debug_fulltrust.txt)

**System Information**
 - OS Version: 
Udgave	Windows 10 Home
Version	20H2
Installeret d.	‎18-‎03-‎2021
Operativsystemets build	19042.868
Visning	Windows Feature Experience Pack 120.2212.551.0

 - App version:
Version 1.5.0.0

**Additional comment**
It seems random whether it just crashes in AppData or a sub-directory, and other sub-directories of AppData than LocalLow don't seem to cause any issues.

**Comment by emilnymann** [comment]
I realised there might be some irrelevant errors from earlier in those logs, so I deleted them and reproduced the crash again. Here are the new logs, which don't seem to reflect the crash at all.

[debug.txt](https://github.com/files-community/Files/files/6206923/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6206925/debug_fulltrust.txt)

**Comment by gave92** [comment]
Thanks for the report:

- Do you get a notification saying "something went wrong" or does the app just close?
- Could you try if it works is you disable these two settings (turn off caching) under Experimental? (warning: probably won't change a thing but it's worth trying)

![image](https://user-images.githubusercontent.com/9673091/110851026-ce2f6680-82b0-11eb-8974-599e144ff399.png)

**Comment by emilnymann** [comment]
The app just closes with notification.

I had already disabled caching, since I'm not even able to access my user files with it enabled (#4282)

**Comment by gave92** [comment]
@emilnymann What about the following? (I'd like to know if this only happens in details view)
1. Turn Off "Enable individual preferences for individual directories" in Settings > Files and Folders
2. Set Tiles or GridView layout mode
3. Try to trigger the crash

**Comment by emilnymann** [comment]
> * Turn Off "Enable individual preferences for individual directories" in Settings > Files and Folders
> * Set Tiles or GridView layout mode

Followed these two steps and browsed around in various directories for 5 minutes, including AppData and its subdirectories, and was not able to trigger a crash. After changing to detail view, the crash did still not occur. After changing to detail view, closing Files, opening it again and browsing to `AppData/LocalLow` a crash occured again. I had caching disabled the whole time.

Reproduced the above results several times.

**Comment by DeveloperWOW64** [comment]
Can you try replacing explorer with Files and seeing if that works? (I don't exactly know how the Registry works, so tell me if that's wrong)

**Comment by emilnymann** [comment]
> Can you try replacing explorer with Files and seeing if that works? (I don't exactly know how the Registry works, so tell me if that's wrong)

Other than the aforementioned registry tweaks, I don't know of any other way of replacing Explorer with Files. It doesn't appear to be an actual neccesary step to trigger this crash, but I included it in my steps when I first wrote the issue in case it was.

**Comment by DeveloperWOW64** [comment]
> 3. Navigate to LocalLow and keep navigating through sub-directories.

It could be that you are attempting to go beneath the character limit for directories, and (I don't know, but I think) Files doesn't have access to go beneath the character limit.

**Comment by emilnymann** [comment]
> It could be that you are attempting to go beneath the character limit for directories, and (I don't know, but I think) Files doesn't have access to go beneath the character limit.

The crash has been confirmed to be related to details view, as it never occurs in tile/grid view, so I don't think that's directly related.

**Comment by DeveloperWOW64** [comment]
ok

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
