### ISSUE TITLE
There is no "Microsoft" folder

### ISSUE THREAD

**Issue by Archeol** [files-community/Files#4305]
**Explain the bug**
There is no path to the "Microsoft" folder

**To reproduce**
1. Go to "AppData" (then "Roaming") or "ProgramData"
2. Scroll down to folders that start with "M"
3. No "Microsoft", just "Microsoft Teams"

**Expected behavior**
To see the "Microsoft" folder

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6206901/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6206903/debug_fulltrust.txt)

**Screenshots**
![Screenshot 2021-03-25 140819](https://user-images.githubusercontent.com/46249833/112522063-94ac3000-8d73-11eb-8c57-c35a5edbdab2.png)

**System Information**
 - OS Version:
Edition	Windows 10 Pro
Version	20H2
Installed on	‎8/‎26/‎2020
OS build	19042.867
Experience	Windows Feature Experience Pack 120.2212.551.0

 - App version: 
Version 1.5.0.0

**Additional comment**
I appear to no longer be able to open Roaming using Files in the middle of writing this report (just after copying the debug files to here)

**Comment by gave92** [comment]
If you manage to solve the other issue, could you try if the folder shows up if you enable "show hidden files" (even if the folder is not hidden) and disable "hidden system files and folders"?

**Comment by Archeol** [comment]
Ah, yup, that appears to have done it (disabling hide system files; I already had show hidden files on), thanks. I now also see a bunch of other folders that didn't show with File Explorer.

**Comment by gave92** [comment]
Thanks for confirming @Archeol 👍
