### ISSUE TITLE
Homepage and License links to QuickLook

### ISSUE THREAD

**Issue by d-Rickyy-b** [files-community/Files#4309]
Hey there,

the "Homepage" and "License" links on the settings page link to QuickLook.

https://github.com/files-community/Files/blob/f7ce0ce12947886a3c281145ba14ffdece40c63c/Files/Views/SettingsPages/About.xaml#L215-L225

**Comment by yaichenbaum** [comment]
@d-Rickyy-b We're having a little trouble understanding this issue, can you add more details about the issue you're having?

**Comment by d-Rickyy-b** [comment]
Hi @yair100 - I am very sorry. I totally missed that the links at the bottom of the about page are actually related to the QuickLook project. I just expected to find a link to the "Files" homepage. My bad!

It's just now that I saw that there's actually "QuickLook" prepended to it.

![grafik](https://user-images.githubusercontent.com/5798157/112559195-bdaede00-8dd0-11eb-9e3b-9f761e7cac3f.png)

**Comment by yaichenbaum** [comment]
@d-Rickyy-b Thanks for the update!
