### ISSUE TITLE
Allow an editable Display Name for pinned/favorite items

### ISSUE THREAD

**Issue by phaselden** [files-community/Files#4311]
**Is your feature request related to a problem?**
The problem is I have folders that I want to pin but they have the same name so it is difficult to distinguish them in the Favorites list. For example, the "Source" folder for different development projects.

**Describe the solution**
Once I have pinned a folder, or while I am pinning it, I would like to have the option to specify a display name for the pinned item. eg "Project 1 Source"

**Describe alternatives you've considered**
Can't think of a suitable alternative

**Additional comment**
 * It would be nice if the terminology was consistent. eg either pinned or favorites. 
 * I couldn't see a way to pin a folder while displaying the contents of the folder. It seems I have to navigate to the parent folder and then right-click on the sub-folder's name to pin it. Maybe I am missing something. 

(Very nice app BTW!)

**Comment by yaichenbaum** [comment]
Merging with #3422.

**Comment by yaichenbaum** [comment]
> It would be nice if the terminology was consistent. eg either pinned or favorites.

The terminology makes sense in terms that you are pinning an item to the favorites section.

> I couldn't see a way to pin a folder while displaying the contents of the folder. It seems I have to navigate to the parent folder and then right-click on the sub-folder's name to pin it. Maybe I am missing something.

There should be an option to pin a directory to the sidebar when right clicking on a blank space.

**Comment by phaselden** [comment]
> > It would be nice if the terminology was consistent. eg either pinned or favorites.
> 
> The terminology makes sense in terms that you are pinning an item to the favorites section.
Hmm - yeah I guess that is true, but perhaps "Add to Favorites" rather than "Pin to sidebar" might be slightly clearer?

> 
> > I couldn't see a way to pin a folder while displaying the contents of the folder. It seems I have to navigate to the parent folder and then right-click on the sub-folder's name to pin it. Maybe I am missing something.
> 
> There should be an option to pin a directory to the sidebar when right clicking on a blank space.
Couldn't get it to work in the sidebar, but I see it can be done using a right-click to the side of or below the directory contents (not the sidebar)

**Comment by yaichenbaum** [comment]
> Hmm - yeah I guess that is true, but perhaps "Add to Favorites" rather than "Pin to sidebar" might be slightly clearer?

That might be possible, can you open a new issue to track this?
