### ISSUE TITLE
Copy and Pasting with RDP

### ISSUE THREAD

**Issue by phaselden** [files-community/Files#4312]
**Is your feature request related to a problem?**
I work a lot with RDP sessions. My RDP app of choice at the moment is mRemoteNG. If I right-click copy files from the Files app on my host machine, and then try to paste them into a remote (Windows Explorer) folder, it does not work. 

**Describe the solution**
I want it to work like copying from and to Windows Explorer works. 

Thanks

**Comment by gave92** [comment]
@phaselden funny question: could you try if you can copy/paste a file to remote PC it it's a hidden file?

**Comment by Shamatix** [comment]
> @phaselden funny question: could you try if you can copy/paste a file to remote PC if it's a hidden file?

I can copy both normal and hidden files FROM files 2.0 to the RDP, but I cannot copy a single file from the RDP TO Files 2.0

**Comment by gave92** [comment]
Should be fixed on main (#6387?)
