### ISSUE TITLE
Global setting to enable desired layout mode for all folders

### ISSUE THREAD

**Issue by Jmoney1536** [files-community/Files#4314]
So, not a bug, but an annoyance that if you want to change the layout mode setting of all your folders (from a list view to a grid view) you have to do this for every folder individually, as you open them.  Sometimes, the nested folders will also take the chosen setting, but not always.  I have looked everywhere, but there isn't a global setting to set a default layout mode (Unless the "Layout Mode" option under the "Display Options" is meant to be sticky; if so, this may be a bug) format for ALL folders and this would be very helpful.  

![layout](https://user-images.githubusercontent.com/81399693/112570340-d8bf2500-8db3-11eb-82d9-0135864ae037.jpg)

**Comment by gave92** [comment]
You should be able to:

1. Turn Off "Enable individual preferences for individual directories" in Settings > Files and Folders
2. Go to any folder and set your desired layout mode
3. Optional: Turn "Enable individual preferences for individual directories" back on

The selected layout at step 2 will be the default.

**Comment by jjmonteiro** [comment]
what about the 'list' view? the one without details, its my default in explorer and seems to be missing from the provided views.

**Comment by TailyFair** [comment]
I believe default layout mode should option in settings.
