### ISSUE TITLE
App Crashes After Deleting Multiple Files

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#4316]
**Explain the bug**
`Files` app will crash or close unexpectedly after performing delete action (Delete Permanently **Multiple Files**) while I am using 3 `Files'` tabs. `Files` app won't crash on the first delete action, but after several times, it crashes / closed unexpectedly (and it occurs around 4 times in the past half hour)

**Expected behavior**
`Files` doesn't crash or close unexpectedly

**Logfile**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6209303/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6209304/debug.txt)

**System Information**
 - OS Version: Windows 10 Home Single Language 20H2 19042.870
 - App version: v1.5.0.0

**Comment by duke7553** [comment]
@gave92 This stack trace is similar to #4330

**Comment by yaichenbaum** [comment]
@stanleyowen is this still an issue?

**Comment by stanleyowen** [comment]
Hi @yair100,

I think now Files are now getting more stable from day to day 🚀. I enjoyed it really much! This issue is no longer occurred on the latest build release 👍.
