### ISSUE TITLE
Change wording to "Pin to Favorites"

### ISSUE THREAD

**Issue by phaselden** [files-community/Files#4317]
Suggestion: change the terminology slightly to more closely relate "Favorites" to pinning. 

At present the commands to pin are (depending on what right-click menu is used):
* "Pin to sidebar"
* "Pin directory to sidebar"

Suggested alternative:
* "Pin to Favorites"

Note that Favorities is capitalised as its the name of part of the UI. 

**Describe alternatives you've considered**
Also considered "Add to Favorites", but Windows Explorer uses the term "Pin" so I went with that.

**Additional comment**
Windows Explorer calls the area "Quick access" which is an OK alternative name. One advantage of that term is that it avoids the 2 spellings of "favorites" and "favourites", but that is not a big issue.

**Comment by yaichenbaum** [comment]
`Pin to Favorites` sounds good.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5370.
