### ISSUE TITLE
Files Crashes when Use High Contrast [System] is enabled

### ISSUE THREAD

**Issue by chriscross12324** [files-community/Files#4319]
**Explain the bug**
When trying to use 'Files' while High Contrast mode is enabled results in a force quit/crash

**To reproduce**
1. Open Windows' Settings
2. Navigate 'Ease of Access' > 'High Contrast' > Enable 'Use high contrast'
3. Open 'Files' app
4. 'Files' crashes

**Expected behavior**
Conforms to Windows' High Contrast standards, doesn't crash

**Logfile**
[Attached]

**System Information**
 - OS Version: Windows 10 20H2 19042.870
 - App version: 1.5.0.0

**Additional comment**
No way to open app, Logfile attached was reset and then crash reproduced before uploading... just to save you some looking through for the cause

**Comment by yaichenbaum** [comment]
@chriscross12324 This issue should be resolved with #4969.
