### ISSUE TITLE
On Going Tasks Icon feels like something is frozen.

### ISSUE THREAD

**Issue by mertbakir** [files-community/Files#4324]
**Is your feature request related to a problem?**

"On going tasks" icon looks like something is stuck and frozen. It may not be crucial but I think it's a bad icon choice. 

**Describe the solution**
- Use a different icon, that indicates a queue or something else.
- Alternatively, hide the icon if there are "on going tasks"

**Additional comment**

![image](https://user-images.githubusercontent.com/43188411/112720479-aaeef300-8f0f-11eb-8d50-6992c75b7cfc.png)

**Comment by mdtauk** [comment]
You could have an icon swap out for a ProgressRing when there are tasks going on

**Comment by gave92** [comment]
Latest code makes the icon "spin" when the are ongoing tasks

**Comment by emilnymann** [comment]
I agree that the static icon indicating no ongoing tasks should be changed. Users implicitly expect movement from a spinner icon, and so it indeed does indicate that something is stuck or frozen when it does not move. Perhaps `ic_fluent_task_list` would work better, especially in the larger context of Fluent. https://github.com/microsoft/fluentui-system-icons/blob/master/icons.md

As a side note, I think the iOS Fluent spinner (`ic_fluent_spinner_ios`) would look better, even though the current spinner doesn't pose any implicit UX issues.

**Comment by voiiden** [comment]
How about something like `textBulletListLtr20Regular`? It looks like this: 
![image](https://user-images.githubusercontent.com/31285047/115153520-b6e55500-a076-11eb-994a-6e6cb38e9fa7.png)

**Comment by yaichenbaum** [comment]
@XPoppyX Do you have any ideas for a new icon we can use?

**Comment by XPoppyX** [comment]
These are the icons that I found in mdl2 assets, which are related to operations and tasks

![e9f5](https://user-images.githubusercontent.com/61259627/115159942-bbecd900-a063-11eb-94aa-5cd44aa32f56.png) ![eadf](https://user-images.githubusercontent.com/61259627/115159946-bd1e0600-a063-11eb-8bc4-61b8a6167d08.png) ![eb91](https://user-images.githubusercontent.com/61259627/115159947-bd1e0600-a063-11eb-8983-e10388b1f226.png) ![ee40](https://user-images.githubusercontent.com/61259627/115159948-bdb69c80-a063-11eb-9939-fc71f2beb9cb.png)

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
