### ISSUE TITLE
Shortcut for search button

### ISSUE THREAD

**Issue by mertbakir** [files-community/Files#4326]
**Is your feature request related to a problem?**

- I would like to use the search directly using the keyboard.
- I would like to type the path myself without using the mouse.

**Describe the solution**

We need 2 shortcuts. One for focusing on the "path bar" (idk if that's its name) and the other one is to activate search button.

- CTRL + F should work for the search.
- Alt + F (? even better, make it configurable in the settings) for focusing to the path bar.

**Describe alternatives you've considered**

Alternatively or additionally, you can make the app focus on the "path bar" when we open a new tab. This is how most browsers behave. We open a new tab using CTRL+T and the focus is on the search bar.

**Comment by gave92** [comment]
Ctrl+L or Alt+D already focus the path bar. Ctrl+F for search is being implemented in #3558

**Comment by mertbakir** [comment]
@gave92 Oh, thanks CTRL+L does focus. I searched for it but couldn't find. I think this should be added into the docs.

**Comment by gave92** [comment]
> I think this should be added into the docs.

@mertbakir having a page in Settings to view (or even customize) keyboard shortcuts it's something that's planned 👍

Ctrl+L was chosen as it's the one commonly used in Windows Explorer and browsers but I think that some shortcuts are locale-dependant.. what do you use in windows explorer to focus the path bar?

**Comment by mertbakir** [comment]
Well, I don't use anything to focus the path-bar in Windows Explorer. It might be my ignorance to not know CTRL+L, lol. 
I'm usually using a terminal, or Power Toys' Run feature if I'm gonna write the path. Now, I can use CTRL+L.
