### ISSUE TITLE
Remove Cloud Drives On The Sidebar

### ISSUE THREAD

**Issue by mertbakir** [files-community/Files#4327]
**Is your feature request related to a problem?**

I would like to be able to configure showing/hiding "cloud drives" on the sidebar. Because, it becomes useless when there are no cloud drives.

**Describe the solution**

Add a toggle in the Settings>Preferences. "Show cloud drives on the sidebar."

**Comment by gave92** [comment]
Agreed, at least it should be hidden automatically if there are no cloud drives.

**Comment by XPoppyX** [comment]
#3912
