### ISSUE TITLE
Move buttons on top to the status bar

### ISSUE THREAD

**Issue by mertbakir** [files-community/Files#4328]
**Is your feature request related to a problem?**

In my opinion, buttons on the top right corner (below the path and search bar) are taking up space unnecessarily.

![image](https://user-images.githubusercontent.com/43188411/112722065-6582f380-8f18-11eb-80f7-a75832e4aac6.png)

**Describe the solution**

I suggest to move them to the bottom right corner, just before or after the "ongoing tasks" button, in the same line with the status bar.

![image](https://user-images.githubusercontent.com/43188411/112722152-cf030200-8f18-11eb-839f-6cf8e86a553f.png)

**Comment by gave92** [comment]
#2922 #4049

**Comment by CF-71** [comment]
My suggestion would also be to move the option-buttons (selection, display, panel, three-point menu) **and** the information "items / items select / tasks" into **ONE** line. This line then still has enough space for further buttons. 

Whether this line/bar is then positioned, at the bottom or at the top, is certainly a matter of taste. 

I think it's a waste of space to use two lines for so little information / buttons. 
The second line would then be superfluous and the space could be better used for the display of folders and files (less scrolling).
