### ISSUE TITLE
Unknown error.

### ISSUE THREAD

**Issue by SMSourov** [files-community/Files#4330]
**Explain the bug**
I created 2 window of files, both of them had two different folders opened. I was moving few files from one folder to another folder.

**To reproduce**
1. I didn't try to reproduce it.

**Expected behavior**
The task should be done normally.

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6215820/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6215821/debug_fulltrust.txt)

**Screenshots**
![SharedScreenshot](https://user-images.githubusercontent.com/81343486/112723883-e3f08d00-8f3a-11eb-9027-a8701787f69c.jpg)

**System Information**
 - OS Version: [e.g. Windows 10 20H2 19042.804]
 - App version: 1.5.0.0

**Comment by lukeblevins** [comment]
@yair100 We can probably mark this one as resolved since all the reliability improvements to file transfer operations are in testing with v2, right?
