### ISSUE TITLE
Drives blue sidebar missing on Files Startup

### ISSUE THREAD

**Issue by DashCruft** [files-community/Files#4332]
**Explain the bug**
Simply, other then main drive of windows which is C, other drives blue sidebar is missing while opening the app for the first time.

**To reproduce**
1. Open Files
2. As shown, the blue sidebar is missing
3. But when you click on Home button, its fixed.

**Expected behavior**
Suppose to show the blue sidebar for every single drive while opening.

**Logfiles**
[debug.txt](https://github.com/files-community/Files/files/6216289/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6216290/debug_fulltrust.txt)

**Screenshots**
https://youtu.be/lOocSO-nNRQ

**System Information**
 - OS Version: Windows 10 20H2 19042.870
 - App version: v1.5.2
 
**Additional comment**
Does this problem happen again after restarting the app?
`Yes. This problem constantly keeps happening to me`

**Comment by gave92** [comment]
Thanks for this report. Merging with #3701
