### ISSUE TITLE
Add ability to drag folder to the taskbar to pin the item

### ISSUE THREAD

**Issue by timsu92** [files-community/Files#4338]
**Is your feature request related to a problem?**
This relates to #3311 . However, that issue wants a automatic one, but I think a manual one is also great!

**Describe the solution**
Pin files or folders to Windows Taskbar by either these ways:
- drag and drop. This action currently pins to their defaults. e.g. folders to explore.exe, videos to VLC.
- an item in right-click context menu

After pinned, it looks like this:
![image](https://user-images.githubusercontent.com/33785401/112743513-9459a200-8fca-11eb-819e-d54caaec1e04.png)

**Describe alternatives you've considered**
- Currently, Files allows me to open it, wait for the splash, and then click the shortcut either on the sidebar or bundle, which isn't really handy.
- Wait for the item to appear in "recent" in the right-click menu of the Taskbar icon, and then pin it. Nevertheless, I can't figure out when the items will appear(#4337)

**Additional comment**
- App version: v1.5.0.0
- This is a laptop PC, not in tablet mode.
![image](https://user-images.githubusercontent.com/33785401/112744028-f74d3800-8fce-11eb-9937-f9557eace93e.png)

**Comment by yaichenbaum** [comment]
Merging with #10171
