### ISSUE TITLE
Remove the cluster under search bar !!!

### ISSUE THREAD

**Issue by Blendinl** [files-community/Files#4340]
**Move the "Selection Options", "Display Options", "Toggle the preview pane" & "More options" onto the bottom of the application, next to "Ongoing  Tasks"**
It looks way cleaner :))

**Comment by gave92** [comment]
Thanks for this suggestion, buttons were at the bottom till Files 1.3 :)
The plan is to add more elements to the top bar (#4049 / #2922).
If you have any though on this change feel free to comment on #2922
