### ISSUE TITLE
Feature Request: Add "do this for all items" when moving files

### ISSUE THREAD

**Issue by Njsmooth** [files-community/Files#4341]
**Is your feature request related to a problem?**
Yes. When I moved items from one folder to another, multiple files having the same name, I had to individually tell the program to replace each one.

**Describe the solution**
Add a "do this for all items" option when working with multiple files in such a way.

**Describe alternatives you've considered**
Temporarily using the basked in file browser for file transfers.

**Additional comment**
Windows 10, I apologize if the option does exist and I glossed over it.

**Comment by gave92** [comment]
Merging with #3985.
