### ISSUE TITLE
Deprioritize folders on directory

### ISSUE THREAD

**Issue by dreaddr** [files-community/Files#4342]
**Is your feature request related to a problem?**
When I use this app, I often visit the downloads folder, and sort it by time, so that the latest files show on top. However, as folders are given more credence than files, folders that are unnecessary to productivity show up on top of the directory.

**Describe the solution**
A toggle to deprioritize folders over files in the Downloads directory at the very least, so that files that have been recently downloaded can be given more credence.

**Describe alternatives you've considered**
Switching and using default explorers downloads folder, as its easier to access that from the start menu quick access buttons. 

**Additional comment**
I assume this would be a simple feature on the surface that can be complex on the back end, hope it gets implemented though.

**Comment by gave92** [comment]
If you look in Files settings you'll find an option that says "Sort folders together with files" which should do what you describe 👍

**Comment by dreaddr** [comment]
> If you look in Files settings you'll find an option that says "Sort folders together with files" which should do what you describe 👍

Oh great, its already there. Kind of a bummer its not exactly descriptive but yeah, no need of this issue now.
