### ISSUE TITLE
Crash when opening a folder beyond 255 path character limit.

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#4343]
**Expected behaviour**
It should give an in app error saying that the path character limited has been reached.

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6217640/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6217641/debug_fulltrust.txt)

**System Information**
 - OS Version: Windows 10 20H2 19042.870
 - App version: 1.5.2.0

**Comment by gave92** [comment]
Regression after #3716?

**Comment by Jaiganeshkumaran** [comment]
Windows 10 Anniversary Update and later provides a way to disable max path limitations which allows you to work with larger paths. Could you enable that?

**Comment by josh-65** [comment]
That works for me but it should say that the path limit is too small as an error instead of crashing and provide guidance on how to fix it on the wiki. Better yet when the error message does show up provide a button that will increases it to max.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5237.
