### ISSUE TITLE
Rename pinned folders in sidebar

### ISSUE THREAD

**Issue by nando1988** [files-community/Files#4344]
I have just installed files on windows 10, and I love it, but there is something that I would love to see and its the option to rename the pinned folders in the sidebar only. I have a set of folders inside other folders, and I want to pin the last folder, but with the name of its parent, and right now, I think that the only way to do this, is by renaming the folder and the pin it.
Can you please add this feature, it is available in clover, but I like your explorer a lot more, since its more modern.
Thanks for your help.

**Comment by yaichenbaum** [comment]
Merging with #3422
