### ISSUE TITLE
Add "Open Files here..." shell context menu integration

### ISSUE THREAD

**Issue by d2dyno1** [files-community/Files#4345]
**Describe the solution**
Add a switch in settings that adds (and removes) shell context menu item "Open Files here..." that opens Files in current directory. It's meant for Windows File Explorer, hide it for Files.

**Describe alternatives you've considered**
Can't think of any

**Additional comment**
RX Explorer already injects its menu item into the shell context menu but there isn't a way to disable it (?)

**Comment by winston-de** [comment]
I believe this already exists, if you don't see it it's probably a bug.
![image](https://user-images.githubusercontent.com/59544401/112889240-3d1b0680-908a-11eb-91a2-2e35158468a1.png)

**Comment by yaichenbaum** [comment]
We don't plan to implement this option in Files, but as @winston-de mentioned, you can accomplish this by modifying the registry.
