### ISSUE TITLE
[UI] Scrollbar visible on settings button when sidebar is collapsed.

### ISSUE THREAD

**Issue by Tropix126** [files-community/Files#4347]
**Explain the bug**
When the sidebar is collapsed through the hamburger menu, the settings button in the bottom left will develop a scrollbar when the cursor is at the right of the button.

**To reproduce**
1. Open files
2. Collapse the sidebar via the hamburger menu at the top left.
3. Hover your mouse at the very right of the settings button.

**Expected behavior**
A scrollbar should not be visible when the sidebar is collapsed.

**Logfile**
not relevant

**Screenshots**
Add screenshots to help explain your problem if needed.
![image](https://user-images.githubusercontent.com/42101043/112767259-57e27200-8fdb-11eb-9050-1da153b0a3b4.png)

**System Information**
 - OS Version: Dev (OS Build 21332.1000)
 - App version: 1.5.0.0

**Additional comment**
None

**Comment by DashCruft** [comment]
Happens to me too sometimes
![image](https://user-images.githubusercontent.com/59381835/112767643-cff56b80-8fcc-11eb-937b-a81db761b54c.png)

**Comment by josh-65** [comment]
I have this too and made an issue about it. Apparently it a WinUI bug that's suppose to be fixed in WinUI 2.6.

**Comment by yaichenbaum** [comment]
As mentioned by @josh-65, this issue will be resolved once WinUI 2.6 is released.
