### ISSUE TITLE
[Enhancement] Add back dividers between tabs

### ISSUE THREAD

**Issue by Tropix126** [files-community/Files#4348]
**Is your feature request related to a problem?**
With the UI overhaul released, it's rather difficult to tell your tabs apart, due to a lack of elevation or indication of where one tab ends and the other begins.

**Describe the solution**
Add small dividers between inactive tabs (similar to those seen on chrome and edge).

**Describe alternatives you've considered**
Slightly elevate inactive tabs in color to better distinguish between them.

**Additional comment**
Current Design:
![image](https://user-images.githubusercontent.com/42101043/112767352-e656f380-8fdb-11eb-8021-f75dd2e156d3.png)

Proposed Design:
![image](https://user-images.githubusercontent.com/42101043/112767391-228a5400-8fdc-11eb-9eb7-6170b95bc05d.png)

**Comment by DashCruft** [comment]
That's a perfect idea. I vouch for it.

**Comment by d2dyno1** [comment]
Great idea :+1: It's very subtle yet it helps to distinguish between individual tabs.

**Comment by josh-65** [comment]
I think it should be more noticeable if its going to be implemented. I could barely tell that they were there with my display.

**Comment by generalguy41** [comment]
If this does get implemented, I don't think the separators need to be around the active tab, similar to Edge.

![image](https://user-images.githubusercontent.com/8879244/112775926-3a79cc00-900c-11eb-92a0-817d70a31cb7.png)

**Comment by yaichenbaum** [comment]
This change was implemented in #4612.
