### ISSUE TITLE
Address Bar Buttons Only Work When Text is Clicked

### ISSUE THREAD

**Issue by Njsmooth** [files-community/Files#4350]
**Explain the bug**
In the address bar, clicking a button that sends you to a folder only sometimes works. To be more specific, only clicking on the text works.

**To reproduce**
2. Click on a button in the address bar slightly above the text.

**Expected behavior**
Clicking anywhere on the button should (or at least I think should) work.

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6218474/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6218475/debug_fulltrust.txt)

**Screenshots**
https://user-images.githubusercontent.com/70276371/112772974-e538bd00-9001-11eb-93ad-46d4b5d8c707.mp4

**System Information**
 Edition	Windows 10 Pro
Version	20H2
Installed on	‎10/‎10/‎2020
OS build	19042.867
Experience	Windows Feature Experience Pack 120.2212.551.0

 - App version: 1.5.2.0

**Comment by pc-v2** [comment]
reproduceable for me

**Comment by gave92** [comment]
Fixed in latest code.
