### ISSUE TITLE
Add "Pin to Start" and "Pin to Taskbar" For Folders

### ISSUE THREAD

**Issue by pc-v2** [files-community/Files#4351]
**Is your feature request related to a problem?**
The current implementation is only have "Pin to Sidebar"
would be nice to add "Pin to Start/Taskbar"

![image](https://user-images.githubusercontent.com/58063311/112777434-717fca00-906c-11eb-9a98-b0d22557f856.png)

**Comment by d2dyno1** [comment]
This functionality already exists in Files. You can pin folders to start by holding shift and right clicking a folder to expand context menu with options:

![image](https://user-images.githubusercontent.com/53011783/112819916-5bcace80-9085-11eb-94f4-71abb1389285.png)
