### ISSUE TITLE
Custom Icon For Sidebar

### ISSUE THREAD

**Issue by pc-v2** [files-community/Files#4352]
using new windows insider icons could be good (I know uwp uses monochromatic based on MDL fonts at sidebar, but it could be good if there's an option to change the icon

**Additional comment**
Add any other comment or screenshots about the feature request here. What device type/UI layout and app version?

![image](https://user-images.githubusercontent.com/58063311/112777665-f66ae380-906c-11eb-8668-71719bd86d90.png)

**Comment by yaichenbaum** [comment]
Files v2 will load the icons from the system enabling support for loading custom icons as well.
