### ISSUE TITLE
Hi, how is it possible to add folders to Libraries?

### ISSUE THREAD

**Issue by Harfenklang** [files-community/Files#4357]
**Is your feature request related to a problem?**
A clear description of what the problem is.

**Describe the solution**
A clear description of what you want.

**Describe alternatives you've considered**
A clear description of any alternative solutions or features you've considered.

**Additional comment**
Add any other comment or screenshots about the feature request here. What device type/UI layout and app version?

**Comment by josh-65** [comment]
not yet they are working on this

**Comment by Harfenklang** [comment]
Great! I'm looking forward to this feature!
Best wishes,
Lorenz.

Am 29. März 2021 16:31:06 schrieb Josh-65 ***@***.***>:
>
> not yet they are working on this
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

Musik- und TherapieWerkstatt
Praxis für Ergotherapie &
Werkstatt für HarfenKlang

Lorenz Münderlein
Krankenhausstr. 29
78628 Rottweil

0741-480 0987 (Praxis)
0741-4800 988 (Werkstatt)
0741-942 3080 (Privat)

www.harfenklang.de
www.musik-und-therapiewerkstatt.de

**Comment by gave92** [comment]
Being implemented in #4334
