### ISSUE TITLE
Actions in directories that require elevated permissions do not prompt for elevated permissions

### ISSUE THREAD

**Issue by emilnymann** [files-community/Files#4358]
**Explain the bug**
Attempting to perform somean actions (e.g. move, copy, rename, etc.) in specific directories (e.g. `C:\Program Files\`) requires elevated permissions, but Files does not prompt for this, and instead the action is just discarded. When the attempted action is to move, the source file is still deleted. The only action that seems to work is delete.

**To reproduce**
1. Browse to `C:\Program Files\SomeProgramFolder`
2. Attempt to rename or move any folder or file
3. Nothing happens

**Expected behavior**
Files should prompt for elevation and complete the action.

**Screenshots**
![ffOZn4Y](https://user-images.githubusercontent.com/27289912/112843183-9c851080-90a2-11eb-8708-e13e3f5f167d.gif)

**Comment by gave92** [comment]
Merging with #2513 and similar.
