### ISSUE TITLE
RENANE EXTENSION FILES

### ISSUE THREAD

**Issue by ascrs** [files-community/Files#4361]
I was unable to rename the file extension.

I created it through the program itself. Right-click, NEW TEXT FILE. Created a file with no extension. When trying to rename it, it gives an error message (attached). 

Message text/error:
Invalid item name 
The specified name is invalid. Please check the name of the desired item and try again. 
![erro_files_extensionfile](https://user-images.githubusercontent.com/19193416/112846294-469d7200-907c-11eb-84f7-cd9c7277b892.png)

**Comment by gave92** [comment]
Merging with #4661
