### ISSUE TITLE
Second pane fixed in all tabs 

### ISSUE THREAD

**Issue by lugh18** [files-community/Files#4364]
When I have several TABs open and I open a new directory in the second panel, this directory and /or the second panel disappears when I choose one of the open TABs or when I choose to create a new TAB.
I expect to always see the second panel after having created that second panel. Am I wrong?

best regards, Jens
**Explain the bug**
Write a clear description of what the bug is.

**To reproduce**
1. Go to '....'
4. See the error

**Expected behavior**
Write a clear description of what you expected.

**Logfile**
Upload the log file here for us to understand your issue better. 
- You can access it from Settings->About->Open log location. 
or 
- Copy the debug.txt and debug_fulltrust.txt from the following directory, and upload the files here.
`%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 

**Screenshots**
Add screenshots to help explain your problem if needed.

**System Information**
 - OS Version: [e.g. Windows 10 20H2 19042.804] (Press WIN + PAUSE/BREAK, use the copy button at the bottom)
 - App version: [e.g. v1.0] (In the app, go to Settings -> About, the version is shown at the top)

**Additional comment**
Add any other comment about the problem here. Does this problem happen again after restarting the app?

**Comment by gave92** [comment]
If you wish you can choose to always show the second pane when opening a new tab (see setting under "multitasking" settings). But panes are tied to the tab, you can have some tabs with two panes and some tab with one pane. This is by design. Could you elaborate on why the bahaviour you suggest would be better?

**Comment by lugh18** [comment]
I didn't say it would be better; I just expected a consistent 
two-pane-view, when I switch that on. Your design is a new concept, that 
I never found in other file managers.

These (Windows-)managers always offer a consistent 2-pane-view (except 
the Explorer...); I used - almost 20 years OS X and the FINDER with the 
"columns-view" APPLE took from NEXT OS; a horizontal focused view of a 
directory/path. Probably your filemanager reminds me a little bit to 
this FINDER-view - especially the support of "Quicklook" which I 
appreciate very much.
I just see one case, when it is very useful to see the second pane with 
always the same directory/folder : when I want to move/copy 
files/folders from different directories to this one directory/folder, 
because I don't like to have to open a second window of the file 
manager. Therefore I prefer a separate consistent second pane.
Another reason of a separate pane might be the option I found in 
"SpeedCommander": there you can use/switch to) the second pane for 
"Quicklook"-option.
Maybe I'll appreciate your concept after some time of usage.

Best regards, Jens


__________________________________
Gesendet aus eM Client | www.emclient.de <http://de.emclient.com>

------ Originalnachricht ------
Von: "Marco Gavelli" ***@***.***>
An: "files-community/Files" ***@***.***>
Cc: "lugh18" ***@***.***>; "Author" ***@***.***>
Gesendet: 29.03.2021 21:23:57
Betreff: Re: [files-community/Files] Second panel relates to TAB? 
(#4364)

**Comment by gave92** [comment]
Thanks @lugh18 I see your point, keeping this open to get more feedback. I think we could add a button to "pin" the second pane so it stays on the same directory when switching tabs maybe.

**Comment by carlosvsilva** [comment]
I think a solution would be to have two tab bars, one for each side of the pane. That way, you could switch between multiple directories while keeping the two pane interface in place. Thanks

**Comment by yaichenbaum** [comment]
@lugh18 the intended behavior is to change the directory of the first pane as opposed to opening a second tab. I see your use case but it might be better with the split view feature in Windows.
