### ISSUE TITLE
Click and hold selection doesn't always work in detail view

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#4366]
**Explain the bug**
The mouse click and hold selection doesn't always work.

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6224340/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6224341/debug_fulltrust.txt)

**System Information**
 - OS Version: Windows 10 20H2 19042.870
 - App version: v1.5.2.0

**Comment by gave92** [comment]
Could you post a screen recording of this? Thanks!

**Comment by josh-65** [comment]
I will try

**Comment by josh-65** [comment]
Uploading 2021-03-29 23-49-41.mov…

**Comment by generalguy41** [comment]
Same as #3263?

**Comment by josh-65** [comment]
It seems it is.
