### ISSUE TITLE
Text overlapping on address bar.

### ISSUE THREAD

**Issue by Tropix126** [files-community/Files#4369]
**Explain the bug**
When the search bar is focused, opening the "More options" menu will cause a strange visual bug where the search text overlaps the address bar.

**To reproduce**
1. Click the search button to trigger search.
2. With the bar still focused, click on the 3 dots to open the "More options" menu.

**Expected behavior**
Search menu should close upon the menu being opened.

**Logfile**
not relevant

**Screenshots**

https://user-images.githubusercontent.com/42101043/112923626-37e2a980-90d4-11eb-834b-55b6096d2977.mp4

**System Information**
 - OS Version: Windows 10 Dev (21332.1000)
 - App version: 1.5.0.0

**Additional comment**
None.

**Comment by cinqmilleans** [comment]
Hello, I can fix it if the team assigns me this bug.

**Comment by yaichenbaum** [comment]
@Tropix126 This issue should be resolved with #4649.
