### ISSUE TITLE
Google Drive

### ISSUE THREAD

**Issue by mrdzkn** [files-community/Files#4379]
The content of the google drive that is mapped to G: in my Windows 10 is not displayed in the application. Official Google Drive desktop application is used to map the drive to G: 

**Explain the bug**
Write a clear description of what the bug is.

**To reproduce**
1. Go to '....'
4. See the error

**Expected behavior**
Write a clear description of what you expected.

**Logfile**
Upload the log file here for us to understand your issue better. 
- You can access it from Settings->About->Open log location. 
or 
- Copy the debug.txt and debug_fulltrust.txt from the following directory, and upload the files here.
`%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 

**Screenshots**
Add screenshots to help explain your problem if needed.

**System Information**
 - OS Version: [e.g. Windows 10 20H2 19042.804] (Press WIN + PAUSE/BREAK, use the copy button at the bottom)
 - App version: [e.g. v1.0] (In the app, go to Settings -> About, the version is shown at the top)

**Additional comment**
Add any other comment about the problem here. Does this problem happen again after restarting the app?

**Comment by gave92** [comment]
Hello please add app version and log files to the description.
Also could you add the full name of the "Official Google Drive" application you're using? There is actually more than one official client.

**Comment by mrdzkn** [comment]
hi,
Files application version is 1.5.0.0
[debug.txt](https://github.com/files-community/Files/files/6228287/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6228288/debug_fulltrust.txt)
I attached the Google Drive application's about page's screenshot.
![image](https://user-images.githubusercontent.com/51743010/112975025-d6661d80-915b-11eb-9ea9-31a4eb6d6899.png)
and this is the install link of the Google Drive application https://dl.google.com/drive-file-stream/GoogleDriveFSSetup.exe

**Comment by gave92** [comment]
Could you check if turning off "Enable individual preferences for individual folder" under Files Settings > Files and Folders fixes the issue?

**Comment by mrdzkn** [comment]
yes, after turning off "Enable individual preferences for individual folder" under Files Settings > Files and Folder, I can now see files and folder in the Google Drive.
Thanks a lot :)
