### ISSUE TITLE
Missing Catalan language

### ISSUE THREAD

**Issue by sketxa** [files-community/Files#4383]
**Is your feature request related to a problem?**
A clear description of what the problem is.

**Describe the solution**
A clear description of what you want.

**Describe alternatives you've considered**
A clear description of any alternative solutions or features you've considered.

**Additional comment**
Add any other comment or screenshots about the feature request here. What device type/UI layout and app version?

**Comment by sketxa** [comment]
I would like to translate the app to Catalan, how I can do it?

**Comment by yaichenbaum** [comment]
@sketxa All the information you need for translating Files can be found in the documentation, let us know if you have any questions. https://files-community.github.io/docs/#/articles/translating-files

**Comment by sketxa** [comment]
Thank you! I will check it!
