### ISSUE TITLE
Accessing current tab properties

### ISSUE THREAD

**Issue by TyJOrtiz** [files-community/Files#4384]
Is there any way to access the current tab to update the name to the current folder? My Column View utilizes multiple instances of an IShellPage (ColumnShellPage.xaml) with their own instance of the FileSystemViewModel inside the root ModernShellPage.

**Comment by gave92** [comment]
Currently it's done by event, from ModernShellPage.cs:
```cs
ContentChanged?.Invoke(this, new TabItemArguments()
{
    InitialPageType = typeof(ModernShellPage),
    NavigationArg = SOME_PATH
};
```

**Comment by duke7553** [comment]
@TyJOrtiz 
As @gave92 said there's typically no reason to update the tab info (header, icon) directly from the main page's view model. 

With that said, we really should expose the ContentChanged event to all IShellPage-derived pages with that interface.

Right now, my understanding is that we fire the ContentChanged event from within a ModernShellPage which MainPageViewModel handles by calling UpdateTabInfo() itself.

**Comment by duke7553** [comment]
@TyJOrtiz Did we answer your question?

**Comment by TyJOrtiz** [comment]
Yeah
