### ISSUE TITLE
Crash when viewing properties of files

### ISSUE THREAD

**Issue by GiornoJJ** [files-community/Files#4388]
Hello sir, 
Firstly I would like to say GREAT app, I am in love with it. It truly is the modern explorer I was looking for. Now then, I've come with a bug report. Every time I view the properties of any files or folder it crashes. Other than that it has some instability issues. 
I hope that you will look into the matter.
Thank you

**Comment by gave92** [comment]
Thanks for this report. Could you add app version and debug files to the issue description?
When the app crashes do you get a notification saying "Something went wrong"?

**Comment by gave92** [comment]
Merging with #2714
