### ISSUE TITLE
Crashes when there are many files and folders in the current directory.

### ISSUE THREAD

**Issue by bhupathi189** [files-community/Files#4391]
**Explain the bug**
Crashes or become unresponsive when there are too many files and/or folders in the current directory. It will sometimes show the folders but immediately crashes and sometimes it will not just try to load those many folders and crashes.
**To reproduce**
This is a personal folder but you can recreate with any folder with many folders.

**Expected behavior**
It has to show files and folders in the directory.

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6234328/debug.txt)

**Screenshots**
![image](https://user-images.githubusercontent.com/35564316/113102227-5f905980-921b-11eb-9d6c-897256be669d.png)

**System Information**
 - OS Version: [e.g. Windows 10 20H2 19042.906] (Press WIN + PAUSE/BREAK, use the copy button at the bottom)
 - App version: [e.g. v1.5.2.0] (In the app, go to Settings -> About, the version is shown at the top)

**Additional comment**
Add any other comment about the problem here. Does this problem happen again after restarting the app?

**Comment by gave92** [comment]
Thanks for this report. Could you try the following? (I'd like to know if this only happens in details view)
1. Turn Off "Enable individual preferences for individual directories" in Settings > Files and Folders
2. Set Tiles or GridView layout mode
3. Try to trigger the crash

**Comment by SlimShadys** [comment]
> Thanks for this report. Could you try the following? (I'd like to know if this only happens in details view)
> 
> 1. Turn Off "Enable individual preferences for individual directories" in Settings > Files and Folders
> 2. Set folder layout mode to Tiles or GridView
> 3. Try to trigger the crash

I don't know if this is relevant, but I tried your 3 steps above and it seems to be working well.
As soon as I switched to Details View > Closed Files > Reopened Files, I went to my personal folder (containing lots of folders / fiels) and it immediately crashed. Went back to GridView and everything was okay.

**Comment by hannta** [comment]
Im having similar issue. Files crashes when I open my home folder if details view layout mode is selected. 

I have only around 20 files and folders on my home folder.

**Comment by andstrat** [comment]
Same Issue here when I open the second level of a  directory on non-C: drives and root layout is Detailed List.

WORKAROUND: As propososed by @gave92 changing the layout once to anything else than Detailed List. A crash never happed again while app was running and when opening a directory in Detail List layout even when switching to another drive.
Crash happens again with a freshly started app.

Option "Individual Layout doe directories" has no effect on solving the issue.

**Comment by bhupathi189** [comment]
When I tried to open a new location, then again it crashed. Before crashing, there were no thumbnails of my files. When opened 2nd time, it is working fine. I think bug is in first indexing or thumbnail retrieval.

**Comment by yaichenbaum** [comment]
This issue appears to be resolved in `main`.
