### ISSUE TITLE
Feature: Add an option to the properties window to run shortcuts as admin

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#4394]
- [ ] Add a toggle switch to the shortcut properties page to run shortcuts as administrator.

**Comment by hecksmosis** [comment]
Hi, I'm currently working on this, could you assign me?

**Comment by gave92** [comment]
Do we really want it in General instead of under the Shortcut tab?

**Comment by yaira2** [comment]
Let's do it under the shortcut page.

**Comment by yaira2** [comment]
@hecksmosis please note the changes to the description

**Comment by hecksmosis** [comment]
Ok, I'll modify the pr in a bit
