### ISSUE TITLE
[Enhancement] Improving the design of the preview pane

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#4396]
![image](https://user-images.githubusercontent.com/39923744/113172896-e0992200-9216-11eb-9270-dbb5ea6bc77c.png)

**Comment by Rasmagoric** [comment]
What about the file size info?

**Comment by zeealeid** [comment]
I think its a pretty big improvement

**Comment by winston-de** [comment]
This looks really good.
@yair100 would you like me to work on implementing it?

**Comment by yaichenbaum** [comment]
@winston-de That would be great!

**Comment by mdtauk** [comment]
I don't think the headings being alongside the values is a good use of the narrow space.

![image](https://user-images.githubusercontent.com/7389110/113241043-c9eddc00-92a5-11eb-82b2-f6eb67624f9b.png)


Stacking them, with different font colours and sizes would be a better heirachy and fit in the narrow scrollable view better

**Comment by winston-de** [comment]
The main issue I can foresee with stacking them is that there are vertical space constraints as well, especially when the preview pane is in a horizontal layout, so less information would be visible without scrolling.
Perhaps they could be shown stacked when the pane is narrowed, and side by side when there is more horizontal space?

**Comment by mdtauk** [comment]
I'm in support of having it reflow as you resize, but the font sizes and colours can still distinguish headers from values

**Comment by R3voA3** [comment]
I like @mdtauk's version more. Looks way more modern. And it will solve the issue with values being cut-off most of the time.

**Comment by winston-de** [comment]
@R3voA3 

> The Date Created should be underneath the other dates and the Exposure Time (0,000625) should be displays as a fraction 1/1600

Both of these requests can be implemented.

> Last but not least, why does it display the path to the item there? It can already be retrieved via the address bar.

The address bar does not show the full item path. The idea of adding the path was to make it easy to view and copy part of or the full item path, which is useful if you are, to name one example, adding relative path references to files in a c# project.

**Comment by R3voA3** [comment]
> The address bar does not show the full item path. The idea of adding the path was to make it easy to view and copy part of or the full item path, which is useful if you are, to name one example, adding relative path references to files in a c# project.

Since the path is quite long and we do not have the horizontal space in the preview pane. What about a simple *Copy Path* button which has the path as tooltip?

**Comment by winston-de** [comment]
I tried to implement aspects of both designs.
![image](https://user-images.githubusercontent.com/59544401/113461587-fe5eb680-93d1-11eb-841d-a7d0b788b8b6.png)

**Comment by R3voA3** [comment]
The front is pretty huge isn't it?

**Comment by mdtauk** [comment]
@winston-de  you will need to add extra padding beneath the values, to make it clearer which heading goes with which value

**Comment by winston-de** [comment]
@mdtauk Updated

**Comment by mdtauk** [comment]
> @mdtauk Updated

Looking better!

**Comment by R3voA3** [comment]
Looks nice now!
