### ISSUE TITLE
[Bug report] Selection commands aren't working on the selected column

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#4398]
**To reproduce**
1. Go to any directory
2. Click on one of the selection options in the toolbar
3. See the error

**Comment by yaichenbaum** [comment]
Fyi @TyJOrtiz

**Comment by TyJOrtiz** [comment]
I see what's going on, i'll fix it

**Comment by yaichenbaum** [comment]
Thanks!

**Comment by esibruti** [comment]
@yair100 I think we can close this
