### ISSUE TITLE
Please remove the animation for loading the recent used files in the home section

### ISSUE THREAD

**Issue by szaimen** [files-community/Files#440]
**Is your feature request related to a problem? Please describe.**
The home view feels kind of slow, because there is a slow loading animation when loading the recent used files

**Describe the solution you'd like**
They should appear instantly (don't know if that has to do with loading them...

**Describe alternatives you've considered**
Currently nothing.

**Additional context**
app version 0.7.0 Windows 10 1909 Microsoft Surface Pro 3 with i5

**Comment by yaichenbaum** [comment]
The page itself loads pretty fast but I see what you mean with the recent items list. Perhaps we can use a fade-in animation for the list view as opposed to animating each **item** on its own in the list view.

**Comment by szaimen** [comment]
> The page itself loads pretty fast but I see what you mean with the recent items list. Perhaps we can use a fade-in animation for the list view as opposed to animating each **item** on its own in the list view.

Yes, that would be nice 👍
