### ISSUE TITLE
Dialog window disappears behind the Files Window when you select a zip file for extraction.

### ISSUE THREAD

**Issue by mbuschagen** [files-community/Files#4404]
**Explain the Bug**

When selecting a zip file for extraction within Files the dialog window to confirm the extraction settings is placed behind the main Files window, instead, it should pop-up in the foreground so you can see it. Additionally, once you confirm the extraction settings and hit Extract, the newly extracted folder opens in File Explorer, not in Files.

**To reproduce**
1. Go to any folder that contains a zip file.
2. Right-click, and select Extract All.
3. Now you can see that the new window that opens for the extraction is placed behind the Files window.
4. Confirm the extraction path.
5. Hit Extract.
6. A new Windows Explorer instance opens displaying the content of the newly extracted zip file.

**Expected behavior**
I would expect that after you select Extract All, that the dialog window that appears would open in the foreground rather than in the background. Additionally, I would expect that the newly extracted zip file would open in a new window or tab of Files.

**Logfile**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6239815/debug_fulltrust.txt)

[debug.txt](https://github.com/files-community/Files/files/6239805/debug.txt)

**Screenshots**
![RightClick](https://user-images.githubusercontent.com/80843256/113218662-c3734c00-9234-11eb-86d7-f586c45bb822.png)
![Extract](https://user-images.githubusercontent.com/80843256/113218666-c40be280-9234-11eb-841c-e290e382932d.png)
![ConfirmExtract](https://user-images.githubusercontent.com/80843256/113218667-c40be280-9234-11eb-9ad9-3115cf914140.png)
![ExtractComplete](https://user-images.githubusercontent.com/80843256/113218668-c4a47900-9234-11eb-88e7-a704d20aefe4.png)

**System Information**
Edition	Windows 10 Pro
Version	20H2
Installed on	‎12/‎11/‎2020
OS build	19042.870
Experience	Windows Feature Experience Pack 120.2212.551.0

![FilesVersion](https://user-images.githubusercontent.com/80843256/113218861-1a792100-9235-11eb-8c0a-89c69144cb1c.png)

**Additional comment**
This behavior repeat after re-starting the Files App, and after a re-boot on the Windows Machine as well.

**Comment by yaichenbaum** [comment]
Merging with #985.
