### ISSUE TITLE
lost folder

### ISSUE THREAD

**Issue by shuohao** [files-community/Files#4407]
lost the folder, see the screenshot
**System Information**
 - OS Version: Windows 10 21H1 19043.899
 - App version: 1.5.2.0

<img width="723" alt="微信截图_20210401144136" src="https://user-images.githubusercontent.com/4637107/113254106-bfa8fd80-92f8-11eb-819c-e57e123c321a.png">

**Comment by yaichenbaum** [comment]
Is this still an issue in v1.5.62?
