### ISSUE TITLE
File counter

### ISSUE THREAD

**Issue by SiRo24** [files-community/Files#4408]
**Explain the bug**
Write a clear description of what the bug is.

**To reproduce**
1. Go to '....'
4. See the error

**Expected behavior**
Write a clear description of what you expected.

**Logfile**
Upload the log file here for us to understand your issue better. 
- You can access it from Settings->About->Open log location. 
or 
- Copy the debug.txt and debug_fulltrust.txt from the following directory, and upload the files here.
`%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 

**Screenshots**
Add screenshots to help explain your problem if needed.

**System Information**
 - OS Version: [e.g. Windows 10 20H2 19042.804] (Press WIN + PAUSE/BREAK, use the copy button at the bottom)
 - App version: [e.g. v1.0] (In the app, go to Settings -> About, the version is shown at the top)

**Additional comment**
Add any other comment about the problem here. Does this problem happen again after restarting the app?

I sometimes experience that the counter of elements in a folder (bottom left corner) doesn't show the real number. Oftentimes it stays on one number (today it is 29) every time I open a folder. When I refresh by clicking F5, the correct number gets displayed.

**Comment by generalguy41** [comment]
Same as #4281?

**Comment by SiRo24** [comment]
Similar, my counter shows the true number in Detail View, but not in all the other ones, it only corrects itself when I press F5.

**Comment by yaichenbaum** [comment]
Is this still an issue in v1.5?
