### ISSUE TITLE
Create a new file does not create the correct extension file.

### ISSUE THREAD

**Issue by lettucemarcvel** [files-community/Files#4410]
**Explain the bug**
Create a new Word Document, so in any location that you want, inside your folders, righ click in one free space and then select NEW and select Microsoft Word Document, a pop-up window comes to type the new name. The file is created but not extension .docx, so when you double click in the file appears the option to select what app use to open the file (this window selector does not have cancel or X to close the window, another bug coming)

**To reproduce**
1. Go to any folder.
2. Righ click
3. Select NEW
4. Select Microsoft Word Document
5. Type the name.
6. And the files do not have an extension.

**Expected behavior**
After type the name, I expected to see the Word Document File.

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6243504/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6243505/debug_fulltrust.txt)

**Screenshots**

A video always is better!
https://user-images.githubusercontent.com/78508675/113295499-4690b280-92c6-11eb-8ec0-372b47703b17.mp4

**System Information**
 - OS Version:  Windows 10 Pro 10.0.19042

**Additional comment**
Add any other comment about the problem here. Does this problem happen again after restarting the app?

**Comment by yaichenbaum** [comment]
@winston-de This issue is resolved in `main`, right?

**Comment by winston-de** [comment]
@yair100 Yes.

**Comment by yaichenbaum** [comment]
@lettucemarcvel This issue will be resolved in the next update to the Store.
