### ISSUE TITLE
Context menu: Add tooltips for flyout command bar buttons

### ISSUE THREAD

**Issue by XPoppyX** [files-community/Files#4412]
They should have a tooltip so that the user is sure what each button does, even if the icon is obvious.

![Captura de pantalla 2021-04-01 103314](https://user-images.githubusercontent.com/61259627/113310612-6cbe4e80-92d6-11eb-8d11-a40f36ede083.png)

**Comment by yaichenbaum** [comment]
@XPoppyX You beat me to this issue, I was just about to open it 😂.

**Comment by winston-de** [comment]
I could have sworn the CommandBarFlyout was supposed to do this automatically based on the item label.
