### ISSUE TITLE
I'd love to see Quick Access in this app

### ISSUE THREAD

**Issue by DHCross** [files-community/Files#4415]
Got it. 

**Is your feature request related to a problem?**
No problem. 

**Describe the solution**
I would just like to see the Quick Access in your app. 

**Describe alternatives you've considered**
I can't think of anything else.

**Comment by yaichenbaum** [comment]
@DHCross Can you explain what you mean by Quick Access?

**Comment by DHCross** [comment]
![quickaccess](https://user-images.githubusercontent.com/45954119/113356075-58467a00-9307-11eb-9274-b3642179a83b.png)

**Comment by yaichenbaum** [comment]
@DHCross You should already be able to pin things to the favorites section.
