### ISSUE TITLE
App crashes inmediately after clean install while enabling dual pane view

### ISSUE THREAD

**Issue by osieltorres** [files-community/Files#4417]
**Explain the bug**
After a clean install of the application, enabling "dual pane view" option on Multitasking settings by first time, will make the application to crash inmediately.

**To reproduce**
1. Open the 'application' after clean install or after reset app data through windows settings.
2. Click on 'Settings'
3. Go to 'Multitasking' setting and click 'Enable dual pane view'
4. The application crashes inmediately and closes, even on further attempts, the dual pane view is not enable after selecting, and app restart is needed to see changes.

**Expected behavior**
The 'dual pane view' to be enabled and available once go back from app settings to home view.

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6246934/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6246935/debug_fulltrust.txt)

**System Information**
 - OS Version: Windows 10 Pro 20H2, build 19042.906. Experience Windows Feature Experience Pack 120.2212.551.0

 - App version: 1.5.2.0

**Comment by yaichenbaum** [comment]
@osieltorres This issue should be resolved in `main`.
