### ISSUE TITLE
Add NextCloud folder to cloud storages

### ISSUE THREAD

**Issue by tkarika** [files-community/Files#4420]
**Is your feature request related to a problem?**
My NextCloud folder is not listed in the Cloud Storages section.

**Describe the solution**
It would be nice, if along OneDrive and Google Drive, my NextCloud folder would be listed in the Cloud Storages section. I didn't find any way to add it manually either.

**Describe alternatives you've considered**
Currently I just added the folder to the favorites.

**Comment by yaichenbaum** [comment]
Merging with #1245.

**Comment by tkarika** [comment]
Isn't it a different issue though? I see the folder in the file list, but I don't see it in the sidebar.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7401
