### ISSUE TITLE
Share charm doesn't use the right theme when the app uses a different theme

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#4421]
**Explain the bug**
Write a clear description of what the bug is.
When the app theme is different from the system theme, it uses the system theme instead of the app theme.

**To reproduce**
1. Go to folder
2. Right click on a file or folder and click Share
4. See the error

**Expected behavior**
Write a clear description of what you expected.
The share flyout should use the same theme as the app theme. There's actually an overload of ShowShareUI that takes in a ShareUIOptions object which has a theme property and Files should call that instead.

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran This issue should be resolved with #4427.
