### ISSUE TITLE
Context menu issue with list view

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#4422]
**Explain the bug**
When opening the context menu via the keyboard, in list view mode the selection gets cleared and also the context menu appears on the top of the data grid itself as opposed to top/bottom of the selected item. This issue is specific to the list view layout mode and doesn't exist in other layout modes.

**To reproduce**
1. Go to a folder and use the list view layout mode
2. Select an item and use your keyboard's context menu button
4. See the error

**Expected behavior**
Write a clear description of what you expected.
The selection shouldn't be cleared and the context menu shouldn't appear on top of the data grid but below the selected items or above if there's not enough space

**System Information**
 - OS Version: Windows 10 Pro version 2009
 - App version: 1.5.2

**Comment by gave92** [comment]
Also #2609
