### ISSUE TITLE
Crash when trying to rename an item

### ISSUE THREAD

**Issue by XPoppyX** [files-community/Files#4425]
1- Right click on an item
2- Click on "Rename"
3- The app crashes

![crash](https://user-images.githubusercontent.com/61259627/113434640-56d08c80-93af-11eb-96fb-afb259b086a5.gif)

Log:
`2021-04-02 12:28:26.2889|ERROR|Files.App|Object reference not set to an instance of an object.|System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.Views.LayoutModes.GridViewBrowser.StartRenameItem()
   at Files.Interacts.BaseLayoutCommandImplementationModel.RenameItem(RoutedEventArgs e)
`

**Comment by TyJOrtiz** [comment]
This is an issue i raised (#4268) @winston-de @yaichenbaum @d2dyno1

**Comment by gave92** [comment]
Merging with #4228
