### ISSUE TITLE
Add colored icons for recycle bin and home

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#4430]

**Comment by esibruti** [comment]
@yair100 is it still necessary for these icons? Or is it currently implemented?

**Comment by yaichenbaum** [comment]
@esibruti This task isn't completely finished yet.

**Comment by esibruti** [comment]
@yair100  But if you want, I can look for the icons. Can you tell what shape, size, those things ...

**Comment by yaichenbaum** [comment]
@esibruti We have the icons, it's just a matter of using them.
