### ISSUE TITLE
Feature: Add option to sort by date taken

### ISSUE THREAD

**Issue by winston-de** [files-community/Files#4432]
**Is your feature request related to a problem?**
When viewing photos, the date created and date modified values are not an ideal method for viewing photos sorted by the most recent, as it generally will show when you imported the photo, not when it was taken. 

**Describe the solution**
I think a solution to this would be to add a sort by date taken option for folders that mostly contain photos and videos. 

The problem with this is that the only way (that I know of) to get the date taken value is through the StorageFile properties, so this feature may only be possible when using the universal (not the win32 find data one) enumerator, or find a way to access it using win32 APIs.

**Describe alternatives you've considered**
Photos already provides this functionality, although it would be nice to have it in Files for individual directories.

**Additional comment**
OneDrive and Windows Explorer both have this feature.

**Comment by yaira2** [comment]
@winston-de group by date taken as well?

**Comment by winston-de** [comment]
yeah good idea

**Comment by yaira2** [comment]
@winston-de we're going to continue tracking this in #8366.
