### ISSUE TITLE
Automatically generate a new name for copied folder/file if copying from the same directory

### ISSUE THREAD

**Issue by kimlimjustin** [files-community/Files#4435]
**Is your feature request related to a problem?**
Files always ask to generate a new name or replace existing when copying folder/file even in the same directory.

**Describe the solution**
If the source and target of copying is the same, just auto-generate a name for it, for example, `Folder Name` into `Folder Name ~ Copy` instead of asking whether to generate a new name or replace existing (ofc user will generate a new name if it's in the same directory cuz that's the purpose xd)

**Describe alternatives you've considered**
Otherwise, pop up a notification that FIles will duplicate the file/folder to the new name

**Comment by gave92** [comment]
Merging with #3900
