### ISSUE TITLE
Double click on MultiSelect checkbox open the item

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#4437]
**Explain the bug**
Click on MultiSelect checkbox is also a click on the item. Deactivating a checkbox immediately after activating (to correct an entry error), or the opposite, is considered a double click and can open the folder/file.

**To reproduce**
1. Open a non-empty folder.
2. Select a view with multi-select.
3. Active multi-select in the selection menu.
4. Quickly double-click on a selection checkbox.
5. The item opens.

**Expected behavior**
Click on the checkbox shouldn't open the item but only change the state of the box. 

**Additional comment**
I will try to fix this bug.

**Comment by winston-de** [comment]
This behavior was intentional (feature not a bug™️), so that users would still be able to navigate with multiselect enabled. However I can see how it would make more sense do do it this way.
