### ISSUE TITLE
Image resolution in preview pane has too many decimal places

### ISSUE THREAD

**Issue by trulko** [files-community/Files#4444]
**Is your feature request related to a problem?**
When selecting an image and opening the Preview pane, the image resolution (both horizontal and vertical) shows a many many decimal places that overflow the pane and get cut off.

**Describe the solution**
These numbers should be rounded after a certain number of significant figures.

**Describe alternatives you've considered**
You could make it scrollable, but I don't see why you would do that when the simple solution is to round to a certain number of digits.

**Additional comment**
App version 1.5.0.0
![Screenshot 2021-04-03 222901](https://user-images.githubusercontent.com/81886277/113496882-0ef35780-94cc-11eb-9ec4-ebbc5d3cc05f.png)

**Comment by yaichenbaum** [comment]
@trulko This issue should be resolved with #4431.
