### ISSUE TITLE
Broken files sorting

### ISSUE THREAD

**Issue by kimlimjustin** [files-community/Files#4446]
**Explain the bug**
I got no idea why the `rufus_files` folder always placed at the top

**To reproduce**
1. Use Rufus to flash a USB drive
2. Rufus will produce the `rufus_files` folder
3. The `rufus_files` folder will always placed at the top

**Expected behavior**
Just being sorted as it supposed to be.

**Logfile**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6254070/debug_fulltrust.txt)

**Screenshots**
https://user-images.githubusercontent.com/61906684/113501311-473b7a00-954e-11eb-9c06-37fecd01db74.mp4

**System Information**
 - OS Version: Microsoft Windows 10 Home Single Language 10.0.18363 N/A Build 18363
 - App version: 1.5.0.0

**Comment by gave92** [comment]
The folder stays at the top because it's the only folder. Folders by default are always at the top of the list.
To change this you can toggle the "Sort folders together with files" option in Files settings.

**Comment by kimlimjustin** [comment]
> The folder stays at the top because it's the only folder. Folders by default are always at the top of the list.
> To change this you can toggle the "Sort folders together with files" option in Files settings.
> 
> Maybe we could copy explorer here and show folders at the bottom when the sorting is reversed..

Oh okay, thanks
