### ISSUE TITLE
Support for Path Environments

### ISSUE THREAD

**Issue by MRZ07** [files-community/Files#4447]
**Is your feature request related to a problem?**
Paths like  %APPDATA%\GIMP\ do not work currently

**Describe the solution**
Support for Path Environments have to be included to solve it

**Additional comment**
Version: .5.0.0

**Comment by gave92** [comment]
Curious works fine for me so.. bug.

**Comment by emzy07** [comment]
It works now after a reinstallation, I also encountered that "%APPDATA%\GIMP\ " (with a whitespace on the end) will lead to a NotAFolder error. Maybe we could trim the path before executing.

**Comment by yaichenbaum** [comment]
This issue appears to be resolved in `main`.
