### ISSUE TITLE
One Drive Compatibility

### ISSUE THREAD

**Issue by aelbanyard** [files-community/Files#4449]
For me as a student who Likes to have acces to my Files from everywhere, i like to use OneDrive. 
My Problem with this extremely cool App is that it does not have a funktion to add OneDrive, so if you could add this it would be extremely helpfull and cool.
Kind Regards
A future Programmer

**Comment by gave92** [comment]
Onedrive folder should be automatically added to the sidebar but the Onedrive client needs to be installed and running.

**Comment by yaichenbaum** [comment]
We need a little more information from you in order to investigate this issue, please reopen this issue once you have filled out the issue template.

**Comment by aelbanyard** [comment]
It doesn't show onedrive in the sidebar and i def have the client installed. Could you explain to me who to make it appear please

**Comment by yaichenbaum** [comment]
@aelbanyard Can you fill out the issue template so we can investigate this issue? Particularly, we need the app version, and Windows version. An upload of the log files would be helpful as well.
