### ISSUE TITLE
New tab button disappears in a specific width

### ISSUE THREAD

**Issue by AkazaRenn** [files-community/Files#4450]
**Explain the bug**
New tab button disappears in a specific width, for me it's the width when the tab bar sits exactly three tabs

**To reproduce**
1. Open three tabs, if you already have three, close one first
2. Resize the window to a width when the tab bar sits exactly three tabs
3. See the error

**Expected behavior**
A new tab button should be next to the tabs

**Screenshots**
![image](https://user-images.githubusercontent.com/8340896/113517736-dac17a80-954f-11eb-9727-557f2a7a56e6.png)

**System Information**
 - OS Version: Windows 10 Pro for Workstations Insider Preview Dev 21343.1000
 - App version: 1.5.0.0

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
