### ISSUE TITLE
Setting to replace Win+E shortcut to open Files and not Windows File Explorer

### ISSUE THREAD

**Issue by HvadFanSkalJegHedde** [files-community/Files#4452]
**Is your feature request related to a problem?**
The specified feature request is not a specific problem, but it would be nice to quickly open the Files explorer instead of the Windows File Explorer when pressing Win+E.

**Describe the solution**
The solution to this would be to open the Files explorer instead of the Windows File Explorer.

**Describe alternatives you've considered**
I haven't considered any alternatives for this request.

**Additional comment**
No additional comment needed.

**Comment by winston-de** [comment]
Thanks for opening this issue. There is already a way to do this, you can find it [here](https://files-community.github.io/docs/#/articles/configure-win-e) in the docs.
