### ISSUE TITLE
Add an Open With... Option

### ISSUE THREAD

**Issue by DogeLord081** [files-community/Files#4453]
I want a feature for an Open With... when you right-click a file, kind of like the windows file explorer one because when I want to edit a photo with Photoshop, there's no option to let me open it in Photoshop. Also, dragging the image into Photoshop doesn't work either for some reason. Thanks!

**Comment by CF-71** [comment]
Actually, the function should be available. 

(Öffnen mit = Open with)

![Screenshot (9)](https://user-images.githubusercontent.com/79550364/113579010-fa29d780-9623-11eb-8ff8-bf8623674a0f.png)

**Comment by DogeLord081** [comment]
> Actually, the function should be available.
> 
> (Öffnen mit = Open with)
> 
> ![Screenshot (9)](https://user-images.githubusercontent.com/79550364/113579010-fa29d780-9623-11eb-8ff8-bf8623674a0f.png)

Not for photos / images

**Comment by CF-71** [comment]
Do you have a special idea of "photo-files"? Which photo-format (file extension) do you mean in detail?

I mean by a photo-format, for example .jpg/.jpeg and .png. And these formats work.

I also use: .bmp, .gif, .tiff, .cpt (Corel-Photo), .cdr (Corel-Draw). And these also work.

**Comment by winston-de** [comment]
Thanks for opening this. As was already mentioned, this feature already exists, if it's not showing up, then it's a bug. Could you please post a screenshot of it not showing up so I can try and debug it?
