### ISSUE TITLE
Selecting and deselecting items with right click does not work

### ISSUE THREAD

**Issue by mafra99** [files-community/Files#4457]
**Explain the bug**
Right-clicking to select and deselect items does not work on the main branch at the moment. With version 1.5 it works.

**To reproduce**
1. Open a folder
2. Right click any item
    Expected: item is selected
    Actual: item is selected
3. Right click another item
    Expected: new item is selected
    Actual: new item is **not** selected, item from step 2 remains selected
4. Right click an empty area
    Expected: selection is cleared
    Actual: selection is **not** cleared, item from step 2 remains selected

**Screenshots**

https://user-images.githubusercontent.com/56681014/113568116-34897980-9610-11eb-8e37-bfc9dfd3813e.mp4

**System Information**
 - OS Version: 
Edition Windows 10 Pro Insider Preview
Version	Dev
Installed on	‎27.‎03.‎2021
OS build	21343.1000
Experience	Windows 10 Feature Experience Pack 321.7401.0.3

 - App version: main branch commit hash 6f7f602499afa78ea584a8b69342e50d4f250de6

**Comment by mafra99** [comment]
I have already fixed the problem on a local branch.
Let me know if I should create a PR 😃

**Comment by yaichenbaum** [comment]
@mafra99 Can you open a PR?
