### ISSUE TITLE
Open folder from the address bar in a new tab by clicking on the mouse wheel

### ISSUE THREAD

**Issue by almeidx** [files-community/Files#4458]
**Is your feature request related to a problem?**
N/A

**Describe the solution**
Clicking with the mouse wheel on any folder in the address bar should open it in a new tab
Similar to when you click with the mouse wheel on a normal folder.

**Describe alternatives you've considered**
N/A

**Additional comment**
N/A

**Comment by yaichenbaum** [comment]
Merging with #3667.
