### ISSUE TITLE
Tweak sidebar padding for consistency

### ISSUE THREAD

**Issue by trulko** [files-community/Files#4461]
**Is your feature request related to a problem?**
The sidebar in files is very nice, but there are two inconsistencies between the sidebar and right-hand pane that bother me: the sidebar header (hamburger icon and "Files" text) is not aligned with the tabs (see picture below), and the padding of sidebar items is almost-but-not-quite-the-same as padding between folder items in the right-hand-pane list view (see picture below).

**Describe the solution**
Slightly decreasing the vertical padding between sidebar elements to match the right-hand pane and slightly lowering the hamburger button and "Files" text would solve this. This would have the additional benefit of allowing more sidebar items to be seen at a time without scrolling!

**Describe alternatives you've considered**
Padding in the right-hand-pane could also be increased to match the sidebar, but I don't think that would look very nice.

**Additional comment**
App version 1.5.0.0
![Screenshot 2021-04-05 134458](https://user-images.githubusercontent.com/81886277/113605797-238f3700-9615-11eb-9234-111c34215b0c.png)

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
