### ISSUE TITLE
Pressing Alt while dragging and dropping file between directories should copy instead of move

### ISSUE THREAD

**Issue by carlosvsilva** [files-community/Files#4467]
**Is your feature request related to a problem?**
When I have 2 panes open and I drag and drop a file from one pane to another Files always moves the file but sometimes I just want to copy

**Describe the solution**
When I'm dragging and dropping a file between Files panes if I press Alt when dropping Files should copy the file instead of moving.

**Describe alternatives you've considered**
I tried pressing Ctrl, Alt, Shift and nothing changed.

**Additional comment**
Files 1.5 and two panes side by side

**Comment by gave92** [comment]
Merging with #1396
