### ISSUE TITLE
Add a pop-up explorer mode for Files

### ISSUE THREAD

**Issue by JamesIslan** [files-community/Files#4469]
**Is your feature request related to a problem?**
Yes. A problem related to Windows Explorer.

**Describe the solution**
I would like Files to also support pop-up menus (such as those for selecting files in Photoshop).Files is already a standard file explorer, but when a program asks you to open a file or asks to designate a location to save a specific file, you cannot use Files instead of Windows Explorer.

**Describe alternatives you've considered**
In fact, I would continue to use Windows Explorer in pop-up if this feature cannot be added

**Additional comment**
Here's a screenshot to exemplify my request:

![Sem título](https://user-images.githubusercontent.com/69359116/113713826-25610500-96be-11eb-87bc-e8cc8154b8b1.png)

![Captura de tela 2021-04-06 095555](https://user-images.githubusercontent.com/69359116/113714002-517c8600-96be-11eb-8a2e-7d32bd46a677.png)

**Comment by gave92** [comment]
Merging with #4106. Unfortunately to my knowledge it's just not possible to do this.
