### ISSUE TITLE
Refreshing a folder with PDFs crashes the app

### ISSUE THREAD

**Issue by LorenzoSTF** [files-community/Files#4470]
-->

**Explanation of the bug**
If you have a folder in Documents only with PDFs which will be opened with Microsoft Edge PDF Reader and start refreshing the folder too many times very fast, Files will crash..

**To reproduce**
1. Go to 'Documents'.
2. Go to a folder full of only PDFs that will be opened with Microsoft Edge PDF Reader (Microsoft Edge PDF.
3. Click on 'Refresh' too many times in a row.
4. The app crashes.

**Expected behavior**
Not to crash.

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6264762/debug.txt)

**System Information**
 -OS version: Windows 10 Pro 20H2 19042.870 
 - App version: 1.5.0.0

**Additional comment**
This problem happens after restarting the app. With other folders it didn't happens.

**Comment by gave92** [comment]
Is the folder in Details layout mode or Grid/Tiles mode?

**Comment by LorenzoSTF** [comment]
I had it on Gride/tiles mode. The app is pretty but some crashing problems and issues with the folders made me uninstall it.

**Comment by gave92** [comment]
Thanks, we are working to release a big update to Files which have this and other issues fixed (and it's quite faster).
If you wish to give the app another spin you can join the beta testing program:

> Join the insider flight group
You can fill out this form to get access to the preview builds in the Microsoft Store https://forms.office.com/r/UsaBmzC99n. It can take a couple of days until you're added to the flight group, but once added, you will start receiving updates to the regular Files app through the Microsoft Store.

**Comment by LorenzoSTF** [comment]
Another problem its that when you want to draw a file to upload it, it doesnt work
