### ISSUE TITLE
Hidden / System Files should use existing registry values from Explorer

### ISSUE THREAD

**Issue by BelowZeroLH** [files-community/Files#4473]
Why should there be SEPARATE settings for showing Hidden and System Files? This is a well-established setting in Explorer with values stored in the Registry. Pull/change existing values for universal use instead of making your own.

**Comment by yaichenbaum** [comment]
@BelowZeroLH One of the core principles of Files is that it's a modern file manager. While we technically have access to the registry, it goes against our policies as a modern app on Windows to make changes to the registry.
