### ISSUE TITLE
Files crashes on certain folders

### ISSUE THREAD

**Issue by KibSquib48** [files-community/Files#4475]
**Explain the bug**
When I enter certain folders, Files just crashes

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6266858/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6266859/debug_fulltrust.txt) (not sure which one i should put so i put both)

**System Information**
 - OS Version: Windows 10 20H2 19042.906
 - App version: v1.5.2.0

**Comment by gave92** [comment]
Merging with #4304. Please also see #4304 for possible workarounds.
