### ISSUE TITLE
Mapped Drives have wrong label

### ISSUE THREAD

**Issue by dgodfather** [files-community/Files#4477]
Mapped Drives show up as "Data" and not the name of the drive as listed in File Explorer.

https://postimg.cc/mczwZCJz

**Comment by gave92** [comment]
Files version? Could you post the log files?

**Comment by dgodfather** [comment]
V 1.3.0.0, 
[debug.zip](https://github.com/files-community/Files/files/6271731/debug.zip)

**Comment by gave92** [comment]
@dgodfather Is this still an issue in v2.0.13?

**Comment by dgodfather** [comment]
Seems that way. Nothing has changed as it is viewed from my opening reply image.
