### ISSUE TITLE
Adding Attributes (e.g Rating) to details view

### ISSUE THREAD

**Issue by gdstuart** [files-community/Files#4479]
Requesting the ability to add attributes, particularly a "Rating" column which can be used to assign Ratings to individual files (recipes, movies, etc.).

**Is your feature request related to a problem?**
This is not a problem, just a request.  I did not find the ability to add any additional attributes to the Files app.

**Describe the solution**
A Ratings attribute would be populated either as free-form text or a drop-down that would be user-populated.  The drop-down option would allow filtering.

**Describe alternatives you've considered**
Competing app XYplorer allows a Rating but the app is cumbersome.

**Additional comment**
Add any other comment or screenshots about the feature request here. What device type/UI layout and app version?

**Comment by gave92** [comment]
If you open a file properties you should be able to set a rating. This request is about to add the rating column to the details file list correct?

**Comment by gdstuart** [comment]
Yes.  The point is to list the property (and probably many others) on the
main display to enable sorting/filtering/ranking etc.

Thanks,

Geoff Stuart
4119 Nesco Rd.
Hammonton, NJ  08037
610-348-9590 cell

**Comment by gdstuart** [comment]
However, I do not see the Rating attribute you refer to.  

Geoff

**Comment by yaichenbaum** [comment]
Merging with #8366
