### ISSUE TITLE
Remove the "Cloud Storage" menu item, when there are no cloud storage services

### ISSUE THREAD

**Issue by crashmit** [files-community/Files#4485]
**Is your feature request related to a problem?**
This is a minor request, I uninstalled OneDrive and use Google Drive FS which creates a virtual drive for the files. Hence I don't have any cloud storage services in the corresponding menu item. 

![image](https://user-images.githubusercontent.com/58466626/113862187-63d2ee80-97a8-11eb-9059-9db1f20f9b6f.png)

**Describe the solution**
It would be nice, if it becomes invisible when this is the case. This is far from important, just a minor thing that buggs me.

**Describe alternatives you've considered**
Menu option to disable the menu item

**Comment by gave92** [comment]
Merging with #3912
