### ISSUE TITLE
Changing Layout Mode to List crashes Files

### ISSUE THREAD

**Issue by crashmit** [files-community/Files#4486]
**Explain the bug**
I just changed the layout mode of a folder to "List". This crashed Files and continues to do so, when I navigate to this folder. I tried "changing" from List to List (so no change at all) and this also caused this behaviour. This only happens in my virtual drive created by "Google Drive FS".

**Expected behavior**
Write a clear description of what you expected.

**Logfile**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6271379/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6271380/debug.txt)
-> Debug.txt contains things about the crash

**System Information**
Edition	Windows 10 Pro
Version	20H2
Build	19042.867
Windows Feature Experience Pack 120.2212.551.0

 - App version: 1.5.0.0

**Additional comment**
Happens again after restarting. Can't access that folder anymore through Files.

**Comment by gave92** [comment]
Thanks for this report. The only way to fix this for now is to create a new folder and copy the contents over.

**Comment by yaichenbaum** [comment]
@crashmit is this still an issue in Files v2.0?

**Comment by crashmit** [comment]
Haven't had it in quite some time, but haven't been using Files too extensively. For now, I'll close the ticket.
