### ISSUE TITLE
Some .dll file properties are not visible

### ISSUE THREAD

**Issue by WeeJeePee** [files-community/Files#4487]
**Is your feature request related to a problem?**
I would like to suggest a feature that Files is lacking over the default file explorer.
Can't see quick info when hovering a .DLL file like in the built-in file explorer nor is all info visible when viewing properties. I would love to use Files as my default but little things like this unfortunately keep it from being my default file manager as it slows down my development workflow 😔

Built in file explorer:
![image](https://user-images.githubusercontent.com/25634676/113868403-50c81a80-97b8-11eb-9161-e55d9df6d43a.png)
![image](https://user-images.githubusercontent.com/25634676/113868766-b4eade80-97b8-11eb-819a-74bbb4addb0e.png)

Files: (note how I cannot see the version number or product name)
![image](https://user-images.githubusercontent.com/25634676/113868806-bfa57380-97b8-11eb-8144-177ae336511f.png)

**Describe the solution**
I would like to see a quick view of information when hovering the item like in the default file explorer.

**Describe alternatives you've considered**
Would already help if it was possible to view these properties either in the property window or in the preview panel

**Additional comment**
Here is a NuGet Gallery link to the DLL I used as an example
[https://www.nuget.org/packages/Google.Protobuf](url)
Extract it and you see the .DLL it contains.

Also just wanna say that I absolutely adore this project! ♥

**Comment by yaira2** [comment]
@WeeJeePee does it work for you to load the details page for dll files? It looks like it crashes the app.

**Comment by yaira2** [comment]
Which properties are missing?

**Comment by WeeJeePee** [comment]
> Which properties are missing?

**Windows file explorer:**
When i hover my mouse over i see the following properties:
_file description,
company
File version
size_

When I click to see details I see these properties in file explorer:
_File description
Type
Product name
Product version
Copyright
Size
Date modified
Language
Original filename_

</br>

**Files: (Version: 2.4.25.0 OS Version: 10.0.19044.2486)**
When i hover my mouse over i see the following properties:
Name 
Type
Date modified

When I click to see details I see these properties in files:
Item Name
Item Path
Item Type
Title
Subject
Comment
Copyright
Language
File Version
Sync status
Date Created
Date Modified
Owner

Most of these properties are not really relevant to the specific file type like they are in the default file explorer.

**Comment by yaira2** [comment]
@WeeJeePee can you open a feature request for displaying the version number in the tooltip?
