### ISSUE TITLE
Files are shown but in 1 second they simply desappear

### ISSUE THREAD

**Issue by FernandoConsentino** [files-community/Files#4488]
It works well in all my drives, but when I go to "google drive", then "my drive", I can see the files in it. But in less than 1 second, the central panel make a "refresh" and the files are gone. I see just a blank screen.

**To reproduce**
1. Go to 'google drive'
2. Click on 'me drive'
3. The files are there, but in less than 1 second the central panel makes a "refresh"
4. So the files are gone and I see just a blank panel (on the central panel)

**Expected behavior**
I expect to see the files in "my drive", just it happens in all of other drives

**Logfile**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6271930/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6271931/debug.txt) 

**Screenshots**
![image](https://user-images.githubusercontent.com/82100470/113874917-a4bd0a00-978c-11eb-8668-8a77a73b02d6.png)

**System Information**
![image](https://user-images.githubusercontent.com/82100470/113875049-c0c0ab80-978c-11eb-9678-b919418ead3b.png)
![image](https://user-images.githubusercontent.com/82100470/113875136-d59d3f00-978c-11eb-83eb-fc4427e67c41.png)

I want to use Files, because is Great, but all my files are at google drive! Please help me! Thanks!

**Comment by adumat** [comment]
i have the same problem.

**Comment by samwzlim** [comment]
Same issue even on version 1.5

**Comment by samwzlim** [comment]
@yair100 This should have been fixed in version 1.5, but I am still facing the same issue in the latest version of Files. Just bring this to your attention as you might have missed it.

**Comment by gave92** [comment]
Closing this in favor of #5695 since the issue is still present on the latest beta.
