### ISSUE TITLE
The hours (duration, when present) are not displayed in the preview pane on the right.

### ISSUE THREAD

**Issue by short-int-happiness-0** [files-community/Files#4489]
**Explain the bug**
The hours (duration, when present) are not displayed in the preview pane on the right. However, they are displayed correctly on the "miniplayer" at the top of this pane.

**Screenshots**
![image](https://user-images.githubusercontent.com/49497386/113879325-b0272a00-97ba-11eb-82e1-e92553faaacb.png)

**System Information**
 - OS Version: Edizione	Windows 10 Home
                                        Versione	20H2
                                        Build OS	19042.867
                                        Windows Feature Experience Pack 120.2212.551.0
 - App version: v1.5.0.0

**Comment by winston-de** [comment]
Thanks for opening this issue. This has been fixed in #4431, and will be rolled out in the next update.
