### ISSUE TITLE
Error "App Installer failed to install package dependencies. Ask the developer for  package" when installing the Msixbundle

### ISSUE THREAD

**Issue by christubuntu** [files-community/Files#4491]
When I try the app (Mxbundle), the app tries to install some dependencies and stalls. I get error "FApp Installer failed to install package dependencies. Ask the developer for  package".
I'm connected to the Internet when trying to install.
I cant post logs since the app isn't even installing.
OS version= Windows 10 20H2 (Os build 19042-508)
App version = Files-1.5.Msixbundle
https://imgur.com/r38BzKt

**Comment by yaichenbaum** [comment]
The msix installer will only work if you have the correct dependencies installed, you can use this installer to install Files https://files-community.github.io/package.github.io/Files.Package/Files.Package.appinstaller.

**Comment by christubuntu** [comment]
I was able to fix this issue by updating some dependencies on the ms store.

**Comment by yaichenbaum** [comment]
Thanks for the update!
