### ISSUE TITLE
Add the option to open the themes folder directly from settings

### ISSUE THREAD

**Issue by Yuhtin** [files-community/Files#4492]
**Describe the solution**
A button named 'Open in folder' on right of button to select Color schema 
![image](https://media.discordapp.net/attachments/728068076289130547/829386237122576384/unknown.png)

**Why add this**
Make more easy to open the app themes folder

**Comment by merwie** [comment]
or maybe make a gui to submit themes and download themes in the app? I think I heard them discussing that

**Comment by Yuhtin** [comment]
make a gui to drag and drop themes and select one, appears more userfriendly, but, for now, one button to open folder is a better and more faster solution

**Comment by winston-de** [comment]
This is a great idea!

**Comment by XPoppyX** [comment]
It would be even better to have a color picker ui, much easier to edit colors. Would it be a lot of work?

![RegionBasePrimary_Properties](https://user-images.githubusercontent.com/61259627/113908523-a692c780-97a4-11eb-9307-01e516bce98b.png)

**Comment by Yuhtin** [comment]
> It would be even better to have a color picker ui, much easier to edit colors. Would it be a lot of work?
> 
> ![RegionBasePrimary_Properties](https://user-images.githubusercontent.com/61259627/113908523-a692c780-97a4-11eb-9307-01e516bce98b.png)

Yeah, this is better

**Comment by yaichenbaum** [comment]
@Yuhtin This issue should be resolved with #4498.
