### ISSUE TITLE
Extremely slow opening context menu

### ISSUE THREAD

**Issue by BlackBeltPanda** [files-community/Files#4496]
**Explain the bug**
When opening a directory, right-clicking takes a couple seconds for the context menu to load.

**To reproduce**
1. Open directory
2. Right-click to open context menu
3. Context menu takes a couple seconds to appear

**Expected behavior**
Context menu should have no delay.

**Logfile**
[debug (1).txt](https://github.com/files-community/Files/files/6273605/debug.1.txt)

**Screenshots**
Hard to tell in the .gif, but when the cursor stops moving is when I right-clicked. 
![3ac13ff2dfd7a579ecb9c3da741b7427](https://user-images.githubusercontent.com/5866087/113912658-66821380-97a9-11eb-8ba8-39eb8eb5d10f.gif)

**System Information**
 - OS Version: Windows 10 Pro 2004 19041.867
 - App version: 1.5.0.0

**Comment by gave92** [comment]
Merging with #2527
