### ISSUE TITLE
After renaming/editing files in WSL I need to manually refresh Files

### ISSUE THREAD

**Issue by stevenbrix** [files-community/Files#4497]
**Explain the bug**
When I make a change to a file in my WSL instance (say, do a rename or copy/paste) it doesn't look like anything happened. I have to refresh the view to see the changes take effect.

**To reproduce**
1. Go to any file in a WSL distro
2. Right click and select "Rename" and rename the file
3. See that the filename hasn't changed

**Expected behavior**
I would expect to see the changed filename

**Logfile**

[debug_fulltrust.txt](https://github.com/files-community/Files/files/6273622/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6273623/debug.txt)

**Screenshots**
N/A

**System Information**
 - OS Version: [e.g. Windows 10 20H2 19042.804] (Press WIN + PAUSE/BREAK, use the copy button at the bottom)
 - Edition	Windows 10 Enterprise
Version	Dev
Installed on	‎4/‎6/‎2021
OS build	21354.1
Serial number	003798101557
Experience	Windows 10 Feature Experience Pack 321.7601.0.3

 - App version: [e.g. v1.0] (In the app, go to Settings -> About, the version is shown at the top)
1.5.0.0

**Additional comment**
It happens after restarting the app

**Comment by gave92** [comment]
Merging with #2542.
