### ISSUE TITLE
Feature: Improve support for compressing and decompressing archives

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#45]
- [ ] #9947
- [ ] Keep timestamps from the .zip file
- [x] Extract files
- [x] Menu options to extract items quickly without the use of the dialog
- [x] #9948
- [x] When pasting a file into an archive the file is fully currently loaded into memory first (bad)
- [x] "Extract" command on toolbar when an archive is selected or being browsed #7639
- [x] 7zip & other formats support (requires switching to SharpCompress or something)
- [x] Specific icon to show when zip files are associated with Files?
- [ ] Add shell extensions to File Explorer
- [ ] Add dedicated progress view when using shell extensions in File Explorer
- [ ] #9949
- [x] 7z
- [ ] gz
- [x] tar
- [x] rar
- [x] zip
- [ ] lzma
- [ ] lzh
- [ ] arj
- [ ] bz2
- [ ] cab
- [ ] chm
- [ ] deb
- [ ] iso (known to have issues with files displaying)
- [ ] rpm
- [ ] wim
- [ ] udf
- [ ] mub
- [ ] xar
- [ ] hfs
- [ ] dmg
- [ ] Z
- [ ] xz
- [ ] flv
- [ ] swf
- [ ] exe
- [ ] dll
- [ ] vhd
- [x] msix
- [x] appx

**Comment by yaichenbaum** [comment]
Take a look at https://github.com/adamhathcock/sharpcompress

**Comment by szaimen** [comment]
Maybe also looking inside zip files and opening files from there should be supported?
(it is working like that currently in the file explorer)

**Comment by ChihweiLHBird** [comment]
Why not just use https://docs.microsoft.com/en-us/dotnet/api/system.io.compression.zipfile?view=netcore-3.1 ?

**Comment by chuchanpr** [comment]
This is a recommend to be added to Files UWP, when possible

**Comment by Jaiganeshkumaran** [comment]
@ChihweiLHBird Using System.IO will make it slower because UWP apps have limited access and you need to use StorageItems to get them. Instead we can use the native API: https://docs.microsoft.com/en-us/uwp/api/Windows.Storage.Compression?view=winrt-19041

**Comment by duke7553** [comment]
@Jaiganeshkumaran Does the native API support folder items? In my analysis, it appears support for that is lacking, but I'm still unsure.

**Comment by Jaiganeshkumaran** [comment]
@duke7553 It seems to not support by default but System.IO should be sufficient

**Comment by VelocityDesign** [comment]
Please add this. It really annoys me when File Explorer opens because I double click on a .Zip file. If the team implements this, I would like them to add support for XZ, BZIP2, GZIP, and TAR.

**Comment by mdtauk** [comment]
> Maybe also looking inside zip files and opening files from there should be supported?
> (it is working like that currently in the file explorer)
> 
> BTW: extracting should imo always result in creating a folder with the same name like the zip file inside the directory and putting the content into this newly created folder.
> (file explorer is doing this as well)

I happen to use 7zip, and that gives me the option to choose how I extract an archive.
![image](https://user-images.githubusercontent.com/7389110/104385448-27864e00-552b-11eb-94f3-e1c5ade3dc8c.png)

**Comment by d2dyno1** [comment]
Hmmm

**Comment by yaichenbaum** [comment]
@d2dyno1 Do you want to work on this? We will probably want to use 7zip or something similar to power the feature.

**Comment by d2dyno1** [comment]
> @d2dyno1 Do you want to work on this? We will probably want to use 7zip or something similar to power the feature.

@yaichenbaum This is not possible with current state of Files' codebase. I'll focus on this particular codebase first before taking any action on this feature request.

**Comment by d2dyno1** [comment]
@ChihweiLHBird I'm very busy this month. Feel free to start initial work on this if you want :)

**Comment by yaichenbaum** [comment]
> I think we can implement zip and unzip functions with System.IO.Compression first. Any plan to start working on that?

@ChihweiLHBird We used that in the original implementation, but we weren't very happy with the results. Because of this, we decided to base the feature off an alternative such as the shell dialog (with a custom UI), or a custom UI for 7zip.

**Comment by tobiegsmusc** [comment]
>     * [ ]  Menu options to extract items quickly without the use of the dialog
Hello is it possible just like 7-Zip by default to keep the 3 timestamps from the .zip file: Modified, Created and Accessed when extracting for folders and files?

**Comment by josh-65** [comment]
https://www.7-zip.org/sdk.html
Don't know if this would help but 7zip has an SDK and from what I can see they support C# and it gives access to 7zip compressing and decompressing (maybe viewing too) of many archive types.

**Comment by d2dyno1** [comment]
Not working on all of the issues but can work on some of them.

**Comment by wise-gorilla** [comment]
I think it would be great if it was possible to use those libraries instead of 7zip
https://github.com/mcmilk/7-Zip-zstd
https://github.com/jinfeihan57/p7zip

**Comment by Josh-65** [comment]
Could support be added for .mcpack. its just a zip file renamed for Minecraft's use

**Comment by Josh-65** [comment]
GitHub doesn't support uploading it but you can just change the .zip to .mcpack
[zResourcePackBedrock.zip](https://github.com/files-community/Files/files/9418569/zResourcePackBedrock.zip)

**Comment by Josh-65** [comment]
.jar file could also have viewing/editing support they use zip for it compresion.
