### ISSUE TITLE
Opening new tab should keep you on current tab

### ISSUE THREAD

**Issue by meowish** [files-community/Files#4506]
**Describe the solution**
Opening a new tab should not automatically move you to the new tab, and should keep you on the current one.

**Comment by cinqmilleans** [comment]
I agree. I can take care of the community accept this change.

**Comment by yaichenbaum** [comment]
@cinqmilleans That would be great! Let's continue tracking this in #2512.

**Comment by cinqmilleans** [comment]
yaichenbaum, meowish and myself wished it in issue # 4506. Most software with tabs works this way, so it's more intuitive for the user. If we need the folder right away, we open it in the current tab. If it's for later, you open it in a pending tab. You can open multiple subfolders in tabs easily.
