### ISSUE TITLE
Have files as the default windows file explorer 

### ISSUE THREAD

**Issue by meowish** [files-community/Files#4507]
**Is your feature request related to a problem?**
Opening desktop folders does not use Files, would like to have Files as the default windows file explorer.

**Describe the solution**
Add the ability to have Files as the default windows explorer.
Files should automatically open folders on the computer.
Files should be automatically used by software that use windows explorer.

**Describe alternatives you've considered**
Have my desktop empty and use Files exclusively.

**Comment by gave92** [comment]
You can follow the method explained here: https://files-community.github.io/docs/#/articles/replace-file-explorer

**Comment by meowish** [comment]
Thank you very much!

**Comment by cinqmilleans** [comment]
We could add a button in the settings to automatically set/unset it as a default.
Or offer a popup when opening to suggest it (yes / no / no longer ask).
