### ISSUE TITLE
Use CTRL + Left click for new tab

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#4511]
**Is your feature request related to a problem?**
In most software, you can open a new tab with middle click or ctrl + left click.
The second option is not available in Files.
This is however useful when the mouse does not have a middle button.

**Describe the solution**
Implement ctrl + left click to open new tab.

**Additional comment**
I can implement it.

**Comment by yaichenbaum** [comment]
@cinqmilleans That would be great!

**Comment by kiikoh** [comment]
I agree this needs to be there, as well as middle clicking

**Comment by yaichenbaum** [comment]
@cinqmilleans We don't have plans to go through with this for regular folders. However, we still plan to do this for the sidebar.

**Comment by cinqmilleans** [comment]
@yair100 I hadn't done it because there were bugs with the libraries. These bugs seem to have been fixed. I will create a pr today after further testing.
