### ISSUE TITLE
when creating a new file, the .docx needs to be introduced manually

### ISSUE THREAD

**Issue by baldaiacharles** [files-community/Files#4514]
When creating a document by right click > new > word. 
![image](https://user-images.githubusercontent.com/70418775/114066993-b082fc00-9872-11eb-825b-a4a2dbb92850.png)

the documente created doesn't come with a .docx at the end of it, so it stays like this:
![image](https://user-images.githubusercontent.com/70418775/114067147-dc05e680-9872-11eb-8cfd-e01ae95042f6.png)

being needed to manually write .docx at the end of it, so the problems get fixed 
![image](https://user-images.githubusercontent.com/70418775/114067250-fc35a580-9872-11eb-92a0-a0aaac64cbd8.png)

the same happen the other types of files

**Comment by winston-de** [comment]
Thanks for opening this issue, this has been fixed in #4190.
