### ISSUE TITLE
Replacing an existing folder does not merge its content

### ISSUE THREAD

**Issue by ItaloCunhaBueno** [files-community/Files#4520]
**Explain the bug**

> If you try to cut or copy a folder with files inside, to a location that already has a folder with same name, Files gives 2 options, replace or paste with another name. If you choose to replace, it actually replaces the folder instead of merge, destroying everything that was in the replaced folder.

 
**Expected behavior**

> It's expected that Files merge the two folders with same name, resulting in a folder with both original folder's files inside, just like File Explorer does.

**System Information**

> Edição	Windows 10 Pro
> Versão	20H2
> Instalado em	‎22/‎12/‎2020
> Compilação do SO	19042.906
> Experiência	Windows Feature Experience Pack 120.2212.551.0

>  App version: 1.5.0.0

**Comment by winston-de** [comment]
Thanks for opening this, merging with #3958
