### ISSUE TITLE
Clicking outside filename box when renaming a file cancels the action.

### ISSUE THREAD

**Issue by ItaloCunhaBueno** [files-community/Files#4521]
**Explain the bug**

> If you double click a file to rename it (or right click and choose rename), write the new name, and than click outside the name box to finalize the action, it cancels the action and the original name returns. It only rename if you hit enter. File Explorer rename the file when you click outside the name box.

**Expected behavior**

> The expected behavior is to Files rename the file even if you do not hit enter (as File Explorer does)

**System Information**

> Edição	Windows 10 Pro
> Versão	20H2
> Instalado em	‎22/‎12/‎2020
> Compilação do SO	19042.906
> Experiência	Windows Feature Experience Pack 120.2212.551.0
> App version: 1.5.0.0

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
