### ISSUE TITLE
Error mounting Hyper-V drive

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#4529]
**Explain the bug**
When I try to mount a Hyper-V virtual disk get an error mounting message.

**To reproduce**
1. Go to Hyper-V virtual disk
2. Right click
3. Click mount
4. Give admin privileges
5. Hear error sound

**Expected behaviour**
It should show up as a normal drive

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6287007/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6287008/debug_fulltrust.txt)

**Screenshot**
![image](https://user-images.githubusercontent.com/26977075/114207181-01b6ec80-9954-11eb-8c41-c9bef0efb6f6.png)

**System Information**
 - OS Version: Windows 10 20H2 19042.906
 - App version: v1.5.2.0

**Comment by gave92** [comment]
Merging with #3490
