### ISSUE TITLE
Colour schemes are not working

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#4533]
**Explain the bug**
When I try colour schemes from the themes repository they don't change anything when I apply and restart the app. The restart message also shows it as a language change.

**Expected behaviour**
The colour scheme is apply and changes the look of the app,

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6288937/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6288939/debug_fulltrust.txt)

**System Information**
 - OS Version: Windows 10 20H2 19042.906
 - App version: v1.5.2.0

**Comment by yaichenbaum** [comment]
@josh-65 Some themes only have brushes for light or dark mode, can you see if switching the theme solves the issue?

**Comment by josh-65** [comment]
i have try multiple themes file in both light and dark mode I don't see any change however I'm not sure what there support to change to look.

**Comment by yaichenbaum** [comment]
@josh-65 Which themes did you try?

**Comment by josh-65** [comment]
blackpixel, discord purple, midnight, lavender

**Comment by yaichenbaum** [comment]
@josh-65 Can you try black pixel and lavender again?

**Comment by josh-65** [comment]
I tried them nothing changed in dark or light mode even after a restart between them.

**Comment by yaichenbaum** [comment]
@josh-65 Can you upload the theme files you tested with?

**Comment by josh-65** [comment]
These are unmodified versions from the themes repository
[Themes.zip](https://github.com/files-community/Files/files/6291950/Themes.zip)

**Comment by yaichenbaum** [comment]
@josh-65 Can you try black pixel and lavender again (you need to download the latest version)?

**Comment by josh-65** [comment]
where are they i downloaded them from the themes repository when you ask me to re try them

**Comment by josh-65** [comment]
just did it again to make sure and there's no change

**Comment by yaichenbaum** [comment]
I just realized lavender wasn't fixed at that time, can you download it again?

**Comment by josh-65** [comment]
sure can i ask what there suppose to change/look like so i know what to look for

**Comment by josh-65** [comment]
There working now. Here a suggestion though add a override app theme option. Since the themes may only work with one and make the app look broken if not set correctly.

**Comment by yaichenbaum** [comment]
@josh-65 Moving forward, we are going to require that custom themes include brushes for all themes.
