### ISSUE TITLE
[Feature Request] Option for App theme: Scheduled Change between Light and Dark themes

### ISSUE THREAD

**Issue by kimlimjustin** [files-community/Files#4535]
**Describe the solution**
Inspired by Zorin OS Appearance, it'd be nice if there's a scheduled switching between themes option, which is described as follows: 
- From Sunrise to Sunset (around 6:30 am to 6:30 pm), Files use the Light theme
- From Sunset to Sunrise (around 6:30 pm to 6:30 am), Files use the Dark theme

**Describe alternatives you've considered**
User input the time which Files use Light theme and Files use Dark theme.

**Comment by gave92** [comment]
I think any method to change the windows theme (e.g. [this](https://www.windowscentral.com/how-automatically-switch-dark-mode-night-time-windows-10) affects Files as well. I'm not sure about having a separate option just for Files.

**Comment by SOI7** [comment]
> I think any method to change the windows theme (e.g. [this](https://www.windowscentral.com/how-automatically-switch-dark-mode-night-time-windows-10)) affects Files as well. I'm not sure about having a separate option just for Files.

Yup, that's what I use

**Comment by kimlimjustin** [comment]
> I think any method to change the windows theme (e.g. [this](https://www.windowscentral.com/how-automatically-switch-dark-mode-night-time-windows-10)) affects Files as well. I'm not sure about having a separate option just for Files.

I know this method but for other users who only need this option for Files, it might very bothering.  If Files implement this separately, it would be better tho :) Just my two cents.

**Comment by yaichenbaum** [comment]
@kimlimjustin Can you provide your use case where you would only want this for Files vs the whole system?

**Comment by kimlimjustin** [comment]
> @kimlimjustin Can you provide your use case where you would only want this for Files vs the whole system?

Both Light theme and Dark theme in Files looks good, However, if you make this in the whole system, it will also affects some other applications (which are only looks good in single theme, dark theme for instance) tho... Anyway, this is just my suggestion...

**Comment by yaichenbaum** [comment]
@kimlimjustin We'll keep this open for a discussion for now.

**Comment by kimlimjustin** [comment]
> @kimlimjustin We'll keep this open for a discussion for now.

Okay thanks!

**Comment by yaichenbaum** [comment]
@kimlimjustin while there are valid use cases for such an option, we've decided not to implement a built-in option for auto changing the theme in Files.
