### ISSUE TITLE
Have an option to show tasks (delete or copy) in native windows instead of integrated tasks 

### ISSUE THREAD

**Issue by AhmadHddad** [files-community/Files#4537]
It would really help if I can choose between integrated tasks or default windows or even any other copying program I choose.
In my case, I am using TeraCopy, and I can't use it while using Files,

Please consider this feature.

**Comment by yaichenbaum** [comment]
We don't have plans to make this change however, if there are any ways you think we can improve the copy/detete experience, please let us know in seperate issues 🙂
