### ISSUE TITLE
Crash while doing specific things

### ISSUE THREAD

**Issue by GiornoJJ** [files-community/Files#4544]
I will get straight to the point. I was deleting 31 videos of a total size of around 15gb and right after deleting I got a notification that the app crashed due to an unknown issue or something of that sort. Another instance was keeping the app idle, after around 20 mins of the app being idle it stops responding and crashes soon after

App version - 1.5.0.0

**Comment by gave92** [comment]
@GiornoJJ thanks for the report. Please upload the debug files.

**Comment by GiornoJJ** [comment]
> @GiornoJJ thanks for the report. Please upload the debug files.

[debug.txt](https://github.com/files-community/Files/files/6291357/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6291358/debug_fulltrust.txt)

Are these the files?

**Comment by yaichenbaum** [comment]
@GiornoJJ thanks! Is this still an issue in v2.0.34?
