### ISSUE TITLE
Perfomance problems

### ISSUE THREAD

**Issue by Guardian820** [files-community/Files#4545]
**Files has a heavy perfomance problem:**
When you have so many archives in a folder, you already had a problem because these archives take some long time (is a heavy process) to be read, the navigation and preview of these archives is perfect, but the selection between one archive and other archive is like the application go to crash.

**To reproduce**
1. Create a folder with 10,000 archives inside (for example a folder with 10.000 PNG/JPG images)
2. Select an archive and then try to select another.

**Screenshots**
I dont have screenshots, but I can upload two comparative videos.

**USING FILES:**
https://youtu.be/DKd0QxPnkyE
**USING EXPLORER:**
https://youtu.be/YCjMxgpWcx8

**System Information**
Edition	Windows 10 Pro
Version	20H2
Installed on	‎4/‎7/‎2021
OS build	19042.867
Experience	Windows Feature Experience Pack 120.2212.551.0

 App version: 1.5.0.0

**Additional comment**
The application seems to crash when it needs to load a new info between archives.

**Comment by winston-de** [comment]
Thanks for the feedback, merging with #4180.

**Comment by yair100** [comment]
@Guardian820 we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
