### ISSUE TITLE
Files window is not maximized from taskbar after setting background image from MS Photos app

### ISSUE THREAD

**Issue by militaryCoder** [files-community/Files#4546]
### Bug Explanation

After changing background image while Files application is open (especially through MS Photos application), if it was hidden it stops opening from taskbar.

### Steps to reproduce

1. Open Files app.
2. Open any image through MS Photos application and set image up as background image.
3. Minimize Files window to taskbar.
4. Try to open it again by clicking it's taskbar shortcut.
5. Here we are.

### Expected behavior

Of course Files app should appear on the screen again after clicking it's taskbar shortcut.

### Debug info
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6291590/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6291591/debug.txt)

### System Info
 - OS Version: Windows 10 Pro, version 20H2, OS build 19042.867, additional: Windows Feature Experience Pack 120.2212.551.0
 - App version: v1.5.0.0

**Comment by yaichenbaum** [comment]
@militaryCoder is this still an issue in v2.0.34?

**Comment by nullptr-deref** [comment]
@yair100, no, it isn't.
