### ISSUE TITLE
keyboard shortcut: select All Files in Directory

### ISSUE THREAD

**Issue by danielUCM** [files-community/Files#4547]
**Is your feature request related to a problem?**
In Windows File Explorer, all files in a directory are selected with the keyboard shortcut: SHIFT + END. 
In Files: SHIFT + CTRL + END

**solution**
Both alternatives would be fine.

**Additional comment**

![selectAllFiles](https://user-images.githubusercontent.com/45082598/114301896-f6d09900-9ac6-11eb-80e5-50f04161ddbe.PNG)

**Comment by gave92** [comment]
Does Ctrl+A work?

**Comment by cinqmilleans** [comment]
No. in Windows File Explorer, Shift + end selects from current item to last item.
ctrl + a selects all items from directory.

**Comment by danielUCM** [comment]
> Does Ctrl+A work?
Very good, thanks!. I didn´t know.

> No. in Windows File Explorer, Shift + end selects from current item to last item.
> ctrl + a selects all items from directory.
Sorry, I didn´t explain myself correctly. But I think you understood what I was referring to.

For some reason CTRL+A in my windows file explorer doesn't work =(
In Files, yes =)

**Comment by voiiden** [comment]
Ctrl + Shift + Down arrow does the trick.
