### ISSUE TITLE
App suddenly close when you are navigating between folders

### ISSUE THREAD

**Issue by lettucemarcvel** [files-community/Files#4551]
**Explain the bug**
Open de app go to Documents and start to navigate between my folders and the app suddenly closes. No specific action or folder.

**To reproduce**
1. Go to your documents that have saved in the C: and start to navigate. 

**Expected behavior**
Do not close the app

**Logfile**

[debug_fulltrust.txt](https://github.com/files-community/Files/files/6292073/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6292074/debug.txt)

**Screenshots**
NA

**System Information**
 - OS Version: Windows 10.0.19042
 - App version: 1.5.2.0

**Additional comment**
Add any other comment about the problem here. Does this problem happen again after restarting the app?

**Comment by gave92** [comment]
Probably same issue as #4304, happens more or less frequently to most users. Less likely in GridView, less likely with cache turned off.

**Comment by gave92** [comment]
This should be resolved in main
