### ISSUE TITLE
Window in BackGround when Extracting zip files

### ISSUE THREAD

**Issue by tozzy2012** [files-community/Files#4554]
Hi. First, congratz for the awesome app!!! 

Whenever you have a zip file, when you right click and click on "extract all"  (extrair tudo, in portuguese), the confirmation windows is on background. You have to go to your taskbar, bring it to the front, and then confirm the operation. 

Would be awesome if you could bring that window to the front.

**Comment by yaichenbaum** [comment]
@tozzy2012 Thanks for opening this issue, we are tracking it in #985. Make sure to subscribe to the issue to be notified when it's resolved.
