### ISSUE TITLE
.exe , .rar and .zip files don't open!

### ISSUE THREAD

**Issue by marcio126** [files-community/Files#4555]
_**Yesterday, April 10, 2021**_ I discovered his software Files, but today I decided to test it and realized that by double-clicking on an **.exe**, **.zip**, or **.rar** file, it just doesn't open the file! and I realized that using standard windows file explorer it opens normally.
I also already clicked with the right mouse button and then on Open, but it had the same problem, it didn't open!
I would like to know why this happens, I do not know what the solution would be but I expect an answer!

**Comment by josh-65** [comment]
Try re installing files. If that doesn't work upload the logs from settings > about > open logs folder.
