### ISSUE TITLE
Drive sizes are not refreshable

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#4556]
**Explain the bug**
The drive amount of space free doesn't update when clicking the home button or f5 and the refresh is greyed out. I have to close and reopen files to see the current correct size.

**Expected behaviour**
The refresh function should be enabled on the home page to update the drive sizes.

**System Information**
 - OS Version: Windows 10 20H2 19042.906
 - App version: v1.5.2.0

**Comment by gave92** [comment]
Merging with #2242
