### ISSUE TITLE
Google Drive Desktop App (not Backup and Sync) does not show in Cloud Storage

### ISSUE THREAD

**Issue by NoraTheGamer** [files-community/Files#4557]
**Is your feature request related to a problem?**
This is not a problem just a feature request

**Describe the solution**
I want Google Drive to show up under the cloud storage tab.

**Describe alternatives you've considered**
There is really no other alternatives

**Comment by gave92** [comment]
Doesn't this app add a virtual drive? It should appear in the drives section in Files

**Comment by NoraTheGamer** [comment]
It appears in the Drives tag. It normally adds itself as the G Drive named Google Drive by default. Maybe just add to cloud drives if name = Google Drive

**Comment by jrmoynihan** [comment]
Same issue, but with OneDrive.  Doesn't appear at all in the sidebar.

**Comment by gave92** [comment]
#5690
