### ISSUE TITLE
Move/Copy File or Folder without Selection

### ISSUE THREAD

**Issue by CreepyCat225** [files-community/Files#4560]
**Is your feature request related to a problem?**
Immediately trying to drag a file/folder without putting it in the "Selected" state (AKA Left-Click to make it colored) doesn't allow me to drag and drop the file/folder into another place unless I Left-Click it first then drag, in the official File Explorer app I can Immediately drag an item on top of another folder or to another app without having to Left-Click it first.

**Describe the solution**
Original File Explorer like functionality where I can drag a file such as a picture without having to Left-Click the file to select it first and then dragging, or just an option in settings to turn on such functionality.

**Describe alternatives you've considered**
I CAN Left-Click then drag the file but it really slows down my workflow since I drag and drop a lot of pictures into photoshop and into and out of other folders.

**Additional comment**
Here are some Gifs to Demonstrate:

Here is how it currently is where I have to select before dragging

![Files Functionality](https://user-images.githubusercontent.com/66734989/114323649-d3413900-9b2e-11eb-983b-8684fce34598.gif)

And Here is how I would like it to be where I can freely drag without selecting, This is shown in File Explorer

![File Explorer Functionality](https://user-images.githubusercontent.com/66734989/114323504-32527e00-9b2e-11eb-94f9-7e28c9af039c.gif)

**Comment by winston-de** [comment]
Thanks for opening this, merging with #673
