### ISSUE TITLE
Application Shuts Down Unexpectedly and Freezes Machine

### ISSUE THREAD

**Issue by radascuta** [files-community/Files#4561]
**Explain the bug**
The app shuts down and sometimes it freezes the computer after opening a folder

**To reproduce**
1. Go to any folder
2. Click on any subfolder
3. The folder update bar runs for a while
4. The application disapears or freezes

**Expected behavior**
I expected the folders and files to open normally, not to freeze or disappear

**Logfile**
Upload the log file here for us to understand your issue better. 
- You can access it from Settings->About->Open log location. 
or 
- Copy the debug.log and debug_fulltrust.log from the following directory, and upload the files here.
`%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 

(see attached log files)

**Screenshots**
See this video linked here: https://1drv.ms/v/s!AoKFMAGNHJLhhKlIBOFUpfQcZGIK3g. 

**System Information**
 - OS Version: Windows 10 Version	10.0.19042 Build 19042
 - App version: Files 1.5.0.0
[debug.txt](https://github.com/files-community/Files/files/6293255/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6293256/debug_fulltrust.txt)

**Additional comment**
It looks like after one folder is accessed a couple of times, then accessing that folder is not a problem. But then accessing another subfolder makes the app freeze again. Once the whole computer froze and I had to jump start it.

**Comment by gave92** [comment]
Likely same as #4304. Please see there for a couple of suggestion that should reduce the issue.

**Comment by radascuta** [comment]
The application shuts down every time it tries to open a file in OneDrive that is not downloaded to the local disk. This can be easily verified, it's 100% the case.

**Comment by gave92** [comment]
Have you tried the suggestions in #4304?

In particular:
1. Turn Off "Enable individual preferences for individual directories" in Settings > Files and Folders
2. Set Tiles or GridView layout mode
3. Disable these two settings (turn off caching) under Experimental

![image](https://user-images.githubusercontent.com/9673091/110851026-ce2f6680-82b0-11eb-8974-599e144ff399.png)

**Comment by gave92** [comment]
> tries to open a file in OneDrive that is not downloaded to the local disk

Is the issue when opening a file or a folder?

**Comment by gave92** [comment]
Thanks @josh-65 indeed we haven't got any reports of this on Files v2
