### ISSUE TITLE
Moving files from explorer to Files does not work

### ISSUE THREAD

**Issue by Ni4ellas** [files-community/Files#4564]
** Explain the bug **
Objects are not moved by pressing the bindings ctrl + c, ctrl + x, ctrl + v.

** Expected behavior **
Moving an object.

** Logfile **
https://www.upload.ee/files/13047326/debug.zip.html

** Screenshots **
https://youtu.be/i-KjIr4ybAE

** System Information **
  - OS Version: [Windows 10 20H2 19042.746]
  - App version: [. v1.5.0.0]

** Additional comment **
The problem persists after restarting the application and the computer itself

**Comment by gave92** [comment]
Does copy pasting using the context menu work? 
Sometimes shortcuts do not work and closing and reopening the app a couple of times should fix it.

**Comment by cinqmilleans** [comment]
The copy/move does not always work with keyboard shortcuts or drag/drop.
It works with the menu. I will look to correct this.

**Comment by Ni4ellas** [comment]
> Does copy pasting using the context menu work?
> Sometimes keyboard shortcuts do not work and closing and reopening the app a couple of times should fix it.

in the video I clearly showed that even through the context menu moving does not work

**Comment by etadzeta** [comment]
I see the same behavior (files are not moved) using keyboard bindings `ctrl + c`, `ctrl + x`, `ctrl + v`

**Comment by Ni4ellas** [comment]
I want to add that this problem occurs when transferring files inside the "Files" explorer itself"

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?
