### ISSUE TITLE
Add default layout option

### ISSUE THREAD

**Issue by michelebiancucci** [files-community/Files#4565]
**Is your feature request related to a problem?**
no

**Describe the solution**
Add option to settings menu to choose an default layout mode for all folders.

**Describe alternatives you've considered**
-

**Additional comment**
Using Files 1.5.2.0 on Win 10 (OS Build 19042.844)

**Comment by gave92** [comment]
@d2dyno1 does setting a default layout make sense with the adaptive layout feature?

**Comment by gave92** [comment]
@michelebiancucci you can set a default layout for all folder by turning off "Enable individual preferences for folders" options in Files settings

**Comment by yaichenbaum** [comment]
@gave92 I am pretty sure the default is already the details view.

**Comment by michelebiancucci** [comment]
Thank you. Much appreciated.
