### ISSUE TITLE
New instance of FilesFullTrust.exe started every time Files is opened

### ISSUE THREAD

**Issue by BlackBeltPanda** [files-community/Files#4572]
**Explain the bug**
Whenever I open Files, a new instance of FilesFullTrust.exe is created and when I close Files, the process remains running. After a few days, I had somewhere around 75-100 instances of FilesFullTrust.exe running at once, eating up a large amount of system memory.

**To reproduce**
1. Start Files
2. Close Files
3. Repeat
4. View running processes in Task Manager

**Expected behavior**
Files should not create a new instance each time or it should end the process when closed.

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6299682/debug.txt)

**Screenshots**
After opening/closing Files a few times:
![image](https://user-images.githubusercontent.com/5866087/114458908-d596a800-9bad-11eb-9f58-c785e6818284.png)

**System Information**
 - OS Version: Windows 10 Pro 1909 18363.1082
 - App version: 1.5.0.0

**Comment by yaichenbaum** [comment]
@gave92 This issue has been resolved in `main`, right?

**Comment by gave92** [comment]
@yair100 yeah should be.
