### ISSUE TITLE
Files not saving default app for music files

### ISSUE THREAD

**Issue by randellgreer** [files-community/Files#4579]
**Explain the bug**
Default app for FLAC files is set up for Foobar2000 in Windows 10.  When double-click on FLAC file in Windows Explorer Foobar2000 opens as expected.  When double-click on FLAC file in Files a window pops up for user to select what app to use, even after selecting Foobar2000 multiple times and clicking the "Always use this app" box.

**To reproduce**
1. Go to any folder containing FLAC music files
2. Double-click on FLAC music file
3. "How do you want to open this file" window pops up

**Expected behavior**
Foobar2000 should launch and start playing the FLAC music file

**Screenshots**
Screenshot attached
![Files_Screenshot](https://user-images.githubusercontent.com/82454331/114561266-6a93b280-9c3b-11eb-8d11-f5813358c368.jpg)

**System Information**
 - OS Version: Windows 10 20H2 19042.906
 - App version: v1.5.0.0

**Additional comment**
Does this problem happen again after restarting the app?  YES

**Comment by winston-de** [comment]
Thanks for reporting this. Default apps is handled by Windows, not by Files, please file a bug report for this issue in the [Feedback Hub](https://aka.ms/feedbackhub).
