### ISSUE TITLE
When the preview pane is open, PDFs cannot be deleted because they are being "used by another application"

### ISSUE THREAD

**Issue by WolfIcefang** [files-community/Files#4582]
**Explain the bug**
When I try to delete a PDF while the preview pane is open, I get the error message:
"File in use"
"The file you're trying to delete is currently being used by an another application."
(side note, that's a typo, it shouldn't say "by an another", it should just say "by another"... ANYWAY! Moving on.) I do not have the PDF open anywhere else, and if I close the Preview Panel, I can delete the PDF file like normal.

**To reproduce**
1. Go to a folder containing a PDF you want to delete. (We'll be permanently deleting this file later, so choose something you really do not care about.)
2. Click on the Toggle the Preview Pane button to open the preview pane, if it is not already open.
3. Left click to select the PDF file and hit the delete key, or right click on the PDF to open the context menu and choose delete. Either way, the PDF file will be selected and a preview will be loaded in the preview pane.
4. You will see the first pop-up: "Delete item(s)  Are you sure you want to delete this item? [  ] Permanently delete   [Delete]  [Cancel].
5. If you choose delete, you will get the error message: "File is in use  The file you're trying to delete is currently being used by an another application".
6. Click OK, then close the preview pane.
7. Try deleting the PDF again. It might still give you the File is in use error message, this is likely due to the preview pane still existing in the background, or something, IDK. Keep trying until you successfully delete the file.
8. After the file is gone, hit Ctrl+Z to bring it back.
9. Re-open the preview pane.
10. Attempt to delete the file one last time, but this time, check the "Permanently Delete" check box.
11. The PDF file should be permanently deleted, even though the Preview Pane is open.

**Expected behavior**
I expect PDFs to be deleted when I try to delete them, even if the Preview pane is open. Files will delete other types of documents, even while showing a preview, but to avoid issues with other formats in the future, it might be a good idea for the app to deactivate the preview before attempting to delete anything, regardless of file type.

**Logfile**
Here are some log files, I guess.
[debug.txt](https://github.com/files-community/Files/files/6304747/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6304748/debug_fulltrust.txt)

**Screenshots**
Add screenshots to help explain your problem if needed. (not needed)

**System Information**
 - OS Version:
Edition	Windows 10 Home
Version	20H2
Installed on	‎2020-‎10-‎11
OS build	19042.906
Experience	Windows Feature Experience Pack 120.2212.551.0

 - App version: 1.5.2.0

**Additional comment**
I've had this problem fairly consistently through multiple PC restarts and regardless of whether I am in the PDF's folder or seeing a list of files from a search. I've had this issue for a while, but I also have a habit of legitimately leaving PDFs open while trying to delete them, so I cannot give a definite answer as to when the issue started.

**Comment by winston-de** [comment]
Thanks for filing this issue.
Are you able to delete the PDF once it has finished loading the preview (when the loading bar at the bottom has disappeared)?

**Comment by WolfIcefang** [comment]
I have had a bit more experience while paying attention now, and have seen a few instances where I am able to delete a PDF while the preview pane is open. However, I have not been able to figure out what allows this to happen. To say it another way, and avoid ambiguity:
The preview pane must be open (or have very recently closed) for the "file open elsewhere" error to occur, however, sometimes the PDF can be deleted even if the preview pane is open. I get the error message far more often than not.
I have not found any correlation with letting the preview fully load; I can count to 100 after the loading bar has vanished and the error will still appear.
I have noticed a few other things, that might help diagnose the issue:
You can scroll up and down in the preview of multi-page PDFs! (that's neat!)
If the first page of a multi-page PDF finishes loading, the loading bar will disappear but will reappear if you scroll down to view the other pages. (that's less neat.)
The other pages of a multi-page PDF will not start to load until you mouse over the PDF for the first time. I know this because the scroll bar in the preview pane will shrink as pages get loaded in.

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
