### ISSUE TITLE
The right-click menu becomes very dark 

### ISSUE THREAD

**Issue by glike1** [files-community/Files#4598]
**The right-click menu becomes very dark **
![image](https://user-images.githubusercontent.com/70507345/114719078-4209d680-9d69-11eb-9208-e9ab13606838.png)

Thanks for watching my report !

**Comment by yaichenbaum** [comment]
@chingucoding Is there any way we can fix this, or is it a WinUI issue?

**Comment by winston-de** [comment]
I remember seeing a PR that fixed this in the WinUI repo, I'll see if I can find it.

**Comment by marcelwgn** [comment]
@yair100 @winston-de This is a theme shadow bug on light theme, that's almost certainly a WinUI issue since this has been reported/known there before.
