### ISSUE TITLE
Invalid filename on preview pane for files in recycle bin

### ISSUE THREAD

**Issue by yaayimanalien** [files-community/Files#4608]
**Explain the bug**
Write a clear description of what the bug is.

**To reproduce**
1. Go to 'Recycle Bin'
2. Click on 'any file'
3. Scroll down to 'Item name in preview pane'
4. See the error

**Expected behavior**
Write a clear description of what you expected.

I expected to name to be the same as it actually is. Seems like Windows renames files if they're in recycle bin. The same invalid filename shows up in file path but I think it'd be the best to keep it if someone wants to locate the file while it's in there.

**Comment by winston-de** [comment]
Thanks for filing this issue. This was (inadvertently) fixed along with a recent redesign of the preview pane, which will be included in the next update.

![image](https://user-images.githubusercontent.com/59544401/115063321-4258bd80-9ea0-11eb-82b7-e07e7c97a740.png)
