### ISSUE TITLE
Pasting images from clipboard is not 100% reliable

### ISSUE THREAD

**Issue by d2dyno1** [files-community/Files#4609]
**Explain the bug**
Copying an image of choice and pasting it to a directory is not always reliable. The image appears to be > 0B in size albeit the read is corrupted. From what I found, some images will be 100% reliablity pasted while some will always paste corrupted.

Important note:
By "Copied image" I do **not** mean image as file but raw data in clipboard.

**To reproduce**
1. Copy any image
2. Paste it to a folder
3. Only sometimes images are corrupted

**Expected behavior**
All images should be reliably pasted.

**Logfile**
(I'll upload it later)
Upload the log file here for us to understand your issue better. 
- You can access it from Settings->About->Open log location. 
or 
- Copy the debug.log and debug_fulltrust.log from the following directory, and upload the files here.
`%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 

**System Information**
 - App version: 1.5.2

**Additional comment**
I'll try to report investigation on this case.

**Comment by winston-de** [comment]
I believe the problem is that it's always being saved as a png file, even if it's not encoded as one.
