### ISSUE TITLE
Alert When Update is installed

### ISSUE THREAD

**Issue by CyrilCharlier** [files-community/Files#4614]
**Is your feature request related to a problem?**
Not really a problem, i just want to know when files has been updated to see new features ;) 

**Describe the solution**
When a new version is installing, alert the user and ask him/her for seeing the release note

**Describe alternatives you've considered**
no alternive in mind 

**Additional comment**
My version has been updated in 1.5 and I didn't know it and I couldn't enjoy the new stuff

**Comment by gave92** [comment]
Also #2454

**Comment by yaichenbaum** [comment]
@CyrilCharlier The Microsoft Store should display a notification whenever an update is installed. Additionally, if you ever want to see the changelog, you can find a link in the settings page.
