### ISSUE TITLE
Send To option

### ISSUE THREAD

**Issue by mhsayan** [files-community/Files#4615]
Like old windows explorer if you can add a "Send to" option when we click mouse right button over any file. that would be a very good for us.
![Files](https://user-images.githubusercontent.com/38936021/114828709-0bc16b00-9dec-11eb-98f0-eeb8f2c72d8a.png)
![send to](https://user-images.githubusercontent.com/38936021/114828728-0f54f200-9dec-11eb-94b0-dc0a05eb3e1e.png)

**Comment by gave92** [comment]
Merging with #285
