### ISSUE TITLE
Add `shift+mouse scroll` to scroll horizontally in item window

### ISSUE THREAD

**Issue by ldsands** [files-community/Files#4618]
**Is your feature request related to a problem?**
No

**Describe the solution**
Many programs I use allow for `shift+mouse scroll` to scroll horizontally in item window (`shift+mouse scroll down` for right scroll and `shift+mouse scroll up` for left scroll). Chrome and VSCode are examples of programs that use this same scroll scheme.

**Describe alternatives you've considered**
Although there are alternatives this seems to be the most common horizontal scroll scheme that I've seen.

**Additional comment**
Obviously this is not very important but I know that I would use this many times everyday.

**Comment by winston-de** [comment]
Related: https://github.com/microsoft/microsoft-ui-xaml/issues/877

**Comment by Josh-65** [comment]
Merging with #10006
