### ISSUE TITLE
Touch screen click and hold doesn't work in Android RDP Client

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#4619]
**Describe the solution**
Click and hold allows users to access right click options it work everywhere but in files. It should work for single and double click options in any layout.

**Comment by winston-de** [comment]
I just tested, touch and hold to right click does indeed work. Could you please provide more information on this issue?

**Comment by josh-65** [comment]
i test this using touch mode on rdp android client

**Comment by josh-65** [comment]
Any update on this?

**Comment by josh-65** [comment]
So it sort of works on 1.5.26. The issue now is when an items selected it won't bring it up but when it's not it will but also open the file/folder.

**Comment by josh-65** [comment]
Fixed in 1.9.14
