### ISSUE TITLE
I love this application. Only one thing, its possible replace the current Ctrl+E to open WinExplorer will be replaced by Files?

### ISSUE THREAD

**Issue by ameliandev** [files-community/Files#4622]
**Is your feature request related to a problem?**
A clear description of what the problem is.

**Describe the solution**
A clear description of what you want.

**Describe alternatives you've considered**
A clear description of any alternative solutions or features you've considered.

**Additional comment**
Add any other comment or screenshots about the feature request here. What device type/UI layout and app version?

**Comment by winston-de** [comment]
Yes there is a way to do this, please see [this](https://files-community.github.io/docs/#/articles/configure-win-e) article.
