### ISSUE TITLE
Need network file access

### ISSUE THREAD

**Issue by JohntheLast99** [files-community/Files#4623]
**Is your feature request related to a problem?**
No

**Describe the solution**
Show files that are on other servers (i.e. NAS)

**Describe alternatives you've considered**
None

**Additional comment**
Nice interface but sorely lacking if network files aren't included

**Comment by YuanfengZhang** [comment]
I suppose it's your own mount problem. 
![image](https://user-images.githubusercontent.com/71358306/124771362-a5249700-df6d-11eb-9337-6865732def74.png)
If you wanna browse files of NAS, that's it.
