### ISSUE TITLE
Pop out status center to compact overlay window

### ISSUE THREAD

**Issue by winston-de** [files-community/Files#4627]
**Is your feature request related to a problem?**
No.

**Describe the solution**
Being able to pop the status center out into a compact overlay window would make it easy to monitor the progress of large file operations while working in other programs. 

**Describe alternatives you've considered**
- Keep Files on top
- Pin status center to side of files

**Additional comment**

**Comment by kleenkanteen** [comment]
I don't understand. What is a status center. How would it look compacted?

**Comment by winston-de** [comment]
@kleenkanteen This is the status center, it allows you to view the status of ongoing file operations. 
![image](https://user-images.githubusercontent.com/59544401/115158287-46244580-a042-11eb-971a-25acd5f2106a.png)

> How would it look compacted?

It wouldn't be compacted, it would be in it's own compact overlay window, which is much smaller and remains on top of other windows. It would be relatively similar to how Explorer shows file operations now.
