### ISSUE TITLE
Box Cloud Drive Contents Missing

### ISSUE THREAD

**Issue by madtempest** [files-community/Files#4629]
**Explain the bug**
When browsing the contents of the "Box" cloud drive, there is only a single file. When reviewing this directory within regular Windows Explorer, all expected content is there.

**To reproduce**
1. Go to Cloud Drives
2. Click on Box
3. Review the list of content

**Expected behavior**
When browsing the contents of the "Box" cloud drive, there is only a single file. When reviewing this directory within regular Windows Explorer, all expected content is there.
[debug.txt](https://github.com/files-community/Files/files/6323107/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6323109/debug_fulltrust.txt)
![Box Screenshot 01](https://user-images.githubusercontent.com/14276889/114984302-2cf58a80-9ec4-11eb-8e4c-4cbc9a3cbc18.PNG)

**Logfile**
Upload the log file here for us to understand your issue better. 
- You can access it from Settings->About->Open log location. 
or 
- Copy the debug.log and debug_fulltrust.log from the following directory, and upload the files here.
`%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 

**Screenshots**
Add screenshots to help explain your problem if needed.

**System Information**
 - OS Version: Windows 10 2004 19041.746
 - App version: 1.5.0.0

**Additional comment**
Add any other comment about the problem here. Does this problem happen again after restarting the app?

**Comment by gave92** [comment]
Could you check if turning on "show hidden files" and turning _off_ "hide system files and folders" options the missing items appear?

**Comment by madtempest** [comment]
![Box Screenshot 02](https://user-images.githubusercontent.com/14276889/115013676-f2034f00-9ee3-11eb-88b6-3aa499747c8e.PNG)
 I couldnt find "hide system files and folders" as a specific option, but I did follow what I think was your intended instructions as per the screenshot.
 
 This did not resolve the issue.

**Comment by Jaiganeshkumaran** [comment]
Box seem to create a virtual folder where it loads the list on demand for online-only files unlike OneDrive which creates a placeholder file for each online-only file

**Comment by madtempest** [comment]
@Jaiganeshkumaran That might be the case, but what about files that are kept locally on disk via its always sync feature? Surely those would be present.

**Comment by yaichenbaum** [comment]
@madtempest This issue should be resolved with #4921.
