### ISSUE TITLE
Selection animation in left sidebar broken

### ISSUE THREAD

**Issue by mmischitelli** [files-community/Files#4630]
**Explain the bug**
The selection animation in the left sidebar is broken. It used to move across the elements in between the two folders you're navigating to/from. Now instead it "teleports" from one to the other.

**To reproduce**
1. Go to any of the folders you have on your left sidebar
2. Click on another folder you have on the left sidebar, possibly quite distant from the current one
3. The animation skips from the previous folder to the new one. Folders in between don't receive the animation.

**Expected behavior**
The same as per Fluent Design specifications

**Screenshots**
A brief video of the issue: https://1drv.ms/v/s!Auxdy70nvM2pp6AC8ve3nWvJt2V2dw?e=KtgTux

**System Information**
 - OS Version: Windows 10 20H2 19042.928
 - App version: v1.5.13

**Comment by yaichenbaum** [comment]
@mmischitelli is this still an issue in the preview version? https://files.community/download/preview
