### ISSUE TITLE
Show dialog when accessing folders without read/write permissions 

### ISSUE THREAD

**Issue by jonathan-reichardt** [files-community/Files#4631]
**Explain the bug**
Write a clear description of what the bug is.

**To reproduce**
1. Let someone create a Folder on a network drive, so that you dont have read/write/open permissions for the folder, but so that you can see it (see first screenshot)
2. Try to open the Folder in Files.
3. Now it looks as if the folder you opened is an empty folder 

**Expected behavior**
- A warning message when you try to open folders, that you don't have permissions for. 

**Screenshots**
![image](https://user-images.githubusercontent.com/31374296/115003180-da0cda80-9ea5-11eb-845e-0ad0594e62b0.png)
![image](https://user-images.githubusercontent.com/31374296/115003338-fc065d00-9ea5-11eb-980b-90fa24fce237.png)

Add screenshots to help explain your problem if needed.

**System Information**
 - OS:	Windows 10 Pro Version	20H2 19042.868
 - App version:  v1.5 -  e859940

**Comment by yaichenbaum** [comment]
@gave92 Should we merge this with #1194?

**Comment by gave92** [comment]
Merging with #1194
