### ISSUE TITLE
The settings button has scrollbar buttons

### ISSUE THREAD

**Issue by xpopy** [files-community/Files#4634]
**Explain the bug**
The settings button has scrollbar buttons, which partly covers the settings icon when the left panel is collapsed

**To reproduce**
1. Open files
2. Look in the bottom left corner

**Expected behavior**
Since there's nothing to scroll and it looks ugly, the expected behaviour is to not show a scrollbar/scroll buttons.

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6325581/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6325582/debug_fulltrust.txt)

**Screenshots**
![image](https://user-images.githubusercontent.com/3540971/115035357-cc1e8000-9ecc-11eb-8286-19a972ef3ce9.png)
![image](https://user-images.githubusercontent.com/3540971/115035379-d0e33400-9ecc-11eb-962f-9742b92e0192.png)

**System Information**
 - OS Version: Version 20H2 (OS Build 19042.746)
 - App version: 1.5.0.0

**Additional comment**
This happens even after restarting the app and after reinstalling the app.

**Comment by yaichenbaum** [comment]
This issue has been resolved in `main`.
