### ISSUE TITLE
Feature: Attach version info when submitting issues reports

### ISSUE THREAD

**Issue by kimlimjustin** [files-community/Files#4635]
**Is your feature request related to a problem?**
Submitting issues on GitHub is somehow troublesome especially to create bug report, which requires many OS information.

**Describe the solution**
Being inspired by vscode, create an issue submission form in Files, and automatically attach OS information and Files information.

**Requirements**
- Automatically fill out the version information when clicking the report issue button on the about page.

**Additional comment**
Found this resource https://docs.github.com/en/rest/reference/issues#create-an-issue, hope it's useful :)

**Comment by yaira2** [comment]
@kimlimjustin thank you for the feedback, I added this to the project board.

**Comment by yaira2** [comment]
This feature will be included in the next release.
