### ISSUE TITLE
Being able to tag documents

### ISSUE THREAD

**Issue by combatbutter** [files-community/Files#4636]
**Is your feature request related to a problem?**
A clear description of what the problem is.

**Describe the solution**
A clear description of what you want.

**Describe alternatives you've considered**
A clear description of any alternative solutions or features you've considered.

**Additional comment**
Add any other comment or screenshots about the feature request here. What device type/UI layout and app version?

**Comment by combatbutter** [comment]
I tag my documents routinely in my documents' "Properties" (right click) in File Explorer to enable a more intuitive search, it would be great if you could add this feature to Files. In fact, if you could make it cleaner and with fewer steps than what is needed in File Explorer that would be ideal.

**Comment by winston-de** [comment]
This would be relatively easy to implement in the properties details page.

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
