### ISSUE TITLE
What happened to the icons

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#4638]
**Explain the bug**
Some of the icons are missing or incorrect there also quite small.

**Screenshots**
![image](https://user-images.githubusercontent.com/26977075/115050346-9204ac80-9ed3-11eb-9792-aa3afcf6ac37.png)

**System Information**
 - OS Version: Windows 10 20H2 19042906
 - App version: 1.5.13.0

**Comment by yaichenbaum** [comment]
@josh-65 Are you in the Discord server? The icons are still a work in progress.

**Comment by josh-65** [comment]
i knew that just didn't think the old icons would disappear

**Comment by yaichenbaum** [comment]
@josh-65 You are in the insider flight group which will sometimes get new features or changes that are still a work in progress, we usually give a heads up in the Discord server before we ship a change like this. You can rest assured though, that we are working on finishing work on the new icons.

**Comment by josh-65** [comment]
i know that fine just making sure.

**Comment by yaichenbaum** [comment]
@josh-65 Thanks for checking! And for the future, it would be great if you could join the Discord server https://discord.gg/files.
