### ISSUE TITLE
App crash when opening properties

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#4639]
**Explain the bug**
When I try opening properties of a drive it will crash instantly. When doing it for folders it will open but crash when I press cancel (why is that there in the first place) the properties.

**Expected behaviour**
Open properties of the folder or drive

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6326666/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6326667/debug_fulltrust.log)

**System Information**
 - OS Version: Windows 10 20H2 19042.928
 - App version: v1.5.13

**Comment by yaichenbaum** [comment]
This issue should be resolved with #4658.
