### ISSUE TITLE
Recycle bin doesn't refresh when deleting

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#4640]
**Explain the bug**
When deleting items in the recycle bin it won't auto refresh.

**Expected behaviour**
Write a clear description of what you expected.

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6326777/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6326778/debug_fulltrust.log)

**System Information**
 - OS Version: Windows 10 20H2 19042.928
 - App version: v1.5.13.0

**Comment by Josh65-2201** [comment]
@yair100  it open

**Comment by josh-65** [comment]
Just to add the icon for it should update to show whether there's something in it or not

**Comment by yaichenbaum** [comment]
This issue should be resolved with #4736.
