### ISSUE TITLE
Opening folder in google drive can cause a crash

### ISSUE THREAD

**Issue by NikitaProgramist** [files-community/Files#4642]
**Explain the bug**
Write a clear description of what the bug is.
Opening the folder on my google drive using "Files" sometimes application finishes work
[debug.txt](https://github.com/files-community/Files/files/6326990/debug.txt)
![failure](https://user-images.githubusercontent.com/58474512/115063111-d011c880-9ef3-11eb-8d80-21f411e11b07.png)

**To reproduce**
1. Go to '....'
4. See the error

**Expected behavior**
I want to open the folder on my google drive.

**Logfile**
Upload the log file here for us to understand your issue better. 
- You can access it from Settings->About->Open log location. 
or 
- Copy the debug.log and debug_fulltrust.log from the following directory, and upload the files here.
`%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 

**Screenshots**
Add screenshots to help explain your problem if needed.

**System Information**
 - OS Version: [e.g. Windows 10 20H2 19042.804] (Press WIN + PAUSE/BREAK, use the copy button at the bottom)
 - App version: [e.g. v1.0] (In the app, go to Settings -> About, the version is shown at the top)

**Additional comment**
Add any other comment about the problem here. Does this problem happen again after restarting the app?

**Comment by yaichenbaum** [comment]
@NikitaProgramist is this still an issue in Files v2.0?
