### ISSUE TITLE
Improving the new details view

### ISSUE THREAD

**Issue by winston-de** [files-community/Files#4643]
This issue is to track bugs and enhancements for the new details view. If you have any, please post them here and I'll add them.

- [x] Collapse status column when not in a cloud drive
- [x] Add recycle bin columns, and hide them when outside of the recycle bin
- [x] Columns aren't always collapsed after switching layout modes
- [x] Add empty space to the right of the last column instead of stretching
- [x] #2570 (wasn't possible before with the DataGrid)
- [x] Add button visuals for ascending and descending sort
- [x] Implement horizontal scrolling
- [x] Remember column sizes (feature request)
- [x] Fix double click to rename
- [x] File icons are too small
- [x] Folder icons are cut off slightly
- [x] Better handling of overlapping columns
- [x] Reduce grid splitter width, remove element
- [x] Context menu sometimes fails to open because selected items is empty
- [x] Reimplement #4460
- [x] Fix columns getting squished
- [x] Show status column in a library with a cloud folder
- [x] Fix collapsed column headers not being updated when switching layout modes
- [x] Right click menu to collapse columns
- [x] Don't end rename when name text box content is right clicked
- [x] Add a size column
- [x] Add a date created column (collapsed by default?)
- [x] Fix crash when navigating while renaming
- [x] Fix sticky headers
- [x] Focus file list upon navigation instead of header
- [x] reduce width so that it doesn't horizontal scroll when the window is already large enough
- [x] Double clicking the header divider should fit the column to width
- [x]  Allow tab selecting columns
- [x] Fix issue where columns can't be resized with keyboard only
- [x] Can't invoke headers with keyboard alone
- [ ] #8384
- [ ] #8385

**Comment by yaichenbaum** [comment]
>  Add padding to sides to make it easier to activate rectangle selection and clear selection

@winston-de Instead of stretching the last column, can you just have empty space like we have with the current DataGrid?

**Comment by winston-de** [comment]
@yair100 Yeah, that's a better idea.

**Comment by josh-65** [comment]
#4460 still works for me in 1.5.16.0

**Comment by complex** [comment]
I'd like to be able to reorder columns, for example moving size before date.

An option to auto-size the name column (to be as wide as possible) would be nice too.

**Comment by winston-de** [comment]
> I'd like to be able to reorder columns, for example moving size before date.

@complex This is out of scope for this issue, as the main purpose of this issue to get get to feature parity with the DataGrid based details view. However, please feel free to create a new issue for this.

> An option to auto-size the name column (to be as wide as possible) would be nice too.

Currently, the name size column is adapted to take up a certain percentage of the horizontal space available. I can definitely look into increasing that.

**Comment by beqabeqa473** [comment]
Hello.

when toggling to new details mode, screenreader starts to read contents of files and folders, but everytime folder changes focus jumps to name button instead of staying on file/folder list.

please fix that thing which makes app usage not so comfortable.

thanks.

**Comment by yaichenbaum** [comment]
@winston-de Fyi #2963.

**Comment by gave92** [comment]
Is the new selected item background final? With the new one I find very hard too see selected items:

![image](https://user-images.githubusercontent.com/9673091/120103385-a8975800-c14f-11eb-932f-ddf661ae2f9e.png)

Edit: just noticed same goes for GriView selection so not tied to this issue.

**Comment by yaichenbaum** [comment]
@gave92 the new styles seem to only work on 20H2. A potential fix could be to create a custom style for older versions of Windows 10.
![image](https://user-images.githubusercontent.com/39923744/120107859-a8d42b00-c130-11eb-96b8-e6c22dbe42bc.png)

**Comment by josh-65** [comment]
When opening a folder then scrolling the top bar with Name, Date and stuff disappears. It also shows up as scrollable left and right when it shouldn't.
![image](https://user-images.githubusercontent.com/26977075/120118969-1c0b8a80-c18d-11eb-886f-01789816ca10.png)

**Comment by BanCrash** [comment]
> @gave92 the new styles seem to only work on 20H2. A potential fix could be to create a custom style for older versions of Windows 10.
> ![image](https://user-images.githubusercontent.com/39923744/120107859-a8d42b00-c130-11eb-96b8-e6c22dbe42bc.png)

The new styles are only compatible with 20H2? I have installed 21H1 but still not working. Or perhaps it's necessary install something else?

**Comment by gave92** [comment]
The new styles are only compatible with 2**1**H2 not 20H2

**Comment by yaichenbaum** [comment]
@gave92 The stable version of WinUI 2.6 seems to have disabled the new styles.

**Comment by BanCrash** [comment]
> The new styles are only compatible with 2**1**H2 not 20H2

Oh, that explains it. Thanks!

**Comment by winston-de** [comment]
> @gave92 The stable version of WinUI 2.6 seems to have disabled the new styles.

I think they bumped the new styles to require an even newer build of Windows than what's been released to insiders so far. I'd guess the first Windows 11 preview will have the styles.

**Comment by josh-65** [comment]
I don't the top bar shouldn't disappear when scrolling.
https://user-images.githubusercontent.com/26977075/124296123-85e2cf80-db51-11eb-9d30-a3dd74ca044c.mp4

**Comment by mdtauk** [comment]
> I don't the top bar shouldn't disappear when scrolling.
> 
>  2021-07-02.16-19-27_Trim.mp4

I would agree, the header should be sticky when it is visible, so when in the Details view.

**Comment by yaichenbaum** [comment]
@josh-95 we haven't gotten a chance to fix this yet.

**Comment by josh-65** [comment]
> The highlight/selection of a file and folder should not go pass the green line as that's were the tabs end but it end up extending pass the apps width and created a scroll bar too.
> ![image](https://user-images.githubusercontent.com/26977075/121821529-8514f700-cc91-11eb-9f0c-f99058ed5f00.png)

The scroll bar issue has been fixed but it still extends to the full width of the screen witch makes it impossible to use the white space right click menu if the files/folders extend past the height of the window.

**Comment by yaichenbaum** [comment]
@josh-65 thanks for letting us know, we haven't gotten around to implementing this in the new details layout, but we will make sure to check it off in our list once it's done.
