### ISSUE TITLE
I liked the old icons on sidebar, current ones seems too small and don't fit with design

### ISSUE THREAD

**Issue by osieltorres** [files-community/Files#4645]
**Explain the bug**
New icons on sidebar panel seems too small comparing to the font, please consider place back the old ones.

**To reproduce**
1. Go t the app.
2. Click on anywhere
3. Check on the size of sidebar panel icons.

**Expected behavior**
An icons more related to the design followed by the app, like the folder icons as example.

**Screenshots**
![image](https://user-images.githubusercontent.com/3835402/115077926-d6d91500-9ecc-11eb-92ba-bd486ab0f7e8.png)

**System Information**
 - OS Version: Windows 10 20H2 19042.928
 - App version: 1.5.13.0

**Additional comment**
Add any other comment about the problem here. Does this problem happen again after restarting the app?

**Comment by yaichenbaum** [comment]
As mentioned in the release notes, the icons are placeholder and will be adjusted in a future update.
