### ISSUE TITLE
Dynamic tab width

### ISSUE THREAD

**Issue by xpopy** [files-community/Files#4646]
**Is your feature request related to a problem?**
When I have even 3 tabs open the tab bar becomes scrollable and the tabs are a bit too wide taking up precious space

**Describe the solution**
Dynamically adjust the tab width to fit the tabs within the tab bar until a minimum width has been reached, and first then make it scrollable.

**Describe alternatives you've considered**
A clear description of any alternative solutions or features you've considered.

**Additional comment**
Add any other comment or screenshots about the feature request here. What device type/UI layout and app version?

**Comment by yaichenbaum** [comment]
@xpopy This issue should be addressed with #4891.
