### ISSUE TITLE
Add the option to use the old right click menu

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#4651]
**Is your feature request related to a problem?**
I don't like the new version of it

**Describe the solution**
A toggle in appearance settings to use the old one would be nice

**Comment by winston-de** [comment]
May I ask what about it you don't like?

**Comment by josh-65** [comment]
Mostly the inconstancies of how the buttons are group some are icons like the open and pin to sidebar. some are the icon and text like open with and pin to start menu and with the icons changing I don't know what some of them do. They also change a lot in different part/folders.

**Comment by winston-de** [comment]
Thanks for the feedback. Fyi, all the buttons without text next to them have a tooltip so that you can identify what they do.
![image](https://user-images.githubusercontent.com/59544401/115124827-35f46380-9f79-11eb-8006-283832c0982b.png)

**Comment by josh-65** [comment]
i still prefer having then all icon text format

**Comment by josh-65** [comment]
Moving to #4824
