### ISSUE TITLE
Folder icons on side bar should be normal folders

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#4652]
**Is your feature request related to a problem?**
The replacement for the sidebar icon currently look bad.

**Describe the solution**
It should be the normal folder icons in the navigation area. They should be double the size they currently are.

**Additional comment**
![image](https://user-images.githubusercontent.com/26977075/115118853-43234980-9f9d-11eb-99a9-b912cdf4dc98.png)

**Comment by josh-65** [comment]
can i know the reason this has been closed

**Comment by yaichenbaum** [comment]
The icons are just placeholders and will be changed in a future update.
