### ISSUE TITLE
Sidebar selection animation not working properly

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#4653]
**Explain the bug**
The sidebar currently selected animation cuts off when going outside the active button

**Expected behaviour**
It should show the animation all the way to the selected item.

**Screenshots**
https://user-images.githubusercontent.com/26977075/115121188-373d8480-9fa9-11eb-9982-51de9d521ea7.mp4

**System Information**
 - OS Version: Windows 10 20H2 19042.926
 - App version: [e.g. v1.5.16

**Comment by gave92** [comment]
#4630?

**Comment by josh-65** [comment]
Yes that the same one.
