### ISSUE TITLE
Group files by type or extension

### ISSUE THREAD

**Issue by Masamune3210** [files-community/Files#4654]
**Is your feature request related to a problem?**
No, more of a lack of a feature parity that I use all the time

**Describe the solution**
Allow files to be grouped by extension/file type like Explorer

**Describe alternatives you've considered**
A clear description of any alternative solutions or features you've considered.

**Additional comment**
My device is a computer running Windows 10 20H2

**Comment by winston-de** [comment]
Thanks for this feature request, merging with #1874.

**Comment by Masamune3210** [comment]
Sorry, didnt see the already open request
