### ISSUE TITLE
The library(folder) section only has the Desktop folder and the Downloads folder

### ISSUE THREAD

**Issue by pklion** [files-community/Files#4657]
**Explain the bug**
The library(folder) section only has the Desktop folder and the Downloads folder.

**To reproduce**
1. Open Files
2. See the error

**Expected behavior**
I would like to show all of the following folders:
- Desktop
- Downloads
- Documents
- Pictures
- Videos
- Music

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6330288/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6330289/debug_fulltrust.txt)

**Screenshots**
![image](https://user-images.githubusercontent.com/78145811/115130072-49f69e80-a027-11eb-9a53-3a09d7fae34a.png)

**System Information**
 - OS Version: [Windows 10 Home 20H2 19042.928]
 - App version: [e.g. v1.5.16.0]

**Additional comment**
Does this problem happen again after restarting the app?
- Yes, it does.

**Comment by yaichenbaum** [comment]
This should be resolved in v2.3.11
