### ISSUE TITLE
Merge conflict resolution button is hidden for items with long names

### ISSUE THREAD

**Issue by winston-de** [files-community/Files#4660]
**Explain the bug**
The merge conflict resolution button is hidden for items with long names.

**To reproduce**
1. Find a file with a very long name
2. Copy it
3. Paste it into the same directory
4. Conflict resolution button is hidden

**Expected behavior**
The text should be wrapped or cut off to not interfere with the button.

**Logfile**
Not applicable

**Screenshots**
![image](https://user-images.githubusercontent.com/59544401/115133341-3e21c280-9fbc-11eb-8998-a4025865b12c.png)

**System Information**
 - OS Version: 19043.928
 - App version: 1.5.16.0

**Additional comment**

**Comment by yaichenbaum** [comment]
This should be resolved in `main`.
