### ISSUE TITLE
Bug report: Invert selection sometimes freezes for a couple seconds before it works

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#4662]
This is reproducible in v1.5.16

**Comment by d2dyno1** [comment]
This is caused by multiple UI updates. In the function `InvertSelection` ItemsView.SelectedItems.Add is called for every item causing UI freeze in large directories.

**Comment by yaichenbaum** [comment]
@hez2010 I believe you tried solving this a while ago, right?

**Comment by hez2010** [comment]
The problem I met previously is that sometimes the rectangle selection didn't work. I think they might be the same problem, though I didn't dig into it much.

**Comment by hez2010** [comment]
@yair100 I previously solved the performance issue with `SelectAll` via calling the internal method of `DataGrid`, but I haven't figure out a way to do invert selection in this way.

Related: https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/3264

**Comment by yaichenbaum** [comment]
@hez2010 @winston-de created a list view data grid that's already in `main`, does that make a difference?

**Comment by winston-de** [comment]
@yair100 The new details view seems to have the same issue, I tried doing invert selection in the system32 and Files froze. It's the same for grid, tiles, and columns view as well. 
We may want to file an issue for this in the WinUI repo as well. There doesn't seem to be one, so I'll open one. 
https://github.com/microsoft/microsoft-ui-xaml/issues/4850
