### ISSUE TITLE
Copy and Paste not working

### ISSUE THREAD

**Issue by mangoepic** [files-community/Files#4665]
**Explain the bug**
Copying and Pasting does not work

**To reproduce**
1. Go to 'Desktop'
2. Richtclick on any file
3. Select 'Copy'
4. Rightclick on the Desktop Window
4. Select 'Paste'
5. Nothing happens
Same with Ctrl+C Ctrl+V

**Expected behavior**
A copy of the file to be generated

**Screenshots**
![5jS7yCy](https://user-images.githubusercontent.com/71931749/119264441-85b2f400-bbe3-11eb-8e42-751e48baff85.gif)

**Logfile**
```
2021-04-19 19:21:08.6758|ERROR|FilesFullTrust.Program|Die Pipe wird gerade geschlossen.
|System.IO.IOException: Die Pipe wird gerade geschlossen.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.Pipes.NamedPipeServerStream.BeginWaitForConnection(AsyncCallback callback, Object state)
   bei System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   bei System.IO.Pipes.NamedPipeServerStream.WaitForConnectionAsync(CancellationToken cancellationToken)
   bei System.IO.Pipes.NamedPipeServerStream.WaitForConnectionAsync()
   bei FilesFullTrust.Program.<InitializeAppServiceConnection>d__10.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   bei System.Threading.ThreadPoolWorkQueue.Dispatch()
```

Not sure if anything related.

**System Information**
 - OS Version: Microsoft Windows Version 1909 (Build 18363. 1500)
 - App version: 1.5.0.0

**Additional comment**
Issue persists after restarting: Yes
**Updating windows to  20H2 (Build 19042.928) fixed the issue for me**

**Comment by hez2010** [comment]
Does restarting Files app help?

**Comment by haneenmahd** [comment]
Yeah! Your are right it does not work.
It does not completely copy paste the files in to another directory and also ignore some files too.

**Comment by mangoepic** [comment]
Here is just a short screen recording how it looks like: https://imgur.com/a/xfiPpFy
Cutting and pasting doesn't work, too (it seems to get reset as soon as I change directory?)

**Comment by hez2010** [comment]
Can you provide your system version? (Run `winver` and you can see the system build number)

**Comment by mangoepic** [comment]
@hez2010 Oh there it is thanks. It's Microsoft Windows Version 1909 (Build 18363. 1500)

**Comment by JettFlat** [comment]
Same problem.  Microsoft Windows Version 2004 (Build 19041. 331)

**Comment by haneenmahd** [comment]
Maybe you should update to the latest one!
It worked on my machine after I updated

**Comment by mangoepic** [comment]
@haneenmahd I will try this thanks. Just realized windows gave me some update errors so will try. It sounds like a good idea for a file manager to be compatible with at least some older versions though?

**Comment by haneenmahd** [comment]
If that did not work try downloading to windows insider builds

**Comment by mangoepic** [comment]
I can confirm that it now works for 20H2 (Build 19042.928)

**Comment by haneenmahd** [comment]
https://github.com/files-community/Files/blob/c098f579997f11bd77c540d0567643dd666e29af/Files.Launcher/packages.config#L1-L4

Maybe you need a windows build which supports the latest version of `.NET` Framework or Sdk

**Comment by yaichenbaum** [comment]
@mangoepic is this still an issue in Files v2.0?

**Comment by mangoepic** [comment]
> @mangoepic is this still an issue in Files v2.0?

It works since my windows upgrade. But I'm not sure if the bug is fixed for people with the older windows versions

**Comment by Suprethreal** [comment]
Still an issue.
https://github.com/files-community/Files/issues/6391

**Comment by yaichenbaum** [comment]
Merging with #6931.
