### ISSUE TITLE
Media files: Context menu doesn't appear and app freezes

### ISSUE THREAD

**Issue by Xairoo** [files-community/Files#4666]
**Explain the bug**
Right click on media files (PNG, MOV, MP4, ...) freezes Files (PDF work, but it's a document ;-)).

**To reproduce**
1. Select a media file
2. Right click...

**Expected behavior**
Context menu should appear

**Logfile**
Nothing more than:
`2021-04-18 20:01:51.2956|INFO|FilesFullTrust.Program|Argument: LoadContextMenu|`

**System Information**
 - OS Version: 10.0.19043 Build 19043
 - App version: 1.5 (fresh install, never used this app before)

**Additional comment**
Restart didn't helped.

**Comment by winston-de** [comment]
Thanks for opening this issue. This should be fixed with #4625, which will be included in the next major update.

**Comment by Xairoo** [comment]
No nightly builds? =)

**Comment by winston-de** [comment]
There are, you can ask to sign up for them in the discord server :)
https://discord.gg/files

**Comment by Xairoo** [comment]
Would be great if you guys would publish the nightly builds outside of discord ;-)

The bug I have reported also appears on my partners system. The "sometimes freezing" bug from #4625 should be fixed ASAP because the app isn't usable at this state.
