### ISSUE TITLE
Change Downloads Folder Location

### ISSUE THREAD

**Issue by K12T6** [files-community/Files#4670]
**Is your feature request related to a problem?**
Default directories on the home page cannot be changed.

**Describe the solution**
Add the option to change what folders go where on the home page. For example, changing the Downloads quick link to go to a different directory for those who have their downloads folder in a different location (i.e. iCloud Drive)

**Additional comment**
App version 1.5.0.0

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
