### ISSUE TITLE
Choose Files

### ISSUE THREAD

**Issue by aayushyap89** [files-community/Files#4675]
Hello, I really love the files app but a few this that may exist but I dont know
If there is then please inform me
1. Please add a way to open files app instead of file explorer when you are choosing a file on a website to upload.
2. Is there a way to make it default so when you search a file in the Start Menu to open Files Instead of File explorer

**Comment by winston-de** [comment]
Hi there! Happy to hear your enjoying Files.

> Please add a way to open files app instead of file explorer when you are choosing a file on a website to upload.

Unfortunately, it is not currently possible to replace the default save as and file selection dialogs. Please see #4106.

> Is there a way to make it default so when you search a file in the Start Menu to open Files Instead of File explorer

Yes there is, please see [this guide](https://files-community.github.io/docs/#/articles/replace-file-explorer).
