### ISSUE TITLE
Delete folders from Program Files

### ISSUE THREAD

**Issue by LuanRoger** [files-community/Files#4676]
When trying to delete folders from 'Program Files (x86)' but the Files simply closes, even as Administrator

### To reproduce
1. Go to C:\Program Files (x86)
2. Try to delete or create a folder
4. See the error

I also tried to create files or folders but the program ends up failing. Apparently the problem is caused by the lack of permission to the program, but it happens even as Administrator 

### Logfile
[debug.txt](https://github.com/files-community/Files/files/6338313/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6338314/debug_fulltrust.txt)

### Screenshots
![Administrator](https://user-images.githubusercontent.com/46284513/115287329-865cf400-a126-11eb-9d59-fef6e7dcfbed.png)
![Error](https://user-images.githubusercontent.com/46284513/115287327-85c45d80-a126-11eb-9045-6763083894e3.png)

### System Information
 - OS Version: Windows 10 Home 20H2 19042.928
 - App version: v1.5

**Comment by gave92** [comment]
@winston-de fixed in #4586?

**Comment by winston-de** [comment]
@gave92 No, I didn't know what was causing it, that PR just added a catch for the error and logs it.

**Comment by winston-de** [comment]
@gave92 This was fixed in your null task pr, right?

**Comment by gave92** [comment]
@winston-de yeah should be 👍
