### ISSUE TITLE
Escape key to exit settings

### ISSUE THREAD

**Issue by voiiden** [files-community/Files#4678]
I often try to exit the settings page using the escape key, as is convention in many other apps, such as discord and steam. I suggest the implementation of this feature, as I don't see any other use for the escape key in this situation.

**Comment by cinqmilleans** [comment]
It's a good idea.
I am always confused because the button to close is not in the same place as to open it. We could put a Close button at the bottom of the sidebar.

If the community accepts these changes, I can implement it.

**Comment by voiiden** [comment]
I'm not sure about that last idea. Back buttons are typically on the top, usually to the left.

**Comment by yaichenbaum** [comment]
@voiiden Another option is to use the back button, it doesn't make much of a difference to me though.

**Comment by voiiden** [comment]
Escape seems the most logical to me. It's literally called escape, as in escape from a menu, and backspace to go back is getting dated, usually getting replaced by Alt + Left arrow.

**Comment by yaichenbaum** [comment]
The reason I suggested back is because you are going back to the last page, esc is usually used for a dialog.

**Comment by Jaiganeshkumaran** [comment]
Settings page is full screen and not a modal. Esc is used for modal and transient surfaces, not for page navigation

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran Agreed, that's why I think we should use the back button.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5077.
