### ISSUE TITLE
Quick open sidebar folder in new tab

### ISSUE THREAD

**Issue by v0iden** [files-community/Files#4679]
Pressing a folder with the mouse wheel opens it in a new tab. This should work for sidebar folders, too. 

I made a crude video to demonstrate my idea:
https://user-images.githubusercontent.com/31285047/115386176-5ae71180-a1d9-11eb-85a7-7bd31508ed54.mp4

**Comment by voiiden** [comment]
Sorry for all the editing. I realized most of what I was proposing was already implemented.

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
