### ISSUE TITLE
Add keyboard shortcuts to change layout mode

### ISSUE THREAD

**Issue by pklion** [files-community/Files#4682]
**Is your feature request related to a problem?**
I'm sometimes frustrating because I have to click 2 times when changing layout modes.

**Describe the solution**
Add keyboard shortcuts to change layout mode.

**Describe alternatives you've considered**
N/A

**Additional comment**
N/A

**Comment by Rasmagoric** [comment]
yeah maybe Alt+ 1 to 5? Or Ctrl + Shift instead of alt?

**Comment by pklion** [comment]
I think Ctrl+Alt+1 to 5 or Alt+1 to 5 is good, isn't it?

**Comment by cinqmilleans** [comment]
@Rasmagoric @pklion @yair100
I have started to implement this issue. I have questions.

1) The order of layouts is not the same in the navigation bar menu and in the context menu. It is annoying to assign a number. It is therefore necessary to use the same order. I propose the order, from the smallest to the biggest.
1. Column
2. Details
3. Tiles
4. Grid (small)
5. Grid (medium)
6. Grid (big)

2) You have to choose shortcuts. I propose:
Alt + 1/6: Layout 1/6
Alt + Subtract -> previous layout
Alt + Wheel Down -> previous layout
Alt + Add -> next layout
Alt + Wheel Up -> next layout

**Comment by yaichenbaum** [comment]
Btw, we already have `ctrl` + wheel up/down and `ctrl` + `+`\`-`

**Comment by cinqmilleans** [comment]
Yes, I just saw it. We could still use ctrl.
ctrl + 1, ctrl + add, ...

**Comment by yaichenbaum** [comment]
Ctrl + 1 - 9 is used to switch tabs.

**Comment by cinqmilleans** [comment]
ok, we will stay on alt + 1/6.

**Comment by yaichenbaum** [comment]
What about `ctrl` + `shift` + 1/6?

**Comment by cinqmilleans** [comment]
ok for me.

**Comment by pklion** [comment]
> What about `ctrl` + `shift` + 1/6?

Looks good to me, too.

**Comment by Rasmagoric** [comment]
I prefer the alt + 1/6.

**Comment by yaichenbaum** [comment]
`ctrl` + 1/6 would be consistent with the existing shortcut `ctrl` + `+`, is `alt` + 1/6 used in other applications for this type of thing?

**Comment by pklion** [comment]
> `ctrl` + 1/6 would be consistent with the existing shortcut `ctrl` + `+`. Is `alt` + 1/6 used in other applications for this type of thing?

Ctrl + Shift + 1/6 used in the windows default explorer.

**Comment by yaichenbaum** [comment]
In that case, let's change it to `ctrl` + `shift` + 1/6.
FYI @cinqmilleans

**Comment by gave92** [comment]
I'd personally change the ordering of the layouts to have Details first like this:
Details -> Tiles -> Grid (small) -> Grid (medium) -> Grid (big) -> Column
Mostly because I associate "1" to the most well known/commonly used layout.

**Comment by yaichenbaum** [comment]
@pklion this feature was implemented in #4722.
