### ISSUE TITLE
[BUG] Files just automatically disappears on clicking folder

### ISSUE THREAD

**Issue by HariAcidReign** [files-community/Files#4687]
**Explain the bug**
When you click on any random folder, sometimes the Files application just shuts down without warning. 

**Expected behavior**
I expected the folder to open up and the path to change, as usual. 
However, the app closes suddenly. This is a recurring issue and can happen anytime. i.e. sometimes te folders open, sometimes they don't.

**Screenshots**
Add screenshots to help explain your problem if needed.

![demo](https://user-images.githubusercontent.com/58134096/115541813-2e0c2a80-a2bd-11eb-80a7-a6b479bb1426.gif)

**System Information**
 - OS Version: Windows 10 Version 1909
 - App version: v1.5.0.0

**Additional comment**
Add any other comment about the problem here. Does this problem happen again after restarting the app?
Yes, It happens after app restart as well

**Comment by winston-de** [comment]
Hi! Could you please upload the ```debug.log``` file to help us debug this issue? You can find it in this folder:
```%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState```

**Comment by HariAcidReign** [comment]
I didn't find the debug file in the said path. Can you let me know where to navigate to?


![image](https://user-images.githubusercontent.com/58134096/115598528-261dac00-a2f8-11eb-88ce-6eda806d3922.png)

**Comment by HariAcidReign** [comment]
Also, I observed that I was able to navigate through all the folders without any issue if I used the keyboard instead of clicking them with the mouse. Maybe double-clicking the folders is causing the issue.

**Comment by winston-de** [comment]
> I didn't find the debug file in the said path. Can you let me know where to navigate to?
> 

@HariAcidReign 
It's not located in the folder in your screenshot. You can access the folder with the log file by pasting the following in the path bar:
```%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState```

From there, please upload this file:
![image](https://user-images.githubusercontent.com/59544401/115599963-056e3b80-a291-11eb-9154-8739d7e5b5d7.png)

**Comment by winston-de** [comment]
Thanks for uploading the log file and additional info, I'm going to merge this with #3973.

As a workaround to this issue, you can disable the caching feature in Settings -> Experimental -> "Cache files and folders for better performance".
![image](https://user-images.githubusercontent.com/59544401/115602611-fccb3480-a293-11eb-8698-b4f1a6a508f5.png)

**Comment by HariAcidReign** [comment]
@winston-de Even with it turned off, I'm still getting the issue. Only using arrow keys to navigate is solving the problem. Thanks for the prompt responses! Hope this bug gets fixed soon.
