### ISSUE TITLE
Add drag and drop feature. 

### ISSUE THREAD

**Issue by imsandro** [files-community/Files#4689]
**Is your feature request related to a problem?**
I can't drag files from Files to another place - like for example importing files to Adobe Premiere by drag and drop.

**Describe the solution**
Allowing drag and drop feature like the Explorer.

**Describe alternatives you've considered**
Not much alternative other than use the ugly Windows default Explorer. 

**Additional comment**
It would be the ultimate feature to make me completelly switch to your app.

**Comment by winston-de** [comment]
Hi! Thanks for opening this issue. Drag and drop is a feature that has been implemented. However, please keep in mind that currently you have to select an item before you can drag it. Like this:

https://user-images.githubusercontent.com/59544401/106496017-3d739880-6471-11eb-9f80-b8c9733b0026.mp4
