### ISSUE TITLE
Extra process spawned when opening a folder with the app execution alias

### ISSUE THREAD

**Issue by winston-de** [files-community/Files#4696]
**Explain the bug**
When a folder is opened in an already existing instance of Files using an app execution alias, a new extra process is spawned.

**To reproduce**
1. Open Files
2. Open task manager, check sub processes for Files
2. Run the command ```files.exe C:\users```, or similar
3. New process is spawned, even though folder is opened in current window

**Expected behavior**
Since the same instance is used, a new process should not be spawned.

**Screenshots**
![image](https://user-images.githubusercontent.com/59544401/115662934-8f032500-a2f4-11eb-9cce-b4aefa8a934f.png)

**System Information**
 - OS Version: 19043.962
 - App version: 1.5.20.0

**Comment by yaichenbaum** [comment]
This issue appears to be resolved
