### ISSUE TITLE
Error in open Google Drive Steam in Files

### ISSUE THREAD

**Issue by KITTran** [files-community/Files#4697]
**Explain the bug**
Write a clear description of what the bug is.
When I press a folder in Google Drive that already sync on my device, the Files wasn't response and auto exit.

**To reproduce**
1. Go to 'Files'
2. Click on 'any folder in Google Drive partition'
4. See the error

**Expected behavior**
Write a clear description of what you expected.
I expect that Files will response which error was happened.

**Logfile**
Upload the log file here for us to understand your issue better. 
- You can access it from Settings->About->Open log location. 
or 
- Copy the debug.log and debug_fulltrust.log from the following directory, and upload the files here.
`%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6361965/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6361966/debug.txt)

**Screenshots**
Add screenshots to help explain your problem if needed.

**System Information**
 - OS Version: Windows 10 21H1 19043.928
 - App version: 1.5.0.0
 
**Additional comment**
Add any other comment about the problem here. Does this problem happen again after restarting the app?

**Comment by gave92** [comment]
Thanks for this report. Please add Files version to the issue description and upload the log files.

**Comment by KITTran** [comment]
> Thanks for this report. Please add Files version to the issue description and upload the log files.

I have already added Files version and uploaded log files

**Comment by gave92** [comment]
Thanks I can confirm this issue is fixed in latest code
