### ISSUE TITLE
Add build date next to version in About page

### ISSUE THREAD

**Issue by TailyFair** [files-community/Files#4699]
**Is your feature request related to a problem?**
When looking in about page, it's not clear when current local version was built. So when looking in main git commit history, it's unclear if my local version has these changes.
Tags are not made for minor versions, so they are not useful for smaller changes.

**Describe the solution**
I would love to see build date next to version in About page.
For example: `Version: 1.5.17.0 (2021-04-01)`

**Describe alternatives you've considered**
-

**Additional comment**
-

**Comment by yaichenbaum** [comment]
The changelog for insider builds can be found in the Discord server. In the case of v1.5.17, it's the same as v1.5.
