### ISSUE TITLE
Renaming drives doesn't work

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#4707]
**Explain the bug**
When I go to rename a drive it will allow me to type a name and click ok it brings up admin mode for PowerShell I click yes and it does nothing even after restarting the app.

**To reproduce**
1. Right click a drive
2. Go to properties
3. Rename drive
4. Click ok
5. Click yes on PowerShell prompt
6. Restart files
7. Drive not renamed.

**Expected behaviour**
Drive should be renamed after clicking ok in properties

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6361361/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6361362/debug_fulltrust.log)

**System Information**
 - OS Version: Windows 10 20H2 19042.928
 - App version: v1.5.21

**Comment by tocram1** [comment]
I have kind of the same problem, except that after I click yes on the PowerShell prompt, the app is stuck and doesn't respond anymore. I have to close it, then open it again to see that the drive indeed gets renamed.
My debug files don't seem to have anything interesting aside these two lines in `debug_fulltrust.txt` (the first for the renaming, the second for the termination of the app :/)
```
2021-06-08 01:26:54.8881|INFO|FilesFullTrust.Program|Argument: SetVolumeLabel|
2021-06-08 01:27:07.3835|INFO|FilesFullTrust.Program|Argument: Terminate|
```

Here they are anyways :
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6612479/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6612480/debug.txt)

**Comment by josh-65** [comment]
So an update on this using a build from main. I try renaming a drive didn't work even after re launching. Tried again and it did show after a relaunch but the drive letter was also add so it became '(S:)  (S:)'. Renaming it again worked but the double drive letter remained.

Updated logs:
[debug.log](https://github.com/files-community/Files/files/6612661/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6612662/debug_fulltrust.log)

**Comment by tocram1** [comment]
I've encountered this issue as well, the field in which we input the new drive label contains the drive letter by default, but you have to delete it from the field before you save not to have it written twice, just as you described.

**Comment by josh-65** [comment]
In 1.5.67 the only issue is that it renames the drive with the drive letter added on again

**Comment by josh-65** [comment]
Closing since only issue left is #5696
