### ISSUE TITLE
Renaming a shortcut removes the extension

### ISSUE THREAD

**Issue by etaui** [files-community/Files#4709]
**Explain the bug**
When renaming a shortcut file, the extension is removed.

**To reproduce**
1. Create a shortcut file
2. Rename the shortcut file to something that does not have an extension

**Expected behavior**
The shortcut should hide the extension of .lnk (or .url) when renaming the file.

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6361745/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6361746/debug_fulltrust.txt)

**Screenshots**
Add screenshots to help explain your problem if needed.
![image](https://user-images.githubusercontent.com/33045716/115796542-017d0f00-a3a0-11eb-832a-583806102a97.png)
![image](https://user-images.githubusercontent.com/33045716/115796558-06da5980-a3a0-11eb-96dc-bfbf3cd9b69a.png)

**System Information**
Version 10.0.19041 Build 19041
App Version 1.5.0.0

**Additional comment**
none

**Comment by gave92** [comment]
Looks to be fixed in 1.9.22.
