### ISSUE TITLE
Feature: Drag folder onto "+" icon to create new tab

### ISSUE THREAD

**Issue by trulko** [files-community/Files#4710]
**Is your feature request related to a problem?**
It would be nice to be able to drag a folder onto the "+" icon for creating a new tab or onto a blank spot on the tab strip to create a new tab. Chrome/Edge/Firefox support doing this with links, and I have gotten used to doing it in browsers. When you try in Edge, a little arrow pops up too, which is a nice touch!
![image](https://user-images.githubusercontent.com/81886277/115799469-8e2acb80-a3a6-11eb-893f-74ed53320986.png)

**Describe the solution**
Implementing something like I described above would be nice!

**Describe alternatives you've considered**
CTRL+click on a folder to do this would work too, but both would be even better!

**Additional comment**
Thank you for the work y'all are putting into this app, it's amazing!

**Comment by jcedmiston** [comment]
possibly related to #4511 (Use CTRL + Left click for new tab)

**Comment by ELowry** [comment]
Shouldn't the entire title bar act as a drop-point for folders to create new tabs?

A good example of something users will be familiar with could be to look at major browsers (Chrome, Edge, Firefox, etc.) which allow you to drop links into the title bar to create a new tab. In fact, these include the possibility to place the new tab in a specific position using a small indicator:

![image](https://user-images.githubusercontent.com/7792033/177550604-c2f431c6-db09-4ed5-bcac-482b64bd6f01.png)
(Firefox)

Based on the browsers I have access to, it seems that the one spot that doesn't allow URL dropping in the browsers I have access to is the one with the system's minimize/maximize/close buttons.

**Comment by yaira2** [comment]
This can be particularly useful for touch users.

**Comment by yaira2** [comment]
@0x5bfa fyi

**Comment by ashrafmansuri** [comment]
Hi, I'd like to work on this. May I? Also I tried dragging a folder onto the "+" icon it shows the not allowed sign. How do I overcome that?

**Comment by yaira2** [comment]
@ashrafmansuri you will have to add the dropped event.

**Comment by ashrafmansuri** [comment]
> @ashrafmansuri you will have to add the dropped event.

I found the dropped event in BaseLayoutViewModel.cs but I'm not sure where exactly. Can you guide me a little?

**Comment by ashrafmansuri** [comment]
Hi, can anyone help me with the dropped event? I tried but was unable to. Just the hints would do and I can take it from there.
Thanks.

**Comment by denisdekh** [comment]
Alright think I am figuring it out, Drop was never called until one of the Drag events was handled it seems. I will explore this some more and see if I can get the drag and drop to trigger properly

**Comment by xmha97** [comment]
Thanks
