### ISSUE TITLE
Opening Windows directory crashes program

### ISSUE THREAD

**Issue by 01-1** [files-community/Files#4711]
**Explain the bug**
Opening the windows directory crashes the program. Also, one time opening a new tab after opening the Windows directory also crashed the program.

**To reproduce**
1. Open windows directory

Also might be related to preemptive cache of 1

**Expected behavior**
Does not crash

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6362000/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6362001/debug_fulltrust.txt)

**Screenshots**
none

**System Information**
Version 10.0.19041 Build 19041
App Version 1.5.0.0

**Additional comment**
none

**Comment by etaui** [comment]
also happened when i went into Recycle Bin, it might be a problem with large folders (maybe memory?)

**Comment by winston-de** [comment]
Thanks for reporting this. You mentioned preemptive caching, does this issue occur with the preemptive cache feature disabled?

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
