### ISSUE TITLE
Unable to drag or place created Shortcut onto Taskbar

### ISSUE THREAD

**Issue by JackGFuller** [files-community/Files#4713]
**Explain the bug**
Write a clear description of what the bug is.
This capability is available in Win10 File Explorer.

**To reproduce**
1. Go to '....'
4. See the error

**Expected behavior**
Write a clear description of what you expected.
In File Explorer, one can drag an item and pin it to the Taskbar, or drage an item from one folder to another - that is, Move the item.

**Logfile**
Upload the log file here for us to understand your issue better. 
- You can access it from Settings->About->Open log location. 
or 
- Copy the debug.log and debug_fulltrust.log from the following directory, and upload the files here.
`%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 
[debug.txt](https://github.com/files-community/Files/files/6362140/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6362142/debug_fulltrust.txt)

**Screenshots**
Add screenshots to help explain your problem if needed.

**System Information**
 - OS Version: [e.g. Windows 10 20H2 19042.804] (Press WIN + PAUSE/BREAK, use the copy button at the bottom)
 - Edition	Windows 10 Home
Version	20H2
Installed on	‎2020-‎10-‎30
OS build	19042.928
Experience	Windows Feature Experience Pack 120.2212.551.0

 - App version: [e.g. v1.0] (In the app, go to Settings -> About, the version is shown at the top)
 - 1,5,0,0,

**Additional comment**
Add any other comment about the problem here. Does this problem happen again after restarting the app?

**Comment by winston-de** [comment]
Thanks for reporting this. Unfortunately dragging shortcuts is currently not implemented, merging with #3952.

**Comment by JackGFuller** [comment]
Thanks for your response. That's unfortunate, as otherwise I find "Files"
to be a useful app, esp. the use of Tabs.
