### ISSUE TITLE
Library sometimes fails to load items

### ISSUE THREAD

**Issue by winston-de** [files-community/Files#4715]
**Explain the bug**
Sometimes certain libraries will fail to load items, and will show a blank page. It is not fixed by refreshing, but can be fixed by switching layout modes. I have only seen this occur with the Documents and Saved Pictures libraries.

**To reproduce**
1. Go to the Documents library
2. Sometimes it will not load, and show a blank page

**Logfile**
No errors were logged.

**Screenshots**
![image](https://user-images.githubusercontent.com/59544401/115818520-c552aa00-a3b1-11eb-9e21-73bd18d0e7ed.png)

**System Information**
 - OS Version: 19043.962
 - App version: 1.5.23.0

**Additional comment**

**Comment by yaichenbaum** [comment]
@winston-de is this still an issue in the preview version? http://files.community/download/preview

**Comment by winston-de** [comment]
Probably not, haven't run into it for long while
