### ISSUE TITLE
Missing or incorrect shortcuts in tool tips

### ISSUE THREAD

**Issue by TailyFair** [files-community/Files#4718]
**Explain the bug**
Some actions in their tooltips are missing keyboard shortcut descriptions.

Missing:
- [ ] Missing Add new tab (in tabs navbar) should show (CTRL + T)
![image](https://user-images.githubusercontent.com/27275873/115854424-e6a7aa80-a432-11eb-96c9-c960d45b5233.png)

- [ ] Missing in tab right click context (currently no shortcut shown) should show (CTRL + T)
![image](https://user-images.githubusercontent.com/27275873/115854283-c2e46480-a432-11eb-94c0-7124072781c4.png)

- [ ] Incorrect Close tab (currently it shows CTRL + F4), but it should be (CTRL + W)
![image](https://user-images.githubusercontent.com/27275873/115854512-fa531100-a432-11eb-932d-c7c23ce32aa9.png)

**Expected behavior**
Actions that have shortcut, should have it correctly shown in tooltip.

**Comment by Jaiganeshkumaran** [comment]
Ctrl+F4 should also work I think

**Comment by TailyFair** [comment]
CTRL + F4 closes whole application, not specific tab.

**Comment by Jaiganeshkumaran** [comment]
Isn't that Alt+F4?

**Comment by TailyFair** [comment]
Oh,  you're right... I confused CLTR with ALT key 😅
Although I still think that CTRL + W is more common than CTRL + F4 and should be shown in tooltip.

**Comment by yaichenbaum** [comment]
CTRL + F4 is valid, but the main shortcut is CTRL + W.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #4793.
