### ISSUE TITLE
No context menu when pressing on Library folders in home page

### ISSUE THREAD

**Issue by TailyFair** [files-community/Files#4719]
**Explain the bug**
No context menu appears when pressing on Library folders in home page

**To reproduce**
1. Go to '....'
4. See the error

**Expected behavior**
Context menu appears like pressing on Drives.

**Affected version**
1.5.17.0

**Comment by yaichenbaum** [comment]
What version of Files do you have?

**Comment by TailyFair** [comment]
I have 1.5.17.0.

**Comment by yaichenbaum** [comment]
The context menu is only available in `main`.
