### ISSUE TITLE
Home screen refreshing

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#4724]
**Is your feature request related to a problem?**
Home screen doesn't refresh until I reopen the app entirely.

**Describe the solution**
The refresh button and f5 hotkey should be enabled for it.

**Describe alternatives you've considered**
When ever a user goes on the home screen it refreshes.

**Comment by winston-de** [comment]
Thanks for the feedback. Which widgets on the home screen you think need to be refreshed?

**Comment by josh-65** [comment]
Drives mostly

**Comment by winston-de** [comment]
@josh-65 Thanks for the additional info. I believe this can be merged with #2242.
