### ISSUE TITLE
Dragging over a tab or library in sidebar doesn't navigate

### ISSUE THREAD

**Issue by winston-de** [files-community/Files#4726]
**Explain the bug**
Dragging over a tab or a library in the sidebar doesn't navigate to the folder or switch to the hovered tab, respectively. 

**To reproduce**
1. Drag item over library in sidebar
2. Files does not navigate to the library

1. Open 2 tabs in 2 different folders
2. Drag item from one on top of the tab
3. Files does not switch to hovered tab

**Expected behavior**
Files should switch tabs or navigate to the hovered library, when dragged over either.

**Logfile**
No errors.

**Screenshots**

**System Information**
 - OS Version: 19043.962
 - App version: 1.5.23.0

**Additional comment**
Related side note: dragging over a collapsed sidebar item should expand it.

**Comment by yaichenbaum** [comment]
@winston-de dragging an item over a directory should not only navigate to it, it should also the user to drop the item there as well. This used to be the behavior but it looks like it broke in one of the many commits since v1.5.

**Comment by winston-de** [comment]
@yair100 Yeah, I remember you mentioned that. I'm working on a PR with a few drag & drop fixes, I'll include that.
