### ISSUE TITLE
Files wont open no matter what

### ISSUE THREAD

**Issue by Therogamer** [files-community/Files#4731]
Files wont launch/open not matter what.
I tried reinstalling running it as administrator everything it just wont work.

**Comment by yaichenbaum** [comment]
@Therogamer Can you provide the log files and version information?

**Comment by Therogamer** [comment]
I can provide the version log files i cant right now
Version 1.5 Github

**Comment by Therogamer** [comment]
I resolved the issue with store and yes the store version works.
