### ISSUE TITLE
Different display option for different folder type

### ISSUE THREAD

**Issue by minidarknova** [files-community/Files#4732]
Can we have different display option saved for different folder type. For example if a folder is video folder, it should show at a specific size that I assign it to show. If its Music folder, it should show all my music folders in a specific way and size in display option part.
Does that make sense what I am asking?
Explorer already does similar thing.

**Comment by d2dyno1** [comment]
That feature already exists! Make sure you're on the latest version head to **Settings > Files and Folders > Enable individual preferences for individual directories**
