### ISSUE TITLE
bug when right clicking on a jpg or mp4 file 

### ISSUE THREAD

**Issue by matheus1776** [files-community/Files#4734]
Go to any image file or mp4 / video file from windows through the files, Right click on it, an icon will appear as if you were processing / loading the options tab q always appears when you right click, but there , the files freezes, and you can’t access absolutely anything, you can just minimize and close it, when it freezes you try to do any action, like, click again or left click, and it just doesn’t go, freezes and gets the file just selected. 

**Expected behavior**

I expected that when I right-clicked on a mp4 / jpg file it would open the normal options just like when I right-click on any of the two file types in windows explorer.

**System Information**
 Edition	Windows 10 Home
Version	21H1
Compilação do SO	19043.928
Experiência	Windows Feature Experience Pack 120.2212.551.0

 - App version: v1.5.0.0

**Additional comment**
And, yes, this problem occurs even after I restart windows, it occurs even if I restart the app and it occurs even if I kill through the terminal or close it through the task manager, it always freezes in the same way and I have to close it and open it again to defrost / unlock.

**Comment by winston-de** [comment]
Thanks for reporting this bug. This issue was resolved with #4625.
