### ISSUE TITLE
Cannot delete multiple files selected using "SHIFT" key

### ISSUE THREAD

**Issue by karthikeya-Git** [files-community/Files#4735]
**Explain the bug**
when i tried to delete multiple files, i used shift key to select files and then delete key which resulted in bug and windows prompted me to report the bug.

**To reproduce**
1. Go to 'any file path'
2. Click on 'multiple files using SHIFT key'
3. Click on 'DELETE key'
4. See the error

**Expected behavior**
All selected files to be deleted (moved to recycle bin)

**Logfile**
[LocaleMetaData.zip](https://github.com/files-community/Files/files/6370315/LocaleMetaData.zip)
[debug.txt](https://github.com/files-community/Files/files/6370336/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6370337/debug_fulltrust.txt)

**System Information**
 - OS Version: [
Edition	Windows 10 Home Single Language
Version	20H2
Installed on	‎02-‎01-‎2021
OS build	19042.928
Experience	Windows Feature Experience Pack 120.2212.551.0
]
 - App version: [v1.5.0.0]

**Comment by josh-65** [comment]
I don't have this issue so its fixed for the next update or was never broken. Try reinstalling files.

**Comment by winston-de** [comment]
Thanks for reporting this. I cannot reproduce the crash with the steps provided, however the stack trace matches #4316, which is a similar issue, so I'm merging this with it.
