### ISSUE TITLE
Unable to drag selected items to a secondary pane

### ISSUE THREAD

**Issue by osieltorres** [files-community/Files#4740]
**Explain the bug**
Unable to move files/folders dragging over secondary pane.

**To reproduce**
1. Go to Files application
2. Select some items
3. Try moving to secondary pane by dragging them
4. Overlay not block icon appears, not being able to drag the items

**Expected behavior**
Selected items to be moved by dragging them into pane.

**System Information**
 - OS Version: Windows 10 Pro, version 20H2, OS build 19042.928 Experience	Windows Feature Experience Pack 120.2212.551.0
 - App version: 1.5.17.0
 -

**Comment by winston-de** [comment]
Thanks for reporting this, this should be fixed with #4728.
