### ISSUE TITLE
Size of  .rar files with small size not showed correctly

### ISSUE THREAD

**Issue by AndriiHarashchak** [files-community/Files#4741]
**Explain the bug**
 .rar files that have a size smaller than 100kb (as I see on my device) are shoved as "empty" (0B) in folder view and in the "about" context menu.
In the screenshot given below the size of the archives is about 50kb each, but in Files, it`s showed as 0B.

**To reproduce**
Find a .rar file with a size smaller than 100 kb and look at its size.

**Expected behavior**
 To show the correct file size.

**Logfile**
 Nothing to show in log file.
**Screenshots**
![image](https://user-images.githubusercontent.com/63160844/115996564-793d7a80-a5e8-11eb-9251-8ff7691603ce.png)

**System Information**
 - OS Version: release Windows 10 Pro
                       version 20H2
                       installation date	‎05.‎02.‎2021
                       build	19042.928
                       feature pack Windows Feature Experience Pack 120.2212.551.0

 - App version: v1.5 (the latest stable one).

**Additional comment**
This problem is not attached to the session and still occurs all the time I'm using app.

**Comment by cinqmilleans** [comment]
I have not been able to reproduce the problem.

**Comment by AndriiHarashchak** [comment]
@cinqmilleans maybe, I found trouble. It looks like when creating a .rar ( I saw this only with small .rar files) file inside "Files",  the size isn`t correct, but after opening a folder with such files using stock file explorer the size in "Files" becomes correct. And as I suppose the trouble is with reading size from the source.

**Comment by yaichenbaum** [comment]
@AndriiHarashchak is this still an issue in v2.0.34?

**Comment by AndriiHarashchak** [comment]
> @AndriiHarashchak is this still an issue in v2.0.34?

Tested it now. Looks like a file size is correct now (tried to create a file and archive in "Files" and in "Windows Explorer"). The archive from the issue is with the correct size too. Screenshots are given below.
![image](https://user-images.githubusercontent.com/63160844/145879539-f4c58c23-5e86-48ce-9fab-406df7de0dc2.png)
![image](https://user-images.githubusercontent.com/63160844/145880003-9bcbc676-3cc8-4f1f-b55d-95f01fd85c80.png)
