### ISSUE TITLE
Files Closes Unexpectedly

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#4746]
**Explain the bug**
`Files` will close unexpectedly while trying to open a folder, then it loads for around 2s, and suddenly close unexpectedly which only occurs sometimes but stubborn.

**To reproduce**
It occurs suddenly and I didn't try to reproduce it.

**Expected behavior**
`Files` shouldn't close unexpectedly and any task should be done normally.

**Logfile**
Upload the log file here for us to understand your issue better. 
- You can access it from Settings->About->Open log location. 
or 
- Copy the debug.log and debug_fulltrust.log from the following directory, and upload the files here.
`%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 
[debug.txt](https://github.com/files-community/Files/files/6375321/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6375324/debug_fulltrust.txt)

**Screenshots**
Add screenshots to help explain your problem if needed.

**System Information**
 - OS Version: Windows 10 20H2 19042.928
 - App version: v1.5.2.0

**Additional comment**
This problem doesn't occur after restarting the `Files`, **BUT** sometimes it still happens.

**Comment by EcksDy** [comment]
I'm having the same issue.

**Logfile**

[debug.txt](https://github.com/files-community/Files/files/6376463/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6376466/debug_fulltrust.txt)

**System Information**

- OS Version: Windows 10 Pro 20H2 19042.928
- App version: v1.5.0.0 from Microsoft Store

**Additional comment**

I've just updated to 1.5.0.0, and just installed WSL 2. I see that Files has integration with WSL so I'm guessing that could be relevant. Reopening the same directory that led to the crash will not crash again.

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
