### ISSUE TITLE
The installation get stucked at 16%.

### ISSUE THREAD

**Issue by fnfontana** [files-community/Files#4751]
**Explain the bug**
When I try to install the app, the installation get stucked at 16%. I've tried directly by the Microsoft Store and downloading the file here at GitHub.

**To reproduce**
Initiate the installer and wait for it...

**Expected behavior**
Finish the installation and use the program.

**Logfile**
I couldn't finish the installation, so there nos log file.

**Screenshots**
![Bug](https://user-images.githubusercontent.com/8870142/116131427-c2520500-a6a2-11eb-9c10-d80f0a40a5a1.png)

**System Information**
 - OS Version: Windows 10 Pro 1903 18362.836
 - App version: 1.5.0.0
 
**Additional comment**

**Comment by yaichenbaum** [comment]
The msix bundle will only work if you have the required dependencies. Can you try this installer https://files-community.github.io/package.github.io/Files.Package/Files.Package.appinstaller?

**Comment by fnfontana** [comment]
> The msix bundle will only work if you have the required dependencies. Can you try this installer https://files-community.github.io/package.github.io/Files.Package/Files.Package.appinstaller?

Hi Yair, thank you for reply! I've also tried this installer, but still get stuck at 16% of the installation. What is the dependencies which I have to install before?

**Comment by yaichenbaum** [comment]
The app installer should add them all, where is it getting stuck?

**Comment by fnfontana** [comment]
Hello,

After update my Windows to 20H2 version, I was able to use your app.

Thank your for the support!

Em seg., 26 de abr. de 2021 às 17:02, Yair Aichenbaum <
***@***.***> escreveu:
