### ISSUE TITLE
Show when actions would required admin privileges

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#4754]
**Describe the solution**
Like file explorer have an admin shield symbol next to an action that would require it like deleting a file.

**Comment by yaichenbaum** [comment]
This is already implemented in v1.5. Can you add a little more context?

**Comment by josh-65** [comment]
Deleting or renaming won't show that they need admin always with the UAC prompt so a symbol next to the action can show it.

**Comment by yaichenbaum** [comment]
Oh, you mean in the context menus? Does this provide any benefit over the confirm dialog that we already show?

**Comment by josh-65** [comment]
It only appears once for the first time its needed if i was testing actions to see if they need admin i would have to click all of them and restart files in between to see if the admin prompt comes up.  It is slow and annoying especially on lower spec systems. Right clicking to see a symbol can instantly tell me that multiple action's would require admin.

**Comment by yaichenbaum** [comment]
The UAC prompt should always show when trying to take an action that requires admin access.

**Comment by josh-65** [comment]
you sure it only shows up once for me then files is always in admin mode until it closed

**Comment by yaichenbaum** [comment]
@josh-65 Files running in admin mode is something else, the UAC prompt should still come up when you need to take an action.

**Comment by josh-65** [comment]
ok ill make a new issue.
