### ISSUE TITLE
Unable to Select Multiple Folders/Files

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#4756]
**Explain the bug**
Users are unable to select Multiple Folders/Files, it occurs also after I have reopen the `Files` Application.

**To reproduce**
It occurs suddenly and I didn't try to reproduce it.

**Expected behavior**
Users are able to select multiple folders/files.

**Logfile**
Upload the log file here for us to understand your issue better. 
- You can access it from Settings->About->Open log location. 
or 
- Copy the debug.log and debug_fulltrust.log from the following directory, and upload the files here.
`%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 
[debug.txt](https://github.com/files-community/Files/files/6381626/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6381627/debug_fulltrust.txt)

**Screenshots**

https://user-images.githubusercontent.com/69080584/116180874-d7cb3b80-a743-11eb-8359-c65a3b282982.mp4

**System Information**
 - OS Version: Windows 10 20H2 19042.928
 - App version: v1.5.2.0

**Additional comment**
This problem occurs after restarting the Files, but it doesn't happen after I restarted my entire pc.

**Comment by yaichenbaum** [comment]
The v1.5.2 rollout was paused to a couple breaking issues, can you try reinstalling Files to see if it's still an issue?
