### ISSUE TITLE
Unable to Upload Video Through Drag and Drop Feature

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#4758]
**Explain the bug**
As described, `Files` supports Drag and Drop Feature, I am unable to upload video through Drag and Drop Feature to other third party apps, but I am able to drop other file types (.*txt).

**To reproduce**

**Expected behavior**
Users should be able to upload all file types without any restriction extension.

**Logfile**
Upload the log file here for us to understand your issue better. 
- You can access it from Settings->About->Open log location. 
or 
- Copy the debug.log and debug_fulltrust.log from the following directory, and upload the files here.
`%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 
[debug.txt](https://github.com/files-community/Files/files/6381847/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6381850/debug_fulltrust.txt)

**Screenshots**

https://user-images.githubusercontent.com/69080584/116185613-28469700-a74c-11eb-836e-2913e76baa2e.mp4

**System Information**
 - OS Version: Windows 10 20H2 19042.928
 - App version: v1.5.2.0

**Additional comment**
This problem occurs both after I have restarted the app nor restarted my entire pc.

**Comment by josh-65** [comment]
It also doesn't work for log files in 1.5.21

**Comment by winston-de** [comment]
Thanks for the feedback, this issue should be resolved in ``main``.
