### ISSUE TITLE
CAN NOT SHOW  THE WINDOWS HIDDEN FILES

### ISSUE THREAD

**Issue by bieye250** [files-community/Files#4761]
Hi，I'm from China, using Windows 10, and I notice the application can't show the hidden files .  Also,  I have a file named "edge下载", but it doesn't  show (of course, the file can  be found by search-bar ) .
 see the images:![](https://ftp.bmp.ovh/imgs/2021/04/feec52112cdfe6f4.png)

**Comment by TailyFair** [comment]
Are hidden files setting turned on?
![image](https://user-images.githubusercontent.com/27275873/116229352-0f93ac80-a75f-11eb-917c-6fe3f1293005.png)
