### ISSUE TITLE
More Libraries!

### ISSUE THREAD

**Issue by nickolas52468** [files-community/Files#4763]
**Is your feature request related to a problem?**
NO

**Describe the solution**
a way to add more Libraries to Files, like on original explorer

**Describe alternatives you've considered**
add a action for when the user right-click on Libraries, on the side bar, apears a option for create a New Librarie

**Additional comment**
is muth useful then Packeges, bacause is more minimalist and great to use.

**Comment by winston-de** [comment]
Thanks for opening this issue. This has already been implemented, the option is located in the "..." menu in the library cards widget. You can then add folders to that library through the library properties, which you can access by right clicking it. 


https://user-images.githubusercontent.com/59544401/116278674-93d43880-a73b-11eb-869c-8bfaaac2d9e4.mp4

**Comment by nickolas52468** [comment]
strange .. there is no option in the version I have here (1.5.0.0)

**Comment by winston-de** [comment]
My bad, full library support is currently in insider builds, so it isn't available in 1.5. I apologize for the confusion.

**Comment by nickolas52468** [comment]
not bad, so i will look for insider and still wait for it on realease version...
a great good tool  can be costum icons to libraries too... i like to use personal ICONs on special folders 😆
