### ISSUE TITLE
UAC prompt only shows up first time when admin is needed.

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#4765]
**Explain the bug**
When I take an admin action it will only show up the first time after that it will accept all others

**Expected behaviour**
UAC prompt should show up for all admin actions

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6386213/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6386214/debug_fulltrust.log)

**System Information**
 - OS Version: Windows 10 20H2 19042.928
 - App version: v1.5.21.0

**Comment by yaichenbaum** [comment]
I was able to reproduce this in `main`. Thanks for opening the issue.

**Comment by josh-65** [comment]
This seems to have been fixed for me in 1.5.26. Has it in main too?

**Comment by yaichenbaum** [comment]
@josh-65 It's still an issue when deleting items.

**Comment by josh-65** [comment]
Still an issue in 1.5.67

**Comment by josh-65** [comment]
Closing since I don't think this is an issue any more in 2.0.16.0
