### ISSUE TITLE
Click, Drag, Release File Moving

### ISSUE THREAD

**Issue by iamjoelburris** [files-community/Files#4766]
So when dragging files from the app to another app or within itself, one must click the item, release then click a second time to drag selected item. In WinExplorer it is 1 click. Click, drag, release click and it transfers. LOVE your application, but this one hiccup is uber frustrating to me. 1 click-select-drag-drop-release click motion is very very much desired. Thank you!

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.

**Comment by yaichenbaum** [comment]
The changes will be included when we release the next update 🚀

**Comment by iamjoelburris** [comment]
Killer!!!!
