### ISSUE TITLE
Files app freezes when right-clicking in the interface

### ISSUE THREAD

**Issue by TobberH** [files-community/Files#4768]
**Explain the bug**
Opening files App, selecting any drive to see files content will freeze the app interface making it unusable for me.

**To reproduce**
1. Open app
2. Click on any drive or folder
3. Right click anywhere in the interface.
4. App freezes and becomes unresponsive

**Expected behavior**
Expect the app to show context menu or something like that?

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6387626/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6387627/debug_fulltrust.txt)

**System Information**
Edition	Windows 10 Pro
Version	20H2
Installed on	‎3/‎18/‎2021
OS build	19042.928
Experience	Windows Feature Experience Pack 120.2212.551.0

**Additional comment**
Happens every time I open the app from just having installed it so haven't been able to use the App at all.

**Comment by yaichenbaum** [comment]
@TobberH What version of Files do you have?

**Comment by TobberH** [comment]
I'm running latest version 1.5.0.0 from the Microsoft Store. Still have the issue, so app is unusable.

**Comment by yaichenbaum** [comment]
This issue will most likely be resolved when we release v2.
