### ISSUE TITLE
Clicking "OK" in Downloads Properties window crashes the app

### ISSUE THREAD

**Issue by shoker537** [files-community/Files#4774]
If I open Properties of Downloads folder (from sidebar) while being in the main screen (not in any folder) and click "OK" to close it the app crashes.
So if you open any folder and then open Properties of Downloads from sidebar it works fine.

**To reproduce**
1. Open Files
2. Open Properties of Downloads folder from sidebar
3. Click "OK" in Properties

**Expected behavior**
Just close Properties like it closes when any folder is opened.

**System Information**
Windows 10 Pro 20H2 19042.928

**Logs**
[debug.txt](https://github.com/files-community/Files/files/6391115/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6391116/debug_fulltrust.txt)

App version: 1.5.0.0

**Comment by winston-de** [comment]
Thanks for reporting this, merging with #4531
