### ISSUE TITLE
New design

### ISSUE THREAD

**Issue by SiRo24** [files-community/Files#4779]
**Is your feature request related to a problem?**
A clear description of what the problem is.

**Describe the solution**
A clear description of what you want.

**Describe alternatives you've considered**
A clear description of any alternative solutions or features you've considered.

**Additional comment**
Add any other comment or screenshots about the feature request here. What device type/UI layout and app version?

I once updated the Files Program, and I was surprised by a completely refreshed design with rounded corners on many boxes, new context menus, win 10 sun valley-like icons, new pop-up windows, hover and click animations for icons and more. I was really happy about that update, but unfortunately about one day after that, in the next update all those improvements got removed again... 
Can we expect to see this redesign and its new features again in the (near) future?

**Comment by yaichenbaum** [comment]
@SiRo24 Are you in the insider flight group? The new design is currently only for insiders.

**Comment by SiRo24** [comment]
I always installed the latest windows insider versions, and I am currently on "Windows 10 Insider Preview 21364.1 (co_release)"

**Comment by yaichenbaum** [comment]
@SiRo24 The Files insider program is different than the Windows Insider Program.

**Comment by SiRo24** [comment]
Ok, but I never entered that one, even though I could use that version for about one day.. anyway, is there any way to become part of the Files insider program?

**Comment by yaichenbaum** [comment]
Yes! Please join our Discord server for more information.
