### ISSUE TITLE
Hide "Open in Files"

### ISSUE THREAD

**Issue by pklion** [files-community/Files#4781]
**Is your feature request related to a problem?**
I'm using the Files app by default, but it shows the "Open in Files" item in the context menu.

**Describe the solution**
Hide the "Open in Files" item only in Files

**Describe alternatives you've considered**
N/A

**Additional comment**
N/A

**Comment by pklion** [comment]
Oh, why isn't this tagged automatically?

**Comment by yaichenbaum** [comment]
@pklion Can you add more context on the open in files option?

**Comment by pklion** [comment]
![image](https://user-images.githubusercontent.com/78145811/116487666-76ce6f80-a8cb-11eb-8452-376266595fdd.png)

**Comment by yaichenbaum** [comment]
@pklion This isn't part of Files, did you by any chance run the script we made a while back for this?

**Comment by pklion** [comment]
I ran [This script](https://files-community.github.io/docs/#/articles/replace-file-explorer)
So maybe that causes this problem...

**Comment by pklion** [comment]
And FYI "Open in Files" menu only showed in the folder context menu.

**Comment by yaichenbaum** [comment]
That script doesn't add anything to the context menu, we had a different script a while ago on the Wiki but we stopped supporting it a couple months ago.

**Comment by pklion** [comment]
@yair100 
![image](https://user-images.githubusercontent.com/78145811/116497284-f23b1b80-a8e1-11eb-8888-a06c5ef2861f.png)
I think this is adding the "Open in Files" menu, isn't it?

**Comment by yaichenbaum** [comment]
Hmm, if it is, it shouldn't be there. @gave92 do you know what this is doing?

**Comment by josh-65** [comment]
you can go to "HKEY_CURRENT_USER\SOFTWARE\Classes\Directory\shell\openinfiles" in the reg and delete openinfiles folder to remove it. As for the reg file the line @pklion highlighted does add it.

**Comment by gave92** [comment]
Mm those lines are there to open Files instead of explorer e.g. when opening a folder on the desktop. Unfortunately they also add a context menu item :/

**Comment by josh-65** [comment]
I've remove those lines from the registry and it opens files fine from the old explore of desktop the only think i found is that they add the context menu

**Comment by josh-65** [comment]
weirdly when i restarted my pc i get the context menu item again but it show like this "openinfiles"

**Comment by winston-de** [comment]
We could just remove any shell context menu item with the command "openinfiles".

**Comment by yaichenbaum** [comment]
@pklion This issue should be resolved with #4794.
