### ISSUE TITLE
Proposal for icon changes (3)

### ISSUE THREAD

**Issue by XPoppyX** [files-community/Files#4783]
_Part 3 of icon change proposals_

**Before:**

The "**Open in new tab**" and "**Open in new window**" icons are actually outdated so the change is necessary for these two

![Captura de pantalla 2021-04-28 212431](https://user-images.githubusercontent.com/61259627/116491588-3ab5f300-a868-11eb-9e69-784cd27eeb1e.png)

![Captura de pantalla 2021-04-28 212404](https://user-images.githubusercontent.com/61259627/116491577-3558a880-a868-11eb-8257-58fae4923bb8.png)
![Captura de pantalla 2021-04-28 212413](https://user-images.githubusercontent.com/61259627/116491581-37226c00-a868-11eb-80e6-712d3af9041a.png)

--------------

**After:**

Without using the `OldFluentUIGlyphs` font family anymore _(Only custom and Segoe)_

![Captura de pantalla 2021-04-28 223054](https://user-images.githubusercontent.com/61259627/116495702-6ee1e180-a871-11eb-8761-f5c2e099fa56.png)
![Captura de pantalla 2021-04-27 204023](https://user-images.githubusercontent.com/61259627/116491374-b4011600-a867-11eb-99c1-62bb6123ac27.png)
![Captura de pantalla 2021-04-27 204015](https://user-images.githubusercontent.com/61259627/116491379-b5324300-a867-11eb-8bf3-d00a59368b8a.png)

Other extra changes:
- Change the "Eject" icon to another from the mdl2 font family _(visual change is minimal, no screenshot required)_
- Tweak the size of the new "Column view" custom icon. A little smaller because it does not match the size of the other icons of the new segoe fluent icons
- Change the "Preferences" icon on the settings page _(visual change is minimal, no screenshot required - Without using the `OldFluentUIGlyphs` font family anymore)_

**Comment by yaichenbaum** [comment]
@XPoppyX This looks good, are these the last icons using `OldFluentUIGlyphs`?

**Comment by XPoppyX** [comment]
@yaichenbaum I think it is still used in some parts because if I delete that font family the app crashes when clicking on certain options

**Comment by mangoepic** [comment]
i find that the Multitasking maybe shouldn't be exactly the task view symbol?

**Comment by yaichenbaum** [comment]
> i find that the Multitasking maybe shouldn't be exactly the Windows Task View symbol as known from the taskbar?

@mangoepic Do you have any ideas what we can use instead?
