### ISSUE TITLE
When maximising a window, the accent colour is shown for a few frames

### ISSUE THREAD

**Issue by ChildishGiant** [files-community/Files#4784]
**Explain the bug**
When a window is maximised, the new area is shown in the user's accent colour for a few frames.

**To reproduce**
1. Drag a window to the top or press the maximise button
100% reproducible

**Expected behavior**
The window to immediately resize or use the themed colour so as not to flash.

**Screenshots**

https://user-images.githubusercontent.com/13716824/116496832-d4e45e00-a89d-11eb-8e9e-b51aca8198eb.mp4

**System Information**
 - OS Version: 
Device name	DESKTOP-ECO40Q0
Processor	AMD Ryzen 5 1600X Six-Core Processor              3.60 GHz
Installed RAM	16.0 GB
Device ID	BB110B17-97DB-4DCD-A197-CE7E1F37C395
Product ID	00330-80000-00000-AA101
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

 - App version: 1.5.0.0

**Comment by yaichenbaum** [comment]
This appears to be a framework bug with CoreWindow, can you open an issue for this  in the Feedback Hub as it's not specific to Files?

**Comment by ChildishGiant** [comment]
Would there be any way to change it to use the background colour, not the accent?

**Comment by yaichenbaum** [comment]
Unfortunately changing the background isn't something that's supported.
