### ISSUE TITLE
Custom icons aren't used in the favourites bar

### ISSUE THREAD

**Issue by ChildishGiant** [files-community/Files#4785]
**Is your feature request related to a problem?**
I use custom icons for my folders so I can quickly recognise them but in the sidebar they aren't shown
![ApplicationFrameHost_EtwZqAOoLn](https://user-images.githubusercontent.com/13716824/116496901-ff361b80-a89d-11eb-912e-25c25a48188d.png)

**Describe the solution**
Customs icons should be used in the sidebar 🤷 

**Describe alternatives you've considered**
uhm not really sure

**Comment by yaichenbaum** [comment]
Thanks for opening this issue, there is an open PR for this right now, in the meantime, let's continue tracking this in #2472.

**Comment by ChildishGiant** [comment]
Ah sorry about that 😅

**Comment by yaichenbaum** [comment]
No worries! It will hopefully be ready when we ship the next update.
