### ISSUE TITLE
Text color not setting properly when switching to Windows default

### ISSUE THREAD

**Issue by Weilbyte** [files-community/Files#4786]
**Explain the bug**
Switching from `Light` to `Dark` theme works fine but when you switch from `Light` to `Windows default` (in this example, the windows default is dark) the files have black text (resulting in unreadable black-on-black text).

**To reproduce**
1. Navigate to a folder (with files)
2. Go to `Settings > Appearance`
3. Set theme to opposite of Windows default (for me, light)
4. Set theme back to Windows default
5. Exit settings and the files in the folder will have black-on-black text

**Expected behavior**
If switching from Windows default (dark) to light and then back to Windows default, the files text should be white.

**Screenshots**
![image](https://user-images.githubusercontent.com/43392677/116501253-a3c15900-a8b0-11eb-9b66-d2cb066c8183.png)

**System Information**
 - OS Version: Windows 10 Pro 20H2 19042.928
 - App version: 1.5.0.0

**Comment by yaichenbaum** [comment]
Thanks for opening this issue, this issue should be resolved in `main`.
