### ISSUE TITLE
Add animation for opening a file

### ISSUE THREAD

**Issue by mangoepic** [files-community/Files#4788]
**Is your feature request related to a problem?**
Currently the double click animation (in the larger layouts) is just the same as two single clicks. Some programs need a while to start up. It would be nice to have a small reassuring indication that Files is now opening something. Users might try to open the file multiple times

![GIF 29 04 2021 11-04-35](https://user-images.githubusercontent.com/71931749/116527268-ca948500-a8da-11eb-9f62-41250f1eef7d.gif)

**Describe the solution**
Add some kind of double click/opening animation instead of just two single clicks
Some ideas:
- Change the accent color border to white/black for a short moment
- Remove the accent color border to for a short moment
- Flash the accent color into the selection background for a short moment
- Change the mouse pointer to loading mouse pointer for a short time

**Describe alternatives you've considered**
Maybe a short animation for the loading bar on the top?

**Additional comment**
App version 1.5.0.0

**Comment by yaichenbaum** [comment]
Once a user double clicks an item, Files doesn't know when the item is done opening, it's technically possible to try to track it, but it's out of scope for Files.

**Comment by tellmewhy12** [comment]
@yair100 its less about knowing exactly when a file is opened, but more about a general ux hint _that_ a file is trying to open, because there is no visual difference between selecting and opening something

**Comment by yaichenbaum** [comment]
@mangoepic I understand, however, once Files runs the command to open an item, Windows is doing the rest of the work. It's really up to the application that's being launched to let you know what going on.
