### ISSUE TITLE
FR: option for lasttab-behaviour

### ISSUE THREAD

**Issue by torgeros** [files-community/Files#4789]
## Feature Request

I would like to have an option to change the behaviour on closing the last tab.

## Reasons for that

Right now, when you close the last tab, the window closes with it. I like my tabbed windows (ie firefox) to open a new tab when closing the last one.  
I do not like the fact that I can't spam-click the close-button of the tabs until all tabs are closed.

## Suggestion for Implementation

Add a switch in the multitasking-settings which toggles the behaviour from "close window with last tab" to "open new tab when closing the last one"

## Examples

Firefox has an option in `about:config` that does the exact same thing. The option is named `browser.tabs.closeWindowWithLastTab`.

**Comment by hiranmayd** [comment]
Well what if it just redirected you to the home page when you close your last tab and have that setting enabled?

**Comment by torgeros** [comment]
Yeah that is exectly what I was expecting: On closing the last tab, it opens a new empty tab with the home page. Of you could instead just redirect the existing tab to the home page...

**Comment by hiranmayd** [comment]
Yep.

**Comment by hiranmayd** [comment]
Yeah or maybe you can set a custom default page for that scenario too

**Comment by torgeros** [comment]
The default page aka home page can be customized from the settings already

**Comment by hiranmayd** [comment]
yes, but i was talking about being able to be redirected to a different page than just home.

**Comment by torgeros** [comment]
Imo the pages shown on "new tab" and "new single tab because you closed the last one"should be the same.

**Comment by hiranmayd** [comment]
i agree.

**Comment by yaichenbaum** [comment]
We don't have plans to implement this change. We'd like the tab behavior to be consistent with Edge and Chrome.
