### ISSUE TITLE
[Vertical multitasking flyout] Closing tab with Ctrl + W doesn't switch to the previously open tab after closing the active one

### ISSUE THREAD

**Issue by winston-de** [files-community/Files#4798]
**Explain the bug**
Write a clear description of what the bug is.

**To reproduce**
1. Open a few tabs
2. Shrink window until the horizontal tabs are collapsed
3. Press ctrl + W
4. Blank content shown

**Expected behavior**
The previously active tab should be switched to.

**Logfile**
Nothing relevant. 

**Screenshots**
![image](https://user-images.githubusercontent.com/59544401/116619887-ece7cc00-a8f5-11eb-9f6d-1bd31e42bee6.png)

After expanding the window:
![image](https://user-images.githubusercontent.com/59544401/116620153-4e0f9f80-a8f6-11eb-8787-fbdfc18948ee.png)

**System Information**
 - OS Version: 19043.962
 - App version: 1.5.25.0

**Additional comment**

**Comment by yaichenbaum** [comment]
@winston-de I can't reproduce this, are you still seeing this bug?

**Comment by winston-de** [comment]
Nope, seems to be resolved
