### ISSUE TITLE
Bug when trying to delete multiple files (only deletes one at a time)

### ISSUE THREAD

**Issue by skrivskithar** [files-community/Files#4799]
**Explain the bug**
Deletion of multiple selected files is impossible, it only deletes one by one

**To reproduce**
1) select multiple files
2) hit DELETE
3) Confirmation to delete all
4) only deletes the file that was selected first

**Expected behavior**
Deletion of all files

**Logfile**
N/A

**Screenshots**
N/A

**System Information**
 - OS Version:  Windows 10 20H2 19042.804
 - App version: 1.5.0.0

**Additional comment**
N/A

**Comment by puppetsw** [comment]
I can't replicate this issue. Might be fixed?

OS Version: Windows 11
App version: 2.1.2.0

**Comment by yaichenbaum** [comment]
@skrivskithar this issue should be resolved in v2.1.13.
