### ISSUE TITLE
Shadows are broken on 10bit displays

### ISSUE THREAD

**Issue by rafifos** [files-community/Files#4801]
**Explain the bug**

Shadows on Files are broken/blocky when the color depth configuration of the display is set to `10 bpc` (on the NVIDIA Control Panel).

**To reproduce**
1. Go to the `NVIDIA Control Panel`
2. Click on `Change resolution`
3. Set the `output color depth` to **10 bpc**
4. Go to Files
5. Right click anywhere, shadows are already broken at this point.

**Expected behavior**
Shadows should not be blocky.

**Logfile**

- [debug.txt](https://github.com/files-community/Files/files/6402775/debug.txt)
- [debug_fulltrust.txt](https://github.com/files-community/Files/files/6402781/debug_fulltrust.txt)

**Screenshots**

![image](https://user-images.githubusercontent.com/12601769/116643439-72e03300-a947-11eb-9e89-1a8e64f8a2b8.png)

**System Information**
 - OS Version: Windows 10 20H2 19042.928
 - App version: v1.5.0.0

**Additional comment**

--

**Comment by yaichenbaum** [comment]
I believe this is a WinUI issue, can you open an issue on their repo?
