### ISSUE TITLE
no Context menu on image files with Powertoys resize feature enabled

### ISSUE THREAD

**Issue by SiRo24** [files-community/Files#4802]
**Explain the bug**
Write a clear description of what the bug is.

**To reproduce**
1. Go to '....'
4. See the error

**Expected behavior**
Write a clear description of what you expected.

**Logfile**
Upload the log file here for us to understand your issue better. 
- You can access it from Settings->About->Open log location. 
or 
- Copy the debug.log and debug_fulltrust.log from the following directory, and upload the files here.
`%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 

**Screenshots**
Add screenshots to help explain your problem if needed.

**System Information**
 - OS Version: [e.g. Windows 10 20H2 19042.804] (Press WIN + PAUSE/BREAK, use the copy button at the bottom)
 - App version: [e.g. v1.0] (In the app, go to Settings -> About, the version is shown at the top)

**Additional comment**
Add any other comment about the problem here. Does this problem happen again after restarting the app?

I use Files v1.5.17 and Windows 10 Insider Preview 21370.1 (co_release) with Microsoft PowerToys and have the "change image size" feature enabled.

Every time I right-click an image file (for example .jpg .png .ico .bmp, maybe more), to bring up the context-menu, Files freezes. 
I have to manually close it and wait a few seconds before being able to open it again.
This can be really frustrating, when one has many tabs open while organizing or copying files and then the program freezes and all tabs and file transfers are gone. 
When I disable the PowerToys feature to change the Image size, the context menu works fine.

**Comment by SiRo24** [comment]
Edit: 
it's not due to the Powertoys feature, that was just a coincidence.
The right click on images usually doesn't work, only in that case it randomly did.

**Comment by josh-65** [comment]
You will need to upload the log files as it says in the template.

**Comment by josh-65** [comment]
Is this still an issue in V2 for you?

**Comment by SiRo24** [comment]
It works again

Simon Rotter
________________________________

**Comment by BanCrash** [comment]
> It works again

@SiRo24 Thanks for letting us know, feel free to come again to ask if this issue happens to you again ;)
