### ISSUE TITLE
Reordering of Favorite folders

### ISSUE THREAD

**Issue by SiRo24** [files-community/Files#4804]
**Is your feature request related to a problem?**
A clear description of what the problem is.

**Describe the solution**
A clear description of what you want.

**Describe alternatives you've considered**
A clear description of any alternative solutions or features you've considered.

**Additional comment**
Add any other comment or screenshots about the feature request here. What device type/UI layout and app version?

/////////////////////////////////////////////////////////////////////////////////////////

I use Files v1.5.17 and Windows 10 Insider Preview 21370.1 (co_release)

It would be great if one could change the order of the preset and pinned folders on the Favourites list on the left side.
Custom icons for the pinned folders would be fantastic as well.

**Comment by Keefaetana** [comment]
https://github.com/files-community/Files/issues/3094

**Comment by yaichenbaum** [comment]
Merging with #1069.
