### ISSUE TITLE
Deleting content in C: drive doesn't always work

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#4807]
**Explain the bug**
Currently I found that trying to paste files into an admin folder doesn't do it or ask or admin privileges.  Deleting files does show the admin prompt but also doesn't take an action.

**To reproduce**
1. Copy some files/folder
2. Go to 'C:/programs'
3. Right click on some folder
4. click paste (or do ctrl + v)
4. See nothings done

**Expected behaviour**
Ask for admin and do the task.

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6407950/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6407951/debug_fulltrust.log)

**System Information**
 - OS Version: Windows 10 20H2 19042.968
 - App version: v1.5.26

**Comment by gave92** [comment]
Hello pasting and renaming as admin is not implemented yet (#2513)
Only deleting is supposed to work, do you have issues with that too?

**Comment by josh-65** [comment]
did have issues yesterday but its working now

**Comment by josh-65** [comment]
Never mind cant delete content in the c: drive even though it only needs admin access according to file explorer. and the some that don't and that are being used it wont say that it just does nothing.
[debug.log](https://github.com/files-community/Files/files/6446206/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6446207/debug_fulltrust.log)
