### ISSUE TITLE
Feature: Improving the status center UI

### ISSUE THREAD

**Issue by Black-StellarSpectrum** [files-community/Files#4811]
### What feature or improvement do you think would benefit Files?
Files app is great but the only thing is that its file transfer UI is not that great, official windows UI is much better and easy to work with.

### Requirements

- 

### Files Version

2.3.11.0

### Windows Version

10.19043.1899

**Comment by yaichenbaum** [comment]
While we don't have plans to make this change, one of the things we are looking at is an option to pin the status center UI in Files. Please let us know what you think of this idea.

**Comment by josh-65** [comment]
I too like this idea I would much prefer a reskinned version of windows 10 default one. It gives all the information needed and could allow users to see files transfers while the main window is minimized or and a different display.

**Comment by duke7553** [comment]
I think we should ditch the Status Center UI that I built. It has proven to be unintuitive and could be better served by a window displaying information.

**Comment by winston-de** [comment]
> I think we should ditch the Status Center UI that I built. It has proven to be unintuitive and could be better served by a window displaying information.

@duke7553 Personally, I find the status center as it is is much less intrusive than the Windows explorer one, especially for smaller/shorter file operations. I think having a separate window can be helpful (eg. #4627), but more often than not I find the Windows explorer method of managing operations to be inconvenient and just gets in the way. Not to mention, Windows explorer's use of windowing to show operation progress goes against [Microsoft's own design guidelines for utilizing multiple windows](https://docs.microsoft.com/en-us/windows/uwp/design/layout/show-multiple-views#dos-and-donts).

I think the current design could instead be improved upon by adding more management options, like pause, cancel, and maybe even an undo operation button. I also think having progress badges/indicators on the status center button would make it easier to identify the status of ongoing operations. Perhaps similar to how the Edge team does it with their downloads flyout.

Here's a few rough mockups I made for progress indicators/badges:
![image](https://user-images.githubusercontent.com/59544401/116825121-aaff9580-ab42-11eb-8f6a-d307005ae285.png)
![image](https://user-images.githubusercontent.com/59544401/116825525-915f4d80-ab44-11eb-91a1-c4fe66e573ad.png)
![image](https://user-images.githubusercontent.com/59544401/116825547-a9cf6800-ab44-11eb-947f-82115f6aeec3.png)

![image](https://user-images.githubusercontent.com/59544401/116826083-10558580-ab47-11eb-82d1-b6f8a13b54b9.png)

Edge ones:
![image](https://user-images.githubusercontent.com/59544401/116824904-80f9a380-ab41-11eb-964e-08c65708bec8.png)
![image](https://user-images.githubusercontent.com/59544401/116824916-8951de80-ab41-11eb-96db-70c0a85a18f8.png)

**Comment by yaichenbaum** [comment]
> > I think we should ditch the Status Center UI that I built. It has proven to be unintuitive and could be better served by a window displaying information.
> 
> @duke7553 Personally, I find the status center as it is is much less intrusive than the Windows explorer one, especially for smaller/shorter file operations. I think having a separate window can be helpful (eg. #4627), but more often than not I find the Windows explorer method of managing operations to be inconvenient and just gets in the way. Not to mention, Windows explorer's use of windowing to show operation progress goes against [Microsoft's own design guidelines for utilizing multiple windows](https://docs.microsoft.com/en-us/windows/uwp/design/layout/show-multiple-views#dos-and-donts).
> 
> I think the current design could instead be improved upon by adding more management options, like pause, cancel, and maybe even an undo operation button. I also think having progress badges/indicators on the status center button would make it easier to identify the status of ongoing operations. Perhaps similar to how the Edge team does it with their downloads flyout.
> 
> Here's a few rough mockups I made for progress indicators/badges:
> ![image](https://user-images.githubusercontent.com/59544401/116825121-aaff9580-ab42-11eb-8f6a-d307005ae285.png)
> ![image](https://user-images.githubusercontent.com/59544401/116825525-915f4d80-ab44-11eb-91a1-c4fe66e573ad.png)
> ![image](https://user-images.githubusercontent.com/59544401/116825547-a9cf6800-ab44-11eb-947f-82115f6aeec3.png)
> 
> ![image](https://user-images.githubusercontent.com/59544401/116826083-10558580-ab47-11eb-82d1-b6f8a13b54b9.png)
> 
> Edge ones:
> ![image](https://user-images.githubusercontent.com/59544401/116824904-80f9a380-ab41-11eb-964e-08c65708bec8.png)
> ![image](https://user-images.githubusercontent.com/59544401/116824916-8951de80-ab41-11eb-96db-70c0a85a18f8.png)

@winston-de This is spot on with what I discussed with Luke around an hour ago. A lot of users don't even have the latest changes, and the changes you mentioned above will further improve the current design.

**Comment by josh-65** [comment]
In any case features like to and from file paths, current speed, what type it is (copy, move, recycling, perm deleting), how many files/folders are left and what file/folder it currently doing should be added.

**Comment by cinqmilleans** [comment]
An idea to discuss. Replace the Status Center by a new page, and the current button opens a tab with that page (like the chrome download center).

**Comment by Black-StellarSpectrum** [comment]
> > > I think we should ditch the Status Center UI that I built. It has proven to be unintuitive and could be better served by a window displaying information.
> > 
> > 
> > @duke7553 Personally, I find the status center as it is is much less intrusive than the Windows explorer one, especially for smaller/shorter file operations. I think having a separate window can be helpful (eg. #4627), but more often than not I find the Windows explorer method of managing operations to be inconvenient and just gets in the way. Not to mention, Windows explorer's use of windowing to show operation progress goes against [Microsoft's own design guidelines for utilizing multiple windows](https://docs.microsoft.com/en-us/windows/uwp/design/layout/show-multiple-views#dos-and-donts).
> > I think the current design could instead be improved upon by adding more management options, like pause, cancel, and maybe even an undo operation button. I also think having progress badges/indicators on the status center button would make it easier to identify the status of ongoing operations. Perhaps similar to how the Edge team does it with their downloads flyout.
> > Here's a few rough mockups I made for progress indicators/badges:
> > ![image](https://user-images.githubusercontent.com/59544401/116825121-aaff9580-ab42-11eb-8f6a-d307005ae285.png)
> > ![image](https://user-images.githubusercontent.com/59544401/116825525-915f4d80-ab44-11eb-91a1-c4fe66e573ad.png)
> > ![image](https://user-images.githubusercontent.com/59544401/116825547-a9cf6800-ab44-11eb-947f-82115f6aeec3.png)
> > ![image](https://user-images.githubusercontent.com/59544401/116826083-10558580-ab47-11eb-82d1-b6f8a13b54b9.png)
> > Edge ones:
> > ![image](https://user-images.githubusercontent.com/59544401/116824904-80f9a380-ab41-11eb-964e-08c65708bec8.png)
> > ![image](https://user-images.githubusercontent.com/59544401/116824916-8951de80-ab41-11eb-96db-70c0a85a18f8.png)
> 
> @winston-de This is spot on with what I discussed with Luke around an hour ago. A lot of users don't even have the latest changes, and the changes you mentioned above will further improve the current design.

Nice idea, but the current design is too small & I am kinda person who likes to see the whole process plus the window from native windows shows a progress bar which is big and also shows me the transfer speed,<< this makes file transfer in "Files" app feel slow, and since it's a separate window we can minimize it & reopen it through shortcut keys if say I am anther app (I've shortcut keys on my mouse to switch between apps) not only that hovering mouse on taskbar icon it shows me the realtime progress plus progress is also shown by green gradient on taskbar icon which is very underrated but very useful features so that the main reason for me to want that native transfer UI.
Thanks.

**Comment by TailyFair** [comment]
I would like to add additional idea. Currently it seems that in status UI only active transfers are visible.
It would be great to see at least few last file transfers to verify that something was completed.

**Comment by josh-65** [comment]
I think that might be better as a windows notification as then there's a sound and popup on the main display. Action centre on windows could log it and users can see the ones done there.

I think the status page should pop out like the preview pane. that way the users could adjust the width and it more consistent with the rest of the app.

**Comment by esibruti** [comment]
For the whole conversation that I've been watching, I'll give my opinion: the current state center needs to be improved, this is an inescapable fact, it has to be more appealing and easier for the user to understand how it works.  Therefore, I propose the following idea: could we make a state center like something similar to the Windows notification center? From the way I am saying it is a bit complicated but I am going to make a concept this week. Once you’re done, I’ll post it here or on the discord. But to explain it out loud, we would do something similar to the Windows notification center. It has the icon, we load it there and there will be the part of the notifications that in this case will be the operations in progress and within that notification would have the button to pause and cancel. Modern ProgressBar, with the percentage and if you wanted to see what was going on, you had the button with more details for that. I think it would look beautiful, appealing and modern. I promise, I'll do a concept this week.

**Comment by yaichenbaum** [comment]
I just want to give an update on this issue. We plan to continue using a similar UI to what we already have. The plan is to improve the UI on the status bar to indicate the overall progress of all operations, and to update the icon depending on the status. We are also working on improving the reported progress.

**Comment by hiranmayd** [comment]
TBH, having a progress indicator is the best solution as it grabs the user's attention.
The way it works currently involves unnecessary navigation and it can be reduced by something like this : 
This is a concept I had made for a personal project which had status in the side-bar but you can adjust that to your liking
![Figma_kcaXakEFbN](https://user-images.githubusercontent.com/60701764/118095692-00af2a00-b3ee-11eb-9e6a-ef51dacc0e5d.png)
![Figma_7kEAFAZ45W](https://user-images.githubusercontent.com/60701764/118095699-0147c080-b3ee-11eb-8e11-e10dea0b9b8f.png)

**Comment by esibruti** [comment]
> TBH, having a progress indicator is the best solution as it grabs the user's attention.
> The way it works currently involves unnecessary navigation and it can be reduced by something like this : 
> This is a concept I had made for a personal project which had status in the side-bar but you can adjust that to your liking
> ![Figma_kcaXakEFbN](https://user-images.githubusercontent.com/60701764/118095692-00af2a00-b3ee-11eb-9e6a-ef51dacc0e5d.png)
> ![Figma_7kEAFAZ45W](https://user-images.githubusercontent.com/60701764/118095699-0147c080-b3ee-11eb-8e11-e10dea0b9b8f.png)
> 
> 

This concept is very beautiful. It would be interesting to see something like that in the Files.

**Comment by hiranmayd** [comment]
Thanks.

**Comment by ealap** [comment]
If you are still open to ideas on this one, I hope you would still consider taking inspiration from the Downloads UI in web browsers, from showing a progress UI at the bottom to having a full page that can be accessed from menus or keyboard shortcut (ctrl+j)

**Comment by matthiscock** [comment]
Im fairly new to files, and its superb
I agree with comments above, something on its own page, would be sensible, showing speed, number of, number left

I will point out, i missed the fact that it was copying, so what happens when you initialize a copy needs to highlight to the user that it is underway and they can inspect it by clicking 'here'

ITs one of those things, as a new user I hold the real feedback of missing it - and i would def stress that while making a 'status of copies' is maybe future dev, ensuring that a user knows that the copy is at least underway a critical issue.

**Comment by KeremArdicli** [comment]
We can make window tab change color (fill with light transparent green) like a progress bar. Similar idea is implemented by chrome at app icon on taksbar for downloads.

**Comment by Josh-65** [comment]
That proberly wont be possible since WinUI doesnt support that by default and would invole a custom tab interface witch would be difficult to maintain. Plus theres already the progress ring and icon that browers use.

**Comment by yaichenbaum** [comment]
> We can make window tab change color (fill with light transparent green) like a progress bar. Similar idea is implemented by chrome at app icon on taksbar for downloads.

This is already supported

**Comment by Josh-65** [comment]
I presume they mean the actual tabs in Files.

**Comment by KeremArdicli** [comment]
> I presume they mean the actual tabs in Files.

I indeed meant the tabs within the files window.

**Comment by Josh-65** [comment]
New thing I notice is that when lots of files are being discovered to run an operation, Explorer will show that and how many have been found with Files it just looks like it frozen at 0%.

**Comment by yaira2** [comment]
Merging with #11265
