### ISSUE TITLE
german translation problem in preferences

### ISSUE THREAD

**Issue by torgeros** [files-community/Files#4815]
The German translation has a problem in the settings:

<img width="500" src="https://user-images.githubusercontent.com/67151313/116812037-d4252380-ab4c-11eb-96b2-902909bfc9ef.png">

The last entry *"Unter Bibliotheken in der Seitenleiste anzeigen"* translates to *"show in sidebar under libraries"* which does in no way describe the functionality of the switch.

---

*"Bibliotheken in der Seitenleiste anzeigen"* (*"show libraries in sidebar"*) would be better.

**Comment by torgeros** [comment]
if someone tells me where to change the translations, I will fix this myself.

**Comment by gave92** [comment]
Hello @torgeros, thanks for you interest in improving Files. You can find documentation about translating Files [here](https://files-community.github.io/docs/#/articles/translating-files). 

@yair100 I see that the docs state that installing Visual Studio is required, isn't that too much?  Do you know if there's a "standalone" editor for xlf files? Any text editor would probably be enough.

**Comment by torgeros** [comment]
thanks! VS is installed so that does not matter for me

also [VS-Code](https://code.visualstudio.com/) seems to have an extension for xlf files: [nab al tools](https://marketplace.visualstudio.com/items?itemName=nabsolutions.nab-al-tools)

**Comment by torgeros** [comment]
I am going to look into this.

maybe I can improve some other parts of the DE translation, too.

**Comment by torgeros** [comment]
in regards to the "language editor", here is a standalone tool to edit those files: https://developer.microsoft.com/en-us/windows/downloads/multilingual-app-toolkit/

**Comment by yair100** [comment]
> Hello @torgeros, thanks for you interest in improving Files. You can find documentation about translating Files [here](https://files-community.github.io/docs/#/articles/translating-files).
> 
> @yair100 I see that the docs state that installing Visual Studio is required, isn't that too much? Do you know if there's a "standalone" editor for xlf files? Any text editor would probably be enough.

@gave92 Visual Studio shouldn't be required, the editor linked there should be enough.
