### ISSUE TITLE
Files Closes

### ISSUE THREAD

**Issue by michaelmckelvey** [files-community/Files#4818]
**Explain the bug**
Write a clear description of what the bug is.

**To reproduce**
1. Go to '....'
4. See the error

**Expected behavior**
Write a clear description of what you expected.

**Logfile**
Upload the log file here for us to understand your issue better. 
- You can access it from Settings->About->Open log location. 
or 
- Copy the debug.log and debug_fulltrust.log from the following directory, and upload the files here.
`%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 

**Screenshots**
Add screenshots to help explain your problem if needed.

**System Information**
 - OS Version: [e.g. Windows 10 20H2 19042.804] (Press WIN + PAUSE/BREAK, use the copy button at the bottom)
 - App version: [e.g. v1.0] (In the app, go to Settings -> About, the version is shown at the top)

**Additional comment**
Add any other comment about the problem here. Does this problem happen again after restarting the app?
As click down through folders (drive, documents, folder, subfolder) drive closes before I reach my destination.  At this point is is unusable for me.

**Comment by yaichenbaum** [comment]
We need a little more information from you in order to investigate this issue, please reopen this issue once you have filled out the issue template.

**Comment by michaelmckelvey** [comment]
1.  Open Files
2.  Click on Documents
3.  Scroll down to Revit & double click
4.  Double click on Revit Pure
5. Files closes

I expected Files to stay open so I could access the file I wanted to open.

Windows 10 20H2

Files 1.5.0.0

This happens every time I try to use Files.

[debug.txt](https://github.com/files-community/Files/files/6412072/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6412073/debug_fulltrust.txt)

**Comment by yaichenbaum** [comment]
@michaelmckelvey Thanks for the detailed information.

**Comment by gave92** [comment]
@michaelmckelvey Could you try the following? (I'd like to know if this only happens in details view)
1. Turn Off "Enable individual preferences for individual directories" in Settings > Files and Folders
2. Set Tiles or GridView layout mode
3. Try to trigger the crash

**Comment by michaelmckelvey** [comment]
I turned off "Enable individual preferences, etc".

Now it still crashed once with small grid bud didn't other times.

It didn't crash after several tries with tiles and medium & large grid.

It still crashes with Details.

**Comment by gave92** [comment]
Merging with #4304. Will be fixed by the new details view which is in the work.
