### ISSUE TITLE
Spacebar doesn't trigger QuickLook

### ISSUE THREAD

**Issue by Dylan-Osborne** [files-community/Files#4823]
**Explain the bug**
Selecting a file and pressing spacebar doesn't open QuickLook.

**To reproduce**
1. Select a file.
2. Press spacebar.
3. QuickLook doesn't open.

**Expected behavior**
QuickLook should open for the selected file.

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6413060/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6413061/debug_fulltrust.log)

**Screenshots**
Add screenshots to help explain your problem if needed.

**System Information**
 - OS Version: Windows 10 20H2 19042.928
 - App version: v1.5.26.0

**QuickLook Information**
 - Version: v3.6.11
 - Microsoft Store Version

**Additional comment**
Restarting and resetting Files does not appear to fix the issue.
QuickLook works perfectly from the the built-in File Explorer.
This issue may be similar to #3823, however I think it's different as that issue's logs indicate that QuickLook was not detected while my logs indicate that QuickLook was detected (...FilesFullTrust.QuickLook|QuickLook detected: True|).

**Comment by josh-65** [comment]
i think they removed support for it just didn't remove the credits in settings

**Comment by Dylan-Osborne** [comment]
I know they recently removed the unnecessary QuickLook item from the context menu, but as far as I'm aware it should still work when pressing spacebar.

I don't think this is due to any recent changes either, I've had this issue for quite a while.

**Comment by gave92** [comment]
Yeah quicklook is still supported by pressing spacebar.
@Dylan-Osborne could you post a screenshot of how a context menu appears in Files for you?

**Comment by Dylan-Osborne** [comment]
@gave92 For a simple .txt file the context menu looks like this
![image](https://user-images.githubusercontent.com/46000533/116871593-c89d2f80-ac14-11eb-8d73-9e7a78446214.png)

**Comment by yaichenbaum** [comment]
> Yeah quicklook is still supported by pressing spacebar.
> @Dylan-Osborne could you post a screenshot of how a context menu appears in Files for you?

@gave92 QuickLook was removed from the context menu so we might need the log file. Either way, I think this issue was resolved when the issue with shortcuts not working in the details layout was fixed.

**Comment by gave92** [comment]
Yeah I was asking to make sure it wasn't an issue with the ftp but it looks all right ;)
Can't find the commit related to fixing the shortcuts.

**Comment by yaichenbaum** [comment]
@gave92 It was a couple days ago, but I can't test it right now because it's crashing in release mode 😄.

**Comment by rusti4** [comment]
Also have this issue

**Comment by RafaelPereiraSilva** [comment]
I'm facing this same issue =/ Spacebar doest not do anything

**Comment by RafaelPereiraSilva** [comment]
I was having this issue, but i realised I needed to reopen Files so quicklook could apply on the app haha

**Comment by daniel-a-melo** [comment]
At some point spacebar to enable QuickLook stopped working on my computer. Still broken on 2.0.0

**Comment by yaichenbaum** [comment]
This issue is resolved in `main`.
