### ISSUE TITLE
Customisation of right click pop out

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#4824]
**Is your feature request related to a problem?**
Now a days there are many different right click options. I wish I could chose what ones were in the top icon only bar and in the icon text version. also to remove options entirely like the layout, refresh and open in terminal (windows terminal adds it own that shows in whitespace and on files/folders) button when clicking on white space.

**Describe the solution**
In settings there could be a category called right click menu and it could have this format. with graphical UI of course. -- is an indent

quick actions bar
--option 1
--option 2

Icon and text
--option 1
--option 2

more overflow
--option 1
--option 2

Disabled
--option 1
--option 2

**Comment by winston-de** [comment]
Thanks for this feedback. Merging with #3966.
