### ISSUE TITLE
Live Refresh

### ISSUE THREAD

**Issue by dazlab** [files-community/Files#4830]
**Is your feature request related to a problem?**
When performing any file operation that changes the structure, adding new files, deleting files, new folders etc. you have to manually click refresh to update the view.

**Describe the solution**
Upon completing any operation that changes the view, it should automatically update and display the changes.

**Describe alternatives you've considered**
None

**Additional comment**
Currently using version 1.5.

**Comment by josh-65** [comment]
It should alrady do that. You will properly have to upload the logs here.(settings > about > open log folder > upload debug and debug_fulltrust)

**Comment by dazlab** [comment]
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6425904/debug_fulltrust.txt)

Just tried it now, and no. I had to refresh the view to see the newly created file. To recreate: choose a directory, right-click and select New Text Document. It creates the document, but it doesn't update the current view until you manually refresh.

**Comment by josh-65** [comment]
Are you trying to make the files in L: or P: drives as they are network locations and that's the only area it won't refresh automatically for me.

**Comment by dazlab** [comment]
Yes, my user profile is a network location. However, I tried doing it in the root of C: and again no live refresh. Specifically when trying to create a .txt file. Seemed to work when creating a directory. 

Can you confirm?

**Comment by dazlab** [comment]
I will try that, thanks. It also doesn't seem to show shortcuts, but I'll see what it's like after a re-install.

**Comment by josh-65** [comment]
network drives don't show shortcuts yet. there's an issue open for that

**Comment by gave92** [comment]
Merging with #2042
