### ISSUE TITLE
Date modified is incorrect on some files

### ISSUE THREAD

**Issue by stevenbrix** [files-community/Files#4835]
**Explain the bug**
Date modified is incorrect on some files, but it doesn't seem to be all.

See screenshot below, i think it sums up the problem pretty well:
![image](https://user-images.githubusercontent.com/9649518/117076013-9958f200-acea-11eb-854e-b83a2757036f.png)

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6424185/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6424186/debug_fulltrust.txt)

**Screenshots**
Add screenshots to help explain your problem if needed. (see above)

**System Information**
 - OS Version: 10.0.21370.0
 - App version: 1.5.0.0

**Additional comment**
It looks like restarting the app fixed it.

**Comment by stevenbrix** [comment]
Seems similar to #2917, but since this isn't just being off by a few hours, i filed a new issue

**Comment by winston-de** [comment]
Thanks for reporting this. Could you please check if caching is enabled (Settings -> Experimental -> Cache files and folders for better performance)? If it is enabled, does the issue occur when it's disabled?
