### ISSUE TITLE
Slow loading of large folders

### ISSUE THREAD

**Issue by Shaheer-Mirza** [files-community/Files#4836]
**Is your feature request related to a problem?**
Yes, The loading time of folders containing lots of files is considerable.

**Describe the solution**
My Desktop contains lots of files and when I open my desktop folder using this application, it takes about 10 seconds to show all the files.

**Describe alternatives you've considered**
Please improve the performance as it may solve the problem.

**Additional comment**
The latest version of the app is installed.

**Comment by yaichenbaum** [comment]
@Shaheer-Mirza What version of Files & Windows do you have?

**Comment by Shaheer-Mirza** [comment]
Windows : 20H2

![image](https://user-images.githubusercontent.com/83059821/117162267-1021e800-addc-11eb-851b-53c58975f17d.png)

Files: 1.5.0.0

![image](https://user-images.githubusercontent.com/83059821/117162373-2465e500-addc-11eb-9fd1-cc54f5a95013.png)

**Comment by yaichenbaum** [comment]
@Shaheer-Mirza Is this still an issue if your turn off the option to cache items?

**Comment by Shaheer-Mirza** [comment]
I am observing the changes for the Cache settings.
One more issue. When I open the new Tab of the application, sometimes I do not see the storage bar of the drives. The screenshots are attatched.

![ApplicationFrameHost_2AVTMUU1mI](https://user-images.githubusercontent.com/83059821/117178264-4ca91000-adeb-11eb-86dd-5fdd561ba4af.png)
![0Txf5FETym](https://user-images.githubusercontent.com/83059821/117178269-4e72d380-adeb-11eb-8bf0-4721669a63e4.png)

**Comment by yaichenbaum** [comment]
@Shaheer-Mirza This is a known issue. It will hopefully be resolve in v2.

**Comment by Shaheer-Mirza** [comment]
Both cache on or off takes about the same time.

**Comment by Shaheer-Mirza** [comment]
Please try to add an online cloud manager in the application.
Helpful screenshots are attatched.
![image](https://user-images.githubusercontent.com/83059821/117244017-b956f580-ae51-11eb-9de8-d2f397394fcb.png)
![image](https://user-images.githubusercontent.com/83059821/117244037-c378f400-ae51-11eb-8a0a-dfb294499c34.png)
![image](https://user-images.githubusercontent.com/83059821/117244062-cffd4c80-ae51-11eb-9ce0-49bac1855e99.png)
