### ISSUE TITLE
Problem with Libraries(again)

### ISSUE THREAD

**Issue by rounk-ctrl** [files-community/Files#4840]
**Explain the bug**
When i click documents in libraries section, the blue bar jumps to the documents from Favorites Section.
Only happens with Documents, nothing else.

**To reproduce**
1. Enable Libraries (if not already).
2. Click on Documents under Libraries.
3. See Bug.

**Expected behavior**
To see the blue bar where it should've been

**Screenshots**
![Reference](https://rounk.is-inside.me/DHpreuwE.gif)

**System Information**
 - OS Version: Windows 10 21H1 (19043.962)
 - App version: 1.5.0.0

**Comment by yaichenbaum** [comment]
This issue should be resolved in `.main`.

**Comment by rounk-ctrl** [comment]
oh ok
