### ISSUE TITLE
Add option to create symlinks

### ISSUE THREAD

**Issue by pozm** [files-community/Files#4842]
**Is your feature request related to a problem?**
A clear description of what the problem is.
No.
**Describe the solution**
A clear description of what you want.
I would like to be able to create symlinks from within the applications as currently you would have to use the command line with the command mklink.
**Describe alternatives you've considered**
A clear description of any alternative solutions or features you've considered.
shortcuts, but they do not perform like symlinks as with symlinks they are a direct portal. 
**Additional comment**
Add any other comment or screenshots about the feature request here. What device type/UI layout and app version?

**Comment by itsmeboy0** [comment]
This is already possible in windows explorer via the [Link Shell Extension](https://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html). The only problem I have is that the "Link Properties" is missing in Files.

![image](https://user-images.githubusercontent.com/75471378/140675605-01727d83-373a-4044-94e7-2be74a6f4f4b.png)

**Comment by Josh-65** [comment]
Merging with #9991
