### ISSUE TITLE
Show linux hidden folders

### ISSUE THREAD

**Issue by ghost** [files-community/Files#4848]
Hi there,
Is there an option to see linux hidden folders, the ones that have ' . ' dot in begining of their name?
cheers

**Comment by yaichenbaum** [comment]
I don't think it's any different than showing regular hidden folders, do you have the option to view hidden items turned on?

**Comment by minidarknova** [comment]
Yes I have that option on, and I can see windows hidden folder but not linux aka the ".downloads" for example.

**Comment by dhbtfs** [comment]
Please consider adding this feature as soon as you can. I am literally waiting on this feature to ditch old windows explorer.

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
