### ISSUE TITLE
How to set this app as the default file explorer app in windows 10

### ISSUE THREAD

**Issue by ShobanChiddarth** [files-community/Files#4853]
This is better than the default file explorer app. How to set this as the default? (This should open whenever choosing download location in browser or uploading files to some sites or even when clicked on path links and every other file things)

How?

**Comment by Jaiganeshkumaran** [comment]
@ShobanChiddarth See https://files-community.github.io/docs/#/articles/replace-file-explorer

**Comment by ShobanChiddarth** [comment]
Thanks
