### ISSUE TITLE
Precise dates

### ISSUE THREAD

**Issue by Twentydragon** [files-community/Files#4854]
### Problem
In the new Files application, the dates/times shown default to a "fuzzy" format, showing relatively how long ago they were created or last modified. However, "3 days ago" and so on break the format of simply showing the exact date and time _(Fig. 1)_.

### Solution
It would be useful for there to be an option under `Settings > Appearance` or `Settings > Preferences` to show exact dates/times instead of fuzzy ones. This should only be an alternative to fuzzy dates, not a replacement.

### Current alternatives
The details pane does show exact dates/times, but this can be cumbersome to use, especially when using a secondary pane or working with a folder that contains long file names. The details pane also cuts off the headings and date/time even with a fairly generous width allowed _(Fig. 2)_.

### Images
Fig. 1: sorting by date in Files
![image](https://user-images.githubusercontent.com/9030918/117421660-f9fb5100-aedb-11eb-8348-7593f48bdf7b.png)

Fig. 2: the default width of the preview pane truncates information and headers
![image](https://user-images.githubusercontent.com/9030918/117421806-1e572d80-aedc-11eb-8e57-438dc55b6926.png)

**Comment by winston-de** [comment]
Thanks for opening this well-detailed request.

Regarding the text cutoff issue the details pane, the design is being updated to fix that. 
![image](https://user-images.githubusercontent.com/59544401/117476772-13b78b00-af12-11eb-9ef8-811679366637.png)

**Comment by yaichenbaum** [comment]
@Twentydragon You can already change this behavior by changing the date format to system.

**Comment by Twentydragon** [comment]
> 
> 
> @Twentydragon You can already change this behavior by changing the date format to system.

My setting had already been in System mode, but it appears that changing to Application, refreshing, changing back to System, and refreshing again fixed the formatting.

However, this only sticks until the next time I open Files; then it's right back to the mixed display.

Upon opening with System already set:
![image](https://user-images.githubusercontent.com/9030918/117507853-dd473380-af44-11eb-9cc8-5bb4135ab6f6.png)

Changing it to Application, then refreshing:
![image](https://user-images.githubusercontent.com/9030918/117507563-775aac00-af44-11eb-85f5-9b5b25b1b71d.png)

Changing it to System, then refreshing again:
![image](https://user-images.githubusercontent.com/9030918/117507921-f9e36b80-af44-11eb-87e9-4dcf4ee4a292.png)

**Comment by yaichenbaum** [comment]
Merging with #2207.
