### ISSUE TITLE
Copy / Delete progress bar

### ISSUE THREAD

**Issue by esysfound** [files-community/Files#4859]
**Is your feature request related to a problem?**
A clear description of what the problem is.

Not clear when a copy is complete -especially with multiple files

**Describe the solution**
A clear description of what you want.

Simple "progress bar" showing % of copy complete updating in real time.

**Describe alternatives you've considered**
A clear description of any alternative solutions or features you've considered.

**Scope**

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Additional comment**
Add any other comment or screenshots about the feature request here. What device type/UI layout and app version?

**Comment by josh-65** [comment]
There is a percentage for the on going tasks it just doesn't work well. they are improving it in #4811
