### ISSUE TITLE
Date display format is inconsistent in Dual Pane mode at times

### ISSUE THREAD

**Issue by bartvanandel** [files-community/Files#4874]
**Explain the bug**
See attached screenshot. Left pane uses a different date format than the right.

Looks like Date format setting isn't applied correctly in Dual Pane mode. This happens when opening a new Dual Mode tab when the current setting is set to "Application" and opening a dir in both panes. When the current setting is "System", date formats in both panes of a new Dual Mode tab are the same.

Switching the date format setting doesn't seem to have (full) effect on dual mode tabs that are already open. I tried switching back and forth while dual mode tabs were already open, but the setting didn't seem to be applied. Only new tabs use the setting.

I checked BTW that the problem wasn't caused by one of the panes showing a OneDrive folder. That didn't make any difference though.

**To reproduce**
1. In settings, set Date format to "Application" and make sure Dual Pane mode is enabled
2. Open a new Dual Pane tab
3. Open a directory in both panes
4. See the error

**Expected behavior**
Both panes use the configured date format.

**Logfile**
Maybe later if required

**Screenshots**
![Files - Date format issue in Dual Pane tab](https://user-images.githubusercontent.com/1194804/117638806-85e2d680-b183-11eb-992a-e791ae2abe14.png)

**System Information**
 - OS Version: Windows 10 20H2 19042.964
 - App version: 1.5.0.0

**Additional comment**
-

**Comment by yaichenbaum** [comment]
@bartvanandel is this still an issue in the preview version? https://files.community/download/preview
