### ISSUE TITLE
Network drives don't automatically refresh

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#4875]
**Explain the bug**
Deleting, copying, moving, creating file or folder wont refresh automatically

**Expected behaviour**
It should refresh contents like any attached storage devices

**Logfile**
[debug_fulltrust.log](https://github.com/files-community/Files/files/6453341/debug_fulltrust.log)

**System Information**
 - OS Version: Windows 10 20H2 19042.928
 - App version: v1.5.26

**Comment by yaichenbaum** [comment]
Merging with #2042.
