### ISSUE TITLE
Incompatibility with Google Drive Filestream.

### ISSUE THREAD

**Issue by MrJeff47** [files-community/Files#4878]
**Explain the bug**
I'm triyng to use Google Drive in Files in the same way i used to use in Explorer, it something like the "Files by Demand" in OneDrive, i use this in work, but, the firt one folders in Google Drive are "hidden" in Files, but i can access those folders by copyng the directory from Explorer, however, some folders crashes the app, making it close itself, that problem not happen in Explorer.

**To reproduce**
1. Go to "Your Computer" section
2. Click on 'Google Drive' folder, notice that doesnt show anything
3. Copy directory link from Explorer, paste on Files than it opens some folders
4. Some folders inside that one that has open by copyng the directory from Explorer crash the Files.

**Expected behavior**
In Explorer i can access all these files and folders almost as i use the OneDrive, that "Files by demand" feature. But i can tell that even on Explorer Google Drive crashes sometimes when the folder is too heavy, but it only take some seconds to recover.

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6459862/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6459863/debug_fulltrust.txt)

**Video showing the bug and comparison with what happens in Explorer**

https://user-images.githubusercontent.com/79664514/117831128-aaee4c80-b24a-11eb-9c40-1c146238e3b3.mp4

**System Information**
 - Edição	Windows 10 Home
Versão	20H2
Instalado em	‎21/‎10/‎2020
Compilação do SO	19042.964
Experiência	Windows Feature Experience Pack 120.2212.2020.0

 - App version: 1.5.2.0

**Additional comment**
Its a long time issue, i thought it was a Google Drive problem, but it has many updates and never change this issue, so i'm assuming it as a Files bug or some incompatibility

**Comment by Fairydx** [comment]
Mine works fine 🤔
In version from Microsoft Store, version 1.5.0.0

**Comment by josh-65** [comment]
Apparently 1.5.2 was broken you should have an update in the store or msixbundle on GitHub to fix it

**Comment by MrJeff47** [comment]
Thank you guys for the attention, but how do i download this update on GitHub? Sorry, i'm kinda new in here 😅

**Comment by josh-65** [comment]
You might have to uninstall the one you have currently or use the Microsoft store as it will likely reset your settings but https://github.com/files-community/Files/releases/download/v1.5/Files-1.5.Msixbundle  download that then click on it. it should open a windows you can click install

**Comment by MrJeff47** [comment]
As you said, apparently this is a 1.5.2 bug, the 1.5 works perfectly, thank you so much! 😄 Its even faster now.
