### ISSUE TITLE
Path bar only allow clicking on the text to navigate

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#4879]
**Explain the bug**
When I try to go somewhere in the path the text is the only clickable part even though the is a button around it that highlights. it should trigger it with the whole button.

**Comment by duke7553** [comment]
@josh-65 You're going to have to provide us more information like what version of the app this is.

**Comment by josh-65** [comment]
Whops sorry:
OS version Windows 10 Pro 20H1 19042.964
App version: 1.5.26.0

**Comment by duke7553** [comment]
@josh-65 Thanks!

**Comment by yaichenbaum** [comment]
@josh-65 This issue should be resolved in `main`.
