### ISSUE TITLE
Feature: Show error message when copying/moving large file to FAT32 filesystem

### ISSUE THREAD

**Issue by jh961202** [files-community/Files#4884]
**Explain the bug**
Since FAT32 doesn't support huge size file (>=4GB), Windows will show an alert message when trying to move/copy such file(s) into FAT32 filesystem (i.e. USB Flash Disks), but not in Files.

**To reproduce**
1. Make up an huge enough file that is over 4GB, such as DVD ISO image and so on.
2. Make up a FAT32-formatted drive such as inserting a USB Disk
3. Copy-paste or cut-paste into that FAT32 filesystem
4. See the error, which is nothing happens

**Expected behavior**
Files should show a message tell users this filesystem does not support files which sizes exceeds 4GB

**Logfile**
Logfile seems like didn't logged anything related to this issue

**Screenshots**
(No error message showed up, so no screenshots could provided)

**System Information**
 - OS Version: Windows 10 Pro 20H2 19042.964
 - App version: v1.5.2.0

**Comment by yaira2** [comment]
Thank you for your feedback

**Comment by yaira2** [comment]
This feature is implemented in our dev branch and will be included in the next release.
