### ISSUE TITLE
Missing file extension on new file creation

### ISSUE THREAD

**Issue by Noxdor** [files-community/Files#4885]
**Explain the bug**
When I want to use Files to create a new file of a specific type (e.g. a word document or an excel document) it doesn't add any file extension. For example I click to create an Excel file and give it the name "test". It doesn't create the file "test.xlsx" but "test". Same happens with any other file type, Word, txt etc.

**To reproduce**
1. Go to any folder
2. Right click -> new
3. Choose any type of file you want to create
4. Insert a name
5. See that the new file has no extension

**Expected behavior**
The file should have the correct extension for the chosen type.

**Logfile**
Those contain personal information and I won't publish them here online. Having a look at them I couldn't find any activity related to the file creation, but maybe you can tell me, what I should find in that specific line.

**Screenshots**
![image](https://user-images.githubusercontent.com/64439978/117955782-b0b26380-b318-11eb-8b13-097618de3726.png)

**System Information**
 - OS Version: Windows 10 Version	10.0.19042 Build 19042
 - App version: 1.5.0.0

**Comment by josh-65** [comment]
if you are clicking on new file you have to add it while naming it like .txt for text documents

**Comment by Noxdor** [comment]
Well I'm sorry but that makes no sense! Why would I choose the file type then anyway? I don't want to remember every file extension just to create basic files. I'm not talking about the blank file option obviously, I'm talking about the specific Excel, Word, PP, Textfile, etc. types.

![image](https://user-images.githubusercontent.com/64439978/117995082-537ed800-b341-11eb-97d4-8bbf3f1d34db.png)

**Comment by josh-65** [comment]
ah I was talking about the blank file option were you have to add the extension yourself. i don't have MS office so I cant try that but it does work for me with open office and the zip ones.

**Comment by yaichenbaum** [comment]
@Noxdor Thanks for opening this issue, it's resolved in the `main` branch and will be included in the next update.
