### ISSUE TITLE
shortcut for opening the app

### ISSUE THREAD

**Issue by techgue** [files-community/Files#4886]
**Is your feature request related to a problem?**
A clear description of what the problem is.

**Describe the solution**
A clear description of what you want.

**Describe alternatives you've considered**
A clear description of any alternative solutions or features you've considered.

**Scope**

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Additional comment**
Add any other comment or screenshots about the feature request here. What device type/UI layout and app version?

**Comment by josh-65** [comment]
you can set files as default using the instructions here (https://files-community.github.io/docs/#/articles/replace-file-explorer) then use windows key + e. you can also add it to the start menu or task bar.

**Comment by winston-de** [comment]
Adding on to what josh-65 said, another method to configure the Win+E shortcut without replacing Explorer with Files is to use [this](https://files-community.github.io/docs/#/articles/configure-win-e) guide.
