### ISSUE TITLE
Weekly Builds?

### ISSUE THREAD

**Issue by pklion** [files-community/Files#4887]
**Is your feature request related to a problem?**
I don't have an environment to build Files from source.

**Describe the solution**
So I would love to have weekly builds.

**Describe alternatives you've considered**
N/A

**Scope**
Should? (at least I want)

**Additional comment**
N/A

**Comment by josh-65** [comment]
if you join the discord you can request for insider. that will get you more updated builds.

**Comment by pklion** [comment]
@josh-65 I'm already in the insider :)
But it's not weekly

**Comment by pklion** [comment]
I want to have weekly builds like Microsoft Edge if we can...

**Comment by yaichenbaum** [comment]
The insider channel is already updated about once a week. Sometimes we run into blocking issues so we can't release an update, but we usually let you know when that happens.
