### ISSUE TITLE
Open in terminal uses root drive path instead of folder path

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#4888]
**Explain the bug**
The open in terminal option seems to open it in C: rather than the current working directory.

**To reproduce**
1. Go to any folder except the root drive (C: in my case)
2. Right click and hit open in terminal
4. See the error

**Expected behavior**
Write a clear description of what you expected.
It should open in the current working directory instead of the root drive location.

**System Information**
 - OS Version: Windows 10 Pro 20H2 build 19042.964
 - App version: 1.5.16.0

**Additional comment**
Add any other comment about the problem here. Does this problem happen again after restarting the app?
This problem exist in all there terminal app options - CMD, PowerShell, Windows terminal

**Comment by josh-65** [comment]
It works fine for me in the new windows terminal. You will properly have to upload your logs.

**Comment by yaichenbaum** [comment]
This issue appears to be resolved in `main`.
