### ISSUE TITLE
Ellipse-based selector for touch-based devices.

### ISSUE THREAD

**Issue by hiranmayd** [files-community/Files#4889]
**Is your feature request related to a problem?**
No.
**Describe the solution**
There needs to be a way to select stuff on (primarily) touch-based devices quicker without going into a multiselect mode in the upcoming beta, this could also be a potential UI concept/mock-up for the multi-select mode. depends on the way y'all see it. Pls refer to image attached. Conceptualized for grid-view and details-view (img 2)
_the concept was for a different project, was altered to fit files!!!!_
**Scope**
| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to select file/folders/items quicker on mainly touch-based devices. | Should |
![img1](https://user-images.githubusercontent.com/60701764/118009246-88078980-b36b-11eb-9579-543ddf2d7fa6.png)
![img2](https://user-images.githubusercontent.com/60701764/118009673-e2a0e580-b36b-11eb-981b-5bea647796d1.png)

**Comment by winston-de** [comment]
Hi there, thanks for opening this issue. Your concepts look very nice, and are also fairly similar to what we already have for multiselect (and looks even more similar on devices with dev channel builds of Windows).

![image](https://user-images.githubusercontent.com/59544401/118013861-6d032e00-b307-11eb-9504-9f91d3175d5b.png)
![image](https://user-images.githubusercontent.com/59544401/118015085-c1f37400-b308-11eb-8d0f-98a14ae92899.png)

Could you please better describe what about the current multiselect implementation we could improve?

**Comment by hiranmayd** [comment]
This is great! I hadn't seen this. firstly, having a tick beside the item (img 1) might confuse the user so I think you should reconsider that. Except for that, it'll be great if these small selection boxes were persistent and not triggered by something like the multi-select mode **on touch devices**.
Multi-select mode for keyboard and mouse users is great but they can always ctrl + click to select stuff. for touch-devices on the other hand, it isn't that easy, and the boxes being persistent can save those users a bunch of taps and presses : )

**Comment by winston-de** [comment]
The reason why multiselect mode is not always enabled is because there isn't a small selection box, clicking/tapping any part of the item toggles selection instead of opening it. This does require a few extra taps to toggle, but it makes it easier to select with touch as there isn't a tiny hit area the user has to tap.

Although a bit old, here's a demonstration of it:

https://user-images.githubusercontent.com/59544401/105762228-fd5c6500-5f08-11eb-81f4-8c6856d14e4c.mp4

**Comment by hiranmayd** [comment]
ok that seems great, but how about a select button by itself instead of it being inside a menu?

**Comment by winston-de** [comment]
> ok that seems great, but how about a select button by itself instead of it being inside a menu?

That's a good idea, and I believe others have requested that as well. Would you like to open an issue for it?

**Comment by yaichenbaum** [comment]
Is there a reason we can't show check boxes like the concept? We would still want to keep the menu option because that enables larger touch targets, but I still think there is a benifit of showing the checkboxes all the time.

**Comment by winston-de** [comment]
@yair100 No, all that would need to be done is add a checkbox to all the templates and handling the tapped event so that it overrides the default tap behavior (which is selection). I'm not sure how much the checkboxes would interfere with the multiselect selection checkboxes though.

**Comment by yaichenbaum** [comment]
Another option is to ditch the current behavior altogether, and to use larger touch targets for touch input.

**Comment by hiranmayd** [comment]
> That's a good idea, and I believe others have requested that as well. Would you like to open an issue for it?
sure, ill do that later!

**Comment by hiranmayd** [comment]
> Another option is to ditch the current behavior altogether, and to use larger touch targets for touch input.

please elaborate
