### ISSUE TITLE
Feature: Support for changing the preview pane position

### ISSUE THREAD

**Issue by aeges** [files-community/Files#4890]
**Is your feature request related to a problem?**
Depending of the size of the file list the preview pane is either to the right or at the bottom. 
This is a bit uncomfortable when e.g. previewing documents (pdf or word): The preview is often to small and with two (file) panes it happens that one pane shows the preview to the right and the other at the bottom.
Also the details pane is not always needed and it should be possible to hide it.

**Describe the solution**
The "Toggle the preview pane" Buttons should be extended to a flyout menu providing the following options:
- Show Preview (On / Off)
- Show Preview Details (On / Off)
- Set Preview Position (Right / Bottom)

*Example:*
![image](https://user-images.githubusercontent.com/4764933/118050876-649b0980-b380-11eb-8551-935892672225.png)

*Remarks:*
- Should the preview pane options be valid only for the current tab or for all tabs?
- Instead of a simple fly out: A split button could be useful to quickly toggle the preview pane and setting the options when expanding the menu.
- Position and size of the pane could be applied on all tabs whereas toggling the pane could be per tab / file pane

**Scope**

| Capability | Priority |
| :---------- | :------- |
| Add flyout menu with the options mentioned above | Must |
| Synchronize the selected options (inclusive position and size?) in the AppSettings | Must |
| Load preview pane options (inclusive position and size) from the AppSettings at start up | Must |
| Remove size limitation of preview pane | Should |
| Translations | Should |

**Additional comment**

I already implemented a working version of the proposal, but not all requirements are fulfilled. So in case you are interested tell me how to commit the code (branch?).

**Comment by yaira2** [comment]
Thank you for your feedback.

**Comment by yaira2** [comment]
The upcoming v2.5 release has several improvements for the automatic positioning and layout of the preview pane. It'll also include an easy way to hide the details section.

**Comment by Josh65-2201** [comment]
This is no reason to contact ai-iskuzhin with either of those
