### ISSUE TITLE
Sync settings across devices

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#4903]
**Is your feature request related to a problem?**
Right now I have to set all settings for every device witch is kind of annoying.

**Describe the solution**
Don't know if its possible but sync all settings through the store so that there applied when reinstalling or opening on new device.

**Describe alternatives you've considered**
Export settings file like windows terminal has, if store syncing is not possible.

**Scope**
| Capability | Priority |
| :---------- | :------- |
| Sync the settings page contents | Must |
| Sync the home page widgets (active ones and content in bundles) and layout options | Should |
| Widths of the sidebar and preview bars | Could |

**Comment by yaichenbaum** [comment]
The current plan is to enable importing/exporting user settings #1260.
