### ISSUE TITLE
Search Feature not Working

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#4909]
**Explain the bug**
`Files` Search Feature doesn't seem to display the document(s), whether through `keywords` or `exact` file name, which the users may want to search for it.

**To reproduce**
1. Go to a directory which consists of files
2. Click on Search Button
3. Try to Type Some `Keywords` or Exact File Name
4. No file(s) is previewed

**Expected behavior**
Data(s) or file(s) should be previewed.

**Logfile**
Upload the log file here for us to understand your issue better. 
- You can access it from Settings->About->Open log location. 
or 
- Copy the debug.log and debug_fulltrust.log from the following directory, and upload the files here.
`%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 

**Screenshots**
![Search Feature not Working](https://user-images.githubusercontent.com/69080584/118347097-c28b4500-b56a-11eb-909b-2d1635090528.png)

**System Information**
 - OS Version: Windows 10 20H2 19042.985
 - App version: v1.5.0.0

**Additional comment**
Does this problem happen again after restarting the app? Yes, this problem occurs again after I have restarted the app.

**Comment by gave92** [comment]
Do you happen to have search indexing disabled?

**Comment by stanleyowen** [comment]
Hi @gave92, after trying to enable the "Show unindexed items when searching for files and folders" option, it works for me. Thanks!
