### ISSUE TITLE
Files Crashed After Switching Between Hide and Unhide Folders

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#4910]
**Explain the bug**
`Files` Crashed After Switching certain Folders from Hide Status to Unhide. `Files` will crashed after some operations of `hide` and `unhide` the same folders.

**To reproduce**
1. Open `Download` Tab
2. Click on `Properties` and Check Unhide/Hide
3. Click on `OK` nor `Cancel`
4. See `Files` closes unexpectedly

**Expected behavior**
Folder(s) should be hidden or unhidden after the operation without causes the application to crash.

**Logfile**
Upload the log file here for us to understand your issue better. 
- You can access it from Settings->About->Open log location. 
or 
- Copy the debug.log and debug_fulltrust.log from the following directory, and upload the files here.
`%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 
[debug.txt](https://github.com/files-community/Files/files/6481990/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6481994/debug_fulltrust.txt)

**Screenshots**

https://user-images.githubusercontent.com/69080584/118347706-670f8600-b56f-11eb-9ddc-1256b35a28b2.mp4

**System Information**
 - OS Version: Windows 10 20H2 19042.985
 - App version: v1.5.0.0

**Additional comment**
Does this problem happen again after restarting the app? Yes, this problem occurs again after I have restarted the app.

**Comment by gave92** [comment]
Merging with #2714. Opening and closing the properties window a few times will crash the app, regardless of toggling the hide/unhide option.
