### ISSUE TITLE
Map Network Drive Dialog isn't Being Previewed In the Front Position After Clicking It

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#4911]
**Explain the bug**
Map Network Drive Dialog isn't being previewed In the front position after clicking it, otherwise it shows up in the back of the application, which is not effective for users to minimize the `Files` app and switch it to the Map Network Drive DIalog

**To reproduce**
1. Open `FIles`
2. Go to `Home` on `Favorites` Tab
3. Besides the drive label, click on the three dots icon and click on Map Network Drive
4. See the Map Network Drive Dialog Previewed Behind the App

**Expected behavior**
Map Network Drive Dialog should be previewed in front of the app, not behind the app.

**Logfile**
Upload the log file here for us to understand your issue better. 
- You can access it from Settings->About->Open log location. 
or 
- Copy the debug.log and debug_fulltrust.log from the following directory, and upload the files here.
`%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 

**Screenshots**

https://user-images.githubusercontent.com/69080584/118348035-b5258900-b571-11eb-98c1-96984891e2a8.mp4

**System Information**
 - OS Version: Windows 10 20H2 19042.985
 - App version: v1.5.0.0

**Additional comment**
Does this problem happen again after restarting the app? Yes, this problem occurs again after I have restarted the app.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #4917.
