### ISSUE TITLE
Unable to Rename Drive(s) Name via Properties

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#4912]
**Explain the bug**
When users click on a file(s) properties, the app will show up many details or description about a certain files, besides that, users are also able to rename their file(s) or folder(s) via Properties by move the cursor to the folder(s) or file(s) name and change it. However, when users open properties of a Unable to Rename Drive(s) Name via Properties.

**To reproduce**
1. Open `Home`
2. Right click on a drive and click Properties
3. Move the mouse cursor to the disk's name
4. Change the name
5. Click Ok
6. Nothing Changed

**Expected behavior**
Drive(s) name should changed, however if it is impossible to do it, the only way is to disable the mouse cursor for rename function in `Properties` Dialog when users are trying to open Drive(s) Properties.

**Logfile**
Upload the log file here for us to understand your issue better. 
- You can access it from Settings->About->Open log location. 
or 
- Copy the debug.log and debug_fulltrust.log from the following directory, and upload the files here.
`%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 

**Screenshots**

https://user-images.githubusercontent.com/69080584/118348350-d4251a80-b573-11eb-8802-e45ccdfcc998.mp4

**System Information**
 - OS Version: Windows 10 20H2 19042.985
 - App version: v1.5.0.0

**Additional comment**
Does this problem happen again after restarting the app? Yes, this problem occurs again after I have restarted the app.

**Comment by gave92** [comment]
Before clicking on "OK" to close the window please try to click outside the textbox first

**Comment by yaichenbaum** [comment]
This issue should be resolved with #4917.
