### ISSUE TITLE
Empty Recycle Bin Not Working

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#4913]
**Explain the bug**
Empty Recycle Bin `Button` doesn't seem to work because the file(s) which wanted to be deleted permanently is/are still exist(s). The option I am doing now is by deleting manually which is using `Shift` + `Delete` button.

**To reproduce**
1. Go to Recycle Bin tab
2. Make sure the Recycle Bin isn't empty, otherwise the `button` is disabled
3. Click on the Empty Recycle Bin `button`
4. Nothing Changed

**Expected behavior**
After users click on Empty Recycle Bin `button`, temporary deleted file(s) should be deleted permanently.

**Logfile**
Upload the log file here for us to understand your issue better. 
- You can access it from Settings->About->Open log location. 
or 
- Copy the debug.log and debug_fulltrust.log from the following directory, and upload the files here.
`%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6482217/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6482219/debug.txt)

**Screenshots**

https://user-images.githubusercontent.com/69080584/118348815-f9675800-b576-11eb-8901-fada495bebb8.mp4

**System Information**
 - OS Version: Windows 10 20H2 19042.985
 - App version: v1.5.0.0

**Additional comment**
Does this problem happen again after restarting the app? Firstly I think the app has encounter some problems, so I planned to reset the app via `App Settings > Reset`, however this problem occurs again both after I have restarted the app and reset the app.

**Comment by cinqmilleans** [comment]
This issue has been corrected since the last release. So this will be in the next version.

**Comment by stanleyowen** [comment]
Okay thanks.
