### ISSUE TITLE
Navigation Display Becomes Messy While One Tab Open Navigation and Others Close Navigation

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#4914]
**Explain the bug**
`Navigation Display` becomes messy or being cut while One Tab uses `Open Navigation` option and the other tab uses `Close Navigation` option.

**To reproduce**
1. Open `Files`
2. Click on `Close Navigation` on current tab
3. Click on New Tab which automatically uses `Open Navigation` option
4. Switch back to first tab
5. Navigation Tab Display only show half of the supposed `width` or sometimes it becomes `blank` or there is a `gap`.

**Expected behavior**
Navigation must has the same display between one tab with each other.

**Logfile**
Upload the log file here for us to understand your issue better. 
- You can access it from Settings->About->Open log location. 
or 
- Copy the debug.log and debug_fulltrust.log from the following directory, and upload the files here.
`%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 

**Screenshots**
![image](https://user-images.githubusercontent.com/69080584/118349593-be1b5800-b57b-11eb-8309-07f7dfa6d1da.png)
![image](https://user-images.githubusercontent.com/69080584/118349606-ca071a00-b57b-11eb-81bd-4e34faab804e.png)
![image](https://user-images.githubusercontent.com/69080584/118349596-c5426600-b57b-11eb-9e1d-94f126a7fd62.png)

**System Information**
 - OS Version: Windows 10 20H2 19042.985
 - App version: v1.5.0.0

**Additional comment**
Does this problem happen again after restarting the app? Yes, this problem occurs again after I have restarted the app.

**Comment by gave92** [comment]
Thanks for the report. This is fixed in latest code.
