### ISSUE TITLE
No folder icon

### ISSUE THREAD

**Issue by asahidev** [files-community/Files#4916]
No folder icon is shown in the explorer

**To reproduce**
Instal from either alt. link or from MS Store; both have the same issue

**EDIT** I use internal GPU Intel HD Graphics®

[debug.txt](https://github.com/files-community/Files/files/6487598/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6487599/debug_fulltrust.txt)
![image](https://user-images.githubusercontent.com/51609372/118365325-e66b7c80-b5a4-11eb-8c39-5825baadd900.png)
![image](https://user-images.githubusercontent.com/51609372/118365402-54b03f00-b5a5-11eb-86bf-bec237cf8f57.png)
![image](https://user-images.githubusercontent.com/51609372/118365330-f08d7b00-b5a4-11eb-9ba6-1ff442e9184a.png)

**Comment by yaichenbaum** [comment]
@asahidev Is this still an issue if you turn off the setting to cache files and folders?

**Comment by asahidev** [comment]
> @asahidev Is this still an issue if you turn off the setting to cache files and folders?

Yes, this issue is still present if I turn off the setting

**Comment by yaichenbaum** [comment]
@gave92 Can you check if this is resolved in `main`?

**Comment by yaichenbaum** [comment]
@asahidev Can you please fill out the issue template with the log file and version info?
