### ISSUE TITLE
Disk Space Capacity Doesn't Being Previewed on the First Launch

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#4924]
**Explain the bug**
Disk Space Capacity for other disk(s) besides of `(C:)` doesn't being previewed on the first app launch.

**To reproduce**
1. Open Files
2. See the error

**Expected behavior**
Disk Space Capacity should be previewed on the first launch.

**Logfile**
Upload the log file here for us to understand your issue better. 
- You can access it from Settings->About->Open log location. 
or 
- Copy the debug.log and debug_fulltrust.log from the following directory, and upload the files here.
`%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 
Not Applicable

**Screenshots**
![image](https://user-images.githubusercontent.com/69080584/118383716-b36bcc00-b62a-11eb-8008-64fa2be5f475.png)
![image](https://user-images.githubusercontent.com/69080584/118383717-b797e980-b62a-11eb-9fd7-c03bcef9a6cc.png)

**System Information**
 - OS Version: Windows 10 20H2 19042.985
 - App version: v1.5.0.0

**Additional comment**
Does this problem happen again after restarting the app? Yes, this problem occurs again after I have restarted the app.

**Comment by gave92** [comment]
Merging with #3701
