### ISSUE TITLE
Add a MSI build

### ISSUE THREAD

**Issue by Milo123459** [files-community/Files#4926]
**Is your feature request related to a problem?**
A clear description of what the problem is.
No.
**Describe the solution**
A clear description of what you want.
Add a `msi` in the release so I can add it to a scoop bucket.
**Describe alternatives you've considered**
A clear description of any alternative solutions or features you've considered.
N/A
**Scope**

**Additional comment**
Add any other comment or screenshots about the feature request here. What device type/UI layout and app version?
N/A

**Comment by gave92** [comment]
No MSI for UWP apps but there's the AppInstaller package available:
https://files-community.github.io/package.github.io/Files.Package/Files.Package.appinstaller
Can be installed from PowerShell like this:
`Add-AppxPackage -AppInstallerFile Files.Package.appinstaller`

**Comment by Milo123459** [comment]
Thank you

**Comment by Whirlpool-Programmer** [comment]
> No MSI for UWP apps but there's the AppInstaller package available:
> https://files-community.github.io/package.github.io/Files.Package/Files.Package.appinstaller
> Can be installed from PowerShell like this:
> `Add-AppxPackage -AppInstallerFile Files.Package.appinstaller`

This does not work now...

**Comment by gave92** [comment]
\+ @yair100

**Comment by yaichenbaum** [comment]
@gave92 the correct package is in the release page :)
