### ISSUE TITLE
Cloud Drives option is not working!!!

### ISSUE THREAD

**Issue by TejasPatil80178** [files-community/Files#4931]

**Comment by duke7553** [comment]
@TejasPatil80178 Thanks for your feedback. We're having trouble understanding what you're requesting and need additional information to investigate this item. We typically close issues like this in 7 days, so please fill out the issue template to the best of your ability before then.

**Comment by Karthik-Dulam** [comment]
Even though I have two cloud drives, both one drive, one personal and the other institutional, there are no options under cloud drives.

![image](https://user-images.githubusercontent.com/59601648/120934239-27c1f880-c71b-11eb-9f2e-ac5a7688b52d.png)

Probably this is what the OP meant, I have the same problem.
