### ISSUE TITLE
Display of Collapsable Categories should be an option in the settings.

### ISSUE THREAD

**Issue by oseughu** [files-community/Files#4937]
**Is your feature request related to a problem?**
I can't seem to choose if I want the sidebar categorized or not. 

**Describe the solution**
I want to be able to choose if I want collapsable categories to be displayed or not. 

Specifically, I would like my files app to look like the image below

https://www.windowscentral.com/sites/wpcentral.com/files/styles/large_wm_brw/public/field/image/2021/01/files-modern-explorer-lede-4-3.jpg

**Describe alternatives you've considered**
A clear description of any alternative solutions or features you've considered.

**Scope**

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Additional comment**
Add any other comment or screenshots about the feature request here. What device type/UI layout and app version?

**Comment by yaichenbaum** [comment]
@oseughu Thank you for opening this issue, we don't have any plans to make this change.
