### ISSUE TITLE
Add option to disable recent items list

### ISSUE THREAD

**Issue by clorteau** [files-community/Files#4941]
**Is your feature request related to a problem?**
The recent items list may give away things we don't want shown, including in hiden folders

**Describe the solution**
Add an option to disable the recent items list

**Describe alternatives you've considered**
I can't think of an alternative

**Scope**

| Capability | Priority |
| :---------- | :------- |
| Toggle button in Settings > Files and Folders labelled "Disable recent items" | Must |
| When toggle button is on, don't show the recent items list anywhere | Must |
| When toggle button is on, don't even record recent items | Should |
| When toggle button is flipped to on, delete all recent items so they don't show again when flipping the button back | Could |

**Additional comment**
None

**Comment by gave92** [comment]
There's already an option in Files settings for points 1 and 2, it's under "Widgets"

**Comment by geetanshpancholi** [comment]
There is no Widgets option in settings.
![image](https://user-images.githubusercontent.com/78640436/127169031-a531ace4-4177-4336-9817-f95c6c9654f6.png)

**Comment by yaichenbaum** [comment]
The settings for widgets have been moved to the home page.
