### ISSUE TITLE
Cannot move file to recycle bin (It tries to copy)

### ISSUE THREAD

**Issue by mangoepic** [files-community/Files#4947]
**Explain the bug**
In Windows Explorer you can move a file to the recycle bin by dragging it into the window.
In Files, Moving it from the sidebar is blocked. And trying  to move it from desktop gives an error message.

**To reproduce**
1. Go to your Desktop
2. Go into the Recycle Bin Folder in Files
3. Drag a File from the Desktop to the Recycle bin Folder
4. See the error

**Expected behavior**
I expected the file to get moved into the recycling bin

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6500812/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6500813/debug_fulltrust.txt)

**Screenshots**
![image](https://user-images.githubusercontent.com/71931749/118641320-4eef6f00-b7da-11eb-88e8-5ad1d23660f7.png)
Move from within files to the sidebar.

![image](https://user-images.githubusercontent.com/71931749/118641211-28313880-b7da-11eb-8693-508ea9fef96e.png)
Move from Desktop into Recycle bin Folder

**System Information**
 - OS Version: Windows 10 20H2 19042.985
 - App version: 1.5.0.0

**Additional comment**
It also happens after restarting.

**Comment by mangoepic** [comment]
Also, when closing Files while the dialogue is still open it can make this Copy dialogue stick to the front of your screen which i can still see while typing this even though i closed Files and checked if it was still running through the taskmanager
![error](https://user-images.githubusercontent.com/71931749/118643278-9ecf3580-b7dc-11eb-92c7-b61c2dcf47e3.gif)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5273.
