### ISSUE TITLE
Useless without treeview in leftmost column

### ISSUE THREAD

**Issue by ALHE3668** [files-community/Files#4948]
**Is your feature request related to a problem?**
A clear description of what the problem is.

**Describe the solution**
A clear description of what you want.

**Describe alternatives you've considered**
A clear description of any alternative solutions or features you've considered.

**Scope**

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Additional comment**
Add any other comment or screenshots about the feature request here. What device type/UI layout and app version?

**Comment by duke7553** [comment]
@ALHE3668 
Thanks for your feedback. We're having trouble understanding what you're requesting and need additional information to investigate this item. We typically close issues like this in 7 days, so please fill out the issue template to the best of your ability before then.

**Comment by ALHE3668** [comment]
I’m simply stating that without tree-view in the leftmost column (“Files”) the application is useless.
This is what I want:

***@***.***D74C08.C7160F40]

With this it is possible to perform drag and drop from the right side (showing the active folder) to the left side (showing files in a tree-view).


Venlig hilsen
Allan Helboe
Underviser,
UCL Erhvervsakademi og Professionshøjskole


Fra: Luke Blevins ***@***.***>
Sendt: 18. maj 2021 17:01
Til: files-community/Files ***@***.***>
Cc: Allan Helboe ***@***.***>; Mention ***@***.***>
Emne: Re: [files-community/Files] Useless without treeview in leftmost column (#4948)


@ALHE3668<https://github.com/ALHE3668>
Thanks for your feedback. We're having trouble understanding what you're requesting and need additional information to investigate this item. We typically close issues like this in 7 days, so please fill out the issue template to the best of your ability before then.

**Comment by hnOsmium0001** [comment]
I think the author's intention is to say a feature request for File Explorer-like tree layout in the left column, aka the one that shows up when you click the arrows.
Related but not duplicate (that one asks for tree layout in the main panel): #1928

**Comment by yaichenbaum** [comment]
@ALHE3668 We have plans for a tree view layout, we are tracking this feature request in #1928.

**Comment by yair100** [comment]
@ALHE3668 Tree View is currently available in preview https://files.community/download. It will be included in the next stable release.
