### ISSUE TITLE
send directories to dropbox

### ISSUE THREAD

**Issue by tonyms51** [files-community/Files#4952]
why cant i send directories to dropbox?

**Comment by winston-de** [comment]
@tonyms51 Thanks for reporting this, I'm having trouble understanding what your issue is and how to reproduce it. Could you please provide more info, like how you were trying to send directories to dropbox? Filling out the issue template would also be very helpful.

**Comment by tonyms51** [comment]
On other directory programs, I select a directory, hit my right button 
and I see a list of options, one of which is 'send to' which I /then 
click on and get a list of places to send to, including dropbox/-shortcut.
I use this option to back up my directories to dropbox. How can I do 
this using Files?
Regards
Tony

**Comment by gave92** [comment]
Merging with #285 (request for send to context menu)
