### ISSUE TITLE
Crash when quickly scrolling through the files display options (in folder > scroll + ctrl)

### ISSUE THREAD

**Issue by dawid2727** [files-community/Files#4953]
**Explain the bug**
Crash when quickly scrolling through the files display options (in folder > scroll + ctrl).

**To reproduce**
Open any folder with a couple of files. For me, it was a bunch of .blend files, and 2 pictures (pretty large, 4k-ish?)
I used scroll wheel + ctrl to go back from miniatures (tiles) to a list view. The program clearly struggled, (like it went in 10fps maybe), and then crashed while I saw the miniatures get smaller as they should.

**Expected behavior**
Well, to not crashing...

**Logfile**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6507662/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6507663/debug.txt)

**System Information**
Procesor	Intel(R) Core(TM) i9-10900 CPU @ 2.80GHz   2.81 GHz
Zainstalowana pamięć RAM	32,0 GB
Wersja	Windows 10 Pro
Wersja	20H2
Zainstalowano dnia	‎15.‎01.‎2021
Kompilacja systemu operacyjnego	19042.985
Możliwości	Windows Feature Experience Pack 120.2212.2020.0

 - App version: [e.g. v1.0] (In the app, go to Settings -> About, the version is shown at the top)
1.5.0.0

**Additional comment**
Hard to tell, what is happening from just a regular user side, I think it just becomes overloaded and crashes?

**Comment by gave92** [comment]
Thanks for the report. Was this in a OneDrive folder?

**Comment by yaichenbaum** [comment]
This issue appears to be resolved in `main`.
