### ISSUE TITLE
Can't copy, cut or paste any file.

### ISSUE THREAD

**Issue by Apheiro** [files-community/Files#4961]
**Explain the bug**
Let me explain, I cut (ctrl+x) the file and it becomes transparent so theoretically it is cutting, but when pasting (ctrl+v) it does nothing. The only thing it does is to select with a white lines box the first file of the list in the folder for example: I have 4 folders inside a directory (hello1 hello2 hello3 hello4) I select "hello4" and in the same directory I do the test of copy and paste or cut and paste, when I am going to use ctrl+v it selects with a white box the hello1 and it does not paste the copied or cut file and if I do it with the mouse it simply does nothing and does not select any folder with any white box, nothing happens.

**To reproduce**
1. I am located in a directory.
2. select a folder.
3. proceed to "ctrl+c" , "ctrl+v" , right click cut or copy , "ctrl+v" or right click cut or copy
4. I proceed to paste in all possible ways.
5. nothing happens

**Expected behavior**
I hope that when cutting or copying I can paste in the directory where I am located or in any other directory where I am going to be located.
nothing happens

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6511890/debug.txt)

**Screenshots**
![cut](https://user-images.githubusercontent.com/69778636/118895881-66635080-b8dd-11eb-931a-067e93cda5b7.png)
![paste](https://user-images.githubusercontent.com/69778636/118895885-682d1400-b8dd-11eb-8c9d-58aeb2efdc00.png)

**System Information**
 - OS Version: 
         Edition Windows 10 Pro
         Version 20H2
         Installed on ‎2/‎23/‎2021
         OS build 19042.985
         Experience Windows Feature Experience Pack 120.2212.2020.0

 - App versión: last version available in 19/05/21 on github (1.5.0.0)

**Additional comment**
I restarted my computer, reinstalled the application, tried the one from the Microsoft store first and then I downloaded it from the github to see if the problem was solved, I tried to run it with maximum permissions, I set it as default application. I did all these attempts to see if it worked, I also looked to see if there was any other key combination that was overlapping the copy and paste of the application so I also tried right click copy and paste but it didn't work. I really love the application I would like to leave it as default and I hope you can solve the problem or give me a solution.

**Comment by zhucp** [comment]
奇怪的是, 第一次打开 不能复制和剪切, 重启软件, 可以剪切但任然不能复制...

**Comment by yaichenbaum** [comment]
@Apheiro is this still an issue in Files v2.0?
