### ISSUE TITLE
Missing some icons

### ISSUE THREAD

**Issue by minidarknova** [files-community/Files#4962]
Not sure this is a bug persay, but icons from other windows dlls are not showing.
Same partition and folders in Windows default Explorer vs Files.
Latest version since I just reinstalled windows 21H1 (fresh)
https://imgur.com/a/5pkQXY9

**Comment by josh-65** [comment]
there still in the process of implemting them

**Comment by yaichenbaum** [comment]
> there still in the process of implemting them

@josh-65 This is unrelated to the sidebar icons.

@minidarknova This issue should be resolved when we release v2.
