### ISSUE TITLE
Feature: Add support for having multiple sharepoint drives in sidebar

### ISSUE THREAD

**Issue by michelebiancucci** [files-community/Files#4966]
### What feature or improvement do you think would benefit Files?
The solution is to show multiple OneDrive or SharePoint folders under the Cloud Drives section. At the moment, the Cloud Drives section shows only one item for OneDrive folders and one item for SharePoint folders

### Requirements
- multiple sharepoint drives should be displayed under cloud drives

### Files Version

2.3.11.0

### Windows Version

10.19043.1899

**Comment by winston-de** [comment]
Thanks for this feedback. Just to clarify, are you referring to showing cloud drives for different onedrive/sharepoint accounts, or for showing multiple folders that are in a cloud drive?

**Comment by michelebiancucci** [comment]
Thank you for the support. I'm actually referring to showing multiple SharePoint sections as in the attached screenshot from File Explorer. Please also find attached another screenshot representing Files. As you can see, File Explorer shows two SharePoint sections, while Files only shows the first one.
![file explorer](https://user-images.githubusercontent.com/5813257/120176275-5fa2da80-c207-11eb-8a30-85d0f4eabb6e.png)
![files](https://user-images.githubusercontent.com/5813257/120176280-603b7100-c207-11eb-9cd4-8b823aeb3b16.png)

**Comment by tduong-cloud** [comment]
Actually, I have found a workaround, you can add the other Sharepoint folder to Favorites

**Comment by michelebiancucci** [comment]
I'm actually already using this workaround, but again... it's a workaround and not a feature

**Comment by tduong-cloud** [comment]
Indeed, I wanted to share the info because I have just thought about it today :p

**Comment by MalteTasler** [comment]
please add the "feature request" label. c:

**Comment by Josh-65** [comment]
Is this still an issue?

**Comment by michelebiancucci** [comment]
it's a feature request, not an issue. I think it would be useful to show multiple SharePoint sections. As shown in the previous screenshots the Windows File Explorer shows two (or more) SharePoint sections, while Files shows only one.

**Comment by Josh65-2201** [comment]
@yair100

**Comment by yaichenbaum** [comment]
I think it's already supported, @gave92 can you confirm?

**Comment by michelebiancucci** [comment]
As shown in the attachments, I have two SharePoint synced folders, one for each account. Files only shows one of them: the one that was last configured to be synced locally. On the other hands, Windows File Explorers shows both.

**Comment by Bao1296** [comment]
![image](https://user-images.githubusercontent.com/42288514/216668723-0f0fd9f2-ecbd-4e7c-b2b4-cab5fb522fe0.png)

I think my feedback is an issue because when I click to cicamt folder, it shows folder in vilai viet sharepoint
