### ISSUE TITLE
App runs extremely slow, almost unusable, in any view mode other than list/details

### ISSUE THREAD

**Issue by Lu9-ST** [files-community/Files#4971]
**Explain the bug**
In folders with large quantities of items, using any view mode other than list/details while navigating and interacting with the items can be quite slow, and after doing a rectangular selection, the application hangs for a few seconds (although hovering over the files still do the outline reveal effect, but clicking on anything doesn't work)  and eventually either successfully selects the files in the range of the rectangle (that was not shown) or continues to not respond and eventually Files closes itself.

**To reproduce**
Make a rectangular selection in any view mode that isn't list/details in a folder with a large amount of items

**Expected behavior**
The rectangle should appear as I drag the cursor across the screen, which currently works as expected in details view, and in other views only on smaller folders.

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6545120/debug.txt)

**System Information**
OS Version: Windows 10 20H2 19042.985
App version: 1.5.0.0 from Microsoft Store

**Additional comment**
I have just noticed the application seems to be closing itself as well even when I am not doing anything, it was just now on the about page and it closed. Not sure if it really is a crash, the log file did not update.

**Comment by gave92** [comment]
@LuNiney thanks for the report. How many items in the Downloads folder?

**Comment by LuNiney** [comment]
2.594 (counting folders)

**Comment by yaichenbaum** [comment]
@LuNiney Can you fill out the issue template?

**Comment by LuNiney** [comment]
additionally, i've noticed recently that files would also hang after right clicking on empty space in a folder, and i tested that even on a smaller folder, same issue.

**Comment by yaichenbaum** [comment]
@LuNiney Is this also in v1.5?

**Comment by Lu9-ST** [comment]
@yair100  yes.

**Comment by tony-0tis** [comment]
I do not want to create new issue, because the essence is the same. Compared to the standard explorer, the application is very slow. Folders take a long time to open. The selection of files is not intuitive (the first click does not open the file, it looks like you are going to drag and drop it). I am surprised that a C# application could be so slow. It seems even electron.js can be much faster.

**Comment by yaichenbaum** [comment]
@Lu9-ST the issue with the selection rectangle has been resolved in `main` and will be included in the next update.
