### ISSUE TITLE
Crashes after Drag New Tab

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#4972]
**Explain the bug**
Files `crashes` or closes unexpectedly after dragging a new tab to other position.

**To reproduce**
1. Open `Files`
2. Click on New Tab
3. Drag the New tab to other tab
4. App crashes or closes unexpectedly

**Expected behavior**
`Files` shouldn't crashes and other operations should working appropriately.

**Logfile**
Upload the log file here for us to understand your issue better. 
- You can access it from Settings->About->Open log location. 
or 
- Copy the debug.log and debug_fulltrust.log from the following directory, and upload the files here.
`%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 
[debug.txt](https://github.com/files-community/Files/files/6520040/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6520039/debug_fulltrust.txt)

**Screenshots**

https://user-images.githubusercontent.com/69080584/119082352-1349e480-ba28-11eb-8877-2f72c9bccb79.mp4

**System Information**
 - OS Version: Windows 10 20H2 19042.985
 - App version: v1.5.0.0

**Additional comment**
Does this problem happen again after restarting the app? Yes this bug occurs after the app restarted.

**Comment by winston-de** [comment]
Thanks for reporting this, this issue should be resolved in ``main``.
