### ISSUE TITLE
Typo in GER translation of "Map network drive"

### ISSUE THREAD

**Issue by DinoTymo** [files-community/Files#4975]
**Explain the bug**
There is a typo in the German translation of the app. "Map network drive" should be "Net***z***werklaufwerk hinzufügen", not "Netwerklaufwerk hinzufügen"

**To reproduce**
1. Set the app's language to German (Settings > Preferences > App language).
2. After starting the app in German, go to "Home".
3. Click on the three dots next to "Laufwerke" ("Drives").
4. You'll see "Netwerklaufwerk hinzufügen".

**Expected behavior**
It should be "Netzwerklaufwerk hinzufügen".

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6522196/debug.txt)

**Screenshots**
![image](https://user-images.githubusercontent.com/64032626/119130837-0681bc80-ba39-11eb-86e2-948e9d82ffeb.png)

**System Information**
 - OS Version: Edition	Windows 10 Home 20H2 19042.985
 - App version: 1.5.0.0

**Additional comment**
-

**Comment by yaichenbaum** [comment]
@DinoTymo Would you like to try to fix this issue?

**Comment by R3voA3** [comment]
@yair100 You can mention me or ping me on Discords about issues with the German translation.

Fixed in #5002

**Comment by yaichenbaum** [comment]
@R3voA3 Thanks!
