### ISSUE TITLE
Unable to open

### ISSUE THREAD

**Issue by SpeedyIndeedy** [files-community/Files#4977]
Hii there,

I am not able to install File app from Microsoft Store. It gives me error.
So I tried to install from here from Files.package, now I am able to install but app wont start.
It only shows starting screen then automatically closes.

**System Information**
 - Windows 10 20H2 19042.928
 - App version: 1.5
![1](https://user-images.githubusercontent.com/74235469/119166480-4d44d600-ba7c-11eb-9a8f-145a634c477d.png)
![2](https://user-images.githubusercontent.com/74235469/119166494-503fc680-ba7c-11eb-9133-51be20c97ac8.png)

**Comment by yaichenbaum** [comment]
@RishiVora Can you upload the log files?

**Comment by SpeedyIndeedy** [comment]
@yair100
The app won't even start, how can I access logs?
"%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState" is also empty.

**Comment by gave92** [comment]
Perhaps we can get some info about this from Windows "Event Viewer"?
Like this:
![image](https://user-images.githubusercontent.com/9673091/119174521-f97cc180-ba68-11eb-8e62-f95b9d73a898.png)

**Comment by RishiVora** [comment]
@gave92 
Here you go.

![1](https://user-images.githubusercontent.com/74235469/119437706-5237ad00-bd3c-11eb-88bc-2b35bafc10d2.png)
![2](https://user-images.githubusercontent.com/74235469/119437707-52d04380-bd3c-11eb-8c5e-cc14054e418b.png)
![3](https://user-images.githubusercontent.com/74235469/119437709-5368da00-bd3c-11eb-9eac-710fb52edcdd.png)
![4](https://user-images.githubusercontent.com/74235469/119437715-54017080-bd3c-11eb-9c9b-4acd84a4cd82.png)
![5](https://user-images.githubusercontent.com/74235469/119437716-54017080-bd3c-11eb-8934-d3d4c558de6f.png)
![6](https://user-images.githubusercontent.com/74235469/119437717-549a0700-bd3c-11eb-9416-984f9f78958a.png)
![7](https://user-images.githubusercontent.com/74235469/119437700-506de980-bd3c-11eb-8a2f-9a5d3bde9ad6.png)

**Comment by gave92** [comment]
![119437707-52d04380-bd3c-11eb-8c5e-cc14054e418b (2).png](https://user-images.githubusercontent.com/9673091/119445301-dda94200-bd2c-11eb-9859-a69f14377762.png)

Is there anything more in those 3 highlighter error events?

**Comment by Noisyfox** [comment]
I'm having the same problem:
![image](https://user-images.githubusercontent.com/1537155/120058234-d49dd500-c08c-11eb-9d16-87affe6f48af.png)

**Comment by Noisyfox** [comment]
This is the log file for this crash
[debug.txt](https://github.com/files-community/Files/files/6595252/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6595254/debug_fulltrust.txt)

**Comment by Noisyfox** [comment]
![image](https://user-images.githubusercontent.com/1537155/120737668-d6a2e080-c531-11eb-9af8-33e323b4be5a.png)

Seems that you are not allowed to have slash in the key name...

**Comment by SpeedyIndeedy** [comment]
@Noisyfox 
Nope, its the same as first one.

**Comment by yaichenbaum** [comment]
@SpeedyIndeedy is this still an issue in v2.0.34?

**Comment by SpeedyIndeedy** [comment]
> @SpeedyIndeedy is this still an issue in v2.0.34?

the issue was my pc, old hardware ig, so when i fresh installed, i was able use files app.

**Comment by gave92** [comment]
Thanks for the update
