### ISSUE TITLE
Bad animation when open & close settings

### ISSUE THREAD

**Issue by ryadhiprasetya** [files-community/Files#4979]
Description: white glitch on top. see title and video for more visual.

![bad naimation](https://user-images.githubusercontent.com/47018482/119208132-f9151280-baca-11eb-8bb7-34509a1f1933.gif)

**Comment by yoshiask** [comment]
Note that the opposite happens with the light theme, a black bar appears at the top.

**Comment by duke7553** [comment]
@yoshiask @ryadhiprasetya Does this occur when your app theme preference matches the system theme set in Windows Settings?

**Comment by ryadhiprasetya** [comment]
in my situation, have same white glitch on windows default, dark, and white theme.

**Comment by yoshiask** [comment]
Good point, my system theme is Dark. It's still a bit jarring though, since pretty much all of the backgrounds in Files are gray (not black).

**Comment by yaichenbaum** [comment]
@ryadhiprasetya This is a system issue, can you open an issue on the WinUI repo?

**Comment by ryadhiprasetya** [comment]
> @ryadhiprasetya This is a system issue, can you open an issue on the WinUI repo?

done [#5071](https://github.com/microsoft/microsoft-ui-xaml/issues/5077)

**Comment by ryadhiprasetya** [comment]
Can we just turn off the animation. even the color is fix, animation itself is worst, not smooth

**Comment by yaichenbaum** [comment]
> Can we just turn off the animation. even the color is fix, animation itself is worst, not smooth

Yes, there is a system setting to turn off animations.

**Comment by ad1Dima** [comment]
@yaichenbaum  I didn't see if you set RequestedTheme on your root frame. Mey be this is the problem?

**Comment by ad1Dima** [comment]
![5vGiNJQF1z](https://user-images.githubusercontent.com/3244664/119561393-4ea13600-bdcf-11eb-9708-d54feb93a23b.gif)
found this strange behaviour. may be related

**Comment by yaichenbaum** [comment]
This issue is no longer relevant with #5077.
