### ISSUE TITLE
Ability to close sidebar by dragging

### ISSUE THREAD

**Issue by ryadhiprasetya** [files-community/Files#4981]
**Is your feature request related to a problem?**
right now we can close dual panel with drag behaviour. why we not do the same with sidebar, like finder macos do.

**Describe the solution**
![ezgif-6-6a57cf1063e2](https://user-images.githubusercontent.com/47018482/119213204-a85fe280-bae7-11eb-9a58-dc5412cc09b5.gif)

**Describe alternatives you've considered**
-

**Scope**

| Capability | Priority |
| :---------- | :------- |
| This proposal will collapse the sidebar when resizing it to have no width | Must |

**Additional comment**
-

**Comment by yaichenbaum** [comment]
@winston-de what are your thoughts on using the minimal sidebar feature for this scenario?

**Comment by winston-de** [comment]
@yair100 I think just toggling expanded/collapsed makes more sense. Something like how VSCode does it:

https://user-images.githubusercontent.com/59544401/119247515-02d85d80-bb3f-11eb-91a9-c07413344f98.mp4

**Comment by yair100** [comment]
> @yair100 I think just toggling expanded/collapsed makes more sense. Something like how VSCode does it:
> 
>  2021-05-22-204723.mp4

That looks like a good implementation.

**Comment by yaichenbaum** [comment]
This feature request was implemented in #5006.
