### ISSUE TITLE
Greek language localization

### ISSUE THREAD

**Issue by geonetor** [files-community/Files#4982]
**Is your feature request related to a problem?**
No

**Describe the solution**
Please inform me how i can localize the program in Greek for you.

**Describe alternatives you've considered**
I am new in Github, so i could use some guidance how to submit the files that i will translate.
-->
| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to use the program in Greek | Could |

**Additional comment**
Add any other comment or screenshots about the feature request here. What device type/UI layout and app version?

**Comment by geonetor** [comment]
Please inform me how i can help to localize your program in Greek.
Thanks!

**Comment by gave92** [comment]
Thanks for your interest in contributing to Files.
You can find documentation about how to translate Files [here](https://files-community.github.io/docs/#/articles/translating-files)
Feel free to ask here or on the [Discord server](https://discord.gg/files) if you need any help.
