### ISSUE TITLE
Copy paste file to folder that requires administrator privileges

### ISSUE THREAD

**Issue by vivaanmathur** [files-community/Files#4983]
**Explain the bug**
Copy pasting a file to a folder that requires administrator privileges does not work if not opened the app with administrator privileges.

**To reproduce**
 1. Copy any file from Desktop
 2. Paste it to C drive

**Expected behavior**
I expected it to be like Windows File Explorer: Show me an admin grant where I can put my admin password.

**Logfile**
Upload the log file here for us to understand your issue better. 
- You can access it from Settings->About->Open log location. 
or 
- Copy the debug.log and debug_fulltrust.log from the following directory, and upload the files here.
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6526394/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6526395/debug.txt)

**Screenshots**
Add screenshots to help explain your problem if needed.
Nothing happens, so no screenshot.
**System Information**
 - OS Version: [e.g. Windows 10 20H2 19042.804] (Press WIN + PAUSE/BREAK, use the copy button at the bottom)
 Windows 10 20H2 19042.985
 - App version: [e.g. v1.0] (In the app, go to Settings -> About, the version is shown at the top)
1.5.0.0

**Additional comment**
Add any other comment about the problem here. Does this problem happen again after restarting the app?
YES.

**Comment by gave92** [comment]
Thanks for opening this issue. Copy/paste as admin is not yet implemented, only delete is supposed to work. Tracking the progress in -> #2513
