### ISSUE TITLE
Request: Long File Names to use multiple lines

### ISSUE THREAD

**Issue by Ouronos** [files-community/Files#4987]
**Is your feature request related to a problem?**
This feature is not related to a problem; this is a QoL request.
Currently file names are limited to one line. This means that long file names are truncated. This can complicate finding the correct file in a directory (or the current directory) if the file names have the same beginning characters. 

Example: "[Item Description] Snapshot XX.jpg" will truncate to, roughly "[Item Description] Snap..."; if there are multiple files (XX = sequential or nonsequential numbers), the end user must hover each file until the correct one s found.

**Describe the solution**
Rather than long file names being truncated, long file names can occupy two (or three) lines in the file name area.
(This may require making the file type icon smaller).

**Scope**

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to accomplish viewing long file names without having to hover. | Should |

**Comment by winston-de** [comment]
Thanks for this feedback, merging with #1033.
