### ISSUE TITLE
性能需要提升

### ISSUE THREAD

**Issue by swos0000** [files-community/Files#4988]
这个files非常漂亮，逼死官方，用了段时间感觉有几个地方再改进下就无敌了
1把缩略图缓存的问题搞定，打开几百个缩略图的文件夹时每次都要重新读取很慢
2单击打开文件的速度还需要优化，暂时还不能替代资源管理器
3设法常驻后台，保证启动速度
4绑定win+E

**Comment by gave92** [comment]
1. Add thumbnail cache, it is very slow to re-read every time when you open a folder of hundreds of thumbnails
2. The speed of single-click to open the file needs to be optimized
3. Stay in the background to improve startup speed
4. Open with Win+E 
------------------------------------------------------
For [4] see [here](https://files-community.github.io/docs/#/articles/configure-win-e) to see how open Files on Win+E

**Comment by yaichenbaum** [comment]
@swos0000 Can you open a separate issue for each thing you posted?
