### ISSUE TITLE
Preview pane syntax highlighting

### ISSUE THREAD

**Issue by Tropix126** [files-community/Files#4989]
**Is your feature request related to a problem?**
At the moment, all text-based files are rendered in plaintext without any syntax highlighting, which makes previewing code files sometimes tedious.
![image](https://user-images.githubusercontent.com/42101043/119238217-d30d6380-bb06-11eb-9ce9-d14957a18854.png)

**Describe the solution**
Add syntax highlighting to common code-related files in the preview pane.

**Describe alternatives you've considered**
n/a

**Scope**

| Capability | Priority |
| :---------- | :------- |
| Add basic syntax highlighting to code-related files. | Must |

**Additional comment**
Add any other comment or screenshots about the feature request here. What device type/UI layout and app version?

**Comment by yaichenbaum** [comment]
@Tropix126 This feature was implemented with #4990.
