### ISSUE TITLE
Left margin on the horizontal tab control is inconsistent with the top and bottom margins

### ISSUE THREAD

**Issue by alixsep** [files-community/Files#4991]
Hi, The tap padding differs for the top/bottom and sides, It would be cool to get fixed for much more consistent design.

I want the padding to be same size across all the sides, top , right, bottom and left.

This is how it looks at moment:
![image](https://user-images.githubusercontent.com/59757582/119245919-4314fb80-bb92-11eb-8686-5573b6e22de0.png)

 - OS Version: Windows 10 1809
 - App version: v1.5

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
