### ISSUE TITLE
Files not getting detected on browsers, discord and most other apps even after making the regedit (Win+E is working)

### ISSUE THREAD

**Issue by touzel** [files-community/Files#4994]
**Explain the bug**
I'm a new user and I have run the regedit to make Files the default file explorer, and Win+E opens Files instead of windows file explorer - no issue there. However, apps and websites that require you to attach files from the PC still open windows file explorer (even now as I attach the log files and screenshots to this issue) and don't seem to respect the regedit. I have attached both a screenshot and a video showing the problem. I do not know if a workaround for this already exists or if it is a feature in the making, but I would really appreciate some help as the main reason I decided to switch to files is how slugging windows file explorer is while attaching/ uploading files on the web and elsewhere. Thanks in advance!

**To reproduce**
1. Go to any website/ app that requires you to upload/ attach a file
2. Click on the option to attach a file from your system
3. See the error

**Expected behavior**
Attach files on a browser/ app -> Opens Files 

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6527651/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6527652/debug_fulltrust.txt)

**Screenshots**
https://user-images.githubusercontent.com/67477423/119251156-969f3d80-bbc2-11eb-8fb0-b11e029f5e7e.mp4

![screenshot-files](https://user-images.githubusercontent.com/67477423/119251153-93a44d00-bbc2-11eb-8a37-2ff1a9c3920f.jpg)

**System Information**
 - OS Version: 
Edition	        Windows 10 Home Single Language
Version	        20H2
Installed on	‎03-‎05-‎2021
OS build	        19042.928
Experience	Windows Feature Experience Pack 120.2212.551.0
 - App version: v1.5.0.0

**Additional comment**
Yes, the problem persists even after restarting both the app and pc.

**Comment by gave92** [comment]
Sadly it's not possible to override the "Open" and "Save To" dialogs

**Comment by touzel** [comment]
> Sadly it's not possible to override the "Open" and "Save To" dialogs.

Unfortunate. Thanks for letting me know!
