### ISSUE TITLE
Modification in network driver / share folder cannot get displayed automatically.

### ISSUE THREAD

**Issue by YuanfengZhang** [files-community/Files#4995]
I have a share folder at 192.168.3.x, and already mapped it in the file explorer.
![image](https://user-images.githubusercontent.com/71358306/119252149-2651e580-bbdd-11eb-8375-dbb7adbeb8a6.png)
Q: After my operation in this driver, like make dir/file, remove or rename a file, it won't refresh to show the newest status.
![image](https://user-images.githubusercontent.com/71358306/119252159-3d90d300-bbdd-11eb-9bd4-b42350e23750.png)
![image](https://user-images.githubusercontent.com/71358306/119252175-500b0c80-bbdd-11eb-83be-a96595efc9b1.png)
![image](https://user-images.githubusercontent.com/71358306/119252218-8f395d80-bbdd-11eb-8031-7ffae680b3ed.png)

As u can see, it remains empty. If I press F5 button, it will refresh and show what i expect:
![image](https://user-images.githubusercontent.com/71358306/119252179-5a2d0b00-bbdd-11eb-812d-c20187350f12.png)

**Comment by gave92** [comment]
Merging with #2042
