### ISSUE TITLE
Pin Folders to the Favorites with simple Drag'n'Drop

### ISSUE THREAD

**Issue by mangoepic** [files-community/Files#4997]
**Is your feature request related to a problem?**
In Windows Explorer you can pin folders by drag and dropping them to the favorites. This is a quicker and more user friendly way to add something to the favorite bar.

Steps with dragging:
 - Look at folder and at favorites to see if it is already there
 - Drag the folder to favorites

Steps without dragging:
 - Look at folder and at favorites to see if it is already there
 - Right Click on the Folder, wait 200ms for the rightclick to appear, focus your eyes on that
 - Find the Button (which is called pin to side bar currently)
 - Click

**Describe the solution**
Add folders to the Favorites bar by dragging them onto the Favorites button in the sidebar

**Describe alternatives you've considered**
A clear description of any alternative solutions or features you've considered.

**Scope**

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to accomplish pinning to the sidebar with simple drag and drop | Must |

**Additional comment**
![image](https://user-images.githubusercontent.com/71931749/119263995-9d897880-bbe1-11eb-9b1b-c5f176141ac0.png)
Add any other comment or screenshots about the feature request here. What device type/UI layout and app version?

**Comment by gave92** [comment]
Thanks for this suggestion. Merging with #2626 & #1069.
