### ISSUE TITLE
Consider use of Semibold or Bold text, only for headings or with accompanying text

### ISSUE THREAD

**Issue by mdtauk** [files-community/Files#5000]
**Is your feature request related to a problem?**
The Home Tab page uses a lot of Semibold text, which feels as if it is screaming for attention.

**Describe the solution**
Please could you consider using it only for Drive Labels, where there is small secondary text alongside, but not for single lines of labels.

**Describe alternatives you've considered**
![image](https://user-images.githubusercontent.com/7389110/119274651-f3bde200-bc08-11eb-9030-f5892f510cb7.png)
_Visual example of how they could be changed_

**Additional comment**
The issue is present in Files **1.5.17.0** as well as in the current dev versions 2.0

**Comment by yaichenbaum** [comment]
@mdtauk This issue should be resolved with #5001.
