### ISSUE TITLE
Bug: Turning off grouping can show an empty view

### ISSUE THREAD

**Issue by nvi9** [files-community/Files#5011]
**Explain the bug**

When grouping (implemented in #4826) is turned on and the user clicks on a header to show the group names only and then turns off grouping the view becomes empty.

**To reproduce**

1. Go to any folder
2. Click on Arrangement options
3. Select any grouping type (eg. Name)
4. Click on a group header
5. Click on Arrangement options again
6. Select None in the Group by options
5. See the error (empty view)

**Expected behavior**

The original folder view should be restored when Group by > None is being selected.

**Screenshots**

![image](https://user-images.githubusercontent.com/42123156/119371139-646f0800-bcb6-11eb-895c-30ddd152f5e1.png) ![image](https://user-images.githubusercontent.com/42123156/119371169-6e910680-bcb6-11eb-8694-8a02fee339dc.png)

**System Information**

 - OS Version: Windows 10 20H2 19042.985
 - App version: 2.3.11.0

**Additional comment**

This is not an issue when the folder contents were visible, not just the group headers.

**Comment by LukoFoks** [comment]
By the way sorry for my misunderstanding, but how did you find this feature? I have no idea running the version 1.5.0. I even look up the Release notes and couldn't find any mentions about it.

**Comment by winston-de** [comment]
> By the way sorry for my misunderstanding, but how did you find this feature? I have no idea running the version 1.5.0. I even look up the Release notes and couldn't find any mentions about it.

@LukoFoks This feature has yet to be released, and can only be found by building the source code from ``main``.

**Comment by MarkBirkholz** [comment]
Looks like it is necessary to call ToggleActiveView (to turn off zoom mode) when IsSourceGrouped is set to false. Either in the DetailsLayoutBrowser config or somewhere here https://github.com/files-community/Files/blob/main/Files/ViewModels/ItemViewModel.cs#L657.
(Sorry, i'm new to this project)

**Comment by yaichenbaum** [comment]
@nvi9 is this still an issue in v2.1.13?

**Comment by nvi9** [comment]
> @nvi9 is this still an issue in v2.1.13?

@yair100 yes it is

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.11.0 or above?

**Comment by nvi9** [comment]
> Is this still an issue in 2.3.11.0 or above? 

@Josh-65 yes, just checked it with version 2.3.11.0

**Comment by ferrariofilippo** [comment]
@nvi9 I don't whink that's a bug: that view shows you the existing groups and how many items they contain. If you turn off grouping there are no more groups so that page is empty.
Anyway, if you want to remove that empty page, I think we might add an entry saying: `All x items`, or we could simply navigate one page back

**Comment by Josh-65** [comment]
It should default to showing the items as normal with grouping none

**Comment by ferrariofilippo** [comment]
I should have fixed this. If you can confirm, I'll proceed with code cleanup
