### ISSUE TITLE
Hover to select item

### ISSUE THREAD

**Issue by LukoFoks** [files-community/Files#5013]
**Is your feature request related to a problem?**
Selecting items in the app is impossible, when the "Open items with one click" is enabled. Therefore I can't even use shortcut keys like `DEL` to delete a file quickly.

**Describe the solution**
As Windows Explorer does, I would like to select items by just hovering over them. It's fast and easy like the "One click to open" feature.

**Scope**

| Capability | Priority |
| :---------- | :------- |
| Select one item with hover | Must |
| Select multiple items with `CTRL` | Should |
| Select multiple item with `SHIFT` | Should |

**Comment by gave92** [comment]
Merging with #3682

**Comment by LukoFoks** [comment]
I added the multi-selection feature just in case the hover would be somewhat different. In the Double click mode it works just fine. Thank you and I'm looking forward to enjoy this feature!

**Comment by gave92** [comment]
Ah apologies was your request for multi selection with "Ctrl + Hover"? Currently even in one-click-to-open mode Ctrl+Left click should work

**Comment by R3voA3** [comment]
While ctrl + left click works fine, how is the user supposed to figure that out? I just found out because I wanted to open an issue and did a search first. Imho, hover to select should still work and the current solution should be an alternative way.

**Comment by gave92** [comment]
Still planned to be implemented as of as part of #3682
