### ISSUE TITLE
Disabling the folder loader bar?

### ISSUE THREAD

**Issue by Yolo-plop** [files-community/Files#5014]
**Is your feature request related to a problem?**
Files just looks great, especially compared to the aging default explorer. I just have one major issue, the loading bar at the top makes me feel like the app is sluggish. I have only SSD so everything is quick, but there is that bar that shows for like one tenth of a second and makes you feel, in my opinion, like you're waiting much longer than you are actually waiting.

**Describe the solution**
Add an setting to allow the users to disable the loader bar and have the same behavior as Windows, just don't show anything while it is loading.

**Scope**
| Capability | Priority |
| :---------- | :------- |
| Option to disable the loading bar | Must |

**Comment by yaichenbaum** [comment]
Disabling the loading bar isn't going to make the app any faster, it's used to indicate that the app is loading your Files. We have made several improvements in `main` in regards to loading items faster and you'll see the improvements of this in the next update.

**Comment by Yolo-plop** [comment]
Sorry but i strongly disagree and it's a general UX matter that i faced many times in web developement. My complain is not that the load is too slow, it's that the loader makes you feel like it is. Why show it for less than a second? It just makes the small load time noticeable.

**Comment by yaichenbaum** [comment]
@Yolo-plop You have a good point about the bright flash making it seem slow to the users, that's why we plan to make the loading indicator less prominent with #3922.

**Comment by mdtauk** [comment]
Perhaps only display the progress bar after a certain amount of milliseconds?

**Comment by yaichenbaum** [comment]
@mdtauk That's something to look at, can you add your feedbac to #3922?
