### ISSUE TITLE
Margins on layout modes are not equal on all sides

### ISSUE THREAD

**Issue by ryadhiprasetya** [files-community/Files#5015]
**Is your feature request related to a problem?**
1. Hard to select multiple item from top center.
2. Inconsistent margin

![image](https://user-images.githubusercontent.com/47018482/119379754-11af4380-bcea-11eb-92f1-59849aaec9fe.png)

**Describe the solution**
Give more and equal margin on each side 

**Describe alternatives you've considered**
good example, finder macos:
![image](https://user-images.githubusercontent.com/47018482/119380113-7d91ac00-bcea-11eb-973d-683367b6868d.png)

**Comment by yaichenbaum** [comment]
@winston-de This appears to be related to the grouped view feature, do you mind checking this one out?

**Comment by yaichenbaum** [comment]
@ryadhiprasetya This issue should be resolved with #5019.
