### ISSUE TITLE
Widget background brush on hover is hard to distinguish from normal brush in dark mode

### ISSUE THREAD

**Issue by winston-de** [files-community/Files#5016]
This is more noticeable now that the scale affect is gone.
Normal:
![image](https://user-images.githubusercontent.com/59544401/119383841-b5600b80-bc78-11eb-8714-03db89278146.png)

Hover:
![image](https://user-images.githubusercontent.com/59544401/119383860-bc871980-bc78-11eb-9024-185f81683a36.png)

_Originally posted by @winston-de in https://github.com/files-community/Files/pull/5010#issuecomment-847202065_

**Comment by mdtauk** [comment]
You could remove the background plate in the rest state, using only the border

**Comment by yaichenbaum** [comment]
> You could remove the background plate in the rest state, using only the border

@mdtauk this is a pretty simple fix, do you want to give it a try?

**Comment by mdtauk** [comment]
I think we should probably stick with using the Card brushes that come with WinUI - this way we are keeping consistent with Microsoft apps and other WinUI apps.

You should ensure the Rest and Hover brushes are being used correctly in Light and Dark themes.

**Comment by mdtauk** [comment]
Could you shift these to using the Button brushes then, and see if that improves things?

![image](https://user-images.githubusercontent.com/7389110/145881612-85847335-91a7-4bdc-8835-ba97bfe42093.png)

**Comment by yaichenbaum** [comment]
@mdtauk it's already using the button brushes 🤔

**Comment by mdtauk** [comment]
There is also the Grid View styling, that could be used.
![image](https://user-images.githubusercontent.com/7389110/145882435-782adbe3-dba2-478a-a5d1-550691c2ae65.png)

![image](https://user-images.githubusercontent.com/7389110/145882489-0a90ccaa-a145-4f31-9fbc-682eeea76471.png)

**Comment by mdtauk** [comment]
Whatever changes you make to the Bundles/Home Tab Cards - it should be used in a consistent manner with similar controls - so no implied differences will make users expect different behaviours from them

**Comment by yaichenbaum** [comment]
I guess this should really be brought up on the WinUI repo as the contrast ratio affect more than just Files, @winston-de any thoughts?

**Comment by mdtauk** [comment]
> I guess this should really be brought up on the WinUI repo as the contrast ratio affect more than just Files, @winston-de any thoughts?

Contrast ratio only applies to the button content and the hover's foreground and background
