### ISSUE TITLE
FILES Crashes

### ISSUE THREAD

**Issue by Kedehern71** [files-community/Files#5021]
[debug.txt](https://github.com/files-community/Files/files/6534754/debug.txt) 

FILES crashes when I open a certain OneDrive folder.  ALL other folders seem to open properly.   Files crashes for a single folder only.

**Comment by gave92** [comment]
Thanks for the report:

- Do you get a notification saying "something went wrong" or does the app just close?
- Could you try if it works is you disable these two settings (turn off caching) under Experimental? (warning: probably won't change a thing but it's worth trying)

![image](https://user-images.githubusercontent.com/9673091/110851026-ce2f6680-82b0-11eb-8974-599e144ff399.png)

**Comment by Kedehern71** [comment]
No notification – it simply shuts down.

Ok, turning caching OFF fixed the issue!  No crash.


Timothy A.C. Hader, NCARB
Senior Project Designer
ARCONS DESIGN STUDIO, PC
10550 Independence Pointe Parkway, Suite 300
Matthews, NC 28105
(O) 704-542-5252
(D) 704-815-6292
(M) 704-497-7484
WWW.ARCONSDS.COM<http://www.arconsds.com/>

***@***.***D750B9.37DF6C80]

CONFIDENTIALITY WARNING: This email may contain confidential or proprietary business information and is for the sole use of the intended recipient(s).  Any unauthorized use or disclosure of this communication, including attachments, is strictly prohibited. If you believe that you have received this email in error, please notify the sender immediately and delete it from your system.
