### ISSUE TITLE
Can't open created library on the home page

### ISSUE THREAD

**Issue by tsvietOK** [files-community/Files#5023]
**Explain the bug**
Can't open created library on the home page

**To reproduce**
1. Go to Home page
2. Create new library
3. Try to open it
4. Nothing happens when clicking on it (opening in new tab works fine)

**Expected behavior**
Library should open on mouse click.

**System Information**
 - OS Version: [e.g. Windows 10 20H2 19042.985] 
 - App version: [e.g. v1.3.1.0] 

**Additional comment**
App restart doesn't help.

**Comment by yaichenbaum** [comment]
@tsvietOK libraries are no longer displayed on the homepage so this issue should be resolved.
