### ISSUE TITLE
Crashes If Copying Large File/Folder and Open Large Folder Simultaneously

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#5024]
**Explain the bug**
`Files` crashes or closes unexpectedly if users copying large file (up to 3gb) and open large folder simultaneously.

**To reproduce**
1. Open New Tabs
2. Copy a Large File/Folder
3. While the app is copying the file(s), try open large folder simultaneously
4. See the error

**Expected behavior**
`Files` shouldn't crash or closes unexpectedly.

**Logfile**
Upload the log file here for us to understand your issue better. 
- You can access it from Settings->About->Open log location. 
or 
- Copy the debug.log and debug_fulltrust.log from the following directory, and upload the files here.
`%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6535861/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6535862/debug.txt)

**Screenshots**

https://user-images.githubusercontent.com/69080584/119426616-be61e300-bd33-11eb-8790-d8f726980478.mp4

**System Information**
 - OS Version: Windows 10 20H2 19042.985
 - App version: v1.5.0.0

**Additional comment**
Does this problem happen again after restarting the app? Yes this problem happens again after restarting the app with the less potential of crash, however it is annoying to copy the large file and suddenly it crashes which causes some file(s) to be corrupted.

**Comment by gave92** [comment]
Could you check if the same happens if you set gridview layout mode?

**Comment by stanleyowen** [comment]
Hi @gave92, this method works! However, it works more slower than before, is there an alternative way to solve this issue without using caching? Thanks.

**Comment by gave92** [comment]
@stanleyowen was turning off caching enough to fix the issue also in details view?

You could try reenabling the caching and to delete the "cache.db" file you can find in the folder where the log files are.

**Comment by stanleyowen** [comment]
Thanks @gave92, after deleting `cache.db` and reenabling the caching mode option, the app is no longer crash. I'll close this issue now.
