### ISSUE TITLE
Acrylic coloring issue in light mode.

### ISSUE THREAD

**Issue by Tropix126** [files-community/Files#5025]
**Explain the bug**
When interacting with certain UI elements in the app, the light mode acrylic occasionally switches themes to the dark mode tint.

**To reproduce**
Truthfully, I have no idea how this is reproduced exactly, however it often occurs when interacting with certain clickable UI elements. Two of these examples that trigger the visual bug almost 100% of the time in my testing were the TabView area after opening a new tab, and selecting a file entry in Details View.

**Expected behavior**
The acrylic keeps it's light coloring.

**Logfile**
N/A

**Screenshots**

https://user-images.githubusercontent.com/42101043/119436496-df014d00-bce1-11eb-87b0-f3e8f0220a29.mp4

**System Information**
 - OS Version: Dev (OS Build 21364.1000)
 - App version: 1.3.1.0 - **NOTE:** This is a built version of files from the `main` branch. I last pulled around 30 minutes before opening this issue. I'm not sure how version strings are handled on the developer build of Files.

**Additional comment**
None.

**Comment by ryadhiprasetya** [comment]
experience the same thing.

i build from source yesterday and get dark sidebar on white theme.
try to build last pulled 5 hour ago and bug is disappear, but get the same problem like your issue, glitch, sometime color is change weird

**Comment by mdtauk** [comment]
Same here, app theme set to dark, system so theme is light.

The acrylic sidebar changes from dark to light sporadically when hovering on random controls or other interactions

**Comment by Rasmagoric** [comment]
I get the same issue with the acrylic sidebar enabled or not and it only happens when windows is in light mode and files is set to dark.

**Comment by gave92** [comment]
I get the sidebar in dark tint only in Release mode, debug looks fine.

**Comment by duke7553** [comment]
Thank you for creating this feedback item. A solution for it is currently being reviewed as a PR (pull request) to our active development branch. We'll let you know once it's merged by closing this issue.
