### ISSUE TITLE
Apply admin action to all current operations

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#5030]
**Describe the solution**
Currently when transferring files that requires multiple admin actions I have to do it for each one and becomes annoying when there's many. There should be a apply to all that the original file explore has.

**Scope**
| Capability | Priority |
| :---------- | :------- |
| Add a apply to all check box on the admin prompt | Must |

**Comment by myfix16** [comment]
Agree. I think Windows's default explorer's way to handle this issue is a good reference.

**Comment by Windows11-Pro-Ultimate** [comment]
Yes please fix it.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #8809
