### ISSUE TITLE
Taking 15 seconds to open menu when rightclicking a file or folder

### ISSUE THREAD

**Issue by TheSpringBoy** [files-community/Files#5032]
**Explain the bug**
When right-clicking a file or folder to get the menu, where you can delete and rename, its taking about 15 seconds to open, sometimes the app will freeze and then I need to reopen it in order to use it again.
My app is in the latest version from the Microsoft Store so the latest update didnt fixed it.

**To reproduce**
Right click filr ot folder

**Expected behavior**
It should just open the menu immidiately like the normal file explorer

**Logfile**

[debug.txt](https://github.com/files-community/Files/files/6540816/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6540817/debug_fulltrust.txt)

**System Information**
 - OS Version: Windows 10 21H1 19043.985
 - App version: v1.5.0.0

**Additional comment**
The entire app is very laggy and almost unusable because of it, my pc is very strong (Ryzen 9 5900x nvme and all of the good stuff) so its not the problem

**Comment by Skaldebane** [comment]
Perhaps you installed many apps that add their entries to the contextual bar?

**Comment by TheSpringBoy** [comment]
Google Drive, WinRar and eset. thats it.
but it also freezing so I think thats a different problem

**Comment by gave92** [comment]
@TheSpringBoy could you post a screenshot of the context menu that appears in Files (if/when it appears)?

@yair100 should we add an option to disable getting the context menu items from explorer?

**Comment by yaichenbaum** [comment]
@gave92 That doesn't seem like a bad idea. It can be under the experimental settings page.

**Comment by gave92** [comment]
This is fixed on main.
