### ISSUE TITLE
Show file extension when creating a new file

### ISSUE THREAD

**Issue by mangoepic** [files-community/Files#5033]
**Is your feature request related to a problem?**
When creating a new File in Windows Explorer or exporting a file from Software like Photoshop, the File extension usually gets shown in the naming input field.

**Describe the solution**
Show the File extension behind the cursor in the input field.

This helps to
 - Reassure the user that they are creating the right File
 - Gives the user a chance to still change the file type easily
 - Users are accustomed to it, so it helps to avoid things like "File.txt.txt"

**Describe alternatives you've considered**
If there was no dialogue and the File would be created in the Folder window like in Win Explorer, it would still be necessary

**Scope**

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow users to see the file extension in an inline text box when creating a new file| Must |
| This proposal will allow users to edit the file extension when creating the file | Could |
| This proposal will get disabled with a feature to toggle file extensions | Could |

If Files had a option to toggle File extensions, it could make sense to disable the extension in the dialogue, too i am not sure what users would prefer here, but Windows Explorer does it that way.

If the functionality gets toggled by a show file extensions feature, or the feature does not get implemented this way I think it would be helpful to signal the user that he is indeed creating the file he wants to with text in the file creation dialogue.

*For example:*

**Creating New Text File**
Insert File Name

*Instead of just:*

**Insert File Name**

*(like in the screenshot below)*

**Additional comment**
![image](https://user-images.githubusercontent.com/71931749/119567557-bf832680-bdac-11eb-8908-03682460a300.png)
App Version: 1.5.0.0

**Comment by yaichenbaum** [comment]
@mangoepic Do you mind if I change this feature request to include support for an inline text box (similar to what you see when you rename an item) when creating items?

**Comment by tellmewhy12** [comment]
@yair100 do you mean an option to have file creation that looks like in windows explorer instead of the pop up dialogue?
personally i kinf of like the dialogue, it looks cool and modern, but i haven't used it too much yet .. so can't really say? But if you like this feature i mean sure go ahead, users would probably expect this behaviour anyways? maybe as an option?

**Comment by Josh-65** [comment]
Since you can add a extention in the rename and creation text feilds im going to close this.
