### ISSUE TITLE
Indication for Drag'n'Dropping multiple files

### ISSUE THREAD

**Issue by mangoepic** [files-community/Files#5035]
**Is your feature request related to a problem?**
It isn't clear that Files has the ability to drag and drop multiple files to the user, when he can only see one file following the mouse cursor while drag and dropping.

**Describe the solution**
An indication of having multiple files in the drag and drop

For Example by doing one or more of these things:
- Doing it like a web browser with a transparency gradient
- Showing a fading stack of files (the dragged file looks different according to view in files in contrast to windows explorer where it always is just a square, so maybe the appearance of the stack would have to adjust to that?)
- Showing a number with the amount of files, for example where the "blocked" symbol is or beside

(I believe the blocked symbol should appear while just having the files in the same folder, because this isn't a illegal operation it just does nothing and the user expects it to be this way?)

**Scope**

| Capability | Priority |
| :---------- | :------- |
| This proposal will give users an indication that multiple files are getting moved | Must |
| This proposal will show users how many files are getting moved | Could |
| This proposal will disable the illegal action symbol while staying in the same folder with drag and drop | Could |

**Additional comment**
![GIF 25 05 2021 23-26-04](https://user-images.githubusercontent.com/71931749/119571112-41754e80-bdb1-11eb-8865-cef2986800f5.gif)
App Version: 1.5.0.0

**Comment by yaira2** [comment]
@winston-de can we change the icon to indicate multiple items are selected?

**Comment by winston-de** [comment]
@yair100 Which icon?

**Comment by winston-de** [comment]
If you mean the 🚫 icon, I don't believe you can because that's managed by the system. There is a count already shown, however. 

![Files_dxADkXc7Zn](https://user-images.githubusercontent.com/59544401/226208106-7bfa5f72-4a9a-4026-8698-1570086fff0a.png)

**Comment by yaira2** [comment]
File Explorer shows an icon of the item being dragged.

**Comment by winston-de** [comment]
I'm sure with WinUI 3 you could find some other API to use for drag and drop to make it more customizable. But unfortunately with the UWP APIs we are currently using the options are very limited.

**Comment by yaira2** [comment]
Thank you for your feedback, the latest version of Files displays a number indicating how many items are being dragged..
