### ISSUE TITLE
Link file problems

### ISSUE THREAD

**Issue by mangoepic** [files-community/Files#5049]
**Explain the bug**
I have noticed multiple problems with link files

- Link files can't be dragged around like other files (they're just stuck)
- When renaming link files the .lnk extension gets removed
- Creating link files using alt+drag isn't working (it only shows "Link" hovering over Desktop)

**System Information**
 - OS Version: Windows 10 20H2 19042.985
 - App version: 1.5.0.0

**Comment by yaichenbaum** [comment]
@mangoepic Support for dragging shortcut files hasn't been implemented yet, I thought we had an issue for this but I can't find it, can you open one so we can continue tracking it?

> When renaming link files the .lnk extension gets removed

This definitely looks like a bug, can you open a separate issue for this?

> Creating link files using alt+drag isn't working (it only shows "Link" hovering over Desktop)

This hasn't been implemented yet, can you create a new feature request so we can track it separately?

**Comment by tellmewhy12** [comment]
@yair100 alright I will make separate issues later, just wondering 

> This hasn't been implemented yet

![image](https://user-images.githubusercontent.com/71931749/119871349-a43a2780-bf22-11eb-9d4f-42a7186d3972.png)

why this shows up when dragging to desktop 🤔

**Comment by yaichenbaum** [comment]
Thanks!
