### ISSUE TITLE
Google Drive folders not showing up

### ISSUE THREAD

**Issue by AE102** [files-community/Files#5050]
When I load up my google drive (virtual drive.) No folders appear. When I try to paste in the exact file path it still shows nothing.

**To reproduce**
1. Go to 'Google Drive drive'
2. And nothing is there.

**Expected behaviour**
To show the folders and files

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6556086/debug.txt)

**Screenshots**
![image](https://user-images.githubusercontent.com/71657811/119880014-ba94b300-bf23-11eb-9939-94493fb8dc57.png)
**System Information**
 - OS Version: Windows 10 Version	10.0.19042 Build 19042
 - App version: 1.5.0.0

**Comment by mauriciomagalhaes** [comment]
I have the same problem

**Comment by AE102** [comment]
> I have the same problem,
> I have to type the path to the folder to access it

Even when I type in the path it doesn't diaplry anything.

**Comment by mauriciomagalhaes** [comment]
![image](https://user-images.githubusercontent.com/28632649/119998154-d3927800-bfa6-11eb-9656-bec98674e595.png)
![image](https://user-images.githubusercontent.com/28632649/119998401-0c325180-bfa7-11eb-91b8-c0a45307e216.png)

**Comment by mauriciomagalhaes** [comment]
only shows when I go to the directory that I know exists

**Comment by gave92** [comment]
Could you try to turn on the option to show hidden files and turn off the option to hide system and protected files?

**Comment by mauriciomagalhaes** [comment]
Dont work!

**Comment by gave92** [comment]
Could you check if turning off "Enable individual preferences for individual folder" under Files Settings > Files and Folders fixes the issue?
