### ISSUE TITLE
Feature: Add different click options based on user input method (Touch or mouse)

### ISSUE THREAD

**Issue by Agredo** [files-community/Files#5052]
### What feature or improvement do you think would benefit Files?
Open files and directories with one click works for touch but is unfamiliar using mouse
Allow openening files on touch screen by taping once and with mouse via double click. 

### Requirements

- 

### Files Version

2.3.11.0

### Windows Version

10.19043.1899

**Comment by yaichenbaum** [comment]
@ADeltaX 👀

**Comment by Josh-65** [comment]
Asking @yaichenbaum for approval.

**Comment by yaichenbaum** [comment]
I'm not against the idea but we need to do some user research and come up with a good ux before approving this change.

**Comment by yaira2** [comment]
Thank you for your feedback. We appreciate the time and effort you took to share your idea with us. After careful consideration, we have decided not to implement this feature at this time. However, if our plans change in the future, we'll make sure to announce any updates in our release notes.
