### ISSUE TITLE
QuickLook not working

### ISSUE THREAD

**Issue by viveksupport** [files-community/Files#5056]
**Explain the bug**
Quicklook does not seem to be working in the Files app. I have Quicklook installed and it worked in Windows File Explorer but does not work in Files. Hitting the spacebar does not do anything. I have checked for other issues but they all say that the feature has been removed. Is there any way to enable Quicklook?

**To reproduce**
1. Go to 'Files'
2. Click on 'any file'
4. Press the 'spacebar'
5. See the error

**Expected behavior**
Quicklook previews the file selected

**Logfile**

**Screenshots**
Add screenshots to help explain your problem if needed.

**System Information**
 - OS Version: Windows Server 2019 1809 (OS Build 17763.1935)
 - App version: Files Version: 1.5.0.0

**Additional comment**
Is this supposed to happen? Quicklook version 3.6.11

**Comment by gave92** [comment]
Quicklook feature was not removed. Could you upload the two app's debug files?
- You can access them from Settings->About->Open log location. 
or 
- Copy the debug.log and debug_fulltrust.log from the following directory, and upload the files here.
`%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 

(Note that QuickLook must be opened before opening Files or it won't be detected)

**Comment by viveksupport** [comment]
Here they are
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6564793/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6564794/debug.txt)

**Comment by viveksupport** [comment]
Also, Quicklook is open before starting Files and I can see the Quicklook icon in the taskbar.

**Comment by Gmemster** [comment]
MIne is working.

**Comment by gave92** [comment]
This is not an issue with the Quicklook feature in particular, I dont' think anything related to the fulltrust process is working for him.
@viveksupport could you post a screenshot of how the context menu for file/folders appears for you in Files?

**Comment by viveksupport** [comment]
The right-click menu does not have any of the extra options I have in File Explorer. Here are the two screenshots of the same file: 
![image](https://user-images.githubusercontent.com/74747996/120094035-a0352200-c13b-11eb-8d19-2a415d9791fc.png)
![image](https://user-images.githubusercontent.com/74747996/120094056-c1960e00-c13b-11eb-88a0-b3aa2c7d71df.png)

Thanks

**Comment by viveksupport** [comment]
I have reinstalled the program and I have checked my Windows Security settings to make sure it has full access to the system.
A lot of the functions are not working for me in Files. I can't even copy/paste files. Right-click>Paste doesn't work, Ctrl+V also doesn't work.

**Comment by gave92** [comment]
Thanks a lot for the info @viveksupport. I'm going to close this issue as the issues you're facing are not tied to quicklook. Not being able to copy paste has been reported in #4665, #4971.
