### ISSUE TITLE
个性化中选择第三方终端 ConEmu 发生 BUG

### ISSUE THREAD

**Issue by yeungchie** [files-community/Files#5059]
## 个性化中选择第三方终端 `ConEmu` 发生 BUG

> “第三方” 指非 `CMD` 或 `PowerShell`

1. 症状是疯狂弹出新的 `ConEmu` 终端窗口，只有重启或者卸载 `Files` 才能停下来。
2. 而且现在我也不能选择其他的第三方的终端应用了，因为我重新安装 `Files` 后，只要点击 修改终端项 中那个🖌编辑按钮就会开始疯狂弹出 `ConEmu` 终端窗口了。结果我又得把 `Files` 卸载一遍。。。

**Comment by gave92** [comment]
Could you post your "terminal.json" file?

**Comment by yeungchie** [comment]
### like this
![terminalConRmu_1](https://user-images.githubusercontent.com/30793662/121055044-8193f280-c7ef-11eb-9ec8-5a7040377206.gif)

---

### terminal.json
```json
{
  "version": 1,
  "DefaultTerminalName": "PowerShell",
  "terminals": [
    {
      "name": "CMD",
      "path": "cmd.exe",
      "arguments": "",
      "icon": ""
    },
    {
      "name": "PowerShell",
      "path": "powershell.exe",
      "arguments": "-noexit -command \"cd '{0}'\"",
      "icon": ""
    }
  ]
}
```

**Comment by yeungchie** [comment]
+ And when I uninstall "files", these terminal will close automatically in turn.

**Comment by gave92** [comment]
I see no reference to ConEMu in terminals.json. Do you have this options set in COnEmu?

![image](https://user-images.githubusercontent.com/9673091/121070945-9bbdd880-c7cf-11eb-9bed-35250a2dd506.png)
