### ISSUE TITLE
Files crashes very often,  almost always crashes with the onedrive folders.

### ISSUE THREAD

**Issue by Neikon** [files-community/Files#5064]
**Explain the bug**
The program crashes very often, sometimes just by opening the download folder, but almost always crashes with the onedrive folders.
I have configured network disks, maybe that is relevant. 
![imagen](https://user-images.githubusercontent.com/1765319/120115155-b4504200-c182-11eb-930d-0b00bbcec2ed.png)

**To reproduce**
1. Simply navigate to a onedrive folder which files is not localy yet
2. The programme will think for a moment and then disappear. 
![imagen](https://user-images.githubusercontent.com/1765319/120115188-da75e200-c182-11eb-98b1-c1972812b948.png)
 

**Expected behavior**
Work without crash in any moment 
**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6566687/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6566688/debug_fulltrust.txt)

**Screenshots**
![imagen](https://user-images.githubusercontent.com/1765319/120115663-01cdae80-c185-11eb-9a82-170ff3856f13.png) 
Half a second after taking this screenshot, the app crashes and closes suddenly.

**System Information**
 - OS Version: Edición	Windows 10 Pro
Versión	21H1
Instalado el	‎18/‎12/‎2020
Compilación del sistema operativo	19043.985
Experiencia	Windows Feature Experience Pack 120.2212.2020.0

 - App version: 1.5

**Additional comment**
it has been happening for months and since before upgrading to wind10 21h1

**Comment by gave92** [comment]
Could you try deleting the two debug files, trigger the crash again and upload the debug files again?

**Comment by Neikon** [comment]
> 
> 
> Could you try deleting the two debug files, trigger the crash again and upload the new debug files?

here are the clean records
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6566739/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6566740/debug.txt)

**Comment by gave92** [comment]
A couple of things you can try.

1. Does it works is you disable these two settings (turn off caching) under Experimental?

![image](https://user-images.githubusercontent.com/9673091/110851026-ce2f6680-82b0-11eb-8974-599e144ff399.png)

2. Does it work if you change the following options?
- Turn Off "Enable individual preferences for individual directories" in Settings > Files and Folders
- Set Tiles or GridView layout mode
- Try to trigger the crash

**Comment by Neikon** [comment]
Yes! Files only crashes if a set view to "details". I desactivate experimental features too

**Comment by gave92** [comment]
Thanks for confirming, this issue is fixed in latest code.
