### ISSUE TITLE
Feature request: Allow hiding options from the toolbar

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#5071]
**Scope**

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow right clicking on toolbar options to unpin them | Must |
| This proposal will add a section to the appearance settings page where users can pin/unpin options from the toolbar | Must |

**Comment by BanCrash** [comment]
@yair100 could you assign this to me? While I can't assure (yet) the first condition, I can do the second, so in the worst scenario at least it will be done half of the work.

**Comment by yaichenbaum** [comment]
@BanCrash we don't plan on implementing this anymore, sorry about the confusion.

**Comment by BanCrash** [comment]
> @BanCrash we don't plan on implementing this anymore, sorry about the confusion.

@yair100 No problem.
