### ISSUE TITLE
Feature request: right clicking on back and forward buttons should show navigation history

### ISSUE THREAD

**Issue by gave92** [files-community/Files#5073]
**Feature description**
Right clicking on back and forward buttons should a popup containing folders from navigation history. This would allow to navigate more quickly back and forth.

Something like web browsers do:

<img src="https://user-images.githubusercontent.com/9673091/120123410-014a0d80-c1af-11eb-8078-16fb1d04dbef.png" width="500" />

**Scope**
| Capability | Priority |
| :---------- | :------- |
| This proposal will add a popup with visited folders when right-clocking on back/forward buttons of the navigation bar | Must |

**Comment by yaichenbaum** [comment]
Merging with #4098 😂

**Comment by gave92** [comment]
Oops haven't seen it thanks =)
