### ISSUE TITLE
Feature: Added resolution info to details pane

### ISSUE THREAD

**Issue by SuperZombi** [files-community/Files#5075]
### What feature or improvement do you think would benefit Files?

Add the file resolution to the file information in preview mode, and also let the user choose what information to display in this mode.

![image](https://user-images.githubusercontent.com/75096786/120150336-9b33a980-c1f3-11eb-8aaf-e2ac61fdcc50.png)

### Files Version

2.3.11.0

### Windows Version

10.19043.1899

**Comment by yaichenbaum** [comment]
Fyi @winston-de

**Comment by Josh65-2201** [comment]
@yair100

**Comment by yaira2** [comment]
@SuperZombi this will be included in the next release.
