### ISSUE TITLE
Remove "Cloud drives" section when there are no cloud drives

### ISSUE THREAD

**Issue by luximus-hunter** [files-community/Files#5076]
**Is your feature request related to a problem?**
No, but it's a slight design inconvenience

**Describe the solution**
Since I uninstalled OneDrive, and have no other cloud providers, the "Cloud drives" section is empty. I don't think it should display when there are no drives connected to it.

**Describe alternatives you've considered**
N/A

**Additional comment**
App version: 1.5.0.0

![image](https://user-images.githubusercontent.com/49814847/120173754-a4794200-c204-11eb-86af-b85ccadcd678.png)

**Comment by gave92** [comment]
Merging with #3912
