### ISSUE TITLE
a11y: extraneous information is read in file/folder list

### ISSUE THREAD

**Issue by beqabeqa473** [files-community/Files#5079]
Hello.

When using screenreader, and navigating files and follders list, information is announced in the following way.

fsdn, C:\Users\beqap\Downloads\fsdn, Folder

if folder has some sort of needed value, it cannot be told the same about path.
because of that, navigation becomes extremely slow.

It would be great if you rethink display behaviour of such information for screenreaders and do it for example in this way.
fsdn, Folder
or maybe better, as it is in total commander for example
fsdn, <DIR>
And remove File from type of files, as we already know that folders have identification sign.

Thanks.

**Comment by yaichenbaum** [comment]
@beqabeqa473 Is this still an issue in `main`?

**Comment by beqabeqa473** [comment]
Yes

**Comment by yaichenbaum** [comment]
@beqabeqa473 Is the issue that it reads the item path, or the item type?

**Comment by yaichenbaum** [comment]
@beqabeqa473 Thanks for catching this!

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5769.
