### ISSUE TITLE
Right Click Freezes with pCloud

### ISSUE THREAD

**Issue by minidarknova** [files-community/Files#5080]
If you have Files (obviously) and pCloud desktop client.
Right clicking on anything will freezes the software for 2-3 minutes before crashing completely.
I have tested this. I used ContextMenu Cleaner from Easy Context Menu latest version and disabled the pCloud items (copy this to pcloud, backup this folder, sync to pcloud). Once this is removed; Files, can easily open right click menu on files and folders. But as soon as you turn it back on, the freezes and crashing comes back.  
If you need more information, I'll be happy to help and provide.

Files 1.5 version

**Comment by gave92** [comment]
Thanks for this report. We'll investigate.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5081.
