### ISSUE TITLE
Replacement confirmation for multiple files

### ISSUE THREAD

**Issue by intricatebiscuit** [files-community/Files#5083]
This is probably a duplicate feature request and so I apologize I am new to github.

When duplicate files are found on move / copy operations, a check box that says - repeat (replace / duplicate) for all files - would be very desirable.

Thank you for your great work.

**Comment by yaichenbaum** [comment]
@intricatebiscuit Thank you for opening this feature request, we have made some changes in `main` that resolve this issue.
