### ISSUE TITLE
pCloud P: in address bar will get you BSOD

### ISSUE THREAD

**Issue by minidarknova** [files-community/Files#5085]
Typing in P: in address bar to access your pCloud partition/folder will get you blue screen of death with error bxxconnect2007 (I dont remember the x bits)

**Comment by gave92** [comment]
Could you get a screen recording of this happening (e.g using a phone)? Thanks!

**Comment by minidarknova** [comment]
https://imgur.com/a/Othmyzn

Please do NOT make me do it again....I do not wanna f-up my pc

**Comment by mod-terrik** [comment]
![pcloud](https://user-images.githubusercontent.com/85971103/122222414-3d07f700-ce80-11eb-90ac-fe936bb31826.PNG)

FYI I have pcloud drive mapped to P: and when I access it in the address bar it works fine. See screenshot.

**Comment by yaichenbaum** [comment]
@minidarknova in order to help investigate this issue, can you upload the log files and let us know which version of Files you're having this issue with?
