### ISSUE TITLE
No Blue selection box in details mode

### ISSUE THREAD

**Issue by awesomelewis2007** [files-community/Files#5092]
**Explain the bug**
No selection box in details mode

**To reproduce**
1. Go to 'view mode'
2. Click on 'drag your mouse over files and folders'

**Expected behavior**
A blue selection box to appear 

**Screenshots**
![image](https://user-images.githubusercontent.com/60709927/120286225-eb734000-c2b5-11eb-9a09-30ca6769aa40.png)
![image](https://user-images.githubusercontent.com/60709927/120286348-0d6cc280-c2b6-11eb-9e4d-026d2127ef22.png)

**System Information**
Device name	XPS-Lewis
Processor	Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz   1.99 GHz
Installed RAM	8.00 GB (7.75 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	Pen support

Files app from the Microsoft store v1.5.0.0

**Additional comment**
The problem never goes away

**Comment by gave92** [comment]
Thanks for the report. This is fixed in latest code.

**Comment by awesomelewis2007** [comment]
Thanks for replying so quickly and fixing the code @gave92
