### ISSUE TITLE
Feature: Add artworks to special folders if they are empty

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#5093]
OneDrive app for example adds an artwork if the recycle bin is empty. Same could be done for the home screen if no widgets are activated.

Recycle Bin
![image](https://user-images.githubusercontent.com/17484252/120337821-f351d500-c2f3-11eb-8aa3-ac1d30830100.png)

Access Denied
![image](https://user-images.githubusercontent.com/17484252/120338643-b89c6c80-c2f4-11eb-842e-c2db1933be1f.png)

**Comment by cinqmilleans** [comment]
For a normal folder, it is also much more beautiful and ergonomic.

**Comment by winston-de** [comment]
If this is implemented, a good source for these would likely be https://undraw.co/ since they are free to use and don't require attributions.

**Comment by yaichenbaum** [comment]
@R3voA3 wouldn't this be useful for regular folders as well?

**Comment by R3voA3** [comment]
Sure, but might be a bit too much.

**Comment by yaichenbaum** [comment]
@R3voA3 do you have any assets in mind that we can use for this?

**Comment by QuaintMako** [comment]
I'm gonna give it a shot, it sounds like a fun little implementation to do!

Tried to find a picture, anyone of those would do?/
- https://www.freepik.com/free-vector/no-data-concept-illustration_5928293.htm#query=empty&position=39&from_view=search
- https://www.freepik.com/free-vector/empty-concept-illustration_7117865.htm#query=empty&position=2&from_view=search
- https://www.freepik.com/free-vector/no-data-concept-illustration_8961448.htm#query=empty&position=11&from_view=search

**Comment by yaichenbaum** [comment]
I'm not a fan of any of those, the Phone Link app is a pertty good example of what I'm looking for.

**Comment by QuaintMako** [comment]
> I'm not a fan of any of those, the Phone Link app is a pertty good example of what I'm looking for.

Gave a quick look to the app, maybe something from https://undraw.co/ could do the trick? As @winston-de suggested.

**Comment by HorseBandit** [comment]
@QuaintMako  How are you doing on this one?

**Comment by mdtauk** [comment]
Whatever illustration or icon you go for, it needs to be consistent throughout the app, for other empty states

**Comment by QuaintMako** [comment]
> @QuaintMako  How are you doing on this one?

Haven't touched it in a long while.
