### ISSUE TITLE
Unified design for user input dialogs

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#5094]
Right now, the user has to face several different dialog designs.

![image](https://user-images.githubusercontent.com/17484252/120340891-b1765e00-c2f6-11eb-8dad-cbd7c474cab5.png)

![image](https://user-images.githubusercontent.com/17484252/120340917-b804d580-c2f6-11eb-9919-3875e6ac4332.png)

![image](https://user-images.githubusercontent.com/17484252/120340937-bdfab680-c2f6-11eb-9d1a-7fa88ff16d5e.png)

Things to unifiy:

- [ ] width
- [ ] height
- [ ] aspect Ratio
- [ ] margins
- [ ] buttons width
- [ ] button background
- [ ] corner radius
- [ ] position on the screen

**Comment by yaichenbaum** [comment]
@R3voA3 Are you building from `main`? If so, can you make a list of the dialogs using the older style?

**Comment by R3voA3** [comment]
Unfortunately I am not building from main.

**Comment by yaichenbaum** [comment]
In that case this issue should be resolved.
