### ISSUE TITLE
Feature request: Add support for middle click to open folder in new tab in ColumnView 

### ISSUE THREAD

**Issue by d2dyno1** [files-community/Files#5095]
**Is your feature request related to a problem?**
 ColumnView doesn't have the option to middle-click to open a folder in new tab while other layout modes do.

**Describe the solution**
Implement middle click to open folder in new tab in ColumnView.

**Scope**

| Capability | Priority |
| :---------- | :------- |
|Implement middle click to open folder in new tab in ColumnView. | Must |

**Comment by yaichenbaum** [comment]
@d2dyno1 Would you like to work on this?
