### ISSUE TITLE
Files crashes when launched from admin command line

### ISSUE THREAD

**Issue by monsterzzz** [files-community/Files#5096]
在命令行输入 files . 或者其他路径都会闪退
不使用管理员权限则不会

**Comment by gave92** [comment]
There are issue launching UWP apps as admin, also seen in #3117

**Comment by yaichenbaum** [comment]
@gave92 was this resolved?

**Comment by gave92** [comment]
It was, but the fix was later reversed as it (probably) caused windows store certification failure.

**Comment by Josh-65** [comment]
Is fixed moving to Wasdk?

**Comment by gave92** [comment]
It is, at least in my testing.
