### ISSUE TITLE
Enhancement: Replace theme combo box with radio buttons

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#5099]
**Scope**

| Capability | Priority |
| :---------- | :------- |
| This proposal will replace the theme combo box on the appearance settings page with radio buttons | Must |

**Comment by lukeblevins** [comment]
@yair100 How will this work with detected custom app themes?

**Comment by yair100** [comment]
> @yair100 How will this work with detected custom app themes?

Custom themes has a separate combo box, this proposal is limited to the dark/light/default options.
