### ISSUE TITLE
Colorize! app is not working properly (to change folder color)

### ISSUE THREAD

**Issue by monimesita** [files-community/Files#5111]
**Explain the bug**
I was using the Colorize! app to put color on the folders before start using "Files", however, is not working with Files, the little icon is not coloured, but the preview does.

**To reproduce**
1. Select a folder
2. Right Click 
3. Click on "Colorize!" 
4. Select any color
5. See that the icon does not change of color.

**Expected behavior**
It is expected to see immediately the change of color in the folder, as well as in the preview.

**Screenshots**
![image](https://user-images.githubusercontent.com/85280827/120613276-b123b300-c41b-11eb-88b8-ce4b51fc6276.png)

**System Information**
 - OS Version: Windows 10 Home 19041.985
 - App version: v1.5.0.0

**Additional comment**
Does this problem happen again after restarting the app? No, when restart the app, the icon color is the new one, the right one. But that means I have to close and open again to see the changes. It is not the idea.

Thanks!!!

**Comment by gave92** [comment]
What about refreshing the folder (F5)? Is it enough to update the icon?

**Comment by monimesita** [comment]
Gave92, yes! now it works, when press F5! thanks! :)

**Comment by gave92** [comment]
Thanks for confirming, closing this for now. We'll look for a way to do this automatically.
