### ISSUE TITLE
Single Click and point to select

### ISSUE THREAD

**Issue by dheerajvirgo** [files-community/Files#5116]
**Is your feature request related to a problem?**
Yes. the feature that lets you open files with one click basically removes the option to select files. 

**Describe the solution**
Windows solves this by letting us select by pointing at the files.  Adding that would be very useful

**Describe alternatives you've considered**
since selecting option is gone i basically turned off one click

**Scope**

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**System Information**
 - OS Version: [e.g. Windows 10 20H2 19042.804] (Press WIN + PAUSE/BREAK, use the copy button at the bottom)
 - App version: [e.g. v1.0] (In the app, go to Settings -> About, the version is shown at the top)

**Additional comment**
Add any other comment or screenshots about the feature request here. What device type/UI layout and app version?

**Comment by gave92** [comment]
Merging with #3682
