### ISSUE TITLE
Bug: PDF preview pages are very blurry at low scaling

### ISSUE THREAD

**Issue by winston-de** [files-community/Files#5117]
**Explain the bug**
In the pdf preview, pages are blurred to the point where they are almost unrecognizable. 

**To reproduce**
1. Open files
2. Move it to monitor with low scaling
3. Open preview pane, select pdf
4. Content is blurred to the point of being unrecognizable

**Expected behavior**
PDF pages should appear sharp.

**Logfile**
NA

**Screenshots**
![image](https://user-images.githubusercontent.com/59544401/120700228-4350a900-c466-11eb-98fe-cd5dbad27717.png)

**System Information**
 - App version: 1.5.27.0

**Additional comment**
The fix for #3477 can likely be used to fix this issue.

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.11.0 or above?

**Comment by yaichenbaum** [comment]
Still an issue, we might need to use a different control to render the preview.
Fyi @hez2010

**Comment by lucas-thiebaut** [comment]
![Capture d'écran 2023-05-05 195320](https://user-images.githubusercontent.com/128183422/236532519-87a7f8bd-17a8-477c-ad6f-99005d1e54ae.png)
![Capture d'écran 2023-05-05 195333](https://user-images.githubusercontent.com/128183422/236532521-907f4486-4266-4552-a967-987ef2af65e5.png)
@yair100 Personally I have no problem with the preview pane (neither blurry nor small thanks to the option show only the preview)
