### ISSUE TITLE
Feature: Show files the user has recently created in the recent items widget

### ISSUE THREAD

**Issue by winston-de** [files-community/Files#5118]
**Is your feature request related to a problem?**
Windows explorer shows recently created items in quick access, which makes it easy to view or drag and drop files that were just created.

**Describe the solution**
Show files recently created by the user in the recent items list.

**Describe alternatives you've considered**
N/A.

**Scope**

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow users to view files they recently created in the recent items widget | Must |
| This proposal will use a filesystem watcher or similar api to check when the user saves a new file, and add it to the recent items list | Could |

**Additional comment**
We can enumerate the items in ``%userprofile%\AppData\Roaming\Microsoft\Windows\Recent`` to implement this feature.

**Comment by yaira2** [comment]
@jiejasonliu can you confirm if this still an issue?

**Comment by jiejasonliu** [comment]
> @jiejasonliu can you confirm if this still an issue?

hmm I think so. if you create files on windows explorer, it works great.
but from Files, you'd need to manually open it for it to appear in recents.

**Comment by yaira2** [comment]
I think we address this by adding a shortcut to `%AppData%\Microsoft\Windows\Recent\`.
