### ISSUE TITLE
Implement drag support for items in the recent files widget

### ISSUE THREAD

**Issue by winston-de** [files-community/Files#5120]
**Describe the solution**
Allow items in the recent items widget to be dragged, so that users can easily drag items they were recently using into other applications. For example, the user could drag a document they just opened into mail to attach it. 

**Describe alternatives you've considered**
Copy-paste maybe.

**Scope**

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow users to drag items from the recent items widget into other programs | Must |

**Comment by gave92** [comment]
Bumped #8282
