### ISSUE TITLE
Switching the layout in an empty directory hides the "This folder is empty" text

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#5121]
**Is your feature request related to a problem?**
Currently some layouts like Grid make it hard to tell if the folders empty or files isn't loading the content. As it just appears blank.

**Describe the solution**
Text to say "This folder is empty" should be added

**Scope**
| Capability | Priority |
| :---------- | :------- |
| Keep "This folder is empty" text when switching layout | Must |
| Add a related image above the text (Like OneDrive and Teams) | Could |

**System Information**
 - OS Version: Windows 10 21H1 19043.1023
 - App version: v1.5.26

**Comment by yaichenbaum** [comment]
This is already implemented in `main`. However, it appears that switching the layout inside an empty directory will hide the text.

**Comment by d2dyno1** [comment]
@Josh-65 Closed with #7909
