### ISSUE TITLE
Add Latin American Spanish translations

### ISSUE THREAD

**Issue by XPoppyX** [files-community/Files#5123]
I would like to continue translating but in **es-419** (Latin American Spanish), because I'm actually Latin American and **es-ES** which is where I am adding my translations are for Spain. There are differences between Castilian (Spain) and Latin American Spanish.

**Scope**

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow strings to be translated into es-latam without worrying about any word or accent that is not used in Spain | Must |
------------

I have the changes ready to open a PR

**Comment by yaichenbaum** [comment]
@XPoppyX I added es-419 to `main`, looking forward to your pull request 🙂
