### ISSUE TITLE
F11 to Toggle Fullscreen

### ISSUE THREAD

**Issue by Rasmagoric** [files-community/Files#5126]
There's already a shortcut to toggle fullscreen (win+shift+enter) in uwp apps, but F11 is quicker way and a shortcut adopted in most of programs such as browsers, code editors , default file explorer etc.

**Comment by levimatheri** [comment]
@yair100 I'm new here. I've decided to take a stab at this. Will submit a PR for review. Thanks!

**Comment by yaichenbaum** [comment]
@levimatheri Welcome! When implementing this, you should probably add the logic to MainPage.xaml.cs.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5152.
