### ISSUE TITLE
Launching explorer.exe with arguments just opens explorer.exe

### ISSUE THREAD

**Issue by JotaRata** [files-community/Files#5132]
Ok title might be a little misleading..

if you execute `explorer "C:\Users"` or something like this in CMD or another program calls it this way (i.e. Steam)
It just opens regular explorer.exe and not Files even when the guide for making Files the default explorer is followed as intended

**Expected behavior**
Files should open in the desired directory when executing `explorer "Directory"`

**Logfile**
No logfile necessary

This is a small issue but quite annoying

**Comment by duke7553** [comment]
Considering explorer.exe is itself an executable, and Files supports launching from the command line with args, we don't want to make any changes that overwrite the explorer.exe binary.

**Comment by JotaRata** [comment]
Is it possible to use the same method that launches Files using Win+E shortcut to override the excecution of explorer.exe with args?

**Comment by JotaRata** [comment]
Nevermind I found the solution!

There's no need to modify explorer.exe binaries, instead you can follow this [guide](https://stackoverflow.com/questions/20530996/aliases-in-windows-command-prompt) to set an alias for _explorer_ and set it to Files

First you need to include the path where Files.exe is located (C:\Users\NAME\AppData\Local\Microsoft\WindowsApps) to PATH
You create a bat or cmd file (ie Alias.bat) and save it somewhere, here you write:

`@echo off
set PATH=%PATH%;";C:\Users\NAME\AppData\Local\Microsoft\WindowsApps"
doskey explorer=files.exe $*`

Now the bat file creates an "alias" for explorer, but this only last until the cmd window is closed that's less than a second
To make it persistent you need to create a new string keyword in the registry at:

> HKEY_CURRENT_USER\SOFTWARE\Microsoft\Command Processor

with the name **AutoRun** and set the path to the bat file you created.

And that's it!
Now everytime you call explorer.exe form CMD  using arguments it should open Files in the specified folder.

_If you can add this guide somewhere it would be nice_

**Comment by BanCrash** [comment]
> Nevermind I found the solution!
> 
> There's no need to modify explorer.exe binaries, instead you can follow this [guide](https://stackoverflow.com/questions/20530996/aliases-in-windows-command-prompt) to set an alias for _explorer_ and set it to Files
> 
> First you need to include the path where Files.exe is located (C:\Users\NAME\AppData\Local\Microsoft\WindowsApps) to PATH
> You create a bat or cmd file (ie Alias.bat) and save it somewhere, here you write:
> 
> `@echo off`
> `set PATH=%PATH%;"C:\Users\NAME\AppData\Local\Microsoft\WindowsApps"`
> `doskey explorer=files.exe $*`
> 
> Now the bat file creates an "alias" for explorer, but this only last until the cmd window is closed that's less than a second
> To make it persistent you need to create a new string keyword in the registry at:
> 
> > HKEY_CURRENT_USER\SOFTWARE\Microsoft\Command Processor
> 
> with the name **AutoRun** and set the path to the bat file you created.
> 
> And that's it!
> Now everytime you call explorer.exe form CMD using arguments it should open Files in the specified folder.
> 
> _If you can add this guide somewhere it would be nice_

Hello @JotaRata , I tried your solution but It doesn't work for some programs that still launch explorer.exe. How can I unmade those changes? I tried restarting computer, but it doesn't work.

I didn't create the registry key, but the change seems to be permanent.

Regards and thanks.

**Comment by JotaRata** [comment]
> > Nevermind I found the solution!
> > 
> > There's no need to modify explorer.exe binaries, instead you can follow this [guide](https://stackoverflow.com/questions/20530996/aliases-in-windows-command-prompt) to set an alias for _explorer_ and set it to Files
> > 
> > First you need to include the path where Files.exe is located (C:\Users\NAME\AppData\Local\Microsoft\WindowsApps) to PATH
> > You create a bat or cmd file (ie Alias.bat) and save it somewhere, here you write:
> > 
> > `@echo off`
> > `set PATH=%PATH%;"C:\Users\NAME\AppData\Local\Microsoft\WindowsApps"`
> > `doskey explorer=files.exe $*`
> > 
> > Now the bat file creates an "alias" for explorer, but this only last until the cmd window is closed that's less than a second
> > To make it persistent you need to create a new string keyword in the registry at:
> > 
> > > HKEY_CURRENT_USER\SOFTWARE\Microsoft\Command Processor
> > 
> > with the name **AutoRun** and set the path to the bat file you created.
> > 
> > And that's it!
> > Now everytime you call explorer.exe form CMD using arguments it should open Files in the specified folder.
> > 
> > _If you can add this guide somewhere it would be nice_
> 
> Hello @JotaRata , I tried your solution but It doesn't work for some programs that still launch explorer.exe. How can I unmade those changes? I tried restarting computer, but it doesn't work.
> 
> I didn't create the registry key, but the change seems to be permanent.
> 
> Regards and thanks.


It's not permanent, the DOSKEY command is only active for the current session of CMD, if you close it, it's gone.
The AutoRun key In the registry only references the bat file you created, so in order to disable it just remove the file

Now if for some reason you still have explorer mapped to files.exe, just write 

`doskey  explorer=explorer.exe`

**Comment by BanCrash** [comment]
This is so odd, I used your command but even with that still writing explorer.exe on cmd opens files.exe

I used the registry key to make files as default explorator, but I think this doesn't happened before...
