### ISSUE TITLE
The id of a textblock does not match the id that is in string resources

### ISSUE THREAD

**Issue by XPoppyX** [files-community/Files#5134]
The id of textblock "Layout" does not match the id of string resources

**NavigationToolbar.xaml:**
NavToolbar > Layout button > Flyout > Textblock "Layout":

ID: `NavToolbarLayoutMode`

------------

**String resources:**
ID: `NavToolbarLayout.Text` : "**Mode**" is missing

**Comment by yaichenbaum** [comment]
@XPoppyX The correct ID should be`NavToolbarLayout`.

**Comment by XPoppyX** [comment]
ok, I'll open a PR
