### ISSUE TITLE
Feature: Add a widget for network drives

### ISSUE THREAD

**Issue by gus33000** [files-community/Files#5135]
**Is your feature request related to a problem?**
The files app makes it less easy and clear to distinguish between network drives and local drives compared to file explorer. Currently in the stable release network drives get a different icon but does not help much regarding clear separation.

![image](https://user-images.githubusercontent.com/3755345/120858538-3675a780-c583-11eb-89b7-430fc5d99ab2.png)

**Describe the solution**
Windows File explorer clearly separates both types of drives with a section on "This PC". However it also does not do it on the pane. It would be nice for Files to have a sub category on the pane for Network drives, like it is done for Cloud drives.

Here's how File Explorer separates drives in This PC:

![image](https://user-images.githubusercontent.com/3755345/120858670-6624af80-c583-11eb-80e3-bd75ae1ac0d3.png)

Notice the separation isn't present on the side pane either here.

**Describe alternatives you've considered**
An alternative solution to providing another category would be using colors to distinguish the icons better from each other. Classic File Explorer has a green hue primarily on network share drives making it easier to distinguish.

**Scope**

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to distinguish network drives from local drivers more easily | Must |
| This proposal will allow end users to have different categories for network drives than local drives | Should |
| This proposal will allow end users to have different coloring to help distinguish network attached drives from local drives | Could |

**Requirements**
- Added Network Locations widget to the home page
- Add setting to enable/disable (off by default?)
- Stop showing network locations in the drives widget

**System Information**
 - OS Version: Windows 10 Insider Preview [10.0.21382.1 (co_release.210511-1416)]
 - App version: v1.5.0.0

**Additional comment**
N/A

**Comment by esibruti** [comment]
@yair100 Can I try to implement this feature?

**Comment by yair100** [comment]
> @yair100 Can I try to implement this feature?

Absolutely! Good luck 🙂

**Comment by yaichenbaum** [comment]
@gus33000 now that we use colored icons, is this still an issue?

**Comment by gus33000** [comment]
Yes I am afraid it is still an issue. They need to be clearly separated like in explorer.

**Comment by yaichenbaum** [comment]
What do the icons look like?

**Comment by yaira2** [comment]
@gus33000 I changed the title to better reflect the feature request. Do you think the widget sohuld be turned off by default?

**Comment by yaira2** [comment]
The widget header would still be visible

**Comment by yaira2** [comment]
> This pc is also a normal shell location. It should be possible to navigate to it as well and display it with categorization?

Technically you can, but it's slow and not a very good experience.

> the issue was more about this pc and the pane than a widget for home. I think we are diverging from the original intent here, I dont recall talking about widgets

I may have misunderstood the screenshots you were showing in File Explorer, my apologies. I still think we can solve the "This PC" aspect by adding more widgets to the home page and letting you choose which ones to display.

**Comment by gus33000** [comment]
It is a good compromise if we can't implement the real shell location. I wonder however what could be done about the pane, I am lost currently due to the issue being edited a fee times. It is possible another issue overlaps now with this one

**Comment by yaira2** [comment]
@gus33000 in more recent versions of Files, there is a dedicated section for Network drives. I know we're tracking some issues where this isn't working properly but can you confirm if the section is there?
