### ISSUE TITLE
Crash when opening specific path

### ISSUE THREAD

**Issue by MeikelLP** [files-community/Files#5141]
**Explain the bug**
When I try to open my folder at

```
F:\very\obfuscated\path\of\my\dotnet5\app.service\bin\Debug\net5.0
```

The app crashes reproducably. I installed Files for the first time very recently (~1h ago)

This is only happening in the specific project path. Other projects `/bin/` work fine.

For example
```
F:\very\obfuscated\path\of\my\dotnet5\app.api\bin\Debug\net5.0
```

**To reproduce**
???

**Expected behavior**
Should not crash ?

**Logfile**
Sadly the logs do not contain any crash information.
Only multiple
```
2021-06-05 18:40:18.9888|INFO|FilesFullTrust.Program|Argument: GetIconOverlay|
```

I cleaned the files before I reproduced the issue.

**Screenshots**
n.A.

**System Information**
 - OS Version: Windows 10 Pro Version 20H2 - OS build 19042.985 - Windows Feature Experience Pack 120.2212.2020.0
 - App version: 1.5.0.0 (from MS Store)

**Additional comment**
I'd love to give you more info but it seems I can't. Maybe this is a known issue? I didn't find a similar issue.

**Comment by MeikelLP** [comment]
Sadly I have to state that the issue is no longer reproducable. It took me about ~10min to write this issue so maybe this is some caching issue? I very often opened/cleaned that folder...

**Comment by gave92** [comment]
Thanks for this report.
- Could you upload the debug files (there are two of them) anyway?
- When the app crashed did you get a notification saying "something went wrong"?
- Where you using the "Details" layout mode or Tiles/Grid?

I'm closing this issue for now, if you can replicate it again we'll reopen this. In the meantime I'm posting below 2 workarounds that were found for similar issues.

Workaround 1:

1. Turn Off "Enable individual preferences for individual directories" in Settings > Files and Folders
2. Set Tiles or GridView layout mode
3. Try to trigger the crash

-------------------------------------

Workaround 2:

1. Disable these two settings (turn off caching) under Experimental

![image](https://user-images.githubusercontent.com/9673091/110851026-ce2f6680-82b0-11eb-8974-599e144ff399.png)
