### ISSUE TITLE
Drag & Drop to extract compressed file

### ISSUE THREAD

**Issue by itsmehoaq** [files-community/Files#5145]
Not so sure if this is just on my end or not, but currently drag and drop to extract compressed file using 7-Zip is impossible.

**Comment by gave92** [comment]
Thanks for this report. It works for me, could you upload here the two debug files and add the Files version to the description?

**Comment by itsmehoaq** [comment]
[debug.txt](https://github.com/files-community/Files/files/6603891/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6603892/debug_fulltrust.txt)
Files version: 1.5.0.0

**Comment by gave92** [comment]
A few more info :)
- Could you delete the two log files, try to drag&drop from 7zip and upload the new log files?
- Any difference if you try to drag&drop a folder or a single file from 7zip to Files?
- When you drag something from 7zip over Files does a semitransparent window appear saying "Drop here"?
- Does it work if you drag&drop from a zip opened in explorer?
- Could you share a screenshot of the right-click context menu that appears in Files before and after you try to drig&drop?

Thanks for the help.

**Comment by itsmehoaq** [comment]
Here are the 2 new log files.
[debug.txt](https://github.com/files-community/Files/files/6603918/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6603919/debug_fulltrust.txt)

For the questions:
- Either single file or whole folder produces the same error
- When dragging the file into Files window, there is an overlay saying "Drop here"
- If the zip is opened using Files Explorer, the overlay will not appear and the cursor showing not-allowed action. 

And I also should point out that if the compressed file is opened within Files, then the drag & drop will actually works fine. But if I open the zip from other software (IDM or a browser for example) then the operation would fail.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5273.
