### ISSUE TITLE
Can not load Google Drive

### ISSUE THREAD

**Issue by laksa19** [files-community/Files#5146]
![image](https://user-images.githubusercontent.com/16347475/120914603-6929b800-c6c9-11eb-9a8b-02f00db29851.png)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6603729/debug_fulltrust.txt)

**Comment by gave92** [comment]
Could you try to turn on the option to show hidden files and turn _off_ the option to hide system and protected files?

**Comment by gave92** [comment]
Merging with #5050
