### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by akset045** [files-community/Files#5147]
The app crashes when I open tabs on both SSD and HDD at the same time. And don't work hotkeys for switch tabs (Ctrt + Tab), but Ctrl +1, Ctrl + 2 and ect. is OK.

Maybe you can find some useful. Tnx.

System:

Windows 10 Pro 64 bit
Version 20H2
OS build	19042.985

[debug.txt](https://github.com/files-community/Files/files/6603930/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6603931/debug_fulltrust.txt)

**Comment by yaichenbaum** [comment]
@akset045 Is this still an issue in `main`?

**Comment by akset045** [comment]
@yair100, only with switching tabs. Other stuff are not terrible.

**Comment by yaichenbaum** [comment]
@akset045 What version of Files did you test with?

**Comment by akset045** [comment]
@yair100 1.5.0.0.

**Comment by yaichenbaum** [comment]
These issues appear to be resolved in `main`. Let us know if it's still an issue once v2 rolls out.

**Comment by akset045** [comment]
@yair100 ok.
