### ISSUE TITLE
Come back using folder name in the nav/url bar is confusing

### ISSUE THREAD

**Issue by Neikon** [files-community/Files#5148]
**Explain the bug**
Come back using folder name in the nav/url bar is confusing. I thought the program was getting stuck when I wanted to go back to a previous folder. Because no matter how many times I clicked on the program it didn't respond when I realised that although the whole section was illuminated when you put the mouse over it, if you click on it nothing happens unless you are over the text.

**To reproduce**
1. go to "C:\Windows\System\Speech" for example
2.  If you want to go back to system you can click here, Right?
3. 
![imagen](https://user-images.githubusercontent.com/1765319/120933787-f7b72d00-c6fb-11eb-830a-f4ce78baaaaa.png)
4. But that only works if you click in the text, no all highlight 
![imagen](https://user-images.githubusercontent.com/1765319/120933818-377e1480-c6fc-11eb-838e-abf5f0f71bd2.png)

**Expected behavior**
You should be able to click on the entire highlighted area to navigate to that folder. Not just the text
![imagen](https://user-images.githubusercontent.com/1765319/120933922-93489d80-c6fc-11eb-99d2-924c4eff70c1.png)

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6604582/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6604583/debug_fulltrust.txt)

**Screenshots**
Highlitghted Zone
![imagen](https://user-images.githubusercontent.com/1765319/120934068-271a6980-c6fd-11eb-9e10-9e37514582f5.png)
Clickable Zone
![imagen](https://user-images.githubusercontent.com/1765319/120934108-4b764600-c6fd-11eb-8bad-5d86ce34bda8.png)

**System Information**
 - OS Version: Edición	Windows 10 Pro
Versión	21H1
Instalado el	‎18/‎12/‎2020
Compilación del sistema operativo	19043.985
Experiencia	Windows Feature Experience Pack 120.2212.2020.0

 - App version: 1.5
**Additional comment**
Thank you all for making this wonderful application

**Comment by gave92** [comment]
Merging with #4879
