### ISSUE TITLE
Always crash when file list is loading

### ISSUE THREAD

**Issue by richwxd** [files-community/Files#5154]
**Explain the bug**
Write a clear description of what the bug is.
Event for a folder with 3 files, but rarely opened recently, when open this folder, a gauge was shown, if do another operation such as click other drive at the same time, the "Files" crashed and disapeard. After open this program twice, it works.

**To reproduce**
1. Go to '....'
4. See the error

**Expected behavior**
Write a clear description of what you expected.

**Logfile**
Upload the log file here for us to understand your issue better. 
- You can access it from Settings->About->Open log location. 
or 
- Copy the debug.log and debug_fulltrust.log from the following directory, and upload the files here.
`%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 

**Screenshots**
Add screenshots to help explain your problem if needed.

**System Information**
 - OS Version: [e.g. Windows 10 20H2 19042.804] (Press WIN + PAUSE/BREAK, use the copy button at the bottom)
 - App version: [e.g. v1.0] (In the app, go to Settings -> About, the version is shown at the top)

**Additional comment**
Add any other comment about the problem here. Does this problem happen again after restarting the app?

**Comment by f-x1-1** [comment]
[debug.txt](https://github.com/files-community/Files/files/6609931/debug.txt)



https://user-images.githubusercontent.com/77340515/121038788-779ad100-c7a8-11eb-979a-50677d8fa511.mp4

As you can see It in the video above keeps crashes

**Comment by gave92** [comment]
Could you try the following?

1. Turn Off "Enable individual preferences for individual directories" in Settings > Files and Folders
2. _Set Tiles or GridView layout mode
3. See if it's still crashing

Also disable these two settings (turn off caching) under Experimental:

![image](https://user-images.githubusercontent.com/9673091/110851026-ce2f6680-82b0-11eb-8974-599e144ff399.png)

**Comment by f-x1-1** [comment]
> Could you try the following?
> 
> 1. Turn Off "Enable individual preferences for individual directories" in Settings > Files and Folders
> 2. Set Tiles or GridView layout mode
> 3. See if it's still crashing
> 
> Also disable these two settings (turn off caching) under Experimental:
> 
> ![image](https://user-images.githubusercontent.com/9673091/110851026-ce2f6680-82b0-11eb-8974-599e144ff399.png)

It worked! Thank you so much!

**Comment by gave92** [comment]
Thanks for confirming, this issue is fixed in latest code.
