### ISSUE TITLE
TextZone too small for text in settings

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#5159]
**Explain the bug**
The language change confirmation popup displays unreadable text. 

**To reproduce**
Open settings, tab Preferences
Choose a another lang

**Expected behavior**
Larger text box

**Screenshots**
![lang](https://user-images.githubusercontent.com/46631671/121084888-78038e00-c7e1-11eb-9022-1a5da603ab11.png)

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
