### ISSUE TITLE
Closing Properties crashes Files

### ISSUE THREAD

**Issue by Beniplay** [files-community/Files#5161]
**Explain the bug**
I did a backup of my android phone on an USB flash drive (64GB, exFAT). When I closed the properties of my backup folder, the application crashed. After a few tries, I recognized it, that it will not happen all the time.

**To reproduce**
1. Go to the flash drive
2. Right-Click on a folder 
3. Open "Properties"
4. Close "Properties" (OK or CANCEL)
5. Files will (sometimes) crash

**Expected behavior**
I expected, that the programm will behave as normal. That means it should close the properties-window without any problems or crashes.

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6616759/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6616760/debug_fulltrust.txt)
Timestamp from debug.txt: 2021-06-08 15:15:21.3049 (I opened 2 times the properties window befor it crashed)

**Screenshots**
No Screenshots

**System Information**
 - OS Version: 
 - Edition Windows 10 Pro
 - Version	20H2
 - Betriebssystembuild	19042.985
 - Leistung	Windows Feature Experience Pack 120.2212.2020.0

 - App version: 1.5.0.0

**Additional comment**
The problem happens only when you open the properties-window of a folder. A restart of the programm does not help. When I close the dialog, my mouse gets a windows waiting circle until i move the cursor. The crash also comes, when you close a properties-window of a folder of a drive. With a bigger folder, the problem appears more often.

**Comment by gave92** [comment]
Thanks for the report. Merging with #2714.
