### ISSUE TITLE
Software crash when quit Desktop property popup with the 'ok' button

### ISSUE THREAD

**Issue by BaptisteDyrt** [files-community/Files#5162]
**Bug desciption**
When you go to your files manager and try to see property for a file or a folder, the popup comes,
but when you want to kick it away when clicking on the ''OK'' button, the files manager crash and close himself.

**To reproduce**
1. Right click on Desktop
2. Click on property
3. Click on ''OK'' button
4. See the error

**Expected behavior**
The files manager should be close the popup and not close himself.

**Logfile**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6617685/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6617686/debug.txt)

**System Information**
 - OS Version: [e.g. Windows 10 20H2 19042.804]
 - App version: [e.g. v1.5.0.0]

**Comment by gave92** [comment]
Thanks for this report. Probably same as #2714.
Does it happen all the times? Or is it random?

**Comment by gave92** [comment]
Thanks it's the usual issue then.
