### ISSUE TITLE
Remove experimental setting to show file owner in properties dialog

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#5163]
With the recent addition of the security tab, this setting is no longer needed.

**Comment by gave92** [comment]
Even when we move the owner to the advanced properties page?

**Comment by yaichenbaum** [comment]
> Even when we move the owner to the advanced properties page? Why is that an optional setting by the way?

The setting was to show it on one of the existing tabs, the reason it was optional was because it didn't really fit on that page, it was only there because we didn't have the security tab at the time.
Perhaps we can keep the owner on both the regular security tab in addition to the advanced options.

**Comment by gave92** [comment]
For files there's also the possibility of showing it in the Details tab (like explorer) maybe

**Comment by yaichenbaum** [comment]
@gave92 Absolutely, but even then, this setting isn't needed anymore, that behavior should be the default.

**Comment by gave92** [comment]
@yaichenbaum agreed 👍 BUT WE NEED SOME COOL NEW SETTING FOR THE EXPERIMENTAL TAB (lol)

**Comment by yaichenbaum** [comment]
@gave92 We will come up with something before v2 😂
