### ISSUE TITLE
Force close on opening OneDrive folder

### ISSUE THREAD

**Issue by gavinayling** [files-community/Files#5165]
**Explain the bug**
When opening OneDrive locations, Files will occasionally crash with an error about a thread already being in use.

**To reproduce**
1. Navigate to a Cloud location that is OneDrive
2. Occasionally find that Files has closed.

**Expected behavior**
Folders displayed in the Files window that can be interacted with.
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6617986/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6617987/debug.txt)

**Logfile**
Upload the log file here for us to understand your issue better. 
- You can access it from Settings->About->Open log location. 
or 
- Copy the debug.log and debug_fulltrust.log from the following directory, and upload the files here.
`%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 

**System Information**
 - OS Version: 10.0.19042 Build 19042
 - App version: 1.5.0.0

**Additional comment**
This does not always happen.

**Comment by gave92** [comment]
Thanks for this report. Could you try the following?
1. Turn Off "Enable individual preferences for individual directories" in Settings > Files and Folders
2. Set Tiles or GridView layout mode
3. See if it's still crashing

**Comment by gave92** [comment]
I believe this is fixed in main

**Comment by gavinayling** [comment]
The folder does not crash with those settings.

________________________________

**Comment by gavinayling** [comment]
I downloaded the Windows store version and it is no longer crashing.

________________________________

**Comment by gave92** [comment]
Thanks for confirming!
