### ISSUE TITLE
Error while installing via Msixbundle

### ISSUE THREAD

**Issue by SKProCH** [files-community/Files#5171]
**Explain the bug**
I've downloaded Files-1.5.Msixbundle (Files.Package.appinstaller causes this too) from Releases and try to open it. And after that i get a crush dialog:
```
File system error (-2147219195).
```

**To reproduce**
1. Download installer
2. Run
3. See the error

**Expected behavior**
The program should install / run

**Logfile**
I've have no log files

**Screenshots**
![image](https://user-images.githubusercontent.com/29896317/121497166-d39d6980-c9e3-11eb-924a-ad3d803dff20.png)

**System Information**
 - OS Version: 
Edition	Windows 10 Pro
Version	20H2
Installed on	‎09.‎05.‎2021
OS build	19042.867
Experience	Windows Feature Experience Pack 120.2212.551.0

 - App version: Seems like 1.5

**Comment by yaichenbaum** [comment]
@SKProCH By any chance, did you remove the Microsoft Store from your system?

**Comment by SKProCH** [comment]
@yair100 Yes, I turned it off. Does the installer of the program have to be tied to the MS Store?

**Comment by yaichenbaum** [comment]
@SKProCH No, it's likely that removing the Store removed AppInstaller as well. It's pretty simple to [restore](https://yairai.medium.com/how-to-restore-windows-10-app-installer-99c15b7c3ec4) it though. Let me know if those instructions work for you.

**Comment by SKProCH** [comment]
Yes, this worked for me. Thanks!
