### ISSUE TITLE
Add tooltips

### ISSUE THREAD

**Issue by StLa1** [files-community/Files#5172]
Some features are not self-explanatory or standard (ex: Bundles). It would be good practice to add a help icon (for instance on the left of the ... icon) that displays a tooltip when clicked

**Comment by yaichenbaum** [comment]
@StLa1 Which options are missing tooltips?

**Comment by stanlrt** [comment]
@yair100 So far Bundles is the only unexplanatory feature I found. I also didn't find any documentation about it on the github.io

**Comment by yair100** [comment]
> @yair100 So far Bundles is the only unexplanatory feature I found. I also didn't find any documentation about it on the github.io

@StLa1 thanks for your feedback.
