### ISSUE TITLE
Great application, I have some suggestions & issues

### ISSUE THREAD

**Issue by REVENGE977** [files-community/Files#5177]
### **Suggestions**
1- we need the ability to set default application for the file extension in properties.
2- files listing in the left panel like this concept, [Source](https://github.com/files-community/Files/issues/777)

![image](https://user-images.githubusercontent.com/32039975/121619722-b3b48700-ca71-11eb-99b6-2922a38fc67f.png)

3- we need a replace all button when pasting files already exist like the normal file explorer.
4- in the default file explorer when I sort files/folders by name first comes the folders and then the files but in files,
it's not, so I do love to get the option to get the same in files too.

### **Issues**
one issue actually,
when I right click on any file/folder and click on properties and I close the properties tab immediately the app gets crashed..

_**English is not my native language..**_
**And in the end I want to thank everyone worked on this application 😀.**

**Comment by yaichenbaum** [comment]
1. https://files-community.github.io/docs/#/articles/replace-file-explorer.
2. We don't have plans for a tree view in the sidebar, however, you can subscribe to the feature request for a tree view layout #1928.
3. This was implemented in `main` and will be available with v2.
4. Do you have the option to list and sort directories with files turned on? It sounds like this could be why you see the wrong behavior.

Thank you for all your feedback!

**Comment by REVENGE977** [comment]
in the first suggestions i didnt mean to replace the default file explorer
i meant a button like this button in the file explorer properties tab
![image](https://user-images.githubusercontent.com/32039975/121621273-8917fd80-ca74-11eb-8ed2-bd0de711618c.png)

**Comment by REVENGE977** [comment]
and yes i have this option turned on
![image](https://user-images.githubusercontent.com/32039975/121621414-c8dee500-ca74-11eb-8e1b-e2790f685222.png)

**Comment by REVENGE977** [comment]
> when I right click on any file/folder and click on properties and I close the properties tab immediately the app gets crashed..
it seems this problem only happens when i have this option in experimental turned on 

![image](https://user-images.githubusercontent.com/32039975/121621732-6b976380-ca75-11eb-951c-e1a6f6576895.png)

**Comment by yaichenbaum** [comment]
> in the first suggestions i didnt mean to replace the default file explorer
> i meant a button like this button in the file explorer properties tab
> ![image](https://user-images.githubusercontent.com/32039975/121621273-8917fd80-ca74-11eb-8ed2-bd0de711618c.png)

I misread that, we are working on this option 🙂 

> it seems this problem only happens when i have this option in experimental turned on

This setting is being removed in v2 so it will longer be an issue.

**Comment by yair100** [comment]
@REVENGE977 Tree View is currently available in preview https://files.community/download. It will be included in the next stable release.
