### ISSUE TITLE
pCloud Drive causes problems

### ISSUE THREAD

**Issue by BitTim** [files-community/Files#5181]
**Explain the bug**
Having pCloud Drive installed leads to unexpected behaviour, which includes:
- Disappearance of the "Cloud storage" Group in the sidebar (As seen in screenshot)
- Freeze of app, when right clicking any folder or file, which is not listed in the sidebar
- Icons of files not loading
- QuickLook not working
- Possibly other issues I have not tested

**To reproduce**
1. Open Files without pCloud Drive installed, to see everything listed above works fine
2. Install and start pCloud Drive
3. Restart Files
4. Try everything listed above, which results in described unexpected behaviour

**Expected behavior**
- "Cloud storage" section should not disappear
- App should not freeze, when trying to open a context menu
- Icons should load
- QuickLook should work normally

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6638869/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6638871/debug_fulltrust.txt)

**Screenshots**
Before pCloud installation (Left) - After pCloud installation (Right)
![Before pCloud installation](https://user-images.githubusercontent.com/43250787/121697277-2ef75680-cacd-11eb-8e01-5c826ecdcf80.png)![After pCloud installation](https://user-images.githubusercontent.com/43250787/121697272-2e5ec000-cacd-11eb-89cf-85b568ca421e.png)

**System Information**
 - OS Version: Windows 10 Home 21H1 (Build 19043.1052)
 - App version: 1.5.0.0

**Additional comment**
- I am aware, that I have listed more than one issue in this bug report, but I wanted to give an idea as to why some bugs from other users might happen, since I did not suspect that it was pCloud Drive at first. I am not dependant on pCloud Drive and this should not be treated as an issue with high priority, this report was created with the intention of raising awareness about problems caused by pCloud drive.
- I am german, which is why I am running Windows in german. One problematic thing with this would be that some statements in the log file appear to be also in german, to which I apologize and hope that you can still understand them

**Comment by gave92** [comment]
Thanks a lot for this report. All these issues actually have a common cause which has been fixed in latest code. I'm closing this now, if you still have this issue when Files v2 is published please let us know,
In the meantime the workaround is to change pCloud settings to not add its items to explorer's context menu
