### ISSUE TITLE
Box doesn't list all files and folders

### ISSUE THREAD

**Issue by sdel85** [files-community/Files#5182]
Box is listed under the cloud drive section, but selecting it only shows a single folder. The other files and folders don't exist.

**To reproduce**
1. Go to 'Cloud Drive section'
2. Click on 'Click on Box'
3. Only the folder 'Absolute' appears in the right pane
4. See the error

**Expected behavior**
I would expect all the folders and files in Box to appear in the right-pane

**Logfile**
There is no debug.log or debug_fulltrust.log in the location specified, only a debug.txt which has been uploaded.

**Screenshots**
Add screenshots to help explain your problem if needed.

**System Information**
 - OS Version: [e.g. Windows 10 1903 18362.1256] 
[debug.txt](https://github.com/files-community/Files/files/6639193/debug.txt)
![Files Screenshot_2021-06-11](https://user-images.githubusercontent.com/25733278/121703822-cee6bd00-ca98-11eb-96a7-6583a6ba61b0.png)
![Explorer Screenshot_2021-06-11](https://user-images.githubusercontent.com/25733278/121703837-d27a4400-ca98-11eb-9e73-166cd6b8577f.png)

 - App version: [1.5.0.0]

**Additional comment**
Problem is repeatable and happens after the app is restarted as well as after a system reboot.

**Comment by gave92** [comment]
Thanks for this report. This issue has been fixed in the latest code. The fix will ship with the next Files version.
