### ISSUE TITLE
Collapse sidebar shortcut

### ISSUE THREAD

**Issue by Rasmagoric** [files-community/Files#5184]
Currently there is no shortcut to collapse the sidebar.

I purpose either **ctrl + B** because it's used in visual studio code to also collapse sidebar, and in firefox it shows the bookmarks sidebar.
Or **f10**, because the F11 shortcut is to toggle fullscreen, and you would have those two shortcuts near each other that have a similar function to expand or contract the interface.

**Comment by R3voA3** [comment]
I'd prefer CTRL+B. Function keys are always hard to reach.

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
