### ISSUE TITLE
It would be great if we could make the list of files more compact. In the default file explorer of windows you can view more items without having to scroll, Im saying Files should give us the option to have more items visible without having to scroll just like in the default file explorer

### ISSUE THREAD

**Issue by AUsername12121212** [files-community/Files#5185]
**Is your feature request related to a problem?**
A clear description of what the problem is.

**Describe the solution**
A clear description of what you want.

**Describe alternatives you've considered**
A clear description of any alternative solutions or features you've considered.

**Scope**

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**System Information**
 - OS Version: [e.g. Windows 10 20H2 19042.804] (Press WIN + PAUSE/BREAK, use the copy button at the bottom)
 - App version: [e.g. v1.0] (In the app, go to Settings -> About, the version is shown at the top)

**Additional comment**
Add any other comment or screenshots about the feature request here. What device type/UI layout and app version?

**Comment by specterflare** [comment]
A couple of things here:

1. You put the issue description in the title. Your title should be something concise, like "Please add more compact viewing options", and you would put your current title in the main body, which leads to...

2. You didn't fill out any part of the issue template. If you want your request to be taken seriously, you should do as the maintainers ask and give them the information they request, which in this case includes your OS and Files version, as well as further descriptions of what you are envisions. Furthermore...

3. Files already has what you are asking for. Simply navigate to any folder, and either right-click and select "Layout mode" or click on the Display options button in the top right corner (the one with three boxes). From either of those, you can select your new layout view, which includes several compact options.

**Comment by winston-de** [comment]
Thanks for the feedback, merging with #1940.
