### ISSUE TITLE
Option to disable all animations

### ISSUE THREAD

**Issue by ImportTaste** [files-community/Files#5186]
* When going to or leaving Settings, I don't want to see a swipe transition.
* When clicking on categories within settings, I don't want to see the text on the right rise into position.
* ~~When resizing the window or collapsing the sidebar, I don't want to see the files slide into new positions.~~
* ~~When clicking dropdowns, I don't want to see the contents fall into place.~~

Smooth scrolling is an exception, I like that, though some people might not. A separate option for disabling smooth scrolling would be good.

**Comment by mdtauk** [comment]
There is a windows setting to disable animation, I don't think you need do more than respect that setting.  The in-built controls do so, but does the app need to handle this itself for some things?

**Comment by ImportTaste** [comment]
> There is a windows setting to disable animation, I don't think you need do more than respect that setting. The in-built controls do so, but does the app need to handle this itself for some things?

Huh, I didn't know there was a setting for that (I don't use the new fluent scheme often outside of Settings).

Enabling it makes everything but these go away:
* When resizing the window or collapsing the sidebar, I don't want to see the files slide into new positions.
* When clicking dropdowns, I don't want to see the contents fall into place.

Smooth scrolling is also unaffected.

**Comment by yaichenbaum** [comment]
> When going to or leaving Settings, I don't want to see a swipe transition.

The settings page has been redesigned and is now a dialog so there is no longer a transition.

> When clicking on categories within settings, I don't want to see the text on the right rise into position.

Can you explain this issue so we can investigate?

**Comment by ImportTaste** [comment]
> Can you explain this issue so we can investigate?

![2021-06-14;16-13-53](https://user-images.githubusercontent.com/53661808/121960427-afb38e00-cd2b-11eb-88be-23c8e8abc8c1.gif)

**Comment by yaichenbaum** [comment]
@ImportTaste did the built-in setting to disable animations in Windows 10 work?

**Comment by ImportTaste** [comment]
> @ImportTaste did the built-in setting to disable animations in Windows 10 work?

Yes, this is one of the animations that is disabled by disabling that. Although I'm not sure if this animation is even intentional, because this doesn't happen when you go to different subcategories in Windows Settings.

**Comment by yaichenbaum** [comment]
The animations in Files were done a little differently than the Windows 10 settings app. Either way, you can disable it using the setting mentioned above.
