### ISSUE TITLE
Fluent Terminal launching behind the Files on window version `21H1`, same issue #986

### ISSUE THREAD

**Issue by dim0147** [files-community/Files#5190]
Hi, I'm using window version `21H1`, install through `Microsoft Store` which current version `1.5` but have this issue, I test when open other files like `mp3` or `txt` the application is working fine, it launching in front but when right-click and choose `Open In Terminal` the `Fluent Terminal` is behind `Files`.
- Test with mp3 is fine:
![image](https://user-images.githubusercontent.com/44487221/121779970-ca252480-cbd0-11eb-8b6b-dda633be7cf8.png)
- But when `Open In Terminal`:
![image](https://user-images.githubusercontent.com/44487221/121780023-fc368680-cbd0-11eb-9066-654da40eedbb.png)

**Comment by gave92** [comment]
Thanks for this report. This issue is expected to be already fixed in main (to be verified) -> #5009
