### ISSUE TITLE
Cant Open Files

### ISSUE THREAD

**Issue by SQO21Dev** [files-community/Files#5193]
**Explain the bug**
Can´t open the program

**To reproduce**
1. Download the App
2. Try to open the app
3. Do not open 

**Expected behavior**
I expected that i can open the program.

**Logfile**
Does not generate any files

**Screenshots**
I do not have screenshots because it does not open

**System Information**
 - OS Version: 21H1 19043.1052
 - App version: 1.5.0.0

**Additional comment**
Any aditional comments

**Comment by gave92** [comment]
Where have you installed the app from? The Windows Store? Also #4977, #4684

**Comment by StLa1** [comment]
Same issue. Stopped working a few minutes ago.

**Comment by StLa1** [comment]
> Thanks for the report. Where have you installed the app from? The Windows Store? Also #4977, #4684

Those aren't the same issue. We can use FIles. But we can't open any file, only folders. The handler icon (ex: browser for pdfs, Photos for pngs) won't show. QuickLook is able to open the preview properly.

**Comment by StLa1** [comment]
.txt seem to work. Here are my logs. 
[debug.txt](https://github.com/files-community/Files/files/6649590/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6649591/debug_fulltrust.txt)
