### ISSUE TITLE
Right click expanded menu as not arrow

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5202]
**Explain the bug**
when using the right click menu there's no way of know if a item can be expanded since there's no arrow

**Expected behaviour**
for expandable items an arrow should be present.

**Screenshots**
![image](https://user-images.githubusercontent.com/26977075/121820157-20ee3500-cc89-11eb-9bdf-e2020aed4a82.png)

**System Information**
 - OS Version: Windows 10 21H1 19042.1055
 - App version: v1.5.32

**Comment by yaichenbaum** [comment]
@josh-65 This isn't specific to Files. Can you open an issue in the WinUI repo?

**Comment by josh-65** [comment]
sure

**Comment by josh-65** [comment]
they seem to have multiple witch one is it

**Comment by yaichenbaum** [comment]
https://github.com/microsoft/microsoft-ui-xaml

**Comment by josh-65** [comment]
According to them it does work see link above

**Comment by mdtauk** [comment]
![image](https://user-images.githubusercontent.com/7389110/121820998-d4f1bf00-cc8d-11eb-95c7-53090a161238.png)
Works fine with WinUI 2.6 right now

**Comment by winston-de** [comment]
> ![image](https://user-images.githubusercontent.com/7389110/121820998-d4f1bf00-cc8d-11eb-95c7-53090a161238.png)
> Works fine with WinUI 2.6 right now

@mdtauk That's a ``MenuFlyout``, this is an issue with the ``CommandBarFlyout`` (which is what Files uses for right click menus).

**Comment by mdtauk** [comment]
If it was a problem, it is likely to be fixed now
![image](https://user-images.githubusercontent.com/7389110/121821279-f784d780-cc8f-11eb-87b1-82a4f761cace.png)
