### ISSUE TITLE
Added security options to drive properties 

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5204]
**Explain the bug**
Right clicking a drive and going to properties doesn't show a security tab

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6644552/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6644553/debug_fulltrust.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/26977075/121820494-f4d3b380-cc8a-11eb-902a-67c7dd8cf838.png)

**System Information**
- OS Version: Windows 10 21H1 19042.1055
- App version: v1.5.32

**Comment by yaichenbaum** [comment]
@josh-65 Good catch!

**Comment by yaichenbaum** [comment]
This issue should be addressed with #5189.
