### ISSUE TITLE
New details view expands way past tab area

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5205]
**Explain the bug**
The selection of a folder/file goes beyond the tabs were the type of information is.

**Logs**
[debug.log](https://github.com/files-community/Files/files/6644569/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6644570/debug_fulltrust.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/26977075/121820889-1766cc00-cc8d-11eb-9f3e-4374202a2089.png)

**System Information**
 - OS Version: Windows 10 21H1 19042.1055
 - App version: v1.5.32

**Comment by yaichenbaum** [comment]
@josh-65 I'm having a hard time understanding this issue, can you explain and add steps to repro this?

**Comment by gave92** [comment]
That we should add empty space to the right of the last column instead of stretching -> already included in #4643

**Comment by josh-65** [comment]
The highlight/selection of a file and folder should not go pass the green line as that's were the tabs end (or if preferred max width of the window) but it end up extending pass the screens width and created a scroll bar too.
![image](https://user-images.githubusercontent.com/26977075/121821529-8514f700-cc91-11eb-9f0c-f99058ed5f00.png)

**Comment by josh-65** [comment]
that might be it seem i also mention it in that issue and forgot. il update my comment on that one.
