### ISSUE TITLE
Crash After Double Clicking a Directory 

### ISSUE THREAD

**Issue by KieferLao** [files-community/Files#5210]
**Explain the bug**
When using files on my Zephyrus G14, the app always seems to crash without fail after double clicking on a directory with more than 2 folders/contents inside. After double clicking, the app will show the loading bar and then crash. Sometimes the app just freezes then crashes.

What's strange is, after turning on the option to open items with a single click, the app runs amazingly well and does not crash. Crashes only occur when I double click. I have a desktop that also has files however there seems to be no issue there when I double click on folder. It only occurs on my laptop.

**To reproduce**
1. Open Files App
2. Open  a system directory such as C: or D:
3. Open (Using double click) a folder such as Program Files or Windows (Any folder with more that 2 sub folders)
4. Crash

**Expected behavior**
I expect that the folders regardless of the contents would be loaded without crashing.

**Log File**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6645154/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6645155/debug.txt)

**Screenshots**
Not Applicable

**System Information**
 - OS Version: Windows 10 21H1 19043.1052
 - App version: v1.5.0.0

**Additional comment**
Only happens on my laptop and not my desktop

**Comment by gave92** [comment]
This issue should be fixed in latest code. To verify this is the same issue could you try to turn Off "Enable individual preferences for individual directories" in Settings > Files and Folders and see if it still crashes?

**Comment by KieferLao** [comment]
Thanks! Workaround 1 seemed to have fixed the issue. Glad to know that a fix is coming! Thanks so much

**Comment by gave92** [comment]
Glad it works.

For workaround 1 you may be able to set also Details view as layout (I'm not sure), the only limitation is that all folders will use the same layout mode.

**Comment by KieferLao** [comment]
I tried using details view and that's what I think is causing the crashing, I tried turning off the options on workaround 2 as well but with details view on, the whole program still crashes. As of right now I don't mind using other layout modes though!
