### ISSUE TITLE
Navigation list in new Settings dialog is too narrow

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#5215]
![image](https://user-images.githubusercontent.com/17484252/121850907-c0ddaa00-cced-11eb-8f3e-6b958cc9e954.png)

Long localisations are cut off.

**Comment by yaichenbaum** [comment]
@R3voA3 Do the names show in a tooltip when you hover the mouse over the options? Also, how much more space do you think is needed to fit them all?

**Comment by R3voA3** [comment]
![image](https://user-images.githubusercontent.com/17484252/121895011-10d56480-cd20-11eb-8755-c6dc7349a69d.png)

**Comment by yaichenbaum** [comment]
Thanks again for your feedback.

_Since we didn't hear from you on this topic for 3+ days, we'll assume everything is worked out and close this feedback item. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this._

**Comment by R3voA3** [comment]
What more is there to provide? The nav list is still too narrow. The screenshot and the red lines above indicate how wide it has to be to make it work at least for the German localisation.

**Comment by yaichenbaum** [comment]
@R3voA3 is this still an issue?

**Comment by R3voA3** [comment]
Yeah, overall it feels cramped and the text is still cut off.

**Comment by yaichenbaum** [comment]
This issue should be resolve in `main`.
