### ISSUE TITLE
Drive Widget: Parts of the content are cut off 

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#5216]
![Screenshot 2021-06-14 090243](https://user-images.githubusercontent.com/17484252/121852539-ec619400-ccef-11eb-92e4-c5423de58eef.png)

This seems to be causes by having an increased text size set for windows. I'd recommend to move the text a bit closer to the progress bar.

**Comment by yaichenbaum** [comment]
@R3voA3 What do you have your scaling set to?

**Comment by R3voA3** [comment]
UI Scaling on my Surface is 175% (which does not affect this issue).
My text size was very slightly increase. (There doesn't seem to be an actual value. The slider in the settings was probably moved by a mm.

**Comment by yaichenbaum** [comment]
Oh, if you changed the text size, I'm sure we can support that without messing up the regular sizes 🤔.

**Comment by R3voA3** [comment]
I think in this case there is still room for improvements since the there is quite a bit of vertical space wasted between the text and the progress bar.

**Comment by yaichenbaum** [comment]
I'll have to double check, but I believe the rows have the exact height for the progress bar.

**Comment by duke7553** [comment]
@R3voA3 Thank you for creating this feedback item. A solution for it is currently being reviewed as a PR (pull request) to our active development branch. We'll let you know once it's merged by closing this issue.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5272.
