### ISSUE TITLE
Date grouping mixed with last year files

### ISSUE THREAD

**Issue by IniGisah** [files-community/Files#5217]
**Explain the bug**
When enabling Date grouping (Date Modified and Date Created), grouped files and folder is mixed with last year date modified.

**To reproduce**
1. Go to a folder with older files
2. Click on Sort and Group By Date Modified
3. All the grouped items mixed with last year date items

**Expected behavior**
Items grouped normally with today and yesterday date 

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6646397/debug.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/38863379/121855353-6f4d1380-cd1d-11eb-8a52-2999bfd00845.png)

**System Information**
 - OS Version: Windows 10 21H1 19043.1055
 - App version: Build from `main` branch from 0f53a4241323f64ccaf66d6c0e281a09349e411c commit

**Comment by winston-de** [comment]
Thanks for reporting this, does this issue persist after manually refreshing?

**Comment by IniGisah** [comment]
> Thanks for reporting this, does this issue persist after manually refreshing?

Yes, it's still shows the bug

**Comment by SHADOW-XIII** [comment]
I was about to report same issue but I see already here. Had a look at the code and I think I have a good enough fix (only checked Today and Yesterday grouping, I don't see issues with older groups)
The PR seems stuck (my first fix here not 100% sure what to do with it) but hopefully someone can review it or help me with it ;)

**Comment by yaichenbaum** [comment]
@IniGisah this issue should be resolved with #6134.
