### ISSUE TITLE
How would I run this on Windows 7?

### ISSUE THREAD

**Issue by Joe23232** [files-community/Files#5220]
I understand that Windows 7 does not support universal apps but is there a way to get this to run on Windows 7?

**Comment by gave92** [comment]
Thanks for opening this issue, Files relies on APIs and features that are only available on Windows 10. We don't plan on backporting Files to Windows 7, sorry.

**Comment by Joe23232** [comment]
Hi thanks for your response @gave92 :)

So I understand you guys won't be porting it over to Windows 7, but is there a third party software which allows windows 10 applications to run on Windows 7?

**Comment by gave92** [comment]
To my knowledge, no.

**Comment by Joe23232** [comment]
Thanks anyways
