### ISSUE TITLE
Allow going back to the new tap page in the current tab

### ISSUE THREAD

**Issue by blacklightpy** [files-community/Files#5222]
**Is your feature request related to a problem?**
Cannot go back to homepage in a tab

**Describe the solution**
Create a home button to quickly go back to the new tab homepage. Additionally, create a new tab section before drive letters so I can directly click the address bar and go back to the new tab.

**Describe alternatives you've considered**
Open a new tab and close the current tab

**Scope**

| Capability | Priority |
| :---------- | :------- |
| Make new tab the root path, preceding drive letters | Must |
| Add a home button to go back to the new tab page | Could |

**System Information**
 - OS Version: Windows 10 21H2 21390.1
 - App version: v1.5
 
**Additional comment**
N/A

**Comment by josh-65** [comment]
The home button on the sidebar in favourites always

**Comment by blacklightpy** [comment]
Oh I didn't notice that.
Still it makes sense to have a Windows Explorer like section for new tab page in the address bar.
Having the homepage as a toolbar icon seems better to me than on the sidebar, bec I like to keep my favorites minimized when I'm not using them. But this is upto choice on what looks better from a design perspective.

**Comment by yaichenbaum** [comment]
Pressing the `up` button will eventually take you to the home page.
