### ISSUE TITLE
Cannot drag files and folders without clicking and selecting them first

### ISSUE THREAD

**Issue by blacklightpy** [files-community/Files#5223]
**Explain the bug**
Cannot drag files and folders without clicking and selecting them first. Files can be dragged only after clicking and selecting once, unlike Windows Explorer where you can directly drag files and it will automatically recognize the action, providing a smoother UX.

**To reproduce**
1. Go to 'any folder'
2. Try to drag any file or folder directly

**Expected behavior**
We should be able to drag the files

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6648941/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6648943/debug_fulltrust.txt)

**Screenshots**
N/A

**System Information**
 - OS Version: Windows 10 21H2 21390.1
 - App version: v1.5

**Additional comment**
N/A

**Comment by yaichenbaum** [comment]
Thank you for the bug report. This issue should be resolved in `main`.

**Comment by rhey0027** [comment]
tnanks for the info
