### ISSUE TITLE
Add option to close panes

### ISSUE THREAD

**Issue by blacklightpy** [files-community/Files#5224]
**Is your feature request related to a problem?**
Cannot close opened second pane in a tab

**Describe the solution**
Add an option to close a pane

**Describe alternatives you've considered**
Open a new tab and close the current tab

**Scope**

| Capability | Priority |
| :---------- | :------- |
| Allow users to close panes| Must |

**System Information**
 - OS Version: Windows 10 21H2 21390.1
 - App version: v1.5
 
**Additional comment**
N/A

**Comment by gave92** [comment]
Ctrl+Shift+W closes the pane, also dragging the pane all the way to the right works.
