### ISSUE TITLE
Cannot create new folder or new item

### ISSUE THREAD

**Issue by fbtwitter** [files-community/Files#5225]
**Explain the bug**
i found bug when i wanted to create new folder or any item, using ctrl + shift + n and also create new item using right click. not giving anything i want. these all unsuccessfully created. 

**To reproduce**
1. Go to any folder or drive
2. Click on new item menu also using ctrl + shift + n
3. I see error, my created folder won't appeared. and it's not there when i check using file explorer

**Expected behavior**
the new folder has to be created.

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6649508/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6649510/debug_fulltrust.log)

**System Information**
 - OS Version: Windows 10 21H2 21390.1010] 
 - App version: v.1.5.32

**Comment by matheusgomestpereira** [comment]
Same
Windows 10 Home 19042
App version: 1.5.2.0

**Comment by esibruti** [comment]
@yair100 I think we can close this

**Comment by yaichenbaum** [comment]
@esibruti this is still an issue in `main`

**Comment by lukeblevins** [comment]
@yair100 Was this fixed? Can't reproduce this one with the latest in main

**Comment by yaichenbaum** [comment]
This was recently resolved in #5594.
