### ISSUE TITLE
is "app.files.com..." part of the Files program? 

### ISSUE THREAD

**Issue by bradley1martin** [files-community/Files#5228]
Also, is the image below from the same program?  I looked online to send a message to the Files team, since I didn't want to do GitHub.  I'm not that techy.  

And I ran across this website, app.files.com..., and it keeps opening up a new tab in my browser, asking for my domain name.  I've never seen anything like this happen before. 
![image](https://user-images.githubusercontent.com/85904877/121955493-e3cf8480-cd14-11eb-84dd-70e892d772c5.png)  

I'd love to learn how to stop it, though. Thanks, Brad

**Comment by gave92** [comment]
That's no us. You can contact the developers also on [Discord](https://discord.gg/files)
