### ISSUE TITLE
Option to hide file names

### ISSUE THREAD

**Issue by nrkus** [files-community/Files#5232]
**Problem**
Windows Explorer used to have a feature that is much missed since it was removed, which was to hide file names entirely, and navigate certain folders purely as a gallery of thumbnails. This is especially nice for pictures, but also any other collection of files with unique thumbnails. I believe this feature would be a great fit with the stylistic approach that Files has taken.

**Solution**
An On/Off switch in the Display Options menu which allows you to show or hide entire file names, just as it is currently possible to show or hide file extensions or hidden items.

**Comment by gave92** [comment]
Could you take a look at this concept -> #5058? Is this close to what you have in mind?

**Comment by Rasmagoric** [comment]
I mentioned that windows 7 feature here #2692
And it was me that designed the #5058 :)

**Comment by nrkus** [comment]
> Could you take a look at this concept -> #5058? Is this close to what you have in mind?

While that concept looks very nice, what I was suggesting is quite a bit simpler than that. I was thinking just giving the option to remove the text without changing the thumbnail size, shape or position (what is the max thumbnail size on Files btw, is it 256px like with Windows Explorer?). It could look something like this :

![Files example](https://user-images.githubusercontent.com/67284030/122289998-99582e80-cef3-11eb-9dca-2a26d3b180d8.jpg)

Most importantly I would like to have that option not just for images, but for other file types as well. The example above is video files for instance.

> It would be a good option to toggle here, in Layout > Display options (Show Image Filenames)

Yes, exactly what I was thinking.
 
> I think this option should only hide filenames of video or image file types, it wouldn't make sense to hide folder's filenames.... maybe there is other files types that this option make sense but can't think of any right now.

I think it could make sense for any file type that has thumbnails, so I see no reason to restrict it. An example that comes to mind is .epub files or .cbr files that display book or comic book / magazine covers as thumbnails.

Funny you should mention folders, I wasn't planning to suggest extending it to folder names, but come to think of it I would love that as well. For example music albums I keep as folders with associated icons : 

![Files example 2](https://user-images.githubusercontent.com/67284030/122292387-3ae07f80-cef6-11eb-83b4-0e3ed93c4505.jpg)

It would look so much more elegant without those pesky file names. Though for folders it would have to be a separate option and also folder-specific, since nobody is going to have custom icons for every single folder.

**Comment by Rasmagoric** [comment]
Agreed 100%. Your screenshots illustrate what I'm talking about, when you have a perfectly curated collection of pictures or videos filenames becomes visual clutter. Specially in images where you can't bother to give a title to all of them.

Now, the problem with hiding folder filenames, is that in windows 21H2 (as far as I know) all the folder icons will look the same, and hiding might be a problem for users that toggle that option in folders that have folders inside. It could be a separate option like you said. But I would be happy with just hiding the filenames of pics, video and other files that have image thumbnails.

**Comment by nrkus** [comment]
>It could be a separate option like you said. But I would be happy with just hiding the filenames of pics, video and other files that have image thumbnails.

Yeah I'm on the same line, I'd be happy with just the option for files, though having the additional option for folders would be perfection.

**Comment by yaichenbaum** [comment]
Merging with #2692
