### ISSUE TITLE
Feature request: international date format option

### ISSUE THREAD

**Issue by davidxxtaylor** [files-community/Files#5234]
**Is your feature request related to a problem?**
The current short date format selected at system>appearance>dateformat does not respect the actual system date format settings of the Win10 installation but instead imposes the m/d/y order which is not applicable outside North America [https://en.wikipedia.org/wiki/Date_format_by_country] . The enforced use of m/d/y outside the US is as annoying as d/m/y would be if it was to be enforced on NA users. Actually its more than annoying its a dealbreaker as a user if you want to avoid error.

**Describe the solution**
Ideally the dropdown should say 'Long date', and 'Short date', and these should follow the user's Win10 system settings for both long and short date formats.

**Describe alternatives you've considered**
The 'System' menu item should at least be less misleadingly renamed 'Concise', and a third menu option 'Concise international' should be offered that delivers  mm/dd/yyyy hh:mm 

**Scope**
| Capability | Priority |
| Date selection options follow Win10 system settings | 1 |
| Add international shortform date format option | 2 |

**System Information**
Win 10 Home 20H2 1902.1052
App v 1.5.0.0

**Comment by gave92** [comment]
> imposes the m/d/y order
Curious, it's alright on my system (dd/mm/yy for Italy)
![image](https://user-images.githubusercontent.com/9673091/122198839-ca0b7a00-ce99-11eb-90ec-f62f80bb25f3.png)
Could you share what settings you have in Windows Settings > Date/time and language > Area?

**Comment by davidxxtaylor** [comment]
Hi
this is what I have:

Win system:

App settings:

App result:


And in Windows Explorer:



Regards
David



------ Original Message ------
From: "Marco Gavelli" ***@***.***>
To: "files-community/Files" ***@***.***>
Cc: "davidxxtaylor" ***@***.***>; "Author" 
***@***.***>
Sent: 16/06/2021 10:58:22
Subject: Re: [files-community/Files] Feature request: international date 
format option (#5234)

**Comment by gave92** [comment]
Looks like the screenshots in your post got removed.

**Comment by davidxxtaylor** [comment]
Here's a pdf

------ Original Message ------
From: "Marco Gavelli" ***@***.***>
To: "files-community/Files" ***@***.***>
Cc: "davidxxtaylor" ***@***.***>; "Author" 
***@***.***>
Sent: 16/06/2021 11:17:31
Subject: Re: [files-community/Files] Feature request: international date 
format option (#5234)

**Comment by gave92** [comment]
Also the pdf got removed 😂 You may have to post images from github not from email. Thanks for the help.

**Comment by davidxxtaylor** [comment]
[Re_ [files-community_Files] Feature request_ international date format option (#5234).pdf](https://github.com/files-community/Files/files/6662746/Re_.files-community_Files.Feature.request_.international.date.format.option.5234.pdf)

**Comment by gave92** [comment]
My bad, it looks like we select the date format based on the selected locale (either system or the one set in the app) not based on the date format settings.

Make sure you have the following:
- In Files:
![image](https://user-images.githubusercontent.com/9673091/122224331-4dd26000-ceb4-11eb-8f53-ad9036600738.png)

- In Windows
![image](https://user-images.githubusercontent.com/9673091/122224526-7ce8d180-ceb4-11eb-923a-77dafcd93780.png)

**Comment by davidxxtaylor** [comment]
Thanks, that has helped. Now I have these settings:

![image](https://user-images.githubusercontent.com/78256455/122230849-e7e4d900-ceb1-11eb-8613-7976913b6f21.png)
_______________________

![image](https://user-images.githubusercontent.com/78256455/122229326-8b34ee80-ceb0-11eb-8ced-470e39bde6de.png)
______________________

![image](https://user-images.githubusercontent.com/78256455/122229392-99830a80-ceb0-11eb-97c5-7d71deef42a2.png)
__________________


The result is that selecting system date or application date makes no difference:

![image](https://user-images.githubusercontent.com/78256455/122228623-f0d4ab00-ceaf-11eb-9ae5-d293b6ee7856.png)

So: for all internal HDDs, dirs and files show dd/mm/yyyy hh:mm:ss +UTC suffix. Correct dym order but does not seem to correspond with any windows locale or time or other setting visible to me. 

______________________
I then have 3 external HDDs, two of them show as above, but one shows like this
![image](https://user-images.githubusercontent.com/78256455/122228909-385b3700-ceb0-11eb-96ed-5dde821ba121.png)
So: a nice shortform date per my Win settings.

Although this inconsistency is annoying, and the lack of change on different Date Format settings in the app is puzzling,  the main thing is that the dmy is now correct for me so that is the main thing and many thanks for your help.

A small change in the Help page [https://files-community.github.io/docs/#/articles/date-formats] to say that the examples will vary according to Win system settings would be useful, I thought when first reading it that they are fixed, hence the feature request..

**Comment by yaichenbaum** [comment]
Merging with #2207.
