### ISSUE TITLE
Feature Request: Switch to previous tab with Ctrl + Shift + Tab

### ISSUE THREAD

**Issue by BanCrash** [files-community/Files#5235]
**Is your feature request related to a problem?**
I don't think so.

**Describe the solution**
Hello, I saw that you can use Ctrl + Tab to go to the next tab, but you can't use Ctrl + Shift + Tab to go to the previous tab, as you can do in navigators. I would like to have this option so you can switch easily among tabs.

It would be to have another keybind to Ctrl + Shift + Tab to go to the previous tab.

**Describe alternatives you've considered**
I don't know any alternative to this.

**Scope**
To be honest I'm not sure how I have to fill this since it's a very simple request. If this is mandatory for the request I can edit if you let me know how can I do it for this request.

**System Information**
 - OS Version: Windows 10 Pro 21H1 compilation: 19043.1055 Windows Feature Experience Pack: 120.2212.2020.0

 - App version: 1.5.0.0

**Additional comment**
Thanks so much for the app, this is what windows explorer should be.

**Comment by BanCrash** [comment]
Perfect, thanks you!

**Comment by yaichenbaum** [comment]
@BanCrash By the way, great work on your first pull request!

**Comment by BanCrash** [comment]
> @BanCrash By the way, great work on your first pull request!

Thanks you!! I hope that I will be able to contribute with other things in the future.

**Comment by yaichenbaum** [comment]
Looking forward 😄
