### ISSUE TITLE
Files and folder view 

### ISSUE THREAD

**Issue by bradley1martin** [files-community/Files#5243]
Looking at the root of my Dropbox files, files and folders are shown all in alphabetical order, but I really want to see all the folder first, then the assorted files that reside in the root.  Is this a simple setting?  It seemed like it did display it the other way, like Windows File Explorer does, when I first got the program. 

Thanks, Brad

**Comment by josh-65** [comment]
settings > files and folders > list and sort directories alongside files to off

**Comment by bradley1martin** [comment]
That did it, thanks!
