### ISSUE TITLE
Incorrect Active Tabs

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#5244]
**Explain the bug**
I have my "Show library section on the sidebar" option turned on (Settings > Preferences), which will add a section that consists of Documents, Pictures, Music, and Videos. While I am trying to open Document Tabs located in `Favorites`, with `Favorites` and `Libraries` Section extended, the active properties (small blue bar) are located in `Favorites` Section, instead of `Libraries` Section.

**To reproduce**
1. Extend `Favorites` and `Libraries` Sections
2. Click on the Documents Tab, which is located in `Libraries` Section
3. See the error

**Expected behavior**
The active properties should be on `Libraries` Section instead of `Favorites` Section.

**Logfile**
Upload the log file here for us to understand your issue better. 
- You can access it from Settings->About->Open log location. 
or 
- Copy the debug.log and debug_fulltrust.log from the following directory, and upload the files here.
`%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 

**Screenshots**

https://user-images.githubusercontent.com/69080584/122363952-9278fc80-cf83-11eb-971a-4363dea27ada.mp4

**System Information**
 - OS Version: Windows 10 21H1 19043.1055
 - App version: v1.5.0.0

**Additional comment**
Does this problem happen again after restarting the app? Yes this problem happens again after restarting the app.

**Comment by gave92** [comment]
Thanks for this report. This is fixed on main.

**Comment by BanCrash** [comment]
> Thanks for this report. This is fixed on main.

I am having a similar issue with the main branch, but with drives instead libraries:

![GIF 18-06-2021 3-12-09](https://user-images.githubusercontent.com/11770760/122490806-17473300-cfe3-11eb-8845-f5b0c9d43bd8.gif)
