### ISSUE TITLE
Copying, pasting, deleting, the folders just don't refresh automatically

### ISSUE THREAD

**Issue by geffao** [files-community/Files#5246]
Whenever copying, pasting, deleting, the folders just don't refresh automatically. You can't exactly know if one of those operations succeeded if you don't refresh the tab yourself, or reopen the folder.

**Explain the bug**
Write a clear description of what the bug is.

To reproduce just copy, delete, paste, or move a file or folder.

**To reproduce**
1. Go to '....'
4. See the error

Expected behavior is that after moving/copying/deleting/pasting, the folder/tab should update automatically to reflect the changes.

**Expected behavior**
Write a clear description of what you expected.

**Logfile**
Upload the log file here for us to understand your issue better. 
- You can access it from Settings->About->Open log location. 
or 
- Copy the debug.log and debug_fulltrust.log from the following directory, and upload the files here.
`%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 

**Screenshots**
Add screenshots to help explain your problem if needed.

Windows version: Windows 10 Pro 21H1 build 19043.1052
App version 1.5.0.0
**System Information**
 - OS Version: [e.g. Windows 10 20H2 19042.804] (Press WIN + PAUSE/BREAK, use the copy button at the bottom)
 - App version: [e.g. v1.0] (In the app, go to Settings -> About, the version is shown at the top)

Keep the good work. The app looks nice!
**Additional comment**
Add any other comment about the problem here. Does this problem happen again after restarting the app?

**Comment by josh-65** [comment]
A lot of work has been done for auto refreshing so it should be fixed for v2 update.

**Comment by gave92** [comment]
Thanks for this report. This issue should be fixed in latest code.
