### ISSUE TITLE
Zoom within chosen layout instead of changing layout

### ISSUE THREAD

**Issue by MikeFarrington** [files-community/Files#5247]
**Is your feature request related to a problem?**
No. The problem is with my aging eyes.  Detail view is the only useful view in my opinion, but it does not scale / zoom.

**Describe the solution**
I would like to see a padlock or on/off toggle next to the layout options in the settings.  When the layout is locked down, zooming will scale the display within the desired layout style instead of shifting to the next layout style. 

**Describe alternatives you've considered**
Other options could be a zoom slider or an alternate key when using +/- or mousewheel, but I think that would muddle the main UI and only work for keyboard or keyboard/mouse and not pinch-to-zoom on a tablet.  My initial proposal would work for all zoom methods.

**Scope**

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to accomplish zooming within the desired layout | Should |

**System Information**
 - OS Version: Windows 10 21H1 19043.1055
 - App version: v1.5.0.0

**Additional comment**
None

**Comment by yaichenbaum** [comment]
This is a cool idea and I think it will be helpful for a lot of users. The usual shortcuts that are used for zooming in and out are already being used to change the layouts, any ideas how we can accommodate this without changing the current behavior?

**Comment by esibruti** [comment]
> This is a cool idea and I think it will be helpful for a lot of users. The usual shortcuts that are used for zooming in and out are already being used to change the layouts, any ideas how we can accommodate this without changing the current behavior?

@yair100 You couldn't make it so that when you place the mouse's arrow on the button it would click, in a temporary way, and when you remove it, it applies the original again? I don't know if I understood...

**Comment by gave92** [comment]
Just to add that there's an option in Windows Settings that allows to scale text/UI (for all apps) which might already cover this feature.

![image](https://user-images.githubusercontent.com/9673091/122600892-c120d100-d070-11eb-83b5-2553091252db.png)

**Comment by yaichenbaum** [comment]
The text scaling is a little different, but either way, that might be the only way to do it without breaking virtualization.

**Comment by MikeFarrington** [comment]
> 
> 
> This is a cool idea and I think it will be helpful for a lot of users. The usual shortcuts that are used for zooming in and out are already being used to change the layouts, any ideas how we can accommodate this without changing the current behavior?

My suggestion of a lock that the user enables, I think, would basically switch the behavior of the actions.  Frankly though, I think this is something that is worthy of a breaking change.  If there were metrics, I would imagine that few people change layouts in this manner.  I believe, and I have no data to back this up, that people choose one view and stick with it (except, perhaps, when it comes to image folders).  Click+Scroll has become a de facto standard for UI zooming/scaling, and Microsoft's File Explorer is simply behind the times in that regard.  At a certain point, mimicry must be set aside for usability and progress.  Of course, that is not for me to decide here -- only to suggest.

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
@MikeFarrington I don't see a way to do this without breaking virtualization, it seems like the only option for now is to change the display scaling. Alternatively, we can try adding a more spacious layout setting where the text is larger, and everything is more spread out.
