### ISSUE TITLE
Feature: Add the open in terminal option when right clicking on a folder

### ISSUE THREAD

**Issue by Darkempire78** [files-community/Files#5248]
### What feature or improvement do you think would benefit Files?
The "Open in terminal" option works only when you right click in a blank space

### Requirements

- 

### Files Version

2.3.11.0

### Windows Version

10.19043.1899

**Comment by oleitao** [comment]
Before start to solve that issue I've tested the required feature and that looks to be already implemented. Please see on my test (below) if i did something wrong.

![test](https://user-images.githubusercontent.com/72361786/126567453-47ea31e2-63ed-45c7-ac6d-6e004a7b5ea3.gif)

**Comment by Darkempire78** [comment]
Yes, it seems to be fixed!

**Comment by yaichenbaum** [comment]
This is still an issue in `main`.
