### ISSUE TITLE
Crash without apparent explanation

### ISSUE THREAD

**Issue by Darkempire78** [files-community/Files#5249]
**Explain the bug**
The application crashed without any apparent explanation during normal use

**To reproduce**
No idea, check the logs

**Expected behavior**
I think I wanted to open a folder, but it's certainly not related, I think it's due to the caching feature

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6675923/debug.txt)

**System Information**
 - OS Version: Windows 10 20H2 19042.928
 - App version: 1.5.0.0

**Additional comment**
Cache files and folders is enabled

**Comment by gave92** [comment]
Thanks for this report. This should be fixed in Files 1.5.44.0. If you find it happening there too please let us know.
