### ISSUE TITLE
Recent files are incorrectly sorted when Files opens

### ISSUE THREAD

**Issue by Darkempire78** [files-community/Files#5250]
**Explain the bug**
Recent files are incorrectly sorted when Files opens.
They are sorted from oldest open (top) to newest open (bottom)
However, when you click on one of these files or add a new one, they become well sorted

**To reproduce**
1. Open Files and see Recent (ncorrectly sorted)
2. Open a recent file
3. Open a folder as the Desktop
4. Go back to recent (they become well sorted)

**Expected behavior**
Sort recent files correctly when Files opens

**Logfile**
/

**Screenshots**
When Files opens
![image](https://user-images.githubusercontent.com/50015928/122546107-e8ef4500-d02e-11eb-9e98-039f47efb37b.png)
After
![image](https://user-images.githubusercontent.com/50015928/122546038-d6750b80-d02e-11eb-8807-2808b0088871.png)

**System Information**
 - OS Version: Windows 10 20H2 19042.928
 - App version: 1.5.0.0 and 1.5.44.0

**Additional comment**
Does this problem happen again after restarting the app? 
**Yes**

**Comment by Darkempire78** [comment]
still with the app version 1.5.44.0

**Comment by yaichenbaum** [comment]
This issue should be resolved with #9153
