### ISSUE TITLE
New tab or new window from second pane opened

### ISSUE THREAD

**Issue by esibruti** [files-community/Files#5251]
I had an idea but I don't know if it already exists in Files: could there be a button to make that second pane a new tab or a new window? I think it would be interesting to put this feature, if it doesn't already exist.

**Comment by yaichenbaum** [comment]
@esibruti Can you explain how this feature would be helpful to you?

**Comment by esibruti** [comment]
@yair100 In my opinion, I find it an interesting feature, because if, for example, the user opens through the second pane and then has the need to keep this "path" so to speak open, this can lead to keeping it open as a new tab or new window.

For example, it looks for a folder inside a local disk, and in turn, it needs to keep that folder open, because then inside that folder it has to open more folders. This is the birth of the idea of ​​having the option of being able to move the second pane as a new tab or as a new window. I find it an interesting idea for some users who have the need to open folders and move folders to tabs for later use.

**Comment by yaichenbaum** [comment]
@esibruti In your example, are you keeping the path in the other pane open as well, or are you done with that and just want the path from that one pane?

**Comment by esibruti** [comment]
@yair100 In this case, it would just take the path to the secondary panel and then the user would either open it in a new tab or a new window. 
Of course, once chosen, this secondary panel is closed. We could even make a definition in the Files settings for the user whether, after choosing the option, the secondary panel closes automatically or not.

**Comment by yaichenbaum** [comment]
@esibruti I was actually referring to the other pane, not the one that you choose to open in a new tab.

**Comment by esibruti** [comment]
@yair100 Ahhh😅, I didn't understand that it was this panel. On this panel, it will still be open.

**Comment by esibruti** [comment]
@yaichenbaum What do you think of this idea?

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.11.0 or above?

**Comment by yaichenbaum** [comment]
We don't have plans to implement this feature.
