### ISSUE TITLE
The option to create bundles isn't working

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#5252]
Steps to reproduce:
1. Create a bundle
2. Try creating a second bundle
3. Nothing happens

**Comment by yaichenbaum** [comment]
Fyi @d2dyno1

**Comment by d2dyno1** [comment]
On `main`?

**Comment by yaichenbaum** [comment]
Yes

**Comment by d2dyno1** [comment]
https://user-images.githubusercontent.com/53011783/122604513-583c5780-d076-11eb-9997-24cbf892b0cc.mp4

@yair100

**Comment by yaichenbaum** [comment]
Let's keep this open for now since it's still an issue on my device.

**Comment by pc-v2** [comment]
also #5395

**Comment by yaichenbaum** [comment]
@d2dyno1 Are you testing in release mode?

**Comment by d2dyno1** [comment]
> @d2dyno1 Are you testing in release mode?

I'll give it a try

**Comment by yaichenbaum** [comment]
This issue appears to be resolved in `main`.
