### ISSUE TITLE
File and folder icons don't load

### ISSUE THREAD

**Issue by TheOnlyTails** [files-community/Files#5254]
**Explain the bug**
Some files' icons don't load, and use Files' default icon instead of the proper one.

**To reproduce**
1. Open a folder
2. See the error

**Screenshots**
![image](https://user-images.githubusercontent.com/65342367/122574148-084e9800-d058-11eb-99ee-c6a809a1e531.png)

**System Information**
- Edition: Windows 10 Home
- Version: Dev
- Installed on: 26-‎May-‎21
- OS build: 21390.2025
- Experience: Windows 10 Feature Experience Pack 321.13302.10.3

 - App version: v1.5.44.0

**Additional comment**
Sometimes this problem happen again after restarting the app, sometimes it does not.

**Comment by yaichenbaum** [comment]
@TheOnlyTails Can you confirm if this happens with specific file types of if it's just random?

**Comment by TheOnlyTails** [comment]
@yair100 It seems to be random, as it has only happened to that specific file.

**Comment by duke7553** [comment]
@TheOnlyTails Can you check if that specific file displays an icon in File Explorer? Some items simply don't have icons, but soon we'll be retrieving them more quickly and reliably.

**Comment by TheOnlyTails** [comment]
Looks like it does:
![image](https://user-images.githubusercontent.com/65342367/122681856-0246eb80-d1ff-11eb-9003-1f8d0d42d9af.png)

**Comment by yaichenbaum** [comment]
@TheOnlyTails This issue should be resolved with #5357.
