### ISSUE TITLE
Cannot rename bundles 

### ISSUE THREAD

**Issue by TheOnlyTails** [files-community/Files#5255]
**Explain the bug**
When trying to rename bundles, the name does not update.

**To reproduce**
1. Create a bundle
2. Open the 3-dot menu
3. Click "Rename bundle"
4. Enter a new name and confirm
3. See the error

**System Information**
- Edition: Windows 10 Home
- Version: Dev
- Installed on: 26-‎May-‎21
- OS build: 21390.2025
- Experience: Windows 10 Feature Experience Pack 321.13302.10.3

 - App version: v1.5.44.0

**Comment by yaichenbaum** [comment]
Fyi @d2dyno1

**Comment by d2dyno1** [comment]
Sorry, but I wasn't able to reproduce the issue on my end :(

**Comment by pc-v2** [comment]
i have this issue too #5395

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5439.
