### ISSUE TITLE
Improve UX for adding new items to bundles

### ISSUE THREAD

**Issue by TheOnlyTails** [files-community/Files#5256]
**Is your feature request related to a problem?**
Once a bundle contains items, the tooltip explaining how to add more to it goes away. If a user set up their bundles and then forgot, there is no way to figure out how to add new items without creating a new bundle.

**Describe the solution**
Adding an option to add a new folder to a bundle via the right click menu.

**Describe alternatives you've considered**
Adding an option to add a new folder to a bundle via the 3-dot menu.

**Scope**

| Capability | Priority |
| :---------- | :------- |
| This proposal will add the button to the right click menu | Must |
| This proposal will add the button to both the right click and 3-dot menu | Could |
| This proposal replace the old drag-drop system. | Won't |

**System Information**
- Device name: TheOnlyTails
- Processor: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz   2.30 GHz
- Installed RAM: 8.00 GB (7.85 GB usable)
- Device ID: EFEC9023-BBDC-4447-ADCD-269D64BDF32C
- Product ID: 00325-96606-60041-AAOEM
- System type:	64-bit operating system, x64-based processor
- Pen and touch: No pen or touch input is available for this display
- App version: v1.5.44.0

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5475.
