### ISSUE TITLE
Crash when Downloads opens

### ISSUE THREAD

**Issue by Darkempire78** [files-community/Files#5258]
**Explain the bug**
Files crashes when I opened the Downloads section.

**To reproduce**
Idk
Check the logs to get more info

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6677648/debug.log)

**Screenshots**
/

**System Information**
 - OS Version: Windows 10 20H2 19042.928
 - App version: 1.5.44.0

**Additional comment**
Does this problem happen again after restarting the app?
**No**

**Comment by Darkempire78** [comment]
it may be due to the transition between version 1.5.0.0 and version 1.5.44.0

**Comment by yaichenbaum** [comment]
@Darkempire78 Was this just a one time crash?

**Comment by clementwzk** [comment]
@yair100 yes

**Comment by gave92** [comment]
FWY @d2dyno1 the crash seems related to Files.ViewModels.Widgets.Bundles.BundlesViewModel.Load() could you take a look?

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5262.
