### ISSUE TITLE
Moving translation resources from XLFs to JSONs

### ISSUE THREAD

**Issue by TheOnlyTails** [files-community/Files#5259]
## The problem
Right now, if someone wants to translate Files, they have to clone the whole project just to work on one small file, not to mention having to work with XML, which has really bloated syntax, making finding the important stuff hard.

## The solution
Replacing the XLF files with JSON files (preferably using a JSON schema to determine the structure), and removing all of the unnecessary stuff that doesn't apply to translators, then using a custom script to generate XLF files from the JSONs.

## Scope

| Capability | Priority |
| :---------- | :------- |
| Set a structure for all translation files to follow | Must |
| Use a JSON schema to pre-determine that structure | Should |
| Move the translation files into a separate repo, reducing the clone size | Could |
| Use a crowd sourcing platform to manage translations | Could |
| Require the translators themselves to move their translations into JSONs | Won't |

## Additional comments
If needed, I can write the JSON schema and/or port the old XMLs myself.

**Comment by yaichenbaum** [comment]
@TheOnlyTails How would this prevent the need to clone the repository?

**Comment by gave92** [comment]
Plus the repo is 17MB if you don't build the app which is not that much :)

**Comment by TheOnlyTails** [comment]
> @TheOnlyTails How would this prevent the need to clone the repository?

@yair100 I've updated the issue description. 

> The xlif files also do a lot more than hold the strings, it keeps track of which strings were updated, which ones need to be translated etc. 

That could all be passed as optional fields with default values. The files are still way too big and complex.

**Comment by yaichenbaum** [comment]
@TheOnlyTails How would we update those fields? The multilingual toolkit extension automatically updates them for us.

**Comment by TheOnlyTails** [comment]
@yair100 I wasn't aware of that, but I don't think it's a really big issue.

**Comment by yaichenbaum** [comment]
@TheOnlyTails Unfortunately I don't think it's worth spending time on creating an alternative method since our current focus is on the Files app rather than the tooling around it.

**Comment by TheOnlyTails** [comment]
OK then, I see what you mean.
