### ISSUE TITLE
Crash when you delete something while Files is open in the Bin section

### ISSUE THREAD

**Issue by Darkempire78** [files-community/Files#5260]
**Explain the bug**
Files crashes when you delete something whilethe Trash section is opened

**To reproduce**
1. open Files 
2. Go to "Bin"
3. Delete a file from you computer (tested with a shortcut on the Desktop)

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6678398/debug.log)

**System Information**
 - OS Version: Windows 10 20H2 19042.928
 - App version: 1.5.44.0

**Additional comment**
Does this problem happen again after restarting the app?
**Yes**

**Comment by yaichenbaum** [comment]
This issue is resolved in `main`.
