### ISSUE TITLE
Bin is empty if you open it in a new tab

### ISSUE THREAD

**Issue by Darkempire78** [files-community/Files#5261]
**Explain the bug**
the Bin is empty if you open it in a new tab when it really isn't. 
It works fine when you open it without the current tab

**To reproduce**
1. Open the Bien in a new tab

**Logfile**
/

**Screenshots**
/

**System Information**
 - OS Version: Windows 10 20H2 19042.928
 - App version: 1.5.44.0

**Additional comment**
Does this problem happen again after restarting the app?
**Yes**

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5170.
