### ISSUE TITLE
Multi range selection using Ctrl and Shift does not work as expected

### ISSUE THREAD

**Issue by sujeendran** [files-community/Files#5267]
**Explain the bug**
I tried selecting multiple items that appear consecutively while holding down Shift and this worked. But after clicking on another item while holding down Ctrl and trying to add few more items in the range using Shift to the current selection it forgets the first range I had selected. This is default behavior in File Explorer and I think should also work with Files.

**To reproduce**
1. Go to any folder with several files in list display mode.
2. Click on a file to select it.
3. Hold down shift and select a range of files.
4. After first range is selected, hold down Ctrl and click a file that has not yet been selected to add to selection.
5. Now hold down Ctrl and Shift and try to add a new range of files to the selection.
6. Only the second range gets selected.

**Expected behavior**
Step 6 should result in two ranges of selection and not just the last range.

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6680364/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6680365/debug_fulltrust.txt)

**Screenshots**
How above steps work in File Explorer (Expected)
![image](https://user-images.githubusercontent.com/30560413/122637268-49ec4b00-d10b-11eb-9129-de5deacc8b16.png)
How above steps work in Files
![image](https://user-images.githubusercontent.com/30560413/122637289-67b9b000-d10b-11eb-9eec-af1a5c09ed8b.png)

**System Information**
 - OS Version: Windows 10 21H1 19043.1055
 - App version: v1.5.0.0

**Additional comment**
This is not a one off behavior but mostly something wrong in how the selection part is handled overall.
On a side note: The app is beautiful and really something Microsoft should take up as default. Do please add more touch support. Keep it going!

**Comment by gave92** [comment]
Thanks for this report. This issue has been fixed in latest code.

**Comment by sujeendran** [comment]
Thanks for the update! When can we expect to get this update for the windows store app?

**Comment by gave92** [comment]
I'm going to say "mid-august". If you wish you can anyway get the beta versions by [joining Files insiders program].(https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAO__Qw_X6FUM0pUSzMxNUlCWE1FVENKVlVNVUNTRVpOUS4u)
