### ISSUE TITLE
Custom folder icons not always showing

### ISSUE THREAD

**Issue by davidxxtaylor** [files-community/Files#5274]
**Explain the bug**
Custom folder icons do not always appear in details pane, sometimes they are replaced by genericfolder icon, though they do appear in preview pane

**To reproduce**
Using Explorer set icons as shown in the clip. In Files they do not always appear.

**Expected behavior**
Icons to show like in Explorer

**Screenshots**
![image](https://user-images.githubusercontent.com/78256455/122648751-7790be80-d122-11eb-8f29-a54d295fabcd.png)

**System Information**
 - OS Version: Edition	Windows 10 Home
Version	20H2
Installed on	‎07/‎06/‎2021
OS build	19042.1052
Experience	Windows Feature Experience Pack 120.2212.2020.0

 - App version: 1.5

**Comment by gave92** [comment]
Thanks for this report. This is fixed in latest code.
