### ISSUE TITLE
"Set as" Doesn't appear when selecting >1 image.

### ISSUE THREAD

**Issue by swolenutz1951** [files-community/Files#5275]
"Set as" does not appear on the right click menu when **multiple** images are selected.

When trying to create a slideshow background, on explorer I would: 
Highlight multiple images > right click > Set as > Background

System Information
 - OS Version: Windows 10 19043.1055 21H1 
 - App version: v1.5

**Comment by yaichenbaum** [comment]
This issue should be resolved with #9712
