### ISSUE TITLE
[FR] Collapse sidebar on load

### ISSUE THREAD

**Issue by Hukuma1** [files-community/Files#5276]
**Is your feature request related to a problem?**
Currently the sidebar is always opened on Files start.

**Describe the solution**
Add an option to have sidebar be collapsed on load.

**Describe alternatives you've considered**
Manually pressing the menu button constantly like an ape to collapse the sidebar.

**Additional comment**
I don't use the sidebar frequently and would rather have it be collapsed to have a more minimal look to the Files app. It still retains the icons in its collapsed state, so no functionality is lost. Only space is saved. :)

**Comment by yaichenbaum** [comment]
Fyi @winston-de

**Comment by winston-de** [comment]
The sidebar should remember whatever state it was in last when you open Files. As in, if you had it collapsed last time you closed Files, when you open it again it will be collapsed.

**Comment by yaichenbaum** [comment]
@Hukuma1 The changes mentioned by Winston will be coming to Files in v2.
