### ISSUE TITLE
Focus on File After Open File Location Command

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#5278]
**Is your feature request related to a problem?**
Many people often use `Recent items` feature to open the folder or file they recently open, sometimes people also wanted to open file location - where the file is located. And the problem is, it will be difficult for users to find which file it is when the folder consists of many files and /.or folders.

**Describe the solution**
Try to focus the files when users click on Open file location.

**Describe alternatives you've considered**
A clear description of any alternative solutions or features you've considered.

**Scope**

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**System Information**
 - OS Version: Windows 10 21H1 19043.1055
 - App version: 1.5.0.0

**Additional comment**
Add any other comment or screenshots about the feature request here. What device type/UI layout and app version?

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5282
