### ISSUE TITLE
Picture rendering in files list/tab

### ISSUE THREAD

**Issue by palben** [files-community/Files#5280]
**Explain the bug**
Rendering of pictures in the files lists/tabs
Picture files are not always rendered completely in the files list. This seems to be random on each restart of the app. Usually the tab opened is completely populated but when I switch to the other tab, some files are rendered black or with the generic icon only. 

**To reproduce**

**Expected behavior**
Complete rendering of all pictures.

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6682153/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6682154/debug_fulltrust.txt)

**Screenshots**
![files1](https://user-images.githubusercontent.com/57135408/122670947-becf8b80-d1c4-11eb-9ff1-9c55f38faecf.jpg)
![files2](https://user-images.githubusercontent.com/57135408/122671382-934da080-d1c6-11eb-8234-7d589614137a.jpg)

**System Information**
Edition	Windows 10 Pro
Version	Dev
Installed on	‎27-‎May-‎21
OS build	21390.2025
Experience	Windows 10 Feature Experience Pack 321.13302.10.3
bottom)
 - App version: 1.5.0.0

**Additional comment**

**Comment by yaichenbaum** [comment]
@palben Can you confirm if this is the same issue as #5254?
