### ISSUE TITLE
The program freezes.

### ISSUE THREAD

**Issue by DotX3** [files-community/Files#5284]
I have a problem that has been repeated many times before. If you try to open the context menu on any folder, the program freezes completely and you have to restart it to continue working.

OS Version: Windows 10 Pro 20H2 19042.1052

App Version: v1.5.0.0

[debug.txt](https://github.com/files-community/Files/files/6682650/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6682651/debug_fulltrust.txt)

**Comment by gave92** [comment]
Merging with #5032

**Comment by gave92** [comment]
Does it un-freeze after 15seconds or not at all?

**Comment by DotX3** [comment]
After 2 minutes, an error appeared and the program closed
"pCloud" is not installed

**Comment by DotX3** [comment]
[debug.txt](https://github.com/files-community/Files/files/6682678/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6682679/debug_fulltrust.txt)

Debug files after crash
