### ISSUE TITLE
Crash when trying to navigate folders

### ISSUE THREAD

**Issue by TheOnlyTails** [files-community/Files#5287]
## Explain the bug
When I'm trying to navigate folders, Files just unexpectedly crashes.

## To reproduce
1. Navigate between folders (not sure what exactly causes it)
4. See the error

## Expected behavior
It not crashing.

## Logfile
[debug.log](https://github.com/files-community/Files/files/6682931/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6682933/debug_fulltrust.log)

**System Information**
- Edition: Windows 10 Home
- Version: Dev
- Installed on: 26-‎May-‎21
- OS build: 21390.2025
- Experience: Windows 10 Feature Experience Pack 321.13302.10.3
 - App version: v1.5.44.0

**Additional comment**
This problem repeats, even after relaunching.

**Comment by gave92** [comment]
Annoyingly common stacktrace on AppCenter.

**Comment by yaichenbaum** [comment]
@TheOnlyTails is this still an issue in v2.0.34?

**Comment by TheOnlyTails** [comment]
I haven't noticed it in quite a while, so I don't think so!
