### ISSUE TITLE
When cutting (Ctrl+X), item(s) are unselected when going between tabs

### ISSUE THREAD

**Issue by Scrut1ny** [files-community/Files#5295]
Cutting (Ctrl+X) file(s) are unselected when switching between tabs.
- Win10 - Latest version

**Comment by Raithlin** [comment]
What version on Windows is this on? I am unable to replicate the issue on Windows 11.

**Comment by Anonymoushacker4926** [comment]
It was on the latest version of windows 10. The issue was 6 months ago though it might've been patched already idk.
