### ISSUE TITLE
Detailled list accessibility and selection with keyboard

### ISSUE THREAD

**Issue by iubito** [files-community/Files#5296]
**Explain the bug**
In grid view or classic Explorer, below behaviours are correct. In Files detailled view they behave badly :
- ctrl + up/down to extend a discontinuous selection
- up / down to select one file, no accessibility for screen readers.

**To reproduce**
1. Go to a directory and choose the detailled view
2. Start a good screen reader like NVDA or Jaws
3. move the mouse, you can hear the name of hovered files :)
4. use up/down keys to change the highlighted file, you hear nothing :(
5. Use shift + up/down keys, the selection is extended continuous :)
6. Use ctrl + up/down keys to skip one file in the selection, all files are unselected, list of move files move up/down one page, and only one file is selected :(

**Expected behavior**
1. In detailled view, up/down keys to select one file should send file name to screen reader.
2. Ctrl + up/down key should skip one file in the multi-selected file, not move the list from one page up/down and loose the already selected files.

**System Information**
 - OS : Windows 10 Professionnel, 20H2, 19042.1052, Windows Feature Experience Pack 120.2212.2020.0
 - external app : NVDA screen reader, or you can try with windows Narrator (which works worse than good screen readers like NVDA or Jaws, no blind people use Narrator).
 - App version: 1.5.0.0

**Additional comment**

**Comment by yaichenbaum** [comment]
There is a chance this is resolved in `main`. @winston-de can you confirm this?

**Comment by yaichenbaum** [comment]
This issue is resolved in v2.0.34.
