### ISSUE TITLE
Different layout mode and sorting for each folder

### ISSUE THREAD

**Issue by XPoppyX** [files-community/Files#530]
I would like to be able to use different layout modes and sorting in each folder, like in file explorer.

**Comment by yaichenbaum** [comment]
We can definitely explore this but in order to be transparent I want to let you know it probably won't be before Launch 2020.

**Comment by Jaiganeshkumaran** [comment]
In File Explorer, the layout of a folder is stored in a hidden file named "Desktop.ini". We could use the same file for setting the layout.

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran Is this something you would like to work on?

**Comment by Jaiganeshkumaran** [comment]
Yes, sure.

**Comment by Jaiganeshkumaran** [comment]
In File Explorer, the layout mode and sorting for a directory is stored in a file named desktop.ini in that folder. We can do something similar or we can use a JSON file in the app local folder.

**Comment by Cyberdroid1** [comment]
Any updates to this? I am really looking forward to this! 👀

**Comment by XPoppyX** [comment]
first implementation attempt with #1485, read the comments

**Comment by yaichenbaum** [comment]
@XPoppyX This feature is implemented with #2667.
