### ISSUE TITLE
Recycle bin delete confirmation not showing display names for files/folders

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5302]
**Explain the bug**
The real folder name the recycle bin uses is show rather them what the actual original folder/file name was

**Expected behaviour**
The original folder/file name should be shown

**Screenshots**
![image](https://user-images.githubusercontent.com/26977075/122989594-e5dfb600-d39a-11eb-8a6a-4a100f02d4f4.png)

**System Information**
 - OS Version: Windows 10 20H2 19042.1055
 - App version: v1.5.46

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5440.
