### ISSUE TITLE
Constantly hangs/loads files slowly

### ISSUE THREAD

**Issue by pinkiepanda** [files-community/Files#5304]
**Explain the bug**
The app takes a long time to load any number of files. This occurs whenever I change directory. Even a folder with 10 tiny JPEG images can take up to 2-3 seconds to load.
A folder with many items will also hang when scrolling, after about 10-20 "new" items, for about 0.5-1 second, also regardless of file size or type. Scrolling down then back up to files I just saw a second ago will cause it to hang again.
When it hangs, the icons for the "new" files the app is trying to load have the blank icons, if that indicates anything.
Clicking on an opened tab also hangs for about 0.5-1 second, though not as long as loading a new directory or scrolling through one.

Both "Cache files and folders..." and "Use preemptive cache..." settings appear to have no effect. Restarting the app also has no effect.

I haven't seen anyone else with this issue, on github or other people I know who use it.

**To reproduce**
All situations, accessing any directory or tab with any kind of files.

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6700246/debug.txt)

**System Information**
 - OS Version: Windows 10 Pro 20H2 19042.1052
 - App version: 1.5.0.0

**Comment by gave92** [comment]
Loading speed has been much improved in the latest beta version. If you wish to try it you can join the Files insider program.

> Both "Cache files and folders..." and "Use preemptive cache..." settings appear to have no effect.

Fastest result with current version are with those settings _off_.

**Comment by yaira2** [comment]
We're excited to share that startup performance will be significantly improved in the upcoming release of version 3. You can download the preview version from our website https://files.community/download.
