### ISSUE TITLE
Grid View Incorrect Item Widths

### ISSUE THREAD

**Issue by Dylan-Osborne** [files-community/Files#5305]
**Explain the bug**
Grid view item widths are incorrect if you have less files than the number required to wrap the files around to the next row.
For example, if your grid view layout sizing is such that your files should wrap to the next row if there are more than 6 items and you only have two files, the entire row's width is split between those two files instead of the width being calculated as if there were 6 items.

**To reproduce**
1. Use any of the Grid View layouts.
2. Open any folder with one file.
3. Instead of the Grid View 'cell' being the correct width it takes up the entire row.

**Expected behavior**
The width of a 'cell' for a file/item should always be the same regardless of the number of items.

**Screenshots**
Single file with the correct height, but the width uses the full width instead of being restricted to e.g. 1/6 of the width:
![image](https://user-images.githubusercontent.com/46000533/123070821-655d9b80-d414-11eb-903f-f7c6346a1021.png)

Multiple files with each 'cell' having the correct width, this happens as long as there are the enough files to complete the first row (meaning that adding one more file would create a new row) which in this case is 6:
![image](https://user-images.githubusercontent.com/46000533/123070713-47903680-d414-11eb-9f89-9f3a2061b6fa.png)

**System Information**
 - OS Version: Windows 10 21H1 19043.1052
 - App version: 1.5.46

**Additional comment**
I still get this issue after restarting.
Note, if you have enough files so that the width is correct e.g. 6 in this case and delete files the width remains correct until you refresh or change directory.

**Comment by gave92** [comment]
@winston-de

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5334.
