### ISSUE TITLE
Cannot Open Files

### ISSUE THREAD

**Issue by 0wv** [files-community/Files#5309]
**Explain the bug**
Some files open without an issue, but in other folders none of the files open at all. I've reset, uninstalled and reinstalled and tried everything to try fix the issue. At first i thought it was the file size being over 1kb that caused the issue, but that doesn't seem to be the case!

**To reproduce**
1. Go to 'Any File'
2. Click on 'Any File'
3. Scroll down to 'Any File'
4. See the error

**Expected behavior**
The file to open

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6705227/debug.txt)

**System Information**
 - OS Version: Windows 10 10.0.18363 Build 18363
 - App version: 1.5.0.0

**Additional comment**
N/A

**Comment by ElbowBaggins** [comment]
@0wv Might wanna check out #2299. I had a similar issue.
