### ISSUE TITLE
Feature: Keyboard shortcuts to move between sibling folders

### ISSUE THREAD

**Issue by CodedNil** [files-community/Files#5310]
**Is your feature request related to a problem?**
At the moment the quickest way to move to sibling folders is with the address bar dropdowns, which is far slower than a keybind would be.

**Describe the solution**
Shortcuts to move up and down between sibling folders, similar to the drop down menu when clicking the arrow in the address bar. Perhaps alt-pageup/down.
Ideally would display the drop down for a few seconds after using the keybind so you can view the folder structure as you move through it.
![image](https://user-images.githubusercontent.com/5075747/123212870-3f400600-d4bd-11eb-9f28-df407067c937.png)

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish easily moving between sibling folders | Must |

**Comment by Josh-65** [comment]
Asking @yaichenbaum for approval.

**Comment by yaira2** [comment]
Given all the different ways of sorting folders, what's the best way to determine which folder to switch to next?

**Comment by yaira2** [comment]
@CodedNil do you have any thoughts on how this would work? Given all the different ways that items can be sorted, I'm not sure how to move forward with this feature.
