### ISSUE TITLE
Save Layout Mode/Sorting for folders

### ISSUE THREAD

**Issue by Grizzlywolf** [files-community/Files#5311]
**Problem:**
If I open a folder, set a different Layout Mode, sort by different column, then move to a different folder/close tab and reopen folder, the layout mode will be reset. 
**Solution:**
It should save a preferred Layout Mode and sorting for each folder, like Windows Explorer does.

**Comment by XPoppyX** [comment]
Do you have this option enabled?
![Captura de pantalla 2021-06-24 090419](https://user-images.githubusercontent.com/61259627/123267586-2dfdf600-d4cb-11eb-98bf-f3f8f2da7a8d.png)

**Comment by Grizzlywolf** [comment]
> Do you have this option enabled?
> Settings > Files and folders
> ![Captura de pantalla 2021-06-24 090419](https://user-images.githubusercontent.com/61259627/123267586-2dfdf600-d4cb-11eb-98bf-f3f8f2da7a8d.png)

Hmm, I actually do. So this is a bug I guess. I reproduced this with option enabled: I go to Downloads folder, set layout and sorting, open an new tab, open Downloads folder. The layout and sorting is reset. Logs in attachment.
[debug.txt](https://github.com/files-community/Files/files/6709570/debug.txt)

**Comment by gave92** [comment]
Files version? I believe we added this after version 1.5.0.0

**Comment by Grizzlywolf** [comment]
> Files version? I believe we added this after version 1.5.0.0

Yea, it's that version, downloaded from Store. But as I explained above, this is a bug.

**Comment by gave92** [comment]
Thanks for confirming, this is fixed in latest code.
