### ISSUE TITLE
QuickLook should react to different file selected

### ISSUE THREAD

**Issue by Grizzlywolf** [files-community/Files#5312]
**Problem:** 
In Windows Explorer, QuickLook usually automatically opens a preview of newly selected file while QL window is opened. Here, I still have to press Space to see the preview of newly selected file, selecting a different file doesn't automatically change the preview. 
**Solution**
Maybe this behaviour should be changed so that QuickLook automatically reacts to selected file?

**Comment by gave92** [comment]
Merging with #1373
