### ISSUE TITLE
Port to other OSes using uno.platform

### ISSUE THREAD

**Issue by DaniellMesquita** [files-community/Files#5313]
Reference:
https://play.google.com/store/apps/details?id=uno.platform.calculator
https://calculator.platform.uno/

**Comment by yaichenbaum** [comment]
Thank you for opening this feature request, we have looked into UNO in the past and someone even wrote a blog post on porting the app https://blog.lextudio.com/migrating-files-uwp-to-uno-part-i-ee20c4b0084a. If someone wants to explore this further, we would love to work together with them, but it's not something we plan on doing as our focus is on providing the best file manager experience for Windows.
