### ISSUE TITLE
Support to Windows Explorer extensions such as Tortoise Git

### ISSUE THREAD

**Issue by DaniellMesquita** [files-community/Files#5315]

**Comment by gave92** [comment]
Windows Explorer context menu items are supported and should show in the context menu in Files. Is this what you mean by extensions?

**Comment by yaichenbaum** [comment]
We need a little more information from you in order to investigate this issue, please reopen this issue once you have filled out the issue template.

**Comment by masta** [comment]
This is probably related to #8633 as the TortoiseGIT/SVN items aren't shown in the context menu on empty folder areas.
