### ISSUE TITLE
Right clicking white space uses old right menu

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5317]
**Expected behaviour**
It should use the current one that's on folders and files.

**Screenshots**
![image](https://user-images.githubusercontent.com/26977075/123306736-91af1000-d519-11eb-9dc0-712060bd2f33.png)

**System Information**
 - OS Version: Windows 10 20H2 19042.1055
 - App version: v1.5.46

**Comment by yaichenbaum** [comment]
Thank you for opening this issue, this is by design.

**Comment by josh-65** [comment]
really it make consistency very bad

**Comment by yaichenbaum** [comment]
@josh-65 The context menus are actually the same, the primary actions you see when right clicking on an item aren't available when right clicking in a blank space.

**Comment by geetanshpancholi** [comment]
That is a problem of Windows and not the app.
