### ISSUE TITLE
Cant Acces Program Folder on C:

### ISSUE THREAD

**Issue by Waldehyd** [files-community/Files#5320]
**Explain the bug**
I can't copy any files into the Default Program Folder on my C: Drive and I can't create any new folders in there either.

**To reproduce**
1. Go to C:/Program Files
2. Create new Folder or Copy folder in there
3. Nothing happens

**Expected behavior**
Files are created/copied.

**Logfile**
The debug log isnt containing anything regarding this Problem, it files just like nothing is happening at all.

**Screenshots**
Add screenshots to help explain your problem if needed.

**System Information**
 - OS Version: [e.g. Windows 10  Pro 21H1

**Comment by josh-65** [comment]
if you are on 1,5 this isnt implemented. it will be for v2
