### ISSUE TITLE
Ongoing task - progress bar

### ISSUE THREAD

**Issue by Wre2** [files-community/Files#5321]
**Is your feature request related to a problem?**
Yes there is no progress bar in ongoing task area as copying files or moving it. It is impossible to know if the files are copying or not.

**Describe the solution**
If there is a progress bar is included in the task list it will be helpful or maybe open a copy dialog box as windows.

**Describe alternatives you've considered**
Maybe include a visual accent in window bar or below like a line or something .

**System Information**
 - OS Version: [e.g. Windows 10 20H2 19042.804] (Press WIN + PAUSE/BREAK, use the copy button at the bottom)
 - App version: [e.g. v1.0] (In the app, go to Settings -> About, the version is shown at the top)

**Comment by josh-65** [comment]
for v2 the icon will have a ring to show overall progress. like edge does now. there's a percentage and visual ring for individual task too.
