### ISSUE TITLE
Inconsistent Files crashes/instabilities

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5322]
**Explain the bug**
Using 1.5.46 I have had random crashing (creating, deleting, moving between files and folders), app freezes (UI not doing anything on mouse input), Right clicks not responding. They are all different things I do with same results.

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6712346/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6712347/debug_fulltrust.log)

**System Information**
 - OS Version: Windows 10 21H1 19043.1055
 - App version: v1.5,46

**Comment by yaichenbaum** [comment]
@josh-65 Can you open an issue for each action that causes the app to crash? This will help us better investigate the individual issues.

**Comment by josh-65** [comment]
Doesn't crash opening the log folder anymore. I also can not consistently reproduce the crashes.

Updated logs for 1.5.46
[debug_fulltrust.log](https://github.com/files-community/Files/files/6779731/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/6779734/debug.log)

**Comment by josh-65** [comment]
Can i ask why this was closed?

**Comment by yaichenbaum** [comment]
@josh-65 maybe I misunderstood but I thought you said the issue was resolved.

**Comment by josh-65** [comment]
only the log folder crashing

**Comment by yaichenbaum** [comment]
Can you open a separate issue for each crash so we can properly track them?

**Comment by josh-65** [comment]
il try but there quite inconsistent. usually one offs
