### ISSUE TITLE
Status stuck on 0%

### ISSUE THREAD

**Issue by awesomelewis2007** [files-community/Files#5323]
**Explain the bug**
The status % won't move when moving folders or files 

**To reproduce**
1. get big file 
2. open the ongoing tasks box

**Expected behaviour**
The status bar to move

**Logfile**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6717817/debug_fulltrust.txt)

**Screenshots**
![image](https://user-images.githubusercontent.com/60709927/123461848-80313b00-d5e1-11eb-9dd3-411908cd3eec.png)

**System Information**
Processor	Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz   2.59 GHz
Installed RAM	16.0 GB (15.9 GB usable)
System type	64-bit operating system, x64-based processor
App version: 1.5.0.0

**Additional comment**
The problem doesn't go away after restarting

**Comment by winston-de** [comment]
Were you moving one item, if so how long did you wait? At the moment, progress for individual items is not tracked, so it won't change until the operation has completed.

**Comment by gave92** [comment]
Merging with #2543.
