### ISSUE TITLE
Context menu crashes

### ISSUE THREAD

**Issue by MuhammadAshouri** [files-community/Files#5326]
When I'm trying to right click a file to open context menu suddenly application crashes.
All settings are default values

**Comment by gave92** [comment]
Thanks for the report. Please add Files version to the description and upload the debug files:
- You can access them from Settings->About->Open log location. 
or 
- Copy the debug.log and debug_fulltrust.log from the following directory, and upload the files here.
`%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`
