### ISSUE TITLE
Libraries don't work properly

### ISSUE THREAD

**Issue by DeanKellham** [files-community/Files#5330]
**Explain the bug**
When activating the Libraries option, the libraries do not display libraries, but instead display single folders from within the %userprofile% folder.

**To reproduce**
1. Go to Settings
2. Go to Preferences
3. Enable "Show library section on the sidebar"
4. Click back
5. Expand "Libraries" on the sidebar
6. Click on any library
7. Note that the Windows Library is not displayed, and instead you have been navigated to the %userprofile% folder.

**Expected behavior**
The libraries displayed should be the Windows Libraries. This feature allows you to display the contents of multiple locations within one virtual folder.

**Logfile**
Upload the log file here for us to understand your issue better. 
- You can access it from Settings->About->Open log location. 
or 
- Copy the debug.log and debug_fulltrust.log from the following directory, and upload the files here.
`%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 

**Screenshots**
Add screenshots to help explain your problem if needed.

**System Information**
 - OS Version: Device name	DESKY
Processor	Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz   3.41 GHz
Installed RAM	16.0 GB
Device ID	9C784FBB-C885-43C5-986F-6BA925B84665
Product ID	00330-80000-00000-AA761
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

 - App version: 1.5.0.0

**Additional comment**
Add any other comment about the problem here. Does this problem happen again after restarting the app?

**Comment by gave92** [comment]
Thanks for this report. Proper support for libraries has been added in Files v2 (currently in beta).
