### ISSUE TITLE
Random crash when oping a .bat file in C: drive

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5331]
**Expected behaviour**
Shouldn't crash

**Logfile**
[debug_fulltrust.log](https://github.com/files-community/Files/files/6721986/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/6721987/debug.log)

**System Information**
 - OS Version: Windows 10 21H1 19043.1088
 - App version: v1.5,46

**Comment by haneenmahd** [comment]
Not only .bat files 
It crashes when opening binaries and executables.

**Comment by josh-65** [comment]
Doesn't crash with .bat files in 1.5.62 anymore. I had never had an issue with exe on either version though.
