### ISSUE TITLE
Crash when opening log folder

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5332]
**Explain the bug**
As the title says another thing is that the log files rapidly appear and disappear before crashing.

**To reproduce**
1. Go to Settings
2. Click on About
3. Click on Open logs
4. Wait a bit
5. see "Something when wrong" notifications 

**Expected behaviour**
Shouldn't crash

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6721993/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6721994/debug_fulltrust.log)

**System Information**
 - OS Version: Windows 10 21H1 19043.1088
 - App version: v1.5,46

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
