### ISSUE TITLE
Volume usage is unreadable when using dark mode

### ISSUE THREAD

**Issue by CheeryLee** [files-community/Files#5336]
**Is your feature request related to a problem?**
When dark theme enabled in Windows, it's a bit tricky to understand how much space the volume is using. The usage line is unreadable, it's too dark.

**Describe the solution**
Make it brighter. I'd rather tell it's need to have a color inversion.

![image](https://user-images.githubusercontent.com/11297752/123609536-67ef3500-d808-11eb-8644-7e61442a278a.png)

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to accomplish easily determine volume usage | Must |

**System Information**
 - OS Version: Windows 10 Pro 21H1, build 19043.1052
 - App version: 1.5.0.0

**Comment by jczanfona** [comment]
Not in my case:
![image](https://user-images.githubusercontent.com/46503049/123610665-155e4a80-d801-11eb-8775-a006136553fb.png)

But I'm agree... it's to much dark
![image](https://user-images.githubusercontent.com/46503049/123610870-4cccf700-d801-11eb-8296-629eedbd4df7.png)

**Comment by yaichenbaum** [comment]
@CheeryLee It looks like you have a dark accent color, it's usually recommended to use a lighter accent color in dark mode to prevent these kinds of issues.

**Comment by CheeryLee** [comment]
@yair100 yeah, it makes sense. Changed it to blue and now it looks normal. But it's not properly suitable behaviour for me, 'cause I use accent color for window frames. Can we make a color swap for volume usage widget? Maybe there is a theme config that I can't find.

**Comment by yaichenbaum** [comment]
There are custom skins that can override the accent, other than that though, there isn't much we can change on our end.
