### ISSUE TITLE
Copy & Paste does not work in conjunction with Windows Remote Desktop

### ISSUE THREAD

**Issue by SC24Jan** [files-community/Files#5341]
As the title states, copy & pasting does not work in conjunction with Windows Remote Desktop. 
Not sure if this is a feature request or a bug.

**To reproduce**
1. Select a file/folder and copy it on the remote desktop.
2. Try to paste it in Files.
3. Nothing happens.

**Expected behavior**
The normal Windows Explorer just copy & pastes it, like from one local folder to another local one (separate windows with a progress bar shows the progress).

**Logfile**
Not needed, I think.

**Screenshots**
Also not needed.

**System Information**
 - Windows 10 21H1 19043.1081
 - App version: 1.5.0.0.

**Comment by SC24Jan** [comment]
Did not search first. There are a couple of tickets already explaining this issue.
My bad.

**Comment by gave92** [comment]
No problem, merging with #4136. Thanks for the report.
