### ISSUE TITLE
Missing Download Icon on Sidebar

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#5343]
**Explain the bug**
As I have just joined the insider program and downloaded it, I found out that the download icon was missing on the sidebar.

**To reproduce**
1. Open Files
2. See the missing download icon

**Expected behavior**
Show a download icon on the sidebar instead of a transparent background.

**Logfile**
Upload the log file here for us to understand your issue better. 
- You can access it from Settings->About->Open log location. 
or 
- Copy the debug.log and debug_fulltrust.log from the following directory, and upload the files here.
`%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 
[debug.log](https://github.com/files-community/Files/files/6737673/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6737676/debug_fulltrust.log)

**Screenshots**
![Missing Download Icon on Sidebar](https://user-images.githubusercontent.com/69080584/123894508-7fedc280-d988-11eb-8bd7-c13e67f7709a.png)

**System Information**
 - OS Version: Windows 10 21H1 OS Version 2009 (Build 19043.1081)
 - App version: v1.5.46.0

**Additional comment**
The download icon doesn't seem to appear although I have restarted the app. Additionally, I have also deleted the `cache.db`, `debug.log`, and `debug_fulltrust.log`, however it returns the same result.

**Comment by haneenmahd** [comment]
Are you sure you are up-to-date with the app?

I have never experienced something like this

**Comment by stanleyowen** [comment]
Hi @haneenmahd,

Firstly I would like to say thank you for your response and it seems this issue hasn't been solved yet. I have tried re-installing the app from Microsoft Store, and also check for the app updates, it still shows up the missing download icon.

![image](https://user-images.githubusercontent.com/69080584/124342074-51bbed00-dbeb-11eb-8db5-a0aa4c4fa618.png)
![image](https://user-images.githubusercontent.com/69080584/124342084-6304f980-dbeb-11eb-88ae-f9ec3d27b838.png)

**Comment by josh-65** [comment]
you can try use file explorer and set the icon again for the downloads in your user directory

**Comment by stanleyowen** [comment]
After resetting the `hidden` attributes in folder properties, the download icon is back. Thanks!
