### ISSUE TITLE
Linked Files and Folder Missing

### ISSUE THREAD

**Issue by eXplOiD1** [files-community/Files#5344]
Hello,
I have the Problem that Files dont show me my Linked Files and Folders,
I cant find an Option to Turn on Link Folders or Files

Windows 10
Lastest version from today V1.5

Thanks for the Help

**Comment by gave92** [comment]
Hello thanks for this report. Could you add more details? Do shortcut files do not appear in Files? Cold you show what's different between Files and Windows Explorer?
Also please upload the app's debug files.
