### ISSUE TITLE
Columns settings not useful & column sizes are not saved

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5353]
**Is your feature request related to a problem?**
Currently columns have to be set for every directory making quite pointless to have it customisable.

**Describe the solution**
It should pull what columns to show from the main drive (C: have columns set and all directory's in it should be the same)/cloud drive

**Scope**
| Capability | Priority |
| :---------- | :------- |
| Have columns be the same for all directories | Must |
| Have columns be the same per drive/cloud drive | Should |

**Comment by gave92** [comment]
Please try the following:
- Turn off "Enable individual preferences for folders" in Files Settings
- Show/hide any column you wish
- Turn back on "Enable individual preferences for folders" in Files Settings

**Comment by josh-65** [comment]
that worked but it not very user friendly, I also discoved that the column sizes don't save with it on or off.

**Comment by josh-65** [comment]
I have an idea about implementing an easier way to apply columns to all directory's. The should be a check mark button in the list. If users want to apply columns to all directory's they right click, select the button, then change the settings.
