### ISSUE TITLE
Request to join the default application function

### ISSUE THREAD

**Issue by jkyiyue** [files-community/Files#5359]
_**I am Chinese, the following is machine translation, which may not be accurate**_

**Is your feature request related to a problem?**
Yes.

**Describe the solution**
Request to join the default application function.

**System Information**
 - OS Version:Windows 10 21H1 19043.1081
 - App version: v1.5.0.0

**Comment by yaichenbaum** [comment]
We are having trouble understanding this feature request, can you provide more information?
