### ISSUE TITLE
the bottom scrollbar almost hides the last file n the detail view

### ISSUE THREAD

**Issue by Neikon** [files-community/Files#5360]
**Explain the bug**
the bottom bar almost hides the last file in the detail view. the area available to interact with the file ends up being half of what it should be.

**To reproduce**
1. Go to a folder with many files
2.  activate details view
3. reduce the window until the bottom scrollbars appear.
4. go to the last file and you will see that the area available to interact with the file is reduced because of the bottom scrollbar.

**Expected behavior**
the bottom scrollbar should not reduce the area available to interact with the last file or there should be an empty area so that the opening of the bottom scrollbar does not overlap with the last file.

**Logfile**
i think in this case is not necesary. if necessary, let me know and I will upload it without any problem.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/1765319/124311170-9ef97980-db6d-11eb-8e06-c331a9c984b7.png)
![imagen](https://user-images.githubusercontent.com/1765319/124311184-a4ef5a80-db6d-11eb-8e08-055c7ac7a597.png)

**System Information**
 - OS Version: Edición	Windows 10 Pro
                      Versión	21H1
                      Instalado el	‎18/‎12/‎2020
                      Compilación del sistema operativo	19043.1052
                      Experiencia	Windows Feature Experience Pack 120.2212.2020.0

 - App version: 1.5

**Comment by mdtauk** [comment]
Maybe add an empty item, or just some bottom margin so the bottom of the view is always clear of the scrollbar

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5396.
