### ISSUE TITLE
Add group by feature in folders

### ISSUE THREAD

**Issue by cyanidecygnet** [files-community/Files#5361]
**Is your feature request related to a problem?**
Currently, folders with too many files and sub folders can get too messy to look through.

**Describe the solution**
Explorer on windows allows grouping in folders. This allows for faster browsing when looking for items from particular time periods or types for example by having items grouped into drop down tabs that can be minimised. 

![image](https://user-images.githubusercontent.com/86849866/124312346-7f387480-dbb2-11eb-8593-9ccf586598f1.png)

This feature can be directly copied from explorer with the addition of items such as grouping by tags, properties or custom grouping for further improvement and functionality. 

![image](https://user-images.githubusercontent.com/86849866/124311899-cbcf8000-dbb1-11eb-9e86-e478c0acf878.png)

**Describe alternatives you've considered**
Sorting by tags in detail view does work but can involve a significant amount of scrolling to reach items, and overlooking a particular file is still a problem using this method.

**Scope**

| Capability | Priority |
| :---------- | :------- |
| Grouping by name, type, date, size and tags | Must |
| Folder specific grouping | Must |
| Custom file grouping specific to folder | Could |

**Comment by gave92** [comment]
Implemented in beta version.
