### ISSUE TITLE
Use Windows 11 icons

### ISSUE THREAD

**Issue by DeveloperWOW64** [files-community/Files#5365]
**Describe alternatives you've considered**
It could be possible to have not just Windows 11 icons, but be able to have an icon set.

**Scope**

| Capability | Priority |
| :---------- | :------- |
| The default icon scheme for Files must be the WIndows 11 ones, (for recycle bin, this pc, documents, etc.) with an option to revert them to the Windows 10 icons| Must |
| We should allow developers of themes to also be able to create icon packs| Should |

**System Information**
 - OS Version: Windows 10 Home 21H1 19043.1052

 - App version: 1.5.46.0

**Comment by yaichenbaum** [comment]
@DeveloperWOW64 All this is already possible in v1.5.46, can you provide more information on which part isn't working?

**Comment by DeveloperWOW64** [comment]
What do you mean 'Which part isn't working?

**Comment by pc-v2** [comment]
You have to use latest Windows 10 Insider build (21390)

**Comment by mdtauk** [comment]
The team will not be able to bundle the Windows 11 icons into the app, so you'll have to use Windows 11 if you want to see those icons.

**Comment by yaichenbaum** [comment]
In addition to what @mdtauk said, you will be able to customize icons (via File Explorer) and they will show up in Files.
