### ISSUE TITLE
Sort alphabetically

### ISSUE THREAD

**Issue by brodie1010** [files-community/Files#5373]
This was initially the reason i went looking for a new explorer, when iv unzipped a folder the extracted folder wont show directly underneath the og zip.This has bugged me for a while in windows, im happy to find this software because its beautiful, super impressed! If you can find a remedy for this that would be huge. so basicly make an option for all file types to be sorted alphabetically, just an extra tile option or something or menu selection something simple please.Brodie

**Comment by josh-65** [comment]
Files already can soft alphabetically by clicking on the name option for A-z or z-A. You can sort folder alongside files in the settings > file and folders > list directory's along side files

**Comment by brodie1010** [comment]
awwhhhhh, nice.Thanks for letting me know that's so good.I didn't really go
through any documentation.
