### ISSUE TITLE
New folder or items are not getting created

### ISSUE THREAD

**Issue by thedeveloper-sharath** [files-community/Files#5374]
**Explain the bug**
When you try to create a new folder or file using the context menu or the keyboard shortcut, nothing happens

**To reproduce**
1. Go to Any folder
2. Right-click and new - > folder or ctrl  + shift + n
3. Give name and press enter

**Expected behavior**
The folder or the file should be created

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6763950/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6763951/debug_fulltrust.log)

**Screenshots**
Add screenshots to help explain your problem if needed.

**System Information**
 - OS Version: 
      Edition: Windows 11 Home
      Update: 21H2
      Installed on: ‎28-‎06-‎2021
      OS build: 22000.51
      Experience: Windows Feature Experience Pack 421.16300.0.3

 - App version: 1.5.46
**Additional comment**
Also, when you enter a folder that has a file that keeps on changing(like the log folder for files). The page refreshes extremely quickly and causes files to crash

**Comment by yaichenbaum** [comment]
Merging with #5225.
