### ISSUE TITLE
navigate with arrows on column view / open it with just a single click

### ISSUE THREAD

**Issue by Vanillabacke** [files-community/Files#5375]
It would be nice, if you can navigate through the file structure with the arrow keys within the column view.
And in addition it feels wrong in that column view, to double click to open the next folder. I know you can set it in the global settings with an single click. but i would prefer it like in the mac finder.

maybe there should be an settings page for each view, how you would prefere to open the folder (single or double click)

Column View:
- single click on a folder should open it directly
- navigating with up and down arrow in the column should open the folder directly
- selected folder with arrow right should jump into the selected folder
- arrow left should jump into the parent folder

**Comment by yaichenbaum** [comment]
Fyi @TyJOrtiz

**Comment by Svk1190** [comment]
It would be great to have single click for the column view, and double click for the other views.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7425
