### ISSUE TITLE
Some translated strings won't fit on their place

### ISSUE THREAD

**Issue by BanCrash** [files-community/Files#5376]
I have translated the remaining lines of ES-ES (Spain spanish) and I found that in some places those strings got cut.

Security properties:
![image](https://user-images.githubusercontent.com/11770760/129962301-bcced470-0214-41c7-942c-cccc2bb9e27f.png)
Should show "Mostrar el contenido de la carpeta". Since this string is copied literally from Windows explorer security properties, I think this string should stay untouched.

Easy solution is to add more space to make it fit.

EDIT: Solved issues:

<del>Another on about:</del>

![image](https://user-images.githubusercontent.com/11770760/129962249-9d98a6fe-6def-48cc-bb9a-81a2f33bb39e.png)

<del>Should show "Política de privacidad".</del>

<del>Besides, I found another incomplete string on settings, on preferences:</del>

![image](https://user-images.githubusercontent.com/11770760/125179065-fd1c0180-e1ea-11eb-99d9-70d1f02771d6.png)

<del>Settings:
![image](https://user-images.githubusercontent.com/11770760/124503315-98fdd580-ddc5-11eb-9197-e08d4f6f2935.png)
Should show "Archivos y carpetas". Not much more space needed, but a little.
</del>

**Comment by yaichenbaum** [comment]
@BanCrash is this still an issue?

**Comment by BanCrash** [comment]
> @BanCrash is this still an issue?

Yes, but only partially. I've updated the original post to clarify what is solved and what is still an issue.

**Comment by BanCrash** [comment]
Closing this since it's fixed on last release.
