### ISSUE TITLE
Crash when Right-clicking

### ISSUE THREAD

**Issue by Spammivication** [files-community/Files#5380]
**Explain the bug**
Write a clear description of what the bug is.

The "Files"-App is crashing when i right-click in any destination other than the start-screen(New Tab).

**To reproduce**
1. Go to 'C:\'
2. Right-Click on Any Folder
3. See the error

**Expected behavior**
Write a clear description of what you expected.

Opening of Right-click Menu.

**Logfile**

[debug.txt](https://github.com/files-community/Files/files/6775422/debug.txt)

**System Information**
Edition	Windows 10 Pro
Version	20H2
Betriebssystembuild	19042.1052
Windows Feature Experience Pack 120.2212.2020.0

- OS Version: [e.g. Windows 10 20H2 19042.804] (Press WIN + PAUSE/BREAK, use the copy button at the bottom)
 - App version: v1.5.0.0

**Additional comment**
Does this problem happen again after restarting the app?
Yes

**Comment by josh-65** [comment]
Try reinstalling the app from the Microsoft store.

**Comment by yaichenbaum** [comment]
This issue appears to be resolved in v2.0.34.
