### ISSUE TITLE
Operation Progress ring looks bad

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5382]
**Explain the bug**
The ring cuts off at the bottom, its not centre to the icon and look too big

**Screenshots**
![image](https://user-images.githubusercontent.com/26977075/124819322-07789a00-df64-11eb-824e-bf143a6b9866.png)

**System Information**
 - OS Version: Windows 10 20H2 19042.804
 - App version: v1.5.62

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5406.
