### ISSUE TITLE
Crashes when Setting Hidden Attribute in Favorites Tab

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#5386]
**Explain the bug**
App will crash or close unexpectedly when users trying to configure the hidden property inside the Favorites Tab (Home, Desktop, Downloads, Documents, and Recycle Bin).

**To reproduce**
1. Right click on the Favorite Tabs Menu (Home, Desktop, Downloads, Documents, or Recycle Bin)
2. Click on Properties
3. Check or uncheck the hidden attributes
4. Click Ok
5. See the error

**Expected behavior**
The app shouldn't crash or close unexpectedly.

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6782156/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6782159/debug_fulltrust.log)

**Screenshots**
![Crashes when Setting Hidden Attribute in Favorites Tab](https://user-images.githubusercontent.com/69080584/124875476-27a36a00-dff3-11eb-8a03-29362d0821ba.png)

https://user-images.githubusercontent.com/69080584/124875840-8bc62e00-dff3-11eb-9658-cf677c81ba10.mp4

**System Information**
 - OS Version: Windows 10 21H1 OS Version 2009 (Build 19043.1081)
 - App version: v1.5.62.0

**Additional comment**
This problem occurs although I have restarted the app. Note that sometimes the app won't crash for the first time after changing the hidden attribute, but it will do crash for the second, third, and further times.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5392.
