### ISSUE TITLE
Avoid Transition when Active Tabs is Clicked

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#5387]
**Explain the bug**
When users open a file/folder's properties, it will pop out a dialog which shows up a certain information about the file/folder. There are several tabs on the dialog, such as General, Security, and Details. When users click on the active tab (not the first child tab), there will be a transition from the first tab to the active tab.

**To reproduce**
1. Select a file or folder
2. Right click and click on Property
3. Click on the Security tab or Details tab
4. Now the active property will be set to that tab
5. Click again on the active tab
4. See the error

**Expected behavior**
Avoid transition when active tab is clicked.

**Screenshots**
![Avoid Transition when Active Tabs is Clicked](https://user-images.githubusercontent.com/69080584/124878269-1c9e0900-dff6-11eb-9c39-1547596e4728.gif)

**System Information**
 - OS Version: Windows 10 21H1 OS Version 2009 (Build 19043.1081)
 - App version: v1.5.62.0

**Additional comment**
This problem occurs although I have restarted the app.

**Comment by gave92** [comment]
+ @winston-de, related to #5329?

**Comment by winston-de** [comment]
I think the issue is we navigate to the page again every time the option is clicked even if the page is already active.

**Comment by gave92** [comment]
Also selection always goes briefly to the first tab:
https://user-images.githubusercontent.com/9673091/124959345-65b48400-e01b-11eb-98ea-ae7eb8d1e860.mp4

**Comment by winston-de** [comment]
> Also selection always goes briefly to the first tab:
> https://user-images.githubusercontent.com/9673091/124959345-65b48400-e01b-11eb-98ea-ae7eb8d1e860.mp4

I noticed this issue before #5329, so I don't think it's directly related. Would be nice to figure out and fix though.

**Comment by winston-de** [comment]
This may actually be an issue with the navigation view's ``SelectionFollowsFocus`` property, as it is reproducible in the xaml controls gallery. Setting it to disabled in Files fixes this issue. I'll make an issue there for this.

https://user-images.githubusercontent.com/59544401/125229048-c7c6f080-e28a-11eb-8ee7-a35ae5cb092d.mp4

**Comment by gave92** [comment]
We could set `SelectionFollowsFocus` to false till the bug is fixed. You can still navigate by keyboard, you just need to press Enter to navigate to the selected tab..

**Comment by stanleyowen** [comment]
Hi, I can't repro this issue again in v1.9.14.0 of Files, is this issue fully fixed? Thanks in advance!

**Comment by winston-de** [comment]
> Hi, I can't repro this issue again in v1.9.14.0 of Files, is this issue fully fixed? Thanks in advance!

Yes, SelectionFollowsFocus has been disabled as a workaround for this issue.

**Comment by yaichenbaum** [comment]
This is the expected behavior.

**Comment by yaichenbaum** [comment]
This issue appears to be resolved
