### ISSUE TITLE
Improve Button Hover Effect in About Section

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#5388]
**Is your feature request related to a problem?**
After exploring the app for a while after a fresh update, I found out that the About Section's button, which can be accessed through Settings > About (Submit Feedback, Release Notes, Documentation, etc), hover effects are alike with Windows 10 hover effect, however it would be great if there are some improvements on the hover effect.

Saw:

https://user-images.githubusercontent.com/69080584/125009047-fb88f700-e08d-11eb-8e89-93a29a4527fc.mp4

Expected:
![Improve Button Hover Effect in About Section](https://user-images.githubusercontent.com/69080584/125009141-23785a80-e08e-11eb-9497-c30b481bab20.gif)

**System Information**
- OS Version: Windows 10 21H1 OS Version 2009 (Build 19043.1081)
- App version: v1.5.62.0

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5391.
