### ISSUE TITLE
Command bar flyout goes off screen

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5389]
**Explain the bug**
A bit of the pop out goes of the left of the screen

**To reproduce**
1. move window to left
2. right click a file/folder on icon area
3. See the pop out off the screen

**Expected behaviour**
It should auto move to the closest position to cursor

**Screenshots**
![image](https://user-images.githubusercontent.com/26977075/125012218-c1a1fb80-e061-11eb-8534-764ee36dd9f1.png)

**System Information**
 - OS Version: Windows 10 21H1 19043.1088
 - App version: v1.5.62

**Comment by yaichenbaum** [comment]
@josh-65 Thank you for opening this issue, this a bug with the WinUI library so it might be better to open an issue on their repository.
Fyi @winston-de

**Comment by winston-de** [comment]
I filed an issue for this a while ago as well, however it seems to have gotten buried.
https://github.com/microsoft/microsoft-ui-xaml/issues/4881
