### ISSUE TITLE
Improve Custom Skin Dialog

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#5390]
**Is your feature request related to a problem?**
While trying to access the Appearance tab (Settings > Appearance) for Custom Skin, I discover the custom skin info dialog (an info button next to the custom skin) should be improved. Here are the details:
![Improve Custom Skin Dialog](https://user-images.githubusercontent.com/69080584/125017355-2a5a9980-e09d-11eb-94fe-888274191b7d.png)
![Improve Custom Skin Dialog](https://user-images.githubusercontent.com/69080584/125017469-68f05400-e09d-11eb-8c96-04472c53230a.png)

**Describe the solution**
The Custom Skin dialog should only consist of one color (dark gray or gray) instead of 2 colors.

**System Information**
 - OS Version: Windows 10 21H1 19043.1083
 - App version: v1.5.62.0

**Comment by yaichenbaum** [comment]
I believe this was an issue with WinUI that has since been resolved. Please let us know if it's still an issue in future preview builds.
