### ISSUE TITLE
Memorize item collapse states when closing and reopening Navigation menu

### ISSUE THREAD

**Issue by AkazaRenn** [files-community/Files#5397]
**Is your feature request related to a problem?**
When you have the items in Navigation menu un-collapsed, close Navigation and reopen it, you'll see all the items are collapsed. If you prefer some of them open, you have to manually do that again every time such thing happens.

**Describe the solution**
Memorize the collapse status for each of the items in the menu, restore them when Navigation menu is opened.

**System Information**
 - OS Version: Windows 11 Pro for Workstations 21H2 Build 22000.65
 - App version: 1.5.0.0

**Comment by gave92** [comment]
Merging with #4128.
