### ISSUE TITLE
Hard to drag an item when "Open items with a single click" is turned on

### ISSUE THREAD

**Issue by AkazaRenn** [files-community/Files#5398]
**Explain the bug**
Since the item cannot be dragged before getting activated, when "Open items with a single click" is turned on, you can only right-click onto it, close the context menu, then do the dragging. In File Explorer, the item will be activated when I do a LMB (left mouse button) down onto the file, enabling dragging instantly.

**To reproduce**
1. Go to "Settings" -> "Files and Folders"
2. Turn on "Open items with a single click"
3. Go to a random directory
4. Try dragging an item by simply holding down LMB

**Expected behavior**
The item is dragged

**System Information**
 - OS Version: Windows 11 Pro for Workstations 21H2 Build 22000.65
 - App version: 1.5.0.0

**Comment by gave92** [comment]
Thanks for this report. This is fixed in latest beta version.
