### ISSUE TITLE
Windows 11: Files cannot be installed offline

### ISSUE THREAD

**Issue by plorerfisfct** [files-community/Files#5399]
**Explain the bug**
Files cannot be installed on a freshly installed Windows 11.

**To reproduce**
1. Double click on the file: Files.Package_1.5.0.0_x86_x64.msixbundle
2. The installation window appears
3. Click on Install
4. Files can not be installed - App Installer failed to install package dependencies. Ask the developer for Microsoft.UI.Xaml.2.5 package.

![Capture](https://user-images.githubusercontent.com/87186277/125147485-e793d280-e12b-11eb-8fbd-3943eb3b81b4.PNG)

**Expected behavior**
I have been using Windows since Windows XP (released in year 2001). I am used to the possibility that user software for Windows can always be installed offline.

Here are some examples of what file managers I use under Windows for a very long time and can to this day and without problems always install it offline.

- [XYplorer](https://www.xyplorer.com/download.php) 
- [Multi Commander](http://multicommander.com/downloads)
- [Total Commander](https://www.ghisler.com/ddownload.htm)

![Capture 2](https://user-images.githubusercontent.com/87186277/125148003-94bc1a00-e12f-11eb-8dde-49b6e5214407.PNG)

**Logfile**
No log file available because Files generally cannot be installed offline.

**Screenshots**
Here is another screenshot with non file manager software for Windows. But in general it can also be installed offline. They are well-known video player software for users. In this case, I already installed it offline and started the video player software offline and there were no problems.

![Capture 3](https://user-images.githubusercontent.com/87186277/125148080-01371900-e130-11eb-95fd-46c34f2f605f.PNG)

**System Information**
 - OS Version: [Windows 11 21H2 22000.65]
 - App version: [v1.5]

**Additional comment**

**Comment by gave92** [comment]
Merging with #5176.
