### ISSUE TITLE
Add recently opened folders to Windows timeline

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#54]
Not critical but support for Windows Timeline would be nice as a bonus feature.

**Comment by soumyamahunt** [comment]
A toggle for user will be good, since some user might not want their timeline to be filled with folders.

**Comment by Jaiganeshkumaran** [comment]
This doesn't make sense anymore since now we add recently accessed folders to the jumplist. The timeline feature is best-used with multiple devices and directory paths will not be the same across devices.

**Comment by yaichenbaum** [comment]
A toggle would probably work best in this case. I mainly use one device, but I would still like to have the directories show in the timeline.

**Comment by yaichenbaum** [comment]
Merging with #2043.
