### ISSUE TITLE
Drag and Drop Files in Recycle Bin Cause Items Deleted Permanently

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#5404]
**Explain the bug**
Drag and drop deleted files in recycle bin will cause items deleted permanently.

**To reproduce**
1. Go to Recycle Bin (Make sure there are unused files which will be deleted permanently)
2. Drag one or more file(s) and drop it in the same context
3. File(s) deleted permanently

**Expected behavior**
Files shouldn't be deleted permanently and still exists in the recycle bin.

**Screenshots**

https://user-images.githubusercontent.com/69080584/125183422-c7a20300-e240-11eb-8cf4-90281642f82f.mp4

**System Information**
 - OS Version: Windows 10 21H1 Build 19043.1083
 - App version: v1.5.62.0

**Additional comment**
Does this problem happen again after restarting the app? Yes.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5406.
