### ISSUE TITLE
Differentiate Recycle Bin Icon when Empty or not

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#5405]
**Is your feature request related to a problem?**
As a windows user, everyone will realize (or not) that sometimes the recycle bin icon (located in Desktop) will be quite different when it is empty or not.

Empty Recycle Bin:
![Empty Recycle Bin](https://user-images.githubusercontent.com/69080584/125183615-21ef9380-e242-11eb-8856-62b74de3fdab.png)
Filled Recycle Bin:
![Filled Recycle Bin](https://user-images.githubusercontent.com/69080584/125183611-18fec200-e242-11eb-8200-1094874cbf06.png)

**Describe the solution**
It will be great if the recycle bin icon changes dynamically when the recycle bin is empty or not.

**Scope**

| Capability | Priority |
| :---------- | :------- |
| Recycle bin icon changes dynamically when the recycle bin is empty or not | Could |

**System Information**
 - OS Version: Windows 10 21H1 Build 19043.1083
 - App version: v1.5.62.0

**Comment by gave92** [comment]
Thanks for this report. Are you asking for a different recyclebin icon _on File sidebar_ when the bin is full? Or is the issue that the recyclebin on the desktop does not refresh when the bin is emptied from Files?

**Comment by stanleyowen** [comment]
Hi, I am asking for a different Recycle Bin icon on the sidebar when the bin isn't empty.

**Comment by mdtauk** [comment]
Does the app specifically pull a Recycle Bin icon from Shell32 or imageres, or does it query the OS for the current Recycle Bin state?

Not sure if this Win32 API is still relevant ``SHUpdateRecycleBinIcon``

**Comment by gave92** [comment]
Merging with #1089.
