### ISSUE TITLE
Sidebar fails to load on startup

### ISSUE THREAD

**Issue by crashmit** [files-community/Files#5408]
**Explain the bug**
Sometimes the sidebar doesn't load properly, when I start Files.

**To reproduce**
1. Start Files

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6797531/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6797532/debug_fulltrust.log)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/58466626/125207606-83891f80-e28d-11eb-8807-d773feea4b93.png)

**System Information**
 - OS Version: Win10 21H1 Build 19043
 - App version: 1.5.62
 
**Additional comment**
Doesn't happen everytime, usually a restart helps. The last time, I had it twice in a row, working on the third try.

**Comment by crashmit** [comment]
I found a workaround: closing and reopening the navigation pane reloads the contents, after which it works
![grafik](https://user-images.githubusercontent.com/58466626/125590782-fbd1eaa9-9724-417e-8aa3-c8aaea80c5ce.png)

**Comment by yaichenbaum** [comment]
@crashmit is this still an issue in v2.0.34?
