### ISSUE TITLE
NOT BUG something missed 

### ISSUE THREAD

**Issue by iskander93** [files-community/Files#5409]
**Explain the bug**
Write a clear description of what the bug is.

**To reproduce**
1. Go to '....'
4. See the error

**Expected behavior**
Write a clear description of what you expected.

**Logfile**
Upload the log file here for us to understand your issue better. 
- You can access it from Settings->About->Open log location. 
or 
- Copy the debug.log and debug_fulltrust.log from the following directory, and upload the files here.
`%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 

**Screenshots**
Add screenshots to help explain your problem if needed.

**System Information**
 - OS Version: [e.g. Windows 10 20H2 19042.804] (Press WIN + PAUSE/BREAK, use the copy button at the bottom)
 - App version: [e.g. v1.0] (In the app, go to Settings -> About, the version is shown at the top)

**Additional comment**
Add any other comment about the problem here. Does this problem happen again after restarting the app?

**Comment by iskander93** [comment]
just if you add column view (similar to mac os ). OR  files tree (like windows explorer)

**Comment by gave92** [comment]
Column view is already implemented.

**Comment by iskander93** [comment]
[I](url) mean something like this 
[https://i.stack.imgur.com/GiecU.jpg](url)

**Comment by iskander93** [comment]
> Column view is already implemented.

I mean something like that

![GiecU](https://user-images.githubusercontent.com/71032559/125529932-5d0bce9c-774f-4c6b-ae97-aa3a79f3906a.jpg)
 or

**Comment by gave92** [comment]
Like this =)

![image](https://user-images.githubusercontent.com/9673091/125587165-a161f310-621d-403d-89e2-1272c6402888.png)
