### ISSUE TITLE
Failed to Rename File's Extension

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#5414]
**Explain the bug**
While trying to rename extension's of a file, nothing changes.

**To reproduce**
1. Rename a file's extension
2. Click on Enter and Ok
3. See the error

**Expected behavior**
Files' extension should changed.

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6800040/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6800041/debug_fulltrust.log)

**Screenshots**

https://user-images.githubusercontent.com/69080584/125260559-a584af80-e32a-11eb-9836-7f367eaab110.mp4

**System Information**
 - OS Version: Windows 10 21H1 19043.1083
 - App version: v1.5.62.0

**Additional comment**
Does this problem happen again after restarting the app? Yes

**Comment by gave92** [comment]
Fixed with #5403.
