### ISSUE TITLE
Add Overflow Property on Property Layout

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#5415]
**Explain the bug**
When right clicking on a file, there will be a pop up dialog which shows up several action button such as Rename, Properties, etc. However in some cases, the property layout goes off the screen.

**To reproduce**
1. Right click on a file, which is located around the middle of your screen
2. Some buttons such as Rename, Properties, etc are missing

**Expected behavior**
Adding an overflow property will be great.

**Screenshots**
![Add Overflow Property on Property Layout](https://user-images.githubusercontent.com/69080584/125261508-863a5200-e32b-11eb-868b-7a3c596f2749.png)

**System Information**
 - OS Version: Windows 10 21H1 19043.1083
 - App version: v1.5.62.0

**Comment by gave92** [comment]
Thank you for opening this issue, this a bug with the WinUI library.
