### ISSUE TITLE
Right Click Menu Inconsistent

### ISSUE THREAD

**Issue by mr-september** [files-community/Files#5418]
**Explain the bug**
Right Click menu is inconsistent, the most notable one is "Open with..." is only sometimes present. I have not been able to find any replicable pattern to this behaviour.

**To reproduce**
1. Go to any file, opened in "Files" app.
2. Right click
3. Look for "Open with..." 
4. It's absent

**Expected behavior**
"Open with..." to always be present.

**System Information**
 - OS Version: Windows 10 20H2 19042.1052
 - App version: 1.5

**Additional comment**
Add any other comment about the problem here. Does this problem happen again after restarting the app?

Yes, sometimes it goes away but I haven't been able to find out exactly why/how.

**Comment by gave92** [comment]
Appears to be fixed in 1.9.18 (beta version)
