### ISSUE TITLE
Newly created items or renamed items don't show up

### ISSUE THREAD

**Issue by chingucoding** [files-community/Files#5420]
**Explain the bug**
Write a clear description of what the bug is.

When creating a new file using Right click -> New -> [file type], the item does not show up in the list, you have to manually reload the view for it to show up. This also seems to apply to items when renaming the file extension. See following gif:

![Gif showing creation of new item and said item only showing up after reloading the view.](https://user-images.githubusercontent.com/16122379/125490696-1795880e-b3f1-42fb-98c5-33d1a1ef36c7.gif)

**To reproduce**
1. Go to folder
2. Right click
3. Click on new
4. Create new file

**Expected behavior**
Write a clear description of what you expected.
Elements should show up.
**Logfile**
Upload the log file here for us to understand your issue better. 
- You can access it from Settings->About->Open log location. 
or 
- Copy the debug.log and debug_fulltrust.log from the following directory, and upload the files here.
`%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 

**Screenshots**
See above.

**System Information**
 - OS Version: Windows 10 Education, build 19043
 - App version: https://github.com/files-community/Files/commit/62b2086cc0e2cb3dce14bfed3b00892db78700c8

**Additional comment**
Add any other comment about the problem here. Does this problem happen again after restarting the app?

**Comment by puppetsw** [comment]
Looks to be fixed?

OS Version: Windows 11
App version: 2.1.2.0

**Comment by yaichenbaum** [comment]
@chingucoding This issue should be resolved in the preview version. https://files.community/download/preview
