### ISSUE TITLE
Media controls on video preview are not completely showed

### ISSUE THREAD

**Issue by BanCrash** [files-community/Files#5422]
**Explain the bug**
If you use the preview of a video, you will see the media controls cutted (see screenshot for a better explanation).

**To reproduce**
1. Enable preview pane
2. Click on a video file
3. See the behaviour on the screenshot

**Expected behavior**
I think there is another media control that has to be showed, and also should end with rounded corners.

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6811888/debug.txt)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6811889/debug_fulltrust.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/11770760/125521732-6157d1e7-d98d-4f05-a94d-1768c593e178.png)

**System Information**
 - OS Version: Windows 10 Pro 21H1 19043.1081 Windows Feature Experience Pack 120.2212.3530.0
 - App version: 1.5.62.0

**Additional comment**
This problem still happen after restarting the app.

**Comment by winston-de** [comment]
Thanks for the feedback. Closing as this is a WinUI bug https://github.com/microsoft/microsoft-ui-xaml/issues/5441.
