### ISSUE TITLE
Root folder without icon doesn't have an icon on sidebar (favorites)

### ISSUE THREAD

**Issue by BanCrash** [files-community/Files#5423]
**Explain the bug**
EDITION: It seems that they indeed have icons, but Files can't get it. This also happens with MTP root folders. So the bug is some root folders (smb, MTP) can't get their icon in Files.

**To reproduce**
1. Go to the root folder of a SMB / MTP folder. I'm using the root folder of a Synology NAS with SMB.
2. Right click and pin to favorites.
3. Root folder pinned to sidebar will not have an icon, but if you repeat those steps with subfolders, those will have it (check screenshot for better explanation).

**Expected behavior**
Should have an icon. Maybe a standard icon for any folder that doesn't have an icon?

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6812040/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6812041/debug_fulltrust.log)

**Screenshots**
Windows explorer:
![image](https://user-images.githubusercontent.com/11770760/126789493-1d3c4e44-6840-468c-b50c-ec2199b486ed.png)

Files:
![image](https://user-images.githubusercontent.com/11770760/126789542-ce034820-e76f-4e93-b407-2e53f53cb639.png)

**System Information**
- OS Version: Windows 10 Pro 21H1 19043.1081 Windows Feature Experience Pack 120.2212.3530.0
- App version: 1.5.62.0

**Additional comment**
This problem still happen after restarting the app.

**Comment by stanleyowen** [comment]
This issue will happen when the hidden attribute is set. Try to uncheck the hidden attribute will maybe solve this issue.

**Comment by BanCrash** [comment]
> This issue will happen when the `hidden` attribute is set. Try to uncheck the `hidden` attribute from Properties > Hidden, this method works for me.

Hello, thanks for the answer, but there is no properties for smb folders, or at least for this folder.

In Windows explorer there is no option of "Properties", and on Files there is, but if I click on it nothing happens.
