### ISSUE TITLE
Bug found in Line 160 of App.xaml code

### ISSUE THREAD

**Issue by AlfarexGuy2019** [files-community/Files#5426]
**Explain the bug**
Bug found in Line 160 of Files App.xaml in v1.5.65

**To reproduce**
1. Go to 'App.xaml'
2. Scroll down to 'Line 160'
3. See the error

**Expected behavior**
N/A

**Logfile**
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/78948152/125568827-b64f58db-b883-48b8-9b07-7afb328fcb63.png)

**System Information**
 - OS Version: [e.g. Windows 10 21H1 19043.701] (Press WIN + PAUSE/BREAK, use the copy button at the bottom)
 - App version: [e.g. v1.5.65 Dev] (In the app, go to Settings -> About, the version is shown at the top)

**Additional comment**
N/A

**Comment by winston-de** [comment]
Sometimes VS shows that there are errors when there are not. Does it fail to build with the same error if you press Build -> Build solution?

**Comment by AlfarexGuy2019** [comment]
> Sometimes VS shows that there are errors when there are not. Does it fail to build with the same error if you press Build -> Build solution?

It fails, yes.

**Comment by winston-de** [comment]
Maybe try build -> clean solution, then building again. Looking at the pipeline when that line was introduced, there isn't a build error, and it also builds without errors for me as well.

https://github.com/files-community/Files/runs/3054999781

**Comment by gave92** [comment]
Closing as this is not an issue with Files. If you have trouble building the app from source feel free to ask here for help here or on Discord.
