### ISSUE TITLE
Avoid Auto Scrolling while Selecting Multiple Files in Details View

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#5428]
**Explain the bug**
While trying to select multiple files and or folders which has *y-overflow* will cause the screen to scroll to top in Details View.

**To reproduce**
1. Open Folder which contains more than 15 items
2. Scroll down and select 2 until 3 files in the bottom
3. See the error

**Expected behavior**
Avoid auto scrolling while selecting multiple files in details view.

**Screenshots**

https://user-images.githubusercontent.com/69080584/125637121-d76e2160-3852-4838-873f-ca3d84771e9f.mp4

**System Information**
 - OS Version: Windows 10 21H1 19043.1083
 - App version: v1.5.62.0

**Additional comment**
Does this problem happen again after restarting the app? Yes

**Comment by gave92** [comment]
@winston-de Can you reproduce this on main? Has this been fixed in #5396?

**Comment by winston-de** [comment]
Seems like it may have been, I can't reproduce it anymore.

**Comment by gave92** [comment]
@stanleyowen is this fixed for you in Files v1.5.67.0?

**Comment by stanleyowen** [comment]
Hi @gave92, this issue has been solved in Files v1.5.67.0, thank you for the awesome services!
