### ISSUE TITLE
Files-Dev icons not showing

### ISSUE THREAD

**Issue by DeveloperWOW64** [files-community/Files#5429]
**Explain the bug**
In Files-Dev, (the gh build) the icons on the sidebar do not show. See picture below:

**Expected behavior**
I expect the icons to render and display on the sidebar

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6817824/debug.log)
debug_fulltrust.log file does not contain content.

**Screenshots**
![image](https://user-images.githubusercontent.com/71598437/125665000-44d58f4e-1655-47db-8d71-d66a17cedfed.png)

**System Information**
 - OS Version: Windows 10 21H1 19043.1083
 - App version: Files-Dev Version 1.5.45.0

**Comment by gave92** [comment]
This happens when building the app with VS 16.10. @yair100 do you know which versions work?

**Comment by yaichenbaum** [comment]
@gave92 I'm still on an older version of Visual Studio so it's working for me. I believe the issue was reported and will be fixed in a future version, but for now, you can build in release mode as a workaround.

**Comment by gave92** [comment]
@DeveloperWOW64 could you try adding the following to the uwp project file ("Files.csproj") and see if the issue is solved (without the need to build in release mode)?
```xml
<PropertyGroup>
    <UseAppLocalCoreFramework>true</UseAppLocalCoreFramework>
</PropertyGroup>
```

**Comment by duke7553** [comment]
@gave92 Can definitely confirm those lines fix it for me (at least on VS2022)

**Comment by gave92** [comment]
@duke7553 thanks for confirming, we can add this workaround in `main` but I'd suggest we only add it to the Debug configuration as I don't really know what this setting does (do you?) xD

**Comment by yaichenbaum** [comment]
@DeveloperWOW64 this issue should be resolved in `main`.

**Comment by DeveloperWOW64** [comment]
ok
