### ISSUE TITLE
Dangerous Quirk When Moving Files Causes Unexpected Data Loss

### ISSUE THREAD

**Issue by 358sebastian** [files-community/Files#5431]
**Explain the bug**
When pasting a folder with a same name, choosing "Replace existing items" deletes all files from the folder instead of combining them.

**To reproduce**
1. Go to any location, make a folder with a same name of any existing folder in your computer. (ex: make "New Folder" in C:/, and "New Folder" in D:/. Make a text file in the folder in C:/ with "C.txt", and make a text in D:/ with "D.txt")
2. Move the new folder to the location containing old folder with similar name, choose "Replace existing items" (ex: move "New Folder" from C:/ to D:/, choose "Replace existing items")
3. Open the newly replaced folder (ex: open "New Folder" on D:/)
4. Contents of the old folder is now gone, only contents of the new folder is present (ex: "New Folder" now only contains "C.txt." The file "D.txt" is gone)

**Expected behavior**
Contents of the new folder should be moved to the old one without removing the contents of the old folder (both "C.txt" and "D.txt" should be present in the new folder, not just "C.txt"). This is the case with the default windows File Explorer, it simply moves all of the contents into the same folder, without deleting anything. File Explorer won't delete anything unless the files themselves have the same name, which is not the case in this particular issue. Your Files app deletes the files that don't even have the same name. Any user who is not aware of this unique quirk on your app will risk losing important data on their computer without any warning. I have lost weeks of hard work because of the silly way this app behaves, and all I can do is sit down and cry. I love that this app exists, but it's far from perfect. So please, let this be the last time anyone has to experience major psychological breakdowns because of your app.

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6824932/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6824933/debug_fulltrust.txt)

**System Information**
 - OS Version: Windows 10 21H1 19043.1055
 - App version: 1.5.0.0

**Additional comment**
Suffering is the only constant in life, and the only thing that I can do about it is write a complaint on a GitHub bug report.

**Comment by winston-de** [comment]
I'm truly sorry for your lost work. Here are links to a few free tools that may still be able to recover the lost files; [Windows File Recovery](https://support.microsoft.com/en-us/windows/recover-lost-files-on-windows-10-61f5b28a-f5b8-3cc2-0f8e-a63cb4e1d4c4), [Ease US](https://www.easeus.com/datarecoverywizard/free-data-recovery-software.htm).
I know it doesn't help much now, but this issue has been fixed, and starting from the next release contents will be merged when replacing an existing folder.

**Comment by yaichenbaum** [comment]
@358sebastian as the project owner, I'd like to apologize about the loss of data and repeat what Winston said about this issue being resolved in the next release.
