### ISSUE TITLE
Crash on start-up

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5434]
**Logfile**
[debug.log](https://github.com/files-community/Files/files/6827067/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6827068/debug_fulltrust.log)

**System Information**
 - OS Version: Windows 10 21H1 19043.1083
 - App version: v1.5.65

**Comment by duke7553** [comment]
@gave92 This was probably fixed by https://github.com/files-community/Files/pull/5419?

**Comment by gave92** [comment]
Yeah fixed by #5419

**Comment by stanleyowen** [comment]
Hi, when will the next version be released? I am having trouble in starting Files App 😥. Thanks in advance!
