### ISSUE TITLE
Change time format to show direct time zones

### ISSUE THREAD

**Issue by Stormbender0025** [files-community/Files#5438]
Since I live in India, the format of time in the date modified column shows as UTC + 5:30. For example, currently, I see the date modified section as dd-mm-yyyy UTC + 5:30, as in the image below. Instead, I want it to be dd-mm-yyyy IST (for India).
![image](https://user-images.githubusercontent.com/44270163/126026285-feb380b5-7dfb-44b4-948a-8d84c331da0f.png)

I would like the developers to change this so that instead of showing the offset of different time zones, the application gives the time for that time zone. 

**System Information**
 - OS Version: Windows 10 20H2 19042.1081
 - App version: 1.5.0.0

My device is a Dell Inspiron 15R 5521 Laptop with intel i7 5th Gen, 16GB RAM

**Comment by gave92** [comment]
Thanks for this report. What option do you have under Files Settings > Graphics > Date Format? "Application" or "System"?
If it's "System" what do you have under Windows Settings > Time and Language > Region > Regional format data?
