### ISSUE TITLE
Some strings can't be translated

### ISSUE THREAD

**Issue by BanCrash** [files-community/Files#5441]
**Explain the bug**
Some strings of Files are not being translated. I don't know if those strings are hardcoded or the issue is that there is a bug preventing those strings to get pass by the function that gets the translated value, but the fact is some strings are on english even if you translated all the strings of the xlf.

**To reproduce**
1. Go to Settings -> preferences -> Set "spanish (International Spain) as language, or to another language that has all strings translated.

List of untranslated strings:
- 'New tab' in vertical tab flyout:
1. Go to the vertical tab flyout.
2. Check that it will show "New tab" instead "Nueva pestaña":
![image](https://user-images.githubusercontent.com/11770760/126038019-8150281f-fbf6-44e8-9f8b-8c101da1e88f.png)

- 'Home' in Address Toolbar:
1. Go to Home.
2. Start editing the address on the address toolbar.
3. Check that it will show "Home" instead "Inicio":
![image](https://user-images.githubusercontent.com/11770760/126038063-b7d928c3-1d86-41aa-bf34-5b205cdc5fd1.png)

- Shortcuts on layout mode overflow menu when right-clicking a folder:
1. Go to a folder.
2. Right click without selecting any item.
3. Go to overflow menu of 'Modo de diseño' / 'Layout mode'.
4. Check that shortcuts are with 'Shift' instead 'Mayús':
![image](https://user-images.githubusercontent.com/11770760/126038156-79b8151c-99b9-4cd2-9040-d2c3f44bdfac.png)

For example should show 'Ctrl+Mayús+1' instead 'Ctrl+Shift+1'

- Shortcuts on three dots menu of a folder:
1. Go to a folder.
2. Select the three dots right to 'Vista previa' / 'Preview pane'.
3. Check that there are another shortcut with 'Shift' instead 'Mayús' and another with 'Up' instead 'Arriba':
![image](https://user-images.githubusercontent.com/11770760/126038301-4cd3ec57-87d8-41c6-912c-8a66314fedfe.png)

**Expected behavior**
Those strings should be translated too.

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6834752/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6834753/debug_fulltrust.log)

**Screenshots**
Already added before.

**System Information**
 - OS Version: Windows 10 Pro 21H1 19043.1081 / Windows Feature Experience Pack 120.2212.3530.0
 - App version: Last main commit.

**Additional comment**
This issue still happen after restarting the app.

**Comment by yaichenbaum** [comment]
@BanCrash Do you want to work on this issue?

**Comment by BanCrash** [comment]
> @BanCrash Do you want to work on this issue?

@yair100 I can try at least. I will let you know if I can't solve this issue.

**Comment by BanCrash** [comment]
@yair100 since I've found the way to replace the shortcuts I shouldn't have any issue on completing the work to close this issue.

![image](https://user-images.githubusercontent.com/11770760/126376904-cc9ecd05-5329-4d35-b693-426f90eec25b.png)
