### ISSUE TITLE
Files/folders access control using OpenLDAP

### ISSUE THREAD

**Issue by oleitao** [files-community/Files#5442]
Implementing roles-based access control to control access to resources by users given a specified operation type.
To define users, roles, and permissions, then authorise access attempts to resources (by resource name and operation).

1. On first stage define an default RBAC users/roles structure
2. Include [OpenLDAP](https://www.openldap.org/) setup on Files to be installed with Files
3. Use an RBAC library [Gatekeeper](https://github.com/jchristn/Gatekeeper) or [Casbin](https://github.com/casbin/Casbin.NET) to communicate with OpenLDAP
4. Open/Modify/Delete over files/folders based on RBAC user/permissions
5. Include user permission and groups on files/folders properties

**Comment by gave92** [comment]
Hello could you explain better how this would be useful? We already added the possibility to view and change Windows file/folders permissions in properties.

**Comment by oleitao** [comment]
> Hello could you explain better how this would be useful? We already added the possibility to view and change Windows file/folders permissions in properties.

So, I've read about that Issue and the possibility to view and edit files and folder based user permissions as well as what group/s that user be. In order to support that kind of structure and give possibility to escalate that.  So, OpenLDAP already have all that security and permissions/roles included. 
That software [Automation Studio](https://www.efacec.pt/en/products/automation-studio/) use RBAC to manage user and their permissions over software features. My suggestion is to apply a similar procedure based on OpenLDAP but over files and folders.
An other questions please feel free to ask.

**Comment by gave92** [comment]
_Windows_ already has all that security and permissions/roles included. Still failing to see the point of using OpenLDAP :)
It's already possible to set file permissions in Files:
![image](https://user-images.githubusercontent.com/9673091/126058667-eac84a17-e230-486d-860c-8a161baf7aaf.png)
