### ISSUE TITLE
crash on the splash screen

### ISSUE THREAD

**Issue by stem2580** [files-community/Files#5443]
**Explain the bug**
when i launch the app, it shows the splash screen and it just closes itself

**To reproduce**
just click the app icon

**Expected behavior**
it should open

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6834863/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6834864/debug_fulltrust.log)

**Screenshots**
https://user-images.githubusercontent.com/37732484/126040561-964658fb-0a0f-4b58-aae6-6d74361c9aca.mp4

**System Information**
 - OS Version: Windows 10 20H2 19043.1110
 - App version: 1.5.65.0

**Comment by Itelmen** [comment]
I have the same thing after the last update

**Comment by gave92** [comment]
Thanks for the report. This is fixed on main.
