### ISSUE TITLE
Keep consistency with "pin to favorites"

### ISSUE THREAD

**Issue by BanCrash** [files-community/Files#5447]
**Is your feature request related to a problem?**
#5370 introduced a change with IMO is very good, but now we have inconsistency on the same feature, because depending of where you look you will have "pin to favorites" or "pin to the sidebar". Besides, with rightclicking a folder with is pinned, you will have "unpin directory from sidebar" instead "unpin directory from favorites".

**Describe the solution**
Rename all related strings to keep consistency on every place.

**Scope**

| Capability | Priority |
| :---------- | :------- |
| When you right click on a pinned directory, it should show "Unpin from favorites" instead "Unpin from sidebar" | Must |
| On settings -> Sidebar, it could show "Pin Recycle Bin to favorites", since that section will be pinned to favorites and not to sidebar itself | Could |

**Screenshots**
![image](https://user-images.githubusercontent.com/11770760/126068149-72ab9dec-1d1c-4dcf-90d6-ac8282f4549e.png)
![image](https://user-images.githubusercontent.com/11770760/126068141-8055987e-575f-411b-9979-3b380458c3cc.png)

![image](https://user-images.githubusercontent.com/11770760/126068166-73aa76cf-0f7b-4123-b7ee-5eb7c3ec06f1.png)

**System Information**
- OS Version: Windows 10 Pro 21H1 19043.1081 / Windows Feature Experience Pack 120.2212.3530.0
- App version: Last main commit.

**Comment by yaichenbaum** [comment]
@BanCrash do you want to work on a fix?

**Comment by BanCrash** [comment]
> @BanCrash do you want to work on a fix?

@yair100 yep!
