### ISSUE TITLE
Reduce Overlay/Delay while Resizing Column

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#5450]
**Is your feature request related to a problem?**
While trying to resize the column, there will be some delay/overlay. It will be great to reduce this delay. For more information, here are the details:

File Explorer:

https://user-images.githubusercontent.com/69080584/126106171-172dd94e-36c4-4ecc-8254-fd182a888691.mp4

Files:

https://user-images.githubusercontent.com/69080584/126106182-b33fa089-77d3-49c8-8a26-c7db116c1a30.mp4

**Describe the solution**
It will be great to reduce this delay while trying to resize the column.

**Describe alternatives you've considered**
A clear description of any alternative solutions or features you've considered.

**Scope**

| Capability | Priority |
| :---------- | :------- |
| Reduce delay while trying to resize the column. | Should |

**System Information**
 - OS Version: Windows 10 21H1 19043.1110
 - App version: v1.5.67.0

**Comment by gave92** [comment]
Merging with #5371.
