### ISSUE TITLE
dragging photo to new folder crashes

### ISSUE THREAD

**Issue by pickettryan** [files-community/Files#5451]
**Explain the bug**
When dragging a photo to a new folder, the program crashed.

**To reproduce**
1. Go to Files
2. Create a new folder
3. Drag existing photo to new folder
4. See the error

**Expected behavior**
Not a crash

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6838765/debug.txt)

**Screenshots**
none

**System Information**
 - OS Version: Windows 10 Pro
 - App version: v1.5.0.0

**Additional comment**
n/a

**Comment by gave92** [comment]
Thanks for this report, this issue should be fixed in the beta version.
