### ISSUE TITLE
Screen Doesn't Scroll Automatically while Selecting Multiple Files

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#5453]
**Explain the bug**
While trying to select multiple files in details view which has `y-overflow`, the app doesn't seem to automatically scroll up and or down.

**To reproduce**
1. Open Folder which consist of more than 8 items
2. Select multiple files until top/bottom
3. See error

**Expected behavior**
Screen should scroll automatically while users select multiple files.

**Screenshots**
Expected:

https://user-images.githubusercontent.com/69080584/126172425-2b092ef0-9b64-4460-8bec-38e8e20b1fb2.mp4

Saw:

https://user-images.githubusercontent.com/69080584/126172176-1f2488f6-3fc4-46f4-b8b2-f0d1ae65ce28.mp4

**System Information**
 - OS Version: Windows 10 21H1 19043.1110
 - App version: v1.5.67.0

**Additional comment**
Does this problem happen again after restarting the app? Yes

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5463.
