### ISSUE TITLE
Automatically Adjust Column Length with Files Name on Double Click

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#5456]
**Is your feature request related to a problem?**
In my opinion, it would be great when Files automatically adjust it's column length with it's files' name when users double click on the column in details view. Here is the example:

https://user-images.githubusercontent.com/69080584/126257888-7463a315-ca9e-4dc0-867b-8573a5abbde6.mp4

**Scope**

| Capability | Priority |
| :---------- | :------- |
| Automatically adjust it's column length with it's files' name when users double click | Should |

**System Information**
 - OS Version: Windows 10 21H1 19043.1110
 - App version: v1.5.67.0

**Comment by yaichenbaum** [comment]
Merging with #4643.
