### ISSUE TITLE
False Documentation Link for Custom Themes

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#5457]
**Explain the bug**
There is false documentation link in the Custom Themes documentation, which can be accessed via Settings > Appearance. When trying to click the documentation link in info button, it redirects to https://files-community.github.io/docs/#/articles/custom-themes instead of https://files-community.github.io/docs/#/articles/custom-skins.

**To reproduce**
1. Go to Settings
2. Surf to Appearance Tab
3. Click on the link on info button in Custom themes
4. See 404 Error Page

**Expected behavior**
The link should redirect user to https://files-community.github.io/docs/#/articles/custom-skins instead of https://files-community.github.io/docs/#/articles/custom-themes.

**Screenshots**

https://user-images.githubusercontent.com/69080584/126259911-849ce6b2-93c9-4ca0-9fcb-a2c9d678dc4b.mp4

**System Information**
 - OS Version: Windows 10 21H1 19043.1110
 - App version: v1.5.67.0

**Additional comment**
Does this problem happen again after restarting the app? Yes

**Comment by gave92** [comment]
We should also remove the "Performance Settings" page from the documentation as the settings described there have been removed.

**Comment by yaichenbaum** [comment]
@gave92 it's been removed from the new documentation site.

**Comment by yaichenbaum** [comment]
@stanleyowen The documentation links have been updated.

**Comment by stanleyowen** [comment]
Okay thanks!

**Comment by tellmewhy12** [comment]
@yair100 they seem to be broken again in Version: 2.0.12.0
OS Version: 10.0.19043.1165

**Comment by mangoepic** [comment]
![image](https://user-images.githubusercontent.com/71931749/133412947-82b901f7-265c-430b-9b7a-2c695598a5f5.png)

**Comment by yair100** [comment]
> @yair100 they seem to be broken again in Version: 2.0.12.0
> OS Version: 10.0.19043.1165

The new website hasn't been published yet.
