### ISSUE TITLE
Could not find SDK "WindowsDesktop, Version=10.0.19041.0"

### ISSUE THREAD

**Issue by trparky** [files-community/Files#5460]
**Explain the bug**
I tried to load the solution and I got this error...
Could not find SDK "WindowsDesktop, Version=10.0.19041.0".	Files

**To reproduce**
1. Clone GIT repo
2. Load solution
3. Let Visual Studio load the appropriate modules
4. Try to build the project
5. See error message.

**Expected behavior**
Well, to be able to compile it. Obviously.

**Comment by gave92** [comment]
You can install it from visual studio installer:
![image](https://user-images.githubusercontent.com/9673091/126384569-9d8f2870-24a5-4e72-8437-9f636489426f.png)
Make sure you also have these workloads:
![image](https://user-images.githubusercontent.com/9673091/126384678-d51e72b2-2043-4f67-87b5-5cf846e66c42.png)

**Comment by gave92** [comment]
Closing this issue but feel free to reply here if you need further help 👍

**Comment by trparky** [comment]
That's the thing, I already have that component installed.
![image](https://user-images.githubusercontent.com/32105035/126385022-d476835e-3dc2-4ab0-a197-80528f4c8bca.png)

**Comment by gave92** [comment]
That's funny, my only suggestions would be to restart VS and/or reinstalling that component manually from [here](https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk/)
@winston-de any other idea?

**Comment by trparky** [comment]
I've even tried to do a repair on Visual Studio and it didn't work.

**Comment by trparky** [comment]
Update... I had to go to the folder "C:\Program Files (x86)\Windows Kits" at the command line and issue this command...
mklink /d 10 "G:\Windows Kits\10"
Once I did that, Visual Studio was able to find the path to the associated dependency.
