### ISSUE TITLE
Context menus sometimes faded on windows 10

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5461]
**Explain the bug**
The right click menu and hovers becomes faded and blurry

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6851129/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6851130/debug_fulltrust.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/26977075/126393487-da741f9f-0bae-4bee-9441-ce6f09696736.png)
![image](https://user-images.githubusercontent.com/26977075/126393535-b9f1e23a-7fdd-494f-9a77-f6d35111e591.png)

**System Information**
Version: 1.5.67.0
OS Version: Windows 10 10.0.19043.1110

**Comment by yaichenbaum** [comment]
This appears to be a WinUI issue, can you open an issue on their repository?

**Comment by yaichenbaum** [comment]
@josh-65 thank you for the report and for opening the issue on the WinUI repo.

**Comment by josh-65** [comment]
Apparently it may have been fix in version 2.6.1 according to the WinUI team
