### ISSUE TITLE
Focus on Newly Created Folder or File

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#5464]
**Is your feature request related to a problem?**
Firstly, I have noticed a big changes for Files UI and UX since the v1.5.0.0, so I would like to say thank you for all the contributors! Here is the issue: Sometimes after creating a new file or folder, it doesn't automatically focused on the newly created folder/file, and it will take a second or more for users to manually click the recently added file or folder, which is actually really bad for UX.

**Describe the solution**
It will be great if Files automatically focus on newly created folder or file.

**Scope**

| Capability | Priority |
| :---------- | :------- |
| Focus on Newly Created Folder or File | Must |

**System Information**
 - OS Version: Windows 10 21H1 19043.1110
 - App version: v1.5.67.0

**Comment by gave92** [comment]
Merging with #7310
