### ISSUE TITLE
Some Strings Got Cut in Tiles View

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#5465]
**Explain the bug**
While trying to create some Microsoft PowerPoint Presentation files in Tiles View, I noticed some string got cut instead of showing `...`. I'm not sure whether this issue is similar to #5376, however this issue is produced in tiles view and occurred in files' property.

**To reproduce**
1. Create a Microsoft PowerPoint Presentation Files in Tiles View
2. See the error

**Expected behavior**
Instead of showing the overflow string, try to shows `....`.

**Screenshots**
![image](https://user-images.githubusercontent.com/69080584/126468693-a3b235eb-8b6d-451f-9f5b-022d4a96b557.png)

**System Information**
 - OS Version: Windows 10 21H1 19043.1110
 - App version: v1.5.67.0

**Additional comment**
Does this problem happen again after restarting the app? Yes

**Comment by gave92** [comment]
Could you confirm that this happens depending on Files window width? If you increase the width slightly does the "..." appear?

**Comment by stanleyowen** [comment]
Ah I just realize that the "..." will appear if I minimize the app, however I can't see the dots when the screen is maximized (as default). Just to make sure that I have updated Files to v1.9.13.0.

![image](https://user-images.githubusercontent.com/69080584/126904900-992759c8-5786-4c20-9454-ca2f204b946d.png)

**Comment by yaichenbaum** [comment]
Merging with #1033
