### ISSUE TITLE
Unable to move the files app on windows 10

### ISSUE THREAD

**Issue by Wtcheesecakes** [files-community/Files#5476]
**Explain the bug**
Trying to move around the app on the latest update (1.9) as you can see in the screenshot
![Untitled](https://user-images.githubusercontent.com/21296476/126642535-eb5e5e37-0d55-463e-9a0c-884341aca881.png)

**To reproduce**
try to move the app around from anywhere within the above screenshot

**Expected behavior**
Should be able to move from anywhere on the top bar

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6862348/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6862349/debug_fulltrust.log)

**Screenshots**
Screenshot above

**System Information**
 - OS Version: 
Edition	Windows 10 Pro
Version	21H1
Installed on	‎19/‎05/‎2021
OS build	19043.1147
Experience	Windows Feature Experience Pack 120.2212.3920.0

 - App version: 1.9

**Comment by MindOfBrianna03** [comment]
I can confirm that I have this issue, only able to move it by click and dragging from right next to the minimise button.

**System Information**

- OS Version:
Edition Windows 10 Pro
Version 21H1
Installed on ‎26/‎06/‎2021
OS build 19043.1110
Windows Feature Experience Pack 120.2212.3920.0

- App version: 1.9.0.0

Hopefully, this is fixed quickly!

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5484.
