### ISSUE TITLE
Settings in compact overlay not responsive

### ISSUE THREAD

**Issue by padredalvi** [files-community/Files#5477]
**Explain the bug**
Write a clear description of what the bug is.

**Expected behavior**
It should be horizontally and vertically scrollable to access the buttons

**Screenshots**
![image](https://user-images.githubusercontent.com/87815703/126646340-9af7c66c-1f87-4d14-bcb7-d4915631b0f7.png)

**System Information**
 - OS Version: Windows 11 21H2 22000.71
 - App version: v1.9.0.0

**Additional comment**
Restarting the app and/or the PC doesn't solve the problem

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5482.

**Comment by Poopooracoocoo** [comment]
would be neat if it went from being a popup to being a regular page at smaller sizes! 😎
