### ISSUE TITLE
context menu gets cut off when selecting items on the bottom

### ISSUE THREAD

**Issue by stem2580** [files-community/Files#5479]
**Explain the bug**
When right clicking an item || folder in the lower part of the screen, part the context menu gets cut off, sometimes the menu becomes scrollable but 1st: it's somewhat small tbh && 2nd: it doesn't let me scroll to the lowest option ("more..." button). 

**To reproduce**
1. Right click an item in a lower part of the screen.

**Expected behavior**
the menu should be limited by the screen boundaries, so when i right click an item in the bottom & the menu length is larger than what would fit in the space between that item and the bottom screen boundary, it should shift up.

**Logfile**
[debug_fulltrust.log](https://github.com/files-community/Files/files/6864558/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/6864559/debug.log)

**Screenshots**
https://user-images.githubusercontent.com/37732484/126692030-2c3e02c2-1fc7-4797-a0eb-2aa580fe5aae.mp4

**System Information**
 - OS Version: Windows 10 21H2 19043.1110
 - App version: v1.9 (older versions had this bug too)

**Comment by gave92** [comment]
This is a WinUI issue -> microsoft/microsoft-ui-xaml#4881
