### ISSUE TITLE
Crash on folder/file right click

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5481]
**Expected behaviour**
It shouldn't crash and show the content

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6864784/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6864785/debug_fulltrust.log)

**System Information**
- Version: 1.9.0.0
- OS Version: 10.0.19043.1110

**Comment by yaichenbaum** [comment]
@josh-65 This issue should be resolved with #5480.
