### ISSUE TITLE
No icons or thumbnails

### ISSUE THREAD

**Issue by Darhagonable** [files-community/Files#5483]
**Explain the bug**
First time opening some folders no icons or thumbnails get loaded.

**To reproduce**
1. Update to 1.9.0.0 preview
2. Run Files
3. Click on for example Music folder
4. Possibly no icons or thumbnails gets loaded

**Expected behavior**
The icons and thumbnails to load

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6865616/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6865617/debug_fulltrust.log)

**Screenshots**
No icons:
![image](https://user-images.githubusercontent.com/14127357/126719441-f0224fd4-b721-41c0-abc7-0b46bb57f820.png)
With icons:
![image](https://user-images.githubusercontent.com/14127357/126719412-4a362508-9750-4cdf-a9fe-de197864e6b9.png)

**System Information**
 - OS Version:
Edition	Windows 10 Home
Version	21H1
Installed on	‎2020-‎10-‎28
OS build	19043.1083
Experience	Windows Feature Experience Pack 120.2212.3530.0

 - App version: 1.9.0.0

**Additional comment**
When this happens it also seems to not list number of items

**Comment by BanCrash** [comment]
I detected this issue when #5436 was pushed to main, so I think it's related to that.

**Comment by yaichenbaum** [comment]
@Darhagonable is this still an issue in v2.0.34?

**Comment by Darhagonable** [comment]
@yair100 I'm struggling to reproduce this in v2.0.42
The issue originally just happened after initial install so can't guarantee it's actually fixed or if it just doesn't happen once its been installed once.
I tried uninstalling Files and nuking the temp files i could find in a VM and it seems to be working like it should after installing again.
I think we can close this issue for now but keep eyes open for any new similar reports if they appear.
