### ISSUE TITLE
Files crashes after closing Properties window (1.9.0.0 - 1.9.12.0)

### ISSUE THREAD

**Issue by Nuzza** [files-community/Files#5490]
**Explain the bug**
Wherever you trigger the properties window to open, upon closing it via the close button, OK button, or the Cancel button will cause the entire Files app to crash.

**To reproduce**
1. Go to any directory (i.e. Downloads)
2. Right click in the empty space/folder/file and select Properties
3. When the properties window opens, press the close, OK, or Cancel button
4. Files will crash

**Expected behavior**
I expect to be able to close the properties window in Files without the app crashing.

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6866723/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6866724/debug_fulltrust.log)

**System Information**
 - OS Version: Windows 11 Home 21H2 22000.100
 - App version: v1.9.0.0

**Additional comment**
The problem does still occur after restarting the app as well as repairing/resetting the app in settings. The problem occurs 100% of the time.

**Comment by stanleyowen** [comment]
I can't produce this issue though in Files v1.9.11.0.

**Comment by Nuzza** [comment]
@stanleyowen

I just updated to version 1.9.11.0 myself but unfortunately this issue still occurs. I have attached a gif of the problem I am experiencing.

![Animation](https://user-images.githubusercontent.com/29596317/126745688-a6df3837-4ad4-4f56-a225-9c67c370e944.gif)

**Comment by Nuzza** [comment]
Update:
I updated to the latest version of Files (1.9.12.0) and the bug still occurs. I have attached another gif to show me causing the bug and have also attached another debug.log and debug_fulltrust.log file.

I am still running the latest Windows 11 insider preview being build 22000.100 so maybe the crash could be caused by the version of Windows otherwise, I have tried every solution I could think of to fix the issue (such as repairing/resetting the app) with no luck.

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6871774/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6871775/debug_fulltrust.log)

**Gif**
![Animation](https://user-images.githubusercontent.com/29596317/126854587-fb6dff86-6276-4936-93f8-6fc6d9c24313.gif)

**Comment by gave92** [comment]
Merging with $2714
