### ISSUE TITLE
Scroll Tab button Not Being Centrally Aligned

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#5492]
**Explain the bug**
Trying to open around 10 tabs and users will be able to see the button to trigger the tab forward and backward, however the button is not centrally aligned.

**To reproduce**
1. Open more than 10 tabs
2. See the error

**Expected behavior**
Scroll tab button should be centrally aligned.

**Screenshots**
![Scroll Tab button Not Being Centrally Aligned](https://user-images.githubusercontent.com/69080584/126744451-6c6831f2-387c-436a-9798-1f8ccdc485e6.png)
![Scroll Tab button Not Being Centrally Aligned](https://user-images.githubusercontent.com/69080584/126744573-95709374-2f7a-453e-afa7-a5c9b9b341fa.jpg)

**System Information**
 - OS Version: Windows 10 20H2 19043.1110
 - App version: v1.9.11.0

**Additional comment**
Does this problem happen again after restarting the app? Yes

**Comment by d2dyno1** [comment]
@stanleyowen This should be resolved with #7915
