### ISSUE TITLE
Open Certain Items via Recent Files will Open Document Behind Files

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#5493]
**Explain the bug**
Open certain items (such as Microsoft PowerPoint, Google Chrome, etc) in recent files will open the selected document behind the Files app.

**To reproduce**
1. Click on one items
2. See the document opened behind Files app

**Expected behavior**
Documents should be previewed in front of Files App.

**Screenshots**

https://user-images.githubusercontent.com/69080584/126746188-1cf73e08-2075-4dd8-8105-718ebe58e88a.mp4

**System Information**
 - OS Version: Windows 10 20H2 19043.1110
 - App version: v1.9.11.0

**Additional comment**
Does this problem happen again after restarting the app? Yes

**Comment by gave92** [comment]
Thanks for this report, I'm merging this with #5493

**Comment by stanleyowen** [comment]
Hi @gave92 is there any mistakes with the link? It looks like the link redirected me back to this issue page.

**Comment by gave92** [comment]
Fixes thanks.
