### ISSUE TITLE
Open and Close Map Network Drive will Cause Another Apps to Appear

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#5494]
**Explain the bug**
While trying to open map network drive in the Home > Drives Section, and after closing the map network drive dialog will cause another or background apps to appear in front of Files. I am not sure whether this issue is related to Files App or Windows.

**To reproduce**
1. Go to Home which is located in Favorites Tab
2. Click the three dots in the Drives Section
3. Click on Map Network Drives
4. Close the Dialog
5. Another app appear in front of Files App

**Expected behavior**
Another app shouldn't appear in front of Files App

**Screenshots**
![Open and Close Map Network Drive will Cause Another Apps to Appear](https://user-images.githubusercontent.com/69080584/126749704-2c7374d6-e97a-46c7-a5fa-3c09b89f215c.gif)

**System Information**
 - OS Version: Windows 10 20H2 19043.1110
 - App version: v1.9.11.0

**Additional comment**
Does this problem happen again after restarting the app? Yes

**Comment by gave92** [comment]
I don't think we can fix this. UWP apps and Win32 dialogs don't agree with each other.

**Comment by Josh-65** [comment]
Is this still an issue?
