### ISSUE TITLE
Broken animation when opening the Settings dialog

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#5495]
**Explain the bug**
The animation that's played when the Settings dialog is opened seems broken.

**To reproduce**
1. Open click
2. Click on settings
4. See the broken animation

**Expected behavior**
Animation shouldn't be broken.

**System Information**
- App version: 1.9.11.0
- OS Version: 10.0.22000.71

**Comment by yaichenbaum** [comment]
We're having a hard time reproducing this issue, can you add a screen recording?

**Comment by jaigak** [comment]
@yair100 
![2021-07-23 17-20-04](https://user-images.githubusercontent.com/45227503/126778578-20828d9e-e3ec-4e8e-a16b-b86afabc5e23.gif)

**Comment by Jaiganeshkumaran** [comment]
If you notice carefully, some element is rearranged behind the settings dialog.

**Comment by yaichenbaum** [comment]
This issue appears to be resolved in `main`.
