### ISSUE TITLE
Right click .ogg file causes jamming

### ISSUE THREAD

**Issue by 1135108813** [files-community/Files#5496]
Hello, I found a bug.
Right-clicking on .ogg files causes jamming, and 
this issue is triggered steadily.

![bug](https://user-images.githubusercontent.com/46586346/126760476-328c6b47-13c5-4369-ada7-6e4d66f8339f.gif)

[debug.txt](https://github.com/files-community/Files/files/6867638/debug.txt)

**Comment by gave92** [comment]
Cound you show the windows explorer's context menu for .ogg files?
