### ISSUE TITLE
Files crash after selecting theme

### ISSUE THREAD

**Issue by esibruti** [files-community/Files#5499]
**Explain the bug**
When selecting a theme, whatever it is, Files crashes.

**To reproduce**
1. Go to Settings
2. Click on Custom themes
3. Click on any theme
4. See the error

**Expected behavior**
Normally I should select the theme and Files won't crash.

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6869546/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6869547/debug_fulltrust.log)

**Screenshots**
https://user-images.githubusercontent.com/78214358/126800136-8abf7e65-48e3-46f6-b49b-75cce814efb0.mp4

**System Information**
 - OS Version: Windows 10 Home
                       21H1
                       19043.1110
                       Windows Feature Experience Pack 120.2212.3530.0

 - App version: v1.9.12.0

**Comment by gave92** [comment]
I think one of the themes is broken. Could you try to remove all themes except for e.g. Acrylic and see if the app still crashes when you select it?

**Comment by esibruti** [comment]
@gave92 Could you indicate where the themes are located? It's just that I can't find...

**Comment by gave92** [comment]
`%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState\Themes`

**Comment by esibruti** [comment]
Well... it's just that I don't have any in this folder... Is it normal not to have any?

**Comment by gave92** [comment]
@yair100 what folder are themes in?

**Comment by winston-de** [comment]
Themes from the optional themes package won't show up in the normal folder. The themes in that package are located [here](https://github.com/files-community/Custom-themes/tree/main/CustomThemesPackage).

**Comment by gave92** [comment]
So @esibruti could try to uninstall the optional package and manually add one of those themes to the folder right?

**Comment by esibruti** [comment]
@gave92 I installed the extension that is available in the Store. But I will do this, I will install one of them manually like you said

**Comment by esibruti** [comment]
@gave92 I just now put a theme to choose from and no longer the problem. After all, is the problem of extension?

**Comment by gave92** [comment]
I think it may be just one or some of the themes which causes the issue, what happens if you put all themes listed there in the themes folder?

**Comment by edge261** [comment]
Happens the same to me. Maybe I should reinstall the extension?

Using Windows 11.

**Comment by esibruti** [comment]
> I think it may be just one or some of the themes which causes the issue, what happens if you put all themes listed there in the themes folder?

@gave92 I put all the themes and what happens? Crash Files

**Comment by gave92** [comment]
Black Pixel.xaml

**Comment by yaichenbaum** [comment]
@gave92 do you know which value in the theme is causing the issue?

**Comment by gave92** [comment]
`<<Color x:Key="SolidBackgroundFillColorBase">#181818</Color>`
See the double "<"

**Comment by esibruti** [comment]
And Middle Blue

**Comment by esibruti** [comment]
@gave92 @yair100 It´s Black Pixel.xaml and Middle Blue.xaml 
All tested now

**Comment by gave92** [comment]
Funny, `Middle Blue.xaml` works ok for me (after removing `Black Pixel.xaml `)

**Comment by esibruti** [comment]
Funny that I didn't have `Black Pixel.xaml` in the folder and `Middle Blue.xaml` didn't work

**Comment by yaichenbaum** [comment]
I updated the theme extension to fix the issue.

**Comment by esibruti** [comment]
Is the update available now?

**Comment by yaichenbaum** [comment]
It'll be available in around an hour.

**Comment by edge261** [comment]
I selected the Acrylic one and it crashed, but the theme was correctly applied after opening it again.

**Comment by esibruti** [comment]
> I selected the Acrylic one and it crashed, but the theme was correctly applied after opening it again.
> 
> Same with other themes...
> 
> ![image](https://user-images.githubusercontent.com/79731301/126818906-533d008d-6dd4-4d06-ab36-e5c0905cbe4a.png)

Don't worry, in a few hours, there will be an update for the extension of themes that will solve these problems.

**Comment by edge261** [comment]
I had to uninstall the plugin, since now the app doesn't open after a theme change.

**Comment by esibruti** [comment]
> I had to uninstall the plugin, since now the app doesn't open after a theme change.

@edge261 Have you tried reinstalling Files?

**Comment by stanleyowen** [comment]
> I had to uninstall the plugin, since now the app doesn't open after a theme change.

I have also recently encountered the same issue, deleting the `Black Pixel.xaml` file helps me solve this issue.

**Comment by edge261** [comment]
> > I had to uninstall the plugin, since now the app doesn't open after a theme change.
> 
> @edge261 Have you tried reinstalling Files?

I did. Happens the same...
