### ISSUE TITLE
Enhancement: Improve the mica color on the content area

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#5500]

**Comment by winston-de** [comment]
How does this look?
![image](https://user-images.githubusercontent.com/59544401/126834246-3901e1e0-ac4f-43b3-9ed4-d2112b710285.png)

**Comment by yaichenbaum** [comment]
Adding @itsmichaelwest.

**Comment by itsmichaelwest** [comment]
The content area should use [`LayerFillColorDefaultBrush`](https://docs.microsoft.com/en-us/windows/apps/design/style/mica#app-layering-with-mica) for the tint, which defaults to `#FFFFFF` at 50% transparency in light mode and `#3A3A3A` at 30% transparency in dark mode.

**Comment by winston-de** [comment]
layer fill color default

![image](https://user-images.githubusercontent.com/59544401/126849476-0386fd1b-38b6-402c-b92f-2dfd6ee0ef35.png)
![image](https://user-images.githubusercontent.com/59544401/126849544-b5c03c34-2622-4319-a5ce-871d2d64fc9b.png)

**Comment by itsmichaelwest** [comment]
LGTM 👍

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5507.
