### ISSUE TITLE
Move ongoing tasks button back to the status bar.

### ISSUE THREAD

**Issue by Tropix126** [files-community/Files#5501]
**Is your feature request related to a problem?**
In Files v2, the tasks flyout button was moved up to the navigation bar. I believe that this doesn't make much sense logically , as it   doesn't relate to navigation. I think it would make more sense to keep it in the status bar.

**Describe the solution**
Move the ongoing tasks button back to it's previous location.

**Describe alternatives you've considered**
None

**Scope**

n/a

**System Information**
 - OS Version: Windows 11 22000.100
 - App version: 1.9.0.0

**Additional comment**
![image](https://user-images.githubusercontent.com/42101043/126819044-80ddb01c-4aba-416c-9af5-e0f3fd424b5e.png)

**Comment by yaichenbaum** [comment]
We don't have any plans to make this change, however, we should note that we plan to hide the button when there are no ongoing tasks.

**Comment by rlaphoenix** [comment]
I actually agree with Tropical here. It doesn't make sense to be up there, which can potentially cause a layout shift when you proceed with making it hide when there are no ongoing tasks. This could be a hindrance when navigating and all of a sudden it pops up.
