### ISSUE TITLE
Shortcut to open the settings dialog.

### ISSUE THREAD

**Issue by Tropix126** [files-community/Files#5502]
**Is your feature request related to a problem?**
At the moment, getting to settings with keyboard navigation can be tedious. Most applications offer a shortcut to it's settings page.

**Describe the solution**
Add a shortcut for opening settings. A general standard for a fair few applications i've seen is <kbd>Ctrl</kbd> + <kbd>,</kbd>

**Describe alternatives you've considered**
N/A

**Scope**

| Capability | Priority |
| :---------- | :------- |
| Keyboard shortcut to open settings. | Must |

**System Information**
 - OS Version: Windows 11 22000.71
 - App version: v1.9.0.0

**Additional comment**
None

**Comment by winston-de** [comment]
Might be good to add an access key as well.

**Comment by yaichenbaum** [comment]
Settings can be accessed by the `alt` + `i` access key.
