### ISSUE TITLE
Empty Disc Reader Allows File Creation

### ISSUE THREAD

**Issue by esibruti** [files-community/Files#5503]
(It's a bug but at the same time it's a suggestion for improvement a little linked to issue #4550)

In this new update (v1.9.12.0), it has options like paste or create new folder, when it shouldn't let it do this on the empty disk player.

https://user-images.githubusercontent.com/78214358/126789322-29dbbe1f-3469-40f6-90b7-b71dfcd21655.mp4

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5740.
