### ISSUE TITLE
Please add path largest 255 chars in path

### ISSUE THREAD

**Issue by korenevskiy** [files-community/Files#5505]
The standard explorer limit is 255 characters in the full folder path.
All partition formats do not have this restriction. And also the operating system does not have this restriction. Only the standard Windows Explorer has a restriction.
I would love to use your browser. By default, all applications also have this restriction. But if you had set parameters in the application configuration to remove the restriction on the length of the file path more than 255 characters. I would use your application to back up working files.
You need to be able to: Copy, Move, Create folders with a large number of characters in the path.
But so far, there is no point in your application.

**Comment by gave92** [comment]
Files already supports paths longer than 255 chars, you just need to enable the NTFS Long Path policy. What issues are you experiecing?

**Comment by korenevskiy** [comment]
I know all this. I have already configured these settings for more than 5 years. But I just checked these settings. Everything is set up as it should be.
The Files Explorer window closes when you try to create a folder. Check it out for yourself. Do the Create, Copy, Move functions work with a path length of more than 260 characters?

**Comment by gave92** [comment]
Ahhh, which Files version do you have? If it's 1.5.0.0 there was a bug preventing this to work. It's since been corrected but the fix has not yet shipped publicly. To take advantage of it you'd have to get the beta version of Files:

> Join the insider flight group
You can fill out this form to get access to the preview builds in the Microsoft Store https://forms.office.com/r/UsaBmzC99n. It can take a couple of days until you're added to the flight group, but once added, you will start receiving updates to the regular Files app through the Microsoft Store.

**Comment by korenevskiy** [comment]
@gave92 
I download last version "_Files.Package_1.5.0.0_x86_x64.msixbundle_" from https://github.com/files-community/Files/releases .
But when I tried to open a folder located deep beyond 255 characters, the Explorer crashed.
In the microsoft store, it is written that the publication was still in 2019.
Is there an up-to-date version on Github https://github.com/files-community/Files/releases?

**Comment by gave92** [comment]
Nope to get the beta versions you need to join the Files Insiders program as explained above.

**Comment by korenevskiy** [comment]
> Ahhh, which Files version do you have? If it's 1.5.0.0 there was a bug preventing this to work. It's since been corrected but the fix has not yet shipped publicly. To take advantage of it you'd have to get the beta version of Files:
> 
> > Join the insider flight group
> > You can fill out this form to get access to the preview builds in the Microsoft Store https://forms.office.com/r/UsaBmzC99n. It can take a couple of days until you're added to the flight group, but once added, you will start receiving updates to the regular Files app through the Microsoft Store.

I entered the wrong address by mistake. Can I reuse the Beta link to enter the correct address?

**Comment by gave92** [comment]
Sure 👍

**Comment by korenevskiy** [comment]
Time passed.

I have already sent my EMAIL 5 times using the specified link.
And the Beta version never loaded.
In the beta version, what is the version number?
How do I get the beta version?

**Comment by korenevskiy** [comment]
> Sure 👍

Time passed.

I have already sent my EMAIL 5 times using the specified link.
And the Beta version never loaded.
In the beta version, what is the version number?
How do I get the beta version?

**Comment by gave92** [comment]
Beta version is 1.9. @yair100 is there anything else to do?

**Comment by yaichenbaum** [comment]
@korenevskiy it can take a couple days until you're added to the flight group.
