### ISSUE TITLE
Context Menu Still Exist When Click on Some Button

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#5508]
**Explain the bug**
When user right click on a folder / file, a context menu will show up, while click on some specific button (Copy Location, Create Shortcut, Delete, and Pin to Favorite), the context menu won't close and still exist. I am not sure whether this is a bug with Files App or winUI.

**To reproduce**
1. Right click on a file or folder
2. Click on Copy Location, Create Shortcut, Delete, or Pin to Favorite Button (located on the top of context menu)
3. See the error

**Expected behavior**
The context menu should be closed after users click on those buttons.

**Screenshots**

https://user-images.githubusercontent.com/69080584/126855514-2c8500c1-78c9-4f19-a70c-bd6d67cde1ca.mp4

**System Information**
 - OS Version: Windows 10 20H2 19043.1110
 - App version: v1.9.12.0

**Additional comment**
Does this problem happen again after restarting the app? Yes

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5531.
