### ISSUE TITLE
Touch Screen Double Click

### ISSUE THREAD

**Issue by liyuxuan3003** [files-community/Files#5511]
When I try to double click a selected file or folder by touch screen, it doesn't work.

But if I selectd a file or folder, and double click at a blank area by touch screen, it will actually open that file or folder.

**Comment by josh-65** [comment]
what version of the app and windows your on?

**Comment by liyuxuan3003** [comment]
The app version is 1.5.0.0.
The windows version is 20H2, and the "Operating system internal version" is 19042.1110.

**Comment by yaichenbaum** [comment]
This issue should be resolved in v2.0.34.
