### ISSUE TITLE
Tooltip on back, forward and up buttons should say where to like native file explorer

### ISSUE THREAD

**Issue by Poopooracoocoo** [files-community/Files#5512]
**Is your feature request related to a problem?**
A clear description of what the problem is.
where does the button go?

**Describe the solution**
A clear description of what you want.
in tooltip

**Describe alternatives you've considered**
A clear description of any alternative solutions or features you've considered.

**Scope**

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**System Information**
 - OS version: Windows 10 21H1
 - App version: 1.5

**Additional comment**
Add any other comment or screenshots about the feature request here. What device type/UI layout and app version?

**Comment by Josh-65** [comment]
This issue isn't clear if it still a problem in 2.4.33.0 then please make a new issue following the issue template.

**Comment by yaira2** [comment]
It's a feature request, that being said, can you open a new request with the template so we can track it?
