### ISSUE TITLE
Feature: Hide parts of the path in the breadcrumb bar under a chevron and menu when it goes offscreen

### ISSUE THREAD

**Issue by Poopooracoocoo** [files-community/Files#5513]
**Is your feature request related to a problem?**
A clear description of what the problem is.
users can't scroll it using a mouse. most mice don't have horizontal scroll wheels.

**Describe the solution**
A clear description of what you want.

**Describe alternatives you've considered**
A clear description of any alternative solutions or features you've considered.

**Scope**

| Capability | Priority |
| :---------- | :------- |
| This proposal will add an option to collapse items in the pathbar when there isn't enough space | Must |

**System Information**
 - OS Version: Windows 10 21H1
 - App version: 1.5

**Additional comment**
Add any other comment or screenshots about the feature request here. What device type/UI layout and app version?

**Comment by yaichenbaum** [comment]
This will be implemented when we switch to the WinUI Breadcrumb control.

**Comment by Josh-65** [comment]
Asking @yaichenbaum for approval.

**Comment by yaira2** [comment]
Which items should be collapsed first?

**Comment by yaira2** [comment]
@Poopooracoocoo, thank you for your feedback! We’ll address this issue along with #16029.
