### ISSUE TITLE
Closing properties window crashes the App

### ISSUE THREAD

**Issue by ExpressLuke** [files-community/Files#5516]
**Explain the bug**
Closing the file/folder properties window results in a force closure of the App.

**To reproduce**
1. Right click any item and click "Properties"
2. Close the Properties window
3. App crashes.
4. See the error

**Expected behavior**
Closing the Properties window to not crash the App.

**Logfile**
Upload the log file here for us to understand your issue better. 
[debug_fulltrust.log](https://github.com/files-community/Files/files/6872997/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/6872998/debug.log)

**Screenshots**
N/A

**System Information**

**OS Version**
Edition	Windows 11 Pro
Version	21H2
OS build	22000.100
Experience	Windows Feature Experience Pack 421.18901.0.3

**App version**
1.9.12.0

**Additional comment**
Can be replicated infinitely after restarting the App.

**Comment by gave92** [comment]
#5490
