### ISSUE TITLE
Lighter than normal when launching with default theme

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5518]
Disregard
> **Screenshots**
> what it should look like (I can change the colour mode to light then dark and it fixes it)
> ![image](https://user-images.githubusercontent.com/26977075/126888404-54061105-7153-438d-bd44-73d984e30980.png)
> 
> What it actually looks like
> ![image](https://user-images.githubusercontent.com/26977075/126888411-93380df6-bef4-4b80-a3f3-54516c47d328.png)
> 
> **System Information**
> - App Version: 1.9.13.0
> - OS Version: 10.0.19043.1110

**Comment by gave92** [comment]
Happens in light mode too, it appears fully white on launch (Windows 10):
<img src="https://user-images.githubusercontent.com/9673091/126896144-d1c6618b-7da1-4913-9d35-06434bd74395.png" width="600" />

**Comment by BanCrash** [comment]
One workaround I've found it's to set a custom theme. With that it seems to not happen this, at least with Bound to be blue and Discord.

**Comment by josh-65** [comment]
So I have got use to the new/broken dark mode and like it more than the original however I don't know about light mode. I'm going to close this issue for now.

**Comment by BanCrash** [comment]
> So I have got use to the new/broken dark mode and like it more than the original however I don't know about light mode. I'm going to close this issue for now.

Could you let this opened for light mode please? In light mode is fully white, which I find so sad. I'm using a workaround to avoid it but I think this should be fixed.

**Comment by josh-65** [comment]
Sure

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5662.
