### ISSUE TITLE
Properties windows on shortcut doesn't open file location in tab

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5519]
To reproduce**
1. Right click shortcut file
2. Click on properties
3. Click on shortcut tab
4. Click "open file location"
5. See it open a new window instead of tab

**Expected behaviour**
It should open in a new tab

**System Information**
- App Version: 1.9.13.0
- OS Version: 10.0.19043.1110

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5529.
