### ISSUE TITLE
Feature: Option to Enable/Disable Drag & Drop of files and folders

### ISSUE THREAD

**Issue by ClementYip1713** [files-community/Files#5521]
### What feature or improvement do you think would benefit Files?
Wish there is an option to Enable/Disable Drag & Drop capability for files and folders.
This is one feature missing in standard windows File Explorer also.

Some people, with clumsy hands, might find Drag & Drop annoying and can easily cause them to make mistakes.
It would be great if we can disable this feature.

### Files Version

2.3.11.0

### Windows Version

10.19043.1899

**Comment by MalteTasler** [comment]
As an alternative (or addition), I would consider adding these features to prevent unwanted changes made with drag and drop: 

- a decent notification when a file was dragged and dropped that disappears after a few seconds, including an "undo" button
- a warning dialog hat appears for the more advanced directories - for example when moving a file contained in C:\windows

**Comment by yaira2** [comment]
@ClementYip1713 thank you for your feedback. Due to some differences in sensitivity thresholds in Files, I haven't had any instances where I accidentally drag & dropped items. I'm curious if you've given this a try and if you found this to be true in your experience as well.

**Comment by yaira2** [comment]
@ClementYip1713

**Comment by ClementYip1713** [comment]
This is a general problem.  Both the "Files" and "Windows File Explorer".
It happens to me (in much lesser extent), and often happen to older people.

Do not underestimate the "clumsiness" in people (particularly older people).
(My mother would often call me for emergency rescue, because she "lost" her files.)

**Comment by yaira2** [comment]
I'm interested in hearing if this is an issue you've actually had in Files, or if it's just a general feature request coming from frustrations with File Explorer. I too have had this issue in File Explorer but it's never been a problem in Files.

**Comment by ClementYip1713** [comment]
This is a general frustration in Windows File Explorer.
This is a feature request, and not a bug complain of Files.

I believe this is a feature that could give an edge to Files over Windows File Explorer.
That's why it should be an option (and not outright disabling)

Regards,
Clement

**Comment by yaira2** [comment]
Thank you for the clarification. Being that this hasn't been an issue with Files, we don't have plans to add an option to disable drag & drop.
