### ISSUE TITLE
Bugs & Functionality

### ISSUE THREAD

**Issue by SunnySSwag** [files-community/Files#5526]
Hi, I’ve recently started using your app and I really loved it’s functionality! Specially the design! Though there are a few things that makes it difficult for me and I’m sure many other people to use it as my default app.

Bugs
-	Window crashes when:
o	Trying to rearrange tabs with other tabs
o	Right clicking – properties and then clicking ok
-	Loading issue:
o	Sometimes the page doesn’t completely load up. Custom folder icons don’t show up or thumbnails of some videos are still blurry until the page is refreshed
-	Display:
o	Unable to change the display size in some folders. No matter which display size I pick, it stays the same. For some folders it works fine
-	Slight delay when switching between tabs
-	Slight delay when opening a folder

New useful features
-	Option to drag and drop items: Like, the folders I have pinned, I can’t drag them anywhere. For example In windows file explorer, I can drag the pinned folders to desktop to create a shortcut. Or drag and drop a folder to “favorites” without needing to right click and pin it.
-	Drag & Rearrange pinned locations. After I’ve pinned some folders, I can’t click and drag them to rearrange. It would be a nice feature to have. 
-	Option to apply same settings for all sub folders like display size settings etc. so you don’t need to manually change the size on each folder. 

So far these are the things I’ve tested and experienced. 
Keep up the good work! Hope this helps 😊

Best wishes
Sunny

**Comment by yaichenbaum** [comment]
Thank you for opening this report, can you split each issue into its own issue so we can track them better?

**Comment by gave92** [comment]
I'm pretty sure all the issues/features are either resolved in version 1.9.0.0 or already tracked.
