### ISSUE TITLE
Softlock and crash when properties close

### ISSUE THREAD

**Issue by Pipixel** [files-community/Files#5536]
**Explain the bug**
Softlock and crash the software when the properties window closes

**To reproduce**
1. Right click on the left side bar items
2. Open properties
3. Close immediately on general (crash) or go to security
4. Close the window in security (infinite loading)

**Expected behavior**
Back to normal state

**Logfile**
[https://mega.nz/folder/3UF3jIaY#kdreaBWHQgvnPJNE-5nTng](url)

**System Information**
 - OS Version: Windows 11 22000.100
 - App version:  1.9.13.0

**Comment by gave92** [comment]
Merging with #2714. Looks like it's become more common.
