### ISSUE TITLE
Crashing on startup when upgrading or reinstalling

### ISSUE THREAD

**Issue by TechGuysTechSpot** [files-community/Files#5539]
**Explain the bug**
When I try to install the app or upgrade from a previous version it crashes on startup 

**To reproduce**
1. Go to the Files app
2.  Go to %userprofile%\AppData\Local\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState\debug.log
3. See the error

**Expected behavior**
I expected the app to open normally and show files

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6875273/debug.log)
Logfile when I upgraded from 1.5 to 1.9.13

**System Information**
 - OS Version: Windows 11 21H2 22000.100
 - App version: 1.9.13

**Additional comment**
It happens after restarting the application too

**Comment by yaichenbaum** [comment]
@TechGuysTechSpot is this an issue with v2.0.34?
