### ISSUE TITLE
Sub Context Menu Still Exists When Switching App

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#5540]
**Explain the bug**
When right click on a file and choose more, a sub context menu will appear. When a user switch to another app (I usually use `Alt+Tab`) and switch back again to Files app, I found out that the sub context menu dialog still exists!

**To reproduce**
1. Right click on a file
2. On the bottom of the context menu, click on More
3. Additional dialog will appear
4. Switch to another app and switch back to Files App (Alt+Tab)
5. See error

**Expected behavior**
The sub context menu should be hidden when users switch app.

**Screenshots**

https://user-images.githubusercontent.com/69080584/126929391-2260f7f3-6cae-4822-9f71-36fb1fb33255.mp4

**System Information**
 - OS Version: Windows 10 21H1 9043.1110
 - App version: v1.9.14.0

**Additional comment**
Does this problem happen again after restarting the app? Yes

**Comment by gave92** [comment]
Closing this as WinUI issue. I'd recommend to open this on the WinUI repo.
