### ISSUE TITLE
Bug: If there are issues with a network drive no reason is given when clicked

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#5542]
**Explain the bug**
If there's any issue with a network drive like it not being found, cant authorise/log in or other reasons it wont show that and just open it as a empty folder.

**Expected behaviour**
Use a pop up to show the user the issue with connecting to the drive

**Steps to reproduce**
1. Map a network drive
2. Un-share drive from host or disconnect from network
3. Restart Files
4. Open network drive to see empty folder

**System Information**
Version: 1.9.14.0
OS Version: 10.0.22000.100

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by Josh-65** [comment]
Yes

**Comment by yaira2** [comment]
@Josh-65 can you fill out the repro steps and move to `Ready to build`?

**Comment by Josh-65** [comment]
Merging with #1100
