### ISSUE TITLE
Network option on sidebar should display items in grid mode by default

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5544]
**Describe the solution**
Having the list use detail view is quite point less since the only information would be the icon and name. having it go to grid mode would make it look nicer and make use of icons more.

**System Information**
- Version: 1.9.14.0
- OS Version: 10.0.19043.1110

**Comment by gave92** [comment]
Is this a request to change the default view mode for that folder to grid or is the issue that after setting grid view the view mode is not persisted when you visit that folder again?

**Comment by josh-65** [comment]
The issue is the default view should be grid mode. However I didn't realised it saved if set manually.

**Comment by josh-65** [comment]
Closing as it not an issue in 2.0.11.0. With manually settings the view mode.
