### ISSUE TITLE
Mabey a better way to give insider builds out

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5545]
**Is your feature request related to a problem?**
Currently it's kind of a hassle to get insider build. Users have to open the forum, enter the information, wait a few days and sometime manually check for updates to get it. I'm sure it also an annoying task for the one who puts the emails in too. It can also be annoying to switch back to the stable build if the user changes there mind (doesn't seem to have an official way of doing so in documentation) or just want both it compare it or something else.

**Describe the solution**
Why not making it like how Microsoft (e.g. Windows Terminal) does it they have a separate app with preview text added to the title and a "Pre" text added to the icon. Then users can just download the one they want instantly and without the extra steps of going in and out of preview builds.

**Comment by yaichenbaum** [comment]
There are a couple of reasons we don't but the main one is because of the approval process. Files uses restricted permissions in the store and it's not very simple to get them approved again.
