### ISSUE TITLE
Format drive should not be an option in the C drive

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5547]
**To reproduce**
1. Go to C drive
2. Right click
3. See Format option

**Screenshots**
![image](https://user-images.githubusercontent.com/26977075/126947965-44c7ec27-69a2-4059-83df-719b6859384e.png)

**System Information**
- App Version: 1.9.14.0
- OS Version: 10.0.19043.1110

**Comment by gave92** [comment]
Mmm does Explorer show it for the C drive?

**Comment by josh-65** [comment]
No

**Comment by gave92** [comment]
It will only open the format dialog ;)

**Comment by josh-65** [comment]
Good to know. However it should properly be remove from it if it not hard to do since it doesn't seem right for it to be there.
