### ISSUE TITLE
Allow users to set a default state for the sidebar in new tabs and windows

### ISSUE THREAD

**Issue by jacraff** [files-community/Files#5548]
**Is your feature request related to a problem?**
Yes. The problem is, when a user opens a new tab or window, Files does not respect the previous state of the sidebar, always defaulting to 'Open'. This means that the sidebar has to be closed after opening a new window or tab and this is especially frustrating when using Files as a small floating window because the sidebar takes up a lot of space and manually closing it every time is frustrating. 

**Describe the solution**
Ideally, the solution would be adding a new options list under the heading 'On Startup' in settings. This list should be under a subheading 'Sidebar on Launch' and have three options; 'expanded', 'collapsed' and 'unchanged' (with unchanged respecting its previous state).

**Describe alternatives you've considered**
Alternatively, the sidebar could be made to respect its previous state and this wouldn't need any extra settings - so if the user collapses the sidebar, it stays that way when closing Files, opening a new tab or window.

**Scope**

| Capability | Priority |
| :---------- | :------- |
| This proposal will remove an extra step for the end user to use the program efficiently | Must |
| This proposal will allow the end user to save space automatically when opening a new window or tab | Should |
| This proposal will provide the end user with a more seamless experience | Could |

**System Information**
 - OS Version: Windows 10 21H1 19043.1110
 - App version: 1.5.0.0

**Comment by josh-65** [comment]
the sidebar does save it state in insider build and will be available for version 2

**Comment by jacraff** [comment]
Great to hear!
