### ISSUE TITLE
Add a mass rename/extension changer

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5550]
**Is your feature request related to a problem?**
So I used google takeout to download my music files unfortunately it downloads them with a wired extension (It can be changed to .mp3 so they work again). however a mass extension change feature would be needed for it to be practical.

**Describe the solution**
Selecting the files and clicking on rename should bring up a prompted with a name and extension box. If left blank it would keep there original name/extension. Entering an value in the rename box will set that on all files with a number on the end so they don't conflict.

**Scope**
| Capability | Priority |
| :---------- | :------- |
| Mass extension changing | Must |
| Mass name changing| Should |

**Comment by yaichenbaum** [comment]
@josh-65 is there added value in us putting resources into this other than saving a download of PowerToys or other similar applications?

**Comment by josh-65** [comment]
I didn't know power toys had this feature. But it could be added for convenience of using one app.
