### ISSUE TITLE
Download folder when sorted by date, should group files and folders 

### ISSUE THREAD

**Issue by patryk-siewiera** [files-community/Files#5551]
**Describe the solution**
Download folder when sorted by date, should group files and folders 

**System Information**
- Windows 10, 21H1
 - App version: 1.5

<img width="1479" alt="screenshot_files_app" src="https://user-images.githubusercontent.com/45758580/126976920-a22f1e90-b9ab-421d-a56f-9e605615d750.png">

**Comment by josh-65** [comment]
This has been added for insider builds and will be available for version 2

**Comment by patryk-siewiera** [comment]
Thank you!
