### ISSUE TITLE
Software Rendering and 3D/GPU Acceleration

### ISSUE THREAD

**Issue by lollilol** [files-community/Files#5552]
**Is your feature request related to a problem?**
I have issues in UWP Apps with hardware acceleration while mining cryptocurrency.

**Describe the solution**
A toggle that enables me to use the file manager only with software rendering, just like Windows Terminal has:
![image](https://user-images.githubusercontent.com/38194372/126976796-d021c457-a91b-46a4-be31-8bcc45830ae9.png)

**System Information**
- [OS version] 21H1 Build 19043.1110
- [App version] 1.5.0.0

**Comment by gave92** [comment]
I'm not sure uwp have that option. What issues are you experiencing?

**Comment by lollilol** [comment]
its extreme UI lag
Windows Terminal Preview has that option too tho? do you use different backends?

**Comment by gave92** [comment]
I _think_ windows terminal is a classic desktop app (wpf) + xaml islands for UI. Files is a pure UWP app.

**Comment by vitorgrs** [comment]
> its extreme UI lag
> Windows Terminal Preview has that option too tho? do you use different backends?

Try to enable on registry this
**HKLM\SOFTWARE\Microsoft\XAML\** and create a dword **ForceWarp** and set to 1. But this will affect **all** UWP apps.

**Comment by duke7553** [comment]
@lollilol Does this issue exist when you aren't performing a GPU-intensive operation?

**Comment by lollilol** [comment]
No it doesn't

**Comment by duke7553** [comment]
Closing as wont-fix because this behavior is expected when GPU intensive operations are in progress. It's unlikely that Files is any more susceptible to graphical problems than other Windows apps.

**Comment by lollilol** [comment]
I didn't open the issue because i had problems, i opened the issue because i want to turn off hardware acceleration, thats my main point
