### ISSUE TITLE
Scroll position resets when delete a file (Video demo)

### ISSUE THREAD

**Issue by KryptoPX** [files-community/Files#5554]
**Explain the bug**
when delete a file, scroll position resets

**To reproduce**
1. go to any folder that have many files
2. scroll down
3. delete any file

**logfile**
[debug.txt](https://github.com/files-community/Files/files/6877780/debug.txt)

**Screenshots**
https://user-images.githubusercontent.com/79398439/126982452-cdf1ebd8-575c-4a79-847b-e98ab661a2a6.mp4

**System Information**
- Versión: 1.9.14.0
- OS Version: 10.0.22000.100

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
