### ISSUE TITLE
trusted applications not showing in context menu

### ISSUE THREAD

**Issue by RadNotRed** [files-community/Files#5556]
---> trusted applications not working (7zip, vsc, etc)

**Explain the bug**
Write a clear description of what the bug is.

**To reproduce**
1. Go to any folder that can be compressed by 7z, ect
2. it won't show an option to use 7z

**Expected behavior**
7zip or any other application should show up in context menu (as shown in crashmit's screenshot from the discord 
![image](https://user-images.githubusercontent.com/80015713/127014861-29fb8468-815a-4b7e-b7d6-2da1775aaf2f.png)
)

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6879358/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6879360/debug_fulltrust.log)

**Screenshots**
What I see compared to what crashmit sees above:
![image](https://user-images.githubusercontent.com/80015713/127015020-61843f2e-725a-4b1c-a908-c54528072de7.png)

**System Information**
 - OS Version: 
Edition	        Windows 10 Pro
Version	        20H2
Installed on	‎10/‎4/‎2020
OS build	        19042.1110
Experience	Windows Feature Experience Pack 120.2212.3530.0

 - App version: v1.1.9.14

**Additional comment**
Continues after restart, Yair said it was trusted applications crash and to make a report

**Comment by RadNotRed** [comment]
added new fulltrust log
[debug_fulltrust.log](https://github.com/files-community/Files/files/7028251/debug_fulltrust.log)

**Comment by gave92** [comment]
@RadNotRed if possible, could you try to delete the log files and post them after triggering the issue with the latest Files version?

**Comment by RadNotRed** [comment]
> @RadNotRed if possible, could you try to delete the log files and post them again after triggering the issue with the latest Files version?

cleared them and remade
[debug_fulltrust.log](https://github.com/files-community/Files/files/7085724/debug_fulltrust.log)

**Comment by gave92** [comment]
O.o I see no crash in the log this time. Could you check if you just need to scroll down the menu to see the fulltrust items?

**Comment by RadNotRed** [comment]
> O.o I see no crash in the log this time. Could you check if you just need to scroll down the menu to see the shell menu items?

yeah it doesnt have it even i try to scroll

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.11.0 or above?
