### ISSUE TITLE
Style Issue? Cannot read the text on a delete confirmation button.

### ISSUE THREAD

**Issue by adrynalyne** [files-community/Files#5558]
**Explain the bug**
The confirmation dialog when deleting a file(s) does not show text (Styling issue?).

**To reproduce**
1. Open Files.
2. Delete an item.
3.Notice the text on the confirmation button cannot be read.

**Expected behavior**
Should be able to read text on confirmation button

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6881187/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6881188/debug_fulltrust.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/246382/127058499-25dd30e5-d7e8-4540-b427-320ee51fb37c.png)

**System Information**
Edition	Windows 10 Pro for Workstations
Version	21H1
Installed on	‎7/‎18/‎2020
OS build	19043.1110
Experience	Windows Feature Experience Pack 120.2212.3920.0
Files Version: 1.9.14.0

**Additional comment**
Happens after restarting app.
OS is using dark mode.

**Comment by gave92** [comment]
Have you set a custom theme for Files? Is Files set to English?

Looks fine for me:

<img src="https://user-images.githubusercontent.com/9673091/127062776-dd0f26fc-af51-4e9f-9e52-c160d765131e.png" width="400" />

**Comment by adrynalyne** [comment]
No custom theme, English language.

**Comment by adrynalyne** [comment]
I am using a 10 bit color monitor though, and with 10 bit color, Windows 11 shows the same issue at the resolution I am running (3840x1600). Aside from this application, I've not seen this issue in Windows 10.

**Comment by adrynalyne** [comment]
Just to update: 1.9.18.0 still exhibits this issue.

**Comment by yaichenbaum** [comment]
@adrynalyne this appears to be a WinUI issue, can you report this on the WinUI repository? https://github.com/microsoft/microsoft-ui-xaml
