### ISSUE TITLE
Allow Navigation via Scroll Wheel Up/Down on Address Bar

### ISSUE THREAD

**Issue by rlaphoenix** [files-community/Files#5560]
**Is your feature request related to a problem?**
No.

**Describe the solution**
Ever need to quickly jump between neighboring folders? Perhaps to compare the files within them, or compare filenames or sizes? Then this can often be a highly productive and quick way of doing so.

**Describe alternatives you've considered**
N/A.

**Scope**
| Capability | Priority |
| :---------- | :------- |
| Next folder via Scroll Wheel Down | Must |
| Previous folder via Scroll Wheel Up | Must |
| Allow this functionality on any folder of the address bar | Should |
| Honor the parent folder's sorting/order when deciding which folder to navigate to | Could |

**System Information**
 - OS Version: Windows 11 21H2 22000.100
 - App version: V2 Beta

**Additional comment**
If you need to see what I mean in action, take a look at Dolphin. There are also beta/tinkery windows msvc binaries available on the KDE Jenkins build server that has the functionality. Simply open Dolphin, hover over a folder in the address bar, and scroll up or down.

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0? There is double click to go up a folder and there are the keyboard shortcuts (alt + up arrow to go up and alt + left arrow to go back). Its also clickable.

**Comment by yaichenbaum** [comment]
Merging with #5310
