### ISSUE TITLE
Cannot open shortcut location from properties panel

### ISSUE THREAD

**Issue by crazy-dave-create** [files-community/Files#5565]
**Explain the bug**
Opening shortcut file location from properties window gives error message

**To reproduce**
1. Right click on any short
2. Click on 'the shortcut'
3. Select Properties
4.  Navigate to shortcut tab
5. Click on 'open file location'
4. See the error

**Expected behavior**

'open file location' should open the location of the file

[debug_fulltrust.log](https://github.com/files-community/Files/files/6883180/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/6883182/debug.log)

**System Information**
 - OS Version: Windows 10 21H1 (OS Build - 19043.1110)
 - Version: 1.9.15.0

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5565.
