### ISSUE TITLE
Feature: Add bitrate info for audio files in properties windows

### ISSUE THREAD

**Issue by ghost** [files-community/Files#5566]
I just love this app but the biggest flaw in this app is that it doesn't have the bitrate details for an audio file in the details tab. Instead, there's an encoding bitrate but that's not what I need. The only reason I'm considering to switch back to file explorer is this. Hope you will implement it.

**Requirements**
- Display bitrate info in the details page of the properties window

![image](https://user-images.githubusercontent.com/78640436/127109883-dbf3738b-f854-4780-8b83-70066a0447dc.png)

**Comment by bsinky** [comment]
Maybe the solution here is to format the "Encoding Bitrate" in a friendlier way. For example, if the Encoding Bitrate is "320000" it would probably be more familiar to display it as "320kbps" (this is what File Explorer seems to be doing in its File Properties > Details tab as far as I can tell).
