### ISSUE TITLE
Ongoing task doesn't report status correctly

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5568]
**Explain the bug**
When a task is started sometimes the ring doesn't appear on the icon and in the menu it just says 0% progress for a long time then either stay like that or show completed

**Expected behaviour**
It should show the percentage. if a task is being prepared (e.g. Discovering files) it should have the loading ring around the button icon

**Logs**
[debug.log](https://github.com/files-community/Files/files/6887948/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6887949/debug_fulltrust.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/26977075/127122267-4954fe96-f991-4111-aa98-2cf86b67a257.png)

**System Information**
- Version: 1.9.15.0
- OS Version: 10.0.19043.1110

**Comment by gave92** [comment]
Have you found this happening only with "Move to recyclebin" operation or with others too (e.g move/copy/permanent delete)?

**Comment by josh-65** [comment]
its happen with everything

**Comment by josh-65** [comment]
Closing as it does not seem to be an issue in 2.0.11.0
