### ISSUE TITLE
Copy/cut operations not working

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5569]
**Explain the bug**
Sometimes when I copy/cut then paste it doesn't copy the files it will do one of the folders and then show it completed with no files or other folders. Click and drag will also do that same.

**Expected behaviour**
It should copy all files/folders

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6884313/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6884314/debug_fulltrust.log)

**System Information**
- Version: 1.9.15.0
- OS Version: 10.0.19043.1110

**Comment by gave92** [comment]
Hi, do you find this still an issue in 1.9.21?

**Comment by josh-65** [comment]
Haven't seen it happen again yet

**Comment by gave92** [comment]
Thanks! Please let us know if it does.
