### ISSUE TITLE
Add taskbar status for average operation progress

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5575]
**Is your feature request related to a problem?**
Currently it not that easy to see if tasks have started or are done without opening the operation centre.

**Describe the solution**
Like Edge and File explorer do it
![image](https://user-images.githubusercontent.com/26977075/127151430-bdf5b3f1-1a5a-49fa-8a81-39e91df0ad0e.png)

**Scope**
| Capability | Priority |
| :---------- | :------- |
| Show average status of operations in taskbar| Must |

**System Information**
- Version: 1.9.15.0
- OS Version: 10.0.19043.1110

**Comment by esibruti** [comment]
@yair100 
After doing research, I think this might help introduce this functionality.

[Link 1](https://docs.microsoft.com/en-us/dotnet/api/system.windows.shell.taskbariteminfo?view=net-5.0)
[Link 2](https://docs.microsoft.com/en-us/dotnet/api/system.windows.shell.taskbaritemprogressstate?view=net-5.0)

**Comment by josh-65** [comment]
Merging with #6266
