### ISSUE TITLE
Crash when changing view on Google Drive

### ISSUE THREAD

**Issue by smuyo** [files-community/Files#5576]
**Explain the bug**
When you change the view from icons to details on a Google Drive folder with no subfolders, Files crashes. 
Once Files has crashed, if you try to open the folder again the program crashes, not letting you access said folder.

**To reproduce**
1. Open a Google Drive folder with no subfolders.
2. Change view from icons to details.
3. Files crashes.
4. Open Files.
5. Double click on the folder where the crash happened.
6. Files crashes.

**Expected behavior**
Change the view on the folder.

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6885330/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6885331/debug_fulltrust.txt)

**System Information**
 - OS Version: Windows 10 Home
        Version 21H1
        Compilation	19043.1149
        Windows Feature Experience Pack 120.2212.3920.0

 - App version: v1.5.0.0
 - Google Drive version: 49.0.9.0

**Comment by gave92** [comment]
Thanks for this report. This issue is fixed in the beta version of Files.
