### ISSUE TITLE
Context Menu Still Exist When Click on Extract Files

### ISSUE THREAD

**Issue by esibruti** [files-community/Files#5578]
**Explain the bug**
When selecting the option to extract, in a zip file, the context menu won't close and still exist.

**To reproduce**
1. Right click on a zip file
2. Click on Extract -> Extract files
3. See the error

**Expected behavior**
The context menu should close after users click this button.

**Screenshots**

https://user-images.githubusercontent.com/78214358/127172040-7b0522f9-7257-43d0-a29a-3bb7c4fe4e4f.mp4

**System Information**

- OS Version: Windows 10 Home
   21H1
   19043.1110
   Windows Feature Experience Pack 120.2212.3530.0

- App version: v1.9.15.0

**Comment by gave92** [comment]
Thanks for this report. Is the issue only for extract or for any submenu?

**Comment by esibruti** [comment]
@gave92 It's just on the extract.

**Comment by esibruti** [comment]
@gave92 I've been thinking about your question and then I've been testing it and I've found that after all, it also happens with other options.
It does with the following:

- To extract;
- To set an image as a background;
- Print out;
- Rotate the image left or right, in which case we have to update the folder to see the image rotated;
- Scan in Windows Defender;
- Restore previous versions;

Possibly there will be more but I just tested this. If you want, I can make a demo video.

**Comment by gave92** [comment]
It happens when you click on any item that is in a submenu (does not happen for items in the main menu). Sounds about right?

**Comment by esibruti** [comment]
https://drive.google.com/file/d/112g3JfsrlYZLQmYMWedx1ECRFbQjfbto/view?usp=sharing

@gave92 Watch this video. It demonstrates the bug

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5776.
