### ISSUE TITLE
Add option to open Files on Windows startup

### ISSUE THREAD

**Issue by mynando** [files-community/Files#5579]
**Is your feature request related to a problem?**
No

**Describe the solution**
On Windows 10, if you usually work with the same set of folders, instead of having to reopen them manually every time you sign into your account, you can enable an option that allows File Explorer to remember and resume your opened folders at startup automatically. This would be a great addition to Files to promote productivity.

**Describe alternatives you've considered**
Going back to the File Explorer which already does this.

**Scope**

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to quickly get back to their files after closing Files | Should |

**System Information**
 - OS Version: 10.0.19044.1149
 - App version: Version: 1.9.15.0

**Additional comment**
N/A

**Comment by esibruti** [comment]
@yair100 or @gave92 
This site has been around for some time but I think this could help implement this function.
https://blogs.windows.com/windowsdeveloper/2017/08/01/configure-app-start-log/

https://www.c-sharpcorner.com/article/startuptask-in-uwp-windows-10-fall-creators-update-features/

https://tipsfordev.com/specify-startup-monitor-for-uwp-app

**Comment by yaichenbaum** [comment]
@esibruti do you want to work on this?

**Comment by esibruti** [comment]
> @esibruti do you want to work on this?

@yair100 Of course, I do it. Just one thing, you have to have the option to turn it on and off right?

**Comment by yaichenbaum** [comment]
Yes

**Comment by esibruti** [comment]
> Yes

@yair100 Okay I'll take care of it :)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7309
