### ISSUE TITLE
Extract Strings in English Appear in Other Languages

### ISSUE THREAD

**Issue by esibruti** [files-community/Files#5580]
**Explain the bug**
This bug arises because there are no such translatable strings in other languages. Occurs only in extract options.

**To reproduce**
1. Right click on a zip file
2. Click on Extract and select any option
3. Go to Ongoing tasks
4. See the error

**Expected behavior**
Normally, strings should appear in the language the program has defined.

**Screenshots**

https://user-images.githubusercontent.com/78214358/127183382-950468ee-fff0-4332-91ed-b5469ec8cd1b.mp4

The video above shows the string in English and Files in Portuguese.

**System Information**
- OS Version: Windows 10 Home
   21H1
   19043.1110
   Windows Feature Experience Pack 120.2212.3530.0

- App version: v1.9.15.0

**Comment by BanCrash** [comment]
Yep, it seems that those strings are untranslated.

@yair100 if you approve the triage you can assign this to me if you want to.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5590.
