### ISSUE TITLE
Drive shown full even if that's not the case.

### ISSUE THREAD

**Issue by nolombic** [files-community/Files#5581]
**Explain the bug**
Files shows the remaining space of a drive as completely filled up once Windows claims the drive has as issue/problem with it.

**To reproduce**
1. Insert a DVD-RAM Disc
2. Provoke Windows to think the drive has a problem. This can be done by starting up Linux (in my case Zorin OS through Dual Boot, a VM with the drive mounted should probably be sufficient as well). A folder named "System Volume Information" should be written to the drive (you'll have to enable the showing of hidden files).
3. Back in Windows the drive will now be recognized as having a problem. At this point Files will show the drive as being completely full to the last bit.
Based on this process and it appearing with the existence of "System Volume Information" I'm guessing a USB Drive or anything else will work as well for this (with similar results probably).

**Expected behavior**
Files should display the remaining disc space correctly (for DVD-RAM typically x out of 4.7-ish GB).

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6887345/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6887349/debug_fulltrust.log)
Upload the log file here for us to understand your issue better. 

**Screenshots**
![Screenshot 2021-07-27 162500](https://user-images.githubusercontent.com/67807622/127194758-9a3a20ba-afee-43a0-bac2-5a8efddaed8d.png)
![Screenshot 2021-07-27 175525](https://user-images.githubusercontent.com/67807622/127194761-49d05da7-d51b-40b8-8edf-6c91684c9f1d.png)

**System Information**
 - OS Version: Windows 10 21H1 19043.1110
 - App version: v1.9.15.0

**Comment by nolombic** [comment]
Yeah, but I'm starting to think it might be a general Windows issue because Windows Explorer can't seem to write to the drive with that folder in place.

**Comment by Josh-65** [comment]
I will close this for now then. Feal free to make a comment if you have it with other ones as well
