### ISSUE TITLE
Choice of preview handlers

### ISSUE THREAD

**Issue by Svk1190** [files-community/Files#5582]
**Is your feature request related to a problem?**
For some filetypes (such as cbz, djvu, etc) the preview pane only shows the cover page. The subsequent pages cannot be previewed. For some filetypes, the preview pane shows a limited number of pages (for example a pdf can be previewed for 10 pages). So the default previewer cannot show the full preview of many filetypes. 

**Describe the solution**
Many applications offer their own preview handler. For example Adobe Acrobat and Sumatra PDF offers their own preview handler. I can choose the preview handlers to render the preview for specific filetypes. For example, I can use the Adobe handler for previewing PDF, and I can use Sumatra PDF to preview CBR/CBZ files. 

**Describe alternatives you've considered**
I use windows explorer along with Stephen Taub's [preview handler association editor](http://web.archive.org/web/20070207075925/https://msdn.microsoft.com/msdnmag/issues/07/01/PreviewHandlers/default.aspx), which is shown in the images below. 
![image](https://user-images.githubusercontent.com/12389625/127225351-fd6ef1bc-d19b-417b-a253-19de6efa5f7a.png)
![image](https://user-images.githubusercontent.com/12389625/127225582-deec45cf-fa1b-4194-9a0c-aa50c0ad396a.png)

**Scope**
| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to preview files using custom handlers| Should |

**System Information**
 - OS Version: [e.g. Windows 10 21H1 19043.1110]
 - App version: [e.g. v1.5.0.0] 

**Additional comment**
None

**Comment by winston-de** [comment]
Thanks for the feedback. Unfortunately it is not currently possible to host shell preview handlers within Files as a framework limitation. Also, the 10 page limit was put on the pdf preview because the windows pdf rendering api uses a lot of memory, which unfortunately would causes crashes.

**Comment by winston-de** [comment]
It's possible this will become a possibility if/when Files switches to the windows app sdk, so reopening.

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by hez2010** [comment]
> @hez2010 is this something that will make sense with your work?

Added to the TODO list.

**Comment by yaichenbaum** [comment]
Is there an issue to track the progress?
