### ISSUE TITLE
Feature: Default Terminal application should be Windows Terminal, PowerShell, CMD in that order of Availability

### ISSUE THREAD

**Issue by rlaphoenix** [files-community/Files#5583]
**Is your feature request related to a problem?**
No.

**Describe the solution**
When you first install Files, it should default to using Windows Terminal, PowerShell, or CMD, in that order of Availability. This is instead of simply assuming CMD as the default.

**Describe alternatives you've considered**
N/A

**Scope**
| Capability | Priority |
| :---------- | :------- |
| Default to Windows Terminal if available | Must |
| Default to PowerShell if available | Must |
| Default to Command Prompt if neither were available | Must |

**System Information**
 - OS Version: Windows 11 21H2 22000.100
 - App version: v1.9.15.0

**Additional comment**
It's generally recommended by most to consider the order of preference to be Microsoft Terminal > PowerShell > CMD. Windows itself is also doing the same order of preference.

**Comment by Wtcheesecakes** [comment]
Just adding a comment I personally use windows terminal but know a lot of people will used cmd over powershell and terminal (Most people probably don't even have terminal installed on win10)

**Comment by rlaphoenix** [comment]
> 
> 
> Just adding a comment I personally use windows terminal but know a lot of people will used cmd over powershell and terminal (Most people probably don't even have terminal installed on win10)

I'm not saying force people to use it in the preferred order, I'm saying it should default to it. If the user really does want CMD, even though they have Microsoft Terminal or PowerShell, then they can change back to CMD in the settings.

**Comment by Wtcheesecakes** [comment]
I think it should default to terminal if it's installed but would need files to check that, Which I'm not sure how easy that is

**Comment by yaichenbaum** [comment]
This seems reasonable being that Terminal will be installed by default on Windows 11,.

**Comment by MarcAnt01** [comment]
> This seems reasonable being that Terminal will be installed by default on Windows 11.

Yep, also the context menu in Windows 11 explorer "open with terminal" uses it

**Comment by fatpowaranga** [comment]
I would add that there should be a layer added, if pwsh.exe or Cross-Platform PowerShell 7 is detected, it should be used after Windows PowerShell. Some people might know them as Black PowerShell and Blue PowerShell, with the Blue PowerShell being the older however still more reliable version as far as Windows OS Management goes. 

Although, that being said this particular piece may be worth having as it's own ticket and also may need to be re-reviewed as Microsoft has pointed a few times that they are looking to replace Windows PowerShell with the newer PowerShell 7/Core when the time is right.
