### ISSUE TITLE
Allow pressing Enter on a Delete Confirmation Dialog to proceed with the deletion.

### ISSUE THREAD

**Issue by rlaphoenix** [files-community/Files#5584]
**Is your feature request related to a problem?**
When I press SHIFT+DEL to delete some files, I'm used to Windows asking if I'm sure with a Yes/No prompt, with Yes auto-focused. This allowed me to simply press SHIFT+DEL+Enter to proceed.

**Describe the solution**
Like Windows File Explorer's own Dialog, it would be ideal to autofocus on the "Delete" button so I can simply press enter.

**Describe alternatives you've considered**
N/A

**Scope**
| Capability | Priority |
| :---------- | :------- |
| Press Enter on a Delete Confirmation Dialog to proceed with Deletion | Must |
| Mouse should not need to be used | Should |

**System Information**
 - OS Version: Windows 11 22000.100
 - App version: v1.9.15.0

**Additional comment**
N/A

**Comment by yaichenbaum** [comment]
@rlaphoenix this should already be implemented in v1.9.15, can you check if it ever works?

**Comment by rlaphoenix** [comment]
> 
> 
> @rlaphoenix this should already be implemented in v1.9.15, can you check if it ever works?

I've tried already. It seems to focus on the first file in the list of items to be deleted, so pressing enter tries to click on the file rather than the button.

**Comment by rlaphoenix** [comment]
Ok strangely I've retried again, and it now works fine. That's quite odd. I was definitely testing this on v1.19.15 too.

**Comment by rlaphoenix** [comment]
**I've found out why!** The bug in question only occurs if the "Permanently delete" is disabled (cannot be unticked). E.g. while deleting from the Recycle Bin.

**Comment by d2dyno1** [comment]
This has been resolved with #7882
