### ISSUE TITLE
Better management of column sizes and auto-sizing

### ISSUE THREAD

**Issue by rlaphoenix** [files-community/Files#5585]
**Is your feature request related to a problem?**
I don't find it helpful whatsoever that each column resizes proportionally to the window size. E.g. by default without any manual changes, each column is equal in size to each other. Why would the File name and Size columns need to be the same size?

My main trip with this is I would ideally like each column to be a default set size (like win explorer), but allow some columns to fill the remaining untaken space of the window (like Dolphin and Directory Opus).

**Describe the solution**
Let's say I wanted to always have the Filename column take up as much space in the window as it can, without eating up the space I set for the other columns. This isn't currently possible in Files. If it was possible, it would allow me to always see the full filename length unless my window is too small or the other columns' *hardcoded* space is too large. I could then resize either the columns to be smaller to allow more space for the Filename column or make the window larger to give more space for all columns.

**Describe alternatives you've considered**
I tried manually resizing each column and such to get as best I could with the sizing, but at the end of the day it did not pan out. It felt very annoying as I constantly had to be messing with the column sizes to get what ultimately could be done automatically.

**Scope**
| Capability | Priority |
| :---------- | :------- |
| Allow one column to be a filler column (take up all leftover horizontal space) | Must |
| Do not resize the columns with the window sizing (otherwise resizing the app doesn't give more space to the filler column) | Must |
| Filler column will push other columns outside the visible view space (e.g. overflow out the right side of the window) | Won't |
| Name column should be larger in size by default compared to other columns | Could |

**System Information**
 - OS Version: Windows 11 21H2 22000.100
 - App version: v1.9.15.0

**Additional comment**
Before you may potentially pass off this as a misunderstood feature request, you may not potentially understand the productivity and UX improvements this brings along. You should give Directory Opus's Free Trial a shot, which has this feature. You can set any one column as a filler column in settings (e.g. the Name column) so that you don't constantly have to meddle with column sizes to see long filenames in full, as it optimizes the space based on what space is left over after the other columns take their needed space.

Here's an example of the same folder showing how annoying it is to see the full file names compared to Directory Opus with a filler column on Name:

![image](https://user-images.githubusercontent.com/17136956/127215919-ed9e2021-eabf-4705-bd97-9b9adfd3e509.png)

**Comment by rlaphoenix** [comment]
Something like the following where I can have Name column automatically fill, globally, across all folders is what I ultimately would want. We shouldn't have to manually resize columns for something that should be simple.

![image](https://user-images.githubusercontent.com/17136956/127219010-0d8a8ee7-16df-445b-a83d-e18d36d4cce1.png)

(Ignore the scrollbar, see #5587)

**Comment by Hefaistos68** [comment]
One might add that remembering column size and visibility settings is a must, not necessarily on the folder level but at least globally.

**Comment by yaichenbaum** [comment]
Merging with #6448
