### ISSUE TITLE
Details Layout has a small bit of blank space on the right causing scrollbar to appear

### ISSUE THREAD

**Issue by rlaphoenix** [files-community/Files#5587]
**Explain the bug**
E.g. after "Size" column, there's a tiny mini bit of an empty column that when you resize other columns (e.g. Name) to move the last column (in my case Size) to the very edge of the window, as indicated by its border-right of the Size column header, it causes a Horizontal scrollbar to appear, as if there's some text I've overflowed.

**To reproduce**
1. Open any folder, and assume you only have 3 columns. Name, Date modified, and Size.
2. Enlarge the Name columns width to move size to the far right of the window's edge.
3. You will notice a horizontal scrollbar appears as if you overflowed some text or content, but you haven't.

**Expected behavior**
It shouldn't show the scrollbar as there was no content in what was hidden.

**Logfile**
N/A. It's unnecessary.

**Screenshots**
As you can see below, I've moved the size column to the very edge, and it still thinks there's content there so it shows a scrollbar.

![image](https://user-images.githubusercontent.com/17136956/127218270-e863c490-5415-49bc-9c45-ea9d5181ac40.png)

**System Information**
 - OS Version: Windows 11 21H2 22000.100
 - App version: v1.9.15.0

**Additional comment**
N/A

**Comment by gave92** [comment]
Thanks for opening this feedback item. That's done on purpose to always let you resize the last column easily. If there's no space you'd risk resizing the window instead.

**Comment by rlaphoenix** [comment]
I see now that its the same happening on the left-most column, a bit of space for resizing the column.

May I ask for an option in settings to remove or condense this then?

**Comment by josh-65** [comment]
It could just make more sense to have it padded so that there will always be space whether the scrollbar is at the end or not.

**Comment by edge261** [comment]
This behavior it's the same when you resize a window with this view activated... it can become annoying.

**Comment by yaichenbaum** [comment]
As @gave92 mentioned, this is the intended behavior, and it lines up with other apps such as File Explorer.
