### ISSUE TITLE
Blue highlight on files get stuck if you drag after selecting

### ISSUE THREAD

**Issue by rlaphoenix** [files-community/Files#5588]
**Explain the bug**
If you click a file, then drag it, the Blue pill/highlight on the left of the file gets stuck until you click away from it and re-click it, and again click away from it.

**To reproduce**
1. Click any file
2. Click, hold, and drag around and just let go of the drag so it doesn't move the file anywhere.
3. Repeat for a few files and you will notice they are all stuck.

The file you drag does not have to be the file you clicked that you are trying to get stuck.

**Expected behavior**
When dragging the Blue pill/highlight should be removed.

**Logfile**
N/A. Not necessary.

**Screenshots**
![image](https://user-images.githubusercontent.com/17136956/127219684-1c1647ff-38b4-47a4-8b9c-6dfab1f4d600.png)

**System Information**
 - OS Version: Windows 11 21H2 22000.100
 - App version: v1.9.15.0

**Additional comment**
It gets unstuck once you do anything that would refresh its state, that includes changing the folder, restarting, etc.

**Comment by gave92** [comment]
Thanks for this report. Could you confirm this is purely a "visual" issue? Meaning if you press say Delete key does it try to delete all items with the blue pill or only the "truly selected" ones?

**Comment by rlaphoenix** [comment]
Correct. Purely visual. It only asks to delete the truly selected ones.

**Comment by gave92** [comment]
Merging with #6778
