### ISSUE TITLE
Allow removing Favorites from the sidebar via Sidebar settings (Like Libraries, Drives, WSL)

### ISSUE THREAD

**Issue by rlaphoenix** [files-community/Files#5589]
**Is your feature request related to a problem?**
I do not wish to have a Favorites section as I do not use one. All I need is Libraries, Drives, etc to satisfy my navigation needs. Since the others have an appropriate option to hide it from the sidebar, I don't see why Favorites can't be added too.

**Describe the solution**
Add Favorites to the Settings -> Sidebar section. "Show favorites section on the sidebar" with it defaulted to On, allowing you to choose Off.

**Describe alternatives you've considered**
N/A

**Scope**
| Capability | Priority |
| :---------- | :------- |
| Allow favorites section to be hidden from the Sidebar | Must |
| Add the option to Settings -> Sidebar | Must |

**System Information**
 - OS Version: Windows 11 21H2 22000.100
 - App version: v1.9.15.0

**Additional comment**
N/A

**Comment by gave92** [comment]
We would need to figure out what to do with Home and Recycle bin sidebar items. If favorites section is hidden there is currently no way to access Recycle bin.

**Comment by yaichenbaum** [comment]
@gave92 They would be considered favorites so if the user wishes, I don't see why they shouldn't be able to unpin the whole section.

**Comment by rlaphoenix** [comment]
I agree yeah, I won't ever be using the Home and Recycle Bin items. And it's not like the project is worried about people being unable to access the recycle bin as there is an option to hide the Recycle Bin already.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5675.
