### ISSUE TITLE
Cloud Drives not displayed

### ISSUE THREAD

**Issue by NPAUDEL** [files-community/Files#5596]
**Explain the bug**
Sidebar sometimes displays physical drives in place of cloud drives, creating duplicate, and not showing cloud drives.

**To reproduce**
1. Open Files
2. Go to "Preferences"
3. Click on "Sidebar"
4. Enable "Show drives selection on the sidebar" and "Show drives selection on the sidebar"
5. Two drop down menu for drives are present, instead of cloud drive.

**Expected behavior**
One drop down for physical drives and one for cloud drive displayed.

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6889960/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6889963/debug_fulltrust.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/54449465/127256492-f82bd78a-bfa2-4709-8307-ee3c3bf7fb31.png)

**System Information**
 - OS Version: [ Windows 11 Pro 21H2 22000.100] 
 - App version: [Version: 1.9.15.0]
**Additional comment**
This problem doesn't always occur, but most of the time. Occasionally it shows the cloud drives, but that does not depend on restarting the app or the system.

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
