### ISSUE TITLE
creating new folders & files doesn't work

### ISSUE THREAD

**Issue by stem2580** [files-community/Files#5597]
**Explain the bug**
creating folders & files doesn't work

**To reproduce**
1. right-click -> new -> folder
2. type a name
3. click set name
4. folder won't be created

**Expected behavior**
a folder with the name I choose should be created

**Logfile**
[debug_fulltrust.log](https://github.com/files-community/Files/files/6890244/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/6890246/debug.log)

**Screenshots**
https://user-images.githubusercontent.com/37732484/127262505-96ed9fd9-293f-4a6f-aa1f-ae67d1cfc61d.mp4

**System Information**
 - OS Version: Windows 11 21H2 22000.100
 - App version: 1.9.15.0

**Additional comment**
this problem happens again after restarting the app
& creating folders from windows explorer works fine so it's not the drive's fault

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
