### ISSUE TITLE
Implement Windows 11 style context menu

### ISSUE THREAD

**Issue by gulshanmudgal** [files-community/Files#5598]
**Is your feature request related to a problem?**
Right now, Files follows Windows 10 style context menu where all the context menus are listed in the main pane, or they can be viewed by clicking on more. 

**Describe the solution**
What I'm proposing is only the app name should appear under the context menus and relevant context items should be grouped under the app name. That way Context menu can house multiple app names and also most of the context menus would be easily accessible.

**Describe alternatives you've considered**
Other alternative is to give icons for Copy/Cut/Paste/Rename/Properties in second row.

**Scope**

| Capability | Priority |
| :---------- | :------- |
| File Management related commands icons (such as pin, share, copy path etc)should be displayed at top | Must |
| File Manipulation related command icons should be housed(such as Cut/Copy/Paste/Delete) in a separate row | Good To Have |
| App which adds file related context menus, those app names should be listed | Must |
| App-specific context menus should be listed under the app name | Must|

**System Information**
 - OS Version: Windows 11 21H1 OS Version: 10.0.22000.100
 - App version: Version: 1.9.15.0

**Additional comment**
Adding Screenshot for the same:
![image](https://user-images.githubusercontent.com/11193392/127265391-b525dc40-f5d8-44a7-b680-883848263171.png)

So like KDIFF3 is listed and housing relevant context menus, In similar fashion Winrar/Git/Gitextension related context menus should be grouped and listed under the main context menu pane itself.

**Comment by yaichenbaum** [comment]
> File Management related commands icons (such as pin, share, copy path etc)should be displayed at top

This was a deliberate decision to help users identify the most important options faster. This change was made based on initial feedback that showed that having the most important options in the context menu pinned to the top was slowing users down.

**Comment by gulshanmudgal** [comment]
yes, since it would be a design change initially it might affect the workflow, but slowly people can get accustomed to icons, and it would be better for usability. 

Right now, the Delete command icon is placed among File management-related commands, as per me, ideally it should be clubbed with Cut/Copy/Paste/Rename section.

I'm changing the priority to good to have.

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.

**Comment by gulshanmudgal** [comment]
I believe points 3 and 4 are still not implemented.

**Comment by yaichenbaum** [comment]
> I believe points 3 and 4 are still not implemented.

@gulshanmudgal sorry for the delayed response, can you add some more context on what you're asking for each of those requests?

**Comment by gulshanmudgal** [comment]
Sure, No Issues @yair100.

Multiple applications register shortcuts to the context menu. Any application can add one or multiple shortcuts to the context menu. 

For Windows 11, Microsoft recommends clubbing all the shortcuts under a submenu, and in the main context menu, the application name is displayed. Currently, OneDrive is the only application that supports this kind of behavior and is listed under the main context menu.

![image](https://user-images.githubusercontent.com/11193392/135960165-495080f5-ee70-4383-9c39-b0926f87d65c.png)


in #3 and #4 what I mean is if we can have a context menu that can intelligently club all the shortcuts into a submenu would be better. Instead of having to click on More and then accessing the shortcuts, what can be done is just have one Context menu and list all the applications which register context menu shortcut(s).  And then hovering/clicking the Application name in the context menu should give us all the related shortcuts for that application.

For example, KDiff supports multiple context menu shortcuts, it lists them inside a submenu, which is what we want so we will put it into the main context menu. But then Git Extensions doesn't do that so the Files app will intelligently group them, and in the main context menu, we shall have Git Extensions with a submenu with all the shortcuts just like KDiff or OneDrive.

This is a sample context menu for the same:
![image](https://user-images.githubusercontent.com/11193392/135962467-184e4c0d-d9fe-4882-8ba6-c420a7b03bab.png)


In the end, we would have a very simple yet powerful context menu.

**Comment by gulshanmudgal** [comment]
Currently this is how it looks like, Like a forest:
![image](https://user-images.githubusercontent.com/11193392/135962969-9a7284df-c9e4-4d79-8eca-7d2075b8f831.png)

**Comment by yaichenbaum** [comment]
@gulshanmudgal seems like a reasonable request, can you open a new issue for that one so it doesn't get lost?

**Comment by gulshanmudgal** [comment]
Sure

**Comment by gulshanmudgal** [comment]
@yair100 I've created the issue https://github.com/files-community/Files/issues/6346

**Comment by yair100** [comment]
> @yair100 I've created the issue #6346

Thanks!
