### ISSUE TITLE
Rename using mouse click is easily triggered and is unstable

### ISSUE THREAD

**Issue by xezrunner** [files-community/Files#5600]
**Explain the bug**
Clicking to select files/folders at their names unintentionally triggers the rename functionality. During multi-selection, the rename functionality is still invoked and can crash the app.

**To reproduce**
1. Open Files and navigate to a folder.
2. Click on different items' names. _Timing doesn't matter, you just have to click one item after the other._
3. Observe how the rename functionality is invoked unintentionally.
_Additionally:_
_4. Try selecting multiple files using Ctrl / Shift + clicking_
_5. Observe how the rename functionality is invoked on the first selection item only._
_6. Now try selecting and unselecting the first selected item._
_7. The app should crash._

**Expected behavior**
- Rename using single-click should not be triggered this easily.
- Rename using single-click should not work while multiple items are being selected.

**Logfile**
Since the app crashed during the recording of this bug, I'm including a log file here.
I was holding Control and selecting folders. Check recording below.
[debug.log](https://github.com/files-community/Files/files/6892362/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6892363/debug_fulltrust.log)

**Screenshots / screen recordings**
https://user-images.githubusercontent.com/8061077/127310052-60aca982-4cfe-4d32-8290-97ce85b6d87a.mp4

**System Information**
 - OS Version: Windows 11 21H2 build 22000.100 (co_release)
 - App version: 1.9.15.0

**Additional comment**
- Perhaps there could be a toggle for whether renaming using single-click is enabled.
- Click to rename should only be invoked when the user has selected the item **and** clicked on the name label. It should **not** trigger when the user selects another item _(Is it checking against a global 'is item selected' variable?)_

**Comment by yaichenbaum** [comment]
@xezrunner is this the same issue as #2963?

**Comment by xezrunner** [comment]
@yair100 No, that issue is in regards to the textbox and its cursor/focus behaviors, **once rename has been invoked**. This one is about the app invoking the rename function unintentionally during simple selection.

**Comment by xezrunner** [comment]
With version 1.9.18.0 and commit https://github.com/files-community/Files/pull/5635, click-renaming is no longer erratic when selecting items and cannot be invoked when selecting multiple items.
