### ISSUE TITLE
BUG! Files program closes itself automatically when opening it.

### ISSUE THREAD

**Issue by iolandoguimaraes** [files-community/Files#5605]
![image](https://user-images.githubusercontent.com/88102299/127354482-19c5827c-7c8b-447a-85f9-532c54745d85.png)

Error Description: 

This error appears when I click on the Files program icon to open it.
The "Files" program opens, but then this message appears, shown in the attached image. The message says:
"Error!

Files has encountered an issue that the developers have not yet prepared for. "

And I can't do anything else within the program. Then the Files program closes itself automatically.

I also posted an attached video that demonstrates what is happening.

It was working normally. It happened after updating my Intel audio and video driver:  "Intel Audio for Screens" version 10.27.0.10. 

Device name:

LAPTOP-FC8O4M1J

System Information:

Windows 10 Pro - 21H1 19043.1110

App version: 

1.5.0.0

Thank you.

https://user-images.githubusercontent.com/88102299/127373929-d382e41a-b74b-481e-9fb3-0cc4b9e1fbdd.mp4

**Comment by iolandoguimaraes** [comment]
It happened after updating my Intel audio and video driver.

**Comment by yaichenbaum** [comment]
@iolandoguimaraes can you please fill out the issue template?

**Comment by iolandoguimaraes** [comment]
> @iolandoguimaraes você pode preencher o modelo de emissão?

 Yes. Is it correct now?

**Comment by iolandoguimaraes** [comment]
> @iolandoguimaraes can you please fill out the issue template?

Yes. I think I corrected it. Is it correct now?

**Comment by iolandoguimaraes** [comment]
> @iolandoguimaraes você pode preencher o modelo de emissão?

I uninstalled and re-installed the program and it is working perfectly again.
