### ISSUE TITLE
Application crashed when deleting folder

### ISSUE THREAD

**Issue by hunterlan** [files-community/Files#5606]
**Explain the bug**
App is crashed, when trying delete folder, which request administrator

**To reproduce**
1. Go to any folder, which can be deleted only by admin
2. Try to delete folder
3. See window, with request of getting admin rights, allow it
4. See the crash

**Expected behavior**
Deleted folder, continue work with app.

**Logfile**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6896209/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6896211/debug.txt)

**System Information**
 - OS Version: Windows 10 20H2 19042.1110
 - App version: v1.5.0.0

**Comment by gave92** [comment]
Thanks for this report. This should be fixed in the beta version.
