### ISSUE TITLE
Keyboard shortcut to open current/selected directory in terminal.

### ISSUE THREAD

**Issue by Tropix126** [files-community/Files#5607]
**Is your feature request related to a problem?**
Many programs such as VSCode have a global shortcut to open a terminal in the selected project or folder (typically <kbd>Ctrl</kbd> + <kbd>`</kbd>). While the native file explorer doesn't support this, I believe that it would be a convenient thing for Files to include.

**Describe the solution**
Add a keyboard shortcut to open the selected folder in the user's terminal of choice.

**Describe alternatives you've considered**
None.

**Scope**

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow the use of the keyboard to open the user's terminal. | Must |

**System Information**
 - OS Version: 11 22000.100
 - App version: 1.9.15.0

**Additional comment**
None

**Comment by puppetsw** [comment]
Mind if I take this issue on?
