### ISSUE TITLE
Add ability to re-organize sidebar menu

### ISSUE THREAD

**Issue by DeveloperWOW64** [files-community/Files#5609]
**Describe the solution**
In Files, although you can pin and unpin items to the sidebar, you cannot re-arrange them.
Idea: Have a simple UI opened when the user Right clicks on 'Favourites' -> 'Customize' that dims the app, except the sidebar, and allows the end-user to simply drag and drop items in the sidebar.

**Scope**

| Capability | Priority |
| :---------- | :------- |
| Add the ability to re-arrange sidebar | Must |
| Have a simple UI that allows users to drag-and-drop items in sidebar.| Should |

**System Information**
 - OS Version: Microsoft Windows 10 Version 21H1 Build 19043.1110
 - App version: 1.9.15.0

Notes: Thanks to @!!! prod. mindzy#4456 from the Files discord for helping with this idea.

**Comment by DeveloperWOW64** [comment]
I think this is a duplicate of #1069. Can anyone tell me if it is?

**Comment by yaichenbaum** [comment]
@DeveloperWOW64 yeah, #1069 is the same issue 🙂
