### ISSUE TITLE
[Sidebar] Cloud Drives section replaced by another one after a reboot

### ISSUE THREAD

**Issue by Yohan-Janolin** [files-community/Files#5610]
**Explain the bug**
At launch, the Cloud Drives section in the sidebar is replaced by the Drive Section or the Library Section. It results in a double Drives Section or a double Library Section. I have to uncheck the "Show cloud section" in the settings and then recheck it in order to have the correct OneDrive folder appears

**To reproduce**
Go to Settings, activate the "Show Cloud drives section on the sidebar"
Close Files
Reboot
Open Files, the Library Section or the Drives Section would be appearing twice and the Cloud Drive Section is missing

**Expected behavior**
Don't have a section that appears twice and have the right section displayed

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6899161/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6899163/debug_fulltrust.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/57586103/127461617-92ec4ed4-782d-4431-adbd-0bf7edf9c742.png)

**System Information**
 - OS Version: Windows 11 22000.100
 - App version: v1.9.15.0

**Additional comment**
Happens every time after a reboot. Do not seems to occurs when closing Files and reopen it

**Comment by Yohan-Janolin** [comment]
Another additional comment : closing Files and reopen it make the duplicated Section to change. For example, after the reboot, the Drives Section is duplicated. If I close Files and reopen it, the Library Section will be duplicated instead of the Drives Section. In all cases, the Cloud Drives Section is always missing

**Comment by yaichenbaum** [comment]
This issue should be resolved in 1.9.16.
