### ISSUE TITLE
Make Ribbon quick action icons similar to default File Explorer

### ISSUE THREAD

**Issue by Jack7511** [files-community/Files#5611]
**Is your feature request related to a problem?**
In Ribbon quick action icons layout and smaller size looks weird compared to default file explorer of windows 11.
Especially the colour of icons because usually accent colour is dark, it looks bad.

Screenshots attached for comparison.

Files
![files](https://user-images.githubusercontent.com/68644741/127493727-eb7a3b8b-ffad-48a7-9b07-6f5f36e1537d.png)
Default file explorer
![file explorer](https://user-images.githubusercontent.com/68644741/127493723-eb3dbe64-9173-4d29-9ade-a98b56249e3c.jpg)

**Describe the solution**
Make the layout, size and colour of icons similar to default file explorer of windows 11.
I wouldn't mind if you straight up copy the exact same layout from windows 11 file explorer to Files.

**Describe alternatives you've considered**
None.

**Scope**
| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish better Files design| Should|

**System Information**
 - OS Version: Windows 11 build 22000.100
 - App version: v1.9.15.0

**Additional comment**
None

**Comment by yaichenbaum** [comment]
@Jack7511 can you add some more context on why you feel this change is necessary? Files isn't the same as File Explorer and we don't usually copy File Explorer just for the sake of it.

**Comment by YashJogani** [comment]
@yair100 Just open default file explorer and files side by side and you will notice icons in files are bit smaller, spacing is less too and default file explorer icons pop out little more because of bright blue colour. At least try to change the secondary colour of those icons from accent colour to bright blue like in default file explorer.
