### ISSUE TITLE
.iso files do not have delete option

### ISSUE THREAD

**Issue by kamilli0n** [files-community/Files#5612]
Version: 1.9.16.0
OS Version: 10.0.19043.1149

While right clicking an iso file, the top row of icons are missing including delete

**Comment by gave92** [comment]
Thanks for this report. Could you post a screenshot of the context menu appearing for .iso files VS other files?

**Comment by kamilli0n** [comment]
I was wrong about it being related to a file type, this occurs for files at the bottom of a details view folder

that last couple files at the bottom do not have the top row of icons

NO ICONS
![iso-context](https://user-images.githubusercontent.com/12013369/127508106-4b4c291e-2995-4779-a72c-27df5fac3ccf.png)

ICONS
![zip-context](https://user-images.githubusercontent.com/12013369/127508153-c72e0552-c4e6-4d7f-95ac-1f5c7e761f94.png)

**Comment by josh-65** [comment]
The screenshots show the top quick action button are at the bottom witch is what support to happen

**Comment by kamilli0n** [comment]
You are correct, got a bad screenshot of error, see image below

![Screenshot 2021-07-29 104517](https://user-images.githubusercontent.com/12013369/127513052-b2481d84-b659-44f0-a5e9-0d8f321a68c1.png)

**Comment by gave92** [comment]
Thanks, this is related to a WinUI bug, there's an issue open on their repo, closing.
