### ISSUE TITLE
Change combo boxes width on the settings page to auto

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5613]
**Is your feature request related to a problem?**
Currently the three boxes are different sizes with look odd.

**Describe the solution**
The boxes should be the same size (would also fix Windows terminal text being cut off)
![image](https://user-images.githubusercontent.com/26977075/127510510-632feb80-6f2a-4b94-8772-bff72d9c645a.png)

Also "edit terminal actions" should be in a related links bar like in windows 11 settings have on some options. 

**System Information**
- App Version: 1.9.16.0
- OS Version: 10.0.19043.1110

**Comment by yaichenbaum** [comment]
The combo boxes are meant to have different sizes but it's probably a good idea to remove the hardcoded sizes to account for different languages.

**Comment by Jaiganeshkumaran** [comment]
It would be better if the combo box on the right of the card instead to be consistent with the Settings app.

**Comment by josh-65** [comment]
There wouldn't be room with the current width of the settings pop out if they make it auto/bigger size. Since the options text would be bigger than the room available at least for the first 2.
