### ISSUE TITLE
Have useful links auto expanded in settings about

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5614]
**Describe the solution**
The settings page right now is a fixed size with leaves room for the useful link column to be expanded without hiding any other option. Also windows 10 does this with some options so it could fit better with that.

**System Information**
- App Version: 1.9.16.0
- OS Version: 10.0.19043.1110

**Comment by yaichenbaum** [comment]
Thank you for your feedback, we are working on adding other elements to the about page so it's probably best to keep it collapsed for now.
