### ISSUE TITLE
Focus on secondary action on the delete confirmation dialog in recycle bin

### ISSUE THREAD

**Issue by DuCanhGH** [files-community/Files#5617]
Bug credit: ninopiamonte#7007 on Discord
**Explain the bug**
In Recycle Bin, when you click Delete, the focus box is first on the filename, and it's unnecessary to have the focus box on it.
**To reproduce**
1. Delete a file (not permanently)
2. Go to Recycle Bin
3. Click Delete (maybe the window should be maximized since I see the focus box appear more often)
**Expected behavior**
The focus box will be on the filename first.
**Screenshot**
https://user-images.githubusercontent.com/75556609/127519696-8719d3da-58db-46a7-8265-6ae83be105ee.mp4
Image (more like a video) credit: ninopiamonte#7007
**System Information**
OS version: Windows 11 Pro for Workstations 21H2 22000.100
App version: 1.9.16.0
**Additional comment**
I think the focus box can skip the filename, since it is not actionable.

**Comment by yaichenbaum** [comment]
I think we can focus the actions instead to solve this issue.

**Comment by gave92** [comment]
Mering with #5584
