### ISSUE TITLE
Internal drag and drop for dual plane

### ISSUE THREAD

**Issue by KristofKekesi** [files-community/Files#5626]
### What's the Problem?

Drag a folder and drop it on the other dual mode plane to open it

### Solution/Idea

```markdown
The problem is that drag and drop is already implemented for coping and mobing files and folders.
A rectangle could do the trick. If the mouse with the dragged element is outside of the rectangle it is moving the element, but if it is inside of the rectangle it would open the folder on the pane. (Only dragged folders should make the rectangle to appear becouse files couldn't be opened at a pane)
```

### Alternatives

```markdown
The context menu is cool too.
```

### Files Version

1.9.17.0

### Windows Version

Windows 11 Pro 21H2 22000.100

**Comment by KristofKekesi** [comment]
![heh](https://user-images.githubusercontent.com/64812024/127651079-f2a56f89-5334-49a7-b10f-64ed26b62333.png)
Look at the right bottom.

**Comment by MalteTasler** [comment]
I would rather consider a context menu entry. Drag and drop should be reserved for moving or copying elements like the user expects it.

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.11.0 or above?

**Comment by yaichenbaum** [comment]
v2.3.12 has a context menu option for this
![image](https://user-images.githubusercontent.com/39923744/193436428-13c391af-bad7-4bed-b0ec-cc295dcc864a.png)
