### ISSUE TITLE
Thumbnails of images are cropped into squares

### ISSUE THREAD

**Issue by Darhagonable** [files-community/Files#5631]
### Description

Thumbnails of images are cropped into squares
![image](https://user-images.githubusercontent.com/14127357/127717298-0a6eb243-64ff-4b0f-835f-6b1d420f52af.png)

### Steps To Reproduce

1. Go to Pictures folder
2. See image thumbnails being cropped into squares

### Expected behavior

Thumbnails of images to not be cropped

### Files Version

1.9.0.0

### Windows Version

Windows 10 21H1 19043.1083

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5717.
