### ISSUE TITLE
Drag-and-drop support for adding file to zip archives

### ISSUE THREAD

**Issue by trparky** [files-community/Files#5632]
### Solution/Idea

```markdown
I'd like to see drag-and-drop support similar to how standard Windows Explorer works. For instance, selecting some files and dragging them onto a ZIP file to be added to a ZIP or 7ZIP file.
```

### Alternatives

```markdown
None.
```

### Files Version

v1.9.17

### Windows Version

Windows 10 21H1 19043.1151

**Comment by gave92** [comment]
Thanks for opening this feedback item. Could you clarify if this is a request for ability to drag-and-drop unto zip archives or if you're also finding other issues with drag-and-drop?

**Comment by trparky** [comment]
I can't drag and drop files onto a ZIP file, or in this case, a 7ZIP file. It gives me a red icon when I try to do so.

**Comment by gave92** [comment]
Should be good with #9633
