### ISSUE TITLE
Properties details page text boxs dont show unless hovered over

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#5636]
### Description

as title says

### Expected behavior

The box should always be there

### Files Version

1.9.17

### Windows Version

10.0.19043.1110

**Comment by josh-65** [comment]
This seem to happen for any text box in the properties menu (Details view)

**Comment by Josh-65** [comment]
This now only applys to the details page

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`. (the details page is by design)
