### ISSUE TITLE
The application failed when I use the context menu!

### ISSUE THREAD

**Issue by estrelaporvenus** [files-community/Files#5638]
### Description

The aplication failed when I try to acess the context menu!

### Steps To Reproduce

1. Open Files. 
2. 2. Access one of the directories
3. select one archive
4. try to access the context menu
5. the aplication failed and restart

### Expected behavior

I expeted to acess the context menu normaly.

### Files Version

Versão: 1.9.17.0 

### Windows Version

Windows 11 Version: 10.0.22000.100

**Comment by josh-65** [comment]
You will need to upload the logs folders. You can get them in files settings > about > open log folder

**Comment by estrelaporvenus** [comment]
[debug.log](https://github.com/files-community/Files/files/6913563/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6913564/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
@estrelaporvenus is this still an issue in v1.9.32?

**Comment by estrelaporvenus** [comment]
No! Since v1.9.24 the context menu works properly! Thanks! 👏🏿🖤
