### ISSUE TITLE
Drag & Drop file into folder inconsistent 

### ISSUE THREAD

**Issue by justb7** [files-community/Files#5639]
### Description

I am unable to drag and drop a file into a subfolder consistently. It works flawlessly sometimes and then other times it just shows the red do not sign. 

### Steps To Reproduce

1. Open any folder that has both files and subfolders  
2. Drag a file from that folder into a subfolder

### Expected behavior

Ability to drop file into any folder

### Files Version

v1.9.17.0

### Windows Version

Windows 11 21H2 22000.100

**Comment by MalteTasler** [comment]
Having this issue too with column view.

**Comment by Firedrops** [comment]
Having this issue as well, I think it's related to #4571 and #5466.

One little workaround that sometimes work is to click on a file first, let it become "selected", give it a second (just so it doesn't register as a double-click), then click again to do drag-and-drop.

**Comment by yaichenbaum** [comment]
Merging with #7195
