### ISSUE TITLE
When renaming link files the .lnk extension gets removed

### ISSUE THREAD

**Issue by mangoepic** [files-community/Files#5643]
### Description

When renaming link files the .lnk extension gets removed

### Steps To Reproduce

1. Click on a .lnk file
2. Press F2 to rename
3. Rename it anything
4. 
![image](https://user-images.githubusercontent.com/71931749/127763221-f1fb81b6-cb7f-435e-b44c-556d8709524c.png)

### Expected behavior

The .lnk file extension stays

### Files Version

1.5

### Windows Version

21H1

**Comment by josh-65** [comment]
This has been fixed in the current insider builds and will be available for v2
