### ISSUE TITLE
Creating link files using alt+drag isn't working (it only shows "Link" hovering over Desktop)

### ISSUE THREAD

**Issue by mangoepic** [files-community/Files#5644]
### Description

Creating link files using alt+drag isn't working (it only shows "Link" hovering over Desktop)

### Steps To Reproduce

Desktop:
1. Go to any folder in files
2. alt drag any file to the desktop
3. It shows "Link"
4. Let go
5. It doesn't create a .lnk file

Files alt drag inside the same Folder:
 - Action blocked

Files alt drag to sidebar folder:
 - Moves the file instead of creating a shortcut

### Expected behavior

See above

### Files Version

1.5

### Windows Version

21H1

**Comment by gave92** [comment]
Thanks for the report. This is fixed on main.
