### ISSUE TITLE
Improving the conflict dialog UI

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#5645]
![image](https://user-images.githubusercontent.com/39923744/150205770-d7f2b322-fc72-40b8-ac8a-f2d62f950d37.png)

**Comment by gave92** [comment]
Please try the following:
- Press Ctrl+A to select all
- Right click on an item
- Select an option from the context menu

**Comment by josh-65** [comment]
Cant try it now but that really isn't an obvious action and probably isn't for many users. I think there should be an option at the top saying apply to all with the drop down box so it more clear and works without a keyboard.

**Comment by gave92** [comment]
\+ @d2dyno1

**Comment by d2dyno1** [comment]
Wow! Somehow I missed that ping...

**Comment by d2dyno1** [comment]
@yair100 could you please ping me when the redesign of conflicts dialog is ready?

**Comment by yair100** [comment]
> @yair100 could you please ping me when the redesign of conflicts dialog is ready?

I can try 🙂

**Comment by Talisman39ar** [comment]
@yair100 Is there a design in progress for reworking the Conflicting File Names dialog? If not, I was thinking I'd take a crack at it

**Comment by yaichenbaum** [comment]
@Talisman39ar we're still working on a design spec. Are you in the Discord server?

**Comment by Talisman39ar** [comment]
No just here on git

**Comment by yaichenbaum** [comment]
@Talisman39ar can you join so we can work on this together?

**Comment by Talisman39ar** [comment]
Sure, my user name there is Richardsona39#8797 if you want to send an invite (sorry if I'm missing it, don't see a way to join it from within Git)

**Comment by yaichenbaum** [comment]
@d2dyno1 do you want to work on this?

**Comment by d2dyno1** [comment]
No, I'll be busy with #7540 and #7402

**Comment by pritster5** [comment]
Is it also possible to make Merging/Overwrite Existing the default option so that it matches the Windows File Explorer Default?

**Comment by Josh-65** [comment]
It will save what you last use from what i know

**Comment by DAmNRelentless** [comment]
I would **love** to see this! `CTRL + A` is not very obvious to use in that pop up.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #8914
