### ISSUE TITLE
Drag and drop mailfunction

### ISSUE THREAD

**Issue by Zemlen** [files-community/Files#5646]
### Description

It is hard to use drag and drop for some applications.
For example - I want to import some graphics to an opened CorelDRAW I drag the file from a folder opened in Files and try to drop it to an opened CorelDRAW document, but it simply doesn't allow me to do this. 
The same happens with Adobe Photoshop and some other applications, but everything works fine in a common windows explorer, which I have to use in such cases.
This is the only annoying thing, which stops me from using files as a default file browsing application.
This happened in Win10. The same issue with Win 11.
![image](https://user-images.githubusercontent.com/88270761/127766681-e3d5e4b0-66d6-4fab-9b5f-90eeac4a89e4.png)

### Steps To Reproduce

1 - Open CorelDRAW file.
2 - Open a folder in Files containing any Jpeg file
3 - Try to drag and drop file from a folder to a CorelDRAW document

### Expected behavior

I expect a Jpeg file to be imported to a CorelDRAW document just like it happens, when using Windows Explorer instead of Files.

### Files Version

v1.5

### Windows Version

Windows 11  21H2 Windows Feature Experience Pack 421.18901.0.3

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5650.
