### ISSUE TITLE
Feature: Environment variables should be sent to admininstrator program's

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#5648]
### Description

If I start a .bat file in C:\users as administrator it default to system32.

### Expected behavior

It should have C:\users as its start location.

### Files Version

1.9.17

### Windows Version

10.0.19043.1151

### Relevant Assets
[debug.log](https://github.com/files-community/Files/files/6912617/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6912618/debug_fulltrust.log)

**Comment by gave92** [comment]
Does Explorer behaves any different?

**Comment by josh-65** [comment]
Apparently not. Didn't realise it was a windows issue.

**Comment by gave92** [comment]
This is not to say it can't be done in Files, reopening this as a feature request but don't be surprised if this proves technically impossible to implement ;)

**Comment by yaira2** [comment]
@gave92 can we solve this by setting the working directory when we start the process?

**Comment by gave92** [comment]
You can try but this hints it won't work (and why).
> https://superuser.com/questions/1067901/how-to-open-command-prompt-in-a-specific-folder-as-administrator
Looks like you cant run the bat directly bu you need to do like (untested):
> cmd /c cd /d "~dp0" && call my_bat.bat
