### ISSUE TITLE
Context Menu Still Exist After Zipping Files

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#5654]
### Description

After trying to zip a file using WinRAR using right click on context menu, the context menu still exists although the file is zipped successfully.

### Steps To Reproduce

1. Right click on a file to be zipped
2. Click on More in the Context Menu
3. Click on `Add to {Files}.rar`

### Expected behavior

The context menu should be closed as the operation succeed.

### Files Version

v1.9.17.0

### Windows Version

Windows 10 21H1 19043.1151

### Relevant Assets

https://user-images.githubusercontent.com/69080584/127836798-3eac063d-8615-400e-a194-04ceb2ed8dff.mp4

**Comment by gave92** [comment]
See #5578
