### ISSUE TITLE
Move files between folders

### ISSUE THREAD

**Issue by onelucas** [files-community/Files#5658]
[debug.log](https://github.com/files-community/Files/files/6920055/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6920056/debug_fulltrust.log)

**Comment by gave92** [comment]
Does the crash happen when you drop items in a folder which has files grouped by name or type, etc.?

**Comment by onelucas** [comment]
No, the file display is ungrouped, and the icons are large. I usually move by holding and releasing on the flaps. But this also happens by cutting and pasting in the menu.

**Comment by gave92** [comment]
When it crashes do you get a notification saying "Files ran into a problem that the developers didn't prepare for yet." or does the app just close?

**Comment by onelucas** [comment]
It just closes. But I've seen this message a few times. But I confess I don't remember if it was related to that.

**Comment by gave92** [comment]
Could you delete the two log files and upload them again if (when) the next crash happens? Thanks!

**Comment by onelucas** [comment]
Okay. Do I copy it all over again, or just some snippet?

**Comment by onelucas** [comment]
Now, at 19:40 it closed again. Without that error message.

**Comment by gave92** [comment]
> Okay. Do I copy it all over again, or just some snippet?

Yu can just upload the file, no need to copy the text ;)

**Comment by onelucas** [comment]
I did a new test, and this time, the file transfer crashed, and that message you quoted came up. Updated logs.

**Comment by yaichenbaum** [comment]
@onelucas is this still an issue in 2.0?
