### ISSUE TITLE
Layout Mode and Group By

### ISSUE THREAD

**Issue by C0d3r6u01-3122** [files-community/Files#5661]
### Description

1) Reduce the Tiles View Size. The size tiles are being shown are too Huge! 
2) Add 'List, Content View' in layout mode. 
3) The Scrolling function stops after any Group By option is used. Have to left-click to make it work again.
4) Resizeable Settings window. Few items in it aren't viewed properly due to compressed window size. are

### Expected behavior

1) Medium Size Tiles View option. 
2) Presence of new view modes like 'List, Content View' etc.
3) Scrolling works without the need for left-clicking.
4) Medium size/ resizeable settings window.

### Files Version

v1.9.17.0

### Windows Version

Windows 11 21H2 v22000.100

**Comment by yaichenbaum** [comment]
Merging with #3009.
