### ISSUE TITLE
Have a move files UI 

### ISSUE THREAD

**Issue by aunight** [files-community/Files#5664]
### Solution/Idea

```markdown
I think it can have new moving files ui it will be more intuitive.
```

### Alternatives

```markdown
I will try to make a concept ui to discord.
Hope you can make it real!
```

### Priorities

```markdown
| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |
```

### Files Version

v1.5

### Windows Version

Windows10 20H2 19042.1110

**Comment by yaichenbaum** [comment]
@aunight we're having a hard time understanding the feature request, can you please add some more context to the issue?

**Comment by aunight** [comment]
![image](https://user-images.githubusercontent.com/52199445/127948806-c8258b11-2a74-4e4f-838e-cbc6d3987b8b.png)
I mean this ui.
Hope this can get a new fluent design in Files

**Comment by gave92** [comment]
Merging with #4811
