### ISSUE TITLE
Only able to drag Windows around if I click the upper right corner near the minimize button 

### ISSUE THREAD

**Issue by ClementYip1713** [files-community/Files#5665]
### Description

I can only drag the windows if I click the upper right corner near the minimize button.
If I click other area (e.g. the title bar cloer to the left or middle), the windows would not respond to dragging around.

This behavior is different from every other apps.  And different from built-in Windows File Explorer.

### Steps To Reproduce

1. Click near the Upper Right Hand corner of the window.  Near the minimize button.
2. See that I can successfully drag the windows around.
3. Now, click a bit more to the left (where I previously clicked to drag the window).
4. See that I can no longer drag the window.  The window simply would not respond.
 

### Expected behavior

I should be able to click anywhere on the entire title bar area (all the way from left to right), and be able to drag the window around.

### Files Version

1.5.0.0

### Windows Version

Windows 10 21H2

**Comment by gave92** [comment]
Fixed in insiders version.
