### ISSUE TITLE
The app keep crashing when I use the context menu

### ISSUE THREAD

**Issue by estrelaporvenus** [files-community/Files#5666]
### Description

When I click in some archive to access the context menu, the app just crash and restarts

### Steps To Reproduce

1. open files
2. access one of the directories
3. click with the right botton to access the context menu
4. ... the app crash, and a flyout/notification asking me to report the error shows up. :)

[debug.log](https://github.com/files-community/Files/files/6921584/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6921588/debug_fulltrust.log)
 

### Expected behavior

the context menu should open normally. 

### Files Version

Versão: 1.9.17.0 

### Windows Version

Windows 11 Version: 10.0.22000.100

**Comment by gave92** [comment]
Thanks for reporting this. The error in question is:
```
2021-08-03 03:32:10.9738|ERROR|AppUnhandledException|Layout cycle detected.  Layout could not complete.
Layout cycle detected.  Layout could not complete.
	Windows.UI.Xaml.LayoutCycleException: Layout cycle detected.  Layout could not complete.
Layout cycle detected.  Layout could not complete.
```
Seen this on AppCenter too, @winston-de you've got any ideas?

**Comment by winston-de** [comment]
> Thanks for reporting this. The error in question is:
> ```
> 2021-08-03 03:32:10.9738|ERROR|AppUnhandledException|Layout cycle detected.  Layout could not complete.
> Layout cycle detected.  Layout could not complete.
> 	Windows.UI.Xaml.LayoutCycleException: Layout cycle detected.  Layout could not complete.
> Layout cycle detected.  Layout could not complete.
> ```
> Seen this on AppCenter too, @winston-de you've got any ideas?

From what I know, a layout cycle exception generally occurs when the size is changed in a size changed event handler, which causes the size changed event to be triggered again, and a feedback loop occurs. It's basically thrown when there's recursion with the app layout.

My best guess is this is triggered when the shell items are added, which causes the command bar size to be reevaluated.

**Comment by estrelaporvenus** [comment]
i did the steps and it's working properly :)

Only the context menu has less options than before, after ending the fulltrust process task.
That's supposed to happen, right?

**Comment by yaichenbaum** [comment]
@estrelaporvenus is this still an issue in the preview version? https://files.community/download/preview
