### ISSUE TITLE
Rename the First Document Name in Grid View (Medium) Cause Another Files to shift

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#5667]
### Description

Rename the first document's name in Grid View (Medium) will cause another documents to get minimized.

### Steps To Reproduce

1. Surf to a folder which consists more than 1 document
2. Change Layout to Grid View
3. Click on rename (F2) on the very first document

### Expected behavior

Another document(s) should not get minimized.

### Files Version

v1.9.18.0

### Windows Version

Windows 10 21H1 19043.1151

### Relevant Assets

https://user-images.githubusercontent.com/69080584/127991805-1f05117d-fee5-432f-a18b-1d9f070eb5b9.mp4

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5674.
