### ISSUE TITLE
File duplicated during copying

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5668]
### Description

When I copy a file during copying/moving it will create the original file and another one with the copy thing at the end

![image](https://user-images.githubusercontent.com/26977075/127995648-82348e38-641f-49cb-a04c-97e1c3c84106.png)

### Steps To Reproduce
_No responce_

### Expected behaviour

It shouldn't make another file.

### Files Version

1.9.18

### Windows Version

10.19043.1151

### Relevant Assets
[debug.log](https://github.com/files-community/Files/files/6923159/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6923157/debug_fulltrust.log)

**Comment by gave92** [comment]
Thanks for this report.
- Does it happen repeatably?
- Does it happen when copying multiple files at once or also when copying a single file?

**Comment by josh-65** [comment]
I only tested it with a single file to a new empty directory and it happen 2/2 when I tested it

**Comment by gave92** [comment]
Uff can't reproduce.
- Do you find this happening only for "big" files?
- Do you find this happening only in "particular" locations, e.g network share?
- What happens if after the file gets duplicated you press "Ctrl+Z" (undo copy)? Do both files get deleted?
- What happens if after "Ctrl+Z" you press "Ctrl+Y" (redo copy)?

**Comment by josh-65** [comment]
I did it with an about 230GB file and i haven't tried the CTRL + Z and Y. It was from my internal HDD to my external bit locker enabled one

**Comment by josh-65** [comment]
I've had it happen with at under 200MB file transferring to a new folder on the same drive also in 1.9.19

**Comment by josh-65** [comment]
Merging with 5714

**Comment by gave92** [comment]
Reopening as I believe this has a different cause.. unless you verified that on 1.9.21 this issue does not happen anymore?

**Comment by josh-65** [comment]
Currently it hasn't with my backup file at 38% complete.

**Comment by gave92** [comment]
Thanks @josh-65, please let us know if it happens again.
