### ISSUE TITLE
Unknow crash in background

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5669]
### Description

The app was running in the background then just crashed.

### Expected behavior

.

### Files Version

1.9.18

### Windows Version

10.0.19043.1151

### Relevant Assets
[debug.log](https://github.com/files-community/Files/files/6923448/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6923449/debug_fulltrust.log)

**Comment by gave92** [comment]
> The app was running in the background then just crashed.

Meaning the app was minimized and at some point it terminated on its own?

**Comment by josh-65** [comment]
yes

**Comment by josh-65** [comment]
Hasn't happened again so I'm going to close this.
