### ISSUE TITLE
Themes duplicated

### ISSUE THREAD

**Issue by Wtcheesecakes** [files-community/Files#5671]
[debug_fulltrust.log](https://github.com/files-community/Files/files/6923880/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/6923882/debug.log)
### Description

Themes are showing duplicated in Files settings, Using the Themes for files from Store

### Steps To Reproduce

Open settings and they're duplicated

### Expected behavior

One set should show up

### Files Version

Version: 1.9.18.0

### Windows Version

21H1 19043.1110

**Comment by gave92** [comment]
Should be fixed by 9a5ca681b97c1bff6789498a6279af7356a7a766, but it's better to extract the commit to a separate PR.

**Comment by yaichenbaum** [comment]
@gave92 Looking good now.
