### ISSUE TITLE
Sidebar sections are not being showed well when you hide and show them repeatly

### ISSUE THREAD

**Issue by BanCrash** [files-community/Files#5676]
### Description

While testing #5675 I found that when you disable and enable sections, it shows and hides one random section, and sometimes one section has the icon as if it is expanded, but really it's not. See gif to understand this.

I tested this and also it's happening on last preview release, so it's not related with that PR.

### Steps To Reproduce

1. Go to Settings.
2. Enable all sections
3. Start disabling and enabling random sections.
4. Check the behaviour in the sidebar while you do the step 3.

### Expected behavior

It should show the section really expanded, or appearing as unexpanded.

### Files Version

1.9.18.0

### Windows Version

Windows 10 21H1 10.0.19043.1151

### Relevant Assets

![GIF 03-08-2021 23-12-48](https://user-images.githubusercontent.com/11770760/128087051-6b8844ed-36be-4442-9b57-f8fe60fa09c3.gif)

See the arrow of "Dispositivos y unidades" and "Unidades de red". It shows that it is expanded, but it isn't. I have to click two times to get it expanded, since the first click will contract it technically.
![image](https://user-images.githubusercontent.com/11770760/128087312-7841c7bf-f382-42b8-8483-d9bae43ff78b.png)

[debug_fulltrust.log](https://github.com/files-community/Files/files/6927109/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/6927110/debug.log)

**Comment by gave92** [comment]
Does it look like its related to whether se section is expanded or collapsed when it's hidden?

**Comment by yaichenbaum** [comment]
@BanCrash is this still an issue in the preview version? http://files.community/download/preview

**Comment by BanCrash** [comment]
> @BanCrash is this still an issue in the preview version? http://files.community/download/preview

It seems that it's fixed.
