### ISSUE TITLE
Unable to navigate to path if it has forward slashes

### ISSUE THREAD

**Issue by mpatel8** [files-community/Files#5678]
### Description

If path entered in navigation bar has forward slashes eg h:/bat_files then error reported unlike Windows Explorer which will navigate to the relevant path 

### Steps To Reproduce

1. Type c:/users in the navigation bar and error reported rather than navigating to c:\users

### Expected behavior

Similar to windows explorer, navigate to relevant path

### Files Version

v1.5.0.0

### Windows Version

Version 10.0.18363.1679

**Comment by yaichenbaum** [comment]
@gave92 can you reproduce this in `main`?

**Comment by gave92** [comment]
This is fixed on main

**Comment by mpatel8** [comment]
Sorry - my mistake - it does work in current version eg c:/temp

Observed that if it is a network drive then windows explorer is launched with that path open  eg A:/OLD_Data where A is mapped to a shared drive on another PC

![pre](https://user-images.githubusercontent.com/28053298/128363575-3fb433f8-2660-4f98-a3c4-9d2613a108b8.JPG)
![post](https://user-images.githubusercontent.com/28053298/128363595-295fafe6-6f9a-4f01-89cf-643fe1dcf8e1.JPG)
