### ISSUE TITLE
Can't open folder with keyboard when only one folder is in view

### ISSUE THREAD

**Issue by andreaslutsch** [files-community/Files#5681]
### Description

When there is only one folder inside a folder and you travel with the keyboard keys and try to open the folder with the enter key, the folder isn't opened even when it is focused.

https://user-images.githubusercontent.com/7101531/128199478-eeffea91-95f8-4b6d-85a7-d85eb94b6bb9.mp4

### Steps To Reproduce

1. Create a folder
2. Create a folder inside the newly created folder.
3. Use keyboard to enter the first folder.
4. The second folder is focused, but you cannot enter it with pressing enter.

### Expected behavior

When pressing enter, the single focused folder should open.

### Files Version

v1.9.18.0

### Windows Version

Windows 10 Pro 21H1 19043.1151

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7425
