### ISSUE TITLE
Grid View should have Rounded Corners

### ISSUE THREAD

**Issue by DakshG07** [files-community/Files#5682]
Honestly, I think grid view would look better with rounded corners. In the current setup, the video and image thumbnails have straight corners, which don't really match with the design.
![image](https://user-images.githubusercontent.com/48651837/128200463-4bcc85e1-d16f-4baa-b7ea-63ef6a475b48.png)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5717.
