### ISSUE TITLE
Hard to use scrollbar on the left panel

### ISSUE THREAD

**Issue by andreaslutsch** [files-community/Files#5683]
### Description

If you'd have a long list of pinned folders or many drives in the left panel, it is hard to grab the scrollbar because the panel resize bar is being selected instead. Also it is too sensitive to hover the mouse for the scrollbar to appear.

https://user-images.githubusercontent.com/7101531/128203190-86e7111f-7a4b-45e7-a902-b780dc48fa09.mp4

### Steps To Reproduce

1. Resize files so a scrollbar can appear on the left panel.
2. Try to quickly grab the scrollbar with the mouse cursor.
3. Move the scrollbar
4. In many cases, instead of moving the scrollbar, the panel gets resized.

### Expected behavior

It should be easier to hover over the scrollbar in the left panel and to use it. When clicking anywhere on the scrollbar, it should start scrolling instead of resizing the panel.

### Files Version

v1.9.18.0

### Windows Version

Windows 10 Pro 21H1 19043.1151

**Comment by yaichenbaum** [comment]
Yes

**Comment by yaira2** [comment]
This will be fixed in the next release
