### ISSUE TITLE
Cloud drive have different folder icons

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5686]
### Description

Compared to file explorer the cloud folders will have different icons.
Files:
![image](https://user-images.githubusercontent.com/26977075/128209692-bdcae8cc-48cc-4668-87d1-faaa17221d02.png) (Shows up on the sidebar like this also)

Explorer:
![image](https://user-images.githubusercontent.com/26977075/128209729-10652ff8-227c-4b43-92dd-8370f6a710b0.png)

### Expected behavior

They should not have a folder icon just the cloud drive icon in files

### Files Version

1.9.18

### Windows Version

10.0.19043.1151

**Comment by yaichenbaum** [comment]
What's the resolution on your display? This might have to do with your screen resolution as it appears to load differently on different devices.

**Comment by josh-65** [comment]
1920x1080

**Comment by gave92** [comment]
Explorer shows those icons as well in you navigate to the user folder, I guess that's why we're picking those up. Not sure how to fetch the sidebar icon.
<img src="https://user-images.githubusercontent.com/9673091/128242130-29aef2d7-fbbc-47ed-806c-bc15930b45fc.png" width="500"/>

**Comment by josh-65** [comment]
The icons in the file explorer screen shot is the normal folder not sidebar of it. But going into grid mode shows the same icon that files shows.

**Comment by josh-65** [comment]
It seems resetting the icons in file explore fixes it.
