### ISSUE TITLE
Unable to work with C: and D:

### ISSUE THREAD

**Issue by GitTomK** [files-community/Files#5692]
### Description

The app is unable to work with any files on C: or D:. It has no problems with attached drives. I have run through all Windows and App permission settings I can think of but have not been able to fix this. 

This is an extract from the log file, debug.txt.

2021-08-05 15:02:38.6981|INFO|.ctor|App launched|
2021-08-05 15:02:39.3341|WARN|.ctor|Unauthorized: Attempting to add the device, C:\, failed at the StorageFolder initialization step. This device will be ignored.|
2021-08-05 15:02:39.4031|WARN|.ctor|Unauthorized: Attempting to add the device, D:\, failed at the StorageFolder initialization step. This device will be ignored.|

### Steps To Reproduce

Run the app. Choose any file and attempt Open or Open With. Nothing happens.

### Expected behavior

"Open" should run the default app for the file and open it using that app.
"Open With" should open a menu of apps that are able to open the file.

### Files Version

1.5.0.0

### Windows Version

Windows 10 Pro Version	21H1 OS build	19043.1151 Windows Feature Experience Pack 120.2212.3530.0

### Relevant Assets

![Screenshot 2021-08-05 155142](https://user-images.githubusercontent.com/88475578/128298268-3ac6fe92-4a42-43d9-994d-ff4edc5b14e9.jpg)

**Comment by gave92** [comment]
Hello please check if in Windows Settings > Privacy > Filesystem, the filesystem permission is enabled.

**Comment by GitTomK** [comment]
Thank you. That fixed it. I had tried switching this on and off, but the "Files" app did not appear (and still does not appear) in the list of apps that "... can access your file system". So I had left the switch off. Thanks for suggesting that I try it again.
