### ISSUE TITLE
Always show status centre again

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5694]
### What's the Problem?

Currently it hide when there are no active tasks. So now it difficult to see what operations were done and if they even started or failed.

### Solution/Idea

Have it act like before an be always visible.

### Alternatives

None

### Files Version

1.9.18

### Windows Version

10.0.19043.1151

**Comment by gave92** [comment]
The plan is to hide it only when no operations have been started or when the user clears all messages from the fly out.

**Comment by josh-65** [comment]
I don't see a reason to hide it in the first place since there's enough room for it
