### ISSUE TITLE
Google drive for desktop doesn't show all files.

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5695]
### Description

In my documents .gdoc files and my password manager sync files disappear after a second of showing up
![image](https://user-images.githubusercontent.com/26977075/128395091-80dcf650-0e7a-4ab4-b125-bc62fab5175a.png)

### Expected behavior

The files/folders show up

### Files Version

1.9.18

### Windows Version

10.0.19043.1151

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/6940572/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6940574/debug_fulltrust.log)

**Comment by gave92** [comment]
Could you check if turning _off_ "Enable individual preferences for individual folder" under Files Settings > Files and Folders fixes the issue?

**Comment by josh-65** [comment]
yes it does.

**Comment by FernandoConsentino** [comment]
Hi guys, I'm sorry, but the problem still occurs, can you please make this issue open? If you need some additional information, please tell me. I sent you a video of the problem:

https://user-images.githubusercontent.com/82100470/128630661-61a6b8e6-9f75-4aa6-b3ad-12195276f6cf.mp4

Thanks!

**Comment by josh-65** [comment]
The issue is open

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5719.
