### ISSUE TITLE
Renaming a drive appends the drive letter

### ISSUE THREAD

**Issue by Patlen123** [files-community/Files#5696]
As the title says, if you rename a drive in the Files app it appends the drive letter every time despite that appearing by default so if you renamed the drive several times you'd end up with "Local Disk (C:) (C:) (C:) (C:)..."

**Reproduction Steps**

Right click a drive on the sidebar

Then go to properties

Rename the drive without getting rid of the drive letter

Save

This is on the Files v2 Insider Preview

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5719.
