### ISSUE TITLE
When delete file name including file extention, the warning dialog about file extention changed pops up

### ISSUE THREAD

**Issue by xwnb** [files-community/Files#5697]
### Description

When delete file name including extention, the file will be reset to the original name, but I don't think we should popup the warning dialog about file extention changed.

### Steps To Reproduce

1. choose a file with file extention
2. rename
3. clear file name
4. Enter or Lost focus to confirm renaming
5. file name reset
6. warning dialog popup

![image](https://user-images.githubusercontent.com/45145954/128442296-fec27d5d-8f62-4ff6-b192-8fffc8e6c66a.png)

### Expected behavior

The dialog should not be popped up.

### Files Version

Main

### Windows Version

Windows 10 21H1 19043.1110

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5719.
