### ISSUE TITLE
Files crashed when trying to drag and drop more than one file out of a zip file from explorer.exe

### ISSUE THREAD

**Issue by KillTrot** [files-community/Files#5701]
### Description

I have a zip file opened in explorer.exe and want to drag and drop the files to a folder opened in Files.
If I only drag and drop one file it is working fine, but as soon as I try with two or more files, Files crashes and leaves dead "Copy to ..." icons like this:

![image](https://user-images.githubusercontent.com/19376891/128464594-bd7578a1-56e1-4413-8b77-e30806763d29.png)

Also, it does not matter if the folder to copy into is empty or contains files or if those files are the same we are copying.

### Steps To Reproduce

1. Open a zip file in exporer.exe
2. Drag and drop more than one file into a folder opened in Files
3. -> Crash

### Expected behavior

Files should be copied and if any file already exists it should ask what to do like it does when we only copy one file.

### Files Version

Version: 1.9.19.0

### Windows Version

Windows 10 Pro 21H1 19043.1151

### Relevant Assets
[debug.log](https://github.com/files-community/Files/files/6943465/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6943466/debug_fulltrust.log)

_No response_

**Comment by xwnb** [comment]
It looks work well to me.😂

![image](https://user-images.githubusercontent.com/45145954/128493055-f931e2bd-dea5-418c-b6f6-e9ec8df1c40c.png)

**Comment by KillTrot** [comment]
> It looks work well to me even copying duplicated files.😂
> 
> ![image](https://user-images.githubusercontent.com/45145954/128493055-f931e2bd-dea5-418c-b6f6-e9ec8df1c40c.png)
> 

You're using 7zip, not the windows explorer to open the zip file 😀

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5719.
