### ISSUE TITLE
Press Ctrl and drag files can not clone the files in same folder.

### ISSUE THREAD

**Issue by xwnb** [files-community/Files#5702]
### Description

Press Ctrl and drag files can not clone the files. It is forbidden. By design?
![image](https://user-images.githubusercontent.com/45145954/128494482-a9bc336a-efa3-4d6b-81c2-516f5f56540e.png)

### Steps To Reproduce

1. press Ctrl and drag files in same folder
2. can not copy files

### Expected behavior

Clone files with automatically renamed as explorer.exe does.

### Files Version

v1.9.19

### Windows Version

Windows 10 21H1 19043.1110

**Comment by yaichenbaum** [comment]
@xwnb we've found that it gets triggered accidently way too often so we don't plan to implement this shortcut.
