### ISSUE TITLE
[UI-Looking / Colour]_Files Tab bar colour should look like this.

### ISSUE THREAD

**Issue by 2ndBillGates** [files-community/Files#5709]
### What's the Problem?

current using TAB's colour causing confusion

### Solution/Idea

In the present version, Tab bar's colour displays wrong.
![What-Files-app-Should-look-like_Compare](https://user-images.githubusercontent.com/60785205/128591904-c0a0d5de-d8c7-415f-8292-3d71f17da74e.jpg)

The Tab that's using should has the same colour like other region, like blending in. While the one that's not using, should be different from the whole UI. Or dimmer/ lighter.

I love this app and I want to replace the stock Microsoft FIleExplorer too. But that colouring is really confusing me recently and the app is a bit unstable. Sometimes it crashed/frozen when using the "Right click menu"/ TABs"

Hope you can fix it, thank you

### Alternatives

I made some other examples, you can take a look.
![What-Files-app-Should-look-like_Complete](https://user-images.githubusercontent.com/60785205/128591884-80cabdaa-41c7-4423-b8a4-77feaa8ebded.jpg)

I also upload these PSD for the pictures I made above, you can use and edit it for other look, to display or testing, hope you enjoy.
[Uploading What-Files-app-Should-look-like.zip…]()

Thank you for making this App

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

v1.5.0.0

### Windows Version

Windows 11 version 21H1 build 22000.120

**Comment by gave92** [comment]
Thanks for this suggestion. The next version of Files (v2) is going to have a whole new look. If you wish to try the beta versions you can join Files Insiders.

> Join the insider flight group
You can fill out this form to get access to the preview builds in the Microsoft Store https://forms.office.com/r/UsaBmzC99n. It can take a couple of days until you're added to the flight group, but once added, you will start receiving updates to the regular Files app through the Microsoft Store.
