### ISSUE TITLE
Bulk deletion of files is slow

### ISSUE THREAD

**Issue by qwer130140190** [files-community/Files#5710]
### Description

When more than 70 files are selected for deletion, the deletion speed is particularly slow, which takes about 30 seconds. These are very small files, which is not normal, and my laptop fan has been noisy. I guess there may be a performance problem

### Expected behavior

It is hoped that the deletion operation can be completed faster like the built-in explorer

### Files Version

v1.5

### Windows Version

Windows 11 22000.120

**Comment by gave92** [comment]
Thanks for this report. File operations speed has been much improved in the beta version. If you wish to try it you can join Files Insiders.

> Join the insider flight group
You can fill out this form to get access to the preview builds in the Microsoft Store https://forms.office.com/r/UsaBmzC99n. It can take a couple of days until you're added to the flight group, but once added, you will start receiving updates to the regular Files app through the Microsoft Store.
