### ISSUE TITLE
Errors during file copy from Android device

### ISSUE THREAD

**Issue by AugustFalcon9** [files-community/Files#5711]
### Description

Have no idea what the bug is. Just got a message from Win10 saying "Something went wrong! Files ran into a problem that the developers didn't prepare for yet." 

### Steps To Reproduce

1. Attach an Android 11 device with a USB C cable.
2. Open the device in its own Files Window
3. Navigate to the SD card subdirectory containing your MOV files
4. Ctl-A to select all files
5. Right click and select copy
6. Open a new Files window
7. Navigate to the USB connected D drive
8. Open the Movies subdirectory and Paste the files

### Expected behavior

I expected it to copy the files to the subdirectory. There were a few hundred files averaging about 95 MB each.
What happened was that it seemed to copy the files although as they appeared in the new location they were selected (all but one of them near the end) <--- Didn't expect that. Nor did I expect the four error messages I got,

### Files Version

v1.5.2.0

### Windows Version

Edition	Windows 10 Home Version	21H1 Installed on	‎6/‎11/‎2020 OS build	19043.1151 Experience	Windows Feature Experience Pack 120.2212.3530.0

**Comment by gave92** [comment]
Thanks for this report, could you upload the app's debug files?

**Comment by AugustFalcon9** [comment]
I can't seem to find any debug files for the app! I tried searching using the terms "debug" and then "log" and searching using the modifier time is today but had no luck. If you could give me the file name or location I will look further.

**Comment by AugustFalcon9** [comment]
Oops... should have read a little further, sorry!
[debug.txt](https://github.com/files-community/Files/files/6949784/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6949785/debug_fulltrust.txt)

**Comment by gave92** [comment]
Thanks this issue should be fixed in the beta version of Files.
