### ISSUE TITLE
Missing and inconsistent icons

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5713]
### Description

Right clicking white space:
![image](https://user-images.githubusercontent.com/26977075/128613509-c3e737a7-0d99-4e55-a51f-91221ee2d377.png)

Right clicking Path bar:
![image](https://user-images.githubusercontent.com/26977075/128613513-41320c19-d1cd-4bdd-b7e8-27c867bf79a6.png)

The new item and properties icons are not the same as the others and path bar used completely different icons with the select all one missing.

### Expected behavior

.

### Files Version

1.9.19

### Windows Version

10.0.19043.1151

**Comment by Rick-HM** [comment]
Some time ago they said that the context menu icons of the path bar cannot be modified. I do not know if currently it still cannot be modified.

**Comment by winston-de** [comment]
> Some time ago they said that the context menu icons of the path bar cannot be modified. I do not know if currently it still cannot be modified.

Yeah, the path bar context menu is managed by winui not Files.

the properties and new item menu items aren't using the colored icon, thanks for catching that

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5715.
