### ISSUE TITLE
Context Box not Being Closed Immediately after Click `Open With` Options

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#5718]
### Description

The latest dev version brings up the `open with` feature in flyout at context menu, however when users click on the options there or choose another app, the context menu still exists there / not immediately closed as in the file explorer.

### Steps To Reproduce

1. Right click on a file (for example a .pdf file)
2. Click on Open With
3. There will be several options (Google Chrome, Adobe Acrobat, Edge, Choose Another App, etc)
4. Click on one of the available options
5. See the error

### Expected behavior

The context menu should be closed when users clicked on the options.

### Files Version

v1.9.20.0

### Windows Version

Windows 10 21H1 19043.1151

### Relevant Assets

Files Explorer:

https://user-images.githubusercontent.com/69080584/128621657-936fa55e-df23-447b-9627-b2cd35be3f6f.mp4

Files:

https://user-images.githubusercontent.com/69080584/128621613-f21beb74-a3ab-4f97-91dc-32a57400b3a2.mp4

**Comment by gave92** [comment]
Merging with #5578
