### ISSUE TITLE
Crash when accessing quest storage

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5720]
### Description

^

### Expected behavior

Should display the internal storage

### Files Version

1.9.20

### Windows Version

10.0.19043.1151

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/6950603/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6950604/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5712.
