### ISSUE TITLE
Incorrect string shown in Recent Files contextual menu when app language set to French.

### ISSUE THREAD

**Issue by Voxybuns** [files-community/Files#5721]
### Description

The "New tab" page has a section that shows recently opened files. Right-clicking one of them brings up a contextual menu, in which a few actions are available, one of them being "Clear all items".
However, when the app's language is set to "français (France)", said option is erroneously labelled "Créé le :" ("Created on:"). It's likely that this string belongs to a different label altogether.

### Steps To Reproduce

1. Open the app's settings.
2. Under "Preferences", set the language to "français (France)".
3. Restart Files.
4. On the New tab page, right click one of the items in the "Recent files" section.

### Expected behavior

This label should instead say something like "Supprimer tous les éléments".

### Files Version

v1.9.20

### Windows Version

Windows 11 Home 22000.120

### Relevant Assets

![files_issue](https://user-images.githubusercontent.com/42387308/128633944-ca4c7056-56d9-499e-894e-356501c998f4.png)

**Comment by gave92** [comment]
If you wish you can correct the translation yourself, you just need to fork the repository and edit the [language file](https://github.com/files-community/Files/blob/aeee14defc9f91977cfd0d38d6bf41ab01bb620c/Files/MultilingualResources/Files.fr-FR.xlf#L33).

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5735.
