### ISSUE TITLE
Multiple ideas / enhancements cuz im lazy to create multiple issues. Read.

### ISSUE THREAD

**Issue by m1karii** [files-community/Files#5722]
### Solution/Idea

Multiple ideas / enhancements listed below:

1. Option to hide search bar and turn it into a button, same way its already implemented in compact overlay
![path](https://user-images.githubusercontent.com/82673417/128634712-67fbf16e-ae30-4b34-bf05-4821a784d9dd.png)
![search](https://user-images.githubusercontent.com/82673417/128634720-227e0b11-42f5-473e-ba5d-68f93c44abaa.png)

2. Option to disable rename on double click as (idk if this happens to others too) sometimes double click opens the folder and sometimes it triggers rename of that folder and since i always rename from right click menu this (rename on double click) just gets in the way

3. Option to hide icons on tabs - I mean this is not a web browser. 90%+ times it will be folder icon and if you always have opened 10+ tabs like me, icons just take up unnecessary space

4. Add "Open as Administrator in Terminal..." to dropdown menu shown in image below (I would probably NOT put it in the right click menu... but you can do that TOO if you think its a good idea). this option would always trigger UAC prompt even if logged in as admin.
![](https://i.imgur.com/tGspDgf.png)

(following images are not mine i just took them from discord and edited them)
5. My OCD is just killing me looking at this... like why is it like this...
![before](https://user-images.githubusercontent.com/82673417/128635860-02fa1f5f-594f-496a-9227-96af18a922ad.png)
and not like this... ?
![after](https://user-images.githubusercontent.com/82673417/128635874-d1040220-64c1-4e28-a951-e389576bace3.png)

(not all of the following points are illustrated above)
- right sidebar / preview pane and left sidebar both inbetween top bar and bottom bar
- right sidebar / preview pane and left sidebar have same default width (adjustable by user and resettable to default)
- bottom bar either 100% height of top bar / 50% height of top bar / or completely removed
- different background for preview pane removed

### Priorities

fifth point / idea

### Files Version

v1.9.20

### Windows Version

Windows 11 Insider Preview Build 22000.120

**Comment by yaichenbaum** [comment]
@m1karii I know it takes time to open multiple issues and we appreciate the time that went into this, but for tracking purposes, we're going to have to close this issue as each of these are their own request.
