### ISSUE TITLE
Option to hide search bar and turn it into a button

### ISSUE THREAD

**Issue by m1karii** [files-community/Files#5724]
### Solution/Idea

Option to hide search bar and turn it into a button, same way its already implemented in compact overlay

![path](https://user-images.githubusercontent.com/82673417/128634712-67fbf16e-ae30-4b34-bf05-4821a784d9dd.png)
![search](https://user-images.githubusercontent.com/82673417/128634720-227e0b11-42f5-473e-ba5d-68f93c44abaa.png)

### Files Version

v1.9.20

### Windows Version

Windows 11 Insider Preview Build 22000.120

**Comment by yaichenbaum** [comment]
@m1karii thank you for opening this issue, can you explain the issue with the way it is right now and how hiding the text box will improve the experience for you?

**Comment by m1karii** [comment]
> 
> 
> @m1karii thank you for opening this issue, can you explain the issue with the way it is right now and how hiding the text box will improve the experience for you?

I don't really think I "have an issue" with the way it is now except that with the search bar hidden I think it 'd look cleaner.
There's also the minor disadvantage with the way it is now that when there's alot of subfolders/ they have long names you can't see the full path - this will always be an issue; what i'm proposing only reduces it by making the space for path larger but it's still not unlimited space...
Anyways: the main reason: it looks cleaner
Clarification: i am asking for switch in settings so every user has option to choose which way they prefer it.

also sry for not responding. i completely forgot i opened these issues.

**Comment by yaichenbaum** [comment]
@m1karii thanks for the update, we're working on other solutions for when there are long paths. As for adding an option, while there is a use case for it, I don't think this is something that many users would take advantage of so I'd prefer keeping it how it is since it's fine for most users.
