### ISSUE TITLE
Option to disable rename on double click

### ISSUE THREAD

**Issue by m1karii** [files-community/Files#5725]
### Solution/Idea

Option to disable rename on double click as (idk if this happens to others too) sometimes double click opens the folder and sometimes it triggers rename of that folder and since i always rename from right click menu this (rename on double click) just gets in the way

### Files Version

v1.9.20

### Windows Version

Windows 11 Insider Preview Build 22000.120

**Comment by yaichenbaum** [comment]
We're working on a fix for the double tap to rename toggling when it's not supposed to. Merging with #5672.
