### ISSUE TITLE
Option to hide icons on tabs

### ISSUE THREAD

**Issue by m1karii** [files-community/Files#5726]
### Solution/Idea

Option to hide icons on tabs - I mean this is not a web browser. 90%+ times it will be folder icon and if you always have opened 10+ tabs like me, icons just take up unnecessary space

### Files Version

v1.9.20

### Windows Version

Windows 11 Insider Preview Build 22000.120

**Comment by yaichenbaum** [comment]
The icons really make the most sense with custom icons since they help differentiate between tabs. My experience is that even when the icons are the default folder, it still helps brighten up the app with a little color. How many tabs do have open on a regular basis?

**Comment by m1karii** [comment]
5~8

**Comment by yaichenbaum** [comment]
@m1karii thank you for your feedback, we gathered feedback from a number of users and when asked if they were interested in an option to hide the icons, the majority preferred to keep them visible.
