### ISSUE TITLE
Add "Open as Administrator in Terminal when shift + right click..."

### ISSUE THREAD

**Issue by m1karii** [files-community/Files#5727]
### Solution/Idea

Add "Open as Administrator in Terminal..." to dropdown menu shown in image below (I would probably NOT put it in the right click menu... but you can do that TOO if you think its a good idea). this option would always trigger UAC prompt even if logged in as admin.

![](https://i.imgur.com/tGspDgf.png)

### Files Version

v1.9.20

### Windows Version

Windows 11 Insider Preview Build 22000.120

**Comment by wupaz** [comment]
Or powershell

**Comment by Josh-65** [comment]
This has been added to the right click menu. in v2 and up

**Comment by Josh-65** [comment]
#5648 Might cause issues with adding this

**Comment by yaira2** [comment]
We added a new shortcut ctrl + shift + ` for this.
