### ISSUE TITLE
Reposition of sidebars

### ISSUE THREAD

**Issue by m1karii** [files-community/Files#5728]
### Solution/Idea

(following images are not mine i just took them from discord and edited them)
My OCD is just killing me looking at this... like why is it like this...
![before](https://user-images.githubusercontent.com/82673417/128635860-02fa1f5f-594f-496a-9227-96af18a922ad.png)
and not like this... ?
![after](https://user-images.githubusercontent.com/82673417/128635874-d1040220-64c1-4e28-a951-e389576bace3.png)

(not all of the following points are illustrated above)
- right sidebar / preview pane and left sidebar both inbetween top bar and bottom bar
- right sidebar / preview pane and left sidebar have same default width (adjustable by user and resettable to default)
- bottom bar either 100% height of top bar / 50% height of top bar / or completely removed
- different background for preview pane removed

### Files Version

v1.9.20

### Windows Version

Windows 11 Insider Preview Build 22000.120

**Comment by yaichenbaum** [comment]
@m1karii thanks for opening this issue, the simple answer to your question is that when it comes to design there is always more than one way to do things, but at the end of the day you need to settle on one of them and make sure you do the best you can. We believe the design we came up with for v2 is intuitive and lays out controls in the best possible way. We're open to feedback, but to make any change, we need to know the issue you're having with the current layout, and we need to evaluate to see if this issue applies to the majority of users as well.

**Comment by m1karii** [comment]
> We're open to feedback, but to make any change, we need to know the issue you're having with the current layout, and we need to evaluate to see if this issue applies to the majority of users as well.

I'll go through the points in (a bit) more depth. Try to look at it with eyes of somebody who has preview pane almost always on.


> * right sidebar / preview pane and left sidebar both inbetween top bar and bottom bar

again: with eyes of somebody who has preview pane almost always on (and OCD almost always on) - right sidebar / preview pane and left sidebar look very imbalanced. one option on balancing this would be stretching both sidebars and putting top and bottom bar in between of them. However i think in windowed mode this wouldn't create enough space for top bar icons/ items; thats why i proposed the second option: both sidebars being in between of top and bottom bar.

> * right sidebar / preview pane and left sidebar have same default width (adjustable by user and resettable to default)

this is to make it look balanced too.
adjustable by user - for obvious reasons; it already is adjustable by user.
resettable to default - in case somebody accidentally changes width of either panel there should be option in settings (or somewhere else) to reset it to default so they don't have to reinstall the app - which i would totally do.
I was also thinking about anchoring the widths of sidebars together and users being able to change both widths at the same time so the sizes (width) stay the same for both sidebars while being adjusted by users; but i decided not to propose this one (however i wouldn't be mad if it was implemented). 

> * different background for preview pane removed

I think that preview pane having its own (different) background looks out of place

> * bottom bar either 100% height of top bar / 50% height of top bar / or completely removed

I believe the bottom bar is close to being 50% height of top bar if not being 50% height of top bar already. I don't know what else to say to this one. It's close to it already so there shouldn't be an issue changing it to the proposed size for aesthetical purposes.

**Comment by yaichenbaum** [comment]
@m1karii stretching the toolbar across the whole width of the app would take up valuable space from the sidebar, on the other hand, stretching the preview pane vertically would cause toolbar options to collapse into menus.
Adding @mdtauk and @itsmichaelwest for additional feedback
