### ISSUE TITLE
[UX] Autofocus TextBoxes in action dialogs where they are the primary content.

### ISSUE THREAD

**Issue by Tropix126** [files-community/Files#5729]
### What's the Problem?

One slight annoyance i've had as of recent is that the new folder/file dialogs don't provide a way to fill in a text field immediately. Rather, they require mouse input or additional tabbing to focus the textbox which is required to complete the action. I wish there was a way to just immediately start typing, then complete the action with no additional input.

### Solution/Idea

Autofocus the TextBox in dialogs where they are the primary focus of the action (eg. providing a name for a file or folder). Additionally, (this might be better suited for the WinUI repo) it might also improve UX to perform the primary action of the dialog when the user hits enter on a single-line textbox to avoid another additional tab input or mouse click (similar to how discord handles their modal components).

### Alternatives

I suppose that a possible alternative would be getting rid of some modals entirely in place for a similar UI to what file explorer uses now, but I don't endorse that personally.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow users to immediately enter a file name in the "New <x>" dialogs. | Must |

### Files Version

1.9.20.0

### Windows Version

Windows 11 22000.120

### Additional comment

https://user-images.githubusercontent.com/42101043/128645578-3c6d9e9c-6839-4560-8105-145f69625e28.mp4

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5782.
