### ISSUE TITLE
Disc Number is not displayed in properties of Music file

### ISSUE THREAD

**Issue by YourOrdinaryCat** [files-community/Files#5730]
### Description

The Disc Number property is not being displayed in Music file properties.

### Steps To Reproduce

1. Right click on a Music file 
2. Click on "Properties" in the context menu
3. Check file details, Disc Number does not show up

### Expected behavior

I expect to see the disc number in the file properties.

### Files Version

v1.9.20.0

### Windows Version

Windows 11 21H2 22000.120

### Relevant Assets

![image](https://user-images.githubusercontent.com/49221554/128646731-69f66fec-3260-4853-977c-cf64423a552a.png)

This is what shows up in the file properties

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5734.
