### ISSUE TITLE
Files fails to launch after recent update

### ISSUE THREAD

**Issue by GittenKittens** [files-community/Files#5736]
### Description

Files fails to launch after the update pushed out today, 8/9/2021.  After updating all attempts to launch it briefly open the Files window with the icon but then that closes.

### Steps To Reproduce

1. Update Files app via Microsoft Store to version 1.9.21.0
2. Attempt to open Files via either a desktop shortcut or Windows start menu.

### Expected behavior

Files will open when selecting it via either desktop shortcut or via the Windows start menu.

### Files Version

1.9.21.0

### Windows Version

Windows 10 20H2 19042.1151

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/6954691/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6954692/debug_fulltrust.log)

**Comment by gave92** [comment]
Uops this is my fault -> part of #5719

**Comment by gave92** [comment]
As a workaround you can try uninstalling/removing custom themes.

**Comment by GittenKittens** [comment]
> 
> 
> As a workaround you can try uninstalling/removing custom themes.

Is there a directory that custom Themes would be in besides [Files package location]/LocalState/Themes?  That file is empty and I don't think I've added any custom themes.

**Comment by gave92** [comment]
Perhaps you've installed the themes optional package? If so you can uninstall the "Themes For Files" app from the Store. If you haven't it means that the bug can happen regardless..

**Comment by GittenKittens** [comment]
I haven't installed the "Themes For Files" app from the Store so I think the bug is happening no matter what.

Thanks for looking at this and all the work!

**Comment by KillTrot** [comment]
This happens on two of my machines too.

If you need logs or similar, let me know

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5738.
