### ISSUE TITLE
Quick actions ribbon disappears in context menu when folder list is longer than window on the bottom

### ISSUE THREAD

**Issue by andreaslutsch** [files-community/Files#5737]
### Description

When you have a folder open with many files/folders and you right click a file/folder on the bottom of the window to open the context menu, the ribbon with quick actions buttons disappears.

https://user-images.githubusercontent.com/7101531/128717286-5d20d196-defa-4647-a57e-59983706be49.mp4

### Steps To Reproduce

1. Open folder with many files/folders
2. Right click on a file/folder on the bottom of the window so that the context menu would not fit in the bottom of the screen.
3. Ribbon disappears after the context menu expands.

### Expected behavior

The ribbon with quick action buttons should stay.

### Files Version

v1.9.21.0

### Windows Version

Windows 10 Pro 21H1 19043.1151

**Comment by gave92** [comment]
Probably to be redirected to [WinUI repo](https://github.com/microsoft/microsoft-ui-xaml/issues).

**Comment by gave92** [comment]
Should be fixed in 1.9.22 (#5776)
