### ISSUE TITLE
When extract file dialog shows up, the context menu should disappear.

### ISSUE THREAD

**Issue by xwnb** [files-community/Files#5739]
### Description

Both of them can not be moved. It is hard to do extract workflows.

![image](https://user-images.githubusercontent.com/45145954/128725864-4f53b876-7e5f-450b-bd84-0806383f3668.png)

### Expected behavior

When extract file dialog shows up, the context menu should disappear.

### Files Version

v1.9.19

### Windows Version

Windows 10 21H1 19043.1110

**Comment by gave92** [comment]
Merging with #5578
