### ISSUE TITLE
Google drive for desktop documents don't show in the new menu

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#5743]
### Description

![image](https://user-images.githubusercontent.com/26977075/128756409-b6dc917a-9cde-4d23-8771-06b8285c75e1.png)
![image](https://user-images.githubusercontent.com/26977075/128756421-a784ebeb-f861-4613-8126-cdafc65792af.png)

### Expected behavior

They should show up like file explorer

### Files Version

1.9.21

### Windows Version

10.0.19043.1151

**Comment by yaichenbaum** [comment]
This issue should be resolved with #8784.
