### ISSUE TITLE
Extremely slow right click

### ISSUE THREAD

**Issue by surelynottrue** [files-community/Files#5744]
### Description

The right click menu takes way longer than what it takes on the normal file explorer to show up. I am not sure how to show this, but it is way, way slower. I am running a windows 11 public beta on my ROG zephyrus, for context.

### Steps To Reproduce

Just right click anywhere

### Expected behavior

I am comparing the normal file explorer right click to this. This takes more than a second to pup up

### Files Version

1.5

### Windows Version

10.0.22000 Build 22000

**Comment by gave92** [comment]
Thanks for this report. This has been improved in the beta version.
