### ISSUE TITLE
Right Click on specific Folders freezes Files 

### ISSUE THREAD

**Issue by AssasinMaster** [files-community/Files#5745]
### Description

Whenever i rightclick Folders with mutliple mp3s or Pictures in my G: drive, Files Freezes, but it wont freeze on the D: and C:  drive. It also wont freeze when i first go into the Folder and preload the Files in it.

### Expected behavior

The rightclick menu should open like usual.

### Files Version

1.5

### Windows Version

Windows 10 20H2

**Comment by gave92** [comment]
Thanks for this report. This issue should be fixed in the beta version.
