### ISSUE TITLE
Sort Needed

### ISSUE THREAD

**Issue by imransadik** [files-community/Files#5747]
### What's the Problem?

There are no sort feature which is needed.

### Solution/Idea

Add Sort Feature.

### Alternatives

No alternative only sort is needed.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

v1.5.0.0

### Windows Version

Win 10

**Comment by gave92** [comment]
Implemented in the beta version.
