### ISSUE TITLE
Files crashes on start

### ISSUE THREAD

**Issue by gkkirilov** [files-community/Files#5748]
### Description

Files crashes at the start. I open it and see the window with the icon but after 1 sec it crashes and closes

### Steps To Reproduce

Open Files
Crash

### Expected behavior

Open files
Manage to use the app

### Files Version

1.9.20 - latest beta

### Windows Version

Windows 11 -V 10.0.22000 Build 22000

**Comment by gave92** [comment]
Thanks for this report. Please add the debug files to the issue description. Also you can try and see if resetting the app solves this.

**Comment by gkkirilov** [comment]
@gave92 Where to find the debug file? Also does resetting the application mean reinstalling it?

**Comment by gave92** [comment]
- You can find the debug files (`debug.log` and `debug_fulltrust.log`) in `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`
- Reinstalling also works but you can also try to right click on Files on the start menu > More > App settings -> Reset

**Comment by gkkirilov** [comment]
Yep reset worked, thanks @gave92!

Here are the files, anyway hope they help
[debug.log](https://github.com/files-community/Files/files/6962028/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6962029/debug_fulltrust.log)
