### ISSUE TITLE
Interface: Selected folder not coloured in accent color

### ISSUE THREAD

**Issue by mangoepic** [files-community/Files#5749]
### Description

![image](https://user-images.githubusercontent.com/71931749/128900891-6c7eb570-3515-43d7-b9dd-763512d855bb.png)

This Item could be selected or hovered over... it is selected!
When hovering over it it changes to the accent colour:

![image](https://user-images.githubusercontent.com/71931749/128901022-211e4b77-5db0-4d5f-bc8b-e55a82491cb1.png)

maybe the text should also change to white for darker accent colours while I'm at it, or use a different version of the colour for selection? just something to make it more readable

### Steps To Reproduce

Go to any folder
Click on any file, but don't move your mouse
Move your mouse one pixel

### Expected behavior

Accent colour for selected folders

### Files Version

Version: 1.9.21.0 OS Version: 10.0.19043.1110

### Windows Version

Windows 10 Home 21H1

**Comment by gave92** [comment]
The listview selection syles only work correctly on Windows 11. Hopefully WinUI will fix it.
