### ISSUE TITLE
UI changes for improving the renaming dialogue

### ISSUE THREAD

**Issue by mangoepic** [files-community/Files#5750]
### What's the Problem?

![image](https://user-images.githubusercontent.com/71931749/128902363-050c1a2d-f03c-498c-b853-bc7136b19ca3.png)

Currently the renaming dialogue looks almost exactly like the navigation dialogues at the top.
I think it should be made a little more minimal to not conflict too much with the other input fields weight wise.
The line is usually used to indicate focus - but this text field cannot be seen unfocused and the user knows exactly what is focused anyways since he very actively wants to rename something. (It's a bit too much)

What also makes renaming more distracting:
 - The text shifts from the original position, making the user read it again
 - It conflicts with the outline on the large icon version
![image](https://user-images.githubusercontent.com/71931749/128903204-00190bed-7dac-4700-961d-5ac2caf7a994.png)
 - I'm not sure yet but maybe the input field size should be dependent on the text length instead of the width of the name column
 - I'm also not sure about the "x" for now, i expected it to end the renaming operation, not sure if it's useful or not (since the text is already marked for the user and can be deleted with one keyboard press)

### Solution/Idea

So a solution could be to:
 - Keep the text in place and either move the input box or leave out some whitespace on the left
 - Make the textbox size on the right dependent on the text length
 - Make the text box slightly smaller than the outline (align with the inner) and make the bottom of the outline longer with multiple line names
![image](https://user-images.githubusercontent.com/71931749/128904378-a0b5771c-7629-469e-96c3-b55a44af5d38.png)
 - Get rid of the "x"
 - Scroll to the beginning of the input field  text when renaming

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Scroll to the beginning of the input field text when renaming (list view) | Should |
| Keep the text in place and either move the input box or leave out some whitespace on the left (list view) | Should |
| Get rid of the underline or make it less prominent (list view) | Could |
| Make the textbox size on the right dependent on the text length similiar to win explorer (list view) | Could |
| Get rid of the "x" or change it's functionality to quitting the input dialogue (list view) | Could |
| Make the text box slightly smaller than the outline (align with the inner) and make the bottom of the outline longer with multiple line names (larger views)  | Should |

### Files Version

Version: 1.9.21.0 OS Version: 10.0.19043.1110

### Windows Version

W10 Home 21H1

### Additional comment

If you have any other ideas or think this should be tackled differently of course feel free to comment, these are just some ideas.
I love the how the new interface is coming together! so I want to nitpick some stuff that could (hopefully) make it more polished.

**Comment by josh-65** [comment]
All text inputs are like that as it's the WinUI standard.

**Comment by yaichenbaum** [comment]
Fyi @mdtauk

**Comment by Takanu** [comment]
I have no strong feelings on the smaller issues raised here but the "text shift" issue I think is a really important one:

* When you edit an item with a long name **the text box changes to show you the end rather than the beginning of the text** like the standard UI element would, which creates confusion.
* **The "cursor movement" required to move through text that DOESN'T fit inside the editing box happens _vertically_ rather than _horizontally_**, and because the editing box is a perfect fit for the text size it initially looked to me like a bug.

**Comment by yaichenbaum** [comment]
We don't plan to make this change.
