### ISSUE TITLE
Clicking on a folder should have a less strong animation in list view

### ISSUE THREAD

**Issue by mangoepic** [files-community/Files#5751]
### What's the Problem?

Clicking on a folder in list view should have a less strong animation

### Solution/Idea

![image](https://user-images.githubusercontent.com/71931749/128905544-bfc36c95-b9ae-40a7-af0a-a81747b869cb.png)
![animations](https://user-images.githubusercontent.com/71931749/128905793-74325040-863e-489d-b2dd-210ad554310b.gif)

**The Problems**

- The main problem i have right now is the blur. It makes everything blurry. Blurry text looks not good.
-  The feel of it, it skews everything in a little bit fiddly unpredictable way
- The intensity. It is just selecting a folder. As an opening animation it would probably work. But not when just selecting something.

**Solution/Ideas**

- Make it not blur regardless of animation or not
- Make it feel more productive, easier to understand
- In my opinion it doesn't really need an animation at all from a ux standpoint, the selection colour is completely enough, everything else will be a little bit over the top for just a selection in my opinion. There could maybe be a cooler smooth animation when opening a folder or something but just with the selection it doesn't sit right for me

### Alternatives

-

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Make it not blur regardless of animation or not | Must |
| Make selecting feel more productive, easier to understand | Should |
| Get rid of the zooming animation when single-clicking | Could |

### Files Version

Version: 1.9.21.0 OS Version: 10.0.19043.1110

### Windows Version

Win10 Home 21H1

### Additional comment

Could also have a slightly longer delay until the renaming function get's called its pretty easy to accidentally go into renaming mode (this also annoys me about the original windows explorer, i think it has a slightly longer delay even)

**Comment by starkgate** [comment]
I also feel like the current animation is a bit confusing. Double clicking produces this zoom / blur effect twice.

Same for the renaming delay, it's too short, making it difficult to actually open the file / folder.

**Comment by drkdw** [comment]
Agreed. Current click/double click animation is weird and confusing. For me, its feels like I'm about to drag the file.

The text shouldn't move to the right and doesn't need to be 'italic' on click. Logically it should have a color on click and doesn't need extra effect on opening.

**Comment by gave92** [comment]
Marging with #6259
