### ISSUE TITLE
When starting Files the divider of the sidebar gets selected

### ISSUE THREAD

**Issue by mangoepic** [files-community/Files#5752]
### Description

You can see this big black outlined bar right there:
![image](https://user-images.githubusercontent.com/71931749/128907975-7e6c061e-62ab-4241-81cd-ba497998ea7e.png)

This divider can be tab selected and moved left and right with the arrow keys. While i think this is good as accessibility functionality, it shouldn't be selected on startup

### Steps To Reproduce

Start files

### Expected behavior

It shouldn't be tab selected

### Files Version

Version: 1.9.21.0 OS Version: 10.0.19043.1110

### Windows Version

Win10 21H1

### Relevant Assets

-

**Comment by yaichenbaum** [comment]
Merging with #5685.
