### ISSUE TITLE
On startup current folder not selected

### ISSUE THREAD

**Issue by mangoepic** [files-community/Files#5753]
### Description

On Startup the current folder not selected in the sidebar

"Continue where you left off" Setting:

![image](https://user-images.githubusercontent.com/71931749/128908731-aa5b801d-d405-47ce-a778-7ebe05f2670a.png)

"Open a new tab" Setting

![image](https://user-images.githubusercontent.com/71931749/128908890-58f79ad4-eaad-46b6-a018-0dbaab9be8df.png)

instead of

![image](https://user-images.githubusercontent.com/71931749/128908935-df7fedbc-2a73-47ae-81b2-99609a7565b9.png)

### Expected behavior

Select the current folder in the sidebar

### Files Version

Version: 1.9.21.0 OS Version: 10.0.19043.1110

### Windows Version

Win10 21H1

**Comment by Josh-65** [comment]
This has been fixed in 2.3.11.0
