### ISSUE TITLE
Admin actions in C: drive doesnt work

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5754]
### Description

When trying to do an admin required action it just does nothing. (no in app pop out or the Windows UAC prompt) I haven't tried in other drives/partitions since I don't have any.

### Expected behavior

It should ask for admin

### Files Version

1.9.21

### Windows Version

10.0.19043.1151

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/6963606/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6963607/debug_fulltrust.log)

**Comment by gave92** [comment]
> When trying to do an admin required action it just does nothing.

Delete? Copy? Everything?

**Comment by josh-65** [comment]
i have tried creating, deleting and moving

**Comment by gave92** [comment]
Thanks, do you remember it working on Files <=1.9.20?

**Comment by josh-65** [comment]
last time I test was with 1.9.0,0 I think.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5757.
