### ISSUE TITLE
Scrollbar showing despite no Overflow

### ISSUE THREAD

**Issue by mangoepic** [files-community/Files#5758]
### Description

There is this inactive scroll bar showing in the Tabs-list even when there is no overflow:

![image](https://user-images.githubusercontent.com/71931749/128937180-fb4d3ffb-2896-4e13-a131-9eb707fa11b6.png)

Same in Settings:

![image](https://user-images.githubusercontent.com/71931749/128937619-8a33138f-f62a-4d45-8475-86795926c608.png)

And in Home tab:

![image](https://user-images.githubusercontent.com/71931749/129161497-8645f33b-5bd1-401e-b6e9-0b8778dfab44.png)

### Steps To Reproduce

- Create a few tabs in the new tabs list
- Open the Settings dialogue (it comes in after a fracture of a second)

### Expected behavior

Remove the scrollbar when there is no overflow (like in the files-section when there are just a few files)
![image](https://user-images.githubusercontent.com/71931749/129161382-2704c57a-9676-488f-966c-d38c07a9f39e.png)

### Files Version

Version: 1.9.21.0 OS Version: 10.0.19043.1110

### Windows Version

Win10 21H1

**Comment by yaichenbaum** [comment]
This can be adjusted from the Windows settings app.
![image](https://user-images.githubusercontent.com/39923744/168609534-056f637f-94b2-4c61-8ef9-eae0c458499c.png)
