### ISSUE TITLE
Layout popup closes only when selecting Details view

### ISSUE THREAD

**Issue by austin-dudzik** [files-community/Files#5759]
### Description

When selecting a layout view from the layout popup, the popup window only closes when selecting the "Details" view, but stays visible when selecting any another layout view.  About 90% of the time the popup will show this behavior, although it will occasionally behave normally. It can not be determined what triggers the usual behavior.  (See screen recording)

### Steps To Reproduce

Open the layout popup and select the "Details" view option.

### Expected behavior

The layout popup should stay visible after selecting "Details" view.

### Files Version

Version: 1.9.21.0

### Windows Version

Windows 11 21H2 22000.120

### Relevant Assets

https://user-images.githubusercontent.com/65981261/128938595-3d0e0b7f-d2af-48b9-a592-6453d4ae1c5c.mp4

**Comment by josh-65** [comment]
It also happens when double clicking any of the values. Might be set to close when the adaptive layout mode takes over.

**Comment by generalguy41** [comment]
Not sure if it's exactly the same (since this was _5 months_ ago...), but I had a similar issue in #4240. Possible regression maybe? Though it wasn't explicitly addressed.

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.11.0 or above?

**Comment by generalguy41** [comment]
Looks like the issue still applies for the Columns layout

https://user-images.githubusercontent.com/8879244/197060345-1dc97412-0196-450b-aa41-30f322e3d10d.mp4
