### ISSUE TITLE
Google Drive shows in 'Drives' section instead of 'Cloud Drives'

### ISSUE THREAD

**Issue by justb7** [files-community/Files#5760]
### Description

I recently updated from Google's 'Backup & Sync' software to their new Google Drive cloud streaming app. The link to Gdrive now shows under the 'Drives' section instead of the 'Cloud Drives' Section in Files. 
![image](https://user-images.githubusercontent.com/88261672/128940261-3c14e986-13ca-4794-ba10-1aac504ef450.png)

### Expected behavior

Google Drive should show under Cloud Drives

### Files Version

v.1.9.21.0

### Windows Version

Windows 11 21H2 22000.1120

**Comment by josh-65** [comment]
Google drive for desktop mounts the folder as a drive in windows, so this isn't an issue on files end. However I have made an issue that it doesn't show up in the cloud section. #5690
