### ISSUE TITLE
files crash/closes when open program location via task manager

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5761]
### Description

When right clicking a program/process in task manager it will open then close files instantly.

### Expected behavior

It should open the file location

### Files Version

1.9.21.0

### Windows Version

10.0.19043.1151

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/6964780/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6964781/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
Merging with #3117.
