### ISSUE TITLE
Add toolbar button to empty recycle bin

### ISSUE THREAD

**Issue by WelkinBunbury** [files-community/Files#5762]
### What's the Problem?

Add Empty recycle button

### Solution/Idea

![image](https://user-images.githubusercontent.com/33565456/128942934-d0f04c69-6f19-401e-aee7-c7235dca1eb1.png)

add button on top

### Alternatives

add the button thats it.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 1.9.21.0 

### Windows Version

OS Version: 10.0.19042.1110

**Comment by esibruti** [comment]
@yair100 I think this feature is already implemented in Files

![image](https://user-images.githubusercontent.com/78214358/150798103-df8cb2c0-f9b9-422b-926e-3eeddb761b51.png)
