### ISSUE TITLE
Adresses of folders to be opened at startup are cut off

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#5766]
### Description

![image](https://user-images.githubusercontent.com/17484252/128990584-50a8734c-c4fd-4666-9aaa-49a8b8a15309.png)

The adresses are cut off due to the limited width of the UI and the lack of a tooltip showing the full path

Addtionally, there is no way to remove an adress from that list

### Expected behavior

- A button to remove an entry
- Increased UI width and/or a tooltip that shows the full path

### Files Version

Version: 1.9.21.0 

### Windows Version

OS Version: 10.0.19043.1151

**Comment by josh-65** [comment]
When I hover over the location it does show the full path in 1.9.21. Also there is a remove button in the '...' menu but that gets moved off screen when the path is long enough,

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5769.
