### ISSUE TITLE
Right-click menu is cut off

### ISSUE THREAD

**Issue by starkgate** [files-community/Files#5767]
### Description

The right-click / shift-right-click menu is cut off the first time it is displayed in a new tab (see picture below). Any further calls to the menu display correctly.
![ApplicationFrameHost_8E9d93Kn2P](https://user-images.githubusercontent.com/12874678/128993802-7d2f1620-3b46-448c-bcb2-8d8a99beb0ed.png)

### Steps To Reproduce

1. Open a new tab
2. Right click in a folder

### Expected behavior

Correct display of the menu

### Files Version

Version: 1.9.21.0

### Windows Version

OS Version: 10.0.19043.1110

**Comment by TailyFair** [comment]
Happens as well.

Version: 1.9.11.0
OS Version: 10.0.19043.1165

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5776.
