### ISSUE TITLE
Feature: Add way to differentiate between picture and video in the grid view layout

### ISSUE THREAD

**Issue by m1karii** [files-community/Files#5768]
### Solution/Idea

Something that would enable to immediatelly visually differentiate picture and video without using preview panel / opening properties / changing view mode from grid view to one that displays extensions....
Explorer has these squares on both sides of the preview image of video as seen below. 

![vid_vs_pic](https://user-images.githubusercontent.com/82673417/129007530-9e5612a5-a534-427d-875f-5550ee438c4f.png)

im looking for something serving the same purpose. you can implement it as squares on both sides of preview image too... or you can implement it as library icons in corner of given item preview image... Or you can implement it in any other way serving the primary purpose i stated....

![preview](https://user-images.githubusercontent.com/82673417/129007714-68496ae3-e425-476a-bce0-d9fc036fd43e.png)

But in this case you'd probably also have to do the same for document / spreadsheet / presentation with document library icon. and music library icon for audio files... however audio files arent always music.

### Files Version

v1.9.20

### Windows Version

Windows 11 Insider Preview Build 22000.120

**Comment by VOOM108** [comment]
These are related: https://github.com/files-community/Files/issues/7243 resp. 7243 could solve this, too....

**Comment by yaira2** [comment]
Merging with #7243
