### ISSUE TITLE
Crash when deleting content in recycle bin

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5771]
### Description

I deleted all files by selecting and right clicking then it crashed.

### Expected behavior

Shouldn't crash

### Files Version

1.9.21

### Windows Version

10.0.19043.1151

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/6969502/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6969503/debug_fulltrust.log)

**Comment by gave92** [comment]
Where the files successfully deleted?

**Comment by josh-65** [comment]
I didn't look after the crash but I think they did.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5795.
