### ISSUE TITLE
Widgets are missing automation properties

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#5772]
### Description

Widgets on the home page are missing autoatmion properties in the list view.
![image](https://user-images.githubusercontent.com/39923744/129057226-e6445d31-f0bb-4781-8761-9321e380852e.png)

### Expected behavior

The expected behavior would be for the widgets to have automation properteis.

### Files Version

v1.9.21

### Windows Version

22000.120

**Comment by yaichenbaum** [comment]
Fyi @d2dyno1

**Comment by d2dyno1** [comment]
On it!
