### ISSUE TITLE
Bug: WCAG 4.1.2: (Files/group 'Files.Helpers.GroupedCollection`1[Files.Filesystem.ListedItem]') Focusable sibling elements must not have the same Name and LocalizedControlType.

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#5773]
The following accessibility issue needs investigation.

**App:** Files

**Element path:** group 'Files.Helpers.GroupedCollection`1[Files.Filesystem.ListedItem]'

**Issue Details:** Focusable sibling elements must not have the same Name and LocalizedControlType. [WCAG 4.1.2](https://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-rsv.html)

**How To Fix:** Provide unique names for sibling controls that have the same ControlType property.

This accessibility issue was found using Accessibility Insights for Windows, a tool that helps debug and find accessibility issues earlier. Get more information and download this tool at https://aka.ms/AccessibilityInsights.

**Comment by yaichenbaum** [comment]
Fyi @winston-de

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.11.0 or above?

**Comment by yaichenbaum** [comment]
Yes
