### ISSUE TITLE
Sort drives alphabetically

### ISSUE THREAD

**Issue by eislexus99** [files-community/Files#5777]
### Description

How can I sort the view of the drives alphabetically in Files 1.5.0.0?
From A to Z.
Thanks and greetings

### Expected behavior

How can I sort the view of the drives alphabetically in Files 1.5.0.0?
From A to Z.
Thanks and greetings

### Files Version

Version 1.5

### Windows Version

Windows 10 Pro Workstation 21H1 Build 19043.1110

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
Personally I think it's fine the way it is but I'll leave this up to @gave92.

**Comment by Josh-65** [comment]
Since there hasnt been a reason to implement this and gave92 hasnt reponded im going to close this.
