### ISSUE TITLE
Crash when making new folder in my custom downloads library

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5778]
### Description

When I create a folder or file in my custom downloads library (it goes to my user downloads folder only) it will crash with the "Something when wrong" notification. It also didn't create the folder.

### Expected behavior

Shouldn't crash's.

### Files Version

1.9.21.0

### Windows Version

10.0.19043.1151

### Relevant Assets

[debug_fulltrust.log](https://github.com/files-community/Files/files/6971389/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/6971391/debug.log)

**Comment by gave92** [comment]
Did you get to choose the name of the folder before the crash?

**Comment by josh-65** [comment]
yes

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5793.
