### ISSUE TITLE
Browse elements with Files UWP

### ISSUE THREAD

**Issue by Greenorine** [files-community/Files#5779]
### What's the Problem?

When you open file browse in browser or etc. it opens base file explorer.

### Solution/Idea

I'm not sure if it's not made yet but all file browses opens in base file explorer. If it's possible it will be good to make some browse activity with Files UWP.

### Alternatives

-

### Files Version

v1.5

### Windows Version

Windows 11 Beta

**Comment by gave92** [comment]
Unfortunately we haven't found a way to do this.
