### ISSUE TITLE
Use AnimatedIcon on the settings button.

### ISSUE THREAD

**Issue by Tropix126** [files-community/Files#5783]
### What's the Problem?

With the introduction of WinUI 2.6, many icons seen in NavigationView are now animatied through interaction states, including the settings button. I think it would be a nice addition to feature this in v2's new UI with the settings icon being in the header.

### Solution/Idea

Use AnimatedIcon on the new settings button.

### Alternatives

None

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will animated the settings icon in the files header. | Must |

### Files Version

1.9.21.0

### Windows Version

22000.120

### Additional comment

none

**Comment by yaichenbaum** [comment]
This issue should be resolved with #8402
