### ISSUE TITLE
Unresponsive Settings Menu on Restore Down

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#5784]
### Description

The settings menu are unresponsive when click on the restore down button (beside minimize) and click on the settings button.

### Steps To Reproduce

1. Open Files (Make sure it is full screen)
2. Click on the Restore Down located in the edge
3. Click on Settings
4. See the error

### Expected behavior

Settings UI should look fine

### Files Version

1.9.21.0

### Windows Version

Windows 10 21H1 19043.1165

### Relevant Assets

https://user-images.githubusercontent.com/69080584/129135128-adc79283-896f-4411-a587-b576816f720f.mp4

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5775.
