### ISSUE TITLE
Google Drive for desktop as Cloud drive

### ISSUE THREAD

**Issue by WelkinBunbury** [files-community/Files#5785]
### Solution/Idea

i want google drive to appear here
![image](https://user-images.githubusercontent.com/33565456/129140449-b286d983-876a-4eb9-ad0a-3597c69b7f4c.png)

Currently google drive for desktop acts as a drive.
![Uploading image.png…]()

### Alternatives

no alternatives

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 1.9.21.0 

### Windows Version

OS Version: 10.0.19042.1110

**Comment by gave92** [comment]
#5690
