### ISSUE TITLE
No delay for the renaming dialogue

### ISSUE THREAD

**Issue by mangoepic** [files-community/Files#5786]
### What?

In both Files and the Win Explorer the renaming dialogue gets triggered after clicking on a File or Folder when it is selected.

The Win File Explorer has a delay before the renaming dialogue gets triggered. This means a user can open a preselected folder without accidentally being greeted with a renaming dialogue.

https://user-images.githubusercontent.com/71931749/129173358-c1630fcf-0a6a-4e01-82a0-2c9d8d071197.mp4

In this video I am double clicking on the folder without having it pre-selected. It opens as expected.

https://user-images.githubusercontent.com/71931749/129172335-bf52fc8f-5af6-4593-ad4a-8d1e9365ad30.mp4

I am double-clicking, but note that this time I pre-selected both folders. Files jumps into the renaming dialogue. Win Explorer opens files.

### Conclusion

As you can see in Files you get into the renaming dialogue while in Windows Explorer you can open the folder/file.

### Expected behavior

A slight delay before triggering the renaming dialogue so the user has a chance to open the file/folder

### Files Version

Version: 1.9.21.0 OS Version: 10.0.19043.1110

### Windows Version

Windows 10 21H1

**Comment by gave92** [comment]
Should be fixed in 1.9.22
