### ISSUE TITLE
Feature: "Eat" click when refocusing on window

### ISSUE THREAD

**Issue by mangoepic** [files-community/Files#5787]
### Description

 https://user-images.githubusercontent.com/71931749/129176275-03f8d4eb-f5e1-43b6-b120-4951fd1ae955.mp4

As you can see in the video Windows Explorer blurs selected files when deselecting the window (you can notice it changing to a gray-background state).

This means that when reselecting the window by clicking on the selected file, the renaming dialogue doesn't get triggered like described in #5786

Files does not have this functionality yet.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This functionality will blur the selection when selecting another window. Clicking on a blurred selection does not trigger the renaming dialogue | Should |

### Additional Comment
This is a small functionality but little things like this are very helpful in making ux less frustrating for users

### Files Version

Version: 1.9.21.0 OS Version: 10.0.19043.1110

### Windows Version

Windows 10 Home 21H1

**Comment by yaira2** [comment]
Thank you for your feedback. We don't have plans to implement this change, but you can avoid triggering a rename by clicking on the thumbnail.
