### ISSUE TITLE
Wrong selection for deleting permanently with "del" key

### ISSUE THREAD

**Issue by mangoepic** [files-community/Files#5788]
### Description

![image](https://user-images.githubusercontent.com/71931749/129183922-917a114f-9d29-490f-877a-53b64c05db2a.png)

Bug 1:
"Delete permanently" gets selected instead of "Delete" on the bottom.

Bug 2:
Pressing enter does not select "Delete permanently" but triggers the "Delete" button

### Expected behavior

/

### Files Version

Version: 1.9.21.0 OS Version: 10.0.19043.1110

### Windows Version

Win10Home21H1

### Relevant Assets

/

**Comment by mangoepic** [comment]
> Well, this is the fastest you can get using the keyboard: "Space" toggles permanent delete while "Enter" confirms it ;)
> 
> But I guess it's true keyboard focus should be on the Delete button.

I agree that it is really fast :P but probably not what the general user expects and because deleting files is a sensitive functionality as is, having it unexpectedly delete a file instead of selecting a box might scare users

**Comment by yaichenbaum** [comment]
@mangoepic can this be merged with #5584?

**Comment by tellmewhy12** [comment]
@yair100 However it's easier for you guys to handle ^^

This issue here was also about not accidentally hitting "confirm delete" via enter while the checkbox is focused but depending on what you want to do it's definitely overlapping

**Comment by gave92** [comment]
Im not sure what changed but hitting enter does not seem to confirm delete, so perhaps the relevant issue is only #5584.

**Comment by d2dyno1** [comment]
@mangoepic Fixed with #7882
