### ISSUE TITLE
Filename conflict: Option for renaming in dialogue

### ISSUE THREAD

**Issue by mangoepic** [files-community/Files#5790]
### What's the Problem?

![image](https://user-images.githubusercontent.com/71931749/129184557-a3947c76-f30b-48e7-b166-8cac7d81b06e.png)

Duplicating a file/folder prompts the user with a dialogue they **have** to act upon.

Often users want to duplicate a file/folder to create a different version of it. This often goes with renaming the duplicated file/folder afterwards.

### Solution/Idea

Instead of letting the user act twice, first for the renaming dialogue and after by going into renaming mode, another option could be added. The user could give a name to the duplicate directly in the dialogue, making duplicating a way smoother experience.

### Alternatives

/

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This will allow users to rename files/folders directly in the dialogue | Should |
| This proposal will check again for a naming conflict after the user renamed | Must |

### Files Version

Version: 1.9.21.0 OS Version: 10.0.19043.1110

### Windows Version

Windows 10 21H1

**Comment by yaichenbaum** [comment]
Merging with #5645
