### ISSUE TITLE
filename fluctuations

### ISSUE THREAD

**Issue by mangoepic** [files-community/Files#5791]
### Description

test -> test (2) -> test (3) -> test (2)

![filename fluctuations](https://user-images.githubusercontent.com/71931749/129188298-5dfd8c5e-72f9-4d4f-addb-02d06bafc447.gif)

### Expected behavior

test -> test (2) -> test (2)

### Files Version

1.9.21.0

### Windows Version

21H1

**Comment by gave92** [comment]
Closing as Windows Explorer has the very same naming behavior (with files) and Files uses explorer's copy functions.
