### ISSUE TITLE
Pin files in folders

### ISSUE THREAD

**Issue by mangoepic** [files-community/Files#5792]
### What's the Problem?

Sometimes you have folders with lots of files / inside folders but are just working on 1 or 2 files, and you can't/don't want to always change that. This would give you more options of quick intuitive organizing, like putting things "in reach"

Humans can just take in 3-4 items at once anyways, this reduces looking for the right stuff

### Solution/Idea

I thought it could be really cool to be able to pin files/folders to the top of a folder. Files you are currently working on, folders you are often using, etc.

Lots of software and even google drive have a "recently used" section, this is a similiar idea, just letting the user pin all the files and folders they often need for better focus and easier navigation.

Just a quick makeup of what it could possibly look like:
![Files pinned folders](https://user-images.githubusercontent.com/71931749/129193807-e925fbb1-5429-43c2-a27c-afce5b682de1.png)

![Filles pinned folders big](https://user-images.githubusercontent.com/71931749/129193057-1f5a38d4-893c-49d7-bf9c-1e927287c64a.png)

Pinned files/folders should stay in the list below, so it doesn't change the order you are accustomed to.

### Alternatives

Files is starting to support tagging, and while you could list tagged folders on the top it's just not quite the same. I feel like the features would work really well together. Tagging for more general organisation, and pinning for files/folders you want to have quick and easy access to.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| There will be a pinned section in a when a user pinned at least one file/folder | Should |
| There will be an option in the right click menu to pin a file/folder to the top | Should |
| Pinned files will have an option in the right click menu to unpin them | Should |
| This will replace tagging functionality | Won't |
| Replace the "pin" icon in right click with a star | Could |

Forgive me for not finding a better star icon here
![Menu](https://user-images.githubusercontent.com/71931749/129196169-4c5fcd4d-fb0b-4f8e-9679-c18bb2833580.png)

### Files Version

Version: 1.9.21.0 OS Version: 10.0.19043.1110

### Windows Version

Windows 10 Home 21H1

### Additional comment

I will need to use tagging for a while to see if I still would need pinning but as is I think it could be a nice functionality

**Comment by gave92** [comment]
That's an interesting concept, even though you still need to navigate to the parent folder and you won't be able to group files from different folders in the same place.
Have you tried the Bundles feature btw? Sounds about what you need (pin a group of files and folders to the homepage)

**Comment by mangoepic** [comment]
> Have you tried the Bundles feature btw? Sounds about what you need (pin a group of files and folders to the homepage)

The difference is probably that Bundles is more like Desktop shortcuts and the pin to top functionality more of a quick-access organization/productivity feature

Being able to pin files/folders right in the folders gives me a better understanding of the file system I'm working in

For example imagine you have a Projects folder with different types of projects you may or may not currently work on.
If you change projects you can just pin something to the top with two clicks or unpin it again, while Bundles take a bit more effort

The way I us file explorers is often more like "walking through" the filesystem instead of using shortcuts

**Comment by R3voA3** [comment]
I like the idea. Certainly a feature that stands out.

**Comment by mangoepic** [comment]
> @mangoepic is this something you can use the tags feature for?

I want to try it, but tags are still a bit buggy/feeling a bit hacky, imma see if I can open bug reports

**Comment by yaichenbaum** [comment]
Merging with #6514
