### ISSUE TITLE
Language issues

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5797]
### Description

English UK
![image](https://user-images.githubusercontent.com/26977075/129279157-b48420e2-8db3-4c8d-9188-bbeb5b8acacd.png)
![image](https://user-images.githubusercontent.com/26977075/129276127-3117bc5c-ae2b-44e8-b2a7-709a29b39a32.png)
![image](https://user-images.githubusercontent.com/26977075/129276129-1b86a66e-cafd-4618-80a6-752d329567cb.png)

English US
![image](https://user-images.githubusercontent.com/26977075/129279000-ed7efcef-5b6e-4523-a373-0f36b361057f.png)

These are not correct. All area with default is capitalised.

### Expected behavior

They should be as they were before

### Files Version

1.9.23

### Windows Version

10.0.19043.1151

**Comment by gave92** [comment]
Lol this is what you get with automatic translations I guess.. \+ @yaichenbaum

**Comment by esibruti** [comment]
@gave92 If you want, I can fix these translations in the files themselves.
