### ISSUE TITLE
Incorrect layout is applied when the app starts with a small app window

### ISSUE THREAD

**Issue by gus33000** [files-community/Files#5801]
### Description

The files app seems to adopt the wide window layout when started with a small window on startup, here is a screenshot to help understand the problem (here the app was just started from the start menu)
![Screenshot (35)](https://user-images.githubusercontent.com/3755345/129316562-fccbf3c7-d2a9-45bc-8ba8-9689614f6cf7.png)

Rotating back and forth the device is enough to cause a layout update and fix this issue.

### Steps To Reproduce

1. Open the app as a small window
2. Notice the layout is wrong

### Expected behavior

The window should look like this:
![Screenshot (36)](https://user-images.githubusercontent.com/3755345/129316582-25a7da08-17c2-486f-b2b4-b7b2f36cb078.png)

### Files Version

Commit Hash: 965e60852c3bb7998ec000db27c5e7b32635257f

### Windows Version

Windows 11 21H2 22000.132 ARM64

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5814.
