### ISSUE TITLE
Can´t drag and drop Shortcuts

### ISSUE THREAD

**Issue by AssasinMaster** [files-community/Files#5802]
### Description

Its not possible to drag and drop Shortcuts of Folders/ Applications/ etc. to a Folder or a new Location. You cant even "pick it up".

### Expected behavior

Shortcut should be moved to a different Folder/ Location.

### Files Version

1.9.23.0

### Windows Version

Windows 10 20H2

**Comment by gave92** [comment]
Sadly this is a limitation of the uwp platform. Shortcuts (and hidden files) can only be copy/pasted, not dragged.
We're looking for workarounds.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5810.
