### ISSUE TITLE
Can't use middle click or ctrl+click to open a new tab

### ISSUE THREAD

**Issue by oooooooooooooooo** [files-community/Files#5805]
### Description

Title

### Expected behavior

Most applications and program use those two mechanisms for quickly opening new tabs and for some reason it's not working on my end. Can't see anything in the settings that would indicate that I disabled it and it works for me in all other programs.

### Files Version

v1.5

### Windows Version

Windows 20H2

**Comment by gave92** [comment]
Thanks for this report. Middle click is working in the beta version.
