### ISSUE TITLE
Can't cut or copy files

### ISSUE THREAD

**Issue by SomeWeirdDuck** [files-community/Files#5806]
### Description

When I copy or cut a file through the context menu or a keyboard shortcut, and then paste it, nothing happens

### Expected behavior

Files should be inserted in the desired location

### Files Version

v1.5.0.0

### Windows Version

Windows 10 21H1 19043.1110

**Comment by josh-65** [comment]
You will need to upload the logs folders. You can get them in files settings > about > open log folder

**Comment by SomeWeirdDuck** [comment]
[debug.txt](https://github.com/files-community/Files/files/6982336/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6982337/debug_fulltrust.txt)

**Comment by gave92** [comment]
Also #4961, #4665, #3615, #3092. Haven't yet seen the report on the beta version.

**Comment by SomeWeirdDuck** [comment]
> Thanks for this report. What happens when you drag and drop instead?

In Tiles view a forbidding sign appears and nothing works
![image_2021-08-13_173409](https://user-images.githubusercontent.com/73939491/129373320-173e5fcc-504e-45e8-9754-b78286beae4e.png)
But in Details view all works fine
![image_2021-08-13_173227](https://user-images.githubusercontent.com/73939491/129373066-535a031f-89fd-4e56-a46a-ffe0e86cc64f.png)
I will add that if there is a transition to a folder, you need to drag the file to the sidebar and then back to the desired folder

**Comment by xmha97** [comment]
Please fix this issue, "Files" is my default file manager.

**Comment by MalteTasler** [comment]
I have this issue, too, when I am in column view. As it appears rather randomly, I wasn't able to gather more information about why and how this happens. I will further look into this.

**Comment by Gabrielbdd** [comment]
I'm also having this issue. What is more strange is that it works when copying a file from the File apps to the other places other than Files itself. I can drag and drop

**Comment by gave92** [comment]
Merging with #7459
