### ISSUE TITLE
[bug] [Rename] [Quicklook] - rename on <Space> click. <Win11><v1.9>

### ISSUE THREAD

**Issue by 2ndBillGates** [files-community/Files#5807]
### Description

I want to use Quicklook in FIles.

When I select a file and click (Space), it triggers rename in Files app.
Also I cannot click (Space) to close Quicklook window again.

However,
If I click it fast enough, Quicklook cannot be closed, but leaving rename triggered in the background.

### Steps To Reproduce

I want to use Quicklook in FIles.

When I select a file and click (Space), it triggers rename in Files app.
Also I cannot click (Space) to close Quicklook window again.

However,
If I click it fast enough, quicklook cannot be closed, but leaving rename triggered in the background.

### Expected behavior

Here's a video showing how it happen and how it normally works in Explorer.exe
[https://streamable.com/o6ypym]()

### Files Version

Version: 1.9.23.0 OS Version: 10.0.22000.120

### Windows Version

Windows 11 version 21H1 build 22000.120

**Comment by 2ndBillGates** [comment]
Also when renamed by click the (space) key.
Files cannot be renamed again when Files is opened.
![unknown](https://user-images.githubusercontent.com/60785205/129385185-c511064b-02d9-424f-b2e6-e2b4a024148f.png)


`When I click space, it trigger rename. then I try to change it back. but it does not allow me to rename the file, explorer says it's using by Files App.
Files App also say the files is in use cannot be renamed`

**Comment by 2ndBillGates** [comment]
<Using Quicklook will rename it into nothing>

for example, I want to preview this file "abc.mp4"
Quicklook(space) Open  ->  Quicklook(space) close
file name turned into ".mp4"

that didn't happen in the retail version 1.5

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5815.
