### ISSUE TITLE
[Problem] [Rename] - Rename trigger everywhere [Win11] [V1.9]

### ISSUE THREAD

**Issue by 2ndBillGates** [files-community/Files#5808]
### What's the Problem?

Rename triggers clicking on "date, size, type"

### Solution/Idea

In explorer, normally, it only trigger rename when clicking on the name.

While in Files, It trigger everywhere, which is annoying, I can't select files when accidentally click twice, I cannot cancel rename window when click on other places/space like (date, size, type...)

Here's a video showing how it happened & what it does in Windows Explorer.exe
[https://streamable.com/negmyj](url)

### Alternatives

1) Trigger rename ONLY when clicking on the name.
2) Rename can be cancel when clicking the other places (date, size, type...)

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 1.9.23.0 OS Version: 10.0.22000.120

### Windows Version

Windows 11 version 21H1 build 22000.120

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5816.
