### ISSUE TITLE
Right click menu weirdly small

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5809]
### Description

![image](https://user-images.githubusercontent.com/26977075/129388915-520e12bd-29c6-45e3-8e11-e1301aad9428.png)
The right click menu was fine the way it was in <1.9.21. Right now the max height seem to be depending on non shell items amount.

### Expected behavior

It should show all items if the display is large enough.

### Files Version

1.9.23

### Windows Version

10.0.19043.1151

**Comment by gave92** [comment]
Due to WinUI issues the moment we can either have:
- a small menu
- a menu that jumps around or goes out of screen or gets cut

The small menu is probably the lesser of the two evils 😂, but this is an issue nonetheless.

**Comment by gave92** [comment]
Merging with #5884
