### ISSUE TITLE
Laggy window resizing of Files.

### ISSUE THREAD

**Issue by RickeyHo** [files-community/Files#5811]
### Description

When you are on the home page of Files, the window resizes smoothly. But when you open a directory that has a lot of Files, like Downloads, and / or Documents. The window resizing becomes extremely laggy.

### Steps To Reproduce

1. Try resizing the Window with Files on the homepage
2. Enter the Documents / Downloads directory or any directory with a lot of files,  and try to resize the window.

### Expected behavior

I expected the Files window to resize smoothly.

### Files Version

1.9.23.0 

### Windows Version

Windows 11 Beta 10.0.22000.132

**Comment by gave92** [comment]
Thanks for the report. Is it laggy only in Details view or also in Tiles / Grid view?

**Comment by RickeyHo** [comment]
> Thanks for the report. Is it laggy only in Details view or also in Tiles / Grid view?

It is also lagging in Tiles / Grid view.

**Comment by yaichenbaum** [comment]
@RickeyHo this issue should be resolved in the preview version. http://files.community/download/preview
