### ISSUE TITLE
App crash when trying to delete an program in use

### ISSUE THREAD

**Issue by EsGod** [files-community/Files#5812]
### Description

App crash when trying to delete an program in use, i did this trying to delte taskbarX, ps: moving an file wich is in use may cause the same problem

### Steps To Reproduce

1 try to delete an app wich is in use 

### Expected behavior

only show a message e, and dont close 

### Files Version

1.5

### Windows Version

Windows 10 Pro 21H1 19043.1110

**Comment by gave92** [comment]
Thanks for the report. Please upload the app's debug logs.
