### ISSUE TITLE
Give some indication a search is in progress

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5813]
### What's the Problem?

When I search something in a drive there's no indication its doing it. 

### Solution/Idea

When pressing enter for a search it would be better to show a blank screen and have the tab say Searching or "folder" search with the progress ring going, The blank area is were the content will appear.

### Alternatives

None

### Files Version

1.9.23.0

### Windows Version

10.0.19043.1151

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5842.
