### ISSUE TITLE
Themes for Files

### ISSUE THREAD

**Issue by HAKSRUN-LAO** [files-community/Files#5818]
### What's the Problem?

How to use Themes for Files extension?

### Solution/Idea

I have already installed the Themes for Files extension; however, I can't find anywhere to use or open it.

### Alternatives

none

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

1.5

### Windows Version

21H1

**Comment by winston-de** [comment]
The themes extensions currently works only with preview versions of Files, not work in the current stable release (1.5).

**Comment by HAKSRUN-LAO** [comment]
So how can I uninstall it now then?

**Comment by gave92** [comment]
You can uninstall the themes extenion in Windows Settings > Apps > Files -> at the bottom

**Comment by HAKSRUN-LAO** [comment]
I found it, thank you!

**Comment by gave92** [comment]
Closing this as Themes are only supported in the preview version. If you wish you can join Files Insiders and try out the beta:

> Join the insider flight group
You can fill out this form to get access to the preview builds in the Microsoft Store https://forms.office.com/r/UsaBmzC99n. It can take a couple of days until you're added to the flight group, but once added, you will start receiving updates to the regular Files app through the Microsoft Store
