### ISSUE TITLE
Moving and Copying Files

### ISSUE THREAD

**Issue by HarshKr290802** [files-community/Files#5820]
### What's the Problem?

When we move or copy files from from a folder to another we do not get a proper dialog box for replacing/cancelling the existing ones . Instead we get dialogs one after another separately.

### Solution/Idea

Please implement this feature.

### Alternatives

If not this then please think of something new like this.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

v1.5

### Windows Version

Windows 10 21H1 19043.1110

**Comment by gave92** [comment]
Thanks for this report. This has been implemented in the preview version.
