### ISSUE TITLE
Make icons load faster

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5822]
### What's the Problem?

Currently loading files and folders icons is slow but in file explorer it quick.

### Solution/Idea

I believe windows has a caching system for the icons. Files should use this if it can.

### Alternatives

Make your own caching system.

### Files Version

1.9.23

### Windows Version

10.0.19043.1151

**Comment by winston-de** [comment]
> I believe windows has a caching system for the icons. Files should use this if it can.

Files already uses the windows apis for thumbnails, which includes using the thumbnail cache.

**Comment by josh-65** [comment]
doesn't seem to work as it loads the icon one by one and windows file explorer quite instant unless it a new folder

**Comment by JoshKasap** [comment]
I don't think image caching is the issue. The reason windows explorer seems instant to you is that it's all you've ever used hence most files have had a thumbnail cached in the past. From my observations, it seems to load thumbnails as fast as windows explorer.

That said there is definitely some slowdown when compared to windows explorer when it comes to general folder navigation. I visit a folder (even one that has already cached) there is roughly a 1 second loading time before files show and another second wait before I can interact with the files shown. 

There are some scenarios where navigation is instant but the above scenario seems to happen a lot whereas on windows explorer it tends to be instant.

**Comment by josh-65** [comment]
I used files a lot more than file explorer. But even with the same directory's it slower than file explorer sometimes. In small directory's its not that bad but bigger ones it does get slow.

files

https://user-images.githubusercontent.com/26977075/129702396-b7ddcc25-f19c-4c12-940f-3203f9fbe2a0.mp4

file explorer

https://user-images.githubusercontent.com/26977075/129702962-d5e90b06-64b6-4ddb-8b83-8ffc9e8555d4.mp4

**Comment by gave92** [comment]
Perhaps we could try showing the generic icon for folders and a cached icon based on file type for files instead of the monochrome icons, until the icon from explorer is loaded.

**Comment by lukeblevins** [comment]
@yair100 Based on our discussion from a while back, is it preferable to do what @gave92 suggested or leverage elements from the standard GridView placeholder behavior seen when scrolling through a virtualized data source? Or was this only intended for file items?

Personally, I don't see the harm of displaying an identical standard folder icon.

**Comment by yair100** [comment]
> @yair100 Based on our discussion from a while back, is it preferable to do what @gave92 suggested or leverage elements from the standard GridView placeholder behavior seen when scrolling through a virtualized data source? Or was this only intended for file items?
> 
> Personally, I don't see the harm of displaying an identical standard folder icon.

How would that affect the support for displaying custom thumbnails?

**Comment by lukeblevins** [comment]
@yair100 The generic icon, if I understand correctly, would be displayed while the actual folder icon is being loaded.

**Comment by yair100** [comment]
> @yair100 The generic icon, if I understand correctly, would be displayed while the actual folder icon is being loaded.

That should work 👍
