### ISSUE TITLE
Bug: Scroll position isn't always in the correct position

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#5825]
### Description

When in a folder that has folders named with _ at the start or group by options enabled the scroll will not be at the top.

### Steps To Reproduce

1) Create a folder with enough items for scrolling
2) Create a folder with an _ at the start or use group by options
3) Go to previous folder and back
4) See scroll position not at the top

### Expected behavior

Should start at top or directory always

### Files Version

1.9.23.0

### Windows Version

10.0.19043.1151

**Comment by yaichenbaum** [comment]
Is this specific to large directories are just when there are enough items to enable the scroll bar?

**Comment by Josh-65** [comment]
Ive only had it with large directories (200+) when files and folders load and display in chunks

**Comment by IlyaSulli** [comment]
I just tested it, it is something to do with having folders and files together, either the folders or the files load first so that when it opens it goes to the top of that and then when the other is loaded, the position is partially scrolled. It is not based on file size, Since I used 30 empty files and 28 small images.

**Comment by IlyaSulli** [comment]
UPDATE: With my test, only 25 folders are loaded at first.

**Comment by Kradziej** [comment]
Any updates here? It's really not very convenient to open a folder with hundreds of files and land in the middle of the directory, seem like a critical bug to me.

**Comment by yaira2** [comment]
@Kradziej is this only an issue in the downloads folder? If that's the case, you can work around it by setting the grouping type to none.

**Comment by JTFA** [comment]
> @Kradziej is this only an issue in the downloads folder? If that's the case, you can work around it by setting the grouping type to none.

the position is still not correct when the grouping type is set to none

**Comment by yaira2** [comment]
@JTFA I'm having trouble reproducing this on my device, can you upload a screen recording to GitHub so I can make sure I'm following step by step?

**Comment by JTFA** [comment]
> @JTFA I'm having trouble reproducing this on my device, can you upload a screen recording to GitHub so I can make sure I'm following step by step?

this bug occurs when I open the downloads folder with the default settings just after installation, and my downloads folder contains 70 folders and over 1300 files, and the files and folders span about a year and a half

**Comment by yaira2** [comment]
Without a screen recording it's for me to try and repro, the best I can recommend is to make sure you disabled grouping for the Downloads folder specifically via the toolbar.
![image](https://github.com/files-community/Files/assets/39923744/5505104b-5679-4fa4-9e99-7f058e3acd92)

**Comment by JTFA** [comment]
> Without a screen recording it's for me to try and repro, the best I can recommend is to make sure you disabled grouping for the Downloads folder specifically via the toolbar. ![image](https://private-user-images.githubusercontent.com/39923744/322285020-5505104b-5679-4fa4-9e99-7f058e3acd92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxMDk1MDcsIm5iZiI6MTcxMzEwOTIwNywicGF0aCI6Ii8zOTkyMzc0NC8zMjIyODUwMjAtNTUwNTEwNGItNTY3OS00ZmE0LTllOTktN2YwNThlM2FjZDkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDE1NDAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2ZjY3NjIwNzBlNWVmM2ZmOGE1ZmI5NDRlYmMxZjQ0Mjc5YjIzYzY3OTlmNWNlMzcyZTlhNTNmZWNjZjhkMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sm9acHYNmizTGbBmei3WFeWN-pOJyyl5mrEJQz_1OSo)

is there any other settings you are interested in? I can record the screen now

**Comment by yaira2** [comment]
A screen recording would be helpful, thanks!

**Comment by JTFA** [comment]
> A screen recording would be helpful, thanks!


https://github.com/files-community/Files/assets/57850248/59276161-a8d3-4527-ad8b-819e56043e4f

all my settings are displayed in the video

**Comment by yaira2** [comment]
What happens if you change the sort by type to name?

**Comment by JTFA** [comment]
> What happens if you change the sort by type to name?

when sort by ascending, it is at the correct position.
but when sort by descending, the position is at the last folder.

**Comment by yaira2** [comment]
@Josh65-2201 is this the same repro steps for you?

**Comment by Josh65-2201** [comment]
It happen for me with the ascending sort too. Descending puts it at the bottom of the folder for me even when there other content is files.
