### ISSUE TITLE
Video Drivers crashing when using Files

### ISSUE THREAD

**Issue by XjoaxelX** [files-community/Files#5826]
### Description

When Im using Files V2 everything starts lagging a lot and my screen goes black. Using latest Nvidia Drivers and latest Windows 11 version.

### Steps To Reproduce

Just open Files V2 and happens for me.

### Expected behavior

Just to not crash my computer. Before today it was working well.

### Files Version

2.0

### Windows Version

Windows 11 Insider Preview Build 22000.132

**Comment by yaichenbaum** [comment]
@XjoaxelX the latest version available of Files is v1.9.23, can you check which version you're using?
