### ISSUE TITLE
files v2 crashs on startup on windows 10 (same issue after reset the app)

### ISSUE THREAD

**Issue by Fefedu973** [files-community/Files#5827]
### Description

files v2 crashs on startup on windows 10 (same issue after reset the app)

### Steps To Reproduce

1 open
2 see logo
3 close

### Expected behavior

crash on strtutp

### Files Version

v2

### Windows Version

windows 10 pro for workstations 21h1 

### Relevant Assets

[debug_fulltrust.log](https://github.com/files-community/Files/files/6987328/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/6987329/debug.log)

**Comment by yaichenbaum** [comment]
@Fefedu973 which version of Files are you having this issue with?

**Comment by Fefedu973** [comment]
The last one

**Comment by yaichenbaum** [comment]
@Fefedu973 unfortunately we can't really help without a version number, please reopen this issue once you the version number.
