### ISSUE TITLE
F3 for search

### ISSUE THREAD

**Issue by ttalonso** [files-community/Files#5831]
### What's the Problem?

F3 key for launch search doesn't works

### Solution/Idea

Add F3 key for search

### Alternatives

f3 for search

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

1.9

### Windows Version

windows 11

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5842.
