### ISSUE TITLE
Set Default Layout

### ISSUE THREAD

**Issue by xmha97** [files-community/Files#5832]
### What's the Problem?

I want to set default layout.

### Solution/Idea

![image](https://user-images.githubusercontent.com/23485114/129481869-4edb6208-b9c2-4419-883d-f083a82fea2b.png)

### Alternatives

I can't find an option to set the default layout.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

v1.9.23.0

### Windows Version

Windows 11 21H2 22000.132

**Comment by gave92** [comment]
Thanks for this suggestion. You should already be able to set a default layout by:

- turning off "enable individual preferences for folders" option in Files settings
- setting your desired layout mode for any directory
- Optional: turning back on "enable individual preferences for folders"

Merging with #4155
