### ISSUE TITLE
File/Folder priority when sorting option

### ISSUE THREAD

**Issue by Darhagonable** [files-community/Files#5834]
### What's the Problem?

When sorting by date modified folders show up first and then files. In normal explorer it's the other way around.

### Solution/Idea

Since this probably is a matter of preference it would maybe be a good idea to add it as an option in the sort menu.

The alternatives should be:

- Sort files and folders together
- Files first
- Folders first

### Alternatives

My first idea was just to change it to the way its done in explorer were files gets sorted first and folders second.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to have more control over the sorting behavior and find their files/folders faster | Must |

### Files Version

1.9.23.0

### Windows Version

Windows 10 Home 19043.1165

**Comment by Void48** [comment]
I really hope this gets added with the official Files v2.0 release on the MS Store. This is really a must ![sad](https://user-images.githubusercontent.com/85196642/132097884-117e725c-1178-444c-bbc6-be78476d40e3.png)

**Comment by Darhagonable** [comment]
I doubt it will happen with 2.0 but hopefully they'll consider it for a future update

**Comment by serg06** [comment]
Bump, this is important to my workflow. I always sort by newest date to see my newest files without needing to scroll, but this bug forces me to scroll.

**Comment by Darhagonable** [comment]
> Does the "List and sort directory alongside files" option give the wanted result?

of the three cases
- Sort files and folders together
- Files first
- Folders first

that only covers the "Sort files and folders together" case.

**Comment by Josh-65** [comment]
Merging with #9574
