### ISSUE TITLE
Broken text while selecting files

### ISSUE THREAD

**Issue by donut2008** [files-community/Files#5835]
### Description

On selecting a file, the text saying "# file(s) selected" is broken. Screenshot for clarity:
![image](https://user-images.githubusercontent.com/76439683/129486146-d31b0144-8c6c-42aa-b62d-d292ec57da1e.png)

### Steps To Reproduce

Select a file/multiple files.

### Expected behavior

Text should say "1 file selected", "2 files selected" etc.

### Files Version

v1.9.23.0

### Windows Version

Windows 10 20H2 build 19042.1165

**Comment by gave92** [comment]
What language/locale have you set in Windows / Files?

**Comment by donut2008** [comment]
> What language/locale have you set in Windows / Files?

Files:
![image](https://user-images.githubusercontent.com/76439683/129486549-2dd57033-9e63-41aa-a861-c8f367c71591.png)

Windows:
![image](https://user-images.githubusercontent.com/76439683/129486550-474a7d02-0871-4015-8cef-d15c283badd8.png)

**Comment by donut2008** [comment]
It's fixed now
