### ISSUE TITLE
Directories start from the middle

### ISSUE THREAD

**Issue by Darhagonable** [files-community/Files#5837]
### Description

Sometimes when opening some directories (for example downloads from home screen) it will show up having been scrolled down to the middle instead of starting from the top.

This doesn't happen always but seems to happen 1/3 of the times

### Expected behavior

To always start at the top of the directory

### Files Version

1.9.23.0

### Windows Version

Windows 10 Home 19043.1165

### Relevant Assets

![image](https://user-images.githubusercontent.com/14127357/129488845-4a7df612-5426-4b29-b041-4dedb93cd503.png)
[debug.log](https://github.com/files-community/Files/files/6988671/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6988672/debug_fulltrust.log)

**Comment by gave92** [comment]
Thanks for this report. Merging with #5819
