### ISSUE TITLE
Touch input broken in many ways

### ISSUE THREAD

**Issue by ClintBritt** [files-community/Files#5838]
### Description

Single touches just change selection in SideBarControl (root issue may be in NavigationView), and never cause a InvokeItem. Can't expand menu items, or invoke the settings panel. Additionally, as report elsewhere, double-taps don't work at all (may be due to the fact a double touch always moves slightly). This files application is a wonderful start, but large bugs for touch seems a big flaw.   

### Steps To Reproduce

1. Use a touch screen to attempt to invoke items in the SideBarControl
2. Use a touch screen to try and expand or hide items in the drives menu
3. Use the touch screen to try and double-tap

### Expected behavior

1. Tapping a item on the SideBarControl would actual select the item and invoke it.
2. Tapping the expand/hide of a Menu item in the SideBarConrol would actual do a expand or hide
3. Double tapping with a touch screen would actually be interpreted as double-clicks

### Files Version

v2.6.1

### Windows Version

Win10 IoT Core 10.0.177763.1757

**Comment by yaichenbaum** [comment]
@ClintBritt which of version of Files are you using?

**Comment by ClintBritt** [comment]
I

> @ClintBritt which of version of Files are you using?

I did state it is 2.6.1, ops, sorry. 1.5.

**Comment by ClintBritt** [comment]
That is not correct either. I am out of date. I have ported this project to IoT Core, and my last merge was not from your tip. My bad. Go ahead and close this issue. But boy I see massive changes that will take some real effort to port again. Thanks for the attempt at help.
