### ISSUE TITLE
Need "press and hold" operation to support "right-click" operations for touch screens.

### ISSUE THREAD

**Issue by ClintBritt** [files-community/Files#5839]
### What's the Problem?

Can not support any type of right click operation on a touch screen

### Solution/Idea

Pressing with the touch and holding for a specific time would cause the software to invoke the "right-click" like input and simulate the right-click operation.

### Alternatives

Any method that could allow a user with a touch screen to get the "right-button-click" functionality.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

v2.6.1

### Windows Version

Win10 IoT Core 10.0.177763.1757

**Comment by winston-de** [comment]
Thanks for the feedback. You should already be able to right click an item with touch by pressing an item and holding for approximately 1 second. Does this not work on your device?

**Comment by ClintBritt** [comment]
> Thanks for the feedback. You should already be able to right click an item with touch by pressing an item and holding for approximately 1 second. Does this not work on your device?

No, it does not for me. I will doublecheck that I have the latest everything first. Will do that first thing in the morning

**Comment by ClintBritt** [comment]
OK, I was not at tip. My bad, sorry.
