### ISSUE TITLE
Downloading & launching MSIXBundle version 1.5

### ISSUE THREAD

**Issue by nono22300** [files-community/Files#5841]
### Description

Dear all,
When downloading & launching MSIXBundle version 1.5 i have this message
Le programme d'installation d'application n’a pas pu installer les dépendances du package. Demandez au développeur le package Microsoft.UI.Xaml.2.5.

so pb linked to package Microsoft.UI.Xaml.2.5.

how can i move forward?

Thanks

BR
Nono

### Steps To Reproduce

1. Download MSIXBundle version 1.5
2. Launch it
3. Package Microsoft.UI.Xaml.2.5 is missing

### Expected behavior

installation is complete:)

### Files Version

v1.5

### Windows Version

Windows 10 enterprise

**Comment by gave92** [comment]
Here: [Files_dependencies.zip](https://github.com/files-community/Files/files/6990246/Files_dependencies.zip)

@yair100 do we still provide an AppInstaller package?

**Comment by nono22300** [comment]
it is working fine now!
@gave92 thanks!

**Comment by yair100** [comment]
> Here: [Files_dependencies.zip](https://github.com/files-community/Files/files/6990246/Files_dependencies.zip)
> 
> @yair100 do we still provide an AppInstaller package?

Not at the moment.
