### ISSUE TITLE
Request of HD icons of files

### ISSUE THREAD

**Issue by Li-ft** [files-community/Files#5846]
### What's the Problem?

The icons of files are blurry

### Solution/Idea

use high resolution icons

### Alternatives

use SVG?

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

v1.5

### Windows Version

win 10 21H2 19044.1165

### Additional comment

![Files screen shot](https://user-images.githubusercontent.com/36444914/129724790-5ba25c5f-ecf6-4a1e-bcdc-dc0b2c776e4f.jpg)

**Comment by josh-65** [comment]
Can you check your version number they don't seem correct. Also those icons are done by windows so I don't think files can do anything about it.

**Comment by Li-ft** [comment]
I double-check the windows version and the version of Files, they are all correct. I am in the Windows Previewer Program so the Windows version may not be normal to see.

**Comment by yaichenbaum** [comment]
This issue appears to be resolved in `main`.
