### ISSUE TITLE
Improving file(folder?) tags

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#5848]
- [ ] Add teaching tip or explanation in the docs about how to use Tags
- [ ] #9587
  - [ ] auto assign tag when item is dropped into a tag
- [x] add sidebar section for tags
  - [x] auto assign tag when item is dropped into a tag
  - [x] add setting to hide sidebar section
- [ ] #9588
- [ ] create virtual folder to contain tags
  - [ ] add context menu item to open file location 
- [ ] #9586
- [ ] #9585
- [x] move colored circle to the tag column
- [ ] #9584

![image](https://user-images.githubusercontent.com/39923744/129737364-06d0f18e-4a89-4813-93d2-87f6462ceaf2.png)

**Comment by gave92** [comment]
We absolutely need a colored icon for that section though xD

**Comment by yaichenbaum** [comment]
@mdtauk can you upload the icon you created for this?

**Comment by mdtauk** [comment]
At the moment its just a graphic, not sure if it needs to be converted to an ICO file

**Comment by yaichenbaum** [comment]
I belive PNG format should be fine.

**Comment by mdtauk** [comment]
> I belive PNG format should be fine.

What sizes?

**Comment by yaichenbaum** [comment]
I think 24x24 would be enough but maybe @gave92 can confirm.

**Comment by mdtauk** [comment]
![tag_24_x1 5](https://user-images.githubusercontent.com/7389110/129788873-611fa4e4-0832-4bb9-ad41-f2c19d0c0d33.png)
![tag_24_x1](https://user-images.githubusercontent.com/7389110/129788875-882f04d7-734f-4b11-bf95-0075cb2876d9.png)
![tag_24_x2](https://user-images.githubusercontent.com/7389110/129788909-0289565e-36da-4af1-a977-da31f8c6ddf9.png)

**Comment by yaichenbaum** [comment]
Thank you!

**Comment by Tropix126** [comment]
I might also suggest an update to the tag items in the context menu UI, since it's a tad clunky right now.
![image](https://user-images.githubusercontent.com/42101043/131667256-558772ad-ebfb-41d5-8b82-3218d8f0e1d7.png)

**Comment by bimgeek** [comment]
Just discovered Files. It looks great. Notion like tagging system would make it even better.

**Comment by SigmaStar** [comment]
What about add moe than one tag to a file and search files with tag?

**Comment by yaichenbaum** [comment]
I opened separate issues to track these items, thank you for a great discussion!
