### ISSUE TITLE
Add right click mapping options to the network drive section on sidebar

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5851]
### What's the Problem?

Currently I have to go on the network device section witch takes a while to load and the options hidden at the bottom of the right click menu

### Solution/Idea

Add the option to map network drive on sidebar right click (Could also add Map FTP server)
![image](https://user-images.githubusercontent.com/26977075/129766369-743361a5-11ef-4b1a-b91e-09aa2a3cab97.png)

### Alternatives

None

### Files Version

1.9.24

### Windows Version

10.0.19043.1151

**Comment by gave92** [comment]
#5836 adds map network drive to the sidebar context menu. But atm you can also find it on the homepage in the triple dot menu of the drives section.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5836.
