### ISSUE TITLE
Folder not combining on pasting

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5852]
### Description

If I have two folder with the same name but different content they wont be combined. they will either replace the old content with the new content or just make the same folder with "- copy" added on.

### Steps To Reproduce

1) Create a folder with a name in a directory.
2) Add a file to it.
3) Create a new folder with the same name but another place
4) Add a file with a different name
5) Cut on of the folders and paste it were the other one is

### Expected behavior

It should bring up the conflict dialog and ask me to what I want to do and add a combine button. So the content merged.

### Files Version

1.9.24

### Windows Version

10.0.19043.1151

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7001766/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7001767/debug_fulltrust.log)

**Comment by gave92** [comment]
If you choose replace in the conflict dialog it should merge the folders and replace files if they have the same name. Could you confirm this?

**Comment by josh-65** [comment]
When I tried that it seemed to just delete the original files in there. However continuing to use it I've seen that some file just wont copy, usually there left in the original place witch it wasn't,

**Comment by josh-65** [comment]
Just tried it again brings up the prompt I click replace existing and it just made folder name - copy versions. Didn't edit or add any data in the original non - copy folder.

**Comment by gave92** [comment]
Are you in a local folder? Not a network folder or something?

**Comment by josh-65** [comment]
Its a local folder. Seem to happen sometimes didn't do it for the next folder I did. I'll upload the updated logs if that helps.
[debug.log](https://github.com/files-community/Files/files/7022876/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7022877/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
@gave92 any ideas on this?

**Comment by gave92** [comment]
Nope, as I can't reproduce.

**Comment by josh-65** [comment]
Closing due to it not happening for a long time.
