### ISSUE TITLE
Feature: Change "File folder" text to say "Folder"

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#5853]
### Description

![image](https://user-images.githubusercontent.com/26977075/129773701-35858cf8-1e51-4fdf-85a3-c68086309635.png)

### Expected behavior

- Folder type should be displayed as "Folder"

### Files Version

1.9.24

### Windows Version

10.0.19043.1151

**Comment by gave92** [comment]
What does explorer say?

**Comment by josh-65** [comment]
The same but it still doesn't seem right

**Comment by gave92** [comment]
I can agree, we pull the type from explorer but we can make an exception for this case. Anything against this @yair100?

**Comment by yaichenbaum** [comment]
Why is this showing up differently than other folders?

**Comment by josh-65** [comment]
That's what's displayed for a folder.

**Comment by yaichenbaum** [comment]
@gave92 I think this would be a good change 👍

**Comment by QuaintMako** [comment]
This one is only an issue of location. Can be pretty easily fixed on Crowin. Problem is the modification needs to be propagated to all languages. Is there a way to raise an issue on a given string on all translations?

**Comment by yaichenbaum** [comment]
I believe changing the text of the source string will reset the translated strings.

**Comment by QuaintMako** [comment]
Issue may be void depending on what's chosen in #10338.

**Comment by QuaintMako** [comment]
@yair100 since #10338 has been voided, is this issue still relevant?

**Comment by yaichenbaum** [comment]
I think we should make an exception for this one and make this change.

**Comment by QuaintMako** [comment]
Alright, will look into the changes then for it.
