### ISSUE TITLE
Sort Folders and Files Separately 

### ISSUE THREAD

**Issue by JoshKasap** [files-community/Files#5854]
### What's the Problem?

Undesirable sort

### Solution/Idea

When windows explorer sorts it will apply your sort to folders and files separately. So if you sort by name all folders will be sorted from A to Z at the top and then all loose files will be sorted from A to Z below the folders. 

You can see what I mean in the below image. Both windows are sorted by date but windows explorer sort is far nicer. 
![image](https://user-images.githubusercontent.com/56367532/129833236-6510ced3-9a3c-405f-8474-c9061102ac96.png)

### Alternatives

Instead of fully changing the functionality to or the other, it would be nice to allow a toggle for which behavior you want. This could be applied globally to all folders or individually on a per-folder basis depending on the user's preference. 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Allow users to sort Files and Folder Seperately  | Must |
| Folders must be displayed first| Must |
| Make this feature globally togglable in settings | Should|
| Allow single folders to override global setting allowing certain folders to retain default sort behavior | Could |

### Files Version

1.5

### Windows Version

Windows 10 Pro 21H1 19043.1165

**Comment by gave92** [comment]
There's already an option in settings for this: turn off "Sort files alongside folders" option.
