### ISSUE TITLE
Show more text in small - large icon view 

### ISSUE THREAD

**Issue by JoshKasap** [files-community/Files#5855]
### What's the Problem?

Lots of vertical blank space exists when in small-large icon view

### Solution/Idea

Files make terrible use of vertical space for text when viewing files in small-large icon mode.

A comparison can be seen below. The upper image is windows explorer lower image is Files
![image](https://user-images.githubusercontent.com/56367532/129835160-278a834a-40dd-4f89-bdd3-5f97a270b3b0.png)

You can see Files cuts off a significant amount of text despite actually having slightly smaller file icons and more vertical space.  

This app needs to allow text to wrap and display up 4 lines minimum when in grid view. 

### Alternatives

There is no good alternative. Allowing only 10 characters to be visible is unacceptable. 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Make better use of vertical space for text allowing text to wrap | Must |
| Allow the option in setting for the user to configure explicitly how many verticle lines of text they want to be displayed in grid view | Could |
| Include an option to change font size for grid view | Could |

### Files Version

1.5

### Windows Version

Windows 10 Pro 21H1 19043.1165

**Comment by gave92** [comment]
Thanks for this feedback. Merging with #997.
