### ISSUE TITLE
Change the folder loading animation (make more subtle)

### ISSUE THREAD

**Issue by mangoepic** [files-community/Files#5859]
### What's the Problem?

Currently the loading animation is in the new tab, but that makes it a bit hard on the eyes (this is not an high priority issue though)

![image](https://user-images.githubusercontent.com/71931749/129882195-ba1a9bd4-c41e-46b6-a885-a3bd0abc2410.png)
eye movement

### Solution/Idea

Browsers do this, but some sites for example YouTube has their own loading animation which makes it feel more like it is all in one part.

### Alternatives

 - I think the previous verison of files had a loading bar over the folders, i quite liked this approach
 - Windows explorer doesn't have a special loading animation at all, which is also fine and doesn't put any focus on the waiting process
 - Searching shows a loading bar in windows explorers bar (I don't  like this one)

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Make the loading animation more subtle / easier on the eyes | Should |
| Get rid of the loading animation | Could |
| A loading animation that doesn't make your eyes move so much | Could |

### Files Version

Version: 1.9.25.0 OS Version: 10.0.19043.1165

### Windows Version

Windows 10 Home 21H1

### Additional comment

The animation is only distracting for longer loading like 0,5 seconds, for a quick folder switch it is fine

**Comment by yaichenbaum** [comment]
Thank you for your feedback, as noted in your issue description, we used to have a loading bar in the content area. We made this change based on feedback and while there are some who preferred the old setup, the majority of users prefer the current setup.
