### ISSUE TITLE
Bug: Folder size shows as -1 B in FTP

### ISSUE THREAD

**Issue by Darhagonable** [files-community/Files#5863]
### Description

When in an FTP connection and in details view the folders' sizes show up as -1 B instead of being empty.

### Steps To Reproduce

1. Establish FTP connection
2. Set layout to details view
3. See the issue

### Expected behavior

Size column to be left empty for folders

### Files Version

1.9.25.0

### Windows Version

Windows 10 Home 19043.1165

### Relevant Assets

![image](https://user-images.githubusercontent.com/14127357/129931076-9da1ed5d-9ec2-469f-b1a8-4b4bf9ae62da.png)

**Comment by gave92** [comment]
\+ @hez2010

**Comment by hez2010** [comment]
@gave92 I assumed FTP servers won't response size for folders. Don't have time to investigate this right now, but I think the fix should be quite easy. We can ignore the size property for folders in the constructor of `FtpItem`.

**Comment by yaira2** [comment]
@hez2010 is this an issue in `main`?

**Comment by hez2010** [comment]
Haven't tested but I think yes, we haven't touched the related code yet.
