### ISSUE TITLE
When I start Files 1.5, it is slower than Windows Explorer

### ISSUE THREAD

**Issue by tobiegsmusc** [files-community/Files#5865]
### Description

Windows Explorer is faster every time I start it and you can see the differences immediately without having to use a stopwatch. Files must also get this speed, currently Files is very slow.

### Steps To Reproduce

1. Use a stopwatch and open Windows Explorer. Windows Explorer will be open and fully loaded in 1 second.
2. Use a stopwatch and open Files. Files will be open and fully loaded in 5 seconds.

### Expected behavior

Files must be opened and fully loaded exactly like Windows Explorer in 1 second instead of 5 seconds.

What is fully loaded? That means in the user interface all buttons, icons etc. are fully loaded.

### Files Version

v1.5

### Windows Version

Windows 10 21H1 19043.928

**Comment by gave92** [comment]
Speed as been much improved in Files v2, currently in preview. If you wish to try it you can join Files Insiders.

> Join the insider flight group
You can fill out this form to get access to the preview builds in the Microsoft Store https://forms.office.com/r/UsaBmzC99n. It can take a couple of days until you're added to the flight group, but once added, you will start receiving updates to the regular Files app through the Microsoft Store.

**Comment by tobiegsmusc** [comment]
@gave92 
How fast is it for you Files v2 compared to Windows Explorer?

**Comment by gave92** [comment]
It's still slower to launch and in folder loading, though both have been improved in v2. Feel free to try the beta and judge if you still find that Files is too slow :)

Side note: on the "bright side" Windows Explorer in Windows 11 launches slower that in Windows 10 so that also helps 😂

**Comment by yaira2** [comment]
We're excited to share that startup performance will be significantly improved in the upcoming release of version 3. You can download the preview version from our website https://files.community/download.
