### ISSUE TITLE
Exit search when clicking on Sidebar item

### ISSUE THREAD

**Issue by rishisim** [files-community/Files#5867]
### What's the Problem?

I complete a search result and press enter, whenever I press the same bar in the sidebar [e.g. downloads], the search results remain.

### Solution/Idea

**Idea**
I would like it if it would bring back and show the same section as it was before the search when clicking on the section again. 

[For example, I do a search in downloads. Once I finish my search, when I click on the downloads again, I would like it to bring back the downloads without the search filter] <- This happens in File Explorer, however it does not in Files.

Maybe something you can look into and put the feature in the next update?

### Alternatives

**Work Around**

For now, a person can just click on another section from the sidebar, and move back to the previous section, but it's tedious.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| When Clicking on a X Section after the Search Results, it should revert back to the X Section as it was before Searching | Must |

### Files Version

Version: 1.9.25.0 

### Windows Version

Windows 11 Home 21H2 22000.132

**Comment by gave92** [comment]
At the moment you should be able to click "Back" to exit search.

**Comment by Josh-65** [comment]
This is fixed on 2.3.12.0
