### ISSUE TITLE
Network drives show in the regular drives section

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5870]
### Description

![image](https://user-images.githubusercontent.com/26977075/130158459-a9f27a7e-aac0-4374-a767-c0cf967377f8.png)

### Steps To Reproduce

1) Home page drive widget click the `...` in the top right corner
2) Add a network drive
3) See it in the drives section and not network drives

### Expected behavior

^

### Files Version

1.9,25

### Windows Version

10.0.19043.1151

**Comment by gave92** [comment]
Merging with #4236
