### ISSUE TITLE
Allow folders to be added to Favorites

### ISSUE THREAD

**Issue by rosswebediaglasgow** [files-community/Files#5871]
### Solution/Idea

In the Favorites sidebar, it would be really helpful if we could drag folders into it.
This is possible in File Explorer, so was disappointed to learn its not included in Files.
Having to navigate every time to find the folder I'm looking for is a bit of a pain!

### Alternatives

N/A

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to accomplish adding favorite folders to the sidebar | Should |

### Files Version

v1.5

### Windows Version

Windows 10 Pro 20H2 19042.1165

### Additional comment

N/A

**Comment by gave92** [comment]
You can right-click on a folder and choose "Pin To Favorites" ;)
