### ISSUE TITLE
Running really Slow

### ISSUE THREAD

**Issue by neosagg** [files-community/Files#5872]
### Description

Startup is buggy and slow

### Expected behavior

Wanted it to be as fluent as it looks, looking for some speed improvements in the app. Cheers

### Files Version

v.1.5

### Windows Version

Windows 10 21H1 19043.1110

**Comment by gave92** [comment]
Thanks for this report. Speed has been much improved in the preview version 💪

**Comment by yaira2** [comment]
We're excited to share that startup performance will be significantly improved in the upcoming release of version 3. You can download the preview version from our website https://files.community/download.
