### ISSUE TITLE
Incorrect Time Display in File Details

### ISSUE THREAD

**Issue by Archeol** [files-community/Files#5877]
### Description

Whenever a file contains video (not sure about music) in the hours mark, it does not display the hour just the minute and second. It still persists even when the file is multiple hours long, but I do not remember what happens if over 10 hours.

I actually saw this bug from long ago (since my last reported bug), not sure why I never brought it up, then forgot.

### Expected behavior

Display the video length properly.

### Files Version

v1.5

### Windows Version

Windows 10 Pro 21H1 19043.1165

### Relevant Assets

![image](https://user-images.githubusercontent.com/46249833/130311582-eebb4949-a7df-4ca8-9568-778575a67ad8.png)

**Comment by winston-de** [comment]
Thanks for the feedback, showing the hours of the duration has been implemented and will be included in the next release
![image](https://user-images.githubusercontent.com/59544401/130312440-393b7bef-be8a-4566-94b4-dc6d7eb124ec.png)
