### ISSUE TITLE
Files won't open empty folders in Column View

### ISSUE THREAD

**Issue by Takanu** [files-community/Files#5878]
### Description

If a folder is completely empty (including any hidden files or folders), Files will not open it's contents in Column View by creating another column, and the File Path Bar will not change from the previously selected folder.

### Steps To Reproduce

1) Create any folder in any application (File Explorer, Files) and leave it empty.
2) Open Files and display the hierarchy the folder is in with Column View.
3) Attempt to view it's contents by double-clicking.

### Expected behavior

The expected behaviour is that **the contents of the folder, even if empty will be displayed in another column in order for you to perform actions inside it.**  However this is not the case.

In the uploaded image you can see that even though the "Files Playground" folder is the currently active one, the File Path Bar has not changed to reflect that and the contents are not being displayed.

Even if something is added to the folder (either using Files or another app), you will need to use the Refresh action to be able to then view it's contents.

### Files Version

Version: 1.9.25.0

### Windows Version

Windows 11 Pro 21H2 22000.160

### Relevant Assets

![image](https://user-images.githubusercontent.com/9108903/130313209-2edc5a5a-c533-4418-ad54-0bcc4ae88a0f.png)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5914.
