### ISSUE TITLE
Changing the file path of one tab in Column View will replace the contents of any other tab using Column View

### ISSUE THREAD

**Issue by Takanu** [files-community/Files#5879]
### Description

This refers to the contents of the window, NOT the File Path Bar of the other tabs.

When one tab is changed that uses Column View, the displayed contents of all other tabs that use Column View becomes replaced with the File Path of the tab that just changed.  The File Path Bar for every other tab will still show the path they are supposed to be displaying.

### Steps To Reproduce

1) Open a tab in Column View and move to a distinct location in your file hierarchy.
2) Open a new tab in Column View and move to another distinct location in your file hierarchy.
3) Open the first tab you have in the window.  It's displayed contents will now show the hierarchy of the second tab even though the File Path has not changed.

### Expected behavior

The expected behaviour is that each tab displays the file path it is assigned, not the file path of another tab.

This bug occurs with any number of tabs, the only prerequisite is that they use Column View.

### Files Version

Version: 1.9.25.0 OS 

### Windows Version

Windows 11 Pro 21H2 10.0.22000.160

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5961.
