### ISSUE TITLE
Recent items shouldn't register elements when you have it disabled

### ISSUE THREAD

**Issue by BanCrash** [files-community/Files#5882]
### What's the Problem?

If you have disabled recent items, when you enable it back it should show an empty list

### Solution/Idea

When you disable recent items, it should automatically clear the list and not register new recent items until you enable it back.

### Alternatives

Adding a simple setting about disabling the items history, so if you have hidden recent items but you have disabled that setting, it will still work as it does now.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish clear the list of recent items when disabling it | Must |
| This proposal will allow developers to accomplish not register new recent items when it's disabled | Must |

### Files Version

1.9.25.0 

### Windows Version

Windows 10 21H1 10.0.19043.1165

**Comment by yaichenbaum** [comment]
@BanCrash any reason in particular for it to work this way?

**Comment by BanCrash** [comment]
> @BanCrash any reason in particular for it to work this way?

@yair100 Privacy reasons. I don't like to have some files that easy to access. It's true that having disabled will not show them, but I don't feel comfortable that they are that easy to known since sometimes friends come to my house. This is also the functioning of Windows Explorer, when you disabled that option if you enabled it back it will start from 0.

BTW, I thought about an alternative, adding a simple setting about disabling the items history, so if you have hidden recent items but you have disabled that setting, it will still work as it does now.

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by jiejasonliu** [comment]
@yair100 with #9291 indirectly contributing to this issue, I think the privacy part of it is resolved

@BanCrash left a comment addressing whether the actual widget should still be displayed if the setting is disabled (`Show recently sued files in Quick access`) in the native explorer
![image](https://user-images.githubusercontent.com/29434693/206983854-b540bc4a-e3a6-42ce-8a94-4a86bb3f55ea.png)


definitely possible to add that feature but the interaction between the recent files widget toggle and it being hidden if the setting is disabled needs to be ironed out (e.g. should we disable the toggle in Files and show a warning label?)

**Comment by yaira2** [comment]
I wouldn't disable the setting, probably best to add a banner or description to the widget for this scenario.
