### ISSUE TITLE
Contextmenu way to small for given window height and indication to scroll too subtle

### ISSUE THREAD

**Issue by crashmit** [files-community/Files#5884]
### Description

Hi there,

I just wanted to reach the extended context menu (shift-right click) and was confused why I only saw so few items.
![image](https://user-images.githubusercontent.com/58466626/130320922-66acb947-9d3c-4f50-9a4c-0b502d37bd87.png)
Also, I don't know if it was already there but I didn't notice the scrollbar at all. Hence I thought, there were no further items in the context menu. 

After checking if this was an edge case with a multiselection in dualpane, I noticed this is also prevalent in single pane single selection, altough the context menu is slightly taller in this case.

### Steps To Reproduce

1. Select any group of files or single file
2. Right-Click
3. Be confused (a bit)

### Expected behavior

I want the contextmenu to use all the vertical space it needs, if the window size allows for it (which is given in the screenshot in "Description"

### Files Version

Version: 1.9.25.0

### Windows Version

 OS Version: 10.0.22000.132

**Comment by yaichenbaum** [comment]
Merging with #6025.
