### ISSUE TITLE
Feature: Add shell items to widgets right click menu

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#5888]
### Description

Drives in the sidebar have the shell items listed in the context menu but none on the home page

### Steps To Reproduce

1. Right click a drive on the home page

### Requirements
- Right clicking a drive, folder or recent item on the homepage should display shell items

### Files Version

1.9.25

### Windows Version

10.0.19043.1151

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/9591561/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9591562/debug_fulltrust.log)

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by ferrariofilippo** [comment]
I think this should also be implemented for folders

**Comment by yaichenbaum** [comment]
Yes

**Comment by hecksmosis** [comment]
Would this involve a rewrite of DrivesWidget.xaml?

**Comment by hecksmosis** [comment]
The context menu there is implemented differently to how it is implemented in the sidebar

**Comment by yaira2** [comment]
It shouldn't but might require refactoring other parts of the code to reuse it.
