### ISSUE TITLE
Files in Windows 10 21H1 Has Black Item Text When Selected in Dark Mode

### ISSUE THREAD

**Issue by pc-v2** [files-community/Files#5890]
### Description

![image](https://user-images.githubusercontent.com/58063311/130353717-95da673c-079f-4eb5-8dab-bc19858baa8c.png)

### Steps To Reproduce

1. Set Windows color theme to dark
2. open Files
3. select several items

### Expected behavior

item text should be white in dark mode

### Files Version

1.9.25

### Windows Version

Windows 10 21H1

**Comment by gave92** [comment]
Fixed in #5876
