### ISSUE TITLE
Confirming a Rename Action by clicking outside the editing box randomly fails

### ISSUE THREAD

**Issue by Takanu** [files-community/Files#5895]
### Description

Clicking outside the editing box of an item when you're renaming it will randomly confirm or undo the changes made to the name.

### Steps To Reproduce

1) Rename any item in any view.
2) Make some changes to the name.
3) Right-click outside the editing box.

### Expected behavior

While I assume for convenience that clicking outside the box would confirm the change, this behavior should not change - clicking out of the editing box should always either confirm the edits OR undo them.

### Files Version

Version: 1.9.25.0

### Windows Version

Windows 11 Pro 21H2 22000.160

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5896.
