### ISSUE TITLE
Delay in Closing Open Themes Dialog/Tooltip 

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#5901]
### Description

While trying to access the themes folder via Settings > Appearances, I noticed that the dialog/tooltip for `Open themes folder` has delayed for around 2-3 seconds after clicking it.

### Steps To Reproduce

1. Go to Settings
2. Click on Appearances Tab and Surf to the Custom Themes Section
3. Click on the Info Button and a Tooltip/Dialog will Appear
4. Click on the `Open themes folder` button
5. See the error

### Expected behavior

No delay in closing modal/tooltip

### Files Version

v1.9.26.0

### Windows Version

Windows 10 21H1 19043.1165

### Relevant Assets

https://user-images.githubusercontent.com/69080584/130393559-66969ed3-58a0-4bff-8bf2-5e37b4bcdaba.mp4

**Comment by yaichenbaum** [comment]
This issue should be resolved with #6096.
