### ISSUE TITLE
Clicking Direction Button while Renaming File in Tiles View will Cause the Cursor Move to Another Files

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#5902]
### Description

Sometimes while renaming file's name, we will simply use direction button on keyboard (such as `->` and `<-` buttons) instead of using mouse to move the cursor direction. However renaming file in Tiles View will move the cursor to another files when the cursor is located at the end or beginning of a file's name.

### Steps To Reproduce

1. Rename a file or a folder in Tiles View
2. Click on the `->` or `<-` button till the end of the file and click it again
3. See the error

### Expected behavior

The cursor should always stay inside the textarea of a file's name.

### Files Version

v1.9.26.0

### Windows Version

Windows 10 21H1 19043.1165

### Relevant Assets

https://user-images.githubusercontent.com/69080584/130410787-c07fb557-ffd8-4c30-8ef3-499402cd8c66.mp4

**Comment by gave92** [comment]
Merging with #5824
