### ISSUE TITLE
Show Error Message when using invalid folder name

### ISSUE THREAD

**Issue by crashmit** [files-community/Files#5903]
### Description

I tried to name a folder after a chapter title of my thesis and copied the text out of word: "4.3.2.1	Workshop zur Exploration potenziell interessanter Informationen". After clicking create, the folder never appeared, no error message. Creating a folder with a simple name and renaming it doesn't work either.

### Steps To Reproduce

1. Go to a folder
2. Create a folder
3. Call it "4.3.2.1	Workshop zur Exploration potenziell interessanter Informationen"
4. Nothing happens

### Expected behavior

Error message

### Files Version

Version: 1.9.26.0 

### Windows Version

OS Version: 10.0.22000.160

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by sthivaios** [comment]
> Is this still an issue in the preview version? https://files.community/download/preview

I mean, I was able to create a folder called "4.3.2.1 Workshop zur Exploration potenziell interessanter Informationen". And when I tried to name it something like "asfas\';\'.g';';,gerg" it did say that I cannot use /('\ etc.
