### ISSUE TITLE
Dual panes don't change focus when selecting files or opening folders

### ISSUE THREAD

**Issue by JuanChiogna** [files-community/Files#5906]
### Description

When using dual panes (in icon view at least) clicking files or opening a folder on another pane does not give focus to said pane. This give rise to the frustrating problem of selecting a file, trying to perform an action on it (such as delete) and ending up deleting a file on the other pane. What's frustrating is that right now it's also a bit hard to see which pane is focused at any time, as the separation between them is quite small.

### Steps To Reproduce

1. Open a second pane.
2. Give focus to pane "A".
3. Click on a file or open a folder on pane "B" without clicking on empty space first.
4. Try performing an action (rename, delete, going up a folder).
5. Have that action performed on pane "A".

### Expected behavior

When using dual panes, clicking anywhere on a pane should give focus to said pane.

### Files Version

v1.9.26

### Windows Version

Windows 10 21H1 19043.1165

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5961.
