### ISSUE TITLE
Zip browsing not supported in column view

### ISSUE THREAD

**Issue by Svk1190** [files-community/Files#5908]
### Description

When I use the column view, nothing happens if I click on a Zip file. The contents of Zip file are not displayed in the next column, or in the parent column. 

### Steps To Reproduce

1. Go to any folder with a zip file
2. Click on column view
3. Double click on the zip file
4. Nothing happens

### Expected behavior

Ideally, the contents of the Zip file should be displayed in the next column. 

### Files Version

v1.9.26.0

### Windows Version

Windows 10 Pro 21H1 19043.1165

### Relevant Assets

![image](https://user-images.githubusercontent.com/12389625/130510227-5d29bfb0-8a4c-44bf-a0d6-976af1c5655f.png)

**Comment by gave92** [comment]
Cause by #5878

**Comment by Svk1190** [comment]
> Caused by #5878
Just for the record, the zip file in my example was not empty. So, the next column was expected to display several files within it.

**Comment by gave92** [comment]
Files thinks all archives are empty folders ;)

**Comment by Svk1190** [comment]
Oh, haha. Got it!
