### ISSUE TITLE
Highlight items that are currently occupied by an operation in the main view

### ISSUE THREAD

**Issue by Takanu** [files-community/Files#5909]
## Whats the Problem?
![image](https://user-images.githubusercontent.com/9108903/130450158-b777b7a2-aaa6-4e09-bab5-06138e81a546.png)

For operations that don't or cannot be handled instantly such as ZIP operations or the deletion of large folders or files, there is no indication as to which file or folder is actually being operated on.

In this image even with a few items, one of them is being unzipped and you can't tell which folder is the one being operated on.

* If its a folder being unzipped, its really important to tell the user that it's not actually complete in case they try to use or edit it, or perhaps even prevent them from accessing it until the files have been fully extracted.

* If a large folder is being deleted, it's not as big of a deal to mark it as occupied but still helpful to describe the state of the currently viewed directory.

## Solution/Idea
A basic solution would be to:

* Add a secondary item color for items that's slightly darker (or lighter in light mode) which is a common UX idea to describe something as inactive or temporarily unavailable.

* Add a loading wheel to the item to describe the items progress to make the operation process more transparent and specific, particularly useful if multiple items are being operated on at once.

The actual solution is open to debate so long as it satisfies the issue of identification.

### Alternatives

While an alternative would be to remove an entry in the UI immediately if deleted or only add an entry to the UI if it is fully unzipped, **this doesn't accurately reflect the state of the file system and would be misleading.**

This issue is about the opposite of obscuring the state of the file system, but to accurately describe important elements of a hierarchy as it is being viewed.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end-users to clearly understand the specific items of a directory undergoing an operation | Must |
| This proposal will allow end-users to clearly understand the current progress of each item in a directory undergoing an operation | Should |
| This proposal will prevent end-users from editing folders undergoing an operation to prevent unintended consequences | Could |

### Files Version

Version: 1.9.25.0

### Windows Version

Windows 11 Pro 21H2 22000.160

**Comment by yaira2** [comment]
@Takanu thank you for your feedback, we're still planning to do this but we're going to continue tracking it in #12699.
