### ISSUE TITLE
Allow collapsed Sidebar categories to be immediately switched between when one has been opened

### ISSUE THREAD

**Issue by Takanu** [files-community/Files#5910]
## What's the problem?
![image](https://user-images.githubusercontent.com/9108903/130513852-50ace892-a102-4246-aa72-a6593422bf23.png)

When you collapse the shortcut sidebar you view the category contents by clicking on them which brings out a dropdown-esque box, but despite the collapsed sidebar feeling tag-like and the dropdown not blocking the sidebar you **cant click on another sidebar category without the dropdown-esque box disappearing first**, which slows down browsing in case you clicked the wrong category.

(this is the nit-pickiest and least important improvement I have suggested, the only effect this has is slowing down my use of the app)

## Solution/Idea
Allow the sidebar categories to be clickable even when the dropdown-esque box for a category is open, making the current box disappear and another category box appear.

### Alternatives

The actual problem and solution is so precise and small that I don't have an alternative apart from doing nothing.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to quickly and efficiently switch between sidebar categories when collapsed | Should |

### Files Version

Version: 1.9.26.0

### Windows Version

Windows 11 Pro 21H2 22000.160

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
This is the intended behavior, I understand this is your workflow but it's not a common use case. As a workaround, you can try expanding the sidebar and resize it to the smallest size (we're going to be reducing the minimum size even further in a future update).
