### ISSUE TITLE
Bug: Multiselect state is not maintained when a drag and drop event occurs

### ISSUE THREAD

**Issue by Takanu** [files-community/Files#5911]
### Description

https://user-images.githubusercontent.com/9108903/130519198-d6c96a6d-ed89-43ad-8465-4078e631dc95.mp4

When items are selected using Multiselect and a drag and drop action is initiated, two issues occur:

1) **The state of what items have been selected using Multiselect is NOT maintained** when the drag and drop event is cancelled or finished   In particular with cancellation this can be a problem if a complex selection was created and the user made an initially incorrect drag and drop operation.

2) The state of the mouse being clicked when over the tickboxes of items causes them to activate and in some cases remain if the drag and drop action is cancelled over a tickbox, creating a multiselect state that was not in the users intention.

### Steps To Reproduce

1) Enter multiselect mode in any view.
2) Select a number of items using multiselect.
3) Attempt a drag and drop action.

### Expected behavior

Two things should be occurring here:

1) The Multiselect mode should be maintained and only cancelled when the user explicitly wishes to clear it, to allow the user time and space to perform the actions they need to perform.

2) The Multiselect items should only change when the user explicitly does so, not as an incidental reaction to another action (such as drag and drop).

### Files Version

Version: 1.9.26.0

### Windows Version

Windows 11 Pro 21H2 22000.160

**Comment by yaira2** [comment]
This is the expected behavior, hovering over a folder will try and select it so that you can drop the items into the folder. In this case, the folder wasn't a valid target since it was one of the selected items.
