### ISSUE TITLE
Attempting to drag and drop Multiselect items in Column View only includes items selected in that column

### ISSUE THREAD

**Issue by Takanu** [files-community/Files#5912]
### Description

https://user-images.githubusercontent.com/9108903/130520425-208e2ad0-b48d-4663-869c-932575dadd41.mp4

_Note - This issue is tangentially related to issue #5880 due to the Column View's selection design not being particularly clear._

When items are marked during Multiselect across multiple columns, only selected items in the column the drag and drop action is initiated in are included.

### Steps To Reproduce

1) Enter Column View
2) Ensure multiple folders are open in the hierarchy
3) Enter Multiselect mode
4) Select multiple items from different columns
5) Attempt a drag and drop operation in any column

### Expected behavior

The expected behavior changes depending on the intended selection design (#5880).

The expected behavior should EITHER BE:

A - All selected items should have been included in the drag and drop operation irrespective of their column.

B - Only the last or active column should have tickboxes displayed for the Multiselect operation to illustrate that only the items in one column are valid during Multiselect.

(though if B I will file a enhancement proposal afterwards as it adds needless complications, ehehe 😇)

### Files Version

Version: 1.9.26.0

### Windows Version

Windows 11 Pro 21H2 22000.160

**Comment by gave92** [comment]
When selection changed on some column we used to close all subsequent columns. Since now columns stay open instead things has become more confused..

**Comment by Takanu** [comment]
> 
> 
> In the past when selection changed on some column we used to close all subsequent columns. Since now columns stay open instead things have become more confused..

I assumed as much, hence my comments.  Hopefully this will all get clarified soon ^-^

**Comment by yaira2** [comment]
@Takanu is this still an issue?
