### ISSUE TITLE
Drag and dropping a tab without moving it from it's original position creates a new window instance

### ISSUE THREAD

**Issue by Takanu** [files-community/Files#5913]
### Description

https://user-images.githubusercontent.com/9108903/130522933-d9d7a8c3-c739-4af4-93b0-b18a8e1f166e.mp4

When attempting a drag and drop operation on a window tab, if it is barely moved or only moved to within it's original position on the tab bar, it is removed from the tab bar and spawns a new window.

### Steps To Reproduce

1) Create more than one tab (can be more than two).
2) Attempt to drag and drop the tab without moving it out of it's rough original position.

### Expected behavior

Unless deliberately moved out of position, the tab should have remained in it's position when the mouse click is released and not spawned a new window.

### Files Version

Version: 1.9.26.0

### Windows Version

Windows 11 Pro 21H2 22000.160

**Comment by Josh-65** [comment]
Merging with #8976
This seem like it's cause by the title bar having a small area to drag the tab into for window merging.
