### ISSUE TITLE
Unresponsive Drive Section

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#5917]
### Description

After updating it to the latest build version, I noticed that the drive section doesn't have a full width.
![Unresponsive Drive Section](https://user-images.githubusercontent.com/69080584/130544997-bfecfb80-8192-4be3-8164-8b589394508c.jpg)

### Steps To Reproduce

1. Open Files
2. See the Drives Section
3. See the error

### Expected behavior

The drives section should have a 100% full width

### Files Version

v1.9.27.0

### Windows Version

Windows 10 21H1 19043.1165

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7035952/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7035953/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
@stanleyowen This is the intentional design. Stretching one drive across a wide screen monitor would look a little odd 😂

**Comment by stanleyowen** [comment]
Okay got it 😅
