### ISSUE TITLE
Files windows should refresh when enabling view of hidden files

### ISSUE THREAD

**Issue by FMalerba** [files-community/Files#5921]
### Solution/Idea

When enabling the view of hidden files and folders, they don't appear immediately. That is because one needs to refresh the current view (either by pressing the associated button or by switching to a new folder). It seems intuitive to me that upon clicking the slider to view the hidden files and folder (or to stop viewing them), the explorer should automatically refresh without further user input.

I am not sure whether a this auto-refresh principle would apply also to other changes in view that don't already get immediately refreshed.

### Alternatives

None.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Versione 1.9.27.0 OS Version: 10.0.22000.160

### Windows Version

Windows 11 Home 21H2 - 22000.160

**Comment by gave92** [comment]
Merging with #2857
