### ISSUE TITLE
Increase the clickable area of column dividers in Details View

### ISSUE THREAD

**Issue by Takanu** [files-community/Files#5923]
## Whats the Problem?
https://user-images.githubusercontent.com/9108903/130639116-02e76a25-f4d7-41ed-92cc-93d551660bc9.mp4

The clickable area of the dividers between list column headers in Details View are about 2-3px wide, making them extremely difficult to activate and click on without careful precision.

## Solution/Idea
Increase the area that the resize tool becomes available in, so it's easier to resize columns.

### Alternatives

The problem is too narrow in scope to feasibly contain any alternatives.  

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to quickly and efficiently resize columns in Details View | Must |

### Files Version

Version: 1.9.27.0

### Windows Version

Windows 11 Pro 21H2 22000.160

**Comment by mdtauk** [comment]
16-24 px should be a minimum hit target for these dividers and separators you can interact with.

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
