### ISSUE TITLE
During a Rename operation, using Ctrl+Shift+Left/Right to select text regions instead cancels the operation.

### ISSUE THREAD

**Issue by Takanu** [files-community/Files#5924]
### Description

https://user-images.githubusercontent.com/9108903/130641120-7c796a53-a04e-425e-a8a7-ef5799f0b7cc.mp4

When editing sections of long names Ctrl+Shift+Left and Ctrl+Shift+Right is a default behaviour where you can select a text region instead of the next character in order to speed up the selection process.  

Files currently doesn't acknowledge this key combination and will instead cancel the Rename operation if they are used.

### Steps To Reproduce

1) Enter a rename operation in any view.
2) Use Ctrl+Shift+Left or Ctrl+Shift+Right

### Expected behavior

Instead of cancelling the rename operation, the next or previous text region is selected.

### Files Version

Version: 1.9.27.0

### Windows Version

Windows 11 Pro 21H2 22000.160

**Comment by gave92** [comment]
Merging with #5824
