### ISSUE TITLE
Searching when in "search" folder is possible

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#5925]
### Description

Searching when in "search" folder is possible but does not actually show any results.

### Steps To Reproduce

1. Start a search
2. Hit enter to open up a "folder" with all search results
3. Enter something in the search box and hit enter again

### Expected behavior

Either disable the search box when the user is already viewing the results of a previous search **or** actually make it so that starting another search will filter the results of the previous search.

### Files Version

Version: 1.9.27.0

### Windows Version

 OS Version: 10.0.19043.1165

### Relevant Assets

https://user-images.githubusercontent.com/17484252/130648552-7ef2c311-33a0-4c6a-9a52-0c203ee9728d.mp4

**Comment by gave92** [comment]
Expected behavior is that searching from the search page will simply run the new search in the original folder you were in. Do you experience something different? Isn't it the issue that no results appear for you unless you click "Show unindexed items" at the bottom?

**Comment by R3voA3** [comment]
Even if I click on Show unindexed items in the search page it will not filter the found items.

**Comment by gave92** [comment]
It's not supposed to filter the found items, it's supposed to do a new search in the same folder. I don't see anything wrong with that, explorer does the same, but it's an interesting feature we can consider.
