### ISSUE TITLE
Status column has the wrong default size

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#5926]
### Description

The status column's default width is very small.

### Steps To Reproduce

1. Open a cloud drive
2. Change to details view

### Expected behavior

Min. width should at least be wide enough to be able to show the full label.

### Files Version

Version: 1.9.27.0

### Windows Version

 OS Version: 10.0.19043.1165

### Relevant Assets

![image](https://user-images.githubusercontent.com/17484252/130649369-72a9dcaa-9c8f-4526-a278-a21fa66ac38e.png)

**Comment by gave92** [comment]
I'm almost tempted to get rid of the label instead..

**Comment by R3voA3** [comment]
> It's done on purpose not to take unnecessary screen space. I'm almost tempted to get rid of the label instead..

Good idea. Same is true for the "Tag" label that is currently in development.

**Comment by gave92** [comment]
The tag label makes sense since that column shows the tag name which can be arbitrarily long. You can hide the tag name column and still see the tag colored badge if you wish.

@yair100 what do you think of removing the "Status" label on the cloud sync status column?

**Comment by yaichenbaum** [comment]
I believe it makes sense to keep it for consistency and besides, it really doesn't take up that much space.
