### ISSUE TITLE
When a column in Details View is automatically expanded the scroll column becomes hidden

### ISSUE THREAD

**Issue by Takanu** [files-community/Files#5928]
### Description

https://user-images.githubusercontent.com/9108903/130665528-9ab04613-3ecb-4f96-a980-6f2d770946d9.mp4

When the expanded contents of all columns in Details View become larger than the window, the scroll bar is moved off the visible window space until the column widths or window size is interacted with again.

### Steps To Reproduce

1) Make the window small-ish
2) Double-click on a boundary between two columns in Details View

### Expected behavior

The scroll bar should always be visible no matter the circumstances.

### Files Version

Version: 1.9.27.0

### Windows Version

Windows 11 Pro 21H2 22000.160

**Comment by gave92** [comment]
Yeah that's known.. @winston-de why did we separate thw horizontal from the vertical scrollviewer in Details View? To implement the sticky header bahaviour?

**Comment by winston-de** [comment]
Yes, this was to get the sticky header to work reliably (the sticky header behavior from the toolkit would break a lot) while still having horizontal scrolling possible.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5914.
