### ISSUE TITLE
Add thumbnails for vector graphics files & center their preview in preview pane

### ISSUE THREAD

**Issue by m1karii** [files-community/Files#5932]
### Solution/Idea

1. Add thumbnails for vector graphics files
2. (Not sure whether to open separate issue for this, but) vector graphics previews in preview pane are often (if not always) uncentered and scaled

![image](https://user-images.githubusercontent.com/82673417/130817430-87f60c11-78d9-487a-af7f-ed6c915168ed.png)

### Files Version

v1.9.27

### Windows Version

Windows 11 Insider Preview Build 22000.120

**Comment by gave92** [comment]
Does Explorer show thumbnails for vector graphics?

**Comment by winston-de** [comment]
I think this depends on your default browser (which provides the thumbnails). For me (default is Edge), thumbnails are shown.

![image](https://user-images.githubusercontent.com/59544401/130830294-27060049-b1e3-430e-913c-6256b41ca06c.png)

**Comment by TizianoMad** [comment]
Hi There !
I guess you are maybe looking for something like this : [SVG See 1.1.0](https://github.com/tibold/svg-explorer-extension/releases)
It seems to work great on both Microsoft and Yair File Explorer using Chrome.
Why not a little collab with creator [Tibold](https://github.com/tibold) and suggest it as an optional extension when using browser which doesn't display SVGs.
I had a similar issue with PDF thumbnails on Chrome, and had to [tweak registry a bit to make them look like with explorer](https://www.winhelponline.com/blog/set-custom-icon-pdf-files-firefox-default-pdf-viewer/).
Hope it helped a bit.

**Comment by m1karii** [comment]
@TizianoMad Thanks!
It works for me both in Explorer and Files. I use [ImageGlass](https://github.com/d2phap/ImageGlass) as my default image viewer instead of Windows Photos and SVG See works with it. ImageGlass can pretty much display any image filetype (including .svg and .psd for e.g.); thats why i have it as default for .svg files instead of web browser BTW (i recommend it).

**Comment by yaichenbaum** [comment]
Merging with #8376
