### ISSUE TITLE
Reminder from the developer of RX-Explorer

### ISSUE THREAD

**Issue by zhuxb711** [files-community/Files#5942]
### Description

Hi Files team,

Very pleased to hear that your team will release a new version of Files in 4th October.
But I have to remind you that WinUI 2.6.X is current unavailable in Microsoft Store for those app use FullTrustProcess.

I found an issue that if the package submit to MSStore is "Windows Application Packaging Project" with FullTrustProcess (Both RX-Explorer and Files are this type of application). Once you submit the package. Microsoft Store will report "Attention needed" after a few minutes. Error code is 1201.

There is no error with the compilation, so this problem is very strange

So I want kindly remind your team in advance because RX-Explorer have to roll back to WinUI 2.5 and give up all the effort on WinUI 2.6. Make sure that your team check the package (Try create a package and submit to MSStore and wait for a few minutes etc.) in advance. And hope that issue would not block your release day.

For more details, please check the issue in [Here](https://github.com/microsoft/microsoft-ui-xaml/issues/5768). Hope Microsoft could fix this issue ASAP. And if your team found something helpful, please let me know and report to Microsoft. Thanks.

Best regards,
Developer of RX-Explorer
Ruofan

### Expected behavior

None

### Files Version

None

### Windows Version

None

**Comment by zhuxb711** [comment]
> > > @zhuxb711 thank you for reaching out, the current work around we're using is to drop support for ARM64. We'd like to add it back, but until the submission issue is fixed, this seems like the only option.
> 
> > 
> 
> > RX-Explorer only support X64 & ARM. And the issue still exist.
> 
> 
> 
> What happens if you submit a update without ARM?

Since I reverted all the changes. I will restore and submit X64-only package later

**Comment by zhuxb711** [comment]
@yair100 I submitted a package which is X64 only. It failed with same error code 1201.

**Comment by yair100** [comment]
> @yair100 I submitted a package which is X64 only. It failed with same error code 1201.

I'll be submitting v2 soon and I'll let you know what happens.

**Comment by zhuxb711** [comment]
Close this issue since this issue is not exists in Files
