### ISSUE TITLE
Flickering on the disk space usage bars

### ISSUE THREAD

**Issue by Void48** [files-community/Files#5943]
### Description

![fug2koiIuW](https://user-images.githubusercontent.com/85196642/131150360-876b0848-def4-44fa-a385-6fa02911b3c9.gif)

### Steps To Reproduce

Click on any section on the sidebar and then go back to the **Home** section to see the disk space usage bars' flickering

### Expected behavior

It shouldn't flicker

### Files Version

v1.9.27

### Windows Version

Windows 11 Pro Version	21H2 OS build 22000.160 Experience Windows Feature Experience Pack 1000.22000.160.0

**Comment by yaichenbaum** [comment]
This issue appears to be resolved in `main`.
