### ISSUE TITLE
Sorting tags sorts them to the bottom

### ISSUE THREAD

**Issue by mangoepic** [files-community/Files#5944]
### Description

Items with tag get sorted to the bottom instead of to the top

If you change the direction all folders get sorted Z-A

### Steps To Reproduce

1. Tag an item
2. Sort by tag
3. Items with tag get sorted to the bottom

### Expected behavior

Items with tag get sorted to the top

### Files Version

Version: 1.9.27.0 OS Version: 10.0.19043.1165

### Windows Version

Windows 10

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5961.
