### ISSUE TITLE
Allow MEGA to show up in cloud drives

### ISSUE THREAD

**Issue by Weshnaw** [files-community/Files#5946]
### What's the Problem?

I use mega sync and it does not show up in the cloud drives

### Solution/Idea

I would like a way to either add folders manually to cloud drives, or to add whatever mechanism exists for OneDrive to include MEGA sync.

From Files:
![image](https://user-images.githubusercontent.com/3748858/131185139-09772dbe-55d2-44a6-920e-8eb72997ca6e.png)
From Windows Explorer:
![image](https://user-images.githubusercontent.com/3748858/131185169-faea6db8-0482-44da-abe3-28f0002de509.png)

### Alternatives

My alternative is to just favorite MEGA, this works fine, though isn't an exact alternative.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow MEGA sync to show up in Cloud Drives | Must |
| This proposal will allow end users to define what folders show up in Cloud Drives | Could |

### Files Version

v1.5

### Windows Version

Windows 10 10.0.19043 Build 19043

### Additional comment

I apologize if there is already an existing solution, I could not find it.

**Comment by gave92** [comment]
It used to show up in there till MEGA updated their app. The method we used does not work anymore :(

**Comment by yaichenbaum** [comment]
This issue should be resolved with #6076.
