### ISSUE TITLE
Column View renders extra columns unrelated to the viewed hierarchy when multiple tabs use Column View

### ISSUE THREAD

**Issue by Takanu** [files-community/Files#5947]
### Description

https://user-images.githubusercontent.com/9108903/131185725-4c2d9326-275d-456c-848c-1b90e10a0e05.mp4

When using Column View in more than one tab, changing the hierarchy in one tab will cause columns from it to be rendered in the other tabs on top of the hierarchy that they're viewing,

### Steps To Reproduce

1) Use Column View in one tab.
2) Open Column View in another tab and browse some files.
3) Select the original tab.

### Expected behavior

That each tab maintains it's own hierarchy of open folders at all times, and that the hierarchy is accurate to the tab's Path Bar.

### Files Version

Version: 1.9.28.0

### Windows Version

Windows 11 Pro 21H2 22000.160

**Comment by gave92** [comment]
Merging with #5879
