### ISSUE TITLE
Would like to be able to rearrange favorites by dragging them around

### ISSUE THREAD

**Issue by SikSlayer** [files-community/Files#5951]
### Solution/Idea

In File Explorer, you can drag around your pinned Quick Access locations to arrange them however you want. In Files, I'd like to be able to do the same for Favorites.

### Alternatives

The only other solution is to wipe all of them and add in your own favorites in the proper order all at one time, and hope you don't screw up too deep in to 'fix' it. And later on, you may want to reorder them for whatever reason you choose.

Pretty much have feature parity to File Explorer.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 1.9.28.0 OS Version: 10.0.19043.1165

### Windows Version

Windows 10 Pro Version	21H1  OS build 19043.1165 Experience Windows Feature Experience Pack 120.2212.3530.0

**Comment by gave92** [comment]
Merging with #1069

**Comment by gave92** [comment]
Until it's implemented , the not-so-handy workaround is to manually edit this file:
"%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalCache\PinnedItems.json"
