### ISSUE TITLE
Frezing after being minimised for a long time

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5953]
### Description

When I minimises files for about 10 min it will end up freezing when going back to it. Doesn't crash just become non intractable except for the windows control (minimise, full screen, close)

### Expected behavior

Shouldn't freeze up

### Files Version

1.9.28

### Windows Version

10.0.19043.1165

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7071527/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7071528/debug_fulltrust.log)

**Comment by gave92** [comment]
Merging with #3272
