### ISSUE TITLE
Can't create files on protected folders

### ISSUE THREAD

**Issue by b4s714n** [files-community/Files#5956]
### Description

Just wanted to note i am currently being unable to directly create files or folders on windows protected folders i.e (C:/, C:/Windows)

Is there any way to run 'Files' app with UAC prompt atm?

### Steps To Reproduce

1. Open Files app
2. Head to any windows folder i.e (C:/Windows)
3. Try to create any folder or file there (Right click, New)
4. Give it a name and press enter
5. The folder/file won't be created

### Expected behavior

Heading to the desired system protected folder and creating a new file expecting UAC prompt to pop-up, giving it a name and successfully create it

### Files Version

v1.5.0.0

### Windows Version

Windows 10 Education 21H1 19043.1165

**Comment by gave92** [comment]
Crating files as admin is not implemented. Deleting, renaming, copy/move instead should work.

**Comment by b4s714n** [comment]
Oh, ok, looking forward to have this possibility on next updates and finally start using FilesForWindows as my everyday File Browser
