### ISSUE TITLE
Crash when try to autofit columns with Group By Date enabled

### ISSUE THREAD

**Issue by alefranzoni** [files-community/Files#5957]
### Description

Files app crash when you have enabled "group by date" and try to autofit any column by doing double-click on column header divider. This problem doesn't happen when "group by" is setted to none.

### Steps To Reproduce

1. Go to group by and set to Date created or modified
2. Try to fit any column by doing double-click on header divider

### Expected behavior

Fit the columns correctly

### Files Version

1.9.28.0

### Windows Version

Windows 10.0.19043.1165 (21H1)

### Relevant Assets

[debug_fulltrust.log](https://github.com/files-community/Files/files/7071965/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7071966/debug.log)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5961.
