### ISSUE TITLE
Crash when pressing on toggle the preview pane

### ISSUE THREAD

**Issue by amr-sakr** [files-community/Files#5960]
### Description

Pressing on toggle the preview pane inside folder will work but when pressing on it again it will crash the app

### Expected behavior

 toggle the preview pane 

### Files Version

Version: 1.9.28.0 OS Version: 10.0.22000.168

### Windows Version

Windows 11 Pro Version	21H2 ,OS build 22000.168

**Comment by gave92** [comment]
Merging with #5945
