### ISSUE TITLE
Sort by from toolbar always shows sorted by name after restart

### ISSUE THREAD

**Issue by Darhagonable** [files-community/Files#5966]
### Description

The sort by menu within the sort menu in the toolbar is always showing sorted by name as selected after restart.
The sort by menu within the context menu shows the correct selected sort by option though.

### Expected behavior

Sort by menu in toolbar to reflect the actually selected sort by option.

### Files Version

Version: 1.9.30.0

### Windows Version

Windows 10 Home 19043.1165

**Comment by yaichenbaum** [comment]
This issue should be resolved with #6271.
