### ISSUE TITLE
Open In Terminal context menu item missing an icon

### ISSUE THREAD

**Issue by KibSquib48** [files-community/Files#5968]
### Description

The icon for the context menu item to open a folder in the terminal is missing an icon, and shows up as an empty square instead.

### Expected behavior

It should show a proper icon, instead of a blank square.

### Files Version

Version: 1.9.30.0

### Windows Version

Windows 11 22000.168 (Beta Channel)

### Relevant Assets

![image](https://user-images.githubusercontent.com/33189136/131268598-4f2e1a68-56f3-4ddd-88a4-f3bd2f7cacae.png)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #6000.
