### ISSUE TITLE
Make the check box

### ISSUE THREAD

**Issue by Punrawee** [files-community/Files#5971]
### What's the Problem?

Am have 2 device that use this software my custom pc and Microsoft surface go 2 the problem I don't mouse or keyboard so I can't select multiple the file or folder

### Solution/Idea

Add the small check box or able to drag finger like drag mouse to select multiple file or folder

### Alternatives

![image](https://user-images.githubusercontent.com/66133828/131281646-5954fabc-261a-42e6-89c2-b6c1a225743b.png)

![image](https://user-images.githubusercontent.com/66133828/131281720-7cb8b740-badf-4674-aa1c-152a3a960489.png)

### Priorities

Should - Kinda important because sometime I need to select multiple file or floder

### Files Version

1.5.0.0

### Windows Version

Windows 11 build 22000.168

**Comment by gave92** [comment]
Thanks for the feedback. This has been implemented in the preview version of Files.
