### ISSUE TITLE
Titlebar drag area is too small when settings overlay is opened

### ISSUE THREAD

**Issue by andyvol** [files-community/Files#5975]
### Description

You can't drag anywhere in blue zone
![Снимок экрана 2021-08-30 105952](https://user-images.githubusercontent.com/86380645/131308868-23da269e-3dbe-4a00-b301-4209307bdf2c.png)

### Steps To Reproduce

1. Open settings.
2. Try to drag the window from anywhere except near top right corner.

### Expected behavior

Draggable region should either stay the same as with settings flyout closed or expand to the whole top of the window, ignoring tab area.

### Files Version

1.9.30

### Windows Version

Windows 10 21H1 19043.1165

**Comment by yaichenbaum** [comment]
This is the expected system behavior and Files doesn't really have control over it, I'd recommend opening an issue on the WinUI repo to start a discussion there. https://github.com/microsoft/microsoft-ui-xaml
