### ISSUE TITLE
Large amount of files will crash Files

### ISSUE THREAD

**Issue by Bluelighto** [files-community/Files#5978]
### Description

When you do something with large amount of files, it'll crash

### Steps To Reproduce

``Extraction
1. Extract a zip file with a lot of files
2. Crashed.
Copy and paste
1. Copy and paste a lot of files
2. When you get to 780+ files, it will crash.
Viewing
1. View the files
2. Soon, it'll crash

### Expected behavior

It should not crash

### Files Version

v1.9.30

### Windows Version

Windows 10 20H2 19042.1165

### Relevant Assets

![image](https://user-images.githubusercontent.com/63112005/131347826-8c9720bf-aa4b-4cdd-8d65-435edad66ea2.png)

**Comment by gave92** [comment]
Could you upload the two log files? Thanks!

**Comment by buiquangbao** [comment]
Nice UI but crashes every time.
These are 2 files I found in the log location
[debug_fulltrust.txt](https://github.com/files-community/Files/files/7087608/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/7087609/debug.txt)

**Comment by hez2010** [comment]
We didn't observe any crash records in log files you provided, can you try again with the latest version of Files?

**Comment by yaichenbaum** [comment]
@buiquangbao when you get a chance, can you check if this is still an issue in the latest preview build?
