### ISSUE TITLE
Is it possible to switch default file explorer with Files?

### ISSUE THREAD

**Issue by Spontini** [files-community/Files#5983]
### Solution/Idea

Is it possible to switch default file explorer with Files?

### Alternatives

Is it possible to switch default file explorer with Files?

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

v1.5

### Windows Version

Windows11

**Comment by gave92** [comment]
See here: https://files-community.github.io/docs/#/articles/replace-file-explorer.
