### ISSUE TITLE
Feature: Auto restore tabs if the app crashes

### ISSUE THREAD

**Issue by BanCrash** [files-community/Files#5993]
### What's the Problem?

With #5985, it will only remember the tabs of the last opened window, even if you have more than one opened.

### Requirements
Auto restore tabs on first launch after the app crashes

### Files Version

1.9.32.0 / #5985

### Windows Version

Windows 10 21H1 10.0.19043.1165

**Comment by Saul-JedHL** [comment]
Love this, there def needs to be improvements in state handling

**Comment by yaichenbaum** [comment]
@BanCrash do you want to implement this?

**Comment by BanCrash** [comment]
> @BanCrash do you want to implement this?

I look at this at the past and found it beyond my knowledge, but I can give it another try.

**Comment by yaichenbaum** [comment]
I think we already have some exception handling that logs errors so we should be able to save the current tab session and auto restart the app (take a look at the restart prompt on the preferences page).

**Comment by yaira2** [comment]
@BanCrash thank you for your feedback, this has been implemented and will be included in one of the next feature releases.
