### ISSUE TITLE
Layout Preference

### ISSUE THREAD

**Issue by WaChiNx** [files-community/Files#6004]
### Solution/Idea

Hey, i love ur app, its beutifully minimal. I wouild like to suggest a new feature that'd allow u to have a prefence in the "Layout Mode". Every time that i create a new folder, the layout is not the one i like, so it would be an amazing feature having a favorite layout for all the folders.

Thanks!

### Alternatives

-

### Priorities

-

### Files Version

1.5.0.0

### Windows Version

Windows 10

**Comment by gave92** [comment]
Thanks for the suggestion. Merging with #5564.

You can try the following:
- turning off "enable individual preferences for folders" option in Files settings
- setting your desired layout mode for any directory
- turning back on "enable individual preferences for folders"
