### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by xumepoc** [files-community/Files#6006]
### What's the Problem?

The current released version in MS Store 1.5 is quite outdated

### Solution/Idea

Are we going to have a new release soon for the MS Store. I am already running the latest releases on my personal PCs, complied by me, but on my Office PC as it is a corporate machine I can't compile anything, so I am left with the latest official release 1.5., which is....let say a bit buggy. 

### Alternatives

None :) 

### Priorities

Release a new version for MS Store.

### Files Version

v.1.5 

### Windows Version

Windows 10

**Comment by gave92** [comment]
Files v2 is coming to the Store begonkingof October.

**Comment by xumepoc** [comment]
Perfect, thanks :)
