### ISSUE TITLE
Lag When Selecting Large Amount Of Files

### ISSUE THREAD

**Issue by P13rlU** [files-community/Files#6008]
### Description

When selecting a large amount of files, the whole program lags like hell (does not happen with ctrl+a)

https://user-images.githubusercontent.com/67976483/131712453-fdcd5e2e-4306-4493-aa13-d732ff00f735.mp4

### Steps To Reproduce

1. Open a large amount of files
2. Drag the mouse for selection
3. here you go!

### Expected behavior

Not to be lagging like that

### Files Version

v2.0 

### Windows Version

Windows 11 22000.168

**Comment by gave92** [comment]
Thanks for the report. Could you check if it's an issue also in Details view?

**Comment by P13rlU** [comment]
> Thanks for the report. Could you check if it's an issue also in Details view?

Yes, a tiny bit less, but yes, thers is, only when are a lot of files as shown in the current page.
also i want to specify that in stock explorer this does not happen (i'm attaching a video for example)


https://user-images.githubusercontent.com/67976483/131725438-fa8e1e00-cf20-40e7-a2db-348b76459134.mp4

**Comment by yaichenbaum** [comment]
This issue should be resolved in v2.1.13.
