### ISSUE TITLE
Get Status column on all items

### ISSUE THREAD

**Issue by brucebinder** [files-community/Files#6009]
### What's the Problem?

Not seeing status column on some OneDrive folders/files

### Solution/Idea

The Status field (which shows the cloud status of a folder or file) does not apprea on many of the folders/files that are in the cloud.

How toi get cloud Status to show everywhere??

### Alternatives

None

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |
Should

### Files Version

Version: 2.0.0.0

### Windows Version

10.0.19043.1200

**Comment by gave92** [comment]
Could you show some screenshots of Files vs Windows Explorer showing the issue?
