### ISSUE TITLE
EXCELENTE La Versión 2.0 de FILES

### ISSUE THREAD

**Issue by Sebastia181** [files-community/Files#6010]
Os Felicito por la labor que habéis realizado en la versión 2.0 de FILES, es EXCELENTE por lo que ido viendo, esto no excluye que se pueda ir mejorando y puliendo
Muchas gracias por ofrecernos una APP de este nivel 
Un saludo cordial 
Sebastià Tost

**Comment by BanCrash** [comment]
Hello, thanks for your feedback. In the future please use english since only a few speak spanish here. Also if you can edit your post to translate it to english so the team could understand it would be good ;)

**Comment by Sebastia181** [comment]
I congratulate you for the work you have done in version 2.0 of FILES, it is EXCELLENT for what I have been seeing, this does not exclude that it can be improved and polished
Thank you very much for offering us an APP of this level
Best regards
Sebastià Tost

**Comment by BanCrash** [comment]
Thanks you so much for translating it, this will make the team able to read it and to appreciate your feedback. And again thanks for sharing your thoughts 😃
