### ISSUE TITLE
Reorganize favorite sidebar

### ISSUE THREAD

**Issue by guilhermebera** [files-community/Files#6011]
### What's the Problem?

Pinned items on favorite sidebar can't be moved to sort it differently.

### Solution/Idea

Be able to drag the pinned items  and drop for reorder them.

### Alternatives

Be able to drag the pinned items  and drop for reorder them.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

v1.5

### Windows Version

Windows 10 10.0.18362

**Comment by gave92** [comment]
Implemented in Files v2!
