### ISSUE TITLE
Allow Users to Scroll Horizontally when `y-overflow` is Present and No `x-overflow`

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#6013]
### Solution/Idea

It will be awesome to allow users scroll horizontally using mouse when the `y-overflow` is present when there aren't any `x-overflow`, like how the File Explorer implements it.

### Alternatives

https://user-images.githubusercontent.com/69080584/131822334-4b4849dc-ccdd-4caa-80a5-8bfa7d410d38.mp4

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Allow Users to Scroll Horizontally when `y-overflow` is Present and No `x-overflow` | Could |

### Files Version

v2.0.0.0

### Windows Version

Windows 10 21H1 19043.1202

**Comment by yaichenbaum** [comment]
This is a behavior in File Explorer that I find to be bad UX. I prefer for the scroll behavior to be consistent as I often scroll down out of habit.

**Comment by ferrariofilippo** [comment]
I think this should be merged with #10006
