### ISSUE TITLE
Feature Request: Add grouping just like on File Explorer

### ISSUE THREAD

**Issue by ArchXen** [files-community/Files#6015]
### What's the Problem?

Feature Request: Add grouping just like on File Explorer

### Solution/Idea

Feature request to add grouping of files and folders like what the File Explorer already with Group By menu. This feature gives user to visually separate the files based on selected filters, like file type, name, date, etc.

For me I find this feature especially useful when using File Explorer. Without this, any other file manager that does not have it makes it feel less efficient to use.

I really hope that Files will have this feature which is great.

### Alternatives

For now there is no alternative way for this feature. I can simply sort files by not group, so visually when browsing files, it is just flat and no seperation.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

v1.5.2.0

### Windows Version

Windows 11 21H2

**Comment by gave92** [comment]
This has been implemented in Files V2 💪 (now in preview)
