### ISSUE TITLE
Poor Perfomance

### ISSUE THREAD

**Issue by BattiScopa** [files-community/Files#6017]
### Description

When opening Files 2.0, I encounter Lag when it loads the Home Page, and when minimazing and maximizing the Window.

### Expected behavior

Lag

### Files Version

v2.0

### Windows Version

Windows 10 Pro Version	21H1 19043.1165

**Comment by yaichenbaum** [comment]
Thank you for your feedback, we're working on improving performance. You can find the latest improvements in the preview version https://files.community/download/preview.
