### ISSUE TITLE
dynamic recycle bin icon

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#6020]
### What's the Problem?

When the rycle bin has items the icons says as the empty recycle bin.

### Solution/Idea

Make it act like file explorer. Empty icon when there's no items and filled icon when there is.

### Alternatives

None

### Files Version

2.0.0.0

### Windows Version

10,0.19043.1165

**Comment by gave92** [comment]
You're referring to the recycle bin on the Files sidebar, correct?

**Comment by josh-65** [comment]
yes

**Comment by gave92** [comment]
Thanks, merging this with #1089
