### ISSUE TITLE
Problems with viewing files in online folders (Onedrive or Google drive for PC)

### ISSUE THREAD

**Issue by Kromarr** [files-community/Files#6021]
### Description

When I try to modify in which way i view my files (example, a word) from a list to big icons, Files explorer bugs out and shuts up or doesn't show any file at all. This occurs specialy when I am inside an online folder, like onedrive or the new google drive por pc (especially this one).

### Steps To Reproduce

1.- Open File explorer
2.- Enter inside either onedrive or google drive for PC (especially this one)
3.- Try to modify the way you view your files (ideally have a word or PDF file somewhere)

### Expected behavior

It will either way shut down or dont show non of your files at all

### Files Version

v1.5.0.0

### Windows Version

Windows 10 20H2 19042.1202

### Relevant Assets

[debug.txt](https://github.com/files-community/Files/files/7100956/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/7100957/debug_fulltrust.txt)

**Comment by gave92** [comment]
Thanks for the report. This should be fixed in Files v2.
