### ISSUE TITLE
Duplicate Tab

### ISSUE THREAD

**Issue by zzz101** [files-community/Files#6026]
### Solution/Idea

Please add 'Duplicate Tab' action to context menu on tabs

### Alternatives

No alternatives

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

v1.5.0.0

### Windows Version

Windows 10 1909 18363.1734

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
