### ISSUE TITLE
FIle list does not automatically refresh after deleting or copying/moving a file

### ISSUE THREAD

**Issue by zzz101** [files-community/Files#6027]
### Description

Currently, after deleting a file, it is still listed unless manually refreshed.

### Expected behavior

The list of file needs to be automatically updated after a file or folder is deleted from or copied to a folder.

### Files Version

v1.5.0.0

### Windows Version

Windows 10 1909 18363.1734

**Comment by josh-65** [comment]
This has been fixed in the current insider builds and will be available for v2.
