### ISSUE TITLE
Bug: Multiselect doesn't work in the columns layout

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#6031]
### Description

The select all, select none and invert selection options are not working in the column layout.

### Steps To Reproduce

1. Go to any directory in the column layout and try one of the selection options.

### Expected behavior
- Multiselect should work in the columns layout

### Files Version

v2.0

### Windows Version

Windows 11

**Comment by ferrariofilippo** [comment]
Is this still a bug?

**Comment by yaichenbaum** [comment]
It seems to work correctly now but it's a bit confusing how it enables multiselect on all the columns. I'm not sure what the best path forward is but we might have to look at other apps/platforms to see how they handle it.
