### ISSUE TITLE
Online auto-synchronization 

### ISSUE THREAD

**Issue by hez2010** [files-community/Files#6032]
### What's the Problem?

Currently all settings, favorites and tags will lose if user reinstall Files.

### Solution/Idea

We can make use of OneDrive (with Microsoft Account) to auto synchronize user settings, favorites and tags. Also, we can use computer name to identify different computers.

### Alternatives

None.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Auto sync settings, favorites and tags with OneDrive | Must |

### Files Version

v2.0

### Windows Version

Windows 11 22449.1000

**Comment by Jaiganeshkumaran** [comment]
Related to #1260.

**Comment by esibruti** [comment]
Idea: we could ask the user, when he installs Files, if he wants to save it online (with Microsoft Account) or if he wants to save it on the local computer (hard disk of his choice) or even keep this option disabled.

**Comment by Josh-65** [comment]
Im going to close this, as settings can be exported as a zip and placed in the user preferred location.
