### ISSUE TITLE
Transition settings to json format

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#6033]
### What's the Problem?

The current method of saving settings works fine, but there is fragmentation between tags, themes and preferences.

### Solution/Idea

Moving all settings to json will all settings to be stored in one files with the added benefit of allowing users to export and import settings manually.

### Alternatives

NA

### Files Version

v2.0

### Windows Version

Windows 11

**Comment by d2dyno1** [comment]
Can you assign me?

**Comment by yaichenbaum** [comment]
> Can you assign me?

Great work!
