### ISSUE TITLE
Folders on Home are not working

### ISSUE THREAD

**Issue by BanCrash** [files-community/Files#6034]
### Description

When you click on a Home folder, it won't do anything. If you click on a drive it will work as expected though.

### Steps To Reproduce

1. Go to Home.
2. Try to open a Folder (for example, Desktop).
3. Nothing happens.

### Expected behavior

Should open the folder.

### Files Version

Last main

### Windows Version

Windows 10 21H1 19043.1165 

### Relevant Assets

![GIF 03-09-2021 16-25-19](https://user-images.githubusercontent.com/11770760/132021401-d1a875d7-2fee-43bb-bd7b-ec88c9aadfb7.gif)

Has to be because one of those 5 commits, since with my open PR it's working.

![image](https://user-images.githubusercontent.com/11770760/132021167-bbac79e9-f717-43d0-a3d7-fad6b1a17987.png)

**Comment by yaichenbaum** [comment]
@d2dyno1 do you want to look into this?

**Comment by d2dyno1** [comment]
I will!
