### ISSUE TITLE
AUTOFIT IN COLUMNS DOUBLE CLIC 

### ISSUE THREAD

**Issue by hangelini** [files-community/Files#6035]
### Description

Automatic width with double click in the column header limits column.
![Sin título](https://user-images.githubusercontent.com/27622081/132051375-8cc9f057-1eb8-41d1-a266-9b45c03eb9ce.png)

### Steps To Reproduce

GO TO FOLDER HEAD IN TITLE AND DOUBLE CLICK COLUMNS

### Expected behavior

AUTOFIT

### Files Version

1.5

### Windows Version

WINDOWS 10

**Comment by gave92** [comment]
Implemented in v2
