### ISSUE TITLE
Add a tick or X for operation status like MS edge downloads

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#6038]
### What's the Problem?

Currently when an item is done the icon for operation just show up. It would be nicer if I could see if they were done or failed

### Solution/Idea

Do what edge does with its download icon. When the items are complete it will have a tick icon in the corner of the main one. If they failed it has a X.

### Alternatives

Green and red dots without the icon in the middle if the area is too small.

### Files Version

2.0.0.0

### Windows Version

10.0.19043.1165

**Comment by yaichenbaum** [comment]
@josh-65 can you add a little more context?

**Comment by josh-65** [comment]
I updated the issue

**Comment by BanCrash** [comment]
@josh-65 is this what you want? rough mockup to check if I understand you correctly:
![image](https://user-images.githubusercontent.com/11770760/132075538-fd36d5f1-c36e-4c25-8178-fce5bc2e4968.png)

**Comment by josh-65** [comment]
yep

**Comment by yaichenbaum** [comment]
Related to #4811

**Comment by josh-65** [comment]
Merging with #6155

**Comment by yaichenbaum** [comment]
@josh-65 ah sorry Josh! Forgot about this issue 😆

**Comment by josh-65** [comment]
It alright its better said in the other one
