### ISSUE TITLE
Cloud Drives

### ISSUE THREAD

**Issue by moeezimmentia** [files-community/Files#6039]
### Description

cannot connect any cloud drive. It doesn't show any pop-up or error; nothing

### Expected behavior

Cloud drives should give any option to connect

### Files Version

v1.5

### Windows Version

Windows 10 Pro 21H1 19043.1165

**Comment by gave92** [comment]
Could you describe the steps you're following and what you're trying to connect to?
You don't really connect to cloud drives, you just install say the Google drive client app and google drive should appear on the Files sidebar.

**Comment by techtanic** [comment]
I have the same issue with MegaNZ

**Comment by gave92** [comment]
MEGA is not supported, supported cloud drives are atm: Google Drive, OneDrive, Box, Dropbox.
