### ISSUE TITLE
Store thinks the theme extension is a Windows 11 theme

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#6040]
### Description

![image](https://user-images.githubusercontent.com/26977075/132091250-87f8c5b3-7e97-4618-94e8-f46e94a0e24f.png)

### Expected behavior

Shouldn't have an apply button

### Files Version

2.0.0.0

### Windows Version

11.0.22449.1000

**Comment by yaichenbaum** [comment]
@josh-65 can you provide this feedback to Microsoft as it seems like an issue with the store rather than the extension?
