### ISSUE TITLE
Accessing a network folder by writing it on the address bar crash Files

### ISSUE THREAD

**Issue by BanCrash** [files-community/Files#6042]
### Description

When you write a network path on the address bar and press enter, it will make Files to crash.

### Steps To Reproduce

1. Enter the address bar.
2. Write a network address and press enter. I'm trying with my SMB folder `\\Synology` 
3. See that Files crashes.

### Expected behavior

Should not crash

### Files Version

Last Main

### Windows Version

Windows 10 21H1 19043.1165

### Relevant Assets

As #6034 , this should be caused by one of those commits since with my open PR it's working fine:

![image](https://user-images.githubusercontent.com/11770760/132021167-bbac79e9-f717-43d0-a3d7-fad6b1a17987.png)

[debug.log](https://github.com/files-community/Files/files/7110072/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7110073/debug_fulltrust.log)

**Comment by gave92** [comment]
Coud you add the error you get in the log?

**Comment by BanCrash** [comment]
> Coud you add the error you get in the log?

ooops, right, sorry!

2021-09-04 17:06:11.6195|ERROR|AppUnhandledException|Value cannot be null.
Parameter name: source
	System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Files.BaseLayout.ResetItemOpacity()
   at Files.Views.ModernShellPage.ItemDisplayFrame_Navigated(Object sender, NavigationEventArgs e)
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()

I will also edit the first post to include the full logs.

**Comment by gave92** [comment]
And the winner is.. #5981.
