### ISSUE TITLE
Renaming folders may rip them in half

### ISSUE THREAD

**Issue by SED4906** [files-community/Files#6043]
### Description

Renaming folders may fail messily. The renamed folder is created, contains part of the contents of the original folder, but the original still exists and has the rest. Some content exists in both folders at once.

### Steps To Reproduce

1. Create a copy of a folder with a good deal of subdirectories and files (This happened to me with a copy of Kodi's skin.estuary folder that had the generated new name "skin.estuary - Copy")
2. Rename the new copy (I tried to rename it to skin.sed)
3. The folder may be ripped in two.

### Expected behavior

The folder would be renamed properly.

### Files Version

Version: 2.0.0.0

### Windows Version

Windows 11 Home Insider Preview 22449.1000

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7109861/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7109862/debug_fulltrust.log)

**Comment by josh-65** [comment]
Same as #5852

**Comment by yaichenbaum** [comment]
Merging with #5852.
