### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Space-drago** [files-community/Files#6044]
### Description

When I clicked on one of my drives and error appeared. It said to report the bug. 

### Steps To Reproduce

1. I clicked a drive
2. It failed to enter the drive and created an error

### Expected behavior

I expected it to open the drive.

### Files Version

v15.0.0

### Windows Version

Windows 10 home 21h1 build 19043.1165

**Comment by gave92** [comment]
Thanks for the report. Please add the app's debug files to the description.
