### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by JaverHumberto** [files-community/Files#6047]
### Description

Sorry, but i'll write it in spanish.

Abrí una carpeta de una unidad virtual de google, la carpeta contiene archivos .pdf, los cueles se mostraron como íconos, prefiero la visualización como lista, así que traté de cambiarla a la opción detalles, pero tan pronto di click sobre la opción el explorador se cerró, ahora cada vez que intento abrir esta carpeta el explorador se cierra. Probe con otra carpeta que también tenía unicamente archivos .pdf, y sucedió lo mismo.

### Steps To Reproduce

1. Open a folder in googledrive virtual disk, if the folder contains files only, the default visualization is Icons
2. Change visualization to details
3. Files explorer shut down
4. Try to open the folder of step 1. again, and files explorer shut down again

### Expected behavior

The visualization of the folder changes to details type

### Files Version

V1.5.0.0

### Windows Version

Windows 10 Pro 20H2 19042.1165

### Relevant Assets

![image](https://user-images.githubusercontent.com/90112386/132106717-576dc9b8-abae-4e4f-9aa1-d8c342db941b.png)

**Comment by gave92** [comment]
Thanks for the report. Please add the apps debug files to the description.
