### ISSUE TITLE
Working directory in shortcuts are not editable or shown

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#6048]
### Description

![image](https://user-images.githubusercontent.com/26977075/132110675-d2d18724-3113-4e26-b4c3-ba4091cfee36.png)
Start in is blank in working directory and I cant edit it. Clicking on the text box it doesn't save text when closed it also doesn't show when there made.

### Expected behavior

It should show and be editable

### Files Version

2.0.0.0

### Windows Version

10.0.19043.1202

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7110662/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7110663/debug_fulltrust.log)

**Comment by gave92** [comment]
"It doesn't save the text": could you try clicking outside the textbox before hitting "ok"?

**Comment by josh-65** [comment]
It also seem the shortcuts don't get a working directory when made. So i have to add them from file explorer

**Comment by Josh-65** [comment]
Fixed in 2.3.11.0
