### ISSUE TITLE
"extract" in context menu

### ISSUE THREAD

**Issue by padredalvi** [files-community/Files#6050]
### Description

hovering over the extract button in context menu automatically closes the menu itself

### Steps To Reproduce

1. select any 'zip' file
2. right click the file
3. hover to extract button

### Expected behavior

more extract options should appear

### Files Version

v2.0.0.0

### Windows Version

Windows 11 Dev 22449.1000

**Comment by padredalvi** [comment]
not only the extract button, but also some other expandable buttons. I already opened a new issue about it.
https://github.com/files-community/Files/issues/6052

**Comment by gave92** [comment]
Thanks, merging with #6052
