### ISSUE TITLE
Built-in file converter

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#6053]
### What's the Problem?

Today there are many apps/websites that offer file type conversion however many of them aren't that great.

### Solution/Idea

Provide a built-in file converter with Files to convert files from and to common formats. Additionally there could be options to customise as well.

### Alternatives

None.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to convert files of common file types | Must |

### Files Version

v1.5

### Windows Version

Windows 10 Pro build 21354.1

**Comment by MalteTasler** [comment]
I think this would be a fitting and verry useful feature for an app like Files. Thumbs up. 👍

**Comment by yaichenbaum** [comment]
This seems a little more fitting for a third party utility that adds a shell item ot the context menu.

**Comment by MalteTasler** [comment]
If there already was a utility that works fine, I would agree. But I am not aware of such programm. I personally think, it could be an internal function of Files, but if so, then it surely is a priority for the far future for now.

**Comment by BanCrash** [comment]
> If there already was a utility that works fine, I would agree. But I am not aware of such programm. I personally think, it could be an internal function of Files, but if so, then it surely is a priority for the far future for now.

@MalteTasler https://github.com/Tichau/FileConverter this works well for me.
