### ISSUE TITLE
Other elements dropdown instantly closes

### ISSUE THREAD

**Issue by maicol07** [files-community/Files#6055]
### Description

The other elements dropdown opens and closes himself

### Steps To Reproduce

1. Right click a folder/file
2. Scroll down to other elements
3. Hover or click on other elements
4. See issue

### Expected behavior

The other elements dropdown opens and let me select an option

### Files Version

Versione 2.0.1.0

### Windows Version

Windows 11 Pro 10.0.22449.1000

### Relevant Assets

[debug_fulltrust.log](https://github.com/files-community/Files/files/7111338/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7111339/debug.log)

GIF showing the issue:
![itAh6jXB72](https://user-images.githubusercontent.com/9463142/132122151-7cfd42ae-7b61-4c6c-b84a-439d064f4ef0.gif)

**Comment by gave92** [comment]
Merging with #6052
