### ISSUE TITLE
Beta 2.0.1.0: Files won't delete

### ISSUE THREAD

**Issue by enoversum** [files-community/Files#6056]
### Description

When either using the context menu or the Del key, files and folders won't delete. It also creates a corresponding error message in the 'Ongoing tasks' menu. Update: This doesn't happen all the time. 

### Steps To Reproduce

1. Open Files.
2. Delete a file through context menu or with the Del key.
3. File won't get deleted, and an error message appears in the 'Ongoing tasks' menu.

### Expected behavior

Files delete :) .

### Files Version

v2.0.1.0

### Windows Version

Windows 11 (22000.168)

**Comment by enoversum** [comment]
Update: After closing and opening Files once more, file deletion is working again.

**Comment by enoversum** [comment]
Update II: Also happens with drag and drop moving of files or folders. A restart of Files re-enables me to drag and drop folders.

**Comment by duke7553** [comment]
Hi @enoversum,

When you get a moment, can you upload both of the required "debug" log files as pictured below?

![image](https://user-images.githubusercontent.com/20365014/132412385-ae891624-0da2-40d8-a9df-1f54b2724579.png)

Much appreciated!

**Comment by enoversum** [comment]
@duke7553 Cannot reproduce the deletion problem anymore, but drag & drop to a folder is still a bit hit and miss. Oftentimes the stop sign won't allow me to drag a file or folder into another folder. Logs are attached.

[debug_fulltrust.log](https://github.com/files-community/Files/files/7126255/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7126256/debug.log)
