### ISSUE TITLE
Add support for rar files

### ISSUE THREAD

**Issue by Spontini** [files-community/Files#6057]
### Solution/Idea

I don't know if it's possible but can you add support for rar, iso, 7z etc?

### Alternatives

-

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

v2.1

### Windows Version

Windows10

**Comment by gave92** [comment]
Merging with #45
