### ISSUE TITLE
Submenus cause the primary flyout to close.

### ISSUE THREAD

**Issue by Tropix126** [files-community/Files#6058]
### Description

When accessing a submenu in any CommandBarFlyout in Files, it will close as soon as a submenu is rendered making the context menu fairly unusable.

### Steps To Reproduce

1. Right click a file.
2. Hover over any item with a submenu attached.

### Expected behavior

The primary CommandBarFlyout should stay open when the submenu opens.

### Files Version

2.0.1

### Windows Version

22449

### Relevant Assets

https://user-images.githubusercontent.com/42101043/132130634-65bd5c1b-72c0-4805-a514-c64e50f5b865.mp4

**Comment by yaichenbaum** [comment]
Merging with #6052.
