### ISSUE TITLE
error showing hidden files.

### ISSUE THREAD

**Issue by cleuton4k** [files-community/Files#6059]
### Description

when activating or deactivating the show hidden files function a message appears that the unit has been disconnected.

### Steps To Reproduce

layout --> shows hidden files.

### Expected behavior

show hidden files.

### Files Version

2.0.1.0

### Windows Version

windows 10 64 bits 21h1 19043.1202

### Relevant Assets

![2](https://user-images.githubusercontent.com/90144967/132131453-7794a186-3f0b-4b44-8864-66e56b91479c.jpg)

**Comment by josh-65** [comment]
Same as #6054

**Comment by gave92** [comment]
Merging with $6054
