### ISSUE TITLE
Properties option should be expanded in the flyoutmenu

### ISSUE THREAD

**Issue by MarcAnt01** [files-community/Files#6067]
### What's the Problem?

I'd like to have a kind of consistency with Windows 10 explorer context menus. Also because the ui is heavily inspired by it

### Solution/Idea

Move properties window from top icons to the normal flyoutmenu.
I think it makes more sense since icons are too much considering the flyoutmenu dimensions and I also think properties is unrelated to the other stuff there such as copy, delete, rename etc.

### Alternatives

None

### Priorities

| This proposal will allow end users to accomplish X | Should |

### Files Version

2.0.1.0

### Windows Version

Windows 11 Insider

### Additional comment

Files
![image](https://user-images.githubusercontent.com/43090263/132203197-7572bbcd-2b50-45c2-a962-aa7bf161dd60.png)

File explorer
![image](https://user-images.githubusercontent.com/43090263/132203292-be96e2e7-04fc-4540-ba79-462da46a8df7.png)

**Comment by yaichenbaum** [comment]
I don't quite agree with how it's done in File Explorer. While consistency is nice, it's important to remember that Files isn't File Explorer.

**Comment by MarcAnt01** [comment]
True, but it's not only because "explorer does that", it's also because I find that there are too many elements in that section, especially considering the reduced menu, with "more options" and imo it should also logically be in the main menu, because properties is not related at all to the stuff up above

**Comment by yaichenbaum** [comment]
> It's also because I find that there are too many elements in that section

There is quite a bit of room in that section 🤔 

> and imo it should also logically be in the main menu, because properties is not related at all to the stuff up above

The actions in the top row are all common actions and easily recognizable by the icon.

**Comment by MarcAnt01** [comment]
> > It's also because I find that there are too many elements in that section
> 
> There is quite a bit of room in that section 🤔
> 
> > and imo it should also logically be in the main menu, because properties is not related at all to the stuff up above
> 
> The actions in the top row are all common actions and easily recognizable by the icon.

For me they're the typical file related settings, maybe share it's an exception, but the other ones are. For example if you plan to add shortcuts, you don't need to specify them, but in case you add a shortcut for file info, people wouldn't know about it in the current design. (File explorer puts the shortcut next to the option)

**Comment by esibruti** [comment]
@yair100 Couldn't you use the same icons?

**Comment by MalteTasler** [comment]
I like the current approach. The properties shortcut is not only common, it is also an option that is available on every folder and file, like the other buttons in the top row. 

While this is different from file explorer, once you get used to it it shouldn't get in the way for the majority of users.

**Comment by yaichenbaum** [comment]
@MarcAnt01 thank you for opening the issue, I just wanted to let you know that we don't have plans to make this change.
