### ISSUE TITLE
ctrl + F shortcut doesn't work in home

### ISSUE THREAD

**Issue by MarcAnt01** [files-community/Files#6068]
### Description

ctrl + F to search shortcut is normally working, but not in the home

### Steps To Reproduce

1. Go in the home
2. Press ctrl + F

### Expected behavior

Work as it does in the other folders

### Files Version

2.0.1.0

### Windows Version

Windows 11 Insider

**Comment by yaichenbaum** [comment]
This issue should be resolved with #6671.
