### ISSUE TITLE
Photos preview layout

### ISSUE THREAD

**Issue by MarcAnt01** [files-community/Files#6069]
### What's the Problem?

There's no problem at all. But Microsoft has added a video preview layout in Windows 11 explorer which I find quite useful, especially when there are some similar photos and I want to pick the right one.

### Solution/Idea

Implement an optional panel on the right with a similar layout to the one of Windows 11 explorer

### Alternatives

None

### Priorities

| This proposal will allow end users to accomplish X | Should |

### Files Version

2.0.1.0

### Windows Version

Windows 11 Insider

### Additional comment

![image](https://user-images.githubusercontent.com/43090263/132205672-2d042641-b7ba-4dc8-91d4-2829007dbb91.png)

**Comment by gave92** [comment]
There's already a preview pane in Files, the button to toggle it is at the right of the Files toolbar.

**Comment by MarcAnt01** [comment]
I haven't noticed that, now that I've taken a look I have seen that it displays information about the file and not only the preview. I honestly find it useless for other types of files, so I'd like to have a preview specifically for photos without showing unnecessary information that I can easily access in the property window.

**Comment by winston-de** [comment]
You can right click the preview to reveal an option to show only the preview.

![image](https://user-images.githubusercontent.com/59544401/132232387-27954c3d-da81-478f-af3e-cbd42d28d236.png)

**Comment by MarcAnt01** [comment]
Nice, this is what I was looking for, but I do think:
- It's not intuitive to get details/w.o. details view right clicking on the preview, I think you should add a small button in the preview area or an option in the top bar;
- The view without details should be the default option;
- The preview shouldn't show anything when it's unable to get the preview (for example a huge pdf file or an unsupported file type) or when it's a folder/zip archive

**Comment by Rasmagoric** [comment]
I didn't even know about the current right click on the preview pane to hide details.
I prefer the way it was in v1.5 where you could intuitively resize the details and hide it.

https://user-images.githubusercontent.com/24687648/132241123-8c9ce9f8-b107-4961-9919-cb5555bb7019.mp4

If it was collapsible  (in the same way the sidebar is), and you could then alternate between both states intuitively it would be perfect

**Comment by winston-de** [comment]
The ui for collapsing the details is not final, it's a temporary solution until the design is finalized.

**Comment by MarcAnt01** [comment]
I'm closing this, since it's just confusing. I'll soon create a new ticket explaining the improvements that I think that should be made
