### ISSUE TITLE
Allow side-swipe with touchpad/touch for the "pivot" in properties window

### ISSUE THREAD

**Issue by MarcAnt01** [files-community/Files#6070]
### What's the Problem?

Pivots usually allow that by default. Are you using by chance another control that looks like a pivot?

### Solution/Idea

Allow side-swipe with touchpad/touch for the pivot in properties window. Basically allow to go to general, details, security etc.

### Alternatives

None

### Priorities

| This proposal will allow end users to accomplish X | Should |

### Files Version

2.0.1.0

### Windows Version

Windows 11 Insider

**Comment by gave92** [comment]
Correct, currently it's a TabView control not a Pivot.

**Comment by MarcAnt01** [comment]
I don't have any particular need to have you to use pivot, but I'd be happy if you could implement this beahavior

**Comment by Josh-65** [comment]
Is this still and issue?

**Comment by yaichenbaum** [comment]
Yes, but we don't have plans to support this.
