### ISSUE TITLE
Ejecting ISOs does not unmount the virtual drive.

### ISSUE THREAD

**Issue by GittyMac** [files-community/Files#6072]
### Description

If you eject an ISO in Windows Explorer, it will also remove the virtual drive. If you do it in Files, it won't remove the virtual drive. If you look in Explorer after ejecting the ISO, you will see an empty virtual drive.

### Steps To Reproduce

1. Go to the home page with the drives.
2. Eject the ISO.
3. View the drives in Explorer.

### Expected behavior

The virtual drive should also be ejected along with the ISO.

### Files Version

v2.0.11.0

### Windows Version

Windows 11 Home 21H2 22000.176

**Comment by Josh-65** [comment]
@GittyMac is this still an issue in 2.3.11 (stable release)?

**Comment by GittyMac** [comment]
@Josh-65 This is still an issue in 2.3.11.0.

**Comment by yaichenbaum** [comment]
This should be resolved with #9770
