### ISSUE TITLE
Settings close button overlaps window close button with a small window

### ISSUE THREAD

**Issue by MarcAnt01** [files-community/Files#6073]
### Description

Settings close button overlaps window close button with a small window

### Steps To Reproduce

1. Make the window very small;
2. Open settings

### Expected behavior

Not overlap, it should have a bigger vertical margin so that this doesn't happen.

### Files Version

2.0.11.0

### Windows Version

Windows 11 Insider

### Relevant Assets

![image](https://user-images.githubusercontent.com/43090263/132251847-e3b0c640-0346-4c09-9a4e-6b21c792257e.png)

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
