### ISSUE TITLE
Home items should follow "Open items with one click" setting

### ISSUE THREAD

**Issue by BanCrash** [files-community/Files#6074]
### What's the Problem?

Even if you have disabled the one click setting, all items on Home will open with one click.

### Solution/Idea

All Home items (folders, drives, bundles, etc.) should respect the setting at hand to keep consistency.

Related to #2994

### Alternatives

I can't figure it out another alternative.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish respect "Open items with one click" setting on Home items | Must |

### Files Version

Last Main

### Windows Version

Windows 10 21H1

**Comment by gave92** [comment]
Also #2994. If we do this I think that we also need to provide some visual feedback for single clicks (with open-with-one-click disabled). E.g. recent files should get selected, otherwise it may not be obvious you need to click twice especially for the top folders..

**Comment by yaichenbaum** [comment]
Should this be merged with #6074?

**Comment by THEBOSSMAGNUS** [comment]
Also the drag and drop is broken in Home

**Comment by THEBOSSMAGNUS** [comment]
You can't drag an item from recent file

**Comment by gave92** [comment]
I see, we never planned for recent files to be draggable but that would make a useful feature request I think.

**Comment by THEBOSSMAGNUS** [comment]
I will make it

**Comment by yaira2** [comment]
The home page has a bit of a different interaction model, toolbar items are disabled and multi select isn't supported so I think it's okay to leave as is.
