### ISSUE TITLE
Add a Bundles sidebar section

### ISSUE THREAD

**Issue by BanCrash** [files-community/Files#6075]
### What's the Problem?

Currently I'm not using bundles because in the Home section are not very comfortable for me. I would use it if it is on the sidebar as another section

### Solution/Idea

Since now we can show or hide sidebar sections, I don't see any harm on having a Bundles section limited to the bundles titles, so if you click in for example Bundle 1, it will open the bundle in a new tab and you can select whatever item you want there. 

Also you will have the option of drop items into the tab, causing this to be added to the bundle at hand.

This could be added as an addition or as a modification of the actual bundles system. Both options are fine to me.

### Alternatives

Stay with the actual system I guess.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish add a Bundles section on the sidebar | Must |
| This proposal will allow end users to accomplish have a better way to handle bundles | Should |

### Files Version

Last Main

### Windows Version

Windows 10 21H1

### Additional comment

This is a paint (badly) mockup I made basing on the tags section specification. In my idea you can also set colours to the bundles as it's done with tags to easily know each of them, but also could be made with custom icons.

![image](https://user-images.githubusercontent.com/11770760/132257794-a9924495-d434-4da2-ac81-c47165af7dbc.png)

**Comment by yaichenbaum** [comment]
Is this different than tags? As a side note, I think bundles can eventually be replaced with tags.

**Comment by BanCrash** [comment]
> Is this different than tags? As a side note, I think bundles can eventually be replaced with tags.

I didn't think about tags that way, and although I'm not sure they are the same I think that for what I want they should do what I want, so at the moment I will close this.
