### ISSUE TITLE
App closing sometimes

### ISSUE THREAD

**Issue by bnbagiz** [files-community/Files#6078]
### Description

The file manager closes sometimes, i guess its happening when im trying to get deeper and deeper into on edirectory ?!

### Steps To Reproduce

just by using it

### Expected behavior

the app closes completly

### Files Version

1.5

### Windows Version

10

**Comment by gave92** [comment]
Thanks for this report. This issue should be fixed in Files v2. Could you anyway upload the app's debug logs?
