### ISSUE TITLE
Mount external drives

### ISSUE THREAD

**Issue by truni** [files-community/Files#6079]
### What's the Problem?

Volumes like pcloud, onedrive and others do not show up

### Solution/Idea

Can we have external drives attaced to Files?

### Alternatives

How to access them as alternative?

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

v1.50

### Windows Version

Windows10 21H1

**Comment by josh-65** [comment]
Are you talking about cloud drives showing up in the drives section or the cloud drives on the sidebar

**Comment by truni** [comment]
Hello Josh, could not answer yet. But they are cloud drives (i.e. OneDrive,
pcloud, ....) which should show up. Is it possible?

Daniel

Am Mi., 15. Sept. 2021 um 15:40 Uhr schrieb Yair Aichenbaum <
***@***.***>:

**Comment by josh-65** [comment]
They should show up manually after you install the client and set it up.

**Comment by Josh-65** [comment]
Is this still an issue?

**Comment by truni** [comment]
Not at the moment!

Daniel

… verfasst uf Trunis iPhone
