### ISSUE TITLE
Enpass and Gdoc files don't use details view even when its selected

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#6081]
### Description

They seem to not allow details and column views. Selecting one of the view modes will just use the previous one that works. The extensions are .gdoc, .enpassbackup, .syncwallet
![image](https://user-images.githubusercontent.com/26977075/132414924-55d24497-a829-4965-991a-b3469c973990.png)

### Expected behavior

Should allow detail and column views

### Files Version

2.0.11.0

### Windows Version

10.0.19043.1202

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7124155/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7124156/debug_fulltrust.log)

**Comment by gave92** [comment]
Strange, I'd expect the issue is not caused by the file types but by the folder they are in. Is there something that makes you say it's the file extensions?

**Comment by gave92** [comment]
Could you check if the issue persists if you move the files to a new folder?
Could you check if the issue persists if you turn off the "Use individual preferences for individual folders" option?

**Comment by josh-65** [comment]
Seems to be glitched for those folder only. maybe when the fix was added for them diapering they just broke. Il try moving them out into a new folder and see if it happens again.

**Comment by josh-65** [comment]
Closing since fixed by just moving the folders out then back in
