### ISSUE TITLE
Application crashes upon opening folders with large amounts of files.

### ISSUE THREAD

**Issue by gjoedev** [files-community/Files#6088]
### Description

I've noticed that occasionally files will crash after I open my downloads folder with the files app. The app seems to try to load for a bit, then crashes.

### Steps To Reproduce

1. Find a folder with alot of files
2. Open folder
3. May encounter crash.

### Expected behavior

1. Find folder with alot of files
2. Open folder
3. App loads files without crashing.

### Files Version

1.5.0.0

### Windows Version

Windows 20H2 Build 19042.1165

### Relevant Assets

[debug.txt](https://github.com/files-community/Files/files/7132087/debug.txt)

**Comment by gave92** [comment]
Thanks for the report. This issue should be fixed in Files V2.
