### ISSUE TITLE
OneDrive Share Option Hidden 

### ISSUE THREAD

**Issue by thorrrr** [files-community/Files#6090]
### What's the Problem?

OneDrive Share Option Hidden 

### Solution/Idea

When i click on Cloud Services i would expect to be able to get to share option on 1 right clcik not have to go to another level really slows up productivity

### Alternatives

Not using this app

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

1.5

### Windows Version

Win 10 Pro 21H1 19043.1202

**Comment by thorrrr** [comment]
x

**Comment by josh-65** [comment]
Do you have Move items into overflow sub menu one (Settings > appearance)

**Comment by thorrrr** [comment]
Sorted now didn’t see that setting
