### ISSUE TITLE
drag and drop

### ISSUE THREAD

**Issue by vitality29** [files-community/Files#6092]
### What's the Problem?

drag and drop way to move is not available

### Solution/Idea

ability to move the files in the windows and drag it ontop of a folder to move it inside a folder

### Alternatives

none

### Priorities

this proposal will make it easier for us to use the file explorer on a daily basis

### Files Version

v1.5

### Windows Version

22449.1000

### Additional comment

n/a

**Comment by gave92** [comment]
You can already drag&drop to move or copy. You need to select an item first and click again to start dragging. In Files v2 instead you can just start dragging like in explorer.
