### ISSUE TITLE
full files overule not working

### ISSUE THREAD

**Issue by vitality29** [files-community/Files#6093]
### Description

files does not completely replace the files explorer. At times when you need another app to open a file location it uses file explorer instead of files

### Steps To Reproduce

open any app like discord
when u try to open a file to upload
it opens up the file explorer instead of files

### Expected behavior

i wanted it to open files app instead of file explorer

### Files Version

v1.5

### Windows Version

22449.1000

**Comment by gave92** [comment]
Thanks for this suggestion, this is something we're looking into but it's hard to implement. Also #4106.
