### ISSUE TITLE
`NotAFolder` Error after Switching Language

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#6094]
### Description

After switching to another language with the default tab is `New tab`, the error dialog `NotAFolder` will show up.

### Steps To Reproduce

1. Click on New Tab
2. Go to Settings
3. Go to Preferences Tab > Language (Switch to a random language which was different from the default language)
4. Click Yes to restart
5. See error

### Expected behavior

No error was returned from the app

### Files Version

2.0.11.0

### Windows Version

Windows 10 21H1 19043.1202

### Relevant Assets

https://user-images.githubusercontent.com/69080584/132786434-fc6dcdbc-1175-4311-8060-94e113451137.mp4

[debug_fulltrust.log](https://github.com/files-community/Files/files/7140740/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7140741/debug.log)

**Comment by BanCrash** [comment]
Thanks for the report, this is already reported. Merging with #3983
