### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by O-Asymmetricity-O** [files-community/Files#6095]
### Description

![image](https://user-images.githubusercontent.com/82051318/132786480-5c11aa29-0963-4c12-b28b-15aca50a0ad1.png)

the icons look like they are over-lapping each other ( default theme) not sure if its a bug or jus doesnt look right me to me alone

### Steps To Reproduce

1. Open Files app
2.  Press a file once

### Expected behavior

ig it should show one solild colour?

### Files Version

v2

### Windows Version

21 H2 19043 .1165

### Relevant Assets

![image](https://user-images.githubusercontent.com/82051318/132786720-8717b3b2-f30b-455d-9832-431ade11713a.png)

**Comment by josh-65** [comment]
That's what they are suppose to look like. The non white part is based on your systems accent color.

**Comment by O-Asymmetricity-O** [comment]
Oh I see thnx for the clarification
