### ISSUE TITLE
Miller Columns system

### ISSUE THREAD

**Issue by amauriswill** [files-community/Files#6100]
The option of having the "Miller Columns system" could be add to the project?

In order to increase the efficiency navigating deep folder structures...

**Comment by amauriswill** [comment]
# feature request

**Comment by bradmonk** [comment]
I would also like the option to have **Miller Columns**, and **Disclosure Triangles**. Both are native in macOS Finder, and very useful.

![Miller Columns](https://user-images.githubusercontent.com/3250505/132936672-3b300dab-2e1b-4b03-aae7-75596e9dda15.jpg)

![Disclosure Triangles](https://user-images.githubusercontent.com/3250505/132936669-1ecbffa2-3555-4081-a9a4-f9c9558fe869.jpg)

**Comment by gave92** [comment]
Files v2 has ColumnView 💪 For tree view: #1928

**Comment by bradmonk** [comment]
Oh awesome. What's the time estimate for seeing a [release](https://github.com/files-community/Files/releases) version of [v2](https://github.com/files-community/Files/blob/4e9468f6b967d986be0fbcad56e5136478a2fe18/Files.Package/Package.appxmanifest#L12)?

**Comment by gave92** [comment]
October 4th
