### ISSUE TITLE
Date/Time formats

### ISSUE THREAD

**Issue by RedSkyRoad** [files-community/Files#6101]
### Description

I've set the data/time format to follow system preferences but a LOT of folders do not adhere to these changes I've made. Some show correctly and some don't. The folders don't remember their column widths, as well

### Steps To Reproduce

1. Settings
2. Appearance
3. Date Format
4. System

### Expected behavior

ALL the files should show the correct selected format

### Files Version

1.5

### Windows Version

Windows 11 Pro 21H2 22000.184

**Comment by gave92** [comment]
Thanks for the report. Both this issues should be fixed in Files v2.

**Comment by RedSkyRoad** [comment]
Hi,
I'm trying to get access to the v2 preview but after asking for an OTP, it
ask for a password which I don't have.

Thanks in advance

PS: This file browser is AWESOME

**Comment by gave92** [comment]
Glad you like it 🙏. An easier way to get Files v2 is to join the Files discord server https://discord.gg/files. The installers for preview versions of Files get regularly posted there.

**Comment by gave92** [comment]
PS: @RedSkyRoad where do you get asked for a password when trying to get Files preview? Have you filled this form: https://forms.office.com/r/E5Lri2nGqe?

**Comment by RedSkyRoad** [comment]
I went to that discord server and then it said something went weird and
asked to send an otp to my phone

**Comment by RedSkyRoad** [comment]
That lnk you just posted does nothing when I click Accept invite

**Comment by RedSkyRoad** [comment]
I've filled that Microsoft form as well. I'm not having ANY luck at getting
to a download link

**Comment by RedSkyRoad** [comment]
Hi,

I haven't received any news as to the v2 I requested
