### ISSUE TITLE
Use custom fonts in Files

### ISSUE THREAD

**Issue by DeveloperWOW64** [files-community/Files#6102]
### Solution/Idea

I would like the ability to have custom fonts that are installed on the user's computer to be selected as the main font that shows up in Files.
If this feature is accepted, It would be a good idea if it went inside the 'Experimental' section of the Files settings pane, as it may not show or squeeze some strings appearing in small spaces not allocated for the length of some custom font characters. 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Allow custom fonts installed on the system to be chosen as the font showing up everywhere in Files | Must |
| This feature may go inside the 'Experimental' section of the Files settings pane, as (note this as only a guess) it may not show some strings appearing in small spaces not allocated for the length of some custom font characters. | Could |

### Files Version

v2.0.12.0

### Windows Version

Windows 10 Home Version 21H1 19043.1165

**Comment by yaichenbaum** [comment]
@DeveloperWOW64 thank you for the feature request, while we have nothing against this request, won't be implementing it since it doesn't line up with our plans for Files.

**Comment by DeveloperWOW64** [comment]
ok. that's fine.
