### ISSUE TITLE
Broken Scroll Wheel in Settings

### ISSUE THREAD

**Issue by Placeholder6** [files-community/Files#6103]
### Description

scroll wheel doesnt work in the settings menu, unless i use the scroll bar once

### Steps To Reproduce

1. open the app
2. click settings
3. click on files and folders, nd try to scroll
4. the scrollbar moves but the text doesnt

### Expected behavior

text should move when i use the wheel

### Files Version

v2.0.12.0

### Windows Version

Windows 11 beta (22000.120)

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7148261/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7148263/debug_fulltrust.log)

**Comment by R3voA3** [comment]
Win11 issue? Works fine on W10 for me.

**Comment by josh-65** [comment]
There have been may updates on the beta and dev branch's of windows you should try updating.

**Comment by Placeholder6** [comment]
alright i'll try updating windows

**Comment by puppetsw** [comment]
I can't seem to replicate this issue. Windows 11 (10.0.22000)

**Comment by Josh-65** [comment]
This has proberly been fixed from the settings redesign
