### ISSUE TITLE
Scrolling in the Appearence settings when opening the themes menu glitchy.

### ISSUE THREAD

**Issue by RickeyHo** [files-community/Files#6105]
### Description

Upon installing themes, and opening its fly down menu, scrolling themes with the scroll wheel is impossible and it takes a couple of tries with the scrollbar, at that point the scrolling with the scroll wheel actually works.

### Expected behavior

The menu should scroll normally.

### Files Version

Version: 2.0.12.0

### Windows Version

OS Version: 10.0.22000.184

**Comment by yaichenbaum** [comment]
Merging with #6103.
