### ISSUE TITLE
Hide "Ongoing Tasks" when there are no tasks on going

### ISSUE THREAD

**Issue by Creepercdn** [files-community/Files#6106]
### Solution/Idea

Hide "Ongoing Tasks" when there are no tasks on going

### Alternatives

Hide "Ongoing Tasks" when there are no tasks on going

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Hide "Ongoing Tasks" when there are no tasks on going | Should |

### Files Version

1.5

### Windows Version

Windows 10 Professional 21H2 19044.1202

**Comment by BanCrash** [comment]
Thank you for your feedback! This is already implemented on v2.0, which will be released on October.
