### ISSUE TITLE
Can't copy or move shortcuts

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#6108]
### Description

It doesn't copy shortcuts when trying.

### Steps To Reproduce

1) Create a short cut on file
2) Copy or cut shortcut
3) Go to new directory
4) Paste shortcut
5) See it doesn't. (if there a previous copied file it pastes that instead)

### Expected behavior

Should copy short cut

### Files Version

2.0.12

### Windows Version

10.0.19043.1202

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7149605/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7149606/debug_fulltrust.log)

**Comment by gave92** [comment]
Broke in #6028

**Comment by yaichenbaum** [comment]
This issue should be resolved with #6109.
