### ISSUE TITLE
Bug: Changing tab with keyboard doesn't update address bar

### ISSUE THREAD

**Issue by BanCrash** [files-community/Files#6111]
### Description

When you use a keyboard shortcut to change to the previous or next tab (Ctrl + Shift + Tab or Ctrl + Tab), sometimes it will change the folder contents but not the toolbar and address bar, other times it won't change at all...

In the gif, check for example that the second time changing from home to Music, it will keep the widgets button instead the folder buttons, and the address bar says "Nueva pestaña" instead my Music path.

### Steps To Reproduce

1. Open several tabs with differents folder.
2. Start to change tabs with the keyboard shortcut (Ctrl + Shift + Tab or Ctrl + Tab)
3. Check the address bar and see that sometimes it shows an incorrect address.

NOTE: For some reason apening settings and closing it seems to fix the issue until you open a new tab. 

### Expected behavior

It should show the proper address and toolbar.

### Files Version

V 2.0.12.0

### Windows Version

OS Version: Windows 10 21H1 10.0.19043.1202

### Relevant Assets

![GIF 13-09-2021 15-55-22](https://user-images.githubusercontent.com/11770760/133096806-91d2dcfa-c58d-468f-a8fd-9d5cae2a5f12.gif)

Log files:
[debug_fulltrust.log](https://github.com/files-community/Files/files/7154784/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7154785/debug.log)

**Comment by yaichenbaum** [comment]
@BanCrash do you want to work on this issue?

**Comment by BanCrash** [comment]
> @BanCrash do you want to work on this issue?

Yeah, I already had on my to do to check if I can fix it 👍🏻

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by BanCrash** [comment]
> Is this still an issue in the preview version? https://files.community/download/preview

Yes, it is.

**Comment by yaira2** [comment]
It seems to happen when it cycles back to the first tab 🤔

**Comment by BanCrash** [comment]
> It seems to happen when it cycles back to the first tab 🤔

In my case is not necessary, just switching to another tab and going back will make that happen. Just tested with 3 tabs, switching to 3, then switching back to 2 and again to 3. Issue happens.

All my attemps of solving it were a dead end.

**Comment by yaira2** [comment]
@cinqmilleans fyi

**Comment by BanCrash** [comment]
FYI, this is not fixed in 2.4.60.0 @yair100

**Comment by yaira2** [comment]
The fix wasn't included in v2.4.60 but you can test it in `main`.

**Comment by BanCrash** [comment]
> The fix wasn't included in v2.4.60 but you can test it in `main`.

Yep, you are right, in main is fixed, my bad!
