### ISSUE TITLE
Navigating back with mouse buttons is broken

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#6112]
### Description

Navigating back works once, after that it navigates back and immediately forward 

https://user-images.githubusercontent.com/17484252/133124576-cc804909-2d2b-4492-9812-7f23f863e773.mp4

again.

### Steps To Reproduce

1. Navigate into a folder
2. Navigate back a few times with mouse button

### Expected behavior

Should just work as navigating with the UI controls.

### Files Version

Version: 2.0.12.0

### Windows Version

OS Version: 10.0.19043.1165

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7156072/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7156073/debug_fulltrust.log)

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?
