### ISSUE TITLE
Add download icon next to the settings button to indicate when updates are available 

### ISSUE THREAD

**Issue by MarcAnt01** [files-community/Files#6115]
### What's the Problem?

The way that new updates are shown with a ContentDialog is really annoying because in interrupts the app usage (for example if I am studying or doing something important I don't wanna be disturbed) and it keeps happening every time the app is launched even if I have pressed no sthe

### Solution/Idea

Show a small button with update available in that area. There are probably better ideas, just saying the only one that I have thought about
![image](https://user-images.githubusercontent.com/43090263/133157730-07200a64-62ea-4a14-8afa-de45ae28f80a.png)

### Alternatives

None for the moment

### Priorities

| This proposal will allow developers to accomplish W | Must |

### Files Version

2.0.12.0

### Windows Version

Windows 11 Insider

**Comment by josh-65** [comment]
I too find it quite annoying as a pop up, maybe a up arrow as a button to the right of settings would be better. Then when hovered it show update available.

**Comment by Tropix126** [comment]
Could have TeachingTip?

**Comment by ironmankaz** [comment]
How to get files beta, When I install it from the MS Store it is given as 2.0.0.0, but i want the beta

**Comment by yaichenbaum** [comment]
> How to get files beta, When I install it from the MS Store it is given as 2.0.0.0, but i want the beta

The Files Insider program is currently closed, we'll make an announcement when it reopens.

**Comment by esibruti** [comment]
For those who want to make this feature, you can consult this page:
[Microsoft Docs](https://docs.microsoft.com/en-us/windows/apps/design/controls/info-badge)

**Comment by puppetsw** [comment]
@yair100 mind if I take this one?

**Comment by yaichenbaum** [comment]
@puppetsw just to recap, the intentded design is to display a button to the left of the settings button when an update is available.

**Comment by yaichenbaum** [comment]
@MarcAnt01 this issue should be resolved with #8054
