### ISSUE TITLE
Files does not correctly show year 1601 or year 9999 in the column

### ISSUE THREAD

**Issue by gitbbkload** [files-community/Files#6116]
### Description

Hello,

I have found a problem in Files, it does not correctly show in the column (Date modified and Date created) the year 1601 or year 9999. I use NTFS as file system.

![Screenshot 2021-09-14 094228](https://user-images.githubusercontent.com/90634153/133175339-4e3f3955-f314-457c-ad9c-8f82aee901c8.png)

7-Zip shows the year 1601 and year 9999 inside the .zip file.

![Screenshot 2021-09-14 005235](https://user-images.githubusercontent.com/90634153/133116940-b6ca3c47-aff1-4319-ab5e-816b1b9bf935.png)

### Steps To Reproduce

1. [1601+9999.zip](https://github.com/microsoft/winfile/files/7155695/1601%2B9999.zip)
2. The .zip file must be extracted with [7-Zip](https://7-zip.org/download.html) because Files internal zip function cannot set the timestamps (year 1601 and year 9999) correctly.

### Expected behavior

- It correctly shows year 1601 or year 9999 in the column

- Files internal zip function can set year 1601 and year 9999 correctly during extraction

- Files internal zip function can correctly display year 1601 and year 9999 inside a .zip file for Date modified, Date created, Date accessed

- Date accessed can be added to the column so that I can display all 3 timestamps by default: Date modified, Date created, Date accessed

### Files Version

v2.0.12.0

### Windows Version

Windows 11 21H2 22000.184

**Comment by BanCrash** [comment]
Is there any special reason that you want to see the year 1601? The not showing is intentional since 1601 is showed when there is no date set. On Windows File Explorer those files show 1601 too?

**Comment by josh-65** [comment]
The 1601 might not be needed but if a date is set to 9999 it should show that rather than -44 seconds.

**Comment by BanCrash** [comment]
> The 1601 might not be needed but if a date is set to 9999 it should show that rather than negative seconds.

I agree about the not showing negative seconds, but I would prefer the empty space also. Those dates are not real and I can't think on a scenario that they could be useful to be showed. Let's see what @gitbbkload thinks though.

**Comment by yaichenbaum** [comment]
Closing as the underlying issue was resolved.
