### ISSUE TITLE
does the Acrylic blur removed from the last update or is something wrong with my PC

### ISSUE THREAD

**Issue by Evilix** [files-community/Files#6119]
### What's the Problem?

Acrylic blur removed

### Solution/Idea

if you removed it please add it back or add the option to turn it on/off in settings
thanks for the amazing app

### Alternatives

none

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.0.0.0

### Windows Version

Edition	Windows 10 Pro Version	21H1 Installed on	‎10-‎Sep-‎21 OS build	19043.1237 Experience	Windows Feature Experience Pack 120.2212.3530.0

**Comment by yaichenbaum** [comment]
Acrylic was replaced with mica in order to algin with Windows 11. There are a couple of different [themes](https://www.microsoft.com/store/productId/9N20KQ61LSFQ) available that bring back acrylic.
