### ISSUE TITLE
ERROR OPEN FOLDER "BOX" CLOUD

### ISSUE THREAD

**Issue by hangelini** [files-community/Files#6120]
### Description

AN ERROR AND SUBSEQUENT CLOSURE OF THE APPLICATION OCCURS WHEN ACCESSING THE "BOX" CLOUD FOLDER.
https://www.box.com/  
BOX IS SIMILAR IN USE TO ONEDRIVE.
![Sin título](https://user-images.githubusercontent.com/27622081/133346214-440dd8ec-a49d-4c78-b6f5-fa326469a78b.png)
[debug.log](https://github.com/files-community/Files/files/7165678/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7165680/debug_fulltrust.log)

### Expected behavior

MY USER IS AN ADMINISTRATOR. IT SHOULD WORK

### Files Version

V 2.0.0.0

### Windows Version

WIN 10

**Comment by gave92** [comment]
This issue should be fixed in 2.0.1
