### ISSUE TITLE
Multi-Selection indicator(checkbox)

### ISSUE THREAD

**Issue by junukwon7** [files-community/Files#6121]
### Description

After some procedure, the selection indicator works awkward.

### Steps To Reproduce

1. Select all files in the directory.
2. Drag them outside the files without releasing the LMB.
3. Drop them inside the directory you started. (which will make no change).

### Expected behavior

The selection indicator goes wrong. De-selected files are also marked as selected.
![image](https://user-images.githubusercontent.com/48399106/133353635-6dcf2762-84cf-4435-a66e-62a4716f0e55.png)

### Files Version

v2.0.0.0 (according to the files about)

### Windows Version

Windows 11 Pro Insider Preview 22454.1000

**Comment by yaichenbaum** [comment]
Merging with #6768
