### ISSUE TITLE
Multi-Selection indicator(checkbox) (different from the previous one)

### ISSUE THREAD

**Issue by junukwon7** [files-community/Files#6122]
### Description

An unexpected checkboxx apears after the procedure below.

### Steps To Reproduce

1. Multiselect files.
2. Click on one file in the selection.
3. Dag-drop immediately to the same file.

### Expected behavior

An unexpected checkbox appears.
![image](https://user-images.githubusercontent.com/48399106/133353279-68faeee2-48e2-4bd8-bb81-6f4c660149bb.png)
![image](https://user-images.githubusercontent.com/48399106/133353292-91fd7845-6d15-4825-bc7b-d3a145a43ae3.png)

### Files Version

v2.0.0.0 (according to the files about)

### Windows Version

Windows 11 Pro Insider Preview 22454.1000

**Comment by yaichenbaum** [comment]
@junukwon7 is this still an issue in the preview version? http://files.community/download/preview
