### ISSUE TITLE
Default Sorting Option

### ISSUE THREAD

**Issue by FlamenWolf** [files-community/Files#6123]
### Solution/Idea

Add an option to set default sorting options so every new folder open starts with that sorting.
Ex: Setting Sort by Name and Group by Type as default results in every new tab opened to be sorted by name and grouped by type. Any folders changed manually to something other than the default will stay as the manual sort (manual sorting takes priority over automatic/default sorting)

### Alternatives

none

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.0

### Windows Version

Windows 10

**Comment by gave92** [comment]
Thanks for this report. Could you try the following?
- Turn off "Enabled individual preferences for individual folders" in Files settings > Files and Folders
- Go to any folder and set desired sorting option
- Optional: turn "Enabled individual preferences for individual folders" setting back on
