### ISSUE TITLE
Context menu on offset

### ISSUE THREAD

**Issue by flumiie** [files-community/Files#6125]
### Description

The extra context menus on "More..." is offset up by one menu, only if I right-clicked a folder or a file near the bottom of the window. This might need some readjustments.

### Steps To Reproduce

1. Open Files Explorer
2. Un-maximize and shrink the Window enough to a decent size
3. Find a file or a folder that is roughly 40% to 50% above the absolute bottom of the Window (A bit tricky to reproduce, might need to be exact)
4. Right-click it and hover on "More..."
5. Check the sub-context menu position

### Expected behavior

Should be either lined up to the "More..." menu and not on offset, since it's really tricky to hover my cursor on the sub-menus

### Files Version

v1.9.12.0

### Windows Version

Windows 10 Pro 21H1 - build 19043.1165

### Relevant Assets

![context](https://user-images.githubusercontent.com/8995187/133403424-fdfcec65-5cb0-415b-9f78-4b39020b4d58.png)

**Comment by gave92** [comment]
Thanks for the report. Afraid this is not something we can fix ourself as looks like a WinUI issue.

**Comment by flumiie** [comment]
Haven't tested it on Windows 11, see if that's fixed later on when they launched it.
