### ISSUE TITLE
Tab Drag-and-Drop bugs

### ISSUE THREAD

**Issue by mangoepic** [files-community/Files#6126]
## 1. Dragging Tab out to another App
**Bugs:**
  1. **"invalid action"** symbol when dragging onto other applications
  2. It doesn't open a tab when dragging into vscode
![image](https://user-images.githubusercontent.com/71931749/133416390-61fcb8f3-be1a-45d9-824c-ffa99068730c.png)

## 2. Dragging Tab back into another window
**Bugs:**
 1. Dropping it anywhere on the right side does not work
 2. Dropping it onto the "+" opens the "open tabs" window. (Does not add tab and does not close window again)
https://user-images.githubusercontent.com/71931749/133416703-3aad1e42-9496-403f-b71b-3fefecb4cc7f.mp4

## 3. Adding Tab back in behaviour
**Bugs:**
 1. If you drop  it inbetween tabs they "move away" but the tab still gets added to the **front of the list**
 2. Dropping a tab directly on top of another does *not* move the tab "away"

Firefox behaviour: (I like this the most)
https://user-images.githubusercontent.com/71931749/133417730-13bbfeb8-a69a-4fb2-af31-ee59b465b3fc.mp4
Chrome behaviour:
https://user-images.githubusercontent.com/71931749/133417722-3231f113-ecff-4e1b-9065-3c3e297d563e.mp4

### Files Version

Version: 2.0.12.0 

### Windows Version

OS Version: 10.0.19043.1165

### Relevant Assets

https://user-images.githubusercontent.com/71931749/133415929-7e17ac6b-a80d-4472-9be8-ffd0ea8dbb2c.mp4

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
