### ISSUE TITLE
Feature: Add button to open properties from the Details Pane

### ISSUE THREAD

**Issue by MadafakinRio** [files-community/Files#6128]
## Requirements
- Feature: Add button to open properties from the Details Pane

**Comment by yaichenbaum** [comment]
We were thinking of adding a button that takes you to the properties window, but we can definitely look into adding this to the preview pane as well.

**Comment by yaira2** [comment]
We should definitely move forward with this but we need to finalize a design.

**Comment by ferrariofilippo** [comment]
@yaira2 isn't this a duplicate?

**Comment by yaira2** [comment]
@MadafakinRio this feature will be included in the upcoming v2.5.20 release.
