### ISSUE TITLE
Preview on PNG files not shown unless folder is opened in Explorer first

### ISSUE THREAD

**Issue by flackseven** [files-community/Files#6130]
### Description

No previews appear on PNG file icons.
![Screenshot 2021-09-15 153802](https://user-images.githubusercontent.com/78412508/133434897-7ddcd98c-03c4-4777-b935-832a6c9b86c5.png)

### Steps To Reproduce

1. Open any folder that contains png files
2. Set layout to Small/Medium/Large Icons

### Expected behavior

PNG file icons should have a preview

### Files Version

Version: 2.0.0.0 OS Version: 10.0.19043.1237

### Windows Version

Windows 10 Pro 21H1 19043.1237

**Comment by gave92** [comment]
Thanks for the report. Do those files have a preview in Windows Explorer?

**Comment by flackseven** [comment]
@gave92, yes, even with system "Photos" app as default

**Comment by gave92** [comment]
Thanks for confirming, also does the preview pane in Files show a preview for those?

**Comment by flackseven** [comment]
@gave92  Unlike the icons, it is displayed on the preview pane.

**Comment by michaelhthomas** [comment]
I'm having the same issue specific to PNG files, but after opening the same folder in Windows Explorer, then reloading the folder in Files, the thumbnails appear as normal. It's only when opening a folder for which thumbnails have not yet been generated that they don't load. JPG and other files, however, work just fine even when being opened for the first time.

**Comment by sebphillips** [comment]
+1

**Comment by luketxr** [comment]
+1

**Comment by soredake** [comment]
Having similar problem, but going to explorer does not helps.

**Comment by d2dyno1** [comment]
This issue should be resolved with #7881 @flackseven
