### ISSUE TITLE
FTP folder is empty.

### ISSUE THREAD

**Issue by JLoGukA** [files-community/Files#6131]
### Description

When I try to open ftp folder(smth like ftp://192.168.137.148:2121) in LAN, app shows empty folder though it's not empty.
![image](https://user-images.githubusercontent.com/23702864/133448607-8e36e53d-27b6-4eaf-bf46-179e90969e53.png)

### Steps To Reproduce

1. Open any ftp server on your network
2. Type ftp address in the app

### Expected behavior

Maybe app should show something in ftp folder?

### Files Version

Version: 2.0.0.0

### Windows Version

OS Version: 10.0.22454.1000 (Windows 11)

### Relevant Assets

[debug_fulltrust.log](https://github.com/files-community/Files/files/7170756/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7170757/debug.log)

**Comment by ilovefreesw** [comment]
Same issue on Windows 11 I am getting.

**Comment by KosmosisDire** [comment]
I am having this problem as well

**Comment by yaichenbaum** [comment]
@JLoGukA is this still an issue in the preview version? https://files.community/download/preview

**Comment by JLoGukA** [comment]
@yair100 no it is not. App works perfectly with ftp on Windows 11 22621.1. Thank you for your work!
