### ISSUE TITLE
Cursor Change when Hovering Over a File Icon

### ISSUE THREAD

**Issue by WinObs** [files-community/Files#6132]
### What's the Problem?

There is no change when a mouse cursor hovers over an icon

### Solution/Idea

Something similar to how File Explorer in Windows 10/11 works with this would be a perfect solution - just an indicator that you are not just in open space but can interact with the file icon.

### Alternatives

None

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.0

### Windows Version

Windows 11 Beta Channel Build 22000.184

### Additional comment

P.S. Love the 2,0 updates - now my default File Explorer on my system

**Comment by yaichenbaum** [comment]
Thank you for opening this issue, merging with #3544 so that we can track it in on place 🙂
