### ISSUE TITLE
Unexpected close

### ISSUE THREAD

**Issue by angellucruz16** [files-community/Files#6133]
### Description

Sometimes when im trying to open folders it shutdown  so i have to use right click and select "open folder" then it would work.
And then, when i want to drag an archive to another web or app, it never does. Like its not possible. 
The last issue i have to deal with is when y want to drag an archive i have to do double click on it, and i think is annoyng, i would prefer just clicking and dragg it

### Steps To Reproduce

1. Click on any folder to open
**2. it shut down**
3. Open again the app
4. right click on the foler
5. select "open"
.
1.Click on the file i want to dragg
2.click again and drag it
**3. it doesn't export the file**
4. then i have to use the orriginal windows doument
.
1.Click and dragg on the file
**2. it doesn't dragg**
3. click again on the file
4. click again and then dragg it
5. the file would dragg successfully

### Expected behavior

I expect that i could open files by clicking on them, without using the right click.
Also expect that could be able to export files by draggying them outsite the app
Finally, i expect to dragg files witouth clicking two times, just hold click and dragg. 

### Files Version

v1.5.0.0

### Windows Version

Windows 10 19043.1165

**Comment by gave92** [comment]
Thanks for the report. All the issues reported here should be fixed in Files v2.
