### ISSUE TITLE
Version 2.0.0.0 context menus all too short and have to scroll

### ISSUE THREAD

**Issue by TheAndyMac** [files-community/Files#6135]
### Description

Just had version 2.0.0.0 downloaded and now the right-click context menus ALL are truncated length and scroll, even though plenty of space for the full menu to show - this even if the ".... more" option is enabled or disabled.

### Steps To Reproduce

1.Right click on any file
2.Context menu shows list, but truncated and needs to be scrolled to get at all items in the list

### Expected behavior

Context menu should not scroll UNLESS the resulting menu is too large for the window or screen

### Files Version

v2.0.0.0

### Windows Version

Windows 10 21H2

### Relevant Assets

![image](https://user-images.githubusercontent.com/12783814/133518895-7e528581-e66f-41d6-afcf-1daa8ece5d71.png)

**Comment by gave92** [comment]
Merging with #6025
