### ISSUE TITLE
Preview Pane displays nothing when no item is selected

### ISSUE THREAD

**Issue by rigorimpossible** [files-community/Files#6137]
### What's the Problem?

When nothing is selected, the preview pane just displays no item selected

### Solution/Idea

When nothing is selected, it should instead preview/display details of the folder like the number of files, date created, etc.

### Alternatives

display folder details so it wouldn't look empty.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.0.0.0

### Windows Version

10.0.22000.168

### Additional comment

![image](https://user-images.githubusercontent.com/1589022/133560598-28d871a4-fa70-4b96-bc3b-ef41f335bb1c.png)

this is how it looked in File Explorer

**Comment by gave92** [comment]
\+ @winston-de

**Comment by yaira2** [comment]
Merging with #6724
