### ISSUE TITLE
Create new folder with right click on desktop

### ISSUE THREAD

**Issue by 34Alperen34** [files-community/Files#6138]
### Solution/Idea

There was a problem with my file manager and I cannot create a new folder with a right click on the desktop. I want to use your application for this, but this application cannot create a new folder on the desktop. Could you add this feature for me? because the error I get is very annoying, I beg you, it's not an exaggeration

### Alternatives

.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Sürüm: 2.0.0.0 OS Version: 10.0.19044.1237

### Windows Version

21H2 120.2212.3530.0

**Comment by gave92** [comment]
I can't reproduce the issue on my device (I can create folders on the desktop with no problems). Could you:
- Add a screen recording of the steps taken
- Upload the app's two debug files?

Thanks!
