### ISSUE TITLE
Network drives mapped through Files don't appear

### ISSUE THREAD

**Issue by starkgate** [files-community/Files#6139]
### Description

1. Network drives mapped through Files don't appear in the list of drives (Home)
2. After noticing this, I tried mapping the drive again through Files, which gives me an error. I then opened the old Windows Explorer and tried to map the network drive from there. For Windows Explorer, the drive letter I used in Files wasn't in use. Mapping the network from Windows Explorer gives me this display in Files, with each network drive I mapped duplicated 4 times:

![ApplicationFrameHost_2mtBHm45by](https://user-images.githubusercontent.com/12874678/133575621-b5196098-3dd3-46e3-89f6-a85219c341ce.png)

My hypothesis is that the number of times each drive is duplicated matches the number of times the computer was restarted / how many times the Files app was restarted.

### Expected behavior

The same behavior as Windows Explorer is expected: map a network drive, it appears in the Home display (once).

### Files Version

Version: 2.0.12.0 OS Version: 10.0.19043.1165

### Windows Version

Windows 10 Pro 21H1 19043.1165

**Comment by josh-65** [comment]
Have you restarted files and/or your Computer to see if there still there?

**Comment by starkgate** [comment]
I had a crash that is probably unrelated and the duplicates don't appear anymore.

**Comment by Josh-65** [comment]
I presume this isnt an issue anymore so i will close this. If it is please open a new issue.
