### ISSUE TITLE
Search does work buggy

### ISSUE THREAD

**Issue by maxpetrgit** [files-community/Files#6140]
### Description

1. https://i.imgur.com/rEsHjqU.png
2. nothing found https://i.imgur.com/pRxLmId.png

### Expected behavior

The same bug in v1.5

### Files Version

2.0

### Windows Version

21H2 Build 22000.184

**Comment by josh-65** [comment]
There doesn't seem to be any issue . You entered a search term it found files that you highlighted (Other files could be from metadata and file content). And when you searched blank it shows nothing like it should.

**Comment by gave92** [comment]
I'm assuming the two pictures are before and after hitting "Enter" to search, when you do the search box is gets cleared.

**Comment by gave92** [comment]
@maxpetrgit Any difference if you look for "*naviga*" (notice the asterisk before and after the search term)?
