### ISSUE TITLE
Support for Icon Packs in Files

### ISSUE THREAD

**Issue by mangoepic** [files-community/Files#6142]
### What's the Problem?

Lots of people want to costumise their windows icons

### Solution/Idea

Files already has Theme support - so it would be really cool to also have a support for icon packs!

It would give users a more safe, easy, intuitive and functional alternative to modifying their system files. (People going to this extend shows the demand)

There could be another section like "Themes" for Icon Packs.

![image](https://user-images.githubusercontent.com/71931749/133632259-c709e735-0d31-46ef-96c9-f3c2f0d4e6fb.png)

Related but different: #5031 | I'm looking for more of a simple "packed" approach here.

### Alternative

**Adding skinning support for the icons on the Start page (+folders) via Themes**

(Modifying system Files)

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to import Icon packs | Must |
| This proposal will allow end users to switch Icon packs | Must |
| This proposal will add an Icon packs section | Must |
| This proposal will add an Icon pack documentation | Should |

### Files Version

Version: 2.0.12.0 

### Windows Version

OS Version: 10.0.19043.1165

**Comment by josh-65** [comment]
Icon packs can be applied windows wide by external programs or manual changing file/folder icons in file explorer. I don't think it would be beneficial to have it apply to only files. Probably would also be a mess to code in.

**Comment by mangoepic** [comment]
> Probably would also be a mess to code in.
Aren't there already preview loading-icons?

Also I think for starters it would be enough to be able to customize the icons on the home screen + folders.
![image](https://user-images.githubusercontent.com/71931749/133645141-0f8ed60c-db79-426c-ade5-85c93e8d4111.png)

The file icons themselves could just stay the same.

[Regarding that in the future it could be maybe nice to have something like an icon pack which contains images + a iconpack.json file  where you can assign images to file extensions but its not what I'm asking for here]

**Comment by josh-65** [comment]
There all pulled from windows. You can change them in windows. For the drive ones there are properly external programs/tutorials to change them. Your home page folder are from your user directory and can be changed there (C:/users/<your username>)

I don't know what you mean by "loading-icons". if you mean the spin circle that's a icon added by WinUI.

**Comment by mangoepic** [comment]
these:
![image](https://user-images.githubusercontent.com/71931749/133650282-2bf1143a-81f0-47c5-b52b-bf86afa1401e.png)

Yes one can change system icons but it's really hacky and not guaranteed to work / might damage windows ... also its a lot of a hassle, you need to go through registry classes etc. Not great if you just want a quick refresher for the eyes

**Comment by yaichenbaum** [comment]
Icon packs are already supported...

**Comment by mangoepic** [comment]
But only natively in windows not customly in Files

**Comment by wasi-master** [comment]
Yeah I would also like to have a custom feature, manually changing hundreds or even thousands of icons manually is not viable.

**Comment by yaichenbaum** [comment]
We don't have plans for building icon packs into Files.

**Comment by wasi-master** [comment]
Okay no worries, I'll manually use FileTypesMan to do it for the files I see the most thanks
