### ISSUE TITLE
Right menu crash

### ISSUE THREAD

**Issue by coxine** [files-community/Files#6143]
### Description

When hovering on the secondary menu of the right menu, such as “Open with”, the menu will crash
当打开右键菜单的二级菜单，如“打开方式”时，菜单会闪退

### Steps To Reproduce

1. right click on a file
2. hover the mouse on “Open with”
3. The right menu crash

### Expected behavior

The right menu won‘t crash when hovering on the secondary menu.
鼠标打开二级菜单时右键菜单不会闪退

### Files Version

v2.0.0.0

### Windows Version

Windows 11 Dev 22454.1000

### Relevant Assets

https://tgcos-my.sharepoint.com/:v:/g/personal/yxj_tgcos_onmicrosoft_com/ERyhp5W5SpFEi25uscDU_P0BlnzZMCvz83-cGS5KYdd5LA?e=cqB8hD

**Comment by gave92** [comment]
Thanks for the report. Please upload the app's debug files to the issue description.

**Comment by gave92** [comment]
Thanks for the report. Known issue caused by recent Windows 11 build (unrelated to Files)
