### ISSUE TITLE
Drag and Drop from 7zip

### ISSUE THREAD

**Issue by soraphis** [files-community/Files#6145]
### Description

Extracting a folder from a zip archive (using 7zip) into files, shows the "drop here" overlay, and 7zip actually extracts something, but afterwards the folder is not copied to the target location (as in windows explorer).

### Steps To Reproduce

1. Open some zip file with 7zip
2. Open some (empty) folder in Files.
3. Drag and drop from 7zip into files.

### Expected behavior

The zip content appears in the folder opened in files

### Files Version

v1.5

### Windows Version

Windows 10, Version 20H2 Build 19041.329

**Comment by gave92** [comment]
Thanks for the report. This issue should be fixed in Files v2.
