### ISSUE TITLE
Double Click to go back

### ISSUE THREAD

**Issue by mokshsinghji** [files-community/Files#6146]
### What's the Problem?

To go back with my mouse only, I have to go all the top of the explorer and press the up icon

### Solution/Idea

It would be nice if you could double click on any place that is not already being used and it would go to the previous folder.
Explorer++ has this feature and I love it but I like the looks of Files

### Alternatives

Maybe there could be a back icon on the left side to quickly go back to the previous folder but it isn't such a good solution.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers and end-users to accomplish navigating quicker | Should |

### Files Version

v2.0.0.0

### Windows Version

Windows 11 Pro 21H2 22000.184

**Comment by gave92** [comment]
Merging with #5090, #2355
