### ISSUE TITLE
Rightclick Context menu fix

### ISSUE THREAD

**Issue by ironmankaz** [files-community/Files#6148]
### Description

When I go to the nested option in the right click context menu like Sort By, Extract the context menu closes, It is very problematic, So I request the amazing developers to fix it.

### Expected behavior

I thought it would open the sort by or extract option, but it just closes the context menu.

### Files Version

v Version: 2.0.0.0 

### Windows Version

OS Version: 10.0.22458.1000

**Comment by gave92** [comment]
Thanks for the report. Issue due to latest windows 11 build (not a Files issue)
