### ISSUE TITLE
Bad user experience

### ISSUE THREAD

**Issue by htmyname** [files-community/Files#6151]
### What's the Problem?

It is normal for a Windows user to be adapted to using Win + E to open the file explorer, having to click on the app makes you not want to use it, I have been installed for a long time and I always check if they have already added that option

### Solution/Idea

replace default Win + E (windows explorer)

### Alternatives

Or add any other key combination please

### Files Version

2.0

### Windows Version

Microsoft Windows [Version 10.0.19043.1202]

### Additional comment

nothing else

**Comment by yaichenbaum** [comment]
@htmyname I think this should solve the issue 🙂 
https://files-community.github.io/docs/#/articles/configure-win-e
