### ISSUE TITLE
Replace Default File Explorer with Files 

### ISSUE THREAD

**Issue by thisisibini** [files-community/Files#6152]
### What's the Problem?

Windows 11 Start Folders File Explorer

### Solution/Idea

Replace file explorer with files app on windows completely. if possible when we click on folder in windows 11 start menu of file explorer. instead of file explorer. Files app should open. i am using this files app for daily use its nice looking and fast compare to file explorer. 

Thanks for making such a reliable app!

### Alternatives

Replacement of File Explorer with Files Completely!

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

v2.0.0.0

### Windows Version

New Windows 11

**Comment by yaichenbaum** [comment]
@thisisibini please refer to the documentation https://files-community.github.io/docs/#/articles/replace-file-explorer.
