### ISSUE TITLE
Real-Time Copy/Move Percentage

### ISSUE THREAD

**Issue by askfriends** [files-community/Files#6153]
### What's the Problem?

It doesnt show copy percentage in real time

### Solution/Idea

Please add real-time copy/move percentage so that we can see how much data is copied/moved and how much is remaining, Currently it only shows Percentage when a file is copied successfully while copying multiple files together.

Also add copy/move speed in MB/sec just like Windows.

### Alternatives

Make it just like Windows copy/move window

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

v1.5.0.0

### Windows Version

Windows 10 21H1

### Additional comment

Do this asap. thanks

**Comment by josh-65** [comment]
The real time percentages have been added for v2 coming around the start of October. The other features have been discussed in #4811

**Comment by askfriends** [comment]
> The real time percentages have been added for v2 coming around the start of October. The other features have been discussed in #4811

Thats a good news, unfortunately i have installed Files second time in a hope that this would be much improved than before but its not, It still freezez and restarts when i copy to usb drive, its not reliable, which compells me to uninstall it and go to old explorer

**Comment by josh-65** [comment]
You properly should until v2 is out

**Comment by askfriends** [comment]
> You properly should until v2 is out

Alright..btw it shows v2 in in changelog MS Store but when i click on update it doesnt update.
Here is SS
![files](https://user-images.githubusercontent.com/2517219/133823901-a3568458-5ca3-4619-bbd0-60bb9828f32e.jpg)

**Comment by josh-65** [comment]
Its not out yet coming about 4th October

**Comment by askfriends** [comment]
> Its not out yet coming about 4th October

Alright bro, thanks for ur time and waiting eagerly for the next release.

**Comment by yaichenbaum** [comment]
> > You properly should until v2 is out
> 
> Alright..btw it shows v2 in in changelog MS Store but when i click on update it doesnt update.
> Here is SS
> ![files](https://user-images.githubusercontent.com/2517219/133823901-a3568458-5ca3-4619-bbd0-60bb9828f32e.jpg)

2.0 is availible on demand, try updating manually.
