### ISSUE TITLE
Bug: Can't rename network drives

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#6154]
### Description

When I right click a network drive then change its name the PowerShell prompt comes up but it doesn't rename.

### Requirements 

- Rename should work as expected

### Files Version

2.0.12.0

### Windows Version

11.0.22454.1000

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7186251/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7186252/debug_fulltrust.log)

**Comment by erbmur** [comment]
I can confirm that this is an issue.

**Comment by jeriss-cloud-center** [comment]
I confirm the issue as well

![image](https://user-images.githubusercontent.com/87424739/176992605-46d5cb94-a7ed-42b4-8bce-ac9a8b796c1b.png)

**Comment by Starstrike** [comment]
I wanted to add to this that for some reason Network Drives show the drive letters twice. Renaming gets rid of them for that session but if Files is restarted, they're back. See screenshot.

![image](https://github.com/files-community/Files/assets/1996734/d74c9a28-9719-4f80-92ed-070de42c0586)

Would prefer that the Network Drives show just like Physical ones.

**Comment by MattJFX** [comment]
> I wanted to add to this that for some reason Network Drives show the drive letters twice. Renaming gets rid of them for that session but if Files is restarted, they're back. See screenshot.
> 
> ![image](https://user-images.githubusercontent.com/1996734/245530971-d74c9a28-9719-4f80-92ed-070de42c0586.png)
> 
> Would prefer that the Network Drives show just like Physical ones.

I am also getting this issue. Network drive names are showing duplicate drive letters, with renaming only lasting the current session.

**Comment by hishitetsu** [comment]
I'm working on this.
