### ISSUE TITLE
Customizable folder icons

### ISSUE THREAD

**Issue by soeoeb** [files-community/Files#6156]
### What's the Problem?

missing option for costumizing folder icons

### Solution/Idea

Hi, thanks for your great file explorer! I hope MS will develope something like that or hire you int he future :) Unfortunately I miss an option to costumize my folder icons. If you could add this feature in the future, I'd love it! :)

LG

### Alternatives

no, really but idk

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.0.0.0 OS Version: 10.0.19042.1237

### Windows Version

Windows 10 Home 20H2 19042.1237

**Comment by gave92** [comment]
Thanks a lot for the feedback. Custom icons is something we're looking into -> #1015
