### ISSUE TITLE
app told me it ran into a problem and wanted me to report it

### ISSUE THREAD

**Issue by ControlAlternateDelete** [files-community/Files#6157]
### Description

no idea what is wrong, the app just shut down after I clicked on a shortcut link

### Steps To Reproduce

Not sure if this problem can be reproduced. All I did was attempt to launch a shortcut.

### Expected behavior

I expected it to launch the application the shortcut was leading to

### Files Version

v1.5.0.0

### Windows Version

Windows 10 20H2 19042.1165

### Relevant Assets

[debug.txt](https://github.com/files-community/Files/files/7187197/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/7187199/debug_fulltrust.txt)

**Comment by gave92** [comment]
Thanks fir the report. This issue should be fixed in Files v2.
