### ISSUE TITLE
Opening old folders (or ZIP files) is changing their modified date

### ISSUE THREAD

**Issue by SHADOW-XIII** [files-community/Files#6158]
### Description

When I open an old folder in Files, one that I never opened before in Files, it changes the folder "modified date" date.
No file in the folder has been modified, no hidden/system file exists but the folder's modified date is changed.
Just browse to it in Files and open it like normal folder.

Opening same folder first in normal Windows Explorer does not change the date.

### Steps To Reproduce

Find an old folder that you never opened before in Files, preferably with some files.
Ideally first check with Windows Explorer it's date to confirm: Open location of the folder, set View by "Details" and order by "Date modified".

Open the folder in Files and see if the modified date has changed.

### Expected behavior

Opening a folder in Files should not change its modified date.

### Files Version

2.0.0.0

### Windows Version

21H1 19043.1165

**Comment by SHADOW-XIII** [comment]
Also seems to happen when opening ZIP file in Files.

**Comment by generalguy41** [comment]
To add to this, I believe it's happening when the auto layout change occurs.

**Comment by yaira2** [comment]
Is this still an issue in v2.4?
