### ISSUE TITLE
Calculate and display directory size

### ISSUE THREAD

**Issue by ketonik** [files-community/Files#6160]
### What's the Problem?

I don't know what the size of any folder is in any view

### Solution/Idea

Like macOS has been doing for 30 years, setting to calculate size of all folders, so that in details view and in the preview pane it will display the folder size, if a music folder has 22GB of tunes in there, I want details view to show me a size column  and this will be numerical in either MB GB or TB.

We've has SSD's on SATA and NVMe for years now, they are fast enough to calculate size of folder contents.

### Alternatives

use a real OS...macOS

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

1.5

### Windows Version

Windows 11 Pro 21H2 22000.194

![Screen Shot 2021-09-18 at 14 44 17](https://user-images.githubusercontent.com/49221849/133879508-cc4f0c72-fa1a-4367-826d-ef4d62c9640f.png)

**Comment by gave92** [comment]
Merging with #3944
