### ISSUE TITLE
Ability to reorder sidebar sections

### ISSUE THREAD

**Issue by ketonik** [files-community/Files#6161]
### What's the Problem?

Freedom to place sidebar items where needed

### Solution/Idea

select drag Drives to the top above favourites, also removal of cloud drives. 

### Alternatives

no solution

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

v1.5

### Windows Version

Windows 11 Pro 21H2 22000.194

**Comment by gave92** [comment]
Files v2 adds the ability to show/hide sidebar sections.

**Comment by yaichenbaum** [comment]
@ketonik thank you for opening this issue, this goes a little beyond the customization we're planning to offer. You will however be able to rearrange favorites starting in Files v2.
