### ISSUE TITLE
Details view Tag column

### ISSUE THREAD

**Issue by ketonik** [files-community/Files#6162]
### What's the Problem?

need to colour files or folders

### Solution/Idea

in macOS the Finder has a Tag column, in the contextual menu of a selected file or folder the user can select from several colours this would in the olden days colour the background of the row for the time, now days they just put a coloured dot in the tag column, not ideal but at least we can visually colour items of importance.
Critical to a project id tag them red, amber or currently working on in green...

### Alternatives

some third party tools with add an invisible folder icon file, but this aint ideal if the folder or file is on a network share, it colours the folders for everyone, kinds pissed people off init.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

v1.5

### Windows Version

Windows 11 Pro 21H2 22000.194

![Screen Shot 2021-09-18 at 14 46 43](https://user-images.githubusercontent.com/49221849/133879472-44e5b4b4-1ed0-4fe7-aaca-aa953087daa7.png)
![Screen Shot 2021-09-18 at 14 47 37](https://user-images.githubusercontent.com/49221849/133879474-d6df264e-0e3f-4589-8b6e-c2f4586fb90f.png)
![Screen Shot 2021-09-18 at 14 47 53](https://user-images.githubusercontent.com/49221849/133879478-4b5bc308-0edd-4f36-8505-1e8b4a63ab31.png)

**Comment by gave92** [comment]
Tags were implemented in Files v2 💪
