### ISSUE TITLE
Disclosure triangles to view contents of folders in Details View

### ISSUE THREAD

**Issue by ketonik** [files-community/Files#6163]
### What's the Problem?

Unable to view contents of multiple folders in same window.

### Solution/Idea

Windows file browser apps limit user to view only contents of inside one folder. More often than not I need to view the contents of more than one folder in details view and i need to see the folder size of each...maybe im working on a design with a superseded revisions folder inside it, i need to see all the files in the root folder as well as any sub folders. macOS been doing this for 30 years..

### Alternatives

M$'s bright idea is treeview in a sidebar which is causing the user to constantly resize the horizontal width of the sidebar to make the sub folders visible...this is a legacy M$ early 1990's concept, it never worked well then and its not helping users now.

Still you can't view the same column details for sub folder...basically its useless...macOS Finder shits all over M$'s File browser API's, and its the reason all 3rd party attempts have the same basic configuration limitations, maybe new Windows App Platform has a modernised toolset for 3rd parties?

see macOS Finder screenshots, its List View (what windows calls Details view-but their list view is redundant because its uselessly void of any valuable data-ie Details View in Windows should be renamed List view and then remove details view)

notice this list view is one window with selectable columns which are displayed for any sub folders...even folder size is displayed:

![Screen Shot 2021-09-18 at 14 47 53](https://user-images.githubusercontent.com/49221849/133879849-af8b6f68-157b-425c-8102-82c2a20771bf.png)
![Screen Shot 2021-09-18 at 14 44 17](https://user-images.githubusercontent.com/49221849/133879871-2e82ed29-84a4-4115-a264-f2004f36b136.png)

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

v1.5

### Windows Version

Windows 11 Pro 21H2 22000.194

**Comment by gave92** [comment]
Merging with #1928
