### ISSUE TITLE
QuickLook feature like macOS Finder

### ISSUE THREAD

**Issue by ketonik** [files-community/Files#6164]
### What's the Problem?

Details View but want to see a thumbnail of icon

### Solution/Idea

macOS Finder List View, that's Details view for the boneheads at M$ who convolute everything, obviously the image icon, app icon or folder is small and not able to be well perceived.

So hit Spacebar and a large resizable overlaying window displays the icon, typically an image, screenshot or video or audio file.
use the down arrow keys to view the next filer/folder, hit spacebar again to close the quicklook preview...the window can be moved and placed to the side and will remain visible until the user hits spacebar...its super handy if its a text document, that you want to view while typing in a forum or such instead of actually opening the document or image.

macOS has had this for about 15 years, spoilt by Apple or M$ are just lazy and don't give a fsck about users with their primitive legacy POS OS..eh.

Screenshot is quickview on a app but probably a photo would have been a better example. 
![Screen Shot 2021-09-18 at 14 50 22](https://user-images.githubusercontent.com/49221849/133880094-91b0a559-bbf1-48b3-b6ed-9e78d1bb9ed9.png)

### Alternatives

Nothing from M$, maybe 3rd party solution copy of Quicklook, IDK

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

v1.5

### Windows Version

Windows 11 Pro 21H2 22000.194

**Comment by gave92** [comment]
You can install the [QuickLook app](https://www.microsoft.com/en-us/p/quicklook/9nv4bs3l1h4s#activetab=pivot:overviewtab) which works with Files.
