### ISSUE TITLE
reposition columns

### ISSUE THREAD

**Issue by ketonik** [files-community/Files#6165]
### What's the Problem?

Can't position columns in Details View

### Solution/Idea

I typically have Name then size then date modified columns in that left to right order...im unable to click and drag any column to the position I want...maybe this isnt implemented yet...

### Alternatives

unselecting the items in the column contextual menu then reenabling them in the order desired isn't doing as i hoped.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

v1.5

### Windows Version

Windows 11 Pro 21H2 22000.194

**Comment by gave92** [comment]
Thanks for the suggestion! Tracking in #4643
