### ISSUE TITLE
Search results no size data

### ISSUE THREAD

**Issue by ketonik** [files-community/Files#6166]
### Description

results of a filtered search 'fbx' displayed in details view does not show any value for the size of file.
Right Click properties shows 0 bytes, the status bar doesn't show any info for the file selected, there should be a path bar displayed so the user can double click on the directory to view the file inside. The context menu doesn't have an item to show the file in its directory in a new tab...only copy location is provided...user has to do all the manual work cre44ating a new tab then pasting the path in the top address field then user deletes the text of the filename before hitting enter to open thje directory the file is in.

### Expected behavior

Need to find fix as to who its not computing the file size and why even the get info box doesn't show the correct file size.
Need to see full path of file or folder in a status bar...not as a column in the details window. the path bar should show folder icon for users to double click or command click to open in a new tab.
![2021-09-18 15_31_16-Files](https://user-images.githubusercontent.com/49221849/133880729-9aceca07-0b73-4688-a183-9b35462d6fd0.png)

![Inked2021-09-18 15_33_27-Properties ‎- Files_LI](https://user-images.githubusercontent.com/49221849/133881529-df4980e8-053a-420b-8761-f7c12e794ca3.jpg)

### Files Version

v1.5

### Windows Version

Windows 11 Pro 21H2 22000.194

**Comment by josh-65** [comment]
This has been added in the current insider builds and will be available for v2.
