### ISSUE TITLE
Alow us to do commands in the search bar.

### ISSUE THREAD

**Issue by Zubbbz** [files-community/Files#6168]
### What's the Problem?

N/A

### Solution/Idea

Allow us to run commands from the address bar similar to how we can type "cmd" in there and it will open a cmd prompt in the current directory. Built in explorer supports this.

### Alternatives

just use the default built in explorer app.

### Priorities

| Capability | Priority |
| :---------- | :------- |
|This proposal will allow end users to run commands from the address bar in the current directory|Must|

### Files Version

Version: 2.0.0.0

### Windows Version

21H1 Build 19043.1237

**Comment by gave92** [comment]
Merging with #5677
