### ISSUE TITLE
When multiselect is active, the double-click actions will not work.

### ISSUE THREAD

**Issue by dolorosus** [files-community/Files#6169]
### Description

When multiselect is active, the double-click actions will not work.

This behavior is different from that of Windows Explorer. 
If this behavior is  tintended, please traet this as a c&e request.

### Steps To Reproduce

1. turn on multiselect
2. double click on folder

### Expected behavior

When double-clicking, all selections are removed and the double-click action is executed for the current object.

### Files Version

2.0.0.0 

### Windows Version

 10.0.19043.1237

**Comment by Josh-65** [comment]
Merging with #6959
