### ISSUE TITLE
Right click menu alterations

### ISSUE THREAD

**Issue by Zubbbz** [files-community/Files#6170]
### What's the Problem?

Cant access all of the things I might want when I right click an item.

### Solution/Idea

At the bottom of the right click menu add a button for the original one, or in settings. Also, could add customization for items and choose what will and wont appear in the right click menu.

### Alternatives

Add an option in the settings to toggle files custom one, or the default windows one.

### Priorities

| Capability | Priority |
| :---------- | :------- |
|Add a button at the bottom of the files right click menu|Must|
|Add a toggle in settings for files app custom right click menu or default windows|Must|
|Add customization for items in the right click menu|Should|

### Files Version

Version: 2.0.0.0

### Windows Version

OS Version: 10.0.19043.1237

**Comment by gave92** [comment]
Items from explorer menu are added at the bottom of the context menu (you need to scroll to see them). If they are not there please upload the app's debug files.

**Comment by cleuton4k** [comment]
what I am asking is to add a button in the app settings to show the compact or expanded context menu (as in version 1.5) 

https://drive.google.com/file/d/1jQgJfvRkM2dBf096jwpBrGo43ditF5SM/view?usp=sharing

**Comment by yaichenbaum** [comment]
> what i'm asking is to add a button in the app settings to show the context menu compact (same as in version 2.0) or expanded (like in version 1.5) . because it's annoying to have to keep scrolling down.
> 
> https://drive.google.com/file/d/1jQgJfvRkM2dBf096jwpBrGo43ditF5SM/view?usp=sharing

The issue where you have to scroll down is not the intended design and we hope to have a fix in a future build.
