### ISSUE TITLE
The tab loading indicator keeps loading infinitely

### ISSUE THREAD

**Issue by cleuton4k** [files-community/Files#6171]
### Description

when opening, the APP keeps loading infinitely and only stops when I click the refresh button.

### Expected behavior

open the APP and load quickly

### Files Version

2.0.12

### Windows Version

Edição	Windows 10 Pro Versão	21H1 Instalado em	‎19/‎06/‎2021 Compilação do SO	19043.1237 Experiência	Windows Feature Experience Pack 120.2212.3530.0

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7191981/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7191982/debug_fulltrust.log)

https://drive.google.com/file/d/1Vpk2_Y1Y33jpnLPkThn2n-69XAha5AU8/view?usp=sharing

**Comment by gave92** [comment]
Thanks for the report. Looks like it's an issue with the loading indication, the folder is actually loaded correctly.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #6273.
