### ISSUE TITLE
some menus are dimmed

### ISSUE THREAD

**Issue by cleuton4k** [files-community/Files#6172]
### Description

some menus are dimmed

### Expected behavior

shows the menus perfectly

### Files Version

2.0.12

### Windows Version

Windows 10 Pro Versão	21H1 Windows Feature Experience Pack 120.2212.3530.0

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7192000/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7192001/debug_fulltrust.log)

https://drive.google.com/file/d/1CEh_1oDr1OsbiRWoRnms_fMmR4l47ItP/view?usp=sharing

**Comment by gave92** [comment]
Thanks for the report. This appears to be a WinUI issue (@yair100 confirm?)

**Comment by yair100** [comment]
> Thanks for the report. This appears to be a WinUI issue (@yair100 confirm?)

It looks like it's a WinUI issue, the good news is that it seem to be resolved in Windows 11.
