### ISSUE TITLE
add an option to expand the context menu

### ISSUE THREAD

**Issue by cleuton4k** [files-community/Files#6173]
### Solution/Idea

add an option to expand the context menu, as it is annoying to have to keep scrolling to see all the menu options.

### Alternatives

add the settings a button to show the compact or expanded context menu.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.0.12

### Windows Version

Windows 10 Pro Versão	21H1 Windows Feature Experience Pack 120.2212.3530.0

**Comment by gave92** [comment]
Thanks for the report. Unfortunately there are currently some WinUI bug preventing us from doing it.
