### ISSUE TITLE
add checkboxes to select items.

### ISSUE THREAD

**Issue by cleuton4k** [files-community/Files#6174]
### Solution/Idea

add checkboxes to select items.

### Alternatives

add the option to show checkboxes for selecting items.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.0.12

### Windows Version

Windows 10 Pro Versão	21H1 Windows Feature Experience Pack 120.2212.3530.0

### Additional comment

https://drive.google.com/file/d/13iDKxjOdE1dT8y76ZPjx26r2UnanvOHV/view?usp=sharing

**Comment by josh-65** [comment]
There are selection option in the top right ![image](https://user-images.githubusercontent.com/26977075/133927994-4ad21ea4-d7c7-4a9d-850c-ca570c32264c.png), then enable multi select

**Comment by cleuton4k** [comment]
when multi selection mode is enabled i cannot open folders and files.
