### ISSUE TITLE
add program icons to context menu

### ISSUE THREAD

**Issue by cleuton4k** [files-community/Files#6175]
### Solution/Idea

add program icons to context menu

### Alternatives

add program icons to context menu, programs like 7zip, format factory...

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.0.12

### Windows Version

Edição	Windows 10 Pro Versão	21H1 Instalado em	‎19/‎06/‎2021 Compilação do SO	19043.1237 Experiência	Windows Feature Experience Pack 120.2212.3530.0

### Additional comment

https://drive.google.com/file/d/1GUcxVDriSeiTDPRx32HidbTxMVbTZmG8/view?usp=sharing

**Comment by gave92** [comment]
Merging with #3834
