### ISSUE TITLE
Crash when open folder on 1809

### ISSUE THREAD

**Issue by 23Bluemaster23** [files-community/Files#6176]
### Description

when I try to open any folder, it keeps loading and then the program closes abruptly while an error window appears.

### Steps To Reproduce

1. Open the program
2. I try to open a folder
3. remains charging
4. an error window pops up
5. the program closes

### Expected behavior

to open the folder and show me the files

### Files Version

v2.0

### Windows Version

Windows 10 Enterprise LTSC

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7192241/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7192242/debug_fulltrust.log)

**Comment by gave92** [comment]
Issue present on 1809, error when debugging is `Unable to cast object of type 'Windows.System.DispatcherQueue' to type 'Windows.System.IDispatcherQueue2'.`

**Comment by yaichenbaum** [comment]
@23Bluemaster23 this issue should be resolved with #6180.
