### ISSUE TITLE
Compatibility with windows default explorer app list

### ISSUE THREAD

**Issue by yevon** [files-community/Files#6178]
### What's the Problem?

Add compatibility with windows 11 default file explorer settings

### Solution/Idea

If you try to set Files as your default file browser, you need to modify the register. It would be nice adding compatibility with the standard way to do it on windows, in the settings app in set default apps. If you try to do it, you don't get any prompt to use Files, it just redirects you to the windows store.

![image](https://user-images.githubusercontent.com/121157/133931550-8f0cffdf-1bc1-4827-98b0-6c78523649a3.png)

### Alternatives

An alternative would be to add an option to the settings for allowing doing that, by directly modifying the windows registry, allowing to undo the change if needed.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.0.12.0

### Windows Version

Windows 11

**Comment by gave92** [comment]
Windows does not support changing the default file explorer (that's why the need of a registry edit). A settings page to do this is being added in #6107.
