### ISSUE TITLE
App Closes

### ISSUE THREAD

**Issue by Wygzzz** [files-community/Files#6179]
### Description

When I tried to delete a paste on my Program Files (x86) the app suddenly closed.

### Expected behavior

I expected for it to just delete the paste I selected.

### Files Version

v1.5.0.0

### Windows Version

Edição	Windows 10 Pro Versão	21H1 Instalado em	‎10/‎02/‎2021 Compilação do SO	19043.1237 Experiência	Windows Feature Experience Pack 120.2212.3530.0

**Comment by gave92** [comment]
Thanks for the report. Please add the app's debug logs to the issue description.

**Comment by Wygzzz** [comment]
[debug.txt](https://github.com/files-community/Files/files/7192483/debug.txt)

**Comment by gave92** [comment]
Thanks, this issue should be fixed in Files v2.
