### ISSUE TITLE
Can't sort files as per date

### ISSUE THREAD

**Issue by gulshanmudgal** [files-community/Files#6181]
### Description

In any folder if I try to sort items by date, items are sorted as per date string but not as per date.

### Expected behavior

Files should be sorted as per the date.

### Files Version

2.0.12.0

### Windows Version

Windows 11 21h2 10.0.22000.194

**Comment by josh-65** [comment]
What do you mean `as per date`? Sorting files/folders using the group by date option or clicking on the date modified/created does this already.

**Comment by starkgate** [comment]
It's definitely working for me, dates are sorted as they should be.

![ApplicationFrameHost_Ji6UgcVulv](https://user-images.githubusercontent.com/12874678/133974855-be288401-fa73-454e-ba58-b411dae943f7.png)

**Comment by gulshanmudgal** [comment]
Yup, In the latest version I can see this issue has been resolved.
