### ISSUE TITLE
URI of the current folder is displayed in short-hand form

### ISSUE THREAD

**Issue by starkgate** [files-community/Files#6190]
### Description

When clicking on "Open file location", for example in Windows Explorer's start menu, the corresponding folder is displayed in short-hand form in the URI bar. This happens also when using similar functionality from third party applications like Open Shell Utility or MusicBee.

![ApplicationFrameHost_Lik3Ok8lri](https://user-images.githubusercontent.com/12874678/133973407-6d09a2dc-08bd-4b67-b407-aaa872fed9b0.png)

### Steps To Reproduce

1. Right click on an application in the Windows start menu
2. Click Open file location

![ApplicationFrameHost_pglnq9e6MD](https://user-images.githubusercontent.com/12874678/133974131-cd0a87d9-aea8-450a-a5f7-1025dec9faa6.png)
 

### Expected behavior

The URI bar should display the long version of the path. If the short-hand is used in the backend that's fine, but it shouldn't be shown to the user as it is confusing and harder to read.

### Files Version

2.0.13.0

### Windows Version

10.0.19043.1237

**Comment by yaichenbaum** [comment]
This issue should be resolved with #6293.
