### ISSUE TITLE
shift delete crash

### ISSUE THREAD

**Issue by FearTheWhite** [files-community/Files#6191]
### Description

Hi,

i just tried to shift delete two .exe files, when it crashed and reopened saying the was an error that the developers didnt account for, just thought you should know. but apparently it happens only when you do it with more than one file

### Steps To Reproduce

1. select atleast 2 files (havent tried anything else other than .exe)
2. press shift+del 
3. press enter

### Expected behavior

should delete files without them being put into garbage bin

### Files Version

v1.5.0.0

### Windows Version

Version 20H2 (Build 19042.1165)

**Comment by gave92** [comment]
Thanks for the report. Please add the app's debug logs to the issue description.
