### ISSUE TITLE
Change color of new and selection pane toolbar

### ISSUE THREAD

**Issue by ZoroNasr** [files-community/Files#6196]
### Description

I am color blind, using the dark theme, the color in the new, selection pane, sort and toggle are very confusing with the background. 
![Untitled](https://user-images.githubusercontent.com/67539686/134151713-a5686b2b-5e6c-41ad-b209-567be8ae32f4.png)

is there any way to change the colors ?

### Expected behavior

to be able to change the color of those "red" cursors and point to another color, maybe green or yellow

### Files Version

v2.0

### Windows Version

Windows 10 Pro Version	21H1 19043.1237

**Comment by gave92** [comment]
You can change the windows accent color in Windows Settings.

**Comment by ZoroNasr** [comment]
Perfect, worked like a charm
