### ISSUE TITLE
Change "choose your color" UI

### ISSUE THREAD

**Issue by onein528** [files-community/Files#6197]
### What's the Problem?

There is a unified setting UI for the settings of pre-installed apps such as the calculator for windows.

### Solution/Idea

Change like windows apps appearance section

Files app:
![image](https://user-images.githubusercontent.com/62196528/134152936-5381c587-a945-4d2a-8366-925af3ddcf9c.png)

Windows calculation app:
![image](https://user-images.githubusercontent.com/62196528/134152797-242c0514-200f-4a9b-b6e1-73671cf1f8e2.png)

### Alternatives

n/a

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.0.0.0

### Windows Version

OS Version: 10.0.22000.194

**Comment by gave92** [comment]
Default == Use system settings ;)

**Comment by josh-65** [comment]
That should properly be renamed to keep in line with other programes.

**Comment by onein528** [comment]
No. My concern is about UI.
I think the "appearance" section should look like windows calculator.

**Comment by josh-65** [comment]
The apps are not consistent on Windows has it has a drobox also. I think the drop box way is better.

**Comment by onein528** [comment]
certainly. ok I think so.
