### ISSUE TITLE
To be able to move with the arrows once i entered the folder

### ISSUE THREAD

**Issue by ZoroNasr** [files-community/Files#6198]
### What's the Problem?

I cannot move the arrows to select different files if the selection is not on one of the folders or files already

### Solution/Idea

Like file explorer, i would like to be able to allow the arrows to work directly once i'm inside the folder, without having to chose a file or a folder to start using the arrows afterwards

### Alternatives

nothing comes to mind 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

v2.0

### Windows Version

Windows 10 Pro Version	21H1 19043.1237

**Comment by daksh2k** [comment]
Yeah same thing here, I also don't know if this is a bug or the required functionality does not exist but keyboard navigation is really hard in Files. 
When opening files the focus is on the selected tab on the top bar
So you can't reach/select the drives just via keyboard.
Also It doesn't focus on any folder/file when entering a folder so navigating via arrow keys is not possible.

I love this app and Would love to see this implemented in Files.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7390
