### ISSUE TITLE
Crash when pressing up arrow on network location root

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#6200]
### Description

When I open a network location a blank folder appears but nothing else and pressing the up folder arrow crashes files.
![image](https://user-images.githubusercontent.com/26977075/134161243-88b94c4b-ab5d-4c97-bde0-1d2e4dd17671.png)

### Expected behavior

Should show folders and not crash when going up a root.

### Files Version

2.0.13.0

### Windows Version

10.0.19043.1237

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7202592/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7202593/debug_fulltrust.log)

**Comment by gave92** [comment]
Could you confirm what kind of path you tested? Like `\\DESKTOP-CCYY47\share\folder`?

**Comment by josh-65** [comment]
\\DESKTOP-CCYY47  just up to that. if i click a folder it works as expected

**Comment by yaichenbaum** [comment]
This issue should be resolved with #6204.
