### ISSUE TITLE
Network folder content doesn´t automatically refresh

### ISSUE THREAD

**Issue by hondzejk** [files-community/Files#6201]
### Description

Network folders (NTFS on Synology NAS) doesn't refresh after change within Files (folder creation, folder renaming, pasting new file etc.]

### Steps To Reproduce

1.open mapped network drive
2.create new folder
3.nothing changes without manual refresh

### Expected behavior

you can see new folder right after creation without manual refresh (F5)

### Files Version

v2.0

### Windows Version

Windows 10 21H1 19043.1237

**Comment by BanCrash** [comment]
Are u accesing with SMB?
If so, duplicated with #5869

**Comment by hondzejk** [comment]
Yes I am. 
Duplicate issue, please delete.

**Comment by BanCrash** [comment]
> Yes I am.
> Duplicate issue, closing.

Perfect, thanks!
