### ISSUE TITLE
No more indication about google drive backup status

### ISSUE THREAD

**Issue by ZoroNasr** [files-community/Files#6202]
### Description

In the previous version (1.5), it was quite visible if the file has been backed-up by google drive or not, in the new version, there is no indication. It might be the result of the new google drive backup and sync app, but is there any way to restore it like before ?

### Expected behavior

A sign to show that the files are backed-up or not 

### Files Version

v2.0

### Windows Version

Windows 10 Pro Version	21H1 19043.1237

**Comment by gave92** [comment]
Thanks for the report. Could you post a screenshot?
Google drive never showed sync status in the sync status column but only as a badge on the file icon.

**Comment by josh-65** [comment]
Google drive wont show sync status unless it open and setup. Have clicked on the icon in taskbar right side to make sure it setup.

**Comment by ZoroNasr** [comment]
> Thanks for the report. Could you post a screenshot?
> Google drive never showed sync status in the sync status column but only as a badge on the file icon.

Yes, that's exactly what i meant !!, the small badge of a tick which indicated if the file is backed or not, not available anymore in the new version

**Comment by ZoroNasr** [comment]
> Google drive wont show sync status unless it open and setup. Have clicked on the icon in taskbar right side to make sure it setup.

it is setup and everything is synced

**Comment by ZoroNasr** [comment]
Okay, interesting enough, the tick sign is back, maybe it just needed a restart, all is good
