### ISSUE TITLE
Request for option to display subfolders in left-hand list

### ISSUE THREAD

**Issue by dbward** [files-community/Files#6203]
### What's the Problem?

Unable to display subfolders in the left-hand list

### Solution/Idea

Windows Explorer allows subfolders to be displayed in the left-hand column. I rely on that extensively to move files from one place to another. I'm not finding any such option with Files, though.

### Alternatives

Windows Explorer

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.0

### Windows Version

10.0.18363.1801

**Comment by josh-65** [comment]
Same as #1928

**Comment by gave92** [comment]
I understand there is currently no plan to show a tree view in the sidebar. Instead we'll add a TreeView layout in the main pane (#1928).

**Comment by yair100** [comment]
@dbward Tree View is currently available in preview https://files.community/download. It will be included in the next stable release.
