### ISSUE TITLE
Broken Link to Documentation

### ISSUE THREAD

**Issue by killshot13** [files-community/Files#6208]
### Description

When users attempt to view the documentation for _Files_ by clicking the provided link in the _About_ section, they receive an _Error 404_ message.

If I am not mistaken, the erroneous domain was once in use but has been superseded by the new site on GitHub Pages. I would be happy to submit a PR to fix it, but I first wanted to confirm with a maintainer. 

Many thanks for your attention to this matter. :)

### Steps To Reproduce

1. Open the Files application.
2. Navigate to _About > Useful Links > Documentation_ and click the link.
3. Observe the subsequent error message.

### Expected behavior

I expected the link to point to [https://files.community/docs](https://files.community/docs) instead of [https://files-community.github.io/docs](https://files-community.github.io/docs/#/).

### Files Version

v2.0.0.0

### Windows Version

10.0.22000.194

### Relevant Assets

![files-404-error](https://user-images.githubusercontent.com/47695475/134462290-d5ec5c52-9250-4014-b935-9629817b3ad7.png)

**Comment by yaichenbaum** [comment]
@killshot13 thanks for the report, the links will be fixed once the new website is published on October 4th.
