### ISSUE TITLE
popup when moving files

### ISSUE THREAD

**Issue by telemarker** [files-community/Files#6209]
### What's the Problem?

no speedometer when moving files

### Solution/Idea

there should be a little popup when moving files and i like to see the speed in MB/s.

### Alternatives

like in the normal explorers advanced popup

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

v2.0

### Windows Version

WIndows 10 21H1

**Comment by gave92** [comment]
Thanks for the suggestion. Merging with #4811.
