### ISSUE TITLE
make as default explorer

### ISSUE THREAD

**Issue by telemarker** [files-community/Files#6210]
### What's the Problem?

would be nice to set it as default explorer whenever i try to search for files from programs

### Solution/Idea

maybe just open the compact mode for this task.
as long as we have to deal with 2 explorers it makes no sense to switch.

### Alternatives

no alternatives

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.0

### Windows Version

Windows 10 21H1

**Comment by Cliffback** [comment]
I second this. The registry-script works fine except for when a program needs to browse files, and it still opens the old windows explorer

**Comment by gileli121** [comment]
I like this program a lot, I will try to help you in finding a hack for this problem.
Finding "hacks" is not a new thing for me at all (I developed the WindowTop program that requires a lot of hacky thinking)

So I will try to figure out solutions for it because I want this feature also :)

**Comment by gileli121** [comment]
Do you need a contribution of a solution that will work without a registry hack that modifies the system and without any system modification?
I think that you will want such contribution

If so, let me know.
I have ideas

**Comment by yaichenbaum** [comment]
> Do you need a contribution of a solution that will work without a registry hack that modifies the system and without any system modification?
> I think that you will want such contribution
> 
> If so, let me know.
> I have ideas

We're working on a solution that will hopefully be ready for v2.1.
