### ISSUE TITLE
NTFS Long Path Support

### ISSUE THREAD

**Issue by panagiotisTB** [files-community/Files#6211]
### What's the Problem?

Paths longer than 260 chars are not supported

### Solution/Idea

According to MS Support, the NTFS Long Path regkey allows the usage of 260+ char file names and path. Sadly, each application on Windows needs to implement the API for this to work. So it's not a global setting. Windows Explorer is not planning to support this API.

### Alternatives

Total Commander supports NTFS Long Path, but its UI is not modern. Furthermore, the app doesn't feel as native as Files.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Support big/extensive folder structures and longer paths/file and folder names in such structures | Should |

### Files Version

v1.5

### Windows Version

Windows 10 21H1 19043.1165 + Win 11 Insider Preview

### Additional comment

I wonder how people/companies have been handling this in the past. In my opinion MS should be ashamed of this API not being implemented. Especially for companies it's a no-go.
Hope this enhancement will be considered. Thanks in advance.

**Comment by gave92** [comment]
Thanks, Files V2 supports long paths.
