### ISSUE TITLE
Security exception when detecting MEGA drive

### ISSUE THREAD

**Issue by xiaopizi19** [files-community/Files#6212]
### Description

when i run it with Visual Studio，show err “System.Security.SecurityException: Requested registry access is not allowed” at MegaCloudProvider.cs 

### Steps To Reproduce

noe

### Expected behavior

none

### Files Version

latest

### Windows Version

windows 10

### Relevant Assets

System.Security.SecurityException”类型的异常在 Microsoft.Win32.Registry.dll 中发生，但未在用户代码中进行处理
Requested registry access is not allowed.

**Comment by xiaopizi19** [comment]
![16323986338397](https://user-images.githubusercontent.com/10027521/134503628-7e2c3044-e243-41f2-a32f-c61790924d4d.png)

**Comment by duke7553** [comment]
@xiaopizi19 Are you deploying "Files" or "Files.Package" from Visual Studio?

Please make sure you deploy Files.Package for the best results.

**Comment by gave92** [comment]
@xiaopizi19 what0s the value of `subKeyName` when you get the exception?

**Comment by yaichenbaum** [comment]
This issue should be resolved with #6293.

**Comment by xiaopizi19** [comment]
> This issue should be resolved with #6293.

thanks
