### ISSUE TITLE
Set window name to be the same as the selected tab name

### ISSUE THREAD

**Issue by gileli121** [files-community/Files#6214]
### What's the Problem?

I can't work fine if I don't want the tabs feature.. because every window name have the same name "Files"

### Solution/Idea

Hello, I am using this program with a combination of the feature Anchors in WindowTop (A new concept that I think is better than window tabs)
I don't like tabs. I prefer to have multiple windows.

The issue is that every window has the same name so this is what I am getting
![image](https://user-images.githubusercontent.com/17680514/134552154-b9c5caa8-e57b-4ad7-8258-f3696dec7144.png)

We can see the same issue in the taskbar
![image](https://user-images.githubusercontent.com/17680514/134552195-8ef684d4-b767-49fe-a817-795a1a2df1e8.png)

So the problem is very simple.. the window names are always the same.

This is how it should be
![image](https://user-images.githubusercontent.com/17680514/134552368-4bfca354-9105-4447-b7fa-c51ebeb8e2ea.png)

![image](https://user-images.githubusercontent.com/17680514/134552411-3f022436-e8c4-4b07-b7a4-33eea20ed4a2.png)

I really want that every window will have the name of the folder.
Otherwise, the program can't be used nice without tabs.

Please fix the issue.
Thanks

### Alternatives

Using the default file explorer :( 

### Files Version

2.0

### Windows Version

Windows 11 22000.194

**Comment by yaichenbaum** [comment]
This issue should be resolved with #6762.
