### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by SexyRoyalBlue** [files-community/Files#6223]
### Description

I wanted to delete two Word files at the same time. Files crashed, I restarted it and went into the folder they were located. Files crashed again with just getting into the folder. Opened it again, didn't crash and the word documents were gone... it worked but crashed twice :/

### Steps To Reproduce

1. Create two files (doesn't matter what type can even be no type of file)
2. delete them (I did it permantaly)
3. watch how it crashes
4. restart
5. maybe crashes again
6. restart if crashed again
7. see how the files are gone how they should be...

### Expected behavior

if it's just one file it won't happen

### Files Version

latest consumer version

### Windows Version

Windows 21H1 (Build 19043.1237)

### Relevant Assets

https://drive.google.com/file/d/1kbkSziXmDWBgni_tG2W_QuSbZXekEnwR/view?usp=sharing
https://drive.google.com/file/d/1XgDrl5RkMUBN-Cff6OM-0gSfoVyi9G-v/view?usp=sharing

Two videos making it clear what I mean

**Comment by gave92** [comment]
Thanks for the report. Please add the app's debug files.

**Comment by SexyRoyalBlue** [comment]
It actually resolved itself with going to 2.0... and I don't have the debug file anymore... I do have another report tho that with the app in ms store for extra themes for files it just crashes ehile loading :/
Only on my Desktop and not on my laptop
Once I'm home I will get the extra info

**Comment by gave92** [comment]
Thanks a lot for confirming that the issue is fixed. If you can open a new issue about the themes we'll appreciate it (note: it could be that it crashes for some themes but not for others)
