### ISSUE TITLE
Double Clicking on Folders

### ISSUE THREAD

**Issue by infuriatedcodex** [files-community/Files#6224]
### What's the Problem?

Double Clicking on Folders can be unreliable

### Solution/Idea

Double clicking on folders thru the file system is still a bit unreliable.
While not strictly a bug because it does work, it just doesn't work as well as the native explorer.
Can result in either not registering on the odd occasion or if not timed correctly, can end up with a Rename cursor prompt.

### Alternatives

The work around is to change over to Single Click but that's a fairly large compromise for the double clickers amongst us.

### Priorities

| Capability | Priority |
| :---------- | :------- |

| This proposal will allow developers to accomplish Y | Could |

### Files Version

Version: 2.0.13.0 

### Windows Version

OS Version: 10.0.19043.1237

**Comment by yaichenbaum** [comment]
This should be resolved in the latest preview build. https://files.community/download/preview
