### ISSUE TITLE
"Open with" option missing on .bat files

### ISSUE THREAD

**Issue by austinmok915** [files-community/Files#6225]
### Description

"Open with" option missing with .bat files
Find a similar issue, but it has been closed
https://github.com/files-community/Files/issues/5954

### Steps To Reproduce

1. Create a .bat file on any location
2. Right click the files to call the menu
3. Verify the menu

### Expected behavior

"Open with" should be shown under "open" just like all other file types.

### Files Version

Version: 2.0.13.0

### Windows Version

OS Version: 10.0.22000.194 (windows 11)

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7225586/debug.log
[debug_fulltrust.log](https://github.com/files-community/Files/files/7225587/debug_fulltrust.log)
)
![image](https://user-images.githubusercontent.com/36772903/134673998-df36431a-900b-4028-8aae-59a543aa6263.png)

**Comment by gave92** [comment]
@austinmok915 does the open with option appear for .bat files in Windows Explorer?

**Comment by josh-65** [comment]
it does in file explorer but if you scroll down it there. My issue was there being two and files version not working.

**Comment by gave92** [comment]
Thanks for clarifying @josh-65 I had forgotten.

**Comment by austinmok915** [comment]
> @austinmok915 does the "open with" option appear for .bat files in Windows Explorer?

seems like it is a windows 11 issue? "open with" option is also missing in native file explore menu(.bat only)

**Comment by gave92** [comment]
I'm on Windows 10 and I have no open with for .bat files in Windows Explorer either. That's why we had to hide it in Files (if explorer does not have it, clicking the one in Files does not do anything)

**Comment by josh-65** [comment]
Might of been i have modified the right click menu before. Don't remember with what though

**Comment by gave92** [comment]
@austinmok915 since Files here matches the Windows Explorer behavior, I'm gonna consider this as a "feature request". 
Is there any reason for you to have that option considering that you open the bat file in the default text editor by hitting "Edit" in the context menu?
