### ISSUE TITLE
Status field does not show in all OneDrive folders

### ISSUE THREAD

**Issue by brucebinder** [files-community/Files#6227]
### Description

Many of my OneDrive folders do not show the status field.

Also, whern right clicking on header fields, like to have a size all like in file explorer.

### Expected behavior

Status field should show on all OneDrive items. I have a screen shot but I do not see where to attach it.

### Files Version

Version: 2.0.13.0 OS Version: 10.0.19043.1237

### Windows Version

2181 (OS build 19043.1237)

**Comment by gave92** [comment]
Bumping to #7922
