### ISSUE TITLE
Show images on folder hover

### ISSUE THREAD

**Issue by KibSquib48** [files-community/Files#6228]
### Solution/Idea

This video from Reddit is a good example of what I want: https://www.reddit.com/r/Windows11/comments/pumkgn/made_this_just_to_get_rid_of_my_curiosity/?utm_source=share&utm_medium=web2x&context=3

### Alternatives

The implementation for folder previews from Win10 and below doesn't really show as much as the concept.

### Files Version

v2.0.13.0

### Windows Version

Windows 11 21H2 ‎22000.194

**Comment by duke7553** [comment]
I like this solution.

**Comment by yaichenbaum** [comment]
Merging with #4301
