### ISSUE TITLE
Have sidebar and tab content load before displaying it for a smother/consistent transition

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#6229]
### What's the Problem?

Currently files will move from the loading screen (Icon and acent color background) even with the tab content and sidebar not being loaded. It makes it worse transition in my opinion

### Solution/Idea

Have it display the initial loading screen until the content has loaded.

### Alternatives

None

### Files Version

2.0.13.0

### Windows Version

10.0.19043.1237

**Comment by yaichenbaum** [comment]
The previous behavior was to wait until the sidebar was fully loaded, but the general feedback we've gotten is that users prefer seeing the UI as it loads. Regardless, we're working on optimizations to reduce the amount of time it takes to load the sidebar.
