### ISSUE TITLE
'Open with' not working

### ISSUE THREAD

**Issue by mangoepic** [files-community/Files#6232]
### Description

nothing happens

### Steps To Reproduce

Rightclick a file, click 'open with'

### Expected behavior

Windows Open With dialogue appears

### Files Version

Version: 2.0.12.0 

### Windows Version

OS Version: 10.0.19043.1237

**Comment by gave92** [comment]
Any kind of file? Or just some file extensions?

**Comment by Ademord** [comment]
I come to add to this error, in general right click > any other sub-dropdown closes the whole right click menu. You seem to have a bug that crashes when a second-hierarchy dropdown is opened. So New File > .... cant be opened either for example. This makes the whole extension unusable.

**Comment by gave92** [comment]
@Ademord do you have Windows 11? If so it's a known issue of the latest builds of Windows 11, and not something we can fix.

**Comment by Ademord** [comment]
> @Ademord do you have Windows 11? If so it's a known issue of the latest builds of Windows 11, and sadly not something we can fix.

yes i do. ah interesting. cause on the normal file explorer of win11 it works as it should... :/

**Comment by mangoepic** [comment]
> Any kind of file? Or just some file extensions?
> Could you post the app's log files?

Weird, it does work now. I think the arrow with the submenu just didn't appear yesterday and I expected the windows dialogue to pop up instantly instead ... Now it seems to work, though.

**Comment by gave92** [comment]
Thanks @mangoepic, please let us know if the issue pops up again.
