### ISSUE TITLE
Edit File Tags button does not work

### ISSUE THREAD

**Issue by CrazyCherry7** [files-community/Files#6234]
### Description

I click on the icon on the left to pop out another window, hopefully to be able to edit but it doesn't open.

### Steps To Reproduce

1. Go to settings
2. Click on Experimental
3. Enable File Tags
4. Then click on the icon that's to the left of "Edit file tags."

### Expected behavior

I expected it to open something like a new tab or play a video on how to edit the tags.

### Files Version

Version: 2.0.13.0 OS Version: 10.0.19043.1237

### Windows Version

21H1- Windows 10 Home

**Comment by gave92** [comment]
Thanks for the report. This seems to happen if the default text editor is Notepad.
You can modify the tags by editing this file: `%LocalAppData%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState\settings\filetags.json`

**Comment by gave92** [comment]
Note to self: the same happens with the edit Terminals button.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #6236.
