### ISSUE TITLE
Documentation button go to files.community/docs

### ISSUE THREAD

**Issue by steam3d** [files-community/Files#6237]
### Description

Documentation button go to files.community/docs instead https://files-community.github.io/docs/#/
![image](https://user-images.githubusercontent.com/30986874/134812971-e75e1a16-9b81-4b7d-927f-f39a6cf0832e.png)
![image](https://user-images.githubusercontent.com/30986874/134812946-faa9a588-4fc1-4eb1-ab9b-dbb1d13c7293.png)

### Expected behavior

The button will open the docs site.

### Files Version

Version: 2.0.13.0

### Windows Version

OS Version: 10.0.19043.1237

**Comment by yaichenbaum** [comment]
@steam3d the new website will be going live on October 4th.
