### ISSUE TITLE
Access windows network shares 

### ISSUE THREAD

**Issue by mmajko** [files-community/Files#6238]
### What's the Problem?

Computer is not visible in network list, but can be accessed by name (\\\ComputerName typed in Microsoft explorer address bar). In Files, same action gives error: Invalid item...NotAFolder.

### Solution/Idea

Access  windows network shared folders and drives in the same manner as Microsoft Explorer, by typing \\\ComputerName in address bar, if computer is not visible in network list otherwise
![MicrosoftExplorer](https://user-images.githubusercontent.com/91424744/134813888-c392dd53-6eae-469e-8769-eaa239874aa8.png)
![Files](https://user-images.githubusercontent.com/91424744/134813889-d3450e62-b81f-4167-8e46-4dbad4e378a4.png)
![FilesError](https://user-images.githubusercontent.com/91424744/134813890-103c4ab7-63ab-4928-b190-28a5df13b721.png)
. 

### Alternatives

Using native Microsoft Explorer.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.0.13.0 

### Windows Version

OS Version: 10.0.22463.1000 (Windows 11 Pro Insider Preview build 22463.1000)

**Comment by gave92** [comment]
Thanks for the report. Does it work if you type the share name as well e.g. `\\One\Users`?

**Comment by mmajko** [comment]
> Thanks for the report. Does it work if you type the share name as well, e.g. `\\One\Users`? Does the server require username/pw to access?

Yes, server requires user/pass. 
No, the only way is to map network drive through Microsoft explorer, and than they are visible under network in Files. Every other name or address formatting gives same error.

**Comment by gave92** [comment]
> Yes, server requires user/pass.

Thanks for confirming, unfortunately access to shares that require credentials is not supported yet. Merging with #4362
