### ISSUE TITLE
.msi Installer

### ISSUE THREAD

**Issue by SexyRoyalBlue** [files-community/Files#6240]
### What's the Problem?

.msi Installers don't open in files 2.0

### Solution/Idea

Adding support for opening the file like an .exe or .msixbundle

### Alternatives

I don't know how to do it else

### Files Version

2,0.13.0

### Windows Version

Windows 1909 (Build 18.363.1556)

**Comment by gave92** [comment]
Thanks for the report. Please upload the app's debug logs as opening .msi works fine on my device.
