### ISSUE TITLE
Some problems in using files in China

### ISSUE THREAD

**Issue by defutian** [files-community/Files#6243]
### Description

First of all, thank you very much for providing such an excellent program. Many advantages are not described here. Here are some intuitive problems that affect the experience.

### Steps To Reproduce

Question 1 (experience). Right clicking in the blank space of the folder sometimes has a slow response.
Question 2. Different styles appear on the UI interface
1) Repeat question 1. When the right mouse click is slow, right click again, and different color styles will appear on the interface, as shown in the figure:
<img width="901" alt="1" src="https://user-images.githubusercontent.com/5976030/134839172-07b2db99-c775-4712-a32e-1b4a09dc9ee9.png">
2) Of course, this problem will also be transmitted to other parts, such as here:
<img width="220" alt="3" src="https://user-images.githubusercontent.com/5976030/134839228-f60ba5c1-2ae3-494a-8c86-2b6267dabf54.png">
3) The normal situation should be like this
<img width="901" alt="2" src="https://user-images.githubusercontent.com/5976030/134839278-792772c6-e3fa-44b5-9c48-6e252390998f.png">
Problem 3 (experience): the height of the menu hit by the right mouse is not adaptive. You need to scroll down to find the target menu, as shown in the figure:
<img width="318" alt="4" src="https://user-images.githubusercontent.com/5976030/134839369-b1d05ee1-c7c2-459c-9d50-1b65dfed2dae.png">
Question 4 (experience): third party integration needs to be improved, such as tortoisegit
1) The right mouse button does not have a supported menu
2) The file icon is also in the normal state
The following screenshot is the normal situation seen in the file manager when tortoisegit is installed:
<img width="379" alt="5" src="https://user-images.githubusercontent.com/5976030/134839509-841f9a87-76fb-46fb-8cd5-4af8a579fb63.png">

### Expected behavior

Look forward to doing better

### Files Version

2.0.13

### Windows Version

Windows 10 20H1

**Comment by josh-65** [comment]
Please edit this issue in English

**Comment by yaichenbaum** [comment]
1 & 2 are fixed in Windows 11.
3 is an issue we're currently tracking in #6025.
Can you open a new issue for 4?
