### ISSUE TITLE
Ability to Hide Recent Files

### ISSUE THREAD

**Issue by Sage222** [files-community/Files#6247]
### What's the Problem?

Unable to hide Recent Files

### Solution/Idea

Please allow to turn off "Recent Files"

### Alternatives

N/A

### Priorities

Should

### Files Version

2.0.13.0

### Windows Version

20H2

**Comment by gave92** [comment]
You can already hide/show the recent file widget by clicking on the button in the upper-right of the homepage.

**Comment by Sage222** [comment]
ahh thanks - was looking in Options/Settings.

**Comment by Leonick** [comment]
Hiding the widget helps a bit.
But there should be an option to not remember recent files at all.

**Comment by BanCrash** [comment]
> Hiding the widget helps a bit. But there should be an option to not remember recent files at all.

I think you refer to #5882 ;)
