### ISSUE TITLE
Clear Search button

### ISSUE THREAD

**Issue by JoshLizak** [files-community/Files#6249]
### Solution/Idea

When using the search functionality within a directory, there is no obvious way to clear the search and return to viewing all contents of the current directory.

### Alternatives

The only method to accomplish this as I have found is to navigate to another directory first then return to the initial directory.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.0.0.0

### Windows Version

Windows 10 Pro 21H1 19043.1237

**Comment by josh-65** [comment]
Pressing the back button should take you out of the search. You do have to do it multiple times if you did multiple search's on top of each other.
