### ISSUE TITLE
Favorites: Add possibility to rename the entry without renaming the item it links to

### ISSUE THREAD

**Issue by codingdave** [files-community/Files#6250]
### What's the Problem?

Lets say you have the folder name "MyProgram" under %PROGRAMFILES%\MyProgram and %APPDATA%MyProgram. If you add both of them to the favorites, you end up having 2 entries with the same name but different link. It would be good to label them s.t. it can be made clear.

### Solution/Idea

Renaming the Favorite should rename the entry (reference name) not the item it references.

### Alternatives

none

### Files Version

v1.5

### Windows Version

Windows 10 21H1 19043.1237

### Additional comment

I just spotted that software and it looks great. I hope I will have a lot of joy using it. Thanks!

**Comment by yaichenbaum** [comment]
Merging with #3422.
