### ISSUE TITLE
Feature: Increase default width of the name column

### ISSUE THREAD

**Issue by mangoepic** [files-community/Files#6252]
### What's the Problem?

Filenames are usually pretty long

### Requirement
Change the default width of the name column to 240

### Files Version

Version: 2.0.12.0 

### Windows Version

OS Version: 10.0.19043.1237

**Comment by yaichenbaum** [comment]
@gave92 The general feedback seems to be that users expect the columns to be wider by default.

**Comment by gave92** [comment]
Yeah not sure if the issue is also that any time you resize the files windows, user defined column widths are lost.

**Comment by hez2010** [comment]
How about making the column length self-adaptive?

**Comment by mangoepic** [comment]
> How about making the column length self-adaptive? (automatically adjust base on the longest filename in list items)

That also doesn't sound like a bad idea because in practice long enough filenames that would push the other columns away too much don't really exist, _but_ it could make switching folders a bit more annoying visually because the column size jumps all the time

**Comment by yaichenbaum** [comment]
> How about making the column length self-adaptive? (automatically adjust base on the longest filename in list items)

@hez2010 that would be a little confusing if the user manually overrode the default width. Instead, what are your thoughts on setting the default width for the name column to match the longest file name the first time the directory is opened?

**Comment by mangoepic** [comment]
> @hez2010 that would be a little confusing if the user manually overrode the default width. Instead, what are your thoughts on setting the default width for the name column to match the longest file name the first time the directory is opened?

I think that would be pretty good, maybe together with a solid minimum (maybe about the current size) and a maximum, so it doesn't fluctuate too much or move the other columns too far in extreme cases
