### ISSUE TITLE
Right Click Menu > More... dismisses menu early

### ISSUE THREAD

**Issue by SweetJD** [files-community/Files#6253]
### Description

If you right click an item, then attempt to scroll down the right click menu to "More..." and attempt to hover over this menu item, the menu is dismissed immediately, rendering it useless.

### Steps To Reproduce

1. Right click a file in the explorer view.
2. Scroll to bottom of the right click menu to "More..."
3. Attempt to click or highlight this menu

### Expected behavior

The "More..." menu should open a menu without being dismissed.

### Files Version

Version: 2.0.13.0 OS Version: 10.0.22458.1000

### Windows Version

Windows 11 Pro Insider Preview Build 22458

**Comment by gave92** [comment]
Issue caused by recent build of Windows 11. Microsoft has supposedly fixed this bug in the latest build.
