### ISSUE TITLE
Bug: Selecting files in Cloud Drives downloads them

### ISSUE THREAD

**Issue by SweetJD** [files-community/Files#6254]
### Description

When attempting to access files in a cloud service like Dropbox, highlighting any file not currently downloaded to the client computer will cause Dropbox to sync the file immediately.

### Steps To Reproduce

Highlight any icon in Dropbox that is currently Online-only, or scroll through many using the arrow keys.

### Expected behavior

I would expect the same behavior as Finder or File Explorer. The file should be previewable, but should not download until it is explicitly requested by an app or the user.

### Files Version

Version: 2.0.13.0 OS Version: 10.0.22458.1000

### Windows Version

Windows 11 Pro Insider Preview Build 22458

**Comment by gave92** [comment]
Do you have the preview pane in Files open? Does the download still happen if the preview pane is closed?

**Comment by SweetJD** [comment]
It seems to start downloading a variety of files--maybe the entire folder--regardless of whether the preview pane is open.

**Comment by yaichenbaum** [comment]
@gave92 can I remove the `more-info` label?

**Comment by SohamPande747** [comment]
Hi, I am new to open source. Can you guide me in the right direction so that I can work on this issue
Thank You

**Comment by yaira2** [comment]
@SohamPande747 The first step would be to repro the issue on your device, then you'll have to identify the cause and work on the solution.

**Comment by SohamPande747** [comment]
@yaira2 Sir this requires me to install files app which is paid and I can't work due to that. Thank You for your support though.

**Comment by yaira2** [comment]
You'll need to compile from the source code, there are instructions in the readme.

**Comment by yaira2** [comment]
@SweetJD are you able to repro this in the latest preview build? https://files.community/download
