### ISSUE TITLE
Renamimg Folders doesn't always work the first time

### ISSUE THREAD

**Issue by Superenigmatix** [files-community/Files#6256]
### Description

Renaming a folder and hitting return did not appear to change folder name. Renaming and then clicking out of the folder name did not appear to change the folder name. Third time renaming and hitting return did make the folder name change.  This has happened on three occasions today, this last time it crashed files with message "This caused Files to crash with an issue the Developers did not think of" or something close to that.

Scrrenshots of event log attached

### Steps To Reproduce

1. Go to Folder name
2. Slow Double-click to get into rename mode
3. Rename folder
4. Hit Return (or click out of field)
5. Folder name remains the same.
6. Files application crashes.

### Expected behavior

File to be renamed after hitting return or clicking out of the field.

### Files Version

v1.5

### Windows Version

Windows 11 Pro 21H2 22000.194

### Relevant Assets

![image](https://user-images.githubusercontent.com/72653530/135390760-44fc67d7-f0b6-43d0-bc96-cccbec0081c5.png)
![image](https://user-images.githubusercontent.com/72653530/135390838-82a7903d-a343-4827-92d4-aead6a36617e.png)

**Comment by gave92** [comment]
Thanks for the report. Please upload the app's debug logs.
Could you confirm that you're on Files v1.5 and not Files v2.0?

**Comment by Superenigmatix** [comment]
[debug.txt](https://github.com/files-community/Files/files/7257028/debug.txt
[debug_fulltrust.txt](https://github.com/files-community/Files/files/7257029/debug_fulltrust.txt)
)
![image](https://user-images.githubusercontent.com/72653530/135396045-d171a597-63f7-4be5-bf78-27170f75ce04.png)

Screenshot of version #, not aware of a version 2.0 as yet.

**Comment by Superenigmatix** [comment]
[debug_fulltrust.txt](https://github.com/files-community/Files/files/7257046/debug_fulltrust.txt)

**Comment by gave92** [comment]
@yair100 how does one update to v2.0? By manually checking for updates in the windows store?

**Comment by Superenigmatix** [comment]
> @yair100 how does one update to v2.0? By manually checking for updates in the windows store?

I got my install from Github, checking for updates in the Windows store doesn't find a newer version. I searched for it and have downloaded now.

**Comment by gave92** [comment]
Great, please let us know if the new version still has the same issue.
