### ISSUE TITLE
.exe or .msi installer file?

### ISSUE THREAD

**Issue by Whirlpool-Programmer** [files-community/Files#6257]
### What's the Problem?

a `.exe` or `.msi` installer wanted

### Solution/Idea

Add a exe or msi installer

### Alternatives

None.

### Files Version

v1.5

### Windows Version

Windows 7 SP1

**Comment by yaichenbaum** [comment]
@Whirlpool-Programmer Files is a packaged app which doesn't work with exe/msi installers. MSIX packages are available with releases of Files on GitHub.

**Comment by GOKUSSL4** [comment]
While it maybe closed it is a valid request an msi or exe installer that way UWP is not used. Windows 10 and 11 people will use non UWP apps as much as possible.
