### ISSUE TITLE
Single click folden in column view

### ISSUE THREAD

**Issue by EvilCheez** [files-community/Files#6258]
### Solution/Idea

It would be awesome if you could open the folders with single click when in Column view! 

### Alternatives

Option on the settings menu so the user can decide if they want column view to open folders in one click or double 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.0.13.0 OS Version: 10.0.19043.1237

### Windows Version

Edition	Windows 10 Pro Version	21H1 Installed on	‎31/‎1/‎2021 OS build	19043.1237 Experience	Windows Feature Experience Pack 120.2212.3530.0

**Comment by gave92** [comment]
We have that! Files Settings > Files and Folders > Open items with one click. Are you experiencing problems with it?

**Comment by yaichenbaum** [comment]
> We have that! Files Settings > Files and Folders > Open items with one click. Are you experiencing problems with it?

I think they are requesting for the column layout to automatically work with single click while still using double click in the other layouts.

**Comment by zhiqiang-li** [comment]
> We have that! Files Settings > Files and Folders > Open items with one click. Are you experiencing problems with it?

If I enable "Open items with one click", executeables and doc files will be opened with one click too. Can we add a new option to only enable opening folder with one click? When in column mode, it would a very productive way to navigate ;-)

**Comment by EvilCheez** [comment]
What I mean is exactly what Zhiqiang and yair100 are saying. 
I am aware of the option that lets you open folders with one click, but this also opens executable files, which is not convenient if I am being honest. 
In column view, the open with one click option can be enabled but only work with folders, not other files or exe. 

Also, in that view, it doesn't remember the sorting, it would be nice to have it remember that I sorted files by type or date etc when I open it again. 

Thanks for all the hard work, files is pretty awesome!

**Comment by pxab** [comment]
Yes, a "single-click-open on folders only" is the only thing that keeps me from switching over completely at the moment.

**Comment by yaichenbaum** [comment]
Merging with #6308.
