### ISSUE TITLE
Remove clicking animation on list view on Windows 10

### ISSUE THREAD

**Issue by EvilCheez** [files-community/Files#6259]
### Solution/Idea

An option to remove animations when pressing a folder

### Alternatives

option to make animation speed quicker, just like in the android platform. 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.0.13.0 OS Version: 10.0.19043.1237

### Windows Version

Edition	Windows 10 Pro Version	21H1 Installed on	‎31/‎1/‎2021 OS build	19043.1237 Experience	Windows Feature Experience Pack 120.2212.3530.0

**Comment by yaichenbaum** [comment]
Animations in the list view are no longer present in Windows 11 but I'm not sure it's posible to backport them to Windows 10. @winston-de do you know anything about this?

**Comment by gave92** [comment]
Also #6259

**Comment by EvilCheez** [comment]
Hey there, 

What I am saying is that it would be nice to have an option to disable having an animation when you click on a file. That scale in that a folder does when you click it. 
More like a traditional windows behavior would be nice. 
This animation effect, gives the impression that the double click takes way too long to apply and open a folder or a file. 

An option to disable this and even other animation would be much appreciated! 

Thanks!

**Comment by yaichenbaum** [comment]
@EvilCheez this is actually an OS behavior on Windows 10, Windows 11 no longer has this animation.

**Comment by Barthy727** [comment]
Hi there. I just discovered this project. Just want to mention this animation and slower loading of folders is only thing what prevents me to use this program :) . Toggle for turning off animation would we nice :)

**Comment by gave92** [comment]
@yair100 it looks like the only way to remove animation on Windows 10 is to use ListViewItemExpanded `<Style BasedOn="{StaticResource ListViewItemExpanded}" TargetType="ListViewItem">` which is said to negatively affect performance.

**Comment by gsabater** [comment]
nothing about this on the latest release i see

**Comment by yaichenbaum** [comment]
Unfortunately the necessary APIs aren't supported on Windows 10 so we can't backport the styles.

**Comment by Hefaistos68** [comment]
Maybe this is of any help? https://social.msdn.microsoft.com/Forums/sqlserver/en-US/e5dc0add-5176-4891-93d0-46c500cced4d/uwp-how-to-remove-tap-animation-when-a-listview-item-is-clicked?forum=wpdevelop
Dont know anything about UWP programming, so I am just guessing.

**Comment by gave92** [comment]
Yup that would work, unfortunately it negatively affects performance (e.g scrolling) and we haven't considered it. Should check how much of an impact it actually has though.

**Comment by Talisman39ar** [comment]
Just reviving this old request in case there are any recent developments that might improve it. Like others, I find the italicize-and-bounce-right animation when clicking an item to be distracting and unexpected. Any chance of finding a way to remove it or give an option to turn it off?

**Comment by yaichenbaum** [comment]
The next release of Files will bring the latest WinUI styles to Windows 10.
