### ISSUE TITLE
Right click menus are bigger than windows 11 versions

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#6264]
### What's the Problem?

They currently have bigger heights and mabey more padding around the button then windows 11 current version

### Solution/Idea

Make them the same size

### Alternatives

None

### Files Version

2.0.13.0

### Windows Version

11.0.22468.1000

**Comment by gave92** [comment]
@yair100 is there a plan to switch to WinUI [compact style](https://docs.microsoft.com/en-us/windows/apps/design/style/spacing)?

**Comment by yair100** [comment]
> @yair100 is there a plan to switch to WinUI [compact style](https://docs.microsoft.com/en-us/windows/apps/design/style/spacing)?

For just the context menu?

**Comment by gave92** [comment]
For everything actually, like the details view file list.
I'm not really sure how the compact style is supposed to work, I originally thought it was a style that was automatically used depending on input being touch or mouse.. or is that a different thing?

**Comment by yaichenbaum** [comment]
The compact styles can be switched between but besides for the regular context menu (command bar flyout may be different), you need to switch between them manually. @ADeltaX was looking into adding support for auto switching based on the input mode, but we can probably just implement a manual setting for now.

**Comment by MarcAnt01** [comment]
https://github.com/microsoft/microsoft-ui-xaml/issues/6024

**Comment by MarcAnt01** [comment]
https://github.com/microsoft/microsoft-ui-xaml/issues/6024

**Comment by gave92** [comment]
Merging with #6288
