### ISSUE TITLE
Taskbar right click menu looks weird after Files update

### ISSUE THREAD

**Issue by Elaborendum** [files-community/Files#6265]
### Description

I installed Files through Chocolatey, and always updated it through Chocolatey too. However, suddenly it recently appeared updated to the latest version (2.0.13.0) that's not yet available as a direct download (which Chocolatey uses). Turns out the Microsoft Store updated it on its own, which I didn't know could happen before, since I never use it. For example, I have Quicklook (also a UWP app, also in the store) installed, but the MS doesn't detect it as installed, unlike Files, which does register as installed. But I can't verify if this was the case before.

Since that sudden update, the task bar right click menu doesn't show some folder names anymore, they are instead replaced by a string of text and numbers. It even happens to the header of that section, which, if I remember correctly, is meant to be frequent folders? Hovering over them, except for the header, shows me what folder they are meant to be and clicking on them will open the proper folder too.

### Steps To Reproduce

1. Install Files v1.5 through Chocolatey
2. Keep automatic updates activated on the Microsoft Store and wait for it to update automatically.
3. Right-click the Files icon in the taskbar
4. See bug

### Expected behavior

Section header should show a proper name and the folders should have their corresponding names (Desktop, Downloads and Pictures in this case).

### Files Version

v2.0.13.0

### Windows Version

Windows 10 20H2 19042.1237

### Relevant Assets

![imagen](https://user-images.githubusercontent.com/71190696/135743517-30a577d1-5b52-4cb2-b695-3c1828b847a3.png)

**Comment by hez2010** [comment]
You can try resetting Files in system settings (though this would clean your Files preference)

**Comment by gave92** [comment]
#5830 was supposed to take care of this, but it looks like it's not working.

**Comment by yaichenbaum** [comment]
@Elaborendum does opening the app solve the issue?

**Comment by Elaborendum** [comment]
Opening the app didn't solve the issue, but simply rebooting the computer seems to have fixed it now. Is there any way to prevent it from being registered and auto-updated by the Microsoft Store in the future, so I can update it at my own pace? Seems like my only option would be to disable all auto-updates

**Comment by kenmorse** [comment]
Seems like this was resolved by a reboot — should it still be an open issue?

**Comment by gave92** [comment]
Thanks for the tip @kenmorse but yes, it's not supposed to require reboot so the issue stays open ;)

**Comment by yaichenbaum** [comment]
Issue appears to be resolved.
