### ISSUE TITLE
Show ongoing tasks indicator on the taskbar

### ISSUE THREAD

**Issue by FibYar** [files-community/Files#6266]
### What's the Problem?

The "Files" doesn't show files copying status on the Windows taskbar

### Solution/Idea

The "Files" should show ongoing operation status on the Windows taskbar like File Explorer does.
![изображение](https://user-images.githubusercontent.com/12131583/135745643-8e854c71-8ca1-4924-a081-82558317dbbb.png)

### Alternatives

For now "Files" shows status in it's own GUI, but this is not a good case, when you copy a very large file, that you should want to copy in the background.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

v2.0.13.0 OS Version: 10.0.19042.1237

### Windows Version

Windows 10 20H2 19042.1237

**Comment by yaichenbaum** [comment]
This issue should be resolved with #6273.
