### ISSUE TITLE
New Tab Display text change

### ISSUE THREAD

**Issue by John-Zampa** [files-community/Files#6267]
### What's the Problem?
New Tab text change to home or root or some other relevant text. 
_No response_

### Solution/Idea

![Files Tab](https://user-images.githubusercontent.com/91826261/135748657-9b86002c-67a6-4ddc-ba79-cd3acfab11f5.jpg)

### Alternatives

Instead of a new tab, type/display root or home. It will be more relevant. Because the new tab is suitable for blank pages, not for a page that is already showing drives.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.0.13.0 

### Windows Version

OS Version: 10.0.22000.194

**Comment by gave92** [comment]
I'd agree with this, it's strange for the homepage to be called "Home" on the sidebar but "New tab" at the top.

**Comment by yaichenbaum** [comment]
Merging with #4139.
