### ISSUE TITLE
Paste, copy and drag are not allowed

### ISSUE THREAD

**Issue by Rexin2000** [files-community/Files#6268]
### Description

1. When I use "files" in the probation period, right-click a file and choose to copy it to any "files" location, and then right-click to select paste. There is no response. The shortcut key is the same, but it can be pasted to the desktop and system file manager after copying

2. The desktop or system file manager files cannot be directly dragged to "files"

### Steps To Reproduce

See description

### Expected behavior

See description

### Files Version

v1.5

### Windows Version

版本	Windows 10 家庭中文版 版本号	21H1 安装日期	‎2021/‎6/‎30 操作系统内部版本	19043.1237 体验	Windows Feature Experience Pack 120.2212.3530.0

**Comment by gave92** [comment]
Thanks for the report. This issue should be fixed in Files v2 (check for updates in Microsoft Store), please let us know if you have this issue again with the new version.
