### ISSUE TITLE
When trying to make AppData folder favorite, the program crashes

### ISSUE THREAD

**Issue by alanimdeo** [files-community/Files#6269]
### Description

When I drag AppData folder to Favorites, the program crashes.
But it does not crash when right click to AppData folder and click Pin to Favorites.

https://user-images.githubusercontent.com/32806763/135753399-24cfa14c-faf0-4248-b48b-3577e4505a5b.mp4

### Steps To Reproduce

1. Go to user folder (in my case, C:/Users/Alanimdeo)
2. Drag AppData folder to Favorites.
3. Program crashes.

### Expected behavior

Add AppData folder to Favorites

### Files Version

2.0.13.0

### Windows Version

Windows 11 Pro 21H2 22000.194

**Comment by gave92** [comment]
Thanks for the report. Please add the app's debug logs to the issue description.

**Comment by Noisyfox** [comment]
This seems to be fixed in #6271
