### ISSUE TITLE
Thumbnail isn't showing properly

### ISSUE THREAD

**Issue by SamCool939** [files-community/Files#6276]
### Description

When I'm opening a folder that contain image files, sometimes the thumbnail of image files isn't showing properly, even the file isn't invalid. And sometimes only about half of the image files shows thumbnail correctly and the rest isn't loaded (only shows a typical Photos app icon as the thumbnail). Even refreshing doesn't work.

### Steps To Reproduce

1. Open any folder that has image files
2. Set layout to 'Medium Icons' or any other thumbnailed-layouts
3. Thumbnail will not showing properly

### Expected behavior

Thumbnails will showed correctly 100%, except for invalid file(s)

### Files Version

v2.0.13.0

### Windows Version

Windows 11 21H2 22000.194 (Beta Channel)

### Relevant Assets

![image](https://user-images.githubusercontent.com/73696044/135786502-c60545fe-1b37-4e52-9970-42984d102d07.png)

**Comment by gave92** [comment]
Could you check what happens if you open the same folder first with windows explorer and than visit it in Files? Do the thumbnails appear?

**Comment by SamCool939** [comment]
![image](https://user-images.githubusercontent.com/73696044/135847655-772500aa-4fc7-4956-b0a8-39e5c423b6bc.png)

**Comment by gave92** [comment]
Does Files show the thumbnails now that you've visited the folder with explorer?

**Comment by SamCool939** [comment]
Yes, but only half of all image files

**Comment by gave92** [comment]
Merging with #6130
