### ISSUE TITLE
Right click context menu doesn't show all the options.

### ISSUE THREAD

**Issue by mbsanchez** [files-community/Files#6279]
### Description

This is the normal menu show by the windows' explorer
![image](https://user-images.githubusercontent.com/143726/135810090-64575c37-9005-4db2-b904-c9bbc61fe1f2.png)

This is the menu shown by this application:
![image](https://user-images.githubusercontent.com/143726/135810385-7f9f402b-4623-44d9-b943-57b88435055b.png)

I'm using the latest version 2.0.13 on windows 10. The TortoiseGit menu is very important for me because I use it very often.

### Steps To Reproduce

1. Open the application
2. click on an empty area of the explorer
3. You will notice that an item (folder or file) is always selected which is incorrect.

### Expected behavior

I expect to see all the menu entries when I click in an empty area of the explorer.

### Files Version

v2.0.13

### Windows Version

Windows 10

**Comment by gave92** [comment]
Thanks for the report. Could you check if you just need to scroll down the menu to see the items?

**Comment by mbsanchez** [comment]
OMG! yes, I needed to scroll the menu down, sorry. However, I think that the user experience is not good maybe it will be great if you adapt the menu size accordingly.

**Comment by gave92** [comment]
You're right, there's currently a bug preventing us from doing that but that's definitely the plan.
