### ISSUE TITLE
When open a zip file, if have chinese contents, file's name gonna in a mess

### ISSUE THREAD

**Issue by ShangJixin** [files-community/Files#6282]
### Description

(Chinese User) My zip file is contain Chinese, not only its name in a mess, but also when I open it, the program will exit with a toast.
![image](https://user-images.githubusercontent.com/21075413/135831197-37915be3-769e-4720-adba-587fb9b9baf1.png)

### Steps To Reproduce

1. Open a zip file
2. Open a folder or file in this zip which is named by Chinese
3. If you open a folder named by Chinese, application will exit with a toast (Translation:Unexcepted Error)
![image](https://user-images.githubusercontent.com/21075413/135832428-0ad28bf2-36f3-4754-bd47-cc1ad6affce8.png)
4. If you open a file in this zip named by Chinese, the preview will gonna to this:
![image](https://user-images.githubusercontent.com/21075413/135832682-c1d3f76f-b126-4158-b991-ee37d5e8c07c.png)

### Expected behavior

gonna to normal?
or... When open a zip file, use the default third-party application (e.g. BandiZip) to open it is better?

### Files Version

2.0.13.0

### Windows Version

Windows11 22000.194 co_release

### Relevant Assets

![image](https://user-images.githubusercontent.com/21075413/135831197-37915be3-769e-4720-adba-587fb9b9baf1.png)

**Comment by Wangkai8787** [comment]
我也有这个问题。

**Comment by gave92** [comment]
Thanks for the report. Could you upload a zip file that shows the issue?

**Comment by ShangJixin** [comment]
[新建 ZIP 压缩文件.zip](https://github.com/files-community/Files/files/7282420/ZIP.zip)
here is
