### ISSUE TITLE
Crash if adding drive to favourite which label contains "\\" (double back slash)

### ISSUE THREAD

**Issue by Noisyfox** [files-community/Files#6283]
### Description

The app keeps crashing on openning when a drive which label contains double slash is added to favourite.

### Steps To Reproduce

1. Update any drive label to contain double back slash (using explorer)
2. Open Files, then try to add this drive to favourite
3. The app crashes immediately, and will keep crashing on openning

### Expected behavior

The app should work normally

### Files Version

v1 - v2

### Windows Version

Both windows 10 & 11

### Relevant Assets

The place which crashes is here:
![QQ截图20211004214345](https://user-images.githubusercontent.com/1537155/135841053-555b1c6a-9881-4c07-8cc5-00ac479660d8.png)

Logs:
[debug.log](https://github.com/files-community/Files/files/7277600/debug.log)

The exception details:
```
System.Exception
  HResult=0x800700A1
  Message=指定的路径无效。

Error trying to query the application data container item info
  Source=System.Private.CoreLib
  StackTrace:
   在 System.Runtime.InteropServices.WindowsRuntime.IMap`2.HasKey(K key)
   在 System.Runtime.InteropServices.WindowsRuntime.MapToDictionaryAdapter.ContainsKey[K,V](K key)
   在 Files.ViewModels.SettingsViewModel.Get[TValue](TValue defaultValue, String propertyName) 在 F:\MyProject\Files\Files\ViewModels\SettingsViewModel.cs 中: 第 784 行
   在 Files.DataModels.NavigationControlItems.LocationItem.get_IsExpanded() 在 F:\MyProject\Files\Files\DataModels\NavigationControlItems\LocationItem.cs 中: 第 49 行
   在 Files.UserControls.SidebarControl.SidebarControl_obj43_Bindings.Update_(LocationItem obj, Int32 phase) 在 F:\MyProject\Files\artifacts\intermediates\x86\Files\UserControls\SidebarControl.g.cs 中: 第 908 行
   在 Files.UserControls.SidebarControl.SidebarControl_obj43_Bindings.ProcessBindings(Object item, Int32 itemIndex, Int32 phase, Int32& nextPhase) 在 F:\MyProject\Files\artifacts\intermediates\x86\Files\UserControls\SidebarControl.g.cs 中: 第 850 行
```

**Comment by yaichenbaum** [comment]
This issue should be resolved with #6293.
