### ISSUE TITLE
Install error v2.0 or v2.0.13

### ISSUE THREAD

**Issue by bdpita** [files-community/Files#6284]
### Description

Hi, I have v1.5 installed and when I try to install v2.0 or v2.0.13 I get the following error:

App Installer failed to install package dependencies. Ask the developer for Microsoft.UI.Xaml.2.6 package.

Any idea how to fix it.

Thanks, Bernardo.

### Steps To Reproduce

Download release and try to install -v2.0 or v2.0.13.

### Expected behavior

Not have any errors in the installation.

### Files Version

v2.0 & v2.0.13

### Windows Version

Windows 10 Home v21H1 19043.1266

**Comment by gave92** [comment]
@yair100 could we add the dependencies on the Release page?

@bdpita In the meantime you can find the missing dependency [here](https://store.rg-adguard.net/). You'll need to type this in the site textbox: `https://www.microsoft.com/en-us/p/files-file-manager-for-windows/9nghp3dx8hdx` and download the .appx for Microsoft.UI.Xaml.2.6.

**Comment by bdpita** [comment]
@gave92, perfect, with your instructions I was able to install v2.0.13 without problems, thank you very much!

Regards, Bernardo.

**Comment by yair100** [comment]
> @yair100 could we add the dependencies on the Release page?
> 
> @bdpita In the meantime you can find the missing dependency [here](https://store.rg-adguard.net/). You'll need to type this in the site textbox: `https://www.microsoft.com/en-us/p/files-file-manager-for-windows/9nghp3dx8hdx` and download the .appx for Microsoft.UI.Xaml.2.6.

I'll be add the build artifacts in future releases.
