### ISSUE TITLE
When drag a image file from WeChat(PC) to this application, failed

### ISSUE THREAD

**Issue by ShangJixin** [files-community/Files#6286]
### Description

When drag a image file from WeChat(PC) to this application, failed

> 从微信电脑端拽图片到`Files`里，会拖拽失败

![image](https://user-images.githubusercontent.com/21075413/135862632-72463447-2b6d-4f75-b662-70d8d5deb743.png)

Release the mouse, No file be added.

> 松开鼠标后，啥反应都没有，图片也没被成功弄进来

### Steps To Reproduce

--

### Expected behavior

It can works.

### Files Version

2.0.13.0

### Windows Version

10.0.22000.194（Windows 11 co_release）

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?
