### ISSUE TITLE
Play back audio files in the preview pane via a hotkey

### ISSUE THREAD

**Issue by Netrex** [files-community/Files#6287]
### What's the Problem?

Currently you are only able to play back audio in the preview pane by dragging your mouse to the play button.

### Solution/Idea

Having the ability to play audio files in the preview pane is really neat but what would make the experience even better is if you were able to playback the audio via a hotkey.

### Files Version

v2.0.13.0

### Windows Version

Windows 11 Pro (22000.194)

**Comment by gave92** [comment]
Space would be the obvious shortcut but it's used to trigger Quicklook preview 🤔

**Comment by winston-de** [comment]
If your keyboard has one, the pause/play button should do this, although it doesn't work consistently when there's another app playing media.

**Comment by gave92** [comment]
`Ctrl + P` maybe?

**Comment by winston-de** [comment]
Ctrl+P currently toggles the preview pane, maybe ctrl+alt+p though?

**Comment by yaichenbaum** [comment]
This issue should be resolved with #6690.
