### ISSUE TITLE
Offer a "compact view" option with less padding and bit smaller fonts + avoid scroll options on context menu

### ISSUE THREAD

**Issue by pavangayakwad** [files-community/Files#6288]
### What's the Problem?

Too much relaxed spacing resulted in less number of files/folders view and scrolling on context menu to reach "...More" option is counterproductive. 

### Solution/Idea

I am really impressed with the work done by you guys! kudos! and thank you very much for sharing your work with Windows users.

Here are my 2 cents..

File explorer is a very crucial and most frequently used application on windows. When there are too many files and folders, it would be great to see them as many as we can in a view. 

I have attached screenshot of Windows file explorer and the Files (in the right side) and I would like you to observe the effective usage of real-estate by the windows file explorer. Request to offer similar 'compact' view in Files as well so that users like me can get to see more content comfortably.

![image](https://user-images.githubusercontent.com/1834890/135871956-7323e539-4639-48c7-9b58-86766216f2c6.png)

...and

I didn't find scrolling on context menu to view more menu options as a great UX, I prefer the way Windows file explorer does with its context menu, shows all the items and reaching to the "...More" option doesn't require scrolling.

![image](https://user-images.githubusercontent.com/1834890/135873332-0eae448f-fd46-4aca-b573-b1512312c784.png)

### Alternatives

NA

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Offer compact view with less padding and with bit reduced font size | Must |
| scrolling on context menu must be avoided | Must |

### Files Version

Version: 2.0.13.0 OS Version: 10.0.19043.1266

### Windows Version

Windows 21H1

### Additional comment

None

**Comment by yaichenbaum** [comment]
Merging with #1940.
