### ISSUE TITLE
right click popup too small

### ISSUE THREAD

**Issue by LovesHunting** [files-community/Files#6290]
### Description

On Windows 10. Files version 2.0.13.0. When you select one or a few files and right click, we get a popup but the size is way too small and if you don't know to scroll down to see all the available options, you will be looking. As you can see on the right side, i have a scrollbar and i have to scroll down to see my 7-zip or anything else I want to do.
![FilesPopup](https://user-images.githubusercontent.com/91906017/135890211-90cf91af-1a3c-4e4d-83d7-a8c782531cf6.jpg)

### Steps To Reproduce

- go anywhere where you have a file
- select one or more files
- right click on them
- notice we can't see all available options without scrolling down

### Expected behavior

I expect the popup to be bigger. i have notepad ++ and 7 zip installed and in explorer I see what I have and can do immediately but files limits what i see
![winexplorer](https://user-images.githubusercontent.com/91906017/135890785-90e40bf5-2fb7-4b50-9fba-07df7ac0cdcb.jpg)
 

### Files Version

2.0.13.0

### Windows Version

Windows 10 pro 10.0.19043

**Comment by gave92** [comment]
Thanks for the report. There is currently a WinUI issue preventing us from doing that, but that's definitely the plan.
