### ISSUE TITLE
Flac playback in the preview pane

### ISSUE THREAD

**Issue by IdkWhatToCallMe123** [files-community/Files#6291]
### What's the Problem?

Add flac playback in the preview pane

### Solution/Idea

So I use a lot of flac files for my music, so it would be really cool if you play the in the preview pane instead of just showing the artwork.

### Alternatives

_No comment_

### Files Version

2.0.13.0 

### Windows Version

Windows 10 21H1

**Comment by yaichenbaum** [comment]
This issue should be resolved with #6297.
