### ISSUE TITLE
Disk available space is displayed incorrectly

### ISSUE THREAD

**Issue by Pridecoo** [files-community/Files#6292]
### Description

After deleting a game via Uplay to free some space - I checked the disk. It had outdated info, I deleted big folder to be sure, and nothing changed. Check the disk "D" on the attachment.

### Steps To Reproduce

1. Delete game via Uplay
2. Check the disk space available via "Files"

### Expected behavior

Disk space is displayed correctly after deleting files.

### Files Version

Версия: 2.0.13.0

### Windows Version

OS Version: 10.0.19043.1237

### Relevant Assets

![image](https://user-images.githubusercontent.com/59889115/135902156-67c8a919-9e9b-49f7-8899-c138e4b1c3d9.png)

**Comment by gave92** [comment]
Merging with #2242
