### ISSUE TITLE
Control Onedrive sync status

### ISSUE THREAD

**Issue by LucasTaves** [files-community/Files#6294]
### What's the Problem?

The app shows the onedrive status for the file but it doesn't allow to manage it

### Solution/Idea

Add a right click menu option for always keeping the file on the device, and to free up space, and share either the file or a link to the file, mimicking the controls you have on the file explorer app.

### Alternatives

Can't think of an alternative.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to manage their onedrive sync status within the app | Should |

### Files Version

2

### Windows Version

Windows 11 release preview

### Additional comment

![image](https://user-images.githubusercontent.com/30808592/135931081-c55ff284-1a6a-4356-a376-fed3f1ee8685.png)

**Comment by gave92** [comment]
The right click menu in Files should show the same options. Please not that you might need to scroll down the menu to see them.
