### ISSUE TITLE
Being able to change icons

### ISSUE THREAD

**Issue by KavishBansal** [files-community/Files#6295]
### What's the Problem?

I want to be able to change icons in Files app, because I don't like the default look of folder icon.

### Solution/Idea

If we can change icons just like in normal Windows Explorer that would be great and make it almost complete for me. 

### Alternatives

Alternatively if we can even use icon packs, like Microsoft Launcher on Android, that'd be even better solution. But considering this is a UWP app and its limited in functionality by the UWP itself, I am not sure if it would be possible. But yea, any way to change the icons will be great.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

v2

### Windows Version

Windows 11 21H2 (Build 22000.194)

**Comment by gave92** [comment]
Any program/icon pack that changes the icons in windows explorer will also change the icons in Files.
