### ISSUE TITLE
Being able to add background images to the folders like in Windows XP

### ISSUE THREAD

**Issue by KavishBansal** [files-community/Files#6296]
### Solution/Idea

I want to be able to add background images to the folder itself. That'd make it much more personalized based on what folder I am in. I can set picture for whatever folder I am in . For example, the folder with Harry Potter movies can have Harry Potter as its background image, or a Grand Theft V folder can have its relevant picture as background in it. 
It would look something like this, but it'd better if we can change the opacity of the image itself so it doesn't makes it difficult to read text. 
https://i.imgur.com/2HwfMV1.jpg

### Alternatives

I can't think of any alternatives for this, I think this will be one of the greatest personalisation features one can add on this app. 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

v2

### Windows Version

Windows 11 21H2 (Build 22000.194)

**Comment by yaichenbaum** [comment]
@KavishBansal thanks for the request, this goes a little beyond the custmization we're planning on offereing in Files.
