### ISSUE TITLE
Outdated Files version installed from winget. Unknown Files version installed from msstore

### ISSUE THREAD

**Issue by mangkoran** [files-community/Files#6299]
### What's the Problem?

Installing Files from `winget` installs Files 0.21.1.0. Installing Files from `msstore` installs latest Files, but with unknown Files version information in `msstore` (not in the Files app)

### Solution/Idea

- Update Files in `winget`
- Tag proper version in msstore

### Alternatives

No idea

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to have better package management in package repositories | Must |

### Files Version

v2.0.13

### Windows Version

Microsoft Windows [Version 10.0.22000.194]

### Additional comment

Install log: 
```
PS C:\Users\ayams> winget install files --source winget
Found Files - Preview [Files-Community.Files] Version 0.21.1.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.

PS C:\Users\ayams> winget install 9NGHP3DX8HDX --source msstore
Found Files - File Manager for Windows [9NGHP3DX8HDX] Version Unknown
This package is provided through Microsoft Store. winget may need to acquire the package from Microsoft Store on behalf of the current user.
Version: Unknown
Publisher: Yair A
Publisher Support Url: mailto:filesapp@outlook.com
Description: Files is a powerful and efficient file manager. Its has features like multiple tabs, panes, columns, shell extensions and tags.
```

**Comment by yaichenbaum** [comment]
Thanks for the report, a PR is currently open in the WinGet repo, just waiting for it to be merged 👍

**Comment by mangkoran** [comment]
Maybe could you link the PR here so we can see the progress?

**Comment by yaichenbaum** [comment]
> Maybe could you link the PR here so we can see the progress?

https://github.com/microsoft/winget-pkgs/pull/29281

**Comment by mangkoran** [comment]
Seems like it's not passing the pipeline https://github.com/microsoft/winget-pkgs/pull/29281#issuecomment-933112787
