### ISSUE TITLE
Expandable Menus close before being able to click 

### ISSUE THREAD

**Issue by sam1357** [files-community/Files#6301]
### Description

Any expandable menu when right clicking on a file seems to close the menu before once is able to click on any options. Occurs with the 'Open with' and 'Extract' options. 

### Steps To Reproduce

1. Right click on any file
2. Hover over 'Open with'

### Expected behavior

Should normally stay open to allow for one to click an option.

### Files Version

v.2.0.13.0

### Windows Version

Windows 11 22454.1000

**Comment by gave92** [comment]
Thanks for the report. This is a known bug of some builds if windows 11.
