### ISSUE TITLE
WSL2 Section on Windows 11 21H2 Not Visible at Files 2.0 but Visible at Windows Explorer

### ISSUE THREAD

**Issue by azisnaufal** [files-community/Files#6303]
### Description

I cannot access WSL2 file system from Files 2.0 either from address bar using \\wsl.localhost or WSL sidebar section. 

### Steps To Reproduce

1. Open Files. 
2. Access \\wsl.localhost at address bar
3. NotAFolder error 

### Expected behavior

1. Open Files. 
2. Access \\wsl.localhost at address bar
3. Explore WSL2 File System

### Files Version

2.0.13.0

### Windows Version

Windows 11 21H2

### Relevant Assets

![image](https://user-images.githubusercontent.com/2264036/135968170-3fa0d639-7e88-4e52-bca0-b8a01b7cc9aa.png)

**Comment by gave92** [comment]
Merging with #5486 as both have the same cause. For whatever reason on Windows 11 that folder seems inaccessible for uwp? apps.
