### ISSUE TITLE
UWPHost.pdb not found

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#6304]
### Description

I can no longer run the application with Visual Studio. The code compiles, but at runtime I get a "UWPHost.pdb not found" error. I spent hours looking for solutions on the web, without success. Does anyone have a solution?

### Steps To Reproduce

Execute in Visual Studio 2019 with parameters: debug, x64, Files.Packages.

### Expected behavior

Show application.

### Files Version

Last commit

### Windows Version

Windows 10 Entreprise 21H1 19043.1237

**Comment by BanCrash** [comment]
> @BanCrash A thousand thanks, it works! (version 16.11.2)

Glad it work! I updated the comment to add an additional step that I had to make, but since it's working for you there is no problem then!
