### ISSUE TITLE
Columns layout : problem while restoring from previous state when it startsup

### ISSUE THREAD

**Issue by pavangayakwad** [files-community/Files#6305]
### What's the Problem?

In a Columns layout, while restoring from previous state, it should remember all the folders opened in the pane in every tab

### Solution/Idea

I opened `C:\Windows\appcompat\Programs` before closing the Files app. As I have my File application "startup" preference setup to "Continue where you left off", I expect all folders opened in the order _C:\Windows\appcompat\Programs_ should be available when restored, however what I am see is shown below.

You can also observe the progress bar revolving endlessly.

![image](https://user-images.githubusercontent.com/1834890/135988701-ee989f62-ebf0-486a-96cd-58a9e5f60ac1.png)

### Alternatives

NA

### Files Version

Version: 2.0.13.0 OS Version: 10.0.19043.1266

### Windows Version

Windows 10 Enterprise 21H1 Builder Version: 19043.1266

**Comment by ferrariofilippo** [comment]
Duplicate #6902
