### ISSUE TITLE
UI glitches in the settings

### ISSUE THREAD

**Issue by erayrafet** [files-community/Files#6306]
### Description

![image](https://user-images.githubusercontent.com/34194191/135996741-26bb7628-8a08-4099-ac8f-949deb0cb1f5.png)
![image](https://user-images.githubusercontent.com/34194191/135997032-76838580-00eb-4171-8699-995239e127e9.png)
![image](https://user-images.githubusercontent.com/34194191/135997329-dea5cd8c-927b-4d63-b8ee-cddd3ba147a5.png)
![image](https://user-images.githubusercontent.com/34194191/135997619-ede2727c-0f08-4b06-bf41-02d530586da7.png)
**Zoom in very closely!**

There are grey/white hairline marks inside on hover / selected section buttons in the settings.
From what I've tested so far, similar glitches can be observed with the default dark/light themes, Black Pixel, and I guess all.
![image](https://user-images.githubusercontent.com/34194191/135997085-2188ec3d-8997-45a2-a1b2-95cc98a17fd6.png)

### Steps To Reproduce

1. Go to the settings.
2. Observe glitches inside the button area of the selected section or hover over any to see those.

### Expected behavior

Glitch-free color-filled button backgrounds.

### Files Version

2.0.13

### Windows Version

Windows 11 21H2 22000.194

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7284546/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7284547/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
@erayrafet thanks for the report, unfortunately this is a WinUI/OS issue and we can't do anything to fix it.
