### ISSUE TITLE
Add individual options for amount of clicks to open files and folders

### ISSUE THREAD

**Issue by yair100** [files-community/Files#6308]
### What's the Problem?

There is currently an option to open items with a single click, some users might want additional customization in this area to configure files and folders differently.

### Solution/Idea

Adding a second option to "Open files with a single click" should resolve this issue.

### Alternatives

na

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will change the current setting to only apply to folders | Must |
| This proposal will add an option to open files with a single click | Must |

### Files Version

v2.0.15

### Windows Version

Windows 11

**Comment by Chris2011** [comment]
Correct, I would like to have single click for folders (Column view) but still double click for files. I think it is the same behavior with the Mac OS Finder. Also when I move the keyboard arrows up and down, it should open the folder. But this seems another issue, probably.
