### ISSUE TITLE
When opening a directory that is already opened on your current tab, the application should not try to open it again

### ISSUE THREAD

**Issue by Mikey1993** [files-community/Files#6310]
### What's the Problem?

When opening a directory that is already opened on your current tab, the application should not try to open it again

### Solution/Idea

When the current tab shows for example the `Documents` folder from the `Favorites` section, and you are trying to open the same path on the current tab, but now by clicking on the `Documents` tab from another section, for example `Libraries`, the tab refreshes and is trying to open the path without any need as it's already opened.

So what I am proposing is that the application will check if the newly opened directory is the same as the one that is currently opened in the current tab (on the default settings it's opening the directory in the same tab), and if it does. don't do anything :)

### Alternatives

Not relevant..?

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to not have flashy objects reloaded on the screen when not needed | Could |

### Files Version

2.0.13.0

### Windows Version

Windows 10 21H1 19043.1266

**Comment by gave92** [comment]
Mm the documents folder from Favorites and the documents folder in Libraries are two different things though. The fact that your documents library only contains the documents folder is not true for all users.
Not sure if we should make this a special case.

**Comment by Mikey1993** [comment]
> 
> 
> Mm the documents folder from Favorites and the documents folder in Libraries are two different things though. The fact that your documents library only contains the documents folder is not true for all users. Not sure if we should make this a special case.

Well, they are the same for me when opening them, and I haven't changed anything, as it came like this by default.
Also, I didn't say that my `Documents` library only contains the `Documents` folder..

Both of the `Documents` directories are the same directory when looking at the absolute path:
![1](https://user-images.githubusercontent.com/8223772/136086739-bdb9793f-0798-4449-a939-6f0a483a730a.PNG)

**Comment by gave92** [comment]
> Also, I didn't say that my Documents library only contains the Documents folder..

Meaning it's showing the wrong contents for the Documents library?

> Both of the Documents directories are the same directory when looking at the absolute path

That's funny, this is what I have (different path and different contents).

Documents Folder:
<img src="https://user-images.githubusercontent.com/9673091/136087842-71961a13-7f9e-45b1-a89c-5fc37560c7ca.jpg" width="400"/>

Documents Library:
<img src="https://user-images.githubusercontent.com/9673091/136087728-14aa89a4-62c2-4118-86dd-bac5ab88f6d1.png" width="400"/>

**Comment by Mikey1993** [comment]
@gave92 ,
> Meaning Files it's showing the wrong contents for the Documents library? Does the library point to more than one folder? Does Explorer show different/more contents for the documents library?

OK, I see that the `Documents` from `Favorites` is the `C:\Users\XXX\Documents` path,
But the `Documents` from `Libraries` is a **combination** of files/directories from `C:\Users\XXX\Documents` and `C:\Users\XXX\OneDrive\Documents`, which I don't think is the right behavior..? At least it's not what I expected to see (the same directory as under the `Favorites`).

I can also see that when opening the `Properties` dialog for the `Documents` under `Libraries` I can in fact see the two directories listed, but the `C:\Users\XXX\Documents` path is set to be the default one, so I expected it to only show files/directories from this directory, hence thinking that both of the directories are the same (Which I think the intended outcome is that they should be identical):
![2](https://user-images.githubusercontent.com/8223772/136095130-df90eba7-78d8-4342-ae4d-1856163132ba.PNG)

**Comment by gave92** [comment]
Well the intended outcome is to show the same as Explorer, that for the Documents Library is to show the two folders contained in the library _grouped by folder_:

<img scr="https://user-images.githubusercontent.com/9673091/136095651-0a07de06-a19b-4120-84e0-c341e5fe5df8.png" width="400"/>

_But_ this was not implemented and FIles just combines the contents of the folders together. <- bug, let's forget about libraries xD

--------------------------------------------------------

Coming back to issue of "application should not try to open again a folder which is already open in the current tab" do you see this happening in any other case (except for Libraries vs Favorites)?

**Comment by Mikey1993** [comment]
@gave92 ,

> Well the intended outcome is to show the same as Explorer, that for the Documents Library is to show the items of the two folders contained in the library grouped by folder:

For some reason my `Documents` library from the Explorer only showing files from `C:\Users\XXX\Documents`, and I don't remember changing anything from my side on the Explorer settings..

> Coming back to issue of "application should not try to open again a folder which is already open in the current tab" do you see this happening in any other case (other than for Libraries vs Favorites)?

I don't think I can replicate this anywhere else, as I can't pin the same directory two times anywhere.

Looks like if I pin a directory to `Favorites`, it knows not to open it again when clicking on it in the `Favorites` sidebar without reloading it, so this issue seems to be specifically tied to the case of `Libraries` vs `Favorites` :)

**Comment by gave92** [comment]
Thanks a lot for helping us understand the issue!
