### ISSUE TITLE
Network drive folders doesn't update after operation

### ISSUE THREAD

**Issue by Blaztix** [files-community/Files#6311]
### Description

I have a Raspberry PI with samba.
In Windows I have attached this drive with a letter
![image](https://user-images.githubusercontent.com/4962591/136042091-5a30ef0a-1a73-4dfc-b17f-cd9e65164c23.png)

When I do an operation under `Z:` (ex: `Z:\Apps` ) like rename, paste file, delete, etc. The interface does not update and I didnt see any change.
I need press `F5` or change folder to see changes.

### Steps To Reproduce

I thinks is needed a network hard drive.

# Original state

![image](https://user-images.githubusercontent.com/4962591/136042542-06f79d5d-2a9d-4c82-a1ce-0a0275dfb28c.png)

# Renaming

![image](https://user-images.githubusercontent.com/4962591/136042614-e9fba73e-5394-4c96-bca1-036d4aedaff5.png)

# Modificated State (Press Enter or anything)

![image](https://user-images.githubusercontent.com/4962591/136042629-7fab6523-1bee-4764-a5ed-3afe6c913b55.png)

# After press F5

![image](https://user-images.githubusercontent.com/4962591/136042651-e25b503f-c548-42e2-b5bd-c32144c5ac2a.png)

### Expected behavior

When I press Enter the modificated name show immediately.

### Files Version

2.0.13.0

### Windows Version

10.0.22000.194

**Comment by gave92** [comment]
Merging with #5869
