### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by EricAtORS** [files-community/Files#6315]
### Description

I was experiencing crashes on startup 3 out of 4 times with the release available in the store (2.0.13)
I tried debugging it with VS 2019 16.10.3 and this is what I found:

First I get this error: 
`Exception thrown at 0x00007FF9B9573FE9 (KernelBase.dll) in Files.exe: 0x000006D9: There are no more endpoints available from the endpoint mapper.`

then if I press continue, I get this error:
```
Exception thrown at 0x00007FF9B9573FE9 in Files.exe: Microsoft C++ exception: EEMessageException at memory location 0x0000000C338799C0.
```

### Expected behavior

Not to crash

### Files Version

2.0.13 and main

### Windows Version

10.0.18363

### Relevant Assets

First Error:
![image](https://user-images.githubusercontent.com/28938051/136090813-d4b95642-68f0-441d-a742-8df099c41ded.png)

Second Error:
![image](https://user-images.githubusercontent.com/28938051/136090948-a805eabc-ec55-4f3c-99aa-47b38dcb6b35.png)

And thread for the second error if it helps:
![image](https://user-images.githubusercontent.com/28938051/136090992-b73d6c25-23bc-4eea-8741-75f4fc68e9ba.png)

**Comment by yaichenbaum** [comment]
Thanks for the report, unfortunately this is an issue with Visual Studio and the only option appears to be downgrading to an earlier version of Visual Studio.

**Comment by EricAtORS** [comment]
@yair100 
Will the next release be built with a lower version of VS 2019?

**Comment by yair100** [comment]
> @yair100 Will the next release be built with a lower version of VS 2019?

The pipeline seems to be compiling working versions of the app so that shouldn't be an issue. Hoping the VS issue get's fixed soon though as it's been slowing us down.

**Comment by EricAtORS** [comment]
I was experiencing crashes on startup from the release build 2.0.13.
Is it possible that since I have newer versions of VS installed that the release version of Files is using what ever DLLs I have installed instead of what is bundled with Files?

**Comment by yaichenbaum** [comment]
@EricAtORS are you seeing a crash in the store build?

**Comment by EricAtORS** [comment]
Yes. In 2.0.13.
I tried debugging it, but I only got so far. I can just periodically check in on discord to see if the newest release of VS is ok to use.
