### ISSUE TITLE
Files installation failed. Microsoft.VCLibs.140.00 package

### ISSUE THREAD

**Issue by icecoffeeabell1835** [files-community/Files#6316]
Hello everyone,
after installing Files 2.0.13.0 by file, the installer shows an error.
![Files 2 0 13](https://user-images.githubusercontent.com/91980861/136094606-0e3d998e-9ec7-41bc-b9ce-076d0c9f065f.PNG)

**Comment by gave92** [comment]
Hi @icecoffeeabell1835 thanks for the report. In the future we're going to add the dependencies into the Release page. In the meantime you can find the missing dependencies [here](https://store.rg-adguard.net/). You'll need to type this in the site textbox: https://www.microsoft.com/en-us/p/files-file-manager-for-windows/9nghp3dx8hdx and download the .appx for VCLibs (and maybe others, e.g Microsoft.UI.Xaml).

**Comment by icecoffeeabell1835** [comment]
> In the future we're going to add the dependencies into the Release page.

> you can find the missing dependencies [here](https://store.rg-adguard.net/).

It worked, I downloaded and installed these 2 files.
Microsoft.VCLibs.140.00_14.0.30035.0_x64__8wekyb3d8bbwe.appx
Microsoft.UI.Xaml.2.6_2.62108.18004.0_x64__8wekyb3d8bbwe.appx

After the installation, I was able to successfully install Files 2.0.13 by file. Can you add this to your github page or include the missing dependencies in the Files 2.0.13 file?
