### ISSUE TITLE
File History button on the command bar and context menu

### ISSUE THREAD

**Issue by ArchXen** [files-community/Files#6318]
### Solution/Idea

I would like to suggest a File History integration button in the command bar and context menu when you right-click a file or folder.

Just like the old Windows 10 File Explorer, a File History button is needed for users of File History to quickly access what are the backups from that folder and easily restore them.

Currently Files does not support this. Even Windows 11 File Explorer, the button is now missing as well, even though the File History feature is still exist with the OS and working fine, but lost the File Explorer shortcut.

### Alternatives

Currently the only way to access File History in Windows 11 is simply to access its own executable from the Control Panel or searching it from the Windows Search, and pin it to Start Menu. On Windows 10, this remain accessible through Ribbon UI.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish | Should |
| This proposal will allow end users to accomplish | Should |

### Files Version

Version: 2.0.13.0

### Windows Version

OS Version: 10.0.22000.194

**Comment by yaichenbaum** [comment]
Thanks for the request! Merging with #4098.
