### ISSUE TITLE
CUSTOM FONTS  OPTION then we be looking at a  great design also a nord theme would be nice too

### ISSUE THREAD

**Issue by nitani-x** [files-community/Files#6319]
### What's the Problem?

i just want to put custom foonts on everything i see

### Solution/Idea

add a button 🔳  to  the settings :)

### Alternatives

none

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

v1.15

### Windows Version

latest version

### Additional comment

nord theme  would be nice but custom fonts even bettah

**Comment by nitani-x** [comment]
also its  a  should

**Comment by yaichenbaum** [comment]
Thanks for the request, this goes a little beyond the customization we're planning to offer in Files.

**Comment by ghost** [comment]
@yair100 maybe I wouldn't add a button in Settings, but rather make it available in the [Custom themes](https://files.community/docs/configuring/custom-themes "Files").
I don't for example use lowercase letters, so adding the ability to change font, or maybe just use the system font would be helpful.

**Comment by nitani-x** [comment]
Oooo

-
Sent from MailTime<http://www.mailtime.com> for Android


On Oct 14, 2021 1:22:08 PM Luko Foks ***@***.***> wrote:

@yaichenbaum<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fyaichenbaum&data=04%7C01%7C%7C5c38e33a09074c6d1f6608d98f3724e8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637698289278722964%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=53EzyHYM844DHF2NxHAtbzSETpJbSQXIIuoVSt2vU8g%3D&reserved=0> maybe I wouldn't add a button in Settings, but rather make it available in the Custom themes<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ffiles.community%2Fdocs%2Fconfiguring%2Fcustom-themes&data=04%7C01%7C%7C5c38e33a09074c6d1f6608d98f3724e8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637698289278722964%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=m4ZPaiJvovh16OFBtDTlTcSFIlN2Ox7tQFnpn%2BN67%2Bs%3D&reserved=0>.
I don't for example use lowercase letters, so adding the ability to change font, or maybe just use the system font would be helpful.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffiles-community%2FFiles%2Fissues%2F6319%23issuecomment-943563848&data=04%7C01%7C%7C5c38e33a09074c6d1f6608d98f3724e8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637698289278732920%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8vRqv1oLvJSg7CjWXGgBAqtS8Xra59l7jbhDtXahgGY%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ3B5V4WUFZ7O5Y53ZKZF63UG4GTZANCNFSM5FND2RWQ&data=04%7C01%7C%7C5c38e33a09074c6d1f6608d98f3724e8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637698289278732920%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9Elamys5QWN868836WKlJDdkXCZIrAdPV9dBtC3yZdg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C5c38e33a09074c6d1f6608d98f3724e8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637698289278732920%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=GK5THup4tqQcvVnbcmAammXBaXHpYIIJalZgpEOwx4o%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C5c38e33a09074c6d1f6608d98f3724e8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637698289278742877%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=wAcx2zJHqjyfxUJtiL1arxc5PrnY7ZFo1Mgae6a77M4%3D&reserved=0>.

**Comment by yaira2** [comment]
Support for custom fonts is now available, please see the documentation for more details https://files.community/docs/configuring/custom-themes
