### ISSUE TITLE
Improve the Speed and Reliability of Storage Item Operations

### ISSUE THREAD

**Issue by duke7553** [files-community/Files#632]
**Is your feature request related to a problem? Please describe.**
The cut, copy, and paste operations aren't as fast as we'd like.

**Describe the solution you'd like**
Use the Win32 *FromApp APIs available to UWP apps.

**Describe alternatives you've considered**
N/A

**Additional context**
TBA

**Comment by duke7553** [comment]
Notes: Someone really needs to take a good look at improving the reliability of these operations especially when multitasking with different tabs.

I consider this issue a prerequisite for the Status UI.

**Comment by lorisobi** [comment]
When I move some bigger files and switch the tab files uwp crashes

**Comment by duke7553** [comment]
@lorisobi Is this on the latest preview? Also, can you upload your debug log so I can look into this?

**Comment by d2dyno1** [comment]
Are all .dll functions imports supported in Files? ("Kernel32.dll", "win32.dll")

**Comment by duke7553** [comment]
@d2dyno1 They have to be from this list: https://docs.microsoft.com/en-us/uwp/win32-and-com/win32-and-com-for-uwp-apps

**Comment by d2dyno1** [comment]
How do I import them?
Is it done by `[DllImport()]`?

```
[return: MarshalAs(UnmanagedType.Bool)]
[DllImport("Kernel32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
internal static extern bool CopyFileExW(...);
```
?

**Comment by tsvietOK** [comment]
@d2dyno1 
```csharp
[return: MarshalAs(UnmanagedType.Bool)]
[DllImport("api-ms-win-core-file-l2-1-0.dll", CharSet = CharSet.Unicode, SetLastError = true)]
public static extern bool CopyFileExW(...);
```

**Comment by d2dyno1** [comment]
Thanks, @tsvietOK !

I'll see what I can do then...

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
