### ISSUE TITLE
Cannot delete files / folders

### ISSUE THREAD

**Issue by Crea4iveBoy2020** [files-community/Files#6320]
### Description

It gives an error unable to move file to recycle bin 
![image](https://user-images.githubusercontent.com/82692870/136143461-da8bdb52-d227-4a65-aab0-0bfbb059156b.png)
 Please fix this otherwise this app is awesome 
 **Thanks**

### Steps To Reproduce

Go to a file and delete it

### Expected behavior

I wanted to delete files its simple           

### Files Version

2.0.13.0

### Windows Version

Windows 11 22471.1000

**Comment by gave92** [comment]
Thanks for the report. Please add the apps debug files to the issue description
