### ISSUE TITLE
Google drive for desktop not showing under cloud drives

### ISSUE THREAD

**Issue by WelkinBunbury** [files-community/Files#6321]
### Description

![image](https://user-images.githubusercontent.com/33565456/136152651-59fec602-200f-459b-8a4f-042fc19a098a.png)

### Expected behavior

It should come under Cloud drive section

### Files Version

Version: 2.0.16.0

### Windows Version

OS Version: 10.0.19042.1165

**Comment by WelkinBunbury** [comment]
> I'm using the latest version of Google Drive (recently updated from previous iteration called Google Backup & Sync), and my Google Drive folder shows under the Cloud Drives section just fine (alongside with the new "virtual hard drive" that Google have added now).
> 
> ![2021-10-07](https://user-images.githubusercontent.com/15675443/136354853-07768c49-5355-40cc-8a9c-e91fa7a69ab3.png)

i had installed new google drive for desktop before this feature came, so yesterday i uninstalled and reinstalled it but still i didnt came.

![image](https://user-images.githubusercontent.com/33565456/136491641-241fe653-fead-4165-90a6-f1c36182f7d0.png)

**Comment by gave92** [comment]
Might be tricky to distinguish it from the other drives (unless you assume the name is always google drive)

**Comment by ThaUnknown** [comment]
you could make a few rules for it, but I also can't seem to find any clean way of a drive as a google drive, but by far, the best way I found is to check `HKEY_CURRENT_USER\Software\Google\DriveFS\PerAccountPreferences` which is a json object, and just read: `per_account_preferences[0].value.mount_point_path` which gives you the drive letter. I don't think you can change the drive name from `Google Drive` so I guess that could be a decent solution

**Comment by zotabee** [comment]
Same issue with Windows 11.

**Comment by yaichenbaum** [comment]
> you could make a few rules for it, but I also can't seem to find any clean way of a drive as a google drive, but by far, the best way I found is to check `HKEY_CURRENT_USER\Software\Google\DriveFS\PerAccountPreferences` which is a json object, and just read: `per_account_preferences[0].value.mount_point_path` which gives you the drive letter. I don't think you can change the drive name from `Google Drive` so I guess that could be a decent solution
> 
> keep in mind that that json includes all accounts, so you'd need to add this for all accounts, not just the first one like I showed above
> 
> Edit: this also solves #3500

@ThaUnknown would you be interested in making these changes and opening a PR?

**Comment by ThaUnknown** [comment]
> > you could make a few rules for it, but I also can't seem to find any clean way of a drive as a google drive, but by far, the best way I found is to check `HKEY_CURRENT_USER\Software\Google\DriveFS\PerAccountPreferences` which is a json object, and just read: `per_account_preferences[0].value.mount_point_path` which gives you the drive letter. I don't think you can change the drive name from `Google Drive` so I guess that could be a decent solution
> > keep in mind that that json includes all accounts, so you'd need to add this for all accounts, not just the first one like I showed above
> > Edit: this also solves #3500
> 
> @ThaUnknown would you be interested in making these changes and opening a PR?

no, I've never worked with UWP before, and I don't plan on that changing

**Comment by gave92** [comment]
Teaser :)

<img src="https://user-images.githubusercontent.com/9673091/168406695-f3d7370f-a3fe-4ad8-8dbd-3b25ad199e7f.png" width="250" />

**Comment by yaichenbaum** [comment]
This issue should be resolved with #9165
