### ISSUE TITLE
Context menu often close itself when im trying to access the submenu

### ISSUE THREAD

**Issue by Jilon76** [files-community/Files#6326]
### Description

this bug always happening to me, its very annoying, the Context menu often close itself when im trying to access the submenu of the context menu itself... sry for my grammar tho

### Steps To Reproduce

1. Right Click to open context menu
2. Click whichever submenu option there is
3. The context menu closing by itself

### Expected behavior

just work normally u know

### Files Version

2.0.13.0 

### Windows Version

Windows 11 22463.1000

### Relevant Assets

https://user-images.githubusercontent.com/92019116/136170188-98ee39f6-073d-4e73-80bf-b290a05e952e.mp4

**Comment by gave92** [comment]
Known Windows 11 issue. I understand they fixed it in the latest build.
