### ISSUE TITLE
Drives taking up time to show on launching files

### ISSUE THREAD

**Issue by VPraharsha03** [files-community/Files#6327]
### Description

I see this happening every time i open Files. It takes atleast 30 seconds for Files to display all the connected drives on my PC.

### Expected behavior

Connected Drives should show up instantly, the attached video shows the delay in showing up. The same applies to the folders under Favorites section

### Files Version

2.0.16.0

### Windows Version

Windows 10 19H1 10.0.18362.1049

### Relevant Assets

https://user-images.githubusercontent.com/56556436/136175131-31a3c326-3b92-42ed-be7d-be24734155cd.mp4

**Comment by gave92** [comment]
Could you upload the two app's debug logs?

**Comment by VPraharsha03** [comment]
> Could you upload the two app's debug logs?
[debug.zip](https://github.com/files-community/Files/files/7294055/debug.zip)

**Comment by VPraharsha03** [comment]
> Do you see a process called "FilesFullTrust.exe" running in task manager when Files is running? The fulltrust component does not appear to be running and the log is empty, not normal. Where did you install the app from?

"FilesFullTrust.exe" isn't running, i've checked that the file exists in the installation directory but doesn't start with Files. 
I've installed them manually from the DevOps build zip shared by Yair. I installed both x86 & x64 dependencies first and then installed Files package. I ran the installers manually because Install.ps1 failed with the error: ```Error: Could not acquire a developer license. For more information, see http://go.microsoft.com/fwlink/?LinkID=252740.```
