### ISSUE TITLE
Application closes on it's own when kept minimized

### ISSUE THREAD

**Issue by VPraharsha03** [files-community/Files#6328]
### Description

Application closes on it's own when it is minimized after less than 10 seconds (see attached video)

### Steps To Reproduce

1. Launch files
2. Minimize to taskbar

### Expected behavior

It shouldn't close and stay minimized 

### Files Version

2.0.16.0

### Windows Version

Windows 10 19H1 10.0.18362.1049

### Relevant Assets

https://user-images.githubusercontent.com/56556436/136177498-bc037548-1c2d-4456-af17-7ba827b0df6c.mp4

**Comment by VPraharsha03** [comment]
> Could you upload the app's debug files?

[debug.log](https://github.com/files-community/Files/files/7294018/debug.log)

**Comment by y-young** [comment]
Same for me, the application closes immediately when minimized.
[debug.log](https://github.com/files-community/Files/files/7489964/debug.log)

**Comment by duke7553** [comment]
@VPraharsha03 Can you still reproduce this bug with the latest version of Files?
