### ISSUE TITLE
Right click on right pane -> Hover on Others, window will close even after you hover on it.

### ISSUE THREAD

**Issue by KeremArdicli** [files-community/Files#6329]
### Description

Right click on the left pane, go to "others" option. New window appear but, after you hover your mouse on the window, it closes. It mostly occurs when right click menu window does not fit to the below and appear on above. It is easy to replicate but does not occur everytime.

https://user-images.githubusercontent.com/72523365/136178209-92f042f5-93c9-455e-af1e-90648b2d756c.mp4

### Steps To Reproduce

See attached video.

Go to left pane.
Right click on a disk.
Hover on "others".
Hover on new opened window.
It disappears.

If not, move the files window a bit below of the screen so the newly opened menu appear above.

### Expected behavior

Menu should keep opened.

### Files Version

Build: 2.0.13.0 OS Version: 10.0.19042.1237

### Windows Version

Windows 10 20H2 - 1902.1237

**Comment by gave92** [comment]
Possibly happens when the mouse goes outside the menus?

**Comment by yaira2** [comment]
Is this still an issue in v2.4?
