### ISSUE TITLE
Right click menu theme is not consistent with the settings

### ISSUE THREAD

**Issue by KeremArdicli** [files-community/Files#6330]
### Description

Depending on where you right click on the window, the opened menu theme is sometimes wihe (light) and sometimes black (dark).  Once you click on an empty space on right pane, the menu will turn dark, and will remain so for left pane right-clicks. But it is always consistent with folder right clicks.

![white_menuı](https://user-images.githubusercontent.com/72523365/136180132-160d017f-c577-4603-803d-461064cba7a9.PNG)

![dark_menuı](https://user-images.githubusercontent.com/72523365/136180141-39344617-a67d-4b8b-811a-b00dd8b4200e.PNG)

### Steps To Reproduce

Go to files.
right click on a folder or left pane.
Menu will open white (consistent with theme settings).
Now go to empty space on right pane and right click. 
Menu will open dark theme color (contrary to theme settings).
After that, right clicks on left pane will always be dark.
Yet, right clicks on folders are still white.

### Expected behavior

Whereever I right-click, menu theme should be consistent with theme settings.

### Files Version

Sürüm: 2.0.13.0 OS Version: 10.0.19042.1237

### Windows Version

Windows 10 20H2 - 1902.1237

**Comment by gave92** [comment]
Thanks for the report. Closing as this is a known WinUI issue.
