### ISSUE TITLE
Add support for running cmd files as administrator

### ISSUE THREAD

**Issue by slayermaster** [files-community/Files#6333]
### What's the Problem?

add run as admin on cmd files

### Solution/Idea

please add run as admin on .cmd files. currently it only shows run as admin on .bat and presumably .exe files.

### Alternatives

running the files using the native file explorer

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.0.13.0

### Windows Version

Windows 11 Pro 22471.1000

**Comment by maicol07** [comment]
There was a PR about this: #2846

However, it seems that this feature needs to be readded

**Comment by DOWIT-JoelFrojmowicz** [comment]
+1
"Run as Administrator" is a must have for Files!

**Comment by yaichenbaum** [comment]
This issue should be resolved with #9268
