### ISSUE TITLE
[Question] How do tags work exactly?

### ISSUE THREAD

**Issue by christubuntu** [files-community/Files#6336]
I see that I can create color coded tags. But I see no way to see all files with same tags grouped together (like on MacOs). And there doesn't seem to be a way to pin those tags on the sidebar. So, how to interact with them?

**Comment by gave92** [comment]
A tag section on the sidebar is planned but not yet implemented.
At the moment you can find all files matching a tag color by using the searchbox in the upper right corner, e.g: `tag:orange`
