### ISSUE TITLE
More powerful sharing features

### ISSUE THREAD

**Issue by Svk1190** [files-community/Files#6339]
### What's the Problem?

File explorer or Files has very limited sharing features. 

### Solution/Idea

It would be great if Files has more powerful sharing, either natively or by extensions. We should be able to right click a file and choose to share it with various people /services /cloud locations. Some possible sharing options are : 
1) Share to hangouts /messenger / whatsapp can launch the corresponding website and share the selected file. 
2) Share to pushbullet can launch push bullet website and share the selected file, or else it can allow us to directly choose the recipient through sub menu, instead of opening a web page. 
3) We can pin a shared network folder in the share menu, so that it is possible to right click and send a file to a custom network folder. 
4) Save to cloud drives such as Google drive, One Drive, Dropbox, etc. 
5) Share to specific email address via cloud services. It would at first upload the file to a custom folder in the cloud service, and then add the email address to the list of collaborators. 
6) Share with Google lens / reverse image search should allow us to automatically search an image by launching the search engine web page. 

### Alternatives

Android has powerful file sharing features. Sharex also has powerful sharing features. But windows file managers do not have similar capabilities. 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow users to share files easily | Should |

### Files Version

2.0.16

### Windows Version

Windows 10 Pro 21H1 19043.1237

**Comment by yaichenbaum** [comment]
For what it's worth, Files can share to any app that integrates with the Windows share feature.

**Comment by yaira2** [comment]
v2.4.25 added support for the send to menu, does this solve the feature request?

**Comment by Svk1190** [comment]
The send to menu in Files is the same as well as the default file explorer. It has few options, but it does not cover any of the requested features.

**Comment by yaira2** [comment]
Can you update the list? I think 3 and 4 can be taken off.

**Comment by Svk1190** [comment]
Currently the send to menu shows 6 items: Bluetooth, Zip, Desktop, Documents, Fax and Mail. 
Points 3 and 4 requests the ability to pin a shared folder or a cloud folder on this list. So now the list can possibly have 8 items:
Commonly used shared folder, Commonly used cloud folder, Bluetooth, Zip, Desktop, Documents, Fax and Mail. 

The motivation for this is the user can directly send a file copy to the commonly used destination folder instead of having to copy and paste each time. 

I hope I was able to explain this. If you think this feature is not needed, I can remove points 3 and 4.

**Comment by Josh65-2201** [comment]
@Svk1190 Is this still an issue for you. 
You can also add folders to the send to menu as a shortcut then it copy the file/folder to it. Type `%appdata%\Microsoft\Windows\SendTo` into Files address bar > Click `New` on the toolbar > Click `Shortcut` > Add folder/could sync folder.
