### ISSUE TITLE
Cant delete files on drive set to not use the recycle bin

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#6340]
### Description

When I set recycle bin properties for a drive to permanently delete files and not use the recycle bin, deleting items in files will always fail.

### Expected behavior

It should automatically set permanently delete option on for the file.

### Files Version

2.0.13.0

### Windows Version

10.0.19043.1237

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7297182/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7297183/debug_fulltrust.log)

**Comment by josh-65** [comment]
No its enabled and work for all other files when deleting them.
