### ISSUE TITLE
Clicking on an empty space while in column layout crashes the Files2.0 on Windows 10

### ISSUE THREAD

**Issue by Zusurs** [files-community/Files#6341]
### Description

As explained in the title - when using the Files 2.0 on Windows 10 and enabled Single-click-open setting, app crashes every time when user clicks in empty space in the column. Please take a look at the added **debug.log** file, there is an error regarding this crash.

### Steps To Reproduce

1. Open Files 2.0
2. Open settings, enable "Single click to open file"
3. Switch the layout to Column view
4. Open any folder that have a small number of items inside
5. Click on the empty space on the bottom part of any column

### Expected behavior

Expectedly nothing should happen (just like clicking on empty space inside the folder). App crashes instead.

### Files Version

v2.0.13.0

### Windows Version

Windows 10 (20H2, build 19042.1237)

### Relevant Assets

[debug_fulltrust.log](https://github.com/files-community/Files/files/7297194/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7297195/debug.log)

**Comment by josh-65** [comment]
Same as #6327
