### ISSUE TITLE
Screen dips down to 60fps when opening the app

### ISSUE THREAD

**Issue by lawilson97** [files-community/Files#6344]
Specs:

- 8700K
- 64GB 3200MHz C16
- 3080
- 500GB 970 EVO Plus

When opening the app, as well as folders and files inside the app, my 240Hz monitor dips to 60fps until each item has fully loaded. No other apps are running.

Latest version of Windows 11 as of this post and all drivers are up to date.

**Comment by 42-star** [comment]
Thanks

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

If it's still an issue, I recommend reporting this on the WinAppSdk repository.
