### ISSUE TITLE
Files app crash every time i try to use it

### ISSUE THREAD

**Issue by KarimMandor** [files-community/Files#6347]
### Description

Files app crash every time i try to use it

### Expected behavior

Drivers (C,D and E) dose not show in home screen
folders don't open
app closes from itself 

### Files Version

Version: 2.0.13.0 OS Version: 10.0.19043.1237

### Windows Version

Win 10 Version 21H1

**Comment by d2dyno1** [comment]
@KarimMandor Please upload log files and debug files. (Settings > About)
