### ISSUE TITLE
Consider participating in Hacktoberfest

### ISSUE THREAD

**Issue by creativefisher** [files-community/Files#6349]
### What's the Problem?

more people will contribute if this projects participates in Hacktoberfest 

### Solution/Idea

Here is how: https://hacktoberfest.digitalocean.com/resources/maintainers

### Alternatives

N/A

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

N/A

### Windows Version

N/A

**Comment by d2dyno1** [comment]
@yair100 Should this be closed?
