### ISSUE TITLE
[Feature Request] Better right-click context menu when rightclicking the app on the taskbar

### ISSUE THREAD

**Issue by arihant2math** [files-community/Files#6350]
### What's the Problem?

When you right-click the menu is the default menu and does not have shortcuts

### Solution/Idea

Add a custom right-click menu when you right-click on the app on the taskbar.

Files right-click:
![files rightclick](https://user-images.githubusercontent.com/58895652/136328928-402c9912-2cf0-493d-9ed9-f354d7543d9a.png)

File Explorer right-click:
![Screenshot 2021-10-06 230217](https://user-images.githubusercontent.com/58895652/136328989-87bbfd3c-1c49-4f73-8e47-8db281e2f10d.png)

### Alternatives

None

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Allow end users to right-click on the app on the taskbar and see a more relevant context menu| Must |
| Allow end users to customize what happens when the right-click the app on the taskbar | Could |

### Files Version

v2.0.13 (its the default behavior of any app)

### Windows Version

Windows 11 21H2 2200.346

**Comment by d2dyno1** [comment]
Hi! Files already has a "Recent" section in the taskbar context menu.

**Comment by arihant2math** [comment]
hmm weird, it still looks like the default context menu in the taskbar, I wonder if this is even possible with UWP.

**Comment by yaichenbaum** [comment]
@arihant2math this should already be supported, if it's not working as intended, can you open a new issue as a bug report together with the log files so we can look into why it's not working?
