### ISSUE TITLE
Exploration for title bar design to match that of Edge more closely

### ISSUE THREAD

**Issue by SubjunctiveQuaver** [files-community/Files#6351]
### Solution/Idea

Files v2 looks very pretty, but at the moment, it looks quite different from Microsoft Edge on Windows 11. Perhaps this is a point of differentiation, but for consistency, perhaps a tabbed design matching that of Edge can be available as an option? (This is the main thing that's keeping me away from Files at the moment, as it just feels a bit different and not native.)

![image](https://user-images.githubusercontent.com/49895442/136339476-9c778f5b-0541-47d4-9b84-14c39ae82b08.png)
![image](https://user-images.githubusercontent.com/49895442/136340272-3b023f83-bbdc-4079-a9df-054fea0c6755.png)

Another thing I've noticed is that the Mica effect on Files is very very mild compared to Edge in the titlebar area (see this picture):

![image](https://user-images.githubusercontent.com/49895442/136339657-8ddce9be-3116-404d-a45f-b1798d0f3fa7.png)

Would it be a good idea to make the Mica effect a similar strength so that the background comes through more? Right now, it is barely visible for me.

### Alternatives

Not doing anything, but this means that the design is a fair bit different to Edge (which is OK if that is the intended design).

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Mica effect strengthened in title bar (inactive tabs) | Must |
| Current tab integrates into address/search bar (solid colour) | Should |
| Title bar design matching that of Edge | Should |
| Tab dropdown moved to far left like for the vertical tabs switcher | Could |
| Change the position of the tools below the address bar | Won't |

### Files Version

v2.0.13.0

### Windows Version

Windows 11 21H2 22000.194

**Comment by ArtexJay** [comment]
Now Files and Edge have both switched tab styles with one another it seems.
