### ISSUE TITLE
When typing the first letter of file/folder name, view should scroll to the position of the item, as it does in every other file explorer

### ISSUE THREAD

**Issue by Zusurs** [files-community/Files#6354]
### What's the Problem?

When using a feature where you can simply type the first letter of the item to select it (not the search bar, but simply typing a first letter of item when opened a folder), item is being selected, but viewport doesn't scroll to the location of selection.

### Solution/Idea

Default Windows and Linux file explorer behavior allows user to simply type in first (or first few) letters of the file/folder name, and it's automatically selected (you can then use arrow keys to navigate to other items). This feature also works in Files 2.0 (file gets selected as expected - if you have preview pane turned on, you can see that the item is actually selected once you type the first letter of its name), BUT for whatever reason the viewport doesn't actually scroll to the location of the file, which leads to a very confusing behaviour. It should be fixed.

### Alternatives

There is no alternatives to consider - all it takes is to make sure that this feature works fully, as intended.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Typing any letter(s) selects the file, and view should scroll to the position of selection | Must |

### Files Version

2.0.13.0

### Windows Version

Windows 10 (20H2, build 19042.1237)

**Comment by yaira2** [comment]
This is already supported, if for some reason it's still not working, please open a bug report so that we can investigate.
