### ISSUE TITLE
Can not copy paste files if you for some reason have 2x Files 2.0 windows open

### ISSUE THREAD

**Issue by Shamatix** [files-community/Files#6359]
### Description

Soif I have 2x Files 2.0 windows open like this https://i.imgur.com/OQcG1zw.png  the copy paste functions no longer works, however if I close one of em it will work fine again

### Steps To Reproduce

Open 2x Files 2.0 windows
Now try copy paste files, nothing will happen
https://i.imgur.com/jdnB5vc.gif (Gif showing how I reproduce)

### Expected behavior

Copy and pasting files as per usual :)

### Files Version

2.0.13.0

### Windows Version

Windows 11

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?
