### ISSUE TITLE
Middle Mouse Click For Horizontal Scrolling Causes Crash In Column Layout 

### ISSUE THREAD

**Issue by the-phuctran** [files-community/Files#6362]
### Description

In folder column layout, if you middle click in the column contains folders and drag horizontally, the app will crash with the error:

![image](https://user-images.githubusercontent.com/43033446/136362980-a9b17af0-f495-46ac-89fe-6bd1406dfaf7.png)

### Steps To Reproduce

1. Set layout of a folder to "column"
2. Middle click in any column contains folders.
3. Drag it or just wait and app crashed.

### Expected behavior

Middle click or long click to horizontally scroll in column layout.

### Files Version

V2.0.13.0

### Windows Version

Windows 10 21H1 19043.1266 and Windows 11 21H2 22000.194

### Relevant Assets

[debug_fulltrust.log](https://github.com/files-community/Files/files/7301609/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7301611/debug.log)

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?
