### ISSUE TITLE
Renaming a file is aborted when marking text parts with the keyboard in specific layout modes

### ISSUE THREAD

**Issue by ddudda174** [files-community/Files#6363]
### Description

I usually use `STRG`+`SHIFT`+`→` (or `←`, `POS1`, `END` keys) to mark segments of the filename's text while renaming the file's name. This only works for symbols/tiles mode (all sizes), but not for the other layout settings (marked in red):
![image](https://user-images.githubusercontent.com/67892761/136378106-313c94ce-75a0-4872-8bf5-9b010bac584c.png)

### Steps To Reproduce

1. Open a folder with Files
2. Change to a (folder) layout except the symbol layouts (e.g. Details)
3. Create or select a file and rename it
4. Inside the textbox try to mark text segments while holding STRG+SHIFT and pressing an arrow key or Pos1 or End
5. The renaming will be canceled and focus might switch to another Files control (e.g. forward/backward)

### Expected behavior

Normal editing and selecting/marking of the desired text segments while using the mentioned key combinations in every layout mode.

### Files Version

v2.0.13.0

### Windows Version

Windows 10 (Version: 10.0.19043.1266)

**Comment by ddudda174** [comment]
Found duplicate issues: #6778, #7187 and #7337

**Comment by yaichenbaum** [comment]
This issue was resolved in v2.1.
