### ISSUE TITLE
[Feature Request] Add clear all button in the Ongoing tasks flyout

### ISSUE THREAD

**Issue by pratyakshm** [files-community/Files#6365]
### What's the Problem?

Users have to click on each task to clear it from the Ongoing tasks flyout. This is an annoyance when someone's doing a lot of file operations. 

### Solution/Idea

I want to have the *Ongoing tasks* flyout have a Clear all button to clear all inactive / currently not progressing tasks. 

This is how it looks like currently: 
![image](https://i.imgur.com/z71nDpe.png)

This is how I want it to look like: 
![image](https://i.imgur.com/QQyUaaJ.png)

The highlighted area will have a button button "Clear all" to clear all inactive tasks in one click.

### Alternatives

Nothing so far

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to clear all inactive tasks in one click | Must |
| This button could be a text button saying "Clear all" instead of an X button | Could |

### Files Version

2.0.16.0 

### Windows Version

Windows 11 Pro 21H2 22000.194 in production

**Comment by AkazaRenn** [comment]
My suggestion is that all successful tasks are removed by default, so we don't need to take care of them after they finish. That would also align with what the native file explorer does: a pop up that disappears right after the task is done.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7025.
