### ISSUE TITLE
[Feature Request] Make active ongoing task appear on the top in Ongoing tasks flyout

### ISSUE THREAD

**Issue by pratyakshm** [files-community/Files#6367]
### What's the Problem?

When a lot of file operations are happening / have happened, the Ongoing tasks flyout is populated with their status. Whenever a new task is performed, it always shows up next to the last task, which creates a design problem where end users won't be able to look out for an active task unless it appears on the top or they manually scroll all the way down in the Ongoing tasks flyout.

### Solution/Idea

Make the active task(s) appear on the top of the list in Ongoing tasks flyout.

### Alternatives

None

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow users to easily track an active task without scrolling | Must |

### Files Version

2.0.16.0

### Windows Version

Windows 11 Pro 21H2 22000.194 in production

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7022.
