### ISSUE TITLE
Cannot open Appdata or most of it's subfolders (Roaming/Local) from external applications

### ISSUE THREAD

**Issue by christubuntu** [files-community/Files#6369]
### Description

So, I've replaced File Explorer with File V2 using the registry method. Everything gets redirected to it except when I open the Appdata Folder from any external sources, Like Everything Search, Windows Run dialog, etc.

### Steps To Reproduce

1. Open Run window (Win+R)
2. type %appdata% and Enter
3.  I get this error message
![run](https://user-images.githubusercontent.com/55885756/136389601-688cde5f-6440-49c2-8345-4958d58be0ba.png)

or
1. Search for Roaming in Everything Search
2. Double click to open it and you get same error
![file](https://user-images.githubusercontent.com/55885756/136389825-b3ac7ede-a190-4a8b-8b10-f37ec99c9256.png)

### Expected behavior

File V2 should open those folders since I've set it to show hidden files/folders.
Notice that I can open the temp folder from both Everything and Run, even though it's in Appdata subfolder.

### Files Version

v2

### Windows Version

Windows 11 22000.194

**Comment by yaira2** [comment]
Is this still an issue in v2.4?
