### ISSUE TITLE
Layout Column Doesn't remember the sorting. 

### ISSUE THREAD

**Issue by EvilCheez** [files-community/Files#6370]
### Solution/Idea

It would be really nice if in Column view the app remembered the sorting. If you change the sorting to, let's say, by type, the app doesn't remember that if you go to another folder and come back to the one you've already changed the sorting. 

Not sure if that makes sense, but it really gets annoying after a while because you have to constantly change the sorting of files. 
This also happens everytime you open the app and something else that seems strange, the sorting by name, doesn't respect the folders, and that means that the default option is to see folders and files mixed together. 

### Alternatives

I think a solution would be to have an option in the settings where you can select which view and sorting you want to be as a default and if you change a folder to a different view or sorting the tab would remember that. 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.0.13.0 OS Version: 10.0.19043.1237

### Windows Version

Edition	Windows 10 Pro Version	21H1 Installed on	‎31/‎1/‎2021 OS build	19043.1237 Experience	Windows Feature Experience Pack 120.2212.3530.0

**Comment by parideis** [comment]
👍 This is the only missing feature for this otherwise perfect App for me. 😄

**Comment by lukefisklennon** [comment]
What's the status of this?

**Comment by delirium-sidhe** [comment]
Also having this issue. No solution or workarond so far?

**Comment by yaira2** [comment]
@EvilCheez can you share some steps I can use to reproduce the issue?
