### ISSUE TITLE
Bug: Folder thumbnails have a black background

### ISSUE THREAD

**Issue by 0ssamaak0** [files-community/Files#6373]
### Description

The first time thumbnails are displayed for each folder, they are displayed with a black background.
![image](https://user-images.githubusercontent.com/53372259/136399794-924c4cb7-2ade-4891-9373-23284f22309b.png)

### Steps To Reproduce
1. Clear thumbnail cache in Windows
2. Open Files and navigate to any directory with folders
3. Observe error
4. Refresh directory and observe the black background is gone

### Expected behavior
- Black background should never show

### Files Version

Version: 2.0.13.0

### Windows Version

Version: 10.0.22000.194

**Comment by viniciusdel** [comment]
Issue still persists.

**Comment by Radical4ever** [comment]
the only "solution" i could find is press f5. but i guess this is some error at the time file manager start loading the folder icon and when it has some file inside of it changes to the folder with files icon. it has something to do with the loading of icons :P

**Comment by dodyakako** [comment]
Is this issue going to be fixed soon?

**Comment by Radical4ever** [comment]
> Is this issue going to be fixed soon?

Yeah its going to be fixed but they have a lot more issues to deal, see the projects section and you should see how many things they have to be fixed, and this one.

**Comment by dodyakako** [comment]
> Yeah its going to be fixed but they have a lot more issues to deal, there are many things they have to be fixed, and this one. But yeah this appeareance issues should be fixed asap

I hope so because it's so annoying.

**Comment by carlosvsilva** [comment]
Now even MS Windows Explorer is showing black boxes around the folders icons that are accessed or modified, not sure which !!

**Comment by setzor** [comment]
Can confirm still an issue on v2.3.0.0

![image](https://user-images.githubusercontent.com/9101477/176621062-b32547f7-6fef-4153-a575-2202cee048bf.png)

**Comment by carlosvsilva** [comment]
yes, it's one of the 2 show stoppers still present in Files unfortunately, it's this major bug and discarding the current view mode when opening new subfolders, with the option per folder view mode enabled. 😟

**Comment by AndrewLaganaro** [comment]
Same happens with me. Folders and files have no special characters or something like that. just normal names. I think it happens when there's new content on the folders.


image 1:
![image](https://user-images.githubusercontent.com/45211616/180123414-ebafc560-d556-4d57-a0a5-c6be859f6a56.png)

image 2:
![image](https://user-images.githubusercontent.com/45211616/180123431-5f318170-d027-41a8-9771-44538b6e4af1.png)

Image 3:
![image](https://user-images.githubusercontent.com/45211616/180123440-51fdbd27-cef6-4af7-abee-2cde06c60d79.png)

**Comment by arytapermana** [comment]
Refreshing the directory (shortcut F5) fixing this bug and then coming back to that directory no black background showed again. I think the problem is when loading the first-time icon folder that's never opened.
