### ISSUE TITLE
Context menu in windows 11

### ISSUE THREAD

**Issue by VinConstantin** [files-community/Files#6380]
### Description

The context menu in Files doesn't show up any of the third party items. For example, I have 7zip installed, but when I right click on a directory, the is no option showing up to compress the file. In the standard file explorer, the options in the context menu are shown.
![image](https://user-images.githubusercontent.com/26585839/136444022-8896df4b-06df-4cc8-aff1-d3d8a6e0bc39.png)
 

### Steps To Reproduce

1. Right click on any directory/file/p[en space
2. No option showing third party context menu items

### Expected behavior

There should be an item in the context menu showing dialog where you can access more options. From there, you'll have access to all of the items of the context menu.
![image](https://user-images.githubusercontent.com/26585839/136444556-20642f96-3815-4ef8-b3a1-ca88a196f54c.png)

### Files Version

2.0.0.0

### Windows Version

Windows 11 Version	10.0.22000 Build 22000

**Comment by gave92** [comment]
No problem, having to scroll is not intuitive at all and it's a bug we're looking to fix.
