### ISSUE TITLE
Doesn't respect default zip app

### ISSUE THREAD

**Issue by DizzyFop** [files-community/Files#6381]
### Description

Opening a zip file should open it in the default app or at least have an option to not use files integrated zip opener

### Steps To Reproduce

1. Open zip file
2. Opens in files zip preview 

### Expected behavior

1. Open zip file
2. Opens in default zip app (Winrar, 7-zip) 

### Files Version

Version: 2.0.13.0 

### Windows Version

OS Version: 10.0.22000.194

**Comment by josh-65** [comment]
Related #6110
