### ISSUE TITLE
Support for "show in folder"

### ISSUE THREAD

**Issue by Doda94** [files-community/Files#6382]
### What's the Problem?

Currently "show in folder" option, found in 3rd party apps, opens the folder where the file is located but does not highlight the file itself.
Below is an example from Telegram Desktop app.
![yfXPlWOHoh](https://user-images.githubusercontent.com/56204086/136457668-bdd31988-8253-4a07-a64a-170dc4c25787.gif)

### Solution/Idea

Make the app highlight selected files.

### Alternatives

None?

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to find the file they are looking for. | Must|

### Files Version

Version: 2.0.13.0

### Windows Version

Windows 11 21H2 22000.194

**Comment by m1karii** [comment]
Files not having ability to highlight items in folder is the only reason why im not using it as default file manager. I'd really appreciate this feature.

**Comment by gave92** [comment]
Pushed here: https://github.com/files-community/Files/tree/show_in_folder a test branch that adds support for highlighting the item when using "show in folder". Code is taken from Explorer++. Unfortunately it appears it does not work reliably, e.g works from the start menu but not from edge (same does Explorer++).

**Comment by Pietro228** [comment]
Any update?

**Comment by gave92** [comment]
@Pietro228 not really, this thing is hard. Currently we got "show in folder" highlight the item when done from the start menu, but doesn't work when invoked from anywhere else.

**Comment by yaira2** [comment]
Merging with #9390
