### ISSUE TITLE
Holding alt while double clicking to open properties - no longer working

### ISSUE THREAD

**Issue by bdr99** [files-community/Files#6383]
### Description

This feature was originally requested in https://github.com/files-community/Files/issues/3105, and added in https://github.com/files-community/Files/pull/4441, but it was removed in https://github.com/files-community/Files/pull/4365. The removal looks to be by mistake.

### Steps To Reproduce

1. Hold Alt
2. While holding it, double click a file or folder

### Expected behavior

The properties should window should open, but instead, it opens the file or folder.

### Files Version

2.0.13.0

### Windows Version

Windows 10 21H1 19043.1237

**Comment by yaichenbaum** [comment]
I don't know if this was ever supported but you can access properties from the `alt` + `enter` shortcut.
