### ISSUE TITLE
Folder optimization-type feature missing

### ISSUE THREAD

**Issue by eniweii** [files-community/Files#6385]
### What's the Problem?

There is no "folder optimization". In native File Explorer you have that option, changes the information the columns have. I have attached both File Explorer and Files windows with their properties options to be more clear.

![columns on Files](https://user-images.githubusercontent.com/92127415/136474853-ff7a4373-9521-440c-aeb0-32bce79f6207.png)

![Properties Files](https://user-images.githubusercontent.com/92127415/136474893-9990e734-bd78-4de1-a6b0-5605ad49f01a.png)

File Explorer
![native filee explorer columns in music-optimized folder](https://user-images.githubusercontent.com/92127415/136474736-6d3230af-28d9-4d7c-a575-ed1854a13a02.png)

![Properties>Optimize folder window in native file explorer](https://user-images.githubusercontent.com/92127415/136474131-173cba4d-de8e-41ca-892a-d77ab133a1d8.png)

### Solution/Idea

adding this feature if possible

### Alternatives

adding the columns but not the properties>optimize folder for if changing properties is not possible 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must | 
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't | 

### Files Version

Version: 2.0.13.0

### Windows Version

Windows 10 Pro 21H1 19043.1266

### Additional comment

device type:laptop

**Comment by yaichenbaum** [comment]
Would this be any different than the option to hide and show columns?

**Comment by eniweii** [comment]
show/hide columns depending in the file-optimized folder type- in the case of music folders columns like in the image submitted

**Comment by josh-65** [comment]
Same as #5564
