### ISSUE TITLE
Other apps don't respect ascending and descending order

### ISSUE THREAD

**Issue by Superjack78** [files-community/Files#6386]
### Description

When opening images with image class (a open source image viewer) while viewing in descending order using the arrow keys to move left and right are opposite * Watch video for a better explanation

This is really annoying when trying to view hundred of screenshot photos and the arrow keys are backwards.

By the way the whole sorting views should be rewritten just try messing around with it by clicking different options, it will forget where it was (showing a different mode then you have selected) and it'll let you choose ascending and descending at the same time well in small icons layout.

### Expected behavior

Well opening an image click in the right arrow key should go to the picture on the right not on the left well sorted by descending order

### Files Version

Version: 2.0.13.0

### Windows Version

OS Version: 10.0.22000.194

### Relevant Assets

![ezgif com-gif-maker](https://user-images.githubusercontent.com/54298425/136482476-da2a7268-992d-49d0-a77c-2a35f8565651.gif)

**Comment by josh-65** [comment]
Files cant interact with other programs to do that. I don't even think file explorer support it. That photo viewing app will just get the contents of the folder to allow scrolling through them using it own sorting system.

**Comment by Superjack78** [comment]
> I don't even think file explorer support it.

@josh-65 Did you watch the video it works fine on file explorer? Shouldn't files just be able to re-organize the order of images?￼￼
