### ISSUE TITLE
Unresponsive Column Height

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#6388]
### Description

It seems like the text in the column doesn't have the appropriate height which cause the column looks odd.

### Steps To Reproduce

1. Open Any Directory (Download, Desktop, C:, D:, etc)
2. See the column
3. See error

### Expected behavior

The text in should be aligned properly.

### Files Version

v2.0.16.0

### Windows Version

Windows 11 21H2 22000.194

### Relevant Assets

![Unresponsive Column Height](https://user-images.githubusercontent.com/69080584/136488384-1a903ec6-f9a0-4b39-9dda-59757d2931a0.jpg)

**Comment by yaichenbaum** [comment]
This was a deliberate design choice to provide a separation between the toolbar above the header.
Fyi @itsmichaelwest

**Comment by stanleyowen** [comment]
Ahh I see, however tbh I'm still not used with the design 😂. But I really appreciate it!

**Comment by yaichenbaum** [comment]
> Ahh I see, however tbh I'm still not used with the design 😂. But I really appreciate it!

Good feedback! I think this is better than the alternative issue of having there be too much information stacked on top of each other, but we can definitely gather some feedback on this.
