### ISSUE TITLE
Paste file command not responding

### ISSUE THREAD

**Issue by cognociente** [files-community/Files#6391]
Windows 11
Neither control-v nor the buttons are working.
I can drag files into the folder to copy them in though.

**Comment by Suprethreal** [comment]
Fresh Install v2.0.13 with no modifications.
First thing I tried was to copy in some theme files from an extracted folder. Doesn't work.
I thought maybe because it's In C drive but trying other folders and files and it doesn't work either.
No error message. Just doesn't paste with ctrl+v

**Comment by gave92** [comment]
@Suprethreal exact windows version?

**Comment by Suprethreal** [comment]
@gave92

Win 10 build
19043.1237

**Comment by yaichenbaum** [comment]
@cognociente this issue should be resolved in v2.0.34.
