### ISSUE TITLE
Search function finding unreliable results

### ISSUE THREAD

**Issue by Rayuaz** [files-community/Files#6396]
### Description
When searching for something, the results are never the same as using the search function on the default file explorer. Sometimes it shows only folders, sometimes it shows a few of the matching items, but it never gives the same results as the windows explorer search. This would be fine (even better than the default search experience) if it at least displayed all of the items in the current folder, but even that doesn't always happen. I have included a couple screenshots to illustrate the problem.

### Steps To Reproduce
1. Open the same folder on the default explorer and on Files
2. Perform the same search on both

I also tried searching for unindexed items, and that didn't work (and the files I was looking for were indexed anyway).

### Expected behavior
It should show all the matching items in that folder.

### Files Version
2.0.13

### Windows Version
Windows 11 Pro - 21H2 - 22000.194

#### Files
![image](https://user-images.githubusercontent.com/67298960/136575730-45d917ac-ab10-46e3-b954-cba39255196b.png)
#### Explorer
![image](https://user-images.githubusercontent.com/67298960/136575775-f107adf4-725c-4acc-be8a-6f0b1eba1cd4.png)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #6671.
