### ISSUE TITLE
Shift + Double Click on folder makes Files crash

### ISSUE THREAD

**Issue by Meetem** [files-community/Files#6400]
### Description

Freeze and then crash occurs when folder is opened (double-clicked) while shift is held.

### Steps To Reproduce

1. Open Files
2. Hold shift key
3. Double-click folder
4. Get freeze, and then application close.

### Expected behavior

Shift/Control key should open folder in new tab/instance.

### Files Version

2.0.13.0

### Windows Version

Windows 11: 10.0.22000.194

### Relevant Assets

This is the only messages about crash
```
2021-10-08 21:34:33.2541|ERROR|AppUnhandledException|Catastrophic failure

Catastrophic failure

	System.Exception: Catastrophic failure
```

Exception file
[0ad6c656-c8e9-41d0-bf82-456679aa13d2.exception.txt](https://github.com/files-community/Files/files/7313513/0ad6c656-c8e9-41d0-bf82-456679aa13d2.exception.txt)

**Comment by gave92** [comment]
Does this happen in all layout modes or only e.g. in Tiles view? Does it happen all the time?

**Comment by Meetem** [comment]
Yes, it happens all the time. But I’ve only tested list layout (the one
like in default explorer with file name, date and size)

**Comment by Meetem** [comment]
Yeah, I can do that.
