### ISSUE TITLE
Clicking empty space crashes the application

### ISSUE THREAD

**Issue by mimoguz** [files-community/Files#6401]
### Description

When using column layout and single click to open option selected, clicking on the empty space in a column crashes the application.

### Steps To Reproduce

1. Select column layout.
2. Select "Open items with a single click" option in the settings dialog.
3. Click on the empty space in a column.

### Expected behavior

No crash.

### Files Version

2.0.13.0

### Windows Version

Windows 11 21H2 22000.194

**Comment by gave92** [comment]
Should be fixed in v2.0.16.0 💪
