### ISSUE TITLE
FTP function not working

### ISSUE THREAD

**Issue by bznemmanuel** [files-community/Files#6402]
### Description

When accessing an FTP server on my LAN, it does not show the login window and the folder appears empty.
![Captura001](https://user-images.githubusercontent.com/92181196/136611773-6f62564e-2642-4e6f-b383-245b40e5c420.png)
![Captura002](https://user-images.githubusercontent.com/92181196/136611796-d036aa00-151e-401e-8dcf-d567529a1434.png)

I can't find any option to configure access with username and password in the security settings.
![Captura](https://user-images.githubusercontent.com/92181196/136611801-276e239f-f91b-4dab-a7a0-10221244387e.png)

### Steps To Reproduce

1. Open App
2. Enter ftp address in the direction bar
3. Folder empty

### Expected behavior

Login window to access the ftp server.

### Files Version

OS Version: 10.0.19043.1266

### Windows Version

Windows 10 Version 21H1 (Build SO 19043.1266)

**Comment by gave92** [comment]
Thanks for the report. It's supposed to be asking for user/pw the first time the folder is open unless access as "anonymous" does not return error, maybe that's the issue.

**Comment by gave92** [comment]
Merging with #5833
