### ISSUE TITLE
Add open with option for directories

### ISSUE THREAD

**Issue by mimoguz** [files-community/Files#6403]
### What's the Problem?

VS Code adds "Open with Code" option to the context menu for files and folders.  Very useful to quickly open projects.

For files there is already the "Open with" context menu item, so less of an issue here.

### Solution/Idea

Add "Open with" context menu item for folders too.

### Alternatives

A single program/list of programs that can be configured using settings dialog to open folders with. 

### Files Version

2.0.13.0

### Windows Version

Windows 11 21H2 22000.194

**Comment by mangoepic** [comment]
I would also love to see this feature. I'm thinking what programs this might actually be useful for.
- all of the IDEs mostly opening folders as projects (IntelliJ, vscode, visual studio)
- Zip explorers (7zip, winrar)
- FTP Explorers like FileZilla?

It would be more irrelevant for
 - Programs that have their own project manager (Unity, Photoshop, Blender ...)

Do you have more ideas? I think it would be a cool feature nevertheless. I couldn't imagine being annoyed by a open with... dialogue for rightclicking on a folder even if I wouldn't use it very much

**Comment by mimoguz** [comment]
I guess that needs to be a custom dialog, since File Explorer also doesn't have it, right? If so, maybe Open with -> File Explorer can be pinned on top, since not everything (like drag & drop from 7-zip file manager) works with Files.

**Comment by mangoepic** [comment]
From my linked issue:
> I think it would be cool to be able to right click on folders and select "Open with... >" just like you might with files.
> 
> Implementation idea:
> It then shows you a list of a maximum of n programs you recently used to open folders and "more options..."
> If it doesn't work straightforwardly maybe a configuration json file where you can set up command line arguments for the program

![image](https://user-images.githubusercontent.com/71931749/137622865-70f39cc3-71e7-4021-a3b6-82e539b7c807.png)

**Comment by yaichenbaum** [comment]
@mimoguz can you share some programs that can open directories? Ideally this would be applications that don't already add a shell item to the context menu.

**Comment by tellmewhy12** [comment]
@yair100 Open directories in general (like while having the application open and navigating through menus) or open directories in a specific way (like dragging the folder on the executable / specific commandline arguments?)

Also I think it might still be nice for Applications that have an entry in the shell menu anyways (if the user enabled it for that) so these could be together with other apps in a submenu

**Comment by mimoguz** [comment]
@yair100 They do now :) That wasn't the case when I made the suggestion.  I still think this might be nice addition, but less useful now than then.

**Comment by yaichenbaum** [comment]
We're tracking a similar idea to group related actions together.
