### ISSUE TITLE
Column View not working properly when navigating with keyboard

### ISSUE THREAD

**Issue by dybck** [files-community/Files#6404]
### Description

When using the keyboard for navigation through folders in the column view, the content of the opend folder (with Enter) doesn't show up in the column to the right. Instead it acts like if there wasn't a column view and opens the folder in the exact same column of the parent folder. When I open a folder with the mouse, it does work properly and shows the content of the opend folder in a new column to the right.

### Steps To Reproduce

1. Create a folder with a subfolder.
2. Open the parent folder with the keyboard (Enter)

Opend the folder "Test" with the mouse. Child folder "Test1" showing up in the column to the right.
<img width="837" alt="open_folder_with_mouse" src="https://user-images.githubusercontent.com/92184278/136621060-a5fe8304-31ba-44a6-b77e-73131a583ecf.png">

Opend the folder "Test" with the keyboard (Enter). Child folder "Test1" showing up in the same column. The column to the right stays empty.
<img width="839" alt="open_folder_with_keyboard_enter" src="https://user-images.githubusercontent.com/92184278/136621016-2665aa7d-cf92-4c4f-ac88-c69e4c252e78.png">

 

### Expected behavior

Child items of a folder should be displayed in the next right column when the folder ist opend with the keyboard (Enter), like it does when using the mouse.

### Files Version

Version: 2.0.13.0

### Windows Version

Windows 11 21H2 22000.194

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7425
