### ISSUE TITLE
File.exe or Files.msi

### ISSUE THREAD

**Issue by D1mar0n** [files-community/Files#6406]
### What's the Problem?

Good day! Could you also publish new versions with the file extension ".exe" or ".msi"? For users who are not using the Microsoft Store, this would be very helpful! I really hope to see a new version with the ability to install on your system without the help of the Store. Thank you in advance!

### Solution/Idea

Installer Files with file extension ".exe" or ".msi"

### Alternatives

Not.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

v2.0

### Windows Version

Windows 11 21H2 22000.194

**Comment by D1mar0n** [comment]
Thank you very much for your reply! I do not have this installer, as well as the store itself. I, like many users, do not use the Store and everything connected with it. After installing the system, we immediately remove all the "treasures" from Microsoft)) Over the years, I first wanted to install something from the Store, but of course I don't want to leave the Store, its installer and all their other nasty things because of one application .. For this reason alone, I ask you to publish the installer with standard extensions whenever possible. You probably know about OS versions where the Store is not initially included, and users of such systems also want to install Files.

**Comment by gave92** [comment]
You might need to also install some dependencies as explained in #6316.

**Comment by yaichenbaum** [comment]
@D1mar0n the app installer is an integral part of Windows and Files requires it in some for in order to be installed. I wrote up a quick guide on restoring AppInstaller in the event it was removed. https://yairai.medium.com/how-to-restore-windows-10-app-installer-99c15b7c3ec4.
