### ISSUE TITLE
It can copy but can't paste and drag

### ISSUE THREAD

**Issue by ExhYZ** [files-community/Files#6407]
### Description

Copy a file is okay and paste in windows default explorer, but it can't paste in Files or drag-and-drop.

### Expected behavior

Just fix it :)

### Files Version

v2.0

### Windows Version

Windows11 21H2 22000.194 Beta

**Comment by gave92** [comment]
Thanks for opening this issue.
- Are you using mouse or touch?
- Does copy/paste inside Files work if you use the context menu buttons?
- Could you upload the app's log files?

**Comment by duke7553** [comment]
@Suprethreal I'll close this duplicate then 🙂
