### ISSUE TITLE
Box Drive broken functionality

### ISSUE THREAD

**Issue by digital-mystik** [files-community/Files#6409]
### Description

When Files first loads, the cloud drive sidebar does not show Box Drive or OneDrive initially; when toggling the dropdown to hide and then show, the drives will become visible. When Box is selected, the root directory is shown but refreshes/reloads every few seconds. When entering one of the folders before it refreshes, its contents are empty.

### Steps To Reproduce

1. launch Files
2. toggle cloud dropdown
3. select Box
4. enter folder in Box Drive before refresh

### Expected behavior

1. launch Files
2. Box Drive should appear in cloud drive sidebar dropdown menu
3. after selecting Box Drive from the sidebar, the root directory should be static and not keep refreshing
4. entering a Box Drive folder should show its contents and work as a typical directory

### Files Version

v2.0.13

### Windows Version

Windows 10 Enterprise 20H2

### debug.log
```
GetDrivesAsync|Drive added: C:\, Fixed
EnumerateDrivesAsync|Adding cloud provider "Box" mapped to C:\Users\username\Box
EnumerateDrivesAsync|Adding cloud provider "OneDrive" mapped to C:\Users\username\OneDrive 
```

### debug_fulltrust.log (nothing specifically Box related shown)
```
ConnectionRequestReceived|Argument: GetIconOverlay
[repeat x60]
.
.
ConnectionRequestReceived|Argument: Terminate
```

**Comment by gave92** [comment]
Merging with #7428
