### ISSUE TITLE
Show all mounted drives (drives without letters) on home

### ISSUE THREAD

**Issue by bobsage123** [files-community/Files#6410]
### Description

I have several drives set as mountpoints. They don't have their own letters. Currently only 1 is appearing in Home. And this just so happened to be one that was previously a regular drive letter and I moved back to a mountpoint. It seems the only workaround is to temporarily give it a letter, then switch it back to a mount point.

### Steps To Reproduce

see above

### Expected behavior

Mounted drives will appear automatically.

### Files Version

2.0

### Windows Version

Edition	Windows 10 Pro Version	21H1 Installed on	‎6/‎4/‎2021 OS build	19043.1266 Experience	Windows Feature Experience Pack 120.2212.3920.0

**Comment by bobsage123** [comment]
Hello, has any more consideration been put into fully enabling this feature?

**Comment by gave92** [comment]
Still studying how to implement this :)

**Comment by bobsage123** [comment]
Awesome!

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?

**Comment by bobsage123** [comment]
> Is this still an issue in 2.3.3.0?

It still only shows the one mounted drive, B:\2

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
Do these show up in File Explorer?

**Comment by Josh-65** [comment]
From there request no since they dont have any drive letters left but they have assiged them to a NTFS folder. File explorer doesnt support showing them like files does on the home page.

**Comment by yaichenbaum** [comment]
I think it's best to keep them hidden as there are different reasons they might not have a drive letter and we don't want to mess around with this.

**Comment by bobsage123** [comment]
> I think it's best to stay consistent with File Explorer in this area.

Is there a settings file I could perhaps edit to manually add the rest of my mounted drives? Since we know it works based on the one mounted drive that showed up automatically.

**Comment by Josh-65** [comment]
From what i use any local drive mouted as a NTFS folder should just show up.

**Comment by bobsage123** [comment]
> From what i use any local drive mouted as a NTFS folder should just show up.

This may be the difference. I do see the one that shows up as having a folder icon and the rest have a hard drive icon.

How would I go about switching these to be mounted as NTFS?

**Comment by Josh-65** [comment]
If you go to disk managment and right click the partitions > Change letter or path > Add > Mount in the following empty NTFS folder > Select the location > OK . You can remove the drive letter if you have one for it after.

**Comment by bobsage123** [comment]
Hmm, this is actually how I mount normally for every drive but some don't show in Files.

Back to my other question, is there an XML or something where I can manually try adding the other mounted drives?

**Comment by Josh-65** [comment]
Drives aren't read from a file so proberly not. It calls Windows for them.

**Comment by yaichenbaum** [comment]
@bobsage123 you might be able to workaround this limitation by creating and adding the drives to a bundle.
