### ISSUE TITLE
Trackpad back/forward gestures not working

### ISSUE THREAD

**Issue by djcurley89** [files-community/Files#6411]
### Description

I have my trackpad gestures in windows set so that three finger swipes to the left and right navigate back and forward. This works in web browsers and the built in file explorer but does not seem to work in Files. *Note I'm not talking about overscroll based 2-finger back and forward gestures that chrome and edge now have but the actual built in windows gestures you can assign manually.

### Expected behavior

Back and Forward trackpad gestures to actually work

### Files Version

Version: 2.0.13.0 OS Version: 10.0.19043.1237

### Windows Version

21H1

**Comment by yaichenbaum** [comment]
@djcurley89 trackpad gestures weren't implemented yet. Currently tracking this feature request in #100.
