### ISSUE TITLE
[QUESTION] How can I use shell extensions with Files v2?

### ISSUE THREAD

**Issue by ezxpro** [files-community/Files#6415]
Sorry for opening an issue here, but I found no community where to discuss about the app.

Anyways, I got Files v2 from MS Store, where the description says it supports shell extensions. Turns out I use a lot of them and that's where I felt the most impact when using Files v2, because I can't see my shell extensions there.

**Comment by yaichenbaum** [comment]
Currently the only supported shell extensions are via the right click context menu, I'll update the Store description to clarify this.

**Comment by gave92** [comment]
Merging with #6416. It appears he's experiencing an issue with the context menu.
