### ISSUE TITLE
Change view on folder and it's subfolders

### ISSUE THREAD

**Issue by ezxpro** [files-community/Files#6417]
### What's the Problem?

When I change view mode on one folder, the subfolders are not affected. This is an issue when dealing with libraries. For example, my "Pictures" library has lots of subfolders. By default, files is in details or list mode, I'm not sure. The bottom line is I can't see the thumbnails.

If I change the view mode on the parent folder, it doesn't affect subfolders, and I have to change view mode on each of them.

### Solution/Idea

Making a view mode affect all sub folders is certainly not a good solution, however, if we could right click a folder and tick a checkbox that made it's viewmode affect all subfolders, I think this would be an elegant way of solving the problem persistently,

It would be important if from the moment the checkbox is set to "on", all changes on that folder affected it's subfolders recursively.

One possible problem would be, however, if in one of the subfolders, you wished to have a different view mode (either for that subfolder alone or for the subfolders inside this subfolder).

In general, I could not think of a satisfiable way one would handle the recursiveness of this, because if you "tick" that checkbox on the parent folder and it immediately affects all subfolders, how can one possibly manage that same configuration on the subfolders themselves?

### Alternatives

Well, I didn't think of any other alternatives. All I know is that as it is right now, it is kinda of a PITA to deal with view modes on libraries, because I have to alter it for every single folder.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to apply view modes to folders recursively | Must |
| This proposal will allow end users to change the view mode on all subfolders by altering the parent folder's view mode only | Should |
| On/off switch is on the folder's properties page, very visible and easy to reach  | Should |
| Avoid overly complicated ways of handling subfolders and recursiveness | Should |
| Maybe recursiveness could be locked as long as the parent folder has the switch on, so as to avoid a complicated implementation | Could |

### Files Version

Version: 2.0.13.0

### Windows Version

Windows 11 21H2 22000.194

**Comment by SubjunctiveQuaver** [comment]
Was just thinking about this! Would be similarly good to have it affect the sorting mode (e.g. for photos I like it sorted and grouped by date).

**Comment by yaira2** [comment]
Merging with #5564
