### ISSUE TITLE
iCloud link should be shown in Files v2 sidebar like it does in Windows Explorer (see screenshot attached)

### ISSUE THREAD

**Issue by Zusurs** [files-community/Files#6419]
### What's the Problem?

In Windows 10/11, if you have an iTunes installed, it places a very convenient (virtually essential to all who are using Apple product alongside of Windows PC) shortcut to the iCloud drive right in Windows Explorer left-hand sidebar (see image below). It would be very nice if Files v2 would add the same shortcut (should be straight forward for developers to install an iTunes and take a look at the registry key regarding the location of where this shortcut leads to).

iCloud link in Windows Explorer:
![2021-10-10](https://user-images.githubusercontent.com/15675443/136691650-ae1f4504-4713-4182-abfc-ea0116005d38.png)

### Solution/Idea

Investigate the registry key that is added by iTunes to find out where this link is pointing to, and if this registry key exists on user's machine, add the same shortcut to the Files v2 sidebar. Or at least give some option/settings toggle to add this shortcut to the Files v2 sidebar.

### Alternatives

Give some option/settings toggle to add this shortcut (or any other link to particular system folder) to the Files v2 sidebar - so that we can at least add this link to Files v2 sidebar ourselves.

### Files Version

v2.0.13.0

### Windows Version

Windows 10 20H2

**Comment by Josh-65** [comment]
Is this still an issue?
