### ISSUE TITLE
Add an option to always show icons, never thumbnails

### ISSUE THREAD

**Issue by Keefaetana** [files-community/Files#6421]
### What's the Problem?

I strongly prefer the option to always show only icons of all files instead of thumbnails, no matter which layout I deem fit for any folder. Unfortunately, I do not believe there is such an option currently in Files and I did not find a previous issue regarding this matter.

### Solution/Idea

Add an option to always show icons instead of thumbnails.

### Alternatives

None.

### Files Version

2.0.13.0

### Windows Version

10.0.19044.1237

**Comment by TizianoMad** [comment]
Actually, "Files" is trying to offer improvements in displaying thumbnails, though taking more control of your explorer should also be part of the app, I guess it would be normal to include what is already part of usual features of the classic windows file explorer.

**Comment by eliranbenishai** [comment]
Completely agree. I use a few network drives and Files is churning through every single folder to try to create thumbnails. First thing I did was comb the settings for the option to not show thumbnails, and it's sorely missing for me.
