### ISSUE TITLE
Application crash on properties change

### ISSUE THREAD

**Issue by Yurii17K** [files-community/Files#6425]
### Description

The app has crashed after I've changed the links to folders in the Library section.

### Steps To Reproduce

1. Add Libraries to the sidebar
2. Go to the properties of any of the folders in the sidebar.
3. Go to Library part (second).
4. Delete any NON-DEFAULT entry.
5. Click Ok.

### Expected behavior

No crash i guess

### Files Version

2.0

### Windows Version

Edition	Windows 10 Pro Insider Preview Version	2004 Installed on	‎01-‎Feb-‎21 OS build	21301.1010 Experience	Windows Feature Experience Pack 221.501.0.3

### Relevant Assets

![{FCD5CFB9-0786-49F1-9ABA-F3E9D7F36A11}](https://user-images.githubusercontent.com/56108535/136702620-2db28142-75cc-41c8-86e0-6e0d05f437d7.png)
![image](https://user-images.githubusercontent.com/56108535/136702639-8200453b-9aae-40a8-83ad-fcf98bd83758.png)

**Comment by gave92** [comment]
Looks the same as #6414. Could you upload the app's debug logs?
