### ISSUE TITLE
Deleting large files.

### ISSUE THREAD

**Issue by Syltti** [files-community/Files#6429]
### Description

When deleting a file that's too large to go into the Recycle Bin, Files will not actually delete the file. I have to switch back to the regular file explorere to do so.

### Steps To Reproduce

1. Find a very large file that the recycle bin can't hold.
2. Attempt to delete the file. Prompt will ask to permanently delete the file.
3. Files fails to delete the file (no error or anything, mouse icon shows its "working," but the file will remain.

### Expected behavior

Well... said file being deleted.

### Files Version

2.0.13.0

### Windows Version

Windows 11 21H2 22000.194

**Comment by gave92** [comment]
Thanks for the report
- Could you show the prompt(s) that are showed to you when trying to delete such files?
- Does it work if you tick the "permanently delete" option in Files confirmation dialog?

**Comment by yaichenbaum** [comment]
@Syltti can we get an update on this?
