### ISSUE TITLE
Drag and drop gets stuck until transfer is finished

### ISSUE THREAD

**Issue by ivanjx** [files-community/Files#6430]
### Description

When i drag a file from desktop to my SMB server it got stuck until the transfer is finished.

![image](https://user-images.githubusercontent.com/12814796/136727960-e9a05837-8e3c-4e6c-b843-85da6f76c031.png)

### Steps To Reproduce

drag a file into a network drive

### Expected behavior

drag icon not stuck

### Files Version

2.0.13.0

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎06/‎10/‎2021 OS build	22000.194 Experience	Windows Feature Experience Pack 1000.22000.194.0

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview build? https://files.community/download/preview
