### ISSUE TITLE
Dark color bug

### ISSUE THREAD

**Issue by Imchedlishvili** [files-community/Files#6432]
### Description

When I have chosen a dark theme and then click on the properties of the file opens a modal with a white background and white text.

![1](https://user-images.githubusercontent.com/47319323/136765241-6b685a94-bb54-4082-ab68-c51c1f81579a.png)

![2](https://user-images.githubusercontent.com/47319323/136765254-142b4864-419e-42b8-8e8e-b5e48a63e37b.png)

### Expected behavior

When I have chosen a dark theme and then click on the properties of the file opens a modal with a white background and white text.

### Files Version

Version: 2.0.13.0 OS Version: 10.0.22000.194

### Windows Version

windows 11 21H2

**Comment by gave92** [comment]
#6066
