### ISSUE TITLE
Copy files from anydesk

### ISSUE THREAD

**Issue by xeanhort** [files-community/Files#6436]
### Description

I cannot copy a file from Anydesk to a specific folder. Nevertheless, I can do the same operation when using Windows explorer.

### Steps To Reproduce

1. Open an Anydesk session
2. Select a file and Copy (Ctrl+C)
3. Move to a folder (in Files) and paste (Ctrl+V) → Nothing occurs

### Expected behavior

1. Open an Anydesk session
2. Select a file and Copy (Ctrl+C)
3. Move to a folder (in Windows explorer)  and paste (Ctrl+V) → The file is copied into that location

### Files Version

2.0.13.0

### Windows Version

10.0.19042.1237 (20H2)

**Comment by gave92** [comment]
Possibly resolved on main together with #4312

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?

**Comment by JasonTan94** [comment]
Still having this problem in v2.5.21.0
