### ISSUE TITLE
When press any letter on keyboard doesnt go to file which start with that letter

### ISSUE THREAD

**Issue by joseehilton147** [files-community/Files#6437]
### Description

On default explorer when I press key P for example it's go-to first file which starts with P, on files this doenst occur.

### Steps To Reproduce

1. press any letter on a large folder who has a lot of files
2. Files stay on the top of folder, doenst go to file with that letter

### Expected behavior

When any key pressed, go to first file with that letter

### Files Version

Versão: 2.0.13.0 OS Version: 10.0.22471.1000

### Windows Version

Windows 11 Pro Insider Preview 22471.1000

**Comment by gave92** [comment]
Merging with #6322
