### ISSUE TITLE
List view for folders

### ISSUE THREAD

**Issue by nachazo** [files-community/Files#6438]
### What's the Problem?

In the "Design" button for folders, there are "Details", "Icons", "Small icons"... but no the (very useful) "List" view that Windows explorer bundles many years ago. Very useful for folders with many files inside.

### Solution/Idea

Implement the "List" view, like Windows explorer: https://i.imgur.com/AbNRBKa.png

### Alternatives

Idk!

### Files Version

Versión: 2.0.13.0

### Windows Version

Windows 10 20H2

**Comment by yaira2** [comment]
@nachazo thank you for your patience, I'm excited to share that a List View layout will be included in the next release.
