### ISSUE TITLE
Doenst remove label when eject device

### ISSUE THREAD

**Issue by joseehilton147** [files-community/Files#6439]
### Description

![image](https://user-images.githubusercontent.com/53986027/136794334-5b3a0511-4bbc-4513-a264-b693bb10aa0f.png)

This device (pen drive) was removed like 20 minutes ago, but the label stay on files, on normal explorer doenst show.

Edit: I need to physically remove the device to stop showing on files, when I click on eject option on device i receive a alert It's safe to remove but still show there.

### Steps To Reproduce

1. Eject a device
2. Open files.

### Expected behavior

remove the device from files

### Files Version

Versão: 2.0.13.0 OS Version: 10.0.22471.1000

### Windows Version

Windows 11 Pro Insider Preview 22471.1000

**Comment by yaira2** [comment]
Is this still an issue in v2.4?
