### ISSUE TITLE
Mouse scroll crashes in column view

### ISSUE THREAD

**Issue by guilhermepsnt** [files-community/Files#6442]
### Description

When we try to scroll any direction on files with the columns layout the app closes and it notifies with a pop up error message.

### Steps To Reproduce

1. Change to Columns Layout
2. Open some folders
3. Try to scroll  to any side

https://user-images.githubusercontent.com/76705726/136816593-4b3dc424-46df-4a1a-997e-6a1019565a4d.mp4

### Expected behavior

Scroll to sides

### Files Version

Version: 2.0.13.0 OS Version: 10.0.22000.194

### Windows Version

Windows 11 21H2 22000.194

**Comment by gave92** [comment]
Could you post the app's log files?

**Comment by gave92** [comment]
Do you have "open files with a single click option enabled"? Does it crash if you turn it off?

**Comment by kwevin** [comment]
I do have "open files with a single click option enabled" and no it doesnt crash if I turn it off

**Comment by gave92** [comment]
Thanks for confirming, this issue is resolved in latest code. @guilhermepsnt feel free to comment if turning off the option mentioned above does not fix the issue.
