### ISSUE TITLE
Admin prompt doesn't show when copying folder into an admin required folder

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#6445]
### Description

My particular use case was installing an OBS plug where I have to copy tow folder into the programs directory. When I copied it the conflicts dialog came up like it should. The status center say it was completed successfully but the files weren't copied in.

### Expected behavior

The admin prompt should come up after the conflict dialog and then copied the files in.

### Files Version

2.0.17.0

### Windows Version

10.0.19043.1237

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7324108/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7324109/debug_fulltrust.log)

**Comment by gave92** [comment]
What do you choose in the conflict dialog? Replace?

**Comment by Josh-65** [comment]
Fixed in 2.1.4.0
