### ISSUE TITLE
Custom column width in DetailsView is lost on restart or window resize

### ISSUE THREAD

**Issue by pbajorek** [files-community/Files#6448]
### Description

When I start Files, and then adjust column widths (ie Name), then close the app and restart, the column widths are back at defaults - not what I had just changed them to be. Am I doing something wrong?
Thanks.

### Steps To Reproduce

see description

### Expected behavior

see description

### Files Version

v2.0.13.0

### Windows Version

w10 home 21H1 build 19043.1237

**Comment by Twentydragon** [comment]
From the issue I filed, this also occurs when changing directories.

**Comment by DejayRezme** [comment]
I also think it's important you can both customize individual folders but also set a new default for all others. Like a few folders I want sorted by date modified, but all others should just be details with longer filenames showing.

**Comment by yaichenbaum** [comment]
@gave92 can you check if this is still an issue in `main`? I think it's been resolved in one of my recent pull requests.

**Comment by pbajorek** [comment]
Yes, this was fixed a while back. Thanks for following up.

Paul
