### ISSUE TITLE
The app closes randomly.

### ISSUE THREAD

**Issue by SadraqueSP** [files-community/Files#6449]
### Description

Even when I'm doing nothing, the app closes with no apparent reason.

Windows event viewer:

Faulting application name: files.exe, version: 0.0.0.0, time stamp: 0x6147ad85
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.22000.132, time stamp: 0xdab57acf
Exception code: 0xc000027b
Fault offset: 0x0000000000834110
Faulting process id: 0x34e4
Faulting application start time: 0x01d7bec3bb67f691
Faulting application path: C:\Program Files\WindowsApps\49306atecsolution.FilesUWP_2.0.13.0_x64__et10x9a9vyk8t\files.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: 96111dde-74c4-4234-a4f3-5b378db881e9
Faulting package full name: 49306atecsolution.FilesUWP_2.0.13.0_x64__et10x9a9vyk8t
Faulting package-relative application ID: App

### Expected behavior

No random crashes.

### Files Version

V2

### Windows Version

Windows 11 (22000.194)

**Comment by gave92** [comment]
`System.Exception: Unspecified error` very clear log xD
Do you have some steps to reproduce this?
Does it close after being minimized for a while? Or also while being open but not interacted with? Or while you're using it?
