### ISSUE TITLE
Can't drag folders to another folder

### ISSUE THREAD

**Issue by NicoDominique** [files-community/Files#6451]
### Description

Just today I found a bug which doesn't allow me to drag folders into another folder. Usually it seems to be related to black tile folder bug mentioned before, but occasionally it happens also to the "normal" folders.

![folders](https://user-images.githubusercontent.com/92336066/136849864-1a55d32e-1a75-4c40-a590-69fdb2673f76.jpg)

![hue](https://user-images.githubusercontent.com/92336066/136849558-a3037ede-6c6f-4551-b0cc-e6d16c900233.jpg)

### Steps To Reproduce

Seems to appearing randomly from time to time, no specific steps are required.

### Expected behavior

Fixing this would be nice.

### Files Version

2.0.13.0

### Windows Version

Windows 11 21H2 22000.194

**Comment by yaichenbaum** [comment]
This issue should be resolved in the preview version https://files.community/download/preview.
