### ISSUE TITLE
Github release version and file version mismatch

### ISSUE THREAD

**Issue by mark05e** [files-community/Files#6453]
### Description

The version of the release set on github and the version of the application filename have a mismatch. This makes it slightly hard to build automated updates for package managers. 

I am trying to build a entry for the [scoop package manager](https://github.com/lukesampson/scoop) (similar to chocolatey, winget) and it has [a feature which automatically gets the latest version from github](https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate#special-cases) and tries to generate a download url based on the version number it finds from github releases. The difference in the github version tag and the filename version text makes it harder for automation. 😄

### Steps To Reproduce

1. Open current release page - https://github.com/files-community/Files/releases/tag/v2.0.1
2. Observe the release tag and the package filename version number (2.0.1 vs 2.0.13.0)

### Expected behavior

The github release tag to match the version number on the package. In this example github tag=`v2.0.13.0` and release package filename=`Files.Package_2.0.13.0_x86_x64.msixbundle` -- for current and future releases.

### Files Version

v2.0.13.0

### Windows Version

Windows 10 Pro

### Relevant Assets

![image](https://user-images.githubusercontent.com/1783193/136866824-b076a1de-f383-4bd0-8696-e76d9fb7a81a.png)

**Comment by mark05e** [comment]
@yair100 Thank you. Will you be using the last segment on the version number or would that be static?

![image](https://user-images.githubusercontent.com/1783193/136957074-4288a364-cead-4a78-8ca3-0c2dd3d4639a.png)

**Comment by yair100** [comment]
> @yair100 Thank you. Will you be using the last segment on the version number or would that be static?
> 
> ![image](https://user-images.githubusercontent.com/1783193/136957074-4288a364-cead-4a78-8ca3-0c2dd3d4639a.png)

The last number is static.
