### ISSUE TITLE
Open .iso files in Files

### ISSUE THREAD

**Issue by paqgamer** [files-community/Files#6455]
### Description

When trying to open .iso files, a windows explorer windows comes. It happens regardless Files is default explorer or not. But it should open in Files.

### Steps To Reproduce

In Files, double click a .iso file

### Expected behavior

A windows explorer windows should popup with the .iso file open.

### Files Version

Versão: 2.0.13.0 OS Version: 10.0.22000.194

### Windows Version

windows 11 (x64)

**Comment by josh-65** [comment]
files currently only supports opening .zip archives.

**Comment by yaichenbaum** [comment]
Any contribution would be welcome 🙂

**Comment by yaichenbaum** [comment]
Merging with #45
