### ISSUE TITLE
Can it replace default file exproler like other apps?

### ISSUE THREAD

**Issue by jiang-yuan** [files-community/Files#6459]
For example, in some other apps, when I press "Win + E", the new file window will open inside these apps instead of a default file exproler window. Can it be implemented?

**Comment by gave92** [comment]
Yes! See here -> https://files.community/docs/configuring/replace-file-explorer

**Comment by gave92** [comment]
Possible, some programs open explorer.exe directly instead of reading the registry preference. Sadly not much we can do.

**Comment by gave92** [comment]
Could you post a screenshot showing this? Also, could you give some examples of apps that do this? Thanks!
