### ISSUE TITLE
Date format not following system when set to do so

### ISSUE THREAD

**Issue by ezxpro** [files-community/Files#6460]
### Description

Although my PC has English as its display language, Regional format and region are set elsewhere.

The system date is thus in the format dd/MM/YYYY. In Files, I select the date format to system, but it shows the date the on files, for example, just as if it's set to Application (MM/dd/YYYY)

### Steps To Reproduce

1. Set regional format (especially date) to one different than File's
2. Open files > preferences > Date Format > set it to "System"
3. Check file dates within files, it will show in a format different than that of the system

### Expected behavior

It should show date just as it shows up in my clock, on the notification area

### Files Version

Version: 2.0.13.0 OS Version: 10.0.22000.194

### Windows Version

Windows 11 21H2 22000.194

### Relevant Assets

[debug_fulltrust.log](https://github.com/files-community/Files/files/7330182/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7330183/debug.log)

![image](https://user-images.githubusercontent.com/15344931/136962299-65186ae8-5018-442e-bf85-002c66f76d59.png)
![image](https://user-images.githubusercontent.com/15344931/136962407-aafdde0e-147c-452d-ad39-31a045a9a04d.png)

**Comment by Brain-Gamer** [comment]
I was about to report the same issue but then checked the [corresponding wiki page](https://files.community/docs/configuring/date-formats).
Turns out "System" is just hard coded to MM/DD/YYYY and not what your regional system setting provides.

This could be fixed manually once #2207 is implemented.

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
I'm not sure why it's called system (should probably be renamed) but like @fgardt pointed out, this is the expected behavior.
