### ISSUE TITLE
sidebar: files/folders dragged to sidebar buttons are moved to trash when they don't come from Files

### ISSUE THREAD

**Issue by djebzer** [files-community/Files#6461]
### Description

When dragging files or folders from outside Files to any of the buttons inside the sidebar (`Downloads`, `Documents`..), the files are moved to the trash bin. (sometimes you're prompted to confirm by your admin rights but even if you press `No`, it will still move the stuff to the trash) (I tried reinstalling/repairing the app but still)

### Steps To Reproduce

1. Drag a file/folder. (from anywhere outside Files)
2. Aim it at the `Downloads`, `Documents`, `C: Disk` or any button in the sidebar section.
3. You might be prompted to confirm with admin rights. (sometimes)
4. Then the file/folder will be moved to the trash bin. (even if you pressed no)

### Expected behavior

It is definitely not valid, and is kinda critical because I lost many folders without even noticing them being moved to the trash bin. Apparently it happens when the file/folder comes from outside Files.

### Files Version

Version : 2.0.13.0 OS Version: 10.0.22000.194

### Windows Version

Windows 11 21H2 22000.194

### Relevant Assets

https://user-images.githubusercontent.com/35749378/136965625-7a1cad1c-fd2b-4b52-ac11-99879ce10f33.mp4

**Comment by gave92** [comment]
This issue appears to be fixed as of Files v2.1.15
