### ISSUE TITLE
This PC and Recycle Bin open in File Explorer when Files is set as default file manager

### ISSUE THREAD

**Issue by SOI7** [files-community/Files#6462]
### Description

If you turn on the "Use Files as default file manager" toggle in Experimental settings, This Pc and Recycle Bin still open in File Explorer. Any other folder opens in Files as it should be

### Steps To Reproduce

1. Enable "Use Files as default file manager" in Experimental settings
2. Open This Pc or Recycle Bin from your desktop
3. (optional) Open any other folder to compare

### Expected behavior

This Pc and Recycle Bin should open in Files

### Files Version

2.0.18.0

### Windows Version

Windows 10 21H1

**Comment by MohammadMD1383** [comment]
> "Use Files as default file manager" in Experimental settings

I can't find that.
Version: 2.0.13.0
OS Version: 10.0.19043.1266

**Comment by gave92** [comment]
Given that the issue preventing the control panel to work is fixed we can perhaps integrate the following in the app.

To open recycle bin & my PC:
1. Extract the two files from this archive [SetUnsetFilesAsDefault_Bad.zip](https://github.com/files-community/Files/files/5825020/SetUnsetFilesAsDefault_Bad.zip) and place them *on the desktop*
2. Run `SetFilesAsDefault_Bad.reg`

**Comment by yaichenbaum** [comment]
@gave92 should this be integrated into the app and the documentation?

**Comment by gave92** [comment]
@yair100 I think so, it has no known issues anymore.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7408
