### ISSUE TITLE
When trying to extract an invalid non-zero .zip file, Files crashes

### ISSUE THREAD

**Issue by Tudi20** [files-community/Files#6464]
### Description

When trying to extract an invalid non-zero `.zip` file, Files crashes

### Steps To Reproduce

1. Open up notepad, write some junk in it then save it as `invalid.zip`
2. Open up Files, and navigate to where you saved the zip file
3. Right Click -> Extract Here
4. Wait for Files to crash silently

### Expected behavior

An error message saying that the file you tried to extract was invalid or corrupted.

### Files Version

2.0.13.0

### Windows Version

10.0.19043.1237

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7330583/debug.log)

**Comment by gave92** [comment]
Fixed on main.
