### ISSUE TITLE
In a files properties, under the details tab, the information is center ruled, may look better left ruled.

### ISSUE THREAD

**Issue by sultanmckings** [files-community/Files#6470]
### What's the Problem?

When I observer a files details, the text for the information (item Name, Item Path, etc.) scales the the center of the screen, making open up the properties page quite large to view all the information.  

### Solution/Idea

If the text was left ruled with enough space at its slimmest to be distinguishable from the information description, it would improve the readability of the details. 
 
![issue_leftrule_fix](https://user-images.githubusercontent.com/92404050/137035976-2c3d385e-d78c-4843-92ed-16070a603126.png)
  

### Alternatives

You could also start the properties page by default to a larger window. 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Moving the details text to be left ruled | Should |
| Starting the properties window larger by default | Could |

### Files Version

v1.5

### Windows Version

Windows 10 20H2 19042.1237

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
