### ISSUE TITLE
Adding "size on disk" information to file details in properties. 

### ISSUE THREAD

**Issue by sultanmckings** [files-community/Files#6471]
### What's the Problem?

When you view the details tab of a file, it only gives you the size of the file in the General tab. It would be beneficial to add the "Size on disk" attribute like it is in the Windows file explorer. 

### Solution/Idea

add sections in the details of a file for "size" and "size on disk" above the "Date Created" and "Date Modified" attributes.
![Issue_size_sizeondisk_fix](https://user-images.githubusercontent.com/92404050/137037650-72622e4e-b93e-4617-ab3c-b27aa58d515e.png)

### Alternatives

It is not essential to add the "size" in the details section because it is already in the general tab, but because the "created" and "modified" attributes are in both the General and Details tab it would look better for consistency. 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Adding the attribute "size on disk" to the details tab for files | Should |
| Adding the attribute "size" to the details tab for files  | Could |

### Files Version

v1.5

### Windows Version

Windows 10 20H2 19042.1237

**Comment by Korkman** [comment]
+1 for this feature. I frequently need to see the true size of my VM disk images, and having it right with the apparent size on the details page would be best.

**Comment by LosOmatic** [comment]
+1 for adding Size on Disk in items properties panel

**Comment by Josh-65** [comment]
Merging with #3930
