### ISSUE TITLE
File Rename - Keyboard shortcut Ctrl-Shift moving focus out

### ISSUE THREAD

**Issue by venkatarangan** [files-community/Files#6481]
### Description

In a file or folder, after entering rename mode (through F2 or Right-Click Rename), when we press Ctrl-Shift with Arrow keys (Left or Right) to select a word in the filename, the focus shifts out of the current file. It has to remain in the same mode for easy editing of the filenames.

### Steps To Reproduce

1. Go to any folder with a few files.
2. Click on a file, then press F2 to edit a filename say "Welcome to a new world"
3. Move the mouse to say end of the word 'to', now press Ctrl-Shift-Right Arrow (>) twice, to select the next two words.
4. You will see the focus shifting out of the edit more and out of the current file context.

### Expected behavior

Pressing Ctrl-Shift-Arrows twice should've selected the words " a new "

### Files Version

Version: 2.0.13.0 OS Version: 10.0.22000.194

### Windows Version

Windows 11 Version 21H2 (OS Build 22000.194)

### Relevant Assets

![image](https://user-images.githubusercontent.com/4814266/137075033-11031d80-a415-4da3-ab84-66b61f30e833.png)

**Comment by mgranado** [comment]
I just wrote the same issue, i'm glad I didn't send it.

**Comment by venkatarangan** [comment]
Glad it is fixed in 2.0.16.0. Have the binaries for this version been released? the latest I  could get from the Microsoft Store is 2.0.13.0 only.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7390
