### ISSUE TITLE
Make the "Preferences" window movable

### ISSUE THREAD

**Issue by ezxpro** [files-community/Files#6486]
### What's the Problem?

When changing settings under the "preferences" window, I can't see what's behind. For example, yesterday I was going to report a possible bug, and I wanted to show a  configuration under settings AND the files opened in a folder in a screenshot, but that's not posible because the preference window's position is fixed.

### Solution/Idea

One should be able to move this window.

### Alternatives

Maybe preferences could be opened in another tab, but I think that's throwing the baby out with the bathtub, as it wouldn't really solve the problem I mentioned earlier.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow users to move the settings Window | Must |

### Files Version

Version: 2.0.13.0

### Windows Version

Windows 11 21H2 22000.258

**Comment by yaichenbaum** [comment]
The settings dialog is a modal and is not movable by design. For this purpose, we recommend uploading two separate screenshots to GitHub.
