### ISSUE TITLE
File search does not return any result

### ISSUE THREAD

**Issue by Gor80hd** [files-community/Files#6487]
### Description

When searching for a file, it does not return any results. Not with the full name, not when entering part of the file name. Doesn't search even when clicking on the "Search for non-indexed items" button
![image](https://user-images.githubusercontent.com/92448318/137146770-8588dda4-76ef-490e-80f0-953a2406aa67.png)

### Steps To Reproduce

1. Open folder
2. Enter name in search box
3. Start search

### Expected behavior

The files should be located

### Files Version

Версия: 2.0.13.0 OS Version: 10.0.22471.1000

### Windows Version

Windows 11 Pro Insider Preview 1000.22471.1000.0

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7338701/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7338702/debug_fulltrust.log)

**Comment by Gor80hd** [comment]
> Does it work if you add an asterisk "*" at the end of the file name?

In the case when the search is in the "Downloads" folder, then yes it works. If I am looking for something on the C drive, for example "Programs Files" or looking for some folder inside "Programs Files", it does not work

**Comment by yaichenbaum** [comment]
This issue should be resolved with #6671.
