### ISSUE TITLE
Crashing when entering (sometimes) my Images folder

### ISSUE THREAD

**Issue by BanCrash** [files-community/Files#6491]
### Description

Sometimes if I enter my Images folder it will crash with the "something went wrong" notification and this on the debug.log:

> 2021-10-13 21:09:01.8454|ERROR|AppUnhandledException|Object reference not set to an instance of an object.
> 	System.NullReferenceException: Object reference not set to an instance of an object.
>    at Files.Views.LayoutModes.GridViewBrowser.GridViewBrowser_obj27_Bindings.Update_LoadFileIcon(Boolean, Int32) + 0x43
>    at Files.Views.LayoutModes.GridViewBrowser.GridViewBrowser_obj27_Bindings.GridViewBrowser_obj27_BindingsTracking.PropertyChanged_(Object, PropertyChangedEventArgs) + 0x469
>    at System.Action`2.InvokeMulticastThunk(T1, T2) + 0x4e
>    at System.EventHandler`1.Invoke(Object, TEventArgs) + 0x2e
>    at Microsoft.Toolkit.Mvvm.ComponentModel.ObservableObject.SetProperty[T](T&, T, String) + 0x9c
>    at Files.Filesystem.ListedItem.Img_ImageOpened(Object, RoutedEventArgs) + 0x55
>    at Microsoft.Toolkit.Uwp.UI.Controls.InAppNotificationOpeningEventHandler.Invoke(Object, InAppNotificationOpeningEventArgs) + 0x2e
>    at __Interop.Intrinsics.HasThisCall__23[TArg0](Object, IntPtr, Object, TArg0) + 0x36
>    at Files!<BaseAddress>+0x12b1f30

debug_fulltrust.log:

> 2021-10-13 21:10:14.4828|WARN|ParseFileOperationAsync|Devuelto error HRESULT E_FAIL de una llamada a un componente COM.
> 	System.Runtime.InteropServices.COMException (0x80004005): Devuelto error HRESULT E_FAIL de una llamada a un componente COM.
>    en Vanara.PInvoke.Shell32.IShellLinkW.Resolve(HWND hwnd, SLR_FLAGS fFlags)
>    en Vanara.Windows.Shell.ShellLink.LoadAndResolve(String linkFile, SLR_FLAGS resolveFlags, HWND hWin, UInt16 timeOut)
>    en FilesFullTrust.MessageHandlers.FileOperationsHandler.<ParseFileOperationAsync>d__4.MoveNext()
> 2021-10-13 21:10:14.5378|INFO|Connection_RequestReceived|Argument: FileOperation
> 2021-10-13 21:10:14.5488|WARN|ParseFileOperationAsync|El sistema no puede encontrar el archivo especificado. (Excepción de HRESULT: 0x80070002)
> 	System.IO.FileNotFoundException: El sistema no puede encontrar el archivo especificado. (Excepción de HRESULT: 0x80070002)
>    en Vanara.PInvoke.Shell32.ShellUtil.GetShellItemForPath(String path)
>    en Vanara.Windows.Shell.ShellLink.get_Target()
>    en FilesFullTrust.MessageHandlers.FileOperationsHandler.<ParseFileOperationAsync>d__4.MoveNext()

On the end of the post I will add the full logs, tough there is nothing else relevant I think.

### Steps To Reproduce

1. Go to a folder that has a lot of content (I guess... my Images folder has 3552 items)
2. If it's not crashing, open a new tab and try again.

It's not crashing all the times, but eventually it will crash (more or less at the third time, but I got this on the first time I opened Images folder after installing last version), at least in my testings.

### Expected behavior

Should not crash

### Files Version

V2.0.19.0

### Windows Version

Windows 10 21H1 10.0.19043.1288

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7340743/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7340744/debug_fulltrust.log)

In my testings:
![image](https://user-images.githubusercontent.com/11770760/137198681-db450c0d-809d-40f7-ab93-ac8883e98f6f.png)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #6674.
