### ISSUE TITLE
Lots of flash drives!

### ISSUE THREAD

**Issue by AleMello** [files-community/Files#6493]
### Description

I'm creating a windows setup drive, and when I pluged it to my computer I noticed I have more drives than I suppose... :-)

![image](https://user-images.githubusercontent.com/4070249/137207710-f20d0164-5158-43c8-b764-aafdf095806e.png)

### Expected behavior

I woukld expect that only one H: drive appear.

### Files Version

v2.0.13.0

### Windows Version

windows 10 21H1

**Comment by d2dyno1** [comment]
Drives on sidebar are duplicated too

**Comment by AndrewLaganaro** [comment]
Happened right now when connecting a regular flash drive with only one partition (FAT32, regular for flash drives)

It showed up two identical flash drives at first, then the second disappeared when I've updated the program. Don't know why.

Files version: 2.0.3.4

Windows OS: 10, Version: 10.0.19043.1348

**Comment by d2dyno1** [comment]
Resolved with #8325
