### ISSUE TITLE
File operation (copy/move/delete) progress not showed in all Files window

### ISSUE THREAD

**Issue by errypuu** [files-community/Files#6494]
### Description

When copying or moving a file (doing file operations), a progress circle is only showing on one window that initiating the file operation. It is not showing on all other Files window
![image](https://user-images.githubusercontent.com/2776081/137220839-5f7f3bbd-eb4f-4e38-bf13-ab1167be9efa.png)

Even though the file operation is running in background; I believe it should be shown across all windows.
Since if the initiating window is crash, we can open a new window and still know the progress of the file operation

### Steps To Reproduce

1. Open one Files window
2. Initiate file operation (copy/move/delete)
3. Open another Files window
4. Check on the Progress circle icon

### Expected behavior

File operation progress circle is shown across all Files windows

### Files Version

2.0.19.0

### Windows Version

Windows 11 21H2 10.0.22000.258

**Comment by raul8505** [comment]
Me gustaría que se pudiera utilizar el copiador de su gusto tengo supercopier y cuando copio tiene que ser con su copiador ni siquiera con el Windows por defecto

**Comment by Jay-o-Way** [comment]
Is this still an issue with the latest version?

**Comment by Josh65-2201** [comment]
Yes

**Comment by hez2010** [comment]
Merging with #13632.
