### ISSUE TITLE
Invocation of any zip file whose extension is capitalised is not operational.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [files-community/Files#6495]
### Description

![image](https://user-images.githubusercontent.com/42837531/136880563-aa806584-c8a2-401e-b9ce-4f78da1f4bd3.png)

### Steps To Reproduce

Invoke any zip file whose extension is capitalised.

### Expected behavior

This software should either support management (observation and decompression) of capitalised ZIP files.

### Files Version

v2.0.13.0

### Windows Version

Windows 11 22471.1000

### Relevant Assets

[debug_fulltrust.log](http://github.com/files-community/Files/files/7341842/debug_fulltrust.log)
[debug.log](http://github.com/files-community/Files/files/7341843/debug.log)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #6674.
