### ISSUE TITLE
Not possible to drag and drop files from Files to Windows Media Player playlist window

### ISSUE THREAD

**Issue by miwojc** [files-community/Files#6498]
### Description

It's not possible to drag and drop files from Files to Windows Media Player into playlist window. Drag and drop works with File Explorer.

### Steps To Reproduce

Open Files
Open Windows Media Player and go to playlist window
Drag files from Files and drop inside playlist window in Windows Media Player

### Expected behavior

It should be possible to drag and drop files from Files to Windows Media Player playlist as this works with File Explorer.

### Files Version

Version: 2.0.13.0

### Windows Version

Edition: Windows 10 Home, Version: 21H1, OS build: 19043.1237

### Relevant Assets

![wmp](https://user-images.githubusercontent.com/32404415/137253997-97f9845c-ef4f-49ac-8b2c-70fe3555d09a.gif)
![files](https://user-images.githubusercontent.com/32404415/137254429-9a524753-7ee9-4a09-82f4-daba69b37f98.gif)

**Comment by yaichenbaum** [comment]
Merging with #6941
