### ISSUE TITLE
App not refreshing after creating a new file

### ISSUE THREAD

**Issue by Mahdihp** [files-community/Files#6499]
### Description

add new file excel not refresh list view.

### Expected behavior

Refresh List Add new File And Folder

### Files Version

2.0.13

### Windows Version

Windows 10 Enterprise 20H2

**Comment by gave92** [comment]
Does this happen in a network folder or local folder?

**Comment by hermannx5** [comment]
I also have this issue. For me it seems to happen only/mostly with network drives.

**Comment by yaichenbaum** [comment]
@Mahdihp is this still an issue in v2.0.34?
