### ISSUE TITLE
FilesFullTrust.exe doesn't start with Files on Windows 10

### ISSUE THREAD

**Issue by VPraharsha03** [files-community/Files#6501]
### Description

I've installed Files from the DevOps zip shared by running the install.ps1, installation completed without any errors but the FilesFullTrust.exe isn't launching along with Files app. I've done a re-install but still the issue persists. This isn't letting the recording of logs & log file remains blank. Another user too has the same issue. The dependent issue is open [here](https://github.com/files-community/Files/issues/6327) 

### Steps To Reproduce

Launch Files

### Expected behavior

FilesFullTrust.exe should be running

### Files Version

2.0.16.0

### Windows Version

Windows 10 19H1 10.0.18362.1049

### Relevant Assets

Here's a video showing the FullTrust starting and terminating as soon as it starts 

https://user-images.githubusercontent.com/56556436/137343831-d41b78ee-b086-4d10-b5f4-79c20d30653a.mp4

**Comment by d2dyno1** [comment]
Can you add debug logs?

**Comment by VPraharsha03** [comment]
> Have you tried down loading from the Microsoft store or using the .msixbundels on GitHub releases.

@josh-65 yes at first i installed from the msixbundles but the same issue existed(i'd to enable Windows updates for some of the dependencies to download and install but they weren't done properly so installed them manually from devops zip)

Never installed from store as i never signed up for the insider program

**Comment by VPraharsha03** [comment]
> Can you add debug logs?

@d2dyno1 Hmm this time "debug_fulltrust.log" has something in it, earlier it was empty
[debug_fulltrust.log](https://github.com/files-community/Files/files/7351223/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7351224/debug.log)
