### ISSUE TITLE
File space

### ISSUE THREAD

**Issue by lpesar** [files-community/Files#6509]
### What's the Problem?

in the right panel, the list of files have too many space between files

### Solution/Idea

maybe, have a options for choose space between files 

### Alternatives

mmmm  jus use other program, sorry

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Versión: 2.0.13.0 OS Version: 10.0.19043.1288

### Windows Version

Windows 10 Pro Version	21H1 Installed on	‎6/‎11/‎2020 OS build	19043.1288 Experience	Windows Feature Experience Pack 120.2212.3920.0

**Comment by yaichenbaum** [comment]
Merging with #1940.
