### ISSUE TITLE
Support for SageThumbs is broken

### ISSUE THREAD

**Issue by laurorual** [files-community/Files#6512]
### Description

I use the app SageThumbs for showing thumbnails of PSD files in explorer and it kind of works with Files, but only with a few files. Some files do show the thumbnail as expected, some files doesn't show the thumbnail at the grid of files but do show the thumbnail in the "delete window" (see screenshot below), some other files doesn't show the thumbnail at all.
Using Microsoft Explorer works fine.

![Captura de tela 2021-10-15 014157](https://user-images.githubusercontent.com/755915/137433345-6f7cc38a-853f-4b26-a78b-cbb1df51bde8.png)

### Steps To Reproduce

1. Install SageThumbs
2. Open a folder with PSD files inside

### Expected behavior

The thumbnails of PSD files are supposed to show, not an icon of a blank file.

### Files Version

2.0.13.0

### Windows Version

Windows 11 21H2 22000.194

**Comment by d2dyno1** [comment]
This issue should be resolved with #7881 @laurorual
