### ISSUE TITLE
Add temporary shelf (clipboard) for placing files and folders in with support for bulk actions

### ISSUE THREAD

**Issue by neoOpus** [files-community/Files#6514]
### What's the Problem?

It is hard to organize folders and files for example in cluttered Download folder into sub-folders and maybe later add some features and rules to make this even better like auto-renaming files/folders etc... anything that can help the organization will make this a true Modern Explorer alternative... this must be different from library and Quick Access

### Solution/Idea

I suggest to add this feature, a floating or side drag-n-drop area where you can drop a folder so it stay temporarily on a thumb list so it is possible to organize files and folders, when files or folders are dragged over them they show a scrolling sub-folder list and some other icons to decide quickly what to action we want to do... (move/copy/replace/over-write) so it become easier to manage versions of softwares... I can give more suggestions about how this should work 

### Alternatives

(Move-to/Copy-to) and I tried also finding a freeware that can help with this, and I tried several other file-managers but most of them are made for Windows 95 era... something that has a better UI/UX with better thought features is a must

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.0.13.0

### Windows Version

10.0.22000.194

**Comment by Alaknar** [comment]
> something like this, probably?

Is this Files or some other application? I can't find this feature in 2.0.13 anywhere (but might be blind).

**Comment by R3voA3** [comment]
Very nice feature indeed.

**Comment by hiranmayd** [comment]
> > something like this, probably?
> 
> Is this Files or some other application? I can't find this feature in 2.0.13 anywhere (but might be blind).

quote

**Comment by neoOpus** [comment]
> something like this, probably?
> 
> ![Figma_lIkhrcYRId](https://user-images.githubusercontent.com/60701764/137583494-1e30d297-5672-46da-a961-c1dcd8f5eaca.png)
> 
> ![Figma_c3yY1kiHrP](https://user-images.githubusercontent.com/60701764/137583497-98a65b6c-8928-43b2-a3ad-982ca0c628eb.png)
> 
> : ))
> 
> ps. the blur behind the flyout is just so that the flyout is highlighted.

Absolutely, this is exactly what I am talking about!

**Comment by hiranmayd** [comment]
@yair100

**Comment by yaichenbaum** [comment]
@neoOpus do you see this as temp folder with the original files removed, or do you see this as a temporary clipboard?

**Comment by neoOpus** [comment]
>

**Comment by neoOpus** [comment]
> @neoOpus do you see this as temp folder with the original files removed, or do you see this as a temporary clipboard?

I see it as a sort of structured temporary clipboard where paths can be added/removed as favorites on the fly… Something similar to what FileMenuTools move-to feature offers but a bit easier to manage and work with… but I don’t have a clear idea how it should be implanted better, still I know this can increase productivity a lot as it can be a suitable alternative to multiple window / tabs or side by side file mangers…

**Comment by Alaknar** [comment]
Just FYI - until this feature is implemented, you can use [Shelfit](https://apps.microsoft.com/store/detail/shelfit/9NPZ3RHK24WD?hl=pl-pl&gl=PL) (paid, but with a trial period).

**Comment by neoOpus** [comment]
> Just FYI - until this feature is implemented, you can use [Shelfit](https://apps.microsoft.com/store/detail/shelfit/9NPZ3RHK24WD?hl=pl-pl&gl=PL) (paid, but with a trial period).

There is a free alternative called [DropPoint](https://github.com/GameGodS3/Droppoint) but it is not a robust solution still it has most of the required features but I guess Files Devs can come up with better and more modular solution (with several buckets and rules/actions etc)

**Comment by yaira2** [comment]
Thank you for all the feedback, we're going to continue tracking this feature request in #12490.
