### ISSUE TITLE
Drivers do not appear in side Bar

### ISSUE THREAD

**Issue by marcdfranc** [files-community/Files#6515]
### Description

The drivers have desapeared with the new atualization.

![image](https://user-images.githubusercontent.com/24740206/137472235-dd74bfdf-68db-4d39-acd0-22b5b53348f9.png)

### Expected behavior

make the drivers and folders available at the side bar.

### Files Version

Version: 2.0.13.0

### Windows Version

OS Version: 10.0.19043.1263

**Comment by Bornze** [comment]
me too facing same issue, also unable to open downloads folder or any folder under C drive/users.

running on windows 11 Oct 2021 build
