### ISSUE TITLE
boost app startup

### ISSUE THREAD

**Issue by MohammadMD1383** [files-community/Files#6516]
### What's the Problem?

opening the application sometimes is slow

### Solution/Idea

inspired from ms edge.
you can implement a service that initializes the resources needed by the app at system startup, so when user opens the app, it allocates only new resources and the application would be faster.

### Alternatives

Anything just as fast as native file explorer🥺

### Priorities

| Capability | Priority |
| :---------- | :------- |
| faster startup | Must |

### Files Version

2.0.13.0

### Windows Version

Windows 10 19043.1266

**Comment by yaira2** [comment]
We're excited to share that startup performance will be significantly improved in the upcoming release of version 3. You can download the preview version from our website https://files.community/download.
