### ISSUE TITLE
Pasting from MTP device doesn't work.

### ISSUE THREAD

**Issue by ezxpro** [files-community/Files#6518]
### Description

If I copy a file from an MTP device and paste it anywhere else, a 0 bytes file is created, and that's it.

### Steps To Reproduce

1. Plug an MTP device to the PC
2. Copy any file from it
3. Paste it on a local drive

### Expected behavior

It should paste the file as it would from any other disk

### Files Version

Version: 2.0.13.0

### Windows Version

Windows 11 21H2 22000.258

### Relevant Assets

![image](https://user-images.githubusercontent.com/15344931/137489956-eea237de-4f26-4dd0-b385-0c10d8628b76.png)
File I just pasted from an MTP device into my hard drive.

**Comment by pratyakshm** [comment]
It's working for me in v2.0.34.0

![image](https://user-images.githubusercontent.com/54220235/140975046-0d02deb2-9d8b-452c-943c-bfb992d6a962.png)

![image](https://user-images.githubusercontent.com/54220235/140975147-4771d909-12ae-4195-9f30-f95fff20768c.png)

**Comment by pseudoforceyt** [comment]
It happened to me when no sufficient storage space was left on my device

**Comment by Josh-65** [comment]
Merging with #9003
