### ISSUE TITLE
Encrypt and Compress Options

### ISSUE THREAD

**Issue by MrAwesomeGuy27** [files-community/Files#6519]
### Solution/Idea

Basically, in Window's built-in File Explorer, if you go to the properties of a file/folder, you can go to general and under file attributes, there's an advanced button. If you press that advanced button, there will be a pop-up giving you some more options, including the options to encrypt and/or compress the file/folder. When I checked the Files app, I couldn't find it. So, if you could add the option to encrypt and/or compress a file/folder, it would be nice.

### Alternatives

Instead of making a separate advanced button, you could just add 2 more checkboxes for encrypt and compress.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This feature must have at least the encrypt and compress options. | Must |
| This feature should have the advanced button to open up the encrypt and compress options. | Should |

### Files Version

2.0.13.0

### Windows Version

10.0.22000.258

**Comment by yaira2** [comment]
This was recently implemented and will be included in the next update.
