### ISSUE TITLE
Download folder bcomes DOWNLO~1 and cannot auto focus/jump to the downloaded file

### ISSUE THREAD

**Issue by curtis18** [files-community/Files#6523]
### Description

Thanks for creating Files. It is a great app and more comprehensive comparing to other explorer plugins.

It is found that "Download" folder bcomes "DOWNLO~1" and cannot auto focus/jump to the downloaded file when Files is set as a default explorer and is opened via browsers (tested on Firefox / Chrome). Please help and thanks.

![image](https://user-images.githubusercontent.com/6743839/137566146-4b30d539-aec7-4cc8-859e-0ccc77a040bb.png)

![image](https://user-images.githubusercontent.com/6743839/137565880-22c4f843-0fdb-4b4b-adca-5659ef949970.png)

### Expected behavior

Jumping to the downloaded file and showing C:\Users\ (username) \Downloads instead of C:\Users\ (username) \DOWNLO~1

### Files Version

2.0.13

### Windows Version

Windows 10

**Comment by gave92** [comment]
The short path issue has been resolved in latest code. For not focusing folder, merging with #6382.
