### ISSUE TITLE
[Question] FileOperations for other UWA

### ISSUE THREAD

**Issue by jp-weber** [files-community/Files#6524]
I have a question regard to the system file access. I developing an application which generating TOTP codes for two factor authentification (https://github.com/2fast-team/2fast). The account information will be saved und read in a encrypted json file. Currently I have activate the capability 'broadFileSystemAccess' to get the system access authorization to avoid later access problems. 

'Files' relies on win32 com calls here as I have seen. For this I would like to ask which files are all needed to be used in another app and if the helper files could be packaged as nuget to simplify this for other developers.

**Comment by gave92** [comment]
Hi @jp-weber could you clarify what you'd need? If you have the `broadFileSystemAccess` you should be able to use StorageFolder/StorageFile methods on most locations bypassing the file picker.
Files uses Win32 methods from UWP to enumerate folder contents faster and including hidden files. Plus Files is a desktop bridge app that has a Win32 process running separately for handling file operations, but again for your needs you might be better off using StorageFolder+StorageFile.
