### ISSUE TITLE
Operation in progress indicator on the file

### ISSUE THREAD

**Issue by Alaknar** [files-community/Files#6526]
### What's the Problem?

Operation progress (like extraction or copying) shows in the corner under an icon, which is great. But at the same time, when extracting an archive, the folders from that archive appear immediately. At first glance it looks like the extraction was already completed.

### Solution/Idea

Would be nice to have an "operation in progress" icon showing on both the archive being extracted and the target folder. Similarly with copy/delete/move operations.

### Alternatives

Alternatively, make the progress window expand automatically when an operation starts.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Pop up window when an operation starts | Must |
| Operation in progress icons on the files/folders themselves | Should |

### Files Version

v2.0.13

### Windows Version

20h1, 19043.1288

**Comment by yaichenbaum** [comment]
Would adding this to the status column make sense or can you see that getting in the way in OneDrive?

**Comment by Alaknar** [comment]
> Would adding this to the status column make sense or can you see that getting in the way in OneDrive?

It could very well be a similar icon to what OneDrive does. Don't see them getting in the way of each other since any file operations will also trigger a synch in OneDrive.

Unless you mean, one would overwrite the other somehow? In that case, no idea.

I also just had an idea that maybe instead of a progress icon Files could gray out the file being worked on. Like Explorer when you Cut something out.

**Comment by yaichenbaum** [comment]
Merging with #5909
