### ISSUE TITLE
Feature: Add actions to auto adjust column widths in the Details View

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#6528]
### Description

CTRL+ NUM + should auto adjust details view column width, instead it increases the zoom level.

The shortcut should be identical to File Explorer.

### Steps To Reproduce

1. Go into a folder with details view
2. Press CTRL + Num +

### Expected behavior

- The width of the columns in view should auto adjust just like it does in File Explorer

### Files Version

2.0.13

### Windows Version

 OS Version: 10.0.19043.1165

**Comment by yaira2** [comment]
@R3voA3 which column size increases, all of them?
