### ISSUE TITLE
Wrong progress shown with multiple operations

### ISSUE THREAD

**Issue by Gor80hd** [files-community/Files#6529]
### Description

When copying multiple items, the progress bar jumps. And spreads across multiple processes
![image](https://user-images.githubusercontent.com/92448318/137593010-ce1eb951-73b7-486d-b681-9739488ce202.png)

### Expected behavior

The completion percentage should match its process. Should not jump from 1% to ***%

### Files Version

Версия: 2.0.13.0 OS Version: 10.0.22471.1000

### Windows Version

Windows 11 Pro Insider Preview 1000.22471.1000.0

**Comment by yaichenbaum** [comment]
@Gor80hd is this still an issue in the preview version? http://files.community/download/preview
