### ISSUE TITLE
thumbnails get refreshed every time the same folder is opened

### ISSUE THREAD

**Issue by loboly-19** [files-community/Files#6532]
### Description

files thumbnails get refreshed every time the same folder is opened even if opened and closed multiple times.

https://user-images.githubusercontent.com/33003891/137604234-a5deb2ec-2212-4947-ad79-10022e2ed0ca.mp4

### Steps To Reproduce

Switching folders or views.

### Expected behavior

thumbnails are expected to get generated first time only, not every time the folder is re-opened.

### Files Version

2.0.13.0

### Windows Version

windows 11 beta - 21H2 22000.282

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
