### ISSUE TITLE
The window navigation overlaps settings

### ISSUE THREAD

**Issue by mangoepic** [files-community/Files#6538]
### Description

![image](https://user-images.githubusercontent.com/71931749/137622274-714c7556-29e4-468f-9407-f4ba485632d0.png)

### Steps To Reproduce

Resize Files to a smaller area until you can see it happen

### Expected behavior

Keep the settings dialogue either lower or less wide so it doesn't overlap

### Files Version

Version: 2.0.13.0

### Windows Version

OS Version: 10.0.22000.194

**Comment by yaichenbaum** [comment]
Merging with #6073.
