### ISSUE TITLE
Feature: Ctrl + alt + enter to open in new window

### ISSUE THREAD

**Issue by mangoepic** [files-community/Files#6539]
### What's the Problem?

I like the multiple windows workflow to drag files from one location to another. Windows Explorer allows this by pressing ctrl+double click on anything to open the folder in a new explorer window.

### Solution/Idea

I would love to see this in files too. Additionally it might be nice if a new window opened by holding shift when pressing the "+ new tab" symbol
![image](https://user-images.githubusercontent.com/71931749/137622562-25f83fd7-1da2-46f9-845b-6cdcb3a2817a.png)

Would be even cool when holding shift when clicking "open in new tab" in the right click context menu
![image](https://user-images.githubusercontent.com/71931749/137622615-c5fd1a40-174b-4ebb-9921-bae9f8fe2f24.png)

### Alternatives

Any other shortcut

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow users to open new window instances easily | Must |
| This proposal will allow users to open a new folder in new instance by holding shift | Should |
| This proposal will allow users to open a new tab in new instance by holding shift when clicking + | Should |
| This proposal will allow users to open something in a new instance by holding shift when clicking "open in new tab" in the  right click menu | Should |

### Files Version

Version: 2.0.13.0 

### Windows Version

OS Version: 10.0.22000.194

**Comment by yaira2** [comment]
@mangoepic the next update will add support for this via the `ctrl` + `alt` + `enter` shortcut.
