### ISSUE TITLE
switch items arrow keys or mouse click  QuickLook don't change image

### ISSUE THREAD

**Issue by xBLACKICEx** [files-community/Files#6540]
### Description

switch items arrow keys or mouse click  QuickLook don't change image.

In Files each time change image(item) with arrow keys or mouse  need to press on Space key to see changes on QuickLook

## This is in system files explorer 
![quicklook with sys explorer](https://user-images.githubusercontent.com/51036094/137625793-fd05e460-f559-45bd-b93f-d23672ccad1d.gif)

### Files Version

v 2.0.13.0

### Windows Version

Windows 11 Pro Insider Preview 22478.1012

**Comment by yaichenbaum** [comment]
@xBLACKICEx this issue should be resolved with #6543.
