### ISSUE TITLE
keyboard selection on opening with mouse

### ISSUE THREAD

**Issue by mangoepic** [files-community/Files#6541]
### Description

Opening files from the taskbar selects "New tab" with keyboard selection for me

### Steps To Reproduce

Open Files

### Expected behavior

No keyboard selection initially

### Files Version

Version: 2.0.13.0 

### Windows Version

OS Version: 10.0.22000.194

### Relevant Assets

https://user-images.githubusercontent.com/71931749/137633900-4440fce9-48e4-41a7-b59f-6cb0343bcd51.mp4

[debug.log](https://github.com/files-community/Files/files/7360234/debug.log)

[debug_fulltrust.log](https://github.com/files-community/Files/files/7360235/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
@mangoepic is it possible you're pressing a key on the keyboard while the app is opening?

**Comment by tellmewhy12** [comment]
@yair100 I just opened the screen keyboard but it didn't register any presses.. disabling numpad or capslock didn't change behaviour

**Comment by tellmewhy12** [comment]
@yair100 is there anything else I can help you with here or send you?

**Comment by yair100** [comment]
> @yair100 is there anything else I can help you with here or send you?

Not really, do you want to try debugging this issue in Visual Studio?

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?

**Comment by mangoepic** [comment]
@Josh-65 Still happens on Version: 2.3.1.0
OS Version: 10.0.22000.739

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
This is the expected behavior on the home page. If you set the startup settings to restore tabs then it should focus on the file area instead.
