### ISSUE TITLE
Inaccessible base and suspicious casts in FilesOpenDialog

### ISSUE THREAD

**Issue by wnstngs** [files-community/Files#6546]
It looks like `IFileDialog` is inaccessible due to imbiguity: https://github.com/files-community/Files/blob/39a40ed9556e559e5a0e57c256750379e9e6b978/Files.OpenDialog/CustomOpenDialog/FilesOpenDialog.h#L29
class `CFilesOpenDialog` ---> `IFileDialog`
class `CFilesOpenDialog` ---> `IFileDialog2`        ---> `IFileDialog`
class `CFilesOpenDialog` ---> `IFileOpenDialog` ---> `IFileDialog`
_[clang-dignostic-inaccessible-base]_

And due to inaccessible base cannot convert `this` to `IFileDialog *` https://github.com/files-community/Files/blob/39a40ed9556e559e5a0e57c256750379e9e6b978/Files.OpenDialog/CustomOpenDialog/FilesOpenDialog.cpp#L161
(workaround(?) `reinterpret_cast<IFileDialog *>(this)`)

Cannot cast `CFilesOpenDialog *` to `IFileDialog *` via `static_cast` in
```C
#define COM_INTERFACE_ENTRY(x)\
	{&_ATL_IIDOF(x), \
	offsetofclass(x, _ComMapClass), \
	_ATL_SIMPLEMAPENTRY},
```
-- `offsetofclass(base, derived)` -->
```C
#define offsetofclass(base, derived) ((DWORD_PTR)(static_cast<base*>((derived*)_ATL_PACKING))-_ATL_PACKING)
```
https://github.com/files-community/Files/blob/39a40ed9556e559e5a0e57c256750379e9e6b978/Files.OpenDialog/CustomOpenDialog/FilesOpenDialog.h#L42

**Comment by yaichenbaum** [comment]
@gave92

**Comment by wnstngs** [comment]
> 
> 
> @wnstngs thank you for bringing this up. Have you seen this causing issues? Appears to compile and run correctly except for a compile-time C4584 warning. Plus both IFileOpenDialog and IFileDialog2 are defined as ": public IFileDialog", why would it give "inaccessible base"?

If the modifier were private, then there'd be an error. Now it’s a warning, I think caused by multiple inheritance. I don’t have a code at the moment, but I think you’re inheriting something that you already have a copy of (e.g. inheriting object A which has base-class B and inheriting explicitly object B).

**Comment by gave92** [comment]
Correct, but it appears I have to do it or COM won't work for that interface (IFileDialog). Currently not seeing that working being an issue.

**Comment by d2dyno1** [comment]
@gave92 Can you confirm it's resolved?
