### ISSUE TITLE
Show long names of files with mouse hover

### ISSUE THREAD

**Issue by MarcAnt01** [files-community/Files#655]
**Is your feature request related to a problem? Please describe.**
When a file has a long name, it could be shown with mouse hover like Windows explorer does.

**Describe the solution you'd like**
Implement it in the in-folder view

**Describe alternatives you've considered**
None

**Additional context**
Not needed

**Comment by Daninator1** [comment]
@MarcAnt01 Are you planning on implementing this yourself? Otherwise I'd be willing to do it.

**Comment by MarcAnt01** [comment]
> @MarcAnt01 Are you planning on implementing this yourself? Otherwise I'd be willing to do it.

No, just go for it 😉

**Comment by Daninator1** [comment]
> > @MarcAnt01 Are you planning on implementing this yourself? Otherwise I'd be willing to do it.
> 
> 
> 
> No, just go for it 😉 

Alright, thanks! 🙂 @yair100 you can assign me this issue!

**Comment by Daninator1** [comment]
Just a quick heads up regarding this issue, I started implementing it a while back but faced a couple of issues. At the moment I do not have much time to work on this so it would be fine if someone else would be willing to implement it. I'm unassigning myself and @yair100 can move this one back to To Do again. When I'll find time again I can take another look at it as long as no one else has worked out a solution until then.

**Comment by yaichenbaum** [comment]
This enhancement was recently implemented in `main`.
