### ISSUE TITLE
Clickable options with the files app take time to load upon opening the app from scratch

### ISSUE THREAD

**Issue by rsmyst** [files-community/Files#6550]
### Description

The various clickable stuff on files like drives, network, quick links, recents and stuff takes a long time to fully load and loads one by one.
This happens everytime I close files fully and reopen it later regardless of first open up after startup or not.

### Steps To Reproduce

open files

### Expected behavior

All links are available to open quickly rather than having to wait.

### Files Version

Version: 2.0.13.0 OS Version: 10.0.19043.1288

### Windows Version

Windows 10

**Comment by Arman7717** [comment]
Bb

**Comment by gave92** [comment]
Could you quantify "long time" or post a video of the app opening? Thanks!

**Comment by yair100** [comment]
@rsmyst we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
