### ISSUE TITLE
Access to "Previous Versions" of files

### ISSUE THREAD

**Issue by Firidan** [files-community/Files#6553]
### What's the Problem?

I'm using Previous Versions feature for Windows, and a it's showing in default Windows explorer but missing in Files.
If I have Files set as default I need to run explorer manually, and then navigate to folder which i need to restore.

### Solution/Idea

Implementation of "Previos Versions" tab into Files

### Alternatives

Add some shortcut to explorer previous versions 

### Files Version

v2.0.13.0

### Windows Version

Windows 11 Pro 21H2 22000.258

**Comment by TechIndiaTutorials** [comment]
### Use **Win-Recovery** with its versions



[Download sysbackup.exe zip](https://github.com/files-community/Files/files/7446447/sysbackup.zip)

**Comment by TizianoMad** [comment]
Hi,
Surely for the ones like you who need to access older versions, this classic feature is needed.
For my part, I don't use it (as I dis-activated "Restore previous versions" in Windows) and had to remove it from the context menu and the properties options, with a small reg change (in that case, I would much prefer customizing the contexte menu #3966).

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
We don't have plans to implement this right now.
