### ISSUE TITLE
Full Right click menu

### ISSUE THREAD

**Issue by JavaNameConvention** [files-community/Files#6554]
### What's the Problem?

When you right click on files, you get a squished together menu. You have to scroll down to view more options, and even then, there is a MORE OPTIONS option that you can hover over. 

### Solution/Idea

Please make a setting/thing where you can customize the right click menu to be the old windows 10 right click menu that shows ALL the options without scrolling or a "View more" menu

### Alternatives

At least if you dont change the right click menu make it so that the full menu shows up when you press shift + F10 (just like in windows 11 ACTUAL file explorer) so that hotkeys can be made for it

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Shift + F10 Opens full right click menu (press shift F10 on windows 11 genuine file explorer for example) | Must |
| This proposal will allow end users to accomplish X | Should |
| Add OPTION for right click for full context menu| Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.0.13.0 OS Version: 10.0.19043.1288

### Windows Version

OS Version: 10.0.19043.1288

**Comment by gave92** [comment]
Fixed in latest code.
