### ISSUE TITLE
File still visible after being deleted

### ISSUE THREAD

**Issue by fatpowaranga** [files-community/Files#6555]
### Description

There appears to be an issue when deleting a file, a lot of the time it sticks around visually until I either come back to the folder or refresh. I know this does happen from time to time in native explorer.exe, however it seems to happen far more often in Files, some days it feels like it happens for every file. It appears to happen more with single file deletes.

### Steps To Reproduce

1. Select a file.
2. Delete the document using the del or shift+del keyboard shortcut.

### Expected behavior

I would expect the view to refresh to remove the deleted file/s.

### Files Version

Version: 2.0.13.0 OS Version: 10.0.22000.258

### Windows Version

Windows 11 21H2 22000.258

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?

**Comment by fatpowaranga** [comment]
> Is this still an issue in 2.3.3.0?

I have since changed computers and don't have access to Windows 11 any more to test (unable to upgrade).

**Comment by yaichenbaum** [comment]
@fatpowaranga chances are this was resolved, if you do get a chance to test and can still reproduce, feel free to reopen this.
