### ISSUE TITLE
Bug: Files crashes when deleting an archive being extracted

### ISSUE THREAD

**Issue by MrLixm** [files-community/Files#6559]
### Description

Hey, see the step to reproduce for details.

### Steps To Reproduce

1. Download a zip archive (ex: [https://www.blender.org/download/Blender2.93/blender-2.93.5-windows-x64.zip/](https://www.blender.org/download/Blender2.93/blender-2.93.5-windows-x64.zip/))
2. Extract the archive
3. Once the directory appears, wait for a few seconds.
4. Delete the downloaded zip archive while it's still being extracted
5. Files crashes.

### Expected behavior

- Notify user that the archive is still being extracted
- Provide option to delete anyways
- Provide option to cancel

### Files Version

2.3.12.0 

### Windows Version

10.0.19042.1288

### Relevant Assets

 [debug.log](https://github.com/files-community/Files/files/9687398/debug.log)

**Comment by MrLixm** [comment]
Here is the file:

[debug.log](https://github.com/files-community/Files/files/7374963/debug.log)

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.12.0 or above?

**Comment by MrLixm** [comment]
I have stopped using Files since sorry.
I could download the last version and try on my side if you didn't manage to reproduce the issue.

**Comment by Josh-65** [comment]
If you can that would be great.

**Comment by MrLixm** [comment]
Alright downloaded Version: 2.3.12.0 (OS Version: 10.0.19044.2006)
- downloaded https://www.blender.org/download/release/Blender3.3/blender-3.3.0-windows-x64.zip/
- start extracting
- wait 1s once I got the notif that the extraction has started
- delete the zip
- files crash, the zip is not deleted

**Comment by Josh-65** [comment]
Thanks, could you upload the logs files directly to GitHub. You can get them in files settings > about > open log folder.

**Comment by MrLixm** [comment]
Sure: [debug.log](https://github.com/files-community/Files/files/9687398/debug.log)

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
Should we prevent deleting the archive or should the delete action still work and the extract operation fail?

**Comment by Josh-65** [comment]
I presume cancelling the extraction then running a delete operation would make sense.

**Comment by ferrariofilippo** [comment]
I can't reproduce this issue in 2.4.66, I think it's fixed
