### ISSUE TITLE
Add list layout

### ISSUE THREAD

**Issue by zzz6839** [files-community/Files#6560]
### What's the Problem?

List layout is helpful when u have many folders, like that.

![image](https://user-images.githubusercontent.com/57741549/137907884-7420d5b0-69f7-4b6c-a5a4-6beda9169a50.png)

### Solution/Idea

Add list layout

### Alternatives

please optimize the render and open speed of the app.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

latest

### Windows Version

22000.258 win11

**Comment by yaira2** [comment]
@zzz6839 thank you for your patience, I'm excited to share that a List View layout will be included in the next release.
