### ISSUE TITLE
Drag and drop on windows 11 

### ISSUE THREAD

**Issue by Wtcheesecakes** [files-community/Files#6562]
### Description

Dragging and dropping files from files to another app doesnt work

### Steps To Reproduce

Try to drag and drop a file/folder to another app and it wont work

### Expected behavior

Should be able to drag and drop like normal

### Files Version

Version: 2.0.20.0 

### Windows Version

Windows 11 OS Version: 10.0.22000.282

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7375080/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7375081/debug_fulltrust.log)

**Comment by Jack-Works** [comment]
I also tried to drag-and-drop to upload it to the browser (e.g. Gmail) and not working

**Comment by yaichenbaum** [comment]
Merging with #6941
