### ISSUE TITLE
Build failed: MSB3026

### ISSUE THREAD

**Issue by georgetian3** [files-community/Files#6567]
### Description

Build from source is failing with the following error:

MSB3026	Could not copy "C:\Users\George\.nuget\packages\microsoft.ui.xaml\2.7.0\buildTransitive\..\lib\uap10.0\Microsoft.UI.Xaml.winmd" to "..\artifacts\Release\x64\\Files.Package\\Microsoft.UI.Xaml.winmd". Beginning retry 4 in 1000ms. The process cannot access the file '..\artifacts\Release\x64\\Files.Package\\Microsoft.UI.Xaml.winmd' because it is being used by another process. 

### Steps To Reproduce

1. Clone source code
2. Open `Files.sln` with Visual Studio 2022 Preview
3. Retarget solution to latest Windows SDK version
4. Change build config to 'Release' and 'x64'
5. Build

### Expected behavior

Build to complete successfully

### Files Version

Latest source code

### Windows Version

Windows 10  21H1 19043.1288

**Comment by yaichenbaum** [comment]
@duke7553 did you mention you ran into this issue as well?

**Comment by IstvanKor** [comment]
I ran into this issue when trying compiling a large solution in release mode.
Temporary solution if you comment line number 77 in Common.targets file in C:\Users\username\.nuget\packages\microsoft.ui.xaml\2.7.0\buildTransitive folder.
This is the second one before last line.

**Comment by georgetian3** [comment]
Thank you all for the suggestions. The workarounds suggested by @hez2010 and @IstvanKor both work. As this doesn't seem to be a bug in Files itself, I'd think its appriopriate to close this issue.
