### ISSUE TITLE
Disk Cleanup button on Hard Drive properties

### ISSUE THREAD

**Issue by cassianofonseca** [files-community/Files#6578]
### What's the Problem?

The Disk Cleanup button on Hard Drive properties doesn't appear, like windows explorer

![image](https://user-images.githubusercontent.com/92881406/138140636-9ce06fb7-2e91-4c8d-9b54-f7fbfcc4d731.png)

![image](https://user-images.githubusercontent.com/92881406/138140694-c053a1f7-bf51-4f7a-a902-2ce673449c6b.png)

### Solution/Idea

Please create this button in hard drive properties

### Alternatives

Doesn't have

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.0.13.0 OS Version: 10.0.19042.1288

### Windows Version

Windows 10 Enterprise 20H2

**Comment by yaichenbaum** [comment]
@cassianofonseca the properties window is a way to view basic information about the drive, for more advanced options such as cleaning old files, we recommend using the built-in tools in the Windows settings apps.
