### ISSUE TITLE
Add ctrl + shift + k shortcut to duplicate tabs

### ISSUE THREAD

**Issue by 439bananas** [files-community/Files#6579]
### Solution/Idea

The keybind would be heavily useful from a productivity perspective, especially where pressing a keybind is faster than right-clicking a tab and pressing duplicate. This keybind should have the binding ctrl + k or ctrl + shift + k, given that they tend to be used in browser environments and they're not drastically different for the user to understand.

### Alternatives

An alternative I've considered, however impractical, is also to allow for custom keybinds to allow users to change their own.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| A keybind for duplicating tabs | Must |
| Display shortcut on menu when right clicking tab | Must |
| Update documentation with the shortcut | Must |

### Files Version

Version: 2.0.13.0

### Windows Version

Windows 11 Insiders Dev 22478.1012

### Additional comment

If you require further information, feel free to reply to this message or, preferably, ping me on Discord (Banana#0003; I don't tend to read GitHub notifications)

**Comment by StuartvdLee** [comment]
Is it OK if I work on this?

**Comment by d2dyno1** [comment]
This should issue should be resolved with #7884

**Comment by BlairCurrey** [comment]
this should be resolve by https://github.com/files-community/Files/pull/7901

**Comment by yaichenbaum** [comment]
@BlairCurrey does the right click menu show the shortcut?
![image](https://user-images.githubusercontent.com/39923744/150691891-8631131a-57ae-4038-a05a-789ea0a4412a.png)

**Comment by BlairCurrey** [comment]
It does not - good catch. I will work on adding that.

**Comment by BlairCurrey** [comment]
@yair100  I've added the tooltip - should I also be adding the shortcut to the language files where similar commands are included? `Files\src\Files\Strings\af\Resources.resw` etc? I added them to `en-GB/Resources.resw` and `en-US/Resources.resw` locally but see there are many more that include similar shortcuts.

**Comment by yaichenbaum** [comment]
@BlairCurrey yes.
