### ISSUE TITLE
When right-clicking sidebar items, menu appears off-screen

### ISSUE THREAD

**Issue by georgetian3** [files-community/Files#6582]
### Description

Placing the mouse on an item in the sidebar and right-clicking menu to appear offscreen. The position varies depending on the monitor setup:

- When Files is maximized either on a single monitor or on the left-most (main) monitor in a triple-monitor setup, the menu is cut off:
![menu](https://user-images.githubusercontent.com/14836161/138232428-517a7389-038f-42d0-9b92-b48f108f92a1.png)

- Files is maximized on the 2nd monitor of a triple monitor setup, the menu is completely shown on the adjacent monitor:
![spillover](https://user-images.githubusercontent.com/14836161/138232658-9189130b-61c0-4261-8db0-06b90f3d6d7a.png)

### Steps To Reproduce

1. Right click any item in the sidebar **near the left side of the item**. If right clicking near right side, the menu is displayed as expected.

### Expected behavior

Cutting off a portion of the menu is obviously unwanted behavior, and it seems unintuitive to show the menu on a monitor other than the one Files is open on. What I'd expect (please correct me if I'm being pedantic) is for the entire menu to be shown within that one monitor, such as:
![expected](https://user-images.githubusercontent.com/14836161/138233276-19e4ce17-0699-4d6d-b389-1f6404dfd644.png)

### Files Version

2.0.13.0

### Windows Version

Windows 10 21H1 19043.1288

**Comment by Josh-65** [comment]
This is a known WinUI issue and not fixable by Files
