### ISSUE TITLE
Set downloads folder to group by date

### ISSUE THREAD

**Issue by aayushyap89** [files-community/Files#6586]
### What's the Problem?

Till now i was using the default grouping which is nothing but I just found out that you can group by date created/modified which is so useful and would really be nice to make it default like in regular file explorer for the downloads folder.

### Solution/Idea

Just make group by date modified default.

### Alternatives

Just make group by date modified default.

### Files Version

v2.0.28.0

### Windows Version

Windows 11 21H2 22000.282

**Comment by ssm498** [comment]
I am going to give this a shot! I am new to open source and want to get my feet wet.

**Comment by ssm498** [comment]
I managed to mess around in FolderSettingsViewModel.cs and add DirectorySortOption = SortOption.DateModified in the 'FromCompositeValue' function, but this had some 'side effects'. Mainly that the default for the whole program was set to DateModified, and not just the Downloads folder. I wanted to ask if anyone could let me know if this is the correct folder to mess with. I tried going into other functions in this folder to set DirectorySortOptions correctly, but nothing seemed to be working. Maybe I am trying to find a script that gets called whenever a new folder is accessed, but I am not sure where that is. Could someone point me in the right direction?

**Comment by yaichenbaum** [comment]
@ssm498 did you look in ItemViewModel? I think the actual code for sorting items is in this file.

**Comment by ssm498** [comment]
@yair100 Wow... that was really good advice! I am legit surprised It worked. Now if it was the correct way of working that is TBD lol.

**Comment by ssm498** [comment]
Ill clean up my debugging comments and send in a PR

**Comment by yaichenbaum** [comment]
@ssm498 do you still have these changes?

**Comment by esibruti** [comment]
@yair100 If he doesn't have the changes, can I make them?

**Comment by yair100** [comment]
> @yair100 If he doesn't have the changes, can I make them?

Yes

**Comment by yaichenbaum** [comment]
This issue should be resolved with #9248
