### ISSUE TITLE
Drives don't appear anymore no matter what, rendering the program useless

### ISSUE THREAD

**Issue by notNSANE** [files-community/Files#6591]
### Description

Drives have stopped appearing at the sidebar and root.

No idea why or how they stopped showing, they just don't appear anymore.

### Steps To Reproduce

1. Open Files
2. Check sidebar

Toggling the "show drives" option doesn't do anything.

### Expected behavior

Drives appear

### Files Version

2.0.13.0

### Windows Version

10.0.19043.1288

### Relevant Assets

![Screenshot 2021-10-22 144719](https://user-images.githubusercontent.com/7162375/138500170-ff931ef1-dbf8-4321-be7c-6141c02d0642.png)

**Comment by oshox** [comment]
I'm having the same issue on the same Windows & app version.
I'm uploading the two files you've requested, but they don't look like they contain anything useful.

[debug.log](https://github.com/files-community/Files/files/7447942/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7447943/debug_fulltrust.log)
