### ISSUE TITLE
Zip file dont open

### ISSUE THREAD

**Issue by Gor80hd** [files-community/Files#6592]
### Description

When opening zip files, this error is displayed (Disk offline NotAFolder)
![image](https://user-images.githubusercontent.com/92448318/138510784-7d0f6e28-c99b-42a4-a93f-a6bdbd14acc8.png)

### Expected behavior

Zip file must opened 

### Files Version

Версия: 2.0.28.0 OS Version: 10.0.22000.258

### Windows Version

Windows 11 Pro Version 21H2

**Comment by gave92** [comment]
@Gor80hd does it happens if the file extension is lowercase ".zip"?

**Comment by Carson365** [comment]
I am having the same issue. Windows 11 Edu Version 21H2, Files Version 2.0.34.0,
OS Version 10.0.22000.194.
A ".zip" (lowercase) file will lead to this behavior when trying to open with files.

**Comment by gave92** [comment]
@Carson365 what app is set as default app for opening zip files?

**Comment by KibSquib48** [comment]
I'm having the same issue on Windows 11 22000.469, and I have Files set as the default zip opener
