### ISSUE TITLE
new tabs open with a tab name of Files.UserControls.MultitaskingCom... and any subsequent action does not change this

### ISSUE THREAD

**Issue by AlexNovitchkovBurbank** [files-community/Files#6593]
### Description

tab cuts out so I cannot see the rest of what it says. It was fine in Version 2.0.0 but not in 2.0.13

### Steps To Reproduce

Click on new tab or press Ctrl+T
click on any folder/drive in the directory

### Expected behavior

Expect that when I click on a new tab, the name of the location where I am currently in shows up. Ex: Home when the "home screen" quick access screen appears. Or Downloads if I am in the downloads folder

### Files Version

v2.0.13.0

### Windows Version

Windows 11 build 22483

**Comment by gave92** [comment]
Also #6565, is this issue fixed @yair100?

**Comment by yair100** [comment]
> Also #6565, is this issue fixed @yair100?

Not yet but @d2dyno1 was working on a fix.

**Comment by BanCrash** [comment]
> > Can't reproduce. Could you add detailed steps and a log file? @Seraphim7
> 
> Try opening a second tab, in my case the second tab doesn't have any title.

@yair100 I can't replicate neither:

(It is not showed on the gif, but first I open a new tab and then I opened the Downloads folder from the Home page)
![GIF 26-10-2021 19-31-15](https://user-images.githubusercontent.com/11770760/138930692-f3e363e0-c853-4894-bb47-594595ad0f35.gif)

Versión: 2.0.30.0
OS Version: Windows 10 21H1 10.0.19043.1288

**Comment by BanCrash** [comment]
> > > @BanCrash might be limited to Windows 11 then.
> > 
> > Oh, for some reason I thought @d2dyno1 has Windows 11, I'll be wrong in that case.
> 
> I have Windows 11 (21H2 22000.282)
> ![image](https://user-images.githubusercontent.com/53011783/138940589-5e065754-54c4-428e-90c2-064940e76e86.png)
> 

@yair100 do you have another W11 version? Maybe it's for one specific W11 build then lol.

Edit: your W11 version seems prior to the version of the first post (@Seraphim7 's version), maybe it's on a insider update the root cause of the issue.

**Comment by d2dyno1** [comment]
> @BanCrash I'm on the latest insider version, seems like many other users are having the same issue.

I guess then you could try to fix this issue
@yair100

**Comment by ealap** [comment]
This might be a different issue but aside from the incorrect tab name, the tab shape is different, too.
![image](https://user-images.githubusercontent.com/15620712/139518387-6093f203-3a09-4dc7-85f3-1d9ff09dcc4b.png)

OS: Windows 11 22489.1000
Files v2.0.13.0

**Comment by Seraphim7** [comment]
> 
> 
> This might be a different issue but aside from the incorrect tab name, the tab shape is different, too. ![image](https://user-images.githubusercontent.com/15620712/139518387-6093f203-3a09-4dc7-85f3-1d9ff09dcc4b.png)
> 
> OS: Windows 11 22489.1000 Files v2.0.13.0

Same here

**Comment by Seraphim7** [comment]
Same here

**Comment by Seraphim7** [comment]
> 
> 
> Can't reproduce. Could you add detailed steps and a log file? @Seraphim7

![image](https://user-images.githubusercontent.com/22435977/139518757-4580575a-0d00-4e4d-9d06-35c8b4fc678a.png)
I get this exception as part of the debug_fulltrust.log

**Comment by manups4e** [comment]
![image](https://user-images.githubusercontent.com/4005518/139527241-7a5d981e-b8de-4307-bd5b-bb815f1ec772.png)
I set it to open 3 folders each startup.

**Comment by Seraphim7** [comment]
This is fixed in Windows 11 build 22494, the latest build

**Comment by yaichenbaum** [comment]
> This is fixed in Windows 11 build 22494, the latest build

Thank you for the update! That's good news.
