### ISSUE TITLE
Feature: Show pinned items in Folders Widget

### ISSUE THREAD

**Issue by frg2089** [files-community/Files#6596]
### What's the Problem?

`explorer.exe` can read custom folders from the registry. but the `files` app cannot.

The "项目" folder is a custom item and it was not show in `Files` app.
![image](https://user-images.githubusercontent.com/42184238/138536430-dcf80959-2442-4efd-a6c7-d9d9f39b231c.png)
![image](https://user-images.githubusercontent.com/42184238/138536487-8fa460b5-850d-4ef9-8e2a-489be24ac2e9.png)

### Solution/Idea

It can get [`CLSID`](//docs.microsoft.com/windows/win32/com/clsid-key-hklm) items from Registry path `HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\MyComputer\NameSpace\` and `HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\MyComputer\NameSpace\`.

Then, go to the path `HKCR\CLSID\` and find `CLSID` item.
You can also use `HKCU\Software\Classes\CLSID\` and `HKLM\Software\Classes\CLSID\` to replace `HKCR\CLSID\`

The display name is the default value for `CLSID` item.
Icon is the default value for `DefaultIcon` item.
We can find folder path from item `Instance\InitPropertyBag` and key `Target`

See
- [Specifying a Namespace Extension's Location - Microsoft Docs](//docs.microsoft.com/windows/win32/shell/nse-junction)
- [Specifying a Namespace Extension's Location - Legacy Microsoft Docs](//docs.microsoft.com/previous-versions/windows/desktop/legacy/cc144096(v=vs.85))
- [How to create a System folder in My Computer in Windows 10 - technospot.net](//www.technospot.net/blogs/how-to-create-a-system-folder-in-my-computer/)

### Alternatives

The `Favorites` can replace it easy.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Show Folder Items. | Must |
| Show folder icon. | Should |

### Files Version

Version: 2.0.13.0 OS Version: 10.0.22478.1012

### Windows Version

版本	Windows 11 专业版 Insider Preview 版本	Dev 安装日期	‎2021/‎10/‎16 操作系统版本	22478.1012 体验	Windows Feature Experience Pack 1000.22478.1012.0

**Comment by yaichenbaum** [comment]
We don't have plans to implement these changes, but we do plan to add a recent items page where you can see more recent items #2718.

**Comment by frg2089** [comment]
What I mean is explorer.exe can be extended by the registry.

I can create a new folder in "This PC".

Look this screenshot. 
It has 2 "Custom Folders" and is located in "Folders" and "Devices and drives" respectively.
And these two folders do not exist in a new installation of Windows OS
![image](https://user-images.githubusercontent.com/42184238/138576983-570eb202-acb2-460f-a66e-2849e63ccc6a.png)

**Comment by yaira2** [comment]
@hecksmosis
