### ISSUE TITLE
Can't see the image preview

### ISSUE THREAD

**Issue by Mattiuz93** [files-community/Files#6599]
### Description

From some days the app doesn't show the preview of some images (not all). Can u fix it please?

### Steps To Reproduce

![Screenshot (292)](https://user-images.githubusercontent.com/68841551/138566000-13fb797c-ccdf-443b-b189-2951777eae79.png)

### Expected behavior

I expected to see the previews of all images that I've

### Files Version

2.0.13.0

### Windows Version

Windows 10 21H2 19044.1288

### Relevant Assets

[debug_fulltrust.log](https://github.com/files-community/Files/files/7403415/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7403416/debug.log)

**Comment by yaichenbaum** [comment]
Merging with #2582
