### ISSUE TITLE
Files Crashing on Open

### ISSUE THREAD

**Issue by GrantNNZ** [files-community/Files#6602]
### Description

I open the app and it crashes immediately, does not work ever.

### Steps To Reproduce

Open files.

### Expected behavior

For the app to open and run.

### Files Version

v2.0.12.0

### Windows Version

Windows 11 Pro 21H2

### Relevant Assets
Video & logs attached 

https://imgur.com/a/VfmxTd
[debug.log](https://github.com/files-community/Files/files/7403951/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7403952/debug_fulltrust.log)

**Comment by GrantNNZ** [comment]
Looks like it could be related to my network drive, not sure how to troubleshoot.

**Comment by duke7553** [comment]
@GrantNNZ The issue reported appears to have occurred measurably less in the stable builds of Files released over the last 90 days. If it still occurs, you'll want to reinstall the latest stable version of the app. We find user context around regressions valuable, so if you hit the same bug, open a new issue report here which references ticket #6602 & contains your log files.
