### ISSUE TITLE
Copy - Past Is not working

### ISSUE THREAD

**Issue by MrZak-dev** [files-community/Files#6603]
### Description

Copying a file from folder to another seems not doing what it should does .

### Steps To Reproduce

1. Copy a file from  a folder
2. Go to another folder
3. Press Past 
4. Nothing happens

https://user-images.githubusercontent.com/27586088/138583234-dfa4a430-4f3f-4da9-8e05-01b2f366e97d.mp4

### Expected behavior

Normal Copy Past behavior 

### Files Version

Version: 2.0.13.0 OS Version: 10.0.22000.258

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎10/‎10/‎2021 OS build	22000.258 Experience	Windows Feature Experience Pack 1000.22000.258.0

**Comment by gave92** [comment]
Merging with #7459
