### ISSUE TITLE
Add F3 shortcut to toggle the dual layout feature

### ISSUE THREAD

**Issue by Faiataiga** [files-community/Files#6606]
### What's the Problem?

As someone who's comming from an KDE Background (Dolphin as Filemanager) i'm used to different Keyboardshortcuts.
The Problem is that i see no way of that option in Files. Not in an .json like the Terminal setting or an GUI option

### Solution/Idea

A way to customize the Keyboard shortcut without modification of the source code.
Like through the Settings in the Settings Page or through an .json similar to that of Terminal:
```json
{
    "$schema": "https://aka.ms/terminal-profiles-schema",
    "actions": 
    [
        {
            "command": 
            {
                "action": "splitscreen",
            },
            "keys": "ctrl+alt+s"
        },
    ]
}
```
with a Syntax like that example.

For these Types of things its nice to have an extended list for all actions like this one again from Terminal https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions

### Alternatives

An Alternative is through the Registry with an key in `HKCU\SOFTWARE\Files-community\shortcuts`
and put the "Actions" into an `REG_SZ` type and the shortcut in the data field.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| The change of keyboard shortcuts without manual change of the sourcecode | Must |
| Changing it through an .json, with well documented actions | Should |
| Changing it through the Settings in the App with entries for each Action | Could |

### Files Version

v2.0.13.0

### Windows Version

Windows 10 Pro Version 20H2 Build 19042.1288

**Comment by petrjancar** [comment]
What is the current shortcut that you want to change? I am not sure which one do you mean by "toggle the dual layout feature".

**Comment by Faiataiga** [comment]
I mean the alt+shift++ shortcut, where i can work in this Dual panel mode.

**Comment by LastDerivative** [comment]
@yaichenbaum I can take this on

**Comment by yaichenbaum** [comment]
Merging with #1660

**Comment by yaira2** [comment]
This feature will be included in the next release. Please see #9559 for more details.
