### ISSUE TITLE
Need help to install this file

### ISSUE THREAD

**Issue by Kytrex5625** [files-community/Files#6611]
### Description

so I tried simply downloading it install and it just said " App Installer failed to install package dependencies "
then I downloaded vs ( visual studio 2019 ) and I'm totally new to this thing and have no idea what am I doing all
so far I follow a youtube video where he teach me to use git to download the file and also I successfully let vs run and patch or fix the program, then when I try to start It. It just notice me that it got error in it and i have no idea what to do next so pls help.

### Expected behavior

so I tried simply downloading it install and it just said " App Installer failed to install package dependencies "
then I downloaded vs ( visual studio 2019 ) and I'm totally new to this thing and have no idea what am I doing all
so far I follow a youtube video where he teach me to use git to download the file and also I successfully let vs run and patch or fix the program, then when I try to start It. It just notice me that it got error in it and i have no idea what to do next so pls help.

### Files Version

2.0.13.0

### Windows Version

20h2

**Comment by gave92** [comment]
@yair100 do the appx you post on Discord contain all the dependencies?

**Comment by yair100** [comment]
> @yair100 do the appx you post on Discord contain all the dependencies?

@gave92 they contain subfolders with all the dependencies.
