### ISSUE TITLE
Can't copy/-drag files from Files onto VSCode

### ISSUE THREAD

**Issue by seiyria** [files-community/Files#6613]
### Description

When I drag files onto VSCode using explorer.exe, it shows specific locations in VSCode where the files would be dropped, and allows me to copy and paste them into VSCode. Similarly, I can do CTRL+C and CTRL+V to copy/paste into VSCode. 

Files does not seem to allow me to do either.

### Steps To Reproduce

1. Open Files
2. CTRL+C a file
3. Open a VSCode project
4. Try to paste the file into VSCode

### Expected behavior

I am expecting to copy the files into VSCode.

### Files Version

Version: 2.0.13.0 OS Version: 10.0.19042.1266

### Windows Version

19042.1266

**Comment by gave92** [comment]
This issue should be fixed on main.

**Comment by gave92** [comment]
In my testing Drag & Drop to VS Code works correctly. Ctrl+C / Ctrl+V doesn't but doing the same from explorer does not do anything.

**Comment by seiyria** [comment]
Weird, my apologies, it seems like it works for me to do drag and drop and it also now doesn't work with CTRL+C/V. I'm actually confused because I thought I tested this! No worries, and thank you for responding.
