### ISSUE TITLE
Search issue

### ISSUE THREAD

**Issue by TnDoshi** [files-community/Files#6618]
### What's the Problem?

I download several graphic content and all of them a =re zipped files. I unzip them to each individual folder. For eg a folder name food contains 100's of folders and they have JPEG's or ai files in it. In windows file explorer  in the search bar I have to just type a .jpeg or .ai and it will show me the list of all the files with that extension, but in this Files - File Manager for Windows I am not able to do it.‪

### Solution/Idea

Just add it

### Alternatives

It quite a handy feaure

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.0.13.0

### Windows Version

Windows 11 Pro Version	21H2

### Additional comment

Thanks

**Comment by yaichenbaum** [comment]
This issue should be resolved with #6671.
