### ISSUE TITLE
Insert and open a USB drive error

### ISSUE THREAD

**Issue by chuwy2k** [files-community/Files#6621]
### Description

Hi everyone.
This error occurred when:
1. I plugged an USB drive (DataTravelerG4 32 Gb) drive with a corporate image for ISO Windows installation.
2. When I plugged the USB, no problem, it was recognized by Files successfully, but when
3. I tried to see the content, Files closes and throw a bug error report window.

### Steps To Reproduce

1. To plug an USB drive (DataTravelerG4 32 Gb) drive with a corporate image for ISO Windows installation.
2. When I plugged the USB, no problem, it was recognized by Files successfully, but when
3. I tried to see the content, Files closes and throw a bug error report window.

### Expected behavior

To see USB drive content.

### Files Version

v2.0.13.0

### Windows Version

Edition	Windows 10 Home Version	21H1 Installed on	‎05/‎07/‎2021 OS build	19043.1288 Serial number	PF140SNT Experience	Windows Feature Experience Pack 120.2212.3920.0

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7421104/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7421112/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
@chuwy2k is this still an issue in the preview version? http://files.community/download/preview
