### ISSUE TITLE
Add support for expanding the preview pane further than 400px

### ISSUE THREAD

**Issue by bnbagiz** [files-community/Files#6628]
### Description

The Preview Pane is way too small to read anything, so its barely useable. I can not stretch the pane either. The range I can adjust the size is really small.

### Expected behavior

larger range to adjust the pane

### Files Version

Version: 2.0.13.0 

### Windows Version

OS Version: 10.0.19043.1288

**Comment by yaichenbaum** [comment]
@bnbagiz how wide are you trying to stretch it?

**Comment by tommymasterseries** [comment]
@yair100 my screen is 1920x1200   the preview window won't expand above 400 px
![2021-11-05_08-37-34-min](https://user-images.githubusercontent.com/93268389/140483069-945a711f-8b57-4e14-ac65-096c4e8cc4e4.png)

**Comment by ptmrio** [comment]
Same here, it's a productivity killer. Keep improving, nice work!

**Comment by bnbagiz** [comment]
> @bnbagiz how wide are you trying to stretch it?
> @yair100 my screen is 1920x1200 the preview window won't expand above 400 px ![2021-11-05_08-37-34-min](https://user-images.githubusercontent.com/93268389/140483069-945a711f-8b57-4e14-ac65-096c4e8cc4e4.png)

it looks exactly like in that picture yair100 posted. you cant use the panel to preview a pdf at this moment, which is my daily usage to search for a quick info in a doc without opening them

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7920
