### ISSUE TITLE
Libraries need proper seperation

### ISSUE THREAD

**Issue by infuriatedcodex** [files-community/Files#6631]
### What's the Problem?

Adding proper Libraries (Lib) is most welcomed.
However all files/folders from any library source is bundled into a single view making it difficult to tell its actual source especially for users who's workflow involves alot of file management.

Example if my "Documents" Lib has sources from C:\Temp\**Project1** and D:\Temp\**Project1**, then the Lib will show 2 instances of **Project1**.

A small clue is revealed if the folder exists in OneDrive with the status column but if its a local folder, you're out of luck.

### Solution/Idea

Introduce a view similar to the native explorer, where the folder sources are separated.

### Alternatives

Include a new Column that shows the source folder.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.0.13.0

### Windows Version

Windows 11 22000.282

**Comment by infuriatedcodex** [comment]
Thanks for confirming  @yair100 , thought I was going mad missing something obvious

**Comment by yair100** [comment]
> Thanks for confirming @yair100 , thought I was going mad missing something obvious

Sorry about that 😂
