### ISSUE TITLE
Terminal opened by Files doesn't update its environment variables with each launch

### ISSUE THREAD

**Issue by starkgate** [files-community/Files#6634]
### Description

Terminal opened by Files doesn't update its environment variables upon launch.

### Steps To Reproduce

1. Open Files
2. Set an environment variable through the System properties > Environment variables dialog
3. Open a terminal from within Files
4. Try to access the newly added variable

### Expected behavior

The expected behaviour for a terminal is to read the environment variables on startup of the terminal, not of the application launching it (Files).

### Files Version

Version: 2.0.13.0 

### Windows Version

OS Version: 10.0.19043.1288

**Comment by yaichenbaum** [comment]
This issue should be resolved with #6663.
