### ISSUE TITLE
CloudStation in Cloud Storages

### ISSUE THREAD

**Issue by Jipem** [files-community/Files#6637]
### Solution/Idea

Hello,

Include Synology's NAS CloudStation  in Cloud Storages would be interesting.
https://kb.synology.com/fr-fr/DSM/help/CloudStationDrive/cloudstationdrive

Thanks !

### Alternatives

Do without.

### Files Version

2.0.13.0

### Windows Version

Windows 11 Famille 21H2 22000.258

**Comment by yaichenbaum** [comment]
Merging with #8084
