### ISSUE TITLE
Files crashes when pressing Ctrl+L in column view

### ISSUE THREAD

**Issue by pavangayakwad** [files-community/Files#6638]
### Description

Files crashes always whenever I perform steps given below

### Steps To Reproduce

- Open Files app (It is configured to "column view" macOS style folder navigation)
- Go to 2 or 3 folders level deep
- Hit ALT + D
- App crashes.

### Expected behavior

App should not crash!

### Files Version

Version: 2.0.13.0

### Windows Version

OS Version: 10.0.19043.1288

### Relevant Assets

[debug_fulltrust.log](https://github.com/files-community/Files/files/7429065/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7429066/debug.log)

**Comment by pavangayakwad** [comment]
Not fixed in the latest update release.

I open folder and select file like it is shown in the screen capture, now I hit `ALT + L` or `ALT + D` Nothing happens. It was supposed to select the folder path.

![image](https://user-images.githubusercontent.com/1834890/140397878-a9af4635-7eed-4951-8b9b-bd80229eb5b4.png)

**Comment by yaichenbaum** [comment]
@pavangayakwad I don't think those shortcuts were implemented, we only fixed the crash that happened. Can you open a feature request for this?

**Comment by gave92** [comment]
Actually I was supposed to work :)

**Comment by pavangayakwad** [comment]
@yair100  Are you sure? I find `ALT + E` working for most of the time.

![image](https://user-images.githubusercontent.com/1834890/140400919-7e75fb56-6080-49cb-9b47-ffdd7d42df8c.png)

**Comment by yaichenbaum** [comment]
> Actually it was supposed to work :) (And it does for me)

@pavangayakwad can you confirm which version of Files you're using?

**Comment by gave92** [comment]
Edit: works for me if I click on a file first (on any column).

**Comment by pavangayakwad** [comment]
@yair100

Version: 2.0.33.0
OS Version: 10.0.19043.1320

**Comment by 42-star** [comment]
73  Fairfield manor

morgantown, wv 26505
