### ISSUE TITLE
Improve animations in the settings dialog

### ISSUE THREAD

**Issue by kaname-png** [files-community/Files#6643]
### Description

When opening the options menu the animation is not clean, a frame appears first on the right and then appears in the center. I think it should not be like that.

https://user-images.githubusercontent.com/56084970/139189689-38b75061-f4e4-4cfc-8482-2899b8ee4cbe.mp4

### Steps To Reproduce

1. Open Files.
2. Open Settings Menu

### Expected behavior

A clean and elegant animation like the other components of the application.

### Files Version

v2.0.13.0

### Windows Version

Windows 11 Enterprise 21H2 22000.282

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7431177/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7431178/debug_fulltrust.log)

**Comment by IstvanKor** [comment]
I'm not sure this problem is related to the following, but there is an issue with the animation of ContentDialog in WinUI 2.6 and above on Windows 11.
https://github.com/microsoft/microsoft-ui-xaml/issues/5573

**Comment by yaichenbaum** [comment]
> I'm not sure this problem is related to the following, but there is an issue with the animation of ContentDialog in WinUI 2.6 and above on Windows 11. [microsoft/microsoft-ui-xaml#5573](https://github.com/microsoft/microsoft-ui-xaml/issues/5573)

That's a bit unrelated, anyways, this issue should be resolved wtih #6688.
