### ISSUE TITLE
Bad UX of jumping up (and back and foward)

### ISSUE THREAD

**Issue by TheJohny** [files-community/Files#6647]
### What's the Problem?

When I enter into directories on the file list panel (on the right side) and I want to go back or go one folder level up I've to move the mouse too much / so the required mouse route is too long (marked with the red arrow on the image). Unfortunately, the navigation icons are in the left upper corner which is bad. That place would be good if you browse the folder tree using the left side tree view but when you use the tree view usually you don't need the "up" command as you can select easily the parent on the tree view. 

![image](https://user-images.githubusercontent.com/5933893/139333615-05925ea4-af4e-4c3f-8cac-2688eac683e8.png)

### Solution/Idea

I have two solution recommendations - and much better solutions for that.

![image](https://user-images.githubusercontent.com/5933893/139333598-e6b4262f-f206-44f3-a3df-74a634e3cf6c.png)

**1st alternative solution / marked with green on the image**

Relocate the up icon from the red section to the green section

**2nd alternative solution / marked with blue on the image**

add "..." (up) row (command) to the top of the file list on the right side 

This is a typical solution 

### Alternatives

.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.0.13.0

### Windows Version

Windows 11 Pro, 21H2, 22000.2882

**Comment by TheJohny** [comment]
> @TheJohny is this really an issue if you reduce the width of the navigation menu?

@yair100  is the navigation menu the tree view on the left side (sorry for the question)
Then, you're right, in the collapsed state, the situation is much better

![image](https://user-images.githubusercontent.com/5933893/139346575-ee2d2b9c-bc7f-4ad1-be3b-09d95fa41b6c.png)

it might just reinforce that it's not in the right place - shouldn't the width of the side panel determine the location of this feature

I know, UX can be highly subjective :)

**Comment by TheJohny** [comment]
@yair100 you are right!.. forget that :)
maybe the other solution would be the best.

please don't take it as a 'smart-ass', I really like your project, it's really just the icing on the cake that I'm teasing you about. 

It's little things like this that could make the product more convenient for me 
- Left-up - make the window touchable and movable in the usual way (sometimes it's not easy because of the tabs, that part could be fixed
- the settings command could go into the ... menu
- the 'refresh' could be put on the path line itself - similar to search + it would be cleaner and wider
- the back, forward, up buttons could be moved to the section already mentioned
- the multiselect button would have a functionally appropriate place next to the first column header (now that part is unused, it fits there functionally because the selection boxes appear underneath)
- separators between tabs

**Actual**

![image](https://user-images.githubusercontent.com/5933893/139507285-3c9748ed-68c5-43b6-8685-0ccedfbb6ced.png)


**Proposed**

![image](https://user-images.githubusercontent.com/5933893/139506979-13359726-e918-46b9-bd1b-ce18b1730707.png)


**Proposed / with arrows**

![image](https://user-images.githubusercontent.com/5933893/139506919-110b4702-611a-4626-b3a7-7d2df76c4c33.png)

**Comment by yaichenbaum** [comment]
Shifting the controls around would introduce their own sets of issues 😂 
As of now, the solution we plan to implement is letting the user configure double clicking in a blank space to take an action like this. #2355
