### ISSUE TITLE
Add the This PC button instead of home

### ISSUE THREAD

**Issue by RakibRyan** [files-community/Files#6650]
### Solution/Idea

Add the This PC button instead of home

### Alternatives

Add the This PC button instead of home

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.0.13.0 OS Version: 10.0.22000.282

### Windows Version

22000

**Comment by RakibRyan** [comment]
More familiarity & instinct to click this pc whenever I'm lost in folders.

**Comment by yaichenbaum** [comment]
> More familiarity & instinct to click this pc whenever I'm lost in folders. Also instead of hiding it in favourites put it separately like a drive.

I understand the familiarity part but Files isn't File Explorer and I'm not sure that renaming the item makes sense.

**Comment by RakibRyan** [comment]
That maybe ok. But It's annoying to press favourite to find the home. Make it like a seperate tab like the drives are.

**Comment by RakibRyan** [comment]
> > More familiarity & instinct to click this pc whenever I'm lost in folders. Also instead of hiding it in favourites put it separately like a drive.
> 
> I understand the familiarity part but Files isn't File Explorer and I'm not sure that renaming the item makes sense.

That's fine if you don't think rename is necessary. But put the home button as a separate tab like the drives are. It's annoying to click on favourite to find home.

**Comment by yaichenbaum** [comment]
The `home` option is considered a favorite but we're working on allowing users to unpin it.
