### ISSUE TITLE
Feature: Add support for unblocking files from the properties window

### ISSUE THREAD

**Issue by SebaldJ** [files-community/Files#6653]
### What's the Problem?

No Option in file Properties to Unblock the File after Download.

![2021-10-29 12_14_17-Files](https://user-images.githubusercontent.com/17111835/139418779-3a5563b7-aaa0-405e-b886-2b675cedd9f7.png)

**Comment by yaira2** [comment]
Thank you for your feedback, I added this to the todo list.
