### ISSUE TITLE
Folder icon not always displaying with a transparent background

### ISSUE THREAD

**Issue by monkeyboy2805** [files-community/Files#6656]
### Description

![image](https://user-images.githubusercontent.com/20478546/139523865-0d04180f-2980-464d-820a-697823ba77b7.png)

This occurred on first launch when switching to an icon view. I only spotted this issue once and haven't come across it again since even after clearing data for the app.

![image](https://user-images.githubusercontent.com/20478546/139523925-683be6c3-3053-488b-98a6-0b57fb7a6751.png)
 This also occurred when opening file properties for the first time and persists afterwards.

### Steps To Reproduce

Launch the app and go into properties on a folder.

### Expected behavior

As above, I would expect the icons to have transparent backgrounds rather than the black observed in the screenshots.

### Files Version

2.0.13.0

### Windows Version

Windows 11 21H2 22000.258

### Relevant Assets

As in description.

**Comment by gave92** [comment]
Merging with #6373
