### ISSUE TITLE
Possible to make the row height smaller?

### ISSUE THREAD

**Issue by josdemmers** [files-community/Files#6658]
When viewing files in the Details view roughly 25 items fit on my screen.
This is at 2560x1440 with a 125% scaling.

Is there an option somewhere to modify the row height and make it smaller? Otherwise I would like to request that as a feature.

I comparison with the default windows 10 explorer which shows roughly 40 rows, I think only showing 25 rows at a time is rather limiting.

![afbeelding](https://user-images.githubusercontent.com/8627157/139532521-197e4f93-e7d8-4537-81ea-595b7ce2d34d.png)

**Comment by gave92** [comment]
Thanks for the suggestion. Currently there isn't an option for this, but we're looking into implementing a "compact" mode -> #1940.
