### ISSUE TITLE
Right click scroll

### ISSUE THREAD

**Issue by RakibRyan** [files-community/Files#6659]
### Solution/Idea

Move those to sub menu. Maybe leave the terminal  there but move there rest to submenu & increase the menu size a bit to fit more tab there. It's actually easier to just click the more button & click on submenu than to scroll
![Screenshot (52)](https://user-images.githubusercontent.com/85598032/139534190-6a3e1611-b6e3-4abf-a0f4-6196201eb67c.jpg)

### Alternatives

Maybe you can add the more button in the sub menu at the top. Or maybe you can move the more button before the other apps and make the menu big enough so that more button shows as well.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Make the menu a little big to add the more button  | Must |
| Move the apps integration to sub menu | Should |
| Change the position of the more button | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.0.13.0 OS Version: 10.0.22000.282

### Windows Version

Windows Feature Experience Pack 1000.22000.282.0

**Comment by gauravr397** [comment]
how did u get git bash and more option in right click menu ?

**Comment by RakibRyan** [comment]
> how did u get git bash and more option in right click menu ?
> 
> ![image](https://user-images.githubusercontent.com/57338455/139792404-9a95a89c-0cf3-4c6f-bded-7ac466e17551.png)

install git.

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
There isn't anything we can do about this right now but we should make the title a little clearer and approve the issue.

**Comment by yaichenbaum** [comment]
This can be resolved by turning on the option to move items to the overflow menu
![image](https://user-images.githubusercontent.com/39923744/199274262-195f1b94-9489-4ef8-aff7-dae8bcbf2d65.png)
