### ISSUE TITLE
Some apps don't have icons & some don't show up in the menu at all.

### ISSUE THREAD

**Issue by RakibRyan** [files-community/Files#6660]
### What's the Problem?

Some apps don't have icons & some don't show the menu at all.

### Solution/Idea

Some apps don't show icons.
![Screenshot (53)](https://user-images.githubusercontent.com/85598032/139534430-37d0f00a-5b6c-4d0f-a213-1b4ac0c78956.jpg)

Some don't show up in the menu.
Look at the folder marker.
![Screenshot (54)](https://user-images.githubusercontent.com/85598032/139534533-18be61c4-bd86-4346-9c36-3f9ed9e128db.jpg)
It's missing here.
![Screenshot (55)](https://user-images.githubusercontent.com/85598032/139534547-f0971498-5e82-4e32-a69d-2b6dafb9d24b.png)

### Alternatives

Fix them

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Show every menu | Must |
| Fix the missing icons | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.0.13.0 OS Version: 10.0.22000.282

### Windows Version

Windows Feature Experience Pack 1000.22000.282.0

**Comment by josh-65** [comment]
Same as #3834
