### ISSUE TITLE
File tags.

### ISSUE THREAD

**Issue by RakibRyan** [files-community/Files#6661]
### Solution/Idea

Add more option in file tags.
![Screenshot (54)](https://user-images.githubusercontent.com/85598032/139534783-51122d51-5320-458e-b2d4-28ed90c2bafd.jpg)

### Alternatives

.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Will improve productivity | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.0.13.0 OS Version: 10.0.22000.282

### Windows Version

Windows Feature Experience Pack 1000.22000.282.0

**Comment by gave92** [comment]
Thanks for the suggestion. Merging into #5848. At the moment you can add more tags/change tags name and color but editing `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState\settings\filetags.json`
