### ISSUE TITLE
New shortcuts.

### ISSUE THREAD

**Issue by RakibRyan** [files-community/Files#6662]
### Solution/Idea

add shortcuts for new file

![Screenshot (56)](https://user-images.githubusercontent.com/85598032/139536138-6816b878-1673-4667-aa76-9f304dee1f40.jpg)
### Alternatives

.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| will improve productivity | Must |

### Files Version

Version: 2.0.13.0 OS Version: 10.0.22000.282

### Windows Version

Windows Feature Experience Pack 1000.22000.282.0

**Comment by gave92** [comment]
Merging with #1671
