### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by jairmilian** [files-community/Files#6666]
### Description

BUG

### Steps To Reproduce

1. ME SALIO UN ERROR
2. Y SE CERRO EL PROGRAMA

### Expected behavior

.

### Files Version

.

### Windows Version

.

### Relevant Assets

.

**Comment by gave92** [comment]
Thanks for the report. Please add more details to help us understand the issue:
- Post the app's log files
- Add some steps to reproduce the issue
- Add app version and Windows version to the description
