### ISSUE TITLE
Context menu install option for new font files

### ISSUE THREAD

**Issue by PimTournaye** [files-community/Files#6672]
### What's the Problem?

.otf and ttf files can be mass-installed by right-clicking on such a file or files in the normal File Explorer.
Files doesn't give that option, making me go through each and every one manually

### Solution/Idea

Give an install option when right clicking

### Alternatives

Haven't considered any alternatives

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
Allow simple right click install of font files

### Files Version

Version: 2.0.13.0 OS Version: 10.0.19043.1319

### Windows Version

Edition	Windows 10 Home Version	21H1 Installed on	‎18/‎08/‎2021 OS build	19043.1319 Experience	Windows Feature Experience Pack 120.2212.3920.0

**Comment by gave92** [comment]
What is the missing option? An "Install" menu item should appear when right-clicking on multiple ttf files. Could you post a screenshot of you context menu? Also please verify whether you just need to scroll down the menu to see the option.

**Comment by PimTournaye** [comment]
Never mind me being unobservant, didn't see the scroll bar. It only showed three options before I had to scroll. Thanks either way for pointing me in the right direction.

**Comment by gave92** [comment]
@PimTournaye no problem, having to scroll the menu is not intuitive at all :) and we fixed that issue in the insider version.
