### ISSUE TITLE
Some UI elements don't update after importing settings

### ISSUE THREAD

**Issue by d2dyno1** [files-community/Files#6673]
### Description

Continuing on #6542, some UI areas aren't updated after importing settings.

### Steps To Reproduce

1. Import settings
2. See the bug

### Expected behavior

Update all UI elements or ask the user to restart the app.

### Files Version

v2

### Windows Version

Windows 11 21H2 22000.282

**Comment by yaichenbaum** [comment]
@d2dyno1 is this still an issue in the preview version? http://files.community/download/preview

**Comment by d2dyno1** [comment]
It looks like it's been fixed
