### ISSUE TITLE
Files unexpectedly closes when I do any action inside

### ISSUE THREAD

**Issue by matheus1776** [files-community/Files#6676]
### Description

I basically open the files and after opening normally, when I try to enter anything from any path it says something went wrong and just closes

### Steps To Reproduce

1. Open Files and try to enter or browse anyway by clicking on anything
2. It will close unexpectedly informing you that something went wrong

### Expected behavior

I expected it would go into normal any of the files or folders that I clicked once or twice to look and see the files

### Files Version

V2.0.31.0

### Windows Version

Windows 11 22489.1000 Pro Insider Preview 

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7449905/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7449906/debug_fulltrust.log)

**Comment by gave92** [comment]
Thanks for the report. Could you try replacing `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState\settings\filetags.json` with the following content?
```
{
  "FileTagList": [
    {
      "TagName": "Blue",
      "Uid": "3aab30c1-a9f6-4dbd-a3a8-c343b645b177",
      "ColorString": "#0072BD"
    },
    {
      "TagName": "Orange",
      "Uid": "2e1a1dda-688c-4966-a0eb-b28f2315a09f",
      "ColorString": "#D95319"
    },
    {
      "TagName": "Yellow",
      "Uid": "ebba15f5-12f4-4417-bab1-877ae182c171",
      "ColorString": "#EDB120"
    },
    {
      "TagName": "Green",
      "Uid": "5304fa1b-8153-4039-9595-c9dc66e924a1",
      "ColorString": "#77AC30"
    },
    {
      "TagName": "Azure",
      "Uid": "f3714fb0-cfe7-4f01-85c0-fbdda7abde99",
      "ColorString": "#4DBEEE"
    }
  ]
}
```
I it doesn't work please try to turn off "Enable file tags" option in Files settings Exterimental. (#6605)

**Comment by matheus1776** [comment]
Replace the entire file with what you sent me and stopped happening, now it's working normally!

**Comment by matheus1776** [comment]
Just an additional comment: when I replace the part you say and put the one you sent and saved, and open it again, it takes, but if I put the tag colors, close it and try to access it again, it does the same error, anywhere that is clickable, I went to look at the file, and when I replace and save with yours and then put the tags, close and open again, it puts it the same way it was before the replacement

**Comment by gave92** [comment]
Thanks for confirming, merging with #6605. For now you can turn off the file tags feature.

**Comment by gave92** [comment]
Edit: could you clarify what do you mean by "if I put the tag colors"?

**Comment by matheus1776** [comment]
It's just that, when I assign a tag, such as in green, to any file or folder and I don't close the files, it acts with the normal behavior, but if I close it, with the tag assigned to some file or folder and try to open it again, it crashes and closes unexpectedly like in the first situation
