### ISSUE TITLE
Open a closed tab

### ISSUE THREAD

**Issue by ZeoNish** [files-community/Files#6677]
### What's the Problem?

It is very necessary to add a new function "Open a closed tab"

### Solution/Idea

It is very necessary to add a new function "Open a closed tab"

### Alternatives

no ....

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Версия: 2.0.13.0 OS Version: 10.0.22000.258

### Windows Version

Windows 11 Pro 21H2 22000.258

### Additional comment

need ...

**Comment by gave92** [comment]
Ctrl+Shift+T should reopen closed tabs, but perhaps we can add a browser-like "history".
