### ISSUE TITLE
Opening Videos Tab in Library Section will Cause the App to Crash

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#6678]
### Description

Just noticed that when we surf into the `Videos` tab located in the `Library` (make sure to check the `Show Library Section` located in Settings), it will crashes the entire app.

### Steps To Reproduce

1. Go to Videos App from Library Section
2. See the error

### Expected behavior

Files shouldn't crash when users visits Videos section.

### Files Version

2.0.31.0

### Windows Version

Windows 11 21H1 22000.282

### Relevant Assets

Additionally I am able to reproduce this bug every time I visit the Videos tab.

[debug.log](https://github.com/files-community/Files/files/7451736/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7451737/debug_fulltrust.log)

**Comment by stanleyowen** [comment]
Hi @yair100, sorry for the late responses since lately I am quite busy lately with my school projects. It turns out that opening the Videos Tab no longer causes the app to crash. However, it pops out a dialog box with the following messages:
![image](https://user-images.githubusercontent.com/69080584/168977130-5707a4a4-d235-4aca-85af-8eadb771a1ed.png)

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?

**Comment by yaichenbaum** [comment]
I believe so

**Comment by Josh65-2201** [comment]
> Hi @yair100, sorry for the late responses since lately I am quite busy lately with my school projects. It turns out that opening the Videos Tab no longer causes the app to crash. However, it pops out a dialog box with the following messages: ![image](https://user-images.githubusercontent.com/69080584/168977130-5707a4a4-d235-4aca-85af-8eadb771a1ed.png)

Can you try right clicking the library > properties > library and checking if the paths added are still used.
