### ISSUE TITLE
FILES V2

### ISSUE THREAD

**Issue by GUIBOUT** [files-community/Files#6680]
### What's the Problem?

I would like a favorites bar as CLOVER with possiblity to put folder or file inside  (to open a word or an excel files, for exemple)
Thanks

### Solution/Idea

I would like a favorites bar as CLOVER with possiblity to put folder or file inside  (to open a word or an excel files, for exemple)
Thanks

### Alternatives

Clover but i doesn't work on windows 11

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

V2

### Windows Version

Windows 11 Professionnel 21H2 22000.282

**Comment by gave92** [comment]
To confirm, you're asking for Clover's "bookmarks menu" right?
<img src="https://user-images.githubusercontent.com/9673091/139692313-2330608c-4728-4561-9145-eacc3e920704.png" width="500"/>

**Comment by gave92** [comment]
Also #6458.

**Comment by d2dyno1** [comment]
@GUIBOUT Since we haven't heard from you, I'm closing this issue.

**Comment by sobuj53** [comment]
> To confirm, you're asking for Clover's "bookmarks menu" right?
> 
> <img alt="" width="500" src="https://user-images.githubusercontent.com/9673091/139692313-2330608c-4728-4561-9145-eacc3e920704.png">

it would have been a wonderful addition to this file manager

**Comment by GUIBOUT** [comment]
Hello,
I have since successfully installed CLOVER on Windows 11.
So I have all the tabs and bookmark functions working.
What is missing is the language (French for me), I change in the settings but I am taken into account and to put color icons
Thank you
