### ISSUE TITLE
Files 优化建议

### ISSUE THREAD

**Issue by guanmuzb** [files-community/Files#6683]
### What's the Problem?

1.和系统融合性
2.操作的便捷性

### Solution/Idea

1.1）和系统融合更强些，可以设置使用WIN + E打开，2）可以设置默认打开文件夹使用files
2.增加个双击空白处，可以返回上一层

### Alternatives

1.1）和系统融合更强些，可以设置使用WIN + E打开，2）可以设置默认打开文件夹使用files
2.增加个双击空白处，可以返回上一层

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

版本: 2.0.13.0 OS Version: 10.0.22000.258

### Windows Version

Windows 11 专业版 64-bit (10.0, Build 22000)

**Comment by yaichenbaum** [comment]
The next update will let you set Files as the default file explorer.
