### ISSUE TITLE
Files 2.0.31 crashing.

### ISSUE THREAD

**Issue by DuCanhGH** [files-community/Files#6684]
### Description

So I went to use Files this morning and it crashed. Not just once but multiple times and it always reported 'Something went wrong!' and I guess the update from MS Store went wrong and attempted to reinstall and it started working again. I thought it was going to be alright but then Files started crashing again and doing what was above. Maybe it's an issue with MS Store again or it's just my Files?

### Steps To Reproduce

1. Update to 2.0.31
2. ...just open Files I guess?

### Expected behavior

It crashes and notifies "Something went wrong! Files ran into a problem that the developers haven't prepared for yet."

### Files Version

v2.0.31

### Windows Version

Edition: Windows 11 Pro for Workstations Insider Preview
Version: Dev 
Installed on: ‎31/‎10/‎2021 
OS build: 22489.1000 
Experience: Windows Feature Experience Pack 1000.22489.1000.0

There is a chance of this version being the actual problem.

### Relevant Assets

https://drive.google.com/file/d/1ghL-GkhXjdgQgp2j6qflAa2GxoLPs7Uw/view?usp=sharing

**Comment by gave92** [comment]
Thanks for the report. Could you also upload the app's debug logs?
You can get them from `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` (debug.log + debug_fulltrust.log)

**Comment by DuCanhGH** [comment]
[debug_fulltrust.log](https://github.com/files-community/Files/files/7461896/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7461898/debug.log)
@gave92 Alright, here it is :)

**Comment by gave92** [comment]
Thanks it's the same issue as #6605. For now you'll need to delete "user_settings.json" from `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState\settings`

**Comment by DuCanhGH** [comment]
@gave92 Aight, will do, does that mean I can't use the "Open last session tabs" option for now? Thanks :)

**Comment by gave92** [comment]
You can use that, but you can't enable the "file tags" feature under experimental.

**Comment by DuCanhGH** [comment]
Ok, thanks :)

**Comment by gave92** [comment]
@DuCanhGH we're having trouble reproducing (and, so, fixing) this issue. In case, would you be willing to test a debug version of the app (same as insider version but with more logging) to help us identify the bug?

**Comment by DuCanhGH** [comment]
@gave92 uh, ok, lemme go download the code from github :)

**Comment by DuCanhGH** [comment]
[debug.log](https://github.com/files-community/Files/files/7467324/debug.log)
Right, got my hands on Files Dev 2.0.27 after a working day, and... the app didn't crash with my normal configuration :) There doesn't seem to be a debugFullTrust.log though, something might have gone wrong or this version doesn't use FilesFullTrust.exe process and stuff xD Although it works normally, I'll just send the log here in case there might be something of an use.
And hey, did you guys update the animations? They feel... a bit different from what I normally see. And I don't understand why Files Dev version is behind Insider version xD

**Comment by DuCanhGH** [comment]
[vscode.log](https://github.com/files-community/Files/files/7467353/vscode.log)
Here is what was logged in VS22's debug output. I don't actually know if it would be of an use, so here it is.
