### ISSUE TITLE
shared folders 

### ISSUE THREAD

**Issue by sbeeer** [files-community/Files#6685]
### Description

I have a windows server in my network and my mapped shared folders show up as empty with Files app.

when I access the root folder (\\devicename) it shows up some folders but the actual "shared folders" (\\mircowinserver\sharedfolders) show up as empty even when mapped as a network drive (Z:)

also network navigation is REALLY slow.

on windows file explorer it works as expected

![files shared folders issue](https://user-images.githubusercontent.com/63885997/139877381-0db6b1cc-b1f1-4c16-958b-4e9b424fbddd.png)
.

### Expected behavior

expected behavior is to correctly navigate shared folders on the network and not showing drives as empty. and they should be faster to load. as windows explorer is doing.
![files shared folders issue](https://user-images.githubusercontent.com/63885997/139877961-ac8af8c8-b5c0-46b5-a21d-62a6e596bbd9.png)

### Files Version

Version: 2.0.13.0

### Windows Version

OS Version: 10.0.22000.282

**Comment by yaichenbaum** [comment]
> Shortcuts do not appear in network folders (UWP limitation). Are all the folder contents shortcuts?

Can we use the full trust process? I seem to remember some limiation that forced us to use the UWP APIs for this.

**Comment by gave92** [comment]
FindFirstFileFromApp (uwp) was giving access denied on network paths, but I expect FindFirstFile (full trust) to work.

**Comment by sbeeer** [comment]
Yep, that's the issue, shortcut on network shares are not shown. Also loading for network shares is much slower than windows explorer.

**Comment by gave92** [comment]
Merging with #2436
