### ISSUE TITLE
Empty the recycle bin in direct access on the Recycle Bin page

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#6686]
### What's the Problem?

On the Recycle Bin page, there is no button to empty the Recycle Bin.
However, there is a New button which is never used. 

### Solution/Idea

On the Recycle Bin page, replace the button "New" by "Empty".
This button is only active if the Recycle Bin is not empty. 

### Alternatives

Also add a button to restore everything.

### Files Version

v2

### Windows Version

Windows 11

### Additional comment

I made a prototype. This functionality requires little change. 
![RecycleBin](https://user-images.githubusercontent.com/46631671/139879325-ec4446a0-7ca3-4d75-b3ac-ab2cca14aad4.png)

**Comment by cinqmilleans** [comment]
Ok, I'm doing this.

**Comment by yaichenbaum** [comment]
Let's sync with @winston-de to figure out the best way to do it as we also want to add buttons depending on the context for other files/folders such as extracting items when an archive is selected/open.

**Comment by esibruti** [comment]
@yair100 We can close this issue.
