### ISSUE TITLE
FilesFullTrust crashes when opening context menu on image files

### ISSUE THREAD

**Issue by abdonkov** [files-community/Files#6694]
### Description

FIlesFullTrust.exe crashes when opening context menu on image files.
Tested on .png and .jpg files.

### Steps To Reproduce

1. Locate an image file (.png or .jpg)
2. Right click on it to open context menu
3. FilesFullTrust.exe crashes after the additional context menu options are opened.

The context menu for the image looks like this in file explorer.
![image](https://user-images.githubusercontent.com/10236674/140181340-49f60039-9f87-4be7-bf81-2758cbb976dd.png)

### Expected behavior

Not to crash.

### Files Version

Files Insider, Version: 2.0.31.0

### Windows Version

Windows 11, Version: 10.0.22000.282

### Relevant Assets

![image](https://user-images.githubusercontent.com/10236674/140180833-20955d82-79c0-4439-a5d1-9fcae9931622.png)
I was able to see this error only once, after that on additional crashes, no exceptions where logged...

**Comment by gave92** [comment]
Thanks for the report. Could you upload the full log files?

**Comment by abdonkov** [comment]
Yes it is reproducible, happens always.
And the problem with the log files is that they don't have any exceptions.
[debug.log](https://github.com/files-community/Files/files/7470381/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7470382/debug_fulltrust.log)
Only one time I saw the exception provided in the image and then nothing...

**Comment by abdonkov** [comment]
I'm closing the issue, because it isn't crashing anymore on the latest insider build (Version: 2.0.33.0). Maybe it was fixed or just my version was bugged and the update fixed it...

**Comment by gave92** [comment]
Thanks for the info! Please let us know if it happens again.
