### ISSUE TITLE
dragging and dropping to other apps

### ISSUE THREAD

**Issue by TyJOrtiz** [files-community/Files#6697]
With the exception of File Explorer (explorer.exe), other apps can not accept drag and drop operations of files from Files window.

I tested this and the file type is shown as "Files.Filesystem.StorageItems.SystemStorageFile" type

![image](https://user-images.githubusercontent.com/25320332/140189815-7a63d256-40d2-4d6a-9fa5-1e4b43d91b31.png)

Is there any way to maybe expose this as a "StorageFile" type?

**Comment by gave92** [comment]
What app version are you testing?

**Comment by TyJOrtiz** [comment]
I'm using the latest version in the store, and the code is from an app I'm developing

**Comment by gave92** [comment]
> I'm using the latest version in the store

Could you confirm which version is that? (is it the insider version or the latest public version 2.0.13?)

**Comment by TyJOrtiz** [comment]
Versión: 2.0.13.0
OS Version: 10.0.22489.1000

**Comment by gave92** [comment]
Indeed it looks like we provide "normal" storage items on Copy/Paste but not Drag/Drop.

**Comment by gave92** [comment]
@TyJOrtiz when you mention "other apps" is it just your app or did you find others for which drag/drop from Files does not work? E.g in my testing dropping to Edge works.

**Comment by TyJOrtiz** [comment]
Dragging to Snip & Sketch doesnt work for example, I can drag images from Explorer.exe to there

**Comment by gave92** [comment]
Thanks for pointing this out!
