### ISSUE TITLE
Vertical tab flyout setting not consistent after exiting compact overlay

### ISSUE THREAD

**Issue by nahomebssa** [files-community/Files#6699]
### Description

After setting 'Display the vertical tab flyout on the title bar' to off, the button still appears after switching to compact overlay mode. Exiting out of compact overlay mode, the button is permanently in the title bar.

### Steps To Reproduce

1.  Go to Settings > Multitasking
2. Turn off "Display the vertical tab flyout on the title bar"
3. Close settings
4. Turn on compact overlay mode (Ctrl+Alt+Up)
5. Notice the vertical tab flyout button is in the title bar
6. Exit compact over mode (Ctrl+Alt+Down)
7. Notice the vertical tab flyout button is still in the title bar

### Expected behavior

After turning the setting off, the button should not appear in the title bar even after switching to compact overlay mode.

### Files Version

Version: 2.0.13.0 OS Version: 10.0.22000.282

### Windows Version

Edition	Windows 11 Home Version	21H2 Installed on	‎8/‎24/‎2021 OS build	22000.282 Experience	Windows Feature Experience Pack 1000.22000.282.0

**Comment by Josh-65** [comment]
Since vertical tabs arnt included anymore im going to close this.
