### ISSUE TITLE
Elements of sidebar contracting when entering compact view

### ISSUE THREAD

**Issue by bebauke** [files-community/Files#6702]
### Description

When resizing the window to the more compact view (sidebar hides) the elements like Favorites and Drives contract, so that after rescaling the widow back to normal size one has to expand the elements. This even happens, when entering the compact view by exident without mouse-up-event.

### Steps To Reproduce

1. expand some sidebar elements (drive/favorites)
2. resize window horizontaly till the sidebar hides
2. resize window back to previous size

### Expected behavior

the elements should allways stay the way, they were set. rather scroll the sidebar than remove user settings

### Files Version

v2.0.33.0

### Windows Version

Windows 11 22489.1000

### Relevant Assets

![files-issue](https://user-images.githubusercontent.com/45176812/140278914-318f1e9f-67db-487a-aa66-94f42938ae05.gif)

**Comment by gave92** [comment]
Thanks for the report, merging with #4128
