### ISSUE TITLE
Drag & Dropping .png images to indesign corrupts them

### ISSUE THREAD

**Issue by lvi-jonathan** [files-community/Files#6704]
### Description

Hi, 

When drag & dropping an image to InDesign from Files, it bugs out and corrupts the resulting imported image.

Screenshot : 
![image](https://user-images.githubusercontent.com/73218968/140295724-4f315408-1f7b-4da3-b093-11faa4a4b6c8.png)

The original image: 
![noun_Quote_2409407](https://user-images.githubusercontent.com/73218968/140295766-da68dff8-e593-4da2-996c-92ebafba9bb6.png)

### Steps To Reproduce

1. Go to files
2. Drag PNG to Indesign
3. Resulting dropped image is wrongly interpreted

### Expected behavior

The dragged image gets pasted in indesign

### Files Version

2.0.13

### Windows Version

Windows 11 build 22000.282

**Comment by yaichenbaum** [comment]
@lvi-jonathan is this still an issue in the preview version? https://files.community/download/preview
