### ISSUE TITLE
Context menu sizing dependent on window size

### ISSUE THREAD

**Issue by generalguy41** [files-community/Files#6705]
### Description

The right click context menu sizes based on where the bottom of the files window is.

### Steps To Reproduce

1. Right click on a file towards the top of the window.  
    - See that the context menu sizes itself fully.
3. Right click on a file towards the middle of the window.
   - See that the context menu limits itself to the size of the bottom of the window.
5. Right click on a file towards the bottom of the window.
   - See that the context menu doesn't fully resize.

Recording:

https://user-images.githubusercontent.com/8879244/140308396-0519666d-8b69-4484-ac89-96a2aeae9b6d.mp4

### Expected behavior

Context menu will size fully at all times.

### Files Version

2.0.33.0

### Windows Version

Windows 11 Pro Insider Preview v22494.1000

### Relevant Assets

You can see in the video below that while recording this to test, it actually froze before I could show the last row. I tested again after and it froze again. From what I can see, it seems to happen when trying to hover over the bottom most item in the context menu when it hits the lower limit of the window.

https://user-images.githubusercontent.com/8879244/140307855-72ec86a6-2457-4776-bb7d-5771f85a979f.mp4

Log Files:
[debug_fulltrust.log](https://github.com/files-community/Files/files/7474513/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7474514/debug.log)

**Comment by yaichenbaum** [comment]
@gave92 this was intentional for now, right?

**Comment by gave92** [comment]
It it, it's to avoid having to reposition the menu after it was opened.

**Comment by gave92** [comment]
We can get everything from uwp too, but to my knowledge there is no way to force the menu to open upward or downward. Also iirc there's another issue where the menu gets cut if it opens upward and you add more items.

**Comment by yaichenbaum** [comment]
> We can get everything from uwp too, but to my knowledge there is no way to force the menu to open upward or downward. Also iirc there's another issue where the menu gets cut if it opens upward and you add more items. And another where the menu grows out of the screen boundaries.

Isn't there a `Placement` property?

**Comment by gave92** [comment]
There is but it seems to act like a "suggestion", it does not enforce it (tbc).

**Comment by mbeps** [comment]
Showing all the context menu entries at once will make the context menu huge and fragmented like the legacy context menu currently in Windows (the one Microsoft is trying to replace). The scroll was perfect to simplify the context menu and still having the easily accessible. 
I understand that some user had problems discovering the other options, Microsoft's solution to add an entry to bring up the legacy context menu is not ideal. In my option, the best option is to give users the option to choose between the full sized context menu or the scrolling context menu. 
In the long term, having the context menu show all the options at once is not ideal. It will create the very problem that we are trying to solve as we will have a huge cluttered and unnecessary complicated context menu.

**Comment by mbeps** [comment]
Showing all the context menu entries at once will make the context menu huge and fragmented like the legacy context menu currently in Windows (the one Microsoft is trying to replace). The scroll was perfect to simplify the context menu and still having the easily accessible. 
I understand that some user had problems discovering the other options, Microsoft's solution to add an entry to bring up the legacy context menu is not ideal. In my option, the best option is to give users the option to choose between the full sized context menu or the scrolling context menu. 
In the long term, having the context menu show all the options at onces is not ideal. It will create the very problem that Microsoft is

**Comment by yaichenbaum** [comment]
> There is but it seems to act like a "suggestion", it does not enforce it (tbc).

@gave92 does it choose the correct option in most cases or is it random?

**Comment by Josh-65** [comment]
Closing since the options are now shown. The menu does still jump when shell items load.
