### ISSUE TITLE
Double click inside folder to move up to parent folder

### ISSUE THREAD

**Issue by josdemmers** [files-community/Files#6706]
### What's the Problem?

A quicker navigation method to move to a parent folder would be great.

### Solution/Idea

Double click inside a folder to be able to navigate to parent folder.
e.g. clicking at the red cross
![image](https://user-images.githubusercontent.com/8627157/140316823-c3f4a00b-1c50-4fd1-bd97-1a56ee97261c.png)

### Alternatives

When using a keyboard the backspace key already works but would be useful if you can just double click / tab with your mouse / finger to move to the parent folder.

### Files Version

Version: 2.0.33.0

### Windows Version

OS Version: 10.0.19042.1165

**Comment by yaichenbaum** [comment]
Merging with #2355.

**Comment by josdemmers** [comment]
Thanks for the merge. Did a search in the current issues, but did not find that one.

**Comment by yaichenbaum** [comment]
> Thanks for the merge. Did a search in the current issues, but did not find that one.

No worries! It's sometimes a little hard to find issues on GitHub.
