### ISSUE TITLE
Still not showing the Status column on OneDrive folders and Files in many places

### ISSUE THREAD

**Issue by brucebinder** [files-community/Files#6708]
### Description

I depend on being able to see the status column for OneDrive files and folders. They appear inn some places and not others.

### Expected behavior

The status coluymn to appear everywhere, especially on OneDrive files and folders.

### Files Version

Version: 2.0.33.0 OS Version: 10.0.22000.282

### Windows Version

21H2 (Build 22000.282

**Comment by gave92** [comment]
#7144
