### ISSUE TITLE
Restore from Recycle Bin loses filetype

### ISSUE THREAD

**Issue by infuriatedcodex** [files-community/Files#6709]
### Description

When attempting to restore a file from the recycle bin, the recovered file loses its extension and is simply listed as "File". Therefore you may not be able to tell what the application association is, especially if the file was downloaded or emailed to you.

### Steps To Reproduce

1. Navigate/Create a temp folder such C:\Temp.
2. Create a new file such as MS Word Rich Text Format, i.e. "Delete Test.rtf"
3. Place a string inside "Hello World" or similar.
4. Delete the file so it goes to the bin.
5. Restore the file and notice how the file is restored only as "Delete Test" without the file extension.

### Expected behavior

Restore as normal File Explorer would be full filename intact.

### Files Version

Version: 2.0.33.0

### Windows Version

Windows 11 21H2 10.0.22000.282

**Comment by IgnusG** [comment]
Can confirm. Tried with zip files and they just become blank files until I re-add the extension manually

**Comment by d2dyno1** [comment]
Does this occur on 2.0.34.0? @infuriatedcodex

**Comment by d2dyno1** [comment]
@infuriatedcodex do you have enabled "Show file extensions" in both Files and File Explorer?

**Comment by d2dyno1** [comment]
@infuriatedcodex @IgnusG You can enable "Show file extensions" in File Explorer as a temporary fix.

**Comment by infuriatedcodex** [comment]
HI @d2dyno1 ,

confirmed, this temporarily resolves the problem.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #6985.
