### ISSUE TITLE
Crash when opening User's Files folder from desktop with Files as default explorer 

### ISSUE THREAD

**Issue by Crwmy** [files-community/Files#6712]
### Description

Files crashes when I try to open my user's files folder via the desktop icon. Other folders on desktop to not provoke the crash.

### Steps To Reproduce

1. Have User's Files enabled to be shown on desktop
2. Make Files 2.0,33 default file explorer
3. Open User's Files from desktop
4. Files will start open the user's files folder and load it's UI, then crash when the left sidebar is loaded

### Expected behavior

no crash

### Files Version

v 2.0.33 (Microsoft Store version)

### Windows Version

22000.282

**Comment by gave92** [comment]
Thanks for the report. Please upload the app's debug logs.

**Comment by Crwmy** [comment]
@gave92: Done
[Files_6712_logs_crwmy.zip](https://github.com/files-community/Files/files/7477823/Files_6712_logs_crwmy.zip)

**Comment by yaichenbaum** [comment]
@Crwmy thank you.

**Comment by Crwmy** [comment]
Issue seems resolved since version 2.1. 
Thanks!
