### ISSUE TITLE
double click on any blank part of the window to go up one level or go back to the previous folder

### ISSUE THREAD

**Issue by lfelipe1501** [files-community/Files#6713]
### What's the Problem?

Is not a problem, only a suggestion 👍🏻 [Demonstrative Video](https://drive.google.com/file/d/17EkSo8IUhI5IKd3pjeEtUSSzsOf11QBf/view?usp=sharing)

### Solution/Idea

double click on any blank part of the window to go up one level or go back to the previous folder
like qtabbar

[Demonstrative Video](https://drive.google.com/file/d/17EkSo8IUhI5IKd3pjeEtUSSzsOf11QBf/view?usp=sharing)

### Alternatives

Qttabbar
have this integration with the default explorer of windows 11
It would be great if this project included this within the browser, it is very helpful and works very well.

[Demonstrative Video](https://drive.google.com/file/d/17EkSo8IUhI5IKd3pjeEtUSSzsOf11QBf/view?usp=sharing)

### Files Version

v2.0.33.0

### Windows Version

Windows 11

### Additional comment

is a good idea
double click on any blank part of the window to go up one level or go back to the previous folder like qtabbar
[Demonstrative Video](https://drive.google.com/file/d/17EkSo8IUhI5IKd3pjeEtUSSzsOf11QBf/view?usp=sharing)

**Comment by gave92** [comment]
Thanks fot the suggestion, merging with #2355
