### ISSUE TITLE
"Pin to Start11" doesn't work when Start11 is installed

### ISSUE THREAD

**Issue by Keith94** [files-community/Files#6714]
### Description

"Pin to Start11" doesn't pin anything in conjunction with Start11 being installed

### Steps To Reproduce

1. Install free trial/full version of Start11 v1.0 https://www.stardock.com/products/start11/
2. Open Start11 settings and select Windows 11 style
3. Right click application's .exe in Files
4. Click on "Pin to Start11" 

### Expected behavior

App gets added to pinned section. However, nothing gets pinned. Default File Explorer works as expected

### Files Version

2.0.33

### Windows Version

Windows 10 21H1 19043.1320

**Comment by yaichenbaum** [comment]
Can you report this issue to Start11?
