### ISSUE TITLE
Can't install Themes for Files - Select Retry to close and update the app

### ISSUE THREAD

**Issue by TheInvoker** [files-community/Files#6715]
### Description

I have the Files app installed, and now I want to get the [Themes for Files](https://www.microsoft.com/en-ca/p/themes-for-files/9n20kq61lsfq#activetab=pivot:overviewtab). However when I try to install it I get an error shown here:

[Image](https://i.imgur.com/daXrvM1.png)

It says to click retry, but there is no retry button.

### Steps To Reproduce

1. Install Files
2. Install Themes for Files

### Expected behavior

Installing the theme should just work

### Files Version

Version: 2.0.33.0 OS Version: 10.0.22000.282

### Windows Version

11 Home Version 10.0.22000 Build 22000

**Comment by yaichenbaum** [comment]
@TheInvoker this seems like an issue with the Microsoft Store, can you report it in the feedback hub?

**Comment by TheInvoker** [comment]
Where is the feedback hub?

**Comment by yaichenbaum** [comment]
The easiest way to open it is with the `win` + `f` shortcut.
