### ISSUE TITLE
Layout as a default

### ISSUE THREAD

**Issue by evyax** [files-community/Files#6717]
### What's the Problem?

When choosing a layout (Column in my case, waited for so long for someone to bring this layout to windows, thank you!)
it is not being applied overall as the default. 

### Solution/Idea

Choose in the settings which layout would you want as a default

### Alternatives

go through each drive an apply it manually. 

### Files Version

Version: 2.0.33.0 OS Version: 10.0.22000.282

### Windows Version

Windows 11 Pro  21H2  OS build	22000.282

### Additional comment

Edition	Windows 11 Pro
Version	 
Installed on	‎10/‎22/‎2021
OS build	22000.282
Experience	Windows Feature Experience Pack 1000.22000.282.0

**Comment by yaichenbaum** [comment]
Merging with #4155.
