### ISSUE TITLE
unexpected closure

### ISSUE THREAD

**Issue by MortalMaster343** [files-community/Files#6718]
### Description

when I enter the video library the program closes

### Steps To Reproduce

file explorer
video library 
see the error

### Expected behavior

see the video library

### Files Version

Versión: 2.0.33.0 OS Version: 10.0.19043.1237

### Windows Version

Edición	Windows 10 Pro Versión	21H1 Compilación del SO	19043.1237 Experiencia	Windows Feature Experience Pack 120.2212.3530.0

**Comment by gave92** [comment]
Thanks for the report. Could you upload the app's log files?
