### ISSUE TITLE
preview panel is too small

### ISSUE THREAD

**Issue by bnbagiz** [files-community/Files#6719]
### Description

the preview panel is still waaaay too small to read anything, completely senseless in my opinion

### Steps To Reproduce

1. open preview panel
2. select a pdf
3. try to read anything
4. getting disappointed
5. switching back to win explorer

### Expected behavior

resizeable preview panel

### Files Version

Version: 2.0.33.0

### Windows Version

OS Version: 10.0.19043.1288

**Comment by gave92** [comment]
Merging with #6628
