### ISSUE TITLE
Can not Copy exist file and Paste it with the new name file in the same folder

### ISSUE THREAD

**Issue by cobaohieu** [files-community/Files#6720]
I have a file like an exercise.cpp in the Exercise folder. I need to create a new file based on the exercise.cpp file in the same folder "Exercise", so I try to copy and paste it. However, it's not working like Explorer.exe.
Please take time and fix it.
Thanks so much for the great application.

**Comment by d2dyno1** [comment]
@cobaohieu Files already has a conflict resolve dialog where you can specify what to do when a file with the same name already exists.
![image](https://user-images.githubusercontent.com/53011783/141527224-e18181ad-e70d-4f52-baf8-ef5eb8976251.png)

Could you provide more info about the issue you're facing?
