### ISSUE TITLE
Folder with lots of files grouped by date isn't scrolling all the way up when loaded

### ISSUE THREAD

**Issue by 1nikolas** [files-community/Files#6722]
### Description

I've set my downloads folder to group by date created. When I open that folder (either from the sidebar panel or from the drive itslef), it scrolls on top while it's still loading so by the time it finishes loading it's not scrolled all the way up anymore.

### Steps To Reproduce

Open folder with lots of files grouped by date

### Expected behavior

Be scrolled on top after loading is finished

### Files Version

2.0.33.0

### Windows Version

Windows 11 22000.282

### Relevant Assets

https://user-images.githubusercontent.com/30593419/140498743-5b2fc9db-12ff-4e0e-9372-f1eef957e4ca.mp4

**Comment by gave92** [comment]
Thanks for the report. Merging with  #6186.
