### ISSUE TITLE
Feature: Show folder details when no item is selected

### ISSUE THREAD

**Issue by pavangayakwad** [files-community/Files#6724]
### What's the Problem?

Preview pane does not show the root level information when no folder is selected.

![image](https://user-images.githubusercontent.com/1834890/140503876-5321b45e-ba33-46e0-8a81-69c0d8bf969e.png)

### Solution/Idea

Like with folders and files, it would be great if we get to see the information of the active directory.

![image](https://user-images.githubusercontent.com/1834890/140504023-8500fc06-594e-45a0-b699-68db501bc10c.png)

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by QuaintMako** [comment]
I am going to look into this.

**Comment by yaira2** [comment]
This feature will be included in one of our next releases.
