### ISSUE TITLE
New tabs not showing icon and title

### ISSUE THREAD

**Issue by LazieWouters** [files-community/Files#6725]
### Description

![image](https://user-images.githubusercontent.com/77227512/140505242-eb51782f-693f-4422-b45e-b8c4b56d77e4.png)

### Expected behavior

New tabs should show the icon and title of the folder

### Files Version

2.0.33.0

### Windows Version

OS Version: 10.0.22478.1000

**Comment by gave92** [comment]
Closing as Windows issue. It should be fixed in the latest build.

**Comment by LazieWouters** [comment]
Thanks, I will update my OS
