### ISSUE TITLE
Tabs on the left side

### ISSUE THREAD

**Issue by LazieWouters** [files-community/Files#6726]
### What's the Problem?

Please see the image below:

### Solution/Idea

Add a feature to show tabs in the left side like the new Edge browser does

![image](https://user-images.githubusercontent.com/77227512/140505576-a2617640-2ec6-4e1c-bc00-44c7bdbf83a1.png)

### Alternatives

-

### Files Version

2.0.33.0

### Windows Version

OS Version: 10.0.22478.1000

**Comment by yaichenbaum** [comment]
We don't have plans to implement this feature, although it's not the same thing, we do recommend checking out the vertical tab flyout.
