### ISSUE TITLE
There's no title and icon when creating a new tab and The side menus is not opening after closing and opening it again.

### ISSUE THREAD

**Issue by Lainasan** [files-community/Files#6727]
### Description

Hello, I would like to report a bug about the tabs. Because when I try creating a new tab there's no icon and title even restarting my device, signing out, and force close the app.

And the side menu or the dropdown on the left side is not opening  after opening the files app.

### Expected behavior

Create a new tab with icon and names
When opening the Files app the side menus (dropdown) should be open too.

### Files Version

v2.0.33.0

### Windows Version

Windows 11 Dev 22483.1011

**Comment by gave92** [comment]
Closing as Windows issue. It should be fixed in the latest build (22494).
