### ISSUE TITLE
Bug: Files opened from explorer instance loses startup preference

### ISSUE THREAD

**Issue by Talisman39ar** [files-community/Files#6728]
### Description

I've used the Experimental feature to set Files as my default explorer, and when I click on the Files icon in the taskbar it opens to my specified folder right away (Documents in OneDrive in my case).

However, if I use the Win-E shortcut or anything that would normally open File Explorer, Files will open but it goes to the default home view instead.

### Steps To Reproduce

1. Type Win-E
2. Files opens, but opens in Home View rather than folder that user has set in preferences

### Requirements

- Always use correct start preference 

### Files Version

2.0.33.0

### Windows Version

Win 11 22000.282

**Comment by Josh-65** [comment]
Is this an issue in the preview version? https://files.community/download/preview
