### ISSUE TITLE
Can't remove FILES as the default file manager after enabling it

### ISSUE THREAD

**Issue by goalie000** [files-community/Files#6729]
### Description

I installed FILES yesterday and tried the experimental option to make it my default file manager.  I use Box a lot and I can open the base Box folder but it just keeps refreshing over and over again and all of the subfolders are empty.  

I said "fine, that's that I guess" and I uninstalled FILES but it broke Windows File Explorer since the OS still thinks FILES is the default.  I reinstalled FILES and tried to turn off the Default option but it doesn't do anything.  

So, now i have an OS without a file explorer that works.

### Expected behavior

I would have expected that the default file manger would have reverted when I uninstalled.

### Files Version

Version: 2.0.33.0 OS Version: 10.0.22000.282

### Windows Version

windows 11 home 21h2 22000.282

**Comment by gave92** [comment]
> I would have expected that the default file manger would have reverted when I uninstalled.

Unfortunately that is simply not possible (UWP apps don't have "uninstallers"), and it's one of the main reason that feature is marked as "Experimental".
To unset Files you'll need to run the "UnsetFilesAsDefaut.reg" from [this archive](https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip).
We'll see if it's at least possible to make "unset" works after a reinstall, or at least add some warning/reminder when enabling that setting.

For Box merging with #6409.

**Comment by gave92** [comment]
@yair100 proposal: add a warning in the Settings page to unset Files as default before uninstalling. Not that anybody will remember it, but at least it's there ;) Also we should check if it's possible to make "unset" work after reinstall.

**Comment by goalie000** [comment]
Thanks for the quick response - - the reg file fixed the default issue.  Any thoughts on why Box folders just continually refreshed at the root and the subfolders never showed their contents?

**Comment by yair100** [comment]
> @yair100 proposal: add a warning in the Settings page to unset Files as default before uninstalling. Not that anybody will remember it, but at least it's there ;) Also we should check if it's possible to make "unset" work after reinstall.

@gave92 Can you remind me to do this in a couple days?

**Comment by gave92** [comment]
Lol unsetting after reinstall does not work because we don't copy the reg file to the appdata folder.

**Comment by koddajr** [comment]
can we have a directy download link to this .reg on tooltip on experimental (if possible), will be more easy to undo instead searching on google for example or asking here on how to.

**Comment by yaichenbaum** [comment]
> can we have a directy download link to this .reg on tooltip on experimental (if possible), will be more easy to undo instead searching on google for example or asking here on how to.
> 
> @gave92

@koddajr we are working on improving the option, adding workarounds to an experimental feature that we don't support at this time would just slow us down from working on actual improvements.
