### ISSUE TITLE
Allow dragging files and folders without selecting them first

### ISSUE THREAD

**Issue by XeZrunner** [files-community/Files#673]
**Is your feature request related to a problem? Please describe.**
I wouldn't say it's a problem, so I report it as a feature request. Some may consider this annoying or a bug.

**Describe the solution you'd like**
When clicking and holding (or tapping and holding) without selecting the file first, the application should highlight and initiate the drag & drop mechanism.

**Describe alternatives you've considered**
This behavior could be a preference option in the Settings.
Perhaps the highlighting isn't necessary, but Windows normally handles drag & drop this way.

**Additional context**
None.

**Comment by yaichenbaum** [comment]
@XeZrunner Good feedback! This would make drag and drop more user friendly.

**Comment by xPoppyx** [comment]
I want to add something, if you select a folder or file and deselect it, you can't open it

**Comment by yaichenbaum** [comment]
@xPoppyx That sounds more like a bug, can you open a separate issue for it?

**Comment by yaichenbaum** [comment]
@XeZrunner This issue should be resolved with #4626.
