### ISSUE TITLE
Drag tabs off and on window.

### ISSUE THREAD

**Issue by DipsoNOR** [files-community/Files#6730]
### What's the Problem?

I would love to be able to move tabs in and out of windows similar to how tabs work in for instance firefox.
https://user-images.githubusercontent.com/30586730/140527306-0c19cb99-6be1-454d-9272-4ec8c8369fae.mp4

### Solution/Idea

- Make it possible to drag tab out into its own window. (Create new window when tab i dragged out of existing window)
- Make it possible to drag tabs between different windows.

### Alternatives

Looking for other tabbed interface file explorers.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to drag tab out into its own window. (Create new window when tab i dragged out of existing window)| Must|
| This proposal will allow end users to Make it possible to drag tabs between different windows.| Must|

### Files Version

Version: 2.0.33.0 OS Version: 10.0.22000.282

### Windows Version

Windows 11 21H2 22000.282

**Comment by gave92** [comment]
You should be able to do that already. Are you experiencing issues?

**Comment by DipsoNOR** [comment]
I've done some more testing and these are my finds:

If i drag the tab off with only two tabs open, the tab i draged off opens a new window, but the old one dissapears.
With tree tabs open i managed to make it work as intended, but dragging the next tab off caused a crash ("something happened that the developers had not intended" -error)

Dragging tabs between two open windows seems to work, but is a bit fiddly to make it work. IMO i should not have to drag it to the tab bar. It should be enough to drop it on the window. (If i drag a tab from one Files window to another, its pretty obvious what i want to happen)

**Comment by jac0b-w** [comment]
It would also be really nice if the new window was created as soon as it was dragged off the title bar instead of when the mouse is released or at least for the new window to be spawned at the position where the mouse is released.

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
