### ISSUE TITLE
Cant install fonts for all users

### ISSUE THREAD

**Issue by koddajr** [files-community/Files#6731]
### Description

When i try to install fonts for all users with right click button on all fonts gives me a error

"The kernel version information provided is invalid."
![image](https://user-images.githubusercontent.com/53986027/140511986-3b0c21f2-c84d-4e95-a01f-5594de58e342.png)

Font Pack that i've tried install: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/CascadiaCode.zip?WT.mc_id=-blog-scottha

### Steps To Reproduce

1. Select multiple fonts
2. Right click > More > Install for all users
3. See the error

### Expected behavior

Work without error

### Files Version

Versão: 2.0.33.0 OS Version: 10.0.22000.282

### Windows Version

Windows 11 22000.282

**Comment by gave92** [comment]
Merging with #7053
