### ISSUE TITLE
Option for "Acryllic" look on windows11 to be limited to top bar (like explorer.exe)

### ISSUE THREAD

**Issue by DipsoNOR** [files-community/Files#6732]
### What's the Problem?

In File the accryllic effect is on the whole window, while the default file explorer in windows 11 only has this effect on the top bar, not the main window components.

I think both from a performance perspective (possibly?) and aestetics, that users should have an option to have the accryllic apply to only the top bar or the whole window.

### Solution/Idea

Make options for acryllic effect:

- Off
- On (Full window)
- On (Top bar only)

### Alternatives

None.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to choose the look of their UI (And possibly performance) | Should |
| This proposal will allow developers to reduce resources used by app window | Could |

### Files Version

Version: 2.0.33.0 OS Version: 10.0.22000.282

### Windows Version

Windows 11 Pro 21H2 22000.282

**Comment by yaichenbaum** [comment]
We don't have plans to build this into Files but you can accomplish this with a custom theme https://files.community/docs/configuring/custom-themes.
