### ISSUE TITLE
Add support for previewing office documents 

### ISSUE THREAD

**Issue by HughDeLong** [files-community/Files#6733]
### What's the Problem?

File Explorer preview shows the actual document, here I just see a synopsis of author, date, etc...  and not the actual documents as in File Explorer.  Looking forward to having this included.

### Solution/Idea

Have the preview mode show the actual document - particularly Word docx, PDFs, and PowerPoints 

### Alternatives

none except continue to use FileExplorer

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.0.33.0 OS Version: 10.0.19042.1288

### Windows Version

Windows 10

### Additional comment

none

**Comment by yaichenbaum** [comment]
Merging with #4041
