### ISSUE TITLE
Suspend app process after X minutes without use

### ISSUE THREAD

**Issue by LazieWouters** [files-community/Files#6734]
### What's the Problem?

The app process is suspended when the app is minimized, but it also could be suspended when not minimized after 5 minutes without use (or any value set by user)

### Solution/Idea

Add a featute to suspend the app process after X minutes without use even when the app is not minimized

### Alternatives

-

### Files Version

2.0.33.0

### Windows Version

OS Version: 10.0.22478.1000

**Comment by gave92** [comment]
Closing this as apps can't suspend themselves. The app will be suspended by the system when minimized and maybe when it enters a low power state.
