### ISSUE TITLE
Show name of currently selected tab in preview pane on taskbar

### ISSUE THREAD

**Issue by DipsoNOR** [files-community/Files#6735]
### What's the Problem?

Currently the names of the windows are "Files", making it difficult to choose the right window when i have more than one open.

### Solution/Idea

Change window title to the same as the currently active tab on the window.

### Alternatives

none.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish parity with other similar apps | Should|
| This proposal will allow end users to more easily identify what window to click on when choosing between multiple open windows in the preview pane | Must|

### Files Version

Version: 2.0.33.0 OS Version: 10.0.22000.282

### Windows Version
![previewpane](https://user-images.githubusercontent.com/30586730/140526337-8781da9c-2b87-42ee-bc3a-113766468c49.jpg)

Windows 11 Pro 21H2 22000.282

**Comment by yaichenbaum** [comment]
Merging with #6214
