### ISSUE TITLE
Navigation with keyboard

### ISSUE THREAD

**Issue by ariana2011** [files-community/Files#6736]
### What's the Problem?

I wish we could have better navigation with the keyboard. When you enter a folder with the enter button, you cannot navigate/select other folders in the subdirectory with arrow keys. Sometimes it works sometimes it does not. Also going back with ALT + arrow_keys is a hit and miss.

### Solution/Idea

To adopt how it works on the Windows file explorer.

### Alternatives

Also, the behavior of Finder in the Mac OS can be a good option for navigation with the keyboard.

### Files Version

2.033

### Windows Version

Windows 11 22.000282

**Comment by yaichenbaum** [comment]
@gave92 do you know if the arrow key shortcuts are handled in the xaml or in the codebehind? I've seen issues like this when the shortcuts were handled in the xaml instead of the codebehind of the mainpage.

**Comment by gave92** [comment]
I think it depends on which element is currently focused, e.g. a List view may steal the Alt based shortcuts.

**Comment by harsharora08** [comment]
I was going to raise a similar issue. Glad I checked first before raising a new one.
Is this going to be implemented in near future? I have recently switched from stock file explorer to Files, and I would love if the application were to be more keyboard accessible.

**Comment by oomek** [comment]
The currently focused element is random when using a keyboard for navigation. Sometimes it's as it supposed to be a first file/folder, but often it's a Name tab. A bit annoying.

**Comment by oomek** [comment]
Also PageUp button doesn't always scroll the list to the very top, Home button does.

**Comment by diiigle** [comment]
For me it (with *detail* layout) it keeps focusing on the header of the 'table' and I have to press TAB every time.

**Comment by drkn** [comment]
Same here - focus goes to the header all time time.
