### ISSUE TITLE
Clicking restore to default repeatedly crashes files

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#6737]
### Description

Click on the Restore to Default button in the customize icon UI will crash files.

### Steps To Reproduce
https://user-images.githubusercontent.com/17484252/140539999-90ab8bfc-ccae-4cd3-b517-5194eb19c149.mp4

### Expected behavior

It should not crash.

### Files Version

Version: 2.0.33

### Windows Version

Win 10 latest

### Relevant Assets

[debug_fulltrust.log](https://github.com/files-community/Files/files/7487297/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7487298/debug.log)

**Comment by yaichenbaum** [comment]
@duke7553

**Comment by d2dyno1** [comment]
This has been closed by #7891 @R3voA3
