### ISSUE TITLE
drive won't show and close app problem

### ISSUE THREAD

**Issue by MrPatate87** [files-community/Files#6738]
### Description

After a quick test of files, when i try to change settings files app close, moreother after some hours in sleep mode on my laptop, files will not show my drives on the first panel.

### Steps To Reproduce

go to setting, preference, here the app auto kill and crash
when i open files, ly drives won't show

### Expected behavior

just want to change some settings, and see my drives

### Files Version

Version : 2.0.33.0 OS Version: 10.0.19042.1320

### Windows Version

Windows 10 20H2

**Comment by gave92** [comment]
Thanks for the report. Could you upload the app's log files?

**Comment by MrPatate87** [comment]
I not have it anymore cause i uninstall the app.....
Just try to reinstall and reproduce the error but for now work fine (the app need many time to access l'an folder and folder with many content)

**Comment by MrPatate87** [comment]
just try some more time the app and have the same problem than before, don't know where to find log files from now but if you point me I can upload it to have some help.

**Comment by gave92** [comment]
You can get them from %localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState (debug.log + debug_fulltrust.log)
