### ISSUE TITLE
File created when changing sorting settings of folder

### ISSUE THREAD

**Issue by krystofkrticka** [files-community/Files#6739]
Why does Files create hidden file when changing sorting settings of folder, older version was also able to change sorting settings for each folder but to remember them it didn't need to create file in that folder. This is very annoying when you have enabled show hidden files in Windows Explorer.

Files version: 2.0.33
OS version: Windows 10 21H1 19043.1320

**Comment by gave92** [comment]
Ouch yes it now create a file similar in concept to the explorer "desktop.ini". Was a change not meant to go public. Thanks for reporting this.

**Comment by gave92** [comment]
Change introduced in #6648
