### ISSUE TITLE
Background running requirement

### ISSUE THREAD

**Issue by MrTox** [files-community/Files#6740]
### Solution/Idea

Hello, thank you for your amazing job.  The start up time of this "files" app is a little bit long, and it will cost me a lot of time when I open and close the app frequently. So, I will be really appreciate if you can add background running feature in this app. It could save me a lot of time.

### Alternatives

I will be really appreciate if you can add background running feature in this app. It could save me a lot of time.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

V2.0.33.0

### Windows Version

Windows 11

**Comment by gave92** [comment]
Thanks for the kind feedback. Unfortunately background / system tray execution is not available for UWP apps. We're actively looking to make Prelaunch work for Files and keep improving the app's startup time.
