### ISSUE TITLE
File size in preview pane for images

### ISSUE THREAD

**Issue by angellucruz16** [files-community/Files#6743]
### What's the Problem?

Hi! When I select an image, i have to click on "properties" to see the file size
![image](https://user-images.githubusercontent.com/70734046/140574812-d7387426-b6b7-4fc4-a4af-e05dc257ac0a.png)
![image](https://user-images.githubusercontent.com/70734046/140574907-1428dc00-74bd-43e7-9ad9-305d59f6fa3f.png)

### Solution/Idea

I would like this information to be easier and faster access. Just by clicking the img

### Alternatives

I would like if the file size is in the preview seciton:
![image](https://user-images.githubusercontent.com/70734046/140576506-f4b006f4-9847-46a8-839c-5c4dbec6c4ef.png)

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to quickly see if an image is too heavy to implement in their code.| Must |
| This proposal will allow designer users to speed up their work time | Must|

### Files Version

2.0.13.0 

### Windows Version

Windows 10 Pro Versión	21H1

### Additional comment

Thank you so much!

**Comment by gave92** [comment]
\+ @winston-de

**Comment by winston-de** [comment]
Currently file size isnt shown because its already shown in the status ba. Wouldnt do any harm to show it in the preview pane as well, though.

**Comment by mistic100** [comment]
@winston-de Unless I missed something, the filesize is not visible in the status bar anymore ?

Version : 2.1.15.0
OS Version: 10.0.19043.1526

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval. The status bar issue should be fixed.

**Comment by yaichenbaum** [comment]
Should be done together with #6128
