### ISSUE TITLE
Add "send to compressed folder" option to context menu

### ISSUE THREAD

**Issue by taylorphoto** [files-community/Files#6744]
### Description

Hi .

I used the experimental set files as default. When i try to turn it off it does not.
I see that it tries to edit the registry and i give it permission but no luck. 

I wanted to go back the the windows explorer because i see no way to create zip files with this app. when i right click zip is not an option.

### Expected behavior

set files  as default file explorer toggle not working

### Files Version

Version: 2.0.34.0 OS Version: 10.0.19043.1320

### Windows Version

Version: 2.0.34.0 OS Version: 10.0.19043.1320

**Comment by gave92** [comment]
Thanks for the report. To unset Files you'll need to run the "UnsetFilesAsDefaut.reg" from [this archive](https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip).

**Comment by gave92** [comment]
You _can_ create new zip files but the process for now it's not optimal: you create an empty zip file from the "new" menu and then add the elements you wish by drag & dropping on the zip file or by copy paste.

**Comment by taylorphoto** [comment]
Thanks That worked.

Michael Taylor
Taylor Photography
10 Annis Rd.
Toronto, Ontario
M1M 2Y7 
Ph. 416 915 6466
Fax 416 928 1292
www.michaeltaylor.photography
***@***.***
 
This message and any attachments are intended only for the addressee(s) and may contain privileged or confidential information. Any unauthorized disclosure is strictly prohibited. If you have received this message in error, please notify us immediately so that we may correct our internal records. Please then permanently delete the original message and any attachments and destroy any copies. Thank you.

**Comment by Josh-65** [comment]
Merging with #9947
