### ISSUE TITLE
Merge two folder

### ISSUE THREAD

**Issue by xmha97** [files-community/Files#6745]
### Solution/Idea

Please add a new item.
I want to merge two folders.
I don't want to replace a folder with a folder.
![image](https://user-images.githubusercontent.com/23485114/140585672-265668ae-f747-4864-8cd1-493707e60a71.png)

### Alternatives

# Windows 7
![image](https://user-images.githubusercontent.com/23485114/140586047-8161b2b3-e60b-4479-83eb-5142bbc51366.png)
# Windows XP
![image](https://user-images.githubusercontent.com/23485114/140586059-abd3eda3-fc15-4a1c-a1c7-0026c26b65ba.png)

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

v2.0.33.0

### Windows Version

Windows 11 21H2 22000.282

**Comment by gave92** [comment]
"Replace existing" will actually merge the folders _but overwrite files with the same name_, true merge is missing

**Comment by yaichenbaum** [comment]
> Thanks for the report. "Replace existing" will actually merge the folders _but overwrite files with the same name_, true merge is missing. I thought we had an issue open for this but I can't find it.

@gave92 #6024
