### ISSUE TITLE
Sorting capillities missing

### ISSUE THREAD

**Issue by BertrandLan** [files-community/Files#6747]
### What's the Problem?

The sorting menu, and the details columns misses the option to sort by other ways than date, size and name... 
We miss the possibilities to sort by length, width resolution and many other...

### Solution/Idea

Like on the original explorer, adding the option "other" in the sorting options, and let you add new sorting parameters

### Alternatives

Use the original Explorer way to sort files...

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.0.33.0

### Windows Version

Windows 11 Professionnel Version	21H2 22000.282

**Comment by gave92** [comment]
Thanks for the suggestion. Merging with #3927.
