### ISSUE TITLE
Add Support for PowerToys Power Rename in the Context Menu

### ISSUE THREAD

**Issue by Arihant25** [files-community/Files#6748]
### What's the Problem?

Microsoft PowerToys has a feature called Power Rename which allows bulk renaming of files. It can't be accessed from Files, but it can be accessed from File Explorer's context menu.

### Solution/Idea

The option for that should be included in the right click context menu, just like 7-Zip.

### Alternatives

Otherwise, we could implement the entire extended context menu from the default File Explorer, to be shown as an extra option in the Files context menu.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to add Power Rename as an option in Files | Must |
| This proposal will allow developers to implement the entire extended context menu from File Explorer | Could |

### Files Version

v2.0.34.0

### Windows Version

Windows 11 21H2 (Build 22000.282)

**Comment by yaichenbaum** [comment]
This is already implemented, can you confirm that you turned on the option in PowerToys?

**Comment by Arihant25** [comment]
Yeah, I found it under More Options, my bad.
But it would be nice to have an option to keep frequently used options in the main context menu instead of a submenu.
