### ISSUE TITLE
Every Taskbar item is called Files!

### ISSUE THREAD

**Issue by dbareis** [files-community/Files#6749]
If the program was limited to a single instance then it wouldn't matter but as it is it's unusable (or at least I won't be using it).

I looked for an option for this but didn't see one.

Other than the fact that it doesn't support existing Quick Access links it seems pretty good in the short amount of time I've looked at it.

![Every Taskbar Item Called Files](https://user-images.githubusercontent.com/295230/140599763-763cf184-fd91-45a6-96fc-32b25bf82483.png)

**Comment by yaichenbaum** [comment]
Merging with #6214.
