### ISSUE TITLE
Wrong OneDrive storage capacity

### ISSUE THREAD

**Issue by Heiinz** [files-community/Files#6751]
### Description

Files shows under Cloud Storage > OneDrive > Properties a capacity of 200 GByte.
My Windows OneDrive App or the OneDrive web page show a capacity of 1 TByte.

### Steps To Reproduce

Files: Cloud Storage > OneDrive > Properties 

### Expected behavior

The right OneDrive Storage capacity is 1 TByte.

### Files Version

Version: 2.0.34.0 

### Windows Version

OS Version: 10.0.19043.1320

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?
