### ISSUE TITLE
Flies crashes when trying to open user's folders and videos folder

### ISSUE THREAD

**Issue by BANGKOKTAGANROG** [files-community/Files#6752]
### Description

app lags then crashes when opening my user's folder in Files

### Steps To Reproduce

1. Open Files
2. Go to Home -> C:// -> Users -> [your windows username]
3. See the crash

### Expected behavior

loading folder and not crashing

### Files Version

2.0.34.0 (Microsoft Store)

### Windows Version

Windows 11 21H2 22000.282

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7490171/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7490172/debug_fulltrust.log)
[video demonstrating the issue](https://imgur.com/lVK1RWp)

**Comment by NOOB1KXGOD** [comment]
UPD: app doesn't crash if trying to access through any subfolders, but crashes if attempt to access any other folder is made:
[video](https://imgur.com/Tbv1ipm)

**Comment by yaichenbaum** [comment]
@BANGKOKTAGANROG is this still an issue in the preview version? http://files.community/download/preview
