### ISSUE TITLE
Feature of moving columns as user's wish

### ISSUE THREAD

**Issue by lsylusiyao** [files-community/Files#6753]
### What's the Problem?

In explorer.exe, people can move columns as they wish. For example, we can move the "Modified Date" to the last and make "Type"  stay next to "Name".  Actually, what's most annoying me is that, in OneDrive, usually the "State" is next to "Name", but I can't see them easily because it stays at the last column.
BTW, I'm using Chinese version of Windows so the order may be different from yours.

### Solution/Idea

A window of choosing which columns to see and the order would be a choice.

### Alternatives

Just let users pull the columns and order them.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to accomplish X | Should |

### Files Version

v2.0.34.0

### Windows Version

Win10 21H1 19043.1288

**Comment by gave92** [comment]
Thanks for the suggestion. Merging with #4643.
