### ISSUE TITLE
TortoiseSVN dont popup in the Context Menu and no icons status

### ISSUE THREAD

**Issue by Strat0x33** [files-community/Files#6754]
### Description

TortoiseSVN options dont popup in the Context Menu in files but popup in Windows explorer Context Menu.

### Steps To Reproduce

Right click on folder with tortoiseSVN in Files.

### Expected behavior

TortoiseSVN options popup in the Context Menu in Files and Icons on folders.

### Files Version

2.0.34.0

### Windows Version

Windows 10 21H1 9043.1288

### Relevant Assets

![image](https://user-images.githubusercontent.com/48390273/140607994-32656d2e-1aeb-4f38-b2e0-88520f7518a8.png)

![image](https://user-images.githubusercontent.com/48390273/140608003-e29db6d7-5334-410b-9f24-f567ff61f48b.png)

![image](https://user-images.githubusercontent.com/48390273/140608072-0d6103eb-c9b8-4a17-b4da-9859b50651b9.png)

![image](https://user-images.githubusercontent.com/48390273/140608123-390427fd-18a3-41eb-8500-cb029c132824.png)

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?
