### ISSUE TITLE
Copy past multiple file bertween 2 tabs

### ISSUE THREAD

**Issue by DorianSrdt** [files-community/Files#6755]
### Description

So i juste wanted to move some picture from my Download to another folder, so i opened another tab and try to copy and past in the good folder,  but Files crashed when i did it

### Steps To Reproduce

Go to Download
Select multiple picture
Copy them with Crtl+C
Paste them in another folder into another tabs with Crtl+V

### Expected behavior

just copy some pictures into another folder without any crash

### Files Version

Version : 2.0.34.0 OS Version: 10.0.19042.1288

### Windows Version

Windows 10 21H2

**Comment by gave92** [comment]
Merging with #6756.

**Comment by gave92** [comment]
Thanks for the report. Cuuld you upload the app's log files?

**Comment by DorianSrdt** [comment]
Do you mean the file "debug.log" into Localstate ?

**Comment by gave92** [comment]
Yeah "debug.log" and "debug_fulltrust.log"

**Comment by DorianSrdt** [comment]
[debug.log](https://github.com/files-community/Files/files/7491315/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7491316/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview build? https://files.community/download/preview
