### ISSUE TITLE
Status still not shgowing for all items

### ISSUE THREAD

**Issue by brucebinder** [files-community/Files#6756]
### Description

More items seem to show the status, but missing in many places.

### Steps To Reproduce

Open Files
Go to different folders

### Expected behavior

The Status column is missing under many folders. Andeven on folders where it exists, not every item has a stratus icon.

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.282

### Windows Version

21H2 22000.282

**Comment by gave92** [comment]
#6708
