### ISSUE TITLE
Add double click on blank area to go back to parent directory.

### ISSUE THREAD

**Issue by khatwanir111** [files-community/Files#6757]
Hi,

This has been the best file manager I've used in Windows! I would like to suggest a feature that many Linux distros have that I find pretty compelling to use. 

When you double click on blank area it should redirect user to parent directory. The Nemo file manager on Linux Mint has this functionality as I remember.

### Files Version

Version: 2.0.34.0 OS Version: 10.0.19043.1320

### Windows Version

Windows 10 21H1

**Comment by gave92** [comment]
Thanks for the suggestion, merging with #2355. Glad you like Files xD
