### ISSUE TITLE
Resizing the window forces all the sections in the sidebar to collapse

### ISSUE THREAD

**Issue by whizzed** [files-community/Files#6758]
### Description

When you resize the window enough to hide the left sidebar, and then size it back, the sidebar reappears with all the sections collapsed

### Steps To Reproduce

1. Resize the window width until the sidebar disappears.
2. Resize it back until it appears again.

### Expected behavior

The sidebar should be restored in the state it was in when it got hidden during the window resizing.

### Files Version

2.0.34.0

### Windows Version

Windows 10 10.0.19043.1320

**Comment by gave92** [comment]
Thanks for the report. Merging with #4128
