### ISSUE TITLE
Details layout column width is never saved.

### ISSUE THREAD

**Issue by whizzed** [files-community/Files#6759]
### Description

When I change the width of columns in the Details layout it's not saved, including:
- navigating to another directory
- switching to another layout and then back to Details in the same directory
- across application restarts

'Individual preferences for files and folders' setting doesn't seem to have any effect on this issue.

### Steps To Reproduce

1. Enable Details layout
2. Resize one or more columns
3. a) navigate to another directory
3. b) change layout to any other, then change it back to Details
4. c) restart the application

### Expected behavior

Column widths should be saved

### Files Version

2.0.34.0

### Windows Version

Windows 10 10.0.19043.1320

**Comment by gave92** [comment]
Thanks for the report. Merging with #6448
