### ISSUE TITLE
Add option to sort/group photos and videos by their dimensions

### ISSUE THREAD

**Issue by RootBurner** [files-community/Files#6760]
### What's the Problem?

No option to sort videos and photos by their dimensions

### Solution/Idea

An option to sort videos and photos by their dimensions to get a more precise look at high quality files.

### Alternatives

The default file explorer has that option.

### Files Version

2.0.34.0

### Windows Version

Windows 11 21H2

**Comment by Josh-65** [comment]
Merging with #9907
