### ISSUE TITLE
Disposition mode liste

### ISSUE THREAD

**Issue by didierhassio** [files-community/Files#6761]
### What's the Problem?

Les différents modes proposés dans le menu dispositions ne permettent pas d'afficher un maximum de répertoires comme le fait le mode liste de l'explorateur windows.

### Solution/Idea

Ajouter un mode liste dans le menu disposition

### Alternatives

aucune

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.0.34.0

### Windows Version

windows 10 21H1 19043.1320

**Comment by gave92** [comment]
Thanks for the suggestion, merging with #2509.

**Comment by yaira2** [comment]
@didierhassio thank you for your patience, I'm excited to share that a List View layout will be included in the next release.
