### ISSUE TITLE
Add a button to clear all notifications in the status center

### ISSUE THREAD

**Issue by joseehilton147** [files-community/Files#6763]
### What's the Problem?

When we move a lot of files we need to remove one by one from notification list, will be good if we have a clear all button

### Solution/Idea

![image](https://user-images.githubusercontent.com/53986027/140628391-ef072885-3513-4d1c-b4cc-88c22ed5171d.png)

Like image

### Alternatives

None

### Files Version

Versão: 2.0.34.0 OS Version: 10.0.22000.282

### Windows Version

Windows 11 21H2 22000.282

**Comment by Josh-65** [comment]
This should be closed as it has been added.
