### ISSUE TITLE
开打文件夹的时，显示的文件夹图标背景为黑色。

### ISSUE THREAD

**Issue by ZacRenis** [files-community/Files#6766]
### Description

开打文件夹的时，显示的文件夹图标背景为黑色。刷新后回复正常。

### Expected behavior

开打文件夹的时，显示的文件夹图标背景为黑色。刷新后回复正常。

### Files Version

版本: 2.0.34.0 OS Version: 10.0.22000.258

### Windows Version

版本	Windows 11 专业工作站版 版本	21H2 安装日期	‎2021/‎9/‎26 操作系统版本	22000.258 体验	Windows 功能体验包 1000.22000.318.0

**Comment by gave92** [comment]
Merging with #6373
