### ISSUE TITLE
Accent color clashes with background

### ISSUE THREAD

**Issue by and-Zmei** [files-community/Files#6767]
### Description

In the new version, the icons for file operations have become very thin and two-colored, which is why their readability has deteriorated many times.

### Expected behavior

Make the icons one color like the "new window" and "new pan" icons, or choose a different set ...

### Files Version

2.0.34.0

### Windows Version

Windows 11

### Relevant Assets

![yCfekhPX2X](https://user-images.githubusercontent.com/6105225/140637384-fe827a41-8afa-47bc-a734-4e90e1090292.png)
![jZQewUzZa8](https://user-images.githubusercontent.com/6105225/140637387-5b283108-cd9e-4f94-890d-7462818f1edb.png)
![explorer_uBi3PRd7FY](https://user-images.githubusercontent.com/6105225/140637391-e9dfc9da-ba4e-4e49-899f-c0266fc5edea.png)

**Comment by gave92** [comment]
The "second" color depends on what you choose as system accent color in Windows settings, an unfortunate combination here.

**Comment by and-Zmei** [comment]
This is the problem, that in the standard explorer the icons are always blue, and yours depends on the color of the theme, you can see it in the screenshots
I think it's wrong...
![explorer_2Qz52IxS54](https://user-images.githubusercontent.com/6105225/140639713-c0d45ce0-9c80-4c71-a36d-93dc4a39c0c7.png)
![explorer_ibgU0P4AcC](https://user-images.githubusercontent.com/6105225/140639716-60036d47-fb0b-4d1f-8233-c9d39643a439.png)

**Comment by gave92** [comment]
\+ @yair100, should we only use the user's accent color in light mode?

**Comment by SOI7** [comment]
Alternatively, you could make the accent color visible only when the button is enabled, while it turns white when disabled

**Comment by yaichenbaum** [comment]
> + @yaichenbaum, should we only use the user's accent color in light mode?

This is the first time I've seen the colors get messed up like this, perhaps we can tweak the accent color to avoid this. @winston-de any thoughts?

**Comment by winston-de** [comment]
this isn't just an issue with files I think. if the accent color is gray other areas of winui, such as hyperlink buttons, will also have poor contrast. 

Anyway, perhaps adding an option to just use blue for accented icons would be a good workaround.

**Comment by yaichenbaum** [comment]
> this isn't just an issue with files I think. if the accent color is gray other areas of winui, such as hyperlink buttons, will also have poor contrast.
> 
> Anyway, perhaps adding an option to just use blue for accented icons would be a good workaround.

@winston-de what about adding the option to choose a custom accent color when we implement the new themes customization options?

**Comment by yaichenbaum** [comment]
@and-Zmei this is a common issue when using a dark accent color in dark theme, our recommendation is to switch to a lighter accent color.

**Comment by FlorentLM** [comment]
Can it be possible to add an option to just disable the accent colour for these icons and use white?

Or, alternatively, follow the user's preference for "Show accent colour on title bars and windows borders" under the Settings > Personalisation > Colours stock menu

**Comment by Josh-65** [comment]
You can make a custom theme that set them to what every color you want.
