### ISSUE TITLE
Bug: Draging files over other items makes it look like they're being selected

### ISSUE THREAD

**Issue by martsum** [files-community/Files#6768]
### Description

Dragging and dropping files behaviour is inconsistent and unexpected.

### Steps To Reproduce

1. Drag a file or folder over another item
2. Other items will sometimes become 'highlighted' with the accent color
3. When releasing the mouse, the other items will continue to stay highlighted.

### Requirements

When dragging a file/folder over other items, they should not become highlighted...

### Files Version

2.0.34

### Windows Version

Windows 11 21H2 22000.282

**Comment by marcinhordziej** [comment]
Having the same issue on 2.1.13.0 on W11.

**Comment by alishtamimi** [comment]
Any updates on this issue? Is it in progress to solve or not?

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by sthivaios** [comment]
I have just checked this, and the issue is solved, at least for me.

I am using the PRE version of "Files". I suggest updating the app (if it is not up to date) and checking it again.

So, for me, the items did not get hilighted.

**Comment by alishtamimi** [comment]
It is almost solved, but yet, there is a problem when you drag a file and change its place for example, it will remain highlighted even if you click on another file.

**Comment by sthivaios** [comment]
@alishtamimi 

Oh yes! I just tried that and I can confirm that his happens...

https://user-images.githubusercontent.com/109022579/195158682-fa24afa2-6973-4514-89cb-9e27078d3816.mp4

**Comment by yaichenbaum** [comment]
The issue is resolved in the details layout but it's still present in the other layouts.

**Comment by yaichenbaum** [comment]
The issue is resolved in `main`.
