### ISSUE TITLE
Show Drives instead of expand or minimize the label

### ISSUE THREAD

**Issue by LazieWouters** [files-community/Files#6770]
### What's the Problem?

When clicking on "Drives" in the left panel it will expand or minimize the group. I think it will be more useful if it shows the drivers when clicked on it, like in the image below:

### Solution/Idea

![image](https://user-images.githubusercontent.com/77227512/140644459-70ec12b2-9918-42ca-87b8-cf42ac33c143.png)

And it can continue expanding and minimizing the group.

### Alternatives

-

### Files Version

2.0.34.0

### Windows Version

10.0.22478.1000

**Comment by Josh-65** [comment]
This is what the home page is designed for you can turn off all elerments except drives. It should also not be added that way as the sidebar entry will become usless with it opening and closing constantly. See Windows 11 media player playlist for an example.
