### ISSUE TITLE
Configure default layout / Apply layout configuration to all subfolders in tree

### ISSUE THREAD

**Issue by 1Tatsumaru1** [files-community/Files#6771]
### What's the Problem?

Each time File opens a new tab, or when a pinned folder is selected, the layout is restored to "details".
It doesn't seem possible to configure File to memorize a specific layout ("column" for instance) as the default layout, either for all folders nor a specific one in the disc tree.

### Solution/Idea

A fonctionnality matching this need is implemented in Windows default file explorer : it constists of a tweek available from the application's options. Below is a capture of the feature (pardon my French) : 

![image](https://user-images.githubusercontent.com/26043294/140645007-d14493f4-16df-4069-aa55-4ea2c0220484.png)

### Alternatives

None

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.0.34.0

### Windows Version

Windows 10.0.19043.1288

**Comment by gave92** [comment]
You should be able to set a fixed/default layout for all folders by:

- Turn Off "Enable individual preferences for individual directories" in Settings > Files and Folders
- Go to any folder and set your desired layout mode
- Optional: Turn "Enable individual preferences for individual directories" back on

The selected layout at step 2 will be the default.

**Comment by 1Tatsumaru1** [comment]
Works perfectly !

Many thanks
