### ISSUE TITLE
Disable animations optional

### ISSUE THREAD

**Issue by fwkart** [files-community/Files#6772]
### Solution/Idea

Is it possible to add an optional setting that disables all animations? I find the click animations annoying when I want to open folders and files.

Best regards

### Alternatives

...

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

v2.0.34.0

### Windows Version

Windows 10 21H1 19043.1320

**Comment by gave92** [comment]
Click animations can't be removed on Windows 10 unfortunately. Good news is that they have been removed from Windows 11.
