### ISSUE TITLE
Moving a ton of files (externally) causes Files to crash

### ISSUE THREAD

**Issue by cfpwastaken** [files-community/Files#6773]
### Description

I was trying to move the contents of one folder to another while having the folder i was moving from open in files. It crashed because it prob. couldnt handle all of these files moving

### Steps To Reproduce

1. Open folder with a ton of files in the app
2. Open another file manager (like normal explorer) to move all of the files to another folder
3. Crash

### Expected behavior

It should just handle it or stop updating for a bit

### Files Version

2.0.34.0

### Windows Version

10.0.22000.258 (Windows 11 build)

**Comment by gave92** [comment]
Thanks for the report. Could you post the app's log files?

**Comment by cfpwastaken** [comment]
[debug.txt](https://github.com/files-community/Files/files/7506691/debug.txt)
[debug.log](https://github.com/files-community/Files/files/7506692/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7506693/debug_fulltrust.log)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/7506694/debug_fulltrust.txt)
You mean these?

**Comment by yaichenbaum** [comment]
@cfpwastaken thank you.

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview build? https://files.community/download/preview
