### ISSUE TITLE
.htaccess files are being hidden when viewing network drives

### ISSUE THREAD

**Issue by LolaSeveera** [files-community/Files#6774]
### Description

.htaccess files are being hidden from network drives. When viewed in Explorer, the files appear.
Viewing the same files from a local drive reveals the .htaccess files.

I disabled the settings to hide protected files, enabled file extensions and hidden files.

Here are some screenshots:
Viewing network drive: https://i.imgur.com/s9YXGuU.png
Viewing local drive: https://i.imgur.com/okpApka.png
Files folder settings: https://i.imgur.com/r56LXOr.png
Files global settings: https://i.imgur.com/IVZEMNW.png

### Expected behavior

All files should be shown everywhere

### Files Version

2.0.34.0

### Windows Version

10 19041.1288

**Comment by gave92** [comment]
Related #2436
