### ISSUE TITLE
je configurais

### ISSUE THREAD

**Issue by danimusicos** [files-community/Files#6776]
### Description

je m'apprêtais à configurer

### Steps To Reproduce

[debug.log](https://github.com/files-community/Files/files/7492647/debug.log
[debug_fulltrust.log](https://github.com/files-community/Files/files/7492648/debug_fulltrust.log)
)

### Expected behavior

je m'apprêtais à modifier les paramètres

### Files Version

Version : 2.0.34.0 OS Version: 10.0.19043.1320

### Windows Version

Windows Feature Experience Pack 120.2212.1070.0

### Relevant Assets

no image

**Comment by gave92** [comment]
Thanks for the report. Could you post the contents of this file: `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState\settings\terminals.json`.
