### ISSUE TITLE
sidebar UI issue on hover

### ISSUE THREAD

**Issue by exxmen** [files-community/Files#6777]
### Description

There are small underlines showing on currently unselected sidebar items when hovering over them

### Steps To Reproduce

1. Open Files
2. Select an item from the sidebar
3. Hover over an unselected item

### Expected behavior

No underlines on the items upon hover

### Files Version

Version: 2.0.34.0 OS 

### Windows Version

Windows 11 Build 22478.1012

### Relevant Assets

![Files with UI issue](https://user-images.githubusercontent.com/4624303/140655062-1d1af66e-2ff9-4105-a7cf-8ca1bff96b88.png)

**Comment by yaichenbaum** [comment]
This is an issue with WinUI, can you open an issue on their repository?
