### ISSUE TITLE
Word selection cancels renaming

### ISSUE THREAD

**Issue by DAmNRelentless** [files-community/Files#6778]
### Description

When renaming a file or folder and you only want to select the last word with keybinds `CTRL` + `SHIFT` + `<-`, it will cancel the renaming.
Selection by word is a common key combination in Windows and should not cancel the renaming process.

For those who are unaware:
When you place a cursor between two words, you can use `CTRL` + `->` to jump behind the right word and vise-versa.
If you want to select the word at the same time, you need to hold `SHIFT` while doing so.

### Steps To Reproduce

1. select a file in the Files explorer
2. hit F2 to rename it
3. press arrow key to the right to go to the end of the file name
4. try to select a word to the left of the cursor position with hotkeys `CTRL` + `SHIFT` + `<-`
5. see that the renaming is cancelled

### Expected behavior

The word should be highlighted so I can continue renaming.

### Files Version

2.0.34.0

### Windows Version

Windows 11 Pro Version	21H2 Build 22000.282 Feature Experience Pack 1000.22000.318.0

**Comment by gave92** [comment]
Thanks for the report. Merging with #5824.

**Comment by DAmNRelentless** [comment]
The issue you mentioned states that this was fixed with `2.0.16.0`. I have `2.0.34.0` and still have this problem.

**Comment by gave92** [comment]
Uops

**Comment by wasi-master** [comment]
I can also reproduce this on `2.0.34.0`

Although <kbd>Ctrl</kbd> + <kbd>←</kbd> then <kbd>Shift+End</kbd> is a workaround

**Comment by yaichenbaum** [comment]
This issue was resolved in v2.1.
