### ISSUE TITLE
UI Squished in the About - Manage Settings menu

### ISSUE THREAD

**Issue by EpicGamerCodes** [files-community/Files#6780]
### Description

The UI is really squished and the buttons are really hard to press.

### Steps To Reproduce

1. Go to the settings menu
2. Go to the about menu
3. Click the "Manage Settings"

### Expected behavior

The UI showed up properly.

### Files Version

2.0.34.0

### Windows Version

Windows 11 21H2 22000.282

### Relevant Assets

![image](https://user-images.githubusercontent.com/62027082/140657389-0bb686a7-c465-4701-bb17-ba4f3e4a56c9.png)

**Comment by gave92** [comment]
Thanks for the report. Not an issue with the new UI on main.
