### ISSUE TITLE
Error message when using moved libraries

### ISSUE THREAD

**Issue by justinbernard-dev** [files-community/Files#6781]
### Description

If you move your user folder directory from the standard C: partition and try to open a library through the "libraries"-group in your left sidebar it shows an error message which says: 

"Have you deleted this folder? The folder you are trying to access could have been moved or deleted."

However, there is no problem if you access the library from your start page rather than from the "Libraries" section in your left sidebar.

The path that's being accessed is not at all the library's path:

It accesses "C:\Users\justi\AppData\Roaming\Microsoft\Windows\Libraries\Pictures.library-ms"
when it should access "D:\justi\Pictures"

### Steps To Reproduce

1. Move one of your libraries to a different partition than C:
2. Show the libraries section in your sidebar.
3. Click on the library you moved.
4. Get the error.

### Expected behavior

There should be no error whatsoever and you should just get to the newly defined path of your library.

### Files Version

Versão: 2.0.34.0 

### Windows Version

Windows 11 21H2 22000.258

### Relevant Assets

The log doesn't mention anything on the error. The last occurrence was at 20:28 when it says "show context menu".

**Comment by justinbernard-dev** [comment]
### Assets
[debug.log](https://github.com/files-community/Files/files/7492961/debug.log
![Files bug](https://user-images.githubusercontent.com/83189122/140659200-a039bd66-6234-4877-809d-739498983592.jpg)
)

**Comment by nvi9** [comment]
@justinbernard-dev is this happening after deleting/renaming the `cache.db` file too?

**Comment by justinbernard-dev** [comment]
@nvi9 could you tell me where I can find this cache file? Searching my PC with Search Everything doesn't give me a result that could correspond to Files Application.

![image](https://user-images.githubusercontent.com/83189122/147889330-be9e6dc2-95ed-40c1-82c5-a19743960409.png)

**Comment by nvi9** [comment]
It should be located in the same directory as your log file: `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`

**Comment by justinbernard-dev** [comment]
@nvi9 there sadly is no such file. Even if I search the whole `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\` folder using explorer.

**Comment by Josh-65** [comment]
Is this still an issue?

**Comment by WubTheGame** [comment]
In case it helps, I'm having the same issue with different steps. All I did was delete a file or two in my Documents and Pictures libraries, and now when I click on the shortcuts for them I get this same notification once if not twice. Difference is I haven't moved these libraries to another drive, they're still on my C drive. Latest version, 22H2 Win10. Actually, my Videos library is on another drive, but that doesn't have the issue. I figure it's a problem with the shortcuts themselves, Microsoft code being screwy.

**Comment by Josh65-2201** [comment]
Are you sure that all path link in libraires properties are going to valid folders.

**Comment by WubTheGame** [comment]
Yes...? If it weren't so, wouldn't it just not have anything to display and error?
