### ISSUE TITLE
Network shows no network locations vs Existing File Explorer (just spins)

### ISSUE THREAD

**Issue by littlefooch** [files-community/Files#6782]

**Comment by gave92** [comment]
Can take a full minute to load the first time. Could you try what happens if you reopen the app and let it load for a little time?

**Comment by gave92** [comment]
Also please add the app version to the description and upload the log files.

**Comment by littlefooch** [comment]
Marco,

I sat and waited for 30 seconds for any locations to appear (or my NAS).
By comparison, FE shows network locations as soon as it comes up.

Version: 2.0.34.0
OS Version: 10.0.22000.282 (note this is Win 11 Beta)
Point me to the logs and I'll send them.

I'll be happy to do any testing for you.
Look and feel is very good.

I need network locations to make it usable.

Thanks

LF

**Comment by gave92** [comment]
Thanks for the info. You can reach the log files from Files Settings > About > Open log location ("debug.log" + "debug_fulltrust.log").
Could you also post a screenshot of Network folder in windows explorer?

**Comment by Josh-65** [comment]
Is this still an issue?
