### ISSUE TITLE
Window loses transparency when inactive

### ISSUE THREAD

**Issue by Hellobrine** [files-community/Files#6785]
I am using transparent theme and the issue is that Files lose it's transparency when the window is going inactive/not focused.

![image](https://user-images.githubusercontent.com/12008556/140660518-de0691ad-1adb-44bb-b719-7c55cdf10894.png)
![image](https://user-images.githubusercontent.com/12008556/140660539-7d05bb33-de16-4b78-a69f-17a21cfb6d4a.png)

**Comment by gave92** [comment]
Closing as this behavior is expected and controlled by Windows.

**Comment by Hellobrine** [comment]
Thanks for explaining :)
