### ISSUE TITLE
Cast to Device - not working

### ISSUE THREAD

**Issue by psl3** [files-community/Files#6790]
### Description

Just started to use Files so do not know what to expect but I did find that the Cast To Device feature did not work - it showed a sub-menu item "searching for devices" but never changed.  
I did immediately try the Windows 11 default Cast feature that picked up my LG TV and cast perfectly.

Looking great tool - hope it keeps improving, including a fix for the Cast feature.

### Steps To Reproduce

Select a video file
Right click to get context menu
Click on cast to device

### Expected behavior

Show Cast capable devices (in my case an LG TV)

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.282

### Windows Version

Windows 11 Pro 21H2 22000.282

**Comment by gave92** [comment]
Thanks for the the report. Could you post a screenshot of Files vs Explorer?
