### ISSUE TITLE
Items fail to be deleted when recycle bin is disabled

### ISSUE THREAD

**Issue by mbeps** [files-community/Files#6791]
### Description

If the bin is disabled, when trying delete items, they do not get deleted unless the option to delete permanently is selected. An error is returned saying "Recycle failed". This is probably caused since Files tries to move the item to the recycle bin even though it is set to permanently delete items. 

### Steps To Reproduce

1. Disable bin by going on bin properties and selecting "_Don't move files to the Recycle bin". Remove files immediately when deleted_"
2. On Files UWP, try to delete any file

### Expected behavior

The file should be removed permanently deleted by default. Selecting "Permanently delete" works as expected. 

### Files Version

2.0.34.0

### Windows Version

Windows 11 21H1 Build 22000.258

### Relevant Assets

![image](https://user-images.githubusercontent.com/58662575/140650737-b1405c26-a141-484e-a946-38c3e0662b37.png)

**Comment by gave92** [comment]
Thanks for the report. Merging with #6340
