### ISSUE TITLE
Hide desktop.files.json

### ISSUE THREAD

**Issue by Pietro228** [files-community/Files#6793]
### Solution/Idea

I would like to see an option to hide desktop.files.json file. I want to have hidden files visible and it annoys me in my file list. 

### Alternatives

I would like to see an option to hide desktop.files.json file.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

v2.0.33

### Windows Version

Windows 11 21H2 22000.282

**Comment by wasi-master** [comment]
Yeah this would be nice

**Comment by gave92** [comment]
The introduction of desktop.files.json was a mistake, it has been corrected in latest code.

**Comment by wasi-master** [comment]
Oh alright
