### ISSUE TITLE
MEGA on Cloud Storages (and an option to manually configure unrecognized drives)

### ISSUE THREAD

**Issue by yurnasg** [files-community/Files#6794]
### What's the Problem?

Does not recognize Mega Sync folder.

![image](https://user-images.githubusercontent.com/51727725/140669277-964b20cd-cbce-4cc8-83f0-04da5aa0caf1.png)

### Solution/Idea

If possible try to add this Storage automatically

### Alternatives

It would be interesting to put an option in the settings to add unrecognized drives, where we could say the path, write a name and an icon. 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Versão: 2.0.34.0

### Windows Version

Windows 10 21H1 19043.1288

**Comment by gave92** [comment]
Mega should be already detected.
- Does mega appear in the left pane of windows explorer?
- Could you upload the app's log files?

**Comment by yaichenbaum** [comment]
@yurnasg can you open a new feature request to allow users to manually configure unrecognized drives?

**Comment by yurnasg** [comment]
> Mega should be already detected.
> 
> * Does mega appear in the left pane of windows explorer?
> * Could you upload the app's log files?

* Mega is not showing up in windows explorer either
*
[debug.log](https://github.com/files-community/Files/files/7499997/debug.log)

**Comment by yurnasg** [comment]
> @yurnasg can you open a new feature request to allow users to manually configure unrecognized drives?

Yes! I can. This would also be a manual solution for other Issues I created (https://github.com/files-community/Files/issues/6795) and it opens up more possibilities for customization

**Comment by gave92** [comment]
> Mega is not showing up in windows explorer either

Well, that explains why it does not appear in Files. I'm closing this in favor of the feature request for manual drives customization.
