### ISSUE TITLE
Add config section to settings to add/remove cloud drives

### ISSUE THREAD

**Issue by yurnasg** [files-community/Files#6795]
### What's the Problem?

With the new Google Drive for Windows, cloud drives are also shown as external drives in Windows. It would be nice to automatically hide from the units section.

### Solution/Idea

Hide the drive when it's recognized as a network drive

### Alternatives

We can have an advanced option where we can mark drives we don't want to appear. If automatic detection is not possible, the user would do this manually.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Versão: 2.0.34.0

### Windows Version

Windows 10 21H1 19043.1288

**Comment by gave92** [comment]
Thanks for the report. Could you post a screenshot of the Files sidebar showing the cloud and the drive section?

**Comment by wasi-master** [comment]
Not the original author of the issue but since I have the same setup I'll post my screenshots 

Although the files sidebar does not show google drive for me for some reason.\
Files sidebar (not) showing the cloud (maybe because of #6321):

![image](https://user-images.githubusercontent.com/63045920/140707297-4226f0af-4c2b-4e38-91dd-528d6824be6f.png)

Drives sections (Notice the last `Google Drive (O:)`):

![image](https://user-images.githubusercontent.com/63045920/140707369-742402ad-d6cc-4d57-b485-6c882098a1d8.png)

**Comment by yurnasg** [comment]
> Not the original author of the issue but since I have the same setup I'll post my screenshots
> 
> Although the files sidebar does not show google drive for me for some reason. But it does show for the author as stated in the issue Files sidebar (not) showing the cloud (maybe because of #6321):
> 
> ![image](https://user-images.githubusercontent.com/63045920/140707297-4226f0af-4c2b-4e38-91dd-528d6824be6f.png)
> 
> Drives sections (Notice the last `Google Drive (O:)`):
> 
> ![image](https://user-images.githubusercontent.com/63045920/140707369-742402ad-d6cc-4d57-b485-6c882098a1d8.png)
> 
> ### Notes
> The `O` drive letter is configured by me in the settings of Google Drive for Windows, the default drive letter is `G`

I have 4 Google Drive accounts on my computer, so I have 4 fixed drives on my computer. But out of 4, 1 is in stream mode, while 3 is in mirror mode (the files are in a folder on my PC, with offline copy of the files). These 3 mirror mode accounts are listed on the cloud unit. This answers why in wasi-master is not being displayed.

![Captura de tela 2021-11-08 092415](https://user-images.githubusercontent.com/51727725/140742223-4a6a0132-4c14-4cb3-a5ae-1cd7e79744a7.jpg)

**Comment by wasi-master** [comment]
Well mine are also in mirror mode

![image](https://user-images.githubusercontent.com/63045920/140757536-1f0348d1-ec85-4e73-bc5d-1edd25161914.png)

And they show up in the file explorer as actual folders too

![image](https://user-images.githubusercontent.com/63045920/140757766-add359c1-55ee-4082-a87b-46f5f67fa580.png)

I currently don't really need it that much so I did not open a new issue yet. Thanks anyways

**Comment by josh-65** [comment]
It is possible to hid the drive using external tools like Win Aero (https://winaero.com/hide-drive-windows-10-file-explorer/) and fir me it will still show the folder location in the cloud section of the sidebar

**Comment by yurnasg** [comment]
> It's possible to hide the drive using external tools like Win Aero (https://winaero.com/hide-drive-windows-10-file-explorer/) and for me it will still show the folder location in the cloud section of the sidebar

From what I've read, just one change in the registry is enough, this solves half of the problems and could still be an interesting function for the future of the app, what do you think?

**Comment by yurnasg** [comment]
> I think this would be a nice thing to have

I also think. Now just think a little about how to solve this problem with Google Drive

**Comment by yaichenbaum** [comment]
@yurnasg can you report this to Google and ask if they can change the behavior?

**Comment by yaichenbaum** [comment]
@gave92 what do you think about creating a config section in the settings file where users can add/hide cloud drives?

**Comment by gave92** [comment]
@yaichenbaum instead of a dedicated settings page, we could instead allow users to customize the Cloud section of the sidebar like they can the Favorites section.

**Comment by yaichenbaum** [comment]
> @yaichenbaum instead of a dedicated settings page, we could instead allow users to customize the Cloud section of the sidebar like they can the Favorites section. Right-click on section header would show the option to add more cloud drives, right clicking on a cloud drive would show a "hide" option (similar to Libraries section).

That's a better solution, but we would still need a value in the json file to keep track of removed drives so that we don't add them again. Would you add a content menu item to pin new drives, or would the user need to manually edit the file?

**Comment by gave92** [comment]
Good question, a third option is to use a file picker.
I don't fancy an extra context menu entry..

**Comment by yaira2** [comment]
@yurnasg Google Drive will only display under cloud drives in the next release.
