### ISSUE TITLE
Automatically adjust all columns to the appropriate size

### ISSUE THREAD

**Issue by haocvg** [files-community/Files#6796]
### What's the Problem?

When the column width is fixed, some columns such as names cannot be displayed completely
![image](https://user-images.githubusercontent.com/44605406/140676982-5d40981f-9a86-4c5b-b7cd-1cae1610a877.png)

### Solution/Idea

Add the right-click menu in the column header to adjust all columns to a suitable size option .
Add the option to automatically adjust all columns to the appropriate size in the settings like explorer.

### Alternatives

no

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

version: 2.0.34.0 OS Version: 10.0.22494.1000

### Windows Version

windows 11  22494.1000

**Comment by gave92** [comment]
Merging with #4643
