### ISSUE TITLE
The app doesn't organize/group correctcly files and folder from "the future"

### ISSUE THREAD

**Issue by LazieWouters** [files-community/Files#6799]
### Description

![image](https://user-images.githubusercontent.com/77227512/140704063-ef41d97e-5daa-41fb-ba8e-5146dbbd61be.png)

As you can see File Explorer group the folder into "Some date in the future" while Files group it into "Earlier this weak"

I know that is bizarre create files and folder with a future date of creation, but that is a feature I use for some kind of works.

### Expected behavior

Group files and folder with dates of creation that are in the future in the group "Some date in the future"

### Files Version

2.0.34.0

### Windows Version

10.0.22478.1000

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?
