### ISSUE TITLE
Ctrl + L, Alt +D do not focus location bar on a new tab page

### ISSUE THREAD

**Issue by tesar-tech** [files-community/Files#6800]
### Description

Normally Alt + D keyboard shortcut focuses the location bar. This is not happening on Home Tab (new tab)

### Steps To Reproduce

1. Create new tab
2. Press `Alt` + `D`

### Expected behavior

It should focus location bar as it does on "normal" (not new) tab

### Files Version

Version: 2.0.34.0 

### Windows Version

Windows 11 10.0.22494.1000

**Comment by lakani** [comment]
this should be classified as (default explorer)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #8861
