### ISSUE TITLE
Expanded sidebar sections don't show after Files restart

### ISSUE THREAD

**Issue by maicol07** [files-community/Files#6801]
### Description

After expanding sections and restarting Files, these sections can't be shown at first. You need to click two times (collapse and extend again) before seeing them

### Steps To Reproduce

1. Open Files
2. Expand some sections in the sidebar (check first screenshot below)
3. Close Files
4. Reopen Files
5. See bug (check second screenshot below)

### Expected behavior

Files correctly shows the expanded sections

### Files Version

2.0.34

### Windows Version

Windows 11 Pro 22494.1000

### Relevant Assets

[debug_fulltrust.log](https://github.com/files-community/Files/files/7495863/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7495864/debug.log)

## Images
Before restart:
![immagine](https://user-images.githubusercontent.com/9463142/140720155-3f5086d1-1208-4bad-ae88-6b1bee6d1570.png)

After restart:
![immagine](https://user-images.githubusercontent.com/9463142/140720213-33631506-4bbf-4e0e-9401-d762e2f26a38.png)

**Comment by gave92** [comment]
Merging with #5676
