### ISSUE TITLE
crash when the browser jumps to a file

### ISSUE THREAD

**Issue by lningxi** [files-community/Files#6802]
### Description

when the downloaded content in Google Chrome is clicked and displayed in the folder, it will be displayed normally when it is clicked for the first time, and there will be a long delay after the second time

### Steps To Reproduce

1.Google Chrome
2.Download content
3.Show in folder

### Expected behavior

hope there won't be any delay

### Files Version

2.0.34.0

### Windows Version

Windows 11 21H2 22000.282

**Comment by gave92** [comment]
Delay or crash? Could you post the apps log files? Thanks!
