### ISSUE TITLE
Inconsistent context menu size

### ISSUE THREAD

**Issue by mbeps** [files-community/Files#6803]
### Description

Right click context menu is different size depending on where it is clicked. When clicking on the lower half of the app, the context menu is smaller with legacy items being accessible via scrolling down as expected. However, when clicking on the upper half of the app, the context menu is larger showing all the options including all legacy context menu entries without any scrolling. 

### Steps To Reproduce

1. Go to any location and right click (preferably empty space otherwise a folder full of items it required)
2. Right click on the upper half of the page for the larger context menu
3. Right click on the lower half of the page for the smaller context menu

### Expected behavior

The context menu should be the same size no matter where the user right clicks. The context menu should be the smaller one showing legacy entries when scrolling down. A screenshot of the expected behaviour has been attached. 

### Files Version

2.0.34.0

### Windows Version

Windows 11 21H2 Build 22000.258

### Relevant Assets

When right clicking from the button (correct size):
![image](https://user-images.githubusercontent.com/58662575/140725920-0376fc53-c724-44da-bf15-d11f47ce522a.png)

When right clicking from the top (incorrect size)
![image](https://user-images.githubusercontent.com/58662575/140726227-2b330d15-68ee-4231-b0cd-b014cfe2dab3.png)

**Comment by generalguy41** [comment]
Same as #6705?

**Comment by gave92** [comment]
The "correct size" is the big one BTW. Too many people were complaining that they could not find the shell options if they had to scroll.

**Comment by mbeps** [comment]
@gave92 But will clutter up the context menu like the legacy one. If there are a lot of entries in the context menu, it will be  come huge and fragmented. It's not a good option long term.

**Comment by gave92** [comment]
There are at most 4 shell option in the main context menu so it won't become too cluttered. Anyway we could also make this a setting.

**Comment by mbeps** [comment]
Adding an option to choose between the scrolling context menu and the full sized one can be implemented.
