### ISSUE TITLE
Shift Click crash the App

### ISSUE THREAD

**Issue by artscer** [files-community/Files#6805]
### Description

I Shift + Click over a folder an the app crashed

### Steps To Reproduce

1. Open the app
2. Shift + Click over a folder

### Expected behavior

Open a folder

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.282

### Windows Version

Windows 11 Version 10.0.22000 Build 22000

**Comment by gave92** [comment]
Thanks for the report. Could you post the app's log files?

**Comment by artscer** [comment]
[debug.log](https://github.com/files-community/Files/files/7497935/debug.log)

**Comment by yaichenbaum** [comment]
@artscer is this still an issue in the preview version? http://files.community/download/preview
