### ISSUE TITLE
Network symlink reloading

### ISSUE THREAD

**Issue by SiRo24** [files-community/Files#6806]
### Description

I've got a symbolic link directing to another win PCs network share. 
When I am inside this Folder, Files keeps reloading the page every second. Everything works, except it's extremely annoying, and I can't make any selections. 
The strange part is, if I enter a subfolder of this symlink (still on the network share) the reloading issue is gone.

### Steps To Reproduce

1. Create a Symlink directing to a network share
2. Open the Folder

### Expected behavior

No reloading

### Files Version

v2.0.34.0

### Windows Version

Windows 11 Home Insider Preview 22494.1000

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?
