### ISSUE TITLE
Increase the icon size in the customization tab in the properties window

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#6809]
### What's the Problem?

The icons are very small and make it difficult to see them. They also have a lot of padding for the button.
![image](https://user-images.githubusercontent.com/26977075/140775172-9811f13b-3064-44d2-8206-94f650d01d6e.png)

### Solution/Idea

Double the icon size with the same button widths

### Alternatives

None

### Files Version

2.0.34.0

### Windows Version

10.0.19043.1237

**Comment by timwenger** [comment]
I worked on this, and submitted a pull request for it
