### ISSUE TITLE
Drop files to email like gmail or outlook 

### ISSUE THREAD

**Issue by fredericoregateiro** [files-community/Files#6810]
### Description

The drop operation to add files as attached on email client like gmail or outlook is not available. 
I've not tested on any other email clients

### Steps To Reproduce

Create a new email on gmail, or similar web email cliente.
Select 2 or more files from Files and drag them over the email message being created
The drio operation is canceled

### Expected behavior

Normal drop operation

### Files Version

Versão: 2.0.34.0 OS Version: 10.0.19043.1320

### Windows Version

Win 10

**Comment by gave92** [comment]
Is this related to drag&drop on Gmail or Outlook websites in e.g. Chrome or drag&drop to a desktop email client app? If it's the first, what browser? If the second, which email clients?

**Comment by fredericoregateiro** [comment]
It's related to the website, i've tested on edge, chrome and firefox, with gmail and outlook email clients.
Only one file works, but multiple files doesn't.

**Comment by yaichenbaum** [comment]
Merging with #6941
