### ISSUE TITLE
cannot access %appdata%

### ISSUE THREAD

**Issue by cyril59310** [files-community/Files#6811]
hello,
unable to access appdata with files 

"Windows cannot access the specified device, path, or file.
You may not have the correct permissions to access the item."

https://i.imgur.com/CPs4C1N.gif

**Comment by DAmNRelentless** [comment]
In fact, nothing which is executed from the Windows Run menu seems to work with Files.
Version: 2.0.34.0
OS Version: 10.0.22000.348

**Comment by Josh-65** [comment]
you have to put files.exe before the command
