### ISSUE TITLE
Files Not Opening

### ISSUE THREAD

**Issue by MrAwesomeGuy27** [files-community/Files#6812]
### Description

I was just using Files, looking through my files, and I close it, opening it back up again and all of a sudden it just doesn't open! There's the Files splash screen with the Files icon, then it just closes itself automatically. I haven't tried reinstalling yet though, because I'll lose my setup, my settings, and I can't even export them because I can't open the program so yeah that'll suck.

### Expected behavior

I just thought Files would open up as normal, but now it's not opening up at all.

### Files Version

2.0.34.0

### Windows Version

22000.282

**Comment by gave92** [comment]
Thanks for the report. Could you also upload the app's debug logs?
You can get them from `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` (debug.log + debug_fulltrust.log)

**Comment by MrAwesomeGuy27** [comment]
[debug.log](https://github.com/files-community/Files/files/7499594/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7499595/debug_fulltrust.log)

**Comment by gave92** [comment]
Wow. strange. I'd suggest to reinstall the app. After reinstall you can copy over the backed up "LocalState\settings" folder

**Comment by MrAwesomeGuy27** [comment]
just reinstalled it. dunno what that was even about, could be a computer problem but it's never crashed before which is odd
eh whatever
