### ISSUE TITLE
Zip file not opening

### ISSUE THREAD

**Issue by EpicGamerCodes** [files-community/Files#6813]
### Description

It says not a folder, drive unplugged, yet this is a zip file.
Extracting the file works fine (using right click menu) only extracts files not in a folder within that zip file.

### Steps To Reproduce

1. Download a zip file (or find one)
2. Double click it

### Expected behavior

It opens the zip file.

### Files Version

2.0.34.0

### Windows Version

Windows 11 21H2 22000.282

### Relevant Assets

![image](https://user-images.githubusercontent.com/62027082/140802073-abd202ea-8fc2-4691-a64e-c70e9db90376.png)

**Comment by gave92** [comment]
Thanks for the report. 
- Could you share the zip file you're testing with?
- What have you set as default app to open zip files?

**Comment by gave92** [comment]
Any difference if you set Explorer as default app and restart Files?

**Comment by EpicGamerCodes** [comment]
Yes this seems to fix it.

**Comment by IgnusG** [comment]
Didn't fix it for me. Even after restarting. Any zip files fails with the same error.

<details>
<summary>Screenshot</summary>
<img src="https://user-images.githubusercontent.com/6438760/141336433-385fb619-0b28-4420-b36f-32cbae0e5caa.png">
</details>

**Comment by ML-10** [comment]
> Any difference if you set Explorer as default app for zips and restart Files?

Then it'll open in Explorer instead of Files right? I think adding support for zip files would be great.

**Comment by gave92** [comment]
It will still open zip files in Files of you open one _from Files_

**Comment by EpicGamerCodes** [comment]
> > Any difference if you set Explorer as default app for zips and restart Files?
> 
> Then it'll open in Explorer instead of Files right? I think adding support for zip files would be great.

Nope, seems to open in Files.

**Comment by 439bananas** [comment]
> > Any difference if you set Explorer as default app for zips and restart Files?
> 
> Then it'll open in Explorer instead of Files right? I think adding support for zip files would be great.

That did exist but it evidently got broken 🤔
