### ISSUE TITLE
Enable setting a custom path when extracting items

### ISSUE THREAD

**Issue by lakani** [files-community/Files#6814]
### What's the Problem?

when select a Zip file and selects to (extract files), 
files display (Select a destination and extract files) window ,
in which the destination path in text box,

however destination textbox is disabled, and not editable 

### Solution/Idea

the destination textbox should be enabled and editable, so user can modify it by writing down the destination path 

### Alternatives

use can select destination path by pressing browse 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow users to type a custom path when extracting items | Must |
| This proposal will verify the custom path is valid | Must |

### Files Version

Version: 2.0.34.0

### Windows Version

OS Version: 10.0.19043.1320

**Comment by lakani** [comment]
(This proposal will verify the custom path is valid) is not valid, on the opposite, files should create that path if not exist

**Comment by kingsamurai123** [comment]
Hi @lakani , I guess this issue is resolved in the latest version of Files. I don't have this textbox error or any problem with new folder creation. Can you confirm this?

7zip version: 21.07 ( release date 2021-dec-26 )
Files Version: 2.1.15.0 ( installed via MS store )
OS Version: 10.0.22000.593

**Comment by Josh-65** [comment]
Is this still an issue. I can edit the location the extracted files will go on 2.3.0.0
