### ISSUE TITLE
Add an option to manually add cloud drives

### ISSUE THREAD

**Issue by yurnasg** [files-community/Files#6815]
### Solution/Idea

This could be an advanced option where we can type the local folder path on the computer, a name and customize icon. This would create a new section in the Cloud Units space. And it would be nice to put checkboxes where we can hide those that were automatically recognized, but for some reason the person didn't want them to appear. This can resolve unrecognized unit issues (https://github.com/files-community/Files/issues/6794), open up more customization possibilities and improve the experience of people with specific issues (https://github.com/files-community/Files/issues/6795). This advanced solution would be an alternative to the issues I created

### Alternatives

No.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.0.34.0

### Windows Version

Windows 10 21H1 19043.1288

**Comment by yaira2** [comment]
We don't have plans to implement this option right now but if you need a cloud drive that isn't supported, please let us know and we'll try to add support.
