### ISSUE TITLE
Create a Possibility to Hide Units 

### ISSUE THREAD

**Issue by yurnasg** [files-community/Files#6816]
In one of the issues I created, one of the people presented me with a solution that would be a great idea: To have a configuration where we can hide units on the Computer. They remain accessible and the changes to make this happen are just a few modifications to the registry.

It's possible to hide the drive using external tools like Win Aero (https://winaero.com/hide-drive-windows-10-file-explorer/) and for me it will still show the folder location in the cloud section of the sidebar

_Originally posted by @josh-65 in https://github.com/files-community/Files/issues/6795#issuecomment-963220755_

**Comment by Josh-65** [comment]
@yaichenbaum

**Comment by yaichenbaum** [comment]
@yurnasg can you share more details about your use case for this?
