### ISSUE TITLE
Thumbnails not working for png files

### ISSUE THREAD

**Issue by Biodam** [files-community/Files#6817]
### Description

Thumbnails not showing up for png files
![image](https://user-images.githubusercontent.com/15266822/140819092-f5206c0b-417c-4178-964e-9ccf3b8d7fb3.png)
![image](https://user-images.githubusercontent.com/15266822/140819556-2defb43a-2a84-43cc-b456-a0c35c7ac7fe.png)

.jfif .jpeg and .gif are working

### Steps To Reproduce

1. Open a folder with png files
2. Change layout to small/medium/large icons

### Expected behavior

Thumbnails should show up the same as .jpeg and other image types

### Files Version

Version: 2.0.34.0

### Windows Version

Edition	Windows 11 Pro
Version	21H2
OS build	22000.258
OS Version: 10.0.22000.258

**Comment by gave92** [comment]
Thanks for the report. Merging with #6130.
