### ISSUE TITLE
PowerToys Integration

### ISSUE THREAD

**Issue by chking999** [files-community/Files#6818]
### Solution/Idea

Integrate Files with Microsoft PowerToys.  Specifically, the Image Resizer function would be really useful when right-clicking on an image file in Files.

### Alternatives

I have to leave Files and use Windows 10 File Explorer to resize images.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.0.34.0 

### Windows Version

OS Version: 10.0.19043.1288

**Comment by yaichenbaum** [comment]
@chking999 this is already supported, do you have the option turned on in PowerToys?

**Comment by chking999** [comment]
I see it now under More.  Files is a much better file manager that Windows Explorer.  Thanks for the help.
