### ISSUE TITLE
Can't turn off files as default 

### ISSUE THREAD

**Issue by ranjeetsharma0** [files-community/Files#6820]
### Description

I can't turn off files as default file manager.

### Expected behavior

Whenever I uncheck set files as default it asks for admin permission to edit registry, I click ok after editing registry it doesn't uncheck

### Files Version

Version: 2.0.34.0 OS Version: 10.0.19044.1320

### Windows Version

Edition	Windows 10 Pro Version	21H2 Installed on	‎03-‎07-‎2021 OS build	19044.1320 Experience	Windows Feature Experience Pack 120.2212.3920.0

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7501846/debug.log
[debug_fulltrust.log](https://github.com/files-community/Files/files/7501848/debug_fulltrust.log)
)

**Comment by gave92** [comment]
To unset Files you'll need to run the "UnsetFilesAsDefaut.reg" from [this archive](https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip).

**Comment by gave92** [comment]
Issue preventing to unset after reinstall has been fixed.

**Comment by ranjeetsharma0** [comment]
o shit so sorry, Thank You.
