### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by whitemink2012** [files-community/Files#6823]
I love the files app, but there are some ways that I think it could be improved.

- Please allow the preview window to be resizable.  Previews are very small currently.
- Files is a little slower than file explorer, please improve speed.
- Add ability to right-click drag files (to copy, move, create shortcut).

Version: 2.0.34.0
Windows 10

Files is great, thank you.

**Comment by yaichenbaum** [comment]
Thank you for your feedback, merging with #6628 and #1396.
