### ISSUE TITLE
Improve search performance 

### ISSUE THREAD

**Issue by wise-gorilla** [files-community/Files#6825]
### Description

Search feature is very slow compared with the default File Explorer

### Steps To Reproduce

Search on a large indexed folder that contains thousands of files with a broad criteria like *.jpg and compare the speed with File explorer

### Expected behavior

On file explorer it took less than 2 seconds to find 79000 jpg file on 2.8tb folder compared with Files 2.0 which took almost 2 minutes. also the thumbnail generation was much slower on Files 2.0.
Also while loading the thumbnails on File Explorer the searched files was showing the default image viewer app icon while the actual image thumbnail being generated on the other hand on Files 2.0 the files didn't have any default icon during the thumbnail generation.. it was just showing the file names text only

### Files Version

v2.0.34.0

### Windows Version

Windows 11 Pro 21H2

**Comment by carlosvsilva** [comment]
I suggest using the same low-level search method as cmd.exe dir /S which is live and really fast. Maybe PSInternals (now Microsoft) Process Monitor can show the library/system calls to implement same method in Files.

**Comment by yaichenbaum** [comment]
@carlosvsilva is this something you think you can work on?

**Comment by rtxbae** [comment]
Tested out with folder of thousands of items, the search is significantly slower, I thought it's a bug that no result showing up 😅 Also while the programme is searching, perhaps some UI elements could be shown to let user know that they're searching up until the first result showed up? For now, If you double-click to go back when it's searching, the up one level will shows empty (not knowing that it's still searching). Once it's done searching, only then the supposed files/folder on that level will show up.

**Comment by yaira2** [comment]
Merging with #5845
