### ISSUE TITLE
Cannot copy paste if Files is default browser in VMware

### ISSUE THREAD

**Issue by lsassx64** [files-community/Files#6827]
### Description

If the Files is set as a default file browser in a VM environment, copying files form host does not work.

### Steps To Reproduce

Host copy files
Files set as a default browser
Paste or drag and drop form host to guest

### Expected behavior

Copy and pase should work as expected

### Files Version

Version: 2.0.34.0 OS Version: 10.0.19043.1288

### Windows Version

Win 21H1, 10.0.19043.1288

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?
