### ISSUE TITLE
Expand to current folder

### ISSUE THREAD

**Issue by lsassx64** [files-community/Files#6828]
### What's the Problem?

Have ability or setting to expand the left pane to the current listed/selected folder as you can with windows browser

### Solution/Idea

Additional switch in settings

### Alternatives

none

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.0.34.0 OS Version: 10.0.19043.1288

### Windows Version

Win11 21H1 10.0.19043.1288

**Comment by gave92** [comment]
Thanks for the report. For now we have no plans for a tree view in the sidebar, but have a tree view layout instead (#1928).

**Comment by chrfin** [comment]
Please rethink adding this feature. This single feature makes Files useless for me even if I REALLY like all the rest, but I need this navigation capability all the time when using a file explorer, as I switch between neighboring folders in my workflow.
It's always the first thing I change when setting up the default explorer and wonder EVERY time, why they do not enable that by default (anymore)...

**Comment by yair100** [comment]
@lsassx64 @chrfin Tree View is currently available in preview https://files.community/download. It will be included in the next stable release.
