### ISSUE TITLE
Shortcuts not working, and slow refresh

### ISSUE THREAD

**Issue by whitemink2012** [files-community/Files#6829]
I noticed that some shortcuts I have created (on a network drive) are not visible. I use file explorer to verify they are there, but they do not show up in the same location in files. Please fix this.

I noticed that I have to occasionally manually refresh a folder for a contents change to be seen. Please make this automatic.

Version: 2.0.34.0
Windows 10

Files is amazing, please keep improving.

**Comment by gave92** [comment]
Thanks for the report.t merging with #2436.
