### ISSUE TITLE
Add defragment and clean option in drive properties.

### ISSUE THREAD

**Issue by Ketamaboy** [files-community/Files#6831]
Idea

My idea is to add the defragment, check disk errors and clean drive options that appear on the normal file explorer when you see the drive properties.  

### Files Version

Files 2.0.34.0 

### Windows Version

Windows 10 21H1

### Additional comment

![image](https://user-images.githubusercontent.com/91992179/140976148-e962dd78-7764-4641-8828-9b3450b1d32c.png)
![image](https://user-images.githubusercontent.com/91992179/140976200-199514f3-f1f4-462d-8dca-af020fe9ad1b.png)

**Comment by yaichenbaum** [comment]
Thank you for opening this issue, we don't have any plans to implement these options in Files.
