### ISSUE TITLE
"new" menu not closing when changing folder

### ISSUE THREAD

**Issue by mandjevant** [files-community/Files#6836]
### Description

The menu that opens after right-clicking new stays open when I don't choose anything but go to a different folder.

This menu should be closed when I go to a different folder.

### Steps To Reproduce

1. Go to a folder and right-click
2. Hover to "new"
3. Do not select anything but go to the previous folder using the top navigation bar.
4. You can see that the "new" menu is still open.

### Expected behavior

The "new" menu should be closed when I go to a different folder.

### Files Version

v2.0.33

### Windows Version

Windows 10 Home 21H1 19043.1288

**Comment by gave92** [comment]
The "main" menu closes but the new submenu remains open, correct? Could you confirm it happens with any submenu?

**Comment by mandjevant** [comment]
> The "main" menu closes but the new submenu remains open, correct? Could you confirm it happens with any submenu?

Correct, I can confirm.

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?
