### ISSUE TITLE
Bugged menu and unwanted file after "right-click" - "layout-mode".

### ISSUE THREAD

**Issue by mandjevant** [files-community/Files#6837]
### Description

Menu bugginess and weird file generation with layout-mode.

### Steps To Reproduce

1. Right-click on folder
2. Hover over layout-mode
3. Click on another application on a different screen
4. Click back on files, you will not be able to get rid of menu. 
5. When you click "details" a file "desktop.files.json" will appear in the folder you are in.

### Expected behavior

- The menu should be closed when I click on a different application.
Or
- The menu should be closed when I press escape or click next to the menu in files.

Most importantly. "desktop.files.json" should not be generated.

### Files Version

v2.0.33

### Windows Version

Windows 10 Home 21H1 19043.1288

### Relevant Assets

![image](https://user-images.githubusercontent.com/38689620/141105018-716b245a-110f-4328-b9da-955fb4911557.png)

Contents of file:
```json
{"DirectorySortOption":0,"DirectorySortDirection":0,"DirectoryGroupOption":0,"LayoutMode":1,"GridViewSize":100,"ColumnsViewModel":{"TagColumn":{"UserCollapsed":false,"Length":{"Value":0.0,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"LengthIncludingGridSplitter":{"Value":0.0,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"UserLength":{"Value":200.0,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"UserLengthPixels":200.0},"NameColumn":{"UserCollapsed":false,"Length":{"Value":384.46601941747576,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"LengthIncludingGridSplitter":{"Value":385.46601941747576,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"UserLength":{"Value":384.46601941747576,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"UserLengthPixels":384.46601941747576},"StatusColumn":{"UserCollapsed":false,"Length":{"Value":0.0,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"LengthIncludingGridSplitter":{"Value":0.0,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"UserLength":{"Value":50.0,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"UserLengthPixels":50.0},"DateModifiedColumn":{"UserCollapsed":false,"Length":{"Value":384.46601941747576,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"LengthIncludingGridSplitter":{"Value":385.46601941747576,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"UserLength":{"Value":384.46601941747576,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"UserLengthPixels":384.46601941747576},"OriginalPathColumn":{"UserCollapsed":false,"Length":{"Value":0.0,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"LengthIncludingGridSplitter":{"Value":0.0,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"UserLength":{"Value":200.0,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"UserLengthPixels":200.0},"ItemTypeColumn":{"UserCollapsed":false,"Length":{"Value":384.46601941747576,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"LengthIncludingGridSplitter":{"Value":385.46601941747576,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"UserLength":{"Value":384.46601941747576,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"UserLengthPixels":384.46601941747576},"DateDeletedColumn":{"UserCollapsed":false,"Length":{"Value":0.0,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"LengthIncludingGridSplitter":{"Value":0.0,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"UserLength":{"Value":200.0,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"UserLengthPixels":200.0},"DateCreatedColumn":{"UserCollapsed":true,"Length":{"Value":0.0,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"LengthIncludingGridSplitter":{"Value":0.0,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"UserLength":{"Value":200.0,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"UserLengthPixels":200.0},"SizeColumn":{"UserCollapsed":false,"Length":{"Value":384.46601941747576,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"LengthIncludingGridSplitter":{"Value":385.46601941747576,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"UserLength":{"Value":384.46601941747576,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"UserLengthPixels":384.46601941747576},"TotalWidth":1561.8640776699031},"IsAdaptiveLayoutOverridden":true}```

**Comment by gave92** [comment]
Thanks for the report. I can confirm that the "file generation" issue is fixed on main. For the menu issue, merging with #6836.

**Comment by stamminator** [comment]
@gave92 Any date for the release? I think this fix alone should've necessitated a hotfix. Having to add desktop.files.json to the .gitignore in my various git directories is frustrating, and I'm nervous about even opening a network drive using Files.

**Comment by gave92** [comment]
@stamminator It's been fixed for a while on the beta/insider version, which you can grab from here -> https://files.community/download/preview.
For an ETA on a Store release -> @yair100?

**Comment by yaichenbaum** [comment]
@gave92 there are a couple of things left to try to do before the store release like the properties dialog, search filters and reverting the registry changes when uninstalling the app (I'm still working on figuring this one out).

**Comment by yaichenbaum** [comment]
> @gave92 Any date for the release? I think this fix alone should've necessitated a hotfix. Having to add desktop.files.json to the .gitignore in my various git directories is frustrating, and I'm nervous about even opening a network drive using Files.

@stamminator I'm sorry about the issue with the json files, we would have liked to release a hotfix but we're currently held back from releasing updates to the Microsoft Store because the last couple version of WinUI cause certification to fail. They have a fix for this in preview builds but we'd like to wait for a stable version of WinUI before releasing the next update.
