### ISSUE TITLE
Unable to turn off a feature

### ISSUE THREAD

**Issue by TazR6** [files-community/Files#6838]
### Description

I selected the experimental feature of allowing Files to become the default File Explorer.
In trying to turn the feature off, I get the permission window to allow changes, click yes, and nothing happens. It just goes back to the Files settings and the slider remains in the on position.

### Steps To Reproduce

Files settings /experimental
Click on the slider to turn off the default permission.
Permission dialogue appears, click yes.
End up back on the same settings /experimental page with no changes made.

### Expected behavior

I was expecting the app to give default permissions back to File Explorer.

### Files Version

2.0.34.0

### Windows Version

Windows 11 21H2 build 2200.282

**Comment by gave92** [comment]
Thanks for the report. You have reinstalled Files after enabling the feature, correct? This issue is fixed on main.

**Comment by gave92** [comment]
In the meantime to unset Files you'll need to run the "UnsetFilesAsDefaut.reg" from [this archive](https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip).

**Comment by TazR6** [comment]
Hi.

Thank you for the reply and how fast it was. I appreciate it.

Reinstalled after enabling the feature? I have only installed Files once so I do not understand what you mean.
However, I will try running the unset default code and if that works, all is well.
I do not have a clue about coding, so your concise answer is welcome.

Neil :-)
