### ISSUE TITLE
Drag and drop from browser to Files

### ISSUE THREAD

**Issue by Hellobrine** [files-community/Files#6839]
### Description

File cannot be transfered using drag and drop from browser (Chromium based) into Files

### Steps To Reproduce

https://user-images.githubusercontent.com/12008556/141108730-bc4bc08b-80cd-4979-8907-c6d77ceac207.mp4

### Expected behavior

Obviously, it is expected to be transfered

### Files Version

Version: 2.0.34.0

### Windows Version

Windows 11 21H2 22000.258

**Comment by yaichenbaum** [comment]
Merging with #6309
