### ISSUE TITLE
Group by Tags not being saved

### ISSUE THREAD

**Issue by oresfriado** [files-community/Files#6844]
### Description

grouped my folders by tags, but when I left and opened the same folder again, they stopped being grouped by tags.

### Steps To Reproduce

1.Right click, then click group by tags
2. Leave and open the same folder agaim

### Expected behavior

After you re-open the same folder, the folders will stop being grouped by their colors and will instead be part of a "none" group

### Files Version

2.0.34.0

### Windows Version

Windows 10 Pro 20H2 19043.1110

### Relevant Assets

![Untitled-5](https://user-images.githubusercontent.com/71300900/141153273-4e136c84-9f3f-4cae-9ad5-c4039ef2ee08.png)

**Comment by uvmittal** [comment]
happening with me too i have group by tags as default and it just doesnt work properly.
aaaagh this is  such an amazing repo but this bugs just really troubles me day and night , i wish i knew coding and had time so i wouldve fixed it on my own

**Comment by morganwk** [comment]
Just confirmed, I have this issue too. For now, just having the tags at all will fit most of my needs, but I'm really looking forward to being able to actually group by them.

**Comment by Josh-65** [comment]
Is this still an issue?
