### ISSUE TITLE
Add support for loading in translation files at run time

### ISSUE THREAD

**Issue by TheOnlyTails** [files-community/Files#6845]
### What's the Problem?

Today, when translating Files to different languages, you have 2 options:
- The (pretty bad) Multilingual Editor
- Manually editing the XLF file
Neither are particularly good, but they're manageable.

However, one of the more major issues is the lack of context - you have to go hunting around the app to find which string correlates to where, which is annoying, and frankly - a waste of time.

### Solution/Idea

I propose - a new version of Files, specifically for translators, which allowed you to load translation files during runtime, and finally view the context of your translations and verify them before pushing them out to production.

### Alternatives

Not really an alternative, but along with this idea, there could be something like a Crowdin project opened to provide a better UI for translators to work with.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Additional info
Here are the current translation instructions: https://files.community/docs/contributing/translating-files

As requested: @yaichenbaum

**Comment by yaichenbaum** [comment]
@TheOnlyTails I think we can stick with one version and add support for loading in translations files from the settings dialog.

**Comment by TheOnlyTails** [comment]
That would work as well, I would love to have all the other features though.
The reason I suggested a brand new version is that so average users won't have to see all the translator-specific options.

**Comment by yaichenbaum** [comment]
Marking this as resolved since we're now using Crowdin.
