### ISSUE TITLE
Deleting files from WSL does not work if confirmation dialogue is turned off

### ISSUE THREAD

**Issue by IgnusG** [files-community/Files#6849]
### Description

Deleting files in WSL seems to not work if the confirmation dialogue option is turned off. It seems it still tries to do recycling instead of deleting even though that's not possible. 

Turning the dialogue back on resolves the issue since the checkbox for recycling is by default off in the dialogue and cannot be changed.

Additionally the folder view does not update in either of these cases - so the deleted files/folders are still visible after deleting and one has to go out of the directory and back in to see the changes.

### Steps To Reproduce

1. Go to settings and turn off "Show confirmation dialogue when deleting files or folders"
2. Go to WSL and try deleting a file or directory
3. An error message stating "Failed to move N items from \\wsl.localhost\..." appears in the task log in the upper right corner 

### Expected behavior

Deletion works with the dialogue options disabled and updates the folder view as well.

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.282

### Windows Version

Windows 11 Version 21H2  OS build 22000.282 

### Relevant Assets

![image](https://user-images.githubusercontent.com/6438760/141170989-c5dfeb91-be11-4058-840f-1b661e0888e7.png)

**Comment by gave92** [comment]
Thanks for the report. The workaround for now is to press "Shift+Delete*".

**Comment by jhancuff** [comment]
Can confirm, can't permanently delete items from network shares in general if the dialog is disabled.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7500
