### ISSUE TITLE
I can't back to default, file explorer,

### ISSUE THREAD

**Issue by abdotha** [files-community/Files#6851]
### Description

I can not go back to file explorer when I active the experimental option to set this app as the default file explorer 
and when I uninstall the app the file explorer give me an error

### Expected behavior

to find a way to get back 

### Files Version

least version at 2021 11/10

### Windows Version

21H2

**Comment by gave92** [comment]
In the meantime to unset Files you'll need to run the "UnsetFilesAsDefaut.reg" from [this archive](https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip).
