### ISSUE TITLE
Using CTRL+Shift+Arrow to select text when renaming a file instead moves the focus to the navigation bar & buttons

### ISSUE THREAD

**Issue by uninvitedguest** [files-community/Files#6853]
### Description

While editing the name of a file, using CTRL+Shift+Arrow should select an entire word, instead it causes the focus of the program to jump to the nav bar buttons, ending the file renaming.

### Expected behavior

While editing the name of a file, using CTRL+Shift+Arrow should select an entire word.

### Files Version

Version: 2.0.34.0

### Windows Version

OS Version: 10.0.18363.1854

**Comment by gave92** [comment]
Merging with #6481
