### ISSUE TITLE
Using Tab when editing filenames does not move to the next file in sequence

### ISSUE THREAD

**Issue by uninvitedguest** [files-community/Files#6854]
### Description

When renaming a file, pressing the Tab key should move on to edit the name of the next file in the folder. Similarly, Shift+Tab should move to rename the previous file. They do not, instead it ends the file renaming.

### Expected behavior

When renaming a file, pressing the Tab key should move on to edit the name of the next file in the folder. Similarly, Shift+Tab should move to rename the previous file.

### Files Version

Version: 2.0.34.0

### Windows Version

OS Version: 10.0.18363.1854

**Comment by gave92** [comment]
Merging woth #6675
