### ISSUE TITLE
Feature: Improve the video control styles in the preview pane

### ISSUE THREAD

**Issue by d-a-i-m-a-j-i-n** [files-community/Files#6855]
### What's the Problem?

Video controls (in the preview pane) are too blocky. Can they have optional transparency (user can select degree of transparency?)
right now the control block covers a very large amount of the preview itself. 

### Solution/Idea

Optional transparency (user can select degree of transparency?)

### Alternatives

make the controls block resizable (with a compact mode with a very thin strip)

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.282

### Windows Version

Windows 11 Home Version - 21H2

**Comment by yaichenbaum** [comment]
@d-a-i-m-a-j-i-n can you share a screenshot?

**Comment by d-a-i-m-a-j-i-n** [comment]
Yes sure, here is a screenshot with suggestions
![preview](https://user-images.githubusercontent.com/88841201/141226960-ecd20a29-61c2-4d20-8c1a-624720a5a062.png)
:

**Comment by yaira2** [comment]
This will be implemented in the next release
