### ISSUE TITLE
UI cause chrashes

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#6856]
### Description

I tried using the new settings and properties page and click options randomly will crash files.

### Expected behavior

No crash

### Files Version

2.0.35.0

### Windows Version

10.0.19043.1237

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7516728/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7516729/debug_fulltrust.log)

**Comment by gave92** [comment]
From the log it's the Properties Customization page, if you happen to discover how to reproduce it would be great.

**Comment by josh-65** [comment]
I'm unable to produce this and probably was a one off. Possible will be fix with the redesign if there is someway of triggering it. For now I'm going to close this.
