### ISSUE TITLE
The preview pane is too small

### ISSUE THREAD

**Issue by AnharmA** [files-community/Files#6857]
### What's the Problem?

Can you make the preview pane resized larger? I want to view my PDF file without opening, but it is too small.

### Solution/Idea

Make the preview pane to be able to resize larger.

### Alternatives

Make preview pane larger

### Files Version

Version: 2.0.34.0

### Windows Version

OS Version: 10.0.22000.318

**Comment by gave92** [comment]
Merging with #6628
