### ISSUE TITLE
Layout UI：Close icon overlap About button on setting page

### ISSUE THREAD

**Issue by SudaCat** [files-community/Files#6859]
### Description

please see below png
![image](https://user-images.githubusercontent.com/34740895/141234845-c040fdcf-6cba-48d6-b4e2-741f856ba0b2.png)

### Steps To Reproduce

1. open setting page

### Expected behavior

About botton and Close icon show well

### Files Version

版本: 2.0.35.0 OS Version: 10.0.22000.258

### Windows Version

版本	Windows 11 专业版 版本	21H2 安装日期	‎2021/‎10/‎9 操作系统版本	22000.258 体验	Windows 功能体验包 1000.22000.318.0

**Comment by yaichenbaum** [comment]
This issue is resolved with #6858.
