### ISSUE TITLE
Add Rotate left/right to the toolbar for image files

### ISSUE THREAD

**Issue by MidoSpace** [files-community/Files#6861]
### What's the Problem?

Image files are among most important file types for any computer users, and for photographers, graphic designers and even for normal user who deal with photos productivity is essential..

When we have a rotated image, we need a fast way to rotate it. In the past we had to open the photo with a photo editor to do the job then save the edited copy. Later, in Windows XP we got Windows Photo and Fax Viewer which had fast editing features as buttons (rotate left, right, set as desktop background). This feature became a default one in all later Windows releases, and that what Files lacks..

### Solution/Idea

For productivity, please add Rotate Left and Rotate Right buttons to the toolbar those appear/be clickable upon selecting a single or multiple image file(s) just like in Windows Explorer.

### Alternatives

Alternatives are already there. By clicking More from the context menu we get Rotate left/right options.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

v2.0.34.0

### Windows Version

Windows 11 21H2 22000.318

**Comment by puppetsw** [comment]
Happy to take this one on.

**Comment by puppetsw** [comment]
Would this be better served as a flyout button with the 2 options for rotating? Rather than 2 individual buttons on the toolbar.

**Comment by d2dyno1** [comment]
@MidoSpace This has been resolved with #7832
