### ISSUE TITLE
Cannot sort foldes and files by folder first

### ISSUE THREAD

**Issue by richwxd** [files-community/Files#6862]
### Description

As windows explorer and rxexplorer (similar software from windows store), when a user open a folder, all folders are sorted first, then files. But in Files, folders and files are mixed.

### Steps To Reproduce

1. open a folder
2. see folders and files

### Expected behavior

Folders are sorted first then files

### Files Version

2.0.34.0

### Windows Version

Windows 11 21H2 22000.318

**Comment by gave92** [comment]
You can find the option in Files Settings > Files and folders > "Sort folders alongside files"
