### ISSUE TITLE
I cant disable experimental feature 

### ISSUE THREAD

**Issue by Riciard52** [files-community/Files#6863]
### Description

i cannot turn off set files as default files explorer

### Expected behavior

i expectet to disable taht 

### Files Version

2.0.3

### Windows Version

11 last update

**Comment by BanCrash** [comment]
Hi, you have to follow the instructions here to unset as default file explorer:

https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip

TL;DR: download [this zip](https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip) and run UnsetFilesAsDefault.reg to restore windows explorer
