### ISSUE TITLE
Security settings in Program Folder

### ISSUE THREAD

**Issue by Liguma** [files-community/Files#6864]
### Description

If I add a user to a folder in "C:\Program Files" via "properties>security", assign permissions and click OK nothing happens.

### Steps To Reproduce

1. Go to c:\Program Files\
2. Select properties of a Folder
3. Select security
4. Select + and add everyone
5. select everyone and choose full control
6. click OK
<img width="300" alt="2021-11-11_13-12-12" src="https://user-images.githubusercontent.com/24432099/141296155-74a2ff27-e36d-4418-bd84-b2eb6b6ba83b.png">

### Expected behavior

Add new user and chosen security should be added

### Files Version

v2.0.34.0

### Windows Version

Windows 11 Pro 22000.318

**Comment by Josh-65** [comment]
Merging with #7358
