### ISSUE TITLE
When start favorites are hidden even when they are unfolded

### ISSUE THREAD

**Issue by artscer** [files-community/Files#6865]
### Description

When I start Files each time I've to folde and unfold the favorites (and some times others such as cloud drives) in order to access them, watch the video so you can understand.

### Steps To Reproduce

1. Start Files
2. Unfold Favorites
3. Close Files
4. Open Files Again
5. Favorites are hiden
6. you need to click twice on favorites in order to access them.

### Expected behavior

If i unfold the favorites and close the program an reopen again they should be visible.

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.282

### Windows Version

Version	10.0.22000 Build 22000

### Relevant Assets

https://user-images.githubusercontent.com/52377122/141315834-aa5c96d3-0a4d-48ec-bf5a-006138850413.mp4

**Comment by gave92** [comment]
Thanks for the report. It's like the icon is correct but the section is still collapsed. Merging with #5676.
