### ISSUE TITLE
trying to copy files into hard drive

### ISSUE THREAD

**Issue by AnthonyPreite** [files-community/Files#6866]
### Description

I was trying to copy files into new folder in one of my hard drives, and my hard drives disappeared ...

### Steps To Reproduce

idk if you can reproduce it, but it happened while i wanted copy files into one hard drive

### Expected behavior

I would get my hard drive section cause since the bug, it not there anymore

### Files Version

Version : 2.0.34.0 OS Version: 10.0.19042.1320

### Windows Version

Windows 10 pro

**Comment by gave92** [comment]
Thanks for the report. Could you post the app's log files?
You can get them from `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` (debug.log + debug_fulltrust.log)

Do you mean that the drives section does not appear in Files sidebar anymore? If so, could you also post a screenshot of Files sidebar?

**Comment by AnthonyPreite** [comment]
Hello,
yeah it's in sidebar, My drives didn't appear anymore.
I tried to screen the sidebar bug but i think that in starting my pc today, it resolved the bug. 
There, i give you the Log files :)

[debug.log](https://github.com/files-community/Files/files/7527180/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7527181/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
@gave92 can we add this to the backlog?

**Comment by gave92** [comment]
@AnthonyPreite glad the issue fixed itself ;) Please let us know if it happens again.
