### ISSUE TITLE
Add a keyboard shortcut to show hidden files

### ISSUE THREAD

**Issue by ferrazpedro** [files-community/Files#6867]
### Solution/Idea

I think it would be a pretty good idea to have a shortcut to toggle if hidden files are show. I use this a lot in Linux and would be awesome to have this in Files too! Some suggestions of key binds would be "ctrl + h" or "ctrl + shift + ."

### Alternatives

To be honest, I don't know what would be an alternative.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.0.33

### Windows Version

Windows 11 21H2 22000.282

**Comment by yaichenbaum** [comment]
@ferrazpedro this issue should be resolved with #7106.

**Comment by ferrazpedro** [comment]
Why was this option removed?

**Comment by yaichenbaum** [comment]
> Why was this option removed?

The author didn't provide permission when we relicensed under MIT so we had to remove their change.

**Comment by ferrazpedro** [comment]
Could I submit this change myself? Or would it be a problem?

**Comment by yaichenbaum** [comment]
> Could I submit this change myself? Or would it be a problem since it would be similar to the previous one?

I think that's okay, just as long as it's not a direct copy

**Comment by yaichenbaum** [comment]
This issue should be resolved with #9648
