### ISSUE TITLE
Mass conflict actions when copy-pasting

### ISSUE THREAD

**Issue by maicol07** [files-community/Files#6869]
### What's the Problem?

When I have a lot of files to replace when copy-pasting I get bored of setting every file to "Replace" or "Skip"

### Solution/Idea

Add an option of the top to apply an action to every element and also a checkbox before the list elements and a button to change the action of the selected files

### Alternatives

Setting every single file, but it is boring if you have a lot of files that conflicts

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to resolve conflicts faster | Must |

### Files Version

2.0.35

### Windows Version

Windows 11 Pro 22499.1000

**Comment by yaichenbaum** [comment]
You can select multiple items (ctrl + click) and right click them to take the same action.
