### ISSUE TITLE
Feature: Setting to stop folders from auto-reloading (global & folder specific)

### ISSUE THREAD

**Issue by m1karii** [files-community/Files#6870]
### What's the Problem?

I have this folder where I often download to. The download process is dividing file into very small parts (few KB /MB) downloading them separately and then putting them back together. because of these very small files the folder auto-reloads every second or two which makes it unbrowsable for the duration of downloading.

### Solution/Idea

Setting to stop folders from auto-reloading (global & folder specific)

### Files Version

Latest

**Comment by yaira2** [comment]
@m1karii this is an interesting use case, how do you work around this limitation in File Explorer?

**Comment by m1karii** [comment]
wdym @yair100 ?
File Explorer doesn't auto-reload (as of Windows 10 21H2 - which I'm using)

**Comment by yaira2** [comment]
Creating a new file externally will automatically update the list in File Explorer.

**Comment by m1karii** [comment]
cannot confirm

**Comment by yaira2** [comment]
Steps to confirm
1. Open Files and File Explorer to the same directory
2. Create a new file from Files and see if it's displayed in File Explorer

**Comment by Josh65-2201** [comment]
I have a different thing creating and removing a file constantly, I assume it causes the same effect. File explorer doesn't show the file but Files quickly shows and removes it. Could be that File explorer wait for a second to see if the file stays if it's not made/edited in it, before refreshing.

**Comment by yaira2** [comment]
That might be possible 👍

**Comment by superluig164** [comment]
I get a similar issue, nearly any folder on external storage does this, and sometimes on internal as well when moving/deleting/modifying a lot of files at once.  File explorer doesn't exhibit the same behaviour (sometimes it just doesn't refresh until manually refreshing which is the opposite problem) but I would argue File explorer's behaviour is a little more desirable here, if the bug proves too difficult to track down and fix right away.

**Comment by superluig164** [comment]
Here's an example of it happening to me, when deleting one single file from external storage.

https://github.com/files-community/Files/assets/13702255/9eb77847-160e-4f40-a00a-c1a96e5da462

**Comment by superluig164** [comment]
Sorry for the slight spam, but here's another example of how unpleasant this can be, especially when the files change a lot.  Here's me clearing out the same folder.

https://github.com/files-community/Files/assets/13702255/6699b0f5-7442-4e40-ac23-d1c70236130a

**Comment by koppor** [comment]
Even if the folder refreshes, it should stay at the currently marked file and not jump "randomly".

My use case is that a script renames hundreds of files in a folder - and I want to sort the renamed files. I can sort, because I rename "IMG*" to "YYYY-MM-DD" and thus, the new files are at the top of the directory.

This issue also refs https://github.com/files-community/Files/issues/4214

**Comment by yaira2** [comment]
Thank you for your feedback, we're going to continue tracking this issue in #4214.

**Comment by yaira2** [comment]
The underlying issue is same that the list gets reordered when an item is added or renamed.
