### ISSUE TITLE
Feature: Add support for setting the default folder thumbnails

### ISSUE THREAD

**Issue by m1karii** [files-community/Files#6871]
### Solution/Idea

Add a setting to allow users to set the default thumbnail for folders, but also continue to allow users to override the default for individual folders regardless of the setting.

### Files Version

Latest

**Comment by yaichenbaum** [comment]
@m1karii this is already supported, you can right click in the directories and customize the icons from the properties dialog.

**Comment by m1karii** [comment]
> @m1karii this is already supported,

Incorrect. what is supported is manually changing icons of folders on per folder basis.

What I'm proposing is 'icon themes' - ability to load in a .dll / .zip / directory with icons used by Files app other than directory / file icons (but including library + downloads + desktop icons). By this I mean icons like "Home", "Favorites", drives, bin, library icons, ...

![image](https://user-images.githubusercontent.com/82673417/141648699-1003d76d-3a4a-4645-8826-6883fd578cde.png)
![image](https://user-images.githubusercontent.com/82673417/141648734-cb171b03-060f-454d-a8af-6ce42b81b4b2.png)

As mentioned above I know there are means to patch these icons on OS level but that's not what i'm looking for

**Comment by m1karii** [comment]
@yaichenbaum reopen?

**Comment by yaichenbaum** [comment]
We don't have plan to implement this.

**Comment by m1karii** [comment]
> We don't have plan to implement this.

That's kinda the reason why I opened this issue. So people can upvote it and you implement it...

To make UI more customisable. Again - I know that there are means to patch these on OS level but these means require 3rd party closed-source tools. And the default win 10 icons dont go well with Files UI.

**Comment by yaichenbaum** [comment]
> Again - I know that there are means to patch these on OS level but these means require 3rd party closed-source tools. And the default win 10 icons dont go well with Files UI.

We try to stay away from modifying the system as much as possible as patching the OS can have unexpected side effects and we don't want to take that risk. I agree that the Windows 10 icons don't look the best, but you can already customize the main folders and use whatever icon you want. We feel that this is the best compromise between customization and stability on the OS.

**Comment by TizianoMad** [comment]
Installing themes works just the same for both original file explorer & Files.
I used "iPack Builder" (for v1809 & >) for just changing icons (or "7tsp" for v1903 & <)
Though, I don't know how the system will react when patching higher changes on "file explorer" design (XtremPatcher).
This new one with "Files" is so perfect and ample !

**Comment by m1karii** [comment]
> > Again - I know that there are means to patch these on OS level but these means require 3rd party closed-source tools. And the default win 10 icons dont go well with Files UI.
> 
> We try to stay away from modifying the system as much as possible as patching the OS can have unexpected side effects and we don't want to take that risk. I agree that the Windows 10 icons don't look the best, but you can already customize the main folders and use whatever icon you want. We feel that this is the best compromise between customization and stability on the OS.

@yaichenbaum, I don't think you understood. What I meant was:
I know that there are means to patch icons on OS level, however I'd consider these means only if the patching tools were open source - which they are not. So I'm asking you to add an ability to change icons on Files app level only. Example of implementing this would be Files creating its own copy of icons from system DLLs which would be stored as let's say extracted from DLL into ZIP file and this ZIP file 'd be stored in Files installation subdirectory (like with themes). By adding another ZIP-icon theme into same subdirectory we'd be able to change the icon theme displayed by Files in the settings menu (like with themes). of course everything else 'd stay as it is: same thumbnails for files (as before) 'd be displayed, if folder has a desktop.ini/custom icon, that one would be used. The target of this feature is added UI customizability inside Files primarily targetting icons like 'drive', 'recycle bin', 'favourites' and others as seen in https://github.com/files-community/Files/issues/6871#issuecomment-968082919, which can't be changed as easily as folder icons.

**Comment by yaichenbaum** [comment]
@m1karii I added this issue to the backlog 👍

**Comment by yaira2** [comment]
Thank you for your feedback, we're going to continue tracking this request in #10941. You can add a comment or click subscribe to be notified of updates.
