### ISSUE TITLE
explorer.exe error/crash in safe mode even after disabling "Set Files as default file explorer (EXPERIMENTAL)"

### ISSUE THREAD

**Issue by HammerOfDaGods** [files-community/Files#6873]
### Description

I know the replacement feature is experimental. I just want to report the issue. If you happen to know how to fix it I would greatly appreciate that information. Also, I am on WIndows 11.

After installing Files and enabling the explorer replacement feature (EXPERIMENTAL), when booting into safe mode with in enabled it completely breaks the task bar, start menu, explorer, etc. Anything tied to the explorer.exe is frozen, nonfunctional, or missing entirely. If Files explorer replacement feature is disabled, the regular explorer.exe will work normally for about 10 seconds before giving an error.

_"The system detected an overrun of a stack-based buffer in this application. This overrun could potentially allow a malicious user to gain control of this application."_

Then if you click okay the explorer.exe restarts and repeats the cycle.

### Steps To Reproduce

1. Install Files
2. Open Files settings, go to the experimental section, and enable "Set Files as default file explorer"
3. Open system configuration or run mscofig, go to the boot section, and enable safe mode
4. Restart. (Completely broken explorer)
5. To return to normal boot, hit win+r then run "msconfig" and disable safe boot.
5. To reproduce error, boot normally, disable "Set Files as default file explorer", and repeat steps 1-4

### Expected behavior

If the feature is left enabled, explorer.exe (task bar, start, file explorer) will be nonfunctional. If the setting is disabled the explorer.exe will be mostly functional until getting the error.

### Files Version

2.0.34.0

### Windows Version

10.0.22000.318 (Windows 11)

**Comment by Arvind11747** [comment]
Same thing here, I cannot disable the Experimental feature, and it breaks the windows file explorer in multiple areas.

**Comment by yaichenbaum** [comment]
@HammerOfDaGods did you revert the changes before trying to open explorer in safe mode?

**Comment by HammerOfDaGods** [comment]
@yair100 Yes. As I said above, the program causes issues with the feature enabled or disabled.

DISABLED - "If Files explorer replacement feature is disabled, the regular explorer.exe will work normally for about 10 seconds before giving an error." and then crashes and restarts as stated in the report.

ENABLED - "when booting into safe mode with in enabled it completely breaks the task bar, start menu, explorer, etc. Anything tied to the explorer.exe is frozen, nonfunctional, or missing entirely."

When the feature is disabled I don't see why it should effect the default explorer. Turning off the feature is supposed to revert any registry changes which should undo any interference. I understand that leaving it enabled should not work considering what safe mode is meant for. However, if this feature is going to be included it shouldn't completely break under these circumstances, it should just revert to the original explorer.exe. In a situation where a user could not boot normally to disable the feature, the user would be pretty much out of luck unless they have another way to navigate (command line, run, etc).

**Comment by HammerOfDaGods** [comment]
@Arvind11747 Our issue is a little different. I can disable the feature, which has issues of it's own, but when enable yes, same issue. Multiple, possibly all, elements of the default explorer.exe (taskbar, file explorer, etc) break completely.

**Comment by Xavi3RElvis** [comment]
Whatever registry changes are applied for this to work, can they not work in reverese for the default file explorer?
The file browsing state left behind when removing the app is completely broken

**Comment by HammerOfDaGods** [comment]
Would it be possible to have a button or tool to completely undo any changes made by Files' features and installation? I like the app, and I will continue using it, but it modifies essential functions of Windows, and at this point I'm afraid to remove it out of fear it will permanently break, or at the very least adversely affect, the default explorer.exe . I would feel a lot better having something to use in case of emergencies, at least in the mean time until you have time to squash this bug.

**Comment by yaichenbaum** [comment]
> Would it be possible to have a button or tool to completely undo any changes made by Files' features and installation? I like the app, and I will continue using it, but it modifies essential functions of Windows, and at this point I'm afraid to remove it out of fear it will permanently break, or at the very least adversely affect, the default explorer.exe . I would feel a lot better having something to use in case of emergencies, at least in the mean time until you have time to squash this bug.

@HammerOfDaGods we don't recommend using experimental features on your main device. Turning off the option should revert all the changes, we're not sure why it's not working for you but we're looking into it. We're also working on automatically reverting the changes if someone uninstalls Files.

**Comment by yaichenbaum** [comment]
> Whatever registry changes are applied for this to work, can they not work in reverese for the default file explorer? The file browsing state left behind when removing the app is completely broken

@Xavi3RElvis did you revert the changes before removing Files?

**Comment by Xavi3RElvis** [comment]
Not only does it not revert anything for me but the button cannot get deactivated at all.
Clicking teh switch does nothing adn always stays at the on state while also fixing nothing regarding registry file explorer defaults

**Comment by yaichenbaum** [comment]
> Not only does it not revert anything for me but the button cannot get deactivated at all. Clicking the switch does nothing and always stays at the on state while also fixing nothing regarding registry file explorer defaults [screen recording of behavior](https://we.tl/t-6PeB5e4JxY)

@Xavi3RElvis did you revert the changes before removing Files? There is bug in the current release (which has been fixed in `main`) that the script to undo the changes wasn't kept if the app was removed before the changes were undone.

**Comment by Xavi3RElvis** [comment]
Hmm I might have uninstalled before setting the feature to off. So this is already a known and resolved issue?

**Comment by yaichenbaum** [comment]
> Hmm I might have uninstalled before setting the feature to off. So this is already a known and resolved issue?

@Xavi3RElvis yes, it will be included in the next update.

**Comment by BanCrash** [comment]
> Hmm I might have uninstalled before setting the feature to off. So this is already a known and resolved issue?

@Xavi3RElvis in the meantime you can follow the instructions here to unset as default file explorer:

https://files.community/docs/configuring/replace-file-explorer

TL;DR: download [this zip](https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip) and run UnsetFilesAsDefault.reg to restore windows explorer

**Comment by Xavi3RElvis** [comment]
The reg setting did work, thank you for that

**Comment by yaichenbaum** [comment]
@HammerOfDaGods is this still an issue after running the script?
