### ISSUE TITLE
Sidebar to big, too much lost space

### ISSUE THREAD

**Issue by MonsieurZed** [files-community/Files#6875]
### What's the Problem?

Hi, 
I love your app it's truly great but i have a small screen (1080p 13"), would it be possible to get a compact view mode ?
Here is what i see
<img width="960" alt="2021-11-12 18_18_01-2021-11-12 17_50_17-Discord png @ 176% (Layer 18, RGB_8) _" src="https://user-images.githubusercontent.com/18287008/141434133-bae4e89e-2475-430c-83c0-a6a99f1d9167.png">
 
But really your work is amazing ! Keep it going !

### Solution/Idea

Here is what i dream for
![2021-11-12 17_50_17-Discord](https://user-images.githubusercontent.com/18287008/141436117-d0ea25e6-c1ba-4736-b0aa-64f71b77e32b.png)

I could fit 3 more item in the list just by making the top menu smaller. You save a lot more with minimizing each item in the list. 

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22499.1000

### Windows Version

Win11 DEV BUILD 22499.1000

**Comment by yaichenbaum** [comment]
Merging with #1940
