### ISSUE TITLE
Checkbox's security Tab

### ISSUE THREAD

**Issue by Liguma** [files-community/Files#6877]
### Description

Checkbox's on security tab have a strange behaviour - see attached video

https://user-images.githubusercontent.com/24432099/141450832-1edab1b6-5830-46b8-a4af-fc1ce055ea85.mp4

### Expected behavior

checkbox's on security tab should work as expected

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.318

### Windows Version

Windows 11 pro

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview build? https://files.community/download/preview
