### ISSUE TITLE
Letter related search

### ISSUE THREAD

**Issue by ZoroNasr** [files-community/Files#6879]
### Description

When I press on a letter like (P) when opening the folder, it is supposed to go over all files or folders starting with the letter. It doesn't, sometimes it would go over one or two files and ignore the rest

### Expected behavior

When pressing any letter, the select should start to alternate between all files or folders starting with that letter

### Files Version

V 2.0.34.0 

### Windows Version

Edition	Windows 11 Pro Version	21H2 OS build	22000.318

**Comment by yaichenbaum** [comment]
This issue is resolved in `main`.
