### ISSUE TITLE
Display size of folder 

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#6880]
### What's the Problem?

It is not practical to know the total size occupied by a folder. You have to select one, open its property panel, and wait for the calculation. It is therefore not easy to spot a folder whose size is larger than desired. 

### Solution/Idea

Display the size of the folders in the size column of the detail view, in the preview pane and/or in the bottom description, with an asynchronous calculation as in the properties panel. As this can affect performance and disk access, this should be an option disabled by default. This option can be in the settings (with a warning description) or in the layout menu of the toolbar.

### Alternatives

In the size column, display a button for show the size of folder.

### Files Version

v2.0.33.0

### Windows Version

Windows 11

**Comment by gave92** [comment]
Merging with #3944
