### ISSUE TITLE
Open dual pane mode 50/50% by default

### ISSUE THREAD

**Issue by LeWshA88** [files-community/Files#6883]
### Description

Hello! It is very convenient for me to work in dual mode, but when turned on, it opens in sizes 70% by 30% screen 1  ( https://1drv.ms/u/s!AmiFAYn9wCP6gU9iaaIkfOHZKbVh ) How to make h 50/50% as in screen 2 ( https://1drv.ms/u/s!AmiFAYn9wCP6gVCNP9WLRntyD9XT )

### Expected behavior

50|50

### Files Version

 2.0.34.0 OS Version: 10.0.19042.1288

### Windows Version

Widows 10 20H2 19042.1288

**Comment by d2dyno1** [comment]
You can adjust the size by holding and dragging the pane splitter.
![image](https://user-images.githubusercontent.com/53011783/141532803-efdd48ff-5d7c-4c20-b30d-390eefa16b05.png)

**Comment by dansauve** [comment]
+1 from me. I'm glad to see this was reopened... Having used dual-pane file managers for many years this drives me nuts to the point that Files is unusable to me because it drives me crazy! Hope to see a change in a future version
