### ISSUE TITLE
Feature: Add swipe gesture to switch between tabs

### ISSUE THREAD

**Issue by Pein57** [files-community/Files#6884]
### What's the Problem?

Hi !
It would nice to scroll through the tabs easily.

### Solution/Idea

It can be possible to swip with two fingers to scroll through the tabs.

### Alternatives

It can be combined with the fact of typing on keys at the same time like the tab key for example.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

v2.0.34.0

### Windows Version

Windows 11 21H2 22000.282

**Comment by yaira2** [comment]
@Pein57 thank you for your feedback, can you share more about your use case for this gesture and how it would be an improvement over clicking the tab?
