### ISSUE TITLE
Increase file name display in small icons layout

### ISSUE THREAD

**Issue by Pein57** [files-community/Files#6885]
### What's the Problem?

In small icons layout if the name of several files is long and only the last characters change, it is difficult to know which file it is.

### Solution/Idea

Increase file name display  with adding two or three lines of text.

### Alternatives

I have no alternatives ideas.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

v2.0.34.0

### Windows Version

Windows 11 21H2 22000.282

**Comment by yaichenbaum** [comment]
Merging with #1033.
