### ISSUE TITLE
Accent color clashing with button background color in the properties dialog

### ISSUE THREAD

**Issue by cleuton4k** [files-community/Files#6886]
### Description

confirmation button is blurred, cannot see confirmation word OK.

### Expected behavior

clearly show the OK button.

### Files Version

2.0.34

### Windows Version

windows 10 home 64 bits 21h1

### Relevant Assets

[debug_fulltrust.log](https://github.com/files-community/Files/files/7530648/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7530649/debug.log)

![1](https://user-images.githubusercontent.com/90144967/141540802-3ece8e9d-1e47-4c3b-acf2-bd9d7175bf29.jpg)
![SharedScreenshot](https://user-images.githubusercontent.com/90144967/141540805-6ff6a88d-2530-406f-ae97-1db51a87ed93.jpg)

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.

**Comment by yaichenbaum** [comment]
@victoriadealba are you still looking for something to work on?
