### ISSUE TITLE
black square around folder icons

### ISSUE THREAD

**Issue by cleuton4k** [files-community/Files#6887]
### Description

the black squares around the folder icons only disappear when I refresh the page

### Expected behavior

no black square around folder icons

### Files Version

2.0.34

### Windows Version

windows 10 home 64 bits 21h1

### Relevant Assets

[debug_fulltrust.log](https://github.com/files-community/Files/files/7530750/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7530752/debug.log
![00](https://user-images.githubusercontent.com/90144967/141551744-b8e447b6-7718-47ea-ac3d-cf1a449ceb7f.jpg)
)

**Comment by gave92** [comment]
Merging with #6373
