### ISSUE TITLE
Shutdown after copy

### ISSUE THREAD

**Issue by xmha97** [files-community/Files#6889]
### What's the Problem?

Add an option to turn off the computer after copying is complete

### Solution/Idea

![image](https://user-images.githubusercontent.com/23485114/141599302-faa745d5-ccc6-477f-ac90-26cfc4cef17a.png)

### Alternatives

TeraCopy
![image](https://user-images.githubusercontent.com/23485114/141599629-26740cfd-b512-430f-9922-0da828430e52.png)

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

v2.0.35.0

### Windows Version

Windows 11 21H2 22000.318

**Comment by yaichenbaum** [comment]
@xmha97 while this is an interesting idea, it's a bit out of scope for plans for Files. We are looking into adding support for TeraCopy but nothing is final yet.
