### ISSUE TITLE
Can't delete icon from /Users/Public/Desktop

### ISSUE THREAD

**Issue by Crwmy** [files-community/Files#6890]
### Description

Some programs create a desktop icon on the Public Desktop. I do delete these icons. This action requires admin rights. Which Files prompted for. Despite giving the elevated rights, the deletion is failing. 

### Steps To Reproduce

1. (Have a installer with elevated rights) Create an icon at C:\Users\Public\Desktop
2. Try to delete that icon within a standard account using Files
3. Files prompts that that action requires administrator rights
4. The task is already marked as failed in the ongoing tasks indicator
4. Accept and grant elevated rights via UAC
5. Nothing further happens

### Expected behavior

Icon is deleted from C:\Users\Public\Desktop.

### Files Version

2.0.34

### Windows Version

22000.318

### Relevant Assets

![image](https://user-images.githubusercontent.com/91319158/141603990-d20bb68a-5bd4-410f-a350-31a6f91f0967.png)
[Files2034_log_crwmy_6890.zip](https://github.com/files-community/Files/files/7531332/Files2034_log_crwmy_6890.zip)

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
