### ISSUE TITLE
filesfulltrust stopped working

### ISSUE THREAD

**Issue by alx359** [files-community/Files#6891]
### Description

An "filesfulltrust stopped working" issue always happens when trying to delete some files in `/Program Files`, for example. 

### Steps To Reproduce

While reviewing a similar file manager alternative learned that this may follow from given [limitations of MS Store-installed apps](https://onecommander.com/store-limitations.html). Indeed, installing from the github zip instead seems to have fixed the issue so far.

### Expected behavior

"filesfulltrust stopped working" no more of course, with perhaps a way to address such permission limitations with some additional configuration after install. At minimum, make the zip download available at the [official website](https://files.community/) with some extra information of the limitations of the Microsoft Store version.

### Files Version

Version: 2.0.34.0

### Windows Version

10.0.19043.1348

**Comment by yaichenbaum** [comment]
@alx359 can you upload the log files? You can find them from the about page in the settings dialog.

**Comment by alx359** [comment]
I'm sorry, this and other issues still continued one way or another and I'm not using Files atm.

**Comment by yaichenbaum** [comment]
> I'm sorry, this and other issues still continued one way or another and I'm not using Files atm.

@alx359 we'd really to like to find out what went wrong here even if you aren't using Files anymore so if you get a chance to upload the Files, it would be a big help 🙂
