### ISSUE TITLE
Unreadable text in the  file's properties/info box.

### ISSUE THREAD

**Issue by Nalser3200** [files-community/Files#6892]
### Description

My computer set with dark mode with the Files set with a light theme, and when I click the Properties/Info button of a folder/file, the words inside will not be in contrast and makes the words unreadable.
But the bug did not appear if I set the Files theme to dark mode with Windows set to dark mode.

### Steps To Reproduce

1. Open Files app
2. Right-click a file or folder
3. Click the info/Properties "i" icon

### Expected behavior

The words should be readable and in contrast with the background.

### Files Version

v2.0.34.0

### Windows Version

Windows 11 21H2 22000.318

### Relevant Assets

![Files Text Unreadable bug](https://user-images.githubusercontent.com/93972566/141611332-4266f1fb-44cd-42a2-b9c4-bb1ae8f29191.png)
[debug.log](https://github.com/files-community/Files/files/7531625/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7531626/debug_fulltrust.log)

**Comment by gave92** [comment]
Merging with #6066
