### ISSUE TITLE
Can't turn off Files as Default file manager

### ISSUE THREAD

**Issue by ekeppel** [files-community/Files#6895]
Windows 11 build 22000.318

Turning off the experimental switch for making Files the default file manager in settings does not work.  I get a UAC prompt and it attempts a registry change, however the slider goes right back to 'enabled' in the Files app, and Files remains the default file manager.  

I've tried rebooting the PC, repairing and resetting the app, as well as removing and reinstalling the Files App, but the slider won't stay off and is failing to revert the default file manager setting.  This leaves the system unable to use the original File Explorer at this point, no matter what I do.

Though an experimental feature, using it should not bork the system in such a way that the changes can't be reversed.

Please provide the exact registry changes needed so that we can manually make these changes ourselves when the app fails to make them properly.

**Comment by Crwmy** [comment]
Hello @ekeppel,
you can find the exact registry entries on the documentation where also a PowerShell Script is provided to revert the change and set Windows Explorer as default: https://files.community/docs/configuring/replace-file-explorer

I hope this helps!

**Comment by DanielHabenicht** [comment]
I've been running into the same problem. Can we reopen, to make the switch actually work? Or at least add a link to the option so others don't have to search the internet for it?

**Comment by BanCrash** [comment]
> I've been running into the same problem. Can we reopen, to make the switch actually work? Or at least add a link to the option so others don't have to search the internet for it?

Hi, the switch is already fixed in last insider version. The link is on the documentation, which has a link on the about settings page, as part of the useful links.

**Comment by DanielHabenicht** [comment]
Ahh, cool. Thx @BanCrash 

Just for any future reference: https://github.com/files-community/Files/issues/6729
