### ISSUE TITLE
Crash when opening Videos folder in Library

### ISSUE THREAD

**Issue by patrickxfranco** [files-community/Files#6896]
### Description

When specifically entering the Videos folder within the File Library, Files presents a Crash, this also occurred once in the Pictures folder.

### Steps To Reproduce

1. Open Files
2. If the Library section is enabled, expand it
3. Select the 'Videos' folder
4. After opening Files it will crash.

https://user-images.githubusercontent.com/52086621/141643799-bd04196c-a39a-4f1f-926c-c40683bc733a.mp4

### Expected behavior

I expected that when opening any folder within Files it would not crash and correctly display all the files in the folder.

### Files Version

Versão: 2.0.34.0 OS Version: 10.0.19043.1348

### Windows Version

Windows 10 Pro 21H1 19043.1348

**Comment by yaichenbaum** [comment]
@patrickxfranco can you upload the log files?
