### ISSUE TITLE
Add customizable shortcuts to navigate to different directories

### ISSUE THREAD

**Issue by Visual-Dawg** [files-community/Files#6900]
### What's the Problem?

Navigating Windows can be quite slow.

### Solution/Idea

Adding the option to define custom shortcuts to folder-paths.

Also adding CLI functionality to control Files would be awesome. This could then be used by Autohotkeys.

### Alternatives

Using AutoHotkey to create shortcuts myself. However, this should open a new window every time a custom shortcut is used.

### Priorities

| Capability | Priority |
| Custom shortcuts | Must |
| CLI control | Could |

### Files Version

V2

### Windows Version

Windows 11

**Comment by yaichenbaum** [comment]
@v-dawg what kinds of shortcuts are you looking for?

**Comment by v-dawg** [comment]
General shortcuts to folders like:
- Download
- Root
- User-Home
- Desktop
- Program Files folders
- And shortcuts to pinned favourites

Then custom ones like:
- Secondary hard-drive root
- project folder I currently use for work
- main folder for work
- folder for my personal projects

**Comment by yaichenbaum** [comment]
@v-dawg I really like this idea! Adding it to the project board.

**Comment by schroef** [comment]
Coming from OSX and using DefaultFolder X, i really miss this feature on Windows. Have not found an app which is similar, one which is close is Listrary, but this always crashes and the dev took of or something.

For DefaultFolder X, you can add folders en add any shortcut to it, another option it has is using sets. Sets are basically different set of shortcuts, this makes it very expanded.

![Screen Shot 2021-11-29 at 10 40 48](https://user-images.githubusercontent.com/6923008/143887816-36755a5d-7e76-4901-959b-4277281a9be6.png)

**Comment by yaira2** [comment]
Thank you for your feedback, we're going to continue tracking this together with #13251. You can add a comment or click subscribe to be notified of any updates.
