### ISSUE TITLE
Cannot continue with the folder tree in columns layout after relaunching Files

### ISSUE THREAD

**Issue by XuShenLZ** [files-community/Files#6902]
### Description

I always admire the "columns layout" of the file explorer in Mac system. Now I can finally use it with Files! When seeing this feature in Files v2, I immediately switched to Files as my default explorer as a **paid Directory Opus user for years**!

However, I found that with columns layout, you cannot continue with the entire folder tree after relaunching Files. 

In "Setting -> On Startup -> When launching Files", I choose "Continue where you left off".

![image](https://user-images.githubusercontent.com/31999415/141657537-c902beae-bf6a-44e5-add8-4d1ab2fcb138.png)

Then I navigate a few levels down through my disk with "Columns Layout". In the example below, I start the tab with "Downloads", and navigate to "Downloads/DiskGenius/docs". But the title of this tab is still "Downloads".

![image](https://user-images.githubusercontent.com/31999415/141657579-d522a08c-8882-41c4-9998-ee66a89cb101.png)

So when I exit Files and relaunch it, it only start with the "Downloads" and I have to navigate to all subfolders again.

![image](https://user-images.githubusercontent.com/31999415/141657649-80dbf7f6-6b34-405f-9383-b4561df239ac.png)

### Steps To Reproduce

1. Go to "Setting -> On Startup -> When launching Files"
2. Select "Continue where you left off"
3. Open a new tab and start with a "root" location
4. Select "Columns" Layout
5. Navigate down a few subfolders
6. Close Files
7. Relaunch Files
8. I can only get the "root" location back, not the last subfolder I have visited

### Expected behavior

Files should remember the expanded folder tree in columns layout. After exiting Files and relaunch, I should have the entire folder tree back, rather than the root folder only.

### Files Version

2.0.34.0

### Windows Version

Windows 11 Pro 21H2 22000.318

**Comment by sstavridis** [comment]
Is there any way to apply the columns layout to be the default view for all the folders?
For example in File Explorer you can go to view and select Large Icons then you can to Options and on the View tab you check Apply to folders.

**Comment by Josh-65** [comment]
Is this still an issue?

**Comment by XuShenLZ** [comment]
Yes. Everytime I close and restart Files, the folder tree in column layout will root from the latest folder. The entire tree is not preserved
