### ISSUE TITLE
Can't open network drive.

### ISSUE THREAD

**Issue by BaekDoctor** [files-community/Files#6903]
### Description

I can't open network drive.

### Steps To Reproduce

1. Open any Network Drives (except Network)
2. See the error Drive Unplugged NotAFolder

### Expected behavior

Drive Unplugged NotAFolder
![image](https://user-images.githubusercontent.com/82074517/141665124-1f0ddbdc-3363-4207-bf37-dfa7606c644e.png)

### Files Version

Version: 2.0.34.0

### Windows Version

OS Version: 10.0.22499.1010

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview build? https://files.community/download/preview
