### ISSUE TITLE
Every folder will create the same file "desktop.files.json"

### ISSUE THREAD

**Issue by 00LT00** [files-community/Files#6904]
### Description

After I upgrade to version v2.0.34.0, no matter what folder I open, a file will be automatically created.
![image](https://user-images.githubusercontent.com/47566260/141666327-c8bfabea-138f-48df-a6ff-403e389214fa.png)

### Expected behavior

This file should not be created.

### Files Version

v2.0.34.0

### Windows Version

Win11 10.0.22000.282

**Comment by yaichenbaum** [comment]
This issue is resolved in `main`.

**Comment by 00LT00** [comment]
> This issue is resolved in `main`.

Thanks for reply. I hope to release the new version early.
