### ISSUE TITLE
Files crashed when looking at a folder that has files being actively being written to

### ISSUE THREAD

**Issue by chvvkumar** [files-community/Files#6905]
### Description

Had a folder open in files (files is set as the default exporer replacement). I was copying and converting some audio files in this folder while files was open on this folder. Then it crashed.

### Expected behavior

Application should not crash

### Files Version

Version: 2.0.34.0 

### Windows Version

OS Version: 10.0.22000.318

### Relevant Assets
[debug.log](https://github.com/files-community/Files/files/7533276/debug.log)

[debug_fulltrust.log](https://github.com/files-community/Files/files/7533270/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
