### ISSUE TITLE
Overlapping buttons in the Settings window

### ISSUE THREAD

**Issue by shirooo39** [files-community/Files#6906]
### Description

The "About" button is overlapping with the "close" button in the Setings window.  
At first, I thought it was just a glitch. But then I reopened it again multiple times, turns out it is not a glitch.
The buttons are constantly "being lovey dovey" with each other, so I think it's a bug.

Though I can still close the window just fine, but it's quite bothering to see.

### Steps To Reproduce

1. Open the app
2. Click on the gear icon on the top right corner to open up the Settings window

Voila

### Expected behavior

The expect behavior is... well... they shouldn't be overlapping with each other.  

The "About" button should be next to the close button.

### Files Version

2.0.36.0

### Windows Version

Windows 11 build 22000.318

### Relevant Assets

a screenshot

![image](https://user-images.githubusercontent.com/38461122/141678429-57bc0d46-0b0e-4899-84a9-f54bc8d8fc72.png)

**Comment by yaichenbaum** [comment]
Fixed with #6858.
