### ISSUE TITLE
Fix Default Explorer.exe after Files change default explorer program via registry

### ISSUE THREAD

**Issue by miskin1702** [files-community/Files#6907]
### Description

Hello there,
I downloaded and tried the Files program and changed it to the default explorer application. Then I decided to uninstall but explorer.exe did not fix. Can you help?

### Expected behavior

HELP!

### Files Version

Sürüm: 2.0.34.0 OS Version: 10.0.22000.258

### Windows Version

WİNDOWS 11

**Comment by yaichenbaum** [comment]
You can revert the changes using this script https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip.
