### ISSUE TITLE
Set the same visual setting for all folders.

### ISSUE THREAD

**Issue by ooVictorFranco** [files-community/Files#6908]
### What's the Problem?

**[en-US]**
Currently, you can configure the folder view mode in the folder individually.

I have not found a way to do this, so that the same setting is set for all folders.

For example: Opening the downloads folder and setting the layout on columns will not replicate the same effect when I open the documents or videos folder. 

------
**[pt-BR]**
Atualmente, é possível configurar o modo de visualização pasta a pasta de maneira individual.
Eu não encontrei uma forma de fazer isso, de forma que seja definida a mesma configuração para todas as pastas.
Por exemplo: Abrir a pasta de downloads e definir o layout em colunas não replicará o mesmo efeito quando eu abrir a pasta de documentos ou vídeos. 

### Solution/Idea

**[en-US]**
I would suggest that there is a way to replicate or save layout settings for all folders (whether or not the home page is not considered)

------
**[pt-BR]**
Gostaria de sugerir que haja uma forma de replicar ou salvar as configurações de layout para todas as pastas (desconsiderando ou não a página inicial)

### Alternatives

**[en-US]**
If the function is already available in the app, please can tell me how to change because i really have not found. Thank you, have a great day.

------
**[pt-BR]**
Se a função já está disponível no aplicativo, por favor pode me dizer como alterar, pois realmente não encontrei. Obrigado, tem um ótimo dia.

### Priorities

**[en-US]**
| Compatible with all systems on whom the "File" is installed. | Just a dream I'd like to see come true. |
| :---------- | :------- |
| This proposal will allow developers to accomplish | Nothing to be included |
| This proposal will allow end users to accomplish | The unique layout configuration of all paws while navigating the system. |

------
**[pt-BR]**
| Compatível com todos os sistemas em que o "Files" está instalado. | É só um sonho que eu gostaria de ver se tornando realidade. |
| :---------- | :------- |
| Esta proposta permitirá que os desenvolvedores realizem | Nada a ser incluído |
| Esta proposta permitirá que os usuários finais realizem | A configuração de layout única de todas as patas enquanto navega pelo sistema. |

### Files Version

Versão: 2.0.34.0

### Windows Version

Windows 11 Pro Insider Preview - Compilation 22499.1010 - Windows Feature Experience Pack 1000.22499.1010.0

### Additional comment

Thank you very much for your attention in reading this publication.

**Comment by yaichenbaum** [comment]
@ooVictorFranco you can accomplish this by turning off the setting to use individual preferences for different directories.
