### ISSUE TITLE
Customization tab in library properties crashes files

### ISSUE THREAD

**Issue by currall** [files-community/Files#6909]
### Description

The app crashes when trying to customise a library from the properties window

### Steps To Reproduce

1. right click a library
2. properties
3. customization

### Expected behavior

This should open a panel to change the library icon or add folders

### Files Version

2.0.34.0

### Windows Version

Windows 11 22000.318

**Comment by d2dyno1** [comment]
Can you attach log files?

**Comment by gave92** [comment]
#6914 should be the same issue and has the log files. Would still be useful to have  @currall's log files too for confirmation.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7004.
