### ISSUE TITLE
Problemas con el gestor de archivos

### ISSUE THREAD

**Issue by NeiderCamargo** [files-community/Files#6910]
### Description
The file manager has several problems when deleting documents but these problems do not happen when starting the file manager, but after several repetitions of deleting, copying and pasting elements, the selected document is simply not deleted, it also has problems when copying, cutting and pasting elements, simply the elements are not pasted to another location,  the problems are solved by closing the file manager, but after some repetitions deleting and pasting elements the problem reappears, if in the future it works correctly and they manage to implement the default file manager in Windows, it can be a great option to replace the traditional file explorer

### Steps To Play
1.Click on delete,  notifications display a message suggesting that you cannot delete item 2.Copy or cut (either with the keyboard or with context menu), - location where you are going to paste the element

### Expected behavior
1.You expected the item to be deleted 2.You expected the copied or cut item to be pasted into the new location

### Files Version Version: 
2.0.34.0 OS Version: 10.0.19042.1348

### Windows Version
Windows 10 Pro 20h2

**Comment by gave92** [comment]
Thanks for the report. Could you post the app's two log files.
