### ISSUE TITLE
Files 打开文件或文件夹时存在严重的卡顿

### ISSUE THREAD

**Issue by Xtra0123** [files-community/Files#6912]
Description
Files is unusually stuck when tapping or performing file management operations. There's no native Explorer smoothness, even if I set it as the default explorer, but there's still a clear stuck, and the right-click menu always displays the system's default menu when it loads, and then loads the right-click menu that installs the app

Steps To Reproduce
BUG1: File
management operations Repeatedly click on a folder or drag and drop files. Files can get stuck, or load significantly slower.

BUG2: Right-click menu
Select Chinese pieces and repeatedly click right-click, the installation of the application right-click menu loading speed is significantly slower than the original menu.

Expected behavior
It is hoped that File will have the same reaction speed as native resource manager.
It is hoped that File will have the same right-click load speed as native explorer.

Most seriously, modify the property menu to Win11 native. "Hopefully, when you click on the Properties menu, the Microsoft Native Properties interface will pop up, not the File's humble Property Interface"

Files Version
V2.0.34.0

Windows Version
Windows 11 21H2 22000.318

Relevant Assets
No response

**Comment by yaichenbaum** [comment]
Merging with #4180

**Comment by yair100** [comment]
@Xtra0123 we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
