### ISSUE TITLE
Support drag and drop on Favorites sidebar

### ISSUE THREAD

**Issue by myfix16** [files-community/Files#6913]
### What's the Problem?

Currently, if you want to rearrange the Favorites folders, you have to click options like "move one up", "move one down" on the context menu, which is highly inefficient if you want to arrange multiple folders or you have a long Favorites list.

### Solution/Idea

The vanilla Windows explorer's way to deal with pinned folders is good: you can drag and drop any folder to any location you want. Files could also use this way to arrange pinned folders.

### Alternatives

None.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Add drag and drop support on Favorites section | Must |

### Files Version

v2.0.34.0

### Windows Version

Windows 11 21H2 22000.346

**Comment by yaichenbaum** [comment]
@myfix16 the code for this was already implemented but we're held back by an issue with WinUI, can you upvote/comment on their repo? https://github.com/microsoft/microsoft-ui-xaml/issues/3290

**Comment by myfix16** [comment]
Acknowledged. I upvoted that issue😅
