### ISSUE TITLE
设置 库【Libraries】时Files 无响应

### ISSUE THREAD

**Issue by Xtra0123** [files-community/Files#6914]
### Description

Files 在 设置库名称及图标时经常性崩溃错误

### Steps To Reproduce

1.右键右侧【库】部分
![image](https://user-images.githubusercontent.com/27795593/141737141-1371d48a-a6df-4ba8-820b-bda62203d506.png)
2.点击【属性】
![image](https://user-images.githubusercontent.com/27795593/141737261-37477fda-35a3-4f39-be38-f62ca1264b42.png)
3.提示崩溃。
![image](https://user-images.githubusercontent.com/27795593/141737367-37754402-44fb-473f-955e-bd27a0baf175.png)

### Expected behavior

修复系统BUG

### Files Version

版本: 2.0.34.0

### Windows Version

Windows 11 21H2   Version: 10.0.22000.318

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7536552/debug.log
[debug_fulltrust.log](https://github.com/files-community/Files/files/7536553/debug_fulltrust.log)
)

**Comment by josh-65** [comment]
Please re-write in English.

**Comment by gave92** [comment]
Merging with #6909
