### ISSUE TITLE
Feature: Allow creating more than two panes

### ISSUE THREAD

**Issue by Cozy59** [files-community/Files#6915]
### Description

When enable multitasking Files shows only as default two panes on the left stations,drives etc - on the the right folders and files. Enable multitasking on a new tab opens the desired 3 panes - left the stationss/drives etc - mid pane foldens and files eand right pane folders and files. Closing Files  and restart Files then is backto default view so no 3 panes but two although the first multitasking option is enabled. If this is as designed I would like the option to default have 3 panes to work with.

### Requirements
Allow creating more than two panes

### Files Version

20340

### Windows Version

Windows 11 21H2 22000.318

**Comment by yaira2** [comment]
@Cozy59 thank you for your feedback, I think these issues have been addressed in recent versions of Files, but please let us know if you need further assistance and we'll do our best to help.

**Comment by 0x5bfa** [comment]
@yaira2 Addressed in where? More than two panes are not implemented though we’re preparing to be so flexible that we can implement this.

**Comment by yaira2** [comment]
@0x5bfa the panes in this feature request aren't referring to dual pane.
