### ISSUE TITLE
Failue opening Pictures

### ISSUE THREAD

**Issue by Cozy59** [files-community/Files#6917]
### Description

Opening Files and select on the left pane Pictures
Files opens a warning that the folder is gone or missing but it show it contens.
Pressing OK shits down Files (not always)
So far this behavior 

### Expected behavior

Opening Pictures on the right (or midle ) pane without any problem

### Files Version

20340

### Windows Version

Windows 11 21H2 22000.318

### Relevant Assets

[debug_fulltrust.log](https://github.com/files-community/Files/files/7537450/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7537451/debug.log
![Files error](https://user-images.githubusercontent.com/81916673/141757247-15ebe01f-0ef3-4582-a1aa-17fe96f66f2e.png)
)

**Comment by gave92** [comment]
Could you show what folders does your Pictures library point to? (Right click on Pictures folder in sidebar > Properties > Library)

**Comment by Cozy59** [comment]
Hi  Didnt know there was such option. It points to a false directory. Now I have changed this to the correct directory but couldnt set it as default. Closing and restart Files again I can set Pictures as default and delete the wrong path.Files crashes and close. Added the logfiles. Verzonden vanuit Mail voor Windows Van: Marco GavelliVerzonden: maandag 15 november 2021 21:15Aan: files-community/FilesCC: Cozy59; AuthorOnderwerp: Re: [files-community/Files] Failue opening Pictures (Issue #6917) Could you show what folders does your Pictures library point to? (Right click on Pictures folder in sidebar > Properties > Library)—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Cozy59** [comment]
I dont know if it went well…. .opened  again same case in Github incl logfiles and two screenshotsIn Properties >> Pictures  points to the correct folder. Other issue i came across, when select split screen (which shoud be option to open default in split screen) and you line your screen to match your screen. After closing files the splitscreen doesnt  keep this setting (pictures attached) Verzonden vanuit Mail voor Windows Van: Marco GavelliVerzonden: dinsdag 16 november 2021 19:11Aan: files-community/FilesCC: Cozy59; AuthorOnderwerp: Re: [files-community/Files] Failue opening Pictures (Issue #6917) Thanks for the info. Unfortunately I can't see the new log files, i think you need to reply from GitHub and not email.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
