### ISSUE TITLE
Selection animation still showing when windows animations are turned off

### ISSUE THREAD

**Issue by Hefaistos68** [files-community/Files#6919]
### Description

When turning off the window animations in the windows 10 settings, the (slightly annoying anyway) font animation when selecting an item in the files pane are still showing.

### Steps To Reproduce

go to windows settings (Windows+i), display personalization, turn off "show animations in windows"
select any file/folder in the file pane

### Expected behavior

No font animation when windows animations are turned off. All other animations are correctly suspended though.

### Files Version

Version: 2.0.34.0 

### Windows Version

OS Version: 10.0.19042.1348

**Comment by gave92** [comment]
I'm afraid on Windows 10 we're stuck with that animation. Also #6259.
@Hefaistos68 could you check if any other app that has that animation manages to turn it off if system animations are off?
