### ISSUE TITLE
Layout options for folder content display

### ISSUE THREAD

**Issue by Hefaistos68** [files-community/Files#6920]
### What's the Problem?

Current layout for folder content is very spacious, nice to the eye but little useful for frequent file operations. Currently the display seems to about 50% larger than the default windows explorer density.

### Solution/Idea

Offer something like most email programs offer: 3 different density settings, like comfortable, compact and tense? Or at least a line height setting.

### Alternatives

No alternatives, currently it seems to be a fixed setting.

### Priorities

Would be nice to have and improve usability

### Files Version

Version: 2.0.34.0 

### Windows Version

OS Version: 10.0.19042.1348

**Comment by gave92** [comment]
Merging with #1940
