### ISSUE TITLE
Merge all "Open xxx" into the same menu

### ISSUE THREAD

**Issue by Hefaistos68** [files-community/Files#6921]
### What's the Problem?

Currently I see the "open", "Open with", "Open in secondary pane", "Open in new tab" in the main context menu, but "Open in new window" is in the "More..." sub menu

### Solution/Idea

Group all open options into the same (sub-) menu.

### Alternatives

Dont see any other options.

### Files Version

Version: 2.0.34.0 

### Windows Version

OS Version: 10.0.19042.1348

**Comment by yaichenbaum** [comment]
These options are frequently used and I think it's important to keep them in the main menu.

**Comment by Hefaistos68** [comment]
Agree, but point is that not all "open..." options are in the same menu level

**Comment by yaichenbaum** [comment]
> Agree, but point is that not all "open..." options are in the same menu level

The open in new window option is not used as commonly but it's displayed in the main menu when you open the extended context menu (shift + right click).
