### ISSUE TITLE
Tooltips showing up while resizing columns

### ISSUE THREAD

**Issue by Hefaistos68** [files-community/Files#6923]
### Description

When resizing columns in the contents pane and moving the mouse slightly downwards into the file contents area, tooltips for the files under the mouse show up.
No really a major issue, just unexpected and showing that not all activities are cancelled while resizing.

### Steps To Reproduce

resize a column in the file contents pane, while resizing hover the mouse downwards until over a file/folder item, after a short delay  the info tooltip of the item shows up.

### Expected behavior

No tooltips when resizing.

### Files Version

Version: 2.0.34.0 

### Windows Version

OS Version: 10.0.19042.1348

**Comment by Hefaistos68** [comment]
Just noted that the same happens when resizing panes.

**Comment by Josh-65** [comment]
Is this still an issue?
