### ISSUE TITLE
Group refresh

### ISSUE THREAD

**Issue by fredericoregateiro** [files-community/Files#6924]
### Description

when using the group layout,i've tested using the group by file type, the groups are not updated when a temp file is deleted.

### Steps To Reproduce

Open a Libreoffice document so a lock file is created
![tempitem](https://user-images.githubusercontent.com/6304701/141780553-f019e17c-ddb2-404f-8285-30df287bfa14.png)

when closing the Libreoffice document is closed, the lock file is deleted, but the group is still there
![tempnoitem](https://user-images.githubusercontent.com/6304701/141780740-d10ca251-45f2-47b9-a9e8-809018315fc8.png)

### Expected behavior

If the group does not contains any items, the group should be deleted

### Files Version

Versão: 2.0.34.0 OS Version: 10.0.19043.1348

### Windows Version

Windows 10

**Comment by gave92** [comment]
The file itself gets removed but a now empty group remains, correct?

**Comment by Moustik2002** [comment]
Hi, generally speaking there is auto-refresh/update of any kind when you edit anything in file (delete, move paste ...) unless you hit F5, so i jump on this open issue to warn about this

**Comment by fredericoregateiro** [comment]
@Moustik2002 English is not my first language, and i didn't understand your comment. There is auto-refresh or not?

The behaviour i described, is the normal behavior of the windows explorer, it's just a really nice feature.

**Comment by Moustik2002** [comment]
from my point of view there auto refresh is not working on Files and this is why i'm complaining ;)

**Comment by Josh-65** [comment]
Is this an issue in the preview version? https://files.community/download/preview

**Comment by fredericoregateiro** [comment]
just try the 2.3.47.0 preview and it's working ok
