### ISSUE TITLE
Files crashed after 55+ files transfer.

### ISSUE THREAD

**Issue by aayushyap89** [files-community/Files#6929]
### Description

I was just importing some family photos and transfering them all into one big folder to not have a bunch of photos. And one folder had around 55 photos. I then cut and pasted them into the other folder and files crashed although the transfer did complete with no deleted files.

### Steps To Reproduce

1. Get 55+ files into a folder (When I tried to reproduce this I used 58 files)
2. Cut all these files
3. paste them into the parent directory
4. files will crash though the transfer will complete.

### Expected behavior

Not to crash

### Files Version

v2.0.36.0

### Windows Version

Windows 11 21H2 22000.318

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7541461/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7541462/debug_fulltrust.log)

Thoes are the two debug files.

**Comment by yaichenbaum** [comment]
@aayushyap89 is this still an issue in the preview version? http://files.community/download/preview
