### ISSUE TITLE
File changes doesn't reflect on NETWORK drive

### ISSUE THREAD

**Issue by jarayama** [files-community/Files#6932]
### Description

When I do a file operation like delete or copy into a network drive, it doesn't refresh after the completion of that task, I tried with copy and delete and create a folder, the task is accomplished, but the change is not showing.

### Steps To Reproduce

Copy or delete a file on a network drive.

### Expected behavior

After task is done, it should show me the file change.

### Files Version

Versión: 2.0.34.0 OS Version: 10.0.22000.318

### Windows Version

Windows 11 21H2 22000.318

**Comment by gave92** [comment]
Merging with #5869
