### ISSUE TITLE
Add dev and pre release icon to distinguish between versions

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#6933]
### Solution/Idea

Add different icons and config to easily build different versions

### Alternatives

NA

### Files Version

v2.0.36

### Windows Version

Windows 11

**Comment by esibruti** [comment]
![StoreLogo scale-400-dev](https://user-images.githubusercontent.com/78214358/143014399-122d1a99-0cd1-4ad4-a8af-9aae7aba6803.png)


![StoreLogo scale-400-pre](https://user-images.githubusercontent.com/78214358/143014403-f7d2946d-168d-4d25-89f8-59b61ca1b71f.png)

@yair100 Do you want something like this?
Edit: The images are not of good quality, it's just a test.

**Comment by yaichenbaum** [comment]
@esibruti we already have the icons, we just need to add different configurations to switch between them.

**Comment by yaichenbaum** [comment]
This issue is resolved in `main`.
![image](https://user-images.githubusercontent.com/39923744/195741888-957a1434-cc9d-4657-8743-53eb9812453d.png)
