### ISSUE TITLE
default file explorer 

### ISSUE THREAD

**Issue by rRashu** [files-community/Files#6936]
### Description

uninstall the application with the experimental option "default file explorer" now shows an error when trying to open folders in windows

### Steps To Reproduce

un
![Captura de pantalla (3)](https://user-images.githubusercontent.com/94420600/141886634-bf2641fb-cb00-4bf0-9a4d-4c4e4495058e.png)

### Expected behavior

when uninstalling the application it will return to the default browser

### Files Version

1.5

### Windows Version

Edición	Windows 11 Pro Versión	21H2 Se instaló el	‎05/‎10/‎2021 Compilación del SO	22000.318 Experiencia	Paquete de experiencia de características de Windows 1000.22000.318.0

**Comment by gave92** [comment]
You'll need to download [this zip](https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip) and run UnsetFilesAsDefault.reg to restore windows explorer.
