### ISSUE TITLE
drives take long time to show

### ISSUE THREAD

**Issue by lolinajdi** [files-community/Files#6937]
### Description

hello
there is a problem in the files app

 The problem is when I open the app  the app takes time maybe 1 minute  to show drives here is a pic
![Screenshot 2021-11-16 003620_LI](https://user-images.githubusercontent.com/65453926/141857441-ac8b6428-5779-42a1-ab72-a906c575e33f.jpg)
please fix the bug 

I hope that I explain all things 

### Expected behavior

hello
there is a problem in the files app

 The problem is when I open the app  the app takes time maybe 1 minute  to show drives here is a pic
please fix the bug 

I hope that I explain all things 
![Screenshot 2021-11-16 003620_LI](https://user-images.githubusercontent.com/65453926/141887769-d9021ec0-0703-44c8-af2f-69116fc1c1e5.jpg)

### Files Version

Version: 2.0.34.0 OS Version: 10.0.19043.1348

### Windows Version

Edition	Windows 10 Pro Version	21H1 Installed on	‎11/‎9/‎2021 OS build	19043.1348 Experience	Windows Feature Experience Pack 120.2212.3920.0

**Comment by gave92** [comment]
Thanks for the report. Please upload the app's log files.

**Comment by lolinajdi** [comment]
here is log

[debug.log](https://github.com/files-community/Files/files/7544999/debug.log)

[debug_fulltrust.log](https://github.com/files-community/Files/files/7545002/debug_fulltrust.log)


also when I restart the windows and open the files app I face same thing

**Comment by rgilsimoes** [comment]
I have a similar problem.

But only "Local Drives" load slow.

I think I could be related to having network attached drives.

**Comment by tatsumara** [comment]
i can confirm this has to do with network drives. i removed the one i had through windows explorer (it didn't seem to work in files) and now everything loads quickly again.

**Comment by yaichenbaum** [comment]
This should be resolved in the preview build https://files.community/download/preview
