### ISSUE TITLE
崩溃后无法再启动，需要使用app重置后才能启动。

### ISSUE THREAD

**Issue by Tjlastnumber** [files-community/Files#6938]
## 程序版本
版本: 2.0.34.0
OS Version: 10.0.22000.318

-----

估计是因为添加标签引起的，我的几个文件夹添加了标签之后上个版本使用正常，更新以后会有打不开程序的情况，不开启标签功能情况下没有问题。只能用过app的重置后才能启动，但是之前的标签颜色就找不到了。

### Expected behavior

程序可以正常启动

### Files Version

2.0.34.0

### Windows Version

Windows 11 21H2 22000.318

**Comment by yaichenbaum** [comment]
@Tjlastnumber can you upload the log files?
