### ISSUE TITLE
Cloud Drives: Add Yandex

### ISSUE THREAD

**Issue by joergstrohmeier** [files-community/Files#6940]
### Solution/Idea

Adding two other cloud drives 
Google Drive
Yandex Disk

### Alternatives

none

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.346

### Windows Version

Windows 11, latest

**Comment by gave92** [comment]
Good drive should already appear in the sidebar (maybe in the Drives section). Not so for Yandex thoughm

**Comment by joergstrohmeier** [comment]
Hi Marco

Left side my cloud drives with Yandex Disk and Synology Drive (somehow 
Explorer can identify them, even the Syno Drive, that surprices me). In 
the middle the G: drive from Google. Right is Files


Freundliche Grüsse
Jörg Strohmeier

------ Original Message ------
From: "Marco Gavelli" ***@***.***>
To: "files-community/Files" ***@***.***>
Cc: "inthesky" ***@***.***>; "Author" 
***@***.***>
Sent: 16.11.2021 09:16:16
Subject: Re: [files-community/Files] Cloud Drives: Add Google and Yandex 
(Issue #6940)
