### ISSUE TITLE
I can't drag files to other apps

### ISSUE THREAD

**Issue by defaultkavy** [files-community/Files#6941]
### Description

I can drag single file to other app.
But if I select 2 files and drag, the app will not getting files
This problem appeared 1 month ago.

### Expected behavior

The other app get the multiple files.

### Files Version

Version: 2.0.35.0 OS Version: 10.0.22499.1010

### Windows Version

Windows 11 Dev 1000.22499.1010.0

**Comment by guategeek** [comment]
I also am experiencing this, drag and drop seems spotty period, even within files itself I often will have no response when I try to dray one ore multiple files from one folder to another, or one files window into another.

**Comment by was-games** [comment]
I wanted to try Files as my default explorer, but this operation is what I have to do every day, had to go back to standard explorer for now.

**Comment by chaoscreater** [comment]
You can drag and drop a single file? I can't even do that. I'm using the latest Files build and I'm trying to drag and drop .txt files to Notepad++ and it wouldn't work.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #9014
