### ISSUE TITLE
Add settings to choose default option when resolving conflicts

### ISSUE THREAD

**Issue by avansteenbruggen** [files-community/Files#6942]
### What's the Problem?

If try to overwrite a existing file i get a options screen.

- Generate a new name
- overwrite
- skip

Files won't remember my choise, it always starts on the first option (Generate new name).

### Solution/Idea

Remeber user choise or make option to set a default

### Alternatives

Remeber user choise or make option to set a default

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.0.34.0

### Windows Version

Windows 11

**Comment by rywalters** [comment]
I don't even get a prompt to overwrite or not; Files just assigns a new name. And it doesn't refresh so I don't see that anything at all has happened. Also running Win11.

**Comment by yaichenbaum** [comment]
Merging with #5645
