### ISSUE TITLE
Can not diable Set Files as default file explorer

### ISSUE THREAD

**Issue by marius7600** [files-community/Files#6943]
### Description

I accidentally uninstalled files without disabling the Set Files as default file explorer function.
After reinstalling, files is the default explorer again, but unfortunately I can't deactivate that.

Whenever I try to set the slider to off,  the Administrator confirmation for the registry editor opens and i klick on yes, but after that the slider is still on.

### Expected behavior

After setting the slider for setting flies as default explorer to off, the slider should stay on off and files should not be the default editor any more.

### Files Version

2.0.34.0

### Windows Version

Windows 11 Pro 21H2 22000.318

**Comment by gave92** [comment]
To unset Files you can download [this zip](https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip) and run UnsetFilesAsDefault.reg to restore windows explorer.
