### ISSUE TITLE
Alt+arrow_keys navigation only partially works

### ISSUE THREAD

**Issue by Hefaistos68** [files-community/Files#6944]
### Description

This is related to #6736 but its not a feature request but a bug. 
When in the file/folder pane and pressing Alt+◀/▶, the contents is actually correctly updated. In other words: left goes to the previous location, right to the next (if any), as expected by convention.
But, after changing the location the focus is switched away from the pane and goes to the other controls of the app, thus no further navigation is possible.

The Alt+🔼/🔽 keys also exhibit erroneous behavior: Alt+🔼 does (unexpectedly) move upwards in folder hierarchy, yet Alt+🔽 does either nothing when in the file pane, or navigate amongst controls when the focus is outside a file pane.

### Steps To Reproduce

select a folder in the right pane
open a sub folder (repeat if more levels of navigation  history are desired), 
press Alt+◀ to go backwards in navigation history
press Alt+◀ again, when at the last step in history, the focus will jump to the "Name" column of the pane
repeated Alt+◀ will then cycle trough the apps controls

### Expected behavior

Not ever change focus with Alt+◀/▶ as those are not focus keys, rather stay in the navigation mode.

### Files Version

Version: 2.0.34.0 

### Windows Version

OS Version: 10.0.19042.1348

**Comment by yaichenbaum** [comment]
@Hefaistos68 is this an issue in all the layouts?

**Comment by Hefaistos68** [comment]
Just tested it, yes, same behavior in all layouts.

**Comment by yaichenbaum** [comment]
Merging with #9042
