### ISSUE TITLE
Add double click to extract archives

### ISSUE THREAD

**Issue by Elegant-Xia** [files-community/Files#6945]
### Description

When I want to extract a "*.zip" file, I can only right click on it and select extract instead of **double click on it directly,**

### Expected behavior

Hope that I can with just double or single click to extract a zip file.

### Files Version

Version: 2.0.34.0 OS 

### Windows Version

Windows 11 Dev 22499.1010

**Comment by yaichenbaum** [comment]
The intended behavior is for Files to open the archive instead of extracting the items. Both scenarios are useful so I'll leave this issue open to gather feedback from users.

**Comment by ADeltaX** [comment]
I wouldn't extract the archive on double click as a default behavior

Reason 1: Security (you want to see the content before actually extracting it)

Reason 2: Practicality (If the archive is big it will take a considerable amount of time until you can view the content when (e.g.) your intent is to view just a single file)

Reason 3: Muscle memory/Repeatability (Does the user actually always extract the entire archive? or just specific files? If specific files only then it's better just to list the content of the archive and then extract/open the file of interest with a double click)

**Comment by yaichenbaum** [comment]
@Elegant-Xia while we don't have plans to implement this, we added a toolbar button to make it easier to extract archives.
