### ISSUE TITLE
Files hang while During deleting files

### ISSUE THREAD

**Issue by lakani** [files-community/Files#6947]
### Description

system hang while During deleting files

### Steps To Reproduce

try to delete some files that requires Admin privilege's, 
files hangs for a while  , then after deleting them using windows file explorer, files works  

### Expected behavior

should be able to delete without any hang 

### Files Version

Version: 2.0.34.0

### Windows Version

OS Version: 10.0.19043.1320

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7547828/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7547829/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
@lakani is this still an issue in the preview version? https://files.community/download/preview
