### ISSUE TITLE
Settings close icon overlap

### ISSUE THREAD

**Issue by Levminer** [files-community/Files#6948]
### Description

The setting close button overlaps with the about button.

### Steps To Reproduce

1. Click settings in the top right corner

### Expected behavior

The close icon not overlaps with the about button.

### Files Version

Version: 2.0.36.0 OS Version: 10.0.22000.346

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎2021. ‎07. ‎03. OS build	22000.346 Experience	Windows Feature Experience Pack 1000.22000.346.0

### Relevant Assets

![image](https://user-images.githubusercontent.com/33373714/142022067-4717cc54-3f34-4002-9761-c14856da2dca.png)

**Comment by yaichenbaum** [comment]
@Levminer this issue should be resolved in the latest preview build.

**Comment by Levminer** [comment]
Okay, thanks for getting back so fast! Great app btw  👍  .
