### ISSUE TITLE
Please use "Files" application replace file selection dialog window

### ISSUE THREAD

**Issue by laomengwa** [files-community/Files#6949]
### What's the Problem?

I wish this application replace the Windows Explorer default "select"or"save"dialog window,Because the interface of the default dialog window is very old and difficult to use,It does not conform to the interface design style of modern operating system.
![image](https://user-images.githubusercontent.com/69566148/142022325-8119d522-4b11-4756-8f43-3a3ef725f7d9.png)
![image](https://user-images.githubusercontent.com/69566148/142022558-8f96cd08-65f9-40d7-9af7-9e7252d665b1.png)
![image](https://user-images.githubusercontent.com/69566148/142022660-c2f434ea-8332-4bf3-baf0-5268767402e0.png)
![image](https://user-images.githubusercontent.com/69566148/142022728-be6336f3-d8fa-49ae-9a5a-8ad72c443d67.png)

### Solution/Idea

Change these settings by regedit

### Alternatives

proposal...

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.0.34.0

### Windows Version

Windows 11 21H2 22499.1010

**Comment by gave92** [comment]
Thanks for the suggestion, we're actively working to implement open and save dialogs with Files. Unfortunately it's really tricky to get them working right for all programs.
