### ISSUE TITLE
Reorder Columns

### ISSUE THREAD

**Issue by infuriatedcodex** [files-community/Files#6950]
### What's the Problem?

I can't be sure but seem to remember the column for cloud status was positioned similar to the native file explorer.

The problem currently is you cannot even move the columns which I believe with previous versions, you could
![20211116_174055 - ApplicationFrameHost301](https://user-images.githubusercontent.com/40537324/142037772-28528493-e2a1-4fb3-9b9b-17f58715a09f.jpg)
.

### Solution/Idea

Re-enable please (if it was previously doable) and if not, please implement.

### Alternatives

None

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.0.34.0

### Windows Version

OS Version: 10.0.22000.318

**Comment by gave92** [comment]
Included in #4643
