### ISSUE TITLE
"Phantom" USB-Drives remain in Files

### ISSUE THREAD

**Issue by WoSe2021** [files-community/Files#6951]
### Description

I only discovered afterwards that USB drives that are not logged off before the computer is shut down remain under Files as "phantoms". These cannot be removed from Files and the drive letters are not reassigned by Windows 11. Unfortunately, uninstalling and reinstalling Files did not change anything. These phantom drives are not present in Windows Explorer, but the corresponding drive letters are also no longer available for assignment in Windows drive management. The USB drives E-H in the picture are such phantom drives. The assigned letters can be changed in the registry with the help of "regedit". If they are deleted, however, they reappear under "Files" with the original letter.
![Screenshot 2021-11-16 183059](https://user-images.githubusercontent.com/94476095/142040500-b8c5f897-1f50-4749-9d9f-f2dbdd2ee139.png)

### Expected behavior

When the USB drives have been removed, the drive letters previously used under Files should also no longer be displayed as empty drives and the letters used should not be blocked. 

### Files Version

Version: 2.0.34.0 

### Windows Version

Windows 11 21H2 22000.318

**Comment by gave92** [comment]
Mm I don't think Files has the power to lock a drive letter 🤔. Looks more like a windows issue?
Do the drive letters get locked also if you don't use Files at all?

**Comment by WoSe2021** [comment]
The phantom drives are not displayed in Windows Explorer. If I now plug a USB stick into the computer, a letter is used that is after the letters of the "phantom" drives. My idea at first was to change the newly assigned drive letter to the letter of a "phantom drive" and then eject the "USB stick" regularly, but that doesn't work either, because the letters of the phantom drives are not available in the disk management.

**Comment by gave92** [comment]
Could you post the app's log files?

[Comment unrelated to Files below]
In the past I've used DriveCleanup utility from [here](https://www.uwe-sieber.de/drivetools_e.html) to solve a similar issue. You may want to try it, though I don't think it does much more than removing leftover drive keys from registry.

**Comment by WoSe2021** [comment]
I finally found a solution. After "Uninstalling" via "Properties" "Drivers" in the drive management did **not** solve the problem, as the phantom drives initially disappeared but then reappeared in the drive management, it worked via "Drivers" "Deactivate device" and the phantom drives remained gone even after restarting the computer.
