### ISSUE TITLE
Bug: WSL not detected after upgrading from Windows 10

### ISSUE THREAD

**Issue by vabka** [files-community/Files#6952]
### Description

I have a wsl2 image and i can see it in native explorer.exe
But i cant see it in Files on side panel.

There is FileNotFoundException in logs

### Steps To Reproduce

1. Setup WSL on Windows 10
2. Open Files and verify WSL is working 
3. Update to Windows 11
4. Open Files and see if WSL works

### Expected behavior

WSL should work even after updating from Windows 10

### Windows Version

10.0.22499.1010

### Relevant Assets

2021-11-16 23:57:40.7907|INFO|Connection_RequestReceived|Argument: GetIconOverlay
2021-11-16 23:57:40.7942|INFO|StartSTATask|Не удается найти указанный файл. (Исключение из HRESULT: 0x80070002)
	System.IO.FileNotFoundException: Не удается найти указанный файл. (Исключение из HRESULT: 0x80070002)
   в Vanara.PInvoke.Shell32.ShellUtil.GetShellItemForPath(String path)
   в FilesFullTrust.Win32API.GetFileIconAndOverlay(String path, Int32 thumbnailSize, Boolean getOverlay, Boolean onlyGetOverlay)
   в FilesFullTrust.MessageHandlers.Win32MessageHandler.<>c__DisplayClass3_0.<ParseArgumentsAsync>b__0()
   в FilesFullTrust.Win32API.<>c__DisplayClass0_0`1.<StartSTATask>b__0()

**Comment by gave92** [comment]
Is wsl running before opening Files?

**Comment by yaichenbaum** [comment]
@vabka I had this issue after updating from Windows 10 but reinstalling Windows 11 fixed it.

**Comment by vabka** [comment]
> Does it appear if you make sure that wsl is running before opening Files?
> Does it work if you manually insert wsl path in Files's address bar?

I will try it tomorrow

**Comment by vabka** [comment]
On my main PC everything OK.
![image](https://user-images.githubusercontent.com/17644379/142191493-0954ce22-95e3-4cd1-a366-1f484376a81c.png)

**Comment by vabka** [comment]
![image](https://user-images.githubusercontent.com/17644379/142191726-98b7f942-939c-49c4-b985-f9be69e4a65a.png)
Tryed to open by path

**Comment by vabka** [comment]
![image](https://user-images.githubusercontent.com/17644379/142191915-3e754ab0-9e92-4acc-b28d-8530b23a2277.png)
And again when pasting path to address bar

**Comment by vabka** [comment]
![image](https://user-images.githubusercontent.com/17644379/142192007-ca3c3511-b930-4224-85c4-22a8eef11bc0.png)
At same time Explorer can open it.

**Comment by yaichenbaum** [comment]
@vabka did you originally setup this instance of WSL on Windows 10?

**Comment by vabka** [comment]
@yair100 Not sure.
On pc where it was setuped while on Windows 10. It visible.

**Comment by JishnuJayaraj** [comment]
same error exists for me. All other sidebar toggles functions but switching ON/OFF wsl brings up nothing on side panel.

**Comment by yaichenbaum** [comment]
@JishnuJayaraj @vabka is this an issue for you in a fresh install of Windows 11?

**Comment by JishnuJayaraj** [comment]
Nope, it was upgraded from windows 10

**Comment by yaichenbaum** [comment]
@JishnuJayaraj it seems that upgrading from Windows 10 breaks the APIs to detect WSL. I've tested on a couple of devices with a fresh install and the APIs work correctly. This is still something for us to work on fixing but in the meantime, resetting Windows is a workaround.

**Comment by vabka** [comment]
@yair100 my laptop was upgraded to Windows 11 Insider Preview and WSL was installed in Windows 11. (WSL volume not visible)
My PC was upgraded to stable Windows 11 but WSL was installed in Windows 10. (WSL volume visible)

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview build? https://files.community/download/preview
