### ISSUE TITLE
Multiple Copies of Hard Drive Entry

### ISSUE THREAD

**Issue by XuShenLZ** [files-community/Files#6953]
### Description

I pluged in my West Digital Easystore 5TB hard drive. But there are a lot of copies of this same hard drive. They are all pointing to the same thing. If I click on any one of them, it will always jump to the first one.

![image](https://user-images.githubusercontent.com/31999415/142055228-afb95a1c-f6b7-40dc-adf5-a5929e81f2a8.png)

For comparison, this is what I see from system explorer

![image](https://user-images.githubusercontent.com/31999415/142055329-17f50b90-7f95-41a2-9cbe-9db88dfe9fbd.png)

### Steps To Reproduce

1. Plug in a hard drive
2. Then you will see this

### Expected behavior

Only one hard drive entry should be present

![image](https://user-images.githubusercontent.com/31999415/142055743-e3e67a48-dd3a-442a-8b73-093d5dc5cef2.png)

### Files Version

2.0.34.0

### Windows Version

Windows 11 Pro 21H2 22000.318

**Comment by gave92** [comment]
Thanks for the report. Merging with #6493
