### ISSUE TITLE
Creating fake USB drives for USB C Hub

### ISSUE THREAD

**Issue by XuShenLZ** [files-community/Files#6954]
### Description

When I connect a USB C hub to my laptop, there are two extra "USB drive" showing up in Files. There are only a keyboard, a HDMI monitor, and a 3.5mm earphone connecting to the USB hub. Nothing extra shows up in Win 11 default explorer.

![image](https://user-images.githubusercontent.com/31999415/142056986-86c2e1e3-730e-431f-9caf-2714e3fbacb8.png)

Clicking on any of them will just show an access denied error

![image](https://user-images.githubusercontent.com/31999415/142057056-fddcd654-9f52-47a3-a387-4002f9d7be78.png)

BTW, this is the hub I am using: https://www.amazon.com/gp/product/B08D9JF6GJ/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1

### Steps To Reproduce

1. Connect the USB C hub to laptop
2. Open Files
3. You will see extra "fake" USB drives

### Expected behavior

Nothing extra should show up for the USB Hub. 

### Files Version

2.0.34.0

### Windows Version

Windows 11 Pro 21H2 22000.318

**Comment by gave92** [comment]
Thanks for the report. Could you post the app's log files?

**Comment by XuShenLZ** [comment]
@gave92 Are these the files you are looking for?

[debug_fulltrust.log](https://github.com/files-community/Files/files/7578837/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7578838/debug.log)

**Comment by Josh-65** [comment]
Is this still an issue?
