### ISSUE TITLE
Multiselect should be a setting that doesn't affect folder navigation

### ISSUE THREAD

**Issue by EasyRhin0** [files-community/Files#6956]
Just like Windows, multiselect should be an accessibility setting. I need multiselect to be available just as it is for people with two hands who can use Shift and/or Ctrl at any time. Currently Files doesn't allow folder navigation (enter a folder), instead selecting/unselecting the clicked folder. The multiselect mode is also not persisted across sessions. It would make sense for this setting to be in Settings > Files & Folders. The current menu bar checkbox could be disabled when the setting is active. The current multiselect experience should also be changed to allow folder navigation.

**Comment by yaichenbaum** [comment]
@EasyRhin0 can you fill out the issue template so I can get a better understanding of what you're looking for?

**Comment by EasyRhin0** [comment]
There are really two separate requests. I'm not sure what I did to avoid the template but I'll open two new issues and close this one.

**Comment by yaichenbaum** [comment]
> There are really two separate requests. I'm not sure what I did to avoid the template but I'll open two new issues and close this one.

Thanks! I'll check those out.
