### ISSUE TITLE
Saludos!!!

### ISSUE THREAD

**Issue by djtEtO** [files-community/Files#6957]
### What's the Problem?

No problem!

### Solution/Idea

Que posibilidad hay de agregar una vista en modo LISTA.
O que la vista en modo DETALLE en los atributos se pueda ver la ruta de los archivos!

### Alternatives

No alternativas!

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.0.34.0

### Windows Version

Windows 11

### Additional comment

EXCELENTE APLICACIÓN!

**Comment by yaichenbaum** [comment]
Merging with #2509

**Comment by esibruti** [comment]
@yaichenbaum I think you forgot to close this issue
