### ISSUE TITLE
Multiselect mode should allow navigation into folders

### ISSUE THREAD

**Issue by EasyRhin0** [files-community/Files#6959]
### Description

When multiselect is enabled, attempting to navigate into a folder in the right pane instead toggles the checked state.

### Steps To Reproduce

1. Enter a folder that has subfolders such as C:\.
2. Enable multiselect mode
3. Double-click a folder.

### Expected behavior

The window should navigate into the subfolder, just as it would if multiselect was not enabled.

### Files Version

2.0.34.0

### Windows Version

Windows 11 22000.318

**Comment by yaichenbaum** [comment]
@winston-de can I assign you this issue?

**Comment by winston-de** [comment]
> @winston-de can I assign you this issue? Ideally, once two items are selected, clicking on other items should select them instead of navigating to them.

Sure, this should be relatively simple. Double click to open being disabled in multiselect mode is controlled by a simple if statement anyway.

**Comment by yaichenbaum** [comment]
Merging with #8918
