### ISSUE TITLE
When I open the library with files to set properties, it will flash back

### ISSUE THREAD

**Issue by Xtra0123** [files-community/Files#6961]
### Description

When I open the library with files to set properties, it will flash back。

### Steps To Reproduce

1.Open files, select the library and right-click properties
![image](https://user-images.githubusercontent.com/27795593/142134513-39561c52-69a7-4e10-8ef6-7dcd38707825.png)
2.click [customization]
![image](https://user-images.githubusercontent.com/27795593/142134533-46f37fac-ff85-481d-9cb5-a0d6d9db8ccc.png)
3.it will flash back
![image](https://user-images.githubusercontent.com/27795593/142134710-7543ca37-f7e5-451c-96f5-21e3001f1733.png)

### Expected behavior

I hope I can adjust the properties correctly and change the folder with a new icon

### Files Version

 2.0.34.0 

### Windows Version

Windows11 21H2  10.0.22000.318

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7551682/debug.log
[debug_fulltrust.log](https://github.com/files-community/Files/files/7551691/debug_fulltrust.log)
)

**Comment by gave92** [comment]
Same as #6909
