### ISSUE TITLE
Abandon the old and slow search method of windows search

### ISSUE THREAD

**Issue by Xtra0123** [files-community/Files#6962]
### What's the Problem?

I saw someone propose to provide multi-dimensional query criteria for search. This is a good idea and we urgently need it. But files is a great application. It should not be dragged down by windows search. As we all know, windows search is slow and cumbersome, and its query is too slow and index creation is too slow. We need faster query methods, such as integrating "everything" search services.

### Solution/Idea

Integrate "everything" as the main search method, instead of using Microsoft's slow search like an old lady。
The purpose of ” Files “is to upgrade and correct the disadvantages and irrationality of "explorer. Exe". It should abandon all redundant things that slow down the performance, rather than follow the native search application that Microsoft has little use but can't uninstall.
”Files“  is more than just a multi tab resource manager. It should replace Microsoft's native resource manager as one of the applications that users cannot uninstall

![image](https://user-images.githubusercontent.com/27795593/142136796-2c29ce2e-1181-4072-a0d7-81b534ed3b5f.png)

What we need is a faster and more accurate search method, rather than a search method that has multiple filter conditions but is particularly slow to search things

### Alternatives

Faster and easier to use

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

版本: 2.0.34.0 

### Windows Version

Windows 11 21H2 10.0.22000.318

**Comment by gave92** [comment]
Merging with #5845
