### ISSUE TITLE
problem uninstalling

### ISSUE THREAD

**Issue by virus3223** [files-community/Files#6964]
### Description

Español: al desinstalar File Manager for Windows v2 el explorador de archivos no abre carpetas diciendo que no encuentra la aplicación, hay alguna solución para esto ?

When uninstalling File Manager for Windows v2 the file explorer does not open folders saying that it cannot find the application, is there any solution for this?

### Expected behavior

uninstalls the product correctly but the windows 11 file explorer stops working when opening a folder says that it cannot find the app

### Files Version

Versión: 2.0.34.0 OS Version: 10.0.22000.318

### Windows Version

Edición	Windows 11 Pro Versión	21H2 Instalado el	‎08/‎10/‎2021 Versión del sistema operativo	22000.318 Experiencia	Paquete de experiencia de características de Windows 1000.22000.318.0

**Comment by BanCrash** [comment]
Hi @virus3223, you have to follow the instructions here to unset as default file explorer:

https://files.community/docs/configuring/replace-file-explorer

TL;DR: download [this zip](https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip) and run UnsetFilesAsDefault.reg to restore windows explorer

**Comment by virus3223** [comment]
Thanks @BanCrash , it would have to be corrected so that this would not happen at the time of uninstalling I do not think it is very difficult to change it

**Comment by BanCrash** [comment]
> Thanks @BanCrash , it would have to be corrected so that this would not happen at the time of uninstalling I do not think it is very difficult to change it

Yeah, we think the same but it was a feature that needs approval from Microsoft. There is already a PR with that feature opened: https://github.com/files-community/Files/pull/6935
