### ISSUE TITLE
Files crashes when opening pictures from a library location

### ISSUE THREAD

**Issue by Cozy59** [files-community/Files#6965]
### Description

See my earlier bugreport and mail. Now with new logfiles and pictures,

### Expected behavior

No crashes

### Files Version

20340

### Windows Version

Windows 11 21H2 22000.318

### Relevant Assets

[debug_fulltrust.log](https://github.com/files-community/Files/files/7553342/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7553343/debug.log
![002](https://user-images.githubusercontent.com/81916673/142172976-558096df-c8b7-482b-a6fa-ecaad407e7f9.png)
![001](https://user-images.githubusercontent.com/81916673/142172985-d94f2097-c64a-445b-a493-0a65d2163180.png)
)

**Comment by yaichenbaum** [comment]
Is this still an issue in the latest preview build? https://files.community/download/preview
