### ISSUE TITLE
Image file preview sometimes doesn't work

### ISSUE THREAD

**Issue by Pietro228** [files-community/Files#6966]
### Description

Image file preview sometimes doesn't work and only shows gray square.

### Expected behavior

Show image preview.

### Files Version

2.0.34.0

### Windows Version

10.0.22000.346

### Relevant Assets

Files:
![obrazek](https://user-images.githubusercontent.com/53868994/142188831-f449753c-06dc-4f7e-ae1b-0f37927696d2.png)

Windows File Explorer:
![obrazek](https://user-images.githubusercontent.com/53868994/142188840-9d069c60-b8ed-4120-aa04-2eb5a6806767.png)

**Comment by gave92** [comment]
Any difference if you refresh the folder or switch to griview layout mode?

**Comment by Pietro228** [comment]
When I refresh the folder it stays the same. In other layouts it shows file icon not the preview. By the way new images that I've downloaded show in preview but with black background.

**Comment by yaichenbaum** [comment]
@gave92 should we add this to the backlog?

**Comment by esdcgit** [comment]
It is a gamebreak not having this feature.  The application is almost perfect, but i have not had thumbnails work in any try of the software.  I recon there might be challenges with HEIC and other file types.  If the Image previews work then i will gladly be able to try the software again.

**Comment by d2dyno1** [comment]
This issue should be resolved with #7881 @Pietro228
