### ISSUE TITLE
auto create file "desktop.files.json"

### ISSUE THREAD

**Issue by KevinXia** [files-community/Files#6968]
### Description

auto create file "desktop.files.json" when File start

desktop.files.json  File content：
{"DirectorySortOption":0,"DirectorySortDirection":0,"DirectoryGroupOption":0,"LayoutMode":4,"GridViewSize":100,"ColumnsViewModel":{"TagColumn":{"UserCollapsed":false,"Length":{"Value":0.0,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"LengthIncludingGridSplitter":{"Value":0.0,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"UserLength":{"Value":200.0,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"UserLengthPixels":200.0},"NameColumn":{"UserCollapsed":false,"Length":{"Value":384.46601941747576,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"LengthIncludingGridSplitter":{"Value":385.46601941747576,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"UserLength":{"Value":384.46601941747576,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"UserLengthPixels":384.46601941747576},"StatusColumn":{"UserCollapsed":false,"Length":{"Value":0.0,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"LengthIncludingGridSplitter":{"Value":0.0,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"UserLength":{"Value":50.0,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"UserLengthPixels":50.0},"DateModifiedColumn":{"UserCollapsed":false,"Length":{"Value":384.46601941747576,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"LengthIncludingGridSplitter":{"Value":385.46601941747576,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"UserLength":{"Value":384.46601941747576,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"UserLengthPixels":384.46601941747576},"OriginalPathColumn":{"UserCollapsed":false,"Length":{"Value":0.0,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"LengthIncludingGridSplitter":{"Value":0.0,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"UserLength":{"Value":200.0,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"UserLengthPixels":200.0},"ItemTypeColumn":{"UserCollapsed":false,"Length":{"Value":384.46601941747576,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"LengthIncludingGridSplitter":{"Value":385.46601941747576,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"UserLength":{"Value":384.46601941747576,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"UserLengthPixels":384.46601941747576},"DateDeletedColumn":{"UserCollapsed":false,"Length":{"Value":0.0,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"LengthIncludingGridSplitter":{"Value":0.0,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"UserLength":{"Value":200.0,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"UserLengthPixels":200.0},"DateCreatedColumn":{"UserCollapsed":true,"Length":{"Value":0.0,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"LengthIncludingGridSplitter":{"Value":0.0,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"UserLength":{"Value":200.0,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"UserLengthPixels":200.0},"SizeColumn":{"UserCollapsed":false,"Length":{"Value":384.46601941747576,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"LengthIncludingGridSplitter":{"Value":385.46601941747576,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"UserLength":{"Value":384.46601941747576,"GridUnitType":1,"IsAbsolute":true,"IsAuto":false,"IsStar":false},"UserLengthPixels":384.46601941747576},"TotalWidth":1561.8640776699031},"IsAdaptiveLayoutOverridden":false}

### Expected behavior

*

### Files Version

2.0.34.0

### Windows Version

Windows 10 家庭版 19043.1165

**Comment by josh-65** [comment]
These I'm pretty sure the file gets made when files edits settings for that folder. I also believe there would be a huge performance impact from it indexing when they have been made or not and then creating them.

**Comment by yaichenbaum** [comment]
This issue will be resolved in the next update.
