### ISSUE TITLE
Column width saving

### ISSUE THREAD

**Issue by Twentydragon** [files-community/Files#6969]
### What's the Problem?

In the **Details** layout, all the columns default to being the same width. This makes files with long names slightly more difficult to work with.

Adjusting them only works until you change directories or close the program, and then do not go back to the way you had them when you return to that directory.

### Solution/Idea

I think there should be some way for user-defined column widths to persist across directories (esp. if your program is set not to keep individual folders' layouts separate) and across sessions.

### Alternatives

There are other layout views I could use, but they do not display file type and size information up front. I could also maximize the window, but I find the program more useful when I can see around it.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Retain user-defined column widths across directories | Must |
| Retain user-defined column widths across sessions | Must |
| Create an option for column widths to automatically fit to their content | Could |

### Files Version

Version: 2.0.34.0 OS Version: 10.0.19043.1348

### Windows Version

Windows 10 Home Version, 21H1, 19043.1348, Windows Feature Experience Pack 120.2212.3920.0

**Comment by josh-65** [comment]
Same as #3974

**Comment by josh-65** [comment]
Same as #6448

**Comment by gave92** [comment]
Merging with #6448
