### ISSUE TITLE
how to set file explorer as default again?

### ISSUE THREAD

**Issue by adonpaul** [files-community/Files#6970]
### Description

i used the experimental feature which allows to set 'Files' as default
but when i try to turn off this feature it doesn't work

it asks for permission to open on registry editor 
but the feature remain on even after granting permissions 
and trying multiple times

need immediate help  plz!!!

### Steps To Reproduce

,.

### Expected behavior

!?!

### Files Version

v2.0.34.0

### Windows Version

win 10 build 19043.1348

**Comment by BanCrash** [comment]
Hi @virus3223, you have to follow the instructions here to unset as default file explorer:

https://files.community/docs/configuring/replace-file-explorer

TL;DR: download [this zip](https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip) and run UnsetFilesAsDefault.reg to restore windows explorer
