### ISSUE TITLE
Files crashed while watching MP4 file

### ISSUE THREAD

**Issue by slkwd** [files-community/Files#6971]
### Description

While watching mp4 training material video, FILES suddenly crashed with just a notice that something went wrong (something that developers did not manage).

### Steps To Reproduce

1. on Windows 11
2. open mp4 file with Film & TV windows 11 app
2. watch it

### Expected behavior

Watch the Video 

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.318

### Windows Version

WIndows 11 21H2 22000.318

### Relevant Assets

N/A

**Comment by gave92** [comment]
Thanks for the report. Could you post the app's log files? Files crashed while open but not in use, correct?

**Comment by slkwd** [comment]
I don’t have any application log and yes, Files crashed while opened but not in use.

V

**Comment by BanCrash** [comment]
@slkwd you can access the log files on Files settings -> About Files -> Open logs folder. Then you can share here "debug.log" and "debug_fulltrust.log"
