### ISSUE TITLE
Unset FILES as default file explorer

### ISSUE THREAD

**Issue by slkwd** [files-community/Files#6972]
### What's the Problem?

Exprerimental feature writes in the registry he is the default browser but:
a) I don't know where (could be useful)
b) it is not possible to rollback

### Solution/Idea

Let the toggle make its job

### Alternatives

Let (at least) me know which registry filed FILES modifies

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.318

### Windows Version

Windows 11 21H2 22000.318

**Comment by josh-65** [comment]
files allows you to set and unset it as default explore in it settings > experimental

**Comment by yaichenbaum** [comment]
To unset Files you'll need to run the "UnsetFilesAsDefaut.reg" from this archive: https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip.

**Comment by slkwd** [comment]
It’s not true.

At least on my Windows 11 (21H2) installation.

When I toggle the option to “Off”,  Windows asks me “Do you want this app to make changes to your device?”

I say YES and  it returns in the “On” position.



 

Is this a bug?

 

V

**Comment by BanCrash** [comment]
Hi @slkwd , there was a bug that caused what you said, but it was fixed on v2.0.35. 

You can follow @yair100 instructions to unset as default file explorer:

> To unset Files you'll need to run the "UnsetFilesAsDefaut.reg" from this archive: https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip.

**Comment by slkwd** [comment]
This solved the problem.

Thanks so much.

 

V
