### ISSUE TITLE
Unable to create libraries

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#6973]
### Description

When try to create a library a pop out opens where I can enter the name (there is no text for the header part should probably add "enter the library name") nothing happen when clicking ok.

### Expected behavior

It should create and show the library in the sidebar

### Files Version

2.0.36.0

### Windows Version

10.0.19043.1348

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7556869/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7556870/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7004.
