### ISSUE TITLE
Cannot open a directory which name include "." from Bundles Widget

### ISSUE THREAD

**Issue by lixinyang123** [files-community/Files#6974]
### Description

Cannot open a directory which name include "." from Bundles Widget
No response after click

### Steps To Reproduce

1. Create a directory which the name include "."  `qwer.asdf`
2. Add directory to bundles widget
3. Restart the software
4. Open the directory from the bundles widget

### Expected behavior

Click the directory in the bundles widget to open it

### Files Version

v2.0.36.0

### Windows Version

Windows 11 10.0.22499.1010

### Relevant Assets

https://user-images.githubusercontent.com/32838371/142268376-730662bb-334d-4626-a000-c8acdedd658c.mp4

**Comment by yaichenbaum** [comment]
@lixinyang123 this issue should be resolved with #7119.
