### ISSUE TITLE
The app doesn't honor default programs to open music files

### ISSUE THREAD

**Issue by Cassual54** [files-community/Files#6976]
### Description

When I double-click a music file (.mp3 or .wav), it runs in MixPad, even if the default app to do so is foobar2000. I have double checked that the default program is selected correctly in Windows.

### Steps To Reproduce

It happens just opening a music file.

### Expected behavior

The file should be opened with the selected default program.

### Files Version

Versión: 2.0.34.0

### Windows Version

Windows 11 Home 21H2 ver. 22000.318

**Comment by yaichenbaum** [comment]
Merging with #2299
