### ISSUE TITLE
Filter for type of files

### ISSUE THREAD

**Issue by lakani** [files-community/Files#6977]
### What's the Problem?

we need a way to filter for File types, names, date modified and in general for any column in the grid columns   

### Solution/Idea

the same way as windows explorer does 

### Alternatives

the same way as windows explorer does 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.0.34.0

### Windows Version

OS Version: 10.0.19043.1320

**Comment by cinqmilleans** [comment]
@lakani It is in progress and coming soon. You can see the progress here 6679.

**Comment by lakani** [comment]
> @lakani It is in progress and coming soon. You can see the progress here 6679.

Excellent, so i will close this as duplicated
