### ISSUE TITLE
Right clicking on the video option in the sidebars library section crashes the app

### ISSUE THREAD

**Issue by PCDSP** [files-community/Files#6978]
### Description

As per title. Trying to add Videos to Favorites... and remove Libraries from *LEFT PANE. 

Really making too much reference to MacOS's designation is not fun!

Another BUG: I want this program to ALWAYS open my favorites tab (no need to double click to show all favs). Sometimes it does, sometimes it does not! 

Also... adjust the font size - as an option - Widescreen dual pane lovely... but... with a bit of tweak to font size as an option would be MARVEL!

Love the dual pane mode, old school, Windows Commander comes to mind! 

WINDOWS 11 MOTTOS:

PS: OFF TOPIC: 

1. EDGE IS A PILE OF SH*T, SO BILLY GOAT, PLEASE SPARE ME AND ALL OF USE!
2. TASKBAR SHOULD BE ALLOWED TO POSITION ANYWHERE, DON'T BE COMMUNISTS! STOP THE FINGERLICKING APPLE DOCK SUCK'UP!
3. 

### Expected behavior

Pin to Favorites... of course. 

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.346

### Windows Version

Windows 11 21H2

### Relevant Assets

[debug_fulltrust.log](https://github.com/files-community/Files/files/7561353/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7561355/debug.log)

**Comment by yaichenbaum** [comment]
@PCDSP I'm not able to reproduce this on my end, can you add some repro steps so I can verify we're trying the same thing?

**Comment by PCDSP** [comment]
In the Libraries tab, right click on Video - instant crash. 

Not in the Favorites View but 'Library' side pane view. 

Same goes for Pictures and any other Library tab shortcut... right click = instant crash of Files!

**Comment by yaichenbaum** [comment]
Interesting, I can't reproduce this on my end but I'll add this issue to the project board so we can keep track of it.

**Comment by PCDSP** [comment]
I can send you a video but rather not post publicly... if you're in the development team, send me a PM and I'll upload to my gdrive...

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
