### ISSUE TITLE
Install without Microsoft Store & Windows App Installer

### ISSUE THREAD

**Issue by ItsCubeTime** [files-community/Files#6979]
### What's the Problem?

![image](https://user-images.githubusercontent.com/20190653/142396241-2119eff4-a1c0-4d10-8066-687f02832943.png)

Hi, could we have the option to install files without Microsoft store or the windows app installer? Windows app installer has been broken for me for quite a long time, would be nice if you had a 3rd party/standalone installer.

### Solution/Idea

-

### Alternatives

-

### Priorities

-

### Files Version

-

### Windows Version

10.0.19043.1288

**Comment by yaichenbaum** [comment]
@ItsCubeTime Files is a packaged app and the only way to install it is with appinstaller. Hopefully this guide can help you restore appinstaller so you can install Files. https://yairai.medium.com/how-to-restore-windows-10-app-installer-99c15b7c3ec4
