### ISSUE TITLE
Add option to hide the tab navigation bar when only one tab is open

### ISSUE THREAD

**Issue by JosephM101** [files-community/Files#6980]
### Solution/Idea

It'd be nice to have an option you could toggle that makes the tab bar invisible/collapsed if only one tab is open. It might make the already-clean interface look a bit cleaner. Also, it adds an extra area of customization.

### Alternatives

N/A

### Files Version

2.0.34.0

### Windows Version

10.0.22499.1010

**Comment by yaichenbaum** [comment]
@JosephM101 after gathering feedback, we've learned that most users use the tabs feature so we don't plan on implementing this change.
