### ISSUE TITLE
automatically clear completed tasks

### ISSUE THREAD

**Issue by cleuton4k** [files-community/Files#6982]
### Solution/Idea

automatically clear completed (and uncompleted/error) tasks and keep only those in progress.

### Alternatives

automatically clear completed (and uncompleted/error) tasks and keep only those in progress.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.0.34

### Windows Version

windows 10 home 64 bits 21h1

### Additional comment

![01](https://user-images.githubusercontent.com/90144967/142464493-84a44aba-589c-4cd1-a431-ea458f4fde59.jpg)

**Comment by yaichenbaum** [comment]
We intentionally keep completed tasks in the list to inform the user it finished successfully. We are working on a clear all button though to enable users to quickly clear the tasks.
