### ISSUE TITLE
when a program tries to open a window to select files, open through FILES.

### ISSUE THREAD

**Issue by cleuton4k** [files-community/Files#6983]
### Solution/Idea

when a program tries to open a window to select files, open through FILES. instead of an explorer window.

### Alternatives

when a program tries to open a window to select files, open through FILES. instead of an explorer window.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.0.34

### Windows Version

windows 10 home 64 bits 21h1

### Additional comment

![02](https://user-images.githubusercontent.com/90144967/142466143-28aa40ca-176d-427b-a818-c328adfa126e.jpg)
![SharedScreenshot](https://user-images.githubusercontent.com/90144967/142466295-c34fd9b5-8266-4d6f-abab-52f53495d766.jpg)

**Comment by gave92** [comment]
Implemented but disabled, waiting for #6314.
