### ISSUE TITLE
exibir o nome completo dos arquivos

### ISSUE THREAD

**Issue by cleuton4k** [files-community/Files#6984]
### Solution/Idea

display the full name of the files as it is very annoying to have to hover over the files to see the full name.

### Alternatives

display the full name of the files as it is very annoying to have to hover over the files to see the full name.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.0.34

### Windows Version

windows 10 home 64 bits 21h1

### Additional comment

![01](https://user-images.githubusercontent.com/90144967/142467223-1666c2a1-4b61-46d9-b975-bef2daa4e95b.jpg)
![02](https://user-images.githubusercontent.com/90144967/142467226-29c06b9a-0fb1-4899-89b6-5bb5b36e02a2.jpg)

**Comment by yaichenbaum** [comment]
Merging with #1033
