### ISSUE TITLE
IMAGE PREVIEWS

### ISSUE THREAD

**Issue by esdcgit** [files-community/Files#6993]
### What's the Problem?

So, i dont know how to word this correctly.

The application works perfectly, just it doesn't show thumbnail previews for image files.

Would this be a feature that is part of the future planning of the software?

Amazing software though.

### Solution/Idea

Create image thumbnails previews that work?

### Alternatives

I dont know what alternative their would be, without this feature i need to revert to other software.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.318

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎2021/‎09/‎10 OS build	22000.318 Experience	Windows Feature Experience Pack 1000.22000.318.0

**Comment by gave92** [comment]
Thanks for the kind feedback. Could you post a screenshot of Files VS windows explorer showing the missing thumbnails?

**Comment by waltdestler** [comment]
> Thanks for the kind feedback. Could you post a screenshot of Files VS windows explorer showing the missing thumbnails?

I'm not the original poster, but I'm also having this issue with some but not all images. Here's a screenshot where *most* of the thumbnails are not being displayed.

![image](https://user-images.githubusercontent.com/1624160/143686478-7e70bd7c-1947-4745-a956-1d6039397e78.png)

These are all perfectly valid png and jpg image files that open fine if I double-click on them. Note that the preview pane itself does work:
![image](https://user-images.githubusercontent.com/1624160/143686524-29dbc857-e10e-4355-99c3-0522ca628831.png)

Once I double-click on a file and view it in the Windows Photos app, I can then refresh the folder in FIles and the thumbnail will be visible for that file.

Interestingly, the files without thumbnails *also* don't have thumbnails when viewed in the Photos app:
![image](https://user-images.githubusercontent.com/1624160/143686631-729cbaa2-cd08-47b5-ac95-cdd402b5d434.png)

Though if I view the folder in the regular Windows File Explorer, it *does* show the thumbnails for all the files. It can take a few seconds for it to *load* all the thumbnails, but once it does, I can then also see the thumbnails in Files.

Hope this helps!

**Comment by yaichenbaum** [comment]
@gave92 I can reproduce this issue as well, interestingly enough, refreshing the directory usually loads the missing thumbnails.

**Comment by cloo** [comment]
I get many thumbnails missing as too: jpg, png and pdf. 
Larger thumbnails are not generated at all.
 
![220127-151728](https://user-images.githubusercontent.com/651760/151366851-ade04be1-bd29-460e-bb46-5c6a696215db.png)

![220127-151822](https://user-images.githubusercontent.com/651760/151366743-6edef92e-5d96-42ec-89b3-42b24035cba8.png)
1366737-1c799d16-69d9-433c-b5e1-986ae5b634b6.png)
![220127-151829](https://user-images.githubusercontent.com/651760/151366752-d7e5b8e9-d430-4997-8125-e71f636c9b19.png)


Version: 2.1.2.0
Windows 11, OS Version: 10.0.22000.434

**Comment by gave92** [comment]
This issue should be fixed in the preview version.
