### ISSUE TITLE
Proper Symlink Support

### ISSUE THREAD

**Issue by pr4dy** [files-community/Files#6995]
### Description

Symlink files and folders are not shown as .symlink files and the properties information is empty. Whereas in the original windows file explorer, it correctly shows the filetype as .symlink and has properties information like what's the target and path etc.
Also drag and drop functionality is not working on symlink files and folders in the files app, whereas it works in original windows file explorer app.

### Steps To Reproduce

1. Create a symlink for a file or folder
2. View the filetype and properties in both files app and windows file explorer app

### Expected behavior

1. Proper filetype should be given
2. Drag and drop support for symlinks should be done

### Files Version

v2.0.34.0

### Windows Version

Windows 11 21H2 22000.346

### Relevant Assets

Picture of symlinks in Files app
![files1](https://user-images.githubusercontent.com/92441536/142654998-98e77ca2-211e-4447-920c-170c95885e19.png)

Picture of symlinks in File Explorer app (which is expected)
![explorer1](https://user-images.githubusercontent.com/92441536/142655078-ea36099d-935c-4e1d-bd90-be6d009c9578.png)

Picture of symlink properties in Files app vs File Explorer app

![FilesVsExplorer1](https://user-images.githubusercontent.com/92441536/142655756-4bc6ea60-acee-41e2-89cc-24c8d846507b.png)
![FilescsExplorer2](https://user-images.githubusercontent.com/92441536/142655778-d7a85a74-68a7-498d-8fa8-48f32dae099c.png)

Drag & Drop Functionality not working in Files

https://user-images.githubusercontent.com/92441536/142660214-be706681-ce27-47a5-943e-8e51b82446a0.mp4

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7006.
