### ISSUE TITLE
Feature: Add Storage Sense option  when right clicking drives

### ISSUE THREAD

**Issue by JosephM101** [files-community/Files#6996]
### Solution/Idea

File Explorer has an option to open the Disk Cleanup tool when you view the properties of a fixed drive. It'd be nice to have that option in the Files app.

### Requirements
- Add storage sense option when right clicking drives
- Apply this change to the sidebar, layouts, and drives widget

### Files Version

2.0.34.0

### Windows Version

10.0.22499.1010

**Comment by gave92** [comment]
This is implemented already, right?

**Comment by yaira2** [comment]
Thank you for your feedback, this is on our todo list and is being tracked in #14683.
