### ISSUE TITLE
Bug: Rename warning prompt shouldn't display when renaming files from the properties window

### ISSUE THREAD

**Issue by MarcAnt01** [files-community/Files#6998]
### Description

When renaming a file from properties window the file extension rename dialog appears on the main Files window and the properties window overlaps it

### Steps To Reproduce

1. Open properties window
2. Change the file extension from there
3. Click ok

### Expected behavior

Don't display prompt if the rename action is coming from the properties window

### Files Version

2.0.36.0

### Windows Version

Windows 11 21H2 22000.346

### Relevant Assets

![image](https://user-images.githubusercontent.com/43090263/142700777-81829ef6-480e-4ecf-8dfb-9767c54b9cbb.png)

**Comment by yaichenbaum** [comment]
I don't think we should display this dialog at all if you're making the change from the properties window

**Comment by MarcAnt01** [comment]
> I don't think we should display this dialog at all if you're making the change from the properties window

Why? In the end the same action is being performed even if from a different place

**Comment by yaichenbaum** [comment]
The properties window is already a more advanced tool and someone renaming the file through it is more likely to know what they're doing, the option to rename files from the regular layout is used by a much wider range of users who may not understand the concept of file extensions.
