### ISSUE TITLE
Experimental Features

### ISSUE THREAD

**Issue by ethandii** [files-community/Files#7000]
### Description

can't check of the default file explorer option in experimental features!
i also have backed up my reg keys but cant import them or reset them.
i also do not want to reset my whole pc! 

### Expected behavior

it has to check of and i have to be able to get back to the original file explorer!

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.348

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎2021-‎10-‎27 OS build	22000.348 Experience	Windows Feature Experience Pack 1000.22000.348.0

**Comment by BanCrash** [comment]
Hi @ethandii , you have to follow the instructions here to unset as default file explorer:

https://files.community/docs/configuring/replace-file-explorer

TL;DR: download [this zip](https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip) and run UnsetFilesAsDefault.reg to restore windows explorer
