### ISSUE TITLE
Vansh Maheshwari

### ISSUE THREAD

**Issue by VanshM17** [files-community/Files#7001]
### Description

When I go to the Settings Tab and click on preferences, the app suddenly closes displaying "Something went wrong". Also the settings which I had modified also goes back to default after relaunching the app. Please fix this issue and make it more smoother like  File Explorer. The only good feature is multiple tabs, else everything is ordinary and not optimized. 

### Steps To Reproduce

Please modify the app to look more like File Explorer.
Speed up the process of loading UI as it takes much more time

### Expected behavior

Improve the functionality of app.

### Files Version

1.5

### Windows Version

Windows 11 build 22000

**Comment by gave92** [comment]
Thanks for the report.
- Please post the app's debug logs (you can reach them from Settings > About > Open log location)
- Could you also post the contents of the "terminal.json" file (found in the same folder as the log files, under "settings" folder)
- Could you also confirm the app version? Version 1.5 is pretty old
