### ISSUE TITLE
Request for option to override every folder's view option.

### ISSUE THREAD

**Issue by CCSerious** [files-community/Files#7002]
### What's the Problem?

In windows default explorer, you can choose to override and change every folder's default view type, such as Extra large icons, Large icons, Medium icons, Small icons, List, Details, Tiles, and Content. I want the default folder view type to be set as List intead of Details. But it's impossible for me change it for every folder.

### Solution/Idea

Add this feature also for files v2. Also, it would be great if the quick access pinned folder on windows default explorer can be inherited for files v2. It's annoying to manually add every shortcut folder that I have pinned before on windows default explorer quick access. Thank you very much.

### Alternatives

nil.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

v2.0.34

### Windows Version

Windows 11 21H2 22000.282

**Comment by gave92** [comment]
You can set a global/default layout for all folders in Files settings > Files and folders > Turn off "use individual preferences for folders".

**Comment by CCSerious** [comment]
> You can set a global/default layout for all folders in Files settings > Files and folders > Turn off "use individual preferences for folders".

Hello gave92, thank you for your reply. It works. Yet, I want to set some folders to be Large icons, such as videos and images. So, the individual preferences for folders is still needed for me. Meanwhile, I want to keep the view type to be List. As soon as, I turn the individual preferences for folders option back to be on. Every other folder view type becomes Details again. I hope you can make these two things co-exist at the same time.

**Comment by CCSerious** [comment]
> You can set a global/default layout for all folders in Files settings > Files and folders > Turn off "use individual preferences for folders".

Hello gave92, thank you for your reply. It works. Yet, I want to set some folders to be Large icons, such as videos and images. So, the individual preferences for folders is still needed for me. Meanwhile, I want to keep the view type to be List. As soon as, I turn the individual preferences for folders option back to be on. Every other folder view type becomes Details again. I hope you can make these two things co-exist at the same time.

**Comment by CCSerious** [comment]
1 small bug found. When you clean the recycle bin and return to the main page of files v2, the disk space of drives do not refresh. Also, you cannot manually press refresh button either. You have to close the app and open it again to see the changes.

**Comment by gave92** [comment]
Merging with #4155
