### ISSUE TITLE
Trying to pin a Network Device to Favorites crashes the app

### ISSUE THREAD

**Issue by IrealiTY** [files-community/Files#7003]
### Description

I usually have my network devices pinned in the Favourites (NAS, NUC, Pi etc) and not folders from those devices.
Trying to drag the device from 

### Steps To Reproduce

1. Click on Network drives
2. Click on Network
3. Wait for devices to load (anyway this could be sped up somehow? :D )
4. Drag device from listed devices to Favorites

![image](https://user-images.githubusercontent.com/1223686/142723851-75cbeea1-303f-41a6-92ab-c93d33afc1a8.png)

### Expected behavior

Device being added to Favorites-list

### Files Version

2.0.34.0

### Windows Version

Windows 11 Pro 21H2 22000.318

### Relevant Assets

[debug_fulltrust.log](https://github.com/files-community/Files/files/7574412/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7574413/debug.log)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7004.
