### ISSUE TITLE
Files crashes when I enter my main Images folder.

### ISSUE THREAD

**Issue by FenixAlfa159** [files-community/Files#7005]
### Description

When I enter my main Images folder (the default one), Files just load something for 1 sec and then blinks, then proceeds to crash, closing itself with not error windows.no

### Steps To Reproduce

1. Go to your main images folder, where you save all sub folders of stored images.
2. The app closes itself.subfolders

### Expected behavior

I expect to program to not close and load my files so I can see them, move them or share them.

### Files Version

Versión: 2.0.34.0 OS Version: 10.0.22000.318

### Windows Version

Windows 11 Pro Versión	21H2Compilación del SO 22000.318 Experiencia	Paquete de experiencia de características de Windows 1000.22000.318.0

### Relevant Assets

[debug_fulltrust.log](https://github.com/files-community/Files/files/7574985/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7574986/debug.log)

**Comment by yaichenbaum** [comment]
@FenixAlfa159 is this still an issue in the preview version? https://files.community/download/preview
