### ISSUE TITLE
OVERWRITE/ REPLACE - Why drop downs?

### ISSUE THREAD

**Issue by PCDSP** [files-community/Files#7009]
### What's the Problem?

When trying to replace say 10 files, there's no global option to 'REPLACE EXISTING'!

Instead you have a dropdown option for each file!

Now that's just sad!

COPY TASK - Why not show speed at which it happens?

Very useful feature of Windows Explorer!

### Solution/Idea

Drop Down buttons - ADD a 'Replace all' and 'Rename all' option

Show transfer rate in Copy process!

Thank you. 

### Alternatives

I had to remove Files as default, as I can't spend the time to select Replace on individual files!

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.348

### Windows Version

Windows 11 Pro 21H2 22000.348

**Comment by HJH201314** [comment]
I agree!

**Comment by gave92** [comment]
A better UI is coming but at the moment you can:
1) Select replace existing for one file
2) Right click on that file
3) Select "apply for all'
