### ISSUE TITLE
Can't turn off "Default File Explorer"

### ISSUE THREAD

**Issue by DaYiM90** [files-community/Files#7010]
### Description

I use the application for a while,
But for some reasons I prefer to return to the Windows File Explorer

But i can't turn the default options off; it immediately turns back on.
When I uninstalled the program it broke Windows File Explorer in many ways.

### Expected behavior

Be able to Turn it Off.

### Files Version

2.0.34.0

### Windows Version

Windows 11

**Comment by BanCrash** [comment]
Hi @DaYiM90  , you have to follow the instructions here to unset as default file explorer:

https://files.community/docs/configuring/replace-file-explorer

TL;DR: download [this zip](https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip) and run UnsetFilesAsDefault.reg to restore windows explorer

**Comment by DaYiM90** [comment]
Thank you so much.
