### ISSUE TITLE
Scroll-bar doesn't work with touchpad gestures while selecting custom themes

### ISSUE THREAD

**Issue by uttsav1025** [files-community/Files#7011]
### Description

The scrollbar doesn't seem to work when scrolling down using the touchpad gesture, 

The indication of the scrollbar and the themes tab are not in sync, which is making selecting themes below the visible region impossible.

While there is a fix for this by clicking and dragging the scroll bar once, the touchpad gesture doesn't work without doing this.

https://user-images.githubusercontent.com/74333675/142752580-d9fe92b4-f49a-4c85-ac3b-0ddc29a7e39d.mp4

### Steps To Reproduce

1.Go to settings.
2.Click on the drop-down icon on custom themes (assuming some custom themes have been added).
3.Use the touchpad gesture to scroll downwards/upwards to select your desired theme. (Doesn't work)
4.Click and drag the scrollbar thumb.  (Works)
5.Try the touchpad gesture again. (works now)

### Expected behavior

The custom theme-tab is expected to move in sync with the scrollbar-thumb while using the touchpad gesture.

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.318

### Windows Version

Windows 11 Pro Version	21H2 22000.318

### Relevant Assets
https://user-images.githubusercontent.com/74333675/142752580-d9fe92b4-f49a-4c85-ac3b-0ddc29a7e39d.mp4

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
