### ISSUE TITLE
When I rename a shortcut of a folder, it is no longer a shortcut file

### ISSUE THREAD

**Issue by HJH201314** [files-community/Files#7012]
### Description

When I rename a shortcut of a folder, it turns into an empty file which cannot jump to the correct space.

### Steps To Reproduce

1.Create a shortcut of a folder
2.Rename the shortcut
3.It occurs

### Expected behavior

It must correctly rename the shortcut

### Files Version

2.0.34.0

### Windows Version

Windows 11 21H2 22000.348

**Comment by josh-65** [comment]
Same as #5823

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7015.
