### ISSUE TITLE
Unknown File Deletion Error

### ISSUE THREAD

**Issue by Neurectum** [files-community/Files#7013]
### Description

I just tried to remove some files out of the Downloads folder when the application crashed... I don't exactly know what happened.

### Steps To Reproduce

1. Go to Downloads
2. Delete multiple files
3. Instantly delete other files in the downloads folder before the process (2.) is finished.
4. BUG

### Expected behavior

The application will close and an error message will pop up.

### Files Version

2.0.34.0

### Windows Version

10.0.19043.1348

**Comment by gave92** [comment]
Thanks for the report. Please post the app's log files.
