### ISSUE TITLE
Faster animations on settings pane

### ISSUE THREAD

**Issue by ttmx** [files-community/Files#7016]
### What's the Problem?

The settings window animation when switching settings panes is slightly too slow in my opinion
![image](https://user-images.githubusercontent.com/12669467/142783175-b33c21ed-264a-4103-860f-f96970a77a9c.png)
![image](https://user-images.githubusercontent.com/12669467/142783183-d78eaaae-46ab-4d03-8aa7-589c031fdc79.png)

This animation ^

### Solution/Idea

Just play with it a bit to make it faster. I don't know the code base but its likely just some simple value change.

### Alternatives

Just ignoring its slight slowness is a simple and not really bothersome "workaround". 
This is definitely not a major bother, but it should also be a very simple fix.

### Files Version

Version: 2.0.39.0 OS Version: 10.0.22000.318

### Windows Version

Windows 11 Education Version 22000.318

**Comment by yaichenbaum** [comment]
@ttmx this is the default WinUI animation and it's consistent with the other animations throughout the app, I recommend opening an issue on the WinUI repo regarding the speed as we're trying to keep the animation consistent with other apps on Windows. https://github.com/microsoft/microsoft-ui-xaml
