### ISSUE TITLE
Is the developer aware of the Files loading speed problem?

### ISSUE THREAD

**Issue by madlifer** [files-community/Files#7018]
### What's the Problem?

First of all,Thank you for your dedication.I have to say that Files can be said to be my ideal resource manager in terms of UI and function,but there is a problem that is hard to bear is the problem of loading speed. 

I don’t know if it’s the animation loading speed or what caused the problem,it is much worse than the native resource manager list loading speed.

Cause I did not see this problem in the project milestones, nor any feedback on this problem in Issue, I would like to ask the developer's opinion on the problem. What caused the problem?  The problem will be fixed?

### Solution/Idea

Here‘s An GIF to explain the prolem, It should  seem obvious . https://imgur.com/a/0q4iSdS

### Alternatives

I suggest that the loading speed issue should be listed as a more important matter. As a product manager, in my opinion, this will be a very easy point to make users uninstall.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

V2.0.34.0 OS Version: 10.0.22000.318

### Windows Version

Windows 11 Pro 21H2  22000.318

**Comment by yaichenbaum** [comment]
@madlifer performance is a top priority for us and do our best to optimize the codebase. Every release of Files contains more improvements in this area, but it's an ongoing effort and there isn't one thing we can do to fix all the performance issues. We have a main issue to track the performance and optimization in Files #4180 but please do open additional issues for specific areas that you think need improvements.

**Comment by yair100** [comment]
@madlifer we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
