### ISSUE TITLE
Unable to recognize WSL file system created by wsldl.

### ISSUE THREAD

**Issue by zsh2401** [files-community/Files#7020]
### Description

As is written in the title, the FilesV2 application can not find/recognize WSL virtual machine created by [https://github.com/yuk7/wsldl](yuk7/wsldl).  On my computer, I have uninstalled Ubuntu WSL which has been offered in the Microsoft Store. Instead, I have installed [https://github.com/yuk7/ArchWSL](yuk7/ArchWSL). It is weird that Windows Explorer can correctly present its file system, but FilesV2 not. In addition, I have turned  "Show WSL Section" on in settings panel.

![image.png](https://i.loli.net/2021/11/22/BKc15uikDxCrXA3.png)

### Steps To Reproduce

1. Install [https://github.com/yuk7/ArchWSL](yuk7/ArchWSL)
2. Bug appears.

### Expected behavior

Can correctly recognize ArchWSL file system.

### Files Version

v2.0.34

### Windows Version

Windows 11 21H2 22000.348

**Comment by yaichenbaum** [comment]
@zsh2401 did you originally setup WSL on Windows 10? I had this issue after updating to Windows 11 but it was resolved after resetting Windows.

**Comment by zsh2401** [comment]
> @zsh2401 did you originally setup WSL on Windows 10? I had this issue after updating to Windows 11 but it was resolved after resetting Windows.

The current WSL machiens was setup on Aug, after I have upgraded my computer from Windows 10 to Windows 11 with Windows Update, in other words, no resetting, no erasing.

**Comment by yaichenbaum** [comment]
@zsh2401 do you have a fresh install of Windows you can test on to see if the same issue exists?
