### ISSUE TITLE
Can't unset Files as default.

### ISSUE THREAD

**Issue by Luzkan** [files-community/Files#7024]
### Description

I can't unset the Files as default file explorer. It could be because of reinstallation of the Files app, but I don't really know (which I had to do, because Files crashed immediately after update and could not browse files at all).

### Steps To Reproduce

- Install Files.
- Set it as default file explorer.
- Reintall Files.
- Attempt to switch back Files to no longer be the default file explorer.
- Confirm the registry change operation with admin rights
- Nothing happends

### Expected behavior

Files no longer is the default file explorer.

### Files Version

v2.0.34

### Windows Version

Windows 11 21H2

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7579822/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7579823/debug_fulltrust.log)

**Comment by BanCrash** [comment]
Hi @Luzkan , you have to follow the instructions here to unset as default file explorer:

https://files.community/docs/configuring/replace-file-explorer

TL;DR: download [this zip](https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip) and run UnsetFilesAsDefault.reg to restore windows explorer
