### ISSUE TITLE
Crash when Open

### ISSUE THREAD

**Issue by kleytonroan** [files-community/Files#7026]
### Description

I don't know how that happen, but when I open de Files, it's freezy and crashed, than I open it again and it Works!

I notice that "Devices" Right Menu don't appear when it crashed. Now it's working normally

### Steps To Reproduce

Just Open Files

### Expected behavior

Open the Program without crash

### Files Version

Versão: 2.0.34.0 OS Version: 10.0.22000.318

### Windows Version

Windows 11 Pro 21H2 22000.318

**Comment by gave92** [comment]
Thanks for the report. Could you upload the app's log files?

**Comment by kleytonroan** [comment]
[debug.log](https://github.com/files-community/Files/files/7582636/debug.log
[debug_fulltrust.log](https://github.com/files-community/Files/files/7582638/debug_fulltrust.log)
)

**Comment by kleytonroan** [comment]
Sure!
[debug.log](https://github.com/files-community/Files/files/7582644/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7582647/debug_fulltrust.log)

**Comment by gave92** [comment]
Need to chack but this one should be due to drive icon randomly failing to load as it was in other places.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7069.
