### ISSUE TITLE
Copy to Network Locations always requires manual refresh to show

### ISSUE THREAD

**Issue by infuriatedcodex** [files-community/Files#7027]
### Description

When you copy a file from a local folder to another SMB share, it requires the user to manually refresh with the F5 key for it to show in the main window.

This is **NOT** a problem when copying files between local folders.

### Steps To Reproduce

For this test I used a sufficiently large ISO file (Linux ISO).

Place the ISO into any local folder of your choice.
Prepare a remote folder with the appropriate permissions for you to copy the file to.
- Easier if the local and remote pc's are in the same workgroup (or domain).
- the remote folder should have the "Authenticated Users" group permission to atleast modify.

Open a new tab to your local (source) folder and another tab to the remote (destination) folder.
Copy the file (drag, shortcut icons or keyb shortcuts, doesn't matter) across.

Copy operation completes and verified in "ongoing tasks" but you cannot see the file until you manually hit F5.

### Expected behavior

File should appear in the remote location immediately after the copy process completes, like the native explorer.

### Files Version

Version: 2.0.34.0

### Windows Version

OS Version: 10.0.22000.318

### Relevant Assets

See screenies below...
![20211122_113559 - ApplicationFrameHost309](https://user-images.githubusercontent.com/40537324/142857231-54253828-0f49-4c9f-bb92-f6f5bb5099aa.jpg)
![20211122_113605 - ApplicationFrameHost310](https://user-images.githubusercontent.com/40537324/142857248-a52487a1-77c2-41a3-8265-d609dee94628.jpg)
![20211122_113619 - NVIDIA_Share311](https://user-images.githubusercontent.com/40537324/142857255-77c4d3e3-4ed5-4346-a261-cfea0ceac082.jpg)

![20211122_113625 - ApplicationFrameHost312](https://user-images.githubusercontent.com/40537324/142857264-4a947daa-8e68-46e1-8644-1423cbbbfa15.jpg)

**Comment by Firidan** [comment]
It also affects renaming files or folders on network share - you need to press F5 to see changes

**Comment by gave92** [comment]
Merging with #5869
