### ISSUE TITLE
Failed tasks show check mark

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#7028]
### Description

![image](https://user-images.githubusercontent.com/26977075/142871748-32bacf04-26b0-4488-a78b-2f7c5564a034.png)
I have seen this for multiple deletion failed from the recycle bin

### Expected behavior

It should show a X

### Files Version

2.0.36.0

### Windows Version

10.0.19043.1348

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7581603/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7581604/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7500
