### ISSUE TITLE
Remove Click Animation

### ISSUE THREAD

**Issue by kleytonroan** [files-community/Files#7029]
### What's the Problem?

When I click in a File or Folder, an animation is executed in Windows 10, but it's annoy and low performance, in Windows 11 the animation isn't executed, more details in video

Sometimes by the slow, I execute doble click to open a folder, but enter in rename file mode
Sometimes it's freezy and take a time to open a folder or select the file

### Solution/Idea

Add an option to change animation style and disable

### Alternatives

option to change or/and disable animations

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Change Animation Execution "True | False " or "N king of animation, but add possibility to disable" | Must |

### Files Version

Versão: 2.0.34.0 OS Version: 10.0.22000.318

### Windows Version

Windows 10 Pro 21H2 19044.1348

### Additional comment

https://user-images.githubusercontent.com/19601133/142875377-5bbf59fd-5722-4d09-9792-7bac201921e1.mp4

**Comment by yaichenbaum** [comment]
This issue is resolved in Windows 11. We tried the fix in Windows 10 but it had a hit on performance so we don't plan to implement it.

**Comment by anupdebnath** [comment]
Hi, just asking if there is an alternative solution/animation that can be added that doesn't hit on performance at the same time does not hurt my eyes?

**Comment by yaichenbaum** [comment]
@anupdebnath we haven't found one but we will try to update this for Windows 11 if a solution is found.
