### ISSUE TITLE
Grouping Files

### ISSUE THREAD

**Issue by nfe213** [files-community/Files#7030]
### What's the Problem?

In SolidWorks projects a parent assembly relies on many individual part drawings. These parts also get a drawing file linked as well as several exported files for various steps in the manufacturing process.

The parent assembly, part, and drawing all need to be in the same parent assembly, but once you get into larger assemblies with thousands of parts and 2 - 3 export of each part, you get a giant mess of files. 

### Solution/Idea

**Add a grouping feature where users can pin files together**. Following the SolidWorks example, the part file would be on top, and then by hovering on the group or maybe a button in the context menu the user can see the related drawing files, exports, etc.

It would also be nice to be able to preform context menu actions on these groups. For example, sometimes parts get renamed, causing it to lose its drawing (the drawing needs to have the same name as the part file), then the exports for the file also don't match the new file name which causes confusion down the line. This could be solved with the ability to rename the group of files.

Additionally, it would be nice to be able to setup rules, so if I initialize this feature in a new project directory, I can configure it to execute a rule that groups all like file names with mismatched file types together.

### Alternatives

Another solution I had considered was a dependency view. Solidworks has another app called [Treehouse](https://www.goengineer.com/blog/solidworks-treehouse-getting-started#:~:text=SOLIDWORKS%20Treehouse%20is%20a%20standalone,even%20start%20modeling%20in%20SOLIDWORKS.) that allows users to see the structure of an assembly, but since SolidWorks is closed source this dependency view would need to be arranged manually which would take hours for large assemblies, or it would need to rely on the SolidWorks API which is expensive and of course  would not help users of other file types.

Another solution might be an option for a 'fake' folder where users could group files in a folder that isn't recognized by Windows so all the files keep their original path so they can be found by SolidWorks but are still organized for the user.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Organize files for the user without changing the file's path. | Must |
| Be easy to setup for large volumes of files. | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

v2.0.34.0

### Windows Version

Windows 10 Pro Version	21H1 19043.1348

**Comment by yaichenbaum** [comment]
@nfe213 you can already group by file type, is this the option you're looking for?

**Comment by nfe213** [comment]
No - the intent of this feature would be to reduce the number of files immediately visible to the user in list view. 

Let me see if I can whip up a demo of what I'm thinking - that might be easier than trying to explain again.

**Comment by yaichenbaum** [comment]
> No - the intent of this feature would be to reduce the number of files immediately visible to the user in list view.
> 
> Let me see if I can whip up a demo of what I'm thinking - that might be easier than trying to explain again.

@nfe213 kind of like a filter?

**Comment by nfe213** [comment]
https://nfe213.github.io/pin-files-demo/

Check this out. Its a very rough demo but should get the point across. Default view is up top and my proposal is down below. 

It might just be that there aren't enough users to warrant this feature in the main branch; if that is the case, how much work would it be for me to implement this feature on my own? I'm familiar with web dev stuff so XAML shouldn't be too hard to pick up, I've done some Python & Arduino C but haven't done any UWP or Win UI3 or whatever Microsoft is calling it these days. Would this be a handful of weekends worth of work or a bigger endeavor?

**Comment by yaichenbaum** [comment]
@nfe213 correct me if I'm wrong but what you're looking for is an option to link items and group them together in a list. I think that the tags feature will work for this once we improve the feature.
