### ISSUE TITLE
Update OneDrive status icons

### ISSUE THREAD

**Issue by maicol07** [files-community/Files#7031]
### What's the Problem?

Files icons for OneDrive status are a bit tiny and "secondary", compared to the ones of File Explorer

### Solution/Idea

Change current icons to something more colorful, like explorer ones, but better

### Alternatives

None

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to see faster the status of their files on OneDrive | Should |

### Files Version

2.0.36

### Windows Version

Windows 11 Pro 22504.1010

**Comment by yaichenbaum** [comment]
We don't use colored icons in this area as we don't want to draw extra attention to the status icons, rather we opted for something more subtle that does the job without drawing extra attention.
