### ISSUE TITLE
Save favorites in the settings json

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#7032]
### Description

My files (2.0.36) has vertical tabs button off but when importing to files (2.0.39) it gets turned on again. Side bar pins and home screen widgets don't get saved or applied if they are saved.

### Expected behavior

It should correctly apply/save settings stated above

### Files Version

2.0.39.0

### Windows Version

10.0.19043.1348

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7582928/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7582929/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
The sidebar favorites are considered settings and are stored in a different file but perhaps we can merge them into the settings file.

**Comment by gave92** [comment]
@yair100 What do you think of exporting all settings in a .zip file? I've pushed a test branch [here](https://github.com/gave92/files-uwp/tree/issue_7032)  that imports/exports all settings to/from a zip file.
It includes: pinned items, user settings, file tags, terminal profiles, bundles. All settings are applied without restart.

<img src="https://user-images.githubusercontent.com/9673091/143334692-5f3a5a46-f31b-419c-9647-44e8ce270f30.png" width="400"/>

**Comment by yaichenbaum** [comment]
@gave92 that's a great idea! I still think we should merge the terminal settings (or remove them all together) as well as the pinned items with the main settings file.

**Comment by gave92** [comment]
Do you mean merging them only when exporting or also in the app? If we merged the terminal profile with the main settings, clicking on "Edit Terminals" would open a file full of stuff not related to terminals.

**Comment by yaichenbaum** [comment]
> Do you mean merging them only when exporting or also in the app? If we merged the terminal profile with the main settings, clicking on "Edit Terminals" would open a file full of stuff not related to terminals.

@gave92 I edited my original message.

**Comment by yaichenbaum** [comment]
@josh-65 this issue should be resolved with #7078.
