### ISSUE TITLE
crash thing

### ISSUE THREAD

**Issue by BanzOnYt** [files-community/Files#7033]
### Description

in settings i click prefrences then it closed than a notification said something about me reporting this biug

### Steps To Reproduce

go to settings
click on prefrences
a notification pops up
it closes

### Expected behavior

it works now but
it was supposed to not crash when picking prefrences to change your setings

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22504.1000

### Windows Version

windows 11 dev 22504.100 (there is a pending update i havent installed yet)

### Relevant Assets

[debug_fulltrust.log](https://github.com/files-community/Files/files/7583398/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7583400/debug.log)

**Comment by gave92** [comment]
Thanks for the report. Could you share a screenshot of Files after opening? Does the sidebar take a long time to load?

**Comment by gave92** [comment]
This issue should be fixed in #7017.
