### ISSUE TITLE
While copying multiple files/folders from one path to another having folder with same names, provision for single option selection should apply for all files/folders

### ISSUE THREAD

**Issue by adlingepa** [files-community/Files#7034]
### What's the Problem?

While copying multiple files/folders from one path to another having folder with same names, provision for single option selection should apply for all files/folders

### Solution/Idea

While copying multiple files/folders from one path to another having folder with same names, provision for single option selection should apply for all files/folders

### Alternatives

While copying multiple files/folders from one path to another having folder with same names, provision for single option selection should apply for all files/folders

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

v1.5

### Windows Version

Windows 10

### Additional comment

While copying multiple files/folders from one path to another having folder with same names, provision for single option selection should apply for all files/folders

**Comment by gave92** [comment]
Merging with #5645
