### ISSUE TITLE
Add support to view ZIP Files without extracting

### ISSUE THREAD

**Issue by Paras6408** [files-community/Files#7036]
### What's the Problem?

Hi, 
Please add support for viewing ZiP Files directly in without extracting, just like in Windows Default File Explorer...
Even I am not able to extract ...

### Solution/Idea

Hi, 
Please add support for viewing ZiP Files directly in without extracting, just like in Windows Default File Explorer...
Even I am not able to extract ...

### Alternatives

Please add ability to view and extract ZIP

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.0.34.0

### Windows Version

Windows 11 21H2 2200.348

**Comment by gave92** [comment]
It's already supported, are you having trouble with it?
