### ISSUE TITLE
Wordwrap filenames onto new line in icon view

### ISSUE THREAD

**Issue by octopushugger** [files-community/Files#7038]
### What's the Problem?

Long filenames are always cut off in icon view in Files but are often fully shown in Windows Explorer. 

### Solution/Idea

Wordwrap the filename onto multiple lines.

### Alternatives

Forced to use details view or switch back to Windows Explorer. 

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.348

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎10/‎11/‎2021 OS build	22000.348 Experience	Windows Feature Experience Pack 1000.22000.348.0

**Comment by yaichenbaum** [comment]
Merging with #1033.
