### ISSUE TITLE
Files is unable to show a file in the folder when set as default explorer

### ISSUE THREAD

**Issue by MarcAnt01** [files-community/Files#7039]
### Description

With File as default explorer, if through Edge, I select the option "show in folder", Files is opening the related folder, but not showing the exact file

### Steps To Reproduce

1. Set file as default explorer;
2. Download a file through Edge;
3. Select the option to show in folder

### Expected behavior

Show the exact file like file explorer does, this way there's quick access to it and with a lot of files the user avoid to perform an additional source

### Files Version

2.0.36.0 OS 

### Windows Version

Windows 11 21H2 10.0.22000.348

**Comment by gave92** [comment]
Merging with #6382

**Comment by gave92** [comment]
Merging with #6382
