### ISSUE TITLE
Alt+D / Ctrl+L hotkeys don't focus the address bar when the active tab is on Home

### ISSUE THREAD

**Issue by richardnassour** [files-community/Files#7040]
### Description

See GIF
![alt+d ctrl + l](https://user-images.githubusercontent.com/33163707/143107907-2a1244dc-1f4f-413c-80e2-9d2c326adc52.gif)

Tags:
Alt + D, Ctrl + L

### Steps To Reproduce

1- Go to Home
2- Press Ctrl+L or Alt+D

### Expected behavior

Alt+D or Ctrl+L should shift focus to the address bar when the active tab is on Home

### Files Version

2.0.34.0

### Windows Version

Windows 11 21H2 22000.318

**Comment by gave92** [comment]
Merging with #6800
