### ISSUE TITLE
Update Favorites when favorited folders are relocated or renamed 

### ISSUE THREAD

**Issue by richardhttps** [files-community/Files#7041]
### What's the Problem?

In Files Explorer, when a folder that is pinned to Quick Access is renamed or relocated, it's automatically updated in Quick Access to match the new name or location.
I know this isn't the most important feature request, but it would be nice to have it implemented in Files when possible.

### Solution/Idea

None

### Alternatives

None

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.0.34.0

### Windows Version

Windows 11 21H2 22000.318

**Comment by Germs2004** [comment]
or if the favorited folder has its icon changed, especially if it's done within the Files app

**Comment by yaira2** [comment]
This will be implemented in the next release.
