### ISSUE TITLE
Can't copy/cut/paste any file on any location (local/network)

### ISSUE THREAD

**Issue by kemeral** [files-community/Files#7042]
### Description

When I cry to copy/cut/paste files, nothing happens
Issue when coping on local disks/network disks
I have administrative access already & can do that via the windows file explorer

### Steps To Reproduce

1. Copy or cut any files
2. paste a file

### Expected behavior

No copying or pasting is happening. Not even any error message shows up

### Files Version

2.0.34.0

### Windows Version

Windows 10 Enterprise 21H1 Build 19043.1348

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7591841/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7591842/debug_fulltrust.log)

**Comment by gave92** [comment]
When you copy does the "paste" button on the toolbar enable/light up?

**Comment by gave92** [comment]
Merging with #7459

**Comment by kemeral** [comment]
Yes but no action
