### ISSUE TITLE
Why does Desktop.Files.JSON keeps on showing up after I delete it?

### ISSUE THREAD

**Issue by WhosPruv** [files-community/Files#7044]
### Description

I thought my laptop was infected with a virus but then I uninstalled "Files" and it was gone. Should I ignore them or is it a bad thing?

![ApplicationFrameHost_nRfraNwfma](https://user-images.githubusercontent.com/94924029/143161493-5e7a046a-0cb5-4045-a008-c67d98df88c3.png)

### Steps To Reproduce

1. Go to documents, videos, downloads
2. click show hidden files
3. Desktop.files.Json will appear

### Expected behavior

the files should not showup after i delete them

### Files Version

latest

### Windows Version

Windows 11 21H2 22000.318

**Comment by yaichenbaum** [comment]
@WhosPruv this issue is resolved in `main`.
