### ISSUE TITLE
Don't show the file preview when it's just a thumbnail

### ISSUE THREAD

**Issue by MarcAnt01** [files-community/Files#7045]
### What's the Problem?

Atm, Files show preview of photos, videos, txt file and even something more, but if there's an unsupported file or a folder it just shows the preview of the folder. In this context I see a useless zoomed thumbnail

### Solution/Idea

Show "unsupported file preview" like File Explorer or something like that, whatever not show that useless thumbnail

### Alternatives

None

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to accomplish X | Should |

### Files Version

2.0.36.0

### Windows Version

Windows 11 21H2 10.0.22000.348

**Comment by yaichenbaum** [comment]
@MarcAnt01 can you upload a screenshot of the blurry thumbnail?

**Comment by MarcAnt01** [comment]
> @MarcAnt01 can you upload a screenshot of the blurry thumbnail?

I haven't talked about anything being blurry

**Comment by yaichenbaum** [comment]
"In this context I see a useless zoomed thumbnail" I took this to mean blurry, but I guess I misunderstood. Can you add repro steps so I can make sure I'm seeing the same thing?

**Comment by MarcAnt01** [comment]
There's nothing to reproduce. I don't mean anything in particular but a bigger file thumbnail, meaning that I don't see the purpose of the preview in that context

**Comment by yaichenbaum** [comment]
Are you talking about the preview pane or in the grid layout?

**Comment by MarcAnt01** [comment]
> Are you talking about the preview pane or in the grid layout?

![image](https://user-images.githubusercontent.com/43090263/145960996-06177274-7293-4f9c-9e6c-6cf928d45761.png)

This is what I mean

**Comment by yaichenbaum** [comment]
I see what you're saying, what would you suggest to display instead?

**Comment by MarcAnt01** [comment]
> I see what you're saying, what would you suggest to display instead?

I put that in the solution/idea section. Whatever, I would either hide show "unsupported preview" like the file explorer or directly hide the grid

**Comment by yaichenbaum** [comment]
What's the unsupported file preview? Take for example an Audacity file, I don't think there is any preview to display.

**Comment by MarcAnt01** [comment]
I mean when there's no preview available Files just shows the file/folder thumbnail and I think this should not happen, instead I'd rather an "unsupported content" textblock. Let me know, if this still isn't clear

**Comment by yaichenbaum** [comment]
@MarcAnt01 I'm not against the idea but I don't see how it would be an improvement over the current behavior.

**Comment by MarcAnt01** [comment]
> @MarcAnt01 I'm not against the idea but I don't see how it would be an improvement over the current behavior.

It’s distracting, I love the preview feature, but when I see a big folder thumbnail, I am tempted to switch it off, there’s just no point of showing such previews imho. I prefer explorer behavior of not showing anything when there’s no good preview

**Comment by yaichenbaum** [comment]
@MarcAnt01 we're going to keep the current behavior for consistency.

**Comment by MarcAnt01** [comment]
@yair100 how does that give consistency? I honestly don't see any rational behind this. Whatever, can an option be added at least?

**Comment by yaichenbaum** [comment]
When the preview pane is open, users expect content to be shown. A blank space will make it look like the preview failed to load and it wouldn't accomplish anything.

**Comment by MarcAnt01** [comment]
> When the preview pane is open, users expect content to be shown. A blank space would make it look like the preview failed to load and it wouldn't accomplish anything.

"No preview available" or something like that could be shown (like in file explorer)
