### ISSUE TITLE
Improve the UX of file preview details

### ISSUE THREAD

**Issue by MarcAnt01** [files-community/Files#7046]
### What's the Problem?

Currently, right clicking on the preview to enable/disable details view is very confusing, so that I thought that the details view was the only available option

### Solution/Idea

This has to be filled, since I couldn't come with a good ux, just pointing out that the actual one is pretty bad and limited.
It should be intuitive to understand that there are two different layouts and a seamless switch between the two views should be present

### Alternatives

None

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to accomplish X | Should |

### Files Version

Version: 2.0.36.0

### Windows Version

Windows 11 21H2 10.0.22000.348

**Comment by yaichenbaum** [comment]
@MarcAnt01 do you think putting the details in an expander would improve discoverability?

**Comment by MarcAnt01** [comment]
I think an expander is too invasive, what something like this in Explorer (even if it has a different function and is not touch friendly)?
![image](https://user-images.githubusercontent.com/43090263/143401100-f4f24e7a-cc77-4377-9044-a00383746bf7.png)

**Comment by yaira2** [comment]
@MarcAnt01 this issue should be resolved in the latest preview build https://files.community/download.
