### ISSUE TITLE
Почему

### ISSUE THREAD

**Issue by HackFlongee** [files-community/Files#7048]
### Description

Здраствуйте, почему я не могу отключить экспериментальную функцию? А именно установить эту прогрму по умолчанию.
Теперь я когда удаляю эту программу у меня не открываются папки . 
Исправте это пожалуйтса поскорее.
Или напишите как это исправить!

А вопше приложение очень хорошее.)

Всего доброго)

### Steps To Reproduce

ю

### Expected behavior

ю

### Files Version

Версия: 2.0.34.0 OS Version: 10.0.19042.1348

### Windows Version

Windows 10 Pro 20H2

### Relevant Assets

.

**Comment by gave92** [comment]
To unset Files you can download [this zip](https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip) and run UnsetFilesAsDefault.reg to restore windows explorer.
