### ISSUE TITLE
Command Prompt

### ISSUE THREAD

**Issue by hamzacantfindausername** [files-community/Files#7049]
### Description

So, I was on the files app. And, when I typed cmd, it didnt work and said Ran into a problem. Please help. 

### Steps To Reproduce

1) Go to file
2) Type "cmd"

### Expected behavior

Fix

### Files Version

v1.5

### Windows Version

Windows 10 Pro

**Comment by gave92** [comment]
Please upload the app's debug logs and confirm the app's version.

**Comment by yaichenbaum** [comment]
v1.5 is no longer supported, please let us know if this is still an issue in Files v2.0.34.
