### ISSUE TITLE
Missing Narrow-option for details view

### ISSUE THREAD

**Issue by Lenbus** [files-community/Files#7050]
### What's the Problem?

There's a trend towards more widespread layouts in modern design. And even though this looks quite pleasing, oftentimes I'd prefer a more narrow design for the displayed files list in order to have more files fitting to the window space. 
In the windows explorer there is that option available as an option in the views menu. Would love to see that option in your app as well!

### Solution/Idea

As in windows native explorer, just add the option in the view tab

### Alternatives

Option to reduce the "zoom" level.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.0.34.0

### Windows Version

Windows 11 Home 21H2 

### Additional comment

Additional Thoughts and Suggestions, I'd love to see, to make your app the best one out there would be:

### Toolbar
- auto-hide the toolbar (new, cut, copy) to save some space -> most users tend to use Ctrl + C/X/V anyways
- symbols on the right (view, filter, ...) could go down into the status bar

### Details View
- add more attribute columns to be selected (and sorted) in the details view [like in windows explorer]
- show file size also for folders [like TreeSize has the capability]

### Window & Tab Managment
- when opening a folder in a new tab <MouseWheel Click> do not switch to that tab yet (make this an option in the properties)
- [BUG] when undocking a tab by dragging it out from the bar it does not open in a new window, if only two tabs are opened -> the remaining tab is closed then even though it should not
- make the entire breadth of the window header a possible landing zone for tabs to dock -> right now this only works when the tab is moved to the left side of the "+"-sign

#### Split View
- right now I do not understand how to enable split view properly
- best way would be to:
  - have to opportunity to drag and dock a tab on one side of another to create a vertical or horizontal window arrangement
  - have a split view button
  - probably then the address bar should be splitted as well, so that every view has its own

### Navigation
- make the "folder up" button go just above the symbols (e.g. in the properties or tool bar)
   -> especially when the side bar is enabled that one is a bit hard to reach quickly
- double click into empty space to go up one folder [Clover has that very handy feature on board]
- single-click-copy-address-button (on the right of the text field, e.g. when hovered with the cursor) would come in quite handy [as many code blocks for e.g. in Notion or GitHub do have]
- address bar could maybe be merged with the search bar [as most modern browser do]

### Running File Tasks
- having an interactive button for this is great, however this does not display the current status (percentages, estimated time to finish, loading bar, current speed)
- moreover I would understand its (and the gear's) scope to be global for all tabs and therefore maybe a position right next to the window handle buttons would make more sense?
- really cool would be an additional loading bar running beneath the newly created file's name to mark it as not finished yet

- make the app's reactions even faster (even though I don't know if that is possible)

I hope this can grant you some inspiration for future updates to make this the best file explorer out there. :)

Best regards and thank you for your amazing work!
Lenni

**Comment by gave92** [comment]
Merging with #1940
