### ISSUE TITLE
Global layout options

### ISSUE THREAD

**Issue by bebotette** [files-community/Files#7051]
### What's the Problem?

setting up layout for each folder one by one. and it sucks.

### Solution/Idea

option to set layout options (medium icons, large icons, column, etc) as a global setting. so that we don't keep setting up such layouts on each and every folder we visit

### Alternatives

setting up layout for each folder one by one. and it sucks.

### Priorities

| Capability | Priority |

| Global layout options | Should |

### Files Version

Version: 2.0.34.0 

### Windows Version

OS Version: 10.0.19044.1348

**Comment by gave92** [comment]
You should be able to:

> Turn Off "Enable individual preferences for individual directories" in Settings > Files and Folders
> Go to any folder and set your desired layout mode

The selected layout at step 2 will be the default.
