### ISSUE TITLE
Icon overlays are blurry in Grid View mode

### ISSUE THREAD

**Issue by bebotette** [files-community/Files#7052]
### What's the Problem?

right now the check icons for items in google drive (or similar) are blurred and not sharp.

### Solution/Idea

use vector icons instead?

### Alternatives

no alternatives available.

### Priorities

| Vector check icons | Should |

### Files Version

Version: 2.0.34.0

### Windows Version

OS Version: 10.0.19044.1348

**Comment by gave92** [comment]
Tanks for the report. Could you post a screenshot?

**Comment by bebotette** [comment]
![Snipaste_2021-11-25_08-23-31](https://user-images.githubusercontent.com/5653117/143328654-e6f4accf-13e8-4003-9b87-9bf78196abdc.png)

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
