### ISSUE TITLE
desktop.files.json kept modifying folder properties (modified date/time)

### ISSUE THREAD

**Issue by bebotette** [files-community/Files#7053]
### Description

desktop.files.json kept modifying folder properties (modified date/time). Adding that json file might be important, but it messes up sort options of folders according to new/old

### Expected behavior

it should not affect folder properties, and should be treated as a hidden system file

### Files Version

Version: 2.0.34.0 

### Windows Version

OS Version: 10.0.19044.1348

**Comment by gave92** [comment]
desktop.files.json does not get created anymore in latest (insider) version.

**Comment by bebotette** [comment]
hope to see that change reflected soon in the stable version. thanks.

**Comment by jdeloshoyos** [comment]
> hope to see that change reflected soon in the stable version. thanks.

Agree. This bug is bad enough that I can't use Files as my main file manager because of this. Hope we can get a stable release soon! Anyway, a big thank you to the dev team for this awesome app!

**Comment by gave92** [comment]
In the meantime you can give the preview version a try: https://files.community/download/preview. It installs alongside (not replacing) the Store version.

**Comment by jdeloshoyos** [comment]
> In the meantime you can give the preview version a try: https://files.community/download/preview. It installs alongside (not replacing) the Store version. Store is unfortunately blocking new Files versions atm, so it may take some time for a new Store version.

Thanks a lot @gave92 , I installed the preview version. Looks good so far! Hope the store issue gets resolved soon. Again, thanks for your work on this amazing app!

**Comment by mylovesaber** [comment]
> In the meantime you can give the preview version a try: https://files.community/download/preview. It installs alongside (not replacing) the Store version. Store is unfortunately blocking new Files versions atm, so it may take some time for a new Store version.

I'm not able to install the preview version through website. I found some info about this problem:
https://docs.microsoft.com/en-us/windows/msix/app-installer/installing-windows10-apps-web
https://techcommunity.microsoft.com/t5/msix-deployment/the-ms-appinstaller-protocol-has-been-disabled/m-p/3038361

System: win11  21H2  22000.376
