### ISSUE TITLE
more file extension previews for details panel and thumbnails

### ISSUE THREAD

**Issue by bebotette** [files-community/Files#7054]
### What's the Problem?

I am a graphic designer, and I would love to see thumbnail previews and preview of the file in the details panel for the following common design files: svg, psd, psb, tiff, ai, eps, and more.

### Solution/Idea

thumbnail previews and preview of the file in the details panel for the following common design files: svg, psd, psb, tiff, ai, eps, and more.

### Alternatives

no alternatives for now. had to go back to default windows explorer because I have an extension that allows that.

### Priorities

| more thumbnail previews and file extensions support | Could |

### Files Version

Version: 2.0.34.0 

### Windows Version

OS Version: 10.0.19044.1348

**Comment by gave92** [comment]
> had to go back to default windows explorer because I have an extension that allows that

Is that SageThumbs?

**Comment by bebotette** [comment]
I use that before. but right now I'm using limited features from PowerToys to show svg thumbnails

**Comment by null-zero** [comment]
> 

Ive tried SageThumbs as well as Icaros

**Comment by yaichenbaum** [comment]
Merging with #8376
