### ISSUE TITLE
Tree view

### ISSUE THREAD

**Issue by qwaknet** [files-community/Files#7056]
### What's the Problem?

Love the app -- but I'm really missing the tree view in the left panel.  I use it to quickly switch directories.  Kinda must have for me :(

### Solution/Idea

Tree view in the left panel.

### Alternatives

Don't know of any.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.318

### Windows Version

Windows 11 21H2 22000.318

**Comment by yaichenbaum** [comment]
Merging with #1928

**Comment by yair100** [comment]
@qwaknet Tree View is currently available in preview https://files.community/download. It will be included in the next stable release.
