### ISSUE TITLE
Customizar una carpeta de Bibliotecas

### ISSUE THREAD

**Issue by EAxelGM** [files-community/Files#7057]
### Description

![image](https://user-images.githubusercontent.com/56899927/143381303-64e21da4-d442-4a70-85e1-8eee4aeb7693.png)

### Steps To Reproduce

Abrir Files
Abrir el Apartado de Bibliotecas
Clic derecho en el que sea y dar clic en propiedades
en las pestañas "General", "Bibliotecas" y "Customization" dar clic en Customization
y se genera un error.

### Expected behavior

.

### Files Version

2.0.34.0

### Windows Version

Windows 11 Home Single Language 21H2 22000.348

### Relevant Assets

![image](https://user-images.githubusercontent.com/56899927/143381573-44727dff-7975-43b6-aa5a-6e367c9eafc4.png)

**Comment by gave92** [comment]
Thanks for the report. This is fixed in latest code.
