### ISSUE TITLE
Custom themes don't always show up in the settings dialog

### ISSUE THREAD

**Issue by kalvscleo27** [files-community/Files#7058]
### Description

when i open Files for a 2nd or 3rd time or anytime. theme selection is gone and only default is appearing even Theme for files is installed. when i reset the app, it will back to default state and the theme selection is back again.

### Expected behavior

when i open the files and go to theme selection for 1st time, its there. when i open again for 2nd time, the theme selection is gone and only default is appearing

### Files Version

Version: 2.0.34.0 

### Windows Version

Windows 11 21H2 22000.348

### Relevant Assets

![image](https://user-images.githubusercontent.com/95011112/143382527-2451ab17-3322-4505-8a57-ec935bc1ee2d.png)

**Comment by gave92** [comment]
Thanks for the report. Could you post the app's log files?

**Comment by kalvscleo27** [comment]
How can i see the app's log files?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by kalvscleo27** [comment]
Here is the log files

**Comment by gave92** [comment]
You can get them from `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` (debug.log + debug_fulltrust.log).
PS: posting files from email does not work, you'll need to reply from GitHub.

**Comment by kalvscleo27** [comment]
ok here is the files, i replied from GitHub 
[debug.log](https://github.com/files-community/Files/files/7601952/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7601953/debug_fulltrust.log)

**Comment by Josh-65** [comment]
This seem to start happening more on 2.1.5 too. As many people in discord have reported.

**Comment by yaichenbaum** [comment]
This issue should be resolved in v2.3
