### ISSUE TITLE
Shortcut cannot be created on network drive

### ISSUE THREAD

**Issue by olofweb** [files-community/Files#7059]
### Description

When I try to create or copy a shortcut on a network drive, nothing is created/copied.

### Steps To Reproduce

1. Create a folder on a network drive (e:\myFolder)
2. Put a file in this folder
3. Right-click on this file -> Create Shortcut
4. No shortcut created

Same result if you try to drag-and-drop a shortcut from a "normal" drive to e:\myFolder

### Expected behavior

The shortcut will be creatd/copied

### Files Version

2.0.34.0

### Windows Version

Windows 10.0.18363.1916

**Comment by gave92** [comment]
Merging with #2436
