### ISSUE TITLE
Files crashes when loading a Recycle Bin with many items

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#7061]
### Description

Files crashes when loading a Recycle Bin with many items.

### Steps To Reproduce

Open the Recycle Bin with around 500 items in it.

### Expected behavior

Shouldn't crash.

### Files Version

Version: 2.0.36.0 OS Version: 10.0.19044.1348

### Windows Version

Version: 2.0.36.0 OS Version: 10.0.19044.1348

### Relevant Assets

[debug_fulltrust.log](https://github.com/files-community/Files/files/7601782/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7601783/debug.log)

**Comment by gave92** [comment]
Were some files being deleted/restored in the meantime?

**Comment by R3voA3** [comment]
Nope.

**Comment by gave92** [comment]
Does it happen all the times?

**Comment by R3voA3** [comment]
Nah, seems to happen only after a fresh restart of the system. Perhaps even the App.

**Comment by yaichenbaum** [comment]
@R3voA3 is this still an issue in the preview version? https://files.community/download/preview
