### ISSUE TITLE
Drag and drop caused the application to crash

### ISSUE THREAD

**Issue by ejmurray** [files-community/Files#7063]
### Description

I have my windows laptop hooked up to a second monitor. As I dragged the Files application from the laptop screen after launching to the other screen, the application crashed and I had to restart. Upon restarting, drag and drop to the other screen worked. One thing to add is that I was bumping the top of the screen that I had dragged so that it would open in full screen.  

### Steps To Reproduce

Start application from the task bar shortcut.
Drag the opened application on one screen (laptop) to the other monitor
Bump at the top of the screen to open in full screen

### Expected behavior

OPen in full screen

### Files Version

Version: 2.0.34.0 OS Version: 10.0.19042.1348

### Windows Version

Windows 10

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7601919/debug.log
[debug_fulltrust.log](https://github.com/files-community/Files/files/7601920/debug_fulltrust.log)
)

**Comment by gave92** [comment]
Thanks for the report. This is new.
```2021-11-25 09:42:40.7733|ERROR|AppUnhandledException|No installed components were detected.

Child collection must not be modified during measure or arrange.
	System.Exception: No installed components were detected.

Child collection must not be modified during measure or arrange.```

**Comment by yaichenbaum** [comment]
Is this still an issue in the latest preview build? https://files.community/download/preview
