### ISSUE TITLE
Many same messages

### ISSUE THREAD

**Issue by caffeine-mgn** [files-community/Files#7066]
### Description

Getting message on each messages.
I tryed to delete many files whe are bisy. And on each files I got message about that

### Steps To Reproduce

1. open some folder where many files using another applications (for example TEMP folder in windows).
2. Try to delete files
3. getting messages about files are bisy.

### Expected behavior

Getting one message about several files is bisy.

### Files Version

2.0.34.0

### Windows Version

Windows 11 Pro 21H2 22000.348

**Comment by gave92** [comment]
Merging with #7060
