### ISSUE TITLE
Apply the new "Quick Access" icon on customized W10 v1809, with W11 icons.

### ISSUE THREAD

**Issue by TizianoMad** [files-community/Files#7067]
### What's the Problem?

With applied W11 icons on a W10 v1809, a registry modification had to be done to make the new Quick Access icon assignment in the classic Windows "File Explorer".

"Files v2" displays all W11 new icons correctly (located in C:\Windows\System32 in this version, instead of C:\Windows\SystemResources as from 1903) except from the Quick Access one, exactly like in the classic File Explorer before the registry modification.

-------------------------------------------------------------------------------------

### Solution/Idea

Could an equivalent registry command file for this assignment be created ?

-------------------------------------------------------------------------------------

New Quick Access icon assignmment on Classic "File Explorer" : 
("to fa icon.reg" file)

Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\CLSID\{679f85cb-0220-4080-b29b-5540cc05aab6}\DefaultIcon]
@=hex(2):25,00,53,00,79,00,73,00,74,00,65,00,6d,00,52,00,6f,00,6f,00,74,00,25,\
  00,5c,00,73,00,79,00,73,00,74,00,65,00,6d,00,33,00,32,00,5c,00,69,00,6d,00,\
  61,00,67,00,65,00,72,00,65,00,73,00,2e,00,64,00,6c,00,6c,00,2c,00,2d,00,31,\
  00,30,00,32,00,34,00,00,00

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Classes\CLSID\{679f85cb-0220-4080-b29b-5540cc05aab6}\DefaultIcon]
@=hex(2):25,00,53,00,79,00,73,00,74,00,65,00,6d,00,52,00,6f,00,6f,00,74,00,25,\
  00,5c,00,73,00,79,00,73,00,74,00,65,00,6d,00,33,00,32,00,5c,00,69,00,6d,00,\
  61,00,67,00,65,00,72,00,65,00,73,00,2e,00,64,00,6c,00,6c,00,2c,00,2d,00,31,\
  00,30,00,32,00,34,00,00,00

-------------------------------------------------------------------------------------

(reverse "default.reg"file)

Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\CLSID\{679f85cb-0220-4080-b29b-5540cc05aab6}\DefaultIcon]
@=hex(2):25,00,53,00,79,00,73,00,74,00,65,00,6d,00,52,00,6f,00,6f,00,74,00,25,\
  00,5c,00,73,00,79,00,73,00,74,00,65,00,6d,00,33,00,32,00,5c,00,73,00,68,00,\
  65,00,6c,00,6c,00,33,00,32,00,2e,00,64,00,6c,00,6c,00,2c,00,2d,00,35,00,31,\
  00,33,00,38,00,30,00,00,00

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Classes\CLSID\{679f85cb-0220-4080-b29b-5540cc05aab6}\DefaultIcon]
@=hex(2):25,00,53,00,79,00,73,00,74,00,65,00,6d,00,52,00,6f,00,6f,00,74,00,25,\
  00,5c,00,73,00,79,00,73,00,74,00,65,00,6d,00,33,00,32,00,5c,00,73,00,68,00,\
  65,00,6c,00,6c,00,33,00,32,00,2e,00,64,00,6c,00,6c,00,2c,00,2d,00,35,00,31,\
  00,33,00,38,00,30,00,00,00

-------------------------------------------------------------------------------------

### Alternatives

Maybe including the "shell32.dll.mun" file from a 1903 (or higher) version, in the "SystemResources" folder, would be enough to fix the assignment. - (?)

-------------------------------------------------------------------------------------

### Files Version

v2.0.34.0

-------------------------------------------------------------------------------------

### Windows Version

Windows 10 LTSC 1809

-------------------------------------------------------------------------------------

### Additional comment

"Registry edition file for the Quick Access icon" from :
[Quick Access Icon Changer](https://www.deviantart.com/niivu/art/Quick-Access-Icon-Changer-704327034) which is part of the
[Windows 11 Icons Theme](https://www.deviantart.com/niivu/art/Windows-11-Icon-Themes-874289797) by niivu on DeviantArt.

**Comment by yaichenbaum** [comment]
Files uses whatever icon is present on the system, we recommend updating to Windows 11 in order for Files to use the new icons.

**Comment by TizianoMad** [comment]
Thank you for answering @yair100, and for this great app you are providing.

All Windows 11 icons appear with great succes on my Windows 10, as I explained.
I cannot switch to 11 for the time being, and as long as it works nicely on my system, I'm very happy with it.

Just ONLY the Quick Access icon needs switching, and I guessed you could have helped me just by indicating the registory key that displays it (like the classic example I joined).

Thank you for considering,
and for the great work you are doing.

**Comment by yaichenbaum** [comment]
@TizianoMad thanks! We try to stay away from modifying the registry as much as possible. The one exception we made was for setting Files as the default file manager, but changing icons is a bit more than we plan to do.

**Comment by TizianoMad** [comment]
No worries, I will try to tweak this with the help of the icon theme creator.

It is funny you mentionned your Default explorer file, I just posted another request concerning this subject !

So see you later, and thanks again for your feedbacks.
