### ISSUE TITLE
Sidebar oddities

### ISSUE THREAD

**Issue by Hefaistos68** [files-community/Files#7068]
### Description

The sidebar occasionally does show its items as in expanded view although its in collapsed view. This happens sometimes when toggling sidebar items, with the sidebar collapsed, sometimes when opening Files when left with the sidebar collapsed.
![image](https://user-images.githubusercontent.com/8855055/143428771-caec85ec-8dbd-4de4-99d2-54f9b9ad1d07.png)
The item menu that normally appears when collapsed, does not show up, instead its possible to select from the items without text/icon.

### Steps To Reproduce

Collapse the sidebar and enable/disable items. open/close Files with varying state of the sidebar.

### Expected behavior

Always show the sidebar items in correct state.

### Files Version

Version: 2.0.34.0 

### Windows Version

OS Version: 10.0.19042.1348

**Comment by Hefaistos68** [comment]
There is also something with the state of the "Libraries" section, it seems internally to handle open/close even when collapsed, thus the item menu opens often only on the second click on "Libraries"

**Comment by yaichenbaum** [comment]
@Hefaistos68 This issue should be resolved in the preview version. https://files.community/download/preview
