### ISSUE TITLE
Display list of folders when clicking last item in bread crumb

### ISSUE THREAD

**Issue by Hefaistos68** [files-community/Files#7072]
### Description

Last bread crumb in navigation bar does not show folders, all others correctly open the list of folders under the crumb.
As in this image, clicking on the '>' does not open any list of folders
![image](https://user-images.githubusercontent.com/8855055/143452287-88c6494f-99de-49a1-8a56-96e72e70c46e.png)
Yet, here it opens correctly the list of folders under it:
![image](https://user-images.githubusercontent.com/8855055/143452483-9edd06e1-6d05-44b1-a440-a728b2de5a4d.png)

### Steps To Reproduce

Go to any folder that contains subfolders, and click on the '>' of the last crumb in the navigation bar.

### Expected behavior

Open the list of folders under the location.

### Files Version

Version: 2.0.34.0 

### Windows Version

OS Version: 10.0.19042.1348

**Comment by gave92** [comment]
That's on purpose, after all the contents of the current folder are displayed in the file list. Do you see some value/use case in displaying the same folders in the navbar?

**Comment by Hefaistos68** [comment]
Definitely. Actually use it quite often in the explorer especially in folders with many subfolders, so I can quickly compare folder names / order with the ones visible in the files pane. Could do the same with a second pane, but that takes a lot longer, changes view, etc.

**Comment by yaichenbaum** [comment]
@Hefaistos68 just curious, what are you comparing?

**Comment by Hefaistos68** [comment]
Uhm, well, we do have rather weird folder structures, grouping projects and related files, usually like
project-version-type-language, where each part can be quite long, resulting in rather annoying huge lists of folders. Now when you got to quickly check if project X-512-manual-* has all 25 language folders compared with version X-480-manual-*, you get the picture.
Its a mess that cant (wont) be changed and those pesky bread crumbs help a bit navigating that mess.

**Comment by yaira2** [comment]
Thank you for your feedback. We don't have plans to implement this feature, however, the next version of Files hides the chevron so that the behavior is more consistent.
