### ISSUE TITLE
Resizing app window changes column sizes in the files pane

### ISSUE THREAD

**Issue by Hefaistos68** [files-community/Files#7073]
### Description

Navigate to any folder in details layout, grab the apps lower or upper window edge and drag it to resize the window. The column layout slightly changes column sizes.

### Expected behavior

Vertical window resizing should not affect horizontal column sizes.

### Files Version

Version: 2.0.34.0 

### Windows Version

OS Version: 10.0.19042.1348

**Comment by gave92** [comment]
Merging with #6448

**Comment by gave92** [comment]
Not the same, but related #6448

**Comment by yaichenbaum** [comment]
@gave92 I think #6448 covers this as well.
