### ISSUE TITLE
Files Libraries content differs from Explorer Libraries content

### ISSUE THREAD

**Issue by Hefaistos68** [files-community/Files#7074]
### Description

The libraries I see in Explorer vs. Files:
![image](https://user-images.githubusercontent.com/8855055/143454138-a4d2e37e-efed-4ce0-95eb-facf240a0e98.png) 
![image](https://user-images.githubusercontent.com/8855055/143454261-b8949153-1e2a-4650-b19f-57ec81dc176c.png)

### Expected behavior

Have identical contents in both apps since the libraries are user defined in a folder.

### Files Version

Version: 2.0.34.0 

### Windows Version

OS Version: 10.0.19042.1348

**Comment by gave92** [comment]
Could you check if the missing libraries are all "empty"? Meaning point to no folders?

**Comment by Hefaistos68** [comment]
Only the "Test" one is empty.

**Comment by gave92** [comment]
Could you post a screenshot of the windows explrer's properties page for one of the "non-empty" libraries that do not apear in the sidebar? Like this one:
<img src="https://user-images.githubusercontent.com/9673091/143471435-860fc414-b5d8-473e-8f73-49227fb0d417.png" width="300"/>

**Comment by Hefaistos68** [comment]
All three missing ones:
![image](https://user-images.githubusercontent.com/8855055/143472363-1472d844-553e-434c-9a80-b368fbeaff41.png)
![image](https://user-images.githubusercontent.com/8855055/143472469-a09665bc-e33a-40a2-8544-e23c6fa7ba50.png)
![image](https://user-images.githubusercontent.com/8855055/143472614-9ff65f93-85bf-4511-ad1c-a783af21465a.png)

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
Is this still an issue in the latest preview build? https://files.community/download/preview
