### ISSUE TITLE
Close button and horizontal toolbar overlapping in settings window

### ISSUE THREAD

**Issue by starkgate** [files-community/Files#7075]
### Description

![ApplicationFrameHost_d4fXbXTix3](https://user-images.githubusercontent.com/12874678/143458644-5b3af151-74b9-468e-abcc-0a8b1769ad36.png)

### Expected behavior

No overlap

### Files Version

2.0.36

### Windows Version

Windows 10 21H1 19043.1348

**Comment by gave92** [comment]
Thanks for the report. Latest insider version fixes this.
