### ISSUE TITLE
Add support for high contrast folder icons

### ISSUE THREAD

**Issue by TizianoMad** [files-community/Files#7076]
### What's the Problem?

As I am helping designing W11 folder icons on ElevenForum.com,
we realized a while ago that since Light & Dark mode are displayed,
many creations need rework for a nice appearance in each mode.

When I came across the icons you created in "..\Files_2.0.34.0_x64__1y0xx7n9077q4\Assets\AppTiles\contrast-standard"
I was happy to notice you also thinked about this issue.

So why not also include this feature for folder customization, with offering a 2 icons to display for the 2 modes.

(I'm also very often using "desktop.ini" files with its referred icon in the same file to make it portable. Adequate INI commands not perturbing the classic one next to it next -would be tip-top complete !)   

### Solution/Idea

Add switch for "Standard icon" or "2 icons for Dynamic display" in Properties for Folder customisation.

A "desktop.ini" file could include this type of extra command, which would not perturb classic file explorer.
(with all icons needed in same folder -in case they are made for portable mode-)
[.ShellClassInfo]
IconResource=IconMain.ico,0

and could be added commands like :
LightMode=IconDark.ico,0 /or/ DefautIcon (IconMain.ico,0)
DarkMode=IconLight.ico /or/ DefautIcon (IconMain.ico,0)

### Alternatives

--------------------------------------------------------------------------------------------

### Files Version

v2.0.34.0_Test

### Windows Version

Windows 10 LTSC 1809 with Windows 11 icons

**Comment by yaichenbaum** [comment]
@TizianoMad just to confirm, you're looking for support for high contrast folder thumbnails?

**Comment by TizianoMad** [comment]
Why not, that's another good idea, with an automatic tweak for a standard icon.

But my idea was to also have choice to include 2 different icons (1 light for dark mode + 1 dark for light mode) separately designed for each. (I guess like you did in a way with your default one).

I'll be back in a few hours, talk to you later.
See you !

**Comment by TizianoMad** [comment]
Hello Yair ✌

I apologize for coming back late, I was a busy lately.

Actually, I'm not sure the title is the exact request. It is true that in general, the dark icons are more impacted than light colored ones (and the term "dynamic icon" is ment for displaying a small notification upon it, so I agree title's wrong).

On the other hand, my description was quite right. "offering possibility to display 2 different icons according to the (light or dark) mode set in explorer"
I made an example to understand the comparison (pic 1), and how the icons on the center should switch, and how the ones on the side don't appear well enough. Very big size display can seem ok, but when their display gets smaller, they get too "discreet" (pic 2).

Since Microsoft created the Dark mode view, I often realized many icons were created ignoring this feature, and making some icons too dark. Now that this new type of folder icon is favorable for recreation, a special feature could be innovated to make icons with double display, a bit like how the "token" icons react (options on explorer top ribbon).

![Compare1](https://user-images.githubusercontent.com/90962569/143795350-3715e083-f2d6-4921-9b02-5cc7588470a1.png)


![Compare3](https://user-images.githubusercontent.com/90962569/143795365-ca048d9d-eba9-4861-a8b0-20cc06c50c0f.png)

I was also thinking of a folder creator/tweaker that could be included in the future, but this is another subjet.

Thank you and well done for all the feedbacks you manage to give to everyone,
and the consideration you have for the users, in addition to the app you provide and all the work it takes, this is really appreciated.

Take care,
See you 🙌

**Comment by yaichenbaum** [comment]
@TizianoMad I think I see what you're trying to do. We won't be adding a built-in option considering that there isn't much demand, but you can still accomplish what you're trying to do by changing the icons from the properties dialog.
