### ISSUE TITLE
Bug: Can't enter edit mode on path bar using the keyboard

### ISSUE THREAD

**Issue by Hefaistos68** [files-community/Files#7077]
### Description

Its seems not possible to enter edit mode in the navigation bar when using only keyboard. Since the focus jumps to a bread crump and from there between other crumps and other controls, there is no way to actually edit the location.
I expected F2 to work, or having a stop at an extra edit field after the crumps, but nope. nothing of the likes. 

To be fair, explorer doesnt seem to offer this either, but at least in explorer i can select folders from the bread crumps.

### Steps To Reproduce

Use the tab key to jump between the controls in the app until you reach the navigation bar and the bread crumps. 

### Expected behavior

Some way to edit the location in the navigation bar with keyboard only.

### Files Version

Version: 2.0.34.0 

### Windows Version

OS Version: 10.0.19042.1348

**Comment by gave92** [comment]
To enter edit mode you can press Ctrl+L or Alt+D (like explorer). Or do you need to reach it by Tab?

**Comment by gave92** [comment]
To enter edit mode "using keyboard" you can use Ctrl+L or Ald+D. But _it is_ an accessibility issue.

**Comment by Hefaistos68** [comment]
Damn it, didnt know about the Ctrl+L and Alt+D, works just fine with these shortcuts.

**Comment by gave92** [comment]
Np, same shortcuts work in explorer and web browsers too. Still I think all controls should be reachable by Tabbing.

**Comment by yair100** [comment]
> Np, same shortcuts work in explorer and web browsers too. Still I think all controls should be reachable by Tabbing (is that right @yair100?)

@gave92 yes, I'm not quite sure how we can handle this scenario but it's something to look into.

**Comment by Hefaistos68** [comment]
While at it, check why the bread crumps dont open with key down.

**Comment by yaichenbaum** [comment]
> While at it, check why the bread crumps dont open with key down.

@Hefaistos68 can you open a feature request for that?

**Comment by Hefaistos68** [comment]
#7086 opened

**Comment by Raithlin** [comment]
Is there an accepted shortcut we can assign to this? I can do the pull request for this if we decide on that.

**Comment by yaichenbaum** [comment]
@Raithlin there is already a shortcut, this issue is specifically about using tab navigation to enter edit mode. I have a fix I'm working on for this and plan to open a PR soon.

**Comment by yaira2** [comment]
@Raithlin what are your thoughts on using the tab key? If a breadcrumb is selected, the current behavior is to switch the focus to the search box. I think we can change this to enter the edit mode instead. 
![image](https://github.com/files-community/Files/assets/39923744/117c4496-4036-4b32-bf17-22fecd5f1e3c)

**Comment by Raithlin** [comment]
The convention is for Tab to move from one control to the next. Perhaps using Enter (or perhaps Shift+Enter) to edit instead?

**Comment by yaira2** [comment]
The edit box is the next control, but it's hidden when edit mode is turned off so it should be okay to use `tab` in this scenario. Shift + enter would work, but would be harder to discover.

**Comment by yaira2** [comment]
I've opened a pull request to resolve this issue #16653.
