### ISSUE TITLE
Batch Rename

### ISSUE THREAD

**Issue by trulko** [files-community/Files#7080]
### What's the Problem?

When several files are selected simultaneously, the rename option is grayed out and not available.

### Solution/Idea

When several files are selected and renamed, each selected file should be renamed to the set name, with an appended number in parentheses to distinguish the files. For example, selecting several files and renaming them to "example" would give "example (1)", "example (2)", etc.

This is the current behavior in Windows Explorer.

### Alternatives

Perhaps to make it clearer to the user, a "batch rename" command could replace the rename command in the context menu when several items are selected, maybe even with a GUI allowing more advanced batch renaming of files.

### Files Version

2.0.36

### Windows Version

Windows 11 21H2 22000.348

**Comment by gave92** [comment]
Also #372

**Comment by yaichenbaum** [comment]
@trulko a batch rename option is an entire tool of itself and is out of scope of what we have planned for Files. Our recommendation is to use the batch rename option in PowerToys for this.
