### ISSUE TITLE
Feature: Add option to set default sorting options

### ISSUE THREAD

**Issue by bebotette** [files-community/Files#7082]
### Requirements
- Add combo box drop down to folder settings page similar to the default layout options
   - Settings can still be overridden on individual directories 

### Files Version

Version: 2.0.34.0

### Windows Version

 OS Version: 10.0.19044.1348

**Comment by yaichenbaum** [comment]
Merging with #4155.

**Comment by bebotette** [comment]
I saw you merging with another issue. But this is A DIFFERENT case since I'm not talking about layout options but SORTING options. Please take a look again. TY

**Comment by yaichenbaum** [comment]
@bebotette sorry about that, I missed the part about the sorting options. Can you edit this issue to be limited to the sorting options?

**Comment by bebotette** [comment]
updated title and content.
