### ISSUE TITLE
Blurred folders and some are black!

### ISSUE THREAD

**Issue by bebotette** [files-community/Files#7083]
### Description

I think there's an issue with rendering when loading some folders. Today I encountered a folder with a lot of blurred folders inside, some of them have black containers. The folder icons looked blurred too.
The 'blacking' effect seems random since refreshing the folder, or switching between different layout modes, some black folders return to normal, while other normal folders turn to black. it's random. 
Mostly happens to layouts that require icons/thumbnails (small icons, medium icons, large icons)
See my screenshot. (PS: I intentionally blurred the folder names
![Snipaste_2021-11-26_11-17-21](https://user-images.githubusercontent.com/5653117/143521764-153fe184-4266-4821-bdb8-2a94d14937b0.png)
)

### Expected behavior

-folder icons should be crisp and clear
-no blacking of folder containers

### Files Version

Version: 2.0.34.0 

### Windows Version

OS Version: 10.0.19044.1348

**Comment by rp1231** [comment]
I'm having this problem as well.

**Comment by Josh-65** [comment]
The blured folders should be fixed in 2.3.0.0. The black background should be fixed with a refresh but isnt somthing that is fully fixable.
