### ISSUE TITLE
Can't open .url files

### ISSUE THREAD

**Issue by maicol07** [files-community/Files#7085]
### Description

Opening a .url file (internet shortcut) does nothing

### Steps To Reproduce

1. Create a url file
2. Try to open it

### Expected behavior

Opens the browser with the URL in the shortcut	

### Files Version

2.0.38

### Windows Version

Windows 11 Pro 22504.1010

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7607541/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7607542/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
