### ISSUE TITLE
Feature: Add support for selecting the breadcrumb dropdown via keyboard

### ISSUE THREAD

**Issue by Hefaistos68** [files-community/Files#7086]
### What's the Problem?

Currently the bread crumps dont open the drop down with the keyboard as in the Windows Explorer. 

### Solution/Idea

The enter key, and down arrow key should open the drop down list for the current bread crump.
The space key should enter edit mode in the navigation bar.

### Alternatives

Can leave out the space key edit mode, but the arrow key is required.

### Files Version

Version: 2.0.34.0 

### Windows Version

OS Version: 10.0.19042.1348

**Comment by yaira2** [comment]
Thank you for the feedback, I added this to the todo list.

**Comment by yaira2** [comment]
This issue will be resolved in the next update.
