### ISSUE TITLE
Add scale option for layouts. When choosing small icons, the icons are huge.

### ISSUE THREAD

**Issue by krabs-github** [files-community/Files#7087]
### What's the Problem?

When choosing small icons, the icons are huge. They are more than double the size of Windows File Explorer MEDIUM Icons option.

### Solution/Idea

Either match the default windows icon sizing or add an option to change the scale.

### Alternatives

Not using the Files application. I currently can not use the application because of how large the icons are. Real estate on my screen is precious when I am developing, 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish sizing of the different layout icons by customizing or matching the windows default | Must |
![Screenshot 2021-11-26 072601](https://user-images.githubusercontent.com/78506543/143581407-44fa50a2-9b1d-4d1a-89c3-845839712beb.png)

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.318

### Windows Version

Windows 11 Version 10.0.22000 Build 22000

**Comment by yaichenbaum** [comment]
Merging with #1940.
