### ISSUE TITLE
Add Bookmarks

### ISSUE THREAD

**Issue by Wonder-NG** [files-community/Files#7089]
Hello Hope You're fine. Please, add a bookmark feature that act juste as in Firefox, Chrome or all navigators you know. Means that When you are in a folder, you will just have to right click on the folder's title on the top of the file explorer and  on the menu click in "Book mark". Then you'll have your folder path just in the top and click on it to acess shortly your folder content without losing time to switch folder after folder.

**Comment by josh-65** [comment]
You can add folders to favourites like file explorer and I believe there a feature request about adding files to it. For now you can also use bundles on the home page witch can hold anything you want.

**Comment by gave92** [comment]
Merging with #6458

**Comment by ronakkothari123** [comment]
> You can add folders to favorites like file explorer and I believe there is a feature request about adding files to it. For now, you can also use bundles on the home page which can hold anything you want.

Forgive me for asking, but how might I go about adding a file to my favorites list?

**Comment by ronakkothari123** [comment]
Never Mind, I was able to figure it out. It was weird with pinning a cloud drive to favorites, and I had to actually locate the file in order to pin it.

**Comment by Wonder-NG** [comment]
> You can add folders to favourites like file explorer and I believe there a feature request about adding files to it. For now you can also use bundles on the home page witch can hold anything you want.

Thank you for it. I think it would be more useful and ergonomic (intuitive) if it was on the top just like in web browers. And I noticed that I'm no longer able to open a directory in VSCode, neither to other application.

**Comment by ptmrio** [comment]
+1

A dedicated browser like bookmarks bar is abolutely missing in my workflow. It would be a huge success!

**Comment by sobuj53** [comment]
I would request the developer team to consider a browser like bookmark option. For example `Clover file Explorer` has this option. ![image](https://user-images.githubusercontent.com/25761237/153075458-e5c550c6-7340-4f96-84db-4e30ea41ba36.png)
