### ISSUE TITLE
Fonts not installed correctly using shell context menu

### ISSUE THREAD

**Issue by Positron010** [files-community/Files#7093]
### Description

I noticed that when I install **fonts** using the shell context menu in Files, the process continues with no apparent errors, however the fonts are apparently not installed, and are not detected by the OS, as they couldn't be found in either the fonts settings or the control panel. Also, **install for all users** gives an error.

### Steps To Reproduce

Install a font in Files using the shell menu, and it won't be detected by the system (not installed correctly?)

### Expected behavior

Fonts should be installed as if installed using Explorer.

### Files Version

Version: 2.0.34.0 

### Windows Version

Windows 11 22504.1010

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7394
