### ISSUE TITLE
When searching, sometimes only one result is displayed

### ISSUE THREAD

**Issue by waltdestler** [files-community/Files#7094]
### Description

When searching a folder using the search box, often only one file will be displayed even if multiple files match the search text. Pressing back and then forward will display the remaining files. So far I've only been able to repro this with folders with large numbers (hundreds) of image files, but I'm not 100% sure it isn't a problem in other circumstances.

### Steps To Reproduce

1. Open a folder with a few hundred image files.
2. Type some text into the search box that you know matches the names of some of the image files. Press enter to search.
3. Very briefly (fraction of a second), all of the matching files will be displayed, but then all but one will disappear.
4. Press back and then forward.
5. All of the matching files will now be displayed.

### Expected behavior

All of the matching files should be displayed without having to press back and then forward.

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.318

### Windows Version

Edition	Windows 11 Home Version	21H2 Installed on	‎10/‎3/‎2021 OS build	22000.318 Experience	Windows Feature Experience Pack 1000.22000.318.0

**Comment by gave92** [comment]
Thanks for the report. This is fixed in latest code. In the meantime you can refresh the folder (F5) to make the results appear.
