### ISSUE TITLE
Freeze when I click on a css file with the preview tab active

### ISSUE THREAD

**Issue by LightShaft** [files-community/Files#7105]
### Description

Hello, just to report a bug I've just met

So, I've got a theme.css file (a betterdiscord theme to be precise), when I just left click on it, the preview on the left loads indefinitely but I can't do anything now except clicking on X and restarting. Without the preview tab, it works as it should.
So yeah, looks like it has trouble loading this css file.
I don't know if it can happen with all css files or if it's because of this specific one, I'll send it in case you want to check it out.
[quarrel.theme.css.zip](https://github.com/files-community/Files/files/7612444/quarrel.theme.css.zip)

Cheers

### Steps To Reproduce

Left click on the css file with preview tab active

### Expected behavior

The preview shouldn't hang the whole program

### Files Version

2.0.34.0

### Windows Version

Windows 11 Professionnel Version	21H2 2000.318

**Comment by yaichenbaum** [comment]
Is this still an issue in the latest version of Files?

**Comment by SiRo24** [comment]
For me, this issue with is still there. The preview for .css files crashes the whole program.
Files preview 2.3.63
Win 11 22623.1020

**Comment by yaira2** [comment]
@SiRo24 can you open a separate issue?
