### ISSUE TITLE
Can't open shortcuts

### ISSUE THREAD

**Issue by Deswegen** [files-community/Files#7117]
### Description

Greetings,

I noticed that if you try to open a folder shortcut it says "Access denied - Can't access any items to display".
Is there a fix to it?

### Steps To Reproduce

1. Double Click on a shortcut folder

### Expected behavior

It leads me to the folder of the shortcut.

### Files Version

Version: 2.0.34.0 

### Windows Version

Windows 11 OS Version: 10.0.22000.318

**Comment by yaichenbaum** [comment]
@Deswegen is this still as issue with v2.1.5?

**Comment by Deswegen** [comment]
Fixed with the new version!  :)
