### ISSUE TITLE
Add option to sort flyout to sort files and folders together

### ISSUE THREAD

**Issue by Darhagonable** [files-community/Files#7120]
### What's the Problem?

Currently there is an option in the global settings to list and sort directories alongside files. Problem is that i wanna have the flexibility of using this only in specific folders. Having to temporarily change the global setting each time one wanna use it is quite annoying.

### Solution/Idea

Move the setting into the sort menu in the toolbar and have it only apply to the directory in question.

### Alternatives

An even better alternative would be https://github.com/files-community/Files/issues/5834 but it's broader. I'm thinking this new issue covers the most important feature of them all and might be easier to get through.

### Files Version

2.0.40.0

### Windows Version

Windows 10 21H2 19044.1348

**Comment by TizianoMad** [comment]
Hi there,
I guess a whole customized order in addition to the other display settings could be nice.
Also, thinking about files and folders, why not display them in kind of 2 separate columns ?
and why not chose which priority between which category you wanna see first.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #9098
