### ISSUE TITLE
Unknow error

### ISSUE THREAD

**Issue by J-adon** [files-community/Files#7121]
### Description

When I'm using Files, it has a notification that has the content  "Files ran into a problem that developer has not prepared"

### Steps To Reproduce

1. Open Files
2. A bit later, a notification will pop up

### Expected behavior

Please debug as soon as possible

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.318

### Windows Version

Windows 11 21H2  22000.318

**Comment by gave92** [comment]
Thanks for the report. Please upload the app's log files. You can get them from Files Settings > About or ``%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState\` (debug.log + debug_fulltrust.log)
