### ISSUE TITLE
Search filters - Phase 2

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#7124]
### What's the Problem?

Phase 1 of the search filters is nearing completion.
I am creating this issue to discuss parsing.

Here is the actual plan.
Phase 1: Picker for date and size and groups.
Phase 2: Parsing for date and size.
Phase 3: Picker + Parsing for kind
Phase 4: Others filters.

### Solution/Idea

The detailed content of phase 2
- Add a badge on the filter menu button, when there is at least one.
- Suggestion on the parsing keys.
- Syntax and validation while typing.

When a filter is parsed, it is deleted from the search box, and added to the menu.
The badge allows you to have a visual.

The same filter can have several syntaxes.
modified:01/01/2020, date:>2020, after:2020 are equivalent.

### Alternatives

To discuss.

### Comments

Here the actual state

![badge](https://user-images.githubusercontent.com/46631671/143780477-7433d048-1028-4deb-8359-ab48884d5daf.png)
![suggestion](https://user-images.githubusercontent.com/46631671/143780482-286b5725-fda4-404f-a959-d1614ccc7415.png)
![invalid](https://user-images.githubusercontent.com/46631671/143780479-a0fdfc29-6b01-4c3c-ae71-2f263a512c77.png)
![success](https://user-images.githubusercontent.com/46631671/143780481-42ade607-25cd-4b96-9a3e-d8fe1363e1c1.png)

**Comment by xdanielc** [comment]
Another milestone this could further be improved would be filter by metadata, maybe coping some syntax form exiftool, for example: -exif:fnumber>5.6

**Comment by cinqmilleans** [comment]
@xdanielc Could you develop your idea? I do not understand.

**Comment by Tarek-Hasan** [comment]
I would like to search file/folders by attributes, now I'm using **Everything** for this.

**Comment by yaira2** [comment]
Merging with #4813
