### ISSUE TITLE
`Suggestion`: Please make it compatible with windows 7.

### ISSUE THREAD

**Issue by sapioit** [files-community/Files#7127]
### What's the Problem?

I'm trying to run it on Windows 7, but there is no `.exe` and no `.msi` file to open.

### Solution/Idea

Make it compatible with Windows 7.

### Alternatives

Offer a method of running it in windows 7 without a virtual machine.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to increase the compatibility with the systems of more users. | Must |
| This proposal will allow end users to have a better alternative to Windows Explorer than `Clover` and `Explorer++` are. | Should |
| This proposal will allow end users to have a better interface than the one in `Windows Explorer` and `Explorer++`. | Should |
| This proposal will allow developers to accomplish promoting to people who still don't want to move to a newer Windows than 7. | Could |

### Files Version

21.11.26

### Windows Version

Windows 7 Ultimate

### Comments

Please let Windows 7 users use your app.

**Comment by yaichenbaum** [comment]
@sapioit Files uses APIs specific to Windows 10 and Windows 11. We recommend updating to a recent version of Windows in order to use Files.
