### ISSUE TITLE
Open a Folder with VSCode

### ISSUE THREAD

**Issue by Wonder-NG** [files-community/Files#7128]
### What's the Problem?

We are no longer able to open a directory in VSCode, neither to other application (powershell, etc.)

### Solution/Idea

Make it available.

### Alternatives

There are no alternative to this.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.0.34.0
OS Version: 10.0.22499.1010_

### Windows Version

_Windows 11 version dev_

**Comment by yaichenbaum** [comment]
@Wonder-NG can you please fill out the version number and add repro steps?

**Comment by Wonder-NG** [comment]
Thank you @yair100 I did it :-)

**Comment by yaichenbaum** [comment]
@Wonder-NG can you upload the log files? My guess is that the full trust process crashed but I'll need the log files to confirm.
