### ISSUE TITLE
Automatic refresh after folder update

### ISSUE THREAD

**Issue by qiezhenxi** [files-community/Files#7131]
### What's the Problem?

When the contents of the folder are updated, such as copying new files into the folder, we need to refresh manually to display the new files.

### Solution/Idea

Automatic refresh after folder update

### Alternatives

Automatic refresh

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by gave92** [comment]
Merging with #6564
