### ISSUE TITLE
Preserve details view column widths and allow overriding the default sizes

### ISSUE THREAD

**Issue by CyberGen49** [files-community/Files#7132]
### What's the Problem?

If you change the size of the columns while in Details view, leaving and re-entering the directory resets those sizes to the defaults.

### Solution/Idea

I propose something similar to File Explorer's "Options > View > Apply to folders" button, which applies the current sizing for the current view to all instances of that view. This could be added as a button in the Layout menu.

If the user doesn't choose to apply their settings to all folders, we could still preserve their column widths per directory.

### Alternatives

I'm not totally sure what's meant by "Alternatives," but in terms of this issue, I'm just resizing columns as I need to, even if it means doing it repeatedly.

### Files Version

Version: 2.0.34.0

### Windows Version

Windows 11 21H2 22000.348

### Comments

I noticed that the columns responsively resize with the window size, but presumably, that could work just as well with user-defined column widths.,

**Comment by gave92** [comment]
Merging with#6448
