### ISSUE TITLE
Light/Dark Mode Issue on Properties Box

### ISSUE THREAD

**Issue by AhsanJoyia** [files-community/Files#7135]
### Description

When I select the same color (either light or dark) on both the Files and the operating system, the dark/light mode works fine.
But when I set the light mode for the Files and the dark mode for the Operating System, or the dark mode for the Files and the light mode for the Operating System, it does not show the corresponding color on the Properties box.

1st Screenshot Description:
I have selected light Mode for the operating system and dark mode for Files

![Files - Screenshot1](https://user-images.githubusercontent.com/69197057/143811604-4b70340e-67ce-44f9-868a-a62e459d0ca5.png)

2nd Screenshot Description:
I have selected dark Mode for the operating system and light mode for Files

![Files - Screenshot2](https://user-images.githubusercontent.com/69197057/143811610-e591ae0c-b1a5-4c35-a4f4-71044924022f.png)

### Expected behavior

When I set the light mode for the Files and the dark mode for the Operating System, or the dark mode for the Files and the light mode for the Operating System, the Files should show the corresponding color on the Properties window.

### Files Version

Version: 2.0.41.0

### Windows Version

OS Version: 10.0.22000.348

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7615616/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7615617/debug.log)

**Comment by gave92** [comment]
Merging with #6892
