### ISSUE TITLE
Add icon creator to custimization tab in properties

### ISSUE THREAD

**Issue by TizianoMad** [files-community/Files#7136]
### What's the Problem?

> This feature could be created as a proper separate app, and I surely can understand that.
That's why I suggest for a start that it may only be optional, for the ones who would like to customize their personal folders.
Since Windows 11 icons have been created, no proper folder customizer has been released. 😒

Here are the 2 little apps I found so far, which have some good "methods", but still not the expected result :

### Solution/Idea

#1 App Example :

I came across [very interesting little app](https://www.gdzsoft.com/), but which is unfortunately too limited. Though, the ideas are there. It lucks adding your own logo (transparent PNG) upon folders (with precise resizing and position of course), instead of just a "cheap" set. You can import a W11 folder but cannot tweak its colors, but you can on their own templates and import personal picture to fill them with, which is pretty good.

### Alternatives

#2 App Example :

I discovered [another interesting Tweaker](http://cocci10.fredisland.net/fofo/module-dossiers/contenu-du-module-dossiers/) (for W10 though, and in french) which "tries" a little better to do the job. (The creator said in the forum that this extension is minute and took him a couple of days to make, mixing [FolderPaint](https://www.sordum.org/10124/) & [ImageMagick](https://imagemagick.org/)- pity he didn't developed it a bit more, but it's just for showing the example).
It is using W11 icons, and there is a choice with many colors, nice little set of logos but still no personal ones you can integrate.

> Both of these apps provide an optional right clic option, and also surely make the folder icons >portable< (generates a "desktop.ini" file associated with its "*.ico" hidden file, both in same folder).

### Priorities

As an innovating (and best -even not pefect yet) File Explorer, "Files v2" could also integrate an updater (automatic or not /to set), some extensions /addons (like has web browsers) such as a "right click customizer" or other tweaks, in addition to the one I suggested here.

"Files v2" would also be as innovating, with proving that this "AddOn app" I suggested, by finally being the 1st decent folder customizer provider, as neither Microsoft nor thirds have been able to make. I guess copyrights protect owners (Microsoft) from illegal merchandising, but as long as it's free and for personal use, things seems to be ok.

I'm sure it will be something pretty commun in the near future, but the first "easy tweaking" and quality app needs to be experimented a bit before being validated. But when it will be the case, I guess it won't take that long before everybody loves it. 😉

### Files Version

2.0.34.0_Test

### Windows Version

Windows 10 LTSC 1809 - (& soon LTSC 21H2)

### Comments

# Custom folder example (Brave Browser) :

![1635342236](https://user-images.githubusercontent.com/90962569/143818728-b718ca67-2e85-4a8d-8f02-830267050b78.png)

**Comment by yaichenbaum** [comment]
Merging with #6871

**Comment by TizianoMad** [comment]
Hi, 

Careful, this request has got nothing to do with "patching" themes.
It's an Icon creator "option" for individual folders.

Thank you.

**Comment by yaichenbaum** [comment]
@TizianoMad once the icon is created, we would have to modify the system dlls to replace the default icon. There are other ways to do it, but they are a bit complicated and out of scope for what we plan to work on in terms of customization. It's probably better for something like this to be its own app.

**Comment by TizianoMad** [comment]
@yair100, thank for your answer.

No, it is not the case !  As I said, it's not a "patcher" modifying DLLs in the system.
It is just applying a "desktop.ini" file with the icon created in the same folder, to make it portable as well, as I described in the post.

Pity if this app can't be an exclusive addon for "Files", as customization and design are the novolties of your app.
Maybe if you know graphic designer programmers you could submit this idea to, I'm sure they will say it will be the kind of app many people need, we just need a good one. Who will be first ? 🤔

**Comment by yaichenbaum** [comment]
@TizianoMad I think I misunderstood, you're just looking for an icon creator that will set individual icons normally? It's an innovative idea but it's still a bit out of scope for Files, even so I'll reopen the issue as a discussion to see how many users are interested.

**Comment by TizianoMad** [comment]
You got it. I recon you have a lot of work dealing with all prior aspects of your app.
If you take the time to read my intro, I precisely explain it would be optional as an "extension" app.
(means won't be part of the properties unless it is voluntarily added, but you got the right idea now).
I was suggesting integrating such a new proper app as extension (it's just an idea for the future, priority for the main app of course), because it is available nowhere. I just would hope "Files" could offer such a nice feature in the future.

> (other subject : in the settings, I would love to "tic" what I want in context menu)

Thank you for considering the idea.

**Comment by josh-65** [comment]
There is better options for making custom icons like Gimp and Photoshop for this.

**Comment by TizianoMad** [comment]
> There is better options for making custom icons like Gimp and Photoshop for this.

Hi,
These are real picture editors, I'm talking about a very small specially preconfigured extension-app for W11 icons, as you can see in [# 2 App example](http://cocci10.fredisland.net/modules/images/DOSSIERS2.png).

**Comment by Nipponico** [comment]
But why don't you read icons from Registry? I usually modify all the Windows icons importing a .reg like the following:

Windows Registry Editor Version 5.00
; Enable System Icons
[HKEY_CLASSES_ROOT\batfile\DefaultIcon]
@="F:\\Icone Sistema\\EXE File.ico,0"
...
[HKEY_CLASSES_ROOT\xmlfile\DefaultIcon]
@="F:\\Icone Sistema\\INF File.ico,0"
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Shell Icons]
"3"="F:\\Icone Sistema\\Closed Folder.ico,0"
"8"="F:\\Icone Sistema\\Hard Drive.ico,0"
"107"="F:\\Icone Sistema\\Hard Drive.ico,0"
"59"="F:\\Icone Sistema\\DVD RAM.ico,0"
"7"="F:\\Icone Sistema\\USB Drive.ico,0"
"12"="F:\\Icone Sistema\\Ram Drive.ico,0"
"29"="F:\\Icone Sistema\\Shortcut.ico,0"
"0"="F:\\Icone Sistema\\Generic File.ico,0"
"1"="F:\\Icone Sistema\\Generic File.ico,0"
"2"="F:\\Icone Sistema\\EXE File.ico,0"
"4"="F:\\Icone Sistema\\Closed Folder.ico,0"

I see that my icons are loaded by Files, but immediately substituted by default icons, for example the yellow folder icon.

![Files](https://user-images.githubusercontent.com/96755755/147521693-84643cb9-2970-4031-95b0-e54da4cb68c4.png)

Only the folders with desktop.ini inside remain modified.

Why!?

**Comment by josh-65** [comment]
The Registry doesn't contain the icons. Those registry changes are just changing the icon path for certain references witch files should read if they get applies in file explorer since files reads from them.

**Comment by yaichenbaum** [comment]
We don't have plans to implement this feature.
