### ISSUE TITLE
Auto expand favorites when startup

### ISSUE THREAD

**Issue by maytinhdibo** [files-community/Files#7137]
### Solution/Idea

Auto expand favorites when startup

### Alternatives

Auto expand favorites when startup

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.0.34.0

### Windows Version

W11 22000.348

**Comment by gave92** [comment]
Merging with #6469
