### ISSUE TITLE
When I want to copy one folder to another, I copy only one empty folder with the same folder name, but not  copy the files and subfolder in the folder  that i want to copy

### ISSUE THREAD

**Issue by wxy940910** [files-community/Files#7138]
### Description

When I want to copy one folder to another, I copy only one empty folder with the same folder name, but not  copy the files and subfolder in the folder  that i want to copy

### Steps To Reproduce

N/A

### Expected behavior

Copy all the files and subfolder to dest folder

### Files Version

2.0.34.0

### Windows Version

Win10 1809 ltsc

### Relevant Assets/Logs

N/A

**Comment by japesdb** [comment]
I have encountered this problem as well. I noticed that when you cut or copy file/s or folder/s and paste them to a new directory or drive, usually you still have the old or previous folder selected which ends up with that empty folder. I always have to make sure that I have everything deselected then I paste whatever was copied or cut.
