### ISSUE TITLE
Columns view keyboard navigation

### ISSUE THREAD

**Issue by drkn** [files-community/Files#7139]
### Description

Hi, In columns view keyboard navigation seems to be broken. When you select a directory and use Enter key - selected directory opens in the same column. Navigating further down with keyboard opens all directories in the same column. When at some point you switch to mouse and double click on a directory it does nothing. The only solution it to switch back to other view and the back to columns view to make mouse navigation work again.

Another issue is that when you navigate using keyboard - newly opened directory looses focus which seems to be related with #6736

### Expected behavior

When using Enter or right arrow - selected directory should open in a new column on the right side of current one. Focus should go to newly created column the the first file on the list. Navigating up in directories structure should also be possible with left/back keys (keeping focus consistent with newly opened folders).

### Files Version

Wersja: 2.0.34.0 OS Version: 10.0.22000.348

### Windows Version

Windows 11 Pro 21H2 22000.348

### Relevant Assets/Logs

-

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7425
