### ISSUE TITLE
Scrolling in files settings broken

### ISSUE THREAD

**Issue by pcxnet** [files-community/Files#7140]
### Description

When scrolling in th settings for  "Files and folders" , the scrollbar moves, but the options do not, this then causes the alignment to be off and clicking on options to not work as exected.

### Expected behavior

Scrolling down should scroll down.

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.318

### Windows Version

Version	10.0.22000 Build 22000

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7617725/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7617727/debug.log)

**Comment by gave92** [comment]
Thanks for the report. This should be fixed in latest code.
