### ISSUE TITLE
Still not seeing Status column in most places...

### ISSUE THREAD

**Issue by brucebinder** [files-community/Files#7144]
### Description

The status column only shows occasionally. And, for some reason, many of my OneDrive items appear as hidden files (same under File Explorer). Why they are hidden I cannot figure out. But in File Explorer, the staus column shows everywhere.

I have another computer where my OneDrive does not show things as hidden and Files seems to show the status column everywhere.

### Expected behavior

Show staus column for all files and folders.

### Files Version

Version: 2.0.41.0 OS Version: 10.0.22000.348

### Windows Version

21h2 22000.348

### Relevant Assets/Logs

I have no logs to submit.

**Comment by gave92** [comment]
Could you share some screenshots of Files and Explorer that show the issue?
