### ISSUE TITLE
Add command to cmd/wsl/powershell

### ISSUE THREAD

**Issue by maytinhdibo** [files-community/Files#7157]
### What's the Problem?

Likely explore also have a command to open a folder by command.

### Solution/Idea

Likely explore also have a command to open a folder by command.

### Alternatives

Likely explore also have a command to open a folder by command.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.0.34.0

### Windows Version

W11 22000.348

**Comment by gave92** [comment]
Do you mean starting Files from command line? If so you can `> files.exe some_directory`

**Comment by maytinhdibo** [comment]
> Do you mean starting Files from command line? If so you can `> files.exe some_directory`

yes

**Comment by chtenb** [comment]
@maytinhdibo this way of opening files from the command line seems to start the app in the foreground and occupies the terminal session until you exit files again. It would be nice if it would start detached from the terminal session, just like `explorer .`.
