### ISSUE TITLE
Cannot disable the option to set Files as default

### ISSUE THREAD

**Issue by bitchyass** [files-community/Files#7158]
### Description

So I enabled the option to set Files as the default explorer application, but when I try to turn it off, it doesn't work. The prompt from Registry Editor to allow it to edit the registry does appear, but it doesn't work. When I click on the prompt for more notifications, it shows the location of the regedit file to be at "C:/Users/name/AppData/Local/Packages/49306atecsolution.FilesUWP_et10x9q9vyk8t/FilesOpenDialog/UnsetFilesAsDefault.reg" But the .reg file is missing and so, this does not work. I am hoping for either a solution or that the devs can just send a copy of the .reg file so that I can resolve this issue without having to reset my laptop. 
Thank you.

### Steps To Reproduce

1. Open Settings
2. Go to Experimental Features
3. Toggle off "Set Files as default". 
4. Prompts for Admin 
5. DOES NOT WORK, it remains ON.

### Expected behavior

It should be able to turn off without any issues to the registry or app. 

### Files Version

Latest on the Microsoft Store

### Windows Version

Windows 11 22000.348

### Relevant Assets/Logs

Cannot show Logs at the moment

**Comment by jarno9981** [comment]
@bitchyass  try to reinstall it and all remaining updates it had that before but these things fixed for my 

windows 11 build: 22000.348 beta same as you

**Comment by BanCrash** [comment]
Hi @bitchyass  , you have to follow the instructions here to unset as default file explorer:

https://files.community/docs/configuring/replace-file-explorer

TL;DR: download [this zip](https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip) and run UnsetFilesAsDefault.reg to restore windows explorer
