### ISSUE TITLE
Navigating to a directory with forward slashes breaks basic functionality

### ISSUE THREAD

**Issue by laomengwa** [files-community/Files#7159]
### Description

Windows 的文件路径格式是用反斜线"\\"表示目录，但也兼容 Unix 的文件路径格式"/"，当在"Files"的路径框内以正斜线输入我自己的文件夹路径"E:/9/media/1"无法打开文件或创建、删除、编辑文件，但可以浏览文件夹的属性。
![image](https://user-images.githubusercontent.com/69566148/144031429-227a8b39-8deb-4129-a184-88160fca439f.png)

### Steps To Reproduce

点击“文件路径输入框”，把所有的"\\"替换成"/"，按下"enter"。

### Expected behavior

修复正斜线路径下的文件操作，但不希望以字符的替换的方式实现这操作（不希望把"/"替换为"\\"）。

### Files Version

2.0.34.0

### Windows Version

Windows 11 21H2 22499.1010

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7625013/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7625016/debug.log)

**Comment by hez2010** [comment]
A brief translation: cannot use `/` as path delimiter in path bar.

**Comment by laomengwa** [comment]
> @laomengwa is this still an issue in v2.1.5?
yes,you can try input and using "/" as path delimiter.see if you can open,editing the file?
