### ISSUE TITLE
Allow sideloading the themes extension for the sideloaded files

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#7164]
### What's the Problem?

Currently the themes extension is quite hidden and not usable anyway but the store versions.

### Solution/Idea

Adding a themes download button under the current files one on the site with the same options and if sideload is picked

### Alternatives

Allow the extension to work with both store and sideloaded ones from where ever its installed from.

**Comment by yaichenbaum** [comment]
@josh-65 we're planning on replacing the theme extension in one of the next updates, can you try downloading the specific theme file directly from the repo?

**Comment by josh-65** [comment]
I can manually add the file I just like the extension since it all of them and auto updated. if it planed to be replaced that's fine ill close this.
