### ISSUE TITLE
*.txt files opened by notepad opens behind files Explorer GUI

### ISSUE THREAD

**Issue by MUH-ABDOU** [files-community/Files#7165]
### Description

any opened text file goes behind the files explorer, which requires activating the notepad from taskbar to be able to edit.

### Steps To Reproduce

open any text file.

### Expected behavior

notepad opens on top of files explorer GUI, and to be able to edit rightaway.

### Files Version

2.0.34

### Windows Version

Win11 21H2

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/89925339/144096653-b40f99e6-1403-4d5c-b30f-5b1442a07a51.png)

**Comment by gave92** [comment]
Merging with #5291
