### ISSUE TITLE
Speed Enhancements needed

### ISSUE THREAD

**Issue by MUH-ABDOU** [files-community/Files#7168]
### Description

Files takes about 2 seconds to load Drives widget on startup.
Files takes about 1 to 2 seconds to show the full context menu items on right click, it is fast and good on right click and shows some items immediately, but takes time to load the rest.

would be nice if they can get fixed as they are frequently faced while using the app.

### Steps To Reproduce

Issue1- Open Files with home tab as default, Drivers widget takes some time to load.
Issue2- Right Click any item that has lots of options in its context.

### Expected behavior

Issue1- Drivers widget available right away just like windows explorer.
Issue2- All items available with no lag.

### Files Version

2.0.34

### Windows Version

Win11 21H2

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/89925339/144104300-556ff3c2-f470-4a9b-a42f-0dd40ff1662d.png)

![image](https://user-images.githubusercontent.com/89925339/144104395-11818418-614e-42b0-aac2-7048e708cb49.png)

![image](https://user-images.githubusercontent.com/89925339/144104464-e0e4061b-e966-42e6-958c-4d1bfa6119db.png)

**Comment by yaichenbaum** [comment]
Merging with #4180

**Comment by yaira2** [comment]
We're excited to share that startup performance will be significantly improved in the upcoming release of version 3. You can download the preview version from our website https://files.community/download.

**Comment by yair100** [comment]
@MUH-ABDOU we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
