### ISSUE TITLE
Files Crashes when simply selecting all files in a massive folder

### ISSUE THREAD

**Issue by rsmyst** [files-community/Files#7169]
### Description

I have a couple picture folders with 1000+ pictures in them. FIles just seems to slow down a lot when opening those folders. 
when it finally catches up, selecting all basically kills the app. this happens rather consistently as well. 
In the end, i had to resort to copying the folders without opening them which made the issue disappear magically. 

### Steps To Reproduce

1. Have a massive folder with tons of individual items in it. 1000+ ig 
2. open it up in files
3. wait for it to fully load and then select all

### Expected behavior

Selects all like windows explorer does. but instead lags a ton before crashing most of the time. I'm scared of data loss. the crash sometimes happens during the copying too.

### Files Version

Version: 2.0.34.0 OS Version: 10.0.19043.1348

### Windows Version

10 20H1

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7627963/debug.log)

**Comment by yaichenbaum** [comment]
@rsmyst is this still an issue in the preview version? https://files.community/download/preview
