### ISSUE TITLE
I cannot see the Videos folder of my WIndows user

### ISSUE THREAD

**Issue by kaname-png** [files-community/Files#7170]
### Description

I try to enter the default folder that Windows creates for users called Videos, but when I try to enter the application closes, I do not understand why because Windows Explorer can access without problems.

### Steps To Reproduce

1. Go to 'Videos' folder
2. See error

https://user-images.githubusercontent.com/56084970/144114926-e696dc08-e75a-44ea-b7ba-3962b03982c7.mp4

### Expected behavior

Show all videos in my video folder like Windows Explorer does.

### Files Version

Versión: 2.0.34.0 OS Version: 10.0.22000.318

### Windows Version

Windows 11 Pro 21H2 22000.318

### Relevant Assets/Logs

Logs files:
[debug.log](https://github.com/files-community/Files/files/7628290/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7628295/debug_fulltrust.log)

**Comment by gave92** [comment]
Thanks for the report. Could you try the following?
- Turn off "enable individual preferences for folders" option in Files settings > files and folders
- Go to any directory and set Grid View layout mode
- Try open the Videos folder

**Comment by kaname-png** [comment]
@gave92 I did it and it has worked very well what you have told me, now I no longer get that error when viewing the videos and images folder of my Windows user.

**Comment by gave92** [comment]
Note: happens if folder is grouped and contains an element with DisplayName != Name.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7202.
