### ISSUE TITLE
Unmount ISO files

### ISSUE THREAD

**Issue by MarvinGrijalva** [files-community/Files#7171]
### Description

I have used files for some time and I consider that it is very good, better than the traditional file explorer, I have only noticed that when unmounting an ISO the unit still remains.

### Steps To Reproduce

1. Mount a ISO file
2.  Unmount a ISO file

### Expected behavior

That the units used are cleaned

### Files Version

Versión: 2.0.34.0 OS Version: 10.0.22000.318

### Windows Version

Windows 11 Pro Version	21H2 1000.22000.318.0

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/19395657/144146820-8c246b7e-1cd1-4b33-bf20-6477a3f1b0ab.png)

**Comment by gave92** [comment]
Thanks for the report. Merging with #6072
