### ISSUE TITLE
Drag file not working on win11

### ISSUE THREAD

**Issue by dayue1984** [files-community/Files#7172]
### Description

I can not drag file into wechat on windows11.
besides, I can not revert choice of setting files to defualt file manager.

### Steps To Reproduce

1. select file in files
2. drag the file onto wechat window
3. it shows "+" and file number under the mouse cursor witch means the drag operation should be receipted by wechat
4. release mouse button
5. nothing happened

### Expected behavior

it should copy files into wechat with drag operation, tested with windows explorer working good.

### Files Version

2.0.34.0

### Windows Version

10.0.22000.348

### Relevant Assets/Logs

none

**Comment by gave92** [comment]
Hi, to restore windows explorer you'll need to download [this zip](https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip) and run UnsetFilesAsDefault.reg.

**Comment by yaichenbaum** [comment]
@dayue1984 is this still an issue in the preview version? https://files.community/download/preview
