### ISSUE TITLE
Set as default Experimental Feature will not revert.

### ISSUE THREAD

**Issue by nixwf** [files-community/Files#7173]
### Description

I love this app, but it is notably slower than the default Windows 10 explorer. I recently set it as default to test it out, but i can't go back now. Whenever i click on the button to un-set it as default, it opens up a "Allow this app too maked changes to your pc blah-blah-blah", but when i click yes, it stays as my default file explorer. I'd really like to go back, but i'm unsure how to.

### Steps To Reproduce

1. Go to settings.
2. Go to Experimental
3. Click "Set files as default file explorer"
4. Click it again, but it won't go back.

### Expected behavior

I expected it to stop being my default file explorer.

### Files Version

Version: 2.0.34.0 OS Version: 10.0.19043.1348

### Windows Version

Windows 10 Pro 21H1 19043.1348

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7632015/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7632021/debug.log)

**Comment by BanCrash** [comment]
Hi @nixwf , you have to follow the instructions here to unset as default file explorer:

https://files.community/docs/configuring/replace-file-explorer

TL;DR: download [this zip](https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip) and run UnsetFilesAsDefault.reg to restore windows explorer

**Comment by yaira2** [comment]
We're excited to share that startup performance will be significantly improved in the upcoming release of version 3. You can download the preview version from our website https://files.community/download.
