### ISSUE TITLE
Google Drive Folders not showing up under "Cloud Drives"

### ISSUE THREAD

**Issue by WhosPruv** [files-community/Files#7176]
### Description

I am 3 google drive accounts logged in but the folders are not showing

![image](https://user-images.githubusercontent.com/94924029/144211761-7e5b8697-d2e8-4dbe-9ac6-9c26746d2875.png)

### Expected behavior

Should show the folders

### Files Version

Version: 2.0.41.0 OS Version: 10.0.22000.348

### Windows Version

Windows 11 21H2 22000.318

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7632793/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7632794/debug_fulltrust.log)

**Comment by gave92** [comment]
Does Google drive show under Drives section?
Could you show a screenshot of Windows Explorer sidebar?

**Comment by DanieLoche** [comment]
Indeed, I have this in Windows 10 (I just installed Files and configured my Google Drive now).
![image](https://user-images.githubusercontent.com/11614445/147881919-0076d414-7b25-4957-8786-805ab735029b.png)

**Comment by gave92** [comment]
Merging with #6321
