### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Torikkusu** [files-community/Files#7177]
### Description

total crash

### Steps To Reproduce

1 go to Libraries 
2 go to Picture
3 crash 

1 go to Libraries 
2 go to Video
3 crash

### Expected behavior

open the folder

### Files Version

Version: 2.0.34.0 OS Version: 10.0.19043.1348

### Windows Version

Windows 10 Pro 21H1 19043.1348

### Relevant Assets/Logs

I don't get any logs

**Comment by gave92** [comment]
Merging with #7170
