### ISSUE TITLE
Filter folder contents via a fuzzy search

### ISSUE THREAD

**Issue by RickeyWard** [files-community/Files#7179]
### What's the Problem?

Different than Search (which searches down from current folder) I find I'm often looking for files in the current folder but not its subfolders. I often deal with very large folders with hundreds or thousands of files in it. Its very difficult to find files I'm looking for when I remember/know only a subset of the file name and Its not the beginning. File explorer and Files both jump to the file that matches characters typed quickly in succession starting from the beginning of the filename. I often find this useless. (its nice to jump to a letter but I don't know full filenames of everything I'm looking for and Id like to filter to everything that contains x)

### Solution/Idea

The type ahead default behavior from explorer has been carried over to Files (You can type a letter to jump to the next file that starts with that letter, and if you type quickly it will select a file that matches exactly what you've typed, I don't find that very useful though I know some do)

I'd like to see a setting to change the typeahead (typing when the folder has focus) behavior to filter the current view to only those items that match the fuzzy search of what is being typed (hiding the other items) possibly with a floating text box that appears or jumping to the search box with what is being typed.

### Alternatives

in regular explorer I can use StExBar though its quite ugly since it was designed for older windows versions.
![image](https://user-images.githubusercontent.com/342468/144262771-faa6b4ec-82ed-4c40-8287-d311be1b5c5a.png)

This could be implemented by allowing a search depth modifier that's easy to change and have it where you could set the search depth to 0 so it would only look in the current folder, though It's not my preference to have to change this setting back and fourth it would solve my issue.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Filter the view with a fuzzy search matching typed text | Must |
| Still allow single letter typed to jump to the first matching file, allow typehead to filter | Should |
| have this as a setting not to bother those happy with the current config, possibly reuse the search box with filter or search based on a toggle or keyboard shortcut | Could |

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.348

### Windows Version

Windows 11 21H2 Build 22000.318

**Comment by yaira2** [comment]
Thank you for your feedback, this is on our todo list and is being planned in #14391. Please add a comment or subscribe to the issue to be notified when it's added.
