### ISSUE TITLE
I can't keep sorting preferences to stay in tact.

### ISSUE THREAD

**Issue by zzz2496** [files-community/Files#7180]
### Description

I've set my view mode to "Column", then set "Sort by" to "Date created" and "Group by" also to "Date created". If I close the tab, or close "Files" app, whenever I reopen, "Sort by" and "Group by" returns to it's default value.

### Steps To Reproduce

1. Go to "Layout"
2. Select "Columns"
3. Go to "Sort"
4. Highlight "Sort by", choose "Date created"
5. Go to "Sort"
6. Highlight "Group by", choose "Date created"
7. Close Files, then reopen
8. The "Sort" and "Layout" will return to it's default value.

### Expected behavior

I expect the Layout and Sort settings to stay even after I restart the app.

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.318

### Windows Version

Windows 11 Version 10.0.22000 Build 22000

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7635410/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7635411/debug.log)

**Comment by gave92** [comment]
Merging with #6370

**Comment by brccabral** [comment]
Hi @gave92 , was this deployed in any release? I have 2.1.13.0 but it is still an issue for me.

**Comment by gave92** [comment]
Not yet, progress is tracked in #6370
