### ISSUE TITLE
New icon for mixed operation results

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#7182]
### What's the Problem?

Currently if there a mix of successful and failed (not sure if it also does it during active ones) it will show the badge as failed.

### Solution/Idea

Add a new badge colour orange with a tilde (~) icon

### Alternatives

None

### Files Version

2.0.41.0

### Windows Version

10.0.19043.1387

**Comment by yaichenbaum** [comment]
Merging with #4811.
