### ISSUE TITLE
Network Locations or equivalent of This PC

### ISSUE THREAD

**Issue by DevTechSolutions** [files-community/Files#7183]
### What's the Problem?

When using Files vs File Explorer, I noticed that there is no way to view the "Network Locations". This is where we place all Department Share shortcuts at our enterprise, so having this feature would be amazing. It could drastically increase adoption at our organization.

### Solution/Idea

I suggest to add another tab in the sidebar for Network locations.

### Alternatives

An alternative would be to add a tab similar to This PC in File Explorer that would show the Network locations on a PC.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.0.34.0 

### Windows Version

10.0.19044.1348

**Comment by gave92** [comment]
Could you show a screenshot of windows explorer showing this?

**Comment by DevTechSolutions** [comment]
![12-01-2021-explorer_0zYCYDzuBx](https://user-images.githubusercontent.com/37643484/144325676-2b240e58-a2a1-431e-88f1-4a17f02baab9.png)

Hopefully this gives a clear picture of what I am referrring to. It is best practice to use shortcuts instead of mapped drives these days, so we push these shortcuts to all our users for accessing department shares instead of mapping drives.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7185
