### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by TCMOREIRA** [files-community/Files#7184]
### What's the Problem?

Whenever I'm on Linux I really miss having "Files" as my Files-Browser. I haven't found a replacement for it that looks just as good and with all of its functionality right out of the box (not even Nautilus + Extensions + Themes).

Would it be too much? To ask for a Linux version? 

### Solution/Idea

Making 'Files' compatible with Linux would be awesome!

Being able to download a '.flatpak' or '.deb' of it or simply compile it from the github source like many other projects do.

### Alternatives

If you guys have any suggestions on how to replicate the 'Files' experience on Linux I'm all ears.

### Priorities

Definitely a 'Could'. It would make me very happy to be able to use the same file browser on both operating systems.

### Files Version

Always the latest whenever I'm on Windows.

### Comments

I'm only asking this because I got enamored with your project! I like it a lot. ; )
Thank you for your time and forgive me in advance if what I'm asking for is too stupid.

**Comment by CHJ85** [comment]
I like this file manager a lot.
However, Linux has a ton of file managers already. So Linux support would be a waste of developer time (in my opinion). The most similar file manager to this one would probably be the Deepin file manager. You might wanna give that one a try.

**Comment by softyoda** [comment]
> [@TCMOREIRA](https://github.com/TCMOREIRA) we don't have enough resources to work on Linux version but if someone is interested in putting together a group of devs to work on such a version, I'll be happy to work with them on such a project.

Where do i give money to crowdfund this ? I hate having like gazilion of linux file explorer but all are garbage dev by people who don't even understand ux

**Comment by yair100** [comment]
@softyoda please feel free to reach out to us on Discord for further discussion.
