### ISSUE TITLE
Arrange Widgets Feature

### ISSUE THREAD

**Issue by MUH-ABDOU** [files-community/Files#7188]
### What's the Problem?

Currently I can't find an option to arrange widgets in home. for ex. make drivers widget above folders widget.

### Solution/Idea

Add an option for this either in settings or in manage widgets dropdown.

### Alternatives

N/A

### Files Version

2.0.34

### Windows Version

Win11 21H2

**Comment by yaichenbaum** [comment]
Merging with #2263
