### ISSUE TITLE
设置了默认文件管理，然后取消不掉。现在软件闪退，没法用。

### ISSUE THREAD

**Issue by groundwater-modeling** [files-community/Files#7189]
### Description

设置了默认文件管理，然后取消不掉。现在软件闪退，没法用。

### Expected behavior

It can't be set as non-default files manager.

### Files Version

win11

### Windows Version

win11

### Relevant Assets/Logs

no logs

**Comment by gave92** [comment]
Hi, download [this zip](https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip) and run UnsetFilesAsDefault.reg to restore windows explorer.

**Comment by groundwater-modeling** [comment]
> Hi, download [this zip](https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip) and run UnsetFilesAsDefault.reg to restore windows explorer.

我真的太感谢你了。Much appreciated.

**Comment by Kingqibin** [comment]
I meet the same problem, thank u so much!!!
