### ISSUE TITLE
Files keeps crashing, no visible error code

### ISSUE THREAD

**Issue by epullay** [files-community/Files#7190]
Hello!
Yesterday I installed Files on my computer, and after some hours of usage I set it as the default files explorer on win 10 enterprise.
Everything was working fine until a couple of hours had passed, and now Files won't open. It displays the splash screen of the software, holds for about 1 second and then closes automatically

![image](https://user-images.githubusercontent.com/7623299/144437349-f52ece55-3f21-46b0-8e82-0c9e776fcf4c.png)

First question (and the most obvious one): Does anyone have any idea on how to fix this?

Leading to the second one: Is there any kind of logs for the app someplace, so I can try to debug or fix this myself, or at least contribute more information on this bug?

Lastly: In case there's no way to fix this without uninstalling, is there any way to revert to the default file explorer without needing to open Files?

**EDIT:** Already figured the third question, I reverted back to the vanilla windows file explorer using the .reg file included on the documentation

**Comment by yaichenbaum** [comment]
@epullay can you upload the logs? It might be easier to open a new bug report where you can use the template to include relevant information https://github.com/files-community/Files/issues/new?assignees=&labels=bug&template=bug_report.yml.
