### ISSUE TITLE
Files crashes whenever I click on it

### ISSUE THREAD

**Issue by jesuisleprecieu** [files-community/Files#7193]
When I open Files, it just closes itself... I can't do anything except reinstalling files on the Microsoft Store... Any advice pls ?

**Comment by yaichenbaum** [comment]
@jesuisleprecieu can you upload the logs? It might be easier to open a new bug report where you can use the template to include relevant information https://github.com/files-community/Files/issues/new?assignees=&labels=bug&template=bug_report.yml.
