### ISSUE TITLE
Can't drag and drop files or folders into other places or folders.

### ISSUE THREAD

**Issue by aayushyap89** [files-community/Files#7195]
### Description

New bug, for some reason I cant drag and drop items such as images or folders into a folder, it shows that little block icon on the white square, the same one that shows up when you drag an item onto your taskbar to open chrome which dosnt work on win11 anymore but use to on win10.
Btw forgot to report so the debugfiles might be late.

### Steps To Reproduce

1. Find a file and create a folder
2. try to drag a file into that folder
3. the folder wont let you and will give you a red circle cross icon

### Expected behavior

To let me drop items into a folder.

### Files Version

v2.0.41.0

### Windows Version

Windows 11 21H2 22000.348

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7644011/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7644012/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
@aayushyap89 is this still an issue in the preview version? https://files.community/download/preview
