### ISSUE TITLE
Video previews in recycle bin broken.

### ISSUE THREAD

**Issue by aayushyap89** [files-community/Files#7196]
### Description

So whenever I clicked on a video it starts out normal for I would guess 1/4 to 1/2 a second and then it turns into this covering the whole video, I also noticed for the 1/2 second it is normal the play button is white as if I am able to click it but after it bugs out it turns this gray and I cant play it neither can I change the time line. I have restarted and tested this 3 times and found out that it is re-creatable and it only happens in the recycle bin. So videos in say videos folder didn't get this bug.

### Steps To Reproduce

1. Recycle a random video
2. go to recycle bin
3. click on the video and enable the preview pane
4. see this bug happens (image linked below.)

### Expected behavior

To not extend up that high.

### Files Version

v2.0.41.0

### Windows Version

Windows 11 21H2 22000.348

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7644026/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7644027/debug_fulltrust.log)
![image](https://user-images.githubusercontent.com/77907390/144474432-afa28de0-67ea-4f11-8951-ff5279fb997e.png)

**Comment by yaichenbaum** [comment]
@winston-de are previews meant to work in recycle bin?

**Comment by winston-de** [comment]
Yes, because it seemed to work fine, but if it's causing issues I'll make a PR so it only shows the thumbnail.

**Comment by yaichenbaum** [comment]
@aayushyap89 this issue should be resolved with #7203.
