### ISSUE TITLE
Option to disable recent files section

### ISSUE THREAD

**Issue by alirezanoori1986** [files-community/Files#7197]
### What's the Problem?

Just like the title says. I don't want the program to save the recent files that I have opened. Imagine a browser that doesn't let you clear history or disable it.

### Solution/Idea

Add an option for this. Both to disable the feature and clear current ones.

### Alternatives

Use windows options

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by gave92** [comment]
Being implemented in #5882
