### ISSUE TITLE
Remember sidebar status

### ISSUE THREAD

**Issue by alirezanoori1986** [files-community/Files#7198]
### Description

The program doesn't remember the status of lists on the sidebar. The default explorer does this. For example, I want the Favorites to be visible all the time.

### Steps To Reproduce

1. Open the program
2. Expand Favorites
3. Close the program
4. Open the program again

### Expected behavior

Favorites should be expanded

### Files Version

2.0.34.0

### Windows Version

Windows 11 10.0.22000.348

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/2578984/144481971-e8dab50d-97bb-49c6-8561-b47f5577197e.png)

**Comment by gave92** [comment]
Merging with #6469
