### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by brunur** [files-community/Files#7204]
### Solution/Idea

I do not need date/type/size columns. I remove these and resize the name column every time I load up. I'd like the ability to save the preferences so I don't have to do this every day and with every folder that I open, which is many. I work in a dozen folders and rename files constantly. Please add an 'apply to all folders' option and include all options that the windows manager does currently.

### Alternatives

My alternative is to continue using the windows file manager. 
![Screenshot 2021-12-03 084150](https://user-images.githubusercontent.com/17552385/144639774-2a8be363-d730-47e9-9915-84bb271fcdf1.png)
e 

### Priorities

| Capability | Priority |
| :---------- | :------- |

| This proposal will allow end users to accomplish saving folder preferences like windows file manager does | Should |

### Comments

Overall this is a vast improvement over the MS standard files, please keep up the good work :)

**Comment by gave92** [comment]
Try to turn off the "enable individual preferences for folders" in Files setting > File and folders. Any preference you set will be used for all folders.

**Comment by brunur** [comment]
I hadn't seen that option there. I had to increase the size of the window,
it was being cut off at the 'show unindexed items..' line.

Thank you for the help :)
