### ISSUE TITLE
Potential race condition in FileOperationsHandler

### ISSUE THREAD

**Issue by chselab** [files-community/Files#7209]
### Description

The file contains the class `ProgressHandler` whose methods `AddOperation`, `RemoveOperation`, and `UpdateOperation` may be called in parallel judging from the use of `ConcurrentDictionary`. All three methods invoke `UpdateTaskbarProgress` which ultimately uses the property `Progress`: 
https://github.com/files-community/Files/blob/3a8da90d8009010d699a1c94df9b2420d97c06fa/Files.Launcher/MessageHandlers/FileOperationsHandler.cs#L809-L816

The property makes use of the field `operations` of type `ConcurrentDictionary`. Now, to compute the actual progress, it uses a combination of LINQ-Statements. I assume the intent of `ToList` here is to create a snapshot/copy of the `operations` dictionary to run the `Where` method on it safely. Unfortunately, the `ToList` method uses an optimized copy-mechanism for collections that implement the `ICollection` interface, which `ConcurrentDictionary` does. It first retrieves the length of the source collection, initializes the internal data structure accordingly, and copies the values after that; thus, there’s a race condition between the initialization and the copy-mechanism. You can see this behavior within the reference source:

- [Enumerable.ToList]( https://github.com/dotnet/runtime/blob/e80476680121b400676f4c244afeeb98f3b08a66/src/libraries/System.Linq/src/System/Linq/ToCollection.cs#L29)
- [List]( https://github.com/dotnet/runtime/blob/e80476680121b400676f4c244afeeb98f3b08a66/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/List.cs#L66)

### Steps To Reproduce

Due to the nature of race conditions, it's hard to reproduce the error in the actual code (and probably unlikely to occur). However, you can reproduce the race condition with the following example:

```cs
public class Program {
  private static ConcurrentDictionary<int, int> dictionary = new();

  static async Task Main() {
    Console.WriteLine("starting");
    var producer = Task.Run(Produce);
    CreateToListCopies();
    await producer;
    Console.WriteLine("completed");
  }

  private static void Produce() {
    for(int i = 0; i < 100_000_000; i++) {
      dictionary.TryAdd(i, i);
    }
    Console.WriteLine("finished producing");
  }

  private static void CreateToListCopies() {
    for(int i = 0; i < 100_000_000; i++) {
      dictionary.ToList();  // race condition that leads to System.ArgumentException
      //dictionary.ToArray(); // no race condition, ToArray() correctly creates a snapshot
    }
    Console.WriteLine("finished copying");
  }
}
```

### Expected behavior

The straightforward fix is replacing the invocation of LINQ’s `ToList` with `ToArray` implementation of `ConcurrentDictionary`. Alternatively, you can apply `ToList` after the `Where` clause to not have a race condition between `Any` and `Average` (`GetEnumerator` does not create a snapshot but is thread-safe).

### Files Version

latest commit to the main branch:  fe684bc; latest commit to the document: 3a8da90

### Windows Version

any

### Relevant Assets/Logs

none

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7201.
