### ISSUE TITLE
Display more details when hovering the mouse over a file

### ISSUE THREAD

**Issue by XPoppyX** [files-community/Files#721]
- type
- size
- dimensions (if it is an image)

![tooltip](https://user-images.githubusercontent.com/61259627/80651529-10a6d680-8a44-11ea-9c92-70b0de8fd947.png)

**Comment by yaichenbaum** [comment]
I think that a teaching tip would be very useful for this task.

**Comment by Dylan-Osborne** [comment]
@xPoppyx Would something like this suffice?
It just a standard tooltip that displays for about 5 seconds.
Folder:
![ToolTipFolder](https://user-images.githubusercontent.com/46000533/82329552-c5983780-99e1-11ea-921a-05afca6d3f61.jpg)
File:
![ToolTipFile](https://user-images.githubusercontent.com/46000533/82329560-c7fa9180-99e1-11ea-95e9-927aa3602306.jpg)

**Comment by yaichenbaum** [comment]
@Dylan-Osborne That would be really great! Maybe we can add a feature flag to let you display the hash in the tooltip as well (or would that not work because of the time it takes to calculate the hash)?

**Comment by Dylan-Osborne** [comment]
@yaichenbaum I'm personally not too keen on adding the hash to the tooltip as most standard users will never use a hash.

The real problem comes that the tooltip only shows for around 5 seconds, so for larger files the tooltip may already have disappeared before the hash is calculated.

However as you suggested, it might work to add a flag that determines whether or not to include the hash. It may also be required to exclude the hash for files larger than a preset size e.g. 100mb in order for the hash to calculate before the tooltip disappears?

**Comment by xPoppyx** [comment]
I don't think it will be useful if it takes time to show

**Comment by yaichenbaum** [comment]
@Dylan-Osborne I agree with your points, I think we should leave the hash alone for now. If we do decide to add it later, we can always do it behind a flag.

**Comment by generalguy41** [comment]
Why does the tooltip need to disappear after a set time? Would it not be better to have it replicate the explorer functionality?

**Comment by yaichenbaum** [comment]
The tooltip is just to get a quick glance at the information.

**Comment by generalguy41** [comment]
That's fair, but the way it works in explorer still serves that purpose

**Comment by Dylan-Osborne** [comment]
@generalguy41 I agree with you that the tooltip should display for longer (explorer shows for 32 seconds), unfortunately the tooltip duration property is not available for UWP at the moment. I've tried using other components, but as far as i can see it then breaks the capability to select files.

An issue regarding the missing properties has already been created [here](https://github.com/microsoft/microsoft-ui-xaml/issues/2262) so hopefully this functionality will be added soon.

@duke7553 The current name tooltip also only shows for 5 seconds, so is it worth adding the additional properties to the tooltip and hoping that Microsoft adds the duration property soon or should we just leave the tooltip as is for now?

**Comment by yaichenbaum** [comment]
@Dylan-Osborne The tooltip should be limited to basic information such as the file size and file name. If the user wants more information, they are likely to open the properties window.

**Comment by Dylan-Osborne** [comment]
@yaichenbaum Sorry, I don't think I worded that quite right. I 100% agree with you on only the basic info/file properties being shown. When saying "adding the additional properties to the tooltip" I meant just the basics such as those listed so far in this issue.

**Comment by winiston2212** [comment]
I don't know if this is still being worked on, but I think it would be useful to also show cloud drive sync status and shortcut destinations in the tooltip.

Cloud drive:
![image](https://user-images.githubusercontent.com/59544401/90327058-9cd20080-df44-11ea-9b3a-725b71872fdd.png)
![image](https://user-images.githubusercontent.com/59544401/90327106-0fdb7700-df45-11ea-8141-3febd0f9fc3b.png)

Shortcuts:
![image](https://user-images.githubusercontent.com/59544401/90327072-bbd09280-df44-11ea-9a7e-5984d645d86d.png)
![image](https://user-images.githubusercontent.com/59544401/90327089-e6bae680-df44-11ea-8180-0f3d45c776bb.png)
