### ISSUE TITLE
Bug: No prompt is displayed when shortcut cannot be created

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#7211]
### Description

Admin folders like programs folder can not have shortcuts be made. with file explorer it will ask to make it on the desktop with files it just doesn't do anything

### Expected behavior

Should ask to make it in a user specified location (desktop default)

### Files Version

2.0.41.0

### Windows Version

10.0.19043.1387

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7654173/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7654174/debug_fulltrust.log)

**Comment by Arno989** [comment]
Do you have any information on where this issue is? I might make an attempt myself to try and solve it

**Comment by Josh-65** [comment]
As far as i know it comes from Files not making an admin resquest to make the file in the folder.

**Comment by yaichenbaum** [comment]
The interesting thing is that once the shortcut is created, you can then transfer it to the location (eg. startup folder). I wonder if we can display a UAC prompt and continue with the intended action.

**Comment by Josh-65** [comment]
Merging with #10987
