### ISSUE TITLE
File operations improvements

### ISSUE THREAD

**Issue by alirezanoori1986** [files-community/Files#7216]
### What's the Problem?

As described in "Idea" section.

### Solution/Idea

- Add a button to clear all completed operations.
- An option to automatically remove completed operations
- Option to show operations in a panel/dialog when they are running

### Alternatives

N/A

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
@alirezanoori1986 the first issue is already resolved in `main`. Can you open individual issues for the others so we can track them seperately?

**Comment by alirezanoori1986** [comment]
@yair100 Done.
