### ISSUE TITLE
Copy and Paste doesn't work !

### ISSUE THREAD

**Issue by CHALENCON-Yoan** [files-community/Files#7219]
### Description

When I try to copy and paste a file or a folder, it's not working !
When I copy, the paste logo lights up but when I click on it, nothing happens, not even an error message.
If I paste the file on my desktop, it works and if I do with Windows File Explorer, it works to.

### Steps To Reproduce

1. Select a file or a folder
2. Click on copy
3. Go to an other folder (or not)
4. Click on paste
5. Observe that nothing is happening

### Expected behavior

By doing this, the file or the folder should be duplicate in the new destination.

### Files Version

Version : 2.0.34.0 OS Version: 10.0.22000.348

### Windows Version

Windows 11 Famille Version 21H2 22000.348

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7655648/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7655650/debug.log)

**Comment by gave92** [comment]
Merging with #7459

**Comment by TRI-SS** [comment]
try to copy my ssh key into my terminal, it does not work  
basically i can't copy ans paste into my terminal

**Comment by Josh-65** [comment]
That would be a terminal issue and not Files
