### ISSUE TITLE
An option to automatically remove completed operations

### ISSUE THREAD

**Issue by alirezanoori1986** [files-community/Files#7224]
### Solution/Idea

An option to automatically remove completed operations

### Alternatives

N/A

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
@alirezanoori1986 do you mean a button or a setting that will not show completed operations to begin with?

**Comment by alirezanoori1986** [comment]
A setting that, if turned on, will automatically remove the completed task from the "ongoing tasks" section. So suppose you copy a file. During the copy process, it is shown on the "ongoing tasks operations" and the progress is shown. As soon as it's finished, it'll be removed.

**Comment by yaichenbaum** [comment]
@alirezanoori1986 I'm not against this, can you share a little more feedback though on why this would be useful for your workflow? We like to show completed tasks so users can check the speed graph (once it's added) and other relevant details about the completed operation.

**Comment by alirezanoori1986** [comment]
So this is tied with the other feature that I requested. [#7225](https://github.com/files-community/Files/issues/7225). If I see the progress while it's running, I don't need to see the completed task hanging around anymore so I want it gone. (if you copy with native explorer, once it finishes, you don't see any trace of it).
This could be merged with that. So on the right-hand side of the panel, there would be an "auto-remove" or something like that switch that would automatically remove the finished tasks and hide the panel when no task is running to restore the real estate (to show more files).

![image](https://user-images.githubusercontent.com/2578984/144760470-8bf089e6-8e88-429f-b683-0482176360d1.png)

**Comment by yaira2** [comment]
Thank you for sharing your feedback. We don't have plans to implement this option right now, but we'll make sure to update the community if we decide to add it in the future.
