### ISSUE TITLE
Feature: Option to show operations in a panel/dialog when they are running

### ISSUE THREAD

**Issue by alirezanoori1986** [files-community/Files#7225]
### Solution/Idea

Option to show operations in a panel/dialog when they are running

### Alternatives

N/A

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
@alirezanoori1986 this isn't very hard to implement but I'm not sure it makes sense to move it out of the main view. We've come to the understanding that it's best to keep whatever possible in the main view. Is there any specific use case where moving the operations to their own dialog would improve your workflow?

**Comment by alirezanoori1986** [comment]
Actually, I don't like dialogs either. However, I would prefer to see the progress in more detail when something is running. A simple progress bar on a button is not very helpful. Ideally, I would like to see something like Chrome's download progress which shows you the progress, current speed, current file, etc. at the bottom of the main view.

**Comment by yaichenbaum** [comment]
> Actually, I don't like dialogs either. However, I would prefer to see the progress in more detail when something is running. A simple progress bar on a button is not very helpful. Ideally, I would like to see something like Chrome's download progress which shows you the progress, current speed, current file, etc. at the bottom of the main view.

Can you upload a screenshot of Chromes progress UI?

**Comment by alirezanoori1986** [comment]
![image](https://user-images.githubusercontent.com/2578984/144760267-ae06030b-5078-4e2c-9411-39929ecaaa48.png)

**Comment by yaichenbaum** [comment]
@alirezanoori1986 we plan to show more than just the speed and I don't think that can fit in the status bar. Once those indicators are added to the flyout, are you fine with clicking to button to check on the detailed progress? The reason I ask this is that displaying operations in a separate dialog will require the same amounts of clicks to view the progress but the flyout is integrated and quicker to find. This scenario would be a little different on a split screen or multi monitor setup so it'll be good to get your feedback.

**Comment by alirezanoori1986** [comment]
I personally think that you're going about the file operations wrong. You're treating them like a download. In a download operation, you care about the final product (the downloaded file). In a file operation, what you care about is the progress of that operation. Why would I want to see how a download went? On the other hand, I want to follow the progress of a file operation (especially if it's long) as it's happening.
You might sometimes do hundreds of file operations in a day. Imagin the operation dialog piling up after each rename, delete, copy, etc. I honestly wouldn't care to go back to see which of them took 1 second or 2 hours.
However, if my browser downloaded a file and didn't keep track of those downloads, I would be mad because I want to do something with the downloaded file. Open it, move it somewhere, etc.
I have multiple monitors and most of the time when I'm copying/moving a large number of files, I move them to a secondary monitor while working on my stuff. Sometimes the main task that I'm doing is in the explorer itself, but I want to keep close attention to the file operation that's happening right now.
So maybe, if the number of details cannot fit the panel, your best option would be a dialog. It's flexible and can be moved around.

Well, these are my personal opinions and I might be completely off but I thought to share them with you.

**Comment by yaichenbaum** [comment]
> You might sometimes do hundreds of file operations in a day. Imagin the operation dialog piling up after each rename, delete, copy, etc. I honestly wouldn't care to go back to see which of them took 1 second or 2 hours.

I added your issue regarding this to the backlog 👍 

> I have multiple monitors and most of the time when I'm copying/moving a large number of files, I move them to a secondary monitor while working on my stuff. Sometimes the main task that I'm doing is in the explorer itself, but I want to keep close attention to the file operation that's happening right now.
So maybe, if the number of details cannot fit the panel, your best option would be a dialog. It's flexible and can be moved around.

Well, these are my personal opinions and I might be completely off but I thought to share them with you.

Given your workflow, I think I have a better picture of your feature request. Sorry for all the questions, just wanted to make sure I understood the use case 🙂

**Comment by alirezanoori1986** [comment]
No problem at all. BTW, I created a very similar program a long time ago. Unfortunately, I got tied up with work and couldn't update it after UWP but Files is almost everything that I wanted to implement so that's mainly the reason that I'm so excited about this program. Who knows, maybe if I find the time, I'll jump in and add a couple of PRs. But if you have the time, just take a look at my old design. I have some features in there that are still missing in the current version of Files. There might add a couple of sparks.

**Comment by yaichenbaum** [comment]
> No problem at all. BTW, I created a very similar program a long time ago. Unfortunately, I got tied up with work and couldn't update it after UWP but Files is almost everything that I wanted to implement so that's mainly the reason that I'm so excited about this program. Who knows, maybe if I find the time, I'll jump in and add a couple of PRs. But if you have the time, just take a look at my old design. I have some features in there that are still missing in the current version of Files. There might add a couple of sparks.

@alirezanoori1986 thank you!

**Comment by esibruti** [comment]
Wouldn't it be interesting to use it?:
[Microsoft Docs](https://docs.microsoft.com/en-us/windows/apps/design/controls/infobar)

**Comment by myfix16** [comment]
@yair100  I agree with this proposal that it's better to see the progress in more detail when something is running. Users get used to the fact that, when they copy, move, or delete something, there will be a dialog showing the progress. For Files, when you do such operations, there's no obvious notification, which makes you doubt whether the action is being performed or not.

If the change proposed by @alirezanoori1986 requires discussions and cannot be made now, at least we can add a badge to the task center button, indicating the number of ongoing tasks. 
![image](https://user-images.githubusercontent.com/61649477/229507840-4e798ae6-1c6f-478e-ac1f-5b51368c4d0c.png)

**Comment by yaira2** [comment]
@alirezanoori1986 can you try v3 and see if your feedback has been addressed?
