### ISSUE TITLE
Detection default language work incorrectly

### ISSUE THREAD

**Issue by caffeine-mgn** [files-community/Files#7226]
### Description

By default I use `Russion` language in my windows. In `Files` sets as language `Windows default`. In fact `Files` uses `English` language

### Steps To Reproduce

1. Switch langiage of your OS to some not English langiage. For example to Russian.
2. In `Files` set as language value `Windows default`
3. Look to English interface of `Files`

### Expected behavior

`Files` should use system language

### Files Version

2.0.31.0 21H2

### Windows Version

Windows 11 Pro 22000.348

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7656800/debug.log)

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?
