### ISSUE TITLE
Sidebar isnt collapse when open files

### ISSUE THREAD

**Issue by koddajr** [files-community/Files#7229]
### Description

![image](https://user-images.githubusercontent.com/53986027/144796550-5647e2cc-58a7-4abb-88c4-0aa804aa36cc.png)

As you can see on image, is expandend but isnt showing anythink, i need to click 2 times to show again... is possible to make always collapsed or add a option to it.

### Expected behavior

When i set a menu to be collapsed, persist it even if i close the app.

### Files Version

Versão: 2.0.34.0 OS Version: 10.0.22509.1011

### Windows Version

22059.1011

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7658432/debug.log)

**Comment by gave92** [comment]
Merging with #6469
