### ISSUE TITLE
Creat New File

### ISSUE THREAD

**Issue by anantguru** [files-community/Files#7230]
### Description

Right Click-New Tab- File 

this option open for name of file created by you but after feeding name of file nothing happening
no any file create in particular folder like Microsoft Power point, excel, word etc...    

### Expected behavior

create a new file by new tab option 

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.318

### Windows Version

Windows 11 Pro Version	21H2  22000.318 Windows Feature Experience Pack 1000.22000.318.0

### Relevant Assets/Logs

![Screenshot 2021-12-06 172359](https://user-images.githubusercontent.com/95623278/144841648-37d5e345-893d-4ff2-af2d-f0221f41dba4.jpg)

**Comment by TechyAditya** [comment]
Well, I do not get any problems. I am able to create any filename with extension easily. I tried making a file named hello.txt and it worked just fine.

**Comment by yaichenbaum** [comment]
@anantguru is this still an issue in the preview version? https://files.community/download/preview
