### ISSUE TITLE
Bug: After editing shortcut file information it doesn't get update until next folder refresh

### ISSUE THREAD

**Issue by BanCrash** [files-community/Files#7233]
### Description

When you edit the info of a shortcut, you'll need to refresh the folder to get the updated shortcut information (the icon is updated though):

![GIF 06-12-2021 16-06-10](https://user-images.githubusercontent.com/11770760/144870171-2b4b16d2-3632-4ec2-907d-c7f7a2a20359.gif)

On the gif I've tried two times before refreshing to make sure that it's not a question about opening one time after editing it to get the refreshed info.

I opened the Eclipse lua shortcut and edited its info with the GifCam info, and I needed to refresh the folder to have the new shortcut information.

EDIT: I've forgot to capture the mouse , I can add a new gif if it's not very clear what the issue is.

### Steps To Reproduce

1. Open the properties of a shortcut
2. Edit its information and save it
3. Open its properties again.
4. It will show the previous properties

5. Refresh the folder and then open its properties again. Now it will show the updated shortcut information.

### Expected behavior

It should show the updated information without refreshing the folder.

### Files Version

Versión: 2.0.39.0 OS Version: 10.0.19044.1387

### Windows Version

Windows 10 21H2 19044.1387

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7661660/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7661661/debug.log)

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by BanCrash** [comment]
> Is this still an issue in the preview version? https://files.community/download/preview

Just tested and yes, it's still happening.

**Comment by BanCrash** [comment]
> I can't reproduce this issue in 2.4.81.0

Me neither, closing.
