### ISSUE TITLE
文件夹背景黑色

### ISSUE THREAD

**Issue by mrzouzou** [files-community/Files#7235]
### Description

白色主题下偶尔打开文件夹，子文件夹背景黑色，必须手动放大缩小后黑色背景消失

### Expected behavior

解决白色主题下文件夹背景出现黑色的bug

### Files Version

版本: 2.0.34.0 OS Version: 10.0.22000.348

### Windows Version

Windows 11 专业版  21H2  22000.348 

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7664690/debug.log)

**Comment by gave92** [comment]
Merging with #6373
