### ISSUE TITLE
Recycle Bin deletes the format of my files

### ISSUE THREAD

**Issue by Altdanielplay** [files-community/Files#7241]
### Description

![image](https://user-images.githubusercontent.com/93309350/145155519-9a84b6a0-4f51-437b-8eb0-eaca454078f5.png)

When I accidentally delete a photo or document, when I recover it from the recycle bin, it loses its file format and I have to add it manually

### Expected behavior

Hope they can fix it

### Files Version

Versión: 2.0.34.0 OS Version: 10.0.22000.348

### Windows Version

Windows 11 21h2 (compilation SO 22000.348)

### Relevant Assets/Logs

idk

**Comment by gave92** [comment]
Thanks for the report. This is fixed in latest code. In the meantime the workaround is to enable "show file extensions for known file types" option in Windows Explorer.
