### ISSUE TITLE
Crash on opening terminal from context actions

### ISSUE THREAD

**Issue by dimankiev** [files-community/Files#7242]
### Description

Sometimes, when I try to open the Windows Terminal instance via Files v2 context menu, the app runs into a problem, resulting in a crash.
Windows Terminal Preview, Version: 1.12.2931.0

### Steps To Reproduce

1. Open Files v2
2. Go to desired folder (It was located in "Libraries/Documents")
3. Right-click on blank space in folder items list container to open the context menu
4. Left-click on "Open in terminal..."

(Reproduces not constantly, works as expected after 2nd relaunch)

### Expected behavior

I have expected Terminal to open.

### Files Version

Version: 2.0.34.0 OS Version: 10.0.19043.1348

### Windows Version

Windows 10 Enterprise 21H1 19043.1348

### Relevant Assets/Logs

Log files:
 - [debug.log](https://github.com/files-community/Files/files/7675498/debug.log)
 - [debug_fulltrust.log](https://github.com/files-community/Files/files/7675499/debug_fulltrust.log)

P.S. Under `**CONFIDENTIAL**` marks were only `[a-zA-Z0-9\.]+` characters (`\.` as a dot `.`)
Path length limitations are also disabled.

**Comment by gave92** [comment]
Thanks for the report. Threre's a chance this has been fixed by #7017 / Files beta 2.0.42.

**Comment by gave92** [comment]
I believe you should
