### ISSUE TITLE
files as default explorer can't be changed back

### ISSUE THREAD

**Issue by BlacklightYT** [files-community/Files#7245]
### Description

First i was suprised by the features by the app.
And I have tried files as the default explorer.
Because of some minor inconveniences, I wanted to leave files and change the default explorer back to the file explorer, but I can't.
Is there any other issue like that, haven't found any (Is this a clone?).

### Steps To Reproduce

1. install files
2. go to settings
3. change files as default explorer
4. wait some time

### Expected behavior

Possibility to turn it off again

### Files Version

2.0.34.0

### Windows Version

Windows 10 Pro 21H2

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7677514/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7677515/debug.log)

**Comment by josh-65** [comment]
https://files.community/docs/configuring/replace-file-explorer
follow the instructions for removing it as default

**Comment by yaichenbaum** [comment]
@BlacklightYT did you uninstall Files? Uninstalling Files will not revert the changes and in the latest version of Files, reinstalling Files will result in a broken state where the app cannot toggle the feature on or off. This issue has been resolved and will be included in the next update but in the meantime, you can use this script to revert the changes https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip.

**Comment by BlacklightYT** [comment]
Thank you guys, 
yes I once deinstalled files, because of a misconception or something else, i already fargot why, but after reinstalling it, the option for files as a default explorer was turned off again. Since then I haven't deinstalled the client until today, when i couldn't turn off the option.

**Comment by Saf0001** [comment]
I can't access this website. Is there any other way to recover it, or can you send the file to my email?
 My email :saf20080508@foxmail.com
Thank you very much
