### ISSUE TITLE
Having two tabs open and dragging one will close the other window

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#7246]
### Description

If I have two tabs open and move the one I want to go into a new window it just closes the other one and open the new one.

### Expected behavior

It should keep both windows open at the same location set

### Files Version

2.0.41.0

### Windows Version

10.0.19043.1387

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7677948/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7677949/debug_fulltrust.log)

**Comment by ariana2011** [comment]
This is still an issue in version 2.1.0.0

**Comment by yaichenbaum** [comment]
This issue should be reslolved with #8433
