### ISSUE TITLE
Allow default actions in confit dialog

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#7247]
### What's the Problem?

Currently i use replace existing as the default but all the time it generate new name adding extra steps.

### Solution/Idea

Add a options in settings with a drop down box allowing changing the default action.

### Alternatives

Save the last used result

**Comment by MagikarpLaCarpe** [comment]
i agree with this that is the last and only reason on why i am not using this app...

**Comment by yaichenbaum** [comment]
Merging with #6942
