### ISSUE TITLE
Drag/Drop multiple selected files from ND Files to new email message window (outlook& gmail)

### ISSUE THREAD

**Issue by Aoxe** [files-community/Files#7249]
### Description

Files open split screen with a new o365 updated Outlook email message.  Files has 4 tabs open of different network drives and one synced Onedrive.  I CAN select multiple files from one of the network drive but CANNOT drag and drop them into the Outlook email body to attached them to the email.  A red circle replaces the mouse icon.

### Expected behavior

I would have expected the files I had selected to be dragged to the Outlook email message window, dropped within the body of the email to attach them to the email.

### Files Version

Version: 2.0.34.0 OS Version: 10.0.19043.1348

### Windows Version

Windows 10 Pro 21H1

### Relevant Assets/Logs

![ms_files_drag_and_drop_from_email](https://user-images.githubusercontent.com/78890988/145323233-5407a2e4-8ea5-4848-bd32-96f96b1b8e3c.png)

**Comment by gave92** [comment]
Does dragging and dropping a single file work?
Does dragging and dropping multiple files work if after starting to drag you wait a few seconds before moving the mouse out of Files window?

**Comment by Aoxe** [comment]
A single file moves fine.  The dragging and dropping multiple files does work if I wait a few sec before moving the mouse out of the first window.

**Comment by gave92** [comment]
Closing as #8047 added progress in status center to show when files are ready to be dropped.
