### ISSUE TITLE
winget version is outdated

### ISSUE THREAD

**Issue by shayvt** [files-community/Files#7250]
### Description

winget version is outdated of files is 0.9.1.0

### Expected behavior

winget version should be Files latest version

### Files Version

n/a

### Windows Version

n/a

### Relevant Assets/Logs

Files                               Files-Community.Files               0.9.1.0

**Comment by yaichenbaum** [comment]
We no longer support a custom WinGet version, instead, you can install Files through WinGet using the Microsoft Store as a source. Can you open an issue on the WinGet repo about the outdated package?

**Comment by da-anda** [comment]
you should probably remove your app from the winget repo then, because people trying to install it form there (which I just did) will end up with a super old version. Also, your website is still linking to winget as download option and will download the super outdated version.

**Comment by lbueker** [comment]
@yaira2 What was the reason to not support a custom WinGet version? Is it a lot of effort to support this?
In my case this would be useful, because MS store is blocked on all of our work devices.

**Comment by yaira2** [comment]
It's just not high on our priorty list, there is however a Choco version, can you see if that works?

**Comment by Josh65-2201** [comment]
@shayvt Files is now available to download on Winget
