### ISSUE TITLE
Frequent crashes followed by inability to reopen the window (on Windows 11)

### ISSUE THREAD

**Issue by navedrasul** [files-community/Files#7252]
### Description

On Windows 11 I've been facing frequent crashing of the app followed by the window failing to open on successive attempts to open the app. This failure is observed as an auto-crash as soon as the window launches upon the clicking of the app icon. Please resolve this soon as it is already hindering my work (and probably many others) frequently.

### Expected behavior

1. The app shouldn't crash during normal browsing activity.
2. The app shouldn't crash as soon as it is launched. If it does, it should "temporarily" start in safe-mode (and "temporarily" reset itself to the default settings that are sure to work)

### Files Version

2.0.34.0

### Windows Version

10.0.22000.348

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7685301/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7685302/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
@navedrasul is this still an issue in the preview version? https://files.community/download/preview
