### ISSUE TITLE
Can't replace items with folders that need admin privileges to move

### ISSUE THREAD

**Issue by MUH-ABDOU** [files-community/Files#7254]
### Description

Cutting an item to system folder (Admin privilege needed) and replacing the already existing items fails. 
Items are not cut nor system folder items are replaced.
copying however works.

### Steps To Reproduce

cut an item
go to system directory
paste and replace

### Expected behavior

system folder items gets replaced and cut items gets cut.

### Files Version

2.0.34

### Windows Version

Win11 21H2

### Relevant Assets/Logs

N/A

**Comment by yaichenbaum** [comment]
This issue should be resolved with #8809
