### ISSUE TITLE
Add option to rename pinned items

### ISSUE THREAD

**Issue by xmha97** [files-community/Files#7256]
### What's the Problem?

I can't change favorite item name:
![image](https://user-images.githubusercontent.com/23485114/145475946-e05fc0cf-2a12-4edb-8241-0cb3ec6df8d5.png)

### Solution/Idea

Can change favorite item name.
**File Explorer of Windows 7**
![image](https://user-images.githubusercontent.com/23485114/145477397-3b1b037c-d492-4321-8f02-0d2db455c075.png)
![image](https://user-images.githubusercontent.com/23485114/145477740-5e687c88-388c-4a3a-abf6-2dfa8d1b61f2.png)

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end-users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end-users to accomplish Z | Won't |

### Files Version

Version: 2.0.42.0

### Windows Version

Windows 11 21H2 22000.348

**Comment by MalteTasler** [comment]
Same as #3422 .

**Comment by yaichenbaum** [comment]
@MalteTasler #3422 is about creating a custom name without affecting the original name, this issue is for changing the actual name.

**Comment by MalteTasler** [comment]
@Josh-65 according to Yairs comment above, these two issues are not the same. :) Or did I miss any news on that?

**Comment by Josh-65** [comment]
Oh, didn't seem like that from the description. Il let Yair decide if they should be separate still

**Comment by yaichenbaum** [comment]
They should be kept separate

**Comment by sthivaios** [comment]
Yep, that is a good idea. It should be implemented as a feature.

**Comment by yaira2** [comment]
@xmha97 we don't have plans to support directly renaming from the sidebar, but you can open the properties window and rename the folders from there.
