### ISSUE TITLE
Unable to transfer files from compressed files open with 7zip

### ISSUE THREAD

**Issue by Nilcouv** [files-community/Files#7258]
### Description

Actual Behavior:
The user is unable to transfer files from a compressed file open with 7zip by : 

- Drag and Drop
- Copy - Paste

### Steps To Reproduce

1. Open a compressed file
2. Select the content of the compressed file
3. Drag and drop / copy-paste the content in a folder open with "Files"

### Expected behavior

- by drag and drop : the cursor transform into a forbidden sign to indicate that the action impossible/ not allowed
- by copy - paste : nothing happen

### Files Version

Version 2.0.34.0

### Windows Version

Windows 10 21h2 ( 19044.13448)

### Relevant Assets/Logs

- No problem with the default files manager of windows

**Comment by yaichenbaum** [comment]
Thank you for taking the time to report this, can you please upload the log files?

**Comment by Nilcouv** [comment]
[debug.log](https://github.com/files-community/Files/files/7707593/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7707594/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
> [debug.log](https://github.com/files-community/Files/files/7707593/debug.log) [debug_fulltrust.log](https://github.com/files-community/Files/files/7707594/debug_fulltrust.log)
> 
> I have since installed the version of the app on the Window store, so I'm not sure if the initial log files were kept

Not a problem, I just want to confirm that you reproduced the issue before uploading the log files?

**Comment by Nilcouv** [comment]
yes, I reproduce the bug

https://user-images.githubusercontent.com/51994423/146080264-1af0567c-5c22-418b-a882-6bb06a8747ea.mp4


[debug_fulltrust.log](https://github.com/files-community/Files/files/7714774/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7714775/debug.log)
g

**Comment by yaichenbaum** [comment]
Thanks

**Comment by Korkman** [comment]
I believe this has been fixed? I cannot reproduce with Windows 10 Pro 21H2 (19044.1466), Files 2.1.2.0 and 7-Zip 19.0, also 7-Zip 21.07 (x64 version).

* Drag & drop works as expected (cursor shows "Copy to X" label) on drop).
* Copy & paste is not available in 7-Zip (there is no "copy" in the menus and ctrl-c / ctrl-v doesn't do anything in Windows Explorer either).
