### ISSUE TITLE
Change sections with links in settings dialog to function as regular buttons

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#7260]
### Description

If this hasn't been change in the settings redesigned, on windows it allows you to click the whole thing to open and external link but with files its a button.
![image](https://user-images.githubusercontent.com/26977075/145623205-13b1e201-9644-4d0a-acf8-bfdbd62e13af.png)

### Expected behavior

Allow clicking on the whole button area

### Files Version

2.0.42.0

### Windows Version

11.0.22518.1000

### Relevant Assets/Logs

Not needed

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7336
