### ISSUE TITLE
Crashing when pasting/deleting large files

### ISSUE THREAD

**Issue by RandomParacodes** [files-community/Files#7262]
### Description

UWP apps have been infamous for crashes and freezes, and Files is not an exception.

### Steps To Reproduce

Most common reproduction I can find:
Management of a number of files, can be easier to reproduce when the files are large in size. When do a copy/paste/delete, instant crash.
Elongated use decreases the stability.
Leave it for a long moment in the background and when you reopen it, you can either meet a freeze or a crash.

### Expected behavior

To the file management part, the expected behavior to see is that it should handle with no sweat.

### Files Version

Version: 2.0.34.0

### Windows Version

Windows 11.0.22509.1011

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7696282/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7696283/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
Is this still an issue in the latest preview build? https://files.community/download/preview
