### ISSUE TITLE
Copy and Paste Not working in phone storage.

### ISSUE THREAD

**Issue by Chintan8169** [files-community/Files#7263]
Copying files from phone's internal storage to laptop works but if I try to copy files in phone's internal storage from laptop it does not work.
Also do note that in neither of above case it shows percentage of transfer complete. It stuck at 0%.
Also If I try to copy small files like 1 GB and it works but big files does not works.

**Comment by yaichenbaum** [comment]
@Chintan8169 thank you for taking the time to report this, in order to investigate the issue we'll need the log files and steps to repro this bug, can you please reopen this issue using the issue template?
