### ISSUE TITLE
Show full name

### ISSUE THREAD

**Issue by BAKHSHAWI999** [files-community/Files#7264]
Is it possible to add a feature that allows showing the full file name, because currently if the name is long its text disappears

The name appears like this if the text is long

![NVIDIA_Share_d15mUp9HXK](https://user-images.githubusercontent.com/17739512/145698205-d1e6b89d-4ee0-481e-92f2-4a16142d4ed2.png)

While in Windows Explorer the name appears in full

![NVIDIA_Share_tvOtNAMWRs](https://user-images.githubusercontent.com/17739512/145698214-db9c92d9-28ab-483e-964a-cbd4e81877c7.png)

**Comment by gave92** [comment]
Merging with #1033.
