### ISSUE TITLE
preview panel 

### ISSUE THREAD

**Issue by Heimdallr8181** [files-community/Files#7265]
### What's the Problem?

The preview panel is tiny and should be more adjustable.

### Solution/Idea

I habe no idea

### Alternatives

Maybe a pop up

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by gave92** [comment]
Merging with #6628
