### ISSUE TITLE
Icons on sidebar have white background when patching system dlls

### ISSUE THREAD

**Issue by Pinghigh** [files-community/Files#7267]
### Description

i'm sorry that i cannot speak english well
切换系统图标后，files边栏显示的图标会带白边
![图片](https://user-images.githubusercontent.com/77083712/145716177-0bd7be6c-4ab1-4176-a1dd-c5acde08b0df.png)
如图

### Steps To Reproduce

1.change the icons with 7tsp
2.open the Files with dark mode

### Expected behavior

兼容第三方图标或者支持替换图标

### Files Version

版本: 2.0.34.0 OS Version: 10.0.22000.348

### Windows Version

windows 11 22000.348

### Relevant Assets/Logs

![图片](https://user-images.githubusercontent.com/77083712/145716252-7079a1be-c479-455c-8cad-f703fe5694c0.png)

**Comment by yaichenbaum** [comment]
@Pinghigh can you upload the log files?

**Comment by yaichenbaum** [comment]
@Pinghigh can you check if the icon has a white background in some resolutions?

**Comment by Pinghigh** [comment]
> @Pinghigh can you check if the icon has a white background in some resolutions?

yes, i tried in 800*600, but it still has a white background

**Comment by yaichenbaum** [comment]
@Pinghigh is this still an issue in v2.1.5?

**Comment by Pinghigh** [comment]
![图片](https://user-images.githubusercontent.com/77083712/151952623-39779140-ddab-4f82-aa1e-a7e5dcb3d15a.png)


> @Pinghigh is this still an issue in v2.1.5?

yes

**Comment by yaichenbaum** [comment]
@Pinghigh we're closing this issue for now as we don't support patching system dlls.
