### ISSUE TITLE
Text scaling issues

### ISSUE THREAD

**Issue by TechyAditya** [files-community/Files#7268]
### Description

I am getting weird font issues if I increase the font size of windows. 

### Steps To Reproduce

1. Set display scaling to 100%
2. Set font size to 125-150%
3. Open files app

### Expected behavior

Text to be neat and properly aligned

### Files Version

2.0.34.0

### Windows Version

Windows 11 Insiders 10.0.22518.1000

### Relevant Assets/Logs

Watch steps to reproduce, it's common on all laptops.

**Comment by yaichenbaum** [comment]
@TechyAditya can you add some screenshots showing where the issue exists?

**Comment by TechyAditya** [comment]
![image](https://user-images.githubusercontent.com/72063181/145744256-e2e29403-a31c-4fba-968d-da72baf23e85.png)

**Comment by yaichenbaum** [comment]
@TechyAditya thanks! I'm going to merge this with #5958.

**Comment by TechyAditya** [comment]
> @TechyAditya thanks! I'm going to merge this with #5958.

Yeah, both are different issues but ultimately they are scaling related issues. I didn't notice the settings part though. I fixed this issue by setting both windows scaling and font size to 100%.

**Comment by yaichenbaum** [comment]
@TechyAditya changing the scaling does resolve the issue but the app should really work as expected when it's set to 125/150.
