### ISSUE TITLE
Drive Stays In Sidebar After Ejection

### ISSUE THREAD

**Issue by dbeck12** [files-community/Files#7269]
### Description

When a drive is connected, it shows up as it should but when the device is ejected and removed from the system, it still shows up in the sidebar. When I click eject, it doesn't go away and there is no way that I could find that gets it to go away.

### Steps To Reproduce

1. Plug in a drive
2.  Eject the drive
3. Drive will remain shown in sidebar

### Expected behavior

When I click on eject drive, the drive should not be shown in the sidebar.

### Files Version

Version: 2.0.34.0 

### Windows Version

OS Version: 10.0.22000.348

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/77400420/145720722-e26ff516-9b38-4390-804e-fe2b1e74d967.png)
![image](https://user-images.githubusercontent.com/77400420/145720751-8bc550f6-60e1-4ae9-9c1b-a4d2c015563e.png)
![image](https://user-images.githubusercontent.com/77400420/145720768-6b423c0b-b118-4d8d-90cf-a0a76a11ffdf.png)
Above is before I clicked eject and below is after I clicked and nothing changed.
![image](https://user-images.githubusercontent.com/77400420/145720781-f4915b24-2552-49d2-8151-923c836679e9.png)

**Comment by gave92** [comment]
Merging with #6439
