### ISSUE TITLE
Feature: Display shell items in main context menu when right clicking on sidebar

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#7273]
Shell items are currently displayed in a sub menu when right clicking on the sidebar. It'll be more intuitive to display shell items in the main menu when right clicking on the sidebar.

**Requirements**
Handle shell items in the sidebar menu the same way it's handled in the file area (display 3 shell items in the main menu and the rest in the "more" sub menu)

**Comment by human1978** [comment]
![73DC8F4B-EFDF-41A4-95F0-A7FE25419F42](https://user-images.githubusercontent.com/94195136/146575360-62574ff8-6821-4c9c-9365-e7454898a32d.jpeg)

**Comment by human1978** [comment]
Actives install

**Comment by yaichenbaum** [comment]
Shell items are only shown in the "more" menu. This is requesting for them to be displayed in the main menu.
