### ISSUE TITLE
Option to Mirror Drive layout from the Default file manager

### ISSUE THREAD

**Issue by ZaneDragonBorn** [files-community/Files#7274]
### What's the Problem?

The current way you guys have set up drives means that it's harder for me to use this as a default. I like to have my One Drive and PC drives accessible easily. However, the current system defaults their categories to collapse and makes the OneDrive take extra clicks just to open. Below are pics of the Default app and Files.
![image](https://user-images.githubusercontent.com/68198648/145744460-23a9727e-7f36-412e-b733-80486aa56cf9.png)
This shows my ideal menu. Although not perfect (I don't want the Linux thingy) it's better. I need both the OneDrive and Google Drive things to be accessible.
![image](https://user-images.githubusercontent.com/68198648/145744572-da4fb165-e661-494c-8560-f0645701c426.png)
This is the current one. Always opens with the categories collapsed and never shows my Google Drive thing.

### Solution/Idea

Please make this support the [Google Drive for Desktop Integration](https://github.com/Stratium/Google-Drive-for-Desktop-Integration) and also display everything like the default app. It wouldn't hurt to also offer some customization to this too.

### Alternatives

Nothing other than not using the app.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Mirror the Default Files manager drive setup | Must |
| Add support for the Google Drive Integration | Should |
| Make extra layers of customization for it. Such as adding new categories | Could |

### Files Version

Version: 2.0.34.0

### Windows Version

Windows 11 21H2 22000.348

### Comments

The app also needs some major performance improvements. Currently, it takes way too long to load in all of my drives and data. Without that, I can't use this productively.

**Comment by yaichenbaum** [comment]
@ZaneDragonBorn you can expand the categories in Files and it should remember your preference across sessions.

**Comment by ZaneDragonBorn** [comment]
> @ZaneDragonBorn you can expand the categories in Files and it should remember your preference across sessions.

The first time it didn't but the second time did. May just have been a temp bug
