### ISSUE TITLE
Copy and Paste Not working in phone storage

### ISSUE THREAD

**Issue by Chintan8169** [files-community/Files#7288]
### Description

Copying files from phone's internal storage to laptop works but if I try to copy files in phone's internal storage from laptop it does not work.
Also do note that in neither of above case it shows percentage of transfer complete. It stuck at 0%.
Also If I try to copy small files like 1 GB and it works but big files does not works.

### Steps To Reproduce

connect android phone via data cable.
try to copy file greater than 1 or 2 GB from pc to phone's internal storage.
see notification in files app.
it will stuck at 0%.
Open Task Manager there will be no disk usage means no copying of file.
try to copy file greater than 1 or 2 GB from phone's internal storage to pc.
see notification in files app again.
it will stuck at 0%.
Open Task Manager there will be some disk usage depending on speed of computer.(It copies file.)
File will copy but percentage stuck at 0%.

### Expected behavior

Should show percentage in both senario.
Also should copy file to internal storage of phone.

### Files Version

Version: 2.0.34.0 OS Version: 10.0.19044.1387

### Windows Version

Windows 10 pro, OS build-19044.1387 ,Windows Feature Experience Pack-120.2212.3920.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7709310/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7709311/debug_fulltrust.log)
![copying to pc](https://user-images.githubusercontent.com/76155947/145947243-9a84fcd2-2a57-4587-96d1-3347cad9b984.jpg)

**Comment by gave92** [comment]
Merging with #3317
