### ISSUE TITLE
Add support for windows default file operations as default behaviour.

### ISSUE THREAD

**Issue by bcrdncola** [files-community/Files#7289]
### What's the Problem?

When copying/pasting files, the app uses its internal method for copying/pasting, which can be quite slow at times. Internal method provides little feedback on its progress for long operations, requiring the user to click the progress icon to see it's status. 

### Solution/Idea

Allow the internal copy/paste functions to be replaced with windows default behaviour, and by extension, third party methods (such as Terra Copy which replaces windows default, but only if Windows Explorer is used as file browser). 

User should be given the option in the Settings on which method (windows default or Internal) to use.

### Alternatives

Alternative is to allow for multithreaded file copy as well as including a more detailed progress indication via popup window or otherwise.

**Comment by yaichenbaum** [comment]
@bcrdncola we're already using the built-in file explorer file operations. @gave92 is there any reason it would be falling back to the storage apis?

**Comment by gave92** [comment]
Not that I'm aware of, should use shell operations in most locations, including network shares

**Comment by yaichenbaum** [comment]
@gave92 are there performance differences are should Files be the same as File Explorer?

**Comment by bcrdncola** [comment]
performed a quick test - using Explorer, a copy of 1060 items totalling 36.15 GB, took 1:33. Explorer used Terracopy for the process as I have Terracopy's shell integration enabled. Copying the exact same files to the exact same locations in Files using whatever method it utilizes (it did not bring up Terracopy when the paste was performed) took functionally the same amount of time. (roughly a 2 second time difference, in favor of explorer/Terracopy).

My comment regarding the speed of the copy should be ignored, however I would still much prefer the shell integration Terracopy utilizes be used instead of whatever process Files currently uses, due to its much more robust logging and error handling.

**Comment by yaichenbaum** [comment]
We don't have plans to support third party file operations, rather, we're working on improving the speed in Files so you won't have to rely on additional software.

**Comment by Codel1417** [comment]
> We don't have plans to support third party file operations, rather, we're working on improving the speed in Files so you won't have to rely on additional software.

What about resuming transfers after reboots, automatic handling of network dropouts, verifying transfer after completion?

**Comment by yaichenbaum** [comment]
We're actually interested in picking this up again. Open to ideas if anyone has experience with this.
