### ISSUE TITLE
network folder auto refresh 

### ISSUE THREAD

**Issue by Chrisswl** [files-community/Files#7290]
### What's the Problem?

When creating a folder, currently it does not refresh and will have to refresh manually. 

 

### Solution/Idea

Add auto-refresh function to network drives.

### Alternatives

Otherwise, the program is almost perfect!

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by gave92** [comment]
Merging with #5869
