### ISSUE TITLE
Drag tabs causing files to crash on Win11

### ISSUE THREAD

**Issue by TommyIX** [files-community/Files#7293]
### Description

When dragging tabs to blank area, I expect new window of files created. But files report unknown error and then crashed.
![image](https://user-images.githubusercontent.com/55588115/146127450-cf38f0cc-8c75-48ed-b890-dd908e48ca35.png)
![image](https://user-images.githubusercontent.com/55588115/146127531-18f33271-d15d-40d8-9151-99c0ed3c42d7.png)

### Steps To Reproduce

1. Open multiple tags on files
2. Drag out one tag just as creating a new window in chrome
3. Files crash

### Expected behavior

Just like chrome, drag and create a new window can be good. I can see the tab dragged to blank area is marked with "Link". I wonder if this is the cause, when files try to link to another area when I expect a new window.
I am a AMD HEDT user, the default explorer always stuck, and I expect files be the ultimate alternative. Hope you can fix this quickly😀

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.318

### Windows Version

Windows 11 21H2 22000.318

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7716612/debug.log)

**Comment by yaichenbaum** [comment]
Merging with #7246
