### ISSUE TITLE
Increase the size of breadcrumbs textblocks 

### ISSUE THREAD

**Issue by MarcAnt01** [files-community/Files#7294]
### What's the Problem?

The size of breadcrumbs is too small, for example settings app has a very huge size
![image](https://user-images.githubusercontent.com/43090263/146169819-2df2a97d-6cbd-48f5-ad86-7d226bda13f1.png)
I understand anyway that in the case of Files it would be a waste of space, so I'd just ask it to make it the same size of the search textbox text, since currently it smaller than it should be.
![image](https://user-images.githubusercontent.com/43090263/146170291-dc656cb7-8e48-4f76-aa51-9b8cb4757b5a.png)

### Solution/Idea

slightly increase the size of the text to match it with the search textblock

### Alternatives

None

### Priorities

| This proposal will allow end users to accomplish X | Should |

### Files Version

Version: 2.0.42.0 OS 

### Windows Version

Windows 11 21H2 10.0.22000.348

**Comment by yaichenbaum** [comment]
@MarcAnt01 do you want to work on this?

**Comment by MarcAnt01** [comment]
I can work on this around the end of December, but not any time soon, if someone else would like to step in it's ok

**Comment by MarcAnt01** [comment]
@yair100 can you unassign me on this? The incompatibility of Files with VS2019 is preventing me from contributing

**Comment by yaichenbaum** [comment]
I'm going to close the issue as we no longer plan on making this change.
