### ISSUE TITLE
Use arrows (or add keyboard shortcuts) for moving between 'levels' in the column view

### ISSUE THREAD

**Issue by siemaho** [files-community/Files#7296]
### What's the Problem?

There is no option of taking full advantage of column view using keyboard only.

### Solution/Idea

Either assign left/right arrows (logical since up/down already enable vertical navigation).

### Alternatives

Enable users to assign their own keys for that functionality.

### Files Version

2.0.34.0

### Windows Version

Windows 10 Pro Version	20H2; Windows Feature Experience Pack 120.2212.3920.0

### Comments

-

**Comment by yaichenbaum** [comment]
Mergning with #7139.
