### ISSUE TITLE
Column View :: Show 

### ISSUE THREAD

**Issue by siemaho** [files-community/Files#7297]
### What's the Problem?

When using up/down arrows for vertical navigation in column view, selected folder's contents are not being shown in the next column.

### Solution/Idea

Make the column indexing/listing refresh whenever a folder is selected using arrows, as it is currently when using the mouse.

### Files Version

Version: 2.0.34.0 OS Version: 10.0.19042.1348

### Windows Version

Windows 10 Pro Version 20H2 19042.1348 Windows Feature Experience Pack 120.2212.3920.0

**Comment by yaichenbaum** [comment]
Merging with #7246.
