### ISSUE TITLE
Files doesn't show the weight of the files

### ISSUE THREAD

**Issue by Mariete124** [files-community/Files#7303]
### Description

When you try to see in inflo the weight of a file it just say 0. And also in the preview windows it doesn't show it neither

### Steps To Reproduce

1. Go to a file
2. Right click
3. Info

### Expected behavior

It shoud give the extac weight of that file. And it shoud appear in the preview window too

### Files Version

2.0.34.0

### Windows Version

Windows 10 pro 20h2 19042.1348

### Relevant Assets/Logs

![Captura de pantalla (8)](https://user-images.githubusercontent.com/94454662/146388465-cab7fd2b-f566-452e-abe4-cfbd8125dc0c.png)

**Comment by josh-65** [comment]
Are you sure the folder has files in it with content? As for the size in the item list there currently an experimental option for insider builds for it but isn't support for 2.0.34.
