### ISSUE TITLE
When you delete, create, or do something to a file it doesn't appear at the momento you have to do F5

### ISSUE THREAD

**Issue by Mariete124** [files-community/Files#7304]
### Description

You do some kind of file operatión, you delete one file, change the name or something. And when you do it everything keep the same. You have to refresh the page to see it

### Steps To Reproduce

1. Go to a file
2. Delete it
3. It doesn't do it
4. Refresh it
5. Now it does

### Expected behavior

You shoud see at the momento the canges, if you delete, or do something

### Files Version

2.0.34.0

### Windows Version

Windows 10 pro 20h2 19042.1348

### Relevant Assets/Logs

![Captura de pantalla (11)](https://user-images.githubusercontent.com/94454662/146389329-1c04324b-a4e8-4a8c-9974-79ab11b6fcd6.png)
![Captura de pantalla (12)](https://user-images.githubusercontent.com/94454662/146389332-02661f5a-8cb7-44d1-8ba2-f43b4bb1c4db.png)
![Captura de pantalla (13)](https://user-images.githubusercontent.com/94454662/146389333-f7346dcd-88e7-473c-86b5-6691edade184.png)

**Comment by Moustik2002** [comment]
hi, i'm encountering same issue here.

**Comment by Mariete124** [comment]
Hi, I've found the solution. You need to go to advance setting and activate set at default explorer

**Comment by Moustik2002** [comment]
on my side, even with default explorer set to Files, i need to hit F5 to have updated view of folder content.

**Comment by almostserious** [comment]
Im on Version: 2.1.2.0
OS Version: 10.0.22000.434 

In a normal environment there is auto refresh happening for me. 
However, as soon as I manage a Network share (SMB in my case) every change is only reflected after refresh.
This is even if the File Explorer is set to be the default explorer.

**Comment by Moustik2002** [comment]
that's also the case for me when i try to edit soemthing on my nas shared folder for instance.

**Comment by kennyvv** [comment]
I'm running into the same issue here, my documents folder is a network folder. When i delete a file i have to press F5 for it to be removed from the list.

The same issue occurs when creating a new file.

Version: 2.1.2.0
OS Version: 10.0.19044.1415

**Comment by reave** [comment]
I am also having the same issue when managing mapped drives or shares over UNC.

Version: 2.1.5.0
OS Version: 10.0.22000.438

Settings Backup: 
[Files_2.1.5.0.zip](https://github.com/files-community/Files/files/7967168/Files_2.1.5.0.zip)

**Comment by Moustik2002** [comment]
tested on Version : 2.1.5.0, still have to hit F5 to see the result of a deletion in network folder

**Comment by infuriatedcodex** [comment]
> tested on Version : 2.1.5.0, still have to hit F5 to see the result of a deletion in network folder

Same ... on latest Windows 11 - 22000.469 (latest at time of writing).
Does not appear to happen anymore on local disks.

**Comment by markohau** [comment]
> tested on Version : 2.1.5.0, still have to hit F5 to see the result of a deletion in network folder

I have same issue.
Also if I try to delete multiple files it tells me that it deleted the files but in reality it deleted only the first file in selection. If I use Windows Explorer it deletes the files just fine so it is not an configuration issue on the network share side.

**Comment by Josh-65** [comment]
Since the only issue seems for network locations this will be merged with #5869
