### ISSUE TITLE
I want to remove it as a default app

### ISSUE THREAD

**Issue by PTU93** [files-community/Files#7305]
### Description

Files has been my default file viewer, I want to change it back to File Explorer. The switch in the settings page doesn't deactivate it. Just flicks back on.

### Steps To Reproduce

1. Settings
2. Experimental
3. Default app

### Expected behavior

To actually remove the Files app as a default file viewer

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.348

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎11/‎23/‎2021 OS build	22000.348 Experience	Windows Feature Experience Pack 1000.22000.348.0

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7728322/debug_fulltrust.log)

**Comment by DAmNRelentless** [comment]
There is a method to revert this on their docs. You download the archive and run the `UnsetFilesAsDefault.reg`.
Since this is directly merging the changes with your registry, this should work as intended: https://files.community/docs/configuring/replace-file-explorer
