### ISSUE TITLE
"Send to" missing

### ISSUE THREAD

**Issue by JimOGorman** [files-community/Files#7312]
### Solution/Idea

Add Send to... in right click menu option

### Alternatives

Long click on the file or folder could bring up this option

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by gave92** [comment]
@yair100 I see that similar feature requests have been closed (#2940, #285). Is it still the case?

**Comment by gave92** [comment]
@JimOGorman what do you use that menu most? For "send to desktop"? For "send to compressed folder"?

**Comment by yair100** [comment]
> @yair100 I see that similar feature requests have been closed (#2940, #285). Is it still the case?

Yes, there doesn't appear to be much difference in the send-to feature as opposed to opening a new tab.

**Comment by JimOGorman** [comment]
> @JimOGorman what do you use that menu most? E.g for "send to desktop (create link)", "send to compressed folder" or other?

Usually send to an external drive / flash drive

**Comment by JimOGorman** [comment]
@gave92 More like "Copy to E:\" kinda thing.

**Comment by xeddmc** [comment]
I use it daily to "Send To Desktop (Create Shortcut)". Actually it's omission is why I had to move back to default Windows Explorer. I couldn't get used to having to manually create and move shortcuts around. Hopefully there will be a way to do this in the future

**Comment by yaichenbaum** [comment]
@xeddmc you can right click on files/folders and click on create shortcut.
