### ISSUE TITLE
Issues With Preview-Version and ms-appinstaller

### ISSUE THREAD

**Issue by warappa** [files-community/Files#7313]
### Description

On up-to-date Windows 11 https://files.community/download/preview produces the following Windows error message in the app installer:
```
ms-appinstaller protocol has been disabled (...)
```
For more info see here:  
https://techcommunity.microsoft.com/t5/msix-deployment/the-ms-appinstaller-protocol-has-been-disabled/m-p/3038361

### Steps To Reproduce

1. Open https://files.community/download/preview and allow opening the Windows app-installer.
2. See error message
![image](https://user-images.githubusercontent.com/886232/146623493-c6855a59-1254-4576-98c5-f710430ac8fb.png)

### Expected behavior

https://files.community/download/preview should trigger a working setup routine.

### Files Version

2.0.42.0

### Windows Version

Windows 11 22000.376

### Workaround
Strip the `ms-appinstaller:?source=` prefix from the redirect-link and access the XML-file directly. Look for `MainBundle`, then `Uri`. Use this link to install the app.

For 2.0.42.0 it's:
https://filescommunity.blob.core.windows.net/files/preview/Files.Package_2.0.42.0_Test/Files.Package_2.0.42.0_x86_x64_arm64.msixbundle

**Comment by yaichenbaum** [comment]
@warappa thanks for bringing this up, Microsoft temporarily disabled the protocol, but they are working on bringing it back. In the meantime, you can download Files using the direct path or from the Microsoft Store.
