### ISSUE TITLE
Unable to restore default explorer

### ISSUE THREAD

**Issue by XavierWang3P** [files-community/Files#7314]
### Description

After I set Files as Explorer.exe, I couldn't restore the operation.

### Expected behavior

- The option of setting Files as default explorer can't be shut down.
- I found an article (link: [https://zhuanlan.zhihu.com/p/112818801](https://zhuanlan.zhihu.com/p/112818801)) that introducing how to change default explorer through regedit, however, even if I deleted the *DelegateExecute*, it still can't solve the problem.

### Files Version

Version: 2.0.34.0, OS Version: 10.0.22000.376

### Windows Version

Windows 11 21H2 22000.376

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7739360/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7739361/debug_fulltrust.log)

**Comment by BanCrash** [comment]
Hi @XavierWang3P  , you have to follow the instructions here to unset as default file explorer:

https://files.community/docs/configuring/replace-file-explorer

TL;DR: download [this zip](https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip) and run UnsetFilesAsDefault.reg to restore windows explorer
