### ISSUE TITLE
Cannot reset Experimental/ Default File Explorer

### ISSUE THREAD

**Issue by aerioeus** [files-community/Files#7316]
### Description

I have tried out the experimental feature to set Files as Default. Now that I want to reset it, it doesnt change back to Windows explorer. Where can I find the setting responsible for the Default to delete it?

merci A 

### Steps To Reproduce

go to Experimental
uncheck the button "Default File Explorer"

### Expected behavior

let me uncheck the button "Default File Explorer" and stay unchecked

### Files Version

2.0.34.0

### Windows Version

Windows 10 2HJ 2021

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/23232503/146651844-8431102e-1d84-49fc-b66d-4e3787ac36fa.png)

**Comment by gave92** [comment]
Hi to restore classis Explorer, download [this zip](https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip) and run "UnsetFilesAsDefault.reg".
