### ISSUE TITLE
Default-explorer-setting won't turn off.

### ISSUE THREAD

**Issue by T-electroJo** [files-community/Files#7317]
### Description

Hello there,
the app is very cool and I really liked it so far. It just takes a little long to start.

Now I had activated the experimental function "Use as standard explorer". However, this can no longer be deactivated and so I can no longer use my old, normal Windows Explorer.

Please help quickly!
LG

### Steps To Reproduce

1. Activate "Use as Default-Explorer"
2. Try to disable it.

### Expected behavior

The function should turn off and i can use the Windows-Explorer via "Win + E" and in the Taskbar normally.

### Files Version

Version: 2.0.34.0 OS Version: 10.0.19044.1415

### Windows Version

Windows 10 21H2 19044.1415

### Relevant Assets/Logs

-

**Comment by gave92** [comment]
Hi to restore classis Explorer, download [this zip](https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip) and run "UnsetFilesAsDefault.reg".

**Comment by T-electroJo** [comment]
Hi,

thank you so much! It worked for me.

Greetings from Germany,
Jonas
________________________________
