### ISSUE TITLE
Unpin recycle bin option doesn't work

### ISSUE THREAD

**Issue by babakfp** [files-community/Files#7318]
### Description

Hi
I installed the app 10min ago.

When I right-click and click on the "Unpin from Favorites" option on the "Recycle Bin", it doesn't do anything.

In the Sidebar settings, the "Pin Recycle Bin to favorites" option is off. When I turn it on, then turn it off it works and it's gets removed from the Sidebar.

I tested to see that is it only for the "Pin Recycle" or it's for all directories. It was only for the "Pin Recycle". Now I can't bring back the "Documents" directory. Ok, I just did it. Feature request: add the "Documents" to the Sidebar settings page like the "Pin Recycle".

In the video, you can see that after closing and opening the app, the "Pin Recycle" issue was fixed. I mean, it didn't fix but it unpinned.

https://user-images.githubusercontent.com/44144724/146657568-ff0d9be6-ea2e-469b-af08-6bd7a0edeb55.mp4

### Expected behavior

_

### Files Version

2.0.34.0

### Windows Version

Windows 11 Pro - 10.0.22000 Build 22000

### Relevant Assets/Logs

_

**Comment by theBU3NO** [comment]
Confirming the same for me.

**Comment by yaichenbaum** [comment]
@babakfp is this still an issue in v2.1.13?

**Comment by babakfp** [comment]
Hi
2.1.13.0 **Yes**

**Comment by babakfp** [comment]
https://user-images.githubusercontent.com/44144724/154401933-6e9b458e-9500-4ba2-a41d-ef2879a3f120.mp4

**Comment by babakfp** [comment]
> @babakfp is this still an issue in the preview version? http://files.community/download/preview

Yes, it works fine.

https://user-images.githubusercontent.com/44144724/168650006-e83762a0-b7dd-4674-be80-339bc1b9c22a.mp4
