### ISSUE TITLE
BUG Report

### ISSUE THREAD

**Issue by Fannzc** [files-community/Files#7319]
### Description

1.主页有时候识别不到驱动器，需要关闭重新打开
2.鼠标点击复制、剪切、粘贴功能无法使用，键盘也是如此
3.无法完全取代系统资源管理器，在其他软件许多时候点击后跳转的是系统自带的资源管理器
4.在winrar类似的解压软件中无法做到直接拖动以解压

1. Sometimes the home page cannot identify the drive. I need to close and open the home page again
2. The copy, cut, and paste functions cannot be used, nor does the keyboard
3. It cannot completely replace the system resource manager. In many cases, the resource manager of the system is clicked after other software is clicked
4. In WINRAR similar decompression software can not be directly dragged to decompress

### Expected behavior

FIX BUG

### Files Version

版本: 2.0.34.0 OS Version: 10.0.22000.376

### Windows Version

版本	Windows 11 专业版 版本	21H2 安装日期	‎10.‎16 ‎周六 操作系统版本	22000.376 体验	Windows 功能体验包 1000.22000.376.0

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7740189/debug_fulltrust.log)

**Comment by josh-65** [comment]
its best to split all issues in a separate issues as they can be tracked better.
issue 1 is being tracked with #6182. 
issues 2 and 4 more information is need as I can do them fine. 
issue 3 doesn't make sense as files doesn't have resource manager.
