### ISSUE TITLE
The 

### ISSUE THREAD

**Issue by vstar37** [files-community/Files#7320]
![image](https://user-images.githubusercontent.com/70553922/146669274-c5a07e63-7dda-423e-97d5-b9ea5226d388.png)
It will auto turn on.

**Comment by d2dyno1** [comment]
Please provide more details about the issue

**Comment by gave92** [comment]
Hi to restore classis Explorer, download [this zip](https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip) and run "UnsetFilesAsDefault.reg".
