### ISSUE TITLE
Add support for adding drives to favorites section

### ISSUE THREAD

**Issue by ZaneDragonBorn** [files-community/Files#7321]
### What's the Problem?

I can't favorite Drives or Files. This is kinda a bummer since it would give easier access to stuff. Also, you can't unfavorite stuff in the Home page.

### Solution/Idea

Allow them to be favorited. Only difference with a favorited file would be it is shown as a grid below favorited drives and folders.

### Alternatives

Nothing other than deal with it.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Favoriting of Drives | Must |
| Make it possible to toggle favorites in home menu | Should |
| Allow favoriting of files. | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.0.34.0

### Windows Version

Windows 11 Home 21H2 22000.376

### Comments

Hope this gets added.

**Comment by Naworm** [comment]
Please do it...

**Comment by yaichenbaum** [comment]
This issue should be resolved with #9380
