### ISSUE TITLE
Option to hide files that start with "." in the WSL section

### ISSUE THREAD

**Issue by PicoPlanetDev** [files-community/Files#7322]
### What's the Problem?

Files shows all files that start with "." which are usually hidden in Linux file managers, such as:
- .hushlogin
- .bashrc
- .profile
However, Files and Windows Explorer show these files by default with no way to hide them.

### Solution/Idea

Add an option to Files to hide these files when browsing subfolders of the WSL directory \\wsl.localhost\ or even a custom directory.
In the settings menu, add a tab (that only appears if a WSL distribution is installed to avoid confusing unfamiliar users) that covers all WSL settings, such as show WSL in the sidebar, hide/show different distributions, select directories to hide files that start with "."
Selecting custom directories would be useful because maybe you only want to hide them in subfolders of home so that if you ever need to go searching through subfolders of / the hidden files still show.

Allow users to turn this on and off easily (without the need for the settings menu) maybe something like this:
![Untitled](https://user-images.githubusercontent.com/50522829/146683499-5392d21b-f3cb-40e1-a208-dd1eac491eb0.png)

### Alternatives

General "Filters" option:

- Apply hide/show things that match XXX to certain folders
- Apply filters to just one folder or to all subfolders

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow WSL users to hide files that Linux file managers would normally hide | Must |
| This proposal will allow WSL users to choose specific locations to hide these files | Should |
| This proposal will allow WSL users to enable or disable this entirely on a whim such as in the top right ribbon | Could |

### Files Version

Version: 2.0.42.0

### Windows Version

Edition	Windows 11 Home Insider Preview Single Language Version	Dev Installed on	‎12/‎17/‎2021 OS build	22523.1000 Experience	Windows Feature Experience Pack 1000.22523.1000.0

**Comment by yaichenbaum** [comment]
Merging with #2587
