### ISSUE TITLE
React to dbClick

### ISSUE THREAD

**Issue by CosmicRide** [files-community/Files#7323]
### What's the Problem?

We hope you add this feature: 
After double click ,it can return to the previous level。
This would be a very useful & convenient operation。

### Solution/Idea

After double click ,it can return to the previous level。

### Alternatives

You can refer to clover [http://cn.ejie.me/]

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
Merging with #2355
