### ISSUE TITLE
Caching Files app in memory

### ISSUE THREAD

**Issue by TechyAditya** [files-community/Files#7325]
### What's the Problem?

Files app takes a while to launch, like 10 seconds to fully load everything like drives, shortcuts, navigation bar, etc. 

### Solution/Idea

Cache files app in memory at the startup, so that it'll launch as fast as one-click (whatsapp UWP beta does the same). 

### PC specs

Windows 11
Intel i7 10th gen 
M.2 SSD drive
16 GB ram

**Comment by yaichenbaum** [comment]
@TechyAditya we already do this with Files but due to some platform bugs, it doesn't seem to make a difference. We're hoping to get this working when we switch to WinUI.
