### ISSUE TITLE
File Renaming UX Improvement

### ISSUE THREAD

**Issue by Vinfall** [files-community/Files#7326]
### What's the Problem?

For now when renaming a file/folder in `Files`, when file name is limited to not exceed the width of the `Name` column, which can make the file name less unreadable than the original `Windows File Explorer` (I hope it's called that...).

A simple contrast between the two explorers:

1. Files
![Files](https://user-images.githubusercontent.com/91039000/146752376-3f30d5bc-6e5d-4a72-985c-bc1188b425d1.png)

2. Windows File Explorer
![Explorer](https://user-images.githubusercontent.com/91039000/146752561-bce7ea16-b05d-4cfc-b3d3-05c21952ec93.png)

### Solution/Idea

Mimick the behavior of the original Windows file explorer, i.e., let the file name exceeds the `Name` column when renaming, to improve file name readability.

### Alternatives

1. Show a seperate prompt window to enter the new file name (`Dolphin` by KDE does that IIRC).
2. When renaming, don't let the file name exceeds the `Name` column, but show multiple lines within the set width (this method would be unnatural and hard to deal with when renaming a file in the middle).

Example File Structure:
```
-------Name column------------|----whatever-column----------|
.
├──A folder
├──Random file
├──The file to rename
└──Another random file
```

Example File Renaming UI:

```
-------Name column------------|----whatever-column----------|
.
├──A folder
├──Random file
├──The file to rename (which
|  has a long name like this)
└──Another random file
```

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Improve Renaming UX | Should |

### Files Version

Version: 2.0.33.0

### Windows Version

Windows 10 21H2 (OS Build 19044.1415)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7445
