### ISSUE TITLE
Columns view not working when navigate to folder from file path

### ISSUE THREAD

**Issue by Talisman39ar** [files-community/Files#7329]
### Description

Using the Columns view, if I use a drop-down in the file path to navigate to a folder directly, then the columns aren't refreshed properly, and I can't then double click into folders within the folder I've just picked from the file path.

### Steps To Reproduce

1. Here I've used Columns to navigate to a folder, California Session 2021
<img width="672" alt="image" src="https://user-images.githubusercontent.com/61295915/146793962-58f08e20-0546-46fe-b914-fd43289fbc20.png">

2. Now if I use the file path to pick a different folder from higher up in the hierarchy...
<img width="269" alt="image" src="https://user-images.githubusercontent.com/61295915/146793919-041a2057-4540-42b6-b03e-3c5aa4083c53.png">

3. That folder is then displayed in the middle, while the sub-folder of California Session 2021 is still orphaned on the right. But I can't click into any of the items in the new folder I just selected.
<img width="656" alt="image" src="https://user-images.githubusercontent.com/61295915/146794046-4a9e509f-1f3c-41a2-b97b-73ba0573181f.png">

### Expected behavior

The columns view should refresh so that the folder picked from the file path drop-down is the new starting point for navigation. I should be able to open items from that point.

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.376

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎Sun ‎7/‎25/‎2021 OS build	22000.376 Experience	Windows Feature Experience Pack 1000.22000.376.0

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/61295915/146794879-def08fac-1edb-437f-9819-23a8a93a0b0a.png)

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by Talisman39ar** [comment]
Working as expected now, thanks!
