### ISSUE TITLE
Tab titles don't update when using the "columns" layout

### ISSUE THREAD

**Issue by OscarDL** [files-community/Files#7331]
### Description

When navigating within folders (or even ZIP files), the tab title doesn't update, unlike in "details" layout which works flawlessly.

Live example below using both "columns" and "details" layouts to show the different behaviors.

### Steps To Reproduce

1. Enable "columns" layout by clicking the icon that looks like 3 squares at the top right, then clicking "columns"
2. Go to any folder, and check the tab title, which hasn't changed / updated.
3. Go back, change the layout to the default "details" one
4. Go to any folder, and check the tab title, which this time has changed, and helps tremendously know where our workflow is when using multiple tabs.

### Expected behavior

I expect the tab titles to be updated when using the "columns" layout, just like in the other layouts.

### Files Version

Version: 2.0.42.0 OS Version: 10.0.22000.376

### Windows Version

Windows 11 Pro 21H2 22000.376

### Relevant Assets/Logs

![Example GIF](https://user-images.githubusercontent.com/27915933/146794345-265c9a68-a9a4-452d-a5be-0f917489bec1.gif)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7333
