### ISSUE TITLE
Search file contents...

### ISSUE THREAD

**Issue by trparky** [files-community/Files#7332]
I'd like to see Files (the app) search file contents such as Microsoft Word documents in a particular path. I imagine that it would require tapping into the search system of Windows itself to do this since Windows Search indexes file contents.

**Comment by cinqmilleans** [comment]
It's planned. A research system is under development. It will be possible to search for indexed content.

**Comment by gave92** [comment]
Should be possible already, by typing something like "content:YOURSEARCH"

**Comment by v-dawg** [comment]
It would also be good if it finds music when I search for an artist or a genre

**Comment by Josh-65** [comment]
Merging with #7124
