### ISSUE TITLE
Feature: Add setting to makes delete permanently delete items by default

### ISSUE THREAD

**Issue by Battler624** [files-community/Files#7334]
### Description

Files are undeletable if I turn off "show a confirmation dialogue when deleting files"  but I still get a green checkmark for the operation.

### Steps To Reproduce

Go to recycle bin
click on properties.
turn on "dont move files to recycle bin"
go to files app
turn off the "show a confirmation dialogue" in preferences
try to delete a file

### Expected behavior

File gets deleted

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.376

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎06/‎11/‎2021 OS build	22000.376 Experience	Windows Feature Experience Pack 1000.22000.376.0

### Relevant Assets/Logs

Example of the deletion process on files compared to files explorer
https://youtu.be/cCRKiRlO4HI

The ongoing tasks section with the green checkmark.
https://i.imgur.com/9WbyiEM.png

**Comment by gave92** [comment]
Using Shift+Delete should work for now.

**Comment by Battler624** [comment]
Can confirm

**Comment by gave92** [comment]
Merging with #7492

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7500

**Comment by Battler624** [comment]
Not sure if its right to re-open this but its up to you or I can create a new issue.

While this is fixed, I now get a confirmation to delete even when confirmations are disabled.

https://i.imgur.com/92eqy1j.png

https://i.imgur.com/q1L1R01.png

**Comment by gave92** [comment]
Yeah, behaviour was changed so that if recycle bin is turned off you'll get confirmation. Pressing "Shift+Delete" will never ask confirmation.
This is gonna stay untill we're 110% sure that we detect recycle bin correctly :)

**Comment by Battler624** [comment]
> Yeah, behavior was changed so that if recycle bin is turned off you'll get confirmation, unless you press "Shift+Delete". This is because currently we can't distinguish between a drive where the user disabled the recyclebin from a drive that does not have recyclebin to begin with (e.g removable drives or network drives). I believe Explorer removes confirmation only in the first case.
> 
> Edit: perhaps we get the infp from this key -> HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\BitBucket\Volume

The whole point is that I dont want confirmation when deleting files and I dont need recycle bin, I have no idea why this has to be hard.

**Comment by gave92** [comment]
Cause if you delete a file thinking it's going to the bin but instead it gets permanently deleted without warning you're not gonna be happy.

Guess the simple alternative is to add an option called "always delete files permanently" in addition to the one for displaying confirmation.

@yair100 any thoughts?

**Comment by Battler624** [comment]
I wouldn't mind this at all.

**Comment by yair100** [comment]
> Cause if you delete a file thinking it's going to the bin but instead it gets permanently deleted without warning you're not gonna be happy.
> 
> Guess the simple alternative is to add an option called "always delete files permanently" in addition to the one for displaying confirmation.
> 
> @yair100 any thoughts?

Personally, I use the ctrl + shift + delete shortcut for that, but this can be useful for touch users. I'm hesitant to add something that can cause data loss like this since most users expect items to go to recycle bin.

**Comment by Battler624** [comment]
> > Cause if you delete a file thinking it's going to the bin but instead it gets permanently deleted without warning you're not gonna be happy.
> 
> > 
> 
> > Guess the simple alternative is to add an option called "always delete files permanently" in addition to the one for displaying confirmation.
> 
> > 
> 
> > @yair100 any thoughts?
> 
> 
> 
> Personally, I use the ctrl + shift + delete shortcut for that, but this can be useful for touch users. I'm hesitant to add something that can cause data loss like this since most users expect items to go to recycle bin.

As an option? Do people really fuck up simple stuff like this?

**Comment by Battler624** [comment]
> ![image](https://user-images.githubusercontent.com/39923744/149177669-5bbb30b0-6e15-4839-8c99-c08a471550b2.png)
> 
> I lost count on how many people asked for help after uninstalling Files without turning this setting off.

Then perhaps instead of settings make this only found in the config file?

**Comment by yaichenbaum** [comment]
That sounds reasonable

**Comment by Battler624** [comment]
If you do, can you please update this issue ? Much thanks

**Comment by Josh-65** [comment]
Is this still an issue?

**Comment by hecksmosis** [comment]
I think it's already fixed

**Comment by Battler624** [comment]
I just checked and no its not fixed.

**Comment by yaira2** [comment]
This was implemented in v2.4.33
