### ISSUE TITLE
Unprepared for 

### ISSUE THREAD

**Issue by whitequill** [files-community/Files#7335]
### Description

Files run into a problem that the developer didn't prepare for yet.

### Steps To Reproduce

1. Under Libraries right-click **Documents**
2. Choose **Properties**
3. Left click **Customization**

### Expected behavior

Choose a custom folder Icon dialog opens

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.376

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎12/‎18/‎2021 OS build	22000.376 Experience	Windows Feature Experience Pack 1000.22000.376.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7747666/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7747667/debug_fulltrust.log)

**Comment by gave92** [comment]
Tgabks for the report. This is fixed in latest code.
