### ISSUE TITLE
Can't cut copy and paste

### ISSUE THREAD

**Issue by nhktmdzhg** [files-community/Files#7338]
### Description

I can't paste my file in other folder and I must use File Explore to paste it

### Expected behavior

Can paste file to other folder ?

### Files Version

Version: 2.0.34.0 OS Version: 10.0.19043.1021

### Windows Version

Windows 10 Pro 21H1 19043.1021

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7749015/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7749016/debug_fulltrust.log)

**Comment by jerrywcy** [comment]
Same Question here, quite a weird one because sometimes I can copy from File Explorer and paste in Files, but sometimes I can't.

**Comment by jerrywcy** [comment]
This happens EVERYWHERE, no matter in the cloud or local or libraries or drives. Also, Ctrl+C,Ctrl+V and clicking the Paste button or Copy button simply don't work.

**Comment by jerrywcy** [comment]
What is more weird is that simply drag a file to another folder/tab can work...

**Comment by gave92** [comment]
Merging with #7459
