### ISSUE TITLE
Support for configuring the default sidebar expansion status and folder column name width.

### ISSUE THREAD

**Issue by qinywolf** [files-community/Files#7340]
### What's the Problem?

Support for configuring the default sidebar expansion status and folder column name width.
You need to expand the sidebar manually every time you use it, and it is recommended to record the sidebar status.
The column name interval for the file list often requires manual conditions, and it is recommended to provide a default value instead of creating a desktop.files.json file under each folder to record the values.
Thanks!

### Solution/Idea

Add default expansion configuration for sidebar and default length for folder column names.

### Alternatives

null

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
This issue should be resolved in the preview version. https://files.community/download/preview
