### ISSUE TITLE
Trying to copy file too large for the destination file system mistakenly succeeds

### ISSUE THREAD

**Issue by tatsumara** [files-community/Files#7341]
### Description

Trying to copy a file larger than 4gb onto a FAT32 filesystem doesn't produce an error, but says the operation succeeded, while Explorer correctly errors out.

### Steps To Reproduce

1. Copy a file larger than 4gb
2. Paste it into a FAT32 filesystem

### Expected behavior

There should be an error dialog and it shouldn't claim that the operation worked.

### Files Version

Version: 2.0.42.0 OS Version: 10.0.22000.376

### Windows Version

Windows 11 21H2 22000.376

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7755791/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7755792/debug.log)

**Comment by tatsumara** [comment]
seems this was mentioned already in #4884, my bad

**Comment by gave92** [comment]
PR #8322 adds support for showing an error when copy or move failed for any reason. Using #4884 to track request to show _why_ the operation has failed.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #8322
