### ISSUE TITLE
Question about icons on the menu bar

### ISSUE THREAD

**Issue by Dhyfer1** [files-community/Files#7342]
Hi. I need your help. I want to customize the toolbar of an app to zip/unzip files by replacing its icons with the icons shown in the image. What I want to know is, in which dll or exe file or in which directory could you find the icons in two colors shown in the image?

![0xAeu.png](https://user-images.githubusercontent.com/50301201/146962382-bdd060c2-9b5a-49d9-ae7c-2d42a6ea861c.png)

**Comment by yaichenbaum** [comment]
I'm not sure where File Explorer stores their icons, but we have our own custom font with them https://github.com/files-community/Files/blob/main/src/Files/Assets/Custom%20Glyphs/Colored-Icons.ttf.
