### ISSUE TITLE
Copy and Paste don't work

### ISSUE THREAD

**Issue by jerrywcy** [files-community/Files#7344]
### Description

No matter how hard I tried to copy/paste files in Files, it simply doesn't work. No matter I copy/paste files from a cloud or local directory, no matter I use keyboard shortcuts or click the Copy/Paste button, it JUST DOESN'T WORK.

### Steps To Reproduce

1. Go to a random folder and select a random file
2. Ctrl+C or click the Copy button
3. Go to another random folder and press Ctrl+V or click the Paste button

### Expected behavior

Copy and paste files just as in File Explorer

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.348

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎2021-‎09-‎11 OS build	22000.348 Experience	Windows Feature Experience Pack 1000.22000.348.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7762775/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7762776/debug_fulltrust.log)

**Comment by jerrywcy** [comment]
Note that logs in `debug_fulltrust.log` after 21:00 might be useful because I carried out a copy and paste operation at that particular time, and for logs at other times, I'm not sure what they are recording.

**Comment by Akex13** [comment]
Same problem as you with the last release.

**Comment by gave92** [comment]
Merging with #7459
