### ISSUE TITLE
Right Click Menu does not disapper as it should in certain situation

### ISSUE THREAD

**Issue by JeffersonQin** [files-community/Files#7346]
### Description

1. right click blank area of a folder
2. select "more" in the menu
3. start whatever screenshoting software, in my case, snipaste
4. close the screenshoting software
5. the menu is left there, and will not disappear even if the folder is changed and blank area is clicked.

### Expected behavior

Menu should disappear after clicking blank area.

### Files Version

2.0.34.0

### Windows Version

Windows 10 20H2

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/30655701/147118573-749dce32-084c-43e1-83a5-edd410f0ee2c.png)

**Comment by josh-65** [comment]
This seem to be an issues with WinUI on Windows 10 as I have enounced it also in other apps and windows itself sometimes. its talked about on https://github.com/microsoft/microsoft-ui-xaml/issues/5519. Windows 11 isn't affected.

**Comment by gave92** [comment]
Merging with #6922
