### ISSUE TITLE
Pictures opens behind Files Explorer Window

### ISSUE THREAD

**Issue by islahamine** [files-community/Files#7347]
### Description

Hi ALL,

I Faced This Problem : When Trying To Open a Picture It Opens Behind And I Should Click On It In TaskBar 
I'm Using The Microsoft Store Version .
Thanks In Advance.

### Expected behavior

I Expected The Picture To Be Opened On Top Like The Default Explorer

### Files Version

Version 2.0.34.0

### Windows Version

Windows 21H2 OS Build 19044, 1415

### Relevant Assets/Logs

![Capturee](https://user-images.githubusercontent.com/32944101/147152641-174c95dc-50ce-45aa-9279-4c1a1aa6b33c.PNG)

**Comment by gave92** [comment]
Thanks for the report. Merging with #5291
