### ISSUE TITLE
How can I Replace Old File Exploer With registry Change

### ISSUE THREAD

**Issue by FranklinOP-IND** [files-community/Files#7349]
### Description

![image](https://user-images.githubusercontent.com/64591314/147191828-c5748883-bae8-477b-91ce-3d8e93aad9b7.png)
I unstall File Exploer 2 Then I show this meassge 

how can defulat use old file explorer 

### Expected behavior

![image](https://user-images.githubusercontent.com/64591314/147192084-22285cf5-e67d-45a7-9570-6e028e58aaac.png)
default file explorer change to off but can't off how can i off them ??

### Files Version

Version: 2.0.34.0 OS Version: 10.0.19044.1415

### Windows Version

Windows 10 Pro 21H2 19044.1415

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7766876/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7766877/debug.log)

**Comment by gave92** [comment]
Hi to restore classis Explorer, download [this zip](https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip) and run "UnsetFilesAsDefault.reg".
