### ISSUE TITLE
Add the "Send to" option

### ISSUE THREAD

**Issue by wonderNG** [files-community/Files#7350]
### What's the Problem?

Hello :-) Hope you're fine. I wrote last time caus I couldn't open directly a folder (expect when I'm not in the folder, when I right clik on it) with VSCode or PowerShell7. Now I see that I can open a folder even if I'm already in. If last time I was wrong and did'nt see it, forgive please.
Now, there is a feature that make me use the native Files Explorer( FE) : the **send to option**. You don't put it in the app.

### Solution/Idea

Please insert the send to option. I got a lot to say about how very Amazing is your application. **Seriously, you're doing a GOOOD JOB guys**. If I could ongreats you with money... But I can now. May God Bless you more and give you what you need.

### Alternatives

Redesign if possible the windows that appear on right clik on a document: for example you can put **Edit New Print** in the same line.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |

### Files Version

2.0.34.0

### Windows Version

Windows 11 Dev

### Comments

![Screenshot (3)](https://user-images.githubusercontent.com/82185052/147209842-e74539b3-f755-4522-a7b0-993cc8700b96.png)

**Comment by gave92** [comment]
Hi, what do you use the Send To option the most? For the "compressed folder", the "send to desktop" or other options?

**Comment by wonderNG** [comment]
> Hi, what do you use the Send To option the most? For the "compressed folder", the "send to desktop" or other options?

I oftenly use **Bluetooth Devices**

**Comment by yaichenbaum** [comment]
@wonderNG I think you can do that from the share menu, can you give that a try?

**Comment by wonderNG** [comment]
Here is the result
![image](https://user-images.githubusercontent.com/82185052/147280024-be3bbcaa-eb5b-4947-86ed-5392421171c8.png)

**Comment by josh-65** [comment]
You will need to enable nearby sharing it should show up then. Not sure if nearby sharing also has to be enabled on the other device also

**Comment by Meiryo7743** [comment]
I sometimes use Bluetooth sharing to receive files from my Android device, but Windows' nearby sharing works only between Windows devices. Thus adding the feature the author proposed to the right-click menu would be great at least for me.

**Comment by wonderNG** [comment]
> You will need to enable nearby sharing it should show up then. Not sure if nearby sharing also has to be enabled on the other device also

**Nearby Share** works but between two PC's

**Comment by AndrewLaganaro** [comment]
I support this

**Comment by yaichenbaum** [comment]
@wonderNG can you open a feature request in the Feedback Hub for Microsoft to add a Bluetooth option to the share menu? Please note, we'll keep this issue open for further discussion but ideally this will be resolved by Microsoft adding this option to the share menu.

**Comment by MaxSteven** [comment]
![image](https://user-images.githubusercontent.com/6467223/150175163-1c792384-0475-4141-a77f-5c3520f4a4a7.png)
Hello Can you consider adding the Send to Options?
I usually use it to send the file to some custom batch for render or conversion.

**Comment by wonderNG** [comment]
> @wonderNG can you open a feature request in the Feedback Hub for Microsoft to add a Bluetooth option to the share menu? Please note, we'll keep this issue open for further discussion but ideally this will be resolved by Microsoft adding this option to the share menu.

Then, find an way to put it back. With the Original Explorer I got this option. pls

**Comment by couleurm** [comment]
> ![image](https://user-images.githubusercontent.com/6467223/150175163-1c792384-0475-4141-a77f-5c3520f4a4a7.png) Hello Can you consider adding the Send to Options? I usually use it to send the file to some custom batch for render or conversion.

Hey I also use batchfiles in my Send To folder for FFmpeg stuff, if you don't mind could you tell me what these `zAE_RENDER_BY_DRAG` do? Does it import selected videos into After Effects??

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval. Proberly best to just add it back since Microsoft really dont care about the share menu it seems. Plus theres customisations with the send to menu option.

**Comment by yaichenbaum** [comment]
The main thing that people use this for is Bluetooth, I don't know if Microsoft will add this to the share menu or not, but we don't have plans to add this to Files.

**Comment by Josh-65** [comment]
The new dev insider build for Windows 11 says it added bluetooth sharing to the share window not sure if that will work as other want.

https://blogs.windows.com/windows-insider/2022/07/20/announcing-windows-11-insider-preview-build-25163/#:~:text=Bluetooth%20to%20discover%20nearby%20devices

**Comment by yaichenbaum** [comment]
That was quick 😂

**Comment by vatsdimri** [comment]
> Hi, what do you use the Send To option the most? For the "compressed folder", the "send to desktop" or other options?

I don't know if this feature is being considered or not but I use send-to option to send some books to kindle. 

![Screenshot (139)](https://user-images.githubusercontent.com/61177515/195119074-48fde0d6-8bd6-475d-a01f-a013b09a11f0.png)

**Comment by yaichenbaum** [comment]
@vatsdimri is that something that would work with copy & paste?

**Comment by vatsdimri** [comment]
> @vatsdimri is that something that would work with copy & paste?

I don't think copy & paste would work but I don't know this how this work internally. Send to Kindle option is not there by default, it is added after you download send-to Kindle app. Maybe the app adds itself to the menu.

Other ways of sending to Kindle is by emailing the books to your Kindle account.

**Comment by nerditation** [comment]
the `SendTo` menu is not only about sending files to bluetooth or similar locations, nor can it be replaced with the "share" feature, it's a convenient way to add custom context menu actions without the need to install any third party plugins or extensions. you just need a command that accept file names as command line arguments. you can use any program, you can put it directly, or create a shortcut in the `SendTo` folder. combined with custom scripts, you can do a lot more.

for instance, what I use everyday is to send any file to my text editor or hex editor. I don't need to set up file association or install any shell plugins. this is especially useful for files that have uncommon or wrong suffix, or have no suffix at all.

**Comment by couleurm** [comment]
Gotta agree with nerdidation here, Send To is to me the best way to feed your file paths into your script, you can easily open it from the Run dialog (Windows+R) by typing `shell:sendto` to dump your batch files and shortcuts

**Comment by ElitePheonix2009** [comment]
I will like to customize the context menu using a app, and the app puts the custom context menu items in the send to option. So, pls support the send to option.

**Comment by vvirtues** [comment]
I support this, I use it to send files to preconfigured scripts easily.r
