### ISSUE TITLE
App sometimes scrolls down slightly in any folder

### ISSUE THREAD

**Issue by TechyAditya** [files-community/Files#7351]
### Description

It's in the muscle memory to open the first folder of the G drive that contains all movies. But somehow, the files app slightly scrolls down when I open a folder (especially the downloads folder that has 1000+ files). 

### Steps To Reproduce

1. Open a folder with 100s of files (say downloads folder)
2. Group by Date modified
3. Download some files
4. Close all files instances. Then open the app, and open Downloads folder as soon as it appears

### Expected behaviour

1st folder should be the top-most folder. But the "Today" category gets scrolled up and top-most files will be of "Yesterday". 

### Files Version

2.0.34.0

### Windows Version

Windows 11 Insiders 10.0.22518.1000

### Relevant Assets/Logs

It's UI glitch.

**Comment by yaichenbaum** [comment]
Merging with #6186
