### ISSUE TITLE
Issues With Admin Font Installation

### ISSUE THREAD

**Issue by thierryntoh24** [files-community/Files#7352]
### Description

Unable to grant admin access to install some fonts I've got for all users. Keeps returning 'kernel version' error

### Steps To Reproduce

1. RC on a font face
2. Take install for all users
3. Grant admin permission
4. Error

### Expected behavior

Admin permissions should be granted and the installations proceeds as normal/

### Files Version

Version: 2.0.34.0 OS Version: 10.0.18363.1198

### Windows Version

Windows 10 Pro 1909 18363.1198

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/84026134/147305873-90fcf0fe-5a27-4a57-ac46-3d2b9634479b.png)
![image](https://user-images.githubusercontent.com/84026134/147305913-7118d731-d769-4981-82d1-b91a268623ac.png)

**Comment by gave92** [comment]
Merging with #6731, #7093
