### ISSUE TITLE
Unable to customize a library section

### ISSUE THREAD

**Issue by kaname-png** [files-community/Files#7353]
### Description

When the options of a library category section are opened, the application crashes and closes immediately.

![image](https://user-images.githubusercontent.com/56084970/147317731-452f4638-8984-430c-bba2-ba874dea844d.png)

### Steps To Reproduce

1. Go to libraries
2. Right clic > Properties
3. Click customization

https://user-images.githubusercontent.com/56084970/147319062-f20a103a-2b6d-4756-bda5-1327edff5830.mp4

### Expected behavior

Menu to customize this section of the library.

### Files Version

Versión: 2.0.34.0 OS Version: 10.0.22000.376

### Windows Version

Windows 11 21H2 1000.22000.376.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7772628/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7772629/debug_fulltrust.log)

**Comment by gave92** [comment]
Thanks for the report. This is fixed on main.
