### ISSUE TITLE
Files experimental reg edit won’t disable 

### ISSUE THREAD

**Issue by shehabaldien** [files-community/Files#7354]
I turned the experimental feature for changing the reg edit
But now I can’t turn it off and when i uninstall the app 
I can’t open any folder 
Plz helppppppp

**Comment by yaichenbaum** [comment]
This issue is resolved in `main`. In the meantime you can use this script to revert the changes https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip.

**Comment by MaoshuiI** [comment]
网站失效了，麻烦重新发一个感谢

**Comment by XavierWang3P** [comment]
I tried the method that officially provided, however, it didn't work on Windows 11. So I asked my [friend](https://sspai.com/u/clyde/posts) to send an original copy of `HKEY_CLASSES_ROOT\Folder\shell`, then I can restore the default explorer.

Comparing to default settings, it isn't enough to just delete the `present value` in the `command` folder, also need to add a `DelegateExecute`, which is `{11dbb47c-a525-400b-9e80-a54615a090c0}`

The [bak.txt](https://github.com/files-community/Files/files/7795730/bak.txt) is the copy of default explorer settings from my friend (Need to change the surffix to .reg).

**Comment by Gareth064** [comment]
I was panicking that I had wrecked my PC and would have to do a clean install to fix this.

Thank fully the "UnSetFilesAsDefault.reg" provided by @yair100 above has worked.
