### ISSUE TITLE
List view

### ISSUE THREAD

**Issue by sergiosgAGP** [files-community/Files#7355]
Hi, thanks in advance.

I need a better list view, like the other Windows files.

![image](https://user-images.githubusercontent.com/22889550/147328899-1a506e70-f370-4fe2-9b2d-a4f8b4fed814.png)
![image](https://user-images.githubusercontent.com/22889550/147328938-102f66aa-a4c5-431e-b6fd-62d012ce6362.png)

**Comment by yaichenbaum** [comment]
Merging with #2509.

**Comment by yaira2** [comment]
@sergiosgAGP thank you for your patience, I'm excited to share that a List View layout will be included in the next release.
