### ISSUE TITLE
Chinese character display in context menu

### ISSUE THREAD

**Issue by KingfuChan** [files-community/Files#7356]
### Description

System language is Chinese (simplified). Using Huorong Security software (https://www.huorong.cn/) some entries will be put in the context menu. And sometimes (by this I mean not always) some of them can't be displayed properly. Other programs and Chinese context menu entries are likely to have the same problem randomly. I doubt it is a char encoding issue. Hope to see a fix in future version.

### Steps To Reproduce

Right click on any file or directory, scroll down, and will see the wrong char in the list.

### Expected behavior

A correct display of these Chinese characters

### Files Version

2.0.34.0

### Windows Version

10.0.22000.376

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7773270/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7773272/debug.log)

**Comment by yaichenbaum** [comment]
@KingfuChan can you upload a screenshot?

**Comment by KingfuChan** [comment]
Well I have to wait until next time I see this bug. It's really random and I have no idea if it is Files to blame.

**Comment by yaichenbaum** [comment]
Merging with #7389
