### ISSUE TITLE
Bug: Setting file permissions fails when admin access is required

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#7358]
### Description

I have tested this with an image file in the programs folder on my C drive. File explorer says it required admin whilst files doesn't do anything. Reopening the properties menu, it will remove the permissions I had set/changed.

### Steps To Reproduce

1. Open an admin access only folder (e.g. C:/Users)
2. Open security page
3. Add a user to permission
4. Click ok
5. See nothing happens. Reopening the security page will have the original permissions

### Expected behavior

UAC prompt should be displayed asking for admin access

### Files Version

2.0.43.0

### Windows Version

10.0.19043.1387

### Relevant Assets/Logs

Logs were deleted and didn't show anything when re doing the issues steps.

**Comment by josh-65** [comment]
This seem to apply every ware permissions can be set

**Comment by yaichenbaum** [comment]
Can you fill out the steps to repro?

**Comment by Josh-65** [comment]
Done

**Comment by hecksmosis** [comment]
Isn't this linked to #10422

**Comment by Josh-65** [comment]
This is an issue that was present in the UWP versions before that issue.

**Comment by hecksmosis** [comment]
Oh ok

**Comment by 0x5bfa** [comment]
@Josh65-2201 What do you think about closing this issue since setting permissions is not available at the first place, and problem code has been removed, for now, and that feature is tracked in other feature request issues.

**Comment by Josh65-2201** [comment]
Sure
