### ISSUE TITLE
Dont restore default explorer

### ISSUE THREAD

**Issue by gusgeek** [files-community/Files#7359]
### Description

Files dont return  Windows Explorer to the default App for open dir's on windows.

### Steps To Reproduce

- Set Files Default to Explorer of Windows System
- Restore the setting to default (Windows Explorer)
- Try to open a dir in windows desktop or another directory

### Expected behavior

Windows explorer shows an error after restoring default settings from files

### Files Version

Versión: 2.0.34.0 OS Version: 10.0.22000.376

### Windows Version

11 21h1

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7774704/debug.log)

**Comment by yaichenbaum** [comment]
Merging with #7534
