### ISSUE TITLE
files crash when i select the preferences secction or i delete multiple files

### ISSUE THREAD

**Issue by Turbolol** [files-community/Files#7361]
### Description

so... idk why when i select in the settings the preferences secction or i try to delete multiple files, files crash and send a notificacion saying that the app crashed

### Expected behavior

when i want to config files as my own, the app crashed. later i tried to delete some files at the same time and crashed (again)

### Files Version

Versión: 2.0.34.0 

### Windows Version

Windows 10 21H2 19044.1415

### Relevant Assets/Logs

idk where's the logs :/

**Comment by gave92** [comment]
Hi, you can get the logs from: Files Settings > About > Open log locations (the two ".log" files)
