### ISSUE TITLE
add an option to keep keyboard forcus stay in files pane

### ISSUE THREAD

**Issue by wanderseeme** [files-community/Files#7362]
![Keyboard Focus currently defaults to tabs, which makes people feel clumsy and unhandy](https://user-images.githubusercontent.com/1303078/147375070-16184ab5-3f99-43ae-8e02-ecee89567d44.png)

Keyboard Focus currently defaults to tabs, which makes people feel clumsy and unhandy for fast keybaord navigation

**Comment by yaichenbaum** [comment]
Merging with #2977
