### ISSUE TITLE
Right-clicking in folder empty space causes crash

### ISSUE THREAD

**Issue by Ccaesar** [files-community/Files#7363]
### Description

Greetings,
When I open multiple folders in COLUMN view, right-clicking on the blank block to the right causes the whole program to crash (it could be one right-click or multiple). I think there may be a problem with the implementation of the right margin block in this view.

### Steps To Reproduce

1.switch to the "column" view.
2.open two or more folders.
3.right click the blank block twice or more.
4.then crashed.

### Expected behavior

I dont know what is the expected behavior but not crashed.

### Files Version

Version:2.0.34.0

### Windows Version

Windows 10 Professional 21H1

### Relevant Assets/Logs

![screenshot 2021-12-26 150854](https://user-images.githubusercontent.com/94092181/147401477-7a6b17c4-7aa4-460f-9c93-3188d8e4cda6.png)

**Comment by gave92** [comment]
Not specific to column view:
`2021-12-28 10:46:14.7413|ERROR|AppUnhandledException|Layout cycle detected.  Layout could not complete.
Layout cycle detected.  Layout could not complete.
	Windows.UI.Xaml.LayoutCycleException: Layout cycle detected.  Layout could not complete.
Layout cycle detected.  Layout could not complete.`

**Comment by gave92** [comment]
Merging with #5666
