### ISSUE TITLE
Drag and drop uploading  in google chrome

### ISSUE THREAD

**Issue by dieggono** [files-community/Files#7364]
### What's the Problem?

I'm trying to upload photos from files to google photos in chrome by drag and drop but nothing happens.

### Solution/Idea

I want to be able to upload file in google chorome just by drag and drop the file from de app

### Alternatives

Right now I have to  upload file by selecting them in a pop-up window

### Files Version

Versión: 2.0.34.0 OS Version: 10.0.22000.376

### Comments

Edition	Windows 11 Pro
Version	21H2
Installed on	‎5/‎10/‎2021
OS build	22000.376
Experience	Windows Feature Experience Pack 1000.22000.376.0

**Comment by PetoFeFe** [comment]
Same here
