### ISSUE TITLE
Set files as default file explorer

### ISSUE THREAD

**Issue by jashanpreet11** [files-community/Files#7365]
### Description

hey Files team,
I m here to a problem i  am having with files .Sorry to say, but i want to delete files and remove files as my 'default file explorer' . I want to remove Files as my default file explorer but i go in settings and in experimentel section then when i clickthe option to make it off then a security notification comes to editthe registy i give permission but it donot get off .
thank
![s1](https://user-images.githubusercontent.com/96712911/147437658-d9ad5547-02e0-42f1-a63b-f4de0a9ff5e2.png)
![s2](https://user-images.githubusercontent.com/96712911/147437662-996c4fe3-e79c-4797-8e5d-5e2e05ea0354.png)
![s3](https://user-images.githubusercontent.com/96712911/147437670-1182b3ea-2bfa-48c7-b110-f3d56143ff8d.png)
![s2](https://user-images.githubusercontent.com/96712911/147437677-ee0778f9-57e9-449f-be62-5a6ef81f5d36.png)
![s2](https://user-images.githubusercontent.com/96712911/147437683-4cf68bcc-b0ab-4dcd-80a5-efef8c1251af.png)
s

### Steps To Reproduce

![s1](https://user-images.githubusercontent.com/96712911/147437778-42cc4b4f-af04-4ae7-b5b1-3fe3fee95c33.png)
![s3](https://user-images.githubusercontent.com/96712911/147437780-a66641ca-b690-405b-b4c0-36397bda6188.png)
![s2](https://user-images.githubusercontent.com/96712911/147437782-5dd46688-e71e-45b2-b591-8a7dc84167cd.png)
![s2](https://user-images.githubusercontent.com/96712911/147437783-9a23ad30-6e90-4c7c-b424-065e871e1a25.png)

### Expected behavior

![s1](https://user-images.githubusercontent.com/96712911/147437787-bf36f5b3-7915-4b22-9145-816abad90d23.png)
![s3](https://user-images.githubusercontent.com/96712911/147437789-cb02f4c9-5400-4d29-8cd8-2ae32a9aedd5.png)
![s2](https://user-images.githubusercontent.com/96712911/147437791-e2307942-590d-458e-9e65-bb9f0d98b2a0.png)
![s2](https://user-images.githubusercontent.com/96712911/147437793-4030299b-a924-4dd7-8c52-9fb355050bc0.png)

### Files Version

Version: 2.0.34.0 OS Version: 10.0.19044.1415

### Windows Version

21H2 (10.0.19044.1415)

### Relevant Assets/Logs

i want it solved as soon as posiibale

**Comment by totoro1024** [comment]
After uninstalling, I can’t open the folder anymore

**Comment by duke7553** [comment]
@totoro1024 @jashanpreet11 This issue is resolved in main. In the meantime, you can use this script to revert the changes https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip.
