### ISSUE TITLE
Flash back when opening a picture folder

### ISSUE THREAD

**Issue by Pinghigh** [files-community/Files#7367]
### Description

When i was opening the Picture folder(in library), it kept flashing back

### Steps To Reproduce

1.open Files
2.click the Picture folder
3.flash back

### Expected behavior

normally open the folder

### Files Version

版本: 2.0.34.0 OS Version: 10.0.22000.376

### Windows Version

windows 11 22000.376

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7780239/debug.log)

**Comment by gave92** [comment]
Thanks for the report. This issue is fixed in latest preview version.
