### ISSUE TITLE
Add product version column to details layout

### ISSUE THREAD

**Issue by paulocampoy** [files-community/Files#7368]
### What's the Problem?

I didn't found a way to add new columns on Files. I always use a column with info about version of app or documents. May you help me?
<img width="458" alt="2021-12-27 11_50_13-C_" src="https://user-images.githubusercontent.com/38701792/147483089-860bb7c8-e0cf-42c9-abe9-0978c44a6359.png">

### Solution/Idea

Create a way to add or remove columns from Files with infos like version of files.
<img width="458" alt="2021-12-27 11_50_13-C_" src="https://user-images.githubusercontent.com/38701792/147483078-d636fe66-a227-4add-af4f-af89a5ada474.png">

### Alternatives

Didn't found any alternative...

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Windows Version

Windows 10 - 21H1

**Comment by yaichenbaum** [comment]
Merging with #8366
