### ISSUE TITLE
Experimental Option Default File Explorer

### ISSUE THREAD

**Issue by BillCC95531** [files-community/Files#7369]
### Description

Files will not allow me to revert back to File Explorer as the default.  When I click the toggle switch in the experimental settings section to off, I get the windows message asking me if I want to allow the files program to make changes to the system, I click yes and then the files app turns the toggle switch back to the on position.

### Steps To Reproduce

Won't let me reproduce.

### Expected behavior

To restore the Windows File Explorer as the default. 

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.376

### Windows Version

Edition	Windows 11 Home Version	21H2 Installed on	‎9/‎5/‎2021 OS build	22000.376 Experience	Windows Feature Experience Pack 1000.22000.376.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7781072/debug.log)

**Comment by gave92** [comment]
Hi, this issue is resolved in main. In the meantime, you can use this script to revert the changes https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip.

**Comment by BillCC95531** [comment]
Thank you.  I ran the script and it successfully restored explorer to the
default.

**Comment by GlassySundew** [comment]
> Hi, this issue is resolved in main. In the meantime, you can use [this script](https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip) ("UnsetFilesAsDefault.reg") to revert the changes.

Hello, after restoring back to default windows explorer it now creates a new window with a startup page instead of opening a folder when i try to open a folder

**Comment by GlassySundew** [comment]
oh i have just found a thread at https://github.com/files-community/Files/issues/7626, so it fixed it
