### ISSUE TITLE
Missing Dropbox context menu in Files right click

### ISSUE THREAD

**Issue by v-aravind** [files-community/Files#7370]
### What's the Problem?

The context menu (right click) on files and folders in Dropbox folders does not include the context menu items specific to Dropbox, which appear in the standard windows Explorer context menu. The context menu items that appear in Windows Explorer are in the image below. These are missing from the context menu in the Files app.
![image](https://user-images.githubusercontent.com/69113302/147503918-1dd293c8-44b2-4dce-8b81-69ae4bea34db.png)

### Solution/Idea

Enable integration of the Dropbox context menu items into the context menu in Files.

### Alternatives

Only alternative is to use Explorer, not Files, for any Dropbox folders.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.376

### Windows Version

Windows 11 Enterprise

**Comment by gave92** [comment]
Could you post a screenshot of Files context menu for a Dropbox file?

**Comment by emkelley** [comment]
The Dropbox options can be found by clicking "More" at the bottom of the right click menu:

![image](https://user-images.githubusercontent.com/11874169/147962834-e81266da-827c-4b20-be39-e7296ee08f6a.png)
