### ISSUE TITLE
Folder icon for Dropbox Business is incorrect

### ISSUE THREAD

**Issue by v-aravind** [files-community/Files#7371]
### Description

The folder icon for Business Dropbox is not showing correctly - it shows the generic yellow folder icon instead of the dropbox icon
![image](https://user-images.githubusercontent.com/69113302/147504238-41c05565-923a-4302-88e1-1b505a4eba8f.png)

### Expected behavior

The correct icon for dropbox should appear - this happens for personal Dropbox acounts but not for Business Dropbox accounts

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.376

### Windows Version

Windows 11 Enterprise

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/69113302/147504286-d7d3ac81-78f9-45c0-9c05-523a0e45f3f4.png)

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?
