### ISSUE TITLE
crash bug

### ISSUE THREAD

**Issue by njliligan** [files-community/Files#7372]
### Description

When I clicked the pictrues ，the application is crash。

### Steps To Reproduce

1,in the setting choose "SideBar".
2,open "Show library section".
3,click the Pictrues in "library section".

### Expected behavior

The apllication will crash

### Files Version

版本: 2.0.34.0 OS Version: 10.0.22000.376

### Windows Version

Windows 11 21H2 22000.376

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7782243/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7782242/debug.log)

**Comment by gave92** [comment]
Thanks for the report. This issue is fixed in latest preview version.
