### ISSUE TITLE
Regain the UX/UI of the properties window in #6691

### ISSUE THREAD

**Issue by onein528** [files-community/Files#7377]
### Description

The property window UI prior to #6691 is more similar to the properties window in Windows File Explorer and is more familiar to users, making it easier to acquire UX.

![image](https://user-images.githubusercontent.com/62196528/147593951-d919e181-623a-4dc1-ac26-59356be60f18.png)

Property windows, such as folders, have completely different content for each section and are terribly confusing to display in the same view.

### Expected behavior

Revert changes in properties.xaml in #6691.

### Files Version

Version: 2.0.42.0 OS Version: 10.0.22523.1000

### Windows Version

Windows 11 21H1 22523.1000 (the last pre version of 2021)

### Relevant Assets/Logs

None

**Comment by yaichenbaum** [comment]
The properties dialog is in middle of undergoing a refresh and the tab design was temporarily removed as we get ready to implement the changes.

**Comment by yaichenbaum** [comment]
@onein528 I should clarify, the navigation view isn't being removed. I think you'll like the new design once it's fully implemented.

**Comment by onein528** [comment]
That's interesting!!

**Comment by yaichenbaum** [comment]
Feel free to follow the progress in the PR I opened a couple of minutes ago #7378
