### ISSUE TITLE
Default to pasting in right most column

### ISSUE THREAD

**Issue by Talisman39ar** [files-community/Files#7379]
### What's the Problem?

When in columns view, if I go to paste a file from another folder, it's unclear how to tell Files which column I want to paste into. Generally I'd want to paste into the right-most column (IMO), but Files seems to use the next-to-last column as the focus.

I have to right click in the desired column and use the Paste in the drop-down to force it to paste in the column I want.

In this screenshot, the image with the red asterisk next to it is what I pasted using ctrl-V. I would have expected it to go in the right-most column as that's what was most recently opened, and it also is shown as the focused folder with the yellow line next to its folder name in the middle column.

<img width="688" alt="image" src="https://user-images.githubusercontent.com/61295915/147622054-f10c2e27-a856-41f5-9867-3bca8ef4f989.png">

### Solution/Idea

I'm inclined to say that the right-most column should be the default. This is how Mac OS handles it, and I never had confusion when using that :) See this video starting at the 3:52 mark https://www.youtube.com/watch?v=68tuXHdJWvc

### Alternatives

Maybe there's a way to indicate visually which column has focus for Paste purposes, or to let the user signify which they want to use before the paste happens

### Priorities

| This proposal will allow end users to accomplish less confusing pasting of files in columns view | Should |

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.376

### Windows Version

Windows 11 Pro Version	21H2   OS build	22000.376 Experience	Windows Feature Experience Pack 1000.22000.376.0

**Comment by sergiubacioiu** [comment]
I have the same issue. It's not just copy and paste, the new button in the upper left corner does the same thig. I think the focus should be on the right column when it's opened.
A good implementation of this feature in my opinion would be like this:
- make the active column for actions the right most column by default
- change the background color slightly of the active column
- if you explicitly click on another column you can make that column active so the actions can be performed there but by changing the background color the active column is always known beforehand

**Comment by yaira2** [comment]
@Talisman39ar thank you for your feedback, we've made a number of improvements in this area, and it looks like this was fixed. Can you try the latest preview build and confirm if this is resolved? https://files.community/download
