### ISSUE TITLE
Layout picker menu only allows clicking on the view icons

### ISSUE THREAD

**Issue by Talisman39ar** [files-community/Files#7380]
### What's the Problem?

The layout picker only allows clicking on the view icons. Clicking on the name of the view (Details, Columns, etc.) doesn't do anything.

### Solution/Idea

I would expect both the icon and the associated name to be treated as a single button, so clicking anywhere in there switches the view. (Nice that you have the tooltips with the keyboard shortcuts in there BTW!)

![image](https://user-images.githubusercontent.com/61295915/147623863-f78a80f5-a0da-4ad9-81f6-af3534eed58e.png)

### Alternatives

None

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W |  |
| This proposal will allow end users to accomplish easier switching of views | **Should** |
| This proposal will allow developers to accomplish Y |  |
| This proposal will allow end users to accomplish Z |  |

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.376

### Windows Version

Windows 11 Pro Version	21H2 OS build	22000.376

**Comment by yaichenbaum** [comment]
This will be resolved in the next update.
