### ISSUE TITLE
the icon looks not clear

### ISSUE THREAD

**Issue by sdnvm** [files-community/Files#7382]
### Description

![image](https://user-images.githubusercontent.com/96822193/147654809-953c75be-8bfa-477d-bcc6-a67ed439391e.png)
the icon looks not clear

### Expected behavior

🐱

### Files Version

版本: 2.0.34.0 OS Version: 10.0.22000.376

### Windows Version

Windows 11 21H2 22000.376

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7788486/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7788490/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
@sdnvm are they clearer in a smaller layout?
