### ISSUE TITLE
Smaller/Adjustable Item Spacing

### ISSUE THREAD

**Issue by knuxyl** [files-community/Files#7383]
### What's the Problem?

Files cannot display as many items either in the sidebar or in the main window as Windows Explorer. It makes it hard to scan through due to the big spacing between each item. I believe the issue is more about the spacing between the items than the font size of the text.

### Solution/Idea

An option to adjust the size would be great, or just have the spacing smaller in general.

### Alternatives

Using Windows Explorer as opposed to Files.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish seamless transition from Windows Explorer to Files for the end users. | Must |

### Files Version

v2.0.34

### Windows Version

Windows 10 21h2

**Comment by gave92** [comment]
Merging with #1940
