### ISSUE TITLE
Allow Enable/Disable "Open files/folders with a single click" to also work on items in the Home page.

### ISSUE THREAD

**Issue by knuxyl** [files-community/Files#7384]
### What's the Problem?

The persistent single click to open an item on the Home page is inconsistent with the rest of the file explorer when "Open files/folders with a single click" is disabled in settings.

### Solution/Idea

Allow double click to open items in the Home page, but also adhering to the setting "Open files/folders with a single click".

### Alternatives

Have the Home page not behave as an entirely different element than the rest of the file explorer. Have it act just like a folder with shortcuts, so that there is consistently with appearance and behavior with the rest of the UI.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish consistency of UI settings for the Home page. | Must |

### Files Version

v2.0.34

### Windows Version

Windows 10 21h2

**Comment by gave92** [comment]
Merging with #6074
