### ISSUE TITLE
Reduce minimum size for the sidebar

### ISSUE THREAD

**Issue by knuxyl** [files-community/Files#7385]
### Description

The sidebar seems to have a minimum width which takes up too much space. I cannot seem to resize it past a certain point, even though all the items in the sidebar will not be hidden. This could be a feature request, but I believe it to be a bug due to the ability to resize it.

### Steps To Reproduce

Try to resize the sidebar to hide all unused space.

### Expected behavior

Be able to resize sidebar all the way to the left without it creating a tiny button based bar.

### Files Version

v2.0.34

### Windows Version

Windows 10 21h2

### Relevant Assets/Logs

![2 0 34](https://user-images.githubusercontent.com/19507326/147661196-5ea0ceef-835a-48d9-b9dc-26fa87a28e3a.jpg)

**Comment by yaichenbaum** [comment]
Fyi @winston-de

**Comment by winston-de** [comment]
This behavior is intentional, it's so that the user can collapse and expand the sidebar by resizing it. However, the minimum size to collapse can be adjusted.

**Comment by yaichenbaum** [comment]
@winston-de Should we reduce the minimum size?

**Comment by winston-de** [comment]
yeah I think so

**Comment by Tarek-Hasan** [comment]
Current sidebar occupy too much space. It would be nice to resize the sidebar and have the blank space for file/folders.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7725
