### ISSUE TITLE
Bad column sizes in the new property popup

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#7386]
### Description

In the disk size part of the properties, the column sizes are suitable for English, but not for other languages. The texts can be too long.

### Steps To Reproduce

1. Use Files after commit #7378.
2. In settings, choose the language French.
3. In Home (Accueil in French), open the properties panel of a drive.
4. Look Général/more details

### Expected behavior

The texts should be readable, or at least cut cleanly. 

### Files Version

Commit #7378

### Windows Version

Windows 11

### Relevant Assets/Logs

![properties](https://user-images.githubusercontent.com/46631671/147682543-f371a820-fad5-4703-8ec8-250ef6517bf0.png)

**Comment by yaichenbaum** [comment]
@cinqmilleans They aren't wrapping?

**Comment by yaichenbaum** [comment]
@cinqmilleans this issue should be resolved with #7388
