### ISSUE TITLE
USB Key - Properties Window

### ISSUE THREAD

**Issue by CyrilCharlier** [files-community/Files#7392]
Hello,

Files version 2.0.34.0

When i want to go to "Properties" in the right click menu on a USB Key, the window is a bit empty : 
<img width="533" alt="image" src="https://user-images.githubusercontent.com/11455745/147809748-67f9f6b9-5157-4a88-a1c3-aaac0f849dbc.png">

Thanks

**Comment by onein528** [comment]
Describe the details of the system you are using.

This happens if your system theme is light windows 11 and you have specified Files as a dark theme.

**Comment by CyrilCharlier** [comment]
Hi thanks for the reply,

You are right, i'm on Win 11 with light theme and darh theme with Files ;)

i will turn off dark theme as an alternate for this issue.

thanks :)

**Comment by onein528** [comment]
@CyrilCharlier you need to mark this issue as closed

**Comment by CyrilCharlier** [comment]
oh sorry i thought you should keep open to link this issue to fixing the issue.
I close immediately.

Thanks again

**Comment by onein528** [comment]
It seems technically impossible for Files to fix this.

UWP doesn't have the API to specify a theme that applies only to apps with Mica material.
