### ISSUE TITLE
Fonts can't install for all users

### ISSUE THREAD

**Issue by Pinghigh** [files-community/Files#7393]
### Description

当我点击右键，为所有用户安装一些字体时，显示“FileAllTrust.exe”的UAC然后出现“内核信息无效”的提示，最后没成功

When I right-click to install some fonts for all users, the UAC of "filealltrust. Exe" will be displayed, and then the prompt of "invalid kernel information" will appear. Finally, it failed

*使用翻译软件，可能语言有疏漏*

*There may be language omission when using translation software*

### Steps To Reproduce

1.选中一些字体
1.Select some fonts
2.右键，选择为所有用户安装
2.Right click and select install for all users
3.弹出UAC，点确定
3.Pop up UAC and click OK
4.弹出“提供的内核信息版本无效”的提示
4.The prompt "the kernel information version provided is invalid" pops up
5.字体没成功安装
5.The font was not installed successfully
*使用翻译软件，可能语言有疏漏*
*There may be language omission when using translation software*

### Expected behavior

install the fonts for all users successfully

### Files Version

版本: 2.0.34.0 OS Version: 10.0.22000.376

### Windows Version

22000.376

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7795645/debug.log)

**Comment by gave92** [comment]
Merging with #7093
