### ISSUE TITLE
Add support customizing items in the folder widget on the home page

### ISSUE THREAD

**Issue by AndrewLaganaro** [files-community/Files#7395]
### What's the Problem?

Hello guys! I like Files so much but i have a problem, **I have several Libraries** that I've made on windows, Libraries are different than folders, because **they group multiple folders** (perhaps even in different HD or SSD drives) into only one folder.

So, I have three storage drives, and I have a library for Development, Electronics projects, Design, Music, Books and so on. Each of them feature folders in different drives due to drive size issues or even folder size issue (wouldn't fit in one drive, so I move it to another without losing access to its usual icon)

So I've been missing that I lot, I use windows 10 and I still use the solution given for windows 7, which you can choose the windows "URL" to the global Libraries folder (that shows ALL of your libraries in one place) to show up as a start page on windows explorer. **I can't do that on Files**, unfortunately.

**This "URL" is that one:**

`**%WinDir%\explorer.exe /e,::{031E4825-7B94-4dc3-B131-E946B44C8DD5}**`

If you make a **shortcut** with the "**Destination**" filled with it, it will show you the **Libraries section**/folder on your windows (prior to Windows 7, works on 10 and 11 too)
![image](https://user-images.githubusercontent.com/45211616/147841388-3ff0c2a2-d553-4290-aa81-7a33c57f04e3.png)
_**("Libraries" shortcut proprieties on windows 10, "Destino" = "Destination" to execute)**_
### Solution/Idea

My suggestion is to **_make the home page editable_** in a way that you can link **_instead of the default user folders_**, optionally you can **_put a library link to the library you want_**

I've made a rough mock-up of what it would sounds like to the eye, see:
![image](https://user-images.githubusercontent.com/45211616/147841227-d8a4adf6-0e81-4d6e-8255-43549330b691.png)

So, as you can see I've edited the image with the windows libraries that I'd want on top of the default folders just to look at it and **have a glimpse of what it'd be**.

My system is in portuguese, so my libraries are listed as follows: **Courses** (web courses, programming etc), **Development** (programming, coding folders), **Torrents**, **Music**, **Electronics** (projects, circuits etc), Books (pdf, ebooks)

So, finally. This is what I'd want to come true. Hope that's possible, because y'know, _**in windows this existis**_ :
![image](https://user-images.githubusercontent.com/45211616/147841255-fc337506-395d-4e2a-a5fd-8de344694feb.png)
**This is my regular libraries section on windows explorer**, so I think it is not an impossible change (made optional, of course).

As the mock-up shows, the idea would be joining the "My computer" folder with the "Libraries" folder, **showing drives** (Disk C:, disk B:, disk D: etc) **along with libraries** selected by the user at the top, again, like this:
![image](https://user-images.githubusercontent.com/45211616/147841274-86c09e66-3c46-455c-838b-34b9db2bb8db.png)
Comparing to **what we have now**, only the default user folders:
![image](https://user-images.githubusercontent.com/45211616/147841277-4d622636-315b-466f-9b77-7475d3375de2.png)
Could even be **mixed up**, the first three folders are the default folders for: **Desktop, Documents and Downloads**, along with the next three which are the libraries made by the user: **Music, Electronics, Books**
![image](https://user-images.githubusercontent.com/45211616/147841290-03f9c6f0-9a8d-4409-8d5a-4e6ae1389861.png)

**So, that's my suggestion. I think it would be a real game changer for the Files app!**

Thanks and happy new year for those reading in 31/12/2021. bye

### Alternatives

I didn't find any

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish **Better customization** | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

Really sorry, I didn't get this table quite right....

### Files Version

Versão: 2.0.34.0

### Windows Version

Version: 10.0.19043.1348

### Comments

No extra comments.

**Comment by yaichenbaum** [comment]
@AndrewLaganaro thank you for your feedback, we're tracking a similar request in #6596.
