### ISSUE TITLE
Always open folder with one click in column view

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#7397]
### What's the Problem?

In Column View, folders do not open in a new page. Not displaying the contents of a selected folder is irrelevant. 

### Solution/Idea

Always open folder with one click in column view.

### Alternatives

None.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Last commit

**Comment by Talisman39ar** [comment]
Same as #6490 and part of #5375 I believe
