### ISSUE TITLE
Files crashing upon opening the Images and Video folders from the library section in the sidebar menu

### ISSUE THREAD

**Issue by DustyOldRowe** [files-community/Files#7398]
### Description

I dowloaded Files today and I use the library section in the sidebar very often, but when I open the Images and Videos folder from there de app crashes out of nowere, but when I access from the main page, the one you when you startup the app, it works, wich is very weird

### Steps To Reproduce

1. Open Files
2. Go to the sidebar menus
3. Make sure that the library cestion is active
4. Click in the Images or Video folders
5. There the app crashes for me

### Expected behavior

The folders should open like normal, it shouldn't make a difference from where you try to open the folder

### Files Version

Versão: 2.0.34.0 OS Version: 10.0.22000.376

### Windows Version

Windows 11 Pro 21H2

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7798183/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7798184/debug.log)

**Comment by gave92** [comment]
Thanks for the report. This is fixed on the preview version.
