### ISSUE TITLE
have Nextcloud folder appear in Cloud Disk

### ISSUE THREAD

**Issue by Tonic8** [files-community/Files#7400]
### What's the Problem?

Hello

i'm using Nextcloud https://nextcloud.com/ as my cloud file storage, but it seems that it is not recognize as so by Files :) .

### Solution/Idea

Have file integrate Nextcloud as a cloud file service.

### Alternatives

use Windows Explorer in the samtime

### Priorities

this will allow Nextcloud user to have Files as the definitive tool for file manager :)

### Files Version

Version : 2.0.34.0 OS Version: 10.0.19042.1415

### Windows Version

Windows 10 20H2 19042.1415

**Comment by gave92** [comment]
Merging with #4420
