### ISSUE TITLE
Add skin forms support

### ISSUE THREAD

**Issue by dinrise** [files-community/Files#7403]
### What's the Problem?

Sorry for my English. I very like Apple Finder design, but windows give me more features. Some peoples like gnome, kde designs.

### Solution/Idea

Add any ways to customize xaml forms for create new awesome designs.

### Alternatives

no ideas

**Comment by yaichenbaum** [comment]
Please refer to the documentation on creating custom themes https://files.community/docs/configuring/custom-themes.

**Comment by dinrise** [comment]
@yair100 but why? Your link, it's for color schemes. But my idea, for fully customization.

**Comment by yaichenbaum** [comment]
@dinrise are you interested in changing the location of controls or just the styles? To change the location of controls you'll need to fork the app and modify the xaml.

**Comment by dinrise** [comment]
@yair100 i know, but my VS2022 crashes when trying to open designer( I don't know why.. Only with Files project

**Comment by yaichenbaum** [comment]
@dinrise there have been some issues with the designer crashing with WinUI so in the meantime you might want to disable it. Have you tried debugging the solution and using hot reload to visualize changes?

**Comment by dinrise** [comment]
@yair100 yes, but not effected

**Comment by yaichenbaum** [comment]
Depending on what you change you'll sometimes have to redeploy the solution.

**Comment by dinrise** [comment]
@yair100 i try to do something like that [https://i.imgur.com/uzcSRuL.png](https://i.imgur.com/uzcSRuL.png)

**Comment by yaichenbaum** [comment]
That's going to require moving a number of controls around on the different pages and you'll likely have to redeploy after modifying the different files.

**Comment by dinrise** [comment]
@yair100 thanks, will try tomorrow. Oh, and happy new year)

**Comment by dinrise** [comment]
@yaichenbaum sorry, but i cant do that( Can you help me? [https://i.imgur.com/LbRjxn9.png](https://i.imgur.com/LbRjxn9.png)

I'm only frontend developer.. And dont know xaml(

**Comment by dinrise** [comment]
@yair100 can you create new branch for my project? [https://github.com/dinrise/Files/tree/iFiler](https://github.com/dinrise/Files/tree/iFiler)

**Comment by yaichenbaum** [comment]
@dinrise we don't have plans to incorporate alternative designs into the main repo.
