### ISSUE TITLE
[Question]How did you undock the TabView?

### ISSUE THREAD

**Issue by onein528** [files-community/Files#7404]
**Abstract**
I can't force Corner Radius for TabViewItem.
What code did you use to undock the TabViewItem?
Please help me......

**Screenshots**
I am currently creating an app with multi-tabs enabled:
![image](https://user-images.githubusercontent.com/62196528/147881392-b74f384c-dc10-4c85-8a28-6751a5b8b8df.png)

I imported these files(thx for those resources) but it didn't happen:

- [TabViewItem_shared.xaml](https://github.com/files-community/Files/blob/main/src/Files/ResourceDictionaries/TabViewItem_shared.xaml)
- [TabView_themeresources.xaml](https://github.com/files-community/Files/blob/main/src/Files/ResourceDictionaries/TabView_themeresources.xaml)

https://github.com/microsoft/microsoft-ui-xaml/issues/3084
I read this but I cant find solution to this problem.

**Comment by yaichenbaum** [comment]
@duke7553 do you remember what you had to change for this to work?

**Comment by duke7553** [comment]
@onein528 You should be able to use those resources by referencing them like this under your control's resources: 
```xml
<ResourceDictionary>
     <ResourceDictionary.MergedDictionaries>
         <ResourceDictionary Source="/YourFolderName/TabView_themeresources.xaml" />
         <ResourceDictionary Source="/YourFolderName/TabViewItem_shared.xaml" />
     </ResourceDictionary.MergedDictionaries>
</ResourceDictionary>
```

**Comment by duke7553** [comment]
@onein528 Closing this since it's not directly related to the development of Files.

**Comment by onein528** [comment]
I will see PR of tab view updating...

**Comment by onein528** [comment]
Finally, I did!!! Thank you two!!

![image](https://user-images.githubusercontent.com/62196528/148668373-f4b26d6f-6bb0-4657-a1c4-7d00426e6913.png)

**Comment by yaichenbaum** [comment]
@onein528 what are you working on?

**Comment by onein528** [comment]
I am working on [GitHub deskto UWP client](https://github.com/onein528/FluentHub) and am developing to learn C # and MVVM patterns(so this is very bad:).
In the future, I want to make the frame transition when I enter the URL of GitHub.
I'm sorry that the UI of Files is similar.

![image](https://user-images.githubusercontent.com/62196528/148668628-3a102e46-379a-4fa7-8ed3-a2eb1ccee826.png)
![image](https://user-images.githubusercontent.com/62196528/148668638-8898140b-cf29-4deb-b51e-ce07e015b1fb.png)

**Comment by yaichenbaum** [comment]
> I'm sorry that the UI of Files is similar(just learning ;) ).

@onein528 having a familiar UI between apps is great and I consider the fact you choose Files a compliment. Do you have a GitHub repository where I can follow the progress?

**Comment by onein528** [comment]
The quality of the code is terribly bad, but thank you for starring my repo😭

**Comment by onein528** [comment]
@yaichenbaum I invited you to FluentHub. If you can follow the progress :)
