### ISSUE TITLE
Drag from a file in a zipped folder

### ISSUE THREAD

**Issue by frfidecaro** [files-community/Files#7407]
### Description

I had a zip folder with three files. I tried to drag multiple compressed files onto the parent folder in the path bar. I had the popup saying that the file would be copied in that location but Files told me of an error not foreseen by developers and sent me here.
Thank you

### Steps To Reproduce

In a compressed folder
drag more than one file to some location in the address bar

### Expected behavior

File regularly copied to upper folder

### Files Version

Versione 2.0.34.0 OS Version: 10.0.22000.376

### Windows Version

Windows 11 PRO 21H2 22000.376

### Relevant Assets/Logs

No way to copy something..

**Comment by gave92** [comment]
Thanks for the report. Please upload Files debug logs, you can find them from Files Settings > About > Open log location (debug.log + debug_fulltrust.log)

**Comment by frfidecaro** [comment]
Thanks for the prompt reaction.
Sincere apologies, I had a lot of trouble with Windows 11 Explorer and among other things I uninstalled Files so data was deleted. I reinstalled Files now and this operation worked. Files Version is still 2.0.34.0, OS Version: 10.0.22000.376.

**Comment by gave92** [comment]
Thanks, closing this for now. Please let us know if it happens again.
