### ISSUE TITLE
Set default folder layout/view across all system

### ISSUE THREAD

**Issue by AndrewLaganaro** [files-community/Files#7409]
### What's the Problem?

Hi. In every folder I come across I have to change it's layout from "details" to "blocks", which is the one that I use the most

(I've tried to look on the issues if there was some similar to it, but I could find it. I've searched some terms but got no luck.)

This happens on every drive, every folder, in any location. **I have to change the layout as I come across with each folder**, and I think this is kinda of annoying. There should be an global option to set a global layout/view to our folders, right?

### Solution/Idea

**A global option to set a global layout/view to our folders across all the system and all the drives.**

### Alternatives

Re-set each and every folder, one by one, until the end of time.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to accomplish **Better customization** | Should |

### Files Version

Files: 2.0.34.0

### Windows Version

Windows 10: 10.0.19043.1348

**Comment by yaichenbaum** [comment]
Merging with #4155
