### ISSUE TITLE
Unselecting group option doesn't default to none

### ISSUE THREAD

**Issue by aayushyap89** [files-community/Files#7412]
### Description

This is a part of a second bug, I couldnt see all the files in my downloads folder and I was told to unselect the group by date modified option. I clicked on it and it removed the checkmark but it didnt select none and didnt nothing. I then selected group by none and then download files showed.

### Steps To Reproduce

1. select group by date
2. select group by date to unselect but it wont default to none.

1. click downloads and files wont be there.

### Expected behavior

1. To default to none when unselecting a option, in this case group by date.
2. To show files in download.

### Files Version

2.0.43.0

### Windows Version

Windows 11 21H1 22000.376

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7799821/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7799822/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7423
