### ISSUE TITLE
issue  with  set back file explorer as  a default

### ISSUE THREAD

**Issue by mrkamalali** [files-community/Files#7413]
i  can not go  back  to  set  (file explorer) as a default  file explorer after  make  " Files" as  a default

**Comment by gave92** [comment]
Hi, this issue is resolved in main. In the meantime, you can use [this script](https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip) ("UnsetFilesAsDefault.reg") to revert the changes.
