### ISSUE TITLE
Still not getting Status column in some places...

### ISSUE THREAD

**Issue by brucebinder** [files-community/Files#7424]
### Description

If I got to this level, the status shows. When iigot to next level, status stops showing.

C:\Users\bruce\OneDrive\Documents\Lakshmi\—shows status
C:\Users\bruce\OneDrive\Documents\Lakshmi\Chair Yoga—stops showing status.

### Steps To Reproduce

go to C:\Users\bruce\OneDrive\Documents\Lakshmi\Chair Yoga

### Expected behavior

Show status everywhere.

### Files Version

2.0.44.0

### Windows Version

21H2 (22000.376)

### Relevant Assets/Logs

No logs to show

**Comment by gave92** [comment]
Still merging with #6227 :)
