### ISSUE TITLE
Files not appearing.

### ISSUE THREAD

**Issue by Saelman** [files-community/Files#7426]
### Description

Hi guys! So I so far love files as it just feels a bit more fancy but i noticed that files that i download arnt showing up in files. I'll install something off opera, for example i install notepad++ and checked files to run the installer but my downloads file was WAY behind. files i downloaded like a week ago were the last things it was showing. I had downloaded several images and such that arnt appearing withing the downloads location on Files. they do appear within windows file explorer. Not sure if theres some settings i may have messed with that are causing this, or if this is a known bug with the software. I tried finding the file via, Date created and other sorting methods but nothin. I can search it and it sees its in the downloads file but it doesnt appear when im just browsing the file.

### Steps To Reproduce

Seems to just happen.

### Expected behavior

I'd be able to view newly downloaded files.

### Files Version

Files v 2.0.34.0

### Windows Version

Windows 11 PRO Version 10.0.22000  

### Relevant Assets/Logs

![Screenshot 2022-01-03 155029](https://user-images.githubusercontent.com/24628383/147978976-afceb4d4-5a9c-430f-8325-8841a20800f4.png)

**Comment by Saelman** [comment]
The screenshot listed is showing the newest* file shown, there should be roughly 10 to 15 more items newer than this. including the file for notepad++ as i noted above.

**Comment by gave92** [comment]
Hi, thanks for the report. You might want to try the [preview version](https://filescommunity.blob.core.windows.net/files/preview/Files.Package_2.0.45.0_Test/Files.Package_2.0.45.0_x86_x64_arm64.msixbundle) as there have been a couple of fixes in this area.
