### ISSUE TITLE
Still cannot see Status when I drill down too far...

### ISSUE THREAD

**Issue by brucebinder** [files-community/Files#7427]
### Description

When I go to  certain level of folders I stop seeing the status column.

C:\Users\bruce\OneDrive\Documents\Lakshmi\Chair Yoga does no show

C:\Users\bruce\OneDrive\Documents\Lakshmi\ shows

### Steps To Reproduce

I  go to C:\Users\bruce\OneDrive\Documents\Lakshmi\Chair Yoga and stop seeing status column

### Expected behavior

Expect to see the status column

### Files Version

2.0.45.0

### Windows Version

21h2 22000.376

### Relevant Assets/Logs

No logs

**Comment by yaichenbaum** [comment]
Do you see it if you scroll horizontally?

**Comment by gave92** [comment]
Still merging with #6227
