### ISSUE TITLE
Box (cloud provider) doesn't display files and constantly reloads

### ISSUE THREAD

**Issue by SullieLore** [files-community/Files#7428]
### Description

Hi. The cloud app from Box works fine in explorer, but constantly reloads in Files and doesn't display any files/folders, besides the high level (C:\Users\user\Box).

### Steps To Reproduce

1. Install Box software (box.com).
2. Run software.
3. Restart.
4. Open Files and check the Box software under cloud provider.

### Expected behavior

Not to reload constantly. Show all files in Box like Windows explorer does.

### Files Version

Version: 2.0.44.0 OS Version: 10.0.22000.376

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎30/‎07/‎2021 OS build	22000.376 Experience	Windows Feature Experience Pack 1000.22000.376.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7804414/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7804415/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #8808
