### ISSUE TITLE
Add an option to provide Admin Rights to open files that need it.

### ISSUE THREAD

**Issue by Wizards-god** [files-community/Files#7430]
### What's the Problem?

Many files need administrator rights to open/view. I am not able to view/open these files from the Files app.
The only way I can view these files I through the File Explorer app. 

### Solution/Idea

Some apps like Windows Terminal, PowerShell (both of which are UWP apps), have an option to run as Administrator, the Solution that I can think of at this point is that of adding the Run as Administrator option for the Files app as well.
This Feature/Enhancement Should be implemented in the next release of Files. And I really hope it does.

### Alternatives

I have tried a Shortcut that runs files.exe with Admin rights, but that does not seem to work. Another way I tried was by setting files.exe to always run with Admin Rights, which also does not work. Those are the only alternatives I have tried.

### Files Version

2.0.34

### Windows Version

Windows 11 21H2 22000.376

**Comment by yaichenbaum** [comment]
Files will prompt you to elevate the app when extra permissions are needed, there are a couple of scenarios that aren't supported yet but we're tracking them in issues like #1194.

**Comment by Wizards-god** [comment]
It has never prompted me to elevate it until now, it just does not display the contents of that folder.

**Comment by yaichenbaum** [comment]
> It has never prompted me to elevate it until now, it just does not display the contents of that folder.

Directories that require admin access are not supported but we're tracking support for this in #1194.
