### ISSUE TITLE
please fix that names of folders and files doesn't show up 

### ISSUE THREAD

**Issue by Fighteros** [files-community/Files#7432]
### What's the Problem?

file names and dir names are overflow hidden that's so annoying when using small group icons or ctrl + shift + 3 mode 
also the side bar doesn't render dirs of device i must close it and open it to work 

### Solution/Idea

please fix the text overflow in group modes 
and also make sure sidebar rerender when closed and opened again 

### Alternatives

no idea 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.0.45.0 OS Version: 10.0.22000.376

### Windows Version

window 11

**Comment by yaichenbaum** [comment]
Merging with #1033
