### ISSUE TITLE
Auto select first username in permissions list on the security page

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#7433]
### Solution/Idea

Auto select first username in the permissions list on the security properties page.

### Alternatives

NA

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will automatically select the first item in the list view when navigating to the security page | Must |

**Comment by ivankahl** [comment]
Hi @yair100, can I take a shot at this issue? Thanks!

**Comment by yaichenbaum** [comment]
@ivankahl sure!

**Comment by yaichenbaum** [comment]
@ivankahl are you still working on this?

**Comment by ivankahl** [comment]
Hi @yair100 , sorry life got a bit busy and I haven't had a chance yet! If someone else would like to take it on then that's fine. Otherwise, I will try to find time this next week.
