### ISSUE TITLE
Files hidden

### ISSUE THREAD

**Issue by louisecarlo** [files-community/Files#7434]
### Description

When I go to the Downloads folder only, I cannot see any files. Even there are files.

### Expected behavior

It should not be hidden

### Files Version

Version: 2.0.34.0

### Windows Version

OS Version: 10.0.21996.1

### Relevant Assets/Logs

https://user-images.githubusercontent.com/97078794/148011792-e78a97e1-ebd2-49aa-ae16-5ec1ddb4dc31.mp4

**Comment by yaichenbaum** [comment]
This issue is resolved in `main`. In the meantime you can work around this by setting the group by option to `none`.
