### ISSUE TITLE
hidden files not show on network storage with show hidden files enable

### ISSUE THREAD

**Issue by JGomsss** [files-community/Files#7438]
### Description

hidden files not show on network storage with show hidden files enable
view on explorer
![image](https://user-images.githubusercontent.com/28355812/148044241-930086c3-e679-4293-92fc-9b6c3824f825.png)
view on Files
![image](https://user-images.githubusercontent.com/28355812/148044297-a319493f-4a0f-4db4-a591-ca1b10feab23.png)

### Expected behavior

hidden files not show on network storage with show hidden files enable

### Files Version

Version : 2.0.34.0 OS Version: 10.0.19044.1415

### Windows Version

21H2  19044.1415

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7806894/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7806895/debug.log)

**Comment by gave92** [comment]
Merging with #2436 (same cause)
