### ISSUE TITLE
Run in background feature

### ISSUE THREAD

**Issue by matinmn87** [files-community/Files#7442]
### What's the Problem?

The problem in the Low speed of Files' loading.

### Solution/Idea

My idea is:
- Add load with system startup
- Stay in background like MS edge's startup boost

### Alternatives

You can make the program's loading faster instead of doing these.

### Files Version

Latest version

### Windows Version

Windows 11 22000.376

**Comment by gave92** [comment]
Thanks for the kind feedback. Unfortunately background / system tray execution is not available for UWP apps. We're actively looking to make Prelaunch work for Files and keep improving the app's startup time.
