### ISSUE TITLE
App installer broken after using “Set Files as default explorer”

### ISSUE THREAD

**Issue by elliots2007** [files-community/Files#7443]
### Description

When activating “Set Files as default explorer” the app installer breaks, and you aren't able to sideload packaged apps. Here is the screen:

![image](https://user-images.githubusercontent.com/67877214/148098868-6e1011ff-70c2-40b8-9334-3c3c418581f1.png)

This seems to happen regardless of application, and does not stop to happen after I turn “Set Files as default explorer” off again.

I did test the application I was trying to install on another PC (Xpo Music) which had never had Files installed, and here it worked fine, until I installed Files and turned on “Set Files as default explorer”.

### Steps To Reproduce

1. Open Files
2. Go to settings
3. Go to Experimental
4. Turn on “Set Files as default explorer”
5. Try to sideload an app. For this example, I tried Xpo Music
6. Observe the error message on the app installer

### Expected behavior

You should still be able to use App Installer

### Files Version

Version: 2.0.34.0 OS Version: 10.0.19044.1415

### Windows Version

Windows 10 21H2 19044.1415

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7809326/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7809327/debug_fulltrust.log)

**Comment by gave92** [comment]
This issue has (unfortunately) nothing to do with the "set as default" option. Microsoft recently disabled the App installer protocol.
