### ISSUE TITLE
Sidebar Categories Appear Open With No Content

### ISSUE THREAD

**Issue by JoshLizak** [files-community/Files#7444]
### Description

Occasionally upon starting the application the sidebar will indicate, via the arrow on the right, that the sidebar categories are expanded however no content is displayed within the category. Clicking the category to condense the category then clicking again to re-expand it will reveal the contents within

### Steps To Reproduce

1. Have single or multiple sidebar categories expanded.
2. Close the Files application.
3. Re-open the Files application.

### Expected behavior

It is expected that categories within the sidebar that were previously left open would remain upon reopening the application.

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.376

### Windows Version

Windows 11 Pro 21H2 (OS Build 22000.376)

### Relevant Assets/Logs

<img width="197" alt="Screenshot 2022-01-04 101429" src="https://user-images.githubusercontent.com/22390591/148105950-0407537e-4a03-43a6-a86e-e32cea2aeeb3.png">

**Comment by gave92** [comment]
Merging with #6469
