### ISSUE TITLE
Highlight file when Jumping to File from browser.

### ISSUE THREAD

**Issue by CristenPerret** [files-community/Files#7447]
### What's the Problem?

Currently when using a browser's Show in File feature from its download section, this app only opens up the folder directory. Or at least have it be enabled by default (assuming its an existing feature that I missed and haven't toggled), as its kind of one of the few core features between browser and file explorer.

### Solution/Idea

Have that file be selected, and in view on the File app, as it does in the default explorer. Not just open up to that directory. 

### Alternatives

Could have it search for that file while opening up that directory, if theres an issue automating a scripted targeting / highlighting of a file.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by MalteTasler** [comment]
same as #6382 .
