### ISSUE TITLE
Selecting text in the rename box cancels the rename action in all layout modes

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#7449]
### Description

Selecting text in the rename box cancels the rename action in all layout modes

### Steps To Reproduce

- Start renaming an item
- Select text

### Expected behavior

The expected behavior is to be able to select text without canceling the rename

### Files Version

v2.0.46

### Windows Version

Windows 11

### Relevant Assets/Logs

NA

**Comment by sicil1ano** [comment]
Hi. I reproduced the issue locally on my Windows 10 machine. I'd suggest to amend the 2nd reproduction step: "Select text using mouse". I often use the keyboard for mostly everything, and indeed the text selection via keyboard _works_.
