### ISSUE TITLE
Copying files promp window 

### ISSUE THREAD

**Issue by KeremArdicli** [files-community/Files#7451]
### What's the Problem?

There is no information window appearing while moving/copying folders/files from one window to another. This also makes me wonder if the process will stop when i close the files window.

### Solution/Idea

Another copy/move process window should open up

### Alternatives

current defeault file manager behaviour is a good exmple

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.0.34.0

### Windows Version

Edisyon	Windows 10 Pro Sürüm	20H2 Yüklenme tarihi	‎12.‎11.‎2021 İS derlemesi	19042.1415 Deneyim	Windows Feature Experience Pack 120.2212.3920.0

**Comment by Josh-65** [comment]
Theres should be an icon in the top right next to the search bar. futher discutions are beeing talked about in #4811
