### ISSUE TITLE
Google drive sync icons is too big

### ISSUE THREAD

**Issue by soredake** [files-community/Files#7452]
### Description

Google drive sync icons is too big in files

How they look in files:
![Снимок экрана 2022-01-03 122400](https://user-images.githubusercontent.com/5204968/148199164-71ddf772-809a-49b3-98c6-bdf70432827f.png)

### Steps To Reproduce

1. Install windows 11/10
2. Install google drive
3. Install files
4. Go into google drive folder in files

### Expected behavior

How they look in windows explorer:
![Снимок экрана 2022-01-03 122349](https://user-images.githubusercontent.com/5204968/148199218-a980ecab-a7ab-4fc7-8ec0-9e565daa5f87.png)

### Files Version

Версия: 2.0.34.0 OS Version: 10.0.22000.376

### Windows Version

Windows 11 Pro 21H2

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7814047/debug.log)

**Comment by yaichenbaum** [comment]
Is this still an issue in the latest preview build? https://files.community/download/preview

**Comment by soredake** [comment]
@yair100 i can't really test this since there is no google drive sync icons anymore in preview.

**Comment by yaichenbaum** [comment]
That sounds like a different issue, can you open a separate issue so we can track it?

**Comment by soredake** [comment]
@yair100 i don't think closing this issue is right decision, in stable version icons are still big, on preview there is no icons so i can't test. I reported missing icons here https://github.com/files-community/Files/issues/10204

**Comment by soredake** [comment]
> Is this still an issue in the latest preview build? [files.community/download/preview](https://files.community/download/preview)

@yair100 yes, that's still a problem 
![изображение](https://user-images.githubusercontent.com/5204968/205457101-bcae9a09-8e30-4c67-a8c9-c21b434483b3.png)
![изображение](https://user-images.githubusercontent.com/5204968/205457107-a53ec396-1119-4f45-99ae-8066aeb3e00b.png)

[debug_fulltrust.log](https://github.com/files-community/Files/files/10147151/debug_fulltrust.log)

**Comment by soredake** [comment]
@yair100 @gave92 @Josh-65 can someone re-open this?

**Comment by BananenRitter** [comment]
still there

**Comment by Josh65-2201** [comment]
Thats not Files that is the desktop

**Comment by Josh65-2201** [comment]
@soredake Have you tried with 2.5.21.0?

**Comment by mdtauk** [comment]
In the future, this should be treated like our other Status Icons

**Comment by BananenRitter** [comment]
> Thats not Files that is the desktop

The green synchronisation icon on top of the files icon

**Comment by Josh65-2201** [comment]
Your screenshot is showing the shortcut/files on your desktop were talking about in the Files App

**Comment by soredake** [comment]
> @soredake Have you tried with 2.5.21.0?

Yes, icons are not too big now, they are too small now.
