### ISSUE TITLE
List of drives takes a long time to load when network drives are unavailable

### ISSUE THREAD

**Issue by starkgate** [files-community/Files#7453]
### Description

The list of drives takes a long time to load when network drives are unavailable. I am also wondering if this is the reason for the buggy arrows in the sidemenu: when I open Files the favorites arrow is down, yet the favorites are not showing up. It works fine if I close the favorites submenu and open it again.
![vDABX18rj4](https://user-images.githubusercontent.com/12874678/148207564-cb473c3a-1532-4a4d-9b39-5b9cd77b99b5.png)

### Steps To Reproduce

1. Map a network drive
2. Ensure the network drive is not accessible by Files (e.g. disconnect the host computer from the network)
3. Run Files

### Expected behavior

Perhaps the availability of the drives can be detected asynchronously, so the rest of the GUI can load properly. Unavailable network drives shouldn't delay the entire application.

### Files Version

Version: 2.0.45.0 OS Version: 10.0.19044.1415

### Windows Version

Windows 10 Pro Version 21H2

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7814426/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7814428/debug.log)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7464

**Comment by starkgate** [comment]
Beautiful, thank you!
