### ISSUE TITLE
All popup menus are obscured

### ISSUE THREAD

**Issue by ismslv** [files-community/Files#7457]
### Description

Shadows under all popups (like menus, dropdowns, item hints) are shown on the top, making them dark and blurred.
This happens after random time (usually almost immediate) with Light or Dark theme, any Custom theme. It does not depend on the Windows theme or Windows apps theme.

![20220105_145015](https://user-images.githubusercontent.com/37056221/148228779-019c78a5-4ffb-4901-99f1-edbc2e2af3cc.jpg)
![20220105_145159](https://user-images.githubusercontent.com/37056221/148228782-edaf1aa6-aea8-4d55-bfff-b18b6cb0230f.jpg)

If "Transparency effects" are set to off in "Settings -> Personalization -> Colours", shadow is not shown at all, thus the problem is  partly resolved.

### Steps To Reproduce

I've just installed application from Microsoft Store and launched it.

### Expected behavior

Shadow should be under the semi-transparent elements, not obscuring the view.

### Files Version

2.0.34.0

### Windows Version

Windows 10 19043.1415

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7815382/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7815383/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
This is an OS bug in Windows 10 but should be fixed in Windows 11.
