### ISSUE TITLE
Icons in context menu are black or not shown

### ISSUE THREAD

**Issue by ismslv** [files-community/Files#7458]
### Description

Certain custom icons in context menu show black background.
Certain others are not shown at all.

![image](https://user-images.githubusercontent.com/37056221/148230152-3ee11906-7c32-4c4d-9b55-7e3ba4eb985f.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/37056221/148230250-4d61ba56-c91b-443a-8da2-46bdd5ed4931.png)

### Files Version

2.0.34.0

### Windows Version

Windows 10 19043.1415

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7815413/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7815414/debug.log)

**Comment by gave92** [comment]
Merging with #3834
