### ISSUE TITLE
Can't cut or copy any files

### ISSUE THREAD

**Issue by geraltofrivia894** [files-community/Files#7459]
### Description

If i copy or cut any file then click paste on another location, nothing happens.

### Expected behavior

It is supposed to copy or cut the file to my preferred location

### Files Version

2.0.34.0

### Windows Version

Win 11 - 21h2 - Build 22000.376

### Relevant Assets/Logs

https://user-images.githubusercontent.com/97174738/148231627-4cdad7a0-5337-4ad3-91f8-7d3399234a93.mp4
[debug.log](https://github.com/files-community/Files/files/7820049/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7820050/debug_fulltrust.log)

**Comment by gave92** [comment]
Merging with #7459

**Comment by yaichenbaum** [comment]
Is this still an issue in the latest preview build? https://files.community/download/preview

**Comment by Josh-65** [comment]
I've had it happen recently it seems rare through. Cut stop working but copy still does

**Comment by yaichenbaum** [comment]
I think @gave92 had a fix for cut not working.

**Comment by gave92** [comment]
For the winui3 version only, and copy works for me. This is a different issue.

**Comment by aitronssesin** [comment]
I have the issue in the latest version of Files there's any fix?

**Comment by Josh65-2201** [comment]
Try restarting your computer.

**Comment by aitronssesin** [comment]
Thx now it works perfectly
