### ISSUE TITLE
Status column not showing when I drell down too far...

### ISSUE THREAD

**Issue by brucebinder** [files-community/Files#7462]
### Description

C:\Users\bruce\OneDrive\Documents\Lakshmi\Chair Yoga—status does not show

C:\Users\bruce\OneDrive\Documents\Lakshmi\—staus shows

### Steps To Reproduce

Open folder C:\Users\bruce\OneDrive\Documents\Lakshmi\Chair Yoga and no status shows

### Expected behavior

Status to show no matter how many levels I go

### Files Version

2.0.46.0

### Windows Version

21h2 22000.376

### Relevant Assets/Logs

No logs needed.

**Comment by gave92** [comment]
You may want to try to move the Onedrive folder to a new location to see if this solves the issue
- Taskbar > Onedrive > Settings > Account > "Unlink this PC"
- In OneDrive setup screen follow the instructions until you get to the screen where you can change your OneDrive folder's location.
- Select a new empty folder
