### ISSUE TITLE
Request to delete a file

### ISSUE THREAD

**Issue by VVARAXE** [files-community/Files#7465]
### What's the Problem?

There is no way to disable the request for confirmation of file deletion in the program settings, as it is in Windows 10 explorer

### Solution/Idea

Add a checkbox to the settings that allows you to remove the request to confirm the deletion of the file, you can still quickly display the message "the file has been moved to the trash bin" somewhere downstairs, and if you delete it with the Shift button held down, then "the file has been deleted".
And also rework or remove the animation of clicking on a folder once with the left mouse button, because when you click 2 times to open the folder, the animation looks ugly and confusing, just a suggestion. Sorry for my google translate

### Alternatives

I don't know what to write here

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.0.34.0

### Windows Version

Windows 10 20H2 19042.1415

**Comment by gave92** [comment]
There's already an option to disable the delete confirmation dialog.
The animation can't be removed because it's system defined. Good news, the animation has been removed in windows 11.

**Comment by VVARAXE** [comment]
OMG, excuse me, I sort of looked at all the settings, and did not see it, sorry, I’m apparently blind
