### ISSUE TITLE
Click animation is a little redundant

### ISSUE THREAD

**Issue by LItterBoy-GB** [files-community/Files#7468]
### What's the Problem?

Click animation is a little redundant.
![tets](https://user-images.githubusercontent.com/28385638/148311636-b2f65e7f-ea19-4026-84d5-4b637aabbe7b.gif)

### Solution/Idea

I wish I could turn on and off this animation effect

### Alternatives

There are no alternatives.

### Files Version

2.0.34.0 

### Windows Version

Windows 10.0.19043.1288

**Comment by yaichenbaum** [comment]
@LItterBoy-GB this is part of the ListView control in Windows 10 but is no longer present in Windows 11.
