### ISSUE TITLE
Trying to rename any file & clicking sidebar crashes app.

### ISSUE THREAD

**Issue by CrypticVader** [files-community/Files#7472]
### Description

After I select any file/folder and select rename & then click on any item in the sidebar, then Files will crash with the notification saying### 
![image](https://user-images.githubusercontent.com/61494838/148331936-1c780fd2-39d8-4963-83b1-9f0aadd5cd3b.png)

Sometimes this notification appears twice or thrice in a row.

### Steps To Reproduce

1. Open any directory & select any file/folder and click rename (or press F2).
2. Now without dismissing the rename overlay, press on any local drive on the sidebar.

### Expected behavior

Files should crash with a notification (attached above) which appears twice or thrice.

### Files Version

v2.0.47

### Windows Version

Windows 11 21H2 22000.376

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7819597/debug_fulltrust.log)

**Comment by gave92** [comment]
Should be fixed by #7481
