### ISSUE TITLE
Crash on navigation 

### ISSUE THREAD

**Issue by J-HS-L** [files-community/Files#7474]
### Description

had launched Files right after updating in store last night, but immediately switched to some other stuff, 

Switched back (clicked on the "files is open" indicator on the taskbar) later the next day to use it for the 1st time. 

But it crashed & an error box came up (see the title of this report), it asked something else, I said/clicked OK; 
And then it launched this page, as well as a fresh instance of Files.

Copied xxx.FilesUWPzzz folder (located in Users -> User -> AppData -> Local -> Packages)
To this sub-folder in my OneDrive account:
https://1drv.ms/u/s!AgX5ZmkXXVySgZpba5Si7HYC-Q8Pqg?e=5AQUGy

### Expected behavior

normal context switch back to app

### Files Version

Version: 2.0.46.0 

### Windows Version

OS Version: 10.0.19044.1415

### Relevant Assets/Logs

See my OneDrive link in description field

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7483
