### ISSUE TITLE
The "Set Files as default file explorer" cannot be reverted to OFF

### ISSUE THREAD

**Issue by NinjaCross** [files-community/Files#7479]
### Description

Once selected (ON) the "Set Files as default file explorer"  option, it cannot be set to OFF.
![image](https://user-images.githubusercontent.com/5829421/148381989-198305ed-d247-466a-a15f-6639ba850c58.png)

### Steps To Reproduce

1. Set the "Set Files as default file explorer"  to ON
2. Restart Files
3. Set the "Set Files as default file explorer"  to OFF
4. The UAC appears asking for permissions to open Regedit as administrator
5. Click "Yes" in the UAC window
6. ... nothing changes, the "Set Files as default file explorer" is always ON

### Expected behavior

Once clicked, the option should change to "OFF"

### Files Version

Version: 2.0.34.0 OS Version: 10.0.19042.1415

### Windows Version

Windows 10  19041.vb_release.191206-1406

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7821717/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7821718/debug.log)

**Comment by gave92** [comment]
You can revert to Explorer by running "UnsetFilesAsDefault.reg" from [here](https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip)
