### ISSUE TITLE
[Request/Feedback] Fetch smaller thumbnails to speed up loading time

### ISSUE THREAD

**Issue by SOI7** [files-community/Files#7485]
### What's the Problem?

As you can see in the video, Shrestha loads thumbnails much faster compared to Files, with the same folder and the same layout. Yair suggested that it may be due to the size they are requesting being smaller, so that may be something to look into

https://user-images.githubusercontent.com/50930970/148400668-c45a495d-0f8e-4ffd-8c01-9cdb3cb5cd52.mp4

### Solution/Idea

Fetch thumbnails with smaller size

### Alternatives

Something else that could enhance the loading time

### Priorities

| This proposal will allow developers to accomplish faster loading speed | Must |

### Files Version

2.0.46

### Windows Version

Windows 10 21H2

### Comments

Note that I'm on an SSD, so it's not due to my hardware

**Comment by gave92** [comment]
Might be due to the fact that we wait for all folder items to be loaded while shrestha load files in batches and immediately fetches the thumbnails (but takes longer to actually load all the items, you can see the scrollbar getting smaller)

**Comment by gave92** [comment]
Btw looks like that we are caching the thumbnails for image files that does not male sense (at the beginning all images appear to be the same)

**Comment by yaichenbaum** [comment]
> Btw looks like that we are caching the thumbnails for image files, which does not make sense (at the beginning all images appear to be the same)

We also fetch the basic thumbnail the first time the directory is opened and we don't reload when the actual thumbnail is cached by Windows.

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
This still requires some investigation on our part.

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
