### ISSUE TITLE
Opening a video to VLC launch VLC but not the video

### ISSUE THREAD

**Issue by newSebastienTHOMAS** [files-community/Files#7490]
Double clicking a video file or right-clicking and choosing "Open" does not work with VLC.

It opens VLC (that is associated with video files) but the video does not start at all.

Although if I right-click and choose "Open With" and select VLC then the video starts correctly.

No issues with opening other types of file.
And if I associate the video file to another video player there is also no issue.
If I switch back to VLC then again, the video is not started.

**Comment by yaichenbaum** [comment]
thank you for taking the time to report this, in order to investigate the issue we'll need the log files and steps to repro this bug, can you please reopen this issue using the issue template?
