### ISSUE TITLE
"Display Vertical Tab Flyout" Option Resets Every Time Files is Updated.

### ISSUE THREAD

**Issue by Gryzle** [files-community/Files#7491]
### Description

The "Display the vertical tab flout on the title bar" in the "Multitasking" tab in Settings is reset every time the app is updated via the Microsoft Store (not sure about other update methods). To clarify, what is happening in my case is that the toggle goes from the "Off" state (before updating) to the "On" state (after updating).

**Thank you** for your continued support of Files

### Steps To Reproduce

1. Disable "Display the vertical tab flout on the title bar" in the "Multitasking" tab in Settings
2. Update the app via the Microsoft Store
3. Go back to the same page in settings

### Expected behavior

This option should remain off when turned off, even after updating the app.

### Files Version

Version: 2.0.48.0 OS Version: 10.0.22000.376

### Windows Version

Windows 11 22000.376

### Relevant Assets/Logs

![Screenshot 2022-01-06 162340](https://user-images.githubusercontent.com/51198087/148454130-0e930787-f04e-4c04-b2c5-a5e5eb744bf0.png)

**Comment by yaichenbaum** [comment]
@gave92 are you able to reproduce this?
