### ISSUE TITLE
Files Attempts (and fails) to Move a File to the Recycle Bin When It Is Disabled by Windows

### ISSUE THREAD

**Issue by Gryzle** [files-community/Files#7492]
### Description

Files produces an error when attempting to delete a file when the Recycle bin is disabled. When the "Permanently Delete checkbox is turned on, files then properly delete, but having to check this every time is very inconvenient. This can be seen as a feature request, but I am filing as a "Bug" because it results in an error when the workaround isn't utilized.

**Thank you** for your continued support of Files

### Steps To Reproduce

Within Windows:
1. Right-Click on the "Recycle Bin" on the Desktop
2. Select "Properties"
3. Select "Don't move files to the Recycle Bin. Remove files immediately when deleted."

Within Files:
1. Find a file, and hit the "Delete" button.
2. In the delete panel, click "Delete" (without selecting "Permanently Delete)

### Expected behavior

The functionality is already built into files with the "Permanently Delete" checkbox. To make using Files more usable when the Recycle Bin is disabled, there are two ways that Files can better handle deleting a file:

1. The "Permanently Delete" checkbox should be automatically enabled (and user interaction should be disabled so it can't be un-checked as it simply results in an error).
2. A new option under the "Preferences" to automatically always enable the "Permanently Delete" checkbox when removing files.

### Files Version

Version: 2.0.48.0 OS Version: 10.0.22000.376

### Windows Version

Windows 11 22000.376

### Relevant Assets/Logs

![Screenshot 2022-01-06 163911](https://user-images.githubusercontent.com/51198087/148455825-b26da423-7b49-440d-b055-a2e762ef87be.png)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7500
