### ISSUE TITLE
Feature: Option to open all items in a tag

### ISSUE THREAD

**Issue by StLa1** [files-community/Files#7493]
### What's the Problem?

People usually use the same group of apps for common tasks. 

Right now Bundles are just a fancy quick-access bookmarks, but allowing to open all contained items at once (when the bundle is clicked) would make them much more useful

### Solution/Idea

Open all contained items at once when the Bundle is clicked

### Alternatives

Click+Shift+Click to select all items then Enter to open them

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Allow users to still open items individually when the item name is clicked | Must |
| Allow users to open all items in 1 click, probably from a menu flyout on the top right of the tag container on the home page | Must |

### Files Version

.34.0

### Windows Version

21H2

**Comment by MalteTasler** [comment]
I think this can be closed as bundles are going to be replaced by tags.

**Comment by Josh-65** [comment]
This could be done for tags instead
