### ISSUE TITLE
无法批量复制粘贴文件？

### ISSUE THREAD

**Issue by aa2013** [files-community/Files#7495]
### Description

在一个文件夹里面（4000+文件），进行搜索后，搜索结果列表里面全选复制后无法粘贴到另一个文件夹里面，剪切也不可以，右上角提示已经粘贴成功。
测试了下复制三个文件可以，数量少的话好像是可以的
没有在原生的资源管理器里面测试，因为我把 files 设置为了默认了
整个文件夹一起复制是可以的

### Expected behavior

应该可以批量复制

### Files Version

版本: 2.0.34.0 OS Version: 10.0.19042.1288

### Windows Version

Windows 10 20H2 19042.1288

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7828978/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7828979/debug_fulltrust.log)

**Comment by josh-65** [comment]
Please re write in English.
