### ISSUE TITLE
无法打开Bandizip解压

### ISSUE THREAD

**Issue by domeniczz** [files-community/Files#7497]
### Description

我的bandizip设置为双击直接解压到当前文件夹

在Files里面双击压缩包会大概率无响应，就是双击压缩包没有任何反应

### Steps To Reproduce

1. bandizip设置为双击直接解压到当前文件夹
2. 双击一个压缩包（如果成功调出bandizip解压，则重新打开Files，再次双击该压缩包，有很大概率会无反应）
我百试百灵

### Expected behavior

双击直接解压到当前文件夹

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.376

### Windows Version

Windows 11 Pro 21H2 22000.376

### Relevant Assets/Logs

no log no image

**Comment by josh-65** [comment]
Please re write in English.
