### ISSUE TITLE
 Opening a video to VLC launch VLC but not the video 

### ISSUE THREAD

**Issue by newSebastienTHOMAS** [files-community/Files#7498]
### Description

Double clicking a video file or right-clicking and choosing "Open" does not work with VLC.

It opens VLC (that is associated with video files) but the video does not start at all.

Although if I right-click and choose "Open With" and select VLC then the video starts correctly.

No issues with opening other types of file.
And if I associate the video file to another video player there is also no issue.
If I switch back to VLC then again, the video is not started.

### Steps To Reproduce

1. Set VLC app from windows store as default media player
2. Select a video file in Files
3. Double click to open file

### Expected behavior

Files should not only opens VLC app but the video selected  should starts playing.

### Files Version

Version : 2.0.34.0 OS Version: 10.0.22000.376

### Windows Version

Windows 11 21H2 22000.376

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7830327/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7830328/debug_fulltrust.log)

**Comment by josh-65** [comment]
It works for me, what VLC version are you on and have you check it works in normal file explorer?

**Comment by newSebastienTHOMAS** [comment]
It is VLC straight from the windows store latest version.
3.2.1.0
![image](https://user-images.githubusercontent.com/75215554/148659837-827e068a-5257-475a-94ef-ed52304f1d9a.png)

There is no issues with the normal file explorer. videos files are open and stars playing on VLC. But not with files.

**Comment by josh-65** [comment]
Could try the exe version of VLC. https://www.videolan.org/vlc

**Comment by newSebastienTHOMAS** [comment]
Hi,
 I have deleted the VLC and reinstall it from windows store (again). And Installed the latest Files version.
 It works now.
 Not sure what makes it work.

Anyway, thank you for your time.
