### ISSUE TITLE
Add option to add selected tabs to a bundle

### ISSUE THREAD

**Issue by MalteTasler** [files-community/Files#7502]
### What's the Problem?

I want to save a setup of tabs for later use before I close the app or some tabs.

### Solution/Idea

- (requires #7501 and #7493 to be implemented)

- an option to add selected tabs to a bundle
- an option to add all tabs opened to a bundle

This feature request resembles the possibility in Microsoft Edge to add all tabs to a collection.

### Alternatives

- Adding paths manually to a bundle -> not as straightforward and quick
- Use the new feature to restore last session witb "ctrl + shift + t" -> works only for the latest session

### Files Version

2.0.48.0

### Windows Version

Windows 11 21H2 - 22000.376

**Comment by yaichenbaum** [comment]
Bundles are no longer being developed and will be replaced with a tags widget.
