### ISSUE TITLE
Bigger tile size option

### ISSUE THREAD

**Issue by gusky14** [files-community/Files#7507]
### What's the Problem?

The "Large Icons" option is currently smaller than File Explorer's largest tile size option. 

### Solution/Idea

Add an "Extra Large Icons" selection

### Alternatives

Increase the size of the "Large Icons" option to match the size of the largest option in File Explorer.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.0.34.0

### Windows Version

Windows 11 Insider 22523.1000

**Comment by yaichenbaum** [comment]
Closing since this was resolved by the `ctrl` + `+` shortcut.
