### ISSUE TITLE
Preview does not work for many images

### ISSUE THREAD

**Issue by soredake** [files-community/Files#7509]
### Description

For some reason Files cannot show preview for many images in my folder.
![изображение](https://user-images.githubusercontent.com/5204968/148678853-9c33a3f4-f091-48e7-af09-618b475f997a.png)

### Steps To Reproduce

1. Install windows 11 pro.
2. Install files.
3. Go to folder with many pictures.

### Expected behavior

Previews work.

### Files Version

Версия: 2.0.34.0 OS Version: 10.0.22000.376

### Windows Version

Windows 11 pro 21H2 10.0.22000.376

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7834878/debug.log)

**Comment by gave92** [comment]
Thanks for the report. What file format are those images? What have you set as default program to open those images?

**Comment by gave92** [comment]
Should be the same as #6130

**Comment by soredake** [comment]
> Thanks for the report. What file format are those images? What have you set as default program to open those images?

Images are png. I set nomacs as default image viewer.

**Comment by soredake** [comment]
> Should be the same as #6130

Opening folder in explorer does not helps, previews are already generated.

**Comment by soredake** [comment]
Why close?

**Comment by yaichenbaum** [comment]
https://github.com/files-community/Files/issues/7509#issuecomment-1008274187
