### ISSUE TITLE
Experimental Features 

### ISSUE THREAD

**Issue by bhagatshiv124** [files-community/Files#7510]
### Description

once the experimental feature turn on then toggle of that feature couldn't turn off please solve this bugs soon.thank you

### Expected behavior

when i turn off that toggle then one registry warming popup and click on yes or no again by again but notting happen.

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.376

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎2021-‎11-‎01 OS build	22000.376 Experience	Windows Feature Experience Pack 1000.22000.376.0

### Relevant Assets/Logs

.

**Comment by gave92** [comment]
You can revert to Explorer by running "UnsetFilesAsDefault.reg" from [here](https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip).
