### ISSUE TITLE
Feature: Add support for changing icons for the home page, recycle bin etc

### ISSUE THREAD

**Issue by alessandrocaseti** [files-community/Files#7512]
### What's the Problem?

I'm on Windows 10 and default system icons are pretty ugly compared to the fluent ones.

![Screenshot (89)](https://user-images.githubusercontent.com/90320229/148691763-82618e19-2cb7-4583-a796-ddfe55f49b2d.png)

### Solution/Idea

Add custom icon packs for Themes.

### Alternatives

Add an option to use Segoe MDL2/Fluent icons font instead of custom images.

**Comment by kelwilson** [comment]
Add custom icon packs for Themes.
