### ISSUE TITLE
Open directories in File Explorer when it's already open

### ISSUE THREAD

**Issue by Gryzle** [files-community/Files#7513]
### Description

Files appears to crash (closes and reopens) when File Explorer is opened.

**Thank you** for your continued support of Files

### Steps To Reproduce

1. Open Files
2. Enable "Set Files as the default file manager" in Settings
3. Leaving Files opened, also open a File Explorer window
4. Files then crashes and relaunches

### Expected behavior

Files should not close and reopen (crash) when File Explorer is opened.

### Files Version

Version: 2.1.0.0 OS Version: 10.0.22000.376

### Windows Version

Windows 11 22000.376

### Relevant Assets/Logs
![2022-01-09 17-28-17_Trim](https://user-images.githubusercontent.com/51198087/148705067-12427c9a-30d2-4f89-8f56-7fce073525a7.gif)

**Comment by yaichenbaum** [comment]
This is the intended behavior, you might notice the same thing when you open Control Panel. The reason this happens is that the registry keys we change to set Files as the default prevents users from opening File Explorer. To accommodate situations where the user wants to open explorer, we redirect back to File Explorer and close Files.

**Comment by Gryzle** [comment]
I completely understand what you're saying, but in that case shouldn't Files stay closed? It doesn't re-open previously open tabs/windows.

**Comment by yaichenbaum** [comment]
@Gryzle Files needs to open long enough to detect that the user was trying to open Explorer and to handle the logic.

**Comment by yaichenbaum** [comment]
@gave92 is it posible to do something similar to what you did with Control Panel?

**Comment by gave92** [comment]
@Gryzle how do you manage to open Files Explorer when Files is set as default? Where do you open in from?

**Comment by yaichenbaum** [comment]
You can open it from the search box

**Comment by gave92** [comment]
Typing "explorer.exe" opens a new tab in Files for me

**Comment by yaichenbaum** [comment]
Are you pressing enter or are you clicking on the search result?

**Comment by gave92** [comment]
Tried both with the same result (Files opens)

**Comment by yaichenbaum** [comment]
> Tried both with the same result (Files opens). Do you see something different then? And you can reproduce this issue? Note: I've only tried Debug version.

I can reproduce on Windows 11, it's the same issue we had with control panel and ideally we can do a similar fix so that people can still use File Explorer.

**Comment by gave92** [comment]
This requires switching to separate Win32 launcher.

**Comment by yaichenbaum** [comment]
@gave92 is this possible to implement now that we use a separate launcher?
