### ISSUE TITLE
Font get blurry after using property pannel

### ISSUE THREAD

**Issue by MrLixm** [files-community/Files#7515]
### Description

Hello, see Steps to Reproduce for description.
Cheers.
Liam.

### Steps To Reproduce

1. Select any file/folder
2. Right click and open the Properties panel (with the i icon)
3. Close the properties panel
4. The file/folder selected has now its name with a blurry appearance.

### Expected behavior

Name's font doesn't change appearance.

### Files Version

Version: 2.1.0.0 OS Version: 10.0.19044.1415

### Windows Version

Edition	Windows 10 Pro N Version	21H2 Installed on	‎13/‎12/‎2020 OS build	19044.1415 Experience	Windows Feature Experience Pack 120.2212.3920.0

### Relevant Assets/Logs

Example of file names looking blurry after opening the properties pannel :

![2022_01_09_231116_649x286](https://user-images.githubusercontent.com/64362465/148705521-e416c347-a23a-4ace-a71e-6ddb42f2fc54.png)

**Comment by yaichenbaum** [comment]
This issue is resolved in Windows 11.
