### ISSUE TITLE
Browsing folder load times are very inconsistent and slower compared to explorer.exe

### ISSUE THREAD

**Issue by ilbalta** [files-community/Files#7519]
### Description

Navigating trough a hierarchy of files using Files presents perceivable slowdowns and lags. This is particularly noticeable when compared to explorer.exe and when navigating quickly around. Using keyboard controls will make the issue even more apparent.
Here is video with a keyboard overlay clearly showing this inconsistency and slowness: [https://youtu.be/TJiyZ72gXOM](https://youtu.be/TJiyZ72gXOM)

### Steps To Reproduce

Open a folder in Files
Open the same folder in explorer.exe
Notice there is a perceivable lag when using Files compared to using explorer.exe

### Expected behavior

Opening folders should be lag-free

### Files Version

Version: 2.0.34.0

### Windows Version

Windows OS Version: 10.0.19044.1415

### Relevant Assets/Logs

[https://youtu.be/TJiyZ72gXOM](https://youtu.be/TJiyZ72gXOM)

**Comment by yaichenbaum** [comment]
Merging with #4180

**Comment by yair100** [comment]
@ilbalta we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
