### ISSUE TITLE
Files 2.1 package

### ISSUE THREAD

**Issue by gh0sti** [files-community/Files#7520]
### What's the Problem?

Can we get the precompiled version of 2.1? The other releases have this and 2.1 is only showing source code. 

Another question how long do updates take to populate in the windows store?

### Solution/Idea

Add pre-package 2.1 

### Alternatives

are you done providing pre-packaged updates?

### Priorities

| Capability | Priority |
| :---------- | :------- |

| This proposal will allow end users to accomplish X | Should |

### Files Version

Version: 2.0.34.0

### Windows Version

Windows 11 22000.376

**Comment by coolmyll** [comment]
I was wondering the same thing. Maybe it gets a day or two for package to be approved in the store?

**Comment by yaichenbaum** [comment]
@gh0sti you can download Files from https://files.community/download/stable or alternatively from the release page on GitHub https://github.com/files-community/Files/releases/tag/v2.1.
The store release depends on certification from Microsoft which takes 1 - 3 business days.

**Comment by coolmyll** [comment]
First link doesnt work. Seem like it needs to be updated.
![image](https://user-images.githubusercontent.com/4244134/148840132-f638bc31-2714-46b2-a1ef-50a8886313aa.png)
The second, has a link for a zip which i am not sure how to install.

**Comment by Saelman** [comment]
Having same issue

**Comment by yaichenbaum** [comment]
> Having same issue

Please ask Microsoft to reenable appinstaller protocol. In the meantime, try installing the package on the release page https://github.com/files-community/Files/releases/tag/v2.1.

**Comment by Saelman** [comment]
Which of the files is the Installer. I'm unable to run any of the files besides besides the x64_arm64.msixbundle. I'm on Windows 11 PRO.

**Comment by gh0sti** [comment]
> @gh0sti you can download Files from https://files.community/download/stable or alternatively from the release page on GitHub https://github.com/files-community/Files/releases/tag/v2.1. The store release depends on certification from Microsoft which takes 1 - 3 business days.

At first the release wasn't there it was just source code so that must have been uploaded later. Store update came out yesterday so thanks.

**Comment by yaichenbaum** [comment]
> Which of the files is the Installer. I'm unable to run any of the files besides besides the x64_arm64.msixbundle. I'm on Windows 11 PRO.

The msixbundle
