### ISSUE TITLE
Add item button disabled when creating fresh bundle.

### ISSUE THREAD

**Issue by rp1231** [files-community/Files#7523]
### Description

The add item is greyed out when I create a new empty bundle.
Restarting the app fixes the greying out, but the same problem occurs when I create a new empty bundle.
Every time I create a new empty bundle, I have to restart the app to fix the greying out.

### Steps To Reproduce

1. Open Files
2. Click on create bundle
3. Click on the three dots menu in the newly created bundle
4. The Add item button will be greyed out in the menu
5. Restarting the app will enable the add item button, but the same problem appears when a new bundle is created.

### Expected behavior

The add item button shouldn't be  greyed out.

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.376

### Windows Version

Windows 11 21H2 22000.376

### Relevant Assets/Logs

![ApplicationFrameHost_0XCRdCehwo](https://user-images.githubusercontent.com/47380919/148819807-50333bdd-90f9-48db-a556-98050605869b.png)

**Comment by boscorelly** [comment]
i can confirm the same issue in v2.1.0.0 plus another linked issue i think : if you create a bundle, the third points at the extreme right are no more usables.

for the initial bug, if you quit and relaunch files, you can add folders/files

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7569
