### ISSUE TITLE
Folder "group by" not saved.

### ISSUE THREAD

**Issue by xmha97** [files-community/Files#7524]
### Description

Hi,
Folder "group by" not saved.

https://user-images.githubusercontent.com/23485114/148827566-46bab524-006a-4419-b096-d23c8f15cc96.mp4

### Expected behavior

Folder "group by" saved.

### Files Version

Version: 2.1.0.0 OS Version: 10.0.19044.1415

### Windows Version

Windows 10 20H2 19044.1415

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7841435/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
This is intentional and matches the behavior of File Explorer where each directory has their own settings. You can change this by turning off the option to use individual preferences in different directories.

**Comment by xmha97** [comment]
Now I turning on the option to use individual preferences in different directories.
![image](https://user-images.githubusercontent.com/23485114/148831362-9062328c-97a9-4031-a995-2241ad65d79c.png)
I expected "group by" saved for each folder.
