### ISSUE TITLE
File size aren't shown for Hidden folders

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#7525]
### Description

In the properties the size text doesn't show.

### Expected behavior

Folder size should be shown

### Files Version

2.0.50.0

### Windows Version

10.0.19043.1387

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7841865/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7841866/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
@cinqmilleans

**Comment by cinqmilleans** [comment]
@yair100 @josh-65 I will investigate.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7538
