### ISSUE TITLE
Existing tabs being lost when opening from the taskbar jumplist

### ISSUE THREAD

**Issue by SullieLore** [files-community/Files#7526]
### Description

Hi,

Latest version, 2.1, installed on Windows 11.

When I open a folder from the jumplist while Files is open, it opens the window as a tab to the existing Files window. This is what I want it to do. However, When Files is closed, and I open a folder from the jumplist it opens the folder but all previous saved tabs are lost.

I tried "open new instance when opening directories~" under preferences/startup settings, but the same issue remains when Files is closed.

### Expected behavior

Files to remember tabs under all circumstances, and potentially keep regular backups in case of failure.

### Files Version

Version: 2.1.0.0 OS Version: 10.0.22000.376

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎30/‎07/‎2021 OS build	22000.376 Experience	Windows Feature Experience Pack 1000.22000.376.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7842980/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7842981/debug_fulltrust.log)

**Comment by SullieLore** [comment]
Perhaps a way of fixing this could be to add a new experimental option that keeps Files running in the background. If the user closes Files, it hides instead of closing completely, then when a user clicks a folder to open from the jump list Files can reappear instead of open from being completely closed. An advantage of this approach could be running Files as an admin once to retain elevated functionality for the entire Windows session.

**Comment by Josh-65** [comment]
Merging with #6728

**Comment by SullieLore** [comment]
Another thought: Close button closes Files to the Tray with an option of having a hidden icon. This would essentially replicate a running service. Since Files is a Windows app, the Efficiency mode should kick in to prevent excessive cpu/memory. The Open Files on Windows Startup should have another checkbox to Hide to Tray.

This all will mean that when people open folders from Start (or, in my case, Wox), Files should bounce back into view with the existing set of saved tabs.

**Comment by Josh-65** [comment]
It has been suggested #9837
