### ISSUE TITLE
It's Slow and Unstable

### ISSUE THREAD

**Issue by AhmadrezaAlipouryaan** [files-community/Files#7527]
### Description

Please check your app performance. Thanks

### Expected behavior

Sometimes some icons are have a black square
sometimes it's crash
sometimes it use much power of PC.

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.376

### Windows Version

Windows11 22000.376

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7843567/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7843569/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
Thank you for taking the time to report this, in order to investigate the issue we'll need the log files and steps to repro this bug, can you please reopen this issue using the issue template?

**Comment by yaira2** [comment]
We're excited to share that startup performance will be significantly improved in the upcoming release of version 3. You can download the preview version from our website https://files.community/download.
