### ISSUE TITLE
The songs will not automatically enqueue by selecting multiple music files and play

### ISSUE THREAD

**Issue by Nalser3200** [files-community/Files#7530]
### Description

When highlighting multiple music files and pressing enter to play, only one music file will be played and not enqueue all the music files selected.

### Steps To Reproduce

1. Go to the folder containing music files.
2. Highlight multiple music files.
3. Press enter to play the selected music files.
4. Only one music file will be played, other selected music files will not be enqueued.

### Expected behavior

All the selected music files should be enqueued and played in a list, but not only one music file will be played.

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.376

### Windows Version

Windows 11 21H2 22000.376

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7844441/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7844442/debug_fulltrust.log)

**Comment by gave92** [comment]
What program do you have as default for music files?

**Comment by Nalser3200** [comment]
> What program do you have as default for music files?

I tried with foobar2000 and Groove Music also same problem, and sorry for the mistake of windows version, it is win 11, not win 10.
