### ISSUE TITLE
Folder tags won't save on folders with custom icons

### ISSUE THREAD

**Issue by DoppelKomma** [files-community/Files#7534]
### Description

If I change the icon of a folder, it will not save the assignment of a tag. If the folder had a tag before changing the icon, it will not save the removing of it.
If the icon has been changed once, even "Restore default" in the Customization tab will not fix it. I did not find any other way to fix it, other than creating a new folder.

### Steps To Reproduce

1. Go to the properties of any folder
2. Assign a custom folder icon
2. Give the folder a tag or remove the tag, if it had one before assigning a custom icon
3. Refresh
4. The Tag is gone or back - reset to how it was before the custom icon

### Expected behavior

Assigning and removing tags should be saved, even if the folder icon has been changed.

### Files Version

2.1.0.0

### Windows Version

Windows 11 Pro 21H2 22000.376

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7847144/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7847145/debug.log)

**Comment by gave92** [comment]
Apparently it's because a folder with a custom icon is set as "read only" so we can't save the tag in it. You can restore the folder with "attrib -r FolderName" from command prompt but you'll also loose the custom icon.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7558
