### ISSUE TITLE
Right clicking folder on details view empty space doesn't select it

### ISSUE THREAD

**Issue by mangoepic** [files-community/Files#7535]
### Description

![Files right click report](https://user-images.githubusercontent.com/71931749/148962469-f9f6de82-349c-45b1-8e87-2ff00852a2f4.gif)

You unfortunately can't see the cursor here, but I right click other folders and most of the time it doesn't select the folder I rightclicked, which tags the "wrong folder"

### Steps To Reproduce

-

### Expected behavior

-

### Files Version

Version: 2.1.0.0 

### Windows Version

OS Version: 10.0.22000.194

### Relevant Assets/Logs

-

**Comment by DoppelKomma** [comment]
I think it depends on where you right click, if you right click in the name column, it will be selected, in every other column it won't.

**Comment by gave92** [comment]
A similar issue suggests that the only problematic column is the "tags" column, right clicking anywhere else selects the folder as expected. Is it the same for you?

**Comment by gave92** [comment]
Possible duplicate: #7208

**Comment by mangoepic** [comment]
> A similar issue suggests that the only problematic column is the "tags" column, right clicking anywhere else selects the folder as expected. Is it the same for you?

https://user-images.githubusercontent.com/71931749/149012345-024e02bd-5d82-47eb-8805-1e3f935890b2.mp4

It happens in any column here

**Comment by gave92** [comment]
Ok it selects correctly unless you click on a column empty space (any text or icon is ok)

**Comment by yaichenbaum** [comment]
This is resolved in `main`.
