### ISSUE TITLE
Files not sorted by sync status after refreshing

### ISSUE THREAD

**Issue by mangoepic** [files-community/Files#7536]
### Description

Refreshing Page: (Same happens when restarting files or switching folders back and forth, the issue only seems to exist for the tags column)

https://user-images.githubusercontent.com/71931749/148963958-30afd9e7-dd5d-42d2-a1a9-da1eb59fc949.mp4

### Steps To Reproduce

-

### Expected behavior

-

### Files Version

Version: 2.1.0.0 

### Windows Version

OS Version: 10.0.22000.194

### Relevant Assets/Logs

-

**Comment by gave92** [comment]
Thanks for the report. Apparently we sort the list before the tags are loaded.

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
