### ISSUE TITLE
Second part of right click always comes late

### ISSUE THREAD

**Issue by mangoepic** [files-community/Files#7537]
### Description

https://user-images.githubusercontent.com/71931749/148966333-216575ee-d3f4-469b-9e9c-050e4e46310d.mp4

The second part of the right click menu always comes late which makes it distracting.

**Ideas to fix this issue:**
 - Make it so you have to scroll down to access the second part of the menu, so there is no immediate visual change when these options get added

 - Hide them under "more"

### Steps To Reproduce

-

### Expected behavior

-

### Files Version

Version: 2.1.0.0

### Windows Version

OS Version: 10.0.22000.194

### Relevant Assets/Logs

-

**Comment by yaichenbaum** [comment]
The alternative is waiting a couple seconds before showing the menu. I think it's better to lazy load the items when the become available instead of waiting to show the menu.
