### ISSUE TITLE
Design clutter

### ISSUE THREAD

**Issue by pedro-gt3250** [files-community/Files#7541]
### What's the Problem?

i think the ui is not as clean as it could be, and the side preview is missing completely, witch is anoying, and there is no way to disable annoying tabs, i hate tabs

### Solution/Idea

thats why i chose to declutter visually the top portion so that its more organized, please copy this concept since its more organized while you add more features as you want, please note that when the user single click the grayed this pc on top, it will go back to the this pc area, when the user double click it, the full path appears and the user is able to copy it... 

see the blank space on top of search? this is the area for tabs, but instead being always on screen, witch is useless when you have only one tab avaliable, it hides itself and they wouldnt appear as big rectagles, but one icon in a square similar to vertical tabs in edge (plus i dont like tabs sooo yea... i would leave this disabled)

the main problem with yours currently, its the ammount of vertical stuff that is cluttering the user experience... there is toooooo much that can be hidden, like lines and search boxes and settings icon and tabs, and buttons... 

its starting to feel weird

![76236y60yzf71](https://user-images.githubusercontent.com/85065672/148984294-cc103a32-6164-4c05-8ae8-264b33bf7409.png)

### Alternatives

there arent really any alternatives

### Priorities

| Capability | Priority |
| Clean design | Show only whats necessary |
| This proposal will allow developers to accomplish their task faster | Must use the design i send to you| 

 This proposal will allow end users to accomplish  (mainly creators) to look at the design of your file explorer and be less confused/frustrated/ annoyed with the organization with everything 

This proposal will allow end users to accomplish disable tabs if they dont use them, and see less of what they dont need, as well as keep the functionality of the left panel (when they click, it expands accordingly) 

i also think this wont, would should to be very confusing... so i just deleted them and wrote like a normal human

### Comments

![image](https://user-images.githubusercontent.com/85065672/148987665-511d8ccf-6962-49f6-bf58-2306c3362777.png)
this was done right when windows 11 released, so there are ui elements that could follow win 11 ui better ...

**Comment by yaichenbaum** [comment]
@pedro-gt3250 thank you for your feedback, you can enable the preview pane from the toolbar button. If you have suggestions for other improvements, please open an individual feature request so we can track each idea separately.
