### ISSUE TITLE
On ARM, Files Unable to Connect to Network Shares

### ISSUE THREAD

**Issue by garyvoth** [files-community/Files#7542]
### Description

Files throws an error when connecting to any network share on my LAN from my Surface Pro X (Windows 11 on ARM). This occurs when I attempt the connection using the share's UNC pathname (e.g. "\\server_name\share_name\") or when I add the share as a network location in File Explorer.  When added as a network location, the share appears in the Files network view, but when connecting a "NotAFolder" error occurs.  (See attached image.)

The only way I have been able to access network locations is if I first map the share to a drive letter. This is an outdated method of working with network shares, so I prefer not to have to do this.

I use the default out of the box network settings for a Private network profile: Network discovery ON, File and Printer sharing ON, 128-bit encryption ON, Password-protected sharing ON. 

All locations are navigable using File Explorer. 

Note that I have verified that Files produces correct behavior on an x64 Intel-based system, so this error is likely related on some differences in Windows on ARM. 

![Files 2 1 Error](https://user-images.githubusercontent.com/45211745/148993135-a08e58dc-e8fe-490b-9887-9c5ef1a5c0af.jpg)
 

### Steps To Reproduce

Using a Windows on ARM client: 

1. Configure Windows for Private LAN on both server and client using default settings
2. Create network share on remote PC.
3. Ensure correct user account and credentials match on server and client
4. Connect to remote share via File Explorer to validate correct behavior
5. Attempt to connect to remote share in Files

### Expected behavior

Files should connect to network share in a manner similar to File Explorer.

### Files Version

Version: 2.1.0.0 (ARM)

### Windows Version

Windows 11 Pro 21H2, 22000.376

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7848860/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7848861/debug.log)

**Comment by gave92** [comment]
Thanks for the report. Was the x64 device you tested also running Windows 11?

**Comment by garyvoth** [comment]
Yes it was, thanks.

Gary

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by garyvoth** [comment]
Also, I noticed the second backslash on the UNC example in my post seemed to go missing. Should read: \\server_name\share_name\.

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
