### ISSUE TITLE
Crash everytime I go to my pictures folder

### ISSUE THREAD

**Issue by Mashilo-FS** [files-community/Files#7543]
### Description

I have the "Show library section" activated, and everytime I use it to my Pictures Folder, it crashes.
For 2 seconds, I can see the content of my folder and freeze for 2 seconds, and the app closes without any crash message or whatever.
And, the weird part, I can go freely to my Picture folder by going to "C:\Users\<me>\OneDrive\Pictures"
Note : I use OneDrive, and my "Pictures" folder in "C:\Users\<me>" is empty.
Note2 : Once I visited "C:\Users\<me>\OneDrive\Pictures", when I use the Pictures button in the side bar, I don't crash anymore

List of files type within my folder : jpg, mp4, png, mov

### Steps To Reproduce

1. Start Files
2. Activated the "Show library section" setting withing the Settings / Sidebar sub-menu
3. Use the "Pictures" button in the Sidebar under the "Libraries" category
4. There you go, I crash

### Expected behavior

I shouldn't crash I think.

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.376

### Windows Version

Windows 11 21H2 22000.376

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7848880/debug.log)

**Comment by gave92** [comment]
Thanks for the report. This issue is fixed in Files v2.1 which is currently in certification for the Store.
