### ISSUE TITLE
Sidebar not showing expanded groups on start

### ISSUE THREAD

**Issue by aleksanderlukasiewicz** [files-community/Files#7546]
### Description

Sidebar does not show groups that were previously expanded

### Steps To Reproduce

1. Open Files
2. Expand group in sidebar
3. Close Files
4. Open again

### Expected behavior

Expanded groups should be visible after start 

### Files Version

Version: 2.1.0.0 OS Version: 10.0.22000.376v

### Windows Version

Windows 11 21H2 OS Version: 10.0.22000.376

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/69370471/149025075-98a17410-dd21-4796-a7ca-caf174329324.png)

**Comment by gave92** [comment]
Merging with #6469
