### ISSUE TITLE
Unable to Debug Files

### ISSUE THREAD

**Issue by EyreC** [files-community/Files#7547]
First time contributor here. Am not sure where is best to ask how to debug Files in Visual Studio as I am facing some trouble. I hope it is fine to raise it this way; if not please do let me know where is more appropriate.

I am using Visual Studio 2022 with the UWP development  workload, and the C++ v143 build tools.

However when launching the app (x64) in VS I get a InvalidOperationException when accessing any property on the ApplicationData object. 

I've followed the instructions here: https://files.community/docs/contributing/building-from-source

Can't find any obvious StackOverflow posts explaining why I get this error and how to resolve it. Am new to UWP development.

Am looking forward to picking up a 'good-first-issue' and would be grateful for some help!

**Comment by gave92** [comment]
Hi thanks for your interest in Files! Please make sure you have set "Files.Package" as startup project (point 3). If you still have trouble please let us know. You can also reach us on [Discord](https://discord.com/invite/files).
