### ISSUE TITLE
Is it possible to download this files program without having win 11 and neither windows store?

### ISSUE THREAD

**Issue by lenti21** [files-community/Files#7549]

**Comment by yaichenbaum** [comment]
You can sideload the app using the package from the release page https://github.com/files-community/Files/releases/tag/v2.1.

**Comment by lenti21** [comment]
> You can sideload the app using the package from the release page https://github.com/files-community/Files/releases/tag/v2.1.

I installed the zip, now how do i enable it dont know which pack or file i should click on?

**Comment by yaichenbaum** [comment]
@lenti21 did you install the msixbundle?

**Comment by lenti21** [comment]
This is what i downloaded:
![image](https://user-images.githubusercontent.com/96147828/149320822-6ba3a3d4-1cb8-4eea-98bf-f135226d9d16.jpeg)

**Comment by yaichenbaum** [comment]
@lenti21 you can double click the msixbundle to install Files.

**Comment by lenti21** [comment]
Hmm, it doesnt let me download tho. On the picture it says its a problem with app installer. ![image](https://user-images.githubusercontent.com/96147828/149375687-ad9c625b-3583-4a43-b55e-907bd4248c9b.jpeg)

**Comment by yaichenbaum** [comment]
@lenti21 can you translate the error?
