### ISSUE TITLE
I have updated the latest version, but copy and paste is still not available

### ISSUE THREAD

**Issue by Fannzc** [files-community/Files#7550]
### Description

I have updated the latest version, but copy and paste is still not available

### Expected behavior

Fix copy and paste

### Files Version

版本: 2.0.34.0 OS Version: 10.0.22000.376

### Windows Version

版本	Windows 11 专业版 版本	21H2 安装日期	‎10.‎16 ‎周六 操作系统版本	22000.376 体验	Windows 功能体验包 1000.22000.376.0

### Relevant Assets/Logs

.

**Comment by josh-65** [comment]
What files/folders are you copying.
Where are they being coped from (network, local drive, external drive, external device)
Are you using drag and drop or right click menu
You will need to upload the logs files. You can get them in files settings > about > open log folder.

**Comment by gave92** [comment]
#7459
