### ISSUE TITLE
[feature request] Add recently used folders to the sidebar

### ISSUE THREAD

**Issue by M09Ic** [files-community/Files#7553]
### What's the Problem?

I switch between frequently used working directories every once in a while. In windows, the most recently used folder is automatically recorded in `quick access`, so I want to use it in files as well.

![image](https://user-images.githubusercontent.com/29176200/149086548-fb7d2750-7fc1-4c92-9bc7-948632e3b14e.png)

### Solution/Idea

Add recently used folders to the sidebar

### Alternatives

__

### Priorities

No response

**Comment by yaichenbaum** [comment]
The sidebar is meant to access frequent folders rather than recent folders. We're working a recent items page where you will get a richer view of recent folders and you will be able to pin this page to the sidebar and if you want, you'll also be able to set it as the home page.
