### ISSUE TITLE
Nothing in the sidebar

### ISSUE THREAD

**Issue by Stapxs** [files-community/Files#7554]
### Description

PS: I'm not good in English

- Just nothing in the sidebar, as shown in the picture

![image](https://user-images.githubusercontent.com/42486439/149089613-52749e1c-2b15-4006-9a3e-1cf61fe1cfff.png)

### Steps To Reproduce

I installed it from the Microsoft store and the first time I opened it had this problem. Rebooting didn't improve it.

PS: The error message is when I try to solve the problem by switching the item in Settings > Sidebar

### Expected behavior

Show folders such as launchers in the sidebar

### Files Version

Version: 2.1.0.0 OS Version: 10.0.22526.1000

### Windows Version

Windows 11 Pro Insider Preview 22526.1000

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7852899/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7852900/debug_fulltrust.log)

**Comment by Gryzle** [comment]
I had this glitch too. For whatever reason, Files was unable to load ANY files, including the C:\ Drive. I had to uninstall and reinstall to fix this.

**Comment by Stapxs** [comment]
> I had this glitch too. For whatever reason, Files was unable to load ANY files, including the C:\ Drive. I had to uninstall and reinstall to fix this.

Reinstalling it didn't work for me …

**Comment by WuYoTing** [comment]
me either! can't load any drive from my pc , maybe will reinstall v2.0.34 first
![image](https://user-images.githubusercontent.com/38146901/149248751-c9d8a483-95bd-49ed-8f84-74b9816a44ac.png)

**Comment by Tarek-Hasan** [comment]
It seems minimizing and then restoring the app temporary solves the issue.

**Comment by arandommudkip** [comment]
Confirming the same issue on Windows 10, version 21H1 , OS build 19043.1466.

Tarek's solution above works.

**Comment by yaichenbaum** [comment]
@Stapxs is this still an issue in the preview version? https://files.community/download/preview

**Comment by Stapxs** [comment]
Sorry I didn't see the query 😖
It seems that this problem will not appear in the latest version
Thanks a lot for fixing it
