### ISSUE TITLE
Suggestions on privacy protection and Copy/Paste function

### ISSUE THREAD

**Issue by zane-ng** [files-community/Files#7559]
### What's the Problem?

1. The current app records any recently opened files no matter what, and there is no option to completely turn it off. The 'Recent Files' widget can be turned off. However, when turned on, it still shows recordeds of recent files during the period when the widget is turned off.
This can easily cause damage to user privacy. 

1. The current Copy/Paste function is weak compared to Windows' original function, considered that Windows provide a detailed window showing the progress and speed, helping the users to monitor the progress. Users can see whether there is any underlying issue of the hardware, and can decide whether to wait or doing other things in the meantime, etc.
However, this app hides the Copy/Paste progress rather deep, making it rather difficult to monitor the progress. Users wouldn't easily know how fast or slow it is, and why it is. With Windows' original function, the progress is slow, user can easily tell what file or path is causing the issue.
The current app also doesn't support software such as TeraCopy. That is, even TeraCopy is installed and set as the default copy/paste manager, the app uses its own function nonetheless with so much less functionality compared to TeraCopy or alike.

### Solution/Idea

For problem 1: Simply provide the option to stop recording 'recent files' at all.

For problem 2: 

1. Simply use the original Windows copy/paste function.
2. Coordinate with apps like TeraCopy to provide integration.
3. Redeign the current copy/paste progress function: simply copy/redo the current design of the Windows' progress window, but put it into a pane or tabs that're at the bottom of the app, with the same kind of info. The pane will stay there as long as there is any such progress, but can be manually collaped into smaller squared tabs with progress rings and percentage on each tab.

### Alternatives

For problem 2, alternatively, design an internal copy/paste function that's similar to or better than software like TeraCopy. This can be sold as an paid package with a price that's similar to TeraCopy.

However, this option should only be pursued when the above solutions have been pursued first.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Solution to problem 1 | Must |
| Solution 1 and 3 to problem 2 | Should |
| Solution 2 and alternative solution to problem 2 | Could |

### Comments

This app is great, and thank you for making it free to use. The mentioned problems are are currently prevent me from using this app on regular basis.

**Comment by gave92** [comment]
Thanks for the suggestions. We're tracking these items in #5882, #7518, #4811
