### ISSUE TITLE
Pfff

### ISSUE THREAD

**Issue by samtris** [files-community/Files#7560]
Bonjour,
je souhaite désinstaller le logiciel mais il n'y a pas d'option dans les paramètres, le fichier "files" ne se trouve pas dans paramètres windows / désinstaller un programme. Belle galère pour retirer le logiciel... Impossible de contacter le créateur, pas de FAQ réel...
la merde totale !

**Comment by JordyEGNL** [comment]
If you installed Files via the Microsoft Store you can find it under Settings > Apps > Apps & features
![image](https://user-images.githubusercontent.com/65036298/149121929-85342113-3e89-46d8-9fed-f707588b6720.png)

**Comment by boscorelly** [comment]
> Bonjour, je souhaite désinstaller le logiciel mais il n'y a pas d'option dans les paramètres, le fichier "files" ne se trouve pas dans paramètres windows / désinstaller un programme. Belle galère pour retirer le logiciel... Impossible de contacter le créateur, pas de FAQ réel... la merde totale !

je vais prendre la peine de te répondre en français, même si la langue usuelle est l'anglais.
déjà, tu pourrais prendre la peine d'écrire en anglais.
Ensuite, visiblement, il y a un défaut de formation, puisque les applications du store se désinstallent via le store. Du coup, c'est logique de passer par là.
ensuite, le principe des logiciels où tout le monde collabore, c'est... la collaboration !
du coup si la faq ne te convient pas, je t'invite à y participe, comme ça tu ne pourras pas dire que ça ne te convient pas.

avec un peu de recherche, tu aurais trouvé la manipulation de @JordyEGNL
avec un peu de recherche aussi, tu aurais pu trouver autrement :
`Get-AppxPackage -Name *files*`
Name              : 49306atecsolution.FilesUWP
Publisher         : CN=53EC4384-7F5B-4CF6-8C23-513FFE9D1AB7
Architecture      : X64
ResourceId        :
Version           : 2.1.0.0

`Get-AppxPackage -Name *files* | Remove-AppxPackage`

voilà voilà.
je te laisse fermer l'issue.

**Comment by yaichenbaum** [comment]
> Hello, I want to uninstall the software but there is no option in the settings, the file "files" is not in windows settings / uninstall a program. Nice hassle to remove the software... Unable to contact the creator, no real FAQ... total shit!

Thank you for your question, like any other store app, you can right click in the start menu and press on uninstall. You can also find it in the app section in the Windows Settings app.
