### ISSUE TITLE
Network drives in bundles

### ISSUE THREAD

**Issue by boscorelly** [files-community/Files#7561]
### Description

The name of the folder is not diaplayed if the folder is a network drive, but clicking on the folder is working.

### Steps To Reproduce

Create a bundle
link a network drive as a folder

### Expected behavior

Display name of network drive in the bundle list

### Files Version

2.1.0.0

### Windows Version

Windows 11 21H2

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/3873787/149139533-01d1f150-8405-4d06-9928-87278ea9b807.png)

**Comment by jonluu1** [comment]
New to open source, happy to take this on.

**Comment by Bayrem00** [comment]
This is happening because of changes in .Net 5 to` System.IO.Path.GetFileName`, as discussed [here](https://github.com/dotnet/runtime/issues/48039).

The issue also arises when a drive is selected as a folder, i will create a PR with a fix suggestion
