### ISSUE TITLE
2.1 still doesn't work with Box without flashing

### ISSUE THREAD

**Issue by sdel85** [files-community/Files#7562]
### Description

My last bug report on this was closed because it was supposed to be addressed in the last release. This issue still exists with Box.

### Steps To Reproduce

1. Open files.
2. Select your Box drive
3. The files displays continually refresh, preventing any actual work from being performed.

### Expected behavior

It should display like any other drive (C: D: or OneDrive)

### Files Version

2.1.0.0

### Windows Version

Windows 10 Enterprise (OS Build 19044.1415)

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7854801/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7854802/debug_fulltrust.log)

**Comment by gave92** [comment]
Thanks for the update, we know this is still an issue -> tracked in #7428
