### ISSUE TITLE
Add a Properties Button to the Toolbar

### ISSUE THREAD

**Issue by AJLeuer** [files-community/Files#7563]
### What's the Problem?

As a Files user, when I have a file or folder selected, I expect to be able to be able to choose common actions to perform on it in the toolbar, including viewing its properties.

### Solution/Idea

Add a properties button to the toolbar.

Viewing the properties of an item is one of the most fundamental interactions that a user can perform, on par with deleting or renaming. I'd argue it's even more fundamental than the _Share_ function, and even that has its own button on the toolbar. So with that in mind, there ought to be a _Properties_ button on the toolbar.

### Alternatives

Since _Properties_ can already be accessed through the context menu, the most obvious alternative is to do nothing.

### Files Version

2.1

### Windows Version

Windows 11 21H2 22000.376

**Comment by AJLeuer** [comment]
I've implemented this change on my own fork and I'm working on opening a pull request at the moment.

**Comment by yaichenbaum** [comment]
> I've implemented this change on my own fork and I'm working on opening a pull request at the moment.

Thank you!
