### ISSUE TITLE
Global Save sorting / Group settings

### ISSUE THREAD

**Issue by ERGPOL** [files-community/Files#7565]
### What's the Problem?

Sorting and / or Group settings will not affected to all Folders (tested in Columns view)

have to set every time sorting and grouping

### Solution/Idea

checkbox to overtake setting as global setting with overwriting all exisitings settings

### Alternatives

--

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.0

### Windows Version

Windows 11

**Comment by gave92** [comment]
@ERGPOL could you check if turning off "enable individual preferences for folders" option under settings > preferences does the job (might not affect column view)?

@Futureblur that issue is fixed in Files v2.1 that was just released 👍

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?
