### ISSUE TITLE
Downloads folder shows nothing when group by is set to "date created" or "date modified"

### ISSUE THREAD

**Issue by Futureblur** [files-community/Files#7568]
### Description

When setting group by to "date created" or "date modified" in the "Downloads" folder and refreshing or re-opening the app, the downloads folder is completely empty. Nothing gets deleted though, it's only a display issue. When setting group by to something else, it seems to display everything correctly.

### Steps To Reproduce

1. Open Files
2. Go to "Downloads" folder
3. Click on "Sort" button on the top right (arrow up and down icon)
4. Hover over "Group By"
5. Select either "Date created" or "Date modified"
6. Optional: Hit F5 to refresh or close and re-open the app
7. All items in the "Downloads" folder suddenly disappear

### Expected behavior

The items in the "Downloads" folder should be grouped by the date they are created or modified at (depends on which option you chose), similarly on how you would group by other categories.

### Files Version

Version: 2.0.34.0

### Windows Version

OS Version: 10.0.19042.1415

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/61380971/149167734-5a20fb47-a91c-4708-b44c-25a215dbb5e9.png)

**Comment by yaichenbaum** [comment]
This issue is resolved in v2.1. You can ge the update from the Microsoft Store.
