### ISSUE TITLE
Uninstalled Cloud Service (Dropbox) folder is still visible in "cloud drives" section of the sidebar after deletion

### ISSUE THREAD

**Issue by Crwmy** [files-community/Files#7572]
### Description

First of all, congratulations on Version 2.1! It feels much more refined (especially when using it as default).

Now to my "problem" which is more of an inconvenience: I would like to have my uninstalled and deleted Dropbox folder removed from the "Cloud Drives" section of the sidebar. 

Although this report fits in the larger context of costumization requests (#6815),  I have not seen this particular bug report in the Issues when searching. My goal with this report is simply pointing out another usecase for that costumization and maybe point out an actual bug here.

(I know that reinstalling Files likely will solve the issue, but before doing this I wanted to report and see if further info is required.)

### Expected behavior

When uninstalling a cloud service (like Dropbox) and deleting the sync folder, it should also be deleted in the sidebar

### Files Version

2.1.0.0

### Windows Version

22000.434

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/91319158/149209783-c9706640-027e-42c9-8196-47d33c93c9bd.png)
[7572_crwmy_debug_fulltrust.log](https://github.com/files-community/Files/files/7857369/7572_crwmy_debug_fulltrust.log)
[7572_crwmy_debug.log](https://github.com/files-community/Files/files/7857374/7572_crwmy_debug.log)

**Comment by gave92** [comment]
Thanks for the kind feedback. Dropbox still appearing means that it did not fully uninstall itself.
Try to delete the "%localappdata%\\dropbox" folder and it will be gone from Files sidebar.
