### ISSUE TITLE
Some Environment Variables are not accessible via Win + R when Files is set as the default file manager.

### ISSUE THREAD

**Issue by oleklukasiewicz** [files-community/Files#7574]
### Description

%APPDATA%,
%LOCALAPPDATA% 

are not accessible via Win + R when Files is set as the default file manager.

### Steps To Reproduce

1. Set Files as default file manager
2. Launch run
3. Type %LOCALAPPDATA%  or %APPDATA%

### Expected behavior

Files should open these folders like %HOMEPATH%

### Files Version

Version: 2.1.0.0 OS Version: 10.0.22000.376

### Windows Version

Windows 11 21H2  22000.376

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/69370471/149220038-358f776c-7868-4e67-800a-f604988e2739.png)
![image](https://user-images.githubusercontent.com/69370471/149220060-ef1c833a-c42a-4bba-b21b-853eede68017.png)

**Comment by yaichenbaum** [comment]
@aleksanderlukasiewicz try typing `Files %appdata%`

**Comment by gave92** [comment]
Explorer++ when set as default is able to open %appdata%. Given that it uses our same method we should be able to do it as well. Funnily accessing %appdata% subfolders works correctly.

**Comment by yaichenbaum** [comment]
This issue should be resolved with https://github.com/files-community/Files/pull/8684
