### ISSUE TITLE
High Memory/CPU usage issue

### ISSUE THREAD

**Issue by Andy-2732** [files-community/Files#7575]
### Description

New user, noticed very high resource usage. Files is open with a couple of tabs, but no operations active. Earlier it was using 14+gb of RAM until I closed from Task manager. Please let me know if any further info would be helpful.

Edition	Windows 11 Pro
Version	21H2
OS build	22000.434
Files 2.1.0.0

![image](https://user-images.githubusercontent.com/92577745/149222254-5f6b4a24-2373-48a7-91d3-a70250cd1094.png)

### Steps To Reproduce

I'm not sure in this case. First noticed when performing a search.

### Expected behavior

Lower RAM usage for sure

### Files Version

Version: 2.1.0.0 OS Version: 10.0.22000.434

### Windows Version

Windows 11 Pro Version	21H2

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/92577745/149221626-65dbe07c-75bc-48a9-8b6e-d6a66ec6b02a.png)

**Comment by Andy-2732** [comment]
Seems to be heavily spamming my drives too. Is there some sort of built in Indexer, or does it use the Windows search index?

**Comment by yaichenbaum** [comment]
It uses the Windows APIs so we aren't running our own indexer. Most of the memory usage comes from bad code or memory leaks in the platform controls. We're making an effort to reduce the performance impact, please subscribe to #4180 to follow the progress.

**Comment by yair100** [comment]
@ALittleCremeFraiche we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
