### ISSUE TITLE
Crashed when trying to modify compress file using 7-zip file manager

### ISSUE THREAD

**Issue by Sunrise521** [files-community/Files#7576]
I am using Windows 11 pro 21H2 and the latest version of _Files_.
When I try to modify files inside a zip file using the 7-zip file manager, It occasionally crashed and outputs "Cannot rename file or folder: Wrong function". 
![image](https://user-images.githubusercontent.com/22720058/149232854-929e0876-e49e-4d3b-b1d6-c8194aa3a69e.png)
As the result, the new version of the zip file was saved as ***.zip.tmp and the original zip file becomes empty.
![image](https://user-images.githubusercontent.com/22720058/149232670-f8ec7c8b-b5ec-48fd-ba8d-4b74b16b7f06.png)

Moreover, I found that It only occurs when the path of the file being modified is opened.

**Comment by josh-65** [comment]
What version of files are you using latest is not a version. Settings > about
You will need to upload the logs files. You can get them in files settings > about > open log folder.

**Comment by Sunrise521** [comment]
> 

Thanks for your reply.
I am using the 2.1.0.0 version from the Windows store.

Here is the log file:

[debug_fulltrust.zip](https://github.com/files-community/Files/files/7861188/debug_fulltrust.zip)

**Comment by Josh-65** [comment]
Is this still an issue if you use 2.3.0.0?

**Comment by yaichenbaum** [comment]
I can't reproduce this in v2.3, if it's still an issue on your end, can you check if it's an issue in File Explorer as well?
