### ISSUE TITLE
Use Cloud drives without installing different software

### ISSUE THREAD

**Issue by upintheairsheep** [files-community/Files#7578]
### What's the Problem?

Please. Just fix the name of this post.

Different software you have to install to get access to cloud storage also eat processing power and take a long time. We can solve that by making you be able to log in cloud services via their API.
Support:
*Google Drive
*OneDrive
*iCloud Drive
*Dropbox
*Box
*MEGA
*MediaFire
*Calyx cloud

### Solution/Idea

Add support to log in to cloud services via this app. Their API allows it.
Support:
*Google Drive
*OneDrive
*iCloud Drive
*Dropbox
*Box
*MEGA
*MediaFire
*Calyx cloud

### Alternatives

Installing all the software

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Not installed because my laptop has a slow hard drive.

### Windows Version

Android 10.0 "Queen Cake", planning to get a PC

**Comment by upintheairsheep** [comment]
Also add:
*iCloud Photos
*Google Photos
*Google Contacts
*Google Calender
*iCloud Contacts 
*iCloud Calender
*Microsoft Contacts, Calender, and to do 
*iCloud iOS Backup
*Google Drive Android Backup

**Comment by Josh-65** [comment]
Should note that the extras in your comment are not cloud drives.

**Comment by Josh65-2201** [comment]
@yair100

**Comment by yaichenbaum** [comment]
Thank you for your feedback, maintaining each API is a project on its own and we don't have the bandwidth to support this.
