### ISSUE TITLE
Add support for Mobile device exploration

### ISSUE THREAD

**Issue by upintheairsheep** [files-community/Files#7579]
### What's the Problem?

Mobile devices are getting bigger by the day. Browsing the phone's internal files are hard without jailbreak that voids your warranty or root, that you litterly have to do a factory reset to accomplish. And file transfers are hard and backups are great way to solve the problem, but they are hard to view without forensic software or closed source paid personal software.

### Solution/Idea

Add support for browsing mobile phones by adding a new category, the Mobile category. Here, mobile devices pop up here. For iOS devices, it will have a few folders for different jobs. One folder is the Backup folder and allows to browse the iTunes backup of the device, and if there is no backup, prompt for it and open iTunes. The next folder is photos which displays photos. The next folder is iTunes file transfer that browses apps that support iTunes file transfer. The last folder is logs, which allows you to view your logs of the iOS device. For Android, you can make and view ADB backups, and browse the root for rooted devices.

### Alternatives

iMazing, my main tool to do this eats resources and the UI is dated on windows

Android backup extractor requires the command line and Java.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by upintheairsheep** [comment]
And on Android, check

**Comment by upintheairsheep** [comment]
http://fileformats.archiveteam.org/wiki/Android_ADB_Backup for more information on ADB backups and flags that you can use to backup.

**Comment by josh-65** [comment]
On Android this is already a thing. As for IOS, iTunes for PC is used for backups and browsing. No idea if this a apple force limitation but properly is.

**Comment by yaichenbaum** [comment]
Thank you for opening this feature request, this falls outside our plans for Files and we won't be implementing it.
