### ISSUE TITLE
Inconsistency between file creation flyouts.

### ISSUE THREAD

**Issue by Tropix126** [files-community/Files#7581]
### Description

The order of items on the New File menu opened from the toolbar seems to be slightly different from the one opened from a context menu.

### Steps To Reproduce

Click the "New" command in the toolbar.
Right click in any area that opens a context menu and choose the "New" option.

### Expected behavior

Flyouts should maintain a consistent order of items.

### Files Version

2.1

### Windows Version

Windows 11 22509.1011

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/42101043/149256447-30009851-23c8-48aa-8a01-c80c1fc845dd.png)
![image](https://user-images.githubusercontent.com/42101043/149256420-6fb05a34-629e-4c21-bce9-12885253fa65.png)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7618
