### ISSUE TITLE
Deleting Temporary Files

### ISSUE THREAD

**Issue by rifkyaprasetya** [files-community/Files#7582]
### Description

Files went error after i deleted temporary files in run

### Expected behavior

I expected the files don't error after deleting temporary files.

### Files Version

Version 2.1.0.0

### Windows Version

Windows 11 21H2 OS Build 22000.434

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7859565/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7859566/debug.log)

**Comment by yaichenbaum** [comment]
@rifkyaprasetya is this still an issue in the preview version? https://files.community/download/preview
