### ISSUE TITLE
Feature: Metadata editing - Audio file album cover modification

### ISSUE THREAD

**Issue by Neptune-mk2** [files-community/Files#7585]
### What's the Problem?

Currently even in the standard file explorer one is not able to edit the album cover image in various types of audio files

### Solution/Idea

Once metadata editing is implemented, in the same area add the option to replace the album cover when a format is compatible (ex. mp3, aac, .flac)

Optional - Have a preview of the image in the metadata entry area

### Requirements
- Dim album cover when hovering over it with mouse (referring to the properties page)
- On hover, display "edit" icon in the center of the photo
- Clicking the image should open a file picker and allow the user to select a different photo
- Support updating multiple files at a time

**Comment by yaichenbaum** [comment]
@Neptune-mk2 where would you expect the option to be? I'm thinking that it can be an option when rightclicking thethumbnail in the properties dialog but perhaps there is a better way.

**Comment by Neptune-mk2** [comment]
> @Neptune-mk2 where would you expect the option to be? I'm thinking that it can be an option when rightclicking thethumbnail in the properties dialog but perhaps there is a better way.

I think to not clutter the context menu, it could be a additional option at the top of the metadata section in properties.

**Comment by yaichenbaum** [comment]
> > @Neptune-mk2 where would you expect the option to be? I'm thinking that it can be an option when rightclicking thethumbnail in the properties dialog but perhaps there is a better way.
> 
> I think to not clutter the context menu, it could be a additional option at the top of the metadata section in properties.

There currently isn't any context menu in the properties dialog, this would be a new context menu with the option to paste an image.

**Comment by Neptune-mk2** [comment]
> > > @Neptune-mk2 where would you expect the option to be? I'm thinking that it can be an option when rightclicking thethumbnail in the properties dialog but perhaps there is a better way.
> > 
> > 
> > I think to not clutter the context menu, it could be a additional option at the top of the metadata section in properties.
> 
> There isn't any context menu in the properties dialog, this would be a new context menu with the option to paste an image.

My bad I misunderstood , in that case that would work great!

**Comment by yaira2** [comment]
An alternative could be to open a file picker when clicking the thumbnail.

**Comment by yaira2** [comment]
@Neptune-mk2 I updated the requirements and I'm marking this as "ready to build".
