### ISSUE TITLE
After creating a new folder, it should be selected in the Files Explorer

### ISSUE THREAD

**Issue by rajendrasp** [files-community/Files#7586]
### Description

When I create a new folder, the focus goes to first tab in the Explorer. Instead the newly created folder should be selected so that it can be opened quickly.
Once a new folder is created most likely we want to navigate to that folder to do something inside it. But changing focus to first tab makes no sense. Please fix this

### Steps To Reproduce

Create a new folder using New button inside Explorer
check that we can open that folder right away by pressing Enter key because focus is on first tab.

### Expected behavior

Newly created folder should be selected in the Explorer view

### Files Version

Version: 2.1.0.0 OS Version: 10.0.22000.434

### Windows Version

Windows 11 21H2 OS Build 22000.434

### Relevant Assets/Logs

NA

**Comment by DefiniteCoding** [comment]
This is very true, I wish this functionality is enabled by default akin to the default Windows File Explorer!

Appreciate your work @yair100 on Files very much, promise to support you next month.

**Comment by yaichenbaum** [comment]
@rajendrasp merging with #5464 

@DefiniteCoding thank you!
