### ISSUE TITLE
Feature: Bigger breadcrumb touch targets for path of folder open in Explorer

### ISSUE THREAD

**Issue by rajendrasp** [files-community/Files#7587]
### What's the Problem?

The size of breadcrumb buttons on the navigation bar is small and it is sometimes hard to click exactly the right folder especially if the folder name is small. Please see the image below

![image](https://user-images.githubusercontent.com/51284446/149281133-cfad9df4-900b-4f5d-83b3-105df00bb941.png)

Can we increase this size of breadcrumb buttons? Maybe set a minimize size for them so that irrespective of folder name, there is enough size on the button. Also I think if we reduce padding/margin on this button, it would be better. Otherwise can we increase the height of the entire navigation bar so that there is enough height on the button. 
The look of the navigation button is also not aligned with the rest of UI because of this size/height issue.

### Solution/Idea

Can we increase this size of breadcrumb buttons? Maybe set a minimize size for them so that irrespective of folder name, there is enough size on the button. Also I think if we reduce padding/margin on this button, it would be better. Otherwise can we increase the height of the entire navigation bar so that there is enough height on the button. 
The look of the navigation button is also not aligned with the rest of UI because of this size/height issue.

### Alternatives

Can we increase this size of breadcrumb buttons? Maybe set a minimize size for them so that irrespective of folder name, there is enough size on the button. Also I think if we reduce padding/margin on this button, it would be better. Otherwise can we increase the height of the entire navigation bar so that there is enough height on the button. 
The look of the navigation button is also not aligned with the rest of UI because of this size/height issue.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.1.0.0 OS Version: 10.0.22000.434

### Windows Version

Windows 11 21H2 OS Build 22000.434

**Comment by rajendrasp** [comment]
Just adding a reference image that will help. Please note the height of the icon on the left and the space at the top and bottom of the text of the breadcrumb. That space is does not look proper. Just my opinion.

![image](https://user-images.githubusercontent.com/51284446/149287578-43205a71-cca0-4ede-944b-23cd3b7f854e.png)

**Comment by starkgate** [comment]
I do not have this issue. For me the size of the breadcrumbs is fine and easily accessible (1080p screen). You can click on all of this space to open it:
![Files_AlmMUOR4Y0](https://user-images.githubusercontent.com/12874678/149309201-8d23b186-2234-431c-be17-7ddf89ee2bec.png)
