### ISSUE TITLE
Option to open complete path of favorite folder in "Columns" view

### ISSUE THREAD

**Issue by rajendrasp** [files-community/Files#7589]
### What's the Problem?

I have selected "Layout" option as "Columns"
Currently when I open a folder that is added to favorite from the favorites section, It opens only that folder in the leftmost column like below.

![image](https://user-images.githubusercontent.com/51284446/149293863-69727aa9-c66d-4f46-8674-b770f7191be2.png)

I would like some option in settings to open the folder including its parents in four columns with the target folder in rightmost column like seen below

![image](https://user-images.githubusercontent.com/51284446/149294152-90bddb48-0b67-4c87-bb22-c8fbf8122a07.png)

### Solution/Idea

Please can you add option in settings to make this feature available.

### Alternatives

You can make this default method to open folder when Column is the selected layout.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.1.0.0 OS Version: 10.0.22000.434

### Windows Version

Windows 11 21H2 OS Build 22000.434

**Comment by yaichenbaum** [comment]
How is this handled in Mac OS?

**Comment by hishitetsu** [comment]
As discussed in #9769, any folder pinned to favorites should start from the directory and everything else from root.
However, the behavior of the operation history and focusing the parent folder column should be as it is.

@yair100 Is it now ready to build? I think it will resolve #6902 and #11128 too.

**Comment by yaira2** [comment]
Yes
