### ISSUE TITLE
Task-Bar Pins

### ISSUE THREAD

**Issue by SakethKanchi** [files-community/Files#7590]
### What's the Problem?

I pin some folders to taskbar icon. From where I could just right click and access it.
![image](https://user-images.githubusercontent.com/70198692/149294177-b7498590-9149-4290-b982-0ccb85d417d6.png)

### Solution/Idea

Allow users to pin folders or applications on the taskbar.

### Alternatives

Instead of bundles allow users to add a single folder or a file. Which occupy the space and size as these:
![image](https://user-images.githubusercontent.com/70198692/149294652-0ae45f6f-5df3-4654-b8d8-4413a09aee3b.png)

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.1.0.0 OS Version: 10.0.22000.376

### Windows Version

Windows 11 Pro 21H2 22000.376

**Comment by yaichenbaum** [comment]
Merging with #6596
