### ISSUE TITLE
Files in network drives does not update automatically

### ISSUE THREAD

**Issue by MaddPenguin** [files-community/Files#7591]
### Description

I created a new folder in my network drives, but it is not showing after creation. I need to manually refresh for it to appear. Same with delete, cut, and paste. Also not working with the secondary pane.

### Expected behavior

Files in the view to be automatically updated on creation or deletion.

### Files Version

Version: 2.1.0.0 OS Version: 10.0.22000.434

### Windows Version

22000.434

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/60058928/149296749-d20aafb8-1cb5-444d-871f-82019ae16a49.png)

Folder only appears after manually refrehed

![image](https://user-images.githubusercontent.com/60058928/149296856-9eef17c9-73a0-4806-9f0f-92e6a4ae7170.png)

**Comment by starkgate** [comment]
I noticed the same thing when creating, copying or moving files to/from network drives. The view isn't updated automatically, unlike in Windows Explorer.

**Comment by gave92** [comment]
Tracked in #5869
