### ISSUE TITLE
FilesFullTrust has stopped working

### ISSUE THREAD

**Issue by Rafael000000** [files-community/Files#7592]
### Description

When I try to access the themes folder from Files, or when I try to go anywhere in the %appdata% folder FilesFulltrust stops working.
And when I try to copy and paste the path to the themes directory Files says that it doesn't exist.

### Steps To Reproduce

Open Files
Copy and paste: %appdata%\Local\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState\Themes
For it says it does not exist
#------------------------------------------
Open Files
Go to %appdata%\Local\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState\Themes
try to copy and paste, or delete 
It crashes for me

### Expected behavior

I expect not to get the FilesFullTrust error and that I can copy and paste in every directory I have permission to do so.

### Files Version

Version: 2.1.0.0 OS Version: 10.0.19043.1466

### Windows Version

Windows 10 21H1 19043.1466

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7861662/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7861663/debug.log)

**Comment by gave92** [comment]
Did you install the app from Store?

**Comment by gave92** [comment]
S*it @yaichenbaum does the store use the same .net sdk version as sidelined version? If it uses 6.0.101 instead of 6.0.100 fulltrust process is broken for everyone.

**Comment by Rafael000000** [comment]
@gave92 I installed via winget, so I think the app store version

**Comment by gave92** [comment]
Could you test with the sideloaded version? From here: https://filescommunity.blob.core.windows.net/files/stable/Files.Package_2.1.0.0_Test/Files.Package_2.1.0.0_x86_x64_arm64.msixbundle

**Comment by Rafael000000** [comment]
@gave92 I will, give me a couple minutes

**Comment by Rafael000000** [comment]
@gave92 It is working correctly now!

**Comment by Rafael000000** [comment]
Good luck😱!! And keep up the great work. I love the look and feel of the file manager!

**Comment by Rafael000000** [comment]
Should I close the issue or leave it open?

**Comment by gave92** [comment]
Leave it open, thanks. We'll close this once it's fixed. 👍

**Comment by yaichenbaum** [comment]
> Uh ho @yaichenbaum does the store use the same .net sdk version as sideloaded version? If it uses 6.0.101 instead of 6.0.100 fulltrust process is broken for everyone.

It should be the same but it's possible the store does its own thing.

**Comment by gave92** [comment]
We set the sdk version only in the CI files. I think we need to put it "globals.json".
