### ISSUE TITLE
List view

### ISSUE THREAD

**Issue by SarreqTeryx** [files-community/Files#7594]
### What's the Problem?

I'd like to see a List view (or Compact view, as some Linux FMs call it).

### Solution/Idea

add a list view

### Alternatives

sticking with File Explorer

### Files Version

2.1.0.0

### Windows Version

11 22000.434

**Comment by josh-65** [comment]
Same as #1928

**Comment by yaichenbaum** [comment]
Merging with #2509

**Comment by yaira2** [comment]
@SarreqTeryx thank you for your patience, I'm excited to share that a List View layout will be included in the next release.
