### ISSUE TITLE
Folder Tree in left pane

### ISSUE THREAD

**Issue by SarreqTeryx** [files-community/Files#7595]
### What's the Problem?

I make extensive use of the Folder Tree in Explorer, so for Files not to have it is problematic.

### Solution/Idea

add a folder tree option to the left pane

### Alternatives

stick with file explorer

### Files Version

2.1.0.0

### Windows Version

11 22000.434

**Comment by josh-65** [comment]
Same as #1928

**Comment by yair100** [comment]
@SarreqTeryx Tree View is currently available in preview https://files.community/download. It will be included in the next stable release.
