### ISSUE TITLE
Files opens then closes immediately

### ISSUE THREAD

**Issue by richeaston** [files-community/Files#7596]
### Description

I've change the default file explorer to use files, and when I open it, it immediately closes, and won't allow access to explore anything.

what registry entries does it change to change the default explorer so I can change explorer.exe back to the default

### Steps To Reproduce

1. open files (immediately closes

### Expected behavior

Not expected behavior

### Files Version

2

### Windows Version

Windows 10 21h2

### Relevant Assets/Logs

can't navigate to the location as files crashes

**Comment by josh-65** [comment]
You can use the UnsetFilesAsDefault.reg file in this.
https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip

**Comment by gave92** [comment]
Thanks for the report. After you restore explorer we'd be grateful if you cound upload the debug logs so we can understand the issue. Could you also confirm what Files version are you using (v2.1)?
