### ISSUE TITLE
Columns view truncation

### ISSUE THREAD

**Issue by SarreqTeryx** [files-community/Files#7597]
### Description

in Columns view, the rightmost column should take up the entire rest of the space of the window, instead of truncating extra long filenames to keep the column width the same.

also, I think it'd be a good option to allow the columns to the left be only as wide as the longest file/folder name, with a maximum width setting.

### Steps To Reproduce

activate Columns view
go to a folder with filenames longer than the column width
see your filenames get cut off when there's a ton of space to display them

### Expected behavior

being able to see the full filename is necessary sometimes.

### Files Version

2.1.0.0

### Windows Version

11 22000.434

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/3124383/149311524-d7d13e1c-d2ea-4dc3-98ff-988c1afe51fb.png)

**Comment by gave92** [comment]
Merging with #7863
