### ISSUE TITLE
Bypass open limit of 10 files at once

### ISSUE THREAD

**Issue by exomarty** [files-community/Files#7598]
### What's the Problem?

Windows at default has the 10 limit top open files at once wich is very limited
that is really annoying while working with multiple documents, pdf, etc.

In windows native explorer its easy to bypass that limit creating  a new DWORD (32-bit) Value called MultipleInvokePromptMinimum on the registry with the new limit 30,50,etc..

Files seems to have the limit on 10 files too

### Solution/Idea

Can we increase that limit or give the option too on the configuration?

### Alternatives

tutorial to do it myself on registry

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
@exomarty does the registry change work for Files as well?

**Comment by exomarty** [comment]
No, if i change registry on windows only applies to default explorer, Files keeps the limit on 10 files

> @exomarty does the registry change work for Files as well?

**Comment by yaira2** [comment]
I can't reproduce this issue, can you see if it's resolved?
