### ISSUE TITLE
Open .zips in files rather than file explorer using external programs when it's set as default

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#7600]
### What's the Problem?
Current opening a .zip file via external programs it will open always use file explorer even if default is set to files.

### Solution/Idea

if .zip are called from external programs like Edge and files is default manager it should open in files.
If it set to use an external program like 7-zip it should open in that. 
If the zip is called from file explorer window it should open in that.

### Alternatives

*

### Comments

I believe this was an intended because of my previous issue #6110

**Comment by yaichenbaum** [comment]
@josh-65 did you toggle the option to set Files as the default off and on after updating to v2.1?

**Comment by josh-65** [comment]
yep just did it

**Comment by starkgate** [comment]
The behaviour you describe works for me, zips are opened in Files as they should.

**Comment by Josh-65** [comment]
They don't if you use something like edge download manager to open them. I know they work if I open them from files directly.

**Comment by starkgate** [comment]
Even from Edge or Firefox, they open fine.

**Comment by Josh-65** [comment]
They don't for me they just use file explorer

**Comment by gave92** [comment]
Does setting Files as default app for zips make any difference?

**Comment by Josh-65** [comment]
That's fixes it though that would be included with the toggle in settings.
