### ISSUE TITLE
Bug: Typing name doesn't visibly jump to selected file/folder in the column layout

### ISSUE THREAD

**Issue by enoversum** [files-community/Files#7602]
### Description

When I have the multi-pane (columns) layout activated, typing in the name of a file or folder does bring to the selected item, but doesn't show in the file/folder list of said column. The next column though shows its content, so jump itself is working.

### Steps To Reproduce

1. Open a Files window and change it to the column layout.
2. Just to make sure, click on an item, so the correct column is activated.
3. Start typing the name of a file or folder.
4. Files shows some other file or folder on top of the column instead of the selected one.

### Expected behavior

Files jumps to the selected item, just like in any of the other views.

### Files Version

2.1.0.0 (Store version)

### Windows Version

22000.434

### Relevant Assets/Logs

not applicable?

**Comment by windracer** [comment]
In my installation of Files, when switched to the Columns Layout, I experience the same issue.

1. Ensure that the number of files in the column exceeds the window height (in other words, some files aren't visible)
2. Start typing a file name. 
3. A file or a folder starting from the typed letter is selected (the contents of the folder or a zip archive is shown in the next column), but the column scrolls to the end (in most cases), or jumps back to the top. The selected item isn't visible.

**The other issue** is that if a folder was selected in the first column, the content of the folder is shown in the next column. If after pressing a key the selection switches to a file, the next column continues to show the content of the folder that was selected previously (but the preview panel displays the correct file details).

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by enoversum** [comment]
@yair100 Just downloaded 2.4.44.0 (Preview), and yes, still exactly as described by @windracer and me. No change, unfortunately.

**Comment by yaira2** [comment]
Is it a large folder?

**Comment by enoversum** [comment]
> Is it a large folder?

In fact, it is. The content doesn't fit into the window, as described above in the steps to reproduce.
