### ISSUE TITLE
Open a new Files window if explorer is called on a different virtual desktop

### ISSUE THREAD

**Issue by enoversum** [files-community/Files#7603]
### What's the Problem?

When I use multiple virtual Desktops (the inbuilt Windows 10/11 feature) and have Files set as the standard Explorer application, opening a new Explorer window always attaches it to an existing Files window, even when I am on another virtual Desktop. Files then jumps back to the Desktop which has the first Files window open and attaches the new window there. 
I know there is a setting for starting Files in a new process if started from a taskbar jump list, but that makes _every_ window I open via Win + E, or Strg + N when I have Files focussed, open as a separate window. 

### Steps to reproduce:
1. Enable Set as default option in Files.
2. Open a Files window on virtual Desktop 1. 
3. Go to Virtual Desktop 2.
4. Use Win + E to open a blank Files window. 
5. Files attaches the new tab with the existing Files window, going back to Desktop 1. 

### Requirements
- Open a unique instance of Files for each virtual desktop

### Files Version

2.1.0.0

### Windows Version

220000.434

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
@princesingh04 do you want to work on this? We still need to finalize the requirements.

**Comment by yaira2** [comment]
I'm not sure if this was a deliberate change but this now appears to be the current behavior for win + e.
