### ISSUE TITLE
Sidebar content disappears

### ISSUE THREAD

**Issue by lungudaniel** [files-community/Files#7605]
### Description

After going into a folder sidebar content disappears.  Going back to previous folder does not fix it. Closing and opening the app sometimes restores sidebar content.

### Steps To Reproduce

1. Run Files
2. Open a folder > sidebar content disappears
3. Going back to previous folder does not fix it.
4. Closing and opening the app sometimes restores sidebar content

### Expected behavior

1. Run Files
2. Open a folder > sidebar content is present

### Files Version

Version: 2.1.0.0 

### Windows Version

Edition	Windows 10 Pro Version	21H2 Installed on	‎19-‎Jul-‎20 OS build	19044.1348 Experience	Windows Feature Experience Pack 120.2212.3920.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7864006/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7864008/debug_fulltrust.log)

**Comment by gave92** [comment]
Store version is broken, could you test with the sideloaded version? From here: https://filescommunity.blob.core.windows.net/files/stable/Files.Package_2.1.0.0_Test/Files.Package_2.1.0.0_x86_x64_arm64.msixbundle
