### ISSUE TITLE
Add details pane to preview file information

### ISSUE THREAD

**Issue by Debagnik** [files-community/Files#7606]
### Solution/Idea

I can't see details of a file/folder when selected, It would be immensely helpful if you kindly include this feature in your next release

### Alternatives

A small information box containing the information appears while hovering over the file/folder would also helpthat 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.0.0

### Windows Version

Windows 11 Home Single Language Version	21H2 OS build	22000.434

**Comment by Josh-65** [comment]
this is an option
![image](https://user-images.githubusercontent.com/26977075/149382186-5032f610-00d8-4996-9094-b34c8536468f.png)

**Comment by Tarek-Hasan** [comment]
> this is an option 

Details pane help view essential metadata without occupying huge screen area like preview pane.

**Comment by gave92** [comment]
@Debagnik could you confirm you're referring to the bottom pane in this image (from @Tarek-Hasan)?

![file explorer](https://user-images.githubusercontent.com/27731012/149367939-418e63a8-0216-471f-9ef4-92b2f5e68605.png)

**Comment by gave92** [comment]
@yair100 I approved this one, what do you think? Plays nicely with dual pane mode.

**Comment by yair100** [comment]
> @yair100 I approved this one, what do you think? Plays nicely with dual pane mode.

How is it different than the current implementation (other than the smaller thumbnail)?

**Comment by gave92** [comment]
Position being at the bottom mostly, would be like an upgraded status bar.

**Comment by mdtauk** [comment]
I did suggest both a Vertical and Horizontal arrangement for the Preview/Detail Pane some time ago, but for now, its a resizable right hand pane.

**Comment by yaichenbaum** [comment]
> I did suggest both a Vertical and Horizontal arrangement for the Preview/Detail Pane some time ago, but for now, its a resizable right hand pane.

The current behavior is for it to adapt based on screensize, there is an open issue requesting support to change the arrangement manually so we should probably merge with that.

**Comment by gave92** [comment]
Oh right, I was thinking of showing a details pane at the bottom for each pane but that's probably too much.
