### ISSUE TITLE
Update Russian translation

### ISSUE THREAD

**Issue by Pavlusha311245** [files-community/Files#7611]
### Description

Баг обнаружен на версии 2.1.0.0. Дублирование пуктов меню в настройках
![ApplicationFrameHost_itMozfs1oc](https://user-images.githubusercontent.com/49598333/149392189-79dcbe71-00d9-490a-af91-5ca13d5144fb.png)
.

### Steps To Reproduce

1. Зайти в настройки
2. Перейти на вкладку предпочтения
![ApplicationFrameHost_Yy4VSx4GVE](https://user-images.githubusercontent.com/49598333/149392096-b62b7f97-ebce-4229-80eb-36feeaa3bd21.png)

### Expected behavior

Отсутствие английского варианта дублированного пункта

### Files Version

2.1.0.0

### Windows Version

Windows 11 21H2 22000.376

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7865298/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7865299/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
@Pavlusha311245 can you upload a screenshot of the duplicate items?

**Comment by Pavlusha311245** [comment]
> @Pavlusha311245 can you upload a screenshot of the duplicate items?

In Steps To Reproduce

**Comment by gave92** [comment]
Traslation was not updated: now one setting is for files, the other is for folders.

**Comment by yaichenbaum** [comment]
@Pavlusha311245 would you like to work on this?

**Comment by Pavlusha311245** [comment]
> 
@yair100 Yes

**Comment by Pavlusha311245** [comment]
> @Pavlusha311245 would you like to work on this?

How can I make a pull request?
