### ISSUE TITLE
Windows register. Default expolorer

### ISSUE THREAD

**Issue by Pavlusha311245** [files-community/Files#7612]
### Description

После обновления проводника пункт меню "Использовать Files в качестве проводника по умолчанию" был выставлен с галочкой false.

### Steps To Reproduce

1. Использовать старую версию Files.
2. Установить Files проводником по умолчанию
3. Обновить приложение в Microsoft store
4. Убедиться, что галочка установки Files проводником по умолчанию в состоянии false

### Expected behavior

Отслеживания состояния установки проводника по умолчанию в интерфейсе и отображение его в пункте настроек.

### Files Version

2.1.0.0

### Windows Version

Windows 11 21H2 22000.376

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7865329/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7865330/debug.log)

**Comment by gave92** [comment]
Thanks for the report. This is normal as the method was slightly changed, you'll need to enable it again.
