### ISSUE TITLE
Can not create more than one bundle.

### ISSUE THREAD

**Issue by widkit** [files-community/Files#7614]
### Description

Can not create more than one bundle. Everything works fine except this,
![image](https://user-images.githubusercontent.com/75989700/149400563-73b70dab-43a0-4a0f-9fb2-5ab776fd8ad8.png)
this settings button here.
I can't click it. I tried every way around, but hey; you can't click it and create more bundles.

### Steps To Reproduce

Create a bundle
Try to create another one

### Expected behavior

Creating a bundle
Creating another one

### Files Version

Version: 2.1.0.0 OS Version: 10.0.22000.376

### Windows Version

Windows 11 Home 21H2 22000.376

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/75989700/149400563-73b70dab-43a0-4a0f-9fb2-5ab776fd8ad8.png)

**Comment by gave92** [comment]
\+ @d2dyno1

**Comment by widkit** [comment]
seems to have fixed for me

**Comment by widkit** [comment]
I thought it was fixed nvm

**Comment by cloudmapleleaf** [comment]
I have the same problem😢

**Comment by DMS4444** [comment]
> I have the same problem😢

Same here

**Comment by DMS4444** [comment]
You can manually add more bundles like this:
[](https://user-images.githubusercontent.com/81837486/149846741-a71eb8b5-a356-4381-b8e8-acd2af8a2b48.png)
Editing the "bundles.json" file.
To find bundles.json go here: 
![Captura de pantalla 2022-01-18 002120](https://user-images.githubusercontent.com/81837486/149847053-27392425-24ec-416e-8d16-042f493e4378.png)
It is on the settings folder. BTW Sorry for my english.

**Comment by d2dyno1** [comment]
Aaaaa I really need to fix it 😅

**Comment by bagiosw** [comment]
> A quick "solution" You can manually add more bundles like this: ![a](https://user-images.githubusercontent.com/81837486/149846741-a71eb8b5-a356-4381-b8e8-acd2af8a2b48.png) Editing the "bundles.json" file. To find bundles.json go here: ![Captura de pantalla 2022-01-18 002120](https://user-images.githubusercontent.com/81837486/149847053-27392425-24ec-416e-8d16-042f493e4378.png) It is on the settings folder. BTW Sorry for my english.

For now this is the working solution, just make sure the app is closed while you editing the json file, otherwise it will revert back to the current state while it was opened.

**Comment by widkit** [comment]
> > A quick "solution" You can manually add more bundles like this: ![a](https://user-images.githubusercontent.com/81837486/149846741-a71eb8b5-a356-4381-b8e8-acd2af8a2b48.png) Editing the "bundles.json" file. To find bundles.json go here: ![Captura de pantalla 2022-01-18 002120](https://user-images.githubusercontent.com/81837486/149847053-27392425-24ec-416e-8d16-042f493e4378.png) It is on the settings folder. BTW Sorry for my english.
> 
> For now, this is the working solution, just make sure the app is closed while you edit the json file, otherwise it will revert back to the current state while it was opened.

![image](https://user-images.githubusercontent.com/75989700/149977870-d84cfe31-ab4e-472d-966b-59bb056bfe0c.png)



this solution here seems to work, but GUI option should be fixed.
![image](https://user-images.githubusercontent.com/75989700/149977953-b07802c9-0896-4100-a4fc-6cc4b3abcca3.png)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7787
