### ISSUE TITLE
Ability to make the preview much bigger

### ISSUE THREAD

**Issue by tracyrosstracyross** [files-community/Files#7617]
### What's the Problem?

I'm using this on a 10" Surface Go and the file preview is so tiny that it's almost useless. I would love to be able to resize it.

### Solution/Idea

Allow resizing of the preview area.

### Alternatives

Allow expanding folder contents on the left so that the main area could show previews instead of folder contents.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Windows Version

Windows 10 S

### Comments

Thank you!

**Comment by gave92** [comment]
Thanks for the report. This is tracked jn #6628.

**Comment by tracyrosstracyross** [comment]
Thanks.
