### ISSUE TITLE
Sidebar Dropdown Bug

### ISSUE THREAD

**Issue by TheAlphaReturns** [files-community/Files#7620]
### Description

This bug makes it so that if you close and reopen the app, you would have to close, then reopen any dropdown menu (such as favorites) to make the contents shown

### Steps To Reproduce

1. Open Files
2. Make a dropdown menu shown (e.g Favorites)
3. Close and Reopen
4. The contents will be hidden, but the up arrow is shown
5. Closing and reopening it will get the contents to show up again

### Expected behavior

I want the contents shown if the app is reopened

### Files Version

Version: 2.1.0.0 OS Version: 10.0.22000.376

### Windows Version

Windows 11 21H2 22000.376

### Relevant Assets/Logs

A video:

https://user-images.githubusercontent.com/61358474/149421518-4b7b6cc7-9aaa-4cd5-8fd8-74b0f4f9025e.mp4

**Comment by gave92** [comment]
Merging with #6469
