### ISSUE TITLE
Cannot Add a Shortcut to Favorites

### ISSUE THREAD

**Issue by TheAlphaReturns** [files-community/Files#7621]
### Description

hence the title

### Steps To Reproduce

1. Make a shortcut
2. right click> add to favorites
3. it doesn't work
4. try reopening. it still doesn't work

### Expected behavior

for it to work

### Files Version

Version: 2.1.0.0 OS Version: 10.0.22000.376

### Windows Version

Windows 11 21H2 22000.376

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7866497/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7866498/debug_fulltrust.log)

**Comment by gave92** [comment]
Merging with #1607
