### ISSUE TITLE
[Crash Report] Drag a tab into home

### ISSUE THREAD

**Issue by TheAlphaReturns** [files-community/Files#7622]
### Description

Files crashes if you drag a second tab into home

### Steps To Reproduce

1. Open files. Default opens home tab
2. make a new tab and open it into any folder you want
3. drag the new tab into the home tab
4. it crashes

### Expected behavior

for it not to crash

### Files Version

Version: 2.1.0.0 OS Version: 10.0.22000.376

### Windows Version

Windows 11 21H2 22000.376

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7866510/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7866511/debug_fulltrust.log)

**Comment by gave92** [comment]
Merging with #7838
