### ISSUE TITLE
Drive for Desktop not showing up as a cloud drive

### ISSUE THREAD

**Issue by TheAlphaReturns** [files-community/Files#7623]
### Description

hence the title, p.s. autodesk drive/autodesk desktop connector also

### Steps To Reproduce

1. Install drive for desktop (https://www.google.com/drive/download/)
2. Install files
3. It does not show up in cloud drives

### Expected behavior

for it to show up in cloud drives

### Files Version

Version: 2.1.0.0 OS Version: 10.0.22000.376

### Windows Version

Windows 11 21H2 22000.376

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7866524/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7866525/debug_fulltrust.log)

**Comment by gave92** [comment]
Does it appear under Drives?

**Comment by TheAlphaReturns** [comment]
yes
