### ISSUE TITLE
Give it a compact view

### ISSUE THREAD

**Issue by TheAlphaReturns** [files-community/Files#7624]
### What's the Problem?

no problem. just a feature request. something that i would like to see.

### Solution/Idea

Built-in file explorer in windows 11-like view>compact view would make the space between listed files and folders 0

### Alternatives

none

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow literally everyone to accomplish ease of viewing by making the space between listed files and folders 0 | Must |

### Files Version

Version: 2.1.0.0 OS Version: 10.0.22000.376

### Windows Version

Windows 11 21H2 22000.376

**Comment by gave92** [comment]
Merging with #1940
