### ISSUE TITLE
Unable to turn off 'Default file manager'

### ISSUE THREAD

**Issue by luketxr** [files-community/Files#7626]
If you uninstalled Files before turning off the option to set Files as the default, you can revert the changes using this script. https://raw.githubusercontent.com/files-community/Files/main/src/Files.Launcher/Assets/FilesOpenDialog/UnsetFilesAsDefault.reg

![image](https://user-images.githubusercontent.com/39923744/150415668-cd68c258-9493-489e-b004-066dbb3c9a37.png)

**Comment by yaichenbaum** [comment]
@luketxr are you using v2.1?

**Comment by luketxr** [comment]
> 

Yes. Got the update via Windows Store

**Comment by gave92** [comment]
Did you have that option enabled before the update? Now it's stuck at "off"?
Could you upload the app's log files?

**Comment by gave92** [comment]
To revert to explorer you can use the UnsetFilesAsDefault.reg file in this.
https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip.

**Comment by luketxr** [comment]
The reg file solved the problem for not being able to turn off 'Default file manager'. However the button in experimental is still buggy. I wish I could send you the log so you can fix it, but once I click "Open log location" it opens a new home tab. Can you specify where can I find the log file?

**Comment by onein528** [comment]
here %LOCALAPPDATA%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState
debug.log and debug_fulltrust.log

**Comment by luketxr** [comment]
> here %LOCALAPPDATA%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState debug.log and debug_fulltrust.log
[debug.log](https://github.com/files-community/Files/files/7867056/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7867057/debug_fulltrust.log)

**Comment by Dardrai** [comment]
> To revert to explorer you can use the UnsetFilesAsDefault.reg file in this archive. https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip.

That one Fixed Win+E for me! Very good now that Win+E opens the "right" File Manager thx!

**Comment by gave92** [comment]
[Internal note]
The two reg files need to be updated to match the ones used in Files v2.1.
Currently the unset file only reverts the changes done by Files V2.0.34.

**Comment by Rykimaruh** [comment]
When I ran the unset registry, now I can't open folders, all it does is open a new file explorer window :( 

Any help is appreciated!

**Comment by gave92** [comment]
@Rykimaruh this is the updated version of the script:
https://raw.githubusercontent.com/files-community/Files/main/src/Files.Launcher/Assets/FilesOpenDialog/UnsetFilesAsDefault.reg

If it still does not solve the issue please let us know.

**Comment by Rykimaruh** [comment]
Excellent! This solved the issue! 

Thank you so much for the quick response!

**Comment by utkarsh-ut9** [comment]
> @Rykimaruh this is the updated version of the script (make sure to save it as a ".reg" file): https://raw.githubusercontent.com/files-community/Files/main/src/Files.Launcher/Assets/FilesOpenDialog/UnsetFilesAsDefault.reg Please let us know if it solves the issue.

Thank you so much! It worked as expected and fixed the issue. Cheers! :D

**Comment by rr-da-cat** [comment]
![image](https://user-images.githubusercontent.com/97874600/149886191-0fa79028-41b7-44d9-91a5-1a077a03a53b.png)

I downloaded the new .reg file and ran it...
But now i again want to set files as default.

I downloaded the msixbundle and reinstalled it.
Now i have 2 instances as below. And both the buttons are stuck.

All I want to do now is MAKE files app as default opener. I have the .reg file as backup so waiting for a quick response...!

**Comment by raghav-ramesh** [comment]
1 instance of app is launched from taskbar, Other from msixbundle windows's launch button...
They are not 2 same windows. 

@gave92  @yair100

**Comment by gave92** [comment]
You need to run the script, uninstall the Store version, switch the option in from the side loaded version.

**Comment by rr-da-cat** [comment]
My MS Store apps don't work already so I don't want to risk uninstalling Files... Can u provide me with a script that makes it default file explorer please @gave92

**Comment by gave92** [comment]
If you want to keep both, look at Windows Settings > Apps > App execution alias. Make sure the correct Files install had the right switch enabled.

**Comment by ScottRButler** [comment]
I came here looking for this exact question. I just reinstalled Files, turned the setting off, and uninstalled it. That fixed it for me.
The reason I installed it was I couldn't map a network drive. I will look through here for the answer in a bit but if you happen to know off the top of your head where the answer is can you point me that way.? Thanks much. OH, I was using the store version.

**Comment by DOWIT-JoelFrojmowicz** [comment]
Why not return Windows Explorer as default when uninstalling Files ??

**Comment by rr-da-cat** [comment]
Ye do that

**Comment by gave92** [comment]
@DOWIT-JoelFrojmowicz because UWP apps can't have an Uninstaller unless allowed by Microsoft (and they have not approved our request). We're looking for alternatives aroung that.

**Comment by idan054** [comment]
> To revert to explorer you can use the UnsetFilesAsDefault.reg file in this archive. https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip.

Thanks! this realy works.

**Comment by LTcorpio** [comment]
The reason why I can't Disable "Set Files as default file manager" is that I don't close Defender.
When I close Huorong Security, it works!!!

**Comment by lippoliv** [comment]
https://github.com/files-community/Files/issues/7626#issuecomment-1012654935
> To revert to explorer you can use the UnsetFilesAsDefault.reg file in this archive. https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip.

This did work partly for me. I could use `WIN+E` again but in the explorer, I could not open folders.

https://github.com/files-community/Files/issues/7626#issue-1102651539 did the job for me
> If you uninstalled Files before turning off the option to set Files as the default, you can revert the changes using this script. https://raw.githubusercontent.com/files-community/Files/main/src/Files.Launcher/Assets/FilesOpenDialog/UnsetFilesAsDefault.reg

Thanks for linking those files.
