### ISSUE TITLE
Empty Network

### ISSUE THREAD

**Issue by dmeffe-21** [files-community/Files#7627]
### Description

No shared folders, computers or devices are showing up in Network
![unknown](https://user-images.githubusercontent.com/97712407/149433659-dbd9d2a2-e232-4d27-8642-c257714f84dd.png)

### Steps To Reproduce

1. Open Files
2. Go to Network
3. Nothing Appearing.

### Expected behavior

Not sure what is supposed to happen but I assume you would at least see the available shared locations on the network.

### Files Version

Version: 2.1.0.0

### Windows Version

Windows 11 Pro Version	21H2 OS build 22000.434 Windows Feature Experience Pack 1000.22000.434.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7866929/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7866930/debug_fulltrust.log)

**Comment by d2dyno1** [comment]
@dmeffe-21 This has been cloed with #7931
