### ISSUE TITLE
Keyboard shortcuts vs other Windows/macOS/Linux file managers

### ISSUE THREAD

**Issue by RedBearAK** [files-community/Files#7628]
### What's the Problem?

This file manager seems like one of the most promising choices available to get a modern experience in Windows, comparable to the Finder in macOS and a number of the better GUI file managers in Linux. 

I use the Kinto.sh project by Ben Reaves, which remaps the keyboard in Windows or Linux to behave like macOS. I wanted Linux file managers to respond to keyboard shortcuts like the Finder in macOS, so I implemented a shortcut remap overlay that "modded" the shortcuts of all the Linux GUI file managers I could find (the ten variations in the list below). It was eventually merged into the base Kinto config file as part of the defaults. 

https://github.com/rbreaves/kinto/pull/463
https://github.com/rbreaves/kinto/pull/594

The Linux file managers supported by these remaps are: 

```
# Caja File Browser (MATE file manager, fork of Nautilus)
# DDE File Manager (Deepin Linux file manager)
# Dolphin (KDE file manager)
# Nautilus (GNOME file manager, may be named "Files")
# Nemo (Cinnamon file manager, fork of Nautilus, may be named "Files")
# Pantheon Files (elementary OS file manager, may be named "Files")
# PCManFM (LXDE file manager)
# PCManFM-Qt (LXQt file manager)
# SpaceFM (Fork of PCManFM file manager)
# Thunar File Manager (Xfce file manager)
```

I'm trying to port these remaps over to some file managers in Windows, where Kinto uses AutoHotKey to do the remaps. This is working OK for Windows Explorer (explorer.exe). But when I try to figure out the executable name for this "Files" application, I see things like this in the Task Manager properties: 

```
49306atecsolution.FilesUWP_2.1.0.0_x64__et10x9a9vyk8t
```

So that's the first problem. Without a standard, simple executable name like `files.exe`, I'm not sure how to apply AutoHotKey remaps. And I can't even seem to find where this application is installed, either when I installed it from the release file downloaded from GitHub or when I reinstalled it from the Microsoft Store. I've never actually seen anything like this before. Is there a chance Files would eventually wind up with a more standard "real" executable name and location? 

Anyway, there is an issue here (#1660) asking for a page in the preferences to list all the keyboard shortcuts, and I would also like to see that implemented. But at the moment what I need is just a reference to the currently implemented keyboard shortcuts. So if someone could point me to a file here somewhere that might list all of the current shortcuts, that would be helpful. I tried to search for "shortcuts" in the repo, but a lot of different things came up and it was not immediately obvious if any of the results would contain anything like a complete list of shortcuts. 

### Solution/Idea

My work on remapping keyboard shortcuts for file managers between macOS and Linux showed that there were a number of shortcuts that were common to both platforms and didn't therefore even need to be remapped, and that there were some other shortcuts that were just minor variations using a different modifier key, and then some that were sort of standard but one or more of the Linux file managers had chosen different shortcuts which needed to be accounted for. 

So my remaps for Linux file managers consist of a "general" block and then a few "overrides" for some of the individual file managers. I'd like to possibly converse with the devs here and see if it might be possible to get Files to conform as closely as possible to some of the established "standard" shortcuts commonly used by other file managers. Without seeing a list I don't know for sure yet exactly how close the current shortcuts for Files are to the most common shortcuts I've seen in other file managers. 

I happen to like macOS and the Finder, so I made remaps that made Linux file managers act like the Finder for all sorts of common functions like navigation, tab switching, and so on. But Windows shortcuts often most closely resemble Linux shortcuts, and vice versa. 

In short, I would like to participate in discussions about Files having a keyboard shortcut scheme that is as closely aligned as possible with the most standardized keyboard shortcuts in other file managers. So that the transition is smoother for users who need to move between Windows, Linux and/or macOS. 

For instance, the shortcut for "preferences" in macOS apps has always been standardized on Command+comma. In Linux, it is becoming fairly common for newer apps that don't have a traditional menu bar (where the Preferences shortcut might have been `Alt+E` to open the Edit menu, then `P` or `E` or `N`) to use the equivalent of Ctrl+comma (which with Kinto's remapping ends up in the same physical position on the keyboard). I notice Files doesn't have a traditional menu bar, so it's a lot like a modern GTK app in Linux in that respect. 

Here is a spreadsheet of what I needed to remap to get the GUI Linux file managers to behave (mostly) as I expected: 

[Finder_keyboard_shortcut_mapping_project_2021-12-25.xlsx](https://github.com/files-community/Files/files/7867062/Finder_keyboard_shortcut_mapping_project_2021-12-25.xlsx)

The thing to pay attention to here is not the shortcut I was implementing (from macOS) but rather the shortcut(s) they were being remapped to in order to work with each file manager application. A number of them were actually standard across all the file managers I was testing. 

Feedback/discussion on this entire matter is appreciated. 

### Alternatives

[Nothing to put here.]

### Files Version

Version: 2.0.34.0 OS Version: 10.0.19043.1466

### Windows Version

Windows 10 21H1 (Build 19043.1466)

**Comment by yaichenbaum** [comment]
@RedBearAK https://files.community/docs/configuring/keyboard-shortcuts

**Comment by RedBearAK** [comment]
@yaichenbaum 

> @RedBearAK https://files.community/docs/configuring/keyboard-shortcuts. The executable name is `files.exe`.

Silly me, I always search in the wrong places. 

Do I need to reboot or something, because I'm definitely not seeing that as the executable name in my Task Manager.

**Comment by RedBearAK** [comment]
@yair100 

> Task manager might not display the name, but it should work. You can test by opening a cmd window and typing `Files`.

I'll have to try again and see if I can get the remapping to work. Maybe reboot if it doesn't. I'm still kind of new at trying to use AHK. 

These shortcuts mostly look pretty standard and logical already, as expected. But, can I ask about the logic of using `Ctrl+D` to delete? This is a shortcut that web browsers use for bookmarking, and I've noticed file browsers, especially in Linux, have evolved to behave substantially similar to web browsers. So much so that using `Ctrl+D` to delete files seems like it might be problematic. Muscle memory can easily cross over between file managers and web browsers. `Ctrl+L` does the same thing in both, basically, intuitively letting you change the "location".

**Comment by yaichenbaum** [comment]
@RedBearAK `ctrl` + `d` was for consistency with File Explorer but this shortcut can be removed for reasons you mentioned. Can you open a feature request for this?

**Comment by RedBearAK** [comment]
@yair100 

Rebooted and started from the search field as "files.exe", but in Task Manager I still see something like this as the main application name: 

```
Files_2.0.34.0_x64__1y0xx7n9077q4
```

I still can't seem to get the remapping working using the executable name of `files.exe`, the way I was able to get it to work with `explorer.exe`. 

Is this perhaps happening because I started using Files several months ago, around version 1.5? Do I need to try and completely wipe it from my system and reinstall from the Microsoft Store?

**Comment by RedBearAK** [comment]
> @RedBearAK `ctrl` + `d` was for consistency with File Explorer but this shortcut can be removed for reasons you mentioned. Can you open a feature request for this?

@yair100 

Sure, not a problem. I guess that one was so standard I actually left it off my spreadsheet, but all the Linux file managers I was working with used the `Delete` key. I assume you have no issue with this?

**Comment by yaichenbaum** [comment]
> > @RedBearAK `ctrl` + `d` was for consistency with File Explorer but this shortcut can be removed for reasons you mentioned. Can you open a feature request for this?
> 
> @yaichenbaum
> 
> Sure, not a problem. I guess that one was so standard I actually left it off my spreadsheet, but all the Linux file managers I was working with used the `Delete` key. I assume you have no issue with this?

I agree, delete is the more natural shortcut.

**Comment by yaichenbaum** [comment]
> Is this perhaps happening because I started using Files several months ago, around version 1.5? Do I need to try and completely wipe it from my system and reinstall from the Microsoft Store?

It shouldn't make a difference when you downloaded Files, I know that people have successfully configured Files with AutoHotKey https://github.com/files-community/Files/issues/2355#issuecomment-927377572

**Comment by RedBearAK** [comment]
@yair100 

An example of what I would like to see added to supported keyboard shortcuts is `Ctrl+PgUp/PgDn` for tab navigation. The `Ctrl+Tab/Ctrl+Shift+Tab` shortcuts as currently implemented are also fairly common, but `Ctrl+PgUp/PgDn` is even more common, at least in Linux, but also in Windows and Linux web browsers. Importantly, this is a link between file managers and web browsers, and it works in Windows web browsers for tab navigation. 

This works for me in Chrome, Edge and Firefox on Windows. It would be an intuitive tab nav shortcut for anyone used to using it in any of those web browsers. 

To be clear, I would not want the `Ctrl+Tab/Ctrl+Shift+Tab` shortcuts to be removed. Lots of users are very used to those, and they are also intuitive and easy to remember, and also work the same way in web browsers. These would be alternate shortcuts for tab nav, for those who find `Ctrl+PgUp/PgDn` less awkward or easier to remember.

**Comment by gave92** [comment]
Full path of the executable: `%LocalAppData%\Microsoft\WindowsApps\files.exe`. Could be that the app execution alias is disabled under Windows Settings > Apps > App execution alias?

**Comment by Josh-65** [comment]
Presuming you still want to remap keyboard shortcuts il merge this with #9559

**Comment by yaira2** [comment]
@RedBearAK This feature will be included in the next release. Please see #9559 for more details.
