### ISSUE TITLE
Remove ctrl + d shortcut to avoid accidentally deleting items

### ISSUE THREAD

**Issue by RedBearAK** [files-community/Files#7629]
### What's the Problem?

Current keyboard shortcut for deleting files is `Ctrl+D` to conform with Windows File Explorer. Due to the close relationship between web browsers and file managers (file browsers), this can be a dangerous muscle memory spillover, especially for users moving between Linux and Windows, since `Ctrl+D` in web browsers is "bookmark page". In addition, a number of file managers implement some form of "bookmarks" in the sidebar, and may utilize `Ctrl+D` for adding a folder to the sidebar. 

### Solution/Idea

Suggested: Change delete shortcut to `Delete` key, to conform with other common file managers. 

### Alternatives

Alternate solution: Finder in macOS uses Cmd+Delete, but the Mac Delete key is actually the same keycode as "Backspace" on a PC keyboard. The Finder ignores and produces a "bonk" error sound if either "Delete" (Backspace) or "Delete" (forward delete, found on full size Mac keyboards or accessed with Fn+Delete on a Mac portable) are pressed without using the Command key. I believe this was a choice taken long ago to make it more difficult for users to accidentally delete files. 

Coming from 20 years of macOS usage I would approve of an equivalent like Ctrl+Delete to help safeguard users from accidental deletions. But most other file managers in Windows or Linux just use the `Delete` key without any safeguarding.

**Comment by yaichenbaum** [comment]
@RedBearAK I should have clarified that `delete` already works.

**Comment by yaichenbaum** [comment]
This should be resolved in `main`.
