### ISSUE TITLE
Blank sidebar, spinning icon in tab opening any folder

### ISSUE THREAD

**Issue by RedBearAK** [files-community/Files#7630]
### Description

So, I seem to have managed to get Files to stop working reliably, even after uninstalling, rebooting and then reinstalling from the Microsoft Store. 

I checked the Docs and couldn't find anything related to doing a full "clean" uninstall of all possible files that might be related, so, not sure how to fix this. Currently the sidebar is blank and trying to go into any folder from the main view pane just spins forever in the tab, with a blank main view pane. 

I keep quitting and running the app again, and everything seemed to be working once, but then the next time it was flaky again, etc. It works about 1 out of 4 times I start the app. 

### Steps To Reproduce

Unknown. Besides uninstalling and reinstalling. 

### Expected behavior

Expected: Normal sidebar and ability to open folders. 

### Files Version

Version: 2.1.0.0 OS Version: 10.0.19043.1466

### Windows Version

Windows 10 21H1 (Build 19043.1466)

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7867681/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7867682/debug.log)

**Comment by Tarek-Hasan** [comment]
Duplicate issue [Nothing in the sidebar #7554](https://github.com/files-community/Files/issues/7554#issue)
Temporary workaround - minimize and restore the app.

**Comment by RedBearAK** [comment]
@Tarek-Hasan 

Does seem to work. I was having trouble deleting a folder and that folder deleted successfully afterward too. Weird.

**Comment by gave92** [comment]
Thanks for the report. Store version is currently broken, you may try the sideloaded version instead.
