### ISSUE TITLE
Drag and drop causes improper display of the "selected files indicator"

### ISSUE THREAD

**Issue by jh961202** [files-community/Files#7631]
### Description

When drag and drop an oobject ( no matter files/folders ) in Files, if the object is dragged over other objects ( say, a folder/executable ), the targeted ones' selected indicator will be lit up like this: 
![image](https://user-images.githubusercontent.com/8479301/149448583-83c2aa42-6cbe-4bc8-a2c0-080256df2d19.png)
This behavior is okay but, **after leaving the target object, the target object's selected indicator will still being lit up, which is incorrect.**
![ezgif com-gif-maker](https://user-images.githubusercontent.com/8479301/149449543-2f5e732e-d04e-43fb-a971-3bd2c90fdf73.gif)

Same situation happens on draging files/folders out of Files ( say, to other applications like browser to upload files ); if one or more files/folders were selected, **their indicator WON'T disappear**, which is different from what Windows Exploere does.
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/8479301/149450376-214c5c50-15f1-4102-8fb7-be094f0c0e5f.gif)
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/8479301/149450465-c606954f-ce5c-4683-8e2f-eba79631fa5a.gif)

Moreover, after drag and drop, **those pre-selected objects BEFORE the drag and drop action will also unable to disappear unless click on them once**, which may misleading users thinking those files were selected (but status bar reports none of the objects were selected)
![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/8479301/149450639-8f047ff0-8544-4708-8f59-de012e26d896.gif)

### Steps To Reproduce

1.Go to a path that contains decent amount of files/folders.
2.Follow the description section.
3.See the error.

### Expected behavior

Selected indicator should behave like Windows Explorer, e.g. disappear when drag and drop other objects.

### Files Version

Version: 2.1.0.0 OS Version: 10.0.22000.434

### Windows Version

Windows 11 21H2 22000.434

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7867815/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7867816/debug.log)

**Comment by gave92** [comment]
Tracked in #6768
