### ISSUE TITLE
Automatic refresh on LAN server

### ISSUE THREAD

**Issue by Micka974** [files-community/Files#7633]
### Description

When I copy/cut/delete documents between files I must refresh manually to see the copied documents. (only on LAN server)

### Steps To Reproduce

Copy or cut or delete documents on LAN serveur

### Expected behavior

Auto-refresh when files are copied/cut/delete

### Files Version

2.1.0.0

### Windows Version

Windows 10  21H2

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7867955/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7867956/debug.log)

**Comment by gave92** [comment]
Tracked in #5869
