### ISSUE TITLE
Drag and drop png to corel make black background

### ISSUE THREAD

**Issue by NaufalF22** [files-community/Files#7634]
### Description

So somehow drag and drop png picture from files to corel make black bacground

### Expected behavior

No black background

### Files Version

Versi: 2.1.0.0 OS Version: 10.0.22000.376

### Windows Version

Windows 11 21H2 22000.376

### Relevant Assets/Logs

Expected
![image](https://user-images.githubusercontent.com/63091744/149464082-5bf1e54e-7207-418a-aec5-2448ade44e37.png)

The bug
![image](https://user-images.githubusercontent.com/63091744/149464182-9f515f7b-760d-41ed-8f4d-e50fe80a08cb.png)

**Comment by yaichenbaum** [comment]
@NaufalF22 is this still an issue in the preview version? https://files.community/download/preview

**Comment by NaufalF22** [comment]
> @NaufalF22 is this still an issue in the preview version? https://files.community/download/preview

Yes, even now you cant drag and drop png to corel anymore
