### ISSUE TITLE
Clear Indication of copying files in background

### ISSUE THREAD

**Issue by Cheechako** [files-community/Files#7635]
### What's the Problem?

It is not very clear that files are being copied. Especially if one closes the window after having started the process. The files are still being copied which is unclear for the user

### Solution/Idea

If that happens, a copy dialog box like the standard windows explorer would be nice.

### Alternatives

an option to toggle such a dialog that would either inform the user that files will still be copied in the background or if the files explorer is closed, that a copying pop up dialog appears until the files have finished being copied.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.0.0

### Windows Version

Windows 11 Insider Preview 22533.1001

**Comment by yaira2** [comment]
Merging with #8207
