### ISSUE TITLE
Faster start of the explorer

### ISSUE THREAD

**Issue by Cheechako** [files-community/Files#7636]
### What's the Problem?

The Files Explorer launches slower than the windows one

### Solution/Idea

find a way for it to be the same time as many users might be put off by that - I know, I am sorry for that remark, but I like your product and you know how picky users can be

### Alternatives

none to offer

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.0.0

### Windows Version

Windows 11 Insider Preview 22533.1001

**Comment by Hidetoshi6721** [comment]
I also hope this improvement is taken into consideration. Although Files has improved a lot since V1, it still lags well behind of Microsoft's antique File Explorer in terms of performance.

**Comment by gave92** [comment]
Thanks for the report. Merging with #4180. Improving performance is something we're always looking into.

**Comment by Gegen103** [comment]
Up. I have 4 frames opened at launch. 
Why refresh theses 4 frames and at the end, show the one that was on screen when Files was closed ? 
Just open the 4 frames and refresh only the one that was on screen when Files was closed

**Comment by yaira2** [comment]
We're excited to share that startup performance will be significantly improved in the upcoming release of version 3. You can download the preview version from our website https://files.community/download.

**Comment by yair100** [comment]
@Cheechako we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
