### ISSUE TITLE
A date divider like in Windows Explorer's Downloads folder

### ISSUE THREAD

**Issue by Mcfly2340** [files-community/Files#7638]
### What's the Problem?

I'd like to see the date divider implemented in the Files app. What i mean by date divider is the divider in the Downloads folder in Windows Explorer like in the attachment

![Screenshot 2022-01-14 122232](https://user-images.githubusercontent.com/71077562/149508086-3deb39ce-d3db-401e-8b01-676a2a2c1afc.png)

### Solution/Idea

A toggleable setting to enable or disable the divider, with or without a date

### Alternatives

anything similar to a divider, just to make it more pleasing to the eye.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to see a clear line in between files | Must |
| This proposal will allow developers to see a clear line in between files indicating the date when the files were made or modified | Could |

**Comment by Josh-65** [comment]
There is
![image](https://user-images.githubusercontent.com/26977075/149525314-24590ad4-bb9e-4246-919e-48d49c62ffc6.png)

**Comment by Mcfly2340** [comment]
> There is in the menu from the two arrows. just selected grouping by data created or modified ![image](https://user-images.githubusercontent.com/26977075/149525314-24590ad4-bb9e-4246-919e-48d49c62ffc6.png)

Thank you so much! I couldn't find it in the settings panel so i thought it didn't have this feature but i guess i was wrong
