### ISSUE TITLE
Show an Extract all button when selecting a .zip file

### ISSUE THREAD

**Issue by Mcfly2340** [files-community/Files#7639]
### What's the Problem?

Just like in the Windows Explorer application, make a button appear with the text Extract all when clicking once on a .zip file

### Solution/Idea

Add a button to extract all contents from a zip file 

### Alternatives

Maybe A shortcut like CTRL + E to extract

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to click A button in the icon bar that extracts all contents from a .zip file | Must |
| This proposal will allow developers to click a shortcut (maybe CTRL + E) to extract all contents from a zip file | Could |

**Comment by Josh-65** [comment]
There is an extract button in the right click context menu already.

**Comment by Mcfly2340** [comment]
I did figure that out already but lately I've been using this feature a lot so i thought it could be (this button bellow) implemented into this app
![image](https://user-images.githubusercontent.com/71077562/149526740-119daf52-ea15-4588-868d-8ca5b4b5ea5b.png)

**Comment by puppetsw** [comment]
Do you mind if I have a go at this?

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7696
