### ISSUE TITLE
This sentences has not been translated into Arabic

### ISSUE THREAD

**Issue by Anas-Elgarhy** [files-community/Files#7645]
- There are many sentences that have not been translated into Arabic, such as:
https://github.com/files-community/Files/blob/5580cc7c7c9d431dcafd2dedf940258dfe3d1503/src/Files/Strings/ar/Resources.resw#L1240
https://github.com/files-community/Files/blob/5580cc7c7c9d431dcafd2dedf940258dfe3d1503/src/Files/Strings/ar/Resources.resw#L964
https://github.com/files-community/Files/blob/5580cc7c7c9d431dcafd2dedf940258dfe3d1503/src/Files/Strings/ar/Resources.resw#L856
https://github.com/files-community/Files/blob/5580cc7c7c9d431dcafd2dedf940258dfe3d1503/src/Files/Strings/ar/Resources.resw#L664

- The translation of a byte into Arabic is supposed to be "بايت", not the letter B.
https://github.com/files-community/Files/blob/5580cc7c7c9d431dcafd2dedf940258dfe3d1503/src/Files/Strings/ar/Resources.resw#L421

**Comment by Josh-65** [comment]
These can be all in one issues

**Comment by Anas-Elgarhy** [comment]
Well, I've opened up a few issues already but I'll put them together here and close the rest, thanks for your comment <3

**Comment by Anas-Elgarhy** [comment]
Am I translating them? Or is there a reason not to translate these particular sentences?

**Comment by yaichenbaum** [comment]
@Anas-Elgarhy would you like to update the translations?

**Comment by Anas-Elgarhy** [comment]
Yes, of course

**Comment by gave92** [comment]
Thanks! Here's how to translate, if needed: https://files.community/docs/contributing/translating-files

**Comment by Anas-Elgarhy** [comment]
@gave92 What is the difference between the file `src\Files\Strings\ar\Resources.resw` and the file `src\Files\MultilingualResource\Files.ar.xlf` I noticed that the file `Files.ar.xlf` contains more strings, huh Is the `Resources.resw` file generated from it?

**Comment by gave92** [comment]
You only need to touch the XLF. Resw is automatically generated from it.
