### ISSUE TITLE
Windows drive not showing with WSL 2

### ISSUE THREAD

**Issue by frankhuurman** [files-community/Files#7646]
### Description

I'm using Win 10 Home together with WSL 2 Ubuntu 20.04 and when I open up Files(installed through the Windows Store) it seems to pick up on my WSL 2 Ubuntu as my main system.

It doesn't seem to pick up on any Drive and I'm unable to get to my "This PC" to get an overview of my disk usage and such.
The Folders at the top (Documents/Downloads etc) dó actually link to my C: Windows drive but I can't get to the root layer of it all.
The dropdown top-left only seems to show WSL and Docker things.

### Steps To Reproduce

1. Install Ubuntu 20.04 on Windows 10 with WSL 2 enabled
2. Install Files Version: 2.1.0.0 through the Microsoft Store
3. Open Files and see that it uses Ubuntu instead of Windows as a root dir

### Expected behavior

I expected Files to give me an overview of "This PC" with my C: drive and the storage percentages. I did not expect my Ubuntu home directory to be picked up as the main entry point for Files with no way to return to some sort of disk overview.

### Files Version

2.1.0.0

### Windows Version

10.0.19043.1466

### Relevant Assets/Logs

![Screenshot 2022-01-14 144331](https://user-images.githubusercontent.com/19980966/149527400-38492fe3-7a3f-45d4-8268-7faa487d0eef.png)

**Comment by gave92** [comment]
Thanks for the report. Could you upload the app's debug files (from settings > about)? Also the Store version is currently broken, could you try installing the [sideloaded version](https://filescommunity.blob.core.windows.net/files/stable/Files.Package_2.1.0.0_Test/Files.Package_2.1.0.0_x86_x64_arm64.msixbundle) instead?

**Comment by frankhuurman** [comment]
Thanks for the quick response!
With debug files do you mean opening the log location and sharing the debug.log and debug_fulltrust.log here?

**Comment by gave92** [comment]
Yeah, thanks

**Comment by frankhuurman** [comment]
[debug.log](https://github.com/files-community/Files/files/7875239/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7875240/debug_fulltrust.log)

There you go! 👍

**Comment by gave92** [comment]
I can confirm this is an issue affecting only the Store version, a fix is in the works. In the meantime you may switch to the sideloaded version linked above.
