### ISSUE TITLE
Hover over music, videos, text and preview them.

### ISSUE THREAD

**Issue by tiger360** [files-community/Files#7654]
### What's the Problem?

I'd like a feature that lets you hover over things without pressing anything. 
It can preview music, videos, text, pdf ...

### Solution/Idea

Kind of the feature in QTTabBar.

### Alternatives

Or make an integration of QTTabBar 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by Anas-Elgarhy** [comment]
Won't this feature affect performance?, especially that the performance is currently lower than the default file browser for Windows (explorer.exe) and less than most of the file browsers available in Linux

**Comment by gave92** [comment]
Could you clarify the benefits over the current preview pane?

**Comment by yaichenbaum** [comment]
> Could you clarify the benefits over the current preview pane?

It's quicker to hover over a thumbnail than to select an item. There is a similar feature request to add this behavior for gifs. I'm pretty sure the request is to display the preview over thumbnail.

**Comment by tower-town** [comment]
maybe QuickLook(https://github.com/QL-Win/QuickLook) can help you

**Comment by Josh-65** [comment]
Asking @yaichenbaum for approval.

**Comment by yaichenbaum** [comment]
We're still waiting for some context from the author if this issue is to preview items in the preview pane or thumbnail.

**Comment by Josh-65** [comment]
@tiger360 Can you answer the above question

**Comment by yaira2** [comment]
With QuickLook, you can press space to open the preview and use the arrow keys to switch between files.
