### ISSUE TITLE
Crashes on Pressing Back on Mouse

### ISSUE THREAD

**Issue by MarcelLang** [files-community/Files#7655]
### Description

Crash on pressing back-button on mouse (MX Master 3)

### Steps To Reproduce

1. Open Drive C:\
2. Press the back-button on mouse (not the arrow/software button)
3. Press the back-button on mouse (not the arrow/software button) again 
4. Crash.

### Expected behavior

Not crash.

### Files Version

2.1.0.0

### Windows Version

Windows 11 21H2 Build 22000.376

### Relevant Assets/Logs

Name der fehlerhaften Anwendung: files.exe, Version: 0.0.0.0, Zeitstempel: 0x61db1062
Name des fehlerhaften Moduls: Windows.UI.Xaml.dll, Version: 10.0.22000.348, Zeitstempel: 0x003360cd
Ausnahmecode: 0xc000027b
Fehleroffset: 0x0000000000834af0
ID des fehlerhaften Prozesses: 0x711c
Startzeit der fehlerhaften Anwendung: 0x01d80979ff5047a9
Pfad der fehlerhaften Anwendung: C:\Program Files\WindowsApps\49306atecsolution.FilesUWP_2.1.0.0_x64__et10x9a9vyk8t\files.exe
Pfad des fehlerhaften Moduls: C:\Windows\System32\Windows.UI.Xaml.dll
Berichtskennung: a0def590-229b-4016-916a-73bb249db721
Vollständiger Name des fehlerhaften Pakets: 49306atecsolution.FilesUWP_2.1.0.0_x64__et10x9a9vyk8t
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: App

Fehlerbucket , Typ 0
Ereignisname: MoAppCrash
Antwort: Nicht verfügbar
CAB-Datei-ID: 0

Problemsignatur:
P1: 49306atecsolution.FilesUWP_2.1.0.0_x64__et10x9a9vyk8t
P2: praid:App
P3: 0.0.0.0
P4: 61db1062
P5: combase.dll
P6: 10.0.22000.282
P7: 426c1ced
P8: 80004003
P9: 000000000005c41b
P10: 

Angefügte Dateien:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.3b0d6da6-d1ad-4183-bb9d-9c81aee5a8c5.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.8a34d3f5-d2cf-4c43-81a2-daf15fe7b3d9.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.b4ac31c7-1d41-45b0-8db1-a753c140a85e.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.795d7acc-2a9b-470f-8d18-f452df5157d2.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.c8a416ec-27aa-40bb-b430-ec9e01f88530.tmp.txt
\\?\C:\Users\Marcel\AppData\Local\Temp\WER.4da99619-2df8-417d-94a8-62f2d0ffcf88.tmp.appcompat.txt

Diese Dateien befinden sich möglicherweise hier:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_49306atecsolutio_e5cb202342ae96369da220daf81585f2b79cc21_24c58fae_cab_8aa5f15c-7957-48d1-bc79-ba34e9544074

Analysesymbol: 
Es wird erneut nach einer Lösung gesucht: 0
Berichts-ID: a0def590-229b-4016-916a-73bb249db721
Berichtstatus: 4
Bucket mit Hash: 
CAB-Datei-Guid: 0

Fehlerbucket 1993756618420721028, Typ 5
Ereignisname: MoAppCrash
Antwort: Nicht verfügbar
CAB-Datei-ID: 0

Problemsignatur:
P1: 49306atecsolution.FilesUWP_2.1.0.0_x64__et10x9a9vyk8t
P2: praid:App
P3: 0.0.0.0
P4: 61db1062
P5: combase.dll
P6: 10.0.22000.282
P7: 426c1ced
P8: 80004003
P9: 000000000005c41b
P10: 

Angefügte Dateien:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.3b0d6da6-d1ad-4183-bb9d-9c81aee5a8c5.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.8a34d3f5-d2cf-4c43-81a2-daf15fe7b3d9.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.b4ac31c7-1d41-45b0-8db1-a753c140a85e.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.795d7acc-2a9b-470f-8d18-f452df5157d2.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.c8a416ec-27aa-40bb-b430-ec9e01f88530.tmp.txt
\\?\C:\Users\Marcel\AppData\Local\Temp\WER.4da99619-2df8-417d-94a8-62f2d0ffcf88.tmp.appcompat.txt

Diese Dateien befinden sich möglicherweise hier:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_49306atecsolutio_e5cb202342ae96369da220daf81585f2b79cc21_24c58fae_8aa5f15c-7957-48d1-bc79-ba34e9544074

Analysesymbol: 
Es wird erneut nach einer Lösung gesucht: 0
Berichts-ID: a0def590-229b-4016-916a-73bb249db721
Berichtstatus: 268435456
Bucket mit Hash: de4ac56d4e193dfbbbab3f14c18d1584
CAB-Datei-Guid: 0

**Comment by gave92** [comment]
Could you upload the app's log files (from settings > about > open log location)? Are you using column view layout?

**Comment by MarcelLang** [comment]
I like to do that very much. I hope these two files are the right ones.

[debug.log](https://github.com/files-community/Files/files/7872708/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7872709/debug_fulltrust.log)

> I like to do that very much. I hope these two files are the right ones.

Yes. It seems to me that the error occurs when I was, or am, in a column view.

**Comment by gave92** [comment]
Perfect thank you. I can confirm that this issue has been fixed and we will publish a patch soon.
