### ISSUE TITLE
Program Closed

### ISSUE THREAD

**Issue by PeterWBoyer** [files-community/Files#7658]
### Description

Running the program, as usual, and a message came up on Windows 11 saying "something went wrong, report a bug". The program had closed. I do not know why. I wasn't doing anything at the time. Just the message & the program closed.

### Expected behavior

i expected the program to continue running.

### Files Version

Version 2.1.0.0

### Windows Version

Windows 11 Home 10.0.22000

### Relevant Assets/Logs

Nothing to attach

**Comment by gave92** [comment]
Please upload the app's debug logs. You can get them from Files settings > About > Open log location.
