### ISSUE TITLE
Themes don't apply when downloaded from community repository

### ISSUE THREAD

**Issue by T0bycat** [files-community/Files#7662]
### Description

Themes do not apply after setting them.

### Steps To Reproduce

1. Navigate to files theme folder
2. Open in terminal
3. Use `wget` `pip` package to download a specific .xaml theme from Github.
4. restart files, as the theme[s] doesn't show up immediately.
5. Apply a theme in the settings menu.

### Expected behavior

I expected the theme to apply when i click it.  and it doesn't work when i restart either.

### Files Version

Version: 2.1.0.0 OS Version: 10.0.19043.1466

### Windows Version

Windows 10 10.0.19043 Build 19043

### Relevant Assets/Logs

![vlc_LNNOach8cW](https://user-images.githubusercontent.com/53319478/149597945-f0978b43-254a-4818-bbe9-a260b09d07eb.gif)
[debug.log](https://github.com/files-community/Files/files/7873786/debug.log)

**Comment by Josh-65** [comment]
Try download one from here (https://github.com/files-community/Custom-themes/tree/main/CustomThemesPackage) and put it in the themes folder via the I icon on the the custome theme section

**Comment by yaichenbaum** [comment]
@T0bycat it looks like those themes work with mica which is not supported on Windows 10, we're redoing the theme files to make sure they all support acrylic but in the meantime, you can try the acrylic or glass theme.
