### ISSUE TITLE
May I copy or move multi target and overwrite by one click?

### ISSUE THREAD

**Issue by hastonewy** [files-community/Files#7663]
### What's the Problem?

May I copy or move multi target and overwrite by one click?

### Solution/Idea

need a button with dropdown list contains [overwrite/skip/autorename]  all current targets

### Alternatives

none...

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.0.0

### Windows Version

win10 21h1

**Comment by Josh-65** [comment]
if your talking about the confilct dialog when copy/moveing using Ctrl+A then selected an option in any of the boxes wll apply them. A better way is beeing tracked in #5645
