### ISSUE TITLE
In the network folder i can see my network computers

### ISSUE THREAD

**Issue by abirabedinkhan** [files-community/Files#7664]
### Description

In the network folder, i can see my network computers
but in wondow explorer i can see them

### Expected behavior

there should be shown my network computers

### Files Version

2.0.34

### Windows Version

Windows 11 build 22000

### Relevant Assets/Logs

In the network folder, i can see my network computers
but in wondow explorer i can see them

**Comment by gave92** [comment]
Merging with #7227
