### ISSUE TITLE
Changes to folders content from completed network tasks don't appear in the main Files window without a manual refresh

### ISSUE THREAD

**Issue by metaltermite** [files-community/Files#7665]
### Description

Completed tasks (renaming a file/folder, creating a new file/folder, deleting a file/folder, etc) on a network folder or mapped network drive are not reflected in the main window. A manual refresh of the main window (F5) is required to show any changes from the completed task.

### Steps To Reproduce

1. Go to any network folder or mapped network drive
2. Navigate to any folder on the network
2. Rename any file or folder (or create a new file or folder, or delete a file or folder)

### Expected behavior

The new file or folder name should appear instantly (or if a new file was created the new file should appear immediately, or if a file was deleted the file should disappear immediately)

### Files Version

Version: 2.1.0.0 OS Version: 10.0.19043.1466

### Windows Version

Windows 10 Home 21H1 19043.1466

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7874180/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7874181/debug.log)

**Comment by gave92** [comment]
Tracked in #5869
