### ISSUE TITLE
Provide installer for those who can't sideload

### ISSUE THREAD

**Issue by CharlotteCross1998** [files-community/Files#7666]
### What's the Problem?

My windows install can't install appx files. It would be nice to have a traditional installer so I wouldn't have to download Visual Studio just to be able to use this program.

### Solution/Idea

Provide a traditional installer.

### Alternatives

Additional build instructions that don't require Visual Studio

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to install the program the way most people are used to | Should |
| This proposal will allow end users to build the program without the need for Visual Studio | Could |

### Files Version

2.1

### Windows Version

Windows 10 Version 1909 (Build 18363.836)

**Comment by Josh-65** [comment]
Files is a UWP app that only has the 1 installer type so your only option would be VS.

**Comment by HimusakiProgramming** [comment]
Yes
I also want one Installer as well as portable version

**Comment by yaichenbaum** [comment]
@CharlotteCross1998 thank you for the request, UWP apps like Files are packaged and requires appinstaller so it's not posible for us to provide a portable version.

**Comment by CharlotteCross1998** [comment]
> @CharlotteCross1998 thank you for the request, UWP apps like Files are packaged and requires appinstaller. Unfortunately, it's not possible for us to provide a portable version.

I wasn't aware it's not a possibility, that's a shame.
