### ISSUE TITLE
Sidebar section does not correctly remember the state before the files is closed

### ISSUE THREAD

**Issue by rstanuwijaya** [files-community/Files#7667]
### Description

The sidebar should retain the state before the app is restarted. However, most of the time, I noticed that the sidebar does not automatically expand after the app is restarted, even though the arrow icon next to the label is indicating that the state is saved.

### Steps To Reproduce

1. Open files, expand one of the sidebar categories, i.e. "SidebarFavorites", now the arrow icon is pointing downwards and all the items are shown
2. Close and reopen files
3. Notice that only the arrow is still pointing downwards, but the items are no longer shown

### Expected behavior

on 3. the items should be shown as before the app is closed. If possible, add an option to either reset or store the state.

### Files Version

Version: 2.1.0.0 OS Version: 10.0.22000.376

### Windows Version

Windows 11 Home 21H2 22000.376

### Relevant Assets/Logs

![Before restarting the app](https://user-images.githubusercontent.com/55012032/149614136-cc9cd303-20cc-4ab2-831d-a3d30997aa1e.png)
![After restarting the app](https://user-images.githubusercontent.com/55012032/149614144-f722f956-3904-4400-845a-aae5869ea3e6.png)

**Comment by gave92** [comment]
Tracked in #6469
