### ISSUE TITLE
Create Portable Version as well as Installer

### ISSUE THREAD

**Issue by HimusakiProgramming** [files-community/Files#7670]
### What's the Problem?

I want Portable Version as well as Installer so i can hop around different os in my vmware.

### Solution/Idea

I need portable verison

### Alternatives

no alternative 
i need portable and installer version.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by Josh-65** [comment]
Files is a UWP app that only has the 1 installer type so your only option would be VS. Not sure if a portable version is possible.

**Comment by gave92** [comment]
Portable version is not possible for uwp apps. You can install the app without the Store though by using the [msix package](though.https://filescommunity.blob.core.windows.net/files/stable/Files.Package_2.1.0.0_Test/Files.Package_2.1.0.0_x86_x64_arm64.msixbundle).
