### ISSUE TITLE
i cant rollback to windows default file explorer after uninstalling files

### ISSUE THREAD

**Issue by newraozx1** [files-community/Files#7671]
### What's the Problem?

If files is set to default insted of windows file explorer then after unistalling files windows wont roll back to its original file explorer and gives error of app not found.

### Solution/Idea

Please fix this so after uninstalling files, everything returns to the state what it was before. People who are not into computers won't be able to fix it on their own, just like me.:(

### Alternatives

..

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.0.0

**Comment by gave92** [comment]
You can revert to explorer by running this script (make sure to save it as a ".reg" file):
https://raw.githubusercontent.com/files-community/Files/main/src/Files.Launcher/Assets/FilesOpenDialog/UnsetFilesAsDefault.reg

**Comment by newraozx1** [comment]
thank you ,it worked :)

**Comment by SonGokussj4** [comment]
Thanks. This worked for me too. But I wouldn't call this "closed". There should be an option in the menu of Files settings.

I tried it today for a little while, noticed it's much slower for opening folder, wanted to go back (after I tried setting it as default) and I couldn't have without searching and finding this issue.

**Comment by gave92** [comment]
@SonGokussj4 glad the script it worked. I assume you tried to disable the feature from the toggle switch in Files settings but it didn't work?

**Comment by SonGokussj4** [comment]
Yeah. When I switched it on, UAC showed for registry edit. A few minutes later, when I switched it off, nothing happened and I started searching for a solution.

I installed it through Microsoft Store.

**Comment by gave92** [comment]
Tracking in #7626
