### ISSUE TITLE
Dual pane keyboard shortcut

### ISSUE THREAD

**Issue by Azakiradev** [files-community/Files#7672]
### What's the Problem?

The current keyboard shortcut for opening dual pane view is Alt+Shift++
In some keyboard layouts such as English(UK), the + is typed by pressing Shift+=, which is not a problem in keyboards with a numpad since you can use the numpad for the + input, but on keyboard without such numpad like most laptops, the shortcut is inaccessible.

### Solution/Idea

I suggest adding a panel in preferences to change the keyboard shortcuts to anyone's liking and avoid all possible issues of this kind.

### Alternatives

Alternatively, the current shortcut should be changed from a + to any letter

### Priorities

| Capability | Priority |

| This proposal will allow developers to accomplish an easier time ensuring accessibility in any form factor | Should |
| This proposal will allow end users to accomplish a more customizable and productive experience | Should |

### Files Version

Version: 2.1.0.0

### Windows Version

Windows 11 Home Insider Preview Version	Dev 22533.1001

**Comment by gave92** [comment]
Merging with #9559

**Comment by yaira2** [comment]
@Azakidev This feature will be included in the next release. Please see #9559 for more details.
