### ISSUE TITLE
Network Drives not showing up.

### ISSUE THREAD

**Issue by TLC-John** [files-community/Files#7673]
Hi there,

Firstly may I say, what a great tool Files is, love it!

One thing I have noticed is that our home network drives are not showing up within Files.  On the old windows explorer, they are showing up.

Is there something in need to turn on or off for these drives to show up?

Thank you for any help you can give me with this.

All the very best.

Cheers
John

**Comment by Josh-65** [comment]
Have you assigned them as a drive with a drive letter or are you using the network search page.

**Comment by aWeinzierl** [comment]
For me they don't show up until they are connected

**Comment by gave92** [comment]
Merging with #7843 / #7627
