### ISSUE TITLE
Can´t open old control panel/ cant return to windows explorer

### ISSUE THREAD

**Issue by igorqpedroso** [files-community/Files#7674]
### Description

Can´t open open old windows control panel even with CMD, it open Files
Then I tried using UnsetFilesAsDefault.Reg and when I tried oppening control panel, it opens windows explorer
Finally, when I tried to return to the original windows explorer, I coudnt open some folders, it returns to windows explorer main menu

And, dumb as I am, I didnt made a registry backup. Could you help me fix my registry? :)

### Expected behavior

.

### Files Version

2.1

### Windows Version

Windows 11 21H2 1000.22000.376.0

### Relevant Assets/Logs

.

**Comment by ayoubsousali** [comment]
same problem i can't open original Files Explorer and Control panel after  setting Files as default files explorer

**Comment by ayoubsousali** [comment]
https://github.com/files-community/Files/issues/7626#issuecomment-1013469616

@igorqpedroso this one solved the issue for me, the File Explorer  and the Control Panel are working

**Comment by igorqpedroso** [comment]
@ayoubsousali thanks a lot!! It worked here to
