### ISSUE TITLE
Crash before syncing with Google Drive

### ISSUE THREAD

**Issue by PushingTrooper** [files-community/Files#7675]
### Description

The app crashed when I opened a folder that was synced with Google Drive(my Documents folder located not in the default windows location), at first it was working not as fast but I figured that was some caching thing, the Google Drive Synced icons didn't show in any of the folders and when I tried to paste some files from my Desktop to a folder in my Documents it crashed. Then when I opened it again it the Synced icons showed up and everything worked as expected

### Steps To Reproduce

1. Make sure Google Drive is working on both the Desktop and Documents
2. Cut some files from the Desktop
3. Go to Documents(located in a separate drive) (at this point no Google Drive icons should appear)
4. Create new Folder for new files
5. Paste the files there
6. App should crash

### Expected behavior

App shouldn't crash and paste the files

### Files Version

Version: 2.1.0.0 OS Version: 10.0.22000.434

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎30/‎12/‎2021 OS build	22000.434 Experience	Windows Feature Experience Pack 1000.22000.434.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7875167/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7875168/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
@PushingTrooper is this still an issue in the preview version? https://files.community/download/preview
