### ISSUE TITLE
Lists are blank when opening Files, loads in after 1 - 2 minutes

### ISSUE THREAD

**Issue by C4uTi0N** [files-community/Files#7676]
### Description

When i open Files it is often blank in the left pane as well as the "drives" section, making it unusable

![when openning Files](https://user-images.githubusercontent.com/45887100/149625871-21d5f62c-e6ca-4cf0-b7aa-b3515146e412.png)

### Steps To Reproduce

1. Open Files from either taskbar or windows start menu
2. it's blank

### Expected behavior

Everthing should just show up immediately

### Files Version

Version: 2.1.0.0 OS Version: 10.0.19044.1466

### Windows Version

Windows 10 21H2 build 19044.1466

### Relevant Assets/Logs

![when openning Files](https://user-images.githubusercontent.com/45887100/149625840-603fb351-5a3f-4131-a079-afabcefb088c.png)
![after about a minute](https://user-images.githubusercontent.com/45887100/149625844-3a8e84fa-d2fa-47da-8c31-baa1b91abb43.png)

**Comment by gave92** [comment]
Thanks for the report. Please upload the apps debug files (from setting > about > open log location)

**Comment by C4uTi0N** [comment]
[debug.log](https://github.com/files-community/Files/files/7875403/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7875429/debug_fulltrust.log)

**Comment by Dai-Prazz** [comment]
I'm facing the same issue.

**Comment by ZXY-CC-3ag13** [comment]
It seems minimizing and then restoring the app temporary solves the issue.
You're welcome.

_Originally posted by @Tarek-Hasan in https://github.com/files-community/Files/issues/7554#issuecomment-1012234173_

**Comment by gave92** [comment]
Merging with #7554
