### ISSUE TITLE
Folder and files preview like in qttabbar 

### ISSUE THREAD

**Issue by Ergoprett** [files-community/Files#7677]
### Solution/Idea

For years, I used the explorer with qttabbar and i really miss the feature to hover over folders and files to see a preview.

### Alternatives

Right now I'm using the preview tab on the right, but it doesn't work with folders and also not with hovering like in qttabbar 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by gave92** [comment]
Tracked in #7654
