### ISSUE TITLE
Image thumbnail

### ISSUE THREAD

**Issue by Noisemagician** [files-community/Files#7678]
### Description

Most thumbnails in Files explorer won't load, some do. Tried everything in the settings. thumbnails do show in windows explorer. 

### Expected behavior

Hello,

First I like to thank you for your hard work in making this amazing product, so far I am enjoying it very much.
I do have a problem, I am a photoshop artist and work with a lot of images, the file explorer doesn't load the thumbnails (windows explorer does show them). I have tried everything in the setting or deleting the cache but for files explorer, this doesn't work.

What I did find to work is to open ALL of the images, close files explorer, and then open files again. The thumbnails show now but to do this for every folder and every image is a bit of a hassle. Could you repair this issue, please?

Thank you for your hard work, have a nice day. 

### Files Version

Version: 2.1.0.0 OS Version: 10.0.19043.1466

### Windows Version

Edition	Windows 10 Home Version	21H1 Installed on	‎16/‎09/‎2021 OS build	19043.1466 Experience	Windows Feature Experience Pack 120.2212.3920.0

### Relevant Assets/Logs

![Untitled](https://user-images.githubusercontent.com/84987848/149628090-433bc338-c9a7-4617-933f-7f501c6d7cdd.png)

**Comment by topbun92** [comment]
same issue. i assumed it was just when the app was first opened after cold boot but it seems to just be random. i can open Files and everything pops up immediately, really snappy. Then like 15 minutes later if i need to open Files again it will take a good 30 seconds to load all my drives

**Comment by gave92** [comment]
Thanks for the report. This is unfortunately a known issue. Merging with #6130.
