### ISSUE TITLE
Make it clear how to set Files to open at windows startup if consent dialog has been declined

### ISSUE THREAD

**Issue by willynanita** [files-community/Files#7679]
### Description

I tried to set the app to start with Windows, but I accidently pressed on decline or something, now I can't set it to open with Windows.

### Steps To Reproduce

Set the app to start with windows, turning on the feature, press on no or decline on the next window. Now I can't turn it on again.

### Expected behavior

The turn on or off should be always available.

### Files Version

Version: 2.1.0.0

### Windows Version

Windows Version: 10.0.22000.434

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7875351/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7875352/debug_fulltrust.log)
![Screenshot 2022-01-15 121709](https://user-images.githubusercontent.com/97799301/149629174-3b2d966c-d415-4366-9e22-9d855316f7fb.jpg)

**Comment by Josh-65** [comment]
Try checking task manager and see if the startup tab has files disabled

**Comment by willynanita** [comment]
Thank you! That was it.

**Comment by gave92** [comment]
Thanks for the report. I believe it's a good idea to provide a link to startup settings or at least add an explanation about how to enable the setting if the dialog was not accepted.

**Comment by yaira2** [comment]
This will be resolved in the next update.
