### ISSUE TITLE
Cannot open Zip folders on arm64 devices

### ISSUE THREAD

**Issue by topbun92** [files-community/Files#7680]
### Description

When attempting to open a zip folder with Files, i get a pop up that says "Drive Unplugged, Not a Folder". i click ok on the popup and the folder shows up empty. 

### Steps To Reproduce

double click zip folder

### Expected behavior

opens folder, shows contents

### Files Version

V2.1

### Windows Version

Windows 11 21H2 22000.434

### Relevant Assets/Logs

![Untitled](https://user-images.githubusercontent.com/87154955/149630057-f9d964b7-2065-4fef-891d-737132083183.png)

**Comment by gave92** [comment]
What have you set as default app for opening zip files?

**Comment by topbun92** [comment]
when i look at Files in the Default apps view in windows settings, it says Files is set as default app for .zip files. 

as a side note, i do have 7zip installed, its just not set as default for...anything it looks like

**Comment by gave92** [comment]
Does it happen with any zip file? Are those files password-prorected? Could you share one of the non-working zip files?

**Comment by topbun92** [comment]
none are password protected. i actually don't have any currently, i noticed it when i downloaded a zip from github containing custom themes for Files. i could get the files out by right clicking and "extract here".  but i could not just open the folder and view its contents prior to extraction like you can in windows file explorer.

https://github.com/files-community/Custom-themes

i then created some dummy .txt and .docx files to zip and try reopening, those didn't work either.

**Comment by TheDiamondGen** [comment]
It happened for me as well, change default zip app to file explorer in settings. Then all of the zip files will work and they will open in files. Its weird.

**Comment by CessnaBroon** [comment]
I also experience this issue.

**Comment by gave92** [comment]
@CessnaBroon, @topbun92 does @TheDiamondGen suggestion work for you? (Try setting file explorer or Files as default app for zip files)

**Comment by CessnaBroon** [comment]
> @CessnaBroon, @topbun92 does @TheDiamondGen suggestion work for you? (Try setting file explorer or Files as default app for zip files)

Setting file explorer as default fixes, but setting default as Files results in a message 'No such interface supported'.

**Comment by CessnaBroon** [comment]
Still getting this error.

**Comment by MystikReasons** [comment]
I also get the error when trying to open .zip files

**Comment by dennorske** [comment]
I can also chime in on this.

What I have tried:
1. Assign files as default app for ZIP.
2. Reassign explorer, and then back to files.
3. Tried several different ZIP files, not only one. Even the ones I have zipped.
4. Opening in explorer works fine.
5. Reinstalling Files (clearing all local data, resetting settings)

Can I contribute in any meaningful way with debug logs? I am happy to do so. This app is so cool and I'd be happy to help how I can. Thank you

**Comment by yaichenbaum** [comment]
@dennorske do you have any experience with c#?

**Comment by dennorske** [comment]
Yes, I do, at least a bit 👍

**Comment by yaichenbaum** [comment]
@dennorske we have branch that can potentially fix this issue but there are a few conflicts that need to be resolved before it can be merged, would you be interested in opening a PR to help update the branch with `main`? https://github.com/files-community/Files/pull/8400

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.7.0?

**Comment by yaichenbaum** [comment]
@topbun92 
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by yaira2** [comment]
I'm excited to share that this issue will be fixed in the upcoming v3.6 release.
