### ISSUE TITLE
Skip/Overwrite/Rename All option in file transfer queue

### ISSUE THREAD

**Issue by t9999clint** [files-community/Files#7681]
### What's the Problem?

Current behavior is when a conflicting file/folder is detected the entire transfer process is paused untill a decision is made for every individual file.
This makes file transfers where you're just updating a folder with the latest versions extremely tedious. Especially if there's 100+ files.

### Solution/Idea

Currently windows 10 and 11 have a very good approach for this, it continues the non-conflicting files in the background while you make your choices. It also allows for you to choose a resolution for all the files at once.
You should just duplicate this behaviour.

This is the only area where Files is worse than Windows Explorer IMHO

### Alternatives

An alternative solution would be to add the option to use the standard windows file transfer API instead of the one used in files.
Then you can just use the normal windows method, or even a 3rd party tool like teracopy.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish feature parity with the existing windows file transfer API | Could |
| This proposal will allow end users to allow for faster and more easy file transfers with Files. | Should |

### Files Version

2.1.0.0

### Windows Version

Windows 10 21H2 (OS Build 19044.1466)

### Comments

I've never used a template like this before, I hope I didn't fill in anything wrong.

Thanks for your hard work on this project and taking the time to read this.

**Comment by Josh-65** [comment]
If your talking about the confilct dialog when copy/moveing using Ctrl+A then selected an option in any of the boxes will apply them to all. A better way is beeing tracked in #5645

**Comment by yaichenbaum** [comment]
@t9999clint thank you for the feedback, we're going to merge this with #5645 to continue tracking the request.
