### ISSUE TITLE
[feature request] Add open command line shortcut

### ISSUE THREAD

**Issue by M09Ic** [files-community/Files#7683]
### What's the Problem?

In linux, we can use ctrl+shift+t to open the terminal in the current directory.
But in the files docs, I didn't find the corresponding shortcut key. 
If there is, please remind me

### Solution/Idea

add  ctrl+shift+t shortcut to open the terminal in the current directory.

### Alternatives

none

### Priorities

none

**Comment by yaichenbaum** [comment]
Merging with #5607
