### ISSUE TITLE
the application crashes when opening properties

### ISSUE THREAD

**Issue by Luk121** [files-community/Files#7685]
### Description

Everytime i open properties for any folder on my computer and scroll down in properties the application crashes.

### Steps To Reproduce

1.click right on any folder and open properties
2. scroll down in properties and it will crash right away

### Expected behavior

Not to crash.

### Files Version

Version: 2.1.0.0 OS Version: 10.0.19044.1466

### Windows Version

Windows 10 21H2

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7875916/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7875917/debug.log)

**Comment by gave92** [comment]
@yair100 is this the issue you were experiencing as well?

**Comment by yair100** [comment]
> @yair100 is this the issue you were experiencing as well?

Yes

**Comment by Luk121** [comment]
yes
