### ISSUE TITLE
Self-hosted Nextcloud not appearing in Cloud Storages

### ISSUE THREAD

**Issue by koelle25** [files-community/Files#7687]
### Description

Hello :)

Despite #7401 my 2 configured accounts of some self-hosted Nextcloud instances are not being listed under the _Cloud Storages_ section in the sidebar.

I had a look at the code and have a mild understanding of why this might be.

In [CloudDrivesDetector.cs#L55](https://github.com/files-community/Files/blob/main/src/Files.Launcher/Helpers/CloudDrivesDetector.cs#L55) the value of the `Default` key (empty key name) is used.
In case of my 2 Nextcloud instances this not only contains the string `"Nextcloud"` but also an identifier (_user@domain_) for this account/instance, see screenshots in the Assets/Log section of this bug report.
Because the switch in [CloudDrivesDetector.cs#L73](https://github.com/files-community/Files/blob/main/src/Files.Launcher/Helpers/CloudDrivesDetector.cs#L73) expects the string to just contain "Nextcloud" this registry key is then skipped.

As you can also see in the screenshots there is another key `ApplicationName` containing just the expected string `"Nextcloud"` which could be used instead, e.g. by modifying [L55](https://github.com/files-community/Files/blob/main/src/Files.Launcher/Helpers/CloudDrivesDetector.cs#L55) like so¹:
```cs
var driveType = (string?)namespaceKey?.GetValue("ApplicationName") ?: (string)namespaceKey?.GetValue("");
```
But this would later in the code lead to multiple entries in the sidebar just labeled "Nextcloud" and you wouldn't know which one is which.

The default/old Windows Explorer seems to be using the value from the `Default` key (empty key name). I have also attached a screenshot of this below.

_¹ Note: I am not a C# developer. This code snippet could contain errors._

### Steps To Reproduce

1. Install [Nextcloud Desktop-Client](https://nextcloud.com/install/#install-clients)
2. [Configure](https://docs.nextcloud.com/desktop/3.4/installing.html#installation-wizard) an account for a (self-hosted) Nextcloud instance
3. Feel the pain of manually navigating to the Nextcloud folder everytime

### Expected behavior

Any account configured in the Nextcloud Desktop-Client appears as a (distinguishable) entry under the _Cloud Storages_ section in the sidebar.

### Files Version

Version: 2.1.0.0 OS Version: 10.0.19043.1466

### Windows Version

Windows 10 Education Edition, Version 21H1, Build 19043.1466, Windows Feature Experience Pack 120.2212.3920.0

### Relevant Assets/Logs

<details>
<summary>Screenshot of Files app NOT listing Nextcloud accounts/folders:</summary>

![(New) Files app NOT listing Nextcloud accounts/folders](https://user-images.githubusercontent.com/915514/149639693-bd0ea2aa-36b6-458b-b1c3-7cd6e56d7e71.png)
</details>

<details>
<summary>Screenshots of HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Desktop\NameSpace:</summary>

![HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Desktop\NameSpace\Nextcloud-Instance-1](https://user-images.githubusercontent.com/915514/149639533-032e5ead-f2e3-4f4d-ab3e-d9d6b1c83a7f.png)
![HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Desktop\NameSpace\Nextcloud-Instance-2](https://user-images.githubusercontent.com/915514/149639534-8581fa12-73b6-4b4a-a28b-88fe6138f150.png)
</details>

<details>
<summary>Screenshot of old/default Windows Explorer sidebar listing Nextcloud accounts:</summary>

![Old/Default Windows Explorer sidebar listing Nextcloud accounts](https://user-images.githubusercontent.com/915514/149639537-e8f73905-9f14-4078-81f4-c3e9f5111680.png)
</details>

**Comment by d2dyno1** [comment]
#7763 Should resolve this issue
