### ISSUE TITLE
App crashed

### ISSUE THREAD

**Issue by Galloclau** [files-community/Files#7689]
### Description

I was browsing my files, and had 3 tabs open in the app window.
It suddenly froze and force-closed, I don't know why.

### Expected behavior

It shouldn't crash while using the app for a simple task as this one.

### Files Version

Versión: 2.1.0.0 OS Version: 10.0.19044.1415

### Windows Version

Windows 10 21H2 19044.1415

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7876035/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7876036/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
@Galloclau is this still an issue in the preview version? https://files.community/download/preview
