### ISSUE TITLE
CD tracks support

### ISSUE THREAD

**Issue by upintheairsheep** [files-community/Files#7690]
### What's the Problem?

Files does not support audio cds

### Solution/Idea

Make when you insert a CD or an audio DVD, the filesystem acts like the mp3 or audio files are there as tracks. Basically like the Macintosh does.

### Alternatives

iTunes, VLC

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?
