### ISSUE TITLE
"Programs" or "Applications" folder

### ISSUE THREAD

**Issue by upintheairsheep** [files-community/Files#7691]
### What's the Problem?

There is no programs folder

### Solution/Idea

Make a "Applications" folder that shows all you Win32, Metro, UWP, and MSIX apps. All this means is the https://www.google.com/amp/s/www.techrepublic.com/google-amp/blog/windows-and-office/quick-tip-add-an-applications-folder-to-the-windows-8-desktop/

Tip from windows 8 and 10 and 11.

### Alternatives

DIY

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
Thank you for opening this feature request, you can already do this by creating a library and adding the different applications folders to the library.
