### ISSUE TITLE
Tree view in left panel

### ISSUE THREAD

**Issue by rusty-boffin** [files-community/Files#7692]
### What's the Problem?

The left hand panel shows a tree view with **Favourites**, **Drives**, **Cloud Drives**, and **Network drives** (I'm not sure why that has a lower case D) - this is similar to the Navigation Manager in the File Explorer. Each of these expands to a selection  but unlike the File Explorer these lower items are not expandable. Since I do most of my navigation in the Navigation Manager, this makes Files clumsy from my point of view.

### Solution/Idea

Make the left hand panel function more like the Navigation Manager by making all folders (drives, directories, zipfiles, etc) fully expandable.

### Alternatives

I've tried using the columns view but I really don't like it - it's very wasteful of screen real estate. A TreeView of the directory structure is much more efficient (and shouldn't be difficult to implement).

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version 2.1.0.0

### Windows Version

Edition	Windows 10 Pro Version	21H2 Installed on	‎13/‎09/‎2021 OS build	19044.1466 Experience	Windows Feature Experience Pack 120.2212.3920.0

**Comment by yaichenbaum** [comment]
Merging with #1928

**Comment by yair100** [comment]
@rusty-boffin Tree View is currently available in preview https://files.community/download. It will be included in the next stable release.
