### ISSUE TITLE
Control Panel issues

### ISSUE THREAD

**Issue by benas5** [files-community/Files#7694]
### Description

After installing Files, Control Panel opens as Files' new window called "Home".
If Files is uninstalled and Control Panel is being opened, the error displays: "shell::::{52205fd8-5dfb-447d-801a-d0b52f2e83e1} Application not found" as well as opening Explorer "Explorer. EXE Application not found"

### Steps To Reproduce

1. Open Windows start menu
2. Search for "Control Panel"
3. Open Control Panel

### Expected behavior

Opening Control Panel should provide actual panel, not Files' new window which leads to "Home" page.

### Files Version

2.1.0.0

### Windows Version

Windows 11 - 21H2

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/92250874/149644958-cff9266b-f809-4ef2-8888-3955f8de93d7.png)
![image](https://user-images.githubusercontent.com/92250874/149644966-4a9373c0-1114-4265-8709-9e721f24a71d.png)
As research suggests, the bug has to do something with **Registry Editor** path:
[Computer\HKEY_CLASSES_ROOT\Folder\shell\explore\command]

**Comment by yaichenbaum** [comment]
@benas5 can you try running this script and then turning the option to set Files as default on again? https://raw.githubusercontent.com/files-community/Files/main/src/Files.Launcher/Assets/FilesOpenDialog/UnsetFilesAsDefault.reg

**Comment by benas5** [comment]
As it appears, Anti-virus software blocks registry change, but Files still partly commits the change. Everything sets back to normal when setting Files as default file manager on and back off without Anti-virus running.
![image](https://user-images.githubusercontent.com/92250874/149645814-3e1997e0-a85d-4807-ac9a-f6e8aa89eb19.png)
As seen in the image above, 2 out of 4 changes are blocked by Anti-virus such defined as "Trojan"

**Comment by yaichenbaum** [comment]
@benas5 is there an option to report it as a false positive?

**Comment by benas5** [comment]
@yair100 as far as I'm considered, the app functions as intended and without issues, it was my fault assumption to make while using advanced options with running anti-virus system.
Cheers for quick response, keep up the good work!
