### ISSUE TITLE
Files App doesn't remember last session (opened folders) as default explorer

### ISSUE THREAD

**Issue by AdrX003** [files-community/Files#7695]
### Description

The Files App doesn't remember its last session of opened folders with the option turned on+As a Default Explorer app.

There are two main different ways of opening the app, one is as shortcut/lnk and the other is by using it as the default file explorer (As its an experimental option, its an expected behavior but it might help to have this noted when the option receive updates)

### Steps To Reproduce

1. In the **Files App > Experimental** turn On "**Set Files as the Default File Explorer**";
2. Close the app (_maybe to save the configs?_) and open it with either the default explorer key `Win+E` or with a created shortcut;
3. Open multiple folder tabs, only one more is enough;
4. Close the app and re open it with with the default explorer key `Win+E`;
5. Check the last session not opening back.

### Expected behavior

Opening Files App should start the last session of opened folders as normal in any startup method.

### Files Version

2.1.0.0

### Windows Version

Windows 10 Pro 20H2 19042.1466

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/22359798/149645325-783b0d96-1934-48ff-a50e-f755adfde538.png)

**Comment by gave92** [comment]
#7272
