### ISSUE TITLE
Open each files instance in a separate process.

### ISSUE THREAD

**Issue by rihards-simanovics** [files-community/Files#7699]
### What's the Problem?

I have entirely migrated to files about a year ago, and since then, I found that there is one thing that I miss from File Explorer: the ability to open each "file explorer" in a new process.

The reason for that is should one instance misbehave; I can kill it through the task manager while the others will continue to exist, or should the explorer crash (or be restarted), the other instances don't get killed.

Now I understand that there will be an issue with that idea due to the presence of tabs, but I mostly open new instances of the files in a new window.

I believe that we have an issue here similar to that of a browser back in a day where if one tab crashes, the entire application crashes and unfortunately, files crash quite a lot.

### Solution/Idea

add an ability such as in Windows Explorer where a user can open each Files instance in a new process.

Perhaps reading up on chromium source code can give some ideas on how to wrap each tab into its own process to keep the entire application from crashing due to one misbehaving tab.

### Alternatives

None at the moment, but I will update this if I think of any.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to provide a better user experience to an end-user | Should |
| This proposal will allow end-users to have a more stable experience which right now is quite there, should anything go wrong the entire application crashes killing all instances in a domino effect | Should |

### Files Version

Version: 2.1.0.0

### Windows Version

OS: Windows 11 Version: 21H2 Build: 22000.318

### Comments

N/A

**Comment by rihards-simanovics** [comment]
Just did a quick search, perhaps this can help: https://github.com/chromium/chromium/blob/58b25d60e2fa2556bb3a5561792ca274980c3d50/chrome/browser/renderer_host/render_process_host_chrome_browsertest.cc#L183

**Comment by gave92** [comment]
Each Files instance already opens each window in a new process. You can kill each process by going to Details tab in task manager, there will be a 'Files.exe" process for each window

**Comment by rihards-simanovics** [comment]
Hi @gave92 my apologies, it does seem to be so (I have a special folder made to crush anything that attempts to read it). Now I need to figure out why both instances get killed, I'll produce a bug report if I encounter it again.
