### ISSUE TITLE
Option to disable animations

### ISSUE THREAD

**Issue by themisir** [files-community/Files#7700]
I think it might be useful if there is an option to disable listing animations since it takes some time to see content after opening up something.

**Comment by ZXY-CC-3ag13** [comment]
It seems minimizing and then restoring the app temporary solves the issue.
You're welcome.

_Originally posted by @Tarek-Hasan in https://github.com/files-community/Files/issues/7554#issuecomment-1012234173_

**Comment by Tileinstal** [comment]
> It seems minimizing and then restoring the app temporary solves the issue.
> 
> You're welcome.
> 
> 
> 
> _Originally posted by @Tarek-Hasan in https://github.com/files-community/Files/issues/7554#issuecomment-1012234173_

**Comment by themisir** [comment]
> It seems minimizing and then restoring the app temporary solves the issue. You're welcome.
> 
> _Originally posted by @Tarek-Hasan in [#7554 (comment)](https://github.com/files-community/Files/issues/7554#issuecomment-1012234173)_

I don't think that's related to my issue (suggestion). Everything works alright for me. I just thought maybe it might make experience more smooth if contents displayed without animation rather than some sort of fade in animation which takes about .4-.5 second to happen.

**Comment by yaichenbaum** [comment]
@themisir have you tried the option to disable animations in the Windows settings app?

**Comment by themisir** [comment]
> @themisir have you tried the option to disable animations in the Windows settings app?

Nope. I'll try and share my experience with it.

**Comment by Tileinstal** [comment]
> It seems minimizing and then restoring the app temporary solves the issue.
> 
> You're welcome.
> 
> 
> 
> _Originally posted by @Tarek-Hasan in https://github.com/files-community/Files/issues/7554#issuecomment-1012234173_

**Comment by themisir** [comment]
I've tried disabling animations on windows settings, restarted the app and used for some time. My final thoughts is it seems like loading file list takes some time, when disabling animations this becomes even more noticeable so having animations currently seems like better option unless we could increase file list loading performance.

Btw just curious, why does loading file list takes some time. Afaik it should be fast to query directory entries on windows. So probably there's some other factors causing that delay. My guess is either UI updates slowly or probably the loading is slower due to resolving thumbs (aka: file icons).

**Comment by yaichenbaum** [comment]
There are several reasons why enumerating items take time, but the main reason is that on top of enumerating the items, the data is passed from the full trust process to the UWP process and that causes there to be some latency. The thumbnails and extended properties shouldn't affect the loading speed as those are lazy loaded.
These issues will hopefully be resolved when we eventually make the switch to WinUI 3 but we don't have a timeline on when that will happen.
