### ISSUE TITLE
make alt+right and alt+left accessible on trackpad using two finger swipe/gestures.

### ISSUE THREAD

**Issue by Prasanjit-4** [files-community/Files#7702]
### Solution/Idea

We can use gestures on trackpad to go forward or backward in browser similarly it would be a great relief to be able to do the same in files.

### Alternatives

I don't know what to write here there's already alt+right and alt+left but I personally end up using the trackpad gestures a lot. Might be good from a UX perspective.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.1.0.0 

### Windows Version

Windows 11

**Comment by PetoFeFe** [comment]
i have touchpad too, i wish this will be a feature. It is windows precision touchpad and I have set up gestures for navigation back/forward.

**Comment by Prasanjit-4** [comment]
Am I supposed to close this feature request or there are other plans? Kindly let me know.

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?

**Comment by yaichenbaum** [comment]
Yes

**Comment by yaichenbaum** [comment]
Merging with #100
