### ISSUE TITLE
Allow user to use windows richt-click menu insted of app right-click menu

### ISSUE THREAD

**Issue by C4uTi0N** [files-community/Files#7703]
### What's the Problem?

Personally i dont like default right click menu in the app, nor the default Windows 11 (so i restore the one from windows 10).
And needing to scroll or click an extra menu button to reveal all options in the menu isnt very time effecient imo.
Also not having sectioning in the righclick menu makes it look very messy and sometimes difficult to find what i'm looking for

In app:
![In App](https://user-images.githubusercontent.com/45887100/149657735-8a331745-129d-482e-a105-1af49aacaeca.png)

Windows Menu:
![Windows](https://user-images.githubusercontent.com/45887100/149657751-2ebb8da4-36c4-4545-9098-0c319eb7d6e7.png)

### Solution/Idea

Allow the user to pick between using the in app menu or the windows rightclick menu from the settings

Idea:
![Idea](https://user-images.githubusercontent.com/45887100/149657959-fcd4dd7a-a840-479a-a66d-e5bd9c57e546.png)

### Alternatives

I dont know about any alternatives

### Priorities

| Capability | Priority |
| This proposal will allow end users to work more comfortably with Files | Could |

### Files Version

Version: 2.1.0.0 OS Version: 10.0.22000.434

### Windows Version

Windows 11 21H2 22000.434

**Comment by yaichenbaum** [comment]
@C4uTi0N I believe this issue will be resolved when we add a compact option #1940.
