### ISSUE TITLE
Change ctrl + alt + p to something easier

### ISSUE THREAD

**Issue by Cazvind** [files-community/Files#7705]
### What's the Problem?

Hi I'm loving the program but I'm missing a key feature for me. When I'm moving through my sample library I would like to listen quickly to the audio. Right now I just move with the up and down keys and play by pressing CTRL + ALT + P, but that shortcut is just too hard. Thank you

![Screenshot](https://user-images.githubusercontent.com/97838698/149664459-cad66b3b-d63a-4a26-9f23-d44d9e8d9bff.png)

### Solution/Idea

I would be great if we could change that shortcut to "space bar" for example or having an autoplay function.

### Alternatives

I've tried QuickLook but for some reason doesn't play files that are inside of Google Drive, if they are in the desktop for example it works fine, although the audio glitches a little bit sometimes and you have to replay the sample.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by kbuno** [comment]
✋ I'll take the issue @yair100

**Comment by yaichenbaum** [comment]
@kristoferbuno what do you plan to change the shortcut to?

**Comment by kristoferbuno** [comment]
> @kristoferbuno what do you plan to change the shortcut to?

I took a look at the shortcuts list (https://files.community/docs/configuring/keyboard-shortcuts) - I'm thinking Ctrl+Space. Maneuverable with one hand, no surprise playback with just one key.

**Comment by kbuno** [comment]
@yair100 polite ping!

**Comment by yair100** [comment]
> @yair100 polite ping!

`ctrl` + `space` sounds good.

**Comment by LastDerivative** [comment]
Can I also get added on to this? Or can only one person work on it at a time?

**Comment by LastDerivative** [comment]
@yair100

**Comment by yaichenbaum** [comment]
@LastDerivative you can reach out TO @kristoferbuno to see if they can use some help.

**Comment by LastDerivative** [comment]
@kristoferbuno Hello! I sent you an email, or you can find on the discord as LastDerivative. Im in the Files server. Reach out to me when you get a chance!!

**Comment by yaichenbaum** [comment]
This issue should be resolved with `8893`.
