### ISSUE TITLE
add the function of agreeing to all requests

### ISSUE THREAD

**Issue by thientrile** [files-community/Files#7707]
### What's the Problem?

When I copy multiple files, many of which are the same as the folders I copy, I have to choose to deal with each one that bothers me. So hopefully the developer will add consent functionality to all requests soon.

### Solution/Idea

add option button Yes All or No All

### Alternatives

![image](https://user-images.githubusercontent.com/68942875/149668200-17b54ea6-0384-45d5-ad55-e40242361403.png)

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.1.0.0 OS Version: 10.0.22000.466

### Windows Version

Windows 11 21H2 22000.466

**Comment by Josh-65** [comment]
Sames as #5030

**Comment by yaichenbaum** [comment]
@thientrile This issue should be resolved in the preview version. https://files.community/download/preview
