### ISSUE TITLE
Removal of Custom Libraries Option

### ISSUE THREAD

**Issue by servebeer** [files-community/Files#7708]
### What's the Problem?

It would be great if there was an option to delete a library from the "main" screen where you can right-click on Libraries and create a new library. 

### Solution/Idea

It would be great if there was an option to delete a library from the "main" screen where you can right-click on Libraries and create a new library. 

### Alternatives

n/a

### Priorities

| Capability | Priority |
| Removal of Custom Libraries Option | Low |
| This proposal will allow end users to more easily delete custom libraries from Files.|

**Comment by APT256** [comment]
@yair100 Yes, I am referring to the sidebar.

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
