### ISSUE TITLE
Please add the function of background image

### ISSUE THREAD

**Issue by whtrys** [files-community/Files#7710]
### What's the Problem?

Please add the function of background image

### Solution/Idea

allow users use an image as a background

like this
![image](https://user-images.githubusercontent.com/69187424/149670606-8847829f-9b7d-4475-95f9-7c776152893c.png)

### Alternatives

windows built-in explorer

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
@whtrys you can already do this with a custom theme. I'll try to update to documentation to explain how to set an image for the background brush.

**Comment by whtrys** [comment]
Did you add it to the documentation? I cannot see it in the offical documentation.

**Comment by whtrys** [comment]
> @whtrys you can already do this with a custom theme. I'll try to update to documentation to explain how to set an image for the background brush.

Did you add it to the documentation? I cannot see it in the offical documentation.

**Comment by yaichenbaum** [comment]
https://files.community/docs/configuring/custom-themes
https://files.community/blog/posts/how-to-use-background-image
