### ISSUE TITLE
Filmstrip view

### ISSUE THREAD

**Issue by android272** [files-community/Files#7712]
### What's the Problem?

In a folder with many Photos/videos, I would like to preview these files in a larger layout then even the large icon layout provides.

### Solution/Idea

I don't remember what it was called but Windows XP's File Explorer used to have what I call a filmstrip view. Where all the files went along the bottom and the majority of the screen was a preview of the photo that was selected. What I liked most about the way Windows XP's File Explorer did it was that only folders that I decided to present this was had this layout. All other folders were in a regular layout.

https://www.techlicious.com/images/computers/windows-xp-filmstrip-view.jpg

### Alternatives

Allow for the preview pain to be expanded past 1/5 the screen size it allows now. Currently, the preview pain is Good enough for a quick view. But it could allow for preview to be much larger than it is today.

### Files Version

2.1.0.0

### Windows Version

Windows 10

**Comment by yaichenbaum** [comment]
@android272 are you fine with us merging this issue together with #6628?

**Comment by android272** [comment]
Yep that is a good solution to this problem.
