### ISSUE TITLE
Extra open context menu item with shortcuts

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#7718]
### Description

When right clicking on a shortcut there are two items that do the same thing "open" and "open file location"

### Expected behavior

There shouldnt be the open file location entry

### Files Version

2.1.1.0

### Windows Version

10.0.19043.1466

### Relevant Assets/Logs

*

**Comment by yaichenbaum** [comment]
The open option opens the actual shortcut, the open file location opens the parent directory.
