### ISSUE TITLE
High CPU usage when 'show folder size' is enabled

### ISSUE THREAD

**Issue by Darkspirit2017** [files-community/Files#7719]
### Description

Abnormally high CPU usage when 'show folder size' feature is enabled.

CPU:  Ryzen 9 5900x
RAM: DDR4 3800 32G
Storage: Samsung 980 Pro 2T

### Steps To Reproduce

1. enable 'show folder size' feature under Setting/Experiential
2. switch between 2-3 folders simultaneously

### Expected behavior

CPU usage goes up to 100%

### Files Version

Version: 2.1.0.0 OS Version: 10.0.22000.466

### Windows Version

Windows 11 Pro 21H2 22000.466

### Relevant Assets/Logs

![issue](https://user-images.githubusercontent.com/24643433/149677757-868b9d43-4b4c-49f7-abc4-d6a4decff54b.jpg)

**Comment by yaichenbaum** [comment]
@Darkspirit2017 this is due to the fact that calculating the size of all folders and sub items is very resource intensive. We added this as an optional feature flag so that users can decide if they want the tradeoff, but it should be used with the knowledge that it's resource intensive.
