### ISSUE TITLE
Home Indicator is Missing on Launch

### ISSUE THREAD

**Issue by Gryzle** [files-community/Files#7720]
### Description

The indicator in the sidebar is missing when Files is launched.

### Steps To Reproduce

1. Launch Files

### Expected behavior

The sidebar indicator should be visible and on Home when the app is launched.

### Files Version

Version: 2.1.1.0 OS Version: 10.0.22000.434

### Windows Version

Windows 11 22000.434

### Relevant Assets/Logs

Observed:
![Screenshot 2022-01-16 161152](https://user-images.githubusercontent.com/51198087/149678256-71819239-3e80-4237-9b46-95ddc7ffcf0f.png)

Expected:
![Screenshot 2022-01-16 161206](https://user-images.githubusercontent.com/51198087/149678271-8cc21394-3b3b-4242-9517-03ab944be1de.png)

**Comment by IgorKordiukiewicz** [comment]
It looks like it has been fixed already.
