### ISSUE TITLE
Some Folder Icons Occasionally Appear Broken

### ISSUE THREAD

**Issue by Gryzle** [files-community/Files#7721]
### Description

What seems randomly, some folder icons appear to have a reduced resolution and lack transparency. None of the folder icons effected were altered in any way.

### Steps To Reproduce

Steps to Reproduce:
Unknown

Current Fix:
1. Go to directory containing affected folder
2. Right click on empty space
3. Select "Refresh"

### Expected behavior

Folder icons should always appear normally.

### Files Version

Version: 2.1.1.0 OS Version: 10.0.22000.434

### Windows Version

Windows 11 22000.434

### Relevant Assets/Logs

Observed Behavior:
![Screenshot 2022-01-16 161747](https://user-images.githubusercontent.com/51198087/149678474-1175a615-577b-48a5-9300-ee45fba67e29.png)

Expected Behavior:
![Screenshot 2022-01-16 162010](https://user-images.githubusercontent.com/51198087/149678489-f4072b5c-fba7-4455-b1e1-4e6ad2fcd0ae.png)

**Comment by gave92** [comment]
Tracked in #6373
