### ISSUE TITLE
Your Files applicaton is not in the Microsoft Store 

### ISSUE THREAD

**Issue by NousB** [files-community/Files#7722]
I saw a description of your FILES application and wanted to try it.  When I clicked on the [ Get ]  button, a popup appears with the message - 'The thing you're looking for isn't here'  

 partial link without the last bit of gibberish "https://www.microsoft.com/en-us/p/files-file-manager-for-windows/ "

I also tried "Themes for Files" with the same result.

I was hoping to get a utility that would show the actual file directories with sizes for Windows 10 / 8.1 / 7 / XP to use for documentation and script files.  Currently I use the DIR command and pipe the results to a text file for a clear picture of what is where.

Since you are in the business, if you know of anything that can export list of directories and files more easily I would appreciate knowing.  The Windows 10 file manager misrepresents the directory structure on my hard drive.  I don't want to use my file listings as a source for moving or deleting files since that could screw up the file and drive links in File Manager.

This is the first time I have tackled anything beyond Windows 3.1 and DOS 6.1  and it is a nightmare to do anything Microsoft doesn't want you to.  I would use Linux but that brings up compatibility issues.  So I am staying with Windows and trying to bend it to my will.

Thanks, Guy Groner

**Comment by yaichenbaum** [comment]
@NousB what link are you clicking on? https://www.microsoft.com/store/apps/9NGHP3DX8HDX

**Comment by NousB** [comment]
Just clicked on the link provided and got the same message. 

I am slogged in to my Microsoft account - nousburg@earthllink.net

**Comment by NousB** [comment]
I am not often on any particular site so it may take me time to respond.  Thanks, Guy

**Comment by yaichenbaum** [comment]
Can you upload a screenshot?

**Comment by NousB** [comment]
image is below
![MS Response to Get Files app](https://user-images.githubusercontent.com/97853763/149679904-9e63fda7-052b-4bec-9273-6607fae1aeea.png)

**Comment by yaichenbaum** [comment]
@NousB are you able to find any other apps in the store?

**Comment by NousB** [comment]
[Screen captures from Microsoft Store 16JAN 2022.docx](https://github.com/files-community/Files/files/7878053/Screen.captures.from.Microsoft.Store.16JAN.2022.docx)

**Comment by yaichenbaum** [comment]
@NousB it seems like a firewall or something else on your device is preventing store pages from loading, I recommend reporting this issue on Feedback Hub.

**Comment by NousB** [comment]
Thanks for your help.  I am looking forward to trying your Files.  Guy

**Comment by gave92** [comment]
You can also install the side loaded version without the Store: https://filescommunity.blob.core.windows.net/files/preview/Files.Package_2.1.2.0_Test/Files.Package_2.1.2.0_x86_x64_arm64.msixbundle

**Comment by NousB** [comment]
Thank you,
 
I have been thinking that Microsoft wants to control the Windows ecology the same way Apple does their's. I may let them try on one of my lappies to see what happens - once I determine the sacrificial goat.
 
I had  to get an iPhone last year and it works OK. The iPhone on the Verizon network is solid, though not very malleable. 
 
Their seems to be a paucity of manuals on iPhones, et.al.  so I have been piecing together guides and literature on both Win 10/11 and the iPhone.  Trying to find where a file actually is stored in nigh impossible.  That is why I was interested in trying the FILES application / utility.
 
I have been on micros since the Age of DOS (3.1), supported and audited them.  I don't know that all the complexity in each application is necessary.  It should be possible to co-op the UNIX model and have many limited purpose apps that can be assembled on an as needed basis.
 
Modules could be assembled with the help of an IDE.  Checkpoints in the data flow could be 'installed' between modules, kind of in the way IBM mainframes have 'exits' available in system software to do monitoring.  The sophistication of an application would be governed by the IDE and the user / developers knowledge. Analysis and maintenance of an application would be performed using the IDE which could insert comments in the code, link to reference materials and a library of modules..
 
It would not be an object oriented language, again something akin to the original aim of UNIX developers.
 
Anyway, that is what I would like.  Am I missing something that is already on GITHUB?  It doesn't seem all that novel once an individual has been using DOS, Windows, Unix servers and IBM mainframes.  Very different beasts, but if you can move data between them, magic happens.
 
Anyway, thank you for getting back so me on FILES.  I really do appreciate it.  Guy Groner
 
 
-----Original Message-----
