### ISSUE TITLE
Sidebar automatically closes after exiting minimal mode when maximizing the window

### ISSUE THREAD

**Issue by oleklukasiewicz** [files-community/Files#7723]
### Description

Sidebar automatically closes when is opened after exiting minimal mode when maximizing the window.

### Steps To Reproduce

1. Set the window width to very small (so that the sidebar enters minimal mode)
2. Open it
3. Maximize the window

The sidebar should automatically enter compact mode (close) even though it was open before entering the minimal mode.

### Expected behavior

Sidebar should remember its state from before entering minimal mode (be open if the user left it that way) 

### Files Version

Version: 2.1.0.0 OS Version: 10.0.22000.376

### Windows Version

Windows 11 21H2 Version: 22000.376

### Relevant Assets/Logs

Before entering minimal mode:
![image](https://user-images.githubusercontent.com/69370471/149679733-183ea097-1583-4431-8844-e642d33d8384.png)
In minimal mode:
![image](https://user-images.githubusercontent.com/69370471/149679743-e599bcb9-665c-454c-ba18-046ca5cb3965.png)
After maximizing:
![image](https://user-images.githubusercontent.com/69370471/149679759-6b009bef-1276-49a5-885f-f8d74a892019.png)

**Comment by yaichenbaum** [comment]
@oleklukasiewicz This issue should be resolved in the preview version. https://files.community/download/preview
