### ISSUE TITLE
After update (1/17/22), Drives no longer appear on the Home page

### ISSUE THREAD

**Issue by rckmnr** [files-community/Files#7732]
### Description

Files updated about an hour ago. As soon as it did, the Drives widgets no longer appear on the home page. It was working a few hours ago. Also icons no longer show default program icons.

### Expected behavior

For Drives to show up on the home page, and correct icons.

### Files Version

Version: 2.1.2.0 OS Version: 10.0.19043.1466

### Windows Version

Windows 10.0.19043 Build 19043

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7879219/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7879220/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
@rckmnr can you check if you collapsed the widget?

**Comment by imtiazAyon** [comment]
Same thing happened to me. The widget wasn't collapsed. Also The files icon in the taskbar was missing. All the themes in the setting was missing. They worked after I restarted the PC.

**Comment by rckmnr** [comment]
> @rckmnr can you check if you collapsed the widget?

I set the widget every way possible. However, I did a restart last night, and saw no change. This morning, everything was working fine. Go figure!

**Comment by rckmnr** [comment]
> Same thing happened to me. The widget wasn't collapsed. Also The files icon in the taskbar was missing. All the themes in the setting was missing. They worked after I restarted the PC.

I restarted last night, with no improvement. However, this morning everything is working fine.

**Comment by Korkman** [comment]
I've had the same effect when BitLocker-Driver decided to do some kind of "cleanup" on my drives (that's what event log says, event ID 24660). After that, "FilterManager" complained about some volumes not being accessible until after the next restart. Explorer.exe subsequently hung as well after a few clicks. Not sure what triggered the cleanup. I activated the secure folder in OneDrive just before.

Anyways, I think this is not actually a bug in Files but the result of instability in Windows (which may occur at any time when receiving updates in background).
