### ISSUE TITLE
Folder/file sort grouping outside of sorting by name

### ISSUE THREAD

**Issue by Satsaa** [files-community/Files#7733]
### What's the Problem?

Show folders first/last only when sorting by name. When sorting by Date/Size, it feels a bit funny to have folders not mix with files.

### Solution/Idea

Add a new setting for this behaviour. (Like "List and sort directiories alongside files" but when not sorting by name)

### Alternatives

Make this default behaviour. (either when "List and sort directiories alongside files" is on or off)
-or-
Be able to toggle folder grouping for each of the sorting setting, e.g. in the right click menu.
-or-
I noticed this actually when browsing downloads, so maybe just let the folder grouping loose when there.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to customize if folders are grouped when not sorting by name | Must |
| This proposal will allow end users to customize when folders are grouped depending on current sorting | Could |
| This proposal will allow end users to customize when folders are grouped when in download folder | Could |

### Files Version

2.1.2.0

### Windows Version

Windows 11 21H2 22000.434

**Comment by xgitc** [comment]
I also have the same demand, hope can change "folders first/last" in any sort mode. THANKS.

**Comment by Josh-65** [comment]
This can be fixed by enabling "List and sort directory along side files" in the sorting menu
