### ISSUE TITLE
File Sorting Preference

### ISSUE THREAD

**Issue by ressing1** [files-community/Files#7734]
### What's the Problem?

Thank you for writing this application.  I am really enjoying using it, so far.  Would it be possible to have a setting to select whether files or folder have sorting precedence?

### Solution/Idea

I would like to be able to change whether folder have sorting priority.  For example, if I am sorting by the Date Modified coumn, I would like to have files on top and folders below. 

### Alternatives

None

### Priorities

Choose sorting Precedence: Should

### Files Version

2.1.2.0

### Windows Version

Windows 11 Pro 22000.434

### Comments

Thanks once again for this excellent program.  It is so nice to have a tabbed file manager.

**Comment by Josh-65** [comment]
You can change the sorting order with ascending and descending options in the sorting button. you can have file and folder mixed rather than folders first in Setings > Preferences > Files and folders > List folders along side files.

**Comment by anhell** [comment]
I'd like to see that feature too, files first and folders last when sorting by date modified, no matter if ascending or descending.

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
@Josh-65 looks like the option to "List folders along side files" does the trick. Does this solve the feature request?

**Comment by yaichenbaum** [comment]
I have a feeling this is a niche scenario but let's leave this open for discussion.
