### ISSUE TITLE
Sort by descending by default

### ISSUE THREAD

**Issue by Satsaa** [files-community/Files#7735]
### What's the Problem?

Sorting by oldest first feels like a rarer use case when sorting by date created/modified.
Sorting by largest first when sorting by size seems better as a default as well.
Oh and yes this is how my File Explorer behaves.

### Solution/Idea

When sorting by date modified/created default to newest first.
When sorting by size default to biggest first.

### Alternatives

Remember last used sorting direction per sorting category.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will require developers to set the default sorting directions | Must |
| This proposal will allow the sorting direction to be remembered (alternative) | Must |

### Files Version

2.1.2.0

### Windows Version

Windows 11 21H2 22000.434

### Comments

This will save me 2 clicks.

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
Seems like a bug as file name is descending by default.

**Comment by yaichenbaum** [comment]
Is this still an issue in the latest preview build? https://files.community/download/preview
