### ISSUE TITLE
Hidden Files on network drives have strange behavior

### ISSUE THREAD

**Issue by C0D3-M4513R** [files-community/Files#7737]
### Description

Hiding files & Hidden files don't work on network drives.

### Steps To Reproduce

1. Go to a network drive.
2. Create a File
3. Go into it's properties in Files.
4. Mark it as Hidden
5. Refresh
6. Watch it unhide itself

1. Go to the network drive in explorer
2. Notice how the File really isn't hidden
3. Go into the File's Properies
4. Mark it as Hidden
5. Refresh Files
6. Watch the File disappear

### Expected behavior

I would expect network drives to behave just as local drives.
I would expect files to be able to mark a file as hidden on a network drive.
I would expect files to be able to see hidden files, if I chose to.

### Files Version

2.1.2.0

### Windows Version

Windows 10 Pro 21H119043.1466

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7879500/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7879501/debug_fulltrust.log)
Related #6774

**Comment by gave92** [comment]
Same cause as #2436

**Comment by C0D3-M4513R** [comment]
Read title incorrectly. Is it by any chance possible, that the winget command on the [website](https://files.community/) outdated is?
When I copy & paste it, it just gives me the following:

> winget install -e Files-Community.Files
> No package found matching input criteria.

**Comment by gave92** [comment]
It is, you may try "install -e 9NGHP3DX8HDX" instead.

**Comment by gave92** [comment]
#2436 is correct. Missing hidden and shortcut files on network are due to the same UWP platform limitation and will be solved together.
