### ISSUE TITLE
idea  open in explorer 还是打开的系统默认文件管理器

### ISSUE THREAD

**Issue by MambaOutZY** [files-community/Files#7739]
### Description

1.实验性设置了系统默认，idea浏览文件还是会默认打开文件管理器
2.打开主页后无法右键查看属性，以及没有快捷查看设备管理器等。

### Expected behavior

实验性设置了系统默认，idea浏览文件还是会默认打开文件管理器

### Files Version

2.1.2.0

### Windows Version

windows11 22000.434

### Relevant Assets/Logs

1.实验性设置了系统默认，idea浏览文件还是会默认打开文件管理器
2.打开主页后无法右键查看属性，以及没有快捷查看设备管理器等。

**Comment by Josh-65** [comment]
This is not a readable issue. You should re write this and add the logs files. You can get them in files settings > about > open log folder.
