### ISSUE TITLE
Indicator for selected folders appears on folder when a file is dropped onto it

### ISSUE THREAD

**Issue by Mahas1** [files-community/Files#7740]
### Description

The blue indicator, which indicates that a file/folder is selected, appears when a file is dragged and the mouse is hovered over the folder
![image](https://user-images.githubusercontent.com/82939599/149726880-503a7d40-9654-4df6-9288-0f164efc998c.png)

This doesn't disappear even after reloading, and the only way to turn the indicator off seems to be to click on the folder, and then click somewhere else. 

### Steps To Reproduce

1. Select a file
2. Drag it over a folder (do not drop it)
3. Highlight appears
4. Repeat Step 2 while not releasing the mouse

### Expected behavior

The expected behaviour, in my opinion, would be that the indicator vanishes when I move the mouse away from the folder.

### Files Version

Version: 2.1.2.0 OS Version: 10.0.22000.434

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎17-‎Oct-‎21 OS build	22000.434 Experience	Windows Feature Experience Pack 1000.22000.434.0

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7879897/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7879900/debug.log)

**Comment by gave92** [comment]
Tracked in #6768
