### ISSUE TITLE
Fixed Columns

### ISSUE THREAD

**Issue by infuriatedcodex** [files-community/Files#7741]
### What's the Problem?

Seem to remember an older version that supported users ability to move & resize the detail columns (Date, Type, Size etc.).

Current layout has fixed columns and when using cloud storage (OneDrive) it now places the "Status" column on the far right. This becomes problematic when you have a preferred Window size for the main Files app.

Example:
![20220117_075104 - ApplicationFrameHost5](https://user-images.githubusercontent.com/40537324/149730598-b45d9d79-fcb5-4591-8e35-d4ee4d334fce.jpg)

### Solution/Idea

Please allow user to move these columns around to their preferred locations (like the native explorer).
Allowing user to resize the column would be fab too !

### Alternatives

N/A

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.2.0

### Windows Version

Windows 11 22000.434

**Comment by gave92** [comment]
You should already be able able resize columns by dragging the (invisible) divider between them

**Comment by gave92** [comment]
For reordering, tracked in #4643

**Comment by infuriatedcodex** [comment]
> You should already be able able resize columns by dragging the (invisible) divider between them

Indeed you are correct sir!
Noticed that the OneDrive status column is the only one that cannot be resized (currently).
