### ISSUE TITLE
icon of adobe indesign file

### ISSUE THREAD

**Issue by seec1111** [files-community/Files#7742]
### Description

Icon of indesign file type cannot be shown.

### Expected behavior

wish the adobe indesign file type icon can show correctly, thanks!

### Files Version

2.1.2.0

### Windows Version

win10 21H1 19043.1466

### Relevant Assets/Logs

Right hand side is the preview of Files, left hand side is the indesign icon in win10 file explorer.
![indesign_icon](https://user-images.githubusercontent.com/93403256/149733611-17a6032e-cc59-4e6b-8c1f-b85699fccfcd.png)

**Comment by yaichenbaum** [comment]
Merging with #2582
