### ISSUE TITLE
Library not recognising path

### ISSUE THREAD

**Issue by AndreBlackScribe** [files-community/Files#7745]
### Description

I have enabled "Show library on the sidebar"

When I am trying to access any Folder from that menu Item I get the following error:

Error: 
> "Did you delete delete this folder?"
> "The folder you are attempting to access may have been moved or deleted."

![error](https://user-images.githubusercontent.com/5656905/149759292-2c0f1fc1-9efb-4f89-89db-1480804685e9.png)

After the error the path sowed is: 
C:\Users\User\AppData\Roaming\Microsoft\Windows\Libraries\Music.library-ms

I have Tried:
- PC restart
- Remapping the folder

### Steps To Reproduce

1. Show library on the sidebar
2. Click any item under the sidebar Library 

### Expected behavior

Show the selected item with no error under the path
C:\Users\User\Music
or
C:\Users\User\Documents
or
C:\Users\User\Picture
or
C:\Users\User\Videos

### Files Version

2.1.2.0

### Windows Version

Windows 10 Pro Version 21H1 Feature Pack: 120.2212.3920.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7881406/debug.log)

**Comment by gave92** [comment]
From the screenshot it looks like the Documents library works, correct? At least, it shows a message but in fact it properly shows the library contents.

**Comment by AndreBlackScribe** [comment]
yes it show the folder under: 
C:\Users\User\AppData\Roaming\Microsoft\Windows\Libraries\Music.library-ms

**Comment by yaichenbaum** [comment]
@gave92 can I add this to the backlog?

**Comment by gave92** [comment]
Should be the same as #6781
