### ISSUE TITLE
too much lag while transferring file 

### ISSUE THREAD

**Issue by ajay-mishra7** [files-community/Files#7746]
### Description

I'm facing too much of lag while transferring file/data form one device to other. It takes too much time to share files form devices.

### Expected behavior

I think file sharing time should less or it should share my data quickly

### Files Version

Version: 2.1.2.0 OS Version: 10.0.22000.466

### Windows Version

Windows 11 21H2 22000.466

### Relevant Assets/Logs

![bug](https://user-images.githubusercontent.com/70057599/149778253-4dcfc935-2672-44cb-8119-1d63777a69b4.jpg)

**Comment by JoshuaDup** [comment]
am experiencing the same thing, but also while having more than two tabs open and attempting to edit text files, bat files, etc.

**Comment by yaichenbaum** [comment]
@ajay-mishra7 is this still an issue in the preview version? https://files.community/download/preview
