### ISSUE TITLE
Files crashes if you try to drag multiple images

### ISSUE THREAD

**Issue by imtiazAyon** [files-community/Files#7747]
### Description

If you drag multiple images, files crashes when you release them. Images size has to be large and you have to set group by to something other than None.

### Steps To Reproduce

1. Set Group by to something other than None
2. Set Layout to Large Icon
3. Select Multiple Image files and drag them
4. Release the dragged images

### Expected behavior

The software will hang and crash.

### Files Version

Version: 2.1.2.0 OS Version: 10.0.19042.1466

### Windows Version

Windows 10 Version 20H2 OS build 19042.1466 Windows Feature Experience Pack 120.2212.3920.0

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7882155/debug_fulltrust.log)

**Comment by gave92** [comment]
Where do you release the dragged files? In the same folder they are in? 
Could you upload the other debug file as well (debug.log)? Thanks!

**Comment by imtiazAyon** [comment]
The same folder yes
[debug.log](https://github.com/files-community/Files/files/7882360/debug.log)
.

**Comment by yaichenbaum** [comment]
@imtiazAyon is this still an issue in the preview version? https://files.community/download/preview

**Comment by imtiazAyon** [comment]
> @imtiazAyon is this still an issue in the preview version? https://files.community/download/preview

No. It's no longer an issue.
