### ISSUE TITLE
Bug: Opening folder from external source does not honor dual pane settings

### ISSUE THREAD

**Issue by dansauve** [files-community/Files#7748]
### Description

When opening a folder, say from Explore (right-click on a folder on desktop and "Open") or other source (e.g. Download menu in Edge browser) then folder is opened in a new tab but in single-pane only mode.

Preconditions:
- Files is set as the default file browser
- Multitasking > Enable dual pane setting "On"
- Multitasking > Always open tabs in dual pane mode setting "On"

### Steps To Reproduce

See description

### Expected behavior

Folder should open in a new tab in DUAL PANE mode. 

Folder should display in left tab.

"Home" should display in right tab.

### Files Version

2.1.2

### Windows Version

22000.466

### Relevant Assets/Logs

N/A

**Comment by yaira2** [comment]
Thank you for reporting this issue, I can confirm it's still an issue in v2.5.20.
