### ISSUE TITLE
Can't open multiple images at once since the new update. 

### ISSUE THREAD

**Issue by Noisemagician** [files-community/Files#7750]
### Description

Hi,

Because of the thumbnail loading problem, I used to open all the images in (jpg, jpeg, png, psd, psb,)at once closed Files and reopen the map where the images were. The thumbnails do show after doing this. I made a bug report, reporting this very issue. I was informed that this is a know-issue. 
I expect that solving this problem will take a long time so using the method that I found is a good solution until the problem with thumbnails not loading is solved.
Unfortunately since the update today I can only open 1 image at a time, files won't allow me to open all the images selected. 

Thank you,

Have a nice day

### Expected behavior

Reenable opening multiple selected images, it worked yesterday when I updated it today, it stopped working, now I can only open 1 image at a time.

### Files Version

Version: 2.1.2.0 OS Version: 10.0.19043.1466

### Windows Version

Edition	Windows 10 Home Version	21H1 Installed on	‎16/‎09/‎2021 OS build	19043.1466 Experience	Windows Feature Experience Pack 120.2212.3920.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7882904/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7882905/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
@gave92

**Comment by Noisemagician** [comment]
> Related to #7557? @gave92

It could be, I don't know what using FTP means. But I have issues with opening multiple images. I have no music on my PC so I can't test it with music files.

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?
