### ISSUE TITLE
Navigating through images in same folder

### ISSUE THREAD

**Issue by RwbyChan** [files-community/Files#7751]
### What's the Problem?

When I try to open an image within Files, it the default Windows images app doesn't let me navigate through all the images in the folder (unlike with the default File Explorer app)

### Solution/Idea

I'd be nice if when I open an image through the Files app that the Images app can navigate through all the images in the folder just like with the default File Explorer app.

### Alternatives

I use this option a lot, so this is kinda making me go back to the default File Explorer. Of course I can just look at the previews, but it's way easier and better for me to go through them in a full view instead of a small preview

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow users to navigate through all the images in a folder without having to open them one by one | Must |

### Files Version

2.1.2.0

### Windows Version

Windows 11 Pro 21H2 22000.434

**Comment by yaichenbaum** [comment]
@RwbyChan is this still an issue in the preview version? https://files.community/download/preview

**Comment by RwbyChan** [comment]
> @RwbyChan is this still an issue in the preview version? https://files.community/download/preview

Yes, this issue is still there. I have checked and if I open an image in a folder with not a lot of files (or images) it works but it seems that if there are too many, it doesnt work

**Comment by yaichenbaum** [comment]
At what point (how many items) does it stop working?

**Comment by RwbyChan** [comment]
I'm not sure either, I do have almost 6000 items in the folder where it doesnt work, when I made a folder and duplicated the same file over 1000 times it still worked but I was also having other issues while doing so

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?
