### ISSUE TITLE
Keyboard Shortcut - Alt-D

### ISSUE THREAD

**Issue by MervinHernandez** [files-community/Files#7752]
### What's the Problem?

Not a problem - just a suggestion. 

### Solution/Idea

Add support for traditional Windows Explorer keyboard shortcut `Alt-D` to get to the address bar.

### Alternatives

I'm pursuing temporary alternative via AHK to get to the address bar by way of `Ctrl-F` or tabbing a few times.

### Files Version

Version: 2.1.2.0 OS Version: 10.0.22000.434

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎2021-‎12-‎19 OS build	22000.434 Experience	Windows Feature Experience Pack 1000.22000.434.0

### Comments

Thanks for a great project!

**Comment by yaichenbaum** [comment]
`Alt` + `D` is already implemented, is it not working on your device?

**Comment by gave92** [comment]
Also "Ctrl+L" but both don't work on the homepage

**Comment by yaichenbaum** [comment]
Merging with #6800

**Comment by MikeFarrington** [comment]
> `Alt` + `D` is already implemented, is it not working on your device?

It works very inconsistently for me.  It seems like certain things must have focus for it to work.  It certainly does not work after a fresh launch without first using the mouse to click on something else first.
