### ISSUE TITLE
Add "Run script" button to toolbar when ps1 files are selected

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#7755]
### What's the Problem?

Double clicking a ps1 file will open the script in the default editor, to run the script, you need to right click and find the "Run with PowerShell" option in the context menu.

### Solution/Idea

Adding a "Run script" button to the toolbar will make running PowerShell scripts easier and improve the users workflow.

### Alternatives

NA

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will add a run script button to the toolbar when ps1 files are selected | Must |

**Comment by puppetsw** [comment]
Can I claim this one?

**Comment by yaichenbaum** [comment]
> Can I claim this one?

Sure! Thank you for your work on the extract button.
