### ISSUE TITLE
Very High CPU Usage Windows 10

### ISSUE THREAD

**Issue by Lucien950** [files-community/Files#7756]
### Description

The CPU Usage of this application is far higher than the standard file explorer.

### Steps To Reproduce

Use the app

### Expected behavior

Less CPU usage

### Files Version

Version: 2.1.2.0 OS Version: 10.0.19043.1466

### Windows Version

Windows 10 Home 21H1 19043.1466

### Relevant Assets/Logs

ni=/a

**Comment by yaichenbaum** [comment]
Merging with #4180 and #2065
