### ISSUE TITLE
preview pane

### ISSUE THREAD

**Issue by boyy21** [files-community/Files#7757]
### What's the Problem?

The preview pane only shows the file logo, on the normal windows 10 file explorer you can read Word and Excel documents without opening them.

Windows 10 File Explorer: https://imgur.com/gallery/y5OPY4t
Files: https://imgur.com/gallery/pct9Fhp

would be nice if this feature would be added.
Thank you

### Solution/Idea

i dont know much about how it works i just love Files and i just saw that this feature is not available.

### Alternatives

Ill just live with it if it doesnt work :) Files is too good to abonden just for this feature

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1

### Windows Version

Windows 10 Pro 20H2

**Comment by gave92** [comment]
Tracked in #4041
