### ISSUE TITLE
Add support for application start-up to detect if windows exists and open a new tab in the existing window

### ISSUE THREAD

**Issue by barkermn01** [files-community/Files#7758]
### What's the Problem?

I would like an option so that when the Files Application is already open, and I open another copy from my taskbar (Shift+Click, Middle Mouse Button click) I can set it to open in the existing window, and not always open a new window.

This follows on from a conversation on https://github.com/files-community/Files/issues/7637 

### Solution/Idea

I would like a setting adding that allows me to select whether Shift-clicking or Middle mouse button clicking the task bar (AKA I open a new Copy of the Application) it opens a new tab in an existing window if one is present already.

### Alternatives

N/A 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Allow end-users to toggle whether they would like new copies of the application to open a new window or want it in the existing window as a new tab | Should |
| When option is enabled and a new tab is opened focus the new tab and window to bring it to the foreground| Should |

### Files Version

2.1.0.0

### Windows Version

Windows 11 Pro 21H2 22000.376

### Comments

 I have a multi-screen setup and the only reason I pin stuff to my taskbar is I use it often across multiple screens and middle mouse click, as a developer I often have lots of windows open across my screens, with normal windows explorer, the Shift+Click or Middle mouse button click on the taskbar icon opens a new instance of Explorer, with Files having tabs that it makes the opening a new window redundant everything should be in the one window.

**Comment by Josh-65** [comment]
Merging with #9709
