### ISSUE TITLE
When setting the column width, the width changes less than the mouse pointer moves

### ISSUE THREAD

**Issue by TheJohny** [files-community/Files#7759]
### Description

the movement is not synchronous

### Steps To Reproduce

1. start adjusting with any of the columns

### Expected behavior

The column with should be in synch with the mouse pointer

### Files Version

Version 2.1.2.0

### Windows Version

Windows 11 Pro 21H2 22000.434

### Relevant Assets/Logs

https://user-images.githubusercontent.com/5933893/149832524-959b1d1c-bf1f-4392-93b2-7c55d5fcd0dc.mp4

**Comment by gave92** [comment]
Tracked in #5371
