### ISSUE TITLE
Shell extension not work

### ISSUE THREAD

**Issue by kaitoconan** [files-community/Files#7760]
### Description

The right click menu for both open with and other program options worked for a while and not anymore. Not even reinstalling the app fixed the problem. 

### Expected behavior

You could use the open with from the app

### Files Version

Versión: 2.1.2.0 OS Version: 10.0.19043.1466

### Windows Version

Windows 10 21H1 19043.1466

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7884687/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7884688/debug_fulltrust.log)

**Comment by gave92** [comment]
Thanks for the report. Could you delete the two log files and upload the new ones after opening the app and opening the context-menu? Thanks!

**Comment by kaitoconan** [comment]
Ok
[debug_fulltrust.log](https://github.com/files-community/Files/files/7884684/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7884685/debug.log)

**Comment by gave92** [comment]
@kaitoconan mind trying opening the context menu after minimizing and restoring Files window?

**Comment by kaitoconan** [comment]
It was resolved by trying several times and in the end the open menu with system default was opened and I selected what I wanted to do and it was resolved
