### ISSUE TITLE
Option to disable smooth scrolling

### ISSUE THREAD

**Issue by capSAR273** [files-community/Files#7764]
### What's the Problem?

Smooth scrolling is pretty to look at, but an option to disable this and scroll a fixed number of lines would be a useful feature. This is the behavior of stock File Explorer and its something I find nice to have.

### Solution/Idea

Add a toggle under the Files and Folders subsection of Preferences to enable/disable smooth scrolling.

### Alternatives

I looked around the settings of Files to see if the option already existed, but did not see one.

### Files Version

2.1.2.0

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎12/‎14/‎2021 OS build	22000.434 Experience	Windows Feature Experience Pack 1000.22000.434.0

### Comments

I really appreciate this project, so thank you to everyone contributing!

**Comment by tiomanisland** [comment]
Can we expect this to be fixed and when? Thank you.

**Comment by b-** [comment]
I think that this and/or the trackpad "elastic" scrolling may be related to this: https://github.com/files-community/Files/issues/9363

**Comment by still-dreaming-1** [comment]
Ugh, "smooth scrolling" is just a cute term for laggy scrolling. Should be disabled by default. Having it only on and no option to turn it off is way, way worse than just never having this feature to begin with.

**Comment by tiomanisland** [comment]
Really dumb thing to use smooth scrolling. Such a nice app destroyed easily. I switched to Free Commander XE - works well but a bit slow. Any fast alternative?
