### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by lovexxx** [files-community/Files#7765]
### Description

setting - preferences - files and folders - "list and sort directories alongside files" has been translated into "列出和排序文件旁的目录”.

### Expected behavior

should be translated into “文件夹与文件一同分类排序”

### Files Version

Version: 2.1.2.0 OS Version: 10.0.18363.1500

### Windows Version

Windows 10, version 1909 (OS Build 18363.1500)

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/28099434/149856291-bcfedc55-241d-423a-9ac4-d48952cd5473.png)

**Comment by yaichenbaum** [comment]
@lovexxx would you like to work on a fix?

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7831
