### ISSUE TITLE
the dark pixel theme is too dark

### ISSUE THREAD

**Issue by azlan-syed** [files-community/Files#7768]
### What's the Problem?

it is a theme problem there is a theme called dark pixel it is  very dark in color and it is hard to see some icons 

### Solution/Idea

we should try making another kind of dark theme that is not clearly dark with a little bit of grey color at the sides

### Alternatives

as mentioned in the solution we should make (remake) the theme or we can make a function that when the user switches to any dark theme then the app theme is switched to dark too

### Files Version

2.1

### Windows Version

windows 10 20h2 version

### Comments

![Screenshot 2022-01-18 102019](https://user-images.githubusercontent.com/92157088/149872915-2d487745-331c-4249-a693-0b4a13bd325b.png)
 
here is the black pixel theme looks

**Comment by yaichenbaum** [comment]
@azlan-syed this theme is intended to be used with the dark mode option.

**Comment by azlan-syed** [comment]
Ok
