### ISSUE TITLE
Add set as background button to toolbar when image files are selected

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#7769]
### Solution/Idea

Adding a toolbar button will increase ease of use when setting an image as the desktop background.

### Alternatives

NA

**Comment by rr-da-cat** [comment]
Yea plz do it

**Comment by puppetsw** [comment]
@yair100 Is this another one I can take on?

**Comment by generalguy41** [comment]
Would it be possible to make it a dropdown with the option to Set as Lockscreen as well? (Or alternatively add that as a button too).

**Comment by yaichenbaum** [comment]
> Would it be possible to make it a dropdown with the option to Set as Lockscreen as well? (Or alternatively add that as a button too).

At the moment, that's not part of the design spec.

**Comment by generalguy41** [comment]
> > Would it be possible to make it a dropdown with the option to Set as Lockscreen as well? (Or alternatively add that as a button too).
> 
> At the moment, that's not part of the design spec.

Right, but... could it be? Should I raise a separate feature request? Figured it'd be better to ask now before this gets merged in.

**Comment by yaichenbaum** [comment]
@generalguy41 can you open a separate feature request?

**Comment by esibruti** [comment]
@yair100 Can I open the feature request myself?

**Comment by esibruti** [comment]
@yair100 We can close this issue.
