### ISSUE TITLE
Random images appearing when opening folders with lots of images

### ISSUE THREAD

**Issue by TripSea6023** [files-community/Files#7770]
### Description

There are random images appearing when opening folders with lots of images, and any folder after that. For example if I open a folder with a cake's picture, and I open another folder, all the images' thumbnails of that folder become cakes.

### Expected behavior

Normally it should show the thumbnails of the actual images, but still show thumbnails of the previous folder's images.

### Files Version

Version: 2.1.2.0 OS Version: 10.0.22000.434

### Windows Version

Windows 11 21H2 22000.434

### Relevant Assets/Logs

I really don't think there is a log for this kind of problem.

**Comment by d2dyno1** [comment]
This issue should be resolved with #7881 @TripSea6023
