### ISSUE TITLE
Files crashed after shift+delete.

### ISSUE THREAD

**Issue by SU-Ki-MA** [files-community/Files#7771]
### Description

I recently started learning vim, and when I created few python files with it, It created some swap files and un~ files and PY~ files.
I shift+deleted all those files, it was around 10 files or more.
a popup appeared to make sure that I wanted to permanently delete it and I agreed.
then Files crashed. I opened it again, and the files were deleted.

so it was just a crash.

### Steps To Reproduce

I went to my powershell terminal(Windows Terminal) went to the location where I code.
I opened explorer using that terminal in that location(had some OhMyPosh theme going on... used link form that to ctrl+click to open explorer).
selected all the .swp .UN~ .PY~ files and shift+deleted
accepted the popup(I had my terminal open in that location, when doing all this, and had browser and discord open as well.)

### Expected behavior

The files which I tried to delete be permanently deleted, and files to stay open in that location.

### Files Version

Version: 2.1.2.0 OS Version: 10.0.22000.434

### Windows Version

Edition	Windows 11 Home Single Language Version	21H2 Installed on	‎19-‎12-‎2021 OS build	22000.434 Experience	Windows Feature Experience Pack 1000.22000.434.0

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/60312363/149889564-9f8c95e5-cdbf-4a2d-946c-a509220e79c2.png)
![image](https://user-images.githubusercontent.com/60312363/149889592-fc4def39-1f4c-4e06-921b-c7323c771fca.png)
![image](https://user-images.githubusercontent.com/60312363/149889880-1b5d778b-3089-4b93-835a-fe88a6a9a050.png)

**Comment by Josh-65** [comment]
You will need to upload the logs files. You can get them in files settings > about > open log folder.

**Comment by SU-Ki-MA** [comment]
[debug.log](https://github.com/files-community/Files/files/7889594/debug.log)
do you need debug_fulltrust.log as well?

**Comment by Josh-65** [comment]
best to do so

**Comment by SU-Ki-MA** [comment]
[debug_fulltrust.log](https://github.com/files-community/Files/files/7890303/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7890304/debug.log)
done

**Comment by azlan-syed** [comment]
this bug is fixed now reinstall the software from store and you are good to go

**Comment by SU-Ki-MA** [comment]
wow, that was fast!... amazing ill reinstall.
Thanks!!
