### ISSUE TITLE
No refresh on mapped network drive

### ISSUE THREAD

**Issue by ytse77** [files-community/Files#7772]
### Description

Folders on mapped network drive aren't being refreshed. I have to manually refresh them.

### Steps To Reproduce

1. Go into a folder on a mapped network drive.
2. Paste a file and it wont show unless you press F5.
3. Rename a file and it wont show the new name unless you press F5.
4. Save a file into that folder from an app and it wont show unless you press F5.

### Expected behavior

Folder feedback should update automatically. 

### Files Version

Version: 2.1.2.0 OS Version: 10.0.19042.1415

### Windows Version

Windows 10 Version	10.0.19042 Build 19042

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7887022/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7887024/debug_fulltrust.log)

**Comment by gave92** [comment]
Tracked in #5869
