### ISSUE TITLE
Change application font

### ISSUE THREAD

**Issue by TripSea6023** [files-community/Files#7773]
### What's the Problem?

Well, right now, Files uses Windows 10's Segoe UI. It's fine for people using Windows 10, but for those on Windows 11, it would be nice if we could atleast get the Segoe UI Variable Display font.

### Solution/Idea

My suggestion is to add the **Segoe UI Variable Display** font.

### Alternatives

Or you can even add the option to change the application font to a font of our choice.

I hope this gets implemented.

### Files Version

Version: 2.1.2.0 OS Version: 10.0.22000.434

### Windows Version

Windows 11 21H2 22000.434

### Comments

I hope this gets added. It will definitely make Files look neater.

**Comment by yaichenbaum** [comment]
@TripSea6023 this issue should be resolved with #7786
