### ISSUE TITLE
Con not show Dialog Question Replace And Copy File

### ISSUE THREAD

**Issue by Mahdihp** [files-community/Files#7777]
### Description

Con not show Dialog Question Replace And Copy File

### Expected behavior

![image](https://user-images.githubusercontent.com/6378625/149915281-c561230f-dbde-4c7e-98ef-7fcf76a06570.png)

### Files Version

Version: 2.1.2.0 OS Version: 10.0.19042.1288

### Windows Version

win 10

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/6378625/149915249-7e758208-edd7-4f37-b714-92a02de53e2a.png)

**Comment by Josh-65** [comment]
What your issue? "Con not show Dialog Question Replace And Copy File" means nothing. if you want to disable  the conflict dialog you can't.

**Comment by yaichenbaum** [comment]
Thank you for taking the time to report this, in order to investigate the issue we'll need the log files and steps to repro this bug, can you please reopen this issue using the issue template?

**Comment by Mahdihp** [comment]
Con not show "Replace or Skip Files" Dialog

**Comment by Josh-65** [comment]
Whats the name of the file in files

**Comment by Mahdihp** [comment]
any file

**Comment by Josh-65** [comment]
the file that was suppost to be replaced

**Comment by Mahdihp** [comment]
yes .Do not ask Replace or Skip Files

**Comment by Josh-65** [comment]
what do you mean yes. If a file with the same name is already there and you copy another file to it, it's going to ask for you to decided witch one you want witch you cna do and is what makes sence.

**Comment by revenz** [comment]
I just stumbled upon this too.   Whenevever I try to update some files,  Files asks me what to do for every single file.  Which is really annoying.  Is there any an option to just "Replace All" ?

**Comment by Josh-65** [comment]
it s been done via #5645

**Comment by revenz** [comment]
k, welll thats just bad user experience, something that would be very common hidden away behind a hot key.  it should be default to replace all files, unless copying into the same directory as source, exactly the same way Explorer does this.
