### ISSUE TITLE
Change Glass Theme’s On-unfocus Background

### ISSUE THREAD

**Issue by thierryntoh24** [files-community/Files#7778]
### What's the Problem?

When you chose the Glass Theme from themes, it works ok and is really beautiful until the app loses focus, then it just reverts back to black.

Im on my phone rn so I can’t attach a photo.

### Solution/Idea

I think it’d be cool if it could stay somewhat transparent still, like the Acrylic theme does, when focus has been lost.

### Alternatives

I set theme to Acrylic, although it’s not my most preferred (I don’t like the lines running through the app)

### Files Version

2.1.2.1

### Windows Version

Windows 10 Pro 1909 18363.1198

**Comment by Josh-65** [comment]
This is becuase it use acrylic and Windows will disable it when a window not in focus, i dont belive it can be changed.

**Comment by thierryntoh24** [comment]
🤦🏿‍♂️, Windows.
It just throws off the whole vibe of the theme.

**Comment by yaichenbaum** [comment]
@thierryntoh24 is this in light mode or dark mode?

**Comment by thierryntoh24** [comment]
Dark mode. I haven’t tried in Light mode.

Enviado desde mi iPhone

**Comment by yaichenbaum** [comment]
@thierryntoh24 this is the way Acrylic works.
