### ISSUE TITLE
Frezzing when accent color changes in Windows

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#7779]
### Description

I have my background as a slide show and accent color to auto change with it. Most of the time files will end up frezzing entirely either in the forground or background. The rare times it doesnt it will lag out for a while.
This also happends with transparacy being toggled but it will always freeze up.

### Expected behavior

The app should have minimal lag outs and should require a full resstart of files.

### Files Version

2.1.2.0

### Windows Version

10.0.19043.1466

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7889221/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7889222/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
@Josh-65 is this specific to Files or does it happen with all Windows apps?

**Comment by Josh-65** [comment]
Ive only encouned it with files. I havent tryed windows 11 with since how to does it seem to be diffrent

**Comment by yaichenbaum** [comment]
@Josh-65 it doesn't look like we have control over this process, but it looks smoother on Windows 11.
