### ISSUE TITLE
Can't Drag & Drop

### ISSUE THREAD

**Issue by ArthurMTX** [files-community/Files#7781]
### Description

https://cdn.discordapp.com/attachments/725514946112127057/933000056833998878/Desktop_18-01-2022_15-07-19.mp4

As you can see in the recording, I can't drag & drop a file, whatever the extention is. I can drag and drop out of the explorer, but not into it.

PM if more informations required at MitralyxL#1337

### Steps To Reproduce

1. Take a random file
2. Open an explorer window
3. Drag and drop the file INTO the explorer window

### Expected behavior

I simply expect the file to transfer to the destination window.

### Files Version

Version : 2.1.2.0 OS Version: 10.0.22000.434

### Windows Version

Windows 11 21H2 22000.434

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7889905/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7889909/debug.log)

https://cdn.discordapp.com/attachments/725514946112127057/933000056833998878/Desktop_18-01-2022_15-07-19.mp4

**Comment by gave92** [comment]
Are you able to drop on the folders on the sidebar or the file list or the navigation bar? Is the issue only dropping in the blank space?

**Comment by yaichenbaum** [comment]
Merging with #6941
