### ISSUE TITLE
Can't open the terminal

### ISSUE THREAD

**Issue by Anas-Elgarhy** [files-community/Files#7782]
### Description

I am trying to open the terminal inside the current path from the "Open in terminal" option but it is not responding

### Steps To Reproduce

1. Open Files
2. Go to the path
3. Clik on the right mouse button 
4. Clik on "Open in terminal" option

### Expected behavior

Open the Terminal in the current path 

### Files Version

Version: 2.1.2.0 OS Version: 10.0.19044.1466

### Windows Version

Windows 10 Pro Version	21H2

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7889966/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7889967/debug.log)

**Comment by azlan-syed** [comment]
you need to install the windows terminal software from the Microsoft store or go to settings and change the default shell (terminal)

**Comment by Anas-Elgarhy** [comment]
Oh yes the problem was resolved when I changed the default emulator from Tabby to Windows terminal and also when I changed it to Fluent terminal it seems the problem is related to my Tabby terminal or my configuration of the terminal.json file

**Comment by Anas-Elgarhy** [comment]
It turns out that the problem was because I didn't put the full path to the executable file

```json
   {
      "name": "Tabby Terminal",
      "path": "Tabby.exe",
      "arguments": "",
      "icon": ""
    }
```
