### ISSUE TITLE
Folder icon bug

### ISSUE THREAD

**Issue by chimichala** [files-community/Files#7784]
### Description

Some folder icons have black background for some reason. Its the same on every icon size except when i set it to detailed view, then its normal. 

### Expected behavior

Well, the background should by transparent.

### Files Version

Version: 2.1.2.0 OS Version: 10.0.22000.438

### Windows Version

Windows 11 Pro N 21H2 22000.438

### Relevant Assets/Logs

![Screenshot 2022-01-18 175415](https://user-images.githubusercontent.com/61027237/149983006-0e37e9d9-96b2-4c7c-9044-7ca0a9aba63b.png)

**Comment by gave92** [comment]
Tracked in #6373
