### ISSUE TITLE
Crash Dragging & Dropping tab items

### ISSUE THREAD

**Issue by HarriVainola** [files-community/Files#7785]
### Description

Crash after dragging & dropping tab items.

### Expected behavior

Purpose was sort tab items by name.

### Files Version

Version: 2.1.2.0 OS Version: 10.0.22000.434

### Windows Version

MS Windows 11 Home: 10.0.22000.434

### Relevant Assets/Logs

logs not available

**Comment by gave92** [comment]
Matching with #7796
