### ISSUE TITLE
Slow indexing SMB local network server

### ISSUE THREAD

**Issue by wodawoda** [files-community/Files#7788]
### Description

Files is very slow to index new files on the local server. After saving a new file you have to refresh the application window. The same happens when you delete a file or a directory. Maybe it is possible to use native [windows index ](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/indexers/using-indexers)mechanism or implement [Everything](https://www.voidtools.com) application index. Or automatic refreshing in the active window. The application is beautiful but unfortunately too slow

### Steps To Reproduce

1. the active window on drive M(local server) is open.
2. the file saved in this location is not visible without refreshing
Delete file, directory, no change without refreshing

### Expected behavior

file saved in place

### Files Version

Version: 2.1.2

### Windows Version

 Windows 11 Build 22000.466 

### Relevant Assets/Logs

f

**Comment by gave92** [comment]
Unfortunate limitation is the UWP platform. Issue tracked in #5869
