### ISSUE TITLE
Add option to share with bluetooth

### ISSUE THREAD

**Issue by 14AUDDIN** [files-community/Files#7789]
### What's the Problem?

Currently there's no option to share files across devices using Bluetooth.

### Solution/Idea

Add bluetooth sharing as an option in the share windows
![image](https://user-images.githubusercontent.com/42714433/150000039-bc75c8a7-36eb-4c5b-807d-6ab085d49fc8.png)

### Alternatives

Alternatively you could add the send to option in the right click menu from the regular Windows File Explorer
![image](https://user-images.githubusercontent.com/42714433/150001206-e4f936dc-0b4c-436b-84bf-217ef039ca6a.png)

### Files Version

2.1.2.0

### Windows Version

Windows 11 Home 21H2

**Comment by yaira2** [comment]
Merging with #7350
