### ISSUE TITLE
Better search with multiple files of the same name.

### ISSUE THREAD

**Issue by mattish91** [files-community/Files#7791]
### What's the Problem?

I have multiple files in a dev project that have the same name, i would love to see the actual file location to get the correct one 😬

### Solution/Idea

Add an option to view "file location" in the colums on the search page. or "location" if it's folders that im looking for.

### Alternatives

Open Windows explorer that can actually show me that information.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to find the correct files much easier | Must |
| This proposal will allow end users to find the correct file with ease | Should |

### Files Version

Version: 2.1.2.0

### Windows Version

Windows 10 21H2 19044.1466

### Comments

Well, if we could see the file location it would be much easier when selecting a specific file when searching, especially when i got 10+ files with the same name (php developer project, it's made to confuse/ eventual proprietary system leaks).

**Comment by Josh-65** [comment]
Same as #7070
