### ISSUE TITLE
Is it possible to bring flash memory/drive formatting feature?

### ISSUE THREAD

**Issue by legalMori** [files-community/Files#7793]
### What's the Problem?

Hi,

I use the application by default, but when I insert a flash memory, while formatting easily with the wibdows file manager, I could not see the formatting option in this application. Will it come in the future?

### Solution/Idea

Hi,

I use the application by default, but when I insert a flash memory, while formatting easily with the wibdows file manager, I could not see the formatting option in this application. Will it come in the future?

### Alternatives

Original windows Explorer

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Windows Version

windows 11 21h2

### Comments

Hi,

I use the application by default, but when I insert a flash memory, while formatting easily with the wibdows file manager, I could not see the formatting option in this application. Will it come in the future?

**Comment by Josh-65** [comment]
Right click the drive on the sidebar and formatt will be an option
