### ISSUE TITLE
A version that has working indexing when in safemod.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [files-community/Files#7794]
### What's the Problem?

When you activate windows 11 safe mode search is just gone and I am looking for an application that can safely mimic that as this is the first windows version where this is definitely an issue.

### Solution/Idea

Dunno - maybe a low grade shell style? Something ... dunno.

### Alternatives

None that I am aware of.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Windows Version

Windows 11 x64 pro mainline branch.

### Comments

This is not a huge priority.

**Comment by Josh-65** [comment]
Files use features from windows search. so it not possible unless they change the provide but im not sure on when or if there doing that.

**Comment by P3rf3ctXZer0** [comment]
I understand thanks for the information.
