### ISSUE TITLE
Crashes when i drag a tab into another tab

### ISSUE THREAD

**Issue by JackSkellet** [files-community/Files#7796]
### Description

As stated in the title. it crashes when i drag a tab into another tab

### Steps To Reproduce

1. open files
2. go to a dir
3. open another tab
4. drag first tab onto new tab

### Expected behavior

i would want this to open dual view, or it should do nothing at all

### Files Version

Version: 2.1.2.0 OS Version: 10.0.19043.1466

### Windows Version

Device name	DESKTOP-JD1RLG3 Processor	Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz   3.40 GHz Installed RAM	16.0 GB (15.9 GB usable) Device ID	4353DF37-36B3-48D0-9220-C4A5E42F85A9 Product ID	00326-10000-00000-AA357 System type	64-bit operating system, x64-based processor Pen and touch	No pen or touch input is available for this display

### Relevant Assets/Logs

cant find logs :/

**Comment by gave92** [comment]
Hi you can find the logs from Files settings > About > Open log location

**Comment by JackSkellet** [comment]
[debug.log](https://github.com/files-community/Files/files/7893031/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7893032/debug_fulltrust.log)

**Comment by azlan-syed** [comment]
yup same to me we may have a drag and drop animation too

**Comment by gave92** [comment]
Merging with #7838
