### ISSUE TITLE
ClickMoveAnimation OFF for Windows10

### ISSUE THREAD

**Issue by watya1** [files-community/Files#7799]
### What's the Problem?

Clicking on a file moves the line 

### Solution/Idea

I want to turn off the movement of lines when selected 

### Alternatives

I want an item that turns off animation when selected 

### Files Version

Version: 2.1.2.0 OS Version: 10.0.19042.867

### Windows Version

Windows 10 Pro 20H2

**Comment by yaichenbaum** [comment]
@watya1 does the option to turn off animations in Windows 10 help?

**Comment by watya1** [comment]
@yair100 It wasn't turned off with the optional animation off in windows10. 

![MoveIcon](https://user-images.githubusercontent.com/32918589/150038292-8f286c4f-b012-4fe3-a25e-3195df21fe74.gif)

**Comment by yaichenbaum** [comment]
> @yaichenbaum It wasn't turned off with the optional animation off in windows10.
> 
> ![MoveIcon](https://user-images.githubusercontent.com/32918589/150038292-8f286c4f-b012-4fe3-a25e-3195df21fe74.gif)

This seems to be a system behavior that was changed with Windows 11.

**Comment by watya1** [comment]
It can be inferred that it is difficult to correct if it is a movement peculiar to the system.
I hope someday it will be resolved. Thank you for your quick answer.
