### ISSUE TITLE
Add install button to toolbar when font files are selected

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#7800]

**Comment by puppetsw** [comment]
Happy to take this one on.

**Comment by LastDerivative** [comment]
@puppetsw Hello, Ive noticed that youve been active on a few threads so I was wondering if I can ask you for some help? This is my first time contributing to open source projects and I cant get visual studio to reflect changes to xaml files when running the app on db. The app does not reflect any of the changes ive made. Ive tried cleaning/building the sln but that isnt working, ive also tried doing that for each specific file as well. How do you get the changes to reflect on the app?

**Comment by puppetsw** [comment]
> @puppetsw Hello, Ive noticed that youve been active on a few threads so I was wondering if I can ask you for some help?

Hi @LastDerivative if you’re not already you should jump on the Files discord there are some very helpful people there and will be able to better guide you and is a better place to communicate. 

As for xaml changes not showing, I’m not sure what would cause that issue.

**Comment by d2dyno1** [comment]
This issue has been resolved with #7846
