### ISSUE TITLE
Folders icons have a black square border around them

### ISSUE THREAD

**Issue by washicjr** [files-community/Files#7802]
### Description

Folders icons have a black square border around them

![Screenshot 2022-01-18 184643](https://user-images.githubusercontent.com/28652385/150042407-4a4d5dfd-b020-4cb4-b940-bf5253b354e4.png)

### Steps To Reproduce

Nothing special, happens with each of the provided themes. Drilling into a folder causes this. Each version of Files that I have installed and each version of Windows 11 has had this issue.

### Expected behavior

No black squares around folders

### Files Version

Version: 2.1.2.0 OS Version: 10.0.22000.466

### Windows Version

Windows 11 Pro Version 21H2 (OS Build 22000.466)

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7893262/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7893263/debug_fulltrust.log)

**Comment by gave92** [comment]
Tracked in #6373
