### ISSUE TITLE
I hope it can change fonts

### ISSUE THREAD

**Issue by sunshineharry** [files-community/Files#7803]
### What's the Problem?

I hope the fonts of `Files` can be changed! I can use the other fonts to render interface. thank you

### Solution/Idea

I donnt have the solution to achive it.

### Alternatives

`OneCommander` can change the fonts, but i dont like it

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by azlan-syed** [comment]
we can ask for some fonts and we can have a font store with some cool fonts like neonderthaw, Rubik beastly, luxorius roman,etc

**Comment by sunshineharry** [comment]
Thank you for your response. Font store could be a great idea, but it can cause **Law Rick**, thus, can fonts be changed in theme? just in this file?

>https://files.community/docs/configuring/custom-themes 

thank you!

**Comment by LukoFoks** [comment]
Just a dropdown to select font from installed fonts would be amazing. Or maybe just a path to it. That is how Godot solved it. Everyone can always install more fonts themselves.

**Comment by yaichenbaum** [comment]
@sunshineharry you can change the default font using a custom theme
```
<ResourceDictionary
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:BelowWindows10version1809="http://schemas.microsoft.com/winfx/2006/xaml/presentation?IsApiContractNotPresent(Windows.Foundation.UniversalApiContract, 7)"
    xmlns:Windows10version1809="http://schemas.microsoft.com/winfx/2006/xaml/presentation?IsApiContractPresent(Windows.Foundation.UniversalApiContract, 7)">
    <ResourceDictionary.ThemeDictionaries>
        <ResourceDictionary x:Key="Default">
              <FontFamily x:Key="ContentControlThemeFontFamily">Comic Sans MS</FontFamily>
        </ResourceDictionary>
    </ResourceDictionary.ThemeDictionaries>
</ResourceDictionary>
```
