### ISSUE TITLE
Right-click drag support

### ISSUE THREAD

**Issue by tlitookilakin** [files-community/Files#7804]
### Solution/Idea

The standard file explorer allows one to drag items by holding right-click, and when "dropped", shows a small context menu allowing the user to choose how to process the dragged file(s). This is very convenient when multitasking with many files and folders at once. 

By default, windows offers Copy, Move, and Create Shortcut options, though some programs add extra options, so it's worth checking that in the same way Files already does for the ordinary context menu. (For example, I have a tool that provides a "create symlink" option to the right-click-drag context menu, which would be nice to have in Files too.)

### Alternatives

Since this is built into Windows, it works on File Explorer, which I can still use if necessary. File Explorer is otherwise less convenient for multitasking due to not having tabs. Cut/Copy + Paste keyboard shortcuts can be used as a placeholder, but do not offer full functionality.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to explicitly specify click-and-drag behavior for a given operation | Must |
| This proposal will allow end users to access the same drag context options available in File Explorer | Should |
| This proposal will allow end users to bypass the duplicate file behavior modal | Won't |

### Files Version

2.1.2.0

### Windows Version

Windows 10 21H2 120.2122.3920.0

### Comments

Parity with basic file explorer functionality

**Comment by yaichenbaum** [comment]
Merging with #1396
