### ISSUE TITLE
try adding icons 

### ISSUE THREAD

**Issue by azlan-syed** [files-community/Files#7805]
### What's the Problem?

// not a problem

I have a brilliant idea why not just make an icon theme. I mean we can change through icons of Windows 10 and 11 for Windows 10 people who want to experience Windows 11 and  people who miss Windows 10 in Windows 11

### Solution/Idea

make an icon theme of windows 10 from win 10 icons  and a windows 11 icon theme from windows 11 

### Alternatives

/*well sorry no alternatives*/

### Priorities

| Capability | Priority |
| :---------- | :------- |
| add icon themes from Windows 10 and 11 | Must |
| add the options for icon theme after adding the icons | Should |
| better if animations | Could |
| thanks in advance | Thanks |

### Files Version

Version: 2.1.2.0 

### Windows Version

Windows 10 20H2

**Comment by upintheairsheep** [comment]
Icon pack list:
*Windows 11 (default)
*Windows 10 (MDL2)
*Windows 8 (Metro)
*Windows 7 (Aero (also aero chocolate is really yummy try it if you ever go to Canada or Europe) )
*Windows XP (Luna)
*Windows Classic 
* Windows Classic Aesthetic
*Mac OS Classic B&W
*Mac OS Classic color
*Mac OS X Cheetah - Tiger
*Mac OS X Leopard - Mountain lion
* OS X Yosemite - macOS Catilina
* macOS Big Sur
*Android Snow Cone
*Android Nougat - Red Velvet Cake
*Android Lollipop - Marshmallow
*ANDROID Ice Cream Sandwich - KitKat
*Android 1.0 - Gingerbread
*iOS 6
*iOS 7
*iOS 13

**Comment by azlan-syed** [comment]
> Icon pack list: *Windows 11 (default) *Windows 10 (Fluent) *Windows 10 (MDL2) *Windows 8 (Metro) *Windows 7 (Aero (also aero chocolate is really yummy try it if you ever go to Canada or Europe) ) *Windows XP (Luna) *Windows Classic
> 
> * Windows Classic Aesthetic
>   *Mac OS Classic B&W
>   *Mac OS Classic color
>   *Mac OS X Cheetah - Tiger
>   *Mac OS X Leopard - Mountain lion
> * OS X Yosemite - macOS Catilina
> * macOS Big Sur
>   *Android Snow Cone
>   *Android Nougat - Red Velvet Cake
>   *Android Lollipop - Marshmallow
>   *ANDROID Ice Cream Sandwich - KitKat
>   *Android 1.0 - Gingerbread
>   *iOS 6
>   *iOS 7
>   *iOS 13
WOWWWW amazing
