### ISSUE TITLE
Feature: Add "Open with" to context menu when multiple files are selected

### ISSUE THREAD

**Issue by TeoMorabito** [files-community/Files#7806]
### What's the Problem?

I would love to be able to select multiple jpg files, right click, and open all those files with say photoshop.
As I remember this works in macos but the feature is lacking in windows (unless i'm missing a settings somewhere)

### Solution/Idea

Is this something that could be added to files?

### Alternatives

currently, selecting multiple images and right clicking to open with, only opens the file where the right click was initiated.

### Priorities

This proposal will allow end users to accomplish "open with" for multiple items at once

### Files Version

Version: 2.1.2.0 OS Version: 10.0.22000.434

### Windows Version

windows 11

**Comment by yaira2** [comment]
Thank you for your feedback, I added this to the todo list.

**Comment by hecksmosis** [comment]
This is already a feature afaik, albeit quite buggy

**Comment by yaira2** [comment]
@hecksmosis what types of issues? It might be best to track those separately.

**Comment by hecksmosis** [comment]
When selecting multiple files sometimes it only acts on the first one
