### ISSUE TITLE
one_click_clicker

### ISSUE THREAD

**Issue by azlan-syed** [files-community/Files#7807]
### What's the Problem?

not a problem but a suggestion 

add a setting that we should open folders in how many clicks this should be with choices and it should have 1 click and 2 click

### Solution/Idea

^ up above is the soultion

### Alternatives

nope no alternatives

### Priorities

| Capability | Priority |
| :---------- | :------- |
|  make a setting to set how many clicks are needed to open a folder  | Must |
| should be in options  | Should |
| animation kinda hoversome ?| Could |
| there should be only options on 1 click or 2 click | limit of clicks |

### Files Version

Version: 2.1.2.0 

### Windows Version

Windows 10 20H2

**Comment by gave92** [comment]
Take a look at Files settings > preferences > files and folders. There's "open files with one click" and "open folders with one click"

**Comment by azlan-syed** [comment]
> Take a look at Files settings > preferences > files and folders. There's "open files with one click" and "open folders with one click"

ik but maybe we should make a better UI
