### ISSUE TITLE
Back Button on mouse crashes app in Columns View with Multiple Tabs open

### ISSUE THREAD

**Issue by raulpop8** [files-community/Files#7808]
### Description

When ever I try to use the back button on my mouse, the app crashes. I tried this using the backspace button, witch works ok, but when ever I have more than one tab open, and I press the back button on my mouse (by mistake or not) the app crashes. 

### Steps To Reproduce

1. Click on Layout Options
2. Select Columns
3. Navigate to any folder
4. Click Back Button (on mouse) 
5. If the error doesn't appear, open new tab and navigate to a different folder
6. Click Back Button (on mouse)
7. The app crashes  

### Expected behavior

When I click the back button on mouse, it should go back home. 

### Files Version

Version: 2.1.2.0 OS Version: 10.0.22000.434

### Windows Version

Windows 11 Pro 21H2

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7894990/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7894991/debug_fulltrust.log)

**Comment by CrypticVader** [comment]
Same here in column view, at times Files navigates all the way back to Home when pressing the mouse back button, or it crashes.

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by QuaintMako** [comment]
Cannot reproduce it in 2.4.3 at all.

If we can get somebody else to give it a shot, that'd be nice.

**Comment by yaira2** [comment]
Let's close for now, we can reopen if it's still an issue
