### ISSUE TITLE
FilesFullTrust.exe - System Error

### ISSUE THREAD

**Issue by bagiosw** [files-community/Files#7809]
### Description

This error shows up once everytime Files is open, and then right-click a file (as far as I know, only image or video file). The second time I right-click the file again, it's normal no error. But if I close and reopened Files, it pops up again. So far there are 2 different error titles, the first one is **_FilesFullTrust.exe - System Error_**, and the other one is **_.NET-BroadcastEventWindow.4.0.xxxxxx: FilesFullTrust.exe - System Error_**. Both have the same message, **_Exception Processing Message 0xc0000005 - Unexpected parameters_**.

### Steps To Reproduce

1. Open Files
2. Right-click a file (image/video file as far as I know)
3. Error pops up, hit OK
4. Close Files
5. Step 1 and looped everytime I reopened Files and right-click particular file type

### Expected behavior

Right-click with no error

### Files Version

Version: 2.1.2.0

### Windows Version

Edition	Windows 10 Pro Version	20H2 Installed on	‎24/‎03/‎2021 OS build	19042.1415 Experience	Windows Feature Experience Pack 120.2212.3920.0

### Relevant Assets/Logs

![error](https://user-images.githubusercontent.com/15670237/150091630-bfa44a0d-3c5f-4fb1-a894-d2e4ffbcb718.gif)
![Screenshot (234)](https://user-images.githubusercontent.com/15670237/150085088-1e43e526-4a0f-487b-ae31-c3c008c6ebac.png)
![Screenshot_26](https://user-images.githubusercontent.com/15670237/150085115-0cc55bfe-2c25-4af2-a342-75f6180b06d2.png)
[debug.log](https://github.com/files-community/Files/files/7894981/debug.log)

**Comment by gave92** [comment]
What PC/ device you have?

**Comment by bagiosw** [comment]
> What PC / device do you have? Could you upload the second debug log as well?

I'm using a PC, it's Intel i5 CPU, ASUS GTX 750 Ti, 8,00 GB RAM if that helps. Did you mean another debug file? here it is: 
[debug.log](https://github.com/files-community/Files/files/7902014/debug.log)

**Comment by gave92** [comment]
Sorry I meant: on the same folder there should also be a second debug file called "debug_fulltrust.log". If it's not there that is interesting in itself :)

**Comment by bagiosw** [comment]
Oh sorry, here it is :
[debug_fulltrust.log](https://github.com/files-community/Files/files/7904171/debug_fulltrust.log)

**Comment by gave92** [comment]
Could you check if the same happens when you right click a folder or a e.g a ".txt" file?
If not, could you share a screenshot of the context menu that appears _in windows explorer_ when you right click on the ".png" image file if the first screenshot?
Thanks for the help 👍

**Comment by bagiosw** [comment]
Hey I'm sorry for the late reply, I was away from my PC for days.

> Could you check if the same happens when you right click a folder or a e.g a ".txt" file?

When I right click a txt file, it's normal, with no error. 

> If not, could you share a screenshot of the context menu that appears _in windows explorer_ when you right click on the ".png" image file in the first screenshot?

Okay here it is:
![image](https://user-images.githubusercontent.com/15670237/150628976-be0f30fa-896f-4958-b921-7952d01b7447.png)

**Comment by gave92** [comment]
Thanks, given that it works for txt files I suppose one of the entries for png files is causing the issue.
- Could you also post a screenshot of windows explorer's context menu for txt files? (so we can check the differences)
- What program adds the 3 items "resize picture"/"rotate left"/"rotate right"?

**Comment by bagiosw** [comment]
> * Could you also post a screenshot of windows explorer's context menu for txt files? (so we can check the differences)

Okay, here
![image](https://user-images.githubusercontent.com/15670237/150762889-1c28bc51-6dd5-44c5-ad2a-8abfed0c83aa.png)

> * What program adds the 3 items "resize picture"/"rotate left"/"rotate right"?

For the "resize picture" I think it's from a program called PowerToys, same for the "PowerRename", but for the "rotate right/left" I forgot, it's built in item isn't it? I just read it from Winaero [here](https://winaero.com/remove-rotate-left-rotate-right-context-menu-windows-10/), it said `"Windows 10 allows you to do it without using third party tools. The built-in functionality will allow you to do it quickly right from the File Explorer app"`.

**Comment by bagiosw** [comment]
Oh and I think the error leads to "weird" behavior. So after the error, the "additional items" in the context menu disappeared. But before that, it's there, let me show you.

Here's the context menu of a .txt file before the error:
![Screenshot_3](https://user-images.githubusercontent.com/15670237/150766453-0aab5a9b-3b17-4258-be1c-f2e51e6fbe3b.png)

And here's it after the error shows up:
![Screenshot_4](https://user-images.githubusercontent.com/15670237/150766665-4e30b75f-253f-49f9-8ec1-51a786d26179.png)

All of them are just gone, same for all types of files. But It;s there again after I reopen the Files. Hope it helps you.

**Comment by gave92** [comment]
Thanks for the info, I'll test with power toys.
To restore the missing items you can also minimize and restore the app instead of restarting it.

**Comment by bagiosw** [comment]
Great, good luck.
> you can also minimize and restore the app instead of restarting it.

Ohh that's true I just tested it, and so the error also occurred after minimizing and restoring the app.

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?
