### ISSUE TITLE
Bulk rename feature

### ISSUE THREAD

**Issue by SoesBR** [files-community/Files#7813]
### Solution/Idea

**It's an idea**

If we look at the Finder rename system, we will notice there's an advanced option to rename a file, better, files! Yes, renaming many files at one time should be amazing. Should we look for perfection? So, why not rename the files with a chosen prefix and automatic date suffix?

To reference, follow some useful links: 

Video shows rename system:
[https://youtu.be/B5gY6pxyoV4](url)

Rename's user guide:
[https://support.apple.com/en-mt/guide/mac-help/mchlp1144/mac](url)

### Alternatives

No alternative 😁

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Rename many files at the same time | Should |
| Rename with a format and auto prefix, as date, counting or index | Could |

### Files Version

v2.1.2

### Windows Version

Windows 11 21H2 22000.466

### Comments

It's not an issue, just a nice idea that I'm looking for - you guys are doing a great job, the Files app looks beautiful!

Have a nice day, thanks and take care.

**Comment by yaichenbaum** [comment]
@SoesBR have you tried Powertoys?

**Comment by el-tavares** [comment]
Yes, @yair100, I tried Powertoys, pretty good, but not enough - I wish to rename files using the date that's they were created, not the current date. May even with hour time!

Example: "photo212ba65" to "Photo_02-06-19"

**Comment by DutchEclipse** [comment]
If it renames files just as in file explorer (Renamed title +1 suffix behind it)  that would be great.

**Comment by yair100** [comment]
> Yes, @yair100, I tried Powertoys, pretty good, but not enough - I wish to rename files using the date that's they were created, not the current date. May even with hour time!
> 
> Example: "photo212ba65" to "Photo_02-06-19"

@SoesBR can you request that on the Powertoys repository? Building a powerful rename feature is possible but the one in Powertoys already works pretty well.

**Comment by DerpFromAbove** [comment]
There actually is an app you may be interested in:
Bulk Rename Utility
Its features include:
Bulk renaming (duh)
Search and replace
Remove characters (say, the first or last 3 characters in a file name)
Add text as prefix, suffix or inside the file name
Auto date (fully customizable, of course)
Auto numbering 
Add folder name as prefix/suffix
Change/add file extensions
