### ISSUE TITLE
Support opening application from the path editbox

### ISSUE THREAD

**Issue by StefanLobbenmeier** [files-community/Files#7814]
### What's the Problem?

In explorer.exe, you can start a new cmd at the current folder by typing "cmd.exe" in the path editbox. I also like to open IntelliJ at the current folder using "idea .".

This is what I mean in explorer.exe:
![image](https://user-images.githubusercontent.com/36509607/150145968-8e03b420-9f60-4222-b31e-1a87daca3397.png)

In the files app, "cmd" actually works somehow. But typing other things on the path, like idea gives an error:

![image](https://user-images.githubusercontent.com/36509607/150146031-f339e687-9721-425d-8848-b32edbc4c3b6.png)

### Solution/Idea

Match the behaviour of explorer.exe and open the application. I am pretty sure this could be achieved by running

```cs
using System.Diagnostics;
...
Process.Start("process.exe");
```

But I am not 100% sure if that is the exact logic / recognizing that the user is actually trying to do that. Probably involves manually verifying that the provided application name is actually an executable on the path.

### Alternatives

As a workaround I have to start a terminal at the current location and type the command in there.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Start applications entered in the path editbox | Must |
| Pass the arguments to it | Must |
| Keep the launched application open when files closes | Must |

### Files Version

2.1.2.0

### Windows Version

Edition	Windows 10 Enterprise Version	21H2 Installiert am	‎04.‎08.‎2020 Betriebssystembuild	19044.1415 Leistung	Windows Feature Experience Pack 120.2212.3920.0

**Comment by yaichenbaum** [comment]
@StefanLobbenmeier that sample would work but it would need to open the application in the current directory. Do you want to work on this?

**Comment by StefanLobbenmeier** [comment]
I do not have a development environment setup, but I think Azure can build it and I test it after fixing it with a text editor 😄

**Comment by gave92** [comment]
Tracked in #5677
