### ISSUE TITLE
Opening Zip Files

### ISSUE THREAD

**Issue by doodlemania2** [files-community/Files#7815]
### Description

When I attempt to open a zip file (expecting it to open like the standard Windows file manager) with a double click, nothing happens.

### Steps To Reproduce

1. Download a zip to /Downloads
2. Double click zip file
3. *should open zip file*

### Expected behavior

Open the zip file so I can grab a file or files.

### Files Version

Version: 2.1.2.0 OS Version: 10.0.22538.1000

### Windows Version

Version 10.0.22538.1000

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7897858/debug.log)

**Comment by TheAlienDrew** [comment]
I also have this same issue, and 7-Zip was set as the default ZIP program for my computer, prior to using this app.

**Comment by Andrew-J-Larson** [comment]
@yair100 & @doodlemania2 found a work around. For all the effected file types (that are previously associated in a different program than Windows Explorer, e.g. 7-Zip, prior to using Files), you need to reset the default file association back to normal Windows Explorer, and then change it back.
