### ISSUE TITLE
Recent files does not respect the "single click" to open a file preference

### ISSUE THREAD

**Issue by EricAtORS** [files-community/Files#7818]
### Description

When I open a new tab, at the bottom of the main frame, I have a "Recent Files" section. When I single click on a file in that section, it opens that file.
My preferences say that it should require 2 clicks, but a single click opens the file. This does not happy anywhere else, as far as I can tell.

### Steps To Reproduce

1. Set your preference "Open files with a single click" to off
3. Open a new tab.
4. Click on a file in the recent files.

### Expected behavior

For the recent files widget to respect my preference

### Files Version

Version: 2.1.2.0 OS Version: 10.0.18363.1977

### Windows Version

Windows 10 1909

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7898908/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7898910/debug_fulltrust.log)

**Comment by gave92** [comment]
Tracked in #6074
