### ISSUE TITLE
Reduce Tile height in Tiles layout

### ISSUE THREAD

**Issue by CrypticVader** [files-community/Files#7820]
### What's the Problem?

Currently, files & folders look oversized in Tiles layout, compared to Explorer.

### Solution/Idea

Reducing the size of the tiles.

### Alternatives

Provide an option in settings to reduce to size of items in Tiles layout.

### Files Version

v2.1.2.0

### Windows Version

Windows 11 21H2 22000.466

### Comments

In Files:
![image](https://user-images.githubusercontent.com/61494838/150190387-5b1b0765-0b4e-454a-a6a4-bc3259c7d8c7.png)
In Explorer:
![image](https://user-images.githubusercontent.com/61494838/150190400-982301ed-9ed6-4520-b2f1-7bfb56ec3956.png)

**Comment by CrypticVader** [comment]
#7824 has fixed this. So ig this issue can be closed.

**Comment by d2dyno1** [comment]
This should be resolved with #7820
