### ISSUE TITLE
Ajout de l'icone Affiché/Caché les fichiers caché dans la barre d'icone.

### ISSUE THREAD

**Issue by riksque** [files-community/Files#7821]
### What's the Problem?

Il faut aller dans les paramètres pour pouvoir afficher les fichiers ou dossiers caché, il serait bien d'avoir une icone raccourci dans la barre d'icone.

![Sans titre 1](https://user-images.githubusercontent.com/93746398/150199197-a9e39d8d-f677-4536-b8f2-33e2d35041a4.jpg)

### Solution/Idea

Il serait bien d'avoir une icone raccourci dans la barre d'icone.

![Exemple](https://user-images.githubusercontent.com/93746398/150199269-cd7225d9-3945-4d60-90ca-488ec40fde89.jpg)

### Alternatives

je ne sais pas.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Comments

Votre appli est super, et quand même mieux faites que l'explorateur Windows.
Voilà une appli qui donne ce que beaucoup d'utilisateur demande à microsoft depuis des années.
Merci beaucoup.

**Comment by yaichenbaum** [comment]
You can adjust this option from the layout/view flyout. 
![image](https://user-images.githubusercontent.com/39923744/150206223-7f25fc07-4929-45d3-b546-e739b0c06666.png)

**Comment by riksque** [comment]
Merci beaucoup, je ne l'avait pas vu.
Bonne continuation.
