### ISSUE TITLE
[Feature Request] Option to not show delete confirmation popup

### ISSUE THREAD

**Issue by the-mr-matt** [files-community/Files#7823]
### What's the Problem?

I find it cumbersome deleting a number of files when each one has to be confirmed.

![image](https://user-images.githubusercontent.com/36836699/150216915-fc9c2e0a-0119-49eb-a756-3e0217b95ad7.png)

### Solution/Idea

I propose a checkbox, "don't show this again", and a toggleable option in the settings menu.

### Alternatives

N/A

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to not be shown the delete confirmation popup repeatedly | Should |

**Comment by yaichenbaum** [comment]
You can turn off the confirmation dialog from settings > preferences > files and folders
![image](https://user-images.githubusercontent.com/39923744/150217283-b943205e-c797-46b7-bf02-10eb29b54fa6.png)
