### ISSUE TITLE
Redirect issues

### ISSUE THREAD

**Issue by J4kulMei** [files-community/Files#7825]
### Description

When I for example open edge go to customs in page layout and upload my own image, it always uses file explorer.

### Steps To Reproduce

1. Go to edge
2. Tap settings
3. Press custom
4. Your own image
5. Upload
6. It redirects to file explorer

### Expected behavior

It should open files.

### Files Version

Version: 2.1.2.0 OS Version: 10.0.19044.1466

### Windows Version

21H2

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/94040450/150266993-1fa3d3dd-6c7f-47b9-a890-e40bdf0f9b31.png)

**Comment by gave92** [comment]
Open and save file dialogs are not yet implemented but we're looking at how to do it.
