### ISSUE TITLE
Unmapped Network drives and WSL directories not showing

### ISSUE THREAD

**Issue by CEbbinghaus** [files-community/Files#7826]
### Description

Network drives do not show up at all if they are unmapped (i haven't tried mapped yet) and the WSL submenu with its directories is missing too. Both of them are enabled in the settings

### Steps To Reproduce

* Run a second PC on the network with network sharing enabled
* Launch Files and enable show Network Drives section in the Sidebar dropdown

### Expected behavior

It to show all Available network drives as Windows File Explorer does.

### Files Version

2.1

### Windows Version

Windows 11 21H2 Build 22000.434

### Relevant Assets/Logs

<img width="373" alt="image" src="https://user-images.githubusercontent.com/31423391/150268385-b856a688-e46d-45de-a434-2228f051d69e.png">

**Comment by d2dyno1** [comment]
This has been resolved with #7931 @CEbbinghaus
