### ISSUE TITLE
OneDrive sync Icon too big on Small/Medium/Large icons or Tiles layout.

### ISSUE THREAD

**Issue by EvaRune** [files-community/Files#7829]
### Description

I haven't seen this bug reported yet but I may have missed it.
On OneDrive folders, the sync icon is getting way too big and seem to scale with the icon itself instead of keeping a fixed size.

### Steps To Reproduce

1. Open a folder from OneDrive.
2. Set the Layout to either Tiles or Small/Medium/Large Icons.

### Expected behavior

Sync icons should stay their initial size like on the default file explorer, no matter what layout is chosen.

### Files Version

2.1.2.0

### Windows Version

Windows 11 21H2 22000.434

### Relevant Assets/Logs

In Files v2.1.2.0
![Sync icons are too big](https://user-images.githubusercontent.com/6675362/150303701-e565e18f-f223-4bb7-995e-e79f6d1d0d14.png)

In Explorer
![Here's how it looks on regular file explorer.](https://user-images.githubusercontent.com/6675362/150303915-88da4d6d-d838-4c81-b4d0-fdf6e5b6cf1d.png)

**Comment by gave92** [comment]
Thanks for the report. Sounds like #7452
