### ISSUE TITLE
Create New any Office Document is not working

### ISSUE THREAD

**Issue by lakani** [files-community/Files#7830]
**steps** 
1. navigate to any folder 
2. Press New and select any Microsoft Office Related documents like Word or Excel 
3. enter the new file name in the popup window
4. press (Set Name)

**Actual Results**

- nothing happened, even after pressing refresh  

**Expected Results**

- a new word file should be created

**Comment by yaichenbaum** [comment]
Thank you for taking the time to report this, in order to investigate the issue we'll need the log files and version info, can you please reopen this issue using the issue template?
