### ISSUE TITLE
Add set as Lockscreen button to toolbar when image files are selected

### ISSUE THREAD

**Issue by esibruti** [files-community/Files#7834]
### Solution/Idea

Adding a toolbar button will increase ease of use when setting an image as lockscreen.

### Alternatives

NA

### Comments

Related: [https://github.com/files-community/Files/issues/7769#issuecomment-1016431345](https://github.com/files-community/Files/issues/7769#issuecomment-1016431345)

**Comment by puppetsw** [comment]
The "Set as background" could be changed to a flyout labelled as "Set as..." for example, and have it drop-down so you can choose either lockscreen or desktop. But, for me, changing the lockscreen isn't a "common" task, so just having the desktop background button is sufficient in my use case.

**Comment by yaichenbaum** [comment]
Adding a flyout would require two clicks to choose an action which will in most cases end up being the set as desktop background option.

**Comment by BanCrash** [comment]
> Adding a flyout would require two clicks to choose an action which will in most cases end up being the set as desktop background option.

What about "Set as... Background" but if you right click it shows the flyout? Left-clicking will have the same effect (setting as background)

**Comment by yaichenbaum** [comment]
@BanCrash one of the goals of the toolbar is ease of access, would adding a menu flyout would have any benefit over the existing context menu?

**Comment by BanCrash** [comment]
> @BanCrash one of the goals of the toolbar is ease of access, would adding a menu flyout would have any benefit over the existing context menu?

Yep, I think you are right. Then would be to add another button but just in case there is space for that.

Maybe we can recover the option to customize the toolbar so the users can choose what they want to have or not in the amount of space that we have.

**Comment by generalguy41** [comment]
Not sure what the proper element is called, but instead of a separate button why not a split button? The primary button is to set as desktop, and the arrow would show the dropdown to set as lockscreen. Personally, when I change my desktop, I always set my lockscreen to match, so this would be very useful to me.

**Comment by yaichenbaum** [comment]
@generalguy41 do you have a concept or design showing how this would work?

**Comment by generalguy41** [comment]
> @generalguy41 do you have a concept or design showing how this would work?

@yair100 Split button examples in latest Word Office Insider preview:
![image](https://user-images.githubusercontent.com/8879244/153415303-982bea20-4d94-48c9-8a81-82f8046fd3c3.png)
![image](https://user-images.githubusercontent.com/8879244/153415334-83d540b0-7394-4a0c-bff6-0bd8f38882ca.png)

Icon only example in latest Paint preview:
![image](https://user-images.githubusercontent.com/8879244/153417511-b6f647d2-9591-4dfc-b072-788c164e572a.png) ![image](https://user-images.githubusercontent.com/8879244/153417554-588dc952-589d-4fcc-a0a9-1dd08f6126cd.png)


Pressing the button performs the action labeled on the button, and pressing the arrow presents a list of secondary options (while also maintaining the primary option):
![image](https://user-images.githubusercontent.com/8879244/153415718-fdd403bc-a18f-462c-8fe0-86951fbc53cd.png)

I think this is the correct Windows documentation for it: 
https://docs.microsoft.com/en-us/windows/apps/design/controls/buttons#create-a-split-button
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.splitbutton?view=winrt-22000

**Comment by yaichenbaum** [comment]
@generalguy41 I should have explained, we use split buttons in Files, the question was how it can work with the existing toolbar UI.

**Comment by generalguy41** [comment]
@yair100 here's a quick mockup. Something like this:
![image](https://user-images.githubusercontent.com/8879244/153595483-6b3df36e-d520-44c3-905f-706bf4a44338.png)
![image](https://user-images.githubusercontent.com/8879244/153595555-bf6cc9aa-81e9-4ed1-97c7-0090b873bd99.png)
![image](https://user-images.githubusercontent.com/8879244/153595929-e52bc631-51a4-4d10-9624-0c2a4af403b3.png)
![image](https://user-images.githubusercontent.com/8879244/153596920-e536ecf9-e3be-4c8c-a4fd-8f6d2de146a5.png)

**Comment by yaichenbaum** [comment]
![image](https://user-images.githubusercontent.com/39923744/153597410-c9cfb916-58e3-4440-8073-ecf33c0b3def.png)
This looks like a regular flyout, in order for the slip button to work, it would need a solid background.

**Comment by puppetsw** [comment]
> I think we can do this if it works like a regular flyout, while it would add an extra click, it's still easier to find the toolbar option than the context menu.
> 
> @puppetsw do you want to implement this one?

@yair100 Sure!
