### ISSUE TITLE
Please add an working indicator when attempting to delete large files/folders

### ISSUE THREAD

**Issue by kpervin** [files-community/Files#7835]
### What's the Problem?

When attempting to delete a large folder, Files did not seem to respond to my request. However, after a while, it finally showed a popup asking if I wanted to delete or permanently delete. Because I had hit this several times, multiple popups showed up.

### Solution/Idea

Please either add a loading indicator, a progress bar indicating any sort of indexing, or some sort of visual to the user that the program did indeed accept my delete command.

### Alternatives

Lock the user out of the delete command if a current delete operation is in progress. That indicates to the user that the first delete command was accepted and that it is currently doing some sort of work in the background.

### Files Version

Version: 2.1.2.0 OS Version: 10.0.19042.1466

### Windows Version

Edition	Windows 10 Home Version	20H2 Installed on	‎2021-‎10-‎22 OS build	19042.1466 Experience	Windows Feature Experience Pack 120.2212.3920.0

**Comment by gave92** [comment]
When you issue the first delete command is the UI "freezed"? E.g can you scroll the file list or is everything locked up?

**Comment by gave92** [comment]
Could you clarify if this happens also when deleting a single item or only when many items are selected?

**Comment by Ein-Tim** [comment]
@kpervin Is this issue still relevant?

**Comment by Josh-65** [comment]
@kpervin Is this still an issue in 2.3.11?

**Comment by kpervin** [comment]
> @kpervin Is this still an issue in 2.3.11?

Let me redownload the version and attempt

**Comment by kpervin** [comment]
@Josh-65 The delete modal shows up immediately, but the delete process still takes a long time.

**Comment by Josh-65** [comment]
Thats good since this issue is about the confimation dialog i will close this. The speed with progress should be improved with the next stable build and better status are tracke din #4811
