### ISSUE TITLE
Bundles Widget

### ISSUE THREAD

**Issue by Woksben** [files-community/Files#7837]
### Description

I cannot create more than one bundle at a time...

the three dots at the right-hand side of the bundle widget not respond
![Screenshot 2022-01-20 173118](https://user-images.githubusercontent.com/88069105/150380961-93b5e919-6c73-4891-b3a0-3b13301351bc.png)
 whenever I click on it.

### Expected behavior

list of drop down options to select from

### Files Version

Files v2

### Windows Version

Windows 11 Pro 21H2 22000.434

### Relevant Assets/Logs

![Screenshot 2022-01-20 173118](https://user-images.githubusercontent.com/88069105/150381486-fa16b752-5ffe-40df-8c57-203c4480a489.png)

**Comment by gave92** [comment]
Fixed in #7314
