### ISSUE TITLE
Files app crash when two tabs are opened and then one of the tab is dragged and dropped.

### ISSUE THREAD

**Issue by venktesh3** [files-community/Files#7838]
### Description

The app crashes when two tabs are opened and then one of the tab is dragged and dropped anywhere on the screen. I tried opening from 1 - 10 tabs, and this only happens when two tabs are opened.

### Steps To Reproduce

1. Open two tabs in files app.
2. Drag and drop a tab anywhere in the screen.

### Expected behavior

It was expected to create two different windows or either just do nothing and get back to its position from where it was dragged.

### Files Version

Version: 2.1.2.0

### Windows Version

Windows 10 21H1 19043.928

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7907415/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7907416/debug_fulltrust.log)

**Comment by jiejasonliu** [comment]
@yair100 resolved with #8433 right?

**Comment by yair100** [comment]
> @yair100 resolved with #8433 right?

Yes

**Comment by yaichenbaum** [comment]
@venktesh3 this issue is resolved in `main` and will be included in the next release of Files.
