### ISSUE TITLE
App Crashed when moving Favs, now no Hard Drives show

### ISSUE THREAD

**Issue by daveo132** [files-community/Files#7839]
### Description

I was setting up the app on my PC, I was adding and organising my favourites which caused the app to crash.
On reopening the app, my hard drives and network drives no longer show.
![image](https://user-images.githubusercontent.com/96916642/150412056-698207c3-47b3-416e-922a-21d44b0e3d2f.png)
![image](https://user-images.githubusercontent.com/96916642/150412123-4461700d-fddd-4d9c-8677-5adb9c271727.png)

### Steps To Reproduce

1. Add favourites
2. Move / reorder favourites
3.  App crashed

### Expected behavior

App not to crash / no lose all local drives

### Files Version

Version: 2.1.2.0 OS Version: 10.0.19044.1466

### Windows Version

Edition	Windows 10 Home Version	21H2 Installed on	‎24/‎03/‎2021 OS build	19044.1466 Experience	Windows Feature Experience Pack 120.2212.3920.0

### Relevant Assets/Logs

Images added to first post.

**Comment by gave92** [comment]
Thanks for the report. Please upload the 2 app's log files.

**Comment by daveo132** [comment]
[debug_fulltrust.log](https://github.com/files-community/Files/files/7912211/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7912212/debug.log)

Hi, thanks for getting back to me.  Are these to ones you need?

**Comment by daveo132** [comment]
Ironically, the drives are now showing again.
I haven't reset my PC, I just left it running over night and it seems to have fixed itself.  Hopefully something in those logs will point in the right direction.
Let me know if you need anything else from me.

**Comment by Josh-65** [comment]
Have you encounted this issue again?
