### ISSUE TITLE
Mapped network drive won't load all files and folders

### ISSUE THREAD

**Issue by reedjaz** [files-community/Files#7840]
### Description

Hi there, the Files app can open mapped network drive, but it won't display all files and folders. For example I have attached a screenshot. The network drive should have 800 items inside (shown on Windows File Explorer), but on Files app, it only shows 32 items.

### Expected behavior

It should display all of the mapped network drive contents (files and folders).

### Files Version

Version: 2.1.2.0 OS Version: 10.0.22000.438

### Windows Version

Windows 11 21H2 22000.438

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/17940791/150412555-571057ac-5fee-48ed-af71-e65641ed6385.png)

**Comment by megamorf** [comment]
Seems to be related to #3903. It's taking very long to enumerate the items on the share and they will slowly pop up in batches. Might be a duplicate even.

**Comment by Josh-65** [comment]
Is this still an issue. if so have you tried waiting a while and seeing if it loads more?
