### ISSUE TITLE
Fonction Couper/Coller inactive dans Win11

### ISSUE THREAD

**Issue by JackPro72** [files-community/Files#7844]
### Description

Bonjour.
J’utilise ce logiciel ‘Files’ depuis qqes jours sous WIN11 et je n’arrive pas à faire de **Couper/coller** !
Dans la liste de taches en cours, l’action est marquée comme effectuée mais le fichier n’est pas déplacé. Idem pour un répertoire.

En faisant différents tests, j’ai remarqué que _cela fonctionnait bien si ‘Files’ n’était pas déclaré comme l’explorateur de fichiers par défaut._

Etonnant.

### Expected behavior

Déplacement du ou des fichiers. 
Idem pour le ou les dossiers.

### Files Version

Version : 2.1.2.0 OS Version: 10.0.22000.434

### Windows Version

Windows 11 Famille Version 21H2 

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7908626/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7908627/debug_fulltrust.log)

**Comment by Josh-65** [comment]
Merging with #8757
