### ISSUE TITLE
Layout Mode Missing

### ISSUE THREAD

**Issue by Angell1993** [files-community/Files#7845]
### What's the Problem?

List layout mode missing.. 

### Solution/Idea

Add List Layout Mode..

### Alternatives

None

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.1.2.0

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎Dec ‎19 ‎Sun ‎2021 OS build	22000.434 Experience	Windows Feature Experience Pack 1000.22000.434.0

**Comment by gave92** [comment]
Tracked in #2509
