### ISSUE TITLE
Bundle not working

### ISSUE THREAD

**Issue by andrefiaschi** [files-community/Files#7847]
### Description

I cannot create more than 1 Bundle. The ... button does not work after 1 created.
And the one Bundle I created eventually disappears...

### Expected behavior

Create more Bundles and do not disappear.

### Files Version

2.1.2.0

### Windows Version

Windows 11 Home Single Language 21H2

### Relevant Assets/Logs

None.

**Comment by gave92** [comment]
Tracked in #7743
