### ISSUE TITLE
New Icons

### ISSUE THREAD

**Issue by upintheairsheep** [files-community/Files#7849]
### What's the Problem?

Nothing.

### Solution/Idea

Add icons to a few unthemed commonly used folders

* AppData folder

- AppData folder

- C:/Windows
- System 32
- C:/Users

- Local (AppData)
- Roaming (AppData)
- LocalLow (AppData)
- Program files

- Program files (x86)
- WindowsApps from program files
- Packages from AppData

- Google and chrome from AppData

- . Minecraft folder

- Driver's folder
- Temp from AppData local
- programdata folder
- System Volume Information
- $ Recycle Bin $

Folders for external drives not created by Windows and appears when another device is plugged in
- /.Trashes (macOS trash) 
- /Android (Android general data on SD card or otg)
- /LG Smart TV (LG webOS tv image cache)
- 

### Alternatives

N/A

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
@upintheairsheep thank you for your feedback, for changing thumbnails, we'd prefer to let users customize it on their own rather than making a change like this from the app.
