### ISSUE TITLE
Opening new tabs duplicates themes

### ISSUE THREAD

**Issue by BusteanHAN** [files-community/Files#7851]
### Description

On a new instance, the custom themes tab shows the normal amount of themes (I mean the included ones).
For every new tab that is opened through pressing Win + E, all the themes get duplicated in the list.

Normal:

![Screenshot 2022-01-21 095521](https://user-images.githubusercontent.com/60746455/150497276-14ca0a5e-c0ff-4793-99d6-ee4ec7a05577.jpg)

### 
The problem:

https://user-images.githubusercontent.com/60746455/150498271-1104fad2-49ca-41f3-af4b-f76651c1aaf7.mp4

Steps To Reproduce

1. Open the program
2. Check Settings -> Custom Themes, everything should be normal
3. Open new tab, by using Win +E
4. Check Settings -> Custom Themes, the themes have now doubled;
For every new tab a new set of the same themes is added

### Expected behavior

Themes should not be loaded anew each time a new tab is opened with Win + E

### Files Version

Version: 2.1.2.0 OS Version: 10.0.19042.1466

### Windows Version

Windows 10 Pro 20H2 19042.1466

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7911812/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7911813/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #9317
