### ISSUE TITLE
Cannot resize or move from top bar when settings menu is open

### ISSUE THREAD

**Issue by BusteanHAN** [files-community/Files#7852]
### Description

The top edge is not selectable for resizing or moving when the settings menu is open

![Issue](https://user-images.githubusercontent.com/60746455/150499661-1ebefae5-da56-49f3-aef3-d23e7025e44d.gif)

### Steps To Reproduce

1. Open settings menu
2. Mouse over top edge, the cursor does not change, and you cannot resize or move the window

### Expected behavior

Being able to resize from top edge and to move window from top bar

### Files Version

Version: 2.1.2.0 OS Version: 10.0.19042.1466

### Windows Version

Windows 10 Pro 20H2 19042.1466

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7911838/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7911839/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
This is resolved in `main`.
