### ISSUE TITLE
mouse clicks are buggy sometimes

### ISSUE THREAD

**Issue by Animanion** [files-community/Files#7853]
### Description

I am using files instead of windows explorer and I think it's the best app I have used after a very long time on windows 10, it is far better than windows explorer, RAM and CPU consumption is also very low as compared to the default explorer. but sometimes the mouse clicks act weirdly, sometimes a folder opens with a single click and sometimes doesn't respond even after several double clicks. I see the app improving and getting better with each passing day. I hope this would be fixed very soon.
Thank you

### Steps To Reproduce

simply browse through the system and folders with a mouse.

### Expected behavior

I don't see any particular reason for the double click and single click bug. It's just happening randomly.

### Files Version

Version: 2.1.2.0 OS Version: 10.0.19043.1466

### Windows Version

Windows 10 21H1 (19043.1466)

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7913473/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7913477/debug.log)

**Comment by Josh-65** [comment]
It will be becuase it's loading the directory i believe. Have you looked in th tab icon area for a loading icon?
