### ISSUE TITLE
Compact View

### ISSUE THREAD

**Issue by jaredratcliff** [files-community/Files#7854]
### Solution/Idea

I think the Files app would greatly benefit from a compact mode, similar to what is present in the Windows 11 files manager (click "view" -> "compact view"). This would compress the list vertically, allowing me to see more items on the screen at once when using the "details" layout or the "columns" layout.

### Alternatives

The built in Windows files explorer app: it already has the option to turn on compact mode in Windows 11.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to see many more files on the screen at once when using the "Columns" or "Details" layouts | Must |
| This proposal will allow end users to see many more files on the screen at once when using the "Tiles" layout | Could |

### Files Version

Version: 2.1.2.0

### Windows Version

Windows 11 21H2 22000.438

**Comment by yaichenbaum** [comment]
Merging with #1940
