### ISSUE TITLE
Feature: Add an access denied error when drive/folder is blocked because of permissions

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#7856]
### What feature or improvement do you think would benefit Files?

I have set a drives permissions for a user account to not allow access, it works but is not very clear to the user that there are permissions stoping them from seeing the drives contents, I presume this happends for folders too.

### Steps to reproduce

1. Open drives properties page (don't do it on the C drive it will brake Windows)
2. set a user account to deny on the full control option
3. accses the drive with that denied account
4. see the "folder is empty" message

### Requirements

- Display access denied error instead of opening the drive

### Files Version

2.3.11.0

### Windows Version

10.19043.1899

**Comment by yaichenbaum** [comment]
@Josh-65 can you add steps t reproduce?
