### ISSUE TITLE
''Recent Files'' option 

### ISSUE THREAD

**Issue by 2ndwonder** [files-community/Files#7857]
Recent Files option is missing in the settings. Even though the function in Windows 11 is disabled.

**Comment by Josh-65** [comment]
If it's disabled in Windows then it will be disabled in files. Please use the issue templates next time.

**Comment by 2ndwonder** [comment]
> If it's disabled in Windows then it will be disabled in files. Please use the issue templates next time.

sorry, I just figured out. case can be closed. thank you anyways

**Comment by Josh-65** [comment]
You can close it yourself it next ot the comment button
