### ISSUE TITLE
Smaller Larger font size in Details view

### ISSUE THREAD

**Issue by aindriu80** [files-community/Files#7858]
### What's the Problem?

The font size is too big when viewing a folder in detail view - there is too much vertical space between folders and you can't shrink them closer - use a smaller font, also you can make them bigger

### Solution/Idea

Add a feature to increase and decrease the font size when viewing a folder.  Something like CTRL + and CTRL -

### Alternatives

using another file browser

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.2.0

### Windows Version

Leagan	Windows 11 Pro Leagan	21H2 Suiteáilte ar	‎15/‎10/‎2021 Leagan OS	22000.376 Eispéireas	Paca Eispéiris Ghné Windows 1000.22000.376.0

**Comment by yaichenbaum** [comment]
Merging with #1940
