### ISSUE TITLE
The file path bar can use input environment variables

### ISSUE THREAD

**Issue by tower-town** [files-community/Files#7861]
example：
- %homepath% ： open homepath.
- %appdata% ： open user of appdata file.

**Comment by Josh-65** [comment]
On 2.1.2.0 I can. What version of files and your OS are you on. Also you will need to upload the logs files. You can get them in files settings > about > open log folder. For future issues please use the Issue templates.

**Comment by tower-town** [comment]
> On 2.1.2.0 I can. What version of files and OS are you on? Also you will need to upload the logs files, You can get them in files settings > about > open log folder. For future issues please use the Issue templates.

thanks you,I upgrade the Files just now.Files can do it.
