### ISSUE TITLE
Bug: Can't move folder to a new empty folder in columns view

### ISSUE THREAD

**Issue by emanuelbg** [files-community/Files#7864]
### Description

Can't move folder or multiple folders to a new empty folder if that folder it's not opened with the collumn visualization it's active. I can do this if I have at least one file/folder in the new folder.

### Steps To Reproduce

1. With the column view, create a new folder.
2. Select the folder you want to put in the new folder.
3. Drag the folder above the new folder. You can't complete the action.
4. Select the new folder
5. Drag the folder above the new folder, and now works.

### Expected behavior

When a drag a folder to a new folder, it's just to move the folder to a new folder

### Files Version

Versão: 2.1.2.0 OS Version: 10.0.22000.434

### Windows Version

Windows 11 Pro 21H2 22000.434

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/3956874/150580903-5f3b8385-9273-4fb7-8781-171295207c5f.png)

**Comment by yaira2** [comment]
I was able to reproduce this in v2.4.70

**Comment by yaira2** [comment]
@emanuelbg a potential fix was added in #12898.
