### ISSUE TITLE
Black color background behide folder icon thumbnail

### ISSUE THREAD

**Issue by laspersonas** [files-community/Files#7866]
### Description

Black color background behide folder icon `thumbnail
https://imgur.com/a/B3NwNNm

### Steps To Reproduce

Black color background behide folder icon thumbnail

### Expected behavior

Black color background behide folder icon thumbnail

### Files Version

2.1.2.0

### Windows Version

10.0.22538.1010

### Relevant Assets/Logs

Black color background behide folder icon thumbnail

**Comment by gave92** [comment]
Tracked in #6373
