### ISSUE TITLE
Grouping order

### ISSUE THREAD

**Issue by Unknown-64** [files-community/Files#7868]
### What's the Problem?

When using files with group by set to "Type", every type of file is separated, like it should be. However, where each type of file is located is not controllable by the user. For example, zip folders are always on top, and there is no way to change that.

### Solution/Idea

For example, let's say I want my folders to always be on top of the list. However, zip files are always on top of the list. One way the user should be able to change it so that they could have folders appear at the top of the list is to be able to drag each section around.

### Alternatives

A different way that the user can choose where each type of file is listed.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.2.0

### Windows Version

Windows 10 Home 21H1 19043.1466

### Comments

While making this feature request, I somehow got folders to appear on top of the list, but I don't know how I did. Is a feature that would let me do the same thing as described in the feature request already in files?

**Comment by yaichenbaum** [comment]
Did you try the option to sort folders together with files?
