### ISSUE TITLE
Lags out file explorer with experimental features.

### ISSUE THREAD

**Issue by MaybeFlyZ** [files-community/Files#7869]
### Description

I turned on "make files the default explorer" or something like that it was the only experimental setting, anyways I decided to switch back to file explorer after a little while and I unchecked the setting but now file explorer runs really really slow and sometimes just freezes. Like as soon as I open it, it has to load even though all the files are there. I also noticed when right clicking on .zip files sometimes it freezes.

### Steps To Reproduce

Disable experimental settings

Right click on a .zip

### Expected behavior

File explorer to not lag.

### Files Version

v2.1.2 GitHub Version. 

### Windows Version

Windows 11 21H2 22000.434 Windows Feature Experience Pack 1000.22000.434.0

### Relevant Assets/Logs

I have no logs to share.

**Comment by gave92** [comment]
Not really aure what's up, you may try to run this script that undoes changes made by Files (make sure to save it as a ".reg" file):
https://raw.githubusercontent.com/files-community/Files/main/src/Files.Launcher/Assets/FilesOpenDialog/UnsetFilesAsDefault.reg

**Comment by yaichenbaum** [comment]
@MaybeFlyZ is this still an issue after restarting?

**Comment by yaira2** [comment]
We're excited to share that startup performance will be significantly improved in the upcoming release of version 3. You can download the preview version from our website https://files.community/download.
