### ISSUE TITLE
Can't open files at all

### ISSUE THREAD

**Issue by flamesred** [files-community/Files#7872]
### Description

when I downloaded files, and installed it, it closed the default files app, when I click the default app again I can't open  default files, files at all. as it is now tied to the app, now the old shortcut for the default icon doesn't work, I can get around this by using apps that can open default file explorer, but only be allowed to send stuff, not use or open files as a separate app.

### Steps To Reproduce

/files-main/src/Files.launcher/Assets/SetFilesAsDefault
then letting that last one to do as it does, causing my situation

### Expected behavior

I expected for the files app to be open, now I'm locked out of using file explorer properly.

### Files Version

I just downloaded the code

### Windows Version

windows 21H2

### Relevant Assets/Logs

I can access my files to put anything here.

**Comment by gave92** [comment]
It's not very clear what the problem is but if you can't open windows files explorer try to run this script (make sure to save it as a ".reg" file):
https://raw.githubusercontent.com/files-community/Files/main/src/Files.Launcher/Assets/FilesOpenDialog/UnsetFilesAsDefault.reg
