### ISSUE TITLE
Android phone issue

### ISSUE THREAD

**Issue by hooddy** [files-community/Files#7873]
### Description

Works so slow with Android Phone. Its hard to describe whole proccess issue.

### Expected behavior

Copy-past files/fodlers from C to Phone. In comparing with default Explorer it's realy slow. As well as some operations work strande (create folder for i.e. its doesnt show created folder so I need to leave current folder and enter it again to see it. The same wth delete folders its takes foever to delete it so Files just freeze and freeze Explorer til I remove Phone from PC etc).

### Files Version

2.1.2.0

### Windows Version

Windows 11 21H2 22000.438

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7917873/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7917874/debug_fulltrust.log)

**Comment by Josh-65** [comment]
Merging with #9003
