### ISSUE TITLE
Implimentation of a graph of file sizes

### ISSUE THREAD

**Issue by Atrello** [files-community/Files#7874]
### Solution/Idea

Basically a visual graph or ordering method that shows file sizes for absolutely everything.

Makes things a lot easier to find and saves lots of time when finding large files to clear space.

### Alternatives

I've tried a few programs that do this job.

TreeSize
WinDirStat
SpaceMonger (from stardock)

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Addition of a visual graph/indicator to represent and compare file sizes in a select directory | Could |

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
Feature request is approved but we still need finalize a design.

**Comment by yaira2** [comment]
@Atrello is this something that should be in the properties window?

**Comment by yaira2** [comment]
Merging with #6091
