### ISSUE TITLE
add the old toolbar 

### ISSUE THREAD

**Issue by ThemisterNaim** [files-community/Files#7875]
### What's the Problem?

the windows 11 toolbar is too simple

### Solution/Idea

I think that would be nice if you make an option to select witch toolbar use: the windows 11 toolbar or windows 10 toolbar, thanks!

### Alternatives

(i have nothing else to say)

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
@ThemisterNaim we're constantly improving the toolbar and adding more options, please let us know if there is a specific action that you're looking for.
