### ISSUE TITLE
Copying/moving files doesn't work

### ISSUE THREAD

**Issue by remco59** [files-community/Files#7876]
### Description

Sometimes when dragging one or multiple files over to another folder to move or copy them, the activity box says that the files have been copied or moved, but the files aren't actually there.

### Steps To Reproduce

1. Open 2 windows of the files app
2. Select one or multiple files/folders
3. Drag the selected files/folders to another folder in the second window of the files app
4. Click the activity button to see that the files have been copied
5. Check the destination folder to see that the files are not there

### Expected behavior

The files and folders should have been moved or copied.
If for whatever reason they can't be moved or copied there should be an error message, and the activity tab should not say the task is completed.

### Files Version

2.1.2.0

### Windows Version

Editie	Windows 11 Home Versie	21H2 Installatiedatum	‎17-‎12-‎2021 Build van besturingssysteem	22000.434 Serienummer	R90YKX11 Ervaring	Windows Feature Experience Pack 1000.22000.434.0

### Relevant Assets/Logs

n/a

**Comment by CyclingLand** [comment]
Something to note with this issue is that it can be resolved when quitting files through the task manager.
The bug also doesn't always appear.

I do work a lot with cloud storage, that might be relevant.

**Comment by Unknown-64** [comment]
When this happens, does it also happen in the normal windows explorer? Sometimes I try to move files and it is frozen in both windows explorer and files.

**Comment by CyclingLand** [comment]
> When this happens, does it also happen in the normal windows explorer? Sometimes I try to move files and it is frozen in both windows explorer and files.

No, for me it still works in the windows file explorer when this happens

**Comment by tasnimahmedtusar** [comment]
yes same issue. cut/copy/paste works inside the Files but if i try to cut it from desktop to any specific folder it does not work (if i try copy, it works)

**Comment by MintHawk** [comment]
Sometimes cut/paste works, sometimes not.
It's the only thing preventing me from using Files full time...

**Comment by Josh-65** [comment]
Forpeople who have thsi issue can you upload the logs files directly to github. You can get them in files settings > about > open log folder.
