### ISSUE TITLE
No way to install your app

### ISSUE THREAD

**Issue by ImoutoChan** [files-community/Files#7877]
### Description

Please provide the usual executable installer so that people can download and install your app without any troubles. Right now your way of installation is a mess.

1. Microsoft store isn't working
![image](https://user-images.githubusercontent.com/14975965/150638262-28bef241-c9b3-407f-ab25-fcba759a358f.png)

Sometimes it loads and then throw some Authentication errors

2. winget is broken
```
PS C:\Users\Username> winget install -e Files-Community.Files
The `msstore` source requires that you view the following agreements before using.
Terms of Transaction: https://aka.ms/microsoft-store-terms-of-transaction
The source requires the current machine's geographic region to be sent to function properly.

Do you agree to all the source agreements terms?
[Y] Yes  [N] No: Y
No package found matching input criteria.
```
3. sideload requires some insane actions
![image](https://user-images.githubusercontent.com/14975965/150638119-782dbaa7-2d77-41c1-b5b2-544490c6e4f1.png)

### Expected behavior

Release page on this project with the installer or at least zip folder with this program.

### Files Version

latest

### Windows Version

Windows 10 Pro N 21H1 19043.1110

### Relevant Assets/Logs

there are no logs

**Comment by BusteanHAN** [comment]
Bro there is a zip file with the installer in the latest release
https://github.com/files-community/Files/releases/download/v2.1.2/Files.Package_2.1.2.0.zip
