### ISSUE TITLE
Bundles disappearing

### ISSUE THREAD

**Issue by widkit** [files-community/Files#7878]
### Description

Bundles disappear after some time.
Have no idea what could've caused it.
bundles.json's output returns null.
```
{
  "SavedBundles": null
}
```

### Steps To Reproduce

Create a bundle
Wait a couple of days
Your bundle is gone

### Expected behavior

Bundles wouldn't disappear

### Files Version

Version: 2.1.2.0 OS Version: 10.0.22000.434

### Windows Version

Windows 11 Home 21H2  22000.434

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/75989700/150638968-4510c206-1449-478b-b42c-9bd70b9731b0.png)

**Comment by gave92** [comment]
Merging with #7743

**Comment by StLa1** [comment]
It happened to me after updating to 2.1

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
While this feature is still in the app, we're planning to replace it with a tags widget.
