### ISSUE TITLE
Add the ablity to mount disc image files

### ISSUE THREAD

**Issue by Advik-B** [files-community/Files#7880]
### What's the Problem?

# When you double click on a disc image file, the following happens:

## Windows Explorer
will mount the file and display it as a drive

## Files
nothing happens 

### Solution/Idea

Add the ablity to mount disc image files, or ... at least use windows explorer to mount it, then show it as a drive

### Alternatives

hard-code it yourself, or use [this library](https://github.com/DiscUtils/DiscUtils)

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.1.2.0
OS Version: 10.0.22000.434

### Windows Version

Windows 11 Pro 22000.434

#### Windows Specs:
```
Edition	Windows 11 Pro
Version	21H2
Installed on	‎09-‎12-‎2021
OS build	22000.434
Experience	Windows Feature Experience Pack 1000.22000.434.0
```
#### Device Specs:
```
Device name	Trivvv
Processor	Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz   3.00 GHz
Installed RAM	8.00 GB
Device ID	94635F54-E20A-4659-9DD3-C11F86B428C7
Product ID	00331-10000-00001-AA267
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

```

**Comment by gave92** [comment]
Are we talking about ".ISO" files?

**Comment by Advik-B** [comment]
yes

**Comment by Advik-B** [comment]
Also **TRY** to add support for [The following file extensions](https://fileinfo.com/filetypes/disk_image)

**Comment by gave92** [comment]
Iso images open fine in Files for me, so bug.

**Comment by Advik-B** [comment]
[debug_fulltrust.log](https://github.com/files-community/Files/files/7920090/debug_fulltrust.log)

**Comment by Advik-B** [comment]
[debug.log](https://github.com/files-community/Files/files/7920102/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7920103/debug_fulltrust.log)

**Comment by Advik-B** [comment]
Yea.... the log files are not showing anything

**Comment by Advik-B** [comment]
So... this is a bug **AND** a feature request?

**Comment by Advik-B** [comment]
I found a lot of helpful links [here](https://duckduckgo.com/?t=ffab&q=mount+disc+image+files+in+C%23&ia=web)

**Comment by gave92** [comment]
@Advik-B could you check what happens if you right-click an ISO file and choose "Mount" instead of double-clicking it?

**Comment by Advik-B** [comment]
No it does not work

**Comment by gave92** [comment]
What happens instead? You don't have a mount option? You get a request for administrator but the iso is not mounted?

**Comment by Advik-B** [comment]
Yes, also I don’t need admin to mount drive in windows explorer Sent from Mail for Windows From: Marco GavelliSent: 25 January 2022 13:32To: files-community/FilesCc: Advik; MentionSubject: Re: [files-community/Files] Add the ablity to mount disc image files (Issue #7880) What happens instead? You don't have a mount option? You get a request for administrator but the iso is not mounted?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by Josh-65** [comment]
You wouldn't need to extract it to view it would just act like a folder.

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
> Would there be any point to mounting it as a drive when #8232 is implemented?

@Josh-65 #8232 might not come with support for viewing iso files. We can keep this open for now but we haven't been able to reproduce the issue on our end.
