### ISSUE TITLE
7zip

### ISSUE THREAD

**Issue by dano227** [files-community/Files#7883]
### What's the Problem?

When I want to unzip something and close the Files app it won't load in the Background.

### Solution/Idea

Files could load in the Background so it can still unzip with 7zip.

### Alternatives

/

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1

### Windows Version

Win 10

**Comment by yaichenbaum** [comment]
@dano227 can you reopen this as a bug report and include steps to reproduce the issue?
