### ISSUE TITLE
Report and a few requests.

### ISSUE THREAD

**Issue by SaccoSVD** [files-community/Files#7885]
### Solution/Idea

N/A

### Alternatives

N/A

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.2

### Windows Version

Win11

### Comments

I'm loving Files quite a lot. I like how it works in general and how snappy it feels. So far so good. Gonna be reporting issues from now on.

Here are a couple requests, I hope you don't mind :)

1) "List" layout equivalent. "Details" is useful on specific situations but I mainly use "List". I deal quite often with large amount of audio sample files and "List" is quite an important layout.

2) Ability to rename Favorite locations: I often have folders of the same name in different drives and I normally rename them in Explorer. For instance "GameTitle - ProductionFolder", "GameTitle - UnityFolder" things like that.

3) Seems like properties->customize lacks the ability to select "general items" / "Audio", "Pictures" etc...

4) Ability to determine and display the "most used folders" perhaps?

**Comment by yaichenbaum** [comment]
@SaccoSVD thank you for the requests, I'm going to close this issue since there are several similar requests on the todo list.
