### ISSUE TITLE
New Icon

### ISSUE THREAD

**Issue by Pujadinny** [files-community/Files#7886]
### What's the Problem?

I think is not a problem 

### Solution/Idea

I wish you will can change the icon file for what ever you wanna put there i think

### Alternatives

You can change the icon .png to .ico or whatever you wanna show in the explorer icon 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Windows Version

Win11

### Comments

For me its fine the app but i wanna change the icon XD

**Comment by yaichenbaum** [comment]
@Pujadinny did you try changing the icon from the properties dialog?

**Comment by Pujadinny** [comment]
Yes i try it to click on propieties but i can 't do nothing

**Comment by yaichenbaum** [comment]
> Yes i try it to click on propieties but i can 't do nothing

Can you open a new bug report and include the log files?
