### ISSUE TITLE
Invoke a third-party replication engine

### ISSUE THREAD

**Issue by sunshineharry** [files-community/Files#7887]
### What's the Problem?

The original copy method is too slow! Especially in the world of cut folders. I hope it can invoke a third-party replication engine, like `TeraCopy` and `FastCopy`.

### Solution/Idea

invoke a third-party replication engine, like `TeraCopy` and `FastCopy`

### Alternatives

I donnt know.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
We don't have plans to add support for third party copy engines, however, there are a number of issues regarding improving the built in search feature.
