### ISSUE TITLE
Using Listary's quick switch feature for Files

### ISSUE THREAD

**Issue by KevinABK** [files-community/Files#7888]
### What's the Problem?

Currently, I am able to use Listary to launch Files, however the one thing I am sorely missing would be the "Quick Switch" function from Listary. The function allows quick switching of the page from any currently opened folder when doing"save as", " open files" function.

### Solution/Idea

No solution, just a request or if theres a way to make it work, I would like to know.

### Alternatives

N/A

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

V2.1.2

### Windows Version

windows 10 21h2

**Comment by yaichenbaum** [comment]
Merging with #6314

**Comment by yaira2** [comment]
Support for Listary is actively being worked on in #15069.
