### ISSUE TITLE
Startup settings - Open in dual pane view

### ISSUE THREAD

**Issue by cbsims** [files-community/Files#7889]
### Solution/Idea

Enable dual pane view under startup settings with individual page for each pane at startup

### Alternatives

Open dual pane view at startup settings

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by Josh-65** [comment]
Theres isnt any infomation on your issue if it still a probelrm then plase open an new one.
