### ISSUE TITLE
Global option for setting layout

### ISSUE THREAD

**Issue by AnupNair08** [files-community/Files#7890]
### What's the Problem?

Currently, you have to individually go to folders and set layouts. What could be better is to allow an option to change the layout of all the folders globally. 

### Solution/Idea

Provide an option in the setting to select a default layout that applies to folders. Within each folder keep the current layout system that allows users to change the layout for specific folders

### Alternatives

None

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.2.0

### Windows Version

Windows 11 21H2 Build 22000.466

**Comment by gave92** [comment]
Merging with #4155.
You can already set a global layout mode bu turning off "enable individual preferences for folders" option.
