### ISSUE TITLE
Malfunción en Biblioteca

### ISSUE THREAD

**Issue by Tximistargi** [files-community/Files#7893]
### Description

La aplicación muestra problemas con la visualización de la Biblioteca. Tengo una Biblioteca con elementos añadidos correctamente desde el File Explorer, y después de reiniciar NO se muestra al hacer click en ella.

### Expected behavior

La Biblioteca debería expandirse correctamente al hacer click en ella.

### Files Version

2.1.2.0

### Windows Version

Windows 10 Pro Workstation

### Relevant Assets/Logs

![Screenshot_1](https://user-images.githubusercontent.com/98258784/150674880-dfc23d5a-7645-42e7-a693-6779bed1cced.jpg)

**Comment by yaichenbaum** [comment]
@Tximistargi is this still an issue in the preview version? https://files.community/download/preview
