### ISSUE TITLE
Right-clicking specific items crashes Files (LayoutCycle)

### ISSUE THREAD

**Issue by StLa1** [files-community/Files#7894]
### Description

When I right click some specific items, Files consistently crashes. 
The right-click pop-up shows, but 1-2 seconds later Files crashes.

So far this happened only with folders, but I can't confirm the issue is specific to folders.
This happens with folders nested in other ones, pinned in the Favorites, or pinned in Bundles. Not necessarily all 3 together.

### Steps To Reproduce

I couldn't find a common characteristic to the folders causing the crash. Therefore can't give steps.

### Expected behavior

Files does not crash.

### Files Version

2.1.2.0

### Windows Version

22000.466

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7920324/debug.log)

```
2022-01-23 12:09:04.1546|ERROR|AppUnhandledException|Layout cycle detected.  Layout could not complete.
Layout cycle detected.  Layout could not complete.
	Windows.UI.Xaml.LayoutCycleException: Layout cycle detected.  Layout could not complete.
Layout cycle detected.  Layout could not complete.
```

**Comment by tasnimahmedtusar** [comment]
yes anywhere it happens. extreme annoying bug for this beatutiful Files. I am looking for fix too

**Comment by yaichenbaum** [comment]
@StLa1 is this still an issue in the preview version? https://files.community/download/preview

**Comment by gave92** [comment]
Error still appearing on Appcenter:
![image](https://user-images.githubusercontent.com/9673091/168338905-47254a0a-7d55-47cc-86a4-f627dc96cbeb.png)

**Comment by yaichenbaum** [comment]
> Error still appearing on Appcenter:
> 
> ![image](https://user-images.githubusercontent.com/9673091/168338905-47254a0a-7d55-47cc-86a4-f627dc96cbeb.png)

Do we know this is from the right click context menu?

**Comment by gave92** [comment]
Indeed we don't know. Same error was reported in: #9019, #642, #5666

**Comment by yaichenbaum** [comment]
> Indeed we don't know. Same error was reported in: #9019, #642, #5666 but in different circumstances.

A number of these are issues with WinUI itself so there might not be much we can do.

@chingucoding do you have any ideas?

**Comment by gave92** [comment]
For #5666 and #7894 it could be due to us messing with the context menu height but not certain.

**Comment by gave92** [comment]
Just reproduced crash on preview by invoking 3 times the "empty space" context menu.

**Comment by chingucoding** [comment]
If it repros consistently, this might be interesting to debug. I know that Itemsrepeater can rarely exhibit layout cycles and there isn't much we could do in that case (which probably doesn't apply here)

**Comment by gave92** [comment]
We could check if we're responsible for this by removing the code that fixes the menu height:
```cs
var openedPopups = Windows.UI.Xaml.Media.VisualTreeHelper.GetOpenPopups(Window.Current);
var secondaryMenu = openedPopups.FirstOrDefault(popup => popup.Name == "OverflowPopup");
var itemsControl = secondaryMenu?.Child.FindDescendant<ItemsControl>();
if (itemsControl is not null)
{
    ...
    if (requiredHeight > availableHeight)
    {
        itemsControl.MaxHeight = Math.Min(Constants.UI.ContextMenuMaxHeight, Math.Max(itemsControl.ActualHeight, Math.Min(availableHeight, requiredHeight))); // Set menu max height to current height (avoids menu repositioning)
    }

    mainItems.OfType<FrameworkElement>().ForEach(x => x.MaxWidth = itemsControl.ActualWidth - Constants.UI.ContextMenuLabelMargin); // Set items max width to current menu width (#5555)
}
```

**Comment by gave92** [comment]
I have windows 10, but this report is about windows 11. So no, I guess this happens regardless of win ver.

**Comment by yaichenbaum** [comment]
I think it's in the first release of Windows 11 as well but I haven't been able to reproduce the issue in the preview versions of Windows.

**Comment by yaichenbaum** [comment]
> Oh it's quite consistent. We could check if we're responsible for this by removing the code that forces the menu height and items width:

@gave92 would additional logic to make sure the height is a full number (eg. 200 instead of 199.45555) help? I'm wondering if the rendering engine is trying to round the number causing the size change event to keep being hit.

**Comment by yaichenbaum** [comment]
Is this still an issue in the latest preview build? https://files.community/download/preview

**Comment by yaichenbaum** [comment]
I can confirm this is resolved
