### ISSUE TITLE
Switching to dual pane view updates sidebar location but doesn't receive focus

### ISSUE THREAD

**Issue by Korkman** [files-community/Files#7896]
### Description

When opening a new pane (switching to dual pane view), the side panel location is updated in sync with the newly opened pane but the focus is still kept on the original pane. It would be nice to focus the new pane immediately so that clicking on a new location in the side panel changes the location of the new pane, which is suggested by the location update. What happens is that the original pane location is changed.

### Steps To Reproduce

1. Three-dot-menu
2. New pane
3. See location updated in side panel
4. Change location in side panel
5. Original pane changes location

### Expected behavior

New pane changes location

### Files Version

2.1.2.0

### Windows Version

Windows 10 Pro 21H2

### Relevant Assets/Logs

This space intentionally left blank

**Comment by apollofps** [comment]
HI im new to opensource so can i take it as my first issue?

**Comment by yaichenbaum** [comment]
@apollofps I missed your request but otherwise the answer would have been yes. This issue was just resolved in #9144. Would you like to take on a different issue?
