### ISSUE TITLE
[CRITICAL] Files Crashes When Renaming Files in Documents Folder

### ISSUE THREAD

**Issue by Gryzle** [files-community/Files#7897]
### Description

When attempting to rename a file specifically in the Documents Folder, Files crashes. There are no special permissions within the Documents library, or on any of the folders I have attempted to rename. I renamed a file in Downloads, and it worked just fine.

### Steps To Reproduce

1. Open Files
2. Navigate to Documents
3. Rename an existing folder

### Expected behavior

Files should not crash when renaming a file in Documents.

### Files Version

Version: 2.1.3.0 OS Version: 10.0.22000.438

### Windows Version

Windows 11 22000.438

### Relevant Assets/Logs

There are no relevant issues/logs. This issue persists throughout complete restarts of the Files application.

**Comment by Gryzle** [comment]
This bug appears to only effect the Documents folder, I tested it in every other library.

**Comment by yaichenbaum** [comment]
Are you using the tiles layout?

**Comment by gave92** [comment]
Is the library grouped? If so, could you try without grouping?

**Comment by d2dyno1** [comment]
@Gryzle #7900 May fix this issue

**Comment by Gryzle** [comment]
> Are you using the tiles layout?

I am, and since it was the only directory that I was using it in at the time, I misidentified the issue. The title should be "Renaming with the "Tiles" View causes Files to Crash."

**Comment by StLa1** [comment]
> > Are you using the tiles layout?
> 
> I am, and since it was the only directory that I was using it in at the time, I misidentified the issue. The title should be "Renaming with the "Tiles" View causes Files to Crash."

You can rename your issue

**Comment by gave92** [comment]
@yair100 why did you think of tiles layout? Is there a known issue with it?

**Comment by yair100** [comment]
> @yair100 why did you think of tiles layout? Is there a known issue with it?

I noticed the issue in the tiles layout myself while working on the visual tree pull request.

**Comment by yaichenbaum** [comment]
Merging with #7996
