### ISSUE TITLE
Add a need triage or review to new issues

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#7898]
### What's the Problem?

Ive seen many issue be seeming ignored by moderators. I presume this isn't intentinal and simply get missed. Adding the needs review label to new issues would proberly help with this as its just going down a list rather then scrolling through many issues.

### Solution/Idea

Add the need-review label to new issues.

### Alternatives

*

**Comment by yaichenbaum** [comment]
@Josh-65 we simply don't have enough time to go through all the issues but we're doing our best. Personally I take a couple hours every now and then to go through all the issues and to take care of the ones we previously missed.

**Comment by Josh-65** [comment]
I do get that but i think it would be easer for you and others to go through them if there was a tag that could make it a list
