### ISSUE TITLE
Compact format for files list

### ISSUE THREAD

**Issue by tsvetnoff** [files-community/Files#7899]
### What's the Problem?

Files list is too fat for large folders for now.

### Solution/Idea

It would be good to add a compact format of files list identical to the standard Windows 11. This contributes to a smoother transition from the standard Explorer to Files.

### Alternatives

An alternative is to make a slider that would set the height of the rows.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.1.2.0

### Windows Version

Windows 11 21H2 22000.434

**Comment by yaichenbaum** [comment]
Merging with #1940
