### ISSUE TITLE
Make the home sections movable

### ISSUE THREAD

**Issue by ohidurbappy** [files-community/Files#7903]
### What's the Problem?

These sections are not rearrangeable.

![image](https://user-images.githubusercontent.com/22405409/150693488-d685654e-6578-4916-bd9f-e14c1a06d1d0.png)

### Solution/Idea

Add feature to be able to rearrange the section by the end-user as per their convenience.

### Alternatives

I haven't looked for any alternative.

### Files Version

2.1.2.0

### Windows Version

Windows 11 21H2 22000.434

**Comment by yaichenbaum** [comment]
We don't have plans for this option.
