### ISSUE TITLE
Other apps still don't consider Files as default file manager

### ISSUE THREAD

**Issue by OpenSource03** [files-community/Files#7904]
Hello!

Apps like PHPStorm, IntelliJ, or basically any other app that has an option like "reveal in file explorer" still open up the old file explorer instead of Files, even with the experimental feature enabled.

**Comment by yaichenbaum** [comment]
@OpenSource03 thank you for opening this issue. We need a little more information from you in order to investigate this issue, please reopen this issue once you have filled out the issue template.
