### ISSUE TITLE
Date format doesn't match Windows date format.

### ISSUE THREAD

**Issue by HTD** [files-community/Files#7907]
### Description

I have my display language set to English, but my date format set to Polish.
The application ignores the date format set in Windows and uses mm/dd/yyyy instead of dd.mm.yyyy I see in Windows Explorer.

### Steps To Reproduce

1. Set Windows display language to English.
2. Set date format to Polish.
3. Check the dates in Files when the "System" format is used.

### Expected behavior

The dates should look exactly like in Windows Explorer, the system date format should be used.
System display language, keyboard layout, region (physical location used for maps), date, time and number format are SEPARATE settings. Date format should not be derived from display language, but read directly from the system setting.

### Files Version

Version 2.1.2.0

### Windows Version

Windows 11 22538.1010

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/263558/150703181-bd6716da-b812-4a84-9351-945e4ff17488.png)

**Comment by yaichenbaum** [comment]
@HTD what did you set the time format to in Files?

**Comment by HTD** [comment]
It's set to System. I've checked the documentation and I'm totally confused: in documentation System is in fact English, I have no idea why it's called "System". It's not an international standard, even SQL doesn't use it as default, ISO8601 IS a standard. It's a very weird choice, since the actual Windows system has a culture dependent time format that is selectable by the user and available to any Windows application via Windows API. As the Files is able to follow the Windows color scheme, it also should follow Windows date / time / numbers settings.

**Comment by yaichenbaum** [comment]
@HTD what is your system region set to?
![image](https://user-images.githubusercontent.com/39923744/150890187-a95f3df9-9056-480c-8927-76b7e2265166.png)

**Comment by jyrijh** [comment]
Same here, I have System.Globalization.CultureInfo.CurrentCulture "fi-FI" and dates are incorrect.
Then I just  forced in App Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("fi-FI");
and datetime format was correct.

But definately if setting tell System, then app should should ask the System.Globalization.CultureInfo.CurrentCulture and use that

**Comment by Josh-65** [comment]
Is this still an issue?

**Comment by HTD** [comment]
Still an issue in version 2.1.15.0, recent from Windows Store.

**Comment by Josh-65** [comment]
Its not an issue for me if you set the date format in the above screenshot to system. It then follows windows settings.
