### ISSUE TITLE
Sending Files to Devices

### ISSUE THREAD

**Issue by Mneyuu** [files-community/Files#7908]
### What's the Problem?

First off, thank you for making Files! I found it shortly after upgrading to Windows 11 back in October and loved it. The recent update brought compatibility settings, which I really needed to really daily drive Files. All that said, I recently found something missing that I'd like to request.

Would it be possible to add the ability to send files to other devices? For example, sending an MP3 to your phone (either via USB or Bluetooth). I tried to do this yesterday, only to find that I had to revert back to file explorer to do it.
![explorer_NQa2ppUMyC](https://user-images.githubusercontent.com/97762952/150705159-5baf629e-a6aa-4780-9014-ef8db363bd0f.png)

### Solution/Idea

N/A

### Alternatives

Simply using the standard file explorer.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.2.0

### Windows Version

Windows 11 21H2 22000.434

### Comments

Really enjoying the experience with Files. I look forward to future updates! Also, not quite sure how the "Priorities" list is meant to be made. It's not quite clear.

**Comment by yaichenbaum** [comment]
Merging with #7789
