### ISSUE TITLE
Font Scaling / Text cut off

### ISSUE THREAD

**Issue by Chaython** [files-community/Files#7910]
### Description

![image](https://user-images.githubusercontent.com/6486343/150719415-3bf64f6a-7206-4933-b91f-30344624374f.png)
I believe this is related to changing font size in windows scaling settings. "Accessibility > Text Size"

### Expected behavior

Elements should stretch to fit the text.

### Files Version

2.1.2.0

### Windows Version

10.0.22000.438

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7922497/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7922498/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
@Chaython which scaling and font size are you using?
