### ISSUE TITLE
Search Improvement

### ISSUE THREAD

**Issue by saaiful** [files-community/Files#7912]
### What's the Problem?

Windows search sucks it's slow and useless.

### Solution/Idea

You can include Everyting in Files search, Everyting has SDK for intregration. 
https://www.voidtools.com/support/everything/sdk/

### Alternatives

https://www.voidtools.com/downloads/

### Files Version

2.0.36.0

### Windows Version

Edition	Windows 10 Pro Version	21H1 Installed on	‎2/‎21/‎2021 OS build	19043.1466 Experience	Windows Feature Experience Pack 120.2212.3920.0

**Comment by yaichenbaum** [comment]
Merging with #2447
