### ISSUE TITLE
Default File Manager: Steam, Recycle bin

### ISSUE THREAD

**Issue by Chaython** [files-community/Files#7913]
### Description

Going to a Steam app, properties, local files, browse... does not open files and open the related directory. Only opens a home tab in files.
![image](https://user-images.githubusercontent.com/6486343/150736309-9bb61d54-75b5-4143-8593-6c1e707cc89f.png)
Recycle bin shortcut: Shows it has files, clicking it opens files but not the recycle bin dir, when manually going to recycle bin, the dir is empty.

### Expected behavior

Open the related directories.

### Files Version

2.1.2.0

### Windows Version

10.0.22000.438

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7923330/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7923331/debug_fulltrust.log)

**Comment by Crwmy** [comment]
@Chaython Was curious and in my test, Files opened the related directory. 

Just out of curiosity: Have you tried the "Repair" option in the advanced options of Files in Apps and Features? I have had an issue with icon display after updating to 2.1.0 and this solved it for me without loosing my settings.

**Comment by Chaython** [comment]
I ran repair.
![image](https://user-images.githubusercontent.com/6486343/150754430-a1794872-9c9c-40ed-a54c-6112b733d5a1.png)
Issue persists: 
https://user-images.githubusercontent.com/6486343/150755442-64c19a64-f052-4b94-84c3-32212631acc8.mp4

**Comment by yaichenbaum** [comment]
@Chaython is this still an issue in the preview version? https://files.community/download/preview
