### ISSUE TITLE
Can't type on New File Popup 

### ISSUE THREAD

**Issue by kakalpa** [files-community/Files#7914]
### Description

Can't type file name when creating a new file on the Popup "enter new item name" non of the keystrokes seems to work 

### Steps To Reproduce

Go to New 
File 
Try entering a name for the file in the pop-up 

### Expected behavior

To Create a new file 

### Files Version

Version: 2.1.2.0 

### Windows Version

Processor	Intel(R) Xeon(R) E-2224G CPU @ 3.50GHz   3.50 GHz Installed RAM	16.0 GB (15.8 GB usable) Device ID	1DA4A583-EEB8-41CD-969D-8396D08E82C3 Product ID	00331-10000-00001-AA992 System type	64-bit operating system, x64-based processor Pen and touch	No pen or touch input is available for this display

### Relevant Assets/Logs

-
[debug.log](https://github.com/files-community/Files/files/7925193/debug.log)
-

**Comment by yaichenbaum** [comment]
@kakalpa is this still an issue in the preview version? https://files.community/download/preview
