### ISSUE TITLE
Slow open

### ISSUE THREAD

**Issue by Seuguhfr** [files-community/Files#7916]
### What's the Problem?

File is very slow to open when closed (unlike default windows explorer)

### Solution/Idea

Open File in background when the computer start.

### Alternatives

Leave File open in the background when it has been closed

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version : 2.1.2.0

### Windows Version

OS Version: 10.0.19042.1466

**Comment by yaichenbaum** [comment]
@Seuguhfr you can set Files to open on startup from the startup settings in the preferences page.

**Comment by Seuguhfr** [comment]
> 

Thank you for your answer, but my issue is for open in background. Else, when I close File, he's slow to open. my request is for leave File open in background.

**Comment by yaichenbaum** [comment]
This a unfortunately a limit of the UWP platform and I'm not aware of any solutions for this.

**Comment by yaira2** [comment]
We're excited to share that startup performance will be significantly improved in the upcoming release of version 3. You can download the preview version from our website https://files.community/download.
