### ISSUE TITLE
Resizing preview pane

### ISSUE THREAD

**Issue by mhoude1966** [files-community/Files#7917]
### Description

Cannot resize the preview pane to make it bigger even if we narrow all the columns.

### Steps To Reproduce

1. Try to resize the preview pane to make it bigger.

### Expected behavior

Just like the old Explorer.exe does

### Files Version

2.1.2.0

### Windows Version

Windows 10 21H2

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7926831/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7926832/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
Thank you for your feedback, merging with #6628
