### ISSUE TITLE
Crashed after moving tab

### ISSUE THREAD

**Issue by antpowell** [files-community/Files#7919]
### Description

Click + held tab, moved it outside of window my mistake and back into its position.   

### Steps To Reproduce

1. Navigate to a folder in first tab
2. Open another file from "Reveal in File Expolorer" right click option (ensuring Files is set as default), should open second tab
3. Click and drag first tab around and drop it back into its original place

### Expected behavior

I would expect it to File to operate as if I didn't click drag anything since the tab was placed on it's original position or to focus that tab. 

### Files Version

Version: 2.1.2.0 OS Version: 10.0.22000.318

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎11/‎16/‎2021 OS build	22000.318 Experience	Windows Feature Experience Pack 1000.22000.376.0

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/10569986/150824543-d99dec34-1d55-4b9e-b564-c6239a55ede4.png)

**Comment by gave92** [comment]
Merging with #7838
