### ISSUE TITLE
Quick look focus is moved to the Files app

### ISSUE THREAD

**Issue by ChelaruCatalin** [files-community/Files#792]
Preview a image with "space" will open the quick preview app but the focus will be on Files app. This will make the use of "Esc" key to turn off QuickLook impossible. 

To be able to use the "Esc" key one left click on the QuickLook window is required. 

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.5.0]

**Comment by lampenlampen** [comment]
You can press spacebar again to turn off quicklook.

**Comment by okayada92** [comment]
This seems a little redundant

**Comment by okayada92** [comment]
Am I done yet

**Comment by yaichenbaum** [comment]
We're working on a built-in preview feature and don't have plans to continue working on QuickLook support.
