### ISSUE TITLE
Colour labels don't "stick" to files

### ISSUE THREAD

**Issue by xx88xx** [files-community/Files#7921]
### Description

experimental labels don't apply permanently  to files.

### Steps To Reproduce

1) apply label to file
2) navigate to new folder
3) navigate back to previous folder
4) label is gone

### Expected behavior

label applies permanently to file

### Files Version

2.1.2

### Windows Version

Windows 11 22000.466 21H2

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7927749/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7927752/debug_fulltrust.log)

**Comment by gave92** [comment]
Where are the files you're trying to tag? In a local drive? In a network drive?

**Comment by xx88xx** [comment]
ah yes I've just retested it. It works on a local drive, but not with network drives. Are a lot of my stability issues due to the fact I'm primarily running a network drive?

**Comment by yaichenbaum** [comment]
@xx88xx very likely, we currently use a different set of APIs for network drives.

**Comment by AntonyCilleros** [comment]
I have the same issue except that this happen even on local drive but not all the folders are affected
I am on VM

Here are all the labels that stays after refreshing the window
![image](https://user-images.githubusercontent.com/77164002/163655893-2d0f7622-ed37-4ea7-8a78-dc69219a562c.png)

**Comment by gave92** [comment]
You need to have write permissions to the folder to be able to tag it.

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.0.0?
