### ISSUE TITLE
Open New tab by duplicate current tab not open the default Home Directory

### ISSUE THREAD

**Issue by MaxSteven** [files-community/Files#7923]
### What's the Problem?

Right now Files open new tabs by go to Home folder

### Solution/Idea

It will be great to have an option in preference that allow it by default open new tabs by duplicating current tab instead.
And maybe another option in preference to allow user choose where is the default folder.

### Alternatives

Or Ctrl + T = Open new tab to default home folder
Ctr + D = Duplicate current tab

### Priorities

| This proposal will allow end users to quickly open folder instead of going back to default folder since Files quite laggy with big folders | Should |

### Files Version

Version: 2.1.2.0

### Windows Version

Windows 10.0.19044.1466

**Comment by yaichenbaum** [comment]
#7901 added a shortcut to duplicate tabs.
