### ISSUE TITLE
ADD LIST VIEW LIKE WINDOWS FILE EXPLORER IN LAYOUT MENU 

### ISSUE THREAD

**Issue by nicholateslaisme** [files-community/Files#7924]
### What's the Problem?

WINDOWS FILE EXPLORER HAS LIST VIEW WHICH IS COMPACT, TIDY AND DO NOT SHOW THUMBNAIL IN THIS VIEW.
JUST THE FILE ICON ALONG WITH FILE NAME. 

FOR EXAMPLE IT DOS NOT  SHOW VIDEO THUMBNAILS IN THIS VIEW

### Solution/Idea

WINDOWS FILE EXPLORER HAS LIST VIEW 

### Alternatives

WINDOWS FILE EXPLORER

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.2.0

### Comments

![fILES-REQUEST](https://user-images.githubusercontent.com/98349504/150845672-b5246617-6230-4432-8791-0a6e7883e142.jpg)

**Comment by yaichenbaum** [comment]
Merging with #2509

**Comment by yaira2** [comment]
@nicholateslaisme thank you for your patience, I'm excited to share that a List View layout will be included in the next release.
