### ISSUE TITLE
 QL-Win / QuickLook NOT WORKING

### ISSUE THREAD

**Issue by nicholateslaisme** [files-community/Files#7925]
### What's the Problem?

QuickLook is a file viewer, it plays video for video file, opens image in image viewer if its a image, opens pdf file. 
All without opening separate application from the file explorer.

Its a very handy tool to preview media files , just like Mac

### Solution/Idea

Pls implement support for QuickView

https://github.com/QL-Win/QuickLook/releases/tag/3.7.1

### Alternatives

windows File explorer, its still the go to file explorer after using many many 3rd party , free alternative file explorers.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
@nicholateslaisme thank you for opening this issue, QuickLook support is already implemented. Can you create a new bug report and include the log files and version information so we can look into why it's not working for you?
