### ISSUE TITLE
Ability to set the default option on colliding names

### ISSUE THREAD

**Issue by Andret2344** [files-community/Files#7926]
### What's the Problem?

When I copy&paste files, sometimes the colliding name appear, and I want to quickly overwrite old file to new. To do so, I have to manually change "Generate new name" to "Replace existing" for every file.

### Solution/Idea

The idea is to add to settings the setting to change the default behavior to overwriting.

### Alternatives

Manually changing the option to all files every time

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Change the default behavior when colliding names | Must |
| Apply to current session or all sessions (all by default) | Could |

### Files Version

2.1.2.0

### Windows Version

Windows 11  21H2; OS Built 22000.438

**Comment by yaichenbaum** [comment]
Thank you for your feedback, we're tracking this in #5645

**Comment by andret2344** [comment]
Hi @yair100, the #5645 doesn't 100% match this feature request. I am mostly a keyboard user, so I'd like to have the "Replace" option by default globally. The mentioned PR only allows to change the behavior for all conflicting files, but left "generate new name" as the default option and I still need to change it at last once. When I want to replace exactly one file, I still have to change the option. Bulk operation is not a point of this issue, the **default** option is.

**Comment by yaichenbaum** [comment]
#5645 will allow you to change the default option at the top of the dialog and the preference will be remembered the next time the dialog is opened.

**Comment by earshinov** [comment]
As OP suspected, #5645 (fixed in !8914) didn't fulfill the request he had. The "Generate new name" / "Replace existing" / etc. option selected in the top-right corner of the dialog doesn't seem to be persisted, at least not for me. I am going to file a new issue.

**Comment by yaira2** [comment]
> As OP suspected, #5645 (fixed in #8914) didn't fulfill the request he had. The "Generate new name" / "Replace existing" / etc. option selected in the top-right corner of the dialog doesn't seem to be persisted, at least not for me. I am going to file a new issue.

It's supposed to, if it's not working for you please open a bug report so we can track the issue.
