### ISSUE TITLE
Add a drive to favorites

### ISSUE THREAD

**Issue by vineetk101** [files-community/Files#7927]
### Solution/Idea

Possible to add a drive to Favourites? I use Cryptomator, I'd like to add the drive [i.e. lettered drive] that I use for mounting to my Favourites if possible.

### Alternatives

Cryptomator doesn't allow for a custom location anymore, which I first thought of implementing. They used to.

But also, my work enterprise environment is also made up of several network shares identified by drive letter, so ultimately, the above request remains.

### Windows Version

Windows 10.0.19044

**Comment by gave92** [comment]
Merging with #7321
