### ISSUE TITLE
Left-most navigation groups are broken

### ISSUE THREAD

**Issue by hanskokx** [files-community/Files#7929]
### Description

The shortcut groups on the left-most side of the window are broken. Some which should be expanded are not and clicking the arrow to expand them sometimes works.

### Steps To Reproduce

1. Open Files
2. Look at the left panel - some arrows point up while others point down
3. Tap some of the arrows

### Expected behavior

When tapping a down-pointing arrow, the group should expand. When tapping an up-pointing arrow, the group should contract.

### Files Version

Version: 2.1.2.0 OS Version: 10.0.22000.466

### Windows Version

Windows 11 21H2 22000.466

### Relevant Assets/Logs

![Animation](https://user-images.githubusercontent.com/1911919/150875710-232cc64c-3e5c-476b-9f23-c2d1cb5f937d.gif)

**Comment by gave92** [comment]
Tracked in #6469

**Comment by hanskokx** [comment]
> Tracked in #6469

...My bad. I should have searched, first.
