### ISSUE TITLE
Launch "bash" from Address Bar

### ISSUE THREAD

**Issue by tdw46** [files-community/Files#7930]
### What's the Problem?

Running "bash" from the address bar does not launch a WSL bash terminal at the location:
![image](https://user-images.githubusercontent.com/10996763/150881009-0b437007-1e09-438b-9e92-56d9da8778f9.png)
![image](https://user-images.githubusercontent.com/10996763/150881029-a3f2a91e-046c-450e-90c2-e2737d23e4f0.png)

### Solution/Idea

In the default file explorer you can run "bash" "python" and many other system terminal names and it will launch the corresponding terminal at the location the explorer is currently at. This is a very important part of my workflow as a programmer and I (and many others) would benefit from this feature being supported.

### Alternatives

There is no alternative to this solution. You can either add support for this, or not.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.1.2.0 OS Version: 10.0.22000.466

**Comment by gave92** [comment]
Thanks for the report. This has been recently implemented (#7859) and will ship with the next version.

**Comment by gave92** [comment]
In the meantime you can get around this limitation by going to Settings > Preferences > Terminals > Edit terminal applications.
You can add any executable to the json file that opens. Executables listed here will open when you type them in the address bar.
