### ISSUE TITLE
Consider making a Linux beta version?

### ISSUE THREAD

**Issue by AndrewLaganaro** [files-community/Files#7932]
Hello. I love files and I've been thinking about a Linux version, particularly Ubuntu.

Do you think it is possible some day? Would really appreciate it.

There's the suggestion. Thanks 😊

**Comment by yaichenbaum** [comment]
@AndrewLaganaro we don't have enough resources to work on Linux version but if someone is interested in putting together a group of devs to work on such a version, I'll be happy to work with them.

**Comment by LokeYourLord** [comment]
That would be great really as one of the reasons I love Windows over Linux is the File Explorer and several other "neat" things that Linux doesn't have. Now, if there was a version of this File Explorer for Ubuntu 20.04, THAT would be a compelling reason to start using Linux/Ubuntu far more. I hope someone would be willing of making a proper File Explorer for Linux/Ubuntu, as they are all trash.
