### ISSUE TITLE
Flash drive opens on regular windows explorer

### ISSUE THREAD

**Issue by AndrewLaganaro** [files-community/Files#7933]
**Description**
I have Files defined as default file explorer on "Experimental" settings but even though when I plug any flash drive it still opens on the regular windows explorer.

**Steps to reproduce**
Just plug a flash drive
**Expected behavior**
It should open into Files instead
**Version**
Files: 2.0.34.0
OS Version: 10.0.19043.1348

**Comment by yaichenbaum** [comment]
This issue should be resolved by updating to v2.1.2 and toggling the setting of and on again.
