### ISSUE TITLE
Scan for Update available

### ISSUE THREAD

**Issue by lyonelf** [files-community/Files#7942]
### What's the Problem?

The program have no alert for an update available

### Solution/Idea

periodically scan for update

### Alternatives

no one

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.2

### Windows Version

10 21h1

**Comment by yaichenbaum** [comment]
@lyonelf the store version will prompt you when an updatee is availible.
