### ISSUE TITLE
Plugging in an MTP device makes Files unable to detect all system drives and causes erratic explorer.exe behaviour

### ISSUE THREAD

**Issue by nyaambxr** [files-community/Files#7943]
### Description

The app becomes unresponsive, failes to detect drives, launches explorer.exe, does not let explorer access the drive and more when an MTP USB device, such as an Android Phone is connected.
The MTP device in question shows up as one peripheral that consists of two drives, the primary drive and the SD Card. This is expected and always happened in Explorer but when using Files, Explorer does not have access to any of the drives, just the pseudo-drive where they are attached.

### Steps To Reproduce

1. Enable Files as your Default File Manager.
2. Connect your Android Phone via USB.
3. Turn on File Transfer.
4. (The explorer window pops up as soon as you turn on File Transfer. May suggest that this is an AutoRun problem.) 
Sometimes Explorer and Files will open, close, become unresponsive and block all file transfers to the device. Other times Explorer will partially work but making Files unable to detect any drives connected to the host machine.

### Expected behavior

It should not open explorer by default and open Files instead, read all drives properly (including the MTP one). IMO: Limiting Explorer's function is OK if Files works.

### Files Version

Version: 2.1.2.0 OS Version: 10.0.22000.438

### Windows Version

Windows 11, 21H2, 22000.438

### Relevant Assets/Logs

The first time it happpened both Explorer and Files became unresponsive, Opened, Closed, Could not read or write to the Device, Etc... 
After I reproduced the issue, behaviour was different and the logs look much cleaner:
[debug.log](https://github.com/files-community/Files/files/7933408/debug.log)
(The relevant part starts at "2022-01-25 12:47:13.4692|INFO|DeviceAdded|Drive added: \\?\motorola one macro\, Removable" and then again at "2022-01-25 13:00:11.5857|INFO|DeviceAdded|Drive added: \\?\motorola one macro\, Removable")
[debug_fulltrust.log](https://github.com/files-community/Files/files/7933413/debug_fulltrust.log)

It seems like both apps are blocking eachother's access to the drive(s).

[A video demonstrating the issue that appears in logs around 13:01](https://youtu.be/z3JNbLuh1Pc)

**Comment by Ir1sDev** [comment]
May be linked to #779

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.0.0?

**Comment by yaichenbaum** [comment]
I can't reproduce this in v2.3 so I think it's fixed.
