### ISSUE TITLE
Error :  NotAFolder when refreshing in the home tab

### ISSUE THREAD

**Issue by sivelswhy** [files-community/Files#7944]
### Description

When you click on refresh on the "Home" Tab, an errors appears _(screenshot in the asset section)_

`Disk Deconnected`
`NotAFolder`

### Steps To Reproduce

1. Open Files App (if not already)
2. Click on the "Home" Tab
3. Click on the refresh button at the top left (if the button is gray, click to another tab and co back to it and it should be white)
4. Observe

### Expected behavior

There should not be any error or the button shouldn't be in this tab

### Files Version

Version : 2.1.2.0 OS Version: 10.0.19044.1466

### Windows Version

Windows 10 pro 21H2 Build version : 19044.1466

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7935449/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7935451/debug_fulltrust.log)

![image](https://user-images.githubusercontent.com/82051273/151019846-dc8ef829-7062-4943-87c7-689f2ac5ba4b.png)

**Comment by yaichenbaum** [comment]
@sivelswhy is this still an issue in the preview version? https://files.community/download/preview
