### ISSUE TITLE
Drag and drop from one tab to another invokes scrolling in second tab (=can't drop into sub-folder)

### ISSUE THREAD

**Issue by enoversum** [files-community/Files#7945]
### Description

When I try to drag and drop a file or folder from one Files tab to another, the list of files and folders in the destination tab starts to scroll automatically. It is thus impossible to drop the file/folder into the desired sub-folder in the second tab.
This possibly requires to have more files and/or folders in the destination tab than can be viewed in the window at once, thus making it scrollable. 

### Steps To Reproduce

1. Open two tabs in one Files instance. Second tab should have more files and/or folders than are visible in the window.
2. Click and hold a file or folder in the first tab and drag it onto the header of the second tab.
3. Second tab appears, but files/folder list immediately starts scrolling, making it impossible to drop it into the desired sub-folder, as it scrolls out of view. 

### Expected behavior

I can simply drop the file/folder I dragged from another tab to a folder in the second tab. 

### Files Version

2.1.3 (Store version)

### Windows Version

11 (current stable release)

### Relevant Assets/Logs

none

**Comment by gave92** [comment]
Thanks for the report. Could you post a screen recording of this?

**Comment by enoversum** [comment]
It seems to happen in detail view, the grid views don't seem to be affected on my quick tests. Here is a screen recording of that phenomenon, reproduced on another machine than I reported it from.

https://user-images.githubusercontent.com/8190174/151064946-c14507a0-745f-43e1-aea4-e0ae792df015.mp4

**Comment by gave92** [comment]
Thanks, curious for me the list only scrolls if the dragged item is near the top or the bottom of the list.

**Comment by enoversum** [comment]
Well, no idea if that helps. Maybe you need a folder with files and/or folders into both directions, so try a destination folder that has a lot of files or folders in it, and stick to somewhere in the middle before you drag and drop, maybe that helps evoking it. 
For me though, I can be at the very end of my folder content, and after switching from first to second tab move the mouse wherever I want, it most of the time starts this happy scroll dance.

**Comment by yaichenbaum** [comment]
@enoversum is this still an issue in the preview version? https://files.community/download/preview

**Comment by enoversum** [comment]
@yair100 Thanks for the link to the Preview version. And yes, unfortunately, this is still happening, even with the Preview version.

**Comment by yaira2** [comment]
This appears to be resolved in v2.4.11.

**Comment by enoversum** [comment]
@yair100 It's still there for me. It doesn't happen if I drag an item _beside_ the columns in Detail View, to the far right of the window. As soon as my mouse lands on one of the columns (Name, Tag, Last change, Type etc.), the tab starts scrolling like an Instagram user on Acid. Edit: Even in the Preview version.
