### ISSUE TITLE
Copy and move operations always report success even on error

### ISSUE THREAD

**Issue by lightningHoneypot** [files-community/Files#7947]
### Description

On Windows Explorer, when you drag a file to another directory but the file is still open, it will prompt an error message that it can't move the file because it is currently open with an another program. In Files (Community) however, it doesn't show an error, but instead shows that the task has been completed. 

### Steps To Reproduce

1. Take one file and one folder
2. _Important:_ Open the file first
3. Move the file to a folder
4. The file is still on the original place pre-"moving", but Files (Community) shows that the move has been complete

### Expected behavior

I expected that one should see an error message saying that the file has not yet been transferred because the file in question is currently open and one should save all work before closing and trying again the task they tried to do.

### Files Version

Version: 2.1.2.0 OS Version: 10.0.19043.1466

### Windows Version

Windows 10 21H1 OS Build 19043.1466

### Relevant Assets/Logs

https://user-images.githubusercontent.com/88814097/151035531-a4ea4fe8-3545-4505-b06b-76bb92332de8.mp4

**Comment by kenleyshaw** [comment]
I am new to the Open source community. For one of my courses for college, we have to contribute to a project - this seems like an issue that I may be able to help with. Can you assign this to me please? I'll update along the way as I troubleshoot

**Comment by yaichenbaum** [comment]
@lightningHoneypot is this still an issue in the preview version? https://files.community/download/preview

**Comment by lightningHoneypot** [comment]
> @lightningHoneypot is this still an issue in the preview version? https://files.community/download/preview

Nope! It seems that everything is good to go! 

There is one issue that Files still shows a checkmark on the ongoing tasks icon that it makes it look like a file transfer is successful, but then the error box appears stating that a process is still using the file in question. However, it might as well be an inconvenience (see video on what am I saying, if there's any questions tell me).

(excuse the crappy editing in DaVinci Resolve, I am still in the beginner stages and that is the reason why it took so long for my response)

https://user-images.githubusercontent.com/88814097/167963318-842da106-8d91-400f-9773-a05b8838813c.mov

**Comment by yaichenbaum** [comment]
@lightningHoneypot thanks for the response, can you open a separate issue for the status icon? It's deffinitly something that should be fixed.
