### ISSUE TITLE
Add the ability to hide empty drivers

### ISSUE THREAD

**Issue by ChelaruCatalin** [files-community/Files#795]
Add a feature like Don't show hidden files, folders, or drivers from Folder Options.
This will hide this drivers as long as there is nothing plugged in.
![Annotation 2020-05-17 041703](https://user-images.githubusercontent.com/9988172/82133579-8f4a9480-97f6-11ea-80ed-55ed0ae6788c.png)

**Comment by yaichenbaum** [comment]
Merging with #2722.
