### ISSUE TITLE
Scrolling is weird

### ISSUE THREAD

**Issue by tiomanisland** [files-community/Files#7950]
### What's the Problem?

This app is fantastic but why is scrolling different that in Windows Explorer or other Windows apps? You should use scrolling set in Windows, not override with your smooth scrolling. This is bad, otherwise your app is fantastic.

### Solution/Idea

Use scrolling type as defined in user's settings in Windows 10 when there are more files in windows and you scroll with mouse wheel, scrolling in your app is smooth although my settings are set NOT to smooth.

### Alternatives

Windows Explorer - I like the scrolling there more

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.2.0

### Windows Version

Windows 10

**Comment by gave92** [comment]
Tracked in #7764
