### ISSUE TITLE
No Access to a WebDAV Network Location

### ISSUE THREAD

**Issue by babyblue69** [files-community/Files#7951]
### Description

No Access to a WebDAV Network Location

error message:
title: Disk Disconnected
message: Generic

### Steps To Reproduce

1. open the application, Files (File Manager)
2. select Network Disk in (go video)

[https://drive.infomaniak.com/app/share/Files-managerfile_souciNASWebDAV_2022-01-25.MP4](https://drive.infomaniak.com/app/share/107658/80cc5b77-f173-492a-a62e-138069aaed6a)

### Expected behavior

select Network Disk in (go video)

[https://drive.infomaniak.com/app/share/Files-managerfile_souciNASWebDAV_2022-01-25.MP4](https://drive.infomaniak.com/app/share/107658/80cc5b77-f173-492a-a62e-138069aaed6a)

### Files Version

Version : 2.1.2.0 OS Version : 10.0.19044.1469

### Windows Version

Windows 10 Pro 64 - Version 21H2 - Installé le ‎11.‎06.‎2020 - Build os : 19044.1469

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7937888/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7937889/debug_fulltrust.log)

**Comment by fabian-st** [comment]
Can confirm this issue

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
Is this a SFTP connection?
