### ISSUE TITLE
Adding options and optimizing

### ISSUE THREAD

**Issue by ismael12br** [files-community/Files#7952]
### What's the Problem?

On the home page, the program is slow to show the folders (images, downloads, etc.), in addition to not returning to the home page when clicking on drives in the sidebar. The program also does not have a "send to" option.

### Solution/Idea

You can add the options mentioned above.

### Alternatives

Add a button to take you to the home page, as seen in browsers

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Versão: 2.1.2.0

### Windows Version

Windows 10 Pro 21H2 19044.1499

**Comment by yaichenbaum** [comment]
Merging with #7350

**Comment by yaira2** [comment]
We're excited to share that startup performance will be significantly improved in the upcoming release of version 3. You can download the preview version from our website https://files.community/download.
