### ISSUE TITLE
Compact mode

### ISSUE THREAD

**Issue by Yoshomay** [files-community/Files#7953]
### What's the Problem?

Normal windows explorer lets you make things compact like 10-. only thing stopping me from using this

### Solution/Idea

Add compact mode

### Alternatives

don't i guess..? idk this is required so

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.1.0.0

### Windows Version

Windows 11 Pro 21H2

**Comment by yaichenbaum** [comment]
Merging with #1940
