### ISSUE TITLE
Crash while Hiding Folder

### ISSUE THREAD

**Issue by spooferjahks** [files-community/Files#7954]
### Description

App crashes when trying to hide two folders at the same time. 

### Expected behavior

Expected the two folders to be hidden 

### Files Version

Version: 2.1.3.0

### Windows Version

Windows 11 21H1 build 22000.469

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7938661/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7938662/debug_fulltrust.log)

**Comment by gave92** [comment]
Same as #7918
