### ISSUE TITLE
Turn of file press animation

### ISSUE THREAD

**Issue by grahamwheaton** [files-community/Files#7956]
### What's the Problem?

I personally find the animation quite jarring, and makes it feel slow.

(compared to explorer)

### Solution/Idea

In the settings, have a toggle on off.

### Alternatives

In the settings, have a toggle on off.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by Wanooo0** [comment]
I totally agree. This animation is pretty ugly.

**Comment by yaichenbaum** [comment]
This issue is resolved in Windows 11.
