### ISSUE TITLE
Copying a file shows "success" when there is no space left on the disk

### ISSUE THREAD

**Issue by xcad2k** [files-community/Files#7957]
### Description

Copying a file shows "success", even though the file isn't copied, because there is no space left on the disk. This also happens when the file is moved.

**Test Scenario:**

I tried to copy a large file 3.44GB to a Disk which hasn't enough space left, as you can see in the screenshots below:

<img width="231" alt="image" src="https://user-images.githubusercontent.com/28359525/151150978-78ffa5ec-e7c7-49e6-ac4a-2772ac180c86.png">
<img width="254" alt="image" src="https://user-images.githubusercontent.com/28359525/151151004-b023c186-5d07-47e3-ac87-f28185525af6.png">

When I copied the file to the Disk, I received this message, even though the file wasn't copied.

<img width="319" alt="image" src="https://user-images.githubusercontent.com/28359525/151150940-ecb67e50-fcd3-4684-99e3-103e81bb7580.png">

### Steps To Reproduce

1. No space left on disk
2. Copy a file to the disk that would exceed the space left
3. Files shows "success"

### Expected behavior

Files should show an error message "No space left on the disk".

### Files Version

2.1.2

### Windows Version

Windows 11 21H2 (22000.466)

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7941194/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7941195/debug_fulltrust.log)

**Comment by gave92** [comment]
Merging with #7947
