### ISSUE TITLE
Can't change default File explorer

### ISSUE THREAD

**Issue by Quinten0508** [files-community/Files#7959]
### Description

In an older version, I chose to set Files as my default files explorer. However, in the current version installed (20.0.13.0) the option to toggle this "default file manager" is gone. This means I cannot switch back to Windows' built-in explorer anymore. I have to switch back to Explorer from time to time for some more niche features or to fix / identify the cause of related issues. 

### Steps To Reproduce

1. Install an older version of Files
2. Select Files to be the default file manager under experimental options
3. Files gets updated to a new version
4. Observe the option mentioned in step 2 is gone

### Expected behavior

The option should still be there, even if it's in it's very early stages. Now, people might be stuck with Files as their default with no way out (but to uninstall Files? - untested). 

### Files Version

20.0.13.0

### Windows Version

Windows 11 Pro Insider Preview 22538.1000 (rs_prerelease)

### Relevant Assets/Logs

New Files `experiments` screen, without the aforementioned option:

![image](https://user-images.githubusercontent.com/55107945/151165045-581e6e10-01a4-492f-9a74-321afa756046.png)

**Comment by yaichenbaum** [comment]
It looks like you're using an older version of Files. Please update to v2.1.2 and try again.
