### ISSUE TITLE
Feature: Always display the size in the status bar when ShowFolderSize is enabled

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#7961]
### What's the Problem?

In a folder you have to select all to display the total size.

### Solution/Idea

It would be handy to show the total size in the status bar when nothing is selected and the option to show folder sizes is enabled.

### Alternatives

None.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by ferrariofilippo** [comment]
@yair100 this is already supported, I think you can close it

![Image](https://user-images.githubusercontent.com/102259289/212567506-7f079575-6601-4dd1-badb-72d96f92f80c.png)

**Comment by yaira2** [comment]
Might keep this open until we decide is if we should show this even with the option turned off.
