### ISSUE TITLE
Copy operation doesn't auto refresh on network drives

### ISSUE THREAD

**Issue by diegoborgh** [files-community/Files#7965]
### Description

Anytime I copy files, or create a folder, I have to hit the reset button. It works ok on the main drives, but on network drives it doesn't work

### Expected behavior

I"d like to see the files copied displayed in the folder.

### Files Version

2.1.2.0

### Windows Version

Windows 10 21H2

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7946534/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7946535/debug.log)

**Comment by gave92** [comment]
Tracked in #5869
