### ISSUE TITLE
设置成默认文件管理器后，无法调出系统的控制面板

### ISSUE THREAD

**Issue by 850710247liu** [files-community/Files#7966]
### Description

一个严重的无法调出控制面板的BUG

### Expected behavior

在设置中开启设为默认文件管理器后，无法调出控制面板

### Files Version

最新

### Windows Version

win10

### Relevant Assets/Logs

闪退

**Comment by yaichenbaum** [comment]
Thank you for opening this issue, in order to investigate, we will need the version number and log files.
