### ISSUE TITLE
Automatically delete/discard illegal filename characters when *pasting* a string on a *new* file/folder

### ISSUE THREAD

**Issue by lightningHoneypot** [files-community/Files#7967]
### What's the Problem?

In Files Explorer, every time when you paste a string that contains: 

- :
- &
- "
- ?
- <
- (>)
- (#)
- {
- }
- % 
- ~
- /
- \

It will automatically delete the string **and** displays the following message
> file names can't contain the following characters: & " ? < > # { } % ~ / \.

If the user tries again by deleting and pasting the same string, File Explorer will automatically post the string of text without those characters as if the user didn't copy them in the first place. (see video 2)

Currently, Files (Community) does not support this feature, but this idea could help people like for example: a student that is organizing their folders when an instructor releases new materials by the week. Small but significant features that are in Files Explorer should be implemented into Files (Community) so the program could be seen as a replacement to the venerable but dated Files Explorer.

https://user-images.githubusercontent.com/88814097/151285775-efbd8a5d-b18a-402c-81e8-f786b8d13c9f.mov

https://user-images.githubusercontent.com/88814097/151285778-d48a250b-6266-464d-8c5c-05aeecf8c354.mov

### Solution/Idea

When the user pastes a string when naming a new file/folder with these illegal filename characters:

- :
- &
- "
- ?
- <
- (>) 
- (#) 
- {
- }
- % 
- ~
- /
- \

It should automatically delete the string **and** displays the following message
> file names can't contain the following characters: & " ? < > # { } % ~ / \.

If the user tries again by deleting and pasting the same string, Files should automatically post the string of text without those characters as if the user didn't copy them in the first place. (see video 2)

### Alternatives

There is currently no alternative to what I describe other than not implementing it, it's a small feature but it could help some people.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to not manually delete a copied text that has an illegal filename character(s) when naming files/folders | Must |
| If the user tries again by deleting and pasting the same string, Files (Community) will automatically post the string of text without those illegal filename characters as if the user didn't copy them in the first place, just like Files Explorer. | Must/Should |

### Files Version

Version: 2.1.2.0 OS Version: 10.0.19043.1466

### Windows Version

Windows 10 21H1 OS Build 19043.1466

**Comment by yaichenbaum** [comment]
This issue should be resolved with #8204
