### ISSUE TITLE
Pack of scripts

### ISSUE THREAD

**Issue by dimitakhs1** [files-community/Files#7971]
### What's the Problem?

I love files!I'd like to see in the future pack of cool scripts

### Solution/Idea

A pack of right-click sub menu scripts like we have on linux

### Alternatives

No idea

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version
2.1.2.0
_No response_

### Windows Version

Windows 11 21H2 22000.469

**Comment by gave92** [comment]
Could you post some screenshots / more details to clarify what you're referring to?

**Comment by dimitakhs1** [comment]
Something like that: Nautilus Scripts - Gnome-look.org for Windows though Στάλθηκε από την Αλληλογραφία για τα Windows Από: Marco GavelliΑποστολή: Πέμπτη, 27 Ιανουαρίου 2022 21:50Προς: files-community/FilesΚοιν.: dimitakhs1; AuthorΘέμα: Re: [files-community/Files] Pack of scripts (Issue #7971) Could you post some screenshots / more details to clarify what you're referring to?—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by yaichenbaum** [comment]
@dimitakhs1 can you try adding the comment again?

**Comment by dimitakhs1** [comment]
Nothing big. I just wanted more right click scripts,like 'copy to','batch
copy to','move to','open terminal here','open command line here','open iso
file here' etc. Might be in the form of script or an add-on or something
else maybe,you know better

Στις Δευ, 31 Ιαν 2022, 06:36 ο χρήστης Yair Aichenbaum <
***@***.***> έγραψε:

**Comment by yaichenbaum** [comment]
Merging with #5248 #7350
