### ISSUE TITLE
Acryll effect bugs out, getting dark

### ISSUE THREAD

**Issue by rGunti** [files-community/Files#7972]
### Description

When using any bright theme, context menus and flyouts tend to get blurred incorrectly, getting darker in the process.
![image](https://user-images.githubusercontent.com/5184813/151316433-9b36a4e4-63da-48c3-8590-5fb4b65bc262.png)

### Expected behavior

Flyout and Context Menus should be colored like this:
![image](https://user-images.githubusercontent.com/5184813/151316814-fe5c52b1-0091-4cdb-87e4-2b4f68d849c5.png)

### Files Version

Version: 2.1.2.0 OS Version: 10.0.19044.1348

### Windows Version

Windows 10 21H2 19044.1348

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7948658/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
This issue is resolved in Windows 11.
