### ISSUE TITLE
Files is a bit slow comparing to Windows 10 native Explorer

### ISSUE THREAD

**Issue by tiomanisland** [files-community/Files#7973]
### What's the Problem?

Sometimes clicking around seems slow. In what program is this written? Is it possible to make click action faster (instant)?

### Solution/Idea

Make clicking more responsive.

### Alternatives

Default Windows 10 Explorer.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
@tiomanisland this is becuase of the Windows 10 xaml styles but it's resolved in Windows 11.

**Comment by tiomanisland** [comment]
> @tiomanisland this is becuase of the Windows 10 xaml styles but it's resolved in Windows 11.

If I understand you right you are saying that Files is slow in Windows 10 but fast in Windows 11?

**Comment by yaichenbaum** [comment]
@tiomanisland I meant in regards to the click animation, performance for item enumeration should be about the same.

**Comment by yaira2** [comment]
We're excited to share that startup performance will be significantly improved in the upcoming release of version 3. You can download the preview version from our website https://files.community/download.
