### ISSUE TITLE
Drag and Drop to Windows Mail

### ISSUE THREAD

**Issue by FionNoir** [files-community/Files#7975]
### Description

Drag and Drop of files to Windows Mail App isn't working

### Steps To Reproduce

1. Open Windows Mail App
2. Write a new mail
3. Try to Drag and Drop a File from the Explorer to the new mail

### Expected behavior

File should be added as attachment to the mail.

### Files Version

2.1.2.0s

### Windows Version

Windows 10 Home 21H1  19043.1466

### Relevant Assets/Logs

No

**Comment by yaichenbaum** [comment]
Merging with #6941
