### ISSUE TITLE
Linking with QuickLook

### ISSUE THREAD

**Issue by zsxdcfvgbh** [files-community/Files#7976]
### Solution/Idea

Nice to meet you.
File and I have been best friends since we met at the Microsoft Store.
Now, what I would like to ask you to do is to work with a Windows software called QuickLook.
This is a very capable software that allows you to use the functionality of QuickLook on Mac as it is on win.
I used to use Windows Explorer, and it was an indispensable feature for me.
So, I would like to ask you to make it possible to use quicklook in Files.
I know that this is a very selfish and self-serving request. I know this is a very selfish and selfish request, but I would appreciate it if you could do it in your spare time.
This is a low-priority item, so please keep it in mind.

Thank you.

Translated with www.DeepL.com/Translator (free version)

### Alternatives

I don't know much about programming, so I can't tell you anything.
I apologize.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.2.0 

### Windows Version

windows11 21H2 22000.434

**Comment by yaichenbaum** [comment]
QuickLook is already supported, if it's not working for you, can you please open a bug report and include the log files and version information?
