### ISSUE TITLE
sudden death when browsing through network folder

### ISSUE THREAD

**Issue by AlYahyaMajed** [files-community/Files#7977]
### Description

Files suddenly stopped working when browsing through network mapped drive and folders

### Steps To Reproduce

1- open network drive
2- navigate to a subfolder
3- return to parent folder

### Expected behavior

open the subfolder and return to main folder normally. 

### Files Version

Version: 2.1.2.0 

### Windows Version

Windows 10 Version: 10.0.19044.1469

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7951896/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7951897/debug.log)

**Comment by yaichenbaum** [comment]
@AlYahyaMajed is this still an issue in the preview version? https://files.community/download/preview
