### ISSUE TITLE
Allow disabling the hover effect when clicking on folders

### ISSUE THREAD

**Issue by ManfredRichthofen** [files-community/Files#7978]
### What's the Problem?

Not a huge problem but imo the hover effect doesn't look great at least as it is currently implemented especially because the text and icons loose quality.  

### Solution/Idea

I think giving the option to disable this effect would be great

### Alternatives

Im not sure what this is asking.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.2

### Windows Version

Windows 10 2004

**Comment by yaichenbaum** [comment]
@ManfredRichthofen we don't plan to change the style on Windows 10 but this issue should be resolved on Windows 11.

**Comment by joseska** [comment]
+1.. is not good when click or double click
