### ISSUE TITLE
Update German translation

### ISSUE THREAD

**Issue by enoversum** [files-community/Files#7979]
### Description

When having multiple language packs installed, Files doesn't show strings from the chosen system language, but mixes them with the other language(s). My system is in German, but shows some strings in Norwegian, which I have installed as a secondary language pack and keyboard layout. 
The Norwegian strings are in the last line: _Rydd opp… Disk-opprydding_

### Steps To Reproduce

Possibly only happening if multiple language packs are installed. 

### Expected behavior

All strings are shown in chosen system language. 

### Files Version

2.1.3.0 (Store version)

### Windows Version

Windows 11 (22000.466)

### Relevant Assets/Logs

![ApplicationFrameHost_jmLAhV4rKd](https://user-images.githubusercontent.com/8190174/151397304-7202f3fb-39b7-4882-9cd5-41d5a42bf1b6.png)

**Comment by yaichenbaum** [comment]
@enoversum Files will fall back to secondary languages if there are untranslated strings, would you like to update the German translation? https://files.community/docs/contributing/translating-files

**Comment by enoversum** [comment]
@yair100 Ah, good to know, had no idea. So it's basically only happening when there are missing strings. Funny enough, Norwegian has only a tiny community of speakers in the whole world, whereas German is far more popular. 
Thanks for the link for the translations! I'm afraid it's a bit too technical and time consuming for me at the moment ❤️!

**Comment by BirnadinErick** [comment]
@yair100 how do I know which strings needs to be translated and which are already translated? the `Files.de-DE.xlf` file seems to have all the nodes translated, sorry I am new here.

**Comment by yaichenbaum** [comment]
@BirnadinErick there is a value called `state`, translated strings have the `translated` and new strings have the `new` state.

**Comment by BirnadinErick** [comment]
@yair100 v2.13.0 and latest clone from the repo seems to have all the strings in `translated` state. @enoversum was using older version, guess it was the issue.

**Comment by enoversum** [comment]
@yair100 @BirnadinErick I fear it's not the issue. As stated, I use the Store version, and update on a regular basis. 2.1.13.0 still shows some strings in Norwegian vs. German. The two strings in my first screenshot are gone already, but I found two places on the spot that still carry Norwegian instead of German.
First one: Eksperimentelt and the Advarsel sentence are Norwegian. Second one: All the strings at the top are Norwegian.
![eksperiment](https://user-images.githubusercontent.com/8190174/154644190-428f8099-64a7-4252-8c03-f41bc0d59721.jpg)
![Egenskaper](https://user-images.githubusercontent.com/8190174/154644193-e857c921-e6a7-475e-b4d7-4e2d7465be63.jpg)

**Comment by yaichenbaum** [comment]
@enoversum we often update strings so it's not uncommon for there to be some untranslated strings. The current dev branch is fully up to date though and will be included in the next update.

**Comment by enoversum** [comment]
@yair100 Aaah, so it's completed in dev, but not yet gone to production (i.e. Store version)? Then everything's as it should be I suppose ;) . From the sounds of it, I lacked some updated translations that I didn't replace myself (which I wouldn't with the Store version).

**Comment by enoversum** [comment]
Just a small heads up: 2.1.14 still doesn't include the strings. Just in case something went wrong. I'll gladly wait for updates though 🙂.

**Comment by enoversum** [comment]
@yair100 Just to make sure: On the current update, several strings still show in Norwegian, while you already stated that German is 100% translated two versions ago. Are the translations still not integrated fully, or is there something else amiss (maybe because I have two language packages installed)?

**Comment by yaichenbaum** [comment]
@enoversum we ended up reverting some strings and updating other ones so they may be out of date again, would you be intresting in updating the translation file from time to time?
