### ISSUE TITLE
File renaming: Focus jumping in Icon/Details view

### ISSUE THREAD

**Issue by enoversum** [files-community/Files#7980]
### Description

When renaming a file in Detail view, after renaming the focus jumps to the column header (Name). If I switch to small/medium/large Icon view (no idea how it is called in English), the focus jumps to the first file or folder in the location. 

### Steps To Reproduce

1. Switch to Details view.
2. Rename a file.
3. Focus jumps to column header ('Name').
4. Switch to small/medium/large Icons view.
5. Rename a file.
6. Focus jumps to first item inside the current location.

### Expected behavior

Files keeps focus on renamed item after renaming instead of jumping.

### Files Version

2.1.3.0 (Store version)

### Windows Version

Windows 11 (22000.466)

### Relevant Assets/Logs

none

**Comment by enoversum** [comment]
Edited, as I saw crashes when renaming files in Grid/Tiles view has already been reported.

**Comment by yaira2** [comment]
Is this still an issue in v2.4?

**Comment by enoversum** [comment]
It is kind of fixed in v 2.3 (my Store won't download the new 2.4 update). The focus jumps quickly to the header atop the columns, then jumps back quickly to the file edited.
