### ISSUE TITLE
Can't go back on default File explorer

### ISSUE THREAD

**Issue by osaunier** [files-community/Files#7981]
### Description

In the previous release, I have set Files as the default File Manager. I've upgraded to 2.1 and see the button to roll back but it doesn't work.

### Steps To Reproduce

1. Install the previous release with no rollback possible
2. Set Files as default file manager
3. Update to the last release
4. Try to rollback

### Expected behavior

Explorer is the Default Manager again. 

### Files Version

Version : 2.1.2.0 OS Version: 10.0.19044.1466

### Windows Version

Windows 10 Professionnel Version	21H2

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/1670130/151400472-6d710143-877c-4292-b5e8-04fd4e2c66d2.png)
but when I try a win + e
it opens Files

**Comment by Josh-65** [comment]
You can run this script and then try turning the option on again if you want.
https://raw.githubusercontent.com/files-community/Files/main/src/Files.Launcher/Assets/FilesOpenDialog/UnsetFilesAsDefault.reg
