### ISSUE TITLE
Cannot open Properties for any file/folder

### ISSUE THREAD

**Issue by prajjwal27** [files-community/Files#7983]
### Description

When I try to open the properties window for any file or window, the cursor shows a loading animation but nothin happens after that.

### Steps To Reproduce

1. Open Files.
2. Navigate to required directory (any).
3. Press the 'Properties' button.
OR
3. Right click on the required file/folder.
4. Press the 'properties' button in the context menu.

### Expected behavior

A properties window should open like the one below.

![image](https://user-images.githubusercontent.com/55483277/151412339-a1b8741d-fd76-4931-83b2-3ee3ae0d52f2.png)

### Files Version

Version: 2.1.2.0 OS Version: 10.0.22000.466

### Windows Version

Windows 11 Home 21H2 OS build 22000.466

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7952594/debug_fulltrust.log)

**Comment by rondDev** [comment]
I am having the same issue. Same replication as stated above.

### Files Version
Version: 2.1.15.0

### Windows Version
Windows 11 Pro (Dev Channel) OS build 22557.1

###Logs
[debug_fulltrust.log](https://github.com/files-community/Files/files/8155714/debug_fulltrust.log)

**Comment by mj123456-ux** [comment]
Guys, come on, we must fix this problem. I really like this resource manager and don't want to give up using it because of this problem

**Comment by yaichenbaum** [comment]
This issue cannot be reproduced in `main`. Please let us know if you run into this issue again in the future.

**Comment by prajjwal27** [comment]
Is the main version the same one as the one downloaded from Microsoft Store? I can still reproduce the bug currently. Also this version does not let me set Files as the default file manager anymore.

Edition	Windows 11 Home Single Language
Version	21H2
Installed on	‎26 ‎Feb
OS build	22000.593
Experience	Windows Feature Experience Pack 1000.22000.593.0

Files:
Version: 2.1.15.0
OS Version: 10.0.22000.593

[debug_fulltrust.log](https://github.com/files-community/Files/files/8396834/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
@prajjwal27 the changes in the `main` branch haven't been released yet. This issue was caused by a bug in Windows which MIcrosoft has since resolved.
