### ISSUE TITLE
Animations speed

### ISSUE THREAD

**Issue by dbbgba** [files-community/Files#7984]
### What's the Problem?

The animations between interactions are great but they do slow down the workflow of intense file management.

### Solution/Idea

Maybe have a slider to speed up the animation or a drop-down menu (ala android).

### Alternatives

Just a checkbox to disable them could be a quick temporary solution, I don't like it because I do like animating things on screen, but as a temporary option, I will take it.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Have a quick way to disable or speed up animations speed | Must |
| Might even add extra easy in/out animations | Could |
| Shouldn't remove the fun of using the interface | Won't |

### Files Version

Version: 2.1.2.0 

### Windows Version

Win 10 Version: 10.0.19043.1466

**Comment by yaichenbaum** [comment]
This is specific to Windows 10 and is fixed in Windows 11.
