### ISSUE TITLE
Cmder as terminal option

### ISSUE THREAD

**Issue by dmegatool** [files-community/Files#7986]
### What's the Problem?

I would like to launch [Cmder ](https://cmder.net/) terminal with the contextual "Open in terminal". 

### Solution/Idea

Can we support 3rd party command line tools ? Or is it possible and not documented ? 

### Alternatives

I'm considering Fluent but I kinda like Cmder to be honest. It's portable, all my stuff's in there.

**Comment by yaichenbaum** [comment]
@dmegatool custom profiles are already supported, please see the docs for sample profiles and information on creating your own profile. https://files.community/docs/configuring/terminal-profiles

**Comment by dmegatool** [comment]
I tried that but didn't work. Turns out it was the slashes in the path making the json invalid. So if anybody needs this, you've got to use / instead of \ for the Windows path. Ex : "path": "C:/Cmder/Cmder.exe"
