### ISSUE TITLE
Automatically select file when opening it's location

### ISSUE THREAD

**Issue by Pietro228** [files-community/Files#7987]
### What's the Problem?

When I open downloaded file location from e.g. Firefox, it will only open the directory and it doesn't select the downloaded file.

### Solution/Idea

Select opened file in directory.

### Alternatives

I need to search the file in large directory.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.1.3.0 

### Windows Version

Windows 11 10.0.22000.466

**Comment by gave92** [comment]
Tracked in #6382
