### ISSUE TITLE
Option to show old Right Click Context Menu by Default

### ISSUE THREAD

**Issue by romanroth** [files-community/Files#7991]
### What's the Problem?

The Files App is a great substitute for the default explorer with a more visually appealing GUI and especially tabs. However many users like the old layout of the right click context menu instead of the Win11 style where you have to click "More" to get to your Shell Context Menu Options. 

### Solution/Idea

It would be cool if there was an Option to show the old right click context menu by default.
So instead of the Win11 style menu:
![image](https://user-images.githubusercontent.com/77147171/151570385-8901bf54-ed89-4647-be7a-e9b1a6086984.png)
The Shell Context Menu Options:
![image](https://user-images.githubusercontent.com/77147171/151570539-adbb3ffb-715e-4459-9996-6d9d190e554b.png)
But without having to click more.

### Alternatives

No Alternatives found other than dealing with it or using explorer.exe

### Files Version

2.1.2.0

### Windows Version

Windows 21H1 19043.1446

**Comment by yaichenbaum** [comment]
@romanroth you can show everything in the main menu by turning off the option to move items into the sub menu.
![image](https://user-images.githubusercontent.com/39923744/151572777-ee6038a3-2268-4184-9fa6-bac71cb87f39.png)

**Comment by romanroth** [comment]
@yair100 I am very sorry I did not see that... Was too obvious I guess.

**Comment by L0garithmic** [comment]
I am going to bump this and reiterate the request. I am currently using Ultimate Windows Tweaker on Windows 11 to bring back the old context menus for use with programs like XNShell and it is not working inside "Files". 

Images for example. Ignore the gawd awful context menu mess that I have not gotten around to cleaning up yet lol.
I need to be able to see the shell items, but I can not in your app. Though I prefer your app..

Files App
![FILES APP](https://user-images.githubusercontent.com/1237743/192078012-c2efe016-866e-427c-a23e-c234e773a94a.png)

Windows Explorer
![WINDOWS](https://user-images.githubusercontent.com/1237743/192078010-62c7d4a3-826e-4435-8d60-9fce781ebd7c.png)

**Comment by Josh-65** [comment]
Files uses frameworks that don't have the old content menu, Windows explorer does have it that why it works there and not Files.

**Comment by L0garithmic** [comment]
Yeah well... Maybe I am asking that files allow us to revert to the old context menu with say, a setting.. I don't think its an impossible ask

**Comment by yaichenbaum** [comment]
It's not impossible but it doesn't align with our goal for Files. If there is a popular shell extension that you use, please open a feature request and we can see if there is an alternative way, we can implement it.

**Comment by Vulcanraven91** [comment]
https://github.com/moudey/Shell
what about this shell from Nilesoft https://nilesoft.org/? 

I don't like the current Files current one is to slow with many items, and that's the reason why I'm not switching completely to Files as Explorer.
