### ISSUE TITLE
Words correction does worse than better

### ISSUE THREAD

**Issue by GkqqNkKC** [files-community/Files#7993]
### What's the Problem?

When renaming an item, a red underline appears under incorrectly spelled words. Sometimes these underlined words corrects themselves without explicit user input. A lot of people do not have the os in the desired naming language for their files. On top of that, there are a lot of times when a user actually wants to spell the filename by a different encoding system: as example: `${1}${2}${3}_${name}` where 1, 2 and 3 are some identifying characters that are not meant to form a word. Also, in a native-language-os, when downloading files, you're almost bound to download a file with English filename

### Solution/Idea

Remove the correcting system or make it less intrusive, like: do not underline the words, but let the user select the words, right-click, and there see any suggestions. The user knows when the word might be misspelled, so he can double check by right-clicking

A lot of text context menus now-days provides such a way of correcting the words without showing additional visual effects

### Alternatives

I find myself often renaming a file, then try to rename it again since the previous rename has corrected some intended words

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Allow the correcting system take place only by explicit user input | Must |
| Remove visual effects | Should |
| Provide a way to invoke the explicit input using the context menu (select text, right-click) | Should |
| Auto-correction | Won't |

### Files Version

Version: 2.1.0.0 OS Version: 10.0.22000.434

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎21/‎10/‎05 OS build	22000.434 Experience	Windows Feature Experience Pack 1000.22000.434.0

**Comment by gave92** [comment]
Merging with 7948
