### ISSUE TITLE
Option for bigger file preview with the preview pane

### ISSUE THREAD

**Issue by Slowwwww** [files-community/Files#7994]
**Problem**
When going through images the maximum size that image is displayed in the preview pane is a small. 
**Solution/Idea**
Having the option to hide the metadata and just view the image and/or resize the preview pane to make it bigger would greatly improve the usability for going through photos.
**Alternatives**
Opening every file you want to see (slow)

**Comment by gave92** [comment]
Thanks for the report. Latest preview version has the ability to make the preview pane a lot wider than before.
