### ISSUE TITLE
Better resizing Preview Pane

### ISSUE THREAD

**Issue by anwar3606** [files-community/Files#7995]
### What's the Problem?

Right now I can't see the preview panel that usefull. It's too small !!
For example, I can't see whats inside a image like this. 
This also applicable for Video preview. Even video preview takes up 30% of the space. 

![image](https://user-images.githubusercontent.com/3619250/151612785-3c028ec4-4f6d-42d7-8fb5-25aacf148d8a.png)

### Solution/Idea

remove resize restriction

able to resize vertically too

### Alternatives

Just removing horizontal resize restriction will also helpfull. 

### Files Version

Version: 2.1.2.0 OS

### Windows Version

Edition	Windows 10 Pro Version	21H2 Installed on	‎8/‎10/‎2021 OS build	19044.1503 Experience	Windows Feature Experience Pack 120.2212.4170.0

**Comment by yaichenbaum** [comment]
@anwar3606 this issue is resolved in our development branch and will be included in the next update.

**Comment by anwar3606** [comment]
> @anwar3606 this issue is resolved in our development branch and will be included in the next update.

Thank you!!!, I use this heavily in Windows Explorer. I saw there is a new option to see only preview. Along with this and resize will make my life really easy.
