### ISSUE TITLE
Drive Properties in Dark Mode Unreadable

### ISSUE THREAD

**Issue by ddetton** [files-community/Files#7997]
### Description

In Dark Mode with Default Theme, right click C: drive and select Properties.  The dialog background is white making the white text unreadable.

### Steps To Reproduce

 right click C: drive and select Properties

### Expected behavior

Expect to be able to read the dialog.

### Files Version

2.1.2.0

### Windows Version

Windows 11 Version 21H2 (OS Build 22000.438)

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/3335359/151621922-6ee354c4-6a7b-4a30-a3ca-34edaaa220d4.png)

**Comment by gave92** [comment]
Merging with #6066
