### ISSUE TITLE
Navigation Pane Hide/Show Keyboard Shortcut

### ISSUE THREAD

**Issue by jasonsafir** [files-community/Files#7998]
### Solution/Idea

Would be useful to have the ability to quickly hide and show the sidebar/navigation pane without using the mouse using a keyboard shortcut.

### Alternatives

Just a simple keyboard shortcut such as Ctrl+Alt+S like in macOS Finder!

**Comment by yaichenbaum** [comment]
This issue should be resolved with #8157
