### ISSUE TITLE
List Layout

### ISSUE THREAD

**Issue by gchegr** [files-community/Files#8000]
### What's the Problem?

The application has Columns, Details, Tiles, Icons... but no List view/layout, which is my default view of folders. I have a thousand of them and a big screen, so I’d like to display a lot of them in a list, with no thumbnails displayed

### Solution/Idea

List Layout should be added

### Alternatives

The are no alternatives to this, Columns layout uses only one small portion of the screen

### Files Version

Version: 2.1.2.0 OS Version: 10.0.19042.1466

### Windows Version

Windows 10 Pro 20H2 19042.1466

**Comment by gave92** [comment]
Tracked in #2409
