### ISSUE TITLE
Can't restore deleted file that needs admin

### ISSUE THREAD

**Issue by dippa-1** [files-community/Files#8001]
### Description

When trying to restore a deleted file that required admin privileges, nothing happens.

### Steps To Reproduce

1. Open Files without admin
2. Delete file that requires admin rights
3. Go to Recycle Bin
4. Press restore
5. Nothing happens

### Expected behavior

In default Windows Recycle Bin it asks for admin rights again and restores it.

### Files Version

Version: 2.1.2.0 OS Version: 10.0.22000.434

### Windows Version

Windows 11 Version 10.0.22000 Build 22000

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7963390/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7963391/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #8809
