### ISSUE TITLE
Open In Terminal Button Broken (Weird Naming)

### ISSUE THREAD

**Issue by pc-v2** [files-community/Files#8003]
### Description

![image](https://user-images.githubusercontent.com/58063311/151658540-983f6842-f94b-45b5-8b4f-3c491351fa22.png)

### Steps To Reproduce

1. open Files
2. click 
![image](https://user-images.githubusercontent.com/58063311/151658549-7b0e3ba8-3816-46a4-ba32-13081b058e14.png)
3. voila!
![image](https://user-images.githubusercontent.com/58063311/151658550-4bb76f96-36bc-4777-bda4-6d05474b1f60.png)

### Expected behavior

The text string not broken

### Files Version

2.1.4 (insider)

### Windows Version

22000.469

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7963540/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7963541/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #8008
