### ISSUE TITLE
Chrash when clicking on a path bar item

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#8004]
### Description

*

### Expected behavior

Should go to the folder clicked on in the path bar

### Files Version

2.1.4.0

### Windows Version

10.0.19043.1466

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7963642/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7963643/debug_fulltrust.log)

**Comment by chrs-it** [comment]
+1, easily reproducible.

**Comment by d2dyno1** [comment]
Resolved with #8010
