### ISSUE TITLE
Download folder opens at a wrong group.

### ISSUE THREAD

**Issue by PavelDobCZ23** [files-community/Files#8006]
### Description

When I open Downloads folder, it opens at the "Older" group when selecting option group by date modified.

### Steps To Reproduce

1. Open Files.
2. Go to Downloads folder.
3. Open "Sort" options.
4. Set "Group by" to "Date modified".
5. Open some other folder.
6. Reopen Downloads folder (*In the same tab).
7. It won't open on the top of the folder but instead on the group "Older". (*You need to have files old enough to make sure this group exists as well as a more recent group like "Today".)

### Expected behavior

It should open at the top of the folder with the latest files in a group like "Today".

### Files Version

2.1.2.0

### Windows Version

10.0.22000.438

### Relevant Assets/Logs

https://user-images.githubusercontent.com/62188082/151661863-43c90053-825a-42d3-8eeb-92d4d1388678.mp4

**Comment by yaichenbaum** [comment]
Merging with #6186
