### ISSUE TITLE
Selecting directory from navigation bar crashes Files

### ISSUE THREAD

**Issue by CrypticVader** [files-community/Files#8007]
### Description

Selecting/clicking on any folder on the navigation bar will crash Files.

### Steps To Reproduce

1. Open a folder within any local drive.
2. Now click on any folder on the navigation bar.
3. Files should crash after becoming unresponsive for a second or two.

### Expected behavior

Open the selected folder.

### Files Version

Version: 2.1.4.0 OS Version: 10.0.22000.469

### Windows Version

Windows 11 21H2 22000.469

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7963718/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7963719/debug_fulltrust.log)

**Comment by gave92** [comment]
Tracked in #8004
