### ISSUE TITLE
"Open in terminal" isn't working

### ISSUE THREAD

**Issue by CrypticVader** [files-community/Files#8009]
### Description

Clicking on "Open in terminal" does nothing.
Also, the option is shown in a random language.
![image](https://user-images.githubusercontent.com/61494838/151662364-2dd73a24-545b-468a-a624-ab1ec928c777.png)

The "Terminal Applications" dropdown list is also empty.
![image](https://user-images.githubusercontent.com/61494838/151662380-38ab2f4b-f185-454e-a4d0-b65badecc761.png)

### Steps To Reproduce

1. Open any drive.
2. Click on "Open in terminal" from the ellipsis (...) menu.

### Expected behavior

The selected folder should be opened in the terminal application of choice.

### Files Version

Version: 2.1.4.0 OS Version: 10.0.22000.469

### Windows Version

Windows 11 21H2 22000.469

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7963741/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7963742/debug_fulltrust.log)

**Comment by gave92** [comment]
Could you check what happens in settings if you click "edit terminals" and make any change to the file that open?

**Comment by CrypticVader** [comment]
I tried changing the file and then restarted the app, still the same.

**Comment by yaichenbaum** [comment]
@CrypticVader can you upload your terminal configuration for Files?

**Comment by CrypticVader** [comment]
I tried clearing everything in the terminal configuration file to see if that would fix the issue. I thought the contents of the file would regenerate, but it didn't.

**Comment by CrypticVader** [comment]
This bug is now resolved.
I reset Files through windows app settings and used the export/import settings option in Files to retain my configuration.
Even though it worked, restoring the settings through the zip showed a dialog box in Files saying
![image](https://user-images.githubusercontent.com/61494838/151689433-223beb2c-2423-406c-9134-93259954fad6.png)
Is the terminal configuration file still required now that it functions?

**Comment by yaichenbaum** [comment]
> Is the terminal configuration file still required now that it functions?

Yes, the error is probably because the terminal settings were invalid.

**Comment by CrypticVader** [comment]
I have attached the terminal config, but it currently functions properly.
I do not have the terminal config file when it was bugged.
[terminal.zip](https://github.com/files-community/Files/files/7966308/terminal.zip)

**Comment by yaichenbaum** [comment]
> I have attached the terminal config, but it currently functions properly. I do not have the terminal config file when it was bugged. [terminal.zip](https://github.com/files-community/Files/files/7966308/terminal.zip)

I think we can close this now that we know the issue was caused by a bad configuration.
