### ISSUE TITLE
Bug: Navigating backwards after changing the layout uses the previous layout option

### ISSUE THREAD

**Issue by Rick-HM** [files-community/Files#801]
**Steps to reproduce**
1. Set folder options to apply to all directories
2. Navigate to the `c:` drive and then navigate to a child directory
3. Change the layout mode
4. Navigate backwards and observe that the `c:` drive is using the previous layout even though all directories are supposed to use the same layout

**Requirements**
- Navigating backwards should reload the items with the correct layout

**Comment by duke7553** [comment]
The simple solution is that changing the view mode should clear navigation history.

**Comment by yaichenbaum** [comment]
@duke7553 It would probably be better to remove the previous directory from the stack. Clearing the navigation history is not such a good UX so we should stay away from that.

**Comment by duke7553** [comment]
@yaichenbaum OK. So we should find a way to remove items with a certain layout mode from the navigation stack? In most cases, we'd be clearing out a lot anyways.

**Comment by yaichenbaum** [comment]
@duke7553 We would only need to remove the last one from the stack, what happens is when you change the layout mode, it reloads the directory which adds it to the navigation stack. If we remove the last item from the navigation stack after changing the layout mode, it should prevent this issue. Additionally, when the user does navigate back to a previous directory, we should always navigate back using the correct layout mode.

**Comment by XPoppyX** [comment]
mm currently it doesn't happen anymore

**Comment by yaichenbaum** [comment]
@XPoppyX It depends on whether you have the option to use individual preferences for folders on or off. Keeping this issue open until it's fixed.

**Comment by XPoppyX** [comment]
> It depends on whether you have the option to use individual preferences for folders on or off

i see
