### ISSUE TITLE
Empty context menu

### ISSUE THREAD

**Issue by CrypticVader** [files-community/Files#8011]
### Description

When right-clicking any empty space, the context menu that opens is empty.
![image](https://user-images.githubusercontent.com/61494838/151663023-98eb69fa-3f16-4ef5-9e0f-ef9a42c3a425.png)

### Steps To Reproduce

1. Open any folder/drive
2. Right-click on empty space.

### Expected behavior

A context menu with all options should be displayed.

### Files Version

v2.1.4.0

### Windows Version

Windows 11 21H2 22000.469

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7963766/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7963767/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
Is this an issue in v2.1.2?

**Comment by CrypticVader** [comment]
I believe its been there before I updated to v2.1.4

**Comment by CrypticVader** [comment]
Edit: I incorrectly reported the version of Files, now it is proper.

**Comment by CrypticVader** [comment]
This bug is now resolved.
I reset Files through windows app settings and used the export/import settings option in Files to retain my configuration.
Even though it worked, restoring the settings through the zip showed a dialog box in Files saying
![image](https://user-images.githubusercontent.com/61494838/151689390-c8ca0538-e6c4-45f3-8225-9e030504317e.png)
