### ISSUE TITLE
Add progress ring when loading custom themes in the settings dialog

### ISSUE THREAD

**Issue by CrypticVader** [files-community/Files#8012]
### Description

Custom themes are missing after the latest update.
![image](https://user-images.githubusercontent.com/61494838/151663145-72de129b-acf0-42ea-804e-4adec314afe6.png)

### Steps To Reproduce

1. Open settings.
2. Click on "Custom themes"

### Expected behavior

Show the available custom themes.

### Files Version

Version: 2.1.4.0 OS Version: 10.0.22000.469

### Windows Version

Windows 11 21H2 22000.469

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7963782/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7963783/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
Custom themes can take a couple seconds to load, try waiting a couple seconds before expanding the section.

**Comment by CrypticVader** [comment]
I did wait for several seconds, and Files is installed on an NVMe drive btw.
This issue did get resolved after I reset Files.
