### ISSUE TITLE
Error while opening the properties of files and folders

### ISSUE THREAD

**Issue by kart1ka** [files-community/Files#8017]
### Description

An error occurs while opening the **properties of file/folder** in Windows 11. When I try to open the properties of some file/folder the dialog box opens but **it (dialog box) then freezes** and **nothing is displayed** on the dialog box.

### Expected behavior

I expect the dialog box to open as it does in the native file explorer app in windows 11 and show me the relevant properties.

### Files Version

Version: 2.1.2.0 OS Version: 10.0.22000.466

### Windows Version

Edition	Windows 11 Home Single Language Version	21H2 Installed on	‎19-‎11-‎2021 OS build	22000.466 Experience	Windows Feature Experience Pack 1000.22000.466.0

### Relevant Assets/Logs

![Screenshot (1897)](https://user-images.githubusercontent.com/41051387/151671818-afb45790-fac6-4302-9ef4-407dcf51dd20.png)

**Comment by gave92** [comment]
Are you sure it freezes? It looks like the text is white

**Comment by gave92** [comment]
Merging with #6066
