### ISSUE TITLE
Problem when changing the layout

### ISSUE THREAD

**Issue by Haitham-7** [files-community/Files#8018]
### Description

When changing a file's layout to small icons or tiles, sometimes a black square appears behind random Icons, here is an example:

### **Details layout**
![Details_layout](https://user-images.githubusercontent.com/98659384/151671625-c3760ba6-5734-421c-bd70-92e69e80c2d5.png)

### **Changing to tiles layout:**
![Tiles_Layout](https://user-images.githubusercontent.com/98659384/151671632-11e89eb2-eda8-4be3-b7de-c1f52f9ec379.png)

### **Changing to small icons layout:**
![Small_icons_layout](https://user-images.githubusercontent.com/98659384/151671636-54176670-d869-4762-ab07-95237d66a9d7.png)

### Steps To Reproduce

Just change a file's layout to tiles or small icons

### Expected behavior

a black square appears behind random icons

### Files Version

Version: 2.1.2.0 OS Version: 10.0.19044.1469

### Windows Version

Windows 10 21H2 19044.1469

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7964270/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7964271/debug_fulltrust.log)

**Comment by gave92** [comment]
Merging with #6373

**Comment by gave92** [comment]
Does refreshing the folder make the black background go away?

**Comment by Haitham-7** [comment]
yes! it makes it go away, so it seems that the problem is with the loading process, not with changing the layout.
