### ISSUE TITLE
Application hangs when attempting to add a network drive

### ISSUE THREAD

**Issue by wiktorderelf** [files-community/Files#8019]
### Description

Exactly as the title says

### Steps To Reproduce

1. Call **_Map Network Drive_** window from menu besides drives list in _Home_ screen. (See screenshot)
2. Go through the window, select drive letter, address etc. and click _Finish_

### Expected behavior

Login/password dialog is expected. Instead, the application doesn't respond to any clicking as well as the window cannot be manipulated (i.e. move, close/hide etc.)

The application behaves as expected when adding the drive from context menu in _Network Drives/Network_ folder.

### Files Version

2.1.2.0 from MS Store

### Windows Version

Windows 10 1809 LTSC [Version 10.0.17763.2452]

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/49633257/151673907-9047a48b-64fe-45f5-b80a-4a7d6f19e051.png)

**Comment by gave92** [comment]
Please verify whether a window appears behind Files window.

**Comment by wiktorderelf** [comment]
It seems the login dialog doesn't appear at all.
There's no new entries in alt-tab window list, moving _Map Network Drive_ window outside **Files** so all new windows emerge outside it too doesn't really help. The login dialog doesn't appear after connection message, the last one closes along with _Map Network Drive_ window.

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?
