### ISSUE TITLE
The drives list doesn't update upon drive disconnection/removal

### ISSUE THREAD

**Issue by wiktorderelf** [files-community/Files#8020]
### Description

The disconnected drives (both USB and network ones) still show up in both _Home_ screen and sidebar until the application restarted. Clicking their buttons to open returns 'Drive Unplugged' in-app message.

### Steps To Reproduce

0. Connect the drive. The app should not be running at that moment.
1. (Re-) Start the app.
2. Disconnect the drive. Disconnecting drive from the app menus also reproduces the bug.

### Expected behavior

The respective drives should disappear from the lists.

### Files Version

2.1.2.0 from MS Store

### Windows Version

Windows 10 1809 LTSC [Version 10.0.17763.2452]

### Relevant Assets/Logs

--

**Comment by gave92** [comment]
Does physically removing the drive make the list update?

**Comment by wiktorderelf** [comment]
Neither safe removal nor simple unplugging makes the list update.

**Comment by pritster5** [comment]
This is still a bug in the latest version. Just tested by ejecting the drive via the standard windows eject USB option in the taskbar tray yet the USB still showed up in the Files menu even after refreshing.
