### ISSUE TITLE
Missing icon for Disconnect button in context menu on 1809

### ISSUE THREAD

**Issue by wiktorderelf** [files-community/Files#8021]
### Description

In _Home_ screen, the _**Disconnect**_ option in the drive context menu (see screenshot) has 'tofu' instead of an icon.

### Expected behavior

--

### Files Version

2.1.2.0 from MS Store

### Windows Version

Windows 10 1809 LTSC [Version 10.0.17763.2452]

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/49633257/151675496-2ea16101-8f53-45c7-8410-9d4c17df4d15.png)

**Comment by yaichenbaum** [comment]
@GargDivanshu using [Character Map](https://www.microsoft.com/store/productId/9WZDNCRDXF41), you can browse the Segoe Fluent Icon font to find a good icon to use. Once you found one, you'll need to find the file where the current icon is being used and update it to use the new icon.

**Comment by GargDivanshu** [comment]
@yair100 sure, i will do it

**Comment by GargDivanshu** [comment]
@yair100 i am on windows 7, and it can't be downloaded on this, can there be other way to do it or should i move with other issue?

**Comment by GargDivanshu** [comment]
@yair100 hello, i need to know, since it's my first time, will installing Linux, WSL under windows will help me to work on these projects??

**Comment by jiejasonliu** [comment]
@GargDivanshu You can also try browsing the assets directly [here](https://docs.microsoft.com/en-us/windows/apps/design/style/segoe-ui-symbol-font)

**Comment by esibruti** [comment]
@yair100 
Segoe MDL2 Icons
![image](https://user-images.githubusercontent.com/78214358/161543084-e6f74a71-9893-4123-b562-671de242e925.png)

Segoe Fluent Icons
![image](https://user-images.githubusercontent.com/78214358/161543485-b000a207-2683-46a1-b90a-68be9ec3d25f.png)

**Comment by yaichenbaum** [comment]
@esibruti would you be intrested in openig a pull request?

**Comment by esibruti** [comment]
@yair100 Yes, I can work on that

**Comment by yaichenbaum** [comment]
This issue should be resolved with #8854
