### ISSUE TITLE
the app crashes when clicking on the address bar

### ISSUE THREAD

**Issue by cleuton4k** [files-community/Files#8022]
### Description

the app crashes when clicking on the address bar

### Expected behavior

click on the address bar and go to the desired destination

### Files Version

2.1.4

### Windows Version

windows 10 21h1 64bits

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7964708/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7964709/debug_fulltrust.log)

https://user-images.githubusercontent.com/90144967/151677346-ef1c953b-ca20-4ba0-b349-25bbb4cde382.mp4

**Comment by gave92** [comment]
Thanks for the report. Fixed.
