### ISSUE TITLE
Send to Option

### ISSUE THREAD

**Issue by Ahmad-Hummoody** [files-community/Files#8024]
### What's the Problem?

Add send to option when you right click a file, just like in file explorer.

### Solution/Idea

Add send to option when you right click a file, just like in file explorer.

### Alternatives

I don't have alternatives.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.1.2.0 OS Version: 10.0.19044.1466

### Windows Version

Windows 10 Pro Version	21H2  OS build	19044.1466 

### Comments

Take the feature in file explorer as example

**Comment by gave92** [comment]
Thanks for the report. We currently have no plan to add that option. 
What do you use that menu most? E.g for "send to desktop (create link)", "send to compressed folder" or other?
