### ISSUE TITLE
Files app crashes when navigating dirs

### ISSUE THREAD

**Issue by ajilidali** [files-community/Files#8025]
### Description

The app crashes when navigating directories from the top bar, I have tried the app with default settings, also tried to set it as main file explorer, it didn't change much, here's some footage of the issue, I tried changing directories too in the vid to be sure it is connected to a specific one

https://user-images.githubusercontent.com/40182073/151678383-ab2b2cd6-da8c-4d00-8bb6-42d58aa06208.mp4

### Steps To Reproduce

Open Files
Open Whatever directory you want to open
In the top bar, click any folder that precedes the one you're in
Crashes. 

### Expected behavior

Take me back to the folder I'm clicking on.

### Files Version

Version 2.1.4.0

### Windows Version

Windows 11 Pro, 21H1 Build 22000.318

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7964790/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7964791/debug.log)
Deleted all the logs, and started the app and reproduced it once, so you can directly see what happens.

**Comment by gave92** [comment]
Thanks for the report. This is fixed in latest code.
