### ISSUE TITLE
Crash when dragging files between tabs

### ISSUE THREAD

**Issue by mayfrogs** [files-community/Files#8027]
### Description

Dragging files between tabs seems to crash depending on the file. Seems more likely to happen with larger files, but I have not so far determined what the limit is.

### Steps To Reproduce

1. Open a folder in a new tab
2. Click and drag a file from the first tab into the second tab.

### Expected behavior

The file to be moved or copied into the folder in the second tab.

### Files Version

2.1.2.0

### Windows Version

Windows 10 Home 21H1 19043.1466

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7965132/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7965133/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
@mayfrogs is this still an issue in the preview version? https://files.community/download/preview
