### ISSUE TITLE
File Name Setting - Always Show Full Name

### ISSUE THREAD

**Issue by hl2guide** [files-community/Files#8029]
### What's the Problem?

Currently filenames are truncated and the name column is not wide enough by default.

### Solution/Idea

Please add a "Show full file name" toggle for this (auto-sizes width of name column to correct width).

### Alternatives

Manually setting it. 😢

### Files Version

2.1.2.0

### Windows Version

Windows 10 21H2

**Comment by Josh-65** [comment]
Merging with #9377
