### ISSUE TITLE
Resizing file filter categories does not follow mouse

### ISSUE THREAD

**Issue by BusteanHAN** [files-community/Files#8031]
### Description

![Issue](https://user-images.githubusercontent.com/60746455/151694021-5e770b4e-ecb6-46d5-a35e-e041c179e045.gif)

### Steps To Reproduce

See the gif above

### Expected behavior

The separator should follow the mouse cursor.

### Files Version

Version: 2.1.2.0 OS Version: 10.0.19042.1466

### Windows Version

Windows 10 Pro 20H2 19042.1466

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7965625/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7965626/debug_fulltrust.log)

**Comment by gave92** [comment]
Tracked in #5371
