### ISSUE TITLE
Everything integeration as alternative search engine

### ISSUE THREAD

**Issue by RedIODev** [files-community/Files#8037]
### What's the Problem?

Files does everything I could wish from a file explorer. Tabs, ease of use, good design... but there is 1 thing witch is a dealbraker for me. It uses the windows search. And as we all know that thing is slow and good for nothing. So my idea would be to make an option to change the search to use [Everything](https://www.voidtools.com/). A free alternative search engine with suport for 3th party integration. It searches and finds files instently and is in my opinion the best search running on windows. It would be a great addition in my opinion and I don't think it would be a hard thing to implement for you judging by the brilliant look and feel Files presents itself with.

### Solution/Idea

Add an option in settings to use everything (or other) as the search engine of the search field.

### Alternatives

Add an extra search field for everthing search if installed.

### Priorities

| Capability | Priority |
| High | Medium |
| This proposal will allow end users to use a faster search and better search engine then the windows search | Must |
| This proposal will help users to search faster with Files then the normal explorer | Could |
| This proposal will make Files more atractive to users that use a different file browser with support for different search engines | Could |
| This proposal wont stop users from using normal windows search | Won't |

**Comment by gave92** [comment]
Merging eith #5845
