### ISSUE TITLE
Rounded edges have disappeared (Windows 10)

### ISSUE THREAD

**Issue by Felkha** [files-community/Files#8038]
### Description

The rounded edges of the Files window have disappeared and now look like a standard Windows 10 window. Has happened after restarting PC, reinstalling hasn't fixed it.

### Expected behavior

![Screenshot 2022-01-30 180432](https://user-images.githubusercontent.com/98707287/151711613-41efcedc-2ded-4df1-bccb-42c5526ce007.png)

Files window no longer has it's rounded edges.

### Files Version

Version: 2.1.2.0 OS Version: 10.0.19043.1466

### Windows Version

Windows 10, version 21H1

### Relevant Assets/Logs

![Screenshot 2022-01-30 180432](https://user-images.githubusercontent.com/98707287/151711638-7612ef3f-63c2-41ba-9067-82768717cf35.png)

**Comment by yaichenbaum** [comment]
@Felkha the rounded windows are exclusive to Windows 11.

**Comment by Felkha** [comment]
Sorry, you're right. I could've sworn it was showing rounded last night! It was quite late... apologies and thank you
