### ISSUE TITLE
Add ability to pin other folders to favourites menu

### ISSUE THREAD

**Issue by Felkha** [files-community/Files#8039]
### What's the Problem?

Can't pin folders to favourites menu, can only unpin what is already on there. Would be extremely useful to pin own folders here.

### Solution/Idea

Add 'pin to favourites' option

### Alternatives

N/A

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.1.2.0 OS Version: 10.0.19043.1466

### Windows Version

Windows 10, version 21H1

**Comment by yaichenbaum** [comment]
@Felkha can you send a screenshot of the context menu when right clicking on a folder?

**Comment by gave92** [comment]
Right clicking on a folder should show "Pin to favorites"

**Comment by Felkha** [comment]
My bad! I was right clicking on the Pictures folder here and wasn't getting the full options but if I go into my user folders I can pin that folder from there, sorry!!
![Screenshot 2022-01-30 183157](https://user-images.githubusercontent.com/98707287/151712598-5bfb9583-aac1-42a6-9800-ba1a12297385.png)
