### ISSUE TITLE
Symlink file extensions don't display

### ISSUE THREAD

**Issue by Antyos** [files-community/Files#8040]
### Description

File extensions for symlinks do not display in Files. A symlink to a `.gitconfig` file displays as blank and `.prettierrc.json` displays as `.prettierrc`. Note, I do have "Show file extensions" enabled. 

This seems to be related to #7006.

Additionally, symlinks show as having a filetype of "Shortcut", though this seems intended as of #7006.

### Steps To Reproduce

Navigate to a folder and run the following in Powershell to create a symlink:

```powershell
"foo" | Out-File .foo
New-Item -ItemType SymbolicLink -Target .foo -Path .bar
```

### Expected behavior

Symlinks should display their file extensions and have a file type of `.symlink` (or something clear that it isn't a shortcut).

### Files Version

2.1.2.0

### Windows Version

Windows 10 20H2 19042.1466

### Relevant Assets/Logs

Symlink shown in Files:
![Symlinks in Files](https://user-images.githubusercontent.com/17516195/151711694-9cdcac74-6883-4cb3-a22b-184b4b88e927.png)

Symlinks shown in Explorer:
![Symlinks in Explorer](https://user-images.githubusercontent.com/17516195/151711681-acce2133-3ad5-4c57-8783-c697d055bb61.png)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #8145
