### ISSUE TITLE
Add a Verison checker and update

### ISSUE THREAD

**Issue by qw1324** [files-community/Files#8045]
### Solution/Idea

Can please add a verison check and auto update

### Alternatives

Can please add a verison check and auto update

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
@qw1324 can you add some more context?

**Comment by qw1324** [comment]
> @qw1324 can you add some more context?

just like if user's Files version is outdate then can auto update or manual update


when user opened Files then check the version or add a check version button on the Version page

**Comment by yaichenbaum** [comment]
@qw1324 the app auto updates through the store, but there is also a popup notifying users if there is an update available.
