### ISSUE TITLE
Compact display (rows are more tightly spaced)

### ISSUE THREAD

**Issue by ctrlbrk42** [files-community/Files#8048]
### What's the Problem?

The default Windows Explorer has a feature called "decrease space between items (compact view)" which really increases usability dramatically for me.

### Solution/Idea

Please implement a compact listing option, where the spacing between each row is much tighter, so that more rows can fit in the same screen real estate.

### Alternatives

The only alternative is using Windows Explorer!

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.2.0

### Windows Version

Windows 11 Insider Dev 10.0.22543.1000

**Comment by yaichenbaum** [comment]
Merging with #1940
