### ISSUE TITLE
Unable to undo "set files as default file explorer setting"

### ISSUE THREAD

**Issue by DerpFromAbove** [files-community/Files#8050]
### Description

Some time ago, I ticked the "set files as default file manager" option in the experimental settings

Because I was unsatisfied with it, I attempted to get rid of it. I ticked the setting to "off" as instructed and deleted the app. When I attempted to use the default W11 file explorer right after, I got an error message. Thankfully, I was able to re-install files but now I am forced to keep using a file explorer I am very dissatisfied with till I finally bring myself to do a clean install of my OS

Fix this, pretty please.
A "set this as default" setting shouldn't require a clean install to undo...

### Steps To Reproduce

1) Go to the "experimental" section under "settings"
2) Toggle on the "set files as default file explorer"
3) Toggle it back off
4) Uninstall files
5) Open the default Windows file explorer

Maybe throw in a restart or two after steps 2 and 3. 

### Expected behavior

An error message will pop up that essentially tells you the W11 file explorer is not there any more. It's been a while so sorry for not having something more specific but I don't dare to reproduce it 

### Files Version

The most recent version of a week ago

### Windows Version

Windows 11 Pro 21H2 22000.434

### Relevant Assets/Logs

I do not have it and as I said before, I do not want to risk bricking my PC just to reproduce this bug

**Comment by yaichenbaum** [comment]
> A "set this as default" setting shouldn't require a clean install to undo...

An experimental option with a warning to turn it off before removing the app shouldn't need any additional explanation. That being said, you can find instructions for reverting the changes in #7626.
![image](https://user-images.githubusercontent.com/39923744/151733883-fd0c4bcc-6873-4249-8754-0dbf527255cc.png)
