### ISSUE TITLE
Give a GUI Interface to Create Custom Theme

### ISSUE THREAD

**Issue by Pratham-Galaxy** [files-community/Files#8053]
### What's the Problem?

It is difficult for a normal user to create custom theme in Files

### Solution/Idea

So please make a gui interface to make it easy

### Alternatives

It is difficult for a normal user to create custom theme in Files, so please make a gui interface to make it easy

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.5.0

### Windows Version

Window 11 21H2 22000.469

**Comment by yaichenbaum** [comment]
Merging with #5916
