### ISSUE TITLE
Files crashes when renaming an item in the tiles layout

### ISSUE THREAD

**Issue by inarrr** [files-community/Files#8055]
### Description

After 5 to 10 mins of Files running and unused, the applications crashs with no error code.

### Steps To Reproduce

1. Open Files.
2. Let it run.

### Expected behavior

Not crashing since I'm not using it.

### Files Version

2.1.5.0

### Windows Version

Windows 11 Professionnel 21H2 22000.434

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7968569/debug.log)
![image](https://user-images.githubusercontent.com/87371558/151748955-d5ac8f8d-4f21-44a3-8cf9-d462d66e486b.png)

**Comment by yaichenbaum** [comment]
@inarrr are you using a custom theme?

**Comment by yaichenbaum** [comment]
@inarrr does resetting the app fix the issue?

**Comment by inarrr** [comment]
@yair100 I'm not using any theme.
How can I reset the app ?
Thank you.

**Comment by DutchEclipse** [comment]
App crashes for me aswell, but only after renaming files.

Resetting doesn't work.

**Comment by DutchEclipse** [comment]
![image](https://user-images.githubusercontent.com/83969413/151792782-40f71769-9a7d-439a-a206-c4e581314abd.png)
If any more information is required just let me know.

**Comment by yaichenbaum** [comment]
@inarrr you can reset the app from the app page in the Windows Settings app.

**Comment by DutchEclipse** [comment]
> @inarrr you can reset the app from the app page in the Windows Settings app.

Resetting doesn't work at all, even crashes in a clean reinstall of windows in a VM

**Comment by yaichenbaum** [comment]
@DutchEclipse is there a specific action that causes the app to crash?

**Comment by DutchEclipse** [comment]
> @DutchEclipse is there a specific action that causes the app to crash?

Alwaya happens when renaming a file in tiles modez in other layouts it works fine. 

But this has been known already right?

**Comment by yaichenbaum** [comment]
We had a potential fix but it doesn't seem to have worked.

**Comment by yaichenbaum** [comment]
Merging with #7996
