### ISSUE TITLE
Add support for 4 finger windows shortcut for going forward and backward

### ISSUE THREAD

**Issue by shockproof22** [files-community/Files#8059]
### What's the Problem?

I've set up my advanced touchpad settings for 4 fingers to be, swipe left for backward navigation and swipe right for forward.
This doesn't seem to work in your app, works everywhere else just fine; really stops me from using this wonderful app as my daily driver cause of this single thing.

I am not really sure what's causing this issue, app not supporting 4 finger gestures or not allowing forward or backward nav?
regardless, please add support for this ASAP!!

screenshot showing my touchpad settings for 4 fingers,
![S (112) (13-24)](https://user-images.githubusercontent.com/60001922/151757874-2b2e5808-c689-4f03-a820-f1766e8b75c6.png)
 

### Solution/Idea

Simply add this feature allowing me to go forward and backward using my four finger gesture setup.

### Alternatives

No alternatives are there unfortunately, you have to fix this

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.1.5.0 OS Version: 10.0.22000.434

### Windows Version

WIndows 11 version 21H2 (OS Build 22000.434)

**Comment by gave92** [comment]
Merging with #7702, €6804
