### ISSUE TITLE
Terminal Error

### ISSUE THREAD

**Issue by skykeyjoker** [files-community/Files#8060]
### Description

Can not find terminal in 2.1.5.0.

### Expected behavior

terminal!!!

### Files Version

2.1.5.0

### Windows Version

Windows 11 21H2 22000.469

### Relevant Assets/Logs

![error](https://user-images.githubusercontent.com/17134346/151763382-773078fe-daeb-49c1-b2fd-791e61028fdb.png)

**Comment by gave92** [comment]
Please try to reset the app from Window Settings. Before that could you upload the terminals config file?

**Comment by skykeyjoker** [comment]
> Please try to reset the app from Window Settings. Before that could you upload the terminals config file?

{
  "version": 1,
  "DefaultTerminalName": "PowerShell",
  "terminals": [
    {
      "name": "CMD",
      "path": "cmd.exe",
      "arguments": "",
      "icon": ""
    },
    {
      "name": "PowerShell",
      "path": "powershell.exe",
      "arguments": "-noexit -command \"cd '{0}'\"",
      "icon": ""
    },
    {
      "name": "Windows Terminal",
      "path": "wt.exe",
      "arguments": "-d .",
      "icon": ""
    }
  ]
}

**Comment by yaichenbaum** [comment]
Merging with #8100
