### ISSUE TITLE
After settings Files as default file manager, i am facing issue while opening control panel

### ISSUE THREAD

**Issue by Pratham-Galaxy** [files-community/Files#8063]
### Description

After settings Files as default file manager.

Whenever i open control panel 'Files' automatically open and close after few seconds.

### Steps To Reproduce

1. open control panel
2. then you will notice Files open and close after few seconds

https://user-images.githubusercontent.com/97865710/151767726-0e1b17f6-d776-403d-81be-3da018859502.mp4

### Expected behavior

I don't like that Files open when i am trying to open control panel. so please fix this issue.

### Files Version

2.1.5.0

### Windows Version

Window 11 21H2 22000.469

### Relevant Assets/Logs

https://user-images.githubusercontent.com/97865710/151767726-0e1b17f6-d776-403d-81be-3da018859502.mp4

**Comment by gave92** [comment]
That is expected, as Files can't show the control panel. We're looking to avoid opening Files though.
