### ISSUE TITLE
Can you made Preview Pane that is not integrated to Files

### ISSUE THREAD

**Issue by Pratham-Galaxy** [files-community/Files#8064]
### Solution/Idea

I sometimes use dual pane for multitasking but at that time opening preview pane consume more space as it is intergrated to Files.

Can you make Preview Pane that will work as a separate window, it will be helpful.

### Alternatives

I sometimes use dual pane for multitasking but at that time opening preview pane consume more space as it is intergrated to Files.

Can you make Preview Pane that will work as a separate window, it will be helpful.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.5.0

### Windows Version

Window 11 21H2 22000.469

**Comment by gave92** [comment]
Perhaps you could install QuickLook which works with Files and shows a preview as a separate window by pressing Space.
