### ISSUE TITLE
Not able to open file explorer even after disenabling defult explorer option

### ISSUE THREAD

**Issue by samarthiith** [files-community/Files#8065]
### Description

Hi,
I am not able to open file explorer anymore even after the setting shows file explorer is disabled as default app. Not able to toggle the setting too. Kindly provide some temporary fix. 
best,
Samarth 

### Expected behavior

to be able to toggle default explorer option

### Files Version

2.1.5.0

### Windows Version

19042.1466

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/9819174/151772151-9ccb4fb1-a460-4bea-9ac9-12562c0e342e.png)
even thou here it shows that files is not the default option, it still is.

**Comment by gave92** [comment]
To revert to explorer you can use the UnsetFilesAsDefault.reg file in this archive.
https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip.
Please let us know if it fixes the issue.

**Comment by samarthiith** [comment]
The toggle option was not working. But a file did! thanks a ton! 
btw, amazing product! Had been looking for something like this for a while!
