### ISSUE TITLE
MS Office previews

### ISSUE THREAD

**Issue by RichardMiami** [files-community/Files#8067]
### What's the Problem?

I can not see previews of my MS Office files - Word, Excel, PowerPoint

### Solution/Idea

Enable the MS Office preview handlers

### Alternatives

I have no alternative suggestion

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |
This proposal will allow end users to use the tool.

### Comments

Thank you for considering this request

**Comment by gave92** [comment]
Tracked in #4041
