### ISSUE TITLE
Delete warning panel can be turned on/off when deleting item/items

### ISSUE THREAD

**Issue by arch12pi** [files-community/Files#8069]
### What's the Problem?

Can we have a function to turn off/turn on the delete warning panel? 
My work is required to select and delete items thousands of times a day and for now, it is super slow when a warning shows up whenever I delete a file

### Solution/Idea

An option in **Files and Folders** to turn on/off warning panel whenever deleting an item

### Alternatives

An option in **Toolbar** to turn on/off warning panel whenever deleting an item

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end-users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end-users to accomplish Z | Won't |

**Comment by gave92** [comment]
You can find that option in Files settings > Preferences

**Comment by arch12pi** [comment]
> You can find that option in Files settings > Preferences

oh my bad, thank you so much !
