### ISSUE TITLE
Network drive

### ISSUE THREAD

**Issue by TaraRedDiamond** [files-community/Files#8070]
### What's the Problem?

It is not available in Files when using the Windows Network Sharing Folder function.

### Solution/Idea

Please make it possible to open the Windows Basic Function Network Sharing folder.

### Alternatives

Please make it possible to open the Windows Basic Function Network Sharing folder.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by gave92** [comment]
Could you post a screenshot to show what you're referring to?
