### ISSUE TITLE
"Open file location" only works once

### ISSUE THREAD

**Issue by RoyFurious** [files-community/Files#8071]
### What's the Problem?

"Open file location" only works once

### Solution/Idea

Fix it so that right-clicking on a file ALWAYS opens the file location.

### Alternatives

Remove the feature if it can only work once.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by gave92** [comment]
I assume you set Files as default file explorer right? Could you confirm whether it really works only once or if it takes a long time to work (several seconds) the second time?
