### ISSUE TITLE
Create link on right-click drag

### ISSUE THREAD

**Issue by RoyFurious** [files-community/Files#8072]
### What's the Problem?

In Explorer, you could create link by right-clicking a file or folder and dragging into another application, such as Outlook.  You can't do this in Files.

### Solution/Idea

Add this functionality to Files.

### Alternatives

You can copy a link to an item and the paste a link into Outlook, but it is a multistep process.  Why can File Explorer do it as a right-click function, but Files can't?

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by gave92** [comment]
You can drag while keeping Ctrl and Shift key pressed, it should create a link

**Comment by gave92** [comment]
Merging with #1396
