### ISSUE TITLE
Properties dialog is not accessible in light theme when system theme is set to dark

### ISSUE THREAD

**Issue by niklouf** [files-community/Files#8073]
### Description

properties with dark theme is not readable (both file and folder)
check screenshot
![image](https://user-images.githubusercontent.com/23717463/151824964-7afeb923-b76e-4492-9b88-2eecb4967bb4.png)

### Expected behavior

readable properties

### Files Version

Version : 2.1.5.0 OS Version: 10.0.22000.469

### Windows Version

WIndows 11 up-to-date

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7972076/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7972077/debug.log)

**Comment by gave92** [comment]
Tracked in #6066
