### ISSUE TITLE
Search is not finding something it should

### ISSUE THREAD

**Issue by serg06** [files-community/Files#8075]
### Description

When I have a file called `newv28-Daniel-help.pdf`, and I search for `daniel`, it doesn't show up.

### Steps To Reproduce

1. Create a file called `newv28-Daniel-help.pdf`
2. Search for `daniel`
3. It won't show up
4. Click `Search unindexed items`
5. It still doesn't show up

### Expected behavior

It should show up.

### Files Version

Version: 2.1.5.0 OS Version: 10.0.19044.1469

### Windows Version

Windows 11 21H2 19044.1469

### Relevant Assets/Logs

.

**Comment by Josh-65** [comment]
Files currently uses windows search indexing to find files. if you search for it in normal file explorer with the same name and folder location does it show up

**Comment by serg06** [comment]
@Josh-65 It doesn't show up in normal file explorer either.

**Comment by Josh-65** [comment]
Windows will be the issue then. The devs have talked about looking for a better alternative for future update. For now you can open windows index and add your drive or folder to the index list and try again when it finished. Or try the enhanced indexing in the settings.

**Comment by Talisman39ar** [comment]
Down at the bottom of the Preferences pane there's a toggle to turn on "Show unindexed items when searching" - try flipping that on (assuming it's currently off) and see if it helps also - it has for me
