### ISSUE TITLE
Files crashes when renaming a item

### ISSUE THREAD

**Issue by DutchEclipse** [files-community/Files#8076]
### Description

Whenever you rename a file be it a .txt .mp4 or whatever, files just simply crashes when renaming it. Worst thing is that it doesn't even save the new file name.

### Steps To Reproduce

1. Open files
2. Find a file you want to rename
3. Rename the file
4. Wait for 3 seconds
5. Files crashes.

### Expected behavior

It renames the file without crashing

### Files Version

2.1.5.0

### Windows Version

Windows 11 Pro  21h2 Build 22000 434

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7972547/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7972548/debug_fulltrust.log)

**Comment by Josh-65** [comment]
What view are you trying on Grid, tiles, detail?

**Comment by gave92** [comment]
Same as #7996
