### ISSUE TITLE
.webm preview are not working

### ISSUE THREAD

**Issue by soredake** [files-community/Files#8077]
### Description

![изображение](https://user-images.githubusercontent.com/5204968/151836207-ef2ffed5-5240-4881-8af8-0b7d66b8bd72.png)

Webm preview not working.

### Steps To Reproduce

1. Install version 2.1.5.0 on windows 11 pro
2. navigate to folder with .webm
3. preview not working.

### Expected behavior

.webm preview working

### Files Version

Версия: 2.1.5.0 OS Version: 10.0.22000.469

### Windows Version

Windows 11 pro 21H2 22000.469

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7972573/debug.log)

**Comment by gave92** [comment]
Could you show a screenshot of the same folder in file explorer? Do the thumbnails show there?

**Comment by soredake** [comment]
> Could you post a screenshot of the same folder in file explorer? Do the thumbnails show there?

Yes, they are shown, i will post screenshot later.

**Comment by gave92** [comment]
Thanks for the additional info. Did you have to install some software to show the thumbnails in Explorer for .webm? If not, what have you set as default program to open .webm?

**Comment by soredake** [comment]
> Thanks for the additional info. Did you have to install some software to show the thumbnails in Explorer for .webm? If not, what have you set as default program to open .webm?

They are working out of the box IIRC, default program for .webm is [mpv.net](https://github.com/stax76/mpv.net)

**Comment by LolicoreExpress** [comment]
Can confirm. Exact same problem here since v2.1.5.0.

**Comment by Josh-65** [comment]
Theres also #8376, #8339, #8320 and #8202 with missing thumbnails

**Comment by yaichenbaum** [comment]
Merging with #8376

**Comment by Piloton1231** [comment]
Hi, I'm looking for a solution to my problem!
This may have been solved by now, but I solved it as follows.

In my case, I did not have access to "HKEY_CLASSES_ROOT\.webm\ShellEx" and could not delete it.

However, I succeeded in deleting the .webm file by using RegmagiK.

Now I can see the previews with Icaros software!
