### ISSUE TITLE
Bug: Updating a folder outside Files loses selection

### ISSUE THREAD

**Issue by warpdesign** [files-community/Files#8078]
### What's the Problem?

- Open the folder `foo` which contains several files/folders in Files
- Select a few files
- Switch to Windows File Explorer or the Terminal and create a new directory inside the `foo` folder

=> This will refresh the folder in Files and by doing so, the selection is lost.

### Solution/Idea

Refreshing a directory outside of Files should keep selected files in Files.

### Alternatives

n/a

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version 2.1.5.0

### Windows Version

version 10.0.19044.1503

**Comment by warpdesign** [comment]
Note: if the selected file is renamed, the selection should be kept as well, ie:

- I select the `foo` file
- the file `foo` is renamed to `bar`

I am expecting that:
- the directory is refreshed
- `bar` (which was renamed from `foo`) becomes selected

**Comment by yaira2** [comment]
Merging with #2856
