### ISSUE TITLE
Files crashes when i right click on empty area 

### ISSUE THREAD

**Issue by Pratham-Galaxy** [files-community/Files#8079]
### Description

![Screenshot 2022-01-31 223314](https://user-images.githubusercontent.com/97865710/151839046-399212ca-3ae4-42c5-b913-9c43b690f43d.png)

### Steps To Reproduce

right click on empty space in Files

Files crashes

### Expected behavior

Files should not crash when right click

### Files Version

2.1.5.0

### Windows Version

Window 11 21H2 22000.469

### Relevant Assets/Logs

![Screenshot 2022-01-31 223314](https://user-images.githubusercontent.com/97865710/151839046-399212ca-3ae4-42c5-b913-9c43b690f43d.png)

**Comment by Josh-65** [comment]
You will need to upload the logs files. You can get them in files settings > about > open log folder.

**Comment by Pratham-Galaxy** [comment]
[debug.log](https://github.com/files-community/Files/files/7979654/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7979655/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
@Pratham-Galaxy is this still an issue in v2.1.13?
