### ISSUE TITLE
Loading of C: drive gets blocked by network request 

### ISSUE THREAD

**Issue by yatima1460** [files-community/Files#8080]
### Description

When getting the files located in C:\ Files will be stuck if there is already a Network drives listing loading

I have no network drives setup, just the PC name appears with some shared folders inside

I have a fast NVMe so it's not a disk loading problem

### Steps To Reproduce

1. Click Network drives\Network as first action
2. Click Drives\C:\ instantly
3. Need to wait about 20-25 seconds before C:\ appears

### Expected behavior

1. Click Network drives\Network as first action
2. Click Drives\C:\ instantly
3. Files would show instantly C:\ file listing

### Files Version

Version: 2.1.5.0 OS Version: 10.0.19044.1466

### Windows Version

Windows 10 Pro 21H2 19044.1466

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/7545597/151847044-3109a664-7d66-4706-a98a-f6f566394bdf.png)

**Comment by hez2010** [comment]
We currently haven't implemented the cancellation for network devices, in this case you may open a new tab for C: drive loading.

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
