### ISSUE TITLE
Text appareance

### ISSUE THREAD

**Issue by TreviSyn** [files-community/Files#8081]
### Description

When select a file o directory text change; when de-select text doesn't return to "normal style"

### Expected behavior

Text should return to previous state

### Files Version

2.1.5.0

### Windows Version

windows 10 21h2

### Relevant Assets/Logs

nothing to add

**Comment by Josh-65** [comment]
Can you screenshot both stats of this

**Comment by TreviSyn** [comment]
![original](https://user-images.githubusercontent.com/91346889/151877487-29f28cdd-8780-4cb6-b5fc-57f514c0e3bb.JPG)
![select](https://user-images.githubusercontent.com/91346889/151877498-2924614c-29ba-440f-ad1f-51a2b773caed.JPG)
![deselect](https://user-images.githubusercontent.com/91346889/151877506-280c14a8-6e71-4c78-9222-ba45d19e5892.JPG)
i hope that difference is visible ;)

**Comment by yaichenbaum** [comment]
@TreviSyn is this also an issue on Windows 11?

**Comment by TreviSyn** [comment]
I don't know, sorry. I can't try Windows 11

**Comment by yaichenbaum** [comment]
@TreviSyn we've gotten similar reports from users on Windows 10. Unfortunately it seems to be a WinUI behavior so unless it's fixed from WinUI, I don't think we'll have a fix for this issue.

**Comment by TreviSyn** [comment]
I don't know if i can make a comparison with another similar software... However, it hasn't this visual bug...
