### ISSUE TITLE
Add drag and drop via pen support

### ISSUE THREAD

**Issue by Noisemagician** [files-community/Files#8083]
### What's the Problem?

Hi,

I work with Wacom one tablet and I can't drag images from my folder to photoshop instead of that it scrolls up or down. Could you enable drag and drop with pen and tablet.

### Solution/Idea

Enable drag and drop of items in folders.

### Alternatives

If possible enable both functions, dragging and dropping and scrolling.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Windows Version

Edition	Windows 10 Home Version	21H1 Installed on	‎16/‎09/‎2021 OS build	19043.1466 Experience	Windows Feature Experience Pack 120.2212.3920.0

### Comments

Thank you for fixing problems like thumbnails not loading, it works like a charm now.

**Comment by yaichenbaum** [comment]
Merging with #2520
