### ISSUE TITLE
Synology Drive Client

### ISSUE THREAD

**Issue by russh26** [files-community/Files#8084]
### What's the Problem?

I use the Synology Drive Client to access my works NAS server. In the default windows file explorer this appears as an additional drive (much like DropBox or Google Drive) that can be easily accessed. However this does not appear in the Files explorer.

### Solution/Idea

Integrate Synology Drive Client to be included in the 'Cloud Drives'

### Alternatives

Currently I have to open the native file explorer or access it via my toolbar.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.5.0

### Windows Version

Windows 11 Home 22000.438

**Comment by MystikReasons** [comment]
+1 for me

**Comment by yaichenbaum** [comment]
This issue should be resolved with #9188
