### ISSUE TITLE
[Feature Request] Feature to isolate each tab in its own process/instance to reduce application crashes

### ISSUE THREAD

**Issue by rihards-simanovics** [files-community/Files#8086]
### What's the Problem?

It's the second time I have encountered the same frustrating issue where I would have 5~6 tabs open with the correct scroll position in each tab for quick access to the right files I need, and then the entire app crashes all of them.

As I already mentioned in issue #8085, I've encountered that each time I relocate from child dir to a parent dir, that Files instance would crash, and if it so happens that you are not running many separate Files instances, but instead, only have two, with one of them having a few tabs open. If that instance then crashes, so will the open tabs.

This is not the first time I mentioned this, as I already hinted this in a previously closed feature request #7699, which was (broadly speaking) about making each Files instance containerised in a separate process. Still, I also briefly spoke of early browsers' issue where if one website (tab) were to misbehave, the entire browser would crash, an issue that we are now experiencing here.

### Solution/Idea

As mentioned in the previous issue, I would suggest looking up how the Chromium browser has solved the issue and recreating it here.

### Alternatives

I guess you can say, "If you want a stable experience, ditch the tabs and use separate files instances", but that would not be right since tabs are one of the selling points for this app and are very useful if you are on a low res single monitor which is every laptop and home PC.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to provide a better user experience | Must |
| This proposal will allow end-users to have a more stable experience which if you are using tabs is not quite there, should anything go wrong one tab the entire application closing all other tabs along with it | Must |

### Files Version

Version: 2.1.4.0 OS Version: 10.0.22543.1000

### Windows Version

Edition Windows 11 Business Insider Preview Version Dev Installed on ‎29/‎01/‎2022 OS build 22543.1000 Experience Windows Feature Experience Pack 1000.22543.1000.0

**Comment by yaichenbaum** [comment]
@rihards-simanovics there are currently two processes, the full trust process, and the main app process. Crashes in the full trust process will limit functionality but it won't bring down the rest of the app. The crashes that close the app are in the main process and creating a separate process for each tab wouldn't help with this issue.
We're tracking an issue to restore the scroll position when restarting the app and we're also working on improving stability. Preview builds are going to have crashes so you might want to switch to the stable branch if you're using this on your main device.

**Comment by rihards-simanovics** [comment]
@yair100, I see. Thanks for your reply. In such a case, please accept my apologies. I am still figuring out the code and hope I will be able to contribute in the future. As for the position tracking and restoring app with all tabs is excellent news!
I believe that using an unstable version of the software in daily use is a necessary trade-off in the requirement of finding issues rather than waiting until the end-user finds them and hopefully submits full feedback with a debug log.
It also simplifies the triaging process for the issue, "if I encountered it during normal use, so will the end-user" therefore, I must fix it first.

Thanks again for your reply.

**Comment by yaichenbaum** [comment]
@rihards-simanovics I agree, the preview builds helps us find and fix issues before they are released to the stable branch. We're currently working on a refactor that will improve stability and make it easier to work with the code base. Is this something you would be interested in helping with?

**Comment by rihards-simanovics** [comment]
@yair100 I have attempted to already, but I am not sure if what I see in the VS2022 visualiser for XAML view is what I should expect. Still, I'm afraid my last app development experience was back in college with the visual basic, haha. I am primarily on web dev now, and I will need to have a good understanding before I begin contributing anything.

I believe we spoke before on Discord. I am the CapsLock1980 or RichMan3215#7462. I can pm you on Discord, and we can discuss this further.
