### ISSUE TITLE
Files is Unable to Drag & Drop Files Into Folder Within Same Directory

### ISSUE THREAD

**Issue by Gryzle** [files-community/Files#8087]
### Description

FIles is unable to use drag and drop to move files into a folder that is in the same directory as the file being moved.

### Steps To Reproduce

1. Create a File
2. Create a Folder (In the same directory as the previously created File)
3. Attempt to drag the File into the Folder

### Expected behavior

Files should be able to move the file into the folder without issues.

### Files Version

Version: 2.1.5.0 OS Version: 10.0.22000.469

### Windows Version

Windows 11 22000.469

### Relevant Assets/Logs

![Files-2022-01-31](https://user-images.githubusercontent.com/51198087/151895806-ea2b9ae1-73fb-477b-ac2c-5b73e9c0d5bc.gif)

**Comment by yaichenbaum** [comment]
Can you add the log files?

**Comment by Gryzle** [comment]
[debug.log](https://github.com/files-community/Files/files/7975134/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7975135/debug_fulltrust.log)

**Comment by itsWindows11** [comment]
It seems that the list item wasn't selected when they tried to drag & drop to the destination folder, I might try to look into this.

**Comment by itsWindows11** [comment]
Update: I think something is wrong with the binding in AllowDrop, removed the binding and that fixed it.

**Comment by yaichenbaum** [comment]
@gave92 is this still an issue?

**Comment by gave92** [comment]
This was recently fixed.
