### ISSUE TITLE
Delete Prompt is Extremely Delayed when Using a Shared Network Drive

### ISSUE THREAD

**Issue by Gryzle** [files-community/Files#8088]
### Description

Files hangs when attempting to delete something on a remote drive.

### Steps To Reproduce

1. Connect to a Shared Network Drive
2. Attempt to delete a file or a group of files

### Expected behavior

Files should bring up the prompt immediatly, and if needed, loading times should occur after the user has already made their choice.

### Files Version

Version: 2.1.5.0 OS Version: 10.0.22000.469

### Windows Version

Windows 11 22000.469

### Relevant Assets/Logs

![Files-2](https://user-images.githubusercontent.com/51198087/151896297-2fcb395d-7bae-437c-84da-933880fa4558.gif)

**Comment by yaichenbaum** [comment]
Merging with #6502
