### ISSUE TITLE
Changes to files within a Shared Network Drive aren't reflected in Files

### ISSUE THREAD

**Issue by Gryzle** [files-community/Files#8089]
### Description

When changes are made (by Files), the changes don't visually change unless it's manually refreshed.

### Steps To Reproduce

1. Connect to a Shared Network Drive
2. Modify a file (Create, Delete, etc.)
3. Changes don't appear
4. Refresh the page
5. Changes appear

### Expected behavior

Files should automatically refresh or update files on a network drive that have been modified by Files.

### Files Version

Version: 2.1.5.0 OS Version: 10.0.22000.469

### Windows Version

Windows 11 22000.469

### Relevant Assets/Logs

![ezgif com-gif-maker](https://user-images.githubusercontent.com/51198087/151897279-7843d525-b992-4041-8092-6c4b0a9579f0.gif)

**Comment by gave92** [comment]
Tracked in #5869
