### ISSUE TITLE
No title in tab when in "Documents" library

### ISSUE THREAD

**Issue by austin-dudzik** [files-community/Files#8091]
### Description

When navigating to the "Documents" library from within the link in the sidebar, the tab title appears blank. This behavior does not occur for Music, Pictures, and Videos, and does not occur when opening "Documents" from the "Home" tab. It appears to only occur when accessing the page from the sidebar.

### Steps To Reproduce

Open the "Documents" library from the sidebar and check the tab title.

### Expected behavior

When selecting the "Documents" library from the sidebar, the tab should have a title.

### Files Version

Version: 2.1.5.0 OS Version: 10.0.22000.434

### Windows Version

Windows 11 21H2 22000.434

### Relevant Assets/Logs

Preview of the tab area with all libraries opened from the sidebar (In order: Documents, Music, Pictures, Videos)

![image](https://user-images.githubusercontent.com/65981261/151917118-50319e6c-4014-47dd-8581-f5a0d1b15c6c.png)

**Cannot pinpoint when this bug first started, but it was also noticed in Version 2.1.3 before updating to the latest version.**

**Comment by yaichenbaum** [comment]
This issue should be resolved with #8107
