### ISSUE TITLE
Classic Control Panel unavailable while using "Set Files as the default file manager"

### ISSUE THREAD

**Issue by Cm4nXD** [files-community/Files#8092]
### Description

The control panel is part of the original windows file explorer, and when attempting to open the classic windows control panel, files presents the user with the message "Drive Unplugged", "NotAFolder". Since the control panel is a part of the original file explorer in windows, as long as Files is set as the default file manager, the control panel is unavailable.

### Steps To Reproduce

1. Enable "Set Files as the default file manager" under experimental features in files app
1. Use any method of launching control panel

### Expected behavior

Alternatively, Files could somehow program an exception to this behavior and launch the original file explorer program when launching the windows control panel, or by somehow programming the control panel into files app.

### Files Version

Version: 2.1.5.0 OS Version: 10.0.22000.469

### Windows Version

Windows 11 Pro 21H2 22000.469

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7976136/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7976137/debug.log)

**Comment by yaichenbaum** [comment]
@Cm4nXD this seems to be hit or miss, which version of Files did you use to set the app as the default?

**Comment by Cm4nXD** [comment]
2.1.5.0

**Comment by yaichenbaum** [comment]
@Cm4nXD can you try toggling the setting on and off again?

**Comment by tsakalerisk** [comment]
Had the same issue after updating to 2.1.5.0. Disabling "use Files as the default file manager", and then reinstalling the app seems to have fixed it.
