### ISSUE TITLE
Please include the compact view as a standard feature of Windows.

### ISSUE THREAD

**Issue by nopitech** [files-community/Files#8095]
### What's the Problem?

I am currently working with 3DCG software. The number of image files to be output is lightly over 1000. And to manage the scenes, I use a large number of directories to separate the classification.

The standard Windows Explorer has a feature called Compact View, which allows you to narrow the width between lines. This is a very useful feature for people who manage a large number of files because it allows more items to be displayed on the screen.
However, this feature is not available in Files. Due to the large width between lines and the small number of items that can be displayed at a time, unnecessary scrolling occurs, which is so troubling that I cannot use it as my main explorer.

### Solution/Idea

Provide an option to narrow the width between lines.
(Compact view function of windows)

### Alternatives

Please provide an option to narrow the line spacing.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.5.0

### Windows Version

Windows 11 Insider Preview 22543.1000 (rs_prerelease)

### Comments

![image](https://user-images.githubusercontent.com/32907066/151967294-2c5a0b75-adf5-48cf-abf8-6143790ff950.png)
![image](https://user-images.githubusercontent.com/32907066/151967444-10927d5e-6ff6-49aa-b1f5-c385f37b36bb.png)

**Comment by gave92** [comment]
Tracked in #1940
