### ISSUE TITLE
i have to select each action after i copy or move multiple files,to other folder with the same files

### ISSUE THREAD

**Issue by dimitakhs1** [files-community/Files#8097]
### What's the Problem?

i don't see batch select,to replace,ignore or rename same multiple files i copy or move,so i have to do this to each file!

https://user-images.githubusercontent.com/85411841/151989697-28ff3dcc-472c-4e8a-a658-3e481731c693.mp4

### Solution/Idea

i don't have any

### Alternatives

This exists on Windows Files

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.5.0

### Windows Version

Windows 11 21H2 22000.469

**Comment by Josh-65** [comment]
You can use ctrl + A then right click to apply actions to all. A better way is beeing discussed at #5030

**Comment by gave92** [comment]
For now you can select replace for one, then right click on that file and select apply to all.
Pressing Ctrl+A and selecting replace for any file also works.
A better UI is in the work.
