### ISSUE TITLE
Terminal applications dropdown menu is empty

### ISSUE THREAD

**Issue by CrypticVader** [files-community/Files#8100]
### Description

The "Open in <terminal-of-choice>" doesn't work.
And the option is missing from the context menu  as well.
![image](https://user-images.githubusercontent.com/61494838/152028084-e150bffb-5919-4e2a-beb6-46142a2efa53.png)
![image](https://user-images.githubusercontent.com/61494838/152028092-edda7f82-55ff-4dc8-adbd-6a8fd5bcd9eb.png)

### Steps To Reproduce

1. Open any drive.
2. Click on the ellipsis menu.

### Expected behavior

Selecting the option should open the folder in the terminal application of choice, and the dropdown should show all available terminal applications.

### Files Version

v2.1.5.0

### Windows Version

Windows 11 21H2 22000.469

### Relevant Assets/Logs

[terminal.zip](https://github.com/files-community/Files/files/7981030/terminal.zip)
[debug.log](https://github.com/files-community/Files/files/7981039/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7981040/debug_fulltrust.log)

**Comment by gave92** [comment]
Do the terminals show in Settings > Preferences?

**Comment by codewing** [comment]
Resetting the App via windows settings works but it's pretty annoying to lose all the settings...

**Comment by MahdiGhiasi** [comment]
This is consistently happening for me in the second launch of the app after resetting the app via Windows settings.

![image](https://user-images.githubusercontent.com/1775637/154917863-4515bf8c-932a-4f4c-bd72-561554f7fbf9.png)

[debug.log](https://github.com/files-community/Files/files/8107609/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8107611/debug_fulltrust.log)
[terminal.zip](https://github.com/files-community/Files/files/8107619/terminal.zip)

**Comment by heewoonkim2020** [comment]
I have this issue too. Note that this is a very severe issue. A few days before Files even caused Explorer to crash and it wouldn't start up and it caused Windows to not be able to shut down. I had to press the power button manually.

**Comment by heewoonkim2020** [comment]
This happens when you resize the window.

**Comment by skykeyjoker** [comment]
themes setting also has the same problem, the list is empty. It happens after every system rebooting. Resetting works, but it's really annoying.

**Comment by heewoonkim2020** [comment]
@skykeyjoker THE SAME ISSUE!

**Comment by yaichenbaum** [comment]
This issue appears to be resolved.
