### ISSUE TITLE
Duplicate copy path function in context menu

### ISSUE THREAD

**Issue by cleuton4k** [files-community/Files#8101]
### Description

Duplicate copy path function in context menu

### Expected behavior

Duplicate copy path function in context menu

### Files Version

2.1.5

### Windows Version

w10 21h1 64 bits

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7981250/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7981251/debug_fulltrust.log)
![1](https://user-images.githubusercontent.com/90144967/152033376-e98d44dd-72a4-4eee-a0f8-d05f17168cab.jpg)

**Comment by yaichenbaum** [comment]
@cleuton4k do you have any shell extensions that might have added the second option?

**Comment by cleuton4k** [comment]
I have an APP that creates tabs in windows file explorer and it adds the copy path function, but I didn't think it affected the FILE.

**Comment by yaichenbaum** [comment]
@cleuton4k Files has a built in option for copying the path, it sounds like the app you installed is adding the second option.
