### ISSUE TITLE
high CPU usage when opening APP

### ISSUE THREAD

**Issue by cleuton4k** [files-community/Files#8102]
### Description

high CPU usage when opening the APP, not sure as I'm not a developer, but I think it's due to lack of cache. because every time I open the APP, navigate between folders or open tabs, it has a high cpu usage.

### Expected behavior

use cache to decrease CPU usage

### Files Version

2.1.5

### Windows Version

w10 21h1 64 bits

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7981295/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7981296/debug_fulltrust.log)

https://user-images.githubusercontent.com/90144967/152034596-d72a1a10-6cf7-478c-aad7-36e8628880a1.mp4

**Comment by Josh-65** [comment]
This is because it loading a driectory and the items infomation which is normal behaviour. They are working on updates to improve performace witch may help when its released.

**Comment by gave92** [comment]
Merging with #4180 unless @yair100 thinks this should be a separate item.

**Comment by yaichenbaum** [comment]
@gave92 this is also because of the experimental option to calculate folder sizes. This option is resource intensive and not recommended for regular use.

**Comment by gave92** [comment]
Good spotting that's true

**Comment by Josh-65** [comment]
It not that high for me it only goes to about 10% whats your CPU. Also caching did exist for files but it cause a lot of problems and wasnt useful in the end.

**Comment by yaichenbaum** [comment]
> even with the option to show folder size disabled, cpu usage remains high. the problem is the lack of cache, as the app has to create thumbnails every time I open it or navigate between tabs/folders. and even the windows explorer having to create the thumbnails (when I clear the cache) it consumes approximately 6% of cpu.

We reuse the cache from File Explorer, creating our own cache wouldn't have any improvements that I know of in terms of performance. We're working on a refactor of the code base to help reduce resource usage in Files, do you have any experience with c#?

**Comment by cleuton4k** [comment]
Unfortunately not
