### ISSUE TITLE
add a file information bar

### ISSUE THREAD

**Issue by cleuton4k** [files-community/Files#8103]
### What's the Problem?

when clicking on a file, it shows a bar containing information such as size, dimensions, frame rate...

### Solution/Idea

when clicking on a file, it shows a bar containing information such as size, dimensions, frame rate...

### Alternatives

when clicking on a file, it shows a bar containing information such as size, dimensions, frame rate...

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.5

### Windows Version

w10 21h1 64 bits

### Comments

![2 1](https://user-images.githubusercontent.com/90144967/152035633-daced6ff-31e3-4981-ab4e-c6c4bd5b11dc.jpg)
![2 2](https://user-images.githubusercontent.com/90144967/152035637-a3380524-886a-461c-907e-3a90e7a07215.jpg)

**Comment by Josh-65** [comment]
This is available with the preview pane
![image](https://user-images.githubusercontent.com/26977075/152039372-b90c1870-6a76-4cb2-b7e9-d4c366f3e27d.png)

**Comment by gave92** [comment]
Merging with #7606
