### ISSUE TITLE
add search history to search box

### ISSUE THREAD

**Issue by cleuton4k** [files-community/Files#8104]
### What's the Problem?

add search history to the search box and also a button to remove searches

### Solution/Idea

add search history to the search box and also a button to remove searches

### Alternatives

add search history to the search box and also a button to remove searches

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.5

### Windows Version

w10 21h1 64 bits

### Comments

![3](https://user-images.githubusercontent.com/90144967/152036089-5df39323-e081-482e-8188-a1d62a556f08.jpg)

**Comment by yaichenbaum** [comment]
Related #2447

**Comment by Josh-65** [comment]
[Discord conversation related to feature request](https://discord.com/channels/725513575971684472/725514946112127057/994673268030177432)
