### ISSUE TITLE
OK button does not work in compatibility window, changes are not applied

### ISSUE THREAD

**Issue by DAmNRelentless** [files-community/Files#8105]
### Description

When you right-click some `.exe` and switch to the compatibility tab, the `OK` button doesn't work anymore.
Due to this fact, the changes can't be applied.

### Steps To Reproduce

1. Right-click a `.exe`
2. Go to properties
3. Switch to the compatibility tab
4. Try to close the window by using `OK` (doesn't matter if you change something or not)

### Expected behavior

The window should close and changes should be applied.

### Files Version

Version: 2.1.5.0 OS Version: 10.0.22000.469

### Windows Version

Windows 11 Pro 21H2 Build 22000.469

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7982287/debug.log)

**Comment by yaichenbaum** [comment]
@DAmNRelentless can you upload the fulltrust log files?

**Comment by DAmNRelentless** [comment]
[debug_fulltrust.log](https://github.com/files-community/Files/files/7989147/debug_fulltrust.log)

**Comment by puppetsw** [comment]
I couldn’t replicate this one on main. Is it a particular exe that is causing the bug?

**Comment by DAmNRelentless** [comment]
Yes, it's the Rocket League `.exe`. After a bit of testing, it works occasionally when only changing the admin mode in the compatibility tab. But for all other options, the OK button does not work. I was able to reproduce this with other executables too. Seems like a permission error but it works fine with the normal Windows Explorer.
[Here](https://i.imgur.com/dbjx9Fa.gif) is a GIF that shows that nothing is happening when changing no data but then suddenly working when switching the admin mode (this is the only option where it works).

**Comment by WereWolfix** [comment]
I have the same issue with Files version 2.1.13.0. For me it doesn't work with all .exe files

https://user-images.githubusercontent.com/45063794/153618901-24a4cc02-cc16-4132-954c-a2598669f419.mp4

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
