### ISSUE TITLE
Files unpins itself from the taskbar when opening Explorer

### ISSUE THREAD

**Issue by Antyos** [files-community/Files#8106]
### Description

When Files is pinned to the taskbar, the **Set Files as default file manager** feature is enabled, and the original Windows File Explorer is launched through the start menu, Files will unpin itself from the taskbar.

### Steps To Reproduce

1. Enable **Set Files as default file manager** experimental feature
2. Unpin Windows File Explorer from taskbar
3. Pin Files to the taskbar
4. Open Windows start menu, search for and launch "File Explorer"

### Expected behavior

Files should not unpin itself from the taskbar if Explorer is opened.

### Files Version

Version: 2.1.5.0 OS Version: 10.0.19042.1466

### Windows Version

Windows 10 20H2 19042.1466

### Relevant Assets/Logs

Files pinned to taskbar:
![image](https://user-images.githubusercontent.com/17516195/152070337-5a686de7-6203-4c60-86ee-87be58620fec.png)

Files unpinned itself from the taskbar after opening Explorer:
![image](https://user-images.githubusercontent.com/17516195/152070390-fb04dbc0-d0bf-452c-9ef5-3781d4c896ff.png)
> I moved the Explorer icon over so it's in the screenshot

**Comment by yaichenbaum** [comment]
I can't reproduce this consistently, but it appears to be a Windows behavior, can you open an issue in the Feedback Hub under the taskbar section?
