### ISSUE TITLE
Merge Conflicting Folder Names / Bulk "All" Actions For Conflicting Files

### ISSUE THREAD

**Issue by WasabiIceCream** [files-community/Files#8109]
### What's the Problem?

It's way too tedious to perform cut/copy/paste actions with conflicting folders/files.
Files wants the user to confirm the action for EVERY conflict individually.
There's no simple "Merge" option for folders of the same name.

### Solution/Idea

This is something that Windows Explorer does pretty well, I think.
I think the default action for folders of the same name should just be to merge them.
For any conflicting files, the user should be asked to either overwrite all, skip all, or choose the action per-file.
![image](https://user-images.githubusercontent.com/12481327/152096068-989b3ecc-4019-499c-abfc-9bbecba3a644.png)

### Alternatives

Just use Windows Explorer to perform the cut/copy/paste actions.

### Priorities

| Capability | Priority |
| Merge conflicting folder names | Should |
| Prompt the user with an "Overwrite All Conflicting Files" option | Should |
| Prompt the user with a "Skip All Conflicting Files" option | Should |
| Prompt the user with more advanced options per-file | Should |
| Allow the user to tweak this behavior is the application settings | Could |

### Files Version

2.1.5.0

### Windows Version

Windows 10 Pro 21H2

**Comment by yaichenbaum** [comment]
Merging with #5645. In the meantime you can select all the items with `ctrl` + `a` and right clicking to take a bulk action.
