### ISSUE TITLE
Visual Blur Effect

### ISSUE THREAD

**Issue by w0otness** [files-community/Files#8110]
### Description

Fonts are sharp when a folder is first opened, when you select a file, the text animates and when is comes to rest, it remains blurry compared to original text.

### Expected behavior

Two options for fixes:

- Re-render text after animation or deselection so it returns to sharp text.
- Provide option to not use animation (its cute but not 100% needed)

### Files Version

Version: 2.1.5.0 OS Version: 10.0.19044.1466

### Windows Version

Edition	Windows 10 Home Version	21H2 Installed on	‎10/‎12/‎2021 OS build	19044.1466 Experience	Windows Feature Experience Pack 120.2212.3920.0

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/1296032/152105081-5fc1fa71-62f7-4400-ae8a-faecbfdb5b62.png)
![image](https://user-images.githubusercontent.com/1296032/152104178-4294ec8d-b0e3-49b2-bd12-d4bfe9ab185a.png)

**Comment by yaichenbaum** [comment]
This issue is specific to Windows 10 and we don't plan to work on a fix.
