### ISSUE TITLE
Drag-and-drop copying

### ISSUE THREAD

**Issue by deepprod** [files-community/Files#8111]
### What's the Problem?

Does not work by dragging and dropping files from the desktop or from a zip archive. I can't drag and drop any of the files.

### Solution/Idea

Make it workable by dragging and dropping files

### Alternatives

-

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.5.0

### Windows Version

Windows 10, 21H2

**Comment by yaichenbaum** [comment]
@deepprod is this still an issue in the preview version? https://files.community/download/preview
