### ISSUE TITLE
Bundles get deleted automatically

### ISSUE THREAD

**Issue by kart1ka** [files-community/Files#8112]
### Description

Bundles get deleted automatically after a couple of hours of creating them.

### Expected behavior

Bundles should not get deleted.

### Files Version

Version: 2.1.5.0 OS Version: 10.0.22000.469

### Windows Version

Edition	Windows 11 Home Single Language Version	21H2 Installed on	‎19-‎11-‎2021 OS build	22000.469 Experience	Windows Feature Experience Pack 1000.22000.469.0

### Relevant Assets/Logs

It shows the bundles that I created - ![Screenshot (1907)](https://user-images.githubusercontent.com/41051387/152116066-b316a6e7-4ad2-483e-9b53-db19a4f568d5.png)
It shows that those bundles got deleted automatically - ![Screenshot (1921)](https://user-images.githubusercontent.com/41051387/152116081-9395f95e-5e07-4f86-af12-ee6a2f6339eb.png)

**Comment by yaichenbaum** [comment]
@d2dyno1

**Comment by d2dyno1** [comment]
Wow

**Comment by yaichenbaum** [comment]
@d2dyno1 we don't support bundles anymore but we keep getting reports of this issue.

**Comment by gave92** [comment]
Closing as feature is being rebuilt in #9587.
