### ISSUE TITLE
Files crashes when right clicking on empty space 

### ISSUE THREAD

**Issue by Pratham-Galaxy** [files-community/Files#8113]
### Description

When i click on empty space in Files, it somehow crashes

### Steps To Reproduce

https://user-images.githubusercontent.com/97865710/152138706-243c26d8-e648-4c7a-86e1-53ede08bad23.mp4

### Expected behavior

It should not crash

### Files Version

2.1.5.0

### Windows Version

Window 11 21H2 22000.469

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7985658/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7985659/debug_fulltrust.log)

**Comment by SOI7** [comment]
I was able to reproduce this bug

**Comment by gave92** [comment]
The usual Layout cycle error. Might be solved if we stopped playing with the context menus height, but that brings issues on its own.
> 2022-02-02 16:05:29.3361|ERROR|AppUnhandledException|Layout cycle detected.  Layout could not complete.
Layout cycle detected.  Layout could not complete.
	Windows.UI.Xaml.LayoutCycleException: Layout cycle detected.  Layout could not complete.`

**Comment by gave92** [comment]
Merging with #7363
