### ISSUE TITLE
Files crashed when scrolling in a folder

### ISSUE THREAD

**Issue by THEBOSSMAGNUS** [files-community/Files#8117]
### Description

random crash

### Steps To Reproduce

1. i was scrolling searching a folder
2. file crash

### Expected behavior

nothing

### Files Version

Versione 2.1.5.0 OS Version: 10.0.22000.469

### Windows Version

Windows  21h2 22000.469 (insider release preview channel)

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7989731/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7989732/debug.log)

**Comment by yaichenbaum** [comment]
@THEBOSSMAGNUS is this still an issue in the preview version? https://files.community/download/preview

**Comment by THEBOSSMAGNUS** [comment]
It was a random crash, not a common occurrence
