### ISSUE TITLE
Interfaz Gráfica

### ISSUE THREAD

**Issue by adrianlegra86** [files-community/Files#8120]
### What's the Problem?

Tienen que habilitar la función Ctrl + Scroll para aumentar o disminuir el tamaño de los iconos de particiones, torre DVD, Smartphone  en el Home. La APP de temas respecto a los colores y diseños de skins no se integra bien a la APP principal del explorador, me funcioonó bien y después no funcionó más.

### Solution/Idea

Tienen que habilitar la función Ctrl + Scroll para aumentar o disminuir el tamaño de los iconos de particiones, torre DVD, Smartphone  en el Home. La APP de temas respecto a los colores y diseños de skins no se integra bien a la APP principal del explorador, me funcioonó bien y después no funcionó más.

### Alternatives

Tienen que habilitar la función Ctrl + Scroll para aumentar o disminuir el tamaño de los iconos de particiones, torre DVD, Smartphone  en el Home. La APP de temas respecto a los colores y diseños de skins no se integra bien a la APP principal del explorador, me funcioonó bien y después no funcionó más.

### Priorities

| Capability | Priority |
| :-------W--- | :--Must----- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.5.0

### Windows Version

Windows 11 Pro 21H2 22000.469

### Comments

Tienen que habilitar la función Ctrl + Scroll para aumentar o disminuir el tamaño de los iconos de particiones, torre DVD, Smartphone  en el Home. La APP de temas respecto a los colores y diseños de skins no se integra bien a la APP principal del explorador, me funcioonó bien y después no funcionó más.

**Comment by yaichenbaum** [comment]
@adrianlegra86 we're having a hard time understanding this feature request, can you try explaining the issue and possible solution?

**Comment by antonio-carrillo** [comment]
@yair100 , I think @adrianlegra86 is proposing to Zoom Out and Zoom In on the Home screen, be able to change the icon size (drives, libraries, bundles, etc.). Ctrl + Scroll, Ctrl + Plus, and Ctrl + Minus don't change anything on the Home screen. (I don't know if this is related to the missing layout option here).

**Comment by yair100** [comment]
> @yair100 , I think @adrianlegra86 is proposing to Zoom Out and Zoom In on the Home screen, be able to change the icon size (drives, libraries, bundles, etc.). Ctrl + Scroll, Ctrl + Plus, and Ctrl + Minus don't change anything on the Home screen. (I don't know if this is related to the missing layout option here).

Thanks for the help! We don't have plans to implement this feature request.
