### ISSUE TITLE
Double clicking on a folder anywhere opens the home page in Windows Explorer after uninstalling the app!

### ISSUE THREAD

**Issue by razzlesama** [files-community/Files#8121]
### Description

There are too many bugs in the app for me to use it in my work laptop so i uninstalled it. After uninstalling, double clicking on a folder anywhere just opens the home page in Windows explorer. 

### Steps To Reproduce

1. Uninstall the Files Application
2. Double click on any folder

### Expected behavior

Double clicking the folder should open that folder, not the home page.

### Files Version

2.1.5.0

### Windows Version

Windows 11 21H2 22000.469

### Relevant Assets/Logs

I can't open the log location in the settings of the app because clicking on the option opens the home page!

**Comment by yaichenbaum** [comment]
@razzlesama can you clarify what the home page is?

**Comment by razzlesama** [comment]
> @razzlesama can you clarify what the home page is?

It's the windows explorer default page. - The page that opens when you press the Windows key + E.

**Comment by yaichenbaum** [comment]
@razzlesama can you try running this script to see if it helps? https://raw.githubusercontent.com/files-community/Files/main/src/Files.Launcher/Assets/FilesOpenDialog/UnsetFilesAsDefault.reg

**Comment by razzlesama** [comment]
> @razzlesama can you try running this script to see if it helps? https://raw.githubusercontent.com/files-community/Files/main/src/Files.Launcher/Assets/FilesOpenDialog/UnsetFilesAsDefault.reg

This fixed it. I don't have admin privileges in my own account but i was able to log into the admin account and run the script and it worked for my account too. 

Now i have files installed again because it's more convenient, but i hope "set as default" for the Files app is fixed in the future. 
Thanks for the help :)
