### ISSUE TITLE
List mode? Compact view?

### ISSUE THREAD

**Issue by wpcoe** [files-community/Files#8123]
Just downloaded/installed List and am favorably impressed.  However, before I could ever consider replacing File Explorer with it, I would need List mode and Compact view.  So far, I haven't found those two items in Files – are they there, but I'm just not finding them?  Without them, folders with lots of files take too long to scroll through.

Compare:

![FileExplorer](https://user-images.githubusercontent.com/92417196/152278136-7719e27d-a8fc-4331-bb87-aec8bd4e1092.jpg)

 with

![File](https://user-images.githubusercontent.com/92417196/152278153-0689d618-487c-48e3-abd4-719ae887806e.jpg)

**Comment by yaichenbaum** [comment]
Thank you for your feedback, merging with #1940 and #2509

**Comment by yaira2** [comment]
@wpcoe thank you for your patience, I'm excited to share that a List View layout will be included in the next release.
