### ISSUE TITLE
Issues with libraries and OneDrive

### ISSUE THREAD

**Issue by Patz12** [files-community/Files#8124]
### Description

I have two main issues with libraries:
- Files add automatically my OneDrive folder even if I delete it from properties.
- The music library doesn't seem to work, it doesn't appear, all the other libraries work just fine.

I don't know if it is normal behavior or if Files needs my OneDrive folder added to Documents in order to make it work at the cloud drives section.

Also, I don't know if my system language could affect the app, since I have it in Spanish and windows changes things (like the program files folder name), and maybe some other registry entries I have this feeling because my logs have some entries written in Spanish.

![image](https://user-images.githubusercontent.com/49144585/152285852-547a2ece-1206-4890-b06e-9a6a31129338.png)

### Steps To Reproduce

1. Open Documents folder, in my case I have two drives (C:/ and D:/) and those sections appear, along with the third section for OneDrive.
2. Delete the entry of OneDrive from properties, that way I only have my C:/ and D:/ documents folders.

![image](https://user-images.githubusercontent.com/49144585/152285963-f1718546-c2cf-4304-8e0f-92d135db25f6.png)

3. Restart Windows, maybe restarting explorer.exe as well.
4. OneDrive appears again in my documents library.

### Expected behavior

- The OneDrive folder shouldn't be added by Files to my Documents library, since I deleted it before.
I read my logs and yes, my OneDrive folder is added automatically.
```log
2022-02-02 23:19:18.3144|INFO|EnumerateDrivesAsync|Adding cloud provider "OneDrive" mapped to D:\pax-1\OneDrive
```
- I can also see some errors related to access denial for the same folder, maybe those two lines are related?
```log
2022-02-02 23:05:50.4185|INFO|EnumerateDrivesAsync|Adding cloud provider "OneDrive" mapped to D:\pax-1\OneDrive
2022-02-02 23:05:51.3351|INFO|IsRunningOnArm|Running on ARM: False
2022-02-02 23:07:57.8288|INFO|IgnoreExceptions|Acceso denegado.

	System.UnauthorizedAccessException: Acceso denegado.

   at System.Runtime.InteropServices.McgMarshal.ThrowOnExternalCallFailed(Int32, RuntimeTypeHandle) + 0x21
   at __Interop.ComCallHelpers.Call(__ComObject, RuntimeTypeHandle, Int32, Void*) + 0xbe
   at __Interop.ForwardComStubs.Stub_3[TThis, TResult](__ComObject, Int32) + 0x37
   at Files.App.<>c.<OnSuspending>b__82_1() + 0x2e
   at System.Action.Invoke() + 0x25
   at Files.Common.Extensions.IgnoreExceptions(Action, Logger) + 0x22
```

- The music library should appear in my libraries section.

### Files Version

Versión: 2.1.5.0 OS Version: 10.0.22000.376

### Windows Version

Windows 11 Pro 21H2 (22000.376)

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7991958/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7991959/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
@Patz12 do you have a music library? You can hide the cloud drive section by right clicking on cloud drives and clicking on the hide option.

**Comment by Patz12** [comment]
> @Patz12 do you have a music library? You can hide the cloud drive section by right clicking on the cloud drives section and clicking on the hide option.

Yes, I have it

![image](https://user-images.githubusercontent.com/49144585/152287123-29e2a582-f96f-4582-9989-6c4f3d2d08fc.png)

About the OneDrive folder, I talk about the file list, my expected result is to remove my OneDrive directory view since Documents is grouped by folder directory, I need only my C:/ and D:/ folder.
But... I have an idea, maybe Files is adding this folder because it detects the name of "Documentos" from OneDrive, maybe if I rename that main folder in the cloud fixes my issue :0

![image](https://user-images.githubusercontent.com/49144585/152287490-4ddba330-991d-4e58-96a8-c36bef2ad38e.png)

**Comment by yaichenbaum** [comment]
> About the OneDrive folder, I talk about the file list, my expected result is to remove my OneDrive directory view since Documents is grouped by folder directory, I need only my C:/ and D:/ folder. But... I have an idea, maybe Files is adding this folder because it detects the name of "Documentos" from OneDrive, maybe if I rename that main folder in the cloud fixes my issue :0

I'm not sure I understand what you're trying to do with OneDrive, can you open a seperate issue for this?

> Also... weirdly enough, the music folder appears at Home

The folders on the home page are hardcoded, do you see the music library if you navigate to `C:\Users\username\AppData\Roaming\Microsoft\Windows\Libraries` in Files?

**Comment by Patz12** [comment]
> > About the OneDrive folder, I talk about the file list, my expected result is to remove my OneDrive directory view since Documents is grouped by folder directory, I need only my C:/ and D:/ folder. But... I have an idea, maybe Files is adding this folder because it detects the name of "Documentos" from OneDrive, maybe if I rename that main folder in the cloud fixes my issue :0
> 
> I'm not sure I understand what you're trying to do with OneDrive, can you open a seperate issue?
> 
> > Also... weirdly enough, the music folder appears at Home
> 
> The folders on the home page are hardcoded, do you see the music library if you navigate to `C:\Users\username\AppData\Roaming\Microsoft\Windows\Libraries` in Files?

- Yes, I will open a new issue for OneDrive if I have it because I think that I fixed both problems.
- I can't access that directory from Files since "it doesn't exist", I opened Windows Explorer instead and found that folder in another path.

I verified each library and the music library doesn't have a folder assigned to it, I added one and now Files shows it, which also made me make a new library called Downloads since I didn't have that one, and I erased the OneDrive entry manually for Documents. All of this was made from Windows Explorer, and the changes were reflected at Files.

![image](https://user-images.githubusercontent.com/49144585/152289958-e678275d-0b94-4104-935b-e1f3805d34e5.png)

![image](https://user-images.githubusercontent.com/49144585/152290230-c1a45894-b0d7-43c7-8e29-fc24bfefae31.png)


If I still have issues, I will open a new entry, thank you for your time :)
