### ISSUE TITLE
Thumbnails get cropped

### ISSUE THREAD

**Issue by Tarek-Hasan** [files-community/Files#8128]
### Description

In new version of files, thumbnails of photo and video gets cropped to centred and square area. 

### Expected behavior

Thumbnails should not get cropped.

### Files Version

2.1.5

### Windows Version

Win10 Pro 21H2 19044.1415

### Relevant Assets/Logs

Files:
![Screenshot 2022-02-03 133416](https://user-images.githubusercontent.com/27731012/152300295-239a6ce0-6580-4147-b035-0ecd732fb8e4.png)

File Explorer:
![Screenshot 2022-02-03 134103](https://user-images.githubusercontent.com/27731012/152301134-61b6a30b-ca61-4853-afc1-c1f6df7e4ba3.png)

**Comment by Josh-65** [comment]
Merging with #9129
