### ISSUE TITLE
embedded Terminal

### ISSUE THREAD

**Issue by woldtwerk** [files-community/Files#8131]
### What's the Problem?

Being a developer I really like the embedded Terminal you have in linux. Both nautilus and dolphin can do that.

It makes working with files much easier for experienced users.

### Solution/Idea

This is the nautilus extension:  
https://github.com/flozz/nautilus-terminal

### Alternatives

-

### Priorities

| Capability | Priority |
| :---------- | :------- |
| show embedded terminal | Must |
| terminal follows if you change directories | Must |
| explorer follows if you change directories in terminal | Must |
| select which terminal to use. wsl, powershell, ... | must |

### Comments

thx =)

**Comment by gave92** [comment]
Merging with #6235

**Comment by woldtwerk** [comment]
awesome! 
thx for quick reply

didn't find #6235 because I had different search terms :/

**Comment by gave92** [comment]
No problem, I just happen to know by heart most of the ~8000 issues 🤣

**Comment by lakani** [comment]
is this really being implemented ?

**Comment by Josh65-2201** [comment]
Yes https://github.com/files-community/Files/pull/13631
