### ISSUE TITLE
reduced motion

### ISSUE THREAD

**Issue by woldtwerk** [files-community/Files#8132]
### What's the Problem?

some animations make it feel a bit slow.

### Solution/Idea

add setting to reduce motion

### Alternatives

-

### Priorities

| Capability | Priority |
| :---------- | :------- |
| setting to change animation duration | Should |
| setting to disable animations | Should |

**Comment by gave92** [comment]
Alre you on Windows 10?

**Comment by gave92** [comment]
Some notes:
- you could try the option to disable animations in the Windows settings app but we've been told (#7700) that it does not affect Files speed
- click animations on file list can't be removed on Windows 10. Good news is that they have been removed from Windows 11

**Comment by woldtwerk** [comment]
> Are you on Windows 10?

yes I am. Wasn't aware that win11 behaves differently

thx for the info =)

**Comment by Wanooo0** [comment]
Why can't animations be disabled on windows 10?

**Comment by gave92** [comment]
They are done by the system, to remove them we'd need to stop using the system provided ListView control but that would degrade performance.
