### ISSUE TITLE
Expand disk folder tree in side pane

### ISSUE THREAD

**Issue by devilerj** [files-community/Files#8133]
### What's the Problem?

The sidepane doen't expand subfolders of a disk like windows explorer 

### Solution/Idea

Have the same behaviour of the side pane like windows explorer

### Alternatives

-

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.5

**Comment by gave92** [comment]
Merging with #1928

**Comment by yair100** [comment]
@devilerj Tree View is currently available in preview https://files.community/download. It will be included in the next stable release.
