### ISSUE TITLE
Update Italian translation 

### ISSUE THREAD

**Issue by THEBOSSMAGNUS** [files-community/Files#8134]
### Description

![19-03-22-141900](https://user-images.githubusercontent.com/92474350/152350545-553d8326-4250-4365-8a1b-c46aa0860bc8.png)

Propably translator's typing error. It should be, in italian,  "risoluzione" (english "resolution")

### Steps To Reproduce
See an immage preview zone 
.

### Expected behavior

it should be Risoluzione

### Files Version

Versione 2.1.5.0 OS Version: 10.0.22000.469

### Windows Version

Windows  21h2 22000.469 (insider release preview channel)

### Relevant Assets/Logs

.

**Comment by gave92** [comment]
Thanks, if you feel like it you can fix the issue yourself: https://files.community/docs/contributing/translating-files

**Comment by THEBOSSMAGNUS** [comment]
Alredy done a pull request 
https://github.com/files-community/Files/pull/8135
