### ISSUE TITLE
Updated Japanese translation

### ISSUE THREAD

**Issue by aiueokun111111** [files-community/Files#8137]
### Description

The translation is not correct.
The "Empty Trash(ゴミ箱を空にする)" button is always labeled "Trash is empty(ゴミ箱は空です)". (I apologize for this. I'm not good at English, so all the text in this post was translated by DeepL. There may be errors in the text.)

### Steps To Reproduce

Set the display language to Japanese.

### Expected behavior

Correct translation must be done.
× "The trash can is empty(ゴミ箱は空です)" → 0 "Empty the trash can(ゴミ箱を空にする)"

### Files Version

バージョン: 2.1.5.0 OS Version: 10.0.22000.469

### Windows Version

Windows 11 Home 21H2 Build22000.469

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7995497/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7995498/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
@aiueokun111111 would you like to update the translation?

**Comment by aiueokun111111** [comment]
Thanks !

**Comment by aiueokun111111** [comment]
> @aiueokun111111 would you like to update the translation?

I'm sorry I don't have the ability to improve this
