### ISSUE TITLE
Recent file bug

### ISSUE THREAD

**Issue by THEBOSSMAGNUS** [files-community/Files#8138]
### Description

1) Drag and drop with recent file don't work
2) if you click on a recent files 1 time it open, normaly require 2 click. So if you click 2 times it open two times.

(sorry for the english)

### Steps To Reproduce

Go to recent file

### Expected behavior

.

### Files Version

Versione 2.1.5.0 OS Version: 10.0.22000.469

### Windows Version

Windows  21h2 22000.469 (insider release preview channel)

### Relevant Assets/Logs

.

**Comment by yaichenbaum** [comment]
Thank you for your feedback, merging with #6074
