### ISSUE TITLE
Add a context menu when right click Files on taskbar

### ISSUE THREAD

**Issue by Pratham-Galaxy** [files-community/Files#8140]
### What's the Problem?

When we right click on file explorer in taskbar a context menu appears which contain pinned shortcuts but when we right click Files on taskbar no context menu appears

### Solution/Idea

![Screenshot 2022-02-03 225344](https://user-images.githubusercontent.com/97865710/152395432-7f6b82b0-2c6a-433d-885c-a0cc89658a0f.png)

### Alternatives

If the pinned shortcut context menu will appear when right click Files on taskbar, it will make easier to locate pinned shortcuts faster.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.5.0

### Windows Version

Window 11 21H2 22000.469

**Comment by yaichenbaum** [comment]
Thank you for your feedback, merging with #5577
