### ISSUE TITLE
Make a theme that wiil have mica effect only on command bar

### ISSUE THREAD

**Issue by Pratham-Galaxy** [files-community/Files#8141]
### What's the Problem?

I like file explorer theme that have mica effect on command bar and rest of window have no mica effect

### Solution/Idea

![Screenshot 2022-02-03 231132](https://user-images.githubusercontent.com/97865710/152398408-345e25be-b721-4ac3-88f3-fe245edc4c92.png)

Make theme such that mica effect wiil be only on this bar 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.5.0

### Windows Version

Window 11 21H2 22000.469

**Comment by yaichenbaum** [comment]
We don't have plans to build this theme into Files but you can follow the documentation to build the theme and import it manually.

**Comment by Pratham-Galaxy** [comment]
can you help me, because i don't know how to build theme

**Comment by yaichenbaum** [comment]
Here is a link to the documentation https://deploy-preview-135--files-community.netlify.app/docs/configuring/custom-themes. Let me know if you have any questions.

**Comment by Pratham-Galaxy** [comment]
can we only put mica effect to command bar?

**Comment by yaichenbaum** [comment]
@Pratham-Galaxy yes, you can add a transparent background to `NavigationToolbarBackgroundBrush`.
