### ISSUE TITLE
Can't drag a file in recent file

### ISSUE THREAD

**Issue by THEBOSSMAGNUS** [files-community/Files#8142]
### Description

Can't drag a file in recent file

### Steps To Reproduce

Try to drag a file from recent file

### Expected behavior

it drag normaly like in other folder

### Files Version

Versione 2.1.5.0 OS Version: 10.0.22000.469

### Windows Version

Windows  21h2 22000.469 (insider release preview channel)

### Relevant Assets/Logs

.

**Comment by yaichenbaum** [comment]
@THEBOSSMAGNUS thank you for your feedback, can you open a new issue for this using the feature request template?
