### ISSUE TITLE
crash when using alt+enter in recycler bin

### ISSUE THREAD

**Issue by shayan15sa** [files-community/Files#8153]
### Description

hi
when i want to see property and using alt+tab in recycler bin i get a carsh

### Expected behavior

hi
when i want to see property and using alt+tab in recycler bin i get a carsh

### Files Version

Version: 2.1.5.0 OS Version: 10.0.18363.1734

### Windows Version

windows 10 1909

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8001620/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8001621/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
This is resolved in the preview build https://files.community/download/preview
