### ISSUE TITLE
Context menus appearing off screen when clicking near the edge of the screen

### ISSUE THREAD

**Issue by TheWox** [files-community/Files#8156]
### Description

When you context click things close to the edge of a monitor, the context menu is cut off, or can appear on a second monitor (and be scaled according to the other monitor).

### Steps To Reproduce

1. Maximize a Files window to full screen, or place Files close to the left edge of your monitor.
2. Right click a Favorites menu item very close to the edge of the screen.
3. Notice that the context menu appears either half visible (par of it is off screen), or in the case of double monitors the context menu might appear on the next monitor over (and be scaled accordingly to the next monitor).

### Expected behavior

My suggestion is to make it so the context menu always appears fully in view, on the monitor where the item was context clicked by off setting its position to the other side of the cursor.

### Files Version

Version: 2.1.5.0 OS Version: 10.0.22000.469

### Windows Version

Windows 11 21H2 (OS Build 22000.469)

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/26923521/152606733-9641899a-cff9-4ab9-aefb-30474002268e.png)

![image](https://user-images.githubusercontent.com/26923521/152607482-b865ee47-0fd3-431d-8381-afccb5191e0e.png)

**Comment by Josh-65** [comment]
This is a bug with WinUI, what files uses for the UI. I belive it known as an issue on there github page.

**Comment by gave92** [comment]
To be checked if using ShouldConstrainToRootBounds=True works on context menus but I don't think so.
