### ISSUE TITLE
Solid black background color on folder icons

### ISSUE THREAD

**Issue by thyranus** [files-community/Files#8158]
### Description

I assume this bug has already been reported, but if not, I report that the folder icons appear with a solid black background color, which doesn't look good with the overall aesthetics of the app, especially if I change the visual theme for "Acrylic". 

### Expected behavior

This background color should be transparent.

### Files Version

2.1.5.0

### Windows Version

Windows 11 Pro 21H2 22000.469

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8007037/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8007039/debug_fulltrust.log)

**Comment by gave92** [comment]
Tracked in #6373
