### ISSUE TITLE
After deleting or renaming files, file list scrolls to the top

### ISSUE THREAD

**Issue by dlee098** [files-community/Files#8159]
### Description

When I delete any file, the explorer window scrolls all the way back to the top. 

### Steps To Reproduce

1. Go to any explorer window.
2. Scroll down to anywhere but the very top.
3. Delete a file
4. The window automatically scrolls back to the top

### Expected behavior

For the scroll location to remain the same. Sometimes I want to delete multiple files that are in the same general date/area in the window, but this makes that a huge hassle.

### Files Version

Version: 2.1.5.0 OS Version: 10.0.19044.1466

### Windows Version

Windows 10 Version: 10.0.19044.1466

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8007232/debug.log)

**Comment by THEBOSSMAGNUS** [comment]
can you also add debugfulltrust.log ? it's in the same folder

**Comment by dlee098** [comment]
[debug_fulltrust.log](https://github.com/files-community/Files/files/8007687/debug_fulltrust.log)

Done!

**Comment by THEBOSSMAGNUS** [comment]
perfect, attending a developer

**Comment by yaichenbaum** [comment]
@d2dyno1 are you able to reproduce this issue?

**Comment by d2dyno1** [comment]
Nope, doesn't happen for me

**Comment by yaichenbaum** [comment]
@dlee098 can you upload a screen recording to help us debug the issue?

**Comment by Josh-65** [comment]
Ive had this happend when the confimation for deletion is turned off.

**Comment by dlee098** [comment]
> 

Ah this is it! I had thought that it didn't do this before and then all of a sudden I had the issue. It was after I changed that setting.

Not sure if this is a feature or a bug but is there any way to get this fixed in a future update? It's an extra step to have to confirm every deletion, and then another hassle to have the window scroll all the way to the top each time if the setting is off.

**Comment by yaichenbaum** [comment]
@dlee098 this issue should be resolved with #9130
