### ISSUE TITLE
[Experimental] File is not focused when "Show in Folder" is called 

### ISSUE THREAD

**Issue by alphapuggle** [files-community/Files#8160]
### Description

When opening a downloaded file with "Show in Folder" and Files is set as the default file manager, files will open the containing directory, but not focus the file

### Steps To Reproduce

Download a file
Select "Show in Folder"

### Expected behavior

Downloaded file should be focused

### Files Version

2.1.5.0

### Windows Version

Windows 11 Pro 21H1 Build 22543

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8007354/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8007357/debug_fulltrust.log)

**Comment by THEBOSSMAGNUS** [comment]
i confirm, also file open at full screen, unlike stock explorer. I think that stock  explorer solution is better for for multitasking!

**Comment by gave92** [comment]
Tracked in #6382
