### ISSUE TITLE
Random crashes in the background

### ISSUE THREAD

**Issue by nijoj** [files-community/Files#8161]
### Description

Files randomly crashes in the background and i get a warning message about "something happened which developer didnt plan for" !?. So im attaching logs so that you can figure this out

### Expected behavior

Files dont randomly crash in the background

### Files Version

Version: 2.1.5.0 OS Version: 10.0.22000.434

### Windows Version

Windows 11 Pro 22000.434

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8007385/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8007386/debug.log)

**Comment by yaichenbaum** [comment]
@nijoj is this still an issue in the preview version? https://files.community/download/preview

**Comment by nijoj** [comment]
@yair100  Haven't got this issue recently, so closing this one. Thanks for looking into it.

Current Version:
Version: 2.1.15.0
OS Version: 10.0.22000.675
