### ISSUE TITLE
Right-click menu Bad performance

### ISSUE THREAD

**Issue by THEBOSSMAGNUS** [files-community/Files#8165]
### Description

The right click menu is glitch and laggy.
it load the first part in te right way, but the second part sometimes laggy appear in a feaw instant.
The situation is better if the split ecxed item in a different menu because the menu is smaller.

It didn't appened every times but only in 30% 

### Steps To Reproduce

right click on an items

### Expected behavior

.

### Files Version

Versione 2.1.5.0 OS Version: 10.0.22000.469

### Windows Version

Windows  21h2 22000.469 (insider release preview channel)

### Relevant Assets/Logs

.

**Comment by gave92** [comment]
Merging with #4180.

Behaviour's expected, takes a little time to load shell context menu items.

**Comment by yair100** [comment]
@TheBossMagnus we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
