### ISSUE TITLE
Default option for conflicting files

### ISSUE THREAD

**Issue by Null69** [files-community/Files#8167]
### What's the Problem?

No option to make conflicting files prompt to replace files or generate new name etc...

### Solution/Idea

Let us be able to set the default conflicting files actions when copying files. It's going to need work to select replace the conflicting files one by one especially when you're copying more than 20 files. I hope you understand my request sorry for bad English it's not my first language.

### Alternatives

aa

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by Josh-65** [comment]
Same as #5645

**Comment by gave92** [comment]
A better UI is in the works. In the meantime you can choose e.g "Replace" for one then right click and choose "Apply to all"

**Comment by Null69** [comment]
Sorry for not using the search first before posting. I'll keep that in mind
thanks!
