### ISSUE TITLE
Folder thumbnails

### ISSUE THREAD

**Issue by willynanita** [files-community/Files#8168]
### What's the Problem?

Is it possible to add folder thumbnails to the app in windows 11? This feature is in windows explorer on windows 10, but they didn't add it to windows 11.  This is a very useful feature.

### Solution/Idea

Add content thumbnails to folders, just like in windows explorer in win 10.

### Alternatives

Haven't got any.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.1.5.0

### Windows Version

OS Version: 10.0.22000.469

**Comment by Josh-65** [comment]
Right click the folder you want to change > Properties (i symbol in top right) > click the ... menu > customize > browse. Select the icon you want.
