### ISSUE TITLE
Use teracopy for copy files

### ISSUE THREAD

**Issue by eminaguil** [files-community/Files#8170]
### What's the Problem?

Files v2 minimalistic approach to copy files. I make my backups using [**teracopy**](https://www.codesector.com/teracopy) and I miss the option for replacing archives, the progress status, and the verification. I use files for my every day explorer necessities, but, when copying, I switch to the default explorer because of teracopy.

### Solution/Idea

If teracopy is installed, use it instead of the integrated copy or configure for using it..

### Alternatives

Allow to configure / integrate other external copy tools.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to accomplish copy files using an external copy tool| Could |

### Files Version

Version: 2.1.5.0 

### Windows Version

Windows 10 21H2 OS (Version: 10.0.19044.1503)

**Comment by Josh-65** [comment]
Improvments are beeing talked about on #4811

**Comment by gave92** [comment]
Also #7518 / #7275
