### ISSUE TITLE
SSH file explorer 

### ISSUE THREAD

**Issue by upintheairsheep** [files-community/Files#8172]
### What's the Problem?

All the ssh file browsers look ugly

### Solution/Idea

Add support for managing files via ssh

### Alternatives

Using the command line

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by LeCodeCo** [comment]
By this, I presume you mean SFTP, which has been requested in #3917 and #2407.
