### ISSUE TITLE
Can't return to default file explorer.

### ISSUE THREAD

**Issue by 5vl** [files-community/Files#8173]
So, basically,

I changed back the "set default file explorer" to off, and then deleted the application because I wanted to have the old one back.
Now though, I cannot open my file explorer at all because it can't find it.
When I do WIN+E or run explorer.exe in cmd it says:
![image](https://user-images.githubusercontent.com/66801986/152658785-f3d13db5-1cc7-4229-b3ef-e8be712019fe.png)
I've already tried to change registry settings to point back to the old explorer.exe, but it does not work.
How the hell do you fix this?!

**Comment by Josh-65** [comment]
try running this https://raw.githubusercontent.com/files-community/Files/main/src/Files.Launcher/Assets/FilesOpenDialog/UnsetFilesAsDefault.reg

**Comment by 5vl** [comment]
THANK YOU SO MUCH. It worked. 
It's just annoying that it didn't do that from within the app itself..
