### ISSUE TITLE
Move colums and double tree panel

### ISSUE THREAD

**Issue by sanekaze** [files-community/Files#8174]
### What's the Problem?

Hello,
A feature I would like to see in the app:

- Ability to rearrange the columns to customize the display. In my case, I usually have the "Size" column after the "Name" column, then "Type" and finally "Date modified".

### Solution/Idea

Be able to re arrange the colums

### Alternatives

Stay with Windows file explorer

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.5.0

### Windows Version

Win10 21H2

**Comment by gave92** [comment]
Tracked in #4643
