### ISSUE TITLE
ERROR AL RENOMBRAR CARPETA O ARCHIVO

### ISSUE THREAD

**Issue by e-slzr** [files-community/Files#8175]
### Description

Al intentar renombrar una carpeta o archivo Files se reinicia y no realiza el cambio de nombre..

### Steps To Reproduce

1. Seleccionar carpetar o archivo a renombrar
2. Click derecho o F2
3. Introducir nuevo nombre
4. Presionar ENTER

### Expected behavior

Cambio de nombre realizado correctamente

### Files Version

Version: 2.1.5.0 OS Version: 10.0.22000.376

### Windows Version

Windows 11 Pro 21H2 22000.376

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/65575720/152660839-3a7b20c4-0eca-4826-be2b-1a531d650357.png)

**Comment by gave92** [comment]
Merging with #7996
