### ISSUE TITLE
Memory + Performance Leak

### ISSUE THREAD

**Issue by Roryl-c** [files-community/Files#8176]
### Description

On initial open on my system, Files takes ~95-105mb of memory and is pretty snappy and performant.
However, after even light workloads involving opening and closing tabs, some actions become very sluggish.
With Task manager open, I have observed the following:

- Opening a folder in a new tab (such as the Desktop) allocates between 30mb-50mb memory (it seems to scale with number of items in the opened folder) that never gets freed again in the lifetime of the program.
- Navigating back and forth using the back and forward buttons allocates some memory each time (in the realm of 3-10mb) which never gets freed again in the lifetime of the program.
- At high memory allocation, the program is very significantly slower (up to 3 seconds to close a tab).

To demonstrate the severity of this issue, I compared the response time and memory usage of Files opening my desktop in a new tab after launch and after opening and closing it 10 times:

- Initial: ~0.5s, 140mb
- After 10 times: ~4s, 650mb

### Steps To Reproduce

1. Open Task Manager
2. Open Files and observe its idle memory usage
3. Middle-click your desktop (or another folder which may contain more items, such as Documents or Downloads) to open it in a new tab, note the response time and observe the increase in memory usage in Task Manager over a few seconds
4. Close the tab opened in step 3, note the response time and observe memory usage not decrease
5. Repeat steps 3 and 4 as many times as desired, note the response time and memory usage increasing consistently

### Expected behavior

Files should be exactly as responsive on startup as it is after heavy use.

### Files Version

Version: 2.1.5.0 OS Version: 10.0.19043.1466

### Windows Version

Windows 10 Home 21H1 19043.1466

### Relevant Assets/Logs

Fresh logs that just consist of me performing the repro steps above:
[debug.log](https://github.com/files-community/Files/files/8009104/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8009105/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
Merging with #2065
