### ISSUE TITLE
AppData via Run (Windows+R)  not working

### ISSUE THREAD

**Issue by thepumpkin1** [files-community/Files#8177]
### Description

Hello,

I have downloaded Files just an hour ago, and I have noticed the AppData folder is not opening via the Run window which can be opened by Windows + R. It keeps saying "Windows cannot access the specified device, path, or file. You may not have the appropriate permissions to access the item." Also, the file CAN be opened via the searching bar. (It happened after I selected Files as my default File Manager program.)

Please let me know if you have a solution for this.
Have a good day/night.

### Steps To Reproduce

1. Go to Files.
2. Select Settings at the top left.
3. Select Experimental.
4. Open the "Set Files as the default file manager."
5. Click Yes.
6. Press Windows + R.
7. Type %appdata% at the label.
8. See the error.
![image](https://user-images.githubusercontent.com/99102114/152662169-2394aca5-08a0-434c-abbf-f3d82b4aab81.png)

### Expected behavior

I want to open the AppData file via Windows+R. It must open the AppData folder. Not the error.

### Files Version

Version: 2.1.5.0 OS Version: 10.0.22000.466

### Windows Version

Windows 11 Pro Version	21H2 22000.466

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/99102114/152662414-5bdfde08-5407-4eb0-841e-0963a4dc2fd2.png)
![image](https://user-images.githubusercontent.com/99102114/152662418-c54bbd82-9be5-4a80-bcd1-2971f016845d.png)
![image](https://user-images.githubusercontent.com/99102114/152662431-248fc892-6d72-49db-be59-b38608528f9f.png)

(I couldn't find the logs)

**Comment by yaichenbaum** [comment]
@thepumpkin1 in order to open Files from the run dilog box you need to include the app name. `Files %appdata%`
