### ISSUE TITLE
Could not copy file name

### ISSUE THREAD

**Issue by charleschiu2012** [files-community/Files#8179]
### Description

While trying to copy the file name, it reports an error then shutdown.

### Steps To Reproduce

1. Choose any file.
2. Press F2 to edit the file name.
3. Encounter error.

### Expected behavior

After copy/edit the file name, click somethere else or press ESC to leave edit mode.

### Files Version

Version： 2.1.5.0 OS Version: 10.0.19044.1503

### Windows Version

Windows 10 Enterprise 21H2 120.2212.4170.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8009469/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8009470/debug_fulltrust.log)

**Comment by gave92** [comment]
Merging with #7996

**Comment by gave92** [comment]
Could you confirm it only happens in Tiles view?

**Comment by charleschiu2012** [comment]
@gave92 ys, it seems to be.
