### ISSUE TITLE
Could not switch the text color to white in switch to the "Black Pixel" theme.

### ISSUE THREAD

**Issue by Huanlan233** [files-community/Files#8182]
### Description

When I switch to the "Black Pixel" theme, the font color becomes invisible.

### Steps To Reproduce

1. Go to "Settings".
2. Open "Custom themes"
3. Switch to "Black Pixel" theme

### Expected behavior

The text switch to white

### Files Version

Version: 2.1.5.0 OS Version: 10.0.19044.1415

### Windows Version

Windows 10 21H2 19044.1415

### Relevant Assets/Logs

![bug](https://s2.loli.net/2022/02/06/Q3PplERg1K4mVNw.png)

**Comment by yaichenbaum** [comment]
The black pixel theme is only intended to be used with dark mode.
