### ISSUE TITLE
Canceling mapped network drive wizard sometimes causes focus to move to different window

### ISSUE THREAD

**Issue by sebscherrer** [files-community/Files#8183]
### Description

When canceling the mapped network drive wizard focus will go to another application running in the background.

I went to add a new mapped network drive but wanted to cancel out to check a path. When I hit cancel, instead of going back to the Files window, I went back to a chrome window I had open.

### Steps To Reproduce

I've documented my steps in a video I've attached
https://user-images.githubusercontent.com/20893446/152671500-d4aff711-149e-4424-a340-50b4048c55ab.mp4

### Expected behavior

I would expect that canceling the mapped network drive wizard would return the user back to the Files window they had initiated the call from.

### Files Version

2.1.5.0

### Windows Version

Windows 11 Pro 21H2 22000.469

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8009664/debug_fulltrust.log)

**Comment by yaira2** [comment]
This looks like an issue in Windows, trying to work around this on our own could have unintended side effects.
