### ISSUE TITLE
Custom Folder Icons in Bundles

### ISSUE THREAD

**Issue by arnolicious** [files-community/Files#8185]
### What's the Problem?

Folders which have a custom icon, show up with a default folder icon when added to a bundle.

That default folder icon also does not seem to be the same folder icon as the regular folder icon used in Files.

### Solution/Idea

- Make the folders inside bundles use their custom icon
- Make the default folder icon inside bundles the same as the default folder icon in the rest of Files

### Alternatives

It's just a minor incovenience.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Folders with custom icons should use that custom icon inside a bundle | Must |
| The default folder icon in a bundle should be the same folder icon as in the rest of Files | Should |

### Files Version

2.1.5.0

### Windows Version

Windows 11 21H2 22000.466

**Comment by yaichenbaum** [comment]
Bundles are no longer being developed and will be replaced with a tags widget.
