### ISSUE TITLE
Files may crash when pulling a tab out to separate window

### ISSUE THREAD

**Issue by isak-dombestein** [files-community/Files#8186]
### Description

While doing some work requiring me to have several instances of Files open, I decided to pop out one of my tabs by dragging it outside the Files Window, forcing it to open as a new instance with the current location active. I've done this several times  in the past and have found it working perfectly with this being the first time it happened. 
I did try to replicate the issue a bit afterwards but was not able to reproduce the same error more than once, where both crash cases happened while the active tab was on a different drive than the C: Drive.

### Steps To Reproduce

1. Open two separate folders in two tabs
2. Choose one of the folders to pop out
3. Drag the selected tab outside the active Files window
4. Crash should occur after releasing the tab.

Crash may only occur with the tab being popped out being a non-Windows drive (any drive letter except for C:)

### Expected behavior

The tab should open up in a new Files window with the folder active when the tab was pulled out being automatically reloaded instead of the Home screen popping up.

### Files Version

Version: 2.1.5.0 OS Version: 10.0.22000.469

### Windows Version

Windows 11 Version 21H2 (OS Build 22000.469)

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8010285/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8010286/debug_fulltrust.log)

**Comment by Josh-65** [comment]
Same as #7246
