### ISSUE TITLE
Feature: Preview gif files when hovering the mouse on top of the thumbnail

### ISSUE THREAD

**Issue by Darhagonable** [files-community/Files#819]
**Requirements**
- Holding the mouse cursor over gif thumbnails in the grid layouts should start playing the gif

**Comment by yaichenbaum** [comment]
That is an interesting idea, I assume this would be for the grid view layout.

**Comment by Darhagonable** [comment]
Yes for grid view layout. I forgot to mention that :P

**Comment by octopushugger** [comment]
I would like the option to always play animated gifs in thumbnails as long as there is window focus.

**Comment by gh0sti** [comment]
wouldnt it be better if the gif played in the sidepanel view similar to how pictures can be viewed in the sidepanel?

**Comment by yaichenbaum** [comment]
We're looking into creating a built-in preview feature that displays a popup preview when pressing the spacebar. While it's not the same as hovering the mouse over the file, it gives the user a richer preview and reduces the visual clutter that can result when the user unintentionally leaves the cursor on top of a gif file.
