### ISSUE TITLE
Feature: Support renaming multiple files at the same time

### ISSUE THREAD

**Issue by goncaloMgomes** [files-community/Files#8191]
### What's the Problem?

Only one file can be renamed at the same time.

### Solution/Idea

1. Using the rename action when multiple items are selected should open a "Rename items" dialog
2. The rename dialog should consist of a simple title and text box for entering the new name
3. Items containing different extensions should get the new name
4. Items with the same extension should have a number attached to the end

**Comment by Josh-65** [comment]
It been said that there arent going to implemnt a systems like this as PowerToy exsits with this feature. You can search for it on the MS store to get it.

**Comment by yaichenbaum** [comment]
@Josh-65 this is a bit of a different request, File Explorer has support for renaming multiple files at the same time and it automatically appends a number to the end. I think we can do something similar in Files.

**Comment by goncaloMgomes** [comment]
File explorer only appends a number if the file's extensions are the same, if the files have different extensions the same name is applied without numbers. You can test this.

**Comment by Leebo-missile** [comment]
I went to edit pictures today using this files app, and i thought oh no I cant just highlight multiple files and delete the tile to have it auto sequence the files like before, when i would build collections or just need to remove clutter, power tools isn't not a very efficent tool to use in this the default windows 11 file explorer does it perfectly, highlight multiple files hit rename,  delete existing title, it's already highlighted, and see it work magic., 1 file 2 file 3 file 4 file, works perfectly to batch rename quickly. no right click and looking through menu for power tools rename feature only to have it pop up another window asking you to add or replace like the replace feature in a word document, so bad. we need this batch rename feature of windows 11

**Comment by nordquistdave** [comment]
I also like multi-file rename features! On the case, I like putting media files on an USB disk for playback on a TV, but the filemanager in the TV is bad at exposing full filenames s.t. 
  [Erai-Raws] Ranked-Choice Voting Julia Sentai - 03 - [HVSC][4192p][Multi-Sub][Thai dub] [5600826498].mkv
is indistinguishable from the other episodes. For sensibility:
Episode-first with knockout for common elements (e.g. removing Multi-Sub and **Hash** (not the same for all files! But like it's not a cared for human-readable element in portable media cases much) would be lovely.

**Comment by Draise14** [comment]
Aye, can agree this UX would be very nice. F2 on multiple equals "[NAME]+(1,2,3,etc)

**Comment by QuintessentialForms** [comment]
This is a very basic and necessary feature! I just found out it was missing, and I will have to stop using Files. (I know there are other softwares out there for batch renaming, but I don't have time to go experimenting with those this morning. Thought posting this comment would be more productive use of five minutes.)

Because of this missing feature:
- I can't work with generative AI output images.
- I can't work with rendered frames outputted from Blender.
- I can't work with frames split from a video input (animation reference recordings).

There goes about 20% of my regular tasks. Definitely unusable.

I am attaching Ubuntu's rename panel solution as reference, although I suspect there are better solutions out there:
![Screenshot from 2024-04-26 04-52-57](https://github.com/files-community/Files/assets/87719075/43db72e7-97d9-4351-98f7-e5c498682d67)

**Comment by yaira2** [comment]
@QuintessentialForms thank you for your feedback, we understand your frustration and this is on our todo list to add. At the same time, we recommend using PowerToys by Microsoft which integrates with Files. Besides for having a powerful tool for bulk renaming, it has many other integrations for Windows which you might useful.

**Comment by yaira2** [comment]
We're currently working on basic support for bulk renaming. At this stage, the feature will only allow you to change file names. Please note that advanced functionalities, such as changing file extensions or performing find & replace operations, are not planned at this time.
