### ISSUE TITLE
Detailed view column order

### ISSUE THREAD

**Issue by gTamatea** [files-community/Files#8192]
### What's the Problem?

Hello,
In the detailed view, is it possible to change the column order ? By default I use Name | Size | Type | Date and sort by Type. It's something possible on the default Explorer for example.

### Solution/Idea

Allow draging column in detailed view as you would like to order them

### Alternatives

Use the default Windows Explorer :(

### Files Version

Version : 2.1.5.0 OS Version: 10.0.22000.434

### Windows Version

Windows 11 21H2 22000.434

**Comment by gave92** [comment]
Not yet, tracked in #4643

**Comment by gTamatea** [comment]
> Not yet, tracked in #4643

Thanks didn't see it. Regards.
