### ISSUE TITLE
Allow option to upload picture as files theme

### ISSUE THREAD

**Issue by Verisimilitude11** [files-community/Files#8193]
### Solution/Idea

add an option in files that allows users to upload any image of their choice and use it as their background in files

### Alternatives

using the default themes

### Priorities

| upload images | low |
| :---------- | :------- |
| upload images as a custom background | Must |
| have a high image size limit| Should |

### Files Version

2.1.5.0

### Windows Version

Windows 11 Pro Insider Preview Dev Installed on	‎1/‎29/‎2022 OS build	22543.1000 Experience	Windows Feature Experience Pack 1000.22543.1000.0

**Comment by yaichenbaum** [comment]
https://files.community/blog/posts/how-to-use-background-image

**Comment by VerisimilitudeX** [comment]
> https://files.community/blog/posts/how-to-use-background-image

implement an easier method that allows a user to upload it in-app @yair100

**Comment by yaichenbaum** [comment]
We're tracking that in #5916

**Comment by Verisimilitude11** [comment]
Got it, thanks!
