### ISSUE TITLE
Save view as default 

### ISSUE THREAD

**Issue by hiharry** [files-community/Files#8194]
### Solution/Idea

It would be awesome if there were a "save view as default" button. Here's two scenarios this would be really awesome:

1. If I wanted to always see my folders using the column view, I would have to manually change to that view every time I enter a "root" folder. This is not that painful because we don't really have many "paths" we use daily as we tend to go the same folders over and over again. But it would be helpful anyway.
2. The name column is too short on my window and I have to make it bigger in every single folder. That is really painful. Lol. Here's an example:
[](https://user-images.githubusercontent.com/444878/152703003-a2cf3e91-a628-4908-b10a-d3d840204830.png)

Thanks a lot for the effort in making Files.

### Alternatives

Not sure

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.5.0

### Windows Version

Windows 11 21H2 22000.434

**Comment by gave92** [comment]
Thanks for the report. You should be able to set a view as default by:
- Turning off "enable individual preferences" in Settings > Preferences > Files and folders
- Setting the desired view mode on any folder
- Optionally turn the above option back on

**Comment by hiharry** [comment]
Right. It works for the view mode change, but not for the width of the name column. Is there any way of changing that?

**Comment by gave92** [comment]
Currently there's a bug preventing that, tracked in #6448.

**Comment by theophanemayaud** [comment]
It seems that #6448 was closed but doesn't, when "enable individual preferences" is off, save the user custom width for the current folder to all the others. When "enable individual preferences" is disabled, it seems to me to always restore the default width when changing folders. Therefore, when enabling "enable individual preferences", the default for all folders that haven't been manually changed, is the app default. 

I think as the OP that it would be great to set a custom default width, when "enable individual preferences" is enabled. That is, set a custom width different than the app default, to all folders that do not already have a custom width. It doesn't seem possible in preview version 2.1.41.0

For me there are two ways to go about this:
- enable changing the default app width, wether "enable individual preferences" is on or off
- only when "enable individual preferences" is on, have a way to set a specific default custom preference to all folders that don't already have one set by the user.
