### ISSUE TITLE
Group items by color tags not working properly

### ISSUE THREAD

**Issue by hiharry** [files-community/Files#8195]
### Description

Hello, I have a folder with lots of files marked with color tags and I want to see them grouped together, like when we view the Downloads folder grouped by creation date. The first time I set Files to group my files, it works like a charm. But when I go to another folder and enter again that folder I configured before, the files are all in the "not set" category. The color tags are all there, but they are all together in the same group.
Here's a screenshot.
![image](https://user-images.githubusercontent.com/444878/152707046-7faa6554-fb90-4a6c-acc0-c1449b1a7d95.png)

What I know is the Downloads folder works ok set like that. It's always grouping items by the date, as seen in the screenshot below.
![image](https://user-images.githubusercontent.com/444878/152707025-b99d6bd9-3561-4d43-aba8-3c8fbc710814.png)

### Steps To Reproduce

Go to a folder and set it to group files by the tags.
Go to another folder.
Go back to the first folder.
That's it.

### Expected behavior

Whenever you enter such folder, It should be displaying the files grouped by the color tags.

### Files Version

2.1.5.0

### Windows Version

Windows 11 21H2 22000.434

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8011472/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8011473/debug_fulltrust.log)

**Comment by gave92** [comment]
Merging with #6844
