### ISSUE TITLE
Files via Chocolatey Package Manager is Outdated

### ISSUE THREAD

**Issue by ThisNekoGuy** [files-community/Files#8196]
### Description

The Chocolatey Package Manager package for Files is missing a maintainer and had it's last update in October 5th of 2021.

### Steps To Reproduce

1. Go to https://community.chocolatey.org/packages/files#files
2. See that it's out of date and is missing a maintainer on the left
3. Optionally, install Chocolatey and Files via Chocolatey with: `choco install files` and compare it with current release(s)

### Expected behavior

- For files to have a Chocolatey package maintainer
- For Files to be up to date via Chocolatey

### Files Version

Version: 2.0.0.0 OS Version: 10.0.19042.1466

### Windows Version

Edition	Windows 10 Home Version	20H2 Installed on	‎12/‎7/‎2019 OS build	19042.1466 Experience	Windows Feature Experience Pack 120.2212.3920.0

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/28468662/152708673-21941958-c1b3-4646-bc40-5f917165b5ea.png)

**Comment by yaichenbaum** [comment]
We don't have plans to support a Chocolatey version of Files, the previous maintainer did a great job keeping the app up to date but that was a separate effort, and we don't plan to provide an official package.
