### ISSUE TITLE
Default explorer

### ISSUE THREAD

**Issue by Agility17** [files-community/Files#8197]
### Description

Is there a way you can set this as your default file explorer like if I open a folder on my desktop it opens the files app?

### Expected behavior

Open as default 

### Files Version

2.1.5

### Windows Version

Windows Feature Experience Pack 1000.22000.466.0

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/70218994/152719951-781879b9-7813-4bd5-9dba-4e2ddcfdefbb.png)

**Comment by yaichenbaum** [comment]
https://files.community/docs/configuring/replace-file-explorer

**Comment by FahimKamal** [comment]
I also have the same issue. 
![image](https://user-images.githubusercontent.com/47342396/152726085-5336e7be-92d1-4810-8b2e-f33d2be3f476.png)
I tried to turn this on but still not working. Every time I'm trying to open a folder its opening in default file explorer. 

![image](https://user-images.githubusercontent.com/47342396/152726358-4ebaeb1a-5286-40c8-8f6d-30c7cc3786c4.png)
This is my Windows version.
