### ISSUE TITLE
In-app Update from Github Releases Feature

### ISSUE THREAD

**Issue by ThisNekoGuy** [files-community/Files#8200]
### What's the Problem?

For end-users, the install process from `Releases` is unusual and the `Microsoft Store` version of Files being out of date leads the Releases to be the only option to use every time one would install or update it.

### Solution/Idea

- Provide an installer for Files for these users (if possible)
- Provide an in-application update option that pulls from Github's releases for Files and automate the update

### Alternatives

The only other updating mechanism, aside from this, that I can think of at the moment is updating the existing off-site package management options used in the past (like the MS Store and Chocolatey), however, I was told that these are unsupported distribution options.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish a simple and independent update mechanism | Must |
| This proposal will allow end users to accomplish installation in an expected and straightforward manner; not driving them away due to the absence of such | Should |
| This proposal will allow developers to accomplish release installation instructions for average end-users | Could |
| This proposal will allow end users to accomplish not needing to ask basic install questions | Won't |

(Please correct me if I haven't filled this out properly)

### Files Version

Version: 2.1.5.0 OS Version: 10.0.19042.1466

### Windows Version

Edition	Windows 10 Home Version	20H2 Installed on	‎12/‎7/‎2019 OS build	19042.1466 Experience	Windows Feature Experience Pack 120.2212.3920.0

**Comment by gave92** [comment]
A recent change from Microsoft broke auto update for the GitHub version. We're hoping they get it fixed soon.

**Comment by ThisNekoGuy** [comment]
@gave92 Would not having a self-reliant infrastructure for this be better than begging Microsoft to fix it with an unknown timeline?

Not saying that Files can't have MS Store updates, but there's obviously no stable fallback plan in place when the default provider is the only provider.

**Comment by gave92** [comment]
\+ @yair100 Do you have any news/ideas about this?

**Comment by yaichenbaum** [comment]
@ThisNekoGuy the GitHub release version is specific for offline devices as it doesn't have auto update. To download Files, we recommend using the sideload link in the readme file.

**Comment by ThisNekoGuy** [comment]
@yair100 I'm aware; to clarify, I was suggesting that the function I mentioned be made a user triggerable button in Files and not necessarily an auto-update feature.

This naturally wouldn't impact offline users but it does directly impact online users that prefer to get their updates without having to go out of the way to sideload for every minor or major release and instead do so from the comfort of Files

**Comment by yaichenbaum** [comment]
@ThisNekoGuy the sideload version of Files has auto update

**Comment by ThisNekoGuy** [comment]
@yair100 
Ah, I was unaware of this; it isn't mentioned on https://files.community/ , the Github `reamdme.md`, nor in-app so I was under the impression that it simply didn't have it without the currently broken Microsoft Store's update feature.

Apologies for the confusion
