### ISSUE TITLE
Missing the advanced file view feature from the stock explorer

### ISSUE THREAD

**Issue by Milvvy** [files-community/Files#8201]
### What's the Problem?

The project is great. Keep it up. However, I'm dearly missing the advanced file view feature from the stock windows explorer. Here's the thing I'm on about.
![Advanced view](https://user-images.githubusercontent.com/99170984/152750193-1dc425ae-b6a6-4216-9dd4-a0acf3d5f033.png)

### Solution/Idea

My guess, it would be simpler to copy the existing GUI to Files 2.1. It could be listed as an option in the settings menu.

### Alternatives

-

### Files Version

2.1.5.0

### Windows Version

Windows 21H2

**Comment by gave92** [comment]
What of those options you miss the most?
