### ISSUE TITLE
SVG thumbnails NOT SHOWING

### ISSUE THREAD

**Issue by bernbilazon** [files-community/Files#8202]
### Description

SVG thumbnails not showing when viewing in icons after update

### Expected behavior

It should show as per previous versions

### Files Version

Version: 2.1.5.0 OS Version: 10.0.22000.434

### Windows Version

Windows 11 Pro 21H2 22000.434

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/16414628/152754250-20160546-1478-4315-86e0-896929b9824e.png)

**Comment by yaichenbaum** [comment]
Merging with #8376
