### ISSUE TITLE
Dragging Tab results in app crashing

### ISSUE THREAD

**Issue by bnbagiz** [files-community/Files#8203]
### Description

When i have two tabs open and drag one out to the bar to open as a new window, the app crashes

### Steps To Reproduce

1. open folder in new tab
2. drag the tab out of the bar to open in a new window

### Expected behavior

having two "tabs" in separate windows

### Files Version

Version: 2.1.5.0

### Windows Version

OS Version: 10.0.19043.1466

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8014347/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8014348/debug.log)

**Comment by gave92** [comment]
Merging with #7838

**Comment by gave92** [comment]
Would you be able to post a screen recording of this?
