### ISSUE TITLE
"Unpin from taskbar" and "Unpin from Start" are shown in Win11 but don't work

### ISSUE THREAD

**Issue by manfromarce** [files-community/Files#8205]
### Description

"Pin to Start" and "Pin to Taskbar" are currently not shown in Files context menus, while Windows Explorer has this feature.
However, if a shortcut or exe file has already been pinned, the "Unpin" command is sometimes displayed on Windows 11 (but does not work). It's not very consistent, for example I noticed that on the Microsoft Word shortcut only unpin from start is shown and unpin from taskbar is hidden, while on other shortcuts both are displayed.
It seems that they are always hidden on Windows 10 instead.

### Steps To Reproduce

1. On Windows 11, open Files and right-click on an item that has already been pinned to Start or the taskbar
2. Choose "Unpin from Start / Taskbar"

### Expected behavior

These entries should be hidden, unless we find a way to get both Pin and Unpin to work like on Windows Explorer.

### Files Version

Version: 2.1.5.0 OS Version: 10.0.22000.469

### Windows Version

Windows 11 21H2 22000.469

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/45036600/152788799-e06984d7-9992-4504-a097-a7e10af55c7c.png)

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?

**Comment by manfromarce** [comment]
Yes, these are still displayed for already pinned apps.

**Comment by Josh-65** [comment]
if you unpin and repin them does it still say like that

**Comment by manfromarce** [comment]
It seems that for some shortcuts (e.g. Visual Studio Code) they disappear if I unpin and pin again, but they come back when Files is restarted and are still present for shortcuts to Store apps.

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
Does it work in File Explorer?

**Comment by manfromarce** [comment]
It works in Windows Explorer. However, Pin doesn't appear in Files context menu (maybe the implementation is incomplete), so Unpin probably shouldn't be there either (at least until they're both fixed).

**Comment by yaichenbaum** [comment]
You might need the preview version https://files.community/download/preview
