### ISSUE TITLE
Programm crush

### ISSUE THREAD

**Issue by DoubleTroubleOf** [files-community/Files#8209]
### Description

Sometimes "Files" is crushing without any reason. For example I could exploring different folders, maybe delete some files.
After  some time program is running and I am going to do smth else - "Files" is crushing.

Device:      ASUS ZenBook Duo 14 UX482EA-HY034R
OS:             Windows 11 Pro (21H2): Microsoft Windows [Version 10.0.22000.469] 

### Expected behavior

I think that progrmam must not crush periodicaly

### Files Version

2.1.5.0

### Windows Version

Windows 11 Pro (21H2): Version 10.0.22000.469 

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8017075/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8017077/debug_fulltrust.log)

**Comment by gave92** [comment]
Thanks for the report. Closing this as the errors reported in the logs are already present in other issues.
