### ISSUE TITLE
3rd Party Apps Context Menu’s

### ISSUE THREAD

**Issue by yodaluca23** [files-community/Files#8212]
### What's the Problem?

If I right-click on anything it will not show me my 3rd part context menu shortcuts…

### Solution/Idea

Make it show my 3rd party context menu shortcuts.

### Alternatives

Have an option not to and to show the 3rd party context menu short cuts.

### Priorities

| Have the ability to show 3rd party context menu shortcuts. | Must |
| Have an option to turn them on and off. | Should |
| Have the option to turn specific ones on and off  | Could |

### Files Version

2.1.7

### Windows Version

Windows 11 21H2 22000.469

### Comments

An example of a context menu short cut is for when you download Malwarebytes then when you right click on something in file explorer then it has the option to “Scan With Malwarebytes”.

**Comment by yaichenbaum** [comment]
Third party shell extensions are supported, can you open a new issue using the bug report template and include the log files?
