### ISSUE TITLE
Status still not showing everywhere

### ISSUE THREAD

**Issue by brucebinder** [files-community/Files#8214]
### Description

See subject

### Steps To Reproduce

Display certain folders

### Expected behavior

Status to show for all folders displayed

### Files Version

Version: 2.1.9.0 

### Windows Version

OS Version: 10.0.22000.469

### Relevant Assets/Logs

None

**Comment by yaichenbaum** [comment]
@brucebinder can you upload the log files?

**Comment by Josh-65** [comment]
You dont need to keep opening new issues. #5704 and #7922 should be merged with this one
