### ISSUE TITLE
Bug: Emptying recycle bin doesn't display operation in the status center

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#8215]
### Description

Using the sidebar right click menu an opration for items beeing delted doesnt show the status center at all

### Steps To Reproduce

1. Delete some items
2. Right click Recycle Bin and press on empty
3. Observe that no operation is added to the status center

### Requirements 

- Status center should show progress of the file operation

### Files Version

4.1.7.0

### Windows Version

10.0.19043.1503

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8019574/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8019575/debug.log)

**Comment by gave92** [comment]
True, but we can't get progress for that operation. But should show an operation in progress regardless. Windows might not even report completion for this, to be checked.
