### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by R4z0rBl8D3** [files-community/Files#8217]
### What's the Problem?

When I search or open a folder that I have not opened before, it uses a lot of my cpu.

### Solution/Idea

You could add a setting that allows me to slow the search speed so it won't use as much cpu, the built-in file explorer uses way less of my cpu.

### Alternatives

the built-in file explorer

### Priorities

| Capability | Priority |
| :Slow down search to lower cpu usage | :Could |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.1.7.0

### Windows Version

Windows 10 Version 21H1

**Comment by gave92** [comment]
Merging with#4180
