### ISSUE TITLE
Add a way to add to the any file/folder to the Favorites Folder.

### ISSUE THREAD

**Issue by yodaluca23** [files-community/Files#8218]
### What's the Problem?

Add a way to add any file/folder to the Favorites Folder.

### Solution/Idea

Have a right-click option to add it to favorites on any folder and an option when right-clicking favorites to browse for a folder to add.

### Alternatives

Have it a complicated way of doing it in settings.

### Priorities

| Be able to add any file/folder to the favorites submenu. | Must |
| Be an option to browse for a folder by right-clicking on favorites. | Should |
| Have a right-click option on any folder/file to add it to the favorites submenu. | Could |

### Files Version

Version: 2.1.5.0 OS Version: 10.0.22000.469

### Windows Version

Edition	Windows 11 Home Version	21H2 Installed on	‎10/‎29/‎2021 OS build	22000.469 Experience	Windows Feature Experience Pack 1000.22000.469.0

**Comment by yaichenbaum** [comment]
You can already do this by right click a folder and clicking on "pin to favorite's"
