### ISSUE TITLE
Allow expanding folders in the navigation pane

### ISSUE THREAD

**Issue by JacksonCampbell99** [files-community/Files#8220]
### What's the Problem?

I like to see and work with the folders in my OneDrive and `This PC`. Windows File Explorer has those two folders expanded in the navigation pane by default when I open a window to show `Documents`, `Pictures`, `Videos`, etc. in both of those folders. Files, on the other hand, has no option to expand in the navigation pane other than `Favorites`, `Drives`, `Cloud Drives`, `Network Drives`, which in and of themselves are useless other than to expand and show the folders or local drive or whatever in them, but will not expand those folders at all. That is my major downside with this app, because I don't want to use Favorites for the folder one directory in OneDrive to `This PC`. Granted, they show up in `Home`, but I'd rather be able to jump around between them in the left navigation pane. Poor use of the navigation pane if it can't expand at all either.

### Solution/Idea

Enable expanding at least one level to reveal `Documents`, `Downloads`, `Pictures`, `Videos`, etc. in the left navigation pane for each drive including `Home` since it is the replacement of `This PC` in File Explorer.

### Alternatives

Adding each folder to favorites could be an alternative, but I like to reserve favorites for the few folders I access regularly that are buried halfway down inside other folders instead of putting all the main folders from `This PC` in there.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to expand the main drives at least one level in the navigation pane | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow end users to expand to any folder in the navigation pane just like Windows Exploror | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.1.7.0

### Windows Version

Windows 11 Pro 21H2 22000.469

**Comment by gave92** [comment]
Could you check if enabling "show libraries on the sidebar" from Settings > Appearance > Sidebar does about what you need?

**Comment by JacksonCampbell99** [comment]
@gave92 I know about libraries in Files and File Explorer, and that serves its own purpose which is similar. While that may potentially give me all the folders I need, it would be blending the local and OneDrive together (viewing folders in `This PC`\`Videos` and `OneDrive`\`Videos` together in one `Videos` library folder). While a couple of those folders are the same like Documents, I still just want to be navigating between the folders of OneDrive and the folders of `This PC` (`Home`), which is where I base my navigation and my organization of files. I want to click right into `Downloads` when I'm buried in `Documents` or jump from `Documents` to `Music`. Another thing is that `Downloads`, for example, is not in the `Libraries` pane.
<img width="118" alt="image" src="https://user-images.githubusercontent.com/76508020/152938563-53a255ad-8642-43ba-9184-833ca63778f0.png">

**Comment by yaichenbaum** [comment]
We don't have plans to add a tree view pane but we're tracking requests for a tree view layout in #1928

**Comment by yair100** [comment]
@JacksonCampbell99 Tree View is currently available in preview https://files.community/download. It will be included in the next stable release.

**Comment by JacksonCampbell99** [comment]
4 years later.... Wow.
