### ISSUE TITLE
Capitalization error in navigation pane

### ISSUE THREAD

**Issue by JacksonCampbell99** [files-community/Files#8221]
### Description

"Drive" in `Network drive` is not capitalized. All other titles in the navigation pane have both words properly capitalized including `Cloud Drives` and `Recycle Bin` as illustrated in the screenshot below.

### Steps To Reproduce

1. Open the app
2. Look at the navigation pane
3. See that the "drive" in `Network drive` isn't capitalized

### Expected behavior

Proper proofing.

### Files Version

Version: 2.1.7.0 OS Version: 10.0.22000.469

### Windows Version

Windows 11 Pro 21H2 22000.469

### Relevant Assets/Logs

<img width="187" alt="image" src="https://user-images.githubusercontent.com/76508020/152935379-1b276fdc-099c-46af-af80-ea2719c78f5b.png">

**Comment by yaichenbaum** [comment]
@JacksonCampbell99 would you be intrested in trying to fix this?

**Comment by JacksonCampbell99** [comment]
@yair100 It would be fun if I knew how to code.

**Comment by d2dyno1** [comment]
Closed with #8357
