### ISSUE TITLE
Categorize `Home` by itself in the navigation pane

### ISSUE THREAD

**Issue by JacksonCampbell99** [files-community/Files#8223]
### What's the Problem?

This sort of goes with my other [request](#8220) (#8220) for expanding folders in the navigation pane, because in order to expand `Home`, it would have to be its own thing in the navigation pane, not under favorites. Since `Home` is this File app's substitute for `This PC`, it would make sense for it to be by itself in the pane since `This PC`/`Home` is used far more than navigating through the main drive. So, having it by itself and with the [ability to expand](#8220) to see `Documents`, `Downloads`, `Pictures`, `Videos`, etc. in the navigation pain would be great.

### Solution/Idea

See above.

### Alternatives

None.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to use Home outside of favorites | Must |
| This proposal will allow developers to integrate expanding Home to show folders in it in the navigation pane without Home being under favorites | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.1.7.0 OS Version: 10.0.22000.469

### Windows Version

Windows 11 Pro 21H2 22000.469

**Comment by yaichenbaum** [comment]
We don't have plans for this as home is considered a favorite item that can be unpinned

**Comment by JacksonCampbell99** [comment]
@yair100 How do you get to `Home` if it's unpinned?

**Comment by yaichenbaum** [comment]
@JacksonCampbell99 you can type `home` in the adress bar and it's also the default page when opening a new tab.
