### ISSUE TITLE
 Option to hide "Ongoing tasks"  button

### ISSUE THREAD

**Issue by KumarjitDey** [files-community/Files#8224]
### What's the Problem?

Not a problem. I just feel it isnt necessary to notify every time I copy paste file from one folder to another or make such small changes

### Solution/Idea

Introduce an option in Settings > Preference called "Disable Ongoing tasks button"

### Alternatives

To toggle on and off between ongoing tasks,

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.7.0

### Windows Version

Windows 11 Home  21H2 22000.438

### Comments

![Ongoing tasks](https://user-images.githubusercontent.com/99241036/152937464-7f1adde9-4fbd-4284-96b8-6c9f7f382572.png)

**Comment by Josh-65** [comment]
This doesnt seem to add any benfit since it's quite out of the way right now. Also just extra work to make

**Comment by yaichenbaum** [comment]
We don't have plans to make this change
