### ISSUE TITLE
Add an option to hide bottom bar

### ISSUE THREAD

**Issue by KumarjitDey** [files-community/Files#8225]
### What's the Problem?

Not really a problem. For those who got minimal tastes, you could add an option in preferences to Hide the bottom bar which displays number of items, as it is not really that necessary.

### Solution/Idea

Settings > Appearance > Bottom Bar > Toggle on or off.

### Alternatives

Settings > Appearance > Bottom Bar > Toggle on or off.

### Priorities

This proposal will allow end users to accomplish X | Should |

### Files Version

2.1.7.0

### Windows Version

Windows 11 Home  21H2 22000.438

### Comments

![Screenshot 2022-02-08 125804](https://user-images.githubusercontent.com/99241036/152938573-90748a77-6d03-4df2-b2b4-a758d7ec3daf.png)

**Comment by yaichenbaum** [comment]
@KumarjitDey thank you for your feedback, we don't have plans to implement this option right now.
