### ISSUE TITLE
Add support for reordering recycle bin item

### ISSUE THREAD

**Issue by zmr242538** [files-community/Files#8227]
### What's the Problem?

The Recycle bin folder now under the pinned folders, which is not in the place for system folder.

### Solution/Idea

The Recycle bin folder is a system folder, it should first prioritized.

### Alternatives

Let others suggest for more alternatives. I just comment on some point you may missed.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |

### Files Version

2.1.7.0

### Windows Version

Windows 11 21H2 22000.469

### Comments

![image](https://user-images.githubusercontent.com/99237931/152942624-1f7f136e-351a-4821-8e90-9cfdab322f74.png)

**Comment by yaichenbaum** [comment]
This issue should be resolve with #9207
