### ISSUE TITLE
Thumbnail not showing and Icon on section has gone sometime

### ISSUE THREAD

**Issue by laspersonas** [files-community/Files#8228]
### Description

Thumbnail not showing and Icon on section has gone sometime 
https://imgur.com/a/HKIYogL

### Steps To Reproduce

Thumbnail not showing and Icon on section has gone sometime 
https://imgur.com/a/HKIYogL

### Expected behavior

Thumbnail not showing and Icon on section has gone sometime 
https://imgur.com/a/HKIYogL

### Files Version

2.1.7.0

### Windows Version

10.0.22543.1000

### Relevant Assets/Logs

Thumbnail not showing and Icon on section has gone sometime 
https://imgur.com/a/HKIYogL

**Comment by gave92** [comment]
Could you post the two app's debug logs? You can get them from settings > about
