### ISSUE TITLE
Layout options are broken in v2.1.7

### ISSUE THREAD

**Issue by UP890684** [files-community/Files#8230]
### What's the Problem?

None of the layout options work for a Google Drive. They work just fine for OneDrive.
<img width="943" alt="image" src="https://user-images.githubusercontent.com/62099599/152965771-69036b47-6524-4626-b867-eb1895e8ec23.png">

### Solution/Idea

This could be due to one of a multitude of things. One thing I noticed though, was that Google Drives (formerly Google File Stream) are not actually considered Cloud Drives. I guess that does make sense since although they are synced to the cloud they are actually also written to disk.

### Alternatives

No alternatives, this could be a quick fix.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Microsoft Store Version2

### Windows Version

Windows 11 Home 21H2 22000.469

**Comment by yaichenbaum** [comment]
@UP890684 is this an issue in v2.1.7?

**Comment by yaichenbaum** [comment]
This issue should be resolved in v2.1.13
