### ISSUE TITLE
Add confirmation when removing bundle

### ISSUE THREAD

**Issue by UP890684** [files-community/Files#8231]
### What's the Problem?

Was far to easy to accidently remove a bundle I had painstackingly added folders one by one to.

### Solution/Idea

Include an are sure you want to remove bundle promt.

### Alternatives

To make it easier to through a bundle together make it so that you can add multiple files/folders to the bundles at once.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Microsoft Store Version 2

### Windows Version

Windows 11 Home 21H2 22000.469

**Comment by yaichenbaum** [comment]
Bundles are no longer being developed and will be replaced with a tags widget.
