### ISSUE TITLE
Add 7zip integration

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#8232]
### What's the Problem?

To compress/extract formats other than zip, you need to install external plugins. It is not possible to browse these formats in Files.

### Solution/Idea

We could use the free library sevenzip to offer other formats (exploration/compression/extraction). This will then work without installing any plugins. 

For information, we find this kind of UI in Linux.
![compress1](https://user-images.githubusercontent.com/46631671/152986714-9d74e80d-4aa1-42f7-b827-7d9794bb2389.png)
![compress2](https://user-images.githubusercontent.com/46631671/152986718-f0155cfa-63dc-4101-82b2-856f65fafa17.png)

### Alternatives

Use another library.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
@cinqmilleans we have a branch with 7zip integration but there are a couple of issues with it so it hasn't been merged yet.

**Comment by gave92** [comment]
Done #9633
