### ISSUE TITLE
Context menu on the sidebar

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#8233]
### What's the Problem?

It is possible to hide sections from the sidebar using the section's contextual menu.
It is not possible to view a section without opening the settings menu.

### Solution/Idea

We can add a context menu on the sidebar (there is none yet) to show/hide all sections.

### Alternatives

None

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
This issue should be resolved with #8317
