### ISSUE TITLE
Question? 

### ISSUE THREAD

**Issue by MalachiRecro** [files-community/Files#8238]
### What's the Problem?

Is there a way to sort all files by "Date Created" and "Desceding" and for it to stay that way everytime I open the folder?

### Solution/Idea

Potentially have a default sort setting that you can save 

### Alternatives

have it save where you left off in each folder 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by Josh-65** [comment]
sort options are here
![image](https://user-images.githubusercontent.com/26977075/153076443-d939dabe-77d7-413a-8174-e5a9b080b7db.png)
