### ISSUE TITLE
Bug: Navigation items take around 45 seconds to load

### ISSUE THREAD

**Issue by Spawn43** [files-community/Files#8243]
### Description
Whenever I open up Files this is what it looks like - 
![image](https://user-images.githubusercontent.com/62122244/153066085-49366b63-6d4b-41b7-abae-5c862e2d2ba5.png)
Note the lack of any drives or naviagtion on the side.

After about 45 seconds of waiting it'll actually load everything.
![image](https://user-images.githubusercontent.com/62122244/153066305-59ead974-3fba-4496-a4f7-40410b555877.png)

If I have a direct link to a different drive it will load it properly meaning it is possible for me to quickly get to drives by creating shortcuts to them. I'm new to using Files and this issue is making using it very difficult since I can't access 80% of my files without a massive wait.

### Steps To Reproduce
1. Open files.

### Files Version
Version: 2.1.5.0
OS Version: 10.0.19043.1466

### Windows Version
Windows 10 Pro 19043.1466

### Relevant Assets/Logs
[debug.log](https://github.com/files-community/Files/files/8028020/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8028021/debug_fulltrust.log)

**Comment by gave92** [comment]
Thanks for the report. Could you upload the two app's log files (from settings > about > open log location)?

**Comment by Spawn43** [comment]
> Thanks for the report. Could you upload the two app's log files (from settings > about > open log location)? Also please add the app version to the description

Done that now :)

**Comment by gave92** [comment]
Do you happen to have any disconnected network drives?

**Comment by Spawn43** [comment]
No, I did have one months ago which i disconnected and fully unmapped long before switching to files

**Comment by iNether** [comment]
Same to me, much longer with Files

**Comment by yaichenbaum** [comment]
@gave92 is this still an issue in `main`?

**Comment by gave92** [comment]
Yeah sometimes I've seen it happen.

**Comment by yaichenbaum** [comment]
I've seen this as well, is something blocking the thread from running?

**Comment by yaichenbaum** [comment]
@Spawn43 can you confirm that this is resolved in the latest preview build? https://files.community/download/preview
