### ISSUE TITLE
Some file types are not shown in the "New" menu

### ISSUE THREAD

**Issue by manfromarce** [files-community/Files#8244]
### Description

Some file types (e.g. bitmap image and microsoft access database) are present in the Explorer "New" menu but are not displayed in Files (see screenshot below).

### Expected behavior

The same entries as Windows Explorer should be shown.

### Files Version

Version: 2.1.7.0

### Windows Version

Windows 11 21H2 22000.469

### Relevant Assets/Logs

Windows Explorer:
![Screenshot (64)](https://user-images.githubusercontent.com/45036600/153066420-2fa8931c-a6db-4c80-8368-34457d2f70b2.png)

Files:
![Screenshot (65)](https://user-images.githubusercontent.com/45036600/153066436-b5ea9a9a-40e4-4686-90d5-d8a6f6e52f86.png)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #8598
