### ISSUE TITLE
Files fails to open box folder

### ISSUE THREAD

**Issue by D4b4d00** [files-community/Files#8246]
### Description

Just started using Files. It will not open my Box folder and subfolders. All other folders OK. One of the Box subfolders is also linked to Mega. The screen flashes off and on and all subfolders are unavailable.

### Steps To Reproduce

1. Click on Files
2. Open Cloud Drives
3. Click on Box - screen flashes
4. Double click on any sub folder in Box
5. Get message that "This folder is empty" which it is not.

### Expected behavior

I would expect when clicking on Box for the subfolders to be displayed and then by clicking on the subfolders that the files would be displayed.

### Files Version

Version: 2.1.7.0 OS Version: 10.0.19043.1466

### Windows Version

Edition	Windows 10 Home Version	21H1 Installed on	‎07/‎10/‎2020 OS build	19043.1466 Experience	Windows Feature Experience Pack 120.2212.3920.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8027060/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8027061/debug_fulltrust.log)

**Comment by gave92** [comment]
Merging with #7428
