### ISSUE TITLE
Add samples to date formats 

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#8249]
### What's the Problem?

The settings menu allows you to select the date format. This format is named and the user does not know which to choose.

### Solution/Idea

Modify the combobox template to display formatted today's date below the format name.

### Alternatives

Display formatted today's date in the current format to the left of the combobox.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
Would it be better to remove the date format setting and just follow the Windows default?

**Comment by cinqmilleans** [comment]
@yair100 Huge question. Here is my very personal humble opinion.
1) The system format seems to me less practical, less pleasant and less pretty. It contravenes modern usage (facebook, ...). It lacks information (day of the week) and requires more effort from the user (August = 8).
2) The application format provides added value compared to File Explorer.
3) It is debatable whether the system format should be removed. I know we have usage statistics. We can check if the system option is used.
4) The previous point should be qualified because the user probably changes this option very little since he does not know what it changes in practice.
5) Perhaps a 3rd option is missing: the international format (YYYY-MM-DD). This format has the advantage of reconciling chronological and nominal order.
6) This option is not annoying if it remains an option that is only available in the settings menu. It never bothers the user.
7) In the future, we may add an expert mode in the settings menu to show some less used options. VLC has adopted this method.

**Comment by yaichenbaum** [comment]
@cinqmilleans can you upload a screenshot of the options in VLC?

**Comment by Conquesttintin** [comment]
Number 5 seems like a werry good solution :)

**Comment by cinqmilleans** [comment]
@yair100 Here are the screenshots. VLC has many many many options. We are not yet at such a stage.
VLC uses 2 very distinct settings windows.

Kodi uses settings levels (Simple, Advanced, Expert, Master, ...). Each option has a level and changing the level simply changes the visible options. I was thinking more about this principle but we don't have enough to have 2 levels yet. It was just an idea to know that we can have a lot of options because there are interface solutions for the settings.

Kodi
![kodi](https://user-images.githubusercontent.com/46631671/154012260-863b9c16-9c9e-4e21-a1f1-fde909b7d1a8.jpg)

VLC
![interface_simple](https://user-images.githubusercontent.com/46631671/154011777-8be7d9bf-75de-4641-adcb-8bf39fc29015.png)
![interface_advanced](https://user-images.githubusercontent.com/46631671/154012256-b5f5636d-5a7d-48bf-a3d3-1fd878343e2f.png)
![video_simple](https://user-images.githubusercontent.com/46631671/154011785-ae47621a-c050-4edb-a12b-a44c9b5a6749.png)
![video_advanced](https://user-images.githubusercontent.com/46631671/154011781-1b0aae15-6653-42cf-ab6c-98206ff124c8.png)

**Comment by yaichenbaum** [comment]
@cinqmilleans I should have specified, I meant the options you referenced for the date format.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #8875
