### ISSUE TITLE
keine automatische Aktualisierung im Net

### ISSUE THREAD

**Issue by dieter1731** [files-community/Files#8250]
### Description

Sehr geehrte Damen und Herren, wenn ich mit dem Programm in einem (lokalen) Netzwerkordner Dateien kopiere/einfüge/entferne, dann wird die Ansicht nicht aktualisiert. Erst, nachdem ich F5 drücke, erhalten ich die Aktualisierung. 
Ließe sich daran was machen?

### Expected behavior

Eigentlich erwarte ich, dass er die Ansicht von selber aktualisiert. Auf dem lokalen Laufwerk funtioniert das auch.

### Files Version

Version: 2.1.7.0 OS Version: 10.0.19043.1503

### Windows Version

Windows 10

### Relevant Assets/Logs

Hier gibt es nichts anzumerken.

**Comment by gave92** [comment]
It's a known issue, tracked in #5869
