### ISSUE TITLE
CRASHING

### ISSUE THREAD

**Issue by zex-e** [files-community/Files#8252]
### Description

the app suddenly shut it self down with no errors or anything

### Expected behavior

maybe when i try to copy a file from my pc to other device?

### Files Version

Version: 2.1.5.0 OS Version: 10.0.19044.1466

### Windows Version

lastest

### Relevant Assets/Logs

like i said no errors appaired

**Comment by Josh-65** [comment]
You will need to upload the logs files. You can get them in files settings > about > open log folder.

**Comment by gh0sti** [comment]
latest update to files seems to be broken
