### ISSUE TITLE
Bug: Can't change library directory

### ISSUE THREAD

**Issue by Pietro228** [files-community/Files#8253]
### Description

When I click on "default" button it wouldn't change the default directory.
![obrazek](https://user-images.githubusercontent.com/53868994/153204695-7f41e337-c754-4e79-8375-57118f30affb.png)

### Steps To Reproduce

1. Create library.
2. Go to properties.
3. Add directory.
4. Select the new added directory and set it as default.

### Expected behavior

Select the new directory as default directory.

### Files Version

2.1.11.0

### Windows Version

10.0.22000.466

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8032834/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8032835/debug.log)

**Comment by gave92** [comment]
Relevant from log files:

> 13:49:09.0035|ERROR|UnhandledExceptionTrapper|Byl učiněn pokus načíst program v nesprávném formátu. (0x8007000B) 	System.BadImageFormatException: Byl učiněn pokus načíst program v nesprávném formátu. (0x8007000B) at Vanara.PInvoke.Shell32.IShellLibrary.LoadLibraryFromItem(IShellItem library, STGM grfMode) at FilesFullTrust.Helpers.ShellLibrary2..ctor(IShellItem iItem, Boolean readOnly) at FilesFullTrust.MessageHandlers.LibrariesHandler.OnLibraryChanged(WatcherChangeTypes changeType, String oldPath, String newPath) at System.Threading.Tasks.Task.<>c

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by Josh-65** [comment]
Yes
