### ISSUE TITLE
Always Show Icons, never thumbnails

### ISSUE THREAD

**Issue by A-A-Haggag** [files-community/Files#8257]
### What's the Problem?

Always Show Icons, never thumbnails feautre

### Solution/Idea

Always Show Icons, never thumbnails feautre

### Alternatives

Always Show Icons, never thumbnails feautre

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

last one

### Windows Version

windows 11

### Comments

if someone could add this feature it would be great help

**Comment by yaichenbaum** [comment]
Merging with #6421
