### ISSUE TITLE
Sluggish,especially 1stt time

### ISSUE THREAD

**Issue by brucebinder** [files-community/Files#8259]
### Description

When I first start a new version, it takes a long time to be usable. And then it is somewhat slow.

And, I still do not see Status on many folders.

### Steps To Reproduce

Start Files after new release and display certain folders

### Expected behavior

Start faster and show Status for all folders

### Files Version

Version: 2.1.13.0

### Windows Version

OS Version: 10.0.22000.493

### Relevant Assets/Logs

None

**Comment by yaichenbaum** [comment]
@brucebinder we welcome user feedback but you can't keep opening duplicate issues.
