### ISSUE TITLE
the app does not load the thumbnails and crashes

### ISSUE THREAD

**Issue by cleuton4k** [files-community/Files#8262]
### Description

the app doesn't load the thumbnails of some files (especially images) and after closing and opening the app, the storage drives section disappears.

### Expected behavior

the app doesn't load the thumbnails of some files (especially images) and after closing and opening the app, the storage drives section disappears.

### Files Version

2.1.13

### Windows Version

w10 21h1

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8036155/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8036156/debug_fulltrust.log)
![0](https://user-images.githubusercontent.com/90144967/153288575-6369d660-4579-4171-91e5-78ed1fe889a1.jpg)
![SharedScreenshot](https://user-images.githubusercontent.com/90144967/153288577-36257d85-9a20-4d2e-8ad6-4a6d4e51e204.jpg)

**Comment by yaichenbaum** [comment]
Merging with #8376
