### ISSUE TITLE
Files break when I try to open the WSL filesystem

### ISSUE THREAD

**Issue by david-minaya** [files-community/Files#8263]
### Description

Files break when I try to open the WSL filesystem.

WSL 2
Ubuntu-20.04

### Steps To Reproduce

1. Open File
2. Try to open the WSL dir

### Expected behavior

Can open the WSL dir on Files

### Files Version

Versión: 2.1.5.0 OS Version: 10.0.19043.1466

### Windows Version

Windows 10 Home 19043.1466

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8036240/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8036241/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
@david-minaya is this still an issue in the preview version? https://files.community/download/preview
