### ISSUE TITLE
Files + QuickLook: Esc doesn't hide/close the QuickLook window

### ISSUE THREAD

**Issue by matheussouza9** [files-community/Files#8264]
### Description

Using [QuickLook](https://www.microsoft.com/store/productId/9NV4BS3L1H4S) with Files, I'm not able to hide/close the QuickLook window by pressing `esc`

Ps.: On Windows Explorer, after open the QuickLook window by pressing `space bar`, it receives the focus and the `esc` key works. However, Files doesn't do that. The focus remains on Files.

### Steps To Reproduce

1. Install [QuickLook](https://www.microsoft.com/store/productId/9NV4BS3L1H4S)
2. Open any file by pressing `space bar`
3. Your file should open inside a QuickLook window
4. Press `esc`
5. The QuickLook window still there

### Expected behavior

The QuickLook window should hide/close, just like Windows Explorer integration with QuickLook

### Files Version

Version: 2.1.7.0 OS Version: 10.0.22000.493

### Windows Version

Windows 11 Pro 21H2 22000.493

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/6036320/153289842-d7c91569-337d-44cd-bf4a-9e4ad266e439.png)

**Comment by gave92** [comment]
Merging with #792
