### ISSUE TITLE
Conflict dialog doesn't open

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#8265]
### Description

The conflict dialog doesn't open when it should

### Steps To Reproduce

Copy and paste an item to create a conflict

### Expected behavior

For the dialog to open

### Files Version

v2.1.13

### Windows Version

Windows 11

### Relevant Assets/Logs

NA

**Comment by gave92** [comment]
If you mean in the same directory it's done on ourpose

**Comment by yaichenbaum** [comment]
> Do you mean when pasting to the same directory or also in other cases? If it's the first it's done on purpose.

Is that new behavior?

**Comment by yaichenbaum** [comment]
@gave92 would it be possible to revert the change?

**Comment by yaichenbaum** [comment]
> You can revert anything you like :) Comes from request #3900, matches explorer, makes more sense (what's the point of showing "replace")..

There will be an option to rename files at some point but I see your point.

**Comment by gave92** [comment]
Lol sorry I was aggressive. If you wish it's a change easy to revert. If we add an option to choose a new file name from the conflict dialog it would make sense.
