### ISSUE TITLE
win+e for new windows

### ISSUE THREAD

**Issue by littleblack111** [files-community/Files#8266]
before while Im uisng the windows files I usually use win+e to add a new windows of files but I cant do it here it will just open a new tab and u can open new tab with ctrl+t so u can adda a setting saying win+e to open new windows,my english is poor some of it im using google translate Please excuse me
### What's the Problem?

I try to use win+e to open a new windows

### Solution/Idea

add a setting writting win+e to open new windows 

### Alternatives

idk

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.5.0

### Windows Version

Windows Home Inside Preview Build 22543.rs_prerelease.220122-2315(Im using DEV)

**Comment by littleblack111** [comment]
plzzzz help, this matter lot to me

**Comment by yaichenbaum** [comment]
@littleblack111 It's not exactly labeled the way you might expect but you can get the behavior you're looking for by turning on the option to open a new instance when opening an item from the jumplist.
![image](https://user-images.githubusercontent.com/39923744/153331116-a0750fa7-09bd-483d-b8fe-4af0a96bb32f.png)

**Comment by littleblack111** [comment]
wdym

**Comment by littleblack111** [comment]
where is it

**Comment by yaichenbaum** [comment]
Settings dialog > preferences > startup settings

**Comment by littleblack111** [comment]
sorry Im using chinease 
![image](https://user-images.githubusercontent.com/97672521/153520765-569b56cf-901a-49c9-9f46-4b88c9b6a11f.png)
