### ISSUE TITLE
Feature: Option to search only the current folder (not also the subfolders)

### ISSUE THREAD

**Issue by Slowwwww** [files-community/Files#8267]
### What's the Problem?

When searching in a folder that has many subfolders and many files in these subfolders the search becomes rather slow. 

### Solution/Idea

Add an option similar to the default file explorer to only search the contents of the current folder.

### Alternatives

Using the default file explorer

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Add option to search only the current folders contents | Must |
| Have the ability to easily switch between searching only the contents of the folder and searching the content of the folder and its subfolders | Must |

### Files Version

2.1.13.0

### Windows Version

Windows 10 21H2 19044.1526

**Comment by yaira2** [comment]
@Slowwwww can you try adding this to the search box? `*.* folder:"\CurrentDir"` (replace "CurrentDir" with the name of the folder)

**Comment by Slowwwww** [comment]
That does work, thanks for letting me know about that feature!

**Comment by yaira2** [comment]
Thanks for checking 👍
