### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by LuciferGmod** [files-community/Files#8270]
### Description

In the downloads folder, I selected a few files and clicked on the information. After receiving the information, I click "OK" in the window that opens and the application crashed.

### Steps To Reproduce

1. Go to the Downloads folder.
2. Select 5 files (in my case).
3.View folder properties.
4.Click on the "OK" button.

### Expected behavior

I expected that the application would not crash.

### Files Version

Version: 2.1.5.0

### Windows Version

Windows 10 Pro 21H2 19044.1466

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8038627/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8038628/debug_fulltrust.log)

- [ ]

**Comment by gave92** [comment]
Fixes in latest code
