### ISSUE TITLE
Slow to open Files

### ISSUE THREAD

**Issue by WereWolfix** [files-community/Files#8273]
### Description

every time I close Files and reopen it, it always takes a few seconds to load
I tried to restart my pc and reinstall the software but nothing changed.

### Expected behavior

I expect to open like the normal file explorer. Instantly.

### Files Version

2.1.13

### Windows Version

Windows 11 Insider Preview 22543.1000 (rs_prerelease)

### Relevant Assets/Logs

https://user-images.githubusercontent.com/45063794/153402471-a3e5fba4-e796-43af-acfe-d7ca72f472e8.mp4
[debug.log](https://github.com/files-community/Files/files/8040647/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8040648/debug_fulltrust.log)

**Comment by yaira2** [comment]
We're excited to share that startup performance will be significantly improved in the upcoming release of version 3. You can download the preview version from our website https://files.community/download.
