### ISSUE TITLE
Highlight active column in "Columns" view

### ISSUE THREAD

**Issue by amzon-ex** [files-community/Files#8274]
### What's the Problem?

I mostly use Files in the Columns view, as I find it handy. However, I find it difficult to figure out which column is currently "active" when performing operations. For instance, when I use the ribbon to create a new folder/file, or use the various quick options (cut/copy/paste...), figuring out where it will end up is not immediately obvious.

Let me be clear on this. I know that the currently "active" column is shown as the tab title and also in the address bar. Also, before doing the operation, clicking on an empty area in the column of interest activates it. However, there is no proper visual feedback mechanism that makes it immediately obvious.

### Solution/Idea

This is more like a quality-of-life improvement. If something like a little highlight could be put on the active column - or maybe a bar at the bottom - or whatever visual indicator that makes it immediately obvious where I currently am in the 5-6 or so columns that are open would be helpful.

### Alternatives

None so far

### Files Version

2.1.13.0

### Windows Version

Windows 11 21H2 22000.493

**Comment by yaichenbaum** [comment]
Merging with #5880
