### ISSUE TITLE
Add detailed file trasfer speed

### ISSUE THREAD

**Issue by AlbertM94** [files-community/Files#8276]
### Solution/Idea

Add a detailed description or even an option for a new window showing the copy/move progress with speeds and visuals like the original explorer.

### Alternatives

1. Add speed in "Ongoing Tasks"
2. Add new window option to show detailed progress w/ visual, speed, est. 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by Josh-65** [comment]
This is been talked about in #4811
