### ISSUE TITLE
Issue when installing

### ISSUE THREAD

**Issue by IbrahimAlIbrahimz** [files-community/Files#8277]
I tried installing it from Microsoft store and from GitHub (I pressed on the download button next to the preview button) it give me an error both times
![image](https://user-images.githubusercontent.com/95413094/153437102-c4a7239c-6ea6-4aff-9248-9dd45602e002.png)

**Comment by yaichenbaum** [comment]
@IbrahimAlIbrahimz thank you for your feedback, this doesn't appear to be an with Files, can you report this issue under MSIX or the MIcrosoft Store in the Feedback Hub?

**Comment by Josh-65** [comment]
try doing this from https://answers.microsoft.com/en-us/windows/forum/all/windows-10-does-not-install-updates-error/80fcf8c8-21d7-4e22-bceb-1dd88255658b

type services in the start menu and open it
Find the Windows Update service, right-click it, and then click Properties.
On the General tab, next to Startup type, make sure that Automatic is selected.
Next to Service status, check to see if the service is started. If it is not, click Start.

**Comment by IbrahimAlIbrahimz** [comment]
I tried doing so but it keeps saying access denied
![image](https://user-images.githubusercontent.com/95413094/153485678-8af21abc-0d2e-4017-880a-e59b9ade59e1.png)
