### ISSUE TITLE
Files doesn't follow disabled drive via group policy

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#8279]
### Description

I have my C: drive disabled on a user account. File exploer will show an error that it been restriced but files will allow navigation and file accses.

### Expected behavior

Should show an access denied error

### Files Version

2.1.13.0

### Windows Version

10.0.19043.1503

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8042424/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8042426/debug.log)

**Comment by gave92** [comment]
So much for windows security lol

**Comment by yaichenbaum** [comment]
@Josh-65 we don't plan to add artificial limitations for accessing the file system, the only time we will prevent access is if Windows returns an unauthorized exception. Can you open an issue on the Feedback Hub regarding the group policy?

**Comment by Josh-65** [comment]
My feedback hub doesnt work. Could you add it? please.

**Comment by Josh-65** [comment]
Also since Microsoft not really good at accepting feedback most of the time, I feel an exception should be made in this case. if it doesnt get resolved by them.

**Comment by gave92** [comment]
Josh what happens if you try to navigate to that drive using cmd?
Could you try changing drive's security properties instead?

**Comment by Josh-65** [comment]
I have tried that before an ended up destroying my windows install. Blocking it with security permistion stops the account logging in and other issues with programs. That what the group policy is designed for i belive to block users from opening it so they carnt mess with the files but allow the system to log in, open programs from it using shortcuts and other things.
