### ISSUE TITLE
Favorites are not being remembered after log off

### ISSUE THREAD

**Issue by sdragoo** [files-community/Files#8280]
### Description

When I add a 'Favorite' it is not remembered after a log off or restart.

Files Version: 2.1.5.0

System Info:
Windows 10 Enterprise
Version 1909 (OS Build 18363.2039)
64-bit
Dell Latitude 7420
16 GB RAM

### Steps To Reproduce

1. Add a favorite by right clicking on a folder in the right-hand pane and selecting "Pin to Favorites"
2. Log off of computer (or restart)
3. Log on to computer
4. Open Files application
5. Added favorite is no longer present

### Expected behavior

If I add a Favorite, it should be remember after log off or restart / reboot of system.

### Files Version

2.1.5.0

### Windows Version

Windows 10 Enterprise Version 1909 (OS Build 18363.2039)

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8042600/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8042603/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
This issue should be resolved in the preview version. https://files.community/download/preview

**Comment by vg-sbdragoo** [comment]
Confirmed to be working as expected now. Thank you very much for resolving this item.

**Comment by vg-sbdragoo** [comment]
That is great news Yair. I was just thinking about this yesterday while re-entering my most used ‘favorite’ after a reboot….

I’ll test and let you know.

Peace,

SCOTT B DRAGOO
Enterprise Information Architect
Pronouns: he/him
Platinum Vitality Status®

Mobile: 779.875.0945

Vitality Group
Website<http://www.vitalitygroup.com/> ǀ LinkedIn<https://www.linkedin.com/company/the-vitality-group-inc-/> ǀ Twitter<http://www.twitter.com/powerofvitality> ǀ Facebook<https://www.facebook.com/powerofvitality> ǀ YouTube<https://www.youtube.com/user/MyPowerofVitality> ǀ Instagram<https://instagram.com/powerofvitality/>

The most exciting phrase to hear in science, the one that heralds the most new discoveries, is not “Eureka!” but, “That’s funny…” - Isaac Asimov
