### ISSUE TITLE
Selecting files with first letter capitalization issue

### ISSUE THREAD

**Issue by BusteanHAN** [files-community/Files#8285]
### Description

I don't know the technical term for the procedure; that's why the title is maybe scuffed;

Attempting to select files starting with "o" by pressing the o key on the keyboard skips **_files_** that start with capitalized O. Folders seem to work regardless of capitalization. (See Gif)
![issue](https://user-images.githubusercontent.com/60746455/153480845-94216d02-dc2f-4c5d-8d61-bd69a823cc3f.gif)

### Steps To Reproduce

1. Go to some folder that contains folders and files
2. Use a key on the keyboard to iterate through files & folders
3. Files with capitalized first letters are skipped while iterating

### Expected behavior

Iterate through all files starting with that letter, no matter the capitalization

### Files Version

Version: 2.1.7.0 OS Version: 10.0.19044.1503

### Windows Version

Windows 10 Pro 21H2 19044.1503

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8043719/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8043720/debug.log)

**Comment by d2dyno1** [comment]
Closed with #8324
