### ISSUE TITLE
API support to use Files as a front-end for custom file systems/formats

### ISSUE THREAD

**Issue by DorCoMaNdO** [files-community/Files#8286]
### What's the Problem?

Many games nowadays implement their own file systems, formats, compression and encryption, and while deciphering many of the custom implementations might be simple in code, presenting it to users in a user-friendly manner can often be awfully complex and time consuming. A popular modern example done right would be OpenIV, made for Rockstar's RAGE engine games, supporting most typical Windows Explorer actions (simple copy/paste, drag&drop, familiar interface for file browsing), but it's closed source.

### Solution/Idea

Files could offer a familiar front-end interface to users while the specifics of implementing support for different file systems, formats, compression and decompression could be handled by others.
If Files would support different "content providers" via APIs, most of the hard work involved in creating presentable and usable user interfaces would be spared as it's been already done. It could vastly improve support for somewhat-niche audiences and workaround the half-measures such as barely comprehensible command line interfaces, basic WinForms interfaces, or the tactical-nuke approach of "extract everything, make your changes, repackage".

### Alternatives

Creating my own file browser for a game's custom archives format, however I've not been satisfied with it and never released it as a result, it's lacking many basic file browser features that require a lot of time and work to do right, many that other tools such as the previously mentioned OpenIV have implemented, along with many more nice-to-haves.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| APIs to allow third-party software to create "content providers", supplementing file structures, methods of opening, etc | Must |
| Support most basic operations (copy/paste, drag&drop, etc) | Should |

### Comments

I'm glad I stumbled across Files and the fact that it uses C# makes me think it would be much more accessible for anyone who might similarly be in my (admittedly niche) position if this request were to ever be implemented.
I'm aware it's quite out of scope for the current behavior of Files but I wanted to make this request so it could be up for consideration.

**Comment by Josh-65** [comment]
Games do this so users cant tamper with/copy it. prrety sure files wont be able to accses this at all if there custom made by game developers.

**Comment by DorCoMaNdO** [comment]
Games that openly support modding such as The Witcher 3, Cyberpunk 2077 and many others still use custom archives/formats, it's often just by the design of the engine, there are many games on the Unreal Engine and Unity that support modding but those engines have their baked archives, etc.
I never said that Files should be explicitly a mod manager, it should be a file explorer as it is now, but if we can provide it with info about custom formats or at least simulate entries via Files and handle file operations (read/write/execute, etc) in our code then it would act like an archive browser, just like Windows Explorer can browse zip archives by default.

**Comment by yaichenbaum** [comment]
> Games that openly support modding such as The Witcher 3, Cyberpunk 2077 and many others still use custom archives/formats, it's often just by the design of the engine, there are many games on the Unreal Engine and Unity that support modding but those engines have their baked archives, etc. I never said that Files should be explicitly a mod manager, it should be a file explorer as it is now, but if we can provide it with info about custom formats or at least simulate entries via Files and handle file operations (read/write/execute, etc) in our code then it would act like an archive browser, just like Windows Explorer can browse zip archives by default.

Are the formats supported by 7zip?

**Comment by DorCoMaNdO** [comment]
> > Games that openly support modding such as The Witcher 3, Cyberpunk 2077 and many others still use custom archives/formats, it's often just by the design of the engine, there are many games on the Unreal Engine and Unity that support modding but those engines have their baked archives, etc. I never said that Files should be explicitly a mod manager, it should be a file explorer as it is now, but if we can provide it with info about custom formats or at least simulate entries via Files and handle file operations (read/write/execute, etc) in our code then it would act like an archive browser, just like Windows Explorer can browse zip archives by default.
> 
> Are the formats supported by 7zip?

Nope, most are typically proprietary or with different encryption keys (UE4 games for example, sometimes the keys also change, I think Dragon Ball FighterZ had it's key changed for example).

**Comment by yaichenbaum** [comment]
@DorCoMaNdO supporting the different formats and updating them each time they change is a bit out of scope for Files. It might make more sense to fork Files and create a dedicated application for this purpose.

**Comment by yaichenbaum** [comment]
@DorCoMaNdO we recommend for the applications in question to use the built-in file system in Windows.
