### ISSUE TITLE
Network Explorer can't access to other computers & random restarts con Network Hardrive

### ISSUE THREAD

**Issue by diegosaga13** [files-community/Files#8287]
### Description

Basically the title

### Steps To Reproduce

asd

### Expected behavior

asd

### Files Version

Latest Version 

### Windows Version

Windows 11 Latest version (stable release)

### Relevant Assets/Logs

asd

**Comment by megamorf** [comment]
Sorry, but this issue is useless and does not meet any basic bug report requirements.
