### ISSUE TITLE
Interface options and features

### ISSUE THREAD

**Issue by LukeSkyMo** [files-community/Files#8290]
### Solution/Idea

Clover (http://en.ejie.me/) was my best default file explorer in Win 10 with incredible and so simple and fluid functionalities and nice interface. It still works fine in Win 11 but unfortunately, the new icon/action bar in Win 11 file explorer is not well displayed in Clover. This said, I'd like to control line spacing (compact display parameter in Win 11 File Explorer) and font to use, and have the Quick Access pinned folders either based on those selected in Win 11 File Explorer or importable (from registry ?). Thx and cheers to everyone working on Files v2 :-)

### Alternatives

Clover (http://en.ejie.me/) 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version : 2.1.13.0 OS Version: 10.0.22000.469

### Windows Version

Version : 2.1.13.0 OS Version: 10.0.22000.469 (Win 11)

**Comment by Josh-65** [comment]
You can add content to favorites it acts the same as quick access. Compact layouts are beeing done with #1940
