### ISSUE TITLE
Laggy animations only when window is focused

### ISSUE THREAD

**Issue by cultab** [files-community/Files#8291]
### Description

Animations are laggy. 
It only happens when the window is _focused_.
When it is _unfocused_ they are smooth.
I think it's the same thing reported in #6548.

### Steps To Reproduce

1. Open Files 2.0
2. Open Explorer
3. Focus Explorer
4. Scroll in Files 2.0
5. Focus Files 2.0
6. Scroll in Files 2.0

You should see a diference between steps 4 and 6.

### Expected behavior

Animations are fluid regardless if the window is focused or not.

### Files Version

Version: 2.1.13.0 OS Version: 10.0.22000.434

### Windows Version

Windows 11 Pro Version	21H2 OS build 22000.434 Experience Windows Feature Experience Pack 1000.22000.434.0

### Relevant Assets/Logs

https://user-images.githubusercontent.com/51170833/153528585-5c7f721d-f76e-4aa5-830d-839507e230bb.mp4

**Comment by yaichenbaum** [comment]
@cultab is this still an issue if you use the default theme?

**Comment by cultab** [comment]
yes

**Comment by yaichenbaum** [comment]
@cultab this seems to be a result of the transparent background that's shown when the window is focused, can you report this issue on the WinUI repository?

**Comment by cultab** [comment]
Ok, I will report it to https://github.com/microsoft/microsoft-ui-xaml.
