### ISSUE TITLE
Single click hover select

### ISSUE THREAD

**Issue by RichSiciliano** [files-community/Files#8292]
### Solution/Idea

When using single click to open files and folders, I have to ctrl click to select in order to perform actions (e.g. cut, copy, rename). If hover over would select, it can be done with just the mouse.

### Alternatives

An option to enable check boxes.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
Thank you for your feedback, merging with #3682
