### ISSUE TITLE
Emptying recycle bin from Files doesn't update the icon

### ISSUE THREAD

**Issue by PRMyx** [files-community/Files#8294]
### Description

When emptying recycle bin from within the app, the bin icon on my desktop doesn't update to an empty bin icon.

### Steps To Reproduce

1. Click on Recycle bin in the app
2. Click on the option "Empty Recycle Bin"
3. Once it is empty in the app, the bin on the desktop won't update the icon

### Expected behavior

When I empty the recycle bin from the app, the bin icon on the desktop should automatically update.

### Files Version

2.1.13.0

### Windows Version

Windows 10 21H2

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8046021/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8046022/debug_fulltrust.log)

**Comment by gave92** [comment]
Merging with #1089
