### ISSUE TITLE
Holding down the right key cannot drag.

### ISSUE THREAD

**Issue by Minecraft-562** [files-community/Files#8296]
Windows system holds down the right button to drag the file to a certain area, and then release it. Some options, such as copy or cut, will be displayed, but Files App will not work. 

↓Here are some videos for your reference↓
If you can't view them, please download them. 
Files Apps:
https://user-images.githubusercontent.com/83543104/153548547-81d5a068-4afe-44cf-b6da-a3761b27e1f3.mp4
System Files Manager:
https://user-images.githubusercontent.com/83543104/153548543-9ee44203-2e96-41f0-8735-05e889e9532c.mp4

 I rely on these functions very much. I hope developers can repair them as soon as possible. Thanks.

**Comment by gave92** [comment]
#1396

**Comment by gave92** [comment]
To cut/copy you can keep Ctrl or Shift keys pressed while dragging.

**Comment by Minecraft-562** [comment]
> To cut/copy you can keep Ctrl or Shift keys pressed while dragging.

I got it. Thank you very much.
