### ISSUE TITLE
"Empty Recycle Bin" option overrides muscle memory from people transitioning from regular File Explorer

### ISSUE THREAD

**Issue by pritster5** [files-community/Files#8297]
### What's the Problem?

If you're coming from using the standard File Explorer for Windows, your muscle memory will be used to emptying the recycling bin by clicking the button for it in the top left corner. 

With this program, the option has been moved to the rightmost part of the options ribbon, in a weird location. 

I request that this be moved to the left of the "New" button so that it is much closer to the Standard Windows File Explorer experience. 

### Solution/Idea

![image](https://user-images.githubusercontent.com/7132319/153552325-f6e37617-e189-440b-a05e-883f4676b335.png)

### Alternatives

you could also swap the places of "New" and "Empty Bin" as that better resembles the old flow (Win 10)

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.1.7.0 

### Windows Version

OS Version: 10.0.22000.493

**Comment by Pamasich** [comment]
> If you're coming from using the standard File Explorer for Windows, your muscle memory will be used to emptying the recycling bin by clicking the button for it in the top left corner.

Windows 11 File Explorer has it on the right too, not the left.
