### ISSUE TITLE
save crashing

### ISSUE THREAD

**Issue by shetozz** [files-community/Files#8298]
### Description

The app crashes when I edit a PowerPoint file and try to save my edit for the first time. after I relaunch the app it works perfectly.

### Steps To Reproduce

open a PowerPoint .pptx on Microsoft Office version 18.2106.12410.0
make an edit and save the document

### Expected behavior

app crashing and quitting.
this bug is not consistent but it happened enough to make a lazy bussy person report it.

### Files Version

Version: 2.1.13.0 OS Version: 10.0.19044.1466

### Windows Version

windows 10pro 21H2 build 19044.1466 

### Relevant Assets/Logs

![Screenshot 2022-02-11 104059](https://user-images.githubusercontent.com/93838524/153561196-9313ad49-38b3-4e59-8cc7-c88bbf5cd4c1.png)

**Comment by gave92** [comment]
Thanks for the report. Could you upload the debug logs?

**Comment by shetozz** [comment]
sorry, I'm not a developer so I don't know how to get it.

**Comment by gave92** [comment]
You can get them from Files settings > About > Open log location

**Comment by shetozz** [comment]
[debug.log](https://github.com/files-community/Files/files/8103872/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8103874/debug_fulltrust.log)

**Comment by gave92** [comment]
Thanks, should be the same as #8429
