### ISSUE TITLE
option "ouvrir avec"

### ISSUE THREAD

**Issue by philippecaron** [files-community/Files#8300]
### Description

Version : 2.1.13.0
OS Version: 10.0.22000.493
la fonction ouvrir avzec ne fonctionne pas , ni sous win 11 ni sous win 10

### Expected behavior

fonction "ouvrir avec qui ne répond pas "

### Files Version

Version : 2.1.13.0  sous Win 11 ou Win 10 mis à jour

### Windows Version

windows 11 21H2 build 22000493 sous licence

### Relevant Assets/Logs

je n'ai aucun message d'erreur

**Comment by philippecaron** [comment]
je n'ai hélas aucune image ou vidéo à donner à part ça :
[image: image.png] je clique droit sur un fichier JPG et cette fenêtre
s'ouvre.
je clique sur "ouvrir avec" mais rien ne se passe aussi bien sur mon ordi
en Win 11 ou en Win 10.
Cette possibilité fonctionne bien sur l'explorateur de fichier de windows.
c'est dommage car autrement le programme FILES est très appréciable.
C'est pareil avec n'importe quel fichier DOC ou PDF etc....
merci de votre réaction rapide.





Le ven. 11 févr. 2022 à 11:10, cinqmilleans ***@***.***> a
écrit :

**Comment by Josh-65** [comment]
You will need to upload the logs files. You can get them in files settings > about > open log folder.

**Comment by philippecaron** [comment]
voici les debug files
merci .

**Comment by Josh-65** [comment]
You will have to use github site (https://github.com/files-community/Files/issues/8300) to upload them as github doesnt pickup on email attachments.

**Comment by philippecaron** [comment]
[debug.log](https://github.com/files-community/Files/files/8049457/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8049459/debug_fulltrust.log)
