### ISSUE TITLE
Lateral bar does not re-open menus

### ISSUE THREAD

**Issue by AlexDicy** [files-community/Files#8302]
### Description

Previously opened menus are not opened again when starting Files
![image](https://user-images.githubusercontent.com/11839341/153583637-3076edc9-d1db-4df0-b2b1-26062a226f4e.png)

Sometimes only some menus are opened.

### Steps To Reproduce

1. Open some lateral menu
2. Close the app
3. Open the app
4. Repeat 2 and 3 if needed

### Expected behavior

Menus should be fully open 
![image](https://user-images.githubusercontent.com/11839341/153583750-d580f78f-1148-4adf-bd5b-aa40a8d82364.png)

### Files Version

Versione 2.1.13.0 OS Version: 10.0.22000.493

### Windows Version

Windows 11 1000.22000.493.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8048204/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8048205/debug_fulltrust.log)

**Comment by gave92** [comment]
#4128
