### ISSUE TITLE
File Explorer opens when I upload/download files from browser

### ISSUE THREAD

**Issue by DeFaLT-dj** [files-community/Files#8303]
### Description

I set Files app as default in the settings but when I try to upload a file or choose "Save as" for a file, it opens File explorer instead Files (I am not totally sure if this is expected behavior from File explorer or a bug)

### Steps To Reproduce

1. Open any page that has download option or just right click on web page and choose "save as"

### Expected behavior

It should open Files app instead of File explorer

### Files Version

Version: 2.1.13.0 OS Version: 10.0.22543.1000

### Windows Version

Windows 11 21H2 22543.1000

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8048639/debug.log)

**Comment by yaichenbaum** [comment]
Thank you for your feedback. This is the expected behavior for now.
