### ISSUE TITLE
Remove Files Previews in Details, Tiles, Small and Column Layouts

### ISSUE THREAD

**Issue by hassaanmasood** [files-community/Files#8306]
### What's the Problem?

Showing file previews for images and video makes no sense in Details, Tiles, Small, and Column Layout view. The Previews are so small and are very much helping. 

### Solution/Idea

Just the icons would look much better as they are in the Windows File Explorer.  Disabling this feature within the code will add much performance to the Files App. The previews should be available for Medium and Large Layouts configuration.

### Alternatives

Not something on my mind.

### Priorities

This is a Should be implemented feature

### Files Version

2.1.13

### Windows Version

Windows 11

**Comment by yaichenbaum** [comment]
I personally find the preiews useful and it helps differentiate between images.
