### ISSUE TITLE
Sizing of columns

### ISSUE THREAD

**Issue by AzaelMew** [files-community/Files#8307]
### Description

When toggleing Preview Mode for files, the sizing set for the columns for "name" etc. reset back to their defaults
Same happens when changing between folders

### Expected behavior

Expected behavior would be them not resetting after i set them to be something

### Files Version

Version: 2.1.7.0 OS Version: 10.0.19044.1503

### Windows Version

Windows 10 21H2 (OS Build 19044.1503)

### Relevant Assets/Logs

https://ss.azael.codes/fMqxDw23xxUQ/direct
https://ss.azael.codes/F4k55Tg0zRy1/direct

**Comment by yaichenbaum** [comment]
Merging with #6448
