### ISSUE TITLE
Icons don't have any color?

### ISSUE THREAD

**Issue by Pamasich** [files-community/Files#8309]
I just installed Files (the latest version), but unlike what I see on the images on the website, the icons at the top of the file/folder view don't have any color to them. They're just white-black, which makes them hard to see with non-color themes.

This is what I saw on the website and thus expected:
![image](https://user-images.githubusercontent.com/18553452/153651915-796e7374-4005-4255-9db6-85d84d82bc35.png)

But this is how it looks for me:
![image](https://user-images.githubusercontent.com/18553452/153651965-14a2efad-e50a-4cf7-90f8-259d61333542.png)

Is this intended? It looks like themes can change the secondary color of icons in the context menu, but they stay white-black at the top of the file/folder view regardless of theme.

I'm on Win11, clean-ish Windows installation, use dark theme. If any of those matter.

**Comment by gave92** [comment]
The color depends on your system Accent color which you can change in windows settings.

**Comment by alphayama** [comment]
Is there a way that makes the app ignore the system accent color and use the default blue accent (like in explorer.exe)?

**Comment by gave92** [comment]
Nope, but feel free to open a feature request if you find it important.
