### ISSUE TITLE
Creative Cloud Files should show up under "Cloud Drives"

### ISSUE THREAD

**Issue by amitbapat** [files-community/Files#8311]
### What's the Problem?

Creative Cloud Files does not show up under "Cloud Drives".

### Solution/Idea

Similar to OneDrive, Creative Cloud Files (this is the default name for the folder) should also show up under Cloud Drives section.

### Alternatives

None

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?
