### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by Senninha1974** [files-community/Files#8312]
### What's the Problem?

How can I uninstall files version 2.1.13.0

### Solution/Idea

I need / want to uninstall the app

### Alternatives

Easy method to unistall the app

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.13.0

### Windows Version

Microsoft Windows [Versión 10.0.22000.493]

### Comments

Thanko you

**Comment by gave92** [comment]
As with all uwp apps you can uninstall them from Windows Settigs > Apps. Or right click on Files in start menu and choose Uninstall.
