### ISSUE TITLE
Feature: Use correct icon for work OneDrive accounts

### ISSUE THREAD

**Issue by JJarv04** [files-community/Files#8313]
### What's the Problem?

The icon for a work & school OneDrive Drive in the Cloud Drives section is a standard folder icon.

### Solution/Idea

Instead of the folder icon, the OneDrive Icon should be used -Ideally similar to the way the taskbar icons are represented ( white & blue cloud icons for Personal OneDrive, Work & School OneDrive, respectively.
![image](https://user-images.githubusercontent.com/69032029/153682177-78ff54dc-8ea4-4758-80f6-c17492a933ce.png)

### Alternatives

M$ File Explorer only represents them both as the Blue OneDrive Cloud icons, so I think that could be simpler solution as well.
![image](https://user-images.githubusercontent.com/69032029/153683006-e21115f8-f26c-4dbc-88ab-fe2d75892698.png)

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.1.13.0

### Windows Version

OS Version: 10.0.22000.493

**Comment by Conquesttintin** [comment]
YES! this would be really useful. White & blue cloud icons would make it look a lot better.

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
Thumbs up on this 👍

**Comment by Lukiluc29** [comment]
I'm not sure if this issue is on my end or yours, but I've been experiencing this problem for a while now, where the OneDrive icon doesn't appear.
![Capture d'écran 2023-08-21 174337](https://github.com/files-community/Files/assets/128183422/b6ee6c0b-0205-44fa-8507-cb66964f90fb)
![Capture d'écran 2023-08-21 174624](https://github.com/files-community/Files/assets/128183422/39b7c768-d426-4cfd-a292-ebe6b444c7b7)

**Comment by yaira2** [comment]
@JJarv04 thank you for your patience, this issue is resolved in `main` and will be included in the next release.
