### ISSUE TITLE
Files app crashed when I tried to drag to Favorites section

### ISSUE THREAD

**Issue by GUPTAVARUN1992** [files-community/Files#8314]
### Description

I was trying to Pin Music folder to Favorites. I couldn't find any option in toolbar or context menu, so I tried to do it drag and drop to favorites section. When I dragged the folder to Favorites, and left mouse, I got "File in use" error and app crashed.

### Steps To Reproduce

1. Drag folder to Favorites section 
2. Drop it over Favorites word on section.
3. App crashes

### Expected behavior

1. Better way or say discoverable way to pin folders to favorites. 
2. Pin folder to Favorites when I drop it over Favorites

### Files Version

2.1.13.0

### Windows Version

Windows 10 21H2 (Build 19044.1526)

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8052857/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8052858/debug_fulltrust.log)

**Comment by gave92** [comment]
There's a "Pin to favorites" option in the context menu.

**Comment by GUPTAVARUN1992** [comment]
Hi,
There is no "Pin to favourites" option in Home page. I was looking there, got the option after navigating to specific folder.

Varun

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by yaichenbaum** [comment]
@GUPTAVARUN1992 is this still an issue in the preview version? https://files.community/download/preview

**Comment by GUPTAVARUN1992** [comment]
Hi team,
The issue is resolved now. Thank you so much.

Thanks & Regards,
Varun Gupta
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
