### ISSUE TITLE
Files Conflict: Replace Exisiting Button for all Conflicts

### ISSUE THREAD

**Issue by itayotten** [files-community/Files#8318]
### What's the Problem?

When copying some files with the same name to another folder the conflict windows suggests two options:
- Generate new name
- Replace exisiting file
You have to decide manually for each file whether to replace or generate a new name.

### Solution/Idea

I wish to have an option for choosing once for all confilcts.

### Alternatives

Just deciding manually for each file.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by gave92** [comment]
A better UI is in the works, but for now you can:
- select the option for one then right click and select "apply to all"
- or press "Ctrl+A" before selecting an option
