### ISSUE TITLE
Zip Files

### ISSUE THREAD

**Issue by Alistelian** [files-community/Files#8319]
### What's the Problem?

I'm sorry if there's already a way to zip files, but I can't seem to find it in the app context menu. If there isn't, it's the only thing I need to permanently switch to files because in every other way is better than the default file explorer.

### Solution/Idea

Add the feature to zip pulling it from windows and adding it to files in the context menu.

### Alternatives

 If directly pulling the feature from windows is not possible maybe you could add an open source third party program like you are doing with quicklook.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | 

- [x] Should

 |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Versión: 2.1.13.0 OS Version: 10.0.19042.1526

### Windows Version

Edición	Windows 10 Home Versión	20H2 Se instaló el	‎7/‎2/‎2022 Compilación del SO	19042.1526 Experiencia	Windows Feature Experience Pack 120.2212.4170.0

**Comment by gave92** [comment]
Currently it's not obvious: you have to create a new (empty) zip file from the "new" menu and then add files/folders to it. Tracked in #45.
