### ISSUE TITLE
Files does not show previews for .clip files

### ISSUE THREAD

**Issue by seyone22** [files-community/Files#8320]
### Description

When opening a folder containing .clip files (image work files similar to .psd, which are used by clip studio paint), files shows a generic thumbnail for the file instead of the actual image itself.
![image](https://user-images.githubusercontent.com/61453289/153720920-355b335b-dc00-4e71-9607-05feb77798c8.png)

### Steps To Reproduce

1. Open any folder containing a .clip file

### Expected behavior

It should show a preview of the image file, instead of a generic thumbnail.

### Files Version

Version: 2.1.13.0 OS Version: 10.0.22000.469

### Windows Version

Windows 11 21H2 22000.469

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/61453289/153720985-7078a409-8864-4a9b-b298-5d8a0646f81e.png)

**Comment by yaichenbaum** [comment]
Merging with #2582
