### ISSUE TITLE
Naming Collision of the app.

### ISSUE THREAD

**Issue by saidbakr** [files-community/Files#8327]
### Description

The application name is clashed with other already available apps names, they probably in other ecosystems but the idea is the same. For example, Elementary OS has the same name app [Files](https://github.com/elementary/files) too.
I suggest to change the application's name to something new and unique. 

### Steps To Reproduce

The application name.

### Expected behavior

The application name should be unique.

### Files Version

All

### Windows Version

Windows

### Relevant Assets/Logs

N/A

**Comment by yaichenbaum** [comment]
@saidbakr the name "Files" is an accurate representation of the app and despite being generic, it's one of the top search results. We're open to ideas if you have any suggestions but we don't currently have any plans to change the apps name.
