### ISSUE TITLE
Password Protected Sharing Credential Prompt

### ISSUE THREAD

**Issue by goaldfish** [files-community/Files#8328]
### What's the Problem?

Context:
This is my first time using github, so please excuse any mistakes I make in this request.
I use a windows 10 NAS server as a long-term storage and as a media server. I turned on "Password protected sharing" 'cus I share it with my friends.

Problem:
When I try to access the device with the Files app, it doesn't show anything- not even a prompt asking for my credentials. I had to use windows explorer to get the login screen. Once I logged in on windows explorer though, Files is able to see all the folders.
I also tried using "Connect with Remote Desktop Connection" to login but it doesn't give access to the folders.

Just a minor issue that prevents me from turning on the "Default file manager" option.

### Solution/Idea

Add support for password protected network locations.

### Alternatives

I haven't explored any alternatives.

### Priorities

| Ask for credentials when clicking a network device that has password protected sharing | Must |
| - | Should |
| Have an option to require entering credentials again after exiting the app or a set time to expire | Could |
| Saving credentials even after restart | Won't |

### Files Version

Version 2.1.13.0

### Windows Version

Windows 10 Pro 21H2  19044.1526

**Comment by gave92** [comment]
Merging with #7205
