### ISSUE TITLE
Add options to open Files in a new instance (Window) instead of tabs

### ISSUE THREAD

**Issue by miguelisidoro** [files-community/Files#8330]
### What's the Problem?

Hello,

Please add options to open Files in a new instance (new window) instead of tabs when using Windows+E.
From the tests I made, if I click Files from Windows Search or from the taskbar (I have Files in the taskbar), a new instance (window) is opened already. So:

1 - Add the option in Files
2 - Change the behavior of Windows+E to open new Files instances

Thanks

### Solution/Idea

Hello,

Please add options to open Files in a new instance (new window) instead of tabs when using Windows+E.
From the tests I made, if I click Files from Windows Search or from the taskbar (I have Files in the taskbar), a new instance (window) is opened already. So:

1 - Add the option in Files
2 - Change the behavior of Windows+E to open new Files instances

Thanks

### Alternatives

N/A

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.13.0

### Windows Version

Windows 11 21H2

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
@miguelisidoro can you share more context about your use case for this?

**Comment by yaira2** [comment]
I'm not sure if this was a deliberate change but this appears to be the current behavior for `win` + `e`.
