### ISSUE TITLE
Focus on new items after pasting

### ISSUE THREAD

**Issue by miguelisidoro** [files-community/Files#8333]
### Description

Hi,

In Windows Explorer from Windows 10 or 11, whenever I copy files or folders, the focus is to the copied files or folders.
In Files 2.0, this doesn't happen.

Thanks

### Steps To Reproduce

Copy files or folders from one folder to another.

### Expected behavior

After copying, the focus on the destination folder should be on the copied files or folders.

### Files Version

2.1.13.0

### Windows Version

Windows 11 21H2

### Relevant Assets/Logs

N/A

**Comment by yaichenbaum** [comment]
This issue should be resolved with #9299
