### ISSUE TITLE
Files - When in a folder, I start typing a word, the focus does not go to files or folders started by that folder

### ISSUE THREAD

**Issue by miguelisidoro** [files-community/Files#8334]
### Description

Files - When in a folder, I start typing a word, the focus does not go to files or foldes started by that folder

### Expected behavior

1. Open Files
2. Go to any folder
3. Start typing the name of one of the folders

### Files Version

2.1.13.0

### Windows Version

Windows 11 21H2

### Relevant Assets/Logs

N/A

**Comment by Josh-65** [comment]
Are they using capital letters

**Comment by miguelisidoro** [comment]
It seems to be working now, not sure what was causing the previous behavior.
