### ISSUE TITLE
Copy and paste doesn't show progress

### ISSUE THREAD

**Issue by miguelisidoro** [files-community/Files#8337]
### Description

Hello,

When copying and pasting folders, no progress indication is shown.
Also, sometimes copy takes a long time, making us copying the same files or folders again, resulting in duplicate data in the destination folder.

Thanks

### Steps To Reproduce

1. Go to any folder
2. Copy and paste a lot of folders to any other folder

### Expected behavior

To show a progress indicator and for the copy files to be fast.

### Files Version

2.1.13.0

### Windows Version

Windows 11 21H"

### Relevant Assets/Logs

N/A

**Comment by gave92** [comment]
Hi, progress should be shown in the top-right, near the settings button. Could you post a screenshot of Files during a copy?

**Comment by miguelisidoro** [comment]
Ok, didn't check the top-right, I am used to have a window with the progress. Thanks for the clarification.

**Comment by gave92** [comment]
Thanks for clarifying, closing this as improvement to progress indication is already tacked.
