### ISSUE TITLE
Preview support

### ISSUE THREAD

**Issue by ChrisJMair** [files-community/Files#8339]
### What's the Problem?

So I use a lot of 3D files in cinema 4D and in the native file explorer for windows 10 I am able to see a preview of what's in the file. On your app, it doesn't show the file but just the logo of the program. 

### Solution/Idea

Show the file preview of what's inside the files for Cinema 4D 
![image](https://user-images.githubusercontent.com/54102689/153770566-8d750779-1cd4-40f0-ba79-03aa9b6c3099.png)

### Alternatives

Going back to the standard explore in windows 10 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.1.13.0 OS Version: 10.0.19043.1466

### Windows Version

Device name	Chris-PC Processor	AMD Ryzen 9 5900X 12-Core Processor               3.70 GHz Installed RAM	64.0 GB Device ID	24260493-0BD9-4C5F-9D59-53A3B965DD66 Product ID	00330-81487-59735-AA227 System type	64-bit operating system, x64-based processor Pen and touch	No pen or touch input is available for this display

**Comment by yaichenbaum** [comment]
Merging with #2582
