### ISSUE TITLE
Add file transfer information (speed, time remaining, ecc...)

### ISSUE THREAD

**Issue by WereWolfix** [files-community/Files#8343]
### Solution/Idea

Would be cool to add a botton like "more details" in the "on going tasks" or something similar.

### Alternatives

An alternative could be a feature switch in the setting. So if you prefer have more detail you can turn on the feature "show more file transfer detail" for exemple.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.13

### Windows Version

Windows 11 Insider Preview 22543.1000 (rs_prerelease)

**Comment by yaichenbaum** [comment]
Merging with #4811
