### ISSUE TITLE
File crashes when I open the control panel

### ISSUE THREAD

**Issue by WereWolfix** [files-community/Files#8344]
### Description

When i open a Files window and than control pannel, Files crash.

### Steps To Reproduce

1. Open a Files window
2. Open control pannel 
4. Files crash

### Expected behavior

Files should not close after opening contol pannel 

### Files Version

2.1.13

### Windows Version

Windows 11 Insider Preview 22543.1000 (rs_prerelease)

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8057078/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8057079/debug_fulltrust.log)

https://user-images.githubusercontent.com/45063794/153783057-34b0ac6e-4227-43ab-a47a-1db4eb244b3e.mp4

**Comment by yaichenbaum** [comment]
This issue should be resolved with https://github.com/files-community/Files/pull/8684
