### ISSUE TITLE
Dragging a tab out of the Files window (with only 2 tabs open), Files close the other tab

### ISSUE THREAD

**Issue by WereWolfix** [files-community/Files#8345]
### Description

When I have 2 tabs open, and I try to drag one out the Files window (to split the window in 2 window, this is what I expect) Files close the other tab and reopen the one you dragged out

### Steps To Reproduce

1. Open 2 Files tab in the same window
2. drag one tab out of the window
3. Files close the other tab and load the one you dragged

### Expected behavior

I expect to split the window in 2 window instead  of having 2 tab in the same window

### Files Version

2.1.13

### Windows Version

Windows 11 Insider Preview 22543.1000 (rs_prerelease)

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8057097/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8057098/debug_fulltrust.log)

https://user-images.githubusercontent.com/45063794/153783657-e6ae29ab-3157-4c4c-a8e4-c7f91d9e4967.mp4

**Comment by yaichenbaum** [comment]
Merging with #8334 7838
