### ISSUE TITLE
select files with checkboxes

### ISSUE THREAD

**Issue by arlandi1974** [files-community/Files#8346]
### What's the Problem?

Since you already have the ability to open/launch file by single click, its now difficult or even nearly impossible to select file(s) with a left click.

### Solution/Idea

Please add checkbox in the left side of the file to select it, when user turn on single click to launch/open.
Explorer already has this.

### Alternatives

none comes to mind at the moment.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Add checkboxes to select one or more files | Should |

### Files Version

Version: 2.1.13.0 OS Version: 10.0.22000.526

### Windows Version

Microsoft Windows [Version 10.0.22000.526]

**Comment by yaichenbaum** [comment]
@arlandi1974 you can toggle the multi select feature from the toolbar.
![image](https://user-images.githubusercontent.com/39923744/153794571-febf6dd4-1e63-46d4-a39b-a4973e173ea7.png)

**Comment by arlandi1974** [comment]
thank you

**Comment by arlandi1974** [comment]
After I tried enabling Multiselect, it automatically disable single click to open.
In Explorer you can enable both 'multiselect' and 'single click to open'

**Comment by yaichenbaum** [comment]
@arlandi1974 we're tracking that in a separate issue 👍
