### ISSUE TITLE
Add option to hide Files and Folder pop-up information.

### ISSUE THREAD

**Issue by KumarjitDey** [files-community/Files#8348]
### What's the Problem?

This annoying pop-up which shows "Name: So-and-So. Type: Folder" is, I feel, pretty much a 90s thing. It takes a point away from the "modern" UI which Files takes pride in.

![Screenshot 2022-02-14 085416](https://user-images.githubusercontent.com/99241036/153795174-946dd08b-c3b4-4e28-ac36-1ee0ab9e5104.png)

### Solution/Idea

However, some people may find the pop-up information helpful. So under Files and Folders in Settings, you could implement an option to hide/show this pop-up.

![1111](https://user-images.githubusercontent.com/99241036/153805401-08f5a44e-9d64-4320-a7e1-cfde924094c4.png)

### Alternatives

n./a

### Priorities

n/a

### Files Version

2.1.13.0

### Windows Version

Windows 11 Home  21H2 22000.438

### Comments

**Comment by yaichenbaum** [comment]
@KumarjitDey can you clarify which option you're looking for and update the description and title accordingly?

**Comment by KumarjitDey** [comment]
> @KumarjitDey can you clarify which option you're looking for and update the description and title accordingly?

Sorry for creating a confusing post. English is not my native language. I have edited the post. Hopeful it is comprehensible.

**Comment by KumarjitDey** [comment]
> @KumarjitDey can you clarify which option you're looking for and update the description and title accordingly?


Option to hide this obvious thing, which hides Avril's face (lol): 

![1111](https://user-images.githubusercontent.com/99241036/153805259-87fd07e1-22c6-440c-bc56-461fabb8f0dc.png)

**Comment by yaichenbaum** [comment]
@KumarjitDey the tooltip is only shown when hovering over the thumbnail, can you just move the mouse away from the item?

**Comment by KumarjitDey** [comment]
> @KumarjitDey the tooltip is only shown when hovering over the thumbnail, can you just move the mouse away from the item?

I just found out that I can move my mouse around, yes. But, in the future if you devs have the time and no other priorities, building an option to turn it off would be truly awesome.

**Comment by Conquesttintin** [comment]
I agree this would be a werry useful option.

**Comment by yaichenbaum** [comment]
Thank you for your feedback, we don't have plans to include an option for this right now.
