### ISSUE TITLE
After pressing a character on the keyboard, highlight first item with that character

### ISSUE THREAD

**Issue by roybosch** [files-community/Files#8349]
### What's the Problem?

After pressing a character on the keyboard, no file is highlighted.

### Solution/Idea

After pressing a character on the keyboard, I'd like the first item with that character to be highlighted. 

This is a function I'm using often in Windows Explorer. Especially when there's a long list of files with different file names, it's very convenient to be able to scroll to the first file matching that first character.

### Alternatives

I don't see any other way to accomplish this right now.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Highlight the first item with a first character matching the pressed key on the keyboard  | Must |
| None | Should |
| After pressing the same key again, scroll through the files as long as they have the same first character  | Could |
| None | Won't |

### Files Version

2.1.13.0

### Windows Version

Windows 11

**Comment by yaichenbaum** [comment]
@roybosch this is already supported, can you see if this works for you in the preview version? https://files.community/download/preview
