### ISSUE TITLE
Compress file/folder list view vertically

### ISSUE THREAD

**Issue by ChrisMooreGB** [files-community/Files#8350]
### What's the Problem?

Apologies if this is already there but I missed it when searching through!

The vertical spacing of files & folders is very wide, meaning a given height of screen displays far fewer items than Windows File Explorer. On my monitors Files displays almost exactly half the number of files/folders per unit display height than File Explorer, and to no benefit in my view. The result is valuable screen estate being wasted.

### Solution/Idea

Provide an option for a 'Compressed' display to take out the vertical white space between files and give a display apaced like File Explorer. Microsoft do this in Outlook (on Windows at least) under View / Layout there's an option 'Use Tighter Spacing' for those who wish to increase the vertical message density shown in the list view. 

I'd suggest a similar 'Use Tighter Spacing' option perhaps under Preferences / Files and Folders.

### Alternatives

None - the idea is simply to have the option of a more space-efficient, tighter-spaced file/folder list display.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to view and work with files more efficiently because they can see more on screen within a given space. My view is that it's a 'Must' to have this option before Files will be really useful to me.

### Files Version

Version: 2.1.13.0 OS Version: 10.0.22000.493

### Windows Version

Windows 11 Pro 21H2 22000.493

**Comment by yaichenbaum** [comment]
Merging with #1940
