### ISSUE TITLE
program crashing 

### ISSUE THREAD

**Issue by OMAR-3OOV** [files-community/Files#8351]
### Description

when i open the desktop folder the program crash for no reason.

### Steps To Reproduce

1. Desktop folder

### Expected behavior

i don't have any idea why it's crashing

### Files Version

last one

### Windows Version

windows 10 

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/50619134/153833165-621f85ae-a6fb-458a-a601-ae599a8817c1.png)

**Comment by yaichenbaum** [comment]
@OMAR-3OOV what version of Files are you using?
