### ISSUE TITLE
Please make quicklook feature /include the quicklook app in files

### ISSUE THREAD

**Issue by Cloudwires** [files-community/Files#8353]
### What's the Problem?

Hi,
I'm very happy with the new files v2 app for Windows 11.
The only feature I am missing is a quick look feature.
macOS users are familiar with this handy function: you just press the space bar inside the finder app and instantly see a preview i.e. of an image file.

Now, for Windows explorer there is already a quick look app, developed by Paddy Xu. Unfortunately, this app does not work inside the files app.

### Solution/Idea

The most obvious solution would be to get in touch with the developer of quicklook for windows to include this app inside the files app for windows.

### Alternatives

If that's not possible, another solution would be to create an independent quick look feature for the files app.

### Priorities

| Capability | Priority |
| This proposal will allow developers to accomplish Y | Could |

### Files Version

2.1.13.0

### Windows Version

Windows 11

**Comment by yaichenbaum** [comment]
@Cloudwires QuickLook is already supported in Files, can you open a new issue as a bug report and include the log files so we can look into this?
