### ISSUE TITLE
Unable to create a new file/folder inside a 'hidden' folder

### ISSUE THREAD

**Issue by Roockie36** [files-community/Files#8355]
### Description

When trying to create a new file/folder(using the "New" button or the context menu) while inside a hidden folder, nothing happens after pressing "Set Name". 

### Steps To Reproduce

1. Create or just take any folder.
2. Click on the Properties button, and set it to "Hidden" under "Attributes".
3. Open the folder and try creating a new file/folder.

### Expected behavior

A new file/folder should appear inside the hidden folder.

### Files Version

Version: 2.1.2.0 OS Version: 10.0.22000.493

### Windows Version

Windows 11 21H2 22000.493

### Relevant Assets/Logs

![folder is hidden](https://user-images.githubusercontent.com/91465659/153877417-74b6cb2b-7b21-47ed-b3df-7074439b3727.png)
This folder is hidden

![creating new folder](https://user-images.githubusercontent.com/91465659/153877492-a88de87a-3bb8-412b-9385-2a33a5f4f714.png)
I set a name and hit "Set Name" to create a new folder inside it

![doesn't work](https://user-images.githubusercontent.com/91465659/153877576-5e816cea-23d2-4ff9-aecb-673661c2f00d.png)
But the folder remains empty

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
