### ISSUE TITLE
Stuck File from Archive Option While Application is Open

### ISSUE THREAD

**Issue by Cody-Soultz** [files-community/Files#8356]
### Description

When selecting "add to archive..." using the 7-zip tab inside the right-click menu when selecting multiple files to compress,  a file is created with the name you selected but that file gets stuck. As in the 7-zip operation fails because it creates a file with the extension .zip.tmp that is supposed to be moved to the .zip file, but an error message from 7-zip says in cannot create a file when that file already exists referring to the .zip file being there. 

This would not be a huge issue except for the fact that the .zip file created that is 0 bytes long will not delete from the files delete prompt. Even if you use the normal files explorer, files just creates the .zip file again until files is off of the directory. Even when closing the application and returning to the directory the file comes back.

This can only be solved from what I can tell by leaving the directory using another tool to delete the file then files does not seem to make the file sticky. Or it appears cmd will delete the file without it coming back

I do not know if it is relevant, but files is my default program for the file explorer.

### Steps To Reproduce

Select some files
right click and select the 7-zip menu (if no option for 7-zip then install 7-zip and add it to the context menu)
give the archive a name
hit OK
![image](https://user-images.githubusercontent.com/15863142/153886383-7bba3d2e-3693-4608-b786-a282afdfbfe0.png)
Now there is a .zip and a .zip.tmp file in the directory the .zip file cannot be removed while files is in that directory

### Expected behavior

FIles would not hold onto the .zip file and recreate the file when deleted.

### Files Version

2.1.13.0 but this is not the first version that has this bug

### Windows Version

Edition: Windows 10 Enterprise Version
Version: 21H1
OS build: 19043.1466
Experience: Windows Feature Experience Pack 120.2212.3920.0

### Relevant Assets/Logs

I greped the files for the name of the .zip I was creating and nothing was returned, so I have no relevant logs to post.

**Comment by Cody-Soultz** [comment]
Even when deleting with cmd it sometimes comes back. This is a weird issue that has been one of the things holding me back from adopting this program full time. This is just the first time it made me inconvenienced enough to not ignore it and to create an issue here

**Comment by yaichenbaum** [comment]
@Cody-Soultz is this an issue in File Explorer as well?

**Comment by Cody-Soultz** [comment]
I am sorry, apparently, it is. Does this now seem like a 7-zip issue? Or would you like to have me keep this issue open?

**Comment by Cody-Soultz** [comment]
OK, I have updated my 7zip to a newer version from 19.0 to 21.07 and the same issue persists, but there is no 7z process running so I do not know why the file stays around. Are you suggesting this may be a window's bug of some sort?

**Comment by yaichenbaum** [comment]
> I am sorry, apparently, it is. Does this now seem like a 7-zip issue? Or would you like to have me keep this issue open?

It appears to be an issue with 7zip, can you report the issue to them?
