### ISSUE TITLE
Black background around the folder's icon

### ISSUE THREAD

**Issue by dodyakako** [files-community/Files#8361]
### Description

![Screenshot 2022-02-15 031610](https://user-images.githubusercontent.com/54448026/153974359-99fd5378-7820-431a-9a73-27bcefa484ac.jpg)

### Steps To Reproduce

I don't know how to reproduce it, but I think it happens to the folder which has been modified recently: created new folders inside it, moved files to it, etc.

### Expected behavior

No black background around the icon.

### Files Version

Version: 2.1.13.0 

### Windows Version

OS Version: 10.0.22543.1000

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8065020/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8065022/debug_fulltrust.log)

**Comment by gave92** [comment]
Tracked in #6373
