### ISSUE TITLE
Allow third party theming.

### ISSUE THREAD

**Issue by seventhstorm** [files-community/Files#8362]
### What's the Problem?

The app is great. Just a few suggestions. I'm sure you`re aware of third-party theming. The likes of Niivu (one great artist). Is it possible to make the app themeable using these themes? The default file explorer supports that. Perhaps if not the entire app, maybe the minimize to the taskbar, resizing and close buttons, to support custom themes. the 

### Solution/Idea

Allow third-party custom themes.

### Alternatives

Allow theming for the control buttons.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.13.0

### Windows Version

Windows 11 22000.493

**Comment by yaichenbaum** [comment]
@seventhstorm thank you for your feedback, unfortunately UWP doesn't support theming systems the way the rest of shell does. You might be interested in the custom solution we built for Files https://files.community/docs/configuring/custom-themes.
