### ISSUE TITLE
Music, Pictures, and Videos folders not translated in the homepage

### ISSUE THREAD

**Issue by ACh-K** [files-community/Files#8363]
### Description

![image](https://user-images.githubusercontent.com/98224334/154008337-0d66cff2-a0fb-415c-bc61-c47656e8c157.png)

### Steps To Reproduce

It happens if the language is not English but any other language, which is Traditional Chinese in this case.

### Expected behavior

Music, Pictures, and Videos folders are translated into matching language in Home.

### Files Version

Version: 2.1.13.0

### Windows Version

OS Version: 10.0.22000.493

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8066685/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8066686/debug_fulltrust.log)

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.0.0?

**Comment by ACh-K** [comment]
No, it’s working now. Much appreciated!
