### ISSUE TITLE
Disabling "Set Files as default file manager" does not disable [win][e] from opening Files instead of explorer.exe

### ISSUE THREAD

**Issue by taroj1205** [files-community/Files#8364]
### Description

I've enabled "Set Files as default file manager" feature, I disabled it but it does not fix [win][e] from opening Files app instead of windows default explorer.
I've tried reinstalling Files after disabling the feature, did not fix the problem.

### Steps To Reproduce

1. Go to settings
2. Enable "Set Files as default file manager"
3. Disable "Set Files as default file manager"

### Expected behavior

After disabling it, it should turn [win][e] to open default explorer instead of Files.

### Files Version

Version: 2.1.13.0 OS Version: 10.0.22000.493

### Windows Version

Edition	Windows 11 Home Version	21H2 Installed on	‎7/‎10/‎2021 OS build	22000.493 Experience	Windows Feature Experience Pack 1000.22000.493.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8066784/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8066785/debug_fulltrust.log)

**Comment by gave92** [comment]
To fix this please take a look at #7626
