### ISSUE TITLE
Files crashes when opening Downloads

### ISSUE THREAD

**Issue by TheChilliPL** [files-community/Files#8367]
### Description

When I try to open Downloads in Files, it freezes, shows the notification below, and then closes the window.
![image](https://user-images.githubusercontent.com/18823939/154094636-fb008d06-2934-4d9e-9dc9-73988ece91d7.png)

### Expected behavior

Files should not crash and allow me to browse my Downloads

### Files Version

Version: 2.1.13.0 OS Version: 10.0.22543.1000

### Windows Version

Edition	Windows 11 Pro Insider Preview Version	Dev Installed on	‎2022-‎02-‎15 OS build	22543.1000 Experience	Windows Feature Experience Pack 1000.22543.1000.0

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8072421/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8072422/debug.log)

**Comment by gave92** [comment]
What if you turn off the option to show folder sizes?

**Comment by Josh-65** [comment]
Merging with #8413
