### ISSUE TITLE
ordered by & group by BUG

### ISSUE THREAD

**Issue by osgfxman** [files-community/Files#8368]
### Description

When I sort a folder by name, date, or group icons by anything IT SHOULD STICK just like explorer, but the behavior right now is so weird! I have to re-order/group-by the same folder again and again! this is very annoying! 

for example the download folder .. i need to sort it by DATE! i just want the newest item!
but in the source folder i need to sort by NAME

this is very important! every folder should KEEP its state!
   

### Steps To Reproduce

........

### Expected behavior

every folder should KEEP its state!

### Files Version

2.1.13.0

### Windows Version

11

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/23291429/154137478-179de73e-a502-4b52-9680-2965467e59ce.png)

**Comment by osgfxman** [comment]
Columns
and wait! There's another bug in the bug! :D
When you right click in an empty area to (group by) icons (in the column
view) it doesn't work at all!
you have to make it from the menu bar in the top left corner, which is not
a big deal if i'll do it once, but the problem i have to do this every
single time!

**Comment by gave92** [comment]
Thanks for confirming. Tracked in #6370.
