### ISSUE TITLE
Copy & paste not working between SMB shares

### ISSUE THREAD

**Issue by nedpyle** [files-community/Files#8369]
### Description

Cannot copy from an Explorer window to a Files window with certain SMB shares. Copying using Files to Files works, and copying from one of my servers works, but one other server does not to the same target. There is no error, the file simply doesn't copy. I can share paths offline, these are in MS corpnet domains/forests that you will have access to.  

### Steps To Reproduce

1. created a zipped file on a server SMB share
2. Using Explorer, copy that file
3. Using Files, paste that file onto another server's SMB share

Note that this does not reproduce for every share I use. I can demonstrate offline.

### Expected behavior

File copies.

### Files Version

Version: 2.1.13.0 OS Version: 10.0.22555.1000

### Windows Version

Version: 2.1.13.0 OS Version: 10.0.22555.1000

### Relevant Assets/Logs

Can send you logs offline, these contain MS internal server names and paths. nedpyle@microsoft.com

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?

**Comment by Josh-65** [comment]
If it is can you look for an error like "system.unauthrisedAccsesException" or "the task was cancelled".
