### ISSUE TITLE
`Ctrl + P` to open Previews Panel crashes Files?

### ISSUE THREAD

**Issue by lightningHoneypot** [files-community/Files#8371]
### Description

So, I just discovered a useful feature called preview pane, it is designed to get people to preview a file before opening it (although I think that an addition to a Quick Look feature would be much more useful than using a two button combo)

The shortcut is `Ctrl + P`, which is odd considering when I check on the regular File Explorer it is  `Alt + P`, and `Alt + P` does something different in Files (Community) by pasting a file? Why is it like that?

But that's beside the point, there are times where `Ctrl + P` crashes the program, and I couldn't figure it out why is it that it is crashing.

### Steps To Reproduce

1. Press Ctrl + P

### Expected behavior

I expect that the previews pane to open, but it crashes the program

P.S.
While messing around, I opened File Explorer (regular), to check if the `Alt + P` shortcut works, and it does. So, I decide to try again with Files, for some reason `Alt + P` works in Files, but the icing on the cake is that if I do `Ctrl + P`, it crashes the program **AND** somehow Files removes itself from the taskbar!

### Files Version

Version: 2.1.13.0 OS Version: 10.0.19043.1526

### Windows Version

Windows 10 21H1 19043.1526 (Is there an alternative shortcut key for 10 keyless laptop users?)

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8075109/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8075111/debug_fulltrust.log)

**Comment by tomhoad** [comment]
Seeing the same:

[debug.log](https://github.com/files-community/Files/files/8123189/debug.log)

**Comment by lightningHoneypot** [comment]
> Ctrl + P is the correct shortcut, alt + p works as well since it's set as the access key. ![image](https://user-images.githubusercontent.com/39923744/160006355-31487de3-db92-4d77-a5b7-17ff74f1487f.png)

It seems that this is not a bug, but a side feature, therefore I am closing this issue.

**Comment by lightningHoneypot** [comment]
> Ctrl + P is the correct shortcut, alt + p works as well since it's set as the access key. ![image](https://user-images.githubusercontent.com/39923744/160006355-31487de3-db92-4d77-a5b7-17ff74f1487f.png)
From here: https://github.com/files-community/Website/issues/187

It seems that this is not a bug, but a side feature.

But still as of now, there is no crashes when using `Ctrl + P` or `Alt + P`, this seems to be a rare occurring bug. I will keep in touch if there is any crashes involving using those keyboard shortcuts. As of now, there is no crashes.

**Comment by Josh-65** [comment]
Have you encounted this issue anymore?

**Comment by lightningHoneypot** [comment]
> Have you encounted this issue anymore?

I don't think so. I don't think that there is any issues anymore
