### ISSUE TITLE
Problems when cycling through tabs 

### ISSUE THREAD

**Issue by Maltbrew** [files-community/Files#8372]
### Description

When switching between tabs using Ctrl + Tab, while it does show the new tab (tab 2) for the first time,  Files is still in the previous tab (tab 1). 

If you happen to have more than 2 tabs only it also only works a single time before going back to tab 1. 

### Steps To Reproduce

Simply use Ctrl + Tab to cycle through tabs. 

### Expected behavior

That it should work like when cycling through tabs in a browser. 

### Files Version

2.1.13.0

### Windows Version

21H2 19044.1526

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8075517/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8075518/debug.log)

**Comment by jakubmatej** [comment]
Hi, I can confirm strange behavior of Ctrl + Tab keystroke.
### Description

1. Tab no.1 + [Ctrl + Tab] = switched to Tab no.2 ✔️
2. Tab no.2 + [Ctrl + Tab] = nothing happened, nor screen (folder content) changed ❌
3. Still Tab no.2 + [Ctrl + Tab] = screen changed to Tab no.1 ✔️ ; folder path inputbox still showing path from Tab no.2 ❌ ;  Back and Forward buttons affecting Tab no.2 ❌

### Files Version
Version: 2.1.13.0
### Windows Version
OS Version 10.0.19042.1466
Edition        Windows 10 Enterprise
Version       20H2
OS build     19042.1466
### Relevant Assets/Logs
[debug_fulltrust.log](https://github.com/files-community/Files/files/8096449/debug_fulltrust.log)

**Comment by IgorKordiukiewicz** [comment]
Idk why but after commenting out:
```
<KeyboardAccelerator Key="Tab" Modifiers="Control">
    <i:Interaction.Behaviors>
        <icore:EventTriggerBehavior EventName="Invoked">
            <icore:InvokeCommandAction Command="{x:Bind ViewModel.NavigateToNumberedTabKeyboardAcceleratorCommand}" />
        </icore:EventTriggerBehavior>
    </i:Interaction.Behaviors>
</KeyboardAccelerator>
```
Ctrl+Tab still changes tabs (although not by `MainPageViewModel.NavigateToNumberedTabKeyboardAccelerator()` as it should normally) , even though this is the only place that defines Ctrl+Tab action.

**Comment by yaira2** [comment]
Merging with #6111
