### ISSUE TITLE
Files Auto-Scrolling Upwards and Resets Theme Selection to the Top-Right

### ISSUE THREAD

**Issue by ThisNekoGuy** [files-community/Files#8373]
### Description

I noticed that a this issue also occasionally occurs for me in Windows's settings menu(s) where there's enough space to scroll; so, I think this might be related to `UWP`, considering that I don't have this issue with any other application(s), but I'm not sure.

### Steps To Reproduce

1. Open Files
2. Click on `settings`
3. Go to `Appearance`
4. Open `Custom Themes`
5. Select any theme
6. Watch Files override the selection with Burgundy
7. Attempt to scroll down in the themes menu
8. Have the scrollbar scroll back up without consent and highlight Burgundy after doing so

### Expected behavior

- Honor the user-selected `Theme` selection
- Don't scroll without user input

### Files Version

Version: 2.1.13.0 OS Version: 10.0.19042.1526

### Windows Version

Edition	Windows 10 Home Version	20H2 Installed on	‎12/‎7/‎2019 OS build	19042.1526 Experience	Windows Feature Experience Pack 120.2212.4170.0

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/28468662/154188583-02270617-bf9f-4963-880c-b9c641439128.png)

[debug.log](https://github.com/files-community/Files/files/8076389/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8076390/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
@ThisNekoGuy is this still an issue in the preview version? http://files.community/download/preview

**Comment by ThisNekoGuy** [comment]
@yair100 Sorry for being slow to respond, I had caught covid

I'm testing it right now and it doesn't seem to be happening but I'll let you know if I see it again

**Comment by yair100** [comment]
> @yair100 Sorry for being slow to respond, I had caught covid
> 
> I'm testing it right now and it doesn't seem to be happening but I'll let you know if I see it again

Thank you for the update, be well!
