### ISSUE TITLE
Disk C cannot be copied

### ISSUE THREAD

**Issue by lf5120556** [files-community/Files#8374]
### Description

C # publish project to c drive folder, copy invalid, delete invalid，This is the path C:/Users/taiyangmobile/Desktop/public/ServerDmckd

### Expected behavior

 not work

### Files Version

2.1.13.0

### Windows Version

windos

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/58462809/154193927-d5ab9d62-cbe1-47c3-b984-e1331f31fb76.png)

**Comment by Josh-65** [comment]
You will need to upload the logs files. You can get them in files settings > about > open log folder. Also what does it do if you try in the normal file explorer
