### ISSUE TITLE
App crash when opening ~20 tabs

### ISSUE THREAD

**Issue by kristiyanmv** [files-community/Files#8375]
### Description

App crashes after opening ~20 tabs /no matter the tab contents/. it crashes exactly when I try to open the 20th tab.

### Steps To Reproduce

Spam CTRL + T 20 times

### Expected behavior

On the 20th tab opening, the app freezes briefly and closes itself

### Files Version

Version: 2.1.13.0 OS Version: 10.0.22000.493

### Windows Version

Windows 11 22000.493

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8077214/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8077215/debug_fulltrust.log)

**Comment by QuaintMako** [comment]
@yair100 this is probably linked to #[2145](https://github.com/files-community/Files/issues/2145)
