### ISSUE TITLE
Thumbnails Not Showing

### ISSUE THREAD

**Issue by naamiil** [files-community/Files#8376]
### Description

I use Adobe reader and Microsoft Powerpoint and adobe`s and Powerpoint`s files not showing thumnails, how can i reapir this? Please help me guys ... 

### Steps To Reproduce

I use Adobe reader and Microsoft Powerpoint and adobe`s and Powerpoint`s files not showing thumnails, how can i reapir this? Please help me guys ... 
![1](https://user-images.githubusercontent.com/87846324/154217449-f2be6e95-fc8f-4d62-b144-c14df5348351.png)

### Expected behavior

![1](https://user-images.githubusercontent.com/87846324/154217500-a33a6eec-7898-409d-ad86-2790e0fdf545.png)

### Files Version

Version: 2.1.13.0 OS Version: 10.0.19044.1526

### Windows Version

Version 21H2 

### Relevant Assets/Logs

![1](https://user-images.githubusercontent.com/87846324/154217326-f97b4270-ea7b-412e-a028-d60ca84da017.png)

**Comment by yaichenbaum** [comment]
Merging with #2582
