### ISSUE TITLE
Downloads forlder

### ISSUE THREAD

**Issue by thegodcat13** [files-community/Files#8377]
### What's the Problem?

The downloads folder doesn't have the the downloads format with: today, yesterday, last week etc. 

The folder loads like a normal folder so for me it takes a while before I can see my most recent files.  Also the folders are on top so if you're searching a file you need to scroll down for a while.

### Solution/Idea

Maybe load the downloads from newest files to latest files and order the files and folders like the Windows downloads folder.

### Alternatives

format

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by Josh-65** [comment]
![image](https://user-images.githubusercontent.com/26977075/154288363-f7ccfdd4-7113-496f-a954-85d578fbad96.png)

**Comment by thegodcat13** [comment]
Thanks for the quick reply!

Yeah I have that enabled, but all the folders are on top and the files below that, instead of the folder and files sorted by date on top.

**Comment by Josh-65** [comment]
Settings > prefrances > files and folder > list and sort directors along with files. you can tuen that on

**Comment by thegodcat13** [comment]
Thanks

**Comment by thegodcat13** [comment]
is there a way to only apply this setting to the downloads folder instead of to all folders

**Comment by yaichenbaum** [comment]
> is there a way to only apply this setting to the downloads folder instead of to all folders

No

**Comment by Josh-65** [comment]
Dont think so you can make a feture request for it in a new issue
