### ISSUE TITLE
Hidden folders and shortcuts don't appear in network drive

### ISSUE THREAD

**Issue by Vinickw** [files-community/Files#8379]
### Description

I opened my folder located in a network drive, and I felt that something was missing, until I realize that hidden folders and shortcuts weren't there.
![Captura de tela 2022-02-16 094844](https://user-images.githubusercontent.com/89015723/154273528-8a2efe84-f8d1-43c2-89cd-032bf6cd77ac.png)
I double-checked my settings to see if I had something disabled, but no.
![Captura de tela 2022-02-16 094826](https://user-images.githubusercontent.com/89015723/154273607-c2258725-9833-4b22-8a78-d79808e5446d.png)
These files appear normally if it is on my PC, like my documents folder.

### Expected behavior

It should appear.

### Files Version

Version: 2.1.13.0 OS Version: 10.0.22000.526

### Windows Version

Windows 11 21H2 (22000.526)

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8080126/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8080129/debug_fulltrust.log)

**Comment by gave92** [comment]
Tracked in #2436
