### ISSUE TITLE
Spacebar to preview

### ISSUE THREAD

**Issue by jimmydeanhartog** [files-community/Files#8380]
### What's the Problem?

Really love the app. The only thing I'm missing is spacebar to preview files, or support for the QuickLook application (see: https://www.microsoft.com/en-us/p/quicklook/9nv4bs3l1h4s)

### Solution/Idea

Adding support for QuickLook or create a similar solution within the app itself.

### Alternatives

Switching back to the default file explorer

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

latest

### Windows Version

Windows 11 pro 21H2

**Comment by yaichenbaum** [comment]
@jimmydeanhartog QuickLook is already supported, can you try restarting Windows to see if that helps?

**Comment by jimmydeanhartog** [comment]
Hey @yair100, thanks for your quick reply. I've just restarted, and it doesn't seem to help. So this might be a bug or something. I've also tried to reinstall Quicklook and that didn't do anything. It is working in the default file explorer. Let me know if you have any other ideas or possible solutions! :)

**Comment by yaichenbaum** [comment]
@jimmydeanhartog can you upload the log files?

**Comment by bobarakatx** [comment]
Not working for me either. I'm not sure but it might have stopped working after upgrading to Windows 11. Works as expected on another Windows 10 PC.

**Comment by mreed4** [comment]
I created an [Issue in the QuickLook repo](https://github.com/QL-Win/QuickLook/issues/1112).
