### ISSUE TITLE
Keyboard arrow support when viewing files in column mode

### ISSUE THREAD

**Issue by jimmydeanhartog** [files-community/Files#8381]
### What's the Problem?

I would love to use my keyboard arrows to navigate true files when in column mode.

### Solution/Idea

Adding support for this feature :)

### Alternatives

using the mouse, but this sucks haha

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
@jimmydeanhartog you can already use the arrow keys, is there a specific shortcut you're looking for?

**Comment by jimmydeanhartog** [comment]
This was fixed with a reboot.. thanks!
