### ISSUE TITLE
Allow to assign custom name to favorites when two folders has a same name

### ISSUE THREAD

**Issue by MaxSteven** [files-community/Files#8383]
### What's the Problem?

In daily project we always have to use multiple drives since the data is really huge.
So I often pin the favorite folder but the problems is sometimes they have the same name.,

### Solution/Idea

In windows 7 M$ allows user to assign a custom name to favorites folder
Even though it's not available anymore from win 10 but that's a nice solutionthe 

### Alternatives

Alternatives may be showing folder name with a number next to it.
But not recommend

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Should |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.1.13.0

### Windows Version

 OS Version: 10.0.19044.1566

**Comment by yaichenbaum** [comment]
@MaxSteven thank you for your feedback, merging with #3422 to track this in one place.
