### ISSUE TITLE
Add option to size all columns to fit in the details layout

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#8384]

**Comment by GargDivanshu** [comment]
I'm Divanshu, fresher, and i wish to contribute to this good first issue, can any moderator pls help me on how to start?? Or from where and  how to learn the relevant skills

**Comment by yaichenbaum** [comment]
@GargDivanshu here is a good starting point, I recommend going over the documentation on UWP as it has a number of examples of the different apis https://docs.microsoft.com/en-us/windows/uwp/.

**Comment by destrex271** [comment]
I would like to work on this issue too.

**Comment by yaichenbaum** [comment]
> I would like to work on this issue too.

@destrex271 I assigned you the issue.

@GargDivanshu let me know if you'd like a different issue that might be a little easier to start with.

**Comment by destrex271** [comment]
> > I would like to work on this issue too.
> 
> @destrex271 I assigned you the issue.
> 
> @GargDivanshu let me know if you'd like a different issue that might be a little easier to start with.

@yair100 I by mistake clicked on the unassign button can u pls reassign the issue😅😅😅

**Comment by GargDivanshu** [comment]
@yair100 I went through the link regarding UWP, but it's a sincere request to assign some easier issue to start with. Also pls tell what prerequisite should I cover to contribute in better way.

**Comment by yaichenbaum** [comment]
@GargDivanshu do you want to try #8021? It requires finding a good icon to use and replacing the existing one that doesn't work.

**Comment by GargDivanshu** [comment]
@yair100 ya means for now i just have to find a relevant icon?? Pls do tell what relevant prerequisites i should know before starting

**Comment by destrex271** [comment]
@yair100  do we need this functionality to be as a menu bar option or is a keyboard shortcut enough?

**Comment by yair100** [comment]
> @yair100 do we need this functionality to be as a menu bar option or is a keyboard shortcut enough?

A menu option is required but a keyboard shortcut can be added as well, do you have one in mind?

**Comment by destrex271** [comment]
@yair100  yes I do have one, currently I was just figuring out the grid view that has been used for the details view.

**Comment by destrex271** [comment]
I am unable to resolve the issue. I am extremely sorry, kindly assign it to someone else.
