### ISSUE TITLE
Copy and rename going weird?

### ISSUE THREAD

**Issue by Colon101** [files-community/Files#8387]
### Description

it is a really difficult to describe accurance but when i use snip and sketch to make a screenshot and copy it over to files after i rename it it just goes allover the place

### Steps To Reproduce

make multiple files to the point you need to scroll (mine had them with numbers if it changes anything) then rename one of them here is whats happening to me:

https://user-images.githubusercontent.com/99831740/154331432-8986cdd2-0eca-4871-be57-1ab42e04821a.mp4

### Expected behavior

scrolls to the top automatically

### Files Version

2.1.13.0

### Windows Version

10

### Relevant Assets/Logs

here is my settings i guess,
[Files_2.1.13.0.zip](https://github.com/files-community/Files/files/8082527/Files_2.1.13.0.zip)
 also sorry if my english is bad

**Comment by gave92** [comment]
Merging with #8159
