### ISSUE TITLE
Feature: Display Nextcloud status

### ISSUE THREAD

**Issue by foxhoundv** [files-community/Files#8388]
### What's the Problem?

In Windows Explorer, with Nextcloud, it can show if a file is saved to your computer or in the personal cloud. 

### Solution/Idea

I know this seems more of a coding request on Nextcloud App side since that is where it originates from to inject the code into Windows Explorer, but maybe there is a way to pull that from Windows Explorer. Maybe have an instance that every time a File Explorer window is opened it checks to see if Nextcloud is installed on the PC and if yes, then execute the code from Windows Explorer into File Explorer... or something along those lines.

### Alternatives

The only other alternative I can see is if Nextcloud includes checking and writing to File Explorer upon install. If maybe File Explorer became more mainstream, then I can see this happening. Hopefully File Explorer does get more attention!

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish including users with Nextcloud | Could |

### Files Version

Version: 2.1.13.0 OS Version: 10.0.22000.493

### Windows Version

Windows 11 Pro Version	21H2  OS build 22000.493

**Comment by gave92** [comment]
Could you show a screenshot of windows explorer vs Files that shows what's missing?

**Comment by foxhoundv** [comment]
Interesting... I didn't see it earlier but now that I opened Files it is showing the status Column that is in Windows Explorer. Though it doesn't come up on the list if you right click on the columns. Also when trying to take this screenshot I noticed if you have the preview pane open it doesn't resize things internally properly. I will include another screenshot of that. So maybe this will be more of a bug issue now.
![explorercompare](https://user-images.githubusercontent.com/16512250/154352573-448c8631-d23d-47e6-a250-a0ada34ddd77.png)
![windowresize](https://user-images.githubusercontent.com/16512250/154353159-4a666988-46f6-4087-b8ff-539436924c46.png)

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?

**Comment by foxhoundv** [comment]
Yes. First image is maximized view, the second one is if I drag the window to the left side of the screen and view it in split screen. Also included in the first image is the right-click on the attribute bar that shows the status tab as not being an option.
![resize-preview1](https://user-images.githubusercontent.com/16512250/179292299-54a8bfc5-9ffa-481a-bdf9-1127f69ecc39.jpg)
![resize-preview2](https://user-images.githubusercontent.com/16512250/179292363-18b86c3b-f9c1-4ed7-b7b9-c89c84c7cf93.jpg)

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaira2** [comment]
@foxhoundv It looks like the status column is visible in the screenshot you shared, can you clarify what the issue is?

**Comment by foxhoundv** [comment]
@yair100 So in the first image I shared, the "status" option wasn't available to turn off or on, not that the column didn't show up. In the second image, the preview pane collapsed the menu so you couldn't turn off the preview pane.

However, that being said, I am running version 2.4.70.0 now and both issues are resolved. Though with one change I would like to request. In Windows Explorer, the columns are moveable to show what is most important where ever the user wants the columns. It would be nice to be able to change the order of the columns around.
