### ISSUE TITLE
Folder format setting

### ISSUE THREAD

**Issue by Merc4tor** [files-community/Files#8389]
### What's the Problem?

You can change if you see folders and files mixed, or sorted differently. 
I prefer to have the folders and files be mixed in the downloads folder because it is easier to see what you downloaded recently. 
But I other folders to be sorted seperate. 

### Solution/Idea

Maybe a button with a menu where you can configure how to folder is formatted,
 like: Settings > preferences > files and folder, for new folders, but you can configure those settings for individual folders.

Idk if it is possible, but would be cool

### Alternatives

That only the downloads folder is formatted like the windows one and that the other folders are formatted like the settings in preferences.

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?
