### ISSUE TITLE
Add file pining to favorites

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#8390]
### What's the Problem?

File exploer now has them i feel files should too.

### Solution/Idea

*

### Alternatives

*

**Comment by yaichenbaum** [comment]
@Josh-65 can you give a little more context how this would improve your workflow?

**Comment by Josh-65** [comment]
Honestly i dont have a use case for it. But other may. i could also see it beeing useful when im helping others as they are not typically organised well.

**Comment by yaichenbaum** [comment]
@Josh-65 I think that bundles feature does the job for this.

**Comment by Josh-65** [comment]
Should this be reconsidered since bundles aren't supported anymore. Had a few people request this on discord too.

**Comment by yaichenbaum** [comment]
Bundles will be replaced with widget for tags.
