### ISSUE TITLE
Creating, renaming or deleting a file or folder requires refresh

### ISSUE THREAD

**Issue by koraxcz** [files-community/Files#8391]
### Description

Creating, renaming or removing a file or folder requires a refresh to become apparant. This happens to me on multiple computers running Windows 11. This is happening on a local drive. 

I have tried restarting, reinstalling, and even tried another machine running Windows 11. One of them is a home computer, the other one is a company computer in an AD domain, both Windows 11. 

This is happening on 2.1.13.0, but I've seen the same issue when I tried Files first sometime in November. 

### Expected behavior

Performing these actions should become apparent immediately, without performing a refresh. 

### Files Version

2.1.13.0

### Windows Version

Windows 11 Pro 21H2

### Relevant Assets/Logs

A video recording of the bug: [link](https://1drv.ms/v/s!AohDmDW98tXLipR7yLhQpOYrEkxQzg?e=g5Pr4t)

**Comment by gave92** [comment]
Does this happen only in network drives/paths or also for local paths?

**Comment by gave92** [comment]
Sorry I didn't notice it was written in the first post. Merging this with #7034
