### ISSUE TITLE
Cannot open properties on any file, program or drive

### ISSUE THREAD

**Issue by SarcXE** [files-community/Files#8392]
### Description

When I try to open the properties for any file, drive or folder nothing happens.

### Steps To Reproduce

1.-Open Files.
2.-Navigate to any directory or file
3.-Press the 'Properties' button.

### Expected behavior

Open a properties window like this

![image](https://user-images.githubusercontent.com/41241527/154370335-e0bf26c2-6092-42d4-a897-96950dd6319a.png)

### Files Version

Version: 2.1.13.0 OS Version: 10.0.22557.1

### Windows Version

Windows 11 Pro Dev 22557.1

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8084151/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
@SarcXE thank you for your feedback, this appears to be a regression in the latest Windows Insider build, can you report the issue on the Feedback Hub?
