### ISSUE TITLE
spacebar acts like down arrow key (unexpected behavior)

### ISSUE THREAD

**Issue by nickgarver** [files-community/Files#8394]
### What's the Problem?

i often preview audio files with spacebar because of this little extension i have, but when i hit spacebar it previews and also arrows down to the next file.  this only happens in big lists of files.

navagating through folders is also a bit slow. i would suggest loading a raw list of the files in first and displaying a placeholder like many messaging apps do when loading lots of messages.

also, when dragging files into programs (audio into abletion, pictures into photoshop) the file is off by a few inches when dragging.  in order to drag into the program i have to drag much lower than where i should and compensate for the drag and drop "hitbox" kindof...sorry it is odd to explain.

love the app thank you so much. it works so nicely

### Solution/Idea

add an option to either turn this function off or add a file preview for audio with spacebar.  

### Alternatives

i currently just preview the file then have to scroll up a bit 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
@nickgarver thank you for your feedback, which version of Files and Windows are you using?

**Comment by nickgarver** [comment]
> 

woah that was fast, i edited a few things about my post also sorry.  it is Version 10.0.19043 Build 19043

**Comment by Josh-65** [comment]
@nickgarver Can you add the infomation asked of
