### ISSUE TITLE
Show Tooltips on disabled buttons

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#8396]
### What's the Problem?

When a button is disabled, its tooltip no longer appears. It is difficult to understand the meaning of a disabled icon and therefore why it is disabled. It's especially annoying in the toolbar or context menu. 

![toolbar](https://user-images.githubusercontent.com/46631671/154453073-cc34fede-11e0-45e7-a734-77eb1ed5daf9.png)

### Solution/Idea

It is possible to globally activate the tooltips on the deactivated buttons. I can create the pr if the feature is accepted.

### Alternatives

Don't enable the feature globally but locally for each button or it makes sense. The tooltip is less useful when the button contains text. 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.1.13.0 OS Version: 10.0.19043.1237

### Windows Version

Windows 10

**Comment by yaichenbaum** [comment]
@cinqmilleans is this the default WinUI behavior?

**Comment by cinqmilleans** [comment]
@yair100 The default behavior of uwp is not to show tooltips for disabled buttons. This is also the case in File Explorer (Tested on Windows 11). It's a detail but it would be an added value compared to File Explorer.

**Comment by yaichenbaum** [comment]
@cinqmilleans is there a property we can set?

**Comment by cinqmilleans** [comment]
@yair100 After checking it is not possible in uwp but only in wpf. There are complex workarounds but it's not worth it. We will forget this feature as long as nothing changes.
https://stackoverflow.com/questions/60949643/how-to-show-tooltip-over-disbabled-button-in-uwp
