### ISSUE TITLE
Issues with Files as default file manager

### ISSUE THREAD

**Issue by ColtMorgan** [files-community/Files#8397]
### Description

I have encountered an issue several times when Files is set as the defualt file manager. After several hours of the system being in use, it will begin to register every key on the keyboard being pressed a letter E. It will also register the Windows key as being held down. Any key presses just result in opening multiple tabs of the Files application. Unregistering as default file manager will fix the issue. This seems to happen after using the Windows Key + E hotkey to launch the application. 

### Steps To Reproduce

1. Set Files as the default file manager
2. Use the Windows Key + E hotkey to launch the file manager
3. Eventually the behavior will present itself

### Expected behavior

I would not expect that the application would cause an issue where the keyboard became unusable

### Files Version

Version: 2.1.13.0 OS Version: 10.0.22000.493

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎11/‎22/‎2021 OS build	22000.493 Experience	Windows Feature Experience Pack 1000.22000.493.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8088395/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8088397/debug_fulltrust.log)

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Does 'http://github.com/files-community/Files/pull/8474' remediate this?

**Comment by Josh-65** [comment]
Is this still an issue

**Comment by ColtMorgan** [comment]
This seems to be a problem across all third party file managers with Windows 11. I began experiencing similar issues with OneCommander as well.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.0.0? if so it likly a windows issue since other programes are doing it according to your comment.
