### ISSUE TITLE
Crash when accessing directory

### ISSUE THREAD

**Issue by Oricul** [files-community/Files#8401]
### Description

Was exploring Files themes (then data directories) at C:\Users\<USERNAME>\AppData\Local\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\ - clicking into the Settings directory will crash the files app pretty consistently.

### Steps To Reproduce

1. Open Files.
2. Click 'Settings' cog.
3. Click the 'i' next to 'Custom Themes'.
4. Click 'Open Themes Folder'.
5. Go up two levels to '49306atecsolution.FilesUWP_et10x9a9vyk8t'.
6. Enter 'Settings' directory. The crash is intermittent when accessing this directory. If it doesn't crash, close and restart process.

### Expected behavior

Settings folder should open without issue.

### Files Version

Version: 2.1.13.0 OS Version: 10.0.22000.493 (Installed from Windows Store)

### Windows Version

Windows 11 Home Version 21H2 22000.493 1000.22000.493.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8090516/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8090520/debug_fulltrust.log)

**Comment by Josh-65** [comment]
Have you tryed reinstalling files

**Comment by enoversum** [comment]
Not sure this is the same problem, but I recently also saw Files crash randomly on opening folders. Explorer opens them fine, also a fresh Files instance will succeed on a second try. I can't really see a pattern.

**Comment by yaichenbaum** [comment]
@enoversum it might be worth opening an issue even if you can't reproduce it consistently.
