### ISSUE TITLE
Change the default copy duplicate option

### ISSUE THREAD

**Issue by Nuckerr** [files-community/Files#8406]
### What's the Problem?

When I copy a file with the same name as an existing file, it by default suggests me to generate a new name. 

### Solution/Idea

May I suggest that a setting that allows you to change the default option and even toggle for the popup and just do it automatically

### Alternatives

I can't really think of any

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must | allow you to change the default option when selecting what to do with default files
| This proposal will allow end users to accomplish X | Should | be a customizable specifically to certain directories as well
| This proposal will allow developers to accomplish Y | Could | have a toggle to turn off the popup entirely and just do it

### Files Version

Version: 2.1.13.0 OS Version: 10.0.22543.1000

### Windows Version

Windows 11 Pro Insider Preview

### Comments

![image](https://user-images.githubusercontent.com/62883418/154553536-2e1e6f8a-e425-4c21-8616-bb92681d1bbb.png)

**Comment by yaichenbaum** [comment]
Merging with #5645
