### ISSUE TITLE
No automatic update of folders

### ISSUE THREAD

**Issue by robebo** [files-community/Files#8411]
Hi,
on every computer i installed Files i have the problem, that folders are not updated automaticly.
If if copy a file in an folder i have to press F5 to update the folder.
Bye

**Comment by yaichenbaum** [comment]
@robebo are you using a network drive?

**Comment by roddone** [comment]
I'm experiencing the same issue.

It seems to occurs only on network drives, here I'm accessing a shared folder on another computer (\\network-path\example\)
File operations like move and delete works, but the UI is not updated. Pressing F5 updates the UI successfully.

[logs.txt](https://github.com/files-community/Files/files/8102227/logs.txt)

**Comment by Josh-65** [comment]
Its a known issue for network drives.

**Comment by robebo** [comment]
Sorry for the missing logfiles.
Yes, it's only on network drives. I'm using a Synology NAS.

**Comment by lwolfs** [comment]
I experience the same problem

**Comment by Josh-65** [comment]
#7304
