### ISSUE TITLE
Files crashes when folder opens and "show folder sizes" is enabled

### ISSUE THREAD

**Issue by wolfplay013** [files-community/Files#8413]
### Description

I don't really know how this happened but it happens every time i go to downloads

### Steps To Reproduce

1. Go to Downloads
2. Files crashes

### Expected behavior

It shouldn't crash

### Files Version

Version: 2.1.13.0 OS Version: 10.0.19042.1526

### Windows Version

Edition	Windows 10 Pro Version	20H2 Installed on	‎23.‎08.‎2020 OS build	19042.1526 Experience	Windows Feature Experience Pack 120.2212.4170.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8097779/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8097780/debug_fulltrust.log)

**Comment by gave92** [comment]
Do you have the "show folder sizes" option enabled? Any difference if you turn it off?

**Comment by wolfplay013** [comment]
Yeah it worked. I'm dumb lmao

**Comment by gave92** [comment]
Thanks for confirming, still something we have to fix.

**Comment by wolfplay013** [comment]
ah okay

**Comment by yaichenbaum** [comment]
This issue should be resolved with #8716
