### ISSUE TITLE
Properities icon of the context menu & files isn't working

### ISSUE THREAD

**Issue by M7MDE7EGAZY** [files-community/Files#8417]
### Description

not working

### Expected behavior

It should view files & folder properities

### Files Version

2.1.13.0

### Windows Version

22557.1

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8100571/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8100572/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
@M7MDE7EGAZY this issue is related to the latest insider build, can you report this issue on the Feedback Hub?
