### ISSUE TITLE
freezes the display

### ISSUE THREAD

**Issue by mi-araf** [files-community/Files#8419]
### Description

After sometimes of running this app, my pc freezes or hang for sometimes. This happens quite much, which gives unpleasant. :((

### Expected behavior

I think this hang bug should be fixed.

### Files Version

Version: 2.1.13.0 OS Version: 10.0.19042.1526

### Windows Version

Windows 10 20H2 19042.1526

### Relevant Assets/Logs

idk

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.0.0? if so could you give your system specs. it may be a case of it been to low in hardware but there performace and comatability improvents beening made.
