### ISSUE TITLE
Not performing simple cut/copy/paste drag n' drop

### ISSUE THREAD

**Issue by Djuganight** [files-community/Files#8420]
### Description

Hello,
I am trying to use this great app but the copy/cut/paste/drag n' drop etc don't seem to work.
Also, it does not show the small images/tiles of .ico files
I have tested at least on 3 different computers, all windows 11 and the issue is there on all them since installation.
What could it be?
Thank you

### Steps To Reproduce

simple copy and paste not work
simple cut and paste not work
drag n' drop not work
not showing tiles/preview of .ico files

### Expected behavior

simple copy and paste 
simple cut and paste
drag n' drop 
Show preview .ico files

### Files Version

Versão: 2.1.13.0 OS Version: 10.0.22000.527

### Windows Version

Windows 11 21H2 22000.527

### Relevant Assets/Logs

![Untitled - 1](https://user-images.githubusercontent.com/6967668/154793823-d7f03a57-d4f9-4bd5-8b3a-c713eff91dd0.jpg)

**Comment by furkanisikay** [comment]
> 

I have also same problem.
I am cutting any files in desktop and pasting into any folder but it is not paste.
Sometimes, I am copying any files in desktop and pasting into any folder, it is paste.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #9014
