### ISSUE TITLE
Allow hiding tab UI

### ISSUE THREAD

**Issue by C0ffeeCode** [files-community/Files#8422]
### What's the Problem?

I do not intend to use tabs in Files.
Therefore, for me it is just takes up lots of UI space and makes the UX more complicated for something I do not use.

### Solution/Idea

Allow us to disable the tab features by hiding its UI.

### Alternatives

Not to allow users to hide it.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to disable/hide tab specific UI if desired | Should |

**Comment by yaichenbaum** [comment]
We don't have plans to implement this change.
