### ISSUE TITLE
Auto highlights first tab when layout is automatically changed to small icons (for folders containing images).

### ISSUE THREAD

**Issue by Shishir8213** [files-community/Files#8424]
### Description

When I open any folder containing images, the layout automatically changes to small icons (expected) and then when I use arrow keys to navigate, it automatically highlights the first tab in the title bar and then I'll have to select the file using the cursor to start navigating with arrow keys.
The issue seems to be resolved when I manually change the layout to something else and then back to small icons.

https://user-images.githubusercontent.com/100041962/154814294-e009d47b-ef15-445a-abc2-476e7b1b4c9c.mp4

### Steps To Reproduce

1. change layout to "Details"
2. open a sub-folder containing images using keyboard (the layout should automatically change to small tiles)
3. the app then highlights the first tab and won't let you move to your files without moving the cursor.

### Expected behavior

It should always highlight the first file in the folder opened after step 2.

### Files Version

version 2.1.13

### Windows Version

Windows 11 21H2 22000.527

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8102774/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8102775/debug_fulltrust.log)

**Comment by yaira2** [comment]
Merging with #10567
