### ISSUE TITLE
Auto focus on content when application is launched

### ISSUE THREAD

**Issue by Shishir8213** [files-community/Files#8425]
### What's the Problem?

Using the keyboard to get around the UI feels buggy and quite half-baked. For Instance, using the keyboard to open files the application now highlights the first tab in the window, while the contents are loading, and user can actually execute a command by mistake during such interval.

### Solution/Idea

Need to strengthen the feature.

### Alternatives

you can take some inspirations from the built in files explorer I guess.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish polish the experience. | Must |
| This proposal will allow end users to accomplish easier navigation capabilities | Should |

**Comment by yaichenbaum** [comment]
@Shishir8213 thank you for your feedback, can you fill out the version information?

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
