### ISSUE TITLE
Search box is 1px shorter than address bar

### ISSUE THREAD

**Issue by ChristopherHaws** [files-community/Files#8427]
### Description

The search box appears to be 1px shorter than the address bar.

### Steps To Reproduce

N/A

### Expected behavior

I would expect for the address bar and search bar to be the same height.

### Files Version

Version: 2.1.13.0 OS Version: 10.0.22000.527

### Windows Version

Windows 11 Pro for Workstations 21H2 22000.527

### Relevant Assets/Logs

Here is what it currently looks like:
![image](https://user-images.githubusercontent.com/5934505/154825506-cd3d9f54-1b96-42ee-98cd-aee075b79e8f.png)

Zoomed in:
![image](https://user-images.githubusercontent.com/5934505/154825527-bf7a3505-1778-450b-9dad-b9681fda4079.png)

**Comment by mnmonherdene1234** [comment]
![giphy](https://user-images.githubusercontent.com/67050647/154966143-367b668e-80ef-4347-aa4d-937982833bf9.gif)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #8452
