### ISSUE TITLE
Wrong sorting order with grouping for creation date

### ISSUE THREAD

**Issue by TheChilliPL** [files-community/Files#8428]
### Description

I have a folder with a lot of files, and this software seems to be unable to sort and group the files based on the creation date correctly. See screenshots below.
It may or may not be related to an issue that makes this folder open showing older files, and then needing me to manually scroll to the top when the rest loads.

### Expected behavior

2022-02-20 should be considered to be after 2022-02-19, unlike it is now.

### Files Version

Version: 2.1.13.0 OS Version: 10.0.22543.1000

### Windows Version

Edition	Windows 11 Pro Insider Preview Version	Dev Installed on	‎2022-‎02-‎15 OS build	22543.1000 Experience	Windows Feature Experience Pack 1000.22543.1000.0

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/18823939/154827592-2a0a8f4f-cf1b-4026-8e2d-7073323d794b.png)

**Comment by gave92** [comment]
Specific to creation date, sorting by modified date appears ok.

**Comment by TheChilliPL** [comment]
> Specific to creation date, sorting by modified date appears ok.

I experience the same issue with sorting and ordering by modified date:
![image](https://user-images.githubusercontent.com/18823939/154844197-8b21ca5a-e65d-4ef1-9a19-10002fa095c8.png)
![image](https://user-images.githubusercontent.com/18823939/154844200-1738b3fd-e85c-483e-8e10-a3c0aed193e0.png)
![image](https://user-images.githubusercontent.com/18823939/154844209-33f5e778-b7b0-4078-b986-cc3f9bb9270b.png)

**Comment by Josh-65** [comment]
Is this still an issue?

**Comment by TheChilliPL** [comment]
It seems to work in small folders, but I cannot negate the possibility that it may still happen in folders with a huge number of files, although I don't have such folders at the moment

**Comment by yaira2** [comment]
@TheChilliPL can you try with the preview version? https://files.community/download/preview
