### ISSUE TITLE
Files app crashing

### ISSUE THREAD

**Issue by IBR-41379** [files-community/Files#8429]
### Description

Files app crashing while viewing a directory where small files(200 1 mb files) are being downloaded and the folder is refreshing simultaneously

### Expected behavior

App crashing and restarting

### Files Version

version 2.1.13.0

### Windows Version

Windows 11 21H2

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8103640/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8103641/debug.log)

**Comment by gave92** [comment]
The usual:
> 2022-02-20 13:54:08.9756|ERROR|AppUnhandledException|Index larger than max value.
Parameter name: index
	System.ArgumentOutOfRangeException: Index larger than max value.
Parameter name: index
   at System.Runtime.InteropServices.WindowsRuntime.IVector_CCWAdapter.EnsureIndexInt32(UInt32, Int32) + 0x74
   at System.Runtime.InteropServices.WindowsRuntime.IBindableVector_CCWAdapter.GetAt(IList, UInt32) + 0x26
   at System.Collections.IList__Impl.Vtbl.GetAt__n(IntPtr, UInt32, Void**) + 0x3e

**Comment by yaichenbaum** [comment]
Is this still an issue in the latest preview build? https://files.community/download/preview

**Comment by IBR-41379** [comment]
Nope. Just tested now. Not anymore.
