### ISSUE TITLE
Change icon

### ISSUE THREAD

**Issue by hetingrui** [files-community/Files#8431]
### Solution/Idea

I like this program but the icon looks a little strange in Windows 11, can you add an "change icon" option in Apperence?

### Alternatives

null

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by gave92** [comment]
Which icons? Most of them are pulled from the system.
