### ISSUE TITLE
OK button not highlighted in Empty Recycle Bin confirmation dialog

### ISSUE THREAD

**Issue by pritster5** [files-community/Files#8432]
### What's the Problem?

In the default Win11 File Explorer, clicking Empty Recycle Bin automatically moves the mouse cursor to the "Yes" button on the confirmation dialogue. 

This doesn't happen in Files and would be nice if it did.

### Solution/Idea

Make the cursor automatically jump to the "Yes" button in the Empty Recycle Bin Confirmation Dialogue.

### Alternatives

Make this feature  a toggleable option perhaps?

### Priorities

Low

### Files Version

Version: 2.1.7.0 

### Windows Version

Windows 11 22000.493

**Comment by gave92** [comment]
Pressing "Enter" already confirms the action. But the OK button should be highlighted.

**Comment by yaichenbaum** [comment]
@pritster5 is this an issue in v2.1.13?

**Comment by gave92** [comment]
Yes, no button appears selected:

![image](https://user-images.githubusercontent.com/9673091/154852974-c45fe750-b7d2-4a7f-8962-8d43644174ac.png)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #8442
