### ISSUE TITLE
Files impressions

### ISSUE THREAD

**Issue by Spacedg** [files-community/Files#8434]
### What's the Problem?

Great program, here are a few suggestions that would really make me consider switching over.

### Solution/Idea

-Option to always expand the left pane to the the current folder.
-Allow more compact details view for the right pane. At the moment the view seems very spaced out vertically and is not suitable for large file lists.
-Allow Select all, Invert Selection, Select None buttons to be added directly on the toolbar.

### Alternatives

...

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.13.0

### Windows Version

10.0.19044.1526

**Comment by gave92** [comment]
Thanks for the feedbak. For the last point:

![image](https://user-images.githubusercontent.com/9673091/154849841-1c2432c2-3a8e-42ba-9fa8-3a916b1d680a.png)
