### ISSUE TITLE
Files crashes

### ISSUE THREAD

**Issue by raineedust** [files-community/Files#8436]
### Description

Files crashes seemingly randomly. This has happened with different file operations on occasions, and isn't reproducible at all times.

### Steps To Reproduce (only for this occasion)

1. Drag and drop an Excel file
2. Files crashes

### Expected behavior

Files does not crash when performing various kinds of operations.

### Files Version

Version: 2.1.13.0 OS Version: 10.0.22000.527

### Windows Version

Windows 11 21H2 22000.527

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8104410/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8104411/debug.log)

**Comment by gave92** [comment]
The only error in the log files appear related to a delete operation. And it's a sadly common one. Are you able to consistently reproduce a crash when deleting items? If you find a way to reproduce it we'd really like to know.

**Comment by raineedust** [comment]
If that was the case, perhaps it crashed after a certain interval. I'm certain I was in the browser as it crashes.

Unfortunately, no, I can't reproduce it consistently. Guess it's case closed seeing as there are multiple similar issues opened, and my log files weren't useful. Lemme know if there's anything more to the issue I can help with though.
