### ISSUE TITLE
Changing attributes in file properties is not very user friendly

### ISSUE THREAD

**Issue by KosmosisDire** [files-community/Files#8439]
### What's the Problem?

In the properties we have two attributes: readonly and hidden. These are underneath a dropdown. The main problem is that these settings are hard to access for a couple of reasons:

1. The dropdown is always folded closed when the properties are opened. Meaning to hide multiple files individually you have to continually reopen the dropdown to get to the hidden checkbox. (Even switching between tabs in properties makes this close)
2. The default size of the properties window means that when you _do_ open the dropdown the options overflow off the page and you have to scroll down to get to them (the window is resizable of course, but the default shouldn't do this)

### Solution/Idea

Take the two attributes out from under the dropdown. Put the options side by side, not hidden under anything. This takes less space and is quick and easy to use.

### Alternatives

These problems could also both be fixed by increasing the default size of the properties window and saving the dropdown's last state (open or closed).

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow the user to quickly and easily access the hidden and read-only checkboxes | Must |
| The two options will not be under a dropdown | Must |
| The two options will be placed side by side | Must |
| If it isn't already, the default window size should be sure to not make the user scroll down to see these options | Should |

### Files Version

N/A

### Windows Version

N/A

### Comments

Here is what it looks like right now:
![image](https://user-images.githubusercontent.com/39423700/154855845-7f966554-4647-41e1-b9ae-f99646cc7dcf.png)

Here is a relatively exact mockup of what I am proposing:
![Properties Mockup](https://user-images.githubusercontent.com/39423700/154857552-f19d434b-b41a-4e5e-88ec-aaca8aec603d.png)

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
We don't have plans to implement this change.
