### ISSUE TITLE
Auto-size column widths

### ISSUE THREAD

**Issue by AMit-96** [files-community/Files#8440]
### Solution/Idea

If we have a feature that can auto-size column widths with a single click, that'd be great. Like in the general settings if we set that enabled, all the columns in all of the folders will automatically adjust, just like the folder size feature.

### Alternatives

Instead of double-clicking on each individual column, we can just click on one button in the Layout option and it should do it. And also have an option in the confirmation window to apply the settings to all the subfolders. This way we can just adjust when we want and to which folder(s) we want instead of using up CPU power on opening every single folder.

### Files Version

v2.1.13.0

### Windows Version

Windows 11

**Comment by yaichenbaum** [comment]
Merging with #8384
