### ISSUE TITLE
Option to show all items on right-click context menu by default

### ISSUE THREAD

**Issue by Thunderz2016** [files-community/Files#8443]
### What's the Problem?

A lot of the more advanced options (such as restore previous versions, 3rd program context menu items) are hidden under the "More" option. This may not be convenient for power users who use those options frequently. While keeping the context menu neat is a great idea, there should also be an option to always show all items for power users. 

### Solution/Idea

An option in the settings to always show all options on the right-click context menu at once, without the need to scroll through them or click on the "More" option.

### Alternatives

The original Windows 10 (and below) File Explorer always shows all items on the context menu for easy access.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end-users to gain access to all context menu items with ease | Must |
| This proposal will allow end-users to decide whether or not to keep the context menu concise or verbose | Must |

### Files Version

2.1.13.0

### Windows Version

Windows 10 Home 21H2 19044.1526

### Comments

![image](https://user-images.githubusercontent.com/24950670/154888989-d34ab090-95ae-4822-bac6-5c58396a5378.png)

These are the current steps to add files to a WinRAR archive from the Files context menu. Just one too many clicks.

**Comment by yaichenbaum** [comment]
Thank you for your feedback, you can display all items in the main menu by turning off the option to move items to a sub menu.
![image](https://user-images.githubusercontent.com/39923744/154890353-07df9f49-b071-48b9-af79-84601ea2cb83.png)
