### ISSUE TITLE
Copy always successful, also when permission denied

### ISSUE THREAD

**Issue by Foakx** [files-community/Files#8447]
### Description

When I copy a dll file in a folder to replace the already existing dll but the dll is used by a exe, i also get the result process successful, but the dll is not replaced

### Steps To Reproduce

Start an .exe with a implemented dll
replace the dll

=> the DLL is still the same like before

### Expected behavior

I should get the result "error while replacing"

### Files Version

Version: 2.1.13.0 OS Version: 10.0.22000.527

### Windows Version

Windows 11 Pro 21H2 22000.527

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8109162/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8109163/debug.log)

![image](https://user-images.githubusercontent.com/59312676/154955354-0df2c805-4671-4a9d-844e-d2b326eb9f44.png)

**Comment by gave92** [comment]
Merging with #7947
