### ISSUE TITLE
Launching from CLI stucks the process

### ISSUE THREAD

**Issue by enisn** [files-community/Files#8448]
### Description

Before last update I can easily launch it from command line with following command:
```bash
files .
```

But with last update, it allocates the process and I'm no longer available to use that command line windows anymore.

![image](https://user-images.githubusercontent.com/23705418/154955418-fa48d583-e238-45ce-926a-b66bfed71dc1.png)

Can't type anything more in that command line unless I stop the opened files instance or pressing CTRL + C

There was no such problem In earlier versions.

### Steps To Reproduce

1. Open a command line (powershell or just 'cmd')
2. Type `files .`
3. You'll see the command line is blocked.

### Expected behavior

A behavior should be same with earlier versions, 

Also it can be comparable explorer.exe.
The bahvior should be same with explorer:
`explorer .`

![image](https://user-images.githubusercontent.com/23705418/154955763-cf6352f9-32af-42d2-a2ff-4e35e82b8b2d.png)
I can still use this command line windows when I use explorer

### Files Version

Version: 2.1.13.0 OS Version: 10.0.22000.527

### Windows Version

Windows 11 21H2 (OS Build 22000.527)

### Relevant Assets/Logs

There is no logs. No action is taken. I'm just launching a new instance.

**Comment by gave92** [comment]
Thanks for the report. Does the instance open correctly? Does the command line unblock if you close the Files window or do you need to kill the process in task manager?

**Comment by enisn** [comment]
The opened instance is working as expected. Command line is unblocked when I close the files instance normally. 

Instance isn't stuck or no-responding. But it blocks command-line during its lifetime

**Comment by yaichenbaum** [comment]
Merging with #3652

**Comment by gave92** [comment]
Same issue, but @enisn says it was working before lastest update
