### ISSUE TITLE
Tags section is visible even if tags are disabled.

### ISSUE THREAD

**Issue by oleklukasiewicz** [files-community/Files#8459]
### Description

Tags section is visible even if tags are disabled in settings.

### Steps To Reproduce

1. Enable tags
2. Show tags section in sidebar
3. Disable tags

### Expected behavior

Tags section should be hidden when tags are disabled.

### Files Version

Files Version 2.1.13.0

### Windows Version

Windows 11 21H2 22000.527

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/69370471/155037679-6b46cd39-af43-482c-a3c4-c2c9252758ba.png)

**Comment by yaichenbaum** [comment]
Merging with #8451
