### ISSUE TITLE
DOUBLE CLICK

### ISSUE THREAD

**Issue by omarbey** [files-community/Files#8462]
### What's the Problem?

NO SMART GESTURES

### Solution/Idea

EXAMLE PREVIOUS PAGE CAN BE OPENED BY DOUBLE CLICK

### Alternatives

https://chrome.google.com/webstore/detail/smartup-gestures/bgjfekefhjemchdeigphccilhncnjldn#:~:text=smartUp%20Gestures&text=A%20better%20gestures%20extension.,boost%20productivity%20by%20you%20mouse.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by gave92** [comment]
Merging with #2355, #7702
