### ISSUE TITLE
QuickLook don't open when press space button

### ISSUE THREAD

**Issue by leorcdias** [files-community/Files#8463]
### Description

When pressing space, files are not opening in a new window to show a preview of it. I've tested it with Office files, images, PDF, TXT, and nothing works.

### Steps To Reproduce

1. Open Files
2. Select a file
3. Press space
4. File don't open preview in new window

### Expected behavior

Open file preview in new window

### Files Version

Version: 2.1.13.0 OS Version: 10.0.22000.527

### Windows Version

Window 11 21H2 22000.527

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8116902/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8116905/debug_fulltrust.log)

**Comment by leorcdias** [comment]
The preview opens only on the desktop. Using Files, does not open preview of any files.

**Comment by leorcdias** [comment]
I noticed that the settings weren't loading correctly, so I reset the app and everything worked again.

- The themes list was not showing, only the current theme was displayed.

- The option to choose the terminal application was also having problems. There was no option in the drop-down list.

After the reset, everything went back to normal.

**Comment by Josh-65** [comment]
So is the issue fixed for you now
