### ISSUE TITLE
Add option to use forward slash

### ISSUE THREAD

**Issue by highfredo** [files-community/Files#8465]
### What's the Problem?
Add support for using forward slashes instead of back slashes

### Solution/Idea

So, when selecting the current route, show a route like "c:/Users/myuser/proyect33" instead of
![file](https://user-images.githubusercontent.com/5951524/155196792-344643af-97c6-493e-80f7-f6550aa315cb.png)

### Alternatives

I have not thought of any alternative.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Why? Surely the file:// URI is superior, and is what most software for Linux utilises.

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
Does msys2 not convert the paths on it's own?

**Comment by highfredo** [comment]
> Does msys2 not convert the paths on it's own?

Nop :(
![image](https://user-images.githubusercontent.com/5951524/179696692-8e17691e-3668-4d06-a69a-9aeeb5f456a2.png)

**Comment by yair100** [comment]
> Asking @yair100 for approval.

Keeping open as a discussion but so far it doesn't seem like there is a lot of interest.
