### ISSUE TITLE
Missing close pane icon

### ISSUE THREAD

**Issue by oleklukasiewicz** [files-community/Files#8466]
### Description

Missing close pane icon in toolbar. 

### Expected behavior

There should be an icon of closing pane

### Files Version

Version: 2.1.13.0 OS Version: 10.0.22000.527

### Windows Version

Windows 11 21H2 22000.527

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/69370471/155218129-08b67cf2-bfc7-4502-a97f-c97bedd8eb7f.png)

**Comment by Creperi** [comment]
The edit is done
(https://github.com/files-community/Files/compare/main...Creperi:patch-1)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #8513
