### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by konradsikorski** [files-community/Files#8467]
### Description

It is neither a bug nor a feature.

I want to contribute to this project but first must build it. Unfortunately, the build fails with this error: 

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB8020	The build tools for v143 (Platform Toolset = 'v143') cannot be found. To build using the v143 build tools, please install v143 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".	CustomOpenDialog	C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets	440	

The readme says I have to install "C++ ATL for UWP build tools" but the VS Installer doesn't have such an option. I have installed the "C++ ATL for latest v143 build tools (x86 & x64)". There is an option "C++ Universal Windows Platform support for v143 build tools (ARM64)", should I install it.

I am using VS Version 17.2.0 Preview 1.0

### Steps To Reproduce

1. Download repo
2. Install VS 2022
3. Install Windows SDK
4. Change Solution Platform to x64
5. Build

### Expected behavior

Solution should build

### Files Version

latest master

### Windows Version

Windows 11 Pro 21H2 22000.527

### Relevant Assets/Logs

n/a

**Comment by Josh-65** [comment]
unload the CustomOpenDialog folder in solution explorer

**Comment by konradsikorski** [comment]
Thx @Josh-65 , I entirely built this project after a few tries of installing and uninstalling components in VS. I have updated the Readme to help other contributors.
