### ISSUE TITLE
I love Files, but it's a bit slow compared to the native windows explorer.

### ISSUE THREAD

**Issue by danielduckworth** [files-community/Files#8468]
### What's the Problem?

I'm used to files and folders responding very quickly. Opening folders in "Files" can be a bit sluggish and sometimes doesn't register double clicks.

Is there any way to speed up the application at my end? Are you planning to optimize the application for responsiveness?

### Solution/Idea

GPU acceleration, faster animation transitions etc.

### Alternatives

Single click to open folders.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Increased responsiveness | Must |
| Configurations to control graphics settings, animations etc. | Should |
| Use GPU acceleration | Could |
| Nyan Cat theme | Won't |

### Files Version

Version: 2.1.13.0 

### Windows Version

Windows OS Version: 10.0.19043.1526

**Comment by Josh-65** [comment]
It currently beeing done and is tracked in #4180

**Comment by yaira2** [comment]
We're excited to share that startup performance will be significantly improved in the upcoming release of version 3. You can download the preview version from our website https://files.community/download.

**Comment by yair100** [comment]
@danielduckworth we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
