### ISSUE TITLE
it crashed when I tried to copy the path of a file from properties windows 

### ISSUE THREAD

**Issue by Saitpstc** [files-community/Files#8469]
### Description

I tried to  copy the path of a file it freezed for 1-2 seconds after that it crashed 

### Steps To Reproduce

1)open a file
2) right click to an application with .exe extension
3) go to properties
4)select the path's  text
5)copy the text
6)file explorer crashed 

### Expected behavior

it should copy the path from properties 

### Files Version

Version: 2.1.13.0 OS Version: 10.0.22000.493

### Windows Version

windows 11 Version 21H2 (OS Build 22000.493)

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8122250/debug.log)

[debug_fulltrust.log](https://github.com/files-community/Files/files/8122251/debug_fulltrust.log)

Here is the event log on system 

Log Name:      Application
Source:        Application Error
Date:          23-Feb-22 9:00:55 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Sait
Description:
Faulting application name: files.exe, version: 0.0.0.0, time stamp: 0x6203e189
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.22000.493, time stamp: 0x632525e9
Exception code: 0xc000027b
Fault offset: 0x0000000000834af0
Faulting process id: 0xe30
Faulting application start time: 0x01d8286ca00f2eb8
Faulting application path: C:\Program Files\WindowsApps\49306atecsolution.FilesUWP_2.1.13.0_x64__et10x9a9vyk8t\files.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: e4bad2ac-7a5d-428b-8a54-3998ed190757
Faulting package full name: 49306atecsolution.FilesUWP_2.1.13.0_x64__et10x9a9vyk8t
Faulting package-relative application ID: App
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-02-23T06:00:55.9981671Z" />
    <EventRecordID>4846</EventRecordID>
    <Correlation />
    <Execution ProcessID="18996" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>Sait</Computer>
    <Security />
  </System>
  <EventData>
    <Data>files.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>6203e189</Data>
    <Data>Windows.UI.Xaml.dll</Data>
    <Data>10.0.22000.493</Data>
    <Data>632525e9</Data>
    <Data>c000027b</Data>
    <Data>0000000000834af0</Data>
    <Data>e30</Data>
    <Data>01d8286ca00f2eb8</Data>
    <Data>C:\Program Files\WindowsApps\49306atecsolution.FilesUWP_2.1.13.0_x64__et10x9a9vyk8t\files.exe</Data>
    <Data>C:\Windows\System32\Windows.UI.Xaml.dll</Data>
    <Data>e4bad2ac-7a5d-428b-8a54-3998ed190757</Data>
    <Data>49306atecsolution.FilesUWP_2.1.13.0_x64__et10x9a9vyk8t</Data>
    <Data>App</Data>
  </EventData>
</Event>

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.0.0?

**Comment by Saitpstc** [comment]
at that time it was buggy   so I  stopped using it.   Today  I downloaded to see if  it  fixed or not.Unfortunately it still same on the 2.3.3 version. It's not crashing like it used to(It crashed only once it was the same exception )  but now when I execute same steps after runing application it works fine but when I close the properties window and open again  it  seems like properties window freezing  also  I cant use right click  anymore with second time 
![2022-07-11 12-24-58_Trim](https://user-images.githubusercontent.com/42850688/178235182-7d888aa6-baf3-47d8-ad51-f8d4027f35ef.gif)

**Comment by Josh65-2201** [comment]
@yair100

**Comment by yaichenbaum** [comment]
This is a known issue with AppWindow and has been reported to Microsoft.
