### ISSUE TITLE
GetInfo title font color is invisible with Grass Green Theme and Light Color and System Dark mode 

### ISSUE THREAD

**Issue by mqliang** [files-community/Files#8470]
### Description

As the screenshoot, GetInfo title font color is invisible:

<img width="1417" alt="image" src="https://user-images.githubusercontent.com/12423751/155283157-9e518bbd-22d0-49c8-a678-232a2fa932ec.png">

My setting:
* Choose your color: Light
* Custom themes: grass green
* System mode: dark
<img width="1401" alt="image" src="https://user-images.githubusercontent.com/12423751/155283603-44b0c3e9-d2fd-45b3-99c5-a3ed358b87d8.png">

### Expected behavior

GetInfo font color should be visible

### Files Version

2.1.13.0

### Windows Version

Windows 21H2 22000.527

### Relevant Assets/Logs

-

**Comment by gave92** [comment]
Thanks for the report. Just to confirm: is it ok with default  theme?

**Comment by yaichenbaum** [comment]
> Thanks for the report. Just to confirm: is it ok with default theme?

This seems to be the issue with using a light mode when the system theme is dark mode.

**Comment by yaichenbaum** [comment]
Merging with #6066
