### ISSUE TITLE
The application shut down while doing copy paste.

### ISSUE THREAD

**Issue by Shifath472533** [files-community/Files#8471]
### Description

In a folder I just copied a file and paste it there. But without any reason the application was closed. I happend 3+ times.

### Steps To Reproduce

The steps are simple copying and pasting a file. But Later on I found that I enabled the option "Preview Pane" and the size of the file was 507.63 KB. It was an XML file.

### Expected behavior

It shouldn't shut down like this.

### Files Version

Version: 2.1.13.0 OS Version: 10.0.22000.493

### Windows Version

Edition	Windows 11 Home Single Language Version	21H2 Installed on	‎11/‎11/‎2021 OS build	22000.493 Experience	Windows Feature Experience Pack 1000.22000.493.0

**Comment by gave92** [comment]
Thanks for the report. Could you post the log files? You can get them from Settings > About > Ope log location (the two .log files)
