### ISSUE TITLE
cleartype rendering for fonts

### ISSUE THREAD

**Issue by soredake** [files-community/Files#8472]
### What's the Problem?

Right now most (all?) UWP apps use grayscaling for font rendering, which is looks bad on low dpi (92 in my case) monitors.

### Solution/Idea

Would be nice to have option to render fonts with cleartype like in classic win32 apps.

### Alternatives

?

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.13.0 

### Windows Version

Windows 11 PRO 10.0.22000.527

**Comment by yaichenbaum** [comment]
@soredake this is the expected behavior for UWP applications, can you open an issue on the WinUI repository for this?

**Comment by soredake** [comment]
@yair100 created a report, but i doubt they will do anything https://github.com/microsoft/microsoft-ui-xaml/issues/7115

**Comment by JiaChen-Zeng** [comment]
[MacType](https://github.com/snowie2000/mactype) is also not compatible with this program. People like me who use MacType are not likely to be able to stand the bad font rendering. Is there any way to improve it or make it compatible?
