### ISSUE TITLE
Is sort really sorting?

### ISSUE THREAD

**Issue by NomSayin** [files-community/Files#8475]
### Description

Trying to get files to sort by "date modified" in order to see most recent files/folders first.  Sort is not sorting so I must switch back to File Explorer.

### Expected behavior

Expected to see files/folders sorted in order chosen.

### Files Version

Version: 2.1.13.0 OS Version: 10.0.22000.527

### Windows Version

Both Windows 10 and Windows 11 

### Relevant Assets/Logs

![Sort](https://user-images.githubusercontent.com/100302072/155361052-4577bd5e-f933-49bf-9a89-61987018af51.png)

**Comment by cinqmilleans** [comment]
The files are sorted on your screenshot. Sorting is chronological, not alphabetical.
