### ISSUE TITLE
Box cloud storage issues

### ISSUE THREAD

**Issue by ArcticFox7** [files-community/Files#8477]
### Description

I use the box drive app that integrates the cloud storage provider's box into file explorer, but it does not play nicely with the app, it uses the feature that only downloads content when opened and I think this is causing the issue. but the main page constantly refreshes when in the box folder and it only leads up the folder names for the main directory not any sub directories or actual files. subdirectories.

### Expected behavior

All file name are displayed and sub folders and downloaded when opened. subfolders

### Files Version

2.1.12.0

### Windows Version

Windows 11 21H2 22000.527

### Relevant Assets/Logs

![Screenshot 2022-02-23 094938](https://user-images.githubusercontent.com/46506398/155366798-ff56a1e2-59d8-4d2c-901c-0b9100260c7b.png)

**Comment by gave92** [comment]
#7428
