### ISSUE TITLE
Addition of List View

### ISSUE THREAD

**Issue by sepsol** [files-community/Files#8481]
### What's the Problem?

Mac Finder has a lot of views that Windows lacks. Files introduces the `Column` view on windows but I wish we also had access to the `List` view as well.

### Solution/Idea

The List view from macOS:

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/47871887/155403274-9eeffdf5-6acc-4d2b-b051-8c8223a93521.png">

### Alternatives

N/A

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish N/A | Must |
| This proposal will allow end users to better explore their files | Should |
| This proposal will allow developers to accomplish N/A | Could |
| This proposal will allow end users to accomplish N/A | Won't |

### Files Version

Version: 2.1.13.0

### Windows Version

Windows 11 21H2 22000.527

**Comment by yaichenbaum** [comment]
Merging with #2509
