### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Saraccostein** [files-community/Files#8484]
### Description

La aplicación se reinició a la hora que quise eliminar una carpeta de un programa ya desinstalado.

### Steps To Reproduce

1. Abrir la carpeta de programas del equipo
2. Seleccionar la carpeta de adobe
3. Eliminar
4. ¿Desea darle permisos de administrador a Files? -Si
5. Files cierra abruptamente y se reabre y sale una leyenda que dice Files ha tenido un error al eliminar el archivo

### Expected behavior

Que sea capaz de borrar  el archivo.

Nota: Aparte de todo lo anterior, cuando pongo a Files como explorador de archivos predeterminado, siempre al abrir el panel de control y otras ventanas de configuraciones y sistemas se abre files para poder abrir panel del control y después se cierra, solo aparece un momento, es algo molesto que impide que files sea mi administrador de archivos predeterminado, sería un gusto si pudieran corregirlo, gracias!!!

### Files Version

Versión: 2.1.13.0 OS Version: 10.0.22000.493

### Windows Version

Edición	Windows 11 Pro Versión	21H2 Se instaló el	‎11/‎12/‎2021 Compilación del SO	22000.493 Experiencia	Paquete de experiencia de características de Windows 1000.22000.493.0

### Relevant Assets/Logs

Disculpen, no soy programador así que no supe que poner en esta área, además intenté provocar el fallo de nuevo y no ocurrió así que tampoco tengo capturas, tengo la sospecha que es porque algún servicio de adobe seguía ejecutándose en segundo plano y se hospedaba en esa carpeta, aún así creo que deberían agregar un cuadro de diálogo que diga que no se puede eliminar porque un programa está utilizando esos archivos

**Comment by Josh-65** [comment]
You will need to upload the logs files directly to github. You can get them in files settings > about > open log folder.
