### ISSUE TITLE
Bug: Can only extract 16 files with drag to unzip

### ISSUE THREAD

**Issue by xgitc** [files-community/Files#8485]
### Description

Can only unzip 16 files with drag to unzip. And it can be determined that it has nothing to do with the unzip software, because I have tried two kinds of unzip software (WinRAR & Bandizip). Please help fix this bug, thanks for the FILES again.

### Steps To Reproduce

1. Open the zip/RAR file in 7zip/WinRAR.
2. Select 20 or more files.
3. Drag the selected files to the Files window.
4. See only 16 files extracted.

### Expected behavior

Extract all items

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.527

### Windows Version

Windows 11 21H2

**Comment by yaichenbaum** [comment]
@gave92 is this still an issue?

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview build? https://files.community/download/preview

**Comment by sthivaios** [comment]
> Is this still an issue in the preview build? https://files.community/download/preview

Nope, it is not. I just tried it and on version 2.3.48.0 it seems to be fixed.

I was able to drag 20 files out of a zip file.


https://user-images.githubusercontent.com/109022579/195946684-6a40799b-3189-432e-aec9-8c3aae2d7f80.mp4

I also tried it with a 100 files later, and it worked too.

**Comment by Josh-65** [comment]
Should be tested using 7zip or WinRAR to extract as there external programs that are used

**Comment by HyPeRXKo** [comment]
Unfortunately, it's not working with WinRAR. (on the preview version)

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
What steps can I use to reproduce this?

**Comment by Josh-65** [comment]
1. Open the zip/RAR file in 7zip/WinRAR.
2. Select 20 or more files.
3. Drag the selected files to the Files window.
4. See only 16 files extracted.

**Comment by yaichenbaum** [comment]
Is this an issue with Files or with the archive apps @gave92?

**Comment by HyPeRXKo** [comment]
For me, it's only an issue with Files, I can unzip from WinRAR to the windows explorer fully, but with files, it will only transfer 16.

**Comment by AestheticalZ** [comment]
Same issue here, with WinRAR too.
