### ISSUE TITLE
The app keeps crashing when I am on column mode and I press the back button from my mouse. 

### ISSUE THREAD

**Issue by EvilCheez** [files-community/Files#8489]
### Description

App crashes when in Column mode and press the back button from mouse. 
This happened three times yesterday. Overall, I would say the app isn't that stable and that's with only 5 tabs open. 

Well that was the case, but as I was writing this, it crashed and I wasn't even on the Column mode. 

### Expected behavior

go back

### Files Version

Version: 2.1.13.0 OS Version: 10.0.19043.1526

### Windows Version

10

### Relevant Assets/Logs

[debug.txt](https://github.com/files-community/Files/files/8130613/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/8130614/debug_fulltrust.txt)

**Comment by Josh-65** [comment]
Merging with #8409
