### ISSUE TITLE
Set Default Layout mode

### ISSUE THREAD

**Issue by EvilCheez** [files-community/Files#8490]
### What's the Problem?

I would love to have the Column layout mode to be the default. 

### Solution/Idea

Add an option to set a layout mode to be the default for all folders you open. 

### Alternatives

The alternative would be for the app to not crash and return to whatever mode it feels like returning after the crash. 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by Josh-65** [comment]
You can by going to Files settings > preferences > file and folder > turn off individual preferences. Then select collum layout in any folder.
