### ISSUE TITLE
Eliminate Animations.

### ISSUE THREAD

**Issue by EvilCheez** [files-community/Files#8491]
### What's the Problem?

I've said it before and I'll say it again because I keep coming back on this app and I just can't stick to it because of some issues that make it feel really slow. One of the reasons is the animations. There are animation everywhere, but the worst one is when you click a tab, it takes a full second till it changes tab. All these rollover animations and on press, are really not worth it IMO. 
I want files to be as responsive as possible since the main reason I am using it is to de-clutter my desktop when I work that I usually have like 10 windows open at the same time. 

### Solution/Idea

The idea here is simple in though, but not sure if it's simple in coding terms. 
An option to remove or make the animations faster kinda like Android developer mode options. 

### Alternatives

The alternative here, is that I'm always end up going back to the default file explorer because even though I LOVE files, these "issues" are making it not worth it to use in daily basis, it feels fragile sometimes.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by Josh-65** [comment]
There are very little animations and many slow downs are proberly from the app iteself witch is beeing improved with #4180 but is limited currently. You can go to Windows settings > ease of access/Acssesability > turn off windows animations, then restart files and see if it improved for you.

**Comment by EvilCheez** [comment]
Thanks for your reply. 
Animations are turned off but that doesn't change anything in Files app. There's still noticeable lag when changing from one tab to another and the animations when clicking a folder/file are still there and for me, it makes the experience way slower than it should be.

**Comment by gave92** [comment]
I suppose you're on windows 10? Animations when clicking the list are system-made and can't be removed (without degrading performance). Good news is that they are not present anymore on windows 11.

**Comment by yair100** [comment]
@EvilCheez we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
