### ISSUE TITLE
default shortcut and request

### ISSUE THREAD

**Issue by drinehart1** [files-community/Files#8492]
Your app appears clean and functional however I saw several posts on web about replacing the Windows file explorer with the Files app but the version I downloaded (2.1.15) does not have this option in the Experimental section.  Are you planning to put this back in with next version?  I would like to use the shortcut to pull up Files instead of Windows File Explorer.

Separately, as a feature request, it would be nice to have saved tabs (assuming folders still exist).  To autosave state (like Notepad++ saving files automatically even if user does not) would be a huge productivity improvement (for me) as I frequently open navigation to the same locations.

**Comment by Josh-65** [comment]
You now need to slide load it from the files site https://files.community/
