### ISSUE TITLE
White text white background on properties

### ISSUE THREAD

**Issue by falcon550** [files-community/Files#8493]
### Description

Sorry if repost. here's the issue- 
![image](https://user-images.githubusercontent.com/100348186/155500769-db9924ad-dde1-4acf-8968-f471675c76c3.png)
expected properties window and texts on the opposite color.

### Steps To Reproduce

1. Personalization
2. colors>custom 
![image](https://user-images.githubusercontent.com/100348186/155500588-88ac0d76-2398-490b-abf9-93e3018ba487.png)

3. windows dark, app white
4. on file app, any items properties. 
![image](https://user-images.githubusercontent.com/100348186/155501044-ae0e57cc-3739-466e-a4a2-7f8f26c7b437.png)

### Expected behavior

Window and texts should have been opposite in color

### Files Version

2.1.15

### Windows Version

11

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/100348186/155501112-bc241f42-1632-43a7-ae5e-f332d546f96c.png)
![image](https://user-images.githubusercontent.com/100348186/155501121-1dfff5bf-0db2-4cd8-983b-f8ad44b65b23.png)

**Comment by gave92** [comment]
Thanks for the report. Tracked in #6066
