### ISSUE TITLE
Double-Click Blank Space to Go Back

### ISSUE THREAD

**Issue by sohotrightnow** [files-community/Files#8496]
### What's the Problem?

Clicking the back button is super tedious in file explorers.  It's so tiny!  

### Solution/Idea

If I could double-click any blank space in a folder and have it back up (or alternately go up a level in the hierarchy) that would make it super-easy to back up without having to even glance away from the main window.

### Alternatives

Other options might be a click-and-drag-to-the-left on blank space?  

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish: Backing up easily without finding and clicking the <- button | Must |
| This proposal will allow end users to accomplish: Give users the option whether this double-click should go back or go up a level in the hierarchy | Should |

### Files Version

2.1.13.0

### Windows Version

Windows 10

**Comment by gave92** [comment]
#2355
