### ISSUE TITLE
Icons/Text skew when selecting/deselecting files and folders.

### ISSUE THREAD

**Issue by snarkDADMin** [files-community/Files#8497]
### Description

When clicking on a file or folder when using the Details view type, a little animation will occur (which I wish I could disable) as the folder is selected. This results in the text being skewed in one direction or the other. Clicking another file sometimes leaves the text skewed. When I click on this skewed text again, it sometimes skews _the other direction_ or it may straighten itself back out, remain skewed, etc. There doesn't seem to be any rhyme or reason to this but it is very irritating, although not unworkable.

### Steps To Reproduce

Use Details layout
Click any file or folder.
Text and icon will skew after a small animation plays when they are selected (which I would like to have the option to turn off eventually)
Selecting other items will leave the previously selected item skewed
Going back to a skewed item will change the skew, or possibly get close to straightening it.

### Expected behavior

Icons and text should remain upright and normal when selected, and remain that way when deselected.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.17763.2452

### Windows Version

Windows 10 LTSC 2019 (1809)

### Relevant Assets/Logs

![ApplicationFrameHost_3G0fNgaXAB](https://user-images.githubusercontent.com/10532219/155568346-7df38283-16f8-4bd1-b059-7e66bf2b0b9a.png)
![ApplicationFrameHost_BwHmsVrs9I](https://user-images.githubusercontent.com/10532219/155568348-ba975391-9879-4dbf-a55f-7fc8c86e4909.png)

**Comment by snarkDADMin** [comment]
To add, I just verified after posting that this only occurs in Details view, which is the one I am used to and need to use 95+% of the time. It does not occur in columns view despite it being a "list" view. I will update the original post to clarify this.

**Comment by gave92** [comment]
Closing this as I'm fairly sure it's an OS issue (should not happen e.g on windows 11 where system click animations are removed). Can't reproduce on newer versions of windows 10 as well. @yair100 feel free to reopen if you think differently.

**Comment by yaichenbaum** [comment]
@gave92 it sounds like the column layout doesn't have this issue, can you confirm?
