### ISSUE TITLE
Moving Sidebar items context menu options from sidebar class to items classes

### ISSUE THREAD

**Issue by oleklukasiewicz** [files-community/Files#8498]
### What's the Problem?

In the SidebarControl.xaml.cs file, all the right-tap methods have a lot of variables specific to the current item (IsLocationItem, ShowProperties etc. ) that often repeat or are based on comparing item text, which decreases its flexibility and increases the size of the class code.

### Solution/Idea

We could move these variables from sidebar methods to items directly.
After that every item will store text, icon ect. but also which context menu options will be shown in context menu.

### Alternatives

N/A

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to make future changes to sidebar items easier | Should |
| This proposal will allow to reduce code behind size | Must |

**Comment by d2dyno1** [comment]
@oleklukasiewicz Would you like to work on it?

**Comment by oleklukasiewicz** [comment]
@d2dyno1 Sure!
