### ISSUE TITLE
Bugs that I've found

### ISSUE THREAD

**Issue by Dangomation** [files-community/Files#8500]
### Description

Heya, I love using the program but here are a few things I've noticed when using the program. 

- "Theme's" don't show up for whatever reason.
- General slowdowns when basic browsing. 
- "Bundles" would disappear on computer reboot
- "Show Folder Size"(I know, experimental) when entering folders sometimes "loses track" of data. I.E entering sometimes dens folders and saying they aren't as large as before.

I wish I had more specifics to help out. I hope at min the performance problems get dulled out! 
~Thanks!

### Steps To Reproduce

I wish I had specifics to help out here

### Files Version

Version: 2.1.15.0 OS Version: 10.0.19044.1466

### Windows Version

Edition	Windows 10 Pro N Version	21H2 Installed on	‎10/‎1/‎2021 OS build	19044.1466 Experience	Windows Feature Experience Pack 120.2212.3920.0

### Relevant Assets/Logs

N/A?

**Comment by yaichenbaum** [comment]
Thank you for your feedback, in order to address your feedback, please comment on existing issues and open individual feature requests so we can track each one separately.

**Comment by Dangomation** [comment]
Just so I go through the right channels. I would be making 3 separate bug reports. 
I can do that. though it will be quite sparse with details.
