### ISSUE TITLE
Trying to delete a folder will increase CPU to almost MAX without succes

### ISSUE THREAD

**Issue by Noisemagician** [files-community/Files#8501]
### Description

Hi,

When I try to delete a folder the CPU increases to almost max, the folder does not delete.

Sidenote, the option to remove Files from default software editing REGEDIT is removed. Please add it back, at times like this when FIles is not working properly I want to use windows explorer. 

### Expected behavior

Fix CPU usage, fix not being able to delete a folder. 

Add option to change files from default software. 

### Files Version

Version: 2.1.15.0 OS Version: 10.0.19043.1526

### Windows Version

Edition	Windows 10 Home Version	21H1 Installed on	‎16/‎09/‎2021 OS build	19043.1526 Experience	Windows Feature Experience Pack 120.2212.4170.0

### Relevant Assets/Logs

none

**Comment by gave92** [comment]
Any difference if the folder is small / big / empty?

**Comment by gave92** [comment]
To restore windows explorer run this script (make sure to save it as a ".reg" file):
https://raw.githubusercontent.com/files-community/Files/main/src/Files.Launcher/Assets/FilesOpenDialog/UnsetFilesAsDefault.reg

**Comment by Noisemagician** [comment]
> Any difference if the folder is small/big/empty? Does the delete confirmation dialog appear?

I am going to reinstall it not from Microsoft store because of the removed functionalities. I am going to test it afterward. Thank you.

**Comment by yaichenbaum** [comment]
> Sidenote, the option to remove Files from default software editing REGEDIT is removed. Please add it back, at times like this when FIles is not working properly I want to use windows explorer.

The option to reset the default file manager should still show if the setting is already turned on.

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?
