### ISSUE TITLE
Not able to move the window if the drager point is out of the right window edge.

### ISSUE THREAD

**Issue by Mannshoch** [files-community/Files#8504]
### Description

Not able to move the window if the pick-point in the Title bar is out of the right window edge. You have to resize the window until you found enough space to click and drag.
Also, it is not possible to resize from maximize by dragging the window from the top edge.

### Steps To Reproduce

1. Open Window
2. Move it outside the right Border
3. Open new Tabs until the drag-point in title bar is missing.

### Expected behavior

moving Window ishould be possible. Some pixel above the tab to drag the window is needed

### Files Version

2.1.15.0

### Windows Version

Windows 10 H2 19044

### Relevant Assets/Logs

![grafik](https://user-images.githubusercontent.com/7795891/155705615-fac4c8f9-d3d4-4c51-a9c0-29126f4c928c.png)

**Comment by yaichenbaum** [comment]
@Mannshoch this issue should be resolved with #9157.
