### ISSUE TITLE
>Os temas desapareceram                               >The themes disappeared

### ISSUE THREAD

**Issue by lucasaraujocabra** [files-community/Files#8509]
### Description

![image](https://user-images.githubusercontent.com/61991370/155765824-434388dc-d181-42a1-ac7f-a06cea28a9cd.png)

### Expected behavior

escolher livremente os temas!

### Files Version

Versão: 2.1.15.0 OS Version: 10.0.22000.318

### Windows Version

windows 11 

### Relevant Assets/Logs

resposta?

**Comment by gave92** [comment]
Please try to reinstall the app. Themes should come back. Please let us know.

**Comment by lucasaraujocabra** [comment]
Voltou obrigado!
