### ISSUE TITLE
Shortcuts on network drives

### ISSUE THREAD

**Issue by Chrisswl** [files-community/Files#8510]
### What's the Problem?

Shortcuts on network drives is not displaying.  The ones on local drive work.

### Solution/Idea

Please add support for network shortcuts.

### Alternatives

No action.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by gave92** [comment]
#2436
