### ISSUE TITLE
Refresh folder after file moves

### ISSUE THREAD

**Issue by JoshChymy** [files-community/Files#8517]
### What's the Problem?

Panes do not refresh after renames, move, deletion, copy or paste options. 

### Solution/Idea

Add a toggle to turn this functionality to enable automatic refreshing of panes when files and folders are moved or renamed. 

### Alternatives

perhaps make this default behavior. 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Refresh panes on file move (copy, paste, cut) | Must |
| refresh panes on file rename | Must |
| refresh panes on file/folder creation | Must |
| refresh panes on file/folder deletion | Must |

### Files Version

2.1.15.0

### Windows Version

Windows 11 21H2 22000.527

**Comment by ShoQue92** [comment]
Supporting this feature request!

**Comment by Josh-65** [comment]
What do you mean by panes. is it the preview pane or the actual file/folder content area

**Comment by JoshChymy** [comment]
the actual file/folder content area. Even when creating a new file or folder, you must refresh the page to view the entity you just created.

**Comment by Josh-65** [comment]
Mergin with #7304
