### ISSUE TITLE
Cloud Box Folder continuously refreshes 

### ISSUE THREAD

**Issue by aconc** [files-community/Files#8518]
### Description

With a synced Box cloud folder the folder refreshes every 2 seconds. No files can be viewed only folders. Tab refreshes continuously not allowing interactions with folders and files within the box folder.

### Steps To Reproduce

1. Click on Cloud Drives
2. Select "Box" folder
3. Watch box folder continiously refresh

### Expected behavior

Expect box folder to load once and only refresh on open.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.493

### Windows Version

Windows 11 21H2

### Relevant Assets/Logs

![ApplicationFrameHost_PFvEiefyzO](https://user-images.githubusercontent.com/78361939/155854888-24f98c92-d155-488f-8cb1-08b0599c063a.gif)

**Comment by gave92** [comment]
#7428
