### ISSUE TITLE
Set default file manager nowhere to be found

### ISSUE THREAD

**Issue by lopbox** [files-community/Files#8521]
I just downloaded and installed the files v2 app from the Microsoft Store and at the experimental section the setting to make it as a default file manager is nowhere to be found. I attach 2 screen shots, one with the version and another with the menu on experimental tab.
![34-26-22-233422](https://user-images.githubusercontent.com/1247044/155859878-d61042d0-571e-4fda-878c-a065c165051f.png)
![34-26-22-233459](https://user-images.githubusercontent.com/1247044/155859881-7fc13901-308b-4128-b7e1-15b270400734.png)
.

**Comment by Lauvap06** [comment]
#8521

**Comment by Josh-65** [comment]
It's only available in the sideload version https://files.community/download/stable
