### ISSUE TITLE
files can not open files with space

### ISSUE THREAD

**Issue by anoykin** [files-community/Files#8522]
There is a folder located on the desktop and in File Explorer. When opened from the desktop, instead of the name "TG Spam" in Files, TG is written (and, accordingly, it turns out that such a folder was not found). Fix this please! Attached video with error

https://disk.yandex.ru/i/1Xis76SbO4VYlQ

**Comment by Josh-65** [comment]
Please use the issues templates. https://github.com/files-community/Files/issues/new/choose
