### ISSUE TITLE
There is a folder located on the desktop and in File Explorer. When opened from the desktop, instead of the name "TG Spam" in Files, TG is written (and, accordingly, it turns out that such a folder was not found). Fix this please! Attached video with error  https://disk.yandex.ru/i/1Xis76SbO4VYlQ

### ISSUE THREAD

**Issue by anoykin** [files-community/Files#8524]
### Description

There is a folder located on the desktop and in File Explorer. When opened from the desktop, instead of the name "TG Spam" in Files, TG is written (and, accordingly, it turns out that such a folder was not found). Fix this please! Attached video with error

https://disk.yandex.ru/i/1Xis76SbO4VYlQ

### Steps To Reproduce

There is a folder located on the desktop and in File Explorer. When opened from the desktop, instead of the name "TG Spam" in Files, TG is written (and, accordingly, it turns out that such a folder was not found). Fix this please! Attached video with error

https://disk.yandex.ru/i/1Xis76SbO4VYlQ

### Expected behavior

There is a folder located on the desktop and in File Explorer. When opened from the desktop, instead of the name "TG Spam" in Files, TG is written (and, accordingly, it turns out that such a folder was not found). Fix this please! Attached video with error

https://disk.yandex.ru/i/1Xis76SbO4VYlQ

### Files Version

latest

### Windows Version

11

### Relevant Assets/Logs

There is a folder located on the desktop and in File Explorer. When opened from the desktop, instead of the name "TG Spam" in Files, TG is written (and, accordingly, it turns out that such a folder was not found). Fix this please! Attached video with error

https://disk.yandex.ru/i/1Xis76SbO4VYlQ

**Comment by Josh-65** [comment]
- Lastest is not a version. 11 is that use full. you can find both of these by going to files settings > about > copy button. 
- Dont spam the same thing everywere its not usefull. 
- You will need to upload the logs files directly to github. You can get them in files settings > about > open log folder.
