### ISSUE TITLE
Some Bugs of plug-in UDisk.

### ISSUE THREAD

**Issue by RickPan357** [files-community/Files#8526]
### Description

1. When plugin U-disk, sometimes will show many U-Disk Icon in the home panel.
2. Use Files open UDisk, copy/remove files. After that, sometime can not stop/remove the disk from Safe and reject disk function.

The UDisk means USB harddisk, not only UDisk.

### Steps To Reproduce

1.Plug-In UDisk
2.Open Tab in home tab page
3.Sometimes will show many U-Disk icon.

1.Copy/remove files in UDisk.
2.Use Sage and reject disk function (windows function in right-bottom task panel), but shows can NOT safety remove it.

### Expected behavior

<img width="782" alt="Snipaste_2022-02-27_21-34-08" src="https://user-images.githubusercontent.com/41313154/155884574-231f14de-3c42-4602-aa0a-960dedbfe44e.png">

### Files Version

2.1.15.0 OS Version: 10.0.22000.527

### Windows Version

Win11 21H2

### Relevant Assets/Logs

<img width="782" alt="Snipaste_2022-02-27_21-34-08" src="https://user-images.githubusercontent.com/41313154/155884556-a60ea8d3-8a08-45f3-bae7-55bcfa6969bd.png">

**Comment by yaichenbaum** [comment]
@RickPan357 can you upload the log files?

**Comment by RickPan357** [comment]
> @RickPan357 can you upload the log files?

Sure I can. But can you tell which file you need? 
And whether need me clear the log file, and then plug-in the UDisk so that you can find the issue in log easily?

**Comment by yaichenbaum** [comment]
@RickPan357 the log files from the app directory (there is an option to open the directory in the about page). Clearing the files and reproducing the bug would be helpful.

**Comment by RickPan357** [comment]
The log files as attached.

BTW, maybe you can repeat this issue with below steps:
1. open some tabs of some folder.
2. plug-in udisk1. if works normally, unplug, plug again.
3. unplug, and plug-in udisk2. should find the issue.

[debug.log](https://github.com/files-community/Files/files/8174723/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8174725/debug_fulltrust.log)

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.0.0?

**Comment by yaichenbaum** [comment]
I can't reproduce this on my end but I'm not sure if I got all the steps right. We can reopen the issue if users are still experiencing it.
