### ISSUE TITLE
Can't set to default anymore because button doesn't exist!

### ISSUE THREAD

**Issue by OscarPutz14** [files-community/Files#8527]
### Description

Since the latest update (downloaded from MS Store) I can't set the app to default anymore because the button under "experinatl" doesn't exist anymore! The only 2 options I can see now are "show markings" and "show folder size". What can I do?
![Screenshot 2022-02-27 153210](https://user-images.githubusercontent.com/91553409/155886638-147ef431-2ada-4b02-8834-1b059c45f7b2.png)

### Steps To Reproduce

Use the latest version. I don't know what else I did wrong...

### Expected behavior

Option to set to default should be shown.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.527

### Windows Version

Windows 11 Home 21H2 Edition	Windows 11 Home Version	21H2 Installiert am	‎30.‎01.‎2022 Betriebssystembuild	22000.527 Leistung	Windows Feature Experience Pack 1000.22000.527.0

### Relevant Assets/Logs

![Screenshot 2022-02-27 153210](https://user-images.githubusercontent.com/91553409/155889679-20299527-95d5-4c2a-a2a8-d08cc9a5d4ef.png)

**Comment by yaichenbaum** [comment]
The option to make Files the default is only available in the sideload version of Files https://files.comunity/download/stable.
