### ISSUE TITLE
How to change themes

### ISSUE THREAD

**Issue by Someone-Somwhere** [files-community/Files#8528]
I was looking at some of the themes which are built into the app. I liked the theme called "Discord" but I don't like the purple color. I clicked on the "I" and clicked on the "Open the themes folder" but there is no files in the folder (I also clicked on the option to view hidden files.) 
How do I edit the color of the theme?

**Comment by gave92** [comment]
You can find all bundled themes here: https://github.com/files-community/Custom-themes/tree/main/Themes

**Comment by Someone-Somwhere** [comment]
@gave

> You can find all bundled themes here: https://github.com/files-community/Custom-themes/tree/main/Themes

Thanks
