### ISSUE TITLE
Custom theme not showing 

### ISSUE THREAD

**Issue by Someone-Somwhere** [files-community/Files#8529]
### Description

I edited the built-in discord theme. I then moved it into the themes folder but it didn't come up in the settings I have tried relaunching the app but it doesn't help 

### Expected behavior

The option to enable it doesn't appear. 

### Files Version

Version: 2.1.15.0 OS Version: 10.0.19044.1566

### Windows Version

Windows 10 pro version 21H2 OS build 19044.1566 Windows Feature Experience Pack 120.2212.4170.0

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/71657811/155897577-68516fb0-1595-4c5a-89cf-f3df24c69c1d.png)

**Comment by Josh-65** [comment]
- Did you give the theme a diffrent name. 
- Have you make sure it in the correct folder. you can use the (i) icon to open it.

**Comment by Someone-Somwhere** [comment]
Yes, I called it a different name and I put it in the folder that the (i) icon leads to.
![image](https://user-images.githubusercontent.com/71657811/156025178-20cdddce-0362-47d6-b26b-2f196d8d16c6.png)

**Comment by Josh-65** [comment]
xaml should be the extention not axml

**Comment by Someone-Somwhere** [comment]
> xaml should be the extention not axml

Thanks
