### ISSUE TITLE
Bundles keep resetting

### ISSUE THREAD

**Issue by DutchEclipse** [files-community/Files#8530]
### Description

Every time you create a couple of bundles with folders within them, after a while they disappear without any indication of why. 

### Steps To Reproduce

Go to the home section of Files
Create a bundle
Add a couple of folders to the bundle
Wait for around half an hour to an hour
The bundle got deleted/reset

### Expected behavior

The bundle stays without getting deleted

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.493

### Windows Version

Windows 11 21H2 22000.493

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8149570/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8149571/debug_fulltrust.log)

**Comment by Noisemagician** [comment]
I have the same problem, a temp workaround is to save and import it when it happens.

**Comment by yaichenbaum** [comment]
We don't have plans to fix this sepcific bug since we're working on merging the bundles feature with the tabs feature.
