### ISSUE TITLE
View like folder sizes

### ISSUE THREAD

**Issue by davidbuckleyni** [files-community/Files#8531]
I love what u trying to do here a good feature to add would be a folder level folder sizes like how folder sizes does it

**Comment by yaichenbaum** [comment]
You can view folder sizes by turning on the experimental option in the settings dialog.
![image](https://user-images.githubusercontent.com/39923744/155923239-974202dc-1d65-44fe-a96b-3183a6bac66e.png)

**Comment by davidbuckleyni** [comment]
Sweet
