### ISSUE TITLE
v2.1.15 removed ability to set as default file manager

### ISSUE THREAD

**Issue by neilbalch** [files-community/Files#8533]
### What's the Problem?

I've just noticed that the [latest release has removed](https://github.com/files-community/Files/releases/tag/v2.1.15) the ability to set Files as the default file manager. This is, perhaps, the single most important feature of the app which would enable me to daily drive it on my computer.

### Solution/Idea

However, I didn't see any significant _(or easily accessible)_ discussion of why this was done. Could someone clarify?

### Alternatives

[The associated PR](https://github.com/files-community/Files/pull/8474) appears to have not been filled out with any relevant information. Is it because of [this (_unlinked_) issue](https://github.com/files-community/Files/issues/7626)? [@gh0sti](https://github.com/gh0sti) also [commented on the PR](https://github.com/files-community/Files/pull/8474#issuecomment-1049451547) with a question similar to mine, but it appears no one noticed their question.

### Priorities

_**I'm not sure how to fill out this section**_

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

v2.1.15

### Windows Version

Windows 10 21H2 Build 19044.1566

**Comment by yaichenbaum** [comment]
The option to make Files the default is available on the sideload version https://files.community/download/stable

**Comment by neilbalch** [comment]
But why was it removed from the store-packaged version?

**Comment by xPoP** [comment]
It seems strange to me that there wouldn't be a check done during uninstall that resets this, but I'm not sure what that would take to implement. Removing it in the store-packaged version seems sensical until they can figure that out, I imagine.

**Comment by yaichenbaum** [comment]
> It seems strange to me that there wouldn't be a check done during uninstall that resets this, but I'm not sure what that would take to implement. Removing it in the store-packaged version seems sensical until they can figure that out, I imagine.

There is a way but it requires special permission from Microsoft and we're still trying to get it.
