### ISSUE TITLE
Bug: Files doesn't drag and drop in sequential order into mpv

### ISSUE THREAD

**Issue by dahjin** [files-community/Files#8534]
### Description

dragging and dropping videos from files into Mpv to create a play list, the expected behavior is for it to sequentially load from 1-24 episodes. instead it does them in odd pairs of 10, 8, 12, 7, 6, 9, 11, 13.

The default behavior in File explorer loads from 1-24.

### Steps To Reproduce

1. Drag and drop from files to mpv
2. it loads the files in odd pairs not in order.

### Expected behavior

Files to be "dropped" in sequential order.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.493

### Windows Version

Windows 11 21H2 22000.493

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8151396/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8151397/debug.log)

**Comment by yaira2** [comment]
@dahjin thank you for reporting this issue, we were able to repro it on our side as well.

**Comment by Qin-shihuang** [comment]
@yaira2  I'm trying to solve this issue and #15308. I have observed Explorer's behavior. It sorts the files according to the current sorting option, opens the currently selected file and the files below it, then opens the files above. Should we keep the behavior consistent with Explorer or open the files sorted by name?

**Comment by yaira2** [comment]
I would refer to @dahjin on this, but otherwise, the behavior in File Explorer sounds good to me.

**Comment by dahjin** [comment]
Explorer's behavior is what i figured would happen when i used files, So that sounds good to me as well.

**Comment by yaira2** [comment]
@dahjin thank you for your patience on this, the fix will be included in the next update.
