### ISSUE TITLE
Favorites section on application start

### ISSUE THREAD

**Issue by vertigobo** [files-community/Files#8535]
### Description

In the startup settings I selected "Continue where you left off". When I start the application the favorites section does not show the items present in it. I point out the opening status of the section (the arrow). See attached screenshot.

### Expected behavior

The favorites section should display its items.

### Files Version

Version: 2.1.15.0 

### Windows Version

OS Version: 10.0.19044.1526

### Relevant Assets/Logs

![Files - Screenshot 2022-02-28 145519](https://user-images.githubusercontent.com/3796904/155995408-bb3543c7-2c87-46a3-ada6-c0f77bd0e34e.png)

**Comment by gave92** [comment]
Tracked in #8506 6469
