### ISSUE TITLE
Randomly opens C://

### ISSUE THREAD

**Issue by DevanshR1123** [files-community/Files#8536]
### Description

It randomly opens the C drive when opening a folder, without any out of the ordinary actions.

### Expected behavior

Open the folder that's being opened.

### Files Version

2.1.15.0

### Windows Version

Edition	Windows 10 Pro Version	21H2 19044.1566 

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8156861/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8156862/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
@DevanshR1123 can you upload a screen recording?
