### ISSUE TITLE
Unable to set Files as default File Explorer - Windows 11

### ISSUE THREAD

**Issue by brendonmconnett** [files-community/Files#8537]
### Description

Hello,

First of all, I LOVE the look of your file explore app for Windows. It's so clean.

Secondly, I was attempting to follow your instructions to set my default file explorer to the Files app (through the experimental tab), but there is no option to set it as default.

Any thoughts?

### Expected behavior

I expected there to be an option for me to click on that tells Windows to default to the Files app when opening files.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.527

### Windows Version

Windows 11 Pro 21H2

### Relevant Assets/Logs

![Screenshot 2022-02-28 133845](https://user-images.githubusercontent.com/100497079/156062986-36dcc2ca-d57a-4e4f-acd7-6774317e54c4.jpg)

**Comment by yaichenbaum** [comment]
This option is only available in the sideload version of Files.
