### ISSUE TITLE
The "set as default file manager is missing"

### ISSUE THREAD

**Issue by Radical4ever** [files-community/Files#8539]
### Description

trying to enable the 'set as default file manager' appears missing at the experimental window. i dont know its just me or there are more people with the same issue.

### Expected behavior

that i can actually set it as default file manager

### Files Version

Versión: 2.1.15.0 OS Version: 10.0.22000.527

### Windows Version

Windows 11 Pro N 21H2 22000.527 (using the insider channel)

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8158197/debug.log)

**Comment by RifsxD** [comment]
Its not availabe in the windows store version, install the app from the github release.
