### ISSUE TITLE
title bar is too large

### ISSUE THREAD

**Issue by Huihui-Mao** [files-community/Files#8542]
### What's the Problem?

title bar is too large

### Solution/Idea

Set an option to set the title bar width

### Alternatives

Set the default title bar width smaller

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

版本: 2.1.15.0 OS Version: 10.0.19043.1526

### Windows Version

Windows 10 21H1 19043.1526

**Comment by yaichenbaum** [comment]
@Huihui-Mao can you provide some more context on the issue?

**Comment by Huihui-Mao** [comment]
@yair100  As you can see, the red box part is kind of wider, I want to set the part narrower, thank you for your reply!
![image](https://user-images.githubusercontent.com/42145787/156274434-76f1c18d-d31f-4d3c-8cd4-84087c0b6f4f.png)

**Comment by yaichenbaum** [comment]
@Huihui-Mao can you try resizing it?

**Comment by Huihui-Mao** [comment]
@yair100 Yes, I can resize it, but when I open another folder, and go back to this folder, the size is changed to the default, which is pretty annoying, I mean the size can not be set by the user and fixed, it always keeps the default width unless I stay in the folder. thank you anymore!

**Comment by yaichenbaum** [comment]
We're tracking a similar issue in #6448
