### ISSUE TITLE
turn off filenames cutoff

### ISSUE THREAD

**Issue by zzaria** [files-community/Files#8544]
### What's the Problem?

in icon layout the filenames are cut off and only first few characters are shown

### Solution/Idea

show full filename like in default explorer
![image](https://user-images.githubusercontent.com/33037196/156244410-149cbad9-9c96-410b-a91c-3154f3bed717.png)

### Alternatives

currently it is like ![image](https://user-images.githubusercontent.com/33037196/156244300-e6ee09a5-0f83-4e07-b127-0690e48b3a55.png)

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.1.15.0

### Windows Version
OS Version: 10.0.19043.1526

**Comment by yaichenbaum** [comment]
Merging with #1033
