### ISSUE TITLE
Please add this GIF to README.md

### ISSUE THREAD

**Issue by xmha97** [files-community/Files#8546]
Please add this GIF to README.md

![ezgif-1-c2e981ce51](https://user-images.githubusercontent.com/23485114/156282055-15cbb53f-05e6-4951-ae69-2ca7e6f01170.gif)
https://user-images.githubusercontent.com/23485114/156282055-15cbb53f-05e6-4951-ae69-2ca7e6f01170.gif

Reference:
https://www.youtube.com/watch?v=yif6fhAajog

**Comment by yaichenbaum** [comment]
I played around with this and it looks like the transparency doesn't work too well in the gif format.

**Comment by xmha97** [comment]
Why do you want to create a transparent GIF?

**Comment by yaichenbaum** [comment]
The mica background has transparency
