### ISSUE TITLE
Open in Issue

### ISSUE THREAD

**Issue by heewoonkim2020** [files-community/Files#8548]
### Description

Rebooting fixes the issue, and the issue is: You cannot use the context menu item "Open in Windows Terminal". I have Windows 11 Home and Files installed from the Microsoft Store. Once this bug happens, the "Open in Windows Terminal" is "Open in". Personally, I have spent minutes trying to fix the terminal profiles. But the thing is, Settings -> Preferences -> Terminal Applications -> dropdown has no content. For example, the dropdown next to "Terminal applications" is blank and there are no items to select from.

Please help!

### Steps To Reproduce

I'm not kind of sure.
Interacting with the app a lot and using it for a while it naturally happens.

### Expected behavior

When I right-clicked somewhere, I expected to see "Open in Windows Terminal".

### Files Version

Version 2.1.15.0

### Windows Version

OS Build: Windows 11 21H2 22000.527 / Windows Feature Experience Pack 1000.22000.527.0

### Relevant Assets/Logs

This was too long so I couldnt upload but here it is:
(I used OneDrive)
Password is files (if there is one)
debug_log : https://1drv.ms/t/s!AoR6Pt7sgZKbhJhRrhE5Op1o4raFPA?e=rOJHfR
debug_fulltrust_log : https://1drv.ms/t/s!AoR6Pt7sgZKbhJhSuUuvUldHSdiHNw?e=dGF2Ps

**Comment by heewoonkim2020** [comment]
Some personal information may be included in the logs (such as the username 'heewo'), please ignore that and fix this issue fast.

**Comment by fybedev** [comment]
@yair100

**Comment by yaichenbaum** [comment]
Merging with #8100
