### ISSUE TITLE
Some descriptions translated into other languages when simplified Chinese is set

### ISSUE THREAD

**Issue by lovexxx** [files-community/Files#8550]
### Description

When you set simplified Chinese as the app language, there will be some descriptions shown in other languages (mostly Japanese). Like:
1. in Settings - Experimental: フォルダーサイズの計算はリソースを消費するため、CPU使用率が上昇する可能性が Its Chinese should be: 计算文件夹大小会消耗资源并可能增加 CPU 使用率
2. in Settings - Preferences - Files and folders: Show dot files. I don't know what it means😂
3. in Settings - About: the "copy" button shows コピー in Japanese. In Chinese, it's 复制
4. "New" button in the main interface is shown with 新規 in Japanese. In Chinese, it's 新建. When clicked, the popup menu presents フォルダー, which is 文件夹 in Chinese.
5. when you press Alt + S, the popup menu reads すべて選択(全选) and 選択をクリア(取消选择)
6. the popup menu of the "..." button in the top right corner gives 新しいウインドウ (新窗口) and 開く CMD (打开CMD).
7. when you right click a file or folder, the context menu reads 場所のコピー, which is 复制地址
8. when you right click an item in the sidebar, the context menu reads 新しいウインドウで開く(在新窗口中打开) and プロパティ(属性)
9. the descriptions of some icons. 切り取り(cut, 剪切) コピー(copy, 复制) 名前の変更(rename, 重命名) 共有(share, 共享) 削除(delete, 删除)
There might be some places I don't find out.

### Expected behavior

Already described in the "Description" part, with the correct Chinese translation in parentheses

### Files Version

Version: 2.1.15.0 OS Version: 10.0.18363.1500

### Windows Version

Windows 10, version 1909 (OS Build 18363.1500)

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/28099434/156330358-51592aa7-d07d-4839-8c89-4340cff0e889.png)
![image](https://user-images.githubusercontent.com/28099434/156330469-34c11cf9-1794-4f60-845f-e69a8a52991d.png)
![image](https://user-images.githubusercontent.com/28099434/156330524-075401b8-b3f8-4d4f-870d-1c784146d877.png)
![image](https://user-images.githubusercontent.com/28099434/156332480-557c23b3-6ff6-4ba5-93ba-ce85ec3680e0.png)
![image](https://user-images.githubusercontent.com/28099434/156330768-d73784c3-a2b6-4ef2-a472-00979d8f2874.png)
![image](https://user-images.githubusercontent.com/28099434/156331656-2a3d39ec-7601-45dc-a1f2-77fbf9c8c277.png)
![image](https://user-images.githubusercontent.com/28099434/156332048-d4b4a347-1de8-4f4b-b7e1-ad7a2001295e.png)
![image](https://user-images.githubusercontent.com/28099434/156332143-a785ad6b-78da-4363-be88-e3c8b9508c89.png)
![image](https://user-images.githubusercontent.com/28099434/156332308-822cc855-5f63-4843-8d73-4ce909d5a116.png)

**Comment by yaichenbaum** [comment]
@lovexxx this happens when translations are out of date, translations are handled by users so you can expect this to be resolved in a future update.
