### ISSUE TITLE
Box - Cloud Drive

### ISSUE THREAD

**Issue by dany20mh** [files-community/Files#8551]
### Description

I use Box Drive and the folder shows under the Cloud Drives.

When I click on that to check the content, it shows the content but keeps refreshing the page every 5 seconds or so making it unusable. 

### Steps To Reproduce

1. Open Files
2. Go to Cloud Drive
3. Select Box from there
4. Page keep refreshing every 5 seconds or so

### Expected behavior

Just show the content like any other folder or drives

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.493

### Windows Version

Windows 11 21H2 2200.493

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8169854/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8169855/debug_fulltrust.log)

**Comment by gave92** [comment]
#7428
