### ISSUE TITLE
Updating Drive Sizes

### ISSUE THREAD

**Issue by hddnby** [files-community/Files#8552]
### Description

After deleting large files from a drive, I clicked HOME and noticed that the size of the drive has not updated visually. So, if say my drive was 100 out of 128 GB, it would still show the same info even after deleting 50 GB.

### Expected behavior

I expected the bar and size info of the drives to update after clicking HOME or going back to HOME.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.19044.1526

### Windows Version

Windows 10 21H2 19044.1526

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8169882/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8169883/debug_fulltrust.log)

**Comment by gave92** [comment]
#2242
