### ISSUE TITLE
It's taking so long

### ISSUE THREAD

**Issue by idknameso69** [files-community/Files#8553]
So as of now its been 46 minutes in Visual Studio and I don't know if its done already or if I should let it be. As of now I'm letting it do its thing because it's the only thing that seems logical

**Comment by idknameso69** [comment]
![image](https://user-images.githubusercontent.com/95858495/156375656-7ea0aee7-56df-4e8d-b844-b2d01a8186e7.png)

**Comment by yaichenbaum** [comment]
@idknameso69 can you try stopping the debugger and deploying again?
