### ISSUE TITLE
favorites do not update on other windows

### ISSUE THREAD

**Issue by modest-marmot** [files-community/Files#8556]
### Description

when i add a favorite in one window it does not update the favorite lists in other windows. new list only propagates to windows created after the favorite is added.

### Steps To Reproduce

1. create (2) new windows
2. pin a favorite to one of the windows
3. note that favorite list on second window does not update
4. open 3rd window - favorite now shows up properly

### Expected behavior

favorites update in all windows when added in another.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.19044.1526

### Windows Version

Edition	Windows 10 Pro Version	21H2 Installed on	‎12/‎25/‎2020 OS build	19044.1526 Experience	Windows Feature Experience Pack 120.2212.4170.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8171765/debug.log)

**Comment by jiejasonliu** [comment]
Had a glance at this, problem is that new windows have their own `SidebarPinnedController` but we serialize favorites into `PinnedItems.json.` This won't be propagated to other windows. 

The most reasonable strategy I can think of is a `FileSystemWatcher` (or some other polling strategy) to track changes and force an update. But this seems to be an issue that could reoccur elsewhere so I'm not sure if an isolated patch would be a good idea.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #8712
