### ISSUE TITLE
Drag the file to open invalid/Cut operation invalid

### ISSUE THREAD

**Issue by Huihui-Mao** [files-community/Files#8559]
### What's the Problem?

1. I want to open a file by drag it to some software, but it can't open, most of the softwares support drag and open the files, so I hope  this problem could be solved. 
2. By the way, the cut file operations cannot be performed, no matter the shortcut or right-click, which is pretty strange.

### Solution/Idea

fix the problem of draging and open files, and fix the invalid cut operations.

### Alternatives

None

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

版本: 2.1.15.0 OS Version: 10.0.19043.1526

### Windows Version

Windows 10 21H1 19043.1526

**Comment by Josh-65** [comment]
- What file types are you draging to what program. 
- You will need to upload the logs files directly to github. You can get them in files settings > about > open log folder.

**Comment by Huihui-Mao** [comment]
1. for exampe, to drag a .xls file or a .dbf file to Microsoft Excel 2019, Excel acts like I didn't drag anything to it, and by the way, when I drag the file, there is a red forbidden Icon occured, please see the screenshot. 
![Snipaste_2022-03-03_15-32-24](https://user-images.githubusercontent.com/42145787/156517607-ac7eab51-324d-4223-bc7e-34079b4ebb84.jpg)
2. I'm sorry, but I didn't find the position to upload the logs files, because I'm a newcomer.

**Comment by Josh-65** [comment]
Have you tried draging it around the window a bit before going to excel it sometime is slow and it beeing worked on. Files can't be moved/copied into the same folder it's in that why it denied in your screenshot.

**Comment by Josh-65** [comment]
There has been some work recently on this in the preview version https://files.community/download/preview. Have you tried using that?
