### ISSUE TITLE
Make default file manager 

### ISSUE THREAD

**Issue by tanmoypaul007** [files-community/Files#8560]
### Description

Make default file manager option is not showing

### Expected behavior

I want the solution 

### Files Version

version 2.1.15.0

### Windows Version

Edition	Windows 11 Home Single Language Version	21H2 Installed on	‎28-‎02-‎2022 OS build	22000.527 Experience	Windows Feature Experience Pack 1000.22000.527.0

### Relevant Assets/Logs

![2022-03-03](https://user-images.githubusercontent.com/78530006/156501200-6376f9f6-b65e-46de-bcba-2952714f47fc.png)

**Comment by yaichenbaum** [comment]
Please see the [docs](https://files.community/docs/configuring/replace-file-explorer#:~:text=This%20is%20currently%20only%20available%20for%20the%20sideload%20version%20of%20Files%20and%20is%20not%20supported%20in%20the%20store%20version.).
