### ISSUE TITLE
application  getting closed when I open a folder in new tab and I click on secondary mouse button to go back.

### ISSUE THREAD

**Issue by messenger-1012** [files-community/Files#8561]
### Description

1:
![image](https://user-images.githubusercontent.com/27795050/156512685-178098de-937b-4db4-911e-18cc48f5b3d4.png)
2 : go to the new tab
3 :click on secondary mouse button (back)
![image](https://user-images.githubusercontent.com/27795050/156512986-a34df46f-7725-4678-a79e-36a4bda66420.png)

### Steps To Reproduce

same as in discription

### Expected behavior

close the new tab and go back to the previous tab from where the new tab was called

### Files Version

Version: 2.1.15.0 OS Version: 10.0.19044.1526

### Windows Version

Edition	Windows 10 Home Single Language Version	21H2 Installed on	‎23-‎01-‎2022 OS build	19044.1526 Experience	Windows Feature Experience Pack 120.2212.4170.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8175638/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8175639/debug_fulltrust.log)

**Comment by Josh-65** [comment]
Merging with #8409
