### ISSUE TITLE
'设置默认资源管理器'选项消失

### ISSUE THREAD

**Issue by GrahLnn** [files-community/Files#8562]
### Description

实验性选项内无设为默认资源管理器开关

### Expected behavior

可以设为默认资源管理器

### Files Version

版本: 2.1.15.0 OS Version: 10.0.22000.527

### Windows Version

Windows 11 21H2 22000.527

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/67181515/156546224-9512a3e4-129d-48fc-a7a8-184b8be39239.png)
[debug.log](https://github.com/files-community/Files/files/8176999/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8177000/debug_fulltrust.log)

**Comment by a95788** [comment]
> [https://github.com/files-community/Files/pull/8474](url) It was removed from the latest MS Store version. Use the sideload version to get the feature back.

我很明白在Github上用英语回答问题并没有任何问题，但是对于国人的话，我觉得还是用中文回应会比较好。
无意冒犯，感觉像是两个中国人在讲着不同的语言
