### ISSUE TITLE
Bundles dissapear on startup

### ISSUE THREAD

**Issue by EvilCheez** [files-community/Files#8563]
### Description

I have set up some folders as bundles (amazing feature btw) but everytime I start files the bundles are not there and I have to import them. It's a minor inconvinience but I thought I'd report it. 

### Expected behavior

Not having to import bundles everytime you open the app

### Files Version

Version: 2.1.15.0 OS Version: 10.0.19043.1526

### Windows Version

10

### Relevant Assets/Logs

[debug_fulltrust.txt](https://github.com/files-community/Files/files/8177516/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/8177517/debug.txt)

**Comment by yaichenbaum** [comment]
Merging with #8530
