### ISSUE TITLE
Keeps asking "How do you want to open this app" for certain apps

### ISSUE THREAD

**Issue by AlbertM94** [files-community/Files#8564]
### Description

I recently noticed that when I set the default app to open .mp3 file to Foobar2000 (ver. 1.6.9), every time I open a .mp3 file, the window "how do you want to open this app" will appear, despite my clicking "always use this app to ..." every time, but when I set it to the Media Player that comes with Windows the prompt doesn't appear and opens directly. 
Originally I thought it was a windows issue, but after a random thought I switched back to original explorer and it opens fb2k directly without prompts. So this appears to be a Files issue. So far I only encounter it with fb2k, but because it is my go-to app for music, it is rather annoying. I hope you could figure out the cause of this and solve it.

### Steps To Reproduce

1. open any audio file that is associated with foobar2000
2. the window "how do you want to open this app" will appear
3. select foobar2000 and "always use this app to open..." option
4. open another audio file
5. the prompt comes again

### Expected behavior

Open the associated app (which in this case is foobar) directly without any prompts

### Files Version

2.1.15

### Windows Version

Windows 11 21H2 22000.493

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8177621/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8177622/debug.log)

**Comment by ElbowBaggins** [comment]
[I encountered what I think is the same behavior several months ago and worked around it.](https://github.com/files-community/Files/issues/2299#issuecomment-1003677095)

Unfortunately the workaround is extremely complicated and annoying. This is a limitation from Microsoft's side.

**Comment by yaichenbaum** [comment]
> [I encountered what I think is the same behavior several months ago and worked around it.](https://github.com/files-community/Files/issues/2299#issuecomment-1003677095)
> 
> Unfortunately the workaround is extremely complicated and annoying. This is a limitation from Microsoft's side.

Thanks for the detailed explanation.
