### ISSUE TITLE
add "press space buttton to preview"feature

### ISSUE THREAD

**Issue by a95788** [files-community/Files#8565]
### What's the Problem?

Hi Developer!
I'm Chinese user, i have installed Files 2.1.5.0.
English is not my mother language, so maybe can't describe what i want. but i will attach chinese description.

I'm macOS + WIndows user and very like a feature “press space button to preview” by macOS.
i have saw QuickLook GPL via “About” page, but i don't know how to enable this function
maybe i can use this function in future?

你好，开发者！
我是中国用户，我目前已经安装了 Files 2.1.5.0。

我是 macOS + WIndows 用户，非常喜欢 macOS 的“按空格键来预览”功能。
我通过关于页面看到了 QuickLook GPL，但我不知道如何启用此功能
也许我将来可以使用这个功能？ 

### Solution/Idea

add "press space buttton to preview"feature
增加按空格来预览的功能

### Alternatives

add "press space buttton to preview"feature
增加按空格来预览的功能

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.5.0

### Windows Version

Windows 11 1000.22000.493.0

**Comment by gave92** [comment]
Hi thanks for you interest in Files. You need to install the QuickLook program (e.g from the windows store), launch it and then restart Files. You should be able to trigger preview with Space.
