### ISSUE TITLE
file manager predefinito

### ISSUE THREAD

**Issue by Giovanni-89** [files-community/Files#8567]
### What's the Problem?

come mai avete tolto l'opzione per renderlo il file manager predefinito?

### Solution/Idea

ripristinatelo 

### Alternatives

non saprei

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
The option to make Files default is available in the sideload version.
