### ISSUE TITLE
Add support for new app picker in Windows 11

### ISSUE THREAD

**Issue by jolopapina** [files-community/Files#8568]
### Description

app picker crashes

### Steps To Reproduce

1. Open with
2. Choose other app
3. App picker crashes

### Expected behavior

New app picker should open without a crash

### Files Version

Version: 2.1.15.0

### Windows Version

Windows 11 22H2 22567.1

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8180442/debug.log)

[debug_fulltrust.log](https://github.com/files-community/Files/files/8180444/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
This issue should be resolved.
