### ISSUE TITLE
Files not Opening When internet is not connected

### ISSUE THREAD

**Issue by an0unym0us3** [files-community/Files#8569]
### Description

Files isn't opening when my pc is disconnected from the internet, or if pc is on airplane mode. But after turning off airplane mode and turning back on WIFI, the problem settles down and everything works fine. 

### Steps To Reproduce

1. Turn off Wi-Fi / disable internet connection / Turn on airplane mode
2.  Open files 

### Expected behavior

If you open files when you're not connected to any internet connections, files will not start and it looks like it refreshes the desktop but doesn't start even after doing so. 

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.527

### Windows Version

Windows 11 21H2 22000.527

### Relevant Assets/Logs

https://user-images.githubusercontent.com/100888141/156682932-9d0d51aa-e9cd-4fe6-b63a-9d14a8394957.mp4

**Comment by yaichenbaum** [comment]
@an0unym0us3 are you using the store version or sideload version?

**Comment by martymarty004** [comment]
I'm having the same issue, here's the information that I gathered:

Files Version: 2.1.24.0
OS Version: Windows 11 21H2 10.0.22000.556

Logs:
[debug_fulltrust.log](https://github.com/files-community/Files/files/8318295/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8318296/debug.log)


Errors found in Event Viewer:

```txt
Nome registro: Application
Origine:       Application Error
Data:          21/03/2022 19:23:27
ID evento:     1000
Categoria attività:(100)
Livello:       Errore
Parole chiave: Classico
Utente:        N/D
Computer:      DuckPC-2021
Descrizione:
Nome dell'applicazione che ha generato l'errore: sihost.exe, versione: 10.0.22000.1, timestamp: 0x5c7a6c09
Nome del modulo che ha generato l'errore: AppXDeploymentClient.dll, versione: 10.0.22000.469, timestamp: 0xe01e2319
Codice eccezione: 0xc0000005
Offset errore 0x0000000000043400
ID processo che ha generato l'errore: 0x386c
Ora di avvio dell'applicazione che ha generato l'errore: 0x01d83d2e1e4a48de
Percorso dell'applicazione che ha generato l'errore: C:\WINDOWS\system32\sihost.exe
Percorso del modulo che ha generato l'errore: C:\WINDOWS\system32\AppXDeploymentClient.dll
ID segnalazione: 1eaa96f8-c641-4b69-9e25-e140cfdde7e9
Nome completo pacchetto che ha generato l'errore: 
ID applicazione relativo al pacchetto che ha generato l'errore: 
XML evento:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-03-21T18:23:27.1127700Z" />
    <EventRecordID>40880</EventRecordID>
    <Correlation />
    <Execution ProcessID="7164" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DuckPC-2021</Computer>
    <Security />
  </System>
  <EventData>
    <Data>sihost.exe</Data>
    <Data>10.0.22000.1</Data>
    <Data>5c7a6c09</Data>
    <Data>AppXDeploymentClient.dll</Data>
    <Data>10.0.22000.469</Data>
    <Data>e01e2319</Data>
    <Data>c0000005</Data>
    <Data>0000000000043400</Data>
    <Data>386c</Data>
    <Data>01d83d2e1e4a48de</Data>
    <Data>C:\WINDOWS\system32\sihost.exe</Data>
    <Data>C:\WINDOWS\system32\AppXDeploymentClient.dll</Data>
    <Data>1eaa96f8-c641-4b69-9e25-e140cfdde7e9</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>
```

**Comment by martymarty004** [comment]
@yair100 if you need more information, just let me know.

This is not much of a problem on my desktop, but it is very annoying on my laptop, which I use most of the time when I'm not home.

**Comment by martymarty004** [comment]
@gave92 after you helped me manually fix the issue #8749 this problem has changed.

Now, when I try to open Files without an internet connection, it will not crash Explorer, but will show the following error instead:

![Screenshot_2](https://user-images.githubusercontent.com/61474670/160256026-a9b1e5f2-8945-43dc-9cb1-52270226076e.png)


At this point, I think that this issue is also related to having the username with a space in between just like #8759 


Here's all the usual logs from Files:

Versione 2.1.30.0
OS Version: 10.0.22000.556
User folder: `C:\Users\Martino Papero`

[debug.log](https://github.com/files-community/Files/files/8356295/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8356294/debug_fulltrust.log)




I discovered that my friend also has the same issue, but he didn't have any problem like #8749 
His Explorer **does** crash

Here's his information:

Version: 2.1.24.0
OS Version: 10.0.22000.556
User folder: `C:\Users\hexev` (He has more than one user on his computer, this is the main account)

[debug.log](https://github.com/files-community/Files/files/8356299/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8356300/debug_fulltrust.log)

**Comment by gave92** [comment]
I'm not sure about this one. Does Files open correctly in the following cases?

| Case | Internet on | Internet off |
| :---------- | :------- |:------- |
| if you launch "Files" from the Start menu | ? | ? |
| if you type "files" in a cmd prompt | ? | ? |
| double-clicking on some folder on the desktop (if set as default) | ? | ? |

Also, does the file shown in the error exist at that location?

**Comment by martymarty004** [comment]
| Case | Internet on | Internet off |
| --------------- | --------------- | --------------- |
| if you launch "Files" from the Start menu| OK | Nothing happens and the app will not launch until I restart the PC |
| if you type "files" in a cmd prompt | OK | The following errors appear in CMD and PowerShell |
| double-clicking on some folder on the desktop (if set as default) | OK | The previous error appears |

![image](https://user-images.githubusercontent.com/61474670/160258302-fc401b4d-b89d-4d4f-9f0c-a8518e5b21b4.png)
![Screenshot_3](https://user-images.githubusercontent.com/61474670/160258303-53941267-33fd-41b3-98ce-5a8f47ad899b.png)

`C:\Users\Martino Papero\AppData\Local\Microsoft\WindowsApps\files.exe` exists, but when I try to open it without an internet connection nothing happens, and the app will not launch until i restart the machine (after I restore the connection it will work if I open anything with explorer)

**Comment by martymarty004** [comment]
I asked my friend to check the same conditions. (He's running the release 2.1.24)

| Case | Internet on | Internet off |
| --------------- | --------------- | --------------- |
| if you launch "Files" from the Start menu| OK | Explorer immediately crashes and restarts |
| if you type "files" in a cmd prompt | OK |   The same errors appear in CMD and PowerShell |
| double-clicking on some folder on the desktop (if set as default) | OK | An error box appears and disappears instantly, I can't read what it says |

**Comment by allen404** [comment]
I can confirm this bug happens too when the internet connection is set to metered

Files Version: 2.1.34.0
OS Version: Windows 11 21H2 10.0.22000.593

Here's the log:
[debug.log](https://github.com/files-community/Files/files/8389725/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8389726/debug_fulltrust.log)

Event Viewer:
```
Faulting application name: FilesLauncher.exe, version: 0.0.0.0, time stamp: 0x6243683b
Faulting module name: ntdll.dll, version: 10.0.22000.527, time stamp: 0x931cda92
Exception code: 0xc000000d
Fault offset: 0x00000000001243a0
Faulting process id: 0x2b44
Faulting application start time: 0x01d845011f30d0d4
Faulting application path: C:\Users\Allen\AppData\Local\Files\FilesLauncher.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 10457f5f-c485-4890-adc1-e303039f4760
Faulting package full name: 
Faulting package-relative application ID: 
```
And it shows this menu when launching on metered connection, with files set as default:
![image](https://user-images.githubusercontent.com/20906721/161063689-0d35d5dd-a407-4c9d-9da5-ed612ca3c9a1.png)
![image](https://user-images.githubusercontent.com/20906721/161064754-98b6a5fd-58de-4d3a-a198-d67811a58896.png)

**Comment by yaichenbaum** [comment]
The sideload version requires internet access for auto updates. We'll try to work around this but it's the expected behavior for now.

**Comment by yaichenbaum** [comment]
> Is it confirmed that it's auto update? I don't see why it would prevent the app from opening at all and the sideload app opens just fine on windows 10 without internet 🤔

Yeah, app installer checks for updates on app launch. I'm not sure why it's only an issue on some devices but there is a way we can work around it.
