### ISSUE TITLE
History Sidebar

### ISSUE THREAD

**Issue by servebeer** [files-community/Files#8571]
### What's the Problem?

No problem, a request

### Solution/Idea

It would be nice to have a History option in the sidebar area. Having the option to turn it on and off would be nice too. Basically it would contain a number (configurable) of recent locations (both local and remote).

### Alternatives

n/a

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
Thank you for your feedback, we don't have plans to implement this but we're tracking an issue to add a history page.
