### ISSUE TITLE
No "in use" notification when trying to move a file

### ISSUE THREAD

**Issue by deathgrape** [files-community/Files#8572]
### Description

When trying to move a file that is open to a new directory, nothing pops up to inform you that Files can't do that because the file is in use.

This is in contrast to trying to delete a file that is open, when Files will tell you the file is in use.

### Steps To Reproduce

1. Have a file in a folder (I have been using the Downloads folder)
2. Open that file and keep it open
3. Try to drag the file to a new folder (eg Documents, Desktop folder in Files)
4. The file move will not happen BUT nothing will tell you WHY it didn't happen (eg because the file is currently in use)

### Expected behavior

At step 4, the file move will not happen and a popup will come up saying "the file is in use", like what happens with deleting a file.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.527

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎2/‎18/‎2022 OS build	22000.527 Experience	Windows Feature Experience Pack 1000.22000.527.0

### Relevant Assets/Logs

No log because no error code

**Comment by Josh-65** [comment]
You will need to upload the logs files directly to github. You can get them in files settings > about > open log folder.

**Comment by deathgrape** [comment]
Yes, in Windows default File Explorer if I try to do this, I get an error dialog saying the file is in use.

[debug.log](https://github.com/files-community/Files/files/8193274/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8193275/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #8809
