### ISSUE TITLE
Acknowledge tag info in .DS_Store file

### ISSUE THREAD

**Issue by mqliang** [files-community/Files#8573]
### What's the Problem?

Mac store tag information in a .DS_Store. When copy files from Mac to Windows, I don't want the tag information be lost.

### Solution/Idea

[Files](https://github.com/files-community/Files) app parse the  .DS_Store file in the folder, extract the tag info, and store to FIles's own database. Probably add a button, if there is a .DS_Store file, user can click the button to load tag info, otherwise the button is disabled. 

It's OK that only support Mac's default tag.

### Alternatives

Provide a script that  extract the tag info from .DS_Store, and store to FIles's own database.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by gave92** [comment]
Hi, are you sure the ds_store contains the tag? I'm aware of it containing only stuff like folder icon and layout.
Could you post a sample of a ds_store file?

**Comment by mqliang** [comment]
Sorry my bad. I tried to verify, it turns out adding/removing a tag will not change ds_store, which means the tag info is stored somewhere else.

Close this.

**Comment by gave92** [comment]
No problem, tags on Mac os are stored within the files themselves as extended attributes. Moving files to a different filesystem e.g Windows drive or even FAT32 USB key will loose tag info.
