### ISSUE TITLE
"Grant permission" dialog box appears if the c: drive is hidden

### ISSUE THREAD

**Issue by JarvisDigital** [files-community/Files#8574]
### Description

If you hide the C: drive where Windows is installed, either through the Group Editor Policy or through the Registry, then every time you open Files, the "Grant Permissions" dialog box comes up, even though permission has already been granted.

If you make C drive visible again, this problem disappears.

Why do I need to hide C drive anyway? In our company we make our PCs as idiot-proof as possible. I believe a lot of other enterprises do this as well. Part of it is making C drive hidden in Explorer (while still accessible from the URL bar).

How to hide C: drive: https://www.windowscentral.com/how-hide-entire-drive-prying-eyes-windows-10

### Steps To Reproduce

1. Hide C: drive using either the GPO or Registry method in this link: https://www.windowscentral.com/how-hide-entire-drive-prying-eyes-windows-10
2. Open Files

### Expected behavior

When opening Files even after hiding C drive, the "Grant Permissions" dialog box should not pop up.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.527

### Windows Version

Windows 11 21H2 22000.194

### Relevant Assets/Logs

![Files](https://user-images.githubusercontent.com/100966446/156834452-37b27cda-4602-4546-9f37-5cb6759742c5.png)

**Comment by gave92** [comment]
Ah yes, we use drive C being accessible to test whether the user granted the filesystem permission.

**Comment by gave92** [comment]
Funny though, #8279 tells a different sorry.

**Comment by gave92** [comment]
Funny though, #8279 tells a different sorry. @JarvisDigital could you post the app's log files?

**Comment by Josh-65** [comment]
I presume their hiding it for everyone on the system using the registry. My issue was disabling accses to one account on my system whilest not hiding it.

**Comment by JarvisDigital** [comment]
> I presume their hiding it for everyone on the system using the registry. My issue was disabling accses to one account on my system whilest not hiding it.

Yes you're right. I'm hiding it using the registry while still making it accessible (helpful for admins). I'm sharing the log file soon

**Comment by JarvisDigital** [comment]
Alternatively, if users can hide specific drives only in Files (e.g. C: drive is invisible in Files only, but visible in Explorer and elsewhere) that would solve this particular use case as well.

This way, the C: drive is hidden from regular users who use Files, but accessible via Windows Explorer and hence the "Grant Permission" dialog box issue is also solved.

**Comment by JarvisDigital** [comment]
> Funny though, #8279 tells a different story. @JarvisDigital could you post the app's log files?

Here are the log files
[debug.log](https://github.com/files-community/Files/files/8229532/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8229533/debug_fulltrust.log)

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
