### ISSUE TITLE
Stop favorites from disappearing when drive is not mounted

### ISSUE THREAD

**Issue by fabian-st** [files-community/Files#8575]
### What's the Problem?

When a favorite folder (e.g. WSL location) isn't available, the icon is removed.

### Solution/Idea

Don't remove non-available favorites from the sidebar or just temporarily hide them

### Alternatives

None

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by gave92** [comment]
Merging with#6860
