### ISSUE TITLE
Keybinds

### ISSUE THREAD

**Issue by jaikomodo** [files-community/Files#8576]
### What's the Problem?

Some of the key binds are kind of awkward. For example, the "new pane" and "close pane" key binds are wildly different.

### Solution/Idea

It would be nice to customize the key binds associated with certain actions. Referring back to the example, I would switch the key binds to the same one to create a toggle situation or switch the "new pane" key bind to alt+shift+t (since ctrl+shift+t already reopens a closed tab) and the "close pane" one to alt+shift+w (to match the alt+shift category of key bind).

### Alternatives

If it wouldn't be possible to custom make key binds, it would still be nice to have potential options to choose from to ensure ease of access and customizability.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to easily customize and memorize different key binds associated with different actions | Must |

### Files Version

Version: 2.1.15.0

### Windows Version

Windows 10

**Comment by gave92** [comment]
Merging with #1660

**Comment by yaira2** [comment]
@jaikomodo This feature will be included in the next release. Please see #9559 for more details.
