### ISSUE TITLE
Change the Default Windows File Explorer to Files

### ISSUE THREAD

**Issue by hayden-trvn** [files-community/Files#8577]
### What's the Problem?

Version: 2.1.15.0 has lost the ability to make Files as Default File Manager. Please bring it back or show us where does it hide?
Thanks

### Solution/Idea

lease bring it back or show us where does it hide?
Thanks

### Alternatives

or show us where does it hide?

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.527

**Comment by CapoFantasma97** [comment]
You made a duplicate issue. Also, no it's still there? [As per the documentation](https://files.community/docs/configuring/replace-file-explorer), with the sideload version of the app, go into Settings>Experimental tab.

**Comment by BloodLegend** [comment]
> You made a duplicate issue. Also, no it's still there? [As per the documentation](https://files.community/docs/configuring/replace-file-explorer), with the sideload version of the app, go into Settings>Experimental tab.

![image](https://user-images.githubusercontent.com/84155894/156889362-86033588-9a57-4b1b-94d2-a9cc42dd70dd.png)
There's no such option
