### ISSUE TITLE
Change the Default Windows File Explorer to Files

### ISSUE THREAD

**Issue by hayden-trvn** [files-community/Files#8578]
### What's the Problem?

Version: 2.1.15.0 has lost the ability to make Files as Default File Manager. Please bring it back or show us where does it hide?
Thanks

### Solution/Idea

lease bring it back or show us where does it hide?
Thanks

### Alternatives

or show us where does it hide?

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.1.15.0 / OS Version: 10.0.22000.527

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎3/‎5/‎2022 OS build	22000.527 Experience	Windows Feature Experience Pack 1000.22000.527.0

**Comment by gave92** [comment]
Since 2.1.15 only the sideload version cab be set as default. This feature was removed from the Store version at Microsoft request.
