### ISSUE TITLE
Wrong translation of the deleted folder popup title in [it-IT]

### ISSUE THREAD

**Issue by CapoFantasma97** [files-community/Files#8579]
### Description

Using the Documents link in the Libraries section causes the prompt “Did you delete this folder” to appear systematically.
The folder however works correctly, once the popup is dismissed. It also does not appear when opening the Documents folder through other means (example: from the Favourites).
This only happens with the Documents folder, the Music and Video folders in the Libraries section do not have this issue.

![immagine](https://user-images.githubusercontent.com/9368910/156889508-0fac1c52-ab9e-4bc3-a5ff-52c1bafdfe56.png)

### Steps To Reproduce

1. Go to the sidebar
2. In the Libraries section, click on the Documents folder: the prompt appears
3. In the Favourites section, clicking on the Documents folder does not show and anomaly

### Expected behavior

The folder already works fine, yet somehow the app detects it as if it has been deleted or moved. Could it be a bug caused by a duplicate link? (Documents in Favourites and Documents in Libraries).

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.527

### Windows Version

Windows 11 Home 21H2 Build 22000.527

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8190937/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8190940/debug_fulltrust.log)

**Comment by CapoFantasma97** [comment]
Also the Italian translation is flawed. It says:

### Do you want to delete this folder?

But the English prompt says:

### Did you delete this folder?

They ask very different things.

![immagine](https://user-images.githubusercontent.com/9368910/156889796-d80fcb8c-98eb-4f93-b835-4e952c074435.png)

**Comment by gave92** [comment]
Try to right click on Documents Library in the sidebar > Properties > Library.
You'll see the list of folders that the library points to, some of them may be invalid or not accessible.

**Comment by gave92** [comment]
Tracking the popup issue in #6681. Tracking here the wrong translation issue.

**Comment by CapoFantasma97** [comment]
> Try to right click on Documents Library in the sidebar > Properties > Library. You'll see the list of folders that the library points to, some of them may be invalid or not accessible. If you remove them the popup should be gone.

I confirm that there was a (no longer valid) OneDrive folder included. I've removed it from the Documents library and it's now fixed.

**Comment by CapoFantasma97** [comment]
> Tracking the popup issue in #6781. Tracking here the wrong translation issue.

I can update the localization file when I have free time and create a pull request; I'll take the opportunity to proofread the other strings as well.

**Comment by yaichenbaum** [comment]
@gave92 do you know if this is still an issue?

**Comment by gave92** [comment]
Fixed!
