### ISSUE TITLE
Files do not automatically refresh for network folders

### ISSUE THREAD

**Issue by gregveres** [files-community/Files#8581]
### Description

I have a Synology NAS that I am connected to over SMB. When I have Files open a folder on the NAS, the contents of the folder do not update when I do the following operations:

- drag and drop a file into the folder
- rename a file that already exists in the folder
- delete a file from the folder

After each of these opertations I have to explicitly refresh the folder to see the change. I am using the details view, but the other views behave the same way.

I have verified that these operations behave as expected when I am operating on a local drive.

### Steps To Reproduce

Drag and Drop
1. connect to a network drive / folder
2. drag a file from a local drive to this network drive window
3. observe that the contents of that network drive window do not show the dropped file in the list of files. 
4. click on the refresh button and observe that the file that was dropped now shows up

Rename

1. connect to a network drive/folder
2. select a file and press F2 to rename the file
3. rename the file
4. hit enter to confirm the rename
5. Observe that the file still shows the original file name
6. click on the refresh button and observe that the file now has the new name you gave it

Delete
1. connect to a network drive/folder
2. select a file and press ctrl-c then ctrl-v to make a copy of the file
3. observe that the copy does not appear in the window when it should
4. click on the refresh button and observe that the copy of the file now appears in the window
5. select the copy of the file and delete it it
6. select delete in the confirmation dialog
7. observe that the copy of the file is still shown in the window
8. click on the refresh button and observe that the copy of the file is no longer there

### Expected behavior

I expect the behaviour to be the same as a local drive. All of these operations should update the contents of the folder immediately without me having to click on the refresh button.

### Files Version

Version: 2.1.15.0

### Windows Version

windows 10 home 21H1 19043.1526

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8191110/debug.log)

**Comment by Josh-65** [comment]
Merging with #7304

**Comment by gregveres** [comment]
sorry for not noticing the other open issue. It does appear to be the same issue.
