### ISSUE TITLE
Continuous Crash of the Files App for windows 11

### ISSUE THREAD

**Issue by romario9113** [files-community/Files#8582]
### Description

after making a few new folders the app just starts spamming crashes no matter now often you open it. Practically making it unusable.

### Steps To Reproduce

Seems to occur after scrolling down a log list
Go to a folder with a long list of items that would necessitate about 3 scrolls minimum 
scroll to the bottom 
then scroll a bit up the list
the app will crash

### Expected behavior

I expected to scroll down to the bottom of my desktop folder and  to find some files 

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.527

### Windows Version

Windows 11 21H2

### Relevant Assets/Logs

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/101014279/156893880-df3c5a45-f94e-48ba-8afa-760405e55188.png">

**Comment by Josh-65** [comment]
You will need to upload the logs files directly to github. You can get them in files settings > about > open log folder.

**Comment by romario9113** [comment]
[debug.log](https://github.com/files-community/Files/files/8195074/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8195075/debug_fulltrust.log)

**Comment by Josh-65** [comment]
Is this still an issue?

**Comment by yaichenbaum** [comment]
While you're at it, you can see if it's resolved in the preview version https://files.community/download/preview.
