### ISSUE TITLE
Feature: Groups should follow ascending/descending preference 

### ISSUE THREAD

**Issue by jonnyka** [files-community/Files#8583]
### Requirements 
- Groups should follow ascending/descending preference

**Comment by Josh-65** [comment]
Sort option are on the toolbar
![image](https://user-images.githubusercontent.com/26977075/156901161-1382e110-ec3d-4827-9fe0-79e10457ada8.png)

**Comment by jonnyka** [comment]
that's for sorting, not grouping, can we re-open this?

**Comment by Josh-65** [comment]
grouping is below it

**Comment by jonnyka** [comment]
can you please try to understand my problem? I have eyes, I can see the grouping menu, but there is no way to GROUP in descending, I can only SORT in descending order

sorry, am I not clear?

**Comment by Josh-65** [comment]
what do you mean by groups

**Comment by jonnyka** [comment]
in the picture below, I'd like to have 2/1/2022 at the top, 1/1/2022 below it, 2/27/2022 below that, and 3/6/2022 would be the bottom group

![2022-03-06 11_28_14-Torrent ‎- Files](https://user-images.githubusercontent.com/2361747/156919232-58084b57-eb1c-40e5-9487-f04ff078abd0.jpg)

**Comment by Josh-65** [comment]
Ah right ok

**Comment by yaira2** [comment]
This will be supported in the next update
