### ISSUE TITLE
Feature: Add progress ring to properties when calculating sizes

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#8586]
### What's the Problem?

There used to be a loading icon when sizes were calculated which now doesnt appear and causes some confusion. See #8585

### Requirements
- Display progress ring next to the size labels to indicate when they are still loading

### Files Version

2.1.15.0

**Comment by yaichenbaum** [comment]
Is it really needed? The size itself acts as a loading indicator since it keeps updating.

**Comment by Josh-65** [comment]
for larger files it does end up stoping seeming like its done

**Comment by cinqmilleans** [comment]
@yair100 We better indicate if the calculation is in progress.
1) It is possible that the calculation seems to stop but then resumes. For example if the calculation in progress examines a subfolder that contains many very small files and the size given is an order of magnitude larger.
2) If the displayed size comes from the cache, it is never decreased until the calculation is finished (only increased). This is a current limitation that should be fixed when the cache is persistent. But even in this case, the calculation may take a moment before detecting a subfolder whose size has changed.

**Comment by Josh-65** [comment]
It was just a spinning loading icon before with no fixed value should probably be the same.
