### ISSUE TITLE
Crashes with Onedrive 365 folders

### ISSUE THREAD

**Issue by Memesy02** [files-community/Files#8587]
### Description

Scrolling through the right click context menu of a 365 synced folder when "Move overflow items into a sub menu" is toggled OFF results in severe lag then crash of all open windows of the app.

### Steps To Reproduce

1. Open Files
2. Click Settings
3. Move the toggle to "off" on the "Move overflow items into a sub menu" setting.
4. Navigate to a folder synced with Office Onedrive 365
5. Right click a file
6. Scroll up and down 1-2x while moving cursor inside the area of the overflow menu

### Expected behavior

Scrolling the overflow menu works

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.527

### Windows Version

Edition	Windows 11 Home Version	21H2 Installed on	‎Friday ‎14/‎01/‎2022 OS build	22000.527 Experience	Windows Feature Experience Pack 1000.22000.527.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8191941/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8191942/debug_fulltrust.log)

**Comment by gave92** [comment]
15:14:55.0549|ERROR|AppUnhandledException|Layout cycle detected.  Layout could not complete.
Layout cycle detected.  Layout could not complete

**Comment by gave92** [comment]
Merging with #5666
