### ISSUE TITLE
Using default Context Menu and Properties page

### ISSUE THREAD

**Issue by CapoFantasma97** [files-community/Files#8588]
### What's the Problem?

Both the Context Menu (right click) and the Properties pages of files/folders miss a fair amount of features that Windows possesses by default.

Some of the things missing in Context Menu:
- Customize folder
- Cancel/Repeat last action
- Change/Remove access to folder
- “Send to” submenu
- Some submenus generated by certain programs (e.g. AMD Radeon Software)

Some of the things missing in Properties (files and folders):
- “Open With:” (change default program to use when opening its file type)
- Advanced Attributes (indexing settings, compression, cryptography)
- Previous Versions tab
- Sharing tab
- Customization options (Files app only allows to choose an icon, you can't change the folder type or pick an image as preview)

### Solution/Idea

If possible, allow to choose between Files's Context Menu and Properties page, or Windows's default ones.

### Alternatives

Reach feature parity.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| A legacy option to enable back Windows's Context Menu and Properties page | Must |
| Files's own as default, but additional UI buttons to open Windows's own | Could |
| UI button/Shortcut to open the current tab into Windows File Explorer | Could |

### Files Version

Version 2.1.15.0

### Windows Version

Windows 11 Home 21H2 Build 22000.527

**Comment by yaichenbaum** [comment]
We don't have plans to add support for the classic menu and properties dialog but we're tracking support for the other options to bring feature parity between the two.
