### ISSUE TITLE
A bug while dragging files 

### ISSUE THREAD

**Issue by StormVortexx** [files-community/Files#8590]
So I was dragging some files from a folder to a ProgramFiles x86, it worked but every time I moved a file I had to press yes for the permission pop up, so I had to move 80 files and I had to press yes 80 times. Not a big bug but it can be annoying.

Here is a Google Drive link including the video since GitHub has a 10MB file limit.
https://drive.google.com/file/d/1GvXJxt0XMmR9pZfRWDlTUP37Oj34RC8S/view?usp=sharing

**Comment by gave92** [comment]
Merging with #5030
