### ISSUE TITLE
Remove the shortcut overlay icon

### ISSUE THREAD

**Issue by TheBanishingOfMosquito** [files-community/Files#8591]
### What's the Problem?

in the default browser i used winaero tweaker to edit the registry and disable the shortcut icon.
looks much better.

![R_defaultExplorer__L_File](https://user-images.githubusercontent.com/65665572/158433198-f3e82570-8d94-4f5b-babb-e80e33edeee0.png)

### Solution/Idea

![image](https://user-images.githubusercontent.com/65665572/156945742-1bb43ee7-c678-4be1-bf6a-5c35d8b52d94.png)

adding a tickbox in the setting menu
![image](https://user-images.githubusercontent.com/65665572/157094266-b35c5215-30c1-43cd-9f12-c80e29ad6d01.png)

### Alternatives
Going into the file directory and deleting that png/ico or swapping it out with an transparent icon. Where is the shortcut symbol reference¿
![image](https://user-images.githubusercontent.com/65665572/157094404-1fdd99f7-50fa-4815-87c3-5b72f9a9cbb0.png)

### Files Version

Version: 2.1.15.0 OS Version: 10.0.19044.1526

### Windows Version

OS Version: 10.0.19044.1526

### Comments
WinAero partly working with files. 
Seems like there is an additional id linked to files.  WinAero can only affect the true default shorcut arrow  which is hidden by default. Thus changing to e.g a custom shortcut arrow icon will return a third layer.
![image](https://user-images.githubusercontent.com/65665572/157093934-34aaf91f-6d88-469d-b948-87f1d60de614.png)

_No response_

**Comment by yaichenbaum** [comment]
https://winaero.com/remove-shortcut-arrow-overlay-in-windows-10/
