### ISSUE TITLE
No thumbnail preview for .blend file

### ISSUE THREAD

**Issue by ezul4000** [files-community/Files#8592]
### What's the Problem?

By default when using vanilla window file manager it should show the thumbnail preview for the file 
![image](https://user-images.githubusercontent.com/46102620/156971969-87e5ced2-40ae-48aa-9baf-16c935cd6d5f.png)

but when using the Files its only show like this
![image](https://user-images.githubusercontent.com/46102620/156972065-a0ff91ce-6297-4f6a-a329-7146fe34eb1e.png)

### Solution/Idea

apparently its a bug from blender itself but can be fixed with this 

![image](https://user-images.githubusercontent.com/46102620/156972491-3b4bd775-dbd2-4843-8fae-b786fe2c2cbf.png)

work on vanilla file explore but not on Files

### Alternatives

im not sure if there alternative

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.1.15.0 OS Version: 10.0.19043.1165

### Windows Version

Edition	Windows 10 Pro Version	21H1 Installed on	‎20-‎Jul-‎21 OS build	19043.1165 Experience	Windows Feature Experience Pack 120.2212.3530.0

### Comments

Your program were soo good btw. its just this small feature if implemented would benefit everyone who use blender

**Comment by yaichenbaum** [comment]
Merging with #2582
