### ISSUE TITLE
Drag files into folder tricker media keys

### ISSUE THREAD

**Issue by MaxSteven** [files-community/Files#8593]
### Description

When drag multiple files into a folder
And having some media player in background
Files tricker media key to resume playing video

### Steps To Reproduce

1. Open any media video with MPC and leave it paused in the background
2. Create a new folder with Files
3. Drag files into the new folder
4. Files is moved but also the video got resume playing back

### Expected behavior

It shouldnt affect the video playback in the background which is paused

### Files Version

Version: 2.1.15.0

### Windows Version

Windows 10.0.19044.1466

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8195202/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8195203/debug.log)

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.0.0?
