### ISSUE TITLE
Setting UI bug

### ISSUE THREAD

**Issue by whynotjinx** [files-community/Files#8596]
### Description

When I select different languages and auto restart the app, some dropdown menu fails to show correctly.
Btw the Chinese(simple) is mixed with Japanese translation.

### Steps To Reproduce

1. Reinstall the app
2. Change the language and auto-restart
3. Go to the setting and some dropdown menu fails to work.

### Expected behavior

Show the dropdown menu as usual.

### Files Version

2.1.15.0

### Windows Version

OS Version: 10.0.22000.527

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/33567283/157097712-285b1d44-676d-43b6-a2d4-c407dace2069.png)
![image](https://user-images.githubusercontent.com/33567283/157097742-e3f6e6c9-cdb2-44b3-bda7-d053b693baa2.png)

**Comment by whynotjinx** [comment]
About the translation:
![image](https://user-images.githubusercontent.com/33567283/157098119-3d4d3f3b-b0f6-4756-9b09-54e6864508f5.png)
I guess those two language files are somehow mixed.

**Comment by yaichenbaum** [comment]
Merging with #8100
