### ISSUE TITLE
Hover margin for tabs

### ISSUE THREAD

**Issue by shetozz** [files-community/Files#8597]
### What's the Problem?

the area that I'm allowed to click to switch between tabs doesn't cover the hall vertical space of the top bar, the red area looks like it will work if you press on it but it doesn't.
![Screenshot 2022-03-07 231124](https://user-images.githubusercontent.com/93838524/157118678-601edab7-6d4c-4fb5-a63e-ee21093e0e44.png)

### Solution/Idea

increasing the hover area to include the hall top bar vertical space

### Alternatives

making the top bar thinner

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
Merging with #6397
