### ISSUE TITLE
Transfer progress inaccurate

### ISSUE THREAD

**Issue by Samskandar** [files-community/Files#8602]
### Description

The transfer progress is listed at 100% but disk is still reading/writing and the progress bar in the taskbar is still running. This makes it unclear whether the file transfer between drives has really completed.

### Steps To Reproduce

1. Transfer a number of large files from harddisk to external drive
2. See that progress is listed at 100% in the ribbon besides the File's setting icon
3. See that disk is still writing in Task Manager/ Progress bar still in progress in taskbar (icon highlighted in green) - Windows 10

### Expected behavior

The progress in the files app in the ribbon corresponds to the actual progress

### Files Version

Version: 2.1.15.0 OS Version: 10.0.19044.1566

### Windows Version

10.1.19044 Build 19044

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8206489/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8206490/debug_fulltrust.log)

**Comment by gave92** [comment]
Thanks for the report. Would you be able to post a screenshot/recording showing this? Possibly with the "ongoing tasks" flyout open.

**Comment by Samskandar** [comment]
![error report incorrect file transfer status](https://user-images.githubusercontent.com/15168560/158008377-64086479-b2d2-48b8-ad03-a7fd20aca906.png)

**Comment by gave92** [comment]
And I suppose you were copying more than 5 files right?

**Comment by Samskandar** [comment]
Yes you are right. Several folders of files actually

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by yaichenbaum** [comment]
@Samskandar is this still an issue in the preview version? https://files.community/download/preview

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?
