### ISSUE TITLE
Can't open terminal

### ISSUE THREAD

**Issue by Viole403** [files-community/Files#8603]
### Description

After I installed the update, I can't even use it anymore

### Steps To Reproduce

1. Open Files
2. Press the three dots under the settings menu
3. Click ' Open in '

### Expected behavior

I just hope this function can work before update

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.527

### Windows Version

Windows 11 21H2 22000.527

### Relevant Assets/Logs
[debug.log](https://github.com/files-community/Files/files/8206987/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8206988/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
Merging with #8100
