### ISSUE TITLE
Can't access root of Drives

### ISSUE THREAD

**Issue by SpoonMcForky** [files-community/Files#8606]
### Description

Files can't access the root point of drives. In the home screen, there are no drives displayed, and manually typing in the path just makes it hang on loading.

### Expected behavior

Drives should appear and be accessible, not just their subfolders 

### Files Version

Version: 2.1.15.0

### Windows Version

OS Version: 10.0.19044.1566

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8209442/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8209443/debug.log)

**Comment by gave92** [comment]
Could you verify if in windows settings > privacy > Filesystem, filesystem permission is granted to Files?
