### ISSUE TITLE
Add support for showing dot files on network drives

### ISSUE THREAD

**Issue by dhbtfs** [files-community/Files#8607]
### What's the Problem?

Linux hidden folders are still not visibile, Can you please add this so we can have them if we have linux server on network using:
Please make it so we are not force to use the network Z;/ partition.
`\\mylinuxip\.hiddenlinuxfolder`

### Solution/Idea

It already exist in normal windows drive (who has linux folder in windows which tbh doesnt make any sense to me, but then again I am no dev). 

### Alternatives

NA

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.18.0

### Windows Version

Windows 11 Pro 21H2 22000.527

**Comment by gave92** [comment]
Merging with #3153 #2436
