### ISSUE TITLE
Feature: Display conflicts modal when pasting on FTP locations

### ISSUE THREAD

**Issue by Notarin** [files-community/Files#8609]
### What's the Problem?

When copy/pasting files the default behavior is to simply append " - copy" to the end of the file names, more often than not this is not the intended action on the users behalf. The frequency that a user wishes to copy over, or even cancel the entire operation is enough to warrant this being an issue.

### Requirements

- Display conflicts modal when there are conflicts on network shares

**Comment by Notarin** [comment]
I'm sorry, i just realised with some experimentation that files already has this feature, for some reason it was not working as intended, I will close this issue until I am able to reproduce this issue on demand, I will then reopen and request the tag to be changed to bug.

**Comment by Notarin** [comment]
I have figured out how to reproduce the issue, it seems to only occur when copy/pasting on mounted share drives. Should I request the tag be changed to bug or submit a new issue? and what logs are safe to share?

**Comment by Notarin** [comment]
@yair100 I have installed the preview version 2.2.9.0 and tested again, It is still an issue.
[debug.log](https://github.com/files-community/Files/files/8705565/debug.log)

**Comment by Notarin** [comment]
If it helps, the drives are mounted via VBA
`MapDrive "O:", "\\xxx.local\xxx\O"`

**Comment by Notarin** [comment]
By the way, isn't this technically a bug, since this isn't necessarily adding anything new, but rather correcting unintended behavior?

**Comment by yaichenbaum** [comment]
> By the way, isn't this technically a bug, since this isn't necessarily adding anything new, but rather correcting unintended behavior?

It's considered a feature request since we haven't implemented this feature for network drives yet.

**Comment by jspro25** [comment]
everyone, please kkownim not trying to di anything wrong. fir somersason this part of crypto is just hard for me. too many wallets. please help me by being more direct. i dont even know for sure this is mine. i will absolutely help those who help me, without a doubt


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Notarin** [comment]
> It's considered a feature request since we haven't implemented this feature for network drives yet.

Ah, I understand, I was thinking that it has been implemented for everything relevant, but simply was not opening on network drive pastes due to a bug.
Understandable, have a nice day.

**Comment by hishitetsu** [comment]
Conflicts modal is already displayed on network drives such as `Z:` and `\\servername\share`.
It is not displayed on FTP servers though.

**Comment by yaira2** [comment]
@hishitetsu I updated the title to reflect this, thank you.

**Comment by yaira2** [comment]
This issue will be resolved in v2.5.

**Comment by Notarin** [comment]
@yair100 Awesome! Thank you and the team for the awesome work y'all do! I can't wait to see it!
