### ISSUE TITLE
No error message if a USB stick hasn't any space left

### ISSUE THREAD

**Issue by mursonic** [files-community/Files#8610]
### Description

I wanted to copy a zip-file to a USB stick. The file was larger than the remaining space on that stick. I wasn't aware of that. Files gave positive feedback that the file was copied but it didn't show up on the stick.

I tried to copy the file via the Windows file explorer and now a message popped up that there was no space left on the stick.

### Steps To Reproduce

- use a USB stick with no space left
- try to copy a file larger than the remaining space

### Expected behavior

I would like to get a message that there is no space left. Like the windows file explorer does.

### Files Version

Version: 2.1.15.0

### Windows Version

Windows 11 21H2 22000.527

### Relevant Assets/Logs

-

**Comment by gave92** [comment]
Merging with #7947
