### ISSUE TITLE
User/PW window do not show when access to file server

### ISSUE THREAD

**Issue by almes10** [files-community/Files#8613]
### Description

When I trying to access to a file server (e.g. \\192.168.0.50\shared folder) it should show a User/PW login window. But it do not show. I have to use File Explorer to input User/PW and then use Files App.

### Expected behavior

It should show the login window.

### Files Version

Version 2.1.15.0 

### Windows Version

Windows 11 21H2 22000.527

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8219755/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8219756/debug_fulltrust.log)

**Comment by gave92** [comment]
Merging with #7205
