### ISSUE TITLE
Thumbnails Not showing

### ISSUE THREAD

**Issue by Splitpulse** [files-community/Files#8614]
### Description

Thumbnails not showing since 2.1.2 when small or large icons layout is enabled.

### Expected behavior

Thumbnails are suppose to show. File explorer shows them properly while Files does not.

### Files Version

2.1.19

### Windows Version

Win 10

### Relevant Assets/Logs

![Screenshot 2022-03-09 212008](https://user-images.githubusercontent.com/101306829/157582257-91e858cb-6498-4db6-8747-98325fbd7c09.jpg)

**Comment by yaichenbaum** [comment]
Merging with #2582
