### ISSUE TITLE
File sorting options

### ISSUE THREAD

**Issue by SaajidAtVX7** [files-community/Files#8615]
### What's the Problem?

The currently available file sorting options in detailed layout are Name, Date modified, Date created, Type, and Size. Other than this windows explprer provides plenty of options for sorting. The sorting options in Files app are currently limited to 5.

### Solution/Idea

Consider adding more options to sorting menu and more columns in detailed layout

### Alternatives

Look in the more section of sort by menu in windows explorer

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
Merging with #3927
