### ISSUE TITLE
Sorting options are not available in column layout

### ISSUE THREAD

**Issue by SaajidAtVX7** [files-community/Files#8616]
### What's the Problem?

The sorting options are not available in the column layout. While on the column layout the sorting is according to file name only

### Solution/Idea

Add an option to perform sorting while the selected layout is column

### Alternatives

The one feature missing on windows explorer when comparing to Mac finder is the column view. Please refer it.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.15.0

### Windows Version

Windows 10 21H1

**Comment by gave92** [comment]
Merging with #6370. Sorting in column view is possible (from context menu or toolbar flyout) but the selected sorting option does not stick.
