### ISSUE TITLE
Adjusting width of the columm in column layout

### ISSUE THREAD

**Issue by SaajidAtVX7** [files-community/Files#8617]
### What's the Problem?

In Files app we can adjust the width of the sidebar. But I can't adjust the width of a column in column layout

### Solution/Idea

Adding an option for adjusting column pane width would be more useful while dealing with long file names

### Alternatives

In Mac finder we can adjust the width of the column view pane

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.15.0

### Windows Version

Windows 10 21H1

**Comment by yaichenbaum** [comment]
Merging with #6534
