### ISSUE TITLE
Option for hinding sidebar

### ISSUE THREAD

**Issue by SaajidAtVX7** [files-community/Files#8618]
### What's the Problem?

There are options available to show or hide items in the sidebar in the settings page but the option to hide the sidebar entirely is absent

### Solution/Idea

Adding this option will help to view more files at once

### Alternatives

Windows explorer can hide the navigation pane entirely

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.15.0

### Windows Version

Windows 10 21H1

**Comment by yaichenbaum** [comment]
You can collapse the sidebar by double clicking the grid splitter/resize handle.
