### ISSUE TITLE
Feature: Add play button when multiple media files are selected

### ISSUE THREAD

**Issue by SaajidAtVX7** [files-community/Files#8619]
## Requirements
- Add play button to toolbar when multiple media files are selected
- Play button should open the files in the default media player app

### Files Version

2.1.15.0

### Windows Version

Windows 10 21H1

**Comment by yaichenbaum** [comment]
Which options are you looking for that aren't already in the toolbar?

**Comment by SaajidAtVX7** [comment]
Like, for example if we selected an audio file, then the explorer will dynamically shows an audio tools menu highlighted in a different color in the Ribbon UI. This menu will disappear as soon as we deselected the file. Such options are absent in Files app. Also it is more convenient to managing files from icons in the Ribbon UI rather than pulling and selecting an option from a menu

**Comment by yaichenbaum** [comment]
> Like, for example if we selected an audio file, then the explorer will dynamically shows an audio tools menu highlighted in a different color in the Ribbon UI. This menu will disappear as soon as we deselected the file. Such options are absent in Files app. Also it is more convenient to managing files from icons in the Ribbon UI rather than pulling and selecting an option from a menu

Can you send screenshot of the audio tab?

**Comment by SaajidAtVX7** [comment]
![Screenshot 2022-03-11 112014](https://user-images.githubusercontent.com/6974937/157811038-9067dc23-c996-48f5-adc2-f4c1e8d4f68a.png)

Here is the normal ribbon menu ☝

![Screenshot 2022-03-11 112117](https://user-images.githubusercontent.com/6974937/157811146-9723f2c7-fd54-4446-ad32-e52942555120.png)

This is the music tools menu generated when selected an audio file (shows picture tools menu if we selected an image file)

**Comment by yaichenbaum** [comment]
That's quite a waste of real estate for two options (the first one isn't necessary since you can already double click a file to play it).

**Comment by yanoryuichi** [comment]
In Office apps, Ribbon menu is customizable, so that I can put specific menu items I frequently use on spcific Ribbon tabs. But in File Explorer Ribbon menu is fixed, so third party apps clutter context menu with their long items. Then it makes problems like this. https://github.com/files-community/Files/issues/8633

**Comment by puppetsw** [comment]
The "Add to playlist" button. Do we want it to create a m3u playlist in the current directory? or store it in the temp folder? or something different all together?

**Comment by yaira2** [comment]
Let's hold off on the playlist option and limit this to the "play" button.
