### ISSUE TITLE
Bottom deatils pane

### ISSUE THREAD

**Issue by SaajidAtVX7** [files-community/Files#8620]
### What's the Problem?

The meged preview and details panes are littile bit cluttered and sometimes confusing.

### Solution/Idea

Please seperate the details in to seperate bottom pane like in windows 7 explorer and put preview pane on right

### Alternatives

Windows 7 Explorer

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.15.0

### Windows Version

Windows 10 21H1

**Comment by yaichenbaum** [comment]
Merging with #4890
