### ISSUE TITLE
Audio playback in preview pane stops when changing tab

### ISSUE THREAD

**Issue by SaajidAtVX7** [files-community/Files#8621]
### Description

While previewing an audio track if we open a new tab or lock our pc the playback stops immediately. The playback won't start even if press play button on the lockscreen mini player.

### Steps To Reproduce

1. Select an audio file
2. Play it on preview pane
3. Try to open a new tab or lock the pc
4. The playback stops immediately

### Expected behavior

The playback should continue even after open a new tab or locked the PC

### Files Version

2.1.15.0

### Windows Version

Windows 10 21H1

### Relevant Assets/Logs

Nothing

**Comment by SaajidAtVX7** [comment]
Ok I'm agreeing that it's not a media player. But it would be great if it had  a mini audio player built in with it

**Comment by KosmosisDire** [comment]
It seems like it would make sense for it to keep playing when tabs are changed, but I don't know about when the computer is locked.

**Comment by yaichenbaum** [comment]
This is the expected behavior. Allowing audio to play on multiple tabs at once isn't desirable.
