### ISSUE TITLE
New Tab default location

### ISSUE THREAD

**Issue by LosOmatic** [files-community/Files#8622]
### What's the Problem?

When you click to open a new tab, it defaults to a particular folder, the HOME folder. For a majority of my workflow, it is a huge time saver to have that new tab open in the same folder view as the current folder I have open now. 

### Solution/Idea

Default the new tab folder view to the current folder view. (this is what Stardock's Groupy app currently does)

### Alternatives

Provide option in settings to default to a specific folder, instead of the Home folder, when the new tab button is pressed.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version
2.1.15.0

### Windows Version
11 | build 22000.556

**Comment by yaichenbaum** [comment]
Merging with #6480
