### ISSUE TITLE
Missing filesize in status bar

### ISSUE THREAD

**Issue by mistic100** [files-community/Files#8623]
### Description

In some conditions the selected filesize is not displayed in the status bar.

### Steps To Reproduce

1. make sure Files is closed
2. open a new Files instance
3. navigate somewhere
4. select a single file => **the filesize is not displayed**
5. select multiple files => **the filesize is displayed**
6. select a single file => **the filesize is displayed**

for no on, the filesize is always displayed, until Files is restarted and multiple files are selected at least once

### Expected behavior

The selected filesize is always shown

### Files Version

2.1.15.0

### Windows Version

10.0.19043.1526

### Relevant Assets/Logs

![Capture d’écran](https://user-images.githubusercontent.com/41597/157751859-e630257c-3767-4e9e-84b4-10d091e8d571.jpg)

**Comment by mistic100** [comment]
More generally I feel that the status bar shows outdated informations.

Today I have another case where the total number of items is wrong :
![selection](https://user-images.githubusercontent.com/41597/158012648-aea307e9-4787-4499-9597-011663f323d5.PNG)

of course "66 selected over 30" is not possible

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.0.0?

**Comment by yaichenbaum** [comment]
It appears to be resolved
