### ISSUE TITLE
preview pane

### ISSUE THREAD

**Issue by Bargithub** [files-community/Files#8625]
### What's the Problem?

Hello, 

When I turn on preview pane all I see is name of file or folder etc, not what is in document. Is this feature available, if so how do I enable?

Thanks,
Barry 

### Solution/Idea

Include it if it hasn't been done.

### Alternatives

same as solution

### Files Version

Version: 2.1.15.0 OS 

### Windows Version

windows 11

**Comment by gave92** [comment]
What kind of document? Office?

**Comment by Bargithub** [comment]
Yes.

**Comment by gave92** [comment]
Currently not supported. Tracked in #4041.
