### ISSUE TITLE
Opening "shell:AppsFolder" from Run has odd behavior...

### ISSUE THREAD

**Issue by yodaluca23** [files-community/Files#8626]
### Description

Whenever I open the "shell:AppsFolder" from run (Win+R) It opens then closes, then opens my documents folder in the old file explorer app (Despite me having the default registry thing enabled"

### Steps To Reproduce

1. Sideload the latest version
2. Turn on "Set files as the default file manager"
3. Press Win+R
4. Type in "shell:AppsFolder"
5. Press enter
6. Witness bug

### Expected behavior

It to open the Shell Apps folder in the Files app.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.556

### Windows Version

Edition	Windows 11 Home Version	21H2 Installed on	‎10/‎29/‎2021 OS build	22000.556 Experience	Windows Feature Experience Pack 1000.22000.556.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8227854/debug.log)

**Comment by gave92** [comment]
Any difference is you type `files shell:appsfolder`?

**Comment by yodaluca23** [comment]
Interesting... When I do that the files app opens the closes instantly like before, but then instead of File Explorer opening to Documents, it does open to the desired shell:appsfolder...

**Comment by yaichenbaum** [comment]
This issue should be resolved with #8684
