### ISSUE TITLE
Crash when removing multiple .exe files

### ISSUE THREAD

**Issue by fori920** [files-community/Files#8627]
### Description

When selecting multiple files in a local drive directory (in this case they were a bunch a .exe installer files), Files app crash for an unknown reason.

### Steps To Reproduce

1. Navigate to the files to delete
2. Select multiple files via mouse as well as holding Shift key
3. Press Shift+Del to prompt the confirm dialog.
4. Confirm delete pressing the Delete button on the dialog.

### Expected behavior

Files should have been deleted.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.493

### Windows Version

Windows 11 21H2 22000.493

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8228361/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8228362/debug.log)

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?
