### ISSUE TITLE
Files App: MS Office files cannot be previewed

### ISSUE THREAD

**Issue by pli7pli7** [files-community/Files#8628]
### Description

I love everything about the Files app for Windows. Thanks! But just one issue/bug: MS Office files (.docx, .pptx, .xlsx) do not show Preview. Other files such as PDF's show preview correctly.

Any fix?

### Steps To Reproduce

1. Go to any folder with DOCX / PPTX / XLSX files
2. Make sure the Preview pane is turned on
3. Click on one of those MS Office files
4. The Preview pane only shows a large generic icon of Word, PPT, or Excel

### Expected behavior

The Preview pane should show a preview of the selected MS Office file instead of a generic icon.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.19043.1586

### Windows Version

Windows 10 Version 21H1 (OS Build 19043.1586)

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/101374403/157790270-4d98792a-6449-47c0-a08b-22d972b45e4a.png)

**Comment by yaichenbaum** [comment]
Merging with #4041
