### ISSUE TITLE
Favorites section always collapse when open

### ISSUE THREAD

**Issue by narutophuc113** [files-community/Files#8631]
### Description

It's been a while and I hope it will be fixed soon. It's also is the reason why I can totally switch from default File Explorer from window to Files.
-----
Every time I open FIles, I want the Favorites section should be expanded, the arrow shows that it's was expanded (as the image I attached) but the content inside wasn't shown.
(I also tested with other sections such as Drives and have the same behavior)

### Steps To Reproduce

1. Open Files
2. Click Favorites
3. The arrow changes direction
4. Click **again** in Favorites
5. The content shown

### Expected behavior

1. Open Files
2. Favorites and Drives section can be expanded as default

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22563.1

### Windows Version

Version: 10.0.22563 Build 22563

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/45137920/157804487-d2917e4d-a676-4c33-bef5-a33197c4dab2.png)

**Comment by gave92** [comment]
Tracked in #6469. Unfortunately fixing this appear to require is to rewrite the sidebar control.
