### ISSUE TITLE
Issue with box cloud drive

### ISSUE THREAD

**Issue by mellor66** [files-community/Files#8632]
### Description

I have "box" mounted as a drive through their app in explorer - when selecting it through files it just continually flashes and you cannot access the folders (although they do show up in the right hand pane) - tried on another machine with the same result.

Any ideas?

### Steps To Reproduce

1. Open files
2. Go to cloud files
3. Select "box"

### Expected behavior

Should work as normal file access

### Files Version

2.1.15.0

### Windows Version

Edition	Windows 11 Business Version	21H2 Installed on	‎30/‎07/‎2021 OS build	22000.556 Serial number	CZC0289P8S Experience	Windows Feature Experience Pack 1000.22000.556.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8229415/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8229417/debug_fulltrust.log)

**Comment by gave92** [comment]
Merging with #7428
