### ISSUE TITLE
Show full folder context menu when right-clicking on empty folder area

### ISSUE THREAD

**Issue by masta** [files-community/Files#8633]
### What's the Problem?

In Windows Explorer, when you right-click on the empty area of a folder, you get the context-menu of the current folder. In Files, this is not the case.

Please implement it like in Windows Explorer.
See below for screenshots.

Context:
I use this a lot as I'm working with TortoiseGIT and TortoiseSVN.
This may also be the cause of the following issues:
#3206
#5315

### Solution/Idea

When right-clicking on the empty area of a folder, show the folder context menu.

### Alternatives

There is no alternative other than always moving up or using 'Columns' view to be able to right-click on the current folder.

### Files Version

2.1.15.0

### Windows Version

Windows 11 21H2 22000.556

### Comments

See the context menu when opening in empty area of current folder:

![ContextMenuOnFolderArea](https://user-images.githubusercontent.com/69071/157818755-b8db0e92-5b06-4176-994a-3741c8530638.png)

Here's the context menu when opening on a folder:
![ContextMenuOnFolder](https://user-images.githubusercontent.com/69071/157818840-040278e4-bdf3-4d58-acc2-9ecf5f9d0ceb.png)

The second one gives you access to all the folder features, including TortoiseGIT/SVN integration.

**Comment by gave92** [comment]
Thanks for the report. Could you verify if you simply need to scroll down the context menu to see the missing options?

**Comment by masta** [comment]
Hey @gave92 thank you and the community for this nice application!

Holy yes, you are right. There is an invisible scrollbar in this context menu.
You can see it in the screenshot above, or better, you can see that I can't see it. But if I move the mouse inside, it appears. It also doesn't scroll when reaching the bottom. I have use the scroll wheel.

So it really depends on the screen resolution and context menu position.

Is there any way to improve this i.e. make it more visible?

**Comment by Josh-65** [comment]
This has been fixed in 2.3.0.0 and for the invisible scrolbar it likely a WinUI/Windows issue. I havent had it happen so make a new issue if you encounter it again.
