### ISSUE TITLE
Importing png image to Adobe Indesign

### ISSUE THREAD

**Issue by mak-inter** [files-community/Files#8634]
### Description

Hi, I'm trying to discontinue some png indesign but something goes wrong. When I use explorer it transfers correctly but in your application the background of the picture is also included.

### Expected behavior

PNG images should be imported correctly

### Files Version

latest

### Windows Version

win 10

### Relevant Assets/Logs

?

**Comment by yaichenbaum** [comment]
@mak-inter can you upload a screenshot?
