### ISSUE TITLE
Nice product, but without hierarchy view I can't use it

### ISSUE THREAD

**Issue by PESarlington** [files-community/Files#8636]
I was surprised that the folders were not expandable in the left pane to show sub-folders.  Nice product, but, having hundreds of nested folders, this is pretty useless without it, as that is an important navigational feature for developers, who, I would expect to be one of your primary targets.  I like the multiple tabs.  Tried because of a shout-out in Verge this morning.  Good luck.

**Comment by yaichenbaum** [comment]
Merging with #1928

**Comment by yair100** [comment]
@PESarlington Tree View is currently available in preview https://files.community/download. It will be included in the next stable release.
