### ISSUE TITLE
Unable to set File Explorer as default after uninstalling Files

### ISSUE THREAD

**Issue by jeevanthespark** [files-community/Files#8637]
### Description

I have uninstalled Files App without disabling the Files App default toggle in experimental features. Now i am unable to use File Explorer. It throws **Explorer.EXE Application Not Found** error. Could you please provide with a powershell script for the registry entries and other things that need to be modified to revert it back to normal. Please help on this one asap.

### Steps To Reproduce

1. Install Files App
2. Set Files App as default file explorer app in Experimental Features
3. Uninstall Files App without disabling the experimental feature toggle
4. Explorer.EXE Application Not Found error thrown when trying to open Windows Explorer

### Expected behavior

I need to restore Windows Explorer as default file explorer after uninstalling Files App.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22572.1

### Windows Version

Windows 11 22H2 22572.1

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8232096/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8232097/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
#7626
