### ISSUE TITLE
batch, bulk, multi-rename

### ISSUE THREAD

**Issue by recordscience** [files-community/Files#8638]
### What's the Problem?

Would love to see that, as in xplorer², but simpler :)
Wildcard textbox #1
Output textbox #2
Preview-Area
[Preview] [Do Rename]

done <3

### Solution/Idea

The solution for the feature i am missing would be to have it implemented.

### Alternatives

create own symlinks to windows command line (that'd be even more simple, as in: mark multiple files, rightclick, rename by executing "for %a in (*. *)..." but yeah, having that menu entry would be cool!

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.1.15.0 OS Version: 10.0.19042.1586

**Comment by yaichenbaum** [comment]
Merging with #6514
