### ISSUE TITLE
A Few Issues

### ISSUE THREAD

**Issue by vikevinn** [files-community/Files#8640]
- Files app crashes often
- Unable to drag and drop files from Files window into web page file upload boxes
- Dragging files between folders is slow and often does not work
- Files window needs to be refreshed often to show correct files in any folder
- Files window will act like random items in the left pane are being selected until the Files window is closed and reopened

**Comment by Josh-65** [comment]
Plese open sperate issues following the template. Some of these issues may also be alrady made so look at some first
