### ISSUE TITLE
feature request list

### ISSUE THREAD

**Issue by fazioliamboina** [files-community/Files#8641]
### Solution/Idea

- I would like even bigger thumbnails in the file listing (up to the whole screen width)
- i want to pinch-to-zoom to make thumbnails smaller or bigger
- pictures in the preview panel do not fill the whole space. I want to see the previews as big as possible.
- make showing details in the preview panel disable-able, to recover more screen space for the preview.
- the file thumbnails are cropped to perfect squares. this makes my work really difficult.
- There is no way to differentiate video files from pictures. no indicator for it in the thumbnail.

### Alternatives

The windows default file explorer has all the features i want, except for bigger thumbnail sizes... same problem as Files v2

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by Josh-65** [comment]
Plaese open seprate issues.

> the file thumbnails are cropped to perfect squares. this makes my work really difficult.

see #8128
