### ISSUE TITLE
Open in cmd/powershell not working

### ISSUE THREAD

**Issue by DennisTsiang** [files-community/Files#8642]
### Description

Using:
Version: 2.1.15.0
OS Version: 10.0.19042.1586

The "Open in" feature to open directories in cmd/powershell appears to not longer work 

### Steps To Reproduce

1. Open directory in files
2. Right click empty space
3. Click "Open in"

### Expected behavior

When "Open in" is clicked, I expect either cmd/powershell to be opened to the directory. Instead, nothing happens.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.19042.1586

### Windows Version

Edition	Windows 10 Pro
Version	20H2 Installed on	‎05/‎12/‎2021
OS build	19042.1586
Experience	Windows Feature Experience Pack 120.2212.4170.0

### Relevant Assets/Logs

N/A

**Comment by gave92** [comment]
Sometimes it happens, you'll need to reset the app

**Comment by DennisTsiang** [comment]
@gave92 By reseting do you mean restarting the application? Because that doesn't fix it for me, and I don't think that is a practical solution to the problem either.

**Comment by gave92** [comment]
No, I mean resetting the app from  windows settings > apps > Files

**Comment by DennisTsiang** [comment]
Right I see thanks, that does seem to fix the issue for now

**Comment by gave92** [comment]
Thanks for confirming. Merging with #8100. Till this is fixed if you may need to reset the app again after each update.
