### ISSUE TITLE
Display/indication of file-size

### ISSUE THREAD

**Issue by miller3d09** [files-community/Files#8643]
### What's the Problem?

The file-size is shown both in MB & GB. 
This makes quick file-size-analysis time-consuming (e.g. when one wants to keep files in chronological-order, eg. in a backup-file-folder).
Also; the display of file-figures is formatted left, adding further to time-wastage. 

{It is appreciable that the programmers of this file-manager want to offer more chronistically appropriate file-sizes, but one must not mix file-dimensions.

### Solution/Idea

Offer users to display file-sizes either in GB or MB. 
Format file-size-display right (with the 2 digits after the dot). 

### Alternatives

Reverting to usage of Micros-file-explorer.

### Priorities

| Capability | Priority | WW
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.1.15.0 

### Windows Version

OS Version: 10.0.19044.1586

### Comments

This feedback-webpage should automatically display the requested version-numbers. 
Users should not have additionally suggest a capabilty/priority to developers in such a convoluted manner (it should be point & click).

**Comment by Josh-65** [comment]
> This feedback-webpage should automatically display the requested version-numbers.
This is not possible as github has no intergration or relation to files to send this infomation.

> Users should not have additionally suggest a capabilty/priority to developers in such a convoluted manner
This is an optional item and is as good as github fourms allow it, also isnt that hard.

As for the rest of your issue. Is it that you want a way to force files sies to be shown in one way (like always MB or always GB)
