### ISSUE TITLE
Maybe we should have a separate "discussions" section

### ISSUE THREAD

**Issue by ezxpro** [files-community/Files#8644]
### What's the Problem?

Not much of a problem, but an idea to be discussed. Have a separate "discussion" page and leave issues strictly to report actual issues.

### Solution/Idea

I always thought the "issues" page from most GitHub projects seems to be a lot less about issues than it is about discussions in general.

Explorer Patcher is a project where the devs explicitly ask people to only post issues in that page, and everything else (including feature suggestions or requests, but also general discussions relating the project) goes into a separate discussion page. I think that'd be nice to have here, see this:

https://github.com/valinet/ExplorerPatcher/issues/56

### Alternatives

None, just this one.

### Priorities

just discuss about this suggestions

### Files Version

nil

### Windows Version

nil

### Comments

a

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
I agree.

**Comment by yaichenbaum** [comment]
Thank you for your feedback, we currently use Discord for discussions.
