### ISSUE TITLE
Expiremental Features Gone

### ISSUE THREAD

**Issue by Flowrif** [files-community/Files#8645]
### Description

When I go into experimental features, none of the features I use are present. They have just disappeared for no apparent reason!

### Steps To Reproduce

1. Open files app
2. Click settings gear
3. Click experimental features
4. I am on Windows 11 and I have cleared app data and also re-installed Files while issue persists

### Expected behavior

I am trying to activate "Set as default file browser"

### Files Version

2.1.15.0

### Windows Version

Windows 11

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/100743148/158021236-ce776ad7-d3ff-4289-8fa3-45d1c51214b7.png)

[debug.log](https://github.com/files-community/Files/files/8237733/debug.log)

[debug_fulltrust.log](https://github.com/files-community/Files/files/8237734/debug_fulltrust.log)

**Comment by gave92** [comment]
"Set as default" is only available for the sideload version. It was removed from the Store version at Microsoft request.
