### ISSUE TITLE
App crashing

### ISSUE THREAD

**Issue by 3Y3G** [files-community/Files#8646]
### Description

When I open my Pictures folder in the app crashes

### Steps To Reproduce

1. Go to Libraries
2. Open Pictures
3. Crash appears

### Expected behavior

I expected to see my pictures.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.556

### Windows Version

Windows 11 Pro 21H2 22000.556

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8238015/debug.log)
![image_2022-03-12_191931](https://user-images.githubusercontent.com/79056979/158027976-52176872-eb60-404d-8564-70c6cc8e2692.png)

**Comment by 3Y3G** [comment]
When I open anything from the Libraries section the app crashes

**Comment by gave92** [comment]
Any difference if you turn off the "show folders size" option(if it's on)?

**Comment by 3Y3G** [comment]
There is a difference. It doesn't crash when it's off.

**Comment by gave92** [comment]
Merging with #8413
