### ISSUE TITLE
Files crash when deleting file that is in use

### ISSUE THREAD

**Issue by blbezcc** [files-community/Files#8647]
### Description

When I have Minecraft opened and try to delete a resource pack, Files crash.

### Expected behavior

I expected to show a message.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.19044.1586

### Windows Version

Windows 10 Pro 21H2 19044.1586

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8238079/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8238080/debug.log)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #8809
