### ISSUE TITLE
Selection of Files/Folders via Hovering Mouse Over

### ISSUE THREAD

**Issue by T3chminator** [files-community/Files#8648]
### What's the Problem?

I see that there is no way to select files/folders by hovering the mouse pointer over.

Also, there is no option to make Files the default file explorer but I found out that if I use the sideload version from the Files website, I have the option to make it default file explorer but not if I get it via the MS Store.

### Solution/Idea

By hovering the mouse pointer on a file/folder it should be selected without having to click on it.

### Alternatives

n/a

### Files Version

Version: 2.1.15.0

### Windows Version

Windows 10 OS Version: 10.0.19044.1526

**Comment by gave92** [comment]
Merging with #3682
