### ISSUE TITLE
Recycle bin doesn't ask for confirmation when dragging item to sidebar

### ISSUE THREAD

**Issue by Nexxol** [files-community/Files#8649]
### Description

![image](https://user-images.githubusercontent.com/68960034/158043032-6eabf679-5e07-4eb6-a9e8-142798a1f03a.png)
(these are the folders I'm talking about)

If you go to wherever those system folders are located (mine is at the root of my B: drive) you can drag them into the recycle bin if you have recycle bin pinned to favourites.

If you drag it to the recycle bin it deletes all files inside of it even if you recover it in recycle bin, To recover these files you NEED to use recovery software. I Accidentally dragged my Videos folder into the recycle bin and when I restored it from recycle bin everything was gone.

### Steps To Reproduce

1. Have recycle bin pinned to the sidebar
2. Go to where those system folders are located
3. Drag them into the recycle bin on the sidebar
4. Try recovering them from the recycle bin
5. All files will be gone

### Expected behavior

You should not be able to delete these folders, they are system folders. File explorer does not allow you to and for good reason.
![image](https://user-images.githubusercontent.com/68960034/158043246-3ff3361c-4d7f-4210-9fce-f7dc4ea18e07.png)
(Windows file explorer) 

Below is a picture of me dragging Videos from  B: into Recycle Bin that is pinned on the sidebar. You should not be able to do this.
![image](https://user-images.githubusercontent.com/68960034/158043290-dec25551-b905-4241-8b32-5bb136f6194d.png)‌‌
(this is from Files)​‌‌‌‌​‌​​‌‌​‌​‌​​​​‌​​‌​​‌​‌‌​​‌‌​‌‌‌​‌​​‌​‌‌​‌​​‌‌‌‌​‌​‌​​‌‌

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22572.100

### Windows Version

Windows 11 22H2 (OS Build 22572.100)

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/68960034/158043325-d8145fda-2aa7-44f3-88bc-1b514e555e88.png)

**Comment by yaichenbaum** [comment]
@Nexxol this is by design, you can delete these folders in File Explorer as well.

**Comment by Nexxol** [comment]
@yair100  You cant. as shown in my screenshot 
![image](https://user-images.githubusercontent.com/68960034/158044235-d17c3b9b-ea9a-4045-b057-56f66a6fdd64.png)
it does not allow you to. This is because if you do, it deletes every file inside of it. If you recover it in recycle bin it only recovers the folder itself, it doesn't recover any files inside and the files inside are nowhere to be found inside of recycle bin. Which is why I mentioned you have to use a data recovery tool to get it back. These are system folders, they are not meant to be deleted.
![image](https://user-images.githubusercontent.com/68960034/158044303-52943de7-8d88-4dc7-a4b4-042507ce1e9e.png)

**Comment by yaichenbaum** [comment]
@Nexxol The Video "Folder" in File Explorer is actually a library. If you navigated to actual directory that contains the videos in File Explorer, you'll be able to delete it.

**Comment by Nexxol** [comment]
Ah, well when i accidentally dragged that library into the recycle bin it completely wiped everything inside and I had to resort to a data recovery tool

**Comment by yaichenbaum** [comment]
That's unfortunate, did you get a confirmation prompt before the items were deleted?

**Comment by Nexxol** [comment]
No, I just accidentally dragged it into the recycle bin and all my files were gone. On file explorer it does not allow you to drag it into the recycle bin to prevent this

**Comment by yaichenbaum** [comment]
@Nexxol I reopened this issue and updated the title to better reflect the issue with the missing confirmation dialog. As noted, the expected behavior is to be able to delete these folders (File Explorer lets you delete them as well) but it's only supposed to delete them after confirming the action.

**Comment by gave92** [comment]
Umh the issue here does not seem to be the missing confirmation. He's saying that moving some stuff to the bin results in files being permanently deleted instead..

**Comment by yaichenbaum** [comment]
> Umh the issue here does not seem to be the missing confirmation. He's saying that moving some stuff to the bin results in files being permanently deleted instead (or that they're not restored correctly)..

That's another issue but it's also missing confirmation.

**Comment by gave92** [comment]
Oh right, I though we removed the confirmation when sending to bin but it's only when the relative option in settings is switch off.

**Comment by cinqmilleans** [comment]
@yair100 @gave92 @Nexxol I add the missing confirmation box.
