### ISSUE TITLE
DDS image preview

### ISSUE THREAD

**Issue by SuperWangKai** [files-community/Files#8651]
### Description

DirectDraw Surface image cannot be previewed.
DDS file - https://docs.microsoft.com/en-us/windows/win32/direct3ddds/dx-graphics-dds-pguide

### Steps To Reproduce

Open a folder with dds files.
Use icon views

### Expected behavior

dds file review is expected.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.556

### Windows Version

Windows 11 Pro 21H2 2021/‎11/‎7 22000.556

### Relevant Assets/Logs

none.

**Comment by gave92** [comment]
Merging with #2582
