### ISSUE TITLE
Drag and drop of subtitle files (srt) on videos using MPC-BE doesn't work

### ISSUE THREAD

**Issue by Maxairo** [files-community/Files#8652]
### Description

Drag and drop of srt files from Files app on videos while using MPC-BE media player doesn't work and gives the error "Encountered an improper argument.". Meanwhile, drag and drop from the default Windows explorer works fine. I haven't tried with any other players because I've been using MPC-BE only.
![Screenshot_137](https://user-images.githubusercontent.com/50197993/158058539-ce7c3260-ff78-4778-ba57-bce24b1bb8a6.png)

### Steps To Reproduce

1. Open a video file with MPC-BE media player
2. Open Files app.
3. Locate the srt file.
4. Drag and drop the srt file into MPC-BE.

### Expected behavior

The srt file should be inserted into MPC-BE media player.

### Files Version

Files Version: 2.1.15.0 

### Windows Version

Windows 10 Enterprise 21H2 Build 19044.1586

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8239455/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8239456/debug_fulltrust.log)

**Comment by yaira2** [comment]
@Maxairo thank you for reporting this issue, can you see if it's resolved in the latest release (v2.4.69)?
