### ISSUE TITLE
Why remove the app from winget?

### ISSUE THREAD

**Issue by CodeCubeNeo** [files-community/Files#8653]
### Solution/Idea

Re-add this app to winget, since it is the easiest way for app distribution (mostly updating) on windows, rather than the windows store and manually updating it. If not, can you please state the reason why not?

### Alternatives

The ms store is full of bloat, the manual installation requires manual updating, choco and scoop work, but winget is starting to replace them.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
The app can still be installed through WinGet, alternatively you can use the sideload version of Files https:/files.community/download/stable which has auto update.

**Comment by CodeCubeNeo** [comment]
Can you please tell me, what is the ID of the winget package, since I can't find it. And also your sideload link (https://github.com/files.community/download/stable) is a broken (github 404 page)?

**Comment by yaichenbaum** [comment]
The WinGet package id is `9NGHP3DX8HDX`. 
The download link for the sideload packages is https://files.community/download/stable

**Comment by CodeCubeNeo** [comment]
I would like to ask why is the winget id just some random string and not a descriptive name?
(something like files-community.Files, like for most other apps)? And also how to find it using the winget search command? Also i can't seem to find files on something like https://winstall.app?

**Comment by yaichenbaum** [comment]
@CodeCubeNeo the winget id is provided by the Microsoft Store, I believe you can still search for the app name.

**Comment by CodeCubeNeo** [comment]
I tried to search for "files", " files community", "files app" (using the "winget search {search query}" command and it didnt find anything.

**Comment by Danik1601** [comment]
> > Ok, but what about my second comment, about getting Files its own standalone winget package (not provided with ms store, but the actual winget-pkgs)
> 
> The last time we tried, there were some issues with WinGet not installing the correct dependencies, so they stopped accepting packaged apps like Files.

[Not a problem](https://github.com/microsoft/winget-cli/issues/163#issuecomment-1697930113) since [Winget 1.6](https://github.com/microsoft/winget-cli/releases/tag/v1.6.2631) (Sep. 21, 2023).

However there is [another problem](https://github.com/microsoft/winget-pkgs/pull/146185#issuecomment-2018669881) now.

**Comment by Josh65-2201** [comment]
Try using 
```
https://cdn.files.community/files/stable/Files.Package.appinstaller
```
If that doesn't work you can try using the offline files, first is Files and seconds WinAppSDK. there will have to be updated as Files gets updates.
```
https://cdn.files.community/files/stable/Files.Package_3.3.0.0_Stable_Test/Files.Package_3.3.0.0_x64_arm64_Stable.msixbundle
```
```
https://cdn.files.community/files/stable/Files.Package_3.3.0.0_Stable_Test/Dependencies/x64/Microsoft.WindowsAppRuntime.1.5.msix
```

**Comment by Danik1601** [comment]
> Try using the below, if any of them work please comment which one did.
> 
> ```
> https://cdn.files.community/files/stable/Files.Package.appinstaller
> ```
> 
> If that doesn't work you can try using the offline files, first is Files and seconds WinAppSDK. these will have to be updated as Files gets updates.
> 
> ```
> https://cdn.files.community/files/stable/Files.Package_3.3.0.0_Stable_Test/Files.Package_3.3.0.0_x64_arm64_Stable.msixbundle
> ```
> 
> ```
> https://cdn.files.community/files/stable/Files.Package_3.3.0.0_Stable_Test/Dependencies/x64/Microsoft.WindowsAppRuntime.1.5.msix
> ```

@vikingnope

**Comment by yaira2** [comment]
@vikingnope it's a standard msixbundle so you can use any of the appxpackage commands. See our [documentation](https://files.community/docs/install#:~:text=Install%20via%20PowerShell) for an example.

**Comment by vikingnope** [comment]
will have a look and see what I can do, thanks

**Comment by Kaligula0** [comment]
Maybe this can be reopened? It would be more visible on the list. I almost filed a new issue here to add Files to Winget… 😅

**Comment by Josh65-2201** [comment]
Any issue with Winget would be on Microsoft's side. The links I posted above are standard app installer package which can be installed silently

**Comment by Josh65-2201** [comment]
There is still some issue on Winget side blocking the install without known what the issue is I can't do anything to put Files on there.

**Comment by NicTanghe** [comment]
under what name is it available is it this one ?

```
Found Files [FilesCommunity.Files] Version 3.9.0.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
This package requires the following dependencies:
  - Packages
      Microsoft.VCLibs.Desktop.14
      Microsoft.WindowsAppRuntime.1.5
(1/1) Found Windows App Runtime 1.5 [Microsoft.WindowsAppRuntime.1.5] Version 1.5.8
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://aka.ms/windowsappsdk/1.5/1.5.241107002/windowsappruntimeinstall-x64.exe
  ██████████████████████████████  61.2 MB / 61.2 MB
Successfully verified installer hash
Starting package install...
The installer will request to run as administrator, expect a prompt.
Successfully installed

Successfully verified installer hash
Starting package install...
  ██████████████████████████████  100%
Successfully installed
```

its unclear

**Comment by Josh65-2201** [comment]
Yes.
