### ISSUE TITLE
Extracting to directories that require admin privilage doesn't work

### ISSUE THREAD

**Issue by YamiYukiSenpai** [files-community/Files#8655]
### Description

Earlier, I wanted to paste something to the VLC's skin directory inside `C:\Program Files`.  That doesn't work because  it requires elevated permission to do so, and I don't receive a prompt

### Steps To Reproduce

1. Extract a ZIP'd file to a folder that requires root privilege (i.e. `C:\Program Files\`) 

### Expected behavior

UAC prompt should appear to ask me if I want to elevate.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.556

### Windows Version

Windows 11 21H2 22000.556

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8240299/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8240300/debug_fulltrust.log)

**Comment by YamiYukiSenpai** [comment]
I'd like to expand this problem by mentioning that I can't use 7-Zip to extract them:
![image](https://user-images.githubusercontent.com/13153124/158072834-579cb505-1e33-4e30-afb9-7781d92fbd5e.png)
![image](https://user-images.githubusercontent.com/13153124/158072850-2b33b8bc-1d68-4d41-9ca1-dbc3c8cd4333.png)

**Comment by gave92** [comment]
Scroll down the context menu and you should see the 7zip options.

**Comment by YamiYukiSenpai** [comment]
> Scroll down the context menu and you should see the 7zip options.

I am so blind...
I got so used to the classic one I didn't think of scrolling.

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
