### ISSUE TITLE
Option to disable "simplified" context menu on Windows 11

### ISSUE THREAD

**Issue by YamiYukiSenpai** [files-community/Files#8656]
### What's the Problem?

I really hate Windows 11 context menu, and wish to keep using the classic one with more options.

And for extraction, I'd like to use 7-Zip, but I can't access it from that simplified menu.

### Solution/Idea

An option to disable that menu would be great.  I currently have it disabled via Registry for Windows 11 as a whole.

### Alternatives

N/A

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.556

### Windows Version

Windows 11 21H2 22000.556

### Comments

Classic context menu on Windows 11
![image](https://user-images.githubusercontent.com/13153124/158072707-3b91b4ef-b191-45a7-8331-5b7fdb01c597.png)
No option to use 7-Zip for extracting ZIPed files:
![image](https://user-images.githubusercontent.com/13153124/158072741-952b55c3-a882-4241-b653-dc61ffe6b15e.png)

**Comment by yaichenbaum** [comment]
We don't have plans for this, you can scroll down in the context menu to find the other options.

**Comment by pengweiqhca** [comment]
I don't like win11 context menu, I has restore to win10 context menu in explorer.
