### ISSUE TITLE
Shortcuts for changing folder view

### ISSUE THREAD

**Issue by edu-hilario** [files-community/Files#8657]
### What's the Problem?

The 2 main views of the Files app (Details and Columns) currently (Version: 2.1.15.0) don't have any shortcuts for power users.

### Solution/Idea

Implement shortcuts as the OG Windows Explorer have, like Ctrl+Alt+0 and Ctrl+Alt+6.

### Alternatives

Move the options for these two out of the dropdown button, and instead put them in the primary tools bar.

### Files Version

Version: 2.1.15.0 

### Windows Version

OS Version: 10.0.22000.527

**Comment by yaichenbaum** [comment]
We support ctrl + shift + 1 - 6.
