### ISSUE TITLE
Calculating folder sizes is resource intensive and may cause your CPU usage to increase. [ERROR]

### ISSUE THREAD

**Issue by benniegee** [files-community/Files#8660]
### Description

Can't proceed with the setup because of this error. My laptop is running 32 gb of RAM with an old NVIDIA 1050 Ti. How to solve this?

### Expected behavior

![image](https://user-images.githubusercontent.com/101556945/158145320-647959b3-f42b-4c11-b1a2-132eb383bca3.png)

### Files Version

Version 2.1.15.0

### Windows Version

Windows 22489.1000

### Relevant Assets/Logs

N/A

**Comment by gave92** [comment]
What setup? What are you trying to accomplish?
