### ISSUE TITLE
How does this app replace the real explorer

### ISSUE THREAD

**Issue by Bysid** [files-community/Files#8661]
### Solution/Idea

Firstly we could add symbols of computer , documents, galleria, like that on desktop. if you do that we can use this app as real explorer. Secondly for the rainmeter users or customization lovers we could add widgets of computer documents galleria whatever we want./ a little nice example of widgets
![image](https://user-images.githubusercontent.com/101604902/158272369-feb1775d-6cdb-461d-9d42-5da34fc8d0fa.png)

### Alternatives

Thank you!

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.15

**Comment by Josh-65** [comment]
Files pulls icon from file exploer and you can change them. Icons dost mean it not a real file exploer. As for rainmeter linking it should alrealy work if you call files.exe "path" or use the set as default toggle.
