### ISSUE TITLE
What's something happened on Chinese Language?

### ISSUE THREAD

**Issue by SudaCat** [files-community/Files#8662]
When I planned to localize zh-hans, I found that ALL STRINGS WERE RESET TO ENGLISH. :anguished:
I traced the history of the changes, #8487 changed 3000+ lines. 

**What's happened?**
![image](https://user-images.githubusercontent.com/34740895/158290775-6da62459-3238-4152-87db-fb769acaa333.png)

@yaichenbaum Could do you check the changed again?

**Comment by yaichenbaum** [comment]
@SudaCat we had to reset the strings as part of the recent switch to the MIT license.

**Comment by SudaCat** [comment]
@yair100  So...   we need translate all strings again?   It will be heavy workload...

**Comment by yair100** [comment]
> @yair100 So... we need translate all strings again? It will be heavy workload...

Unfortunately yes, we reached out to the contributors a couple of times, but they didn't respond.
