### ISSUE TITLE
Permanently delete recent files

### ISSUE THREAD

**Issue by jeddrosz** [files-community/Files#8663]
### What's the Problem?

None

### Solution/Idea

Add an option/feature where when you click "remove this item" or "remove all items" from recent files it does that permanently and not temporarily. For example, currently if I open image.jpg and I don't want that particular image to be shown in my recent files, I right click on it and perform the "remove this item."  Then let's say I open image.jpg tomorrow and it will, even though I clicked on "remove this item" from my Recent Files the day before, still appear on my Recent Files. 

### Alternatives

I think this should be either permanent or an option for every user of Files V2 to select.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22572.100

### Windows Version

Windows 11 Pro Version	22H2 Installed on ‎3/‎11/‎2022 OS build	22572.100 Experience	Windows Feature Experience Pack 1000.22572.100.0

**Comment by yaichenbaum** [comment]
You can turn off the recent items widget from the toolbar button flyout.
![image](https://user-images.githubusercontent.com/39923744/158291980-b4590e24-ad45-4aee-a746-9f937fa0a1a2.png)
