### ISSUE TITLE
Bookmarks like google chrome

### ISSUE THREAD

**Issue by rikin-patel435** [files-community/Files#8667]
### What's the Problem?

If the bookmarks feature is there then quickly open a frequently used folder.

### Solution/Idea

If we add bookmarks to the app then it's very fast to access the frequently used folders.
An app like Google Chrome and Clover windows explorer.

### Alternatives

Clover windows explorer

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by gave92** [comment]
Merging with #5468

**Comment by luke-motto** [comment]
Perhaps like the file manager "clover"? It should be possible to import and export the bookmarks to a file. To create bookmarks, the folders or files are dragged and dropped onto the bookmarks bar.
![bookmarks](https://user-images.githubusercontent.com/92398339/216580774-0775db3e-87e4-481c-b51f-3163535566aa.png)
