### ISSUE TITLE
Can't open ZIP/RAR files using Winrar

### ISSUE THREAD

**Issue by Darrel-Santoso** [files-community/Files#8668]
### Description

Files isn't able to open any ZIP/RAR files using Winrar as the default app.

### Expected behavior

Files are opened by Winrar similar to the windows file explorer

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.556

### Windows Version

Edition	Windows 11 Home Single Language Version	21H2 Installed on	‎11/‎1/‎2021 OS build	22000.556 Experience	Windows Feature Experience Pack 1000.22000.556.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8254207/debug.log)

**Comment by Josh-65** [comment]
Does it give an error message?

**Comment by Darrel-Santoso** [comment]
No, it doesn't give an error message. The only way I can open using WinRAR is if I decide to manually click "open with:" and select WinRAR

**Comment by gave92** [comment]
Expected on windows 11. The only fix for now is to install an old winrar version.

**Comment by gave92** [comment]
Misread, could you confirm that the issue is that .rar files don't open in winrar when you double click on them? What does happen instead? Simply nothing?

**Comment by Darrel-Santoso** [comment]
Yes, when I double click on either RAR files or ZIP files they do nothing instead of opening using winRAR

**Comment by Celaro** [comment]
The simple answer is to go to this site (win-rar.com) and download the latest English version 6.11 from 
https://www.win-rar.com/predownload.html?&L=0

Selwyn,
WinRAR Technical Support (since 1994)

**Comment by AaronKatzin** [comment]
I'm having issues opening .zip files too.
My default zip file program is 7zip and either double clicking or right click -> open  on a .zip doesn't work.
No error, but nothing happens.

double clicking or right click -> open in the native file explorer works properly.
I was able to temporarily solve the issue by "repairing" the app in windows Installed App settings (installed apps -> files -> repair).
But the issue returned in a day or less.

**Comment by TenTmavyTypek** [comment]
I got same issue, cant open files with 7zip, and extracting with Files in painfully slow, unusable really.

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.0.0?

**Comment by Darrel-Santoso** [comment]
Nope, got it working fine again
