### ISSUE TITLE
Error when deleting files

### ISSUE THREAD

**Issue by Jacksole** [files-community/Files#8670]
### Description

Received a error message when deleting 1 .mph and 3 .jpg files

### Steps To Reproduce

Selected 4 files and hit the delete key

### Expected behavior

Files deleted with no errors

### Files Version

Version: 2.1.15.0 OS Version: 10.0.19044.1586

### Windows Version

Device name	DW7B3B3 Full device name	DW7B3B3.meansindustries.local Processor	11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz   1.80 GHz Installed RAM	16.0 GB (15.7 GB usable) Device ID	210381D3-6B61-43D8-BD27-048480AFD152 Product ID	00331-20160-00000-AA055 System type	64-bit operating system, x64-based processor Pen and touch	No pen or touch input is available for this display

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8255599/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8255600/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
Is this an issue in the preview version? https://files.community/download/preview
