### ISSUE TITLE
Auto Refresh after copy/rename

### ISSUE THREAD

**Issue by cdnnhicks** [files-community/Files#8671]
### What's the Problem?

After I copy or rename a file in a pane, the changes don't show up until I manually refresh the window. 

### Solution/Idea

It would be nice if a refresh was done after a copy/move or rename was completed.

### Alternatives

No alternative suggested

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by gave92** [comment]
Does this happen on network drives only? Or also on local paths?

**Comment by gave92** [comment]
Thanks for confirming, tracked in #5869
