### ISSUE TITLE
Can't copy file

### ISSUE THREAD

**Issue by Pietro228** [files-community/Files#8674]
### Description

Hi, I can't copy a file to my flash drive. My flash drive is not corrupted and it's working when using Windows file explorer.
Files shows that it has copied instantly (that's impossible - it takes 3 minutes everytime).

### Steps To Reproduce

1. Copy a file (CTRL + C)
2. Go to your flash drive
3. Paste file (CTRL + V)

### Expected behavior

Copy my file to E:/

### Files Version

2.1.15.0 OS Version: 

### Windows Version

Windows 11 10.0.22000.556

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8257286/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8257287/debug_fulltrust.log)

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.0.0?

**Comment by Josh-65** [comment]
Merging with #8972
