### ISSUE TITLE
Far edge scrolling

### ISSUE THREAD

**Issue by Mennaruuk** [files-community/Files#8675]
### What's the Problem?

Windows Explorer has a level of tolerance where the user does not have to necessarily click the scrollbar in the middle. Simply dragging the scrollbar up and down at its edges works equally well.

In Files, the user has to make sure not to move the mouse too far, or else they would not be able to scroll.

This issue isn't necessarily exclusive to Files. The new Microsoft Store for Windows 10 suffers from the same problem: a very thin scrollbar that disallows scrolling at the edges.

https://user-images.githubusercontent.com/52135169/158481956-dbef3835-275f-4306-8b26-9243242212df.mp4

### Solution/Idea

Make it possible to scroll whenever the mouse is dragging the scrollbar—whether in the middle or at the edges.

### Alternatives

It's not really a deal-breaker, Files has plenty to be thankful for. But it does make it more effortful to explore my files. 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to scroll wherever on the scrollbar | Must |

### Files Version

Version: 2.1.15.0

### Windows Version

10.0.19043.1586

### Comments

Appreciate y'all!

**Comment by yaichenbaum** [comment]
@Mennaruuk you should still be able to hold down with the mouse to grab the scroll bar. We encourage opening an issue on the WinUI repository to share your feedback about the scrollbar as it applies to all apps using WinUI.
