### ISSUE TITLE
Pick-up and drop doesn't work properly

### ISSUE THREAD

**Issue by Ojas1804** [files-community/Files#8677]
### Description

When I try to pick up a file and put it in a folder, many times it doesn't give the option of dropping it in the correct folder. This issue doesn't occur every time but it occurs most of the time I try to do it.

### Steps To Reproduce

1. Go to files
2. Create 2-3 folders
3. Create a file
4. Pick up the file with the mouse
5. Try to move it to the desired folder and drop it.

### Expected behavior

I should be able to drop the file in the desired folder in one go.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.556

### Windows Version

Windows 11 Home 21H2 OS build	22000.556

### Relevant Assets/Logs

![Screenshot (206)](https://user-images.githubusercontent.com/74397676/158515023-fc14ffd9-a1d4-48a9-ae7e-1b41c107a450.png)
![Screenshot (206)](https://user-images.githubusercontent.com/74397676/158515108-bb826dd6-a79e-4e5d-b21f-61e1ef898d1c.png)

**Comment by gave92** [comment]
Does refreshing the folder fix the issue?

**Comment by Ojas1804** [comment]
yes

**Comment by devovercome** [comment]
Hey everyone!
I want to fix this issue.

I've reproduced the issue under the `Column View`.
The refresh helps a little, but still glitchy.

Tested on main - [412dd98](https://github.com/files-community/Files/commit/412dd9863a453e28926d935a8b4a93de18fc5db5).

May I proceed with investigation and try to fix that?

**Comment by gave92** [comment]
Go ahead 👍

**Comment by yaichenbaum** [comment]
This should be resolved in `main`.
