### ISSUE TITLE
Properties bottom

### ISSUE THREAD

**Issue by mustafaallawi** [files-community/Files#8678]
### Description

Properties bottom don't work for all main partitions and subfolders .

### Expected behavior

not sure 

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22572.201

### Windows Version

W 11 22572.ni

### Relevant Assets/Logs

![Screenshot 2022-03-16 134602](https://user-images.githubusercontent.com/74121757/158574640-d750f4bd-696e-4f7d-8155-842a769ea718.png)

**Comment by gave92** [comment]
Thanks for the report. Closing as apparently it's a bug in the latest windows 11 build.
