### ISSUE TITLE
Themes for Files don't show up in the Settings dialog

### ISSUE THREAD

**Issue by Hidetoshi6721** [files-community/Files#8679]
### Description

![image](https://user-images.githubusercontent.com/85873175/158577338-00acdcc8-1537-469a-a6a8-2977868f73b6.png)
A picture is better than a thousand words.

Also, the Themes folder is empty too.

### Steps To Reproduce

1. Open Files.
2. Click on the Settings icon.
3. Under Appearance, click the down-facing arrow of Custom Themes.
4. Only one theme is present, that's the default one.

### Expected behavior

A wide variety of themes should show up for the explorer's customization.

### Files Version

2.1.15.0

### Windows Version

Windows 10 21H2 19044.1586

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8261555/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8261556/debug_fulltrust.log)

**Comment by gave92** [comment]
Thanks for the report. We're aware of the issue. You'll need to reset the app from windows settings.
