### ISSUE TITLE
Default action for already existing files

### ISSUE THREAD

**Issue by DAmNRelentless** [files-community/Files#8680]
### What's the Problem?

When you want to replace a set of files in a folder, you will get the pop-up where you have to choose the action for each file individually.
`replace`, `new name`, `skip`

If I have 30 files, that's very tedious especially since the default option for all of them is `new name`.

### Solution/Idea

Have a dropdown menu above the individual files to select the default action.
Could be placed here:
![](https://i.imgur.com/mOCqel8.png)

### Alternatives

Choose `replace` for each file individually or delete all the contents first before you replace which is also very tedious.

### Priorities

Should

### Files Version

2.1.15.0

### Windows Version

Windows 11 Pro 21H2 22000.556

**Comment by Josh-65** [comment]
Merging with #5645. You can currently do ctrl + a then select a option in the box like normal.

**Comment by DAmNRelentless** [comment]
Oh, I wasn't aware of that. Pretty hidden. Thanks for the fast response!
