### ISSUE TITLE
Glass Theme

### ISSUE THREAD

**Issue by Aramrahgozar** [files-community/Files#8681]
### What's the Problem?

Hi
I use the glass theme from the setting and it looks great, but on deactivate mode, the glass look disappears. It would be great if in both active and deactivate mode, the glass look has appeared.
Another suggestion; If there would be an option for changing the "transparency". For example, right now I think it's about only 30-40% transparent. It would be great if this can goes to 100%.
Thanks,

### Solution/Idea

-

### Alternatives

-

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.15.0

### Windows Version

Windows 11 21H2 (22000 . 556)

**Comment by Josh-65** [comment]
This is a windows limitation as it applys the effect.
