### ISSUE TITLE
Properties bug

### ISSUE THREAD

**Issue by swineosaur** [files-community/Files#8685]
### Description

When right clicking on a drive and selecting properties nothing opens on the latest dev version, same as the last version from last week released by MS prior to "cumulative updates".

### Steps To Reproduce

Open files, and right click on a HDD/SDD, nothing happens when on the latest DEV build.

### Expected behavior

Nothing happens.

### Files Version

2.1.15.0

### Windows Version

Win 11 22572.201

### Relevant Assets/Logs

As stated above, launch Files while using the latest dev version, right click a hdd/ssd and select properties and nothing happens, beta/rp work fine.

**Comment by gave92** [comment]
Thanks for the report. We are aware of this issue. Merging with #7983.
