### ISSUE TITLE
Unable to set Alacritty as default terminal

### ISSUE THREAD

**Issue by menguele** [files-community/Files#8686]
### Description

Editing terminal.json and adding:
`{
      "name": Alacritty",
      "path": "alacritty.exe",
      "arguments": "",
      "icon": ""
}`
results in nothing as Files apparently rewrites the file anyway, even when setting terminal.json as read-only.

### Expected behavior

Edit terminal.json, whithout Files rewriting it even if it is marked as read-only, and Alacritty showing up as a selectable terminal and being able to set it as default.

### Files Version

Versão: 2.1.15.0 OS Version: 10.0.19042.1586

### Windows Version

Windows 10 20H2 19042.1586

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8279901/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8279903/debug.log)

**Comment by gave92** [comment]
There's a missing quote before Alaccrity

**Comment by menguele** [comment]
> There's a missing quote before Alacritty:
> `{ "name": "Alacritty", "path": "alacritty.exe", "arguments": "", "icon": "" }`

Strange, I remember putting those before as I tried many times, even restarting my pc, but thank you so much.
