### ISSUE TITLE
Reduce margin/padding size

### ISSUE THREAD

**Issue by MonJamp** [files-community/Files#8687]
### What's the Problem?

I've noticed that there is a lot of spacing around UI elements.

For example the examples below, I have both `explorer` and `files` windows resized to the same size.
When viewing a folder, there is so much space around each item in the directory that `explorer` shows double the amount of items:
![listview](https://user-images.githubusercontent.com/7116269/158737123-a837ffbd-4af8-40e1-9c53-12430f5a6d21.PNG)

For the properties window, I was unable to resize it all the way to match `explorer`'s window. In `Files` you can see that the attributes are cut off. There's not much information shown in the properties window so I think it would be designed better if all the information could be seen at the minimum window size for this screen. 
![properties](https://user-images.githubusercontent.com/7116269/158737126-94a9797e-d9b0-423d-8aad-ce8d64585c36.PNG)

Also in a tabbed layout, all the tabs should be visible. Tabs are used to save visual space and make it easier for navigation. I think it's a bit silly to have a three dotted menu next to the tab headers. If anything the remaining tabs would look better if they were shown underneath. As shown here:
![tabs](https://user-images.githubusercontent.com/7116269/158738016-4f23d46f-d0e4-473c-bf7e-51cd432d32c3.PNG)

### Solution/Idea

Personally, I think the padding/spacing around most UI elements should be 1/2 - 1/3 of what they are at currently.

### Alternatives

An alternative would be to make padding a configurable setting.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Allow users to use view directories more effectively | Could |
| This change would improve the overall design language of the application | Could |
| This change would also make it easier to incorporate more design elements without being too bloated | Could |

### Files Version

Version: 2.1.15.0

### Windows Version

Windows 10 21H2 19044.1586

**Comment by gave92** [comment]
Merging with #1940
