### ISSUE TITLE
Folder Sharing inside Properties

### ISSUE THREAD

**Issue by cerahmed** [files-community/Files#8688]
### What's the Problem?

I'm not sure if it's hidden somewhere, but I haven't seen a way to modify the sharing of _folders_ (not files).
This is a very big part of Window's Explorer that I use frequently .. so I wonder if it's in the features list to be included.

<img width="274" alt="Screenshot 2022-03-17 095925" src="https://user-images.githubusercontent.com/21166481/158754491-f1fdd00f-ac6e-4c32-ba54-840ad0b04e2f.png">

### Solution/Idea

Adding Folder Sharing Tab in the Properties Menus.

### Alternatives

N/A

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.15.0

### Windows Version

Windows 11 Build 22000.556

**Comment by Josh-65** [comment]
Merging with #5941
