### ISSUE TITLE
Dropdown in search

### ISSUE THREAD

**Issue by lawrencevasseur** [files-community/Files#8689]
### Description

In the search box, after a search, the results appear in a dropdown. However, long titles are not displayed in full, so aborted.

### Steps To Reproduce

Go Search
Search for a file with a long name
Look at the results

### Expected behavior

Long filename is broken

### Files Version

21150

### Windows Version

Windows 11 22000.556

### Relevant Assets/Logs

![Schermafbeelding 2022-03-17 083133](https://user-images.githubusercontent.com/101792516/158760279-2506805a-96f0-41a2-9d70-de8f50cc8471.png)

**Comment by Josh-65** [comment]
There isnt an issue here, there not supost to be. It's a quick access/preview. If you want to full file name press enter then it show the results like normal files and folders.
