### ISSUE TITLE
[BUG - critical] Files does not open properties of file or a folder

### ISSUE THREAD

**Issue by rihards-simanovics** [files-community/Files#8690]
### Description

Unable to open file/folder properties through the context menu.
Already tried repairing, resetting and uninstalling>reinstalling the app.

See the video below:

https://user-images.githubusercontent.com/52106095/158772932-89dd38c4-3851-487e-8bef-2984c39dfc7c.mp4

### Steps To Reproduce

right-click on any file or folder within Files app
try and open properties.
the 

### Expected behavior

Properties window opens.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22572.201

### Windows Version

Edition	Windows 11 Business Version	22H2 Installed on	‎12/‎03/‎2022 OS build	22572.201 Experience	Windows Feature Experience Pack 1000.22572.201.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8283148/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8283149/debug_fulltrust.log)

**Comment by gave92** [comment]
Thanks for the report. Apparently it's a bug of the latest windows 11 build.
@yair100 were you able to check if it's something we're supposed to fix in Files? Or if we just wait for a fix from MS?

**Comment by rihards-simanovics** [comment]
@gave92, it's been a while since I've noticed it, and it existed for two or three win11-dev builds if my memory is not failing me. I would check windows APIs and see if something has changed there, but tbh debug log would probably be more helpful.

**Comment by gave92** [comment]
Also #7983, you're not just the latest build.

**Comment by rihards-simanovics** [comment]
@gave92, in that case, it might be better to re-open the ticket so this issue is visible?

**Comment by gave92** [comment]
I'm gonna pin issue #7983 which is the same 👍

**Comment by yaichenbaum** [comment]
> @gave92, it's been a while since I've noticed it, and it existed for two or three win11-dev builds if my memory is not failing me. I would check windows APIs and see if something has changed there, but tbh debug log would probably be more helpful.

It's been an issue for the last three builds and we're going to have to wait for a fix, but in the meantime, you can downgrade to a stable version of Windows in order for this to work again.

**Comment by rihards-simanovics** [comment]
> > @gave92, it's been a while since I've noticed it, and it existed for two or three win11-dev builds if my memory is not failing me. I would check windows APIs and see if something has changed there, but tbh debug log would probably be more helpful.
> 
> It's been an issue for the last three builds and we're going to have to wait for a fix, but in the meantime, you can downgrade to a stable version of Windows in order for this to work again.

@yair100 Nah, don't worry. As you've probably seen in the video, I've got a workaround as I know I am working within dev env and with dev software. I would say that having a button such as the one I got in the context menu (Open with "Explorer") is suitable for these types of issues. Perhaps you can take the code from here ([open in explorer.txt(.ini)](https://github.com/files-community/Files/files/8286710/open.in.explorer.txt)) and integrate it into files?
