### ISSUE TITLE
希望能够接管 Win+E 组合键唤醒

### ISSUE THREAD

**Issue by NULL204** [files-community/Files#8691]
### What's the Problem?

无法使用 Win+E 组合键唤醒，大大降低体验

### Solution/Idea

我百度了一下，有人说在 C:\WINDOWS\system32\shell32.dll ，可以尝试修改这个文件
我也找到了 winhotkey 工具来修改快捷键
可以参考一下

### Alternatives

鬼知道。。。

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

版本: 2.1.15.0 OS Version: 10.0.22000.556

### Windows Version

Windows 11 专业工作站版 21H2 22000.556

**Comment by gave92** [comment]
The sideload version has the option to open on Windows+E (in Settings > Experimental)
