### ISSUE TITLE
Occasionally turns off

### ISSUE THREAD

**Issue by abelokoj-github** [files-community/Files#8693]
### Description

**Kindly add an potion to reorder pinned items on the favorite panel.** Currently, you are not able to reorder the items that have been pinned on the left pane under favorite menu.

I am not sure why but this app seems to turn off occasionally.

Another thing I notice is that the preview pane is not as good as what you have on the main Windows file app. I am not sure why this is so, but there seems to be too much extra space which I have no Idea how to turn off.

**_Is there  a way to make the pdf look bigger and eliminate book title from the bottom?_**

![image](https://user-images.githubusercontent.com/69094732/158910530-cf200449-5a42-45f0-8524-8a4196831745.png)

### Steps To Reproduce

This usually happens whenever many tabs are opened

### Expected behavior

The app is supposed to run without any of these mentioned issues.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.556

### Windows Version

Windows version 21H2  OS Build 22000.556

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8295264/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8295265/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
You can reorder the favorites by right clicking on them and using the rearrange options.
