### ISSUE TITLE
Files crashes when navigating to the Downloads Directory

### ISSUE THREAD

**Issue by CEbbinghaus** [files-community/Files#8697]
### Description

When navigating back to the Downloads directory the application just crashes.

### Steps To Reproduce

1. Open Files
2. Naviate to the Downloads Directory
3. Navigate to another Directory and leave for a while (I think it happens with time but its happened for other reasons too)
4. Navigate back to the Downloads Directory

at that stage it should then Crash

### Expected behavior

To just show the Downloads Directory and its contents

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.493

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎17/‎07/‎2021 OS build	22000.493 Experience	Windows Feature Experience Pack 1000.22000.493.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8301782/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8301785/debug_fulltrust.log)

**Comment by gave92** [comment]
Do you have the "show folder sizes" option enabled under Experimental? Does it crash if you turn that off?

**Comment by gititaly** [comment]
Hello, I have the same problem... I think it depends on the "show folder sizes" option because when it's turned off it doesn't crash.
Windows 11 Home: OS build 22000.556 Experience Windows Feature Experience Pack 1000.22000.556.0

**Comment by gave92** [comment]
Merging with #8646, @CEbbinghaus if you could confirm that turning off the "show folders size" option fixes the issue, it would be great.

**Comment by CEbbinghaus** [comment]
@gave92 will try it out and report back but I do have it on.
