### ISSUE TITLE
Add Pin tab feature

### ISSUE THREAD

**Issue by VanDng** [files-community/Files#8699]
### What's the Problem?

The problem comes from how I use Files.

I don't like to keep opening and closing tabs. I always have a few tabs opening certain folders with Column view mode, so I can easily go in and out, I want them to be there all the time.

I also have tabs for random access, but I constantly open and close them when I am done. The problem is I usually mistakenly close my always-there-tabs if I do not pay attention.

### Solution/Idea

I want to add a context menu item Pin tab and Unpin tab.

![Demo](https://user-images.githubusercontent.com/20492454/158927477-4e719f15-b16d-49f2-ad09-9b610510f076.png)

If a tab is pinned, the close button is hidden, I can not click the close button and the Ctrl F4 also does not work.

_If the idea is okay, then check out my [PR ](https://github.com/files-community/Files/pull/8695)here._

### Alternatives

No, I don't have any alternative.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end-users to accomplish better use of Files | Could |

### Files Version

Version: 2.1.15.0

### Windows Version

Windows 11

**Comment by yaichenbaum** [comment]
Is this equivalent to the pin tab feature in Edge?

**Comment by VanDng** [comment]
I did not refer to the pin tab feature in Edge but yeah it seems equivalent.
I think it's better to have the folder's name displayed on pinned tabs, Edge does not have that.

**Comment by yaichenbaum** [comment]
@VanDng I think displaying the name is a nice improvement. Can you rename the feature to "Pin tab" so that it's familiar for users coming from Edge?

**Comment by VanDng** [comment]
Okay. I renamed it to Pin tab.

**Comment by yaichenbaum** [comment]
Does the option to reopen recently closed tabs help with the issue of accidentally closing tabs?
