### ISSUE TITLE
Quicklook integration is broken

### ISSUE THREAD

**Issue by bobarakatx** [files-community/Files#8700]
### Description

Quicklook integration is broken and it has been for a while.

### Expected behavior

pressing the space bar should bring up quicklook to view files. quicklook is installed (store version) and running.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.556

### Windows Version

22000.556

### Relevant Assets/Logs

.

**Comment by yaichenbaum** [comment]
Can you upload the log Files?

**Comment by 512DuncanL** [comment]
Works fine for me with windows 10 version 19043.1586, files version 2.15.15.0, and quicklook version 3.7.1.0
