### ISSUE TITLE
Side bar doesn't load correctly

### ISSUE THREAD

**Issue by bobarakatx** [files-community/Files#8701]
### Description

Side bar doesn't load open entries correctly. I have to collapse and reopen them to load,

### Expected behavior

they should just load

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.556

### Windows Version

22000.556

### Relevant Assets/Logs

.

**Comment by yaichenbaum** [comment]
We need a little more information from you in order to investigate this issue, please reopen this issue once you have filled out the issue template.
