### ISSUE TITLE
Add SynologyDrive to Cloud Drives section

### ISSUE THREAD

**Issue by rkd-me** [files-community/Files#8703]
### Solution/Idea

I would like to see my `SynologyDrive` sync folder under the `Cloud Drives` section.

### Alternatives

We can pin `SynologyDrive` folder to `Favourites`, but it's just workaround.

### Files Version

2.1.15

### Windows Version

120.2212.4170.0

**Comment by gave92** [comment]
Merging with #8084, #6637
