### ISSUE TITLE
Set Files as defaul file explorer

### ISSUE THREAD

**Issue by josueluna** [files-community/Files#8704]
### What's the Problem?

I'd like to have an option to set files as the default file explorer, I haven't been able to do so. 

### Solution/Idea

An option on the settings menu to set Files as the default file explorer. 

### Alternatives

N/A

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.15.0

### Windows Version

none

### Comments

None

**Comment by yaichenbaum** [comment]
The option to make Files the default is only available in the sideload version available on our website.
