### ISSUE TITLE
Feature: Add menu option to paste items as a shortcut when holding down shift key

### ISSUE THREAD

**Issue by nathanrboyer** [files-community/Files#8705]
### What's the Problem?

I have a "Paste shortcut" button under the right click menu in File Explorer that allows me to copy a file or folder and then paste a shortcut to that file or folder somewhere else. I don't see that option in Files.

Currently you have choose "Create shortcut" under the right click menu. Then cut and paste the new shortcut file somewhere else. This is an unnecessary extra step. Why would I want the shortcut in the same folder as the original file/folder?

### Solution/Idea

Replace "Create shortcut" with "Paste shortcut" in right click menu.

### Alternatives

Add "Paste shortcut" alongside "Create shortcut", or only replace "Create shortcut" with "Paste shortcut" when a file/folder is stored in the clipboard.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish faster shortcut management. | Must add the "Paste shortcut" option.|

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.556

### Windows Version

Windows 11 Pro 21H2 22000.556

### Comments

File Explorer Menu
![image](https://user-images.githubusercontent.com/65452054/159075534-6e7f6810-a48c-4bd7-a062-fddf5d33e612.png)

**Comment by yaira2** [comment]
Thank you for your feedback.

**Comment by hishitetsu** [comment]
Currently paste while holding down Shift is assigned to paste into the selected folder. So it would be better to assign paste while holding down Alt to paste as a shortcut, as drop while holding down Alt is also assinged to create a shortcut.

**Comment by hishitetsu** [comment]
Ok. We can still assign Alt+Ctrl+V as a hotkey.

**Comment by yaira2** [comment]
Support for pasting items as shortcuts will be included in the next release.
