### ISSUE TITLE
Open folder location is delayed when Files is set as the default file manager

### ISSUE THREAD

**Issue by arytapermana** [files-community/Files#8706]
### Description

when i open the folder location from a file i downloaded on MS Edge browser, files v2 delay about 5 to 8 seconds to open the folder location. I know it's still experimental but, maybe this feedback can help fixing this.

### Steps To Reproduce

1. download file on MS Edge
2. klik downloads files (showing all downloaded files)
3. klick icon open folder location for downloaded files
**_4. waiting/delay 5 to 8 seconds_**
5. files v2 open directory of my downloaded files

### Expected behavior

1. download file on MS Edge
2. klik downloads files (showing all downloaded files)
3. klick icon open folder location for downloaded files
5. instantly files v2 open directory of my downloaded files

### Files Version

Version: 2.1.15.0 OS Version: 10.0.19044.1586

### Windows Version

Edition	Windows 10 Pro Version	21H2 Installed on	‎24/‎01/‎22 OS build	19044.1586 Experience	Windows Feature Experience Pack 120.2212.4170.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8308354/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8308355/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by alishtamimi** [comment]
YES. 

> Is this still an issue in the preview version? https://files.community/download/preview

**Comment by yaichenbaum** [comment]
In the preview build, how much of a difference is there between "open file location" and a standard launch?

**Comment by alishtamimi** [comment]
I'm going to test it more, but using edge to open file location from the download drop menu, it takes more than 8 seconds. It is so slow.

**Comment by alishtamimi** [comment]
TBH, this deal breaker bug is holding me back from using the Files as default.

**Comment by alishtamimi** [comment]
Any progress on this bug? @yair100

**Comment by yaichenbaum** [comment]
Did you get a chance to test the difference between a standard launch and "open file location"?

I also recommend removing the stable version before installing the preview version and making it the default.

**Comment by alishtamimi** [comment]
Yes, I did that. But nothing helped. It takes so much time to open file location from edge download section. 
@yair100

**Comment by yaichenbaum** [comment]
Did you time the difference between the different versions?

**Comment by alishtamimi** [comment]
I'm sorry I didn't track the time difference between previous versions. 
But what I can tell that it is as slow as before. 
@yair100

**Comment by alishtamimi** [comment]
The latest prerelease version takes about 11 seconds to open the file location, but it sometimes opens in 4.5 seconds.

**Comment by yaichenbaum** [comment]
@alishtamimi we made some improvements in v2.3.57 to improve startup speed and we'll continue doing what we could with #4180. The biggest boost will happen when Microsoft adds Native AOT support to WinAppSdk but that's not something we have control over.

**Comment by yair100** [comment]
@arytapermana @alishtamimi we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
