### ISSUE TITLE
Option to enable windows 10 Ribbon Interface in "FIles"

### ISSUE THREAD

**Issue by Yoad1704** [files-community/Files#8708]
### What's the Problem?

Hi, my "problem" is in windows 11 - the new ribbon interface in the file explorer, in my opinion, is garbage and I even replaced it in the normal file explorer but unfortunately, there isn't an option to do so in "Files". Moreover - there is an option in file explorer to press right click and it will open the windows 11 context menu there but in "Files" there isn't an option to do so. I think if will you bring these features to "Files" many people will love it. Note related to both features: In the first feature I suggested, I asked to develop an option that adds something in "Files" which is in there but not in that specific style (Windows 10 style), and in the second I asked to add something that there isn't there even in its windows 11 shape and after the addition of it to add the Windows 10 style like the first feature.

### Solution/Idea

Add an option to do what I described above.

### Alternatives

Since the feature isn't in "FIles" I started using file explorer again but I'll switch again to "Files" when the feature will be there.

### Priorities

| Capability | Priority |

| This proposal will allow developers to get more audience that prefers windows 10 style file explorer like I'm

### Files Version

2.1.15.0

### Comments
![image](https://user-images.githubusercontent.com/100999533/159123630-01cc91eb-5f52-4db9-b69b-86414e5ae6f4.png)

![תמונה1](https://user-images.githubusercontent.com/100999533/159121566-18a57baa-5db0-4178-9572-5ce0e2fab792.png)

**Comment by Josh-65** [comment]
WinUI doesnt have a ribbon other then the bar that avaible below the path and search bar in files and its not somthing thats going to be implemented.

**Comment by Yoad1704** [comment]
No, take a look at the second picture: this shows windows 10 style ribbon that was changed to the current and it still can be applied in the normal file explorer (using reg edit) but not in "FIles". That's why I'm asking for this feature in "Files"

**Comment by Josh-65** [comment]
The files team have said in other request that they are not going to implement the ribion becuase it doesnt fit the style and is proberly not easily doable. Files is not file explorer. 
If there a option you want from the ribbon to be on files version of the tool bar you should make an feature request for it. Check for already open ones first.
