### ISSUE TITLE
File View Request 

### ISSUE THREAD

**Issue by OnyxStreaming** [files-community/Files#8709]
Hello, Fantastic rework of the file explorer i must say. i would however like to ask if it would be possible to have one view feature that the windows file explorer has.... the option to view files in a list view. 
i work with a lot of files in my line of work and having this layout helps so much to see and find things alot easier when using so many files.

**Comment by gave92** [comment]
Thanks for your interest in Files! Feature request tracked in #2509.

**Comment by yaira2** [comment]
@OnyxStreaming thank you for your patience, I'm excited to share that a List View layout will be included in the next release.
