### ISSUE TITLE
Follow File Explorer naming preferences when creating a shortcut

### ISSUE THREAD

**Issue by Xiarno** [files-community/Files#8711]
### What's the Problem?

I modified the Regedit [using this tutorial](https://thegeekpage.com/change-text-shortcut-shortcuts-created-windows-10/) so that each time I do a shortcut, the "- shortcut" suffix that is originally appended at the end does not appear anymore.

### Solution/Idea

Have "Files" uses the same system as "Files explorer".

### Alternatives

N/A

### Files Version

Version: 2.1.15.0 OS Version: 10.0.19042.1586

### Windows Version

20H2

### Comments

Not sure of the technical stuff, it was proposed to me by @Josh-65

**Comment by Josh-65** [comment]
To add Files should follow how file explorer renames (if possible) or add an option to not add "- shortcut".

**Comment by yaira2** [comment]
I opened a PR for this but I'd like to get some additional feedback before merging it.
