### ISSUE TITLE
Uninstalled Files, now I can't use Explorer

### ISSUE THREAD

**Issue by zohozer** [files-community/Files#8713]
### Description

I just uninstalled Files into my Windows10 machine, I do rebooted the machine and I can't no longer use the Windows Explorer as it should. Instead I do get an error message: "Application not found".

How I can restore Windows Explorer back?

### Expected behavior

I expect to be able to use Windows Explorer againd after uninstalling Files.

### Files Version

2.1.15

### Windows Version

Windows10

### Relevant Assets/Logs

No log file.

**Comment by gave92** [comment]
You'll need to run this script (make sure to save it as a ".reg" file):
https://raw.githubusercontent.com/files-community/Files/main/src/Files.Launcher/Assets/FilesOpenDialog/UnsetFilesAsDefault.reg
Please let us know if it solves the issue.

**Comment by zohozer** [comment]
Thank you for the answer. The .reg file fixed the issue.

**Comment by rr-da-cat** [comment]
even after the script, win+e works, but it given an error Application not found
![image](https://user-images.githubusercontent.com/97874600/167099365-a59bdd3d-88a5-4a02-84aa-830dadbd2c15.png)
and i cant open any other folder... i ran the script BEFORE uninstalling, but still shows error.

**Comment by bronze** [comment]
I have the same issue. Just uninstalled it and now win+e gives me the `Application not found` error.
The link above isn't working either.

**Comment by rr-da-cat** [comment]
@bronze USE THE UPDATED SCRIPT.. thats old... @yaichenbaum replied and sent it
Here:
Windows Registry Editor Version 5.00

; Revert Default (new)
[HKEY_CLASSES_ROOT\Folder\shell\explore]
"LaunchExplorerFlags"=dword:00000018
"MultiSelectModel"="Document"
"ProgrammaticAccessOnly"=""

[HKEY_CLASSES_ROOT\Folder\shell\explore\command]
@=-
"DelegateExecute"="{11dbb47c-a525-400b-9e80-a54615a090c0}"

[HKEY_CLASSES_ROOT\Folder\shell\open]
"MultiSelectModel"="Document"

[HKEY_CLASSES_ROOT\Folder\shell\open\command]
@=hex(2):25,00,53,00,79,00,73,00,74,00,65,00,6d,00,52,00,6f,00,6f,00,74,00,25,\
  00,5c,00,45,00,78,00,70,00,6c,00,6f,00,72,00,65,00,72,00,2e,00,65,00,78,00,\
  65,00,00,00
"DelegateExecute"="{11dbb47c-a525-400b-9e80-a54615a090c0}"

; Revert Default (old)
[HKEY_CURRENT_USER\SOFTWARE\Classes\Directory\shell]
@=-

[-HKEY_CURRENT_USER\SOFTWARE\Classes\Directory\shell\openinfiles]

; Revert Win+E
[-HKEY_CURRENT_USER\SOFTWARE\Classes\CLSID\{52205fd8-5dfb-447d-801a-d0b52f2e83e1}]


Copy paste above into a .reg file and execute, restart computer and done
