### ISSUE TITLE
Bug: Folder size doesn't update within tags

### ISSUE THREAD

**Issue by austin-dudzik** [files-community/Files#8714]
### Description

When navigating from a folder into a tag, the folder size near the bottom does not update to reflect the total size of files within the tag, but instead keeps the size value from the previous folder.

i.e. If I navigate to the Downloads library with a size of 119.33 GB and then navigate into a tag, the tag will display as having a size of 119.33 GB (the previous value), regardless of the number or size of files within the tag.

### Steps To Reproduce

1. Open Files
2. Navigate to a folder (i.e. Downloads)
3. Navigate to a tag
4. Observe file size near bottom

### Expected behavior

The folder size near the bottom should update once navigating into a tag.

### Files Version

Version: 2.1.21.0 OS Version: 10.0.22000.556

### Windows Version

Windows 11 21H2 22000.556

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/65981261/159145598-03b5449c-0907-41ad-b87b-a2e7337d8642.png)

**Comment by nilufer001** [comment]
Hello, I am Nilüfer Ballı, a 4th year computer engineering student. As part of the software engineering course project, we were asked to do a bug fix on github, if you allow me, I would like to solve this error too.

**Comment by yaira2** [comment]
@nilufer001 are you still interested in looking into this?

**Comment by yaira2** [comment]
@austin-dudzik I can't reproduce this issue on v2.4.70, can you see if it's fixed for you as well?

**Comment by austin-dudzik** [comment]
Looks to now be resolved.
