### ISSUE TITLE
When dual pane mode is on, double clicking folders should open them in the corresponding pane

### ISSUE THREAD

**Issue by ezxpro** [files-community/Files#8715]
### What's the Problem?

When I'm in the dual pane mode, whenever I double click a folder, instead of opening that folder in the pane I'm already at, it's opened in a new tab, which is cumbersome.

see:
![image](https://user-images.githubusercontent.com/15344931/159146320-787294e8-eec7-4e86-b085-046407e2a8a5.png)

Here for example if I double click the "Blues" folder, instead of opening it in that same pane, the folder is opened in a different tab altogether, plus it switches to that tab apparently, taking me away from whatever I was doing.

### Solution/Idea

No new tab should be created, what I double click on the left pane should open in the left pane, likewise in the right pane.

### Alternatives

I can't think of an alternative, this seems pretty straightforward and is done this way in any file manager with 2 panes that I know of.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.556

### Windows Version

Windows 11 21H2 22000.556

**Comment by yaichenbaum** [comment]
@ezxpro can you upload a screen recording?

**Comment by gave92** [comment]
Isn't there an option to always open a folder in a new tab? Please make sure that is turned off.

**Comment by ezxpro** [comment]
> Isn't there an option to always open a folder in a new tab? Could you confirm that the option is _off_?

Actually, there's an option to "Always open new tabs in dual panel mode", so regardless of that option being on or off the behavior I described is in effect.
![image](https://user-images.githubusercontent.com/15344931/159163061-71a9a533-b3e6-4f76-9776-d532fd67e087.png)


> @ezxpro can you upload a screen recording?

I'm afraid I cannot.

**Comment by gave92** [comment]
Thre's also the "open folders in new tab" option under Settings > Preferences > Files and Folder. Could you check if that i soff as well?

**Comment by ezxpro** [comment]
> There's also the "open folders in new tab" option under Settings > Preferences > Files and Folder. Could you check if that is off as well?

Yeah, that one was checked, turning it off did the trick.
Thanks.
