### ISSUE TITLE
Expand drag area on item coloums

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#8722]
### What's the Problem?

Trying to change the width on item coloums really difficult as the drag area is very small

![image](https://user-images.githubusercontent.com/26977075/159191561-711f6d3e-8846-4b43-b5f6-640d4b741e7e.png)

### Solution/Idea

Widen the drag area

### Alternatives

*

**Comment by Josh-65** [comment]
So i have notice it bigger then shown sometimes. When the columns not highlight it still dragable but the drag icon isnt shown. Other times it doesnt do it at all and others will have a good amount with the icon showing it can be draged.

**Comment by itsWindows11** [comment]
![image](https://user-images.githubusercontent.com/81253203/163778621-1041847a-dffc-4c9b-ae2b-e0f6153debe8.png)
Does this look good?

**Comment by yaichenbaum** [comment]
This issue should be resolved with #8947
