### ISSUE TITLE
[Feature request] Quick access support

### ISSUE THREAD

**Issue by LifeIsStrange** [files-community/Files#8724]
### Description

Windows official explorer has a quick access mode
https://support.microsoft.com/en-us/windows/pin-remove-and-customize-in-quick-access-7344ff13-bdf4-9f40-7f76-0b1092d2495b
It shows the most recently accessed/modified folders/files.
It is extremely convenient for quickly finding what you're looking for.

I have not found a similar feature in Files, am I mistaken?

**Comment by yaichenbaum** [comment]
We don't have plans for quick access but we plan on a recent items page.
