### ISSUE TITLE
Set a fix header for tabs

### ISSUE THREAD

**Issue by VanDng** [files-community/Files#8726]
### What's the Problem?

It's not a problem but an improvement, I think.

I usually have multiple tabs that keep opening with Column view mode, so I can quickly switch to a tab and go in and out.

In a tab, when I select a folder, the name of the selected folder is shown on the header. I think it is reasonable behavior for not-Column-view modes, but it seems not right for Column view mode.

I believe people using Column view mode consider a tab to be more like a group or a collection where its name should be fixed. If the header is changed according to the selection, it only takes a fraction of a second to determine what tab it is when they want to switch back but it is a bit frustrating.

![image](https://user-images.githubusercontent.com/20492454/159229713-5ea58e69-cb5a-48b9-9c0e-56ca06ad582f.png)

### Solution/Idea

I have two ideas:

1/ In Column view mode, the header is always the root folder name.
2/ Add a feature allowing users to set a custom header. There will be a new menu context item when a user right-clicks the header.

Personally, I prefer option 2.

### Alternatives

No alternative.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow users to accomplish a better experience | Could |

### Files Version

Version: 2.1.13.0 OS

### Windows Version

Windows 11

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
I personally prefer the current behavior where the tab shows the focused column. Let's keep this open for discussion.

**Comment by yaichenbaum** [comment]
Merging with #9980
