### ISSUE TITLE
Memory increases continually when changing folder in Column view mode

### ISSUE THREAD

**Issue by VanDng** [files-community/Files#8727]
### Description

I opened a folder in Column view mode and just continually selected different folders.
![image](https://user-images.githubusercontent.com/20492454/159242990-f8ef0c77-9b35-4e0a-a7ed-c22f1be174eb.png)

I observed that the memory increases each time I select a folder no matter it is a new folder or a folder I had visited before. It increased from ~80MB to ~400MB in ~4 minutes
![image](https://user-images.githubusercontent.com/20492454/159243485-aa46fd6b-346b-4416-8e54-0b99073b8b61.png)

### Steps To Reproduce

1. Open a folder in Column view mode.
2. Select random child folders.
3. Observe the memory.

### Expected behavior

Memory should be released when I close a tab or folder, the wave should have gone up, down, up, down,...

### Files Version

Version: 2.1.13.0 OS Version: 10.0.22000.556

### Windows Version

Windows 11

### Relevant Assets/Logs

N/A

**Comment by VanDng** [comment]
If the bug is confirmed, you guys can assign it to me. Or you guys can help to fix it ~

**Comment by yaichenbaum** [comment]
There are a number of memory leaks in the code base and while there isn't one way to fix it, there is an ongoing effort to reduce the memory usage.
