### ISSUE TITLE
Keeps crashing!

### ISSUE THREAD

**Issue by laravieira** [files-community/Files#8729]
### Description

Randomly crashes when I click to open any folder inside the app, sometimes I just try again and it works, sometimes it keeps crashing. Happens to me many times, with random folders.

### Steps To Reproduce

1. Try to open a folder.

### Expected behavior

Do not crash and popup notification asking me to report the crash. Just open the folder.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.556

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎27/‎11/‎2021 OS build	22000.556 Experience	Windows Feature Experience Pack 1000.22000.556.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8316246/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8316247/debug_fulltrust.log)
[https://youtu.be/bw7Hdtji1Mk](https://youtu.be/bw7Hdtji1Mk)

**Comment by Josh-65** [comment]
Do you have show folder size enable. if so turn it off and see if it happends.

**Comment by laravieira** [comment]
I had, them I disabled it weeks ago. The problem is still the same.
![image](https://user-images.githubusercontent.com/40150947/159377966-ba19ef4a-752a-4557-9e67-094dca396744.png)

**Comment by gave92** [comment]
According to log file, merging with #8749

**Comment by Bodge-IT** [comment]
no improvement yet.
