### ISSUE TITLE
With "Show extensions for known file types" disabled, when renaming a file you need to type its extension or it will be unformatted

### ISSUE THREAD

**Issue by XPoppyX** [files-community/Files#873]
![bug](https://user-images.githubusercontent.com/61259627/83084735-d8e97980-a057-11ea-97eb-6444337e9eca.gif)

**Comment by duke7553** [comment]
Thanks for your feedback. We're having trouble understanding what you're requesting and need additional information to investigate this item. Please re-open when you've filled out the issue template to the best of your ability.

**Comment by xPoppyx** [comment]
- With "Show extensions for known file types" **Enabled**

![Captura de pantalla (215)](https://user-images.githubusercontent.com/61259627/83083124-4a72f900-a053-11ea-8cf4-c3b9742c7e27.png)
--------------------------------------------------------------------------
- With "Show extensions for known file types" **Disabled**

_when renaming it is necessary to write its extension at the end or the file will be left without a format_

![Captura de pantalla (214)](https://user-images.githubusercontent.com/61259627/83083125-4ba42600-a053-11ea-8a73-f8225c183947.png)

**Comment by xPoppyx** [comment]
@duke7553 Can you re-open it please? I already changed the title to better understand the issue

**Comment by XPoppyX** [comment]
@yaichenbaum I mention you in case you have not read this bug

**Comment by duke7553** [comment]
@XPoppyX No need to nag. We can't get to every open issue.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #2163.
