### ISSUE TITLE
Synology Drive in Cloud Drives Section

### ISSUE THREAD

**Issue by miqueldespuig** [files-community/Files#8730]
### What's the Problem?

Synology Drive is a self-hosted cloud application that runs on Synology NAS.

It is not detected as a Cloud Drive within Files.

![2022 03 21 621 1200x683 ](https://user-images.githubusercontent.com/53223838/159291078-6898eb61-02fc-45f6-b603-e7dc6522c2d2.png)

### Solution/Idea

It would be great if this nifty application is supported as a Cloud Drive!

### Alternatives

Add Synology Drive folder as a favourite works fine.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.1.15.0

### Windows Version

Windows 10 Pro 20H2  OS Version: 10.0.19042.1466

**Comment by yaichenbaum** [comment]
Merging with #8084
