### ISSUE TITLE
Why was my issue deleted?

### ISSUE THREAD

**Issue by martymarty004** [files-community/Files#8731]
Hello,
I wanted to know if the issue I opened a few hours ago (#8728) was deleted by accident, or if it was removed on purpose.

Thanks.

**Comment by martymarty004** [comment]
@yair100 by looking at it, that seems to be the same issue.

Thank you for pointing that out. 

I would have preferred if you mentioned it before deleting my issue (if it wasn't you, then I apologize).

**Comment by martymarty004** [comment]
Do you need the logs and the info that I posted before?

**Comment by yaichenbaum** [comment]
@martymarty004 apologies for the confusion, it should have been merged with #8569.

**Comment by martymarty004** [comment]
@yair100 OK, I added all the information that I gathered on the original issue.
