### ISSUE TITLE
Allow pinning network shares to favourites

### ISSUE THREAD

**Issue by martymarty004** [files-community/Files#8732]
### What's the Problem?

At the moment, it's not possible to pin a network share (like `\\192.168.69.77\` ) to the favourites list / cloud drives / network drives.
You can pin the subfolders, but not the root.

### Solution/Idea

Add a command to add the current folder to the favourite list.

### Alternatives

Add a specific function to add network shares to the favourite list

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to access network shares with more ease| Must |
| This proposal will allow end users to accomplish access network shares with more ease | Must |
| This proposal will allow developers to pin the current folder with more ease| Should |
| This proposal will allow end users to pin the current folder | Should |

### Files Version

Versione 2.1.24.0 OS Version: 10.0.22000.556

### Windows Version

Windows 11 21H2 22000.556

### Comments

![image](https://user-images.githubusercontent.com/61474670/159348760-96ca3f9f-f89e-43b8-a198-37dc8b6f7360.png)

![image](https://user-images.githubusercontent.com/61474670/159348886-a0a9fe3a-9f94-411d-a721-aebbb8209097.png)

**Comment by gave92** [comment]
Atm you should be able to pin it under Network by right clicking on network and choosing "map network drive". From the dialog you'll be able to choose whether to actually map the share as a network drive or only add it as a link.

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
