### ISSUE TITLE
Suggestions for improving the interface

### ISSUE THREAD

**Issue by LiuYueNan** [files-community/Files#8734]
### What's the Problem?

Whether you can add interface font size settings, the current UI as a whole is a bit large, the content is displayed less, it is recommended to add mouse mode and touch mode options, just like Word, or interface font size settings.

### Solution/Idea

 interface font size settings.

### Alternatives

 add mouse mode and touch mode options, just like Word

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
Merging with #1940
