### ISSUE TITLE
Cannot delete deleted library files in recycle bin

### ISSUE THREAD

**Issue by trymeouteh** [files-community/Files#8736]
### Description

Deleted libraries files do not show up in the recycle bin but do show up in the Windows File Explorer recycle bin

### Steps To Reproduce

Go to the Settings
Under Appearance->Sidebar ensure Show Library Section On The Sidebar is enabled
Close settings

Right click on the Libraries dropdown in the Sidebar and click on Create New Library
Set the name of the library
Click Create

Right click on the newly created Library shortcut in the Sidebar and click on Don't Show In Navigation Pane
Right click on the Libraries dropdown in the Sidebar and click on Restore Default Libraries
Click Restore
In the popped up file explorer window, delete the library you want to delete
Go to the recycle bin in Files and the Windows File Explorer

### Expected behavior

Should see library files in recycle bin

### Files Version

2.1.15

### Windows Version

Windows 10

### Relevant Assets/Logs

Will add logs later.

**Comment by Josh-65** [comment]
@trymeouteh  is this still an issue in 2.3.11 (stable release)?
