### ISSUE TITLE
Home takes you to user home folder

### ISSUE THREAD

**Issue by trymeouteh** [files-community/Files#8737]
### What's the Problem?

Home folder takes you to "This PC" and not the user home folder

### Solution/Idea

Home button takes you to user home folder

### Alternatives

Rename "Home" button to "This PC" button

**Comment by Josh-65** [comment]
Files is not file exploerer. Files uses home beacuse its it own custom thing and makes sence within the program itself. It doesnt make much sence to change it.

**Comment by gave92** [comment]
We're not planning to change what the home button does but we're planning to let users customize the page that opens on a new tab #6480.
