### ISSUE TITLE
Show/Hide Recycle Bin in Side Panel (Not Just In Favorites)

### ISSUE THREAD

**Issue by trymeouteh** [files-community/Files#8738]
### What's the Problem?

Add option to have recycle bin button in side panel but not inside of the favorites.

### Solution/Idea

Add a setting to enable/disable recycle bin in side panel and remove recycle bin option in favorites.

### Alternatives

Add a setting to enable/disable recycle bin in side panel.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
Thank you for your feedback. We don't have plans to implement this option.
