### ISSUE TITLE
Sudden crash of files application

### ISSUE THREAD

**Issue by KrishnakantRawat** [files-community/Files#8739]
### Description

I am running this on windows 10 laptop with high specs still it usually just crashes by itself when i need to use it, 
![image](https://user-images.githubusercontent.com/71597724/159404364-b222f79c-7bb1-41b7-b129-969d82b567ed.png)
here as you can see clearly why this is happening is not mentioned, I kept it as default application still its no good for me. It usually crashes itself in 2-3minutes.

### Expected behavior

It is supposed to run without crashing for however long its opened. Crashing of an app, means what to say....

### Files Version

Version: 2.1.15.0 OS Version: 10.0.19043.1586

### Windows Version

Windows 10 version 21H2

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/71597724/159404663-a2e7cfe9-ac8f-4bde-815c-28e5bd492ef3.png)

**Comment by Josh-65** [comment]
You will need to upload the logs files directly to github. You can get them in files settings > about > open log folder.
