### ISSUE TITLE
suddenly close

### ISSUE THREAD

**Issue by HokiKaha** [files-community/Files#8741]
### Description

tiba - tiba window menutup tanpa sebab

### Steps To Reproduce

tiba - tiba window menutup tanpa sebab

### Expected behavior

tiba - tiba window menutup tanpa sebab

### Files Version

windows 11

### Windows Version

windows 11

### Relevant Assets/Logs

tiba - tiba window menutup tanpa sebab

**Comment by yaichenbaum** [comment]
We need a little more information from you in order to investigate this issue, please reopen this issue once you have filled out the issue template.
