### ISSUE TITLE
Ability to set the currently shown columns in Details view as default for all folders

### ISSUE THREAD

**Issue by jtherrienGH** [files-community/Files#8743]
### What's the Problem?

Love the app, but wish I could preset a better default for which columns are shown. For example, I never want to see the "File Type" column. It's redundant to the icon for me and I'd rather have more space for the File Name column. Relatedly, by default, I'd like a wider File Name column.
 

### Solution/Idea

Create options for defaults to show/hide columns, and perhaps even set sizes for columns.

### Alternatives

There are no good alternatives.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.15.0

### Windows Version

Windows 10

**Comment by gave92** [comment]
Turning off the "enable individual preferences for folders" under settings > preferences > files and folders should allow this.

**Comment by jtherrienGH** [comment]
Thanks for the suggestion, but it doesn't totally allow what I'm looking for. When "enable individual preferences for folders" is turned off, you can indeed turn off columns, but you cannot set any defaults for column size. Now, every window has too small of a "File Name" column and too large of a "Tags" column. Still need options for better defaults here.

**Comment by jtherrienGH** [comment]
Furthermore, now I can't set up custom columns for any folder. All must be the same, which is not what I want.

**Comment by jtherrienGH** [comment]
Please reopen.

**Comment by gave92** [comment]
A bug preventing column sizes to be remembered is tracked in #6448.
Reopening to keep track of request to set which columns are visible by default but still be able to customize them for some folders.

**Comment by gave92** [comment]
In the meantime you try the following (I know it's unintuitive and I'm not certain it works in the latest version):
1- Turn off "Enable individual preferences for folders" in Files Settings > Files and Folders
2- Show/hide any column you wish
3- Turn back on "Enable individual preferences for folders" option

What you set in [2] should be the new default.

**Comment by ELowry** [comment]
> Turning off the "enable individual preferences for folders" option under settings > preferences > files and folders should allow this.

This also disables the option of having different views for different folders.

For example I use _Large_ or _Medium_ Icons for some folders, _Details_ for others, and _Tiles_ in some rare cases. However, I still wish to have the columns layout be the same across all _Details_ views.

**Comment by yaichenbaum** [comment]
This is resolved in the latest preview build v2.3.48. https://files.community/download/preview
