### ISSUE TITLE
Not possible to login to network drive

### ISSUE THREAD

**Issue by pepsilon7** [files-community/Files#8747]
### Description

For a given network drive that requires login information files does not ask for the login informatin and instead just shows an empty network drive.

### Steps To Reproduce

1. Add network drive that requires login information
2. Try to open this networkdrive

### Expected behavior

Files should ask for the login information in order to log into the network drive.

### Files Version

2.1.24.0

### Windows Version

Windows 11 Home 21H2 22000.588

### Relevant Assets/Logs

None

**Comment by gave92** [comment]
Merging with #258
