### ISSUE TITLE
如何将 files版本: 2.1.15.0 OS Version: 10.0.22000.556 设置为windows11默认文件管理

### ISSUE THREAD

**Issue by JoonYiLi** [files-community/Files#8750]
### What's the Problem?

在 files版本: 2.1.15.0
OS Version: 10.0.22000.556
中实验室中没有将该软件设置为默认文件管理

### Solution/Idea

我需要将该软件设置为默认文件管理的方法

### Alternatives

修改注册表之类

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

版本: 2.1.15.0

### Windows Version

Windows 11 家庭中文版 21H2 22000.556

### Comments

![微信图片_20220323232033](https://user-images.githubusercontent.com/91377172/159734170-d9ebd4ba-270e-42c0-b529-4120f1568401.png)
![微信图片_20220323232112](https://user-images.githubusercontent.com/91377172/159734199-2948f3a0-21de-4088-a66e-601ec96f8b93.png)

**Comment by yaichenbaum** [comment]
This is currently only available for the sideload version of Files and is not supported in the store version.
