### ISSUE TITLE
Incompatible with application SEER

### ISSUE THREAD

**Issue by BearBearian** [files-community/Files#8753]
### What's the Problem?

Incompatible with application SEER

### Solution/Idea

cant startup files preview app SEER when FILES running

### Alternatives

QUICKLOOK,but i pefer to SEER

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.15.0

### Windows Version

WIn11 pro 21H2

**Comment by yaichenbaum** [comment]
We don't have plans to build an integration for SEER into Files.

**Comment by yaira2** [comment]
@BearBearian support for Seer is currently being tracked in #8052. In the meantime, Files has support for QuickLook which has similar functionality.
