### ISSUE TITLE
Show MEGA in Cloud Drives

### ISSUE THREAD

**Issue by J4k-The-Reaper** [files-community/Files#8754]
I am new to this. Just found out about this application/ community from Twitter. I am wondering how I can add or see my MEGA account/files in the Cloud Drives. Has this already been discussed or added and I am being dumb? Please correct me if so....or help me.

**Comment by gave92** [comment]
Have you installed the mega client app?

**Comment by J4k-The-Reaper** [comment]
Yes I have. I've been using MEGA for years so it's been installed already, before Files. Why?

**Comment by gave92** [comment]
Thanks for confirming. Could you post the following?
1) a screenshot of File Explorer sidebar
2) the log files of the Files app. You can get them from Files settings > About > Open log location. You'll find two ".log" files.

**Comment by J4k-The-Reaper** [comment]
> Thanks for confirming. Could you post the following?
> 
> 1. a screenshot of File Explorer sidebar (it should show the MEGA synced folder(s))
> 2. the log files of the Files app. You can get them from Files settings > About > Open log location. You'll find two ".log" files.

I don't see MEGA in the sidebar. I think they removed that feature long ago since they released the MegaSync Desktop app. I have that installed. I chose to have Mega download/sync to my downloads folder too.

But here are the .log files:
[debug.log](https://github.com/files-community/Files/files/8353833/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8353834/debug_fulltrust.log)

**Comment by gave92** [comment]
> I don't see MEGA in the sidebar. I think they removed that feature long ago since they released the MegaSync Desktop app

Thanks for the info, that's why it does not work. MEGA folders are currently fetched from the explorer sidebar.

**Comment by J4k-The-Reaper** [comment]
Awww damn. That sucks. Woulda been nice to see all cloud/drives in single place and not have to open the app everytime. Oh well. Haha

**Comment by gave92** [comment]
I've just installed what I believe is the latest version of MEGA sync app and the synced folder appear on File Explorer sidebar and in Files too.
Could you check if you have this option enabled (in MEGA)?
![image](https://user-images.githubusercontent.com/9673091/160203166-4689abe0-fe67-4862-9861-59d8d05ea166.png)

**Comment by Josh-65** [comment]
@J4k-The-Reaper Is this still an issue. if so have you tried gave92 suggestion

**Comment by samiullahqutbi** [comment]
I had the same issue but I followed what gave92 said by checking the "Enable windows explorer integration" and now it shows the cloud drive section in the files app
