### ISSUE TITLE
Add padding to the left side of the pathbar

### ISSUE THREAD

**Issue by Tropix126** [files-community/Files#8755]
### What's the Problem?

The horizontal padding on the address bar is rather minimal, especially when being compared to search boxes.

![image](https://user-images.githubusercontent.com/42101043/159827196-5acb4e96-4d99-4109-8d3e-8f6fcae4140d.png)

![image](https://user-images.githubusercontent.com/42101043/159827265-f94adad5-093c-44d8-a186-7ed578879c5c.png)

### Solution/Idea

Increase the horizontal padding of the address bar to be consistent with the search bar.

### Alternatives

none

### Files Version

2.1.28.0

### Windows Version

22572.1

**Comment by yaichenbaum** [comment]
This issue should be resolved with #8758
