### ISSUE TITLE
Open desktop folders delay

### ISSUE THREAD

**Issue by alishtamimi** [files-community/Files#8756]
### Description

When I set the files app as a default, opening any desktop folder takes up to 3 seconds to open files and then another second to load the content and side menu.

### Steps To Reproduce

1. Set files as default
2. close files app
3. open any desktop folder 
4. files takes 3 seconds to open
5. files takes 1 second to load the folder content 

### Expected behavior

1. Set files as default
2. close files app
3. open any desktop folder 
4. files open and load the folder content instantly 

### Files Version

2.1.29 (preview)

### Windows Version

Windows 11 22H1

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8339150/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8339151/debug_fulltrust.log)

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.0.0?

**Comment by alishtamimi** [comment]
Yes

**Comment by Josh65-2201** [comment]
@yair100

**Comment by yaichenbaum** [comment]
Merging with #8706
