### ISSUE TITLE
Cut-paste to cloud storage mapped to Windows location will be copied, not pasted

### ISSUE THREAD

**Issue by emes81** [files-community/Files#8757]
### Description

I think the title sums it up already!

### Steps To Reproduce

1. Install Tresorit and enable Tresorit Drive. Your Tresorit will be mapped as T:\
2. Cut a folder and paste it into a Tresor. Folder will be copied, not pasted; folder will still be present at its original location.

### Expected behavior

Once cut and pasted, the folder is no longer present at the original location.

### Files Version

2.1.15.0

### Windows Version

Win 10 Pro 19042.1526

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8339942/debug.log)

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?
