### ISSUE TITLE
Files app crashes often

### ISSUE THREAD

**Issue by avjoshi-07** [files-community/Files#8759]
### Description

A lot of times, randomly without any patterns, the app crashes and says, "Files encountered an error not seen before" and then crashes without any error codes.

### Steps To Reproduce

1. Open app
2. Try opening random folders

Since there is no pattern or error code observed, it is hard to say what exactly triggers the crash.

### Expected behavior

The app should keep working smoothly instead of crashing.

### Files Version

Version: 2.1.15.0

### Windows Version

Windows 11 Version 21HS (OS Build 22000.556)

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8342955/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8342958/debug_fulltrust.log)

**Comment by Josh-65** [comment]
Do you have show folder sizes enabled in files settings > experimental

**Comment by gave92** [comment]
From the log file, the error could be this one (unrelated to the issue of folder size):
> 11:28:58.3105|ERROR|AppUnhandledException|The parameter is incorrect.
The parameter is incorrect.

**Comment by avjoshi-07** [comment]
Nope, that feature is turned off. I usually never turn on experimental
features.

*Archan V Joshi*
*Software Engineer*
*M.S. (Systems Engineering)*

**Comment by avjoshi-07** [comment]
> Do you have show folder sizes enabled in files settings > experimental

Nope, that feature is turned off.

**Comment by avjoshi-07** [comment]
> From the log file, the error could be this one (unrelated to the issue of folder size):
> 
> > 11:28:58.3105|ERROR|AppUnhandledException|The parameter is incorrect.
> > The parameter is incorrect.

It could be, developers can check when is that message printed and look for what use cases have been missed. I am not familiar with C#, so have not followed the codebase. Hopefully, I'd be a contributor at some point in the future.

**Comment by yaichenbaum** [comment]
We made a number of improvements in this area that will be included in the next release.

**Comment by avjoshi-07** [comment]
No idea what parameter it is talking about.

*Archan V Joshi*
*Software Engineer*
*M.S. (Systems Engineering)*
