### ISSUE TITLE
Crash when invoking the right click context menu in Details layout

### ISSUE THREAD

**Issue by SOI7** [files-community/Files#8762]
### Description

App crashes after multiple right clicks in a folder. The error is consistent in Details view, but I'm not able to reproduce it in Grid view. Compact style doesn't change the error frequency

### Steps To Reproduce

Navigate into a folder, set layout to Details view, right click in an empty spot a couple of times (speed doesn't matter)

### Expected behavior

App shouldn't crash

### Files Version

Version 2.1.29.0 

### Windows Version

10.0.19044.1620 (Windows 10 21H2)

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8344459/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8344460/debug_fulltrust.log)

**Comment by gave92** [comment]
According to log files, merging with #5666
