### ISSUE TITLE
No Custom Themes Available

### ISSUE THREAD

**Issue by psyrider46** [files-community/Files#8766]
### Description

The custom themes option is showing only showing default option. No other themes are showing.

### Steps To Reproduce

![Screenshot 2022-03-26 012736](https://user-images.githubusercontent.com/102386932/160192516-7a0b68eb-3f45-4f73-ad09-280bea38af87.png)

### Expected behavior

When selecting the custom themes option it must show themes to customize. If there is no other themes available other than the default theme, then why are you showing an option for customizing themes?

### Files Version

Version: 2.1.15.0 OS Version: 10.0.19044.1586

### Windows Version

Windows 10 21H2 19044.1586

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8353538/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8353540/debug_fulltrust.log)

**Comment by gave92** [comment]
It's a know bug. You'll need to reset the app from Windows Settings.
