### ISSUE TITLE
Files crashes when an image is edited using the Windows Editor

### ISSUE THREAD

**Issue by alessandrogian** [files-community/Files#8768]
### Description

Every time I edit an Image with the Windows image viewer, once I save it the program crashes.

### Expected behavior

I expect the files app to remain open and show the edited version of the photo

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.556

### Windows Version

Windows 11 Home 21H2 22000.556

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8354031/debug.log)

**Comment by gave92** [comment]
Merging with #8763 (same stack trace)
