### ISSUE TITLE
Add speed and remaining time when copying files 

### ISSUE THREAD

**Issue by Domado** [files-community/Files#8769]
### Solution/Idea

The lack of speed in copying files is very annoying to me, I have no way of knowing how long it will take.
Please add speed and remaining time when copying files.
Thanks.

### Alternatives

Add speed and remaining time when copying files 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by gave92** [comment]
Merging with #4811
