### ISSUE TITLE
Ryujinx Open File Bug

### ISSUE THREAD

**Issue by phuongbag** [files-community/Files#8770]
### Description

Ryujinx Open File Bug - like the name, it said cant found files.exe when i press open folder of that program.

### Expected behavior

Ryujinx Open File Bug - like the name, it said cant found files.exe when i press open folder of that program.

### Files Version

Version: 2.1.24.0 OS Version: 10.0.22000.556

### Windows Version

Wins 11 21H2 22000.556

### Relevant Assets/Logs

do you really need log files :v

**Comment by gave92** [comment]
Please run this script to restore explorer: https://raw.githubusercontent.com/files-community/Files/main/src/Files.Launcher/Assets/FilesOpenDialog/UnsetFilesAsDefault.reg. Make sure to save it as a ".reg" file.
