### ISSUE TITLE
FilesLauncher.exe fails when VC++ runtime is not installed

### ISSUE THREAD

**Issue by whubao** [files-community/Files#8771]
vcruntime.dll cannot be found

**Comment by gave92** [comment]
You'll need to install the VC++ runtime: https://aka.ms/vs/16/release/vc_redist.x64.exe
We're looking if it's possible to budge it with the app.

**Comment by itsWindows11** [comment]
> We're looking if it's possible to bundle it with the app.

Can't static libraries (the ones built into Windows) be used?

**Comment by gave92** [comment]
Yup that's probably better. Should be a simple compilation switch.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #8829
