### ISSUE TITLE
Newly created excel documents have the wrong date modified

### ISSUE THREAD

**Issue by evancjohnson** [files-community/Files#8772]
### Description

When creating an excel document the last modified date defaults to Friday, December 25, 2020

### Steps To Reproduce

1. Right click, new excel worksheet
2. Give whatever name
3. See Friday, December 25th, 2020

### Expected behavior

The newly created excel document should have a last modified date of today.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.556

### Windows Version

Edition	Windows 11 Enterprise Version	21H2 Installed on	‎10/‎5/‎2021 OS build	22000.556 Experience	Windows Feature Experience Pack 1000.22000.556.0

### Relevant Assets/Logs

https://user-images.githubusercontent.com/17952965/160223002-7c0b34ab-a345-425d-b0fd-32f306a341f6.mp4
[debug_fulltrust.log](https://github.com/files-community/Files/files/8354596/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8354597/debug.log)

**Comment by Satevis15** [comment]
Same bug , but for any files , not exel documents specifically

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.0.0?
