### ISSUE TITLE
Code Quality: Simplify the management of keyboard shortcuts.

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#8774]
### What's the Problem?

Currently, keyboard shortcuts are absolutely not centralized.
- The shortcut is often indicated in the localized tooltip and a change of shortcut requires reviewing the text in all languages (and therefore creates bugs).
- This obliges to create a text specific to the tooltip and therefore to have redundancy in the localization with a risk of error or inconsistency (in the format of the shortcut).
- Many shortcuts are missing in the tooltips.
- There is no page that lists all shortcuts.
- It is unthinkable to allow editing of keyboard shortcuts with the current code (even if this is not currently planned).

### Solution/Idea

We can also have a class containing all shortcuts.

We can modify helpers:ResourceString to add the shortcut property (in 1 or 2 properties, it doesn't matter).
This automatically adds the shortcut to the text, so the display will always be consistent. You will have to manage the language in this code because the keys do not have the same name depending on the language.

- This will ensure consistency between the actual shortcut and the displayed shortcut.
- This avoids inconsistencies (difference between shortcut and text in some languages).
- The developer can know more easily if a shortcut is already used.
- We can easily add a page that displays all keyboard shortcuts.
- It will be easier to display the shortcut in all the tooltips (there are currently some missing).
- It will be very easy to modify a keyboard shortcut.
- It will be very easy to make keyboard shortcuts editable if so desired.

### Alternatives

None

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
@cinqmilleans shortcuts aren't supposed to be translated, as part of the review process for any translations, we're supposed to ensure the text for the shortcut stays the same.

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?

**Comment by yaichenbaum** [comment]
We're going to need to do this to prepare for #9559.

**Comment by yaichenbaum** [comment]
@cinqmilleans do you have a proposal on how to implement this (services, view models etc)>

**Comment by cinqmilleans** [comment]
@yair100 Here is what can be set up easily.
1) (I)ShortKey to contain a keyboard shortcut (Key + Modifiers). It is an ObservableObject.
2) ShortKeyViewModel to hold a long list of ShortKey. It is a service accessible by several interfaces (one for the items, one for the views, ...) but with a single implementation.
3) Views that need it use the ViewModel in binding with KeyboardAccelerator. It will be necessary to replace the huge Invoked methods by a method per command. It's cleaner, simpler, and it avoids having to find the right command in the method (which will be more difficult).
4) There is a difficulty. There seems to be a bug in KeyboardAccelerator. Using the binding to modify the key does not remove the old one, it only adds the new one. It is not possible to remove the old one without using the code behind, but we lose the ease of xaml and binding. This bug may be fixed. We can report it.
5) It will be necessary to manage the storage of modifications (LiteDb should suffice). We can save the changes without making them, and announce that Files must be restarted (as for the language).
6) You need a setting page that displays all the shortkeys, with a label, a possible description, and a default value. I created a KeyPicker.

**Comment by yaichenbaum** [comment]
> (I)ShortKey to contain a keyboard shortcut (Key + Modifiers). It is an ObservableObject.

What does this look like, can you share an example piece of code?

> ShortKeyViewModel to hold a long list of ShortKey. It is a service accessible by several interfaces (one for the items, one for the views, ...) but with a single implementation.

What do you mean by items vs views?

> Views that need it use the ViewModel in binding with KeyboardAccelerator. It will be necessary to replace the huge Invoked methods by a method per command. It's cleaner, simpler, and it avoids having to find the right command in the method (which will be more difficult).

Shortcuts will always trigger a command 👍

> There is a difficulty. There seems to be a bug in KeyboardAccelerator. Using the binding to modify the key does not remove the old one, it only adds the new one. It is not possible to remove the old one without using the code behind, but we lose the ease of xaml and binding. This bug may be fixed. We can report it.

I think we can work around this by simply handling everything in code behind but we'll have to do some testing.

> It will be necessary to manage the storage of modifications (LiteDb should suffice). We can save the changes without making them, and announce that Files must be restarted (as for the language).
You need a setting page that displays all the shortkeys, with a label, a possible description, and a default value. I created a KeyPicker.

I'm not sure why the app will need to be restarted, we only force users to restart for languages because it's the only way to update title bar direction. Either way, we should be using json like we do for other settings.


On the topic of customization, it's important to make sure it's implemented in a way where users are assigning shortcuts to actions rather than assigning actions to shortcuts.
![image](https://user-images.githubusercontent.com/39923744/200020722-9bc012b9-36d0-418d-a10d-394e10dc47ef.png)

**Comment by cinqmilleans** [comment]
I was able to work around the difficulties mentioned, including rebooting. I place all the shortcuts in a single class whose properties are shortcuts. This class is used by anything that triggers or displays a shortcut. You won't have to restart. It also handles commands that do not yet have shortcuts (InvertSelection, ...) but the user can assign them. When everything is centralized, we can add a configuration page and store the values in a json in a other pr.

I'm busy with this feature and will post the pr soon.

**Comment by yaichenbaum** [comment]
This hasn't been approved yet, I think we need more time to discuss the details before putting the work into a PR.

**Comment by yaira2** [comment]
@cinqmilleans thank you for all your hard work on building the foundation for custom key-bindings. We've built on top of your solid foundation and we're excited to share that this feature will be included in the next release.
