### ISSUE TITLE
Show more information for multiple media files in the Properties menu

### ISSUE THREAD

**Issue by BrandonLogandi** [files-community/Files#8775]
### What's the Problem?

When working with multiple media files (e.g. music or videos), the only details displayed for selected files are their path, attributes and total size. 
This leaves out a lot of potentially useful information, like their total length, audio bitrate, framerate and resolution (for videos), etc.

### Solution/Idea

The default Windows Explorer displays all of the details mentioned above in a separate Details tab
![image](https://user-images.githubusercontent.com/59068101/160245620-2ec7fc76-0c7b-46de-9d99-b87abb96bd8c.png) 
   
Files does have the same Details tab. However, it only shows up for single files.
![image](https://user-images.githubusercontent.com/59068101/160245736-9abd27e7-0535-40d9-9a2b-b71770b2528f.png)
_With only one file selected, the Details tab shows up and all data is displayed_  

![image](https://user-images.githubusercontent.com/59068101/160245742-ed0d7030-daf6-4c6e-9728-a6886ae376cb.png)
_Details tab is nowhere to be seen with multiple files selected_

### Alternatives

As mentioned previously, the default Windows Explorer does all of the above.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Display details for multiple selected media files | Must |
| Indicate when a certain attribute differs from the same attribute in other files (e.g. files with different resolutions) | Could |

### Files Version

Version 2.1.24.0

### Windows Version

Windows 10 21H1 19043.928

**Comment by jcedmiston** [comment]
I have a basic version of this working. Going to clean it up a bit and make it act a bit more like the Windows Explorer implementation
![Multi-File_Details_1](https://user-images.githubusercontent.com/46663821/164583955-53d79093-fe1c-4859-bc97-529daa78318a.PNG)
![Multi-File_Details_2](https://user-images.githubusercontent.com/46663821/164583957-343b1157-3f49-4bb7-b7ae-87d142837556.PNG)

**Comment by BrandonLogandi** [comment]
That is indeed what i proposed

**Comment by hecksmosis** [comment]
@jcedmiston Are you working on this?

**Comment by jcedmiston** [comment]
@hecksmosis I have had some stuff pop up over the last few months but that's getting better and I hope to keep working on it soon.

**Comment by hecksmosis** [comment]
Ok

**Comment by yaira2** [comment]
This feature is now available in the preview version https://files.community/download.
