### ISSUE TITLE
Files hangs previewing files with .mkv extensions

### ISSUE THREAD

**Issue by Yandall** [files-community/Files#8776]
### Description

Everytime I interact with a file that ends with .mkv files stop responding.
If I click in a mvk file and then click elsewhere, files stop responding and I have to close it.

Update: this is due to the preview pane. When I disable it, the problem doesn't occur

### Steps To Reproduce

1. Download a mkv file
2. Click in the file
3. Click elsewhere, like another file or go to another folder

### Expected behavior

Files will be loading forever and stop responding

### Files Version

2.1.24.0

### Windows Version

Edition	Windows 10 Home Version	21H2 Installed on	‎23/‎07/‎2021 OS build	19044.1586 Experience	Windows Feature Experience Pack 120.2212.4170.0

### Relevant Assets/Logs

https://user-images.githubusercontent.com/49245907/160247636-511fdf58-0be0-4b47-a3c6-7d4af488eca3.mp4

**Comment by gave92** [comment]
Could you check if it's related to the preview pane? What happens if you hide the preview pane before clicking on an MKV file?

**Comment by Yandall** [comment]
Yes it's definetly related to the preview pane. If I disable the preview pane before click the file, Files doesn't crash

**Comment by yaichenbaum** [comment]
Is this still an issue in the latest preview build? https://files.community/download/preview
