### ISSUE TITLE
Quick Access not showing files

### ISSUE THREAD

**Issue by Someone-Somwhere** [files-community/Files#8781]
### Description

When I open Files at the bottom of the Home page it is supposed your recently accessed files. But it doesn't seem to be so accurate. e.g. I will open a file then close it and it doesn't appear on the Home page even after I relaunch the app

### Expected behavior

It doesn't show the most recently opened files and it also randomly shows system files.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.19044.1586

### Windows Version

Windows 10 Pro Version 21H2 19044.1586

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/71657811/160299600-fbf640c3-f707-490e-a3d8-9dba49db3938.png)

**Comment by Josh-65** [comment]
The recent files section only works within files. Is this an issue even if you open a file in files

**Comment by Someone-Somwhere** [comment]
> The recent files section only works within files. Is this an issue even if you open a file in files

I don't think so
