### ISSUE TITLE
The experimental feature allowing me to set Files as default file manager dissapeared

### ISSUE THREAD

**Issue by Dipe08** [files-community/Files#8786]
### Description

I had Files as my default file manager for a couple of weeks but needed to change it for something (I can't remember what but it doesn't matter) I did that fine, but after having finished my business I tried to once again set Files as default file manager and the option is gone from the experimental menu.
![image](https://user-images.githubusercontent.com/83474612/160305101-64e052c5-6cdc-41d4-a9ff-1bd482a61819.png)

### Expected behavior

I guess the expected behaviour would be for the option to be there.

### Files Version

Versión: 2.1.15.0 OS Version: 10.0.19044.1586

### Windows Version

Windows 10 Pro 21H2 19044.1586

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8358650/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8358651/debug.log)

**Comment by yaichenbaum** [comment]
This option is only available for the sideload version of Files.

**Comment by Dipe08** [comment]
I am really sorry but I don't quite understand, how do I get or activate that version?

**Comment by yaichenbaum** [comment]
> I am really sorry but I don't quite understand, how do I get or activate that version?

https://files.community/download/stable
