### ISSUE TITLE
Kind request for help

### ISSUE THREAD

**Issue by PouriaRouzrokh** [files-community/Files#8787]
Hi. I enabled Files as my default file explorer in Windows, but it is not working as expected. Now, I want to turn off that option and again use the windows default file explorer. I tried turning off that feature in the Experimental Features tab in Files settings, but that feature stays activated and does not turn off! I also tried uninstalling Files, but it did not change the file explorer to default. I assume I should do something in the registry to make things work as default again. Would you mind letting me know what I should do?

Thank you.

**Comment by yaichenbaum** [comment]
https://github.com/files-community/Files/issues/7626
