### ISSUE TITLE
Shift+Del aka Perminant Delete does not work.

### ISSUE THREAD

**Issue by dhbtfs** [files-community/Files#8788]
### Description

If you use Shift+ Delete key to delete a file or folder, it does nothing.  

### Steps To Reproduce

Press Shift + Delete on a file or a folder.
Click on Delete button on new menu.
Nothing happens.

### Expected behavior

For the file to be removed permanently 

### Files Version

Version: 2.1.31.0 OS Version: 10.0.22000.556

### Windows Version

Windows 11 Pro Version	21H2 OS build	22000.556 Experience	Windows Feature Experience Pack 1000.22000.556.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8362051/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8362052/debug_fulltrust.log)

**Comment by gave92** [comment]
Issue is only with permanent delete or also moving to bin? Any difference of you try with the keyboard or the context menu? Does the delete confirmation dialog appear?

**Comment by dhbtfs** [comment]
Normal delete or moving to bin has no issue; only the permanent delete has this issue.  
Both keyboard and context menu while holding shift does nothing after confirming to delete. 
Delete confirmation dialog does appear.
Yes it is enabled.

**Comment by CrypticVader** [comment]
Here's what the bug is like for me.
https://user-images.githubusercontent.com/61494838/160541181-0196888d-1b7e-4cd3-b6d1-b73a8d1bd7e8.mp4

**Comment by carlosvsilva** [comment]
In latest preview build version: 2.2.4.0
OS Version: 10.0.22000.652
Shift + Trash Can icon click does not pre-fill the "Permanent Delete" checkbox.

After the file is deleted, and the operation is done, I open the Operation list on the top right, click Clear, and after clearing all operations sucessfully, the operations popup window stays open, empty, instead of closing automatically :)

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?

**Comment by carlosvsilva** [comment]
Yes happens often.

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview build? https://files.community/download/preview

**Comment by sthivaios** [comment]
Everything woks fine for me in version 2.3.48.0


https://user-images.githubusercontent.com/109022579/195945547-8c76fcf5-6f0f-419d-ab13-a4a3cb27a927.mp4
