### ISSUE TITLE
on Delete prompt , Permanent delete option is disabled.

### ISSUE THREAD

**Issue by dhbtfs** [files-community/Files#8789]
### Description

When you press Delete on a file or folder, even using the right click menu on and select delete icon. The new window prompts to delete the file but the Permanent Delete is disabled, unless you press and hold on Delete button and not release right mouse button. Then the option becomes available to be ticked.

### Steps To Reproduce

Delete a file.
Permanent Delete option is visible but not accessible.

### Expected behavior

To have that option available regardless of user holding shift or not, its an option but its not behaving that way atm.

### Files Version

Version: 2.1.31.0 OS Version: 10.0.22000.556

### Windows Version

Windows 11 Pro Version	21H2 OS build	22000.556 Experience	Windows Feature Experience Pack 1000.22000.556.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8362074/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8362076/debug_fulltrust.log)

**Comment by gave92** [comment]
Does pressing "Tab" key when the dialog is open enable the permanent delete checkbox?

**Comment by gave92** [comment]
Is this different from #8788?

**Comment by dhbtfs** [comment]
Pressing the Tab key does enable it. Using Shift+Del key brings up the prompt but checkbox is already ticked, no way to disable/remove tick until you do the mouse trick or Tab like you suggested.
Also yes different issue than #8788. In that issue, shit+del does nothing after you confirm delete. Files and folders remain there.

**Comment by gave92** [comment]
Caused by #8834
