### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by john4641** [files-community/Files#8791]
### Description

crashing when delete something on downloads folder

### Expected behavior

i dont know what to say

### Files Version

Version: 2.1.15.0 

### Windows Version

OS Version: 10.0.19044.1586

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8362433/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8362434/debug_fulltrust.log)

**Comment by gave92** [comment]
Thanks for the report. We're tracking this issue.
