### ISSUE TITLE
Dropbox Smart Sync issue

### ISSUE THREAD

**Issue by rawdogge** [files-community/Files#8793]
### Description

When accessing a Dropbox folder with "Online only" files, it will automaticaly change files to "Local", even if your Dropbox Smart Sync configuration is set to "Allow admin to manage this setting" (or something similar)

### Steps To Reproduce

1. Set Smart Sync to  "Allow admin to manage this setting" [https://ibb.co/jGfDHDC](url) (screencap)
2. Go to any Dropbox folder with "Online Only" files

### Expected behavior

"Online Only" files will automatically set to "Local"

### Files Version

Versión: 2.1.15.0 OS Version: 10.0.22000.556

### Windows Version

Windows 11 21H2 22000.556

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8362948/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8362950/debug.log)

**Comment by gave92** [comment]
Do you have the preview pane open in Files? Any difference if you close it?

**Comment by corylulu** [comment]
I also was seeing this, but it wasn't happening right away. If I left a folder open, periodically I'd see files start changing to Local. It was almost like a periodic scan on the files was causing them to be opened/modified

**Comment by rawdogge** [comment]
> Do you have the preview pane open in Files? Any difference if you close it?

Hi gave. How do I check that?

**Comment by rawdogge** [comment]
> Sorry I think I misunderstood. Do the files change to Local when you select them or is it enough to open a folder and all files inside it are changed to Local?
The documents will change its status once you access the folder.

**Comment by gave92** [comment]
Do you happen to have the "file tags" feature enabled (under Files settings > Experimental)?

**Comment by Josh-65** [comment]
Is this an issue in the preview version? https://files.community/download/preview
