### ISSUE TITLE
Crash extracting a compressed file

### ISSUE THREAD

**Issue by churritomang** [files-community/Files#8796]
### Description

I downloaded a font in a .zip file. I right-clicked the file and left-clicked on the "Extract here..." option. Files then crashed. I restarted the program and attempted again, with this time working as intended.

### Steps To Reproduce

1. Go to .zip file
2. Right click
3. Left-click on "Extract here..."

### Expected behavior

Files program crashes

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.556

### Windows Version

Version	10.0.22000 Build 22000

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8365754/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8365755/debug.log)

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?
