### ISSUE TITLE
Add the compact overlay button to titlebar

### ISSUE THREAD

**Issue by CrypticVader** [files-community/Files#8798]
### Solution/Idea

Add a button to the titlebar to toggle compact mode.
![](https://cdn.discordapp.com/attachments/725514946112127057/958236891176636466/unknown.png)

### Alternatives

Add an option in settings to show this button, similar to how the tab flyout button option.
![](https://cdn.discordapp.com/attachments/725514946112127057/958237694578819123/unknown.png)

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

v2.1.32.0

### Windows Version

Windows 11 22H2 22581.100

**Comment by yaichenbaum** [comment]
@CrypticVader is the current option hard to access? There is also a keyboard shortcut to toggle compact overlay.

**Comment by CrypticVader** [comment]
It's a bit confusing since the option is hidden behind the ellipsis menu. And personally I don't use keyboard shortcuts that much.

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
We don't have plans to implement this change
