### ISSUE TITLE
Drives in sidebar not listed when starting the app

### ISSUE THREAD

**Issue by carlox97** [files-community/Files#8799]
### Description

When I start Files, the sidebar shows that Drives list is expanded (via symbol "∧"), but no drives are listed.
I need to press on Drives one time to collapse ("∨"), and one more type to expand again ("∧"), drives are now listed in sidebar (video attached).

### Steps To Reproduce

1. Open Files
2. "Drives" list empty in sidebar, even though they should be expanded by default (∧)
3. Click on "Drives" twice (first to collapse, then to expand)
4. Drives list appears in sidebar

### Expected behavior

1. Open Files
2. Drives list is showing in sidebar

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.556

### Windows Version

Windows 11 Pro 21H2 22000.556

### Relevant Assets/Logs

https://user-images.githubusercontent.com/31673755/160570282-6ac64c1a-a6fc-4c59-8034-cb135a940ad7.mp4

**Comment by gave92** [comment]
Bug tracked in #6469
