### ISSUE TITLE
Pasting text in search box creates an image

### ISSUE THREAD

**Issue by GeorgeV220** [files-community/Files#8800]
### Description

When I copy an excel column and paste it in the search field, a PNG file is created with the paste value.

### Steps To Reproduce

1. Copy a column from excel
2. Paste it on search field

### Expected behavior

Paste the value and not create the PNG file.

### Files Version

Version: 2.1.33.0 OS Version: 10.0.22000.556

### Windows Version

Windows 11 Pro | 21H2 | 22000.556 | Windows Feature Experience Pack 1000.22000.556.0

### Relevant Assets/Logs

![raw (2)](https://user-images.githubusercontent.com/30936682/160581378-7050c130-94cd-43a5-8a76-f0d29a23733a.png)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #8811
