### ISSUE TITLE
Deleting files on SMB shares does not refresh the folder afterwards

### ISSUE THREAD

**Issue by rursache** [files-community/Files#8807]
### Description

I have a couple of SMB shares mounted on my Windows 11 machine. Each time I delete a file (permanently or not) the parent folder does not refresh. I need to refresh manually in order to make the deleted files disappear 

### Steps To Reproduce

1. Mount a SMB share
2. Delete any file on that share
3. Observe that the deleted file is still there yet you cannot access it and on manual refresh it disappears

### Expected behavior

Refresh automatically or just remove the deleted file from the parent folder contents

### Files Version

Version: 2.1.24.0 OS Version: 10.0.22000.593

### Windows Version

Windows 11 Pro Version	21H2 (22000.593)

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8375061/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8375062/debug_fulltrust.log)

**Comment by gave92** [comment]
Tracked in #5869
