### ISSUE TITLE
Files set to default 

### ISSUE THREAD

**Issue by CarlosRivera4726** [files-community/Files#8810]
### What's the Problem?

I want that you put again to set Files default file explorer win 10 or 11, because this option no show me, ty

### Solution/Idea

Put the option experimental again

### Alternatives

I don't know

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Versión: 2.1.15.0 OS Version: 10.0.19044.1586

### Windows Version

Windows 10 21H2

### Comments

Thank you!

**Comment by yaichenbaum** [comment]
This option is only available in the sideload verison.
