### ISSUE TITLE
Files cannot be removed as the default file manager

### ISSUE THREAD

**Issue by hariganti** [files-community/Files#8813]
### Description

The documentation for Files (as of 2022-03-29) indicates that the setting for making Files the default file manager is under the Experimental tab in settings, but this is not found, making it impossible to remove Files as the default file manager.

![image](https://user-images.githubusercontent.com/16711552/160754306-493030d2-ddc2-47f3-9987-b0c9d0dced84.png)

![image](https://user-images.githubusercontent.com/16711552/160754346-0fcde975-416f-49fa-b339-f59f42c32d38.png)

### Steps To Reproduce

1. Open Files
2. Open Settings
3. Click on the Experimental tab

### Expected behavior

Option for default file manager should appear

### Files Version

Version: 2.1.15.0 OS Version: 10.0.19043.1348

### Windows Version

Edition	Windows 10 Home Version	21H1 Installed on	‎12/‎15/‎20 OS build	19043.1348 Experience	Windows Feature Experience Pack 120.2212.3920.0

### Relevant Assets/Logs

None

**Comment by yaichenbaum** [comment]
As noted in the documentation, this option is currently only available for the sideload version of Files.

**Comment by hariganti** [comment]
When I originally installed Files (from the Windows Store), I had enabled this, which is why Windows + E and folder links open in Files (by default) for me, so I'm not sure when this changed and the option was removed.

**Comment by yaichenbaum** [comment]
@hariganti what happens if you double click the registry file?

**Comment by hariganti** [comment]
Interestingly, it worked this time. The first time, it gave me an error that non-binary files could not be imported. This time, when I double-clicked on it, it opened in Sublime first (so I saw it was saved as a text file instead of a registry file). Upon changing the extension, it worked. I don't know what I did differently, but thank you.
