### ISSUE TITLE
automatic update of drive

### ISSUE THREAD

**Issue by michknu** [files-community/Files#8814]
### What's the Problem?

View does not refresh on network drives for expl after a copy , you need to use F5 or the context menu.

### Solution/Idea

change in the code

### Alternatives

dont know

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Comments

Thanks for the updates

**Comment by Josh-65** [comment]
Merging with #5869
