### ISSUE TITLE
Search in file contents

### ISSUE THREAD

**Issue by GeorgeV220** [files-community/Files#8815]
### What's the Problem?

Files does not search in file contents

### Solution/Idea

Add the option to search in the contents of the files (EG PDFs)

### Alternatives

.

### Files Version

Version: 2.1.33.0 OS Version: 10.0.22000.556

### Windows Version

Windows 11 Pro | 21H2 | 22000.556 | Windows Feature Experience Pack 1000.22000.556.0

**Comment by Josh-65** [comment]
Files search uses the same system as file exploerer. Does it show if you type the same thing in that

**Comment by gave92** [comment]
You may need to type "content:" (localized) before your search term to force searching file contents.

**Comment by GeorgeV220** [comment]
> You may need to type "content:" (localized) before your search term to force searching file contents.

I'll try it when I have access to this PC again.

**Comment by cinqmilleans** [comment]
A new search panel is in preparation and will allow you to filter files easily on many criteria including content. #8495

**Comment by GeorgeV220** [comment]
> A new search panel is in preparation and will allow you to filter files easily on many criteria including content. #8495

This is awesome!! Nice work Mr @cinqmilleans

**Comment by Josh-65** [comment]
Merging with #7124
