### ISSUE TITLE
Auto Adjust Column Width - Especially for File Names

### ISSUE THREAD

**Issue by Bert6376** [files-community/Files#8817]
### What's the Problem?

It seems your software does not 'remember' when I double click on column width. You should consider making this as part or your settings. 

### Solution/Idea

In Settings, allow for automatically adjust column width. Most important is the File Name.

### Alternatives

Double-clicking on column width, the software should remember my preference. 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
This is resolved in `main`.
