### ISSUE TITLE
selection indicator doesn't reset when dragging folder over other folders or EXE files

### ISSUE THREAD

**Issue by alishtamimi** [files-community/Files#8818]
### Description

When I drag an EXE file or folder over other folders in a list, all folders and EXE files I move over get the color (accent windows color) selection indicator on the left and it doesn't reset. 

### Steps To Reproduce

1. go to any folder with a list view of multiple folders and EXE files.
2. select a folder or EXE file.
3. drag the folder/EXE file over other folders.
4. all folders/EXE files you hover over them will get the selection indicator.
5. selection indicator doesn't reset.

### Expected behavior

1. go to any folder with a list view of multiple folders and EXE files.
2. select a folder or EXE file.
3. drag the folder/EXE file over other folders.
4. all folders/EXE files you hover over will get the selection indicator.
5. selection indicator should reset automatically and instantly when you pass it

### Files Version

2.1.34 (preview)

### Windows Version

Windows 11 22H1

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8386111/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8386112/debug_fulltrust.log)

**Comment by alishtamimi** [comment]
https://user-images.githubusercontent.com/93097784/160979573-5e32585a-6944-47f4-a4ad-206c80928dd4.mp4

**Comment by yaichenbaum** [comment]
Merging with #6768
