### ISSUE TITLE
Tick Box

### ISSUE THREAD

**Issue by Someone-Somwhere** [files-community/Files#8819]
### What's the Problem?

I think it would be a good addition to files to have a box next to each item so it would make it easier to select multiple files (that aren't in order.) As pressing the shit key for a long time can be annoying.

### Solution/Idea

Add a tick box (that can be turned off.)

### Alternatives

N/A

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to make multiple files section easier | Should |

### Files Version

Version: 2.1.15.0 OS Version: 10.0.19044.1586

### Windows Version

Edition	Windows 10 Pro Version	21H2 Installed on	‎13/‎02/‎2022 OS build	19044.1586 Experience	Windows Feature Experience Pack 120.2212.4170.0

**Comment by yaichenbaum** [comment]
You can toggle multi select from the toolbar, we're also tracking a couple of feature requests to enhance this feature to always show the check boxes.
![image](https://user-images.githubusercontent.com/39923744/161123139-c3e72576-f76f-41ce-8c58-95944d73c6f7.png)

**Comment by Someone-Somwhere** [comment]
> You can toggle multi select from the toolbar, we're also tracking a couple of feature requests to enhance this feature to always show the check boxes. ![image](https://user-images.githubusercontent.com/39923744/161123139-c3e72576-f76f-41ce-8c58-95944d73c6f7.png)

Thanks, it might look better if the boxes were smaller and if their border were made a bit smaller and rounded to fit in the rest of the style.
