### ISSUE TITLE
After uninstall Files and use standart explorer - Player problem

### ISSUE THREAD

**Issue by koubafire** [files-community/Files#8822]
After uninstall Files and use standart explorer it takes long (30 sec) to open any video (.mkv for example) in any player. If I install Files again and click on mkv in Files it opens very quickly.

If I open player first and choose mkv it works very qiuckly. Maybe is there problem with file assocation between video file - explorer and Files.

EDIT: Ne found info - Filter SmartScreen is a problem. If  I disable smartscreen  it opens MPC-BE in one second.

https://www.neowin.net/news/defender-smartscreen-on-windows-11-beta-build-22581-apparently-causes-video-playback-issues/

**Comment by yaichenbaum** [comment]
This sounds like an issue with File Explorer, can you report this in Feedback Hub?
