### ISSUE TITLE
Clicking on .XML file with preview pane opened, crashes Files

### ISSUE THREAD

**Issue by JowJoris** [files-community/Files#8824]
### Description

When clicking on a file **with preview pane on** with the extension `.XML` (**in all caps**) it crashes Files, renaming the extension to `.xml` fixes the issue.

### Steps To Reproduce

1. Create a file called `test.XML`
2. Add content to the file, example: `<xml></xml>`
3. Click on the file with preview pane opened
4. Crash

### Expected behavior

Succesfully show the code as with `.xml` extension

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.556

### Windows Version

Windows 11 Home 21H2 22000.556

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8396534/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8396535/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #8828
