### ISSUE TITLE
Reduce spacing in "Enter an item name"

### ISSUE THREAD

**Issue by itsWindows11** [files-community/Files#8825]
### Description

There is too much vertical spacing in the "Enter an item name" dialog.

### Steps To Reproduce

1. Create a file or folder
2. On the naming dialog, there's too much vertical space.

### Expected behavior

Reduced spacing

### Files Version

2.1.13.0

### Windows Version

Windows 11 21H2 build 22000.556

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/81253203/161252003-d04dcaf6-6c23-4fd7-b64a-a27d99c03ed1.png)

**Comment by Josh-65** [comment]
There isnt really a point to that since the prompt goes on top of everything. The dialogs are also the same size witch look better in my opinion

**Comment by yaichenbaum** [comment]
This is the default min size, and taking into account what @Josh-65 said, we don't have plans to change this.
