### ISSUE TITLE
Set to Default File Manager option not showing up in Experimental Settings.

### ISSUE THREAD

**Issue by Untxtlxd** [files-community/Files#8827]
### Description

I have recently downloaded Files, but whenever I press windows key + e, it opens up the default file explorer. I searched it up on google and found out about the experimental settings. But when I checked for myself, it wasn't there. Screenshot of the Experimental Settings Page attached here - 
![ExpSettings](https://user-images.githubusercontent.com/98937958/161264652-f8cda816-5c99-44c7-8286-7e2c63507fcd.JPG)

Is it disabled/moved to a new settings page? I have checked all over the app still couldn't find it. Please let me know.

### Expected behavior

Expected that the Set to Default File Manager would be present in Experimental Settings.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.19043.1586

### Windows Version

Windows 10 21H1 10.0.19043 Build 19043

### Relevant Assets/Logs

![ExpSettings](https://user-images.githubusercontent.com/98937958/161265305-a7549824-a021-41af-a446-805f3894c766.JPG)

**Comment by inflavius** [comment]
![Screenshot 2022-04-01 185832](https://user-images.githubusercontent.com/102809611/161273125-318221d1-79b6-4656-982f-790e1b104a8a.png)

**Comment by Josh-65** [comment]
It's only available in the sideload version https://files.community/download/stable
