### ISSUE TITLE
Cache sidebar & context menu items

### ISSUE THREAD

**Issue by fabian-st** [files-community/Files#8830]
### What's the Problem?

When opening the application or performing a right click on a folder item, the sidebar / context menu items take a few seconds to build up, which interrupts one's workflow.

### Solution/Idea

Cache the sidebar and context menu items and reload these items in the background. If there are changes present, switch the sidebar and context menu items after the changes have finished loading.

### Alternatives

n.a.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
Thank you for your feedback. The sidebar items are cached but the cache still needs to be loaded on startup, the context menu items are cached as well but there are several checks that need to be done to ensure that the correct items are being shown for each file type. We're looking into ways to improve the speed and we're open to feedback if you have any other ideas.
