### ISSUE TITLE
Internet Download Manager opening the old File Manager

### ISSUE THREAD

**Issue by koreonsmith** [files-community/Files#8832]
### Description

After using files for a while, i downloaded an antivirus. And inside IDM (Internet Download Manager) there's a feature called show download complete dialog, basically a window that says "hey your file is successfully downloaded and theres 3 botton that says "Open", "Open Folder" and "Cancel". The issue here is when i click Open folder it just lead me into old File Manager. 
This happen also in the downloaded file list.
![Screenshot 2022-04-02 110803](https://user-images.githubusercontent.com/102844544/161366420-7c26551e-cd23-4782-9a26-1198964bd0b3.png)

### Steps To Reproduce

1. Open IDM
2. Go to browser to download something (using IDM) then open IDM 
3. Go to downloaded file list on IDM 
4. Right click on any downloaded files then click open folder
5. IDM will open the old File Manager window instead of Files 

### Expected behavior

This happens every time IDM try to open file dialog appear, When you interact with downloaded file, then try to open where the downloaded file is located, IDM will open the old File Manager instead of Files, even if you have enable the "Set files as the default file manager"

### Files Version

Version: 2.1.24.0 OS Version: 10.0.19042.1586

### Windows Version

Windows 10 Home Single Language 20H2 19042.1586

### Relevant Assets/Logs

![Screenshot 2022-04-02 114900](https://user-images.githubusercontent.com/102844544/161366812-8055620a-9be2-4cb3-a4aa-ba76d5d62b9a.png)
![Screenshot 2022-04-02 115023](https://user-images.githubusercontent.com/102844544/161366814-07911ab6-c5f6-4fe7-b5e0-2ea6fa3ee20c.png)
![Screenshot (924)](https://user-images.githubusercontent.com/102844544/161366899-4f6bc4bc-893d-4517-a368-8688378556cf.png)

**Comment by gave92** [comment]
Appears to work correctly on Windows 10, IDM 6.40, Files 2.1.35
