### ISSUE TITLE
Delete file dialog - PrimaryButton gets no focus

### ISSUE THREAD

**Issue by mafra99** [files-community/Files#8834]
### Description

When trying to delete a file, the delete button does not get focused by default.

### Steps To Reproduce

1. Go to any directory containing a file or folder
2. Try to delete any file using the delete button or the delete key of the keyboard
3. See that the button Delete is not focused

### Expected behavior

That the delete button is focused by default.

### Files Version

Version: 2.1.35.0 OS Version: 10.0.22581.200

### Windows Version

Windows 11 22H2 (OS Build 22581.200)

### Relevant Assets/Logs

https://user-images.githubusercontent.com/56681014/161382961-52a0fd90-0f67-4b56-8151-16668f08837d.mp4

**Comment by mafra99** [comment]
I think the problem is that the property *PrimaryButtonEnabled* is false by default, and is only changed to true after the dialog is loaded (in the [RootDialog_Loaded](https://github.com/files-community/Files/blob/main/src/Files.Uwp/Dialogs/FilesystemOperationDialog.xaml.cs#L120) method of the codebehind)


Maybe caused by this change: https://github.com/files-community/Files/commit/dafba797db437c4925ba27745c0b0c45e17ddce6#diff-843eabee635a202afd595c3a81bf70b3bb7d96937fb6d97dc6aaa55844274bfbR117

Before it was called in the constructor

**Comment by gave92** [comment]
I was thinking the same (though I can't reproduce the issue). Given that since #5782 the primary button is always enabled we cound just remove the `IsPrimaryButtonEnabled="{x:Bind ViewModel.PrimaryButtonEnabled, Mode=OneWay}"` and be done with it.

**Comment by gave92** [comment]
@mafra99 could you check if #8836 does the job (moves enabling the primary button before the Loaded event, as you suggested)? The Release build from the PR is [here](https://dev.azure.com/filescommunity/db556b89-8bf0-4c03-8053-434c8f8714ff/_apis/build/builds/11025/artifacts?artifactName=drop&api-version=7.0&%24format=zip).

**Comment by mafra99** [comment]
@gave92  PR looks good to me and the button gets focused by default

https://user-images.githubusercontent.com/56681014/161388178-fb7dd65c-2cb2-4e56-a54b-f713d7a21002.mp4

**Comment by gave92** [comment]
Thanks!

**Comment by d2dyno1** [comment]
Closed with #8836
