### ISSUE TITLE
Favorites are collapsed while their status shows unfolded

### ISSUE THREAD

**Issue by kyubson** [files-community/Files#8835]
### Description

The Favorites are collapsed when starting Files, however their icon is showing that it should be unfolded. It appears that its status is unfolded, however the items are not listed under it. User needs to click 2 times to finally see the items unfolding. After that, the collapse / unfold toggle works as excepted, with just one click.

### Steps To Reproduce

1. Open Files
2. Unfold Favorites
3. Close Files
4. Open Files again
5. Favorites will appear as collapsed, however the icon is showing that it should be unfolded. User needs 2 clicks to display the items under Favorites.

### Expected behavior

The list of items under Favorites should appear when opening Files, since its status was unfolded when Files was closed.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.556

### Windows Version

Windows 11 21H2 22000.556

### Relevant Assets/Logs

![Files_bug1](https://user-images.githubusercontent.com/101720566/161383664-4bc51f2a-74b3-4b73-a78c-507bbc0e6743.jpg)

**Comment by gave92** [comment]
Merging with #6469
