### ISSUE TITLE
Not able to set as default

### ISSUE THREAD

**Issue by IlPeppeDelPorcoDio** [files-community/Files#8838]
### Description

The switch to set the files app as a default file explorer doesn't show up anymore. It used to be an option, and it worked well. Now I can't do that anymore, and this kind of makes the whole app pointless...
![immagine_2022-04-02_234956](https://user-images.githubusercontent.com/102881385/161402415-ab51b800-3736-4093-8e6a-80b81825c9ae.png)

### Steps To Reproduce

In the settings, experimental.

### Expected behavior

It should show up.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.19044.1586

### Windows Version

Windows 10 21H2

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8403422/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8403423/debug.log)

**Comment by gave92** [comment]
At Microsoft request, the option is only available in the [sideloded version](https://files.community/download/stable)

**Comment by IlPeppeDelPorcoDio** [comment]
still, when I click to activate, and then close the settings, it resets to it being off

**Comment by IlPeppeDelPorcoDio** [comment]
I just checked and actually the option turns itself off after a few secs

**Comment by gave92** [comment]
Do you get the request for administrator when you turn it on?

![image](https://user-images.githubusercontent.com/9673091/161403510-f15e460f-aad9-4ef5-8d61-4b93d27dd271.png)

**Comment by IlPeppeDelPorcoDio** [comment]
no this doesn't pop up. and it is weird, since it did before

**Comment by gave92** [comment]
Indeed it looks like there's some issue with the stable version.
- Does you windows user name contain a space?
- Could you check if you have the same issue with the [preview version](https://files.community/download/preview)?

**Comment by IlPeppeDelPorcoDio** [comment]
yeah I do have the same issue w the preview version

**Comment by gave92** [comment]
@yair100 it looks like the stable sideloaded package (v2.1.24) does not include #8780, is that correct?

This issue appears different though, @IlPeppeDelPorcoDio could you upload the two new log files?

Also, could you post a screenshot of the contents of this folder? `%LocalAppData%\Packages\Files_1y0xx7n9077q4\LocalState\FilesOpenDialog\`

**Comment by IlPeppeDelPorcoDio** [comment]
[debug.log](https://github.com/files-community/Files/files/8403513/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8403514/debug_fulltrust.log)
that folder doesn't appear to be existing

**Comment by gave92** [comment]
I'm stumped, if you with you may try the "manual" method:
- Download this zip: [SetFilesAsDefault.zip](https://github.com/files-community/Files/files/8403524/SetFilesAsDefault.zip)
- Unpack it in `%LocalAppData%\Files` (you'll need to create the folder)
- Run "SetFilesAsDefault.reg"

**Comment by IlPeppeDelPorcoDio** [comment]
It did work thanks, also, will I be able to download updates if I have this version installed?

**Comment by gave92** [comment]
Glad it's working! Yes, the sideload version has auto-update.

**Comment by IlPeppeDelPorcoDio** [comment]
ok thank you so much for the help!

**Comment by yair100** [comment]
> @yair100 it looks like the stable sideloaded package (v2.1.24) does not include https://github.com/files-community/Files/pull/8780, is that correct?

@gave92 that's correct, we're going to wait until the next major release to bring this change to the stable version.
