### ISSUE TITLE
Cannot open tab on current desktop

### ISSUE THREAD

**Issue by 1604042736** [files-community/Files#8839]
### What's the Problem?

I opened two virtual desktops. Files was opened on one of them. When I pressed Win + E on the other desktop, I jumped to the desktop with files open.

### Solution/Idea

No matter how many virtual desktops there are, open files only on the current desktop.

### Alternatives

No matter how many virtual desktops there are, open files only on the current desktop.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish Y | Could |

### Files Version

2.1.13.0

### Windows Version

Windows 10.0.19042.1586

**Comment by yaichenbaum** [comment]
You can change this behavior by toggling the option to open a seperate instance.
![image](https://user-images.githubusercontent.com/39923744/161407303-29f848c3-1545-494b-bc67-a58f21d8fd24.png)
