### ISSUE TITLE
Right click menu is too slow

### ISSUE THREAD

**Issue by 1604042736** [files-community/Files#8844]
### What's the Problem?

When I right-click, the right-click menu takes about a second or two to load additional options. The native resource manager of the system does not need to wait.

### Solution/Idea

Make the right-click menu load faster.

### Alternatives

Make the right-click menu load faster.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to accomplish X | Should |

### Files Version

2.1.13.0

### Windows Version

Windows 10.0.19042.1586

**Comment by gave92** [comment]
Merging with #4180

**Comment by yair100** [comment]
@wyj2006 we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
