### ISSUE TITLE
The default themes vanished forever!

### ISSUE THREAD

**Issue by AlvsDias** [files-community/Files#8849]
### Description

I use the app's default theme and all of them vanished! What do i do?

### Steps To Reproduce

1. Install
2. Wait
3. Default themes vanished!

### Expected behavior

1. Install
2. Use
3. Themes still

### Files Version

2.1.15.0

### Windows Version

Windows 11 10.0.22000.593

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/98051617/161446820-25b580da-18c9-4cf7-bbb3-b2f150e7d58e.png)

**Comment by Josh-65** [comment]
Its a known issue. You need to backup your setting in files settings > about > manage settings first as the get removed. then reset the app via windows settings > apps > files > advanced options.

**Comment by AlvsDias** [comment]
I reinstaled this thing 10 times .:..:.

**Comment by Josh-65** [comment]
The data files are saved for a period of time after an uninstall. Doing the instruction above will wipe the data and bring them back.

**Comment by AlvsDias** [comment]
And i will re-write the settings everytime as i need to change the theme? (0_0)

**Comment by AlvsDias** [comment]
Please answer with more info. I'm a dev too.

**Comment by Josh-65** [comment]
If you follow the instructions above you can export the settings then reset the app to get the themes and terminal options back as that what currently get broken after and update (only known cause as far as I know). Then you can restore the settings in the same page as the backup option is. Thats all thats known right now.

**Comment by AlvsDias** [comment]
Ok.
![image](https://user-images.githubusercontent.com/98051617/161447534-5cf33ef5-324a-42ae-b1f8-949c2368c22b.png)
Now they're Back!

**Comment by gave92** [comment]
Merging with #7058 / #8100
