### ISSUE TITLE
Right ALT key shortcuts colliding with Polish keyboard

### ISSUE THREAD

**Issue by Firidan** [files-community/Files#8852]
### Description

Just like in title
When I'm pressing R ALT+ A it's select all
R ALT + S is hiding navigation panel on the left.

It's colliding with Polish diactric marks: ą, ś - they are made by pressing RALT+ corresponding letter
So I can't put those letters in file name.

### Expected behavior

Make option to disable Right ALT as shortcut key

### Files Version

Wersja: 2.1.15.0 OS Version: 10.0.22000.556

### Windows Version

indows 11 Pro 21H2 Compilation 22000.556 Pakiet funkcji Windows 1000.22000.556.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8407995/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8407996/debug_fulltrust.log)

**Comment by Josh-65** [comment]
@yaichenbaum

**Comment by oleklukasiewicz** [comment]
@yaichenbaum any suggestions on how we can solve this?

**Comment by yaichenbaum** [comment]
I'm curious what other apps do for this scenario but either way, users will have a workaround when we implement custom shortcuts.

**Comment by ferrariofilippo** [comment]
@yair100 I think this is the same as #6150

**Comment by yaira2** [comment]
@ferrariofilippo in the sense that it was already resolved or just the same idea?

**Comment by ferrariofilippo** [comment]
Yes, I mean the problem is the same: in both cases they're pressing `AltGr+A` but using different keyboard layouts

**Comment by yaira2** [comment]
Merging with #6150

**Comment by yaira2** [comment]
Microsoft fixed this issue in WinAppSdk 1.5 and it'll be included in the next version of Files.
