### ISSUE TITLE
Bug: Preview pane is missing grid splitter cursor

### ISSUE THREAD

**Issue by Reverend-Jim** [files-community/Files#8856]
Pressing CTRL-P toggles the preview panel. The preview panel consists of two parts. The first part is the actual preview. The second part is the file information info. Of these two parts, by far the more important is the actual preview. I am mystified as to why much more space is allocated to the file info portion. I would prefer to see a more 90-10 split in favour of the preview. Or better yet, I would prefer to be able to toggle the info off completely.

The splitter between the preview window is so thin that while trying to grab and drag it, I instead end up selecting a different file. It requires extremely precise mousing to be able to keep the cursor over the splitter while left clicking. Is there any way to make it a little less sensitive?

**Comment by gave92** [comment]
For point (1) try to right click on the preview, there should be the option to turn off the file info.

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval. Title should be change to something like "Increase drag area for preview pane spliter"

**Comment by yaichenbaum** [comment]
@itsWindows11 do you want to work on this one?

**Comment by itsWindows11** [comment]
> do you want to work on this one?

I can't work on it right now, but is it using the same splitter as the grid splitter in the top bar of the files list in details view?

**Comment by yaichenbaum** [comment]
Yeah, both of them use the same control.

**Comment by GabrieleMessina** [comment]
Hi, can i try to fix this?

**Comment by GabrieleMessina** [comment]
I've noticed that the left side pane (SidebarControl) has a splitter with a hovering state that changes its style, while the splitter for the preview pane doesn't. Is this behaviour intentional or is it another problem to be solved?

**Comment by Josh65-2201** [comment]
They should probably should use the same styles. Sidebar one seem to be a better option. 
But this issue hasn't been approved yet so should wait for @yair100  to confirm what should be done. You can work on any in the project though. https://github.com/orgs/files-community/projects/3/views/2

**Comment by GabrieleMessina** [comment]
@Josh-65  oh, i didn't notice it wasn't confirmed. Thanks for the advice!

**Comment by yaira2** [comment]
@GabrieleMessina this is ready to build, do you still want to work on it?

**Comment by GabrieleMessina** [comment]
@yair100 yes, thanks

**Comment by yaira2** [comment]
@Reverend-Jim this issue will be fixed in the next release.
