### ISSUE TITLE
Display theme accent color in theme picker

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#8858]
### What's the Problem?

In the settings menu there is a Color section but you can only choose Auto/Light/Dark. Several themes, including the default theme, use accent color, but it is not configurable in settings.

### Solution/Idea

We could add an indicator (i) containing an explanatory message and a link to open the Windows color panel.

### Alternatives

We can provide a color picker to change the accent color in the color section.

We can also, for each theme, display if it uses the accent color or not.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
Some themes change the accent color in order to ensure proper contrast, I think we can add the accent color to the little preview in the theme section.

**Comment by yaira2** [comment]
Custom themes are currently revamped so this is no longer applicable.
