### ISSUE TITLE
Crash when click on Path in home page.

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#8859]
### Description

In the git version (commit #8854), the application has a bug that can cause the application to crash.

### Steps To Reproduce

1) Open Files in Home page.
2) Clic on the adress path in the navigation bar.
3) Crash.

### Expected behavior

Display the suggestions

### Files Version

commit #8854

### Windows Version

Windows 11

### Relevant Assets/Logs

The error is in NavToolbarViewModel, line 1052. currPath cannot be null.

**Comment by yaichenbaum** [comment]
@cinqmilleans the exception should be handled and you should be able to continue debugging the app, can you confirm?

**Comment by cinqmilleans** [comment]
@yair100 Yes indeed.

**Comment by yaichenbaum** [comment]
@cinqmilleans do you want to work on a fix?

**Comment by cinqmilleans** [comment]
@yair100 Ok. I need to work a bit on small fixes to take my mind off the refactoring. I will propose several pr minors in the coming days.
