### ISSUE TITLE
Partially hidden icon

### ISSUE THREAD

**Issue by pullapint** [files-community/Files#8860]
### Description

When on the Home screen, the icon for OS (C:) drive is partially hidden. It happens regardless of the size of the window.

### Steps To Reproduce

Open app
Click on "Home"
OS (C:) is partially hidden. The other drive letters are fine.

### Expected behavior

To be able to see the icon for C drive

### Files Version

Files 2.1.15.0

### Windows Version

Windows 10 Pro v1809, OS build 17763.1098

### Relevant Assets/Logs

![Files screenshot](https://user-images.githubusercontent.com/51059741/161818751-614a7fbb-f344-407a-a65e-620ece2a3372.jpg)

**Comment by gave92** [comment]
Thanks for the report. It happens if the "i" button is shown due to the drive being almost full.

**Comment by pullapint** [comment]
Quick and easy. Thank you.

**Comment by gave92** [comment]
@winston-de you noticed this issue too, right? Do you know if it's fixed on main?
