### ISSUE TITLE
Native Compress Option

### ISSUE THREAD

**Issue by cmactavish** [files-community/Files#8862]
### What's the Problem?

Lack of native 'Compress to Zip' option when right clicking files/folders.

### Solution/Idea

Add a 'Compress to Zip' option to right click menu, as is present in File Explorer
![14-06-22-121420](https://user-images.githubusercontent.com/55484398/161882520-36c74f1e-e25f-454b-b387-98b7426af928.png)

### Alternatives

Adding a third party compression tool which can then be added to context menus. 

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.556

### Windows Version

Windows 11 Home, 21H2, 22000.556

**Comment by yaichenbaum** [comment]
Merging with #45
