### ISSUE TITLE
When scrolling down with scroll bar, Files crashes.

### ISSUE THREAD

**Issue by Sunrise-Sea** [files-community/Files#8863]
### Description

Hello, 

I was working with my files when I required to use a different menu item that lay to the bottom of the menu and I decided to use the scrollbar but when I do it, the app crashes. Please fix this.

And in case you need it, default file explorer in Windows also crashes, so please respond if it can only be fixed when the default file explorer is fixed.

### Steps to crash
1. Went to my working directory.
2. Right clicked.
3. Used the **scroll bar** in order to scroll down the menu items.
4. App crashed.

> It also happens with the default file explorer

### Expected behavior

I expected the menu to scroll down but it crashes.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.593

### Windows Version

Windows 11 21H2 22000.593

### Relevant Assets/Logs

Here are the logs...

[debug.log](https://github.com/files-community/Files/files/8424124/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8424125/debug_fulltrust.log)

**Comment by Josh-65** [comment]
Is this still an issue?
