### ISSUE TITLE
Directories and drives on left pane do not have tree expanding feature like Windows Explorer

### ISSUE THREAD

**Issue by ialhabbal** [files-community/Files#8864]
### What's the Problem?

Directories and drives on left pane do not have tree expanding feature like Windows Explorer. Right now if I want to move a file from the right pane to a folder I have to actually open the destination folder in a new tab to be be able to move the file. In Windows Explorer I could drag it from the right pane to the left pane where the destination directory had been expanded (tree feature) as shown in the below two screenshots.

![No Tree Feature](https://user-images.githubusercontent.com/17925089/161919557-30a81048-5b88-4e09-88e4-41c2857bf2c6.jpg)
![Tree Feature](https://user-images.githubusercontent.com/17925089/161919595-88469ef2-53f2-4e1e-b5e6-d1286eb1fa6c.jpg)
.

### Solution/Idea

Develop a tree expanding feature for directories and drives on left pane like Windows Explorer. It is a great feature and would absolutely make this explorer perfect.

### Alternatives

The tree expanding feature is a must have for functionality.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.1.39.0

### Windows Version

Windows 11 22H2 (OS Build 22581.200)

**Comment by yaichenbaum** [comment]
Thank you for your feedback, we're tracking support for a dedicated tree view layout #1928 but in the meantime, you can use the column layout to achieve a similar result/

**Comment by cyberfrog77** [comment]
This is the only thing why I have uninstalled Files. Would appreciate if this could be added.

**Comment by xxTheGoDxx** [comment]
Same for me. Was loving the app when I discovered it until I realized my folders wouldn't auto expand like I am used to it in the Windows file explorer for the 25 years I use PCs.

**Comment by yair100** [comment]
@ialhabbal @cyberfrog77 @RaffCode-Personal Tree View is currently available in preview https://files.community/download. It will be included in the next stable release.
