### ISSUE TITLE
Windows Defender detecting as virus

### ISSUE THREAD

**Issue by vittring** [files-community/Files#8866]
### Description

Windows Defender is out of nowhere detecting this as Trojan:Win32/Wacatac.B!ml

### Steps To Reproduce

1. Download the stable installer from [here](https://files.community/download/stable).
2. Double click package file.
3. Install.
4. Launch Files with Start Menu or automatically with installer.
5. Click on "Settings" > "Experimental".
6. Flip switch to "Set Files as the default file manager".
7. Reboot Windows normally.

### Expected behavior

This action should install Files for the user with the package installer and should set Files as the default file manager instead of the File Explorer. It should install version 2.1.24.

### Files Version

2.1.24

### Windows Version

Windows 10 10.0.19044.1620

### Relevant Assets/Logs

Windows Defender detects Files version 2.1.39.
![2022-04-06_09-54](https://user-images.githubusercontent.com/82048816/161999344-f65ef34f-7d73-454e-97ca-2c6d519385d9.png)

![2022-04-06_09-51](https://user-images.githubusercontent.com/82048816/161999349-24f9ab6b-891e-4049-a95b-d492473e433d.png)

![2022-04-06_10-37](https://user-images.githubusercontent.com/82048816/162000159-1ff1bb97-c6be-4da6-baad-07042ca44c82.png)

![2022-04-06_10-42](https://user-images.githubusercontent.com/82048816/162001569-e35c26f7-b07a-4358-837a-e4adf064bcda.png)

![2022-04-06_10-44](https://user-images.githubusercontent.com/82048816/162001571-4d4aacfc-dbed-4dc6-9909-4758787efaf2.png)

![2022-04-06_10-43](https://user-images.githubusercontent.com/82048816/162001572-54da9af0-73a3-41c1-bd87-4a8d76d0221e.png)

![2022-04-06_10-49](https://user-images.githubusercontent.com/82048816/162002734-8d083f03-a7d5-47a1-8c9a-bd66bf4ea02a.png)

[debug.log](https://github.com/files-community/Files/files/8427792/debug.log)

[debug_fulltrust.log](https://github.com/files-community/Files/files/8427793/debug_fulltrust.log)

**Comment by vittring** [comment]
I'm going to open this binary and the package installer in Remnux to investigate further.

**Comment by yaichenbaum** [comment]
The only reason I can think of is that it doesn't like the fact that the program is modifying the registry. We're going to look into signing the launcher to avoid false positives in the future.

**Comment by vittring** [comment]
I couldn't find anything useful in FlareVM either. I'll close this unless I find anything else, but I am unable to recreate the scenario where it is actually quarantined by AV. It forced me to uninstall the program, which only succeeded partially because I couldn't access quarantined files. Then I rebooted and it allowed me to access File Explorer again to remove the rest of the local files and reinstall the package.
