### ISSUE TITLE
Random Crashes

### ISSUE THREAD

**Issue by Peramonis** [files-community/Files#8867]
### Description

I can't find a consistent pattern, but often when trying to open a folder, the app simply crashes and closes, then I have to open it again and all the tabs are lost. 

### Expected behavior

I expected the folder to open

### Files Version

2.1.15.0

### Windows Version

Windows 11 Home Single Language 21H2 22000.556

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8428034/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8428035/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
This issue should be resolved in the preview version of Files https://files.community/download/preview.
