### ISSUE TITLE
can't remove "set as default" (Back to File Explorer)

### ISSUE THREAD

**Issue by eho9734** [files-community/Files#8868]
### Description

unsatisfied of File, i can't set File Explorer as default.
The menu vanished is Experimental

On W10
Store Uploaded
V 2.1.15.0
![Capture d’écran 2022-04-06 185613](https://user-images.githubusercontent.com/97898017/162004383-da7234a1-70a4-45f7-a491-3f8afd3b6293.png)

??? Removed set as default option from store version #8474

### Expected behavior

I Want File Explorer default BAck

### Files Version

V 2.1.15.0

### Windows Version

w10

### Relevant Assets/Logs

![Capture d’écran 2022-04-06 185810](https://user-images.githubusercontent.com/97898017/162004832-e013212a-9ed7-49df-ad95-2af400ea3c5b.png)

**Comment by Crwmy** [comment]
hello @eho9734,
this feature has been removed in the Windows Store version by request from Microsoft. 

If you want to use the experimental setting of making Files your default file manager, you need to sideload the app from [files.community ](https://files.community/).

**Comment by eho9734** [comment]
👍
Thanks

I still give it a try !
