### ISSUE TITLE
View: List (as in the default Windows explorer)

### ISSUE THREAD

**Issue by DezMono** [files-community/Files#8874]
### What's the Problem?

Just really missing the view: The list (which is in the default Windows Explorer)

### Solution/Idea

You managed to migrate everything based on the Windows Explorer view. I hope you can make a "view: List" as well.

### Alternatives

- 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.1.15.0

**Comment by yaira2** [comment]
@DezMono thank you for your patience, I'm excited to share that a List View layout will be included in the next release.
