### ISSUE TITLE
Crash when loading SMB share from link in "Favorites"

### ISSUE THREAD

**Issue by austincummings** [files-community/Files#8877]
### Description

Occasionally have a hard crash happen when I load a local SMB share from my favorites.

### Expected behavior

No crash

### Files Version

2.1.15.0

### Windows Version

Windows 11 Pro 21H2 22000.593

### Relevant Assets/Logs

None

**Comment by gave92** [comment]
Thanks for the report. Please upload the debug logs (the two ".log" files from Files settings > About > open log location).

**Comment by austincummings** [comment]
Seems to crash more often than just when clicking the SMB share from favorites, this could probably be merged with #8759.

I reinstalled using the sideloaded version. Here's the logs from right after the first crash I encountered after reinstalling
[debug_fulltrust.log](https://github.com/files-community/Files/files/8448259/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8448260/debug.log)
.

**Comment by gave92** [comment]
Merged with #8759.
