### ISSUE TITLE
Make Default File Manager

### ISSUE THREAD

**Issue by cmactavish** [files-community/Files#8880]
### Description

I've just had to rebuild my system and on reinstalling Files, I can no longer find the option to make Files the default file explorer. Has this feature be moved or removed?

### Expected behavior

Go to Settings / Experimental

Find the 'Make default' option

### Files Version

Version: 2.1.15.0

### Windows Version

Windows 11 Home, 21H2, 22000.556

### Relevant Assets/Logs

N/A

**Comment by gave92** [comment]
At Microsoft request the option was removed from the Store version. It's available for the [sideloaded version](files.community/download/preview).

**Comment by cmactavish** [comment]
Dickheads! Thanks for the info will try sideloading. Does the sideloaded
version update? Or will I just need to keep an eye out for updates?

Thanks again.
-
Chay MacTavish
+61 (0)419 461 632
chaymactavish.com <https://www.chaymactavish.com>

**Comment by gave92** [comment]
Sideloaded version has auto update 👍. 
The link above is for the beta/preview version. On files.community you can also find the "stable" sideloaded package but it currently has a bug for setting Files as default.
