### ISSUE TITLE
ondrive crash

### ISSUE THREAD

**Issue by ludo3163** [files-community/Files#8881]
### Description

Hello, I see many file crashes when I work on ondrive files. File must restart often.

### Expected behavior

Hello, I see many file crashes when I work on ondrive files. File must restart often.

### Files Version

Version : 2.1.15.0 OS Version: 10.0.19044.1586

### Windows Version

windows 10

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8449673/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8449674/debug.log)

**Comment by gave92** [comment]
Merging with #8599
