### ISSUE TITLE
Trying to open desktop folders does nothing

### ISSUE THREAD

**Issue by FrostBird347** [files-community/Files#8883]
### Description

After setting Files as the default file manager, it is unable to open any folders on the desktop or open the log location.
Opening folders via task manager and the start menu's "Open file location" option does work.
Restarting does not seem to have any effect, trying to open these folders does not add anything to either logs.

### Steps To Reproduce

1. Try to open a folder on the desktop and see it open with file explorer
2. Set Files as the default manager
3. Try to open a folder on the desktop and see that it doesn't open
4. Restart
5. Try step 3 again and witness the same result as before
6. Uncheck the "Set Files as the default file manager" option
7. Try step 1 again and witness the same result as before

### Expected behavior

Files should be able to open files on the desktop and the log location.

### Files Version

2.1.24.0

### Windows Version

Windows 10 21H2 19044.1586

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8451308/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8451315/debug_fulltrust.log)

**Comment by gave92** [comment]
Do you get any error? Or simply nothing happens?

**Comment by gave92** [comment]
Does this hold for desktpp recycle bin and this PC as well?

**Comment by FrostBird347** [comment]
> Does this hold for desktop recycle bin and "this PC" as well?

Yeah, it does apply to the recycle bin.
I don't have "this PC" on my desktop, however I assume opening it would have the same outcome.

**Comment by gave92** [comment]
Could you check what happens if you give the following commands in a CMD prompt? Does Files open?
- `"%localappdata%\Files\FilesLauncher.exe" "C:\"`
- `"%localappdata%\Files\FilesLauncher.exe" "C:\Users\<USERNAME>\Desktop\<SOME FOLDER>"` <- put some valid path here

You may also try switching to the [preview](https://files.community/download/preview) version which has some related bugs fixed (turn off the set as default  option before updating).

**Comment by FrostBird347** [comment]
> Could you check what happens if you give the following commands in a CMD prompt? Does Files open?
> 
> * `"%localappdata%\Files\FilesLauncher.exe" "C:\"`
> * `"%localappdata%\Files\FilesLauncher.exe" "C:\Users\<USERNAME>\Desktop\<SOME FOLDER>"` <- put some valid path here
> 
> You may also try switching to the [preview](https://files.community/download/preview) version which has some related bugs fixed (turn off the set as default option before updating).

Trying both of these commands appears to put something else in focus, but nothing else happens.

This issue still exists on the preview version, however command prompt comes back in focus a few seconds after running the command.

**Comment by FrostBird347** [comment]
Turns out that my antivirus was blocking it in both versions.
