### ISSUE TITLE
Add an option to implement mac's drag and drop feature on file selector windows

### ISSUE THREAD

**Issue by FrostBird347** [files-community/Files#8884]
### Solution/Idea

On mac, attempting to drag a file into a file upload window or file download/save window make the window navigate to the folder containing that file. Attempting to drag a folder will navigate the window into the folder.
Currently, dragging the file/folder into this window will only copy or move it there.

Suggested behaviour: 

https://user-images.githubusercontent.com/39435218/162435508-cb59aaf1-e7da-4a5c-90b9-d38baadd08fb.mov

Current behaviour: 

https://user-images.githubusercontent.com/39435218/162435680-1b543cca-24d5-424b-b221-77165e20b6ca.mp4

### Alternatives

I guess you could instead add a shortcut to copy the folder path, however that would be both more time consuming that the above solution and it would be barely any better than manually copying the file path.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Navigate to the folder containing whatever file was just dragged inside the window if it is a upload/load or download/save prompt | Must |
| Navigate inside a folder that was just dragged inside the window if it is a upload/load or download/save prompt | Could |
| Select the file in the prompt | Could |

### Comments

I have no idea what this feature actually is called so forgive my poor naming of this issue.

**Comment by gave92** [comment]
At the moment we don't control the file open/save dialog. It's still regular explorer. I'm not sure if we can impememt this.

**Comment by FrostBird347** [comment]
> At the moment we don't control the file open/save dialog. It's still regular explorer. I'm not sure if we can impement this as shown in the video.

Would it be possible to add a menu option to navigate to the file, with the "Copy here", "Move here" and "Create shortcut here" options?

**Comment by gave92** [comment]
That we could do, it obviously does add some extra steps and you'd need to drag items by right click.

**Comment by yaichenbaum** [comment]
? Would it be possible to add a menu option to navigate to the file, with the "Copy here", "Move here" and "Create shortcut here" options, or is that also outside of it's control?

I think this can be done so we're tracking this in a separate issue.

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
This isn't something we can do on our end as we don't control the file pickers. We encourage sharing this feedback with the File Explorer team on the Feedback Hub.
