### ISSUE TITLE
Navigate to dragged file option

### ISSUE THREAD

**Issue by FrostBird347** [files-community/Files#8887]
### What's the Problem?

refer to #8884

### Solution/Idea

Add an option to navigate to the file with the "Copy here", "Move here" and "Create shortcut here" options as a temporary solution to #8884 until Files has implemented their own file save/open dialogue window:

https://user-images.githubusercontent.com/39435218/162435680-1b543cca-24d5-424b-b221-77165e20b6ca.mp4

### Alternatives

Immediately moving to that location instead of having an option has been discussed in #8884, however it is not a viable solution without a custom file open/save window.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Add an option to navigate to the dragged file with the "Copy here", "Move here" and "Create shortcut here" options | Must |

### Comments

I was recommended to move this temporary solution for issue #8884 into a new feature request.

**Comment by yaichenbaum** [comment]
Merging with #1396
