### ISSUE TITLE
Disable some shortcuts while renaming/creating/searching for files

### ISSUE THREAD

**Issue by oleklukasiewicz** [files-community/Files#8890]
### What's the Problem?

Some shortcuts like Ctrl + Alt + S or Ctrl + A collide with some keyboard (look #8852). 

### Solution/Idea

We can disable some keyboard shortcuts, such as Alt and Shift, when renaming/creating or searching for files without replacing them.

### Alternatives

Change some shortcuts to only use left Alt or change them completely to remove the Alt/Shift keys from them. 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Fix shortcut collisions with some keyboards| Must |
| Change shortcuts | Could |
| Force shortcuts to use only left Alt key | Could |
| Disable some shortcuts while renaming/creating/searching for files | Could |

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.593

### Windows Version

Windows 11 21H2 22000.593

**Comment by Josh-65** [comment]
Merging with #8852
