### ISSUE TITLE
App fails to install on Atlas OS

### ISSUE THREAD

**Issue by CodeCubeNeo** [files-community/Files#8892]
### Description

I try to install the sideload version of files app with the app installer and the installer fails (App installation failed with error message: Class not registered (0x80040154)). I can however install files no problem from microsoft store. I am using Atlas OS which is a modifed version of the windows 10 system. I am just asking why does the sideload package fail, if the store version gets normally installed?

### Expected behavior

It should install as it does from the microsoft app store.

### Files Version

Latest (2.1.24)

### Windows Version

Atlas OS faceit edtition v. 5.0.1.

### Relevant Assets/Logs

none

**Comment by yaichenbaum** [comment]
Files is built for regular installations of Windows. While it may work on modified versions, most modifications remove required components casuing the app installation to fail.

**Comment by CodeCubeNeo** [comment]
But why does the installation work with the microsoft store?
