### ISSUE TITLE
Teracopy in Files

### ISSUE THREAD

**Issue by bluetoohfi** [files-community/Files#8899]
### What's the Problem?

I'm using files as the default explorer but it doesn't support Teracopy.

Text original:

Estou usando o files como explorador padrão mas não possui suporte ao Teracopy.

### Solution/Idea

An alternative to these options

Text original

Uma alternativa  para essas opções.

![Captura de tela 2022-04-11 143242](https://user-images.githubusercontent.com/36335363/162797838-6cf59869-f56d-4d52-87e5-9d36e950bd39.png)

### Alternatives

Have the option to leave this image menu enabled when keeping files enabled.

Text original:

Ter a opção de deixar esse menu da imagem ativado ao manter o files ativado.

![Captura de tela 2022-04-11 143242](https://user-images.githubusercontent.com/36335363/162797863-4b49e073-d1cf-4561-bb1a-bc684e7a7484.png)

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Versão: 2.1.40.0 OS Version: 10.0.19044.1586

### Windows Version

Edição	Windows 10 Pro Versão	21H2 Instalado em	‎16/‎01/‎2022 Compilação do SO	19044.1586 Experiência	Windows Feature Experience Pack 120.2212.4170.0

**Comment by yaichenbaum** [comment]
Teracopy is closed source and as such, we can't really do anything to properly integrate, we recommend reaching out to Teracopy with this request.
