### ISSUE TITLE
Layout change working inconsistent 

### ISSUE THREAD

**Issue by VoxelFloof** [files-community/Files#8906]
### Description

![image](https://user-images.githubusercontent.com/94568504/163010599-10988ef7-1ef1-4b34-984d-2d95c1692c4b.png)

won't change form details layout

---

![image](https://user-images.githubusercontent.com/94568504/163011343-5388f73e-39da-4e46-b69a-ea5e48bf0fc0.png)

can change to all the layouts except details & columns 

### Expected behavior

change to selected layout 

### Files Version

Version: 2.1.40.0 OS Version: 10.0.22593.1

### Windows Version

Windows 11 22H2 (OS Build 22593.1)

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8474818/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8474819/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
This issue should be resolved in v2.3
