### ISSUE TITLE
WSL remote ssh file view

### ISSUE THREAD

**Issue by icedmoca** [files-community/Files#8909]
### Solution/Idea

When you are viewing the WSL for example Ubuntu in "Files" if you have an ubuntu SSH session open in a prompt, allow for "Files" to show all the directories of that remote server. And change the files listed based on the user logged in to that session.

### Alternatives

SFTP which sucks and files could make it so much better.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish saving time | Must |
| This proposal will allow end users to accomplish saved time & upload files directly to the ssh'ed server | Should |
| This proposal will allow developers to accomplish more saved time  | Could |
| This proposal will allow end users to accomplish time saved & upload files directly to the ssh'ed server | Must |

### Files Version

Version: 2.1.15.0 OS Version: 10.0.19042.1586

### Windows Version

Edition	Windows 10 Pro Version	20H2 Installed on	‎4/‎23/‎2021 OS build	19042.1586 Experience	Windows Feature Experience Pack 120.2212.4170.0

**Comment by gave92** [comment]
Also #2407

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
> Also #2407

@gave92 do these go together?

**Comment by gave92** [comment]
I'd close this in favor of #2407
