### ISSUE TITLE
"Pin to Start Menu" needed.

### ISSUE THREAD

**Issue by ExhYZ** [files-community/Files#8910]
### Solution/Idea

Add  "Pin to the Start Menu" to the right-click menu

### Alternatives

Add  "Pin to the Start Menu" to the right-click menu

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.40.0

### Windows Version

Windows 11 22H2 22581.200

**Comment by yaichenbaum** [comment]
This is already supported in the extended context menu (shift + right click).

**Comment by PaperPrototype** [comment]
@yair100 it should be a main option. Also having a pin to taskbar would be very nice :)

**Comment by kingmaster772** [comment]
> This is already supported in the extended context menu (shift + right click).

It is not showing "Pin to Start Menu" when i Shift + Right Clicking file
