### ISSUE TITLE
Local Drives disappear 

### ISSUE THREAD

**Issue by psl3** [files-community/Files#8911]
### Description

Worked correctly when initially installed.  When opening on subsequent days, all local drives not shown. The main screen shows 'Folders' OK, but under that it has text 'Drives' and just blank section (where it should show at least 5 physical drives).
On the sidebar - it does not show 'Drives' at all - despite being selected (and toggled) in Options.

Had same result on multiple versions over last 2 months.

### Steps To Reproduce

On main screen when opened

### Expected behavior

To see the local drives in the 'Drives' section

### Files Version

2.1.24.0

### Windows Version

Windows 11 Pro 22H2 22593.1 Feature Experience 1000.22593.1.0

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8480153/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8480154/debug.log)

**Comment by gave92** [comment]
Thanks for the report. Could you post a screenshot of Files on start?

**Comment by gave92** [comment]
Also, could you check if the issue is due to disconnected network drives?

**Comment by psl3** [comment]
> Also, could you check if the issue is due to disconnected network drives?

After posting - I did notice it was all my drives with drive letters -- so includes the 4x Network drives that are on my Server. The server was on and the drives available when opening FILES just now.  
![Screenshot Files App 2022-04-13 175917](https://user-images.githubusercontent.com/66886433/163232451-0e1dca4f-5381-4c5d-b6bd-e4dd9ad19bac.jpg)

Have included a screenshot from File Explorer taken at the same time showing all the active drives.
![Screenshot File Explorer 2022-04-13 180328](https://user-images.githubusercontent.com/66886433/163232875-eb55138c-8214-42d4-a501-aab47940b57c.jpg)

This is the only issue I have with this great program.

**Comment by Doc-4** [comment]
I can also see this bug, I'm using the sideloaded version. It showed up a day after installation, reinstallation fixed it for the moment but I'll keep testing. Something of note, when the drives disappear, at the same time the option selector for which terminal is used in the context menu appears empty and can't be changed, nor does the button to open the config file work after this point.

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.0.0?

**Comment by psl3** [comment]
I have just started to use 2.3.3.0 (I didn't realise when upgrading, the old version remains installed).  Am testing, removing network, using sleep, hibernate etc. as I previously suspected it might be cause --- however, currently all is working as it should!

**Comment by psl3** [comment]
Version 2.3.3.0 - this is still happening unfortunately. I am still unable to tell the sequence of events that causes the issue to present itself. 
![Screenshot 2022-07-21 110247](https://user-images.githubusercontent.com/66886433/180187877-60f9e20a-ec94-4efa-a390-823b84291579.jpg)
Then strangely Drive C: returned but not my Drive D:, E: F: G: (all local drives) or H: BD-RD Drive
![Screenshot 2022-07-21 110507](https://user-images.githubusercontent.com/66886433/180188387-4b1ce50f-0c8b-4c3f-80a3-3b3c2b525abd.jpg)
Closed and openned again and Drive C: gone again!

**Comment by psl3** [comment]
Sorry - now note that it is all mapped drives that disappear. please see the Windows Explorer view and then the Files view on the same computer.   Thanks for any review of this bug!

![image](https://user-images.githubusercontent.com/66886433/180189954-f37f7747-a564-4724-85cf-dfb96f56885d.png)
![Screenshot 2022-07-21 111246](https://user-images.githubusercontent.com/66886433/180189934-ac46513f-9e55-464e-9dc9-6e58ee7c1705.jpg)
