### ISSUE TITLE
New way(s) to trigger multiselect to improve UX

### ISSUE THREAD

**Issue by bagiosw** [files-community/Files#8912]
### What's the Problem?

There should be a new way(s) to trigger the multiselect function for folders and files. The current experience could be improved.

### Solution/Idea

I come up with these solutions:
1. Long clicking a folder/file to automatically trigger multiselect, or
2. Clicking a folder/file icon to trigger multiselect, or
3. Separating multiselect from the dropdown menu, or
4. Adding multiselect trigger on the left side of the name column, it's a blank space, isn't it?

### Alternatives

If yes, possible adding the select all function at the very top of the checkboxes column after triggering the multiselect. So the multiselect and select all would be next to each other on the first column (a bit rough, could be improved). 

Also since when triggering the multiselect wouldn't let you open a folder by clicking or double-clicking it (if you don't disable it manually), so after doing an action like copy or cut, it should be better to automatically disable the multiselect so the user can directly navigating to another folder (well because navigating to other directory or even other drive/partition didn't automatically disable the multiselect, maybe another request?).

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.15.0

### Windows Version

10.0.19042.1415

### Comments

Image to illustrate
![image](https://user-images.githubusercontent.com/15670237/163210860-713d4fa0-7809-452d-8dce-206138099f6d.png)

**Comment by yaichenbaum** [comment]
> Long clicking a folder/file to automatically trigger multiselect, or

This is used to open the right click context menu

> Clicking a folder/file icon to trigger multiselect, or

This will prevent users from switching the selected item

> Adding multiselect trigger on the left side of the name column, it's a blank space, isn't it?

This is the solution we plan on implementing, can you open a separate issue to track this (I thought we had one, but I can't find it)?

> Adding multiselect trigger on the left side of the name column, it's a blank space, isn't it?

The blank space is currently used to remove focus from the current selected items, it also serves as a way for users to create a selection with the selection rectangle.

**Comment by bagiosw** [comment]
Sure, I will open a new issue for that
