### ISSUE TITLE
Make columns layout the default

### ISSUE THREAD

**Issue by PaperPrototype** [files-community/Files#8913]
### What's the Problem?

One of the biggest hated problems with windows is its File Explorer! And I love how you guys are trying to change that! 

I'm the author of https://sparker3d.com and I plan on having setup instructions for using your app on all of my courses! I will be updating this course https://sparker3d.com/paper/scripting/view/4

The only real problem is that by default you don't use column view! I'm adding instructions in the course to help every student use the column layout by default. Honestly, you could get rid of all other layouts and I would still love Files 😄 

The second problem is that your "home" folder copies what File Explorer does. If you guys could change it so that the home folder showed ALL of the files in your user folder as well as use some kind of column layout, cause it is really annoying to have to open a folder in its own window! EDIT: Even if this isn't fixed just making columns the default for all other views would help. Although I hope I can eventually convince everyone to make the default home use columns as well

You can see how its very easy to navigate with columns on by default

![](https://nektony.com/wp-content/uploads/2018/02/home-folder-mac-442x271.jpg)

I looked at many apps, and yours is so far the best one I've seen. I hope with my site making students download your app we can grow this thing to maybe replace windows default File Explorer! Keep it up!

### Solution/Idea

Make columns layout the default layout.

Update the home folder to use columns as well, plus show all of the files and folders rather than just a few.

### Alternatives

The alternative I am using right now is to have the students manually find the user folder and pin it to favorites so they can get the column view in their home folder.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow all end users to view their folders in a less confusing way by using column view by default | Must |

### Files Version

Version: 2.1.15

### Windows Version

Windows 10

### Comments

![image](https://user-images.githubusercontent.com/48071553/163231982-bdbbbff6-527b-43ca-839d-f7d52318043c.png)

**Comment by PaperPrototype** [comment]
With all my gloating about making columns the default, I have to say the home view is very nice 😋

**Comment by yaichenbaum** [comment]
@PaperPrototype there are two things you can do already today to achieve this setup,

The first thing to do is to set the startup page to the preferred location by navigating to settings > preferences > startup settings and changing the setting to "Open a specific page".
![image](https://user-images.githubusercontent.com/39923744/163234086-0bfbe126-ae1d-42b8-905c-659b7e2b7d6d.png)


Files doesn't currently have support for setting a default layout mode, but in the meantime, you can navigate to settings > preferences > files and folders and turn off the option to use individual preferences for individual directories. Once this is turned off, changing the layout will apply the same layout to all directories.
![image](https://user-images.githubusercontent.com/39923744/163234430-b7339bd2-adc1-49ed-9fbd-a8ce64aa1439.png)

**Comment by PaperPrototype** [comment]
@yair100 Thanks for all the tips! I will definitely make sure to include this in the instructions for setup.

**Comment by PaperPrototype** [comment]
@yair100 Hey, finished updating the course to include setup instructions for using you files app if you are curious https://sparker3d.com/paper/scripting/view/8
