### ISSUE TITLE
Make context sub-menu easier to press

### ISSUE THREAD

**Issue by jac0b-w** [files-community/Files#8915]
### Description

There are two small issues that make it hard access the context sub-menus.

### Issue 1

Sometimes the sub-menu doesn't spawn directly adjacent to the option spawning that menu

![image](https://user-images.githubusercontent.com/51512690/163262797-e0f415c9-cfc0-477f-be90-8ff2270ff9c0.png)

### Issue 2

The sub-menu is always destroyed when the pointer leaves the option. Most context windows will have a time before the menu is destroyed so you can briefly move your mouse over other options en route to the newly create menu.

### Steps To Reproduce

1. Right click a folder for example
2. Mouse over 'More'
3. Move mouse to new sub-menu but via the option above 'Move'
4. Sub-menu infuriatingly is destroyed shortly after 

### Expected behavior

Sub-menu should stay alive for long enough to mouse over them like the context menus in windows file explorer.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.19043.1586

### Windows Version

Version 10.0.19043 Build 19043

### Relevant Assets/Logs

None

**Comment by yaichenbaum** [comment]
Thank you for your feedback, we don't have a lot of control over the menu since we're using the default WinUI control. Can you open an issue in the WinUI repository?
