### ISSUE TITLE
Add easy way to compress to zip

### ISSUE THREAD

**Issue by LABAMBAValentina** [files-community/Files#8916]
Great app really love it. Some suggestions: First make it so that when moving a tab out of the current window opens an entirely new window along side the old window right now it deletes the old tab and only opens the current tab. Second, add easy way to compress to zip, right now the only way I find how to do this is to make a new empty zip folder. Third, make it snappy or add option to reduce animations to make it more responsive.

**Comment by gave92** [comment]
Thanks for the suggestions. Merging with #45.
