### ISSUE TITLE
Feature: Improving multiselect feature

### ISSUE THREAD

**Issue by bagiosw** [files-community/Files#8918]
### What's the Problem?

There should be a new way to trigger the multiselect function for folders and files. The current experience could be improved.

### Solution/Idea

I come up with this solution, adding multiselect trigger on the left side of the name column. By doing that, doing multiselect will be faster and reducing steps required to do multiselect.

### Alternatives

If yes, possible adding the select all function at the very top of the checkboxes column after triggering the multiselect. So the multiselect and select all would be next to each other on the first column (a bit rough, could be improved).

Also since when triggering the multiselect wouldn't let you open a folder by clicking or double-clicking it (if you don't disable it manually), so after doing an action like copy or cut, it should be better to automatically disable the multiselect so the user can directly navigating to another folder (well because navigating to other directory or even other drive/partition didn't automatically disable the multiselect, maybe another request?).

### Requirements
- [ ] Checkboxes should be visible at the left of the file names in the details layout and the corner of items in the grid layouts
- [ ] There should be a checkbox to the left of the name header in the details layout
  - [ ] This checkbox should select/deselect all items in the list
- [ ] Add a setting to the folders page to (eg. "Show checkboxes next to items")
- [ ] The current multiselect menu option should be removed
 
### Files Version

2.1.15.0

### Windows Version

10.0.19042.1415

### Comments

Image to ilustrate
![image](https://user-images.githubusercontent.com/15670237/163340278-6cbc0d85-b988-40fd-821b-b7d78ae9888d.png)

**Comment by DominikGajdos** [comment]
Hi @yaichenbaum, I would like to contribute to your project. This functionality looks interesting to implement. Can you please assign it to me?

**Comment by DominikGajdos** [comment]
Hi @yair100, I would like to help with this issue. It looks very interesting to implement. Can you assign it to me?

**Comment by yaichenbaum** [comment]
Requirements haven't been figured out yet but feel free to copy the UX that File Explorer uses.

**Comment by DominikGajdos** [comment]
When will the requirements be figured?
Alternatively, could you recommend an issue I could help with?
Well thank you.

**Comment by yaichenbaum** [comment]
@DominikGajdos I updated the requirements, do you still want to work on this?

**Comment by DominikGajdos** [comment]
@yair100 Yes. I still want to work on it. What are the new requirements?

**Comment by DominikGajdos** [comment]
Ok. If I finish the previous issue, then I will work on this issue.
