### ISSUE TITLE
Multiple parts of Files not rounded

### ISSUE THREAD

**Issue by Loremly** [files-community/Files#8920]
### Description

Multiple parts of the app arent rounded.

So far only in the file/folder list, and the destination thing at the top

### Steps To Reproduce

Just hover/click over some elements

### Expected behavior

Supposed to follow the fluent design 

### Files Version

Version: 2.1.15.0 OS Version: 10.0.19044.1645

### Windows Version

Windows 10 21H2 19044.1645

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/86319836/163514084-086ea0df-5094-4e3a-a946-ad505548a411.png)
![Screenshot (1)](https://user-images.githubusercontent.com/86319836/163514167-9faf5e4a-c778-487c-87c7-617fab75c8fe.png)

**Comment by Josh-65** [comment]
Thats what it should look like on windows 10. The code requied for the item selection just doesnt work unless your on Windows 11
