### ISSUE TITLE
File in use dialog should show the file name and extention

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#8922]
### What's the Problem?

Currently it just says "The file" which isnt helpful

### Solution/Idea

*

### Alternatives

*

**Comment by gave92** [comment]
Something like this maybe?

<img src="https://user-images.githubusercontent.com/9673091/163604174-4fc6bd25-7d59-410d-b0f4-17f2b3ff3b2a.png" width="500" />

**Comment by Josh-65** [comment]
looks good

**Comment by yaichenbaum** [comment]
This issue should be resolved with #8925
