### ISSUE TITLE
Second, and final, of the day

### ISSUE THREAD

**Issue by RoyAnderson** [files-community/Files#8932]
### Description

Again you borked when opening a folder. Guessing it may be related to OneDrive, and mine aren't in the default locations

### Expected behavior

Otherwise, I love the app. 

Highlights: multiple tabs, configurable navigation pane, split panes

### Files Version

todays

### Windows Version

sent debug twice as only way to clear upload error

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8500533/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8500534/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8500535/debug.log)

**Comment by gave92** [comment]
Same error log as #8759
