### ISSUE TITLE
Default app

### ISSUE THREAD

**Issue by Styralix** [files-community/Files#8933]
### What's the Problem?

Make the application to be the default one for opening folders or files that you have personally chosen.

### Solution/Idea

.

### Alternatives

.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by gave92** [comment]
The [sideloaded](https://files.community/download/preview) can be set as default file explorer.

**Comment by Styralix** [comment]
Would you be able to give me instructions on how to do so? 
Thank you!

**Comment by gave92** [comment]
Hi, after installing the preview version from the link above, you can find instructions here to set it as default: https://files.community/docs/configuring/replace-file-explorer
