### ISSUE TITLE
Files crashes when using RaiDrive virtual drive

### ISSUE THREAD

**Issue by jafet03** [files-community/Files#8934]
### Description

el programa suele cerrarce cuando estoy dentro de un disco virtual creado por raidrive y cuando intento copiar archivos del pc hacia el disco virtual de nube de raidrive, tambien aportando que la parte visual que te dice la tarea de copiado no es tan genial 🤣

### Steps To Reproduce

sdfsdf

### Expected behavior

sdf

### Files Version

sdfsdf

### Windows Version

sfdsdf

### Relevant Assets/Logs

sdfsdf

**Comment by gave92** [comment]
Please upload the app's debug files, you can get them from Settings > About > Open log location (the 2 ".log" files)
