### ISSUE TITLE
Do not fold the context menu

### ISSUE THREAD

**Issue by GaiZhenbiao** [files-community/Files#8935]
### What's the Problem?

The Community Files sarted folding context menu since quite a while ago. It originally provides 2 kinds of context menu: full and scrollable. But now it replaced the full context menu option with "move to submenu",which lowers operating efficiency quite a bit. I have a 27' 4k screen, which can confortably display **the full menu**.Please make that a option too.

### Solution/Idea

Add a option to always display the full context menu, unless having insufficient screen real-estate.

### Alternatives

Make the scrollable context menu longer to fit into big screen.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Add a option to always display the full context menu| Could |

### Files Version

2.1.15.0

### Windows Version

Windows 11 220408.1503

### Comments

Move options to sub menu:
![图片](https://user-images.githubusercontent.com/51039745/163701727-bacc298c-1a4c-4ff6-a376-484ba6422b90.png)
Scrollable context menu:
![图片](https://user-images.githubusercontent.com/51039745/163701745-9215730c-6c61-4166-ac7e-605d7052bc73.png)

**Comment by gave92** [comment]
You can find the option for that in Files settings

**Comment by gave92** [comment]
Reading again I think I misunderstood your request. Is the second screenshot taken with the option off? If so, it becomes scrollable because you clicked close to the bottom of the screen.
