### ISSUE TITLE
Showing a totally different size of a folder/file

### ISSUE THREAD

**Issue by Jaideep25** [files-community/Files#8937]
### Description

Hello!
Thank you so much for such an amazing app, it's truly farr better than the default/classic windows explorer.
The problem which am facing is that when I open the file explorer see the size of a folder it shows a different size, whereas, this files app shows another size. I've attached the pics below, will be waiting for you guys to solve this issue out :) Thanks !

### Expected behavior

The thing is I've tried with other folders & files, but it doesn't show the same, which I feel is happening in temp itself, I'm not sure of the reason tho ! So sorry for troubling you people. 

### Files Version

220000.613

### Windows Version

Windows 11 21H2 220000.613

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/67269475/163704116-8e2172ad-f3f6-49a7-bab5-ed3e44f5afa1.png)

**Comment by Josh-65** [comment]
Could you wait longer with the properties are open currently theres noloading icon for it (see #8586 and #8585) but when its finished it should show the byte number in breackets

**Comment by Jaideep25** [comment]
Hey Josh!
Actually I'd done that too, I'm sure that it takes time, so I did wait, but it just didn't budge more soo yeah secondly you can see yourself there is no no loading icon, by the way is it working for you?
Thanks :)

**Comment by Josh-65** [comment]
For me folder sizes are proberly calculated. is it an issue just for the Edge folder

**Comment by Jaideep25** [comment]
Right!
I just got a lead on it, went on to scan the "Users" dir, it takes huge time, and jumps from one size to another, secondly, I couldn't see a loading icon too, and I just wanted to inform another issue which I guess you guys can try to apply any one of the fixes which I felt fair,
-  to scan the whole dir then show the size
- Or let it continuously count and show the progress like seen in the classic file explorer
- Or just show the loading icon while calculating the folder's size :)

![image](https://user-images.githubusercontent.com/67269475/163807311-ef6461d7-3771-4ca5-99c8-4b754d5dee8f.png)

(Just waited 5mins n this showed up)

**Comment by Josh-65** [comment]
Im going to merge it with #8586. As adding a loading icon to it seems to be the best way right now

**Comment by Jaideep25** [comment]
Okay, cool!
Thanks.
