### ISSUE TITLE
Drag and drop tabs should open them in a new window

### ISSUE THREAD

**Issue by JotaRata** [files-community/Files#8938]
### Description

When dragging a tab outside the main window, it will close that window and open a new one opening the tab that was dragged first, instead of creating two different windows with one tab each

_Watch attached video_

### Steps To Reproduce

- Open a Files window with two tabs.
- - I set one tab to be the Start page and the other was the Downloads folder
- Click and drag one tab outside the window.

### Expected behavior

Files should open two windows for each tab.

### Files Version

Versión: 2.1.15.0 

### Windows Version

OS Version: 10.0.22000.613

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8501177/debug.log)

https://user-images.githubusercontent.com/36273501/163705527-1a133645-4def-4ad9-b2fa-8324d85beedb.mp4

**Comment by Josh-65** [comment]
This has been fixed in preview versions and properly in version .24 can you update the app via the store or https://files.community/download/stable

**Comment by JotaRata** [comment]
Sorry, what version is it?

**Comment by JotaRata** [comment]
Nope.
Same behaviour in Version: 2.1.24.

[debug.log](https://github.com/files-community/Files/files/8502577/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8502578/debug_fulltrust.log)
0

**Comment by Josh-65** [comment]
did you try the preview version

**Comment by JotaRata** [comment]
I tried the link you sent me

**Comment by Josh-65** [comment]
https://files.community/download/preview

**Comment by JotaRata** [comment]
Nevermind. The preview version 2.1.40.0 works fine.

It's somewhat slow to open a new window, and open it at the location of the cursor would be a nice add.

Thank you for your quick response!
