### ISSUE TITLE
The option to set Files as a default file manager si gone

### ISSUE THREAD

**Issue by Bernard512** [files-community/Files#8939]
### Description

When I reinstall the File app, the option to set the Files App to become the default file manager is gone. 

### Steps To Reproduce

1. Go to Settings
2. Experimental
3. I don't see the Set Default Manager option

### Expected behavior

What I expected is there an option to set the default file manager as It should be.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.613

### Windows Version

Windows 11 21H2 22000.613

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8501469/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8501470/debug_fulltrust.log)

**Comment by gave92** [comment]
The option is only available in the [sideload version](https://files.community/download/preview)

**Comment by Bernard512** [comment]
For the sideload version it can run as default file manager without any issues. But, when I "sleep" my computer and turn it on again the Files App is not responsive again. Such as when I want to open file location when I use windows Search it can't be load and I can open my file explorer again.
