### ISSUE TITLE
No auto-update of view on network share when creating or pasting files/folders

### ISSUE THREAD

**Issue by Don-Moahskarton** [files-community/Files#8940]
### Description

I'm using an SMB network share, and when creating a folder, new file, or copy/pasting files and folders, the new element does not show up in the destination. Refreshing the view makes them appear. 

I would like the new files to appear immediately, without having to refresh manually.

### Steps To Reproduce

There's multiple ways, but here is one:

1. Copy some files from anywhare
2. go in an SMB network share location
3. Paste
4. Notice the view of the folder is still empty

### Expected behavior

I'd like it to work just like on local drives. When I paste files in my SMB drive, they should show up where I just pasted them, and not have to refresh the view to see what I just did.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.19043.1645

### Windows Version

Windows 10 Pro Version	21H1 Installed on	‎7/‎1/‎2021 OS build	19043.1645 Experience	Windows Feature Experience Pack 120.2212.4170.0

### Relevant Assets/Logs

No need I think.

**Comment by gave92** [comment]
Thanks for the report. This is fixed in the latest preview version.
