### ISSUE TITLE
Item disappearing from the favorite section

### ISSUE THREAD

**Issue by adnan1710** [files-community/Files#8941]
### Description

In the favorites section, when moving an item up or down more than once unpins it(or another item) from there.

Files MS Store version
Version: 2.1.40.0
OS Version: 10.0.22000.651

### Steps To Reproduce

1. Move an item up or down more than once.

### Expected behavior

Items should be moved as expected without anything disappearing

### Files Version

Files (MS Store) Version: 2.1.40.0

### Windows Version

OS Version: 10.0.22000.651

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8501830/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8501832/debug_fulltrust.log)

**Comment by gave92** [comment]
Thanks for the report. Could you upload a screen recording of this?

**Comment by yaichenbaum** [comment]
This issue should be resolved with #9113
