### ISSUE TITLE
Forward/Backward goes back and forth twice

### ISSUE THREAD

**Issue by dhbtfs** [files-community/Files#8942]
### Description

I dont know what triggers this, but sometimes Files goes back and forth twice using mouse back/forward button. ONLY in this version (2.1.40.0 ) I have seen this bug.

### Expected behavior

Not going Forward/Backward twice

### Files Version

Version: 2.1.40.0 OS Version: 10.0.22000.613

### Windows Version

Win 11 latest

### Relevant Assets/Logs

https://user-images.githubusercontent.com/95389975/163729351-2aeafdc3-0a75-45aa-bc71-4f06b8568d75.mp4

**Comment by gave92** [comment]
When this happens, what do the back and forward buttons at the top left do?
