### ISSUE TITLE
When searching a folder, you can't search for a file with a . in it.

### ISSUE THREAD

**Issue by StormDragon-64** [files-community/Files#8943]
### Description

I was searching a folder for files with a specific version number in their name, which has a . in it, and if I type anything into the search bar with a . in it then no results pop up even though I could see some of the files with the version I was searching before I used the search bar. 

### Steps To Reproduce

Open a folder
Add files that have a . in their name into the folder
search for any of them while including the . in the search
Nothing shows up and a "no items found" message appears.

### Expected behavior

The files that I was searching for would show up.

### Files Version

Version: 2.1.15.0

### Windows Version

 OS Version: 10.0.19043.1645

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/80718549/163732871-c58af9d6-fc54-4124-9f11-2d18881513e5.png)

**Comment by gave92** [comment]
Could you post a screenshot including the searchbox with the term you're using and a couple of file names that should match but don't appear?
