### ISSUE TITLE
Drag and drop files from other programs to files

### ISSUE THREAD

**Issue by Kagura-Nanaa** [files-community/Files#8944]
### Description

files cannot accept files dragged from other programs into files.For example, it is not possible to drag a file from everything to files, it shows the forbidden icon

### Expected behavior

You can drag and drop files from other applications to files

### Files Version

2.1.24.0

### Windows Version

win11 22598.100

### Relevant Assets/Logs

![ApplicationFrameHost_pxO8Eo2mTQ](https://user-images.githubusercontent.com/44108528/163748179-e9c8dfe7-a511-446c-8fc3-3cde44bf43e3.png)

**Comment by gave92** [comment]
Thanks for the report. Make sure that you are _not_ running Everything as administrator and darg&drop should work:
![image](https://user-images.githubusercontent.com/9673091/163779751-fe18ff67-a761-45ab-b511-5d1d57396253.png)

**Comment by Kagura-Nanaa** [comment]
> 

Thanks, it's working fine!

**Comment by mdsatria** [comment]
> Thanks for the report. Please make sure that you are _not_ running Everything as administrator (enable Everything service, disable Run as admin option) and drag&drop should work:
> 
> ![image](https://user-images.githubusercontent.com/9673091/163779751-fe18ff67-a761-45ab-b511-5d1d57396253.png)

Hi, how can I find this option?

**Comment by gave92** [comment]
![Everything.Options.General.png](https://user-images.githubusercontent.com/9673091/166341859-6a613be8-0da3-4250-b42b-ef1fd80d1c6b.png)
