### ISSUE TITLE
Image thumbnails are still blurry

### ISSUE THREAD

**Issue by Darhagonable** [files-community/Files#895]
**The issue**
Pixel arts and low res textures and images appear blurry instead of pixelated like they should. If it's intentional it should at least be an option in the settings.
#812 was supposed to fix #810 but it never got actually fixed and the issue got closed anyways.

**Screenshots**
![image](https://user-images.githubusercontent.com/14127357/83527154-af14d480-a4e7-11ea-9a3a-04cf322f63c3.png)
![image](https://user-images.githubusercontent.com/14127357/83527185-bc31c380-a4e7-11ea-9d62-c6c9782cd7b1.png)

**Desktop**
 - OS Version: Windows 10 1909
 - App version: [v0.9.1]

**Comment by duke7553** [comment]
@Darhagonable I'm interested in fixing this. Can you please send me a pixel art texture to test with?

**Comment by Darhagonable** [comment]
@duke7553 
![door_wood_upper test](https://user-images.githubusercontent.com/14127357/83808503-2f3c6500-a6b5-11ea-94b2-546296fb4def.png)

**Comment by duke7553** [comment]
This file is only 16x16, so we can't display it any better considering how small it is.

**Comment by Darhagonable** [comment]
I feel like i there's a misunderstanding on what i want to be achieved.
Left: What it currently looks like in Files UWP which is blurry.
Right: What it should look like. It can be displayed like this by using integer scaling/nearest neighbor on them instead when displaying them.
![scaling](https://user-images.githubusercontent.com/14127357/83920104-5ad65280-a77c-11ea-8fdf-32851c60453e.png)
Please reopen the issue. If you still don't think there's a single way of it to be done then i wouldn't mind giving it a shot myself if i just knew how stuff work with pull requests and such.

**Comment by duke7553** [comment]
Were you going to give this a shot? I'd recommend first looking at the thumbnail scaling options in ItemViewModel.cs

**Comment by duke7553** [comment]
@Darhagonable I assigned this to you, so you can work on it now.

**Comment by duke7553** [comment]
@Darhagonable Since we've seen no progress from you on this issue, we'll close this soon.

**Comment by yaichenbaum** [comment]
Thanks again for your feedback.

_Since we didn't hear from you on this topic for 7+ days, we'll assume everything is worked out and close this feedback item. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this._
