### ISSUE TITLE
Quicklook doesn't always work

### ISSUE THREAD

**Issue by makyph** [files-community/Files#8950]
### Description

Hi! 

Quicklook doesn't work anymore with files. 
Worked for 3 hours then doesn't work anymore. 

Any suggestions ?

Running Files on 
Version : 2.1.15.0
OS Version: 10.0.19044.1645

Quicklook works fine on native windows file explorer.

Thanks :) 

### Expected behavior

When pressing space bar on selected item, it should popup but nothing happens.

### Files Version

Version : 2.1.15.0 OS Version: 10.0.19044.1645

### Windows Version

Windows 10 21H2 19044.1645

### Relevant Assets/Logs

No logs

**Comment by gave92** [comment]
Thanks for the report. If it doesn't work after restarting the app, could you upload the app's debug files? You can get them from Settings > About > Open log location (the 2 ".log" files).
Alternatively you could check if it works using newer Files v2.1.24 -> from https://files.community/download/stable

**Comment by gave92** [comment]
Merging with #8988
