### ISSUE TITLE
Error on setting files as a default file manager to replace Windows Explorer

### ISSUE THREAD

**Issue by bryz27** [files-community/Files#8951]
### Description

After I set the default file manager to Files (Settings>Experimental>Set Files as the default file manager), upon clicking Start>File Explorer at the sidebar an error window saying:
![image](https://user-images.githubusercontent.com/41132951/163827871-a9b23670-6960-4661-9c45-fea57508b2cf.png)
It couldn't find the Files app. Please fix! Thank you

### Steps To Reproduce

1. Open Files
2. Click Settings
3. Click Experimental tab
4. Enable 'Set Files as the default file manager'
5. Press Start
6. Click File Explorer 
![Untitled](https://user-images.githubusercontent.com/41132951/163828699-6441eeb1-f965-42cb-904e-c950a8a59f81.png)
7. An error appears 
![image](https://user-images.githubusercontent.com/41132951/163827871-a9b23670-6960-4661-9c45-fea57508b2cf.png)

### Expected behavior

This is what happens:
![image](https://user-images.githubusercontent.com/41132951/163827871-a9b23670-6960-4661-9c45-fea57508b2cf.png)

### Files Version

Version: 2.1.24.0 OS Version: 10.0.19044.1645

### Windows Version

Edition	Windows 10 Education Version	21H2 Installed on	‎1/‎10/‎2021 OS build	19044.1645 Experience	Windows Feature Experience Pack 120.2212.4170.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8506468/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8506469/debug_fulltrust.log)

**Comment by Josh-65** [comment]
This has likly been fixed on the preview version https://files.community/download/preview. You will have to turn it off in your current version. then uninstall it then install the new one and set as default.

**Comment by bryz27** [comment]
> This has likly been fixed on the preview version https://files.community/download/preview. You will have to turn it off in your current version. then uninstall it then install the new one and set as default.

I see I'll check it out now, thank you

**Comment by bryz27** [comment]
> This has likly been fixed on the preview version https://files.community/download/preview. You will have to turn it off in your current version. then uninstall it then install the new one and set as default.

I'm sorry but the issue still lingers, I tried to uninstall and reinstall the preview version but the error message appears. I guess it happens on Education edition of my Windows version.

**Comment by Josh-65** [comment]
did you turn off and on the default setting also

**Comment by gave92** [comment]
If the problem still persist after toggling the option off/on in the preview version, could you check the following?
1) Does this path exists? "%LocalAppData%\Microsoft\WindowsApps\files.exe"
2) Does this path exists? "%LocalAppData%\Files\FilesLauncher.exe"
3) Is the switch for Files in Windows Settings > Apps > App execution alias turned on?

**Comment by bryz27** [comment]
> did you turn off and on the default setting also

well yes I did the turn off and on the default settings and even uninstall and reinstall the app, but still the issue is present

**Comment by bryz27** [comment]
> If the problem still persist after toggling the option off/on in the preview version, could you check the following?
> 
> 1. Does this path exist? "%LocalAppData%\Microsoft\WindowsApps\files.exe"
> 2. Does this path exist? "%LocalAppData%\Files\FilesLauncher.exe"
> 3. Is the switch for Files in Windows Settings > Apps > App execution alias turned on?

1 & 2 is absent in my path and 3 is already turned on
I'll reply this back if the workaround works or not

**Comment by bryz27** [comment]
> If the problem still persist after toggling the option off/on in the preview version, could you check the following?
> 
> 1. Does this path exist? "%LocalAppData%\Microsoft\WindowsApps\files.exe"
> 2. Does this path exist? "%LocalAppData%\Files\FilesLauncher.exe"
> 3. Is the switch for Files in Windows Settings > Apps > App execution alias turned on?

1 & 2 still hasn't resolved

**Comment by shakrunk** [comment]
> If the problem still persist after toggling the option off/on in the preview version, could you check the following?
> 
> 1. Does this path exist? "%LocalAppData%\Microsoft\WindowsApps\files.exe"
> 2. Does this path exist? "%LocalAppData%\Files\FilesLauncher.exe"
> 3. Is the switch for Files in Windows Settings > Apps > App execution alias turned on?

1. Yes
2. Yes
3. Yes (For windows 11 people it's "Windows Settings > Apps > Advanced app settings > App execution aliases")

(Same issue, windows 11, Files Version: 2.1.41.0
OS Version: 10.0.22579.100)

**Comment by gave92** [comment]
@bryz27 how where you able to solve this? By updating to the preview version?

**Comment by yaichenbaum** [comment]
This issue should be resolved with #9010.
