### ISSUE TITLE
设置flies为默认文件资源管理器后无法改回原设置

### ISSUE THREAD

**Issue by pxhg** [files-community/Files#8953]
### Description

原来的版本中实验性一项里面有设置flies为默认文件资源管理器这一设置，但是设置成功后无法改回原文件资源管理器，现在的版本连这项设置都没有了 我的文件夹无法直接打开
![image](https://user-images.githubusercontent.com/103972604/163898071-f839f826-b816-432f-ae62-cfc46fa36940.png)
![QQ截图20220419084021](https://user-images.githubusercontent.com/103972604/163898106-fb6643de-6c11-46ce-9ce6-7479e58e82d6.png)

### Expected behavior

恢复系统文件资源管理器为默认应用

### Files Version

版本: 2.1.15.0 OS Version: 10.0.22000.613

### Windows Version

版本	Windows 11 家庭中文版 版本	21H2 安装日期	‎2021-‎07-‎02 操作系统版本	22000.613 体验	Windows 功能体验包 1000.22000.613.0

### Relevant Assets/Logs

找不到……日志打不开……

**Comment by gave92** [comment]
You can use this script to revert the changes (save it as ".reg") https://raw.githubusercontent.com/files-community/Files/main/src/Files.Launcher/Assets/FilesOpenDialog/UnsetFilesAsDefault.reg

**Comment by liushunqiq** [comment]
我也出现了这个问题，但是现在这个网站已经打不开了
