### ISSUE TITLE
pin to the start menu

### ISSUE THREAD

**Issue by Kagura-Nanaa** [files-community/Files#8954]
### Solution/Idea

Add the "pin to the start menu" option to the right-click menu of the .exe

### Alternatives

No options

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
You can pin to the start menu from the extended context menu (shift + right click)

**Comment by Kagura-Nanaa** [comment]
> 您可以从扩展上下文菜单固定到开始菜单（shift + 右键单击​​）

It does not work for .exe applications.I use version 2.1.24.0

**Comment by yaichenbaum** [comment]
You can only pin folders to the start menu.
