### ISSUE TITLE
appearance - animations

### ISSUE THREAD

**Issue by Transmissiontoday** [files-community/Files#8956]
### What's the Problem?

( to have things more minimal )

disable / folder skew animation ( on click )

### Solution/Idea

⚠️ animation toggles in settings , 💌

### Alternatives

consider Dpi Scaling options and animation settings 💌

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Comments

💌

**Comment by gave92** [comment]
Hi, thanks for the report. Unfortunately list view animations are System animations, removing them actually causes a performance penalty. The good news is that they have been removed in Windows 11.
