### ISSUE TITLE
Your Favorites Bar is Awesome but....

### ISSUE THREAD

**Issue by Jaadam11** [files-community/Files#8961]
### What's the Problem?

Would be really cool if we can sort the Favorites bar out to place things in an order we understand. I tend to use the favorites bar like a hub between multiple hard drives. If they were in an order of where each drive starts and stop for me my brain would hurt a little less. Thanks for all you guys are doing though. This truly is an awesome file management system 

 

### Solution/Idea

Let us Sort our Favorites menu like the other files. 

### Alternatives

Maybe give an alphabetical order option. Shooting blanks here sorry. 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version 2.1.24.0

### Windows Version

Windows 11 Pro 21H2 OS build 22000.613

**Comment by Josh-65** [comment]
You can by right clicking

**Comment by yaichenbaum** [comment]
You can rearrange pinned items using the right click context menu.
![image](https://user-images.githubusercontent.com/39923744/164297697-95cafd6c-407b-4eba-aaee-3164a016f2ba.png)

**Comment by Jaadam11** [comment]
My god, thank you.  Ha I'm sorry I didn't notice it. But again thanks.
