### ISSUE TITLE
Add an option to add Google Drive to Cloud Drives.

### ISSUE THREAD

**Issue by mokshsinghji** [files-community/Files#8964]
### Solution/Idea

It would be nice if you could add Google Drive to the Cloud Drives

### Alternatives

I have not considered any alternatives

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to accomplish more easily access Google Drive | Could |

### Windows Version

Windows 11 Pro 21H2 22000.613

**Comment by gave92** [comment]
Merging with #6321
