### ISSUE TITLE
Date of modification changes when setting a tag on file/folder

### ISSUE THREAD

**Issue by Fantom716** [files-community/Files#8965]
### Description

When adding a tag to a file/folder, the date of modification comes true (countdown starts from zero seconds).

### Steps To Reproduce

1. Create new folder;
2. Wait some time;
3. Add tag any color;
4. Look at the modification date of a file/folder.

### Expected behavior

Countdown starts from zero seconds

### Files Version

Версия: 2.1.15.0 OS Version: 10.0.19044.1645

### Windows Version

Windows 10 21H2

**Comment by gave92** [comment]
Expected, file tags are written into the file itself. Perhaps we can change the date back to the previous value after adding the tag.
