### ISSUE TITLE
option turn off displaying recent files in settings

### ISSUE THREAD

**Issue by frax27** [files-community/Files#8966]
### What's the Problem?

There is no option turn off displaying recent files in settings. 

### Solution/Idea

add an option to turn off recent files in settings

### Alternatives

Add an option to turn off displaying recent files with a right click?

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.1.24.0 OS Version: 10.0.22000.613

### Windows Version

Windows 11 Pro 21h2 10.0.22000.613

### Comments

Thank you for your consideration.

**Comment by gave92** [comment]
You can hide the recent items from this button on homepage
![image](https://user-images.githubusercontent.com/9673091/164327507-bd0f9c82-dc89-4a0e-8993-4bfdd1e9f3fd.png)
Recent file are still registered though -> tracked in #5882
