### ISSUE TITLE
Export/Import settings dont work

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#8968]
### Description

I have before exported settings and then imported them they only imported the favorite items and nothing else

### Expected behavior

All settings should import and apply

### Files Version

2.0.41.0

### Windows Version

10.0.19043.1645

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8525625/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8525626/debug.log)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #8970
