### ISSUE TITLE
moving tabs causes files to crash

### ISSUE THREAD

**Issue by RakibRyan** [files-community/Files#8969]
### Description

when you open multiple tabs & if you try to drag one of the tags to + position (new tabs)  files crashes.

### Steps To Reproduce

1.open files
2.open 2 tabs
3.drag one of them to new tab icon

### Expected behavior

program crashes

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.613

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎12/‎10/‎2021 OS build	22000.613 Experience	Windows Feature Experience Pack 1000.22000.613.0

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8526029/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
This issue is resolved in the preview version of Files.
