### ISSUE TITLE
File info button tooltip box empty

### ISSUE THREAD

**Issue by Arno989** [files-community/Files#8973]
### Description

File information button tooltip should say something i presume

### Steps To Reproduce

Hover over button that shows file onformation, tootlip shows up but contains no text

### Expected behavior

Actual tooltip in the tooltip box

### Files Version

2.1.41.0

### Windows Version

Windows 11 22H2 22598.100

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/32594687/164416894-4de42d0c-82b6-41c0-ae14-828d1630a763.png)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #9028
