### ISSUE TITLE
Chinese edition is partly in English、The New menu has no text options

### ISSUE THREAD

**Issue by dyyxxhh** [files-community/Files#8977]
### What's the Problem?

Chinese edition is partly in English、The New menu has no text options

### Solution/Idea

Completely Chinese、New menu adds a text document

### Alternatives

Completely Chinese、New menu adds a text document

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Windows Version

22598.100

**Comment by yaichenbaum** [comment]
Which version of Files are you using?
