### ISSUE TITLE
File transfers should resume with(!) indication after app crash

### ISSUE THREAD

**Issue by joshuajeschek** [files-community/Files#8979]
### What's the Problem?

When there are one or more file transfers running while the app crashes, they continue (I don't know if in the background or when you restart the app), but there is no indication in the Tasks menu. This would be very nice to have, since after an app crash, the first thing I worry about, is wether my ongoing tasks are finished / fine / in what state they crashed.

current behaviour:
1. Start one or more file transfers
2. somehow manage to crash the app
3. start the app again, you'll see no indication about the task status
4. a way I found to figure this out is too look at when the directories in question were last changed

### Solution/Idea

imo, the tasks should reappear in the tasks menu

### Alternatives

none come to mind right now

### Files Version

Version: 2.1.24.0 OS Version: 10.0.22000.651

### Windows Version

Windows 11 Home 21H2 22000.651

**Comment by yaichenbaum** [comment]
Merging with #8207
