### ISSUE TITLE
Add all Ignore Button for delete files is on use

### ISSUE THREAD

**Issue by NNVoria** [files-community/Files#8980]
### What's the Problem?

When I delete multiple temp files.
Comes with me again and again the message that the file is in use. An ignore all button would be helpful

### Solution/Idea

A box message with all ignore feature

### Alternatives

Message with a Box to ignore all datas.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |

### Files Version

2.1.15.0

### Windows Version

Windows 11 21H2 Build 22000.556

**Comment by gave92** [comment]
Fixed in latest preview version

**Comment by NNVoria** [comment]
> 

isnt fixed in latest preview version.
I have downloaded same problem.

**Comment by gave92** [comment]
Were did you get it? Latest preview is version v2.1.41. Link is: https://files.community/download/preview
