### ISSUE TITLE
Allow complete deactivation of telemetry or any other sending of data from the user device

### ISSUE THREAD

**Issue by RwSgxx** [files-community/Files#8982]
Currently your app connects to:
Microsoft : 40.70.161.7 (probably app insights)
and 
nef.dk: 93.184.220.29 (why?)

Your app has complete access to the files in a user's device.
Doing this (nef.dk) without explaining why and what exact data is sent and without requesting permission is suspicions at least.

**Comment by gave92** [comment]
Ugh I really don't think we connect to nef.dk on purpose 🤔 Isn't that your/an internet provider?
We _do_ use MS AppCenter as explained in the privacy policy.

@yair100 does the version from GitHub releases use AppCenter?

**Comment by RwSgxx** [comment]
Maybe a lib that you use connects to nef.dk (93.184.220.29), this is not my isp.
You can trace the connections using [ProcMon](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon)

I understand the reason for using MS AppCenter / Application insights for monitoring, but still, it would be better to make this an optin. By asking first, you create more trust. And trust is the main reason most of us use OSS in the first place.

By the way, your app is great!   
When you decide to add a donation button, please consider using also Monero(XMR), it is private. [Monero OSS Wallet](https://cakewallet.com/)

**Comment by yaichenbaum** [comment]
> does the version from GitHub releases use AppCenter?

All release versions use AppCenter.

@RwSgxx I'm not familiar with nef.dk but it could be that it's used for AppCenter as well.
We encourage you to explore the code base and to inspect the data being sent to AppCenter for peace of mind. We rely on telemetry to fix bugs and to better understand which features are being used and turning it off would limit our abilty to improve the app.
