### ISSUE TITLE
Context menu

### ISSUE THREAD

**Issue by Fantom716** [files-community/Files#8983]
### Description

Context menu goes off screen

### Steps To Reproduce

1. Right click on any point left menu

### Expected behavior

Context menu goes off screen

### Files Version

Версия: 2.1.15.0 OS Version: 10.0.19044.1645

### Windows Version

Windows 10 21H2

### Relevant Assets/Logs

Screenshot with the context menu that went off the screen:
![изображение](https://user-images.githubusercontent.com/73600293/164639685-50a327f1-a7cf-49b8-b27d-550804196a4c.png)
Full context menu:
![изображение](https://user-images.githubusercontent.com/73600293/164642452-cf510b99-cbbb-44b3-91f6-c5ec960580ad.png)

**Comment by Josh-65** [comment]
This is a know issue with WinUI unfortunately files carnt do anything about this

**Comment by Josh-65** [comment]
https://github.com/microsoft/microsoft-ui-xaml/issues/4881  link to the issue
