### ISSUE TITLE
Expandable navigation panel

### ISSUE THREAD

**Issue by fsenthus** [files-community/Files#8985]
### What's the Problem?

On the left navigation panel, you have 4 sections that can be expanded (Favorites, Drives, Cloud Drives, Network Drives).  But nothing else can be expanded.

### Solution/Idea

I would like to be able to have the ability to say Expand Favorites -> Documents and see the folders within Documents, and expand those. 

I'd also like to be able to drag files from within the main panel and drag files/folders to other folders via that left navigation panel instead of having to ctrl+x/c and navigate elsewhere, ctrl+v, then navigate back.

### Alternatives

Using default explorer

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version 21.1.15.0

### Windows Version

Windows 11

**Comment by gave92** [comment]
We don't have plans to add a tree view pane but we're tracking requests for a tree view layout in #1928.

Drag& drop to the side panel should be already possible. If you have trouble with that, try to update to [Files v2.1.24](https://files.community/download/stable).

**Comment by yair100** [comment]
@fsenthus Tree View is currently available in preview https://files.community/download. It will be included in the next stable release.
