### ISSUE TITLE
Tag Files From Search Query

### ISSUE THREAD

**Issue by jasonsafir** [files-community/Files#8986]
### What's the Problem?

Tagging is disabled when searching files inside a folder. It would be useful and convenient to have the ability to tag files when also browsing search results.
![Screenshot-04-23-2022-07h00m20s](https://user-images.githubusercontent.com/5203742/164891997-c7f0b35e-e0e5-43e3-acb0-350754346da6.png)

### Solution/Idea

Add a color labels context menu to files that appear in search results that you would like to tag.

### Alternatives

None

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.24.0

**Comment by yaichenbaum** [comment]
This issue should be resolved with #8987
