### ISSUE TITLE
Quicklook doesn't always work

### ISSUE THREAD

**Issue by enterthemax** [files-community/Files#8988]
### What's the Problem?

QuickLook app: sometimes it works, sometimes it doesn't.

### Solution/Idea

Please add full compatibility for this app, it would be a great combo.

### Alternatives

Using back windows File Esplorer

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Versione 2.1.42.0 OS Version: 10.0.22598.200

### Windows Version

Windows 22 build 22598

**Comment by gave92** [comment]
Merging with #8950. Please upload the app's debug logs. You can get them from Settings > About > Open log location (the two ".log" files).
