### ISSUE TITLE
Bugs in themes and sidebar

### ISSUE THREAD

**Issue by SadiqAli-Syed** [files-community/Files#8989]
### Description

Firstly the favorites section is collapsed on startup and wont expand until 2-3 clicks

The Custom Themes options isn't showing any themes and the already applied theme isn't working

### Steps To Reproduce

open app,check if files app is working properly

### Expected behavior

The Favorites option in the sidebar show work as intended

Themes should not turn themselves off and ghost me

### Files Version

latest from MS Store

### Windows Version

latest Win11 as of 23April,2022

### Relevant Assets/Logs

i didnt generate any logs manually,if it does automatically,then idk

**Comment by gave92** [comment]
Merging with #6469 for the sidebar issue.
For themes it's a known bug, you'll need to reset the app from Windows Settings > Apps.
