### ISSUE TITLE
Support "explorer <PATH>".

### ISSUE THREAD

**Issue by iamr0s** [files-community/Files#8991]
### Solution/Idea

Files is the most comfortable file manager I've ever used.
But when I'm using command line tools like: Terminal.
I type: explorer C:
It starts the system's file manager, not Files.

### Alternatives

Files is the most comfortable file manager I've ever used.
But when I'm using command line tools like: Terminal.
I type: explorer C:
It starts the system's file manager, not Files.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by gave92** [comment]
You can type "files <path>" to open Files.

**Comment by iamr0s** [comment]
> 

However, when I use VScode or Idea and choose open in explorer, it still opens with the system file manager.
