### ISSUE TITLE
Custom themes

### ISSUE THREAD

**Issue by abeneTN** [files-community/Files#8992]
### Description

![image](https://user-images.githubusercontent.com/95079856/164999991-779ace36-46f6-431a-8336-2c4f20449e6a.png)

![image](https://user-images.githubusercontent.com/95079856/164999979-08a56c1e-7c7f-4061-a991-25e447688b51.png)

I can't find pre-installed themes.
When I first installed Files all the themes are available but now I can't seem to find any but only the one I set, If go to
Windows Settings > Apps > Apps & features > Files and I reset the app all the themes are back.

### Expected behavior

All pre-installed themes should stay available after I select one from the available themes.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.613

### Windows Version

Windows 11 Pro, 10.0.22000 build 22000

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8550676/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8550677/debug_fulltrust.log)

**Comment by Josh-65** [comment]
Known issue right now you will need to backup your setting in files settings > about > manage settings first as the get removed. then reset the app via windows settings > apps > files > advanced options.
