### ISSUE TITLE
context submenu disappears

### ISSUE THREAD

**Issue by aqtsalt** [files-community/Files#8995]
### Description

when you click on something in the context menu a submenu appears. but before you can click on the submenu it disappears

### Steps To Reproduce

open context menu, open submenu, then try to click on submenu item

### Expected behavior

submenu opens when you click on the menu option, then it closes when you click elsewhere or you click on a submenu option

### Files Version

Version: 2.1.15.0 OS Version: 10.0.19043.1645

### Windows Version

21H1

### Relevant Assets/Logs

https://user-images.githubusercontent.com/104331720/165022317-e944cbe8-408d-4fa2-aebc-1ede8defc16e.mp4

**Comment by aqtsalt** [comment]
also as you can see in the video the context menu options (other than the default) take half a second to show up after right clicking which can be annoying compared to file explorer where it loads instantly

**Comment by Josh-65** [comment]
It turns off as you are hovering over other options in the content menu. Try hovering from the arrow area and not to click on the option.

**Comment by aqtsalt** [comment]
ok it did not turn off this time thankfully
but I had to carefully thread the needle between the 2 adjacent options which is very hard to do during normal use. can it just stay open once I click it?

**Comment by yaichenbaum** [comment]
is this still an issue in the preview version? https://files.community/download/preview

**Comment by Josh65-2201** [comment]
It does happen in 2.3.1.0. @yair100 Would this be a WinUI issue as that controls the context menus and sub menus.

**Comment by yair100** [comment]
> It does happen in 2.3.1.0. @yair100 Would this be a WinUI issue as that controls the context menus and sub menus.

Sounds like it, is this specific to Windows 10 or the Windows 11 RTM build?

**Comment by Josh-65** [comment]
Seem to be only on Windows 10. Windows 11 insider i carnt get it to happen so it proberly will be fixed on next major realse if not already.
