### ISSUE TITLE
Icon Property Issue

### ISSUE THREAD

**Issue by timcrouse** [files-community/Files#9000]
### Description

Setting custom icons does not work as intended (at least in the favorites pane):

Setting a custom icon may cause the app to crash.  But when you restart it the icon is set to the selected icon.

Changing the icon may generate a dialog stating the drive is unplugged when the folder being changed is a folder on the C: drive.  After you close and re-open the app the icon is set to the desired icon.

-Tim C.

### Steps To Reproduce

Goto favorites pane
Right click folder
Change icon property

### Expected behavior

expect icon to change

### Files Version

2.1.15.0

### Windows Version

10.0.19044

### Relevant Assets/Logs

![Drive Unplugged](https://user-images.githubusercontent.com/28163617/165116347-4e51dcb3-b9d0-44f7-9475-128a46433297.png)
![ImmAfter Acknowledging Unplugged Drive Dialog - No Icon Change](https://user-images.githubusercontent.com/28163617/165116359-8380f942-69ab-4ec0-8539-bdc24ab3ae42.png)
![App Restarted - Icon Changed](https://user-images.githubusercontent.com/28163617/165116373-fe063f03-3658-4e0d-8dd3-3199f9c0b422.png)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8555684/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8555685/debug.log)

**Comment by Josh-65** [comment]
Is this still an issue?

**Comment by timcrouse** [comment]
Has there been an update to the app?   I can reload and test if you whish.

I see no version info in the app or on the GitHub or Microsoft store site.  Version info and release date would be good info to include.

-Tim



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Josh-65** [comment]
theres version info in the app settings > about. and on github it on the code section under realses.

**Comment by timcrouse** [comment]
The latest build seems to be 2.3.3, noted at 2.3 on MS app store).

This is the version I have installed.

If you have a new release I can test the issue but as it stands the issue is still present on my machine.

-Tim

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by timcrouse** [comment]
I have not found a compiled executable with a newer build on GitHub.  But there does seem to be something called a sideload build that was created 2 months ago.  But again, there is no executable.
-Tim

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Josh-65** [comment]
2.3.3 is the lastest version but in your issue you were on 2.1.15. Thats why i asked if it was still an issue

**Comment by timcrouse** [comment]
Hmm,  must of crossed something up on my end.  I will re-check

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by timcrouse** [comment]
So here are the results from 2.3.3

R-click icon in favorites pane
Option to change icon is no longer available
Go to close r-click properties dialog
App crashes.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by timcrouse** [comment]
The crash does NOT occur each time the properties dialog is closed.  Seems to happen at random

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Josh-65** [comment]
Could you try recreate the issue then upload the logs files directly to github. You can get them in files settings > about > open log folder.
