### ISSUE TITLE
Bug while copying files from android to pc via usb

### ISSUE THREAD

**Issue by SadiqAli-Syed** [files-community/Files#9003]
### Description

When i tried to copy a file of size about 3.9gb the files app got hanged

I had no problems while copying it with the built in file explorer app,but cant do it with files app.

### Steps To Reproduce

connect your android to your pc with the help of usb cable

allow file sharing in mobile

open the mobile storage in pc and try to copy some big file from mobile to pc

### Expected behavior

app hangs and does not respond

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.613

### Windows Version

latest Win11 as of 25April,2022

### Relevant Assets/Logs

nope

**Comment by Josh-65** [comment]
You will need to upload the logs files directly to github. You can get them in files settings > about > open log folder.

**Comment by gave92** [comment]
Thanks for the report. Was it a one-off thing or repeatable? Does it happen for smaller files as well?

**Comment by Josh-65** [comment]
> and I think there is a feature missing to show progress of how much of data has been copied,estimated time etc,I didnt see it.

Thats known and being discuesed in #4811

**Comment by gave92** [comment]
If the app closes, it's useful if you could upload the logs files. You can get them in files settings > about > open log folder.
You can see copy progress in the icon in the upper right corner but it does not work well when copying from phone.

**Comment by Josh-65** [comment]
Is this still an issue?

**Comment by Josh-65** [comment]
@SadiqAli-Syed Could you reproduce this issue then upload the log files directly to github. You can get them in files settings > about > open log folder.

**Comment by SadiqAli-Syed** [comment]
[image: image.png]

The lines showing the size of shortcut is trimmed as you can see

**Comment by Josh-65** [comment]
you will have to uplaoded the files directly to github as email attchments dont get shown.
