### ISSUE TITLE
create-element popup should support going to last element

### ISSUE THREAD

**Issue by DAmNRelentless** [files-community/Files#9005]
### What's the Problem?

I want to avoid touching my mouse as much as possible so I heavily use keyboard shortcuts. When creating a new element with `CTRL` + `SHIFT` + `N`, I usually want to create a new file most of the time. Since the folder is the first option and the file is the last option, I need to go all the way down. There are 3 other file types in between that come from Microsoft Office.

So right now this takes a bit of time using the arrow keys or the mouse.

### Solution/Idea

Since the folder element is selected by default, it would be nice if the selection switches to the last element if you press the arrow up key once. Right now, it does nothing. It stays on the first element.

### Alternatives

You can either grab your mouse and select the file, use the arrow key multiple times to scroll down or press `End` but there are some keyboards that don't have this key.

### Priorities

Should

### Files Version

2.1.15.0

### Windows Version

Windows 11 Pro 21H2 10.0.22000.613

**Comment by Josh-65** [comment]
You can use shift + Tab to go from bottom to top
