### ISSUE TITLE
Faster preview

### ISSUE THREAD

**Issue by gruppomilleuno** [files-community/Files#9007]
### What's the Problem?

We noticed that when files tries to do the preview of some heavy files (50 MB), it takes some time to load the image even after opening it before.  

### Solution/Idea

is it possible to store in cache the previews of the images that you open with the files preview with ctrl+space until you change directory? that way the preview can be much faster

### Alternatives

No other alternatives

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.44.0

### Windows Version

Windows 11 21H2

**Comment by yaichenbaum** [comment]
This would have a significant impact on the available resources on your device. Our plan is to improve the actual speed without implementing a cache.
We're not against the idea of a cache but we believe the downside would degrade the user experience.
