### ISSUE TITLE
Files just crashed after closing the settings

### ISSUE THREAD

**Issue by Bufkin** [files-community/Files#9009]
### Description

My app crashed after I enabled the option that it should start where I left off.

### Expected behavior

Open settings
Activate option
CRASH

### Files Version

2.1.24.0

### Windows Version

Windows 10 Version 21H1

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8565336/debug.log)

**Comment by gave92** [comment]
Was it today at 7pm?

**Comment by Bufkin** [comment]
Yes

**Comment by yaichenbaum** [comment]
Is this still an issue in the latest preview build? https://files.community/download/preview

**Comment by Bufkin** [comment]
> Is this still an issue in the latest preview build? https://files.community/download/preview

No.
