### ISSUE TITLE
Bug: Confirmation to delete files shows in recycle bin even when setting is off

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#9012]
### Description

Not sure if it the case for all permanent delete operations but I think it would be better to follow the settings or have it as a separate option.
![image](https://user-images.githubusercontent.com/26977075/165400296-1b87c58b-fc6d-4a23-8807-104cac9a33c7.png)

### Steps To Reproduce

1. Turn off "Show a confirmation dialog when deleting files or folders" at Files settings > Preferences > Files and folder
2. Delete content in Recycle bin
3. See dialog

### Expected behavior

Dialog should not show

### Files Version

4.1.44.0

### Windows Version

10.0.19043.1645

### Relevant Assets/Logs
[debug_fulltrust.log](https://github.com/files-community/Files/files/8567226/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8567227/debug.log)

**Comment by gave92** [comment]
Yeah the dialog is shown anyway if the delete is permanent unless you explicitly press Shift+Delete. This is because Files and Explorer deletion behaviors may differ in some cases.
But I see you point for recycle bin, no one is gonna be surprised if the file is permanently deleted.

**Comment by yaichenbaum** [comment]
I'm not sure what File Explorer does in this scenario but we should definitely hide the prompt when the option is turned off.

**Comment by yaira2** [comment]
@Josh-65 can you fill out the steps to reproduce the issue?

**Comment by Josh-65** [comment]
done
