### ISSUE TITLE
Add a popup to ongoing tasks to indicate a task has started

### ISSUE THREAD

**Issue by NotSoNitro** [files-community/Files#9013]
### What's the Problem?

I sometimes can't tell if something is happening or not since the ongoing tasks don't really alert you of the task your doing like delete a folder or copy a large amount of files over to another location. This can be annoying to some users since you don't really get any indication if something is happening except the little icon that appears which is hard to notice, at least for me.

### Solution/Idea

Add a popup under the ongoing task which appears for a short amount of time saying how many tasks are happening at the moment and what task it is. You can also make this a setting that is togglable.

### Alternatives

An alternative to this is some other type of indication like a toaster notification at the bottom of the UI, this also can be toggled and possibly can be customisable.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by koblue** [comment]
Would just like to +1 this. 

Not having any "in your face" feedback that a copy or move has started caught me out a couple of times. 

Perhaps longer tasks could trigger a popup when it completes as well?

**Comment by Josh-65** [comment]
Merging with #4811
