### ISSUE TITLE
Consistent crashes in specific folders - unclear what causes it

### ISSUE THREAD

**Issue by theophanemayaud** [files-community/Files#9019]
### Description

I've started having frequent crashes, it seems to happen every time I navigate to certain folders, and scroll up/down left/right fast...
I'm not sure what causes it, but it happens every time, and there's an error in the log as : 

```
2022-04-27 10:57:26.1429|ERROR|AppUnhandledException|Layout cycle detected.  Layout could not complete.
Layout cycle detected.  Layout could not complete.
	Windows.UI.Xaml.LayoutCycleException: Layout cycle detected.  Layout could not complete.
Layout cycle detected.  Layout could not complete.
```

Buggy examples:
- `C:\Users\username\SharePoint\Delivery Lwie - Documents\10_Projets\xxxxx\10_PILOTAGE_GENERAL\Bons llslwerrd 2022-2023`. It has : PDFs, excels, words, 16 elements.
- `C:\Users\username\Sharepoint\Delivery Lwie- Documents\80_LWE Rate\Archives 2018` , 42 item s no sub folders. 
- `C:\Users\username\Downloads\Subfolder owoiewoiwe\Sub - kwelkwe lkwe\Folder sur be la la`, 80 items, only pdfs, powerpoints, words, pngs. This one seems harder to crash, I had to scroll around like crazy it seems, but I still get the same debug log error after it crashes.

Working examples : 
Doesn't crash : `C:\Users\username\Sharepoint\Delivery Lwie - Documents\80_LW Rate\Archives 2019` with 9 items (no sub folders).

Maybe it's due to the number of items in the folder ? 

Files doesn't crash if I go to those folders but don't scroll, but crashes as soon as I scroll around a bit fast. It doesn't seem to crash if I scroll a tiny bit at a time.

It happens wether or not the experimental feature to show folder sizes is on or off.

### Expected behavior

No crash should happen

### Files Version

Version : 2.1.41.0 OS Version: 10.0.22000.613

### Windows Version

Windows 11 Pro Version	21H2 1000.22000.613.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8570476/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8570478/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
Is this still an issue in the latest preview build? https://files.community/download/preview
