### ISSUE TITLE
Crtl + left click to open folder in new tab

### ISSUE THREAD

**Issue by theophanemayaud** [files-community/Files#9020]
### What's the Problem?

From within any folder, I'd like to open sub-folders but not in the current tab, rather in another tab to be able to come back to the current folder by switching back tabs.

### Solution/Idea

As with browsers, it'd be great being able to quickly open folders in new tabs. 

### Alternatives

Currently, I have to right click the sub folder and then select open in new tab. I'd like to mapthis to the shortcut ctrl+click

### Files Version

Version : 2.1.41.0 OS Version: 10.0.22000.613

### Windows Version

Windows 11 Version: 10.0.22000.613

**Comment by gave92** [comment]
Pressing the mouse wheel should do the same.
[Internal note]
Wasnt ctrl+click feature already implemented?

**Comment by theophanemayaud** [comment]
I’ve only got a trackpad so I can’t test for the mouse wheel I believe 😬

**Comment by theophanemayaud** [comment]
It would also be great if the same behavior happened when ctrl+click was done on a folder within the current folder, but also if ctrl+click was done in the nav bar, on a higher lever folder (current behavior on this nav bar is to navigate the current tab to that parent folder. Here in the photo, ctrl+click on download folder in the nav bar would open new tab to the downloads folder, and keep the current tab to the current folder. It's similar to macos' file explorer behavior (although the nav bar is only optionnaly shown at the bottom of the window, but ctrl click on a parent folder opens a new tab with that parent folder open) : 

![image](https://user-images.githubusercontent.com/25605953/165514133-5519cb0f-7a14-4476-8a92-8e9172302b33.png)

**Comment by yaichenbaum** [comment]
Ctrl + click is already used for selecting items.

**Comment by theophanemayaud** [comment]
@yair100 of course my bad I meant double click, as is the standard behavior.
Current: Double click folder: open folder
Idea: Ctrl+double click folder: open folder in new tab

I changed the title and description of this issue to be more precise.
