### ISSUE TITLE
Low brightness context menu 

### ISSUE THREAD

**Issue by labdo1** [files-community/Files#9021]
### Description

Right-clicking on an empty area shows the context menu with low brightness/contrast, restarting the app fix this temporary but not for long.

### Steps To Reproduce

Right click on empty area

### Expected behavior

Consistent UI colors

### Files Version

Version: 2.1.15.0 OS Version: 10.0.19044.1645

### Windows Version

Windows 10 LTSC 21H2 19044.1645

### Relevant Assets/Logs

![Files_bvEKhehDE9](https://user-images.githubusercontent.com/84672102/165489490-2e7385fe-1459-4420-9871-9bed3a125979.png)
![Files_X9atKvEPlC](https://user-images.githubusercontent.com/84672102/165489497-118d55eb-6672-498a-8ceb-5a7f6649bce4.png)

**Comment by gave92** [comment]
Bug on microsoft winui library. They only fixed it on windows11. Not much we can do about that.
