### ISSUE TITLE
Cant Customize Favorites Icons

### ISSUE THREAD

**Issue by divmonkey** [files-community/Files#9023]
### Description

Unable to customize favorite icons (.ico)

Windows 10x64 
![image](https://user-images.githubusercontent.com/11624288/165564684-82d26dc6-cb32-4d33-ba08-57941b493b87.png)

Files App version
![image](https://user-images.githubusercontent.com/11624288/165565107-e5f76ed4-b96a-4b6e-a756-73b72e79e93f.png)

### Steps To Reproduce

1. Right click Folder
2. Click Properties
3. Customization
4. Set the icon(.ico)

### Expected behavior

Nothing special, file apps closed up immediately.

### Files Version

2.1.15.0

### Windows Version

Win 10x64 21H1 19043.1645

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8574183/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8574185/debug_fulltrust.log)

**Comment by Josh-65** [comment]
Merging with #9000
