### ISSUE TITLE
Explorer.EXE: Application not found

### ISSUE THREAD

**Issue by saeedNW** [files-community/Files#9024]
### Description

after setting as the default explorer in Windows 11, every time that I try to open file explorer by double clicking on this pc or using keyboard hotkeys (window + E) or any other way except opening it by it's own launcher, it opens an error window that is says Application not found.

note1: This started to happen after removing the requirement to exit the default mode before uninstalling the program (I couldn't find the Relevant commit)

note2: the error start showing after updating to versions above of 2.1.15.0, cause there is no Issue with this version and the versions before it

### Steps To Reproduce

1. download and install the latest sideload package
2. open application setting and set as default file manager
3. try to open file explorer with any way except using it's own launcher (literally any other way)
4. see the error

### Expected behavior

Opening file explorer like normal windows explorer

### Files Version

2.1.24.0

### Windows Version

Windows 11 21H2 22000.613

### Relevant Assets/Logs

![Screenshot 2022-04-28 030424](https://user-images.githubusercontent.com/91555175/165642553-ae3687a6-7bc3-4588-8b42-f3a4e4fa1420.png)

https://user-images.githubusercontent.com/91555175/165644125-21a0e406-000e-443f-9d1c-119301c9a16a.mp4

**Comment by yaichenbaum** [comment]
Please note that the option to set Files as the default is experimental and not supported, however, we did make improvments in the preview version to solve this issue. In the meantime, you can use this registry file to revert the changes. https://raw.githubusercontent.com/files-community/Files/main/src/Files.Launcher/Assets/FilesOpenDialog/UnsetFilesAsDefault.reg

**Comment by raghav-ramesh** [comment]
@yair100
The link says 404: not found error, please provide new one and help me with below issue.

And i had the link already, but after i executed it, the **Win+E** shortcut works to default explorer... but if i open a folder on desktop or any directory, it says **application not found** jus like the image above
I first ran the script, then uninstalled but still the error... PLEASE HELP!!!! 
![image](https://user-images.githubusercontent.com/97874600/167098986-aed53b4f-2bd7-42bc-9eb8-6ab2fbddd637.png)

**Comment by rr-da-cat** [comment]
THANK U SO MUCH

**Comment by RobloxExecutorV3** [comment]
pls new
