### ISSUE TITLE
Column widths in Column View

### ISSUE THREAD

**Issue by exapplerep** [files-community/Files#9025]
### Solution/Idea

Would like to see some method of adjusting the widths of the columns in Miller Column view (both a default width I can set and the ability to drag column widths wider and narrower with a double-click adjusting the target column to the width of the widest name (folder or file). (Yeah...like a Mac, I guess.)

Thanks.

### Alternatives

The alternative is not implementing it.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.15.0

### Windows Version

Windows 10 21H2 OC build 19044.1645

**Comment by yaichenbaum** [comment]
Merging with #7863
