### ISSUE TITLE
Folder icons are shown inside a black box

### ISSUE THREAD

**Issue by carlosvsilva** [files-community/Files#9029]
### Description

When I open a new folder that hasn't been opened before, the subfolders inside it, are displayed with their folder icons inside a black box for no apparent reason, ruining the great visual experience of Files app.

### Steps To Reproduce

1. Open a folder never opened before
2. Look at subfolders icons
3. They are displayed inside a black box for some reason (I use the regular Windows Light Theme)

### Expected behavior

Icons should be displayed by themselves, without a black box around them.

### Files Version

Versão: 2.1.15.0

### Windows Version

OS Version: 10.0.22000.652

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8582515/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8582516/debug_fulltrust.log)
![image](https://user-images.githubusercontent.com/40889421/165748164-2f0e5796-8bd7-40d7-82cb-6d9c77484347.png)

**Comment by Josh-65** [comment]
This is a windows issue and carnt be fixed by files. Refreshing the directory should fix it.

**Comment by carlosvsilva** [comment]
right, to me it seems either Files is requesting the folder icon from the Windows Dark Theme while on Light, or Windows is serving the icon from the Dark Theme even while on Light Theme.
Em 28/04/2022 14:04:40, Josh-65 ***@***.***> escreveu:
Closed #9029 [https://github.com/files-community/Files/issues/9029].

**Comment by Josh-65** [comment]
The black box is transparency default look before it shows as transparent. There isnt a dark/light icon that gets used.

**Comment by carlosvsilva** [comment]
Hi Josh, and @yair100 , I found a way to fix this annoying issue:

First I deleted the icon and thumbnail cache, using this straightforward tool I got here: https://www.thewindowsclub.com/icon-cache-rebuilder-for-windows-10
This first step may have been optional though.
Second, I installed this simple tool: https://github.com/bruhov/WinThumbsPreloader

Before I open a directory in Files, I run this WinThumbsPreloader from a right click - context menu launch in the folder I want to open (only needed the first time I open it), its super fast, and supports recursive mode too, and every icon shows up perfect, including folder icons which used to cause the reported trouble above.
If I open any folder without running this WinThumbsPreloader tool first, some folder icons will show the dreaded black box all around.

My suggestion is for Files workflow to become:

1. User opens a folder named Level1a
2. Files starts automatically building this icon cache on each sub-folder in front of user: Level2d, Level2c, Level2b, Level2a. Files should start from the newer modified folder and end with the oldest modified folder.
3. User double-clicks folder Level2c.
4. Files starts automatically building this icon cache on each sub-folder in front of user: Level3c, Level3b, Level3a.
5. And so on and so forth.

I think it might be easy to have a look at the source code above to create a function to do this necessary legwork for Files to work perfectly.

Thanks!

**Comment by yaichenbaum** [comment]
@carlosvsilva you might notice that refreshing a directory fixes the thumbnails, the fix we're thinking of will automatically refresh the directory when thumbnails are finished caching.
For future reference, we're tracking this issue in #6373.
