### ISSUE TITLE
Pin To Start

### ISSUE THREAD

**Issue by Cheddlar** [files-community/Files#9031]
### What's the Problem?

File explorer allows exes and folders etc to be pinned to the start menu, files does not.

### Solution/Idea

Add the pin to start option to files.

### Alternatives

I have to disable and re enable files to use the option which is annoying and not efficient 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.1.50.0

### Windows Version

11 21H2 22000.613

### Comments

![image](https://user-images.githubusercontent.com/95487074/165778682-2569722b-8cc9-4996-b6f8-8d3b5a68f963.png)
![image](https://user-images.githubusercontent.com/95487074/165778878-c968a3e7-2eda-4f59-956d-58729e4fe87f.png)

**Comment by gave92** [comment]
Try to press "Shift" key while right clicking. You should have the "pin to start" option for folders.

**Comment by Cheddlar** [comment]
> Try to press "Shift" key while right clicking. You should have the "pin to start" option for folders.

doesnt work, ive already spoken to an admin about it and was told to try this, but it is not working.

**Comment by gave92** [comment]
Note: I've checked and we currently only have it implemented _for folders_ not exes.
