### ISSUE TITLE
Tagging a file programmatically

### ISSUE THREAD

**Issue by Zavian** [files-community/Files#9033]
### What's the Problem?

Currently, there is no way to tag a file with the new tagging system if not by using the UI. It would be very useful to implement a some sort of way to do that via command line.

### Solution/Idea

For example it can be done through command line or, even better, by reading the already present metadata in windows that it uses  (for example implementing [EXIF](https://exiftool.org/TagNames/EXIF.html) into the whole tag system, but that would be a little out of scope.

The simplest method it'd be to use the command line.
`files -tag "C:\Path\To\File.txt" "Blue"` 

### Alternatives

Currently there aren't really any alternatives to interact programmatically with the tag system in Files, none that I know of at least.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #9115
