### ISSUE TITLE
Show Dot Files option has no effect on WSL Ubuntu .files

### ISSUE THREAD

**Issue by carlosvsilva** [files-community/Files#9034]
### Description

When I go to the last section of Files, to access WSL (Ubuntu 20 from Ubuntu vanilla app in Microsoft Store), even tho I have the option "Show dot files" turned off, it works in Windows 11 files, but dot files from Linux (WSL) still do show up.

### Steps To Reproduce

1. Click on WSL - Ubuntu
2. Use column mode (Mac style)
3. Naviagate to /home/carlos/
4. See all Linux .files which should be hidden in Files

### Expected behavior

I should be seeing only my regular files when browsing WSL, I shouldn't be seeing an overload of .dot preference files which I wanted hidden.

### Files Version

Versão: 2.1.15.0

### Windows Version

OS Version: 10.0.22000.652

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8587239/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8587240/debug_fulltrust.log)
![image](https://user-images.githubusercontent.com/40889421/165864111-53195622-f2d8-4343-ba1e-6f26a2cd1f80.png)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #9064
