### ISSUE TITLE
A lot of thumbs

### ISSUE THREAD

**Issue by AleMello** [files-community/Files#9036]
### Description

I just created a bootable thumb drive with Ubuntu, using Rufus. When I finish, a lot of links appear in left bar.

### Expected behavior

I would expect just one link. I've seen this before, but now I had time to capture and report.

### Files Version

2.1.15

### Windows Version

Windows 11 Pro 21H2 22000.613

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/4070249/165868091-3fbf09b4-dc6b-4b01-a56a-c8ca30135ac2.png)

**Comment by yaichenbaum** [comment]
This issue is resolved in the preview version of Files https://files.community/download/preview.
