### ISSUE TITLE
Quick replacement option for conflicting file names

### ISSUE THREAD

**Issue by lightningHoneypot** [files-community/Files#9041]
### What's the Problem?

When replacing files that have conflicting file names, Windows Explorer gives an option to do either one of three things:

> The destination has `x` file(s) with the same name(s)
✔ Replace the files in the destination
↶ Skip these files
🗃 Let me decide for each file

Currently, Files defaults to a "Let me decide for each file" prompt, this is cumbersome as what if one wants to replace ALL of the files? They would have to go through every single option just to replace every single file 

### Solution/Idea

Essentially, emulate something that is similar or exactly the same kind of prompt that is featured in Windows Explorer:
![image](https://user-images.githubusercontent.com/88814097/166057987-5d448e8c-5772-4098-a542-75094dcd763b.png)

Each options are clear as day:
"✔ Replace the files in the destination" replaces every files in question
"↶ Skip these files" skips files that have the same name(s)

"🗃 Let me decide for each file" will redirect to the prompt that is currently shown in Files
![image](https://user-images.githubusercontent.com/88814097/166058437-ecf7dce0-a97f-479d-80b9-f134df1c6758.png)

### Alternatives

There are no alternatives that can replace the original prompt box from Windows Explorer. However, one can still use the current prompt that is currently on Files
![image](https://user-images.githubusercontent.com/88814097/166058757-80c3706e-6c30-41cf-b3a5-8bc23feaa3e9.png)

And add in these quick clicks into that prompt:
"✔ Replace the files in the destination" replaces every files in question
"↶ Skip these files" skips files that have the same name(s)

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to quickly replace conflicting file(s) in one click | Must |
| This proposal will allow end users to skip conflicting file(s) in one click | Must |

### Files Version

Version: 2.1.15.0 OS Version: 10.0.19043.1645

### Windows Version

Windows 10 21H1 19043.1645

**Comment by gave92** [comment]
Hi, a improved UI for the conflicts dialog is being worked on. IN the meantime you can choose "Replace" for one file, the right click on it and select "Apply to all"

**Comment by lightningHoneypot** [comment]
> Hi, an improved UI for the conflicts dialog is being worked on. In the meantime you can choose "Replace" for one file, then right-click on it and select "Apply to all".

Thank you! I hope you guys are able to achieve it, take your time!
