### ISSUE TITLE
Windows cannot find Files.exe Make sure you typed the name correctly

### ISSUE THREAD

**Issue by ultra-black** [files-community/Files#9043]
### Description

Anytime you try and open a file's location it says WIndows cannot find "Files.exe"
This was working a while ago but now it isnt. I think that path is not right, this happend to me with something called "Flow Launcher" (https://github.com/Flow-Launcher/Flow.Launcher/issues/1160)
After using the right path it worked.

### Steps To Reproduce

Here is a way to reproduce:
1. Turn on set as default
2. Download any file from chrome
3. Go the bottom left and click the arrow
4. Click "Show in finder"
5. Windows Cannot find Files.exe

### Expected behavior

Files app should have opened, and showed me the file location.

### Files Version

Version: 2.1.50.0 OS Version: 10.0.19044.1645

### Windows Version

Microsoft Windows [Version 10.0.19044.1645]

### Relevant Assets/Logs

![ApplicationFrameHost_TOoMIqmAxs](https://user-images.githubusercontent.com/97588864/166101627-de1f7061-afd0-411f-ae5d-fa5c45c1c954.png)

**Comment by gave92** [comment]
Thanks for this report. This issue has been recently fixed and the fix will ship with the next preview version.
