### ISSUE TITLE
Navigation Issue  

### ISSUE THREAD

**Issue by coxchris859** [files-community/Files#9044]
### Description

When I try to use Files Verison 2, it closes at will and submits a bug report to the developers. It's intermittent. I love the idea and the concept but I need this solved because I hate the old files explorer. I reinstall and it keeps happening. Do you have a beta version 

### Expected behavior

Not feeze up and close down intermittently 

### Files Version

2.1.15.0

### Windows Version

Windows 11 Home 22000.613

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8597180/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8597181/debug_fulltrust.log)

**Comment by gave92** [comment]
Thanks for the report. I'm closing this as the error from the log files is already tracked in other issues.
You can grab the preview/beets version from:
https://files.community/download/preview
