### ISSUE TITLE
Continue where you left off

### ISSUE THREAD

**Issue by ameliandev** [files-community/Files#9047]
### Description

This option doesn't work very well. If I set this option "checked" and I close Files with one folder opened and open again Files, it always display Main window, never where I left off.

It's related with another feature or option?

Thanks

### Steps To Reproduce

1. Go to Config
2. Startup Settings option
3. Continue where you left off

### Expected behavior

Continue where I left off.

### Files Version

2.1.15.0

### Windows Version

10.0.19043.1645

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8597546/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8597547/debug_fulltrust.log)

**Comment by gave92** [comment]
Merging with#9006
