### ISSUE TITLE
Files crash whens deleting multiple files

### ISSUE THREAD

**Issue by Frederic-Jacquet** [files-community/Files#9050]
### Description

I selected old files (several hundreds) and the programme crashed

### Steps To Reproduce

1. Select hundreds of files
2. select delete definitively
3. delete

### Expected behavior

the program should not crash

### Files Version

Version : 2.1.15.0 OS Version: 10.0.19044.1645

### Windows Version

Windows 10 19044.1645

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8598506/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8598508/debug_fulltrust.log)

**Comment by gave92** [comment]
Merging with #8763
