### ISSUE TITLE
Preview panel bug

### ISSUE THREAD

**Issue by AleMello** [files-community/Files#9051]
### Description

When I choose diferent files it doens't change the preview. Have to close and reopen it.

Update1: in the video you can see it's happening with files inside a zip file. But it's happening even with regular files and folders here.
Udate 2: after I close and reopen Files, it come back to normal.

https://user-images.githubusercontent.com/4070249/166141536-e6670664-dc05-40db-adc0-f9fe97056772.mp4

 

### Expected behavior

The preview image should change when you choose another file.

### Files Version

2.1.50.0

### Windows Version

Windows 11 Pro 21h2 22000.652

### Relevant Assets/Logs

https://user-images.githubusercontent.com/4070249/166141578-f0c2bac6-d91e-4113-bfa6-b5d7d57fe52d.mp4

**Comment by AleMello** [comment]
Forgot to say: these files was inside a zip file, as you can see in the video attached.

**Comment by panna-ahmed** [comment]
Was not able to reproduce.

**Comment by yaichenbaum** [comment]
Is this still an issue in the latest preview build? https://files.community/download/preview

**Comment by Josh-65** [comment]
Not for me. Think this was fixed a while ago in another issue
