### ISSUE TITLE
hope to add a quick function：Double-click the blank space to return to the upper directory

### ISSUE THREAD

**Issue by HanHua0402** [files-community/Files#9052]
### What's the Problem?

hope to add a quick function：Double-click the blank space to return to the upper directory

### Solution/Idea

hope to add a quick function：Double-click the blank space to return to the upper directory

### Alternatives

hope to add a quick function：Double-click the blank space to return to the upper directory

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by gave92** [comment]
Already implemented in [preview version](https://files.community/download/preview).
