### ISSUE TITLE
ftp server crash

### ISSUE THREAD

**Issue by khosravihamidreza** [files-community/Files#9055]
### Description

when i connect my phone to FILES whit ftp server, after i enter user name and pass it crash !!

### Expected behavior

I expected it open the ftp server but it crashhhh :(   !
then i had to use file explorer again :/

### Files Version

Version: 2.1.24.0 OS Version: 10.0.19044.1645

### Windows Version

windows 10 version 21H2 OS build 19044.1645

### Relevant Assets/Logs

[
[debug.log](https://github.com/files-community/Files/files/8599319/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8599320/debug_fulltrust.log)
](url)

**Comment by gave92** [comment]
Thanks for this report. Could you confirm this is when it happened: 2022-05-01 21:01:03.5433?

> 2022-05-01 21:01:03.5433|ERROR|AppUnhandledException|The parameter is incorrect.

The parameter is incorrect.

	System.ArgumentException: The parameter is incorrect.

The parameter is incorrect.

**Comment by khosravihamidreza** [comment]
Yes, of course, it just happened

**Comment by khosravihamidreza** [comment]
> Thanks for this report. Could you confirm this is when it (last) happened: 2022-05-01 21:01:03?
> 
> > 2022-05-01 21:01:03.5433|ERROR|AppUnhandledException|The parameter is incorrect.
> > The parameter is incorrect.
> > System.ArgumentException: The parameter is incorrect.
> > The parameter is incorrect.

Yes, of course, it just happened

**Comment by Josh-65** [comment]
Is this an issue in the preview version? https://files.community/download/preview
