### ISSUE TITLE
Feature: Switch between items using arrow keys in the conflicts dialog

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#9057]
### Solution/Idea

When renaming mutliple items in the conflicts dialog, users should be able to quickly switch between items using the up/down arrow keys.

### Alternatives

NA

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Pressing the up/down arrow key should switch the focus to the text box on previous/next item | Must |

### Files Version

v2.1.250

### Windows Version

Windows 11

**Comment by Abhi1992002** [comment]
Hi , can you assign this to me?

**Comment by yaira2** [comment]
@Abhi1992002 are you still working on this feature?

**Comment by SohamPande747** [comment]
Hi, I am new to open source.
I want to work on this issue but I have no prior knowledge, can you guide me in right direction so I can work on this.
Thank You
