### ISSUE TITLE
Default file manager

### ISSUE THREAD

**Issue by NeiderCamargo** [files-community/Files#9060]
### What's the Problem?

Why did they remove the feature of being able to place Files as the default file manager in Windows 10? Will this feature return in the future?

![image](https://user-images.githubusercontent.com/61034783/166158102-040e1168-0b65-4d3a-bf46-3e81ebb26214.png)

### Solution/Idea

put the feature back

### Alternatives

nn

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
The option to make Files the default is available in the sideload version https://files.community/download/preview.
