### ISSUE TITLE
The Options To Set As Default Isnt In Settings

### ISSUE THREAD

**Issue by iiTzVonn** [files-community/Files#9067]
### Description

So I recently reset my laptop and when I downloaded files again I went into settings > experimental and the option to set files as default isn't there and I can't find it.

### Expected behavior

I expected the option to set it has the default files app to show up under experimental

### Files Version

Files Version 2.1.15.0 (Downloaded from Microsoft Store)

### Windows Version

Edition	Windows 11 Home Version	21H2 Installed on	‎02/‎05/‎2022 OS build	22000.652 Experience	Windows Feature Experience Pack 1000.22000.652.0

### Relevant Assets/Logs

![Screenshot 2022-05-02 094905](https://user-images.githubusercontent.com/104774298/166244874-e493743d-77d0-4417-9ca4-b5810dcf4826.png)

**Comment by yaichenbaum** [comment]
The option to make Files the default is only available in the sideload version available on our website.

**Comment by iiTzVonn** [comment]
I just downloaded it from your website and it still doesn't have it

**Comment by yaichenbaum** [comment]
@iiTzVonn do you still have the store version installed?

**Comment by iiTzVonn** [comment]
When I went to your site it said download with Microsoft store under it so
probably

**Comment by yaichenbaum** [comment]
This option is only available on the sidelad version https://files.community/download/preview.

**Comment by iiTzVonn** [comment]
wait when I press to make it the default file explorer and I back out it
turns off

**Comment by Josh-65** [comment]
you have to wait a bit for the admin promt to show as it slow at doing it.

**Comment by iiTzVonn** [comment]
nothing happened I waited an hour and got no notification

**Comment by Josh-65** [comment]
Do you have admin rights?

**Comment by iiTzVonn** [comment]
Yh

**Comment by Josh-65** [comment]
I presume you on 2.2.3 since it doesnt work for me either after updating i made an issue for it here #9083

**Comment by iiTzVonn** [comment]
K

**Comment by iiTzVonn** [comment]
Thanks, it works now and does the app auto-update?

**Comment by Josh-65** [comment]
yes
