### ISSUE TITLE
Cant open any folders in desktop after reinstalling Files preview app

### ISSUE THREAD

**Issue by Corrupted123** [files-community/Files#9073]
### Description

Hello. When i tried to make Files the default searcher. it made it unstable so i downloaded it again nd now i cant open any folders in my desktop. this error occurs
![image](https://user-images.githubusercontent.com/92246934/166419538-6656d12b-2031-4917-a17b-57575f47e7d7.png)
The 'application' isnt an app its a folder

### Steps To Reproduce

.

### Expected behavior

..

### Files Version

Files 2.2.1.0

### Windows Version

Windows 11 21H2 OS Build 22000.652

### Relevant Assets/Logs

..

**Comment by Josh-65** [comment]
try turning off the toggle (wait a bit since it slow at doing it) and see if you can open anything. then try turning it on

**Comment by gave92** [comment]
If Josh suggestion doesn't work you can run this script (make sure to save it as a ".reg" file): https://raw.githubusercontent.com/files-community/Files/main/src/Files.FullTrust/Assets/FilesOpenDialog/UnsetFilesAsDefault.reg

**Comment by Corrupted123** [comment]
Thanks!, gave92 i ran the .reg file and i can open my folders and some apps again!
