### ISSUE TITLE
Unable to open folder in a new tab using the middle-mouse button

### ISSUE THREAD

**Issue by itzbluebxrry** [files-community/Files#9076]
### Description

Hi, I encountered an issue regarding a navigation problem where the app hangs whenever I triggered the middle mouse button to open a folder in a new tab, and shows a toast notification saying some errors. After all, the app crashed. I'm not sure what's the main cause of this, but sometimes it happens. It works well all the time.

### Expected behavior

Would open the folder normally without hanging and crashing the app

### Files Version

2.1.24.0

### Windows Version

Windows 11 21H2 build 22000.613

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8611440/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8611442/debug_fulltrust.log)

**Comment by gave92** [comment]
Thanks for this report. There have been many reports of this error:
> 2022-05-03 22:54:50.6538|ERROR|AppUnhandledException|The parameter is incorrect.

element
	System.ArgumentException: The parameter is incorrect

Can someone reproduce?

**Comment by Josh-65** [comment]
Works fine for me on 2.1.50. Can you try using the preview version https://files.community/download/preview

**Comment by itzbluebxrry** [comment]
> Works fine for me on 2.1.50. Can you try using the preview version https://files.community/download/preview

I'm already on the preview version downloaded from the official site, and yeah this problem is not happening every time. But it does, sometimes.

**Comment by vamsi-krishn** [comment]
Yeah this issue does not come often just happens sometimes out of sudden .

**Comment by goosewin** [comment]
I'm unable to reproduce the issue on the latest Preview version. Running Windows 11 21H2 build 22000.978.

Is it possible to outline steps to reproduce?

**Comment by Josh-65** [comment]
Middle click on a folder. It also doesn't happen every time.
