### ISSUE TITLE
Option to turn off individual preferences for column sizes in the details layout

### ISSUE THREAD

**Issue by ohhsodead** [files-community/Files#9077]
### What's the Problem?

As of now, after resizing the columns in a tab/folder and then opening a sub-folder will restore the default column sizes.

### Solution/Idea

An option to remember the column sizes.

### Alternatives

None

### Files Version

Version: 2.1.24.0
OS Version: 10.0.19044.1682

**Comment by gave92** [comment]
Could you add the Files version to the description?
Currently column widths are saved per folder. Are you asking for column sizes to be common to all folders instead?

**Comment by ohhsodead** [comment]
> Could you add the Files version to the description? 

Sorry, added info. Awesome project!

> Currently column widths are saved per folder. Are you asking for column sizes to be common to all folders instead?

Yes, an option to remember all/universal column sizes would be great!

**Comment by yaichenbaum** [comment]
This matches the current behavior in File Explorer, I'm marking this as a discussion to gather additional feedback.

**Comment by ohhsodead** [comment]
> This matches the current behavior in File Explorer, I'm marking this as a discussion to gather additional feedback.

I was confused at first since the original does exactly this (also remembers form size before closing, too). It would nice to have the same look throughout navigations and inside new tabs. Thanks for considering my suggestion! ❤️

**Comment by gave92** [comment]
Sounds it should part of #4155. Users could set the column size on one folder and have a button to "apply to all". This would still allow to customize some folders.

**Comment by Attacktive** [comment]
I second this. I always try to keep the same desired layout no matter what.
Having such an option would be great for me:
![image](https://user-images.githubusercontent.com/66462458/166634383-4000f6e0-17c4-4184-a4a9-8be47c2801de.png)

**Comment by gave92** [comment]
You can already use the same layout everywhere: just turn off the "enable individual preferences for folders" in settings > preferences

**Comment by Attacktive** [comment]
> Note: you can already use the same layout everywhere. Just turn off the "enable individual preferences for folders" in settings > preferences. I'm not sure if it includes column width though.

Ah, thank you. I didn't know that.
The column widths aren't preserved though.
