### ISSUE TITLE
I tried to access the .docker folder on Ubuntu and it was killed

### ISSUE THREAD

**Issue by fox62843** [files-community/Files#9079]
### Description

I wanted to browse the .docker file in the Ubutu distribution in WSL, but the moment I tried to open it, it forcefully terminated.

### Steps To Reproduce

1.Open Files app 
2.Click "Ubuntu" of WSL from the left navigation 
3.home→<User>→.docker It is a forced termination at the time of clicking

### Expected behavior

Like above

### Files Version

2.1.15.0

### Windows Version

Windows 11 21H2 22000.652

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8619833/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8619836/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
@fox62843 is this still an issue in the preview version? https://files.community/download/preview
