### ISSUE TITLE
Polish: "Open file location" in shortcut properties doesn't focus window where tab is opened

### ISSUE THREAD

**Issue by Arno989** [files-community/Files#9080]
### Description

"Open file location" in shortcut properties opens folder in new tab in already open Files window, but doesn't focus the window when the tab is opened

### Steps To Reproduce

Go to any start menu shortcut, then open its properties, focus on another app to hide Files, refocus only details, go to Shortcut tab and click "Open file location", if another window is in front of Files app it won't focus onto the Files window after opening a new tab

### Expected behavior

window where new tab is opened becomes focused so user gets feedback the button actually did something

### Files Version

Version: 2.2.1.0 OS Version: 10.0.22598.200

### Windows Version

Windows 11 22H2 22610.1

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/32594687/166684394-fca7ded0-218a-4be3-bd17-3784e1f536bf.png)

**Comment by Josh-65** [comment]
Is this still an issue?

**Comment by yaira2** [comment]
It focuses the tab for me so I'm assuming it's resolved.
