### ISSUE TITLE
Can't download Custom Themes

### ISSUE THREAD

**Issue by z01ks** [files-community/Files#9084]
I'm on Windows 10, running Files 2.1.15. I'm unable to Upgrade to Windows 11 due to MS not supporting my i7-7700K processor, and maybe because of this my Files is not the latest. It says Custom Themes are bundled with the latest version of Files, but if I can't install that, I can't add any custom themes either.

**Comment by gave92** [comment]
Hi you don't need to install anything in orde to set custom themes. You should find available themes if you go to settings > Appearance. If only the Default theme is available you need to reset the app from windows settings > Apps.
