### ISSUE TITLE
Use 7-Zip / existing archive extraction software if available for extraction

### ISSUE THREAD

**Issue by YourKalamity** [files-community/Files#9086]
### What's the Problem?

The current built in `Extract` function presented when right clicking a zip file is significantly slower than say something like 7-Zip. 
Waiting for the 7 Zip sub-menu to appear only to go to another sub-menu to select extraction using it's software is neither fast or efficient.

### Solution/Idea

When launching the Files application, the system should be searched for popular extraction utilities such as 7-Zip and WinRAR.

Then, when it comes to extracting an archive, if one was found (or if multiple, choose the better performing one), use it's executables to extract (perhaps via invoking a command and passing the file as an argument)

### Alternatives

Allow users to select their own extraction program in the settings

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Automatically detect and use alternate extraction software if available | Must |
| Retain progress percentage in the Ongoing tasks menu | Could |

### Files Version

Version: 2.1.15.0

### Windows Version

Windows 11 21H2 22000.493 Feature Experience Pack 1000.22000.613.0

**Comment by Josh-65** [comment]
There are plans to intergrate 7zip not sure the progress of it but some work has been done

**Comment by yaichenbaum** [comment]
Merging with #45
