### ISSUE TITLE
Use quick access/primary commands in context menu for folder empty space

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#9088]
### What's the Problem?

The context menu on folder in empty zone does not use quick accesses, in particular "Paste" and "Properties".

### Solution/Idea

Use the quick access in all context menus.

### Alternatives

None.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Comments

![MenuPaste](https://user-images.githubusercontent.com/46631671/166799132-ad8ec135-d366-4e2b-95d3-d245ad15ed0e.png)

**Comment by trongnd32** [comment]
Hello @cinqmilleans. Please let me know how can I add third party item in context menu, such as VLC, VS,... like in image you provided. Thank you

**Comment by Josh-65** [comment]
This has been fixed in 2.3.0.0
