### ISSUE TITLE
Preview pane issues

### ISSUE THREAD

**Issue by z01ks** [files-community/Files#9093]
### Description

Buttons on the top right (Selection options, Sort, Layout, Preview pane, More don't scale with the window when the Preview Pane is enabled and its size is maxed out to the left. Also, changing Preview Pane size doesn't work at that point. When I make the window bigger to the right so the button group appears on top right, I can again scale the preview pane freely. If the preview pane is big enough I just have to make Files windowed to lose my top right button group and the ability to move the preview pane.

Also I have another question. Is it possible for me to have the latest release on Windows 10? I am unable to update Win because they don't support my processor.

### Steps To Reproduce

1. Make Files Windowed.
2. Enable Preview Pane
3. Move Preview pane left edge all the way to the left.
4. Grab the right edge of the whole window and move it to the left.

### Expected behavior

You should see the button group disappear and at that point the preview pane left edge becomes unmovable.

### Files Version

2.1.24.0

### Windows Version

10.0.19044.1645

### Relevant Assets/Logs

n/a

**Comment by cinqmilleans** [comment]
@z01ks @yair100 I was able to reproduce the bug. I will try to fix it.

**Comment by z01ks** [comment]
Will it be possible to get this update on Windows 10 or is the latest Files
version only available on Win 11?
