### ISSUE TITLE
Show contents of zip files in preview pane.

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#9094]
### What's the Problem?

The preview pane displays the zip files poster. It doesn't add any value.

### Solution/Idea

It would be convenient to display the contents as a small file/folder tree. This makes it easy to know if the content is a single folder (extract here) or contains multiple items (extract to).

### Alternatives

None

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
@cinqmilleans would displaying an item count in the details section of the preview pane solve help?

**Comment by cinqmilleans** [comment]
@yair100 It would be better, yes. But displaying the content would be a much better added value. I wrote this down to keep track but it's not the most urgent.

**Comment by yair100** [comment]
> @yair100 It would be better, yes. But displaying the content would be a much better added value. I wrote this down to keep track but it's not the most urgent.

You can already view the sub items in the column layout so I'm thinking that item count is the way to go.
