### ISSUE TITLE
📢📢 Planning for the v2.3 release

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#9095]
As development on v2.3 comes to a close, we're going to focus on stability and bug fixes for the next couple of weeks. Pull requests are welcome as always and bug fixes in particular will go a long way towards making v2.3 a stable release.

If you haven't already, you can download the latest preview build from our website https://files.community/download/preview. For any bugs, please comment on an existing issue or create a new one on GitHub.

We're planning to release v2.3 at the beginning of July but please note that the release date can change.

**Comment by carlosvsilva** [comment]
Hi, I've tested the preview release, and I believe issue #6417 should be fixed before release, as every sub-folder resets the view/sort mode (chosen by the user while in the parent folder). Even on folders never opened before.

I guess that folders where the view/sort mode was chosen by the user should keep that setting. Folders that weren't ever changed by the user, should conform to the parent folder view/sort mode.

If accessing a deep folder directly from the address bar, it could display either the closest parent folder custom view/sort modes, or if none were set by the user, just use the last view mode used up to that point. Thanks :)

**Comment by yaichenbaum** [comment]
@carlosvsilva thank you for your feedback, #6417 is a pretty large change and we haven't gotten enough feedback from users to make a decision if and how to implement it.

**Comment by carlosvsilva** [comment]
Ok, I just mentioned it because the current resets to the view seem way off a production software release. I believe literally anything is better than the current situation in navigation, which I believe to be Files main function. Thanks.

**Comment by yaichenbaum** [comment]
@carlosvsilva it's important to note that the current behavior in Files matches the behavior in File Explorer. We're open to changing the behavior but if it's not a regression from previous versions of Files, there isn't any reason to hold back from releasing all the other improvements :)

**Comment by carlosvsilva** [comment]
Fair enough, when I use this Files app I start to expect MacOS quality level consistency in the back of my mind :)
I hadn't noticed this Windows File Explorer behaviour before (always assumed the MS program as hopeless anyway) as it probably was born in a time before UX was even a thought in anyones head eheh
Cheers

**Comment by Davikar** [comment]
Issue #6373 has been around for quite awhile. Has there been any progress on fixing this?

**Comment by yaichenbaum** [comment]
> Issue #6373 has been around for quite awhile. Has there been any progress on fixing this?

We haven't worked on it yet but we think there are a couple of ways to resolve it.

**Comment by Midosa5** [comment]
Files 2.1.24.0 is a cool and stylish idea - it's better and more promising than the regular one, but!

1. Slows down on Win11 22H2 22610.1 when drawing file icons. Sometimes it doesn't draw everything.

2. It is bad that it is impossible, as with the regular explorer, to reduce the interval between folders vertically. At a resolution of 3840*2160, a scale of 300%, too much space is wasted.

3. It's too bad that there is no undo/redo function (undo move, rename, delete, etc.) - why was it removed?

4. When working with the mouse with 1 click is configured, the possibility of cursor interaction has disappeared - for example, with a regular explorer, you can hover the cursor over a folder or file and, by tapping F2, rename the file or simply select it - you have to click the mouse in Files (especially inconvenient when renaming or selecting several files while holding ctrl).

5. Column width adjustment does not work at all - it cannot be fixed, it constantly creeps away when the window is enlarged/decreased - even when returning to the previous window size, the column width is constantly reduced to a complete inconvenience. Often the possibility of adjustment disappears - it is impossible to pick up.

6. When moving files, folders - moving is not always correct => sometimes part is copied to a new location, and part remains in the old one.

Well, the little things:

7. On a dark acrylic theme, the "Properties" of files and folders do not work.

8. For some reason, the size of folders is recalculated every time - isn't it better to fix it somehow somewhere - and if there were no changes in the folder, then just take the previous size? Does it make sense to recalculate in the absence of changes? And they are visible in the properties of any folder. You can, of course, disable the output of the size of folders - but is it possible to fix it?

If these nuances were fixed... would be in general, practically, ideal.)))
Thank you!

**Comment by yaichenbaum** [comment]
Thank you for all your feedback, v2.3 is now in the final stage of testing and should be available for everyone on July 6th.
