### ISSUE TITLE
Task manager cannot open file location

### ISSUE THREAD

**Issue by Xiaomo250** [files-community/Files#9097]
### Description

When using the task manager to open the location of the file, the taskbar icon of Files will flash and then exit.
But if Files is open, it will open normally.
I haven't tried any other way to open the file's location.
(These were translated by Google Translate, so I don't know if the representation is correct.)

### Steps To Reproduce

1. Open task manager
2. Right-click on any item and select "Open file location"
3. Files' taskbar icon appears and disappears

### Expected behavior

Correctly open file location even if Files are not open

### Files Version

Version: 2.1.24.0 OS Version: 10.0.19044.1566

### Windows Version

Windows 10 21H2 19044.1566

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8636911/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8636912/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
This issue is resolved in `main`. You can also try uninstalling the current version of Files (make sure to turn off the default beforehand) and installing the preview version https://files.community/download/preview.
