### ISSUE TITLE
Favoritos / acesso rapido

### ISSUE THREAD

**Issue by fisilva84** [files-community/Files#9099]
### What's the Problem?

os favoritos do files nao estao linkados ao acesso rapido do windows.. como o files nao atua sobre as janelas de abrir dos aplicativos seria interessante que tivessemos a opção de incluir pastas e arquivos no acesso rapido do windows

### Solution/Idea

incluir o item acesso rapido a coluna esquerda do files e a opção de incluir no acesso rapido no menu suspenso

### Alternatives

penso que pode ser acrescentado o item acesso rápido na coluna esquerda ou pode simplesmente substituir a coluna favoritos pelo acesso rápiido

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by Josh-65** [comment]
Merging with #8797. The team have said they don't want to auto sync the content but possibly add an import feature
