### ISSUE TITLE
Favorites starts closed but Files thinks it's open

### ISSUE THREAD

**Issue by ruilvo** [files-community/Files#9101]
### Description

When I open Files, the Favourites menu is closed, but the icon is with the arrow as if it was open. Clicking it actually changes the icon to closed, and only clicking _again_ opens the menu.

Check video:

https://user-images.githubusercontent.com/8402646/167170385-a4cfecb5-8948-41e9-a8ee-2513f5501fb6.mp4

### Steps To Reproduce

1. Close files with the Favourites menu open;
2. Open Files
  2.1 Now Favourites are closed. Click it. Arrow icon changes
  2.2 Click it. Now Favourites open.

### Expected behavior

For the Favourites menu to stay open between closing and reopening Files.

### Files Version

Files 2.1.24.0

### Windows Version

Windows 10 Pro 21H2 19044.1682 exp. pack 120.2212.4170.0

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8642065/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8642066/debug.log)

**Comment by yaichenbaum** [comment]
@ruilvo this issue should be resolved in the latest preview build https://files.community/download/preview.
