### ISSUE TITLE
Navigation issue in column view

### ISSUE THREAD

**Issue by fairholm** [files-community/Files#9102]
Hi,
Just downloaded the app (77 year old non-geek here) and am VERY impressed.

Don't know if this is a bug.

I have opened COLUMNS in Layout
It shows folders and single items.
I click on a folder and it shows contents in another column to the right. Great.
I go back to my ORIGINAL column and click on a single item.

The item shows up fine in the right hand PREVIEW Pane, but the folder contents I looked at previously remain.
This is not the end of the world, but very messy. ... I don't STILL want to view those contents ... I have moved on.

So ... don't know if this is a bug, or something I have to get used to.

Thanks for your ace work which makes exploring files SO much easier.
Dave Corbett

**Comment by yaichenbaum** [comment]
Thank you for the question, can you upload a screen recording of the issue so I can review the beahvior?

**Comment by fairholm** [comment]
Wow, swift response Yair. So, I opened the older BARN DANCES folder and then decided to look at the file beneath that folder,  a single file, BEYOND THE SUNSET. As you will see, Beyond the Sunset comes up on the right in Preview, but I am also still seeing the list of dances from the Barn Dance Folder, which is rather confusing. It would be great if that Barn Dance folder content column had disappeared when I accessed Beyond the Sunset.Not a world changer ... but a bit annoying. Dave     Sent from Mail for Windows From: Yair AichenbaumSent: 06 May 2022 17:27To: files-community/FilesCc: fairholm; AuthorSubject: Re: [files-community/Files] Almost perfect !! (Issue #9102) Thank you for the question, can you upload a screen recording of the issue so I can review the beahvior?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by yaichenbaum** [comment]
@gave92 are you able to repro this?

**Comment by fairholm** [comment]
Really sorry … no idea what you mean.
 It happens with every folder I open

**Comment by gave92** [comment]
Yeah, I think he's referring to this behavior
https://user-images.githubusercontent.com/9673091/167197673-0f4ddcd0-053e-44aa-9705-11d6c11ed801.mp4

**Comment by fairholm** [comment]
Sorry, when I click on “this behaviour “ it doesn’t load.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by yaichenbaum** [comment]
> Yeah, I think he's referring to this behavior https://user-images.githubusercontent.com/9673091/167197673-0f4ddcd0-053e-44aa-9705-11d6c11ed801.mp4 When you click on a file in the first column, the second column does not close.

I think it's okay to leave as is but I'm not against changing it if that's what most users expect.

**Comment by gave92** [comment]
I actually prefer the current behavior. Makes it easier to move files across columns without having to re-navigate.
