### ISSUE TITLE
Bug: Address bar has wrong path in column mode

### ISSUE THREAD

**Issue by carlosvsilva** [files-community/Files#9103]
### Description

Whenever I use WSL (Ubuntu from the MS Store app) in Column Mode, it lacks the current open folder in Path bar at the top.

![image](https://user-images.githubusercontent.com/40889421/167173205-127fc173-9d65-4b3e-890d-f56e8f50ce50.png)

### Steps To Reproduce

1. Open folder in the column layout
2. Navigate down a couple directories from the root
3. Notice that if the cursor is focused on the last column, the address bar doesn't reflect the focused column.

### Expected behavior

Files should display the correct path when the last column is selected.

### Files Version

Version: 2.1.15.0

**Comment by yaichenbaum** [comment]
@carlosvsilva I just tested in the latest preview build with a Debian distro and it's working as expected. Can you see if the preview build fixes the issue for you as well? https://files.community/download/preview.

**Comment by carlosvsilva** [comment]
That latest preview build still displays the same behavior above:

![image](https://user-images.githubusercontent.com/40889421/167177371-09c2dae4-0299-4a08-9e0e-f6f65ce459b0.png)

**Comment by gave92** [comment]
Does the path updates if you click on the last open column empty space?

**Comment by carlosvsilva** [comment]
it does update! however, with 2 clicks the entire path on the address bar disappears and files from the current open folder disappear too!

This is happening system wide, not just WSL, confirmed now.

![image](https://user-images.githubusercontent.com/40889421/167179671-b7694e1d-7410-44c8-81cc-0bc1c5047782.png)

**Comment by gave92** [comment]
Thanks for the update. Double click on empty space navigates up one level, so the last column closing is expected. Path disappearing.. not expected 🤔

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?

**Comment by carlosvsilva** [comment]
Yes:

![image](https://user-images.githubusercontent.com/40889421/179317713-6e0e9dd6-671d-4432-967e-6f66f6dcb106.png)

**Comment by Colin-VideoRevealed** [comment]
This also happens on Windows 11. Is this going to be fixed there too?

**Comment by hecksmosis** [comment]
So the expected behavior for this is to display the path of the last open column? (For example, if i double click a folder to open it in a new column but don't select the new column, the path should be the one of the new column)

**Comment by yaira2** [comment]
We should try that and see how it goes. Column Layout is something new to me so no hard opinions on it 😂

**Comment by hecksmosis** [comment]
Ok, I'll look into this

**Comment by hecksmosis** [comment]
I'm currently waiting for #11003 to be merged before looking at this

**Comment by Lukiluc29** [comment]
From my side, I have the same case happening, where when you click on the first folder, the path bar doesn't update. However, when you click on a second folder, it updates but only shows the first folder and not the second one. And this process repeats.

**Comment by Lukiluc29** [comment]
Do you have any news on this issue? When copying the file/folder path in columnar mode, it can be a bit inconvenient.

**Comment by yaira2** [comment]
@hecksmosis did you get a chance to look into this?

**Comment by hecksmosis** [comment]
Sorry, moving house has taken a lot of my time lately (which is why I haven't been able to contribute these past weeks). If someone wants to work on this in the meantime they're free to do so

**Comment by yaira2** [comment]
@carlosvsilva thank you for your feedback, focusing in the last column now updates the address bar.

**Comment by yaira2** [comment]
> Do you have any news on this issue? When copying the file/folder path in columnar mode, it can be a bit inconvenient.

@Lukiluc29 this sounds like a different issue where the focus isn't moved to the most recently opened column.
