### ISSUE TITLE
Crashes on copying folder

### ISSUE THREAD

**Issue by DeveloperWOW64** [files-community/Files#9104]
### Description

I've got my website code folder and have attempted to copy it to a new location.
It's quite large, but not that much. It has a git repo associated with it and a changed icon - not that that matters.
Upon copying it waits for a bit, saying the copy has 0.00% of it completed, then crashes, giving me the bug report toast.

### Steps To Reproduce

1. Copy folder to a new location
2. Wait
Application crashes.

### Files Version

Version: 2.2.4.0 OS Version: 10.0.22000.652

### Windows Version

10.0.22000.652

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8642326/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8642327/debug_fulltrust.log)

**Comment by gave92** [comment]
Should be fixed in latest preview
