### ISSUE TITLE
Tag colors set in current released version show up as color Unknown in current prerelease

### ISSUE THREAD

**Issue by carlosvsilva** [files-community/Files#9107]
### Description

If I'm using Files in the current release version from the MS Store (Version: 2.1.15.0
OS Version: 10.0.22000.652), and I tag a file as 'red' , then later, if I see this same file in the prerelease version of Files (Version: 2.2.4.0
OS Version: 10.0.22000.652), the file tag shows up as 'gray' Unknown color.

### Steps To Reproduce

1. Tag any file as a color tag like 'red' in Files 2.1.15.0
2. Open the same directory as that file in prerelease version of Files 2.2.4.0
3. See the file tag in the prerelease Files, as color 'gray' and name 'Unknown'

### Expected behavior

A file tagged Red in a Files release, should continue to be tagged Red in any future updates, barring any intentional changes for future proofing the internal tags mechanism while in EXPERIMENTAL mode.

### Files Version

Version: 2.2.4.0

### Windows Version

OS Version: 10.0.22000.652

#### Prerelease Files 
[debug.log](https://github.com/files-community/Files/files/8643187/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8643188/debug_fulltrust.log)

![Tags-preview](https://user-images.githubusercontent.com/40889421/167205591-98b54b37-3c6f-4709-af83-6d84b43b38ac.png)

#### Stable release Files
[debug.log](https://github.com/files-community/Files/files/8643192/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8643193/debug_fulltrust.log)

![Tags-release](https://user-images.githubusercontent.com/40889421/167205589-e6787b9d-71f7-4196-9790-8716d7f120bf.png)

**Comment by gave92** [comment]
That's expected, tags . To make them appear in the other versions you can copy the file "filetags.json" from the Store version to the other. The files can be found e.g here: "%LocalAppData%\Packages\Files_1y0xx7n9077q4\LocalState\settings\filetags.json" for the sideload version, similar path for Store. File can also be opened by going to Settings > Experimental > Tags > Edit
