### ISSUE TITLE
Could not open DVD device.

### ISSUE THREAD

**Issue by aiastia** [files-community/Files#9109]
### Description

Unable to open dvd device.
I put in the CD and I can open it with the file manager that comes with the system. But this software prompt pops up

### Expected behavior

open dvd device.

### Files Version

2.1.24.0

### Windows Version

Windows 10 专业工作站版  21H1 19043.1645

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8644194/debug.log)

**Comment by yaichenbaum** [comment]
@aiastia can you share a screenshot?
