### ISSUE TITLE
I can't make files my default file app

### ISSUE THREAD

**Issue by Onatic48** [files-community/Files#9112]
### Description

When opening settings in files, in the Experimental tab, there are only 2 options; "Enable file tags" and "Show folder sizes" I can't see the option for making a files app to make my default file app.

### Steps To Reproduce

1. Go to settings,
2. Go to the experimental tab
3. There is no option.

### Expected behavior

I should see option for make files default folder app.

### Files Version

2.1.150.0

### Windows Version

Windows 11 Pro 21H2 6.02.2022 22000.652

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8645751/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8645752/debug.log)

**Comment by gave92** [comment]
Only available in the sideload version -> http://files.community/download/preview
