### ISSUE TITLE
Custom/modify shortcuts

### ISSUE THREAD

**Issue by Someone-Somwhere** [files-community/Files#9118]
### What's the Problem?

My idea is to allow users to change the shortcuts that are in the Files app. This will allow the app to be customized more for each person as people might be used to one shortcut for an app but on Files it is different. 

### Solution/Idea

To allow user to customize shortcuts in the app

### Alternatives

N/A

### Files Version

Version: 2.1.15.0 OS Version: 10.0.19044.1682

### Windows Version

Edition	Windows 10 Pro Version	21H2 Installed on	‎13/‎02/‎2022 OS build	19044.1682 Experience	Windows Feature Experience Pack 120.2212.4170.0

**Comment by Josh-65** [comment]
You already can if you open the properties on the shortcut using the right click menu or toolbar > then customise (sometimes its in a ... menu)

**Comment by Someone-Somwhere** [comment]
> You already can if you open the properties on the shortcut using the right click menu or toolbar > then customise (sometimes its in a ... menu)

![image](https://user-images.githubusercontent.com/71657811/167302105-3e1a6dc9-04ae-4a1a-b3ee-ae888b359457.png)
I can't find it.

**Comment by Josh-65** [comment]
Properties

**Comment by Someone-Somwhere** [comment]
> click Properties

![image](https://user-images.githubusercontent.com/71657811/167302237-03d2a71d-dd32-48f2-82ab-f85f31352bc9.png)
Where?

**Comment by Josh-65** [comment]
You have to be on a shortcut for the shortcut spcific options

**Comment by Someone-Somwhere** [comment]
> You have to be on a shortcut for the shortcut spcific options

What I mean is that to duplicate a tab in the Files app I need to right-click on the tab and press duplicate or press ctrl shift K. But on Google Chrome I have an extension which means that I can press shift d to duplicate a tab. So that is why I think it is a good idea to add an option to the app.

**Comment by Josh-65** [comment]
Oh you mean keyboard shortcuts. Merging with #1660 then

**Comment by yaira2** [comment]
@Someone-Somwhere This feature will be included in the next release. Please see #9559 for more details.
