### ISSUE TITLE
Trying to delete folder while child directory is open in column view prompts for admin rights and still fails

### ISSUE THREAD

**Issue by CrypticVader** [files-community/Files#9122]
### Description

Trying to delete a folder while another directory within the folder is already open in column view will make the app request for admin privilege, but still fails the operation.
![](https://cdn.discordapp.com/attachments/725514946112127057/972930354094698597/unknown.png)

![](https://cdn.discordapp.com/attachments/725514946112127057/972930481383415818/unknown.png)

### Steps To Reproduce

1. Open any directory in column view.
2. Now open any folder within the previously open folder.
3. Now try deleting the root folder.

### Expected behavior

The selected folder should be deleted.

### Files Version

v2.2.5.0

### Windows Version

Windows 11 22H2 22616

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8647573/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8647574/debug_fulltrust.log)

**Comment by CrypticVader** [comment]
This issue no longer is applicable since the whole flow of navigation in the column view has changed.
Unlike previously when a tree of directories opened in column view & you clicked/selected the root directory, the child folders still remained open. With the new version of Files, when you attempt to select the root folder of another folder that is open in column view, it automatically closes all folders hierarchically until the root folder.
I do not know if this change is intentional, but the new behavior has been a bummer for me & the column view is no longer as useful as it was previously.

**Comment by yaira2** [comment]
The changes were intentional, the previous implementation had many issues (including this one). For what it's worth, the new behavior is similar to the way it works in Finder.
