### ISSUE TITLE
There is a black box under the folder icon

### ISSUE THREAD

**Issue by Thothinfoicon** [files-community/Files#9124]
### Description

There is a black box under the folder icon[](url
![企业微信截图_16520579968550](https://user-images.githubusercontent.com/34643944/167324049-be89aae6-8520-47d8-b070-e5c88bbc9f58.png)
)

### Expected behavior

Do not show black box

### Files Version

版本: 2.1.15.0 OS Version: 10.0.22000.652

### Windows Version

Windows 11 21H2 22000.652

### Relevant Assets/Logs

[Uploading debug.log…]()
[Uploading debug_fulltrust.log…]()

**Comment by gave92** [comment]
Merging with #6373
