### ISSUE TITLE
Bug: Thumbnails are displayed in the wrong aspect ratio

### ISSUE THREAD

**Issue by gave92** [files-community/Files#9129]
### Description

Issue #8128 is back. Thumbnails of images are cropped into squares.

Fixed in #5717, reintroduced (probably) in #5842.

### Steps To Reproduce

1. Navigate to a folder with images
2. Switch to any grid layout
3. See that image thumbnails are displayed as squares

### Expected behavior

- Thumbnails should display with the correct aspect ratio in the grid layouts

### Files Version

main (2.2.5)

### Windows Version

OS Version: 10.0.19043.1110

### Relevant Assets/Logs

<img src="https://user-images.githubusercontent.com/14127357/127717298-0a6eb243-64ff-4b0f-835f-6b1d420f52af.png"/>

**Comment by cinqmilleans** [comment]
@gave92 After checking, it is possible to have the correct ratio by using ThumbnailMode.SingleItem. But it doesn't work if thumbnails are disabled in File Explorer.

**Comment by gave92** [comment]
Edit: looks like PR #7881 changed mode from SingleItem to DocumentsView to fix thumbnails generated by SageThumbs.

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
Approved 👍
