### ISSUE TITLE
Column view position sometimes resets to the left

### ISSUE THREAD

**Issue by zqbest** [files-community/Files#9133]
### Description

When I use column view, when the folder level is greater than 6 or 7 levels, it does not correctly display the smallest folder level on the far left。The filer's lateral movement bar is bouncing repeatedly。

### Expected behavior

Hopefully this will be resolved quickly，thanks！

### Files Version

2.1.15.0 OS Version: 10.0.22000.613

### Windows Version

Windows 11 21H2 22000.613 

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8657425/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8657426/debug.log)
![20220510123653](https://user-images.githubusercontent.com/80334288/167543576-3977106a-d0f4-46e5-a42f-f2e54eb58e6c.png)

**Comment by zqbest** [comment]
Additional note: This bug will not appear until I double-click the folder

**Comment by yaira2** [comment]
Is this still an issue in v2.4?
