### ISSUE TITLE
Default app

### ISSUE THREAD

**Issue by SHADOWBOY9559959595** [files-community/Files#9134]
### Description

Well i dont really know if it is a bug or a thing they took out of the app but i remember that you could put files as you default files explorer but now the button isnt ther
![ApplicationFrameHost_PeURJRAiZR](https://user-images.githubusercontent.com/92395457/167547525-84fa7e4f-ff3c-4c37-885f-10cd62ee574f.png)
e

### Steps To Reproduce

go to settings
go to experimental options

### Expected behavior

see a button where you can set files as the default file browser

### Files Version

Versión: 2.1.15.0 OS Version: 10.0.22616.1

### Windows Version

Windows 11 22H2  22616.1

### Relevant Assets/Logs

?

**Comment by gave92** [comment]
Setting is only available in the sideloaded version: https://Files.community/download/preview
