### ISSUE TITLE
Does not automatically update the Folder content

### ISSUE THREAD

**Issue by Rudi54rv** [files-community/Files#9135]
### Description

Hello, the Files app is a real good explorer and i like to use it. But while i'm often work on Servers the Folder Content is not recently updated. If i rename a File, i have to manually update the Folder to see the new name of the file.
Also if i work on Local server the Files-Explorer is very slow in content of switching between folders and stuff like that.

### Steps To Reproduce

Open a folder on a local Server
Rename a for example *pptx-file

### Expected behavior

The expected behaviour is like in the Microsoft's Explorer, that there is no delay in seeing changes

### Files Version

2.1.15.0

### Windows Version

Windows 10 Pro 21H2 19044.1645

### Relevant Assets/Logs

no log file

**Comment by gave92** [comment]
Fixed in 2.2.5
