### ISSUE TITLE
explorer.exe crashes when trying to run files while offline.

### ISSUE THREAD

**Issue by demperor-music** [files-community/Files#9139]
Files keeps crashing my explorer.exe on Windows 11 whenever i try to open it offline, which is odd.
**It used to work just fine before**, but when i upgraded to windows 11 it just **wouldn't open while offline and would crash my explorer**, making my taskbar and desktop restart.
I hope you guys fix this, here's a video attachment to show what's happening. I'm using internet over bluetooth.
https://user-images.githubusercontent.com/30912893/167702380-004c5578-d7a2-478b-aeb1-6de8ecfa9aa5.mp4

In case there are some logs I can show you I'd be glad to do so.

**Comment by yaichenbaum** [comment]
Thank you for taking the time to report this, in order to investigate the issue we'll need the log files, can you please reopen this issue using the issue template?
