### ISSUE TITLE
Explorer.exe crashes when opening Files offline.

### ISSUE THREAD

**Issue by demperor-music** [files-community/Files#9140]
### Description

Files keeps crashing my explorer.exe on Windows 11 whenever i try to open it offline, which is odd.
**It used to work just fine before**, but when i upgraded to windows 11 it just **wouldn't open while offline and would crash my explorer**, making my taskbar and desktop restart.
I hope you guys fix this, here's a video attachment to show what's happening. I'm using internet over bluetooth.
https://user-images.githubusercontent.com/30912893/167702380-004c5578-d7a2-478b-aeb1-6de8ecfa9aa5.mp4

### Expected behavior

The app should open and not crash windows' file explorer.

### Files Version

Versione 2.1.24.0 OS Version: 10.0.22000.613

### Windows Version

Windows 11 Pro 21H2 22000.613

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8664515/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8664486/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
@demperor-music is this the store version?

**Comment by demperor-music** [comment]
> @demperor-music is this the store version?

No, installed it using the .appInstaller file

**Comment by yaichenbaum** [comment]
While it's not expected to crash explorer, the way appinstallers handle updates requires there to be an internet connection. We're looking to move away from this format, but this is the expected behavior in the current build.
