### ISSUE TITLE
opening downloads via the home menu opens it at the date the program was installed

### ISSUE THREAD

**Issue by Lord-Excursius** [files-community/Files#9141]
### Description

when opening the downloads folder via the Home menu opens the menu scrolled down to the date the program was installed (when sorted by date)

### Steps To Reproduce

1. sort files by date
2. go to home
3. open downloads via the main menu (on the right)
4. see the error

### Expected behavior

the downloads page should open at the top (aka the most recent file)

### Files Version

2.1.24.0

### Windows Version

Windows 11 22H2 22616.1

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/85514013/167722249-d4feef72-0726-4b4d-af31-68832b39fa0d.png)
![image](https://user-images.githubusercontent.com/85514013/167722292-694a46a0-25c7-453f-bf52-3f2b79a107ad.png)
![image](https://user-images.githubusercontent.com/85514013/167722304-f29c4d1b-f34d-4bd1-a15a-9f7f98935998.png)

**Comment by yaichenbaum** [comment]
Merging with #6186
