### ISSUE TITLE
still isnt set as default file system

### ISSUE THREAD

**Issue by YourMomsFriend** [files-community/Files#9143]
### Description

I downloaded github/sideload version, the toggle showed, but when I open a file it still opens Explorer even after a restart

### Expected behavior

actually be functional as default file system

### Files Version

2.1.14.0

### Windows Version

windows 10 21H2

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8669031/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8669032/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
v2.1.14 isn't supported. Please try using the latest preview https://files.community/download/preview.
