### ISSUE TITLE
Search results not searching through file contents (as the default windows explorer does)

### ISSUE THREAD

**Issue by ludvigpujsek** [files-community/Files#9148]
As described in the title, it doesn't seem as if the Files App searches through file contents when searching within a folder (regardles whether the folder is indexed or not). I don't particularly mind, as i can just momentarily use the Windows default explorer, but as a student with lots of scattered note-taking documents on his computer, it would be rather nice to be able to search for a phrase, and get all documents matching said phrase. Oh, and... Otherwise the app is absolutely amazing :)

**Comment by Josh-65** [comment]
Mergin with #8815. Please use the template if you open any more issues.
