### ISSUE TITLE
Bug: Set as default file manager affects other user accounts

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#9149]
### Description

When it set files as default other accounts are force to use files. Opening anything that uses file explorer just shows the "application not found" message with no promt to change it back like it does normaly. Disabling the default toggle effect all accounts also.

### Steps To Reproduce

1. Create a second user account on Windows
2. Install Files and set as the default file manager on one of the accounts
4. Switch to the user account without Files
5. Try to open File Explorer and see error message

### Requirements 
- Option to set the default file manager should only apply to the current user account

### Files Version

2.2.5.0

### Windows Version

10.0.19043.1685

### Relevant Assets/Logs

Account with toggle enabled
[debug_fulltrust.log](https://github.com/files-community/Files/files/8673342/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8673344/debug.log)

Account that should not be affected
[debug_fulltrust.log](https://github.com/files-community/Files/files/8673348/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8673349/debug.log)

**Comment by gave92** [comment]
Hi @Josh-65 could you try the following?
1. Start from a "clean state": Files not set as default on any account, explorer working
2. Turn on the toggle in Files on one account and close the app
3. Run "UnsetFilesAsDefault.reg" from the archive
4. Run "SetFilesAsDefault_HKCU.reg" from the archive
5. Check if Files is set as default only on one account

[SetFilesAsDefault_HKCU.zip](https://github.com/files-community/Files/files/8693981/SetFilesAsDefault_HKCU.zip)

**Comment by Josh-65** [comment]
Yep that work for settitng it on one account only.

**Comment by gave92** [comment]
Nice, lastly could you confirm that if you do the steps above:
- If you open Files, the toggle is turned on
- If you turn the toggle off, Files is correctly unset as default

**Comment by Josh-65** [comment]
yep

**Comment by ZaLiTHkA** [comment]
thanks @gave92, I didn't see this one before I logged #9838.

**Comment by Josh-65** [comment]
Has this fix been added to the normal setting yet?

**Comment by gave92** [comment]
The issue with multiple accounts has not been not addressed yet.

**Comment by yaichenbaum** [comment]
Is there a confirm fix that works?

**Comment by Josh-65** [comment]
graves first comment under the issue works fine for me
