### ISSUE TITLE
Bug: Ongoing tasks icon shows file transfer complete when the operation failed

### ISSUE THREAD

**Issue by lightningHoneypot** [files-community/Files#9151]
### Description

This is a transfer from a related solved issue referenced in: https://github.com/files-community/Files/issues/7947#issuecomment-1124382038

In essence, when transferring a file that is still opened by a program, Files still shows a checkmark on the ongoing tasks icon that it makes it look like a file transfer is successful,  before then the error box appears stating that a process is still using the file in question. 

### Steps To Reproduce

1. Take one file and one folder
2. _Important: Open the file first_
3. Move the file to a folder
4. See that the check mark appears by the status center even though the operation failed

### Expected behavior

1. The ongoing tasks icon is supposed to show a ❌ mark first before showing an error message, however, it shows a ✔. It converts to a ❌ mark once the user cancels the transfer.

### Files Version

Version: 2.2.5.0 OS Version: 10.0.19043.1645

### Windows Version

Windows 10 21H1 Build 19043.1645

### Relevant Assets/Logs

Skip to 0:08 to see the issue in question

https://user-images.githubusercontent.com/88814097/167968517-0b4e8b03-4e2a-47f3-85ff-ac9dcf0c51ff.mov

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by lightningHoneypot** [comment]
Sorry for not replying on time, I was busy this week
let me test

**Comment by lightningHoneypot** [comment]
Nope, it still shows it green if the file is open, look at the top right corner.

https://user-images.githubusercontent.com/88814097/200194592-98bfb895-8995-4e3e-b42a-11218fb28762.mp4

**Comment by yaichenbaum** [comment]
Thank you for the recording and detailed steps to reproduce this issue.

**Comment by lightningHoneypot** [comment]
> Thank you for the recording and detailed steps to reproduce this issue.

you're welcome! :)
