### ISSUE TITLE
Open Menu

### ISSUE THREAD

**Issue by BragonGod** [files-community/Files#9152]
### What's the Problem?

So when you try to upload an image or something, or import something to an application it still uses the old explorer despite setting files as default in the experimental settings

### Solution/Idea

If it's possible to make it so files shows up instead of the old explorer, that'd be very nice

### Alternatives

![image](https://user-images.githubusercontent.com/86886423/167969591-ff5854fd-61d0-466f-880b-ab93e9256ad4.png)
![image](https://user-images.githubusercontent.com/86886423/167969695-bd1c14cd-54c5-459a-a35d-d0933b7ee611.png)

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
@BragonGod this isn't posible right now but it's something that we're exploring.
