### ISSUE TITLE
The app only copies first 20 files from my android phone's DCIM folder

### ISSUE THREAD

**Issue by navedrasul** [files-community/Files#9159]
### Description

I lost a lot of media because your app only copied first 20 files from my android phone's DCIM folder. I pressed Ctrl+a to select all of the files in the source folder and then pressed Ctrl+v in the destination folder. I thought that all of the files have been copied but it only copied first 20 files. I deleted the files in the source folder to free up the space. What would you say and do over this? 😐

### Steps To Reproduce

1. Go to a folder with more than 100 photos and videos files. Call this folder the source folder.
2. Press Ctrl+a to select all of the files in the source folder.
3. Go to another empty folder. Call this the destination folder.
4. Press Ctrl+v in the destination folder
5. Count the number of files copied to the destination folder.

### Expected behavior

All files should have been copied from source to the destination folder

### Files Version

2 

### Windows Version

Windows 11

### Relevant Assets/Logs

None

**Comment by Josh-65** [comment]
Plase update the file version and windows version using Files settings > about > copy on the top item
