### ISSUE TITLE
Adding the Ctrl + L command to more easily access the address bar

### ISSUE THREAD

**Issue by Darbyus** [files-community/Files#9160]
### Solution/Idea

On the original Windows Files app you could easily access the address bar when pressing Ctrl + L. It's a basic functionality that is present even on web browsers with search bars. I believe Files V2 should have this feature since is very convenient and it's extremely easy to implement. I've been using this command for so long on so many apps that it feels wrong to not have it here, on a file managing app.

### Alternatives

That's pretty much it.

**Comment by gave92** [comment]
Thanks for the report. Files already has that feature. What version are you on?

**Comment by Darbyus** [comment]
> Thanks for the report. Files already has that feature. What version are you on?

I'm on version 2.1.24.0

**Comment by gave92** [comment]
That version should have Ctrl+L support everywhere except on the Home page. Does it work when you're browsing a folder? If not, does Alt+D work to do the same? If not, do other shortcuts (Ctrl+C, Delete, etc) work for you?

**Comment by Darbyus** [comment]
Now that you've mentioned it actually works but not on the Home Page. I'm wondering why.

**Comment by gave92** [comment]
Thanks for confirming. We've fixed that some time ago. You may want to try the [preview version](https://files.community/download/preview) that includes the fix.
