### ISSUE TITLE
Causes the windows explorer application to restart

### ISSUE THREAD

**Issue by saeedNW** [files-community/Files#9161]
### Description

Whenever I try to open files without an Internet connection, it restarts Windows Explorer.
I tried both the sideload package and sideload package (preview), and there was no different.

### Steps To Reproduce

1. Disconnect from the Internet.
2. Run the program.
3. Windows Explorer will be reset

### Expected behavior

Open the app without any problems with or without an internet connection.

### Files Version

2.1.24.0

### Windows Version

Windows 11 21H2 22000.613

### Relevant Assets/Logs

https://user-images.githubusercontent.com/91555175/168383541-fe5416d7-ed8b-4a47-a049-cf8e4a8ede13.mp4

**Comment by gave92** [comment]
Thanks for the report. This issue should be fixed on main. @yair100 since what preview version (if any) did we include the fix?

**Comment by yaichenbaum** [comment]
@gave92 v2.2.8 but it's not a definite fix right now.

**Comment by saeedNW** [comment]
Hi @gave92 , @yair100. thanks for the responses. So what I'm getting is that the fixed version isn't downloadable yet. right? Is there any way to temporarily get around this problem until the fixed version is released?

**Comment by yaichenbaum** [comment]
@saeedNW you can work around this by building from the source code or installing the app from the store.
