### ISSUE TITLE
Crash after deletion

### ISSUE THREAD

**Issue by WirelessSwitcher** [files-community/Files#9164]
### Description

Files have crashed after deleting a zip file.

### Steps To Reproduce

1. Create two zip files in the folder "C:\Users\$user\Documents\coding"
2. Delete first file;
3. Check "Delete Permanently";
4. Wait green icon on top right corner;
5. Delete second file;
6.  Check "Delete Permanently";
7. The second file isn't deleted.

### Expected behavior

Deletion of the files and no crashes.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.19044.1586

### Windows Version

Windows 10 21H2 19044.1586

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8692619/debug.log)

**Comment by gave92** [comment]
Thanks for the report. This issue should be fixed on main.

**Comment by WirelessSwitcher** [comment]
Thank you for the quick response!!
