### ISSUE TITLE
App Crash when media ends playing in the preview panel

### ISSUE THREAD

**Issue by tomijovanoski** [files-community/Files#9167]
### Description

When playing an mp3 file directly in the preview pane, the app crashed when the mp3 file finished playing.

### Steps To Reproduce

1. Select any mp3 (or supported media file)
2. Hit play in the preview pane (if not visible, toggle it on with `Ctrl+P`)
3. Wait till the mp3 file is played till the end

* Bonus info: I've tested this while the app was in the background (I was doing some work in another window)

### Expected behavior

The app shouldn't crash when the mp3 file finish playing in the preview pane.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.19044.1706

### Windows Version

Windows 10 Pro 21H2 19044.1706

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8693824/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8693825/debug.log)

**Comment by gave92** [comment]
> 2022-05-14 22:35:34.8129|ERROR|AppUnhandledException|Layout cycle detected.  Layout could not complete.
Layout cycle detected.  Layout could not complete.
	Windows.UI.Xaml.LayoutCycleException: Layout cycle detected.  Layout could not complete.
Layout cycle detected.  Layout could not complete.

**Comment by Josh-65** [comment]
Merging with #9019. Since it the same error causing this.
