### ISSUE TITLE
Add support for dragging and dropping favorites to rearrange

### ISSUE THREAD

**Issue by the-garlic-os** [files-community/Files#9168]
### What's the Problem?

In native Explorer, you can drag and drop favorites to rearrange them. That was one of the first things I tried to do when I got Files, and I was disappointed that I couldn't do it.

### Solution/Idea

Implement dragging and dropping items within the Favorites sidebar to rearrange their order in the menu, like how you can in Explorer.

### Alternatives

Moving favorites from buttons in the context menu just isn't the same.

### Files Version

Version 2.1.24.0

### Windows Version

Version 21H1, Build 10.0.19043.1645, Windows Feature Experience Pack 120.2212.4170.0

**Comment by gave92** [comment]
Still waiting for MS to fix this but: https://github.com/microsoft/microsoft-ui-xaml/issues/3290 (1.5 years later)
