### ISSUE TITLE
Add support for dragging and dropping items into Favorites

### ISSUE THREAD

**Issue by the-garlic-os** [files-community/Files#9169]
### What's the Problem?

In native Explorer, you can drag and drop items and folders into the Favorites bar to pin that item to the Favorites. It would be nice to be able to do this in Files, too.

### Solution/Idea

Add the ability to drag and drop items and folders onto the Favorites bar to pin that item to Favorites.

### Alternatives

i dont know what im supposed to put here

### Files Version

Version 2.1.24.0

### Windows Version

Version 21H1, Build 10.0.19043.1645, Windows Feature Experience Pack 120.2212.4170.0

**Comment by gave92** [comment]
Thanks for the report. You can already add folders to the favorites section by dropping them on the section header.
