### ISSUE TITLE
"Double tap to rename files" function

### ISSUE THREAD

**Issue by XPoppyX** [files-community/Files#917]
Is it possible to delay the rename action when the file is clicked?

Because currently when you click on the name of a file in list view, it immediately changes to "rename mode", so the best solution would be to delay the rename action by 500 or more milliseconds

**Comment by guai** [comment]
remove this annoying thing entirely!
renaming is not so common thing we need that kind of shortcut. explicit button/hotkey/menu action is more than enough

**Comment by yaichenbaum** [comment]
This issue should be resolved with #2142.
