### ISSUE TITLE
Hide empty drive bays in the sidebar

### ISSUE THREAD

**Issue by the-garlic-os** [files-community/Files#9170]
### What's the Problem?

In Explorer, drives like disc drives and floppy drives are only shown in the sidebar when there is something in them. In Files, empty drive bays are still shown in the sidebar.

### Solution/Idea

When a drive bay is empty, Files should hide it from the sidebar (but it should still be visible on the Home screen).

### Alternatives

​

### Files Version

Version 2.1.24.0

### Windows Version

Version 21H1, Build 10.0.19043.1645, Windows Feature Experience Pack 120.2212.4170.0

**Comment by ferrariofilippo** [comment]
Can I work on this?

**Comment by yaichenbaum** [comment]
@the-garlic-os we made the decision not to auto hide empty drives but we're working on a way to see the drive size when hovering over the sidebar items. The goal of this change is to make it easier to see which drives are empty without having to open them.

**Comment by yair100** [comment]
This request is currently being tracked in #16426.

**Comment by yair100** [comment]
@nate-kean this feature will be included in the next release.
