### ISSUE TITLE
Working on Network Mapped Drives Results in Crashes

### ISSUE THREAD

**Issue by HotdogMassacre** [files-community/Files#9172]
### Description

Not really able to give you much of a repro since it happens no matter what you do on Network Mapped Drives. Randomly when doing pretty much anything it will crash the entire app. Can at least give you an output from EventVwr:

`Faulting application name: files.exe, version: 0.0.0.0, time stamp: 0x62167175
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.22000.675, time stamp: 0x16f23f36
Exception code: 0xc000027b
Fault offset: 0x0000000000834980
Faulting process id: 0x6bf8
Faulting application start time: 0x01d867eda4daf686
Faulting application path: C:\Program Files\WindowsApps\49306atecsolution.FilesUWP_2.1.15.0_x64__et10x9a9vyk8t\files.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: c16097b4-462e-4919-97fb-8e0145faef0f
Faulting package full name: 49306atecsolution.FilesUWP_2.1.15.0_x64__et10x9a9vyk8t
Faulting package-relative application ID: App`

### Steps To Reproduce

1. Have network mapped drive
2. Attempt to use it in pretty much any way, browse files, copy files, view files

### Expected behavior

Expected behavior is to function, sadly it does not.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.675

### Windows Version

Windows 11 Pro Version	21H2

### Relevant Assets/Logs

None sadly except the Error output i put in the above description.

**Comment by gave92** [comment]
Thanks for the report. Could you upload the app's debug logs? You can get them from Settings > About > Open log location (the two ".log" files).
Also you could check if updating to the preview version fixes the issue.

**Comment by HotdogMassacre** [comment]
To expand on this, i think it's related to the "File Tags" feature or maybe the Directory Size, i had a feeling and turned those off and it doesn't crash like that. and Yes I am happy to upload those, getting them now.

**Comment by HotdogMassacre** [comment]
Here you go.
[debug.log](https://github.com/files-community/Files/files/8694067/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8694068/debug_fulltrust.log)

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?
