### ISSUE TITLE
Dropdown menu issue with multiple monitors

### ISSUE THREAD

**Issue by yboumaiza7** [files-community/Files#9174]
### Description

The right click dropdown menu always shows on the first monitor only
I have two monitors, one on the left and one on the right as follows:
1st (main monitor): 1366x768
2nd: 1600x900

when I right click on a folder/file on the second screen, the dropdown menu appears on the first screen while being moved to the extreme right (trying to reach/align itself with the selected item)

### Steps To Reproduce

1. Put a Files window within the second screen
2. Select a folder/file
3. Right click on it
4. The dropdown menu appears on the first screen

### Expected behavior

The dropdown menu appears on top of the clicked item

### Files Version

Version: 2.1.24.0 OS Version: 10.0.19044.1706

### Windows Version

Windows 10 Pro 21H2 19044.1706 + Windows Feature Experience Pack 120.2212.3030.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8694490/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8694520/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
@lukeblevins is this something that will be resolved with the app window changes?

**Comment by lukeblevins** [comment]
@yair100 Not sure, but this sounds like an OS bug

**Comment by yboumaiza7** [comment]
> @lukeblevins is this something that will be resolved with the app window changes?

Not sure what u mean by that 😅 can you explain further?

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.3.0?
