### ISSUE TITLE
path accepts only \ and not /

### ISSUE THREAD

**Issue by yboumaiza7** [files-community/Files#9175]
### Description

When I use "/" instead of "\\" in the path input, the folder name shows differently on the tab header and the folder icon doesn't appear. But I can access the folder, which seams kind of odd.
Example:
> Path => C:\Users\User\Desktop\Path/To/Folder
> Tab title => Path/To/Folder (without icon)

I also tried to use drag & drop with winrar (from Files to Winrar) and it didn't work until I changed all '/' in the path to '\\'
I haven't tried to go to a path with '/' in the middle of it, just at the end of the path like shown in the example

### Steps To Reproduce

1. Open Files
2. Enter a path manually with both '\\' and '/'

### Expected behavior

- Tab title shows the folder name only with its icon
- Drag & drop works properly

### Files Version

Version: 2.1.24.0 OS Version: 10.0.19044.1706

### Windows Version

Windows 10 Pro 21H2 19044.1706 + Windows Feature Experience Pack 120.2212.3030.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8694517/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8694518/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #9229.
