### ISSUE TITLE
Opening a program with the path bar doesnt work anymore

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#9178]
### Description

I use to use the path bar to enter cmd or explorer.exe to open the folder location in that program but now it just says it not a path to a file or folder

### Expected behavior

It should open the program entered at the folder path currently typed in

### Files Version

2.2.5.0

### Windows Version

10.19043.1685

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8695152/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8695153/debug_fulltrust.log)

**Comment by gave92** [comment]
Could you try again after reopening the app? From the logs looks like a transient issue

**Comment by Josh-65** [comment]
Seems to work after killing all the process and reopening. but I have had it happen twice other times.

**Comment by gave92** [comment]
I'm closing this one for now, looks related to the fulltrust process having crashed after trying to go admin.
