### ISSUE TITLE
Files shows the wrong timestamps under heavy load

### ISSUE THREAD

**Issue by kevinj2016** [files-community/Files#9185]
### Description

Windows 11, Files v2.1.15.0

I use Files a lot for looking at the results of parallel builds (up to 64 threads) on 70 C# projects. Sometimes it gets confused and displays the wrong LastModified timestamp on files that are copied into the folder that it is looking at. It has cost me hours and hours of debugging time because I thought it was my MSBuild build/publish processes that were faulty or picking up (or not picking up and copying) the wrong or outdated files. 

Both performance speed and accuracy of information degrade over time until it becomes unusable. For a speed example, I can double click on a folder and nothing happens for three seconds (sometimes more) on a folder that has <500 files. It probably should be faster on my 32-core machine. 

As one accuracy example, it displays the wrong timestamps on half a dozen files in the folder as mentioned above. As a second example, it displayed a LastModified time in the past compared to the Created and LastAccessed times in the future, on a file that none of my processes touched (only MSBuild touched/created the file.) Rebooting it on the same folder shows the correct timestamps on the files after a reboot.  

I'm sorry to say that I don't know how to reproduce the issue because it happens to different files under different parallel builds and parallel file deletion/copying operations. But something is definitely wrong inside it. It is keeping old timestamps around in memory somewhere.

I also apologize that I don't have any good thoughts about potential reasons for the performance decrease over time. I just reboot it when it gets too slow on the display operations or double click operations.

### Expected behavior

Naturally, I expect Files to show the correct Modified time for all files that it displays.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.675

### Windows Version

Windows 11 Pro 21H2

### Relevant Assets/Logs

Showing a timestamp on a random file probably wouldn't help you. But the timestamp (Modified) changes after I reboot Files. And it is different compared to the timestamps shown by "dir myfile.dll" in a Command Window and different from the timestamp shown by other file manager apps.

**Comment by gave92** [comment]
Wondering if this bit of MS docs about FindFirstfileEx has anything to do with it:
> Note  In rare cases or on a heavily loaded system, file attribute information on NTFS file systems may not be current at the time this function is called. To be assured of getting the current NTFS file system file attributes, call the GetFileInformationByHandle function.

**Comment by gave92** [comment]
Could you post a screenshot showing the differences between Files and explorer for modified date?

**Comment by kevinj2016** [comment]
That's an interesting piece of doc about FindFirstFileEx. It uses the word attributes (Readonly, readwrite, etc.) and not the word timestamps; I wonder if they mean to include timestamps with that sentence. I thought of taking screenshots, but I could not imagine how they would help in any way. (I suppose they would be a small indication that my post is valid. :-) I will run a few more builds and get you some screenshots. Could you say a few words about how you would use them? Thank you.

**Comment by kevinj2016** [comment]
Hi Gave, I did in fact use the Files Properties (the little circle 'i' icon) to look at the properties of the affected files. That's how i finally figured out that Files was giving me incorrect info. I compared the Created, Modified, and Accessed times in the Files property window with the times displayed in Windows Explorer (actually, Qttab on my machine) and in the Everything program (a SUPERB piece of work by voidtools). I do appreciate your interest in investigating this issue. I thought about it a LOT because it strikes at the very soul of a file manager app. I thought, how would I debug it and find it? The best I could imagine was to add telemetry into the app to log the create/modify/access timestamps somewhere where you could look at them. Note that it is only the Modified date that goes wonky. The created and accessed dates are always consistent across apps. I spent many hours debugging this in my software, because I use the timestamps to replace old files with new files based on their timestamps. I kept thinking my duplicate-remover code was at fault because Files kept telling me that I was copying OLD files (where the new file was removed as a duplicate). But in fact I was removing duplicate old files and copying the new files correctly - it was just Files giving me an old "sticky" date from somewhere. 

IMHO, Files has an issue at the point where it is notified of changes in the filesystem and where it loads new file info into its internal data structures. For some reason the modified date is not being updated correctly. I don't know if you cache those objects for speed or if the timestamps are stored somewhere, but that's where I would start looking. If I reboot Files and force it to do a new read of the folder and files, all the timestamps show up as they should. I will push it again to generate another instance of the issue. Thank you again for your interest. If you want me to run an instrumented version of the app, just let me know.

**Comment by kevinj2016** [comment]
Here are some screenshots. 
Files 01.png - the bad timestamp after copying in a few hundred files as described above.
Files 02.png - the Files Properties dialog showing the bad Modified timestamp.
Files 03.png - the main display of the QtTab file manager showing the correct timestamp for the same file.
Files 04.png - the Windows Properties dialog for the same file, showing the correct timestamps.

![Files 01](https://user-images.githubusercontent.com/20227107/168670149-f4b3185e-00f6-441f-a031-3d831be313ec.png)

![Files 02](https://user-images.githubusercontent.com/20227107/168670175-6ca43014-41c4-489a-aecf-e53502e76a67.png)

![Files 03](https://user-images.githubusercontent.com/20227107/168670261-6ec1e2b3-7cfd-4031-9963-1865c40e7d07.png)

![FIles 04](https://user-images.githubusercontent.com/20227107/168670048-ff41967d-4603-484c-bd2f-e21368679168.png)

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by kevinj2016** [comment]
Hi, I don't know if it is still an issue - I stopped using Files because of it.

Did the devs make some convincing changes to address the issue?

**Comment by yaichenbaum** [comment]
We're constantly improving/fixing the app and it would help to know if this is fixed in the current preview build (there may be other issues but it helps set our priorities).

**Comment by kevinj2016** [comment]
I have no way of testing and reproducing results right now, so I cannot provide an answer.
The next good opportunity will be over the Christmas holidays when the build system will be started up again.
I will test it again then and report results to this thread.

**Comment by yaira2** [comment]
@kevinj2016
