### ISSUE TITLE
Dropping out second tab closes first window

### ISSUE THREAD

**Issue by mangoepic** [files-community/Files#9187]
### Description

https://user-images.githubusercontent.com/71931749/168577521-85d75ebf-d795-44af-8132-70fe68bd340b.mp4

### Steps To Reproduce

1. Make sure you have two tabs open
2. Drag and drop one of them out

### Expected behavior

First window stays open

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.675

### Windows Version

21H2 22000.675

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8699401/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8699403/debug.log)

**Comment by yaichenbaum** [comment]
This issue should be resolved in the preview version. https://files.community/download/preview
