### ISSUE TITLE
Add entries to show/hide sections in the section context menu

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#9190]
### What's the Problem?

The contextual menu of the sections of the sidebar only allows to hide the selected section. To add them, you must use the contextual menu of the sidebar outside of its elements.

### Solution/Idea

Replaces the "Hide section" entry in the popup menu with the list of available section toggles, possibly after a separator. This only applies to section titles, not their elements, or Home.

### Alternatives

None

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Comments

Before/After
![BeforeSection](https://user-images.githubusercontent.com/46631671/168626132-98b40a68-6034-4768-9c12-43ba64fad350.png)
![Sections](https://user-images.githubusercontent.com/46631671/168626150-8feb9d47-f215-4126-af60-3a0001376fa8.png)

**Comment by yaichenbaum** [comment]
@cinqmilleans this is the expected design since we don't want to overload the user with too many options. If the user wants to hide a section, it's the section they clicked on. They can access the other options by right clicking in an empty space or from the settings dialog.
