### ISSUE TITLE
Add support for pinning recycle bin to favorites

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#9191]
### What's the Problem?

It is possible to unpin the Recycle Bin from favorites from its contextual menu. To pin it, you have to use the settings.

### Solution/Idea

Add the option to pin Recycle Bin in the context menu of the Favorites section if the Recycle Bin is not pinned.

### Alternatives

Also show Unpin the Recycle Bin option when pinned in the favorite section menu.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
@cinqmilleans does it work to repin from recycle bin?

**Comment by cinqmilleans** [comment]
No, it's not in the page menu. You have to use the settings in the Sidebar section.

Also, you need to be able to open the Recycle Bin, and without a shortcut it's not easy because there's no parent or address to use.

![TrashMenu](https://user-images.githubusercontent.com/46631671/168632534-b20dc5ba-4d1e-4707-8a18-4665ced47597.png)
