### ISSUE TITLE
Cloud Drive files pane, status column cant be resized

### ISSUE THREAD

**Issue by Hefaistos68** [files-community/Files#9197]
### Description

When the files pane of a cloud drive is open, the additional "Status" column is shown. Initially this column is sized so that only "Sta..." appears in its title (at least with my display settings).
This column can not be resized, neither by mouse or keyboard. "Size columns to fit" does resize the column though.

As a workaround, one can do a "Size columns to fit" and then resize the other columns manually as seem fit.

Version: 2.2.9.0
OS Version: 10.0.19044.1706

### Expected behavior

Be able to resize the column as all others, and have it show up initially with its text all visible.

### Files Version

2.2.9.0

### Windows Version

10.0.19044.1706

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8701601/debug_fulltrust.log)

**Comment by gave92** [comment]
Alternative would be to remove the header text and leave the column non-resizable like the icon column. After all the content of that column is just an icon (fixed-width).

**Comment by Khit065** [comment]
khitl065

**Comment by WhiteGoldagency** [comment]
from:@babydogecoin @babydog account setting it between balance money all to whitegoldagency7@gmail.com it google cloud to auto complease finish find to @babydog account setting email to gmail account setting to twitter account setting to auto complease finish find to question security strong password auto complease finish find to security strong password fomus pin lockin only one by security update all to @babydog twitter account setting email phone number sim card for password all to need to creadits cards all to bank account all to mobile barking account setting all to bank account mobile phone number sim card for all complease change save to only me see with drive for any years for highway drive to @babydog account setting to update change save for today drive

**Comment by WhiteGoldagency** [comment]
from:@babydogecoin @babydog account setting it between balance money all to whitegoldagency7@gmail.com it google cloud to auto complease finish find to @babydog account setting email to gmail account setting to twitter account setting to auto complease finish find to question security strong password auto complease finish find to security strong password fomus pin lockin only one by security update all to @babydog twitter account setting email phone number sim card for password all to need to creadits cards all to bank account all to mobile barking account setting all to bank account mobile phone number sim card for all complease change save to only me see with drive for any years for highway drive to @babydog account setting to update change save for today drive

**Comment by RATHANAKPESETH** [comment]
Very good for me 😊

**Comment by RATHANAKPESETH** [comment]
Very good for me 😊

**Comment by Etheon88** [comment]
leave it as it is

**Comment by Asyiop** [comment]
تم

في الأحد، ١٩ يونيو ٢٠٢٢ ١:٠٦ ص Etheon88 ***@***.***> كتب:

**Comment by ferrariofilippo** [comment]
Duplicate #10432
