### ISSUE TITLE
Favorite Links Disappear

### ISSUE THREAD

**Issue by sguergachi** [files-community/Files#9198]
### Description

It seems if I add a link to a networked path, it will be removed if that networked path is not available.

This is a problem because I favorite networked directories that are only accessible while I'm on VPN. So that directory is not always available, but when I do connect to VPN I expect to be able to use those Favorite links.

### Steps To Reproduce

1. Add link to networked directory in Favorites
2. Close Files
3. Disconnects from networked location
4. Open Files
5. Networked directories in Favorites disappear

### Expected behavior

The networked directories should still be in Favorites, but selecting them should show error connecting if not able to access the networked path.

### Files Version

Version: 2.1.15.0

### Windows Version

 OS Version: 10.0.19042.1645

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8701715/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8701716/debug.log)

**Comment by yaichenbaum** [comment]
@sguergachi this issue should be resolved in the preview version. http://files.community/download/preview
