### ISSUE TITLE
Ability to Reorder Sidebar Items

### ISSUE THREAD

**Issue by forrest-herman** [files-community/Files#9199]
### What's the Problem?

Currently I cannot reorder sidebar items, even my favourites

### Solution/Idea

Allow sidebar items to be dragged and sorted by the user.

### Alternatives

Add an edit mode to rearrange sidebar items or a preferences page in settings to do so.

### Priorities

| Capability | Priority |
| Sort Sidebar Items Manually | Could |

### Files Version

2.1.15.0

### Windows Version

Windows 10 Pro 20H2 19042.1706

**Comment by yaichenbaum** [comment]
@forrest-herman you can reorder favorites from the right click menu. We'd like to implement drag and drop but we're held back by a bug in the WinUI library https://github.com/microsoft/microsoft-ui-xaml/issues/3290.
![image](https://user-images.githubusercontent.com/39923744/168657749-2042dc64-942c-42b1-9775-06a92a2e5d52.png)
