### ISSUE TITLE
Files for Windows Explorer

### ISSUE THREAD

**Issue by Pepeelguason** [files-community/Files#9200]
### What's the Problem?

Hi! This isn´t really a problem, but I want to change files to Windows Explorer, is there any way to do it?
I am making this question because files is so smooth and clean, its better than Windows Explorer, and its amazing. If there is any way to do it, just let me know please.

### Solution/Idea

I don´t have any solutions, the programme is perfect.

### Alternatives

.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Versión: 2.1.15.0 OS Version: 10.0.22000.675

### Windows Version

Windows 11 21H2  22000.675

### Comments

Please... :

**Comment by yaichenbaum** [comment]
@Pepeelguason the preview version of Files has an option to replace File Explore. It doesn't replace the open/save dialogs, but it should handle the scenario you mentioned. https://files.community/download/preview
