### ISSUE TITLE
Theme customization

### ISSUE THREAD

**Issue by angeloupali** [files-community/Files#9203]
Hi
I would like to change the opacity of the highlighted section 2 from 1. I have tried with the custom themes, but it is not possible to differentiate the 2 zones, can I get some help from you?

thank you
Angelo.
![Immagine 2022-05-17 090328](https://user-images.githubusercontent.com/102119686/168749995-07be5134-ea68-48f2-8d77-a577d29c1113.png)

**Comment by angeloupali** [comment]
I was able to customize the theme, is it possible to better align these elements?
![Uploading Immagine 2022-05-18 090721.png…]()

**Comment by Josh-65** [comment]
You cant move elerment with theming

**Comment by angeloupali** [comment]
certainly not in the theme :) I wanted to know which file I had to go to modify to change the aspect ratio of the bar
