### ISSUE TITLE
The order of favorites is no longer saved.

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#9205]
### Description

The order of favorites is no longer saved between sessions (in main). Maybe it's because of one of the commits. I will investigate.

### Steps To Reproduce

1. Change the order of favorites.
2. Log out.
3. Login.
4. The order is the one before modification.

### Expected behavior

The order is the one after modification.

### Files Version

main #5a7eb0cb2c67e46a7419cd9e14133ac3ded80db4

### Windows Version

Windows 11

### Relevant Assets/Logs

None.

**Comment by yaichenbaum** [comment]
@cinqmilleans is this an issue before your recent commit?

**Comment by cinqmilleans** [comment]
The problem does not exist with the code from a few weeks ago. I'll look for the exact commit that's causing the problem.

**Comment by yaichenbaum** [comment]
> The problem does not exist with the code from a few weeks ago. I'll look for the exact commit that's causing the problem.

Can you see if it's an issue in the #9206?

**Comment by cinqmilleans** [comment]
It was not an app bug.
