### ISSUE TITLE
Custom Tab order in "Details View"

### ISSUE THREAD

**Issue by LordShakti** [files-community/Files#9208]
### What's the Problem?

..

### Solution/Idea

i want to drag and drop file size tab next to the filename tab and then date created and filetag etc. i have checked but there is no option to have a custom order

### Alternatives

..

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
Merging with #8385
