### ISSUE TITLE
File Operations not working in AppData

### ISSUE THREAD

**Issue by IL2C** [files-community/Files#9210]
### Description

I'm unable to create and paste files and folders in folders located in AppData. I've removed the hidden attribute from all items inside of it using File Explorer, but the issue still persists. I'm able to use File Explorer without the issue occurring.

![Demo](https://user-images.githubusercontent.com/101745538/169091101-3b4ad134-1e4c-471a-a5c6-a49cd36c7dce.gif)

### Steps To Reproduce

1. Go to the AppData folder.
2. Create or paste a file or folder.

### Expected behavior

The file operation should be successful.

### Files Version

Version: 2.2.50.0 OS Version: 10.0.25115.1000

### Windows Version

Edition	Windows 11 Pro Insider Preview Version	22H2 Installed on	‎15/‎05/‎2022 OS build	25115.1000 Experience	Windows Feature Experience Pack 1000.25115.1000.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8718089/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8718090/debug_fulltrust.log)

**Comment by Josh-65** [comment]
Have you tried closing files and end any files processes in task manager. then reopening.

**Comment by IL2C** [comment]
> Have you tried closing files and ending any files processes in task manager. then reopening.

Yes

**Comment by ferrazpedro** [comment]
I have this same problem. I can't create any file inside of appdata. I'm using Files 2.3.

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
@gave92 is this supposed to work or should this be a feature request?

**Comment by gave92** [comment]
Bah for some reason windows API reports "success" for file operations in AppData even if they do not succeed.

**Comment by yaichenbaum** [comment]
We may need to add the unvirtualized files capability, can you see if that works?

**Comment by yaichenbaum** [comment]
They indicated that they were open to this so I think it's worth a try.

**Comment by yinyue200** [comment]
Any new?

If Microsoft doesn't approve unvirtualizedResources, maybe we can try this:

```
    <virtualization:FileSystemWriteVirtualization>
      <virtualization:ExcludedDirectories>
        <virtualization:ExcludedDirectory>$(KnownFolder:LocalAppData)</virtualization:ExcludedDirectory>
        <virtualization:ExcludedDirectory>$(KnownFolder:LocalAppDataLow)</virtualization:ExcludedDirectory>
        <virtualization:ExcludedDirectory>$(KnownFolder:RoamingAppData)</virtualization:ExcludedDirectory>
      </virtualization:ExcludedDirectories>
    </virtualization:FileSystemWriteVirtualization>
```

NanaZip uses this approach.

**Comment by Josh-65** [comment]
Its working for me in 2.4.8.0

**Comment by yaira2** [comment]
@Josh-65 are you running as admin?

**Comment by Josh-65** [comment]
No. Folder that don't require it work.
