### ISSUE TITLE
Network Mapped Drive Does Not Refresh

### ISSUE THREAD

**Issue by kyledavis124** [files-community/Files#9213]
### Description

I Network Mapped my companies SMB File share in files, while connected over VPN, from my BYOD laptop.

I observed the following incorrect behavior;

    Item - A folder and file

- A new created item does not appear until refreshed.
- After renaming an item, the item does not refresh, and appears to have the original name. *The name changed, It's just not shown.*
- A deleted item still appears until refresh.
- A item that is copied and pasted has the same behavior as stated above.

A manual refresh solves all the issues above.

### Steps To Reproduce

1. Connect to a VPN.
1. Map a network drive over the VPN.
2. Create a .TXT file.
3. Observe, the file does not appear.
4. Manually Refresh.
5. Observe, the file appears.
6. Select the file.
7. Press F2 and rename the file.
8. Observe, the file has the original name.
9. Manually Refresh.
10. Observe, the file has is renamed.
11. Delete the file.
12. Observe, the file appears to still exist.
13. Manually Refresh.
14. Observe, the file disappears.

### Expected behavior

I expect files to refresh on its own.

### Files Version

Version: 2.1.15.0

### Windows Version

 OS Version: 10.0.22610.1

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8729764/debug.log)

**Comment by yaichenbaum** [comment]
This issue should be resolved in the preview version. https://files.community/download/preview
