### ISSUE TITLE
open with doesn't work

### ISSUE THREAD

**Issue by jason919** [files-community/Files#9215]
### Description

select any file, right click it, click the "open with", it doesn't do anything 

### Steps To Reproduce

select any file, right click it, click the "open with", it doesn't do anything 

### Expected behavior

expects to show option to select apps

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22621.1

### Windows Version

Windows 11 Home  22H2

### Relevant Assets/Logs

select any file, right click it, click the "open with", it doesn't do anything

**Comment by yaichenbaum** [comment]
@jason919 can you upload the log files?
