### ISSUE TITLE
Show the contents of a sidebar entry on hover

### ISSUE THREAD

**Issue by RagingLink** [files-community/Files#9217]
### Solution/Idea

I feel like having the entries show up on hover would make it easier to view what's inside each sidebar category. This could be a sidebar setting.
![image](https://user-images.githubusercontent.com/15198000/169524644-8c44f910-f5ab-4aa3-b192-3bdc9bd1e1e2.png)

### Alternatives

Clicking on the category to show the menu. Attempting to use keyboard shortcuts to transverse the sidebar (when collapsed). Only clicking really works but is not the best.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to accomplish faster sidebar navigating | Could |

### Windows Version

Windows 11 22H2 22621.1

**Comment by yaichenbaum** [comment]
Merging with #3201

**Comment by RagingLink** [comment]
Any additional info on `not planned`?

**Comment by yaichenbaum** [comment]
> Any additional info on `not planned`?

It's a duplicate of #3201, I'm not sure what GitHub added the `not planned` for but it doesn't mean anything

**Comment by RagingLink** [comment]
But that feature request doesn't really seem to be the same as mine. It seems like it's more about the expanding of the entire sidebar, as that's how edge works, and not about just the expanded menu (from my screenshot)

**Comment by yaichenbaum** [comment]
@RagingLink I think I have a better idea what you're looking for, this is a behavior that will have to come to the WinUI library before we implement it in Files. Can you open an issue on the WinUI repository and link it here?
