### ISSUE TITLE
Android phone icon is missing on homepage

### ISSUE THREAD

**Issue by gave92** [files-community/Files#9218]
### Description

Connecting a phone (maybe any removable drive) will add an entry under drives on homepage but the icon is blank.

### Steps To Reproduce

Connect a phone in MTP mode
Phone drive will appear on homepage
Icon for that drive will be missing

### Expected behavior

Load and display the drive's icon

### Files Version

Main

### Windows Version

Windows 10

### Relevant Assets/Logs

None

**Comment by GabrieleMessina** [comment]
Hi! I'm new to this project but I'd like to help. Can I try to fix this or someone else is working on it?

**Comment by gave92** [comment]
Sure, feeling free to work on it!
