### ISSUE TITLE
Something gone wrong

### ISSUE THREAD

**Issue by FranzRome** [files-community/Files#9219]
### Description

I was exploring webpages on my browser when suddenly a message from the app appearred saying something unexpected happened.

### Steps To Reproduce

Can't reproduce that

### Expected behavior

I expect this message wont appear anymore

### Files Version

Versione 2.1.15.0 OS Version: 10.0.19044.1706

### Windows Version

Windows 10 21H2  Build: 19044.1706  Windows Feature Experience Pack 120.2212.4170.0

### Relevant Assets/Logs

Can't provide them, the message vanished and i didn't had time to capture it

**Comment by gave92** [comment]
Thanks for the report. You can upload the debug logs. Open Files > Settings > About > Open log location and upload the two ".log" files here.

So did the app crash while it was in the background/not actively used?

**Comment by FranzRome** [comment]
Yes the App was in background, i was downloading something from my browser and it saved some files to the downoad folder

Here i upload the logs:
[debug_fulltrust.log](https://github.com/files-community/Files/files/8762450/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8762451/debug.log)

In addition I want to point out that the app is often slow in loading when opening a folder, it is not very responsive. Can anything be done to solve this problem?

**Comment by yboumaiza7** [comment]
Same thing for the responsiveness of the app .. it's slow at launch and when opening a folder within the window or going back to the previous one... (browsing folders)

**Comment by Josh-65** [comment]
Is this still an issue?

**Comment by yaichenbaum** [comment]
I'm pretty sure this is resolved in v2.3.
