### ISSUE TITLE
File History

### ISSUE THREAD

**Issue by 42Mockingjay** [files-community/Files#9220]
### What's the Problem?

Windows has a build in "File History" feature which allows users to backup or roll back to previous versions of files. The problem is the File History UI was probably last updated when it was released (Windows 8) and the UI looks very ugly.

![image](https://user-images.githubusercontent.com/70784752/169627964-1d7849df-d068-47fb-be5a-24066a28e00e.png)
![image](https://user-images.githubusercontent.com/70784752/169627983-6791a28c-71b4-463d-867a-e02b47e8241d.png)
![image](https://user-images.githubusercontent.com/70784752/169628012-ff2f3673-3228-4987-a0ee-a7e43c4393b5.png)

### Solution/Idea

An updated and modern File History UI in the Files app.

### Alternative solution

Make a custom version of File History which has the ability to backup files, and/or sync files to folders, and/or restore backed up files.

### Files Version

Latest

### Windows Version

Windows 11 Pro 21H2 22000.675

**Comment by yaichenbaum** [comment]
@42Mockingjay thank you for your feedback, we don't currently have plans to implement this in Files.
