### ISSUE TITLE
Taskbar progress bar jumps when copying many files

### ISSUE THREAD

**Issue by 42willow** [files-community/Files#9222]
### Description

The progress bar on the taskbar keeps moving back and forth every millisecond. 
![image](https://user-images.githubusercontent.com/70784752/169636138-1246e97d-130a-4f34-a533-5347a9347810.png)

### Steps To Reproduce

Sometimes when moving a file or performing another action with a lot of files with network attached storage the loading bar on the taskbar started moving back and forth extremely quickly.

### Expected behavior

The progress bar behaves normally.

### Files Version

Latest Stable

### Windows Version

Windows 11 Latest Stable

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8746986/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
@42Mockingjay is this still an issue in the preview version? https://files.community/download/preview

**Comment by yaichenbaum** [comment]
@42Mockingjay thanks for the update, feel free to reopen the issue if it happens again.
