### ISSUE TITLE
Overwriting the standard CornerRadius does not work completely

### ISSUE THREAD

**Issue by jp-weber** [files-community/Files#9225]
### Description

With a custom theme it is not possible to overwrite the CornerRadius completly.

```xaml
<ResourceDictionary
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
        <CornerRadius x:Key="OverlayCornerRadius">0</CornerRadius>
        <CornerRadius x:Key="ControlCornerRadius">0</CornerRadius>
</ResourceDictionary>
```

### Expected behavior

All controls should be affected, if the CornerRadius is changed (OverlayCornerRadius and ControlCornerRadius).

### Files Version

Version: 2.1.15.0 OS Version: 10.0.19044.1706

### Windows Version

Windows 10 21H2

### Relevant Assets/Logs

[Theme1.zip](https://github.com/files-community/Files/files/8747363/Theme1.zip)

**Comment by lukeblevins** [comment]
@jp-weber Which areas of the app do you notice ignore the specified corner radius?

**Comment by yaichenbaum** [comment]
@jp-weber the way WinUI is built, overriding the corner radius doesn't work for all controls. We recommend opening issues on the WinUI repository for them to track.
