### ISSUE TITLE
Impossible to reinstall or come back in MS Explorer Files manually

### ISSUE THREAD

**Issue by AsimoPaul** [files-community/Files#9233]
### Description

I can't reinstall the apps.
I can't come back in my MS Explorer Files.

I'm just block. Need Help.

### Expected behavior

To Fix

### Files Version

Not installed

### Windows Version

W10

### Relevant Assets/Logs

NA

**Comment by gave92** [comment]
Unclear. If you have issues opening Windows Explorer after setting Files as default, you can run this script (make sure to save it as a ".reg" file) to restore windows explorer: https://raw.githubusercontent.com/files-community/Files/main/src/Files.FullTrust/Assets/FilesOpenDialog/UnsetFilesAsDefault.reg
