### ISSUE TITLE
Can we use this app as a default file manager

### ISSUE THREAD

**Issue by furkanyalcinz** [files-community/Files#9237]
### What's the Problem?

Can we use this app as a default file manager

### Solution/Idea

Can we use this app as a default file manager

### Alternatives

Can we use this app as a default file manager

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by gave92** [comment]
Yes you can set Files as default from Settings > Experimental. The option is only available in the [sideload version](https://files.community/download/preview).
