### ISSUE TITLE
Crash when drag and drop tab

### ISSUE THREAD

**Issue by WirelessSwitcher** [files-community/Files#9240]
### Description

I tried to drag and drop a tab into another monitor and the program crashed.

### Steps To Reproduce

1. Open two tabs in the same monitor
2. Drag and drop one of the tabs into the second monitor.

### Expected behavior

To have two instances, one in each monitor.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.19044.1645

### Windows Version

Windows 10 21H2 OS Build 19044.1645

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8755003/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
