### ISSUE TITLE
Sugestion: OOBE (Out Of the Box Experience)

### ISSUE THREAD

**Issue by esibruti** [files-community/Files#9241]
### What's the Problem?

This feature request is not related to any issues.
This is a very good idea for new Files users to have the first time they open the program. We would also do this for when there are updates where it would show what has changed in general.

### Solution/Idea

Explaining in more detail, OOBE is for new users to have a presentation of Files on their first use, in which they would also have the possibility to customize Files with some options.

For new/existing users, they would also have the first experience for a new update, for example, in the 2.3 update, it could show the news in general and whoever wants to see the specific changes will be redirected to the blog or github (the choice).

### Alternatives

n/a

**Comment by yaichenbaum** [comment]
@esibruti when installing the app, is there anything that you think is confusing or needs to be specifically called out? It's hard to know because I'm very familiar with all the options but I do believe most of the app is self-explanatory even for non-technical users.

**Comment by Josh-65** [comment]
Setting as default, 7zip integration which could also include #10035, how the toolbar works (Most people properly would come from using the ribbon which showed all options regardless of what selected. Users may think the ones shown are the only ones) and maybe tags when finished since most probably haven't used MacOS

**Comment by yaichenbaum** [comment]
> Setting as default

This isn't officially recommended

> 7zip integration

This is an interesting feature but it's something they will automatically discover as they use the app.

> tags

Tags still need a lot of work, and we'll have to evaluate the ease of use but that's a potential candidate for a teaching tip with a link to the documentation. I wouldn't want to prompt the user on an unfamiliar feature before the get a chance to play with the ones they already know from other apps.
