### ISSUE TITLE
Embedded terminal shell tabs

### ISSUE THREAD

**Issue by JoeHGeoghegan** [files-community/Files#9243]
### Solution/Idea

It would be brilliant if we could have terminal shell tabs (with an option to open as a tab or as a separate window

### Alternatives

Always enabled function but select-able in right click menu

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Option to open terminal shells as a Files tab | Must |
| Right-click on the file location has option to open separate terminal when above option is selected | Should |

**Comment by yaichenbaum** [comment]
Thank you for your feedback, we don't have plans to implement this right now.
