### ISSUE TITLE
desktop folders dont open 

### ISSUE THREAD

**Issue by haamedofficial** [files-community/Files#9251]
### Description

when replace of windows explorer and click on desktop folder dont open in files app

### Expected behavior

when replace of windows explorer and click on desktop folder dont open in files app

### Files Version

Version: 2.1.24.0 OS Version: 10.0.22000.675

### Windows Version

windows 11 pro 21H2

### Relevant Assets/Logs

nothing

**Comment by yaichenbaum** [comment]
@haamedofficial You can try using the preview version (https://files.community/download/preview) but please keep in mind this option isn't support on any version of Files.
