### ISSUE TITLE
Tabs and Window improvements

### ISSUE THREAD

**Issue by verdaderoken** [files-community/Files#9253]
### What's the Problem?

I have a few ideas for the tabs and window-related experience.

1. **Spawn a new window to a specific location using the mouse release position**
When dragging out a tab from a window to create a separate window, the new window will spawn just below the previous window regardless of where you released the mouse.

> The image below shows how a new window spawns when dragged out:
![image](https://user-images.githubusercontent.com/88200096/170117656-3991a3d6-0f1a-4fb5-bb6a-f1835b746de7.png)
![image](https://user-images.githubusercontent.com/88200096/170118584-27bcd026-b9c8-4d21-8aee-98120d6d8fba.png)

2. **Tab merging/moving to and from another window**
As of v2.2.58.0, the tabs can't be dragged into another window for merging or re-arranging the tabs.
![image](https://user-images.githubusercontent.com/88200096/170119335-068b4cf3-2268-4a30-a417-681281a7be16.png)

### Solution/Idea

1. **Spawn a new window to a specific location using the mouse release position**
A new window's position after dragging out a tab should depend on the mouse release position, just like when you drag out a tab from a browser to any specific location on your screen.
This is for dragging. The context option "**_Move tab to new window_**" should not be affected.

2. **Tab merging/moving to and from another window**
If we can move tabs to a new window, we should also have an option to put and move the tabs back to any Files window. The same idea can be observed in several browsers.

### Alternatives

Both ideas are very similar to Google Chrome's tab and window behavior, I do not have an alternative for now.

### Files Version

Version: 2.2.58.0

### Windows Version

Windows 11 22H2 10.0.22621.1

**Comment by yaichenbaum** [comment]
> Spawn a new window to a specific location using the mouse release position

This is a known limitation with the WinUI tab control, and it doesn't look like there is any solution for now.

> Tab merging/moving to and from another window

This should already work however you need to drop it on top of the existing tabs, there is an open feature request for improving this feature to allow dropping it anywhere on the title bar.
