### ISSUE TITLE
Compact List view like Standard Windows File Explorer

### ISSUE THREAD

**Issue by Joeblacksilver** [files-community/Files#9257]
### What's the Problem?

I want to view the files in LIST view (same as standard Windows 11 files explorer)

The Tiles view in Files-App is a bit too chunky and big. I want to see things more compact and small.

### Solution/Idea

I want to view the files in LIST view (same as standard Windows 11 files explorer)

### Alternatives

![explorer_YM1yAErYkK](https://user-images.githubusercontent.com/65788515/170208873-4746b430-4824-4586-b942-25994034747d.png)

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.1.24.0 OS Version: 10.0.22000.675

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎15/‎03/‎2022 OS build	22000.675 Experience	Windows Feature Experience Pack 1000.22000.675.0

### Comments

I want to view the files in LIST view (same as standard Windows 11 files explorer)

The Tiles view in Files-App is a bit too chunky and big. I want to see things more compact and small.
![explorer_YM1yAErYkK](https://user-images.githubusercontent.com/65788515/170209158-d1f867cd-3f0f-43e2-906e-488d73e8b3ed.png)

**Comment by yaira2** [comment]
@Joeblacksilver thank you for your patience, I'm excited to share that a List View layout will be included in the next release.
