### ISSUE TITLE
文件粘贴问题反馈

### ISSUE THREAD

**Issue by AisinGioroKiIoi** [files-community/Files#9258]
### Description

文件粘贴后，需要按一下F5刷新才能显示。望解决。ᠪᠠᠨᡳᡥᠠ（巴尼哈/谢谢）

### Expected behavior

希望文件粘贴后能实时预览，不需要再刷新页面。望解决，ᠪᠠᠨᡳᡥᠠ（巴尼哈/谢谢）

### Files Version

版本： 2.1.15.0 OS Version: 10.0.25120.1010

### Windows Version

25120.1010

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8769117/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8769118/debug_fulltrust.log)

**Comment by gave92** [comment]
Where does this happen? In network folders/shares?

**Comment by AisinGioroKiIoi** [comment]
> 

您好，我将本地文件夹内的文件复制到其它文帝文件夹或者网络文件夹，都有该现象。需要手动刷新一下。

另外，刚刚我在使用mstsc远程的时候，我发现本地的文件，右键复制，到远端服务器上粘贴，没有反映。而Windows的文件资源管理器，可以将文件复制过去。

**Comment by AisinGioroKiIoi** [comment]
您好，我将本地文件夹内的文件复制到其它文帝文件夹或者网络文件夹，都有该现象。需要手动刷新一下。

另外，刚刚我在使用mstsc远程的时候，我发现本地的文件，右键复制，到远端服务器上粘贴，没有反映。而Windows的文件资源管理器，可以将文件复制过去。

**Comment by gave92** [comment]
Thanks, you can try the preview version where this issue should be fixed. You can get it from: https://files.community/download/preview.
