### ISSUE TITLE
Add a .exe file

### ISSUE THREAD

**Issue by wexz-ardent** [files-community/Files#9259]
### What's the Problem?

So you see, my computer's Microsoft Store is non-existent because whenever I try to open it, it won't open. I tried all the YouTube tutorials but none of them seem to work and I really want Files as I'm a windows power-user and Files would seem very useful!

### Solution/Idea

And what I'm thinking is that you guys make a .exe file version of Files for all the people who want Files but have the same problem with me and if you have a solution then it would be very appreciated! Thanks!

P.S: The .appinstaller files and the msixbundle files don't work (I tried them).

### Alternatives

nothing

### Files Version

2.1.24

### Windows Version

2004

**Comment by Josh-65** [comment]
This is not possible as the UWP platform exe is an appinstaller file.  They are planing to move to a win32 platform but propberly not for a while. Whats is the error given when trying to use them.

**Comment by vehosah** [comment]
> This is not possible as the UWP platform exe is an appinstaller file. They are planing to move to a win32 platform but propberly not for a while. Whats is the error given when trying to install form the app installer file.

For me it gives me a list of programs to open it, but none of them can open it?

**Comment by Josh-65** [comment]
It uses app installer witch is normaly built in with windows. you can try installing using powershell but i dont know the command for it.

**Comment by vehosah** [comment]
> It uses app installer witch is normaly built in with windows. you can try installing using powershell but i dont know the command for it.

Oh ok
