### ISSUE TITLE
測試版使用反饋

### ISSUE THREAD

**Issue by AisinGioroKiIoi** [files-community/Files#9261]
### Description

1、無論是否開啓刪除確認，均默認勾選了永久刪除，無法改動。
2、右鍵刪除文件，文件還在，重啓後小時。
3、將其設置爲默認應用后，瀏覽器下載文件后打開文件所在位置，不能顯示在最前端，需要去找文件夾。
4、將其設置爲默認應用后，瀏覽器下載文件后打開文件所在位置，光標已經定位在文件所在了，但是，不在當前頁面，需要滾動鼠標去尋找文件。

### Expected behavior

1、關於刪除，希望能像原生那樣，可以設置默認刪除放入回收站，不需要確認。
2、關於下載文件打開文件所在位置，希望像原生那樣，直接打開一個定位到文件所在位置的窗口。

### Files Version

版本： 2.2.62.0 OS Version: 10.0.25120.1010

### Windows Version

版本	Windows 11 專業工作站版 Insider Preview 版本	22H2 安裝於	‎2022/‎5/‎19 OS 組建	25120.1010 體驗	Windows Feature Experience Pack 1000.25120.1010.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8770817/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8770818/debug_fulltrust.log)

**Comment by Josh-65** [comment]
Plase open an issue for eatch feedback you have for easier tracking.
As for point 1 that enable if the file can only be permantly delete. like on external dervices, recycle bin and places were the recycle bin is disabled.
Point 2 were are you deleting local, network, external phone.
Point 3 
Point 4 is beeing tracked in #6186 and the other linked issues.
