### ISSUE TITLE
Cannot right click .cmd file and "Run as Administrator".

### ISSUE THREAD

**Issue by madscribbler** [files-community/Files#9267]
I think the app should be running as administrator, so it can launch other things as administrator.   This has always been what prevents me from moving to the app - I have scripts that take physical drives on and offline, and network drive mappings that are created and destroyed in my scripts requiring administrative access.  I cannot run them from Files.  I have to use a different tool (OneCommander) to have a dual-pane and the ability to execute things.

If you fixed this I would bring several computers over.

**Comment by gave92** [comment]
Merging with #6333. Will be included in Files v2.3.
