### ISSUE TITLE
测试版文件夹删除问题反馈

### ISSUE THREAD

**Issue by AisinGioroKiIoi** [files-community/Files#9269]
### Description

![image](https://user-images.githubusercontent.com/52952040/170369821-1c724803-d2e5-4685-9cf2-31fdedeba442.png)
![image](https://user-images.githubusercontent.com/52952040/170369848-74285b3c-4507-403d-8904-773d6483167d.png)
如图所示，开启了删除确认，但删除界面是默认【永久删除】，无法修改。望解决，ᠪᠠᠨᡳᡥᠠ（巴尼哈/谢谢）

### Expected behavior

希望能像原生那樣，可以增加一个設置选项，默認刪除放入回收站，而不是永久删除，也不需要確認。

### Files Version

版本： 2.2.62.0 OS Version: 10.0.25120.1010

### Windows Version

版本	Windows 11 專業工作站版 Insider Preview 版本	22H2 安裝於	‎2022/‎5/‎19 OS 組建	25120.1010 體驗	Windows Feature Experience Pack 1000.25120.1010.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8774629/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8774630/debug_fulltrust.log)

**Comment by Josh-65** [comment]
Were are you deleting from. As i said in your orginal issue permintion deletion is locked on when it carnt be moved to the recycle bin. External devices, Netowrk location, recycle bin itself and any drive you have the recycle bin disabled.

**Comment by AisinGioroKiIoi** [comment]
不好意思。只看到是自己的文件，忘记自己还有个NAS了。确实是网络位置的文件，原生应用也是直接删除的。给您添麻烦了。

**Comment by Josh-65** [comment]
It the same in File explorer. and is a windows limitation with the delete function. Thats why the promt is there.
