### ISSUE TITLE
Files creating empty zip files unprompted

### ISSUE THREAD

**Issue by octopushugger** [files-community/Files#9271]
### Description

I have a bunch of torrents from a private tracker with the names: 

{EHT PERSONALIZED TORRENT - DO NOT REDISTRIBUTE} [x] x [x].zip.torrent

Replace x with the actual name/info of the individual torrent. 

Files(the program) creates an empty zip file with the same name as the torrent minus the .torrent for every one of these torrents that is VIEWED in the program. Just viewed. Imagine my surprise when I open my downloads folder and a bunch of zip files start spawning. 

### Expected behavior

Expected behavior is that it doesn't do this. 

### Files Version

Version: 2.1.24.0 OS Version: 10.0.22000.493

### Windows Version

Windows 11 21H2 22000.493

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8775161/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8775162/debug.log)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #9273
