### ISSUE TITLE
预览版文件拖拽问题反馈

### ISSUE THREAD

**Issue by AisinGioroKiIoi** [files-community/Files#9272]
### Description

将文件拖拽至钉钉等即时通讯工具时，无法拖入，需要通过键盘Ctrl+C/V来实现。望解决，以实现便利性。ᠪᠠᠨᡳᡥᠠ（巴尼哈/谢谢）

### Expected behavior

直接能将文件夹内的文件，拖拽至即时通讯工具的聊天窗口内。

### Files Version

版本： 2.2.63.0 OS Version: 10.0.25126.1000

### Windows Version

版本	Windows 11 專業工作站版 Insider Preview 版本	22H2 安裝於	‎2022-‎05-‎26 OS 組建	25126.1000 體驗	Windows Feature Experience Pack 1000.25126.1000.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8776597/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8776598/debug_fulltrust.log)

**Comment by AisinGioroKiIoi** [comment]
您好，收到您的回复消息右键后，我试了一下。原生文件夹中的文件，确实可以直接拖到钉钉上。咱的应用上的文件拖到钉钉的输入区的时候，有显示【复制】二字，但拖不进去。

**Comment by yaichenbaum** [comment]
Is Dingtalk UWP?

**Comment by hez2010** [comment]
> Is Dingtalk UWP?

It isn't.

**Comment by AisinGioroKiIoi** [comment]
> 釘釘是UWP嗎？

钉钉是EXE安装包。
下载链接：https://page.dingtalk.com/wow/z/dingtalk/default/dddownload-index?from=zebra:offline

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
It's possible that DingTalk is using a different API set, hopefully this gets fixed with WinAppSDK.
