### ISSUE TITLE
can not open app package

### ISSUE THREAD

**Issue by saeedNW** [files-community/Files#9274]
### Description

starting today whenever that I try to open the app it says "Cannot open app package", and as reason it says "Failed due to unknown reason".

my app version was 2.2.26 (preview version), so I thought maybe due to checks for updates at the app startup, something might have happened. So after uninstalling the app and downloading and installing the latest version of the preview package (2.2.63), the first launch after installation was ok but after closing the app and trying again the same error window shows up.

### Steps To Reproduce

1. opening the application

### Expected behavior

Opening application without any problems

### Files Version

2.2.26 and 2.2.63

### Windows Version

Windows 11 21H2 22000.675

### Relevant Assets/Logs

![Screenshot 2022-05-26 113217](https://user-images.githubusercontent.com/91555175/170435794-f7457c0c-ae82-4bab-9433-cc8b8a6b64e0.png)

**Comment by Josh-65** [comment]
This seems to be an appinstaller issue and files carnt do anything about that. Try run these in an admin cmd then restart when there finished
sfc /scannow
dism /online /cleanup-image /restorehealth

**Comment by saeedNW** [comment]
@Josh-65 
Hi.
thanks for response, I tried those as you said, but nothing's changed. do you have any other suggestions that might help me fix this problem?

**Comment by rudolphos** [comment]
I am getting a different Reason: "Error in parsing the app package."
![image](https://user-images.githubusercontent.com/4366810/210627495-7a978246-29d4-4530-907d-06069cbe7157.png)
![image](https://user-images.githubusercontent.com/4366810/210627522-9b35a376-f7bd-48f2-b650-370d376fc2c4.png)

What happened to more specific error messages? I remember they were very specific not that long ago..

**Comment by rudolphos** [comment]
This worked. Thanks.
![image](https://user-images.githubusercontent.com/4366810/210628876-359aa8e7-d5e1-400d-84f4-e22c4c2034e8.png)
