### ISSUE TITLE
File name sharpness lost if there are some specific characters in the name

### ISSUE THREAD

**Issue by KeremArdicli** [files-community/Files#9275]
### Description

Lets say we have two files, one named "Yapici", and the other one named "Yapıcı". The sharpness of the fonts are lost for the file named "Yapıcı" since it consist the letter "ı" (lower case I in Turkish). 

### Steps To Reproduce

1. Create a file named "Yapici"
2. Create a file named "Yapıcı"
3. You will see the difference.

### Expected behavior

Sharpness shoudl be ther for all character/encoding types.

### Files Version

Sürüm: 2.1.15.0 OS Version: 10.0.19043.1706

### Windows Version

Windows 10 21H1 19043.1706

### Relevant Assets/Logs

![file_name_sharpnesspng](https://user-images.githubusercontent.com/72523365/170460190-f9e4db8b-9773-48cc-8a1a-11953102afde.png)

**Comment by Josh-65** [comment]
This is a windows issue and i dont think its present on Windows 11. Files carnt do anything about this.

**Comment by KeremArdicli** [comment]
I just realized that sharpness is gone when i click on the file. 
Maybe removing the animation on click may help.
TBH, tihs click animation is not so helpful.
