### ISSUE TITLE
File not showing up after renaming from conflict dialog (via drag & drop)

### ISSUE THREAD

**Issue by verdaderoken** [files-community/Files#9277]
### Description

When dragging an image from Google Images to a folder, assume that the filename is already existing (in my case: **_"maxresdefault.png"_**), the conflict dialog will appear and will ask me to rename that file or do something else.
![image](https://user-images.githubusercontent.com/88200096/170522515-d3073c72-0760-48e6-9de6-bed59fed6d24.png)

However, when I choose and confirm the **Generate new name** option, the file I dragged does not appear in the folder.
![image](https://user-images.githubusercontent.com/88200096/170525591-d1288698-bc4c-401c-82c9-20c6945e5649.png)

### Steps To Reproduce

1. Search any image from your browser
2. Drag that image to a folder
3. Drag the same image again from your browser to the folder (make sure to have both files share the same filename)
4. Conflict dialog should appear as expected
5. Choose **"Generate new name"** option and decide a new name for it.
6. Click **Continue** to confirm changes
7. Check if the 2nd image with a different name appears, and if it doesn't, that's the problem.

### Expected behavior

The renamed file should appear inside the folder along with the conflicting file.

### Files Version

2.3.0.0

### Windows Version

Windows 11 22H2 10.0.22621.1

### Relevant Assets/Logs

> The **_"asdfasdf.jpg"_** should be here.
![image](https://user-images.githubusercontent.com/88200096/170523451-96262fb2-341c-4cfb-a3ed-60255a261b15.png)

_Note that this only happens when you drag an image from browser to the Files app._

**Comment by yaichenbaum** [comment]
This issue should be resolved with #9397
