### ISSUE TITLE
Menu Add to Favorites

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#9278]
### What's the Problem?

When you want to add a folder to the favorites, the reflex is often to open the contextual menu of favorites. File Explorer allows to add the current folder by this method. This is not possible with Files.

### Solution/Idea

Add an add sub-menu in the context menu of the Favorites section. This menu allows you to add the active folder, a recent folder, or a list of specific folders (downloads, recyclebin, ...). Items are inactive if already present.

### Alternatives

- Add only entry to add active folder, instead of add submenu.
- Add a submenu to restore a deleted bookmark. Convenient if you delete the wrong folder. The Restore submenus would only be visible if favorites have been deleted during the current session.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Comments

Here is an idea of the result.
![AddFavorite](https://user-images.githubusercontent.com/46631671/170533750-d91a1581-ddb3-43c3-b624-109e8ecaf504.png)

**Comment by yaichenbaum** [comment]
This design doesn't really work with Files as the sidebar is meant to be independent from the content. We have plans to allow drag and drop to pin but we only need so many ways to pin an item 🙂

**Comment by BanCrash** [comment]
> This design doesn't really work with Files as the sidebar is meant to be independent from the content. We have plans to allow drag and drop to pin but we only need so many ways to pin an item 🙂

If you mean to drop a folder into favorites it was added on #6129

**Comment by yaichenbaum** [comment]
> If you mean to drop a folder into favorites it was added on #6129

Sort of, it would be nice to be able to drop the item in a specific location instead of it being added to the bottom of the list.
