### ISSUE TITLE
固定软件至开始屏幕

### ISSUE THREAD

**Issue by AisinGioroKiIoi** [files-community/Files#9279]
### What's the Problem?

希望能像原生应用中，将文件夹中的EXE软件固定到开始屏幕。望采纳，ᠪᠠᠨᡳᡥᠠ（巴尼哈/谢谢）

### Solution/Idea

-

### Alternatives

-

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by Josh-65** [comment]
Merging with #6888
