### ISSUE TITLE
[Details view] set width of columns for all folder 

### ISSUE THREAD

**Issue by dftf-stu** [files-community/Files#9281]
### SUGGESTION

When in DETAILS VIEW, the width of columns are not remembered.

I like a very-simple view for most folders, showing only file-name and file-size.

• In FILES, columns get auto-sized so each is of equal-width
• In FILE EXPLORER you can choose the exact-width you want, then go to File > "Change folder and search options" > View tab > and press the [Apply to Folders] button to remember the column-widths for all future folders set to the same content-type

The only way I can see to workaround this in FILES would be to turn-on the "Enable individual preferences for individual directories" setting, but this then means I'd have to adjust the width of the size column for _every single folder_ I go into, which is not-ideal.

Could you perhaps make it in a future release so that whenever you change the width of columns with the "individual preferences" setting off that the most-recent change becomes the default for all folders?

Thanks

### SCREENSHOT

![FilesApp_ColumnSizes](https://user-images.githubusercontent.com/83965343/170685713-5d4a0fb8-c710-4037-b11e-5b1cf5dd4d09.png)

### VERSION INFORMATION

**Files app version:** 2.3.0.0
**Operating system:** Windows 10 Home Version 21H2 (OS Build 19044.1706) AMD64 kernel (non-ARM)

**Comment by yaichenbaum** [comment]
@dftf-stu you can get this behavior by turning off the option to use individual preferences. This will affect several other settings such as the layout mode and sort settings but we're working on creating separate options for each preference.
![image](https://user-images.githubusercontent.com/39923744/170706044-9e82d433-5e6e-44a7-8842-cce76d83ceff.png)

**Comment by dftf-stu** [comment]
@yair100: I did have "Enable individual preferences for individual directories" **already off**, as I explained -- I said that the only _workaround_ I could find to my issue is to turn that on.

Could you please explain to me further what is wrong for me then?  If I have the FILES app fully-closed and browse into a folder, the "Name" and "Size" columns are both the width you see in my original screenshot -- even when the app is maximised.

If I resize the columns (for-example, make the "Name" column wider) then the moment I browse into any-other folder, it reverts back to the previous size.  Closing FILES also doesn't save this; upon re-opening the app, the default-size returns.

Is the app supposed to remember the last width of a column or not, as for me that is not happening.  Is there any setting I should look at, or is something wrong with the install of FILES on my PC?

Thank you

**Comment by dftf-stu** [comment]
@yair100: maybe the screenshots below help show the issue I'm having?  As you can see, I browse into a folder, adjust the width of the columns, but the moment I browse to any-other folder, they revert-back to the sizes they were when the FILES app is launched.  How do I make the sizes I've chosen become the app-wide defaults?

![ABCD1234](https://user-images.githubusercontent.com/83965343/170982090-80916f78-7727-4764-b101-c24bda927caa.png)

**Comment by ferrazpedro** [comment]
@yair100 in my machine, the app has the exact same behavior that @dftf-stu is describing.

**Comment by yaichenbaum** [comment]
It appears that column sizes aren't yet included in this setting but it's something we're planning to work on.

**Comment by tnaseem** [comment]
Same here too. I'd love for this to be fixed. Otherwise, a great app!
