### ISSUE TITLE
Feature: Make compact mode even smaller

### ISSUE THREAD

**Issue by dftf-stu** [files-community/Files#9282]
### What's the Problem?

The setting "**Use compact styles in the details layout**" allows more rows of files to be visible, but not as-many as FILE EXPLORER

In my example screenshot you can see FILES on the left, and FILE EXPLORER on the right, both browsed-into the same folder:
• FILES can display 18 files fully (where the file-name is fully-visible)
• FILE EXPLORER can display 27 files

Therefore FILE EXPLORER can show an extra 9 files more than FILES in the same view mode

### Solution/Idea

Change the "**Use compact styles in the details layout**" setting from the current OFF/ON to a dropdown:

• Rename the setting to "Compactness of rows when in details layout"

• In the dropdown, offer (as examples) "Touch (wide)", "Touch (narrow)" and "Mouse (narrowest)".

"Touch (wide)" would be equivalent to the row-spacing when the current setting is OFF
"Touch (narrow)" would be equivalent to the row-spacing when the current setting is ON
"Mouse (narrowest)" would be a new row-spacing, which would aim to match FILE EXPLORER

### Requirements

• Make compact mode even smaller

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Consider adding an option to reduce the spacing between rows further for mouse-users, similar to _File Explorer_ | Should |

### Files Version

2.3.0.0

### Windows Version

Windows 10 Home 21H2 (OS Build 19044.1706) 64-bit, non-ARM

### Comments

Screenshot comparison, showing the narrowest row-spacing available in each app (FILES left; FILE EXPLORER right):

![FilesApp_DetailsRowSpacing](https://user-images.githubusercontent.com/83965343/170688954-3d19eff3-6e2c-4ed8-bf11-cdfe18232afb.png)

**Comment by javalosv** [comment]
Also consider change letter size to improve this mode

**Comment by CrypticVader** [comment]
IMO there should be three spacing options: 
1. Touch mode(the current default)
2. Comfortable(current compact mode)
3. Dense(similar to explorer)

**Comment by Midosa5** [comment]
I support this wish!

**Comment by SullyPanda76cl** [comment]
Totally needed feature... +1

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.
