### ISSUE TITLE
Right Click Options

### ISSUE THREAD

**Issue by Ch7ris** [files-community/Files#9283]
### What's the Problem?

The right click within Files does not include as many options as Windows File Explorer (Shift + F10 more options) 
The only option I need for my work flow is Dropbox link copy as I frequently need to paste the link to files in our production management software.
![image](https://user-images.githubusercontent.com/106383946/170693839-3b5f00a9-0ba3-4236-ba6f-0f4bca81dc92.png)

compared to 
![image](https://user-images.githubusercontent.com/106383946/170696018-afcc0631-66a7-4926-b3f4-d7aeb2cc956c.png)

### Solution/Idea

Please add a way to bring up the full right click menu or perhaps find a way to integrate dropbox with files app.

### Alternatives

Alternatively there could be an option in your Files App that when you right click on an item, the bottom option says "show file in File Explorer"

### Files Version

2.3.0.0

### Windows Version

Windows 11 21H2

### Comments

Thanks! I really like files. The layout and theme is way better, just need the same options in FE and its an obvious replacement to the default.

**Comment by yaichenbaum** [comment]
You might need to scroll down to see them. If you still don't see them, please open a bug report and include the logs so we can see what's going on.

**Comment by Ch7ris** [comment]
Yes thank you I just scrolled and it works :) Thanks
