### ISSUE TITLE
Improve copy performance on large number of small files

### ISSUE THREAD

**Issue by MathiasMagnus** [files-community/Files#9284]
### What's the Problem?

When copying a folder with lots of small files, for eg. CMake itself, which is 90 MBs "only" on disk but consists ~7k files. Did some benchmarking how moving this folder fares using different tools: (mm:ss)

- Files UWP 1:50
- Explorer 0:28
- PowerShell 0:15 (`Copy-Item .\CMake -Recursive .\Dest`)

### Solution/Idea

I don't really know how to solve this issue. I'm not a developer of Files, neither am I a C# dev.

(I'd have expected such a perf critical, "low-level" utility be written using C++/WinRT, but given how PS can take care of it almost 10x faster than Files I don't think it's a limitation of involving the .Net runtime.)

### Alternatives

¯\\_(ツ)_/¯

### Priorities

| Capability | Priority |
| :---------- | :------- |
| When shipping, it must be faster than the current implementation | Must |
| Ideally should be at least as fast Explorer who similarly has to render some UI while operating | Should |
| It'd be nice, but shouldn't necessarily be as fast as PowerShell | Could |
| Shouldn't hurt perf in other places | Won't |

### Files Version

Verzió: 2.3.0.0

### Windows Version

OS Version: 10.0.19043.1706

### Comments

Keep up the good work! 💛

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
File operations performance should be the same as File Explorer, we are working on additional improvements, but I think we can close this one.

**Comment by yaira2** [comment]
Merging with https://github.com/files-community/Files/issues/4180
