### ISSUE TITLE
Show properties window near mouse cursor position

### ISSUE THREAD

**Issue by verdaderoken** [files-community/Files#9285]
### What's the Problem?

In **File Explorer**, when you open the **Properties** of an item using <kbd>Alt</kbd>+<kbd>Enter</kbd> or from the context menu, the Properties window will show up at the bottom-right of the mouse except for when the mouse is near-edge of the screen, the window will adjust.

In **Files**, this is not possible as it will always show up to the last location of where you placed it.

### Solution/Idea

Make it show up near the mouse using its cursor position so users can expect where the window will show up.

### Alternatives

Show the Properties window on top of the current File instance like the image shown below.
Similar to a dialog window but not a modal window.

> The window here pops up in the center of the Files window
![image](https://user-images.githubusercontent.com/88200096/170704134-c2e7d802-d90d-491d-9594-556ddbccc360.png)

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Show the **Properties** window near mouse position | Should |

### Files Version

2.3.0.0

### Windows Version

Windows 11 22H2 22621.1

**Comment by yaichenbaum** [comment]
@ahmed605 I feel like this might be one for your 😂

**Comment by ahmed605** [comment]
> @ahmed605 I feel like this might be one for your 😂 

It's possible, but I don't have time to do it these days unfortunately
I will take a look once I have the time 👍

**Comment by yaichenbaum** [comment]
This issue should be resolved with #9391
