### ISSUE TITLE
Files app crashes

### ISSUE THREAD

**Issue by DikshitRJ** [files-community/Files#9287]
### Description

Whenever i open downloads folder, the files app crashes with the following error:
![image](https://user-images.githubusercontent.com/84832364/170850568-12de4c68-000c-45e8-9867-8fd8ba131998.png)

### Steps To Reproduce

1. Open downloads folder
2. Try to scroll
3. Sometimes it works, sometimes it crashes!!!

### Expected behavior

It must not crash and the downloads folder must open correctly.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.25126.1000

### Windows Version

Windows 11 22H2 25126

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8792583/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8792584/debug.log)

**Comment by yaichenbaum** [comment]
This issue should be resolved in the preview version. https://files.community/download/preview
