### ISSUE TITLE
Bug: Drive storage progress bar doesn't always load

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#9289]
### Description

![image](https://user-images.githubusercontent.com/26977075/170884425-a2f28f0e-7c0a-4b9a-b67d-6fcbd0a9d553.png)

### Steps To Reproduce

1. The issue doesn't always occur so keep restarting the app until the issue happens

### Requirements 
- The progress bar should always show

### Files Version

3.3.0.0

### Windows Version

10.19043.1685

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8793934/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8793935/debug_fulltrust.log)

**Comment by gave92** [comment]
Does refreshing help?

**Comment by Josh-65** [comment]
Nope i have to reopen Files

**Comment by yaichenbaum** [comment]
I can reproduce this issue on my device

**Comment by yaichenbaum** [comment]
Can you reproduce this in v2.3.48?

**Comment by Josh-65** [comment]
Haven't seen it happen for a while
