### ISSUE TITLE
Add automatic window version report in logs

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#9290]
### What's the Problem?

Currently with the auto update feature show the Files version in the logs. I believe adding the Windows build version there too would make it easyer for users as the questions on the github bug forums can be remove. This can also make it more consistent as users sometime do it in a wired way or dont give an actual build version.

### Solution/Idea

*

### Alternatives

*

**Comment by yaichenbaum** [comment]
@Josh-65 while having it in the log can be useful, the primary reason we ask users to add it to the description is so that we can tell right away which version the user is on and inform them if the issue was already resolved.
