### ISSUE TITLE
Use everything search instead of windows search for files.

### ISSUE THREAD

**Issue by ibay770** [files-community/Files#9292]
### What's the Problem?

Windows Search is very slow and Files slows down when it's used.

### Solution/Idea

[This](https://www.voidtools.com/forum/viewtopic.php?t=6969#p22492) forum explains it. Instead of integrating into Windows Explorer though, integrate it into Files.
[This](voidtools.com/) is what I'm referring too.

### Alternatives

Listary helps but I figured, why not integrate it if possible?

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
Merging with #6825
