### ISSUE TITLE
[2.3] Network drives don't auto refresh after changes

### ISSUE THREAD

**Issue by AisinGioroKiIoi** [files-community/Files#9294]
### Description

网络位置，新增文件夹，命名的时候，比如说命名为123456789，点了命名之后，文件夹内不显示，需要先按F5刷新一下。刷新之后出来的，也不一定是123456789，有可能是12345，后面的6789没有了，需要按F2再重命名一次。望解决，ᠪᠠᠨᡳᡥᠠ（巴尼哈/谢谢）

### Expected behavior

在网络位置新建文件夹命名后，直接显示文件夹，且文件夹名称完整。

### Files Version

版本： 2.3.0.0 OS Version: 10.0.25126.1000

### Windows Version

版本	Windows 11 專業工作站版 Insider Preview 版本	22H2 安裝於	‎2022-‎05-‎26 OS 組建	25126.1000 體驗	Windows Feature Experience Pack 1000.25126.1000.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8796115/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8796118/debug_fulltrust.log)

**Comment by Josh-65** [comment]
The refreshing issue is being tracked at #5869

**Comment by gave92** [comment]
Problem is, it's supposed to be fixed on 2.3.

**Comment by gave92** [comment]
@AisinGioroKiIoi could you please upload the app's debug logs? From Settings > About > Open log location

**Comment by AisinGioroKiIoi** [comment]
[debug.log](https://github.com/files-community/Files/files/8800800/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8800802/debug_fulltrust.log)
您好，我这个反馈单，其实是想反馈新建文件夹命名的时候，有时候会只出现一部分字符，比如我将一个文件夹命名为“20220531_测试”，刷新后它可能只显示“20220531_”，后面的“测试”二字不显示。

**Comment by yaichenbaum** [comment]
This issue should be resolved with #9297
