### ISSUE TITLE
Feature: Support for installing multiple fonts at the same time

### ISSUE THREAD

**Issue by verdaderoken** [files-community/Files#9295]
### Description

Whenever I try to install a single font or multiple fonts, the  **Install** option in right-click context menu doesn't work.
![image](https://user-images.githubusercontent.com/88200096/171044397-2ba39bea-eed6-417f-93a1-88e751719145.png)

### Steps To Reproduce

1. Select multiple font type files such as TTF & OTF
2. Right-click -> More -> Install
3. Only the first item in the selection will be installed in the system.

**"Install for all users"** doesn't work too

### Expected behavior

I should be able to install multiple fonts and this dialog should appear
![image](https://user-images.githubusercontent.com/88200096/171044469-b9a3370c-d7a6-49be-b786-f1b9eed9c552.png)

### Files Version

2.3.0.0 
Still broken in v2.3.61

### Windows Version

10.0.22621.1

### Relevant Assets/Logs

_N/A_

**Comment by Josh-65** [comment]
You will need to upload the logs files directly to github. You can get them in files settings > about > open log folder.

**Comment by gave92** [comment]
In my testing it works fine: the dialog does _not_ appear but the font _is_ added to `c:\windows\fonts`.

**Comment by verdaderoken** [comment]
A single font file works but when you try to select multiple files and choose 'Install', only the first highlighted font will be installed

**Comment by JediThumper** [comment]
I can confirm that this is still happening. 

[debug_fulltrust.log](https://github.com/files-community/Files/files/10081020/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/10081021/debug.log)
