### ISSUE TITLE
deleting files and folders permanently causes crash.

### ISSUE THREAD

**Issue by yilmazchef** [files-community/Files#9298]
### Description

when I tried to select multiple folders and click delete icon above it pops up a new window asking to delete them and there is a checkbox providing me an option to delete folders permanently. However when I click OK it crashes immediately.

### Expected behavior

![image](https://user-images.githubusercontent.com/36330777/171063948-cb0ce55c-1001-4fe7-a49a-47a0ac418e23.png)

### Files Version

Version: 2.3.0.0 OS Version: 10.0.22000.708

### Windows Version

Windows 11 Pro 64Bit 10.0.22000.708

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/36330777/171063841-f7fd336f-c133-4e45-be2e-45e093ebbeac.png)

**Comment by gave92** [comment]
Please upload the app's debug logs. From settings > about > open log location (2 ".log" files)
