### ISSUE TITLE
File bug out when browsing folder with too many subfolders

### ISSUE THREAD

**Issue by sumasage** [files-community/Files#9300]
### Description

Not sure how to describe the problem.  I recorded a video showing it.

https://youtu.be/xCp4jzIvabU

### Expected behavior

folders should open normally

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.675

### Windows Version

Windows 11 Pro 21H2

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8801276/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8801277/debug.log)

**Comment by gave92** [comment]
Merging with #9133
