### ISSUE TITLE
New Folder window not registering Chinese input

### ISSUE THREAD

**Issue by AlbertM94** [files-community/Files#9301]
### Description

This was an accidental discovery, but when I was trying to create a new folder using the Chinese input source (doesn't matter which, I tried Microsoft Pinyin or Sogou Pinyin), the Set Name button will keep greying out after I've typed the name no matter if it's Chinese or English characters. Haven't tried other languages, but so far it appears that the folder name window is not registering Chinese input results for some reason.

### Steps To Reproduce

1. create a folder (I used Ctrl+Shift+N)
2. select Folder option
3. switch to Chinese input source
4. type anything
5. the Set Name button is unclickable

### Expected behavior

Ability to click Set Name and create new folders

### Files Version

Version: 2.3.0.0 OS Version: 10.0.22000.675

### Windows Version

Windows 11 Pro Version	21H2 22000.675

### Relevant Assets/Logs

![Snipaste_2022-05-31_12-10-29](https://user-images.githubusercontent.com/48676341/171091565-28eede29-4ffc-478f-9213-a415a62b959f.png)
![Snipaste_2022-05-31_12-09-59](https://user-images.githubusercontent.com/48676341/171091546-638494b8-6a49-4778-903c-b19075e620b7.png)

**Comment by fty1777** [comment]
It seems a character must be inputted or deleted without any IME (i.e. a direct change to the input area is a must) to enable the "Set Name" button. Tried inputting multiple words totally inside IME (both Chinese and English) and the button would keep disabled, and deleting a character with Backspace brought the button back.

**Comment by merlinwilde** [comment]
![动画](https://user-images.githubusercontent.com/51823222/173425844-4d30957e-c107-40ae-8161-de0119398ea9.gif)
me too :(
