### ISSUE TITLE
Search on network drives does not work.

### ISSUE THREAD

**Issue by struzjos** [files-community/Files#9302]
### Description

Searching on network drive never finds any file although the file is there.

### Steps To Reproduce

1. Connect to any network drive (for example Samba)
2. Search in the search tab for any file

### Expected behavior

It should list the existing and matching files.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.19042.804

### Windows Version

Edition	Windows 10 Pro Version	20H2 Installed on	‎2021-‎02-‎17 OS build	19042.804 Experience	Windows Feature Experience Pack 120.2212.551.0

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/24386762/171158806-4678415d-8ce0-4fef-989d-d6049c5429ff.png)
![image](https://user-images.githubusercontent.com/24386762/171159021-60d8518b-20d1-4708-b6be-b5802a7142d2.png)

**Comment by gave92** [comment]
Does it work if you turn on "search unindexed items" option in Files settings?

**Comment by struzjos** [comment]
Yes it did help, thank you :)

**Comment by gave92** [comment]
Nice, still it should do this automatically

**Comment by Josh-65** [comment]
Is this still an issue?
