### ISSUE TITLE
Bug: Customization page doesn't have the correct path

### ISSUE THREAD

**Issue by Evgeen** [files-community/Files#9307]
### What's the Problem?

In properties window under Customize tab in the path to icon file, it doesn't use drive letter where my system is actually installed which in my case is S: but the path that is there by default is `C:\Windows\System32\SHELL32.dll` and it results for nothing to show there until I select correct path (`S:\Windows\System32\SHELL32.dll`)

![](https://i.imgur.com/N9ncdBh.jpeg)

### Solution/Idea

This window in regular explorer has path `%SystemRoot%\System32\shell32.DLL`, so an idea is basically having this path in this window in Files as well, which will result for icons to show up when you open that window without a need to select icon file in case if you have system installed not on C: drive.

### Alternatives

I don't think there can be any alternatives to it

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Make sure drive letter in path will match with actual system drive | Could |

### Files Version

Version: 2.3.0.0 OS Version: 10.0.19044.1739

### Windows Version

Windows 10 21H2 19044.1739

**Comment by Josh-65** [comment]
@yaichenbaum

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #9748
