### ISSUE TITLE
Files doesnt load anything restarting explorer.exe fixes it for a short while

### ISSUE THREAD

**Issue by giannisgx89** [files-community/Files#9308]
### Description

Im not sure this is because i enabled Files as my default file explorer but after doing that every folder (or my pc) im trying to open just doesnt load anything. The left sidebar doesnt seem to fully load either.

Looks like this: https://i.imgur.com/AJdP3k1.png

### Steps To Reproduce

1. Enable Files as default file manager from files settings page

### Expected behavior

Files should be able to open folders without hanging.

### Files Version

Version 2.3.0.0 Preview

### Windows Version

Windows 11 22H2 (OS Build 25126.1000) Dev Preview Channel

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8812060/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8812061/debug_fulltrust.log)

**Comment by Josh-65** [comment]
Have you tried turning the option off and opening files see if you get the same issue

**Comment by giannisgx89** [comment]
> Have you tried turning the option off and opening files see if you get the same issue

At the time of the issue turning the option Off didnt do anything. I didnt get the usual registry prompt dialog.

**Comment by Josh-65** [comment]
you might have to wait a bt as its slow to show

**Comment by giannisgx89** [comment]
I have waited for longer than usual.
Here i just recorded a video of the issue happening. The only fix was to restart explorer.exe but then it happens again.
https://drive.google.com/file/d/1v2zirrrfrgsSA5eOkF0nwGvpKYESBsoy/view?usp=sharing

**Comment by Josh-65** [comment]
Open this https://raw.githubusercontent.com/files-community/Files/main/src/Files.FullTrust/Assets/FilesOpenDialog/UnsetFilesAsDefault.reg > right click on the opened page > Save as > set the type to "all files" > remove the .txt from the end of the name > open the file > allow admin when you get the prompt.

**Comment by giannisgx89** [comment]
This works but the issue comes back again after i set files as default. I can disable the files as default file explorer after restarting explorer.exe too.

Im just sharing this cause it might be a bug. I would love to set files a default FE without this is issue.

**Comment by giannisgx89** [comment]
[debug_fulltrust.log](https://github.com/files-community/Files/files/8838077/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8838078/debug.log)

Here are the recent log files if you need them.

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
