### ISSUE TITLE
Need support drag with RIGHT mouse button

### ISSUE THREAD

**Issue by 7OH** [files-community/Files#9309]
### What's the Problem?

I cannot access to drop variants , which is usually shown, when drop files with right click.
![изображение](https://user-images.githubusercontent.com/3063507/171438939-8585536b-a893-4ad0-af5f-d130c0bd33cf.png)

### Solution/Idea

Make this feature as in usual explorer

### Alternatives

-

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by gave92** [comment]
Merging with #1396
