### ISSUE TITLE
Retain the search keywords when searching

### ISSUE THREAD

**Issue by verdaderoken** [files-community/Files#9311]
### What's the Problem?

In Explorer, when you search for an item, the keyword you typed will still be visible in the search bar.
In Files, the keyword I typed here will be erased as soon as I confirm the search
![image](https://user-images.githubusercontent.com/88200096/171509192-5ef46ab7-4708-4db1-8067-4d488d36e217.png)

### Solution/Idea

The keywords in the search shouldn't be erased after pressing Enter or clicking the Search icon.
This makes it easier for users to refine the search results similar to the current keyword.

### Alternatives

N/A

### Files Version

2.3.0.0

### Windows Version

10.0.22621.1

**Comment by yaichenbaum** [comment]
Merging with #8104
