### ISSUE TITLE
Regular crashes

### ISSUE THREAD

**Issue by schmittyd** [files-community/Files#9312]
### Description

I usually have about 4-6 tabs open with dual panes. Files randomly and reguarly crashes

### Steps To Reproduce

Some tabs will have one pane accessing a directory on Google Drive and the other pane a local version of the directory.

`G:\Shared Drives\directory`
`C:\tmp\directory`

Other tabs will have local comparison directories open in each pane

`C:\tmp\directory1`
`C:\tmp\directory2`

### Expected behavior

Not crash

### Files Version

Version: 2.1.15.0 OS Version: 10.0.22000.708

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎19/‎04/‎2022 OS build	22000.708 Experience	Windows Feature Experience Pack 1000.22000.708.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8822083/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8822084/debug_fulltrust.log)

**Comment by gave92** [comment]
Merging with #8759
