### ISSUE TITLE
Indexing For quicker loading of Network Drives

### ISSUE THREAD

**Issue by asinger321123** [files-community/Files#9315]
### What's the Problem?

This App is awesome and still love it. Found what might be my only flaw and a big one given 95% of my work is off large Mapped Network Drives. Accessing Folders and subdirs is terribly slow. Like 2 - 5 seconds per folder clicked. Going back and seaching for files is virtually unusable because it so far behind in trying to figure out how to load everything again.

Using this on the local C drive is absolutely amazing so hope something could be added to help somewhat with mapped network drives for performance.

### Solution/Idea

I don't now the code needed to make this happen but figured some sort of indexing could be added and updated occasionally. I use VOID Tools (Search Everything) which allows you add specific Folders, Mapped drives that will Index it daily at 3 AM so its updated to return search results instant. 

### Alternatives

VOID Tools Search Everything(Not a file explorer but has custom folder indexing option to return results faster when searching large Directories including mapped dirves

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by gave92** [comment]
Merging with #4180
