### ISSUE TITLE
Less jarring search bar refresh

### ISSUE THREAD

**Issue by i-have-testicular-cancer** [files-community/Files#9318]
### Solution/Idea

the search bar refeshing every time you type a character is kind off jarring

### Alternatives

I think something smoother would be better

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by gave92** [comment]
Could you post a screen recording showing this?
