### ISSUE TITLE
Service Host: State Repository Service

### ISSUE THREAD

**Issue by quantumwebco** [files-community/Files#9321]
### Description

I reported poor performance previously but the issue just got immediately closed with no consideration

I tried the 2.3 preview and it was better than 1.1.x but still quite slow

I have now updated to version 2.3 and it literally grinds my pc to a halt (Ryzen 9 5950x, 32GB DDR4, Samsung Evo Pro NVMe etc.)

Folders take 5 seconds or more to load and it is affecting other apps and overall performance

Looking in Task Manager, when Files is open, Service Host: State Repository Service is using between 80% and 100% of my processor

Closing Files everything is back to normal

There is a major bug affecting performance, it has been in the last couple of versions and has gotten worse

### Steps To Reproduce

Open files

### Expected behavior

For it not to use 100% of my processor

### Files Version

2.3

### Windows Version

Win 11 21H2 22000.708

### Relevant Assets/Logs

Too big

**Comment by Josh-65** [comment]
In your previous issue you never mentioned this you just said it was slow to open folders. Do you have "continue were you left off" enabled in Files settings > prefrances > startup (drop down box on the right)

**Comment by quantumwebco** [comment]
No it's not on. It's set to open new tab. I've tried fixing it in other ways like restarting the service. I think I'll just have to give up with Files. It's a nice idea but just unusable

**Comment by quantumwebco** [comment]
Uninstalled, cleared some caches, ran disk cleanup, restarted a couple of times, reinstalled and seems to be working better

It's still a little slow but as useable and the preview version was now

Now my only issue is sometimes it just loads blank pages, but only occasionally and a restart fixes it
