### ISSUE TITLE
Recent files on home shows 2 random files

### ISSUE THREAD

**Issue by quantumwebco** [files-community/Files#9322]
### Description

Open the app to the Home screen, in the recent files list there are 2 random files that I may (or may not) have accessed in the last week. It shows the same 2 files for maybe a week and then shows a different 2 random files

### Steps To Reproduce

Open the app
Go to the Home page
Look at recent files

### Expected behavior

Shows files that have recently been opened or edited

### Files Version

2.3

### Windows Version

Win 11 21H2 22000.708

### Relevant Assets/Logs

Too long

**Comment by Josh-65** [comment]
What are the too files that show. You will also need to upload the logs files directly to github. You can get them in files settings > about > open log folder.

**Comment by quantumwebco** [comment]
Just 2 random file
[debug_fulltrust.log](https://github.com/files-community/Files/files/8837536/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8837537/debug.log)
s

**Comment by quantumwebco** [comment]
Uninstalled, cleared some caches, ran disk cleanup, restarted a couple of times, reinstalled and seems to be working better
