### ISSUE TITLE
Files starting with a period (.) should be treated as hidden

### ISSUE THREAD

**Issue by JotaRata** [files-community/Files#9324]
### What's the Problem?

Nothing it's just annoying to see .filenames not hidden by default

### Solution/Idea

Files starting with period should be hidden when "Show hidden files" is disabled
Or there could be a new option to hide those specific files

### Alternatives

Hide those files by myself using properties

### Files Version

Versión: 2.3.0.0 

### Windows Version

Windows 11 Home Single Language Versión	21H2

**Comment by gave92** [comment]
There's already an option for that under settings > preferences > hidden files
