### ISSUE TITLE
Shortcut to skip the deletion modal

### ISSUE THREAD

**Issue by intergrav** [files-community/Files#9325]
### What's the Problem?

When deleting files, it gets a little tedious to have to right click, press the delete button, and then press confirm or delete then confirm. This is an issue I have always had with the windows explorer as well

### Solution/Idea

Maybe add some sort of shortcut that you can hold down while pressing the delete button that will skip that confirmation screen. Discord has this feature when deleting messages, where you can press shift while pressing the delete button to delete them quickly aswell.

### Alternatives

Maybe a checkbox when deleting that says "Don't ask me again until Files is closed" or something like that

### Files Version

2.3.0.0 Preview

### Windows Version

Windows 11 Pro 22H2 22621.1

**Comment by gave92** [comment]
There's an option in Files settings to hide the confirmation dialog.
