### ISSUE TITLE
Windows 10 Reveal effect is used on the settings contributors page

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#9328]
### Description

This isnt present on thrid party section so i dont think it should be on the contributors section

### Expected behavior

Just use the in app highlight

### Files Version

2.3.0.0

### Windows Version

10.19043.1685

### Relevant Assets/Logs

Not needed

**Comment by yaichenbaum** [comment]
@Josh-65 the two sections are using different controls, the effect isn't present on Windows 11 so we're going to leave this as is.
