### ISSUE TITLE
Feature: Display file in use message when moving a mounted .iso file

### ISSUE THREAD

**Issue by WebTiger89** [files-community/Files#9335]
### Description

I accidently tried to move an .iso file while it was mounted. Nothing happened, so I used the built-in explorer and it showed a dialog that the iso file is in use.

### Expected behavior

It would be great if Files does show a dialog too or any other response.

### Files Version

Version: 2.3.0.0 OS Version: 10.0.22000.675

### Windows Version

Windows 11 21H2 22000.675

### Relevant Assets/Logs

Hi

**Comment by hishitetsu** [comment]
@WebTiger89 thank you for reporting this issue.
Can you try the latest preview? https://files.community/download
I got an error message in my environment.
![image](https://github.com/files-community/Files/assets/66369541/0bc7112d-118e-49a4-8554-be09e41748b0)

**Comment by hishitetsu** [comment]
@yaira2 fyi
