### ISSUE TITLE
Setting Column View as Default

### ISSUE THREAD

**Issue by fxystc** [files-community/Files#9344]
### Solution/Idea

Column view is a long desired feature in Windows, it would be great it Column View can be set as default in Files, or more generally any view setting can be set as Default.

### Alternatives

Currently need to set Column View manually.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by gave92** [comment]
You can turn off "enable individual preferences for folders" option in settings > preferences > files and folders.

**Comment by fxystc** [comment]
Many thanks for the quick response!
