### ISSUE TITLE
Option to adjust font size

### ISSUE THREAD

**Issue by knuxyl** [files-community/Files#9347]
### What's the Problem?

[ FEATURE # 1 ]
The text is too big. I suggest adding a way to decrease the font size, then resizing the sidebar would make more sense. This feature is not required on Windows explorer because the font size isn't ridiculously huge to begin with, but it is with this file manager, thus a need to be able to resize it.

### Solution/Idea

[ Feature # 1 ]
Settings option to change font size for individual components, ie sidebar, directory listing, etc

### Alternatives

Continue using Windows explorer

### Priorities

| MUST |
All of these features are required for me to efficiently use a file manager.
Screen space is extremely important.

### Files Version

2.3.0.0

### Windows Version

Windows 11 Pro 21H2

**Comment by gave92** [comment]
Could you check if enabling "use compact style" option in Files settings > appearance is enough for your needs?

**Comment by knuxyl** [comment]
I did try that and while it was better, the items are still too big.

**Comment by jameslashmar** [comment]
I agree with the op, a compact view mode (not the compact overlay) would be great!

Here's a comparison vs explorer. 

This is including the setting suggested above by @gave92 . It is definitely better but could be pushed a little further IMO.

![image](https://user-images.githubusercontent.com/25590698/172660104-75ca36d4-a8e4-4ece-acd7-013d3b7130d8.png)

**Comment by yaichenbaum** [comment]
Thank you for your feedback, we're working on improvements in this area.
