### ISSUE TITLE
Feature: Add support for hiding the Toolbar

### ISSUE THREAD

**Issue by knuxyl** [files-community/Files#9348]
### What's the Problem?

[ FEATURE # 1 ]
I would like an option to hide the tool bar that has the New button. I will never use this because all of those features are available in either the context menu or hotkeys so the option to hide this would make more sense and give more screen space.

### Solution/Idea

[ Feature # 1 ]
Settings toggle to hide the directory toolbar that contains basic context menu entries such as New, Cut, and Paste

### Alternatives

Continue using Windows explorer

### Priorities

| MUST |
All of these features are required for me to efficiently use a file manager.
Screen space is extremely important.

### Files Version

2.3.0.0

### Windows Version

Windows 11 Pro 21H2

**Comment by yaichenbaum** [comment]
Merging with #9370

**Comment by yaira2** [comment]
It's been a while since this was requested, but I'd like to resume this discussion and see if we can incorporate this moving foward.

**Comment by 0x5bfa** [comment]
I think Inner Toolbar should not be automatically hidden in Home page because Copy and even Eject, Format RichCommands if we make in the future should be shown.
What do you think?

**Comment by yaira2** [comment]
I don't think this should be the default, agreed.

**Comment by knuxyl** [comment]
> @knuxyl I'm excited to share that support for hiding the toolbar will be included in the v3.5 release.

That is great to hear, thank you!
