### ISSUE TITLE
Option to turn animations off

### ISSUE THREAD

**Issue by pyrgasm** [files-community/Files#9350]
### What's the Problem?

Its anoying seeing the animations many again and again when working

### Solution/Idea

Option to turn off the slide down aniumations and all animations

### Alternatives

none

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.3

### Windows Version

Windows 10

### Comments

thats all

**Comment by gave92** [comment]
Mist animations are done by the system and we can't turn them off. Good news most of them have been removed in windows 11.
