### ISSUE TITLE
Lost transparency when out of focus

### ISSUE THREAD

**Issue by KhanhSonPham** [files-community/Files#9352]
### Description

The explorer lost its transparency whenever it's out of focus. Is it a feature or a bug?

### Expected behavior

After changing theme into glass. Left-click on desktop and it will turn black.

### Files Version

Version: 2.3.0.0 OS Version: 10.0.19044.1706

### Windows Version

Windows 10 Pro for Workstations 21H2 19044.1706

### Relevant Assets/Logs

None

**Comment by Josh-65** [comment]
This is a Windows limitation

**Comment by KhanhSonPham** [comment]
Will it happen with windows 11?

**Comment by Josh-65** [comment]
same thing Windows does it for performace and power saving
