### ISSUE TITLE
Cut files & double paste causes crash

### ISSUE THREAD

**Issue by yboumaiza7** [files-community/Files#9353]
### Description

I tried to move files from my own desktop and paste them in a folder
I pasted the files twice as described in the reproduction steps
and 2 progress notifications appeared on the top right of the Files app (found out while checking if the moving process has started or not)
the reason why I pasted the files twice because I always think that the moving/copying process didn't start

### Steps To Reproduce

1. Select some files in desktop
2. Cut files using (Ctrl+X)
3. Paste files using (Ctrl+V) then use the paste button on the Files top bar

### Expected behavior

The Files app ignores the second paste request & doesn't crash

### Files Version

Version: 2.1.24.0 OS Version: 10.0.19044.1706

### Windows Version

Windows 10 Pro 21H2 19044.1706 + Windows Feature Experience Pack 120.2212.3030.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8840545/debug.log)
[Uploading debug_fulltrust.log…]()

**Comment by gave92** [comment]
Should be fixed in Files V2.3
