### ISSUE TITLE
Increase pixel zone around resize column dividers

### ISSUE THREAD

**Issue by ketonik** [files-community/Files#9354]
### What's the Problem?

Pixel zone appears to be about 2 pixels wide for cursor hover over the dividing lines between columns in list view-in contrast to File Explorer the zone is larger.

On an 80cm 4k monitor it's tremendously difficult to convince the cursor to change to the expanding cursor to resize column width often takes over 10 seconds to get it perfectly positioned. This may not be as noticeable on a display with a low pixel pitch display 110 DPI vs 140 DPI for instance.

### Solution/Idea

Increase the pixel zone I don't know how many pixels, but triple the existing zone should be a nice place to test.

### Alternatives

The pixel zone between the sidebar and main list view area functions very well, this seems to be a wider zone, the divider actually increases in width by a factor of 3-5 times when the cursor hovers over it. Perhaps consider same approach for the column header dividers?

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.3.0.0 OS Version: 10.0.25131.1000

### Windows Version

Windows Feature Experience Pack 1000.25131.1000.0

**Comment by Josh-65** [comment]
Merging with #8722
