### ISSUE TITLE
cant unset files as default

### ISSUE THREAD

**Issue by CptVeg** [files-community/Files#9356]
### Description

set preview sideloaded version of files as my default file explorer and now when I try and un-toggle the option I don't get a regedit popup to undo the changes. If I close Files and reopen it the toggle switches back to being the default.

### Steps To Reproduce

not sure exactly what I did to break it

### Expected behavior

i expect to be able to set file explorer back as the default

### Files Version

Version: 2.2.1.0 OS Version: 10.0.22000.708

### Windows Version

Windows 11 21H2 22000.708

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8841892/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8841894/debug.log)

**Comment by gave92** [comment]
You can run this script (make sure to save it as a ".reg" file) to restore windows explorer: https://raw.githubusercontent.com/files-community/Files/main/src/Files.FullTrust/Assets/FilesOpenDialog/UnsetFilesAsDefault.reg

**Comment by AleMello** [comment]
Have same problem here. First time i installed Files, i change something in registry. I just wish to "unchange" this. Does this script does this? In fact, i wish i could do it using regedit, if it's possible.
