### ISSUE TITLE
Android Device connection for data transfer is buggy

### ISSUE THREAD

**Issue by KeremArdicli** [files-community/Files#9357]
### Description

When I connect my Android phone for data transfer, files app becomes responsive for a good time.

After it gets responsive but performance wise it is so slow.

I wanted to transfer my videos but app did not detext any video under DCIM folder. Detected only images.

### Steps To Reproduce

Connect Android phone for data transfer
Open Files App
Go to DCIM folder

### Expected behavior

Everything should work as expected and faster

### Files Version

2.3.0.0 (Preview)

### Windows Version

Windows 10 21H1 19043.1706

### Relevant Assets/Logs

![novideo](https://user-images.githubusercontent.com/72523365/172115876-f12ef8d8-85a6-44bc-8241-582391c95125.png)

**Comment by Josh65-2201** [comment]
@yair100

**Comment by yaichenbaum** [comment]
How large were the files?

**Comment by Josh-65** [comment]
Merging with #9003. I think making the 9003 issue a genral for slow performaces and failed oprations would be best.
