### ISSUE TITLE
拷贝文件出现严重问题

### ISSUE THREAD

**Issue by macfeng111** [files-community/Files#9358]
### Description

我在一台电脑上拷贝了文件夹到移动硬盘，拷贝完成后还检查了没问题。到公司电脑上打开后发现大部分文件没有，我还以为是我拷贝有问题，结果拿着移动硬盘回家后发现，东西是有的，这是为啥？这BUG严重了吧。而且该软件在使用过程中有时会出现错误的弹窗，很是不稳定。

### Expected behavior

？

### Files Version

版本: 2.3.0.0 OS Version: 10.0.22000.708

### Windows Version

Windows 11 专业工作站版 版本：21H2 操作系统版本：22000.708

### Relevant Assets/Logs

？

**Comment by Josh-65** [comment]
Did you use Files to view the files at your company computer. if not then this may be a limitation on your companys computers and is not an issue with files.

**Comment by macfeng111** [comment]
您好，我在公司的电脑上用files软件查看了移动硬盘上拷入的文件夹内容，奇怪的是只有根文件夹，里面也只有一个文件，其它很多文件都没有。而且我还用系统自带的文件管理查看了，也是没有。但我拿着硬盘回家再次用家里的电脑打开时又是有的。



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "files-community/Files"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月6日(星期一) 晚上7:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [files-community/Files] 拷贝文件出现严重问题 (Issue #9358)





 
Did you use Files to view the files at your company computer. if not then this may be a limitation on your companys computers and is not an issue with files.

**Comment by Josh-65** [comment]
Can you upload the logs files directly to github from both of the computer you used. You can get them in files settings > about > open log folder.
