### ISSUE TITLE
Display thumbnails for HEIC files

### ISSUE THREAD

**Issue by Dobatymo** [files-community/Files#9359]
### What's the Problem?

HEIC files only show a generic icon, no thumbnail.

### Solution/Idea

Support reading of HEIC files to create thumbnails.

### Alternatives

I cannot think of any alternatives

### Files Version

2.3.0.0

### Windows Version

Windows 10 20H2 19042.1526

**Comment by gave92** [comment]
Does windows explorer show previews for HEIC files?
What program do you have as default for opening HEIC files?

**Comment by Dobatymo** [comment]
Windows explorer does not show a preview. I don't have any software to open HEIC files.

**Comment by gave92** [comment]
Thanks for the info. Files pulls thumbnails from explorer, no thumbnails in explorer = no thumbnails in Files. You need to have something installed that is able to open HEIC files and generate the thumbnails. The preinstalled Photos app may do this, if not maybe XnView.

**Comment by Dobatymo** [comment]
So Files will only implement features which Explorer already provides?

**Comment by gave92** [comment]
No, point is there are already a lot of programs that add support for thumbnails for different file types (e.g SageThumbs, XnView) which work for both Explorer _and_ Files. I see no point in reinventing the wheel. Adding @yair100 in case he has different ideas.
