### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by taha2-4** [files-community/Files#9360]
### Description

Hello,

I tried to delete  (with Ctrl+right click to select) some files (3 folder, 3 zip .RAR) and after deleting the 3 .RAR it crashed saying a problem happend

(sorry for my english it is not my first language)

### Expected behavior

Delete de files without crashing

### Files Version

Version: 2.1.15.0 OS Version: 10.0.19044.1706

### Windows Version

Windows 10 Version 21H2 for x64 (KB5013887)

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8843269/debug.log)

**Comment by gave92** [comment]
Thanks for the report. Merging with #8763.
