### ISSUE TITLE
While deleting the temp and %temp% folders for clean up.....

### ISSUE THREAD

**Issue by sayef123** [files-community/Files#9361]
### What's the Problem?

The problem simple, but so far no solution from your side.

Like the builtin File Explorer, this file manager should also give following options while cleansing temp folder, and %temp% folder:

1) Continue, or
2) Skip, or 
3) Cancel. 
  
In your file manager, we have to click on "ok" button again and again, and don't know what would be happening nextg.

### Solution/Idea

Simply give the orginal File Explorer like feature....

### Alternatives

You think about alternatives.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Windows Version

Windows 10, Version 21H2 (OS Build 190441706)

### Comments

No farther comment.

**Comment by gave92** [comment]
Please add Files version to the description. This should be fixed in v2.3

**Comment by sayef123** [comment]
The present file version is 2.1.15.0

There is another problem with this file manager
      When the  open window is dragged to any side of the computer screen,
the dragging of the window becomes disabled.
       After lots of trying here and there (called tumbak-toyia in our
language!) the window can be maximised then resized as usual.

You may see to this if you like,

Thanks.

**Syed Sayef Hussain**
 Karachi
 Mobile: 0336-3335558, 0315-7158242
 www.facebook.com/syedsayef.hussain
 https://sayefhussain.wordpress.com/
