### ISSUE TITLE
Don't focus on the window when starting to drag and drop

### ISSUE THREAD

**Issue by adamburgess** [files-community/Files#9362]
### What's the Problem?

Windows Explorer has a neat feature: when you start a drag on a window, that window is _not_ focused. This allows you to navigate to a destination on another window, then easily drag from the old location to the new.

Here's a recording of Explorer:

https://user-images.githubusercontent.com/7473960/172183960-cf1e777c-c3f7-4167-870c-5b57cfcec1e0.mp4

Here's what it currently looks like in Files. The window underneath is focused, unlike Explorer.

https://user-images.githubusercontent.com/7473960/172184063-8dda2766-753a-4b9a-9c3f-679495cdda6f.mp4

### Solution/Idea

The window should not be focused for a drag operation. The receiver (where you drop it) is focused after you drop something there.

### Files Version

Version: 2.3.0.0 OS Version: 10.0.19043.1706

### Windows Version

Windows 10 Pro 21H1

**Comment by gave92** [comment]
Afraid we can't do that. May become possible once we switch to Winui3
