### ISSUE TITLE
Current Directory/WorkingDirectory is c:\windows\system32 when running an application as admin

### ISSUE THREAD

**Issue by EbenZhang** [files-community/Files#9365]
### Description

![image](https://user-images.githubusercontent.com/596334/172335096-ce6ac29f-3d82-42cb-bee0-280e75675182.png)

### Steps To Reproduce

- Right click an application for example process explorer (procexp.exe)
- View the working directory, notice it's c:\windows\system32

### Expected behavior

should be the same directory where the application resides in

### Files Version

Version: 2.3.0.0 OS Version: 10.0.22000.651

### Windows Version

Windows 11 Pro Version	21H2  Windows Feature Experience Pack 1000.22000.651.0

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8851608/debug_fulltrust.log)
debug.log is empty

**Comment by gave92** [comment]
Is it the same if you do it from explorer?

**Comment by EbenZhang** [comment]
when using explorer.exe and run as admin, the working directory the expected one which is the directory where executable resides in.

**Comment by Josh-65** [comment]
@yaichenbaum

**Comment by yaichenbaum** [comment]
@gave92 can you repro this?

**Comment by gave92** [comment]
Yes

**Comment by Josh-65** [comment]
Merging with #5648
