### ISSUE TITLE
无法创建文件夹

### ISSUE THREAD

**Issue by TianLuoQin** [files-community/Files#9367]
### Description

无法在files上创建文件夹。

### Steps To Reproduce

打开files
进入任意一个硬盘
右键选择新建文件夹
键入文件夹名称
“设置名称”一项是灰色的，无法点击，也无法使用enter键继续。
这个文件夹无法被创建

### Expected behavior

修复好它，能用一个简易的方式创建文件夹

### Files Version

2.3.0.0

### Windows Version

windows 11专业版 21H2 22000.675

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8854454/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8854455/debug_fulltrust.log)

**Comment by Josh-65** [comment]
Where are you trying to make the folder. local, network, FTP, connected phone?

**Comment by TianLuoQin** [comment]
local disk，D:/


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "files-community/Files"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月8日(星期三) 凌晨4:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [files-community/Files] 无法创建文件夹 (Issue #9367)





 
Where are you trying to make the folder. local, network, FTP, connected phone?

**Comment by TianLuoQin** [comment]
新发现！我在建立文件夹时，需要多打一个字，然后把那个字删除，就可以成功建立文件夹。但我觉得上述这种操作也是一个bug。

**Comment by fty1777** [comment]
Duplicate of #9301.
