### ISSUE TITLE
Make bluetoth transferst available

### ISSUE THREAD

**Issue by wonderNG** [files-community/Files#9369]
![bitmoji](https://sdk.bitmoji.com/render/panel/27794b2d-d749-4727-b49f-88a1106c3cda-bd19d016-1a88-4150-8e56-c3f268fdab0d-v1.png?transparent=1&palette=1&width=246)
Hey Files's Devs! Sup?
PS: I'm fine!
I use to transfert my file throught bluetoth from Win Explorer and I don't think windows will make it available in **Nearby Sharing** today or tommorow. Please, can you make it available ?
Also, make the file transfert track more efficient thanks you.

---------
I want to help you, I'm learning computer sciences and I love UI-UX design. If there's a way I can contruibute by giving some ui sketch, propositions tell me, **I'd like to help to improve Files**

**Comment by Josh-65** [comment]
Merging with #7789. 
If you would like to develop feature you can look at the backlog or to do section of the project https://github.com/files-community/Files/projects/1 and make apr when its ready. Theres also the discord for design concepts https://discord.gg/files
