### ISSUE TITLE
Expandable toolbar

### ISSUE THREAD

**Issue by giannisgx89** [files-community/Files#9370]
### What's the Problem?

Not sure if this is complex to implement but here are few suggestions that I think can improve the overall look and feel of Files.

### Solution/Idea

1. Expandable toolbar for those who never use the toolbar buttons.
2. Move left sidebar expand and collapse arrows to the left (This way they are not close to the main windows content and also auto hide).
3. Small toolbar info move inside the left sidebar.
4. Favorites merged with home on the left side panel
5. A bit wider searchbar
6. Improved padding for selected highlight area

![Files_Suggestions](https://user-images.githubusercontent.com/5347711/172604660-a8035aec-ea96-494a-86a3-297d340a09ff.gif)
![files_jpg](https://user-images.githubusercontent.com/5347711/172604666-4a773e9f-cebf-46c3-9b27-657636280f8c.jpg)
.

### Alternatives

Alternative is the current version of files.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version 2.3.0.0 Preview

### Windows Version

Windows 11 22H2 (OS Build 25126.1000) Dev Preview Channel

**Comment by Josh-65** [comment]
The arrows being on the right and the sector highlight is a WinUI standard so i don't think they can be easily changed and combing home and favorite doesn't make sense the home page will eventually have an option to remove.

**Comment by yaichenbaum** [comment]
> Favorites merged with home on the left side panel

We don't have plans to implement this as clicking on the section header is reserved for collapsing it

> A bit wider searchbar

We don't have plans to make the search bar wider since the general feedback is that it's wide enough, however, we do have plans to make the search flyout a little wider when needed.

**Comment by ponratm** [comment]
https://goo.gl/maps/BGS68wQbhtxjv1g68

**Comment by giannisgx89** [comment]
> 

I totally get it. I like using the app either way and thank you very much for keeping up to date with new features and bugfixes.

**Comment by cinqmilleans** [comment]
The button to close the toolbar can be useful but it should be open by default.
For the size of the search bar, maybe enlarge it when we use it. Here is a video, but it would need a smoother transition.

https://user-images.githubusercontent.com/46631671/173104037-970b7279-6931-4580-a58f-c96633654dfb.mp4

**Comment by giannisgx89** [comment]
> 

That was my idea as well. Having the toolbar expanded by default and having the option to collapse it if the user wants to.
Also the current toolbar placement doesn't look that great UX wise. Below you can see what i mean and how the version i suggested improves on that too.

Also about the search it can be there as a single icon and when users press on it it will expand like it looks now ready to type and search (also made a preview below)

I hope i am not too annoying with all these suggestions and again thank you very much for bringing this amazing piece of software to us, considering you are doing this for free!

![search](https://user-images.githubusercontent.com/5347711/173107469-8482d40a-6efb-410d-accb-8246a032a641.jpg)
![spacing](https://user-images.githubusercontent.com/5347711/173107475-2d43d362-c084-4f75-a180-22e2dea222f6.jpg)

**Comment by giannisgx89** [comment]
Another suggestion for the search icon can be similar to what ubuntu does.
Clicking on the icon uses the addressbar as a search field
![search ubuntu](https://user-images.githubusercontent.com/5347711/173113879-5c406cb5-94fc-4ccd-b0f3-ac8279418b8a.jpg)
.

**Comment by yaichenbaum** [comment]
We used to do that, but users liked having a dedicated search bar.

**Comment by snatvb** [comment]
@yair100 why don't you want to add this as an option? it takes up a lot of space

it exists even in compact mode...

**Comment by Josh-65** [comment]
1 file/folder slot really isnt a lot of space.

**Comment by yaichenbaum** [comment]
@snatvb most users seem to rely on the toolbar and wouldn't take advantage of this option.

**Comment by yaira2** [comment]
I'm bringing back the discussion for the toolbar in #9348.
