### ISSUE TITLE
Make Files tab design more consistent with Edge

### ISSUE THREAD

**Issue by trulko** [files-community/Files#9373]
Microsoft recently redesigned tabs in Edge to have a much more Windows 11-like, clean, floating look.

**Tab design in MS Edge has a modern, floating design, with lots of contrast to tell which tab is active:**
![image](https://user-images.githubusercontent.com/81886277/172758458-944b5a00-55a1-4913-8b16-321dd2e5884f.png)

**Tab design in Files has a more Google Chrome-like, non-floating design:**
![image](https://user-images.githubusercontent.com/81886277/172758019-417a4964-3078-4f3c-90a9-aaacbc5f9dc1.png)

For the sake of consistency, would you consider moving Files to a similar tab design?

**Comment by yaichenbaum** [comment]
After using the floating tab design for about 2 years, we started using connected tabs in v2.3 and we don't have plans to move back to floating tabs.
