### ISSUE TITLE
vs code issue

### ISSUE THREAD

**Issue by Manish-Rawat-1186** [files-community/Files#9376]
### Description

whenver i open vs code after some time i just got some error like, 
![image](https://user-images.githubusercontent.com/90690490/172854061-7efeeda8-efbc-454c-ab5e-3946e8930bc7.png)

### Steps To Reproduce

you can go to that image link check error view .
afterward you can proceed that according to you.

### Expected behavior

it might not show any error.

### Files Version

vs code 1.66.2

### Windows Version

windows 11 

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/90690490/172855162-b508de1f-09b6-48d5-ad78-b1415feba879.png)

**Comment by Josh-65** [comment]
This is not a files issue. Please report this to the VS team
