### ISSUE TITLE
More Features

### ISSUE THREAD

**Issue by michchan9527** [files-community/Files#9381]
### What's the Problem?

Now too few custom functions

### Solution/Idea

Can I have more customization options? For example, hide recently used files and switch on/off animations

### Alternatives

Can highlight for individual documents

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |
Could

### Files Version

2.3.0.0

### Windows Version

Windows 10 20H2 19042.1706

**Comment by yaichenbaum** [comment]
You can hide the recent files widget from the manage widgets flyout. Animations can be turned off from the Windows Settings app but we recommend keeping it on.
![image](https://user-images.githubusercontent.com/39923744/172919260-ed9becaa-201d-4f59-a892-bb3f67b3f7ab.png)
