### ISSUE TITLE
Preview PDF Documents from SharePoint Library

### ISSUE THREAD

**Issue by dontthroworanges** [files-community/Files#9382]
### What's the Problem?

I am working on transitioning my company from onsite SMB file storage to SharePoint Document Libraries. A huge potential pain point is that if the documents are not synced to the client, there is no preview available for the preview pane which we use ALL the time. This is my biggest issue I'm facing with this transition. 

### Solution/Idea

When accessing the SharePoint Document Library files from either Files App or File Explorer there is no way to preview the file before it's synced down to the client. However, when you are on the web view of the SharePoint document library there is a preview pane under the Information icon. I am wondering if it's possible to somehow hook into this to bring that preview down to the Files App. Maybe there is an API for this? I'm doubtful that there is an actual solution for this but I would love it if this could at least be looked at to see if it's at all possible. 

### Alternatives

No alternatives at this time. 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Windows Version

Windows 11 22H2

**Comment by Josh-65** [comment]
You said preview dont show in file explorer if thats the case then you need to install an preview handler on your computer. I dont think Files has the capabilities to act as one.

**Comment by dontthroworanges** [comment]
> You said preview dont show in file explorer if thats the case then you need to install an preview handler on your computer. I dont think Files has the capabilities to act as one. the web view version is custom made to allow it and doesnt have any connection to windows

Preview handlers are installed and are working for local files. I'm specifically referring to files that are stored in a SharePoint Document library in which the files are NOT physically present on the client. Therefore, there is no preview available.

**Comment by Josh-65** [comment]
Does it show them in File explorer? If not then i dont think anything can be done in Files as it uses the same system as File explorer.

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
I think we'd need to use the API so we won't be implementing this.

@dontthroworanges is there a way to set it up like OneDrive where it creates a copy of the file on the client device?

**Comment by dontthroworanges** [comment]
> I think we'd need to use the API so we won't be implementing this.
> 
> @dontthroworanges is there a way to set it up like OneDrive where it creates a copy of the file on the client device?

Thank you for reviewing this request. Yes the files can by synced via OneDrive desktop clients and appear as "On Demand" (no preview) until opened. So, storing a copy of all of our company data on each workstation just to get previews working would create all sorts of headaches. Anyway, I'll keep looking for a solution to this issue.

**Comment by yaichenbaum** [comment]
Ideally a dedicated client would help but it's a bit out of scope for Files as we'd have to add support for other cloud apis 😞
