### ISSUE TITLE
Keyboard shortcut ALT + Up arrow to move up one folder

### ISSUE THREAD

**Issue by redlegjed** [files-community/Files#9383]
### What's the Problem?

There seems to be no keyboard shortcut for going up one folder. On many file managers this is ALT + Up arrow.

### Solution/Idea

Add ALT+Up arrow shortcut for going up one folder.
Alternatively make keyboard shortcuts customisable and add folder up as an action.

### Alternatives

The only alternative I can see is to use the breadcrumbs bar at the top. But I would prefer to use the keyboard.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Add Folder up keyboard shortcut action | Must |
| Add keyboard shortcut ALT+Up arrow for folder up | Should |

**Comment by yaichenbaum** [comment]
Alt + up is supported in v2.3
