### ISSUE TITLE
Can't drag & drop web link to Files

### ISSUE THREAD

**Issue by rgtb** [files-community/Files#9385]
Hi,

When trying to save a link from a web page, while using drag and drop from the browser
address bar (I've tried Chrome, Edge and FireFox), I'm receiving the following error:

Copy failed: failed to copy 1 item.

This works well under MS Explorer.
Please fix this error.

Thanks in advance,
Ron.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #9388
