### ISSUE TITLE
No default element selected on element creation with shortcut

### ISSUE THREAD

**Issue by DAmNRelentless** [files-community/Files#9386]
### Description

In a previous version, it was possible to create a new folder/file with the key combination `CTRL` + `Shift` + `N`.
This still works and opens the pop-up window but you are no longer able to select the desired element with the arrow keys.

You now have to grab your mouse and select an element manually. I'd love to keep my mouse grabs at a minimum wherever possible and I don't understand why that's no longer a thing. I hope that's a bug and not intentional.
Pressing `Enter` will close the pop-up and cancel the action.

### Steps To Reproduce

1. open any directory
2. hit `CTRL` + `Shift` + `N`
3. see that nothing is selected by default and you can't select anything by using arrow keys

### Expected behavior

Using the arrow keys should switch through the elements that can be created.

### Files Version

2.3.0.0

### Windows Version

Windows 11 21H2 10.0.22000.708

### Relevant Assets/Logs

![](https://i.imgur.com/8AqF9fu.png)

**Comment by jasonpezzimenti** [comment]
I can work on this. But if you press the TAB key once, the first item is selected, and you can then use the arrow keys to move up and down the list.

**Comment by DAmNRelentless** [comment]
Very good to know, thank you!

**Comment by Josh-65** [comment]
Tab seem to be the way of doing it as that how it works in other dialogs.
