### ISSUE TITLE
Drag and drop into app window doesn't work.

### ISSUE THREAD

**Issue by sobear69** [files-community/Files#9389]
### Description

Drag and drop into app window doesn't work. Checked a couple of media players and office apps. When you try to drag and drop a file into the app window it either fails or doesn't do anything as Files is trying to copy/move the file.

### Expected behavior

Just like in normal explorer - drag and drop into an app window opens the file.

### Files Version

V2.3.0.0 

### Windows Version

21H2 22000.708

### Relevant Assets/Logs

N/a

**Comment by gave92** [comment]
Thanks for the report. Could you post a screen recording on this when dropping e.g a ".docx" file from Files to Office Word?

**Comment by sobear69** [comment]
Just restarted explorer and it works for office apps. I'm still having issues with MPC apps (both MPC-HC and MPC-BE). When dragging any file, be it video file or a text one, MPC throws "Encountered an improper argument" error and the file doesn't open.

**Comment by gave92** [comment]
Ah I'm afraid drag&drop to MPC is known not to work. Merging with #8652.
