### ISSUE TITLE
Feature: Select correct file when using "Open file location"

### ISSUE THREAD

**Issue by MalteTasler** [files-community/Files#9390]
**Reequipment**
- Right clicking on a recent item or shortcut and clicking on "Open file location" should select the file when the location is opened.
- The selected item should be scrolled into the view

### Files Version

2.3.0.0

**Comment by gave92** [comment]
Could you confirm whether the file is really not highlighted or the issue is "just" that the list does not scroll down to it?

**Comment by MalteTasler** [comment]
I have to correct myself, it does indeed get highlighted. It just does not scroll to that position. I apologize.

**Comment by MalteTasler** [comment]
should this be merged with https://github.com/files-community/Files/issues/6382 ? @yair100 @Josh-65

**Comment by yaira2** [comment]
@MalteTasler this feature is implemented in the dev branch and will be included in the next release.
