### ISSUE TITLE
Getting an appinstaller error when trying to install 2.3

### ISSUE THREAD

**Issue by Talisman39ar** [files-community/Files#9392]
### Description

I'm getting the following error when I try to install 2.3:

App installation failed with error message: The appinstaller uri https://cdn.files.community/files/preview/Files.Package.appinstaller is already being used by another package and cannot be applied to package FilesPreview_wvne1zexy08sa until the association is removed. (0x80004005)

Have tried restarting, and re-downloading, but same issue each time.

### Steps To Reproduce

1. Download Files Preview (2.3)
2. Double click to install
3. Hit the Install button
4. Get error

### Expected behavior

Installation completes

### Files Version

2.3

### Windows Version

Windows 11 22H2 22621.1

### Relevant Assets/Logs

x

**Comment by yaichenbaum** [comment]
This can be resolved by removing existing versions of Files before running the new installer.
