### ISSUE TITLE
Optimise-Reconfigure layout of files elements

### ISSUE THREAD

**Issue by ketonik** [files-community/Files#9393]
### What's the Problem?

Some difficulties with the placement of elements in Files, think can be improved. 
Example: some elements waste too much space, other elements not needed, some elements in bizarre locations, some additional elements to optimise use, some changes to existing elements.

1-Date column widths preferably not truncated the dates in List view. Ideally dates should expand/contract to system , short, medium & long formats se macOS Finder images:
1-Finder-List-Date-Expanded-Short.png
2-Finder-List-Date-Expanded-Medium.png
3-Finder-List-Date-Expanded-Long.png

2-Disclosure triangle icon elements to view contents of multiple folders inside current tab List view.
See attachment:
Finder-List-Markup-View-Contents-multiple-folders.png

3-Files Path field-so much wasted space, could be utilised to house folder icon controls and Nav arrow icons in same bar at top of window where the current Tab/Title bar is.
Attachment:
Finder-Command+Shift+G-Go.to.Directory-Markup.png
Shows how a Go to path overing box and be displayed with key command, and by adding path icons in the status bar.

4-Removing Tab-bar from Titlebar-this is a poor google inspired design philosophy. Place the Tab-Bar above and actual folder window pane width-between the right side of sidebar and the right edge of window, Tabbar should be specifically enclosed in this space, this is the focus this is relevant. Tabs outside here stuff up in the titlebar lacks cohesion.  
See attachment:
Files-List-Markup-Points-Markup.png
Yes a bit chaotic this markup screenshot, it's detailing and pointing out several elements that could be in better places.

Similar to previous point 3, Folder icon controls, Search field and Nav arrow icons, put in Titlebar. Then this gives user space to click and move the window from the Titlebar. User cannot move window if Tabs fully populate the Titlebar-Google you guys a dumb as sh!T!
Put tabs titlebar above the window pane-tabs are relevant to the window pane space width.
Make the Sidebar full vertical height, also shows reducing indent space, also giving users ability to position drives above or below favourites.

### Solution/Idea

Above does both, issue and resolution ideas

### Alternatives

see screenshots:
![1-Finder-List-Date-Expanded-Short](https://user-images.githubusercontent.com/49221849/173219791-8771442c-e78b-45dd-9385-ef1e2bd8c2d8.png)
![2-Finder-List-Date-Expanded-Medium](https://user-images.githubusercontent.com/49221849/173219793-3920d0ab-431b-48e2-ac86-5486ec4a5153.png)
![3-Finder-List-Date-Expanded-Long](https://user-images.githubusercontent.com/49221849/173219795-632dbb91-8d1d-45e8-a53a-89a03f40ba9a.png)
<img width="1276" alt="Finder-List-Markup-View-Contents-multiple-folders" src="https://user-images.githubusercontent.com/49221849/173219800-09ee8d6f-e04d-4399-81b2-067622a205c4.png">
![Finder-Command+Shift+G-Go to Directory-Markup](https://user-images.githubusercontent.com/49221849/173219850-2fedf88d-875d-46b9-b95f-3d997887196b.png)
![Files-List-Markup-Points-Markup](https://user-images.githubusercontent.com/49221849/173219898-b9dc7a67-caaa-45fb-ac8b-257c3f6aecc3.png)

### Priorities

| Capability | Priority |
| :---------- | :------- |

| This proposal will allow developers to accomplish Y | Could |

### Files Version

2.3

### Windows Version

Windows Feature Experience Pack 1000.25136.1000.0

**Comment by Josh-65** [comment]
First of all Files is not suppose to be MacOS finder whitch many of your suggestions are.

You can right click and select resize to fit for the date collum to show correctly.
Dates are set to follow the users preference and removing that for a force date based on size just doesnt make sence.

The tree view feature in details view is beeing discussed in #1928

Ctrl + L is how you get to the path bar in Windows and is how file explorer has always done it.

Tabs beeing in the titlebar is used by many thing other than Google chrome. They didnt make that a standard. MacOS simply just does it there own way. You can move it at the very top as theres a area for it and theres one on the right.

Reording of sidebar items is beeing discussed in #9351 but right now WinUI hasnt implement a way of doing so/is blocking the develpment of it on Files. The padding and position are WinUI styles to keep consistency and allows for better touch input.

**Comment by yaichenbaum** [comment]
Thank you for your feedback, it looks like @Josh-65 covered this pretty well but I want to add that it's best if you open and comment on individual issues
