### ISSUE TITLE
Can not search files in subfolder, why?

### ISSUE THREAD

**Issue by lin20121221** [files-community/Files#9394]
### What's the Problem?

as title.

### Solution/Idea

Let users can do this.

### Alternatives

None

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by gave92** [comment]
Please edit the issue to fill the required fields.
- Files version?
- Windows version?
- Where are you searching? Local disk? Network drive? Is the folder indexed in windows search? Is it hidden?
