### ISSUE TITLE
7 problems of wonderful Files

### ISSUE THREAD

**Issue by Midosa5** [files-community/Files#9395]
### Description

Files is a cool and stylish idea. It's more stylish than QTTaskbar - and it's better and more promising in terms of convenience than the regular one, but!

1. Slows down on win11 22H2 22610.1 when drawing file icons. Sometimes everything is not drawn.

2. It is bad that it is impossible, as with the regular explorer 11, to reduce the interval between folders vertically (3840 * 2160, scale 300%).

3. It's too bad that there is no undo/redo function (undo move, rename, delete, etc.) - why was it removed?

4. When working with the mouse with 1 click is configured, the possibility of cursor interaction has disappeared - for example, in a regular explorer, you can hover the cursor over a folder or file and, by tapping F2, rename the file or simply select it => in Files, you have to click the mouse (especially inconvenient when renaming or selecting several files with ctrl holding).

5. Column width adjustment does not work at all - it cannot be fixed, it constantly creeps away when the window is enlarged/decreased - even when returning to the previous window size, the column width is constantly reduced to a complete inconvenience. Often the possibility of adjustment disappears - it is impossible to pick up.

6. When moving files and folders - moving is not always correct => sometimes part is copied to a new location, and part remains in the old one.

Well, the little things:

7. On a dark acrylic theme, the "Properties" of files and folders do not work.

8. For some reason, the size of folders is recalculated every time - isn't it better to fix it somehow somewhere - and if there were no changes in the folder, then just take the previous size? Does it make sense to recalculate in the absence of changes? And they are visible in the properties of any folder. You can, of course, disable the output of the size of folders - but is it possible to fix it?

If these flaws were fixed... in general, practically, ideal.)))
Thanks!

### Steps To Reproduce

Files is a cool and stylish idea. It's more stylish than QTTaskbar - and it's better and more promising in terms of convenience than the regular one, but!

1. Slows down on win11 22H2 22610.1 when drawing file icons. Sometimes everything is not drawn.

2. It is bad that it is impossible, as with the regular explorer 11, to reduce the interval between folders vertically (3840 * 2160, scale 300%).

3. It's too bad that there is no undo/redo function (undo move, rename, delete, etc.) - why was it removed?

4. When working with the mouse with 1 click is configured, the possibility of cursor interaction has disappeared - for example, in a regular explorer, you can hover the cursor over a folder or file and, by tapping F2, rename the file or simply select it => in Files, you have to click the mouse (especially inconvenient when renaming or selecting several files with ctrl holding).

5. Column width adjustment does not work at all - it cannot be fixed, it constantly creeps away when the window is enlarged/decreased - even when returning to the previous window size, the column width is constantly reduced to a complete inconvenience. Often the possibility of adjustment disappears - it is impossible to pick up.

6. When moving files and folders - moving is not always correct => sometimes part is copied to a new location, and part remains in the old one.

Well, the little things:

7. On a dark acrylic theme, the "Properties" of files and folders do not work.

8. For some reason, the size of folders is recalculated every time - isn't it better to fix it somehow somewhere - and if there were no changes in the folder, then just take the previous size? Does it make sense to recalculate in the absence of changes? And they are visible in the properties of any folder. You can, of course, disable the output of the size of folders - but is it possible to fix it?

### Expected behavior

If these flaws were fixed... in general, practically, ideal.)))
Thanks!

### Files Version

2.1.24.0

### Windows Version

Windows 11 22H2 22610.1

### Relevant Assets/Logs

No logs)

**Comment by gave92** [comment]
Hi thanks for you interest in Files. Files v2.3 should fix most of the issues listed above (except for [4]). I'd invite you to give it a try and let us know how it goes. If you don't find the update on the Store you can get the latest version from https://files.community/download/stable.

**Comment by cinqmilleans** [comment]
@Midosa5 Thanks for your feedback. Here is the situation of point 8.

The old size is already displayed when it has already been calculated. However, there are several limitations. The size must have been fully calculated otherwise we start from scratch, and sometimes a small folder is missing but takes a long time to calculate because it contains many files. Another limitation is that the calculated sizes are not persisted between sessions. This was introduced because a disk may have changed letter, for example a USB key.

I have been working for several weeks on improving this feature to remove these 2 limits. This requires a lot of research and it will take me several more weeks.
