### ISSUE TITLE
Drag-and-drop copying of large files or folders causes the "Copy to <folder>" text to never disappear until the transfer is complete.

### ISSUE THREAD

**Issue by NorteX-dev** [files-community/Files#9398]
### Description

When drag-and-dropping large files/folders, the hover tooltip never disappears as shown below when transferring a game to the "Epic Games" folder:

![image](https://user-images.githubusercontent.com/32877032/173322002-d0ad97a3-9889-436f-a790-8b327c8d61ec.png)

This persists on other windows and is always on top. When the copying completes, the overlay disappears and all is fixed. The app is not frozen during that process though.

### Steps To Reproduce

1. Go to any target folder in the Files app
2. Drag and drop to copy a large folder or file
3. Release the mouse button to drop, and the overlay is stuck there

### Expected behavior

The overlay disappears before the copying process has begun.

### Files Version

Version: 2.3.0.0 OS Version: 10.0.22621.1

### Windows Version

Windows 11 Experimental Channel 22H2 compilation 22621.1

### Relevant Assets/Logs

N/A

**Comment by NorteX-dev** [comment]
Update: restarting the `explorer.exe` process fixed this.

**Comment by yaichenbaum** [comment]
@NorteX-dev thank you for your feedback, I'm going to close this for now but let us know if it happens again and we'll look into it further.

**Comment by NorteX-dev** [comment]
well ok then I won't submit more issues if you're so ignorant to close issues instantly

**Comment by yaichenbaum** [comment]
> Update: restarting the `explorer.exe` process fixed this.

You mentioned that restarting the process fixed this. We'd like to troubleshoot but it sounds like it's working as expected now.

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
Merging with #10171
