### ISSUE TITLE
Crashes on Settings menu

### ISSUE THREAD

**Issue by Rowan-Bird** [files-community/Files#9399]
### Description

Self explanatory

### Steps To Reproduce

1. Open App
2. Click the gear
3. Watch in horror as it crashes

### Expected behavior

Change the settings

### Files Version

The settings are broken, OS Build: 18363

### Windows Version

Windows 10 1909

### Relevant Assets/Logs

No logs

**Comment by yaichenbaum** [comment]
Thank you for your feedback. We need a little more information from you in order to investigate this issue, please reopen this issue once you have filled out the issue template.
