### ISSUE TITLE
context menu overlay

### ISSUE THREAD

**Issue by cleuton4k** [files-community/Files#9402]
### Description

when an icon is at the edge of the screen and when right clicking to open with, the submenu is brought up to the main menu. and sometimes the submenu did not disappear.

### Steps To Reproduce

when an icon is at the edge of the screen and when right clicking to open with, the submenu is brought up to the main menu. and sometimes the submenu did not disappear.

### Expected behavior

open submenu on the side

### Files Version

2.3

### Windows Version

w10 21h2 home

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8900621/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8900622/debug_fulltrust.log)
![01](https://user-images.githubusercontent.com/90144967/173602778-047f2582-a4df-418e-a3af-46e064b90bbe.jpg)
![02](https://user-images.githubusercontent.com/90144967/173602782-7cf26fd7-9fe9-4cb6-a29e-1024050e5dc6.jpg)
![03](https://user-images.githubusercontent.com/90144967/173602784-85d3c7d4-4d2d-4c1f-be79-c1ed01cb0ddc.jpg)

**Comment by gave92** [comment]
Do you have the "show overflow items in submenu" option enabled in settings > Appearance?

**Comment by cleuton4k** [comment]
yes it is similar to these two cases
https://github.com/files-community/Files/issues/7346
https://github.com/files-community/Files/issues/6922

**Comment by cleuton4k** [comment]
and the menus/panels become opaque

**Comment by Josh-65** [comment]
Merging with #6922
