### ISSUE TITLE
sorting files by type is wrong

### ISSUE THREAD

**Issue by cleuton4k** [files-community/Files#9403]
### Description

FILES should sort files by type the same as file explorer, putting folders first and then other file types.

### Steps To Reproduce

FILES should sort files by type the same as file explorer, putting folders first and then other file types.

### Expected behavior

FILES should sort files by type the same as file explorer, putting folders first and then other file types.

### Files Version

2.3

### Windows Version

w10 21h2 home

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8900774/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8900779/debug.log)

https://user-images.githubusercontent.com/90144967/173606563-634c7991-bbf4-477b-81c4-cee4e661e973.mp4

**Comment by gave92** [comment]
Thanks for the report. Please confirm that you have _not_ checked the "sort folders alongside files" option.

**Comment by cleuton4k** [comment]
sorry, the "sort folders alongside files" option was enabled, I disabled it and now it's working as expected.
