### ISSUE TITLE
多个文件无法同时重命名

### ISSUE THREAD

**Issue by AisinGioroKiIoi** [files-community/Files#9422]
### Description

选中两个文档，进行重命名时，需求是将两个文件重命名，实际上只有一个文档重命名了，另一个文档还是需要重新命名。望解决，ᠪᠠᠨᡳᡥᠠ（巴尼哈/谢谢）

### Expected behavior

能够对选中的所有文档同时重命名。

### Files Version

版本： 2.3.0.0 OS Version: 10.0.25136.1000

### Windows Version

版本	Windows 11 專業工作站版 Insider Preview 版本	22H2 安裝於	‎2022-‎06-‎12 OS 組建	25136.1000 體驗	Windows Feature Experience Pack 1000.25136.1000.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8906660/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8906661/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
This is by design, we are looking into supporting this but in the meantime you can use tools like PowerToys.

**Comment by AisinGioroKiIoi** [comment]
您好，我尝试了一下PowerToys。在咱的软件界面，右键菜单不显示这个软件项。在Windows资源管理器里显示，但人家原本就支持两个文件同时重命名，也就不需要该软件提供的功能。如果可以的话，希望咱的软件后续能够支持该功能。ᠪᠠᠨᡳᡥᠠ（巴尼哈/谢谢）
