### ISSUE TITLE
Feature: Display modal when file properties cannot be transferred 

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#9423]
### Description

Copying/Moving the file in Files will fail instantly. In Explorer the error below is shown
![image](https://user-images.githubusercontent.com/26977075/173921222-464b86c7-5c73-4956-af6f-cea185c9fd3f.png)

### Steps To Reproduce

1. Have a file with properties that can't be moved to a Fat32 File system
2. Copy or move the file into the Fat32 drive
3. Operation will fail instantly

### Steps to fix
- Display a model when properties cannot be copied/moved with a message "This item contains file properties that cannot be transferred, would you like to continue without transferring these properties?"
- Add a "Continue" button
- Add a skip button

### Files Version

2.3.0.0

### Windows Version

10.0.19043.1685

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8912856/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8912857/debug_fulltrust.log)

**Comment by Josh-65** [comment]
@yaichenbaum

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
What is the "continue" button for?

**Comment by Josh-65** [comment]
To transfer the file with the properties that can't be copied removed

**Comment by SteveWorkshop** [comment]
There're many file attributes (e.g. compatibility) that Files cannot display or modify while explorer.exe can

**Comment by yaira2** [comment]
@Josh65-2201 this feature has been implemented and will be included in one of the next feature releases.
