### ISSUE TITLE
App crashed while creating a new tab

### ISSUE THREAD

**Issue by tcantuarias** [files-community/Files#9424]
### Description

when i decided to open a new tab the app crashed.

the tab was of a onedrive folder

### Expected behavior

1. experimental features enabled
2. one onedrive tab open with the preview panel enabled
3. create another tab on the same onedrive account

### Files Version

Version: 2.3.0.0 OS Version: 10.0.22000.739

### Windows Version

Edition	Windows 11 Home Single Language Version	21H2 Installed on	‎6/‎15/‎2022 OS build	22000.739 Experience	Windows Feature Experience Pack 1000.22000.739.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8915306/debug.log)

**Comment by gave92** [comment]
Looks like the "usual" random issue.

> 22:59:05.7587|ERROR|AppUnhandledException|Layout cycle detected. Layout could not complete. Layout cycle detected. Layout could not complete.

**Comment by yaichenbaum** [comment]
@tcantuarias thank you for your feedback, unfortunately most of these issues come from the WinUI library which means it needs to be fixed on Microsofts end.
