### ISSUE TITLE
Crash after adding Library with name "Downloads"

### ISSUE THREAD

**Issue by Arno989** [files-community/Files#9426]
### Description

In libraries section on sidebar, added new library with name "Downloads", pressed enter and Files crashed. Afterwards library was still created.

### Expected behavior

No crash

### Files Version

Version: 2.2.5.0 OS Version: 10.0.22621.1

### Windows Version

Windows 11 Education 22H2 22621.1

### Relevant Assets/Logs

only relevant linein fulltrust log:
2022-06-16 14:39:17.3667|WARN|OnLibraryChanged|Failed to open library after Created: C:\Users\arno\AppData\Roaming\Microsoft\Windows\Libraries\Downloads.library-ms

**Comment by gave92** [comment]
Thanks for the report. This issue should be fixed on Files v2.3. If you don't find it on the Store you can get it from https://files.community/download/stable.
