### ISSUE TITLE
Bug: Deleting file in grouped folder moves selection to random item

### ISSUE THREAD

**Issue by carlosvsilva** [files-community/Files#9429]
### Description

I delete a file, and afterwards Files decides to graphically select another file at random (and scrolls down even to select that other file somewhere else) instead of just selecting the file right next to the one that was just deleted.

### Steps To Reproduce

1. Select a file and delete it
2. Confirm deletion
3. Now Files selects with the blue outline another file at random, and scrolls the window to display where the random selected file is
4. User now is lost because of this random window scroll

### Expected behavior

- Don't select any file

### Files Version

Versão: 2.3.0.0

### Windows Version

OS Version: 10.0.22000.739

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8920369/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8920370/debug_fulltrust.log)
![image](https://user-images.githubusercontent.com/40889421/174110331-d12fe79e-c425-4c9e-9576-27d2c5c9bd88.png)
![image](https://user-images.githubusercontent.com/40889421/174110477-53f5c6a0-4215-4860-aaf2-35d789e16d7f.png)

**Comment by gave92** [comment]
Does it work if the folder is not grouped and sorted by name?

**Comment by carlosvsilva** [comment]
It works correctly in that specific situation yes. This bug is in the current release, it's straightforward to confirm. Thanks.

**Comment by carlosvsilva** [comment]
This is still happening in latest version, deletes in Tile View when Grouping is enabled (ie, Downloads folder grouped by Date) the select rectangles (unfortunately there are still 2 of them, blue and black) will jump to another file somewhere else (that would be the next file in case grouping wasn't enabled).
