### ISSUE TITLE
Slow and lag

### ISSUE THREAD

**Issue by TheGetHuber** [files-community/Files#9431]
This app is beautiful, i want it to change my default ugly file manager without cool features as: tabs, google disk, folder size and ect. But this app is too much slow on my pc and sometimes its making lags in my pc. Please, optimise this app.
My pc specs:
OS: Windows 11
CPU: Intel Xeon E5450 3GHz 4 Cores
GPU: Nvidia GTX 750 Ti 2GB
RAM: 8GB DDR3

**Comment by gave92** [comment]
Thanks for your interest information Files. I suggest you try Files v.2.3 if you  don't have it already. You can get it from the Store or https://files.community/download/stable. A fresh reinstall may also help. Merging with #4180

**Comment by yair100** [comment]
@TheGetHuber we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
