### ISSUE TITLE
Ability to hide WSL distributions

### ISSUE THREAD

**Issue by rubenuijtdewilligen** [files-community/Files#9432]
### What's the Problem?

The main reason I use Files is because it shows Ubuntu WSL files out of the box. I recently installed Docker Desktop using the WSL2 backend and this is also showing in the WSL category in the sidebar. I'm never going to touch these files.

![image](https://user-images.githubusercontent.com/39881862/174428825-5ba443c7-73cd-43f2-b7c1-95dbe39e94e3.png)

### Solution/Idea

It would be awesome to have the option to hide the distros you're not interested in.

### Alternatives

No alternatives at this time.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Allow users to hide WSL distros | Must |
| Use an easy checkbox list | Should |
| While you're at it, maybe implement the same for Cloud Drives | Could |
| Completely hide the category. This feature already exists. | Won't |

### Files Version

2.3.0.0 

### Windows Version

Windows 11 21H2 22000.739

**Comment by yaichenbaum** [comment]
@rubenuijtdewilligen I recommend hiding the WSL section and pinning the Ubuntu distro to the favorites section.

**Comment by rubenuijtdewilligen** [comment]
That's a good solution, thanks!
