### ISSUE TITLE
Unable to display files from iPhone

### ISSUE THREAD

**Issue by oplewq** [files-community/Files#9433]
### Description

连接苹果设备，手机里的文件显示为空！Windows自带的文件管理是正常可以显示的！

### Expected behavior

图片显示如下
![image](https://user-images.githubusercontent.com/56243015/174431224-dde1c362-f667-464a-96e7-cb4c811063dc.png)
![image](https://user-images.githubusercontent.com/56243015/174431284-1e4d1a67-6dd1-48ad-9707-69548619bc26.png)
![image](https://user-images.githubusercontent.com/56243015/174431327-0379c0b2-ceca-42e7-bd0b-df0ccc17b886.png)

### Files Version

版本: 2.3.0.0 OS Version: 10.0.17763.3046

### Windows Version

Windows10 企业版LTSC，版本号1809，操作系统内部版本17763.3046

### Relevant Assets/Logs

[Uploading debug_fulltrust.log…]()
[debug.log](https://github.com/files-community/Files/files/8933284/debug.log)

**Comment by shenjackyuanjie** [comment]
建议把标题改成:
Can't view Apple device file
谢谢

**Comment by gave92** [comment]
Merging with #9453
