### ISSUE TITLE
Files crashed while permanently deleting many files

### ISSUE THREAD

**Issue by baconapo** [files-community/Files#9434]
### Description

I was permanently deleting my downloads folder and files crashed but the files still got deleted.

### Steps To Reproduce

Go to a folder with a lot of items and folders
Select all
Press Del on your keyboard
Select Permanently delete
Delete.

### Expected behavior

Files not to crash

### Files Version

2.3.0.0

### Windows Version

Windows 11 21H2 22000.675

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8934644/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8934645/debug_fulltrust.log)

**Comment by gave92** [comment]
Merging with #8763
