### ISSUE TITLE
移动、复制、剪切到指定目录未响应

### ISSUE THREAD

**Issue by Moe7ilin** [files-community/Files#9438]
### Description

我尝试了多种方式，关闭了一些选项，移动、复制、剪切到指定目录无响应

### Expected behavior

可以正常操作文件

### Files Version

2.3.0.0

### Windows Version

Windows 11 22H2 10.0.22621

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8936546/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8936547/debug.log)

**Comment by gave92** [comment]
Merging with #9404

**Comment by Moe7ilin** [comment]
https://user-images.githubusercontent.com/103707870/174503490-2cc39412-55e8-4384-9626-cafc3a55fbab.mp4
