### ISSUE TITLE
Feature: Cancel search when pressing esc key

### ISSUE THREAD

**Issue by Tamnac** [files-community/Files#9440]
### What's the Problem?

Currently if you are in the middle of a search and press escape, the app treats it like enter and continues the search. This goes against the escape button's supposed behavior.

### Requirements 

Pressing escape should cancel the search.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Pressing `esc` cancels search | Must |

### Files Version

Version: 2.3.0.0 

### Windows Version

10.0.19044.1766

**Comment by squirrelnest1986** [comment]
Kinda just going with the flow

**Comment by Shenbhagam** [comment]
It definitely makes the app close and there might me a chance of missing updates or code that you had made before exit.

**Comment by Sugarlust** [comment]
Hey, I'm new to opensource and would like to contribute to this as my first contribution. Can you please elaborate on the issue and how should I refer to code and the things i need to keep in mind before contributing. Thanks.

**Comment by Saso2022** [comment]
الخروج

**Comment by Tamnac** [comment]
Something strange, I got a comment from @Sugarlust asking for details but I can't see it here, and I'm not sure what @squirrelnest1986m @Shenbhagam and @Saso2022 are on about.

**Comment by Sugarlust** [comment]
@Tamnac i did make the comment and I myself can't see it anymore can you help and lemme know where I should start looking for the issue.

**Comment by Tamnac** [comment]
I just reported the issue and don't have any experience with the project itself so I can't help you much technically. The issue is that when a user is searching and presses `esc` (escape) it should cancel the the search, but it doesn't, instead it seems to treat it like enter. 

I'm guessing you would need to set up some sort of event listener for `esc` and when it comes call some function to cancel the search. For anything more concrete or where to look you'll have to wait for someone who has worked on this project.

**Comment by 13601981** [comment]
باید جستجو را لغو کند

**Comment by intelkid7** [comment]
When you are surfing google, pressing esc cancels the search
I guess there's no problem. Kindly specify which kind of software are you talking about
