### ISSUE TITLE
adjust font size of file icons

### ISSUE THREAD

**Issue by cleuton4k** [files-community/Files#9441]
### What's the Problem?

the font of the file icons has a very large size, not allowing the reading of the name and type of the file.

### Solution/Idea

automatic adjustment of font size for different types of layout.

### Alternatives

automatic adjustment of font size for different types of layout.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.3

### Windows Version

w10

### Comments

![01](https://user-images.githubusercontent.com/90144967/174606697-e086a7d5-688a-4b7b-b677-b527f3d3b7f7.jpg)
![02](https://user-images.githubusercontent.com/90144967/174606704-90ed5e66-8ad6-475f-ab6a-5e002d6eaedd.jpg)

**Comment by Josh-65** [comment]
Are you talking about the text beeing one line only in grid view?
