### ISSUE TITLE
Bug: Icons for libraries aren't displayed when opening the libraries folder

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#9446]
### Description

![image](https://user-images.githubusercontent.com/26977075/174687203-d1f10c7c-0487-491f-8eb2-c402d8f4f8a6.png)

### Steps To Reproduce
1. Navigate to `C:\Users\<User name>\AppData\Roaming\Microsoft\Windows\Libraries`
2. Observe that the library icons aren't displayed

### Expected behavior
- Icons should be displayed

### Files Version
v2.3.48

### Windows Version

10.0.19043.1685

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8944557/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8944558/debug_fulltrust.log)

**Comment by Josh65-2201** [comment]
@yair100

**Comment by Lukiluc29** [comment]
I have neither icons nor the name of the icons displayed
![Capture d’écran (11)](https://github.com/files-community/Files/assets/128183422/ab5349d5-d4cd-41fc-bded-a0f803aa2342)
