### ISSUE TITLE
Files didn't works as default file explorer. Standart windows exploer - always launches

### ISSUE THREAD

**Issue by BlackburnUTG** [files-community/Files#9448]
### Description

I turned on option in expiremental settings, and reloaded my PC. But windows exploer still here, when I open folders on my desktop 

### Expected behavior

Files should works as default file explorer. 

### Files Version

Версия: 2.3.0.0 OS Version: 10.0.19043.1766

### Windows Version

Выпуск	Windows 10 Домашняя Версия	21H1 Дата установки	‎09.‎02.‎2021 Сборка ОС	19043.1766 Взаимодействие	Windows Feature Experience Pack 120.2212.4180.0

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8953050/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8953051/debug.log)

**Comment by Josh-65** [comment]
Do you get an admin promt to change registry settings?

**Comment by BlackburnUTG** [comment]
yes. I got the window, and I clicked yes - to apply new registry settings

**Comment by BlackburnUTG** [comment]
foud the issue., It was other program - QTT bar. After I deleted it - Files works as default file explorer
