### ISSUE TITLE
Drag to reorder Favorites list

### ISSUE THREAD

**Issue by sguergachi** [files-community/Files#9449]
### What's the Problem?

Currently cant reorder favorites list

### Solution/Idea

Allow drag n drop to reorder favorites list items

### Alternatives

none really

### Files Version

Version: 2.3.0.0

### Windows Version

 OS Version: 10.0.22000.739

**Comment by gave92** [comment]
Unfortunately there's a bug in the winui control that prevents us from enabling it.
