### ISSUE TITLE
Display problem when deleting a file

### ISSUE THREAD

**Issue by Av32000** [files-community/Files#9452]
### Description

When I delete a folder (to the recycle bin), when the operation is started, the message displayed is: "The recycle bin is empty" whereas on the contrary I just filled it.
My app is in French

### Steps To Reproduce

1. Select a folder
2. Delete the folder
3. Check the message on the top right

### Expected behavior

Message: The folder has been moved to the recycle bin

### Files Version

Version : 2.1.50.0 OS Version: 10.0.22621.160

### Windows Version

Windows 11 22H2

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/59660601/175023972-5420808d-653a-4da6-b44c-3d38205b8dac.png)

**Comment by Av32000** [comment]
Yes

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
@Josh-65 can you reproduce the issue?

**Comment by Josh-65** [comment]
I have not had this happen to me.

**Comment by yaichenbaum** [comment]
We need some more information like what kind of folder, was it a network drive etc.

**Comment by Av32000** [comment]
It was a classic folder on the desktop that wasn't networked. For me the bug occurs for all folders.

**Comment by Av32000** [comment]
This may be an English -> French translation bug

**Comment by QuaintMako** [comment]
Definitely a translation error. 
The current translation was "The recycle cin is empty", changed it for "The emptying of the recycle bin is done."

Cannot link a PR for this one, but next time the french translations are updated, you may close that ticket @yair100. Thanks in advance :)

**Comment by yaichenbaum** [comment]
Thanks @QuaintMako
