### ISSUE TITLE
listary compatibility

### ISSUE THREAD

**Issue by Padpoy** [files-community/Files#9455]
### What's the Problem?

is it compatible with listary or not 
if not is there any plan to make it compatible

### Solution/Idea

Please make it compatible with listary

### Alternatives

I can't think of any alternative

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.3

### Windows Version

10

**Comment by gaoqiangks** [comment]
Where is #3842?

**Comment by yaira2** [comment]
Support for Listary is actively being worked on in #15069.
