### ISSUE TITLE
侧边栏问题

### ISSUE THREAD

**Issue by AisinGioroKiIoi** [files-community/Files#9457]
### Description

如图所示，左侧的导航栏不能默认展开，一直收缩着。望解决，ᠪᠠᠨᡳᡥᠠ（巴尼哈/谢谢）
![image](https://user-images.githubusercontent.com/52952040/175313761-508353b7-89ba-40dc-8ea2-bdd556aaeee2.png)

### Expected behavior

能默认展开侧边栏。

### Files Version

版本： 2.3.0.0 OS Version: 10.0.25145.1000

### Windows Version

版本	Windows 11 專業工作站版 Insider Preview 版本	22H2 安裝於	‎2022/‎6/‎23 OS 組建	25145.1000 體驗	Windows Feature Experience Pack 1000.25145.1000.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8967788/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8967789/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
You can expand the sidebar by dragging or double clicking the border.

**Comment by AisinGioroKiIoi** [comment]
好的，问题已解决。
