### ISSUE TITLE
Bundles Content Disappears

### ISSUE THREAD

**Issue by RazoBeckett** [files-community/Files#9458]
My 1st Bundle is working properly but 2nd bundle i created content of it disappears when i open it second time. I know it's easy complain but please fix it!

![image](https://user-images.githubusercontent.com/95993675/175324405-a3140473-6005-40eb-8b94-867a94b6dc28.png)

Your Faithfully,
RB

**Comment by yaichenbaum** [comment]
Thank you for taking the time to report this, in order to investigate the issue we'll need the log files and steps to repro this bug, can you please reopen this issue using the issue template?
