### ISSUE TITLE
Starting with Library on First Tab Crashes the App

### ISSUE THREAD

**Issue by AkazaRenn** [files-community/Files#9459]
### Description

Always happens, if I left `Documents` as the first tab and close the app, it will crash on the next start, all my tabs will be lost. However, if it is not the first tab, the app does not crash and gives "Documents.library-ms" on the title of the tab. Clicking onto the tab can load Documents correctly.

### Steps To Reproduce

1. In Settings -> Preference -> Startup settings, choose `Continue where you left off`
2. Open any one of the `Libraries` from the side panel as the first tab, I used `Documents`
3. Close the app through the X on top-right corner
4. Reopen the app
5. See the issue

### Expected behavior

It should not crash

### Files Version

Version: 2.3.0.0 OS Version: 10.0.22621.160

### Windows Version

Windows 11 Home 22621.160

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8968339/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8968340/debug_fulltrust.log)

**Comment by Josh65-2201** [comment]
@yair100

**Comment by Josh-65** [comment]
Is this still an issue?

**Comment by AkazaRenn** [comment]
@Josh-65 Seems like it's not happening now. Thanks for reminding!
