### ISSUE TITLE
Directory tree

### ISSUE THREAD

**Issue by Krowne** [files-community/Files#9460]
### What's the Problem?

In the side panel, the drives of the available partitions or disks are shown, but a tree is not displayed that unfolds as you go into the directories (not like in the windows explorer).

### Solution/Idea

The idea is that as in the Windows file explorer, in the side panel, as you enter the directories, a tree of the directories that are within the same level, or those that have been opened, is displayed. To facilitate access to directories within the same level simply with a click on the side panel. Since it currently doesn't show what level you are on, and to switch to another directory of the same level, you have to go up one level to see the list of available directories, when in the side panel, you could see everything at a glance like in Explorer Windows files.
![2022-06-24_013734](https://user-images.githubusercontent.com/10179070/175432052-8c45d379-dd5d-4907-aedb-f725abd7cf79.jpg)

### Alternatives

It could be considered to add this option so that the tree is displayed, only with the directories that you are opening, or when entering a directory, all the directories of the same level are shown in the tree.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Comments

Not having this feature is the only thing stopping me from definitely switching to this wonderful app.

Sorry if this request was made in the past, I'm not sure how to search for previous requests.

**Comment by yaichenbaum** [comment]
Merging with #1928

**Comment by yair100** [comment]
@Krowne Tree View is currently available in preview https://files.community/download. It will be included in the next stable release.
