### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by AisinGioroKiIoi** [files-community/Files#9461]
### Description

1、带密码的压缩文件，解压缩的时候，没有输入密码的位置，也没有任何提醒。只是生成一个空白文件夹。
2、文件，右键，没有压缩选项。
3、将文件复制到C盘软件安装目录时，提醒需要管理员权限，点了【确定】之后，依旧没有复制文件到目标位置。

### Expected behavior

1、解压缩带密码的文件。
2、可压缩文件
3、可将文件复制到C盘。

### Files Version

版本： 2.3.0.0 OS Version: 10.0.25145.1000

### Windows Version

版本	Windows 11 專業工作站版 Insider Preview 版本	22H2 安裝於	‎2022-‎06-‎23 OS 組建	25145.1000 體驗	Windows Feature Experience Pack 1000.25145.1000.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8972180/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8972182/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
Merging with #45
