### ISSUE TITLE
软件使用设置请求指导

### ISSUE THREAD

**Issue by AisinGioroKiIoi** [files-community/Files#9462]
### Description

![image](https://user-images.githubusercontent.com/52952040/175469832-1cd7a99f-ee81-48ea-ab0d-6e9b8e6fcf24.png)
如图所示，把这几个展开后，【快速访问】那一项，会在一些操作下自动收缩，比如按一下键盘的Windows键。该如何设置让其保持展开呢？

### Expected behavior

【快速访问】保持展开。

### Files Version

版本： 2.3.0.0 OS Version: 10.0.25145.1000

### Windows Version

版本	Windows 11 專業工作站版 Insider Preview 版本	22H2 安裝於	‎2022/‎6/‎23 OS 組建	25145.1000 體驗	Windows Feature Experience Pack 1000.25145.1000.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8973455/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8973456/debug_fulltrust.log)

**Comment by Josh-65** [comment]
Is this still an issue? I have not had this and there isnt any link to those by default.

**Comment by AisinGioroKiIoi** [comment]
最近几天，这个问题消失了。
