### ISSUE TITLE
EXE文件无法执行

### ISSUE THREAD

**Issue by AisinGioroKiIoi** [files-community/Files#9463]
### Description

文件夹中，点exe文件，并不运行。

### Expected behavior

点一下EXE文件，直接运行。

### Files Version

版本： 2.3.0.0 OS Version: 10.0.25145.1000

### Windows Version

版本	Windows 11 專業工作站版 Insider Preview 版本	22H2 安裝於	‎2022-‎06-‎23 OS 組建	25145.1000 體驗	Windows Feature Experience Pack 1000.25145.1000.0

### Relevant Assets/Logs

[Uploading debug.log…]()
[Uploading debug_fulltrust.log…]()

**Comment by Josh-65** [comment]
Have you tried opening them in File Explorer if they do open then you will need to upload the logs files directly to github. You can get them in files settings > about > open log folder.

**Comment by AisinGioroKiIoi** [comment]
> 您是否嘗試過在文件資源管理器中打開它們（如果它們確實打開），則需要將日誌檔直接上傳到github。您可以在檔案設定中獲取它們，>有關打開>日誌資料夾的資訊。

您好，这些EXE文件在Windows文件资源管理器中是可以直接打开的。比如QQ的安装程序。
[debug.log](https://github.com/files-community/Files/files/8982515/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8982516/debug_fulltrust.log)

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
We need another person to be able to reproduce this

**Comment by Josh-65** [comment]
@AisinGioroKiIoi  Is this still an issue in 2.3.11.0

**Comment by AisinGioroKiIoi** [comment]
> @AisinGioroKiIoi 這仍然是 2.3.11.0 中的問題嗎

您好，我测试了三款软件，其一是直接运行的EXE文件，另外两款是进行软件安装的EXE文件。均可以正常运行。ᠪᠠᠨᡳᡥᠠ（巴尼哈/谢谢）
