### ISSUE TITLE
窗口显示问题

### ISSUE THREAD

**Issue by AisinGioroKiIoi** [files-community/Files#9464]
### Description

使用浏览器下载文件时，在浏览器上点击文件打开文件所在位置的时候，咱的软件窗口并不能置顶，只是在任务栏显示一下亮色。

### Expected behavior

在浏览器下载的文件右键打开文件所在位置的时候，咱软件的窗口置顶显示。

### Files Version

版本： 2.3.0.0 OS Version: 10.0.25145.1000

### Windows Version

版本	Windows 11 專業工作站版 Insider Preview 版本	22H2 安裝於	‎2022/‎6/‎23 OS 組建	25145.1000 體驗	Windows Feature Experience Pack 1000.25145.1000.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8975418/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8975421/debug_fulltrust.log)

**Comment by Josh-65** [comment]
Unfortunately translateing the issue into english means it doesnt make sence. Are you talking about Files showing above the brower window when you open the file location? if so this is normal behaviour.

**Comment by AisinGioroKiIoi** [comment]
> 不幸的是，將問題翻譯成英語意味著它沒有意義。您是在談論開啟檔案位置時瀏覽器視窗上方顯示的檔案嗎？如果是這樣，這是正常行為。

您好，在Windows原生应用中，在浏览器中下载区域点【打开文档所在位置】时，会弹出Windows资源管理器，并定位到已下载的文件。而咱的软件中，在浏览器中下载区域点【打开文档所在位置】时，并不弹出文件夹，只是在任务栏闪烁提醒。而且，当点击任务栏上的图标打开文件夹后，虽然定位到了文件，但是当该文件夹文件过多时，仍需要滑动鼠标来寻找刚才下载的问题。不会像原生文件夹那样，直接在视窗所能展示的地方显示出来。

**Comment by Josh65-2201** [comment]
@yair100

**Comment by yaichenbaum** [comment]
This is a limitation of the method we use to set Files as the default. I don't see a reason to keep this issue open, but we'll keep looking for a solution to highlight the downloaded item.
