### ISSUE TITLE
Feature: Smart toolbar prediction

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#9465]
### What's the Problem?

The toolbar was created to make options more discoverable and easier to access without having to open the right click context menu but outside of a few scenarios (such as images and archives), the options stay the same and aren't aware of the selected item. This forces users to frequently open the context menu, it would be great if there was a way for Files to learn the user's preference and reduce the need to open the context menu.

### Solution/Idea

We can use a locally stored database that tracks which options the user is most likely to use. Predictions will be different for each file type, and it will be based on which context menu options they use the most. This database will change over time to keep up with the user's workflow and will also be able to add toolbar buttons to access shell extension when appropriate.

Microsoft Edge has a similar system in place to auto complete URLs (edge://predictors/)

### Alternatives

NA

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Database stored on local machine that tracks which context menu options are used most for each file type | Must |
| Top three options (top three will need to filter out the default options which are already in the toolbar) will be added to the toolbar after the default items | Must |
| Database should export with the rest of the settings | Must |

### Files Version

v2.3

### Windows Version

Windows 11

**Comment by ferrariofilippo** [comment]
> We can use a locally stored database that tracks which options the user is most likely to use

With it we could also load the most used actions on startup, and delay the others. Since loading actions has a big impact on startup, this would improve performance

**Comment by yaira2** [comment]
@ferrariofilippo perhaps a solution for that issue is to delay all actions until the app is fully started.

**Comment by yaira2** [comment]
While not exactly the same as #2780, a command palette will serve a similar purpose of making it easier to access different actions.
