### ISSUE TITLE
Partial translations option in Language setting

### ISSUE THREAD

**Issue by ray1997** [files-community/Files#9467]
### What's the Problem?

Since all translation is now done on Crowdin, it might be a good idea to integrate Crowdin translation into the app where language that hasn't complete should show a total progress translation after its

This might drive some user on other language to motivate to help contribute translation on their language

Something like this:
![image](https://user-images.githubusercontent.com/14814401/175799667-58f703f6-a5b2-47ff-b713-29ad0f829dec.png)

### Solution/Idea

Using Crowdin API ([.net version](https://github.com/crowdin/crowdin-api-client-dotnet)) and integrate into the application, checking for update to the project on Crowdin occasionally should be suffice. This will help reduce the need to wait for each update for new translation 

### Alternatives

Or just compile everything and put it up each update..

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to see the translation on their language quicker | Could |
| This proposal will allow translator to test and made an adjustment to their translation quicker | Could |

**Comment by yaichenbaum** [comment]
Would users understand what the percentage means?
