### ISSUE TITLE
AppSdk:  Why not utilize this?

### ISSUE THREAD

**Issue by KaidudePlays** [files-community/Files#9470]
### Solution/Idea

As this could require a lot of work, the benefits are simple. These include improved compatibility, faster updates, and new design elements.   Plus uwp may not be getting these new technologies.    My main point is that, while this would take a lot of work, the speed.   While the move is not required, uwp seems to be slowly being faded out.   Thanks and I look forward to see how this suggestion improves this app.  (This will use WinUi 3.0)

[Article with some information that I used here](https://www.digitaltrends.com/computing/microsoft-making-moves-kill-off-uwp/)

[Microsoft documentation on porting uwp apps to the AppSdk](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/migrate-to-windows-app-sdk/migrate-to-windows-app-sdk-ovw)

[More details on the AppSdk](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/)

### Alternatives

The options are simple:  Port the app to the AppSdk and take advantage of the speed, do nothing and stay as a uwp app or look into the speed of the alternative file explorer apps that already have ported to the app sdk.

### Priorities

1. This will prioritize new AppSdk features as these come out.
2. The app will have faster load times/speed improvements.
3.  Microsoft seems to be moving towards the AppSdk as the next evolution in windows app development.

### Windows Version

22H2/other windows versions

### Comments

Note: A good example of the AppSdk in use for file explorers is Shrestha Files.  I high recommend checking this out to see the benefits.  Thanks!

**Comment by yaichenbaum** [comment]
@KaidudePlays we've been working on this transition for a couple of months by refactoring the code base and removing blockers. We're hoping to have a preview version by Q3 2023 but it'll depend on the state of WinUI and the amount of help we get with Files.
