### ISSUE TITLE
Flies is slow when I open a folder 

### ISSUE THREAD

**Issue by JosiasAurel** [files-community/Files#9473]
### Description

When I click on a folder it takes about 2s to open the folder. 

### Steps To Reproduce

1. Open files
2. Click on a folder 

### Expected behavior

Load the folder in less than a second as the default explorer would

### Files Version

2.3.00

### Windows Version

Windows 11 22H2 25131.1000

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8994766/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8994767/debug.log)

**Comment by yaichenbaum** [comment]
Thank you for your feedback, improving performance is one of our top goals and we encourage you to watch this area over the next couple of months as we continue work on our refactor.
