### ISSUE TITLE
Merge Files.Uwp\Helpers\NativeIoDeviceControlHelper.cs and Files.Uwp\Helpers\NativeFileOperationsHelper.cs

### ISSUE THREAD

**Issue by peteraritchie** [files-community/Files#9479]
### What's the Problem?

Files.Uwp\Helpers\NativeIoDeviceControlHelper.cs and Files.Uwp\Helpers\NativeFileOperationsHelper.cs contain some of the same definitions creating duplicate code and is either redundant or introduces maintenance issues.

### Solution/Idea

Merge Files.Uwp\Helpers\NativeIoDeviceControlHelper.cs and Files.Uwp\Helpers\NativeFileOperationsHelper.cs to remove duplicate declarations and definitions.

### Alternatives

Leave it alone and accept the maintenance risk.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by d2dyno1** [comment]
@peteraritchie Would you like to work on it? 🙂
