### ISSUE TITLE
Full trust process is crashing

### ISSUE THREAD

**Issue by TheKoTech** [files-community/Files#9480]
### Description

When opening context menu for an .inf file, the context menu is incomplete. In my case, a crusor pack. 

### Steps To Reproduce

1. Get an .inf file. For example, [Windows 11 Cursors Concept v2 (Deviant Art)](https://www.deviantart.com/jepricreations/art/Windows-11-Cursors-Concept-v2-886489356)
2. Right click .inf
3. Unable to install the cursors

### Expected behavior

It should show the same options as the standard Explorer

### Files Version

2.3.0.0

### Windows Version

Windows 10 
Version: 20H2
Build: 19042.1766

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/92980051/176785069-aee8a381-174c-4374-8603-c8390c9751c8.png)
![image](https://user-images.githubusercontent.com/92980051/176785117-80bab7bc-10d6-4fec-b694-1f2ee6fd8f97.png)
*Установить - Install

**Comment by yaichenbaum** [comment]
@TheKoTech what happens if you scroll down?

**Comment by TheKoTech** [comment]
> what happens if you scroll down?

@yair100 Nothing, there is no slider.

Somehow, this problem only occurs on my laptop, but not on PC:
![image](https://user-images.githubusercontent.com/92980051/176993516-391816c5-640e-4352-acc1-7985fee71514.png)

In the fulltrust log it shows the same entry:
`2022-07-02 13:47:52.3778|INFO|OnConnectionRequestReceived|Argument: LoadContextMenu`

**Comment by TheKoTech** [comment]
I checked some more for any differences in the systems. Turns out, I have a different Win10 version on laptop.

Win10 
Version: 20H2 1
Build: 9042.1766

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
Is this specific to inf files?

**Comment by TheKoTech** [comment]
@yair100, it's not, but only happens to somewhat rare extensions

**Comment by yaichenbaum** [comment]
Seems like the full trust process is crashing

**Comment by yaichenbaum** [comment]
@TheKoTech can you see if this is fixed in the preview build? https://www.files.community/download/preview
