### ISSUE TITLE
Context menu "New" option inconsistent with explorer.exe

### ISSUE THREAD

**Issue by 8LWXpg** [files-community/Files#9485]
### Description

I found that the context New option is different form Explorer

## In Explorer
<img width="283" alt="Screenshot 2022-07-03 003419" src="https://user-images.githubusercontent.com/105704427/177008924-877a981d-e09e-4bb2-aa1e-159b5080ac08.png">

## In Files
<img width="290" alt="Screenshot 2022-07-03 003355" src="https://user-images.githubusercontent.com/105704427/177008930-4c8babf3-8982-4379-887a-961932cad32a.png">

### Expected behavior

It should be the same

### Files Version

Version: 2.3.0.0 OS Version: 10.0.22000.739

### Windows Version

Windows 11 Home 21H2 1000.22000.739.0

### Relevant Assets/Logs

the xml document has HKCR\.xml\ShellNew
and the zip Archive has HKCR\.zip\CompressedFolder\ShellNew , which seems wouldn't be detected by Explorer.
.bmp and .txt both don't have ShellNew key.

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
