### ISSUE TITLE
Progress bar while doing file operations like copy, move delete etc.

### ISSUE THREAD

**Issue by DipAdu7476** [files-community/Files#9487]
### What's the Problem?

Can we have a progress bar or graph like the native explorer, while copying, moving or deleting the file rather than the notification on top right. something like a progress indicator. e.g. coped 16% and then a green bar progressing from let to right. something similar to indicate that the operation is in progress.

### Solution/Idea

Create a progress bar indicator.

### Alternatives

or show some indication that the file operation is active on top right, maybe flash a small icon or highlight the progress.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Comments

Edition	Windows 11 Pro
Version	21H2
Installed on	‎07-‎06-‎2022
OS build	22000.778
Experience	Windows Feature Experience Pack 1000.22000.778.0

**Comment by yaichenbaum** [comment]
Merging with #4811
