### ISSUE TITLE
Bug: Opening terminal in libraries doesnt use the default location for the path

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#9488]
### Description

Currently it just open to C:

### Expected behavior

Should use the default libary path

### Files Version

2.3.0.0

### Windows Version

10.19043.1685

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9035170/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9035172/debug_fulltrust.log)

**Comment by searchify7** [comment]
Libary

**Comment by yaichenbaum** [comment]
@Josh-65 is this same as #5648?

**Comment by Josh-65** [comment]
no this only effect libarys using the normal open in terminal right click option. 5648 is for when runing a .bat and proberly .cmd files as admin anywhere

**Comment by wyldcrd** [comment]
then most likely the problem is the app might not know if the other drive letters are like E:\ and stuff. (i don't know much about this app so...)

**Comment by Josh-65** [comment]
It does have anything do do with drive letters. it simply doest read the default location of the libary and sends that to the terminal.

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by Josh-65** [comment]
There isn't an option to open the terminal any more. Seem to be a separate issue were the option doesn't show when clicking a blank area of a directory
