### ISSUE TITLE
Library bug

### ISSUE THREAD

**Issue by red-carrot** [files-community/Files#9490]
### Description

I have a custom library and when I have tried to open it through this app it crashed.

I doesn't crash when I open the same folde through favorites.

### Steps To Reproduce

1. Make a new library
2. Show library's option wih right click in files sidebar
3. Try to acces that library from the sidebar
4. Repeat the cycle

### Expected behavior

The folde should get open

### Files Version

2.3.0.0

### Windows Version

Windows 11

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9042386/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9042387/debug_fulltrust.log)

**Comment by gave92** [comment]
What's the name of the library? What language/locale are you using for Files?
