### ISSUE TITLE
Default view edit

### ISSUE THREAD

**Issue by red-carrot** [files-community/Files#9491]
### What's the Problem?

I want to make the folder column view default. Maybe I just didn't found the option.

### Solution/Idea

Some way of changing the default view

### Alternatives

1. A right click button on the "Columns" kind of buttons to make them default.
2. A click on that view to make the selected option to open the next time.
3. An option on preferences to make the last opened view the next one that is going to open.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.3.0.0

### Windows Version

Windows 11

### Comments

I cannot thing on anything better, grat app by the way, i'm really loving it.

**Comment by Josh-65** [comment]
Go to Files settings > Prefrances > Files and Folder > Turn off the individual prefrances option. then set you view to column.
