### ISSUE TITLE
Compress files

### ISSUE THREAD

**Issue by Andrescity** [files-community/Files#9492]
### What's the Problem?

No hay forma que con el menu contextual se pueda comprimir archivos como se hace con el explorador de windows original

### Solution/Idea

Agregar las funciones de compresión en el menu contextual.

### Alternatives

Agregar las funciones de compresión en el menu contextual.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Versión: 2.3.0.0 OS Version: 10.0.22000.778

### Windows Version

Windows 11 21H2 22000.778

### Comments

No compress files available in contextual menu
![Screenshot_1](https://user-images.githubusercontent.com/48625755/177244948-0f0d466c-df2c-4be3-9629-c86efaacf1be.png)

**Comment by gave92** [comment]
Meriggnwith #41

**Comment by gave92** [comment]
Atm you can create a zip archive from the "new" menu and add stuff to it
