### ISSUE TITLE
Bug: Progress ring indicator is missing from tabs

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#9495]
### Description

For the likes of the network search folder on the sidebar and recycle bin the loading indicator is missing over the tab icon

### Steps To Reproduce

1. Load large directory that takes a couple of seconds to load

### Requirements
- Add progress ring to the tab to indicate it's still loading the folders content

### Windows Version

10.0.19043.1806

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9046320/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9046321/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
Just for context, the loader indicator was removed with the tab redesign and wasn't added back yet.

**Comment by BhaveshAnandpara** [comment]
@yaichenbaum Is this issue still open ?? I want to work on this Issue

**Comment by Josh-65** [comment]
yes it open. just make a pull request with it added

**Comment by BhaveshAnandpara** [comment]
I am still a beginner so is there some Guide ??

**Comment by Josh-65** [comment]
it normal c# and WinUI 2 xmal so you could proberly google stuff about it. WinUI galary on the Microsoft Store also give some excamples and code for WinUi. Enviroment setup instructions are here https://github.com/files-community/Files#building-from-source

**Comment by BhaveshAnandpara** [comment]
@Josh-65  Sorry, but I am actually confused about loader indicator is there some kind of example or image about it looks ??

**Comment by Josh-65** [comment]
The loading indication should replace the icon in the tab its called a progress ring offically 
![image](https://user-images.githubusercontent.com/26977075/179506147-72ba8149-aeca-42f8-a7d3-42be5ac21d51.png)
