### ISSUE TITLE
With Files as the default file manager, selecting "Fonts" in the Control Panel opens a File Explorer window in the Documents library

### ISSUE THREAD

**Issue by dianawhite42** [files-community/Files#9496]
With Files as the default file manager, selecting "Fonts" in the Control Panel opens a (Windows) File Explorer window in the Documents library, or at least it does on my system (Windows 11). This can be worked around by right-clicking Fonts and selecting "open in new window."

Files Version: 2.3.0.0
OS Version: 10.0.22000.739

**Comment by yaichenbaum** [comment]
This is one of the side effects of replacing File Explorer and we don't have plans to fix this. That being said, if we do find a fix, we'll try to implement it.
