### ISSUE TITLE
Ctrl + Enter shortcut to open selected folder in a new tab

### ISSUE THREAD

**Issue by ELowry** [files-community/Files#9499]
### What's the Problem?

There is currently no quick way to open a folder in a new tab.

### Solution/Idea

The idea would be to include some keyboard shortcut and/or Keyboard+Mouse combos to open a folder as a new tab.

### Alternatives

1. `Ctrl`+`Enter`
2. `Shift`+`Enter`

Impossible combinations include:

- `Alt`+`Enter` (Opens Properties)
- `Shift`+`Double-Click` (In single-click mode, Shift is used to select)

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Let users open a single folder in a new tab. | Must |
| Involve as few inputs as possible | Should |
| Move the view to the newly opened tab by default | Should |
| Have an option to not move the view to the newly opened tab | Could |
| Should not interfere with existing shortcuts | Won't |

### Files Version

2.3.0.0

### Windows Version

Windows 11 Pro 22H2 22621.169

### Comments

Though a keyboard shortcut alone would be amazing, it would also be extremely useful to have a keyboard+mouse combo since a lot of people tend to have one mouse on the keyboard and one on the mouse when using Files.

**Comment by yaichenbaum** [comment]
`Ctrl` + `Enter` should work.

**Comment by ELowry** [comment]
Note: the keyboard+Click part is covered by #6539

**Comment by chrisbrown-01** [comment]
Hello all, noob dev here trying to obtain some open-source C# experience. I have a hunch of how to implement this but am looking for some direction on how to proceed.

My initial idea is to find the .xaml file(s) related to folder/drive selection and implement a keyboard accelerator that calls the `OpenPathInNewTab()` method in the `src\Files.Uwp\Helpers\NavigationHelpers.cs` class

However I have been looking for a few days and am unable to figure out how a folder is determined to be selected and what the corresponding .xaml file(s) are. I am wondering if anyone is able to kindly provide some general guidance? Thank you in advance.

@ELowry  @yair100
