### ISSUE TITLE
Include the full list of context menu entries in one block when using  Shift+RightClick

### ISSUE THREAD

**Issue by ELowry** [files-community/Files#9500]
### What's the Problem?

There is currently no way to display all context menu entries directly (including those normally hidden in the "more" sub-panel).

### Solution/Idea

Following the precedent set by Microsoft in Windows 11 22H2, using `Shift`+`RightClick` should open a more compact context menu with all entries included and no "More" overflow menu at the end.

Here are examples of how Windows Explorer handles this system:

- **Default:**
![image](https://user-images.githubusercontent.com/7792033/177429225-5f2bc61e-e2d9-42c9-afa7-98ea1f4ba865.png)
- **With Shift:**
![image](https://user-images.githubusercontent.com/7792033/177429199-ccbb35cf-41d8-480f-8af2-7fce9de36b26.png)

### Alternatives

An option could be added to the Settings to have this be the default mode; possibly flipping the two display types (`Shift`+`RightClick` would display the current default if the option is enabled).

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Use a keyboard modifier—such as the `Shift` key— to display all 1st-level context menu entries in a single list without an overflow. | Must |
| Reduce padding across all context menu items in this display in order to avoid the need for excessive scrolling. | Should |
| Offer an option to make this the default; and possibly flip the two displays if this option is selected. | Could |

### Files Version

2.3.0.0

### Windows Version

Windows 11 Pro 22H2 22621.169

### Comments

Since this is now the default way Windows Explorer operates as of Windows 11 22H2; it would make sense to include it since many users will have integrated it in their habits and expectations. This will avoid a lot of frustration when switching over to Files from Windows Explorer and the unavoidable bug/request tickets some will create.

**Comment by yaichenbaum** [comment]
You can get a similar behavior by turning off this setting.
![image](https://user-images.githubusercontent.com/39923744/177431119-e7d14b39-ac59-4a0a-86fc-5e364cd226d8.png)
