### ISSUE TITLE
Make only the title-bar transparent?

### ISSUE THREAD

**Issue by NiZi9** [files-community/Files#9504]
### Make only titlebars transparent

I'm sorry if this feature already exists, I'm really no computer expert but I read the documentation on themeing and wondered if it is possible to only make the titlebar of the app transparent? If not, could this feature be added to files?

Right now it seems the whole app either has transparency or does not. The attached picture is the concept of the look I'm trying to achieve
![concept](https://user-images.githubusercontent.com/97229944/177502968-ccd5a5a6-28ca-4fdc-8195-00b00aba83b8.png)
.

### Solution/Idea

Add option/designs which only have a transparent titlebar.

### Alternatives

If it is already possible, maybe tutorial on how to do it in the documentation? :)

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
This is not a supported scenario and we don't have any plans to support it right now.

**Comment by Surferlul** [comment]
It is Possible, just not properly Documented. You can set "RootBackgroundBrush" to a transparent value to make the titlebar Acrylic, "NavigationToolbarBackgroundBrush" to make the navigation bar (search, path) transparent, "TabViewItemHeaderBackground" to make the Tabs Transparent and "SidebarContentBackgroundBrush" to an opaque value to make the the rest of the Window opaque. Here is an example where I modified the Acrylic theme (Use dark mode for the example, I did nothing to the Light mode):

```
<ResourceDictionary
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:BelowWindows10version1809="http://schemas.microsoft.com/winfx/2006/xaml/presentation?IsApiContractNotPresent(Windows.Foundation.UniversalApiContract, 7)"
    xmlns:Windows10version1809="http://schemas.microsoft.com/winfx/2006/xaml/presentation?IsApiContractPresent(Windows.Foundation.UniversalApiContract, 7)">
    <ResourceDictionary.ThemeDictionaries>
        <ResourceDictionary x:Key="Default">
            <SolidColorBrush x:Key="TextControlBorderBrush" Color="transparent" />
            <AcrylicBrush
                x:Key="TabViewItemHeaderBackground"
                BackgroundSource="HostBackdrop"
                FallbackColor="{ThemeResource SolidBackgroundFillColorTertiary}"
                TintColor="{ThemeResource SolidBackgroundFillColorTertiary}"
                TintOpacity="0.75" />
            <AcrylicBrush
                x:Key="NavigationToolbarBackgroundBrush"
                BackgroundSource="HostBackdrop"
                FallbackColor="{ThemeResource SolidBackgroundFillColorQuarternary}"
                TintColor="{ThemeResource SolidBackgroundFillColorQuarternary}"
                TintOpacity="0.75" />
            <AcrylicBrush
                x:Key="SidebarContentBackgroundBrush"
                BackgroundSource="HostBackdrop"
                FallbackColor="{ThemeResource SolidBackgroundFillColorBase}"
                TintColor="{ThemeResource SolidBackgroundFillColorBase}"
                TintOpacity="0.95" />
            <AcrylicBrush
                x:Key="RootBackgroundBrush"
                BackgroundSource="HostBackdrop"
                FallbackColor="{ThemeResource SolidBackgroundFillColorBase}"
                TintColor="{ThemeResource SolidBackgroundFillColorBase}"
                TintOpacity="0.85" />
        </ResourceDictionary>
        <ResourceDictionary x:Key="Light">
        </ResourceDictionary>
        <ResourceDictionary x:Key="HighContrast">
            <StaticResource x:Key="RegionColor" ResourceKey="SystemColorWindowColor" />
            <SolidColorBrush x:Key="RegionBrush" Color="{ThemeResource RegionColor}" />
        </ResourceDictionary>
    </ResourceDictionary.ThemeDictionaries>
</ResourceDictionary>
```
