### ISSUE TITLE
Czech (cs-cz) language missing 

### ISSUE THREAD

**Issue by koubafire** [files-community/Files#9505]
### Description

IT WAS in earlier versions but now Czech language is gone.

### Expected behavior

Czech texts

### Files Version

2.3.0

### Windows Version

Windows 11 22H2 22622.169

### Relevant Assets/Logs

For language Bug is not necesary.

**Comment by yaichenbaum** [comment]
We removed a couple of translations with v2.3 as we didn't receive the author's permission to switch the license to MIT. We encourage you to look at our Crowdin project if you're interested in adding a new localization to Files https://crowdin.com/project/files-app).
