### ISSUE TITLE
Bug: Alt+Shift++" shortcut only works with Numpad Plus key

### ISSUE THREAD

**Issue by verdaderoken** [files-community/Files#9508]
### What's the Problem?

It seems that the **New Pane**'s shortcut <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>+</kbd> only works with Numpad plus key. The other <kbd>+</kbd> key near the <kbd>Backspace</kbd> isn't working.
![image](https://user-images.githubusercontent.com/88200096/177630800-a4b2d580-1c84-4a49-8bef-988b69e2d20a.png)

---
_(This is just an extra)_
Currently, the **New Pane** & **Close Pane**'s shortcut keys are so far away from each other.
|Name| Shortcut|
| - | - | 
| New Pane | <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>+</kbd>  |
| Close Pane | <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>W</kbd>  |

### Solution/Idea

Add support for <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>+ (Plus)</kbd> from number row, not just for NumpadPlus key

### Alternatives

I would suggest to rebind the shortcut key for **New Pane** nearer to **Close Pane**'s <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>W</kbd> hotkey.
For example: <kbd>Shift</kbd>+<kbd>W</kbd>

### Files Version

2.3.1.0

### Windows Version

10.0.22621.160

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
Looks like a bug

**Comment by JJRcop** [comment]
I have a laptop which is missing the Numpad + key entirely, so this would be great.

**Comment by ThePython10110** [comment]
I can confirm this as well (Version: 2.3.12.0, OS Version: 10.0.19044.2192)
