### ISSUE TITLE
context menu does not close

### ISSUE THREAD

**Issue by au-lait77** [files-community/Files#9511]
### Description

See video, after calling the context menu and then using ALT+TAB, the menu remains open and then also permanently.

### Steps To Reproduce

Open context menu 
-> Layout mode
-> click ALT + TA

https://user-images.githubusercontent.com/13865833/177734051-952dbb27-348a-48ce-b0ae-07a273aca077.mp4

### Expected behavior

That it closes automatically

### Files Version

2.3.0.0

### Windows Version

Windows 10 Pro 21H2

### Relevant Assets/Logs

-

**Comment by gave92** [comment]
Closing as WinUI issue.
