### ISSUE TITLE
MS Office previews

### ISSUE THREAD

**Issue by EmilioCat** [files-community/Files#9512]
### What's the Problem?

I've just installed files and yes I like it but, and may be I am not intelligent enough, it has no preview of all MS Office files like excel aso.
PDF works fine with the preview windows.
SO my questions to you, is it already there and I didn't find how to or it will come ?

### Solution/Idea

I have no idea

### Alternatives

y

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.3.0.0

### Windows Version

Desktop Windows 10 and Laptop Windows 11 

### Comments

w

**Comment by gave92** [comment]
Merging with #4041
