### ISSUE TITLE
File Preview like windows Explorer

### ISSUE THREAD

**Issue by ERGPOL** [files-community/Files#9515]
### What's the Problem?

File preview is not dynamic like the windows explorer.
(Only reason why iam using win explorer :-))

### Solution/Idea

scrolling, zooming  and a bigger layout (full size) of preview

### Alternatives

--

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installiert am	‎05.‎06.‎2021 Betriebssystembuild	22000.778 Leistung	Windows Feature Experience Pack 1000.22000.778.0

**Comment by yaichenbaum** [comment]
We're working on a full screen preview option but in the meantime, we recommend using QuickLook for a similar behavior.
