### ISSUE TITLE
when you open a folder - it shows as empty for 15seconds

### ISSUE THREAD

**Issue by BlackburnUTG** [files-community/Files#9517]
### Description

Sometimes, when I open any folder - it shows as empty for ~15seconds. After that everything is show corectly.
Plus sometimes I can't open any file (exe, txt etc) - I double click, rmb-open - nothink works, only  close and reopen Files  fixes this

### Expected behavior

no 15second loading tim,es
files opens corectly

### Files Version

Версия: 2.3.0.0 OS Version: 10.0.19043.1766

### Windows Version

Имя устройства	DESKTOP-T7S8V71 Процессор	AMD Ryzen 7 3700X 8-Core Processor                3.60 GHz Оперативная память	16,0 ГБ Код устройства	0797394B-5118-4259-9E93-AB638CD9335E Код продукта	00326-30000-00001-AA594 Тип системы	64-разрядная операционная система, процессор x64 Перо и сенсорный ввод	Для этого монитора недоступен ввод с помощью пера и сенсорный ввод

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/9066669/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/9066672/debug.log)

**Comment by BlackburnUTG** [comment]
is it known bug? or is it just lucky me? something strange appear with Files on my PC - my folder C:\Users\User\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup shows as emprt with only 1 file -desktop.ini. 
but I have them a bunch of files. I even copied there a new files - and it dissapears on the next lauinch of Files

**Comment by yaichenbaum** [comment]
Is this an issue in the preview version? https://files.community/download/preview

**Comment by sthivaios** [comment]
@yair100 Nope, definitely not. This is not an issue in the PRE version.



https://user-images.githubusercontent.com/109022579/195161688-4e14e776-7281-40ff-a1da-af171b8ea807.mp4
