### ISSUE TITLE
Conflicts Dialog not open and works and Google Drive not shown in Cloud Drives

### ISSUE THREAD

**Issue by Mig10100** [files-community/Files#9518]
### Description

When i copy Folders or Files and the same are still there it not open Conflicts Dialog or something, it copy file or folder and make filename - copy or foldername - copy and again copy (2) ..... progress bar when copying is not there only at the top right in files the circle, i dont know this normal or not. i didnt find something to config.

Google drive doesn't show up in Cloud drives, only my OneDrive drive.

### Expected behavior

when i copy or move files or folders, and the file or folder already exists, i get a query what to do (conflicts dialog) (change name, skip, overwrite)

That my Google Drive also is shown in Cloud drivese

### Files Version

Files Version: 2.3.3.0

### Windows Version

Windows 11 21H2 22000.778

### Relevant Assets/Logs

![2022-07-07 (2)](https://user-images.githubusercontent.com/108902110/177877344-258bbf61-6a65-477f-bae7-76fc5d8e7c87.jpeg)
![2022-07-07 (3)](https://user-images.githubusercontent.com/108902110/177877347-9ee32354-a0c2-4b88-8c77-f71610d2cc13.jpeg)

**Comment by yaichenbaum** [comment]
Copying and pasting an item in the same directory doesn't bring up the conflicts dialog by design as the items are a 1:1 match. We only show the dialog when you copy an item from a different location since the items might be different.

**Comment by gave92** [comment]
Due to a limitation of UWP we can't check for file existance on network drives (well, we could but it would be incredibly slow) so we skip the conflict dialog in that case.
For google drive, does it at least show under Drives section?

**Comment by Mig10100** [comment]
Ok understand thanks, Google Drive is shown in Drive section as Google Drive (F:)

**Comment by yaichenbaum** [comment]
Google Drive now displays under the cloud drives section as well
