### ISSUE TITLE
drag and drop files from Files to OneNote does not work

### ISSUE THREAD

**Issue by Larsene** [files-community/Files#9519]
If you try to drag and drop files from your computer to OneNote, this one always show an error box saying Onenote can't paste the content of the clipboard.

If you do that from windows explorer, it works.

**Comment by gave92** [comment]
Which onenote app? The desktop app that comes with Office? Or the  "Onenote for Windows 10" app that comes preinstalled or in the Store?

**Comment by Larsene** [comment]
the one from windows 11, preinstalled from the store, formerly called "OneNote for Windows 10"

**Comment by yaichenbaum** [comment]
Drag and drop to UWP apps like OneNote isn't currently supported but it'll come back when we migrate to WinAppSDK.
