### ISSUE TITLE
Bug: Files is allowing forbidden folder names (CON, NUL, etc)

### ISSUE THREAD

**Issue by Araraura** [files-community/Files#9522]
### Description

It seems that Files doesn't prevent the user from creating files or folders with forbidden names that regular File Explorer would otherwise prevent.

It should prevent the user from creating files or folders named (in either lowercase or uppercase):

CON
PRN
AUX
NUL
COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, COM0
LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, LPT9, LPT0

![con01](https://user-images.githubusercontent.com/109022579/178141486-388201d3-2eba-4dca-92d9-7df22a4abeb5.png)
![con02](https://user-images.githubusercontent.com/109022579/178141487-8c959c80-62dc-478a-94fb-49e98799f0e1.png)

### Steps To Reproduce

1. Open Files
2. Go to a place where you can freely create folders or files
3. Create a folder or a file with a forbidden name (list in the description)
4. Open file explorer and create a folder or a file with the same name
5. File explorer will not allow the creation of a folder or a file with that name

### Steps to fix

- Display text when forbidden folders names are entered into the new folder modal
- Display error content dialog when users try renaming a folder to con

### Files Version

2.3.3.0

### Windows Version

Windows 11 21H2 22000.778

### Relevant Assets/Logs

n/a

**Comment by Araraura** [comment]
> It doesnt make the file/folder for me when using the names

I tried doing that in documents. I'm also using the sideload version of Files

**Comment by Josh65-2201** [comment]
Seem it only effects Windows 11. @yair100

**Comment by Josh-65** [comment]
Is this an issue in the preview version? https://files.community/download/preview

**Comment by Josh-65** [comment]
Asking @yaichenbaum for approval.

**Comment by sthivaios** [comment]
> Is this an issue in the preview version? https://files.community/download/preview

I would check it too but it doesn't even wanna install right now. It has been stuck at the same screen for over 5 minutes now.

![image](https://user-images.githubusercontent.com/109022579/195122489-061bf1c9-82b4-4f1b-a7c7-30f372738840.png)

**Comment by Araraura** [comment]
> > Is this an issue in the preview version? https://files.community/download/preview
> 
> I would check it too but it doesn't even wanna install right now. It has been stuck at the same screen for over 5 minutes now.
> 
> ![image](https://user-images.githubusercontent.com/109022579/195122489-061bf1c9-82b4-4f1b-a7c7-30f372738840.png)
> 
> (And it is definitely not a network issue from my side, because I just downloaded the installer, and I can ping google.com just fine.)

Maybe on a VM?

**Comment by sthivaios** [comment]
> > > Is this an issue in the preview version? https://files.community/download/preview
> > 
> > 
> > I would check it too but it doesn't even wanna install right now. It has been stuck at the same screen for over 5 minutes now.
> > ![image](https://user-images.githubusercontent.com/109022579/195122489-061bf1c9-82b4-4f1b-a7c7-30f372738840.png)
> > (And it is definitely not a network issue from my side, because I just downloaded the installer, and I can ping google.com just fine.)
> 
> Maybe on a VM?

Yes it is a VM.

I am reinstalling Windows right now, since there were not any important things on it. I just have it for reasons like that (testing, etc.).

When I reinstall it I will let you know about the CON, NUL, etc. thing.

**Comment by sthivaios** [comment]
Also, I think the issues' priority should be turned into "High".

Whoever has control over that, (probably @Josh-65) please make that "High" priority.

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval. Priority will be set when approved.

**Comment by sthivaios** [comment]
> Asking @yair100 for approval. Priority will be set when approved.

Thank you! :-)

**Comment by yaichenbaum** [comment]
> Also, I think the issues' priority should be turned into "High".

Priority is set based on how many users it affects, these aren't exactly common names for people to use.

**Comment by sthivaios** [comment]
> > Also, I think the issues' priority should be turned into "High".
> 
> Priority is set based on how many users it affects, these aren't exactly common names for people to use.

Oh, if you consider it that way, yes it does make sense to be set to "low".

**Comment by yaichenbaum** [comment]
I should point out that low priority doesn't mean it won't happen, in fact, most issues are set to low priority. This way contributors know that when an issue is marked as high or urgent, it's very high on the list.

**Comment by hez2010** [comment]
I don't see any problems here. Seems that the newer version of Windows has relaxed the restrictions around file/folder naming.
I can even use PowerShell to create a folder with the name `CON`.

![image](https://user-images.githubusercontent.com/14960345/195367478-bdf872a0-76a7-41f5-8a83-ef1a8d1c0477.png)

i.e. the Windows API allows to do so, and preventing users from creating such files and folders is just the behavior of explorer.

Since we are not explorer, I think we can close the issue as by designed. @yair100

**Comment by Josh-65** [comment]
It should properly be looked into if that names cause issue in windows. I remember some would don't know if it's changed

**Comment by Araraura** [comment]
> It should properly be looked into if those names cause issue in Windows. I remember some would don't know if it's changed. Also, the issue of deleting, moving or copying failing should be fixed if there kept.

I think it could mainly cause issues with legacy devices or configurations

**Comment by sthivaios** [comment]
> The issue is that you can't delete the items normally, we don't want users to end up with folders that they can't do anything with.

You can delete them fine through the normal explorer. It shows an error if you try to delete it through the Files app, but through the normal Windows Explorer, I was able to delete them all.

**Comment by sthivaios** [comment]
> > It should properly be looked into if those names cause issue in Windows. I remember some would don't know if it's changed. Also, the issue of deleting, moving or copying failing should be fixed if there kept.
> 
> I think it could mainly cause issues with legacy devices or configurations

It might.

**Comment by hecksmosis** [comment]
Is this still considered an issue?

**Comment by yaira2** [comment]
Yes
