### ISSUE TITLE
stl,gx and other 3d file extentions

### ISSUE THREAD

**Issue by elixxe** [files-community/Files#9523]
### What's the Problem?

with basic windows file explorer i can see stl and gx previews with the models, it would be cool to have that on files too

### Solution/Idea

add previews

### Alternatives

idk

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.3.0.0

### Windows Version

windows11

### Comments

just a useful thing

**Comment by gave92** [comment]
Are you referring to thumbnails or the right preview pane? What program do you have to show the preview/to open those files?

**Comment by elixxe** [comment]
i'm talking about the medium icon thumbnail, i use flashprint and the previews show in the default files app

**Comment by elixxe** [comment]
[https://i.imgur.com/QPkVbkv.png](url), [https://i.imgur.com/eq3bMjh.png](url)

**Comment by Josh65-2201** [comment]
@yair100

**Comment by yaichenbaum** [comment]
I can't view those images, can you upload directly to Github?

**Comment by Josh-65** [comment]
They just that Files has the default open program as the icon and File explorer displays the actual model in the file.

**Comment by Josh-65** [comment]
Merging with #2582
