### ISSUE TITLE
Files won't allow me to enable "Set files as default File Manager" 

### ISSUE THREAD

**Issue by Kxsumi** [files-community/Files#9524]
### Description

I go to select the Off > On button, but when I click it, it will immediately go back to Off. 

### Steps To Reproduce

Open Settings
Go to Experimental
Find "Set files as default File Manager"
Select the button

### Expected behavior

I believe I am meant to get a pop-up but I do not.

### Files Version

2.3.0.0

### Windows Version

21H2

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/96434998/178039996-5f63004e-6201-442f-b7b6-b0ecca339efa.png)

https://user-images.githubusercontent.com/96434998/178040397-df29685e-8b71-44c9-ad06-df250b3a2f1f.mp4

**Comment by gave92** [comment]
Please upload the app's debug logs from Settings > About > Open log location (the two .log files)

**Comment by Kxsumi** [comment]
[debug_fulltrust.log](https://github.com/files-community/Files/files/9075027/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/9075029/debug.log)

**Comment by gave92** [comment]
Could you check the following?

- Does this path exist?
"%LocalAppData%\Microsoft\WindowsApps\files.exe"
- Does this path exist?
"%LocalAppData%\Files\FilesLauncher.exe"

Also, could you post a screenshot of the contents of this folder? %LocalAppData%\Packages\Files_1y0xx7n9077q4\LocalState\FilesOpenDialog\

**Comment by gave92** [comment]
If you wish you may try the "manual" method:
- Download this zip: [SetFilesAsDefault.zip](https://github.com/files-community/Files/files/8403524/SetFilesAsDefault.zip)
- Unpack it in `%LocalAppData%\Files` (you'll need to create the folder)
- Run "SetFilesAsDefault.reg"

**Comment by Kxsumi** [comment]
%LocalAppData%\Microsoft\WindowsApps\files.exe
Path Exists.
%LocalAppData%\Files\FilesLauncher.exe
Path does not exist
![Screenshot (84)](https://user-images.githubusercontent.com/96434998/178093366-5acf0ccc-3e49-4f36-a840-b41f8a8418a4.png)
.

**Comment by Kxsumi** [comment]
Seems like the manual method worked.
