### ISSUE TITLE
Preview won't refresh with new selected image file

### ISSUE THREAD

**Issue by TheFlyingCelt** [files-community/Files#9525]
### Description

When enabling preview, at first click it sometimes show the content of an image, but when selecting another image the preview won't show the new content but it will still show the content of the first image selected.

### Steps To Reproduce

turn on preview in column view (might not work in other views as well. I didn't try)

### Expected behavior

it should show the preview for the image selected

### Files Version

Versione 2.3.0.0 OS Version: 10.0.22622.290

### Windows Version

Windows 11 latest update on July 8th 2022

### Relevant Assets/Logs

nothing to show

**Comment by Josh-65** [comment]
Merging with #9196.
