### ISSUE TITLE
Cannot see .lnk (Shortcut files) Am I missing something?

### ISSUE THREAD

**Issue by artbyjcm** [files-community/Files#9526]
Using v2.3, looked through settings. Did a search on issues, and can find that people somehow do see them. I looked through many posts, and it certainly seems like people can see them. Is there somehow a setting I am missing, or something in my windows settings that is preventing this from showing? Some admin settings I am overlooking?

If not, this would be a bug.

**Comment by Josh-65** [comment]
They dont show on network drives but should everywere else
