### ISSUE TITLE
Is it possible to use Files on Linux, specifically on the Ubuntu linux distribution?

### ISSUE THREAD

**Issue by rodriguezbrown** [files-community/Files#9527]
### What's the Problem?

I would like to use the Files software on Linux

### Solution/Idea

This is more of a question than a feature request

### Alternatives

None

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Windows Version

Windows 10, Distro Ubuntu 22.2

**Comment by hez2010** [comment]
Files is built on UWP(WinRT) platform and it's not possible to run Files on Linux distros, neither with the help of wine.

**Comment by rodriguezbrown** [comment]
@hez2010 Hi! How are you? Thank you for feedback... I love Files and wanted to know how to port to Linux.

**Comment by hez2010** [comment]
I'm not sure but it might be doable with the help of [uno platform](https://platform.uno/).

**Comment by Josh65-2201** [comment]
Reminding @yair100 to respond
