### ISSUE TITLE
Laggin interface, sometimes it freezes or become unresponsive for a little time

### ISSUE THREAD

**Issue by zaknafein99** [files-community/Files#9530]
### Description

When I change folders or copy a file in a double pane tab, sometimes Files become somewhat unresponsive or it doesn't change folders

### Expected behavior

For example, I've been using Onecommander, similar look & feel and functionality, but it is much more snappy and responsive. I have a desktop PC, 8gb of RAM, 6-core AMD FX6300, nVidia gt 740

### Files Version

Version: 2.3.0.0

### Windows Version

Windows 10 21H2

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/9077366/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/9077367/debug.log)

**Comment by gave92** [comment]
Merging with #4180

**Comment by yair100** [comment]
@zaknafein99 we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
