### ISSUE TITLE
Cut/Paste not working

### ISSUE THREAD

**Issue by MintHawk** [files-community/Files#9532]
First of all, congrats for the work you've been doing.
However, I encounter the same problem when cutting and then pasting a file from one folder to another.
Specifically, I cut an .srt file and then try to paste it in another folder so as to rename it after the video's name.
Each and every time, although it says that the operation has been performed, it has not.
It is rather irritating and, to be honest, I uninstalled Files since I cannot perform this simple task reliably.
Please fix the bug.
My system runs on Win11 and the Files version used is 2.3.1 and 2.3.3.

**Comment by Josh-65** [comment]
You will need to upload the logs files directly to github. You can get them in files settings > about > open log folder.

**Comment by MintHawk** [comment]
[debug_fulltrust.log](https://github.com/files-community/Files/files/9078963/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/9078964/debug.log)

**Comment by Josh-65** [comment]
Where when you copying from and too. A local drive, external device like a phone, network drive, FTP server?

**Comment by Josh65-2201** [comment]
@yair100

**Comment by yaichenbaum** [comment]
I can't reproduce this, is it posible the item is open?

**Comment by MintHawk** [comment]
If you mean if it's open in another application when I try to move it, no, it is not.

**Comment by Josh-65** [comment]
Merging with #8972
