### ISSUE TITLE
Change view for all folders at once

### ISSUE THREAD

**Issue by SirEthanator** [files-community/Files#9533]
### What's the Problem?

I like the "tile" view mode personally, but I couldn't seem to find a way to change all folders to this view.

### Solution/Idea

A way to set the default folder view would be nice.

### Alternatives

Another possible solution would be something that windows file explorer has. You can set the view settings for the current folder to apply to all folders.

### Files Version

Version: 2.3.0.0

### Windows Version

Windows 11 21H2 22000.778

**Comment by gave92** [comment]
You can turn off "Enable individual preferences for folders" under settings > preferences.
