### ISSUE TITLE
Black background behind folder icon

### ISSUE THREAD

**Issue by SirEthanator** [files-community/Files#9534]
### Description

Sometimes there will be a black background behind the folder icon.
![Screenshot 2022-07-10 145108](https://user-images.githubusercontent.com/109008777/178129293-c9d209e6-fbc6-4e09-b96b-2b68e00b4a44.png)
 

### Steps To Reproduce

I believe it happens when something is downloaded and placed in that folder.

### Expected behavior

It should just have nothing behind the folder icon but instead, it has a black square behind it.

### Files Version

2.3.0.0

### Windows Version

Windows 11 21H2 22000.778

### Relevant Assets/Logs

![Screenshot 2022-07-10 145108](https://user-images.githubusercontent.com/109008777/178129293-c9d209e6-fbc6-4e09-b96b-2b68e00b4a44.png)

**Comment by gave92** [comment]
Merging with #6373
