### ISSUE TITLE
App crashed while extracting100 images a folder

### ISSUE THREAD

**Issue by JaynouOliver** [files-community/Files#9535]
### Description

My computer is not at all slow, it is a Ryzen 7 4800H, 32GB Ram and 2TB of SSD along with RTX 3050.

### Steps To Reproduce

Just try to extract a large amount of images

### Expected behavior

The app is crashing

### Files Version

2.3.0.0

### Windows Version

Version Windows 11, 22H2 

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9078711/debug.log)

**Comment by gave92** [comment]
Were you selecting files via mouse drag when it crashed?

**Comment by JaynouOliver** [comment]
yes

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
We're redoing the extract/zip feature so I'm going to mark this as completed.
