### ISSUE TITLE
Failed To Rename Network Map

### ISSUE THREAD

**Issue by sthivaios** [files-community/Files#9536]
### Description

So, I have mapped a network share as a drive. If you right click on it and select properties through this app, and try to rename it through there because there is no rename option under the right click menu, UAC will pop up and ask for the admin password as Power Shell. When I entered that password, and clicked YES, it just didn't rename the folder. Every time I tried it, I could not rename it. I ended up renaming it through the normal windows explorer program.

### Steps To Reproduce

1. Right click on a mapped network drive.
2. Select properties.
3. Rename the folder through the window that appears.
4. Click OK on that window.
5. UAC will open. Type the administrator password and click YES.
6. The network drive is still not renamed.

### Expected behavior

I was expecting it to just rename the network drive after I clicked OK, or even better to have a rename option when right clicking on the drive.

### Files Version

Version: 2.3.0.0 OS Version: 10.0.22000.318

### Windows Version

Windows 11 21H2 22000.318

### Relevant Assets/Logs

![01](https://user-images.githubusercontent.com/109022579/178141095-a765ab94-03a1-4cbc-b901-26f989d774aa.png)
![02](https://user-images.githubusercontent.com/109022579/178141098-7d399716-d9c1-4e58-8a9b-08eed9f4f07a.png)
![03](https://user-images.githubusercontent.com/109022579/178141099-7ba7e429-f0f7-432c-955f-571ac600b5f9.png)
![04](https://user-images.githubusercontent.com/109022579/178141101-18bd2cab-bd8e-49ad-8a3e-6852ded9b62e.png)
![05](https://user-images.githubusercontent.com/109022579/178141102-98e96275-8b7c-446a-bba7-83a647a2ca3c.png)
![06](https://user-images.githubusercontent.com/109022579/178141103-f74a5f57-1542-4e2d-b72b-7d5bf738f672.png)

**Comment by Josh-65** [comment]
Merging with #6154
