### ISSUE TITLE
TAGs are Great but... and Dual Pane little and easy improvement

### ISSUE THREAD

**Issue by CauZion** [files-community/Files#9539]
### What's the Problem?

Tags are awesome, but 
1) We can't create our own tags (I have edited them already)

2) after selecting a tag, clear all files/folders tagged. We may want to change tags categories and/or use tags as temporary tags, to work with a group of files, so we may want to clear the tags afterward.

3) ISSUE: sometimes, after tagging files or folders, the tags are not shown on other views. Like if they were not tagged.

4) DUAL PANE - we can't quickly tell which pane is active.

### Solution/Idea

1) we could be able to create tags, 
2) allow us to clean all files with a given tag
3) correct the issue

4) Dual-pane: just change the active color background or add a color line on the top of the active pane.
4a)It's so common we change the view or something else of a pane when we actually think we are changing the other instead.

### Alternatives

A possible alternative for item 4 is in the solution idea.

### Priorities

Users will be able to increase their productivity and also not lose time with misactions.

### Comments

A really great app

**Comment by yaichenbaum** [comment]
Merging with #5848

**Comment by yaichenbaum** [comment]
> DUAL PANE - we can't quickly tell which pane is active.

There should be a color border for the active pane, can you check if this is visible?

**Comment by Josh-65** [comment]
> 1. We can't create our own tags

You can add more entries to the file just change the UUID to somthing not used on the others

**Comment by Josh-65** [comment]
You can accses the tag on the sidebar then select all and click the tag assieged to it. that removes them

**Comment by CauZion** [comment]
OK, I got it.  Another issue, I’m trying to copy a folder from Onedrive to a USB drive and the app shows “Failed to copy” on that upper left icon. I can’t copy right now. Weird because I first copied 1 file and it worked, then all other attempts to copy something from the same source to the same destination didn’t work. Carlos Sent from Mail for Windows From: Josh-65Sent: Monday, July 11, 2022 1:14 PMTo: files-community/FilesCc: CauZion; AuthorSubject: Re: [files-community/Files] TAGs are Great but... and Dual Pane little and easy improvement (Issue #9539) You can accses the tag on the sidebar then select all and click the tag assieged to it. that removes them—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by CauZion** [comment]
OK,  The only not addressed item is about cleaning all the tagged files to a given tag, This will help a lot the use of temporary tags, Thank you again, Carlos Sent from Mail for Windows From: Josh-65Sent: Monday, July 11, 2022 1:40 AMTo: files-community/FilesCc: CauZion; AuthorSubject: Re: [files-community/Files] TAGs are Great but... and Dual Pane little and easy improvement (Issue #9539) We can't create our own tagsYou can add more entries to the file just change the UUID to somthing not used on the others—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by CauZion** [comment]
Oohh Yes, actually is just a line on the very bottom. Because I use a super large monitor, I keep my yes focusing on the upper half of the monitor and had not sawn the line. I believe, it would be better the line in the top of the windows, but just my opinion. Thank you again, Carlos Sent from Mail for Windows From: Yair yair100: Monday, July 11, 2022 1:13 AMTo: files-community/FilesCc: CauZion; AuthorSubject: Re: [files-community/Files] TAGs are Great but... and Dual Pane little and easy improvement (Issue #9539) DUAL PANE - we can't quickly tell which pane is active.There should be a color border for the active pane, can you check if this is visible?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
