### ISSUE TITLE
Window stays focussed after opening certain files

### ISSUE THREAD

**Issue by quantumwebco** [files-community/Files#9542]
### Description

When opening some files the opened window loses focus and the Files window refocusses

Can reproduce with .bat files also .crt, will try and compile a list of other files it happens with

### Steps To Reproduce

Double click or hit enter on a crt or bat file
Start typing something, hitting enter, whatever
Notice that the opened window has lost focus and Files is now focussed and your keyboard interaction is with files not the recently opened window

### Expected behavior

Opened windows stay focussed

### Files Version

2.3.0.0

### Windows Version

Windows 11 22H2 22621.169

### Relevant Assets/Logs

too long to upload

**Comment by gave92** [comment]
Could you check if the opened window ever gets focus? Perhaps it's on the foreground but not focused.

**Comment by quantumwebco** [comment]
This is still happening for me, how do I check if it ever gets focus? If I double click a .bat file the command prompt opens in the foreground but the window isn't focussed and when I start to type it types in the files window instead of the window in the foreground as expected

**Comment by gave92** [comment]
Thanks for the update. There's a know bug for which opened apps sometimes appear behind files or they appear in front but unfocused -> #5291
Atm you need to click on the opened window to give it focus.
