### ISSUE TITLE
Option to turn off tooltips

### ISSUE THREAD

**Issue by joshcoast** [files-community/Files#9543]
### What's the Problem?

Tooltip gets in the way of the file name above and doesn't offer useful information. 
![image](https://user-images.githubusercontent.com/1174626/178287973-90681c1c-b6db-4db8-85c0-513ca63eca60.png)

### Solution/Idea

Add an option to turn off tooltips. Windows File Explorer has a tooltip feature too but offers an option to disable it. I'd like to see that option on this app as well. 

### Alternatives

You could remove this tooltip feature, but I imagine someone must find it useful. Or you could not show the tooltip if it is only going to repeat the file name that your cursor is over. That would help a little. 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end-users to accomplish disabling the tool tips | Should |

![image](https://user-images.githubusercontent.com/1174626/178288374-1b7e806a-44f8-4eae-ad84-906424d355ea.png)

### Files Version

Version: 2.3.3.0

### Windows Version

Windows 10 Enterprise 10.0.19042

### Comments

Hope this is something you will consider developing. This is a beautiful app, it really makes using Windows OS tolerable. 

Thank you!

**Comment by yaichenbaum** [comment]
@joshcoast you can hide the tooltips by moving the mouse away from the items.
