### ISSUE TITLE
Menu Options Are Grayed Out Even Though They Are Valid

### ISSUE THREAD

**Issue by cachandlerdev** [files-community/Files#9545]
### Description

UI menu item elements are grayed out, as if they are disabled or cannot be clicked at this time, despite being actions that can be performed at this time. For example, all options in the top right side of the screen (i.e. Selection, Sort, Layout, See More) show their contents as grayed out despite being focused.

### Steps To Reproduce

1. Open Files.
2. Navigate to a folder.
3. Right-click on a folder or file.
4. Click on the Selection/Sort/Layout/See More button.
5. (See grayed out options). [BUG]
6. Click off the element.
7. Right-click on a random portion of the screen (but not on a file/folder).
8. (See grayed out context menu items). [BUG]

### Expected behavior

The menu options would only appear grayed out when they are actually unavailable, and therefore would not be grayed out in this instance.

### Files Version

Version: 2.3.3.0 OS Version: 10.0.19044.1766

### Windows Version

Windows 10 21H2 19044.1766

### Relevant Assets/Logs

![Options Grayed Out](https://user-images.githubusercontent.com/70250943/178369955-54e6a727-e13d-497e-b689-1ac34947743f.png)

![Context Menu Options Grayed Out](https://user-images.githubusercontent.com/70250943/178370755-1cd03594-c550-47ea-a7f8-31aea952520f.png)

**Comment by yaichenbaum** [comment]
This is an issue with WinUI and Windows 10 that we don't have control over. The good news is that Microsoft fixed the issue in Windows 11.
