### ISSUE TITLE
Feature: Add chevron to folders in column layout

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#9546]
### Solution/Idea

![image](https://user-images.githubusercontent.com/39923744/178402959-bd0c6814-8687-4f17-ad5f-d791c71ca8e7.png)

### Alternatives

NA

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Add chevron to folders in the column layout | Must |

**Comment by cinqmilleans** [comment]
How should cloud icons be managed? Should they be aligned vertically or positioned to the right?

![FolderChevron1](https://user-images.githubusercontent.com/46631671/178499979-d1cb868d-4642-4e76-b7d7-4c759cb8c2f2.png)
![FolderChevron2](https://user-images.githubusercontent.com/46631671/178499981-2a37c7d2-e63e-4bd1-901e-0a9601f423d1.png)

**Comment by yaichenbaum** [comment]
That's a good question, we could hide the status for folders and only show it on the files but that doesn't seem like the best solution. Let's do it like the first screenshot for now and we can always revisit this later on.

**Comment by yaichenbaum** [comment]
@cinqmilleans I gave this some more thought and I think we should hide the status in the column layout. We can still show it in a teaching tip, but I no longer think that it has a place in the list.
