### ISSUE TITLE
Feature: Add option to create new txt files

### ISSUE THREAD

**Issue by Joonel** [files-community/Files#9548]
### What's the Problem?

'New' => 'Text Document' option is missing:

### Requirements 
- Display shell option for creating new txt files

**Comment by Josh-65** [comment]
You can use the File option and add a name with the .txt or other extention you would like to use.

**Comment by Joonel** [comment]
@Josh-65 I can do like this with any others file extensions, but that menu was created for main extensions like .txt

**Comment by Josh-65** [comment]
I know that why i have left the request open. Just letting you know so you could make one.

**Comment by yaichenbaum** [comment]
Notepad does some weird stuff, so it's not detected as a shell item.

**Comment by Joonel** [comment]
Uh, guys, that's Notepad (or Windows) issue, so no complains for the Files. The option is missing in the Explorer too.

**Comment by Joonel** [comment]
I've restarted my PC and "New Text document" option has appeared in the Explorer... But not in the Files.
