### ISSUE TITLE
Remove effect theme.

### ISSUE THREAD

**Issue by DirtyJohny** [files-community/Files#9551]
### Description

Good day. I love so much your app, but I cry when theme which use remove if I swich another window or click empty place. If you fix it on next rev this application I will so happy. Thank you for your work its awesome app. Good luck for your development and we loving you)

### Steps To Reproduce

Theme effect disappears when switching between windows. I use theme Glass.

### Expected behavior

Permanent theme effect.

### Files Version

2.3.3.0

### Windows Version

Windows 11 Pro 21H2

### Relevant Assets/Logs

https://user-images.githubusercontent.com/73193639/178598969-a8ac1905-7c2e-42d7-8a5c-b7467e3e0abf.mp4

**Comment by gave92** [comment]
This behavior is done by the OS. We can't do much about it.
