### ISSUE TITLE
back to default

### ISSUE THREAD

**Issue by qazzaq666** [files-community/Files#9557]
### What's the Problem?

I have been using "Files" for a long time, and now I would like to change it to default explorer, but I installed "Files" by default, I want to ask if it is possible to return default explorer without reinstalling windows? 
(I can go a long way to recovery)

### Solution/Idea

Add the ability to revert back to the default windows explorer even if the user has set "Files" as default

### Alternatives

Help me

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Версия: 2.3.3.0

### Windows Version

Windows 10 Pro 21H2 19044.1806

**Comment by Josh-65** [comment]
You canturn off the toggle in Files settings > experimental.
if you have uninstalled files then open this https://raw.githubusercontent.com/files-community/Files/main/src/Files.FullTrust/Assets/FilesOpenDialog/UnsetFilesAsDefault.reg > right click on the opened page > Save as > set the type to "all files" > remove the .txt from the end of the name > open the file > allow admin when you get the prompt.

**Comment by grecdel** [comment]
@Josh-65 Guy you can't imagine how you save me XD thanks a lot _/\_
