### ISSUE TITLE
Feature: Add support for key remapping

### ISSUE THREAD

**Issue by yair100** [files-community/Files#9559]
### Solution/Idea

As Files gets more advanced and the number of shortcuts keeps growing, it'll be useful to allow keyboard remapping to allow users to configure shortcuts to work the way they like it.

![image](https://github.com/files-community/Files/assets/39923744/f9e173ce-c229-4ee3-b08c-60f695f186c6)

### Requirement

This proposal will add a settings page called "Actions"
This page will contain a list of actions
This proposal will allow configuring the shortcut or gesture to configure each action
This proposal will allow users to reset all actions to the default

### Files Version

v2.3

**Comment by cinqmilleans** [comment]
Here is a custom KeyPicker that I could integrate into Files. What do you think?

https://user-images.githubusercontent.com/46631671/179416381-91b554f2-69b4-4a67-90ec-a1b8e063ede1.mp4

**Comment by yaichenbaum** [comment]
Something like that, I need to create the design but you should be able to work on the functionality in the meantime.

**Comment by yaira2** [comment]
Remapping actions is already supported if you manually edit the settings file
1. Open Settings > Advanced > Edit settings file
2. Right click the system tray icon for Files and click "Quit"
3. Go back to the settings file and find the section for "Actions"
4. The list of available actions can be found [here](https://github.com/files-community/Files/blob/main/docs/rich-commands.md)

Here is an example remapping the copy action to `ctrl` + `j`
```json
"Actions": {
    "CopyItem": "ctrl+j"
 },
```

**Comment by 0x5bfa** [comment]
![Image](https://github.com/files-community/Files/assets/62196528/9a0c6f9d-c0a6-4af2-b032-93c36f3b422b)

A page would be great? Working on it.

**Comment by yaira2** [comment]
@0x5bfa nice! I would suggest calling the page "Actions" as it's supposed to be more than just keyboard shortcuts.

**Comment by yaira2** [comment]
The requirements listed above are still accurate but I don't have any specific design in mind for the UI.

**Comment by yaira2** [comment]
A big shoutout to @0x5bfa for completing this large task 🎉

**Comment by yaira2** [comment]
> This proposal will allow configuring the shortcut or gesture to configure each action

Custom gestures are out of scope for this task, but we'll continue exploring to see if there is a path forward for them.
