### ISSUE TITLE
Feature: Display modal when drive cannot be ejected

### ISSUE THREAD

**Issue by jdeloshoyos** [files-community/Files#9560]
### Requirements

- Show what app / process is using a drive upon eject (or through a context menu option)
- Be able to close or switch to that app
- If it can't find it, try and show the number of hidden processes using it

### Files Version

2.3.11.0

### Windows Version

Windows 11 21H2 build 22000.795

**Comment by jdeloshoyos** [comment]
Not completely sure about the priorities... Perhaps showing the files is also a must?

**Comment by yaichenbaum** [comment]
> Not completely sure about the priorities... Perhaps showing the files is also a must?

I think the process is enough for the user to be able to figure out what's preventing them from ejecting the drive.

**Comment by Josh-65** [comment]
@jdeloshoyos is this still an issue in 2.3.11 (stable release)?

**Comment by jdeloshoyos** [comment]
> @jdeloshoyos is this still an issue in 2.3.11 (stable release)?

Yes, it still is. This is the dialog that appears when trying to eject a drive with a Excel file open:

![image](https://user-images.githubusercontent.com/27691677/189157476-c7a061a7-6c71-4dfd-af84-7b5372efeb8f.png)

No hint of the program preventing the drive ejection. This is 2.3.11.0 (installed from Microsoft Store).

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaira2** [comment]
Merging with #11091

**Comment by hecksmosis** [comment]
Oh no

**Comment by hecksmosis** [comment]
That was already closed and merged into this

**Comment by hecksmosis** [comment]
@yair100
