### ISSUE TITLE
Bug: Restore option is missing from recycle bin

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#9561]
### Description

Right clicking in the recycle bin there only copy, delete and properties.

**Requirements**
- selecting an item in recycle bin adds a "Restore" button in the toolbar
- selecting multiple items adds a "Restore" button to the toolbar
- if no items are selected, there should toolbar button that says "Restore all items"
- right clicking an item/items adds a "Restore" option to the context menu
- right clicking in a blank space adds a "Restore all items" option to the context menu

### Files Version

2.3.1.0

### Windows Version

10.0.19043.1806

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9105826/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9105827/debug_fulltrust.log)

**Comment by QuaintMako** [comment]
I have a fix in the making for this one, I have two questions about it though:

1- Do we want to have the two actions in the "base menu", following each other? Or do we want to regroup them in a submenu, like on the picture below:
![9561_POC](https://user-images.githubusercontent.com/110472580/185432523-ac684e94-cc99-4dc6-8ffb-e754b11e5a88.png)

2- We cannot use the Restore action on the sidebar when right clicking on the recycle bin icon. Haven't found any issue related to this, is it a normal behavior? Or do we want to have it here as well?

**Comment by Josh-65** [comment]
The option should appear at the base menu when right clicking one or more items in the recycle bin.

**Comment by QuaintMako** [comment]
Is there a known process to add Glyphs to the font? I need to add a new icon for restoring the recycle bin.

**Comment by yaichenbaum** [comment]
> Is there a known process to add Glyphs to the font? I need to add a new icon for restoring the recycle bin. I need to add one icon for Restore Action and we're good to good.

I think we can use whatever File Explorer uses

**Comment by Newguru-1** [comment]
Regarding Recycle Bin options, why not enable these contextual options on the icon´s taskbar jumplist (as it happens on file explorer's taskbar jumplist).
