### ISSUE TITLE
Bug: Original date and path is missing from Recycle Bin

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#9562]
### Description

Original path and the date delete section are always blank.

### Steps To Reproduce

1. Open recycle bin
2. See empty date and path columns

**Requirements**
- Fix issue where the columns are blank

### Files Version

2.3.11.0

### Windows Version

10.0.19043.1899

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9105834/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9105835/debug_fulltrust.log)

**Comment by QuaintMako** [comment]
Could not reproduce it. I'm on version Version: 2.3.6.0 -- OS Version: 10.0.19043.1889.

Can anyone give it a shot?

**Comment by puppetsw** [comment]
Can confirm on 2.3.37 Preview. At least partially, see attached image.


![Image](https://user-images.githubusercontent.com/79826944/193167014-10e353fb-bcfd-4c92-bbf9-c9558a538005.png)
