### ISSUE TITLE
Make manually resized column widths stick in Details view.

### ISSUE THREAD

**Issue by RKinMTL** [files-community/Files#9565]
### What's the Problem?

Make manually resized column widths stick in Details view. I have issued this feature request and it has been closed despite NOT having been addressed (#9558).

### Solution/Idea

Make manually resized column widths stick in Details view. I have issued this feature request and it has been closed despite NOT having been addressed.

### Alternatives

Make the "resize widths to fit contents" option an active setting that applies to directories as they are accessed. 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by Josh-65** [comment]
I have reopen the first issue you maded
