### ISSUE TITLE
Window Goes Blank If the Network Folder is Still Loading

### ISSUE THREAD

**Issue by Naolador** [files-community/Files#9566]
### Description

If the Network folder is still fetching the list from the local network, it makes the whole window in a blank state even if you navigate to other drives/folders.

 To recover from this, you will have to wait till the load has been completed in the background. Alternatively, close the tab or the window, then reopen it.

### Steps To Reproduce

1. Open Files
2. From the navigation bar, click Network drives -> Network
3. The main panel turns to blank due to it's loading the network devices from the network.
4. Now navigate to any other disks/folders, it's still showing a blank window.
5. Once the device list has been retrieved in the network. Everything is back to normal.

### Expected behavior

Contents should show on step 4.

### Files Version

Version: 2.3.3.0 OS Version: 10.0.22000.795

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎5/‎12/‎2021 OS build	22000.795 Experience	Windows Feature Experience Pack 1000.22000.795.0

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/11061451/179184541-46252b1f-0af7-4295-94da-4880bd526d8b.png)
![image](https://user-images.githubusercontent.com/11061451/179185446-fa587d7e-da4a-4c71-98d2-f990a0bd7cb5.png)

Now, wait a few minutes, till the network device list is loaded
![image](https://user-images.githubusercontent.com/11061451/179185882-0bbb252f-e0e0-4265-a865-d0956786228e.png)

Everything is back to normal
![image](https://user-images.githubusercontent.com/11061451/179186046-513ce318-f843-4eab-ae14-c77138f3495c.png)

**Comment by onikyannn** [comment]
Сan confirm this issue. I don't have network drives, but have a few cloud drives and WSL. The behavior is similar.

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by Naolador** [comment]
@yair100 I'm using the App downloaded from the Windows store, and it's still the same. 
The preview version is behaving the same.

**Comment by yaira2** [comment]
Can you share a screen recording?

**Comment by Naolador** [comment]
@yair100 I have uploaded to Youtube [Youtube ](https://youtu.be/6YEVDk9DEp0)

**Comment by yaira2** [comment]
You can upload directly to GitHub

**Comment by Naolador** [comment]
Video attached here, thanks!
https://user-images.githubusercontent.com/11061451/216509505-d467ade0-a59e-4b86-822f-74889e5c15a4.mp4

**Comment by Josh-65** [comment]
This seem to be the same issue as #7259 just with the network folder.

**Comment by yaira2** [comment]
@Josh-65 can you edit #7259 to include network folders as well?
