### ISSUE TITLE
QuickLook doesn't work in 2.3.3.0

### ISSUE THREAD

**Issue by AlamMancera** [files-community/Files#9568]
### Description

The open source app (QuickLook) that serves for shows the preview vist for all files, has stopped working in this new version (2.3.3).
Please, enabled other once this function in "Files". It's very necesary and productive.

### Expected behavior

That when pressing the space bar from keyboard, QuickLook open the preview of the file.

### Files Version

Version: 2.3.3.0

### Windows Version

Windows 11 21H2 22000.795

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/9124837/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/9124838/debug.log)

**Comment by yaichenbaum** [comment]
As per the log files, QuickLook is working correctly on your device, can you check if the app is opening in the background?
