### ISSUE TITLE
Add Pin To Start in the context menu

### ISSUE THREAD

**Issue by AhmadHddad** [files-community/Files#9569]
### What's the Problem?

Add Pin to the start option in the context menu like old one.
![image](https://user-images.githubusercontent.com/33379511/179353429-3d1925e7-17e2-4b82-b3bb-1ffb9edb7774.png)

### Solution/Idea

Adding the pin to start option

### Alternatives

using the old file explorer

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.3.3.0 

### Windows Version

OS Version: 10.0.19044.1826

**Comment by gave92** [comment]
#9374
