### ISSUE TITLE
设为默认资源管理器后回收站无法加载

### ISSUE THREAD

**Issue by Tback1** [files-community/Files#9572]
### Description

版本: 2.3.3.0
OS Version: 10.0.19044.1766

Files不作为默认资源管理器时，回收站打开后立刻能读取并显示已删除的文件和文件夹。
![image](https://user-images.githubusercontent.com/8872546/179411053-5c65cb00-59c7-43c5-978b-db27a655d43f.png)

### Steps To Reproduce

设为默认资源管理器后回收站无法加载
1.设置为默认浏览器
2.重启files
3.打开回收站或在侧栏选择回收站。卡顿很久无法读取到回收站。隔了大概一分钟，弹出一个 "驱动器已弹出 NotAFolder"

![image](https://user-images.githubusercontent.com/8872546/179411135-55d99f3f-94ba-4d66-903b-32394ffe3dad.png)

### Expected behavior

正常显示回收站内的文件

### Files Version

版本: 2.3.3.0

### Windows Version

OS Version: 10.0.19044.1766

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9128075/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9128078/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #9573
