### ISSUE TITLE
Bug: Sorting by date ignores the option to list files alongside folders

### ISSUE THREAD

**Issue by CherenTheCat** [files-community/Files#9574]
### What's the Problem?

When using the default File Manager, in my Downloads folder, Files and Folders are sorted separately, with folders being listed after files. In Files, Folders seem to always be listed first if the option to sort them together is toggled off.

### Solution/Idea

Add a sorting option, alongside "List and Sort Directories alongside Files", to move folders to after files, instead of prior. This should primarily be per-folder, with a potential global option. 

### Alternatives

I don't know any other simple way to implement this .

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.3.3.0

### Windows Version

Windows 11 21H2 22000.795

**Comment by CherenTheCat** [comment]
It doesn't change the position of the folders, they still sort to the top.

[Cheren Alexander - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=1n9ubr)	[1n9ubr]

On July 19, 2022 at 16:33 GMT, Yair Aichenbaum ***@***.***> wrote:

What happens if you change the sort direction?

**Comment by CherenTheCat** [comment]
Ascending Sort
![image](https://files.catbox.moe/cor81p.png)
Descending Sort
![image](https://user-images.githubusercontent.com/18288725/179866760-4d9746c8-c963-4acf-ba6c-96a73faee73c.png)

**Comment by yaichenbaum** [comment]
Looks like a bug, I edited the title to reflect this.

**Comment by ferrariofilippo** [comment]
Should it work like this?

https://github.com/files-community/Files/assets/102259289/6317c714-60a5-4d38-b618-8723e18d08dd

**Comment by yaira2** [comment]
When the option to sort files and folder together is turned on, the expectation is to no longer separate the two.

**Comment by yaira2** [comment]
@ferrariofilippo it works as expected when sorting by name, the issue is when you try sorting by date.

**Comment by ferrariofilippo** [comment]
![image](https://github.com/files-community/Files/assets/102259289/3c3684ce-05a1-41ea-9192-cd9dc7ccd8da)

Seems to work event then

**Comment by yaira2** [comment]
Looks like it was fixed, thanks for checking.
