### ISSUE TITLE
OneDrive flyout like File Explorer

### ISSUE THREAD

**Issue by pratyakshm** [files-community/Files#9582]
### What's the Problem?

N.A.

### Solution/Idea

Add OneDrive flyouts like the one in File Explorer:

![image](https://user-images.githubusercontent.com/54220235/179696277-eacf20d4-e6fe-4fd4-a6c9-f99adaf4a0b2.png)

Just like File Explorer, this may also be accessible through the top right corner of the window. 

The flyout must show if OneDrive is open inside File Explorer.

The flyout has been immensely helpful for me to read my quota, and I miss that feature in Files.

### Alternatives

N.A.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow users to see their OneDrive quota via the OneDrive flyout when a OneDrive location is  open in Files | Must |

### Files Version

Version: 2.3.3.0

### Windows Version

Windows 11 22H2 22622.290

**Comment by DiabeticAnna** [comment]
Would love to see something similar for iCloud or Google Drive

**Comment by yaichenbaum** [comment]
This is resolved in the latest preview build. https://files.community/download/preview
![image](https://user-images.githubusercontent.com/39923744/195707430-23f4586e-aee1-4fde-a70d-50908c713651.png)

**Comment by pratyakshm** [comment]
Nice, this is good! Thanks Yair!
