### ISSUE TITLE
Feature: Display multiple tags in the tags column

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#9584]
We recently added support for applying multiple tags to the same file. The problem is that this isn't properly reflected in the details layout

### Requirements
Use ItemsRepeater or similar control to display multiple tags in the column.

**Comment by ferrariofilippo** [comment]
There's an issue involving #11216. Tags column should have a margin on the right

![2](https://user-images.githubusercontent.com/102259289/217659987-0b2302d0-8580-4bc9-8271-5491fe74ea09.png)

**Comment by yaira2** [comment]
Can you open a PR?

**Comment by yaira2** [comment]
I'll fix this

**Comment by ferrariofilippo** [comment]
I think this can be closed
