### ISSUE TITLE
Turn tags on by default and remove setting to turn it off

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#9586]
We're getting close to the point where tags can leave preview and we can remove the setting to disable it. We should hold off on this a bit longer but I'm opening this issue to keep track.

**Comment by ferrariofilippo** [comment]
I take it

**Comment by gave92** [comment]
Before this I believe we need a way to:
- allow the user to hide the "Tags" column from all folders at once
- allow the user to edit tags as #9710 also removes the "edit tags" command
