### ISSUE TITLE
Feature: Replace bundles with tags widget

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#9587]
While tags and bundles are a little different, they are similar enough that we can remove bundles and replace it with a tags widget. This will lead to less duplication and will provide a more useful user experience.

**Requirements**
- Rename bundles and related settings to "Tags"
- Each tag should display a widget on the home page
- Each tag should have a button to navigate to a page with the full list of files

**Discussion points**
- Should all files be displayed in the widget or just the first 10-15?
- Should there be a menu option to add the tag to a specific file similar to bundles? (I think we should try without this for now)
- Should there be an option to create a new tag from the widget? (I think we should try without this for now)
- Should existing bundles be ported over to tags and if yes, should users be prompted, or should it happen automatically?

**Comment by yaichenbaum** [comment]
> Should all files be displayed in the widget or just the first 10-15?

@mdtauk do you have any input on this?

**Comment by mdtauk** [comment]
I can see the logic of using existing tags to replace the "Bundle".  My initial thinking is that people may see tags as an organisational tool, but see a Bundle as a group like Quick Access or Favourites.

If someone makes a tag specifically for having quick access to files or folders on their home screen - will they be annoyed to see that tag showing up in various folder views?

Also, could the tag group/bundles be responsive, so displaying more items (or displaying their items differently) depending on the space for them?

Do we introduce the idea of perhaps special tags for displaying on the Home screen maybe?

**Comment by yaichenbaum** [comment]
> If someone makes a tag specifically for having quick access to files or folders on their home screen - will they be annoyed to see that tag showing up in various folder views?

My hunch is that users wanting to pin items on the home page will be okay with the tag displaying in other views as well. At the very least, they can hide the tag column if they don't want it displayed.

> Also, could the tag group/bundles be responsive, so displaying more items (or displaying their items differently) depending on the space for them?

The first iteration will have a fixed size, if we do add support for custom sizes in the future, we'll still need to decide on the max items to display.

> Do we introduce the idea of perhaps special tags for displaying on the Home screen maybe? (like a pre-defined Home tag)

How would this work if users want multiple tags on the home page?

**Comment by jandye** [comment]
I think they can both serve separate purposes
