### ISSUE TITLE
Feature: Add a UI to edit, delete and create tags

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#9588]
This issue is open for discussion.
![image](https://user-images.githubusercontent.com/39923744/179832337-66b4601f-bde1-456d-900e-aa5d9a454c14.png)

- Should the UI for creating tag have its own dialog or should it be part of settings?
- Should you be able to right click the tags section on the sidebar to create a new tag or should you have to open the manage tags UI and do it from there?

**Requirements**
- Add a list under experimental settings for adding/deleting tags
- There should be a way to edit existing tags as well

**Comment by Josh-65** [comment]
Adding a new tag option in the tag management page and the context menu would proberly be best. Some properly would expect it to work like a library and other would in the dialog/settings.

**Comment by ferrariofilippo** [comment]
I think the right-click option is the best. We already have a lot of settings and I don't think we should keep overcrowding them.
Maybe we can add two different user interfaces:
- New tag 
  - A simple, small modal that allows you to quickly create a tag (choose color and name);
- Manage tags
  - A settings-like modal where you can create, edit, and remove tags. Renaming tags could work as inline renaming. I'm not sure, but I would like a count of tagged files (e.g. `Red: 30 tags`).

**Comment by yaira2** [comment]
I think it'll have to be part of settings because users can already hide the sidebar section.

**Comment by ferrariofilippo** [comment]
> I think it'll have to be part of settings because users can already hide the sidebar section.

I was thinking of the righ click option because of this: if the user hides `Tag Section` it won't probably use tags so she/he doesn't need that setting

**Comment by Josh-65** [comment]
Based on the open pull request shouldn't there be a new page in settings for tags rather then having the context menu option in Appearance and the editing/creating in Advanced. I think it would make it less hidden and crowded.

**Comment by ferrariofilippo** [comment]
I temporarily created it in Advanced to follow requirements, but I think a new page would make sense

> Add a list under experimental settings for adding/deleting tags

**Comment by yaira2** [comment]
We will move them to a new page in the near future, I want some time to test the changes before officially making tags a supported feature.
