### ISSUE TITLE
Folder size is 0B on SMB Network drive, shows 0 files 0 folders

### ISSUE THREAD

**Issue by SH4FS0c13ty** [files-community/Files#9589]
### Description

Hello,

So the issue is that when I go to the "Properties" of a folder on a network drive, it shows "0 files, 0 folders" and "Size: 0 B (0 bytes)", but there are files in there. However, it doesn't do this on a local folder and this issue is not present on the Windows Explorer (so not a drive or connection issue in my opinion).

I included a screenshot below if you think that would help. I tried taking a look at the debug.log and debug_fulltrust.log files but nothing caught my attention, maybe you'll find something useful.

### Steps To Reproduce

1. Navigate to a network drive (SMBv3)
2. Select a folder (with files and/or folders in it preferably)
3. Right-click on it, then select "Properties"
4. See the "Size: 0B" which is incorrect

### Expected behavior

I expect the "Properties" window to show the correct size of all the elements contained in the folder, as it does with local folders.

### Files Version

Version 2.3.3.0

### Windows Version

Windows 11 21H2 22000.795

### Relevant Assets/Logs

<img width="1256" alt="Untitled" src="https://user-images.githubusercontent.com/52138924/179849529-7ed6157c-3c99-4158-918c-156aafaf9ed4.png">
[debug.log](https://github.com/files-community/Files/files/9144760/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9144761/debug_fulltrust.log)

**Comment by gave92** [comment]
Merging with #6765

**Comment by SH4FS0c13ty** [comment]
Whoops, I haven't seen this issue even though I searched for it. Thank you :)
