### ISSUE TITLE
Improve consistency between New and Rename.

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#9591]
### What's the Problem?

Create New File/Folder and Rename File/Folder are 2 actions that require the user to enter a name. However, these 2 actions use a different UX. Create Item uses a popup and Rename Item edits the name in the main view. It is an inconsistency.

### Solution/Idea

Use similar popup to rename a file/folder.
- This has the advantage of being more readable for long names.
- The editing UX is the same for all views.
- This solution makes it possible to consider future additions (multiple editions, etc.).

### Alternatives

1) Create a file/folder directly in the view (like File Explorer). This is impractical and brings no added value.
2) Provide a user option for the display mode. This choice seems to me unnecessary and reduces the simplicity.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.3.1.0 OS Version: 10.0.22000.795

### Windows Version

Windows 11

### Comments

Here is a comparison.
![Folder1](https://user-images.githubusercontent.com/46631671/180040145-f2344cad-6de1-4e3b-875b-1f191c31fabf.png)
![Folder2](https://user-images.githubusercontent.com/46631671/180040150-34b8adf5-48a9-450d-9879-1cc643341c55.png)

**Comment by yaichenbaum** [comment]
> Create a file/folder directly in the view (like File Explorer).

This is the design we want to use, I thought we had an issue tracking this, but I can't find it.

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaira2** [comment]
This is the expected behavior.
