### ISSUE TITLE
Support for Office previews

### ISSUE THREAD

**Issue by GGProGaming** [files-community/Files#9592]
### What's the Problem?

Hey there, just wanted to point out that the lack of previews for the Microsoft Office lineup is quite annoying when trying to work. Could this feature please be added? I understand there is no proper support for this, but there is always a solution. 

### Solution/Idea

Have a preview

### Alternatives

Going back to windows explorer and suffering

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.3.3.0 OS Version: 10.0.22622.290

**Comment by yaichenbaum** [comment]
Thank you for your feedback, we're tracking this request in #4041
