### ISSUE TITLE
Proper formatting for code per file type

### ISSUE THREAD

**Issue by GGProGaming** [files-community/Files#9593]
### What's the Problem?

The current formatting for any text is the default text that you see in a .txt file.

### Solution/Idea

I am a developer and I would really appreciate a properly formatted preview of the code. I see that this exists with .xml files and I appreciate that, but having this would be fantastic. 

### Alternatives

Opening VS Code and waiting for it to load just to see if it is the file I need or not. Inconvenient 

### Files Version

Version: 2.3.3.0 OS Version: 10.0.22622.290

**Comment by yaichenbaum** [comment]
This is already supported, which file type are you using?

**Comment by GGProGaming** [comment]
> This is already supported, which file type are you using?

I tried doing .lua files

**Comment by yaichenbaum** [comment]
This is not supported at the moment. @winston-de any idea if we can do something similar to what we do with other code files?

**Comment by GGProGaming** [comment]
Also having a dark grey background color behind the code would be amazing
