### ISSUE TITLE
I love it , but I will uesed and recommeded if you make 

### ISSUE THREAD

**Issue by MKVde** [files-community/Files#9595]
### What's the Problem?

I love it, but I will use it and recommended if you make it faster and add feature that will let the user to disable the animation like the default windows file explorer..

Thanks 

### Solution/Idea

I love it, but I will use it and recommended if you make it faster and add feature that will let the user to disable the animation like the default windows file explorer..

Thanks 

### Alternatives

LL

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Comments

**Add these feature as fast you can**

**Comment by yaichenbaum** [comment]
Thank you for your feedback, animations can be disabled system wide from the Windows Settings app.
