### ISSUE TITLE
AVIF image format thumbnails support?

### ISSUE THREAD

**Issue by Kieaer** [files-community/Files#9596]
### What's the Problem?

![image](https://user-images.githubusercontent.com/44261958/180320156-10f8da7d-0cbc-4adf-bbfe-306e3be8fab3.png)
AVIF image preview does not work.
AV1 Extension is already installed on the PC, and it is displayed normally in the default file manager.

### Solution/Idea

Support avif, webp image preview

### Alternatives

There isn't.

**Comment by Kieaer** [comment]
Nevermind. When using OneDrive, there's a problem that images or videos using the av1 format are not displayed.
It's not a Files issue.

**Comment by yaichenbaum** [comment]
> Nevermind. When using OneDrive, there's a problem that images or videos using the av1 format are not displayed. It's not a Files issue.

Does it display if you refresh the directory?

**Comment by Kieaer** [comment]
@yair100 No. not displayed.

**Comment by yaichenbaum** [comment]
This is expected for the details layout as the thumbnail would be too small. Can you confirm that it loads in the grid layouts?

**Comment by Kieaer** [comment]
It's already solved
