### ISSUE TITLE
Enhance Experience when Copying/Moving Files

### ISSUE THREAD

**Issue by Naolador** [files-community/Files#9597]
### What's the Problem?

1. When copying or moving files, there's only an task indicator on the right corner tells you it's ongoing, but it doesn't tell you how fast and ETA.
2. Allow background transfer if the Files window is closed.
3. When copying the whole folder that the destination already exists, Files should ask whether you wish to keep the folder but replace or skip files inside the folders.

### Solution/Idea

Display the transfer speed and ETA like the original file explorer.

### Alternatives

n/a

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Show the transfer speed and ETA | Must |
| Prompt replace or skip files in a folder | Must |
| Transfer in the background if Files is closed | Should |
| Prompt on close when files are still transferring | Could |
| n/a | Won't |

### Files Version

Version: 2.3.3.0 OS Version: 10.0.22000.795

### Windows Version

Windows 11 Pro Version	21H2 Installed on	‎5/‎12/‎2021 OS build	22000.795 Experience	Windows Feature Experience Pack 1000.22000.795.0

**Comment by Josh-65** [comment]
Merging with #4811
