### ISSUE TITLE
Navigation view covers drag area in the properties window

### ISSUE THREAD

**Issue by sho9029** [files-community/Files#9598]
### What's the Problem?

In [Properties.xaml](../blob/main/src/Files.Uwp/Views/Pages/Properties.xaml), the NavigationView is always the same size regardless of the number of MenuItems, resulting in blank spaces that cannot be dragged.

The area surrounded by the green line is the draggable area and the area surrounded by the red line is the NavigationView.
![Properties](https://user-images.githubusercontent.com/49068710/180601605-ca88b663-0ba9-48d2-97fd-294606be3093.png)

### Solution/Idea

- Change the size of NavigationView according to the number of MenuItem.

### Alternatives

I haven't any alternatives.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Change the size of NavigationView according to the number of MenuItem | Should |

### Files Version

Version: 2.3.3.0

### Windows Version

Windows 11 21H2 22000.778

**Comment by yaichenbaum** [comment]
This seems to be a bug with WinUI where it doesn't remove hidden items from the visual tree. @Josh-65 did you already open an issue for this problem?

**Comment by Josh-65** [comment]
#7414 is the one i opened

**Comment by yaichenbaum** [comment]
Merging with #9919
