### ISSUE TITLE
use extentions for the modern files project

### ISSUE THREAD

**Issue by Issam-seghir** [files-community/Files#9599]
Can I use extensions in this modern file explorer like : [Qttabbar ](http://qttabbar.wikidot.com/) or [file converter](https://github.com/Tichau/FileConverter) ?
I know this project is very powerful and has functioned better than the old file explorer but I really miss the function of clicking on files and showing the content of it in a dropped menu, it increases my speed and my productivity,
I will be happy if I can use `Qttabbar` on this files explorer or if you add this function in the future.

**Comment by Josh-65** [comment]
No visual changing ones. Other rpograms would have to make it for Files. If the extention adds entries to the context menu then yes it will work.
