### ISSUE TITLE
instalaçao

### ISSUE THREAD

**Issue by tadkn** [files-community/Files#9600]
bom dia eu moro no brasil eu fiquei sabendo do app atraves de um video no tik tok na qual uma pessoa indica o app e realmnte deixa o explorador de arquivos com um visual muito bom mas eu baixei um arquivo e quando fui instalar como adm ate apareceu aquela mensagem pra autorizar a instalaçao porem depois dessa etapa a instalaçao nao avança e quando eu clico com o botao direito do mouse em qualquer lugar da area de trabalho o windowns faz um som como se tivesse dado erro e esse problema só é resolvido se reiniciar o pc e esse problema acontece com qualquer arquivo que voce tente executar como adm porem o arquivo abre numa boa se voce tentar instalar sem ser como adm

**Comment by Josh-65** [comment]
You will have to give a screenshot of the install window with the error showing

**Comment by tadkn** [comment]
> Você fornecerá uma captura de tela da janela de instalação com o erro de prêmio

no caso eu teria que fazer um video pra mostrar o bug

**Comment by yaichenbaum** [comment]
@tadkn we're having a hard time understanding this issue, can you please open a new one using the issue template?
