### ISSUE TITLE
切换桌面后 Files弹出新的窗口 旧的窗口会出现无法点击

### ISSUE THREAD

**Issue by LinaDaylight** [files-community/Files#9603]
### Description

在多个桌面下 (其中一个桌面打开了Files) 桌面来回切换  有几率导致Files弹出新的窗口 旧的窗口会出现无法点击的情况 

### Steps To Reproduce

使用多个桌面 
并在任意一个桌面打开Files
在桌面吉安来回切换
有几率出现此情况

### Expected behavior

能修复这个错误 桌面切换时 Files保持原状不变 

### Files Version

2.3.3.0

### Windows Version

Windows11

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9179511/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9179512/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
Merging with #7603
