### ISSUE TITLE
默认文件管理器用不了

### ISSUE THREAD

**Issue by baldhead233** [files-community/Files#9604]
### Description

点击什么都都是打开文件管理器
点击dpan 也是打开文件管理器 
什么软件啊 把我的电脑弄坏了

### Expected behavior

..

### Files Version

windows 10

### Windows Version

Windows10

### Relevant Assets/Logs

none

**Comment by yaichenbaum** [comment]
We're having a hard time understanding this issue, can you fill out steps to reproduce and upload the log files?

**Comment by baldhead233** [comment]
> We're having a hard time understanding this issue, can you fill out steps to reproduce and upload the log files?

I have solved it out
