### ISSUE TITLE
Allow an option to copy/paste files using Terracopy

### ISSUE THREAD

**Issue by jameslashmar** [files-community/Files#9608]
### What's the Problem?

Files uses it's own system to copy/paste files.  When using Windows Explorer I use it with the extremely robust Teracopy.  

Files app seems to ignore this preference and use it's proprietary system.

### Solution/Idea

It would be great to have the option to use Teracopy.

[](https://www.codesector.com/teracopy)

### Alternatives

n/a

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.3.3.0

### Windows Version

22H2 22622.436

**Comment by gave92** [comment]
Merging with #7518
