### ISSUE TITLE
Files app crash

### ISSUE THREAD

**Issue by sholimagias** [files-community/Files#9609]
### Description

I was browsing the internet trying to find a wallpaper on Microsoft Edge Browser when i found a **SUPER HIGH RESOLUTION** wallpaper on 4kwallpapers.com
(https://4kwallpapers.com/abstract/apple-pro-display-xdr-stock-liquid-316.html) **(4096 x 2265‬p 24bit image file)**
So I downloaded it and clicked on the downloads icon in the right top corner of the browser and opened the folder location (which in my case happens to be the "Downloads") of the image that I just downloaded. I wanted to see some info about the image so I enabled file preview window and srolled to see all the info of that file and **bam! Files app crashes and notification appears saying; "Something went wrong! Files ran into a problem that the developers didn't prepare for yet.**
I suspect the Files app **crashed because** the image preview window **couldn't render** a super hd image.

Opening the file in MS Edge;
![Στιγμιότυπο οθόνης 2022-07-26 142241](https://user-images.githubusercontent.com/83831424/180995340-9be74e2a-52d1-49f4-8dda-ba7c10647938.png)

Opening the file in files app;
![Στιγμιότυπο οθόνης 2022-07-26 142450](https://user-images.githubusercontent.com/83831424/180995400-1c4966cd-a3f6-4809-90b0-5cc178d5f0c8.png)

After scroling in file preview window app crashes.

After crash notification;
![Στιγμιότυπο οθόνης 2022-07-26 140840](https://user-images.githubusercontent.com/83831424/180995239-8b792480-8ae2-48e4-a2a8-b09f7123fac6.png)

*Note1: I use the Greek version of windows and before reporting ths bug I also used the files app in greek but i changed it to english so that you can understand what is says.

*Note2: I use a Huawei matebook d 14 with 8gigs of ram and radeon integrated graphics so the app might have crashed beacause of not enough performance to render this image.

### Steps To Reproduce

1. Open Microsoft Edge
2. Download a 4096 x 2265‬p 24bit wallpaper (in my case the apple pro dispaly xdr wallpaper)
3. open the file location from the downloads pop up of MS Edge
4. click on the enable file preview window button
5. scroll in the preview window for 4-7 seconds

### Expected behavior

I epected the files app *not to crash* and stay open.

### Files Version

Version: 2.3.3.0 OS Version: 10.0.22000.832

### Windows Version

Windows 11 21h2 22000.832

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9189303/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9189304/debug_fulltrust.log)

*Note: I tried and tested the bug multiple times so there probably be more than one errors.

**Comment by yaichenbaum** [comment]
Thank you for the detailed report (and a special thanks for changing to English). Can you reproduce this consistently?

**Comment by sholimagias** [comment]
> Thank you for the detailed report (and a special thanks for changing to English). Can you reproduce this consistently?

Somehow after some successful reproductions (the day of discovery of this issue) I since haven' been able to reproduce this (I followed my own steps for reproduction and they didn't work). Kind of wierd... At this point I'm not sure of it's the programme's false or something else that magicly got fixed [by restarting my computer, deleting the temp files of my system or running SFC /scannow (those are things that I did after the day of reproduction)]. 
Anyway,
if it wasn't a bug of the Files app, I'm sorry for wasting your time.

**Comment by yaichenbaum** [comment]
Please let us know if you can reproduce it again and we'll investigate this further.

**Comment by gave92** [comment]
From the logs it appears the "usual":
> 13:37:36.7631|ERROR|AppUnhandledException|Layout cycle detected. Layout could not complete. Layout cycle detected. Layout could not complete.
