### ISSUE TITLE
Feature: Auto focus first item in the Add Item modal

### ISSUE THREAD

**Issue by jameslashmar** [files-community/Files#9610]
**Requirements**
- Auto focus the first option in the New Item model so that pressing the enter key automatically creates a new folder

**Comment by manuel-gibaut-h** [comment]
Hi there, I think I found a solution to the problem, by adding an option on `PreferenceSettingService` and changing both `ModernShellPage` and `ColumnShellPage` to check if the option is enabled and redirect the shortcut "Ctrl + Shift + N" directly to `CreateFileFromDialogResultType` from `UIFilesystemHelpers` class, for the other part I've managed to focus the first item of AddItem ListView to be focused so it should be possible to travel the List via arrow keys.

The only problem I found so far is adding the Setting/Preference text to all the Resources.resw files, and if possible I would like to know what steps to follow or if it's not necessary on my part to complete that part.

Thanks on advance

@yair100

**Comment by yaichenbaum** [comment]
@z3r0tru5tk4l1 we shouldn't need a setting for this as it should be the default behavior 🙂 
For the future, when adding a new string, adding the string to the en-us resource file is enough, the other strings are generated on our end.

**Comment by manuel-gibaut-h** [comment]
@yair100 Thanks for the quick answer, final question on how to continue, should I revert the changes made to the Setting/Preference and both `ShellTypes` as well as the Resource.resw change I made in the en-us folder? And only leave the autofocus on the firs item of the AddItem ListView or do I just create a PR for the changes made?

Thanks in advanced

**Comment by yaichenbaum** [comment]
> should I revert the changes made to the Setting/Preference and both ShellTypes as well as the Resource.resw change I made in the en-us folder? And only leave the autofocus on the firs item of the AddItem ListView

That would be ideal 👍
