### ISSUE TITLE
A **Send-to** Sub-menu for the Files App Context Menu

### ISSUE THREAD

**Issue by SE7ENESE** [files-community/Files#9613]
### What's the Problem?

There's a Send-to SubMenu under the traditional Context Menu. I love the fact that Files seems to gradually have some of the traditional sub-menus linked already, but the **_send-to_** sub-menu is also just as vital, as it enables a user to be able to send files using Bluetooth and other _archaic_ methods that are slowly fading away.
![image](https://user-images.githubusercontent.com/108288247/181345792-72995864-15c1-48ce-a4bc-092829002f2e.png)
![image](https://user-images.githubusercontent.com/108288247/181345992-ee715b4a-e900-423d-a568-18e6ea273838.png)

### Solution/Idea

It'd be great if the **_Send to_** Sub-menu could be linked to the Files' App Context Menu.

### Alternatives

Another idea I considered is that the send to menu could be Fused into a new **_share_** sub-menu that combines both the send to and Share features in one "exclusive-to-Files" pop-up window... I thought that'd be cool to see...

![image](https://user-images.githubusercontent.com/108288247/181346674-544ae148-58ff-4f09-84b0-9ff5988e8534.png)

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.3.3.0

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎30/‎06/‎2022 OS build	22000.795 Experience	Windows Feature Experience Pack 1000.22000.795.0

### Comments

I've linked screenshots in the pages above, hope they'll be sufficient to get the idea of my suggestion across... :)

**Comment by yaichenbaum** [comment]
Microsoft is working on improving the share menu so we don't plan to add the send to option.
