### ISSUE TITLE
Option for the Sidebar to replicate Windows File Explorer features

### ISSUE THREAD

**Issue by gmuller2** [files-community/Files#9614]
### Solution/Idea

Provide an option in the Settings for Sidebar to replicate the following File Explorer settings.
1. "Show all folder", so the User's home folder is shown.
2. "Expand to current folder", so that full tree path is shown in the sidebar.

### Alternatives

There are no alternatives other than keep using File Explorer or use an Explorer extension like QTBar.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.3.3.0

### Windows Version

Windows 10 Enterprise Version 21H2 19044.1826

**Comment by yaichenbaum** [comment]
Thank you for your feedback, we're planning a tree view layout option, but we don't plan to add these options to the sidebar.
