### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by JersonGaming** [files-community/Files#9616]
### What's the Problem?

Sometimes the transparency of icons disappears. Sometimes the preview of the image does not appear. 
https://imgur.com/a/aybWFdP

### Solution/Idea

Refresh helps

### Alternatives

Can you remove the cropping of a images as in the standard File explorer?
https://imgur.com/a/Tt8kclV
It would also be cool to return the display of the image resolution when you hover the cursor over it.
https://imgur.com/a/9FDGvFz

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.3.3.0 OS Version: 10.0.22000.795

### Windows Version

Windows 11 21H2 22000. 795

**Comment by gave92** [comment]
#6373 + #9129
