### ISSUE TITLE
I can't use the program

### ISSUE THREAD

**Issue by AtaideDev** [files-community/Files#9618]
### Description

The program opens normally showing all storage, but it doesn't work from there, you can't click on anything, it's as if the program has crashed, even in the task manager showing that it is running normally.

### Steps To Reproduce

open the program
see the error

### Expected behavior

The program opens normally showing all storage, but it doesn't work from there, you can't click on anything, it's as if the program has crashed, even in the task manager showing that it is running normally.

### Files Version

2.3

### Windows Version

Windows 10 21H2 19044.1706

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/98127419/181863037-7e7c9110-1d50-4049-9907-cea8ff2b9504.png)
![Animação (8)](https://user-images.githubusercontent.com/98127419/181864684-ba41fc22-2436-493d-a263-46bf72e038c6.gif)

**Comment by Josh-65** [comment]
You will need to upload the logs files directly to github. You can get them in files settings > about > open log folder.

**Comment by AtaideDev** [comment]
I messed with regedit and somehow managed to get it to work.

**Comment by gave92** [comment]
Thanks for the update, glad it's working now. We're still interested in the log files and if you can share more details about how did you "mess with regedit" to make it work :)
