### ISSUE TITLE
can't uninstall files installed with chocolatey

### ISSUE THREAD

**Issue by Issam-seghir** [files-community/Files#9619]
### Description

I install **files** with `choco install files`, and when I try to uninstall it ,  in the terminal it just shows a successful uninstall message .

but I still saw the files app in my taskbar and I can use it normally 

I go to `$env: ChocolateyInstall\lib` and I don't find **files** on it .

I try to uninstall again with :  `choco uninstall files -y -n --force `
but the message: ` files are not installed. Cannot uninstall a non-existent package. ` occurred

### Expected behavior

files uninstalled and i can't find it in my PC

### Files Version

Version : 2.3.3.0 OS Version: 10.0.19044.1706

### Windows Version

Windows 10 21H2 19044 1706

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/74573675/181878092-3da36db7-86cf-422d-ba76-6356e78f1c51.png)

**Comment by Josh-65** [comment]
Files doesnt support external downloader like chocolatey. Please use the MS store or https://files.community/download/stable
