### ISSUE TITLE
Very nice, but much to slow.

### ISSUE THREAD

**Issue by jreichert73** [files-community/Files#9620]
I'm testing FILES as an Explorer replacement and I really like it.

- PRIO A: The general performance (changing folders etc) has to be **much faster** for power users.
-- Sometimes I open a folder a have to wait 5 seconds or more (even though i have a fast SSD)
-- Maybe there should be an expert mode, without the nice animation stuff, but therefore faster.
- The tags are nice, but should be customizable (Name, Color)
- A horizontal bookmark toolbar like in Chrome would be nice
- Tabs should be able to pin on the left side

Good work for now!

**Comment by gave92** [comment]
Merging with #9588, #4180, #6458

**Comment by yaira2** [comment]
We're excited to share that startup performance will be significantly improved in the upcoming release of version 3. You can download the preview version from our website https://files.community/download.

**Comment by yair100** [comment]
@jreichert73 we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
