### ISSUE TITLE
Setting to turn off finished tasks

### ISSUE THREAD

**Issue by Jan-Fuellhase** [files-community/Files#9621]
### What's the Problem?

Add the ability to turn off the finished tasks tray at the top right.

![image](https://user-images.githubusercontent.com/83337095/181911280-24f0df8d-f4c9-46db-a30a-751324a2b70d.png)

### Solution/Idea

Add a slider in Settings that will remove the finished tasks tray at the top right.

### Alternatives

Turn it off as standard OR delete it as a whole.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.3.3.0 OS Version: 10.0.22000.795

### Windows Version

Windows 11 21H2

**Comment by yaichenbaum** [comment]
Can you share more about your use case?

**Comment by Jan-Fuellhase** [comment]
> Can you share more about your use case?

The finished task tray is not really needed if you only copy small files that are instantly done. Furthermore this is annoying to OCD users like me, who have to click it away after every copy.

**Comment by yaichenbaum** [comment]
How would you differentiate between larger files where validtion doesn't hurt? The OCD goes both ways 😆

**Comment by Jan-Fuellhase** [comment]
> How would you differentiate between larger files where validtion doesn't hurt? The OCD goes both ways 😆

I would just have a popup that shows the ongoing operation. It goes away when its done. Much like WinExplorer.

**Comment by yaichenbaum** [comment]
This is one area where we purposely differentiate from File Explorer. Displaying a green check mark when the operation is completed and displaying an error when it doesn't, gives the user confidence in the file operations much like the download experience in Microsoft Edge.
