### ISSUE TITLE
The wrong next file is selected after deleting a file if folder is grouped

### ISSUE THREAD

**Issue by Jan-Fuellhase** [files-community/Files#9624]
### What's the Problem?

Scenario: Download Folder has 500 Files in it. You have it sorted after date and want to delete the latest file on the top.
If this file is called "page1", the focus will just jump to any file in the folder that is called "page2" way further down. 
Problem: You have to scroll up alot. For workflow this is annoying.
Settings used:
![image](https://user-images.githubusercontent.com/83337095/181920363-6965a783-969e-4c57-81d9-f847a1d08fca.png)

### Solution/Idea

Remove this feature. Putting this in settings would be overwhelming for the user.

### Alternatives

Put it in Settings to turn this off if.

### Files Version

Version: 2.3.3.0 OS Version: 10.0.22000.795

### Windows Version

Windows 11 21H2

**Comment by gave92** [comment]
Is the folder also grouped by something?

**Comment by Jan-Fuellhase** [comment]
> Is the folder also grouped by something or only sorted?

Grouped by Date of Creation, Sorted by changing Date.

**Comment by gave92** [comment]
Could you check what happens if you remove the grouping? Is the next file correctly highlighted?

**Comment by Jan-Fuellhase** [comment]
> Could you check what happens if you remove the grouping? Is the next file correctly highlighted?

Yes it is, since it is now sorted by name and will just highlight the next one.

**Comment by gave92** [comment]
*I meant: remove the grouping but leave it sorted by date (or size, or anything _but_ name). I think the problem only emerges if the folder is grouped.

**Comment by Jan-Fuellhase** [comment]
I have it sorted my Date now and group by nothing and it highlights correctly.
However my problem is not that the highlighting is not working, so im not sure i agree with your title. It does highlight the "next" file even when grouped, but it should highlight a file inside the group so you dont get thrown to the end of the folder.

**Comment by gave92** [comment]
Thanks for confirming. Yeah "next" as in "immediately below in the file list".

**Comment by carlosvsilva** [comment]
same as #9429
