### ISSUE TITLE
Some thoughts on the features

### ISSUE THREAD

**Issue by bbs3223474** [files-community/Files#9625]
### What's the Problem?

1. I personally don't like the "double click on the blank to go back" gesture. But I also cannot find anywhere to disable it.
2. When changing the layout mode to "small icons" and there's Chinese words after the alphabets in the file name (e.g. QQ图片20220731), the file name won't show properly (only "QQ..." and nothing else).
3. Default layout is "details", which is fine. But some of my folders include only pictures or videos. Those I prefer them to show small icons by default, just like what Windows do. (Edited: I noticed when there're a lot of those files, the layout will change to "icons". But if there're folders, it won't)
4. Folders (mostly/only) with media files especially musics should list their own infos e.g. artist, album, No., etc. in "details" layout mode by default, rather than just showing dates and bytes just like other folders.
5. Drive and folder sharing over SMB is not supported. I cannot find any place to set it up.
6. I prefer opening a new drive with a new tab by default, and keeping the "Home" tab's presence. So that I can open up a drive, browse some folders, click on the "Home" tab on the top-left, and open up another drive with another new tab, no need to add a new tab first to do all of them.
7. Pointing on the picture files with the mouse cursor cannot show its resolution. I prefer to know that info even without opening the files.
8. **BUG:** Adding a new folder to the "Library" is buggy. I cannot delete what I added, and editing its location won't change anything. After clicking "OK", nothing happens. When I check it back, the location is still "C:\users\name\documents".

### Solution/Idea

1. Add a gesture setting to let us enable/disable certain things.
2. This is a bug I guess?
3. to 8. are pretty much explained themselves.

### Alternatives

For now I will still use this app because it feels billion times better than Windows 11's file explorer despite all above and nothing I mentioned can be partially/fully resolved within the app as of now.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| 8. | Must |
| 1. 2. 4. 6. 7. | Should |
| 3. 5. | Could |
| None | Won't |

### Files Version

2.3.3.0

### Windows Version

Windows 11 Insider Preview Build 25163.1010

**Comment by Josh-65** [comment]
Please file feedback in seprate issues.
