### ISSUE TITLE
ZIP-Files wont open

### ISSUE THREAD

**Issue by elNino0916** [files-community/Files#9626]
### Description

Files wont show the content of a zip file

### Steps To Reproduce

1. Set Files to default .zip application or xxx.zip -> open with -> files

### Expected behavior

FIles shows the content of the Zip-File

### Files Version

Version: 2.3.3.0 

### Windows Version

Windows 11 Pro 21H2 1000.22000.832.0

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/84574414/181936741-849fcef4-31d6-42f6-a9d2-1be19c430d88.png)
![image](https://user-images.githubusercontent.com/84574414/181936762-981409c3-6eaf-4788-903d-876e6b5d6353.png)

**Comment by DanWahlin** [comment]
I'm seeing the same behavior as well.

**Comment by gave92** [comment]
Merging with #7680
