### ISSUE TITLE
Folder Names on Large Icons Layout

### ISSUE THREAD

**Issue by AMit-96** [files-community/Files#9627]
### What's the Problem?

When I set the view as Large Icons, the folder names are truncated and replaced with '...'.

### Solution/Idea

Just like in the windows file explorer, if it could show full folder names without truncating, that'd be great.

### Alternatives

We can have an option in the settings to toggle short names on/off.
This way people who enjoy minimal UI can enjoy it as it currently is and other people can have full names displayed just like in the windows file explorer.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.3.3.0

### Windows Version

Windows 11 22000.832

**Comment by Josh-65** [comment]
Merging with #1033
