### ISSUE TITLE
Cannot disable "Default File Manager" setting

### ISSUE THREAD

**Issue by 351768593** [files-community/Files#9631]
### Description

The switch of `Set Files as Default File Manager` will automatically turn on every after re-openning `Files` or its config modal.

### Steps To Reproduce

1. Open `Files`
2. Turn `Set Files as default file manager` on
3. (Optional) Close `Files` or its config modal and re-open
4. Turn `Set Files as default file manager` off

### Expected behavior

Hope we are able to disable that setting

### Files Version

2.3.3.0  

### Windows Version

Windows 21H1 19043.1826

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/9230241/debug_fulltrust.log)

**Comment by Josh-65** [comment]
You can open this https://raw.githubusercontent.com/files-community/Files/main/src/Files.FullTrust/Assets/FilesOpenDialog/UnsetFilesAsDefault.reg > right click on the opened page > Save as > set the type to "all files" > remove the .txt from the end of the name > open the file > allow admin when you get the prompt.

**Comment by gave92** [comment]
PR #9580 should fix this issue.

**Comment by 351768593** [comment]
> You can open this https://raw.githubusercontent.com/files-community/Files/main/src/Files.FullTrust/Assets/FilesOpenDialog/UnsetFilesAsDefault.reg > right click on the opened page > Save as > set the type to "all files" > remove the .txt from the end of the name > open the file > allow admin when you get the prompt.

It works, thanks!
