### ISSUE TITLE
Copy-and-paste is not working when run `Files` as admin

### ISSUE THREAD

**Issue by 351768593** [files-community/Files#9632]
### Description

Copy-and-paste is not working both when copying full path or the file(s) when run `Files` as admin.

#### Copy fullpath of current folder
1. Run `Files` as admin
2. Left-click blank space of fullpath input
3. Select-all (by right-clicking -> `Select All` or by Ctrl+A)
4. Copy (by right-clicking -> `Copy` option or by Ctrl+C)
6. Switch to other software, such as Notepad
7. Paste but not work

BTW, Win+V shows nothing was saved to system clipboard after Copy operation in `Files`.

#### Copy file(s)
1. Run `Files` as admin
2. Right-click and file(s)
3. Copy (by right-clicking -> `Copy` button or by Ctrl+C)
4. Paste (By right-clicking -> `Paste` option or by Ctrl+V) but not work

As same as above, nothing was saved to system clipboard.

### Expected behavior

Hope we are able to use copy-and-paste when run `Files` as admin.

### Files Version

2.3.3.0

### Windows Version

Windows 21H1 19043.1826

### Relevant Assets/Logs

This issue was found when submitting #9631 and content of `debug_fulltrust.log` was the same.

**Comment by gave92** [comment]
How are you launching Files as admin?

**Comment by 351768593** [comment]
1. run a CMD as admin
2. run `"C:\Program Files\WindowsApps\49306atecsolution.FilesUWP_2.3.3.0_x64__et10x9a9vyk8t\Files.exe"`

me personally use `Everything` to locate and launch some softwares some days. Does it means that we should not run any UWP softwares like that?

**Comment by Josh-65** [comment]
It not how programs should be ran. Files will ask for admin when it needs it. If you open it the normal way via the start menu does it work?

**Comment by 351768593** [comment]
> It not how programs should be ran. Files will ask for admin when it needs it. 

got it

> If you open it the normal way via the start menu does it work?

Yes, `Files` works well when run via start menu.

**Comment by Josh-65** [comment]
Im going to close this since opening the normal way works.
