### ISSUE TITLE
Folder preview in 'Preview Panel' has a BLACK background when viewing for the first time

### ISSUE THREAD

**Issue by Redbird10** [files-community/Files#9634]
### Description

When clicking on a folder for the first time, the folder's preview in 'Preview Panel' has a BLACK background. 
Only happens if the folder has not been clicked on before.
Click somewhere else and then reclick the folder, the folder's preview in 'Preview Panel' will be correctly displayed without (black) background.

### Expected behavior

The folder's preview in 'Preview Panel' should be correctly displayed without (black) background since the first time.

### Files Version

Version: 2.3.3.0 OS Version: 10.0.22622.440

### Windows Version

Windows 11 22H2 22622.440

### Relevant Assets/Logs

![First Time Click](https://user-images.githubusercontent.com/36776688/182167709-359a1c52-74c7-4f9e-adb1-b1363e5531c2.png)
![Second Time Click](https://user-images.githubusercontent.com/36776688/182167719-44870d16-3b84-4485-9b40-957c6c01b1d0.png)

**Comment by Josh-65** [comment]
This is a Windows issue and Files carnt do anything about it.

**Comment by Redbird10** [comment]
> icon caching

Would you provide more info related to this? Is this a normal behaviour for everyone, or is it that my system is broken? Thanks.

**Comment by Josh-65** [comment]
It happens for everyone refreshing the folder/preview pane usually fixes it.
