### ISSUE TITLE
Hi CPU Usage viewing network drive

### ISSUE THREAD

**Issue by Segullah** [files-community/Files#9635]
### Description

When I navigate to a folder on a network drive, there is a long delay before the contents show up in the folder pane. While waiting I launch task manager and find that CPU utilization can reach as high as 30%, and easily remain above 20% for several seconds. In contrast, Windows file explorer and several other alternative file explorers are almost instantaneous.

What's strange is that if I paste the path directly to the folder, the results are speedy (although I wonder if there could be some caching happening).

### Steps To Reproduce

Launch Files and navigate about 4 levels deep to a network folder containing 2,299 folders and 1,168 files. In my case it was a folder on our NTFS drive U: 

### Expected behavior

Similar performance to Windows file explorer and several other alternative file explorers which are almost instantaneous in their display of folder contents.

### Files Version

version 2.3.3.0

### Windows Version

Windows 11 Pro 21H2 OS Build 22000.795

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9236564/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9236565/debug_fulltrust.log)

**Comment by Josh-65** [comment]
Merging with #4180. This will be because it's loading 3000+ items and network drives are usually slower in general.
