### ISSUE TITLE
Tried running a program and it crashed

### ISSUE THREAD

**Issue by yeliabmit** [files-community/Files#9637]
### Description

I tried running a C# program and it crashed Files.

### Steps To Reproduce

1. double click .exe file
2. Files crashes to desktop

### Expected behavior

I expected files to continue operating and the program to run

### Files Version

2.3.3.0

### Windows Version

Windows 10 19044.1826

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9239335/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9239337/debug_fulltrust.log)

**Comment by gave92** [comment]
Looks like our favorite random error: System.ArgumentOutOfRangeException.
Sane stacktrace as #7035, #8429.
