### ISSUE TITLE
Folders First Toggle

### ISSUE THREAD

**Issue by MuftiAnees** [files-community/Files#9639]
### What's the Problem?

No problem but I think since windows file explorer has this the folders should be shown first. A toggle for this setting would be amazing as it will let users customize it to their liking.

### Solution/Idea

A toggle in settings which turns this setting on or off.

### Alternatives

An option in the view tab or when u right click and go into view settings there

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.3.3.0

### Windows Version

19044.1826

**Comment by yaichenbaum** [comment]
@MuftiAnees can you add more context?

**Comment by MuftiAnees** [comment]
Of course! So what I am saying is that when you are in a folder with multiple files and folders and sort them alphabetically. everything is sorted in Alphabetical order. I don't want that. I want it to sort all the folders in alphabetical order first then all the files like how it is done in the windows explorer.
For Example in the image the folders are not shown before the files rather they are also arranged in order with the files. I hope this makes it clearer.

![Untitled](https://user-images.githubusercontent.com/89216202/182422159-989bcc22-6b1a-44fb-8d76-20c6afa04b64.png)

**Comment by MuftiAnees** [comment]
I should also let you know that this is only happening in my "downloads" folder it works how i want it to work in other folders for some reason.

![image](https://user-images.githubusercontent.com/89216202/182422747-13d76d59-a38b-44da-891a-54c3ed3644dc.png)

**Comment by yaichenbaum** [comment]
Do you have the option to sort folders with files turned on (it should be off by default)?

**Comment by GGProGaming** [comment]
> I should also let you know that this is only happening in my "downloads" folder it works how i want it to work in other folders for some reason.
> 
> ![image](https://user-images.githubusercontent.com/89216202/182422747-13d76d59-a38b-44da-891a-54c3ed3644dc.png)

I have found this to be an issue as well. It seems that windows explorer does by date/time and everything else is set by name
