### ISSUE TITLE
Use of default pdf app for pdf preview. 

### ISSUE THREAD

**Issue by GGProGaming** [files-community/Files#9641]
### Solution/Idea

Hey there, I have loved this project and the progress it has made. I do find some things annoying at times that I miss from Windows Explorer. For instance, when viewing a pdf, you will get the files custom pdf viewer. Which is nice at times, but it becomes annoying for massive documents that may be 600 pages in size but you can only view 5. In windows explorer, it uses your default pdf app for custom buttons and things in the window, programs such as BlueBeam and Adobe work great with this. I would appreciate some work into this, and some work into saving where I moved the name, date, size, etc columns so they don't revert back every time I open a new window.

### Alternatives

Suffer :/

### Files Version

Version: 2.3.3.0 OS Version: 10.0.22622.290

**Comment by gave92** [comment]
Merging with #5582

**Comment by yaichenbaum** [comment]
@GGProGaming I want to point out that #5582 will handle previews for other file types as well.
