### ISSUE TITLE
Items are highlighting while dragging an item

### ISSUE THREAD

**Issue by verdaderoken** [files-community/Files#9645]
### Description

Here's what it looks like

[](https://user-images.githubusercontent.com/88200096/182540102-e6bf53e0-b59c-4bb9-8bbe-28c22b8d14cc.webm)

### Steps To Reproduce

1. Open a folder
2. Select an item and start dragging
3. Notice the other items will also highlight

### Expected behavior

Highlights should disappear after dragging or the items should not be highlighted in the first place.

### Files Version

2.3.2.0

### Windows Version

22H2 Build 22622.440

### Relevant Assets/Logs

None

**Comment by gave92** [comment]
Merging with #6768
