### ISSUE TITLE
Cannot change layout at the top and second directory of Google Drive

### ISSUE THREAD

**Issue by fmsan51** [files-community/Files#9646]
### Description

Layout mode cannot be changed from the default (Details) at the top (G:) and second directory (G:\My Drive) of Google Drive.
At the third and lower directory (G:\My Drive\...), layout mode can be changed.

### Steps To Reproduce

1. Open Google Drive ('G:\')
2. Try to change layout mode

### Expected behavior

Layout mode should be changed accordingly.

### Files Version

Version: 2.3.3.0 OS Version: 10.0.22000.795

### Windows Version

Windows 11 Pro 21H2 22000.795

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/9249559/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/9249560/debug.log)

**Comment by Josh-65** [comment]
Could you try changing it in the preview version https://files.community/download/preview

**Comment by fmsan51** [comment]
I confirmed that the problem is fixed in the preview version (2.3.10.0).
Thank you!
