### ISSUE TITLE
Visual issue, folder icons not rendering as expected

### ISSUE THREAD

**Issue by TRINCETT** [files-community/Files#9649]
### Description

Every time i set de icon size to medium the folder icons render with a black border and doesn't seems good.
![image](https://user-images.githubusercontent.com/93570862/182716410-9fcdd698-dd65-422d-887f-bf1192cb32ec.png)
![image](https://user-images.githubusercontent.com/93570862/182716793-c7575695-c722-42ca-92d8-e4e835efc681.png)

### Steps To Reproduce

Go to layout
Click On medium icons
![image](https://user-images.githubusercontent.com/93570862/182717039-8d8c944d-16d7-4885-84e7-31aa4b1b1edc.png)

### Expected behavior

I expect when i select the medium icon size doesn't show that black border on the folders 😢 

### Files Version

Version: 2.3.3.0 OS Version: 10.0.22000.832

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎7/‎31/‎2022 OS build	22000.832 Experience	Windows Feature Experience Pack 1000.22000.832.0

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/9255217/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/9255218/debug.log)

**Comment by gave92** [comment]
Merging with #6373
