### ISSUE TITLE
Allow dragging the Settings window

### ISSUE THREAD

**Issue by Germs2004** [files-community/Files#9650]
### What's the Problem?

When I click the gear icon, a Settings window pops up.  When I click and drag the top of that Settings window, nothing happens.  In Windows, the expected behavior is that windows can be moved by dragging the top of them.

This can be inconvenient when I have some other program open and need to move the Settings window over where I can see it.  For example, a user may want a web browser open to view documentation about each setting.

### Solution/Idea

Make that window moveable.  Resizable would be nice too, so we can see more settings at the same time.

### Alternatives

none

### Priorities

| Capability | Priority |
| :---------- | :------- |
| window must be moveable | Must |
| window should be resizable | Should |
| window should have a minimum size to prevent making it too small | Should |
| window should prevent user from moving it outside the visible screen, where they can't reach its X button to close it | Should |

### Files Version

2.3.0.0

### Windows Version

Win 11 21H2

**Comment by yaichenbaum** [comment]
The settings dialog is a modal and is not meant to be draggable. You should be able to move the main app window though.

**Comment by Germs2004** [comment]
I respect that it wasn't originally meant to.  I think some modal windows are moveable in other programs, and I see some benefit in allowing this one to be moved.  Just a suggestion though, feel free to decline.

**Comment by yaichenbaum** [comment]
It really depends on the purpose, the properties window for example is meant to be used alongside the app so it's a separate window. When the user opens settings, they usually want to take an action right away and close it afterwards.
