### ISSUE TITLE
Scrollbar gap can allow accidental clicks on files/folders

### ISSUE THREAD

**Issue by Germs2004** [files-community/Files#9651]
### What's the Problem?

At the bottom of Files, there's a horizontal scrollbar that floats a few pixels above the bottom status bar of the window, which means there is a gap of a few pixels where the user can put their cursor between the scrollbar and the status bar, and accidentally drag on a file/folder when they meant to drag the scrollbar.

The same gap problem exists to the right of the vertical scrollbar, but the gap is smaller, maybe just 1 pixel.

### Solution/Idea

Make the gap an invisible part of the scrollbar so any clicks there will still count as clicking the scrollbar.

### Alternatives

Adjust the bottom bound of the part of the window that holds the file list so it stops where the scrollbar's space begins.  That would prevent files from appearing behind the scrollbar, fixing the gap-clicking issue and preventing the file text from being partially obscured/covered by the scrollbar.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Prevent user from clicking a file/folder in the gap between the scrollbar and status bar | Must |
| Prevent the scrollbar from covering the text of the file listing | Should |
| Give us a scrollbar thickness setting | Could |

### Files Version

2.3.0.0

### Windows Version

Win 11 21H2

**Comment by yaichenbaum** [comment]
This looks like an issue with the ListView control, can you open an issue on the WinUI repo?

**Comment by Germs2004** [comment]
It seems unlikely that the scrollbar control would get changed by Microsoft over this since this it seems like this is caused by a stylistic choice by the app developer, not a flaw in the clickable area of the scrollbar control.  You could fix the issue in the app by shrinking the file listing panel a few pixels so it doesn't overlap the scrollbar area so much.

**Comment by yaichenbaum** [comment]
@Germs2004 this is specific to the list view control, not the scroll bar control, while we could retemplate the control, the area behind the scrollbar shouldn't be clickable in any app. It's a pretty simple change on their end so other than limited resources, I think it's a reasonable request to open on the WinUI repository.
