### ISSUE TITLE
Crashing while interacting on Google Drive

### ISSUE THREAD

**Issue by simonMDschu** [files-community/Files#9652]
### Description

It happens a bit randomly, but mostly when moving around files or navigating too fast.

### Expected behavior

No crash

### Files Version

Version: 2.3.3.0 OS Version: 10.0.19044.1826

### Windows Version

Version	10.0.19044 Build 19044

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/9259737/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/9259738/debug.log)

**Comment by gave92** [comment]
Are you using Column view layout mode? Does it happen for other layouts?

**Comment by simonMDschu** [comment]
I mostly use Column layout. Unsure if it happens in the other layouts. I'll try using another mode to make sure.

**Comment by Josh-65** [comment]
@simonMDschu is this still an issue in 2.3.11 (stable release)?

**Comment by simonMDschu** [comment]
No it seems to be fixed! Amazing work :)
