### ISSUE TITLE
Cannot create file in folder that requires Admin permission

### ISSUE THREAD

**Issue by phooBarred** [files-community/Files#9655]
### Description

When trying to add a file to a folder, I was prompted to log in as admin. After logging in, I got an AccessDenied message:

![image](https://user-images.githubusercontent.com/90173926/182962702-96bd21e9-5d50-48d0-ba6f-cb9f6c712691.png)

### Steps To Reproduce

1. Click on New > File (or any other option) 
2.  Name the item, press enter

### Expected behavior

Create new files/folders in folders that need admin permission

### Files Version

Version: 2.3.3.0 OS Version: 10.0.19044.1766

### Windows Version

Microsoft Windows [Version 10.0.19044.1766]

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9263788/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9263805/debug_fulltrust.log)

**Comment by Josh-65** [comment]
Does it work in File explorer? As i can add folder to admin requiered areas?

**Comment by phooBarred** [comment]
I used Explorer to successfully add the folder.

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by phooBarred** [comment]
I got an error -
Cannot open app package
Reason: Error in parsing the app package.

**Comment by yaichenbaum** [comment]
@phooBarred accidentally deleted that comment, can you try again after restarting Windows?

**Comment by yaira2** [comment]
Merging with #10422

**Comment by yaira2** [comment]
This issue is resolved in our dev branch and will be included in the next release.
