### ISSUE TITLE
Cannot open a zip file directly into Files V2 without extracting it.

### ISSUE THREAD

**Issue by AdishSagarawat** [files-community/Files#9658]
### Description

This is what happens:

![Uploading image.png…]()

### Steps To Reproduce

Set Files V2 as Default Explorer
Open any .zip file
Choose Files V2 as Always 
You will get the error.

### Expected behavior

This should open in Files correctly.

### Files Version

2.3.3.0

### Windows Version

Windows 11 22H2 22621.232

### Relevant Assets/Logs

None

**Comment by Josh-65** [comment]
Merging with #7680
