### ISSUE TITLE
no .lnk files on a network drive map

### ISSUE THREAD

**Issue by maoynwa05** [files-community/Files#9659]
### Description

When I open a network drive and  go to my map with shortcuts to programs (.lnk), they are not shown in Files.
However when I open a local drive e.g. D: then they will show up.

### Steps To Reproduce

1: Go to Files and click on a network drive, then a map where there are .lnk files
2: you will not see the lnk files where in other file tools the will show up
3: Go to a local drive and a map with .lnk files and you will see them

### Expected behavior

When I click on a network drive and map where there are .lnk files, I want to see them also in Files

### Files Version

Versie: 2.3.3.0 OS Version: 10.0.19044.1826

### Windows Version

Windows 10 Enterprise 21H2 build 19044.1826

### Relevant Assets/Logs

![view-double-commander-network-drive](https://user-images.githubusercontent.com/56830976/183073195-0ad70db6-149a-422f-a9a4-e646a310ef56.png)
![view-local-drive-thru-Files](https://user-images.githubusercontent.com/56830976/183073198-07667267-4e8e-45aa-bba2-1c9312084fa8.png)
![view-network-drive-thru-Files](https://user-images.githubusercontent.com/56830976/183073199-52fe4352-0e2d-45f7-a990-97d14262110f.png)

**Comment by Josh-65** [comment]
Merging with #2436
