### ISSUE TITLE
Sidebar Icons Not Always Showing

### ISSUE THREAD

**Issue by i-dont-know-username** [files-community/Files#9662]
### Description

Sometimes, when the app is opened, not all icons are shown: all names of locations in the sidebar do appear, but their respective icons do not. I find this happens occasionally after opening the app after a restart.

### Steps To Reproduce

1. Go to the Start Menu.
2. Click the Power button.
3. Click “Restart”.
4. Enter login information.
5. Immediately open the Files app.
6. Observe the Sidebar.

### Expected behavior

I expect all icons in the sidebar to correctly load in next to their respective names.

### Files Version

2.3.3.0

### Windows Version

Windows 11 Home 21H2 22000.832

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/9273806/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/9273807/debug.log)
<img width="960" alt="image" src="https://user-images.githubusercontent.com/110698934/183774253-c68d9b03-b6d6-45c1-84a5-ac6de0630738.png">

**Comment by Josh-65** [comment]
This is possible fixed in the preview version https://files.community/download/preview

**Comment by i-dont-know-username** [comment]
> This is possible fixed in the preview version https://files.community/download/preview. Can you test it

I'll give it a test for a while, then reply after testing, thank you.

**Comment by i-dont-know-username** [comment]
Ok, I've been testing it for a good while now by restarting my computer and and opening a closing the app a lot deliberately to force it to load up from scratch lots. I'm delighted to tell you that the bug doesn't seem to exist there! Thanks!

**Comment by Josh-65** [comment]
Great just comment here if it does.
