### ISSUE TITLE
Preview pane is not updating 

### ISSUE THREAD

**Issue by RRoland80** [files-community/Files#9663]
### Description

When I select something the preview shows up but when I try selecting something else the filename is the new file, but the preview is the old.
So I have a.pdf I click on it shows in the preview pane the contents and under it that that is a.pdf but when I click on b.pdf it shows still the a.pdf preview but the b.pdf filename

### Steps To Reproduce

1. Enable Preview pane
2. click on something
3. then click on something else
(I've  tested it with: PDF, JPG, GIF)

### Expected behavior

The preview would update and show the file that I selected, not the first

### Files Version

Version: 2.3.3.0 OS Version: 10.0.22000.795

### Windows Version

Windows 11 Pro 21H2 22000.795

### Relevant Assets/Logs

![kép](https://user-images.githubusercontent.com/85296423/183243418-7bbf1a63-991c-497d-906d-378663aa65f9.png)
![kép](https://user-images.githubusercontent.com/85296423/183243429-0f132a56-6ac6-4f1e-b29b-de4eb6630005.png)

**Comment by gave92** [comment]
Merging with #9196
