### ISSUE TITLE
Files List (Details Mode) can set the column width uniformly

### ISSUE THREAD

**Issue by terry1976** [files-community/Files#9665]
### What's the Problem?

Files List (Details mode) can only be set one by one in each window

### Solution/Idea

Files List (Details Mode) can set the column width uniformly

### Alternatives

Files List (Details Mode) can set the column width uniformly

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.3.3.0

### Windows Version

Windows 10 21H2

**Comment by Josh-65** [comment]
What do yuo mean set in eatch window. What are you trying to do and want to happen?
