### ISSUE TITLE
An option to disable the animations!

### ISSUE THREAD

**Issue by waleedrana777** [files-community/Files#9666]
### What's the Problem?

Animations slow down the app and also use my cpu or gpu so even with windows animations disabled, app reenables the windows  animations settings which is a cool feature but I like it faster than beautiful! Thanks for the amazing app!

### Solution/Idea

Option to disable animations!

### Alternatives

Probably remove few animations!

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish faster performance over fancy animations | Must |
| This proposal will allow end users to accomplish run multiple app with smooth experience| Should |

**Comment by yaichenbaum** [comment]
Animations can be disabled via the Windows settings app.
