### ISSUE TITLE
When opening the Downloads folder, the view is already scrolled down a bit

### ISSUE THREAD

**Issue by maximedrouhin** [files-community/Files#9670]
### Description

When opening the Downloads folder, if it has vertical overflow and files are grouped by date, the view is already scrolled down to the second or third date group, when it should be entirely scrolled up. I tested this on two different devices, which both have this bug.

### Steps To Reproduce

Prerequisites. The "Group By Date created" option must be enabled in the Downloads folder, files should be sorted by descending dates, and you should have a Downloads folder with enough files to cause a vertical overflow.

1. Open an instance of Files
2. Open the Downloads folder.
3. You should observe that the view is already scrolled down to the second or third date group. If you scroll and reload, the view will again be scrolled down to the second or third date group.

### Expected behavior

The view should begin at the first files. In other words, I shouldn't have to scroll up to find the file I just downloaded!

### Files Version

Version: 2.3.3.0 OS Version: 10.0.22000.795 (test 1) / Version: 2.3.3.0 OS Version: 10.0.19044.1826 (test 2)

### Windows Version

Windows 11 21H2 22000.795 (test 1) / Windows 10 21H2 19044.1826 (test 2)

### Relevant Assets/Logs

None

**Comment by gave92** [comment]
Merging with #6186
