### ISSUE TITLE
Support searching multiple tags

### ISSUE THREAD

**Issue by nilayjoshi89** [files-community/Files#9671]
### What's the Problem?

Recently, support for adding multiple tags was introduced. However, there's no support for multiple tag searches.
Example - File **A** is tagged **Blue** & **Green**. File **B** is tagged **Green**.
Looking up for `tag:Green` should list file **A** & **B** both.
Looking up for `tag: Green, Blue` should list file **A**. 

### Solution/Idea

The search box can be enhanced to support multiple tag lookups. Values can be comma separated (one of many approaches).
Here, the solution/idea depends a lot on the strategy decided for the Search box. 

I believe, it should support advanced multi-field search like `tag:Azure Name:ABC type:txt`.

### Alternatives

As of now, there are no alternatives available.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow the end user to fully utilize the multi-tag feature  | Must |

### Files Version

2.3.5.0

### Windows Version

Windows 10 Pro - 21H2

**Comment by Pein1911** [comment]
Must improve the search feature.  It only searches first word, can't search contained the word, ex: file named "abc_def" if I search "def" won't nothing be found

**Comment by Pein1911** [comment]
Must improve the search feature. Pls support full funtions like explorer, ex: search by date

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.
