### ISSUE TITLE
When I want to change my network drive's name, it doesn't change.

### ISSUE THREAD

**Issue by WiktorWdowiak** [files-community/Files#9672]
### Description

In Files app, I tried to change the name of my network drive. It didn't work though, and name changed from "0" to "0 (\\192.168.1.9@8080\storage\emulated) (M:)".

### Steps To Reproduce

1. In 'Network Drives' go to 'Network'.
2. Right-click on a blank space and select "Map network drive..."
3. Map the drive.
4. In Home, right-click on newly maped drive.
5. Go to "Proporties" and change the name.
6. Click on "OK".
7. Accept (yes) all Powershell prompts.
Drive name doesn't change

### Expected behavior

After accepting all prompts, I expected the drive name to change.

### Files Version

Version: 2.3.3.0 OS Version: 10.0.25174.1010

### Windows Version

Windows 11 22H2 25174.1010

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9277219/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9277220/debug_fulltrust.log)

**Comment by Josh-65** [comment]
Merging with #6154
