### ISSUE TITLE
Make Files more compact

### ISSUE THREAD

**Issue by rudolphos** [files-community/Files#9673]
### What's the Problem?

Currently Files can show only **30 files** in 1920x1080 resolution compared to File Explorer which can show **43 files** in detailed view.

### Solution/Idea

Add an option to reduce unnecessary padding more so that it can fit an equal size of items in one view, just like currently on Windows File Explorer.
![files vs file explorer](https://user-images.githubusercontent.com/4366810/183313104-96213e8a-7f88-4bbc-9585-d180bf3b7105.png)

### Alternatives

Using default File Explorer

### Files Version

Files.Package_2.3.6.0_x64_Sideload

### Windows Version

Windows 10 21H2 19044.1826

### Comments

I don't use a touch screen device so I don't need that large paddings. 
Also this will increase user productivity since we can see more files in one view without having to scroll to see more files..

**Comment by yaichenbaum** [comment]
You can reduce padding by turning on the compact mode setting.

**Comment by rudolphos** [comment]
I had already done that and max I could get was 30 items in detailed list.

**Comment by yaichenbaum** [comment]
We're tracking a request to make this even more compact in another issue.
