### ISSUE TITLE
Bug: Sidebar icons are blurry

### ISSUE THREAD

**Issue by NyaDoo** [files-community/Files#9678]
### Steps To Reproduce

1. Sidebar icons are low resolution 

### Expected behavior

- Use higher resolution icons

### Files Version

2.3.6.0

### Windows Version

Win11 22H2 Preview 25174.1010

**Comment by carlosvsilva** [comment]
Also they look abnormally small here (in a 14" screen at native 1920x1080 and Win11 22H2 125% zoom level) out of line with the design.

**Comment by yaichenbaum** [comment]
This is resolved in the preview build https://files.community/download/preview
