### ISSUE TITLE
When deleting a file or directory that requires administrator privileges, it cannot be deleted properly.

### ISSUE THREAD

**Issue by NyaDoo** [files-community/Files#9679]
### Description

When deleting a file or directory that requires admin permissions, Files asks for admin permissions, and when I agree to give permissions, the deletion cannot be done. Deletion progress is always 0%
I can delete it again, this time without repeated requests for admin rights and the file can be deleted normally.

### Expected behavior

Files can be properly deleted after consent is granted.

### Files Version

2.3.6.0

### Windows Version

Win11 22H2 Preview 25174.1010

### Relevant Assets/Logs

。

**Comment by Josh-65** [comment]
You will need to upload the logs files directly to github. You can get them in files settings > about > open log folder.
