### ISSUE TITLE
When I open a folder on the desktop, Files need a significant startup time (compared to the system's own resource manager), is it possible to speed up the startup speed?

### ISSUE THREAD

**Issue by NyaDoo** [files-community/Files#9680]
### Solution/Idea

Is it possible to speed up the startup process of Files in some way, such as loading Files at system startup and keeping them persistently in the background, so that they can be quickly called up when needed.

### Alternatives

Is it possible to speed up the startup process of Files in some way, such as loading Files at system startup and keeping them persistently in the background, so that they can be quickly called up when needed.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.3.6.0

### Windows Version

Win11 22H2 Preview 25174.1010

**Comment by gave92** [comment]
Merging with #4180

**Comment by yaira2** [comment]
We're excited to share that startup performance will be significantly improved in the upcoming release of version 3. You can download the preview version from our website https://files.community/download.

**Comment by yair100** [comment]
@NyaDoo we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
