### ISSUE TITLE
There is a significant delay in the right-click menu

### ISSUE THREAD

**Issue by NyaDoo** [files-community/Files#9681]
### Description

There is a noticeable lag when the right-click menu is called up. The top half of the menu is displayed first, followed by a pause before the rest of the menu is displayed.

### Expected behavior

Smooth display of right-click menu

### Files Version

2.3.6.0

### Windows Version

Win11 22H2 Preview 25174.1010

### Relevant Assets/Logs

。

**Comment by yaichenbaum** [comment]
Thank you for your feedback, we're working on improving performance and hope to have more to share in the coming months.
