### ISSUE TITLE
Icons do not display correctly when folders are pinned to the start menu

### ISSUE THREAD

**Issue by NyaDoo** [files-community/Files#9683]
### Description

When pinning a folder to the start menu via Files, the folder appears as an icon for Files, not the icon the folder itself has. In the file explorer that comes with the system, the icon of the folder itself can be displayed correctly after pinning to the start menu.

### Expected behavior

The icon for the folder itself is displayed correctly.

### Files Version

2.3.6.0

### Windows Version

Win11 22H2 Preview 25174.1010

### Relevant Assets/Logs

。

**Comment by yaichenbaum** [comment]
Thank you for your feedback, File Explorer has special permissions to modify the pinned icon, but other apps are limited to using their own icon. Based on our research, there are some modifications we can make to the system, but it would require changing registry keys and it's something that we try to stay away from.
What happens if you pin the folders from File Explorer and then set Files as the default file manager?

**Comment by NyaDoo** [comment]
> Thank you for your feedback, File Explorer has special permissions to modify the pinned icon, but other apps are limited to using their own icon. Based on our research, there are some modifications we can make to the system, but it would require changing registry keys and it's something that we try to stay away from. What happens if you pin the folders from File Explorer and then set Files as the default file manager?

if pin the folders from File Explorer and then set Files as the default file manager. The folder's icon is displayed correctly, and it can be opened normally with Files.

**Comment by yaichenbaum** [comment]
I think that's the best option for now, we'll keep this feedback in mind if we come across a way to implement it in the future.

**Comment by NyaDoo** [comment]
> I think that's the best option for now, we'll keep this feedback in mind if we come across a way to implement it in the future.

These are some of my ideas: you can list the functions that need to modify the registry separately and permanently put them in the "experimental project", or issue them as an extension package, instead of not implementing them. Of course, we should try not to modify the registry file. But I think the purpose of Files is to replace the file resource manager of the system with a more efficient and easy-to-use existence. So I think it is more important to make it more perfect. Instead of using the file resource manager that comes with the system in some cases, this makes the whole thing more complicated and troublesome rather than simpler and more efficient. Making Files more perfect should be the first important thing, and then try not to modify registry files.

**Comment by yaichenbaum** [comment]
Unfortunately, users treat experimental features the same as production features and complain when removing the app messes up their device. This also causes certification issues with the Store and is out of our control.
Windows 10 had official support for this so it's possible they plan to add this back to the Start Menu but didn't get a chance yet.
