### ISSUE TITLE
Create Shortcut feature not working

### ISSUE THREAD

**Issue by NyaDoo** [files-community/Files#9684]
### Description

The Create Shortcut feature is not working properly. When I click the Create Shortcut option in the right-click menu, nothing changes, nothing happens.

### Expected behavior

。

### Files Version

2.3.6.0

### Windows Version

Win11 22H2 Preview 25174.1010

### Relevant Assets/Logs

。

**Comment by NyaDoo** [comment]
In addition, I use files as the default file manager.

**Comment by Josh-65** [comment]
Where are you making the shortcuts

**Comment by NyaDoo** [comment]
> Where are you trying to making the shortcuts

Create shortcut in the right-click menu of Files

**Comment by Josh-65** [comment]
whats the path to the folder your making it at

**Comment by yaichenbaum** [comment]
Can you upload the log files?

**Comment by NyaDoo** [comment]
> Can you upload the log files?
This is log. Also the issue seems to be related to folder permissions. This occurs when the folder in which it is located requires admin rights to write (the program does not ask for permission).
[debug.log](https://github.com/files-community/Files/files/9305684/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9305685/debug_fulltrust.log)

**Comment by Josh-65** [comment]
Merging with #7211

**Comment by NyaDoo** [comment]
Create shortcut in the right-click menu of Files.

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
