### ISSUE TITLE
Tabs is hidden by title bar after changing theme

### ISSUE THREAD

**Issue by illuminati2412** [files-community/Files#9685]
### Description

As you can see, the interface of Files is above and the Chrome interface is below.

The tabs of Files is hidden by the title bar, while the tabs of Chrome is not.

Please fix this bug.

Thank you very much.

![desktop-1](https://user-images.githubusercontent.com/101368833/183652434-f9beb158-5458-43b2-8e03-cf6ccd789f56.jpg)

### Steps To Reproduce

1. Install Stardock Curtains.
2. Go to https://www.deviantart.com/niivu/art/Gruvbox-for-Windows-913766735 to download a free Gruvbox theme.
3. Add the Gruvlace Dark style.
4. Apply style to change theme.

### Expected behavior

Tabs is hidden by title bar after changing theme

### Files Version

Version: 2.3.6.0 OS Version: 10.0.19044.1865

### Windows Version

Windows 10 Enterprise LTSC 19044.1865

### Relevant Assets/Logs

![desktop-1](https://user-images.githubusercontent.com/101368833/183655152-486a0d24-6c71-4186-a2fe-c3e271c30b4a.jpg)

**Comment by yaichenbaum** [comment]
Stardock themes don't work well with UWP apps, I encourage sharing this feedback with Stardock but I'm not sure how much they can do given the nature of UWP and AppWindow.

**Comment by yaichenbaum** [comment]
@illuminati2412 did you apply this theme when Files was already open?
![image](https://user-images.githubusercontent.com/39923744/183708502-f4120edb-73b3-4488-917d-2298bd6e8a1a.png)

**Comment by riverar** [comment]
Stardock employee here.

I can't download the theme you mentioned -- it's watchers only. Can you email a copy to me (`rrivera@stardock.com`)? I can't reproduce this with other styles so might be specific to that one?

![image](https://user-images.githubusercontent.com/475132/183708883-8743a7db-b6e8-4218-b437-ea5dd9eb5e6e.png)
