### ISSUE TITLE
Bug: Restore option in the Recycle Bin does not appear for shortcuts

### ISSUE THREAD

**Issue by NyaDoo** [files-community/Files#9686]
### Description

The "Restore" option in the Recycle Bin sometimes does not appear.
This is a probabilistic problem, of course, the probability of occurrence is not low. Sometimes the Restore tab of the Recycle Bin does not appear. Especially when I choose to let Files take over the file explorer that comes with the system and open the recycle bin directly from the desktop icon, the restore tab will most likely not appear.

### Expected behavior

。

### Files Version

2.3.6.0

### Windows Version

Win11 22H2 Preview 25174.1010

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/65238336/183655537-45346655-0273-4868-bb55-c56d6c8106d5.png)
[debug.log](https://github.com/files-community/Files/files/9290881/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9290883/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
Does it load if wait 30 seconds?

**Comment by NyaDoo** [comment]
> 如果等待 30 秒，它会加载吗？

Still won't show. I seem to have found the source of the problem, which seems to be related to the format of the file being deleted. What I've found so far is that if the deleted file is a shortcut (.ink) then the restore button doesn't show. If it is a file of other format, the restore button can be displayed correctly.

**Comment by NyaDoo** [comment]
> Does it load if wait 30 seconds?

Still won't show. I seem to have found the source of the problem, which seems to be related to the format of the file being deleted. What I've found so far is that if the deleted file is a shortcut (.ink) then the restore button doesn't show. If it is a file of other format, the restore button can be displayed correctly.

**Comment by yaichenbaum** [comment]
I believe that shortcuts can't be restored in Files @gave92

**Comment by Josh-65** [comment]
It doesnt show for anything #9561

**Comment by yaichenbaum** [comment]
Merging with #9897
