### ISSUE TITLE
No Folder Tree Option

### ISSUE THREAD

**Issue by MentalBrain** [files-community/Files#9687]
### What's the Problem?

In other file browsers there is usually a folder tree to the left that syncs with the folder you're browsing. I did look carefully through the options but didn't see an option to show this. I find a folder tree very useful and would love to have it in the Files app. It's not essential to my workflow, but it's just an easy, quick way to navigate to nearby folders. 

### Solution/Idea

Add a folder tree pane under the "Drives" area, like what is available in Windows Explorer.

### Alternatives

I've used both Windows Explorer and xplorer2, which both have this feature. 

### Priorities

| Allow users to see a folder tree area in the interface that syncs with current open folder | Should |

**Comment by gave92** [comment]
Merging with #1928.

**Comment by yair100** [comment]
@MentalBrain Tree View is currently available in preview https://files.community/download. It will be included in the next stable release.
