### ISSUE TITLE
Renaming a file using the arrow keys to navigate words in its name, will start selecting other files

### ISSUE THREAD

**Issue by carlosvsilva** [files-community/Files#9691]
### Description

When I'm renaming a file, if I use the arrow keys to navigate between words of its name, the file rename will abort as soon as I navigate to the last or first characters of the name (including extension) and Files start selecting nearby files. 

### Steps To Reproduce

1. Rename file
2. Use left arrow key continuously to rename first characters of filename or right arrow key to rename last characters
3. Files aborts rename operation
4. Files starts selecting other files/folders with the arrow keys

### Expected behavior

Files should only leave the rename operation after an explicit Save or Abort by the **user**

### Files Version

Versão: 2.3.3.0 

### Windows Version

OS Version: 10.0.22621.317 (Win11 22H2 Release Preview)

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9299528/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9299529/debug_fulltrust.log)

**Comment by gave92** [comment]
Also #5824

**Comment by Josh-65** [comment]
Ive noticed it also does it on the search bar with all arrow directions deleting the search bars content. 
With file names i've only had the up and down arrow do it now which I believe normally just goes to start and end of text.

**Comment by gave92** [comment]
Left and right also cause the issue in Grid View. @carlosvsilva what layout mode are you using?

**Comment by carlosvsilva** [comment]
this bug seems to only affect Files when the View is set to Tiles, (Mosaicos), the second of the list, my favourite :)
