### ISSUE TITLE
Bug: Huge (disproportionate) icon overlays (shortcuts, onedrive sync status, etc)

### ISSUE THREAD

**Issue by carlosvsilva** [files-community/Files#9693]
### Description

Icons in Files, when they have an icon overlay (like the famous arrow for shortcuts) or OneDrive sync status of each file, display these overlays in a massive disproportionate size, covering an extensive area of the main file icon.

I have a 14" inch laptop screen, native 1920x1080 resolution at the optimum 125% system zoom level. 

### Expected behavior

Icon overlay sizing should follow the Windows Explorer sizes.

### Files Version

Versão: 2.3.3.0 

### Windows Version

OS Version: 10.0.22621.382 (Win11 22H2 latest Release Preview)

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/40889421/183901692-fced7c49-7298-4465-b266-43bfa056a7e5.png)
![image](https://user-images.githubusercontent.com/40889421/183902536-1a046f1f-6d18-46f4-a39f-c59738102ff9.png)
![image](https://user-images.githubusercontent.com/40889421/183902573-386e7cbc-9aa5-47a2-9363-b0ec21146b1e.png)
![image](https://user-images.githubusercontent.com/40889421/183902855-cb13c9dd-359a-4354-bf49-cc065cec82d9.png)
[debug.log](https://github.com/files-community/Files/files/9300039/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9300040/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview build? https://files.community/download/preview

**Comment by ferrariofilippo** [comment]
> Is this still an issue in the preview build? https://files.community/download/preview

It seems to have been fixed in the preview build

**Comment by yaira2** [comment]
It looks like that's working as expected, should be about the same in File Explorer. Can you check?

**Comment by yaira2** [comment]
I see, can you open a new feature request to track this? "Feature: Reduce shortcut icon overlay"
