### ISSUE TITLE
Details view: Column management

### ISSUE THREAD

**Issue by ekko84** [files-community/Files#9695]
### What's the Problem?

At the moment in Details you cannot:

- re-arrange the column order (i.e. drag and drop columns)
- Add certain columns like w standard File explorer

### Solution/Idea

Enable the ability to 
- re-arrange the column order (i.e. drag and drop columns)
- Add certain columns like w standard File explorer

### Alternatives

n/a

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.3.3.0 OS Version: 10.0.19043.1826

### Windows Version

Windows 10 21H1 (build 19043.1826)

**Comment by gave92** [comment]
Merging with #8385
