### ISSUE TITLE
Feature request: Change layout to Windows 10 style thumpnails etc... (pictures/music)

### ISSUE THREAD

**Issue by F3000** [files-community/Files#9696]
I hope that this is possible to implement

example of what i mean:
![image](https://user-images.githubusercontent.com/8161283/184016049-87a2d2a0-5a98-4e63-a9cc-79f873f3bf1b.png)

**Comment by gave92** [comment]
.. like this?
![image](https://user-images.githubusercontent.com/9673091/184016553-794e2bc0-ebfd-4d4c-b4a2-2000155287d0.png)

**Comment by F3000** [comment]
No I mean the older icons for the standard folders .

Maybe you have another idea .

![image](https://user-images.githubusercontent.com/8161283/184030937-2a297523-c5d4-40ca-84a6-4ffe9dae11b3.jpeg)

**Comment by gave92** [comment]
Ah you wish to have the old icons on windows 11? Then no sorry, we plan to keep using the System provided icons for now.
