### ISSUE TITLE
Request: compress into ZIP

### ISSUE THREAD

**Issue by jolopapina** [files-community/Files#9697]
### What's the Problem?

Files App can't compress folder into zip, while default Explorer can

### Solution/Idea

Add that function

### Alternatives

Using default explorer/install archiver

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.3.6.0

### Windows Version

Windows 11 25179

**Comment by gave92** [comment]
Merging with #45. For now you can create an empty zip file from the new menu and then drag&drop stuff into it.
