### ISSUE TITLE
New "Open with" window not supported in Files app

### ISSUE THREAD

**Issue by jolopapina** [files-community/Files#9698]
### Description

Since new UI for "Open with" was officialy added into Windows 11, clicking "choose another app" do nothing

### Steps To Reproduce

1. Click RMB on files
2. Hover cursor over "Open with"
3. Click "Choose another app"

### Expected behavior

"Open with" popup appearing

### Files Version

2.3.6.0

### Windows Version

Windows 11 25179

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/80640396/184026193-a779df08-b5de-4542-899d-d08dd7b7fc57.png)

**Comment by yaichenbaum** [comment]
Microsoft is still working on this menu and will fix the issue before shipping.
