### ISSUE TITLE
Bug: Dual pane isn't restored after restarting the app

### ISSUE THREAD

**Issue by tywunon** [files-community/Files#9701]
### Description

If I have Dual pane mode on, after closing the App and opening it again Dual pane mode is off.
But the weird thing is, the App thinks it is in Dual Pane mode. So i have to "Close pane" and "New pane" to get Dual pane mode again.

### Steps To Reproduce

1. Open App
2. Click on the 3 dots in the upper right corner and click "New Pane" or use [Alt]+[Shift]+[+]
3. Close App
4. Open App
5. See App has only one pane
6. Click on the 3 dots in the upper right corner
7. See "Close pane"

### Expected behavior

If Dual pane is open and shown I expect it to to see 2 panes after I restart the App.

### Files Version

Version: 2.3.6.0 OS Version: 10.0.19044.1826

### Windows Version

Windows 10 Enterprise

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/1228039/184170201-7a97ea54-1e8c-472a-9823-120997953615.png)

**Comment by Tback1** [comment]
I have the question too. 2.3.6.0 iscorrect but happened In 2.3.7.0. And the title will show two panel but acturally not

![image](https://user-images.githubusercontent.com/8872546/185598330-b69fe2d6-8ea3-4f30-9edb-018f454b6fd2.png)

**Comment by yaichenbaum** [comment]
I can't reproduce this issue, do you have "Continue where you left off" turned on?
![image](https://user-images.githubusercontent.com/39923744/195650065-803c88d0-3b53-4c94-8c61-0bcd1338611d.png)

**Comment by tywunon** [comment]
Just tried that still the same behavior.

**Comment by tywunon** [comment]
may I upload a Video to youtube and post the link here?

**Comment by tywunon** [comment]
https://youtu.be/Qg1TDG7OlOA

**Comment by yaichenbaum** [comment]
> may I upload a Video to youtube and post the link here?

You can upload the video directly to GitHub

**Comment by tywunon** [comment]
> 

I tried, but it said mkv is not supported

**Comment by tywunon** [comment]
The Preview works. So it might already been fixed.

Weird think to me, the preview starts without the 2nd pane, if you not turn on "Continue where you left off" I would think if the 2nd pane was open before closing it would come up with dual pane but both sides at Home, and "Continue where you left off" would only store what folders were open. But I think that's just me.
