### ISSUE TITLE
Compatibility settings ok button not working at all

### ISSUE THREAD

**Issue by Theoldnation** [files-community/Files#9702]
### Description

for no reason in my files the OK button won't work at all even without moving a thing on compatibility in properties, also doesn't work when trying to apply a compatibility setting

### Steps To Reproduce

just go to compatibility settings in any exe properties and the button will not work at all in the latest sideload stable version

### Expected behavior

properties compatibility ok button not working at all and cannot apply any setting of compatibility tab

### Files Version

2.3.6

### Windows Version

Windows 10 19044.1889

### Relevant Assets/Logs

<img width="345" alt="image" src="https://user-images.githubusercontent.com/76594044/184201556-45c41411-8bde-4424-82d3-08a5a7d5b013.png">

**Comment by Theoldnation** [comment]
For no reason the thing won't let me attach the log in main comment so i will be attaching them here
[debug.log](https://github.com/files-community/Files/files/9310803/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9310804/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
