### ISSUE TITLE
Localization incomplete for French

### ISSUE THREAD

**Issue by QuaintMako** [files-community/Files#9703]
### Description

Some of the localization in French has not been made, probably only on the latest additions.

### Steps To Reproduce

1. Go to \src\Files.Uwp\Strings\fr-FR\Resources.resw
2. Get to the bottom of the file.
3. Observe that some strings are still in English.

### Expected behavior

All the localization properly translated in this file.

### Files Version

V.2.3.6.0

### Windows Version

W11 22000.856

### Relevant Assets/Logs

![MissingFrenchLoc](https://user-images.githubusercontent.com/110472580/184213677-1cc49255-72a5-44f9-804c-49b89f525af2.png)

**Comment by QuaintMako** [comment]
I can take care of the traduction. I'm making a bug out of it to have it validated as a task and properly track the issue with a #.

**Comment by yaichenbaum** [comment]
@QuaintMako thank you for reporting this issue, progress for localization is tracked on Crowin https://crowdin.com/project/files-app.

**Comment by Gegen103** [comment]
There is a bad translation :
- right clic on an item from Favorites (not the first one)
- To order this item in the first position, it's written "Descendre tout en haut" but it should be "Monter tout en haut"

**Comment by QuaintMako** [comment]
> There is a bad translation :
>     * right clic on an item from Favorites (not the first one)
>     * To order this item in the first position, it's written "Descendre tout en haut" but it should be "Monter tout en haut"

Thanks for notifying us, this has been taken care of. The proper translation will be push to Files in an upcoming update.
