### ISSUE TITLE
I can't batch rename? Rename auto sequences like windows 11

### ISSUE THREAD

**Issue by Leebo-missile** [files-community/Files#9705]
### What's the Problem?

I can't batch rename?
My most used feature in windows exlporer is batch renaming files. I highlight files I wanted renamed, clear the name hit enter and it auto renames al the files into a sequence. It's very useful for bulk or batch renaming files, with your app highlighting multiple files greys out rename.

### Solution/Idea

Give me a batch rename feature, for smart renaming, alow it to name sequences of files easily, give me many rename options for deailing with my own personal files like images or video clips, this was the reason i loked for a replacement i needed an app that had better solution for working with massive amount of files i have over 200,000 video clips and images i work with, sometimes just opening the folder crashes regular file explorer. I need to go in rename things make new folders zip files to fit under a certain size, these features are hard to do in your ap,p, make batch renaming easy.

### Alternatives

going back to regular file explore until i can batch rename like the built in windows 11 feature.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version 2

### Windows Version

Windows 11

### Comments

none

**Comment by yaichenbaum** [comment]
Thank you for your feedback, batch renaming is something we'd like to implement and is being tracked in #8191.

**Comment by Leebo-missile** [comment]
id like to further comment that using power tools is not a good solution, it's clunky and time consuming and doesn't allow for quick batch renaming, windows 11 i highlight files, hit rename, delete title hit enter, and it auto renames all files, 1.file, 2.file, 3.file, 4.file. I don't need anything advanced but bulk renaming is so useful, type in "new name" with batch selected and it sequences files with the new name. "1 new name.file , 2 new name.file , 3 new name.file I dont want to right click and navigate through many menus just click multiple files very easily see the rename button type in my new name or delete and have eit auto sequence.

**Comment by yaichenbaum** [comment]
That's correct, this request is a lot more simple to implement than something like Power Rename.
