### ISSUE TITLE
Loading screen for copying files

### ISSUE THREAD

**Issue by KamielS** [files-community/Files#9706]
### What's the Problem?

I often doubt if a file coming from for instance a remote server is successfully copying to my files-folder.

### Solution/Idea

A loading screen for the copying of a file or folder would be helpful. 

### Alternatives

A small status-bar or -wheel within the same files screen would be helpful as well.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.3.6.0

### Windows Version

 OS Version: 10.0.22000.856

### Comments

I love files, especially since the latest update. Keep up the good work!

**Comment by Josh-65** [comment]
There is in the top right corner when an opration is beeing done
