### ISSUE TITLE
Additional feature.

### ISSUE THREAD

**Issue by ozanuzer** [files-community/Files#9707]
Can you add files drag and drop to bitvise ssh folder pane? I use most of the time that software. It is not big deal for usage but If it is easy integrate to app. I will very happy. Thank you.

**Comment by Josh-65** [comment]
Files supports drag and drop on to anything that also accepts it. If bitvise ssh does then please open a new issue following the bug report template

**Comment by ozanuzer** [comment]
I can drag and drop with native windows file explorer but files app can't. I think bitvise ssh accept drag and drop. I confused, is it relation with files app or bitvise ssh?
