### ISSUE TITLE
List view

### ISSUE THREAD

**Issue by dpbueno** [files-community/Files#9708]
### Solution/Idea

I think it would be interesting to have a view in list format

### Alternatives

I think it would be interesting to have a view in list format

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by gave92** [comment]
Merging with #2509

**Comment by yaira2** [comment]
@dpbueno thank you for your patience, I'm excited to share that a List View layout will be included in the next release.
