### ISSUE TITLE
Feature: Add an option to open tab in the existing window instead of opening a new one

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#9709]
### What's the Problem?

When I forgot files is open I open it from the start menu which opens a new instance rather then adding a tab.

### Solution/Idea

- Add setting to adjust "Open new instance when launching Files"
- Remove existing setting for "Open new instance when opening directories from the taskbar jumplist"

**Comment by yaichenbaum** [comment]
I think we can change the behavior of this setting to work even when it's not from the taskbar jumplist.
![image](https://user-images.githubusercontent.com/39923744/184662274-ac1dcc86-9724-4ad5-a173-fb59355e342f.png)
