### ISSUE TITLE
Open folders with long loading times will impact all folders in FileManager

### ISSUE THREAD

**Issue by lsyanling** [files-community/Files#9713]
### Description

My `Network Location` needs a long time to load, so when I open `Network Location`, it takes time to load, and in the time, if I choose to open other folders instead of wait, they will not be loaded and `File Manager` will display empty until the Network Location is completely load.

### Steps To Reproduce

1. Open Files App.
2. Click one of `Network Drives` in left column, and it usually takes long time to load.
3. Not wait and click any other drives.
4. Then you can see nothing until the `Network Drive` you Clicked is loaded completely.

### Expected behavior

If I choose to open other folders instead of wait, `File Manager` should stop loading the Network (In fact all folders which take long times) and just load the folder immediately which I newly opened.

### Files Version

Version: 2.3.6.0

### Windows Version

OS Version: 10.0.25179.1000

### Relevant Assets/Logs

I can't copy the files maybe because of the `EFS Encrypting` or `Group Policy`

**Comment by gave92** [comment]
Merging with #9566
