### ISSUE TITLE
It just open the mainpage instead of openning the filepath

### ISSUE THREAD

**Issue by RAint0** [files-community/Files#9714]
### Description

if click `Open the folder`or `Open the file location` on another application or rightclick menu，files just open the main pages.
`Open log location` on files is not work too.

### Steps To Reproduce

click `Open the folder`or `Open the file path` on another application or rightclick menu.
`Open log location` on files is not work too.

### Expected behavior

It just open the mainpage instead of openning the filepath what it's supposed to do.

### Files Version

2.3.6.0 OS Version: 10.0.22000.856

### Windows Version

Windows 11 21H2 22000.856.0 Simplified Chinese version

### Relevant Assets/Logs

https://user-images.githubusercontent.com/53421546/184468775-c7630f32-1bc6-4684-8a29-74779515f59f.mp4

In the vedio ,it just open the "主页"（main pages）instead of openning the log location.

**Comment by Josh-65** [comment]
You will need to upload the logs files directly to github. You can get them in files settings > about > open log folder. 
Also what program are you opening from?

**Comment by RAint0** [comment]
> Can you try turning off the default file manager option and turning it back on?

I turn on the default file manager option but it still show the off status. So i can't turn it off. I have uninstell the files and recover the registry. I'm sure  `default file manager option` cause the problem. Maybe it do something wrong with registry.

**Comment by yaichenbaum** [comment]
Does reinstalling and setting it as the default again help?

**Comment by RAint0** [comment]
> Does reinstalling and setting it as the default again help?

I reinstalled and set it as the default again and it's worked. Thank you !
But why? Last time I uninstell the files and use the official way in issue #7210 that running UnsetFilesAsDefault.reg to restore windows explorer. But the problems still happen on windows original explorer. So I find another way to recover the registry as below :
copy the command below to a txt file ,rename the file as *.bat  and run the .bat as admin.
```
@echo off
title Restore default file manager by:cangshui.net
reg add "HKEY_CLASSES_ROOT\Folder\shell\explore\command" /v "" /t REG_SZ /d "" /f
reg add "HKEY_CLASSES_ROOT\Folder\shell\explore\command" /v DelegateExecute /t REG_SZ /d {11dbb47c-a525-400b-9e80-a54615a090c0} /f
reg add "HKEY_CLASSES_ROOT\Folder\shell\open\command" /v "" /t REG_EXPAND_SZ /d %SystemRoot%\Explorer.exe /f
reg add "HKEY_CLASSES_ROOT\Folder\shell\open\command" /v DelegateExecute /t REG_SZ /d {11dbb47c-a525-400b-9e80-a54615a090c0} /f
reg delete "HKEY_CURRENT_USER\SOFTWARE\Classes\CLSID\{52205fd8-5dfb-447d-801a-d0b52f2e83e1}" /f
echo.&pause
exit
```
After that, he windows original explorer worked well. Then you tell me to  reinstall and set it as the default again. The problems didn't happened again.
Thank you for help again.

**Comment by Josh-65** [comment]
7210 method is outdated.
