### ISSUE TITLE
Not making a folder.

### ISSUE THREAD

**Issue by TCBombLMG** [files-community/Files#9717]
### Description

In appdata i tried to make a folder but it didnt work.
Then i tried in documents and i did work.

### Steps To Reproduce

Go to %appdata%
Next click on local
Click on new
Then folder
And i tried to name it Blender

### Expected behavior

I expected it to make a folder in appdata where i wanted it too.

### Files Version

Version: 2.3.6.0 OS Version: 10.0.19044.1889

### Windows Version

Windows 10 Version 21H2 Build 19044. 1889

### Relevant Assets/Logs

https://user-images.githubusercontent.com/91377410/184480328-94da7635-0a6c-4b2d-ba4e-0f133d2e7e21.mp4

**Comment by gave92** [comment]
Merging with #9210
