### ISSUE TITLE
An Option to Disable Update Notification

### ISSUE THREAD

**Issue by AkazaRenn** [files-community/Files#9720]
### What's the Problem?

The circumstances where the notifications pop is usually when I need to use the app, which means there's not actually a chance it can get updated, instead it added extra work for me to close the pop up. Also, I prefer to get app updates handled by the store, which had worked pretty well for me.

### Solution/Idea

Add an option to disable the "updates available" notification.

### Alternatives

Completely remove the notification? Don't think it's a good idea.

### Files Version

2.3.6.0

### Windows Version

Windows 11 21H2 22000.856

**Comment by yaichenbaum** [comment]
Are you talking about the notification on the toolbar or the dialog? The dialog is for mandatory updates when an important patch is released, and we want to make sure everyone updates before continuing to use the app.
