### ISSUE TITLE
Feature: Show removable drives in a separate group

### ISSUE THREAD

**Issue by Tochees** [files-community/Files#9723]
### What's the Problem?

![image](https://user-images.githubusercontent.com/99777243/184536197-479caeb8-0ffa-44ed-8ef1-e42709abe0d6.png)
我的可移动SD卡混杂在本地磁盘中显示，这令我很不舒服。

### Solution/Idea

就像Windows7一样，那样可能看起来更方便。

### Alternatives

参考Windows7等单独显示可移动设备

### Priorities

must

### Files Version

2.3.6.0

### Windows Version

Windows11 22621.382

**Comment by yaira2** [comment]
Thank you for your feedback.

**Comment by yaira2** [comment]
@Tochees thank you for your feedback, we wanted to let you know that we don't currently have plans to implement this change.
