### ISSUE TITLE
Right-click `Extract..` options makes Files crash

### ISSUE THREAD

**Issue by inknos** [files-community/Files#9724]
Reproducer:
- Make new folder "test" (**not empty!** put an empty file inside named test)
- Zip it with 7zip for instance, I used `7zip>add to "test.zip"`
- Right click `Extract...` option on "test.zip"
- Choose any of the 3 options
- Files crashes but zip gets extracted

Always reproducible for me.

Specs:
```
Edition	Windows 11 Home
Version	21H2
Installed on	‎13/‎08/‎2022
OS build	22000.856
Experience	Windows Feature Experience Pack 1000.22000.856.0
```
Files version:
```
Version: 2.3.6.0
OS Version: 10.0.22000.856
```

**Comment by Josh-65** [comment]
Merging with #9694
