### ISSUE TITLE
unzipping a folder

### ISSUE THREAD

**Issue by yeliabmit** [files-community/Files#9727]
### Description

I was unzipping a folder into another folder, and the destination window closed unexpectedly (I had Files separated into two windows rather than jumping between tabs) .  I had performed this process six times already so I'm not sure what went wrong this time.

### Steps To Reproduce

Open window holding .zip files
Open window for destination of unzipped folders
Open zipped folder to examine contents
Drag and drop zipped folder from .sip file to destination file

### Expected behavior

As noted this had worked numerous times already so I expected it to work once more.

### Files Version

Version: 2.3.6.0 OS Version: 10.0.19044.1889

### Windows Version

Edition	Windows 10 Home Version	21H2 Installed on	‎2022-‎08-‎01 OS build	19044.1889 Experience	Windows Feature Experience Pack 120.2212.4180.0

### Relevant Assets/Logs

N/A

**Comment by yaichenbaum** [comment]
Merging with #9694
