### ISSUE TITLE
NRT comments on your new Files App

### ISSUE THREAD

**Issue by RustyRover** [files-community/Files#9731]
Hey team:

This is what File Explorer should be – should always have been. It’s clean and neat, without confusing repetitions and you can set it up the way you want. It is what I have been searching for for a long time. However, it seems to me that this is still a work in progress and I am hopeful that that you will improve it greatly as time progresses. With that in mind I have a number of suggestions to pass on to you. 
1.	I have not found a way to add and delete folders in the Folders section.
2.	One ought to be able to show the Libraries and Cloud Drives (and maybe Favorites) sections in the center of the screen but there are no widgets for this.
3.	There is no section for Files in the Sidebar (but there is a widget??).
4.	It seems to me that the Libraries section needs some improvement. Right now, you can only modify it by modifying Libraries in File Explorer. And when you update it puts back all the default libraries. 
5.	If you hide a drive, will it be included in any search you do or not? I would prefer that it not be included.
6.	There ought to be ways to modify all the right click menus as desired. 

I am thrilled that someone is giving a lot of thought to how to do this right. Looking forward to speedy progress.

Sincerely,

Norton R. Townsley

**Comment by yaichenbaum** [comment]
First of all, thank you for the kind words!

> I have not found a way to add and delete folders in the Folders section.

We're planning to sync this with the sidebar (I don't remember the issue number but it exists)

> One ought to be able to show the Libraries and Cloud Drives (and maybe Favorites) sections in the center of the screen but there are no widgets for this.

There used to be a widget for libraries but most people turned it off, so we removed it.

> There is no section for Files in the Sidebar (but there is a widget??).

The sidebar in Files is designed for you to access your most important locations unlike than File Explorer which has a bigger focus on showing recent locations and files. We're planning to create a recent items page which you can pin to the sidebar but until then, we recommend using the widget on the home page.

> It seems to me that the Libraries section needs some improvement. Right now, you can only modify it by modifying Libraries in File Explorer. And when you update it puts back all the default libraries.

You can modify library locations from the properties window.

> If you hide a drive, will it be included in any search you do or not? I would prefer that it not be included.

Searches from the home page include all locations however if you search within a drive or folder, it'll only show results for that location.

> There ought to be ways to modify all the right click menus as desired.

We're tracking this request in another issue (I don't remebber the issue number but a quick search should bring it up). To be transparent, it's unlikely that we'll add support for this but we're tracking it nonetheless and encourage adding your feedback to the issue.

**Comment by RustyRover** [comment]
Yair:

 

Thank you for your responses. 

 

I still think you should have widgets for Libraries and Cloud Drives. The options should still be there for people like me who would need to have maximum control over their apps.

 

I said there was “… no section for Files in the Sidebar…” but what I meant to type was Folders. Sorry. I am older and forget more things these days. Please reconsider this comment. 

 

FYI, I have installed an app called EZ Context Menu and it seems to me that some of the changes I have made to context menus in File Explorer have carried over into Files. 

 

Rusty

**Comment by yaichenbaum** [comment]
> I said there was “… no section for Files in the Sidebar…” but what I meant to type was Folders. Sorry. I am older and forget more things these days. Please reconsider this comment.

You can pin folders to the sidebar by right clicking on them, should be one of the options.

> FYI, I have installed an app called EZ Context Menu and it seems to me that some of the changes I have made to context menus in File Explorer have carried over into Files.

Apps like EZ Context Menu should work for shell extensions 👍
