### ISSUE TITLE
Problem with archived .zip folders

### ISSUE THREAD

**Issue by useful-tool-square** [files-community/Files#9736]
### Description

When I open the new compressed (zipped) folder Files App doesn't open it, and unable to copy any files to my zip folder.
Also popup an error window whie trying to open zip from desktop.
No screenshot because OS environment is not English.

### Steps To Reproduce

1. Create a new zip folder.
2. Open, failed,
3. Copy a file, failed.
4. Open on desktop, error appears, showing file directory.

### Expected behavior

Popup an error window.
![image](https://user-images.githubusercontent.com/98749433/184912486-6c3b3738-9d8c-48c4-88cc-dbddca6fc133.png)

### Files Version

Version: 2.3.6.0 OS Version: 10.0.25179.1000

### Windows Version

Windows 11 23H2 rs_prerelease Build 25719.1000

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9352196/debug.log)

**Comment by yaichenbaum** [comment]
This issue should be resolved with v2.3.7.

**Comment by KibSquib48** [comment]
This happens to me in v2.3.11 from the Store

![image](https://user-images.githubusercontent.com/33189136/187313003-93d1d3be-6bee-4ca2-acb0-e6dfd07d4733.png)

Edition	Windows 11 Home
Version	22H2
Installed on	‎May ‎11, ‎2022
OS build	22622.586
Experience	Windows Feature Experience Pack 1000.22634.1000.0
