### ISSUE TITLE
File dates

### ISSUE THREAD

**Issue by RustyRover** [files-community/Files#9738]
### What's the Problem?

I have just started using your program and I finally had occasion to open up a file folder. I was stunned to see that many times the dates are given as days ago. And there are no times listed. This is a real problem for me and I'm sure it will be for others, too. 

### Solution/Idea

At least give users some way to select whether they want dates shown in days ago format or the date and time format used in File Explorer. Thanks. 

### Alternatives

Only provide File Explorer  date and time format. 

### Priorities

This proposal will allow end users to get file dates in their preferred format | Must|

### Windows Version

Windows 10

**Comment by yaichenbaum** [comment]
You can change the date format from the preferences page in the settings model.

**Comment by RustyRover** [comment]
Oh. Thank G-d!
