### ISSUE TITLE
Bug: No differentiator between the selected element and one that is being hovered over in high contrast mode

### ISSUE THREAD

**Issue by nathanielcwm** [files-community/Files#9739]
### Description

When high contrast is enabled files doesn't seem to correctly follow the system wide settings.

### Steps To Reproduce

1. Enable High Contrast
2. Close Files (for some reason it won't allow itself to be unminimised after high contrast changes.
3. Open and observe

### Expected behavior

High contrast settings are correctly observed.

### Files Version

Version: 2.3.7.0 OS Version: 10.0.19044.1826

### Windows Version

Win 10 10.0.19044.1826

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9355870/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9355871/debug_fulltrust.log)

![image](https://user-images.githubusercontent.com/22572406/185022121-ed2cfe58-853f-46ed-99cc-ff0339c5b21a.png)
![image](https://user-images.githubusercontent.com/22572406/185022142-ac008a16-0191-4d56-876d-870376ad71e4.png)

![image](https://user-images.githubusercontent.com/22572406/185022195-e80735c4-4d6d-40e5-8a7e-011db796d711.png)
![image](https://user-images.githubusercontent.com/22572406/185022209-ad48575c-7f4d-4a29-ba25-57e50a62577a.png)

**Comment by yaichenbaum** [comment]
Can you elaborate on what's not being followed?

**Comment by nathanielcwm** [comment]
Well I presumed that the background colour should follow the system wide setting instead of being red for one.

**Comment by nathanielcwm** [comment]
Another issue of note is that there doesn't appear to be a differentiator between the currently selected element and one that is being hovered over.
![image](https://user-images.githubusercontent.com/22572406/185026659-001dee5c-de15-4856-bab1-37946c817a6f.png)

Explorer uses a white outline, but the WinUI demo also appears to do a similar thing.

**Comment by yaichenbaum** [comment]
> Well I presumed that the background colour should follow the system wide setting instead of being red for one.

We can take a look at this, can you open a separate issue to track the background color? It'll help us fix them one by one.

> And the icons are also hard to see when selected over an object, but otherwise seems to be working as expected

Can you open a separate issue for this as well? We want to make sure each accessibility issue is being tracked and given the importance it deserves.

> Another issue of note is that there doesn't appear to be a differentiator between the currently selected element and one that is being hovered over.

I'm going to modify this issue to track this specific problem.

**Comment by yaira2** [comment]
@nathanielcwm these issues have been resolved in our dev branch and will be included in the next release.
