### ISSUE TITLE
Bug: Error when opening pinned exe from start menu

### ISSUE THREAD

**Issue by cleuton4k** [files-community/Files#9740]
### Description

When pinning a .exe to start menu, it shows as a folder, and I get "drive disconnected" error when clicking it in the start menu.

### Steps To Reproduce
1. Pin an exe file to the start menu
2. Try opening pinned item from the start menu and see the error

### Expected behavior
- The shortcut should open the exe instead of Files

### Files Version
v2.3.48

### Windows Version
Windows 10 21h1

**Comment by yaichenbaum** [comment]
Can you include steps to reproduce the issue?

**Comment by Josh-65** [comment]
They have done it in video form but put it at the bottom. I've move it to the step to reproduce section

**Comment by cleuton4k** [comment]
I don't understand why it hasn't been fixed yet

**Comment by Josh-65** [comment]
No one has looked at making a fix yet

**Comment by yaira2** [comment]
> I don't understand why it hasn't been fixed yet

We must have missed your offer to work on this, looking forward to your PR.

**Comment by cleuton4k** [comment]
please fix

**Comment by cleuton4k** [comment]
![error (1)](https://user-images.githubusercontent.com/90144967/207180645-a30a671c-290b-4704-8f4f-fdcf81799dcc.png)
![error (2)](https://user-images.githubusercontent.com/90144967/207180659-607fd414-76c0-478f-ba0b-fab1159d8044.png)
![error (3)](https://user-images.githubusercontent.com/90144967/207180674-7c7f73bc-c42d-47a3-960c-0bc3bc92d27f.png)
![error (4)](https://user-images.githubusercontent.com/90144967/207180699-5c8d7e17-e9d8-4f8c-9041-3de1f08fa4bd.png)

**Comment by yaira2** [comment]
@cleuton4k Files is an open-source project built by community members like you. We're not a corporation and we have limited resources. User feedback and bug reports are critical so that we know what needs to be done but community members and contributors aren't paid so please keep that in mind.
If you're interested in sponsoring a contributor to work on this issue, I can see if someone is interested.
