### ISSUE TITLE
App sometimes crashes when closing the properties window

### ISSUE THREAD

**Issue by cleuton4k** [files-community/Files#9741]
### Description

the properties window consumes a lot of pc resources such as ssd and cpu and takes time to respond to click, drag and close commands (sometimes when trying to close properties, the app closes).
please fix it.

### Expected behavior

work

### Files Version

2.3.7

### Windows Version

w10 64 bits 21h1

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9356121/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9356122/debug_fulltrust.log)

https://user-images.githubusercontent.com/90144967/185029784-d246e11a-91fe-46e6-b105-58b304ad9e70.mp4

**Comment by yaichenbaum** [comment]
> the properties window consumes a lot of pc resources such as ssd and cpu

We're working on improving performance, this is a long process and will take time to complete.

> and takes time to respond to click, drag

We're tracking the dragging problem in another issue

> and close commands (sometimes when trying to close properties, the app closes).
please fix it.

We're going to modify this issue to track the crash.

**Comment by yaichenbaum** [comment]
This appears to be resolved in the preview version https:/files.community/download/preview.
