### ISSUE TITLE
video and image open in background

### ISSUE THREAD

**Issue by cleuton4k** [files-community/Files#9742]
### Description

when clicking on video and image files these are opened in the background and this is very annoying.

### Expected behavior

work

### Files Version

2.3.7

### Windows Version

w10 64 bits 21h1

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/9356144/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/9356145/debug.log)

https://user-images.githubusercontent.com/90144967/185031224-28a82a56-71da-4153-b327-10107dee80ba.mp4

**Comment by gave92** [comment]
Merging with #5291
