### ISSUE TITLE
change thumbnail size when dragging files

### ISSUE THREAD

**Issue by cleuton4k** [files-community/Files#9743]
### What's the Problem?

the size of the thumbnails when dragging is the same as in the main window and this makes it difficult to drag and place over the icons on the taskbar.

### Solution/Idea

decrease the size of thumbnails when dragging

### Alternatives

decrease the size of thumbnails when dragging

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.3.7

### Windows Version

w10 64 bits 21h1

### Comments

https://user-images.githubusercontent.com/90144967/185032930-bc53b84e-b0d5-42d7-8d70-cc62580cbfc4.mp4

_No response_

**Comment by yaichenbaum** [comment]
If you move the cursor a little lower, does it work?
