### ISSUE TITLE
Files app crashes after Right-Clicking on ZIP Files

### ISSUE THREAD

**Issue by mhmdabdulkader** [files-community/Files#9746]
### Description

To extract a ZIP File, right-clicking on it shows the options available, and crashes.

No ZIP Extractors installed, just the standard windows zip extractor

https://user-images.githubusercontent.com/111109197/185144665-c47770e9-1805-487e-a58d-5f08e6a92990.mp4

### Expected behavior

Expecting the Files app to extract the ZIP Files rather than crashing.

### Files Version

2.3.6.0 

### Windows Version

10.0.19044.1889

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9360606/debug.log)

**Comment by yaichenbaum** [comment]
This issue should be resolved in v2.3.7
