### ISSUE TITLE
Tabs display incorrectly

### ISSUE THREAD

**Issue by useful-tool-square** [files-community/Files#9747]
### Description

When maximize, tabs don't display higher up to the top like the Edge, remain a short distance. 
![image](https://user-images.githubusercontent.com/98749433/185161258-18f824d5-e5c3-491e-945a-0af7e63d98fe.png) This is Files App
![image](https://user-images.githubusercontent.com/98749433/185161368-066a3676-e008-4e22-9ceb-840ea28918c1.png) This is edge.
![image](https://user-images.githubusercontent.com/98749433/185161650-770d82d2-fd02-4bba-8cd7-1feed51bbd54.png)This is Terminal.

### Steps To Reproduce

1.Maximize.
![image](https://user-images.githubusercontent.com/98749433/185162069-56746b70-6384-4017-be9e-d418fca7d664.png)
2.Remain a short distance from the top.
![image](https://user-images.githubusercontent.com/98749433/185162413-418a48ab-9670-4e4a-a1ca-e59573210e95.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/98749433/185162526-5f9391ee-f61f-4c08-837e-0d9ba7c9c55c.png)

### Files Version

Version: 2.3.7.0 OS Version: 10.0.25179.1000

### Windows Version

Windows 11 23H2 rs_prerelease Build 25719.1000

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9363548/debug.log)

**Comment by MalteTasler** [comment]
See #6937

**Comment by Josh-65** [comment]
Merging with #6397
