### ISSUE TITLE
Unknown error Files

### ISSUE THREAD

**Issue by wilsonchicaiza** [files-community/Files#9750]
### Description

Hi
Once I asked to save a file in Word in a Cloud drive (OneDrive personal), a messagge appeared of an unexpected error.  There is no more description on it.

### Steps To Reproduce

1. Write a document in Word
2. Save in a OneDrive folder
3. The message appears

### Expected behavior

No message error

### Files Version

2.3.6.0

### Windows Version

Windows 11 Home 21h2

### Relevant Assets/Logs

?

**Comment by gave92** [comment]
You will need to upload the logs files directly to github. You can get them in files settings > about > open log folder (the two ".log" files).
