### ISSUE TITLE
Duplicates being generated when moving or copying

### ISSUE THREAD

**Issue by hipur** [files-community/Files#9751]
### Description

Whenever I move/copy any file with the source being opened in Files, duplicates are being generated. This happens if doing operations between two different tabs, two different windows and moving/copying from Explorer into Files.

### Steps To Reproduce

Open any two folders on different tabs or windows on Files.
Move/copy files/folders between them

or

Open any folder on Explorer
Open any folder on Files
Move/copy any file/folders from Explorer to Files.

### Expected behavior

Copy/move files without generating duplicates

### Files Version

2.3.7.0

### Windows Version

Windows 11 Home Version 10.0.22000 Build 22000

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9364799/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9364800/debug_fulltrust.log)

**Comment by gave92** [comment]
Thanks for the report. Would you be able to post a screen recording of this?
