### ISSUE TITLE
Bug: Sidebar tags section shows "move" options

### ISSUE THREAD

**Issue by ferrariofilippo** [files-community/Files#9753]
### Description

When you enable the "File Tags" feature, a section is added to your Sidebar. 
This contains the available tags.
Right-clicking on one of them gives you a flyout-menu with many actions. None of them work.
"Move One Down" and "Move to Bottom" do nothing.

### Steps To Reproduce

1. Enable Tags
2. Right click on any Tag under the "File Tag" Section in the SideBar
3. See the "move" options

### Expected behavior
- The move options should be hidden when right clicking the tags section

**Comment by ferrariofilippo** [comment]
Reading the code I noted that Move Up/Down and Bottom/Top features are enabled just for the favorite section, but they are shown in all sections' items.
Should I enable these feature for other sections or should I prevent them from being displayed?

**Comment by yaichenbaum** [comment]
> "Move ..." actions should actually change the order of Tags
The move options aren't supposed to be displayed for tags

> "Open in a new ..." actions should open a new tab/window with all files tagged with that tag, instead of generating an error
Can you open a separate issue to track this?

**Comment by ferrariofilippo** [comment]
> The move options aren't supposed to be displayed for tags

I'll remove them

> Can you open a separate issue to track this?

No problem
