### ISSUE TITLE
Bug: Copying an existing directory creates a new directory with a negative 'Date Created' time

### ISSUE THREAD

**Issue by tquin** [files-community/Files#9755]
### Description

Extremely rapid copy+paste of an existing directory can result in a negative value displaying in the Date Created field. I haven't been able to replicate this with files (as opposed to folders), as they seem to keep the Date Created of the original file.

This is just a visual bug; it has no impact on the data. Refreshing the page would resolve the issue by showing an older time.

https://i.imgur.com/VBoYQ1F.png

### Steps To Reproduce

1. Select an existing directory
2. Rapidly press CTRL+C and CTRL+V (you may need to 'roll over' your finger to activate it quick enough)
3. The newly created folder displays as having '-1 seconds ago' as the Date Created

### Expected behavior

The 'date created' field should never show a negative (future) value - it should either show '0 seconds ago' or 'now' instead.

### Files Version

Version: 2.3.7.0 OS Version: 10.0.19043.1826

### Windows Version

Windows 10 Version 21H1 (OS Build 19043.1826)

### Relevant Assets/Logs

Screenshot: https://i.imgur.com/VBoYQ1F.png

The debug_fulltrust log seems mostly unhelpful:
```
2022-08-18 19:16:03.1002|INFO|OnConnectionRequestReceived|Argument: LoadContextMenu
2022-08-18 19:16:10.6496|INFO|OnConnectionRequestReceived|Argument: FileOperation
2022-08-18 19:16:10.9510|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-08-18 19:16:13.3287|INFO|OnConnectionRequestReceived|Argument: FileOperation
2022-08-18 19:16:13.4026|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-08-18 19:16:14.1368|INFO|OnConnectionRequestReceived|Argument: FileOperation
2022-08-18 19:16:14.2055|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
```

**Comment by hishitetsu** [comment]
I had the same problem when I created a folder on a SMB server, probably due to lack of time synchronization.

@yair100 Can you assign this issue to me? I want to fix it.
I think it should show 'Now', if the offset is 0 or negative.

**Comment by yaira2** [comment]
What does File Explorer do?

**Comment by Josh-65** [comment]
Explorer uses the system time and not relative like Files does by default.
![image](https://user-images.githubusercontent.com/26977075/215915807-8f4a6275-7acd-4355-ae9d-47c5e11656b3.png)
