### ISSUE TITLE
Environment variable USERNAME not correctly filled

### ISSUE THREAD

**Issue by JohannesHolzhaeuer** [files-community/Files#9756]
### Description

When I start an executable the environment variable "USERNAME" of that executable shows "SYSTEM" instead of my actual username "z000swdz". This leads to other problems using this variable down the road.

### Steps To Reproduce

Start any executable from within Files

### Expected behavior

USERNAME should have my actual username "z000swdz"

### Files Version

Version: 2.3.7.0 OS Version: 10.0.22000.856

### Windows Version

Edition	Windows 11 Enterprise Version	21H2 Installiert am	‎09.‎08.‎2022 Betriebssystembuild	22000.856 Leistung	Windows Feature Experience Pack 1000.22000.856.0

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/5112473/185363831-217494ef-73ea-4443-bf85-c6bc1fe79d5d.png)

**Comment by yaichenbaum** [comment]
@Josh-65 did you open a similar issue?

**Comment by Josh-65** [comment]
The ones I have are #5648 and #9488. I dont think there the same through.

**Comment by yaichenbaum** [comment]
It's the same as https://github.com/files-community/Files/issues/5648
