### ISSUE TITLE
Crash when dropping files between tabs

### ISSUE THREAD

**Issue by ispeedyg** [files-community/Files#9757]
### Description

I am about to do a reformat. basically took my documents folder and copied the entire thing at once 7 gig. Yes 7. I love files just found it and will be one of the first things i install when I reformat. I used to have a mac  and loved the + at the top so i didn't have to have a lot of different open windows of explorer. That sold me right there. Not sure why it popped up with an error click here to report it. Not sure if it brought along a tell you log. wouldn't know where to find one. But i check a few folders at the copy spot and they seemed to be just fine.  

### Steps To Reproduce

1 documents folder
2 click + at the top
3 navigate to the destination on a separate drive
4 click to the other tab
5 select all
6 clcik and drag all items (which i am used to seeing them pull with me) they didn't
7 drop on the other tab
here is where i was a bit confused at first till i found your progress area since i had been used to a popup window showing me progress. Because at first i thought i only brought one file out of the bunch but then i heard my fans spin up and started seeing more things popup in the new destination. Took a few minutes and popped up there was an error click here and now i am here  

### Expected behavior

didn't expect anything to happen other then the folders copied to another drive which it looks to me like they did. 

### Files Version

Version: 2.3.7.0 OS Version: 10.0.22000.856  thanks for the quick copy

### Windows Version

Windows 11 Pro , vs 21H2, build 22000.856, Windows Feature Experience Pack 1000.22000.856.0  <--freaking windows don't give a nice copy all

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9373065/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9373067/debug_fulltrust.log)

Guess you had the log coming up. Hope this helps. I will be in format world for a bit. Glad i could help

**Comment by gave92** [comment]
Thanks for the report. Related AppCenter issue: 1785846203u.

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview build? https://files.community/download/preview
