### ISSUE TITLE
Add prompt when extracting password protected archives

### ISSUE THREAD

**Issue by Armitage35** [files-community/Files#9761]
### What's the Problem?

ZIP files with password open but blank.

### Solution/Idea

Popup on crypted zip to enter password

### Alternatives

Win rar or windows file explorer 🤮

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by btomblinson** [comment]
@Armitage35 What software are you using to encrypt the files?

**Comment by btomblinson** [comment]
@Armitage35 Trying to replicate the scenario to investigate and then eventually test, I found I don't see this issue when using 7zip and have had trouble using the Windows 11 built in method. Are you able to provide either a video or step by step to create the encrypted ZIP that is causing this issue?

**Comment by Armitage35** [comment]
Thanks a lot for getting in touch
We used the zip command on mac os :)

**Comment by Josh-65** [comment]
Merging with #9948

**Comment by Armitage35** [comment]
Thanks a lot!
