### ISSUE TITLE
Need (.exe) installation package

### ISSUE THREAD

**Issue by jasonzhou037** [files-community/Files#9765]
### What's the Problem?

Windows 10 EnterpriseThe system I am using does not recognize installation packages in (.msix) format.
Is it possible to provide (.exe) installation package LTSC

### Solution/Idea

Waiting for it to be installed

### Alternatives

Waiting for it to be installed

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by gave92** [comment]
UWP don't do exe. But even on Enterprise you should be able to install the [msix](https://github.com/files-community/Files/releases/download/v2.3.7/Files.Package_2.3.7.0_x64_Sideload.msix) (.msix, not [.appinstaller](https://files.community/download/stable)) using powershell, e.g: `Add-AppxPackage .\Files.Package_2.3.7.0_x64_Sideload.msix`
