### ISSUE TITLE
The file manager is slow

### ISSUE THREAD

**Issue by NixPlayer** [files-community/Files#9767]
### Description

This app i very like it but there is one issue: that is very slow. For opening a folder it requires like 3 seconds to load everything: the icons, the title of the subfolders and other things like that.

### Steps To Reproduce

just open something like the home, the drive, a folder (the home it's the slowest to load)

### Expected behavior

That it's fast like the normal file explorer

### Files Version

Versione 2.3.7.0 OS Version: 10.0.22000.856

### Windows Version

Windows 11 21H2 Version: 10.0.22000.856

### Relevant Assets/Logs

[Files (Preview) 2022-08-19 09-57-13.zip](https://github.com/files-community/Files/files/9380182/Files.Preview.2022-08-19.09-57-13.zip)

**Comment by gave92** [comment]
Merging with #4180

**Comment by yaira2** [comment]
We're excited to share that startup performance will be significantly improved in the upcoming release of version 3. You can download the preview version from our website https://files.community/download.

**Comment by yair100** [comment]
@unFramebuffer we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller

**Comment by theFramebuffer** [comment]
Sorry, this is a 4 year old issue I wrote as a teen, I haven't touched Windows in about 2 years.

**Comment by yair100** [comment]
No worries! We're trying to follow up on old performance reports to inform users about the significant improvements currently being tested.
