### ISSUE TITLE
Transfer files bug

### ISSUE THREAD

**Issue by buuucci** [files-community/Files#9768]
### Description

Hi, have some problems with transfer files infos like percentage.

[](<a href="https://imgbb.com/"><img src="https://i.ibb.co/272mfsM/Captura-de-Tela-82.png" alt="Captura-de-Tela-82" border="0"></a>)

### Expected behavior

the transfer information contains a bug and does not correctly show the process

### Files Version

2.3.7.0

### Windows Version

Windows 11 H1H2

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9380520/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9380521/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview build? https://files.community/download/preview
