### ISSUE TITLE
Paths

### ISSUE THREAD

**Issue by Tyd00c** [files-community/Files#9771]
### What's the Problem?

Hello, it would be welcome to incorporate favorite paths into your application.

### Solution/Idea

Include a menu to add favorite paths.

### Alternatives

Snap window tabs.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Comments

I am not a professional. My text is translated with Google translator.

**Comment by gave92** [comment]
You can right click on a folder -> click "Add to favorites" to add a path to the sidebar.
