### ISSUE TITLE
Very Slow

### ISSUE THREAD

**Issue by Rexmen1** [files-community/Files#9773]
### Description

Have 5800x with 16gb ram still this is like opening a website with slow internet... even website on my pc opens faster than this
https://gyazo.com/bb6c48238de67097584489cd842acc86

Welp gonna uninstall it but tried for first time and liked it very much, but if its this slow its very bad..

### Expected behavior

Expected to not be slow?

### Files Version

Latest to 20/08/2022 downloaded from official site

### Windows Version

Windows 11

### Relevant Assets/Logs

No logs needed and not gonna spend any more time going... Just wanted to report this if not gonna be fix no issues for me... For many this happens and they may not report either...

**Comment by gave92** [comment]
Are tbe ones in the video local or network folders?

**Comment by Rexmen1** [comment]
local on pc in local disk and on desktop opening folder is same speed

**Comment by Rexmen1** [comment]
After restart it did improved but not smooth like on normal explorer.... It feels slow internet file opening in browser

**Comment by Josh-65** [comment]
Merging with #4180. It's being worked on currently.

**Comment by timxx** [comment]
I have the same issue with i9 and 128GB memory, it's very slow compare to the builtin one.
Have to wait a while for opening a local folder

**Comment by Josh-65** [comment]
Speed improvements are always being made. You can try the preview builds https://files.community/download/preview as it's faster but more unstable.

**Comment by tomasbrchan** [comment]
I just installed the app and yes, it is very very slow. I can't even use it how slow it is on local drive. :-(

**Comment by Josh65-2201** [comment]
Slow in what way?

**Comment by yaira2** [comment]
We're excited to share that startup performance will be significantly improved in the upcoming release of version 3. You can download the preview version from our website https://files.community/download.

**Comment by itsTyrion** [comment]
![image](https://github.com/files-community/Files/assets/17730120/8ed30f19-289a-4fa5-9d11-e0dca5782c32)
The preview is still version 2.x for me

**Comment by Josh65-2201** [comment]
Version 3 hasn't been released and that's an old file, Download it from https://files.community/download

**Comment by yair100** [comment]
@Rexmen1 we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
