### ISSUE TITLE
Bug: Sub menus in context menu doesn't expand

### ISSUE THREAD

**Issue by verdaderoken** [files-community/Files#9776]
### Description

I tried creating a zip file from a selection which, of course, can be accessed using context menu > some zip software > create zip., and then I found this.

Here's what it looks like:
[screen-capture (20).webm](https://user-images.githubusercontent.com/88200096/185752824-ab758580-37fd-41a1-ade0-c5acd8b3ddd7.webm)

### Expected behavior

The submenus should expand and work properly

### Files Version

2.3.7.0

### Windows Version

10.0.22622.575

### Relevant Assets/Logs

N/A

**Comment by Josh-65** [comment]
This is more likely a WinUI bug. Whats your display resolution?

**Comment by verdaderoken** [comment]
> This is more likely a WinUI bug. Whats your display resolution?
I often use 2560x1440 on primary display

**Comment by Josh-65** [comment]
from your video it look very low. Could you try lowering the scaling or expand the window and see if it still doesn't work

**Comment by verdaderoken** [comment]
> from your video it look very low. Could you try lowering the scaling or expand the window and see if it still doesn't work

I'm already using 100% scaling for Windows.
Here's the full 1440p window:

https://user-images.githubusercontent.com/88200096/185936549-0a8df596-3055-4c73-b0a0-9ab794c8ce70.mp4


Apparently, **Edit tags** are also not working (v2.3.9.0)

**Comment by Josh-65** [comment]
This is working for me in 2.3.11.0. Can you try that version.

**Comment by verdaderoken** [comment]
I think the problem also occurs outside the app. I tried the option "Save As" in MS Paint but it doesn't expand. Do you think it has something to do with the UI of Windows?
![image](https://user-images.githubusercontent.com/88200096/194468886-e8a1fcbf-c21d-4285-b679-36a9ca7dfc14.png)

build 22623.730

**Comment by yaichenbaum** [comment]
Most likely, that being said, is this an issue in the preview version of Files?

**Comment by verdaderoken** [comment]
> Most likely, that being said, is this an issue in the preview version of Files?

yes both in stable and preview

**Comment by yaichenbaum** [comment]
Let's treat this as a Windows issue.

**Comment by sthivaios** [comment]
I have just checked this and it works fine, so try restarting your computer, reinstalling Files, or any other common "computer fix". You know what I mean... :)

Conclusion : It is not an issue of "Files".
