### ISSUE TITLE
When opening a large folder, scroll is not at the top

### ISSUE THREAD

**Issue by LapisSea** [files-community/Files#9778]
### Description

When a large folder with many files and many folders (like downloads) is opened, scroll consistently is not at the top. This can be very annoying when files are sorted by date.
Different sorting/grouping configurations seem to create a different offset on open.

### Steps To Reproduce

1. Open a large folder
2. Wait a moment 
3. Observe the list of files not being at the start

### Expected behavior

When a folder is opened the scrollbar should be at the top if it is visible.

### Files Version

Version: 2.3.7.0

### Windows Version

OS Version: 10.0.19043.1889

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9387598/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9387600/debug_fulltrust.log)

**Comment by gave92** [comment]
Merging with #6186 and #5825
