### ISSUE TITLE
Better Performance PLS

### ISSUE THREAD

**Issue by Darkiyus** [files-community/Files#9779]
I think the system is really impressive!
It has great features, is easy to use and has a beautiful design.

The only negative...
The performance is not the best...
It sometimes loads a bit longer and has micro jerks...

My PC:
CPU: AMD Ryzen 9 5950X
GPU: 24GB ASUS ROG Strix 3090 OC
RAM: 64 GB DDR4 3600
Main SSD: Samsung Pro 980 1 TB
Secondary SSD: Samsung QVO 870 4 TB

**Comment by Josh-65** [comment]
Merging with #4180

**Comment by yaira2** [comment]
We're excited to share that startup performance will be significantly improved in the upcoming release of version 3. You can download the preview version from our website https://files.community/download.

**Comment by yair100** [comment]
@Darkiyus we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
