### ISSUE TITLE
WinUI 3 progress

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#9780]
- [ ] #9929
- [ ] #10039
- [ ] #10422

**Comment by verdaderoken** [comment]
- [ ] Title bar bug where another title bar shows above the tabs whenever a folder is opened or a tab is closed
![image](https://user-images.githubusercontent.com/88200096/187096333-60d7073c-6021-4de3-811d-ebf1a046bfdc.png)

https://user-images.githubusercontent.com/88200096/187096389-f0e11472-0c4d-4fff-9c7a-b038d522aee6.mp4

**Comment by BanCrash** [comment]
Screenshot of: Context menu appears partially outside when right clicking an option on sidebar 

![imagen](https://user-images.githubusercontent.com/11770760/187232722-e7f908fa-720e-4d77-96f0-5a8f0c1fa2ee.png)

**Comment by Josh-65** [comment]
> Screenshot of: Context menu appears partially outside when right clicking an option on sidebar
> 
> ![imagen](https://user-images.githubusercontent.com/11770760/187232722-e7f908fa-720e-4d77-96f0-5a8f0c1fa2ee.png)

That has always happend. i think it known on the WinUI github but they havent dont anything for it.

**Comment by yaichenbaum** [comment]
Are you sure? I've only seen this behavior with the wasdk build.

**Comment by Josh-65** [comment]
![image](https://user-images.githubusercontent.com/26977075/187310516-050cab79-bfb9-4c29-ab98-a8fbf39622d0.png)
![image](https://user-images.githubusercontent.com/26977075/187310590-6318f173-58ba-4eeb-bffe-0b0392ca89ce.png)


yep at least for the sidebar and trying it on the right of the screen has it show no were near the cursor

**Comment by MarcAnt01** [comment]
![image](https://user-images.githubusercontent.com/43090263/188173995-7837b46d-7e18-4b0e-9f63-759c4351fd3f.png)
The preview feature seems to be broken

**Comment by yaichenbaum** [comment]
>  Merge failure for shared merged PRI file: error 0x80070490. Fault in my computer?

@gave92 is this still happening?

**Comment by gave92** [comment]
I think it was solved by removing arm build from the package.

**Comment by Josh-65** [comment]
Tooltips like the status center one doesnt go away on its own or with the X button
Settings backdrop doesnt change the title bar
![image](https://user-images.githubusercontent.com/26977075/188321392-67e58f3c-1c91-43ed-ba97-9462434d0587.png)

**Comment by Josh-65** [comment]
Should this be close and use the separated ones or is there a reason for it open.

**Comment by yaichenbaum** [comment]
I'm keeping this open until I finish getting the relevant issues to spec for the `ready for build` column.

**Comment by Fahhd1400** [comment]
> لقد حدث هذا دائما. أعتقد أنه معروف على جيثب WinUI لكنهم لم يفعلوا أي شيء له حتى الآن.

وماهو الحل

**Comment by fahed1998** [comment]
جيد

**Comment by fahed1998** [comment]
جيد

**Comment by raul8505** [comment]
Amigo cuando copio no me llama al copiador que tengo instalado ni al de Windows por defecto

**Comment by MSEDGE-CORE** [comment]
![image](https://user-images.githubusercontent.com/74437699/202839003-94a1d900-cec7-4b5f-bba3-b62d5bb8003b.png)

**Comment by Josh-65** [comment]
Thats fixed in preview builds

**Comment by themerror** [comment]
This is a bug in WinUI 3. In UWP, the MenuFlyout control has its own child window whose class is `Xaml_WindowedPopupClass`. However, in WinUI 3, it is displayed in the program window. So if the program window is too small or the control is displayed near the border, it may be showed partly.

**Comment by Pantyhose-X** [comment]
What happens when you replace the path `\` with the `/` symbol?
C:\Windows
C:/Windows

Most software terminals use `/` and do not use `\`

**Comment by hez2010** [comment]
On Windows \ is the default and standard path delimiter.
