### ISSUE TITLE
Can't drag files over to a DAW

### ISSUE THREAD

**Issue by J-Random** [files-community/Files#9788]
### Description

This is when I drag files like MP3s into FL STUDIO, and this issue only started when I got your app, this may be a bigger issue beyond just DAW's

### Steps To Reproduce

1. Download FL studio (free)
2. Get an audio file supported by FL Studio
2. Drag it from the file app to the midi region
![Screenshot 2022-08-22 004452](https://user-images.githubusercontent.com/111712417/185816010-627b896f-b5fc-4e86-a44b-5345fe6978d5.png)

### Expected behavior

There will be a circle with a line in between or an "Invalid" sign and you will not be able to paste your file there

### Files Version

Version: 2.3.7.0
OS Version: 10.0.22000.856

### Windows Version

Windows 11 21H2

### Relevant Assets/Logs

Irrelevant as replicating the steps can produce the issue at hand

**Comment by yaichenbaum** [comment]
Can you report this issue to FL STUDIO? It might have something to do with their implementation of drop but we can't verify that without access to their code.

**Comment by J-Random** [comment]
> Can you report this issue to FL STUDIO? It might have something to do with their implementation of drop but we can't verify that without access to their code.

Yeah I'll report it over there too in the meantime

**Comment by verdaderoken** [comment]
I have encountered this issue since v2.2.53.0.
![image](https://user-images.githubusercontent.com/88200096/185929835-77d3fe16-75eb-481d-9a76-20e19b3e93f6.png)

**Comment by yaichenbaum** [comment]
This is known and currently intended for applications that use the "Storage" apis. We're actively working on solving this and it'll be fixed in the next major release.

**Comment by koblue** [comment]
FWIW this also happens with Ableton Live
