### ISSUE TITLE
Changing the order of folders in favorites

### ISSUE THREAD

**Issue by tea0112** [files-community/Files#9791]
### What's the Problem?

The Favorite section is all right, but the order of each folder cannot be changed.

### Solution/Idea

Dragging up, dragging down folder in the Favorite section.

### Alternatives

![changing](https://user-images.githubusercontent.com/35191308/185907349-fd609265-1fec-4ead-9a68-7cdadcd08fbb.png)

**Comment by gave92** [comment]
You need to right click on items ->choose "move up", "move down"..
