### ISSUE TITLE
Add option to launch defrag and disk cleanup for a drive

### ISSUE THREAD

**Issue by J-Random** [files-community/Files#9792]
### What's the Problem?

If you try to right-click on your drives to try to defrag or remove files, you only get the option to perform a "disk cleanup" which redirects you to a settings page for storage where you can only remove temporary files and not actually defrag the PC

### Solution/Idea

Add the option to defrag your drives and clean storage directly from the app

### Alternatives

Most people now will disable the checkbox for having this app as your default file explorer because of issues like this, and I say do the same.

### Priorities

Adding the option to defrag and free up drives directly is a major task that the normal explorer already does well, this is a must for an app like This
![Screenshot 2022-08-22 145412](https://user-images.githubusercontent.com/111712417/185938123-fe4b2b1e-dcf0-4265-8ff6-1c72950fec92.png)

### Files Version

Version: 2.3.7.0 OS Version: 10.0.22000.856

### Windows Version

Windows 11 21H2

### Comments

I'd also like to add that in the security section, the permission preferences do not get saved

**Comment by gave92** [comment]
Thanks for opening this feature request. I believe this was refused in the past b/c:
- There's little point in launching a defrag on modern system as either you have SSD or the defrag is run by the system periodically
- The disk cleanup in Settings is able to delete the same stuff that the legacy disk cleanup does (not just temp files, also windows updates, caches..)

Adding @yair100

**Comment by yaichenbaum** [comment]
That's correct, we understand there are still some devices with hard drives especially in enterprise environments but as @gave92 mentioned, it's automatically handled by Windows.

**Comment by J-Random** [comment]
So you guys won't add a basic necessity / major feature cause you rely on someone to have defrag settings activated on windows? ok cool I see what kind of devs you are, good luck with your app I'm changing my review on it and making sure no one downloads it

**Comment by yaichenbaum** [comment]
@J-Random we'd like to remind you of the code of conduct. We kept this issue open so we could have a proper discussion about this request, but it doesn't look like you're interested.
When considering feature requests, we take a careful look at how many others have requested the same feature and how many others would be interested. In this case, the defrag menu can already be brought up from the start menu and while we see how it can be convenient to access when right clicking on drives, the vast majority of our users rely on the automatic option built into Windows. Adding another option that most users won't use makes it harder to find the options they do use.
