### ISSUE TITLE
Don't clear the keywords in search bar after searching

### ISSUE THREAD

**Issue by verdaderoken** [files-community/Files#9793]
### What's the Problem?

In Explorer, when you search for something in the search bar, it would not clear the keywords:
![image](https://user-images.githubusercontent.com/88200096/185940377-07003263-4f11-499c-a1c1-9fb10e1f5a42.png)

However in Files, the keywords are cleared:
![image](https://user-images.githubusercontent.com/88200096/185940103-dae0322d-c758-4eaf-ad7e-eee1841255b9.png)

### Solution/Idea

Don't clear the keywords in the search bar after searching, just like in File Explorer.

This is to make it convenient for the user to not re-type the whole word in case they need to refine, modify or correct some spelling.

If the user is done searching (assumed that the keywords are retained), they can click the "**X**" button (or alternatively, the "Back" button that will act as the close button to escape from "Search" and go back to the normal view
![image](https://user-images.githubusercontent.com/88200096/185941871-c65d2d6a-21a1-4641-88c1-a9d845338adc.png)

### Alternatives

Maybe add recent searches so by clicking the keyword will autofill the search bar.

> from Explorer
![image](https://user-images.githubusercontent.com/88200096/185941346-34de01cb-f51d-4494-a2f4-3a1e5f354295.png)

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Keywords should be retained in the search bar | Must |
| Clicking 'X' button in search bar should exit search mode and go back to normal view | Should |
| Add recent searches so by clicking the keyword will autofill the search bar. | Could |

### Files Version

v2.3.9.0

### Windows Version

10.0.22622.575

### Comments

I've already issued this but I think it's not the way it was fixed in #9311

**Comment by ferrariofilippo** [comment]
I don't think we can add this feature as the search bar is a Windows Control, and it doesn't have any event raised on 'X' click.
I checked even EventArgs passed to OnTextChanged but there is no way to know if that button has been clicked
<html>
<body>


Clicking 'X' button in search bar should exit search mode and go back to normal view | Should
-- | --



</body>
</html>

The only way to add this feature would be to create our own control, but to my mind it's not worthy. Tell me what you think.

Anyway I'll work on the other 2 features

**Comment by verdaderoken** [comment]
Thank you, @ferrariofilippo ! I agree with you on that 2nd feature. Shame that they don't have a click event on that clear button. Many thanks for making the other features implemented. I'll close this issue now :)
