### ISSUE TITLE
Feature: Allow adding files to zip archives by dragging

### ISSUE THREAD

**Issue by verdaderoken** [files-community/Files#9796]
### What's the Problem?

We can't add files to an archive when dragging on top of it
![image](https://user-images.githubusercontent.com/88200096/185946211-c1ab2ad8-2393-4358-8c59-f987a2fa1ec9.png)

### Solution/Idea

Allow adding files to an archive by dragging them without opening the archive. This way is more convenient than opening the zip. (particularly .7z files)
Items are expected to be inside the root directory of the archive.

### Requirements 
- Allow adding files to an archive by dragging

### Files Version

2.3.9.0

**Comment by gave92** [comment]
You can do that if you set Files as default app for that kind of file extension.

**Comment by verdaderoken** [comment]
> You can do that if you set Files as default app for that kind of file extension.

Tried and doesn't work. Looks like an unsupported file.
![image](https://user-images.githubusercontent.com/88200096/185959266-e38eeb17-6770-4ba1-a5fa-1a1ffb207519.png)

In Explorer:
![image](https://user-images.githubusercontent.com/88200096/185959374-42c6e319-3b38-4215-9805-b0a7bc8636ed.png)
![image](https://user-images.githubusercontent.com/88200096/185959423-164f8f1c-73aa-4584-b1e2-874b0db487cd.png)

**Comment by verdaderoken** [comment]
> Could you try what happens if you set windows explorer as default instead? (and restart the Files app)

Opening the archive works but:
(1) the drag thing still doesn't
![image](https://user-images.githubusercontent.com/88200096/185960450-b98cd5c4-52f6-4ff3-9a4b-0cb83e204496.png)

(2) it opens in a new window of File Explorer
![image](https://user-images.githubusercontent.com/88200096/185960745-e7087c73-26a7-47d2-8946-20fa1827338a.png)


This should be possible as File Explorer allows the dragging of files into an archive.
![image](https://user-images.githubusercontent.com/88200096/185960926-b9f8ef62-f5c0-4652-a459-bfea39f4e53b.png)

> the image is here inside the archive after being dragged (using File Explorer)
![image](https://user-images.githubusercontent.com/88200096/185960950-a1ec5628-1c7a-4b3d-8895-cc159139b46b.png)

**Comment by verdaderoken** [comment]
> ~Does the archive open in Files or windows explorer?~ In explorer Could you upload the app's debug logs from Files > Settings > Open log location? (There a 2 ".log" files). Thanks!

It worked now. I just re-setted the default to 7zip and back to File Explorer. Thank you!

Last question, is it possible to get it also working for .7z? (Already set to Files (Preview) as default file type))
![image](https://user-images.githubusercontent.com/88200096/185963390-92773cd2-3a53-4ceb-aeaf-889cf5a6bb6a.png)
![image](https://user-images.githubusercontent.com/88200096/185963527-0f2f9930-4a75-4504-8eb3-5b8b93ba8cc6.png)

**Comment by gave92** [comment]
Glad it's working! I'll keep this issue open to track the second bug you noticed.

**Comment by yaichenbaum** [comment]
I have this same issue, 7z works but zip doesn't.

**Comment by yaichenbaum** [comment]
![image](https://user-images.githubusercontent.com/39923744/185968829-b8307d8d-ffa4-4992-9306-9b971c657468.png)

**Comment by br1trs** [comment]
Hi, I started looking into this issue but it is fixed for me if you do what @gave92 suggested at the start. Files App needs to be set as default for Both .7z and .zip extensions. There does seem to be an issue where sometimes the app won't detect that the move file action is required to run, you can see it in the video.



![Image](https://github.com/files-community/Files/assets/88297220/cf93487c-bc8b-4594-b692-0b63dc41c8d7)



https://github.com/files-community/Files/assets/88297220/ee0898a3-8f8e-4db3-866c-c62cdce3f985
