### ISSUE TITLE
Open Folder in Windows Explorer

### ISSUE THREAD

**Issue by DaTigerYT** [files-community/Files#9798]
### What's the Problem?

As amazing as 'Files' is (to me it's just Windows Explorer: but better looking, but I see its additional features), it can't do everything Explorer can... for instance, WinRar - or just extracting multiple zip files at once.

### Solution/Idea

Easily right-click a folder or the current folder (any white space) and just see an "Open in Windows Explorer" option in the context menu. Or, just add another option in the 'More' section (three horiz- dots) in the Top Right corner.

### Alternatives

As of now, I just go to the top right - to the three dots, click on it, head down to 'Open in CMD', and then type "explorer . && exit". I actually have an AutoHotkey script to do this using shortcuts, so I don't actually need the feature but it would be a nice and pretty easy feature to implement.

### Files Version

2.3.7.0

### Windows Version

Windows 10 Pro | 21H2 | 19044.1889

**Comment by gave92** [comment]
Thanks for opening this feedback item. Could you clarify what it is you can't do in Files? WinRar should appear in Files context menu (plus Files is also able to extract Rar archive also without winrar)

**Comment by Josh-65** [comment]
You can type `explorer ` at the start of the path to open it
