### ISSUE TITLE
WebP format thumbnail support

### ISSUE THREAD

**Issue by BaskyCase** [files-community/Files#9800]
### What's the Problem?

![Captura de tela 2022-08-22 153212](https://user-images.githubusercontent.com/85057717/185993969-d78167c9-4561-4176-86d2-831f9f09aabc.jpg)

With the WebP google Codec installed, Windows is fully capable of displaying WebP file extensions in the default file explorer. However, the same cannot be said about Files where it will instead just show an icon of the default app used to open these files (in my case, Microsoft Edge). This happens regardless of which layout is used in Files.

### Solution/Idea

Implement WebP thumbnail support.

### Alternatives

None.

### Priorities

Not added.

### Files Version

2.3.7.0

### Windows Version

Windows 11 Home 21H2 22000.856

**Comment by gave92** [comment]
Merging with #2582
