### ISSUE TITLE
FreeFileSync-like folder merge options.

### ISSUE THREAD

**Issue by DiabeticAnna** [files-community/Files#9801]
Would love to see folder merging options with some sort of preview, similar to FreeFileSync, including:

- Two Way Sync
- Mirror Folder Sync
- Update Folder Sync

This is something Windows is really lame with, would love to see those options one day.

**Comment by yaichenbaum** [comment]
Thank you for your feedback, we'd love to consider this, can you open an issue with the issue template and share some screenshots and examples of what you're looking for?
