### ISSUE TITLE
能否加入进入文件夹自动调整列宽的功能/ Can you add the function of automatically adjusting the column width when entering a folder?

### ISSUE THREAD

**Issue by no240805** [files-community/Files#9804]
### Solution/Idea

如题所言，开启选项后，进入文件夹或预加载时自动调整文件夹各列宽度以显示全文。
as the title says，after the option is turned on, the width of each column of the folder is automatically adjusted to display the full text when entering a folder or preloading.

### Alternatives

没有想法
no idea

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by gave92** [comment]
Merging with #9377
