### ISSUE TITLE
Files opens behind other windows with keyboard shortcut when maximized

### ISSUE THREAD

**Issue by ZaLiTHkA** [files-community/Files#9807]
### Description

please note: I have searched logged issues, but I can only find people complaining that _other_ apps are launching behind Files.. those issues describe different behaviour to what I'm seeing.

I have enabled the option to "Set Files as the default file manager" under the "Experimental" tab in settings.

I do not have any other third-party window management apps installed.

this also does not affect the app when launched from the Start menu or any other file-based shortcut, this only affects the <kbd>Win</kbd>+<kbd>E</kbd> shortcut.

this only affects Files if it was maximized when last open. if the last state was "windowed", then it launches in front of other apps, as expected.

### Steps To Reproduce

1. launch Files and maximize the window
2. make sure "Set Files as the default file manager" is enabled (possibly not related to this bug, but required for the keyboard shortcut to work)
3. close the Files application
4. hit <kbd>Win</kbd>+<kbd>E</kbd>
5. Files launches, the window is not visible, and the taskbar icon sits there flashing...

### Expected behavior

newly launched apps, including Files, should always launch on top of any other currently open applications (unless there are third-party systems with rules that "tweak" this behaviour, of course).

### Files Version

Version: 2.3.7.0 OS Version: 10.0.22000.856

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎2022/‎07/‎04 OS build	22000.856 Experience	Windows Feature Experience Pack 1000.22000.856.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9413241/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9413242/debug_fulltrust.log)

**Comment by ZaLiTHkA** [comment]
just my luck, immediately after logging this, I opened Files with the same keyboard shortcut and... it was in front of my other apps. 🤦🏼 

I'll drop a comment here if I find out anything more..

**Comment by yaichenbaum** [comment]
This seems to be resolved in the latest preview build

**Comment by ZaLiTHkA** [comment]
> This seems to be resolved in the latest preview build

confirmed.. no longer happens for me with `2.3.57.0`. 👍🏼
