### ISSUE TITLE
Bug: Files doesn't fully resolve path containing ".."

### ISSUE THREAD

**Issue by DakshG07** [files-community/Files#9808]
### Description

When opening a path such as `%appdata%\..\LocalLow`, Files doesn't fully resolve the path, instead expanding the `appdata` but keeping a `..\LocalLow` after it.

### Steps To Reproduce

1. Go to the "bar"
2. Type in `%appdata%\..\LocalLow`
3. Files doesn't fully resolve the path

**Requirements**
- Files properly resolves paths such as `AppData\Roaming\..\LocalLow` into `AppData\LocalLow`.

### Files Version

Version 2.3.7.0

### Windows Version

Windows 11 2H22 25182.1000

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/48651837/186456639-25efc772-2600-42e9-b499-dfe311b86a95.png)

**Comment by Josh65-2201** [comment]
This hasn't fixed the original issue for me. 
Typing `%appdata%/../local` will show the below in the path bar but it loads the contents fine.
![image](https://user-images.githubusercontent.com/26977075/226210580-17a9cc46-1100-49bb-8cc2-362470e43ced.png)
Also doesn't load the results preview just saying. No Results
