### ISSUE TITLE
Recycle Bin Icon showing up as normal Folder icon

### ISSUE THREAD

**Issue by pritster5** [files-community/Files#9815]
### Description

In my files app, the recycle bin just looks like a normal folder in the favorites menu and doesn't use it's icon.

### Steps To Reproduce

1. Open the files manager
2.  Look at the recycle bin icon

### Expected behavior

The correct icon should be displayed, not the generic folder icon.

### Files Version

Version: 2.3.11.0 OS Version: 10.0.22000.856

### Windows Version

Windows 11 Home Version 21H2 1000.22000.856.0

### Relevant Assets/Logs

https://user-images.githubusercontent.com/7132319/186780386-6449e277-721d-45ca-bce6-cb45ce9bb75a.png

**Comment by Xch4rt** [comment]
Hello @pritster5, i took a look to this issue, but the same thing doesnt happen to me. I attached a pic of my screen

![imagen](https://user-images.githubusercontent.com/35347784/187011603-3efa767a-8be1-405a-9ada-5457135dec48.png)


I would like to know if it still happens to you ;)

**Comment by pritster5** [comment]
The issue changed for me after restart. It's no longer a folder icon but a blank page icon, as if the correct icon cannot be located.
