### ISSUE TITLE
Feature: User defined sorting of files (arbitrary arrangement)

### ISSUE THREAD

**Issue by Ein-Tim** [files-community/Files#9818]
### What's the Problem?

Windows 11 removed the possibility to sort files manually in all folders but the desktop.

An example:
I have the files:
Image 01.jpg
Image 02.jpg
Image 03.jpg

and want "Image 03" be displayed before "Image 01". With Windows 10 it was possible to deactivate "Auto Arrange" (as explained f.i. in [this](https://www.techsupportall.com/how-to-manually-arrange-files-in-a-folder-on-windows-10-disable-auto-arrange/) guide) and then just drag and drop "Image 03" before "Image 01" and it would stay there, however, this option isn't available anymore with Windows 11 and thus I am limited to the build in sorting functionality of Windows/Files. 

### Solution/Idea

Give the user the possibility to turn "Auto Arrange" off, just like the user could turn it off in Windows 10.

### Alternatives

As I want to be able to sort my pictures without having to rename them every time so that Windows sorts them in the way I want, I don't really see an alternative to this arbitrary arrangement feature.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to arbitrary arrange files | Must |

### Files Version

Version 2.3.7.0

### Windows Version

Windows 11 Version 21H2

**Comment by yaichenbaum** [comment]
I don't think this is a direction (no pun intended) we want to go, however, I'd like to hear more about your use case before deciding. Is there a reason you don't want to use one of the regular sorting options?

**Comment by Ein-Tim** [comment]
@yair100 

> I don't think this is a direction (no pun intended) we want to go

I fully understand that the main aim with Files is to build an easy to use & UX wise beautiful explorer alternative & thus can understand if such *niche* features won't be included!

> Is there a reason you don't want to use one of the regular sorting options?

The problem is that non of the regular sorting options satisfy my needs. I don't want the pictures to be sorted by name, as the files often have names like "IMG_4491" which would be good to sort by, if the oldest picture would have the lowest and the newest picture the highest number but that's not the case.
Sorting only by date is my current workaround, but there are quite many pictures where the creation date is wrong. Just being able to drag and drop them to their right place would be awesome! 

But as said, I understand that Files is in no way meant to be a photo organizing suite (or whatever :D). I also thought in which other cases arbitrary arrangement could be of use, but I couldn't think of any.
Maybe someone else from the community knows another use case for such a feature?

**Comment by yaichenbaum** [comment]
We're planning to allow editing meta data from the details pane, would it help if there was an easy way to change the created date property from the details pane?

**Comment by Ein-Tim** [comment]
@yair100 That would be great, yes! But still, it's more effort to change the created date for each file than just being able to drag and drop.

**Comment by yaichenbaum** [comment]
I hear you, I'm trying to find a balanced solution here without complicating things 😂 
While we can't implement every niche scenario, we'd like to find a solution that at least provides a workaround.

**Comment by Ein-Tim** [comment]
@yair100 

I fully understand your point! 

Would it be OK for you to leave this issue open for a bit to see if someone else from the community has an idea for what else this feature could be used?

**Comment by yaichenbaum** [comment]
Sure thing

**Comment by Ein-Tim** [comment]
Ok, it doesn't seem like anyone else is interested in such a feature, thus closing this issue!
