### ISSUE TITLE
I will new a file and type a filename,but I see a bug

### ISSUE THREAD

**Issue by why37281** [files-community/Files#9820]
### Description

**language:chinese**
使用中文输入法输入文件名后，无法新建文件（夹），按钮是灰色的。
这个现象给我的日常使用带来了**极大的不便**，
所以才有了这篇文档。

### Steps To Reproduce

1.打开Files
2.用Files任意打开一个能新建文件（夹）的位置
3.右键-新建文件（夹）
4.输入文件名时，用中文输入法在输入框内输入任意一串中文字符（不能用英文输入法输入字符，否则错误会消失）

### Expected behavior

虽然输入框中有文字，但“设置名称”按钮依然是灰色的，并且无法点击。

### Files Version

版本: 2.3.11.0 OS Version: 10.0.22000.856

### Windows Version

windows 11 21H2 22000.856 除KB5016691更新未安装外，其他更新都已安装。

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/74863270/186919930-6ff505bd-5e4c-4482-9a0b-07ea56c50169.png)
如图所示

**Comment by gave92** [comment]
Merging with #9563
