### ISSUE TITLE
Feature: Add extract archive button to the toolbar inside when browsing inside archives

### ISSUE THREAD

**Issue by elNino0916** [files-community/Files#9822]
### What's the Problem?

It's not very clear how to extract archives once they're already open

### Requirements 
- Added "Extract archive" button to the toolbar, this should open a modal asking where the user wants to extract the archive.
- Modal should have a message "Where do you want to extract this archive?"
- Modal should have a read only text box that defaults to the parent path + the archive name
- Modal should have a browse button where the user can choose a different location
- Modal should have an extract button
- Modal should have a cancel button

**Comment by gave92** [comment]
You mean on the toolbar?

**Comment by elNino0916** [comment]
yes

**Comment by yaichenbaum** [comment]
This is already supported :thinking:

**Comment by elNino0916** [comment]
Zip and Rar

**Comment by yaichenbaum** [comment]
Rar is not yet supported, can you confirm that zip files display the extract option?

**Comment by elNino0916** [comment]
Nope I don't see it

**Comment by yaichenbaum** [comment]
Can you upload a screenshot of what the app when the zip file is selected?

**Comment by elNino0916** [comment]
![image](https://user-images.githubusercontent.com/84574414/187083425-4b007d06-ac8d-45f6-ba53-72bc9f76b29d.png)

**Comment by gave92** [comment]
It only shows if you go to the parent folder and select the zip file itself I think.

**Comment by yaichenbaum** [comment]
We don't show the extract option in the archive yet, what happens if you simply select the archive?

**Comment by elNino0916** [comment]
I found it

**Comment by elNino0916** [comment]
then I see it

**Comment by yaichenbaum** [comment]
Should this option display a prompt asking where to extract the items?

**Comment by elNino0916** [comment]
I would say yes
