### ISSUE TITLE
Add support for adding and removing file compression and encryption

### ISSUE THREAD

**Issue by Soniczac7** [files-community/Files#9823]
### What's the Problem?

I have my downloads folder set up so it automatically encrypts the contents of the folder whenever a non-encrypted file gets placed there so I have to go to file explorer and decrypt the file from there.
Not the most problematic thing in the world but would be nice to have.

### Solution/Idea

Add file compression/encryption into the file properties maybe under general.

### Alternatives

This feature could also be placed in a context menu.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Add encryption/decryption support | Could |
| Add compression/deconpression support | Could |

### Files Version

2.3.11.0

### Windows Version

Windows 11 Pro Insider Preview 25179.1000

### Comments

![image](https://user-images.githubusercontent.com/52353209/187029205-3870454c-20b4-49e5-995e-642e71c56f86.png)

**Comment by Josh-65** [comment]
Merging with #6519
