### ISSUE TITLE
Where is the amd64 build artifact for 2.3.11?

### ISSUE THREAD

**Issue by khuongduybui** [files-community/Files#9825]
### Description

I cannot find the amd64 build artifact for the latest release [v2.3.11](https://github.com/files-community/Files/releases/tag/v2.3.11).

### Steps To Reproduce

1. Go to https://github.com/files-community/Files/releases/tag/v2.3.11
2. Expand the **Assets** section.
3. See only arm64 build artifact.

### Expected behavior

See build artifacts for both amd64 and arm64 CPU architectures.

### Files Version

N/A

### Windows Version

N/A

### Relevant Assets/Logs

N/A

**Comment by gave92** [comment]
The package includes both arm64 _and_ x64 (amd64):
Files.Package_2.3.11.0_*x64*_arm64_Sideload.msixbundle

**Comment by khuongduybui** [comment]
Thank you very much for the explanation. Does it mean that from this release onwards, the bundle will always be a combined one?
