### ISSUE TITLE
Bug: Ctrl + C to copy text from a text file is not working

### ISSUE THREAD

**Issue by MarcAnt01** [files-community/Files#9826]
### Description

With the preview enabled and a text file selected Files shows a preview on the right, if I select some text it's not copied properly, but the file is. Copying via context menu works properly

### Steps To Reproduce

1. Enable the preview layout
2. Click on a text file
3. Select some text
4. Ctrl + C

### Expected behavior

If some text is selected ctrl + C should copy it
Else if no text is selected ctrl + C should copy the file

### Files Version

Version: 2.3.7.0 OS Version: 10.0.22598.200

### Windows Version

Windows 11 Pro 22H2 22598.200

### Relevant Assets/Logs

.

**Comment by Josh-65** [comment]
@MarcAnt01 is this still an issue in 2.3.11.0?

**Comment by MarcAnt01** [comment]
> @MarcAnt01 is this still an issue in 2.3.11.0?

I don't know, I am in the insider version which has broken preview. So cannot test

**Comment by Josh-65** [comment]
You can download the stable build as that what the version is to test it. but for me its working so im going to close this for now.

**Comment by yaichenbaum** [comment]
Let's keep this open, the clipboard apis aren't the most reliable so it's posible to have different results depending on the device.

**Comment by MarcAnt01** [comment]
> You can download the stable build as that what the version is to test it. but for me its working so im going to close this for now.

Well honestly, you can just try to reproduce issues on the given version instead of closing in advance....

**Comment by yaichenbaum** [comment]
It's not specific to any Windows version, it's something that works on some devices some of the time and other times it doesn't. Maybe there is a better API we can use with WinAppSdk.

**Comment by Josh-65** [comment]
> > You can download the stable build as that what the version is to test it. but for me its working so im going to close this for now.
> 
> Well honestly, you can just try to reproduce issues on the given version instead of closing in advance.... As someone who opened several issues I don't appreciate this pressure towards the ticket authors...

I did test it on the version myself but I said that you download and test it as a suggestion as the way I did it may not be the same way you did.

**Comment by MarcAnt01** [comment]
True, I didn't read well the message. But still don't get the point of the pressure. Once the preview gets fixed on the WinUI 3 version, I'll test it

**Comment by yaichenbaum** [comment]
@MarcAnt01 I'm having a hard time reproducing this, do you have another device to test on?

**Comment by MarcAnt01** [comment]
Seems to be fixed in the WASDK version
