### ISSUE TITLE
Local network hard drive

### ISSUE THREAD

**Issue by Tyd00c** [files-community/Files#9827]
### What's the Problem?

Very difficult to reach my local hard drives connected to my Freebox (French box)

### Solution/Idea

solve the problem.

### Alternatives

Alternative (for me): put back, original explorer.exe

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Comments

Available for a screenshot or other information.
* I'm sad to have to uninstall, the ergonomics are really nice. *

**Comment by Josh-65** [comment]
Can you send a link to the hosting/client program.
