### ISSUE TITLE
Right-click-menu

### ISSUE THREAD

**Issue by Vosjedev** [files-community/Files#9828]
### My problem:
When right-clicking, i get a menu that looks like the standard windows 11 right-click menu.
I personaly prefer the windows 10 one, so i did some registry tweaking to get that one back. but, in this app i still get the windows 11 looking menu.

### My solution:
Include an option in settings to choose if you want the windows 11 style menu, or the windows 10 style one (would like that one with the rouded corners, so it fits in with the app. see picture).

![image](https://user-images.githubusercontent.com/100359465/187070063-f0e2e509-fb47-481a-90d6-eb451a984994.png)

### an alternative
is to make the option toggle the system menu instead of the custom menu.

it could also be a dropdown to choose from windows 11 style, windows 10 style, or system menu.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| a toggle to use the windows 10 menu in windows 11 style (like image in My solution) | could |
| a toggle to use the system menu | could/alternative |
| a dropdown to choose between windows 11 style, windows 10 style, and system | could/alternative |

### Files Version

newest

### Windows Version

windows 11 (newest)

**Comment by gave92** [comment]
Could you clarify why you'd want to switch to the win10 context menu style?
- Because you prefer a more compact style for the menu/to see more items at once?
- Because the menu in Files is missing some items wrt to explorer?

**Comment by Vosjedev** [comment]
I dont like that you need to press "more" to see all the options, and the fact i now need to scroll in the menu. i dont think it is made to be inefficient, and i think that it currently is inefficient...

[het lachende vosje - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=1pbgxw)	[1pbgxw]

On August 28, 2022 at 10:59 GMT, Marco Gavelli ***@***.***> wrote:

Could you clarify why you'd want to switch to the win10 context menu style?

- Because you prefer a more compact style for the menu/to see more items at once?
- Because the menu in Files is missing some items wrt to explorer?

**Comment by yaichenbaum** [comment]
You can adjust this behavior from the apps settings.
