### ISSUE TITLE
Add %UserProfile% folder to Files' navigation pane

### ISSUE THREAD

**Issue by richardhttps** [files-community/Files#9829]
### What's the Problem?

Going to the %UserProfile% folder is something I (and many, I believe) do on a regular basis, and it would be very convenient to have this folder present in the navigation pane.

I could easily add the folder to Favorites, but the folder would have a generic folder icon that can't be changed, which is why I made this feature request.

### Solution/Idea

I belive the %UserProfile% should be present in the navigation pane like other default folders, and should have an icon to make it stand out like this:
![CopyQ wSteFI](https://user-images.githubusercontent.com/33163707/187075404-95750752-bc21-499a-acf2-a273b9ec8ed7.png)

### Alternatives

Option to set hotkeys to access desired folders.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
Have you tried pinning the folder to the sidebar?
