### ISSUE TITLE
Feature: Add Nutstore cloud drive support

### ISSUE THREAD

**Issue by sherlocknieh** [files-community/Files#9832]
### What's the Problem?

Nutstore is a Cloud Drives I use very often. I hope Files can Support it. Here is their official site:
https://www.jianguoyun.com/

### Requirements
- Add Nutstore cloud drive support

**Comment by Akshat977** [comment]
Hi @sherlocknieh  ,
This issue seems to be a good initiation of my journey towards contribution to FOSS projects.
Can you please assign this to me?

**Comment by yaichenbaum** [comment]
@Akshat977 👍

**Comment by yaira2** [comment]
@Akshat977 are you still working on this?

**Comment by hecksmosis** [comment]
Can I open a pull request for this? @yair100

**Comment by yaira2** [comment]
Yes
