### ISSUE TITLE
Bug: Right click doesn't always select the file/folder hovered over

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#9834]
### Description

When I right click a file/folder it should select then bring up the menu. It does it very inconsistently right now.

### Steps To Reproduce

1. Right click on different files/folders
2. Observe that the item you right click on doesn't always get selected

### Requirements

- File/folder should always be selected

### Files Version

2.3.11.0

### Windows Version

10.0.19043.1889

### Relevant Assets/Logs

*

**Comment by ZaLiTHkA** [comment]
just a random thought, but perhaps the simplest solution here is to apply a "click" action at the mouse pointer location before triggering the context menu action..?

FWIW: I keep getting caught out by a similar scenario, which this would also fix.. moving files _up_ one level in the directory tree:

* enter `/path/to/folder`
* select `n` files
* right click on selection > cut
* navigate "up"
* right click on background > paste
* ..and the files are still where they started

if the right click action, being on the background of the folder, deselected the folder I jyst navigated _out_ of, then this would result in the files moving to where I expect them to go.

this same change would most likely resolve _this_ issue as well..

**Comment by yaichenbaum** [comment]
@ZaLiTHkA we ended up solving this by applying the event to the ItemContainer. It appears that having the event on the actual item is unreliable due to the extra padding around the item.
