### ISSUE TITLE
Folder icons in tabs are not showing up

### ISSUE THREAD

**Issue by verdaderoken** [files-community/Files#9835]
### Description

The icon of folders in the tab area is not showing up

### Expected behavior

Folder icons should appear

### Files Version

Version: 2.3.12.0

### Windows Version

10.0.22622.586

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/88200096/187094080-3ae096d5-fc30-41c4-8e11-00a32492ad41.png)

**Comment by yaichenbaum** [comment]
Thank you for the bug report, v2.3.12 is not an available release and was removed shortly after being published. We recommend downloading the latest preview build in around 30 minutes that reverts back to the previous version (it'll have a higher version number but it's essentially the same version)
