### ISSUE TITLE
Address bar is not resetting if unfocused from it

### ISSUE THREAD

**Issue by verdaderoken** [files-community/Files#9836]
### Description

The address bar is stuck when you try to input and cancelled the input via 'x' clear button or by simply typing anything and it gets retained

### Steps To Reproduce

> Select an item (any folder or file)
![image](https://user-images.githubusercontent.com/88200096/187094232-77610651-84da-4baa-91e0-628aa0df64d7.png)

> Click on the address bar
![image](https://user-images.githubusercontent.com/88200096/187094277-9ff4f267-466e-457c-8e94-a85e9b57e9d3.png)

> Click the 'x' button to clear the address path
![image](https://user-images.githubusercontent.com/88200096/187094300-b4913cb0-844f-4ade-904e-ca0c6f5917a6.png)

> Unfocus the address bar (by clicking another item or clicking the search bar)

> The address bar is now stuck with 'Enter a path' placeholder
![image](https://user-images.githubusercontent.com/88200096/187094374-ac428f02-10f0-46a7-a9e7-8ba4f4026095.png)

Now repeat the steps again but this time, type any random word instead of clearing the path

> The result will be this, stuck with a random word
![image](https://user-images.githubusercontent.com/88200096/187094585-91cdb892-e388-4a0b-9358-27f44e125212.png)

### Expected behavior

The address bar should reset to its last valid path if the user cancels the input (via 'x' button) or simply focuses away from the address bar.

### Files Version

2.3.12.0

### Windows Version

10.0.22622.586

### Relevant Assets/Logs

N/A

**Comment by yaichenbaum** [comment]
Thank you for the bug report, v2.3.12 is not an available release and was removed shortly after being published. We recommend downloading the latest preview build in around 30 minutes that reverts back to the previous version (it'll have a higher version number but it's essentially the same version)

**Comment by verdaderoken** [comment]
To note, this still occurs in the latest preview build (v2.3.48)

**Comment by sthivaios** [comment]
I can confirm that both of the things specified in this issue, are in fact bugs.


https://user-images.githubusercontent.com/109022579/195635229-df9be3d7-7ea1-4abb-9e3f-6b6a1b9df6bd.mp4


https://user-images.githubusercontent.com/109022579/195635250-70d7e3b4-e35d-47e6-bc28-205e96ab3cf9.mp4
