### ISSUE TITLE
experimental "Default File Explorer" setting causes problems for other user profiles

### ISSUE THREAD

**Issue by ZaLiTHkA** [files-community/Files#9838]
### Description

this comes up as a result of two points:

* "Files" itself installs as a user application, which means it is not accessible to all Windows user profiles
* the "Set as default file explorer" alters a system-wide setting in the Windows Registry, which affects all Windows user profiles

when this setting enabled, other users can't browse any files.. while the default Windows "File Explorer" window does open, trying to open any drives or libraries throws an error about "Files cannot be found", obviously becaise _that user_ doesn't have the Files app installed.

### Steps To Reproduce

1. install Files in "User Profile 1" (with Files installed)
2. enable "Set as default file explorer" setting
3. switch to "User Profile 2" (without Files installed)
4. open Windows "File Explorer" and try navigate to anything..

### Expected behavior

optimally, this "Set as default file explorer" setting should only affect the current user profile.

alternatively, Files should require a "system wide" installation before allowing this setting to be enabled.

### Files Version

Version: 2.3.11.0 OS Version: 10.0.22000.856

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎2022/‎07/‎04 OS build	22000.856 Experience	Windows Feature Experience Pack 1000.22000.856.0

### Relevant Assets/Logs

no logs worth sharing my current work PC. this issue was experienced on my personal PC.

the issue can be reproduced and logs can be arranged, if required.

**Comment by gave92** [comment]
Merging with #9149
