### ISSUE TITLE
Can setting Tags font profile?

### ISSUE THREAD

**Issue by godchadigo** [files-community/Files#9840]
### What's the Problem?

Can setting font size and color for tags?
![image](https://user-images.githubusercontent.com/19208239/187160552-21ece448-c39c-4a07-8dda-c48208cae9ca.png)
![image](https://user-images.githubusercontent.com/19208239/187161988-50724071-9496-4919-be96-a430d024a003.png)

### Solution/Idea

Add Font setting in json file.

### Alternatives

default font type set bold.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
Font and color is hardcoded to make sure it's always readable. We still have some work to do on the color side, but rest assured we're working on this.
