### ISSUE TITLE
Bug: Shell extensions are not loading for zip files

### ISSUE THREAD

**Issue by licdar87** [files-community/Files#9841]
### Description

As the title says, I use a 3rd party app for archives (Bandizip). However, the "more" context submenu to let me access Bandizip functions doesn't show up for any archive file (tried with zip, 7z, rar).

This is what appears in the debug_fulltrust.log whenever I right-click an archive:

> 2022-08-29 10:18:12.2744|INFO|OnConnectionRequestReceived|Argument: LoadContextMenu

This is the only line being printed. The program reported no errors. Debug.log doesn't show any relevant info either.

I already tried to restore the app to factory settings, to no avail.

If I attempt to select multiple files, then right-click, the Bandizip submenu works as normal, so this hints to me there's nothing wrong with the submenu itself.

### Steps To Reproduce

1. Open any folder
2. Create a new archive
3. Right-click over the archive
4. The "more" submenu is missing

### Expected behavior

Submenu "More" appears with all the relevant choices

### Files Version

2.3.11.0

### Windows Version

10.0.19043.1826

### Relevant Assets/Logs

2022-08-29 10:18:12.2744|INFO|OnConnectionRequestReceived|Argument: LoadContextMenu

**Comment by yaichenbaum** [comment]
Are you able to scroll in the context menu?

**Comment by licdar87** [comment]
> Are you able to scroll in the context menu?

Thanks for the reply

I think the context menu is too short for being scrollable. Also, I don't know if this could be of any help, but I have the option to move overflow items into a submenu enabled

![image](https://user-images.githubusercontent.com/28860048/187234391-cd822be6-a9c8-48bf-ab37-5dae82beb5ba.png)
![image](https://user-images.githubusercontent.com/28860048/187234776-697798c1-b665-45dc-8cf4-f7952197e10a.png)

**Comment by hez2010** [comment]
Files need some time to load additional context menus for the first time. Can you try waiting a few secs after opening the context menu?

**Comment by licdar87** [comment]
> Files need some time to load additional context menus for the first time. Can you try waiting for a few secs after opening the context menu?

I've waited for more than 2 minutes (for good measure). Still nothing appeared.
[debug_fulltrust.log](https://github.com/files-community/Files/files/9446359/debug_fulltrust.log)

Also, big info I totally forgot to mention. I have the same exact problem on two different machines (both on win10 64)

**Comment by yaichenbaum** [comment]
@licdar87 can you check if this is an issue in the preview build? https://files.community/download/preview.
*please note that this is not a stable build and it will be a while until it's available for the stable branch*

**Comment by licdar87** [comment]
> @licdar87 can you check if this is an issue in the preview build? https://files.community/download/preview. _please note that this is not a stable build and it will be a while until it's available for the stable branch_

I'm sorry but still no luck. I tried to wait for at least 20 secs but the menu won't appear

**Comment by yaichenbaum** [comment]
Can you confirm the version number of the build installed? It should be Version: 2.3.22.0.

**Comment by licdar87** [comment]
> Can you confirm the version number of the build installed? It should be Version: 2.3.22.0.

Yes, the version is correct (Files preview)

what happens when I right click an archive
![image](https://user-images.githubusercontent.com/28860048/188006152-093181e6-acc9-4db2-ba17-7213f5573fde.png)

what happens when Iright  click a folder or group of files
![image](https://user-images.githubusercontent.com/28860048/188006216-ed8945c5-bc6b-4603-99ad-61ec91b00652.png)

**Comment by licdar87** [comment]
[debug_fulltrust.log](https://github.com/files-community/Files/files/9473162/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
@licdar87 do the menu options display if you create a brand new zip file?

**Comment by licdar87** [comment]
> @licdar87 do the menu options display if you create a brand new zip file?

the testfile.zip you see on the screens is indeed a brand new file I created to showcase the problem. It doesn't matter if it's a new file or an already existing one, the menu won't show for either.

![image](https://user-images.githubusercontent.com/28860048/188810796-33a259c6-c1fa-4dae-927b-348aecf9db95.png)

**Comment by yaichenbaum** [comment]
1. Can you share the zip file you're testing with?
2. What's the name of the parent directory?

**Comment by licdar87** [comment]
> 1. Can you share the zip file you're testing with?
> 2. What's the name of the parent directory?

This problem is present for any archive file, in any directory (even C:\).

On a semi-related note, I recently upgraded one of my pcs to Win11 (NO clean install). I noticed I had a similar problem with the regular Win11 context menu (I had the Bandizip voices under the Other submenu instead of the main right-click menu). However, I managed to fix that with the help of a side script present inside the Bandizip installation folder. 
(link to the guide: [https://www.bandisoft.com/bandizip/howto/remove-win11-context-menu/](url).

Unfortunately, this didn't fix the problem on Files as well (both beta and standard versions)

**Comment by yaichenbaum** [comment]
If you install 7zip and right click on the archive, does it display?

**Comment by licdar87** [comment]
> If you install 7zip and right click on the archive in Files, is 7zip displayed?

No, it doesn't. Tried with both standard and preview version

**Comment by yaichenbaum** [comment]
Can you upload the log files from the preview version?

**Comment by licdar87** [comment]
[debug.log](https://github.com/files-community/Files/files/9789167/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9789169/debug_fulltrust.log)


> Can you upload the log files from the preview version?

**Comment by sthivaios** [comment]
I haven't read all the comments, but, I just wanted to say that on version 2.3.48.0 this is not an issue.

**Comment by yaichenbaum** [comment]
@sthivaios it's important to note that not every device or installation will be able to reproduce the issue so we always like to hear from the original poster before marking something as resolved.

**Comment by sthivaios** [comment]
> @sthivaios it's important to note that not every device or installation will be able to reproduce the issue so we always like to hear from the original poster before marking something as resolved.

I mean, sure. I didn't expect it to be closed.

**Comment by licdar87** [comment]
If possible, I'd be happy to try the 2.3.48.0 release and check if this problem is actually solved on my system.

**Comment by Josh-65** [comment]
Can you see if this is an issue in the preview version? https://files.community/download/preview

**Comment by licdar87** [comment]
> Can you see if this is an issue in the preview version? https://files.community/download/preview

Still nothing. I've noticed though that there's a new "Archive" submenu when I open the context menu on a compressed file, which shows the standard default functions (i.e. send to a compressed folder, extract, etc.)

I've updated my system to Windows 11

**Comment by yaira2** [comment]
This should be resolved in the next release
