### ISSUE TITLE
name tags

### ISSUE THREAD

**Issue by laramjo** [files-community/Files#9844]
### What's the Problem?

be able to change label names

### Solution/Idea

be able to change label names

### Alternatives

be able to change label names

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by gave92** [comment]
You can edit tags labels and colors from Settings > Experimental > Edit tags. Merging with #9588.
