### ISSUE TITLE
Adding File Preview for more filetypes

### ISSUE THREAD

**Issue by marcus-universe** [files-community/Files#9845]
### What's the Problem?

On the Side File Preview, there are many more file types than average like raw format supported but some important file types are still missing for better workflow in the design field. 

Missing Filetypes are for example:
EXR, EPS, PSD, AI, INDD, FBX, OBJ, USD, BLEND, IES and MTL

![image](https://user-images.githubusercontent.com/26997041/187200533-2013461d-337b-4b6f-815c-69d26cb44855.png)

### Solution/Idea

Maybe a 3D Viewer or EXR Previewer will be awesome. It will be also fantastic to have previews for these file types in the file list. I mean some raw formats are working in the Preview but not on the Filelist. For software-related formats like PSD can be an optional library download useful, so it will be not a problem with the Open Source License. 

### Alternatives

Adding in the file list the Previews. 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| EXR and EPS Formats | Should |
| 3D Formats like OBJ and FBX and software-related formats | Could |

### Files Version

Version: 2.3.11.0 OS Version: 10.0.19044.1889

### Windows Version

Windows 10 Pro 21H2

**Comment by yaichenbaum** [comment]
Merging with #4041 and #2582. There are a couple other issues as well, so rest assured it's being tracked.
