### ISSUE TITLE
Feature: Double click tab to duplicate the tab

### ISSUE THREAD

**Issue by ijac1** [files-community/Files#9846]
### Solution/Idea

Double click a tab to Duplicate Tab.  This is quicker than Right Click > Duplicate Tab.  I used QTTabBar for years and it has this functionality and I loved it.

This gesture should default to duplicating tabs but an option to customize it should be added as well.

### Requirements 

- Double clicking tabs with mouse, touch or pen should duplicate the tab

**Comment by yaichenbaum** [comment]
We recommend ctrl + shift + k to duplicate tabs but we'll consider this as well.

**Comment by ijac1** [comment]
Thanks for the tip.  I'm an artist who uses a Wacom Cintiq and stylus all
day.  A double click would be more convenient for my case. Thanks for
considering it.

**Comment by yaichenbaum** [comment]
I'm interested in learning more about your use case and when you use the option to duplicate tabs.
