### ISSUE TITLE
Right Click to add to Bundle

### ISSUE THREAD

**Issue by ijac1** [files-community/Files#9847]
### What's the Problem?

I can only add an item to a bundle through the 3 dot menu of the bundle

### Solution/Idea

Right Click a file or folder and have an option to Add to Bundle

### Alternatives

Only alternative is adding an item to a bundle through the bundle's 3 dot menu

**Comment by gave92** [comment]
You can also drag & drop files into bundles. Closing the issue as bundles are gonna be replaced by tags.
