### ISSUE TITLE
Bug: Switching to tab with archive open freezes Files until loaded

### ISSUE THREAD

**Issue by mwisnicki** [files-community/Files#9849]
### Description

Switching to tab with tar file takes a lot of time and UI is completely blocked.
It seems to be even smaller if multiple tar tabs are open.

### Steps To Reproduce

1. Create and open large tar file as per #9848
2. Switch to previous tab showing normal folder - should be instant
3. Switch to tar tab - takes about 3-4 seconds meanwhile whole UI is blocked

### Expected behavior

Tab switching is instantaneous.
Additionally, UI should be non-blocking.

### Files Version

Version: 2.3.11.0 OS Version: 10.0.22000.918

### Windows Version

Windows 11 21H2 22000.918

### Relevant Assets/Logs

#9848

**Comment by yaichenbaum** [comment]
Merging with #9848
