### ISSUE TITLE
Ability to disable Tooltips when hovering over files/UI. 

### ISSUE THREAD

**Issue by welsxn** [files-community/Files#9853]
### What's the Problem?

So the thing is, this file manager shows a dialogue box when hovering over a settings or files showing some details like what's the name of the icon and all that, and its a really good feature, don't get me wrong there but it gets really annoying after a while especially when you have thousands of files and you hover over them looking for a file. And even going through things like UI it shows a dialogue box for what feels like constantly. It really gets annoying overtime.  

### Solution/Idea

The best way to solve this would be adding a option in the settings to turn off the dialogue boxes so the users who wants it can enable and those who don't disable it.

### Alternatives

Another solution would be to add a timeframe after only which the dialogue box appears like 3-4 seconds after your mouse is pointing at that file/option without moving.

### Priorities

This feature should be disabled at default(when installing the app for the first time) for new users so they can get accustomed to the UI and stuff and when they get annoyed like myself, they can go to the settings and enable the feature to hide the dialogue boxes.
This feature will allow the end-users to customize the app to their liking even more.

### Files Version

 version 2.3.11

### Windows Version

Edition	Windows 11 Pro Insider Preview Version	22H2 Installed on	‎8/‎25/‎2022 OS build	25188.1000 Experience	Windows Feature Experience Pack 1000.25188.1000.0

**Comment by yaichenbaum** [comment]
The default tooltip behavior is controlled by WinUi, ideally, they would only show when the user deliberately hovers over an item as opposed to when they're scrolling, and the cursor just happens to end up on top of a UI element.
Can you open a feature request on the WinUI repository on link it here?
