### ISSUE TITLE
Addin Folder to Bundle - App crashes

### ISSUE THREAD

**Issue by tolba59** [files-community/Files#9854]
### Description

Hello 
When I try to add a folder to a bundle on the Home page, the app crashes.
While adding files works.

Thanks for the great app
Best Regards
Eslam

### Steps To Reproduce

- Create new bundle
- Add folder
- choose folder
-

### Expected behavior

Folder to be added in the bundleto

### Files Version

Version: 2.3.11.0 OS Version: 10.0.19044.1889

### Windows Version

OS Name	Microsoft Windows 10 Enterprise  21H2

### Relevant Assets/Logs

- Create new bundle
- Add folder
- choose folder

**Comment by gave92** [comment]
Could you upload the debug logs? You can get them from settings > about > open log location (the two ".log" files).

**Comment by tolba59** [comment]
Hello,
Sure, the 2 .log files are attached.

Thanks
Eslam
[debug_fulltrust.log](https://github.com/files-community/Files/files/9451637/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/9451638/debug.log)

**Comment by Josh-65** [comment]
Have you tried the tags feature that will eventually replace bundels and is proberly be nicer to use.

**Comment by tolba59** [comment]
Hello,
That's actually a pretty cool feature, I tried it now and it's nice.
But I have an issue with Tags now :) after I tag a folder, I can see it under the tag list when I click the tag colour, but after some seconds the tag is removed and it disappears from the tag folder.

And another suggestion, in edit tags submenu, you can only select a tag colour, but you can't remove tag from a tagged folder.

Thanks
Eslam

**Comment by Josh-65** [comment]
You can click it again to remove the tag in the right click menu.

**Comment by Josh-65** [comment]
Im going to close this as bundles is beeing replaced by tags. Please open a new issue for issue you encouter with them.
