### ISSUE TITLE
Feature: Option to hide tags from the context menu

### ISSUE THREAD

**Issue by MarcAnt01** [files-community/Files#9856]
### What's the Problem?

I don't like the idea of tags and I don't need them, hence I'd like to have an option to disable them completely (from the sidebar, context menus etc.)

### Solution/Idea

Add an option in settings

### Alternatives

None

### Files Version

Version: 2.3.11.0 

### Windows Version

OS Version: Windows 11 22H2

**Comment by gave92** [comment]
We've have just removed it. You can get the same result by hiding sidebar section and tags column.

**Comment by ZaLiTHkA** [comment]
I also have absolutely no desire to use "file tags", so if there's any performance benefit to turning it off, having an option to do so would be real nifty. (:
