### ISSUE TITLE
Change explorer.exe (Windows File Explorer) to "Files" when a browser (Chrome, Firefox, Edge) asks for files.

### ISSUE THREAD

**Issue by gabiapk** [files-community/Files#9863]
### What's the Problem?

When a browser makes a call to request one or several files, explorer.exe (Windows File Explorer) opens instead of "Files". Still set as default to "Files" as file manager in windows 10.
![files](https://user-images.githubusercontent.com/16184360/187557876-f5b6eddf-4a4e-4a89-a97d-2f7bd186f972.jpg)
![predeterminado](https://user-images.githubusercontent.com/16184360/187557894-99c32a58-983d-42c5-b2eb-39d9e932022b.jpg)

### Solution/Idea

Could configure "Files" to open instead of explorer.exe when a browser requests a file.

### Alternatives

Set browsers to open "Files" instead of explorer.exe

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Versión: 2.3.11.0 OS Version: 10.0.19044.1889

### Windows Version

Windows 10 Pro Version 21H2

### Comments

This would be of great help to someone who has Amyotrophic Lateral Sclerosis (ALS) (I am currently assisting a patient with an eye reader). Thanks to the feature that "Files" has for multiselection, it would make it much easier for you to work with several files.

**Comment by Josh-65** [comment]
Merging with #6314
