### ISSUE TITLE
Feature: Add menu option to set current directories column sizes as the default

### ISSUE THREAD

**Issue by ManuelPietsch-HPE** [files-community/Files#9867]
### What's the Problem?

Every folder needs to be adjusted regarding the column size and shown columns.
This end up in an non consistent view experience. Every folder needs to be individually set.

**Steps to fix**
- Add a menu option when right clicking the details layout headers "Set column widths as default. This option will set the current column sizes as the default. Users should still be able to override the widths.

**Comment by gave92** [comment]
You can set the same layout for all folders in settings > preferences > force use same layout. You c set the shown columns in details view by right clicking on the columns header and selecting "set as default". Does not work for column sizes atm.

**Comment by ManuelPietsch-HPE** [comment]
> You can set the same layout for all folders in settings > preferences > force use same layout. You can set the shown columns in details view by right clicking on the columns header and selecting "set as default". Does not work for column sizes atm.

Thanks for your reply and adjusting title ;-)
I've seen the layout option, but not the column "set as default"... thanks for the hint.
But as you confirmed, does not work for column size.

**Comment by Josh-65** [comment]
Merging with #9558

**Comment by yaichenbaum** [comment]
Let's merge that one with this as this is written a little clearer.

**Comment by samsong** [comment]
agree this request. using latest version of app it still does not save the column widths for different folders. hope to see it fixed soon & will be nice to have option to add/remove more columns and reposition their locations / order of the columns like in default windows explorer
