### ISSUE TITLE
Bug: Opening properties window crashes app

### ISSUE THREAD

**Issue by ispeedyg** [files-community/Files#9870]
### Description

right clicked and went to the circle with the i in it for info. and it just reset. the folder happens to be about 80 gig large. 

### Steps To Reproduce

1. right click file or folder
2. click on properties option
3. app crashes

**Requirements**
- Fix crash the occurs

### Files Version

2.3.11.0

### Windows Version

win 11 pro

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/9461567/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/9461568/debug.log)

**Comment by gave92** [comment]
> 2022-08-31 05:34:48.8982|ERROR|AppUnhandledException|Unspecified error
Unspecified error
	System.Exception: Unspecified error
Unspecified error

**Comment by yaichenbaum** [comment]
This appears to be resolved in `main`.
