### ISSUE TITLE
Avoid unnecessary async state machine generation

### ISSUE THREAD

**Issue by hez2010** [files-community/Files#9871]
We have plenty of code like below:

```csharp
async IAsyncOperation<T> Foo()
{
    return await AsyncInfo.Run(async () => 
    {
        // no await in the body at all
        return foo;
    });
}
```

which doesn't actually await anything in an async method. Instead, we should rewrite them to

```csharp
IAsyncOperation<T> Foo()
{
    return Task.FromResult(foo).AsAsyncOperation();
}
```

This can avoid unnecessary async state machine be generated to reduce GC pressure.

**Comment by QuaintMako** [comment]
Linking it the performance issues maybe? Anyone taking up that issue may want to dive deeper into optimization.

**Comment by yaichenbaum** [comment]
> Linking it the performance issues maybe? Anyone taking up that issue may want to dive deeper into optimization.

Good idea

**Comment by QuaintMako** [comment]
I believe there is no longer any `return await AsyncInfo.Run` methods inside the codebase.

Does this issue also concerns any `return AsyncInfo.Run` that does not have any `await` in its instructions?

**Comment by itsWindows11** [comment]
There are still stuff which could be changed in the codebase, might need re-opening this issue?

**Comment by hez2010** [comment]
Can I assume this issue has been resolved?

**Comment by itsWindows11** [comment]
It should be fully resolved after merging the PR, no problem.
