### ISSUE TITLE
Preview Pane

### ISSUE THREAD

**Issue by CoderNoel** [files-community/Files#9878]
### What's the Problem?

Doesn't have preview pane like the default file explorer

### Solution/Idea

It would be neat to have a preview feature on the right side panel similar to the default file explorer in windows. 

### Alternatives

Quicklook

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.3.11.0

### Windows Version

Windows 11 21H2 22000.856

**Comment by gave92** [comment]
Files has preview pane, use the button on the toolbar to open it:
![hero-light.png](https://user-images.githubusercontent.com/9673091/188169264-bfb2331b-0e85-46b3-9ef0-c699c6d01e17.png)
