### ISSUE TITLE
No storage display

### ISSUE THREAD

**Issue by Tetroner9** [files-community/Files#9879]
### Description

Sometimes when you open Files the storage isn't shown for the drive.

### Steps To Reproduce

1. Open Files
2. Storage bar is not shown

### Expected behavior

Storage bar should be shown for the drives

### Files Version

Version: 2.3.11.0 OS Version: 10.0.22000.918

### Windows Version

Edition	Windows 11 Home Single Language Version	21H2 Installed on	‎10-‎05-‎2022 OS build	22000.918 Experience	Windows Feature Experience Pack 1000.22000.918.0

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/9478973/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/9478974/debug.log)

**Comment by Josh-65** [comment]
Merging with #9289
