### ISSUE TITLE
Add some features

### ISSUE THREAD

**Issue by taskmanager100** [files-community/Files#9880]
### What's the Problem?

Add a switch to enable/disable tabs on top (full screen)
In Properties: Add button "Show more properties" to open system properties dialog.

### Solution/Idea

Add a button link to the system properties dialog to change more properties.

### Alternatives

Open Explorer > choose an object > properties.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

 2.3.11.0 OS Version: 10.0.25188.1000

### Windows Version

Windows 11 23h2 10.0.25188.1000

**Comment by yaichenbaum** [comment]
Thank you for your feedback, can you share your use case for this "Add a switch to enable/disable tabs on top (full screen)"?

> Add a button link to the system properties dialog to change more properties.

We don't have plans to do this but we'd like to hear more feedback about which properties you're trying to change.
