### ISSUE TITLE
Bug: Doesn't work to drag files or folders to .bat files

### ISSUE THREAD

**Issue by 0w0-Yui** [files-community/Files#9884]
### Description

the .exe shortcut can be drag on, but when I drag on the batch file the app told me the only available function is move.

### Steps To Reproduce
1. 

### Requirements 
- 

### Files Version

Version: 10.0.22000.918

### Windows Version

21H2 22000.918

### Relevant Assets/Logs

no log

**Comment by Josh-65** [comment]
@0w0-Yui  Is this an issue on 2.3.11.0? 
I can do this fine. if it is can you check if File explorer work with the same file your draging and bat

**Comment by 0w0-Yui** [comment]
![Snipaste_2022-09-08_21-11-22](https://user-images.githubusercontent.com/55658921/189130641-a440802c-e1d4-4cab-bd8a-1cba771e314e.png)


> @0w0-Yui Is this an issue on 2.3.11.0? I can do this fine. if it is can you check if File explorer work with the same file your draging and bat

**Comment by Josh-65** [comment]
Folders aren't an excutable and that doesnt work in File explorer either since the CMD carnt do anything with it. Draging .jar, .exe, .MSI and other ones like those should work.

**Comment by 0w0-Yui** [comment]
umm, i tried on the original File explorer, the folder can be drag on batch short cut.

> Folders aren't an excutable and that doesnt work in File explorer either since the CMD carnt do anything with it. Draging .jar, .exe, .MSI and other ones like those should work.

**Comment by Josh-65** [comment]
Ah my bad. it does run it at the drag folders location.

**Comment by yaichenbaum** [comment]
@0w0-Yui can you fill out steps to reproduce this issue and include the log files?

**Comment by 0w0-Yui** [comment]
> 

that's not what I mean, the batch dragging works fine, but the batch's shortcut wont work
