### ISSUE TITLE
Feature: Share recent items list when the home page is open in more than one tab

### ISSUE THREAD

**Issue by whitevegagabriel** [files-community/Files#9888]
### Description

Whenever I open a new tab, after all the Recent Files have loaded, they load and populate again.

### Steps To Reproduce

1. Open Files
2. Observe the Recent Files
3. Open a new tab by clicking on a "+" button on the top bar
4. Observe the Recent Files

### Expected behavior

The Recent Files should only load once both when the app opens and when a new tab is opened.

### Files Version

Version: 2.3.11.0 OS Version: 10.0.22000.856

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎1/‎25/‎2022 OS build	22000.856 Experience	Windows Feature Experience Pack 1000.22000.856.0

### Relevant Assets/Logs

https://user-images.githubusercontent.com/60151680/188284461-b147365e-fae6-4efd-84f8-8ba2fe14c9c7.mp4

**Comment by yaichenbaum** [comment]
This is intentional as there isn't any reason to keep them in memory. We can however look into sharing these items when multiple home pages are open at the same time.

**Comment by whitevegagabriel** [comment]
Thanks for triaging this! I think I probably wrote a poor description.

I meant that after loading all the recent files (0:03), they are seen reloading before a new tab is opened (0:04)

That being said, I was also planning on opening a feature request for what you've described.

Happy to file a separate bug or feature request.

**Comment by yaichenbaum** [comment]
A seperate issue would be appreciated, thanks!
