### ISSUE TITLE
Bug: Recent files widget reloads items a second time

### ISSUE THREAD

**Issue by whitevegagabriel** [files-community/Files#9892]
### Description

As soon as I open a new tab (or window) I can see all the Recent Files load up. That is good. However, after they have finished loading, I can see them all disappear and load again. This is without opening a new window or tab. It looks almost as though someone has hit the "refresh" button on the top left.

### Steps To Reproduce

1. Open a new tab (or window)
2. See the Recent Files load
3. Wait
4. See the Recent Files load again

### Requirements 

- Fix issue where the items reload

### Files Version

Version: 2.3.11.0 OS Version: 10.0.22000.856

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎1/‎25/‎2022 OS build	22000.856 Experience	Windows Feature Experience Pack 1000.22000.856.0

### Relevant Assets/Logs

Note how the files load again at 0:02

https://user-images.githubusercontent.com/60151680/188313979-d3d17bcd-e5b8-48fd-a835-e0492ca1b91b.mp4

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by whitevegagabriel** [comment]
The issue has been fixed in the preview.
