### ISSUE TITLE
ZIP File Malfunction

### ISSUE THREAD

**Issue by i-dont-know-username** [files-community/Files#9893]
### Description

I recently opened a file in my Documents folder (**Files_2.3.6.0.zip**)  and I was asked what app I wanted to open the file with. I chose "Files App" and it mysteriously closed down. 

I'll would attach the ZIP file, but there is no point as it is 0B in size which seems even more odd

### Expected behavior

...
for it not to unexpectedly close down?

### Files Version

2.3.6.0

### Windows Version

Windows 11 Home 21H2 22000.832

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9484760/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9484761/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
Is this an issue in v2.3.11?

**Comment by Josh-65** [comment]
There was an issue on that version were it would make a corrupt file. It has been fixed in 2.3.11. just update and re export the settings.
