### ISSUE TITLE
opening folders is slow an lagging

### ISSUE THREAD

**Issue by lucalewin** [files-community/Files#9894]
### Description

When opening a folder (by double left-clicking it) in Files it looks like it is lagging and it is slower compared to explorer.exe

### Steps To Reproduce

1. Open a drive in Files
2. Double left-click a folder to open it
3. Open the same drive in explorer.exe
4. Double left-click the same folder
5. the difference should be noticable

### Expected behavior

Files should not be lagging and it shouldn't be that slow compared to explorer.exe

### Files Version

Version: 2.3.11.0 OS Version: 10.0.25158.1000

### Windows Version

Version: 2.3.11.0 OS Version: 10.0.25158.1000

### Relevant Assets/Logs

explorer.exe:
![2022-09-04 16-49-25](https://user-images.githubusercontent.com/66569227/188320219-ce6af0ed-cb85-4f51-bfc8-6428402da431.gif)

Files:
![2022-09-04 16-57-03](https://user-images.githubusercontent.com/66569227/188320222-376333e0-c399-4391-a1dc-3c43e9e86ed5.gif)

**Comment by Josh-65** [comment]
Merging with #4180. There are current performace updates beeing made in the preview version https://files.community/download/preview but are not ready for release but you can try it.

**Comment by yair100** [comment]
@lucalewin we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
