### ISSUE TITLE
Feature: Nullable reference types annotations

### ISSUE THREAD

**Issue by hez2010** [files-community/Files#9895]
We are migrating to WASDK and adopt .NET 6, so we get build-in nullable reference types support.

**Requirements**
- We should annotate our code to eliminate thousands of warnings about NRT. 

This is a large one, but we can do it progressively.

**Comment by yaichenbaum** [comment]
Good idea, I believe we can do this one by one (e.g. update things as you notice them).

**Comment by yaira2** [comment]
> We should annotate our code to eliminate thousands of warnings about NRT.

What's the proper way to resolve these warnings? Making properties nullable solves the warnings but doesn't offer any protection.

**Comment by hecksmosis** [comment]
According to stackoverflow and the Microsoft docs, the way to eliminate the warnings with "possible" is to mark the properties as nullable or to check for null values

**Comment by chingucoding** [comment]
My 2 cents: If something can be null, we should make it nullable and add null checks where they are used. If the property can never be null (for reasons that the compiler cannot know about), then disabling the warning for that property with an explanation why is the best way.

**Comment by yaira2** [comment]
I think that's a fair solution. That being said, these warnings should be fixed as needed because otherwise, opening a pull request just to fix the warnings takes away from other review efforts.

**Comment by chingucoding** [comment]
So opening a PR just to fix these warnings is not encouraged?

**Comment by hecksmosis** [comment]
I think not

**Comment by yaira2** [comment]
> So opening a PR just to fix these warnings is not encouraged?

It can also impact stability to make large changes like this without understanding the context.

**Comment by yaira2** [comment]
Just to clarify my previous comments, opening PRs for this that are limited in scope (eg one or two classes) are fine.

**Comment by 0x5bfa** [comment]
Removed null-ref warnings in all Widgets classes in the widget view models introduction PR.

**Comment by 0x5bfa** [comment]
As this might have to be done gradually and not in Separated PRs, can’t we merge this to #4180?
