### ISSUE TITLE
Directory Items Preview Tooltip

### ISSUE THREAD

**Issue by violenceandroid** [files-community/Files#99]
i have to deal with a large number of pictures in many folders.
i hope there is a function can set the first picture of the folder as the folder icon

**Comment by duke7553** [comment]
@violenceandroid I can probably add a Tooltip that displays the first few items in a directory. The folder icon would require a lot more work.

**Comment by yaichenbaum** [comment]
Starting with #4744, Files will use the system thumbnails making this no longer relevent.
