### ISSUE TITLE
In a narrow window the sidebar should be collapsed before shrinking the files view

### ISSUE THREAD

**Issue by MarcAnt01** [files-community/Files#9901]
### What's the Problem?

If I reduce the width of a window the first thing that Files does is to "cut" the files view and move it to a scrollviewer. I don't think this is a good behavior because it looks bad and forces the user to scroll.
![image](https://user-images.githubusercontent.com/43090263/188487724-e24330d6-f282-40d8-bf5b-84e5300fcd10.png)

### Solution/Idea

Collapse the sidebar to gain more space for the files view. At a certain point start to shrink also the files view, but as last option.

### Alternatives

None

### Priorities

| This proposal will allow end users to accomplish X | Should |

### Files Version

Version: 2.3.24.0 

### Windows Version

Windows 22 H2 22622.590

**Comment by yaichenbaum** [comment]
If you make the window a little smaller the sidebar should collapse.

**Comment by MarcAnt01** [comment]
> If you make the window a little smaller the sidebar should collapse.

Yes, but after shrinking the files view. The feature request is basically about collapsing first and shrinking afterwards.

**Comment by gave92** [comment]
Consider that the point at which the scrollbar appears depends on the width of the columns which can be different in each folder. Collapsing the sidebar using that could end up being somewhat unpredictable (gives that it would vary folder to folder)?

**Comment by MarcAnt01** [comment]
> Consider that the point at which the scrollbar appears depends on the width of the columns which can be different in each folder. Collapsing the sidebar using that could end up being somewhat unpredictable (given that it would vary folder to folder)? Also it would not be coherent with the other view modes I suppose.

This is a concern, but I find the actual UX way more invasive. Using my tablet in vertical and horizontal I need to collapse/uncollapse the sidebar. Whenever I am using it vertically it's annoying because the sidebar covers the main files view (that should be the priority imho), so I end up collapsing the taskbar, but then when I use it horizontally it's collapsed and I need to open it again. This prevents a smooth usage in tablet mode for me. I use some messaging apps and they all have my same behavior (even if the chat view width is fixed).

**Comment by gave92** [comment]
I see, could it be just a matter of better calibrating the width at which it collapses (similar to #9902)?

**Comment by yaichenbaum** [comment]
It really depends on the current directory's columns and column widths. Determining the proper width for this is extremely difficult but after a lot of trial and error, the current value seems to work the best. I'm open to further adjustments here, do you think you can clone the repo and adjust the value to whatever you think is ideal?
