### ISSUE TITLE
Feature: Increase the minimum window height at which the preview gets hidden

### ISSUE THREAD

**Issue by MarcAnt01** [files-community/Files#9902]
### What's the Problem?

Files preview, seems to behave in this way:
- If the window is wide enough the preview is on the right;
- If the window is narrow it's moved to the bottom
- At a certain point the preview gets hidden when the window is both too narrow and short

The issue is that the last conditions is not calibrated very well and even if in some conditions the window height is so small the preview is there resulting in an inconvenient usage of the app and unpleasant design
![image](https://user-images.githubusercontent.com/43090263/188488519-e8d45eb4-3460-41a0-b28a-04b40ea537c4.png)

### Solution/Idea

Calibrate it better, the UX  is good

### Alternatives

None

### Files Version

Version: 2.3.24.0 OS

### Windows Version

11 22H2 22622.590

**Comment by yaichenbaum** [comment]
> The issue is that the last conditions is not calibrated very well and even if in some conditions the window height is so small the preview is there resulting in an inconvenient usage of the app and unpleasant design

We want the user to decide this for themselves, we only hide the pane when it would completely block the file viewer.

**Comment by MarcAnt01** [comment]
> We want the user to decide this for themselves, we only hide the pane when it would completely block the file viewer.

This means forcing the user to disable the preview and enable it afterwards in scenarios like the screenshot where showing it doesn't make sense at all

**Comment by yaichenbaum** [comment]
That's correct, if the user is making the window really small and doesn't want to see the preview pane, they can either adjust the size of the pane or they can hide it.

**Comment by yaira2** [comment]
@MarcAnt01 thank you for your feedback, this issue will be resolved in the upcoming v2.5 release.
