### ISSUE TITLE
Something about installation

### ISSUE THREAD

**Issue by digiw** [files-community/Files#9903]
### What's the Problem?

This is a great app, but for some reasons, my win10 can't install the uwp program, so I can't install it. Can we download the win64 installation package?

### Solution/Idea

I very much hope that the app can provide the independent installation package of win64 version

### Alternatives

I have no idea for the time being

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
Files can be downloaded from multiple sources
Microsoft Store: https://www.microsoft.com/store/apps/9NGHP3DX8HDX
Sideload version: https://files.community/download/stable
Offline installer: https://github.com/files-community/Files/releases

**Comment by digiw** [comment]
> Files can be downloaded from multiple sources Microsoft Store: https://www.microsoft.com/store/apps/9NGHP3DX8HDX Sideload version: https://files.community/download/stable Offline installer: https://github.com/files-community/Files/releases

Thank you for your Lightning reply! Since I could not install through the Microsoft Store, I tried to download the installation package, but the sideload and offline versions prompted me: "remote procedure call failed" during installation.
I wonder if there will be exe or MSI executable packages?
![image](https://user-images.githubusercontent.com/5784996/188549357-f3688d1f-6909-4432-9532-e814c15a3beb.png)

**Comment by yaichenbaum** [comment]
Those are the available options. It's possible you're using too old of a version of Windows and there isn't anything to do other than update Windows.

**Comment by digiw** [comment]
> Those are the available options. It's possible you're using an older version of Windows and there isn't anything to do other than update Windows.

I think I will try again on the new version of windows, thank you : )
