### ISSUE TITLE
Multiple instances of folder at creation 

### ISSUE THREAD

**Issue by michknu** [files-community/Files#9905]
When i create  a new folder on a network drive it will generate 3 folders all copies with numbers appended, and issue an error message
![image](https://user-images.githubusercontent.com/102652336/188600241-70fad8d4-ae57-4c4e-8986-e6162770ce1e.png)

access denied error
![image](https://user-images.githubusercontent.com/102652336/188600402-a487e41f-7616-4077-b424-649c34d2f30e.png)

**Comment by gave92** [comment]
Merging with #9628
