### ISSUE TITLE
Autohide taskbar breaks when files is maximised

### ISSUE THREAD

**Issue by RagingLink** [files-community/Files#9906]
### Description

As seen in the gif below, the taskbar doesn't work when files is maximised 
![91_wZmzAODnhX](https://user-images.githubusercontent.com/15198000/188637386-f54144a2-0624-42d7-ac82-de4c864d6cca.gif)

### Steps To Reproduce

1. Make sure `Automatically hide the taskbar` is enabled in Windows settings.
2. Open Files
3. Maximise Files
4. Try to access the taskbar

### Expected behavior

The taskbar should just show up

### Files Version

Version: 2.3.24.0 OS Version: 10.0.22622.590

### Windows Version

Windows 11 22H2 22622.590

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9496941/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9496942/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
We're using the regular app window and don't have control over this behavior. I recommend sharing feedback in Feedback Hub under taskbar.
