### ISSUE TITLE
Feature: Add a dimensions sort type

### ISSUE THREAD

**Issue by cpboleto** [files-community/Files#9907]
### Solution/Idea

I Work with images, and the dimensions is super important for my workflow, i think Files can introduce this feature like default, i can search ".JPG" and right click > short by > dimension, and windows shows me like 2000x2000 images, 1720x500 images separate.
![scr1](https://user-images.githubusercontent.com/54492475/188643425-6e5df446-a3ce-465e-932f-86430d4ee468.png)
![scr2](https://user-images.githubusercontent.com/54492475/188643434-20e37c5b-d0e3-4b6f-a365-ad65c4945c54.png)

### Alternatives

Implement all windows custom shorts for searching
![image](https://user-images.githubusercontent.com/54492475/188643976-696c4901-8cad-4247-b006-04524a2c070c.png)

### Files Version

2.3.11.0

### Windows Version

10.0.19044.1889

**Comment by yaira2** [comment]
Thank you for your feedback, this is on our todo list and is being tracked in #8366. Feel free to subscribe or comment on #8366 to be notified of further updates.
