### ISSUE TITLE
Bug: Shell extensions are missing from right click context menu on downloaded items

### ISSUE THREAD

**Issue by cekkr** [files-community/Files#9908]
### What's the Problem?

When I click with the right button on a particular files is not possible to show the personalized context menu containing installed application operation.

<img width="481" alt="files" src="https://user-images.githubusercontent.com/16149805/188644475-a6bda746-e1a5-4257-894a-5a8a1eec0fb3.png">

<img width="679" alt="explorer" src="https://user-images.githubusercontent.com/16149805/188644451-4a42aa5a-fa15-416a-80b7-a94b78f89482.png">

### Solution/Idea

Make, like in Windows 11 explorer, a "Show more" section where to see these options. But, at difference than Win 11 explorer, you don't have to click on it for showing the old style menu, but should be a "Files" implementation of the way that application registers their context menu on Windows. 

### Alternatives

Showing the classic Windows 10  context menu, if possible 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.3.11.0

### Windows Version

Windows 11 22621.457

### Comments

I don't know how handle "Priorities" section. I'm not (still) expert about proposals. Thank you!

**Comment by yaichenbaum** [comment]
@cekkr this seems like a bug, can you upload the log files?

**Comment by cekkr** [comment]
[LocalState.zip](https://github.com/files-community/Files/files/9498967/LocalState.zip)
The bug persists in the last build Version: 2.3.11.0 OS Version: 10.0.22621.457

At the same time, I had no problem to compress the log folder using Files.
And the problem doesn't appear for the file LocalState.zip itself. It's maybe a problem with the hard disk (a NTFS SSD) where this bug happens. But at the same time, sometimes happens in the Download folder of the main SSD. 

Uhm... maybe it's a problem with the flags of downloaded files? Maybe by Windows, maybe my antivirus (ESET Internet Security).

<p style="color: silver; font-size:8px">In any case, Files it's a beautiful project. You have to teach the how-to to Microsoft ;)</p>

**Comment by yaichenbaum** [comment]
I think this is the same as #9841, can you confirm?

**Comment by cekkr** [comment]
Similar one, but evidently with just file downloaded from internet. Always correlated but different, when is not a zip downloaded from internet and I use "Files zip extractor" the created folder is empty.

**Comment by Josh-65** [comment]
Merging with #9841

**Comment by azra1l** [comment]
i have a similiar issue and i think i found out what's wrong for me:

the files app appears to only grab shell extensions for folders applied to 
HKEY_CLASSES_ROOT\Directory\Background (-> right click on white space in a folder in windows explorer)

and not those applied to 
HKEY_CLASSES_ROOT\Directory (-> right click on actual folder item in windows explorer)

at least that's what the behaviour on my pc suggests.

hope this helps

**Comment by yaichenbaum** [comment]
What's the name of the parent directory?

**Comment by azra1l** [comment]
I tested multiple different directories, appears to happen in any directory. Desktop, C:\temp, C:\users\whoami

**Comment by Josh-65** [comment]
Is this an issue in the preview version? https://files.community/download/preview

**Comment by yaichenbaum** [comment]
> Is this an issue in the preview version? https://files.community/download/preview

Yes

**Comment by yaichenbaum** [comment]
Merging with https://github.com/files-community/Files/issues/9841
