### ISSUE TITLE
Preview pane not working in Files (Preview)

### ISSUE THREAD

**Issue by aleskl** [files-community/Files#9909]
### Description

Preview pane doesn't show the file preview, just the rotating loading circle. Tried with jpg, pdf, txt.

### Expected behavior

Preview pane should show the file contents.

### Files Version

Version: 2.3.24.0 OS Version: 10.0.22000.856

### Windows Version

Windows 11 Pro Version	21H2 OS build	22000.856 Windows Feature Experience Pack 1000.22000.856.0

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9497322/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9497324/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
Merging with #9780
