### ISSUE TITLE
custom tags, bug? and a few suggestions

### ISSUE THREAD

**Issue by audi4444player** [files-community/Files#9910]
### What's the Problem?

Hello, firstly, I'm not a programmer so looking through these issues is a bit tricky and I appologise if I'm duplicating anything. I just updated to w11 and was doing some searching to fix up those little things that are annoying and I stumbled upon your program, I'm really glad someone has finally made something that competes with explorer in functionality and doesn't look like it's from the 90s, I am especially excited where you're going with the tag system, I have always wanted tags and every system I've tried from tabbles to tag libraries are too separated from the file explorer to be actively useable, but you're implementation seems really promising. but I can see that it's unfinished, I just don't know whether things are a bug or just not done.

tag related
-The button for "edit file tags" in experimental does nothing, it seems like it's supposed to?
-I can see that multiple tags work but aren't shown but it looks like that has yet to be implemented? 
-There is a screenshot showing what I'm guessing is a mock-up? of a way to edit the nav pane tag list, I'd like to see that implementation but would also like to suggest a nestable tree for grouping tags that go together eg I'm working in one project and can have all the related tags open and my personal ones minimised etc
-where are the tags stored? as the documentation isn't done yet it's not clear where they are going and if they'll work across pc's etc,
- I would like to see a text field (like a fancy invisible one) next to the properties icon in the "ribbon" thing so you can add tags to the selected file/folder/s with a dropdown as you type thing to select your tags
- as someone else suggested tagging isn't for everyone so a master switch to turn it all off and save performance would be great

Other stuff
-properties while beautiful, doesn't remember its resizing and is annoyingly always too small for all the stuff and it's missing a bunch of stuff, also the file/folder icon is showing a background rather than transparent
- would like to see a new folder button in the ribbon thing and when black right clicking so that you don't need to click twice
- I'd like an option for default new folder names & names for new folder from selection (thank you for adding that, I'm used to teracopy and use that feature a lot) 
- speaking of teracopy, it seems you're using your own service, are you able to allow other software for this, in the settings teracopy has some code for other file managers
- right click dragging would be good too
- ability to completely customise the context menu? sorry for suggesting that one if that's way too much, idk how hard it is but everything I've ever tried had a complete fail of an interface, so maybe it's too difficult. I just want to select a "click type" and see a list of everything that shows in the order that it is in and be able to move/remove/add/change things as I want

sorry for the long "report" but I wanted to get it out, if you'd like my help I'm happy to provide help with logical problem solving and ui design, just not actual programming haha, alternatively if I'm just being annoying and you'd like me to go away let me know.

### Solution/Idea

as above

### Alternatives

as above

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must | 
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.3.11

### Windows Version

Edition	Windows 11 Pro for Workstations Version	21H2 Installed on	‎6/‎09/‎2022 OS build	22000.856 Experience	Windows Feature Experience Pack 1000.22000.856.0

**Comment by Josh-65** [comment]
Thanks for the feedback. Please open separate issues for different feedback so it easier to track.

There is a new option on the tool bar with a folder option.
The edit tag button should open a default text editor. Windows uses notepad. Adding a Ui is tracked in #9588 
File oprations (copy and paste, move) use windows default one. using diffrent ones are tracked in #7518
Right click opration (what i presume you are talking about) are tracked in #1396
Content menu customisng is been tracked in #3966

**Comment by audi4444player** [comment]
thank you for the clear links, and sorry about putting it all in one, I only intended to write about the potential bug but got carried away haha, I will make separate issues in future but yes thanks to your info I've realised that the reason it didn't open is because there was no program set to open json files and there was no "open with" popup when clicking the in app link, also there is no such folder "Files_wvne1zexy08sa" for me it's "49306atecsolution.FilesUWP_et10x9a9vyk8t"

and I meant only one tag is displayed in the tags column but I can see here it's not done https://github.com/files-community/Files/issues/9584, is there another place that has the list other than the add dropdown? 

also with the "new folder" I meant like a one click button rather than the link (like windows 10 had the little icon at the top), but it's fine, it just makes making folders quicker along with default names

**Comment by Josh-65** [comment]
The sidebar has the tags listed but you have to click on them to show the content. I dont believe theres any other view option right now.
