### ISSUE TITLE
App crashes when pressing cancel in the properties window

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#9920]

**Comment by ferrariofilippo** [comment]
I'm not getting this problem
- Files updated to commit: a2ead12392399deed6cbbc1e8d89215197f33285
- OS: Windows 11 Home 21H2  22000.856

https://user-images.githubusercontent.com/102259289/189217823-5fed3c96-c56e-4bcb-9d91-43bbd297ac37.mp4

**Comment by yaichenbaum** [comment]
Looks like it's fixed
