### ISSUE TITLE
Bug: Navigation is randomly hitting fatal COM error (0x8000FFFF)

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#9921]
We don't have proper steps to reproduce and this might be a WinUI issue but we're tracking on GitHub as it's a blocking issue in Files.

**Comment by hez2010** [comment]
Note that this issue only happens while using DetailedLayout.
The crashing is happened at `BaseLayout.NotifyPropertyChanged` for `ColumnsViewModel`:

![image](https://user-images.githubusercontent.com/14960345/188842728-fc119b7d-3b88-46c1-9456-f848da7fdb34.png)

Not sure whether it's a WinUI bug or not.

**Comment by hez2010** [comment]
https://github.com/microsoft/microsoft-ui-xaml/issues/7695

**Comment by QuaintMako** [comment]
An answer has been provided by the [microsoft-ui-xaml](https://github.com/microsoft/microsoft-ui-xaml/issues/7695 ) about this issue with a possible solution :

> Agree it looks like a bug in WinUI3. Thanks for providing the debug info. In response to the property change notification, it's trying to reach back and get the new value, and it looks like the pointer it has to the internal ICustomProperty reflection object is bad.
> 
> In the interest of getting unblocked, maybe you could switch this binding to an {x:Bind}, or otherwise add some code to replace it. If it's happening for all of the bindings on this object, then that would be interesting to know too.

Should we go down this path ?

**Comment by hez2010** [comment]
I don't think the solution works. We are using TemplatedBindings, not Bindings, and they cannot just be replaced with x:Bind.

**Comment by hez2010** [comment]
I have an idea about working around this issue (but don't have time to implement and verify). 
How about removing the xaml code that binds ListView columns to the ViewModel, instead, manipulate the columns in the code behind manually?
