### ISSUE TITLE
Bug: App has wrong icon when hovering over taskbar icon

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#9925]
### Requirements
- use appWindow.SetIcon(path_to_ico)

**Comment by blouflashdb** [comment]
I would like to work on this.

**Comment by blouflashdb** [comment]
It seems like SetIcon only works for .ico Files and with absolute File URI on the Disk itself. I can't find a .ico for that in the project. 

See: 
https://github.com/microsoft/WindowsAppSDK/issues/1914
https://github.com/MicrosoftDocs/windows-dev-docs/blob/158e801182be596bd775278c5a29095caa3bd845/hub/apps/develop/title-bar.md#icon-and-system-menu

Should I create one? @yair100

**Comment by yaichenbaum** [comment]
We don't want to use an ico file, are there any other methods we can use?

**Comment by blouflashdb** [comment]
> We don't want to use an ico file, are there any other methods we can use?

I guess not.

**Comment by yaichenbaum** [comment]
Let's go with ico for now.
