### ISSUE TITLE
Bug: Properties window opens behind main app window

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#9926]
**Steps to reproduce**
1. Right click file or folder
2. Click on properties
3. Observe that the properties window opens behind the main app window

**Requirements**
- Property window should be opened in the foreground

**Version information**
Version: 2.3.26.0
OS Version: 10.0.25193.1000

**Comment by ferrariofilippo** [comment]
@yair100 may I work on this?

**Comment by yair100** [comment]
> @yair100 may I work on this?

We still have some catching up to do on your other pull requests but by all means, this will be very helpful.

**Comment by hecksmosis** [comment]
Isn't this already fixed with #10897 @yair100

**Comment by yaira2** [comment]
This is still an issue

**Comment by ferrariofilippo** [comment]
It doesn't affect Sidebar, Widgets and keyboard navigation, am I right?

**Comment by yaira2** [comment]
I can't reproduce it, it's possible that it still happens under certain circumstances but we can close this for now.
