### ISSUE TITLE
Bug: Icons are no longer shown on the tab control

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#9929]
**Requirements**
- Display the icon of current directory on the tab control

**Comment by daa729** [comment]
Are you still looking for someone to work on this problem? I'm a student looking to contribute to an open source project and would love to try to figure it out if that's okay?

**Comment by yaichenbaum** [comment]
Yes, still an issue, would you like to work on it?

**Comment by daa729** [comment]
Yes, I would like to. please let me know if there is any additional information for this bug.

**Comment by yaichenbaum** [comment]
This issue was intruduced when we switched to WinAppSdk so it might be worth looking at those pull requests.

**Comment by sthivaios** [comment]
Just sayin' here, it still is an issue.

Just to let you know... :-)

**Comment by yaichenbaum** [comment]
@sthivaios this issue is high on our priority list as it's a regression since porting to WinAppSDK.

For what it's worth, your comments on issues these past few days have been extremely helpful. It's hard for us to check every issue and community participation makes it a lot easier and we really appreciate it.

**Comment by sthivaios** [comment]
> @sthivaios this issue is high on our priority list as it's a regression since porting to WinAppSDK.
> 
> For what it's worth, your comments on issues these past few days have been extremely helpful. It's hard for us to check every issue and community participation makes it a lot easier and we really appreciate it.

Thank you! I just have a lot of free time now, because we don't have a lot of homework at school, so I decided to help in this community.

**Comment by yaichenbaum** [comment]
Interesting, this was working fine for us on Microsoft.UI.Xaml 2.7.1.

**Comment by QuaintMako** [comment]
Offered a suggestion of fix if it's high on our priority list. It's more for a temporary fix, and if accepted, I'll open another issue to track that we need to get back to the previous display.

**Comment by daa729** [comment]
When I looked through it, I attempted switching to an iconbox instead and
it caused the application to crash. I was thinking if we could copy the
formatting used for the sidebar it would work but that wasn't running
properly.

**Comment by QuaintMako** [comment]
> When I looked through it, I attempted switching to an iconbox instead and it caused the application to crash. I was thinking if we could copy the formatting used for the sidebar it would work but that wasn't running properly.

Tried to look into this direction as well, but it seems there is an insolvable issue in this path. `SidebarViewModel `does not have any inheritance whereas `TabItem` needs to answer to the format of `TabViewItem` defined by Microsoft. Hence, we cannot replicate the process with the `BitmapImage`. 

Still trying to find a solution that being said.

**Comment by QuaintMako** [comment]
@yair100 had a look on the Microsoft side for the icon issue, and I don't think it's quite up my alley yet. I'm no C++ coder, and I think it'd take quite a while to find the problem and fix it.

So question is: how important is it for us to have the icons displayed on the tabs? If it's high, I'll persist on the Microsoft side, else I'll go focus on more pressing matters.

**Comment by yaichenbaum** [comment]
It's a pretty high priority in the sense this is a regression since migrating to WinAppSdk but the issue itself isn't that bad. Is there an issue on their repo?

**Comment by QuaintMako** [comment]
> It's a pretty high priority in the sense this is a regression since migrating to WinAppSdk but the issue itself isn't that bad. Is there an issue on their repo?

An issue has been opened, as it was mentionned in the comments above. For me, to _try_ and just _try_ to fix it is gonna have a big entry cost since I don't usually do C++. Not even sure I'll find a solution.

It's mostly to known if I focus on this issue or if I spend sometime first on others pressing issues. (Crashes / perfs etc...)

**Comment by yaichenbaum** [comment]
WinUI 3 is closed source so there isn't anything we can do from our end.

**Comment by QuaintMako** [comment]
... Okay I was about to work on WinUI 2 ! Thanks for pointing it out. Well, in that case I'll go raise an issue to WinUI3. 

I'm still not sure how to make a custom controller for that issue though, so I'll pass the towel to someone more experimented that I. 

Worst case scenario, we still have the possibility to replace the icons by Symbol Icons as was done in #10188 until WinUI 3 fixes it;

**Comment by 0x5bfa** [comment]
@yair100 We have same issue. This issue seems to be an issue MUX-side. TabView control certainly worked properly in WinUI 2.7 and also although I searched mux repo for this issue, there is no such an issue filed. This https://github.com/microsoft/microsoft-ui-xaml/issues/7344, which is @QuaintMako mentioned, issue is PathIcon problem so nothing to do with this.

**Comment by yaichenbaum** [comment]
@onein528 have you filed an issue on the WinUI repo?

**Comment by onein528** [comment]
I'll do it.
