### ISSUE TITLE
Add Option to Set the Default Paste Conflict Resolution Behavior

### ISSUE THREAD

**Issue by colejohnson66** [files-community/Files#9934]
### What's the Problem?

When I paste files in Windows Explorer, the default is to overwrite the destination, with the option to change it to skip/rename. With Files, however, the default is to rename, with the option to overwrite/skip.

### Solution/Idea

An option to set the default "paste file" conflict handling. Currently, I'm forced to open the dropdown and change it to "overwrite" every time. Possibly underneath "files & folders" in the preferences.

### Alternatives

Use Windows Explorer (not desired)

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Allow end users to change default paste conflict resolution | Must |

### Files Version

2.3.11.0

### Windows Version

Windows 11 Pro 22H2 22622.575

**Comment by yaichenbaum** [comment]
Thank you for your feedback, merging this with #9058

**Comment by colejohnson66** [comment]
Ah. My bad. I searched first, but didn't see that one.
