### ISSUE TITLE
Having the ability to change the placemeng on a favourited folder (just like regular file explorer)

### ISSUE THREAD

**Issue by iy9k** [files-community/Files#9937]
### Solution/Idea

You should be able to drag the placement of the favourites folder thingy instead of having to "right click to move" your way with them

### Alternatives

Potentially adding it as an option at least to drag the placement instead of being locked to right clicking your favourited folder to be able to move it
Potentially (plan if this doesn't get implemented) have it so that you can move the favourited folder more than just one placement (also can be customizable upon right-clicking the favourited folder)

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Have an option where you could drag the favourited folder (with holding left click) instead of being locked to right-clicking the favourited folder to move it a placement. (just like how it is in regular file explorer) | Must |
| Add an option to drag the favourited folder in settings. (for those who are fine/like/prefer right-clicking method) | Should |
| Add an option to choose how much the favourited folder should move when right-clicking the favourited folder. | Could |
| Do not outright lock us to right-clicking the favourited folder as the only way to move it. | Won't |

### Files Version

Version: 2.3.11.0 OS Version: 10.0.22621.457

### Windows Version

Windows 11 22H2 Build 22621.457 (latest release preview build)

**Comment by yaichenbaum** [comment]
This is already implemented in Files but doesn't work because of this issue #3290
