### ISSUE TITLE
Bug: Couldn't open the recycle bin properties

### ISSUE THREAD

**Issue by rifkyaprasetya** [files-community/Files#9938]
### Description

When select all the recycle bin files, then click properties the app suddenly closed by itself

### Expected behavior

The properties opened

### Files Version

2.3.11.0

### Windows Version

10.0.19044

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9502424/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9502426/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
This is resolved in the preview build https://files.community/download/preview
