### ISSUE TITLE
Opening symlink folders has a delay and weird behaviour

### ISSUE THREAD

**Issue by Nihilopia** [files-community/Files#9940]
### Description

Following scenario on my side:
- 1 SSD (System drive) C:
- 1 HDD (Auxiliary drive) B:
- Downloads folder (`C:\Users\Emmi\Downloads\`) is a symlink to the HDD (`B:\UserData\Downloads\`)

When I try to open the symlink in my home path, Files get stuck for a short while and then proceeds to show the insides of the symlinked folder. However I always have to scroll up a bit to get to the very top of the folder.
These behaviours doesn't occure if I directly navigate to the destination of the symlink (when opening `B:\UserData\Downloads` directly).

### Steps To Reproduce

1. Have symlink on drive-1 showing to a destination on drive-2
    - Possibly needs to have many files
2. Open the symlink on drive-1

### Expected behavior

- No stuttering
- Folder is scrolled to the top upon loading

### Files Version

2.3.11.0

### Windows Version

Windows 10 20H2 19044.1889

### Relevant Assets/Logs

The stutters in the video are real stutters I encountered with Files, while recoding the video. The video recording didn't seem to interfere with the bug's behaviour. Video has no sound - Size 895.25 KiB

https://user-images.githubusercontent.com/28660694/188877142-c65a7aaa-b61e-45b7-87e2-88ca6b20be27.mp4

**Comment by Josh-65** [comment]
Merging with #4180 and #6186. It says for date sorting but is tracking it for all
