### ISSUE TITLE
Feature: Menu option to add selected items to archive

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/Files#9947]
**Requirements**
- Add an option to the right click context menu to add the selected item to an archive
  - The menu option should say "Add to {_FolderName_}.zip"
- When multiple items are selected, there should be a different menu option that says "Add to archive"
  - This action should display a modal where the user can input the archive name. There should also be a cancel button.

**Comment by ferrariofilippo** [comment]
@yair100 may I work on this?

**Comment by yaichenbaum** [comment]
@ferrariofilippo 👍

**Comment by ferrariofilippo** [comment]
I have two questions:
- Should compression-status be shown in the `Ongoing Tasks` section?
- The `Cancel` button (2nd case) is meant to abort the compression before or after it has started?

**Comment by yaichenbaum** [comment]
> Should compression-status be shown in the Ongoing Tasks section?

Yes

> The Cancel button (2nd case) is meant to abort the compression before or after it has started?

Should cancel before it has started
