### ISSUE TITLE
Introduce Humanizer

### ISSUE THREAD

**Issue by onein528** [files-community/Files#9954]
### What feature or improvement do you think would benefit Files?

How about to introducing `Humanizer`? It allows the app to convert byte units to easy-to-understand string.

#### Motivation

https://github.com/Humanizr/Humanizer#bytesize

### Requirements

_None_

### Files Version

Whatever

### Windows Version

Whatever

**Comment by 0x5bfa** [comment]
@yair100 Why did you close?

**Comment by yaichenbaum** [comment]
We close issues that don't have a proper description. The issue template makes it easy to fill out.

**Comment by 0x5bfa** [comment]
I updated. What do you think? @yair100

**Comment by yaichenbaum** [comment]
We're trying to not add any new dependencies to Files right now.

**Comment by onein528** [comment]
Rather than saying to add a new dependency, saying to replace.

**Comment by yaichenbaum** [comment]
We'd like to remove `ByteSizeUnits` as well

**Comment by onein528** [comment]
Then can I fix that?

**Comment by yaichenbaum** [comment]
We'd need to create something equivalent beforehand. Removing extra dependencies should help with security and maintainability.
