### ISSUE TITLE
从地址栏放回闪退

### ISSUE THREAD

**Issue by yunayj** [files-community/Files#9969]
### Description

![image](https://user-images.githubusercontent.com/61784125/189461694-418289ac-80e3-454c-9443-f02e59e8a4c9.png)
从如图地址栏中点击返回上级时会闪退报错，如果一次不会，多试几次就可以了

### Steps To Reproduce

1.随便进入到某地文件夹
2.点击地址栏中该目录的父目录
3.闪退并报错

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

2.3.28.0

### Windows Version

windows 22H2 25197.1000

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9539303/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9539304/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
Tracking in #9780
