### ISSUE TITLE
Every tab should be a different process

### ISSUE THREAD

**Issue by cekkr** [files-community/Files#9970]
### What feature or improvement do you think would benefit Files?

I was working on a bug report (about zip extraction) and during the test for preparing the log the tab froze, and the other tabs become inaccessible. This is not the first time this happens and during a normal session of use. 

Like in web browsers, different processes for every tab could save me from losing total control of my current Files workspace. 

Thank you

### Requirements

- Different process for every Files window (already accomplished)
- Different process for every tab
- Different process (threads?) for included operations like zip extraction (I cannot explain this problem, my original bug was about the fact that if you ask to extract files in a folder with the same zip name it makes an empty folder)

### Files Version

2.3.11.0 

### Windows Version

Windows 11 10.0.22621.457

**Comment by Fahhd1400** [comment]
ماهي المشكله بالضبط هل من شبكه الايداع او خلل فني من طريقه ايداعي

**Comment by cekkr** [comment]
Pardon, but just because I wisely understood the emoji. I'm not giving orders nor know the difficulty of the implementation in the project structure. But it's an evidently necessary request, seeing the quality of this project but also seeing some performance difficulties, maybe dues bugs, but it's a seed for a good optimization.

**Comment by yaichenbaum** [comment]
Thank you for your feedback, we're tracking the issue with archives separately but once it's resolved, there isn't an reason to use a seperate process.

**Comment by cekkr** [comment]
> Thank you for your feedback, we're tracking the issue with archives separately but once it's resolved, there isn't a reason to use a separate process.

Ok, I understand that different processes could justify at the same time a low performance for every process, rather than the complexity of this implementation. But there are a lot of new versions in the repository: if I try to separate the process and for some lucky reason I can do it (well), are there some possibilities to add this feature in a release?

**Comment by yaichenbaum** [comment]
Aside from the issue with extracting items freezing the app, is there any other reason you'd like to see a seperate process for each tab? Seperate processes will lead to worse performance and there are other ways to prevent one tab from freezing other tabs.
