### ISSUE TITLE
Opening downloads folder in quick access doesn't take it to the very top of the list

### ISSUE THREAD

**Issue by ORIOLESFan02** [files-community/Files#9974]
### Description

Unfortunately I am bad at explaining things, but I'll try my best. So, when you click downloads, you assume that it would take you to the very top of the list so you can get the file you just downloaded, well for some reason, it doesn't do that. I hope this makes sense, but I will attempt to provide a video to show you what I mean.

### Steps To Reproduce

Apologies for the bad video quality. OBS wasn't picking up the application in Window Capture, so I had to zoom in after the fact in desktop view. I hope this can still get my point across.

https://user-images.githubusercontent.com/48143202/189501411-2dafa557-3417-4bf4-8ddc-97045c9ec1ba.mp4

### Steps to fix

- Always go to the very top of the list (Vertical)

- After accidentally clicking the today view in video, make sure the horizontal scroll thingy goes to the very far left

### Files Version

Version: 2.3.11.0 OS Version: 10.0.22000.918

### Windows Version

Windows 11 21H2 22000.918

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9541393/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9541394/debug_fulltrust.log)

I would just like to say that I edited `debug_fulltrust.log` just to set my username to `redacted`. That's the only thing I did and I just wanted to tell you.

**Comment by gave92** [comment]
Merging with #6186
