### ISSUE TITLE
Add Format option when right clicking drives on homepage

### ISSUE THREAD

**Issue by colejohnson66** [files-community/Files#9975]
### What feature or improvement do you think would benefit Files?

Windows Explorer allows formatting drives from the "This PC" screen. Files does not.

### Requirements

- This proposal will allow users to format drives without Disk Management

### Files Version

2.3.11.0

### Windows Version

Windows 22H2 22622.590

**Comment by gave92** [comment]
Atm you can right click on the drive on the sidebar to access the format option

**Comment by colejohnson66** [comment]
Here's Files:
![image](https://user-images.githubusercontent.com/11381599/189533154-dbe01a95-3992-45f4-b85c-9b1e5fb46260.png)

Here's Explorer:
![image](https://user-images.githubusercontent.com/11381599/189533192-4b2d9f06-2409-4eb5-b52e-c8c779d695d2.png)

There's no "format" option.

**Comment by colejohnson66** [comment]
It's also not showing the correct drive name. It was formatted as "New Volume", then I formatted it again as "512GB". Files shows the old name even after a refresh. I have to close and reopen it for it to show the correct name.

**Comment by gave92** [comment]
Merging with #5888
