### ISSUE TITLE
Rename a file doesn't refresh the lis

### ISSUE THREAD

**Issue by giovannicandido** [files-community/Files#9979]
### Description

When a file is renamed in a folder inside WSL Distribution, it do not appear in files until you open the folder again, or refresh the list.
Also when we create a new file using the new file option it do not appear right away, maybe related

### Steps To Reproduce

1. Go to any folder inside an WSL2 Distribution
2. Select an file
3. Press F2
4. Enter a new name

The old file name is still in the folder. Trying to open the file open a File Not found Error
After refreshing the folder the new file appears

### Steps to fix

- Refresh the folder state automatically

### Files Version

Version: 2.3.11.0 OS Version: 10.0.22000.918

### Windows Version

Windows 11 21H2

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9549762/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9549763/debug_fulltrust.log)
![2022-09-12_13-00-59](https://user-images.githubusercontent.com/915892/189701541-086fb255-f70b-4efc-9790-9601a5ab27c4.gif)

**Comment by gave92** [comment]
Merging with #9250
