### ISSUE TITLE
Feature: Option to assign an alias name for tabs

### ISSUE THREAD

**Issue by timluther** [files-community/Files#9980]
### What feature or improvement do you think would benefit Files?

I'd like to be able to rename tabs (without renaming the underlying folder).
I often work with sets of tabs in different directories where the subdirectories in question have the same name, so being able to tell which is which at a glance would be very helpful.

### Requirements

Right click on tab to rename (or rather, to apply an alias to) a tab.

### Files Version

2.3.11.0

### Windows Version

Edition	Windows 10 Home Version	21H2 Installed on	‎14/‎05/‎2021 OS build	19044.1889 Experience	Windows Feature Experience Pack 120.2212.4180.0

**Comment by gave92** [comment]
Should the custom tab names be remembered across sessions?

**Comment by timluther** [comment]
@gave92 I yes, so perhaps stored as a metafile or in a database.

**Comment by yaichenbaum** [comment]
I don't use tabs often but when I do, it's often with folders of the same name as well so this could be helpful. It's important to come up with a design that doesn't confuse users with the regular folder names.

An alternative solution would be to display the folders tag in the tab.

**Comment by yaira2** [comment]
What about using the tag name?

**Comment by yaira2** [comment]
@gave92 can we use ADS for this?

**Comment by gave92** [comment]
Potentially yes. Alternative is to use a DB where you store the custom name, the folder path and the folder ntfs ID (for in case the folder is moved/renamed).

**Comment by yaira2** [comment]
A database is probably better because it'll support non NTFS drives.

**Comment by yaira2** [comment]
@timluther are the custom names supposed to be for the directory or should the custom name stick even if you switch directories?

**Comment by yaira2** [comment]
@timluther fyi
