### ISSUE TITLE
Feature: Tab groups

### ISSUE THREAD

**Issue by timluther** [files-community/Files#9981]
### What feature or improvement do you think would benefit Files?

I would like to be able to bookmark particular sets of tabs and recall these quickly.

### Requirements

* Ability to save current set of tabs as a named tab group
* To be able to recall this tab group from a list of saved tab groups
* ability to replace current tabs with those form a saved tab group
* ability to append current tab group with those from a saved tab group

### Files Version

2.3.11.0

### Windows Version

Edition	Windows 10 Home Version	21H2 Installed on	‎14/‎05/‎2021 OS build	19044.1889 Experience	Windows Feature Experience Pack 120.2212.4180.0

**Comment by yaira2** [comment]
Merging with #11900
