### ISSUE TITLE
Bug: Shell extensions don't load for items in folders that end in .tar

### ISSUE THREAD

**Issue by cekkr** [files-community/Files#9994]
### Steps To Reproduce

1. Extract a `sample.tar.gz` archive using 7 zip
2. Open the extracted folder `sample.tar`
3. Right click on the `sample.gz` archive and see that shell items aren't loaded

### Steps to fix
- Display shell items as expected

### Files Version

Version: 2.3.11.0 

### Windows Version

OS Version: 10.0.22621.457

**Comment by cekkr** [comment]
Nada, I copied the files to a new directory and the problem returns. I attach my logs
[LocalState.zip](https://github.com/files-community/Files/files/9563139/LocalState.zip)

Thank you

**Comment by Josh-65** [comment]
You will need to upload the logs files directly to github. You can get them in files settings > about > open log folder.

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
This issue applies to any archive format (I think we have another issue tracking it)
