### ISSUE TITLE
Folder animation and font effect after clicked

### ISSUE THREAD

**Issue by thanosrbg** [files-community/Files#9995]
After clicking a folder or a file the font turns blurred... also the folder moves on the right when you click it... how can I turn it off?

**Comment by gave92** [comment]
Those are system animations. You can only turn animations off globally from Windows settings. Good news on windows 11 those animations are gone.

**Comment by karinayakimova** [comment]
Nothing changed after Settings - Show animations in Windows - OFF
Any workaround, please?
Win 10 PRO  1909

**Comment by Mario-Hofstaetter** [comment]
> Those are system animations. You can only turn animations off globally from Windows settings. Good news on windows 11 those animations are gone.

I have turned of animations in the windows system config app for a long time, but the described animations are present in Files 2.13.12

**Comment by Josh-65** [comment]
The next update to Files will remove them for the Windows 11 styles. You can see what there like in the preview builds https://files.community/download/preview

**Comment by thanosrbg** [comment]
Thanks for the preview it looks amazing nice job.
