### ISSUE TITLE
Thumbnails often have a black background

### ISSUE THREAD

**Issue by mswbol** [files-community/Files#9996]
### Description
![image](https://user-images.githubusercontent.com/46061868/190189362-f7b7cd9e-b961-4d64-8e35-f68f5505cae7.png)
![image](https://user-images.githubusercontent.com/46061868/190189547-ccbf1d05-6964-4cd3-8e7c-e62ed3954708.png)
![image](https://user-images.githubusercontent.com/46061868/190189630-9bcc98e7-9f99-4229-89f5-f7ae93a23cb0.png)
![image](https://user-images.githubusercontent.com/46061868/190189659-645e2aa6-5e34-44c6-9742-53fe4c329177.png)
![image](https://user-images.githubusercontent.com/46061868/190188110-4bb78399-2f9f-42e4-aa69-a521d26b4ba8.png)

### Steps To Reproduce

Appears after opening the tool

### Steps to fix

remove black background

### Files Version

版本: 2.3.11.0 OS Version: 10.0.22000.978

### Windows Version

Windows 11 21H2 22000.978

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9567444/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9567446/debug_fulltrust.log)

**Comment by gave92** [comment]
#6373
