### ISSUE TITLE
USB

### ISSUE THREAD

**Issue by Branca666** [files-community/Files#9998]
### Description

Al tener un pendrive o unidad extraible conectado al equipo, no se puede expulsar con seguridad mientras files esté abierto. Dice que el dispositivo está en uso.  La unica manera de expulsarlo con seguridad es cerrando Files 

### Steps To Reproduce

asd

### Steps to fix

asd

### Files Version

2.3.11.0

### Windows Version

Windows 10 Home 22H2 - Comp. 19045.2006 - Windows Feature Experience Pack 120.2212.4180.0

### Relevant Assets/Logs

asd

**Comment by Josh-65** [comment]
Merging with #9560
